### ISSUE TITLE
Smiley face in textarea option fields breaks the $atts array

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1001]
There seem to be some scaping problem I think.

When a smiley face ":-)" is written in a **textarea** field, the `$atts` array breaks.

**Comment by Ataurr** [comment]
I have also face the same issue few days ago this issue with ":"

**Comment by pe6o** [comment]
Sorry for the disturbing...

Is this fixed?

**Comment by moldcraft** [comment]
We haven't inspected this yet.

You can find the problem and submit a pull request.

**Comment by moldcraft** [comment]
https://core.trac.wordpress.org/ticket/36306#ticket

**Comment by moldcraft** [comment]
It will be fixed in [WP 4.6](https://core.trac.wordpress.org/ticket/36306#ticket)
