### ISSUE TITLE
Creating a custom page-builder item

### ISSUE THREAD

**Issue by c0sm1n87** [ThemeFuse/Unyson#1003]
I found #850 but it's not working. I duplicated the "Section" shortcode, changed its title / tab / description and left the type as it was ('section'). However, it does not show up in my shortcode list. If I remove this type I get a normal shortcode but not a page builder item.

PS: This is my directory structure:
https://www.dropbox.com/s/oud6h7az02nb9yw/saiph-parallax.zip?dl=0

**Comment by c0sm1n87** [comment]
I know probably @moldcraft is tied up with the backup (and the new unreasonable demands from themeforest) but anyone from the community has an idea on this ? :)

**Comment by llemurya** [comment]
@c0sm1n87 please watch this [video](https://youtu.be/sSE8A3w1mHQ) and say if it helps. I am waiting for your response.

**Comment by c0sm1n87** [comment]
hello @llemurya,

I don't want to override the default Section (this is already overriden and has lots of options attached to it), I am trying to create a new section type that has the same functionality (to be able to drop elements on top of it).

**Comment by llemurya** [comment]
@c0sm1n87 in our documentation is not described how to create an custom page builder item, but you can see in the code source how it is done and try to create your own item type, please begin with [this link](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php).

**Comment by c0sm1n87** [comment]
ok @llemurya , that's all I needed to know.

Regards!
