### ISSUE TITLE
How To Populate Page options, added from Front end

### ISSUE THREAD

**Issue by aamirs332** [ThemeFuse/Unyson#1005]
Hello, I need help. I am building an appointment application, i want to submit an  appointment from front end and when i added appointment from front end then i want to populate values on backend side.  Please see attachment

i added appointment from frontend
![appintment](https://cloud.githubusercontent.com/assets/5873187/11027760/48b55488-86da-11e5-860c-2be9d48d605a.png)

then i want to populate values  at backend side.

![backned](https://cloud.githubusercontent.com/assets/5873187/11027796/90c5e0ee-86da-11e5-8805-753cec91017d.png)

is it possible, if yes then how?
Please help me i am waiting your kind response?

Regards,

**Comment by duongancol** [comment]
Hope it helps: https://github.com/ThemeFuse/Unyson/issues/236

**Comment by aamirs332** [comment]
Thanks, for your kind response. i am doing. i will let you know if were still any issue there. :+1:
