### ISSUE TITLE
Page layout issue after installing bootstrap pluggin

### ISSUE THREAD

**Issue by EricDotCA** [ThemeFuse/Unyson#1008]
Hi, 
The design of the homepage was like this before installing pluggin
![desginunysonok](https://cloud.githubusercontent.com/assets/15738993/11042266/1a1e8342-86e4-11e5-95bd-95451d400f37.png)

and now look like this...
![desginunysonerrornow](https://cloud.githubusercontent.com/assets/15738993/11042265/1a1c6efe-86e4-11e5-969c-85b38318f066.png)

I know is not same text and picture, but it was same design with button!
![desginunysonpageeditor](https://cloud.githubusercontent.com/assets/15738993/11042344/857207cc-86e4-11e5-97ae-f31cf1b71ff6.png)

How i can fix it ? Because with the page builder i dont have access to  the code of the page.

Thx!

**Comment by alexluncashu** [comment]
Hi,
I installed the plugin and activated all settings. Tested on our own theme, nothing changed with layout. 
I want to know why you need such plugin? Can you describe more details, what theme do you use and what is the goal of this plugin?

**Comment by EricDotCA** [comment]
Hi,
I have use this plugin for use bootstrap css easier than actually.

The theme is http://themeforest.net/item/dentist-a-responsive-one-page-wordpress-theme/full_screen_preview/12242997

I have do custom pages without unyson page builder and when it have been done i have recheck my homepage and now it look like the previous picture. 

The colunm is unyson page builder doesnt work anymore.

**Comment by EricDotCA** [comment]
How i can fix that by doing it myself in html/css ? i can't find a way to do anything myself after using page builder.it only in one direction... from normal editor to unyson page builder but we can't never come back to the old school editor and keeping the design.

**Comment by EricDotCA** [comment]
I have  disable the  pluggin and everything is alright, so it the pluggin. Try the pluggin named "Bootstrap 3 Shortcodes"  https://fr.wordpress.org/plugins/bootstrap-3-shortcodes/

**Comment by alexluncashu** [comment]
Hi,
please manually download and update [Unyson-Shortcodes-Extension](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension) in `unyson/framework/extesnions/shortcodes`
Unyson shortcodes from your theme will be initialized later than Bootstrap shortcodes, and some of them from Bootstrap Plugin will be replaced with ours from Unyson, shortcodes like `row`, `column` `button` will be replaced because these shortcodes have the name collision.

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid
