### ISSUE TITLE
No content in fw-page-builder-content

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#1010]
Hi, on my live demo site I don't seem to be getting any content in the `fw-page-builder-content` div from the visual builder - http://demo.rocketshipthemes.co.uk/confetti/demo-1/

I've got the same set up locally in terms of plugins/themes. The live one above is on a multi site however, it was working and seems to have randomly stopped.

Has anyone had this issue before or know where I should start looking?

Cheers

**Comment by llemurya** [comment]
@martinburdon you have set `WP_DEBUG` to `true`?

**Comment by martinburdon** [comment]
@llemurya I have, nothing showing up though :/
