### ISSUE TITLE
Image Caption

### ISSUE THREAD

**Issue by databluegmbh** [ThemeFuse/Unyson#1011]
Hello, is it possible to use the Image Caption when i add a image with the Page Builder?

**Comment by alexluncashu** [comment]
Hi,
what exactly do you mean? Show image caption on frontend? This should be done by the theme. You can ovveride the default unyson shortcodes and customize it. Please read about this in our documentation http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes
