### ISSUE TITLE
W3C Validation errors on forms

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#1012]
Hello, ran my site through https://validator.w3.org/ and noticed I was getting a couple of errors around forms.
Is this an issue that ThemeForest pick up on? I heard they only accept sites that pass the validator.

Errors:
![image](https://cloud.githubusercontent.com/assets/4599099/11092096/5a640c8e-8878-11e5-871f-4e2c130906df.png)

**Comment by moldcraft** [comment]
This was fixed https://github.com/ThemeFuse/Unyson/commit/c81e682d0990bf6e317800496b127eb4f4d0bfb2
but we didn't made the release yet. We will make it in a few days

**Comment by moldcraft** [comment]
I will take a look at `<select type="select">`

**Comment by martinburdon** [comment]
Thanks :+1:

**Comment by martinburdon** [comment]
@moldcraft I've created a PR to fix the remaining `select` error: https://github.com/ThemeFuse/Unyson-Forms-Extension/pull/19
