### ISSUE TITLE
Multilanguage Plugin

### ISSUE THREAD

**Issue by Domes75** [ThemeFuse/Unyson#1014]
Hi there,

I am having many problems with a Wordpress page: www.atlantic-drive.com
Is one page template made with Unyson framework and I need to translate the page in 5 languages.
Now, q-translate, BWS and so on....none is working; it is like that the"box" from Unyson, are like layers going above or below the language settings: it keeps only one language.
The Dev is bouncing me to the plugin dev and the plugin dev to the theme dev...so, at the end, I am without translation.
Does somebody can help please?
Thank you in advance!

Domes

**Comment by Domes75** [comment]
Hi,

is anyone in there?

**Comment by llemurya** [comment]
@Domes75 our `Page Builder` is not compatible with `qTranslate`, If you want to translate pages, you can use `WPML`.

**Comment by albertso** [comment]
You should be able to use standard `[:]` `<!--: -->` qtranslate shortcodes in any text as long as the output is filtered for shortcodes. Try it with the Text Block:

    [:en]English Text[:de]Deutsch[:]

Or
    
    English TextDeutsch

In frontend, only text for the current language should be displayed.

In admin, dynamic language switching is not possible for shortcode options, but it's not that bad. You will have to get used to seeing all translations on the same textarea, but you have the advantadge you can translate parts selectively. Notice the closing [:], which allows you to "close" the current language, and continue writing text (or images) for all languages.

Are you using, [qtranslate-x](https://wordpress.org/plugins/qtranslate-x/)? It's the most updated version, the original plugin ceased development. Look here https://qtranslatexteam.wordpress.com/faq/

**Comment by Domes75** [comment]
Hi there,

thank you for your help. In that time I've moved to xili-translate and seems..seems fine; just needing some help for the menu and the front page. The other pages, I can get translated but they are not linked to the front page.. Hope xili support can help.
Alberto: I am newbie, I may understand what you mean, but I am a kind that need videos to understand, sorry!
 :)
