### ISSUE TITLE
Getting error when installing unyson extension

### ISSUE THREAD

**Issue by coderontheroad** [ThemeFuse/Unyson#1016]
I am getting error when installing unyson extension in local like that;

Failed to access Github repository "ThemeFuse/Unyson-Portfolio-Extension" releases.

How can i solve and how can i install extensions manually?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues?q=is%3Aissue+Failed+to+access+is%3Aclosed

->

https://github.com/ThemeFuse/Unyson/issues/957#issuecomment-150150341

----

Installing extensions manually is hard because they are nested and depend on each other.
