### ISSUE TITLE
Is Visual Editor active function?

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1017]
Hello, Team!
It is not an issue, just a question, is it possible to know in which editor the page was built, on front-end part? e.g. something like that:

``` 
// e.g. in /my-theme/page.php
if( is_unyson_visual_editor() ) {
    // page was built with Visual Editor
} else {
    // page was built with default WordPress editor
}
```

Thank you so much for your time!

**Comment by moldcraft** [comment]
Hello,
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/helpers.php
