### ISSUE TITLE
Help with inserting a post manually ( not through wp)

### ISSUE THREAD

**Issue by abadrahman** [ThemeFuse/Unyson#1018]
I am adding pages into wordpress through wp_insert_post and was wondering if there was any way I can add the content into the visual editor and place it in a section , column and a text block automatically.

I noticed in postmeta table there is fw_options and have tried to replicate this but all i am getting is content visible default editor and when i switch to visual editor there is a text block with the content but with the shortcodes visible.

Can you let me know if this is at all possible and if so what i am missing?

Thanks in advance

**Comment by moldcraft** [comment]
Post content is updated [here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/948cf3ae07e334504b68be6e2559e5fca43de4ec/class-fw-extension-page-builder.php#L193-L198).

Sorry I don't have time at the moment to investigate this and provide a solution. I will leave this issue open and someday it will be fixed.

**Comment by moldcraft** [comment]
1. Create a page with a builder structure you want for the pages created with `wp_insert_post()`
2. Use `fw_get_db_post_option($post_id)` to get all options and inspect the structure of `page-builder` array
3. After `wp_insert_post()` call `fw_set_db_post_option($post_id, null, $your_option_values)`
