### ISSUE TITLE
Specifying id and class names for a section

### ISSUE THREAD

**Issue by pierre0042** [ThemeFuse/Unyson#1019]
Hello,

Sorry if my request sounds stupid but I read a lot of your docs and didn't find the answer.
I want to use a "Section" shortcode from the Layout elements, it works fine but I also want to specify a precise name for the "id" and the "class" HTML attributes, to be set for the "section" element.
How could this be done properly?

Best regards,

**Comment by moldcraft** [comment]
Hello,

For id use [this solution](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head)

For class add a new text option in shortcode options.php

**Comment by pierre0042** [comment]
Thanks for your quick answer.
But I am not sure to see the link with my question ? 
I want to add an id attribute to the existing section element in the view.php file.

**Comment by moldcraft** [comment]
Have you tried to

* Overwrite section `options.php` and add your id option
* Overwrite section `view.php` and output that id value

?

http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes

**Comment by pierre0042** [comment]
That's what I am doing but I was wondering if it was possible without modifying the view.

**Comment by moldcraft** [comment]
It's not possible.

If you know a solution, please share.
