### ISSUE TITLE
404 after demo install

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#1021]
Hi. I have a concrete case. On GoDaddy, after theme install, when trying to import demo I am redirected to 404. I can give you guys login details.

Thanks.

**Comment by moldcraft** [comment]
Hello,
Which Backup extension are you using (old or [new](https://github.com/ThemeFuse/Unyson/issues/882#issuecomment-157424646)) ?

**Comment by darwinteam** [comment]
old one

**Comment by moldcraft** [comment]
Sorry, I am not familiar with the old version.
I will close all issues related to old version and just put a link to new version.
