### ISSUE TITLE
Error with new Backups

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1022]
Hi, I got this error when using the new Backup extensions to insall Demo Content from remote server 
```
We are currently installing your content.

Notice: Undefined index: filesize in /Volumes/Data/MAMP/miami/wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php on line 17
Downloading...
```

**Comment by moldcraft** [comment]
You have an old download script version on your server. Please follow [these instructions](http://manual.unyson.io/en/latest/extension/backups/#demos-on-remote-server) again.

**Comment by duongancol** [comment]
It still showed that error. Please check it.

**Comment by moldcraft** [comment]
We tested demo install a lot and everything works fine.

In your download script on the server, do you have [these lines](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/6fbce1322c6178e335760208566caef5ede12555/includes/module/tasks/type/download/type/piecemeal/server/index.php#L109-L111)?

**Comment by duongancol** [comment]
Yes, I have it: http://prntscr.com/946hql
It worked yesterday with the development version. 
But today I tried with the release version(Unyson 2.4.10). Downloaded from Plugin page, and go to Unyson page to download and activate the new Backup extensions.

**Comment by moldcraft** [comment]
Can you give me admin and ftp access? (send details to `moldcraft[at]email.com`)

**Comment by duongancol** [comment]
I tested on localhost so sent you my theme and FTP info. Let me know if you need other information. Thanks!

**Comment by moldcraft** [comment]
I don't see any notice and total download size is displayed

![s](https://static.md/c5bc574d5cb7a317c5f600388a39806c.png)

**Comment by duongancol** [comment]
I don't know why but now it works, just restart Mamp server. But my internet connection's quite slow. After 1 minute downloading, it showed this error: 
![screen shot 2015-11-19 at 8 16 57 am](https://cloud.githubusercontent.com/assets/1773011/11259670/174154ce-8e96-11e5-84f2-f2e4d7a98685.png)

**Comment by duongancol** [comment]
Hi @moldcraft , any idea?

**Comment by moldcraft** [comment]
> internet connection's quite slow

That's the answer.

The minimum size is [`1000000`](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/e84912c9fcb2b8c6f744c5bf0a2d11d3bcd1225f/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php#L50), you almost reached it `854047`.

----

The script works this way:

1. Try to download 3MB in [23 seconds](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/e84912c9fcb2b8c6f744c5bf0a2d11d3bcd1225f/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php#L131)
2. If it fails, try to download ([-1](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/e84912c9fcb2b8c6f744c5bf0a2d11d3bcd1225f/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php#L136)) 2MB in 23 seconds
3. If it fails, try to download 1Mb in 23 seconds
4. If it fails, abort and show the error

**Comment by danyj** [comment]
@moldcraft   since you base the downloads on download speed I suggest you add info about it than instead 

    Operation timed out... 

    Your download speed is slow. Operation timed out...



@duongancol ,  bud that is not slow , it is dead ( no offense ) ,  1mb 23 seconds ,  no one will wait 23 sec for that.

**Comment by danyj** [comment]
@duongancol   if you are downloading only 50mb  demo and your download is on   1mb/23  that is 19 minutes to download.

**Comment by duongancol** [comment]
Yes, I increased execution timeout of Mamp server. Thank guys!

**Comment by duongancol** [comment]
Hi what does this step do? http://prntscr.com/96cu0d
In my hosting, It's still loading and never stop. How can I debug it?

**Comment by moldcraft** [comment]
Please update the **Backup & Demo Content** extension. In your case will appear the **Cancel** link and you'll be able to stop the process.

Also there will be a red warning on the page with details why the install will not work.
