### ISSUE TITLE
Hooks documentation

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1023]
I'm looking for "hooks" documentation, I can't seem to find it anywhere.
The reason why I need this is because I'm trying to create a plugin that will add some additional options to theme options, and to the post type options.
So I'm gessing I will need some kind of hook do know when those options are being printed, so I can add mine.
I'm first time user of the framework, so maybe I'm going about this the wrong way, and there is simpler way to do this.

**Comment by moldcraft** [comment]
Sorry, we don't have a Hooks page in docs. Thank you for pointing this out.

----

* [Filter for theme settings options](https://github.com/ThemeFuse/Unyson/blob/bb969d7d3074d06aaf6459aca174f63636949e29/framework/core/components/theme.php#L86)
* [Filter for post options](https://github.com/ThemeFuse/Unyson/blob/bb969d7d3074d06aaf6459aca174f63636949e29/framework/core/components/theme.php#L116)

**Comment by ikixxx** [comment]
Is there any particular hook that I should wait for to start interacting with the framework?

**Comment by moldcraft** [comment]
Yes, [this](https://github.com/ThemeFuse/Unyson/blob/db4d5a36b81aa3b3bcb7c2ee6e3daa57686e5e91/framework/bootstrap.php#L94-L97)

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/hooks/index.html#contents
