### ISSUE TITLE
W3C validation blown away with Unyson 2.4.10

### ISSUE THREAD

**Issue by AvApsi** [ThemeFuse/Unyson#1025]
I think something went wrong in latest update, ran unyson website through https://validator.w3.org/

and got more than a handfull of w3c errors.  :) hope it helps you

**Comment by danyj** [comment]
That is custom theme not the framework itself. What particular errors are you talking about and how do you know that they come fro the framwork?

**Comment by AvApsi** [comment]
Just updated and they were there.

**Comment by AnitaStef** [comment]
Just updated...cannot get into dashboard...serious error!!! 
Please advise.

**Comment by moldcraft** [comment]
Please, more details, less emotions.

**Comment by AnitaStef** [comment]
Updated unyson...cannot get into dashboard or customize.

**Comment by moldcraft** [comment]
Why you can't get into dashboard?

**Comment by AnitaStef** [comment]
https://www.rummelintranet.com/wp-admin/ shows a Server error

**Comment by moldcraft** [comment]
Please set WP_DEBUG to true or give us the last lines from the apache error log

**Comment by AnitaStef** [comment]
I am not sure why...
https://www.rummelintranet.com/ 
opens
but when I try to go in as admin...it locks up
https://www.rummelintranet.com/wp-admin/

**Comment by AnitaStef** [comment]
I don't know how to set WP Debug...what and where is the apache error log?

**Comment by moldcraft** [comment]
https://codex.wordpress.org/WP_DEBUG

**Comment by AnitaStef** [comment]
I have to get into the site as admin to run WP Debug...correct? I am unable to get in as admin...unable to get in to the dashboard to see my theme>appearance>edit php files. I am not a developer...I am a wordpress user running woffice 1.4.8 and buddy press 2.4 and unyson...just updated...but an hour ago it was 2.4.10.

**Comment by danyj** [comment]
@2Fwebd  is the woffice developer and I am sure he will get in this asap.

**Comment by AnitaStef** [comment]
thank you

**Comment by danyj** [comment]
@AnitaStef  continue here please https://github.com/ThemeFuse/Unyson/issues/1026,  you hijacked @AvApsi  post

**Comment by moldcraft** [comment]
@AvApsi more details please (which errors, maybe a screenshot)

**Comment by danyj** [comment]
@moldcraft   

>  ran unyson website through https://validator.w3.org/


so far I understood he was talking about unyson.io check

**Comment by moldcraft** [comment]
oh, sorry

I thought he ran his site through https://validator.w3.org/

**Comment by c0sm1n87** [comment]
> Please, more details, less emotions.

Lol, I work with customers everyday, and I find this line priceless :+1:
