### ISSUE TITLE
Are empty arrays no more allowed in builder?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1027]
Not sure if this is connected to 2.4.10 update but when I add  column/section I can see my empty boxshadow array http://prntscr.com/94a1ts

but  when I save options modal  and reopen column/section options 
the empty array is gone

**Comment by danyj** [comment]
The same option type works fine in theme options

**Comment by danyj** [comment]
is this https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/152 ref to the above question ?

**Comment by moldcraft** [comment]
Sorry, I haven't inspected this issue.

We just notice that some shortcodes options are not saved.

**Comment by danyj** [comment]
ok il test

**Comment by danyj** [comment]
no is not  connected , still deleting the empty array

**Comment by danyj** [comment]
can you please check this if you have time. I need to find a solution so that I can continue. thnx!

**Comment by moldcraft** [comment]
How to reproduce this? Where/which options to add, where to make inspect element?

**Comment by danyj** [comment]
I need to check my options , did test like this now 


			'test_array' =>	array(
				'type'  => 'thz-test',
				'value' => array(
					'somearray'=> array()
				)
			),


and in test type view 


	fw_print($data);
	if(isset($option['value']['somearray'])){
	
		fw_print('I am here');	
		
	}


and it works fine , on save /open /close

will close this until done , if I cant fix it will reopen.
