### ISSUE TITLE
cast_sender.js error when using the media-video plugin

### ISSUE THREAD

**Issue by Alex-Ascet** [ThemeFuse/Unyson#1028]
Hi there,

I have got this JS error when using the media-video plugin (see attached).
Is it something we can fix? Thank you
![screen shot 2015-11-19 at 3 13 49 pm](https://cloud.githubusercontent.com/assets/12162252/11262189/567f5b38-8ed0-11e5-9d4c-5279809ba734.png)

**Comment by llemurya** [comment]
@Alex-Ascet the error is from your Chrome Extension not from Unyson, please uninstall your extension and the error will disapear.

**Comment by llemurya** [comment]
@Alex-Ascet please answer if the problem is from the chrome extension or describe more detailed how I can reproduce this bug when the Unyson is activated. I am waiting for your response.

**Comment by Alex-Ascet** [comment]
This error appears when I am using the media-video shortcode. Since I have changed it to this, all good:
```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$video = $atts['video'];
$frame = $atts['frame'];
$width = (int)$atts['width'];
$height = (int)$atts['height'];
$class = $atts['class'];

?>
<?php if(!empty($video)):?>
    <?php
        global $wp_embed;

        $width  = ( is_numeric( $width ) && ($width > 0 ) ) ? $width : '500';
        $height = ( is_numeric( $height ) && ( $height > 0 ) ) ? $height : '315';
        $iframe = $wp_embed->run_shortcode( '[embed  width="' . $width . '" height="' . $height . '"]' . trim( $video ) . '[/embed]' );
    ?>

    <div class="video-container">
        <?php echo do_shortcode($iframe);?>
    </div>
<?php endif;?>

<style>
.video-container {
    position: relative;
    padding-bottom: 56.25%;
    height: 0;
    overflow: hidden;
    box-shadow: black 0px 0px 50px 2px;
    margin-bottom: 30px;
}
 
.video-container iframe,
.video-container object,
.video-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
</style>
```

**Comment by Alex-Ascet** [comment]
No, sorry, I have got still the issue. Only when the media-video shortcode is active. Maybe you are right. It comes from Chrome (chromecast??)

**Comment by llemurya** [comment]
@Alex-Ascet what is the name of your chrome extension that you have installed?

**Comment by llemurya** [comment]
@Alex-Ascet seems that error is from Chrome , see this [issue](https://code.google.com/p/google-cast-sdk/issues/detail?id=309) .

**Comment by Alex-Ascet** [comment]
Indeed. Thank you for your time and your work on this awesome framework.
