### ISSUE TITLE
Cannot create temporary directory

### ISSUE THREAD

**Issue by rafeall** [ThemeFuse/Unyson#103]
I used your plugin and when download extensions it alert me this "Cannot create temporary directory: /home/u***********_/public_html/**_******/wp-content/plugins/unyson/tmp"
how can fix that?

**Comment by JustinGuese** [comment]
Warning: Cannot create directory "". It must be inside "/opt/bitnami/wordpress" or "/opt/bitnami/wordpress/wp-content" or "/opt/bitnami/wordpress/wp-content/plugins" or "/opt/bitnami/wordpress/wp-content/themes" in /bitnami/wordpress/wp-content/plugins/unyson/framework/helpers/class-fw-wp-filesystem.php on line 275
Cannot create temporary directory:
