### ISSUE TITLE
Looking for a hook to check for saved options.

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1030]
I'm trying to generate **css** via **sass** and **php**, and I need a hook or some other way to know when user saves the values, so if the values are changed I can fire up css generator and pass in new values.
How can I get a hold of the new and old values when user hits the save button?

**Comment by moldcraft** [comment]
* https://github.com/ThemeFuse/Unyson/blob/7b94dccd142dc473dc7ac52fa47706c411561f43/framework/core/components/backend.php#L1321
* https://github.com/ThemeFuse/Unyson/blob/7b94dccd142dc473dc7ac52fa47706c411561f43/framework/core/components/backend.php#L1310

**Comment by ikixxx** [comment]
Thank you. 
Since those actions are not in the documentation , are they future proof ? 
Can I consider them as a public API and fully rely on them ?

**Comment by moldcraft** [comment]
Yes.

We also use them in one of our themes to compile less.

**Comment by ikixxx** [comment]
Thanks :+1:
