### ISSUE TITLE
Content Install (V2) - Invalid Position error

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#1031]
I'm getting an error after content install - Invalid Position. What does this error mean or what could I be doing wrong here?

Thanks

**Comment by moldcraft** [comment]
It happens [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/463d370917e381d7b5e3d768fdcddfe586d07abd/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php#L149-L159).

Please replace

```php
__('Invalid position', 'fw')
```

with

```php
__('Invalid position', 'fw') .' '. $position .':'. $state['position']
```

and paste here the error message.

**Comment by martinburdon** [comment]
I think this could have actually been down to a wrong filename, however after fixing that I'm getting `Invalid src dir`.

**Comment by moldcraft** [comment]
> Invalid src dir

Your zip must contain

```
f/ (directory)
database.json.txt
```

not

```
my-demo-name/
    f/
    database.json.txt
```

**Comment by martinburdon** [comment]
Ah of course :+1: 
That's installing now however I am having an issue (on multisite) where some images aren't displaying.

This does however work on a non-multisite tested locally so it seems to be a multi site specific issue.

Is there any way around this?

Thanks

**Comment by moldcraft** [comment]
If you don't have [this piece of code](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/bd87407d667e2c177916eb2172d0d8cfb2e45f75/includes/module/tasks/type/class-fw-ext-backups-task-type-db-export.php#L115-L130) then you don't have installed the latest extension version. https://github.com/ThemeFuse/Unyson/issues/882#issuecomment-157804441

**Comment by martinburdon** [comment]
Thank you, I've got that sorted now.

One more issue I'm seeing is after the content install has executed, when going to a page the visual builder is not active, when activating it all shortcodes are places inside one Text Block shortcode instead of having all of the sections and shortcodes set out properly. Very odd, not seen it do this before.

**Comment by moldcraft** [comment]
Can you give me access to your site (admin and ftp) ? Because we can't reproduce this on our site (we tested it a lot and everything works fine)

**Comment by danyj** [comment]
@martinburdon send @moldcraft   login info  and  do us all a favor please and leave the text block and shortcode as is until @moldcraft  takes a look at it. we have been chasing this one for months now and no one was able to provide the actual look at it. all we seen so far was images.

**Comment by martinburdon** [comment]
Yeah no worries, where can I send the info?

**Comment by moldcraft** [comment]
`moldcraft(at)email.com`

But I will check it tomorrow.

**Comment by martinburdon** [comment]
Ok I will send the info.

I will leave the demo site with the issue as it is so you can inspect however I am going to try run it again but I will do it on a different site on the multisite network.

**Comment by moldcraft** [comment]
In your demo install, in `database.json.txt` on line 124 is [this postmeta](http://pastebin.com/qYzeJ6uX). I do `json_decode()` and I get [this](https://static.md/f3f92fac0e5a3fcaab0fd608c7e1ad27.png). Then when I do `unsersialize($s['data']['row']['meta_value'])` I get error

```
Notice: unserialize(): Error at offset 17828 of 63177 bytes in ...
```

On your site I executed this code

```php
add_action('fw_init', function(){
	fw_print(fw_get_db_post_option(2));
});
```

and it shows `false`, so the imported post has no `fw_options` post meta (which contains all data about builder).

I created a new page, added a button in builder and executed the same code for its id (btw `340`) and it displayed [this](https://static.md/26f0a5b855917bcfe4a143902b2baf76.png).

Now **I don't understand why that string fails to unserialize**. Any ideas?

**Comment by martinburdon** [comment]
If the builder extension was not enabled when the demo install package was generated could that cause this issue?

The reason I ask is I have had the backups v2 extension installed since last week then manually upgraded to 2.4.10, I then upgraded to 2.4.11 through the WP admin last night when it became available and I remember having to re-activate the builder extension at one point.

I'm thinking could I have been running my install without the builder extension active at some point and generated the demo content causing issues?

**Comment by moldcraft** [comment]
Page Builder extension doesn't matter, the builder was enabled for sure, look in that [postmeta](http://pastebin.com/qYzeJ6uX), at the end is `s:14:"builder_active";b:1;` which unserialized is `'builder_active' => true`. On import (db restore) the data fails to unserialize, that is the problem.

Why [this string](http://pastebin.com/MjpeWqy0) can't be [unserialized](https://www.functions-online.com/unserialize.html)?

**Comment by martinburdon** [comment]
The only thing I could think which would make this different to any other demo content is that my username and password was littered throughout it so I did a search and replace and changed it to a generic string. Could that cause issues?

**Comment by moldcraft** [comment]
If you changed it manually in that serialized string, sure, that is the problem. Serialized strings can't be changed easy manually, you need to unserialized, change, and serialize back.

Note that any serialized data is represented as 

```
{type}:{lenght}:{data};
```

when you change `{data}` you need to update the `{lenght}`

**Comment by martinburdon** [comment]
Ah right, ok. Thank you for looking into this.

So to replace my username and password I'm going to need to download the content install, unserialize it, edit it and serialize it back?

**Comment by moldcraft** [comment]
Why don't you set on your site with demo install everywhere a fake username and pass and just export?

**Comment by moldcraft** [comment]
Also I noticed that after demo import that page had ~200 revisions. Please read the green squares http://manual.unyson.io/en/latest/extension/backups/index.html#create-demos

**Comment by martinburdon** [comment]
Where is it I should be changing my username password? I attempted to create a new user a while back with the old backups extension and it still exported my other users details.
When looking at the mailer tab on my contact form shortcode there is no personal info added there. (Sorry if I'm missing something here)

**Comment by moldcraft** [comment]
As described in that "green box" in docs, you need to update all your contact forms, just press Save.

Also user details may be saved in revisions, that's why better exclude them.

**Comment by moldcraft** [comment]
> I attempted to create a new user a while back with the old backups extension and it still exported my other users details.

It doesn't matter with which user your are doing the export, the credentials are saved in post meta and don't depend on currently logged in user.

**Comment by martinburdon** [comment]
Ah thank you, I've managed to clear my revisions and get an export with dummy credentials.

I've re created my site locally (not multsite) and created a demo install, when trying to run it against my live site (multisite) I'm getting the error 'Cannot close the zip file'.

All I've done is export the site content, changed the name of the zip to match what I have set up and uploaded it to my server before running it. Any ideas what could be causing this?

**Comment by moldcraft** [comment]
> I'm getting the error 'Cannot close the zip file'.

Please (always) check apache error log, there should be a more detailed error message.

**Comment by martinburdon** [comment]
I don't know if these are the right logs (still hunting around) but I am seeing the following errors:
```
[Sat Nov 21 14:01:41 2015] [error] [client 82.23.80.67] File does not exist: /home/rocketsh/public_html/demo/404.shtml, referer: http://demo.rocketshipthemes.co.uk/confetti/demo-1/wp-admin/tools.php?page=fw-backups-demo-content
[Sat Nov 21 14:01:41 2015] [error] [client 82.23.80.67] File does not exist: /home/rocketsh/public_html/demo/favicon.ico, referer: http://demo.rocketshipthemes.co.uk/confetti/demo-1/wp-admin/tools.php?page=fw-backups-demo-content
```

**Comment by moldcraft** [comment]
Please send me an email with details how to access your site and reproduce the problem (also ftp access to debug the code)

**Comment by martinburdon** [comment]
I think I sent you details for both on Thursday night. If not I can send them over in about an hour when I get home. Cheers

To reproduce, just go to the content install page and hit install then wait for it to show the error.

Site is http://demo.rocketshipthemes.co.uk/confetti/demo-1/

**Comment by moldcraft** [comment]
ok, I will check within 2 days.

**Comment by martinburdon** [comment]
Thank you

**Comment by martinburdon** [comment]
I've sorted the issue, looks like it was down to low web space, looking into it I'm getting (a lot) less web space than I should be getting from my host so ticket opened with them.

Thanks for your help - time to get this theme submitted to ThemeForest :smile:

**Comment by moldcraft** [comment]
Check your Backup page, maybe there is big list of backups (on every Content Install, first, a Content Backup is created)
