### ISSUE TITLE
Call [0] and [1] option array

### ISSUE THREAD

**Issue by Alex-Ascet** [ThemeFuse/Unyson#1034]
Hi there,

Here is my options:
![screen shot 2015-11-20 at 11 16 06 am](https://cloud.githubusercontent.com/assets/12162252/11288443/24d4351a-8f78-11e5-999c-47608c894511.png)

I want to be able to exclude selected pages and posts from a sitemap.
How can I call these array [0] [1] etc.
![screen shot 2015-11-20 at 11 17 51 am](https://cloud.githubusercontent.com/assets/12162252/11288471/726f73b6-8f78-11e5-9b01-0869b22ebfe1.png)

To obtain this:
'exclude'      => '87,89,233' 

Here is my current test:
![screen shot 2015-11-20 at 11 20 31 am](https://cloud.githubusercontent.com/assets/12162252/11288509/c1c4f990-8f78-11e5-8838-c1214f82cda2.png)

Thank you for your support

**Comment by moldcraft** [comment]
```
implode(',', $values['page'])
```
