### ISSUE TITLE
Latest Update Hanging

### ISSUE THREAD

**Issue by splendidbob** [ThemeFuse/Unyson#1035]
Hi, trying to update to the latest version, and it is just hanging on 'updating'. 

Tried removing the plugin entirely and installing fresh from the repository and got:

"Unpacking the package…

Installing the plugin…

Could not copy file. /home/sitename/public_html/wp-content/plugins/unyson/framework/includes/option-types/upload/static/css/images-only.css"

plugin directories have been chmod to 755

**Comment by moldcraft** [comment]
The plugin update process is handled by WordPress, not by Unyson.

Try to delete Unyson and install it back. Check your folders permissions.

**Comment by splendidbob** [comment]
Yep, I tried that and got the above message. Plugin directory is set to 755. The Unyson directory and its files that have been installed after the failed installation all have 755. So for some reason its installing some of the files, and not others:

Upon attempting to activate plugin its giving the warning.

Warning: require(/home/sitename/public_html/wp-content/plugins/unyson/framework/bootstrap.php): failed to open stream: No such file or directory in /home/hairyhan/public_html/wp-content/plugins/unyson/unyson.php on line 28

Fatal error: require(): Failed opening required '/home/sitename/public_html/wp-content/plugins/unyson/framework/bootstrap.php' (include_path='.:/opt/php54/lib/php') in /home/hairyhan/public_html/wp-content/plugins/unyson/unyson.php on line 28

**Comment by moldcraft** [comment]
I am sure you have permissions problems on your server and it's not related to Unyson.

Also try to install/update other plugins.

**Comment by splendidbob** [comment]
All other plugins update fine

**Comment by splendidbob** [comment]
Unyson has always previously updated as well ;)

**Comment by splendidbob** [comment]
I will upload the files manually for now, but figured I should report it as perhaps other hosting configs might have the same problem.

**Comment by moldcraft** [comment]
Thank you for reporting, but I have no idea how to help.

**Comment by splendidbob** [comment]
Fair enough, thanks for your time anyway and work on this plugin :)

**Comment by moldcraft** [comment]
Thank you too, for using it
