### ISSUE TITLE
Question: option values are cached ? 

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1036]
After digging through the code, starting from **`fw_get_db_settings_option`**
Am I correct in assuming that getting the same option values won't have any negative performance, because they are cached when they are accessed the first time ?

**Comment by danyj** [comment]
first time without save ( on theme install )  they come from the options array that you made , 
after save they come from DB. 
http://manual.unyson.io/en/latest/helpers/php.html#database


Unyson cache does something else

http://manual.unyson.io/en/latest/helpers/php.html#cache

**Comment by moldcraft** [comment]
Yes, they are cached.

**Comment by ikixxx** [comment]
What I meant is that if I request the same option again, framework won't go to the database again to get it for me. It will return the value, from it's cache of already accessed values, or something like that.
