### ISSUE TITLE
HTML inside tooltips

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1037]
This would be a nice to have feature.

**Comment by danyj** [comment]
You can do it . Try in  help 

   &lt;br /&gt;&lt;br /&gt;

**Comment by moldcraft** [comment]
tooltips work work with html https://github.com/ThemeFuse/Scratch-Theme/blob/03e9e2afc0e6fa8bbb0039f321016d9b5ad15db8/scratch-parent/framework-customizations/theme/options/demo.php#L12-L17
