### ISSUE TITLE
place a custom shortcode in a specific html tags

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#1038]
place a custom shortcode in a specific html tags? it is possible? (eg. `<h2>[mycustomshortcode]</h2>` or `<div class="myclass">[mycustomshortcode]</div>` in editor when i click the shortcode button)

**Comment by moldcraft** [comment]
> place a custom shortcode in a specific html tags?

It should work, it depends where.

> in editor when i click the shortcode button

Can you give us a screenshot, where exactly and which shortcode are you trying to place

**Comment by moldcraft** [comment]
We recently released the **WordPress Shortcodes** extension. It allows you to insert Unyson shortcodes in any wp-editor
