### ISSUE TITLE
wp-editor option type in builder trows canvas error

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1039]
Since few days  when opening shortocde that contains wp-editor option type 
I get js errors

    Cannot read property 'canvas' of undefined

and 

    Deprecated TinyMCE API call: <target>.onChange.add(..)

http://prntscr.com/95rht3

**Comment by danyj** [comment]
this is sample option I use in accoriond, same for tab ad few other shortcodes



			'accordion_content' => array(
				'type' => 'wp-editor',
				'tinymce' => true,
				'size' => 'large',
				'reinit' => true,
				'wpautop' => false,
				'editor_height' => 100,
				'editor_type' => 'tinymce',
				'value' => 'This is dummy accordion text',
				'label' => __('Content', 'fw')
			)

**Comment by danyj** [comment]
this bug is still present in latest version

**Comment by llemurya** [comment]
@danyj do you mean `2.4.11` as latest version, or you downloaded direct from `github` and tested? Because in `2.4.11` this fix didn't exists, it will be in the next version.

**Comment by danyj** [comment]
I downloaded master several times since.

**Comment by danyj** [comment]
just compared the files , mine and your latest fix are same , so to confirm this is still there

**Comment by llemurya** [comment]
@danyj yes it persist in one case when you loading it as visual tab not html tab i will fix it.

**Comment by danyj** [comment]
error gone , thnx 

chrome notice still there 

    Deprecated TinyMCE API call: <target>.onChange.add(..)

but i think API is fault to that

**Comment by llemurya** [comment]
@danyj please test and  say if it works.

**Comment by danyj** [comment]
@llemurya works now bud , thnx
