### ISSUE TITLE
Need Help To add Flat Icons in Icon List.

### ISSUE THREAD

**Issue by aamirs332** [ThemeFuse/Unyson#1040]
Hello, i am facing some problem to include my flat icons  to list of font awesome icons list. is there any solution for that? I have flat icon css file as well, i want to show both font awesome and flat icon in the list. Please help me.

**Comment by aamirs332** [comment]
I want to be add New icon category as "Flat Icon". I have add icons according to this ticket : https://github.com/ThemeFuse/Unyson/issues/371, and its working . but i want to add new icons in  existing categories. Like i want to add more icons in medical category.

i have add this category code in my theme
function _filter_theme_new_icon_set($sets) {
    $sets['font-awesome'] = array(
        'font-style-src' => get_template_directory_uri().'/css/flaticon.css',
        'container-class' => 'fa-lg', // some fonts need special wrapper class to display properly
        'groups' => array(
			'flaticon' => __('Flat Icon', 'fw'),
        ),
        'icons' => array(
            // Flat Icons
			'glyph-icon flaticon-healthclinic2' => array('group' => 'flaticon'),
        ),
    );

    return $sets;
}
add_filter('fw_option_type_icon_sets', '_filter_theme_new_icon_set');


But its not working.

**Comment by moldcraft** [comment]
[You can't overwrite/change `font-awesome`](https://github.com/ThemeFuse/Unyson/blob/7b94dccd142dc473dc7ac52fa47706c411561f43/framework/includes/option-types/icon/class-fw-option-type-icon.php#L136-L137). Instead, create a new set, a copy of `font-awesome`

**Comment by aamirs332** [comment]
I have overwrite class-fw-option-type-icon.php in my theme Now both font awesome and flat icon are showing im theme list. 

Thanks :+1:

**Comment by moldcraft** [comment]
> I have overwrite class-fw-option-type-icon.php

I didn't meant that, I meant to create a new array key `$sets['font-awesome-and-flat']`.

But it's not a problem to create a new option type from your theme (if it's more convenient for you).

**Comment by aamirs332** [comment]
yes i got it. thanks :+1:
