### ISSUE TITLE
How to add js in admin per shortcode ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1041]
I need to add javascript file in admin that will do some things for icon-box shortcode
do I do this via theme/hooks.php   or  what file /snippet / action do we use in this case? 

for frontend   shortcode we use    

      shortcode_name /static.php

but what to I use for backend?

**Comment by danyj** [comment]
@moldcraft  thnx.  so I do the action in hooks.php or  can I run it from  shortcode_name /static.php ?

**Comment by moldcraft** [comment]
hooks.php

**Comment by Delishable** [comment]
I've been trying to get OFF the Unyson email list for months...can you  
help me?
Thanks!!
Bethany Lynn
bethany@delishable.net

**Comment by moldcraft** [comment]
@Delishable Press [this](https://static.md/d0708fa8a46f0df31b5213d0cc8cd1b8.png)
