### ISSUE TITLE
What event is fired on shortcode options open?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1042]
I am trying to hook in to the fw.OptionsModal  on open for any page builder shortcode and read the options.. 

Is there any way to do something like 

    icon_box_modal.on('open', function(modal, values) {....

**Comment by moldcraft** [comment]
Before opening the modal, execute in browser console

```javascript
fwEvents.debug(true);
```

----

Let me know if you'll need the same events from section and column.

**Comment by danyj** [comment]
God bless you my friend! I think we have 

      fw:page-builder:shortcode:column:controls

for columns but it would be great if they are all same . like suggested , idea is to get any shortcode 
option on open/close/change:values  like we already have   in  fw.OptionsModal. 

on to test what we have

**Comment by danyj** [comment]
perfect 

    http://prntscr.com/96dcpn

**Comment by danyj** [comment]
@moldcraft  I am guessing around here to get the options array , can you please advise what to use 

this one is not working 


		fwEvents.on('fw:builder-type:page-builder:item-type:simple:sub-type:icon_box:options-modal:open', function(data){
			
			console.log(data.modal.get('atts'));
			
		});


I also tried   

      data.modal.get('options')



in this one here I was able to get away with atts
https://github.com/ThemeFuse/Unyson/issues/950#issuecomment-157862058

**Comment by moldcraft** [comment]
> idea is to get any shortcode option on open/close/**change:values**

[Done](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/0a7e1a49978cc7a53480a279aedfd96d821c831f)

**Comment by moldcraft** [comment]
```
fwEvents.on('fw:builder-type:page-builder:item-type:simple:sub-type:button:options-modal:open', function(data){
    console.log(data);
});
```

see `modal.attributes` ... so `data.modal.get('values')`

**Comment by danyj** [comment]
thank you!, 


 something is off , 

I get options only when I save modal once , 
if I drop the icon box in builder and open , data object is empty 


			fwEvents.on('fw:builder-type:page-builder:item-type:simple:sub-type:icon_box:options-modal:open', function(data){
				
				
				var iconbox_options = data.modal.get('values');
				
				console.log(iconbox_options);

				
			});

http://prntscr.com/96dpvl

**Comment by moldcraft** [comment]
That is fine. The workflow:

1. Add element in builder (values unknown)
2. Open modal (values unknown)
3. Save (an ajax sends the form inputs and receives the option values)

**Comment by danyj** [comment]
hmm ,  well I need to hide a set of options and trigger some things on modal open, 
guess will have to look for option and val instead

**Comment by danyj** [comment]
this is the trouble 

I must do timeouts in order to find the value 


			fwEvents.on('fw:builder-type:page-builder:item-type:simple:sub-type:icon_box:options-modal:open', function(data){
				
				setTimeout(function (){
					
					var val =  $('.thz-apply-iconbox-link').val();
					if(val == 'title'){
						
						$('.thz-iconbox-button').hide();
						
					}else{
						
						$('.thz-iconbox-button').show();
						
					}					
					
				},1000);

				
			});

the  open , fires way to soon , it basically fires on click , not when the modal is completely open

look here please
http://screencast.com/t/ycCd5lQlrA

**Comment by moldcraft** [comment]
The open event is fired on actual modal open. What you are looking for is an event after:

1. Options render ajax finish, when the options html arrived from the server 
2. `fw:options:init` event, when the options were initialed

Please add `fwEvents.trigger('test-event');` [here](https://github.com/ThemeFuse/Unyson/blob/f53e756e29f6da1c33029ce72e18874702045d45/framework/static/js/fw.js#L624) and let me know if that is ok, then I will add a full event name there.

**Comment by danyj** [comment]
@moldcraft   that is the one!

http://screencast.com/t/m6ynYafIyhAu

let us get the options there,  call it loaded or something ,but that is the one.

**Comment by danyj** [comment]
@moldcraft , sec , I get 2   logs , one undefined second one with value  on first click with this 


			fwEvents.on('test-event', function(data){
				
				var val =  $('.thz-apply-iconbox-link').val();
				console.log(val);
				
			});

http://prntscr.com/96iguy

**Comment by danyj** [comment]
I can still do 

				if(val != undefined){
					console.log(val);
				}

but just making sure we in the right place before you do a commit.

**Comment by moldcraft** [comment]
I [added](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/9102adee19c21466589317c414cfccfc5cb5d7bc) the `...:options-modal:render` event. Please check if it's good

**Comment by danyj** [comment]
on it

**Comment by danyj** [comment]
that one works perfect for builder, 
do you mind adding this one also ?
https://github.com/ThemeFuse/Unyson/issues/1042#issuecomment-159311647

**Comment by moldcraft** [comment]
> do you mind adding this one also ? https://github.com/ThemeFuse/Unyson/issues/1042#issuecomment-159311647

That is what I just added. Please give more details

**Comment by danyj** [comment]
you added it for builder options modal not for fw.OptionsModal

https://github.com/ThemeFuse/Unyson/blob/f53e756e29f6da1c33029ce72e18874702045d45/framework/static/js/fw.js#L624

**Comment by danyj** [comment]
reason why is , in other scripts I us 

    modal =  fw.OptionsModal ....

and kinda doing same things and need to wait for modal to render

**Comment by danyj** [comment]
@moldcraft   thank you so much bud , this works so well and I dont have to mess with document click/change etc, everything is there on this event. 

P.S.  sections , columns , are you going  to enhance them with this ?

**Comment by moldcraft** [comment]
> P.S. sections , columns , are you going to enhance them with this ?

ok

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/b252381c283d26f069d287eb1dec477a1282236c

**Comment by danyj** [comment]
@moldcraft   ok , render works on that one , I get element via , 


			save_link_modal.on('render', function(e) {
				
				console.log(  $('.thz_find_url'));
				 self.ThzLinkSearch('.thz_find_url');
			});


but e  is undefined , shoulnd I be getting modal data there?

**Comment by moldcraft** [comment]
> sections , columns , are you going to enhance them with this ?

Done https://github.com/ThemeFuse/Unyson/issues/1042#ref-commit-1af76ff

Executed `fwEvents.debug(true)` in browser console to see the events.

> https://github.com/ThemeFuse/Unyson/issues/1042#issuecomment-159598456

inspecting...

**Comment by danyj** [comment]
awesome!
![i7tricj](https://cloud.githubusercontent.com/assets/2340172/11397817/950fc1d4-937c-11e5-84bd-f3bebd1fbe8c.png)

**Comment by danyj** [comment]
this one is from 

http://prntscr.com/96rckz

     var save_link_modal = new fw.OptionsModal({...

**Comment by moldcraft** [comment]
Everything seems to work fine.

```js
var modal = new fw.OptionsModal({'options':{'x':{type:'text'}}});
modal.on('render', function(){
    console.log(modal.content.$el.html());
});
```

![](https://static.md/6963312f68e25f4d33d1f4ad32293471.png)

Do you have the latest Unyson dev version?

**Comment by danyj** [comment]
sec , getting everything

**Comment by danyj** [comment]
Everything works! thank you!

**Comment by moldcraft** [comment]
As requested [here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/40#issuecomment-159685164), I changed event names: removed the `sub-type:{sub-type}` suffix

Now event name is 

```
'fw:builder-type:{builder-type}:item-type:{item-type}:option-modal:{action}'
```

but in event `data.shortcode` is the `sub-type` that was in event name, so you should do

```js
fwEvents.on('fw:builder-type:page-builder:item-type:simple:option-modal:render', function(){
    if (data.shortcode != 'icon_box') {
        return;
    }

    // do your stuff ...
});
```

**Comment by danyj** [comment]
thnx for advising

**Comment by danyj** [comment]
was this changed again ? 

this does not fire anymore 

    fwEvents.on('fw:builder-type:page-builder:item-type:simple:options-modal:render', function(data){

**Comment by danyj** [comment]
re downloaded  builder , works

**Comment by danyj** [comment]
and this does not work anymore

**Comment by moldcraft** [comment]
Please execute this in browser console

```
fwEvents.debug(true);
```

then open an options modal and see which events are triggered

**Comment by danyj** [comment]
http://prntscr.com/cd9xz7

before:open ,  used to be render https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/9102adee19c21466589317c414cfccfc5cb5d7bc

**Comment by moldcraft** [comment]
This is on my side when I open the Text Block shortcode

![screenshot from 2016-09-02 15-20-11](https://cloud.githubusercontent.com/assets/1475489/18203632/cf66dd54-7120-11e6-9dc8-099f91fd1843.png)

**Comment by danyj** [comment]
you right , render is there , http://prntscr.com/cdaesy

but not login anything

try this please 

https://github.com/ThemeFuse/Unyson/issues/1956#issuecomment-244299203

**Comment by moldcraft** [comment]
![](https://static.md/06646e0d53fb9174494aef7a61701fe9.png)

**Comment by danyj** [comment]
right, we used to get them before
