### ISSUE TITLE
Live Customizer and checkbox option.

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1044]
When I **deselect**  the checkbox in live preview customizer, in javascript, after parsing the JSON, I get a array with a single element.
![screenshot_00120151124 t](https://cloud.githubusercontent.com/assets/390700/11368396/d7bd0d8e-92b9-11e5-9ef4-e139806f8279.png)

However, when I do **select** the checkbox, after parsing JSON file, I get an array with two elements.
**New** value is at index `1`, and **old** value is at index `0`
It that how it supposed to work?
![screenshot_00220151124 t](https://cloud.githubusercontent.com/assets/390700/11368425/04dd7222-92ba-11e5-9e6f-b6b676d3f475.png)

**Comment by moldcraft** [comment]
[This](https://github.com/ThemeFuse/Unyson/blob/c08cdf32c5648a52b99086b1764a374bc9457a21/framework/includes/option-types/simple.php#L419-L420) was made to prevent [here](https://github.com/ThemeFuse/Unyson/blob/c08cdf32c5648a52b99086b1764a374bc9457a21/framework/includes/option-types/simple.php#L438) `null` value when the checkbox is not checked.

But I think it's possible to prevent double values in that json. I'll inspect this within a few hours.

**Comment by ikixxx** [comment]
Currently, some funky logic needs to be implemented in order to do live previews with checkbox.
@moldcraft Thanks for linking to the source. :+1:

**Comment by moldcraft** [comment]
[Fixed](https://github.com/ThemeFuse/Unyson/commit/f53e756e29f6da1c33029ce72e18874702045d45)

Please download the latest Unyson dev version from github.

**Comment by ikixxx** [comment]
:+1:
