### ISSUE TITLE
Responsive classes for Columns element

### ISSUE THREAD

**Issue by dobromir-hristov** [ThemeFuse/Unyson#1045]
So I know I can add options to the Column shortcode and get some basic responsive functionality like (small-12 medium-5 large-12) and so on, but I tried displaying those numbers in the back end  and it`s harder that I thought. I cant access the backbone function that is building the column elements, or so I think I cant.

I think this is a really useful feature as current websites are getting more and more mobile oriented.

I havent used the plugin in a while now (mainly because I dont use WP any more) and I got a bit rusty :)

**Comment by moldcraft** [comment]
[Here](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/v1.1.16/config.php#L13) is the grid. [Here](http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid) is how you can change it.

**Comment by dobromir-hristov** [comment]
I know how to change the classes... but I want to be able to put different classes for different breakpoints, like I said, on small to be 12, on medium be a 6 and large 12...
The upper mentioned methods just let me predefine some columns.

**Comment by moldcraft** [comment]
> on small to be 12, on medium be a 6 and large 12

`fw-col-sm-12 fw-col-md-6 fw-col-lg-12` ?

**Comment by dobromir-hristov** [comment]
OK let me put it like this :laughing: 
I want to be able to dynamically (From the builder it self) to setup different sizes on the columns without me being constrained to the list defined in the [config.php](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/v1.1.16/config.php#L13)
I did not want to show other products but this is VC`s approach. I dont want to be able to see it like them (would be good but thats not the point here), but to be able to set column widths for each device, like shown there - [responsive columns](http://vc.wpbakery.com/video-academy/responsive-column-control-width-offset-param-usage-explained/)

**Comment by moldcraft** [comment]
So you want to

![](https://static.md/2082fb89a1919ca3f192b567dd460f48.png)

?

**Comment by dobromir-hristov** [comment]
Here is what I mean. Being able to choose for different screen sizes different column sizes. I cant think of any way to make it more clear than this :( This will give allot of flexibility for column sizes.
![responsive](https://cloud.githubusercontent.com/assets/9863944/11396066/939b3414-9377-11e5-9baa-c7ea6da5b808.jpg)

**Comment by danyj** [comment]
if this is to be added  it should be optional , not everyone is using bootstrap or similar CSS frameworks in in frontend. and I think you are looking for something like this. 

![screenshot_23](https://cloud.githubusercontent.com/assets/2340172/11396210/449df7b8-9370-11e5-9689-92536e00d343.jpg)

**Comment by dobromir-hristov** [comment]
Ok sure, what ever floats your boat :D But the column ships with those classes.. so I don't know of anyone not writing a responsive website these days, but that's another topic, as long as there is some way to state what I said earlier i`m OK with that.

**Comment by danyj** [comment]
@dobromir-hristov  I am not talking about  responsiveness , but about the responsive classes names used , we cant force users to use maze of css classes no matter if that is FW , BS , Uikit etc. 

first thing I did when I started using unyson is change my frontend and my responsive layout is as simple as it gets http://fiddle.jshell.net/6Wb6W/8/show/light/  without to much hassle.

**Comment by dobromir-hristov** [comment]
But ofc.... I did as well.. I use Foundation, not bootstrap so I changed accordingly, so if I can change the config.php array with the classes, the users could as well. 
The classes I stated were just examples, but with the columns being shipped with a bootstrap css, it will be easy to use it out of the box.

**Comment by moldcraft** [comment]
It's complicated, width is used [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/8bd14e1c12a615694ae4baa91fac1b3359f30c6a/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php#L134-L138), [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/8bd14e1c12a615694ae4baa91fac1b3359f30c6a/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php#L175-L181), [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/8bd14e1c12a615694ae4baa91fac1b3359f30c6a/shortcodes/column/includes/page-builder-column-item/static/js/scripts.js#L98-L99) and output is [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/8bd14e1c12a615694ae4baa91fac1b3359f30c6a/shortcodes/column/views/view.php#L3)

In our case `width` is string, but in your case `width` should be array.

So better to copy/create your own `dobromir_column` shortcode with custom builder item and implement whatever functionality you want.

To disable default `column` shortcode, use [this filter](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#disabling-shortcodes)

**Comment by zenics** [comment]
I would like to get extra info on this as well any one figured it out?
