### ISSUE TITLE
Adding different column options as layout elements in page builder

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1047]
Hello,

Is it possible to create/add extra layout elements to the page builder?

For example: in a design for a website we use 12 columns (Bootstrap), and we would like to be able to choose 7/12, 1/12 and 4/12 as layout. To do that, we need to have extra layout elements. Because there are only 8 standard layout elements to choose from.

I hope this is possible, and you can show me how with an example or tutorial somewhere.

Thanks in advance!
-Kevin

**Comment by danyj** [comment]
Here is how to change default grid

https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/v1.1.16/config.php#L13

http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid
