### ISSUE TITLE
"Content Elements" is not sticky in Visual Page Builder

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1048]
As the title says, the "Content Elements" tab doesn't scroll down with the content editor page. No problem with the other two tabs though.

**Comment by moldcraft** [comment]
If the header height is bigger than half of the page height, the sticky function is disabled.

![](https://static.md/168e13f2532ec83554752717d8aedfff.png)

You can try to press `F11` (full screen), if it will have enought space, it will be sticky.

https://vid.me/TGqR

**Comment by pe6o** [comment]
Ah, that's smart. Thanks.
