### ISSUE TITLE
Color palette for color-picker

### ISSUE THREAD

**Issue by dobromir-hristov** [ThemeFuse/Unyson#1049]
So is there a way to set some defaults for color-picker option type? 
I saw that the palettes option on the JS init is set to true and thats that. Would love to set my main 3 or 4 colors and use only them instead of searching through the design for the HEX`s.
Thanks.

**Comment by danyj** [comment]
That should have been done here 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/static/js/scripts.js#L100

and here 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/color-picker/static/js/scripts.js#L58


like 

    palettes:['#ff6600','#ff0000']

**Comment by dobromir-hristov** [comment]
Yes I saw. Maybe the devs will look into it again ?

**Comment by danyj** [comment]
:+1:
