### ISSUE TITLE
Install/Manage extensions with composer

### ISSUE THREAD

**Issue by erralb** [ThemeFuse/Unyson#105]
Hi, this is kind of a feature request.

We use the Bedrock WP Stack, which allows us to manage plugins, themes and such, with composer.

How would you go about managing Unyson extensions with composer?

Where should the extensions be installed?

Can we just activate the extensions from the Unyson dashboard (like we do for the WP plugins) when the files/folders are already in place?

**Comment by roaldjap** [comment]
I am having the same issue and I'm currently on bedrock stack.

Just one question, if the extensions are placed in `unyson/framework/extensions/` does it automatically activate the plugin?

Thanks if someone is clearing this up. :)

**Comment by erralb** [comment]
Hi @roaldjap ,

In the end, we didn't find a proper way to manage Unyson extensions directly with composer, since any Unyson update will override its extensions folder.

What we did:

- We do manage Unyson with composer like any other plugin within the Bedrock stack. 
- Then we have a shell script that clones all Unyson extensions within the Unyson extension folder. 

It seems overkill at first, but in the end it's no big deal and then you have all extensions your current theme might require. [Here's the script.](https://gist.github.com/erralb/8b703019993e0726413518febc4fb48a)

All in all... We are trying to move away from Unyson since the project isn't active anymore, this should only be used for legacy projects.
