### ISSUE TITLE
Bulk get options

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1050]
If I have a setup like this:
```php
	$options['section_1']['options']['menu_colors'] = array(
		"title"   => 'Main menu colors',
		'options' => array(
			'main_nav_wrapper_color' => array(
				'type'  => 'rgba-color-picker',
				'value' => 'rgba(255,0,0,0.5)',
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __( 'Label', 'fw' ),
				'desc'  => __( 'Description', 'fw' ),
				'help'  => __( 'Help tip', 'fw' ),
			)
                     // more options
		)
	);
```
Is there a way to get all  the data in the options array, as array so I can iterate over them.

Ther will be a lot of color options, and getting them one by one, is not a optimal solution.

**Comment by moldcraft** [comment]
You can only get all option values from db if ([first parameter](https://github.com/ThemeFuse/Unyson/blob/b252381c283d26f069d287eb1dec477a1282236c/framework/helpers/database.php#L16)) option id is not specified. Then to iterate only over specific keys, do `array_intersect_key()`

**Comment by ikixxx** [comment]
I get it, thanks.

**Comment by ikixxx** [comment]
also , no performance issues for getting all the data, because if it was already requested , it will be cached ?

**Comment by moldcraft** [comment]
Yes, db results are cached.

*When I create a function that is meant to be called often, I always use cache.*
