### ISSUE TITLE
Post/Category image and text in megamenu

### ISSUE THREAD

**Issue by abuzer** [ThemeFuse/Unyson#1051]
Hello, 
I am new to Unyson. I have install the mega menu extension. I want to create menu like following screenshot. Please help.
![fajar](https://cloud.githubusercontent.com/assets/2954597/11430343/b40bc54e-94a6-11e5-83f7-8bea2b6f57df.png)

**Comment by moldcraft** [comment]
Hi,

You can overwrite the default walker and add custom options to menu items http://manual.unyson.io/en/latest/extension/megamenu/index.html
