### ISSUE TITLE
Color picker rgba value can't get to zero.

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1052]
I can't slide the opacity slider to 0. It can only go to 0.01 (tried with mouse and with arrow keys)
Also why two decimal spaces?

**Comment by danyj** [comment]
What does it add in the input when you let go ? 

Mine also shows 0.01  but when I let go it is 0 , 


http://prntscr.com/97ch99

**Comment by ikixxx** [comment]
No, it's always 0.01. I think I managed to get it to 0 only once when I was playing with it for two minutes.
Even when I use arrows, it won't let me go to zero, when I let go of the arrow, it just goes back to 1 on the indicator(dragging interface) and (0.01) in the value field.

**Comment by llemurya** [comment]
@ivandotv, @danyj  please test.
