### ISSUE TITLE
Is there a way to get values from specific option types?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1056]
I need to gather all  values from typography option types . It is used multiple time throughout the theme and builder.  Is there any way to select all of those without listing the id and display them in another option type view?

Something like 

     select all id's and values from typography option types 

Thing is I have a button shortcode and instead of again using typography option , I rather list the already available theme fonts and have the user choose font-family for the button from that list.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/069fc9cc0a8139c81af0dae275234af620d78c9e/tests/test-helpers.php#L188

```php
$options = fw()->theme->get_..._options();
$collected = $values = array();

fw_collect_options($collected, $options, array(
	'limit_option_types' => array('thz-typography'),
));

foreach ($collected as $option) {
    $values[ $option['id] ] = fw_get_db_..._option($option['id']);
}
```
