### ISSUE TITLE
Implementation of migrating data from fw_termmeta table to native termmeta table in coming WP 4.4? 

### ISSUE THREAD

**Issue by flanger777** [ThemeFuse/Unyson#1057]
I want to use unyson framework but for me important to use only native wp data tables. I know that in past wp hadn't a table for meta. But soon is will be changed as described here - https://make.wordpress.org/core/2015/09/22/preparing-your-plugins-and-your-client-sites-for-termmeta/ (already supported in wp 4.4 RC1). So my question is you will use fw_termmeta in next version of framework, or will make some migrating tool, to use native wp table? If yes when it will released?

**Comment by danyj** [comment]
@flanger777  from your post 
https://make.wordpress.org/core/2015/09/22/preparing-your-plugins-and-your-client-sites-for-termmeta/
I see this here 


>The best of these libraries will be unaffected by termmeta in core: they use prefixed functions, they store data in wp_options rather than a custom table, they use function_exists()

So far I know, Unyson is using prefixes everywhere and data is saved in wp_options table.. 

But @moldcraft  could also way in on this and let us know if there will be any issues.

**Comment by moldcraft** [comment]
> when it will released?

I also head about that, but we haven't investigated this.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1745
