### ISSUE TITLE
builder in theme option

### ISSUE THREAD

**Issue by aijazsiddique** [ThemeFuse/Unyson#1058]
I want to use builder in theme option 

can you please help me how can i use it

**Comment by moldcraft** [comment]
@danyj I remember you did something similar. Can you share if it worked and how you did that?

**Comment by danyj** [comment]
you need this  in theme options ( I made new tab with plenty of space ) 


        'builder_in_theme' => array(
            'label' => false,
            'type'  => 'page-builder'
        ),


and this in hooks.php

	// IF WE NEED PAGE BUILDER IN ADMIN
	function _action_admin_load_shortcodes_in_theme_settings() {
		if ( ! defined( 'FW' ) || fw_ext( 'shortcodes' ) == null ) {
			return;
		}
	
		fw_ext( 'shortcodes' )->load_shortcodes();
	}
	
	add_action( 'wp_loaded', '_action_admin_load_shortcodes_in_theme_settings' );

**Comment by danyj** [comment]
note that you cant have more than one https://github.com/ThemeFuse/Unyson/issues/487

**Comment by danyj** [comment]
@aijazsiddique  note that this will significantly slow down your theme admin , by about 3sec min depending on the server. Your best bet would be to make own option type with builder code and load specific shortcodes

**Comment by aijazsiddique** [comment]
thanks @danyj
