### ISSUE TITLE
ThemeFuse - Unyson Framework - improvement points

### ISSUE THREAD

**Issue by jatin846** [ThemeFuse/Unyson#1060]
Admin Branding with logo, background image
mostly themes giving inbuilt, but you have not notice this when you are build option panel framework

/wp-admin/ login url even rewrite if you can do it
www.domain.com/wp-admin/in list /wp-admin/ login url even rewrite if you can do it

I want to join Unyson Framework team
Myself, jatin gupta from india
I have notice many improve point giving you new sky height in wordpress lover world. I can also code for as designer/developer

Please revert asap, i can do anything to join themefuse - Unyson Framework

**Comment by moldcraft** [comment]
Thank you for suggestions.

You can help us by solving [issues](https://github.com/ThemeFuse/Unyson/issues). Pick one issue, investigate in carefully and find a solution. If it requires some code changes, submit a pull request.

**Comment by moldcraft** [comment]
At the moment your suggestions are minor improvements. We have a lot of issues to fix and don't have time for this. You can submit pull requests. Thanks
