### ISSUE TITLE
[option help] How to get _get_value_from_input with values only

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1061]
@moldcraft I am creating multi short text option type that display multiple short-text option types inline, 

![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/11501592/ba52ce6a-9835-11e5-8780-978b02fb1292.jpg)

this is how option is initiated 

			'counter' => array(
				'type' => 'thz-multi-text',
				'label' => __('Counter settings', 'fw'),
				'desc' => __('Setup your counter.', 'fw'),
				'value' => array(
					'count_from' => array(
						'value' => 0,
						'title' =>  __('Count from', 'fw'),
					),
					'count_to' => array(
						'value' => 103000,
						'title' =>  __('Count to', 'fw'),
					),

				)
			),

these are my defaults  and _get_value_from_input

	/**
	 * @internal
	 */
	protected function _get_value_from_input($option, $input_value)
	{
		if (!is_array($input_value)) {
			return $option['value'];
		}

		$value = $option['value'];

		foreach ($option['value'] as $key=> $val){
			
			if (isset($input_value[$key])) {
				$value[$key]['value'] = $input_value[$key];
			}
		}

		return $value;

	}

    /**
     * @internal
     */
    protected function _get_defaults()
    {

        return array(
            'value' => array(
				'mutlitextgroup' => array(
					'value' => '',
					'title' => 'Title',
				)
			),
			'groupname'=>''
        );
    }

and this is the render 

	foreach ($option['value'] as $key => $textgroup){
			
			
			$html = '<div class="thz-multi-text-holder">';
			$html .= '<span class="thz-multi-text-title">'.$textgroup['title'].'</span>';
			$html .=  fw()->backend->option_type( 'short-text' )->render(
				$key,
				array(
					'type'  => 'short-text',
					'value' => fw_akg($key.'/value', $option['value']),
					'attr'  => array(
						'data-thzmultitext' => $group_name
					)
				),
				array(
					'value' => fw_akg($key.'/value', $data['value']),
					'id_prefix' => $option['attr']['id'] .'-',
					'name_prefix' => $option['attr']['name'],
				)
			);
			$html .= '</div>';
			
			echo $html;
	
	}

the option works fine but thing is it returns the complete option in frontend
![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/11501660/2e262de6-9836-11e5-872e-0d41a1512e32.jpg)

and I would like to return values like   checkboxes option types 

if I return values only   in _get_value_from_input  than the options dont save. 

I tried mix of loops like this 

		if ( is_array( $input_value ) ) {
			$value = array();
			foreach ( $input_value as $key => $val ) {

				$value[$key] = $input_value[$key]['value'];
			}
		} else {
			$value = $option['value'];
		}
		return $value;

but cant get it to work right

**Comment by moldcraft** [comment]
```php
'value' => array(
    'count_from' => array(
        'value' => 0,
        'title' =>  __('Count from', 'fw'),
    ),
    'count_to' => array(
        'value' => 103000,
        'title' =>  __('Count to', 'fw'),
    ),
)
```

I don't like this at all, this is not db value, these are parameters/settings. Translated titles should not be saved in db. I would change it to

```php
'value' => array(
    'count_from' => 0,
    'count_to' => 103000,
)
```

`'value'` is what is saved in db. Create a separate key for parameters/settings, for example

```php
'inputs' => array(
    'count_from' => array(
        'value' => 0,
        'title' =>  __('Count from', 'fw'),
    ),
    'count_to' => array(
        'value' => 103000,
        'title' =>  __('Count to', 'fw'),
    ),
)
```

**Comment by danyj** [comment]
ok , I see what you mean ,  basically dont save the titles , but values only, thnx , makes sense

**Comment by danyj** [comment]
perfect, thnx!
