### ISSUE TITLE
Extensions shouldn't be allowed to update if at max_version

### ISSUE THREAD

**Issue by rawcreative** [ThemeFuse/Unyson#1062]
It has happened on quite a few occasions now where we have set a max_version for an extension either because we've had to make change or wanted to ensure compatibility, and in every case at some point we get a call/message from the client saying that something is broken or they're seeing a version message in the admin.

The updater should either not check for, or not allow extensions to be updated that have a max version defined if they are at that version, otherwise that setting is pointless. Since there is no way to install a specific version of an extension, if someone updates past the max_version and there is a conflict, there is no easy way to roll back to a previous version without lots of manual effort. 

The changes needed to the update extension are minimal (4 LOC) and I can submit a PR if requested.

**Comment by danyj** [comment]
:+1:

**Comment by moldcraft** [comment]
*To not forget: Also on extension install from Unyson page, should be downloaded/installed max_version, not the latest version.*

**Comment by moldcraft** [comment]
Please submit a PR. I don't know when I will start to work on this issue
