### ISSUE TITLE
Bulk get customizer options

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1067]
I've tried getting all the customizer options via ` fw_get_db_customizer_option`, however I do get back all the options, but they are not nested in sections, as created in the `options` array.
I get back an array one level deep with all the options as **key**=> **value** pairs.
I thought that I will get back the same structure as when using `fw_get_db_settings_option`
As explained here #1050

**Comment by moldcraft** [comment]
All Unyson options are saved in db as one level array `option_id => option_value`. It doesn't matter in which container the option is located (box, tab, box > tab > box, etc.)

Each customizer option has it's own [setting](https://codex.wordpress.org/Theme_Customization_API#Adding_a_New_Setting) (own key in db)
