### ISSUE TITLE
Where are things?

### ISSUE THREAD

**Issue by dowlass** [ThemeFuse/Unyson#1068]
I've activated page builder, styling and sidebars in my Unyson installation in Wordpress (4.3.1)

But where are these functions? They seem to be neither in the WP admin, nor in the front end user page.

What am I supposed to be seeing and where?

Thanks

**Comment by danyj** [comment]
go to   Pages > Add New 

click on the button   " Visual page builder" 

![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/11541957/64e77844-9935-11e5-8c3c-c922e782642e.jpg)

**Comment by dowlass** [comment]
Yep....but where are the 'sidebar' and 'styling' functions which I have activated.....these are not evident in the visual page builder (which seems to be a layout function)

**Comment by danyj** [comment]
sidebar is in widgets  ,  right bottom , style I think is about to get obsolete and I never used it 
https://github.com/ThemeFuse/Unyson/issues/874

**Comment by dowlass** [comment]
thx re sidebar - assume it's the 'sidebar manager' bit, then? - very divorced and distant from the page builder, doesn't seem natural.

"style I think is about to get obsolete and I never used it "... hmmm!  So really we're all over the place with this and no one knows where stuff is!

**Comment by danyj** [comment]
bud , I am not Unyson dev , just trying to help you out , 
Unyson is  not all over the place , you need to understand that this is a framework with limitless possibilities and I suggest you start here http://manual.unyson.io/en/latest/

**Comment by dowlass** [comment]
fair enough, Dan, thanks for the help.
I'm just saying that it's not intuitive - it's like you see these functions apparently active in your unyson install..but they're not grouped together in one logical place. I'll do some reading, just thought it might be a bit more obvious and 'visible' where things are! cheers

**Comment by moldcraft** [comment]
![](https://static.md/e006f69782b6e96a0b05145f12cbb035.png)

**Comment by dowlass** [comment]
"moldcraft closed this 4 hours ago"

??

**Comment by moldcraft** [comment]
We placed link on extension titles (where it's possible) that gets you to the page where that extension have its functionality

![](https://static.md/13ed46cc3db0c875c2f8ac6276dc5c8c.png)

> thx re sidebar - assume it's the 'sidebar manager' bit, then? - very divorced and distant from the page builder, doesn't seem natural.

It is how it is. 

![](https://static.md/902296872413a8851e716653af741555.png)

If you have a better idea how it can be made, you can share all details (how it should work and look) and maybe, one day, we will create v2 (or a separate extension)

**Comment by dowlass** [comment]
Aha! OK.  Sorry, I didn't really see that word 'Sidebars' as a link - apart from Sidebars I've only got PageBuilder and Styling extensions at the moment, and they're black and not links...I didn't notice that Sidebars was blue and a link.

There may be good structural reasons for the Sidebars function being on the sidebars widget page - and maybe even constraints of how Wordpress works meaning that it has to be there.  

I guess I just see, as both a viewer and a user, a 'page' as being everything a viewer sees...header, image/slider, menu, main content, sidebar content.....I just see it all as being "part of the page".  So when I see the link 'Visual Page Builder' I'm just expecting, rightly or wrong, to see tools for those functionalities within the page builder....not just tools for the central bit of content.  That's my way of looking at it. To be honest I don't see Wordpress itself as super-intuitive, either; but I've kind of got used to it!  Just thought that a Visual Page Builder was a great opportunity for someone to collect all the true page building tools together in one window.

My penn'orth!

**Comment by moldcraft** [comment]
Thank you.

You should definitely check and monitor the development of [Calypso](https://github.com/ThemeFuse/Unyson/issues/1066), and make sure in the "new WordPress admin" will be no (same) mistakes (criticize them, share your ideas about what can be improved/implemented)

**Comment by dowlass** [comment]
thx, I may well take a look at that.

Back to the present, though, and an earlier question in this thread....what or where are the 'styling' extension functions?  I've loaded the extension - what does it do and where?

**Comment by moldcraft** [comment]
By default it is hidden, because without configuration/integration with theme it does nothing, so it will be visible only if theme developer integrated it with theme and added in `$manifest['supported_extensions']` ([manifest docs](http://manual.unyson.io/en/latest/manifest/theme.html#content))

It looks like [this](https://static.md/1047037f64d70e51808c8144a4ce2820.png) and contains options related only to theme style (colors, fonts, etc.) But very few used it (because similar options are added in Theme Settings page, or Customizer options, and the Styling page becomes useless/inconvenient) and we [soft removed it from the extensions list](https://github.com/ThemeFuse/Unyson/issues/874) (also the page from docs was deleted)

**Comment by dowlass** [comment]
uhuh, right, understood.  Guess I'm just curious how I could select and load an extension without seeing anything!  (I only downloaded and installed Unyson a few days ago).  No worries, though, at least I know what's going on! Thx
