### ISSUE TITLE
Add custom extension from plugin

### ISSUE THREAD

**Issue by braginteractive** [ThemeFuse/Unyson#107]
Anyway to add extensions from a custom plugin? 

For example:
If you create a custom shortcode for page builder that you would like to use in several different themes it would be easier to manage in a custom plugin rather than than adding it to every theme in /framework-customizations/extensions/

This would also allow people to share different custom extensions that are created.

**Comment by thednp** [comment]
So is this thing possible with 2.5.0 or I'm wasting time trying to do the impossible?

**Comment by thednp** [comment]
Hey @braginteractive check out this [short tutorial](https://github.com/ThemeFuse/Unyson/issues/1407). Might be helpful.
