### ISSUE TITLE
Do I need prefix for options?

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1070]
If I have two themes using unyson framework, and after I switch the theme, new theme will pick up options from the database from the previous theme. 
I don't see anywhere in the documentation where I could set a prefix for the options, so they are different for every theme.

**Comment by danyj** [comment]
options are saved with theme name suffix 


     fw_theme_settings_options:scratch

https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/helpers/database.php#L18

**Comment by ikixxx** [comment]
Ah, yes, I was having issues with customizer options,  and thought that this is the problem.
