### ISSUE TITLE
Accordion shortcode

### ISSUE THREAD

**Issue by AndyMinnie** [ThemeFuse/Unyson#1071]
Hi there!

I would like to use the accordion's shortcode in a page template.
To do so, I'd like to use the function do_shortcode(...). So far I have the following code:

```php
$tabs_array = array(
array('tab_title' => 'TEST','tab_content' => 'Content 1'),
array('tab_title' => 'TEST','tab_content' => 'Content 2'),
array('tab_title' => 'TEST','tab_content' => 'Content 3')
);
$tabs_json = json_encode($tabs_array);

echo do_shortcode('[accordion tabs="'.$tabs_json.'" ][/accordion]');
```

But this isn't working, can you help me?

Thanks! :-)

**Comment by danyj** [comment]
why dont you create page with your page template selected and use builder ?

**Comment by AndyMinnie** [comment]
I am making a custom page template in php, the content of the tabs will change regarding some parameters defined by the user.
That's why I can't use the page builder and I need the shortcode. :-)

**Comment by danyj** [comment]
I am not sure if that will work since shortcodes are bound to builder but lets see what @moldcraft says.

**Comment by duongancol** [comment]
why don't you use page meta box for page tempalte? I think it's better choice.

**Comment by AndyMinnie** [comment]
I can't use this.
To be more specific, my page template has a search form in the front end where the user can put any words he wants.
Then I'd like the results of the search to be display in an accordion regarding the category of results.

**Comment by moldcraft** [comment]
```php
$atts = array(
	'tabs' => array(
		array('tab_title' => 'TEST', 'tab_content' => 'Content 1'),
		array('tab_title' => 'TEST', 'tab_content' => 'Content 2'),
		array('tab_title' => 'TEST', 'tab_content' => 'Content 3'),
	),
);

/**
 * @var FW_Extension_Shortcodes $shortcodes_extension
 */
$shortcodes_extension = fw_ext('shortcodes');

/**
 * @var FW_Ext_Shortcodes_Attr_Coder_JSON $coder
 */
$coder = $shortcodes_extension->get_attr_coder('json');

$encoded_atts = $coder->encode($atts,
	'', 0 // these 2 arguments are not used by json coder
);

$tag = '[accordion '. implode(' ', array_map(
	create_function('$v,$z', 'return $v .\'="\'. $z .\'"\';'),
	array_keys($encoded_atts), $encoded_atts
)) .' ][/accordion]';

fw_print($tag, do_shortcode($tag));
```
