### ISSUE TITLE
Form Builder AJAX validation error wrong position

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1072]
Hello, guys!

Just want to report a bug: an error message for "Multiple choices" form builder element appears in wrong place (at form's top instead of bottom of element), please see a screenshot

https://yadi.sk/i/OB2HTr3wkvryY

**Comment by moldcraft** [comment]
Which theme are you using?

**Comment by WPJobs** [comment]
Thank you for a fast response!
Currently i'm developing a new theme, and it contains only basic typography css styles

**Comment by moldcraft** [comment]
I made [this fix](https://github.com/ThemeFuse/Unyson/commit/cfd020c7283414bf748c34eb142d26eeb84a44be) it will be included in the next Unyson release.

**Comment by WPJobs** [comment]
Thank you so much, you are the best, as always!
