### ISSUE TITLE
Extension displays only one element attributes

### ISSUE THREAD

**Issue by Eynsteyn** [ThemeFuse/Unyson#1073]
When I add two same content elements on the page, in output (var_dump($atts))  is only the first element's data
How to solve this problem?

**Comment by moldcraft** [comment]
How to reproduce this? (the exact steps)

**Comment by Eynsteyn** [comment]
I add one element to the page.
Then I duplicate it.
They contain different data. (
element1 { 
["title"]=> "1 title" 
["description"]=> "1 description" 
["service_icon"]=> "fa fa-500px"
 })

element2 { 
["title"]=> "2 title" 
["description"]=> "2 description" 
["service_icon"]=> "fa fa-instagram"
 }
)

Then I do var_dump (atts) on view.php
In output is only the element1 data

**Comment by moldcraft** [comment]
I can't reproduce the problem https://vid.me/i1tn

*I uses this shortcode [shortcodes/demo-two/views/view.php](https://github.com/ThemeFuse/Scratch-Theme/blob/598bd8f5b9f2c4160df5c3ae761f8253225e0cc3/scratch-parent/framework-customizations/extensions/shortcodes/shortcodes/demo-two/views/view.php#L6)*
