### ISSUE TITLE
Extensions not getting installed. 

### ISSUE THREAD

**Issue by sunnyville** [ThemeFuse/Unyson#1074]
Hello, 

I'm creating a theme in which I have enabled the Page Builder and Shortcodes Extensions in the manifest.php file. But for some reason when I click to Install these extensions from this page:
![untitled](https://cloud.githubusercontent.com/assets/9170034/11569583/23597c06-9a0c-11e5-95d0-9e8827295279.png)

I get the following errors and the extensions don't get installed.

![errors1](https://cloud.githubusercontent.com/assets/9170034/11569613/460d0c40-9a0c-11e5-86d1-8d4e5009b843.png)
![errors2](https://cloud.githubusercontent.com/assets/9170034/11569622/4ca887a0-9a0c-11e5-8013-f406c2ad1032.png)

I'm using WordPress 4.3.1, Wamp 2.5 and Windows 10. I've also tried this on Xampp and getting similar errors.

Please let me know about this and thanks!

Edit: I believe it is the Builder extension that is having a problem getting installed. Since this is what I get when I try to Activate the Page Builder extension from this page:
![error3](https://cloud.githubusercontent.com/assets/9170034/11569773/1ed3db6c-9a0d-11e5-8501-e05c1b43696e.png)

**Comment by moldcraft** [comment]
I deleted everything from `unyson/framework/extensions/`. 
Added in `{theme}/framework-customizations/theme/manifest.php`

```php
$manifest['supported_extensions'] = array(
	'page-builder' => array(),
	'shortcodes' => array(),
);
```

Then deactivated Unyson plugin, activated it and I was redirected to [install compatible extensions](https://static.md/007e28db2356b55d14899618993415b5.png) and the installation [went fine](https://static.md/f67588860c23fa44c0b14c570d22e29e.png)

*I am on Ubuntu/Linux.*

We will try to reproduce this on a Windows machine.

**Comment by sunnyville** [comment]
I also just tested this on Ubuntu/Linux and it worked fine. I believe it may be a problem in Windows and possibly only Windows 10, as I have used Unyson in the past on Windows 7 and never got any such problem.

Thanks!

**Comment by danyj** [comment]
I am on win 10  wamp  php 5.4 , and IOS macbook pro xamp no issues at all
cannot move error tells me that the folders are locked somehow or you as a user have no access to it.

**Comment by sunnyville** [comment]
Thanks danyj, I turned off my Anti-Virus and now I don't have the problem.

Thanks and sorry for the trouble.

**Comment by premalk** [comment]
Hi. I have solved this problem. go to wp-content/plugin/unson/framework/helpers. Open class-fw-wp-filesystem.php.

find return $relative_path; 
If you get that then change it by return $base_wp_filesystem_path . $relative_path;
If you still get this error then deactivate all plugins and install extension again. It will work. 
It is about the problem of other file. 

Thank you.
