### ISSUE TITLE
[info] Core auto install failing

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1075]
@moldcraft  Congrats on the new theme but heads up , on the demo the autoinstall is not working. 
I had the install page opened for about 30min and it never installed the demo.

**Comment by moldcraft** [comment]
More details please (screenshots)

**Comment by danyj** [comment]
I closed it ,  installed core in labs , went to autoinstall , installed full demo . that was few hours ago 
now Installed Quantum  and  it works , so that autoinstall might be something else

**Comment by danyj** [comment]
And when I refreshed admin now the Autoinstall menu link is gone

**Comment by danyj** [comment]
let me try another email , will reply

**Comment by danyj** [comment]
here we go 

![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/11573282/bd7ca4ea-9a05-11e5-8da5-82576e32fdfb.jpg)


than it stays here 

![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/11573287/c5035254-9a05-11e5-904e-3e4d5966fc3d.jpg)


currently testing in FF ,  that page is not doing anything , not moving spinning etc...

**Comment by danyj** [comment]
ajax hangs 

![screenshot_6](https://cloud.githubusercontent.com/assets/2340172/11573335/03717020-9a06-11e5-804b-66812729f9c4.jpg)

**Comment by danyj** [comment]
this is the line 

![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/11573352/1cf02cda-9a06-11e5-942f-1abcd4d7e02d.jpg)

**Comment by danyj** [comment]
the response

![screenshot_8](https://cloud.githubusercontent.com/assets/2340172/11573380/4c4a65b8-9a06-11e5-83c3-7f58ff452291.jpg)

**Comment by moldcraft** [comment]
AutoInstall is a separate/standalone script, it's not part of Backups extension (Demo Content Install).

**Comment by danyj** [comment]
understand that , but demos and install demo are not visible until that auto install is finished 
![screenshot_9](https://cloud.githubusercontent.com/assets/2340172/11573532/20cf8598-9a07-11e5-9ef9-b3609d192174.jpg)

so who ever wants to test your theme via lab will not be able to do so

**Comment by danyj** [comment]
bad link  http://demo.themefuse.com/new-the-core2/menu/  here 

http://prntscr.com/9a09tq

**Comment by danyj** [comment]
actual all permalinks on that page are 404

**Comment by llemurya** [comment]
@danyj `auto-setup` is an extension for `Themefuse` what is not used in `Unyson` the bug was fixed.Thanks for the feedback.
