### ISSUE TITLE
Resetting options via code , particularly customizer data

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1078]
I know there has been some discussion about this #576 
But I'm wondering if there is a way to remove all the data in the database, without going to database and doing it manually?

something like:
````php
FW_WP_Option::set('','','');
````

**Comment by moldcraft** [comment]
All Unyson customizer options are [registered](https://github.com/ThemeFuse/Unyson/blob/v2.4.11/framework/core/components/backend.php#L2023) as [WP Customizer Settings](https://codex.wordpress.org/Theme_Customization_API#Part_1:_Defining_Settings.2C_Controls.2C_Etc.) and stored in [theme mods](https://codex.wordpress.org/Function_Reference/get_theme_mod) as sub-key of `fw_options` key, `fw_options[option_id]` ([code](https://github.com/ThemeFuse/Unyson/blob/v2.4.11/framework/core/components/backend.php#L1985)).

So try to remove them with [`remove_theme_mod('fw_options')`](https://codex.wordpress.org/Function_Reference/remove_theme_mod). 

*I haven't tested that, if it will work, please close this issue.*

**Comment by ikixxx** [comment]
it works :+1:
