### ISSUE TITLE
Add font to typography option?

### ISSUE THREAD

**Issue by shankat** [ThemeFuse/Unyson#1079]
Is there any way to add a new font to the typography option (not a google font)? Uses @font-face.

Thanks!

**Comment by llemurya** [comment]
@shankat I think you speak about `typography-v2 option type` in this option type exists an filter `fw_option_type_typography_v2_standard_fonts` you can hook in it and add your fonts. You can see it in the [source code](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php#L54).Hope this helps.

**Comment by shankat** [comment]
Yes..thank you, that helped!
