### ISSUE TITLE
Slider is buggy

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1080]
Clicking on the slider bar moves the knob, but the value inside the know is not updated (both visually and in code), so in customizer live updates don't work.
I'm required to click three times on the slider bar in order to get the value updated.
First click. moves the knob ( value not updated)
Second click (on the knob) value is updated visually.
Third click, value is updated in code ( and customizer picks it up and live update is done)

Note that dragging the knob works correctly, value in code is updated when the know is released.

**Comment by llemurya** [comment]
@ikixxx can you please make some screenshots or an screen cast to understand clearly how to reproduce this issue.Thanks.

**Comment by ikixxx** [comment]
Here you go.
![](http://i.imgur.com/w1jU6LP.gif)

Note that on **second** click , value is update on the slider but only visually , code is not updated, and live preview in customizer is also not updates. We need three clicks in order for evertything to be updated.

**Comment by llemurya** [comment]
@ikixxx thanks for the feedback we will investigate and fix this issue.
