### ISSUE TITLE
Feature request : Image upload with url to the image.

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1081]
I'm using `upload` option inside the customizer, to change the image.
I want as soon as the user chooses the image, to get back the url to a medium sized image ( image size could be optional)

Currently with `upload` option I get an image id, and I have to issue an ajax request to get back the url for that image.
It would be nice if this could be somehow automated.

**Comment by llemurya** [comment]
@ikixxx please read our documentation about [upload option type](http://manual.unyson.io/en/latest/options/built-in-option-types.html?highlight=upload#upload) we save the `attachment_id` and the `url` of the image.

**Comment by ikixxx** [comment]
I've read the documentation, this is not what I get when doing live updates with customizer.
I'm using `postMessage` as transport layer.
````php
'logo_main'           => array(
'type'        => 'upload',
'label'       => __( 'Main logo image', '' ),
'desc'        => __( 'Image that will represent logo in the main menu' ),
'help'        => __( 'Maximum width that will be displayed is 100px.', '' ),
'images_only' => true
						)
````
javascript
````javascript
    wp.customize('fw_options[logo_main]', function (value) {
        value.bind(function (newVal) {

            var data = JSON.parse(newVal);
            debugger;
        });
    });

````
console:

![screenshot_00120151204 t](https://cloud.githubusercontent.com/assets/390700/11601343/db5d3fce-9ad2-11e5-8e14-93f1bdd691e9.png)

**Comment by ikixxx** [comment]
If would be really nice if we could update the images live in the customizer, without the site reload.
 I'm guessing the user expects that since default Worpdress themes support that.

**Comment by danyj** [comment]
@llemurya  works now bud , thnx

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1309
