### ISSUE TITLE
active_callback option for customizer.

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1082]
Is there any way to leverage that kind of functionality ? 
Basically if the site is not using a sidebar, there is no need to show the sidebar section inside the customizer.
[Contextual Controls, Sections, and Panels](https://developer.wordpress.org/themes/advanced-topics/customizer-api/#contextual-controls-sections-and-panels)

**Comment by moldcraft** [comment]
At the moment, no.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1097

```php
$options = array(
    'b' => array(
        'type' => 'box',
        'wp-customizer-args' => array( // <---
            'active_callback' => 'is_front_page',
        ),
        'options' => array(
            'o' => array(
                'type' => 'text',
            ),
        ),
    ),
);
```
