### ISSUE TITLE
auto-install no longer recognised

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#1084]
Hi there,

For some reason, my "auto-install" directory is no longer recognised and allowing customers the option to install the demo content.

I've noticed the Backup extension has changed and doesn't allow for me to create a new content install.

Not sure if this is just something I'm doing (or not doing).

Thanks!

**Comment by moldcraft** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`

----

If you really want the old install to work, add in

```
{theme}/framework-customizations/theme/manifest.php
```

```php
$manifest['supported_extensions']['backup'] = array();
```

and make sure to remove (if it exists)

```php
$manifest['supported_extensions']['backups'] = array();
```
