### ISSUE TITLE
Text block showing as blank wpengine/wp 4.3.1/unyson 2.4.11

### ISSUE THREAD

**Issue by npdang** [ThemeFuse/Unyson#1085]
For unknown reasons, I cannot edit the contents of a text block.  It shows up as a blank uneditable box.  Any suggestions?

**Comment by llemurya** [comment]
@npdang please give us more details , an print screen or an screen cast how to reproduce this bug.

**Comment by llemurya** [comment]
@npdang please answer and provide more details.Thanks.

**Comment by npdang** [comment]
I'm sorry, I'm not certain how to reproduce it other than I am unable to edit the contents of a text block.  My host is wpengine.com.  I'm wondering if there's anything I could check to see if Unyson is not compatible?

Here is a screen shot:  http://img.photobucket.com/albums/v351/npdang/Capture_zpsttwib4b7.png

The text block just appears blank inside, with no way to edit the contents.  Also, if I try to edit the contents of an existing text block that has default content that came with my Wordpress template, it also appears blank even though the text appears on the live page.  For example please see: http://orangecoast.wpengine.com/  The text box is right above the "request a consultation" button, which you can see has text, but shows up as blank inside page builder.

**Comment by llemurya** [comment]
@npdang this is because you have an ajax error , please see in the `Developer tools` in `Network` tab the ajax response.

**Comment by npdang** [comment]
Thank you.  This might be a bit over my head.  Under the network tab in developer tools, I do not see any errors.  Every line is status 200 ok.  However, under console tab there seems to be some exception thrown every time I click to open the text block.  Please see here:  http://img.photobucket.com/albums/v351/npdang/Capture2_zpsyymyma68.png

Would appreciate any comment/suggestion.

**Comment by llemurya** [comment]
@npdang you have an javascript error in console , can you expand the `Exception Object` to see the error,please make another printscreen and send it to us. Thanks

**Comment by npdang** [comment]
Please see screen shot:

![capture3](https://cloud.githubusercontent.com/assets/16181802/11691460/e171170c-9e4f-11e5-8ae1-5f60ed8ccc0d.PNG)

https://drive.google.com/file/d/0B8FAXlWic4ZxeDMwTVJabnRRRWc/view?usp=sharing

Thank you.

**Comment by llemurya** [comment]
@npdang can you make an update of the latest version of `Unyson` and say if  the error persist? Thanks. I am waiting for your response.

**Comment by npdang** [comment]
I updated, and unfortunately am receiving the same error.
![capture4](https://cloud.githubusercontent.com/assets/16181802/11721781/6ba63ba8-9f1a-11e5-90e9-31963efc3f0b.PNG)

**Comment by llemurya** [comment]
@npdang can you give us the array of options that goes in this popup, this is your custom shortcode or the shortcode from unyson?

**Comment by npdang** [comment]
The only options I can see are save and reset.  This is the shortcode from Unyson using the default editor:

[text_block text="&lt;p&gt;Disrupt polaroid freegan, church-key fap crucifix cronut locavore Portland viral bitters keffiyeh wayfarers Pinterest. 90&#039;s Helvetica bespoke flexitarian fanny pack heirloom health goth, organic photo booth ugh whatever Vice pop-up.&lt;/p&gt;&lt;p&gt;Four loko distillery paleo tote bag umami, scenester kale chips before they sold out Austin letterpress heirloom XOXO cardigan. Belly chia Godard biodiesel. YOLO typewriter photo booth, High Life banh mi mumblecore synth stumptown brunch organic Pitchfork pickled Helvetica sustainable Godard. Forage gluten-free gastropub next level, vinyl Vice Bushwick swag brunch kogi. Fanny pack Carles Austin sustainable. IPhone fingerstache four dollar toast, roof party fashion axe direct trade blog&lt;/p&gt;" _made_with_builder="true"][/text_block]

Switching from Unyson to default editor does something funny to the pages... they no longer work correctly.  You have to delete the page, then re-create it using page builder to get it to work properly again.

**Comment by llemurya** [comment]
@npdang if you have an ftp account you can send the ftp details at dev-team@unyson.io and I will investigate your bug , because on my install the `text-block` shortcodes works well.

**Comment by npdang** [comment]
Happy holidays!  I was wondering if you had a chance to take a look yet? :)

**Comment by llemurya** [comment]
@npdang I tested it on your server and for me it works , please see this [video](https://youtu.be/HYjewvyOb-A) as a proof, maybe the problem is from your browser, maybe you have some browser extensions that throw javascript errors.Please test it in other browser. I am awaiting for your response.

**Comment by barbarosva** [comment]
Hello, I am having exactly same situation, what is the fix? different browsers etc did not help me here. I updated unyson - the core theme and unyson extentions still Text Block popup is empty and I can't change a simple text there. Please HELP...

**Comment by moldcraft** [comment]
@barbarosva Please disable all plugins except Unyson

**Comment by anniedanberg** [comment]
I'm having the same problem. This began when I moved my site from a sub-directory into the root
![screen shot 2017-03-06 at 12 46 53 pm](https://cloud.githubusercontent.com/assets/26233506/23629117/85568c5a-026b-11e7-8ff5-ee4e0dd8ccd4.png)

**Comment by GheorgheP** [comment]
Open the chrome **Developer Tools** and in **Network** section look what is the response form the server when you open the popup.

**Comment by anniedanberg** [comment]
Here's what I get:
![screen shot 2017-03-07 at 6 25 00 am](https://cloud.githubusercontent.com/assets/26233506/23660680/13b07a54-02ff-11e7-84b6-9b07dd0dcb59.png)

**Comment by anniedanberg** [comment]
sorry, here's a shot of the network when attempting to edit a text box:
![screen shot 2017-03-07 at 6 36 05 am](https://cloud.githubusercontent.com/assets/26233506/23661120/8488352c-0300-11e7-8ac0-6c79ed3746a3.png)
