### ISSUE TITLE
datetime-picker and datetime-range

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1086]
These 2 option types need readonly attribute . 

I added  

	'attr'	=> array(
		'readonly' => 'readonly'
	)

myself , but users should not be able to mess with date formats

and they both are missing from the docs
http://manual.unyson.io/en/latest/options/built-in-option-types.html

**Comment by llemurya** [comment]
@danyj the description was added in the [documentation](http://manual.unyson.io/en/latest/options/built-in-option-types.html#datetime-picker).

**Comment by danyj** [comment]
@llemurya  :+1: are you thinking on adding readonly? If yes , dont forget  CSS

    cursor:pointer;

for that input

**Comment by danyj** [comment]
We need an option to remove the date. Once it is set we cant remove it , only change.

**Comment by llemurya** [comment]
@danyj please see this [issue](https://github.com/ThemeFuse/Unyson-Events-Extension/issues/15) I want to know how you see the implementation of the readonly , beacause for now you can't remove it , but you can specify the time step. I am wainting for your opinion.

**Comment by danyj** [comment]
I understand , it is tricky but users should have better way of setting it up since they can mess up the format and than we endup with frontend errors.
