### ISSUE TITLE
Backups extension always times out

### ISSUE THREAD

**Issue by rawcreative** [ThemeFuse/Unyson#1087]
This is essentially a duplicate of a previous issue: https://github.com/ThemeFuse/Unyson-Backup-Extension/issues/11 which was closed when the new extension was released. However we have the exact same result as the previous extension. On any installation of moderate size and up, the backups continually timeout when trying to zip the files. 
![screen shot 2015-12-08 at 10 51 36 am](https://cloud.githubusercontent.com/assets/1143718/11661422/d5382f58-9d9f-11e5-8c62-1efe8a1628fe.png)

**Comment by moldcraft** [comment]
Do you have any other plugins installed? There was a problem related to set_timeout(0) https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/5

Note: [The zip is the only step that is not executed in parts (multiple requests)](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/b5b0692d7ed60d0e6bb88209aa9f3cbaa5b176a1/includes/module/tasks/type/class-fw-ext-backups-task-type-zip.php#L30-L35)

The extension tries to increase the timeout limit by [this value](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/b5b0692d7ed60d0e6bb88209aa9f3cbaa5b176a1/config.php#L75). If your server does not allow timeout increase, the you will get timeout on steps like zip/unzip.

**Comment by rawcreative** [comment]
set_time_limit() is not a reliable solution, and is pretty much useless on any server running php-fpm, mod_fcgid or mod_fastcgi since they all impose their own execution limits on the environment.

**Comment by moldcraft** [comment]
I don't know another solution.

I tried to make the zip step in parts (a few files per request) but it took waaay too long to finish.
