### ISSUE TITLE
WP 4.4 messed up theme admin

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1090]
Today 4.4  was released  and it messed up some buttons and tabs 
![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/11681702/ce199380-9e60-11e5-8d0f-1b82988284f0.jpg)

double line under tabs

![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/11681724/f06cce5c-9e60-11e5-9704-e6dac43e8d51.jpg)

we need to have more reliable and robust css in there , not only overrides , and please take it easy on class names and css  

this is horrible 

use class , dont globalize 
https://github.com/ThemeFuse/Unyson/blob/master/framework/static/css/backend-options.css#L26-L27

this can be done much better with normal class /id name not this crazy nesting css class structure  

https://github.com/ThemeFuse/Unyson/blob/master/framework/static/css/backend-options.css#L137
https://github.com/ThemeFuse/Unyson/blob/master/framework/static/css/backend-options.css#L141
and many more of those 

you already have your own form  class so use it 

![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/11681805/76d59474-9e61-11e5-8831-ed9d7f31fe88.jpg)

this is a horror to override and make theme admin your own and like we just seen in 4.4 it can  break so easy. 

and please stop using important ,  if you are already in position that you have to use it, than you are doing it wrong. 

WP load-styles.php  is not doing anything to those tabs , look here everything is our css 

![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/11681965/794a4f46-9e62-11e5-83d2-2b12b58525db.jpg)

so why all those crazy class structures is beyond me . 

I know that 

    settings_form_side_tabs

was added after the 1.0  but we should clearly separate  the structure with a class for all 4 cases

	fw_theme_admin_tabs_top
	fw_theme_admin_tabs_side
	fw_post_admin_tabs
	fw_popup_admin_tabs

and not try to override fix and fix again plus mix and match. The style should be applied for each and not even think about trying to combine them all in one line or one declaration.

**Comment by danyj** [comment]
here , options popup  tabs also double line
![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/11682298/1c77c3be-9e64-11e5-8cc9-ad72241fde47.jpg)

**Comment by danyj** [comment]
@moldcraft   please bud do me a favor , add a class to the side tabs group here , 

![screenshot_6](https://cloud.githubusercontent.com/assets/2340172/11682893/db51f252-9e67-11e5-84a0-57613d6f113d.jpg)


when  

     settings_form_side_tabs

is set to true
 
    fw_side_tabs_menu 

or something  so that we can style it on our own , 


currently it uses same class as all tabs / sub tabs on admin page and only way to nail it is to chase the class with nesting.

**Comment by moldcraft** [comment]
P.S. With WordPress RC everything was looking fine. I am fixing everything now and at the end of the day we should have a version ready for release.

> currently it uses same class as all tabs / sub tabs on admin page and only way to nail it is to chase the class with nesting.

There is no difference between Normal Tabs and Side Tabs in html, the tabs are the same everywhere. Side tabs style was added later and I just added one class at container and added css related only tot that class and didn't change/touched existing styles

```css
.fw-backend-side-tabs ... { ... }
```

if you will remove with inspect element that class, everything will switch to "old" style without any issue.

**Comment by danyj** [comment]
I know that fix is easy but that is not the issue here , this is the problem in detail 
https://github.com/ThemeFuse/Unyson/issues/1092

and to be honest overriding admin is a mess since I have to let backend CSS load , that I see default Unyson theme admin and few sec after my override kicks in. All that because of those nesting things and no freedom to make admin our own.

**Comment by moldcraft** [comment]
P.S. In boxes titles they replaced h3 with h2 https://make.wordpress.org/core/2015/10/28/headings-hierarchy-changes-in-the-admin-screens/

**Comment by moldcraft** [comment]
Please test

**Comment by danyj** [comment]
these are messed up now and have double border 
http://prntscr.com/9c4lap

**Comment by moldcraft** [comment]
it was always like that

**Comment by danyj** [comment]
and if we have only one sub group , this handle should not be active
http://prntscr.com/9c4mpe

meaning it should not collapse on click , only if 2 or more than the handle should work
