### ISSUE TITLE
Can't create custom slider type

### ISSUE THREAD

**Issue by AceoK** [ThemeFuse/Unyson#1093]
Hi, i'm doing all like said in http://manual.unyson.io/en/latest/extension/slider/index.html#create-a-simple-slider-type but nothing is work, new slider type isn't created and not displaying

**Comment by llemurya** [comment]
@AceoK please look at this [issue](https://github.com/ThemeFuse/Unyson/issues/673). Say if it helps you. I am waiting for your response.

**Comment by AceoK** [comment]
@llemurya thanks for your reply, i tried disable/enable slider from Unyson, and disable/enable Unyson plugin but nothing happened. But when i switch theme to another and back it works. Thanks a lot

**Comment by llemurya** [comment]
@AceoK you can close the issue.
