### ISSUE TITLE
Opening and closing theme settings boxes fails in WP 4.4

### ISSUE THREAD

**Issue by ikixxx** [ThemeFuse/Unyson#1095]
Only way to open the box ( metabox) is to click exactly on the arrow.
In the gif when you see a **hand** cursor, I'm actually trying to open/close the box. But it only works if clicking exactly on the arrow. All major browsers affected.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/390700/11691514/963c520a-9e9b-11e5-80d7-6aadadd53e81.gif)

**Comment by moldcraft** [comment]
Are you using the latest dev version from github?

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/159

**Comment by ikixxx** [comment]
No, I'm using Wordpress repository version.

**Comment by moldcraft** [comment]
Please try the dev version.

**Comment by ikixxx** [comment]
I can't do that at the moment, but will do later in the day.
Also , when are you pushing the new version to WP repository ?

**Comment by moldcraft** [comment]
![](https://static.md/3d03cd3a1fd0e1fc05366dab469a5651.png)

**Comment by ikixxx** [comment]
:+1:  :)
