### ISSUE TITLE
Customizer panel and section priority

### ISSUE THREAD

**Issue by developerzinan** [ThemeFuse/Unyson#1097]
Hi, I started using unyson for customizer purpose , everything is fine but when i create a section then it always goes under the all panels. I didn't find priority key under the section or panel settings array. So it is possible to arrange the order of my sections and panels ?

**Comment by moldcraft** [comment]
Hello,

At the moment it's not possible

**Comment by developerzinan** [comment]
Well, thanks for the quick response. Is the any possibility to add this feature in next update ? Because i think it will be nice to arrange the all panels and sections according to the user preference.

**Comment by moldcraft** [comment]
Hello,

I added the [`wp-customizer-args` parameter](https://github.com/ThemeFuse/Unyson/commit/3ce95f82d1a7aee1e9ecdca9020e0f2641a648f9) for options used in `customizer.php`. I tested with the following options array

```
$options = array(
	'b' => array(
		'type' => 'box',
		'wp-customizer-args' => array( // <---
			'priority' => 10,
		),
		'options' => array(
			'o' => array(
				'type' => 'text',
			),
		),
	),
);
```

**Comment by developerzinan** [comment]
Great . Its working !!! thanks for the update :+1:
