### ISSUE TITLE
2.4.12 update deleted extensions

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1098]
Current update deleted all extensions
http://prntscr.com/9chbww.

**Comment by moldcraft** [comment]
Please check error log, maybe you'll find there something.

You did update manually, or you have activated automatic plugin updates?

**Comment by danyj** [comment]
nothing in error logs ,   no auto update , clicked on update and all extensions were gone . this is first time since Jan this year for this to have happened.

**Comment by moldcraft** [comment]
A few minutes ago I did update on @2Fwebd 's site without problems.

**Comment by danyj** [comment]
ok , il test another install and reply

**Comment by danyj** [comment]
hm , other install is ok,must have been isolated issue or I have clicked something in between. or past few days I downloaded masters several times for testing. closing for now

**Comment by danyj** [comment]
guess we found it  https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/160
