### ISSUE TITLE
Map Shorcode "Disable zoom on scroll" not working

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1099]
Is is only me but when **Disable zoom on scroll** is enabled, the map still can't be zoomed even when clicked?

**Comment by llemurya** [comment]
@pe6o this option works as well , please see this [video](https://youtu.be/KW4N4KAwneg) as proof. If you want  to disable zoom bar , please see this [link](https://developers.google.com/maps/documentation/javascript/examples/control-simple).Make your own map shortcode and set this parameter as an option.
