### ISSUE TITLE
Map shortcode option popup large

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1100]
I need the map Locations option popup to be large not small and we cant do this since it is predefined in the 

    _get_picker_dropdown_choices

and by the way , can you advise why you used exclusively small builder popups in your new theme?

**Comment by llemurya** [comment]
@danyj if you want to change the dimension of the `popup option` you can hook at this filter `fw_shortcode_map_provider` and set the `'size'=>'large'`, please take a look at [addable-popup](http://manual.unyson.io/en/latest/options/built-in-option-types.html?highlight=addable#addable-popup) description. Why `Themefuse` use only small size, I don't know, it is a designer choice.
