### ISSUE TITLE
No location provider specified for map / calendar shortcode

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1103]
This error keeps on coming up , have no idea what is missing 

rtcodes\shortcodes\map\class-fw-shortcode-map.php on line 114
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/map/class-fw-shortcode-map.php#L114

Population Method  is set to custom so no idea why it is trowing the error. 
I have to delete the location and recreate.

**Comment by danyj** [comment]
And it is full error , blank screen so we might want to ease on it and show a nice warning instead

**Comment by danyj** [comment]
same for calendar shortcode , 

    Notice: Unknown events provider "" specified for calendar shortcode

you want to check that population method

**Comment by danyj** [comment]
drag and drop the calendar or map without opening options , and the notice comes up 
looks like no default option is set

**Comment by moldcraft** [comment]
Reopen if this still happens.
