### ISSUE TITLE
BBpress breaks page builder

### ISSUE THREAD

**Issue by RodalErmakov** [ThemeFuse/Unyson#1104]
Hi)
I added BBpress plugin. And it breaks page builder's shortcodes in footer
![nex2](https://cloud.githubusercontent.com/assets/14311916/11736089/be8591d0-9feb-11e5-8753-c8a675772d35.jpg)
Footer is a page which attached with Multi-Select option.
On other pages footer works good.
![nex1](https://cloud.githubusercontent.com/assets/14311916/11736140/71d3132a-9fec-11e5-9d77-0046f0ec8d9e.jpg)
What should I do?

**Comment by moldcraft** [comment]
I tried this

1. Install and activate the BBPress plugin
2. Activate PageBuilder for Forums and Topics post type
3. Create a new Forum and Topic post and use PageBuilder in post content
4. On both Forum and Topic the PageBuilder content is not visible. In topic the html is there but the styles are not included in page.

Why do you need to integrate PageBuilder in BBPress?

**Comment by andreiglingeanu** [comment]
bbPress doesn't do `do_shortcode` on their content from WordPress editor.

```php
function fw_bbp_shortcodes( $content, $reply_id ) {
	$reply_author = bbp_get_reply_author_id( $reply_id );

	if( user_can( $reply_author, ct_bbp_parse_capability() ) )
		return do_shortcode( $content );

	return $content;
}

add_filter('bbp_get_reply_content', 'fw_bbp_shortcodes', 10, 2);
add_filter('bbp_get_topic_content', 'fw_bbp_shortcodes', 10, 2);

```

You'll have to also handle dynamic CSS, in this case, which is a bit tricky, by the way.
