### ISSUE TITLE
NEW UPDATE BREAKS PAGES

### ISSUE THREAD

**Issue by WWS1** [ThemeFuse/Unyson#1105]
I have just updated your plugin to the latest release and it breaks all content created with the unyson plugun causing it to display the source code only.
The site was updated to the latest wordpress release yesterday.
To resolve the issue I have had to upload the old plugin and all is well again 
Do you have an issue with this plugin??

Thanks

**Comment by moldcraft** [comment]
When actually it breaks, after page Save, or on all pages display, it also breaks in admin (the page builder is disabled) ?
Please give as more details as you can.

**Comment by WWS1** [comment]
Website is completed and works ok. All that was done was to apply the update as notified by WordPress  from the dashboard.

When the site was displayed afterwards the content was displayed as unyson code the only way I could restore the site was to upload the previous unyson plugin files.

The plugin update appeared to be uploaded correctly and was showing activated.

The view I got on the website after the update was as it would be shown if the unyson plugin had been disabled, though plugin definitely was activated in the dashboard.

That is all the information I am able to provide

 

Thank you    

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by WWS1** [comment]
Sorry I forgot to say,  with regard to Admin the unyson plugin did not appear on the edit page just text code no plugin options.

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by moldcraft** [comment]
I think the PageBuilder deactivated after update.

We had a similar problem when WordPress Plugin Automatic update were enabled, but we fixed that.

Which Unyson version did you have before update?

**Comment by WWS1** [comment]
The previous version was up to date and also the extension updates had also been applied. This problem only happened with today’s update.

Just a thought though after your comments in previous email, the update was applied via the Jetpack WordPress mysite’s interface and not from the actual sites dashboard if this helps?

So there may be a problem when the plugin is updated using this method.

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by moldcraft** [comment]
> the update was applied via the Jetpack WordPress mysite’s interface and not from the actual sites dashboard

Thank you very much for this detail. We will test and let you know

**Comment by WWS1** [comment]
I have just re-applied the new  unyson update using the sites dashboard after reading your comments and it works with no problem after updating in this way, so it may be that it is related to being updated via the Jetpack WordPress updates link.

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by moldcraft** [comment]
@WWS1 Please replace [this line](https://github.com/ThemeFuse/Unyson/blob/v2.4.12/framework/core/components/extensions.php#L106) with

```php
true
```

![](https://static.md/e241badcd12f6ba248bc350987e566b2.png)

and try to update the Unyson via jetpack

**Comment by WWS1** [comment]
Thanks for the response excellent service.

I have already updated the site using site dashboard which works fine so I am happy that my issue is resolved.

Just happy to help in case others are experiencing the same issues and so that you are aware of any potential problems.

I have not tried changing the code as you have suggested on GitHub but at least you are now aware of the problem.

 

Thank you again for your assistance 

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by moldcraft** [comment]
I am very sorry, [here](https://github.com/ThemeFuse/Unyson/commit/9305053f647c838645d5412c214500dc88f048fe#diff-cf866bf08b8f747e3120221a6b1b07cfL130) I deleted by mistake some important actions related to plugin update, now on next plugin update the users will loose installed extensions :(
on future updates it will not happen
