### ISSUE TITLE
Priority for fw.Modal buttons works in reverse order

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1106]
[Priority](https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw.js#L1091) is working in reverse order. After update to WP 4.4 I got [this](https://www.dropbox.com/s/k3gy0bvfq6lha18/Screenshot%202015-12-11%2019.13.31.png?dl=0) order for my custom button. I have to make priority for my button bigger than `40` to restore previous behavior.

**Comment by moldcraft** [comment]
We send the buttons array directly to WP scripts (we used WP backbone js components, same components are used in media upload modals), our script does nothing with that `priority` parameter.

**Comment by andreiglingeanu** [comment]
Okay, got it. It's a WP fault. Thanks.
