### ISSUE TITLE
How to get option, E.g: post option ?

### ISSUE THREAD

**Issue by uxdesignit** [ThemeFuse/Unyson#1109]
Hi, 
I'm trying to build new theme from Scratch-Theme-1.0.7. It is amazing feature to see... i use few post option type image-picker but i dont know how to get it value when view post. I try many way from http://manual.unyson.io/en/latest/options/introduction.html, or get_option()... but it is not return null..
Can you tell me how i can get post / page / taxanomy option ?
Thank in Advances

**Comment by moldcraft** [comment]
Hello, use these functions http://manual.unyson.io/en/latest/helpers/php.html#database

**Comment by uxdesignit** [comment]
Thanks a lot, moldcraft, it work
