### ISSUE TITLE
the_excerpt() empty when using the Visual Layout Editor

### ISSUE THREAD

**Issue by Kiseki** [ThemeFuse/Unyson#111]
I'm having difficulty displaying the_excerpt() on my News page which I'd like to show a summary of each blog post. I am using the visual layout editor for my blog posts and nothing is returned, however when I use the default editor the_excerpt() is displayed. 

Is there another way to get a summary of the blog post to display when using the visual editor? My current code which is located in content.php.

```
<?php if ( is_search() || is_home() ) : ?>
<div class="entry-summary">
    <?php the_excerpt(); ?>
</div><!-- .entry-summary -->
<?php else : ?>
<div class="entry-content">
    <?php
        the_content( __( 'Continue reading <span class="meta-nav">&rarr;</span>', 'unyson' ) );
        wp_link_pages( array(
            'before'      => '<div class="page-links"><span class="page-links-title">' . __( 'Pages:', 'unyson' ) . '</span>',
            'after'       => '</div>',
            'link_before' => '<span>',
            'link_after'  => '</span>',
        ) );
    ?>
</div><!-- .entry-content -->
<?php endif; ?>
```

Many thanks for your help.

**Comment by maxlanser** [comment]
I have the same problem, I use Unyson, the standard function the_expert () does not display anything ... how to solve this problem ???
