### ISSUE TITLE
What does this data attribute in calendar do?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1110]
Sorry but this data attribute is nowhere found or set so I am trying to figure out what you think this should do

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/calendar/static/js/scripts.js#L137

**Comment by moldcraft** [comment]
The developer that created this shortcode is no longer in our team. We will investigate and let you know when we will have a response.

**Comment by danyj** [comment]
ok, i just cant find it anywhere in calendar and it makes no sense to use a dot for it so looks like stray code for something.

**Comment by danyj** [comment]
and while you at it , can you figure out where async is coming from please, I cant find where it is set to true but is  somewhere in calendar scripts  http://prntscr.com/9dcnlr
