### ISSUE TITLE
Calendar and map population method event makes no sense 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1111]
In calendar and map short code we have an option to select population method which is custom or event. 
1. This option should only be visible if events extension is installed ,  I have not used it until now and was wandering all this time what it is. I also do not have it enabled as compatible extension so my users should not be asking what this is at all. 
2. In the event extension we are allowed to publish an event without previously creating category. This event will never be able to be picked up by  map or calendar shortcode.
3. The event selection should not go by categories but by events
   http://prntscr.com/9dczl1

Lets say I am hosting 10 WP Meetup events , I should be able to pick the one I want displayed and not pick the category where that event might belong.

**Comment by llemurya** [comment]
@danyj i will be absent for two weeks ,when I will return I will investigate and fix all these issues.

**Comment by danyj** [comment]
@llemurya did you see this one bud?

**Comment by llemurya** [comment]
@danyj yes I saw this but the events module is hardcoded and I think we must refactor it in the future.Now I think all issues that is opened for events will be on hold.

**Comment by danyj** [comment]
olddddd bump , can someone look at this?
