### ISSUE TITLE
Table shortcode button option large popup

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1112]
Same as here  https://github.com/ThemeFuse/Unyson/issues/1100

we cant change the size of the button popup

**Comment by llemurya** [comment]
@danyj i will be absent for two weeks ,when I will return I will investigate and fix all these issues.

**Comment by llemurya** [comment]
@danyj you can change the size, just need to set in your theme table shortcode  another value in the `popup_size`, please see this example:
```php 
$cfg['page_builder'] = array(
	'title'       => __( 'Table', 'fw' ),
	'description' => __( 'Add a Table', 'fw' ),
	'tab'         => __( 'Content Elements', 'fw' ),
	'popup_size'  => 'small' // you can change this value from your theme.
);
```

**Comment by danyj** [comment]
@llemurya  not talking about shortcode popup 
this button popup here http://prntscr.com/9s3bsj

**Comment by llemurya** [comment]
please see this [issue](https://github.com/ThemeFuse/Unyson/issues/1113#issuecomment-172803544).
