### ISSUE TITLE
How to override table option type?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1113]
We can override table view only , but we cant change wording , help or instructions for table options. 

In my eyes this is not Table Styling  http://prntscr.com/9dzx80  
but a Table Type 
and few other things I need changed but cant since in options all we have is this 

	'table'         => array(
		'type'  => 'table',
		'label' => false,
		'desc'  => false,
	)

and this is in same category than https://github.com/ThemeFuse/Unyson/issues/1112
do I have to make my own table type or  is there easier solution for these ?

**Comment by danyj** [comment]
fixing the button popup size or giving option for  popup size within the table option  and changing the word  styling to type would fix all issues I think , please see if you can change these 2.thnx !

**Comment by llemurya** [comment]
@danyj i will be absent for two weeks ,when I will return I will investigate and fix all these issues.

**Comment by llemurya** [comment]
@danyj now you can hook at this filter. 
```
add_filter( 'fw_option_type_table_defaults' , function($data){
    //your code
    return $data;
}
```
You can change the `popup` option keys or other keys.
