### ISSUE TITLE
How to display image url from upload, multiple-uploads in addable popup

### ISSUE THREAD

**Issue by SilentAce** [ThemeFuse/Unyson#1114]
Hello members,

This might be a beginners questions but i have trouble displaying the image url in the view from the options when they are set inside a addable popup. This is my options code:

    <?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
    }

    $options = array(
	'image_tabs' => array(
		'type'          => 'addable-popup',
		'label'         => __( 'Image tabs', 'fw' ),
		'popup-title'   => __( 'Add/Edit Tab', 'fw' ),
		'desc'          => __( 'Create your image tabs with heading and text content', 'fw' ),
		'template'      => '{{=tab_title}}',
		'popup-options' => array(
			'tab_image_title' => array(
				'type'  => 'text',
				'label' => __('Image Heading', 'fw'),
				'desc'  => __( 'Enter Image Heading', 'fw' )
			),
			'tab_image' => array(
				'type'  => 'upload',
				'label' => __( 'Add Image', 'fw' ),
				'desc'  => __( 'Either upload a new image, or choose an existing image from your media library', 'fw' )
			),
			'tab_title' => array(
				'type'  => 'text',
				'label' => __('Title', 'fw'),
				'desc'  => __( 'Enter Tab Title', 'fw' )
			),
			'tab_content' => array(
				'type'  => 'textarea',
				'label' => __('Content', 'fw'),
				'desc'  => __( 'Enter the Tab Content', 'fw' )
			)
		),
	)
    );

How can i display the images in view from an addable popup? 

Thanks

**Comment by moldcraft** [comment]
Hello,

Try

```php
'template'      => '<img src="{{= tab_image.url }}" >',
```

**Comment by SilentAce** [comment]
Hi,

This is how to display the images in the backend options, i need how to display them in frontent via the view.php file.

**Comment by moldcraft** [comment]
* http://manual.unyson.io/en/latest/helpers/php.html#database
* For shortcode view, your options are in the `$atts` variable http://manual.unyson.io/en/latest/extension/shortcodes/index.html#default-view-file

**Comment by SilentAce** [comment]
Thanks for the documentation. You already have an example in framework/extensions/shortcodes/shortcodes/media-image. When i add the $atts['image']['url'] in view.php it works but only if the 'type'  => 'upload' is not inside the popup-options.

**Comment by moldcraft** [comment]
Add in your view

```php
fw_print($atts);
```

to see the array structure.

**Comment by SilentAce** [comment]
Solved it, thank you very much :)
