### ISSUE TITLE
Update messed up my site

### ISSUE THREAD

**Issue by LevyMarketing** [ThemeFuse/Unyson#1115]
I just updated to the newest version and now my site is just all code. 

I tried reinstalling all of the plugins and I receive an error when I try to (all it says is error).  

When i follow the link provided by you in the update, it asks me to log into my admin account (even though I already am) and then won't let me in. Is that because my site is hosted by Wordpress? 

I need to know how to finish installing the new plugin so I have a site again.

**Comment by moldcraft** [comment]
> and I receive an error 

Which error? Please give us the error message or a screenshot

> it asks me to log into my admin account (even though I already am) and then won't let me in

If you have multisite, you need to login in as network admin

> my site is hosted by Wordpress

What do you mean hosted by Wordpress?

----

Can you give me access details to your site admin, so I will log in and check the problem? If yes, send the details to `moldcraft[at]email.com`

**Comment by LevyMarketing** [comment]
![image](https://cloud.githubusercontent.com/assets/14837164/11784730/fb95eb80-a24b-11e5-9726-6570ef70cc81.png)

As I said, all it says is "error."

I mean hosted by GoDaddy. I'm logged into my admin account, but when I follow the specific link sent with the update, it logs me out and won't let me log back in.

**Comment by LevyMarketing** [comment]
![image](https://cloud.githubusercontent.com/assets/14837164/11784782/4674ea02-a24c-11e5-9995-57ef3f99a1c5.png)

This is what my site currently looks like. I'm assuming it's because with the update, I have no extensions installed anymore.

**Comment by moldcraft** [comment]
Can you give access to your site?

**Comment by moldcraft** [comment]
Also can you find apache/php error.log and check it for error messages?

**Comment by LevyMarketing** [comment]
I would prefer not to since it's a company site. Is there nothing you can offer me to do?

**Comment by LevyMarketing** [comment]
Where would the apache/php error log be? It's not in my editor.

**Comment by moldcraft** [comment]
> I would prefer not to since it's a company site. Is there nothing you can offer me to do?

We can continue the discussion, and I will try to explain you to do different things until you will find a fix the problem, but I can do all that by myself and find the problem faster.

For example, please open browser developer tools (F12), go to Network tab, press the Download button for an extension then inspect the ajax response.

> Where would the apache/php error log be? It's not in my editor.

It's not in WordPress admin, it should be in cPanel or if you have VPS, go in ssh and run

```sh
tail /var/log/apache2/error.log
```

**Comment by LevyMarketing** [comment]
When I go to the developer tools, there are no extensions to be downloaded.

**Comment by moldcraft** [comment]
Developer tools allows you to inspect ajax requests to see if there are hidden errors.
