### ISSUE TITLE
Duplicating table shortcode save ajax error

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1118]
When you duplicate already existing table shortcode , remove one row and try to save , there is parse ajax error because this line https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/table/includes/fw-option-type-table/class-fw-option-type-table.php#L141

is trowing undefined  offset error. 
http://prntscr.com/9efagp

to replicate issue , create table with 4 columns

http://prntscr.com/9efapj

save  page , 

duplicate shortocde ,  than remove highlight  column 

try to save the popup

**Comment by danyj** [comment]
correction ,  remove highlight column and error comes 

http://screencast.com/t/ed0nmNTnUgd

**Comment by llemurya** [comment]
@danyj please test and say if it works properly.Thanks for the bug reporting.
