### ISSUE TITLE
[info]  How to place shortcode options inside another shortcode options

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1119]
I just ran in to this one and to be honest I needed it before but never knew how to do it properly. 

So if for example you need a shortcode inside another shortcode,  for example icon or button shortcode inside icon-box this is one of the ways to do this. 

	$icon_shortcode = fw()->extensions->get( 'shortcodes' )->get_shortcode( 'icon' );
	$options = array(
		
		'icon_options' => array(
			'type' => 'popup',
			'label' => __('Popup', 'fw'),
			'popup-title' => __('Popup Title', 'fw'),
			'button' => __('Edit', 'fw'),
			'popup-title' => null,
			'size' => 'large', // small, medium, large
			'popup-options' => $icon_shortcode->get_options()
		)
	);

This will place  icon shortcode inside the popop option type
http://manual.unyson.io/en/latest/options/built-in-option-types.html#popup

 and when clicked it opens the popup with icon shortcode options. 

@moldcraft  or other developers might know another way and if they do it wold be great if they could pitch in , but for now this one worked fine for me.

**Comment by moldcraft** [comment]
P.S. (Not the actual answer) Use [this solution](https://github.com/ThemeFuse/Unyson/issues/1071#issuecomment-161586475) to generate shortcode notation to be able to do `do_shortcode('[icon ...]')` inside icon box view

**Comment by danyj** [comment]
@moldcraft  I meant inside the pagebuilder shortcode options , not the front view or am I missing something now?

**Comment by moldcraft** [comment]
So the title should be: How to place shortcode options inside another shortcode options?

**Comment by danyj** [comment]
yes , right

**Comment by moldcraft** [comment]
Your code should work fine.
