### ISSUE TITLE
how to use  oEmbed as Post / Page option

### ISSUE THREAD

**Issue by uxdesignit** [ThemeFuse/Unyson#1120]
i see full demo option on Scratch-parent theme, but till no see an oEmbed option. Can you tell me how to use this or i have to create new my own option for this purpose ?

Best Regards

**Comment by moldcraft** [comment]
We don't have any oEmbed related options.

Can you give more details what it should do?

**Comment by uxdesignit** [comment]
hi, thanks for your responding message.
almost other metabox plugin has a Field Types to handle an oEmbed :
https://codex.wordpress.org/Embeds

Context: for example we want to attach an oEmbed into new post, i need a new text box to fill and store  oEmbed url. E.g: https://soundcloud.com/octobersveryown/drake-back-to-back-freestyle
If oEmbed url is valid, it will show a preview box bellow [in backend mode only]

See example: http://d.pr/i/O3xw
[it was created by ECB2 metabox plugin] 
https://github.com/WebDevStudios/CMB2/wiki/Field-Types#oembed

Can you create it for next release or guide me how to do it?
Thanks in advances
Cuong

**Comment by moldcraft** [comment]
Thank you for details.

I haven't investigated in detail how oEmbed works and can't advice you, sorry

We will try to implement this feature (I can't give any eta)

**Comment by danyj** [comment]
I am digging on it also and there is no clear info about this feature. Will reply once found something of use.

**Comment by danyj** [comment]
So far I see there is no need for additional  input box  in post edit since the editor is now picking up all oEmbed providers, just paste the link and switch to visual tab 
http://prntscr.com/9esisq
http://prntscr.com/9eshvk
http://prntscr.com/9esi1a

Now for page edit there might be a need for it since the editor is taken by builder

**Comment by uxdesignit** [comment]
a real example post with oEmbed for more detail:
http://d.pr/i/14M8L

**Comment by llemurya** [comment]
@uxdesignit @danyj the option was added https://github.com/ThemeFuse/Unyson/commit/f1a90c94b50622e4f92b28e0c2d040d2d9dbbd83, please test it.You can see in the [documentation](http://manual.unyson.io/en/latest/options/built-in-option-types.html#oembed) how to use it.

**Comment by uxdesignit** [comment]
greate work
sorry for the late reply

**Comment by danyj** [comment]
:+1:

**Comment by danyj** [comment]
@uxdesignit   do u mind posting again the real example , the link above is dead. I would like to see how you think this should be used. thnx!

**Comment by uxdesignit** [comment]
sure, budy, you can see how it work with some real examples:
http://gennews.uxdesignit.com/clasic/nam-leo-enim-rhoncus-et-elit-quis-mollis-eleifend-elit/
http://gennews.uxdesignit.com/clasic/cras-laoreet-turpis-eget-commodo-scelerisque/

**Comment by danyj** [comment]
:+1:
