### ISSUE TITLE
Can FW_Cache help  me with this?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1121]
@moldcraft  I have a function that is processing ( printing ) 2 color gradient with help of my css generator class. For example gradient CSS 

	function thz_bg_gradient($color1,$color2,$type = 'linear'){
		
		
		if($color1 == '' && $color2 == ''){
			return;
		}
		
		$array= array(
			'background' => array(
				'background-type' => 'gradient', // none,color,image,gradient,video
				'background-gradient-style' => $type, // linear, radial
				'background-gradient-angle' => '0',
				'background-gradient-size' => 'farthest-corner',//closest-corner, closest-side,farthest-corner,farthest-side
				'background-gradient-shape' => 'circle',//circle,ellipse
				'background-gradient-h-poz' => '50',
				'background-gradient-v-poz' => '50',
				'background-gradient-start' => '0',
				'background-gradient-start-color' => $color1,
				'background-gradient-add-stop' => array	(),
				'background-gradient-end' => '100',
				'background-gradient-end-color' => $color2,
			),	
		);
		
		$print_css 	= new ThzCssGenerator();
		return $print_css->ThzBackground($array);		
	}

all of this works fine , thing is that I am using it in a shortcode static.php after I have received the 2 colors.

    thz_bg_gradient($package_bg,$package_bg2)

 

So I am not saving it at all but processing  this function on every page load. 

Would FW_Cache be able to help me cache the printed css 
and reuse it instead of processing it all the time ? 

If yes would you be able to advise how?
Any help is appreciated!

**Comment by moldcraft** [comment]
No, FW_Cache doesn't have a "magic" cross request storage, it contains just a simple private array variable, so it's useful only in one request and is reset on next request (just like all variables).

**Comment by danyj** [comment]
than you!
