### ISSUE TITLE
New Demo Content Issue

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1123]
Hi!
My client got that error when install demo content in localhost. 
![2015_12_15_17_21_29_demo_content_install_restaurante _parrilla_argentina _tehuelche_wordpress](https://cloud.githubusercontent.com/assets/1773011/11829671/dad34218-a3d0-11e5-8800-3cd4b74b04c6.png)
So what is the problem?

**Comment by llemurya** [comment]
@duongancol I think you call twice the same filter or action what's why you see two screens with Demo Content Install.

**Comment by moldcraft** [comment]
Hello,
Similar issue https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/5 Please check if on your client is the same (timeout 0) or give me admin/ftp access (email to `moldcraft[at]email.com`)

**Comment by moldcraft** [comment]
Today we had the same problem on one of our team member localhost, and the problem was `set_time_limit(0);` in `wp-config.php`

**Comment by duongancol** [comment]
They don't have this code in wp-config.php. And they need to install in local So I have to find other way. I'll close this issue.

**Comment by duongancol** [comment]
Hi! My other client get issue with demo install. It showed this issue
![screen shot 2016-01-21 at 10 04 42 am](https://cloud.githubusercontent.com/assets/1773011/12470422/b175e6a6-c026-11e5-8899-037c82cd7abc.png)
I setup the permission of fw-backup folder to 777, but this error still happen.

**Comment by duongancol** [comment]
Please help us urgent!

**Comment by moldcraft** [comment]
Give me admin/ftp access details to `moldcraft[at]email.com`

**Comment by duongancol** [comment]
I did, please check your inbox!

**Comment by moldcraft** [comment]
We had already 2 clients on WpEngine with the same issue and we have no idea how to fix it.

I will try something now ([execute steps via ajax](https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/7))

**Comment by moldcraft** [comment]
Thanks to [this script](http://sourcebox.io/8b8c68d8abcbf4b13f5197c13142d38a/php) I found some errors

```
file_put_contents(/.../wp-content/uploads/fw-backup/.htaccess): failed to open stream: Permission denied in /opt/nas/www/common/production/php_prevent_flock.php on line 22
```

See the "File Permissions:" section https://wpengine.com/support/troubleshoot-wordpress-wp-engine-error-log/

Inspecting...

**Comment by moldcraft** [comment]
Done! (imported Demo Content)

Still not sure what is the problem. I pressed [this button](https://static.md/6d488c764f6503f12620a43b4c50623c.png) then tried to Demo Content Install, it failed, the I tried again and it worked.

I think WpEngine has too restrictive file permission configuration...

**Comment by duongancol** [comment]
Thank @moldcraft, hope it will be helpful for other people that using wpengine hosting!

**Comment by ekamran** [comment]
What's the solution for this? I got similar issues but resetting permissions doesn't help. Neither WPEngine logs are showing up anything.

**Comment by moldcraft** [comment]
WPEngine users still have problems with Demo Install. ThemeFuse support team discussed a few times directly with WPEngine support team about it but no cause of the problem or a solution was found. It's weird.

**Comment by ekamran** [comment]
So a company who brags about WordPress Exclusivity doesn't support a framework to work peacefully?
Anyway, the only solution i got now is to install the theme & demo data on a different hosting, then Export that XML file & upload into the new site on WPEngine.

**Comment by stevevorass** [comment]
Here's the solution guys - switch over to staging and install the demo content there.  It will work.  Then synch that over to the live site and you're set!

**Comment by iamnotjason** [comment]
@moldcraft Hey, my name is Jason and I work at WP Engine. I'd like to chat with you about the installation issue of the demo content when you have some free time. Is moldcraft@email.com a good email to reach you at?

**Comment by moldcraft** [comment]
Hello @iamnotjason 

Yes, that's my email.
