### ISSUE TITLE
Multi Picker value fetching

### ISSUE THREAD

**Issue by ahmmob** [ThemeFuse/Unyson#1124]
<pre>
$options = array(
	'demo_multi_picker_radio'        => array(
		'type'         => 'multi-picker',
		'label'        => false,
		'desc'         => false,
		'value'        => array(
			'gadget' => 'mobile',
		),
		'picker'       => array(
			'gadget' => array(
				'label'   => __( 'Multi Picker: Radio', 'unyson' ),
				'type'    => 'radio',
				'choices' => array(
					'phone'  => __( 'Phone', 'unyson' ),
					'laptop' => __( 'Laptop', 'unyson' )
				),
				'inline' => true,
				'desc'    => __( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
					'unyson' ),
				'help'    => sprintf( "%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
					__( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
						'unyson' ),
					__( 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
						'unyson' )
				)
			)
		),
		'choices'      => array(
			'phone'  => array(
				'price'  => array(
					'type'  => 'text',
					'label' => __( 'Price', 'unyson' ),
				),
				'memory' => array(
					'type'    => 'select',
					'label'   => __( 'Memory', 'unyson' ),
					'choices' => array(
						'16' => __( '16Gb', 'unyson' ),
						'32' => __( '32Gb', 'unyson' ),
						'64' => __( '64Gb', 'unyson' ),
					)
				)
			),
			'laptop' => array(
				'price'  => array(
					'type'  => 'text',
					'label' => __( 'Price', 'unyson' ),
				),
				'webcam' => array(
					'type'  => 'switch',
					'label' => __( 'Webcam', 'unyson' ),
				)
			),
		),
		'show_borders' => false,
	),
</pre>

I am little bit confused about which option_id will be used if .
1. Radio button with laptop is selected (main option)
2. and when I want to get price of laptop

<pre>
$value = fw_get_db_post_option(
    'option_id/'. fw_get_db_post_option('option_id/'. 'gadget')
);
</pre>

**Comment by moldcraft** [comment]
Hello,

Your database value will always be this

```php
array(
    'gadget' => 'mobile', // or 'phone'
    'phone'  => array(
        'price' => '100',
        'memory' => '16',
    ),
    'laptop' => array(
        'price' => '1000',
        'webcam' => true,
    ),
),
```

So first you pick the `gadget` key value, and based on that get the selected choice values

```php
$gadget_name = fw_get_db_post_option('option_id/gadget');
$values = fw_get_db_post_option('option_id/'. $gadget_name);
```

Hope it makes sense.

**Comment by ahmmob** [comment]
thanks for answer. It worked. 
But how to get price value inside phone or laptop?

**Comment by moldcraft** [comment]
```php
fw_get_db_post_option('option_id/phone/price');
```

**Comment by ahmmob** [comment]
Thanks for quick response :+1:

**Comment by ahmmob** [comment]
how I can use multi-picker inside multi-picker.
e.g; I want to select first option of video then I want to choose from youtube,vimeo or upload from local system.

**Comment by moldcraft** [comment]
Just use it. You can put any options inside multi-picker

```php
'choices' => array(
    'video' => array(
        'video-type'  => array(
            'type'  => 'multi-picker',
            ...
        )
    )
)
```
