### ISSUE TITLE
Cannot create temporary directory: /wp-content/plugins/unyson/tmp

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1127]
I know that this issue should be fixed 1 year ago but today two of my clents have this error while trying to install Unyson extensions.

"Cannot create temporary directory: /wp-content/plugins/unyson/tmp".

One of the tried a couple of the latest Unyson versions and Wordpress versions but the problem is still there.

Any help will be greatly greatly appreciated.

**Comment by pe6o** [comment]
Ah, there are 3 clients now...

**Comment by moldcraft** [comment]
Can you give admin/ftp to a site with the problem?

**Comment by pe6o** [comment]
Is there an email that I can send you to?

**Comment by moldcraft** [comment]
`moldcraft[at]email.com`

**Comment by pe6o** [comment]
Email sent :)

**Comment by moldcraft** [comment]
Yes, I received, already inspecting (it's something weird with `$wp_filesystem`)

**Comment by moldcraft** [comment]
Thank you for ssh access.

**Comment by moldcraft** [comment]
P.S. I did debug with the following code, I'll just paste it here, maybe someday it will be useful for inspecting a similar bug

```php
add_action('fw_init', function(){ if (!isset($_GET['test'])) return;
	global $wp_filesystem;
	
	$debug = false;
	
	if (FW_WP_Filesystem::request_access(fw_get_framework_directory('/extensions'), fw_current_url(), array())) {
		$debug = array(
			'fs_method' => get_filesystem_method(),
			'dir_map' => FW_WP_Filesystem::get_base_dirs_map(),
			'path_normal' => fw_ext('update')->get_path(),
			'path_wp_fs' => FW_WP_Filesystem::real_path_to_filesystem_path(fw_ext('update')->get_path()),
			'fs' => $wp_filesystem,
			'fs_error_code' => $wp_filesystem->errors->get_error_code(),
		);
	}
	
	fw_print($debug);
});
```

**Comment by pe6o** [comment]
That's a nice code there. 

I am on a phone right now. Did it help you to pinpoint the problem?

**Comment by moldcraft** [comment]
In a few words what was the problem: Our code expected that if `$wp_filesystem` is not empty, then it was successfully initialized and it's ready to use (that it's impossible to initialize it in a failed state), but on your server it was initially not empty but initialized and container errors. So I changed the code to check `$wp_filesystem` every time for errors

Before

```
$success = !empty($wp_filesystem);
```

After

```php
$success = $wp_filesystem && !(
    is_wp_error($wp_filesystem->errors)
    &&
    $wp_filesystem->errors->get_error_code()
);
```

**Comment by pe6o** [comment]
That's great! This will be in the new version I suppose?

**Comment by moldcraft** [comment]
Yes. In a few days (soon I will create an [approval](https://github.com/ThemeFuse/Unyson-Extensions-Approval))

**Comment by pe6o** [comment]
You are awesome!

Meanwhile I could send them the github version I suppose.

**Comment by moldcraft** [comment]
Yes, if other clients have similar issue, use the github version

**Comment by Prateekm16** [comment]
Hi Ghost, I'm facing a similar problem can you help me to resolve it.
