### ISSUE TITLE
Page Builder Loosing Content in Editor, but Still Displaying Content On Page

### ISSUE THREAD

**Issue by AndrewSocialLite** [ThemeFuse/Unyson#1128]
Hi there,

I've run into a extremely concerning problem while building my site. The page builder widgets are not showing up in the page editor.

For example:
This page looks normal
http://sociallitetester2.info/application-guides/

But, when I go to edit it, the page editor is blank. No sections, content, or anything. When I look at previous versions, the code is all there, it's just not showing up in page builder .
![screen shot 2015-12-16 at 9 34 20 am](https://cloud.githubusercontent.com/assets/16324399/11847022/9b0fbc4e-a3d8-11e5-9a78-5f82be36ef68.png)
![screen shot 2015-12-16 at 9 34 33 am](https://cloud.githubusercontent.com/assets/16324399/11847023/9b119d34-a3d8-11e5-8163-a2e49fe28ff7.png)

Do you know how to fix this issue? I have updated Uyson to the latest version. It has happened on a number of pages on my site, but not all.

Thanks
Andrew

**Comment by moldcraft** [comment]
Hello,

I don't know what the problem may be, sorry. (on our side we don't have this issue)

Without concrete steps to reproduce the problem I can't help. If you know how to reproduce the problem, please give me access to your site and a list of steps to follow, then I will debug the code.

For now you can check apache error log, maybe there were some errors on post save.

**Comment by moldcraft** [comment]
Have you tried to recover those pages from Revisions?

**Comment by dobromir-hristov** [comment]
Aha same as the problem I have atm when using WPML. posted here #1131

**Comment by AndrewSocialLite** [comment]
When I recover the page, it deletes all the content and I'm left with a blank page entirely.

**Comment by moldcraft** [comment]
Sorry :(

Do you have the latest Unyson version, extensions are up-to-date?

**Comment by jsrothwell** [comment]
I have reproduced the situation through importing a wordpress export file. Everything is there but the editor is blank

**Comment by moldcraft** [comment]
Have you fixed this? I see that http://sociallitetester2.info/application-guides/ looks fine

**Comment by moldcraft** [comment]
> @jsrothwell I have reproduced the situation through importing a wordpress export file

That's why we create our own export/import tool http://manual.unyson.io/en/latest/extension/backups/index.html

**Comment by mostrador** [comment]
I'm getting very frustrated with using the page builder's seemingly endless lockups but this last issue is a huge problem. I'm getting the very same issue as above to my most important page that would take forever to recreate. I can see the code now but only a text box in the page builder screen. Is there any way to get the content back into the editor so I can continue building the page?

**Comment by mostrador** [comment]
Also, trying to restore a revision but it only brings up a blank page.

**Comment by moldcraft** [comment]
First create a backup!

Then try to restore the page from revisions. Do you have any custom configuration in wp-config.php (for example related to revisions) ?
Check post meta for meta_key named `fw_options`, what is its length?

**Comment by mostrador** [comment]
Thank you for the quick reply.
I just created a backup. I have one created with Duplicator from a couple days ago but don't want to resort to that.
There is no custom config in wp-config.php.
As for checking post meta - how do you do that? Sorry I don't know what you mean.
Thanks again for helping.

**Comment by mostrador** [comment]
If I refresh the blank revisions page I get a  Server error 500.

**Comment by moldcraft** [comment]
> As for checking post meta - how do you do that?

From phpMyAdmin

> I have one created with Duplicator from a couple days ago but don't want to resort to that.

Anyway, keep that backup, maybe it will be useful to restore the info manually from it.

> I get a Server error 500

Check apache error.log for error messages

----

Do you have the latest version of Unyson and extensions are up-to-date?

**Comment by mostrador** [comment]
for the meta_key, the varchar(255) field is empty.

for error logs, I only see the following in the php-errors:
[31-Jan-2016 20:05:06 UTC] PHP Warning:  Invalid argument supplied for foreach() in C:\home\mywebsite\wwwroot\wp-content\themes\the-core-parent\framework-customizations\extensions\shortcodes\shortcodes\team-member\views\view.php on line 121

------------------------------------
I started rebuilding from a backup. I'm very concerned about this occurring again as it's obvious I'm not the only person that has seen this issue.
Also, the posts I've seen from others about the pages not updating is real but I don't know how to reproduce it. I've only used Chrome but I don't think that's it. 
This is the issue:
I make page updates and hit Update. The circle next to Update spins forever but the page doesn't update. You have to click back on the page in the menu and start over. This happens possibly every third save!
Sometimes when this happens, it won't let you click out of the page. Everything locks up. A browser page refresh does nothing. You have to completely close the browser and start over. 
All of this is a time waster and unacceptable.
Any help would be appreciated.

Thanks,
Dave

**Comment by moldcraft** [comment]
1. How many revisions that page has?
2. Do you have many shortcode options? I mean a shortcode has 7-10 options or it has a lot of options (included multi-picker) grouped in tabs?
3. How big is post_content length? ([screen](https://static.md/9a9bfc22b630cc8f654d671e3e4450b1.png))

**Comment by mostrador** [comment]
I believe the page had 117 revisions when I was trying to access them to restore.
I don't know what you mean about the shortcode options. I haven't added anything and I'm altering a page that I got from demo content. The page is actually smaller than the demo as I have 1/3 of it deleted.
I don't think I replicated your third request correctly but my hover shows Original Length 73.

**Comment by moldcraft** [comment]
Sorry, I don't know how to help.

Which theme are you using?

**Comment by mostrador** [comment]
I'm using The Core.

**Comment by moldcraft** [comment]
Set in wp-config.php

```php
define('WP_POST_REVISIONS', 30);
```

and maybe it will fix the endless loading on post save

**Comment by GheorgheP** [comment]
During 2016 we did not notice this problem or it was noticed but for some special conditions, so I think we can close this issue for now.
