### ISSUE TITLE
taxanomy option just work in edit mode ?

### ISSUE THREAD

**Issue by uxdesignit** [ThemeFuse/Unyson#1129]
Hi, 
Follow instruction, i create category option and place it on my theme where:
\framework\theme\options\taxonomies\category.php

Problem is: when i create new category from : Blog Post / Category.. I can see category option. But when edit it.
Question is: how to enable taxanomy option when we create new it. [now, we just see it when we do edit any already category for example]

Please Advice
Thanks in Advances
Cuong

**Comment by moldcraft** [comment]
We didn't found a possibility in WP to do that. If you know how, please create a pull request.
