### ISSUE TITLE
Slider with decimal places

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1130]
Feature request:
Slider with one decimal place.
reason:I want to use it to set font size in **rem**, so I really need those decimal places.

**Comment by llemurya** [comment]
@ikixxx you can try this solution.
```php
array(
     'type'       => 'slider',
     'properties' => array(
         'step' => 0.1
    )
)
```
If it helps , please close the issue.

**Comment by ikixxx** [comment]
This won't give me the value in decimal places, I always get a round value.

**Comment by llemurya** [comment]
@ikixxx please see this [video](https://youtu.be/WNDatiGaE4o) as a proof, or explain more detailed what you mean as a round value?

**Comment by llemurya** [comment]
@ikixxx please answer in order to fix this issue.

**Comment by llemurya** [comment]
@ivandotv please answer.

**Comment by ivandotv** [comment]
I'm on vacation right now until  Monday.

**Comment by ivandotv** [comment]
I apologize for the delay.
Works as expected.
