### ISSUE TITLE
Add a button in Page Builder Interface

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1132]
Is there some sort of event for adding a button [here](https://cloud.githubusercontent.com/assets/2979628/11873830/3247978c-a4e5-11e5-8cec-7130db4ad613.png)? I need also a way to access page builder instance from this event, just like with `fw:builder-type:page-builder:item-type:section:options-modal:settings` event.

I haven't found this event in source code (yet).

Thanks.

**Comment by moldcraft** [comment]
No.

I will create an event.

**Comment by andreiglingeanu** [comment]
Anything new about this?

**Comment by moldcraft** [comment]
Nope

**Comment by moldcraft** [comment]
Events

1. https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/1a56724bd402e1d8a426dd00cfcfb056aae5cb5a/includes/option-types/builder/static/js/builder.js#L1057
2. https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/1a56724bd402e1d8a426dd00cfcfb056aae5cb5a/includes/option-types/builder/static/js/builder.js#L1314

    ```js
    $(document.body).on('fw:option-type:builder:init', function(e, data){
        console.log(data);
    });
    ```

**Comment by danyj** [comment]
@moldcraft , @andreiglingeanu   I am trying to do something like this 
http://prntscr.com/byb1hl

add a custom CSS for the complete page in one of these 2 locations,  ( preferably the one next to full screen ) 
http://prntscr.com/byb2g6

can you guys provide a snipp for it ?

**Comment by danyj** [comment]
I basically need the popup for the options set in one of these locations

**Comment by andreiglingeanu** [comment]
@danyj 
```javascript

$(document.body).on('fw:option-type:builder:init', function(e, data) {
    if (data.builder.get('type') !== 'page-builder') {
        return;
    }

    builderData = data;

    $('#fw-option-page-builder .fw-builder-header-tools .fw-builder-header-post-preview-button').remove();

    $('#fw-option-page-builder .fw-builder-header-tools .template-container').before(
        $('<button>', {
            class: 'button fw-pull-right',
            html: 'HTML'
        })
    );
});
```
