### ISSUE TITLE
Fonts not loading on Https sites

### ISSUE THREAD

**Issue by jsrothwell** [ThemeFuse/Unyson#1134]
When I try to load up a Unyson powered site on IE and FF for the mac I encounter a mixed content warning. 

Are google fonts loaded by http by default and how can this be changed so it works on a secure url?

**Comment by jsrothwell** [comment]
My current temporary fix. I changed all http references to https in my copy of unyson. Hopefully a better solution arises.

**Comment by moldcraft** [comment]
It will arise for sure (I haven't inspected this yet)

**Comment by moldcraft** [comment]
I search unyson and all extensions and found only these 2 places with hardcoded `http://` [#1](https://github.com/ThemeFuse/Unyson-Styling-Extension/commit/df58b194114863cb6a18a468c0977905fbb79773) [#2](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/453bdc62307b4cb64577ffa31e357a4c616a1de6)

Can you give us a link to a site with this problem so I can understand better where it comes from?
