### ISSUE TITLE
"error: undefined" on Page Builder shortcode modal window

### ISSUE THREAD

**Issue by gianlucaponti** [ThemeFuse/Unyson#1136]
Just published on the production server a simple website with Unyson and Page Builder extension, and found a problem I can't resolve.
Clicking on the gear on many of the shortcode extension of the PB, I've got an error "error: undefined" loading the shortcode content. (this happens on many of the shortcode, like Divider, Special Heading, Icon, Icon Box, but not in other kind like: Accordion, Team member, Testimonial, Text Block or my custom shortcodes).

I have done many tests even with a clean D, a default theme (twentyfifteen) with only Unyson Framework Plugin installed and removing all my custom extension and settings, but the error is always there.

I've tested the theme in 2 different machine before publishing (my dev laptop and a dedicated Ubuntu server on Google Cloud) and everything works fine. 

Looking at Chrome Console, there is a 404 error during the ajax-post.php that load the Modal Window content.

I really have no idea why this is not working, since I've been using this identical configuration in many other websites.

Please help me!
Thanks a lot!

Here the posted data, that in my opinion are not different from other data posted from working shortcodes:

**GENERAL**
```
Request URL:http://alaskatrasporti.com/wp-admin/admin-ajax.php
Request Method:POST
Status Code:404 Not Found
Remote Address:185.2.4.12:80
```

**RESPONSE HEADER**
```
Cache-Control:no-cache, must-revalidate, max-age=0
Connection:close
Content-Type:text/html; charset=UTF-8
Date:Fri, 18 Dec 2015 10:13:50 GMT
Expires:Wed, 11 Jan 1984 05:00:00 GMT
Link:<http://alaskatrasporti.com/wp-json/>; rel="https://api.w.org/"
Pragma:no-cache
Server:Apache
Set-Cookie:_icl_current_language=it; expires=Sat, 19-Dec-2015 10:13:50 GMT; Max-Age=86400; path=/
Set-Cookie:_icl_current_language=it; expires=Sat, 19-Dec-2015 10:13:50 GMT; Max-Age=86400; path=/
Transfer-Encoding:chunked
X-Powered-By:PHP/5.6.16
```

**REQUEST HEADER**
```
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:it,en-US;q=0.8,en;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Content-Length:909
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:wordpress_cff9851fe62e6952388c9863f64be823=superadmin%7C1450604650%7Chf6qs1uIknUnWrCHN16MRfu21HGCwJT0FIaGBev6N3a%7Cfc8cbea0486226678f9c29fddfee778547a0f27bdb43617865f538bcdd312c94; PHPSESSID=lfa9eh06s3hb3kvkujlbuaqdb1; wp-settings-2=editor%3Dtinymce; wp-settings-time-2=1450190538; viewed_cookie_policy=yes; wp-settings-1=hidetb%3D1%26editor%3Dtinymce%26libraryContent%3Dbrowse; wp-settings-time-1=1450376874; adminer_version=0; _ga=GA1.2.383975422.1450374996; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_cff9851fe62e6952388c9863f64be823=superadmin%7C1450604650%7Chf6qs1uIknUnWrCHN16MRfu21HGCwJT0FIaGBev6N3a%7C9f1bec08412810d27ab38a348b0c411e4aa44f1203960f5be4df9773cc3b7bf2; _icl_current_language=it; _icl_current_admin_language_d41d8cd98f00b204e9800998ecf8427e=it
Host:alaskatrasporti.com
Origin:http://alaskatrasporti.com
Pragma:no-cache
Referer:http://alaskatrasporti.com/wp-admin/post.php?post=5&action=edit&lang=it
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
X-Requested-With:XMLHttpRequest
```

**FORM DATA**
```
action:fw_backend_options_render
options:[{"style":{"type":"multi-picker","label":false,"desc":false,"picker":{"ruler_type":{"type":"select","label":"Ruler Type","desc":"Here you can set the styling and size of the HR element","choices":{"line":"Line","space":"Whitespace"}}},"choices":{"space":{"height":{"label":"Height","desc":"How much whitespace do you need? Enter a pixel value. Positive value will increase the whitespace, negative value will reduce it. eg: '50', '-25', '200'","type":"text","value":"50"}}}}}]
values[style][ruler_type]:line
values[style][space][height]:50
data[name_prefix]:fw_edit_options_modal
data[id_prefix]:fw-edit-options-modal-
```

![screen shot 2015-12-18 at 10 57 38](https://cloud.githubusercontent.com/assets/13873726/11894640/e28232e0-a578-11e5-8036-1603fa970ddb.png)

**Comment by gianlucaponti** [comment]
Just to add some more informations: 
I am running WP 4.4 with Unyson 2.4.14 with only PageBuilder extension installed.

**Comment by moldcraft** [comment]
Hello,

please execute the below code in browser console

```js
jQuery.ajax({
	url: '/wp-admin/admin-ajax.php',
	type: 'POST',
	data: {
		action: 'fw_backend_options_render',
		options: JSON.stringify({test:{type:'text'}}),
		values: {},
		data: {
			name_prefix: 'fw_edit_options_modal',
			id_prefix: 'fw-edit-options-modal-'
		}
	},
	dataType: 'json',
	success: function (response, status, xhr) {
		console.log(response);
	},
	error: function (xhr, status, error) {
		console.log(error);
	}
});
```

also try to find why [this method](https://github.com/ThemeFuse/Unyson/blob/v2.4.14/framework/core/components/backend.php#L1100) is not executed, or send me the admin/ftp access details for site to `moldcraft[at]email.com` and I will do it myself

**Comment by gianlucaponti** [comment]
Hi Moldcraft,
thank you for your support.

Executing the code in the console there are no errors. 
The response text of the first log is: 
```
"{"success":true,"data":{"html":"<div class=\"fw-backend-option fw-backend-option-design-default fw-backend-option-type-text fw-row\" id=\"fw-backend-option-fw-edit-options-modal-test\">\n\t\t\t<div class=\"fw-backend-option-label fw-col-xs-12 fw-col-sm-3 fw-col-lg-2\">\n\t\t\t<div class=\"fw-inner\">\n\t\t\t\t<label for=\"fw-edit-options-modal-test\">Test<\/label>\n\t\t\t\t\t\t\t\t<div class=\"fw-clear\"><\/div>\n\t\t\t<\/div>\n\t\t<\/div>\n\t\t<div class=\"fw-backend-option-input fw-backend-option-input-type-text fw-col-xs-12 fw-col-sm-9 fw-col-lg-10 width-type-fixed\">\n\t\t<div class=\"fw-inner fw-pull-left\">\n\t\t\t\t\t\t<div class=\"fw-inner-option\">\n\t\t\t\t<input name=\"fw_edit_options_modal[test]\" id=\"fw-edit-options-modal-test\" class=\"fw-option fw-option-type-text\" value=\"\" type=\"text\" \/>\t\t\t<\/div>\n\t\t\t<div class=\"fw-clear\"><\/div>\n\t\t<\/div>\n\t\t<div class=\"fw-clear\"><\/div>\n\t<\/div>\n\t<div class=\"fw-clear\"><\/div>\n\t\t<div class=\"fw-clear\"><\/div>\n<\/div>"}}"
```

the second log is:
```
success: true
```

I'm sending you all the admin/ftp access to the website right now.
Than you very much!

**Comment by moldcraft** [comment]
```js
// works
//var options = {test:{type:'text'}};

// doesn't work
var options = [{"label":{"label":"Button Label","desc":"This is the text that appears on your button","type":"text","value":"Submit"}},{"link":{"label":"Button Link","desc":"Where should your button link to","type":"text","value":"#"}},{"target":{"type":"switch","label":"Open Link in New Window","desc":"Select here if you want to open the linked page in a new window","right-choice":{"value":"_blank","label":"Yes"},"left-choice":{"value":"_self","label":"No"}}},{"color":{"label":"Button Color","desc":"Choose a color for your button","type":"select","choices":{"":"Default","black":"Black","blue":"Blue","green":"Green","red":"Red"}}}];

jQuery.ajax({
    url: '/wp-admin/admin-ajax.php',
    type: 'POST',
    data: {
        action: 'fw_backend_options_render',
        options: JSON.stringify(options),
        values: {},
        data: {
            name_prefix: 'fw_edit_options_modal',
            id_prefix: 'fw-edit-options-modal-'
        }
    },
    dataType: 'json',
    success: function (response, status, xhr) {
        console.log(response);
    },
    error: function (xhr, status, error) {
        console.log(error);
    }
});
```

I don't know why it happens. Looks weird. Maybe you have set custom limitations on sever?

**Comment by gianlucaponti** [comment]
doing some deep testing with the code you suggest, I found this specific case that fires the error code:

```javascript
// works
//var options = {"test":{"type":"selec_"}};

// doesn't work
var options = {"test":{"type":"select"}};
jQuery.ajax({
    url: '/wp-admin/admin-ajax.php',
    type: 'POST',
    data: {
        action: 'fw_backend_options_render',
        options: JSON.stringify(options),
        values: {},
        data: {
            name_prefix: 'fw_edit_options_modal',
            id_prefix: 'fw-edit-options-modal-'
        }
    },
    dataType: 'json',
    success: function (response, status, xhr) {
        console.log(response);
    },
    error: function (xhr, status, error) {
        console.log(error);
    }
});
```

It looks like there is a sensible "string" that the server deny: *select*

I really don't know why and if there is any specific reason, may be any security reason?
But this could be a starting point to investigate and eventually report to the hosting manager.

I don't think i can make a "workaround" renaming any select present in any shortcode with something else..

Thanks for your support!

**Comment by moldcraft** [comment]
Maybe the hosting has a security check for all $_GET and $_POST variables for mysql keyworks (SELECT, UPDATE, DELETE, ...) for the purpose of preventing mysql injections. Ask them about that.

**Comment by gianlucaponti** [comment]
I was supposing something like that.. and doing some googling about security restriction.

[ps. never trust clients hosting... ;-) - joking of course!]

If you want, you can consider this issue closed, I will post any further info I can found about this just to complete the info on this page.

**Comment by gianlucaponti** [comment]
Hi moldcraft,

I'm replying to this post only now because it took some time to find what was causing this problem and maybe what I found can be useful to you.

Just a short recap: thanks to your suggestions I found that any POST on the server hosting my website (a shared  - low cost - hosting on a big Italian company) containing the string "select" (text with double quote) was returning a 404 error.

Isolated the problem I contacted the support that suggested me to disable an option on the cPanel used to manage the domain settings.
The option that cause the problem is "ModSecurity".
Searching online I found that this option enables a set of rules related to the Apache module mod_security but these rules are defined at server level not domain level, so I cannot see which rule is returning the 404 error.

On the last 30 days the Unyson framework has worked fine for some days and stopped working just a few days ago, so I'm thinking that these rules are changing on cPanel Updates basis.
Actually the version in cPanel 11.52.2.2.

I decided to reply this issue because I think that if there are some restriction on posting data whits some version of cPanel, this problem can affect other websites than mine.

I don't know if there is any possibilities to change the posted data, changing the 'sensible' key "select" whits some other value to avoid collision with SLQ Injection restrictions, in future version of the framework.

Hope this can help.
Please contact me if you need any further information.

**Comment by moldcraft** [comment]
Hello,

Thank you for details. But I don't see a solution for this. 

_SQL injection is possible when the php code is bad written, not escaped/prepared sql is a mistake done by beginners, we don't do that. If you'll find a weak sql in our code, please report or submit a pull request._

**Comment by gianlucaponti** [comment]
Absolutely no weak code in my opinion! 

I think that the set of rules used by mod_security in cPanel are returning some false-positive that are colliding with the ajax post used in retrieving the content of the shortcodes in the Visual Builder.

In the test file I have done to isolate the problem, even posting a simple html form with a textarea containing the text "select" is returning an error, so is absolutely a "too strict" set of rules in my opinion.

I only would like to inform you in case you receive other notifications.

**Comment by danyj** [comment]
@gianlucaponti , bud , why dont you try and post here https://github.com/SpiderLabs/ModSecurity and see what they tell you. It is good to know where our limits and issues are.

**Comment by gianlucaponti** [comment]
@danyj, thanks! why not! 
but my first thought was ti give you a feedback on what I found, because your framework is awesome in my opinion! :-)

thanks for your great job guys.

**Comment by danyj** [comment]
@gianlucaponti , I am dev like you , but I like to call Unyson ours :)

**Comment by susipop** [comment]
Hello, I found out that in my case, my server is a Unix server, not a Linux server. So, I don't know how or why, it does not like the ajax script. It seems that returns a 500 server error.
I still will solve with my client if we change servers or ask web.com to solve this issue for us.

I hope this helps.
