### ISSUE TITLE
Initial zoom level for map shortcode.

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#1137]
Is there any way to change the default zoom level for map shortcode, some people are saying that it is way too close, they want the map to be zoom out at first once it has been loaded.

**Comment by danyj** [comment]
you have to override map shortcode and add zoom level yourself. 
add map zoom slider option type 
http://prntscr.com/9fmajg
http://manual.unyson.io/en/latest/options/built-in-option-types.html#slider

than in view.php add 


	$map_zoom 			= fw_akg('map_zoom',$atts);
	$map_data_attr['data-map-zoom'] = $map_zoom;

than in scripts.js you need to set this 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/map/static/js/scripts.js

to something like 


    parseInt($mapWrapper.data('map-zoom'))

**Comment by moldcraft** [comment]
@danyj Thank you

**Comment by mbtocalli** [comment]
I followed your instructions but I can't get the map to show the selected zoom (4).
The html code shows data-map-zoom=4, but the rendered map seems to be at 12.
`<div class="fw-map" data-locations="[{"title":"","url":"","thumb":false,"coordinates":{"lat":-52.9432618,"lng":-80.6744003},"description":""}]" data-map-type="ROADMAP" data-map-height="400" data-gmap-key="MY_GMAP_KEY" data-map-zoom="4" data-disable-scrolling="" data-map-style="">`

I can't figure it out how to change the scripts.js file.
Any help on this? thanks
