### ISSUE TITLE
Portfolio script not GPL?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1141]
mixItUp  is not free for commercial use, why are we using it in the scratch theme and pushing its license?
https://mixitup.kunkalabs.com/licenses/

https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/portfolio/static/js/jquery.mixitup.min.js#L8-L9

**Comment by moldcraft** [comment]
Scratch theme is commercial?

**Comment by danyj** [comment]
No is not but why are we as GPL product pushing a commercial one. Shouldn't all our scripts be GPL , MIT  etc, not commercial ones.

**Comment by moldcraft** [comment]
We will try to find another script or figure out a page to indicate all third-party scripts and their licenses.

**Comment by danyj** [comment]
> indicate all third-party scripts and their licenses.

that would make more sense since anyone who is using this script  now and wants to publish on TF will have trouble. Especial if they purchased license and did not read this 

![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/11919505/77c97934-a755-11e5-805e-29f3defc82f5.jpg)

**Comment by danyj** [comment]
Isotope is GPL http://isotope.metafizzy.co/license.html and devloper license is transferable , we used it since few years on our joomla templates 

![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/11919605/19f827e0-a757-11e5-9946-a4c761330ff9.jpg)

**Comment by duongancol** [comment]
:+1:  for Isotope, I also uses it.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Scratch-Theme#third-party-libraries
