### ISSUE TITLE
How to add option types in portfolio category/items edit?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1143]
Can we please get some info on how to add custom option types to portfolio category and or portfolio items.

**Comment by danyj** [comment]
for portfolio it is , 

    framework/theme/options/taxonomies/fw-portfolio-category.php

 this should not be a guessing game , please post info how to set and get those options. 
I went trough 

portfolio
fw-portfolio
category 
portfolio-category 

to find the right one

and this is very confusing 


here we have no additional views 

https://github.com/ThemeFuse/Unyson-Portfolio-Extension/tree/master/views


here you made own thing  and content view is not there 


https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-parent/framework-customizations/extensions/portfolio/views

there is no clear path and no info how it is done right.

**Comment by moldcraft** [comment]
The developer that created the portfolio extension is not in our team anymore. But I don't have time to inspect the extension. Sorry

**Comment by danyj** [comment]
@moldcraft  ok can you ad least tell me how you are getting any taxonomy options in frontend.

**Comment by danyj** [comment]
@moldcraft   got it 

    fw_print(fw_get_db_term_option($term_id, $taxonomy));

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/extension/portfolio/index.html#views
