### ISSUE TITLE
Can we have fw_admin_enqueue_scripts for taxonomy please

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1144]
Can we have these for taxonomy  please. 
https://github.com/ThemeFuse/Unyson/search?utf8=%E2%9C%93&q=fw_admin_enqueue_scripts

**Comment by moldcraft** [comment]
Github search skipped this https://github.com/ThemeFuse/Unyson/blob/v2.4.14/framework/core/components/backend.php#L1087

**Comment by danyj** [comment]
ok , how about portfolio and events category ?

**Comment by moldcraft** [comment]
More detailed please (I am not expert in Portfolio and Events extensions).

**Comment by danyj** [comment]
sorry , on Edit Category  in portfolio and events I need the hook to load admin scripts http://prntscr.com/cnh4t2

**Comment by danyj** [comment]
http://prntscr.com/cnh528

**Comment by moldcraft** [comment]
[Same hook](https://github.com/ThemeFuse/Unyson/blob/7de5ae9f0e9fd65e49e71284d983e497e3d9e172/framework/core/components/backend.php#L1180)

**Comment by danyj** [comment]
works thnx!
