### ISSUE TITLE
Addable option question

### ISSUE THREAD

**Issue by SilentAce** [ThemeFuse/Unyson#1145]
Hi,

This is your demo code from the demo page

    'demo_addable_option_2'            => array(
		'label'  => __( 'Addable Option', 'unyson' ),
		'type'   => 'addable-option',
		'option' => array(
			'type' => 'text',
		),
		'value'  => array( 'Option 1', 'Option 2', 'Option 3' ),
		'desc'   => __( 'Lorem ipsum .', 'unyson' ),
	),

Is it possible in the 'option' => array( 'type' => 'text', )  to add more option types such as upload? I tried to add type upload after the text but it didn't worked.

Thanks

**Comment by moldcraft** [comment]
```php
'option' => array(
    'type' => 'upload',
),
```

should work.

You can't add more that one option there, for multiple options use option type `addable-popup` or `addable-box`

**Comment by SilentAce** [comment]
Thanks that's what i wanted to know.
