### ISSUE TITLE
Failed to access Github repository

### ISSUE THREAD

**Issue by Mkriiis** [ThemeFuse/Unyson#1150]
Hello. I have error "Failed to access Github repository "ThemeFuse/Unyson-******-Extension" releases. (connect() timed out!)" when I intstall any extension. How can I fix it?
![screenshot-hunterbit tk 2015-12-22 15-08-24](https://cloud.githubusercontent.com/assets/16401371/11955852/0daeb5ea-a8be-11e5-8dd4-93492867cb6c.png)

**Comment by moldcraft** [comment]
Hello,

It looks like your server internet connection is slow.
