### ISSUE TITLE
Failed to connect to github-api-cache.unyson.io port 80: Connection refused

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1154]
Hello
One of my client getting issue when they tried to install extension. http://puu.sh/m677E/ad78ccb7c2.png

What can be the issue ?

Thanks

**Comment by moldcraft** [comment]
Hi,
Please add in `{theme}/functions.php`

```
add_action('fw_init', function(){
    fw_print(file_get_contents('http://github-api-cache.unyson.io'));
});
```

I think the server can't reach `http://github-api-cache.unyson.io`, we need to find why and to report that to hosting support

**Comment by Ataurr** [comment]
Print value showing "false"

**Comment by moldcraft** [comment]
Please set in `wp-config.php` `WP_DEBUG` to `true` and run the above code again, maybe you will see some error messages. If not, add in `wp-config.php`

```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
```

**Comment by moldcraft** [comment]
Also try

```php
fw_print(wp_remote_get('http://github-api-cache.unyson.io/'));
```

**Comment by Ataurr** [comment]
with get contents
<pre>Warning: file_get_contents(http://github-api-cache.unyson.io): failed to open stream: Connection refused in /home/vhosts/huidenmeer.nl/httpdocs/Wordpress/wp-content/themes/wellnesscenter/functions.php on line 125</pre>

with remote

<pre>WP_Error
(
    [errors] => array
    (
        [http_request_failed] => array
        (
            [0] => 'Failed to connect to github-api-cache.unyson.io port 80: Connection refused'
        )
    )
    [error_data] => array()
)</pre>

**Comment by moldcraft** [comment]
The site works for sure, you can open it in browser http://github-api-cache.unyson.io so the server is blocking requests to it. Please contact the hosting support and tell them about the problem.
