### ISSUE TITLE
There Is No Mega Menu

### ISSUE THREAD

**Issue by Newwaybiz** [ThemeFuse/Unyson#1156]
In Unyson, there is Mega Menu!?

**Comment by llemurya** [comment]
@Newwaybiz please see our documentation about [Mega Menu](http://manual.unyson.io/en/latest/extension/megamenu/index.html?highlight=megamenu)

**Comment by moldcraft** [comment]
Read please the **IMPORTANT** box from docs page

**Comment by Newwaybiz** [comment]
Thank you! Understood!
