### ISSUE TITLE
Completely overwriting extension

### ISSUE THREAD

**Issue by Code-Divine** [ThemeFuse/Unyson#1158]
Hello,

1. I would like to completely overwrite the events extension, that is to create a new extension but using the same "Events" name. I've added my own child manifest.php and class files in an "events" folder under my framework-customizations folder buy they don't seem to overwrite the ones in the parent framework directory.

2. I know I can mark which extensions are supported by my theme but they are still displayed the the fw-extensions page and can be activated. I think removing the marker " Compatible with your current theme" in some cases would not be enough and extensions not marked as supported should be hidden from sight.

Thanks!

**Comment by moldcraft** [comment]
Hi,

A fast solution would be to hide the extension with css.

**Comment by moldcraft** [comment]
Also better prefix your extension name, the directory name should be `{your-prefix}-events`
