### ISSUE TITLE
Failed to install supported extensions. Sidebars, Portfolio, Page-builder, Backups, Seo, Forms, Mailer, Slider, Events, Analytics, Megamenu, Social

### ISSUE THREAD

**Issue by colettehapi** [ThemeFuse/Unyson#1160]
hi

i just uploaded a theme unto my WP site but when i try to download the extension i get the following message: "Failed to access Github repository "ThemeFuse/Unyson-Sidebars-Extension" releases.", making it impossible to activate the demo site. How do i fix this issue?

**Comment by moldcraft** [comment]
Please, add the following code in `{theme}/functions.php`

```php
add_action('fw_init', function(){
    fw_print(
        wp_remote_get(
            'http://github-api-cache.unyson.io/repos/themefuse/unyson/releases'
        )
    );
});
```

and show us the output

**Comment by colettehapi** [comment]
hi, i tried inputting the code in the functions file but i get a black
screen at the top of my dashboard:
[image: Inline image 1]

**Comment by moldcraft** [comment]
What's in that black screen? Can you make a screenshot?

**Comment by colettehapi** [comment]
still getting these messages when attempting to download the extensions:
"Downloading the "Sidebars" extension...

Failed to access Github repository "ThemeFuse/Unyson-Sidebars-Extension"
releases.


   - Failed to access Github repository
   "ThemeFuse/Unyson-Sidebars-Extension" releases.

"

**Comment by colettehapi** [comment]
i sent a picture with the previous email...

**Comment by moldcraft** [comment]
> still getting these messages when attempting to download the extensions

The above code is not a fix, is just a way to find the problem.

> i sent a picture with the previous email...

Sorry but I don't see any picture

![](https://static.md/06043ecea91d2f9fd013866dadb2378d.png)

**Comment by colettehapi** [comment]
OK im attaching it:

**Comment by moldcraft** [comment]
I don't think that attaching will work here, since your emails are converted to comments and the attachments are lost.

Please upload your screenshot to an image hosting and give us the link

**Comment by colettehapi** [comment]
http://postimg.org/image/km30i9nyh/

**Comment by moldcraft** [comment]
Thank you, but it doesn't show any details.

1. Please set in `wp-config.php` `WP_DEBUG` to `true` and run the code again, maybe that will print some error message.
2. Are you able to download/install WordPress plugins from admin page?

**Comment by colettehapi** [comment]
yes i am able to install plugins from my admin page
am i making the alterations directly from the wordpress editor or through a
file in my template folder?

**Comment by moldcraft** [comment]
The [`wp-config.php`](https://codex.wordpress.org/Editing_wp-config.php) file is located in root directory. I don't think you can edit it from wordpress editor.

**Comment by colettehapi** [comment]
ok

i made the change through my hosting account, but i have yet to see a
change...

**Comment by moldcraft** [comment]
Can you give us a screenshot again?

**Comment by colettehapi** [comment]
http://postimg.org/image/qxoj2l6u5/

still getting this:
http://postimg.org/image/o3njf3xmj/

**Comment by moldcraft** [comment]
Please change the code to 

```php
add_action('fw_init', function(){
    fw_print(
        wp_remote_get(
            'https://google.com'
        )
    );
});
```

and make a screenshot again

**Comment by colettehapi** [comment]
http://postimg.org/image/i96whenon/

am I doing something wrong? because so far i have not seen any change (good
or bad)

http://postimg.org/image/4exev43lr/

**Comment by moldcraft** [comment]
Again, that code will not fix the problem, don't try to install extensions. I just want to figure out why request to external sites don't work on your server, but so far I haven't seen any error message, they just don't work, very strange.

Please contact your hosting support and tell them that the above code doesn't work and show them the screenshot, or give the link to your site so they can see the problem themselves.

**Comment by colettehapi** [comment]
ok great! thank you for that! I was able to enable the connection from the
server side and now i get this on my dashboard,

http://postimg.org/image/40d210655/

**Comment by colettehapi** [comment]
http://postimg.org/image/wtto8qsfp/

**Comment by moldcraft** [comment]
Now try to install extensions, it should work

**Comment by moldcraft** [comment]
And remove that code from `{theme}/functions.php`

**Comment by colettehapi** [comment]
i apologize for this but now this is coming up:
http://postimg.org/image/q30txnqnx/

**Comment by moldcraft** [comment]
Please add [here](https://github.com/ThemeFuse/Unyson/blob/v2.4.14/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2503) `fw_print($response);` and try to install an extension

**Comment by colettehapi** [comment]
http://postimg.org/image/3n8ulsvzh/

**Comment by moldcraft** [comment]
Same problem.

Your server is blocking the request

**Comment by colettehapi** [comment]
http://postimg.org/image/qsw1nts27/

**Comment by moldcraft** [comment]
`response[code]` is 0, that is an invalid value, it must be 200.

Can you tell what's the actual problem with the server? Are you using safe mode or something, or it's a custom built/compiled php version?

**Comment by colettehapi** [comment]
no I'm not sure what is going on with the server, I do not believe that I
am in safe mode and I have not customized anything.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1160#issuecomment-167934769
>
> I was able to enable the connection from the server side

How you did that and what was the problem?

**Comment by colettehapi** [comment]
everything is good now! thank you very much for your assistance and for
your patience. You were amazing! thank you!

**Comment by moldcraft** [comment]
Glad I could help.

Can you share what was the actual problem?

**Comment by colettehapi** [comment]
I believe the issue was on my host panel.So I contacted my host company and
this is the solution they provided: "There were two github hosts that were
blocked by the Outgoing Connections filter of your hosting account."

**Comment by moldcraft** [comment]
Thank you

**Comment by oskerlau** [comment]
Still got the same error, enabled to black box, this is what it says>>
```

array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary
    (
        [*:data] => array
        (
            [content-length] => '1103'
            [content-type] => 'text/html; charset=UTF-8'
            [date] => 'Tue, 18 Jul 2017 23:45:45 GMT'
            [alt-svc] => 'quic=":443"; ma=2592000; v="39,38,37,36,35"'
        )
    )
    [body] => '<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>'
    [response] => array
    (
        [code] => 403
        [message] => 'Forbidden'
    )
    [cookies] => array()
    [filename] => null
    [http_response] => WP_HTTP_Requests_Response
    (
        [*:response] => Requests_Response
        (
            [body] => '<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>'
            [raw] => 'HTTP/1.1 403 Forbidden
Content-Length: 1103
Content-Type: text/html; charset=UTF-8
Date: Tue, 18 Jul 2017 23:45:45 GMT
Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
Connection: close

<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>'
            [headers] => Requests_Response_Headers
            (
                [*:data] => array
                (
                    [content-length] => array
                    (
                        [0] => '1103'
                    )
                    [content-type] => array
                    (
                        [0] => 'text/html; charset=UTF-8'
                    )
                    [date] => array
                    (
                        [0] => 'Tue, 18 Jul 2017 23:45:45 GMT'
                    )
                    [alt-svc] => array
                    (
                        [0] => 'quic=":443"; ma=2592000; v="39,38,37,36,35"'
                    )
                )
            )
            [status_code] => 403
            [protocol_version] => 1.1
            [success] => false
            [redirects] => 0
            [url] => 'https://google.com/'
            [history] => array()
            [cookies] => Requests_Cookie_Jar
            (
                [*:cookies] => array()
            )
        )
        [*:filename] => null
        [data] => null
        [headers] => null
        [status] => null
    )
)
```
