### ISSUE TITLE
Impossible to reset portfolio pagination 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1161]
I need to set number of post per page for portfolio extension. Currently it works only with blog default 

    Reading Settings->Blog pages show at most

so I tough to use my own query  which works fine to show specific number of posts but the pagination  is not reset  to use the new query. 

I have 20 items in 2 categories 

the query 

	$posts_per_page  = 3;
	$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
	$tax_query = array();
	
	if ( $term_id != '0' ) {
		$tax_query = array(
			array(
				'taxonomy' => 'fw-portfolio-category',
				'field'    => 'id',
				'terms'    => $term_id
			)
		);
	}
	
	$args = array(
	  'posts_per_page'  => $posts_per_page,
	  'post_type'  		=>  'fw-portfolio',
	  'orderby'    		=>  'date',
	  'order'      		=>  'desc',
	  'paged'			=>$paged,
	  'tax_query'  		=> $tax_query
	);
	
	$query = new WP_Query( $args );

after the loop 

	<?php
	$big = 999999999; // need an unlikely integer
	 echo paginate_links( array(
		'base' => str_replace( $big, '%#%', get_pagenum_link( $big ) ),
		'format' => '?paged=%#%',
		'current' => max( 1, get_query_var('paged') ),
		'total' => $query->max_num_pages
	) );
	?>

all looks fine 

![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/12007547/e4d0576a-ac09-11e5-864e-cdb34b5690db.jpg)

but  only page 2 works ,  page 3 is not found due to this not being reset 

![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/12007550/08e5ee44-ac0a-11e5-923e-241168436315.jpg)

I tried this and just changed the post_type to fw_portfolio ,  same thing , page 3 and up is dead. 

http://wordpress.stackexchange.com/a/43931/67176

any help is appreciated.

**Comment by duongancol** [comment]
Hi bud, Please try this:
```php
 global $wp_query;
		$big = 999999999; // need an unlikely integer

		$pages = paginate_links( array(
			'base' => str_replace( $big, '%#%', esc_url( get_pagenum_link( $big ) ) ),
			'format' => '?paged=%#%',
			'current' => max( 1, get_query_var('paged') ),
			'total' => $wp_query->max_num_pages,
			'type'  => 'array',
		) );
```

**Comment by danyj** [comment]
@duongancol  I tried all of those  bud, thing is that we cant change anything from the template because we fire to late there , I had to do this 

@moldcraft  do you think this is ok?



    /**
	 * Set portfolio posts per page
	 */ 

	function thz_portfolio_posts_per_page($query) {
		
		$taxonomy        	= 'fw-portfolio-category';
		if(isset($query->query[$taxonomy])){
			
			$term            	= get_term_by( 'slug', $query->query[$taxonomy], $taxonomy );
			$term_id         	= ( ! empty( $term->term_id ) ) ? $term->term_id : 0;
			$cat_options		= fw_get_db_term_option($term_id, $taxonomy);
			$posts_per_page		= thz_akg('posts_per_page',$cat_options);
		
			$query->set('posts_per_page', $posts_per_page);
		}
	}
	add_action( 'pre_get_posts', 'thz_portfolio_posts_per_page' );


and in cat I added post per page option http://prntscr.com/9kb5oy
