### ISSUE TITLE
Table Editor: additional spaces and feature request (if possible)

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1162]
Hello!

I noticed one thing in Table Editor, it adds additional spaces when i edit a table, please see a screenshot https://yadi.sk/i/wRnKtClgmXaS6

And one question, why it is impossible to add a link in table column / row?, e.g. `<a href="http://some-url.com">Click here</a>`. If possible, could you add it in the next update, thank you!

Kind regards, Dmitriy

**Comment by danyj** [comment]
:+1:
