### ISSUE TITLE
Github connection error

### ISSUE THREAD

**Issue by NitaAlexandr** [ThemeFuse/Unyson#1163]
One user had this problem with the TheCore/Unyson package:

```
Failed to access Github repository "ThemeFuse/Unyson-Sidebars-Extension" releases.
```

While installing available extensions for the theme.

Here is an screenshot: http://i.imgur.com/xOlHqHQ.png

**Comment by moldcraft** [comment]
Please, add the following code in `{theme}/functions.php`

```php
add_action('fw_init', function(){
    fw_print(
        wp_remote_get(
            'http://github-api-cache.unyson.io/repos/themefuse/unyson/releases'
        )
    );
});
```

and show us the output

**Comment by NitaAlexandr** [comment]
it gives a result like in the next screenshot: http://i.imgur.com/7vddv7r.png

**Comment by moldcraft** [comment]
Is this the same site/server? https://github.com/ThemeFuse/Unyson/issues/1160#issuecomment-167643138

**Comment by NitaAlexandr** [comment]
yes, it is the same....
