### ISSUE TITLE
Problem with Switch option in update 2.4.14

### ISSUE THREAD

**Issue by RodalErmakov** [ThemeFuse/Unyson#1164]
Hi)

I have used this option in my theme:

'berg_white_txt' => array(
		'label'        => esc_html__('White Text', 'berg'),
		'type'         => 'switch',
	),

but after last update it doesn't work

**Comment by moldcraft** [comment]
Hello,

1. I added in `{theme}/framework-customizations/theme/options/settings.php`

    ```php
	$options = array(
		'berg_white_txt' => array(
			'label' => __('White Text', 'berg'),
			'type' => 'switch',
		),
	);
    ```

2. Added in `{theme}/functions.php`

    ```php
	add_action('init', function(){
		if (empty($_POST)) fw_print(
			fw_get_db_settings_option('berg_white_txt')
		);
	});
    ```

3. And everything works fine

    ![](https://static.md/3a979d60174b374eb36c987bc4e4ac6a.png)

**Comment by moldcraft** [comment]
> but after last update **it doesn't work**

more details please

**Comment by RodalErmakov** [comment]
Hi) Thanks for your answer.

Yes it works in theme settings but it doesn't work in page builder.
For example I created Section in Page builder then I switched on "White
Text" and clicked save. But when I opened Section settings again White Text
wasn't changed. It was switched off.

But if I use
'berg_white_txt' => array(
        'label'        => esc_html__('White Text', 'berg'),
        'type'         => 'switch',
        'left-choice'  => array(
                            'value' => 'enabled',
                            'label' => __( 'Yes', 'fw' ),
                        ),
        'right-choice' => array(
                            'value' => 'disabled',
                            'label' => __( 'No', 'fw' ),
                        )
    ),
instead
'berg_white_txt' => array(
        'label'        => esc_html__('White Text', 'berg'),
        'type'         => 'switch',
    ),


it works correctly.

But I use this simple option:
'berg_white_txt' => array(
        'label'        => esc_html__('White Text', 'berg'),
        'type'         => 'switch',
    ),
in all my theme and it is too hard to change all my options.

Is there simple way to fix it?

Thanks)

**Comment by RodalErmakov** [comment]
..and there are not any problem before last update...

**Comment by RodalErmakov** [comment]
also I have found "simple switch" in your shortcodes (section and special-heading)
If you add section and switch Full width on, save and then reopen full width option will not be changed.

**Comment by moldcraft** [comment]
Please [download](https://github.com/ThemeFuse/Unyson/archive/master.zip) the latest Unyson dev version, extract in `wp-content/plugins/unyson` and test all your shortcode modal options if the save works fine

**Comment by RodalErmakov** [comment]
Yes it works, 
Thank you very much)
