### ISSUE TITLE
Cant install compatible extesions IOS Yosemite XAMP

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1166]
I am trying since 2 hours now and it is impossible  to install compatible extensions. 
http://prntscr.com/9jvvok

checked files permission , uploads , folders , chmod everything  on xamp several times , restarted server anything I can find and think of and this is just not happening. 

Any suggestions?

**Comment by danyj** [comment]
stupid thing , deleted unyson plugin , downloaded , installed , worked. why ?

**Comment by moldcraft** [comment]
I think permissions

**Comment by danyj** [comment]
ut how if I was messing with it for 2 h, changing everything , testing uploads and other plugins. why did I had to delete unyson completely and reinstall everything , makes no sense
