### ISSUE TITLE
How to disable a built-in child extension

### ISSUE THREAD

**Issue by Taimurian** [ThemeFuse/Unyson#1167]
How to disable a built-in child extension or extension type. in my case I want to create my own custom slider type and disable the 3 built-in slider types ( bx-slider, nivo-slider & owl-carousel ).
Any ideas?

Thanks

**Comment by llemurya** [comment]
@Taimurian please see this [issue](https://github.com/ThemeFuse/Unyson/issues/391).Hope this helps.

**Comment by Taimurian** [comment]
@llemurya it works perfectly .. Thank you so much
