### ISSUE TITLE
Switch option type not displaying correctly

### ISSUE THREAD

**Issue by Taimurian** [ThemeFuse/Unyson#1171]
The switch option will not display correctly if you add it to the first slider type. but for the other types it works properly.

![untitled-7](https://cloud.githubusercontent.com/assets/1550077/12070510/5dd5d04c-b081-11e5-9d50-3d71276dfbb9.png)
![untitled-8](https://cloud.githubusercontent.com/assets/1550077/12070511/5eb0488a-b081-11e5-80c1-b073a41cdc55.png)

**Comment by moldcraft** [comment]
Fixed https://github.com/ThemeFuse/Unyson/commit/dfc4a906169f00b47f1e9a9983bf93778ce0c983

Please download the [latest dev version](https://github.com/ThemeFuse/Unyson/archive/master.zip) of Unyson, extract it in `wp-content/plugins/unyson` and test if the switch is not duplicated

**Comment by Taimurian** [comment]
It's fixed now .. Thanks

**Comment by zenics** [comment]
Hey @Taimurian would you mind sharing your slider files with me I am trying to use slick slider instead of the default one but I have problem getting it to work.

Thanks

**Comment by Taimurian** [comment]
@zenics 
Here's my slider files which are based on [UIKit Framework](http://getuikit.com). Just extract the file in your theme folder and then customize it to your own liking. If the slider didn't appear then you have to disable/enable the slider extension from Unyson extensions page.

[framework-customizations.zip](https://github.com/ThemeFuse/Unyson/files/172692/framework-customizations.zip)

**Comment by zenics** [comment]
Thanks @Taimurian :+1:

**Comment by zenics** [comment]
getting an error on array_flatten function

**Comment by Taimurian** [comment]
@zenics 
I used this helper function to extract the options array values. Just past it in your functions.php

`if ( ! function_exists( 'array_flatten' ) ){
    function array_flatten($array) { 
      if (!is_array($array)) { 
        return FALSE; 
      } 
      $result = array(); 
      foreach ($array as $key => $value) { 
        if (is_array($value)) { 
          $result = array_merge($result, array_flatten($value)); 
        } 
        else { 
          $result[$key] = $value; 
        } 
      } 
      return $result;    
    } 
}`

**Comment by zenics** [comment]
ooo! I see that make sense thanks dude
