### ISSUE TITLE
One of your customers needs support.

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1172]
@moldcraft  bud you need to respond and assure  your customer that your support answer was a shortcut to issue fix instead some bogus hack or advertising attempt as they see it. 
https://www.facebook.com/groups/wphelpandshare/permalink/741608065972859/

**Comment by moldcraft** [comment]
Thank you, our support team is in contact with him on zendesk

**Comment by danyj** [comment]
glad we could help.
