### ISSUE TITLE
Couldn't resolve host 'github-api-cache.unyson.io

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1173]
I see this on portfolio homepage , 
just started the server on mac and refreshed portfolio category page 
![jhjdhksdjd](https://cloud.githubusercontent.com/assets/2340172/12078317/e458bce2-b20c-11e5-84d1-9b3fccb273af.png)

not sure why our cache depends on unyson.io  domains but it does not seem right. 
please provide more info about it.

**Comment by moldcraft** [comment]
It works http://www.dnswatch.info/dns/dnslookup?la=en&host=github-api-cache.unyson.io&type=A&submit=Resolve

Maybe the internet connection was slow and it timed out.

----

It is used for extension updates check, the results are then cached for 1 day in a wp transient. You said that you just started the server so the cache from yesterday expired and requests to check for new version were made.

**Comment by danyj** [comment]
>Maybe the internet connection was slow and it timed out.

could be , I just opened the flap and hit refresh.

ok update check but why is it shown in frontend?

**Comment by moldcraft** [comment]
> why is it shown in frontend?

1. https://github.com/ThemeFuse/Unyson/blob/v2.4.15/framework/extensions/update/extensions/github-update/class-fw-extension-github-update.php#L184-L191
2. https://github.com/ThemeFuse/Unyson/blob/v2.4.15/framework/helpers/class-fw-flash-messages.php#L311
