### ISSUE TITLE
Theme settings tabs are really slow to load

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#1174]
Hi there, 

We have some customers complaining about the slowness of the Theme Settings pages. 
As we have a lot of options and there is some PHP conditions for some of them and though a lot of JS loaded for the options. It's true that it can take a while as all is loaded in one piece.

Is there any way to deactivate that and have a different page for each tab ? So we don't load all the options but one tab at the time. 

Regards,

2F

----

- [x] Tabs lazy load

    Don not render/init all tabs on page load. Render only visible tabs, then init tab on open.

    - [x]  on/off parameter for this feature in 

        ```php
        // file: {theme}/framework-customizations/theme/config.php

        $cfg['lazy_tabs'] = bool;
        ```
- [x] Render all tabs within some DOM elements from javascript:

    ```js
    fwEvents.trigger('fw:options:init:tabs', {
        $elements: jQuery('.fw-settings-form')
    });
    ```

**Comment by moldcraft** [comment]
Hello,

I will try to output tabs contents in `<div data-tab-html="....">` then in javascript move the attribute value to actual html, doing that for each tab one by one on interval (to prevent load all at once), or if will be possible [on tab focus/open](http://api.jqueryui.com/tabs/#event-activate). So:

1. Initially the tab will be

    ```html
    <div data-html="...html..."></div>
    ```

2. On focus/open/activate it will become

    ```html
    <div>...html...</div>
    ```

**Comment by 2Fwebd** [comment]
Thank you @moldcraft, that'd be perfect !

**Comment by moldcraft** [comment]
[Done](https://github.com/ThemeFuse/Unyson/commit/661b51a9a624161cd6bcb3b0598027fa713920de) (on a [separated branch](https://github.com/ThemeFuse/Unyson/tree/2.5.0))

But there is a problem: Some tabs are "hidden" not rendered, so a lot of inputs are not present in html, and on form submit their values are not sent in POST. 

I will try to listen form submit -> prevent it -> render and init all options -> trigger submit from code. That will "block" the page (because, again, all options will be loaded at the same time) then the form will be submitted

**Comment by danyj** [comment]
>their values are not sent in POST

sorry I cant have this, I have predefined styles sent to a file and this will not send the rest of the tabs

**Comment by moldcraft** [comment]
[Done](https://github.com/ThemeFuse/Unyson/commit/a621d731a004bd25dac2ef8ffaf4e4e3aeb23cdf) -> https://github.com/ThemeFuse/Unyson/issues/1174#issuecomment-168658183

Please download the latest dev version
https://github.com/ThemeFuse/Unyson/archive/2.5.0.zip
and test if the save works fine

**Comment by danyj** [comment]
cant to this man , I made bunch of layout and menu generator options that depend on options being there  , none of them work now, you cant go change this after  one year of development. I made options types depending on admin and now many of them dont work right

**Comment by moldcraft** [comment]
So I should do an on/off parameter for this feature (enabled by default) ?

**Comment by 2Fwebd** [comment]
Hi, 

I'll give it a try now. I think the best way would be to have an option in framework-customizations/theme/config.php

Like : $cfg['settings_form_side_tabs'] = true;

**Comment by danyj** [comment]
my template generator options is not connected to save but it collects the admin options 

    var templatedata = $(collection + ' :input').serialize().replace(/fwf=[^\&]+\&/, '');


so if they are not rendered they cant be collected , 

I would love to see speed improvement also but I dont think that this is the right solutions. 

yes do on/off ( default off) but this leaves many of us that made custom options types depending on admin without an adequate solution.

**Comment by danyj** [comment]
1. what I think the biggest issue is the initialize , you render html in admin, hide it  and reinitialize everything via js which kills the speed. It is not noticeable on 10-50 options , 
but 2F has many as he said and I have 192 , that alone is a killer . 
192 seems much when said but those are a joke inputs fields that again depend on initialize. If admin were not so dependent on js it would fly. 

2. the options html i HUGE , for a simple html input we  have this 
http://prntscr.com/9m1h4l

where all that can be done with 3 divs and much smaller css class names. But we have a maze of unnecessary html. These are main speed killers.

**Comment by danyj** [comment]
here , I trimmed down all unnecessary fw-clear ( clear via css after or give those an actual css layout )  4 per option
https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/views/backend-option-design-default.php#L119

desc and help dont need inner 
https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/views/backend-option-design-default.php#L124

https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/views/backend-option-design-default.php#L114

look at this 
http://prntscr.com/9m1zep
http://prntscr.com/9m1zn5

that cuts 30+KB from 470KB page  on 192 options and I did not even touch the tabs and JS

and here is where the mess is 

http://prntscr.com/9m20hb

my admin page actually loads in  1.08sec  ( used to be 3sec before this #958 ) 

but the JS ( show options page + initialize ) slows it down another 0.7sec 

now I stayed away from all speed killers or I made my own option types to increasde the speed,  like slider , spinner , typography , the default ones are still killing it especially  the slider

**Comment by moldcraft** [comment]
Sorry, I designed the html bad at the beginning.

I can do a html refactor and update all js/css selectors, if users will report that their options used selectors dependent on `.fw-backend-option-... > .fw-inner` (or some similar) classes, we will force them to update their selectors to match the new html structure, sounds ok, should I do that?

**Comment by moldcraft** [comment]
Sorry, I designed the html structure bad at the beginning.

I can do a html refactor and update all js/css selectors, if users will report/complain that their options used selectors dependent on `.fw-backend-option-... > .fw-inner` (or some similar) classes, we will force them to update their selectors to match the new html structure. Sounds ok? Should I do that?

**Comment by danyj** [comment]
I dont want to break anyone's html or option that is dependent , but main hooks I used are not inner or the clears so that is why I tested the"fat trim" there. 

Trimming the html , setting class names to normal size  instead of this http://prntscr.com/9m4w0w  and the most important one is letting HTML load without JS dependency since there is no need for it on input, text area , checkbox , radios and all normal form options types is where we should start. 

Only options that need initialize are the  options that their render depend on JS like slider, switch , multi-picker or typography. 

think of this ,  from my 192 options I count 128  text inputs http://prntscr.com/9m4xpe

 , which means there is no need to do js initialize 128 times on admin page. But by default we run initialize on any option type. 

So yes I am for refactor but a smart and precise one , not just a new html tree but a carefully picked scan that we know it wont affect anyone. 


P.S. Thank you for taking every consideration. It means that we deal with someone who cares.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/bb5e98a5309761ca27c020d57bcb7fbd9446cb8a#diff-9ffd5283b3cfbde20ef300716d226c60R162

**Comment by moldcraft** [comment]
@2Fwebd Please let us know if it fixes the slow page load problem

**Comment by 2Fwebd** [comment]
Hi there,

I just tried, it loads pretty fast on my side and the saving is working well. I'll release it to my customer and get back if that doesn't fix it but I think that'll :)

Cheers,

**Comment by danyj** [comment]
@moldcraft   is there an event that I can use once the tab content is rendered. you killed all 

    $('.elelement').find.....   

with this feature,  so now half of the scripts must be reworked , 


some I can change 

    from 
    
    $('.element').on('somevent', function(e) {

    //to

    $(document).on('somevent', '.element', function (){

but ones that were used as collectors like 


            var allcolors = $('[data-tmcontainer="tm_colors_container"]').find('[data-tminputid]');

            $(allcolors).each(function(index, element) {.....


I cant find anymore

**Comment by moldcraft** [comment]
Add [here](https://github.com/ThemeFuse/Unyson/blob/2.5.0/framework/static/js/backend-options.js#L66)

```js
fwEvents.trigger('fw:options:container-type:tab:lazy-init', {$tab: $tab});
```

If that is what you are looking for, I will commit.

**Comment by danyj** [comment]
let me test

**Comment by danyj** [comment]
explain it to me ,  is the render done for the tab by tab including sub tabs , or only main tabs ? 
http://prntscr.com/9qt931

**Comment by danyj** [comment]
is by tab, darn. have no idea how to do this, the trigger wont help

**Comment by danyj** [comment]
@moldcraft  , the new event It does help , but another question , 

is there a way to activate all sub tabs once I click on main Top menu tab ? 
You see now I am runing my plugin on that event 

		fwEvents.on('fw:options:container-type:tab:lazy-init', function (){
					self.start();
		 });


and each time user click on one of the sub tabs it runs  again , 
I need to render all topmenu subtabs once the user clicks on the main tab

**Comment by moldcraft** [comment]
I will take a look on Monday.

**Comment by danyj** [comment]
ok

**Comment by danyj** [comment]
@moldcraft   reminder for Monday, 
if possible please create an outside trigger for this 
https://github.com/ThemeFuse/Unyson/commit/a621d731a004bd25dac2ef8ffaf4e4e3aeb23cdf


without a submit , 

I need a trigger to activate all available tabs before creating theme template. 
I am not talking about form submit save , I am generating and saving theme templates by collecting all options, and need something like 

    fwEvents('initTabs');

to run before I save the template. This save process has nothing to do with options save and it is not connected to form submit or DB.

it is just a button that on click collects all form data and sends them to a file. 


that is my biggest issue so far. 

In meantime I managed to do scripts change  and use

    $(document).on..... 

for most of the scripts, but this template saving is huge issue and show stopper fro lazy load.

**Comment by moldcraft** [comment]
Sorry, I am busy with a complicated function and haven't finished it yet. I will answer your question later.

**Comment by danyj** [comment]
take your time

**Comment by moldcraft** [comment]
Ops, the merge closed the issue.

All commits containing `fixed #XX` had no effect while being on the `2.5.0` and after merge were applied all at once.

If you will find similar issue, which was closed from a commit but it's not fixed/finished, please reopen it or  comment and I will reopen it.

**Comment by moldcraft** [comment]
TOOD: Bug: Shortcode options not in first tab are not saved. Need to render all tabs on popup Save

**Comment by danyj** [comment]
> Shortcode options

you mean theme options right?

**Comment by moldcraft** [comment]
No, PageBuilder shortcode popup options.

**Comment by moldcraft** [comment]
No, PageBuilder shortcode popup options which contain tabs (when lazy tabs are enabled).

**Comment by danyj** [comment]
ok , got it , than pleas consider this in both cases 
https://github.com/ThemeFuse/Unyson/issues/1174#issuecomment-172244653
let us have an outside trigger to render tabs on the fly , not connected to save or popup save

**Comment by moldcraft** [comment]
Working on it right now.

**Comment by moldcraft** [comment]
```js
fwEvents.trigger('fw:options:init:tabs', {
    $elements: jQuery('.fw-settings-form')
});
```

**Comment by danyj** [comment]
sorry for bringing this back up ,  can we have a callback after the tabs are loaded so that I can do this 


	fwEvents.trigger('fw:options:init:tabs', {
		$elements: jQuery('.fw-settings-form')
	},function(){
		self.saveTemplate();
	});


and this one is for theme settings only right  `jQuery('.fw-settings-form')`   ?
what do we use for tabs inside popups ?

**Comment by danyj** [comment]
Basically I need to trigger the tabs init  no matter if theme settings or popup, 

so shold I use this instead ?

      $elements:  jQuery('.fw-settings-form, .media-frame-content form')

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1174#issuecomment-196820134

https://github.com/ThemeFuse/Unyson/blob/61725ae8c2de0589379e76625003fdd202a620b8/framework/static/js/backend-options.js#L66-L86

> this one is for theme settings only right jQuery('.fw-settings-form')

Yes, `.fw-settings-form` is for Theme Settings only

**Comment by danyj** [comment]
@moldcraft , and one more sorry ,  is there way to add a hook that will not continue to trigger the init if they are already initiated. Add a class to form maybe `fw-tabs-initiated`

**Comment by moldcraft** [comment]
Sure, nothing is initialized twice, options and containers always add an "initialized" class. https://github.com/ThemeFuse/Unyson/blob/61725ae8c2de0589379e76625003fdd202a620b8/framework/static/js/backend-options.js#L136

**Comment by moldcraft** [comment]
Also to check if lazy tab was initialized or not, check if it has `data-fw-tab-html` attribute.

**Comment by danyj** [comment]
@moldcraft   what I mean is this , when you click on  a button I need all tabs to be initiated before render


            $(self.loadtrigger).on('click', function(e) {
                e.preventDefault();
				fwEvents.trigger('fw:options:init:tabs', {
					$elements: jQuery('.fw-settings-form,.media-frame-content form')
				});
                var templatename = $(this).attr('data-templatename');


                self.renderTemplate(templatename);

            });

now that is triggering every time and I see a lag , like it is initiating tabs every time I click on the button

**Comment by moldcraft** [comment]
>  every time and I see a lag

Maybe because the selector is slow (it't not by id or by class, it needs to check every element atts) https://github.com/ThemeFuse/Unyson/blob/61725ae8c2de0589379e76625003fdd202a620b8/framework/static/js/backend-options.js#L91

Please add [here](https://github.com/ThemeFuse/Unyson/blob/61725ae8c2de0589379e76625003fdd202a620b8/framework/static/js/backend-options.js#L94) `console.log($tabs.length);` to see how many elements are selected on button click

**Comment by danyj** [comment]
OK , this works and it eliminates additional lags, only first one lags a bit , 

				if(!$('.fw-settings-form,.media-frame-content form').hasClass('thz-tabs-init')){
					fwEvents.trigger('fw:options:init:tabs', {
						$elements: jQuery('.fw-settings-form,.media-frame-content form')
					});
					$('.fw-settings-form,.media-frame-content form').addClass('thz-tabs-init')
				}


testing your suggestion

**Comment by danyj** [comment]
returns 4 , but without my check it returns it on every click , that is why I meant to add something to form or to tabs itself for check if they are already initiated

**Comment by moldcraft** [comment]
I can't reproduce this in my side

![](http://static.md/d87ed5376cca69e0e609d3069120874d.png)

**Comment by danyj** [comment]
@moldcraft  you made a button that triggers this 

                fwEvents.trigger('fw:options:init:tabs', {
                    $elements: jQuery('.fw-settings-form,.media-frame-content form')
                });

?

**Comment by moldcraft** [comment]
I execute the code Console

![](http://static.md/d59d42c7be68f97ff8a652ebc78a9f15.png)

**Comment by danyj** [comment]
ok , must be my template render since it is reloading options just like reset theme options does , so tabs are not initiated on reload. This is why a form container class hook works , I am reloading what is inside of the form.

**Comment by danyj** [comment]
either way , is MUCHHHH faster  with lazy_tabs , thnx for the improvement .

**Comment by danyj** [comment]
@moldcraft , exactly like I said , http://prntscr.com/afxrmc   that is after template reload ( the button click )  so re-initiation is a must on next click. No problem , it works either way.
