### ISSUE TITLE
Cannot edit my pages, visual editor has gone

### ISSUE THREAD

**Issue by jchu93** [ThemeFuse/Unyson#1175]
Hello,

Okay this has happened twice to me whilst creating this website, I purchased the theme and now having this issue.

It's whenever I get so far with creating my page it always errors...

All I have done is create a few sections and moved them about, and now I cannot do nothing and everything on the site now looks boxed.

The issue:

https://gyazo.com/c69fcb4f33a21a6c1f849bf21ed7a733

How do I resolve this issue? As I don't want to be creating my page from scratch again....

Regards

EDIT: 

After using the inspection tool on Google, I have come across this issue. I don't understand it could someone help me please?

https://gyazo.com/aaa46f0e17d7657069ea018aa0ede944

Thanks in advance

**Comment by moldcraft** [comment]
Hello,

Please check apache error.log to find useful/informative error messages

**Comment by moldcraft** [comment]
Also try to disable post revisions (there are plugins for that)
