### ISSUE TITLE
Buttons shortcode

### ISSUE THREAD

**Issue by maryslen** [ThemeFuse/Unyson#1177]
Hi,

There is basic shortcode for inserting buttons. But how i noticed, there is only possibility to insert the button as a separate object. Can i insert the button inside the text? For example at the end of the sentence?

Thank you

**Comment by danyj** [comment]
we have been waiting for this for very long time  #756 , and  I think it should be looked at

**Comment by moldcraft** [comment]
At the moment you can only generate the `[shortcode ...]` manually using [this method](https://github.com/ThemeFuse/Unyson/issues/1071#issuecomment-161586475) then make sure that your test is sent to `do_shortcode($text);` before output, so the shortcode will be parsed and transformed to html.
