### ISSUE TITLE
Switch options type renders twice since last update

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1178]
Since latest update switch option type renders twice , 

I used this 

https://github.com/ThemeFuse/Unyson/blob/71736db9dbee049e58743c1a8b2b9deeac2ef6ee/framework/core/components/backend.php#L1141-L1202

to create template option type that saves and reloads theme settings , up until latest update ( Unyson 2.4.15)  the ajax render worked fine , now when I click to change template the switch option type loads twice 

before I change template 

![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/12090051/7080bf7e-b2eb-11e5-98eb-1391b26a30c8.jpg)

after I change template 

![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/12090064/934156ae-b2eb-11e5-8eee-0fbb71c2fa13.jpg)

**Comment by moldcraft** [comment]
Please test with latest dev version

**Comment by danyj** [comment]
fixed thnx!
