### ISSUE TITLE
PHP 5.2 compatibility?

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1179]
Hello!

Is Unyson now not compatible with PHP 5.2? After upgrading, I noticed "Fatal error:  Call to undefined function  json_last_error() in /plugins/unyson/framework/includes/option-types/switch/class-fw-option-type-switch.php on line 117

this can be a problem for many users i believe

**Comment by moldcraft** [comment]
Thank you for reporting, it will be fixed in the next version.
