### ISSUE TITLE
[Question] Add custom font to google font list

### ISSUE THREAD

**Issue by giathinh910** [ThemeFuse/Unyson#1181]
I just want to ask that whether the hook 'fw_google_fonts' works anymore. I tried to add my custom font family using this hook but not working.

Thank you very much.

**Comment by giathinh910** [comment]
**Here is the snippet:**
```php
function mauris_filter_theme_add_hind_google_font($fonts) {
	$fonts['HelveticaNeue']  = array(
			'family'    => 'Helvetica Neue',
			'variants'  => array( 400, 700 ),
	);
	ksort($fonts);
	return $fonts;
}
add_filter('fw_google_fonts', 'mauris_filter_theme_add_hind_google_font');
```

**Comment by llemurya** [comment]
@giathinh910 `fw_google_fonts` works only for `typography` not for `typography-v2`

**Comment by giathinh910** [comment]
So, is there any way to add my custom font to typography-v2?

**Comment by llemurya** [comment]
@giathinh910 please take a look at this [issue](https://github.com/ThemeFuse/Unyson/issues/1079). If it helps, please close the issue.

**Comment by giathinh910** [comment]
Thank you so much.

**Comment by Alex-Ascet** [comment]
Hi,
I added my custom font in parent-theme/theme-includes/option-types/tf-typography/class-fw-option-type-tf-typography.php and it is working but when I duplicate class-fw-option-type-tf-typography.php in my child theme child-theme/theme-includes/option-types/tf-typography/class-fw-option-type-tf-typography.php
It does not work... Any idea or advice? Thank you in advance.

**Comment by Alex-Ascet** [comment]
Please, any support on this?

**Comment by stevebeyatte** [comment]
For the Haven theme, I just solved this by adding this to functions.php of my child theme:

```function add_example_font($fonts)
{
    array_push($fonts, 'Some Font Name');
    return $fonts;
}
add_filter('fw_option_type_tf_typography_standard_fonts', 'add_example_font');
```

And then just adding the @font-face files to my child theme directory and adding the proper CSS to my child theme style.css.

Hopefully this helps someone else battling with this nightmare :-)

**Comment by maymeric78** [comment]
Hello everyone.

I have the same problem as a lot of people. I want to add a font in the list of "google-fonts" that Unyson offers in the management of the theme.
I looked at the problem suggested by the link from @llemurya but I don't know what to understand (no description).
I have read the source code for this page. I have the same in _... / option-types / typography-V2 / class-fw-option-type-typography-v2.php_.

@giathinh910 (or someone else)
Can you describe your additions/codes integrated in which file? and at what location? PLEASE ^^ (example: family-font "Marianne" regular, bold ...)
(If possible, give the solution for the theme-child?)

Thanks a lot.
It's hell for a lot of people, a lot of the same problem solved without really the solution ... a precise answer here would become the benchmark - finally a deliverance answer.
Thanks in advance. I hope your answer ...
Aymeric.




------
French
------

Bonjour à tous.

J'ai le même problème que beaucoup de personnes. Je souhaite ajouter une police dans la liste des "google-fonts" que Unyson propose dans la gestion du thème.
J'ai regardé le problème suggéré par le lien de @llemurya mais je ne sais pas ce que je dois comprendre (sans description).
J'ai lu le code source de cette page. J'ai le même dans _.../option-types/typography-V2/class-fw-option-type-typography-v2.php_.

@giathinh910 (ou quelqu'un d'autre)
Peux-tu décrire tes rajouts/codes intégrés dans quel fichier? et à quel emplacement? PLEASE ^^ (exemple : family-font "Marianne" regular, bold...)
(Si possible, donner la solution pour le theme-child?)

Merci beaucoup.
C'est l'enfer pour beaucoup de personnes, beaucoup de même problème résolu sans vraiment la solution...une réponse précise ici deviendrait la référence - une réponse enfin de délivrance.
Merci par avance. J'espère votre réponse...
Aymeric.
