### ISSUE TITLE
How to make box visible by default?

### ISSUE THREAD

**Issue by Priler** [ThemeFuse/Unyson#1182]
Hi!

If i make few boxes in one tab, only first is visible.
Didn't found solution in documentation.

How can i make all boxes visible by default?

**Comment by moldcraft** [comment]
Hello,

This is [the code that closes non-first boxes](https://github.com/ThemeFuse/Unyson/blob/v2.4.15/framework/static/js/backend-options.js#L105). You can set for each box

```php
'attr' => array(
    'class' => 'prevent-auto-close',
),
```
