### ISSUE TITLE
Theme Settings save button loads the Home Page, troubleshoot ? 

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#1183]
Hi there, 

We have a customer with this issue : "When i try to save option in theme settings, site go out and return on home page."

Do you have any idea how we can fix that or at least troubleshoot the issue ? First time I see this...

Thanks.

**Comment by danyj** [comment]
check the ajax ,  
in chrome hit f12 , click on Network tab , than click on Preserve log
http://prntscr.com/9mejpe

now hit save , 
once done 
click on admin-ajax.php  and check response http://prntscr.com/9mejzx
and check headers status http://prntscr.com/9mek9d
those can get you started

**Comment by danyj** [comment]
could be that headers comes back as 303 ,300 or 404 , either one of those will not allow  you to save  
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
and might kick you out . Check your customers options entries also. Some bad js can mess things up.

**Comment by 2Fwebd** [comment]
Thanks for the fast reaction, I'll do more digging... 

Doesn't seems to be ajax related for now. 

![intranet_ _welt_intranet](https://cloud.githubusercontent.com/assets/5446124/12120301/95e159aa-b3d0-11e5-8424-470fd8d16fff.jpg)

I'll keep you updated

**Comment by danyj** [comment]
must be since it is not there ,  your console has 20 errors , snap those

**Comment by danyj** [comment]
once you hit save ajax must run , otherwise it wont save

**Comment by 2Fwebd** [comment]
It's a server side issue : POST http://.../wp-admin/admin-ajax.php 500 (Internal Server Error)

Thanks anyway, can be closed.

**Comment by danyj** [comment]
there u go , blocked, good luck!

**Comment by 2Fwebd** [comment]
Okay, this is the issue : 

```
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/emmelab/public_html/welt/wp-config.php:1) in /home/emmelab/public_html/welt/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13

Warning: Cannot modify header information - headers already sent by (output started at /home/emmelab/public_html/welt/wp-config.php:1) in /home/emmelab/public_html/welt/wp-includes/pluggable.php on line 1228
```

Any idea ?

**Comment by moldcraft** [comment]
[`wp-includes/pluggable.php line 1228`](https://github.com/WordPress/WordPress/blob/07e9d2296892eb779e8cfcbcab4349ffa2cd6961/wp-includes/pluggable.php#L1228) this does redirect (header) but output is not started (there is no `echo`), weird.

1. I think some script does `wp_redirect();` but doesn't do `exit();` right after that (it should) and the script continues to execute
2. Can you add `debug_print_backtrace()` after `pluggable.php line 1228`, then reproduce the warning and check the trace to find where `wp_redirect()` is called?
