### ISSUE TITLE
I'm having trouble with the Pagebuilder -- Can't seem to have picture, text, and sidebar widget working

### ISSUE THREAD

**Issue by larryshinagawa** [ThemeFuse/Unyson#1185]
Hi,

I have a picture (1/4), text (1/2), and sidebar widget (1/4) on my biography page.  What happens is that it looks fine but if I have it like this:

picture (1/4) text (1/2) sidebar widget (1/4)
picture (1/4) text (1/2)

it looks awful.  where the sidebar contents end is where the next iteration of picture (1/4) text (1/2) begins again.  I don't want that.  I want it to start immediately after the first picture (1/4) text (1/2).  What do I do to make it work?  I appreciate any suggestions!

**Comment by moldcraft** [comment]
Hello,

Please make a video/screencast, it will help us a lot to understand the problem
