### ISSUE TITLE
Can't save anything in and therefore can't use the page builder anymore after recent update

### ISSUE THREAD

**Issue by keysquare1** [ThemeFuse/Unyson#1187]
Hi there,

I just updated to the latest Unyson version and now I can't save anything in the page builder on my site anymore. Worked fine up until that point. Whenever I try to save, I get the following error message:

parsererror: JSON.parse: unexpected character at line 1 column 1 of the JSON data

I'll happily provide more necessary information if needed. Any help is greatly appreciated!

**Comment by moldcraft** [comment]
Hello, try this solution https://github.com/ThemeFuse/Unyson/issues/1184#issuecomment-169108254

**Comment by keysquare1** [comment]
Thank you very much!
