### ISSUE TITLE
Overriding Section Shortcode

### ISSUE THREAD

**Issue by ariona** [ThemeFuse/Unyson#1188]
I have successfully overrided the section shortcode options, I need to group some option so i put them in the tab container, So the option become like this:

```
$options = array(
	'section_options' => array(
		'type' => 'tab',
		'options' => array(
			'is_fullwidth' => array(
				'label'        => __('Full Width', 'fw'),
				'type'         => 'switch',
			),
		),
		'title' => __('Section Options', 'fw'),
	),
	'section_design' => array(
		'type' => 'tab',
		'options' => array(
			'background_color' => array(
				'label' => __('Background Color', 'fw'),
				'desc'  => __('Please select the background color', 'fw'),
				'type'  => 'color-picker',
			),
			'background_image' => array(
				'label'   => __('Background Image', 'fw'),
				'desc'    => __('Please select the background image', 'fw'),
				'type'    => 'background-image',
				'choices' => array(//	in future may will set predefined images
				)
			),
			'video' => array(
				'label' => __('Background Video', 'fw'),
				'desc'  => __('Insert Video URL to embed this video', 'fw'),
				'type'  => 'text',
			)
		),
		'title' => __('Design Options', 'fw'),
	),
);
```

So basically the old options is still there, I just wrap them in a container. But the shortcode is not working as expected. The options is saved, but the view now is not working. Should i update the view.php too to match the new options structure? and how to do that?

Thanks

**Comment by moldcraft** [comment]
Hello

> the view now is not working

Can you give more details, screenshot?

I tried the above options and I have no issues.

> Should i update the view.php too to match the new options structure

No.

**Comment by ariona** [comment]
Oh my god, I forgot to clear the floating on the row since i override the column classes. but here it come another question:
1. How to update the `fw-row` & `fw-container` class? is there a filter of it?
2. If I add new options, and want to make a change in the view, how to call it? do I just directly use $atts['option_name']` ?

**Comment by moldcraft** [comment]
1. You need to overwrite all views that are using/outputing it
2. > **change** in the view

    You **overwrite** it (like `options.php`) and use `$atts['option_name']`

**Comment by Taimurian** [comment]
Sorry if this is not the right place to ask. I want to know if there's a unique ID for each generated section. I want to add it automatically to the id field. the $atts array has no unique identifier.
Thanks

**Comment by moldcraft** [comment]
Nothing has an unique id, you can achieve that with [this solution](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head)
