### ISSUE TITLE
recent posts shortcode

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#1189]
Does anybody have develop a custom shortcode for the Visual Page Builder that shows the recent posts (or custom post types)?

**Comment by moldcraft** [comment]
I think it's very simple, it's just a wp query

**Comment by mbtocalli** [comment]
Could you share the code?

**Comment by moldcraft** [comment]
* http://manual.unyson.io/en/latest/extension/shortcodes/index.html#creating-a-new-shortcode
* https://codex.wordpress.org/Function_Reference/wp_get_recent_posts
