### ISSUE TITLE
How do you display a map option type?

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#1190]
I'm not referring to using a map shortcode, but when I setup a map as an option for a post type or theme setting.

How do I use that data to actually display a map on the front end?

Thanks!

**Comment by zohaib87** [comment]
If I am not wrong I think you are asking about PHP helpers.
check this: http://manual.unyson.io/en/latest/helpers/php.html

**Comment by moldcraft** [comment]
Hello,

In frontend you get the map coordinates via [one of these functions](http://manual.unyson.io/en/latest/helpers/php.html#database) as array, then you display the map yourself using google maps api.
