### ISSUE TITLE
Typography v2 - How can I remove the "Weight" and "Style" dropdowns?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1191]
Is there an option to remove the **Weight** and **Style** dropdowns?

I see that `'family' => true`  disables them but it also remove the **Family** dropdown.

**Comment by pe6o** [comment]
I suppose there is CSS way with custom classes to the field?

**Comment by warudin** [comment]
It's still not possible to disable weight with Typography v2, right?

**Comment by moldcraft** [comment]
[Nope](https://github.com/ThemeFuse/Unyson/blob/v2.5.9/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php#L171)
