### ISSUE TITLE
Editor wont make it possible to edit a inserted image, icon not showing

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#1194]
Hi,

Editor wont make it possible to edit a inserted image, icon not showing

![schermafbeelding 2016-01-10 om 16 26 08](https://cloud.githubusercontent.com/assets/5340923/12222244/f4c833b4-b7b6-11e5-97b4-9150951de468.png)

**Comment by moldcraft** [comment]
![](https://static.md/47c87c71416ecff08c35bba019571ddb.png)
