### ISSUE TITLE
Portfolio / How to authorize author and contributor to create portfolio page ?

### ISSUE THREAD

**Issue by AndyMinnie** [ThemeFuse/Unyson#1195]
Hi there!

I would like to know how can I authorize my users with author and contributor role to create portfolio page.
For instance, only the administrator and Editor are allowed to do so.

Thanks in advance!

**Comment by moldcraft** [comment]
Hello,

You need to play with capabilities https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/v1.0.4/class-fw-extension-portfolio.php#L158-L171
