### ISSUE TITLE
Error when activate Unyson plugin 

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1196]
My client get that error when install and acitvate Unyson latest verion( 2.4.16).
http://prntscr.com/9oo6iw
What could be conflict here?

**Comment by moldcraft** [comment]
Enable a default WP theme then enable Unyson (to check if the problem is in theme)

**Comment by duongancol** [comment]
Yes, The problem from my theme, I'll find it. Thanks!
