### ISSUE TITLE
Color Palette Option Type

### ISSUE THREAD

**Issue by Taimurian** [ThemeFuse/Unyson#1204]
ThemeFuse introduced a color-palette option type in their latest theme 'The Core' which is very cool feature. Is this going to be included in the next Unyson releases ?

![untitled-1](https://cloud.githubusercontent.com/assets/1550077/12399723/6bfed884-be24-11e5-92ae-5c5d70e7cd06.png)

**Comment by duongancol** [comment]
:+1:

**Comment by Ataurr** [comment]
+1

**Comment by onebelarusianguy** [comment]
:+1:

**Comment by DimiBaitanciuc** [comment]
Hi guys, unfortunately, this feature is not gonna be included. The Core guys decided that they wanna keep this option for them self. Sorry.

**Comment by xperter** [comment]
If possible share this options-type with us :)
