### ISSUE TITLE
Styling, css

### ISSUE THREAD

**Issue by Tierislund** [ThemeFuse/Unyson#1205]
Hi.

Love your stuff!
I have no styling menu nor do i have any option for setting margin + more features i have seen in your videos. What have i done wrong? Do i need a paid version? Regards

**Comment by danyj** [comment]
what theme are you talking about? this is framework git.

**Comment by moldcraft** [comment]
Hello,

The Styling extension was removed from the docs and from the extensions list https://github.com/ThemeFuse/Unyson/issues/874

The docs are still available [here](https://github.com/ThemeFuse/Unyson-Documentation/blob/72ab67be20118a50c06a97db0722c672fbb11075/extension/styling/index.rst) in git history
