### ISSUE TITLE
Warning: session_start(): The session id is too long or contains illegal characters

### ISSUE THREAD

**Issue by dirklach** [ThemeFuse/Unyson#1207]
Hello everyone!

Suddenly my website is showing me some error-messages and I have absolutely no idea why. I didn't changed anything for weeks.

----------------------------------------

At the top of the wordpress-backend I got this messages:

he session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /www/htdocs/w0130f83/wp/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php on line 214
Warning: session_start(): Cannot start session with empty session ID in /www/htdocs/w0130f83/wp/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13

Warning: session_start(): Cannot start session with empty session ID in /www/htdocs/w0130f83/wp/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13

Warning: session_start(): Cannot start session with empty session ID in /www/htdocs/w0130f83/wp/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13

![image](https://cloud.githubusercontent.com/assets/2110545/12415396/cd5a7a44-be9b-11e5-9a65-1c36e95d4405.png)

----------------------------------------

On my website i got this messages:

At the top:

Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /www/htdocs/w0130f83/wp/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php on line 241

At the bottom:

Warning: session_start(): Cannot start session with empty session ID in /www/htdocs/w0130f83/wp/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13

Warning: session_start(): Cannot start session with empty session ID in /www/htdocs/w0130f83/wp/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13

Warning: session_start(): Cannot start session with empty session ID in /www/htdocs/w0130f83/wp/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13

Warning: Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0

----------------------------------------

Can anyone help me? :) 
Do you need more information?

Thanks!

**Comment by llemurya** [comment]
@dirklach  please read this [answer](http://stackoverflow.com/a/16318456).
