### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by yanickvanbarneveld** [ThemeFuse/Unyson#1208]
Hi guys,

I have downloaded a PO translation file for Unyson. Now I converted this PO file to a MO file so I can use it in your framework.

I load/include the framework manually so not by plugin but how can I load the localization file now? I tryed to do after the `require dirname(__FILE__) .'/framework/bootstrap.php';` to do a `load_textdomain('fw', get_template_directory_uri() . '/languages');` but it didn't work.

I named my files nl_NL, I hope you guys can help me.

Kinds regards,
Yanick

**Comment by llemurya** [comment]
can you see what value return `load_textdomain()` function.

**Comment by yanickvanbarneveld** [comment]
Hi Illemurya, it returns a bool(false). But when I echo the path it goes succesfully to the right directory. Maybe the name of the file is incorrect?

**Comment by llemurya** [comment]
@yanickvanbarneveld maybe you must use [`load_theme_textdomain()`](https://codex.wordpress.org/Function_Reference/load_theme_textdomain)

**Comment by yanickvanbarneveld** [comment]
Awesome, that worked! Thanks!
