### ISSUE TITLE
Creating a builder 

### ISSUE THREAD

**Issue by AceoK** [ThemeFuse/Unyson#1209]
I'm doing all like in documentation, but when add builder as option there are no items, just title and templates button

**Comment by moldcraft** [comment]
I did all the [instructions](http://manual.unyson.io/en/latest/extension/builder/index.html#creating-items) until **Registering items in javascript** and it works

![](https://static.md/60b3efc43742842388b891b6d272c5a3.png)

also I don't have Templates button, which is [correct](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/0eedf5181b7f84f711383f51f2c784dd25959fce/includes/option-types/builder/extends/class-fw-option-type-builder.php#L176)

**Comment by AceoK** [comment]
I trying to use it in shortcode options, maybe it is a problem?

**Comment by AceoK** [comment]
Maybe I include files wrong? I use fw_option_types_init action hook for class-fw-option-type-column-builder.php file. If I remove this string it becomes /* UNDEFINED OPTION TYPE */

**Comment by moldcraft** [comment]
> I trying to use it in shortcode options

You should note that when created the issue.

----

I reproduced the problem.

Added

```php
'lists-builder-box' => array(
	'type' => 'box',
	'title' => __('Lists Builder', 'fw'),
	'options' => array(
		'lists-builder' => array(
			'type' => 'lists-builder',

			// this will make it full width
			'label' => false,
		),
	),
),
```

in

```
framework-customizations/extensions/shortcodes/shortcodes/button/options.php
```

and it shows

![](https://static.md/95d7a07270baa5c9077490a12dedb1d4.png)

Inspecting...

**Comment by AceoK** [comment]
Builder is working for me now. Problem was in custom-builder.php file. It was not included in my functions.php, but only in  fw_option_types_init action hook.

So I think that isn't bug and ticket can be closed. Thanks for help.

**Comment by moldcraft** [comment]
In docs is specified to include the files on `fw_init`.

Ok, thank you for letting us know.

Good luck with your builder!

**Comment by AceoK** [comment]
Thank You
