### ISSUE TITLE
Download "auto-install" folder from my site instead of embed in theme

### ISSUE THREAD

**Issue by MoBadawy** [ThemeFuse/Unyson#121]
I have a big demo and I need to upload "auto-install" folder to my site to reduce the theme size and when user need to import demo it will download from my site.
Can I make it and how?

**Comment by sergiubagrin** [comment]
@MoBadawy 

I added in our To Do list this option: https://trello.com/c/6EAny3WJ/54-content-demo-install-remote-server

**Comment by MoBadawy** [comment]
good, thanks
