### ISSUE TITLE
Tabs broke when the Give plugin is active

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1210]
![](https://static.md/a893c55a52a7102f71b26dbde97a5704.png)

https://wordpress.org/plugins/give/

**Comment by danyj** [comment]
https://github.com/WordImpress/Give/search?utf8=%E2%9C%93&q=ui-state-default

**Comment by danyj** [comment]
https://github.com/WordImpress/Give/blob/3eafebbfc912cd861e4a0b6645a6039bfe4ef643/assets/css/jquery-ui-fresh.css#L68

**Comment by moldcraft** [comment]
https://github.com/WordImpress/Give/issues/466
