### ISSUE TITLE
Unyson deactivates on it's own

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#1212]
During last days, the plugin is deactivating on it's own on themes we have created.
Can you let us know what the problem is?

Thanks.

**Comment by moldcraft** [comment]
Please give as much details as you can.

**Comment by darwinteam** [comment]
Hi. What details exactly?

**Comment by moldcraft** [comment]
Just asking. Usually most users report issues very few details (for e.g. "It's not working!!!"), then we ask for more and they give screenshots and other details.

I have no idea why plugin deactivates. Plugin activation/deactivation is handled by WordPress, we do nothing related to that. Unyson controls only extensions activation/deactivation/install/uninstall.

**Comment by darwinteam** [comment]
We use BlueHost. The plugin deactivated 2 days ago, I reactivated. And yesterday it deactivated again, so I activated it one more time.

**Comment by moldcraft** [comment]
Please check error.log for informative error messages.

We released Unyson version 2 days ago https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/171

I think the problem may be in automatic plugin updates from WordPress. Maybe on plugin auto-update something happened and WordPress disabled it.

On your site, Unyson is latest version (the auto-update was successful or it failed) ?

**Comment by danyj** [comment]
if possible list all plugins that you have on your install

**Comment by moldcraft** [comment]
Try [this](https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-131184290) to reproduce the problem
