### ISSUE TITLE
Install Compatible Extensions Installing Error

### ISSUE THREAD

**Issue by bL00keRs** [ThemeFuse/Unyson#1213]
Hello, I try Install Compatible Extensions but Cannot download error.
![adsiz](https://cloud.githubusercontent.com/assets/16793461/12442485/04757b4c-bf59-11e5-8bdd-d6b68b3cdaac.jpg)

**Comment by moldcraft** [comment]
Hello,

It's an issue on server side. Please give the above screenshot to your hosting support, and ask why it happens.

**Comment by bL00keRs** [comment]
Can I Install Zip or CuteFTP this files?

**Comment by moldcraft** [comment]
Download [unyson-extensions-20.01.2016.zip](https://github.com/ThemeFuse/Unyson/files/97192/unyson-extensions-20.01.2016.zip) and extract in `wp-content/plugins/unyson/framework/extensions`
