### ISSUE TITLE
Margin and Padding Option Types ?

### ISSUE THREAD

**Issue by IronLady** [ThemeFuse/Unyson#1214]
I need 4 text field options for margin, padding, border-radius, etc... (Top-Right-Bottom-Left)
Is there a way to have this without creating custom option types or using wide text file?

Anyway, thanks for creating this plugin.

**Comment by moldcraft** [comment]
Hello,

Try option type [multi](http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi) or [popup](http://manual.unyson.io/en/latest/options/built-in-option-types.html#popup)
