### ISSUE TITLE
moving to another server / domain change

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#1215]
Moved project from local vvv to VPS. I exported db, replaced domain and imported in VPS. Problem is that all settings configured are now gone.

Why?

**Comment by moldcraft** [comment]
Try to migrate using our backup extension

1. Create Content Backup
2. Upload it in theme as Demo Install http://manual.unyson.io/en/latest/extension/backups/index.html#demos-bundled-in-theme
3. Install Unsyon and Backup extension on VPS and do Demo Content Install

**Comment by sandrodz** [comment]
What does unyson export by default? Does it export normal wp settings / pages / posts / thumbs?

**Comment by moldcraft** [comment]
It exports everything except `users` and `usermeta`

**Comment by sandrodz** [comment]
How does it handle multisite ?

**Comment by moldcraft** [comment]
You want to migrate a network (many sites at once) ?

**Comment by sandrodz** [comment]
yes I need to migrate whole network, as db structure and multisite settings, but I need content only for main site.

**Comment by moldcraft** [comment]
Our extension can export/import only the data for one site.

> Problem is that all settings configured are now gone.
>
> Why?

I don't know how you did the migration. I don't think it's related to Unyson.

Check more carefully why some `wp_options` with `fw...` are not imported

**Comment by sandrodz** [comment]
I found out the issue. I was doing dumb search and replace of domain url while moving. And unyson data is saved in a  serialised string. if serialised string contained any kind of url, replacing its domain was causing sX count at the beginning of the string to be incorrect, thus invalidating the data and unyson was overwriting it.
