### ISSUE TITLE
unyson page builder's text block tinyMCE link button

### ISSUE THREAD

**Issue by jeni1616** [ThemeFuse/Unyson#1218]
Hi There ,

Thanks for this great plugin .
 
i want to make link/unlink button available in text block of unyson page builder  (  http://take.ms/7fndZ ) . i tried editing wp-content/plugins/unyson/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php  file with no luck , i also tried to add filter for this like : 

function my_mce_buttons_2($buttons) {
        $buttons[] = 'link';
        $buttons[] = 'unlink';
        return $buttons;
}
add_filter('mce_buttons_2', 'my_mce_buttons_2');

in functions.php file but don't know why it's not accepting it , any help will be really appreciate :)

Thanks .

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/509#issuecomment-102322805

**Comment by jeni1616** [comment]
Thank you so much :)
