### ISSUE TITLE
possible to get all values from multisite?

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#1219]
Is it possible to get unyson settings for all multisites?

I've options set in each multisite, that needs to be accessible all together 1 php file.

**Comment by moldcraft** [comment]
Theme Settings are saved in a `wp_option` with [this name](https://github.com/ThemeFuse/Unyson/blob/v2.4.17/framework/helpers/database.php#L18). So you'll need too loop through each blog_id and query db for that option...

**Comment by sandrodz** [comment]
Solution came out quite ugly. 

```
	$mu_sites    = wp_get_sites();

	foreach ( $mu_sites as $mu_site ) {
		if ( $mu_site['public'] ) {

			switch_to_blog( $mu_site['blog_id'] );

			$mu_fw_settings   = get_option( 'fw_theme_settings_options:' . fw()->theme->manifest->get_id() );

			restore_current_blog();

		}
	}
```
