### ISSUE TITLE
Some option types needed

### ISSUE THREAD

**Issue by MoBadawy** [ThemeFuse/Unyson#122]
I think these option types needed :
1- "Add video from media" and "create/edit gallery from media" buttons like "add image" and "add multi images" buttons.
2- "Import for theme settings" and "export for theme settings " and "reset to defaults for theme settings" buttons.
3- "Choose sidebar or create" it maybe used in posts , pages and categories. 
It will be great if supported :)
Thank you

**Comment by rockalife** [comment]
Hi @MoBadawy,

Regarding the video and gallery options, I have replied on [this issues](https://github.com/ThemeFuse/Unyson/issues/129). There are some questions to you, please check it out.
