### ISSUE TITLE
Images Dissapear on Browser Resize

### ISSUE THREAD

**Issue by NwpDeveloper** [ThemeFuse/Unyson#1220]
When resizing the browser to test responsive features images will disappear and just show accessibility text. Need to clear the cache and refresh to resolve. 

This happens on Firefox 43.

**Comment by llemurya** [comment]
@NwpDeveloper can you be more specific , in what extension you have this problem? How we can reproduce that. Thanks. I am waiting for your response.

**Comment by NwpDeveloper** [comment]
This happens with the pagebuilder, when you put an image inside a column inside a section. I have admin open editing the page and another the site. When I resize the window sometimes the image will disappear and just leave the accessibility text. I'm on Firefox 43. 

I can't reproduce it consistently, but when I clear cache and refresh the image reappears. I'll update when I can be more specific on what's causing the issue.

**Comment by llemurya** [comment]
@NwpDeveloper please make an screencast for us, it will be very helpful.Thanks.

**Comment by llemurya** [comment]
@NwpDeveloper also I want to know that theme do you have on the front of the site.

**Comment by llemurya** [comment]
@NwpDeveloper please answer.

**Comment by NwpDeveloper** [comment]
This happened on 2015.

**Comment by llemurya** [comment]
now it works? If it work you can close the issue.
