### ISSUE TITLE
Multiple Options One Line

### ISSUE THREAD

**Issue by NwpDeveloper** [ThemeFuse/Unyson#1221]
Is there a way to combine 2 options inline? 
For example, If I have a text option, I'd like to have a popup (Edit) option next to it without a label. That way I can edit the text properties on the same line without a lot of clutter.

Text Label     Text Option -> Popup Option (edit button)

I assumed the multi option would allow this, but it just stacks 2 options in the same group above an hr. The label on the multi isn't aligned properly with the modal. It sits flush on the left with no padding or margin.

**Comment by moldcraft** [comment]
Hello,

We don't have such option type.

Ask @danyj https://github.com/ThemeFuse/Unyson/issues/1065 maybe he can share his option type with you.
