### ISSUE TITLE
Demo content Install issue: Can not remove directory:  / wp-content / uploads / fw backup / tmp

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1223]
Hi
I have just tried to install demo content in one server i am Getting this error.

<pre>Can not remove directory:  / wp-content / uploads / fw backup / tmp</pre>

I have set the file permission for both folder ( fw backup / tmp ) 755 still cant install

**Comment by moldcraft** [comment]
Hello,

Do you use WpEngine?

**Comment by Ataurr** [comment]
No 
This one https://www.strato.de/

**Comment by moldcraft** [comment]
Can you give me admin/ftp access to your site? If yes, send the details to `moldcraft[at]email.com`

**Comment by Ataurr** [comment]
I can give you the login details. but i have already manually installed with backup demo mysql.

**Comment by moldcraft** [comment]
I will press "Content Backup" to simulate the error and will try to figure out why it happens.

**Comment by Ataurr** [comment]
Sent  Please check

Thanks

**Comment by moldcraft** [comment]
Content Backup worked fast without any issue.
