### ISSUE TITLE
Any way to use qTranslateX with unyson ?

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#1224]
Hi
I have tried to use Unyson with qTranslateX but its not work with page builder. 
When i checked Themeforest.. saw your themes support qTranslate. Its will be great if you share how we can use our theme with qTrsnalete support. :)

**Comment by llemurya** [comment]
@xperter you can use `WPML` or 'Polylang' or our `Translation Extension` the `q-Translate` concept in my opinion is  wrong what is why we don't make the `Page Builder` compatible with this plugin.If we goes in this way we will have code smells for every new plugin that need some code to works properly and if the new version appears we will have a headache to fix the compatibility for these plugins.

**Comment by Ataurr** [comment]
I am really Interested to use your Translation plugin but i am stucked when i need to translate string. 
Your plugin not supported to translate string.  
Is there any possibility to add  String  translation system in your extension ? if your extension can do that we dont need any third party plugin for translate our theme :)

**Comment by llemurya** [comment]
@Ataurr I will make an mecanism to do this stuff.

**Comment by Ataurr** [comment]
Great :) are you working for this ?

Thanks very much

**Comment by xperter** [comment]
@llemurya when it will be ready ? are you working with string translation  ?

Thanks

**Comment by moldcraft** [comment]
Not soon. Sorry.

**Comment by xperter** [comment]
It will be great if something include like this https://wordpress.org/plugins/loco-translate/
