### ISSUE TITLE
Translation for Wordpress content

### ISSUE THREAD

**Issue by gpecherle** [ThemeFuse/Unyson#1225]
We have purchased a Wordpress theme, Car Rental WordPress Theme Landing Page (http://themeforest.net/item/car-rental-wordpress-theme-lnading-page/11454552) with Unyson included for writing content. We need to have this content multi-language and we have problems integrating translation plugins. We have tried with qTranslate and some other plugins.

What do you recommend? This is very important for us.

Thanks!

**Comment by llemurya** [comment]
Please take a look at this [issue](https://github.com/ThemeFuse/Unyson/issues/1224).
