### ISSUE TITLE
pass global var to shortcode view?

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#1229]
I need to use $mu_offices in my shortcode view, any ideas how this could be achieved?

```php
function act_get_office_locations() {

	global $mu_offices;

}
add_action( 'after_setup_theme', 'act_get_office_locations' );
```

**Comment by moldcraft** [comment]
If it's global you can access it everywhere, no need to pass it.

```php
// .../shortcode/view.php

global $mu_offices;
```

**Comment by sandrodz** [comment]
My mistake. I thought it was included with something like get_template_part() which makes it impossible to get variables inside included file.
