### ISSUE TITLE
page builder design

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#1230]
Is there a roadmap for improving the design of the page builder?
or allow customising it?

I've seen many page-builders and they do offer better looks.

**Comment by danyj** [comment]
do you mind showing what you think is better?

**Comment by sandrodz** [comment]
for example visual composers backend editor looks great.

**Comment by danyj** [comment]
OK , here they are , and to me Unyson is right on the money visually and ease of use , but sure it is preference thing. 


Visual Composer 

![vc](https://cloud.githubusercontent.com/assets/2340172/12549979/1ab48568-c361-11e5-8c95-5406198e70ab.jpg)

Fusion, Avada 

![fusion](https://cloud.githubusercontent.com/assets/2340172/12549968/0ebc766c-c361-11e5-9013-95e3fd5fa0cc.jpg)


Avia , Enfold
![avia](https://cloud.githubusercontent.com/assets/2340172/12549991/262186da-c361-11e5-9be7-e1862f21cc70.jpg)


Unyson
![unyson](https://cloud.githubusercontent.com/assets/2340172/12549995/30554ccc-c361-11e5-9ea5-c42062d91575.jpg)

**Comment by moldcraft** [comment]
Hello,

We don't have any plans to change page builder design.

You can customize it by enqeue your css
