### ISSUE TITLE
template hierarchy page builder

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#1231]
Is there a way to have page-builder.php file that will override page.php as per hierarchy rules in wp if page-builder is active?

If not, what is conditional to check if page-builder is active?

**Comment by moldcraft** [comment]
Maybe it's possible to overwrite `page.php` with `page-builder.php` by hooking in WordPress actions/filters, I don't know, we haven't done that. If you know how to do it, submit a pull request.

To check if a page is using page builder, use [this helper](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.4.5/helpers.php#L3-L9).

**Comment by sandrodz** [comment]
I went with declared template, so I set page-builder.php as custom template, and editor can select it in dropdown (page templates). This is not the automated solution I was hoping for, but works.
