### ISSUE TITLE
get list of shortcodes/options from within shortcode

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#1232]
Hi,

I've a peculiar situation. I've built around 10 custom shorcodes, 1 of these 10 shortcodes is a Menu.

I want this menu to generate a list of links with href #id_of_shortcode - to build this functionality, I need to know what shortcodes are used in the current page, is this possible?

**Comment by moldcraft** [comment]
Hello,

It's not possible.

How it works:

1. We register shortcodes with [`add_shortcode()`](https://codex.wordpress.org/Function_Reference/add_shortcode)
2. On page display, WordPress parses post content `[shortcode_name attr_name=...]...` and renders  the extracted shortcodes one by one. There is no global variable with all current post shortcodes, or a connection between shortcodes, they all are independent/separated.

**Comment by moldcraft** [comment]
You can use a trick:

1. Listen [this action](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/3c9641767d5511562fa293c69a23bc6e595c485b/class-fw-extension-shortcodes.php#L149) and collect in a variable all shortcodes that went through it.
2. On a later action (`enqueue_scripts` with higher priority) [`wp_localize_script`](https://codex.wordpress.org/Function_Reference/wp_localize_script) all the collected shortcodes data in a script for your menu shortcode.
3. From javascript build the menu with anchors from the collected data.
