### ISSUE TITLE
Can we unescape radio button value?

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#1234]
![screen shot 2016-01-26 at 3 39 11 pm](https://cloud.githubusercontent.com/assets/8479569/12579662/137ce848-c443-11e5-8777-25c7523679ab.png)

I'd like to display images instead of text for the radio button.

**Comment by danyj** [comment]
Use image picker , it does exactly what you need http://manual.unyson.io/en/latest/options/built-in-option-types.html#image-picker

**Comment by sandrodz** [comment]
that is great! any way to control sizes? I don't have thumbs, I have svgs

![screen shot 2016-01-26 at 4 02 20 pm](https://cloud.githubusercontent.com/assets/8479569/12580102/3d0185f4-c446-11e5-8ba4-78c1b0f99744.png)

**Comment by danyj** [comment]
yes

        'value-3' => array(
            // (required) url for thumbnail
            'small' => array(
                'src' => get_template_directory_uri() .'/images/thumbnail.png',
                'height' => 70
            ),
            // (optional) url for large image that will appear in tooltip
            'large' => array(
                'src' => get_template_directory_uri() .'/images/preview.png',
                'height' => 400
            ),
            // (optional) choice extra data for js, available in custom events
            'data' => array(...)
        ),

**Comment by sandrodz** [comment]
super!
