### ISSUE TITLE
Bootstrap code can lead to (others) after_setup_theme actions not being called

### ISSUE THREAD

**Issue by joostdekeijzer** [ThemeFuse/Unyson#1235]
In `framework/bootstrap.php`, when the framework is not loaded yet, an action is added to `after_setup_theme`.
When this action is run, the action is removed immediately with `remove_action`.

As can be seen in https://core.trac.wordpress.org/ticket/17817 and https://core.trac.wordpress.org/ticket/21169 , removing an action or filter during it's execution can lead to the **following** action not being executed.

Perhaps a better way to prevent `_action_init_framework()` being called multiple times is to test on `did_action('fw_init')`?

**Comment by moldcraft** [comment]
Thank you
