### ISSUE TITLE
Are there open/close/change events for popup option type?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1236]
@moldcraft  I have a popup option type with  options and I need to manipulate some views on open/close/change 

kinda like we did here https://github.com/ThemeFuse/Unyson/issues/1042  and here 
https://github.com/ThemeFuse/Unyson/issues/925

I can find this one https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/popup/static/js/popup.js#L45  

			fwEvents.on('fw:option-type:popup:change', function(data){
				console.log(data);
			});

but how do I do this for particular option type , for example this one 

	'item_style' => array(
		'type' => 'popup',
		'size' => 'large',
		'label' => __('Item style', 'fw'),
		'button' => __('Edit item style', 'fw'),
		'popup-title' => __('Item style settings', 'fw'),
		'popup-options' => array(
			fw()->theme->get_options( 'itemstyle' ),
		)
	),

and how to get the popup data on  open/close events? 

debug tells me that there is only 

    fw:options:init 

http://prntscr.com/9v7ewf

**Comment by danyj** [comment]
@moldcraft  thnx! ,  any way to nail particular modal  or we have to do event  check than option names from data ?

**Comment by danyj** [comment]
@moldcraft , I downloaded the changed file but no new events ,  still  fw:options:init   only ,

**Comment by moldcraft** [comment]
Note that I added jQuery DOM events (on `.fw-option-type-popup`), not fwEvents. Listen them on wrapper/parent element or exactly on option element.

**Comment by danyj** [comment]
ah , I see , thnx!!!!

**Comment by danyj** [comment]
sorry to bother , open fires to early and I have to time it with settimeout, now it might work on my end in 500ms , but on someone else server might be longer , can we have this 

https://github.com/ThemeFuse/Unyson/issues/1042#issuecomment-159311647

and than a trigger for rendered  here https://github.com/ThemeFuse/Unyson/blob/86cfb5d1168a19be074c4083b9356fad851c471a/framework/includes/option-types/popup/static/js/popup.js#L63

if possible
