### ISSUE TITLE
Add shortcode option and view filters

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#1237]
I would like to propose a couple new filters to add to the "extensions/shortcodes/includes/class-fw-shortcode.php" file.

On line #134:
`return apply_filters('fw_shortcode_get_options', $this->options, $this->tag);`

And on line #200:
`return apply_filters('fw_shortcode_render_view', fw_render_view($view_file, array(
	'atts'    => $atts,
	'content' => $content,
	'tag'     => $this->tag
)), $atts, $this->tag);`

This would allow access to add global options and modified views of all, or limited amount, of existing shortcodes.

I will attempt to submit a pull request, though I don't have much experience with using git.

Thanks!

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/pull/47
