### ISSUE TITLE
Cant Install extensions: Failed to access Github repository

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1239]
Yesterday night our two buyers facing this issue.  cant install extensions from Github. 

<pre>
Downloading the “Shortcodes” extension…
Failed to access Github repository “ThemeFuse/Unyson-Shortcodes-Extension” releases. (110: Connection timed out)
Downloading the “SEO” extension…
Failed to access Github repository “ThemeFuse/Unyson-SEO-Extension” releases. (110: Connection timed out)
Downloading the “Backup & Demo Content” extension…
Failed to access Github repository “ThemeFuse/Unyson-Backups-Extension” releases. (110: Connection timed out)
Downloading the “Forms” extension…
Failed to access Github repository “ThemeFuse/Unyson-Forms-Extension” releases. (110: Connection timed out)
Dowloading the “Mailer” extension…
Failed to access Github repository “ThemeFuse/Unyson-Mailer-Extension” releases. (110: Connection timed out)
Downloading the “Analytics” extension…
</pre>

<pre>
Downloading the “Shortcodes” extension…
Cannot download the “Shortcodes” extension zip. (Response code: 503)
Downloading the “SEO” extension…
Cannot dwnload the “SEO” extension zip. (Response code: 503)
Downloading the “Backup & Demo Content” extension…
Failed to access Github repository “ThemeFuse/Unyson-Backups-Extension” releases. (Response code: 503)
Downloading the “Forms” extension…
Cannot download the “Forms” extension zip. (Response code: 503)
Downloading the “Mailer” extension…
Cannot download the “Mailer” extension zip. (Response code: 503)
Downloading the “Analytics” extension…
Failed to access Github repository “ThemeFuse/Unyson-Analytics-Extension” releases. (Response code: 503)
Cannot download the “Shortcodes” extension zip. (Response code: 503)
Cannot download the “SEO” extension zip. (Response code: 503)
Failed to access Github repository “ThemeFuse/Unyson-Backups-Extension” releases. (Response code: 503)
Cannot download the “Forms” extension zip. (Response code: 503)
Cannot download the “Mailer” extension zip. (Response code: 503)
Failed to access Github repository “ThemeFuse/Unyson-Analytics-Extension” releases. (Response code: 503)
</pre>

Is there something wrong with Github connection ?

**Comment by moldcraft** [comment]
The site works fine http://github-api-cache.unyson.io/repos/themefuse/unyson/releases/latest

I think the problem is in server configuration. Add in `{theme}/functions.php`

```php
add_action('fw_init', function(){
    fw_print(wp_remote_get('http://github-api-cache.unyson.io/repos/themefuse/unyson/releases/latest'));
});
```

and show us the screenshot

**Comment by aswebdesign** [comment]
Hi.

I have the same problem.
I have added the code to my theme function and i recieved this message :

` array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary
    (
        [*:data] => array
        (
            [server] => 'nginx'
            [date] => 'Sat, 18 Feb 2017 09:56:56 GMT'
            [content-type] => 'text/html; charset=UTF-8'
            [content-length] => '530'
            [x-powered-by] => 'PHP/5.3.10-1ubuntu3.25'
            [cache-control] => 'private, must-revalidate'
            [pragma] => 'no-cache'
            [expires] => '-1'
            [vary] => 'Accept-Encoding'
            [content-encoding] => 'gzip'
        )
    )
    [body] => '{"url":"https://api.github.com/repos/ThemeFuse/Unyson/releases/5418893","assets_url":"https://api.github.com/repos/ThemeFuse/Unyson/releases/5418893/assets","upload_url":"https://uploads.github.com/repos/ThemeFuse/Unyson/releases/5418893/assets{?name,label}","html_url":"https://github.com/ThemeFuse/Unyson/releases/tag/v2.6.14","id":5418893,"tag_name":"v2.6.14","target_commitish":"master","name":"","draft":false,"author":{"login":"moldcraft","id":1475489,"avatar_url":"https://avatars.githubusercontent.com/u/1475489?v=3","gravatar_id":"","url":"https://api.github.com/users/moldcraft","html_url":"https://github.com/moldcraft","followers_url":"https://api.github.com/users/moldcraft/followers","following_url":"https://api.github.com/users/moldcraft/following{/other_user}","gists_url":"https://api.github.com/users/moldcraft/gists{/gist_id}","starred_url":"https://api.github.com/users/moldcraft/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/moldcraft/subscriptions","organizations_url":"https://api.github.com/users/moldcraft/orgs","repos_url":"https://api.github.com/users/moldcraft/repos","events_url":"https://api.github.com/users/moldcraft/events{/privacy}","received_events_url":"https://api.github.com/users/moldcraft/received_events","type":"User","site_admin":false},"prerelease":false,"created_at":"2017-02-08T15:16:52Z","published_at":"2017-02-10T10:52:00Z","assets":[],"tarball_url":"https://api.github.com/repos/ThemeFuse/Unyson/tarball/v2.6.14","zipball_url":"https://api.github.com/repos/ThemeFuse/Unyson/zipball/v2.6.14","body":"https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/337"}'
    [response] => array
    (
        [code] => 200
        [message] => 'OK'
    )
    [cookies] => array()
    [filename] => null
    [http_response] => WP_HTTP_Requests_Response
    (
        [*:response] => Requests_Response
        (
            [body] => '{"url":"https://api.github.com/repos/ThemeFuse/Unyson/releases/5418893","assets_url":"https://api.github.com/repos/ThemeFuse/Unyson/releases/5418893/assets","upload_url":"https://uploads.github.com/repos/ThemeFuse/Unyson/releases/5418893/assets{?name,label}","html_url":"https://github.com/ThemeFuse/Unyson/releases/tag/v2.6.14","id":5418893,"tag_name":"v2.6.14","target_commitish":"master","name":"","draft":false,"author":{"login":"moldcraft","id":1475489,"avatar_url":"https://avatars.githubusercontent.com/u/1475489?v=3","gravatar_id":"","url":"https://api.github.com/users/moldcraft","html_url":"https://github.com/moldcraft","followers_url":"https://api.github.com/users/moldcraft/followers","following_url":"https://api.github.com/users/moldcraft/following{/other_user}","gists_url":"https://api.github.com/users/moldcraft/gists{/gist_id}","starred_url":"https://api.github.com/users/moldcraft/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/moldcraft/subscriptions","organizations_url":"https://api.github.com/users/moldcraft/orgs","repos_url":"https://api.github.com/users/moldcraft/repos","events_url":"https://api.github.com/users/moldcraft/events{/privacy}","received_events_url":"https://api.github.com/users/moldcraft/received_events","type":"User","site_admin":false},"prerelease":false,"created_at":"2017-02-08T15:16:52Z","published_at":"2017-02-10T10:52:00Z","assets":[],"tarball_url":"https://api.github.com/repos/ThemeFuse/Unyson/tarball/v2.6.14","zipball_url":"https://api.github.com/repos/ThemeFuse/Unyson/zipball/v2.6.14","body":"https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/337"}'
            [raw] => 'HTTP/1.1 200 OK
Server: nginx
Date: Sat, 18 Feb 2017 09:56:56 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 530
Connection: close
X-Powered-By: PHP/5.3.10-1ubuntu3.25
Cache-Control: private, must-revalidate
pragma: no-cache
expires: -1
Vary: Accept-Encoding
Content-Encoding: gzip

{"url":"https://api.github.com/repos/ThemeFuse/Unyson/releases/5418893","assets_url":"https://api.github.com/repos/ThemeFuse/Unyson/releases/5418893/assets","upload_url":"https://uploads.github.com/repos/ThemeFuse/Unyson/releases/5418893/assets{?name,label}","html_url":"https://github.com/ThemeFuse/Unyson/releases/tag/v2.6.14","id":5418893,"tag_name":"v2.6.14","target_commitish":"master","name":"","draft":false,"author":{"login":"moldcraft","id":1475489,"avatar_url":"https://avatars.githubusercontent.com/u/1475489?v=3","gravatar_id":"","url":"https://api.github.com/users/moldcraft","html_url":"https://github.com/moldcraft","followers_url":"https://api.github.com/users/moldcraft/followers","following_url":"https://api.github.com/users/moldcraft/following{/other_user}","gists_url":"https://api.github.com/users/moldcraft/gists{/gist_id}","starred_url":"https://api.github.com/users/moldcraft/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/moldcraft/subscriptions","organizations_url":"https://api.github.com/users/moldcraft/orgs","repos_url":"https://api.github.com/users/moldcraft/repos","events_url":"https://api.github.com/users/moldcraft/events{/privacy}","received_events_url":"https://api.github.com/users/moldcraft/received_events","type":"User","site_admin":false},"prerelease":false,"created_at":"2017-02-08T15:16:52Z","published_at":"2017-02-10T10:52:00Z","assets":[],"tarball_url":"https://api.github.com/repos/ThemeFuse/Unyson/tarball/v2.6.14","zipball_url":"https://api.github.com/repos/ThemeFuse/Unyson/zipball/v2.6.14","body":"https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/337"}'
            [headers] => Requests_Response_Headers
            (
                [*:data] => array
                (
                    [server] => array
                    (
                        [0] => 'nginx'
                    )
                    [date] => array
                    (
                        [0] => 'Sat, 18 Feb 2017 09:56:56 GMT'
                    )
                    [content-type] => array
                    (
                        [0] => 'text/html; charset=UTF-8'
                    )
                    [content-length] => array
                    (
                        [0] => '530'
                    )
                    [x-powered-by] => array
                    (
                        [0] => 'PHP/5.3.10-1ubuntu3.25'
                    )
                    [cache-control] => array
                    (
                        [0] => 'private, must-revalidate'
                    )
                    [pragma] => array
                    (
                        [0] => 'no-cache'
                    )
                    [expires] => array
                    (
                        [0] => '-1'
                    )
                    [vary] => array
                    (
                        [0] => 'Accept-Encoding'
                    )
                    [content-encoding] => array
                    (
                        [0] => 'gzip'
                    )
                )
            )
            [status_code] => 200
            [protocol_version] => 1.1
            [success] => true
            [redirects] => 0
            [url] => Requests_IRI
            (
                [*:scheme] => 'http'
                [*:iuserinfo] => null
                [*:ihost] => 'github-api-cache.unyson.io'
                [*:port] => null
                [*:ipath] => '/repos/themefuse/unyson/releases/latest'
                [*:iquery] => null
                [*:ifragment] => null
                [*:normalization] => array
                (
                    [acap] => array
                    (
                        [port] => 674
                    )
                    [dict] => array
                    (
                        [port] => 2628
                    )
                    [file] => array
                    (
                        [ihost] => 'localhost'
                    )
                    [http] => array
                    (
                        [port] => 80
                    )
                    [https] => array
                    (
                        [port] => 443
                    )
                )
            )
            [history] => array()
            [cookies] => Requests_Cookie_Jar
            (
                [*:cookies] => array()
            )
        )
        [*:filename] => null
        [data] => null
        [headers] => null
        [status] => null
    )
)`

**Comment by moldcraft** [comment]
@aswebdesign In you case the server response is ok.
What is your error message?
It is the same `Failed to access Github repository ...` ?

**Comment by celestegt** [comment]
Hello, would you please help me?
I am installing Compatible Extensions Unyson but I got the following messages:

Downloading the "Sidebars" extension...

Failed to access Github repository "ThemeFuse/Unyson-Sidebars-Extension" releases. (cURL error 7: )

Downloading the "Shortcodes" extension...

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (cURL error 7: )

Downloading the "Backup & Demo Content" extension...

Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 7: )

Downloading the "Media" extension...

Failed to access Github repository "ThemeFuse/Unyson-Empty-Extension" releases. (cURL error 7: )

Downloading the "SEO" extension...

Failed to access Github repository "ThemeFuse/Unyson-SEO-Extension" releases. (cURL error 7: )

Downloading the "Analytics" extension...

Failed to access Github repository "ThemeFuse/Unyson-Analytics-Extension" releases. (cURL error 7: )

Downloading the "Portfolio" extension...

Failed to access Github repository "ThemeFuse/Unyson-Portfolio-Extension" releases. (cURL error 7: )

Downloading the "Social" extension...

Failed to access Github repository "ThemeFuse/Unyson-Social-Extension" releases. (cURL error 7: )

Downloading the "Mega Menu" extension...

Failed to access Github repository "ThemeFuse/Unyson-MegaMenu-Extension" releases. (cURL error 7: )

Failed to access Github repository "ThemeFuse/Unyson-Sidebars-Extension" releases. (cURL error 7: )
Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (cURL error 7: )
Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 7: )
Failed to access Github repository "ThemeFuse/Unyson-Empty-Extension" releases. (cURL error 7: )
Failed to access Github repository "ThemeFuse/Unyson-SEO-Extension" releases. (cURL error 7: )
Failed to access Github repository "ThemeFuse/Unyson-Analytics-Extension" releases. (cURL error 7: )
Failed to access Github repository "ThemeFuse/Unyson-Portfolio-Extension" releases. (cURL error 7: )
Failed to access Github repository "ThemeFuse/Unyson-Social-Extension" releases. (cURL error 7: )
Failed to access Github repository "ThemeFuse/Unyson-MegaMenu-Extension" releases. (cURL error 7: )

Would you please let me know what I have to do?

Thank you!

**Comment by onioid** [comment]
Similar problem...

Can you guys pack the downloads in a complete package so as not to need accessing the repo? Would that work?
Not all of us are too code-savvy of course, which is why we're interested in page builders. :\  :)
I feel like I am back on a Sourceforge project... ;)

In any case, I will try something else as per the console output ('destination host forbidden, unlock the panel...') and try to let you know how it goes.

Output:

array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary
    (
        [*:data] => array
        (
            [date] => 'Thu, 09 Mar 2017 08:25:58 GMT'
            [server] => 'Apache'
            [content-type] => 'text/plain'
        )
    )
    [body] => 'Destination host forbidden, unlock the connection from your Altervista control panel (Resources > PHP Settings)'
    [response] => array
    (
        [code] => 403
        [message] => 'Forbidden'
    )
    [cookies] => array()
    [filename] => null
    [http_response] => WP_HTTP_Requests_Response
    (
        [*:response] => Requests_Response
        (
            [body] => 'Destination host forbidden, unlock the connection from your Altervista control panel (Resources > PHP Settings)'
            [raw] => 'HTTP/1.0 403 Forbidden
Date: Thu, 09 Mar 2017 08:25:58 GMT
Server: Apache
Content-Type: text/plain

Destination host forbidden, unlock the connection from your Altervista control panel (Resources > PHP Settings)'
            [headers] => Requests_Response_Headers
            (
                [*:data] => array
                (
                    [date] => array
                    (
                        [0] => 'Thu, 09 Mar 2017 08:25:58 GMT'
                    )
                    [server] => array
                    (
                        [0] => 'Apache'
                    )
                    [content-type] => array
                    (
                        [0] => 'text/plain'
                    )
                )
            )
            [status_code] => 403
            [protocol_version] => 1
            [success] => false
            [redirects] => 0
            [url] => 'http://github-api-cache.unyson.io/repos/themefuse/unyson/releases/latest'
            [history] => array()
            [cookies] => Requests_Cookie_Jar
            (
                [*:cookies] => array()
            )
        )
        [*:filename] => null
        [data] => null
        [headers] => null
        [status] => null
    )
)

**Comment by onioid** [comment]
[This may be relevant](url="http://forum.en.altervista.org/cms/1181-php-settings.html"):

http://forum.en.altervista.org/cms/1181-php-settings.html

**Comment by GheorgheP** [comment]
No, this is not possible as Unyson doesn't install all extensions, but only the required ones by your theme/plugin. Why your hosting do not allow requests to `unyson.io`?

**Comment by onioid** [comment]
Hi, thanks... Maybe with free hosting, it's locked down? 
But I will look more into it as my time warrants, it is possible I am not understanding this properly.

**Comment by GheorgheP** [comment]
Only the hosting can open access to `unyson.io`, also you can install the extensions manually.

Simply make a installation on your local machine and it will download all required extensions, you can copy theme to the server in `wp-content/plugins/unyson/framework/extensions/`.

**Comment by onioid** [comment]
Ah, thanks, GheorgheP...
Unsure how to do that, but I'll look into it as soon as I can, and try to report back here.

**Comment by celestegt** [comment]
Thank you very much.  I don´t know how I can do that, would you please help me?  I have installed Wordpress and Unyson in my hosting.  I have that  wp-content/plugins/unyson/framework/extensions/, but I did not understand what I have to copy in this folder  :)  Would you please help me?  Thank you!

**Comment by GheorgheP** [comment]
Here is an archive with all extensions, just unzip it in your extensions folder.
[extensions.zip](https://github.com/ThemeFuse/Unyson/files/834035/extensions.zip)

**Comment by celestegt** [comment]
Thank you very much!

**Comment by celestegt** [comment]
GheorgheP, thank you very much for helping me, all is working well now.  Have a nice day!

**Comment by ajayshrivas** [comment]
Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received)

**Comment by DarkSide666** [comment]
Please reopen this as this still is the issue more than 4 years from then !

```
Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
```

**Comment by beigi** [comment]
reopen this as this still is the issue more than 5 years from then !
Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

**Comment by vahidsadri20** [comment]
> reopen this as this still is the issue more than 5 years from then !
> Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

I have same issue, do you find resolve?

**Comment by afrinranu** [comment]
Hello dear i install a theme in my website but when i am doing install extrention its showing Downloading the "Backup & Demo Content" extension...

Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 60: SSL certificate problem: certificate has expired)

Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 60: SSL certificate problem: certificate has expired) what is the solution please

**Comment by afrinranu** [comment]
and also showinh Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 60: SSL certificate problem: certificate has expired)

**Comment by iqbalmbadhan** [comment]
Face same problem "Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)"

**Comment by NguefackLoic** [comment]
Downloading the "Social" extension...

Failed to access Github repository "ThemeFuse/Unyson-Social-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Downloading the "Shortcodes" extension...

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (cURL error 28: Connection timed out after 5000 milliseconds)

Downloading the "Media" extension...

Failed to access Github repository "ThemeFuse/Unyson-Empty-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Downloading the "Breadcrumbs" extension...

Failed to access Github repository "ThemeFuse/Unyson-Breadcrumbs-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Downloading the "Mega Menu" extension...

Failed to access Github repository "ThemeFuse/Unyson-MegaMenu-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Downloading the "Portfolio" extension...

Failed to access Github repository "ThemeFuse/Unyson-Portfolio-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Downloading the "Sidebars" extension...

Failed to access Github repository "ThemeFuse/Unyson-Sidebars-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Downloading the "Backup & Demo Content" extension...

Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Failed to access Github repository "ThemeFuse/Unyson-Social-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (cURL error 28: Connection timed out after 5000 milliseconds)
Failed to access Github repository "ThemeFuse/Unyson-Empty-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
Failed to access Github repository "ThemeFuse/Unyson-Breadcrumbs-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
Failed to access Github repository "ThemeFuse/Unyson-MegaMenu-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
Failed to access Github repository "ThemeFuse/Unyson-Portfolio-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
Failed to access Github repository "ThemeFuse/Unyson-Sidebars-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
Failed to access Gith

**Comment by NguefackLoic** [comment]
Hi sorry for the inconvenience I would like to know if you have solved your problem on the wordpress theme HUMAN CONSULT?

**Comment by Aitsimhand** [comment]
Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Operation timed out after 5002 milliseconds with 0 out of 0 bytes received)
Been getting this error every time when i try to install a plugin.

**Comment by AlexeyPolozItexus** [comment]
> Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Operation timed out after 5002 milliseconds with 0 out of 0 bytes received) Been getting this error every time when i try to install a plugin.

Yep, have same problem

**Comment by hagelric** [comment]
Same problem here

**Comment by hagelric** [comment]
any solution?

**Comment by sohamyoga** [comment]
Facing same issue, can you reopen the ticket.

**Comment by dotrock** [comment]
Installing Backup & Demo Content extension :

Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Connection timeout after 10001 ms)

**Comment by Djaber-Meghar** [comment]
Same issue , any help?

**Comment by CiprianGabor** [comment]
use this link to install the unyson plugin, **it automatically installs the Demo Content Install in Tools**: https://docs.wedesignthemes.com/dt_articles/import-demo/

**Comment by dassaffe** [comment]
same problem for me, doesn't work with the auto importer

**Comment by gonzalo1405** [comment]
Veo que en octubre de 2024 siguen con ese problema y a mitad de 2025 aún no se ha solucionado porque a mi me está pasando exactamente lo mismo:
Falló acceso al repositorio de publicaciones Github "ThemeFuse/Unyson-Shortcodes-Extension". (cURL error 28: Connection timed out after 10001 milliseconds)

**Comment by gonzalo1405** [comment]
I see that they're still having this problem in October 2024, and by mid-2025, it still hasn't been resolved because the exact same thing is happening to me:
Failed to access the Github publication repository "ThemeFuse/Unyson-Shortcodes-Extension". (cURL error 28: Connection timed out after 10001 milliseconds)
