### ISSUE TITLE
how to use get_post_meta/option unyson  in wp_query filter by meta_query

### ISSUE THREAD

**Issue by webdevid** [ThemeFuse/Unyson#124]
Hi, unyson is really awesome, and the option metabox really great. but i cant filter post_meta with wp_query. or maybe i am missing with that. can you tell me how to use option meta_box  unyson with wp_query > filter by post_meta.  

thanks

**Comment by saiful-droit** [comment]
I don't understand how can i solve this issue in my themes. 
Please replace

'save-in-separate-meta' => true

with

'fw-storage' => array(
	'type' => 'post-meta',
	'post-meta' => 'fw_option:{your-option-id}',
)

**Comment by moldcraft** [comment]
Instead of

```php
'foo-bar' => array(
    'type' => 'text',
    'save-in-separate-meta' => true,
)
```

change to

```php
'foo-bar' => array(
    'type' => 'text',
    'fw-storage' => array(
        'type' => 'post-meta',
        'post-meta' => 'fw_option:foo-bar',
    )
)
```

**Comment by uxtheme2017** [comment]
hi,
is it possible with 'multi-picker' type. I have post option, something like this [bellow]. 

'postmediakind'       => array(
		'type'         			=> 'multi-picker',
		'label'        			=> false,
		'desc'         			=> false,
 		'fw-storage' => array(
				'type' => 'post-meta',
				'post-meta' => 'fw_option:postmediakind',
			),
		'picker'       => array(
			'gadget' => array(
					'label'   => esc_html__( 'Post Media Kind', 'fw' ),
					'type'    => 'image-picker',
					'value'   => '',								 
					'choices' => array(					
						
						'video' => array(
							'small' => array(
								'height' => 50,
								'src'    => THEME_URI . '/admin/assets/img/post-media-gridgall.png'
							),
							 
						),
						'audio' => array(
							'small' => array(
								'height' => 50,
								'src'    => THEME_URI . '/admin/assets/img/post-media-camera-sld.png'
							),
							 
						),
						
						
					),
	
			)
		),
		'choices'      => array(
			
			'video'  => array(
		
				//do some thing						
				
			),
			
			'audio'  => array(
		
				//do some thing						
				
			),
			
										
			 
		),
		'show_borders' => false,
	),	

**When i try to retrieve post  WP_Query **  
$query = new WP_Query(
				array(
					'post_type'			=> 'post',
					'posts_per_page'	=> $perpage,
					'order'				=> $order,
					'orderby'			=> $orderby,				 
					'paged'				=> $paged, 
					'cat' 				=> $catid,
					'meta_query'		=>array(
			
							'meta_key' => 'postmediakind',
							'meta_value' => 'video',
							 
					) 
				)
			);

**But it is seem does not work for me, can you please advice**

Thanks in Advance
Sam

**Comment by saiful-droit** [comment]
I am little bit confuse #: moldcraft

**Comment by warudin** [comment]
I'm trying a meta_query on a multi-picker as well, but this won't work. I had expected it'd be possible to put fw-storage entries in the options that'd be needed for the meta_query. 

This is my code:
`$options = array(
	'focusgebieden_slider_box' => array(
		'type' => 'box',
		'options' => array(
			'focusgebieden_slider_picker' => array(
				'type' => 'multi-picker',
				'label' => false,
				'value' => array(),
				'picker' => array(
			        // '<custom-key>' => option
			        'focusgebieden_slider_options' => array(
			            'label' => __('Meenemen in slider focusgebieden?', 'youturn'),
			            'type'  => 'switch',
			            'fw-storage' => array(
							'type' => 'post-meta',
							'post-meta' => 'fw_option:focusgebieden-slider',
						),
			            'left-choice' => array(
							'value' => 'off',
							'label' => __('Nee', 'youturn'),
						),
						'right-choice' => array(
							'value' => 'on',
							'label' => __('Ja', 'youturn'),
						),
			        ),
			    ),
			    'choices' => array(
			    	'off' => array(),
			    	'on' => array(
			    		'focusgebieden_slider_title' => array(
							'type' => 'textarea',
							'label' => __('Samenvatting', 'youturn'),
							'fw-storage' => array(
								'type' => 'post-meta',
								'post-meta' => 'fw_option:focusgebieden-slider-title',
							),
						),
						'focusgebieden_slider_image' => array(
							'type' => 'upload',
							'label' => __('Beeld', 'youturn'),
							'images_only' => true,
							'fw-storage' => array(
								'type' => 'post-meta',
								'post-meta' => 'fw_option:focusgebieden-slider-image',
							),
						),
			    	),
			    ),
			),
		),
	),
);`

**Comment by GheorgheP** [comment]
I would recommend to stoare the desired value from `muti-picker` in an separate meta, as it will save arrays that will be serialized by WordPress.

**Comment by warudin** [comment]
When I put the `fw-storage` in the `switch` part there's no meta output.

<pre>
$options = array(
	'focusgebieden_slider_box' => array(
		'type' => 'box',
		'options' => array(
			'focusgebieden_slider_picker' => array(
				'type' => 'multi-picker',
				'label' => false,
				'value' => array(),
				'picker' => array(
					// '<custom-key>' => option
					'focusgebieden_slider_options' => array(
						'label' => __('Meenemen in slider focusgebieden?', 'youturn'),
						'type'  => 'switch',
						'fw-storage' => array(
							'type' => 'post-meta',
							'post-meta' => 'fw_option:switch',
						),
						'left-choice' => array(
							'value' => 'off',
							'label' => __('Nee', 'youturn'),

						),
						'right-choice' => array(
							'value' => 'on',
							'label' => __('Ja', 'youturn'),
						),
					),
				),
				'choices' => array(
					'off' => array(),
					'on' => array(
						'focusgebieden_slider_title' => array(
							'type' => 'textarea',
							'label' => __('Samenvatting', 'youturn'),
						),
						'focusgebieden_slider_image' => array(
							'type' => 'upload',
							'label' => __('Beeld', 'youturn'),
							'images_only' => true,
						),
					),
				),
			),
		),
		'context' => 'side',
	),
);
</pre>

**Comment by notrealdev** [comment]
Hi, how can i query posts by using fw_option with type `date-picker`?
The below code, i want get all post with has date-picker <= 30-12-2020 but it not working!!
```php
$date = date( 'Ymd', strtotime( '30-12-2020' ) );
$args = array(
    array(
        'key'     => 'fw_option:date',
        'value'   => $date,
        'compare' => '<=',
        'type' => 'DATE'
    ),
);
```

**Comment by warudin** [comment]
Something like this should work:

option config:
```
'date' => array(
	'type'  => 'datetime-picker',
	'value' => '',
	'format' => 'Y/m/d',
	'label' => __('Set a date', 'burkely'),
	'hide-bottom-border' => true,
	'datetime-picker' => array(
		'format'        => 'Y/m/d', // Format datetime.
		'maxDate'       => false,  // By default there is not maximum date , set a date in the datetime format.
		'minDate'       => false,  // By default minimum date will be current day, set a date in the datetime format.
		'timepicker'    => false,   // Show timepicker.
		'datepicker'    => true,   // Show datepicker.
	),
	'fw-storage' => array(
		'type' => 'post-meta',
		'post-meta' => 'date',
	),
),
```

query config:
```
$new_events_args = array(
	'post_type' => 'event',
	'posts_per_page' => '-1',
	'orderby' => 'meta-value',
	'order' => 'DESC',
	'meta_query' => array(
      	array(
			'key' => 'date',
			'value' => date("Y-m-d"),
			'compare' => '>=',
			'type' => 'DATE'
		),
    ),
);

$new_events = new WP_Query($new_events_args); 
```

**Comment by notrealdev** [comment]
Thank you, it working!!
