### ISSUE TITLE
Please share with us your experience with Unyson framework

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1240]
Hi dear Unyson users,

We want to make several improvements and need your opinion over them. This is why we will highly appreciate your feedback about your interactions with it. Please complete the following form with your opinion over Unyson experience:

https://kate282.typeform.com/to/GC8AUt

Your feedback will help us make significant improvements to the framework. 

Thank you once again for being an important member of the Unyson community! We intend to keep building its progress together with you and deliver you more benefits.

**Comment by Taimurian** [comment]
Just filled the form :)

**Comment by Alex-Ascet** [comment]
Done :)

**Comment by pe6o** [comment]
Filled :)

**Comment by moldcraft** [comment]
Thank you
