### ISSUE TITLE
Background video not auto play on Ipad

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#1241]
In page builder, if I use background video, it will not auto play on Safari on Ipad. It just shows the "poster" picture of the video only (Video from Youtube).
Hope you guys help.
Thanks,

**Comment by llemurya** [comment]
@TrangDinhVan we will test it and open an an issue at formestone.js , because we use this library for background video. Thanks!

**Comment by llemurya** [comment]
@TrangDinhVan the author of the library wrote as a notice 
```
Note: Mobile browsers do not allow videos to auto play due to bandwidth concerns. Background will not attempt to load videos on mobile devices, instead the poster image will be displayed.
```
Please see this on https://formstone.it/components/background/ page. I think it is clearly why the video will not auto play.
