### ISSUE TITLE
Update google fonts

### ISSUE THREAD

**Issue by Code-Divine** [ThemeFuse/Unyson#1243]
The fonts json file for the typography options is outdated. There are fonts missing like Roboto, Gotham and some others. Is there any chance for the next Unyson update to include those fonts? Or even better you can use the google fonts API to always pull the latest fonts? I've checked their API and the format they are retrieved is almost identical to what you have already in file.

Thanks

**Comment by llemurya** [comment]
@Code-Divine you talk about `typography` option type or about `typography_v2` option type.

**Comment by Code-Divine** [comment]
@llemurya  I am using the typography option type.
