### ISSUE TITLE
Unyson causes other plugins problem

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#1244]
Hi. Users report that Unyson causes problems to plugins with tabs (Yoast SEO for example). Some of them say the problem is caused by admin.js, so tabs in plugins do not work. 

Can you check guys?

Thanks.

**Comment by moldcraft** [comment]
Sorry we are busy at the moment.

You can check the problem yourself and submit a pull request.

**Comment by darwinteam** [comment]
couldn't find the root of problem

**Comment by darwinteam** [comment]
guys, when you have time can you take a look, I've heard other people building one Unyson having this problem

**Comment by andronic90** [comment]
Hi,
I test with our "The Core" theme and work fine: http://screencast.com/t/jg8leXLF
Then I activate the default WordPress theme and all work perfect.

Can you test this problem with default theme?

**Comment by danyj** [comment]
so far I know Unyson does not have admin.js,  what theme are you using and did you report it to developer?

**Comment by htusco** [comment]
> http://screencast.com/t/jg8leXLF
But now make a screencast of the Yoast settings and you will see that the content in the TABS are not showing !

**Comment by andronic90** [comment]
What theme are you use? I tested with "The Core" and "Twenty Sixteen" and all work perfect. Please test with the default WordPress theme

**Comment by htusco** [comment]
The Retouch theme: http://themeforest.net/item/retouch-app-wordpress-theme/11432322?s_phrase=&s_rank=29

But did you check if the SETTINGS pages work? Not a regular PAGE. That works for me too.

**Comment by andronic90** [comment]
Please contact the Theme Author, this error come from theme files
