### ISSUE TITLE
Shortcode style output

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1245]
Hello, 

What is the best way to deal with custom shortcode CSS output which is generated in shortcode view.php files?
For example:

```
<style type="text/css">
<?php if( ... ) { ?>
color: red...
background-color: ...
...
```
Because in end view I am getting too many generated `<style> `tags with generated content and therefore there should be the right way to do this.

**Comment by moldcraft** [comment]
Hi, use [this solution](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head)

**Comment by pear1** [comment]
Thank you for quick reply.

I can't get it working for button shortcode (can't find it in the HTML output)
_(from ../button/static.php file)_

```
if (!function_exists('_action_theme_shortcode_button_enqueue_dynamic_css')):

function _action_theme_shortcode_button_enqueue_dynamic_css($data) {
    $shortcode = 'button';
    $atts = shortcode_parse_atts( $data['atts_string'] );
    $atts = fw_ext_shortcodes_decode_attr($atts, $shortcode, $data['post']->ID);

    wp_add_inline_style(
        'theme-shortcode-'. $shortcode,
        'div { background-color: red!important; }'
    );
}
add_action(
    'fw_ext_shortcodes_enqueue_static:button',
    '_action_theme_shortcode_button_enqueue_dynamic_css'
);

endif;
```

Are there something wrong with my edited code?

**Comment by danyj** [comment]
use this one 

add this in theme helpers.php


	/**
	 * get shortcode options
	*/
	function _fw_shortcode_options($data,$shortcode){
		
		$atts = shortcode_parse_atts( $data['atts_string'] );
		$atts = fw_ext_shortcodes_decode_attr($atts, $shortcode, $data['post']->ID);
		
		return $atts;
	}


than use this  in shortcode static.php

	if(!function_exists('_button_css')){
		
		function _button_css ($data) {
		
			$atts 				= _fw_shortcode_options($data,'button');
	
			fw_print( $atts );

		}
		
		add_action('fw_ext_shortcodes_enqueue_static:button','_button_css');
	
	}

**Comment by pear1** [comment]
Thank you for this code snippet, it works.

But when I replace `fw_print( $atts );` with  `wp_add_inline_style( ... );` I still can't get any CSS ouput.

**Comment by danyj** [comment]
did you enque the style ? http://prntscr.com/9wesxc

**Comment by danyj** [comment]
u need to have this 


	wp_enqueue_style(
		'theme-shortcode-buttons',,// handle
		fw_ext('shortcodes')->locate_URI('/shortcodes/buttons/static/css/styles.css')
	);


than use same handle for inline

    wp_add_inline_style(
        'theme-shortcode-buttons',// handle
        '#shortcode-'. $atts['id'] .' { '.
            'color: '. $atts['color'] .';'.
        ' } '
    );

**Comment by pear1** [comment]
Thank you for clarification.
Looks like I will add output after general theme CSS file, therefore all output will be in one place.
