### ISSUE TITLE
Facebook and Twitter widgets not working 

### ISSUE THREAD

**Issue by justgeraldine** [ThemeFuse/Unyson#1248]
Hello. I need help with the Facebook and Twitter in widgets. We entered the API's in Unyson Social settings. We entered the info needed in the widgets for Facebook and Twitter. But it's not working; it's not showing anything.

**Comment by moldcraft** [comment]
Hi,

Which theme are you using?

**Comment by justgeraldine** [comment]
Hello. I'm using Culinier theme.

**Comment by moldcraft** [comment]
Have you reported this problem to theme author?

**Comment by justgeraldine** [comment]
Yep. I created a ticket. And they told me that I need to contact Unyson.

**Comment by moldcraft** [comment]
> But it's not working; it's not showing anything.

In frontend? If yes, then it's a theme issue.

Or tell me please in exact steps, how to reproduce the problem.

**Comment by moldcraft** [comment]
I will inspect this problem on Monday.

If you have some php skills, you can inspect it yourself, here's the extension https://github.com/ThemeFuse/Unyson-Social-Extension on your installation you can find it in `wp-content/plugins/unyson/framework/extensions/social`

**Comment by justgeraldine** [comment]
For Twitter, tweets show up but its purely texts. I created a screenshot here:
https://drive.google.com/file/d/0B7s77wL2bsXBXzA3MjR3c3RFN28/view?usp=sharing

**Comment by justgeraldine** [comment]
Sorry, I'm not skilled in php. So for the moment, we just use Twitter's own widget feature.

**Comment by duongancol** [comment]
Hi! I'm the author of Culinier theme. The Social icon is not compatible with my theme yet. If you still want use this widget, you have to config here: http://prntscr.com/9wuzdg, http://prntscr.com/9wuzyf
Then, You could get the tweet but I'm not sure about how it's displayed. Please reply at ticket if you need more help.
Thanks!
