### ISSUE TITLE
fw_get_google_fonts_v2 not updating

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1250]
This function should update google fonts json every 7 days 
https://github.com/ThemeFuse/Unyson/blob/f1a90c94b50622e4f92b28e0c2d040d2d9dbbd83/framework/helpers/general.php#L1032

my timestamp 
![screenshot_32](https://cloud.githubusercontent.com/assets/2340172/12702644/ad359bb2-c82e-11e5-8271-2a8d4d577a92.jpg)

which is date 

    echo date("m-d-Y", 1432373744);
    05-23-2015

and this font https://www.google.com/fonts#UsePlace:use/Collection:Poppins  is missing in json

**Comment by llemurya** [comment]
@danyj I tested and it update the fonts ,please watch this [video](https://youtu.be/GluVrwQNO8w).

**Comment by danyj** [comment]
bud , how would I than have may 23rd  2015 if it si updated?

**Comment by danyj** [comment]
Here , in frontend static I called it 

http://prntscr.com/9xok3v

	$do_fonts= fw_get_google_fonts_v2();
	
	fw_print($do_fonts);


just by calling the function it should check the fonts 

my time stamp is still  same 

     1432373744 // 05-23-2015

**Comment by danyj** [comment]
check , when printed it says last modified in may 
![screenshot_33](https://cloud.githubusercontent.com/assets/2340172/12723787/33a647be-c90b-11e5-848b-a96ee706079a.jpg)

**Comment by moldcraft** [comment]
Please test

**Comment by danyj** [comment]
:+1:  thnx!
