### ISSUE TITLE
Customize Popup

### ISSUE THREAD

**Issue by NwpDeveloper** [ThemeFuse/Unyson#1251]
The popup doesn't update the iframe in customizer on the initial save. 
If I hit the popup button, edit a text field, and hit SAVE. The iframe isn't updated. 
I have to hit the edit button again for the iframe to refresh.

**Comment by moldcraft** [comment]
Add [here](https://github.com/ThemeFuse/Unyson/blob/b86df931fdb954c7908865010172973a238aba39/framework/includes/option-types/popup/static/js/popup.js#L27)

```js
$input.trigger('change');
```

and let me know if it fixes the problem.

**Comment by NwpDeveloper** [comment]
Doesn't work. 

Replaced in popup.js. 
```
editItem: function (item, values) {
 item.find('input').val( JSON.stringify( values ) );
}
```
With 

```
editItem: function (item, values) {
	var $input = item.find('input'),
	val = $input.val();

	$input.val( values = JSON.stringify( values ) );

	if (val != values) {
		$this.trigger('fw:option-type:popup:change');
	}
}
```

**Comment by moldcraft** [comment]
Replace

```js
item.find('input').val( JSON.stringify( values ) );
```

with

```js
item.find('input').val( JSON.stringify( values ) ).trigger('change');
```

**Comment by NwpDeveloper** [comment]
Yes that works! 

Not sure how this affects popup in pagebuilder vs customizer. I'll test later.
