### ISSUE TITLE
nav-menu problem with qtranslate-x when mega menu is active

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#1253]
When mega menu is active, every save duplicates title.

If I'm on english tab, and hit save, duplication happens in the other language, and vice versa:

![screen shot 2016-02-01 at 9 44 02 am](https://cloud.githubusercontent.com/assets/8479569/12709746/633fbb88-c8c8-11e5-8ca1-ef7d96426ebf.png)

this doesn't happen when I disable unyson mega menu.

In db with mega menu turned off, `wp_posts` contains `nav_menu_item` with `post_title` (correct):
```
[:ka]სოციალური მიმართულებას[:en]Social Direction[:]
```
And with mega menu active (incorrect):
```
[:ka][:ka]სოციალური მიმართულებას[:en]Social Direction[:][:en]Social Direction[:]
```
And on each re-save it gets bloated (incorrect):
```
[:ka][:ka]სოციალური მიმართულებასსოციალური მიმართულებას[:en][:ka]სოციალური მიმართულებას[:en][:ka][:ka]სოციალური მიმართულებას[:en]Social Direction[:][:en]Social Direction[:][:][:][:en]Social DirectionSocial Direction[:]
```

I looked through all megamenu files, and couldn't find where it actually saves `nav_menu_item`

**Comment by sandrodz** [comment]
I found a workaround: disable mega menu, remove duplicate titles, enable mega menu.

**Comment by moldcraft** [comment]
Hello,

Thank you for report. We will inspect this issue later, currently we are busy with other issues. Sorry

**Comment by sandrodz** [comment]
Can you please direct me to the right direction? I'd be happy yo inspect. I'm really on tight deadline, and this was an unexpected bug that slipped testing.

**Comment by moldcraft** [comment]
The MegaMenu extension is not big.

Key files are:

* https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/class-fw-extension-megamenu.php
* https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/includes/class-fw-ext-mega-menu-admin-walker.php
* https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/hooks.php
* https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/includes/functions.php#L28

Try to disable actions/filters one by one to detect which one is causing the problem, or inspect functions which load/save database data.

**Comment by sandrodz** [comment]
I went through all files before even posting the issue, but couldn't identify a problem.

atm I went through hooks.php and functions.php disabled all actions there, and problem remained.

**Comment by sandrodz** [comment]
class-fw-extension-megamenu.php:line43 commenting seems to help.

`//add_filter('wp_edit_nav_menu_walker', array($this, '_admin_filter_wp_edit_nav_menu_walker'));`

but I don't think its a walker issue.

**Comment by sandrodz** [comment]
Issue seems to be only with "Navigation Label" but "Title Attribute" doesn't exhibit same problem.

**Comment by moldcraft** [comment]
> what could be in walker causing this?

Debug [database values](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/includes/class-fw-ext-mega-menu-admin-walker.php#L30) (with `fw_print()`)

**Comment by sandrodz** [comment]
DB values are fine, its after save that things go crazy. I couldn't find how fw saves `nav_menu_item` post_type

**Comment by moldcraft** [comment]
Then debug the save, find the point where the title is doubled. Add print or die in WordPress core where the save happens, also in qTranslate.

*Also I you know how to install and configure, you can use [`xdebug`](https://www.google.com/webhp#q=php+xdebug+tutorial) in your IDE*

**Comment by sandrodz** [comment]
Another thing I've noticed, duplication doesn't happen when something is changed. So if I change value and save, no duplication occurs, but value is duplicated when I hit save and nothing was changed in inputs.

So save works, update doesn't work. Now the thing is to find update of what is failing.

**Comment by sandrodz** [comment]
I'm about to give up, I've spent whole day with this :( when do you think you could take a look?

**Comment by sandrodz** [comment]
haha! it seems this is causing the issue:

```

					<label>
						<span class="hide-if-mega-menu-item"><?php _e('Mega Menu Column Title', 'fw') ?></span>
						<span class="hide-if-mega-menu-column"><?php _e('Item Title', 'fw') ?></span><br />
						<?php // -------------------------- ?>
						<?php // NOTE this is a post title! ?>
						<?php // -------------------------- ?>
						<input type="text" name="menu-item-title[<?php echo esc_attr($item_id) ?>]" value="<?php echo esc_attr($item->title) ?>" class="widefat mega-menu-title" />
					</label>

```

as you can see there are duplicate inputs!

![screen shot 2016-02-01 at 10 26 57 pm](https://cloud.githubusercontent.com/assets/8479569/12726799/ff493e40-c932-11e5-9d3b-cde9248a2cd9.png)

**Comment by moldcraft** [comment]
:thumbsup:

Can you submit a pull request?

**Comment by sandrodz** [comment]
I'm thinking how to fix this.
I will probably rewrite so that there is only 1 input, and labels are shown or hidden according to if its a column or a mega menu item. This would avoid duplication and retain original functionality.

**Comment by sandrodz** [comment]
@moldcraft I did following: https://gist.github.com/sandrodz/e52a08f60d6dd22f60f6

But its not pretty, so I'm not going to do PR. I simply combined two inputs with identical `name=` into one and changed whole html around it.

AS a result title and label are not aligned as they used to be. Though in column mode I managed to align hide checkbox correctly:

![screen shot 2016-02-02 at 10 52 14 pm](https://cloud.githubusercontent.com/assets/8479569/12760410/bbafdc3e-c9ff-11e5-8a2c-c2ff7b6992da.png)
![screen shot 2016-02-02 at 10 52 20 pm](https://cloud.githubusercontent.com/assets/8479569/12760412/bbe4b99a-c9ff-11e5-84ef-fff9ab057c99.png)

**Comment by Nikschavan** [comment]
I tried @sandrodz's solution but it is deleting the menu item when "Hide title" is turned on.

Here I made a screencast - http://goo.gl/CyqYKy

I am using latest unyson framework and latest mega menu extension with @sandrodz's patch.

**Comment by sandrodz** [comment]
Hey, I don't remember exactly, but I think I had same problem with hide title. I didn't need hiding functionality so I just didn't implement.

Actually you can simply hide the menu item by saving `&nbsp;` I think this is what I told editors to do.

**Comment by moldcraft** [comment]
@Nikschavan I think it is deleted because of [this bug in WP](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/issues/8)

**Comment by Nikschavan** [comment]
@sandrodz I wish I could also just drop the hide option :sweat: 
@moldcraft This does not seem to be because of the WordPress bug the menu items do not get deleted when default v1.0.10 os mega menu extension.

**Comment by Nikschavan** [comment]
@moldcraft Can you check the PR https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/pull/10?

I am using jQuery to keep only one input field active at a time.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/pull/10

**Comment by sandrodz** [comment]
This problem is still not resolved.

**Comment by sandrodz** [comment]
Column / nested menus have same problem, they get duplicated. But parent one works fine.

**Comment by sandrodz** [comment]
@Nikschavan I think your PR is actually misbehaving atm.

on page load mega menu parent item is disabled by js merged in that commit.

<img width="446" alt="screen shot 2017-05-05 at 3 02 10 am" src="https://cloud.githubusercontent.com/assets/8479569/25728320/4b74754e-313f-11e7-976f-343536b6b3ad.png">

and the problem remains will nested items.

**Comment by sandrodz** [comment]
@danyj can you please open this?
