### ISSUE TITLE
Switch option double quotes variables inside customizer.

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1254]
When dynamically updating options in the customizer via javascript, switch option is double quoting the value that it holds.
In the backend when accessed via php, everything is ok. 
![image](https://cloud.githubusercontent.com/assets/390700/12729339/78a82204-c926-11e5-9f06-780dac15e12d.png)

**Comment by moldcraft** [comment]
It's json encoded. Use

```js
var val = JSON.parse(data[0].value);
```

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1083

**Comment by ivandotv** [comment]
I'm alreading parsing JSON , this is the whole code.

````javascript
      var data = JSON.parse(newVal);
      console.log(data[0].value);
````

**Comment by moldcraft** [comment]
I added one `switch` option in `customizer.php` and followed [these instructions](http://manual.unyson.io/en/latest/options/introduction.html#live-preview) and the value is not double quoted

![](http://static.md/b2ca745fbd6c544bdb2df65309889450.png)

> dynamically updating options in the customizer via javascript

How to do that? Please give the exact steps to reproduce the problem

**Comment by ivandotv** [comment]
Well I think you are double parsing the elements.
Where did the `test` variable come from? is that the `newValue` that is passed by the customizer?
If so, if you use json parse on it, you should get the object with the value that is not double quoted.

**Comment by moldcraft** [comment]
> is that the newValue that is passed by the customizer?

yes, I did

```
window.test = newval =JSON.parse(newval);
```

> Well I think you are double parsing the elements.

How should I do?

**Comment by ivandotv** [comment]
My understanding is,and it works with all other option types , and wordpress native options also. 
Is that when you parse the `newval` that is it. You get your object that is properly quoted.
Keep in mind that is all you need to do when working with other options.

**Comment by moldcraft** [comment]
When the value is not encoded we have issues with boolean values https://github.com/ThemeFuse/Unyson/issues/1083

**Comment by ivandotv** [comment]
Okay, but this is going to confuse a lot of people. You should probably but it in the docs.
And for now, I'm using `indexOf` to test if the value is what I'm looking for.
