### ISSUE TITLE
How to review/approve translations?

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1256]
Recently I figured out how translations work and updated [the `.pot` file](https://github.com/ThemeFuse/Unyson/blob/master/languages/unyson.pot) on [transifex](https://www.transifex.com/themefuse/unyson/)

[There](https://www.transifex.com/themefuse/unyson/) are a lot of translations in different languages, I have no idea how to review and approve them.

The only way I see, is to find persons responsible for the language they speak, give them approval access and just trust that they will not translate/approve some wrong/bad words. Or there are other solutions?

**Comment by danyj** [comment]
make translation git like we did https://github.com/YJSGframework/yjsg-translations and have the users contribute

**Comment by moldcraft** [comment]
The format doesn't matter.

> have the users contribute

Ok, users contribute, transifex is a graphical convenient way to translate. The question is how to check if the translations are correct?

**Comment by danyj** [comment]
I guess we would have to trust them until their landsman/landswomen start complaining.
