### ISSUE TITLE
Combining Unyson Page Builder and Visual Composer

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1258]
Is this possible - combining the two plugins?

Some of my clients ask (I suppose they have some VC shortcodes that they want to use) and I just can't think of a way that this can happen. Is it possible in any form for this to be achieved?

**Comment by moldcraft** [comment]
I have no idea.

**Comment by 2Fwebd** [comment]
Hi there, 

Yes ! It is. We're doing it for our customers. 

All page builder's elements can be wrote as plain shortcode using the /options.php as shortcode's attribute.  

Then you can add your shortcode following this video : https://www.youtube.com/watch?v=hvGb8kcEJ9s

I have no idea what the theme you're using @pe6o but go to theme-name/framework-customizations/extensions/shortcodes/shortcodes/**yourshortcode/options.php **

You'll find something like (example that we're using in our theme)  : 

```
$options = array(
	'title'  => array(
		'label' => __( 'Title', 'woffice' ),
		'desc'  => __( 'This is the title of the box.', 'woffice' ),
		'type'  => 'text',
	),
	'content'  => array(
		'label' => __( 'Content', 'woffice' ),
		'type'  => 'wp-editor',
		'tinymce' => false,
		'media_buttons' => false,
		'desc'  => __( 'This is the content of the box.', 'woffice' ),
	),
	'icon'                      => array(
		'label' => __( 'Icon', 'woffice' ),
		'type'  => 'icon',
		'desc'  => __( 'The icon will be displayed in the background with a small opacity', 'woffice' ),
		'value' => 'fa fa-group',
	),
	'color'        => array(
		'label' => __( 'Background color', 'woffice' ),
		'type'  => 'color-picker',
		'desc'  => __( 'The background of the box, remember that the white color should come out.', 'woffice' ),
		'value' => '#d05c3d'
	),
);
```

The shortcode that you can use from the VC would be : 

**[alert title="" content="" icon="" color="" /]**

@moldcraft, please remove the link if you find it inappropriate, here is an article that explains it for our theme : https://2f.ticksy.com/article/5293/ it can be used for all the Unyson themes, well shortcodes list needs to be updated of course. 

I'm not saying it's an easy solution, yet it's working just fine ;)

Cheers, 

2F

**Comment by moldcraft** [comment]
@2Fwebd Thanks

**Comment by pe6o** [comment]
@2Fwebd Thank you. We are having some clients that ask how they can combine the two builders and this is very helpful. Thank you again.
