### ISSUE TITLE
WP Update has messed with Unyson Install

### ISSUE THREAD

**Issue by Markaata** [ThemeFuse/Unyson#1259]
Need some help!  Latest update yesterday totally f'd my site up.  Unsyon is still active and I reactivated the extensions, but I cannot see the editor in the backend, and my site is a mess now.  Please help!

![screen shot 2016-02-03 at 9 41 04 am](https://cloud.githubusercontent.com/assets/17047617/12785376/4deef45e-ca5a-11e5-987a-bec88a66fd12.png)

**Comment by danyj** [comment]
did  you update WP or Unyson ?

**Comment by moldcraft** [comment]
1. Which Unyson version you have installed?
2. Extensions are up-to-date?
3. Have you tried to restore the pages from Revisions?
4. Do you have backups of your site (database) ?

**Comment by Markaata** [comment]
WP auto updated to version 4.4.2 yesterday, which caused the problem.  I have Unyson 2.4.17 installed. When I logged in extensions were deactivated, but I have reactivated them.  I have a backup from October, unfortunately nothing more recent that that.

**Comment by Markaata** [comment]
Tried restoring a previous page version but that didn't fix it, page builder still isn't working.

**Comment by moldcraft** [comment]
Apache error.log has some error from yesterday?

> page builder still isn't working

**Pages** are checked on [Settings page](https://static.md/378f1880a531a3a4e4e48cfc3493591d.png) ?

**Comment by moldcraft** [comment]
Please create a backup of your content before playing with Revisions.

----

Try to reproduce the auto-update problem, to see if extensions will be deactivated, by following [these steps](https://gist.github.com/moldcraft/1fe4c3cded8536c66a19)

**Comment by danyj** [comment]
I just checked , by disabling on pages I get the same format and editor you have now

make sure this is checked

![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/12785872/dbb5737e-ca8e-11e5-9298-acec614a0381.jpg)


![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/12785878/df58d354-ca8e-11e5-9219-a4f511ba84df.jpg)

**Comment by Markaata** [comment]
That fixed it. Apparently page builder wasn't installed, I had to select 'see other extensions' and activate it from there. Very strange that it deactivated after the WP update.  Thank you for the help!! :)

**Comment by moldcraft** [comment]
Try to reproduce the auto-update problem, to see if extensions will be deactivated, by following [these steps](https://gist.github.com/moldcraft/1fe4c3cded8536c66a19)

We need to find the cause of this problem.

**Comment by danyj** [comment]
@Markaata what theme is that?  it should have had builder as required extension

**Comment by Markaata** [comment]
Theme is Airashi, which came with the plug-in. http://themeforest.net/item/airashi-clean-personal-wordpress-blog-theme/10699220 

I have let the theme developer know about the issue. How do I re-produce the  WP upgrade issue?

**Comment by danyj** [comment]
> Will now try to reproduce problem.
thnx!  will help all of us , this bug is pissing us off since few months now.

**Comment by moldcraft** [comment]
> How do I re-produce the WP upgrade issue?

Follow [these steps](https://gist.github.com/moldcraft/1fe4c3cded8536c66a19) to reproduce plugin auto-update. 

I think the same steps can be done to reproduce WordPress auto-update (not tested), just do not change plugin version but [change WordPress version](https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/version.php#L7) (lower the last number only).
