### ISSUE TITLE
Custom shortcode doesn't work properly

### ISSUE THREAD

**Issue by AceoK** [ThemeFuse/Unyson#1260]
Hi, 
I copied section shortcode and replaced all "section" with "colset", also renamed all files. When I trying to use it, I get html not as in my view.php file

this is view.php
`<div class="col-set">
	<?php echo do_shortcode( $content ); ?>
</div>`

this is what i get
`<div class="col-1"><div class="col-set"></div></div>`

**Comment by moldcraft** [comment]
Hello,

I don't know why, need more details, maybe admin/ftp access.

**Comment by AceoK** [comment]
It's on my local machine.
I guess that is not enough detail, but I thought that maybe you have something like this has happened

**Comment by moldcraft** [comment]
Nope.

Try to debug both your shortcode and section by placing `fw_print()` in the "same" files and finding which `fw_print()` will not be executed in your shortcode and why

**Comment by AceoK** [comment]
Hi,

fw_print($tag) of my shortcode outputs '`section`'
fw_print($content) outputs `[row][column width="1_1" _made_with_builder="true"][colset count="" _made_with_builder="true"][/colset][/column][/row]`

why tag is section? my folder name is colset.

**Comment by danyj** [comment]
did you change the config.php ?  
http://manual.unyson.io/en/latest/extension/shortcodes/index.html#creating-a-simple-shortcode
