### ISSUE TITLE
Addable-box arrow problem

### ISSUE THREAD

**Issue by coderontheroad** [ThemeFuse/Unyson#1261]
I am using latest version of WP. And github version of Unyson.

Addable box option has arrow showing problem like;
http://prntscr.com/9zc431

**Comment by moldcraft** [comment]
Can't reproduce

![](https://static.md/7d5f8d3d7df326d43102b59943fc9a9b.png)

Version 4.4.2 | Unyson 2.5.0

----

Please inspect the css and tell us where the problem comes from.

**Comment by coderontheroad** [comment]
@moldcraft can you try to add addable box to page metabox?
In settings or taxonomy metabox i didn't get this bug, but page and posts has this problem. One of my addable box in framework-customizations/theme/options/posts/page.php. Same version wp and unyson (Version 4.4.2 | Unyson 2.5.0).
