### ISSUE TITLE
Extensions Save Button redirects to Home Page 

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#1262]
Hi there, 

We have a really weird issue with one of our customers, whenever he tries to save an extension from the extension's settings page, he's redirecting to the Home page and nothing is saved. 

First time I see this. Here is what has been done : 

- Checking log files on the FTP : nothing
- Checking Console : all clear
- Checking AJAX from theme settings : working just fine 
- Deactivating ALL plugins (except Unyson of course) same issue

You'll also find a network record of the redirection. 

Please let me know if you have any idea about that, we have all the details and we can make changes on the FTP if required. 

![intranet_hytec_ _un_site_utilisant_wordpress](https://cloud.githubusercontent.com/assets/5446124/12861266/6c162060-cc62-11e5-9313-c199ddef9958.jpg)

Thanks for the help :)

Cheers,

2F

**Comment by danyj** [comment]
did you click on preserve log ? sometimes error fires while saving and you cant cache it untill you preserve it in console

**Comment by moldcraft** [comment]
Hello

> save an extension from the extension's settings page

Which extension?

----

The problem may be in hosting's anti sql injection protection https://github.com/ThemeFuse/Unyson/issues/1136

**Comment by moldcraft** [comment]
https://wordpress.org/support/topic/page-builder-does-not-save-changes

**Comment by 2Fwebd** [comment]
I didn't catch anything with the log... :/ 

Sorry for delay here .. Busy days... 

@moldcraft Woffice again on your ticket, I think it depends on the host configuration. Because we only have 1-2 tickets about that on 2000+ Unyson based themes sold. So it's not a global issue. 

Yet, if you need to have some access to our theme's code, to have a look closer. I can send you our files. 

Keep me updated, 

2F

**Comment by keitharrowsmith** [comment]
Hello - and thanks to everyone trying to help on this issue - I've spoken to the host (1and1) and they confirm that they have some anti sql injection protection which may be causing the issue. They need some information about the issue and promise to look into it. 

The error occurs when I try to save an extension from the Unyson framework - instead of injecting the code, i just get dumped back to the website home screen.

**Comment by moldcraft** [comment]
Hello @keitharrowsmith open browser Inspector (F12) > Network and check POST variables on form submit.

**Comment by keitharrowsmith** [comment]
Thanks @moldcraft 
Here is the screenshot of the Inspector > Network variables on form submit. Does that shed any light?
![screen shot 2016-05-12 at 17 10 04](https://cloud.githubusercontent.com/assets/19321846/15221789/c8ca139a-1864-11e6-96eb-2cceafe79578.png)

**Comment by moldcraft** [comment]
Click on it and inspect POST variables. Copy them and send to hosting support team, they will look if variables contain some restricted words by the security system.

**Comment by keitharrowsmith** [comment]
Thanks again @moldcraft 
Here are the screenshots - after I click. If you can give me a pointer on the variables to highlight, that would be fantastic - thanks

![capture1](https://cloud.githubusercontent.com/assets/19321846/15254361/5ea6ad5a-192e-11e6-9c3f-069287d41c0c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/19321846/15254366/63d8563e-192e-11e6-9111-02a612b8dfa8.PNG)
![capture3](https://cloud.githubusercontent.com/assets/19321846/15254373/692cf072-192e-11e6-9f97-1cd1072287ad.PNG)

**Comment by moldcraft** [comment]
@keitharrowsmith 

1. Disable all plugins except Unyson (maybe the problem comes from some plugin)
2. Open extension `settings-options.php` and change option ids one by one and do Save, to detect which one is causing the security system to treat its name as a restricted name

    ![](https://static.md/f2e83ffe444c3bc68219533718afc598.png)

**Comment by susipop** [comment]
Hello, I found out that in my case, my server is a Unix server, not a Linux server. So, I don't know how or why, it does not like the ajax script. It seems that returns a 500 server error.
I still will solve with my client if we change servers or ask web.com to solve this issue for us.

I hope this helps.

**Comment by moldcraft** [comment]
Please reOpen the issue if this still happens and send me your admin and ftp credentials to `moldcraft[at]email.com`
