### ISSUE TITLE
oEmbed preview , links and output

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1263]
oEmbed , http://manual.unyson.io/en/latest/options/built-in-option-types.html#oembed

is a great option type but the admin preview should be generated before we hit save just like the editor does. 
The point of the preview is to see if link is valid/usable before we save. 

![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/12865492/bab7656c-ccad-11e5-9e95-20778de2b811.jpg)

Another thing is, if you for example add a flicker image 
https://www.flickr.com/photos/kitkit201/24528401812/
, than you click on it , it links directly ( same window )  thus taking you away from admin , this should be 

```
target="_blank" 
```

And last and hope the least is , oEmbed  main feature according to WP https://codex.wordpress.org/Embeds is 

> It's super easy to embed videos, images, tweets, audio, and other content into your WordPress site.

so the output should parse the links and give us the embed code , and not only the link we entered 

![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/12865480/3ce29bca-ccad-11e5-8a34-6e14081db3cc.jpg)

**Comment by llemurya** [comment]
@danyj the live preview works , please see this [video](https://www.youtube.com/watch?v=Z61nZxuEaeI).If you want in frontend to see oembed just run this code
```php
$embed_code = wp_oembed_get('http://www.youtube.com/watch?v=AbcDeFg123');
```

**Comment by danyj** [comment]
does not work in post or page options 
http://screencast.com/t/KreXxB3CGq

thnx for oemebed , I figured  it out , forgot to notify you

**Comment by danyj** [comment]
here your embed ajax  returns 0  

http://prntscr.com/a0qkp1

    action:get_oembed_response

**Comment by danyj** [comment]
what I noticed with options that need ajax , is that I had to include them in 

    fw_init 

not 
 
    fw_option_types_init


so in my options.php  I have this http://prntscr.com/a0qo18

**Comment by llemurya** [comment]
@danyj I'l test it and become with an fix.Thanks for reporting.

**Comment by ivandotv** [comment]
Just experienced this issue myself. 
Because of this when the user enters the link to oembed content, the content is not shown. Only after post save and full page reload oembed content is loaded.
Also when user changes the link in the oembed field, old content is still displayed.

After inspecting the php code, it seems that  php framework **action**   `wp_ajax_get_oembed_response` is never fired and ajax request returns 0.
That makes this option effectively unusable.
