### ISSUE TITLE
Get option from page into css

### ISSUE THREAD

**Issue by zohaib87** [ThemeFuse/Unyson#1264]
Hi, i want to get value from page but display it without echoing it as it is inside anothor variable. is it possible? i need to use it as dynaimc css and i am putting styles into stylesheet with file_put_contents()

```
$styles_here = fw_get_db_post_option($post_id, 'sub_heading');
$styles_dy = '
@media (min-width: 768px) {
	.fw-container {
		width: 750px;
	}
}
@media (min-width: 992px) {
	.fw-container {
		width: 970px;
	}
}
@media (min-width: 1200px) {
	.fw-container {
		width: 1170px;
	}
}

' . $styles_here . '

';
```

Regards,

**Comment by danyj** [comment]
http://manual.unyson.io/en/latest/extension/shortcodes/#enqueue-shortcode-dynamic-css-in-page-head

**Comment by zohaib87** [comment]
@danyj thank you, i knew this one. just wanted to know if there is another way. is there another way to get value? besides fw_get_db_post_option() ?

**Comment by danyj** [comment]
here is how to get , page , post , theme , tax options 
http://manual.unyson.io/en/latest/helpers/php.html#database

shortcodes is 


    $atts

**Comment by zohaib87** [comment]
Hi, new problem.. you said dynamic css: 
http://manual.unyson.io/en/latest/extension/shortcodes/#enqueue-shortcode-dynamic-css-in-page-head 
but the problem is same when getting option from pages with fw_get_db_post_option() because values needs to in variable and echo is not possible inside variable :( what to do?

**Comment by zohaib87** [comment]
I think fw_get_db_post_option() should display value without typing echo before it.

**Comment by zohaib87** [comment]
Here is what I did. 
```
function title_background_gradient_primary() {
	$title_background_gradient = fw_get_db_post_option(get_the_id(), 'title_background_gradient');
	echo $title_background_gradient['primary'];
}
```
now I can use get value inside variable :-)
