### ISSUE TITLE
Unyson plugin with other templates installed

### ISSUE THREAD

**Issue by relascope** [ThemeFuse/Unyson#1266]
Installed Unyson, played a bit. 
Installed other template (layerswp). 
Things work different, when in customize mode, vs live mode. 

Especially, that the `after_setup_theme` isn't called for the other template (in live mode). 
In the customize mode it does what it should. 

Deactivating Unyson, and the other theme works fine. 
Activating Unyson and the other them *still* works fine...

**Comment by moldcraft** [comment]
Can you test with the latest dev version of Unyson from Github? Maybe your issue is related tot this https://github.com/ThemeFuse/Unyson/issues/1235 ?
