### ISSUE TITLE
multi-select suggestions bug - suggestions disappear

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1267]
I'm creating a `multi-select` field populated with a custom categories. After selecting a category and clicking save, returning to the options of this particular shortcode again takes me to the bug.

The suggestions are no longer there. 
!) In the beginning everything is normal
![image](https://cloud.githubusercontent.com/assets/1108563/12873299/ebd16868-cdc1-11e5-964f-be6b7a52bbc4.png)
2) After saving and returning (no suggestions):
![image](https://cloud.githubusercontent.com/assets/1108563/12873304/08bb9368-cdc2-11e5-8be1-6675cf758aa6.png)

Latest version of Unyson and Wordpress.

**Comment by moldcraft** [comment]
This should be fixed in latest version

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/330
