### ISSUE TITLE
How and where are slider static files included?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1269]
I am trying to extend extension sliders and need to test owl slider 2 beta , but cant find where you include the files. There is no static.php in any of the extension folders

**Comment by danyj** [comment]
And also , how do you disable specific slider ?

**Comment by llemurya** [comment]
@danyj please see this [ticket](https://github.com/ThemeFuse/Unyson/issues/431) and read about [static files](http://manual.unyson.io/en/latest/extension/slider/index.html#static-files).

**Comment by danyj** [comment]
Noticed that

>static/css/ - directory for styles. They will be automatically enqueued in frontend


 , you are enquing css files in page body which is invalid html
http://prntscr.com/a0l8au  do I need to open new issue about that or can you take it from here?

**Comment by llemurya** [comment]
@danyj I know about this , we do that only for demo , you can set your css and javascript files in your theme static files.At that moment we didn't have a mechanism how to determine in what page is rendered  slider shortcode and enqueue styles and js only for that page.

**Comment by danyj** [comment]
@llemurya  sorry bud I lost you there , I am talking about you loading the slider CSS files inside the body tag which is not valid html, CSS files should be loaded in head tag , not in body,

**Comment by moldcraft** [comment]
It should use [this action](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.9/class-fw-extension-shortcodes.php#L149)

**Comment by giathinh910** [comment]
Hi @danyj, Did you find out the way to move the css to head?

**Comment by danyj** [comment]
@giathinh910   yes , I used my own [collector class ](https://github.com/YJSGframework/yjsg/blob/master/includes/yjsgcore/classes/yjsg.dochead.class.php)that collects all css added in shortcodes  or static.php
https://github.com/ThemeFuse/Unyson/issues/1245#issuecomment-176802025


than  function from #1245 becomes this 



```

if(!function_exists('_button_css')){

    function _button_css ($data) {

        $atts    = _fw_shortcode_options($data,'button');
		$color	 = fw_akg('color',$atts);
		$css ='.something{';
		$css .='color:'.$color.';';
		$css .='}';	
		
		
		if($add_css  !=''){
			YjsgDochead::getDocument()->addCssInhead( $css);
		}
    }

    add_action('fw_ext_shortcodes_enqueue_static:button','_button_css');

}

```


and in hooks.php 

```
/**
 * Dynamic CSS 
 */
function _my_action_enqueue_dynamic_scripts() {
	
	$css= '';

	// cssinhead
	if ( isset( YjsgDochead::getDocument()->dochead['cssinhead'] ) ) {
		$css.= implode( YjsgDochead::getDocument()->dochead['cssinhead'] );
	}
	
	wp_add_inline_style( 'myhandle', $css);
	
	
	
}

add_action( 'wp_enqueue_scripts', '_my_action_enqueue_dynamic_scripts', 90 );


```


note , if you used my YjsgDochead class comment this out  to pass theme check ( that is not used anyway ) 


https://github.com/YJSGframework/yjsg/blob/master/includes/yjsgcore/classes/yjsg.dochead.class.php#L237-L240
