### ISSUE TITLE
How to add Page Builder inside Tab editor(content element)

### ISSUE THREAD

**Issue by lordzeph** [ThemeFuse/Unyson#1270]
Hello, 
In wordpress, when Im editing the content of the created tab (content element), i want to edit and add things with Page Builder, but there is just the default wp editor, with no Page Builder button.
How to add this Page Builder inside the shortcode tab?
/framework-customizations/extensions/shortcodes/shortcodes/tabs

**Comment by moldcraft** [comment]
Hello, it is not possible.

Or @danyj maybe knows a solution, he did something similar.

**Comment by danyj** [comment]
I did not make it , if editor is called inside the builder element for example tabs , the unyson shortcode is not showing , if editor is called outside like in page options , unyson editor button is there , I need this to and we are all waiting for it #756

**Comment by lordzeph** [comment]
maybe  adding a shortcode as a button in the editor? here is a picture, I think it is possible:
http://docs.themefuse.com/exposure/your-theme/portfolio/add-visual-builder-shortcodes-to-your-portfolio-pages

**Comment by moldcraft** [comment]
Recently we have release the WordPress Shortcodes extension, try it out.

**Comment by toleabivol** [comment]
Just a note : In addition to the extension one must use `wp-text` with `shortcodes => true`
