### ISSUE TITLE
HTML from theme hidden

### ISSUE THREAD

**Issue by chrisuehlein** [ThemeFuse/Unyson#1271]
Hello,
I am dealing with a very confusing issue with Unyson and Coupon Hut theme. I am trying to customize the PHP but all the elements I have added are in the page source but are not showing up on the page. When I inspect these elements (which usually highlights the inspected area) there is nothing that pops up. Is Unyson hiding them? Is there a way to add an HTML code block segment to Unyson pagebuilder? That could solve my problem as well.

**Comment by moldcraft** [comment]
Hello,

Please explain us the exact steps how to reproduce you problem (also better with screenshots).

**Comment by chrisuehlein** [comment]
Excuse me for the extended delay in my response. I discovered my issue was caused by my own error. This ticket can be closed.
