### ISSUE TITLE
Trying to get section Name in page builder

### ISSUE THREAD

**Issue by Slipkonn** [ThemeFuse/Unyson#1272]
Hi! It would be great to get some help - i am trying to get section Name (from my option) instead of "Section" in page builder heading - it would be great when there are many sections in page to see section name in block header.

So i am get to this point:

add some code in _shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php_
`$data['title'] = var_dump($attributes['atts']);` turn to

`$options = fw_extract_only_options($options);

		$attributes['atts'] = fw_get_options_values_from_input(
			$options, array()
		);

		$data['title'] = var_dump($attributes['atts']);`

and i see an array
`array(6) { ["backend_name"]=> string(0) "" ["is_fullwidth"]=> bool(false) ["custom_class"]=> string(0) "" ["background_color"]=> string(0) "" ["background_image"]=> string(0) "" ["video"]=> string(0) "" }`

but cant get the value of ["backend_name"] like this
`$data['title'] = $attributes['atts']["backend_name"];`

Any help from php guru would be great!

**Comment by moldcraft** [comment]
Create

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/section/config.php
```

and make sure to set [`$cfg['page_builder']['title_template']`](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file)

**Comment by Slipkonn** [comment]
It was realy simple, thank you)
