### ISSUE TITLE
Column alignment

### ISSUE THREAD

**Issue by tiagocaus** [ThemeFuse/Unyson#1274]
I put two columns. The left with an image and the right with 3 Broad Icon Box.

In addition to not leave one in each column, the broad box icon, the icon does not show each one, only showing the first.

See the image:
-http://i.imgur.com/d0zu7cV.png
-http://i.imgur.com/mW0cp3v.png

What is wrong?

**Comment by moldcraft** [comment]
Have you reported this problem to theme author? Which theme are you using?
