### ISSUE TITLE
Cant install demo content. Loopback connection disable

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1276]
On heartinternet, they disable loopback connections. buyers cant install demo content on heartinternet. 

Is it resolved if they use `define('ALTERNATE_WP_CRON', true);` on config.php ?

Thanks

**Comment by moldcraft** [comment]
Hello,

We made a fix for demo install when loopback is disabled, the install process works via ajax. https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/7

1. Have you tried to press Install anyway?
2. Have you checked apache error.log ?
