### ISSUE TITLE
Embed and pre activate extension

### ISSUE THREAD

**Issue by smemis** [ThemeFuse/Unyson#1277]
Hi,
1- can i use embed without plugin install?
2- How can i activate only one extension (Page Builder) with code?

Thanks.

**Comment by moldcraft** [comment]
Hello,

1. I don't know
2. PageBuilder can't work alone, it has [required extensions](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/manifest.php#L23).

    To install extensions from code

    ```php
    fw()->extensions->manager->install_extensions(array(
        'page-builder' => array()
    ));
    ```

    To activate extensions from code

    ```php
    fw()->extensions->manager->activate_extensions(array(
        'page-builder' => array()
    ));
    ```
