### ISSUE TITLE
Unique ID/classes for pagebuilder sections?

### ISSUE THREAD

**Issue by chrisuehlein** [ThemeFuse/Unyson#1279]
Hello,

I am developing a theme using Unyson and I need each pagebuilder section to have a unique ID or a class to be able to be styled independently from one another in my CSS. Am I missing something? This seems like a simple/typical feature so I am sorry if I am overlooking something.

Yours,

Chris Uehlein

**Comment by moldcraft** [comment]
Hello,

Use [this solution](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head)
