### ISSUE TITLE
Drag and drop not working after 2.5.0 update

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1280]
Hello,

After Unyson 2.5.0 version update page builder new shortcode drag and drop feature is not working. I can add new shortcodes by click, but that is the only way.

I am the only one? (in console I don't see any errors or warnings)

**Comment by moldcraft** [comment]
Hello,

Make sure the extensions are up-to-date. This is [the fix](https://github.com/ThemeFuse/Unyson-Builder-Extension/compare/v1.1.17...v1.1.18#diff-b77c604a7c9b5270e9758f1fbfd47fbaR118) which is included in the [latest Builder extension release](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/181).

**Comment by pear1** [comment]
Unyson Extensions show:
You have the latest version of Unyson Extensions.

**Comment by moldcraft** [comment]
Updates are cached for 24 hours.

Try to press the "Check Again" button, on Updates page.

**Comment by pear1** [comment]
Thank you. I really didn't know this.

I will need to add this for my theme documentation, so customers know this too.
