### ISSUE TITLE
[feature] Page Builder Templates preview

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1282]
Can we have an optional preview image for builder templates. If template image is available for let say features section , when user hovers over the link for the template a small preview image pop-out.

Imagine you have 3 homepages , or 5 header + hero sections , however you name them the user still reacts better to a preview.

**Comment by Ataurr** [comment]
+1

**Comment by danyj** [comment]
can we maybe get this or get response if it will be added? Thnx!

**Comment by moldcraft** [comment]
Sorry, not soon. You can provide a pull request.

**Comment by danyj** [comment]
thnx
