### ISSUE TITLE
reCaptcha и форма обратной связи

### ISSUE THREAD

**Issue by AleksPayne** [ThemeFuse/Unyson#1283]
Ребят! Очень нравится ваш плагин! Вы супер! Но есть проблемка с формой обратной связи. При нажатии кнопки "Отправить", сообщение отправляется, но страница не перезагружается. Проблема в том, что если человек неправильно введёт какие-либо данные, форма предложит их изменить, но вот reCaptcha потребует полного обновления страницы. Это неудобно для тех, кто написал большое сообщение, а вдруг ошибся в написании email или телефона. И тогда придётся заново всё переписывать. Может можно как-то исправить это? Сделать, например, так, чтобы можно было обновить только reCaptcha, а не всю страницу. Перекопал интернет, так и не нашёл иного решения, кроме как попросить о помощи у вас. Буду очень признателен

**Comment by moldcraft** [comment]
Привет @AleksPayne  

Спасибо за позитивный отзыв!

По умолчанию форма отправляеться с обновлением страницы, если вы чтото ввели не правильно, будет ошибка но все данные останутся в инпутах.
Активировать AJAX Submit можно [так](http://manual.unyson.io/en/latest/helpers/php.html#ajax-submit), и похоже что это у вас делается из темы. Какую тему вы используете?

Но если вы настаеваете на AJAX Submit и хотите чтобы reCaptcha обновлялся в случае ошибки, я пока не предстовлю как это сделать из плагина. Так что пока единственный способ это делать обновление вручную из яваскрипта.

**Comment by AleksPayne** [comment]
Большое спасибо за ответ! Использую тему Everglades, можете что-то посоветовать? Заранее благодарю)))

**Comment by moldcraft** [comment]
Пока мы найдем как исправить эту проблему, предлагаю просто закомментировать `fwForm.initAjaxSubmit(...)` в скрипте темы.

Не могу сказать как скоро мы исправим эту проблему, у нас куча тасков и мы не успеваем их решать.

**Comment by AleksPayne** [comment]
Прошу прощения. Я, конечно, как всегда туплю. После того, как я убрал эту часть скрипта, всё стало обновляться, но теперь перестали вылетать предупреждения, такие как "Неверно введённый адрес" и прочее. Не пойму как так получается...

**Comment by moldcraft** [comment]
Через [этот экшн](http://manual.unyson.io/en/latest/helpers/php.html#customize-errors) выводятся ошибки.

P.S. Спросите автора темы про эту проблему, может он сможет помочь быстрее.

P.P.S. Вы можете писать здесь на английском? Много людей подписаны на этот репозиторий и они получают емайл когда ктото пишет комментарий. Думаю вам не было бы приятно если бы вам приходили оповещения на китайском

**Comment by moldcraft** [comment]
http://stackoverflow.com/questions/3371314/how-to-reload-recaptcha-using-javascript

Try this: Find in theme scripts `fwForm.initAjaxSubmit(` and add at the end of `onErrors`

```js
fwForm.initAjaxSubmit({
    onErrors: function(elements, data){
        // ...

        if (typeof Recaptcha != 'undefined') Recaptcha.reload();
        if (typeof grecaptcha != 'undefined') grecaptcha.reset();
    }
});
```

**Comment by AleksPayne** [comment]
You are best! I warmly thank you for your help! Works great! Cool, thank you!
