### ISSUE TITLE
how to make the From Name or the From Address pull from the contact submission form.

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#1285]
how to make the From Name or the From Address pull from the contact submission form
<ul>
<li><strong>From Name</strong> – when you (the admin) will receive the notification that a new form was submitted from the website you’ll see this name in the From field in your email client</li>
<li><strong>From Address</strong> – when you (the admin) will receive the notification that a new form was submitted from the website you’ll see this email address in the email from field in your email client</li>
</ul>

This makes it impossible to reply to the emails that come in… As it would just go to the email setup in the From Address in the contact form.

In Contact form 7 you can set the From Address to be [email] and that pulls the email from the contact form so that when you reply to a contact form it gets sent back to the persons’s email who submitted that contact form.

**Comment by moldcraft** [comment]
Hello,

At the moment it's not possible. Sorry

**Comment by Ataurr** [comment]
:+1:

**Comment by Ataurr** [comment]
Now one of buyer also asking same question. Every time need to copy the email address from email body to send mail. Its really annoying 

Are you working for this ?

Thanks @moldcraft

**Comment by moldcraft** [comment]
Sorry, I will work on it later.

**Comment by xperter** [comment]
I am little confused. what about Ready level ? Its now ready for next version ?

Thanks very much

**Comment by moldcraft** [comment]
Ready to be In Progress https://waffle.io/ThemeFuse/Unyson

**Comment by moldcraft** [comment]
What if we will implement only the **From Address** feature? And it will be very simple, without additional options/settings: Before email send, the script will get the first email field from form and will use it as **From Address** or I think better **Reply to Address**. What do you think?

**Comment by xperter** [comment]
Form address will be great. If contact form have email option field this email will use automatically.  so no need any extra option.

**Comment by moldcraft** [comment]
To test this feature, download the latest dev version of [Mailer](https://github.com/ThemeFuse/Unyson-Mailer-Extension) and [Forms](https://github.com/ThemeFuse/Unyson-Forms-Extension) extensions.

**Comment by Ataurr** [comment]
Its look like its not  working.
Reply email should be grab from form email field. http://prntscr.com/aa65st

From backend contact form shortcode. Options->  Mailer-> From Address
If i use email address here  "From Address"  show this mail address. so we cant reply directly  to customer email address

if i remove "From Address" We get mail but no email address showing 

What i want: A person when they fill-up the form with his email address http://prntscr.com/aa65st

Reply email should be this email field email address.  not  backend form address. 

You can make something like this {reply_email} shortcode which can be grab from contact form email address. 

Sorry for my worst english

**Comment by moldcraft** [comment]
I tested and it works fine

![](https://static.md/f042198cc83e5985b85eaa66a010ad48.png)

![](https://static.md/37523939d7c368874c702f77d917678b.png)

Make sure your email field is actually of type Email, not Single Line Text

![](https://static.md/0815457445cf0038ecdbb04fa6998790.png)

**Comment by Ataurr** [comment]
Strange.

i have removed forms folder from my extension theme folder to

Its still work same here  
here 2 form field 
![ljeomlm](https://cloud.githubusercontent.com/assets/6223399/13458351/f445ea22-e096-11e5-86f3-78afe9375885.png)

and i am using wp mail 

![mail](https://cloud.githubusercontent.com/assets/6223399/13458367/10d2c28c-e097-11e5-8a56-1d8831a5b98e.png)


when i fillup the form i am receiving email  from "form address" 
![mail2](https://cloud.githubusercontent.com/assets/6223399/13458401/48a7f056-e097-11e5-8617-0ba245e090e9.png)

**Comment by xperter** [comment]
Same here Its not work here.
i  am using latest version of  form extension

**Comment by moldcraft** [comment]
You also need latest version of mailer extension https://github.com/ThemeFuse/Unyson/issues/1285#issuecomment-188211745

**Comment by xperter** [comment]
I have removed all the extension from unyson/framework/extenions folder
and install all the extension again from admin panel. and saw mailer and forms extension also installedI

I have used normal text field and email field and number field but still same. 
in mailer settings  i have just set blank both "form name" and " form address"  and i am getting  no email address in form option " wordpress <>"
![form](https://cloud.githubusercontent.com/assets/11317492/13506568/f053d704-e1a8-11e5-9a61-d105f0fadae9.png)


NOW i have found another issue in number field when we add number in number field i am getting this error "The Number field maximum value must be 0 "

**Comment by moldcraft** [comment]
> and install all the extension again from admin panel

Wrong, you must install Mailer and Forms from github https://github.com/ThemeFuse/Unyson/issues/1285#issuecomment-188211745

**Comment by xperter** [comment]
Ops sorry for silly mistake :(

But now we have found issue on Mailer option Mailer details not showing here. only name without link "wordpress <>"   and mail goes to spam folder
![form](https://cloud.githubusercontent.com/assets/11317492/13507656/c27a1136-e1ad-11e5-900e-8c78732ff243.png)

**Comment by moldcraft** [comment]
I think you are using the `wpmail` method. We add [all the necessary headers](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/7decd93a0f30877ca9085fab58c7a09638153cda/includes/send-methods/class-fw-ext-mailer-send-method-wpmail.php#L45), so the problem can be in your server configuration. Mailer extension doesn't have an option `'send_as_spam' => true`

**Comment by mdzhokanov** [comment]
Is there any progress on current feature request? I am looking for the same functionality?

> 
> **From Name** – when you (the admin) will receive the notification that a new form was submitted from the website you’ll see this name in the From field in your email client
> **From Address** – when you (the admin) will receive the notification that a new form was submitted from the website you’ll see this email address in the email from field in your email client

**Comment by moldcraft** [comment]
@mdzhokanov Please bug [here](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/7decd93a0f30877ca9085fab58c7a09638153cda/includes/send-methods/class-fw-ext-mailer-send-method-wpmail.php#L59) `fw_print($headers);` and [here](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/7decd93a0f30877ca9085fab58c7a09638153cda/includes/send-methods/class-fw-ext-mailer-send-method-smtp.php#L169) `fw_print($mailer);`, you should see that all the necessary headers are set.

**Comment by Moorst** [comment]
This feature isn't working for me- is there anything in particular I need to do to get this working? I've left the from name & address blank, and I do have an email field on the contact form.

![image](https://user-images.githubusercontent.com/6151408/35330379-45963b12-00fb-11e8-9f02-bc1451b35d31.png)

![image](https://user-images.githubusercontent.com/6151408/35330414-51b2cb68-00fb-11e8-913f-992122eeb583.png)

It still comes through from Wordpress with address of wordpress@website.co.uk.

Checked the form & mailer extensions and they're the latest versions.
