### ISSUE TITLE
Сlean or replace the section project

### ISSUE THREAD

**Issue by nekit1992** [ThemeFuse/Unyson#1286]
Guys, hey! How to remove a heading in the URL mysite.com/project/* and make  mysite.com/* or mysite.com/ideas/*?

**Comment by moldcraft** [comment]
Hi,

1. Install "Backup & Demo Content" extension
2. Go to Tools > Backup and Create Content Backup
4. Go to Settings and change site url
5. Go to Tools > Backup and do Restore Content Backup

**Comment by nekit1992** [comment]
Спасибо! Но, к сожалению, я не совсем понял. Мне же не нужно менять урл сайта, всего лишь название рубрики "проект". Она относится к функции создания Портволио. Просто хочу, чтобы в адресе не было слова "проект".

**Comment by nekit1992** [comment]
Thank you! But, unfortunately, I do not quite understand. I do not need to change the URL site, only the name of the column "project". It refers to the function of creating Portvolio. Just want to make it the word "project" is not in the address.
