### ISSUE TITLE
Remove the section "project" in the Portfolio

### ISSUE THREAD

**Issue by nekit1992** [ThemeFuse/Unyson#1287]
Thank you! But, unfortunately, I do not quite understand. I do not need to change the URL site, only the name of the column "project". It refers to the function of creating Portfolio. Just want to make it the word "project" is not in the address.

**Comment by nekit1992** [comment]
I do not know how best to explain. Any such references as "/ portfolio / category"
and "/ project / project title" How to remove these most portfolio and project, and it turns into a URL as a category in the portfolio category. All anything, just want to stay in the portfolio of its services and to make at least "/ service / category" "/ services / project name." How this can be done. Well, I will be very

**Comment by moldcraft** [comment]
https://www.google.com/#q=wordpress+change+permalink+structure

**Comment by nekit1992** [comment]
Thank you! However, no method has not helped. I tried to work with plug-ins and htaccess, in the records of all the changes, but it is in the portfolio of any one way did not work. The trouble is, I do not know how to be

**Comment by moldcraft** [comment]
Sorry, I also don't know how to solve this, I never did something similar before.

Maybe someone who's following this thread will be able to give a tip.

**Comment by danyj** [comment]
https://wordpress.org/support/topic/remove-portfolio-url?replies=17
https://wordpress.org/plugins/custom-post-type-permalinks/

**Comment by nekit1992** [comment]
Guys, is closer to solving the problem. But still it does not provide a plugin to remove this "project"!
![screenshot_1](https://cloud.githubusercontent.com/assets/17215241/13030773/559ef152-d2c7-11e5-887d-082645ced4dd.png)

**Comment by moldcraft** [comment]
This issue is not related to Unyson.

[Portfolio extension](https://github.com/ThemeFuse/Unyson-Portfolio-Extension) just registers a post type.
