### ISSUE TITLE
Image picker issue

### ISSUE THREAD

**Issue by joanhard** [ThemeFuse/Unyson#1288]
Hi, I have add 3 images picker but why display 2 image picker on theme options?

![2016-02-13_19-17-43](https://cloud.githubusercontent.com/assets/2072241/13027570/ca41c566-d286-11e5-9a63-1db67845c74a.png)

**Comment by moldcraft** [comment]
Works fine for me

```php

$options = array(
	'test' => array(
		'type' => 'image-picker',
		'choices' => array(
			't1' => 'https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2015-10-28/13433989457_8558ccb72a07090b3a35_96.jpg',
			't2' => 'http://static.binaryfruit.com/images/drivedx/overview/IconTest.png',
			't3' => 'https://devimages.apple.com.edgekey.net/assets/elements/icons/testflight/testflight-96x96.png',
		),
	),
);
```

![](https://static.md/08c1ff857686a7a3d276f5e215ca55d0.png)

**Comment by joanhard** [comment]
hi, sorry.. I miss something... yah it's worked

thank you
