### ISSUE TITLE
Demo Install being slow

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#1289]
Hi guys. Trying to install the demo on a theme we have created with Unyson, usually takes around 7 minutes on Shared Hosting, and more than 10 on localhost.

Do you have an idea why it takes so long, or is this something normal?

Thanks.

**Comment by moldcraft** [comment]
Hello,

1. Which step is the slowest?
2. The size in MB of you demo install?

**Comment by darwinteam** [comment]
Hi. Database restore takes most of time I guess.
Demo install is around 81MB.

Thanks.

**Comment by moldcraft** [comment]
Make sure the demo doesn't contain post revisions.

----

Yes, the install usually takes a few minutes.

**Comment by darwinteam** [comment]
good idea, thanks a lot
