### ISSUE TITLE
Add video from media" and "create/edit gallery from media" 

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson#129]
1- "Add video from media" and "create/edit gallery from media" buttons like "add image" and "add multi images" buttons.

**Comment by rockalife** [comment]
Video
--------

Can you specify how do you imagine the video option type, I understand that it should be similar to the upload option types, but it is not clear what data should the option type save, is it the url to the video file ?
What should you do on the frontend with this data, do you intend to use some kind of custom video player and feed it the url from the option type, or do you want to use the default wordpress player that it uses for the `[video]` shortcode.

*Note: Here is how wordpress generates it's video shortcode* `[video width="214" height="360" webm="http://dev/unyson/wp-content/uploads/2015/01/test.webm"][/video]`

Gallery
---------

Not sure what do you mean by:
> create/edit gallery from media" buttons like "add image" and "add multi images" buttons

Why would yo need to create or edit galleries from an option type ?

**Comment by MoBadawy** [comment]
The Video and Gallery options will be use in the page builder and shortCodes.

For Video it will save the link or if you can make an option for developer to choose what should get link or ID of the video it will be good :).

For Gallery I told you it will use for shortCodes so it should save the IDs of images.

**Comment by moldcraft** [comment]
The upload and multi-upload option-types has a parameter `'only_images' => false` then you can upload any file http://manual.unyson.io/en/latest/options/built-in-option-types.html#upload
Isn't that enough, or you want a parameter something like `'allowed_types' => array('webm', 'mp4')` ?

*Sorry, in case I understood you wrong.*

**Comment by MoBadawy** [comment]
'allowed_types' => array('webm', 'mp4'),
    'multiple' => true   //set false if you want a single file
This is will be great

**Comment by moldcraft** [comment]
`'multiple' => true` sure will not be. This will make the option value confusing, you will not know for sure if the value is an array of values or one value, you will have to look in options array to see if you enabled the `multiple` or not. That's why we made `select` and `select-multiple`, `upload` and `multi-upload`.

**Comment by MoBadawy** [comment]
oh sorry, I did't know there was Multi-Upload. :)
ok for both options  `allowed_types` parameter  will be good.
