### ISSUE TITLE
Extension provides shortcode for Page Builder.

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#1290]
Is there any way that I write an Unyson Extension which is able to provide some shortcodes for Page Builder?

**Comment by duongancol** [comment]
You could create a folder name 'shortcodes' inside extension folder, then put your shortcode there. For example here:
``
Extension A/ 
---Class_Extension_A.php
---shortcodes/
------shortcode A/
----------config.php

**Comment by Shahab2905** [comment]
[This Documentation](http://manual.unyson.io/en/latest/extension/builder/index.html#content) should help.
