### ISSUE TITLE
Container types not working for category options page.

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1295]
On category pages, I can't group options in container types. Is that a bug?

**Comment by danyj** [comment]
No it is default restriction 
http://manual.unyson.io/en/latest/options/introduction.html#restrictions

**Comment by ivandotv** [comment]
Oh, I overlooked that part of documentation.

**Comment by danyj** [comment]
@ivandotv  kad zavrsimo  teme idemo na kafu :)

**Comment by ivandotv** [comment]
@danyj deal :)

@moldcraft 
Why that restriction ?

**Comment by moldcraft** [comment]
> Why that restriction ?

![](https://static.md/6ecf19111a442ada535ef41fa5868c81.png)

**Comment by ivandotv** [comment]
So it's strictly design decision?

**Comment by moldcraft** [comment]
I don't remember exactly, but I think yes.

[This code](https://github.com/ThemeFuse/Unyson/blob/v2.5.0/framework/core/components/backend.php#L734) is responsible for displaying options there. Try to play with it, if groups, boxes, tabs, in your opinion will look ok in term edit page, then I will ask our designer his opinion. If he will say yes, I will remove the restriction.

**Comment by ivandotv** [comment]
:+1:

**Comment by danyj** [comment]
@moldcraft  nah man , I dont believe you did it because of CSS , 
I originally did this but later decided those should be somewhere else
http://prntscr.com/a3lt6e

few lines of CSS  could have given us this feature and there are tons of options that in my opinion simply do not belong in theme settings but rather in category itself.

Please remove that restriction and let us have tabs in tax settings
A simple div wrapper with white bg would fit perfectly there . 

@ivandotv  da trenutno NS

**Comment by moldcraft** [comment]
Please give some screenshots how groups, boxes, tabs and other containers should look like. I need to ask our designer his opinion.

**Comment by danyj** [comment]
Similar to this 

![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/13226929/546fa7ee-d994-11e5-9f3f-8d28952f8327.jpg)

rough  output

![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/13226943/6f2b5e5c-d994-11e5-8deb-df77ec8142c4.jpg)

**Comment by ivandotv** [comment]
In my opinion, in the back-end, functionality should always have precedence over design. 
Limiting the functionality of the framework because something doesn't look good is wrong.
Also, you should just enable this and the designer should find the solution for the design.
That's why he is the designer :)

**Comment by moldcraft** [comment]
We are doing themes for users, not for developers, so the design is important.

**Comment by moldcraft** [comment]
Our designer is busy and doesn't have time to inspect this issues, so I just allowed containers on term edit page. It is up to you to make them look good.

**Comment by ivandotv** [comment]
:+1:
