### ISSUE TITLE
Determine if column is auto generated

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1298]
Hello, 

How can I determine if the column is auto generated for shortcode (in the page builder)?
I found this tread https://github.com/ThemeFuse/Unyson/issues/118, but I don't see any auto generated keys for columns (only sections have auto generated keys).

**Comment by andronic90** [comment]
You can put this code on section/views/view.php:

var_dump($atts['auto_generated']);

When is auto generated the $atts['auto_generated'] == '1'

**Comment by pear1** [comment]
It doesn't work for columns.

**Comment by moldcraft** [comment]
Hello,

[This code](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.6.6/includes/page-builder/includes/items-corrector/class-page-builder-items-corrector.php) is responsible for adding the `auto_generated` attr. Please inspect it, find a solution and provide a pull request.
