### ISSUE TITLE
How to override/extend breadcrumbs options?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1299]
I moved breadcrumbs to my extend folder, views and everything works ok but I am not able to override/extend default options.

**Comment by danyj** [comment]
@moldcraft  can I get a hint for this please. Thnx!

**Comment by danyj** [comment]
thnx for the filter but this is again another filter and filter filter , which is completely different from for example shortcode options. Instead of keeping the same  structure for all extensions , every time we find an issue we get a filter. Don't think I am not grateful for your extended  enhancements but this makes no sense at all . 

If I see a file with options  https://github.com/ThemeFuse/Unyson-Breadcrumbs-Extension/blob/master/settings-options.php

I should be able to extend it the same way I extend the view for the extension and not add options trough   hooks.php 


We did same thing with mega menu yesterday and is just not the way I think extensions options should be added. 

Please try to find a way to make it work like shortcodes options if you can. 

Yes I can use this filter to do file import but I think you understand what I am saying here.

**Comment by danyj** [comment]
This is what I mean 


	/**
	 * Add menu options
	 */
	function _thz_filter_breadcrumbs_options() {
		
		$variables 	= fw_get_variables_from_file(thz_theme_dir().'/inc/framework/extensions/breadcrumbs/options.php', array('options' => array()));
		
		return $variables['options'];
	}
	add_filter( 'fw:ext:breadcrumbs:settings-options:after', '_thz_filter_breadcrumbs_options' );



something like that should be in by default for all extensions

**Comment by moldcraft** [comment]
We don't know what to do with this case: The developer overwrites the settings options in theme, in the future we add more (required) options in settings options and the extension will use them in core functionality, but that will throw errors because the developer doesn't know that we added more options and not updated the overwritten settings options from theme.

**Comment by danyj** [comment]
if you have extension with default options than those defaults should be separated and have a filter , but all extensions in general should have a same place for additional options.
