### ISSUE TITLE
Google Maps on Background

### ISSUE THREAD

**Issue by aldodager** [ThemeFuse/Unyson#1300]
Hi, great framework!

Bought a theme at ThemeForest (UNICUM - http://themeforest.net/item/unicum-one-page-creative-wordpress-theme/13132355) that comes with Unyson. I'm looking forward of a way of adding Google Maps as a section background.

Any idea on how to do that?

Thank you!

Aldo

**Comment by danyj** [comment]
Since this is theme specific you are better off posting on their support channel

http://themeforest.net/item/unicum-one-page-creative-wordpress-theme/13132355/support

**Comment by aldodager** [comment]
Hi Dan, thank you for replying. Already contacted them, their response was to hire a freelancer. I suppose the freelancer will end up here.

I'm doing a small research, so I can understand what and how the solution should be done.
