### ISSUE TITLE
Unyson is not work

### ISSUE THREAD

**Issue by ReinLeib** [ThemeFuse/Unyson#1301]
Hello! 
I have a problem. I upgraded Unyson plugin but it does not work now.
And it does not work Page Builder, Analytics and SEO.
I deactivated those three now, and currently has a half-page. Before the error page

My webside:http://www.reinleibphotography.eu/

**Comment by danyj** [comment]
Did you check if extensions are active? 
Go in Unyson and make sure all extensions that your theme requires are active

![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/13104403/3ac192a2-d55d-11e5-9fb2-03c1b2632ef8.jpg)

than go in builder settings
![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/13104419/4c00a706-d55d-11e5-90ca-57570065ad45.jpg)

and make sure that these are checked

![screenshot_8](https://cloud.githubusercontent.com/assets/2340172/13104446/767cf980-d55d-11e5-8927-84d41ff7066e.jpg)

**Comment by ReinLeib** [comment]
I turned those three now active again. And the check. But now there is a page error:
Fatal error: Call to undefined function menu_page_url() in /home/np37789/domains/reinleibphotography.eu/public_html/wp-content/themes/exposure-parent/framework-customizations/theme/options/posts/page.php on line 3

**Comment by danyj** [comment]
Did you post in theme customer support ? 
http://themeforest.net/item/exposure-photography-wordpress-theme/10562504/support

**Comment by ReinLeib** [comment]
Yes, I can

**Comment by ReinLeib** [comment]
I now work part of the website. But do not work
Visual Page Editor

**Comment by ReinLeib** [comment]
How do I send a picture here? I would get a two piece

**Comment by andronic90** [comment]
Have you the latest version of Exposure? Please update to the latest theme version

**Comment by andronic90** [comment]
Hello, you try to update theme to the latest version? If you have this error after theme update please contact the support team : http://support.themefuse.com/hc/en-us/requests/new
