### ISSUE TITLE
Output date time in Event extension

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1302]
I found the new filter is added in new version of Event extension, but I still couldn't change the output of date time.

when I use above filter, I couldn't change the output of datetime picker of Event extension.
I use this code

```php
add_filter('fw_option_type_event_datetime_pickers', function($data){
	$data['from']['format'] = 'F j, Y';
	$data['to']['format'] = 'F j, Y';

	return $data;
});
```

But when I choosed date time, it showed this error: http://prntscr.com/a3wc40

**Comment by danyj** [comment]
@moldcraft   this is still not working , no way to change the events date format

**Comment by danyj** [comment]
I checked this filter and adjusted the add_filter but no overrdie 
https://github.com/ThemeFuse/Unyson-Events-Extension/blob/a36b24112a622a7bffcf6d8a7a1d5e4e67c28c1c/includes/option-types/event/class-fw-option-type-event.php#L69

```
add_filter('fw_option_type_event_datetime_pickers', function($data){
    $data['from']['extra-formats'] = array('F j, Y');
    $data['to']['extra-formats'] = array('F j, Y');

    return $data;
});
```

**Comment by danyj** [comment]
@moldcraft  this seems like datetime-range option type bug , 

formats are hardcoded 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/datetime-range/class-fw-option-type-datetime-range.php#L77


and in events your extra-formats ,  are not used anywhere

https://github.com/ThemeFuse/Unyson-Events-Extension/search?utf8=%E2%9C%93&q=extra-formats

**Comment by danyj** [comment]
who ever coded the event extension mixed up datetime-picker and datetime-range options type array, thus the bug, 


we use here datetime-range 
https://github.com/ThemeFuse/Unyson-Events-Extension/blob/a36b24112a622a7bffcf6d8a7a1d5e4e67c28c1c/includes/option-types/event/class-fw-option-type-event.php#L66

but array is from datetime-picker 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/datetime-picker/class-fw-option-type-datetime-picker.php#L27-L36

datetime-range does not have extra-formats index , and date formats are hardcoded on output 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/datetime-range/class-fw-option-type-datetime-range.php#L24-L46

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1722
