### ISSUE TITLE
Custom shortcode tag isn't as a folder name

### ISSUE THREAD

**Issue by AceoK** [ThemeFuse/Unyson#1303]
Hi,

fw_print($tag) of my shortcode outputs 'section'
fw_print($content) outputs [row][column width="1_1" _made_with_builder="true"][colset count="" _made_with_builder="true"][/colset][/column][/row]

why tag is section? my folder name is colset.
old issue [#1260](https://github.com/ThemeFuse/Unyson/issues/1260)

**Comment by danyj** [comment]
what is it that you are trying to print?

do

    fw_print( $atts ) 

for the shortcode options

**Comment by AceoK** [comment]
Some info about problem in issue that I wrote in first comment. 

I copied section shortcode and changed all section to colset, but it doesn't work. I trying to debug it but found that $content is strange a little and tag is not same as folder name

**Comment by danyj** [comment]
see this please
http://manual.unyson.io/en/latest/extension/shortcodes/index.html#creating-a-simple-shortcode

**Comment by AceoK** [comment]
I know that You have documentation, but please turn on your brain and think, is it bug or not. Try to reproduce it

**Comment by danyj** [comment]
no is not a bug and you might want to turn off you loud mouth when someone is trying to hep you and be grateful for any response. I am not framework developer but a user so take it down a notch if you want anyone from this community to talk to you.

**Comment by AceoK** [comment]
Hmm, then sorry for that. But why do You trying to help if You don't know how?

**Comment by danyj** [comment]
if you are asking me why am I stopping what I do at this very moment to help you, the answer is community support.  You are right I dont know what you are trying to do because it simply makes no sense why you are bugging with a tag or content vars . Good luck!

**Comment by AceoK** [comment]
section is not a simple shortcode, but it doing almost all what I want. I'm trying to copy it and change for my purposes but on first step it's not working
