### ISSUE TITLE
WordPress post preview is not working correctly

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1304]
Steps to reproduce, please note that Preview works just fine when you're not switching to *Page Builder*:

1. Create new page
2. Switch to *Page Builder* -- if at this step you'll insert some content into WP editor everything will work just fine
3. Insert any random shortcode
4. Click on Preview -- everything is well
5. Publish your page
6. Click on Preview -- whole builder section disappears from Frontend, you're getting just header and footer

Sometimes, you'll not be able to reproduce this bug and that's the most weird part of this bug.

**Comment by Creative-Dreams** [comment]
If someone have the same problem, just deactivate + remove -> download + activate the Page Builder extension, this fixed the bug for me...

**Comment by ntofigh** [comment]
I am having the same problem-- page content / builder section does not show, only header and footer. Pre-loaded pages (such as demo content) work fine, until it gets edited. Then the content disappears (though everything looks intact on the page builder itself). Any solutions?

**Comment by ntofigh** [comment]
Tried deactivating/removing/etc, no change.

**Comment by moldcraft** [comment]
Please get latest [PageBuilder](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension) extension and test if post preview works.

**Comment by moldcraft** [comment]
The problem: When you click on the Preview button, WP checks known post fileds like post_content and if there are no changes it [will not create](https://github.com/WordPress/WordPress/blob/4.5/wp-admin/includes/post.php#L1680) an auto-save/preview and will display the saved/old post in preview.

I made a [trick in javascript](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/e709f8278160de3bc92f485a60fd34ac274e69d0#diff-6c1b2f67a1a1bf6c0ed0295d9dd98cbc):

1. On Preview button click I change post content textarea value (fake value, just to be different)
2. Data is sent to PHP and a preview request is initiated
3. After you release the mouse I recover the original post content textarea value, to prevend double revisions to be created on post save/update

**Comment by ntofigh** [comment]
Thank you moldcraft. On my end however it isn't just that changes won't show-- no page content is visible on live site or page preview. Just clicking update to a page that has page builder content causes the content to disappear. This isn't a change that just started happening haven't been able to get changes made on builder working at all since installing unyson.

**Comment by ntofigh** [comment]
I have the latest extension. Creating a new page and adding content from scratch also does not show, so it isn't just updates.

**Comment by moldcraft** [comment]
@ntofigh Which theme are you using?

**Comment by ntofigh** [comment]
The core, with the wellness Demo content

**Comment by moldcraft** [comment]
@ntofigh Please report this problem to theme author, on theme help desk.

**Comment by moldcraft** [comment]
@andreiglingeanu Please test this and tell if it works.

**Comment by ntofigh** [comment]
themfuse is the theme author, so then you are saying unyson is not the
issue?

**Comment by moldcraft** [comment]
The Core support team will take a better care of your theme related issue.

**Comment by danyj** [comment]
I am not sure if thus is  theme related , I also see this issue on my end , 
what I noticed is that  if you dont save the page preview works perfect , once it is saved and you make changes , you can forget about the preview

**Comment by andreiglingeanu** [comment]
@danyj It's not always true. Sometimes it doesn't work even before page save.

**Comment by danyj** [comment]
@andreiglingeanu  the one thing that we all have in common is that it does not work well
honestly I cant nail it either , Unyson or WP core preview something is definitely buggy.

**Comment by andreiglingeanu** [comment]
@danyj Yep, you're right.
