### ISSUE TITLE
[Feature request] Shortcode preview in pagebuilder

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1305]
I've been working with Unyson for a while now. And as the pages we build are getting more and more complex, there's one feature really missing. And that's a (small) preview of the content in a shortcode/block used in the pagebuilder. This would make working with the shortcodes/blocks in relation to filling a website with content a lot easier.

Is there any chance this is a (soon to be released) future feature?

If not, is there any suggestion to add this functionality ourselves?

**Comment by danyj** [comment]
:100:   I think  @andreiglingeanu   was working on something like this but we never got to see it.

**Comment by danyj** [comment]
Here it is https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/40
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/39

**Comment by noesteijver** [comment]
Actually, I meant something like this:

![idea-2](https://cloud.githubusercontent.com/assets/10668469/13123120/f29377e4-d5ba-11e5-886c-7fb91d40ce80.jpg)
![idea-1](https://cloud.githubusercontent.com/assets/10668469/13123121/f29490b6-d5ba-11e5-9d8d-051060199b91.jpg)

**Comment by danyj** [comment]
ah , you mean frontend visual editor, that is  another beast.

**Comment by noesteijver** [comment]
Well, if there's a reference to the content of a block (not just the title of the block type) on the back end, that would be fine! Then there's no need for a frontend visual editor, as that is indeed another beast..

**Comment by danyj** [comment]
or do you mean these here http://prntscr.com/a4l01j, if those , you can output them with title_template 
https://github.com/ThemeFuse/Unyson/issues/759

**Comment by noesteijver** [comment]
@danyj That's what I'm looking for! Is there any change this will be a core feature in the near future?

**Comment by danyj** [comment]
is already in core , you need to add  title_template to it to your shortcode config.php


![ssdsds](https://cloud.githubusercontent.com/assets/2340172/13123736/f14119a2-d5bd-11e5-83f0-f50cd5441e05.jpg)

https://github.com/ThemeFuse/Unyson/issues/759#issuecomment-127020295
