### ISSUE TITLE
After update plugin All shortcode icon disappair

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#1308]
When I update the plugin Unyson, the icons which there are in layout elements and media elements dissapear.

http://puu.sh/neAAf/15e895421c.png

As you can see in the screenshot which I attach here, when I update the plugin Unyson, the icons which should be in the layout elements, media elements and content elements dissapear.

**Comment by xperter** [comment]
I’ve discovered that this issue with a plugin wordfence security which is making dissapear the icons. Is there any solution or I have to desactivate it?

**Comment by moldcraft** [comment]
Hi,

Thank you for reporting.

You can open the browser console and inspect the javascript error. If the problem is in another plugin, please close this issue and open a ticket on that plugin bug tracker.

We will inspect this issue later, sorry. We can't ensure compatibility with all plugins.
