### ISSUE TITLE
Image URL customizer preview

### ISSUE THREAD

**Issue by spaxter** [ThemeFuse/Unyson#1309]
i'm working on to get the image url from upload options in customizer preview. has anyone a solution? the only thing i get is the image id...

**Comment by ivandotv** [comment]
@spaxter Why do need a `url` instead of `id` ?

**Comment by moldcraft** [comment]
I named the input [`_fake[url]`](https://github.com/ThemeFuse/Unyson/commit/65429b798a55fae2fd01332accf936400bc42680#diff-be73fbd3e934c4c7100fdf7adef06e0cR40) to not overwrite [the main input name](https://github.com/ThemeFuse/Unyson/blob/65429b798a55fae2fd01332accf936400bc42680/framework/includes/option-types/upload/views/images-only.php#L10). If both are named the same, the last one will overwrite others on form submit.
