### ISSUE TITLE
Text box turning from a white background to black background after editing a page

### ISSUE THREAD

**Issue by FredSlabine** [ThemeFuse/Unyson#1311]
Hello, My website www.thoseoldiesbutgoodies.net is using the plugin by Unyson to build the pages, I just editing a text block  and the white background turned to back and there are other text blocks on the page that also turned, how do I get it back to white? Thank you, on the homepage you can see the background under the video.

**Comment by moldcraft** [comment]
Hi,

The problem comes from theme

![](https://static.md/44c44686e2fc4cb6a3e64090f70dbdee.png)

Check the view of the column or text_block shortcode.
