### ISSUE TITLE
VPB pages reverting to Default Editor in backend after update 2.5.0 and WP4.4.2

### ISSUE THREAD

**Issue by photoncreative** [ThemeFuse/Unyson#1312]
Hi,

I recently updated WP to 4.4.2 and Unyson to 2.5.0 as well as a few other plugins.

When I go to edit a page in Wordpress now which was built using the Visual Page Builder, the page is loading all as code and it seems like it's reverted back to the default editor, with all the code just in the text editor:

![screenshot 2016-02-23 16 16 56](https://cloud.githubusercontent.com/assets/17422773/13242462/ec9ebca8-da48-11e5-822e-cf44579a5a40.png)

If I click the 'Visual Page Builder' button, all the code gets pulled into just one text box:

![screenshot 2016-02-23 16 18 24](https://cloud.githubusercontent.com/assets/17422773/13242474/16c1f0cc-da49-11e5-8058-35d6950161c0.png)

Does any one has any ideas on how to "restore" the pages so it knows it should load the Visual Page Builder?

Many thanks in advance.

Cheers,
Luke

**Comment by moldcraft** [comment]
Hello

First: **Create a backup of your content**, to not break it more while you are trying to restore it.

1. Have you ever used github dev version of extensions, or you install extensions only from the Unyson extensions page?
2. Have you tried to restore the page from revisions?

**Comment by Alex-Ascet** [comment]
Same issue for me. Only on one specific page. This page has not been edited since 27 days.
Did not tried to restore revisions.
Everything was up to date. Thank you

**Comment by photoncreative** [comment]
Hi @moldcraft, to answer your questions:

1. I'm not sure. My developer who has gone awol set everything up for me. Is there a way I can check?
2. Restoring loads the previous revision, but still as code in the default editor, not the VPB editor. Same result whether I restore as default editor, or if I click VPB and then restore.
3. Previous version was was 2.4.16

Thanks

**Comment by photoncreative** [comment]
Hi, just wondering if anyone has any ideas on this. Thanks.

**Comment by moldcraft** [comment]
Sorry,

Sometimes users report about this problem but we don't know how to reproduce and why it happens.
