### ISSUE TITLE
Unyson / Page builder extension

### ISSUE THREAD

**Issue by eightnight** [ThemeFuse/Unyson#1313]
Configuration : WP 4.4.2 | Unyson 2.5.0 | Woffice 1.7.3

Hi,
I'm facing a problem with page builder extension. Here's the description of the workflow.

1. Add a new project
2. Switch editor to Visual page builder
3. Create element in Project with page builder (title / texte / table etc.)
4. Previewing Project (all ok)
5. Saving Project (sending to dbase)
6. Project is refreshing
7. Project is saved
8. Project's content missing in page builder editor

Is there something wrong with page builder latest version ? (problem appear only a few days ago)
Thank you for your help

nb: Woffice team is aware of this issu.

**Comment by moldcraft** [comment]
@2Fwebd can you reproduce this?

**Comment by eightnight** [comment]
Yes,
It happens each time I save a project, even if I use the project revision.

**Comment by moldcraft** [comment]
I can't reproduce the problem https://vid.me/4rvK

**Comment by moldcraft** [comment]
Please try the latest PageBuilder extension https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/185

**Comment by 2Fwebd** [comment]
Hi there ! 

Okay I've just tested, I can't reproduce it for now but I can narrow it. 

In fact, I've just seen your update on the Page Builder extension. And we have a few hooks on the "save_post" method. 

In some of these hooks, we update the post meta and the "page_builder" key. I'm sure it comes from here and the update. 

I can't reproduce it for now, but I'll do that when I'm back (3-4 hours). We'll figure it out. But I'm pretty sure @moldcraft it's an issue with our code and the latest update. But don't waste any time on it, we'll find out :)

@eightnight it's only on projects right ? Working fine with wiki, page, blog articles ? 

Keep me updated here or on the ticket.

**Comment by moldcraft** [comment]
@2Fwebd Thank you

Feel free to reopen the issue if the problem is on our side.

**Comment by eightnight** [comment]
Works fin with page / articles. 
I have restart a brand new install from scratch and it happens again when editing/creating a project.

Can't figure out what's going on. I've notice that each time this problem happens, it's no longer possible to switch back to the classic editor (both button visual editor / classic editor are missing in the back office). This two events a related.

![capture-d ecran-2016-03-07-a-16 30 21](https://cloud.githubusercontent.com/assets/13215888/13573883/0f50f5c0-e482-11e5-8780-8b03d95c2578.jpg)

**Comment by eightnight** [comment]
And of course, I didn't figured out how to get this button back in place :)

**Comment by moldcraft** [comment]
> both button visual editor / classic editor are missing

Do you have any errors in browser console?

**Comment by eightnight** [comment]
No a single clue in browser console nor when wp_debug mod is enable.

**Comment by moldcraft** [comment]
Disable all plugins and leave only Unyson active and try to reproduce the problem.

**Comment by moldcraft** [comment]
> when editing/creating a project

I don't have Projects in my menu. Can you give me access to your site so I can test/debug it?

**Comment by moldcraft** [comment]
Also when it will happen again, view page source, maybe there is a fatal error in html.

**Comment by duongancol** [comment]
Hi @moldcraft My client got the same problem. The edit pages was blank. You could see here: http://prntscr.com/adetwr
No console error and I did deactivated other plugins but still couldn't get the edit page back. Need your help please!

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1313#issuecomment-194753551
> view page source, maybe there is a fatal error in html.

Also check error.log

**Comment by duongancol** [comment]
Hi @moldcraft . I checked error.log and sent you an email

**Comment by duongancol** [comment]
Did you check it? it's very urgent.

**Comment by moldcraft** [comment]
@duongancol I told you to view page source (Ctrl+U). https://github.com/ThemeFuse/Unyson/issues/1313#issuecomment-194753551 | https://github.com/ThemeFuse/Unyson/issues/1313#issuecomment-194758121

![](https://static.md/d7a5f1c056fb6587f6498ed2cb361565.png)

![](https://static.md/aeabe378adb41554fdf5c6385f0e27d8.png)

How I fixed it:

1. I added this in `wp-config.php`

    ```php
    define('WP_POST_REVISIONS', 3);
    ```

2. Restored the page from previous revision and it was broken: default editor with `[section ...` code.
3. At this point 300+ revisions were deteled and only 3 left.
4. I restored again from previous (working) revision (created with latest PageBuilder extension, it contained `<!-- {"hash":...`). Now the builder is working
5. I changed in `wp-config.php`

    ```php
    define('WP_POST_REVISIONS', 100);
    ```

    Revisions are useful. Also with latest PageBuilder they should not break anymore because in post content is stored only a small text (the actual builder content is in post meta).

**Comment by duongancol** [comment]
Sorry! Thank for your helps! :+1:  for post meta

**Comment by duongancol** [comment]
Sorry for bother you again, but in the home edit page, All shortcodes is in Text blog shortcode again http://prntscr.com/adtwxe
It's very nightmare, I didn't do anything

**Comment by moldcraft** [comment]
I logged and and restored from a working revision and it's fine now, after page Update everything still works. Please don't restore from older (broken) revisions.

**Comment by duongancol** [comment]
Sure, Thanks!
