### ISSUE TITLE
WPML issue

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#1314]
My problem is that when I create for example a new page in the Dutch language based on the English version of that page, a page is created that shows all the shortcode in the Default Editor. 

When I click the Visual Page Builder a TEXT BLOCK is shown instead of the right BLOCKS as can be found on the English version of that page. So the page in Dutch is not correctly transferred back from shortcode to BLOCKS - everything is put in 1 Text shortcode.

English version: https://www.evernote.com/l/AATDO2cZmPBBG4zT4plNslBd9g7-nxEUars

German version – source code: https://www.evernote.com/l/AARxAEQyMHBBkIJsQ1764HLh2LLlRZpujNM

German version – Visual Page Builder: https://www.evernote.com/l/AARyFjOQa7BLv7vs1AKClOj4zBA_M9SiniE

Any ideas?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1131
