### ISSUE TITLE
Unyson Button CSS included in the footer inside the body tag

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#1316]
Hi team,

I am using the latest version of unyson and WP. I was trying to do an html validation for my new theme and this html error popup ups,

<blockquote>Error: Element link is missing required attribute property.
From line 432, column 1; to line 432, column 232
site -->↩↩<link rel='stylesheet' id='fw-shortcode-button-css'  href='http://www.outcrafter.com/olamwp4/wp-cont…ensions/shortcodes/shortcodes/button/static/css/styles.css?ver=4.4.2' type='text/css' media='all' />↩</blockquote>

It happens as the button styles (css file)are loaded inside body tag in footer section.
Have a look at the screenshot

http://imgur.com/s4ccfq3

Live Url (where issue is happening) :http://www.outcrafter.com/olamwp4/

Please help me fixing this issue

**Comment by linjo** [comment]
Hi team,

Any update on  this? Please have a look at this

**Comment by moldcraft** [comment]
Hello,

I tried with Scratch theme and [it is included in head](https://static.md/3f41f48d15b45ea943208e181da27e18.png)

**Comment by moldcraft** [comment]
Same with Twenty Fifteen theme.

**Comment by linjo** [comment]
Please have a look at this url. I've enabled the twenty fifteen theme.

http://www.outcrafter.com/olamwp4/

On 29 February 2016 at 15:11, moldcraft <notifications@github.com> wrote:

> Same with Twenty Fifteen theme.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190124682>.
>



-- 
Linjo Joson

**Comment by moldcraft** [comment]
Please show the contents of 

```
/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/button/static.php
```

**Comment by linjo** [comment]
<?php if (!defined('FW')) die('Forbidden');

$shortcodes_extension = fw_ext('shortcodes');
wp_enqueue_style(
'fw-shortcode-button-css',
$shortcodes_extension->get_declared_URI('/shortcodes/button/static/css/styles.css')
);


On 29 February 2016 at 15:29, moldcraft <notifications@github.com> wrote:

> Please show the contents of
>
> /wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/button/static.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190133801>.
>



-- 
Linjo Joson

**Comment by linjo** [comment]
Also, Im not using static.php in
my framework-customizations/extensions/shortcodes/shortcodes/button/,

I even tried removing the button folder from framework-customizations

That too didnt help

On 29 February 2016 at 15:33, Linjo Joson <linjo13@gmail.com> wrote:

> <?php if (!defined('FW')) die('Forbidden');
>
> $shortcodes_extension = fw_ext('shortcodes');
> wp_enqueue_style(
> 'fw-shortcode-button-css',
>
> $shortcodes_extension->get_declared_URI('/shortcodes/button/static/css/styles.css')
> );
>
>
> On 29 February 2016 at 15:29, moldcraft <notifications@github.com> wrote:
>
>> Please show the contents of
>>
>> /wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/button/static.php
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190133801>.
>>
>
>
>
> --
> Linjo Joson
>



-- 
Linjo Joson

**Comment by moldcraft** [comment]
You have a different version of shortcodes extension. Your handle differs from [the one in latest version](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.9/shortcodes/button/static.php#L5). Please reinstall the extensions or make sure they are up-to-date.

**Comment by linjo** [comment]
Sorry, I mad that change manually to see if its working. Im having the same
updated version

On 29 February 2016 at 15:36, moldcraft <notifications@github.com> wrote:

> You have a different version of shortcodes extension. Your handle differs
> from the one in latest version
> <https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.9/shortcodes/button/static.php#L5>.
> Please reinstall the extensions or make sure they are up-to-date.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190136989>.
>



-- 
Linjo Joson

**Comment by linjo** [comment]
*made

On 29 February 2016 at 15:39, Linjo Joson <linjo13@gmail.com> wrote:

> Sorry, I mad that change manually to see if its working. Im having the
> same updated version
>
> On 29 February 2016 at 15:36, moldcraft <notifications@github.com> wrote:
>
>> You have a different version of shortcodes extension. Your handle differs
>> from the one in latest version
>> <https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.9/shortcodes/button/static.php#L5>.
>> Please reinstall the extensions or make sure they are up-to-date.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190136989>.
>>
>
>
>
> --
> Linjo Joson
>



-- 
Linjo Joson

**Comment by moldcraft** [comment]
Send the admin/ftp details to `moldcraft[at]email.com` and I will take a look in a few hours.

**Comment by linjo** [comment]
moldcraft[at]email.com  ?

On 29 February 2016 at 15:44, moldcraft <notifications@github.com> wrote:

> Send the admin/ftp details to moldcraft[at]email.com and I will take a
> look in a few hours.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190140076>.
>



-- 
Linjo Joson

**Comment by linjo** [comment]
Hi,

I just found that this happens when you add a table row as a button row.
Looking more into it

On 29 February 2016 at 15:58, Linjo Joson <linjo13@gmail.com> wrote:

> moldcraft[at]email.com  ?
>
> On 29 February 2016 at 15:44, moldcraft <notifications@github.com> wrote:
>
>> Send the admin/ftp details to moldcraft[at]email.com and I will take a
>> look in a few hours.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190140076>.
>>
>
>
>
> --
> Linjo Joson
>



-- 
Linjo Joson

**Comment by linjo** [comment]
Specifically it happens in this line

extensions/shortcodes/shortcodes/table/views/pricing.php

* Line 49:* <?php echo $button->render($atts['table']['content'][ $row_key
][ $col_key ]['button']); ?>

On 29 February 2016 at 17:27, Linjo Joson <linjo13@gmail.com> wrote:

> Hi,
>
> I just found that this happens when you add a table row as a button row.
> Looking more into it
>
> On 29 February 2016 at 15:58, Linjo Joson <linjo13@gmail.com> wrote:
>
>> moldcraft[at]email.com  ?
>>
>> On 29 February 2016 at 15:44, moldcraft <notifications@github.com> wrote:
>>
>>> Send the admin/ftp details to moldcraft[at]email.com and I will take a
>>> look in a few hours.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190140076>
>>> .
>>>
>>
>>
>>
>> --
>> Linjo Joson
>>
>
>
>
> --
> Linjo Joson
>



-- 
Linjo Joson

**Comment by moldcraft** [comment]
Please add [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.9/shortcodes/table/static.php)

```php
fw_ext('shortcodes')->get_shortcode('button')->_enqueue_static();
```

and let us know if it fixes the problem.

**Comment by linjo** [comment]
Inside theme or plugin?

On 29 February 2016 at 18:03, moldcraft <notifications@github.com> wrote:

> Please add here
> <https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.9/shortcodes/table/static.php>
>
> fw_ext('shortcodes')->get_shortcode('button')->_enqueue_static();
>
> and let us know if it fixes the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190192927>.
>



-- 
Linjo Joson

**Comment by linjo** [comment]
Oh Yes! That fixed the issue . Thanks a lot :)

On 29 February 2016 at 18:08, Linjo Joson <linjo13@gmail.com> wrote:

> Inside theme or plugin?
>
> On 29 February 2016 at 18:03, moldcraft <notifications@github.com> wrote:
>
>> Please add here
>> <https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.9/shortcodes/table/static.php>
>>
>> fw_ext('shortcodes')->get_shortcode('button')->_enqueue_static();
>>
>> and let us know if it fixes the problem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ThemeFuse/Unyson/issues/1316#issuecomment-190192927>.
>>
>
>
>
> --
> Linjo Joson
>



-- 
Linjo Joson
