### ISSUE TITLE
WP Engine - Cannot create file: ".../wp-content/uploads/fw-backup/index.php"

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1319]
The page hangs on "We are currently installing your content. Directory Cleanup"

or

error message "Cannot create file: /sitename/wp-content/uploads/fw-backup/index.php"

I thought that the problem is in the permissions but it's not them. What may be the cause of this?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1123#issuecomment-173549247

**Comment by pe6o** [comment]
Oh, there is already such issue. My searching skills...
