### ISSUE TITLE
Theme Settings saved hook.

### ISSUE THREAD

**Issue by Priler** [ThemeFuse/Unyson#1320]
Hi!

Is there something like
```add_action('fw_db_settings_saved', 'blabla_do_something');```
available?

I mean "after theme settings saved" event.

**Comment by moldcraft** [comment]
[Yes](https://github.com/ThemeFuse/Unyson/blob/v2.5.0/framework/core/components/backend.php#L1329) ([yes](https://github.com/ThemeFuse/Unyson/blob/v2.5.0/framework/core/components/backend.php#L1318))

**Comment by dinhtungdu** [comment]
Is there a way to manipulate newly saved data on save action? From `fw_settings_form_saved` action, we can only access old value.

**Comment by moldcraft** [comment]
New values are already updated in db and can be accessed with `fw_set_db_settings_option()`
