### ISSUE TITLE
Translation Spanish on Transifex

### ISSUE THREAD

**Issue by olavepablo** [ThemeFuse/Unyson#1321]
Hi, Good day, I translated to the spanish version through Transifex, you must designate a reviewer to approve translations. 
Option "Manage Collaborators" https://www.transifex.com/themefuse/unyson/language/es/

Best Regards
Pablo

**Comment by moldcraft** [comment]
Thank you!

P.S. I don't know where to find a reviewer.

**Comment by olavepablo** [comment]
Thanks to you for your work, your framework is fantastic.
If you are in agreement I can accept the position of reviewer for spanish languages. 
For translations in the spanish do not maintain too much variation.
I use Wordpress six years ago, I know the adequate translation Spanish-speaking regions.

I remain attentive to your response @moldcraft , best regards

**Comment by moldcraft** [comment]
Omg, what a confusing interface has transifex for managing roles, I can't find where/how to make you Reviewer

**Comment by moldcraft** [comment]
Try to submit a request for Reviewer (if there is a possibility to do that) and I will accept it

**Comment by olavepablo** [comment]
Hi, take a look to this faq: 
[Roles in transifex](http://docs.transifex.com/introduction/#user-roles-in-transifex) 
And in this page click on "[manage collaboratos](https://www.transifex.com/themefuse/collaborators/)" maybe exists option to assign roles if you are a "Team Manager " or "Coordinator". [Page team](https://www.transifex.com/themefuse/teams/) click on "team manager settings" (user icon beside icon message)

Best Regards!

**Comment by moldcraft** [comment]
* On [manage collaborators](https://www.transifex.com/themefuse/collaborators/) I can only remove collaborators.
* On [Edit Spanish Team](https://www.transifex.com/themefuse/teams/31332/es/) there is an option and I tried a lot of times to used it but nothing happens, there is no Save button https://vidozz.com/4nK

    * Also I tried to Delete you from team but it doesn't work (nothing happens)

**Comment by moldcraft** [comment]
Done.

How I did it:

1. Moved Pablo to Coordinators.

    Moving from Translators to Coordinators works, but from Translators to Reviewers not.

2. Tried to move from Coordinators to Reviewers - doesn't allow that because it sais "There must be at least one coordinator"
3. Added myself to coordinators.
4. Moved Pablo to Reviewers

What a mess...

**Comment by olavepablo** [comment]
Hi @moldcraft, good day, jajajajajaj it's true the interface of Transifex is not the best, what is awaiting... assign my account to :

Spanish (Spain) (es_ES)
Spanish (Chile) (es_CL) <--- I'm Chilean :D :wine_glass: :+1: 
Spanish (Colombia) (es_CO)
Spanish (Mexico) (es_MX)

Best Regards and thanks for all

**Comment by moldcraft** [comment]
Done
