### ISSUE TITLE
Section in section

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1324]
Hello, 

Looks like there still isn't nested columns in sections, but are there any plans to include them?
For some clients this feature is a must-have and therefore we need to find some kind of solution.

**Comment by moldcraft** [comment]
Hi,

We don't have plans for this.
You can create your own section and column (with prefixed name) that will allow that and disable the existing section and column.

**Comment by YaegerDesign** [comment]
I agree that this should be included. I've used page-building extensions for several years that allow nested sections/columns, and as @pear1 stated, this is a must-have for many projects!

If this is currently possible, please give a more detailed explanation.

**Comment by Undecided90210** [comment]
Nested sections and columns - very necessary things.. really-really

**Comment by danyj** [comment]
no need for this if you know how to use sections and columns , especially nesting sections in sections is a mess. @moldcraft  advised already to create own if you need this.

**Comment by Undecided90210** [comment]
How can I create a structure like this?
![-1](https://cloud.githubusercontent.com/assets/17682602/13554495/416ac158-e3ba-11e5-87d1-54540b2d6456.png)
Visual Composer, or even Cherry Framework allows to do that.

**Comment by danyj** [comment]
@Undecided90210  split it in 2 sections
![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/13554699/68fadd62-e3af-11e5-9045-0c54d7916e3f.jpg)

**Comment by Undecided90210** [comment]
wow :)) thanks! But... it is not universal solution.
Nested sections and columns should be included nevertheless.
I am not alone, many people are talking about this

**Comment by YaegerDesign** [comment]
@danyj, your example assumes even alignment of the first text box and fifth image, which may not be the case. I am trying to do something much simpler, which apparently still can't be done:
![columns](https://cloud.githubusercontent.com/assets/4699897/13582431/59417784-e47a-11e5-9323-e445bce18981.jpg)

**Comment by pear1** [comment]
@YaegerDesign I am trying to do similar layout, which is quite simple, but at this moment can't be done.
