### ISSUE TITLE
Unyson & Changing site URL question

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1325]
Hello!

Is there a simple way to change URL for attached images in Unyson options? I noticed a problem, if i change website URL, URL for images (used in Background image / Icon options created by Unyson) are remains

Thank you :)

**Comment by moldcraft** [comment]
Hi,

Besides `http://site/image.png` you also need to replace

* `http:\/\/site\/image.png`
* `//site/image.png`
* `\/\/site\/image.png`
* all the above with 2+ slashes

Here is how the replace functionality is done in the Backup extension https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.7/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L299-L362
