### ISSUE TITLE
Error Showing

### ISSUE THREAD

**Issue by alisiddique** [ThemeFuse/Unyson#1326]
Warning: include(): Filename cannot be empty in F:\SERVER\XAMP\htdocs\WP\FRAMEWORK\UNYSON\wp-content\themes\scratch-parent\framework-customizations\extensions\portfolio\static.php on line 9

Warning: include(): Failed opening '' for inclusion (include_path='.;F:\SERVER\XAMP\php\PEAR') in F:\SERVER\XAMP\htdocs\WP\FRAMEWORK\UNYSON\wp-content\themes\scratch-parent\framework-customizations\extensions\portfolio\static.php on line 9

**Comment by moldcraft** [comment]
[On line 9](https://github.com/ThemeFuse/Scratch-Theme/blob/4db4e1b2e9860f7ec9dbaa2ab4106f7bbd047334/scratch-parent/framework-customizations/extensions/portfolio/static.php#L9) there is no `include(...)`. Maybe you are using an older version.
