### ISSUE TITLE
Change the display location of the contact form success/fail message

### ISSUE THREAD

**Issue by SilentAce** [ThemeFuse/Unyson#1327]
Hello,

I have a little problem with the contact form and where the success/failed send flash messages are displayed. I am using Unyson with the twentyfourteen theme. Currently they display on top, but i have another image element there which acts as a banner and it pushes that element down. [Link to image](http://prnt.sc/aaoqq8)
Is there a way to display the flash messages on the .fw-row above the contact form? 

Thanks

**Comment by moldcraft** [comment]
Hi,

1. Your theme is based on Scratch theme?
2. Have you read [this](http://manual.unyson.io/en/latest/helpers/php.html#fw-form)?
