### ISSUE TITLE
Fatal Error Due to "Page Builder" extension

### ISSUE THREAD

**Issue by hhbrown123** [ThemeFuse/Unyson#1328]
Hi,

Using Wordpress 4.2.2 and the lasted Unyson and Redox Framework updates, when I activathe the "Page Builder" extension, I get "Fatal error: Call to undefined function menu_page_url() in /home/forthepeople/public_html/rebuilding/wp-content/themes/campaign/framework-customizations/extensions/shortcodes/shortcodes/section/options.php on line 6".

**Comment by moldcraft** [comment]
Please report this problem to theme author
