### ISSUE TITLE
Unyson settings for Widgets.

### ISSUE THREAD

**Issue by Priler** [ThemeFuse/Unyson#1329]
I've tried this: https://github.com/ThemeFuse/Unyson/issues/568

But, when I'm saving settings, Unyson options dissapears.
Is there a way to fix this?

Before saving: http://storage4.static.itmages.com/i/16/0304/h_1457094871_2659513_14ebaaa660.jpeg
After saving: http://storage5.static.itmages.com/i/16/0304/h_1457094906_8272074_28705fccfa.jpeg

Thanks.

p.s. I have last versions of everything. WordPress and Unyson is up to date.

**Comment by moldcraft** [comment]
Hello,

Can you give me all your code related to this issue so I can test (and fix it) on my side?

**Comment by Priler** [comment]
The same code as here https://github.com/ThemeFuse/Unyson/issues/568#issuecomment-102938517

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/568
