### ISSUE TITLE
Can't create working inipage Anchor Tag

### ISSUE THREAD

**Issue by AndrewSocialLite** [ThemeFuse/Unyson#1333]
Hey there, I'd like to create anchor tags like the method described here:
http://help.typepad.com/anchor-tags.html

But for some reason it doesn't work in a Theme that i'm using Unyson on. Is it possible that the blocks disrupt the anchor link code?

**Comment by moldcraft** [comment]
Hello,

Use [this solution](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head).
