### ISSUE TITLE
Pagebuilder - problem with content on the frontpage

### ISSUE THREAD

**Issue by mariuszpucek** [ThemeFuse/Unyson#1334]
I was using to display content of static page 197 on frontpage:

  

```
<?php
 $sw_content = get_post_field('post_content',197);
$sw_content = apply_filters('the_content', $sw_content);
echo $sw_content;
?>
```

After updates that function stop to work, previously was working. Can you help me? How should looks like the code to display a post content on the front page?

I was trying

```
<?php
$post = get_post(197);
echo $post->post_content;
?>
```

is not working a with page builder either

Any ideas?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1337#issuecomment-192966785
