### ISSUE TITLE
Please do something about builder drag and drop 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1336]
This is just very hard  to work with. I know we were looking at other builder possibilities but this is almost unacceptable

http://screencast.com/t/S2AXm0qTT

**Comment by duongancol** [comment]
it should get hight priority :100:

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25

**Comment by danyj** [comment]
@moldcraft  couldn't find  that one. thnx
