### ISSUE TITLE
Unable to show Unyson content with get_post_field

### ISSUE THREAD

**Issue by pgluz** [ThemeFuse/Unyson#1337]
Hi. 
I’ve made an empty page with 3 columns + icon boxes inside in Unyson. The page ID is 13.

Now I’m trying to display it on front-page.php. Here’s my code:
```
<?php
	$post_id = 13;
 	echo get_post_field('post_content', $post_id);
?>
```

It doesn’t work. 
Anyway, any content written in the default editor is displayed correctly.

My question is: what am I doing wrong?

I will be grateful for your help.

**Comment by moldcraft** [comment]
It is because of [PageBuilder 1.5.0 update](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/185). This should work:

```php
$posts = get_posts(array(
	'include' => 13,
	'post_type' => 'any',
	'numberposts' => 1,
	'suppress_filters' => false,
));

echo apply_filters('the_content', $posts[0]->post_content);
```

**Comment by moldcraft** [comment]
In PageBuilder 1.5.1 will be available [this function](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/aec7bb41437316b8a798ec229147c43d6e78d1eb/helpers.php#L36-L49). Which can be used like this

```php
echo fw_ext_page_builder_get_post_content(13);
```
