### ISSUE TITLE
Unyson is not recognising the backups extension

### ISSUE THREAD

**Issue by michaellwatson** [ThemeFuse/Unyson#1340]
The backup extension exists, but its not being recognised/installed by the server

**Comment by moldcraft** [comment]
More details please. Maybe a screencast or screenshot.

**Comment by michaellwatson** [comment]
![untitled-8](https://cloud.githubusercontent.com/assets/6263630/13605163/20bef02a-e53e-11e5-9d3a-7ecf5b786ca7.jpg)
![untitled-6](https://cloud.githubusercontent.com/assets/6263630/13605166/2596f354-e53e-11e5-8728-df2400f93cce.jpg)

**Comment by michaellwatson** [comment]
you can see backups is there in extensions, but isn't showing in the front end, I don't know why that is

**Comment by moldcraft** [comment]
show please what's inside the `backups/` folder

**Comment by michaellwatson** [comment]
![untitled-9](https://cloud.githubusercontent.com/assets/6263630/13607672/2a9ed56e-e549-11e5-92ac-835822ab0f90.jpg)

**Comment by moldcraft** [comment]
strange. maybe the problem is in permissions?

**Comment by michaellwatson** [comment]
the folder is 755 and the files are 644

**Comment by michaellwatson** [comment]
I had to install it manually because I have no FTP on my server

**Comment by moldcraft** [comment]
I think it doesn't enter in [this if](https://github.com/ThemeFuse/Unyson/blob/v2.5.0/framework/core/components/extensions.php#L204). Debug it to find why

**Comment by michaellwatson** [comment]
I got it working by renaming the folder and copying the wordpress option data from a working install, strange though
