### ISSUE TITLE
Learning extension, lessons not works

### ISSUE THREAD

**Issue by Priler** [ThemeFuse/Unyson#1341]
Hi!

If I create lesson and open it by this URL: ```/lesson/lesson-1/```
I will get 404 error.

Ho this can be fixed?

**Comment by moldcraft** [comment]
Make sure your permalink settings are ok. Press Save on Permalinks settings page to update the rules.

**Comment by Priler** [comment]
Thank you!
Everything works now.

**Comment by Priler** [comment]
One more question.
Is there a way to make Quizes to be Ajax?

**Comment by moldcraft** [comment]
I am not the author of Learning extension and don't know how it works. So at the moment the answer is no.
