### ISSUE TITLE
Option fields not showing when adding terms to custom taxonomy

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1343]
Hello,

I'm trying to extend the standard taxonomy fields with some custom fields, for example:

- text field to input Font Awesome class name

I've managed to add the field, and let it display on the page where you edit the term. But when I add a new term, the field isn't showing.

![term-edit](https://cloud.githubusercontent.com/assets/10668469/13607748/dbe27404-e551-11e5-812a-cd92200b1b19.jpg)
![term-add](https://cloud.githubusercontent.com/assets/10668469/13607747/dbe26810-e551-11e5-9ada-b9b288e6d195.jpg)

Is there a setting that I'm overlooking? Or is it not possible to do this?

Thanks in advance

-Kevin

**Comment by moldcraft** [comment]
Hello,

We tried to do this but it's not possible.

If you'll find how to implement this, please let us know.
