### ISSUE TITLE
Сan't display two identical shortcodes on a single page

### ISSUE THREAD

**Issue by Eynsteyn** [ThemeFuse/Unyson#1345]
![visual editor](https://cloud.githubusercontent.com/assets/7722113/13635032/04360a0a-e602-11e5-81af-90ff5dcc9e91.PNG)
![page](https://cloud.githubusercontent.com/assets/7722113/13635046/09b65fd4-e602-11e5-9cdf-87f24561cd34.PNG)

I attached link to archive with my shortcode
http://www96.zippyshare.com/v/9BLWy94J/file.html

**Comment by moldcraft** [comment]
The problem is in `require_once` in `views/view.php`. Replace it with `require`
