### ISSUE TITLE
Labels in Taxonomy

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1347]
When I add options for any taxonomy in `options/taxonomies/*.php` it handles labels in a strange way.

It only displays labels correctly options of the [first level](https://i.imgur.com/4QvKUit.png).

I understand that you are limited by the fact that WordPress used to implement this whole __columns__ thing with [tables](https://i.imgur.com/yVY373F.png). This also doesn't allow us to add tabs to the taxonomies page. I know that this is specified in the [manual](http://manual.unyson.io/en/latest/options/introduction.html#restrictions) as a restriction.

Have you tried to include a div [below](https://cloud.githubusercontent.com/assets/2979628/13648067/9cb0ad7a-e63f-11e5-9571-366a3ee4b3f8.png) this table, just like you do for posts -- including them below the wp editor? This may require to disable __lazy tabs__ for this particular container, not sure. This will fix a lot of troubles and will bypass restriction you wrote into the manual.

I haven't looked into the code yet, let me know if there's some limitations that would not let us do this.

**Comment by danyj** [comment]
@moldcraft  lifted the restrictions few days ago but I think the manual is not up to date for now 
https://github.com/ThemeFuse/Unyson/issues/1295#issuecomment-188693200

**Comment by moldcraft** [comment]
> Have you tried to include a div below this table, just like you do for posts -- including them below the wp editor?

If you'll find a WordPress action to do that we will do it.

> I think the manual is not up to date for now

Yes, because the changes are not included in release yet.

**Comment by andreiglingeanu** [comment]
@moldcraft

> If you'll find a WordPress action to do that we will do it.

[There](https://github.com/WordPress/WordPress/blob/master/wp-admin/edit-tag-form.php#L255) you go. You can also [find](https://github.com/WordPress/WordPress/blob/master/wp-admin/edit-tag-form.php#L227-L244) a whole range of deprecated ones.

**Comment by moldcraft** [comment]
I will

**Comment by andreiglingeanu** [comment]
@moldcraft Thanks.

**Comment by moldcraft** [comment]
I will use `get_current_screen()` to detect current taxonomy and do only one `add_action()`

**Comment by andreiglingeanu** [comment]
@moldcraft Sounds great.

**Comment by moldcraft** [comment]
_I think initially we added options in table to make them look the same as WordPress options, to not "break" the design._

**Comment by andreiglingeanu** [comment]
I see, that was a good temporary behavior. It breaks as soon as you add a nested option or when you need tabs or other containers.

**Comment by moldcraft** [comment]
It contains some [hardcode css fixes](https://github.com/ThemeFuse/Unyson/blob/610311f56b8c72320baf8b75141b55101c1db3f1/framework/static/css/backend-options.css#L1126-L1127). I don't know a general solution. If you'll find one, please pull request.
