### ISSUE TITLE
reCaptcha doesn't work if allow_url_fopen is set 0

### ISSUE THREAD

**Issue by mrblc** [ThemeFuse/Unyson#1349]
Hi,

reCaptcha implementation is using `get_file_content` to validate. If `allow_url_fopen` is set `0` (security reasons), `get_file_content` fails with error message.

Problem is in forms extension and solution is:
In file: `/forms/includes/option-types/form-builder/items/recaptcha/includes/includes.php` line (13):

```php
		'Post'              => 'RequestMethod/Post'
```

replace with:

```php
		'Post'              => 'RequestMethod/Post',
		'Socket'            => 'RequestMethod/Socket',
		'SocketPost'        => 'RequestMethod/SocketPost'
```

In file: `/forms/includes/option-types/form-builder/items/recaptcha/class-fw-option-type-form-builder-item-recaptcha.php` line (156):

```php
		$recaptcha          = new ReCaptcha( $keys['secret-key'] );
```

replace with:

```php
		$recaptcha          = new ReCaptcha( $keys['secret-key'], new SocketPost() );
```

ALTERNATIVE VERSION, to allow users with `allow_url_fopen` set `1` to continue using `get_file_content` version:

in file: `/forms/includes/option-types/form-builder/items/recaptcha/includes/includes.php`

```php
if (!ini_get('allow_url_fopen')) {
    // define array with newly added defines
}
else {
    // define original array
}
```

in file: `/forms/includes/option-types/form-builder/items/recaptcha/class-fw-option-type-form-builder-item-recaptcha.php`

```php
if (!ini_get('allow_url_fopen')) {
    $recaptcha          = new ReCaptcha( $keys['secret-key'], new SocketPost() );
}
else {
    $recaptcha          = new ReCaptcha( $keys['secret-key'] );
}
```

With regards,
Marko Bilić

**Comment by moldcraft** [comment]
Thank you
