### ISSUE TITLE
Changing the grid for all builders as in manual didn`t work

### ISSUE THREAD

**Issue by heyas** [ThemeFuse/Unyson#1350]
How it works:
```
	wp_register_style(
		'fw-ext-builder-frontend-grid',
		get_template_directory_uri().'/framework-customizations/extensions/builder/static/css/frontend-grid.css',
		array(),
		fw_ext('builder')->manifest->get_version()
	);
```

But with parameter "fw-theme-frontend-grid" (as in [manual](http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid-for-all-builders)) did not.

**Comment by moldcraft** [comment]
In which file you placed the above code?

**Comment by heyas** [comment]
In static.php and it works.

**Comment by moldcraft** [comment]
The idea is when you create

```
{theme}/framework-customizations/extensions/builder/static.php
```

then

```
unyson/framework/extensions/builder/static.php
```

will not be included at all, and the style will not be enqueued.

On your side this doesn't work?

**Comment by heyas** [comment]
I got it, but if i use "fw-theme-frontend-grid" it doesn`t work. Work only with 'fw-ext-builder-frontend-grid', work as expected: I have only my {theme}/framework-customizations/extensions/builder/static/css/frontend-grid.css.

**Comment by moldcraft** [comment]
Sorry, the actual problem is `wp_enqueue_style(` not `wp_register_style(`.

But also I think your solution is better because you don't have to overwrite/replace `fw-ext-builder-frontend-grid` with `fw-theme-frontend-grid` everywhere it is used, you just change the url. Thanks!
