### ISSUE TITLE
Global get option function suggestion

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1356]
Many of us will use some of the theme default options inside page, post , category or portfolio, 
Currently they are all separated  in each respective function

    fw_get_db_settings_option($option_id, $default_value = null)
    fw_get_db_post_option($post_id, $option_id, $default_value = null)
    fw_get_db_term_option($term_id, $taxonomy, $option_id, $default_value = null)

can we bundle these 3  in to one so that we can use one function for all of them like, 

     fw_get_db_global_option($option_id, $default_value = null)

I started with this  which bundles portfolio, category and post ,  but I am sure that there is better approach and more checks to be done 

	 /**
	 * Get portfolio, category, post or page option
	 * @return option value
	 */
	function _thz_fw_get_global_option ($id,$default = null){
		
		
		if ( ( is_tax('fw-portfolio-category') || is_post_type_archive('fw-portfolio') )) { // portfolio options
			$taxonomy 		= 'fw-portfolio-category';
			$term 			= get_term_by( 'slug', get_query_var( 'term' ), $taxonomy );
			$term_id		= ( ! empty( $term->term_id ) ) ? $term->term_id : 0;
			$get_option 	= fw_get_db_term_option($term_id, $taxonomy,$id,$default);
			
			return $get_option;
		
		}else if ( is_category() ) {// category options	
			
			$term 	  		= get_category( get_query_var( 'cat' ) );
			$term_id  		= ( ! empty( $term->term_id ) ) ? $term->term_id : 0;	
			$get_option		= fw_get_db_term_option($term_id, 'category',$id,$default);
			
			return $get_option;
			
		} else {// post options	
			
			return fw_get_db_post_option(get_the_ID(),$id,$default);
			
		}
		
	}

**Comment by ivandotv** [comment]
Bad idea.
Checking all those options if they are for `category` , `post` or whatever, is prone to error. 
Also what happens when you want `category` option on `post` page, for whatever reason?
In my opinion best thing to do is to create your own custom wrapper function.

maybe something like this:
`function _thz_fw_get_global_option ($where='settings',$id,$default = null)`

`$where` can be (settings,term,customizer,post etc...)
and you do a `switch` statement for `$where` variable.

**Comment by danyj** [comment]
@ivandotv  

> is prone to error.

 thus I advised that

> I started with this which bundles portfolio, category and post , **but I am sure that there is better approach **

in short , I am looking for a short way possible to get a global option that has same ID and is declared in 
theme settings
post
page
category


> what happens when you want category option on post page

again , that global option would be in either of the above mentioned  option groups so what will happen is you get the global option value depending on where you are. 


plain example , you have in theme settings ,  following 

	'breadcrumbs_switch' => array(
		'label' => __('Show/hide', 'fw'),
		'type' => 'switch',
		'right-choice' => array(
			'value' => 'hide',
			'label' => __('Hide', 'fw')
		),
		'left-choice' => array(
			'value' => 'show',
			'label' => __('Show', 'fw')
		),
		'value' => 'show'
	)


than  you add same option in category , page, post 

in your page templates you add something like 


    echo  my_breadcrumbs ()



currently to get the value , you need to use 3 different functions and multi checks,  with global option function , you would use just this . 


	function my_breadcrumbs (){
		
		$breadcrumbs_switch = fw_get_db_global_option('breadcrumbs_switch','show');
		
		if($breadcrumbs_switch === 'show' ){
			
			return 'breadcrumbs';	
		}
		
	}

**Comment by ivandotv** [comment]
If I understood you correctly, you want to check for `global` option, and for `custom` option.
If `custom` option is defined, it will override the global option?

**Comment by danyj** [comment]
@ivandotv  Exactly.

**Comment by ivandotv** [comment]
I'm gonna be needing this soon, still working on global options. 
Will tackle this issue next week :)

**Comment by danyj** [comment]
thnx for looking out, pay attention to this one , I made huge mistake above and used query to get the id instead  ,  

    get_queried_object_id()

is much faster 

	function _thz_fw_get_global_option ($id,$default = null){
		
		
		if ( ( is_tax('fw-portfolio-category') || is_post_type_archive('fw-portfolio') )) { // portfolio options
			
			return fw_get_db_term_option(get_queried_object_id(),'fw-portfolio-category',$id,$default);
			
		
		}else if ( is_category() ) {// category options	
	
			return fw_get_db_term_option(get_queried_object_id(),'category',$id,$default);
			
		} else {// post options	
			
			return fw_get_db_post_option(get_the_ID(),$id,$default);
			
		}
		
	}

**Comment by ivandotv** [comment]
@danyj 
Yeah, I'm always using `get_queried_object_id()`
Also it appears to me that your code is trying to do to much.

My relationship with global options is this:
- global post option.
- custom post option.

- So the function to get the definite post option would check `custom` option, and if `null` it would check
`global` option (which has the default value always)

- I would make custom function for 'terms', 'posts' etc....

**Comment by danyj** [comment]
@moldcraft   bud if you have a sec to direct me please. 
Since themes must work without Unyson, from the start I created own options function that check for unyson

	function thz_get_option($id,$default = null){
		
		if (thz_fw_loaded()) {
	
			// default theme option
			return fw_get_db_settings_option($id,$default);
	
		}else {//  Unyson is off, show defaults
	
			$options 	= thz_get_default_theme_options();	
			return thz_akg($id,$options,$default);
			
		}
	
	}


now that same function is extended to check for global option but I cant seems to shake of the check  inside each option , this is a plain example to check option on post single 

	function thz_get_option($id,$default = null){
		
		if (thz_fw_loaded()) {
	
	
	
			// custom post options
			if ( is_single() && 'post' == get_post_type() ) {
				$post_custom_post_picked = fw_get_db_post_option(get_the_ID(),'custom_post_options',array());
				
				if(!empty($post_custom_post_picked) && isset($post_custom_post_picked[0])){
					
					$post_custom_post_option = _thz_fw_get_global_option('custom_post_options/0/'.$id);
					if(isset($post_custom_post_option)){
						return $post_custom_post_option;
					}
				}
			}
	
			
			// default theme option
			return fw_get_db_settings_option($id,$default);
	
		}else {//  Unyson is off, show defaults
	
			$options 			= thz_get_default_theme_options();	
			return thz_akg($id,$options,$default);
			
		}
	
	}



all this works oki'sh  but it just bugs me that the check is running for each option , and if on that page there are 100 `thz_get_option `, the check runs way to much in my opinion.  
how can I globalize this in a best way to return specific option on specific page without running the check inside the   

    thz_get_option

possible? 

hm just writing about it , would it be better to change the function based on condition like 



```
if is single 
function thz_get_option($id,$default = null){
return  fw_get_db_post_option($pageid,$id,$default);
}

if category 

function thz_get_option($id,$default = null){
$tax = is_tax() ? get_queried_object()->taxonomy :'category';

return fw_get_db_term_option(get_queried_object_id(),$tax,$id,$default);

}
```

and so on?

**Comment by moldcraft** [comment]
Add some caching and test if with/without cache makes a difference.

**Comment by danyj** [comment]
@moldcraft    any way to post an example? I have no idea how to start with cache. 
just tested and checking inside the function is an overload. 
page normally loads in 1.6sec , with all the checks for pages, term, single etc , it loads in 4sec ,  


than I removed all checks for page types and did just this 



			$post_options = fw_get_db_post_option(get_the_ID(),'custom_post_options/0/'.$id,array());
			
			if ( ! empty ( $post_options )) {
				return $post_options;
			} 


and that one check adds 1 sec , so 2.5. This is just pain and I dont understand how others dont see this as needed. I am not going to do  ifs and loops inside the files and check back and forth for values. 

Also checked other themes , be , avada , x , enfold and even they have global functions 


here avada


	if( ! function_exists( 'fusion_get_option' ) ) {
		function fusion_get_option( $theme_option, $page_option, $post_id ) {
			if ( $theme_option &&
				 $page_option &&
				 $post_id
			) {
				$page_option = strtolower( fusion_get_page_option( $page_option, $post_id ) );
				$theme_option = strtolower( fusion_get_theme_option( $theme_option ) );
	
				if ( $page_option != 'default' &&
					 ! empty ( $page_option )
				) {
					return $page_option;
				} else {
					return $theme_option;
				}
			}
	
			return FALSE;
		}
	}


checks for option in page and if exists it spits it out.

**Comment by moldcraft** [comment]
let me fix [this](https://github.com/ThemeFuse/Unyson/blob/188e74076943213b77f605297374974252c1ad2c/framework/helpers/database.php#L232) then you will test the speed again (maybe it will help)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/374daad0716eedd7c736f8aa57b3e670029038e3

**Comment by danyj** [comment]
ok , better , 5 checks  now add 0.8 to 1.2  sec , much faster than previously. I think fine tuning the check will help further. what I would love to do is change the function based on check , this way the check is outside and not inside. but that does not work from theme/helper.php

**Comment by danyj** [comment]
sent you the full combo for functions so you can see what I mean

**Comment by moldcraft** [comment]
[Before](http://sourcebox.io/440e96a71a19777973fac9d805182c71/php) and after:

```php
<?php

/**
 * Faster check for options
 * @internal
 */
function thz_fw_loaded() {
	return function_exists('fw_get_db_settings_option');
}

/**
 * Get post options fallback
 * @return post options
 */
function thz_get_post_option($option_id = null, $default_value = null) {
	return thz_fw_loaded()
		? fw_get_db_post_option(get_the_ID(), $option_id, $default_value)
		: array();
}

/**
 * Get portfolio, category, post or page option
 * @return option value
 */
function _thz_fw_get_global_option($id, $default = null) {
	static $condition = null;

	if (is_null($condition)) {
		$condition = array(
			'case' => 0,
			'data' => array(),
		);

		if ( is_tax() || is_category() ) { // category options
			$condition['case'] = 1;
			$condition['data'] = array(
				'id'  => get_queried_object_id(),
				'tax' => is_tax() ? get_queried_object()->taxonomy : 'category'
			);
		} elseif (class_exists( 'WooCommerce' ) && !is_single()) {
			if ( (is_shop() || is_cart() || is_checkout() || is_account_page()) ) {
				$condition['case'] = 2;
				$condition['data'] = array(
					'id' => is_shop() ? wc_get_page_id('shop') : get_queried_object_id(),
				);
			}
		} else { // post options
			$condition['case'] = 3;
		}
	}

	switch ($condition['case']) {
		case 1:
			return fw_get_db_term_option($condition['data']['id'], $condition['data']['tax'], $id, $default);
		case 2:
			return fw_get_db_post_option($condition['data']['id'], $id, $default);
		case 3:
			return fw_get_db_post_option(get_the_ID(), $id, $default);
	}
}

/**
 * Get options value
 * if framework is missing , load defaults
 * @return option value
 */
function thz_get_option($id, $default = null)
{
	if (thz_fw_loaded()) {
		// custom post options
		if (is_single() && 'post' == get_post_type()) {
			$post_custom_post_picked = fw_get_db_post_option(get_the_ID(), 'custom_post_options', array());

			if (!empty($post_custom_post_picked) && isset($post_custom_post_picked[0])) {
				$post_custom_post_option = _thz_fw_get_global_option('custom_post_options/0/' . $id);
				if (isset($post_custom_post_option)) {
					return $post_custom_post_option;
				}
			}
		}

		// custom site options
		$post_custom_site_picked = _thz_fw_get_global_option('custom_site_options', array());

		if (!empty($post_custom_site_picked) && isset($post_custom_site_picked[0])) {
			$post_custom_site_option = _thz_fw_get_global_option('custom_site_options/0/' . $id);
			if (isset($post_custom_site_option)) {
				return $post_custom_site_option;
			}
		}

		// custom header options
		$post_custom_header_picked = _thz_fw_get_global_option('custom_header_options', array());

		if (!empty($post_custom_header_picked) && isset($post_custom_header_picked[0])) {
			$post_custom_header_option = _thz_fw_get_global_option('custom_header_options/0/' . $id);
			if (isset($post_custom_header_option)) {
				return $post_custom_header_option;
			}
		}

		// custom topmenu options
		$post_custom_topmenu_picked = _thz_fw_get_global_option('custom_topmenu_options', array());

		if (!empty($post_custom_topmenu_picked) && isset($post_custom_topmenu_picked[0])) {
			$post_custom_topmenu_option = _thz_fw_get_global_option('custom_topmenu_options/0/' . $id);
			if (isset($post_custom_topmenu_option)) {
				return $post_custom_topmenu_option;
			}
		}

		// custom pagetitle options
		$post_custom_pagetitle_picked = _thz_fw_get_global_option('custom_pagetitle_options', array());

		if (!empty($post_custom_pagetitle_picked) && isset($post_custom_pagetitle_picked[0])) {
			$post_custom_pagetitle_option = _thz_fw_get_global_option('custom_pagetitle_options/0/' . $id);
			if (isset($post_custom_pagetitle_option)) {
				return $post_custom_pagetitle_option;
			}
		}

		// custom footer options
		$post_custom_footer_picked = _thz_fw_get_global_option('custom_footer_options', array());

		if (!empty($post_custom_footer_picked) && isset($post_custom_footer_picked[0])) {
			$post_custom_footer_option = _thz_fw_get_global_option('custom_footer_options/0/' . $id);
			if (isset($post_custom_footer_option)) {
				return $post_custom_footer_option;
			}
		}

		// default theme option
		return fw_get_db_settings_option($id, $default);
	} else { // Unyson is off, show defaults
		$options = thz_get_default_theme_options();
		return thz_akg($id, $options, $default);
	}
}
```

Note: I haven't tested the code.

**Comment by danyj** [comment]
@moldcraft   bud , how do you return default value from  

      fw_get_db_settings_option('id',null );

if   default is set to null ?

I looked trough the function but not sure how to do it , 

asking because I am using this  and just want to make sure  null returns the default if unyson is not enabled  #1515 


```
function thz_get_theme_option($id,$default = null){
	
	
	 if (thz_fw_loaded()) {
		 
		return fw_get_db_settings_option($id,$default);

    }else {//  Unyson is off, show defaults

		$options 	= thz_get_default_theme_options();	
		return thz_akg($id,$options,$default);
		
	}	
	
}
```

**Comment by moldcraft** [comment]
If default is set and db value is empty, the execution will stop [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/helpers/database.php#L50), else it will continue and will extract default values from options array, and again default is used [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/helpers/database.php#L106-L114)
