### ISSUE TITLE
Page Builder not visible

### ISSUE THREAD

**Issue by maxception** [ThemeFuse/Unyson#1362]
Hello,

I have a strange problem. Page Builder doesn't show up anymore when editing a page but it appears when editing a blog page. 

Everything is up to date (Unyson 2.5)

Thank you

**Comment by moldcraft** [comment]
Hello,

We need more details to reproduce the problem on our side, or send us the admin/ftp details to `moldcraft[at]email.com`

**Comment by moldcraft** [comment]
[Check this](https://github.com/ThemeFuse/Unyson/issues/1313#issuecomment-195295812), maybe it's the same problem.

**Comment by maxception** [comment]
It doesn't look like the same problem. I'll attach a screenshot. The problem exists only when editing pages, on blog posts and custom post types there is no problem.

I will send you the admin details.
![bildschirmfoto 2016-03-15 um 11 13 52](https://cloud.githubusercontent.com/assets/17838592/13774774/1d6eeea8-eaa1-11e5-8948-24cac9075a39.png)

**Comment by moldcraft** [comment]
Thank you for admin details. I opened edit page and the builder is there

![](https://static.md/dd00160a84978f72fb7ef38d71900eee.png)

So, where is the problem?

**Comment by maxception** [comment]
I logged in with the user details I've sent you and now I can see the builder too.
With the normal admin login it still doesn't work for me. Do you have an idea about that?

**Comment by moldcraft** [comment]
> With the normal admin login it still doesn't work for me

normal admin?

**Comment by maxception** [comment]
Usually I use another account as admin account for login. With my usual admin account I can't see the builder but with the account I've sent you, I can.

**Comment by giathinh910** [comment]
I have the same issue here. I have to create a new account to make the page builder display.

**Comment by moldcraft** [comment]
When I [check this](https://static.md/d7f5dfff2ef23ecd1fc98ecd4430b4d5.png) I have the same problem

**Comment by giathinh910** [comment]
No luck. If I uncheck it, there will be nothing display for editing. Here is the [screenshot](http://prntscr.com/arkqk1).

**Comment by moldcraft** [comment]
@giathinh910 any js errors?

**Comment by giathinh910** [comment]
@moldcraft I sent you the demo site credential, you can directly check the issue. The user that I sent have the issue, when creating a new user, no problem.

**Comment by moldcraft** [comment]
@giathinh910 WordPress saves on server when you click to close/open a metabox. The box that contains was somehow [closed](https://static.md/7d3512667b464f1ffd90ac4c68a99c95.png), and because it doesn't have a title, it was not visible at all. [I clicked to open it and an ajax request was made](https://static.md/c4cdefd825a26f7dea842819614744da.png) to remember it's open state, so after page refresh it remains open.

**Comment by giathinh910** [comment]
I understood. Just because the collapse button is hide too so I have no clue. Thanks very much for your help.

**Comment by wprookie** [comment]
Hi also have problems with the unyson page builder. the option to edit the page with the unyson builder has dissapeared. can't seem to get this visible again. Any help?
