### ISSUE TITLE
Tabs inside multi-picker in options popup need more top margin

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1364]
In theme settings 

![screenshot_13](https://cloud.githubusercontent.com/assets/2340172/13778827/3c2876b8-eab8-11e5-86f6-6368f674287d.jpg)

in popup 

![screenshot_12](https://cloud.githubusercontent.com/assets/2340172/13778831/417d4e9a-eab8-11e5-8cf0-de519c86f24b.jpg)

**Comment by moldcraft** [comment]
On my side everything is fine

![](https://static.md/927bf9ae902f4ecd516f3ca0a05d65f2.png)

![](https://static.md/504b971335ca528770b8444aa0d34b70.png)

* `framework-customizations/theme/options/settings.php`

```php
$options = array(
	'm' => array(
		'label' => false,
		'type' => 'multi-picker',
		'picker' => array(
			'test' => array(
				'type' => 'switch',
				'desc' => 'Hello World',
				'left-choice' => array(
					'value' => 'hello',
					'label' => __('Hello', '{domain}'),
				),
				'right-choice' => array(
					'value' => 'goodbye',
					'label' => __('Goodbye', '{domain}'),
				),
			),
		),
		'choices' => array(
			'hello' => array(
				't1' => array(
					'type' => 'tab',
					'title' => 'Tab 1',
					'options' => array(),
				),
				't2' => array(
					'type' => 'tab',
					'title' => 'Tab 2',
					'options' => array(),
				),
			)
		),
	),
);
```

* `framework-customizations/extensions/shortcodes/shortcodes/button/options.php`

```
$options = fw()->theme->get_settings_options();
```

**Comment by danyj** [comment]
yes , on my end to now , you changed some css in last couple days so it could have been fixed with it. closing
