### ISSUE TITLE
"Shortcodes" extension github repository "ThemeFuse/Unyson-Shortcodes-Extension" has no releases

### ISSUE THREAD

**Issue by Turkishiello** [ThemeFuse/Unyson#1365]
"Shortcodes" extension github repository "ThemeFuse/Unyson-Shortcodes-Extension" has no releases

**Comment by Turkishiello** [comment]
in local server Apache Unyson go, but on server altervista give me that message....

**Comment by moldcraft** [comment]
Please add [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.0/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2473)

```
fw_print(response);
```

**Comment by Turkishiello** [comment]
i try to insert that string....sorry i don't understand...before the if structure or in the { }??

**Comment by moldcraft** [comment]
inside if

**Comment by Turkishiello** [comment]
`if (empty($release)) {fw_print($response);
							return new WP_Error(
								$wp_error_id,
								sprintf(
									__('"%s" extension github repository "%s" has no releases.', 'fw'),
									$this->get_extension_title($extension_name), $source_data['user_repo']
								)
							);
						}`

Like This??

**Comment by moldcraft** [comment]
Yes.

Now try to install the extension and give us the printed details

**Comment by Turkishiello** [comment]
SyntaxError: Unexpected token <

**Comment by moldcraft** [comment]
Open in browser

```
http://{site}/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=page-builder
```

and do install

**Comment by Turkishiello** [comment]
![cattura](https://cloud.githubusercontent.com/assets/15139306/13827313/1743a426-ebbc-11e5-967f-11085c99a72b.PNG)
![cattura1](https://cloud.githubusercontent.com/assets/15139306/13827314/17612cd0-ebbc-11e5-9fae-6b5455d5b3bc.PNG)

**Comment by Turkishiello** [comment]
if i tru to install from panel i have this.....and if i try to do how you say......i have another response....

**Comment by moldcraft** [comment]
Sorry, comment [this line](https://github.com/ThemeFuse/Unyson/blob/v2.5.0/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2471) and try again

**Comment by Turkishiello** [comment]
![cattura3](https://cloud.githubusercontent.com/assets/15139306/13828778/ae262e8e-ebc3-11e5-8c0c-183f2a290f5c.PNG)

**Comment by moldcraft** [comment]
So that is the answer: Your hosting is blocking requests to `http://github-api-cache.unyson.io/`

**Comment by Turkishiello** [comment]
![cattura4](https://cloud.githubusercontent.com/assets/15139306/13830122/02536970-ebcb-11e5-9d5a-e25315364bdc.PNG)

**Comment by Turkishiello** [comment]
i always think that the htaccess file!!! Very Thanks!!! Very good job!!! Great!!
