### ISSUE TITLE
TinyMCE Custom Buttons

### ISSUE THREAD

**Issue by meneldil** [ThemeFuse/Unyson#1366]
Hello,
I create a button in TinyMCE (plugin), but it is not displayed in the Unyson popup (Text Block).

Here the PHP code:
```
add_action( 'init', 'mcewrap_buttons' );
function mcewrap_buttons() {
	add_filter( 'mce_external_plugins', 'mcewrap_add_button' );
	add_filter( 'mce_buttons', 'mcewrap_register_buttons' );
}
function mcewrap_add_button( $plugin_array ) {
	$plugin_array['mcewrap'] = plugins_url( 'editor_plugin.js', __FILE__ );
	return $plugin_array;
}
function mcewrap_register_buttons( $buttons ) {
	array_push( $buttons, 'mce_wrap', 'mce_remove_wrap' );
	return $buttons;
}
```

Any idea?
Thanks in advance.

**Comment by moldcraft** [comment]
Hello,

https://wordpress.org/support/topic/tinymce-pluings#post-8142088

**Comment by meneldil** [comment]
Ok, we have to be patient then. :(
Thanks!

**Comment by meneldil** [comment]
Ok, we have to be patient then. :(
Thanks!

**Comment by moldcraft** [comment]
Hello,

Tomorrow we will release v2.5.2 that should fix this problem.

**Comment by meneldil** [comment]
Oh really ?
Great news. :D
:+1:
