### ISSUE TITLE
Table Shortcode - moving rows does not save new state

### ISSUE THREAD

**Issue by lineardesign** [ThemeFuse/Unyson#1367]
This is on a fresh WP install using the scratch theme to ensure it was not related to my theme.

The scratch theme **/scratch-parent/framework-customizations/theme/manifest.php** was set to only use the page builder extension.

Steps include:

1. Create a simple table with 3 rows and 3 columns with a basic set of content in each.
2. Saved the table then saved the page.
3. Opened the table and dragged one of the rows to a new position, doesn't matter which one you move.
4. Saved table then saved page.
5. Opened up table and it is back to its original state.

I've tried this on the following [releases](https://github.com/ThemeFuse/Unyson/releases):

- 2.5.0 - with latest extensions installed
- 2.4.17 - with latest extensions installed
- 2.4.16 - with latest extensions installed
- 2.4.15 - with latest extensions installed

This started me thinking it might be due to the extensions rather than the release. I have an old copy of 2.4.3 from a dev site and as long as I did not update the extensions I was able to re-order the rows. As soon as I updated the extensions then I was no longer able to reorder my table.

Two questions:

1. Is anyone else having this issue as well?
2. Any recommendations as to how I can resolve this?

**Comment by moldcraft** [comment]
This was fixed https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/52
