### ISSUE TITLE
How to dequeue style.css on specific extention?

### ISSUE THREAD

**Issue by zenics** [ThemeFuse/Unyson#1368]
I would like to remove/disable the stylesheet it loads with an extension(dont want to overwrite it) so it doesnt conflict with my own styles. Is there a way to do that using a function something like:

```
function _filter_extentions_disable_shortcode($buttons){
wp_dequeue_style()
}
```

**Comment by moldcraft** [comment]
Hi.

Which extension and which stylesheet you want to dequeue?

**Comment by zenics** [comment]
Dont want to desable the extention but just dequeue its style. Buttons.


OZGUR CORUHLU
Creative Manner Design Team 
Mailing: 2331 40th Street #2 NW Washington, DC 20007
Phone: +1 (240) 305 52 34(tel:+1%20(240)%20305%2052%2034)
E-mail: info@creativemanner.com (mailto:info@creativemanner.com)
Web: www.creativemanner.com(http://www.creativemanner.com/) This message was sent by Ozgur Coruhlu .

**Comment by moldcraft** [comment]
The button shortcode?

**Comment by zenics** [comment]
Yes; trying something like

```
$uributton = get_template_directory_uri()  . '/inc/frameworks/extentions/shortcodes/shortcodes/button';
wp_dequeue_style(
    'fw-shortcode-button',
    $uributton . '/static/css/styles.css'
);
```

**Comment by moldcraft** [comment]
You can overwrite [static.php](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/button/static.php) in theme with an empty static.php

**Comment by zenics** [comment]
@moldcraft that doesnt work. It still loads the framework/extensions/shortcodes/shortcodes/button/static/css/styles.css

**Comment by moldcraft** [comment]
I cread on my side

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/button/static.php
```

and it the one from framework is not loaded.

Note that [the same style is also enqueued in another shortcode](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.9/shortcodes/call-to-action/static.php#L15), and you have to overwrite that static.php too
