### ISSUE TITLE
What conditionals can we use to enque styles/scripts for blog ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1370]
I am trying to use blog/static.php override and need a conditionals to enque styles and scripts if I am on a blog, This kinda 
http://wordpress.stackexchange.com/a/141668/67176

but in unyson way like we did it for portfolio 
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/portfolio/static.php#L11-L13

but I get 

    Fatal error: Call to undefined method FW_Extension_Blog::get_settings() 

with 

	$ext_instance = fw()->extensions->get( 'blog' );
	
	if (!is_admin()) {
		
		
		$settings = $ext_instance->get_settings();
		
		if( is_singular( $settings['post_type'] ) || is_tax( $settings['taxonomy_name'] )){
			fw_print('hello');
		}
	}

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/master/class-fw-extension-portfolio.php#L542

**Comment by danyj** [comment]
@moldcraft  right , blog does not ave it ,  https://github.com/ThemeFuse/Unyson/blob/master/framework/extensions/blog/class-fw-extension-blog.php

so do I use this instead or ?

	function thz_is_blog () {
		return ( is_archive() || is_author() || is_category() || is_home() || is_single() || is_tag()) && 'post' == get_post_type();
	}

seems kinda over the top since we use framework already.

**Comment by moldcraft** [comment]
Yes, use your own function.

I am not familiar with blog page (I don't integrate themes) and use very rare `is_*()` functions, so I can't advice you on this.
