### ISSUE TITLE
Theme Integration

### ISSUE THREAD

**Issue by cheungvong** [ThemeFuse/Unyson#1372]
Hi,

I apologize if this is a basic question but I trying to get my theme integrated with some of the option settings by using the example from this article: http://manual.unyson.io/en/latest/options/integrate.html

I am trying to simply change the headings for the theme by using the code below but it's not working. Can someone point me in the right direction?

In my typography.php I have:
`$options = array(

	'headings_font'                => array(
		'label' => __( 'Headings', 'unyson' ),
		'type'  => 'typography',
		'value' => array(
			'size'   => 17,
			'family' => 'Open Sans',
			'style'  => 'regular',
			'color'  => '#333333'
		),
		'desc'  => __( 'Select the font for the headings (h1, h2, h3, h4, h5, h6)',
			'unyson' ),
		'help'  => sprintf( "%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
			__( 'Choose from default and Google fonts.',
				'unyson' ),
			__( 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
				'unyson' )
		),
	),`

In my functions.php I have:
`function _action_theme_wp_print_styles() {
    if (!defined('FW')) return; // prevent fatal error when the framework is not active
	
	$headings_value = fw_get_db_settings_option('headings-font');

    echo '<style type="text/css">'
         . 'h1,h2,h3,h4,h5,h6 { '
         . 'font: '. esc_html($headings_value) .' !important; '
         . '}'
         . '</style>';
}
add_action('wp_print_styles', '_action_theme_wp_print_styles');`

**Comment by moldcraft** [comment]
Hello,

Why you named your file `typography.php`, where and how it is used?

**Comment by cheungvong** [comment]
Hi,
Thanks for the quick response!
In my framework-customizations/theme/options/settings.php I have the following:
`<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}
/**
 * Framework options
 *
 * @var array $options Fill this array with options to generate framework settings form in backend
 */

$options = array(
	fw()->theme->get_options( 'general-settings' ),
	fw()->theme->get_options( 'demo-box' ),
	fw()->theme->get_options( 'style-settings' ),
);
`
In my style-settings.php I have this:
`<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$options = array(
	'styling' => array(
		'title'   => __( 'Styling Options', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			'sub_tab_1' => array(
				'title'   => __( 'Typography', 'unyson' ),
				'type'    => 'tab',
				'options' => array(
					'demo_box2' => array(
						'title'   => __( 'Typography', 'unyson' ),
						'type'    => 'box',
						'options' => array(
					fw()->theme->get_options( 'typography' ),
				),
			
			),
		),
	),
			'sub_tab_2' => array(
				'title'   => __( 'Colors', 'unyson' ),
				'type'    => 'tab',
				'options' => array(
					'demo_box' => array(
						'title'   => __( 'Colors', 'unyson' ),
						'type'    => 'box',
						'options' => array(
							fw()->theme->get_options( 'colors' ),
						),
					),
				),
			),
		),
	),
);`

I have the typography.php to be a separate tab/section. If you have a better way, please let me know.

**Comment by moldcraft** [comment]
![](https://static.md/972850b74d86a209e4f82a79454f844a.png)

**Comment by cheungvong** [comment]
Hi,

Yes, I did realize that after posting but even when those are the same, it does not work. Here is the error I get:

Notice: Array to string conversion in ..../wp-includes/formatting.php on line 1025

**Comment by moldcraft** [comment]
Do `fw_print($headings_value);`

**Comment by cheungvong** [comment]
That printed out the values but did not affect my headings at all. Here is my code now:
**functions.php**
```

function _action_theme_wp_print_styles() {
    if (!defined('FW')) return; // prevent fatal error when the framework is not active
	
	$headings_value = fw_get_db_settings_option('headings_font');

    echo '<style type="text/css">'
         . 'h1,h2,h3,h4,h5,h6 { '
         . 'font: '. fw_print($headings_value) .' !important; '
         . '}'
         . '</style>';
}
add_action('wp_print_styles', '_action_theme_wp_print_styles');
```
**typography.php**
'headings_font'                => array(
		'label' => __( 'Headings', 'unyson' ),
		'type'  => 'typography',
		'value' => array(
			'size'   => 17,
			'family' => 'Open Sans',
			'style'  => 'regular',
			'color'  => '#333333'
		),
		'desc'  => __( 'Select the font for the headings (h1, h2, h3, h4, h5, h6)',
			'unyson' ),
		'help'  => sprintf( "%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
			__( 'Choose from default and Google fonts.',
				'unyson' ),
			__( 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
				'unyson' )
		),
	),

**Comment by moldcraft** [comment]
I meant that `$headings_value` is array but you use it as string...

**Comment by cheungvong** [comment]
I'm sorry, would you mind showing me what the function would look like?

**Comment by moldcraft** [comment]
```php
echo '<style type="text/css">'
     . 'h1,h2,h3,h4,h5,h6 { '
     . 'font: "'. esc_html($headings_value['family']) .'" !important; '
     . '}'
     . '</style>';
```
