### ISSUE TITLE
Page builder / Elements Title

### ISSUE THREAD

**Issue by eightnight** [ThemeFuse/Unyson#1373]
Hi again,

Is there a simple way to add a title row to describe elements in page builder ? (see capture)
![element-title](https://cloud.githubusercontent.com/assets/13215888/13893412/5c6a676c-ed5e-11e5-8aec-c92b52355532.jpg)

Thank you very much

**Comment by moldcraft** [comment]
Hello,

See the `title_template` config parameter http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file

**Comment by eightnight** [comment]
Sorry, 
I didn't get where and how to do this.
Thank you again.

**Comment by eightnight** [comment]
@moldcraft 
Sorry, I didn't get where and how to do this.Thank you for your help.

**Comment by eightnight** [comment]
@moldcraft Sorry, I didn't get where and how to do this.Thank you for your help.

**Comment by moldcraft** [comment]
1. Read http://manual.unyson.io/en/latest/extension/shortcodes/index.html
2. Overwrite the config of any shortcode and add the `title_template` parameter

**Comment by eightnight** [comment]
Sorry again, I didn't get it, even after reading the manual many times.
Should I overwrite the config of this file ? : /wp-content/plugins/unyson/framework/extensions/builder/config.php
I didn't manage to add the title_template parameter either

In advance we thank you for your help.

`/*
        // Title Template examples
        //
        // Syntax:
        // * {{- variable }} - Output with html escape
        // * {{= variable }} - Output raw (without html escape)
        // * {{ if (execute.any(javascript, code)) { console.log('Hi'); } }}
        //
        // Available variables:
        // * title - shortcode title (from config)
        // * o - an object with all shortcode options values
        'title_template' => '{{- title }} Lorem {{- o.option_id }} ipsum {{= o["option-id"] }}',
        'title_template' => '{{- title }}: {{- o.label }}{{ if (o.target == "_blank") { }} <span class="dashicons dashicons-external"></span>{{ } }}',
        */`

**Comment by moldcraft** [comment]
For example, to ovewrite the config for the button shortcode, copy

```
unyson/framework/extensions/shortcodes/shortcodes/button/config.php
```

to

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/button/config.php
```

and add/change parameters

```php
$cfg = array(
    'page_builder' => array(
        // ...

        'title_template' => '{{- title }} Lorem {{- o.option_id }} ipsum {{= o["option-id"] }}',
    )
);
```
