### ISSUE TITLE
403 error when install demo content

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1377]
Hi! My client got this [error](http://prnt.sc/aiuns1) when they install demo content. How can I debug it?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/0969f10c5b6a4c36a8f687b38d5be37fc9e72306/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php#L149-L154

**Comment by moldcraft** [comment]
The server blocked request to your (demo content) site

**Comment by duongancol** [comment]
Ok, Thanks!
