### ISSUE TITLE
Unyson Section background video not working

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#1378]
The unyson section background video is not working. I tried it with the scratch theme also, dont know whats the issue. Please check

**Comment by moldcraft** [comment]
I tested with an youtube video and it works. Can you give me you video link?

**Comment by linjo** [comment]
Yep pls give me

**Comment by moldcraft** [comment]
Sorry?

**Comment by linjo** [comment]
http://www.outcrafter.com/olamwp4/4438-2/
Thats the link. Pls have a look

**Comment by moldcraft** [comment]
[Background.js](https://formstone.it/components/background/) works only with youtube.

Related issues https://github.com/ThemeFuse/Unyson/issues/795 https://github.com/ThemeFuse/Unyson/issues/260

**Comment by linjo** [comment]
This issue is not resolved, Please check this url I've added the video but
its not appearing.

http://www.outcrafter.com/olamwp5/sample-video/

On 23 March 2016 at 18:52, moldcraft <notifications@github.com> wrote:

> Background.js <https://formstone.it/components/background/> works only
> with youtube.
>
> Related issues #795 <https://github.com/ThemeFuse/Unyson/issues/795> #260
> <https://github.com/ThemeFuse/Unyson/issues/260>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1378#issuecomment-200341513>
>



-- 
Linjo Joson

**Comment by moldcraft** [comment]
It works on my side

![](https://static.md/a1646ef1f27c67ac1c9aaa2d6d181af3.png)

Which browser do you use and which version?

**Comment by linjo** [comment]
Google Chrome , version  49.0.2623.87

On 31 March 2016 at 14:58, moldcraft <notifications@github.com> wrote:

> It works on my side
>
>
> <https://camo.githubusercontent.com/9204ac6d2c4b3b282f195f8c3a3f1ec0a1ff7802/68747470733a2f2f7374617469632e6d642f61313634366566316632376336376163316339616161326436643138316166332e706e67>
>
> Which browser do you use and which version?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1378#issuecomment-203847880>
>



-- 
Linjo Joson

**Comment by linjo** [comment]
Oh, its a theme issue,

Please check this link, I just changed the theme

http://www.outcrafter.com/olamwp5/sample-video/

Any idea why this happens?  I see, the <div
class="fs-background-container"></div> div is empty

On 31 March 2016 at 15:45, Linjo Joson <linjo13@gmail.com> wrote:

> Google Chrome , version  49.0.2623.87
>
> On 31 March 2016 at 14:58, moldcraft <notifications@github.com> wrote:
>
>> It works on my side
>>
>>
>> <https://camo.githubusercontent.com/9204ac6d2c4b3b282f195f8c3a3f1ec0a1ff7802/68747470733a2f2f7374617469632e6d642f61313634366566316632376336376163316339616161326436643138316166332e706e67>
>>
>> Which browser do you use and which version?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ThemeFuse/Unyson/issues/1378#issuecomment-203847880>
>>
>
>
>
> --
> Linjo Joson
>



-- 
Linjo Joson
