### ISSUE TITLE
Can we have attributes for tab container li ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1379]
Currently we can only add attributes to the tab container content , 
http://manual.unyson.io/en/latest/options/introduction.html#containers but I need to add class to the tab li since I am working on a post formats switch that should hide/show tabs on click. 

Right now I must work with aria-controls attribute and look for all the ones I need, with one class I cold control them all at once.

**Comment by danyj** [comment]
:+1:

**Comment by moldcraft** [comment]
```php
array(
	'li-attr' => array('foo' => 'bar'), // <---
	'title' => __( 'Awesome Tab', '{domain}' ),
	'type' => 'tab',
	'options' => array(...),
)
```

**Comment by danyj** [comment]
@moldcraft  I saw that one , thnx!
