### ISSUE TITLE
How i can easily add element without wrappers?

### ISSUE THREAD

**Issue by heyas** [ThemeFuse/Unyson#1380]
For exmaple H1, without all this .main-row .container .row .col-xs, etc ?

**Comment by moldcraft** [comment]
Try

```
{theme}/framework-customizations/extensions/shortcodes/extensions/page-builder/config.php
```

```php
$cfg['disable_correction'] = array('shortcode_name');
```

**Comment by heyas** [comment]
Great! Thank you!

**Comment by danyj** [comment]
@moldcraft , this does not work and we still have this issue opened  #799 
I just tested by adding this

    $cfg['disable_correction'] = array('divider','special-heading');


 to 

    extensions/shortcodes/extensions/page-builder/config.php

and to 

    extensions/builder/config.php

    



none of them work 


http://prntscr.com/aj1y7p

outputs 

http://prntscr.com/aj1z2b

 please test and advise of correct overrides path if any of them work.

**Comment by heyas** [comment]
@danyj 
Just add this to your shortcode config.php

$cfg['page_builder'] = array(
    'disable_correction' => (true)
);

How i got this automatical wrapper calls correction in unyson.

**Comment by danyj** [comment]
@heyas, do you have debug on  ?


after adding this do divider/config.php 


	$cfg['page_builder'] = array(
		'disable_correction' => (true)
	);


wrapper is gone but I get warning  

    Warning: No Page Builder tab specified for shortcode: divider in D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\extensions\shortcodes\extensions\page-builder\includes\page-builder\includes\item-types\simple\class-page-builder-simple-item.php on line 101

**Comment by heyas** [comment]
We need @moldcraft advice.

**Comment by danyj** [comment]
ok , my bad , I had already 

     $cfg['page_builder'] ...  //title etc 


above the newly added code , 

so just needed to add it inside the array , not additional one 

http://prntscr.com/aj2xwk

**Comment by danyj** [comment]
Like this 


```
$cfg['page_builder'] = array(
	'disable_correction' => true, 
	'title'         => __('Icon', 'fw'),
	'description'   => __('Add an Icon', 'fw'),
	'tab'           => __('Content Elements', 'fw'),

);
```

**Comment by moldcraft** [comment]
I added in

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/special-heading/config.php
```

```php
$cfg = array(
	'page_builder' => array(
		// ...
		'disable_correction' => true,
	)
);
```

and it works

![](https://static.md/1c7e01d667d2bd72e33c4b6acd165270.png)

when I set it to `false`

![](https://static.md/5166a10edec39df95ee714c01663712c.png)

**Comment by danyj** [comment]
@moldcraft  confirmed yesterday https://github.com/ThemeFuse/Unyson/issues/1380#issuecomment-200535776
