### ISSUE TITLE
Customizer Options and Page ID

### ISSUE THREAD

**Issue by NwpDeveloper** [ThemeFuse/Unyson#1381]
Is it possible to get the page id of the customizer iframe into customizer.php?

**Comment by moldcraft** [comment]
Unyson doesn't offer such possibility/feature. You can try to do hacks like checking current url or current screen.

**Comment by moldcraft** [comment]
Also on Customizer page you can navigate through frontend pages by clicking the links, the iframe is updated (and the url, if I remember correctly) but the customizer elements remain the same and only are hide/show from javascript.

**Comment by moldcraft** [comment]
Maybe you are looking for `active_callback` parameter? https://github.com/ThemeFuse/Unyson/issues/1082
