### ISSUE TITLE
Equal height columns

### ISSUE THREAD

**Issue by Undecided90210** [ThemeFuse/Unyson#1382]
Hi
How can i make the equal height column option?
Maybe like a flex.. 
![columns](https://cloud.githubusercontent.com/assets/17682602/14024464/37d98ee6-f1fa-11e5-9b92-0571a6131e29.png)

**Comment by Undecided90210** [comment]
I create the switch for section, which adds the class .flex

Styles:
`.flex > div {
    display: flex;
    flex-wrap: wrap;
}
.flex > div > div {
    display: flex;
}`

It works, but it is not good:
- It flexing all columns in section, including special headings and other
- Strange adaptation. It fixed by media queries, but.. deprecated

**Comment by llemurya** [comment]
@Undecided90210 you can use this plugin [equalize](https://formstone.it/components/equalize/) to do this stuff.
