### ISSUE TITLE
Pages header styling is overriding visual builder special heading

### ISSUE THREAD

**Issue by ruude3** [ThemeFuse/Unyson#1384]
I have recently started with Unyson / theCore and noticed a strange behaviour. The first site I made, I never changed the settings for the Pages header which, as it says, only apply to _pages created with the default template (default WordPress pages) and not with the Visual Builder_.

In my second site, however, I started with editing these options. However, this results in the styling of a couple of special heading sections which I insert via the Visual builder to be overruled by the Pages header styles.

The pages header options seem to produce the styling inside the _".page .fw-section-image .fw-special-title"_ class, which overrules the visual builder styling inside, for example, the _".tf-sh-278129148db1d65e674b7660fec67f17 .fw-special-title"_ class.

I can't give a link to the site yet, since it's being developed locally, by if necessary, I can put it on a development server.

**Comment by moldcraft** [comment]
Hello,

It's a theme issue not an Unyson problem.

Please report it [here](http://support.themefuse.com/hc/en-us/requests/new).

Cheers

**Comment by andronic90** [comment]
<p>I can't simulate this problem. Can you put it on a development server?</p>
<p>Please report it <a href="http://support.themefuse.com/hc/en-us/requests/new">here</a>.</p>

**Comment by andronic90** [comment]
Finally I can simulate this and make a commit to "The Core".
This will be fixed in : version 1.0.6

**Comment by ruude3** [comment]
Great. Thanks!
