### ISSUE TITLE
[Feature request] Better way to update global (typography) styles

### ISSUE THREAD

**Issue by ruude3** [ThemeFuse/Unyson#1385]
I think Unyson needs a better way to recognized whether a module is using custom styling. Now, If I have changed for example the H2 typography, I need to go into every page and manually reset the styles for all H2 headings. Maybe an extra option could be added to choose whether your special heading module (or other modules that are effected by global styles) should use the global styling or custom styling. (The custom styling button could be hidden, unless the option for custom styling is checked.)

**Comment by moldcraft** [comment]
Hello,

It's a theme issue not an Unyson problem.

Please report it [here](http://support.themefuse.com/hc/en-us/requests/new).

Thanks

**Comment by andronic90** [comment]
The Core custom styling to each shortcode work so :
If you don't save something custom style to the shortcode is applied general styling.
For example you have in page a special heading with h2, and you save only first popup, title and subtitle, but not save the custom styling, all styles is applied from general settings
