### ISSUE TITLE
[suggestion] Option group show borders

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1386]
Using option group tab hides borders between options , here I have 2 switches inside a group  and no border in between. 
![screenshot_6](https://cloud.githubusercontent.com/assets/2340172/14043026/10fcdb6c-f280-11e5-91cb-f3b866963ac5.jpg)

**Comment by danyj** [comment]
so these  
https://github.com/ThemeFuse/Unyson/blob/master/framework/static/css/backend-options.css#L981-L987

would be replaced by 

```
.fw-backend-options-group .fw-backend-option:last-child{
	border-bottom-width: 0; 
}
```

![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/14043137/4acb1bb4-f281-11e5-81bc-7cca05af5aa5.jpg)

**Comment by danyj** [comment]
can we get this in please

**Comment by moldcraft** [comment]
Then why you use the `group` if you need separators?

**Comment by danyj** [comment]
If I need to group set of options, does not mean I dont want the separators to be seen , 
same thing with multi-picker , we have show_borders if we want separators visible

**Comment by danyj** [comment]
And this is exactly how I am using it 
http://prntscr.com/b04p11

to show/hide specific group of options, not to hide separators

**Comment by moldcraft** [comment]
use `['attr']['class'] = 'show-borders';`
