### ISSUE TITLE
Visual Builder: Column inside column

### ISSUE THREAD

**Issue by ruude3** [ThemeFuse/Unyson#1389]
I'm trying to create a layout where I would need to place a column inside a column. I have attached an example layout structure.
![column-inside-column](https://cloud.githubusercontent.com/assets/11229046/14063883/efa145f0-f407-11e5-9395-4ab174308dbb.png)

Unfortunately, I'm not able to do this with the visual builder. Sometimes, I seem to be able to place a column inside another one, but as soon as I edit it, it jumps out and back into the section segment again.

Is this currently possible with the visual builder? If not, I would really like to see this included.

**Comment by duongancol** [comment]
a column in a column is not ready but I think it's the useful feature. :+1:

**Comment by thednp** [comment]
I was expecting this to work like that already.

**Comment by moldcraft** [comment]
Hello,

We will not add this feature, sorry. You can create your own column shortcode which will allow nesting.
