### ISSUE TITLE
Need some help finding  memory leak

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1391]
I am testing the theme live and lately getting memory leak errors on a page with 1 section and 4 counters. The error 

    fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 76 bytes)

is in edit page , I cant access and  it is pointing to 

https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/class-fw-cache.php#L255

Any help on how to trace this is appreciated.

**Comment by moldcraft** [comment]
Are you calling `fw_get_db_post_option()` inside post options file? https://github.com/ThemeFuse/Unyson/blob/v2.5.0/framework/helpers/database.php#L136-L142

**Comment by danyj** [comment]
Yes and probably and I am missing default value but there are so many options that i dont know wich one it is.

**Comment by danyj** [comment]
it would be great if we would have some utility function that runs along and points to the recursion when it happens.

**Comment by moldcraft** [comment]
Add [here](https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/class-fw-cache.php#L254) `fw_print($keys);`

**Comment by danyj** [comment]
was just thinking about it thnx. in the road now will test tonight.

**Comment by danyj** [comment]
OK , git the print but is not showing what particular option is causing it , instead it repeats this part several times 
![screenshot1](https://cloud.githubusercontent.com/assets/2340172/14090219/4d6baab8-f539-11e5-8d1d-501b3601f12e.png)

**Comment by moldcraft** [comment]
Please install xdebug, or enable somehow traces for errors. I tested with this code:

```php
function test() {
	return str_repeat('hello', 1000000) . test();
}

test();
```

and it printed this:

![](https://static.md/dbdaa35a26344760a8ebe19a8e62c682.png)

**Comment by danyj** [comment]
Man this is pain. I downloaded the live install  ( it is on php 5.3.8 ) to my local,  testing on local   5.3.13 and no issues , 
cant install xdebug since it is dedicated box and I would have to interrupt services in order to restart server.  I checked all 46 references of 

    fw_get_db_settings_option


in theme options and all of them have default values set. 
than I removed custom options , bug still there  but now all of a sudden is dying on topmenu.php which is an option set that is used exclusively in theme options , not in post options. So now seems like all options I have are loaded in post options. Going crazy here.

**Comment by danyj** [comment]
@moldcraft  , I thought I am going crazy,  it is not my script , it is some change in this current master and I think it is the inclusion of containers in categories , I might be wrong there but it is this unreleased master for sure. 

When I started testing few days ago I installed unyson trough wp and than downloaded current master and extracted it on live server. 

Now I deleted that install , and reinstalled Unyson trough wp again and the memory leak is gone. Testing further.

**Comment by danyj** [comment]
Ah , that might be my problem there , I just dumped master , and not all other extensions like PB that have been updated in meantime. Testing my local version live.

**Comment by danyj** [comment]
Nope , I used my local version with all latest master/extensions/ updates and the bug is there. Something in this master is messing with it .

**Comment by danyj** [comment]
and xdebug works on 5.4 and up , so I cant trace it right on the live server.

**Comment by moldcraft** [comment]
Try to add `fw_print();` to find where the recursion occurs (hunt the error)

**Comment by moldcraft** [comment]
Or give me admin/ftp access

**Comment by moldcraft** [comment]
`FW_Cache` frees itself if php memory usage reached `memory_limit - 10Mb`. What happened in your case:

1. The framework cached the php memory_limit (64Mb) value and uses it to check if the memory is enough
2. Some script changed the memory_limit to 256Mb
3. The memory kept increasing above 64Mb but FW_Cache didn't knew that now the limit is 256Mb and freed itself on every cache set/get. So no script was able to store something in cache. That's why [this line](https://github.com/ThemeFuse/Unyson/blob/53a6a05f6c4a0c830e5fb28a29d21c7699d47a95/framework/helpers/database.php#L68) failed and it entered in an infinite recursion.

The fix is to not cache memory_limit.
