### ISSUE TITLE
How to create new option for Event page?

### ISSUE THREAD

**Issue by tnthao10** [ThemeFuse/Unyson#1392]
Hi guys,
I followed this Documentation to create new options for event page, but i could not do this
http://manual.unyson.io/en/latest/extension/events/index.html#new-options-on-the-event-edit-page

It showed this error: http://prntscr.com/al0zst
Please help me to solve it.

**Comment by andronic90** [comment]
Try this

```php
function _the_core_filter_fw_ext_events_post_options( $event_options = array() ){
    $event_options["events_tab"]["options"] = array_merge($event_options["events_tab"]["options"],
        array(
            "ticket_price" => array(
                "label" => esc_html__( "Ticket Price", "the-core" ),
                "desc"  => esc_html__( "Enter the ticket price", "the-core" ),
                "type"  => "text",
            ),
        )
    );

    return $event_options;
}
add_filter("fw_ext_events_post_options", "_the_core_filter_fw_ext_events_post_options");
```

**Comment by tnthao10** [comment]
It worked for me, thanks @andronic90

**Comment by tnthao10** [comment]
Hey @andronic90, sorry to bother you.
I have a problem need you reply.

In my fucntions.php file
http://i.imgur.com/43pOlwG.png

This code with fw_print();
http://i.imgur.com/HR1ngo7.png

But when i print this code, not have 'ticket_price' options.
How i can show this options, please help me

**Comment by andronic90** [comment]
Have you saved the event post?

**Comment by andronic90** [comment]
in "framework-customizations\extensions\events\views\single.php"

I have this code
```
$event_options = fw_get_db_post_option($post->ID);
```

and after then I update or save my post in frontend come:

https://static.md/02b44408812b4511ecb2b02a67d91ab3.png

**Comment by tnthao10** [comment]
I saved.
$event_options = fw_get_db_post_option($post->ID);
Great, thank you very much @andronic90
