### ISSUE TITLE
Customizer Switch Label Missing

### ISSUE THREAD

**Issue by NwpDeveloper** [ThemeFuse/Unyson#1393]
Not sure what this rule is for, but it's causing the YES and NO labels for the switch to stack below the switch...so you don't see the labels. 

customize_theme_controls.css 
#customize-theme-controls label {
    width: 100%;
}

**Comment by moldcraft** [comment]
Which theme are you using? `customize_theme_controls.css` comes from Unyson plugin?

**Comment by NwpDeveloper** [comment]
Ah! Ok. Theme issue. 
Closing now.
