### ISSUE TITLE
Parsing $_POST boolean and integers incorrectly

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1394]
I've noticed that you're [completely neglecting](https://github.com/ThemeFuse/Unyson/blob/master/framework/core/components/backend.php#L1165) the fact that potential boolean or integer parameter may even be nested inside an array, even in multiple levels. You're not sending incoming array further to option for checking. In this case, having `_get_value_from_input` implemented like this will break completely this option in the page builder modal.
```
	protected function _get_value_from_input( $option, $input_value ) {
		if ( is_null( $input_value ) ) {
			$input_value = $option['value'];
		}

		return $input_value;
	}
```

While implementing `_get_value_from_input` I was following [manual](http://manual.unyson.io/en/latest/options/create-option-type.html#content) entry for creating an option type. I was not expecting to receive sometimes a boolean or an integer as my `$input_value`.

By the way, why you're even trying to guess what option type **wants** to receive? I understand compatibility implications for this one but would't be a better idea to convert them everytime we receive them? I think everyone working with Unyson will agree with this one.

It is very frustrating to have conditions like that in my code:

```
if ($atts['some_id'] === 1 || $atts['some_id'] === '1')
if ($atts['some_id'] || $atts['some_id'] === 'true')
```

<hr>

If not parsing every boolean we receive, let's think about a way to handle values that **may** be nested inside arrays, at least for the first level of nesting.

I'm thinking about looping through each key in input and sending it one by one to option for testing.
![](https://i.imgur.com/0i1Rr5p.png)

As you can see in my REPL session I'm happily accepting both variants.

**Comment by moldcraft** [comment]
Please test

**Comment by andreiglingeanu** [comment]
@moldcraft Working fine. Thank you. :+1: 

Hopefully, we'll not get compatibility problems.
