### ISSUE TITLE
PHP Error with builder

### ISSUE THREAD

**Issue by ierpe** [ThemeFuse/Unyson#1395]
Hi, I am using the lastest versiosn of Unyson and its extensions, and I get this error : 

```
PHP Catchable fatal error:  Argument 1 passed to FW_Option_Type_Builder::storage_load_recursive() must be of the type array, null given, 
called in ~/www/bicewp/web/app/plugins/unyson/framework/extensions/builder/includes/option-types/builder/extends/class-fw-option-type-builder.php 
on line 589 and defined in ~/www/bicewp/web/app/plugins/unyson/framework/extensions/builder/includes/option-types/builder/extends/class-fw-option-type-builder.php
on line 594, 
referer: http://loc-bicewp.org/fr/faire-un-don/
```

Any idea what's causing this?

**Comment by moldcraft** [comment]
json decode fails [here](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/be46971a9bb401b06cfd503ca4f133f5425fca1d/includes/option-types/builder/extends/class-fw-option-type-builder.php#L589)

Please add [after this line](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/be46971a9bb401b06cfd503ca4f133f5425fca1d/includes/option-types/builder/extends/class-fw-option-type-builder.php#L588) `fw_print($value);` to see why `$value['json']` is broken

**Comment by ierpe** [comment]
```
array
(
    [json] => ''
    [builder_active] => null
)
```

**Comment by moldcraft** [comment]
Please test and let me know if it fixes the error.

**Comment by ierpe** [comment]
Yes it did!
Thanks
