### ISSUE TITLE
How to display maps into single event page?

### ISSUE THREAD

**Issue by tnthao10** [ThemeFuse/Unyson#1397]
Hi guys,
I tried this code in file single.php
http://prntscr.com/aluxg6
and show this
http://prntscr.com/aluwu2
Have something not right here?
This my file path: framework-customizations\extensions\events\views\single.php
Please help me solve it, thank advance.

**Comment by andronic90** [comment]
have you some location in dashboard to this event ?
https://static.md/5ed904843b1e2916d58454fc9bec2a28.png

**Comment by tnthao10** [comment]
Yes, I have
http://prntscr.com/am043e
I don't know why

**Comment by andronic90** [comment]
try this:
`echo fw_ext_events_render_map($post->ID);`

instead of:
`echo fw_ext_events_render_map();`

**Comment by tnthao10** [comment]
Hey bro, i tried this:
`echo fw_ext_events_render_map($post->ID);`
but still not been.

My code:
http://prntscr.com/ammnjd
Print $event_options:
http://prntscr.com/ammnqi
And print fw_ext_events_render_map($post->ID);
http://prntscr.com/ammns1

**Comment by tnthao10** [comment]
Hi! 
Any news?
Thanks!

**Comment by andronic90** [comment]
Hi,
you can try to put some prints in this finction: "fw_ext_events_render_map"

if this didn't help to understand where is the problem you can send your ftp and dashboard details, and I try to resolve this problem. Please send in email and the link from this ticket. Email: unysonthemes[at]gmail.com
