### ISSUE TITLE
[Urgent] The page built by page builder didn't show the content.

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1399]
Hi!
I have a headache issue with page-builder. After migrating to the live site, I edited the shortcode but I saw nothing change to the content. When I checked the revision. It showed below: 
![screen shot 2016-03-30 at 2 29 27 pm](https://cloud.githubusercontent.com/assets/1773011/14134921/58badcf8-f684-11e5-83cd-62e37b133c2c.png)
How could be possible?

**Comment by moldcraft** [comment]
Post content is saved in post meta https://github.com/ThemeFuse/Unyson/issues/838#issuecomment-176792641

> After migrating to the live site

Which tool you used for migration?

**Comment by duongancol** [comment]
I'm using this tool: https://github.com/welaika/wordmove
It worked well before, but today I got this problem. Not sure this happened because of post content saving in post meta. This tool works by migrating the database from localhost to live server. Therefore, the database is the same except for the URL field. 
Let me know if you need other information!

**Comment by moldcraft** [comment]
Try to migrate with Backup & Demo Content extension.

1. Create Content Backup
2. Find the zip in `uploads/fw-backup` and move it to the second site
3. On the second site find the moved backup in list and do Restore

**Comment by duongancol** [comment]
I know but it's not the solution. I want it could be migrated not backup and restore. It worked well before.

**Comment by moldcraft** [comment]
Test this please: Create a page with builder on the live site, do some changes, save it and restore it from revisions. If everything works fine then the problem is in the migration tool you used**.**

**Comment by duongancol** [comment]
I tested and it didn't work fine. Also, there's no Visual page builder button. 
![screen shot 2016-03-30 at 8 34 07 pm](https://cloud.githubusercontent.com/assets/1773011/14143692/cb666588-f6b6-11e5-9aa9-9aed7df508d6.png)

**Comment by moldcraft** [comment]
> there's no Visual page builder button

Try `Ctrl + R` in browser. Or install manually the [PageBuilder](there's no Visual page builder button) extension in `unyson/framework/extensions/shortcodes/extensions/page-builder`

Do you have any javascript errors in console?

**Comment by duongancol** [comment]
Re-installed several time.
Deactivate all other plugins.
The console showed: http://prntscr.com/am0gev
I checked the wp-tinymce but nothing errors
Do you have any ideas?

**Comment by moldcraft** [comment]
The first error in console is the problem. Click on it and inspect server response.

**Comment by duongancol** [comment]
will try and keep you the update

**Comment by duongancol** [comment]
this bug caused by system file.

**Comment by duongancol** [comment]
Thank for your time again!
