### ISSUE TITLE
Themecheck, register_taxonomy(), register_post_type() issue from posts.php, create plugin ?

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#140]
Hi again,

I got these issues from Theme check : 

> REQUIRED: The theme uses the register_taxonomy() function, which is plugin-territory functionality.
REQUIRED: The theme uses the register_post_type() function, which is plugin-territory functionality.

There is the file **inc/posts.php** for this purpose but it is not compatible with Theme check and TF. So I'm wondering if there is a way to fix this with Unyson or I have to create a custom plugin (which will be a copy/past of the posts.php file) and use the TGM class ? 

Thank you,
2F

**Comment by moldcraft** [comment]
Hi,

I (we) don't know the answer for this question.
We are curious what TF will say about that.
Please let us know if you will find the answer/solution for it.

**Comment by 2Fwebd** [comment]
Ok, I'll leave like that and keep you informed about what the reviewer will say. (I do not submit before 2 weeks, but I keep you posted!).

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/151#issuecomment-71635029
