### ISSUE TITLE
Creating an extension based on documentation guide is going nowhere

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1400]
I'm back to development, I want to modify the `Portfolio` extension according to your [documentation](http://manual.unyson.io/en/latest/extensions/introduction.html#content) and I haven't been able to make the extension look into `plugins/my-plugin/extensions/my-extension/posts.php` for the custom-post-type, it only works if the `_action_register_post_type` function is inside the `class-fw-extension-my-extension.php` file.

OR

I would like to be able to create one from scratch based on the documentation, but it's taking me nowhere anyway I go with it. It would also be super helpful to have a `Plugin Includes` similar to the [Theme Includes](https://github.com/ThemeFuse/Theme-Includes).

**Comment by moldcraft** [comment]
> It would also be super helpful to have a Plugin Includes similar to the Theme Includes.

Have you tried to put it plugin?

It should work from any directory, it doesn't use theme related functions, only `dirname(__FILE__)`.

> I haven't been able to make the extension look into plugins/my-plugin/extensions/my-extension/posts.php for the custom-post-type

I created a plugin with an extension in it and `posts.php` works.

[my-plugin.zip](https://github.com/ThemeFuse/Unyson/files/195394/my-plugin.zip)

**Comment by thednp** [comment]
Thank you @moldcraft. I am already at this point. Please take a minute and make a brief Plugin Includes, it would be much helpful for everyone.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Theme-Includes#install

Extract in plugin and include it.

**Comment by thednp** [comment]
OK, I'll start all over again.

**Comment by thednp** [comment]
Update: I did what you mentioned in the previous  comment and getting

`Notice: Use of undefined constant TEMPLATEPATH - assumed 'TEMPLATEPATH' in xampp\htdocs\wp\site\wp-includes\theme.php on line 136`. 

I believe the plugin doesn't need child theme support stuff, I only need to `include_once` every file separatelly without the `self::include_child_first()` method.

**Comment by moldcraft** [comment]
Then change the code to not check for child theme.

**Comment by thednp** [comment]
The Plugin Includes should look like this (I will update this with new findings if any):

```php
class Plugin_Includes
{

	private static $initialized = false;

	public static function init()
	{
		if (self::$initialized) {
			return;
		} else {
			self::$initialized = true;
		}

		/**
		 * Both frontend and backend
		 */
		{
      include dirname( __FILE__ ).'/helpers.php';
      include dirname( __FILE__ ).'/hooks.php';

			add_action('init', array(__CLASS__, '_action_init'));
		}

		/**
		 * Only frontend
		 */
		if (!is_admin()) {
			add_action('wp_enqueue_scripts', array(__CLASS__, '_action_enqueue_scripts'),
				20 // Include later to be able to make wp_dequeue_style|script()
			);
		}
	}

	/**
	 * @internal
	 */
	public static function _action_enqueue_scripts()
	{
		include dirname( __FILE__ ).'/static.php';
	}

	/**
	 * @internal
	 */
	public static function _action_init()
	{
		include dirname( __FILE__ ).'/menus.php';
		include dirname( __FILE__ ).'/posts.php';
	}

}

Plugin_Includes::init();
```
