### ISSUE TITLE
Cannot filter the fw_framework_customizations_dir_rel_path in both theme and plugin?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1401]
I came to a point where I don't know why trying to set `fw_framework_customizations_dir_rel_path` doesn't work. In the plugin's `/includes/framework` folder I've included my `extensions` folder but the extension is not working.

This is for plugin (not working)
```php
function _filter_plugin_framework_dir($rel_path) {
  var_dump('something');
  return '/includes/framework';
}
if ( defined('FW') ) {
  add_filter('fw_framework_customizations_dir_rel_path', '_filter_plugin_framework_dir' );	
}
```

This is for theme (working)
```php
function _filter_theme_framework_dir($rel_path) {
  return '/includes/framework';
}
if ( defined('FW') ) {
  add_filter('fw_framework_customizations_dir_rel_path', '_filter_theme_framework_dir' );	
}
```

**Comment by moldcraft** [comment]
Why you set `if ( defined('FW') ) {` ?

**Comment by thednp** [comment]
So the user don't get any error when framework is not enbled/installed.

**Comment by moldcraft** [comment]
If framework is not enabled that filter will not be executed at all.

**Comment by thednp** [comment]
Ok, it took me a while to get back to the other code, now I commented the `if ( defined('FW') ) {` and I still don't have it working on my plugin.

**Comment by moldcraft** [comment]
> `fw_framework_customizations_dir_rel_path` doesn't work. In the **plugin**'s `/includes/framework` folder

customizations directory is only for theme

* `{parent-theme}/framework-customizations/*`
* `{child-theme}/framework-customizations/*`
