### ISSUE TITLE
Loading extension's post type options for a plugin doesn't work

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1402]
I have a plugin that creates a custom extension, the following structure is used:

```
pluginName/extensions/myExtension/class-fw-extension-myExtension.php
pluginName/extensions/myExtension/static/
pluginName/extensions/myExtension/views/
pluginName/extensions/myExtension/options/posts/myPostType.php
pluginName/languages/etc..
pluginName.php
```

* `class-fw-extension-myExtension.php` defines the custom post type 
* `myPostType.php` defines the options for the above defined custom post type
* the `pluginName.php` defines a new extensions folder

```php
function _dnp_filter_myExtension_pro_extension($locations) {
    $locations[dirname(__FILE__) . '/extensions'] = plugin_dir_url( __FILE__ ) . 'extensions';
    return $locations;
}
add_filter('fw_extensions_locations', '_dnp_filter_myExtension_pro_extension');
```
Is this not supposed to work? I want to be able to use the framework this way and I think alot of people might need this, I personally want to develop a plugin with custom Unyson extensions for sale at CodeCanyon.

**Comment by moldcraft** [comment]
Don't use case sensitive tricks like `myExtension`. Try with `my-extension` and let me know if it works.

----

> myExtension/options/posts/myPostType.php defines the options for the above defined custom post type

Only `{theme}/framework-customization/theme/options/posts/*` are loaded automatically by the framework, `{extension}/options/posts/*` are not, they are available only in extension `$this->get_post_options('post-type');`

**Comment by moldcraft** [comment]
You can use [this filter](https://github.com/ThemeFuse/Unyson/blob/v2.5.0/framework/core/components/theme.php#L116) to change options for a post type.

**Comment by thednp** [comment]
I tried this

```php
public function add_admin_filters() {
  add_filter( 'fw_post_options', array( $this, '_filter_admin_add_post_options' ), 10, 2 );
}
```
and
```php
public function _filter_admin_add_post_options( $options, $post_type ) {
   $options = apply_filters('fw_post_options', $this->get_options('posts/'. $post_type), $post_type);
  return $options;
}
```

Not working.

**Comment by moldcraft** [comment]
Inside filter you apply the same filter? wt_

```php
public function _filter_admin_add_post_options( $options, $post_type ) {
   $options = apply_filters('fw_post_options', $this->get_options('posts/'. $post_type), $post_type);
  return $options;
}
```

**Comment by thednp** [comment]
I don't know what I'm doing really, I am guessing what should work and then hit F5 to see results or errors :)

**Comment by moldcraft** [comment]
Just remove the apply filter

```php
public function _filter_admin_add_post_options( $options, $post_type ) {
    if ($post_type === 'YOUR_POST_TYPE') {
       return $this->get_options('posts/'. $post_type);
    } else {
        return $options;
    }
}
```
