### ISSUE TITLE
Missing style.css on installation package file

### ISSUE THREAD

**Issue by criscasta** [ThemeFuse/Unyson#1408]
Hello there, 

I'm trying to install the theme, but it get an error message stating that style.css is missing. :(

thanks

**Comment by moldcraft** [comment]
Hi,

Which theme?

**Comment by thednp** [comment]
FYI: before install, unpack the zip and see what's inside, if it looks to be a theme it should work, if not, maybe it's a pack of things.

**Comment by andronic90** [comment]
https://help.market.envato.com/hc/en-us/articles/202821510
