### ISSUE TITLE
Visual Builder is not rendering page content/injecting <p></p> into body content

### ISSUE THREAD

**Issue by jsrothwell** [ThemeFuse/Unyson#1409]
We use Unyson for our company website. Its a fairly simple website and doesnt really do anything too technical other than collect emails for us.

Two things I have noticed on our development site recently:

1.- The loop seems to be injecting a `<p></p>` at the beginning and ending of the body content under the header

```html
< div class="entry-content">
		< p>< /p>  <---- These now appear 
< section id="" class="fw-main-row  section__banner">
    < div class="fw-container">
<!--- Snipped --->
< p>< /p>  <---- These now appear
    < /div><!-- .entry-content -->
```

_spaces added to tags because I barely use markdown_

2 - When creating a new page or editing content on an existing page what is created in the editor is replaced by a tag like this 

`< !-- {"length":221,"hash":"160a0f7e9083eb8c4581d484269d59f0"} -->`

Ive tried the following

1.  reverting the pages/posts to previous revisions
2. - deactivating and reactivating Unyson
3. - removing Unyson and reinstalling Unyson
4. - activating another theme and reactivating the site theme
5. - rebuilding the pages 

None  of these have managed to do anything. Im unable at this point to determine if its a problem with Unyson or Wordpress. 

We've looked at this issue https://github.com/ThemeFuse/Unyson/issues/424 but we arent experiencing the same outcome. 

Is this possible to fix within the framework or are we better off cloning the other site and getting rid of the borked one?

**Comment by jsrothwell** [comment]
Ive also reproduced https://github.com/ThemeFuse/Unyson/issues/424 successfully

**Comment by jsrothwell** [comment]
The solution provided here https://wordpress.org/support/topic/all-layout-elements-now-are-inside-a-text-block?replies=12#post-8183238  doesnt work.

The end result is a truncated default editor section and those
< !-- {"length":221,"hash":"160a0f7e9083eb8c4581d484269d59f0"} -->

replacing the content.

**Comment by duongancol** [comment]
The problem maybe comes from here: #838 (comment)
You also need to check the console when open page builder.

**Comment by moldcraft** [comment]
> spaces added to tags because I barely use markdown

This is the correct way to make multi-line code block in markdown, place it between 3 &grave;&grave;&grave; not 1 &grave; (1 is for `inline code`)

```
    ```
    your code here...
    ```
```

> `< !-- {"length":221,"hash":"160a0f7e9083eb8c4581d484269d59f0"} -->`

Post content is saved in post meta https://github.com/ThemeFuse/Unyson/issues/838#issuecomment-176792641

> The loop seems to be injecting a <p></p> at the beginning and ending of the body content under the header

Can you give me the link to your site or admin/ftp access so I can see/inspect the problem myself?

> Ive also reproduced https://github.com/ThemeFuse/Unyson/issues/424 successfully

Please give us the exact steps to reproduce the problem on our localhost.

**Comment by jsrothwell** [comment]
It turns out the specific wordpress instance was having trouble with the page builder extension and was loading the loop as a text block or not loading the loop at all.
