### ISSUE TITLE
How to use shortcode(store in page content) and avoid post meta using page builder

### ISSUE THREAD

**Issue by mianmajid** [ThemeFuse/Unyson#141]
Hello,
thanks for providing page builder plugin, I am using using it and checked it stores all data in post meta with name "fw_options" is it possible to perform content management by shortcodes in text editor(post/page content field) instead of post meta?

Thank you for your great effort.

**Comment by MoBadawy** [comment]
I think they will released ShortCodes extension in a few days 
https://trello.com/c/CX8emlPS/50-shortcodes

**Comment by mianmajid** [comment]
I think that is drop down shortcode list, I want page builder to convert into shortcodes like WP Bakery Visual Editor, or Avada theme Fusion Builder.

**Comment by 2Fwebd** [comment]
Like that : 
![edit_page_ _starry_ _wordpress](https://cloud.githubusercontent.com/assets/5446124/5602723/cd35e122-9361-11e4-8316-3f53088184ad.png)
?? For what purpose, I don't get it

**Comment by mianmajid** [comment]
Perfect, I want like that, is it possible now a days? or should I should I change code for that purpose?
currently this is storing as serialized array 
>a:2:{i:0;s:0:"";s:12:"page-builder";a:4:{s:4:"json";s:2789:"[{"type":"section","atts":{"is_fullwidth":false,"background_color":"","background_image":{"type":"custom","custom":"5","predefined":"","data":{"icon":"http:\/\/192.168.1.100:85\/wp-content\/uploads\/2014\/04\/picture1.jpg","css":{"background-image":"url(\"http:\/\/192.168.1.100:85\/wp-content\/uploads\/2014\/04\/picture1.jpg\")"}}},"video":""},"_items":[{"type":"simple","shortcode":"button","atts":{"label":"Submit","link":"#","target":"_self","color":"green"}},{"type":"simple","shortcode":"text_block","atts":{"text":""}},{"type":"simple","shortcode":"tabs","atts":{"tabs":[{"tab_title":"Tab 1","tab_content":"this is content of tab 1"},{"tab_title":"Tab 2","tab_content":"content "}]}}]},{"type":"section","atts":{"is_fullwidth":false,"background_color":"","background_image":"","video":""},"_items":[{"type":"column","width":"1_3","_items":[{"type":"simple","shortcode":"text_block","atts":{"text":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius erat sit amet metus faucibus consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ultricies ultrices est, vitae tempor nisi varius non. Fusce venenatis, magna et semper rutrum, ligula leo volutpat leo, suscipit lacinia elit ante at turpis. In at augue gravida risus accumsan elementum nec eget ante. Aenean dignissim pretium libero tincidunt vestibulum. Aliquam a erat sit amet lorem ornare consectetur. Proin consectetur, erat in ornare tristique, diam lectus eleifend odio, ut mattis tortor arcu ut orci. Nulla sed iaculis nibh. Ut at dui diam. Quisque varius nisl tortor<\/p>\n"}}]},{"type":"column","width":"1_3","_items":[{"type":"simple","shortcode":"text_block","atts":{"text":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius erat sit amet metus faucibus consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ultricies ultrices est, vitae tempor nisi varius non. Fusce venenatis, magna et semper rutrum, ligula leo volutpat leo, suscipit lacinia elit ante at turpis. In at augue gravida risus accumsan elementum nec eget ante. Aenean dignissim pretium libero tincidunt vestibulum. Aliquam a erat sit amet lorem ornare consectetur. Proin consectetur, erat in ornare tristique, diam lectus eleifend odio, ut mattis tortor arcu ut orci. Nulla sed iaculis nibh. Ut at dui diam. Quisque varius nisl tortor<\/p>\n"}}]},{"type":"column","width":"1_3","_items":[{"type":"simple","shortcode":"text_block","atts":{"text":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius erat sit amet metus faucibus consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ultricies ultrices est,<\/p>\n"}}]}]}]";s:14:"corrected_json";s:3092:"[{"type":"section","atts":{"is_fullwidth":false,"background_color":"","background_image":{"type":"custom","custom":"5","predefined":"","data":{"icon":"http:\/\/192.168.1.100:85\/wp-content\/uploads\/2014\/04\/picture1.jpg","css":{"background-image":"url(\"http:\/\/192.168.1.100:85\/wp-content\/uploads\/2014\/04\/picture1.jpg\")"}}},"video":"","auto_generated":false,"first_in_builder":true},"_items":[{"_items":[{"width":"1_1","_items":[{"type":"simple","shortcode":"button","atts":{"label":"Submit","link":"#","target":"_self","color":"green"}}],"type":"column"}],"type":"row"},{"_items":[{"width":"1_1","_items":[{"type":"simple","shortcode":"text_block","atts":{"text":""}}],"type":"column"}],"type":"row"},{"_items":[{"width":"1_1","_items":[{"type":"simple","shortcode":"tabs","atts":{"tabs":[{"tab_title":"Tab 1","tab_content":"this is content of tab 1"},{"tab_title":"Tab 2","tab_content":"content "}]}}],"type":"column"}],"type":"row"}]},{"type":"section","atts":{"is_fullwidth":false,"background_color":"","background_image":"","video":"","auto_generated":false},"_items":[{"_items":[{"type":"column","width":"1_3","_items":[{"type":"simple","shortcode":"text_block","atts":{"text":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius erat sit amet metus faucibus consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ultricies ultrices est, vitae tempor nisi varius non. Fusce venenatis, magna et semper rutrum, ligula leo volutpat leo, suscipit lacinia elit ante at turpis. In at augue gravida risus accumsan elementum nec eget ante. Aenean dignissim pretium libero tincidunt vestibulum. Aliquam a erat sit amet lorem ornare consectetur. Proin consectetur, erat in ornare tristique, diam lectus eleifend odio, ut mattis tortor arcu ut orci. Nulla sed iaculis nibh. Ut at dui diam. Quisque varius nisl tortor<\/p>\n"}}]},{"type":"column","width":"1_3","_items":[{"type":"simple","shortcode":"text_block","atts":{"text":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius erat sit amet metus faucibus consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ultricies ultrices est, vitae tempor nisi varius non. Fusce venenatis, magna et semper rutrum, ligula leo volutpat leo, suscipit lacinia elit ante at turpis. In at augue gravida risus accumsan elementum nec eget ante. Aenean dignissim pretium libero tincidunt vestibulum. Aliquam a erat sit amet lorem ornare consectetur. Proin consectetur, erat in ornare tristique, diam lectus eleifend odio, ut mattis tortor arcu ut orci. Nulla sed iaculis nibh. Ut at dui diam. Quisque varius nisl tortor<\/p>\n"}}]},{"type":"column","width":"1_3","_items":[{"type":"simple","shortcode":"text_block","atts":{"text":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius erat sit amet metus faucibus consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ultricies ultrices est,<\/p>\n"}}]}],"type":"row"}]}]";s:18:"shortcode_notation";s:3422:"[section is_fullwidth="" background_color="" background_image="{&quot;type&quot;:&quot;custom&quot;,&quot;custom&quot;:&quot;5&quot;,&quot;predefined&quot;:&quot;&quot;,&quot;data&quot;:{&quot;icon&quot;:&quot;http:\/\/192.168.1.100:85\/wp-content\/uploads\/2014\/04\/picture1.jpg&quot;,&quot;css&quot;:{&quot;background-image&quot;:&quot;url(\&quot;http:\/\/192.168.1.100:85\/wp-content\/uploads\/2014\/04\/picture1.jpg\&quot;)&quot;}}}" video="" auto_generated="" first_in_builder="1" _array_keys="{&quot;background_image&quot;:&quot;background_image&quot;}" _made_with_builder="true"][row][column width="1_1" _made_with_builder="true"][button label="Submit" link="#" target="_self" color="green" _made_with_builder="true"][/button][/column][/row][row][column width="1_1" _made_with_builder="true"][text_block text="" _made_with_builder="true"][/text_block][/column][/row][row][column width="1_1" _made_with_builder="true"][tabs tabs="&#91;{&quot;tab_title&quot;:&quot;Tab 1&quot;,&quot;tab_content&quot;:&quot;this is content of tab 1&quot;},{&quot;tab_title&quot;:&quot;Tab 2&quot;,&quot;tab_content&quot;:&quot;content &quot;}&#93;" _array_keys="{&quot;tabs&quot;:&quot;tabs&quot;}" _made_with_builder="true"][/tabs][/column][/row][/section][section is_fullwidth="" background_color="" background_image="" video="" auto_generated="" _made_with_builder="true"][row][column width="1_3" _made_with_builder="true"][text_block text="&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius erat sit amet metus faucibus consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ultricies ultrices est, vitae tempor nisi varius non. Fusce venenatis, magna et semper rutrum, ligula leo volutpat leo, suscipit lacinia elit ante at turpis. In at augue gravida risus accumsan elementum nec eget ante. Aenean dignissim pretium libero tincidunt vestibulum. Aliquam a erat sit amet lorem ornare consectetur. Proin consectetur, erat in ornare tristique, diam lectus eleifend odio, ut mattis tortor arcu ut orci. Nulla sed iaculis nibh. Ut at dui diam. Quisque varius nisl tortor&lt;/p&gt;
" _made_with_builder="true"][/text_block][/column][column width="1_3" _made_with_builder="true"][text_block text="&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius erat sit amet metus faucibus consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ultricies ultrices est, vitae tempor nisi varius non. Fusce venenatis, magna et semper rutrum, ligula leo volutpat leo, suscipit lacinia elit ante at turpis. In at augue gravida risus accumsan elementum nec eget ante. Aenean dignissim pretium libero tincidunt vestibulum. Aliquam a erat sit amet lorem ornare consectetur. Proin consectetur, erat in ornare tristique, diam lectus eleifend odio, ut mattis tortor arcu ut orci. Nulla sed iaculis nibh. Ut at dui diam. Quisque varius nisl tortor&lt;/p&gt;
" _made_with_builder="true"][/text_block][/column][column width="1_3" _made_with_builder="true"][text_block text="&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius erat sit amet metus faucibus consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ultricies ultrices est,&lt;/p&gt;
" _made_with_builder="true"][/text_block][/column][/row][/section]";s:14:"builder_active";b:1;}}

**Comment by 2Fwebd** [comment]
Well, I'm not the guy who developed this framework, maybe @moldcraft will have a more professional reply with explanations. But to get that result **just disable the extension from Unyson page in WP**. It seems that at the opposite of the Visual Composer the shortcodes generated are hidden when the extension is enabled, which is a good idea in fact! :)

**Comment by rockalife** [comment]
Hi @mianmajid,

When saving or updating the page from the dashboard the page builder extension generates shortcode notation (like the one that @2Fwebd showed) in the `post_content` column of the `wp_posts` database table.

You can check it out yourself, just create a post with the page builder, save it and look up it's `post_content` by the post id in the database.

Can you please share your use case, why does it matter how and where does the page builder save it's data ?

**Comment by mianmajid** [comment]
![unyson-pagebuilder](https://cloud.githubusercontent.com/assets/10381371/5627971/3e533a96-95c2-11e4-813b-4a5c7c9c63f0.jpg)

Hello, thanks for replying.
I am sharing screenshot of wp_posts and wp_postmeta table.
You are right "rockalife" it is saving content into wp_posts, but the the saving json encoded content into wp_postmeta I think that is Database burden, what you comment please?

**Comment by rockalife** [comment]
Hi @mianmajid,

Yes, you are right. Don't know if you need to know the implementation details. but basically the page builder that you see in the dashboard is just a regular option type that is loaded from an extension (the [PageBuilder extension](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension) ), and it saves
it's data like all the other option types in the `wp_postmeta` table. When saving or updating  the page the extension checks if it needs to replace the `post_content` filed from the `wp_posts` table with the value that was saved into `wp_postmeta`.

I know this is confusing, but the developers don't deal with this stuff, they create their shortcodes and the framework takes care of the rest (puts them into the builder, deals with their options, saves thes, etc.)

**Comment by moldcraft** [comment]
The original data (builder json and shortcode notation) is stored in post meta, post content contains a copy of that shortcode notation. The post meta is generated on post save and remains untouched, [the post content can be changed](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/a663c51ae474a5fcb35ce8537db1f79c9bcb806c/class-fw-extension-page-builder.php#L167-L193).

Also [post content can be broke on post save by wordpress](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/a663c51ae474a5fcb35ce8537db1f79c9bcb806c/class-fw-extension-page-builder.php#L200-L221) and fortunately we have the original data in post meta so we can recover/fix the post content.
