### ISSUE TITLE
loading unyson shortcodes stylesheets

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#1410]
I found that the stylesheet for the Buttons shortcode is loaded in wp_head in my homepage but is loaded in wp_footer in other pages. How is this possible? I need it to get loaded always in wp_head

**Comment by moldcraft** [comment]
[This was fixed](https://github.com/ThemeFuse/Unyson/issues/1316) and we will release a new Shortcodes extension version soon. Keep the eye on [Extensions Approval](https://github.com/ThemeFuse/Unyson-Extensions-Approval).

**Comment by mbtocalli** [comment]
thanks!!
