### ISSUE TITLE
Unyson Version 3!

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1411]
As you may have noticed, almost all Unyson core developers left the project. The reason of this is that they all have been working on the new version of Unyson 3.0, which has a lot of improvements and 4 new awesome extensions: MegaMenu 2.0, PageBuilder 2.0, FullBuilder 1.0 and UnsyonAPI 1.0. Also Scratch Theme 2.0.

Unyson 3.0 is compatible with current 2.x version and you can easy migrate your themes!

You can find all the details here http://unyson.io/v3/

**Comment by danyj** [comment]
U got me going! :)

**Comment by thednp** [comment]
I am expecting a v3 with "native" Plugin support as well. :D

**Comment by Shahab2905** [comment]
Keep Calm ;) and expect awesome stuff from Unyson team

**Comment by danyj** [comment]
While we are at it , this is how my wife gave me my mornings coffee, 
http://prntscr.com/ams6x1

**Comment by duongancol** [comment]
You guys could check my latest theme with unyson ver 3 [here](https://ssl.gstatic.com/ui/v1/icons/mail/drpmc4501.gif)
