### ISSUE TITLE
add options (usermeta) to users 

### ISSUE THREAD

**Issue by alealeale** [ThemeFuse/Unyson#1412]
First of all thank you so much for your amazing work.. unyson rules! 
I would like to know if there's a way to add options (usermeta) (type: wp-editor, upload, textarea) to users 

maybe merging this form tutorial you did:
http://sourcebox.io/d3fe4eed474c30ec71edef7a6a4f039c/php

with this:
http://justintadlock.com/archives/2009/09/10/adding-and-using-custom-user-profile-fields

Thanks a lot

**Comment by moldcraft** [comment]
Hello,

We are glad you like it!

In brief:

1. Use an action to print options on user page
2. Use an action to catch user page form submit and save the values somewhere

**Comment by alealeale** [comment]
ok, thanks.. and how to grab the saved data and put them in the printed options when the user page is loaded?

**Comment by moldcraft** [comment]
http://sourcebox.io/d3fe4eed474c30ec71edef7a6a4f039c/php Line 158
