### ISSUE TITLE
[question] Use population methods for other option types like select or radio?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1413]
I would probably find that it's not supported. Any way to make it possible thought?

**Comment by moldcraft** [comment]
Hello,

The developer who created the population-methods extension is no longer in our team. I know for sure that it is not supported. But I can't tell if it's possible. You can inspect the extension and try to figure our how to implement it.

**Comment by thednp** [comment]
Yea, like usual, create a custom option. I was hoping the population methods apply to any radio, select, multi-select, etc type of options. Thanks for the reply nevertheless.
