### ISSUE TITLE
Display multi-select category values

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#1414]
I'm creating a new shortcode for the page builder. In `options.php` I use:

```php
$options = array(
	'category' => array(
		'type'  => 'multi-select',
		'label' => __('Filter Category', 'webiliaria'),
		'desc'    => __('Select categories to be shown, choose none to show all', 'webiliaria'),
		'population' => 'taxonomy',
		'source' => 'category',
		'prepopulate' => 9999,
		'limit' => 9999,
	),
);
```

But then I'm not able to get the categories IDs in the `views/view.php` to use them in the query.
I think `fw_get_db_term_option` is the way to go, but I can't make it.
In the meanwhile, I solved it using `implode(', ', $atts['category'])`

**Comment by moldcraft** [comment]
I added in `{theme}\framework-customizations\extensions\shortcodes\shortcodes\button\options.php`:

```php
'test' => array(
    'type'  => 'multi-select',
    'label' => __('Filter Category', 'webiliaria'),
    'desc'    => __('Select categories to be shown, choose none to show all', 'webiliaria'),
    'population' => 'taxonomy',
    'source' => 'category',
    'prepopulate' => 9999,
    'limit' => 9999,
),
```

Then added in `{theme}\framework-customizations\extensions\shortcodes\shortcodes\button\views\view.php`:

```php
fw_print($atts);
```

And on frontend I got:

```
array
(
    ...
    [test] => array
    (
        [0] => '1' // Uncategorized
    )
)
```
