### ISSUE TITLE
About Customize Everything (styling)

### ISSUE THREAD

**Issue by kaxigt** [ThemeFuse/Unyson#1415]
That doesn't showed up in my admin area (appearance). I have search every link in dashboard but i can't find it. It doesn't appear. I'm using Unyson (latest) as a plugin and the lastest version WP. What has gone wrong?

Edit/ In "read me" doc this function isn't integrate but it is in your video presentation. So, is it on "hold" or have i missed something?

kindly Lillan

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/874
