### ISSUE TITLE
[question] Can the addable-box be made to support duplicate?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1418]
If yes, please briefly guide me on how to achieve this. I haven't found anything on the issues or documentation about this. I know this option supports custom controls, I was hoping I could easily achieve this by using the framework's classes and methods.

**Comment by moldcraft** [comment]
At the moment it's not possible. I will make it possible soon.

**Comment by thednp** [comment]
Awesome, can't wait for it :)

**Comment by moldcraft** [comment]
Add in `{theme}/framework-customizations/theme/options/posts/post.php`:

```php
'test' => array(
	'type' => 'addable-box',
	'box-options' => array(
		'option_1' => array( 'type' => 'text' ),
		'option_2' => array( 'type' => 'textarea' ),
	),
	'box-controls' => array(
		'clone' => '<small class="dashicons dashicons-admin-page" title="'. esc_attr__('Clone', 'fw') .'"></small>',
	),
),
```

Open edit post page and execute in browser console:

```js
jQuery('#fw-option-test').on('fw:option-type:addable-box:control:click', function(e, data){
    if (data.controlId != 'clone') {
        return;
    }

    var $option = data.box.$box.closest('.fw-option-type-addable-box');

    // Create a new box
    $option.find('> .fw-option-boxes-controls .fw-option-boxes-add-button').trigger('click');

    var $newBoxOptions = $option.find('> .fw-option-boxes > .fw-option-box:last-child .fw-option-box-options:first');

    // I don't know how to copy values from data.box.$options to $newBoxOptions ...
    console.log(data.box.$options, $newBoxOptions);
});
```

Add a box then click on clone

**Comment by thednp** [comment]
The thing is: I added this custom control
```php
'duplicate' => '<small class="dashicons dashicons-admin-page item-clone" title="'.__('Duplicate','fw').'"></small>',
```
it does duplicate the entire thing, but it's hidden, please try perhaps I'm wrong.

**Comment by moldcraft** [comment]
Sorry, I forgot to make [this commit](https://github.com/ThemeFuse/Unyson/commit/e89b2dc46d5123cbab919668619ff4399a71d7f4) (it is required for my example above to work).

**Comment by thednp** [comment]
Unfortunately this doesn't work, downloaded latest code from Git and according to the above instructions.

**Comment by moldcraft** [comment]
What exactly doesn't work?

**Comment by thednp** [comment]
After executing the above jQuery script, clicking on the new action icon nothing happens.

**Comment by moldcraft** [comment]
I just tested the code and it works. Do you have latest Unyson dev version?

**Comment by danyj** [comment]
@moldcraft  can you make this for addable popup ?

**Comment by danyj** [comment]
tested this and  the duplicate button works , but is not duplicating the options, it just adds new box with empty options 


@thednp , if your option name is different change the id 


`jQuery('#fw-option-testaddable')`

```
jQuery('#fw-option-testaddable').on('fw:option-type:addable-box:control:click', function(e, data){
    if (data.controlId != 'clone') {
        return;
    }

    var $option = data.box.$box.closest('.fw-option-type-addable-box');

    // Create a new box
    $option.find('> .fw-option-boxes-controls .fw-option-boxes-add-button').trigger('click');

    var $newBoxOptions = $option.find('> .fw-option-boxes > .fw-option-box:last-child .fw-option-box-options:first');

    // I don't know how to copy values from data.box.$options to $newBoxOptions ...
    console.log(data.box.$options, $newBoxOptions);
});
```

**Comment by moldcraft** [comment]
> but is not duplicating the options

Note that I wrote in code comment that I don't know how to implement the options copy

**Comment by danyj** [comment]
ups , did not read it , sorry

**Comment by thednp** [comment]
@moldcraft I have latest SVN version from Github master repository. 

@danyj  BUT copying values is important.

**Comment by danyj** [comment]
add console code before you click on add button , not after

**Comment by thednp** [comment]
Yes man, I did that in the first test.

**Comment by thednp** [comment]
@moldcraft do we have any news on this feature, or at least some plans?

**Comment by moldcraft** [comment]
No news, I have no idea how to make the copy.

**Comment by thednp** [comment]
The page builder has this function. I will investigate this and let you know if I found any solution, meanwhile, everybody else feel free to jump in with any suggestions.

**Comment by danyj** [comment]
@thednp  https://github.com/ThemeFuse/Unyson/pull/2557

**Comment by thednp** [comment]
Is this going to get included with the next update?

**Comment by danyj** [comment]
@thednp  if you mean this , https://github.com/ThemeFuse/Unyson/issues/1419

I am not sure , needs to be approved by the team first. 

I have been working with it the hole day and LOVE IT!

**Comment by danyj** [comment]
As for addable box ,   is not even close to the code of popup but I managed to create clones with options and saves well. Did not check limits or anything else , since the code is crude 


test it please 

option


```

'addsomething' => array(
    'type'  => 'addable-box',
    'value' => array(
        array(
            'option_1' => 'value 1',
            'option_2' => 'value 2',
        ),
        // ...
    ),
    'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
    'label' => __('Label', '{domain}'),
    'desc'  => __('Description', '{domain}'),
    'help'  => __('Help tip', '{domain}'),
    'box-options' => array(
        'option_1' => array( 'type' => 'text' ),
        'option_2' => array( 'type' => 'textarea' ),
    ),
    'template' => 'Hello {{- option_1 }}', // box title
    'box-controls' => array(
        'clone' => '<small class="dashicons dashicons-admin-page" title="'. esc_attr__('Clone', 'fw') .'"></small>',
    ),
    'limit' => 0, // limit the number of boxes that can be added
    'add-button-text' => __('Add', '{domain}'),
    'sortable' => true,
),

```

right  here https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/addable-box/static/js/scripts.js#L229 

add 



		/** Clone button */
		$elements.on('fw:option-type:addable-box:control:click', function(e, data){
				
				if (data.controlId != 'clone') {
					return;
				}
				
				var $name		= $elements.find('.fw-option-type-hidden').attr('name');
				var $button   	= $elements.find('.fw-option-boxes-add-button');
				var $increment 	= parseInt($button.attr('data-increment'));
				var $clonedBox 	= data.box.$box.closest('.fw-option-box').clone(true, true);
				var $prefix		= $($clonedBox).attr('data-name-prefix');
				var $newprefix  = $name + '['+ $increment +']';
				
				$($clonedBox).find(':input').each(function() {
					this.name = this.name.replace($prefix,$newprefix);
				});
				
				$clonedBox.addClass('fw-animation-zoom-in');
				data.box.$box.closest('.fw-option-boxes').append($clonedBox);
		
				setTimeout(function(){
					$clonedBox.removeClass('fw-animation-zoom-in');
					$button.attr('data-increment', $increment + 1);
				}, 300);
		
		});



@andreiglingeanu   the idea is to clone the actual box with events and update the array increment.  
you might know better way of doing this than what I did above.

**Comment by thednp** [comment]
So is this feature going to be included with future updates or we can hack our themes ourselves?

**Comment by GheorgheP** [comment]
We will include this feature in future updates. Sure I cannot guarantee that this will be soon, but we will add this. Now @andreiglingeanu is working hard on a new option types improvement, so after that we'll be able implement all new features.
