### ISSUE TITLE
Extend menu functionalities with Mega menu extension, PHP notice

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#142]
Hello,

For the menu in my theme, I've few requirements : 
* Divided in 2 menus (left and right side so 2 locations in order to have the logo in the middle)
* Mega Menu and submenu compatibility
* Ready for icons
* Use the description for subtitle in the menu

Thanks to the mega menu, I was able to do all quite easily (I make several little changes on the extension to change the location, add the description...) But it works well, the only issue is : I got this PHP notice : 
> NOTICE: wp-content/themes/starry/framework-customizations/extensions/megamenu/views/item-link.php:17 - Undefined index: class
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/starry/index.php'), get_header, locate_template, load_template, require_once('/themes/starry/header.php'), wp_nav_menu, walk_nav_menu_tree, call_user_func_array, Walker->walk, FW_Theme_Menu_Walker->display_element, FW_Theme_Menu_Walker->display_element, call_user_func_array, FW_Theme_Menu_Walker->start_el, FW_Extension_Megamenu->render_str, FW_Extension->render_view, fw_render_view, require('/themes/starry/framework-customizations/extensions/megamenu/views/item-link.php')

After few hours I can  say it comes from : **item/link.php** ->  `$attributes['class'] = trim(@$attributes['class'] . " $icon");`

Do you have any idea, how to fix this ? Or maybe an other way to do this.

Thank you

**Comment by vbarbarosh** [comment]
Hi 2Fwebd.

Concerning PHP Notice. It is strange since @ should suppress it. Try to replace the line with the following:

```php
$attributes['class'] = trim((isset($attributes['class']) ? $attributes['class'] : '') . " $icon");
```

What about your requirements? Do you have some questions about them?

**Comment by 2Fwebd** [comment]
Hello,
Thank you very much !! It works perfectly !!!

**Comment by moldcraft** [comment]
So it seems that on some servers the suppress `@` doesn't work. Maybe it's better to avoid it.

**Comment by vbarbarosh** [comment]
I have tried to find an explanation for this behavior. It seems that standard error handler is replaced. And this replacement is not well written. Instead of taking into account error_reporting variable it ignores it.

[Error Control Operators](http://php.net/manual/en/language.operators.errorcontrol.php):
> If you have set a custom error handler function with set_error_handler() then it will still get called, but this custom error handler can (and should) call error_reporting() which will return 0 when the call that triggered the error was preceded by an @.
