### ISSUE TITLE
Change theme admin menu

### ISSUE THREAD

**Issue by wontone18** [ThemeFuse/Unyson#1420]
i want to change the theme menu apperance -> Theme setting with my own customise theme menu like 'Theme setting'

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/v2.5.1/framework/core/components/backend.php#L510-L514

**Comment by wontone18** [comment]
hi 

thanks for the code, yes i had used it earlier to change the menu little bit and also reorder the wp admin menu.

one quick question, its having TGM plugin, i have included this
array(
			'name'=>'maintenance',
			'slug'=>'maintenance',
			'required'=>false,
			'is_automatic'=>true,
			'force_activation'=>true,
			),
			

its installed the maintenance mode plugin but after its installation in the maintenance section i am getting a error

 Warning: Missing argument 2 for _FW_Component_Backend::_action_create_post_meta_boxes() in D:\web\htdocs\jb-theme\wp-content\plugins\unyson\framework\core\components\backend.php on line 662

**Comment by moldcraft** [comment]
The `add_meta_boxes` action has [2 required parameters](https://github.com/WordPress/WordPress/blob/4.4.2/wp-admin/edit-form-advanced.php#L323), but [the plugin provides only one parameter](https://plugins.trac.wordpress.org/browser/maintenance/tags/2.7.1/includes/admin.php#L15)

**Comment by wontone18** [comment]
how to resolve this?

**Comment by moldcraft** [comment]
They must solve it. Give them [this link](https://github.com/ThemeFuse/Unyson/issues/1420#issuecomment-206417822)
