### ISSUE TITLE
Import to custom fields

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1421]
Hello,

A while ago I came across the 'save-in-separate-meta' option for custom fields. This works like a charm when querying. 

But I've run into the same problem twice this week using WP All Import and Frontend Uploader. When uploading a value to the custom field in the database with either of these plugins, I can see it there. But when viewing the post associated with the custom field value (both frontend and backend), the value doesn't show. 

When I view the post on the backend and save the post, the value still doesn't appear on the backend or frontend. And, the value disappears in the database.

Is there a way to make this work? Thanks in advance!
-Kevin

**Comment by moldcraft** [comment]
> using WP All Import and Frontend Uploader

Sorry we don't have time to provide the compatibility with all plugins.

----

P.S. `save-in-separate-meta` is deprecated, please use `fw-storage` https://github.com/ThemeFuse/Unyson/issues/1388#issuecomment-202347603

----

We will inspect this issue, but I can't tell when. You can inspect it yourself by finding why the imported value is different than the value on the exported site.

**Comment by noesteijver** [comment]
We've fixed this with a custom PHP solution. Thanks anyway!
