### ISSUE TITLE
Cannot Install theme compatible extensions

### ISSUE THREAD

**Issue by renatoalcoforado** [ThemeFuse/Unyson#1422]
Hi, plz help me

I cannot install the compatible extensions on Unyson.
All extensions I try to install is with this same mistake.

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (couldn't connect to host)

**Comment by moldcraft** [comment]
1. Which hosting are you using?
2. Please contact hosting support and tell them to allow requestes to http://github-api-cache.unyson.io/repos/themefuse/unyson/releases/latest

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1691#issuecomment-229382498
