### ISSUE TITLE
Cannot set blank custom background on columns

### ISSUE THREAD

**Issue by webmissioncontrol** [ThemeFuse/Unyson#1423]
Since the latest update, whenever a column is saved with a blank value for the custom background color, it seems to save as #000000 or #FFFFFF and can't be cleared.

**Comment by moldcraft** [comment]
Hello,

The input is color-picker or rgba-color-picker?

**Comment by webmissioncontrol** [comment]
Hi, sorry for the slow response. The picker that comes up is the RGBA picker with the alpha slider.
