### ISSUE TITLE
Cannot center Pricing Table with only one price

### ISSUE THREAD

**Issue by HashtagHustler** [ThemeFuse/Unyson#1424]
Hey guys, love the product, however when using the pricing table, if I use less than 3 prices in the Pricing Table element, everything gets off center. I have tried using different elements to break the page up etc, like using text to off set the price table so it wouldn't matter but it still looks off.
![screen shot 2016-04-05 at 4 14 32 pm](https://cloud.githubusercontent.com/assets/12128335/14301054/837dfe9c-fb49-11e5-8ed1-cdd5f39480f5.png)

I can't seem to adjust the price so account for having only 1 or 2 options, it forever assumes I will have more.

**Comment by moldcraft** [comment]
Hello,

Which theme are you using?

**Comment by HashtagHustler** [comment]
Oh sorry, Obsession

**Comment by moldcraft** [comment]
Have you asked theme author abut this problem?

**Comment by HashtagHustler** [comment]
No... I was under the impression I was supposed to contact you guys about these problems, It seems to be part of the Theme Builder feature of Unysom?

**Comment by moldcraft** [comment]
I am not familiar with the pricing table shortcode and can't tell if the problem is in it or on theme side.

Maybe somebody who already created themes and knows how it works can answer this question.

**Comment by andronic90** [comment]
I try the pricing table on default wordpress theme and is centered: https://static.md/59db98e0c92e496a332a6ae09fc8d4d1.png , you can contact the theme author and ask about this, or write here more details, link to your website, and other details
