### ISSUE TITLE
Catch jquery event of options in admin

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#1428]
I have an option "checkboxes" in my posts, please show me how to catch the JQuery event when the box is checked or unchecked.
Sorry because I tried searching so much but did not find the way.

**Comment by moldcraft** [comment]
Add in

```
{theme}/framework-customizations/theme/options/posts/post.php
```

```php
$options = array(
	'test' => array(
		'type' => 'checkboxes',
		'choices' => array(
			'hello' => 'Hello',
			'world' => 'World',
		),
	),
);
```

Open Post Edit page and execute in browser console

```js
jQuery('#fw-option-test').on('change', function(e){
    console.log(e.target.name, jQuery(e.target).is(':checked'));
});
```

Then click on checkboxes and see the values in browser console
