### ISSUE TITLE
Extensions won't download

### ISSUE THREAD

**Issue by Giorsoine** [ThemeFuse/Unyson#1429]
I just installed the plugin, but when I try to download the extensions I get a pop up box with Error as the only word in it.

What can I do?

I got WP 4.2.2, PHP 7 and MySQL 5.1.x

**Comment by moldcraft** [comment]
Please open this link in browser

```
{your.site}/admin.php?page=fw-extensions&sub-page=install&extension=page-builder
```

**Comment by Giorsoine** [comment]
That worked, so I need to do this for all the extensions I want?

**Comment by Giorsoine** [comment]
I worked for Sidebars as well, but Sliders can't be downloaded it says.

**Comment by moldcraft** [comment]
> Sliders can't be downloaded it says

What is the error message? (Please more details)

**Comment by Giorsoine** [comment]
Just a white box with the word error in it.
![error](https://cloud.githubusercontent.com/assets/18311823/14325378/5e060638-fc29-11e5-94b7-51436332ea15.png)

**Comment by moldcraft** [comment]
Please open browser developer tools and inspect Network server response.

**Comment by moldcraft** [comment]
Or give me admin access to your site and I will inspect it (send details to `moldcraft[at]email.com`)

**Comment by moldcraft** [comment]
I disabled the **Foo Gallery** plugin and the problem disappeared.
