### ISSUE TITLE
Overwriting extension functionality

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1432]
Hello,

I'm using the feedback extension and I've customized the appearance. But now I also want to change something in the functionality. By standard, the feedback extension removes previous comments when an user adds a new one. The piece of code doing that, is found in the 'class-fw-extension-feedback.php' file.

Now, I've added a copy of this file to my 'framework-customizations/extensions/feedback' folder. And next, I've removed the lines that remove previous comments. But when I test this, the code doesn't get picked up. 

Next, I've tried to do this in the original file. That works. But I don't want to make changes in the original extension folder.

Am I doing something wrong here? Or is it simply not possible to make changes this way on functional things?

**Comment by duongancol** [comment]
Is this in function _action_wp_insert_comment ?

**Comment by noesteijver** [comment]
Yes, it is!

**Comment by duongancol** [comment]
you can edit if this code's written in filter action. Unfortunately, it didn't. So creating a new feedback extension base on this extension is a good choice. 
But still want to hear the answer from Unyson team, because many users and my clients also ask about this feature.

**Comment by noesteijver** [comment]
The function I want to change isn't a pluggable function, so it doesn't get overridden automatically in the framework customizations.

And I believe the function also isn't hooked to anything, so I can't remove it from the hook.

**Comment by noesteijver** [comment]
Correction; it is hooked. That happens on line 40. But still can't figure out why the changed function isn't run..

**Comment by duongancol** [comment]
Did you create a Class file in **framework-customization/extension/feedback** ? That'll not work.

**Comment by noesteijver** [comment]
Yes, I did. What would be the proper way to do it? I figured it would work the same as changing the views file etc.

**Comment by moldcraft** [comment]
> I've added a copy of the 'class-fw-extension-feedback.php' file to my 'framework-customizations/extensions/feedback' folder.

It won't work, extension class can't be overwritten.

> So creating a new feedback extension base on this extension is a good choice. 

Nope, you will need to update it when we release updates.

----

@noesteijver You can add a filter there that will disable that feature and submit a pull request. If you don't know how pull requests work, let me know and I will add that filter myself.

**Comment by noesteijver** [comment]
@moldcraft I'm not really sure what you mean. Could you help me with this? Many thanks!

**Comment by moldcraft** [comment]
[Here](https://github.com/ThemeFuse/Unyson-Feedback-Extension/blob/v1.0.9/class-fw-extension-feedback.php#L192) can be added a filter:

```php
if (apply_filters('fw:ext:feedback:remove-previous-comments', true, array(
    'post_id' => $post_id,
    'comment' => $comment,
))) {
    // ...
}
```

----

_P.S. Also [there is a bug](https://github.com/ThemeFuse/Unyson-Feedback-Extension/blob/master/class-fw-extension-feedback.php#L196), the `$comment` variable is changed by `for`_

**Comment by moldcraft** [comment]
The filter will be available in the next release.

**Comment by noesteijver** [comment]
I'm sorry to bother you again about this, but the filter is added in the class file. But how can I override this part? Is that by deleting the filter first and adding my own filter instead in my functions file? Or is there a simpler way to do this?

**Comment by moldcraft** [comment]
Add in your theme

```php
function _filter_theme_fw_ext_feedback_remove_prev_comment($remove, $data) {
    // some logic ...
    $remove = false;
    return $remove;
}
add_filter('fw:ext:feedback:remove-previous-comments', '_filter_theme_fw_ext_feedback_remove_prev_comment', 10, 2);
```
