### ISSUE TITLE
fw_resize doesn't work in subfolder wordpress installation

### ISSUE THREAD

**Issue by hlaporthein** [ThemeFuse/Unyson#1433]
I have been using this plugins ever since it launched. Thanks For that. I use fw_resize and it work fine for me. But, Today I got error in wordpress subfolder installation.
 For example, suppose my site domain name is http://www.example.com and my wordpress installation is http://www.example.com/mywordpress/

`fw_resize($full_image_url, 783, 520, true);`

It only returns full image url path and it didn't give me crop image size? So, my question is 
**Doesn't image crop function work with wordpress subfolder?**
**Doesn't that crop function work with http://www?**

Please help me, I have tested  for a few hours. Thanks in advanced

**Comment by moldcraft** [comment]
Hello,

Unfortunately I am not the author of the `fw_resize()` functionality and don't know how it works. You can try to inspect/debug the code and find out why it's not working in your case.

I will inspect it later, sorry.

**Comment by moldcraft** [comment]
Send `$attachment_id` as first parameter for `fw_resize()` (not `$attachment_url`)
