### ISSUE TITLE
Customizer options: Add support for all setting args

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1435]
> https://github.com/ThemeFuse/Unyson/pull/1425

[All these args](https://codex.wordpress.org/Class_Reference%5CWP_Customize_Manager%5Cadd_setting#Arguments) must be supported, to be able to specify them in option array.

**Comment by moldcraft** [comment]
Please test

```php
'option_id' => array(
    'type' => 'text',
    'wp-customizer-setting-args' => array(
        // https://codex.wordpress.org/Class_Reference%5CWP_Customize_Manager%5Cadd_setting#Arguments
    ),
),
```

Note: You can't overwrite `'default'` because [here](https://github.com/ThemeFuse/Unyson/blob/ec0d480ff889c7dc0103e502dcec0ffcf3c3f756/framework/core/components/backend.php#L2122) is

```php
array_merge($custom_args, $default_args)
```

not vice versa

**Comment by NwpDeveloper** [comment]
Left comments in commit. 

Not sure if typo but you shouldn't array_merge $args_controls with $args_settings.

**Comment by moldcraft** [comment]
It was typo (fixed)
