### ISSUE TITLE
Not able to edit page in visual/text mode

### ISSUE THREAD

**Issue by NickDubelman** [ThemeFuse/Unyson#1436]
I've seen in videos that people are able to create their page in page builder mode and then switch to the default editor and will see their page content in the visual/text representation.

When I try to do this in my site (using ThemeFuse medical theme), the visual/text editors are entirely empty.

Is this the correct behavior? As far as I can tell, I should be able to see shortcodes, etc. (a text representation of my page) in the visual/text tabs.

**Comment by moldcraft** [comment]
Hello,

Can you give the link to video you saw?

It is not possible to convert visual elements to their text/shortcode representation.
