### ISSUE TITLE
FontAwesome missing after update

### ISSUE THREAD

**Issue by blackyangell** [ThemeFuse/Unyson#1437]
I've noticed that all my FontAwesome icons dissapeared after the last framework update. When I load FontAwesome manually, everything is fine. 
Was it planned, and FontAwesome will not be the part of Unyson any more, or it will be fixed?
Thank you.

**Comment by moldcraft** [comment]
Please give more details. How to reproduce this?

FontAwesome didn't disappeared https://github.com/ThemeFuse/Unyson/tree/v2.5.1/framework/static/libs/font-awesome

**Comment by blackyangell** [comment]
Hm... I don't know, because I didn't do anything...  I saw than FontAwesome was the part of Unyson, and I didn't include it by myself, it just worked.
Now I don't see any icons, and don't see font-awesome css file to be loaded... 

Where I can find the file where this css is enqueued? I can check it.

**Comment by moldcraft** [comment]
In backend or frontend? How to test this?

For backend it is registered [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.1/framework/core/components/backend.php#L426) and others just enqueue it's id/handle.

**Comment by blackyangell** [comment]
I have problem in frontend, but I don't use FontAwesome in backend and can't tell that it is only frontend issue.
Sorry, I really don't know how to test it.. Maybe it's some problem on my side only, but I don't understand what could happened, because I didn't deregister any css files.

**Comment by moldcraft** [comment]
FontAwesome is not enqueued automatically in frontend, so it is clearly a theme issue.

**Comment by thednp** [comment]
Also keep in mind that from time to time some icon names get deprecated.

**Comment by blackyangell** [comment]
Thank you for information!
