### ISSUE TITLE
TypeError: Cannot read property 'fw-storage' of null

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1438]
After update the  latest version we are getting error in shortcodes. where used 'null'

like 
```
array(
        'type' => 'date-picker',
        'min-date' => null,
),
```
```
array(
    'type' => 'popup',
 'popup-title' => null,
)
```
And here is the error message

`TypeError: Cannot read property 'fw-storage' of null /wp-content/plugins/unyson/framework/static/js/fw.js?ver=2.5.1:1243`

**Comment by moldcraft** [comment]
Hi, can you give admin/ftp access to your site?

If yes, send the details to `moldcraft[at]email.com`

**Comment by Ataurr** [comment]
I am working on localhost. and our latest new two themes faced this same issue. 

And i am received one of our client also faced our old theme today. here is the screenshot
http://puu.sh/oe2O3/f3da76e2cd.png

Nothing will appears in shortcode when this error occurred.

 If you need i will manage login details from him.
