### ISSUE TITLE
Tab containers don't work inside addable popup and addable box.

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1439]
I am not sure how to report this: an issue or something that haven't been implemented, still, is there a way to make it work without making a new custom option type?

**Comment by moldcraft** [comment]
Please don't use "doesn't work", 'it's not working!", ...

Tell exactly what happens, it is not displayed?

**Comment by thednp** [comment]
Sorry for the language, however not only the options inside the tabs don't show up, but they're not even present in the HTML. Perhaps my array structure isn't right, but if I change the option type from "tab" to "group" it works fine as a group, so it's a puzzle.

**Comment by thednp** [comment]
I'm gonna change the structure to trick this issue, but you have anything on it?

**Comment by moldcraft** [comment]
I haven't started working on this yet.

**Comment by moldcraft** [comment]
I tested with this option array in post options and it works

```php
'test' => array(
	'type' => 'addable-popup',
	'popup-options' => array(
		'tx' => array('type' => 'text'),
		'ta' => array(
			'type' => 'tab',
			'title' => 'Hi',
			'options' => array('x' => array('type' => 'text')),
		),
		'tb' => array(
			'type' => 'tab',
			'title' => 'Hey',
			'options' => array('y' => array('type' => 'text')),
		),
	),
),
```

**Comment by thednp** [comment]
Please test for metaboxes as well.

**Comment by moldcraft** [comment]
Why you need tabs in addable box? Can you give an option array example?

**Comment by thednp** [comment]
I am basically trying to create a kind of content builder for a custom post type called slider, since the page builder is only for posts and pages mostly and cannot be easily customized for that purpose.

But thanks for your input, I will change all my code to work with `addalbe-popup`.

**Comment by thednp** [comment]
I just finished editing all code with `addalbe-popup` option type and it works, just keep in mind that `tab` option type don't show inside `addable-box`.

**Comment by moldcraft** [comment]
addable-box is too small to contain tabs

**Comment by thednp** [comment]
On the contrary: the `addable-box` can be extended to full width, via `'width' => 'full'` while the `addable-popup` cannot. I just tested this as I typed here.

**Comment by moldcraft** [comment]
`'size' => 'large'` http://manual.unyson.io/en/latest/options/built-in-option-types.html#addable-popup
