### ISSUE TITLE
Feature Request:: Can you add "Add element" button in every section or column in page builder?

### ISSUE THREAD

**Issue by AminulBD** [ThemeFuse/Unyson#144]

**Comment by moldcraft** [comment]
More details please:
* which element?
* why do you need such feature?
* maybe a sketch how it should look?

**Comment by AminulBD** [comment]
1. All element have element by default or custom created.
2. Because, Now its bad user experience when page builder content has huge section or elements.

![screenshot from 2015-01-05 13 38 02](https://cloud.githubusercontent.com/assets/5006546/5610353/3fac3b46-94e0-11e4-86d3-472b30a14da1.png)

**Comment by moldcraft** [comment]
Thanks.

We will come back with a response in a few days.

**Comment by moldcraft** [comment]
What should happen when you click the |Add Element" button (maybe a [sketch](http://ninjamock.com/)/screenshot) ?

**Comment by AminulBD** [comment]
Check this examples.
![look](https://cloud.githubusercontent.com/assets/5006546/5624659/1751193c-9594-11e4-82ea-d3937515b868.png)

**Comment by moldcraft** [comment]
It's complicate. We have to think how to do it.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/244
