### ISSUE TITLE
Save range slider in separate meta

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1440]
Hello,

Is it possible to save range slider values in a separate meta with fw-storage?

I've tried this, but it's not working as expected and I can't find examples for usage with range slider:

```php
'prijs' => array(
    'type'  => 'range-slider',
    'value' => array(
        'from' => 0,
        'to'   => 100,
    ),
    'label' => __('Prijs', 'fw'),
    'desc'  => __('Prijs per persoon, in €', 'fw'),						    
	'fw-storage' => array(
        'type' => 'post-meta',
        'post-meta' => 'prijs',
    ),
),
```

**Comment by moldcraft** [comment]
Hi,

Where is this option located (customizer, settings or post options) ?

At the moment fw-storage works only in settings and post options.

**Comment by moldcraft** [comment]
P.S. To add code blocks in comment, use this markup

```
    ```php
    $your_code = 'here';
    ```
```

**Comment by noesteijver** [comment]
This option is located in post options!

**Comment by moldcraft** [comment]
I added the above option array in

```
{theme}/framework-customizations/theme/options/posts/post.php
```

and it is saved in separate meta

![](https://static.md/6e149a9eeac7ba391bb8ce41d748ff3b.png)

`fw_options` contains option-type default value

![](https://static.md/5a891c6a0df520144768739d216d2c89.png)

**Comment by noesteijver** [comment]
My code doesn't do that. To be safe, my whole code is posted below, maybe the deep nesting causes problems saving it to a separate meta?

```php
'speelplek_entree' => array(
	    
	    'type' => 'box',
		'options' => array(

			'entreeprijs' =>   array(
		        'type'  => 'multi-picker',
		        'label' => false,
		        'desc'  => false,
		        'picker' => array(
		            'entreeprijs_betalen' => array(
		                'type'  => 'switch',
		                'value' => 'nee',
		                'label' => __('Entree betalen?', 'fw'),
		                'left-choice' => array(
		                    'value' => 'nee',
		                    'label' => __('Nee', 'fw'), 
		                ),
		                'right-choice' => array(
		                    'value' => 'ja',
		                    'label' => __('Ja', 'fw'),
		                ),
		            ),
		        ),
		        'choices'   => array(
		            'ja' => array(

		                'prijs' => array(
		                    'type'  => 'range-slider',
						    'value' => array(
						        'from' => 0,
						        'to'   => 100,
						    ),
						    'label' => __('Prijs', 'fw'),
						    'desc'  => __('Prijs per persoon, in €', 'fw'),						    
			    			'fw-storage' => array(
						        'type' => 'post-meta',
						        'post-meta' => 'fw_option:prijs',
						    ),
		                ),
		                
		            )  
		        ),
		    ),

	    ),
	    'title' => __('Speelplek entree', 'fw'),

	),
```

**Comment by moldcraft** [comment]
Multi-picker is an option type, its value is a final value, you can't save a part of an option value in separate meta.

I can enable the further processing of options `fw-storage` inside multi-picker but that will cause overhead (too much processing).

Why you need that option to be saved in separate meta? (Anyway you can't do `SELECT ... WHERE ...` to find it because its value is a serialized array, not a simple text value)

**Comment by noesteijver** [comment]
This piece of code asks if you have to pay entrance. If yes, then you can fill out the amount with the range slider (for different ticket types). So the range slider is only displayed (and necessary) when the multi-picker value is yes.

I want to use the values from the range slider in a filter on the search page. That's why I would like them in a separate meta..

**Comment by moldcraft** [comment]
I think the user will be confused, because if you change the range in one post it will affect all posts. Or not?

**Comment by noesteijver** [comment]
The idea is that you can fill out a minimum and maximum price. 

And on the search page, I want to make a range slider as well, so users can set a minimum and maximum price.

**Comment by moldcraft** [comment]
To enable this feature, use [this filter](https://github.com/ThemeFuse/Unyson/blob/0e75050644fa0d001aca3ecd521c1d2680f1e866/framework/includes/option-types/multi-picker/class-fw-option-type-multi-picker.php#L304).

Important: Do not use post meta name `'post-meta' => 'fw_storage:*'` because it will be deleted by [this code](https://github.com/ThemeFuse/Unyson/blob/0e75050644fa0d001aca3ecd521c1d2680f1e866/framework/core/components/backend.php#L995-L1050)
