### ISSUE TITLE
WordPress 4.5-RC2 fw.soleModal z-index problem.

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1443]
![](https://i.gyazo.com/9b9cc833226a15f520f4fa5fca7dd557.gif)

That's just on new WP 4.5. Not really sure what's the problem but I think they've changed some modals settings.

**Comment by andreiglingeanu** [comment]
@moldcraft Thank you.

**Comment by andreiglingeanu** [comment]
It's still not fixed for me. Can anyone confirm this?

**Comment by moldcraft** [comment]
I opened an optionsModal, then executed in console `fw.soleModal.show('test', 'Hello')` and it showed up

**Comment by danyj** [comment]
works for me to http://prntscr.com/aspmwu

**Comment by andreiglingeanu** [comment]
Yeah, after reinstalling unyson from scratch it's fine. Thank you.
