### ISSUE TITLE
In "WP Editor" add table element

### ISSUE THREAD

**Issue by niceandriyanov** [ThemeFuse/Unyson#1444]
Hi, guys! Thank you for framework, true it's good, but arose problem: in option "WP Editor" (page documentation: http://manual.unyson.io/en/latest/options/built-in-option-types.html#wp-editor ) doesn't contain a table. How his add in it's option. 

P.S. sorry for my English.

**Comment by moldcraft** [comment]
Hello,

* Download Unyson latest dev version from github
* Install [this plugin](https://wordpress.org/plugins/tinymce-advanced/)
