### ISSUE TITLE
Feedback .css and .js not loaded on certain pages

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#1445]
Hi guys,

We've implemented the Feedback extension in a website, so visitors can give a rating to a location. When using the fw_ext_feedback() function in a widget (so it can be used in the sidebar) it works just fine on certain pages, on others the necessary stylesheet and script aren't loaded automatically, thus the information in the qtip part isn't hidden.

On this page the rating is fully functional (see 'Best beoordeelde speelplekken' in sidebar):
http://wespire.nl/klanten/playadvisor/wp/speelplek/de-efteling/

Here things are broken:
http://wespire.nl/klanten/playadvisor/wp/hallo-wereld/

Any ideas why the necessary files aren't automatically loaded and what we can do to fix it?

**Comment by moldcraft** [comment]
Hello,

Please check if the problem is in [this condition](https://github.com/ThemeFuse/Unyson-Feedback-Extension/blob/df3ac5048a7fd6a5fc5da547038e6f9f94f69301/extensions/feedback-stars/static.php#L9). If yes, try to find a solution and I will add the changes on github (or submit a pull request)

**Comment by warudin** [comment]
As a test I removed the if statement and then the qtip works as it should.
So you've located the source of the problem.

Thanks, I'll look into it and when I find a good solution I will send them in!

**Comment by warudin** [comment]
I added a check in the static file, so the if statement becomes true when the function is used.
Of course this is in no way a general solution for this problem.

```
if (is_active_widget( false, false, 'best_beoordeelde_speelplekken' || 'aanbevolen_speelplekken', true )) {
		$widget = true;
	}


if ((!empty($post)) && (!empty($post->post_type)) && post_type_supports( $post->post_type, $instance->get_parent()->supports_feature_name ) || $widget) {
```

**Comment by moldcraft** [comment]
If I will add a filter and you can use it to return true, it will be ok?

**Comment by warudin** [comment]
Yeah, I guess that's fine.

I saw that my code is loaded on every page and it's also 'true' when the widget isn't displayed on a certain page. 
So although the files are loaded and the widgets display fine now, it's not as clean as I hoped.

**Comment by moldcraft** [comment]
Download the latest dev version of [feedback extension from github](https://github.com/ThemeFuse/Unyson-Feedback-Extension) and use [this filter](https://github.com/ThemeFuse/Unyson-Feedback-Extension/blob/a6d0fb55780b8968842fc2c475b8fe37abf30d44/extensions/feedback-stars/static.php#L20)

**Comment by warudin** [comment]
Thanks, I've got it working with this filter.
Will this version of the extension be distributed or do my colleagues need to install this dev version manually?

**Comment by moldcraft** [comment]
It will be released soon, follow [this](https://github.com/ThemeFuse/Unyson-Extensions-Approval)

**Comment by warudin** [comment]
Thanks. :)
