### ISSUE TITLE
Alt tag bug

### ISSUE THREAD

**Issue by alriksson** [ThemeFuse/Unyson#1447]
Hi,

Most image uploads are resulting in a missing alt tag. If you upload an image using one of the following methods the image will miss the alt tag:

- Using the "Image" unyson tab, see no.1 here: http://tinypic.com/view.php?pic=xdbfvl&s=9#.VwqIZHrYFjg

- Using the "Background Image" in "Banner"
See no.2 here: http://tinypic.com/view.php?pic=xdbfvl&s=9#.VwqIZHrYFjg

- Using a "Background Image" in a Section
See no.3 here: http://tinypic.com/view.php?pic=xdbfvl&s=9#.VwqIZHrYFjg

This is very crucial for SEO as I really need Google to be able to understand the images that I am using.

Please include the alt tag when using all types of image uploads in unyson.

See attached tinypic link for clarification.

(https://wordpress.org/support/topic/alt-tag-bug)

**Comment by moldcraft** [comment]
Hello,

Alt attribute is added https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.10/shortcodes/media-image/views/view.php#L22

Please report this problem to theme author.

Also I can't view second and third image https://static.md/e3c346d72321ef1b8f40815352c00f75.png
