### ISSUE TITLE
Alignment fixes

### ISSUE THREAD

**Issue by alriksson** [ThemeFuse/Unyson#1448]
print: http://prntscr.com/aqk4vx

1. It would be nice if you could fix a field for Alignment for buttons since it looks like the print below on mobile devices.

2. Alignment for images doesn't work. Nothing happens when you pick center or right so it's always fixed to the left.

Thanks in advance.

(https://wordpress.org/support/topic/alignment-fixes)

**Comment by moldcraft** [comment]
We don't have alignment option for image shortcode https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.10/shortcodes/media-image/options.php

Report this problem to theme author.
