### ISSUE TITLE
Icon deselect 

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#145]
On click you deselect an icon from this option: http://joxi.ru/p27E6pZio7kgr7. I think it will be better from the usability stand point if the hover will actually disappear when you click to deselect the icon. Another option will be to make a different color the selected icon state only: #64bd1f

How it works now is it stay the same and you don't actually know if the icon is deselected or not when you click on it (that's until you move the mouse away).

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/398
