### ISSUE TITLE
Shortcode popup title

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1450]
Hello, 

After WordPress 4.5 update shortcode popup title HTML is not working anymore (it works in 4.4 version):
![screenshot_1](https://cloud.githubusercontent.com/assets/10400351/14474521/3555f478-0106-11e6-9a5f-e456fdc58280.png)

My code _(this is just an example):_
```
'page_builder' => array(
     'title' => __( '<b>Headline</b>', 'theme')
```

**Comment by moldcraft** [comment]
1. Don't use html in `__()` http://wordpress.stackexchange.com/questions/114201/html-inside-or-e-language-translation-string Change to `'<b>'. __( 'Headline', 'theme') .'</b>'`
2. Why you need that title to be bold?
3. Html never worked in modal title

    * WP 3.5.1 https://github.com/WordPress/WordPress/blob/3.5.1/wp-includes/js/media-views.js#L277
    * WP 4.4.2 https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/js/media-views.js#L1980

    You can add `console.log(...);` there to ensure that that's the actual code responsible for modal display.

**Comment by pear1** [comment]
I don't really need any HTML to work in the popup title, it can be just stripped down. 
HTML I need in the **Content Elements** so I can customize some shortcode appearance and their order.

**Comment by moldcraft** [comment]
Please give a screenshot where exactly you need html.

**Comment by pear1** [comment]
You can see it in this image below: 
![screenshot_1](https://cloud.githubusercontent.com/assets/10400351/14487997/9ae3ad9a-016e-11e6-98cb-492183223188.png)

**Comment by moldcraft** [comment]
Use the `"title_template"` config arg. http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file

**Comment by pear1** [comment]
I already use it and it works well.

But it doesn't change the look in the _Content Elements_ tab.
Also it works only after opening/saving shortcode or page update.
This screenshot was taken before these shortcodes was even opened and edited or page saved.

**Comment by moldcraft** [comment]
Download the latest page-builder extension https://github.com/ThemeFuse/Unyson-PageBuilder-Extension

Now every thumbnail has a [this class](https://static.md/20750f3e022643c6186bfb35d89967ba.png)

**Comment by pear1** [comment]
Thank you.
Just tested and it works.

Can you also add a similar class in page builder shortcode items? It would be handy.

**Comment by moldcraft** [comment]
> page builder shortcode items

?

**Comment by pear1** [comment]
These items in picture below.
Didn't know the right name to call them.
![screenshot_2](https://cloud.githubusercontent.com/assets/10400351/14491698/10ae9274-0183-11e6-8f34-4818b3dd758f.png)

**Comment by moldcraft** [comment]
'title_template' is for them, isn't that enought?

**Comment by pear1** [comment]
I wanted to style them before 'title_template' is working, but nevermind.
Thank you.

**Comment by pear1** [comment]
Last thing.
Small feature what would be useful in the future is option to use _Title Template_ syntax in icon attribute (under config file). Then we could use Image shortcode image value inside icon option.

It could work by adding 'icon_template' attribute, which would overwrite 'icon' if it would contain some value.
