### ISSUE TITLE
Trying not to repeat the code. Need an advice.

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1451]
In my `theme/options`  I have file   `single_post_options.php`  which is than called via 

    fw()->theme->get_options( 'single_post_options')

in there for example an option 

	'show_pagination' => array(
		'label' => __('Show post pagination', 'fw'),
		'desc' => __('Show/hide post pagination', 'fw'),
		'type' => 'switch',
		'right-choice' => array(
			'value' => 'hide',
			'label' => __('Hide', 'fw')
		),
		'left-choice' => array(
			'value' => 'show',
			'label' => __('Show', 'fw')
		),
		'value' => 'show'
	)

all nice and dandy , now I need to duplicate this option set to be available also in post edit. 

so instead doing this in  `theme/options/posts/post.php`

	'show_post_comments' => array(
		'label' => __('Show post comments', 'fw'),
		'desc' => __('Show/hide post comments', 'fw'),
		'type' => 'switch',
		'right-choice' => array(
			'value' => 'hide',
			'label' => __('Hide', 'fw')
		),
		'left-choice' => array(
			'value' => 'show',
			'label' => __('Show', 'fw')
		),
		'value' => fw_get_db_settings_option('show_post_comments','show')
	),

is there a better way to duplicate all options from  `single_post_options.php`  but their default values must be from   

        fw_get_db_settings_option('option','val')

note that if I do this in post.php

    fw()->theme->get_options( 'single_post_options')

I dont get the already saved values from db , but the hard coded defaults from that file , thus I need an advice on this before I duplicate the code for no reason. 

Any help is appreciated.

**Comment by danyj** [comment]
@moldcraft  u got a sec for this or https://github.com/ThemeFuse/Unyson/issues/1356#issuecomment-208985483?

**Comment by andreiglingeanu** [comment]
@danyj Probably extract array generation into a helper that will receive values that change as arguments

```
function generate_options($label, $desc, $path_to_db_value) {
  return array(
    'label' => __($label, 'fw'),
    'desc' => __($desc, 'fw'),
    'type' => 'switch',
    'right-choice' => array(
        'value' => 'hide',
        'label' => __('Hide', 'fw')
    ),
    'left-choice' => array(
        'value' => 'show',
        'label' => __('Show', 'fw')
    ),
    'value' => fw_get_db_settings_option($path_db_value','show')
  );
}

// Then use your function multiple times
'show_post_comments' => generate_options(
  'Show post comments',
  'Show/hide post comments',
  'show_post_comments'
);
```

**Comment by danyj** [comment]
@andreiglingeanu hm , not bad bud i need multiple functions for all option types , the switch was just an example , 

something like this would be much more functional I think 


    fw()->theme->get_options( 'single_post_options',null,$db_values = true)

where $db_values loads already saved values, this way there is no double code


i think we already had something like that , a function that gets all options with their db values , extract options or something.

**Comment by andreiglingeanu** [comment]
@danyj [fw_extract_only_options](http://manual.unyson.io/en/latest/helpers/php.html#fw-extract-only-options) separates options that have value in db from arrays that are mixed with containers.

**Comment by danyj** [comment]
@andreiglingeanu  yes , thats the one , to bad , I need containers to but its a start. thnx bud.

**Comment by danyj** [comment]
well , none of those get db values , only hardcoded ones 

    fw_extract_only_options 
    fw_get_options_values_from_input


I tried with 


	$some_options 	= fw()->theme->get_options( 'test_set');
	fw_print(fw_extract_only_options($some_options));


and I get defaults back ,  

@moldcraft   if you get to this please enlighten us. 

i'm trying to use

     fw()->theme->get_options( 'test_set');

but with db values as start, not harcoded ones.

**Comment by andreiglingeanu** [comment]
@danyj You may want to use this one [fw_get_options_values_from_input](http://manual.unyson.io/en/latest/helpers/php.html#fw-get-options-values-from-input). This one will accept an array of options and an array of values. If no value is provided for a particular option it will extract default from the options array.

That is, it's usage is something like this:

```php
fw_get_options_values_from_input(
  fw()->theme->get_options( 'test_set' ),
  fw_get_db_settings_option('your_path'', 'your default value')
);
```

This should fulfill your use case.

**Comment by danyj** [comment]
but I dont undestand this 

      fw_get_db_settings_option('your_path', 'your default value')

your_path?  

you think that fw_get_db_settings_option can pull defaults from specific file only ?

**Comment by andreiglingeanu** [comment]
@danyj Oh, of course no. By `your_path` I mean the key of the values you want to get from DB.

**Comment by danyj** [comment]
ah ok , so list all options I need is what you mean, it might work but we should have something in place for this. every one of us will duplicate specific set of options for a page/post vs theme options and there should be a function that allows us to just copy over without rewriting the code. 

@andreiglingeanu  you suggestion might be on the right way.

**Comment by danyj** [comment]
and this again ,   

    fw_get_options_values_from_input

not letting me move the containers so I am stuck in to looping moving and placing things again

this would be optimal 

       fw()->theme->get_options( 'single_post_options',null,$db_values = true)

**Comment by moldcraft** [comment]
Try [this method](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/core/components/theme.php#L66)

```php
fw()->theme->get_options('settings',  array('values' => fw_get_db_settings_option(...)));
```

then in `settings.php` for each option add a check in `'value'`

```php
array(
    // ...
    'value' => isset($values['option_id']) ? $values['option_id'] : null,
)
```

Is this solution ok?

**Comment by danyj** [comment]
@moldcraft  thnx for the suggestion , I think that is doable for couple of options but I have a maze of multipickers and all kinds of option combos , going trough each and doing double checks now is pain. This is my files structure 

```
site.php
header.php
topmenu.php
footer.php
blog.php
single_post.php
portfolio.php
single_project.php
```

each of those has mutlitude of options within 

now I am copying each of those sets depending where you are , post, project,page and in each I have 

site, header, topmenu, footer plus the specific set

you see how easy this can become a mess when checking values with isset. 

for now I was forced to copy those files , rename them as `custom_set_SETNAME.php`

and use


    fw_get_db_settings_option('option','val')

now this works ok but maintenance will be pain , imagine if I have to change an option in site,php and I forget the customs duplicate , that is why I am looking for simple copy complete set with DB values.

**Comment by danyj** [comment]
maybe some loop to go trough 


	$options = array();
	$some_options   = fw()->theme->get_options( 'test_set');
	
	foreach($some_options as $key => $option){
	
		$options[$option]['value'] = fw_get_db_settings_option($option,$key['value']);	
		
	}

this is just stupid example , it wont work because of multipickers , tabs , containers etc,  but something along those lines.

**Comment by moldcraft** [comment]
I think you can use [this function](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/helpers/general.php#L706), the result is not returned but [added by reference in the first parameter](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/helpers/general.php#L591-L595), also the collected options are not copied but referenced [here ](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/helpers/general.php#L645) and [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/helpers/general.php#L691), so later you can change them and it will also affect the original array.

Here is an (untested) example:

```php
$some_options = fw()->theme->get_options( 'test_set');
$collected = array();
fw_collect_options($collected, $some_options);
foreach ($collected as $id => $option) {
    $collected[$id]['value'] = fw_get_db_settings_option($id, isset($option['value']) ? $option['value'] : null);
fw_print($some_options); // now this should reflect the changes made in $collected
}
```

**Comment by danyj** [comment]
@moldcraft   of the bet!!!!!!!   testing but for now it spits out the right   values!!!! magic man :)

**Comment by danyj** [comment]
man!!!! you just helped me replace over 2k lines from 6 files with 36!
