### ISSUE TITLE
How to create a custom extension to pull post/custom post loops?

### ISSUE THREAD

**Issue by zenics** [ThemeFuse/Unyson#1453]
Is there any one there knows how to create a shortcode extension to loop one(or more) post/custom post?

**Comment by thednp** [comment]
There is something called "Population Methods" required by various option types and / or extensions. Maybe [this](http://manual.unyson.io/en/latest/options/built-in-option-types.html?highlight=population#multi-select) is what you're looking for?

**Comment by moldcraft** [comment]
Just using default WP functions to query posts doesn't work?
