### ISSUE TITLE
Names of builders

### ISSUE THREAD

**Issue by LevyMarketing** [ThemeFuse/Unyson#1454]
Hi, 

Normally when you're in the builder, the items have names like section, text box, image, etc. When I go to edit a page now, all of them have the name function(n){return o.call(this,n,m)}

It was not like this yesterday. Did the update change something on my backend? I also cannot delete parts of the page anymore.

**Comment by moldcraft** [comment]
Please update Unyson and extension. If the problem persists, try to Ctrl+R to refresh browser js cache.
