### ISSUE TITLE
502 bad gateway error when saving a large menu on multisite

### ISSUE THREAD

**Issue by miramedia** [ThemeFuse/Unyson#1455]
Hi There
We have unyson installed on a multi site install with 200 sites on it.
When we save the menu we get 502 errors on the large menus - not all of them.
We have tried to increase the memory allocated to PHP in the php.ini file.
Any ideas what else we can try? We're running version 2.4.7 on WP 4.2.7
Thanks
Dominic

**Comment by moldcraft** [comment]
Hello,

Take a look in apache error.log to find more informative error messages.

**Comment by moldcraft** [comment]
I think this is a WP bug, because large menus contain lots of form inputs and your server limit is reached

https://github.com/WordPress/WordPress/commit/2bfc0f52188c6f3481635f223e468d9827d01392
https://core.trac.wordpress.org/ticket/14134
