### ISSUE TITLE
Demo data installation fails on some hostings

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1456]
Hello, team

I have a problem installing demo data on some specific hosting. Demo content extension generates a loop in it generates a loop in wp-content/uploads, here is an error from debug:

> Failed to copy: /html/wordpress/wp-content/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/tmp/f/uploads/fw-backup/.htaccess

could you advice, how to find a reason / fix this? I'm using latest version of Unyson and "Backup & Demo Content" extension

Thank you again for your help

**Comment by moldcraft** [comment]
I need to reproduce the problem on my localhost or admin/ftp details to server which has this problem, to debug it there.

You can send details to `moldcraft[at]email.com` but I will inspect it tomorrow.

**Comment by WPJobs** [comment]
@moldcraft No problems, you work so hard, i will email you FTP details, thank you for your time again!

**Comment by moldcraft** [comment]
Thank you for admin/ftp details, I discovered some bugs.

**Comment by WPJobs** [comment]
@moldcraft thank you so much for a really fast answer!
