### ISSUE TITLE
Fatal Error when Table Shortcode is used in PageBuilder

### ISSUE THREAD

**Issue by antoniomangiacapra** [ThemeFuse/Unyson#1457]
Hi,

I just discovered that in version 2.5.0, if you insert the shortcode Table using page builder, you get this error:

Fatal Error: Call to a member function _enqueue_static() on a non-object in .../wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/table/static.php on line 3

**Comment by danyj** [comment]
2.5.0 or 2.5.1 ? 
https://github.com/ThemeFuse/Unyson/releases

2.5.1 was released 8 days ago

**Comment by moldcraft** [comment]
You probably [disabled](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#disabling-shortcodes) the button shortcode in your theme
