### ISSUE TITLE
Can I add anonymous array key in custom option type? 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1458]
@moldcraft   bud , I have been doing this in few custom option types 

	protected function _get_value_from_input($option, $input_value)
	{
		
		
		if ( is_array( $input_value ) ) {
			
			$value = $input_value;

		} else {
			
			$value = $option['value'];
		}
		
		$value['css'] = $this->_process_css($value); //  just processing
		$value['classes'] = $this->_process_classes($value);//  just processing
		
		return $value;

	}

to pre process the  css or classes output instead of doing it afterwards inside files. 
those 2 spit this out http://prntscr.com/as3wu8

so I dont have to mess with it in front. 

Is this still ok and do you see any issues with it or do I need to set option type for them and also save them?

**Comment by moldcraft** [comment]
It should befine.

----

Another solution would be to overwrite [this](https://github.com/ThemeFuse/Unyson/blob/v2.5.2/framework/core/extends/class-fw-option-type.php#L395) and [this](https://github.com/ThemeFuse/Unyson/blob/v2.5.2/framework/core/extends/class-fw-option-type.php#L358) and to make the processed values to be saved in a separate post-meta in separate keys namespaced by option id ([something like in multi-picker](https://github.com/ThemeFuse/Unyson/blob/v2.5.2/framework/includes/option-types/multi-picker/class-fw-option-type-multi-picker.php#L299-L333))

```php
/**
 * {@inheritdoc}
 */
protected function _storage_load($id, array $option, $value, array $params) {
    $value['css'] = fw()->backend->option_type($opt['type'])->storage_load(
		'fake_id',
		array(
		    'type' => 'text',
		    'fw-storage' => array(
		        'type' => 'post-meta',
		        'post-meta' => 'thz_{option-type}_preprocess_data',
		        'key' => $id .'/css',
		    ),
		), 
		'',
		$params
	);

	$value['classes'] = fw()->backend->option_type($opt['type'])->storage_load(
		'fake_id',
		array(
		    'type' => 'text',
		    'fw-storage' => array(
		        'type' => 'post-meta',
		        'post-meta' => 'thz_{option-type}_preprocess_data',
		        'key' => $id .'/classes',
		    ),
		), 
		'',
		$params
	);

	return fw_db_option_storage_load($id, $option, $value, $params);
}

/**
 * {@inheritdoc}
 */
protected function _storage_save($id, array $option, $value, array $params) {
    fw()->backend->option_type($opt['type'])->storage_save(
    	'fake_id', 
    	array(
		    'type' => 'text',
		    'fw-storage' => array(
		        'type' => 'post-meta',
		        'post-meta' => 'thz_{option-type}_preprocess_data',
		        'key' => $id .'/css',
		    ),
		), 
    	$this->_process_css($value), 
    	$params
    );
    
    fw()->backend->option_type($opt['type'])->storage_save(
    	'fake_id', 
    	array(
		    'type' => 'text',
		    'fw-storage' => array(
		        'type' => 'post-meta',
		        'post-meta' => 'thz_{option-type}_preprocess_data',
		        'key' => $id .'/classes',
		    ),
		),
		$this->_process_classes($value), 
		$params
	);

	return fw_db_option_storage_save($id, $option, $value, $params);
}
```

Or save nothing in db, instead process data [on every db option get](https://github.com/ThemeFuse/Unyson/blob/v2.5.2/framework/helpers/database.php#L255)

```php
/**
 * {@inheritdoc}
 */
protected function _storage_load($id, array $option, $value, array $params) {
    $value = fw_db_option_storage_load($id, $option, $value, $params);

    $value['css'] = $this->_process_css($value);
    $value['classes'] = $this->_process_classes($value);

    return $value;
}
```

**Note**: Use latest Unyson dev for this to work https://github.com/ThemeFuse/Unyson/commit/838020745edea7aac4cdbdf9ec5115abbbfec4b6

**Comment by danyj** [comment]
thnx!

**Comment by danyj** [comment]
should  this 

`$opt['type']`

be 
  `  $option['type']`

?

the second solution  
>Or save nothing in db, instead process dat

works but first one does not

**Comment by moldcraft** [comment]
Edited

Replaced `$opt['type']` with `'text'`

**Comment by danyj** [comment]
i must be doing something wrong , 

	/**
	 * {@inheritdoc}
	 */
	protected function _storage_load($id, array $option, $value, array $params) {
		$value['css'] = fw()->backend->option_type('text')->storage_load(
			'fake_id',
			array(
				'type' => 'text',
				'fw-storage' => array(
					'type' => 'post-meta',
					'post-meta' => 'thz_font_preprocess_css',
					'key' => $id .'/css',
				),
			), 
			'',
			$params
		);
	
		$value['classes'] = fw()->backend->option_type('text')->storage_load(
			'fake_id',
			array(
				'type' => 'text',
				'fw-storage' => array(
					'type' => 'post-meta',
					'post-meta' => 'thz_font_preprocess_classes',
					'key' => $id .'/classes',
				),
			), 
			'',
			$params
		);
	
		return fw_db_option_storage_load($id, $option, $value, $params);
	}
	
	/**
	 * {@inheritdoc}
	 */
	protected function _storage_save($id, array $option, $value, array $params) {
		fw()->backend->option_type('text')->storage_save(
			'fake_id', 
			array(
				'type' => 'text',
				'fw-storage' => array(
					'type' => 'post-meta',
					'post-meta' => 'thz_font_preprocess_css',
					'key' => $id .'/css',
				),
			), 
			$this->_process_css($value), 
			$params
		);
	
		fw()->backend->option_type('text')->storage_save(
			'fake_id', 
			array(
				'type' => 'text',
				'fw-storage' => array(
					'type' => 'post-meta',
					'post-meta' => 'thz_font_preprocess_classes',
					'key' => $id .'/classes',
				),
			),
			$this->_process_classes($value), 
			$params
		);
	
		return fw_db_option_storage_save($id, $option, $value, $params);
	}

**Comment by moldcraft** [comment]
`'post-meta'` must be the same

**Comment by danyj** [comment]
tried that to , changed it to test , same thing no output , I do see css and classes keys in output but they are both empty

**Comment by danyj** [comment]
```

	
/**
 * {@inheritdoc}
 */
protected function _storage_load($id, array $option, $value, array $params) {
    $value['css'] = fw()->backend->option_type('text')->storage_load(
        'fake_id',
        array(
            'type' => 'text',
            'fw-storage' => array(
                'type' => 'post-meta',
                'post-meta' => 'thz_font_preprocess_data',
                'key' => $id .'/css',
            ),
        ), 
        '',
        $params
    );

    $value['classes'] = fw()->backend->option_type('text')->storage_load(
        'fake_id',
        array(
            'type' => 'text',
            'fw-storage' => array(
                'type' => 'post-meta',
                'post-meta' => 'thz_font_preprocess_data',
                'key' => $id .'/classes',
            ),
        ), 
        '',
        $params
    );

    return fw_db_option_storage_load($id, $option, $value, $params);
}

/**
 * {@inheritdoc}
 */
protected function _storage_save($id, array $option, $value, array $params) {
    fw()->backend->option_type('text')->storage_save(
        'fake_id', 
        array(
            'type' => 'text',
            'fw-storage' => array(
                'type' => 'post-meta',
                'post-meta' => 'thz_font_preprocess_data',
                'key' => $id .'/css',
            ),
        ), 
        $this->_process_css($value), 
        $params
    );

    fw()->backend->option_type('text')->storage_save(
        'fake_id', 
        array(
            'type' => 'text',
            'fw-storage' => array(
                'type' => 'post-meta',
                'post-meta' => 'thz_font_preprocess_data',
                'key' => $id .'/classes',
            ),
        ),
        $this->_process_classes($value), 
        $params
    );

    return fw_db_option_storage_save($id, $option, $value, $params);
}
```

**Comment by moldcraft** [comment]
1. ReSave post
2. Check phpmyadmin if values were saved correctly in separate meta

**Comment by danyj** [comment]
that is exactly what I am doing , I cant find it in DB ,  
look in wp_postmeta right ?

**Comment by moldcraft** [comment]
> look in wp_postmeta right ?

Yes

----

This works for me, the option is useless but the save works fine. I changed nothing in those 2 key methods.

```php
<?php if (!defined('FW')) {
	die('Forbidden');
}


class FW_Option_Type_ThzTest extends FW_Option_Type {
	public function get_type() {
		return 'thz-test';
	}
	/**
	 * @internal
	 * {@inheritdoc}
	 */
	protected function _enqueue_static( $id, $option, $data ) {
	}
	/**
	 * @param string $id
	 * @param array $option
	 * @param array $data
	 *
	 * @return string
	 *
	 * @internal
	 */
	protected function _render( $id, $option, $data ) {
		$option['attr']['value'] = json_encode($data['value']);
		return '<input ' . fw_attr_to_html( $option['attr'] ) . ' type="text" />';
	}
	/**
	 * @param array $option
	 * @param array|null|string $input_value
	 *
	 * @return string
	 *
	 * @internal
	 */
	protected function _get_value_from_input( $option, $input_value ) {
		return ( is_null( $input_value ) ? $option['value'] : (array)$input_value );
	}
	/**
	 * @internal
	 */
	protected function _get_defaults() {
		return array(
			'value' => array(),
		);
	}

	/**
	 * {@inheritdoc}
	 */
	protected function _storage_load($id, array $option, $value, array $params) {
		$value['css'] = fw()->backend->option_type('text')->storage_load(
			'fake_id',
			array(
				'type' => 'text',
				'fw-storage' => array(
					'type' => 'post-meta',
					'post-meta' => 'thz_font_preprocess_data',
					'key' => $id .'/css',
				),
			),
			'',
			$params
		);

		$value['classes'] = fw()->backend->option_type('text')->storage_load(
			'fake_id',
			array(
				'type' => 'text',
				'fw-storage' => array(
					'type' => 'post-meta',
					'post-meta' => 'thz_font_preprocess_data',
					'key' => $id .'/classes',
				),
			),
			'',
			$params
		);

		return fw_db_option_storage_load($id, $option, $value, $params);
	}

	/**
	 * {@inheritdoc}
	 */
	protected function _storage_save($id, array $option, $value, array $params) {
		fw()->backend->option_type('text')->storage_save(
			'fake_id',
			array(
				'type' => 'text',
				'fw-storage' => array(
					'type' => 'post-meta',
					'post-meta' => 'thz_font_preprocess_data',
					'key' => $id .'/css',
				),
			),
			'CSS:'. time(),
			$params
		);

		fw()->backend->option_type('text')->storage_save(
			'fake_id',
			array(
				'type' => 'text',
				'fw-storage' => array(
					'type' => 'post-meta',
					'post-meta' => 'thz_font_preprocess_data',
					'key' => $id .'/classes',
				),
			),
			'CLASSES:'. time(),
			$params
		);

		return fw_db_option_storage_save($id, $option, $value, $params);
	}
}

FW_Option_Type::register('FW_Option_Type_ThzTest');
```

**Comment by danyj** [comment]
ok your test does not work either , http://prntscr.com/as5wjb  , plus the meta is not in DB 
is there a different dev branch ? 

I downloaded the master when you told me to and did override , just did the compare with changes you made and they are there

**Comment by danyj** [comment]
note , im using this in theme settings if it makes any difference

**Comment by moldcraft** [comment]
in which post_id post meta do you expect it to save data if you use it in theme settings?

**Comment by danyj** [comment]
well , I did not even know that is bound to a post untill now. but why would you make me add this in a global optiuon type   if it has a usage restriction ? I never used fw-storage  before

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1458#issue-148329047 I have been doing this in few **custom option types**

Sorry I miss read: **custom post types**

----

Then use your initial solution or the last one (which doesn't save data in db)

**Comment by danyj** [comment]
either way those 2 work ok on default and on save so we are ok ,
