### ISSUE TITLE
None of the custom option types are returning default value

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1459]
Strange ,  any default Unsyon option type would return default value even if it is not saved 

example 

	'testingdefaultoption'    => array(
		'type'  => 'text',
		'label' => __( 'Title', 'fw' ),
		'value' => 'Default text option',
		'desc'  => __( 'Icon title', 'fw' ),
	),

prints 

        fw_print(fw_get_db_settings_option('testingdefaultoption'));

![screenshot_14](https://cloud.githubusercontent.com/assets/2340172/14526853/87b9057a-0246-11e6-94dc-606e3af14a21.jpg)

now make custom text option 

	<?php if (!defined('FW')) {
		die('Forbidden');
	}
	
	
	class FW_Option_Type_ThzTest extends FW_Option_Type {
		public function get_type() {
			return 'thz-test';
		}
		/**
		 * @internal
		 * {@inheritdoc}
		 */
		protected function _enqueue_static( $id, $option, $data ) {
		}
		/**
		 * @param string $id
		 * @param array $option
		 * @param array $data
		 *
		 * @return string
		 *
		 * @internal
		 */
		protected function _render( $id, $option, $data ) {
			$option['attr']['value'] = (string) $data['value'];
			return '<input ' . fw_attr_to_html( $option['attr'] ) . ' type="text" />';
		}
		/**
		 * @param array $option
		 * @param array|null|string $input_value
		 *
		 * @return string
		 *
		 * @internal
		 */
		protected function _get_value_from_input( $option, $input_value ) {
			return (string) ( is_null( $input_value ) ? $option['value'] : $input_value );
		}
		/**
		 * @internal
		 */
		protected function _get_defaults() {
			return array(
				'value' => ''
			);
		}
	}
	
	FW_Option_Type::register('FW_Option_Type_ThzTest');

change option type to thz-test

	'testingdefaultoption'    => array(
		'type'  => 'thz-test',
		'label' => __( 'Title', 'fw' ),
		'value' => 'Default text option',
		'desc'  => __( 'Icon title', 'fw' ),
	),

dont save anything , print returns null 

![screenshot_15](https://cloud.githubusercontent.com/assets/2340172/14526870/9709bcf4-0246-11e6-9874-e4613532ad9f.jpg)

**Comment by moldcraft** [comment]
Works for me

![](https://static.md/a88f02572d6a41bf322494e73eccc1f4.png)

I think you are doing something wrong on option type register. Do what [the docs](http://manual.unyson.io/en/latest/options/create-option-type.html#content) says

**Comment by danyj** [comment]
@moldcraft  same as in docs 

    add_action('fw_option_types_init', '_action_theme_include_custom_option_types');

**Comment by danyj** [comment]
```
function _action_theme_include_custom_option_types() {
    if (is_admin()) {

		require_once dirname(__FILE__) . '/option-types/thz-test/class-fw-option-type-thz-test.php';
		
    }
}
```

**Comment by moldcraft** [comment]
Do you see `is_admin()` in docs?

**Comment by danyj** [comment]
wauu!,  did not notice that at all , thnx!
