### ISSUE TITLE
WP-EDITOR option not working perfecly in addable pop-up window

### ISSUE THREAD

**Issue by AminulBD** [ThemeFuse/Unyson#146]
Hi,
I've getting problem when I'm using wp-editor in addable pop-up. The editor come smotthly but not working visual editor button.

Here is example:
![pop-up](https://cloud.githubusercontent.com/assets/5006546/5641470/9ccb6c8c-9663-11e4-92ff-cef8fd65faab.png)

Console Log:
![consol](https://cloud.githubusercontent.com/assets/5006546/5641489/dcb4872a-9663-11e4-87fd-281a02ba9245.png)

**Comment by moldcraft** [comment]
Add [`'reinit' => true`](http://unyson-docs.themefuse.com/en/latest/options/built-in-option-types.html#wp-editor) parameter ot `wp-editor` option

```php
'test-addable-popup' => array(
	'type' => 'addable-popup',
	'popup-options' => array(
		'test-wp-editor' => array(
			'type' => 'wp-editor',
			'reinit' => true, # <---
		),
	),
),
```
