### ISSUE TITLE
Memory size exhausted when create slider with posts population method

### ISSUE THREAD

**Issue by indopixel** [ThemeFuse/Unyson#1460]
Hi,

Thank you so much for this awesome framework. This helps me a lot. But I have a little issue as described below :

There was no problem when creating slider with posts population method. But when I create a post and insert a slider shortcode the error occured. I couldn't publish the post and the error message was : Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 77 bytes) in /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/unyson/framework/helpers/class-fw-cache.php on line 243

The problem occured after updating my wordpress to 4.5 

Best Regards,

**Comment by danyj** [comment]
did you set option default ? 

example 

     fw_get_db_settings_option('some_option','default');

**Comment by indopixel** [comment]
No, I didn't call fw_get_db_settings_option() at all. I tried using TwentyFifteen theme but the error still exist.

**Comment by danyj** [comment]
is unyson updated to latest version ? https://github.com/ThemeFuse/Unyson/releases/tag/v2.5.2

**Comment by indopixel** [comment]
Yes, it is. I tried with another population method and it works. The problem only exist if I choose posts population method.

**Comment by moldcraft** [comment]
Hello,

Comment [this line](https://github.com/ThemeFuse/Unyson-PopulationMethods-Extension/blob/v1.0.14/extensions/population-method-posts/class-fw-extension-population-method-posts.php#L152) until we will release the fix.

**Comment by indopixel** [comment]
Hi,
Thank you so much for your help, really appreciate it. :)
