### ISSUE TITLE
WP 4.5: empty sliders settings

### ISSUE THREAD

**Issue by ppov** [ThemeFuse/Unyson#1461]
After an update to WP 4.5 all metaboxes in sliders settings are empty.
There's exception in console:
`[Events] Exception  Object { exception: TypeError }`, fw-events.js[132:4]

**Comment by moldcraft** [comment]
Hello,

Please do Ctrl+R in browser.

**Comment by ppov** [comment]
Tried it, issue is still there

**Comment by ppov** [comment]
Oh, it's Unyson 2.5.2. Tested in FF 47, Opera 36, IE 11. Everything is the same with all other plugins disabled.

**Comment by moldcraft** [comment]
I edited a slider, opened the Add New Slider page, and there are no errors. How to test it?

Are your extensions up-to-date?

**Comment by ppov** [comment]
"Add new slider" page is fine. It's possible to add it, but new slider settings are empty as well.

**Comment by moldcraft** [comment]
It looks fine on my side

![](https://static.md/3544376e4495a56623c6e95b741d62d4.png)

Are your extensions up-to-date?

**Comment by ppov** [comment]
Yes, extensions are up-to-date. Sorry, forgot to note that I have Exposure theme. Maybe it's theme-related issue?

**Comment by moldcraft** [comment]
> Maybe it's theme-related issue?

Disable the theme and create a new slider.

**Comment by ppov** [comment]
Nope, with Twenty Fourteen enabled it's the same

**Comment by moldcraft** [comment]
Try to inspect the browser console error and find in which file:line it happens

**Comment by ppov** [comment]
Hm... Was updating everything yesterday and now noticed another update. After updating everything is back to normal. Closing. Thanks!

**Comment by moldcraft** [comment]
Which update, plugin or extension?

**Comment by ppov** [comment]
Unyson extensions

**Comment by moldcraft** [comment]
Ok
