### ISSUE TITLE
lamWP 4.5 and Unyson 2.5.2: there are a few bugs

### ISSUE THREAD

**Issue by tnthao10** [ThemeFuse/Unyson#1462]
Hi,
I had WP and Unyson latest version
http://prnt.sc/asfkjg
And I encountered a few minor bugs
http://prnt.sc/asfkqh
My page there are 11 section, when i drag section 11 up position 1, no phenomenon happens
And position at section 11 still that.

Please help me solve it,
Thanks

**Comment by moldcraft** [comment]
Please do Ctrl+R in browser

**Comment by tnthao10** [comment]
I tried Ctrl + R and Ctrl + F5
And re-install WP 4.5 and Unyson 2.5.2 but still that....

**Comment by moldcraft** [comment]
Maybe you have a cache plugin enabled?

**Comment by moldcraft** [comment]
Which theme are you using?

**Comment by tnthao10** [comment]
Hi, the problem has been solved
http://prnt.sc/asfkqh
--------
But when i drag section up or down, that section will disappears and have bugs
http://prntscr.com/asyitt
(I used Debug Bar to view error)
My builder extension
http://prntscr.com/asywo0
I do not know that error come from, you can give me a hint for it?
Thank you!

**Comment by moldcraft** [comment]
maybe there are updates available? https://github.com/ThemeFuse/Unyson/issues/1461#issuecomment-210325891

**Comment by tnthao10** [comment]
Oh, i'm sorry
Drag section up or down still normal
but i added new template have that bug(not drag section up-down)
http://prntscr.com/aszte5

**Comment by TrangDinhVan** [comment]
Hi, @tnthao10  how can you solve that problem? I have the same weird when update plugin and WordPress.

**Comment by tnthao10** [comment]
Hey @TrangDinhVan,
are you talking about this error?
http://prnt.sc/asfkqh
I deleted all the files and folders that are not needed here
framework-customizations/extensions/shortcodes/shortcodes/section
http://prntscr.com/atmsvr
Hope this helps.
++
also for this error
http://i.imgur.com/a7xyPSY.png
I unresolved

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/204

**Comment by tnthao10** [comment]
It worked thank you @moldcraft :+1:
