### ISSUE TITLE
Allow loader image to be overridden from theme/plugin

### ISSUE THREAD

**Issue by Nikschavan** [ThemeFuse/Unyson#1463]
The loader [svg image](https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw.js#L25) is coded right in the JS file which cannot be overwritten by theme authors, allowing a filter that will pass localized variable with the URL would be a solution to this.

If this is accepted, I can work on a PR for this.

**Comment by moldcraft** [comment]
Please PR
