### ISSUE TITLE
Bug with woffice 1.8.0 theme

### ISSUE THREAD

**Issue by mr-kofeiti** [ThemeFuse/Unyson#1467]
In the theme setting recently after I update Unyson to lastest version I got this error of setting page of theme(/wp-admin/themes.php?page=fw-settings):
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 16135481 bytes) in wp-content/plugins/unyson/framework/helpers/general.php on line 280

I can't access my theme setting after all.

I have woffice theme 1.8
Unyson 2.5.2
wordpress 4.5

**Comment by danyj** [comment]
there were several changes today , 
https://github.com/ThemeFuse/Unyson/issues/1460

download master , shortcodes and slider extension and do manual update, see if that fixes it.

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/203
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/202

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/201

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1460#issuecomment-210437628

**Comment by mr-kofeiti** [comment]
I Try all of them above #1460 (comment) fixed for https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues
I upload and extract theme to exact location that you said but still i have problem loading my theme setting.
Screenshots:
![b1](https://cloud.githubusercontent.com/assets/8203837/14580834/9835ec0a-03f0-11e6-96cd-ffa9ba34c7f4.PNG)
![b2](https://cloud.githubusercontent.com/assets/8203837/14580835/9839708c-03f0-11e6-8f17-166e4d7aa72f.PNG)

**Comment by danyj** [comment]
@2Fwebd   is developer , lets see if he is around to check this for you.

**Comment by danyj** [comment]
if this is in theme options than looks more like recursion because of empty 

    fw_get_db_settings_option

default value. like said @2Fwebd will know more about it.

**Comment by 2Fwebd** [comment]
Hi there ! 

Thanks @danyj for the help here :)

@mr-kofeiti do you have any ticket open on our ticket helpdesk about that ? https://alkaweb.ticksy.com/ 

Because we'll need some access and more details in order to find out what's going on. 

Keep me posted, 

2F

**Comment by mr-kofeiti** [comment]
@2Fwebd  I ticket on your ticket system.
