### ISSUE TITLE
wp menu

### ISSUE THREAD

**Issue by wontone18** [ThemeFuse/Unyson#1468]
```php
                    $menus = array(
                        'primary' => array(
                            'depth'           => 2,
                            'container'       => 'nav',
                            'container_id'    => 'nav',
                            'theme_location'  => 'primary',
							'menu_class'=>'nav navbar-nav color02',
							
							//'menu'=>
                            'fallback_cb'     => 'fw_theme_select_menu_message',
                        )
                    );
                    wp_nav_menu($menus['primary']);
```

i am using fw_theme_select_menu_message to retreive the menu from wp. but i want my first <li list should be in active mode.

in normally way without this framework it works but when i am using unyson it is not working.

**Comment by thednp** [comment]
Are you using the Megamenu extension?

**Comment by wontone18** [comment]
hi not it is wordpress menu i am using.

**Comment by moldcraft** [comment]
> fw_theme_select_menu_message

Please give us this function code here so we can test it.

Also give the exact steps to reproduce the problem. 1. 2. 3. ...

**Comment by wontone18** [comment]
function my_special_nav_class( $classes, $item ){
 if( is_single() && $item->title == 'Home' )
    {
        $classes[] = 'active';
    }
    return $classes;
}
add_filter( 'nav_menu_css_class', 'my_special_nav_class', 10, 2 );

here is the attach image screen shot. the first menu it should like the active one.

this is my code.
![menu](https://cloud.githubusercontent.com/assets/10259774/14603636/847751e8-058c-11e6-89d2-bba57d6744b9.png)

**Comment by moldcraft** [comment]
I added this code in my theme

```php
function my_special_nav_class( $classes, $item ){
	if ($item->title == 'CALENDAR' ) {
		$classes[] = 'hello-world';
	}

	return $classes;
}
add_filter( 'nav_menu_css_class', 'my_special_nav_class', 10, 2 );
```

and it works

![](https://static.md/9240bbb80202c3cbefd72a5f5d16c190.png)

**Comment by moldcraft** [comment]
If the problem comes from MegaMenu extension, you can [overwrite the walker](http://manual.unyson.io/en/latest/extension/megamenu/index.html#overwrite-the-walker)

**Comment by wontone18** [comment]
hi

i changed my code a bit its now working fine...
