### ISSUE TITLE
Small post editor bug

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1469]
If in post and you switch to builder , save , than switch back to default editor, the editor height is about 150px 

![screenshot_16](https://cloud.githubusercontent.com/assets/2340172/14579856/80f03b40-03b9-11e6-8298-3fb6a5c6ea5f.jpg)

**Comment by moldcraft** [comment]
I don't see this as a problem, it will expand/adapt when you will type more text.

**Comment by danyj** [comment]
@moldcraft  it does not bug me much but is different from a default editor height and it was not there before.
