### ISSUE TITLE
Register metabox from plugin

### ISSUE THREAD

**Issue by yongkiagustinus** [ThemeFuse/Unyson#1470]
Is there a method to register custom post type metabox from plugin ?

im currently working on a plugin that have custom post type and i want to use Unyson metabox for the cpt
Thank you!

**Comment by thednp** [comment]
Didn't you see this?
https://github.com/ThemeFuse/Unyson/issues/1407

**Comment by yongkiagustinus** [comment]
Thank you @thednp !! i didnt see that, i will try your tutorial

**Comment by thednp** [comment]
PS: Feel free to continue discussion in that topic or contribute with more findings.
