### ISSUE TITLE
theme options in javascript

### ISSUE THREAD

**Issue by sohaibmuzammal** [ThemeFuse/Unyson#1471]
Hi,

First of all, thank you very much for such an amazing framework.

I want to use the theme options in my javascript file, do you have any method which makes the theme options available to javascript?

Thanks

**Comment by thednp** [comment]
What exactly are you up to?

**Comment by sohaibmuzammal** [comment]
I want to execute a script in my js file, when a specific theme option is set to yes.

**Comment by thednp** [comment]
Well, you can hook a JS file into your theme and make it work only for your option ID.

**Comment by sohaibmuzammal** [comment]
Thanks, i understand this.

But i have other code in the file too. which i do not want to depend on the option ID.

so i wanted some thing like below:

`<script>
var myOption = get_db_option('option-id');
if(myoption=="yes"){
alert("wow");
}
</script>`

**Comment by thednp** [comment]
When does this happen? On load or change of some setting?

**Comment by sohaibmuzammal** [comment]
I am doing this on page load.

**Comment by thednp** [comment]
Well I would advise to have a look at that specific type of option;s JS you are using/targeting and try to duplicate & adapt to your need.

**Comment by sohaibmuzammal** [comment]
Thank you for your time.

**Comment by thednp** [comment]
Feel free to close the issue if that was useful.
