### ISSUE TITLE
How to Remove Description on the Slider?

### ISSUE THREAD

**Issue by blackmekemeke** [ThemeFuse/Unyson#1473]
Some of my custom slider doesn't need description option, how to disable this option on the slider editor?

thanks

![slider-editor](https://cloud.githubusercontent.com/assets/9511351/14586053/474a4582-04b5-11e6-9292-701f6fdf9824.jpg)

**Comment by llemurya** [comment]
@blackmekemeke please read this [answer](https://github.com/ThemeFuse/Unyson-Sliders-Extension/issues/6#issuecomment-76174357) and close the issue. Thanks.
