### ISSUE TITLE
Contact form email error message customization

### ISSUE THREAD

**Issue by buttzahid** [ThemeFuse/Unyson#1474]
how can we customize email error message?? 
we want to customize this function but don't know how to do
public function frontend_validate( array $item, $input_value ) {

**Comment by moldcraft** [comment]
Hello,

Have you tried [this solution](http://manual.unyson.io/en/latest/helpers/php.html#customize-errors)?

**Comment by buttzahid** [comment]
in which file in need to used this code?

**Comment by moldcraft** [comment]
`{theme}/functions.php`
