### ISSUE TITLE
not able to find the preview option for typography

### ISSUE THREAD

**Issue by sohaibmuzammal** [ThemeFuse/Unyson#1477]
I have used the typography-v2 option type, but not able to see the font preview in the drop down.
![screen shot 2016-04-18 at 3 11 44 am](https://cloud.githubusercontent.com/assets/8626629/14590414/4e3d1172-0513-11e6-95dc-1112992d979e.png)

Preview is available in your demo video.
Check @ 00:50 here https://vimeo.com/105002864

**Comment by moldcraft** [comment]
Hello,

Option type `typography` has preview, `typography-v2` doesn't.
