### ISSUE TITLE
TinyMCE not really working on Paragraph, blank line and link

### ISSUE THREAD

**Issue by Hasi2012** [ThemeFuse/Unyson#1478]
Paragraph and blank line does not work in "Visual view". If itry to set `<p> or <br> or &nbsp;` in "Text view", after save, they were lost. There is no way to make a good text layout. I tried it on different Themes with the latest Unyson version, same result. In the default wordpress TinyMCE there is no problem.
There is another mistake with links, when I try to make a link in "Visual view" there is no popup box. In "Text view" it will work.

![bildschirmfoto 2016-04-18 um 03 43 08](https://cloud.githubusercontent.com/assets/2829690/14591820/fb2d981c-0517-11e6-8504-fa836986eb6c.png)

**Comment by moldcraft** [comment]
> There is another mistake with links, when I try to make a link in "Visual view" there is no popup box.

I know about this issue but I don't know how to fix it. You can try to find the solution to help us.

**Comment by Hasi2012** [comment]
Thank you moldcraft, Paragraph and blank line does work now. If I could, I'd like to help you, but I'm not a programmer. I have much respect of your work and want to thank you for your commitment.
Greetings from Hamburg 
Hesi

**Comment by moldcraft** [comment]
Thank you very much for support

I wish you all the best!

Greetings from Moldova
