### ISSUE TITLE
[QUESTION] How to check if page is built with page builder or not?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1479]
I want to be able to use the default page template for simple page and the a custom template for pages built with page builder. How can I know my page is built with page builder?

**Comment by danyj** [comment]
fw_get_db_post_option(get_the_ID(), 'page-builder/builder_active', false)

**Comment by thednp** [comment]
Thanks @danyj, can you please elaborate on this piece of code? I mean what exactly `'page-builder/builder_active'` stand for?

**Comment by danyj** [comment]
exactly what you need , it is page built in option that is set to true once the builder is used in the post.

**Comment by duongancol** [comment]
you could also this helper: fw_ext_page_builder_is_builder_post($pageID)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.2/helpers.php#L3-L8

**Comment by danyj** [comment]
just do 

```
$builder_active = fw_get_db_post_option(get_the_ID(), 'page-builder/builder_active', false);

fw_print($builder_active);
```

in your page template and activate/deactivate builder

**Comment by danyj** [comment]
>you could also this helper: fw_ext_page_builder_is_builder_post($pageID)

I think that one is there only if page builder extension is active so you have to check for the existence , the page option check can be used without builder check

**Comment by duongancol** [comment]
I think check that helper exist or not first. If it's not, the page-builder always doesn't activate.
Like this: 
`if(function_exists('fw_ext_page_builder_is_builder_post') && fw_ext_page_builder_is_builder_post($post->ID))`

**Comment by thednp** [comment]
Thanks everyone.
