### ISSUE TITLE
Only this YouTube video not work for background section

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#1480]
Hello, please give me some advice. 
I used YouTube video for the section background, the weird is that, every video working fine, only this video not playing. I am using Firefox, the video is background of the first section of this site.
http://www.londonfilmschool.co.uk/event/cinematography-indoor-outdoor-lightning/
Theo video URL is: https://www.youtube.com/watch?v=_Wd61X8W0hQ
My custom needs that video, I search so much with the information when I use F12 of Firefox, but no luck.

**Comment by moldcraft** [comment]
![](https://static.md/92c9bd55d6d704125f6c8a6d16d5a5e5.png)
