### ISSUE TITLE
Unyson conflict with WooCommerce

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1481]
That's just an UI issue I have encountered. That's how tabs look on new product page.
![](https://i.imgur.com/bstrylF.png)

<hr>

I'm not sure why it's happening, maybe this is an issue that's comming from the @woothemes. I'm not really sure, Unyson tabs are implemented using jQuery UI?

**Comment by danyj** [comment]
we had this before , disable WOO UI

	function _action_theme_remove_jquery_ui_css() {
	
		if ( class_exists( 'WooCommerce' )  ) {
			wp_dequeue_style( 'jquery-ui-style' );
		}
	}
    add_action( 'admin_enqueue_scripts', '_action_theme_remove_jquery_ui_css', 99 );

**Comment by andreiglingeanu** [comment]
@danyj Thank you. It works fine.

**Comment by danyj** [comment]
@moldcraft  same conflict with Ninja Forms  http://prntscr.com/b6zmil

**Comment by moldcraft** [comment]
We are not enqueue any extra styles that break default wp styles, they (other plugins) are doing that, so please report that problem to them

**Comment by ivandotv** [comment]
Maybe there should be extra classes added to increase specificity?
