### ISSUE TITLE
[BUG] page builder problem with slider inside section makes edit page unreachable

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1482]
Steps to reproduce:
* create a new page
* create a slider (maybe any I'm not sure so far tested the manual populated)
* create a section and add the slider inside the section
* on save/update page the page becomes unreachable.

**Comment by moldcraft** [comment]
This should fix the problem https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/201

Make sure extensions are up-to-date (also you can click on the Check Now button on Updates page)

**Comment by moldcraft** [comment]
Please reopen/comment the issue if the bug is still there

**Comment by thednp** [comment]
Yes, I just updated the extensions via WP Updates and the issue is gone, no need to reopen, thank you.
