### ISSUE TITLE
[Question] add other types of options to 'template' => {{optionID}} for addable option types

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1483]
I am trying to get a `multi-picker` value to be the template title for an `addable-popup` via option setting

`'template'     => '{{ ct_type }}',`

and it's not working, it's blank all the way and the console shows no error.

**Comment by moldcraft** [comment]
* `{{ if (something) console.log("something"); }}` random javascript execution
* `{{- some_variable }}` html-escaped output
* `{{= some_variable }}` raw output

So in your case, first do `{{ console.log(ct_type); }}` to see the value structure, then `{{- ct_type.some_key }}`

**Comment by thednp** [comment]
Wow, that's cool, where... lemme have a look into my code.

**Comment by thednp** [comment]
The `'template' => '{{ console.log( ct_type.subOption ); }}',` shows the right value in the console, but the code `'template'     => '{{ - ct_type.subOption }}',` does not add anything into the box title.

**Comment by moldcraft** [comment]
Remove space from `{{ -`

**Comment by thednp** [comment]
Wonderful.
