### ISSUE TITLE
folder name conflicts

### ISSUE THREAD

**Issue by wontone18** [ThemeFuse/Unyson#1486]
hi

i think in your shortcode folder having naming convention issues for instance difference

1 'what we have done' section -> if this is the shotcode then it almost broken the shortcode and not reading it clearly. either its space should converted into "-" to detect the view.

2. what-we-have-done - yes if i am having this, it will pick the html from the shortcode/what-we-have-done/views/view.php - it works.

**Comment by wontone18** [comment]
one more quick question also, default team member shortcode coming with this framework, yes if i want i can use the custom team member shortcode. but if i want to edit this same shortcode? how i can edit this?

**Comment by wontone18** [comment]
yes ts existing with the plugin and for users preference i cant edit the plugin file. how can i access that same shortcode in my theme folder? instead of custom team member

**Comment by wontone18** [comment]
same this with existing slider extension. i want to change its html. if i will use same shortcode name with slider it will give a error.

**Comment by moldcraft** [comment]
> what we have done

You can't create shortcode names which contain spaces

> but if i want to edit this same shortcode? how i can edit this?

[team-member shortcode](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/v1.3.11/shortcodes/team-member) files can be overwritten by creating in your theme

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/team-member/{file-path}
```

----

Please read [the docs](http://manual.unyson.io/en/latest/extension/introduction.html#content)

**Comment by wontone18** [comment]
hi

i am creating slider by using the slider extension but nothing is coming in my page. i tried it through this basic example http://manual.unyson.io/en/latest/extension/slider/#template. it having 3 image set but slider is not working.

**Comment by moldcraft** [comment]
@wontone18 I am fixing the docs now.

**Comment by moldcraft** [comment]
[fixed](https://github.com/ThemeFuse/Unyson-Documentation/compare/f30271a37e193186848ae4a7af63760148086f56...169bab559d50f6ce40a288a27cdaa62ba70a3b2f) http://manual.unyson.io/en/latest/extension/slider/#create-a-simple-slider-type

**Comment by wontone18** [comment]
hi thanks for the new doc updation. i had checked with your example theme in inside the folder. Slider is coming with the html but its not visible. But let me check with the demo one and change it based on my slider.

i can able to create a shortcode but extension is more easy for the users. i will check it tonight.
