### ISSUE TITLE
Text loses paragraph formatting within the portfolio text module

### ISSUE THREAD

**Issue by Ryan529** [ThemeFuse/Unyson#1489]
Text loses all paragraph formatting in the text block, even if I manually add `<p>` tags. It works in a text block in a normal page, but for some reason it won't replicate that in a portfolio project page once it's saved and previewed.

**Comment by moldcraft** [comment]
Hi,

Unyson plugin is up-to-date? We fixed that in the latest version https://github.com/ThemeFuse/Unyson/issues/1478

**Comment by ssmc13** [comment]
I'm having the same issue in the text block. I updated WordPress to the latest version, as well as Unyson.

**Comment by moldcraft** [comment]
Please check if you have [this line](https://github.com/ThemeFuse/Unyson/blob/a67f4b38f32b048827752e7ddce8c1402f8749c0/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L29)
