### ISSUE TITLE
Custom Section Options

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#149]
Let's make the Custom Section options appear on click - http://joxi.ru/p27E6pZiod7Pr7. Now you have to click the Edit icon from the right hand side in order to make them appear and considering that we've built some important options in there I'd like to have them more accessible. 

All the shortcodes work that way, if you click anywhere on the shortcode the pop up with options appears, that should be the case for the Sections and Column as well if they have options.

**Comment by rockalife** [comment]
This was implemented in [v1.2.8](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/releases/tag/v1.2.8) of the Shortcodes extension
