### ISSUE TITLE
Open saving box modal before tabs initiation

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1491]
Not sure about others but I have many tabs in theme settings and on first time save click ( no tabs have been clicked ) there is about 3-4s delay until all tabs are initiated. The delay is not an issue itself but the saving modal does not open until  this process is done. Is there any way you can open the modal first and than initiate the tabs. 

Currently this looks like a glitch and user might think that saving has not started.

**Comment by danyj** [comment]
@moldcraft   please do something about this http://screencast.com/t/mvrgSmg9k
I cant organize the admin without tabs properly and more tabs I add the slower the first save gets, 

I have no issues with lazy_tabs initiation and speed but just show the saving popup first and than initiate the tabs.

**Comment by andreiglingeanu** [comment]
@danyj This is because it is doing `lazy_tabs` initialisation on save - and this one takes time.

Actually, we're not using `lazy_tabs` at all, it makes more harm than good.

A proper work-around for this will be to split your options across many pages, using [this](http://manual.unyson.io/en/latest/helpers/php.html#create-settings-page).

**Comment by danyj** [comment]
@andreiglingeanu , I see what you mean but I have templating system that needs to read all options at once in order to save them and if I split pages I wont be able to collect/load  all theme settings

**Comment by andreiglingeanu** [comment]
Then consider a way to better handle your `lazy_tabs` approach. Maybe give user a better feedback. Check Theme Settings code (and maybe change it) for more details.

**Comment by danyj** [comment]
@andreiglingeanu  I think that is what I am asking for with the post itself, 

lazy tabs are init on save ,  and I dont have a problem with it , issue is that the modal that says "saving" shows up at the end of tabs initiation instead before the initiation starts. 

Wait time for first save is about 3-6sec and nothing shows up/moves before init is done, 

so I just asked to show the popup before init,

**Comment by andreiglingeanu** [comment]
@danyj I'll be implementing `lazy_tabs` option for each tab. This way you can disable lazy tabs for a single tab instance. How's this sound to you?

**Comment by danyj** [comment]
that is what I suggested yesterday https://github.com/ThemeFuse/Unyson/issues/1924

but I  dont know why no one want to check this properly and see what I am seining ,  

we use  tabs to group options so that the users are not overwhelmed by the amount of options thus I used many of them , looking trough theme admin code I found 108 instances of nav-tab so is only natural that FIRST  lazy init will take some time and you cant see what I see if you test with 5 tabs, 

now  we are talking about an option to enable lazy on specific , fine , let see , 

I have 16  main side tabs in theme admin , and lets say I will use lazy only on them , I still think that the FIRST save will take same time because it has to convert all that HTML and we might endup with same issue back here.

So I dont know why we cant show that darn saving popup first and than init.

**Comment by andreiglingeanu** [comment]
> So I dont know why we cant show that darn saving popup first and than init.

We will. I didn't had time to change its initialisation time.

**Comment by danyj** [comment]
on the other hand,  since you will be messing with it ,   if we want to lower the init on theme admin tabs I would do this 

if lazy is enabled , 


do lazy by default on theme SIDE tabs  without us have to do this on them 

    'lazy' => true


set 

     ' lazy' => false 

on inner  tabs and we can than decide which one we need enabled, 

again I am talking only about theme admin here.

**Comment by danyj** [comment]
@moldcraft  did this make it in 2.6.1 ?  I updated today and the the popup is again waiting for tabs

**Comment by moldcraft** [comment]
Nope. This is all that 2.6.1 contains https://github.com/ThemeFuse/Unyson/compare/v2.6.0...v2.6.1

**Comment by danyj** [comment]
ok thnx!
