### ISSUE TITLE
Создание CSS файла из Theme Options

### ISSUE THREAD

**Issue by suvorovpro** [ThemeFuse/Unyson#1492]
Всем привет. 
Вопрос - использую Theme Options для задания некоторых CSS стилей для моей темы.
Мне очень рекомендовали те стили что я задаю через Them Options выводить в отдельный CSS файл. Подскажите пожалуйста как это сделать с помощью вашего фреймворка. 
Как вывести инлайн в страницу, я знаю, но так делать не рекомендуют, потому что потом модераторы в ThemeForest могут не пустить мою тему.
Заранее спасибо за совет.

Hello.
Question - Using Theme Options to define some CSS styles for my theme.
I recommend those styles that I ask through Them Options display in a separate CSS file. Please tell me how to do it with the help of your framework.
How to display inline in the page, I know, but do not recommend, because later in the ThemeForest moderators can not let my template.
Thanks in advance for your advice.

**Comment by moldcraft** [comment]
Добрый день,

On [these actions](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/core/components/backend.php#L1368-L1379) generate the css and save it in a file in `/wp-content/uploads/`, then enqueue it in frontend.
