### ISSUE TITLE
No more shortcode button in text mode

### ISSUE THREAD

**Issue by BiJeiTi** [ThemeFuse/Unyson#1493]
I use a theme with Unyson framework, after the upgrade to WP 4.5 the shortcode button disaper from the page editor in standard mode.
I'm used to build some page using only shortcode and not the complete visual page builder.
![unyson_noshortcodes](https://cloud.githubusercontent.com/assets/18589702/14700388/826a057a-079f-11e6-9536-de63cb992a82.JPG)

Is it possible to re-enable the shortcode button?

**Comment by moldcraft** [comment]
Hello,

This problem was already reported, check this issue https://github.com/ThemeFuse/Unyson/issues/1484
