### ISSUE TITLE
[Question] Can I search a post by meta option?

### ISSUE THREAD

**Issue by giathinh910** [ThemeFuse/Unyson#1494]
Is there any way that I can search a post by option, not by post name? Thank you.

**Comment by moldcraft** [comment]
You can make an option value to be saved in a separate meta by setting the `fw-storage` parameter

```php
'option_id' => array(
    'type' => 'text',
    'fw-storage' => array(
        'type' => 'post-meta',
        'post-meta' => 'YOUR_POST_META_NAME',
    ),
),
```

`post-meta` is optional and will be `fw:opt:{option_id}` if not specified https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/includes/option-storage/type/class-fw-option-storage-type-post-meta.php#L6

**Comment by giathinh910** [comment]
Thank you !!
