### ISSUE TITLE
Event when unyson has done initializing JS scripts.

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1495]
I have a **js** script that runs on `documet ready event`, and it looks at some options in the **tabs** made by unyson, and hides them.
The problem is that my script runs before the tabs are initialized, and so it can't find the options by their `id`.
So I was wondering is there any way for you to fire off an event when the unyson js script has done initializing, so I can pick up from there ?

**Comment by moldcraft** [comment]
Note that [lazy tabs](https://github.com/ThemeFuse/Unyson/issues/1174) are enabled by default, which means only the visible tabs are initialized.

1. You can listen each tab init and find your options https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/static/js/backend-options.js#L86

```js
jQuery(function($){
    setTimeout(
        function(){
            fwEvents.on('fw:options:init', function(data){
                if (!data.lazyTabsUpdated) return;
                
                // data.$elements.find('.your-elements') ...
            });
        }, 
        /**
         * later than other but a bit before 
         * https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/static/js/option-types.js#L6
         */
        20
    );
});
```

2. You can init all tabs and select your options https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/static/js/backend-options.js#L99-L101

```js
jQuery(function($){
    setTimeout(
        function(){
            fwEvents.trigger('fw:options:init:tabs', {$elements: $(document.body)});
        },
        /**
         * later than https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/static/js/option-types.js#L6
         */
        50
    );
});
```

**Comment by danyj** [comment]
@moldcraft   this is very expensive, with lazy_tabs



   		setTimeout(
			function(){
				fwEvents.on('fw:options:init', function(data){
					if (!data.lazyTabsUpdated) return;
						$('#fw-option-med_over-iceffect').on('change', function(e) {
							
								console.log('changed');	
							
						});
				});
       	 	},20 
		);



@moldcraft  check skype

**Comment by danyj** [comment]
must use  e.stopImmediatePropagation();

**Comment by moldcraft** [comment]
@danyj 

```js
fwEvents.on('fw:options:init', function(data){
    if (!data.lazyTabsUpdated) return;

    $('#fw-option-med_over-iceffect')
        .off('change.someNamespace')
        .on( 'change.someNamespace', function(e) {
            console.log('changed'); 
    });
});
```
