### ISSUE TITLE
Demo data & backups issue

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1496]
Hi again, team!

I have one more problem installing Demo data, it freezes on "Database restore" step, please see a screenshot https://yadi.sk/i/1KM2skj_rBda5.

Could you fix this problem please?

I have emailed FTP / website details to MoldCraft by email

Thank you again for your help

**Comment by danyj** [comment]
@moldcraft  this also happens your TF live demos lab. 
it runs forever even the install have finished it continues to run.

**Comment by moldcraft** [comment]
@WPJobs Please check error log for informative messages.

**Comment by WPJobs** [comment]
@moldcraft i added these strings in wp-config.php

```
define( 'WP_DEBUG', true);
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
```

but error log is empty inside the /wp-content/ directory

**Comment by moldcraft** [comment]
Please ask your hosting to give you the real error log (usually it is not in /wp-content/ directory)

**Comment by WPJobs** [comment]
@moldcraft finally, i've got "timed out" message https://yadi.sk/i/4Q5eG0kKrBnrJ
[errors.txt](https://github.com/ThemeFuse/Unyson/files/230428/errors.txt)

p.s. i have attached error log (latest 300 messages) from cPanel

**Comment by moldcraft** [comment]
Please fix that fatal error, remember which was the last error (its time), start the Demo Install, if it fails again, check the error log for new errors. At the moment there are no errors that come from the backups extension.

P.S. `PHP Warning:  Missing argument 2 for _FW_Component_Backend::_action_create_post_meta_boxes()` is from a plugin, it triggers `do_action('add_meta_boxes')` without second parameter (wrong)

**Comment by moldcraft** [comment]
Which hosting are you using?

**Comment by WPJobs** [comment]
@moldcraft this error dated as yesterday 2016-04-20, i see that there is no errors related due to Backups extension, and this is so strange for me too.

Client (who purchased my theme) using this hotsting http://www.turhost.com/

Should i recommend him to contact hosting provider regarding this issue?

**Comment by moldcraft** [comment]
Try before clicking on the Install button on Demo, execute [this code](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.8/extensions/backups-demo/views/page.php#L46) in browser console

**Comment by WPJobs** [comment]
@moldcraft it doesn't help, but thank you again for your time!

**Comment by moldcraft** [comment]
I will check my email later and inspect the problem on server

**Comment by Ataurr** [comment]
I am also getting same error. one of my client http://puu.sh/or5fM/38a01e3fd7.png

and then timed our error http://puu.sh/or5hf/a7366bd099.png

I have asked login details from client.

**Comment by moldcraft** [comment]
@WPJobs I added this code in `wp-content/plugins/unyson/unyson.php`

```php
<?php

function _error_debug() {
	if ($error = error_get_last()) {
		/**
		 * Usage:
		 * 1. Create a link here http://requestb.in/
		 * 2. Paste it in $url
		 * 3. Reproduce the error
		 * 4. Refresh http://requestb.in/.../inspect and check Request Body (at bottom)
		 */
		$url = 'http://requestb.in/...';

		switch ($error['type']) {
			case E_USER_WARNING:
			case E_USER_NOTICE:
				break;
			default:
				wp_remote_post($url, array(
					'body' => $error['message'] .' in '. $error['file'] .' on line '. $error['line'],
				));
				break;
		}
	}
}
register_shutdown_function('_error_debug');
```

I started Demo Install and I got this error

```
PHP Startup: Unable to load dynamic library '/opt/alt/php53/usr/lib64/php/modules/ffmpeg.so' - libswscale.so.2: cannot open shared object file: No such file or directory in Unknown on line 0
```

Please tell your hosting to fix it, then I will try to inspect the site again.

**Comment by WPJobs** [comment]
@moldcraft hi again! i'm sorry, but client installed demo data manually, i'll ask him to create another test subdomain

**Comment by Ataurr** [comment]
I have found 2 timed out error due to this

`mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/fisheaglelodge/public_html/wp-includes/wp-db.php on line 1515:`

and 
`Allowed memory size of 67108864 bytes exhausted (tried to allocate 32 bytes) in /home/fisheaglelodge/public_html/wp-includes/compat.php on line 97:`


I think it will be great if backup extension introduce a feature to check server minimum requirement to install demo content.

**Comment by WPJobs** [comment]
@moldcraft hi again! FYI, client said that host enabled "ffmpeg.so" module, and now he get following error on a test subdomain: "Important: HTTP Loopback Connections are not enabled on this server. 
If you need to contact your web host, tell them that when PHP tries to connect back to the site at the URL `http://test.mrtendustri.com/wp-admin/admin-ajax.php` and it gets the error `Operation timed out after 5001 milliseconds with 0 bytes received`. There may be a problem with the server configuration (eg local DNS problems, mod_security, etc) preventing connections from working properly."

We will contact to host again

**Comment by moldcraft** [comment]
@wpjobs try to install demo even if that error is showing, maybe it will work

**Comment by moldcraft** [comment]
If you get that warning, [the install is switched to ajax steps](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.8/extensions/backups-demo/views/page.php#L42-L47) ([js](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.8/extensions/backups-demo/static/page.js#L279-L284)) (you need to not leave the page until the install is finished) instead of background steps (you can start the install and close the window, it will continue in background)

**Comment by WPJobs** [comment]
@moldcraft hi again!

for a first client: now demo installation freezes on "unzip" step https://yadi.sk/i/dPBZ-gCarFihf and there is no any shutdown error http://requestb.in/txmmaptx?inspect

and... i have one more client who can't install the demo :) http://requestb.in/1b58hms1?inspect i believe it is related to this:

`Allowed memory size of 100663296 bytes exhausted (tried to allocate 72 bytes) in /home/grupoabre/public_html/wp-includes/compat.php on line 98`

what you can suggest, please :)

**Comment by Ataurr** [comment]
For last error increase memory_limit 256MB

**Comment by WPJobs** [comment]
@Ataurr Unfortunately, increasing memory_limit constant is not helpful for all hostings, it may work on some hostings but doesn't have any effect on others, e.g. for South America companies, most such problems arise from there :)

**Comment by moldcraft** [comment]
@WPJobs In [that code](https://github.com/ThemeFuse/Unyson/issues/1496#issuecomment-213386603) replace

```php
wp_remote_post($url, array(
    'body' => $error['message'] .' in '. $error['file'] .' on line '. $error['line'],
));
```

with

```php
wp_remote_post($url .'?'. http_build_query(array('url' => fw_current_url())), array(
    'body' => $error['message'] .' in '. $error['file'] .' on line '. $error['line'],
));
```

so you will be able to see from which url the request was made, this will help in finding the code where the error happens.

**Comment by WPJobs** [comment]
@moldcraft  I believe, this ticket can be closed, i can't catch an error with PHP, it posts absolutely nothing to requestb.in and finally i get TimedOut message. I will recommend users to contact to hosting provider regarding this issue, since it is related to memory limit or php modules (hosting settings)

Thank you for your time!
