### ISSUE TITLE
Is there any way to add custom font list to styling extension?

### ISSUE THREAD

**Issue by maryslen** [ThemeFuse/Unyson#1497]
Hi,

Styling extension uses google fonts from a certain list. How we can rewrite existing font list in framework-customization?

Thanks

**Comment by moldcraft** [comment]
Hello,

Try [this filter](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/helpers/general.php#L1020)

**Comment by moldcraft** [comment]
P.S. https://github.com/ThemeFuse/Unyson/issues/874

**Comment by moldcraft** [comment]
P.P.S. Have you tried to use `{theme}/framework-customizations/theme/options/customizer.php` ?

**Comment by maryslen** [comment]
Not yet, but will try. Thanks!
