### ISSUE TITLE
Unyson/framework/helpers - Error

### ISSUE THREAD

**Issue by edertuffic** [ThemeFuse/Unyson#1498]
Hi!
My site started showing errors like these:

Warning: explode() expects parameter 2 to be string, array given in /home/perca912/public_html/conquistecomhinode.com.br/wp-content/plugins/unyson/framework/helpers/database.php on line 22

Warning: array_shift() expects parameter 1 to be array, null given in /home/perca912/public_html/conquistecomhinode.com.br/wp-content/plugins/unyson/framework/helpers/database.php on line 23

Warning: explode() expects parameter 2 to be string, array given in /home/perca912/public_html/conquistecomhinode.com.br/wp-content/plugins/unyson/framework/helpers/database.php on line 22

Warning: array_shift() expects parameter 1 to be array, null given in /home/perca912/public_html/conquistecomhinode.com.br/wp-content/plugins/unyson/framework/helpers/database.php on line 23

Warning: explode() expects parameter 2 to be string, array given in /home/perca912/public_html/conquistecomhinode.com.br/wp-content/plugins/unyson/framework/helpers/database.php on line 22

Warning: array_shift() expects parameter 1 to be array, null given in /home/perca912/public_html/conquistecomhinode.com.br/wp-content/plugins/unyson/framework/helpers/database.php on line 23

Can you help me please?

**Comment by moldcraft** [comment]
Hi,

Add <a href="https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/helpers/database.php#L21">here</a> `fw_print($option_id)`

**Comment by edertuffic** [comment]
Hi!

Does not work :(
See the pictures.

2016-04-23 4:36 GMT-03:00 moldcraft <notifications@github.com>:

**Comment by thednp** [comment]
All your errors seem to me like your options arrays are either not properly written.

**Comment by edertuffic** [comment]
Sorry but I did not.

Everything was normal and did not make any changes.

It seems to me started to give this message after upgrading to Wordpress
4.5.

Is there a way to solve this?



2016-04-23 10:14 GMT-03:00 thednp <notifications@github.com>:

**Comment by moldcraft** [comment]
> @moldcraft Add here fw_print($option_id)

&nbsp;

> @edertuffic Does not work :(

It will not work, that will print debug info so you can inspect why/which option_id is specified wrong.

**Comment by edertuffic** [comment]
Hi!
I have information that may help.

I did a fresh install of Wordpress elsewhere and installed two themes:
AppLand and MT-Four

The error displayed is happening with the AppLand theme installed (img4).

This theme adds a tab elements in Page Builder (img3)


When active theme MT-FOUR of the same company Codexcoder, the error does
not happen and is not added any tab elements in Page Builder (img5).

It may be some incompatibility with the theme AppLand? Though always
functioned normally until the update of Wordpress 4.5.

Thanks for attention!
Eder

2016-04-23 11:18 GMT-03:00 moldcraft <notifications@github.com>:

**Comment by thednp** [comment]
Well we can't see any of the (img5) images you're posting, and we can't see any actual code that uses the framework, we can't simply guess what the code looks like or why the WP upgrade prodices the issue, I would suggest sending an e-mail to @moldcraft with your site's FTP and wp admin account, he would check and come up with a fix asap.

As a little side note, this could very much be a user/server issue, not really a framework issue really, so I figured you would have to know this fact. Generally this has to do with: sometimes files get simply corrupted perhaps the drives storing them get damaged or supported PHP version is simply not compatible.

**Comment by moldcraft** [comment]
@edertuffic Thank you for ftp details.

In `{theme}/framework-customizations/unyson-custom-functions.php` there is

```php
fw_get_db_settings_option(['css_settings']);
```

which is wrong, it must be

```
fw_get_db_settings_option('css_settings');
```

**Comment by edertuffic** [comment]
I made the change but still with the same error :(

2016-04-23 16:44 GMT-03:00 moldcraft <notifications@github.com>:

**Comment by thednp** [comment]
Then find all instances of the similar fix applied, perhaps reading the code would also help.
I know this is alot of hard work, but it's actually the best thing to do. I do it too.

**Comment by edertuffic** [comment]
Hi!
you could've give me a guidance what should I look for? because I know
nothing of programming and do not even know where to start .
I must get in touch with the theme of support? The problem may be the theme and
not the plugin?
Sorry but really I do not know where to start .
Thank you for the patience.


Em sábado, 23 de abril de 2016, thednp <notifications@github.com> escreveu:

**Comment by thednp** [comment]
You better head to the theme developer for support, that's best.
