### ISSUE TITLE
xml file import is not working

### ISSUE THREAD

**Issue by mrinal013** [ThemeFuse/Unyson#1499]
Hello,

I am trying to get customer a second option to use xml file for data import. Demo content install is working fine, but xml file import is not working.

I am facing a problem when import xml file. Page is shown ok. But, it does not shown the content of  visual page builder. Please see the screenshot
http://prntscr.com/avq9db

Thanks in advance

**Comment by moldcraft** [comment]
Hello,

We don't support WP default xml file import. If you know how to fix it, please submit a pull request.
