### ISSUE TITLE
how i can use slider shortcode directly in PHP file

### ISSUE THREAD

**Issue by alkeshgupta** [ThemeFuse/Unyson#150]
Hello,

Like example .. i created a slider named "HOMEPAGE" i want to use it like this in php file

<?  echo do_shortcode('[slider name='HOMEPAGE']');?>

is that possible if yes what is the correct code ?

**Comment by llemurya** [comment]
@alkeshgupta you can do this by call a slider render method, please read about that in our [documentation](http://unyson-docs.themefuse.com/en/latest/extension/slider/index.html#frontend-render)
