### ISSUE TITLE
Minify extension CSS and JS

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#1501]
Unyson extensions CSS and JS should be minified to try and help performance on sites using the Unyson framework alongside shortcodes/plugins.

**Comment by moldcraft** [comment]
So we should have 2 versions of all css/js, for e.g. `hello.js` and `hello.min.js` and after each change in `hello.js` to not forget to update `hello.min.js`?

**Comment by danyj** [comment]
@moldcraft  , no I think @martinburdon  is talking about minify class for css and js , 

combine all css js in to one, like compression plugin but unyson based  like https://wordpress.org/plugins/autoptimize/

**Comment by moldcraft** [comment]
Just installing a plugin that does that (minify/combine) isn't enough?

**Comment by danyj** [comment]
It is man , no one  says that we cant find plugins , but having Unyson based compression plugin like we have megamenu , SEO , etc would be sweet. 

1. you have all in one framework
2. you have reliable code and support
3. you have reliable code and support
4. you have reliable code and support
5 you have reliable code and support
6. you have reliable code and support
.............................:)



I think you get the idea

**Comment by danyj** [comment]
and you dont have to mess with 3rd party stuff, everything under one roof,

**Comment by thednp** [comment]
@danyj I have to agree with that, but only up to a point. I personally found ways to optimize page load by combining several CSS/LESS into one file, or several google fonts into one `<link>` resource, so I would **only** need a way to merge and minimize JS files.

So for all of you reading, I think it's really hard to make an extension that does it all and for all kinds of needs (as I described mine). I don't think we need to reinvent the wheel in this case, not to mention the struggle to maintain and keep up with PHP and WP versions.

**Comment by danyj** [comment]
I dont have time now , but once we release the theme and I have no bigger projects il move mine to WP and maybe even make it Unyson based. https://github.com/youjoomla/jcompress
for now autoptimize does exactly same think as my plugin for j
