### ISSUE TITLE
Possible conflict in Customizer with Jetpack Extra Sidebar Widgets

### ISSUE THREAD

**Issue by ciorici** [ThemeFuse/Unyson#1502]
If I use the Page builder from Unyson and also have the Extra Sidebar Widgets module enabled in Jetpack, then I see a lot of errors in the console when using the Customizer.

These errors disappear if I disable the Unyson.

The problem happens in default WP theme.

![screen shot 2016-04-24 at 11 59 00](https://cloud.githubusercontent.com/assets/1674706/14766494/2f0191dc-0a15-11e6-858e-cc9564443f43.png)

**Comment by moldcraft** [comment]
On my side I have [no errors](https://static.md/3e1a5149eadf66bb4b28f3972a28d409.jpeg)

[Extra Sidebar Widgets is active](https://static.md/ba56dcf910f9bee7ce789dac647c5042.png)

**Comment by jeherve** [comment]
That's a known Jetpack issue, and it will be fixed i n the next release. You can follow our progress on this here:
https://github.com/Automattic/jetpack/pull/3738

**Comment by moldcraft** [comment]
@jeherve Thank you!
