### ISSUE TITLE
Page Builder edit screens go blank after updating plugin

### ISSUE THREAD

**Issue by dave9621** [ThemeFuse/Unyson#1503]
I posted this in your support forum and haven't gotten a response, I thought this might be a more appropriate place to ask for support.

I'm having a problem with the page builder after updating it. When I try to edit a content element the popup edit screen comes up but is completely blank. I tried to go back and install older versions of the plugin with some success, I was able to edit some of the layout components, but some of the Text Blocks come up blank. And if I try to edit in the Default Editor and make my changes then it clears out all of the content and gives me one text block with a line of code. And then my homepage won't load. Please help.

**Comment by dave9621** [comment]
I think I resolved my problem. I removed the plugin and reinstalled it. That seems to have done the trick, I'm back in business.

**Comment by danyj** [comment]
shift+ refresh next time you update the plugin
