### ISSUE TITLE
How to get the value from my options?

### ISSUE THREAD

**Issue by webeps** [ThemeFuse/Unyson#1504]
Hi, im create custom taxonomies "model-auto"
and create options "\framework-customizations\theme\options\taxonomies\model-auto.php"

`$options = array(
                'price_car' => array(
		'label' => __( 'Price', 'peugeot_single' ),
		'type'  => 'text',
		'desc'  => __( 'Price a Car', 'peugeot_single' ),
	),
);
`

All ok.  I have field - "Price" , but how to output the value where I want?
Hellp me pls. I'm try use - fw_get_db_term_option() but this not worked. 
Сan not understand what is  $term_id?

**Comment by webeps** [comment]
OMFG. IM DID IT !!!!!!!!11111 ALL WORKED....

`<?php echo fw_get_db_post_option($post_id, 'price_post_auto') ?>`

and even is working in the loop

````
<?php

global $post;

$args = array(
	'numberposts' => 0,
	'posts_per_page' => -1,
	'post_type' => 'handbook-post',

);

$myposts = get_posts( $args );

foreach( $myposts as $post ){ setup_postdata($post);
```

	$cur_terms = get_the_terms( $post->ID, 'handbook-type' );
	foreach( $cur_terms as $cur_term ){
	echo '<li><a href="#">' . $cur_term->name . '</a>';
	}
	?>
	<div><a href="#"><?php the_title(); ?></a>
	<?php the_content();?>
	<p>Price auto -<?php echo fw_get_db_post_option($post_id, 'price_post_auto') ?></p>
	</div>
	<?php echo '</li>';
	}
	wp_reset_postdata();?>`

**Comment by danyj** [comment]
> and to cleanse my karma

not after your cursed the god it wont :)

here is more info and instructions on how to get options 

http://manual.unyson.io/en/latest/helpers/php.html#database

**Comment by webeps** [comment]
@danyj Thx, I use the documentation, but I do not always all understand.
