### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by kaxigt** [ThemeFuse/Unyson#1505]
Problem to get the slider to work. I have chosen the second one (slider) and everything seems to work when you are in back end, but in front end only one img shows up for about 3 secs and after that the slider totally disappear on the page. Bug? Known plugin conflict?

Edit/ i have updated extensions >>  PopulationMethods v1.0.15 | Release date 18.04.2016 #201 without any success. The problem remains.

**Comment by moldcraft** [comment]
> I have chosen the **second one**

Can you give a screenshot?

Also which theme are you using?

**Comment by kaxigt** [comment]
Hello, i found this particular error and solved it. Now it works. I made my
themes and It was a particular code in the functions file (transfer all my
javascript to the footer) who bugged with unysons slider, HOWEVER, i also
got this warning today and my IP became banned - it seems your font "
fonts/Unycon.ttf" reacts and triggers a mode_security rule on the server.
We made a work-around the problem. Perhaps this isn't so important but I
wanted you to know if another got the same problem. =)

Error message:
[Mon Apr 25 12:38:44 2016] [error] [client 83.251.19.92] ModSecurity:
Access denied with code 403 (phase 1). Pattern match "^(%(u00)?2d|-)[^=]+$"
at QUERY_STRING. [file "/usr/local/apache/conf/modsec2.user.conf"] [line
"1064"] [id "1500333"] [hostname "demo.kaxigt.com
<http://l.facebook.com/l.php?u=http%3A%2F%2Fdemo.kaxigt.com%2F&h=uAQFfmsq7>"]
[uri
"/happy/wp-content/plugins/unyson/framework/static/libs/unycon/fonts/Unycon.ttf"]
[unique_id "Vx3ztEgdXr4ADBsKVp4AAAAD"]

Kindly Lillan

2016-04-25 11:14 GMT+02:00 moldcraft <notifications@github.com>:

> I have chosen the *second one*
>
> Can you give a screenshot?
>
> Also which theme are you using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1505#issuecomment-214222601>
>



-- 
Carpe momentum - Fånga ögonblicket innan det är för sent...
