### ISSUE TITLE
Taxonomy options show up on default taxonomy page listing

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1507]
I don't think this is how it supposed to be.
![screenshot - 250416 - 18 08 51](https://cloud.githubusercontent.com/assets/390700/14790297/efae7624-0b10-11e6-8d3a-98618a9cdbb8.png)

As you can see at the bottom of the screen I'm seeing options that should be shown only on single taxonomy page itself. 

Using unyson 2.5.3

**Comment by ivandotv** [comment]
I see why they show up there, but to me it a little counterintuitive.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1129
