### ISSUE TITLE
Is Unyson passing TF requirements? 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#151]
I see many people asked this before but there are no clear answers. Is either wait or I dont know jet or there is a bug but we dont know. So the question is,  is Unyson passing TF requirements?

**Comment by 2Fwebd** [comment]
Hello,

I don't know if there is any approved theme built with Unyson on Themeforest yet (nothing found when I search). But I personally submit mine, next week so I'll keep you informed. 

However, it passes Themeforest themecheck validation very well. So I don't think there will be a problem.

Nevertheless for now it is quite not usable for buyers cause of the Github API rate limit, but they're working on (see https://github.com/ThemeFuse/Unyson/issues/138). I suit my HTML template into a Wordpress theme in less than 3 weeks, with a lot of awesome features ! The only problem is as I said the extensions and Github. (In my opinion)

**Comment by danyj** [comment]
OK Unyson  scratch theme is not passing by default , 
http://www.uploady.com/#!/download/EzTkMyCGjIX/jrjfE1Shz8KoYZm8
I see it is minor issues but still.

**Comment by 2Fwebd** [comment]
Well, you can fix them in a minute ! It is definitely not the problem ;) Those ones are less than minor..

**Comment by danyj** [comment]
Never mind those. Here comes a real question pulled from  reading between lines here #152 if we extend or try to extend Unyson  options within theme, theme wont pass. 

Can we extend unyson from the theme and pass TF ?

For you to understand why I am concerned so much is because I have over 100 themes ready for wp conversion and I am looking for a reliable options framework. Unyson looks more than promising but it is unclear where the limitations are.

**Comment by 2Fwebd** [comment]
Not at all :) 
Here it is an example : https://www.evernote.com/shard/s281/sh/617738dd-14d8-4d37-abd3-dc43e845877e/80f86c0964d7640f7028e907072e81fe
You can create anything you like such as Post Options/Theme Panel/ Extended menu/Custom Plugins/Post types....
The only problem, is that some of these functionalities such as the custom post types have to be wrapped in a plugin. Btw I'm not developper, I prefer frontend stuffs but with knowledge in WP and a good documentation (Unyson one) it's really easy to convert in WP a complex HTML template. I can provide you more informations about mine. But for now all was pretty easy and Unyson team is really active ! :)

**Comment by 2Fwebd** [comment]
Hello @danyj ! 
Just to confirm you and everyone else that you *can upload your theme working with Unyson on Themeforest*. Mine was just accepted today !! ;)
http://themeforest.net/item/starry-creative-easy-wordpress-theme/10100894
Thank you @moldcraft for all the help !!

**Comment by danyj** [comment]
@2Fwebd nice news bud and good luck!

**Comment by moldcraft** [comment]
@2Fwebd :+1:

**Comment by danyj** [comment]
@2Fwebd  Did you update Unyson ? 
you have the old bug where css is inside the body #153  so your html is not validating
http://validator.w3.org/check?verbose=1&uri=http://2f-design.fr/themes/starry/

**Comment by 2Fwebd** [comment]
I think I have the latest release, I'll check.  Actually, they made an exception here because I fixed many other ones ;)

**Comment by moldcraft** [comment]
@2Fwebd It is not the latest release.

[There](http://2f-design.fr/themes/starry/wp-content/plugins/unyson/framework/extensions/shortcodes/) is [a file called `.gitmodules`](http://static.md/7c6f29d5a8bb3ac89fe10dc1d4f14539.png) which was removed in the latest version. Here it is in [v1.2.6](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/b0506930f07770dd7afa857856bf4c61daa0edc2) but not in [v1.2.7](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/620f95dcca4935ad20715fce567e03665e699e64).

Can you please update extensions on [your demo](http://2f-design.fr/themes/starry/) so we can inspect this issue https://github.com/ThemeFuse/Unyson/issues/153#issuecomment-71639825

**Comment by danyj** [comment]
@moldcraft I test it on my local and the files are placed in head in latest version , updated everything 10min ago.

**Comment by 2Fwebd** [comment]
Thank you for the feedback ! ;) I updated to 2.1.18 and removed the file. But it seems that the errors are still here. However, I don't think that there is any impact but I have a bunch of custom shortcodes in the theme files (framework-customizations/extensions/... )
Let me know if you need more details.

**Comment by moldcraft** [comment]
> I updated to 2.1.18

I didn't mean to update the framework, but the extensions. *(anyway it's good that you updated it)*

> and removed the file.

No need to remove the file manually, just update the extensions and the file will be removed automatically.

I mentioned that file just to confirm that you don't have the latest version of the shortcodes extension, it doesn't affect anything that we are talking about.

So just update the extensions. (You can click the "[Check again](http://static.md/4467f83abc7db67bc4e85cb16316c94a.png)" button to reset the updates cache)

**Comment by 2Fwebd** [comment]
Sorry... I just did it and it works perfectly !!! ;) http://validator.w3.org/check?uri=http%3A%2F%2F2f-design.fr%2Fthemes%2Fstarry%2F&charset=%28detect+automatically%29&doctype=Inline&group=0

Thank you very much !!

**Comment by danyj** [comment]
@2Fwebd there you go ! :+1:

**Comment by moldcraft** [comment]
http://themeforest.net/forums/thread/meet-unyson-the-free-drag-drop-wordpress-framework/141818?page=17&message_id=1219088#1219088

**Comment by SenikaIndo** [comment]
> Hello @danyj !
> Just to confirm you and everyone else that you **can upload your theme working with Unyson on Themeforest**. Mine was just accepted today !! (from scratch with Unyson one!) ;)
> http://themeforest.net/item/starry-creative-easy-wordpress-theme/10100894
> Thank you @moldcraft for all the help !!

Sorry, because I am a beginner, and often fail when I send my theme. Will this Notification pass the theme review in Themeforest?

REQUIRED: The theme uses the register_post_type () function, which is plugin-territory functionality.

But if I change the function.
$ register_post_type = 'register_'. 'post_type';
$ register_post_type ($ this-> post_type, $ args);

It doesn't look like this error will be received ...?
What about you with the same problem as me. so that you passed the Themeforest review?
Please help?
