### ISSUE TITLE
Warning upon plugin activation

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1510]
When I activated the plugin I have got this message

 Warning: session_start(): open(c:/wamp/tmp\sess_eic1bdsvlhji9t80gdpuonkes1, O_RDWR) failed: No such file or directory (2) in C:\wamp\www\sofia\wp-content\plugins\Unyson-master\framework\helpers\class-fw-flash-messages.php on line 

How can I solve this?

**Comment by moldcraft** [comment]
Make sure the directory `c:/wamp/tmp` exists.

https://www.google.ru/#q=Warning:+session_start()+No+such+file+or+directory
