### ISSUE TITLE
How to Enqueue Button Shortcode Dynamic CSS in Table Shortcode?

### ISSUE THREAD

**Issue by blackmekemeke** [ThemeFuse/Unyson#1511]
I add styling option to button shortcode (change color etc.). I'm using [this solution](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head) to enqueue the dynamic styles. It works fine on button shortcode, but it doesn't work on button on table shortcode. How to enqueue the dynamic CSS generated by button option in table Sshortcode?

Thanks

**Comment by moldcraft** [comment]
> but it doesn't work on button on table shortcode

What exactly is not working?

Table shortcode contains all the data attributes, you must decode them and loop through each button and enqueue styles.

**Comment by blackmekemeke** [comment]
Ok thanks, problem solved.
