### ISSUE TITLE
Unyson page builder elements title issue

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#1512]
Hi team,

My page builder elements is showing issues with the element title, a function name is shown at the name field
function (n){return o.call(this,n,m)}

Any idea why this happens?
![unyson issue](https://cloud.githubusercontent.com/assets/11642633/14815722/aa7c57aa-0bca-11e6-8391-6b5135c058d5.png)

**Comment by moldcraft** [comment]
Hi,

Update extensions then hard refresh the browser.

**Comment by linjo** [comment]
Extensions are up to date, I did hard refresh also. But no luck.

On 26 April 2016 at 18:04, moldcraft <notifications@github.com> wrote:

> Hi,
>
> Update extensions then hard refresh the browser.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1512#issuecomment-214724883>
>



-- 
Linjo Joson

**Comment by moldcraft** [comment]
Try to reInstall Unyson.
