### ISSUE TITLE
Megamenu extension - remove some functionality

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1513]
I will be using mega menu extension only for the **icon** functionality, and only in the backend (custom walker for the front end)  it would be nice if we could lets say via filters, enable/disable some of the functionality of the extension.
There is always a css way and just hiding the buttons/functionality you don't want the user to use.
But that seems like a hack.

**Comment by moldcraft** [comment]
Please list all the functionalities you want to be able to enable/disable.

```
1. ...
2. ...
...
```
