### ISSUE TITLE
Hook for custom options in Megamenu admin walker

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1514]
It would be nice if we could hook in to the `start_el` method of `FW_Ext_Mega_Menu_Admin_Walker` so we could add our own options.

**Comment by thednp** [comment]
I was asking the same thing some time ago, the best thing to do is still a custom nav-walker class. Or if you use the Megamenu extension you can actually override that one.

**Comment by moldcraft** [comment]
Try [this solution](https://github.com/ThemeFuse/Unyson/issues/240#issuecomment-187221115)

Let me know if it works fine for you and I will merge it in master.

**Comment by ivandotv** [comment]
@thednp I'm overriding the class method at the moment.
But the way it is structured, I need to copy the code from the original class method, and that can be a problem with future updates of the parent class.

I'm gonna try that filter from the solution posted by moldcraft, and report the results.
