### ISSUE TITLE
Unyson activation for ThemeForest theme

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#1515]
Hello, I've currently got a theme in soft reject at ThemeForest and a couple of the issues I'm receiving from the reviewer is related to Unyson not being enabled, the issues are style related that depend on some options from the Theme Settings.

I'm using TGMPA to ask the user to activate the Unyson plugin but the reviewer is picking up on these issues as they occur when the plugin is not activated.

Is there a way or is it even permitted to force activation of the plugin on theme activation, or is it just a case of fixing these style issues for when the plugin is not activated?

Thanks for any input

**Comment by danyj** [comment]
@martinburdon  you mean to say that your theme does not work without Unyson  or am I misunderstanding ? If yes , setup your db options with default values or   simply place null, 

    fw_get_db_settings_option('option', null);


 ( should be doing this from start ) so that the theme itself is not Unsyon dependent.

**Comment by danyj** [comment]
and number one should have been making own theme option that returns same thing like 

       fw_get_db_settings_option


see this   https://github.com/ThemeFuse/Unyson/issues/1356#issuecomment-210355337

it is a mix of what I was trying to do but will get you in the  right direction

**Comment by moldcraft** [comment]
@martinburdon You theme must work (must not throw errors) without any plugin installed.

**Comment by martinburdon** [comment]
Thanks @danyj, yes I think I need to set defaults to solve my problem.

It's not that the theme doesn't work, there's just no styles for things that I set in the Theme Settings so adding defaults should fix this.

I guess in a way the theme wouldn't work without Unyson as all of the shortcodes/extensions are built on the plugin but at least if I set some style defaults the theme will look ok until they enable it.

Thanks 👍

**Comment by danyj** [comment]
than you need to make your own options function , if you have used  `fw_get_db_settings_option` anywhere in template files and unyson is disabled you will have errors.

**Comment by danyj** [comment]
or simply do if function does not exist return your fake fw_get_db_settings_option function

**Comment by martinburdon** [comment]
Yes everywhere that I use `fw_get_db_settings_option` I do a check for it existing first with `( function_exists( 'fw_get_db_settings_option' )`.
So do you mean if it is not available just supply a default for backup?

**Comment by danyj** [comment]
right , just fake it in case they turn it off and return your defaults again

**Comment by martinburdon** [comment]
Thank you 👍

**Comment by martinburdon** [comment]
So close to getting my theme accepted 😬

**Comment by danyj** [comment]
like this 

http://stackoverflow.com/questions/4351835/in-php-how-do-i-check-if-a-function-exists

**Comment by danyj** [comment]
http://prntscr.com/ax6as4

**Comment by danyj** [comment]
here , something along these lines just to get the defaults out 


```
if (!function_exists('fw_get_db_settings_option')) {

     function fw_get_db_settings_option($id,$default = null){
		 
	   if($default){
       	return $default;
	   }
	   
     }

}
```
