### ISSUE TITLE
Contact form issue

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1517]
Hi!

I noticed that "Contact form" element doesn't work after demo data installation. It always displays "Configure mailer" notice and it doesn't save any settings in Mailer tab, please see screenshots

![sc1](https://cloud.githubusercontent.com/assets/12991525/14827084/59008d6e-0be9-11e6-8c3c-955de1be9206.png)
![sc2](https://cloud.githubusercontent.com/assets/12991525/14827083/59002c48-0be9-11e6-9026-bcd1d238432f.png)

 screenshots

**Comment by WPJobs** [comment]
Hi again!

Regarding this issue, it seems that "From address" field have max length limitations, e.g.:

test@site.com can be saved normally

noreply@licenciadeactividad-abstrac.com - can not be saved, if you paste this address in "Mailer" tab settings, "from address" field and save the page, it causes a bug, please check this

**Comment by moldcraft** [comment]
> I noticed that "Contact form" element doesn't work after demo data installation. It always displays "Configure mailer"

Yes, mailer settings contain private smtp settings and are not included in Content Backup (Demo Install). https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.8/hooks.php#L28-L37

> noreply@licenciadeactividad-abstrac.com - can not be saved, if you paste this address in "Mailer" tab settings, "from address" field and save the page, it causes a bug, please check this

On my side everything is saved fine and the form is working.

**Comment by WPJobs** [comment]
@moldcraft i did some test, please see my second message:

it seems that "From address" field have max length limitations, e.g.:

test@site.com can be saved normally

noreply@licenciadeactividad-abstrac.com - can not be saved, if you paste this address in "Mailer" tab settings, "from address" field and save the page, it causes a bug, please check this

**Comment by moldcraft** [comment]
Please download the latest Mailer extension and Unyson from Github and test.

**Comment by WPJobs** [comment]
@moldcraft will do this right now, thank you!

**Comment by moldcraft** [comment]
Thank you for reporting and good details about the issue.
