### ISSUE TITLE
Unyson is not properly prepared for localization

### ISSUE THREAD

**Issue by dinhtungdu** [ThemeFuse/Unyson#1519]
I really want to translate Unyson to Vietnamese because I develop website for Vietnam market. But when I went to [GlotPress](https://translate.wordpress.org/projects/wp-plugins/unyson), I got error message that Unyson can't be translated.

Will Unyson support localization? I'll very happy to translate it to my language!

**Comment by duongancol** [comment]
Nice buddy, I'll support you. 💯

**Comment by Ataurr** [comment]
Agree 👍

**Comment by moldcraft** [comment]
Hello @dinhtungdu 

For translations we use this tool https://www.transifex.com/themefuse/unyson/

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/tree/master/framework/languages
