### ISSUE TITLE
Can we have some valid instructions?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#152]
The frameworks looks fine and usable but the docs are incorrect. 
I had to go to a German website in order to find out how to integrate it in my theme
http://www.drweb.de/magazin/unyson-framework-teil-2-entwickeln-sie-ihr-wordpress-theme-50086/
According to your docs all we need is framework folder and link to bootstrap inside functions.php where in fact looks like we need much more than that. 

Can someone please write few steps in order to include the unyson inside a theme

**Comment by moldcraft** [comment]
That article is outdated (it's for version 1). We do not include the framework in the theme anymore, because the theme will not pass theme-check. That's why we changed the framework to be as plugin https://wordpress.org/plugins/unyson/ . You simply install the plugin and that's all.

**Comment by danyj** [comment]
OK bud I see that and is nice but how do I get my own options inside the theme? That is the crucial part

**Comment by danyj** [comment]
If you don mind just give me an example on twentyfifteen

**Comment by moldcraft** [comment]
[These](http://unyson-docs.themefuse.com/en/latest/convention/directory-structure.html#content) are all the directories and files that you can create in your theme and the framework will load them automatically.

So for a quick demo, create the file `{your-theme}/framework-customizations/theme/options/settings.php` with the following contents:

```php
<?php if ( ! defined( 'FW' ) ) die( 'Forbidden' );

$options = array(
    'demo_text' => array(
		'label' => __( 'My Theme Option', 'unyson' ),
		'type'  => 'text',
	),
	'demo_short_text' => array(
		'label' => __( 'My Theme Second Option', 'unyson' ),
		'type'  => 'textarea',
	),
);
```

Refresh your admin page, and under the Appearance menu you will see the Theme Settings menu, there  you will find these 2 options.

**Comment by danyj** [comment]
There you go! You should have this on that page.
