### ISSUE TITLE
The slider doesn't show in RTL mode

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1520]
I'm using an Owl-slider with a video slide and it's not showing in RTL mode. Please test and/or ask for more info. 

My first guess is that the slider itself may not be compatible.

**Comment by moldcraft** [comment]
Owl-slider is a third party plugin, also it is displayed in frontend, how can Unyson fix that?

**Comment by thednp** [comment]
I guess not, anyways, the script is used with the extension, I found the issue and reported it, my part is done, if I can find a fix I will let you know.
