### ISSUE TITLE
Is it any way to call existing shortcode inside options of another shortcode?

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#1522]
Is it possible to add some button(with 'type' => 'popup' for example) to options.php which will call another shortcode?
For example: in section shortcode options add functionality existing button shortcode by reference it without copying and repeat it.

**Comment by danyj** [comment]
table shortcode has it , https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/table/includes/fw-option-type-table/class-fw-option-type-table.php#L258-L267

but  think @moldcraft  can explain it bbetter

**Comment by moldcraft** [comment]
[`fw_ext('shortcodes')->get_shortcode('button')`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.12/class-fw-extension-shortcodes.php#L21) will return a [`FW_Shortcode`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.12/includes/class-fw-shortcode.php) instance

**Comment by onebelarusianguy** [comment]
@danyj @moldcraft thanks! It is what I'm looking for

**Comment by onebelarusianguy** [comment]
@moldcraft One more little question.

Let's get example above. I have button shortcode. It's options array looks like
`array
        (
            [label] => 'Get It now!'
            [link] => '#'
            [bold] => 'false'
...)
`
I want to render it in section shortcode, so I  include it in section view.php:
`<?php require dirname(__FILE__) . '/../../button/views/view.php'; ?>`
But section options array now will be somehtning like this:
`array
    (
        [button] => array
        (
            [label] => 'Get It now!'
            [link] => '#'
            [bold] => 'false' ...))`
i.e. plus 'button' parent, cause section options.php looksl ike:
`	'button' => array(
		'type'          => 'popup',
		'popup-title'   => __( 'Button', 'nowadays' ),
		'button'        => __( 'Edit', 'nowadays' ),
		'popup-options' => fw_ext('shortcodes')->get_shortcode('button')->get_options()
	)`

So I have various `$atts` for button view.php: `$atts['key']` for simple button shortcode and `$atts['button']['key']` for button shortcode inside section view.
How can I do it right way?
The only idea I have is rewrite $atts variable before including button view in section view, but It's poor idea.

**Comment by moldcraft** [comment]
Inside section view you can `do_shortcode()` button. [Like this](https://github.com/ThemeFuse/Unyson/issues/1071#issuecomment-161586475)

**Comment by onebelarusianguy** [comment]
@moldcraft thanks!
