### ISSUE TITLE
Access Popup Modal Elements 

### ISSUE THREAD

**Issue by NwpDeveloper** [ThemeFuse/Unyson#1524]
I prefer the UI of the popup modals. However, it's a pain having to save and close each modal. 
So I'm trying to create a 'SAVE ALL' button. Is there an event I can use to bubble the changes from grand child popups to the main popup? Or do I need to trigger a click on save for the other modals?

Can the modalsStack be used to get previous popup modals or what is the best way to access previous popup modals? 

utils.modal.frame.closest('.media-modal') doesn't seem to work.

**Comment by moldcraft** [comment]
Hi,

At the moment I don't know a quick solution.

Try to inspect [the code](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/static/js/fw.js#L581). There seems to be a stack of `$modal` so you'll need to access it somehow and trigger Submit click (Note that you must wait for each modal ajax to finish to retrieve the values from sever, then close next modal, not all at once).

> utils.modal.frame.closest('.media-modal') doesn't seem to work.

Open Inspect Element and see that modals are not nested, all are children of `<body>`.
