### ISSUE TITLE
Strange things with background_image type.

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#1526]
Hi, I think it's a bug or maybe I missed something, But I spent the whole day on it. What I'm doing:
I have two custom shortcodes: parallax and slider. Parallax shortcode itself works well.
But when i'm trying to include parallax options in slider shortcode options and do_shortcode with this array I have problem with option type background_image - it's NULL.
Step by step:

1. create slider shortcode with [options](http://pastebin.com/WFCb9GiM)
2. create parallax shortcode with [options](http://pastebin.com/cx6LC2ju)
3. go to admin->add new slider shortcode->it's options->Slides(Add)->Image(Edit)->Choose Background Image->Save
4. Check in slider shortcode view.php `fw_print($atts);`: [screen](http://s32.postimg.org/oh4bjpjkl/image.jpg)
5. In view.php of slider shortcode do: 

	```php
	function nowadays_do_shortcode( $options_array, $shortcode_name ) {
		$shortcodes_extension = fw_ext( 'shortcodes' );
		$coder = $shortcodes_extension->get_attr_coder( 'json' );
		$encoded_atts = $coder->encode( $options_array, '', 0 );
		$shortcode = '[' . $shortcode_name . ' ' . implode(' ', array_map(create_function('$k,$v', 'return $k .\'="\'. $v .\'"\';'), array_keys($encoded_atts), $encoded_atts)) .' ][/' . $shortcode_name . ']';
		echo do_shortcode( $shortcode );
	}

	nowadays_do_shortcode( $atts['slides']['0']['image'], 'parallax' );
	```

6. Check in parallax shortcode view.php `fw_print($atts);`: [null](http://s32.postimg.org/94cuve9g5/image.jpg)
Other options works okay, except background_image. Whrere is my image?

**Comment by moldcraft** [comment]
I added `fw_print($shortcode);` in

```php
function nowadays_do_shortcode( $options_array, $shortcode_name ) {
	$shortcodes_extension = fw_ext( 'shortcodes' );
	$coder = $shortcodes_extension->get_attr_coder( 'json' );
	$encoded_atts = $coder->encode( $options_array, '', 0 );
	$shortcode = '[' . $shortcode_name . ' ' . implode(' ', array_map(create_function('$k,$v', 'return $k .\'="\'. $v .\'"\';'), array_keys($encoded_atts), $encoded_atts)) .' ][/' . $shortcode_name . ']';
fw_print($shortcode);
	echo do_shortcode( $shortcode );
}
```

and it shows

![](https://static.md/6eb39496914aab3890ecf3c155ef71e1.png)

I added [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.12/includes/coder/class-fw-ext-shortcodes-attr-coder-json.php#L83)

```php
fw_print($shortcode_tag, $attributes, $decoded);
```

![](https://static.md/1b9bf5c3c7c7edff9d9de7487bba58a0.png)

The fix is to replace `\` with `&#92;` on [encode](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.12/includes/coder/class-fw-ext-shortcodes-attr-coder-json.php#L52-L53).

**Comment by moldcraft** [comment]
Please test: [Download latest dev version](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension) and extract in `unyson/framework/extensions/shortcodes`.

The fix will be included in the next [extension release](https://github.com/ThemeFuse/Unyson-Extensions-Approval).

**Comment by onebelarusianguy** [comment]
@moldcraft now it's okay, thanks for fix
