### ISSUE TITLE
Which multi language plugin good fit with unyson ?

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1527]
I am really confused with unyson and multi language.

Today i have tried Unyson with WPML. 
i have created 2 lang.  english and Japanese. But i cant copy content from english. http://prntscr.com/az0nf8
When i click `copy content from english`  i got only shortcode broken text. and when click page builder only `text block` showing with broken shortcode text. and when enable page builder after click `copy content from english` nothing work.

And with unyson translation extensions also not cover all the thing for multi language site. like string translation.

Can you please provide us details which multi language plugin good fit with unyson ? so we can recommend buyers to use this.

**Comment by xperter** [comment]
Look like Unyson page builder not work properly with Multi language plugin. Before we tried qTranslate and Polylang as well.
They should care this issue as all buyers are not from USA.

**Comment by pear1** [comment]
+1
We too have less than 10% USA clients and this is a real issue.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1603
