### ISSUE TITLE
Getting `Undefined option type` flash message even if I check option type presence

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1529]
I have some extensions that are activated [automatically](https://github.com/ThemeFuse/Unyson/issues/127). The idea is that I'm having some option types inside all of them and this extensions depend on other ones, which may not be installed.

I'm also forced to use this option types from `framework-customizations/theme/options/*.php`. The problem is that I'm getting [**Undefined option type**](https://github.com/ThemeFuse/Unyson/blob/6575407875fd8648c676ea9547c0126937f2e18d/framework/core/components/backend.php#L1844) error. I want to avoid this.

Most obvious thing to do was to check option type presence: 
```php
if (fw()->backend->option_type('ct-header-picker')) {
	$options = array(
		'id' => array(
			'type' => 'my-option-type',
		),
	);
} else {
	$options = array();
}
```

This one didn't helped, of course -- `fw()->backend->option_type` method is the one that adds flash messages.

I see 4 possible ways of solving this problem:

1. Add a silent flag to `option_type` method, or another way of checking if the option type was registered
2. Add a config flag to `theme/config.php` that will remove this flash message everytime. Check for this flag [here].(https://github.com/ThemeFuse/Unyson/blob/6575407875fd8648c676ea9547c0126937f2e18d/framework/core/components/backend.php#L1841).
3. Add `$options` array to the desired location in a dynamic manner, using some [filters](http://manual.unyson.io/en/latest/hooks/index.html#options).
4. Leave it as it is and do nothing about it. Just let flash message to be around. Force the user to install required extensions this way.

Any opinion is welcome. Thank you.

**Comment by moldcraft** [comment]
Maybe to check if the extension which holds that option-type is active?

```php
if (fw_ext('extension-name')) {
    $options = array(
        'id' => array(
            'type' => 'my-option-type',
        ),
    );
} else {
    $options = array();
}
```

**Comment by andreiglingeanu** [comment]
Huh, haven't considered this option. Definitely should work fine. Thank you.
