### ISSUE TITLE
Can I customize this framework and release it as a new item for free?

### ISSUE THREAD

**Issue by themevan** [ThemeFuse/Unyson#1531]
Hi

Unyson is a so amazing free framework I've ever seen. I want to customize it, change the UI style and so on, so just confirm that whether I can release the changed version as a new item for free and under GNU?

Thanks

**Comment by moldcraft** [comment]
Hello,

Thank you for your interest in our framework.

You can't customize the UI, but you can fork it, change it and release as your own framework, under [GNU](https://github.com/ThemeFuse/Unyson/blob/master/framework/LICENSE).

**Comment by moldcraft** [comment]
P.S. Make sure to keep track of updates/fixes that we release to not encounter with problems like [this user](https://wordpress.org/support/topic/display-error-in-page-editor?replies=7#post-8365916)

**Comment by themevan** [comment]
Thanks I got it!

On Thu, May 5, 2016 at 3:49 PM, moldcraft <notifications@github.com> wrote:

> P.S. Make sure to keep track of updates/fixes that we release to not
> encounter with problems like this user
> <https://wordpress.org/support/topic/display-error-in-page-editor?replies=7#post-8365916>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1531#issuecomment-217095666>
>



-- 

Cheers!
-- 
John Wu
--

“The support service is not include customization or third-party plugin
problem, it's only include trouble using and bug fixing. Thanks!.”

--
ThemeVan- Premium WordPress Themes
Website: http://www.themevan.com
Support Forum: http://www.themevan.com/support
Google+ Group: https://plus.google.com/communities/114840886520756430726
Facebook Page: http://facebook.com/ThemeVan
Twitter: http://twitter.com/ThemeVan
