### ISSUE TITLE
Any way to use Icon with popup instead Whole icon list within shortcode

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1532]
I Saw Megamenu have option  icon with popup. http://puu.sh/oGUHU/15c582f9cb.png
http://puu.sh/oGUMt/6529f3aa79.png
But Normally a shrotcode icon option comes with Icon list http://puu.sh/oGUJk/bc344a96df.png

Is there any way i can use mega menu icon option style with popup ? It will saved lots of space within shortcode. also we can include within multi inline  option type easily.

Thanks

**Comment by moldcraft** [comment]
Hi,

Sorry but I don't see any difference in the above screenshots? Can you explain again in other words? Also add some annotations/arrows in screenshots to point the difference

**Comment by Ataurr** [comment]
I like to use icon option same like megamenu http://puu.sh/oGUHU/15c582f9cb.png

After click a popup will oen with icons

But now icon type comes with icons list http://puu.sh/oGUJk/bc344a96df.png

We are using  multi option type. But with current icon type break the design. and its look like this.
http://puu.sh/oRtki/0881fb77ab.png

I want something like that http://puu.sh/oRtEN/9007c59052.png

Also It will saved space to on shortcode if we select icon with popup in shortcodes.

Where we used icon type i prefer to use icon with popup list instead  icon list. like mega menu. http://puu.sh/oRtMT/926cde4645.png 

Hope  you clear now

**Comment by moldcraft** [comment]
> Is there any way i can use mega menu icon option style with popup ?

No, in MegaMenu is custom js + modal, it is not an option-type. You need to create your own option type.

Thank you for this idea, option type `icon-v2` will be inspired by this.

**Comment by Ataurr** [comment]
Yeah. its looks perfect for icon selection in shortcode.

Are you working icon-v2 near future ? or  any time frame ?

Thanks very much

**Comment by moldcraft** [comment]
No time frame. We just added it in TODO list but not sure when we'll start working on it.
