### ISSUE TITLE
Front End Page Builder solutions?

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1533]
Hello, 

Just wondering are there anyone managed to get Unyson page builder working at front end or something similar or the only way would be to use Visual Composer or similar type of page builders?

**Comment by thednp** [comment]
ATM the framework only works in the back-end as for editing, I believe the front-end editing must have been discussed before in the issues here as well as Unyson developers themselves. Perhaps more requests would swift the balance in favor of going forward with this feature.... I would say this feature isn't coming any time very soon. Perhaps later to the end of the year.

As far as I understand, we're working on improving the core stability and modularity,  as well as fixing small issues, but the most energy focus is the most popular extensions and documentation.

**Comment by moldcraft** [comment]
No new major features in the near future.

I only fix bugs in Unyson and work on other projects.

**Comment by pear1** [comment]
I see.
Front end page builder is manly needed for clients, because lot of new themes advertises themselves with just of theses features and looks like it is working.

Anyone has tested how good Visual Composer works with Unyson framework?

**Comment by duongancol** [comment]
@pear1 : VC don't have any problems with Unyson fW
