### ISSUE TITLE
Major database issue from old post meta data

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1536]
Hello,

After quite some time my database size was gone up to 40mb, what was quite a lot.
I figured out to delete half pages and all revisions, but database size was about size, maybe 39mb.

But then I deleted all orphan postmeta then database size reduced to 6mb.
I think that plugins which deletes revisions, drafts and so on does not see postmeta from page builder and therefore database size is just moving up.

Therefore if I am right, then there should be some kind of cleaner function.

**Comment by moldcraft** [comment]
Which plugin you use to delete post revisions?

**Comment by pear1** [comment]
WP-Optimize (https://lv.wordpress.org/plugins/wp-optimize/), one of the most popular cleanup tools (Active Installs: 500,000+).
