### ISSUE TITLE
Issue with Portfolio Grids not available in content elements.

### ISSUE THREAD

**Issue by dwatwell** [ThemeFuse/Unyson#1537]
I have downloaded and installed the scratch theme for the Unyson framework.  I have downloaded and installed the Portfolio extensions but when I use page builder, the option for the Portfolio Grid does not appear?

**Comment by duongancol** [comment]
It's not supported by default. You could download my custom portfolio shortcode [here](https://www.dropbox.com/s/82wly51g92x2kso/portfolio-shortcode.zip?dl=0) and move the folder to wp-themes/theme/framework-customization/extensions/shortcodes/
Hope it helps!

**Comment by dwatwell** [comment]
I am just curious why it is not supported by default when the them allows
you to download and activate the portfolio grid extension?

On Fri, May 6, 2016 at 11:39 PM, Duong <notifications@github.com> wrote:

> It's not supported by default. You could download my custom portfolio
> shortcode here
> <https://www.dropbox.com/s/82wly51g92x2kso/portfolio-shortcode.zip?dl=0>
> and move the folder to
> wp-themes/theme/framework-customization/extensions/shortcodes/
> Hope it helps!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1537#issuecomment-217606390>
>



-- 
David Atwell
Administrative Pastor/Worship Leader
Waldo Baptist Church
618-564-2180

**Comment by moldcraft** [comment]
@dwatwell We forgot about that. Now we can't add the `portfolio` shortcode by default because it will conflict with the one created by theme developers. Sorry
