### ISSUE TITLE
Using fw_get_db_post_option outputs nothing

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1538]
Hello,

I've made a function in a separate php file and included that in my functions.php. What the script does: retrieve some DB values after saving a post (I used the 'save_post' hook) and check for something. Retrieving terms is no problem. But when trying to retrieve some custom field values from fw-options, it comes up empty.

The function I'm using: 
`$address = fw_get_db_post_option($post->ID, 'address');`

Is there some global variable I should call before retrieving this value? Or is there some other problem/thing that's interfering with the retrieval?

**Comment by moldcraft** [comment]
Which priority you use in your `save_post` hook? It must be `8+` because fw-options are saved on [same hook with priority 7](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/core/components/backend.php#L184)

**Comment by noesteijver** [comment]
I started out with the default, 10. After your comment, I tried 20. But that doesn't work either..

**Comment by moldcraft** [comment]
So in any other case it works, it doesn't work only in `save_post` hook?

**Comment by noesteijver** [comment]
Yes, that's correct.
