### ISSUE TITLE
Page builder duplicate issue. 

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1539]
I am Facing a issue after duplicate content. 
Example 
I have used two 1/2 column http://puu.sh/oJiTU/d354af36d6.png
And just duplicate same section. Tried to move left to right media image.

Media image column hide from duplicate section. http://puu.sh/oJj1O/3285b3c979.png

when i check console a error displaying: 
```
TypeError: Cannot read property 'remove' of undefined
 /ThemeName/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/builder.js?ver=1.2.1:642
```

**Comment by moldcraft** [comment]
Please download the latest dev version of [Builder extension](https://github.com/ThemeFuse/Unyson-Builder-Extension), extract in `unyson/framework/extensions/builder` and test if this problem is fixed.
