### ISSUE TITLE
Extend options admin

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#154]
Is there a way to extend the options admin without messing with the plugin itself?
Trough framework-customizations somehow ?
I would like to add my own style to the options admin area and have the tabs on the side rather than on top plus add some additional styling.

**Comment by moldcraft** [comment]
Options can't be extended or removed. You can only [create new option types](http://unyson-docs.themefuse.com/en/latest/options/create-option-type.html#content).
The only way to customize admin styles is just to include your css from the theme (from anywhere you want, unyson doesn't have a special place for theme css) and overwrite the existing styles.

We tried to make everything look like the default wordpress style (in the past ThemFuse themes also had their own admin style, but with wordpress 3.9 we removed it and just use the default), why do you want to move tabs on the side and change options styles?

**Comment by danyj** [comment]
Im trying to match the look to  our joomla framework and this way make it closer to our members since they already got used to it
http://yjsimplegrid.com/documentation/basics/yjsg-template-manager.html
