### ISSUE TITLE
When using in theme the style and script isn't adding 

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1540]
Hi 

I have using plugin as theme base. I have created a sub folder "framework-customizations"  But the shortcodes styles are taken from plugin not from framework customizations. 

Though there is this code but it does not work for me. I have added this in functions.php

```
if (defined('FW')):
    // the framework was already included in another place, so this version will be inactive/ignored
else:
    /** @internal */
    function _filter_fw_framework_plugin_directory_uri() {
        return 'https://.../uri/to/this/directory' . '/framework';
    }
    add_filter('fw_framework_directory_uri', '_filter_fw_framework_plugin_directory_uri');

    require dirname(__FILE__) .'/framework/bootstrap.php';
endif;
```

**Comment by moldcraft** [comment]
The above code is exactly the code that is now in your plugin?

**Comment by ashraf92** [comment]
No I have pasted in my theme functions.php

**Comment by moldcraft** [comment]
Please give the exact steps to reproduce the problem _(I am not a clairvoyant)_

**Comment by ashraf92** [comment]
Okay . I have unyson installed . Then I created framework-customizations in my theme folder. And put all shortcodes and extension inside it .Now as for shortcode the styles are taken from plugin. Is there any way so that shortcode take styles and script from theme's framework-customizations folder.

**Comment by ashraf92** [comment]
Fixed it by placing this code in static.php
```
define( 'THEME_URI', get_template_directory_uri().'/framework-customizations/extensions/shortcodes/shortcodes/' );
wp_enqueue_style(
	'fw-shortcode-',
	THEME_URI . '/special-heading/static/css/styles.css');
```

**Comment by moldcraft** [comment]
> I created framework-customizations in my theme folder. And put all shortcodes and extension inside it

You should not do that. In `framework-customizations` overwrite only specific/needed files, in your case it's [`framework-customizations/extensions/shortcodes/shortcodes/{shortcode}/static.php`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/button/static.php). Leave the `static.php` file empty to disable all assets for that shortcode, or enqueue any other assets.
