### ISSUE TITLE
[Bug][Urgent] All shortcodes disappear in Page Builder

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1542]
Hi @moldcraft !
My client get the problem today again with page-builder. 
All the shortcode is disappeared and only showed the Text Blog shortcode. 
That is inside this shortcode:
<!-- {"length":38025,"hash":"de449e41e99242ccca688649
I'll send you the site account to check it and please help me urgently, they will launch the site today.
![image](https://cloud.githubusercontent.com/assets/1773011/15110023/b39f282e-1608-11e6-8755-05769eb93f79.png)

**Comment by duongancol** [comment]
I've sent, please take a look and give me your idea! Thanks!

**Comment by duongancol** [comment]
Unyson, extensions & WP are all the latest version.

**Comment by duongancol** [comment]
I'm sorry to bother you again, Could you take a look?

**Comment by duongancol** [comment]
this issue is is closed because my client can't wait and they buy another theme.

**Comment by moldcraft** [comment]
Sorry, I was on holiday.

That problem can happen if you click multiple times on post Update while the page is not loaded https://github.com/ThemeFuse/Unyson/issues/647#issuecomment-215964026

Or maybe from other plugins, or there was a fatal error and the post was not saved (check apache error.log)

**Comment by duongancol** [comment]
Can we have the solution that prevents 'Update' button work when page builder doesn't load fully? 
Because this problem can happen again in the future.
