### ISSUE TITLE
Override child framework view

### ISSUE THREAD

**Issue by saeedsqr** [ThemeFuse/Unyson#1543]
I'm working with child Framework in unyson.
I want to override parent "backend-option-design-default.php" file in "views" folder
but i'm not able to override parent framework view.
My parent framework directory structure is: "framework\views\backend-option-design-default.php"
and my child framework directory structure is: "webalizer-framework\views\backend-option-design-default.php"

please help me to override parent view

**Comment by Ataurr** [comment]
Your child theme folder structure should be same like Parent theme 
Use "framework" Instead "webalizer-framework"

**Comment by saeedsqr** [comment]
if i change it to "framework" Duplicate Error
![2016-05-09_1922](https://cloud.githubusercontent.com/assets/18280988/15116158/9e49a73e-161b-11e6-9d8b-5dcdf07b4b42.png)

**Comment by saeedsqr** [comment]
Thankx Ataurr !!!
guide me for directory structure!

**Comment by moldcraft** [comment]
> child Framework

There is no such thing in Unyson.

You can't overwrite the `backend-option-design-default.php` view. Doing this will break some scripts/styles.

**Comment by dinhtungdu** [comment]
> You can't overwrite the backend-option-design-default.php view. Doing this will break some scripts/styles.

How can I change the grid of Theme setting page? `sm-3` and `lg-2` are too small for me.

**Comment by moldcraft** [comment]
@dinhtungdu Give a screenshot please

**Comment by dinhtungdu** [comment]
@moldcraft Here is the [screenshot](http://prntscr.com/bdcu5h).

**Comment by moldcraft** [comment]
@dinhtungdu I added [this filter](https://github.com/ThemeFuse/Unyson/commit/02b23bb846ab983c7faad4438e0e443c4f747e41#diff-d2e367f4cfc2a8cb1c5d5c8676283fc3R54)

**Comment by dinhtungdu** [comment]
Super cool! Waiting for release! 👍
