### ISSUE TITLE
Huge data size issue with render_options via ajax 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1545]
@moldcraft  I made an template option type that saves set of theme options and renders it back to  form on click. Everything works fine on local server but on live server I just hit a limit. Seems like the ajax response has a data size limit or `post_max_size`  is reached and I get no html back. No errors nothing. 

On local server the returned size of data is 2.7MB ,  reason being is the special chars returned by 

    fw()->backend->render_options( $options, $values, $data );

I know we need it and why we need it but I just hit a wall that I have no idea how to go over. 

Here is the issue on stack http://stackoverflow.com/questions/37125119/jquery-ajax-trouble-receiving-huge-amount-of-data

on php side I am using   this  https://github.com/ThemeFuse/Unyson/blob/65efe568d85a8e1b237d8bd6cc4df04557dca912/framework/core/components/backend.php#L850-L877

to return the html  and send it  back to js . 

This option works perfect for smaller data size , but I am also using it to create theme templates wich save all theme options and need to render them back. 

At this point I have no idea how to go further and this option is meat and bone of the theme. 

So please try to point me in the right direction.

**Comment by danyj** [comment]
@moldcraft   is there a way  I could process the render via JS instead of php and do same type of render on client side. just send the data json to client via php and process it in browser instead of php

**Comment by moldcraft** [comment]
> Seems like the ajax response has a data size limit or `post_max_size`

No sense, `post_max_size` is for data sent by user to server. Maybe you reach max vars http://stackoverflow.com/questions/9505192/php-post-limited-to-1000-variables

**Comment by danyj** [comment]
Not sure , I just set it to max_input_vars to 500  on my local server and still cant replicate the issue. 
The ajax response returns null so I am not sure if it is encoding. Could you try to help me live?

**Comment by moldcraft** [comment]
It's a server limit (but I don't know which one)

This works `1830000`

```php
wp_send_json_success(array(
	'html' => substr($html, 0, 1830000),
	'firstload' => $firstload,
));
```

this not `1840000`

```php
substr($html, 0, 1840000)
```

**Comment by moldcraft** [comment]
![](https://static.md/aac3d3146976965ce1ce33dc516e516c.png)

**Comment by danyj** [comment]
Could you try to accommodate this than , all our options have fw_option name prefix which is great , is there any way that you could add a option type in data to be like 

    <select name="fw_option[option_name]"  data-fw-type="multi-picker"...
    <input name="fw_option[option_name2]"  data-fw-type="textarea"...

with this I might get a faster way to repopulate data via JSON by just checking the type , adding value and reintialize all when done instead of puling 2++MB data from ajax and replacing the DOM.

**Comment by danyj** [comment]
right now some inputs have class name  like 

    fw-option-type-short-text

but multi-picker , image picker and many other have this class set at the parent level or higher so I still dont know what option type I am dealing with

**Comment by moldcraft** [comment]
All options have class `.fw-option-type-*` 

I think you can first select the elements with [this selector](http://stackoverflow.com/a/8588532/1794248) 

```
[class^="fw-option-type-"], [class*=" fw-option-type-"]
```

then extract the type in js via regex

```js
var className = 'hello fw-option-type-test world'; // or 'fw-option-type-test hello world'
var matches = className.match(/(?:^|\s)fw-option-type-([^\s]+)/);
var type = matches[1];

console.log(type);
```
