### ISSUE TITLE
Builder support for custom post type

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1546]
I have a custom post type named ```project``` . But this does not add support for that cpt
```
add_post_type_support('project', 'fw-layout-builder');
```

Is there any other way?

**Comment by moldcraft** [comment]
Use [this filter](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.3/settings-options.php#L15). Also go to menu *Unyson > Page Builder > Settings*

**Comment by danyj** [comment]
@moldcraft , @andreiglingeanu   can you please provide a snippet how to get our own post type listed in builder settings page , 

for example I have custom post types Thz Section 

than in hooks.php I have


```
/**
 *	Builder auto activate for certain post types
 *  @internal
 */
function _thz_filter_auto_activate_builder() {
	
	$auto = array(
		'post' => true,
		'page' => true,
		'thzsection' => true,
		'fw-portfolio' => true,
	);
	
	return  $auto;
}
add_filter( 'fw_ext_page_builder_settings_options_post_types_default_value', '_thz_filter_auto_activate_builder' );
```

but my post type is not being listed 

I create my cpt on init 

        add_action('init', 'thz_custom_post_type');

**Comment by moldcraft** [comment]
@danyj 

1. https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/99bb4122ec829516702abe6588d42cd31cfa1a49/helpers.php#L28
2. https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/99bb4122ec829516702abe6588d42cd31cfa1a49/settings-options.php#L15

**Comment by danyj** [comment]
thank you!

for anyone who needs it , here is the actual snippet



	function _thz_filter_auto_activate_builder() {
		
		$auto = array(
			'post' => true,
			'page' => true,
			'thzsection' => true,
			'fw-portfolio' => true,
		);
		
		return  $auto;
	}
	add_filter( 'fw_ext_page_builder_settings_options_post_types_default_value', '_thz_filter_auto_activate_builder' );
	
	
	
	
	function _thz_filter_page_builder_support($result){
		
		$result['thzsection'] = esc_html__('Thz Section','fw');
		return $result;
		
	}
	add_filter( 'fw_ext_page_builder_supported_post_types', '_thz_filter_page_builder_support' );
