### ISSUE TITLE
Page Builder content not showing on template

### ISSUE THREAD

**Issue by alfgago** [ThemeFuse/Unyson#1549]
Hi, first time theme maker here. 
I have this one-page template that was working before, but on the recent update now the pages only show the code like if the page builder didn't load. 
It only prints things like this: 

It seems like the_content(); is printing that code, ignoring the page builder

This is what I have:

I have this one-page template that loads the content of all of its childs. 

```php
<?php
/**
 * Template Name: One Page
 *
 * This is the template used for the parent of the one page
 *
 * @package WordPress
 * @subpackage Elias 5
 * @since Elias 5 1.0
 */

get_header(); ?>
<div id="elias-fullpage" class="elias-fullpage">
	<?php
	global $wp_query;
	// is Page a parent page
	if ( $post->post_parent == 0 ) {

		// on a parent page, get child pages
		$pages = get_pages( 
		'hierarchical=0&parent=' . $post->ID . '&sort_column=menu_order' 
		);

		// loop through child pages
		foreach ( $pages as $post ){
			setup_postdata( $post );
			// load the content template for the child page
			get_template_part( 'template-parts/content', 'full-page-child' );
		}
	}
	?>
	
	
	<footer id="colophon" class="site-footer elias-fp-section fp-section fp-auto-height" role="contentinfo" data-anchor="footer">
		<?php get_template_part( 'template-parts/footer', 'content' ); ?>
	</footer><!-- .site-footer -->
</div><!-- .content-area -->

```

And then I have this in the child page template:

```php
<?php
/**
 *
 * This is the template used to display the content of the children of the full page
 *
 * @package WordPress
 * @subpackage Elias 5
 * @since Elias 5 1.0
 */

?>
<div id="fp-<?php the_ID();?>" class="<?php echo 'fp-'.$post->post_name; ?> elias-fp-section" data-name="<?php echo the_title(); ?>" data-anchor="<?php echo $post->post_name; ?>">
	<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
		<div class="entry-content">
			<div class="elias-fp-slide ee2">
			<?php
				the_content();

				wp_link_pages( array(
					'before'      => '<div class="page-links"><span class="page-links-title">' . __( 'Pages:', 'fivee' ) . '</span>',
					'after'       => '</div>',
					'link_before' => '<span>',
					'link_after'  => '</span>',
					'pagelink'    => '<span class="screen-reader-text">' . __( 'Page', 'fivee' ) . ' </span>%',
					'separator'   => '<span class="screen-reader-text">, </span>',
				) );
				?>
			</div>
		</div><!-- .entry-content -->

		<?php
			edit_post_link(
				sprintf(
					/* translators: %s: Name of current post */
					__( 'Edit<span class="screen-reader-text"> "%s"</span>', 'fivee' ),
					get_the_title()
				),
				'<footer class="entry-footer"><span class="edit-link">',
				'</span></footer><!-- .entry-footer -->'
			);
		?>

	</article><!-- #post-## -->
</div>
```

Thank you, hope you can help

**Comment by moldcraft** [comment]
Hello,

Use [this function](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.3/helpers.php#L41) to retrieve page builder content.

Page Builder uses [this filter](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.3/class-fw-extension-page-builder.php#L56) to change post content before display, and in your case it is not executed.

**Comment by alfgago** [comment]
Hi, thank you for your help, but I still can't make it work. I changed the child template, changed the "the_content()" for  "fw_ext_page_builder_get_post_content(get_post())" and it looks like this:

```php
<div id="fp-<?php the_ID();?>" class="<?php echo 'fp-'.$post->post_name; ?> elias-fp-section" data-name="<?php echo the_title(); ?>" data-anchor="<?php echo $post->post_name; ?>">
	<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
		<div class="entry-content">
			<?php
				fw_ext_page_builder_get_post_content(get_post());

				wp_link_pages( array(
					'before'      => '<div class="page-links"><span class="page-links-title">' . __( 'Pages:', 'fivee' ) . '</span>',
					'after'       => '</div>',
					'link_before' => '<span>',
					'link_after'  => '</span>',
					'pagelink'    => '<span class="screen-reader-text">' . __( 'Page', 'fivee' ) . ' </span>%',
					'separator'   => '<span class="screen-reader-text">, </span>',
				) );
				?>
		</div><!-- .entry-content -->

		<?php
			edit_post_link(
				sprintf(
					/* translators: %s: Name of current post */
					__( 'Edit<span class="screen-reader-text"> "%s"</span>', 'fivee' ),
					get_the_title()
				),
				'<footer class="entry-footer"><span class="edit-link">',
				'</span></footer><!-- .entry-footer -->'
			);
		?>

	</article><!-- #post-## -->
</div>
```

Is there anything else I'm missing? I don't get it, because the normal content-page.php that works when opened in single page still has "the_content();" only and not that function you say.

**Comment by alfgago** [comment]
Ok, I just changed that line to `echo do_shortcode(fw_ext_page_builder_get_post_content($post));`

Now it works, is this the best way to do it?

Thank you for your help! Great support

**Comment by TrangDinhVan** [comment]
Please help, I get this
Call to undefined function fw_ext_page_builder_get_post_content()
Unyson 2.5.3 and "You have the latest version of Unyson Extensions." in Update Panel

**Comment by moldcraft** [comment]
@TrangDinhVan Open `unyson/framework/extensions/shortcodes/extensions/page-builder/manifest.php` and see the version, you must have this version https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/releases/latest

**Comment by moldcraft** [comment]
> is this the best way to do it?

No, it should work without any unyson functions.

----

Please try this:

1. Add back `the_content()` (remove `fw_ext_page_builder_get_post_content()`)
2. Add in `{theme}/functions.php`

    ```php
    add_action('fw_init', function(){
        add_filter('get_pages', array(fw_ext('page-builder'), '_filter_the_posts'), 2, 2);
    });
    ```

If it will work, I will add this fix [here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.3/class-fw-extension-page-builder.php#L56-L57) and it will be included in the next version of PageBuilder extension.

**Comment by seahunter** [comment]
Hello @moldcraft , i have the same problem, i tried to add current code to funtrion.php but without effect. 
Thank's

**Comment by seahunter** [comment]
Hello, @moldcraft , in older version of unyson this method it worked fine, but now is empy filed instead content.
`<?php
           $company_id = 24;
           $page_data_company = get_post($company_id);
           print apply_filters('the_content', get_the_content($page_data_company->post_content));
        ?>`
Thank's.

**Comment by moldcraft** [comment]
We replace post content via filter, and unfortunately `get_post()` doesn't not offer any filter. Try `get_posts()`

```php
$posts = get_posts(array(
    'include' => 24,
    'post_type' => 'any',
    'numberposts' => 1,
    'suppress_filters' => false,
));

echo apply_filters('the_content', $posts[0]->post_content);
```

**Comment by huepfmonster** [comment]
Hey @moldcraft, thanks for the tip. Using
`fw_ext_page_builder_get_post_content()`
works, but unfortunately I can't hook into the plugin, so it would be best to use a function non-specific to unyson and send it to the plugin author as a patch.

But when i use get_posts (with supress_filters false of course) and then $page_data->post_content; it does not work. Any advice on that?

Best Regards
Jakob

**Comment by CoreyAR** [comment]
I am encountering a similar issue using an existing theme that uses Unyson. I need to add visual builder content for the posts page above the list of posts. 

`echo do_shortcode(fw_ext_page_builder_get_post_content($content));
` is working for me but it is missing dynamic styles added from the page builder.

**Comment by moldcraft** [comment]
Hello @CoreyAR

You need to do the enqueue manually, Unyson doesn't know that you do `echo ...` in your template.

```php
add_action('wp_enqueue_scripts', '_theme_enqueue_custom_content');
function _theme_enqueue_custom_content() {
    if (...) { // detect if you are on the page with `echo do_shortcode()`
        fw_ext_shortcodes_enqueue_shortcodes_static(
            fw_ext_page_builder_get_post_content($content)
        );
    }
}
```
