### ISSUE TITLE
Mega menu not working properly

### ISSUE THREAD

**Issue by tomik3690** [ThemeFuse/Unyson#155]
I was using older Unyson version which was included in my theme via bootstrap.php and mega menu worked fine. I decided to use plugin version ( 2.1.14 ) and mega menu is not working properly. I should get

```
<li class="... menu-item-has-mega-menu">
  <div class="mega-menu">
    <ul class="sub-menu mega-menu-row">
      ...
    </ul>
  </div>
</li>
``` 
but I get 
```
<li class="... menu-item-has-mega-menu">
  <ul class="sub-menu">
    ...
  </ul>
</li>
``` 
instead. I tried to edit <code>display_element()</code> method in <code>class-fw-theme-menu-walker.php</code>, add some string to see if it works and it doesn't :( Nothing changes. Could you help me?

**Comment by 2Fwebd** [comment]
I already has this problem because I was using a menu location different than "primary" one set in the theme.

**Comment by tomik3690** [comment]
Oh, thank you. My primary menu location was called 'header_menu' and that was the problem. I changed it to 'primary' and it works now.
