### ISSUE TITLE
Text block excerpt [feature request]

### ISSUE THREAD

**Issue by nervousdandy** [ThemeFuse/Unyson#1550]
Would it be possible to have excerpt text within a text block show up as the name of the block, rather than just "text block"? On a page with lots of different blocks, it becomes difficult and time consuming to find the correct one to edit. The Special Heading uses the actual heading as its title in the Page Builder, so something like that for Text Blocks would be extremely helpful. Thank you!

Running ver. 2.5.3 on WP 4.5.2

**Comment by moldcraft** [comment]
Have you tried to overwrite the text block shortcode config file in theme and add the [`$cfg['page_builder']['title_template']` parameter](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file) ?
