### ISSUE TITLE
fw-storage in taxonomy and extension settings options

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1551]
I came across fw-storage a while ago. And I've used it for post-meta, that works great. But I can't find much info about it. Only thread I've seen is: https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/includes/option-storage/type/class-fw-option-storage-type-post-meta.php#L6

My question is: is it possible to put term meta in a separate value, like so?

```php
'landcode'  => array(
	    'type'  => 'text',
	    'label' => __('Landcode', 'fw'),
	    'description' => __('WPML landcode', 'fw'),
	    'fw-storage' => array(
	        'type' => 'key',
	        'key' => 'landcode',
	    ),
	),
```

I've used 'post-meta' before. And I've tried 'term-meta', but that doesn't work..

**Comment by noesteijver** [comment]
I see now that there are two option storage types:
- post meta
- wp option

https://github.com/ThemeFuse/Unyson/tree/v2.5.3/framework/includes/option-storage/type

Can I make my own storage type?
And: can I place it in my framework customizations folder?

**Comment by moldcraft** [comment]
The `fw-storage` parameter is not processed (has no effect) in term options. I will fix that later.

**Comment by moldcraft** [comment]
There is no info in docs about `fw-storage` because this feature was recently added and I was not sure if it will work well to promote it in docs. But I will add an explanation in docs soon.

Use [this action](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/helpers/database.php#L869) to register your own `fw-storage` (Please prefix its name).

```php
class FW_Option_Storage_Type_YOUR_TYPE extends FW_Option_Storage_Type { ... }

$register->register(new FW_Option_Storage_Type_YOUR_TYPE());
```

**Comment by moldcraft** [comment]
So at the moment it is not possible to store fw term option in a separate place in db.

**Comment by noesteijver** [comment]
Aha. I have a workaround for now.

But I guess it would be quite nice to be able to save term data as a separate value. I'll keep track of this, thanks!

Topic can be closed.

**Comment by moldcraft** [comment]
Now all `fw_set|get_db_..._option()` functions are processing the `fw-storage` parameter

https://github.com/ThemeFuse/Unyson/blob/bcf4b774ae6293da05b46b5f1ca213a5cc39127e/framework/helpers/database.php
