### ISSUE TITLE
Background video not working in Safari

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#1552]
Hi there,

I'm working on a new theme and I tried out Unyson's background-video option for sections. 
Basically it works pretty good, but I noticed that the video won't play in Safari. I do hear sound, but only see the placeholder image instead of the video. I do get a lot of error messages:
"Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com."

First I thought I'd maybe had to change from a https-connection to http, but this was no solution.

Then I stumbled across a topic about the error, there people said to add a script for the YouTube API and when I do this via functions.php the video does indeed play. This is the link to the script: https://www.youtube.com/iframe_api

Is there something Unyson can do about this problem?

**Comment by moldcraft** [comment]
I tested Scratch Theme and this script enqueued https://www.youtube.com/iframe_api in Safari for Windows and it doesn't work at all, no errors in Firebug console.

Which OS and browser version do you have?

**Comment by moldcraft** [comment]
No video is playing in Safari for Windows https://formstone.it/components/background/demo/

**Comment by warudin** [comment]
Hi Moldcraft,

I am using Mac OS X and Safari 9.1.1.
Currently I'm working locally, maybe this is the problem?

The video's on your demo page work, although I do get this alert in the debug console:
> The page at https://formstone.it/components/background/demo/ was allowed to display insecure content from http://img.youtube.com/vi/LlQ8dhdSjWs/0.jpg.

**Comment by moldcraft** [comment]
> Currently I'm working locally, maybe this is the problem?

Install your theme on a live server and we will find out.

**Comment by warudin** [comment]
Sorry for keeping you waiting for so long.
In the mean time I've moved the website to an online server and I can say that the problem still exists.

The section background video works in Chrome, Firefox, Opera and Internet Explorer. Safari still serves up the same errors, although the sound of the video is being played. When serving up the extra script the video does work.

You can see it here (with the extra script disabled FTM): http://onepager.noesteprojecten.nl/qombine/

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/239c8dbd89614029d4c124d19fada608254f1b4f

Please test

**Comment by warudin** [comment]
Hi Moldcraft,

I've tried your addition locally, and fixes the problem, thanks!
I'm looking forward to the plugin update for Unyson. :)
