### ISSUE TITLE
No text color option in the WYSIWYG field type

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1553]
In the native Wordpress editor (Top) there is a text color option that is missing in Unyson (bottom). Is there a way that it can be brought up?

![image](https://cloud.githubusercontent.com/assets/1108563/15220832/a2d33088-1871-11e6-875f-db871d81101a.png)

**Comment by moldcraft** [comment]
```php
array(
    'type' => 'wp-editor',
    'dfw' => true,
)
```

**Comment by pe6o** [comment]
Ah, thanks!

It was even worse... I was using `'teeny'  => true` and I am seeing in just now.

**Comment by pe6o** [comment]
Is it possible for the Unyson shortcode button to be shown?

**Comment by moldcraft** [comment]
No, it works only in main post editor, because the value is saved in post meta, not in editor content.
