### ISSUE TITLE
Redirect and activate tab

### ISSUE THREAD

**Issue by drkrule** [ThemeFuse/Unyson#1554]
I have a page... since woocommerce can't change language using your unyson translation, and I want to create a link where a tab is active.

This is the page:
http://puertoricoprogress.com/fw_lang/es/donaciones/

This it what the link should be to activate (English):
http://puertoricoprogress.com/fw_lang/es/donaciones/#fw-tabs-5734f07535b8b-2
or
http://puertoricoprogress.com/fw_lang/es/donaciones/#ui-id-2

Please help me with this for a solution. Thank you for your time and plugin.

**Comment by moldcraft** [comment]
Hello,

Where that link will be placed? Please give a screenshot with arrows/annotations.

**Comment by drkrule** [comment]
In the menu as the donation or donaciones link

**Comment by moldcraft** [comment]
Sorry, I don't know how the Translation extension works

**Comment by drkrule** [comment]
This is not part of the translation. Is part of the page builder functions

**Comment by moldcraft** [comment]
Sorry, I still don't understand the problem, why you just can't put the link in menu?

**Comment by drkrule** [comment]
The link is in the first post... I did add it on the menu but the tab is not active when you click on it. 
If you browse http://puertoricoprogress.com/
and click donate now... should be the link withthe english tab active, it isn't. The spanish is active.

**Comment by moldcraft** [comment]
![](https://static.md/1bcf184a28c755cef47e9d9b55c9a03b.png)

It is generated [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.12/shortcodes/tabs/views/view.php#L2)

You need to [overwrite](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes) shortcode options and add a text option called Custom ID and overwrite the view to use that option if it is not empty.

**Comment by drkrule** [comment]
So i have to edit the code? Kind of complicated, but let's see if I come up with the solution.

**Comment by marcingoralczyk** [comment]
Hello, every tab has personal ID like -> fw-tabs-59ba69e78f41d-2 ... 
I have links that have to open specific tab (by id). I was tried add #fw-tabs-59ba69e78f41d-2 to link / url. Any suggestion what to do with code?
