### ISSUE TITLE
No "Edit" button for columns

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1557]
I see here ( http://docs.themefuse.com/exposure/your-theme/shortcodes/columns ) that columns should have an **Edit** button, but it is missing an there is **Save as Template** in its place. How can I enable the **Edit** button?

![image](https://cloud.githubusercontent.com/assets/1108563/15247859/885a1060-191f-11e6-9d08-debb1db300c8.png)

**Comment by moldcraft** [comment]
Create `{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/options.php`

**Comment by pe6o** [comment]
Ah, so they don't come with built in options anymore?

**Comment by moldcraft** [comment]
The `column` shortcode has [no built-in `options.php`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/v1.3.12/shortcodes/column)

**Comment by pe6o** [comment]
Alright. I was confused because the documentation says:

> Every column comes with a bunch of built in options.

**Comment by moldcraft** [comment]
http://docs.themefuse.com/exposure/your-theme/shortcodes/columns That is docs for the Exposure theme, not for built-in Unyson shortcodes. Theme contains lots of customization.

**Comment by pe6o** [comment]
Oh, I saw the URL just now...

What Unyson field is the **Additional Spacing** option, or is it a custom one for the theme?

**Comment by moldcraft** [comment]
> Additional Spacing option

Inspect Element it, it's just a group of 4 input options styled from css.
