### ISSUE TITLE
WordPress Importer creates Blank pages

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#1560]
I'm attempting to use the default WordPress importer to import some pages that where exported from another site, but all the pages are coming up blank after import. I'm using Unyson 2.5.3 and all latest available exensions.

I'm not sure if this has anything to do with special characters (quotes, ampersands, etc..) in the content, but I have a Post Duplicator plugin that I had to modify recently due to this. Normally my plugin pulled custom meta using get_post_custom from the original post and saving it to the duplicated post with add_post_meta. I ran into issue with this on pages that used inline styles or attributes within content of the shortcodes. The quotes weren't being escaped properly at times and the json string became malformed. I ended up modifying my plugin to pull meta directly from the database using $wpdb and inserting it the same way to get around this.

I am attaching a (zipped) export file that you can use to test with. Thanks!

[sample.wordpress.2016-05-13.xml.zip](https://github.com/ThemeFuse/Unyson/files/263822/sample.wordpress.2016-05-13.xml.zip)

**Comment by moldcraft** [comment]
Hello,

We don't support WordPress Importer, sorry. I think it is its problem that it breaks the quotes _(like post_content does, that's why we moved all shortcodes data to post meta and don't store anything in post content)_

**Comment by moldcraft** [comment]
We recommend you to use our Backup & Demo Content extension to migrate your site.

**Comment by meta4creations** [comment]
Ok, thanks for the info. I will attempt to figure out a way to export/import specific posts.
