### ISSUE TITLE
Unyson Framework Intermittent Errors - Any help?

### ISSUE THREAD

**Issue by daveparkhurst** [ThemeFuse/Unyson#1561]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem. I have the latest Wordpress and latest version of the plugin. Thanks for any help!

Warning: Class __PHP_Incomplete_Class has no unserializer in /home/content/p3pnexwpnas13_data03/11/3095811/html/wp-content/object-cache.php on line 520

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/content/p3pnexwpnas13_data03/11/3095811/html/wp-content/object-cache.php:520) in /home/content/p3pnexwpnas13_data03/11/3095811/html/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php on line 241

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/content/p3pnexwpnas13_data03/11/3095811/html/wp-content/object-cache.php:520) in /home/content/p3pnexwpnas13_data03/11/3095811/html/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php on line 241

**Comment by moldcraft** [comment]
The actual problem is the first warning, and it has nothing to do with Unyson

```
Warning: Class __PHP_Incomplete_Class has no unserializer in /home/content/p3pnexwpnas13_data03/11/3095811/html/wp-content/object-cache.php on line 520
```

You can try to just delete `wp-content/object-cache.php`
