### ISSUE TITLE
Using shortcode options in my plugin

### ISSUE THREAD

**Issue by TruongTuyen** [ThemeFuse/Unyson#1562]
Hi ThemeFuse,

Please tell me, can I using my shortcodes in my plugin with your plugin options. 
Ex: in my plugin I have a shortcode "demo", I want to use your shortcode options in my "demo" shortcode.
Do you have any way for this?

Thank.

**Comment by duongancol** [comment]
yes, if your plugin is written as an extension of Unyson. You could read more detail at Unyson Documentation

**Comment by TruongTuyen** [comment]
Thank you!

**Comment by Ataurr** [comment]
Use this filter
```
function _filter_fw_essentials($locations) {
        $locations[dirname(__FILE__) . '/extensions'] = plugin_dir_url(__FILE__) . 'extensions';

        return $locations;
    }
add_filter('fw_extensions_locations', '_filter_fw_essentials');
```
