### ISSUE TITLE
Override Column Shortcode

### ISSUE THREAD

**Issue by ariona** [ThemeFuse/Unyson#1563]
Can i override column shortcode? I tried to copy the columns shortcode to my framework-customizations folder and make some change but no effect.

I want to make the column can be placed on another column, kinda like nested column. Is there any work around instead of overriding the column class?

**Comment by thednp** [comment]
This question have been asked before.
The column nesting is not supported ATM and not in the near future. It might work if you override the entire class, but that won't be so easy.

**Comment by ariona** [comment]
So the column shortcode is kinda the shortcode that can't be override? What about adding options, Unlike section, there is no option for column.

**Comment by moldcraft** [comment]
> So the column shortcode is kinda the shortcode that can't be override?

Yes

> What about adding options, Unlike section, there is no option for column.

Create

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/options.php
```
