### ISSUE TITLE
Do not allow collapse for single box option type

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1565]
I cant find a post but I am sure we had this before. 
If we enable side tabs and inside the first tab we add one box , the box title is collapsible. 
Can we disable this if there is only one box type inside the tab? 

If I do 

    'title'   => false,

than title is completely gone but I dont want to do that 

here is test case

	'tab' => array(
		'title'   => __( 'Maintab', 'fw' ),
		'type'    => 'tab',
		'options' => array(
			'subtab' => array(
				'title'   => __( 'Some title', 'fw' ),
				'type'    => 'box',
				'options' => array(
					//
				),
			),
		),
	),

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1094

**Comment by danyj** [comment]
OCD :)
