### ISSUE TITLE
Most Content Elements showing "undefined error" when clicked on

### ISSUE THREAD

**Issue by kee2corp** [ThemeFuse/Unyson#1566]
Hello, It's a great framework you made. Thanks
Am having an issue when editing a page. Most content elements only show "error: undefined" when I click on them so I can't change their values.

For example when I add "Special Heading" to the page and click to change it's values. I get that error.

![before](https://cloud.githubusercontent.com/assets/19377240/15276686/1f2bdae4-1af8-11e6-8a74-eafd199c3bc8.jpg)

![after](https://cloud.githubusercontent.com/assets/19377240/15276691/26b0838c-1af8-11e6-8c67-7671ab04e378.jpg)

**Comment by moldcraft** [comment]
Hello,

Open Inspect Element (F12) and check ajax server response

**Comment by kee2corp** [comment]
Hi @moldcraft , I actually solved the problem by disabling modsecurity in Cpanel and all worked well. Though I think it's not a good Idea to do that. Is there any safer way?

**Comment by moldcraft** [comment]
I think it's a modsecurity issue. Similar https://github.com/ThemeFuse/Unyson/issues/1262

I don't know a solution for this.
