### ISSUE TITLE
After plugin update, background change to black color

### ISSUE THREAD

**Issue by zhizhong07** [ThemeFuse/Unyson#1567]
Hi,

After i updated to the latest unyson plugin, some of the element like heading, space, divider and others has black background instead of the normal white one.

Please kindly advice. I have tried to revert to the old one and it work so it is definitely the update that cause the problem.

You can check out my website at http://pegasusitsolution.com/

Thanks

**Comment by moldcraft** [comment]
Hello,

I think this should fix the problem https://github.com/ThemeFuse/Unyson/issues/1423

Please download latest Unyson dev version from Github and test.

Note that no Friday we will release new versions https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues
