### ISSUE TITLE
PHP Error: manifest.php not found

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1569]
Hello,

I'm working  on a website were I've made a child theme of an existing theme. I've installed Unyson, mainly to use the pagebuilder. That's working well.

But: I noticed my custom page templates weren't showing. So I installed Query Monitor. After installing that, I came across this PHP Error warning:

include(/var/www/vhosts/noesteprojecten.nl/subdomains/expertisecentrum/httpdocs/wp-content/themes/maskitto-light/framework-customizations/theme/manifest.php): failed to open stream: No such file or directory

and

include(): Failed opening '/var/www/vhosts/noesteprojecten.nl/subdomains/expertisecentrum/httpdocs/wp-content/themes/maskitto-light/framework-customizations/theme/manifest.php' for inclusion (include_path='.:')

I tried placing the manifest file manually, but no luck there. Does anyone know what might be the problem?

Thanks in advance!

**Comment by moldcraft** [comment]
Check `manifest.php` file permissions

**Comment by noesteijver** [comment]
Thanks! That did the trick!
