### ISSUE TITLE
Suggestion: Show option tab only if option_tap.php exists

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#157]
If we use tab option like this 

	'custom' => array(
		'title'   => __( 'Custom options', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			'sub_tab_1' => array(
				'title'   => __( 'Custom options', 'unyson' ),
				'type'    => 'box',
				'options' => array(
					fw()->theme->get_options( 'custom' ),
				),
			),
		),
	),

The tab still shows even if custom.php does not exists. Can we do a check for it before the tab is displayed ?

**Comment by moldcraft** [comment]
```php
$custom_options = fw()->theme->get_options( 'custom' );

'custom' => empty($custom_options) ? array('type' => 'hidden') : array(
    'title'   => __( 'Custom options', 'unyson' ),
    'type'    => 'tab',
    'options' => array(
        'sub_tab_1' => array(
            'title'   => __( 'Custom options', 'unyson' ),
            'type'    => 'box',
            'options' => array(
                $custom_options,
            ),
        ),
    ),
),
```

**Comment by danyj** [comment]
I dont think you understood what I mean. Or did I miss something you wanted to tell me ?
The code I used works perfect and I already made few tabs
what I am after is , if the custom.php does not exists 
than dont show the tab in admin are.

**Comment by danyj** [comment]
here 
http://www.uploady.com/#!/download/dZEYZ0LM5jZ/OH890NJ5jKCAEjx~
the tabs shows and the custom.php does not exists yet

**Comment by moldcraft** [comment]
I the `custom.php` does not exist, this `fw()->theme->get_options( 'custom' )` will [return an empty array](https://github.com/ThemeFuse/Unyson/blob/af5f98f657c667c48c3549eb6256a1b876dad69c/framework/core/components/theme.php#L70).
In this case, the code I show above, will generate

```php
'custom' => array('type' => 'hidden')
```

which in html will be just an invisible hidden input that does nothing. Also you can try to with an empty array

```php
'custom' => array()
```

in this case in html should be displayed nothing.

**Comment by danyj** [comment]
my bad , got it , I did not see the logic before the array
