### ISSUE TITLE
Slider not working in Chrome

### ISSUE THREAD

**Issue by damerms** [ThemeFuse/Unyson#1570]
1. The 1st slider does option does not show in Chrome. The text does not show for images in Chrome and Firefox. I added text to all the fields and nothing shows. I am using a theme called Tribute, but even when I preview the homepage in other theams, the text does not show. 

2. Also, why can't we add call to action link and or buttons?

**Comment by moldcraft** [comment]
1. I reproduced the problem, very strange. Inspecting...

**Comment by moldcraft** [comment]
1. The problem is in css animations, remove these classes and it will show up

    ![ice_screenshot_20160518-114254](https://cloud.githubusercontent.com/assets/1475489/15352632/c61b9e06-1ced-11e6-80f3-982e9eb9117a.png)

**Comment by moldcraft** [comment]
2 . On my side everything works fine

![staticshot_18-05-2016_11-47-56](https://cloud.githubusercontent.com/assets/1475489/15352740/580d1966-1cee-11e6-9f9a-1bf4e349350d.png)

![staticshot_18-05-2016_11-47-36](https://cloud.githubusercontent.com/assets/1475489/15352741/5ac92456-1cee-11e6-9986-e76af27830f6.png)

**Comment by danyj** [comment]
@moldcraft  I think he is think  about buttons and cta's in slides

**Comment by moldcraft** [comment]
You can [add slider custom options and overwrite the view](http://manual.unyson.io/en/latest/extension/slider/index.html#content) to print those options (as buttons and cta's)

**Comment by damerms** [comment]
Thanks. I may explore other slider options.
