### ISSUE TITLE
Text Block Pop-Up opens empty Can't edit a text or smth

### ISSUE THREAD

**Issue by barbarosva** [ThemeFuse/Unyson#1571]
Hello, When I Edit a "Text Block" popup opens empty. and cant change the or edit the text there. 
I updated Wordpress - updated unyson - updated extentions- updated the core theme still same. 
Please see the snap with the error of console ; 
www.visualartsonline.com/error-textblock.jpg
It says something about TinyMCE not defined. 

Awaiting your helps please... 

is somebody out there? :)

**Comment by moldcraft** [comment]
Please disable all plugins except Unyson and check if it fixes the error.

**Comment by moldcraft** [comment]
The wp-editor option-type was refactored, it should work fine now.
