### ISSUE TITLE
Create new tab section 

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1574]
How can I create new tab group? 
![capture](https://cloud.githubusercontent.com/assets/12174913/15417334/7f0c04ee-1e76-11e6-8f62-00d67276b0df.PNG)

**Comment by moldcraft** [comment]
Tab title is specified in [shortcode config](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file). It will be automatically created if doesn't exist.
