### ISSUE TITLE
Flash frontend messages within content/builder output , not outside.

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1575]
Not sure why you do this  but in forms  you are flashing the msg outside containers , and I think on other pages also. 

If this is a form error , dont just place the msg where ever , use the assigned containers please 

![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/15429257/659f3998-1ea0-11e6-8cbb-6a79925246cc.jpg)

**Comment by moldcraft** [comment]
[This script](https://github.com/ThemeFuse/Unyson/blob/v2.5.5/framework/helpers/class-fw-flash-messages.php#L273) prints flash messages by default. To disable default print, add in your theme

```php
if (defined('FW')) FW_Flash_Messages::_print_frontend();
```

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/v2.0.21/extensions/contact-forms/class-fw-extension-contact-forms.php#L180-L182

**Comment by danyj** [comment]
@moldcraft   well that is a terrible idea , why would you trace anyone's div id's or classes? An it is a sure miss on plenty of sites using Unyson. So if someone did not use any of these divs withint the structure there will be no messages? 

						var selector, selectors = [
							'#main #content',
							'#content #main',
							'#main',
							'#content',
							'#content-container',
							'#container',
							'.container:first'
						];
and if I disable it how would the messages show than?

**Comment by moldcraft** [comment]
I don't know another solution, frontend doesn't have a standard action/element for flash messages (like backend has `admin_notices` action), so I try to guess a good place based on standard wp themes frontend html structure. If you know a better solution, please share.

> So if someone did not use any of these divs withint the structure there will be no messages?

If nothing is found, they will be pepended to `body`

https://github.com/ThemeFuse/Unyson/blob/v2.5.5/framework/helpers/class-fw-flash-messages.php#L289-L297

**Comment by danyj** [comment]
Suggested move does not work for me 


I did this 


```
function thz_flash_fw_msg(){
	
	if (defined('FW')) {
		FW_Flash_Messages::_print_frontend();	
	}
	
}

```


and it should be displayed right after thz-main 

```

		$html .='<div class="thz-main">';
		$html .= thz_flash_fw_msg();
```

but it shows up after header   


![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/15605413/1476dd58-2406-11e6-8cd2-230ac5d217fd.jpg)

**Comment by moldcraft** [comment]
`thz_flash_fw_msg()` has no `return`, but you use string concat `$html .= thz_flash_fw_msg();`

https://github.com/ThemeFuse/Unyson/blob/v2.5.5/framework/helpers/class-fw-flash-messages.php#L178-L180 , but you can use in your function `ob_start(); ... ob_get_clean();`

**Comment by danyj** [comment]
I tried with return first and than it showed 

    Oops something went wrong. Coul
       1 //    return

**Comment by danyj** [comment]
![screenshot_8](https://cloud.githubusercontent.com/assets/2340172/15605605/524a81e2-2407-11e6-802c-29874f8b1038.jpg)

**Comment by danyj** [comment]
no man , no go , obp_ or no ob_  return or no , msg shows in wrong place. 
I even took it out of the function and placed it right after the wrappers start

![screenshot_9](https://cloud.githubusercontent.com/assets/2340172/15605713/f3929792-2407-11e6-84c2-3bec988ba447.jpg)

**Comment by danyj** [comment]
> string concat 

those html vars are is a peace of html within the returning function , so it ok without the return there

**Comment by moldcraft** [comment]
Add directly in template

```
if (defined('FW')) {
    fw_print('before');
    FW_Flash_Messages::_print_frontend();   
    fw_print('after');
}
```

and give a screenshot

**Comment by danyj** [comment]
this works for me 

    <?php thz_site_main_start();thz_flash_fw_msg(); ?>

but I still think that messages should be within the extension body, 
this is page builder page with a map above and  contact form under , and now my msg are displaying at the content start which is above the page builder content. So I have to jump trough hoops , JS/CSS/HTML/PHP to bring the form error msg to the form and within user point of view. Makes no sense. 

![screenshot_11](https://cloud.githubusercontent.com/assets/2340172/15606270/6d8798ec-240b-11e6-9bba-10f683351dbb.jpg)

if it is contact form msg/error than it should be displayed within the extension and not outside.

**Comment by moldcraft** [comment]
Form submit is processed before form render (before page content is generated) https://github.com/ThemeFuse/Unyson/blob/v2.5.5/framework/helpers/class-fw-form.php#L129
to be able to make redirect (if you try to redirect after first `echo`, you will get warning `Heareds already sent` and the redirect will not work)

So at the moment I don't know how to fix this.

**Comment by danyj** [comment]
than do ajax for submit and return the response instead 
http://extensions.youjoomla.info/yj-ajax-contact.html

**Comment by moldcraft** [comment]
I can't enable ajax submit by default because some themes activated their own ajax submit and it will conflict with our.

You can [enable ajax submit](http://manual.unyson.io/en/latest/helpers/php.html#ajax-submit) for your theme.
