### ISSUE TITLE
Cant remove title/subtitle from contact

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1576]
There is no way to remove title/subtitle from contact form 

![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/15429850/0f80f166-1ea3-11e6-89b5-3f41d0395b7b.jpg)

They also display default fw classes in frontend

![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/15429854/134cc4d2-1ea3-11e6-84ac-7efa494cfea8.jpg)

hardcoded here , 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/594f844fbb882c5a02cafcaa2163c99180afdff9/includes/option-types/form-builder/items/form-header-title/view.php#L13

you should use 

       $cfg['default_item_widths']['1_1']

**Comment by moldcraft** [comment]
Fixed hardcode, Thank you for reporting.

----

> There is no way to remove title/subtitle from contact form

* You will not be able to add it back if removed
* Just leaving it empty is not a solution?

**Comment by danyj** [comment]
>Just leaving it empty is not a solution?
it spits out html if empty , that is the problem 
http://prntscr.com/b7tlto

another thing is that I dont see the use of it , 
if you want title or subtitle you would add it above the form or am I missing something?

**Comment by danyj** [comment]
@moldcraft , ok that would work

**Comment by moldcraft** [comment]
```php
add_filter('fw:ext:forms:builder:load-item:form-header-title', '__return_false');
```

**Comment by pakiam** [comment]
@moldcraft any options to remove title from <form> tag? and place it outside?

**Comment by ViorelEremia** [comment]
@pakiam add this in functions.php
``` php
add_filter('fw:ext:forms:builder:load-item:form-header-title', '__return_false');
```

**Comment by pakiam** [comment]
@ViorelEremia thx for double comment, but I do no need remove it at all, I want to keep "native" method of adding a title, but remove it from form-items loop and place it to another div for example
