### ISSUE TITLE
How to manually install extensions?

### ISSUE THREAD

**Issue by swoosh983** [ThemeFuse/Unyson#1577]
I am using a theme with Unyson framework on a local server that is not connected to the internet. I successfully installed Unyson plugin but now it needs additional extensions like Megamenu, Shortcodes and Backups. Is there a way to manually install these extensions?

Thanks.

**Comment by moldcraft** [comment]
[Download](https://file.io/NdN6BL) this archive and extract in `wp-content/plugins/unyson/extensions`

**Comment by swoosh983** [comment]
{"success":false,"error":404,"message":"Not Found"}

This is the error that I get when I try to download the file.

2016-05-21 12:17 GMT+02:00 moldcraft <notifications@github.com>:

**Comment by moldcraft** [comment]
https://dropfile.to/5wMbSuB

**Comment by moldcraft** [comment]
http://gofile.io/?id=Zz5QXh

**Comment by swoosh983** [comment]
OK. Thanks. Just downloaded it.
