### ISSUE TITLE
Demo content Install issue: Cannot close the zip file

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1578]
One of our buyers tried to install our theme. and they getting this error. **Cannot close the zip file**

![](http://puu.sh/oZKib/05ffe8264f.png)

**Comment by moldcraft** [comment]
Please check error log for more detailed error message.

**Comment by moldcraft** [comment]
Can you share what was the problem?

**Comment by Ataurr** [comment]
Buyers open a support ticket about this. and i just told him to increase php max_execution_time and Memory limit.
And he dont contact with me anymore. but he open another support ticket for for others thing. 

So i think  this issue related to php max_execution_time or Memory limit.

**Comment by Ataurr** [comment]
I am facing another issue while installing remote demo content.

![](http://puu.sh/p3zHl/e88282d808.png)

When i check error through http://requestb.in/w77aruw7?inspect

Cant fine the issue

**Comment by moldcraft** [comment]
`gzinflate(): data error` https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/9#issuecomment-171257413

**Comment by Ataurr** [comment]
This shouldnt be any issue with ZIP. Cause my zip file size 4.7MB only.

This 500 error occurred when just tried to download the content. 

BTW i will investigate this issue today

**Comment by moldcraft** [comment]
> This 500 error occurred when just tried to download the content.

So it is 500 response from your server.

Maybe the client host is blocking requests to your server? Execute this piece of code

```php
add_action('admin_notices', function(){
    fw_print(file_get_contents('http://{YOUR_SITE_URL}'));
});
```

**Comment by Ataurr** [comment]
Got this issue.
I was forget to zip f folder (uploads files)

**Comment by danyj** [comment]
and I get invalid  source dir after the directory cleanup process, nothing is installed 
![screenshot_18](https://cloud.githubusercontent.com/assets/2340172/15826217/04479d9c-2c07-11e6-87f7-41ea09a1cf2a.jpg)

**Comment by moldcraft** [comment]
@danyj Your zip contains this directory structure?

```
database.json.txt
f/
    uploads/
```

**Comment by danyj** [comment]
@moldcraft    , yes  

http://prntscr.com/bd1t49
http://prntscr.com/bd1t8j

**Comment by danyj** [comment]
@moldcraft ,  tested now again , same zip , clean  empty WP install , same error but this time was much faster to popout

**Comment by danyj** [comment]
@moldcraft   check skype for  details please
