### ISSUE TITLE
How to Create Option Type?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#158]
Sorry but this here does not say where to add the extend 
http://unyson-docs.themefuse.com/en/latest/options/create-option-type.html#content
What is the structure we should follow. 
This #89 seems to be outdated.

**Comment by moldcraft** [comment]
Add it anywhere you want. If you use https://github.com/ThemeFuse/Theme-Includes add it in the `includes/` directory. Also make sure it is included only

```php
if (is_admin() && defined('FW')) { ... }
```

**Comment by moldcraft** [comment]
You can find the structure example in `plugins/unyson/framework/includes/option-types/`

**Comment by danyj** [comment]
does not work 
Fatal error: Class 'FW_Option_Type' not found 
file is located inside the inc/ includes folder

function.php is calling 
include_once get_template_directory() .'/inc/init.php';

bit more on the docs would be really valuable. 
this is becoming a guessing game.

**Comment by moldcraft** [comment]
Add it anywhere you want. If you use https://github.com/ThemeFuse/Theme-Includes add it in the `includes/` directory. Also make sure it is included only when the framework is loaded and you are on the admin page

```php
/** @internal */
function _action_theme_include_custom_fw_options() {
    if (is_admin()) {
        require '.../class-fw-option-type-typography-custom.php';
    }
}
add_action('fw_init', '_action_theme_include_custom_fw_options');
```

**Comment by moldcraft** [comment]
Thank you for pointing out the docs flaws. We will try to improve it

**Comment by moldcraft** [comment]
I added more info to http://unyson-docs.themefuse.com/en/latest/options/create-option-type.html#content
