### ISSUE TITLE
Performance concerns

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1581]
@moldcraft  When you get a chance check this out ,  https://wordpress.org/plugins/p3-profiler/screenshots/

install on Unyson  based site and run it , based on this plugin Unyson is killing site performance on my end ,

![img 1](https://cloud.githubusercontent.com/assets/2340172/15452952/07d19862-2001-11e6-8ef7-f038448a4060.png)

I even tested with removing all styles and scripts calls inline or files and same thing ,
removed also anything that could effect performance but results are same 

not sure if it is last version fault , but since the update I see min 0.5s slower site

this is on scratch theme with no content at all , just a hello word post, clean WP install , Unyson and scratch activated

![img 2](https://cloud.githubusercontent.com/assets/2340172/15452953/1206bde4-2001-11e6-8020-961e2e9c780e.png)

I tested this plugin also on avada to exclude the falses and make sure is not just checking if the plugin is simply active thus always showing it in action 

![img 3](https://cloud.githubusercontent.com/assets/2340172/15452955/1c1cc774-2001-11e6-9e69-00b082c67de5.png)

as you can see fusion which is the avada core and runs everywhere is performing much better than unyson

**Comment by danyj** [comment]
@moldcraft  Heads up ,   found most load increase affected by page builder and mega menu , 
strange thing is that I am not even using builder on blog homepage, 
there are no shrotcodes , no builder styles nothing , 
but if I enable builder in blog posts  trough the extension settings, 

the load time increases from 1.7s, to 2.1s  instantly 

I see no reason why this should be when the builder is not even used  in any of the posts. 
all I have is a post image , and short excerpt http://prntscr.com/b73ju3

mega menu adds another 0.3s

and each Unyson extension weather it is used or not adds aprox 0.1 to 0.2sec

again , I am testing it on a blog homepage/frontpage that has 

6 posts , 
8 images  ( up to 5kb each )

disabling builder on posts, and deactivating all extensions saves me 1sec, 
I go from 2.2, to 1.2s and the strange thing is that **none** of those extensions are loading any CSS or JS files on the homepage. 

Please check.

**Comment by moldcraft** [comment]
You are using Windows or Mac OS? HDD or SSD? If it is a hosting, which one?

**Comment by danyj** [comment]
WIn 10 , SSD, localhost , wamp , php 5.4.17  mySQL , 5.1.36

this comp is better than my dedicated 

![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/15469218/142bf3f8-20e9-11e6-94f7-c60415e50877.jpg)

**Comment by danyj** [comment]
il setup dedicated envr for you to check , few min

**Comment by moldcraft** [comment]
> Win 10

Ah, bad. On Linux or MacOS you can install https://blackfire.io/ and inspect how the php was executed for current page

[ ![](https://static.md/241f913d846970122187b7d96f86c338.png) ](https://static.md/241f913d846970122187b7d96f86c338.png)

**Comment by danyj** [comment]
ok tested same setup on live server , 
it is huge diff in frontend speed , my site is faster with more 10 post and 10 big images 
I get 1.2s, 

autoptimize and wp cache on I get 667ms 


now this plugin performace test is done on unyson scratch live 

http://prntscr.com/b7e7wk

so the question is , what does that plugin test ?

**Comment by moldcraft** [comment]
> what does that plugin test ?

Please ask this question plugin developers

----

Please try to install blackfire on windows https://blackfire.io/docs/up-and-running/installation 
I tried once (a few months ago) but it didn't worked, but maybe now it works on windows.
You will be able able to get more accurate info about performance.

**Comment by danyj** [comment]
>Please ask this question plugin developers
was about to

**Comment by moldcraft** [comment]
I get ~1s with TheCore frontpage _(Intel i5, SSD, Linux / Ubuntu 16.04, PHP 7)_

![](https://static.md/5fc42ad6c7a1b116c102c2d5a88902a5.png)

**Comment by danyj** [comment]
I doubt that there will be any replies according to support tickets ,
https://wordpress.org/support/plugin/p3-profiler
and the last update a year ago. Looks like godaddy just want WP users not to install any plugins 
they want but to use the ones that fits godaddy servers architecture.

**Comment by danyj** [comment]
https://wordpress.org/support/topic/is-this-project-abandoned?replies=1#post-8435359

**Comment by danyj** [comment]
il close this for time being until someone replies and ensure us that the coloring chart is doing what is supposed to do and not simply checking if our plugin is present or some of its classes are being used.

**Comment by danyj** [comment]
@moldcraft  we got a reply 
https://github.com/godaddy/wp-p3-profiler/issues/1#issuecomment-222743234

**Comment by moldcraft** [comment]
On my side (PHP 7) I don't see Unyson at all

![](https://static.md/03090bbc8072a17a039ed4ad54fa080e.png)

![](https://static.md/02b5da6873556377c99e8e18b3a27815.png)

**Comment by danyj** [comment]
>On my side (PHP 7) I don't see Unyson at all

nice ! 

I am on  5.4.17 ,   
will switch test to 7 and report back

**Comment by danyj** [comment]
ok , can confirm , same , full blown theme with plenty of options , all extensions , Unyson + my own plugin , nothing shows 

but , pay attention to your    Plugin impact .  

![screenshot_16](https://cloud.githubusercontent.com/assets/2340172/15709741/a252ae82-2806-11e6-9dea-b98ae60beb9e.jpg)


mine shows    861667.2%

**Comment by moldcraft** [comment]
I know only 2 places that are slow:

1. Buider display in frontend, the conversion: json -> [shortcodes] -> html
2. Extensions and files loading/locating. On every refresh all nested extensions directories are scanned and the `locate_path('rel/path')` `locate_uri('rel/path')` functions are scanning directories.

    I thought to create a file cache in `wp-content/uploads` but don't know when to reset it ( on every admin page load? ) and don't know if it will really will boost the performance (only testing will show)

**Comment by danyj** [comment]
One more to check , you asked me once why I  used is_admin when including option types 
https://github.com/ThemeFuse/Unyson/issues/1459#issuecomment-209918058

and I forgot to explain , I saw page speed increase if I dont load the option types classes in frontend ,

**Comment by danyj** [comment]
>Buider display in frontend, the conversion: json -> [shortcodes] -> html

Isn't there a "silent"   backend PHP worker way to convert those and have them ready on page load ? 

like a compiler type thing that runs after you have saved the post

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1581#issuecomment-222984770

Option types are needed in frontend because all builder options are processed because of this feature https://github.com/ThemeFuse/Unyson/issues/838

1. https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/v1.2.2/includes/option-types/builder/extends/class-fw-option-type-builder.php#L554-L616
2. https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.5/includes/page-builder/includes/item-types/class-page-builder-item.php#L133-L177

> https://github.com/ThemeFuse/Unyson/issues/1581#issuecomment-222985255

It was like that, but prepared `[shortcodes]` get very big and you get `MySql gome away` error https://github.com/ThemeFuse/Unyson/issues/838#issuecomment-175828643

**Comment by danyj** [comment]
yes I know about MySql issue , but I was thinking about backend process , not while saving ( that was where we had  the bug )  but rather after everything is saved

**Comment by moldcraft** [comment]
what exactly is your proposal?

**Comment by danyj** [comment]
ok ,  this is what I was doing for less recompile , 
I was tired of the slow first time page load so I would 
left all CSS/LESS file loads normal , 
check for compiled file existence and set  JS compile variable to 0 if file is missing 

on page load JS reads that var and if it is 0 ,  it just pings the same page via ajax and reloads it 
https://github.com/YJSGframework/yjsg/blob/master/assets/src/yjsg.site.js#L1077

less , is compiled and compressed file is saved and served , 


so the proposal 


let builder do what it does normally now 

set some hook var to check if we have  shortcode HTML in DB on first time page load ,  
if not ,  convert the json  to shortcode to html via ajax , save it , and serve it on the next page load 


when page is saved again , deleted the saved html and just let the process repeat itself.

**Comment by danyj** [comment]
this is how I trigger the compiler 
https://github.com/YJSGframework/yjsg/blob/master/assets/src/yjsg.site.js#L1075

**Comment by moldcraft** [comment]
html is dynamic, it can be generated from "Latest posts" or "Latest tweets", it is not static, we can't generate it once and serve every time.

> shortcode HTML in DB

This also can get very big, I think bigger than `[shortode]`, and we can't save it in db (MySql will gone away)

**Comment by danyj** [comment]
well ,  I think this is ok :) for a homepege with 10 posts  with 10 big images considering that we did not do any compression and or optimization yet. 
![58bf294ca3ce4e0da6639d4e48e45f65](https://cloud.githubusercontent.com/assets/2340172/15781016/8920c5f8-29a4-11e6-8b92-ad001707a32c.png)

**Comment by danyj** [comment]
@moldcraft   tell me ,   when builder options are saved , are  containers names ( tab/box/group) saved as well  and are they at all used when frontend is rendering? 

Im asking because all my shortcodes have multiple tabs and I gave the mid size array names like ,  `sectiondefaulttab ` so all options inside those get parent array key name as prefix . just trying to cut the size of the post , that's all.

**Comment by moldcraft** [comment]
No. Check database post meta value (use an online unserialize tool)

**Comment by eyeswizard** [comment]
i reported this issue today and you mentioned me to this page and i didn't see any solve for the performance problem !

**Comment by kowsar89** [comment]
Is this issue solved yet? I still see the performance issue in php version 5.6.23

**Comment by kowsar89** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/6196149/19686480/2d08d1f6-9ae3-11e6-9d75-fe9560370e03.jpg)

This test is done on localhost (xampp-windows) using plugin "P3 Plugin Profiler". And this test only includes home page performance. Installed Theme: _s. No extra plugins installed. Also no extra Unyson's extensions installed. 

Here the wp core load time is 0.126s and Unyson's load time is 0.155s. You see, Unyson's load time is more than wp core load time(in frontend) which is really frightening.

**Comment by moldcraft** [comment]
I think this 0.15 fine, it's a framework with a lot of functionality and extensions. I thought it was 3+ seconds.

**Comment by kowsar89** [comment]
I understand that it makes sense to take this amount of load time when there is a lot of functionalities. But i don't think that all these classes and codes are needed in front-end, maybe for front-end it can be reduced. When embedding redux framework i usually use is_admin() function to get way with it and that works fine for me. But for Unyson i'm not sure yet.

I have no complain if tons of files are loaded in back-end. But, isn't it possible to improve it in that way so that only necessary files are loaded in front-end?

**Comment by moldcraft** [comment]
We tried to included only the required files in frontend. You can inspect the framework load yourself and detect which files are included useless in frontend and provide a pull request.

**Comment by andreiglingeanu** [comment]
> which files are included useless in frontend and provide a pull request

Or, at least, let us know.

**Comment by kowsar89** [comment]
These are the files (total 42) that's are loaded into front-end:

    unyson.php
    framework\bootstrap.php
    framework\bootstrap-helpers.php
    framework\helpers\class-fw-dumper.php
    framework\helpers\general.php
    framework\helpers\class-fw-cache.php
    framework\core\Fw.php
    framework\core\class-fw-manifest.php
    framework\manifest.php
    framework\core\extends\class-fw-extension.php
    framework\core\extends\interface-fw-option-handler.php
    framework\core\components\extensions.php
    framework\core\components\extensions\class-fw-extension-default.php
    framework\core\components\extensions\manager\class--fw-extensions-manager.php
    framework\core\components\backend.php
    framework\core\components\theme.php
    framework\helpers\meta.php
    framework\helpers\class-fw-access-key.php
    framework\helpers\class-fw-wp-filesystem.php
    framework\helpers\class-fw-file-cache.php
    framework\helpers\class-fw-form.php
    framework\helpers\class-fw-request.php
    framework\helpers\class-fw-session.php
    framework\helpers\class-fw-wp-option.php
    framework\helpers\class-fw-wp-meta.php
    framework\helpers\class-fw-db-options-model.php
    framework\helpers\fw-storage.php
    framework\helpers\database.php
    framework\helpers\class-fw-flash-messages.php
    framework\helpers\class-fw-resize.php
    framework\helpers\class-fw-wp-list-table.php
    framework\helpers\type\class-fw-type.php
    framework\helpers\type\class-fw-type-register.php
    framework\includes\hooks.php
    framework\extensions\blog\class-fw-extension-blog.php
    framework\extensions\blog\manifest.php
    framework\extensions\update\class-fw-extension-update.php
    framework\extensions\update\includes\extends\class-fw-ext-update-service.php
    framework\extensions\update\manifest.php
    framework\extensions\update\extensions\github-update\class-fw-extension-github-update.php
    framework\extensions\update\extensions\github-update\manifest.php
    framework\extensions\update\static.php

I can't go through all the files. My question is, are all of them necessary in front-end? For example, what is the role of "class-fw-extension-github-update.php" in front-end?

Maybe a single file which is responsible for providing the getter functions(getting post meta, options etc from database) is enough in front-end.

**Comment by andreiglingeanu** [comment]
> what is the role of "class-fw-extension-github-update.php" in front-end

The update extension is totally not acceptable to be loaded in frontend. Thank you. I'll go about fixing it.

**Comment by moldcraft** [comment]
All extensions are always loaded. You can't know if an extension has frontend functionality or not. Update extension has functionality in frontend but only when the user is logged in as admin

![screenshot from 2016-10-26 13-52-19](https://cloud.githubusercontent.com/assets/1475489/19723356/980e247e-9b83-11e6-99b4-7963d2cc96df.png)

**Comment by andreiglingeanu** [comment]
> All extensions are always loaded. You can't know if an extension has frontend functionality or not

Yes, the extension itself has to decide when to require its files.

> Update extension has functionality in frontend

Didn't know about that. Thanks.

**Comment by kowsar89** [comment]
> Update extension has functionality in frontend but only when the user is logged in as admin

That's fine, but thing is update extension is still loaded when user is not logged in. ( My checking method: i created a plugin to check which files are loaded in which pages)

> All extensions are always loaded.

Loading an extension even when there is no functionality, this is bad i think.

**Comment by andreiglingeanu** [comment]
> Loading an extension even when there is no functionality, this is bad i think

There's no way to know if there's any functionality in an extension. It's up to extension developer to not load certain files based on conditions like `is_admin()` or `current_user_can()`. That's why we don't allow any extension to be added into the core of the framework.

**Comment by kowsar89** [comment]
> That's why we don't allow any extension to be added into the core of the framework.

What about core extensions and files that comes with the plugin by default? I meant "Blog" and "update" extensions.

I want to make a suggestion. Since all options and meta values are stored into database, is it possible to make a single file which contains only getter functions to grab those values from database? That way i can decide if i want to load the whole framework or not in front-end using is_admin() function. ( You see, i don't care about other extensions, i only use unyson for core functionalities eg. customizer, options, metabox etc)

**Comment by moldcraft** [comment]
> is it possible to make a single file which contains only getter functions to grab those values from database?

At the moment we can't do that because it seems like a simple task but it can become complicate, it can split Unyson in a separate Unyson Light version, and it will need additional maintenance work (bug fixes, updates).

You can copy parts of Unyson (functions, classes) to your theme and create some kind of your personal framework with minimal functionality.
