### ISSUE TITLE
fw_get_db_post_option if used outside loop , catches first post options

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1582]
I am using this inside my theme options function 

```
function thz_get_post_option($option_id = null, $default_value = null){

   return  fw_get_db_post_option(get_the_ID(), $option_id, $default_value)
}
```

problem is when I use this function or 

     fw_get_db_post_option(get_the_ID(), $option_id, $default_value)

outside of a loop ,  it always catches the first post from the loop and returns its values 

try this on blog archive page outside of a loop 

    fw_print(fw_get_db_post_option(get_the_ID()))
    fw_print(fw_get_db_post_option(0))
   

you get options from the first post

**Comment by danyj** [comment]
Even if I use this for the id 


```
function _thz_post_id() {
  if (in_the_loop()) {
       $post_id = get_the_ID();
  } else {
       $post_id =get_queried_object_id();
         }
  return $post_id;
}

```
it wont work because  `fw_get_db_post_option `returns first item options set if ID is 0


this works but it is a stupid hack 

```
function _thz_post_id() {
  if (in_the_loop()) {
       $post_id = get_the_ID();
  } else {
       $post_id =get_queried_object_id() == 0 ? 999999999999 :get_queried_object_id() ;
         }
  return $post_id;
}
```

**Comment by moldcraft** [comment]
I added in `{theme}/archive.php`

![](https://static.md/0cbc6372721b75c2583249b4f379dcb4.png)

And first print for post `6090` is different than last print for `2495` [screenshot](https://static.md/f0198eeb9aba87cff9d7921e550e3ec3.png)

So seems to work fine.

Can you show code from your `{theme}/archive.php`, or give the exact code to reproduce the problem?

**Comment by danyj** [comment]
use it outside of a loop , not in archive
![screenshot_13](https://cloud.githubusercontent.com/assets/2340172/15654105/b58f7fb4-2691-11e6-8805-e2b6aee5f191.jpg)

**Comment by danyj** [comment]
@moldcraft  it should not return first or last item  options if it is outside of a loop, 
if outside than  archive is main and not any of the posts within the loop

**Comment by danyj** [comment]
and you did reproduce the exact issue ,  you are getting data back outside of the loop where you shouldn't

**Comment by danyj** [comment]
fw_get_db_post_option is for posts options within the loop or on the posts page ,  on archive page outside of the loop it should not give you first/last item from loop data

**Comment by moldcraft** [comment]
`get_the_ID()` outside loop returns and ID, so this also looks like a bug, and I would say that the bug is in WP, `fw_get_db_post_option()` uses `global $post;` when post_id is not specified, so `global $post;` should not be initialized outside loop on archive page.

**Comment by danyj** [comment]
ok ,  I see https://github.com/ThemeFuse/Unyson/blob/954b7a8966789766da8db9888c21b50efda9f2ae/framework/helpers/database.php#L183

should I use this than ?


```
function _thz_post_id() {
  if (in_the_loop()) {
       $post_id = get_the_ID();
  } else {
       $post_id =get_queried_object_id() == 0 ? 999999999999 :get_queried_object_id() ;
         }
  return $post_id;
}
```


or will you patch the   `fw_get_db_post_option` ?


as for `get_the_ID`, I submitted a ticket
https://core.trac.wordpress.org/ticket/36980#ticket

**Comment by moldcraft** [comment]
I will wait a reply on https://core.trac.wordpress.org/ticket/36980#ticket

**Comment by moldcraft** [comment]
https://core.trac.wordpress.org/ticket/36980#comment:1

**Comment by danyj** [comment]
replied

**Comment by moldcraft** [comment]
https://core.trac.wordpress.org/ticket/36980#comment:5

**Comment by danyj** [comment]
@moldcraft  I understand why they closed it and that many relied on the bug which is completely wrong , but why are you closing the issue when you  know it is a bug? 

look up The Core setup https://static.md/f0198eeb9aba87cff9d7921e550e3ec3.png

you have a `header_image `,    set it to be displayed on item ID 6090   and it will be also displayed in archive view since the core bug will pick it from the loop. 

I mean I can use my function but  ad least we should do something about it if the WP core wont.

**Comment by moldcraft** [comment]
Usually `fw_get_db_post_option(...)` is called with `$post_id`

![screenshot from 2016-06-02 11-56-45](https://cloud.githubusercontent.com/assets/1475489/15739525/19b9d380-28b9-11e6-97a4-b0283155b185.png)
