### ISSUE TITLE
[Bug] Schedule mode doesn't work with metabox

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1584]
Hi! 
The metabox value'll be removed when you create a post that in Schedule mode. Please see detail in the screenshot. 
http://take.ms/vX4cN
http://take.ms/WlJdq
http://take.ms/A3Dmn

Thanks!

**Comment by moldcraft** [comment]
Post Title and Content are empty? Maybe that is the problem

**Comment by duongancol** [comment]
Any news, mate?

**Comment by moldcraft** [comment]
On my side it works https://vid.me/Gnl6

**Comment by duongancol** [comment]
Did you check at the frontend & try to let it publish automatically!

**Comment by duongancol** [comment]
I'll make the screencast later

**Comment by duongancol** [comment]
Hi @moldcraft : please look at the screencast here: https://monosnap.com/file/dStD2wfWwi89N4mxXEPLQbYRoVt2Ow
I think the key is that you have to wait for the post is publish automatically.

**Comment by moldcraft** [comment]
Thank you for screencast

**Comment by moldcraft** [comment]
https://sendvid.com/gttziml6

**Comment by duongancol** [comment]
What could be the problem? I think I should send you the url to test it directly

**Comment by duongancol** [comment]
Is this ok?

**Comment by moldcraft** [comment]
Try with a default WP theme. (Maybe the problem is in theme)

**Comment by duongancol** [comment]
currently, the metabox option is written at theme but I'll try to move to plugin extension to test it.
