### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1585]
Lorem ipsum

**Comment by danyj** [comment]
OK a year is not that long and I will not be leaving this any time soon. It would be great if @andreiglingeanu  could pick up or if we could get someone that is @moldcraft  level to be main maintainer. Please dont make me fork the project.

**Comment by duongancol** [comment]
It's not a good news. Unyson core is really great at the beginning but I don't know how your team couldn't  develop. I see that someone left and @moldcraft is only the maintainer now. I think Unyson could develop better than that. But good luck and thank you, mate!

**Comment by markcofano** [comment]
Moldcraft,

Thanks for the heads up!  Not many people would be so considerate and give
a year's notice.  Please keep us updated as you get closer to the date.

Mark

**Comment by thednp** [comment]
Sorry to hear the news, I've finished moving from another framework some time ago, now developing on Unyson.

I hope we can at least have it "stable" for 2-3 years from now on, because we invested so much time in in this framework, it's hard to see this go...

**Comment by moldcraft** [comment]
Please don't panic. ThemeFuse will take care of Unyson and will find developers to support it.
I just wanted to inform you about my long term plans and to invite you to be more active and to make Unyson be supported by a community of developers, not only by one developer.
