### ISSUE TITLE
Popup modal option-type is not get triggered in customizer - Unyson Version 2.5.4 

### ISSUE THREAD

**Issue by thenewelementz** [ThemeFuse/Unyson#1586]
Hi,

I am wondering if anyone else is getting this bug? The Popup Modal option-type stopped working for me in the customizer. The Unyson logo/graphic still loads on popup button click, but you don't see the modal. 

The bug was produced after I upgraded to Version 2.5.4. 

Any help would be much appreciated, thanks!

**Comment by moldcraft** [comment]
Tested with `{theme}/framework-customizations/theme/options/customizer.php`

```php
$options = array(
	'x' => array(
		'type' => 'addable-popup',
		'popup-options' => array('t' => array('type' => 'upload')),
	),
);
```
