### ISSUE TITLE
Page builder element usage with multisite

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1587]
Hello,

At this moment I am wondering how to copy sections/columns or templates in page builder and paste it to another multi-site?
This could be very useful to know, because now I need to create many elements by scratch.

**Comment by moldcraft** [comment]
At the moment it is not possible from UI. Also section/column templates are saved in one wp_option as serialized array.

I just made [these changes](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/934e563c7ad8749ad6ab4f18ebdf5e9a1c6d1601) and all new templates will be saved in separate wp_options. You can move the templates manually using phpMyAdmin. To select the templates, us this query

```sql
SELECT * FROM wp_options WHERE option_name LIKE 'fw:bt:%'
```

Unfortunately, there are no plans to provide a way to export/import templates in a visual way.

**Comment by pear1** [comment]
Thank you.
Can't we just add all wp_options tables with left join and therefore allow import from all sites?

Another way could be to just allow copy plain code and paste it in another site.

**Comment by moldcraft** [comment]
> Can't we just add all wp_options tables with left join and therefore allow import from all sites?

Doesn't sound like a good idea.

**Comment by pear1** [comment]
Oh, I mean select them with left join.

**Comment by moldcraft** [comment]
You can use [this filter](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/v1.2.2/includes/option-types/builder/includes/templates/class-fw-ext-builder-templates-component.php#L69) add add your custom loaded templates in list

**Comment by pear1** [comment]
Didn't know about it, I will try.

**Comment by pear1** [comment]
When these updates could be live?

**Comment by moldcraft** [comment]
Next week
