### ISSUE TITLE
Question: How to run Unyson shortcode with do_shortcode() if it has an array in params?

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1588]
Hello!

I'm wondering, is it possible to run Unyson shortcode with do_shotcode() function if it has an array in params? e.g. i'm trying to show a map inside Tabs, but how can i add "data_provider" attribute that contains "population_method", "coordinates", "address", "city", "country", "venue", "location" params as array?

i mean, map shortcode looks like this in the database:

```{"type":"simple","shortcode":"map","atts":{"data_provider":{"population_method":"custom","custom":{"locations":[{"location":{"location":"Melbourne, Victoria, Australia","venue":"Melbourne","address":"","city":"Melbourne","state":"Victoria","country":"Australia","zip":"","coordinates":{"lat":-37.8142155,"lng":144.9632307}},"title":"","description":"","url":"","thumb":""}]}},"map_type":"roadmap","map_height":"330","disable_scrolling":false}}```

how can i run in with do_shortcode() function?

Thanks for an answers an explanation :)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1071#issuecomment-161586475
