### ISSUE TITLE
How to overwrite parent-theme/theme-includes/static.php ?

### ISSUE THREAD

**Issue by Alex-Ascet** [ThemeFuse/Unyson#1589]
Hi there,

I would like to overwrite parent-theme/theme-includes/static.php by using a child-theme/theme-includes/static.php in order to dequeue some scripts and styles (Prettyphoto in this case) but it does not work. 
What is the best practice to do that, do I need to add the dequeue script in function.php?

Thank you for your help.

**Comment by thednp** [comment]
If you have followed the [Theme Includes](https://github.com/ThemeFuse/Theme-Includes) code guidance you will learn that your child themes don't need any additional code to be able to override core framework/theme code.

Now, do you have some more details on your issue?

**Comment by moldcraft** [comment]
[Fixed](https://github.com/ThemeFuse/Theme-Includes/commit/414cb76afa5ca0fca7de620385f4d698f9a21362), download latest version of [theme-includes](https://github.com/ThemeFuse/Theme-Includes)

**Comment by Alex-Ascet** [comment]
Perfect! Thank you @moldcraft and @thednp

Could you please add this piece of code in TheCore next update? Thank you in advance.

**Comment by thednp** [comment]
The fix was about the Theme Includes only.

**Comment by Alex-Ascet** [comment]
Yep, thanks for that. I have added this code in my parent theme already. As I am using TheCore theme, I was just wondering if @moldcraft could add this in the next update of TheCore parent theme as I presume he is a part of the great ThemeFuse team. Thx @thednp

**Comment by moldcraft** [comment]
I noticed TheCore developers about this fix
