### ISSUE TITLE
framework-customizations styles not working..

### ISSUE THREAD

**Issue by alkeshgupta** [ThemeFuse/Unyson#159]
I am using unyson as a plugin.
I am changing style for accordion so i made styles.css file here 

framework-customizations/extensions/shortcodes/shortcodes/accordion/static/css/styles.css

but its not working.. please help

**Comment by moldcraft** [comment]
Sorry, I didn't read the docs attentively. There is nothing saying about creating `style.css` in theme to overwrite it.

The right way to do it is to overwrite `shortcodes/shortcodes/accordion/static.php` in theme, so create 

```
framework-customizations/extensions/shortcodes/shortcodes/accordion/static.php
```

and enqueue your assets.

**Comment by moldcraft** [comment]
Sorry, I didn't read the docs attentively. There is nothing saying about creating `style.css` in theme to overwrite it.

The right way to do it is to overwrite `shortcodes/shortcodes/accordion/static.php` in theme, so create 

```
framework-customizations/extensions/shortcodes/shortcodes/accordion/static.php
```

and enqueue your assets.

**Comment by alkeshgupta** [comment]
Hello,

can you write just a bit of code for that.. like if we want to overwrite this style

.fw-accordion { border: 1px solid #eee;}

**Comment by alkeshgupta** [comment]
Hello,
I tried what you told.. but its not including styles... please check again ..

Thanks

**Comment by moldcraft** [comment]
I tested that code.
Debug it to find out why it is not including.

**Comment by alkeshgupta** [comment]
found it .. fixed.
Thanks
