### ISSUE TITLE
Just a feature suggestion for the one of next updates :)

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1590]
Hi, Unyson authors!

I would like to make a suggestion for one of the following updates: could you add "redirect" feature to the forms? E.g. if the user wants to open another page once form submitted.

Now it can be done by adding some JavaScript to the "Successfull text" message, but you might also find this function as useful.

And i have a question, do you plan to make Front-end page builder? I think this feature is not enough for many users. Maybe, you can create this extension as premium, I would gladly bought developer's license for this add-on.

Thank you again for your work!

Kind regards, Dmitriy

**Comment by moldcraft** [comment]
> could you add "redirect" feature to the forms?

You can use [this action](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/v2.0.21/class-fw-extension-forms.php#L225) to do `wp_redirect(...); exit;`

> do you plan to make Front-end page builder?

No.
