### ISSUE TITLE
Failed to access Github repository 

### ISSUE THREAD

**Issue by Lamorra** [ThemeFuse/Unyson#1591]
Hello, 

we are having problems activating the extensions for the theme Philanthropy. See below the error we get. 

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (connect() timed out!)

I read that it is a problem with our server however i called them and they were not able to help that much. 

Would be great to get support for us to fix the problem ourselves!

thanks so much

**Comment by moldcraft** [comment]
Hello,

Add in `{theme}/functions.php`

```php
add_action('admin_notices', function(){
    fw_print(wp_remote_get('http://github-api-cache.unyson.io/repos/ThemeFuse/Unyson-Shortcodes-Extension/releases/latest'));
});
```

**Comment by cricketwhites** [comment]
Hi there

I am having the same issue and I have tried the above fix but it doesn't work. Which line should this be placed in? Is there another fix?

Thanks

**Comment by moldcraft** [comment]
> I have tried the above fix but it doesn't work

That is not fix, it's debug. We need to find out if the hosting is blocking requests to github api.
