### ISSUE TITLE
Page Builder - Timelines 

### ISSUE THREAD

**Issue by lissaahmad** [ThemeFuse/Unyson#1595]
Hi,

Thumbs up to the team! You have done a great job on building Unyson Framework. :+1: :+1: 

However, I have a small problem with the timelines function in Page Builder extension. 
I've created Day 1, Day 2 & Day 3 with time and some details. The admin forms works well on adding the days & times (refer the screenshot below). 

When comes to the output in page view, Day 1 appeared well with times and other details. But, when I clicked at Day 2 & Day 3, nothing happened. Seems like the link or CSS is broken. When I hover on Day 2 & Day 3 it shows the URL on the status bar: #period-1 for Day 2 and #period-2 for Day 3.

I'm using Wordpress Version 4.5.2 | Unyson 2.5.5

Please help. 

![screenshot-viis16 tk 2016-05-26 20-49-58](https://cloud.githubusercontent.com/assets/19590846/15575089/b022798e-2383-11e6-9a28-9eb43e68b3ef.png)

**Comment by danyj** [comment]
@lissaahmad  you need to post this to your theme provider support, timeline is not default Unyson shortcode or option.

**Comment by lissaahmad** [comment]
OK. Thanks @danyj

**Comment by danyj** [comment]
@lissaahmad , any time!
