### ISSUE TITLE
Page builder content not showing in the front end

### ISSUE THREAD

**Issue by JennyBrakel** [ThemeFuse/Unyson#1596]
Hello,
I installed the Unyson plugin, but the content I create with the vsiual page builder is not shown in the front end - there is still just an empty, white page.
I would be really glad if you could help me!
Thanks a lot in advance,
Jenny

**Comment by moldcraft** [comment]
Hello,

Which theme are you using?

**Comment by moldcraft** [comment]
If your theme is using `get_post()` for content display, then it must switch to [this function](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.3/helpers.php#L41) or

```php
$posts = get_posts(array(
    'include' => $POST_ID,
    'post_type' => 'any',
    'numberposts' => 1,
    'suppress_filters' => false,
));

echo apply_filters('the_content', $posts[0]->post_content);
```

**Comment by JennyBrakel** [comment]
Hello and thanks a lot for your message first! :-)

Can you tell me in which file I have to search for the content display?

Is it functions.php ? In the „functions.php“ file of my theme I can´t find anything about the content display..

I am using the theme Zeitreise from Elmastudio.

Thanks a lot again - I really appreciate your support!

Greetings,
Jenny





> Am 27.05.2016 um 10:30 schrieb moldcraft <notifications@github.com>:
> 
> If your theme is using get_post() for content display, then it must switch to this function <https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.3/helpers.php#L41> or
> 
> $posts = get_posts(array(
>     'include' => $POST_ID,
>     'post_type' => 'any',
>     'numberposts' => 1,
>     'suppress_filters' => false,
> ));
> 
> echo apply_filters('the_content', $posts[0]->post_content);
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ThemeFuse/Unyson/issues/1596#issuecomment-222090600>, or mute the thread <https://github.com/notifications/unsubscribe/AScix1Av5B-PIE8kXiFF1wuRxVEMlBlkks5qFquvgaJpZM4Inoky>.
> 

___________________

Jenny Brakel
Bernadottestraße 77
22605 Hamburg

fon. 040 | 38904920
jennybrakel@t-online.de <mailto:jennybrakel@t-online.de>

**Comment by moldcraft** [comment]
Search in `single.php` or `page.php`.

Please give a link to this issue to theme author.

**Comment by JennyBrakel** [comment]
I will! Thanks a lot!

> Am 28.05.2016 um 11:22 schrieb moldcraft <notifications@github.com>:
> 
> Search in single.php or page.php.
> 
> Please give a link to this issue to theme author.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ThemeFuse/Unyson/issues/1596#issuecomment-222299106>, or mute the thread <https://github.com/notifications/unsubscribe/AScix-D5ct47ze50eLHDTPU7XR2kuJY6ks5qGAlagaJpZM4Inoky>.
> 

___________________

Jenny Brakel
Bernadottestraße 77
22605 Hamburg

fon. 040 | 38904920
jennybrakel@t-online.de <mailto:jennybrakel@t-online.de>
