### ISSUE TITLE
can I use tabs for group options ???

### ISSUE THREAD

**Issue by TruongTuyen** [ThemeFuse/Unyson#1597]
Hi,
When open a shortcode options I want some options are grouped together, 
Please tell me Can I use tabs for group options together?

**Comment by danyj** [comment]
Yes you can , 

http://manual.unyson.io/en/latest/options/introduction.html#containers


just like anywhere where unyson is used, 


	'somegroup' => array(
		'title'   => __( 'Options set', 'fw' ),
		'type'    => 'tab',
		'options' => array(
			// options here
		),
	),
