### ISSUE TITLE
map type on backend

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#1599]
When I use the map option, either as a shortcode or as a post option (metabox), the map type doesnt seems to be "roadmap" since there are no city names, nor streets. Is this an issue to solved or it is supposed to work like this?

**Comment by moldcraft** [comment]
Hello,

I am not the author of `map` option-type and not a google maps expert. The initialization of map is done in [this script](https://github.com/ThemeFuse/Unyson/blob/v2.5.5/framework/includes/option-types/map/static/js/scripts.js), you can inspect it, find the problem and create a pull request.

**Comment by mbtocalli** [comment]
Thanks and I'm sorry having posted this issue here.

**Comment by moldcraft** [comment]
You are welcome

Thank you for using Unyson
