### ISSUE TITLE
Can't add custom short code to Page Builder

### ISSUE THREAD

**Issue by markcofano** [ThemeFuse/Unyson#1600]
Hello,

I am attempting to add a new short cut in Page Builder.  I'm following the directions to add a new shortcode found on unyson.io ("Cookbook Example.")

  http://manual.unyson.io/en/1.x/extension/shortcodes/index.html#cookbook

I've created the appropriate folders and files per the documentation:

scratch-parent/
└─framework-customizations/
 └─theme/
  └─shortcodes/
   └─hr/
      config.php
     └─views/
       view.php

Using the 1.07 scratch parent theme and latest version of Unyson.

The Short Code does not appear in the builder. Please let me know what I am missing if anything.

I've tried with with Scratch-Parent, Scratch-Child, and Core-Parent.  Doesn't appear to work anywhere.  Really need help with this soon.  Thanks!

Mark

**Comment by dinhtungdu** [comment]
If you're using latest version of Unyson, you should go with latest manual ;)

http://manual.unyson.io/en/latest/extension/shortcodes/index.html#cookbook

The shortcode must be in `framework-customizations/extensions/shortcodes/shortcodes/`

**Comment by markcofano** [comment]
Hey Dinhtungdu

I figured it was probably something like a path issue.  Was really
frustrating banging my head.

I will try in the morning.  Thanks!

Best,

Mark Cofano
949-558-2222
