### ISSUE TITLE
Available Extensions Can't Move

### ISSUE THREAD

**Issue by somnath14** [ThemeFuse/Unyson#1602]
Hello Madam/Sir,

I have installed unyson plugin ver 2.5.5 successfully but unfortunately I can't download the Available Extensions and It's giving me an error. Please find the attachment. Also, I am using this plugin over Localhost. Hope you will solve this issue as soon as possible.

Regards,
Som
![unyson](https://cloud.githubusercontent.com/assets/19607437/15605492/f11a7ee6-2423-11e6-9c5d-2c37be16ee7a.png)

**Comment by danyj** [comment]
check folder permissions ( on Win should always be 777 ) and make sure the folder is not used by another Windows service. I am developing on wamp Win 10 pro  and have never seen this issue.

**Comment by somnath14** [comment]
Hey there,
Thanks for your all help.
But it's giving me  Warning: copy(): The first argument to copy() function cannot be a directory in C:\wamp\www\flintoz\wp-admin\includes\class-wp-filesystem-direct.php on line 257

**Comment by moldcraft** [comment]
Maybe you a file open in editor in that directory so it is blocked. Please make sure all other programs are closed (event in system tray)

**Comment by somnath14** [comment]
I am having issues with Page Builder, Sliders and SEO. Other Extensions are working like a charm.
Not sure, It's Permission issue. Because I can download other Extensions.

**Comment by moldcraft** [comment]
Maybe you reach windows path length limit. Try to move your installation from `C:/wamp/www/flintoz` to ``C:/w/w/f``

**Comment by somnath14** [comment]
I have fixed the issue. Actually the path was going wrong.
What was the wrong path : http://abc
What is the correct path now : http://localhost/abc

Thanks for your all valuable help :)

**Comment by sunnyville** [comment]
Hi, 

Could you please explain a bit more about how you were able to fix the issue? I'm having the same issue as you were having and have tried all the other suggestions in this thread. 

Thanks.

**Comment by somnath14** [comment]
Hello Sunny,
It's not a correct way but you can use for localhost.
Please follow the steps. Go to -> wamp->www->index.php and find out line number 403 and replace the following code.
if (is_dir($file) && !in_array($file,$projectsListIgnore))
	{
		$projectContents .= '<li><a href="';
		if($suppress_localhost)
			$projectContents .= 'http://localhost/'.$file.$UrlPort.'/"';
		else
			$projectContents .= 'http://localhost'.$UrlPort.'/'.$file.'/"';
		$projectContents .= '>'.$file.'</a></li>';
	}
 I am not sure. The line will be exact same as I am using wampserver 3.0.4_x86. But you can find out through the ctr+f key. That's it. Hope this will work for you :)
