### ISSUE TITLE
wp-editor option in addable box

### ISSUE THREAD

**Issue by morozovigor** [ThemeFuse/Unyson#1604]
Hello everyone. I had a bug when using wp-editor option in addable box. First item in addable box works correctly, but when i add new items, wp-editor is broken in them. There are screenshots

http://prntscr.com/b94kkc
http://prntscr.com/b94l1h

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1466#issuecomment-211336425

**Comment by moldcraft** [comment]
In next Unyson release will be possible to use wp-editor in addable-box, [test it](https://github.com/ThemeFuse/Unyson-Extensions-Approval), thank [him](https://github.com/andreiglingeanu)

**Comment by duongancol** [comment]
Hi! In Unyson 2.5.7, I tested wp-editor in addable-box but it didn't work, still lag. See [here](http://take.ms/UkJWn)

**Comment by andreiglingeanu** [comment]
@duongancol Are you sure that Unyson's wp-editor is the cause of the lag?

**Comment by duongancol** [comment]
@andreiglingeanu : sorry I don't know why but I couldn't reproduce this bug now.

**Comment by andreiglingeanu** [comment]
@duongancol Strange

**Comment by andreiglingeanu** [comment]
@duongancol Could you test it with Scratch Theme and give us some reproduction steps?

**Comment by duongancol** [comment]
Yes, please try to use both icon and wp-editor in addable-box

**Comment by andreiglingeanu** [comment]
@duongancol Just tried and works [fine](https://i.imgur.com/18tvsRN.png).

**Comment by duongancol** [comment]
I tested in Scratch theme and it's the same.
[Here](http://take.ms/6wIyD) is the video with icon & wp-editor
[Here](http://take.ms/aeLuk) is the video with only wp-editor
You could see that the second loads better

**Comment by andreiglingeanu** [comment]
@duongancol Please try to use `icon-v2` in place of the other `icon` and how it performs. However, please be patient, this `icon-v2` thing is still in beta phase.

**Comment by duongancol** [comment]
@andreiglingeanu Is this included in Unyson 2.5.7?

**Comment by andreiglingeanu** [comment]
@duongancol Nope. Use master version.

**Comment by duongancol** [comment]
Thank @andreiglingeanu , I'll test later, Could you reproduce my problem?

**Comment by andreiglingeanu** [comment]
@duongancol I'll bet the initialisation process for both the `wp-editor` and `icon` takes long. Each addable have to compute it's own icons list and each one have to initialize it's own `wp-editor` instance. There's really nothing I can help with. Maybe `icon-v2` will solve your problems, it separates icon preview from the the icons list by including icons list into it's own modal.
