### ISSUE TITLE
Does Unyson support nested shortcodes???

### ISSUE THREAD

**Issue by TruongTuyen** [ThemeFuse/Unyson#1606]
Good morning.

Please tell me: does unyson framework support nested shortcodes??? Ex: I have a shortcode "Banner carousel" to config carousel, I want shortcode "Child Banner" is child of shortcode "Banner Carousel", and when I click on "Banner Carousel"  then "Child Banner" will be show.

Thanks.

**Comment by dinhtungdu** [comment]
AFAIK is no. But shortcode in Unyson support options type.

For your carousel, You can put config and "Child Banner" in 1 shortcode. Unyson support addable option for adding child banner. Good luck!

**Comment by TruongTuyen** [comment]
Can you tell me how to do this??? 
Thanks

**Comment by dinhtungdu** [comment]
[Documentation](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content) is your friend ;). It's very easy to get started.

**Comment by TruongTuyen** [comment]
I was searching the documentation before I placed this question, but I did not find the solution for my problem. Can you give me an example about "support addable option"?
Thanks

**Comment by dinhtungdu** [comment]
Here is the addable part in docs: http://manual.unyson.io/en/latest/options/built-in-option-types.html#addable-box

**Comment by TruongTuyen** [comment]
Thank for your help!!!

**Comment by dinhtungdu** [comment]
You're welcome!
