### ISSUE TITLE
Issue between Page builder and CM Maps Routes Manager plugin

### ISSUE THREAD

**Issue by bzoum** [ThemeFuse/Unyson#1607]
Hello,

There is an incompatibility between the page builder and CM Maps Routes Manager plugin.

Indeed, when the page builder is activated and try to display a page created by the plugin, I got this message :

Catchable fatal error: Argument 1 passed to FW_Extension_Page_Builder::get_post_content_shortcodes() must be an instance of WP_Post, instance of stdClass given, called in /home/xxxx.com/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/class-fw-extension-page-builder.php on line 339 and defined in/home/xxxx.com/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/class-fw-extension-page-builder.php on line 277

When the page builder is deactivated, everything works fine.
What can I do ?

Best,
Bzoum

**Comment by danyj** [comment]
do you se this bug when the CM plugin is disabled?

**Comment by bzoum** [comment]
When the page builder is disabled, the plugin works and the page is displayed.
When the page builder is enabled, the plugin does not work and I get the error.
When the page builder is enabled and the plugin disabled, there is not problem because there is no plugin :)

**Comment by moldcraft** [comment]
Please test with [this fix](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/8baf46cd801f2b48c214a2f7da6fe5255b9167f8), it will be included in next release.

**Comment by bzoum** [comment]
OK Thank you.
So the error incompatibility came from the framework and not the plugin ?

**Comment by moldcraft** [comment]
Yes
