### ISSUE TITLE
fw_ext_sidebars_get_current_position result is different

### ISSUE THREAD

**Issue by ThemePaper** [ThemeFuse/Unyson#1608]
I have sidebar-left.php and sidebar-right.php files
on Appearance > widget, I set it to full with spesific page.

But result fw_ext_sidebars_get_current_position() on echo is
sidebar-left.php -> full (Right)
sidebar-right.php -> left_right (Wrong)

Can you help? what is the problem?

Thank you

**Comment by moldcraft** [comment]
Hello,

Please give the exact steps and code how to reproduce this problem.

P.S. Sorry, I am not expert in Sidebar extension.

**Comment by ThemePaper** [comment]
Hello, sorry..

fixes is add wp_reset_postdata(); after endwhile
![uny2](https://cloud.githubusercontent.com/assets/19613295/15652859/570959de-26b3-11e6-8965-d492c4ac33ad.jpg)

I'm never use wp reset postdata before for default loop..

Thanks
