### ISSUE TITLE
Import XML Wordpress tool delete Page Builder content

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#161]
Hello,
When I pack the demo content in a .xml file through Wordpress export tool. When I import it in another website, the frontend view is there where as once I click on edit (I switch in the backend). Content in the pagebuilder has disappeared...Any idea ?

**Comment by 2Fwebd** [comment]
No idea ? Maybe the is another way to proceed, I tried the backup extension but in my mind it is not easy for buyer to load the demo content. Because if I understand the thing, user have to install the demo content through a FTP client. Which doesn't seems that user friendly compared to import tool in WP.

**Comment by rockalife** [comment]
Hi @2Fwebd, 

I'll look into the problem today and reply later.

**Comment by 2Fwebd** [comment]
Thank you, it is the last step before releasing my theme!!:)

**Comment by rockalife** [comment]
Hello @2Fwebd,

I have tested exporting with the standard WordPress export tool and importing with the `WordPress importer` plugin with simple pages and portfolio post types. It works fine, the only thing to watch out is to not forget to activate the post types that the page builder supports in the new site.

![settings page](http://static.md/a843d238f4608f67d353bc8da8f71724.png)

![post types that support builder](http://static.md/5bea8a68365c60840667300e4e273eca.png)

**Comment by 2Fwebd** [comment]
Hello @rockalife ! Thank you for the reply, can you edit the pages once imported through Wordpress with the page builder ? Because my issue is not to import them but to edit them. Because I see the layout but when I click on "edit" I get a blank page builder in WP.

**Comment by rockalife** [comment]
Yes @2Fwebd, the imported pages were opened correctly, with the page builder active and the shortcodes arranged in the same way as when they were exported.

**Comment by rockalife** [comment]
However some of the shortcodes options, those that contained urls were not replaced with the new domain. Because of the limitations of the standard export and import tools we have built the auto install extension which was meant to address these issues.

**Comment by 2Fwebd** [comment]
Hello,
Thank you for the replies. I checked again and you are right it works well. Nevertheless do you think it could have been caused by the fact that I saved all the page builder layouts in some "templates" ? Maybe the "templates" in the page builder do not support exportation through Wordpress export tool.

**Comment by rockalife** [comment]
If by templates you mean this ones:

![page builder templates](http://static.md/083b0247fd876160ee2172a023400e35.png)

then you are right, these templates are saved in the `wp_options` table, which is not exported via the WordPress exporter (as far as I know and have tested).

**Comment by 2Fwebd** [comment]
Ok thank you for the informations :) I was talking about that.

**Comment by saulovenancio** [comment]
in my case, all the shortcodes are being imported as 'Text BLock', it renders well but removes the click to change the configuration.
