### ISSUE TITLE
Table type switch not setting the data back

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1610]
To test , create pricing table , similar to this 

![screenshot1](https://cloud.githubusercontent.com/assets/2340172/15635344/d3e0511a-25dc-11e6-83cb-3eddedf52760.png)

save it , save page , click again on table shortcode , now try switching the table type and it will not bring the saved price and button back  

![screenshot2](https://cloud.githubusercontent.com/assets/2340172/15635363/2a41b65c-25dd-11e6-831e-db19dfac9013.png)

**Comment by danyj** [comment]
@moldcraft  did u guys miss this one?

**Comment by moldcraft** [comment]
I never touched the table shortcode (it is not my creation)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/pull/57
