### ISSUE TITLE
Missing 'Publish/Update' button when using 'remove_post_type_support( 'page', 'editor' )' action

### ISSUE THREAD

**Issue by blackyangell** [ThemeFuse/Unyson#1612]
I use "add_action( 'do_meta_boxes', 'fw_hide_admin_metaboxes' )" to hide some metaboxes on some admin pages. 

There is such code there:
remove_post_type_support( 'page', 'editor' );

This causes that 'Publish/Update' button dissapears together with the visual editor. 
Also I get this JS error:
"Uncaught TypeError: Cannot set property 'setup' of undefined
editor_integration.js?ver=1.5.4:209 "

Earlier, before last framework update, button was at it's place and worked.

Can you, please, tell me, if there is a framework error, or it's my fault?

**Comment by moldcraft** [comment]
The Publish button is hidden then shown after PageBuilder is fully initialized https://github.com/ThemeFuse/Unyson/issues/1542#issuecomment-218094104

Looks like you have PageBuilder enabled for that post type but you remove editor with `remove_post_type_support( 'page', 'editor' );`, the required scripts are enqueued but the elements are not in DOM, that's why you get js errors.

I will try to reproduce it and provide a fix.

**Comment by moldcraft** [comment]
> I use `add_action( 'do_meta_boxes', 'fw_hide_admin_metaboxes' )` to hide some metaboxes on some admin pages. There is such code there: `remove_post_type_support( 'page', 'editor' );`

[`remove post type support()`](https://codex.wordpress.org/Function_Reference/remove_post_type_support) docs says:

> Typically remove_post_type_support() should be attached to the 'init' action hook.

**Comment by blackyangell** [comment]
So, can you please provide some solution for this problem? Or I need to wait for the next update?
Thank you.

**Comment by moldcraft** [comment]
The solution is this https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/3cfdd56fd798533a74b0d4a509e0a365372eb65e

It will be included in the next update

**Comment by blackyangell** [comment]
I tried this fix, but the problem is still there...

I can't set 'add_action' on 'init' event - I get errors. There is my custom functon:


`/**
 * Hide particular metaboxes from admin pages depending on choosen page template.
 */
if ( ! function_exists( 'fw_hide_admin_metaboxes' ) ) {

	function fw_hide_admin_metaboxes() {
		if ( get_current_screen()->post_type != 'page' ) {
			return;
		}

		switch ( get_page_template_slug() ) {

			case 'blog-archive.php':
				remove_post_type_support( 'page', 'editor' );
				remove_meta_box( 'fw-options-box-page-builder-box'   , 'page', 'normal' );
				remove_meta_box( 'fw-options-box-page_settings'      , 'page', 'normal' );
				remove_meta_box( 'fw-options-box-portfolio_settings' , 'page', 'normal' );
				break;

			case 'archive-portfolio.php':
				remove_post_type_support( 'page', 'editor' );
				remove_meta_box( 'fw-options-box-page-builder-box' , 'page', 'normal' );
				remove_meta_box( 'fw-options-box-page_settings'    , 'page', 'normal' );
				remove_meta_box( 'fw-options-box-blog_settings'    , 'page', 'normal' );
				break;

			default:
				remove_meta_box( 'fw-options-box-blog_settings' 	 , 'page', 'normal' );
				remove_meta_box( 'fw-options-box-portfolio_settings' , 'page', 'normal' );
				break;
		}

	}

}

add_action( 'do_meta_boxes', 'fw_hide_admin_metaboxes' );`

**Comment by moldcraft** [comment]
You need to separate your code in 2 actions.

1. On `do_meta_boxes` do `remove_meta_box(...)`
2. On `init` do `remove_post_type_support(...)`

**Comment by blackyangell** [comment]
It causes
**Call to undefined function get_current_screen()**
when I remove_post_type_support on 'init' action

**Comment by moldcraft** [comment]
Remove

```
if ( get_current_screen()->post_type != "page" ) { return; }
```

**Comment by blackyangell** [comment]
No errors, but I get Visual editor :) It's loading... 
I guess I need to find some another solution.
Thank you, don't waste your time any more.

**Comment by moldcraft** [comment]
> but I get Visual editor

I tested with 

```php
add_action('init', function(){
    remove_post_type_support( 'page', 'editor' );
}):
```

and it works (not Visual Editor is displayed)

Do you use the fix? How you test? Show your code please

**Comment by blackyangell** [comment]
My code is:

if ( ! function_exists( 'fw_remove_post_type_support' ) ) {

	function fw_remove_post_type_support() {

		switch ( get_page_template_slug() ) {

			case 'blog-archive.php':
				remove_post_type_support( 'page', 'editor' );
				break;

			case 'archive-portfolio.php':
				remove_post_type_support( 'page', 'editor' );
				break;

			default:
				break;
		}

	}

}

add_action( 'init', 'fw_remove_post_type_support' );



Default WP Visual editor is loading. 
But if we click Visual Page Builder button, just empty space appears, no PageBuilder.

**Comment by moldcraft** [comment]
> `fw_remove_post_type_support()`

http://manual.unyson.io/en/latest/convention/prefixes.html#theme

----

Oh, you need to remove the editor only for specific page templates. It's tricky, I don't know a solution.

**Comment by blackyangell** [comment]
Ok, thank you. 

The solution is ugly and simple :)

case 'blog-archive.php':
				remove_meta_box( 'fw-options-box-page-builder-box'   , 'page', 'normal' );
				remove_meta_box( 'fw-options-box-page_settings'      , 'page', 'normal' );
				remove_meta_box( 'fw-options-box-portfolio_settings' , 'page', 'normal' );
				echo '<style>#postdivrich{display:none!important}</style>';
				break;
