### ISSUE TITLE
SEO extension style issue

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1613]
Hello!

I noticed that SEO extension has a styles problem in WooCommerce Product posts, is it possible to fix that? A screenshot https://yadi.sk/i/UyhaHYtKs7b6w

Thank you

**Comment by moldcraft** [comment]
WooCommerce include their own jquery-ui style which breaks other (including our) styles.

We don't include/overwrite default WP jquery-ui styles.
