### ISSUE TITLE
Thumbnail display addable popup image template

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1614]
In addable popup this code display full size image. Is there any way to display thumbnail only?
`'template'      => '<img src="{{= images.url }}" >'`
![capture3](https://cloud.githubusercontent.com/assets/12174913/15664506/4c142b26-2726-11e6-996e-efac55711002.PNG)
![capturer](https://cloud.githubusercontent.com/assets/12174913/15664507/4c15f686-2726-11e6-9fa2-8fcb58ef941f.PNG)

**Comment by danyj** [comment]
we are still waiting for adequate fix, https://github.com/ThemeFuse/Unyson/issues/923, 
sometimes they appear , other times they dont.

**Comment by moldcraft** [comment]
Maybe `<img src="..." style="max-width:...;max-height:...;" >` ?

**Comment by danyj** [comment]
@moldcraft  bud,   he is asking for thumb, not how to resize the image

**Comment by Ataurr** [comment]
It will be great if we add thumbnail image in title_template shortcode config as well.

We can load the images with max width and height. But if you have lots of images on a page then it will take the time to load the large image in page builder.
