### ISSUE TITLE
Can't set Link on Visual editor - 'wp-editor' option type

### ISSUE THREAD

**Issue by blackyangell** [ThemeFuse/Unyson#1615]
When using Visual Editor in PageBuilder (wp-editor option type) it's impossible to create link - Edit/create link popup doesn't appear. Text become blue and underlined, but no link there.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1478#issuecomment-211271632

**Comment by moldcraft** [comment]
![](https://static.md/9af307123fe1ea7737dade14d641c051.png)

**Comment by andreiglingeanu** [comment]
Can someone confirm that this is not happening anymore after 3d8e53fef649a18f3fe731aaef35f9b2b9cd12e7?
