### ISSUE TITLE
In admin wp 4.5 image not show in sliders with manual uploading

### ISSUE THREAD

**Issue by navinweb** [ThemeFuse/Unyson#1618]
Console give me 

![error](https://cloud.githubusercontent.com/assets/7899637/15701540/7f839b46-27e3-11e6-9cae-036c3a15f8ac.jpg)

![error2](https://cloud.githubusercontent.com/assets/7899637/15701565/a6a71766-27e3-11e6-9710-61bb58fef1c2.jpg)

If need, i can give access to admin panel this site

**Comment by moldcraft** [comment]
Hello,

It works on my side. Try with one of default WP themes (maybe the problem comes from a theme script)
