### ISSUE TITLE
lose all content when Edit and Save - possible conflict with toolset (wp-types.com)

### ISSUE THREAD

**Issue by anniebergeron** [ThemeFuse/Unyson#1619]
hi,
My client using Unyson version 2.5.5 with Toolset Types version 2.0.1 and Toolset Views 2.0 and I think there is a conflict.

When I edit a page and save it, all the content disappears. 

I wondered if we could do something to correct this problem or should I change plugin.

Thanks

**Comment by moldcraft** [comment]
Hello @anniebergeron 

I installed "Toolset Types" but I can't find the "Toolset Views" plugin

![](https://static.md/939b46e5fe05049af280398d7f68d01a.png)

**Comment by anniebergeron** [comment]
Hello @moldcraft 
Toolset views is a premium plugin https://wp-types.com/home/views-create-elegant-displays-for-your-content/
Maybe I can send you a copy (in private) for testing?

Thanks

**Comment by moldcraft** [comment]
`moldcraft[at]email.com`
