### ISSUE TITLE
Removing all builder shortcodes is not taking effect

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#162]
This one is bit hard to explain bare with me 

Add 3 icon boxes trough page builder hit update 
Now remove one hit update , works fine 
Now remove remaining 2 , hit update and they wont be removed. 

![capture](https://cloud.githubusercontent.com/assets/2340172/5693032/5a4d6076-990c-11e4-969d-417a0cde5c49.JPG)

![capture](https://cloud.githubusercontent.com/assets/2340172/5693033/66bc43e0-990c-11e4-840c-86e0dc209e8b.JPG)

**Comment by moldcraft** [comment]
I understand that this may be urgent for you, but most of the questions will have a response only on Monday. Sorry

**Comment by danyj** [comment]
No urge. Take your time.

**Comment by levan1993** [comment]
Hi, I've found one issue.
When using history buttons and if you deleted all shortcodes from root last undo remains, you can test it.

**Comment by llemurya** [comment]
@levan1993  can you make a video in way to reproduce this bug with history buttons please.

**Comment by moldcraft** [comment]
Please don't mix issues. I created a new issue, move the discussion there https://github.com/ThemeFuse/Unyson/issues/163
