### ISSUE TITLE
wp-editor wpautop false does not work 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1621]
@moldcraft   this is still not fixed https://github.com/ThemeFuse/Unyson/issues/713 , 

```
wpautop => false 
```

does not strip the p tag 

http://screencast.com/t/1TKXxaFO7o

```
        'heading' => array(
            'type' => 'wp-editor',
            'tinymce' => true,
            'size' => 'large',
            'reinit' => true,
            'wpautop' => false,
            'editor_height' => 100,
            'editor_type' => 'html',
            'value' => 'This is dummy heading text',
            'label' => __('Heading', 'fw'),
            'desc' => __('Add heading text', 'fw')
        ),
```

and is editor_type removed now ?

https://github.com/ThemeFuse/Unyson/issues/942

**Comment by moldcraft** [comment]
> is editor_type removed now ?

Yes. Do you need it?

**Comment by danyj** [comment]
>Yes. Do you need it?
is there adjustmant for this than https://github.com/ThemeFuse/Unyson/issues/942
or ?

**Comment by danyj** [comment]
@moldcraft   this is still going on , even if I do 

   remove_filter( 'the_content', 'wpautop' );

it still prints the p

**Comment by danyj** [comment]
and switch between Visual and text is buggy again , not switching

**Comment by moldcraft** [comment]
@danyj Please give your options array and where to place it (in Theme Settings or in some shortcode options)

**Comment by moldcraft** [comment]
I added in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/accordion/options.php`

```php
$options = array(
	'test_1' => array(
		'type' => 'wp-editor',
		'wpautop' => false,
		'label' => __('autop false', 'fw'),
	),
	'test_2' => array(
		'type' => 'wp-editor',
		'wpautop' => true,
		'label' => __('autop true', 'fw'),
	),
	// ...
);
```

added in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/accordion/views/view.php`

```php
fw_print($atts['test_1'], $atts['test_2']);
```

and in frontend it shows

![1476276160999](https://cloud.githubusercontent.com/assets/1475489/19310396/87c62928-9092-11e6-958b-3c32ff318bb4.jpg)

It doesn't matter if wp-editor is in Visual or Text mode.

**Comment by danyj** [comment]
here it is 

			'heading' => array(
				'type' => 'wp-editor',
				'tinymce' => true,
				'size' => 'large',
				'reinit' => true,
				'wpautop' => false,
				'editor_height' => 100,
				'editor_type' => 'html',
				'value' => 'This is dummy heading text',
				'label' => __('Heading', 'fw'),
				'desc' => __('Add heading text', 'fw')
			),

**Comment by moldcraft** [comment]
It shows this

![1476286225654](https://cloud.githubusercontent.com/assets/1475489/19316438/1b12df70-90aa-11e6-8bdb-d2b680703dee.jpg)

with `'wpautop' => true` it shows

![1476286267801](https://cloud.githubusercontent.com/assets/1475489/19316451/25ad1fea-90aa-11e6-99fc-6295554a967c.jpg)

Everything is fine.

**Comment by danyj** [comment]
ok , il look on my end than , thnx for looking in to it.

**Comment by danyj** [comment]
we did not test this with second and third save.  Things change on each save.
