### ISSUE TITLE
[ question] create 'wrap' element. same as container row col

### ISSUE THREAD

**Issue by prostoVladislav** [ThemeFuse/Unyson#1622]
hello,
how to create an Element . in which you can put one of elements . Something like a row or a column container .
in view we point
<Php echo do_shortcode ($ content)?; ? >
but how to get the builder to expand . in the admin panel.

**Comment by danyj** [comment]
@prostoVladislav  +100 , 
I was about to do same thing and yes we can copy section or column 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/master/shortcodes/section

but this is maintanance nightmare , we have to prefix,suffix everything on our own and any slight builder change can mess things up , 

ctrl+f section here for example 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/includes/page-builder-section-item/static/js/scripts.js
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/includes/template-component/scripts.js

@moldcraft  @andreiglingeanu  is there a faster way to have a wrapper shortcode without copying complete class and  mess with builder JS  to the above extent?

**Comment by moldcraft** [comment]
There is no easy way.

**Comment by andreiglingeanu** [comment]
@danyj Yeah, you basically need to create one more **Build Item Type**, just like shortcode `section` [defines](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php).
