### ISSUE TITLE
How to create demo content?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1623]
Am I missing something here , 
http://prntscr.com/bd0ypt

there is no   Tools > Demo Content Install 

as advised here http://manual.unyson.io/en/latest/extension/backups/index.html#create-demos

**Comment by duongancol** [comment]
the demo content folder is in your theme or your server?

**Comment by danyj** [comment]
@duongancol  I am not installing , creating

according to docs http://prntscr.com/bd12bi it should be there

**Comment by danyj** [comment]
ok I see , that should be bit more prominent and is very easy to miss, http://prntscr.com/bd13bk
and this button or somewhere here http://prntscr.com/bd13kb, it should mention demo
