### ISSUE TITLE
Demo data installer time out error

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1624]
Hello!

I'm still getting too many requests from many users that they have problem installing demo data. They use different hostings, e.g. GoDaddy. Changing configuration to following did not help

max_execution_time 360
memory_limit 128M
post_max_size 32M
upload_max_filesize 32M
max_input_vars 5000

is it possible to add some checking minimum host configuration before demo data installation and warn user if it is necessary please?

**Comment by moldcraft** [comment]
Hello,

On which step it happens?

**Comment by WPJobs** [comment]
Thank you for a quick reply!

For some users this happened during restoring images sizes (time out error), and some users can't unzip a file with demo content (zip error)

**Comment by WPJobs** [comment]
one more thing, i the latest ticket i've got: time out hapened on "We are currently installing your content. Database restore" step. As you can see, the steps are different from host to host, that's why i ask you to add some configuration checking please :)

**Comment by joman1717** [comment]
I am getting the same error, it times out during restoring images sizes

**Comment by moldcraft** [comment]
> is it possible to add some checking minimum host configuration before demo data installation and warn user if it is necessary please?

I don't know which are the minimum host configurations. We have a few very slow notebooks in our office and demo install works very slow but it finishes successfully on them.

The biggest problem with hosting is that they don't provide a good error log. At the moment I have details for a hosting where Image Sizes Restore doesn't work but I have no idea why. I contacted them to provide me full error log but they said to activate WordPress debug.log https://codex.wordpress.org/Debugging_in_WordPress#WP_DEBUG_LOG

So it is very tricky.

**Comment by WPJobs** [comment]
you're right, the problem is that even activating wordpress debug logging will not answer why this happened. Most answers from the hosting providers are "enable debug log" or similar, they are not interested to help unfortunately. I had contact with some clients who inadequately react for messages like "this is hosting problem", it all gets very complicated and it seems there is no way to resolve this problem. Someone can give advice? :)

**Comment by Ataurr** [comment]
New issue i have found one of our buyer. 
"`Failed to create tmp table _fwbk_ks_commentmeta`"
..and no demo content is installed.

**Comment by duongancol** [comment]
What is your Collation of your database?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/19

**Comment by moldcraft** [comment]
I just made [this fix](https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/f27aaebb755dfb788ef303578a78bc825b34336b), I hope it will help in some case.

Also I think that some hosts have anti-flood/anti-ddos security features which maybe blocks the chained requests made by the site to itself while running a backup or demo install process.

All these are assumptions, I have no real info.

**Comment by WPJobs** [comment]
Thank you so much, Moldcraft!

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/d0520977c5eb3f9934b90b118ec392829f2c6568
