### ISSUE TITLE
fw is not defined

### ISSUE THREAD

**Issue by AceoK** [ThemeFuse/Unyson#1625]
Hi, I've got error in console when opened theme settings: "Uncaught ReferenceError: fw is not defined"
Looks like it goes from backend-settings-form.php in Unyson plugin. 

In theme framework-customizations/theme/options/settings.php I wrote 
`if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}` 
and I don't know how to fix issue. Thanks

**Comment by moldcraft** [comment]
Hello,

Please give a screenshot of your error, like this

![](https://static.md/efd6f66d26553f9474653d2d4c53bffd.png)

**Comment by AceoK** [comment]
![image](https://cloud.githubusercontent.com/assets/2799132/15850792/94cd7684-2ca2-11e6-9511-d26dca4508f7.png)
also
![image](https://cloud.githubusercontent.com/assets/2799132/15850842/d26b0c0e-2ca2-11e6-8f6e-3e93d4d6326c.png)

**Comment by moldcraft** [comment]
On my side `fw.js` is enqueued on [this line](https://static.md/6b95a65306ddef7ee0fd33af8b9e2117.png) in `<head>...</head>` and that script is [in footer](https://static.md/8759161bf824a78a7d1aadbb1e40b122.png).

So on your page `fw.js` is not enqueued at all?

**Comment by AceoK** [comment]
jw.js enqueued in footer, and looks like in file unyson/framework/core/components/backend.php:343
```php
wp_register_script(
	'fw',
	fw_get_framework_directory_uri( '/static/js/fw.js' ),
	array( 'jquery', 'fw-events', 'backbone', 'qtip' ),
	fw()->manifest->get_version(),
	true
);
```
it registered to be in footer
my version of Unyson is 2.5.5

**Comment by AceoK** [comment]
looks like if comment 349 string with argument $in_footer
```php
 true
```
then issue is gone, but I can't hardcode that in your plugin
