### ISSUE TITLE
Theme Settings page title not changing

### ISSUE THREAD

**Issue by zohaib87** [ThemeFuse/Unyson#1626]
Hi i am using following function to change the theme settings menu and page title but the page title is not changing. any one can tell me what i am doing wrong? http://prntscr.com/bdhocg

```php
if (!function_exists('_action_theme_custom_framework_settings_menu')) {

    function _action_theme_custom_framework_settings_menu($data) {
        add_submenu_page(
			'themes.php',
            'Admin Options',
            'Admin Options',
            $data['capability'],
            $data['slug'],
            $data['content_callback']
        );
    }

}
add_action('fw_backend_add_custom_settings_menu', '_action_theme_custom_framework_settings_menu');
```

Thank you!

**Comment by moldcraft** [comment]
Page title is [hardcoded](https://github.com/ThemeFuse/Unyson/blob/v2.5.6/framework/core/components/backend.php#L651)

I will add a filter.

**Comment by moldcraft** [comment]
In the next update the page title will be extracted from menu title https://github.com/ThemeFuse/Unyson/commit/23fb1d261d9229efdfdac8f9545c3f1a0c5cee21
