### ISSUE TITLE
Builder: History buttons

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#163]
@levan1993 When using history buttons and if you deleted all shortcodes from root last undo remains, you can test it.

**Comment by moldcraft** [comment]
@llemurya

> @levan1993, can you make a video in way to reproduce this bug with history buttons please.

**Comment by levan1993** [comment]
@moldcraft 

the following code works in this situation.

elements.$undo.on('click', function (e) {

					e.preventDefault();

					if ($(this).hasClass('disabled')) {
						return;
					}
					utils.enableUndo();
					utils.enableRedo();

					saveStateFlag = false;

					var undoSnapshot = history.undo();


					if (undoSnapshot !== undefined) {
					    undoSnapshot = JSON.parse(undoSnapshot); 	
					    builder.rootItems.reset(undoSnapshot);
					    
					    if ( undoSnapshot.length === 0 ) {
					       builder.$input.val('[]'); 
					   }
					} else {
					    utils.disableUndo();
					}
				});

**Comment by llemurya** [comment]
Hi @levan1993,

I don't quite understand what should I do to reproduce your issue. Could you make a screencast or at least provide a clear set of instruction for me to follow, something like:

1. Add button shortcode
2. Add testimonials shortcode
3. Delete the button shortcode
4. Press the undo button
.....

**Comment by levan1993** [comment]
@llemurya 

1. create new page.
2. switch to page builder.
3. add some shortcodes.
4. press the undo button.

when you delete all shortcodes by undoing changes you'll notice that last undo remains,
so page builder json will contain one shortcode.

here is screenshot
![capture](https://cloud.githubusercontent.com/assets/7342339/5769727/492e4eec-9cd4-11e4-954e-ef90395794c8.PNG)

**Comment by llemurya** [comment]
Hi @levan1993 ,yes I can reproduce it, in next hours this bug will be fixed.

**Comment by llemurya** [comment]
I fixed this issue, in next Builder Extension update, it will be available
