### ISSUE TITLE
Filter for not showing shortcode in text mode

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1630]
I do not want to show shortcode in text mode. Any filter for that?
![capture](https://cloud.githubusercontent.com/assets/12174913/15896447/3a0103e0-2db2-11e6-9c50-7311ccbf5272.PNG)

**Comment by danyj** [comment]
disable builder in  blog 
http://prntscr.com/bdvfdb
http://prntscr.com/bdvf4f

**Comment by ashraf92** [comment]
I know that. I do not want to show shortcode in text mode (red circled mark) .

**Comment by moldcraft** [comment]
Hello,

Try

```php
add_action('fw_init', '_action_theme_disable_fw_shortcodes_button');
function _action_theme_disable_fw_shortcodes_button() {
    remove_filter(
        'mce_buttons', 
        array(fw_ext('editor-shortcodes'), '_filter_admin_register_button_menu')
    );
}
```
