### ISSUE TITLE
Page Builder Inconsistent Render (Left vs. Right)

### ISSUE THREAD

**Issue by markcofano** [ThemeFuse/Unyson#1631]
Hello,

I have built a custom shortcode called Rotator.  Rotator has been added to a custom tab in Visual Page Builder.  The purpose of Rotator is to get content from a custom CMS and return it to the page with different content being returned each time (hence the name "rotator").  Rotator can return either text or image(s).

I have constructed a simple page layout using Visual Page Builder

1 Section
2 Columns within the section (1/2 each)

In one column I have included a standard Visual Page Builder Element (Text Block).  In the other column I have included the Rotator.  

For the purposes of this example: The text in the standard VPB Text block is "abc123" and the text returned by the shortcode = "xyz456"

If Rotator returns text only ("abc123"), it does not matter whether Rotator is included in the left or right-hand column.  The page displays as expected below

abc123                            xyz456

or 

xyz456                            abc123

The problem (inconsistent page render ) occurs when Rotator returns an image instead of text (<img src="url" />).

If Rotator is in the left hand column and the VPB Text Block is in the right hand column, the page displays as expected:

[IMAGE]                         abc123

However, if the VPB Text Block is in the left hand column and Rotator is in the right hand column, the page does not render properly.  THE IMAGE ALWAYS WRAPS TO THE NEXT ROW.

abc123
[IMAGE]

Perhaps there is some class that must be assigned to images to cause them to display properly?  I have played around with this quite a bit putting some inline CSS in the image tag (align="right") or enclosing the image in a div and floating the div.  Nothing seems to work.  Please advise, thank you.

**Comment by danyj** [comment]
redo your images please

**Comment by markcofano** [comment]
What does that mean?

**Comment by markcofano** [comment]
I don't understand what you mean by "redo".

**Comment by danyj** [comment]
we cant see your images

**Comment by markcofano** [comment]
Here is the page with the undesired outcome.  The image is below the text and should be to the right.

http://alvakapartner.twist.cloud/wordpress/

**Comment by markcofano** [comment]
Here is what VPB looks like:
![visual-page-builder](https://cloud.githubusercontent.com/assets/13750313/15935762/51b4a44a-2e1d-11e6-80cb-75b594f71755.png)

**Comment by markcofano** [comment]
Dan,

I posted links and a picture of Visual Page Builder.

Mark

**Comment by danyj** [comment]
this seems like theme related issue not framework ,  I think you better off getting support from themefuse 
http://support.themefuse.com/hc/en-us/requests/new

**Comment by markcofano** [comment]
This issue is still open for me.   Because Dan says it is a theme problem and not a framework problem, I have added installed the Scratch theme and have the exact same problem.  Who is responsible for helping me?  Unyson or Themefuse?  Really need some help please.

**Comment by danyj** [comment]
> Because Dan says 
bud,   I said "seems" like theme issue , and I am user just like you are so it was just my good will to look at your issue. Wont do it again.

**Comment by markcofano** [comment]
Dan,

You comment on a lot of the issues, so I assumed that you are in a position
of authority with respect to Unyson / Visual Page Builder.  My mistake.

Since I have posted this problem, no one else has responded.  I am cc'ing
Moldcraft in the hopes that he or someone else can help.

Have a good day.

**Comment by markcofano** [comment]
I have now made the Rotator with with the Scratch theme correctly.  It still does not work with Core.

**Comment by moldcraft** [comment]
Hello @markcofano ,

Please give me admin details to your site or teamviewer access. I need to reproduce the problem in order to understand it. I am thinking that it's just a css problem (for e.g. too big width)

You can contact me `moldcraft[at]email.com`

**Comment by markcofano** [comment]
Moldcraft,

I figured out the problem.  It was my code, not the Core theme.

Mark

**Comment by markcofano** [comment]
Problem was with my code, not the Core theme.  Sorry and thanks for the help.
