### ISSUE TITLE
Error with new option type.

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1632]
Hi @moldcraft ! I wrote a new option type that the same function like switch option. It works well on Theme Setting but has problem in Customizer. The value couldn't change. 
This is screenshot when option is active by default: 
![image](https://monosnap.com/file/504jffP9nyOewJUmuWeQsgzF2kiFPj.png)

When I unselect it, the value is change but I don't know why the value doesn't be updated. 

![image](https://monosnap.com/file/l9bB3P8mkaEhV02QBQgRIivcJQbzok.png)

Do you have any ideas? 

Thanks!

**Comment by duongancol** [comment]
Fixed.

**Comment by duongancol** [comment]
should I make a pull request? Maybe someone like this. 
https://monosnap.com/file/QTfNKY3cdaTc1oTcqM3i24nX9k63bX

**Comment by moldcraft** [comment]
> should I make a pull request?

Thank you, but no.

**Comment by duongancol** [comment]
no problem!
