### ISSUE TITLE
fw:options:init:tabs  does not work on side tabs

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1634]
fw:options:init:tabs  works only on tabs inside side tabs , but cant initiate single side tab 
I am trying to initiate this side tab http://prntscr.com/bfg7pl

	fwEvents.trigger('fw:options:init:tabs', {
		$elements: jQuery('#fw-options-tab-headertab,#fw-options-box-header_subbox')
	});

http://prntscr.com/bfg6st

in order to initiate a specific side tab I must initiate all tabs inside the fw_form .

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/43035809694f3df3fcb3ae965eac0a3556154669

Please test

**Comment by danyj** [comment]
this works but issue now is that is switches to the header tab , 

I am in topmenu tab and have an option that once cliked initiates all tabs inside topmenu + need to initiate header tabs + sub tabs , 

now it works but it switches   from  menutab to header tab

**Comment by danyj** [comment]
example 


```
Header side  ab 
Menu side tab  // I am here , option to initiate tabs is here ,  when clicked , I am moved to header tab 
```
