### ISSUE TITLE
Pricing Table Row Reordering Behaves Stragely

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1636]
It seems sometimes the pricing table cannot save its fields properly.

Adding some fields, renaming buttons and all of the actions don't seem to have issues but row reordering is kinda buggy.

After reordering fields and saving, some fields in are left blank or missing.

**Comment by moldcraft** [comment]
Hello,

Please give the exact steps to reproduce the problem, or a screencast/video.

**Comment by pe6o** [comment]
1. Create a normal pricing table
2. Save the page.
3. Reorder two rows and save.

The reordering should not be saved properly.

**Comment by moldcraft** [comment]
Reproduced https://vid.me/5IFX

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/pull/57

**Comment by pe6o** [comment]
Does the "wontfix" tag mean that this issue won't be fixed? :\

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/pull/57#issuecomment-227981401
