### ISSUE TITLE
AJAX form submit /  NOOB

### ISSUE THREAD

**Issue by markcofano** [ThemeFuse/Unyson#1640]
Help please:

I want to submit form data directly into a custom CMS.  The site is using the Core client theme.

I have read the documentation on AJAX form submission at:

               http://manual.unyson.io/en/latest/helpers/php.html#fw-form-ajax-submit

Per this documentation, I should:

-- enqueue script (Unyson/framework/static/js/fw-form-helpers.js) in front-end
-- run the initialization script

Three questions please:

Q1: where / how do I enqueue?

I am guessing that the following goes in {child-theme}inc/static.php?

if (!is_admin()) {
    wp_enqueue_script(
        'fw-form-helpers',
        fw_get_framework_directory_uri('/static/js/fw-form-helpers.js')
    );
    wp_localize_script('fw-form-helpers', 'fwAjaxUrl', admin_url( 'admin-ajax.php', 'relative' ));
}

Q2:  Where does the initialization code (below) go?

jQuery(function(){
    fwForm.initAjaxSubmit({
        //selector: 'form[some-custom-attribute].or-some-class'

        // Open the script code and check the `opts` variable
        // to see all options that you can overwrite/customize.
    });
});

Q3: where / how to I specify the url to make the ajax post?

I have also read the thread at:

               https://github.com/ThemeFuse/Unyson/issues/353

and still have confusion.

Thanks for any help you can provide!

**Comment by moldcraft** [comment]
> Q1: where / how do I enqueue?
> 
> I am guessing that the following goes in {child-theme}inc/static.php?

Yes

> Q2: Where does the initialization code (below) go?

In any `.js` file in your theme that is enqueued on all frontend pages.

> Q3: where / how to I specify the url to make the ajax post?

https://github.com/ThemeFuse/Unyson/blob/v2.5.6/framework/static/js/fw-form-helpers.js#L15-L20

**Comment by Ataurr** [comment]
@moldcraft  is it possible to add thankyou page after confirmation ?

 I need to track convertions on Google Analytics. Thank you!

**Comment by moldcraft** [comment]
@Ataurr Overwrite [`onSuccess`](https://github.com/ThemeFuse/Unyson/blob/v2.5.6/framework/static/js/fw-form-helpers.js#L69) and do a redirect

**Comment by virvazir** [comment]
Not quite tech savvy, could you tell me what exactly I need to replace with what to do a redirect? 

Also I would like to retain the form submit failure message if its possible.
