### ISSUE TITLE
Insert Link doesn't work in WYSIWYG 

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#1642]
The Insert Link button doesn't seem to work in the `wp-editor` option field. Marking a text and clicking the button, doesn't show the pop-up link window.

![image](https://cloud.githubusercontent.com/assets/1108563/16107971/c7851f2a-33a8-11e6-81a2-208f7d8075c0.png)

```php
'text' => array(
	'type'   => 'wp-editor',
	'label'  => esc_html__( 'Content', 'domain' ),
	'desc'   => esc_html__( 'Enter some content for this texblock', 'domain' )
)
```

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1615

**Comment by pe6o** [comment]
Oh, so I guess I could inspect if to see if I can find the culprit.

**Comment by pe6o** [comment]
@moldcraft  Hmm, do you have any directions what could be the problem? I am trying to fix it but I can't seem to achieve anything...

**Comment by moldcraft** [comment]
I tried to fix it too, but without results
