### ISSUE TITLE
Count number of images under type multi-upload

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1646]
Let just say I am uploading images. 
```
    'bg_image' => array(
        'label' => __('Upload images', 'fw'),
        'type' => 'multi-upload'
    )
```

Can I show the number of attachment? Like 5 images are in bg_image

**Comment by moldcraft** [comment]
Hello,

Images are visible

![](https://static.md/b25c5eed206f80426772bd2245609aa9.png)

Why do you need a counter and where it should be placed? Please give a screenshot

**Comment by ashraf92** [comment]
I want to display number of images on frontend. 
![capture](https://cloud.githubusercontent.com/assets/12174913/16139479/99ff9ffa-3469-11e6-9b9a-7ccc4cc106c0.PNG)

**Comment by duongancol** [comment]
you could use the [count() function](http://php.net/manual/en/function.count.php) to return the number of element
