### ISSUE TITLE
SyntaxError when saving theme option.

### ISSUE THREAD

**Issue by mamunhpath** [ThemeFuse/Unyson#1649]
Hi, I'm getting this error "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" when saving theme option panel.
![error](https://cloud.githubusercontent.com/assets/17651807/16120386/1cb7d98a-3401-11e6-96e7-322cc1c7eec2.png)

**Comment by moldcraft** [comment]
Please open browser inspector and check server response.

**Comment by mamunhpath** [comment]
Hi, Checked that but not found any error. Any other solution? Thanks.

**Comment by moldcraft** [comment]
Please give a screenshot of browser inspector server response

**Comment by mamunhpath** [comment]
Hi, Thanks. 
Here it is : 
http://prntscr.com/bh96aj
http://prntscr.com/bh96kx

**Comment by moldcraft** [comment]
![](https://static.md/ba71e2eb73cf2ca0737a9e8c23ad4290.png)

**Comment by mamunhpath** [comment]
Showing this error: http://prntscr.com/bh9kja

**Comment by moldcraft** [comment]
The error is in theme. Please contact your theme author.
