### ISSUE TITLE
Options suggestion

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#165]
Can we have these  options ,  I posted joomla fields since I could not find better examples
* read files in folder , display them as a select list single/multi  example https://docs.joomla.org/Filelist_form_field_type
* read folder names in folder display them as select list   single/multi  https://docs.joomla.org/Folderlist_form_field_type
* display  menu items as select list  single/multi  https://docs.joomla.org/Menu_form_field_type

so far I see these can just extend the current  select option.

**Comment by moldcraft** [comment]
Can you give us examples of daily uses for each these options?

**Comment by danyj** [comment]
* Read folders I use for fontface kits http://yjsimplegrid.com/documentation/extend/adding-custom-font-face-kits.html
* read files switch stylsheets, or js plugins
* menus, show/hide/add/remove something on specific menu item/page

**Comment by sergiubagrin** [comment]
Q: Read folders I use for fontface kits http://yjsimplegrid.com/documentation/extend/adding-custom-font-face-kits.html
read files switch stylsheets, or js plugins
A: We dont have this options in work. I added it to review board. 

Q: menus, show/hide/add/remove something on specific menu item/page
A: Can you give me more details? You mean to create custom menus for specific pages, posts? 

Thanks

**Comment by danyj** [comment]
Here is an example of what fileslist option could do 

In your demo you have background-image option 
http://screencast.com/t/u7GPbvdlcmD3

This is the partial code for it ( 75 lines ) 
http://screencast.com/t/vmgeumvJrD

By  adding the fileslist option 
it would read all images from specific folder and display them as an option.
If end user wants more or less images as an option he/she would just delete/upload images from a given folder. 
 
With your current setup , Imagine the background-image option code snippet for
something like this http://screencast.com/t/shsjtUXUP1, or  50 bg patterns and 20 bg images. That snippet would be around 554 lines of code.
