### ISSUE TITLE
New added column icon missing.

### ISSUE THREAD

**Issue by mamunhpath** [ThemeFuse/Unyson#1655]

**Comment by moldcraft** [comment]
Hello,

Please give a screenshot

**Comment by mamunhpath** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/17651807/16847148/56c05974-4a11-11e6-8d74-430ca57d1e4c.png)
This two icon missing.

**Comment by moldcraft** [comment]
Those are [custom icons](https://github.com/ThemeFuse/Unyson/issues/1702), not included in Unyson.
