### ISSUE TITLE
Shortcodes do  not process do_shortcode()

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1657]
To test , go in shortcode tabs options and change the tab_content option to be wp-editor 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/tabs/options.php#L18

add text than add media from link http://prntscr.com/bi94dl

the shortcode is not outputed but I do see do_shortcode(....) in the view.php
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/tabs/views/view.php#L20

also when viewing the editor text view the embed is saved 

http://prntscr.com/bi94tz

**Comment by moldcraft** [comment]
I have no video thumbnail and it is inserted as link [screenshots](https://static.md/ac6159f0-37b3-11e6-925a-0d6262eff339#)

**Comment by danyj** [comment]
@moldcraft  strange , here is my editro snipp


					'tab_content' => array(
						'type' => 'wp-editor',
						'tinymce' => true,
						'size' => 'large',
						'reinit' => true,
						'wpautop' => false,
						'editor_height' => 100,
						'editor_type' => 'tinymce',
						'value' => 'This is dummy tab text',
						'label' => __('Content', 'fw')
					)

**Comment by moldcraft** [comment]
Same thing with your array

**Comment by danyj** [comment]
but i have no additional plugins or settings enabled 
http://take.ms/gLEEb

when you save does it insert the shortcode?

**Comment by danyj** [comment]
@moldcraft  either way , the bug is in frontend , shortcode is not processed


add this in and check front 

    [embed]https://www.youtube.com/watch?v=fewEn2ApXTU[/embed]

**Comment by moldcraft** [comment]
Reproduced

**Comment by danyj** [comment]
@moldcraft ,  this is bit higher level bug , is not only  tabs , text-block also , seems like shortcodes do not process `do_shortcode`

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1500

**Comment by danyj** [comment]
@moldcraft   , not sure what this means ,  editor bug or ?
