### ISSUE TITLE
Unyson Visual Page Builder Progress Bars

### ISSUE THREAD

**Issue by angnaybr** [ThemeFuse/Unyson#1660]
Hello, I need an advice about an issue.

In Unyson Visual page builder > theme elements > progress bars
I've changed max value to 500 from 100. It's because i need to use the bar as a minute based comparison instead of percentage.
I've made it with the change in options.php.
But now i have a problem. 
The progress bars become so long and exceeds the page.
I think currently progress bars value = progress bar width in percentage, I changed this value to 500, this will mean 500% of width. how can i shorten the width and use 500 value.

**Comment by angnaybr** [comment]
![screen shot 2016-06-21 at 16 56 40](https://cloud.githubusercontent.com/assets/20068173/16231959/4174ae32-37d1-11e6-968c-ebcecfb10cf0.png)

**Comment by moldcraft** [comment]
Hello,

There is no progress-bar shortcode in Unyson https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/master/shortcodes

Please contact your theme author
