### ISSUE TITLE
How to make extension automatically disable themselves from theme config

### ISSUE THREAD

**Issue by tlartaud** [ThemeFuse/Unyson#1661]
Hi there, thanks for this framework, I'm just starting to play around with it.

I just discovered that your mega menu extension is not compatible with premium themes custom walker nav class. They simply get ignored. If i desactivate the mega menu extension, my menus using some custom walker class start working again.

I realized that my framework-customiaztion had just this configuration :

```
$manifest['supported_extensions'] = array(
	'portfolio' => array(),
);
```

But, for some reason, all the extensions were enabled (the plugin is installed via TGMPA, and I had maybe activated the extensions by hand trough wp-admin -> unyson extensions)

To avoid any problem from my customers, i wish I could disable this page, and automatically activate and desactivate the extensions to fit the configuration from my theme. For some reasons, we are able to activate some extensions even if the theme is not compatible with them : I really, really, reaaaaalllyyy don't want that, it can lead to very strange behaviors. Is there any way to disable this page ? Do you recommend me to include the framework directly from the bootstrap.php file instead of tgmpa ? I simply want that a site with my theme got the appropriate extensions enabled, or at least, I don't want the extensions not compatible with the theme to be enabled. Is there a way to achieve that ?
Do you recommend me to import the included plugin via composer instead of tgmpa to be sure to manage the proper framework version ?

What happened if a user switch to my theme, and if he had already the unyson plugin installed, with a version outside of this scope, let's assume the user has the 3.8.8 version ? What if he has the 5.2.2 version ?
```
'framework'  => array(
		'min_version' => '4.0.0',
		'max_version' => '4.0.2'
	)
```

Thx.

**Comment by moldcraft** [comment]
Hello,

You can hide the extension from list with css (each has an id). In case the extension is somehow auto activated (not sure how), you can add this code in your theme and it will disable it:

```php
add_action('admin_footer', '_action_theme_disable_fw_megamenu');
function _action_theme_disable_fw_megamenu() {
	if (fw()->extensions->manager->can_activate() && fw_ext('megamenu')) {
		fw()->extensions->manager->deactivate_extensions(array('megamenu' => array()));
	}
}
```
