### ISSUE TITLE
Theme settings page load animation changed ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1662]
I downloaded the master today and theme settings page load animation is changed,  like zoom in from bottom and is very bad , preloader is on top and the page flashes. 

http://prntscr.com/bj6b24

**Comment by danyj** [comment]
@moldcraft  this is first frame , and as yo can see it goes over the menu , http://prntscr.com/bj6bi4

**Comment by danyj** [comment]
and modals boxes text is not in the middle anymore http://prntscr.com/bj6cq7

**Comment by moldcraft** [comment]
On my side everything is fine

**Comment by danyj** [comment]
I moved my table css to backend by mistake. false alarm. sorry
