### ISSUE TITLE
New update today causing header repeat

### ISSUE THREAD

**Issue by lastminutewed** [ThemeFuse/Unyson#1664]
Just checked all of our Plugins and the update for Unyson is causing a header repeat on our site. It doesn't matter if it's the header image or just text, it's repeating it endlessly until the server gives out. See below:

![screen shot 2016-06-21 at 4 45 29 pm](https://cloud.githubusercontent.com/assets/20077488/16250762/e76a817e-37d4-11e6-99b7-a0676b7a91ba.png)

**Comment by moldcraft** [comment]
Hello,

Can you give me admin/ftp access to your site? If yes, send the details to `moldcraft[at]email.com`
