### ISSUE TITLE
[Bug] Sidebar Picker doesn't load in custom post type

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1665]
Hi @moldcraft !
The sidebar picker looks well on Edit Page, but in custom post type page, it look like that: 
![Alt text](https://monosnap.com/file/61WtWPpo0jyTNDQMYAVqNqk14zsXhn.png)
You could test with Portfolio extension.

**Comment by moldcraft** [comment]
Hello,

Thank you for reporting. I will inspect this issue later (busy with other). You can try to find the problem and submit a pull request.

**Comment by mowshon** [comment]
Hi, @duongancol !
You need to enable your custom port-type in Page Builder settings.

**Comment by duongancol** [comment]
thank @mowshon , It works well.
