### ISSUE TITLE
Homepage is completely blank

### ISSUE THREAD

**Issue by SujoyM1** [ThemeFuse/Unyson#1666]
I am creating a site with WpHunters Dentist theme which uses Unyson.
http://themeforest.net/item/dentist-dental-one-page-wordpress-theme/12242997

The Homepage suddenly disappeared. Wp Hunters can't seem to figure out the problem.

The error log gives us this error "[17-Jun-2016 06:26:00 UTC] PHP Fatal error:  Call to undefined method WP_Error::get_size() in /home/happymri/public_html/cms/wp-content/plugins/unyson/framework/helpers/class-fw-resize.php on line 79"

The site is on http://happytoothclinic.com/cms

Let me know if you need admin / ftp creds to check.

**Comment by moldcraft** [comment]
Hello,

Please tell WpHunters to try [this fix](https://github.com/ThemeFuse/Unyson/commit/52d11875f8881a808de0eb66ba7df7e7dfade9f4)

**Comment by SujoyM1** [comment]
Still not working. The hosting admin has sent us the following.

We have noticed error in server log under plugin unyson. Please find the log below.
---
[23-Jun-2016 06:15:28 UTC] PHP Parse error: syntax error, unexpected 'if' (T_IF) in /home/happymri/public_html/cms/wp-content/plugins/unyson/framework/helpers/class-fw-resize.php on line 80
---

**Comment by moldcraft** [comment]
Please give a screenshot of the code from that line

```
unyson/framework/helpers/class-fw-resize.php on line 80
```

**Comment by SujoyM1** [comment]
Hi,

Thanks. I renamed the Unyson plugin and the site came back to life. Then I re-installed Unyson. It seems to work now. probably a corrupted file or something.

---
Sujoy
