### ISSUE TITLE
I want to show only content by get_the_excerpt function

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#1667]
When I use the get_the_excerpt  and get_the_content function it will occur like that 

`lwidth="1" default_spacing="min-spacing" height="auto" background_options="{"background":& `

if I want to use only the_content function, then full content is being showing but I want to use substr function for excerpt content like 100 words from 1000 words.

Regards
anisur

**Comment by moldcraft** [comment]
Hello,

What you expect to be in excerpt if page is built with shortcodes like section, column, button, slider, contact form?

I think excerpt is valid only for posts made with default editor and contain only text (without fancy elements).

A solution would be to display in posts list only post title and featured image.
