### ISSUE TITLE
Unable to install extensions

### ISSUE THREAD

**Issue by mrbadger73** [ThemeFuse/Unyson#1668]
Hi, 
We have WordPress installed in a subfolder called /wp. We store the wp-content in the default WordPress root location.
We provide a sym link within the core /wp folder to assist with plugin compatibility.

We are unable to see any PHP errors being generated, alongside the red error message, so suspect it could be your own code catching something and generating the below error message:

Cannot create temporary directory: /var/www/vhosts/domain.com/httpdocs/wp-content/plugins/unyson/tmp

We manually created the /tmp folder for testing and the plugin removed the folder but then gave the same error above.
PHP should be able to write to that location and the removal of the folder helps to back this.

Any thoughts?

WP version: 4.5.3
Core files installed in http://siteurl/wp
httpdocs/wp
httpdocs/wp/wp-content -> /var/www/vhosts/mr-badger.co.uk/httpdocs/wp-content
httpdocs/wp-content
unyson:  2.5.6
PHP-FPM 5.6.22

**Comment by moldcraft** [comment]
>

**Comment by moldcraft** [comment]
> PHP should be able to write to that location

To write in that folder is used `WP_Filesystem` not plain php functions like `file_put_contents`.

Please debug [this code](https://github.com/ThemeFuse/Unyson/blob/v2.5.6/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2372-L2395)

**Comment by philthetechie** [comment]
Hi, this is also an issue for me too. 

Please apply the patch in 
https://github.com/philthetechie/Unyson/pull/1/files
to resolve.

I'll submit a PR tomorrow unless you implement and close this issue in the meanwhile. 

Cheers.
