### ISSUE TITLE
Download Available Extensions

### ISSUE THREAD

**Issue by fedriz** [ThemeFuse/Unyson#167]
![erroreu](https://cloud.githubusercontent.com/assets/9001053/5793541/2847dc18-9f48-11e4-95b8-7262d740664b.png)

Hi! What can I do? I do not know what it means.
It happens when I click the button to download any extension.
Thanks in advance!

**Comment by moldcraft** [comment]
Hi,
It seems that your server can't access properly [this url](http://github-api-cache.unyson.io/repos/ThemeFuse/Unyson-Shortcodes-Extension/releases) or `json_decode()` fails  ([the code](https://github.com/ThemeFuse/Unyson/blob/6db4abf276f2ff50f70b7e9a3736372040a91d67/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L1792))

I can't reproduce this error, so please
* Open in your browser this url `http://{your-domain}/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=shortcodes` and try to install the extension. Maybe you will see some php warnings on the page.
* Else, you can try to debug [this code](https://github.com/ThemeFuse/Unyson/blob/6db4abf276f2ff50f70b7e9a3736372040a91d67/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L1792) to find out why the `$releases` variable is empty

**Comment by fedriz** [comment]
Downloading the "Shortcodes" extension...

"Shortcodes" extension github repository "ThemeFuse/Unyson-Shortcodes-Extension" has no releases.

Same error, i will try to reinstall.
Thanks for your help
