### ISSUE TITLE
Plugin causing a warning to pop up

### ISSUE THREAD

**Issue by meaherma** [ThemeFuse/Unyson#1670]
I installed the plug in and now this warning is up at the top of my screen this is what it says:
Warning: session_start(): open(/home/content/p3pnexwpnas05_data01/49/2382049/tmp/sess_c0m2khfjmktb4ru2n68sflchj6, O_RDWR) failed: No such file or directory (2) in /home/content/p3pnexwpnas05_data01/49/2382049/html/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php on line 214

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/content/p3pnexwpnas05_data01/49/2382049/html/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php:214) in /home/content/p3pnexwpnas05_data01/49/2382049/html/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php on line 214
Skip to main content

It goes away as soon as deactivate it.

**Comment by meaherma** [comment]
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/content/p3pnexwpnas05_data01/49/2382049/html/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php:241) in /home/content/p3pnexwpnas05_data01/49/2382049/html/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php on line 241
 


this shows at the top of my screen when I preview my site.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1273#issuecomment-182040492
