### ISSUE TITLE
[Bug] [Urgent] fw_ext_page_builder_is_builder_post

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1671]
fw_ext_page_builder_is_builder_post helper doesn't work in the latest version of Page builder and Unyson. 
Could you check it please!

**Comment by moldcraft** [comment]
I added `fw_print(fw_ext_page_builder_is_builder_post(get_the_ID()));` in `{theme}/page.php` and it's working.

**Comment by danyj** [comment]
@duongancol    check this if you are dealing with  `get_the_ID()`

https://github.com/ThemeFuse/Unyson/issues/1582

**Comment by duongancol** [comment]
thank you guys! It's my mistake
