### ISSUE TITLE
problem with yoast

### ISSUE THREAD

**Issue by mariap69** [ThemeFuse/Unyson#1673]
I bought a theme which use your Unyson editor. I installed also YOAST plugin and disable SEO of the theme. As you can see in attached file Yoast don't recognize the job done with your editor. It detects 0 words. 
More: while with all other theme I used Yoast, it appears at the bottom, so it read correctly all the words written in the pages, with Unyson Yoast appears at the top. So, probably, that's the reason why it didn't recognize the words written in the page.

I checked the theme with seo tools and it has a great speed value. I appreciate a lot it, and that's why I 'd like continue to use Unyson editor, but I hope you recognize, I need to fix this bugs.  

Please help
 Thank you in advance
![unyson-bug](https://cloud.githubusercontent.com/assets/3530569/16301258/c88046e2-3944-11e6-9404-dcb1a634bb54.jpg)

PS: website is available on hotelunalido.it

**Comment by duongancol** [comment]
The same problem here: https://github.com/ThemeFuse/Unyson/issues/845
