### ISSUE TITLE
[BUG] wp-editor option type problems

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1674]
Okay, I've got here two evident problem for the [`wp-editor`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#wp-editor) option type.

**Prerequisite steps in order to reproduce both of the bugs:**

I'm doing my testing on fresh WordPress 4.5.3 and master branch of the Unyson, with Scratch theme on it.

<hr>

##### 1. `wp-editor` is not diplaying correctly inside `fw.OptionsModal()`

- Go in `/wp-admin`, any page will do.
- Open JavaScript console
- Run this code `(new fw.OptionsModal({options: [{'editor': {type: 'wp-editor'}}]})).open()`

You'll get a new modal with an `wp-editor` that is completely broken. Also, if you are lucky enough, you'll get also `Can't find "fw_wp_editor_7d8036e` error -- [screen](https://i.imgur.com/f5PXGwT.png).

[GIF](https://i.gyazo.com/56b6f295aacd426ac38c4328c2dc687a.gif)

By the way, options for each shortcode are also displayed in `fw.OptionsModal` instances, no? They somehow manage to get `wp-editor` correctly.

<hr>

##### 2. two `wp-editor`s with same IDs

If you've looked carefully at the previous gif, you've seen that two `wp-editor`s with same IDs are somehow treated as same (look at how I'm switching it's tabs), even they belong to different options target. For me, that's plain wrong.

I used this array of options both in **Scratch** Theme Settings and in `fw.OptionsModal`:
```php
'editor' => array(
	'type' => 'wp-editor'
)
```

<hr>

I'm also inspecting how this option type works and the `wp-editor` itself. Any help is appreciated.

**Comment by andreiglingeanu** [comment]
I just discovered [editor_integration.js](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/includes/page-builder/static/js/editor_integration.js) file. I gues that how it is implemented for the Page Builder shortcodes modals.

**Comment by danyj** [comment]
@andreiglingeanu  since you are digging ,   

this was a strange case where we could see our shortcodes in avada editor but could not see our own 


https://github.com/ThemeFuse/Unyson/issues/756#issuecomment-129212311
http://prntscr.com/82nczj

now I am looking at redux editor and it seems more strait forward as ours 
https://github.com/reduxframework/redux-framework/tree/master/ReduxCore/inc/fields/editor

you might want to give that script a try and see if you can bring our shortcodes to wp-editor option that would mean a tremendous framework improvement and add the missing feature that we all need .

**Comment by andreiglingeanu** [comment]
@danyj About [this one](https://github.com/ThemeFuse/Unyson/issues/756#issuecomment-129212311). Avada's using redux framework? I don't know, frankly.

**Comment by andreiglingeanu** [comment]
Taking a look at how redux used to get it done.

**Comment by moldcraft** [comment]
> @danyj this was a strange case where we could see our shortcodes in avada editor but could not see our own

I blocked Unyson shortcodes button https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.5/extensions/editor-shortcodes/static/js/plugin.js#L150-L152

because it is impossible to make it work outside main post wp-editor https://github.com/ThemeFuse/Unyson/issues/1227#issuecomment-177483805

**Comment by andreiglingeanu** [comment]
Some ideas about implementing normal `wp-editor` for `fw.OptionsModal` and `addable`, by the way:

If our preinit data is not in `tinyMCEPreInit.qtInit`, do an AJAX request to the server and try to get this data. It should be achievable using this [class](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/class-wp-editor.php#L1205). [Where](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/class-wp-editor.php#L1167) it is actually generating it. [`self::$qt_settings `](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/class-wp-editor.php#L344) is also interesting.

I think it is doable, at the cost of one more AJAX request before initialization.

I know, [`_WP_Editors`](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/general-template.php#L2830) is private, but there's no other way we can get it to work.

Another option is to completely switch our standard WP editor with something else, but this won't be backwards compatible. But this will involve more work.

Opinions are welcome.

**Comment by moldcraft** [comment]
_Minor note: Don't hurt your nerves with that slow and ugly core.trac.wordpress.org browse the code on github https://github.com/WordPress/WordPress/tree/4.5.3_

> Another option is to completely switch our standard WP editor with something else, but this won't be backwards compatible. But this will involve more work.

Also WP plugins will not be able to hook to add custom buttons. http://codex.wordpress.org/TinyMCE_Custom_Styles#Using_style_formats

**Comment by andreiglingeanu** [comment]
Will come back tomorrow with more info and possibly with a pull request, so that we'll have something more concrete to look at.

**Comment by moldcraft** [comment]
> once the WP core guys will make a change

Please report them issues so they will be aware of the problem and will fix it someday.

**Comment by andreiglingeanu** [comment]
Anyone can also confirm this is working now? Please let me know if something's going not well.

**Comment by andreiglingeanu** [comment]
It should be done now. Leave a note if it's not.
