### ISSUE TITLE
Map shortcode stopped working

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1675]
Hello!

I have noticed that Map Shortcode just stopped working with a following error in console:

`Google Maps API error: Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
`

> MissingKeyMapError
> The script element that loads the API is missing the required authentication parameter. If you are using the standard Maps JavaScript API, you must use a key parameter with a valid API key. If you are a Premium Plan customer, you must use either a client parameter with your client ID or a key parameter with a valid API key.
> 
> See the guide to API keys and client IDs.

is there any way to fix this problem? Thank you

**Comment by WPJobs** [comment]
a screenshot of Alert from Contacts page
![sc](https://cloud.githubusercontent.com/assets/12991525/16302630/e9b2e10c-3954-11e6-8317-2fd24e84bd50.png)

**Comment by moldcraft** [comment]
It works on my side

![](https://static.md/9b6b01f7b5d0ea82f63a0825196ac1d7.png)

**Comment by moldcraft** [comment]
I think they introduced some requests limitations and you reached the limit, to prevent that you will need to create an account and insert somewhere the API key

Trouble...

**Comment by WPJobs** [comment]
yes, it works fine on my test installation too, but this site is not working http://johnsonshomebuilding.co.uk/contact-us/

i can provide you WP admin access if needed

**Comment by WPJobs** [comment]
i think so...

**Comment by andreiglingeanu** [comment]
@moldcraft Also getting [this](https://i.imgur.com/YVtcShX.png) errors, but it works.

**Comment by moldcraft** [comment]
> https://developers.google.com/maps/documentation/javascript/usage#usage-limits-for-google-maps-javascript-api-services

**Comment by moldcraft** [comment]
https://developers.google.com/maps/documentation/javascript/usage

**Comment by Ataurr** [comment]
Same here. Also a popup displayed 

![](http://puu.sh/pFmsG/7ebb3d5268.png)

**Comment by RodalErmakov** [comment]
Hi)
Please help.
I have the same problem.
![fire](https://cloud.githubusercontent.com/assets/14311916/16360519/f89a9bb8-3b81-11e6-9a2f-5477964224b7.jpg)
On this site map shortcode isn't working.

What should I do? How to solve this issue?
If I need API keys where should I add them?

Please help, many of my clients have already complain that map doesn't work.

Thanks)

**Comment by player0k** [comment]
The same issue on "add new event" page  in the events extension.
![screen] (https://i.imgur.com/6BuxqQR.png)

**Comment by duongancol** [comment]
Yes, the same problem here

**Comment by moldcraft** [comment]
### How to fix the error on frontend

* Create a new application in [Google Account](https://console.developers.google.com/flows/enableapi?apiid=maps_backend,geocoding_backend,directions_backend,distance_matrix_backend,elevation_backend&keyType=CLIENT_SIDE&reusekey=true) and get the API key.
* [Overwrite](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes) map shortcode `static.php` and add the `key` query parameter in script url. Replace [this line](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.15/shortcodes/map/static.php#L12) with

```php
'https://maps.googleapis.com/maps/api/js?'. http_build_query(array(
    'v' => '3.23',
    'libraries' => 'places',
    'language' => $language,
    'key' => 'YOUR_API_KEY',
)),
```

**Comment by player0k** [comment]
I think need to rewrite option-type map: 
add new input for API Key, and after saving page  value show map and other inputs

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/pull/1683

**Comment by Ataurr** [comment]
This issue fixed frontend error but backend still showing this  error.

**Comment by moldcraft** [comment]
## How to fix the error in backend

1. Create a new application in [Google Account](https://console.developers.google.com/flows/enableapi?apiid=maps_backend,geocoding_backend,directions_backend,distance_matrix_backend,elevation_backend&keyType=CLIENT_SIDE&reusekey=true) and get the API key.
2. Add in `{theme}/functions.php` or your theme `hooks.php` file

```php
/**
 * Dequeue default google maps option type script wich doesn't have API key
 * and enqueue one with an API key
 */
function _action_theme_replace_gmaps_script() {
	$handle = 'google-maps-api-v3';

	if (!wp_script_is($handle)) {
		return;
	}

	// https://github.com/ThemeFuse/Unyson/blob/v2.5.6/framework/includes/option-types/map/class-fw-option-type-map.php#L32-L38
	{
		wp_dequeue_script($handle);
		wp_deregister_script($handle);
	}

	wp_enqueue_script(
		$handle,
		'https://maps.googleapis.com/maps/api/js?'. http_build_query(array(
			'v' => '3.15',
			'libraries' => 'places',
			'language' => substr( get_locale(), 0, 2 ),
			'key' => 'YOUR_KEY'
		)),
		array(),
		fw()->manifest->get_version(),
		true
	);
}

function _action_theme_fw_init() {
	if (version_compare(fw_ext('page-builder')->manifest->get_version(), '1.5.6', '>=')) {
		add_action('admin_enqueue_scripts', '_action_theme_replace_gmaps_script', 20);
	} else {
		add_action('admin_print_scripts', '_action_theme_replace_gmaps_script', 20);
	}
}

add_action('fw_init', '_action_theme_fw_init');
```

**Comment by moldcraft** [comment]
**Important!** The above solutions ([1](https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228732020) and [2](https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228821014)) are temporary fixes, we are working on a fix that will be included in next Unyson release.

**Comment by giathinh910** [comment]
Thank @mold.

**Comment by martinburdon** [comment]
Thanks @moldcraft  👍 
Do you have an estimate of when the next release will be so I can inform my customers please?

**Comment by moldcraft** [comment]
@martinburdon https://github.com/ThemeFuse/Unyson-Extensions-Approval !

**Comment by martinburdon** [comment]
@moldcraft awesome 👍

**Comment by WPJobs** [comment]
Is it possible to do not load Google Maps script in admin panel until shortcode will be added? Some of my clients see error message in the backend even they do not use maps shortcode on any page :(

if they do not plan to use this shortcode, they should not obtain an API key at all i believe

**Comment by WPJobs** [comment]
Could you tell me, please, how many do you need to fix the problem? Too many people affected with this bug

**Comment by moldcraft** [comment]
> if they do not plan to use this shortcode, they should not obtain an API key at all i believe

How should I know if the user will add or not the Map shortcode in builder. Should we create Telepathy Extension?

> how many time do you need to fix the problem?

The release will be today https://github.com/ThemeFuse/Unyson-Extensions-Approval

**Comment by WPJobs** [comment]
@moldcraft Telepathy Extension sounds good. why Visual Composer plugin + maps shortcode do not have such problems, did they create Telepathy Extension?

**Comment by moldcraft** [comment]
Sorry about the telepathy joke, I am also frustrated by this bug.

I made the google maps script to load on map option type init (when the user will open the maps shortcode settings) https://github.com/ThemeFuse/Unyson/commit/150b8f286b4023be90218dc40ba79ae287a0ecbb

**Comment by WPJobs** [comment]
@moldcraft thank you so much! i know how it's hard to support many users, so i understand you like no other ;)

**Comment by Shahab2905** [comment]
Hi @moldcraft Thank you for all the help with Maps Shortcode, however it seems lazy load google map may have disabled the 'Autocomplete address' functionality. The **Map Option Type** no longer auto complete address and its is now required to click on 'Cannot find the location?' to fill the full address. Can you please look into it. 

![ScreenShot](https://www.diigo.com/file/image/daeoabezdcasrdssczcdordqse/Theme+Settings.jpg)

**Comment by moldcraft** [comment]
Hello @Shahab2905 

On my side everything works fine https://vid.me/ChN4

**Comment by Shahab2905** [comment]
Hi @moldcraft, please try the option on its on, on Theme Settings Page. When you use it as a shortcode, it works fine. Its the map option type outside page builder which is not functional to auto complete. Thank you for your help.

http://manual.unyson.io/en/latest/options/built-in-option-types.html#map

**Comment by moldcraft** [comment]
I added in `settings.php`

```php
$options = array(
	'm' => array(
		'type'  => 'map',
		'value' => array(
			'coordinates' => array(
				'lat'   => -34,
				'lng'   => 150,
			)
		),
		'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
		'label' => __('Label', '{domain}'),
		'desc'  => __('Description', '{domain}'),
		'help'  => __('Help tip', '{domain}'),
	),
);
```

and it works https://vid.me/Ulb7

**Comment by danyj** [comment]
@moldcraft  , I did not test the fix for the map shortcode but today there was a new release and in events extensions this bug is still there, alert in front.

**Comment by danyj** [comment]
@moldcraft  added this in map shortcode static.php overrdie


```
if (method_exists('FW_Option_Type_Map', 'api_key')) {
	$query_params['key'] = FW_Option_Type_Map::api_key();
}

wp_enqueue_script(
	'google-maps-api-v3',
	'https://maps.googleapis.com/maps/api/js?'. http_build_query($query_params),
	array(),
	$query_params['v'],
	true
);
```

but it did not work until I entered my own API key here 

     $query_params['key'] = ....

this is empty 


    fw_print(FW_Option_Type_Map::api_key());

I have the latest Unyson 2.5.8 , updated today  , not master ,

**Comment by moldcraft** [comment]
@danyj Yes, you must enter the API Key

**Comment by Shahab2905** [comment]
@moldcraft Thank you for your help, but autocomplete of location is not working for me. I have tested it over and over even with nothing but twentysixteen theme and unyson alone. Could you please look into it. I can send you the login and FTP details, if you prefer.

**Comment by moldcraft** [comment]
@Shahab2905 Send admin/ftp details to `moldcraft[at]email.com`

**Comment by Shahab2905** [comment]
@moldcraft thank you. I just sent you the email from: shahab.khan[at]quantatec.co.uk. Any help is highly  appreciated.

**Comment by moldcraft** [comment]
@Shahab2905 [screenshot](https://static.md/7653e6a61925bd0c1f0839915d6b1df6.png)

**Comment by Shahab2905** [comment]
@moldcraft Thank you so very much for all your help. I just had to enable the API for Google Places as it was not by default when we create an API key. Thank you :+1:

**Comment by antoniomangiacapra** [comment]
I added it to my theme and it worked well for a while, now I have an user that still experience the popup in backend.

I did some tests and in the function _action_theme_replace_gmaps_script(), the script "google-maps-api-v3" seems not registered or enqueued, so the function just return without do anything.

The only call to google maps API was:

```
/* <![CDATA[ */
var _fw_option_type_map = {"google_maps_js_uri":"https:\/\/maps.googleapis.com\/maps\/api\/js?v=3.23&libraries=places&language=en&key="};
/*  ]]> */
```

At the end I changed the function in this way:

```
function _action_theme_replace_gmaps_script() {

	wp_localize_script(
		'map-scripts',
		'_fw_option_type_map',
		array(
			'google_maps_js_uri' => 'https://maps.googleapis.com/maps/api/js?'. http_build_query(array(
				'v' => '3.23',
				'libraries' => 'places',
				'language' => substr( get_locale(), 0, 2 ),
				'key' => 'MY_KEY_HERE',
			))
		)
	);

	$handle = 'google-maps-api-v3';

	if (!wp_script_is($handle) || !defined('FW')) {
		return;
	}

	// https://github.com/ThemeFuse/Unyson/blob/v2.5.6/framework/includes/option-types/map/class-fw-option-type-map.php#L32-L38
	{
		wp_dequeue_script($handle);
		wp_deregister_script($handle);
	}

	wp_enqueue_script(
		$handle,
		'https://maps.googleapis.com/maps/api/js?'. http_build_query(array(
			'v' => '3.15',
			'libraries' => 'places',
			'language' => substr( get_locale(), 0, 2 ),
			'key' => 'MY_KEY_HERE'
		)),
		array(),
		fw()->manifest->get_version(),
		true
	);

}
```

Now the popup in the backend is disappeared, and the map fields in the backend seems works again, but after saving I noticed that the coordinates are not saved.

The current API call is:

```
/* <![CDATA[ */
var _fw_option_type_map = {"google_maps_js_uri":"https:\/\/maps.googleapis.com\/maps\/api\/js?v=3.23&libraries=places&language=en&key="};
var _fw_option_type_map = {"google_maps_js_uri":"https:\/\/maps.googleapis.com\/maps\/api\/js?v=3.23&libraries=places&language=en&key=MY_KEY_HERE"};
/* ]]> */
```

Some suggestion? Am I totally out of the way?

**Comment by joanna-s** [comment]
Has this been resolved? I have updated Unyson but it still isn't working.
