### ISSUE TITLE
Unyson interface has broken down

### ISSUE THREAD

**Issue by LuqueASZ** [ThemeFuse/Unyson#1677]
We have installed unyson 4 months ago. After working awesome for 4 months, now we have discovered that the Unyson interfase doesn't work.

My english is a little bad, so I attached a screenshot of the problem.

Thanks and regards,

![image](https://cloud.githubusercontent.com/assets/20113124/16310127/9c3c5694-396b-11e6-991f-cc4ea8facf2e.png)

**Comment by moldcraft** [comment]
Hello,

1. Maybe you have corrupt files after changes via FTP?
2. Disable all plugins and check if it helps?
3. Which theme are you using?
