### ISSUE TITLE
Set Unyson Default Color?

### ISSUE THREAD

**Issue by ferman** [ThemeFuse/Unyson#1678]
There isn't a place to set a default color for Unyson that I can find for the Page Builder. Does it grab from somwhere set in WordPress or is there not a way at all to change it? It'd be nice to be able to change the default color so that everything matches my sites style.

**Comment by moldcraft** [comment]
Please give a screenshot, I don't understand which color

**Comment by ferman** [comment]
@moldcraft Sure thing! 

Does setting the default color require me to just overwrite the default color css?

I'd imagine something like that works.

`.fw-btn-1 {
    background-color: #333 !important;
}`

I just thought it'd be helpful to be able to change it in the Unyson settings to make thing more customizable. 

![2016-06-24 11_53_42-sample page wordpress](https://cloud.githubusercontent.com/assets/418533/16347594/6ad05fc8-3a02-11e6-9f95-8b83b975a9a6.png)
![2016-06-24 11_53_20-edit page wordpress wordpress](https://cloud.githubusercontent.com/assets/418533/16347595/6ad3bec0-3a02-11e6-8578-c3f52b8b3544.png)

**Comment by moldcraft** [comment]
Sorry, we will not do any changes in that option. You can [overwrite](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes) button options and view in theme.
