### ISSUE TITLE
Page template

### ISSUE THREAD

**Issue by vrabota** [ThemeFuse/Unyson#1679]
Hi, can I check if Page was created with page builder or default wordpress way?

I need to create different templates for default pages and something different to pages with Page Builder.

Unyson doesn't have any conditional function for this?

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/1479

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.2/helpers.php#L3-L8
