### ISSUE TITLE
Wrong placement of Sidebar

### ISSUE THREAD

**Issue by morgari** [ThemeFuse/Unyson#1681]
Hi, mates. Thank you for your perfect framework.
I have an issue:

To begin with I removed all my sidebars (for them not to bother or confuse me). I have the following structure of my single.php

```php
<?php get_header(); ?>
<div class="container">
<div class="row row-eq-height" id="primary"> 
<div id="content" class="col-sm-8"> 
<section class="main-content">
<?php while ( have_posts() ) : the_post(); ?>
<h1><?php the_title();?></h1>
<ol class="breadcrumb"><?php the_breadcrumb(); ?></ol>
<?php the_content(); ?>
<?php endwhile; ?>
</div><!-- col8 -->
 <aside id="sidebar-single" class="col-sm-4"> 
 <div><?php get_sidebar(); ?></div>
</aside>
</section><!-- main-content -->
</div> <!-- row-primary -->
</div> <!-- container -->
<?php get_footer(); ?>
```

and when I'm adding a new sidebar with a shortcode "Widgets" it appears in the place of `<?php the_content(); ?>` and my `<?php get_sidebar(); ?>` is empty. How can I solve my problem in such a way that my widgets appear in `<?php get_sidebar(); ?>` and not in content part?

Thanks!

**Comment by moldcraft** [comment]
Hello,

The **Widget Area** shortcode gets widgets from the chosen sidebar and displays them in post content.
