### ISSUE TITLE
add custom css class to fw-row inside a section module

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#1684]
Good morning and sorry for may english.
i have added a custom option (text field) to a section module.
is possible to use this option as css class for the .fw-row generated inside this section?
if Yes, how?
Thank you so much

**Comment by moldcraft** [comment]
Hello,

It is not possible to affect other shortcodes from another shortcode.

You can add the class [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.15/shortcodes/section/views/view.php#L30) and in css do

```css
.fw-main-row > div > .YOUR_CLASS {
    ...
}
```

**Comment by moldcraft** [comment]
Hello,

It is not possible to affect other shortcodes from another shortcode.

You can add the class [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.15/shortcodes/section/views/view.php#L30) and in css do

```css
.fw-page-builder-content section > .YOUR_CLASS > .fw-row  {
    ...
}
```
