### ISSUE TITLE
Breadcrumbs extension bug

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1688]
Hi! I've noticed that breadcrumbs displays "No title" for Blog posts page instead of page title from settings, please see attached screenshots

![sc](https://cloud.githubusercontent.com/assets/12991525/16413803/ecf25adc-3d3c-11e6-8027-f174dabd50e6.png)
![sc2](https://cloud.githubusercontent.com/assets/12991525/16413804/ecf837f4-3d3c-11e6-93a7-a94b8bb54cc2.png)
![sc3](https://cloud.githubusercontent.com/assets/12991525/16413805/ed23b60e-3d3c-11e6-8724-6d9a3c4b5745.png)

**Comment by player0k** [comment]
[Unyson-Breadcrumbs-Extension L137](https://github.com/ThemeFuse/Unyson-Breadcrumbs-Extension/blob/master/includes/class-breadcrumbs-builder.php#L137)

**Comment by WPJobs** [comment]
As you can see on a first screenshot, "Page for posts" has "News" title

**Comment by player0k** [comment]
Now the name is taken from  the static page name for posts page.

It may be necessary to remove these lines (L134-L140)[https://github.com/ThemeFuse/Unyson-Breadcrumbs-Extension/blob/master/includes/class-breadcrumbs-builder.php#L134-L140]

**Comment by moldcraft** [comment]
Important info to reproduce the problem:

![staticshot_08-07-2016_17-15-30](https://cloud.githubusercontent.com/assets/1475489/16690239/a432e51e-452f-11e6-9a77-dc1d3ef92f86.png)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1688
