### ISSUE TITLE
Extension : Google Analytics issue

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1689]
It appears that something is wrong with extension.
In google chrome when i insert the GA **id** and click save, I get a blank page (about:blank)

In Firefox i get "Server not found"

Tested with TwentySixteen theme
 Wordpress 4.5.3
 Unyson 2.5.6

It appears that something is being done with the **url** of the site.
This is the url I'm using for development:
````
http://tema-1.192.168.3.101.xip.io/wp-admin/admin.php?page=fw-extensions&sub-page=extension&extension=analytics
````

In case of Firefox this is what I get in the **url** bar with the "Server not found" error
````
http://~^tema-1//..+//.xip//.io$/wp-admin/admin.php?page=fw-extensions&sub-page=extension&extension=analytics
````

**Comment by ivandotv** [comment]
@moldcraft 
Have you found the issue?
Can I help?

**Comment by moldcraft** [comment]
I can't reproduce the problem. On my localhost the page save works fine.

Can you send me admin details to `moldcraft[at]email.com`?

**Comment by ivandotv** [comment]
I'm developing it locally.
Maybe when the page saves, there is a problem with reload/ redirect.
Also, I'm using nginx.
I will take a look at it myself, and get back to you.

**Comment by thednp** [comment]
Server side functionality won't work on localhost in most cases, and especially with G.Analytics.
