### ISSUE TITLE
How to edit directly short code in text mode ?

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#169]
Hi,

Anyone could tell me the way to edit short code that generated by Page Builder in text mode ?

Thanks

**Comment by rockalife** [comment]
Hi @maiakhoa,

If by `text mode` you mean the the WordPress edtior, than we have just updated the repository of the [page builder extension](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension) with new functionality that integrates the page builder shortcodes with it. Here is a screenshot

![page builder wp editor integration](http://static.md/f5faaff2b87743235df25b466bfe5a70.png)

**PS:** This functionality will not be released until Friday (23.01.2015), so there will not be an automated update until then. If you want to test this now you can do one of the following:

* download [v1.3.0](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/releases/tag/v1.3.0) and extract it into `plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/`
* clone [the repository](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension) into the same place as mentioned above
* wait for the release so the update will be automatic

**PPS:** If any bugs or other problems occur feel free to open issues, or comment [here](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/6)

**Comment by maiakhoa** [comment]
Thanks for you feedback and new features.

I mean I can edit the text that generated by Page Builder when switch again to text mode. As you know, if I have a button short-code, I created it once and copy to another page instead of create new by Page Builder.

I will try the new feature.

Thanks

**Comment by rockalife** [comment]
At the moment there is no way editing the page created with the page builder in the WordPress editor's text mode (or visual mode), so you can not create a page with the builder, switch to text mode copy the generated shortcodes and then pasting them into some other page.
You could use page builder templates to save some sort of layout with predefined shortcodes and load it when creating another page.

As for the runtime generation, we do not have such an extension. The shortcodes are generated when the page is being saved or updated. The extension which I have mentioned above just lets you write a page in the WordPress editor and insert somewhere in the text an Unyson shortcode.

**Comment by maiakhoa** [comment]
Thank so much @rockalife

**Comment by rockalife** [comment]
You are welcome.
