### ISSUE TITLE
Google Maps error when developing on localhost

### ISSUE THREAD

**Issue by jsrothwell** [ThemeFuse/Unyson#1690]
I have created a new instance of Wordpress with unyson. I am using a custom theme for Unyson and havent had any problems until today.

When I am trying to edit a page (I have the page builder set to pages only) I get a modal warning about a google maps element.

This page was unable to display a Google Maps element. Please contact the site administrator. If you are the administrator of this site, please check the JavaScript console or check the following page for troubleshooting: http://g.co/mapsJSApiErrors

Im really kinda stuck here as all I did was try to create a page. It happens upon saving and updating pages or refreshing the page editor. I dont know what else I can explain but I will do my best to follow up. I will not be near the actual  instance for a half day from reporting this so if I cannot answer any questions offhand

**Comment by duongancol** [comment]
It's fixed here: https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-229177103
