### ISSUE TITLE
Can't see shortcode list (trying to insert slider)

### ISSUE THREAD

**Issue by polterbyte** [ThemeFuse/Unyson#1693]
Now that all my extensions are installed (thank you mold craft!) I have successfully created a slider, but I can't seem to insert it on a page.

The ThemeFuse instructions (found here: http://docs.themefuse.com/the-core/your-theme/sliders/add-a-slider-to-a-page-the-core) tell me to "Add the Slider Shortcode found under the Media Elements tab", and point to the following image:

![the-core-slider-1](https://cloud.githubusercontent.com/assets/20191664/16481864/af0b2526-3e83-11e6-8380-ae372453e020.jpg)

Unfortunately, when I go the Media Manager, all I can see is this:

<img width="1217" alt="captura de tela 2016-06-29 as 18 09 07" src="https://cloud.githubusercontent.com/assets/20191664/16482143/e38bcf3e-3e84-11e6-8a6f-45dff2dced51.png">

Am I doing something wrong? Is there another type of page where I can insert sliders? Can it be inserted in the main default page?

Thanks!

Ruy

**Comment by moldcraft** [comment]
Hello,

Please ask ThemeFuse support this question.

**Comment by moldcraft** [comment]
Which theme you have?
