### ISSUE TITLE
How to display post from specific category post

### ISSUE THREAD

**Issue by bok12** [ThemeFuse/Unyson#1699]
I have to create two pages with blog template, but for two different category posts. I don't know how exactly solve this problem - I tried make new PHP template file with WP_Query functions (my PHP skill is very low), but it didn't work. 
How I can do this with PHP or maybe some plugin?

**Comment by bok12** [comment]
bump

**Comment by moldcraft** [comment]
Hello,

How is this related to Unyson?

**Comment by bok12** [comment]
Theme is based on this framework, but maybe I made a mistake and should get help with theme support instead framework?

**Comment by moldcraft** [comment]
Yes, please ask theme author.

**Comment by bok12** [comment]
OK, sorry, my mistake.
