### ISSUE TITLE
No Page Preview and Shortcode/HTML generated

### ISSUE THREAD

**Issue by NwpDeveloper** [ThemeFuse/Unyson#170]
I like the plugin, but there are 2 major issues:
1) When using the shortcodes to layout a page it doesn't generate a preview.
2)There also doesn't seem to be a way to convert page to html or edit the page in the text mode.

**Comment by rockalife** [comment]
Hi @NwpDeveloper,

1. Do you mean preview of the page that is being built ? Can you describe more detailed where do you imagine the page preview to be displayed, or draw a mock.
2. About being able to update the page in text mode I've replied to another similar issue, check it out [here](https://github.com/ThemeFuse/Unyson/issues/169)

**Comment by NwpDeveloper** [comment]
1. When editing a page in the upper right hand corner is a the publish section. Theres a "Preview" button there next to the "Save Draft" button and above the "Publish" button.

The default functionality of Wordpress allows you to view chnages in a new tab when you hit "Preview" before saving.

With Unyson, when  you make a change to the page, and  you  hit the "Preview"  button, changes are not shown in the preview tab. You have to publish or save the page to see the changes. 

2. Following the link it seems that shortcode buttons were added to tinymce editor. However, I think the problem is linked to the core of how Unyson creates the page and shortcode. 

When using the drag and drop pagebuilder the shortcodes or html should be generated at run time and not when the page is saved or published. That way the page changes are available in the classic editor as well as the Unyson editor.

**Comment by rockalife** [comment]
1. I understood what you meant by preview, it seems to work fine for me, I've uploaded [a video](https://www.youtube.com/watch?v=okz-JGHfZLA) where I am testing it.
2. You are right, the page builder generates shortcodes when the page page is saved. The main idea is that a user should not need to switch between the visual page builder mode and the WordPress text mode and edit with the shortcode macros (like `[button text="some text" ...]`), however the developers have requested that the Unyson shortcodes to be integrated with tinyMCE and so we have created the extension that I have mentioned above. What I am trying to say is that we have intentionally created the page builder extension without the runtime generation and possibility to edit the content in text mode and then switch to visual and edit it some more.

**Comment by NwpDeveloper** [comment]
1. Thanks for posting the video. Perhaps there's a conflict with jquery in another plugin causing this issue on my install. 
2. Ok. No worries. 
How do I make full width rows? I want a row that spans the entire page with a background color yellow. Currently all rows have a fw-rows class and any css  changes affects all rows. 
Should I edit core files to change or append classes or is js necessary?

**Comment by moldcraft** [comment]
* The Preview and Revisions were fixed in the latest version of Unyson and extensions (make sure you are up to date)
* > How do I make full width rows?

    There is the Section shortcode.
