### ISSUE TITLE
Question regarding adding columns of multiple of 1/5 to the grid system

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1702]
We have the builder's `config.php` grid setup but the documentation doesn't say anything about adding
more column types to the grid, I was thinking about 2/5, 3/5, and 4/5 columns.

Questions: 
- If we override the `config.php` and add additional columns, how do we add the corresponding IMAGES to these new columns and where do we include them?
- With the additional columns, will the editor work properly when we'll change the width of a column to include the new column types?

UPDATE:
- The Javascript properly works toggling through all the new column classes/
- The images are not properly added, as simply configured as the original columns, see below:
  ![new_columns](https://cloud.githubusercontent.com/assets/6761246/16546065/52b02328-4147-11e6-9e60-6fbb7a1cc9da.png)

FINAL UPDATE:
- The thumbnails have to go to `framework-customizations/extensions/shortcodes/shortcodes/column/thumbnails/` folder and your new columns go fine. Here are all the thumbnails you need, already optimized:

![1_3](https://cloud.githubusercontent.com/assets/6761246/16546442/3c95f494-4153-11e6-81f4-6f4c27f7db01.png)
![1_4](https://cloud.githubusercontent.com/assets/6761246/16546444/3c9a0494-4153-11e6-8cf3-4e7c0d4b6e16.png)
![1_2](https://cloud.githubusercontent.com/assets/6761246/16546443/3c98c7fa-4153-11e6-89f9-0b5480e62ada.png)
![2_3](https://cloud.githubusercontent.com/assets/6761246/16546446/3c9bd63e-4153-11e6-82f7-4c0c264f0e9e.png)
![3_4](https://cloud.githubusercontent.com/assets/6761246/16546447/3c9d624c-4153-11e6-80cd-99143ea55255.png)
![1_1](https://cloud.githubusercontent.com/assets/6761246/16546445/3c9a2d20-4153-11e6-9f69-2c62938c0bd0.png)
![1_5](https://cloud.githubusercontent.com/assets/6761246/16546448/3cb3695c-4153-11e6-9d28-9286ddddc1dc.png)
![1_6](https://cloud.githubusercontent.com/assets/6761246/16546449/3cb4885a-4153-11e6-9f9d-145e1d53ab13.png)
![2_5](https://cloud.githubusercontent.com/assets/6761246/16546451/3cb563a6-4153-11e6-8d0d-57d6a9ba73fc.png)
![3_5](https://cloud.githubusercontent.com/assets/6761246/16546450/3cb4a434-4153-11e6-99fb-1c4e58fd5050.png)
![4_5](https://cloud.githubusercontent.com/assets/6761246/16546452/3cb68f92-4153-11e6-890e-a332b25df02c.png)

FYI: I will leave this open for others to learn and discuss.

**Comment by mamunhpath** [comment]
Wow, my two problems solution is here. Thanks.

**Comment by TheSaladFace** [comment]
Thanks for your work here @thednp saved me a lot of frustration :)

A few notes here:

1. "framework-customizations/extensions/shortcodes/column/thumbnails/" should be 
"framework-customizations/extensions/shortcodes/shortcodes/column/thumbnails/" for the image paths.

2.  'fw' needs to be a dependency in the backend grid css include -
`wp_enqueue_style(
        'thshpr-backend-grid',
        get_template_directory_uri() .'/framework-customizations/extensions/builder/static/css/backend-grid.css',
        array('fw'),
        fw()->theme->manifest->get_version()
    );`

3. the frontend grid css completely replaces the one in the unyson plugin builder directory

Probably these are all obvious, but maybe will help someone out who runs across this.

Hopefully these columns will be included in the plugin though (5 columns of 1/5 aren't too useful imo, it really needs the 2/5, 3/5 and 4/5).

Cheers
