### ISSUE TITLE
Search algorithm - suggestion

### ISSUE THREAD

**Issue by mowshon** [ThemeFuse/Unyson#1703]
Hi, everyone!

Once changed the way of backup data of an article in the database, the search no longer works because it only searches in the **titles** and in it **contents**. But now the content of the article is HTML – comment with  and the actual content is saved as JSON in wp_postmeta .

I tried to modify the searching algorithm and tried to find articles containing wp_postmeta with the key `fw:opt:ext:pb:page-builder:json`. But the result of the search is irrelevant, because we have a JSON structure in `fw:opt:ext:pb:page-builder:json` and once the algorithm is searching by keywords, it is searching by the shortcodes options that aren’t even noticeable for a simple user.

_I suggest a solution._
It will be better to save in a separate wp_postmeta the final result of all of the rendered shortcodes from the post, plus the function **strip_tags**, for removing the entire HTML. Thus,we will get only the text of the post. Based on this text will be held the search. By this field, it will be possible for other extensions to work, which need only the text of the article.

What do you think?

**Comment by danyj** [comment]
Check this , https://github.com/ThemeFuse/Unyson/issues/838
that was the reason for json save , mysql is crashing because of the post size on save

**Comment by markcofano** [comment]
Mowshon,

Are you are talking about WP search not searching for the text in Unyson
text fields, etc?  If so, I agree.  This is a shortcoming and hopefully it
is high on the list of enhancements.

Mark

**Comment by andreiglingeanu** [comment]
> Are you are talking about WP search
Yes, about old-good `search.php`.

@danyj Yes, we are aware of this.

**Comment by mowshon** [comment]
@danyj, I know about these changes. The problem is that after this change, the WP Search stopped working correctly, because the real content that you see in frontend is hidden from standard search algorith. If the search phrase is "**Color**", then result of your request will be all posts where shortcodes have `color` option in options.php.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/845#issuecomment-227421825

**Comment by moldcraft** [comment]
Test please: [Download](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/archive/master.zip) and extract in `unyson/framework/extensions/shortcodes/extensions/page-builder`
