### ISSUE TITLE
Moving sections up and down could be easier.

### ISSUE THREAD

**Issue by neko** [ThemeFuse/Unyson#1704]
As of Unyson 2.5.7, it's pretty damn difficult to move a large section (consisting of many rows) above or below another large section, where the top of one section is off screen, and the bottom of the other is off screen.

I feel that a way of fixing this could be to add "up" and "down" arrows, that move the section's position up and down respectively.

**Comment by moldcraft** [comment]
The solution can be to make the placeholder `max-height: 300px`

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1829
