### ISSUE TITLE
wp-editor in theme settings doesn't work after last update 2.5.7

### ISSUE THREAD

**Issue by RodalErmakov** [ThemeFuse/Unyson#1705]
Hi)
I use wp-editor option in my theme settings:
![err1](https://cloud.githubusercontent.com/assets/14311916/16551801/994ba4b8-41d5-11e6-9e10-b85d86a81a91.jpg)
And it worked.
After last update 2.5.7 wp-editor doesn't work:
![err2](https://cloud.githubusercontent.com/assets/14311916/16551828/cf6a69da-41d5-11e6-8b15-901201ad7e45.jpg)
tinyMCEPreInit is not defined

Please help.
Thanks)

**Comment by andreiglingeanu** [comment]
@RodalErmakov Please show the contents of the `tinyMCEPreInit` here.

**Comment by RodalErmakov** [comment]
Yes, I've sent you (to:andrei.glingeanu@gmail.com) an access to my wordpress site.
Thanks)

**Comment by andreiglingeanu** [comment]
@RodalErmakov Problem is reproduced. Fix to come soon.

**Comment by andreiglingeanu** [comment]
@moldcraft The problem here is once again because we don't have `wp-editor` anywhere else besides the popup. In this case it doesn't know it will have to enqueue `wp-editors` static.

**Comment by andreiglingeanu** [comment]
The temporar fix to this problem is to temporary add a hidden `wp-editor` anywhere in your Theme Settings. It doesn't have to be hidden, you should hide it just if you don't want him to be around.

This will do the trick.

Frankly, there should be a better way of doing this but I don't have time to get to this now.

**Comment by RodalErmakov** [comment]
Ok, thanks)

**Comment by moldcraft** [comment]
> The problem here is once again because we don't have wp-editor anywhere else besides the popup

Option-type `popup`? It does enqueue for inner options https://github.com/ThemeFuse/Unyson/blob/v2.5.7/framework/includes/option-types/popup/class-fw-option-type-popup.php#L34

**Comment by andreiglingeanu** [comment]
@moldcraft Addable popup.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/v2.5.7/framework/includes/option-types/addable-popup/class-fw-option-type-addable-popup.php#L31

**Comment by moldcraft** [comment]
#### Steps to reproduce

Add in `{theme}/framework-customizations/theme/options/settings.php`

```php
$options = array(
	'p' => array(
		'type' => 'addable-popup',
		'popup-options' => array(
			'w' => array('type' => 'wp-editor'),
		),
	),
);
```

**Comment by andreiglingeanu** [comment]
@moldcraft This doesn't work. I have to add every time one more `wp-editor` in TS in order to make it working. Not sure why.

**Comment by moldcraft** [comment]
I didn't say that is the solution.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1715

**Comment by andreiglingeanu** [comment]
25a102a

**Comment by moldcraft** [comment]
Please test again https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/232
