### ISSUE TITLE
error:undefined on text block after update

### ISSUE THREAD

**Issue by ChrisBataillon** [ThemeFuse/Unyson#1706]
Hi, after updating Unyson to 2.5.7 I get error:undefined when editing text block. Datas still show up on the website though, but I can't update or add something to a newly created text block.
WP is latest version, theme is Twenty sixteen (child) and I already tried to re-install Unyson…
Thanks for your help.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1700
