### ISSUE TITLE
Adding custom row type to the Page Builder Price Table

### ISSUE THREAD

**Issue by dobromir-hristov** [ThemeFuse/Unyson#171]
I`m trying to extend the builder to have a "description" type row for the Pricing Tables. 
The purpose is to make it compatible with Zurb Foundation, and to learn your framework. For now I love it.
I saw the table types they are defined in FW_Option_Type_Table class, but i cannot figure how to add another type.

**Comment by sergiubagrin** [comment]
Hi @dobromir-hristov,

Why you need a description type row? Can you give me a example with a screen? I think you can use Default Row for descriptions: http://screencast.com/t/JpFA37B4

**Comment by dobromir-hristov** [comment]
It is for the purpose of learning the framework, how to extend the functionalities, and while porting everything to Zurb Foundation, I saw they have a description row so I decided to give it a shot. It can be a different type of row, depending of someones needs.

**Comment by sergiubagrin** [comment]
Hi @dobromir-hristov, 

> It can be a different type of row, depending of someones needs.

We analysed a lot of tables and pricing tables and we decided to use only this type of rows and columns. From our point of view are more than enough : our FrontEnd Standart: http://test.themefuse.com/integrare_html/tables.html (soon will be available with Unyson Docs)
