### ISSUE TITLE
Calendar shortcode issue

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1712]
I noticed adding a calendar shortcode to the page breaks the layout of the entire page as well as the fact that the `bootstrap.min.js` is out of date, I think it's 3.0.0.

I would have liked this to have a very simple view, PHP only and without those HTML template file, only with the timezone detect script mostly, generally very very little scripting.

Since most of us already use Bootstrap and/or some use custom distributions of Bootstrap like [my script](https://github.com/thednp/bootstrap.native/), I feel we could have needed a much more simple shortcode, perhaps somewhat similar to the Wordpress core calendar widget, but I would probably have to do that myself.

My question is: are there any plans to improve this shortcode or should I proceed with disabling it?

Would love to hear from you.

**Comment by moldcraft** [comment]
Twentysixteen theme, layout is fine

![staticshot_06-07-2016_16-23-16](https://cloud.githubusercontent.com/assets/1475489/16619230/f3f2d708-4395-11e6-8265-c0185442d50f.png)

----

No plans to improve the shortcode, sorry.

**Comment by thednp** [comment]
Yes, that's all fine. The problem is with other themes that already have bootstrap, this shortcode uses bootstrap.css and breaks my layout.
