### ISSUE TITLE
Contact Form feedback message

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#1713]
Hi.
is possible to place the contact form feedback message in other position? (eg. at the bottom of form?)
thank's

**Comment by thednp** [comment]
It's really [simple do do](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes).

**Comment by sandromattei** [comment]
Service Unavailable
The service is temporarily unavailable. Please try again later.

**Comment by thednp** [comment]
Where did that come from?

**Comment by moldcraft** [comment]
You can hook to this action http://manual.unyson.io/en/latest/helpers/php.html#fw-form
store the messages in a global variable (don't do `echo`), enqueue the messages in js and from js append them to your `<form>`

**Comment by moldcraft** [comment]
Or store the messages in a global variable and output them on [this action](https://github.com/ThemeFuse/Unyson/compare/b256e354658dbb66412c9ee80a8915e64a9f91a7...2051c3e6d5f04b62eaacb5c9c15e30030af9f2f6#diff-2083b84e23a3f555b62dc06f57b182ceR462)

**Comment by sandromattei** [comment]
Thank's!!!! is a perfect solution!
