### ISSUE TITLE
When adding SVG code to a text block, reopening the text block shortcode shows no content

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#1714]
Repo steps:
1. Add a text block shortcode.
2. Paste some SVG code in.
3. Click save for the text block.
4. Reopen the text block shortcode and the code has gone.

The code does however display on the frontend of the site.

![svg](https://cloud.githubusercontent.com/assets/4599099/16567561/f9b7bd36-4217-11e6-8614-6e3cdf88d37a.gif)

**Comment by martinburdon** [comment]
That's what I assumed however I have a custom shortcode using the `wp-editor` option type and this seems to work fine 😕

**Comment by player0k** [comment]
@martinburdon ,As option - you can write your own shortcode, with custom options and custom view, which will consists svg tags and your options in framework-customizations directory

**Comment by andreiglingeanu** [comment]
@martinburdon It works when you add SVG file with **Add Media**. But you should add svg media type support in your theme.
