### ISSUE TITLE
WP editor is not working

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#1715]
Hi there,

We updated Unyson to the latest version and now WP-editor does not load in shortcodes or theme settings and console log shows this:

scripts.js?ver=2.5.7:97 wp-editor init error fw_wp_editor_65bc16bccvab345345sd0bb0f2b6a TypeError: Cannot create property 'name' on string '['(…)

**Comment by danyj** [comment]
is being worked on, 
https://github.com/ThemeFuse/Unyson/issues/1705

**Comment by pear1** [comment]
Good to know, for us it is little different (sort of loads, but isn't usable).
