### ISSUE TITLE
Addable option is lag in the latest version of Unyson 

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1716]
Hi! the addable option in Customizer is lag when I update to the latest version. 
Please check the screencast [here](http://take.ms/92Iil)
Thanks!

**Comment by andreiglingeanu** [comment]
@duongancol On it. Just reproduced.

**Comment by andreiglingeanu** [comment]
Please test.

**Comment by duongancol** [comment]
@andreiglingeanu : it works well.

**Comment by duongancol** [comment]
@moldcraft : could we remove [it](http://take.ms/LrYfMm)?

**Comment by duongancol** [comment]
Thank @andreiglingeanu

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1716#issuecomment-230412896

Please open a separate issue
