### ISSUE TITLE
Open Graph og:image missing leading "http:"

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1717]
When Facebook Object Debugger scrapes my site, “http:” is dropped from og:image, resulting in the following error: “Object at URL ‘http://flowstaterunner.com/&#8217; of type ‘website’ is invalid because the given value ‘//flowstaterunner.com/wp-content/uploads/2016/07/Mockup-PBK3-Render-smaller.jpg’ for property ‘og:image:url’ could not be parsed as type ‘url’.”
Note the missing http: before the //flowstaterunner.com/… above.
 
http://prntscr.com/boy2up

Any help will be much appreciated! Thank you.

**Comment by moldcraft** [comment]
I can't find the `og:image` string in Unyson and extensions, so that meta is printed from your theme.

Please contact your theme author and tell him to print the url in this way:

```
echo set_url_scheme('//hello.world/wp-content/.../image.jpg');
```
