### ISSUE TITLE
Is there a way to deregister some default option type?

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#1719]
I'm sure, that it is, I want to know how :)
I just want to replace it with my own, but save the original name of this option type to use it in other shortcodes.

**Comment by thednp** [comment]
As of what I know now you can only de-register shortcodes, but frankly I don't see the point of removing option types as long as you can create your own.

**Comment by onebelarusianguy** [comment]
@thednp yeah, I saw about shortcodes. The idea is _to change this option type in all shortcodes_, including the default shortcodes.

**Comment by thednp** [comment]
I think you can also override option types but I haven't tested that, I mostly use other color pickers and other custom option types.

**Comment by onebelarusianguy** [comment]
@thednp not really. I have php notice: 'Option type "icon" already registered',  but it works well :)

**Comment by moldcraft** [comment]
You can't. https://github.com/ThemeFuse/Unyson/blob/v2.5.7/framework/core/components/backend.php#L223

Other option-types or extensions can rely on some specific option-type behavior, if you overwrite an option type you can break other option-types or extensions.

**Comment by onebelarusianguy** [comment]
@moldcraft understood, thanks
