### ISSUE TITLE
Disable shortcodes from the page builder

### ISSUE THREAD

**Issue by ierpe** [ThemeFuse/Unyson#172]
Hi,

Is it possible to disable specific default shortcodes from the page builder?

**Comment by rockalife** [comment]
Hi @ierpe,

We did a demo of how to disable a shortcode [in our Scratch theme](https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/shortcodes/hooks.php), also check out [this similar issue](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/1)

**Comment by ierpe** [comment]
Thanks that solved it!
