### ISSUE TITLE
Use everywhere date format from WordPress Settings page

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1722]
![staticshot_05-07-2016_18-29-49](https://cloud.githubusercontent.com/assets/1475489/16590056/99e0e514-42de-11e6-9d0e-f1cba8da3b16.png)

**Comment by moldcraft** [comment]
It was a huge mistake to save in date pickers date and time as string values. I can't make it work with Settings date format because there a glitches on converting already saved data.

It should be save as timestamp and only on display to be shown as formatted date, but internally all db values should be timestamp, that way users would be able to change any time the date format from Settings and everything would work fine. Unfortunately it's to late and this is not possible.

**Comment by danyj** [comment]
what are you suggesting?  modifying the option formats than ?

**Comment by moldcraft** [comment]
I don't know. I will try to figure out something tomorrow.

**Comment by randybruder** [comment]
Is there any update on this? I'm working on a restaurant website with forms using Unyson's date/time picker, and having the dates show up as European style and in the 24-hour format is potentially confusing to the restaurant's American audience.

Thanks for the great plugin!

**Comment by moldcraft** [comment]
Sorry, no updates. You can create your own datepicker option that will save the value as timestamp

**Comment by andreiglingeanu** [comment]
@moldcraft What about handling timezones? It does handle it correctly?

**Comment by moldcraft** [comment]
I don't know about timezones, never worked with them.

**Comment by andreiglingeanu** [comment]
Okay, I will take a look at it and get back with a bit more details.
