### ISSUE TITLE
PHP Notice for WP Editor

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1724]
Hello!

I have noticed a small bug, Unyson WP Editor displays an error:

`Notice: Undefined index: external_plugins in \wp-content\plugins\unyson\framework\includes\option-types\wp-editor\includes\class-fw-wp-editor-settings.php on line 213`

when i add WP Editor with following params:

```
'page_404_content' => array(
  'type'  => 'wp-editor',
  'label' => esc_html__('Page 404 content', 'mytheme'),
  'value'  => '<h1 style="text-align: center;"><strong>404</strong> Page Not Found</h1><p style="text-align: center;">The page you are looking for does not appear to exist.<br/>Please go back or head on over our homepage to choose a new direction.</p>',
  'tinymce' => true,
  'media_buttons' => false,
  'teeny' => true,
  'wpautop' => true,
  'reinit' => true,
  'size' => 'large',
  'editor_type' => 'tinymce',
  'editor_height' => 200
),
```

**Comment by andreiglingeanu** [comment]
@moldcraft Will be fixed in next release. Same as #1700.

**Comment by moldcraft** [comment]
Please test again https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/232
