### ISSUE TITLE
Can't use Text Block or Team member on Visual page Builder

### ISSUE THREAD

**Issue by polterbyte** [ThemeFuse/Unyson#1725]
Hello!

I am trying to use the Visual Page Builder in order to create some pages, but when I try to insert a text block or a team member, all I get is an error message saying "Error: Undefined". Here it is:

<img width="1278" alt="captura de tela 2016-07-05 as 16 48 24" src="https://cloud.githubusercontent.com/assets/20191664/16597762/f476cb28-42d0-11e6-9476-c50c557540de.png">

Am I dois something wrong?

Thanks!

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1700

**Comment by polterbyte** [comment]
How can I open the Browser Console on macOS? F12 doesn't seem to work.

Thanks.

**Comment by andreiglingeanu** [comment]
@polterbyte If you're talking about chrome, press alt-cmd-j.
