### ISSUE TITLE
[Need help]Contact Form

### ISSUE THREAD

**Issue by tnthao10** [ThemeFuse/Unyson#1726]
Hi,
I have problem with Contact Form, I tried here
https://github.com/ThemeFuse/Unyson-Documentation/blob/master/extension/forms/index.rst
to create custom my form, but it not working  desired.
Can you help me solve it?
Url path:
{my_theme}\framework-customizations\extensions\
My custom form
https://drive.google.com/file/d/0Bwqyu4p-ZcE1T1Q0OGRfV1VoNVE/view?usp=sharing
Check my video!
https://www.youtube.com/watch?v=Dz3F0IBX-r0&feature=youtu.be
Thank you!

**Comment by thednp** [comment]
You need to customize the shortcode of the contact form, only if you need to have it use your own HTML formatting, and not the builder core coding.

Your edits should go here:
* `{my_theme}\framework-customizations\extensions\forms\extensions\contact-forms\shortcodes\contact-form\options.php` for the options, but I am not sure yet if changing them could affect the functionality, perhaps today I am going to do this
* `{my_theme}\framework-customizations\extensions\forms\extensions\contact-forms\views\` for the views

**Comment by tnthao10** [comment]
i want to add custom icon into input or textarea
like this:
http://i.imgur.com/BQvdpZy.jpg

**Comment by thednp** [comment]
As a correction to my above comment, here's the way to go: [click me](https://github.com/ThemeFuse/Unyson/issues/816#issuecomment-135127411).

**Comment by tnthao10** [comment]
Yes, i'll try.

**Comment by thednp** [comment]
Hey there, ignore my above messages, you should only follow this guide I just stumbled upon same issue like you and this explains it all.
http://manual.unyson.io/en/latest/extension/forms/index.html#contents
