### ISSUE TITLE
addable-box doesn't work after update

### ISSUE THREAD

**Issue by antoniomangiacapra** [ThemeFuse/Unyson#1727]
I we an extension containing an addable box, it has always worked until my last update of Unyson to 2.5.7 and WP to 4.5.3 (I can't know what is the cause exactly).

Now if I delete an item it is deleted, but if I reload the page it is again there.

If I click on "Add item", I have this problem:
![fotografia_dello_schermo_070616_124636_pm](https://cloud.githubusercontent.com/assets/11173091/16615537/acd13374-4377-11e6-8f1b-8440a456c3e4.jpg)

The corresponding code section is this one:

```
/**
			 * Re-render wp-editor from newBox
			 */
			if ($option.find('.fw-option-box').length > 1) {
				fwWpEditorRefreshIds( //This one is the line of the error
					jQuery(
						$option.find('.default-box-template').attr('data-template')
					).find('textarea').attr('id'),

					$newBox
				);
			}
```

And the error log is empty.

Thank you so much in advance for the help.

**Comment by andreiglingeanu** [comment]
@antoniomangiacapra Please update to the last Unyson master.

**Comment by antoniomangiacapra** [comment]
Thank you so much for your so quick reply @andreiglingeanu :)
