### ISSUE TITLE
Shortcode wp-editor Visual editor by default

### ISSUE THREAD

**Issue by ierpe** [ThemeFuse/Unyson#173]
Hi,
When creating a wp-editor option for a shortcode, the editor is always on the Text tab by default.
Is there an option to have the visual editor by default?

```
$options = array(
	'text' => array(
		'type'   => 'wp-editor',
		'teeny'  => false,
		'reinit' => true,
    	        'tinymce' => true,
		'label'  => __( 'Content', 'fw' ),
		'desc'   => __( 'Enter some content for this texblock', 'fw' ),
	)
);
```

**Comment by player0k** [comment]
Hi,
No there are not.

**Comment by ierpe** [comment]
Ok, I need this feature.

Could you point out the file that deals with the shortcodes options types please?

I might have a look, implement this option and make a pull request

**Comment by player0k** [comment]
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/wp-editor/static/js/scripts.js#L68
