### ISSUE TITLE
Unyson not displaying Available Extensions

### ISSUE THREAD

**Issue by JaceRidley** [ThemeFuse/Unyson#1735]
Today, I made a clean install of WordPress on my site, and bought a Theme from Envato that requires Unyson. So, I installed both, and am having issues. Unyson doesn't display any available extensions except for the two in the attached picture, but if you leave and come back to the page, several of them show up for a split second in the bottom field. 

The other problem is that the same problem seems to be occuring to my theme's Theme Options, as shown in the first picture. The theme is called Croton, and my site URL is www.jaceridley.com 

The site doesn't seem to be malfunctioning in any way otherwise, and it's not a plugin conflict as I only have the following Active:  Unyson, Contact Form 7 and Jetpack. 

Any guidance would be good. The theme creator is also investigating, though his installation is working fine. 

![screenshot1](https://cloud.githubusercontent.com/assets/20325421/16630193/5a4aad82-4387-11e6-8bda-d52fc08f3e95.png)
![screenshot2](https://cloud.githubusercontent.com/assets/20325421/16630192/5a4a16e2-4387-11e6-835f-e4888b1fee70.png)

**Comment by moldcraft** [comment]
Hello

1. Set `WP_DEBUG` to `true` in `wp-config.php`
2. Press Ctrl+U in browser to see page source code, maybe there is an error
3. Switch to a default WP theme and check if the problem still happens. If not, please contact your theme author

**Comment by JaceRidley** [comment]
It works normally when I switch it to the default. I've informed the Theme creator of this as well. Would anyone have a theory why it would work normally for him and give me a problem?

**Comment by andreiglingeanu** [comment]
I think the problem is in your hosting provider and the limits they're
imposing on yourself.
On Wed, Jul 6, 2016 at 22:04 JaceRidley <notifications@github.com> wrote:

> It works normally when I switch it to the default. I've informed the Theme
> creator of this as well. Would anyone have a theory why it would work
> normally for him and give me a problem?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/1735#issuecomment-230872626>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC13LCCzKUs7c6D2zEpujfTvJROzraQTks5qS_xWgaJpZM4JGYUw>
> .
>
-- 
Kind regards,
Andrei

**Comment by JaceRidley** [comment]
In what way? I use Arvixe. To the best of my knowledge, I shouldn't have any account limitations

**Comment by JaceRidley** [comment]
What limits does Unyson require that I would need for them to change?

**Comment by moldcraft** [comment]
Can you send your admin/ftp details to `moldcraft[at]email.com`?

**Comment by JaceRidley** [comment]
Sent. You wanted the WP Admin info, right? Not access to my CPanel? If so, I'll send that when I get home from work.

**Comment by moldcraft** [comment]
Only admin, no need for cPanel.

Received, inspecting...

**Comment by moldcraft** [comment]
All extensions are there but [are hidden](https://static.md/fcbe8f5a338d035cd1d576b53e8ba336.png).

If you view page html source and search `fw-ext-megamenu` you will see that it doesn't have `style="display:none;"` so it is added later by a script from theme. Contact your theme author.

**Comment by moldcraft** [comment]
![](https://static.md/d47324f1563d475018b87f3ceda4cec7.png)
