### ISSUE TITLE
Builder inputs are blank

### ISSUE THREAD

**Issue by jsrothwell** [ThemeFuse/Unyson#1736]
Im doing some content maintenance on a site that uses the Unyson framework.

When I open a text block in the visual editor it shows a blank input that often cannot have details entered into it. The visual tab doesnt work at all.

1. Empty input box even with content.
2. Cant edit input box, only delete
3. Visual tab doesnt work

**Comment by moldcraft** [comment]
Please test this version https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/232
