### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by themeheap** [ThemeFuse/Unyson#1737]
We are using Unyson in our theme and facing following error:

I was checking the logs and have these msgs on both sites:

PHP Fatal error:  Out of memory (allocated 821035008) (tried to
allocate 77 bytes) in
public_html/lawyer/wp-content/plugins/unyson/framework/helpers/class-fw-cache.php

Our PHP is limited to 1 GB to avoid that a single request to use all
memory of the server, that is a far generous value for any website.
Actually on our shared servers PHP has a limit of 256 MB and works for
all users. We could try to increase that value a bit, though it'll for
sure hang your server and all websites.

I've disabled the plugin 'unyson' (from the error msg) by ssh with command:

$ wp --skip-plugin=unyson plugin deactivate unyson

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1732#issuecomment-230899884
