### ISSUE TITLE
Text Block + TinyMCE Custom Styles = Bug

### ISSUE THREAD

**Issue by meneldil** [ThemeFuse/Unyson#1739]
Hello,
I use custom styles on my WordPress, but I have a problem with the Text Block module since the last (or before last) update.
The WYSIWYG editor does not show the tools and text. (see screenshots below)

Here is the code that generates the bug:
```
add_filter( 'tiny_mce_before_init', 'fb_mce_before_init' );
function fb_mce_before_init( $settings ) {
	$style_formats = array(
		array(
			'title' => 'Majuscule',
			'block' => 'p',
			'classes' => 'uppercase'
		),
	);
	$settings['style_formats'] = json_encode( $style_formats );
	return $settings;
}
```
**With the code**
![with-code](https://cloud.githubusercontent.com/assets/8545547/16650203/46f75292-443d-11e6-8d58-a65ff1f624fe.jpg)

**Without the code**
![without-code](https://cloud.githubusercontent.com/assets/8545547/16650204/46fa832c-443d-11e6-8290-88875fca5385.jpg)

Thanks in advance!

**Comment by moldcraft** [comment]
Reproduced

**Comment by andreiglingeanu** [comment]
On it.

**Comment by moldcraft** [comment]
@andreiglingeanu There are other tinymce parameters that can be set https://www.tinymce.com/docs/configure/content-formatting/
I think we should add a general way to handle them or add them to a hardcoded list and process each.

**Comment by andreiglingeanu** [comment]
[That's once again JSON parsing error.](https://cloud.githubusercontent.com/assets/2979628/16651711/7e03b602-444e-11e6-925d-0e37392aa965.png)

**Comment by andreiglingeanu** [comment]
@meneldil How I can check that this `style_formats` was applied correctly?

**Comment by andreiglingeanu** [comment]
651bebc2707ca9727d618c9eb366ba209ab814ab

**Comment by meneldil** [comment]
@andreiglingeanu Normally, this format appears in the WYSIWYG editor. (Pages and posts)

![ui](https://cloud.githubusercontent.com/assets/8545547/16652881/b3592b80-444d-11e6-9e66-b863b553b55e.jpg)

I forgot to also put the first part of the code that displays this list:
```
add_filter('mce_buttons_2', 'my_mce_buttons_2');
function my_mce_buttons_2( $buttons ) {
	array_unshift( $buttons, 'styleselect' );
	return $buttons;
}
```

**Comment by andreiglingeanu** [comment]
[Yes, it works now.](https://i.imgur.com/gk3dZwm.png). Please check it.

**Comment by meneldil** [comment]
I forgot to mention that the problem happens in Text Block's popup. ;)

**Comment by andreiglingeanu** [comment]
@meneldil [There you go.](https://i.imgur.com/uic3HN3.png).

**Comment by meneldil** [comment]
Great! :D
Thank you. I'm looking forward that the plugin is updated on WordPress. :)
