### ISSUE TITLE
[BUG] Shortcodes extension missing in the Unyson panel?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#174]
I just installed the latest version today for a look around. 

I installed it on a test dev with WP 4.1, first time I see Shorcodes extension in the list, but ignore it, then Download some other extension (for fun) and Shortcodes extension dissapears from the list.

I tried reinstalling the plugin and still no Shortcodes extension in the list.

Unyson version 2.1.17

I really think this is a bug.

**Comment by thednp** [comment]
I believe that shortcodes have been included into the page builder and does not count as a separate extension anymore.

**Comment by rockalife** [comment]
Hi @thednp,

It is strange indeed because the Shortcodes extension should not appear in the extensions list (it has a [special setting](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/manifest.php#L5) which makes it hidden in that list), so if you really mean that the Shortcodes (not the Page Builder) extension has disappeared then the real question is why did it appear in the first place.
I can't reproduce this, the Shortcodes extension does not appear in the extensions list on my installation.

**Comment by MoBadawy** [comment]
I think he was taking about this https://trello.com/c/CX8emlPS/50-shortcodes

**Comment by thednp** [comment]
Perhaps a silent quick update changed my code right after the first install, and yes @MoBadawy is right, I am also not seeing any Unyson Shortcodes in my edit page.

**Comment by rockalife** [comment]
@thednp, this functionality has been [released](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/releases/tag/v1.3.0) recently, so you try the following steps:

1. Update `Unyson Extensions` from the Updates page.
2. Deactivate and activate the Page Builder extension from the extensions list.
3. See if it has appeared when adding a new page

**Comment by thednp** [comment]
HA! 
I have new updates for Unyson extensions in the updates page, but when deactivating the page builder, the updates page don't show any new updates.

**Comment by moldcraft** [comment]
@thednp the update extension is working only with active extensions. For e.g. if you have installed/downloaded 10 extensions and 3 of them are active, only those 3 will be checked for updates.

**Comment by levan1993** [comment]
private function add_admin_filters() {
		global $tinymce_version;
		if ( version_compare( $tinymce_version[0], 4, ">=" ) ) {
			add_filter( 'mce_buttons', array( $this, '_filter_admin_register_button_menu' ) );
			add_filter( 'mce_external_plugins', array( $this, '_filter_admin_register_tinymce_javascript' ) );
		} else {
			//todo: enquee other js plugins for other tinymce versions ??
		}
		add_filter( 'mce_css', array( $this, '_filter_admin_enquee_editor_styles' ) );
	}

Hi , 
the tinyMce version comparison is causing the problem.
When I updated the page builder extension, the editor shortcode extension was't activated...
I've removed comparison lines and created new page and now it appears in tinyMce panel.

**Comment by thednp** [comment]
I believe it has to do with <a href="https://github.com/ThemeFuse/Unyson/issues/192#issuecomment-71787989">this comment here</a>. Perhaps devs merged shortcodes into page builder, that is my guess, or what I make of it.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/174#issuecomment-71162535
