### ISSUE TITLE
adding html between pagebuilder elements

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1740]
i have header and footer partial templates that i would like to be between the pagebuilder elements. how would i go about doing this?

basically i have a homepage design where the header and navigation sit directly underneath a full page slider element. but other page designs have the header at the very top of the page, therefore i wanted to have the flexibilty to move the header anywhere within the pagebuilder.

my previous solution was to create a pagebuilder header element however this would mean the header element can be dropped into the pagebuilder countless times when it should be only allowed to be in the pagebuilder once.

you previously advised me to add the header and footer settings within {theme}/framework-customizations/theme/options/posts/page.php, however this would mean i would have to apply the settings per page which is not ideal and also it still doesnt give me the choice to where to position the header in the pagebuilder.

i think the most functional solution would be to have the header and footer settings in the general-settings (this could store the view type, colour options, logo, menu) and then each page/post can have the option to select where in the page would they like the header to be positioned. ideally i would need to have a select box that populates all the elements that are currently added into the pagebuilder, and the header will sit under the selected element from the select box.

is this possible and if so then can you advise me on how to do this. i assume there might be a filter that i can use to allow me add html between elements?

**Comment by duongancol** [comment]
Hi, just want to share my experience with this situation 
- Header, footer, slider should be in Page Setting
- Header, Footer setting in Theme Setting/ Customizer, the option here set for all pages and will be overrided by the option in Page setting. 
It'll easier for the user to setup rather than add header, footer to be the page builder. The page-builder should only contain the content of the page. You could check out Avada or other multi-purpose themes. It's almost the same solution.

**Comment by moldcraft** [comment]
> ideally i would need to have a select box that populates all the elements that are currently added into the pagebuilder

PageBuilder elements don't have an unique id, so you can't populate a select with string links to builder elements.

The only solution I see is to populate a select with `0`, `1`, `2`, ... values and that will mean: Place the header

* `0` on top
* `1` after the first builder element
* `2` after the second builder element
* ...

First level builder elements are always sections, so you can add in section `view.php` something like this:

```php
<?php
// display section ... 
?>

<?php
global $my_theme_section_counter;

++$my_theme_section_counter;

if (fw_get_db_post_option(null, 'hader_after') == $my_theme_section_counter) {
    // print header ...
}
?>
```

also first we need to initialize the global variable

```php
add_filter(
    'the_content', 
    '_filter_my_theme_reset_section_counter', 
    10 // before https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/default-filters.php#L421
);
function _filter_my_theme_reset_section_counter($content) {
    global $my_theme_section_counter;
    $my_theme_section_counter = 0;
    return $content;
}
```
