### ISSUE TITLE
fw_term_meta and native term_meta table

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#1745]
Good morning & sorry form my english!!!
a little question....
Unyson store term data into a fw_term_meta table.
Is possible to save data into native term_meta table?

**Comment by moldcraft** [comment]
Hello,

At the moment [no](https://github.com/ThemeFuse/Unyson/blob/v2.5.7/framework/helpers/database.php#L493).

We will fix that soon.
