### ISSUE TITLE
Use multi-select with taxonomy as replacement for taxonomy metabox

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1746]
I'm making a website that uses a lot of custom fields. They appear in a logical order.

One of the custom fields is a multi-select, that I've populated with a custom taxonomy. I would like to use this instead of the standard taxonomy metabox. 

But, when I use the multi-select, it doesn't attach the term to the post. But it saves it in fw-options.

Is there a way to use the multi-select as a replacement for the standard taxonomy metabox, thus attaching terms to posts with the multi-select?

**Comment by moldcraft** [comment]
Hello,

It's not possible.

All Unyson options are saved in one postmeta, that's all they do.

You can hoot to [this action](https://github.com/ThemeFuse/Unyson/blob/v2.5.7/framework/helpers/database.php#L421) and do the attachment.
