### ISSUE TITLE
customising twitter feed

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1748]
hi, how do i go about customising the twitter feed. i have a design where it requires to also display the date of the tweet.

i dont like the process of adding a twitter widget into a sidebar and then drop in the widget sidebar from the page builder.

i would like to add the twitter feed as a page builder element and also display the dates. how can i create a shortcode that will output the twitter feed.

**Comment by moldcraft** [comment]
Hello,

You can create a shortcode for PageBuilder like this http://manual.unyson.io/en/latest/extension/shortcodes/index.html#creating-a-new-shortcode

The actual process of pulling, storing and rendering the tweets is not related to Unyson, it is related to your php skills.

**Comment by ahm-3d** [comment]
i know how to create a shortcode for a pagebuilder. i am trying to utilise the twitter feed widget that already comes with unyson but i wanted to add it as a shortcode and not a widget.

creating a twitter feed using php is not the problem, i just dont want to build something that already exists but rather utilise what is already included in the plugin.

Anyways nevermind, i realised that the twitter feed widget was actually included in the scratch theme, so i've removed it as a widget and incorporated it as a shortcode
