### ISSUE TITLE
wp-editor error with tiny_mce_before_init filter

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#1749]
I'm receiving an error with all wp-editors when using the "tiny_mce_before_init" to add custom style formats to the visual editor. This just started happening recently.

I setup my filter like this:

```
if( !function_exists('focus_wysiwyg_styles') ) {
function focus_wysiwyg_styles( $settings ) {
	
	// Create array of new styles
	$new_styles = array(
		array(
			'title'	=> __( 'Custom Styles', 'focus' ),
			'items'	=> array(
				array(
					'title' => '.widget-title',
					'selector' => 'h1, h2, h3, h4, h5, h6',
					'classes'	=> 'widget-title'
				),
			),
		),
		array(
			'title'	=> __( 'Custom Margins', 'focus' ),
			'items'	=> array(
				array(
					'title' => '.no-margin',
					'selector' => 'h1, h2, h3, h4, h5, h6, p, ul, ol',
					'classes'	=> 'no-margin'
				),
				array(
					'title' => '.small-margin',
					'selector' => 'h1, h2, h3, h4, h5, h6, p, ul, ol',
					'classes'	=> 'small-margin'
				),
			),
		),
	);

	// Merge old & new styles
	$settings['style_formats_merge'] = true;

	// Add new styles
	$settings['style_formats'] = json_encode( $new_styles );

	// Return New Settings
	return $settings;
}
}
add_filter( 'tiny_mce_before_init', 'focus_wysiwyg_styles' ); 
```

And here is the error I receive in the dashboard:
```

scripts.js?ver=2.5.7:97
wp-editor init error fw_wp_editor_a52873ce16686139c9c3c605e6497ef8 TypeError: Cannot create property 'name' on string '[{"title":"Custom Styles","items":[{"title":".widget-title","selector":"h1, h2, h3, h4, h5, h6","classes":"widget-title"}]},{"title":"Custom Margins","items":[{"title":".no-margin","selector":"h1, h2, h3, h4, h5, h6, p, ul, ol","classes":"no-margin"},{"title":".small-margin","selector":"h1, h2, h3, h4, h5, h6, p, ul, ol","classes":"small-margin"}]}]'
```

Thanks for the help!

**Comment by meta4creations** [comment]
I am also noticing the following error when adding a wp-editor to the Theme Settings options (even without the "tiny_mce_before_init" filter being used.

`Notice: Undefined index: external_plugins in /Users/joeanderson/Sites/watermark/focusrealestate/wp-content/plugins/unyson/framework/includes/option-types/wp-editor/includes/class-fw-wp-editor-settings.php on line 213`

**Comment by moldcraft** [comment]
Hello,

Please test [this version](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/232) and check if this problem is fixed.

**Comment by eyeswizard** [comment]
also i have the same error

`Notice: Undefined index: external_plugins in /Users/joeanderson/Sites/watermark/focusrealestate/wp-content/plugins/unyson/framework/includes/option-types/wp-editor/includes/class-fw-wp-editor-settings.php on line 213`

i'm using unyson 2.5.7 with wordpress 4.5.3
i'm using the unyson as a plugin
but when i integrate it in the theme the error disappears

**Comment by andreiglingeanu** [comment]
@meta4creations Could you please test one more time, with latest master unyson? Let me know if you need some assistance with this.

**Comment by andreiglingeanu** [comment]
Please re-open if it persists.

**Comment by moldcraft** [comment]
Please test again https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/232

**Comment by meta4creations** [comment]
Thanks! That seems to have resolved the issue.

**Comment by andreiglingeanu** [comment]
Welcome.

**Comment by meta4creations** [comment]
Using **tiny_mce_before_init** to add Custom Styles no longer seems to work at all now. My custom styles dropdown show up when using the normal WP editor, but nothing shows within a Unyson wp-editor.

**Comment by andreiglingeanu** [comment]
@meta4creations Please create a new issue with reproduction steps.

**Comment by meta4creations** [comment]
Thanks, I have created a new issue here #1932
