### ISSUE TITLE
[Question] How can I hook a custom action when saving theme options?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#175]
I am basically thinking how to hook a PHP.LESS compiler when theme options are saved. I already have this done for other framework, but since I wish to learn about your framework I need to know this before I start developing.

Thanks so much.

**Comment by moldcraft** [comment]
Us the [`fw_settings_form_saved`](https://github.com/ThemeFuse/Unyson/blob/af0f72ad19d22eb0b9a3de452b6444d4d0da106a/framework/core/components/backend.php#L907) action

**Comment by thednp** [comment]
Thank you so much. Will it wait for my action to complete before showing "Saving complete"?

**Comment by moldcraft** [comment]
It works like this:
* Save the options
* Add message in `$_SESSION`
* Fire the action
* Refresh the page
* Show the message from `$_SESSION`
* Remove the message from `$_SESSION`
