### ISSUE TITLE
[question] how to find the first section of a page builder built page?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1750]
I need a `padding-top` only for the first section of a page and I don't know how to change the section view in order to do that.

Thanks for any suggestion.

**Comment by moldcraft** [comment]
Hello,

There is no way to find that. All shortcodes are rendered independently by WordPress, PageBuilder just generates `[shortcodes]` from `[{builder:'json'}]` and feeds the generated string to WordPress shortcode parser.

You can try to use a global variable like [here](https://github.com/ThemeFuse/Unyson/issues/1740#issuecomment-231343167):

1. Add a filter to reset the global variable before shortcodes render

    ```php
    add_filter(
        'the_content', 
        '_filter_my_theme_reset_section_counter', 
        10 // before https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/default-filters.php#L421
    );
    function _filter_my_theme_reset_section_counter($content) {
        global $my_theme_section_counter;
        $my_theme_section_counter = 0;
        return $content;
    }
    ```

2. Use the variable in section `view.php`

    ```php
    global $my_theme_section_counter;

    if (0 === $my_theme_section_counter++) {
        // this is the first section
    }
    ```

----

Why can't you do from css:

```css
.fw-page-builder-content > section:first-child {
    ...
}
```

?

**Comment by thednp** [comment]
I'm looking for a rock solid cross browser supported solution, so I will try your code asap.

Thank you so much.

**Comment by moldcraft** [comment]
I think [`:first-child` is supported in all browsers](http://caniuse.com/#feat=css-sel2)

**Comment by thednp** [comment]
I do most of the things via PHP with `.first {}` and `.last {}` but I think I can make an exception since in my case it's not about `border-radius` or other CSS3 stuff.

Thank you for your time.
