### ISSUE TITLE
issue with the addable-box and wp-editor

### ISSUE THREAD

**Issue by eyeswizard** [ThemeFuse/Unyson#1752]
hello, i'm facing some issues with the addable-box field and wp-editor

addable-box: 
when i press the add button it give me this error in the console: 
`scripts.js?ver=2.5.7:260 Uncaught ReferenceError: fwWpEditorRefreshIds is not defined`
also i see a white space like the space of the working box
see : http://i.imgur.com/z0ZBmbH.png

wp-editor : 
the editor is working fine but there is an error : `Notice: Undefined index: external_plugins in C:\xampp\htdocs\window\wp-content\plugins\unyson\framework\includes\option-types\wp-editor\includes\class-fw-wp-editor-settings.php on line 213`

see: http://i.imgur.com/hqkZfxr.png

i'm working on unyson version 2.5.7 with wordpress 4.5.3
i can give you the access info for an online version so you can check the errors.

notice : the unyson version 2.5.6 is working fine at all

**Comment by eyeswizard** [comment]
**UPDATE**
i downloaded unyson v2.5.8 from https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/232

the addable-box is now working fine but the wp-editor still displaying the error

**Comment by andreiglingeanu** [comment]
@eyeswizard Fixed by b300d2d378f9dbef5ab3390a8cb3b21639880d04.

**Comment by moldcraft** [comment]
Please test again https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/232

**Comment by eyeswizard** [comment]
Thanks you 
I will test it and let you know the results

**Comment by eyeswizard** [comment]
Thank you
all errors Solved

but what about the new field icon-v2
is there is a documentation for this field?

also when i try to activate it, this message appears : `Undefined option type: icon-v2`

this is a screen shot from my code:
![code](http://i.imgur.com/c6wwyp2.png)

**Comment by andreiglingeanu** [comment]
I'll be adding a documentation entry for `icon-v2` soon. Will ping here about it. In the mean time you inspect the code for yourself, it is not that hard.

**Comment by andreiglingeanu** [comment]
You also probably want to uncomment this option type from `framework/includes/option-types/init.php`.

**Comment by eyeswizard** [comment]
Thank you @andreiglingeanu :+1:
