### ISSUE TITLE
[question/issue] I'm not using any icon-v2 option but all the CSS files loaded in front-end

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1753]
Isn't [this here](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon-v2/class-fw-option-type-icon-v2.php#L31) supposed to be like this?

```php
if (is_admin()) {
  $this->packs_loader->enqueue_admin_css();
}
```

The above doesn't work, unfortunately, but I really want to know how to stop loading those fonts. I already use my own font icon option type and own CSS.

**Comment by eyeswizard** [comment]
i need to know the documentation of this field

**Comment by moldcraft** [comment]
[This](https://github.com/ThemeFuse/Unyson/blob/v2.5.8/framework/includes/option-types/icon-v2/class-fw-option-type-icon-v2.php#L24-L27) should be removed. Users should enqueue the style manually.

Builder required grid css is not enqueued on all pages, [just registered](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/v1.2.3/static.php#L4), then other scripts do `wp_enqueue_style('fw-ext-builder-frontend-grid');` when it is needed.

**Comment by thednp** [comment]
> Builder required grid css is not enqueued on all pages, just registered, then other scripts do `wp_enqueue_style('fw-ext-builder-frontend-grid');` when it is needed.

Oh I wish all themes and plugins would have such a nice functionality.

**Comment by andreiglingeanu** [comment]
@thednp WIll fix today.

**Comment by andreiglingeanu** [comment]
Use this in order to enqueue css in frontend, in your own theme:

```php
fw()->backend->option_type('icon-v2')->packs_loader->enqueue_frontend_css();
```

**Comment by thednp** [comment]
Thanks, will remember that.

**Comment by andreiglingeanu** [comment]
@thednp Welcome.
