### ISSUE TITLE
Fatal error: Out of memory 

### ISSUE THREAD

**Issue by themeheap** [ThemeFuse/Unyson#1754]
Getting following error on plugin activation:
Fatal error: Out of memory (allocated 821035008) (tried to allocate 72 bytes) in /home/clients/websites/w_legal/public_html/legal/wp-content/plugins/unyson/framework/helpers/class-fw-cache.php on line 256

**Comment by moldcraft** [comment]
Please enable a default WP theme and check if error persists.

Which theme are you using?

**Comment by thednp** [comment]
I wonder could this happen on some server because of too many theme setting options?

**Comment by themeheap** [comment]
Yes, it seems to be due to many theme setting options.

**Comment by themeheap** [comment]
@moldcraft , It is not crashing with default theme

**Comment by danyj** [comment]
@themeheap   what theme are you using, they might have just pulled some theme settings in theme option via 

`fw_get_db_settings_option 
`
and forgot default values

**Comment by danyj** [comment]
and that 820MB +   so there is definitely a recursion going on.

**Comment by danyj** [comment]
@thednp   

> because of too many theme setting options


I have jet to see that ,  I am sure I top everyone who is using Unyson  in the amount of options in theme settings  (200KB in data size , 350+ options and counting  ) and so far have not seen server timeout becuase of the amount .  Have one ajax issue in getting the 200KB pass trough on lightspeed but that seems like server restriction .  Other than that ,  normal theme settings load.

**Comment by themeheap** [comment]
Actually, we have develop a theme with UNYSON. and facing this issue. trying to resolve it. 
Following is the code, which is causing the issue. We are setting mail chimp key in the input field then we are using key to fetch the mailing lists. 
What approach should we use to do this?

```
   function law_firm_mailchimp_list() {
        $mailchimp_list[]  = '';
        $mailchimp_list[0] = 'Select List';
        $mailchimp_option  = '';
        if (!function_exists('fw_get_db_settings_option')) {
            $mailchimp_option = '';
        } else {
            $default_value    = 'e12c8ee5546cf3134b83f02b8b12702e-us11';
            $mailchimp_option = fw_get_db_settings_option('mailchimp_key' , $default_value);
            if (isset($mailchimp_option) && !empty($mailchimp_option)) {
                $mailchimp_option = $mailchimp_option;
            } else {
                $mailchimp_option = '';
            }
        }
        if ($mailchimp_option <> '') {
            $mailchim_obj = new law_firm_MailChimp();
            $lists        = $mailchim_obj->law_firm_mailchimp_list($mailchimp_option);
            if (is_array($lists) && isset($lists['data'])) {
                foreach ($lists['data'] as $list) {
                    if (!empty($list['name'])) :
                        $mailchimp_list[$list['id']] = $list['name'];
                    endif;
                }
            }
        }
        return $mailchimp_list;
    }
```

**Comment by danyj** [comment]
you do see that   

 $default_value

var is nowhere defined right? 


this snipp is familiar , I think is from someone else here with exact same issue

**Comment by themeheap** [comment]
It is defined: `$default_value    = 'e12c8ee5546cf3134b83f02b8b12702e-us11';`

**Comment by danyj** [comment]
@themeheap   saw it afterwards,

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/912

**Comment by ansfazi** [comment]
But default value is being passed in my case.

> 
> fw_get_db_settings_option('mailchimp_key', $default_value);
> $default_value will be returned if there is no db value. If default value is not specified, it will extract default value from options file, causing an infinite recursion because in options file it is called that function.

**Comment by ansfazi** [comment]
But in my case, default_value is being passed:

> fw_get_db_settings_option('mailchimp_key', $default_value);
> $default_value will be returned if there is no db value. If default value is not specified, it will extract default value from options file, causing an infinite recursion because in options file it is called that function.

**Comment by thednp** [comment]
@danyj my theme options folder currently at 138kb in size, but I'm doing less compilation on theme options save with 150+ LESS variables and 3 files written on save (LTR, RTL, ie9-) soI am a bit concerned about the memory limit.

**Comment by moldcraft** [comment]
@thednp We at ThemeFuse have a lot of problems with less compilation because most users use cheap shared hosting plans which have many limitations, including memory limit.

**Comment by thednp** [comment]
So the best content development environment is still localhost.

**Comment by moldcraft** [comment]
@themeheap 

I added in `{theme}/functions.php` this code

```php
function law_firm_mailchimp_list() {
	$mailchimp_list[]  = '';
	$mailchimp_list[0] = 'Select List';
	$mailchimp_option  = '';
	if (!function_exists('fw_get_db_settings_option')) {
		$mailchimp_option = '';
	} else {
		$default_value    = 'e12c8ee5546cf3134b83f02b8b12702e-us11';
		$mailchimp_option = fw_get_db_settings_option('mailchimp_key' , $default_value);
		if (isset($mailchimp_option) && !empty($mailchimp_option)) {
			$mailchimp_option = $mailchimp_option;
		} else {
			$mailchimp_option = '';
		}
	}
	/*if ($mailchimp_option <> '') {
		$mailchim_obj = new law_firm_MailChimp(); // I don't have this class
		$lists        = $mailchim_obj->law_firm_mailchimp_list($mailchimp_option);
		if (is_array($lists) && isset($lists['data'])) {
			foreach ($lists['data'] as $list) {
				if (!empty($list['name'])) :
					$mailchimp_list[$list['id']] = $list['name'];
				endif;
			}
		}
	}*/
	return $mailchimp_list;
}

add_action('admin_notices', function(){
	fw_print(law_firm_mailchimp_list());
});
```

and it shows

```
array
(
    [0] => 'Select List'
)
```

**Comment by moldcraft** [comment]
Please send me admin/ftp details to `moldcraft[at]email.com` and I will inspect the code.

**Comment by thednp** [comment]
@themeheap what was the solution?

**Comment by themeheap** [comment]
I guess, it was issue with the default value, 
Can you have a look at another issue https://github.com/ThemeFuse/Unyson/issues/2145
