### ISSUE TITLE
Visual Builder Template

### ISSUE THREAD

**Issue by christinanahanni** [ThemeFuse/Unyson#1755]
Hello. My website has been operational for approximately four years, but I recently did a big update and began using Unyson, and the template theme 'Philanthropy'. As such, I am new to using the Visual Builder Template and was using the Default Editor before. I have found the Visual Builder Template easy to use thus far in terms of creating content, however, I am having difficulty publishing what I have built. I have created a slider and added my content, but when I go to 'update' or 'preview changes', the page appears blank. 
I am running this for a non-profit organization, and we are heavily reliant upon the website to gather donations. So any help would be very appreciated! 

<img width="1083" alt="screen shot 2016-07-10 at 11 49 26 am" src="https://cloud.githubusercontent.com/assets/20380435/16712870/9855635a-4694-11e6-865c-971f2be90173.png">
<img width="1197" alt="screen shot 2016-07-10 at 11 50 28 am" src="https://cloud.githubusercontent.com/assets/20380435/16712871/9cea4e62-4694-11e6-8ea2-bff5a24c2a1f.png">

**Comment by moldcraft** [comment]
Hello,

If you use the `get_post()` function, please switch to [`get_posts()`](https://github.com/ThemeFuse/Unyson/issues/1549#issuecomment-219377267) or use [this function](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.3/helpers.php#L41)
