### ISSUE TITLE
[BUG] Video embed shortcode script not supported in IE8

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1757]
The console error log:
```
SCRIPT438: Object doesn't support property or method 'forEach'
File: scripts.js, Line: 94, Column: 3
```

I don't do very much to support old browsers but at least make sure JS doesn't mess around, so I would suggest including a `forEach` polyfill or rewrite the script with a simple `for ()` loop (it's what I always do).

Here's a cool and simple polyfill
```javascript
if (typeof Array.prototype.forEach != 'function') {
    Array.prototype.forEach = function(callback){
      for (var i = 0; i < this.length; i++){
        callback.apply(this, [this[i], i, this]);
      }
    };
}
```

UPDATE: adding the polyfill didn't fix the issue, it seems the embed code is trying to get the page id and also fails there, perhaps that's the final verdict, but I leave this to you to decide if this is important or not.

**Comment by danyj** [comment]
who ever asks about it , send them here 
https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by thednp** [comment]
Yea, I guess I will replace all stuff with a link to video when detected browser is older.
