### ISSUE TITLE
[Question] Can the containers be repeatable?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#176]
I am thinking about being able to add multiple options inside a group. I need to know if the group can be repeatable and posibility to duplicate.

Thanks again.

**Comment by moldcraft** [comment]
The group does not affect option ids. If you duplicate a group, you have to change the inner options ids.

**Comment by thednp** [comment]
I think you didn't get it because my question sounds quite vague. 

Here's a more detailed example:
* I have a CPT with some "child items" that are manageable in a metabox options group.
* I need this group to behave like a page builder element.

NOTE: Just like with pagebuilder elements (can be added/duplicate existing element, etc). 

I hope you get a better picture this time.

**Comment by moldcraft** [comment]
Try the [Addable Box](http://manual.unyson.io/en/latest/options/built-in-option-types.html#addable-box) option type, I think it may match what you described. Unfortunately it doesn't have the "duplicate" feature.

P.S. What is CPT?

**Comment by thednp** [comment]
Thanks. I believe I can achieve it with an override and use some code from the page builder. Anyways, I think this would be a great feature to consider implementing, there aren't many frameworks that can do this.

CPT stands for custom post type.

I think I will migrate to your framework after all, not because great support, but because the code, it's so valuable.

Thanks again.

**Comment by moldcraft** [comment]
You are welcome
