### ISSUE TITLE
Typography v2 problem with default fonts

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#1764]
Hi there,

When using Typography v2 it's possible to select a whole bunch of Google Fonts, but there are also some fonts that are considered as 'safe'. These fonts include Arial Black, Helvetica and Calibri. 

The problem is that not every device has these fonts. Per example, a iOS device doesn't include fonts like Arial Black or Calibri. 

I'm not sure how to handle these fonts. Is it possible to disable them or is there some kind of fallback so these devices use a reasonable font?

**Comment by moldcraft** [comment]
[There is a filter](https://github.com/ThemeFuse/Unyson/blob/v2.5.9/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php#L56)
