### ISSUE TITLE
Event extension edit page tabs and options mess. Help me remove hard coded fw-option-box 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1765]
@moldcraft  I am not sure why this is done this way but the events extension does not match  Unyson coding patterns at all. 

To add   custom options to the events we must use hooks like 

    fw_ext_events_post_options

where fw-portfolio , blog , page and all other standard unyson edit pages use MVC ,  

now the events extension also has the MVC option witch lets me add  own options set with tabs 

via ,   

       framework/theme\options/posts/fw-event.php   

file  but it places my tabs above  the Events options box  . 

Than I thought that I can simply remove the hard coded extension tab with this 

```
function _thz_filter_fw_ext_events_post_options( $event_options = array() ){

	return false;

}
add_filter("fw_ext_events_post_options", "_thz_filter_fw_ext_events_post_options");
```

 , but no , since it leaves an empty fw-option-box 

http://prntscr.com/brwg8w

can we please get this extension on the same page as Unyson instead of making things up as we go. 
Please help me remove the hardcoded options box and let me work with 

`framework/theme\options/posts/fw-event.php  ` 

file instead.

**Comment by moldcraft** [comment]
> the events extension does not match Unyson coding patterns at all

It was created by a new developer which worked a few months then left.

**Comment by danyj** [comment]
@moldcraft , I figured  that much , hope you know that this was not me pointing at your work. Was merely a suggestion to "fix" the issue.
