### ISSUE TITLE
Contact form not working 

### ISSUE THREAD

**Issue by Jo-lumina** [ThemeFuse/Unyson#1766]
Hi there, 
I'm relatively new to word press in general, I've gotten on well with Unyson in building my first site but I can not figure out what's wrong with my contact form, 

I've googled it to no prevail so here I am. 

I've checked every setting in the editor, tried both wp-mail and STMP for the mailer options, neither work, I constantly get the 'oops something went wrong' when I test the form. 

Any advice? 

Here's the page with the form on:  http://foreveryoursfilms.co.uk/?page_id=2519

Thank you!

**Comment by thednp** [comment]
This is not the place for customer support, here's a public development site. 

You should contact the author via Themeforest provided chanels.

**Comment by moldcraft** [comment]
Please open `wp-content/plugins/unyson/framework/extensions/mailer/includes/send-methods/class-fw-ext-mailer-send-method-smtp.php`, uncomment [this line](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/v1.2.5/includes/send-methods/class-fw-ext-mailer-send-method-smtp.php#L173), set your form to SMTP and try to send a message. It should output debug information why the messages was not sent.

**Comment by Jo-lumina** [comment]
Hi, 

I've done as you've instructed and all I get it 'Oops something went wrong. Could not send the email'

The Could not send email is the transparent message you mentioned in another thread. No other debug info to be seen.

Thanks, 
Jo

**Comment by Jo-lumina** [comment]
Feeling rather proud right now from having solved this after days of trying! Posting the fix here for others in the same boat. 

I ended up using the Gmail SMTP plug in - https://wordpress.org/plugins/gmail-smtp/ 

Going through authentication instructions here  -  http://www.wpbeginner.com/plugins/how-to-send-email-in-wordpress-using-the-gmail-smtp-server/

and setting the mailer to wp-mail rather than SMTP on the form settings. 

Hey presto, now it works. 

Thanks for the support :+1:
