### ISSUE TITLE
wp_add_inline_script() was added in WP 4.5.0

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1767]
We must support [WP 4.3](https://github.com/ThemeFuse/Unyson/blob/v2.5.8/readme.txt#L4) so [this function](https://github.com/ThemeFuse/Unyson/blob/v2.5.8/framework/core/components/backend.php#L457-L460) must be removed.

https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/functions.wp-scripts.php#L96

**Comment by andreiglingeanu** [comment]
@moldcraft Damn it, we should change dynamic CSS behavior for shortcodes.

**Comment by andreiglingeanu** [comment]
@moldcraft I was wrong. This [one](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/functions.wp-styles.php#L77) was added much earlier.
