### ISSUE TITLE
row and columns

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#1768]
I put 8 columns ( fw-col-4 ) in a section, but the framework close a row every 3 columns. how can I avoid this? i need only one row with 8 columns inside

**Comment by moldcraft** [comment]
[This parameter](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/config.php#L35) will be available in [next PageBuilder extension release](https://github.com/ThemeFuse/Unyson-Extensions-Approval).
