### ISSUE TITLE
[Suggestion] Improve the Unyson Extensions page

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#177]
Have it capable to install/activate/deactivate/remove multiple extensions at once with user selection.

I also noticed it may reach the server response time limit when all extensions are being installed.

**Comment by moldcraft** [comment]
> Have it capable to install/activate/deactivate/remove multiple extensions at once with user selection.

Can you give us an idea of how it should look like (a screenshot or [a mock](http://ninjamock.com/)) ?

> I also noticed it may reach the server response time limit when all extensions are being installed.

Ok, we will add

```php
set_time_limit(
    ini_get('max_execution_time') + $extensionsCount * 10
);
```

**Comment by thednp** [comment]
OK. Here some ideas:

1. Give the user the option to switch list/gird view
2. Simply give those boxes some checkbox, and below the list/grid some buttons Download | Download & Activate
3. For the active extensions list also some checkboxes and buttons Disable | Delete

**Comment by sergiubagrin** [comment]
Hi @thednp,

Q: Give the user the option to switch list/gird view Simply give those boxes some checkbox, and below the list/grid some buttons Download | Download & Activate For the active extensions list also some checkboxes and buttons Disable | Delete
A: Thank for suggestion i add it to review list. 

Q: Think about the end user who's gonna have to install 5 theme extensions and 5 core framework extensions. It's a bit annoying, so make it more friendly.
A: If this theme was created for Unyson all those extensions will be installed automatically with Theme Install. 

Thanks

**Comment by thednp** [comment]
Alright, sounds interesting.
