### ISSUE TITLE
Demo will not install Always "times Out

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1774]
I am trying to install the demo data but it keeps timing out.

**Comment by moldcraft** [comment]
The only way to find you what happens is to ask the hosting support to give you the error.log, or to try `register_shutdown_function()` to catch the error message.

P.S. https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/21

**Comment by moldcraft** [comment]
Try to install latest dev version of Backups extension from Github, it contains this fix https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/fc0e7261bda612f66c860e82628088b8b9aec8b5
