### ISSUE TITLE
Template redirect if page uses the builder

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1776]
Is there any way to use specific page template if the page uses page builder?
I can do it using page template drop down .But I want it to be done automatically. If page uses builder then use this template if not then use general one .

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/573#issuecomment-117331120

On [templates select](https://static.md/22be3dce6927aca91398833e8555493f.png) change, if the selected template supports page-builder, the builder will be enabled, else will be disabled. When the builder is enabled manually (clicked on "Visual Page Builder" button) the select value will be changed to firs template that supports builder.

To specify templates that support page-builder, use [this filter](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/54855dffc8470dec8af6fc2346a91e7400ecd172/includes/fw-option-type-page-builder/class-fw-option-type-page-builder.php#L73-L75).

If there are no templates specified, this feature will be disabled (so it is disabled by default).
