### ISSUE TITLE
Are we still having issues with wp-editor option type? 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1777]
@moldcraft  @andreiglingeanu  Updated to latest master just now but the editor is buggy 

http://prntscr.com/bsj9gi

**Comment by andreiglingeanu** [comment]
@danyj That's in `wp.OptionsModal`? Give me reproduction steps please.

**Comment by andreiglingeanu** [comment]
@moldcraft It looks like our [trick](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/wp-editor/includes/class-fw-wp-editor-settings.php#L221) doesn't work very well.

**Comment by danyj** [comment]
@andreiglingeanu  it is a wp-editor inside a special heading builder shortcode, nothing special about it 


			'heading' => array(
				'type' => 'wp-editor',
				'tinymce' => true,
				'size' => 'large',
				'reinit' => true,
				'wpautop' => false,
				'editor_height' => 100,
				'editor_type' => 'html',
				'value' => 'This is dummy heading text',
				'label' => __('Heading', 'fw'),
				'desc' => __('Add heading text', 'fw')
			),

**Comment by andreiglingeanu** [comment]
@danyj Can't reproduce your problem. Please do the following steps:

1. Get to the phase where you got your error (open your shortcode) - Please in Chrome or Chrome Canary!
2. Make sure it doesn't work correctly
3. Open JS console and check the error
4. Run the code `copy(copy(tinyMCEPreInit.mceInit)` in console
5. Paste the output in a `gist.github.com`

**Comment by danyj** [comment]
@andreiglingeanu  https://gist.github.com/danyj/fcc8cc8d2681520695e8ee150cf55168


http://take.ms/xRehn

**Comment by andreiglingeanu** [comment]
Solution: Update or delete [Unyson-WP-Shortcodes-Extension](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension).
