### ISSUE TITLE
page builder for events and other post types

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1778]
Hi,

i have been using the scratch theme as base for building my own theme.
i love unyson's versatility that i have introduced this to my development team as the ultimate web development framework.
the principle of what i am trying to achieve is to create page builder elements so a non developer can build a website without having to write a single code.
that in mind, i have already created a header and a footer page builder elements that offer a variety of views. these can be saved as template and used across other pages.

i am currently trying to utilise the events and blog extensions to fit in with what i am trying to achieve.

the default events and blog extensions output their content above the page builder elements. is there away i can specify a placeholder within the page builder to populate the content of the event and blog post. My immediate thought is that i would need to create another page builder element via shortcodes that will pull the data that i have added in the event and blog post. Is this the case or is there already a built in solution to achieve this. any thoughts or advise would be much appreciated.

Also if i was to go down the shortcode route, is there away to display the available shortcodes for each post type. i.e. i want the "show event data" shortcode to be only available to event custom post types.

i have attached a screenshot hoping it would give you a better understanding of what i am trying to do.
<img width="1440" alt="screen shot 2016-07-13 at 21 35 40" src="https://cloud.githubusercontent.com/assets/9349172/16818941/13a66d42-4942-11e6-8867-6420fbab95df.png">

**Comment by thednp** [comment]
The best thing you can do (at least what I think it would be) is to reproduce &/or understand the contact form extension, it's an extension/merge of two extensions: `builder` and `mailer`.

Or simply create metaboxes, via Unyson you just create settings specific to `events` post type.

**Comment by moldcraft** [comment]
Hello

> or is there already a built in solution to achieve this

&nbsp;

> is there away to display the available shortcodes for each post type. i.e. i want the "show event data" shortcode to be only available to event custom post types.

Nope

----

Sorry, I can't give you a solution at the moment. I will leave this issue open and we will fix it someday.

You can try to inspect the problem your self and maybe find a solution (and create a pull request).

**Comment by ahm-3d** [comment]
i managed to determine which shortcodes can be used by adding in the following condition into the shortcodes/shortcodes/hooks.php:

```
$post_type = (isset($_GET['post_type']) ? $_GET['post_type'] : (isset($_GET['post']) ? get_post_type($_GET['post']) : 'post'));

if('page' === $post_type){
$to_disable[] = 'event_location';
$to_disable[] = 'event_schedule';
}

if('post' === $post_type){
$to_disable[] = 'event_location';
$to_disable[] = 'event_schedule';
}

if('fw-event' === $post_type){
}
```

i think by establishing the condition above, the easiest solution would be to create page builder elements under a new tab called 'Events Elements', 'Post Elements' etc... to be displayed on their respective post type and these will display the data entered within meta boxes and positioned anywhere within the page builder
