### ISSUE TITLE
Invalid options warning latest master

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1779]
Just downloaded master and getting these 2 on homepage 

Warning: Invalid option: post in D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\general.php on line 888

Warning: Invalid option: fw-slider in D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\general.php on line 888

note I have no options by name post or fw-slider 
points to 

https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/general.php#L888

**Comment by moldcraft** [comment]
Please add after [this line](https://github.com/ThemeFuse/Unyson/blob/45736d1c266b0113aaee866545ff637c94e0428b/framework/helpers/general.php#L888)

```php
echo '<pre>'; debug_print_backtrace(); echo '</pre>';
```

**Comment by danyj** [comment]
@moldcraft few min

**Comment by danyj** [comment]
@moldcraft  data is huge , it prints out all page, and theme options http://prntscr.com/bskrd6

**Comment by danyj** [comment]
this seems to be bugging only on Frontpage , reading is set as Your latest posts, and blog archives

**Comment by danyj** [comment]
[fw-slider] => Array ())) called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\general.php:593]

digging for post

**Comment by danyj** [comment]
found it ,  had 5  get options without defaults but that check was a miss and did not point to the right option names

**Comment by danyj** [comment]
@moldcraft  OK this is still on going but found different cultrpit now ,  

I am using this 

    fw_get_db_post_option($slider_id)

to get **all** slider options ,  it does let me have them but first it shows the same error 

    unyson/framework/helpers/general.php on line 921
    unyson/framework/helpers/class-fw-db-options-model.php on line 169


I dont know what to pass as option or default value there since I need all slider options in to one variable.

**Comment by danyj** [comment]
Is this ok ?

     fw_get_db_post_option($slider_id,null,array())


it fixes the error but not sure if I should do it this way.

**Comment by danyj** [comment]
nah , that wont do it , is empty
