### ISSUE TITLE
Cannot install Demo Content

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1780]
I’m trying to install demo content for a client of mine and I’m getting the following error:

“Failed to create tmp table _fwbk_wp_commentmeta”. How do I fix it?

Thanks.

**Comment by moldcraft** [comment]
1. Maybe the mysql user set in `wp-config.php` doesn't have the permission to create tables?
2. Can you find a more detailed error message in error.log?

**Comment by jimtyrro** [comment]
That was my question, thank you @Ataurr for posting this for me.

1. WP user has all permissions, I can install/remove/update any plugin or theme except this one (WellnessCenter Beauty Spa WordPress Theme from Themeforest) which is based on your framework.
2. Which error.log should I provide, MySQL? /var/log/mysql/error.log - has no errors.

Which makes me believe there's something either with framework or the way the theme implements Demo Content Installation.

Any ideas how to further troubleshoot it?

**Comment by Ataurr** [comment]
Did you check your apache error.log ?

**Comment by moldcraft** [comment]
@jimtyrro The error happens [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L430-L437), you can replace that code with

```php
if ( false === $wpdb->query( $sql ) ) {
	$fo = null;
	return new WP_Error(
		'tmp_table_create_fail',
		sprintf( __( 'Failed to create tmp table %s', 'fw' ), $tmp_table_name )
		. ' | wpdb->last_error: '. $wpdb->last_error
		. ' | SQL: '. $sql
	);
}
```

**Comment by jimtyrro** [comment]
Thank you for the tip.

Here's the detailed error. 

`Failed to create tmp table _fwbk_wpmu_commentmeta | wpdb->last_error: Unknown storage engine 'InnoDB' | SQL: CREATE TABLE `_fwbk_wpmu_commentmeta` ( `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `comment_id` bigint(20) unsigned NOT NULL DEFAULT '0', `meta_key` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `meta_value` longtext COLLATE utf8_unicode_ci, PRIMARY KEY (`meta_id`), KEY `comment_id` (`comment_id`), KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci`

It looks like your script is trying to create a table using InnoDB engine by default but I do not use it, I exclusively use MyISAM hence the cannot create error. Where should I modify the script to use MyISAM engine instead?

Thanks.

**Comment by moldcraft** [comment]
Add [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L429)

```php
$sql = str_replace('InnoDB', 'MyISAM', $sql);
```

**Comment by jimtyrro** [comment]
Thank you, that fixed it!!

**Comment by ThemeHelp** [comment]
Hi,

I need a little help! I can't get the demo content installed. I have all the plugins except woocommerce installed.

The image has populated under tools - demo contact install.....

But it keeps giving me the following error message:

Failed to create tmp table _fwbk_0d7_media_file_manager_log. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci ROW_FORMAT=DYNAMIC' at line 3

Can you help??

**Comment by sylasfilho** [comment]
> Hi,
> 
> I need a little help! I can't get the demo content installed. I have all the plugins except woocommerce installed.
> 
> The image has populated under tools - demo contact install.....
> 
> But it keeps giving me the following error message:
> 
> Failed to create tmp table _fwbk_0d7_media_file_manager_log. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci ROW_FORMAT=DYNAMIC' at line 3
> 
> Can you help??

Get into the file path wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/ and replace the class-fw-ext-backups-task-type-db-restore.php file using the below file .

File Path : https://www.dropbox.com/s/5mpt6tdt1tpumtp/class-fw-ext-backups-task-type-db-restore.php?dl=0

After that you can import the demo under the tools > demo install

**Comment by junereycasuga** [comment]
Hi, I am having this error. 
>Failed to create tmp table _fwbk_wp_commentmeta. Storage engine MyISAM is disabled (Table creation is disallowed).

We are using a managed database in DigitalOcean and I believe it's using InnoDB

This is the error log
```
WordPress database error Storage engine MyISAM is disabled (Table creation is disallowed). for query CREATE TABLE `_fwbk_wp_commentmeta` (\n`meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, \n`comment_id` bigint(20) unsigned NOT NULL DEFAULT '0', \n`meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL, \n`meta_value` longtext COLLATE utf8mb4_unicode_520_ci, \nPRIMARY KEY (`meta_id`), \nKEY `comment_id` (`comment_id`), \nKEY `meta_key` (`meta_key`(191))) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci made by do_action('wp_ajax_nopriv_fw:ext:backups:continue-pending-task'), WP_Hook->do_action, WP_Hook->apply_filters, _FW_Ext_Backups_Module_Tasks->_action_ajax_continue_pending_task, _FW_Ext_Backups_Module_Tasks->execute_pending_task, FW_Ext_Backups_Task_Type_DB_Restore->execute, FW_Ext_Backups_Task_Type_DB_Restore->do_import, referer: https://heytonic.com/wp-admin/admin-ajax.php
```
