### ISSUE TITLE
Projects and events tags questions

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1783]
@moldcraft   you recently added tags feature for projects , 

https://github.com/ThemeFuse/Unyson-Portfolio-Extension/commit/42a34749de462a52b643d79813ff6ed1cb6dfc14#diff-a8eea449878b7253793f631a46092703R292

```
add_filter( 'fw:ext:portfolio:enable-tags', function(){
	return true;
});
```
and it works ok in backend ,  but I am not getting the tags in front via 

				$tags = wp_get_post_tags(get_the_ID()); 
				fw_print($tags);

and is there  same feature for the Events extension ?

**Comment by moldcraft** [comment]
> I am not getting the tags in front

1. [`wp_get_post_tags()`](https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/post.php#L2882)
2. https://github.com/ThemeFuse/Unyson-Portfolio-Extension/commit/42a34749de462a52b643d79813ff6ed1cb6dfc14#diff-a8eea449878b7253793f631a46092703R11

so

```php
fw_print( 
	wp_get_post_terms( get_the_ID(), 'fw-portfolio-tag' )
);
```

> is there same feature for the Events extension ?

No
