### ISSUE TITLE
Fatal error on admin

### ISSUE THREAD

**Issue by Twbarnes10** [ThemeFuse/Unyson#1784]
Since updating to the latest version of the plugin (2.5.8) we are getting the following fatal error when we log in to the site:

**Fatal error: Call to undefined function wp_add_inline_script() in /home/mbfamgolf/public_html/wp-content/plugins/unyson/framework/core/components/backend.php on line 457**

The live side of the site seems to be doing fine with no errors. We are using The Core theme (version 1.0.2). We see that there is a newer version of the theme available but before we upload it, just wanted to see if this is related to the theme needing updating or if there is another issue at play here.

**Comment by danyj** [comment]
https://make.wordpress.org/core/2016/03/08/enhanced-script-loader-in-wordpress-4-5/

update wordpress

**Comment by Twbarnes10** [comment]
You rock...that did that trick. Thanks for you VERY fast response!

**Comment by danyj** [comment]
@Twbarnes10 , any time. Please close the issue when you ready.
