### ISSUE TITLE
Can't move or delete content blocks. 

### ISSUE THREAD

**Issue by xmartini** [ThemeFuse/Unyson#1788]
I cannot move or delete content blocks. When I move them and save, they are back to how they were originally before I saved. Same goes for when I try deleting content blocks. I've tried deleting the page completely and creating it again but have the same issue. Only have this issue on some pages, others seem to be working fine (for the most part). Just installed latest update but still have the issue.

**Comment by thednp** [comment]
Does your console show any error?

**Comment by xmartini** [comment]
Yea, I'm getting this error when I try to delete a layout element:

Uncaught TypeError: Cannot read property 'remove' of undefined
removeItem @ scripts.js:167
dispatch @ load-scripts.php:3
r.handle @ load-scripts.php:3

Also, it's the layout elements I cannot delete. I _am_ able to delete content elements. My mistake.

**Comment by thednp** [comment]
Does your rendered HTML also have some PHP error dumps or is just a simple JS error in the console?

I suspect your customization/override might be incorrect.

**Comment by xmartini** [comment]
No errors on the rendered page. I just get these errors when trying to edit on the layout build page. 

I don't have any customization's or overrides. It actually seems to be on pages that are children of other pages. Maybe that's causing an issue?

**Comment by thednp** [comment]
I don't know about that, never tested, but perhaps Unyson devs would check that.

I believe @moldcraft will be interested in investigating this.

**Comment by moldcraft** [comment]
Hello

1. Are Unyson extensions up-to-date? (Check Dashboard > Updates page)
2. Activate a default WP theme and check if the problem persists. If not, then it is a theme issue.

**Comment by xmartini** [comment]
Yea, everything is up to date. I believe it's a theme issue as some pages are working just fine. Thank you both for your help.
