### ISSUE TITLE
Feedback comments wrong class name

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1789]
I tested feedback extension comments and than disabled it, 
the feedback comment is still there and its html has different class names from default wp comments 
resulting in unmatched style with his siblings

![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/16893430/f61fb48e-4b37-11e6-8b4c-38eddcaf861a.jpg)

**Comment by moldcraft** [comment]
1. On my side it looks fine 

    ![staticshot_18-07-2016_13-48-31](https://cloud.githubusercontent.com/assets/1475489/16912692/59ca2624-4cee-11e6-937b-9fc8f9b5272d.png)

2. That class is set here https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/comment-template.php#L444

**Comment by moldcraft** [comment]
> I tested feedback extension comments and **than disabled it**

Sorry, missed that step.

**Comment by moldcraft** [comment]
Do you have any suggestion how to fix this?

**Comment by danyj** [comment]
I turned feedback on ,  made a cooment with it , than disabled the feedback extension. 
The comment is there but it has fw- class name instead of default wp comment class names. 

I am not sure what overrides it and why if feedback is disabled I still see its class names.

**Comment by moldcraft** [comment]
That class is [comment_type](https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/comment-template.php#L444) saved in db

**Comment by danyj** [comment]
ok , cant you than use default comment class names and just addon the fw-feedback?

from the image above you see that the class .comment  is missing , thus the issue with the style ,.

**Comment by danyj** [comment]
> Do you have any suggestion how to fix this?

yes just change 

`fw-feedback `

to 

`fw-feedback comment`
