### ISSUE TITLE
Plugin Check Errors

### ISSUE THREAD

**Issue by wpEvents** [ThemeFuse/Unyson#179]
Hello,

First of all I want to Thank you for this great product! It is a wonderful plugin, so easy to use and to configure. My favorite part is how easy it is to adapt it for WordPress themes. Absolutely incredible. :)

If you can fix the errors underlined by Plugin Check plugin it would be wonderful. (I attached a printscreen)

Great work guys!

![unyson-plugin-check](https://cloud.githubusercontent.com/assets/10648135/5850947/016fb662-a207-11e4-9511-40b6482a5728.png)

**Comment by moldcraft** [comment]
We know about them and we explained everything in [`plugin-check-info.md`](https://github.com/ThemeFuse/Unyson/blob/master/plugin-check-info.md).

If there errors that are not specified in `plugin-check-info.md` let us know.
