### ISSUE TITLE
over-ride blog extension

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1791]
Hi,
is there a way to over-ride the blog extension to change from "Blog Posts" to "News Posts"?

**Comment by thednp** [comment]
You can either disable the extension and create another just like it or simply override it.

Here's how to override:
* Copy files from `plugins/unyson/framework/extensions/blog`
* to `yourtheme/framework-customizations/extensions/blog`
* find replace the strings you want
* to create another extension you can do the same process but it should also have a different name. EG. `yourtheme/framework-customizations/extensions/news`

**Comment by ahm-3d** [comment]
i have tried doing the following:

-     Copy files from plugins/unyson/framework/extensions/blog
-     to yourtheme/framework-customizations/extensions/blog
-     find replace the strings you want

but it hasn't worked, any ideas what i could be doing wrong?
<img width="1440" alt="screen shot 2016-07-17 at 17 13 54" src="https://cloud.githubusercontent.com/assets/9349172/16901666/fc87ae2a-4c41-11e6-8d70-e3168beb2e3b.png">

**Comment by thednp** [comment]
I don't know why that doesn't work, here's the `news` extension, I cooked it in like 2 minutes.
[news.zip](https://github.com/ThemeFuse/Unyson/files/368098/news.zip)

You must activate it in Unyson Extensions Manager page.

**Comment by moldcraft** [comment]
Hello,

You can disable [this action](https://github.com/ThemeFuse/Unyson-Blog-Extension/blob/v1.0.1/class-fw-extension-blog.php#L14) by adding in your theme this code:

```php
add_action('fw_init', '_action_theme_disable_fw_ext_blog_post_labels');
function _action_theme_disable_fw_ext_blog_post_labels() {
    if (fw_ext('blog')) {
        remove_action(
            'init', 
            array( fw_ext('blog'), '_admin_action_change_post_labels' ), 
            999
        );
    }
}
```

then do your `add_action()` and change the labels [same as here](https://github.com/ThemeFuse/Unyson-Blog-Extension/blob/v1.0.1/class-fw-extension-blog.php#L20-L77)
