### ISSUE TITLE
2 upload folders, one for public access and one for private access

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1793]
is there a way i can upload to a specific directory using the unyson framework.

i am building a membership website using unyson framework and i would like to add a page builder element shortcode that will allow me to upload files to the wp-content/uploads/private and then place the page builder element where i would like those uploaded files to appear if user with the right permissions views the page.

is there away i can set an upload to directory for the upload option type?

would i need to create a custom option type called "private-upload" which is a copy of the uploads option type and some how set this option type to save files into the private directory?

i've already made the necessary setup to disallow any immediate access to the wp-content/uploads/private via .htaccess. and created a php file that checks users permission before giving access to the files within the private directory as instructed here: 
https://gist.github.com/hakre/1552239

**Comment by moldcraft** [comment]
Hello,

The upload option-type doesn't allow upload to custom directory, it uses default wp medial uploader and just receives the attachment_id after the file was uploaded and an attachment post was created.

You will need to create your own custom option-type.

**Comment by ahm-3d** [comment]
sorry to be a pain, but any suggestions on how i can create my own custom option-type to achieve this. i attempted to duplicate the upload option type and rename it to private-upload but i couldn't find any where in the code where i can over-ride the wp_upload_dir(). if you can point me to the right direction i would really appreciate it. thanks

**Comment by moldcraft** [comment]
WordPress uploader is a bit complicated (and almost with no documentation), we just figured out how to get the uploaded file id from it and that's all.

Better open a ticket on WordPress bug tracker and ask them how to achieve this. Or first try to inspect it yourself (for e.g. look for a suitable filter where you can change the upload directory, but be careful to not break other uploaders).
