### ISSUE TITLE
jQuery.tabs() breaks page made with builder in customizer

### ISSUE THREAD

**Issue by JustinJohnM** [ThemeFuse/Unyson#1794]
When adding unyson default tab into a page and then open that particular page in customizer the error occurs.
![unysonissue](https://cloud.githubusercontent.com/assets/20510572/16908995/1dacb356-4ced-11e6-9720-ba9e18036f09.png)

The error occurs only after adding tab element.  the error shows only on customizer but when it started it repeat the item continuously  and crash the entire site

**Comment by moldcraft** [comment]
Hello,

In screenshot I don't see any error message.

Please give the exact steps to reproduce the problem.

**Comment by JustinJohnM** [comment]
the menu items - "logout", "search icon" & "cart icon" -  are automatically repeating after adding tab

**Comment by moldcraft** [comment]
I used these test options:

```php
$options = array(
	'test1' => array( 'type'  => 'text', ),
	'tab1' => array(
		'type' => 'tab',
		'options' => array(
			'test2' => array( 'type'  => 'text', ),
		),
	),
);
```

I added the options in `customizer.php` and everything is fine

![screenshot from 2016-07-18 14-35-01](https://cloud.githubusercontent.com/assets/1475489/16913697/0821fffc-4cf5-11e6-86e5-aea0d19fad9e.png)

I added the options in `posts/page.php` and everything is fine

![screenshot from 2016-07-18 14-39-40](https://cloud.githubusercontent.com/assets/1475489/16913750/80e3155c-4cf5-11e6-866f-5e453634afbc.png)

**Comment by JustinJohnM** [comment]
We didn't override the tabs , we are using the default unyson tabs. Please have a look at the screenshot. The issue occurs once we add the tab in a page using pagebuilder.

![tabs](https://cloud.githubusercontent.com/assets/20510572/16916191/3784652c-4d19-11e6-95d0-d80bc41617a0.png)

**Comment by moldcraft** [comment]
So the steps to reproduce are:

1. [Add a Tabs shortcode in PageBuilder](https://cloud.githubusercontent.com/assets/1475489/16916783/7239e578-4d07-11e6-8149-9d62769012c8.png)

2. View the page in frontend
3. Press the [Customize link in wp admin top menu](https://cloud.githubusercontent.com/assets/1475489/16916804/9566b81e-4d07-11e6-9bcb-8377dc30c9ce.png)

![staticshot_18-07-2016_16-51-00](https://cloud.githubusercontent.com/assets/1475489/16916872/d48eedc2-4d07-11e6-82c4-29fe1f80440f.png)

**Comment by moldcraft** [comment]
[This](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.17/shortcodes/tabs/static/js/scripts.js#L2) is the problem

![staticshot_18-07-2016_17-05-55](https://cloud.githubusercontent.com/assets/1475489/16917344/e7bc2480-4d09-11e6-8a10-090dd46c6e23.png)

**Comment by moldcraft** [comment]
While I am inspecting this, you can switch to bootstrap tabs, they seems to work fine.

**Comment by moldcraft** [comment]
I replaced the contents of [this file](https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/js/jquery/ui/tabs.min.js) with [this](https://github.com/jquery/jquery-ui/blob/1.8.17/ui/jquery.ui.tabs.js) and it works fine. So it is a bug in jquery.ui.tabs bundled in WordPress, not an Unyson bug.

**Comment by moldcraft** [comment]
I will report the problem to WordPress core developers.

**Comment by JustinJohnM** [comment]
Thanks for your help

**Comment by moldcraft** [comment]
* https://core.trac.wordpress.org/ticket/24032#comment:6
* https://core.trac.wordpress.org/ticket/23225#comment:40
