### ISSUE TITLE
Unyson Extension Update Error

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#1795]
Hello Support,

I was trying to update the unyson extension then show me the error message and I can't access admin dashboard or main site  : Fatal error: Class 'FW_Option_Type_Builder' not found in D:\xampp\htdocs\logic\wp-content\plugins\unyson\framework\extensions\forms\includes\option-types\form-builder\class-fw-option-type-form-builder.php on line 9

What should I do now?

Regards
anisur

**Comment by moldcraft** [comment]
Hello,

Please delete directory `D:\xampp\htdocs\logic\wp-content\plugins\unyson\framework\extensions\forms`

**Comment by anisur210** [comment]
Hello

I deleted that directory but Page Builder extension has an error like : http://prntscr.com/bubeg5

Thanks

**Comment by moldcraft** [comment]
Click "View Requirements" and follow the instructions

**Comment by anisur210** [comment]
Thanks!!!
