### ISSUE TITLE
Customizer options broken in latest update.

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1796]
I have just updated unyson to **Unyson 2.5.9**
WordPress: **Version 4.5.3**
And all customizer options are broken. They all return `null`.
````php
fw_get_db_customizer_option('header_width', '1000px'); //returns null
````

Other methods work:
`fw_get_db_settings_option` works.
`fw_get_db_post_option` works.

**Comment by moldcraft** [comment]
Have you tested your theme? https://github.com/ThemeFuse/Unyson-Extensions-Approval

**Comment by ivandotv** [comment]
I don't have any extensions active.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/239

**Comment by ivandotv** [comment]
Okay, I always read what issues are fixed, and if any functionality is added before I update.
Looking at the change log, I don't see that anything has changed regarding the customizer.
So this is a mayor bug.

**Comment by ivandotv** [comment]
tnx.
