### ISSUE TITLE
Map option type , preview bugs and can we get some fields descriptions please

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1797]
@moldcraft  Current map option type does not have any description for the fields. 

We are using it in the events extension and the first field on top is actually the venue
but the auto population adds the address as the venue and user does not know that he/she can 
actually change the first field to be for example "Staples Center" 

check this video out , the first field is venue and when auto-populated it gets the address 
and the second filed is the address but the address number is removed , which is wrong 
http://take.ms/yKdcR

so something like this is missing  there 

![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/16929102/67deb322-4d36-11e6-830e-5a7bd33494af.jpg)

The venue field should be empty and user should add it in or the auto-population should add something like ,   "Change to venue name" .   The address field should not have the address number removed since that field is what controls the map location in the map preview. 

I am trying to make our events extension as good as the best WP events plugin and 
we need to give users as much info as possible and our map must be accurate.

**Comment by danyj** [comment]
@ViorelEremia do we have descriptions now ?

**Comment by ViorelEremia** [comment]
create pull request
