### ISSUE TITLE
I didn't get The column options 

### ISSUE THREAD

**Issue by JustinJohnM** [ThemeFuse/Unyson#1800]
In the [tutorial](http://docs.themefuse.com/the-core/your-theme/shortcodes/columns-1)  it says "Every column comes with a bunch of built-in options. Click a column to bring up the options pop up:"   But i didn't get the column options.

**Comment by moldcraft** [comment]
Install TheCore theme and you will have the options from video or create

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/options.php
```

and add any options you want.
