### ISSUE TITLE
Multi option type is not accepting numerical index key

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1801]
http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi

if I do this 

```
0 => array(
    'type'  => 'multi',
    'value' => array( ),
    'inner-options' => array(
        'option_1' => array( 'type' => 'text' ),
    )
),
```
I get 

 Invalid option: value in \unyson\framework\helpers\general.php on line 888

https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/general.php#L888

**Comment by moldcraft** [comment]
Option id must a string.
