### ISSUE TITLE
Table option is broken

### ISSUE THREAD

**Issue by aravindajith** [ThemeFuse/Unyson#1802]
Multiple strange issues with the Table option
- [ ] 'Table Styling' field is showing twice  [Screenshot](https://cl.ly/gkBm)
- [ ]  Data is not showing up if we choose 'Data Table' option [Example Link](http://santhigram.org/2016/table-testing/) | [Screenshot](https://cl.ly/gjy7)
- [ ]  When tried to edit a 9 rows pricing table (which was already published and working fine in the frontend) the popup displays `error:undefined` [Screenshot](https://cl.ly/gkD8)

**Comment by moldcraft** [comment]
Hello,

Please activate a default WP theme and check if the 'Table Styling' is snowing twice

**Comment by thednp** [comment]
I believe you are trying to override the `table` shortcode. You might wanna [check this out](https://github.com/ThemeFuse/Unyson/issues/1786).
