### ISSUE TITLE
Shortcode is hidden with opacity: 0 since Unyson 2.5.10

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#1805]
My customers have just began to see an issue where one of my custom shortcodes does not display when clicking to edit it.
It works fine if I remove the wp-editor option type so must be to do with that.
I have `'reinit' => true` on the wp-editor option type.
I get the following in the console:
`exception: TypeError: Cannot set property 'setup' of null at HTMLDivElement.init`

Any help would be much appreciated.

**Comment by andreiglingeanu** [comment]
Have you updated your other extensions? A screen of the full JavaScript error backtrace would be also welcome.

**Comment by andreiglingeanu** [comment]
The `reinit` option of the `wp-editor` is not relevant anymore.

Also, let me know if you can reproduce this on the scratch theme.

**Comment by martinburdon** [comment]
Hi @andreiglingeanu, this does happen with the scratch theme too.

Here is a screenshot of the full error:

![image](https://cloud.githubusercontent.com/assets/4599099/17000097/ebd2717c-4eb8-11e6-8dd8-8ee2ed9b6303.png)

**Comment by andreiglingeanu** [comment]
@martinburdon which shortcode gives you this error in scratch?

**Comment by martinburdon** [comment]
It's a custom events shortcode I've made for my theme, this is the wp-editor config I have set up in options.php for the editor option type.

```
'icon_image' => array(
    'label'   => esc_html__('Icon', 'rkt-shortcodes-general'),
    'type'    => 'wp-editor',
    'desc'    => esc_html__('Description..., 'rkt-shortcodes-general'),
    'reinit' => true,
    'wpautop' => false,
    'tinymce' => false,
    'editor_height' => 200,
    'editor_css' => '<style>.quicktags-toolbar { display: none; }</style>'
)
```

All seemed to work great until the Unyson update and removing this ☝️  from my shortcode gets things working again

**Comment by andreiglingeanu** [comment]
@martinburdon `'tinymce' => false` causes [this](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/wp-editor/includes/class-fw-wp-editor-settings.php#L210) to not run. Remove this option, I'll release a quick fix for this.

**Comment by andreiglingeanu** [comment]
Fix https://github.com/ThemeFuse/Unyson/commit/a03d4d37b5116220c566500071f4820c9ab83cf0

**Comment by martinburdon** [comment]
Thanks @andreiglingeanu, I will remove `'tinymce' => false` and get a fix out for my theme 👍
