### ISSUE TITLE
how wrap section in page builder

### ISSUE THREAD

**Issue by jekaorlov** [ThemeFuse/Unyson#1806]
#Hello ! i using unyson.. help please..I need wrap section shortcode using page builder..but i cannt do that. How add custom shortcode  using in page builder. Need to get next html code ...
```
<div class="wrapper">
<section>bla-bla</section>
<section>bla-bla</section>
</div>
```

**Comment by moldcraft** [comment]
Hello,

I don't understand what you mean by wrap section shortcode using page builder.

Please give more info or some screenshots.

**Comment by jekaorlov** [comment]
i need get following html using page builder 
<div class="wrapper">
<section>bla-bla</section>
<section>bla-bla</section>
</div>
How i can wrap section shortcode using page builder...

**Comment by moldcraft** [comment]
Sorry, You can't, section is first level builder element, it doesn't have a parent element.
