### ISSUE TITLE
EditorShortcodes Major Update

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1807]
This extension adds the Unyson shortcodes button in wp editor

![](https://static.md/befebf9e5742217fda08b09b3b25a649.png)

It was refactored and now it has the following pros and cons.

## Features / Pros

* Unsyon Shortcodes button ![staticshot_20-07-2016_17-58-56](https://cloud.githubusercontent.com/assets/1475489/16991262/a676fee6-4ea3-11e6-91cd-b84bdc6edc70.png) works in `wp-editor` option-type 
 by setting the `'shortcodes'` parameter:

    ```php
    array(
        'type' => 'wp-editor',
        'shortcodes' => true,
    )
    ```

    Before it wasn't possible because WordPress "fixes" (breaks) the quotes. More detailed: We store shortcode data json encoded in attributes

    ```
    [shortcode_name some_attribute="{&quot;hello&quot;:&quot;world&quot;}"]
    ```

    but after post Update/Save, WordPress "fixes" the text to

    ```
    [shortcode_name some_attribute="{"hello":"world"}"]
    ```

    and that is an invalid shortcode attribute because the second `"` closes the attribute and the result is a mess which throws warnings

    ```
    [shortcode_name some_attribute="{"   hello":"world"}"]
    ```

    To prevent that, we stored all attributes in post meta and in post content were links to those post meta array keys

    ```
    [shortcode_name fw_shortcode="1"]
    [shortcode_name fw_shortcode="2"]
    ```

    so there was a tight connection between EditorShortcodes and the post in which it was used.

    But @andreiglingeanu created [this coder](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/includes/coder/class-fw-ext-shortcodes-attr-coder-aggressive.php) which converts the quotes and other special characters to something like `__fwqt__` and WordPres can't break/change them. And now there is no need to store attributes in post meta, the shortcodes are independent and can be used in any `wp-editor` (for e.g. in Text Block shortcode).

* It was moved out off `page-builder` extension and it is a separate extension. So the user can install EditorShortcodes without PageBuilder or both. Fixes https://github.com/ThemeFuse/Unyson/issues/191

## Cons

* All functionality from old EditorShortcodes was removed except the render functionality. So when users will update the PageBuilder extension, the [Unsyon button](https://static.md/a3e7cb08921d3c495401e97eaf68ea86.png) will disappear from post editor, and in post content instead of [shortcode box](https://static.md/3a142d3cfced4691a55a6d26bb547795.png) will be text `[button fw_shortcode="1"]`, but **the frontend render will still work**. Users will be required to go to Unyson page and install the new extension.

## You can help

* The extension needs title and description. At the moment it looks like this:

    ![](http://static.md/08bee74fbb00f2f651cc1e5a936485e3.png)

* Question for Theme Developers: Will your users be affected much by the cons? Do you have any idea how to fix/remove the cons?

## How to Test it

* [Download](https://github.com/ThemeFuse/Unyson/archive/master.zip) and Install Unyson latest dev version
* [Download](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension) the Shortcodes extension and extract in `unyson/framework/extensions/shortcodes`
* [Download](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension) the extension and extract it in `unyson/framework/extensions/shortcodes/extensions/wp-shortcodes`

----

*P.S. Thanks to @andreiglingeanu*

**Comment by andreiglingeanu** [comment]
🎉

**Comment by moldcraft** [comment]
Added install instructions in issue description

**Comment by thednp** [comment]
> The extension needs title and description. At the moment it looks like this:

My suggestion:
**Unyson Shortcodes**
_Enables shortcode editor in any Wordpress editor with the full power of the Unyson Framework._

**Page Builder**
_Build countless pages with ease thanks to the drag and drop visual content builder that's working with basic to advanced shortcodes._


**Other suggestions**

* We need a way to _disable certain shortcodes_ for this extension so that they only work for Page Builder extension (for instance I know columns nesting isn't supported and it ain't easy to implement, but even so, a quick and simple shortcode I think anyone can do for level 1 nesting, with no hustle. ). Also some certain shortcodes should be only for the editor and not for the Page Builder (labels, special text formatting, I am still thinking about it)
* Some shortcodes must work in both extensions: button/s (yes I made a _buttons_ shortcode), image box, icon box, generally anything except layout sections. Layout sections must be page builder only, and I think we all want to be able to break the page anywhere we want, to have a full window width section, no matter the context, like in the image below
![page-builder](https://cloud.githubusercontent.com/assets/6761246/17030498/51aec60c-4f78-11e6-986a-fe230206b7a2.png)

* Perhaps some would consider imperative to have ALL available in both worlds, I know now this is insane, perhaps not even necessary, 

* About column nesting: I did a shortcode editor back some years ago that could do level 2 nesting, that was insane I realized later, but it's actually easy to do 
** `[column]` - level 0
** `[column1]` - level 1, I think we could stop here
** however, they can easily get wrapped in a single `row` wrapper, with no real need to include the nested `row`

To be updated soon.

**Comment by moldcraft** [comment]
Updated install instructions, you must install the Shortcodes extesion because [this bug](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/issues/1) was fixed

**Comment by danyj** [comment]
Name suggestion:  Unyson Shortcodes for WP Editor,  or  Unsyon WP Editor Shortcodes, 

naming it only Unsyons Shortcodes suggests that shortcodes are not available until this extension is enabled which is not true. . 

pros vs cons ,  pros overtake the cons by a mile and since this issue is currently in the posts and not page builder I dont think users would mind.

**Comment by danyj** [comment]
THANK YOU   @andreiglingeanu  AND @moldcraft !!!

**Comment by danyj** [comment]
@thednp ,

>  Uncaught ReferenceError: fwShortcodesAggressiveCoder is not defined
plugin.js?wp-mce-4310-20160418:249 


you made same think like me ,  you did an theme override for shortcodes/static.php   


update it with this 


```
wp_register_script(
	'fw-ext-shortcodes-editor-integration',
	fw_ext('shortcodes')->get_uri('/static/js/aggressive-coder.js'),
	array(),
	fw_ext('shortcodes')->manifest->get('version'),
	true
);
```

**Comment by thednp** [comment]
@danyj that was before the last update, I was testing the WP Shortcodes Extension and the Master Unyson repository, right now I'm using last version from wordpress.org and it's working fine, except it doesn't work inside shortcodes that have `wp-editor` as option type.

**Comment by danyj** [comment]
tested works perfect so far , http://prntscr.com/bw9wdv 
http://prntscr.com/bw9wuo
all shortcodes inside tab shortcode

**Comment by andreiglingeanu** [comment]
@thednp 

> We need a way to disable certain shortcodes for this extension so that they only work for Page Builder extension (for instance I know columns nesting isn't supported and it ain't easy to implement, but even so, a quick and simple shortcode I think anyone can do for level 1 nesting, with no hustle. ). Also some certain shortcodes should be only for the editor and not for the Page Builder (labels, special text formatting, I am still thinking about it)

I believe you have all the filter/action infrastructure already in place to do this in your own theme. Both in Page Build and WP Shortcodes, or whatever name you come with guys)

> Loops, layout sections must be page builder only, and I think we all want to be able to break the page anywhere we want, to have a full window width section, no matter the context, like in the image below

[Of course](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/master/class-fw-extension-wp-shortcodes.php#L24).

<hr>

Nested columns is another which we'll get to much later. Maybe when we'll switch the Drag and Drop JS library for Page Builder. We had some discussion with @moldcraft about this though it was very short.

<hr>

> first test issue: adding an iconbox inside a text-block shortcode with 'shortcodes' => true, throws

Please open an issue, with reproduction steps. Thanks. Actually, I think @danyj got you covered with this.

**Comment by thednp** [comment]
> tested works perfect so far , http://prntscr.com/bw9wdv 
> http://prntscr.com/bw9wuo
> all shortcodes inside tab shortcode

I just tested with with the aggressive JS file in my static, but no shortcode button in my `wp-editor` option type.

**Comment by danyj** [comment]
You need to enable the shortcode extension
http://prntscr.com/bwg8b4

here is my unyson just in case you did not place the files in the right place

[unyson-dan.zip](https://github.com/ThemeFuse/Unyson/files/379450/unyson-dan.zip)

**Comment by thednp** [comment]
@danyj thanks for the tip. I didn't have the `shortcodes` into the `framework/extensions/shortcodes/extensions/` folder or the `WordPress Shortcodes` extension in my Unyson Extensions Manager page.

@moldcraft now I understand what was the **Cons** about and I agree with @danyj that the **PROS** are way above. I still need to understand this: if you have NOT installed `Page Builder` extension, the post editor will HAVE the Unyson Button for shortcodes, but if it is installed, then it's hidden, right? If that's true, then I think it's alright, makes sense.

**Comment by moldcraft** [comment]
@thednp 

* Page Builder extension is reponsible for "Visual Page Builder" button
* WP Shortcodes is responsible for Unyson Button

There is no connection between these two, they are independent.

**Comment by andreiglingeanu** [comment]
@thednp Next release, probably. Use master version of _Unyson_ till then.

**Comment by thednp** [comment]
@andreiglingeanu Thank you, lookin forward to this.

**Comment by danyj** [comment]
Shortcodes icon missing in bbForum wp-editor , 
http://prntscr.com/bxo7t1

looks like fw-icons are not loading there

**Comment by andreiglingeanu** [comment]
@danyj Please do `wp_enqueue_style('fw-unycon')` somewhere in your theme and let me know if it's fixed.

**Comment by danyj** [comment]
@andreiglingeanu    you want me to enque it in backend?

**Comment by andreiglingeanu** [comment]
Yep, admin side, on every page, just for tests sake.

**Comment by danyj** [comment]
@andreiglingeanu , yes  that fixes it, I enqued it in , `admin_enqueue_scripts`

**Comment by danyj** [comment]
also aggressive coder not in , 

check this out ,
http://take.ms/r1Zrd
 I disabled builder on  woo product, can use the button but the aggressive script is missing. 


currently testing what @moldcraft   said ,  https://github.com/ThemeFuse/Unyson/issues/1807#issuecomment-234730285

> There is no connection between these two, they are independent.

**Comment by danyj** [comment]
and, custom option types scripts and styles are also missing if builder is disabled on not fw post types, like , woo product or bbforum

**Comment by danyj** [comment]
@andreiglingeanu  To sum down, 

if post type is based on Unyson like ,events or portfolio , and you disable the page builder on those post types, you can still use shortcodes trough wp-editor Unyson shortcode button, 

if post type is not based on Unyson , than we are missing  wp-editor icon, the aggressive script and our custom option types scripts and styles are not loading within the shortcode popup.

**Comment by andreiglingeanu** [comment]
> also aggressive coder not in ,

Please check this:

```php
add_action('wp_enqueue_editor', '_enqueue_agressive');
function _enqueue_agressive() {
  wp_enqueue_script('fw-ext-shortcodes-editor-integration');
}

```

Yes, you are right. We'll have to re-consider [this](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L144). I'll get back to this later. You have a temporary workaround below.

<hr>

> and, custom option types scripts and styles are also missing if builder is disabled on not fw post types, like , woo product or bbforum

That's where really Unyson weaknesses start to come in. We are aware of this. Also faced it before. I'll have a discussion with @moldcraft about the thing.

**Comment by danyj** [comment]
OK  I added this , 


```
add_action('wp_enqueue_editor', '_enqueue_agressive');
function _enqueue_agressive() {
  wp_enqueue_script('fw-ext-shortcodes-editor-integration');
}
```
icon still missing ,   aggressive is ok , option types script/styles ok , 
added icon shortcode in woo product description ,  but the shortcode is not saving

**Comment by danyj** [comment]
disregard previous post

**Comment by danyj** [comment]
K , tested bit further , have many ediors open trying to nail all corner cases , 


this helps , and loads all required scripts and shortcode is saving in 
woo product, 



```
add_action('wp_enqueue_editor', '_enqueue_agressive');
function _enqueue_agressive() {
  wp_enqueue_script('fw-ext-shortcodes-editor-integration');
}

```
only thing now is we are still missing the icon

**Comment by andreiglingeanu** [comment]
@danyj Please update `Shortcodes`, `Page Builder` and `WP Shortcodes` extensions. It should be solved.

**Comment by thednp** [comment]
Thanks. Again with latest `Unyson` master?

**Comment by danyj** [comment]
@andreiglingeanu , seems ok now, 
icon back , I removed the _enqueue_agressive  action and all scripts , option types etc are ok. 
will keep poking around but for now we look ok. 


question , 

how do we disable the editor shortcode button on let say , forum post type? 
http://prntscr.com/bxrvvg

**Comment by danyj** [comment]
I think we should have something like builder settings with similar builder hooks to disable/enable the button.

**Comment by thednp** [comment]
>I think we should have something like builder settings with similar builder hooks to disable/enable the button.

I think different. The end user may not need to choose where things happen, I think the `wp-editor` option type could have an additional attribute especially designed for WP Shortcodes extension called `'post_types' => array('post','product');` this way the user needs to worry less about what works and what not.

**Comment by danyj** [comment]
@thednp  I think you did not understand me but you did describe what I wanted , something like this is what I had in mind , https://github.com/ThemeFuse/Unyson/issues/1820#issuecomment-235235130, 
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/9b33254617e646f5fb695dabf667dbd5a279f3f0/helpers.php#L28

**Comment by thednp** [comment]
@danyj yes, sorry, I've read like 5-6 words from that, I was thinking you want something like the `Page Builder` config page with post types checkboxes. But I think I gave a proper reply nevertheless.

**Comment by danyj** [comment]
@andreiglingeanu  add link  does not work in new wp-editor option type

http://take.ms/JEhgA

no js bugs

**Comment by andreiglingeanu** [comment]
@danyj it happens when `wp-editor` is inside a modal. I'll take a look.

**Comment by danyj** [comment]
add link works in text mode

**Comment by andreiglingeanu** [comment]
@danyj Find your current editor by looking inside the `tinyMCEPreInit.mceInit` variable. Copy it. Then execute this:

```javascript
// change your ID here
window.wpLink.open("fw_wp_editor_c4fb98161a6723db603211953e140a8b")
```

After this it'll work. I'll post a fix tomorrow or today in the evening.

**Comment by moldcraft** [comment]
Same problem reported a few times https://github.com/ThemeFuse/Unyson/issues/1615

**Comment by andreiglingeanu** [comment]
@moldcraft Huh, thanks, I thought that's by bad.

**Comment by moldcraft** [comment]
@andreiglingeanu Thank you for [the fix](https://github.com/ThemeFuse/Unyson/commit/03a1a482be1b565ff13bb1553e880c3e1a90cc56)

**Comment by moldcraft** [comment]
We have the thumbnail

![](https://static.md/a2111521f3804f2ea901f9b51978a564.png)

The release will be next week. Tomorrow I will create approvals for extensions and Unyson.
