### ISSUE TITLE
Page builder not loading correctly

### ISSUE THREAD

**Issue by ryankolalis** [ThemeFuse/Unyson#1808]
Recently my visual page builder is not loading correctly. When you go to edit a page it shows the short code, when you change it over to visual page builder it only shows one element (text block) event tho the page could have several elements. If you edit that element it shows the content in an editor with the short codes inside of it. All plugins are up to ate, as well as Wordpress. I have changed to 2016 theme and disabled all plugins one by one, still no luck. Any help would be much appreciated. 

![screen shot 2016-07-21 at 10 43 45 am](https://cloud.githubusercontent.com/assets/20581982/17029337/7cc844be-4f30-11e6-8a54-71db02e432ca.png)
![screen shot 2016-07-21 at 10 43 53 am](https://cloud.githubusercontent.com/assets/20581982/17029336/7cc4c654-4f30-11e6-9fbe-173e448ba144.png)
![screen shot 2016-07-21 at 10 44 01 am](https://cloud.githubusercontent.com/assets/20581982/17029335/7ca63afe-4f30-11e6-835d-b44ea943bd89.png)

**Comment by moldcraft** [comment]
Hello

1. This happened for all pages?
2. Try to restore the page from Revisions.
3. If there is a page that you didn't touched yet, please do:

    1. Cltr+A (select all post content)
    2. Delete all content
    3. Switch to Visual Page Builder

    Maybe the builder elements are still there.

**Comment by ryankolalis** [comment]
Hello, 

This actually after the most recent update of Unyson the issue only existed with the home page. Once I realized that was the case I re-created the page.
