### ISSUE TITLE
[Suggestion] Improve the typography option type

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#181]
I think at this point the typography option type >as is< today is mostly unusable. I am talking about "fast development" here. Most users will have to override the option type to simplify or extend current functionality like myself and this isn't fast development. I mean no offence here, please read on.

For instance I see no reason why having the color option for the headings because I use PHP.LESS to determine the colors depending on various elements background color.

Suggestions:
* remove text-color from the option (yes, I know I can achieve this with a simple override or configure the option to do so)
* add character set support for Google fonts, you know this is extremely important for many languages (german, romanian, vietnamese). I am curious, does your cached GFonts file include the fonts' charsets? I ask maybe I can implement this myself..
* why having the ability to choose a font for each heading level? I think this will leave room for inconsistent design and heavy loads, then users will complain about their site being slow "your theme loads is very very slow. pls fix it asap". 2 google fonts for the entire website is more than enough especially if you use the standards webfonts Helvetica, Georgia and even Verdana with newer OS
* make the preview editable, perhaps users wanna check if selected font covers their language special charsets
* the example 1 below gives you a deeper insight, just that it splits font-style and font-weight into 2 separate settings
* make a heading level specific option like example 2 below

EXAMPLE 1: Headings general settings
<img src="http://s30.postimg.org/ask1z4j9t/typo_example.jpg">

EXAMPLE 2: Heading 1 Metric Settings
<img src="http://s11.postimg.org/wc181r103/typo_settings.jpg">

**Comment by azharijelek** [comment]
Hi, I think we should update google font .json file. Because I can't find few fonts such as merriweather, fairplay display, etc. Though I can add them manually by filtering fw_google_fonts, but that'd be better if the core plugin using the latest google fonts database.

**Comment by moldcraft** [comment]
@azharijelek I created a separate issue https://github.com/ThemeFuse/Unyson/issues/245

**Comment by azharijelek** [comment]
@moldcraft thank you!

**Comment by thednp** [comment]
Any news on this as well?

**Comment by thednp** [comment]
I have a working custom option type that manages the first example, with latest Google Fonts cache.

**Comment by thednp** [comment]
Developed and PRd here
https://github.com/ThemeFuse/Unyson/pull/288

**Comment by thednp** [comment]
Anyone tested yet? Please I need to get some feedback, I want to develop something new.

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/options/built-in-option-types.html#typography-v2

Sorry, we will not create any new typography option types soon.

You can share your option type here https://github.com/ThemeFuse/Unyson/issues/955
