### ISSUE TITLE
RTL looks bad in Extensions page

### ISSUE THREAD

**Issue by antoniomangiacapra** [ThemeFuse/Unyson#1810]
Hi, I would just signal the the Extensions page have some problem in the RTL mode 

![fotografia_dello_schermo_072316_011327_pm](https://cloud.githubusercontent.com/assets/11173091/17077647/48c48864-50d7-11e6-9aa3-b3b7486eea71.jpg)

**Comment by thednp** [comment]
I did some commits on RTL for Unyson and forgot about that one ;) 

Feel free to try yours.
