### ISSUE TITLE
i can't over-ride divider shortcode

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1811]
hi,

for some reason, i can't seem to be able to over-ride the divider shortcode view!

i have modified the options file so you can select a style. i then created a class-fw-shortcode-divider.php file so it handles the style value and output it to view associated to the style.

the options over-ride works fine. however for some reason the class-fw-shortcode-divider.php is not getting detected. this part is the most essential part as it declares which of my view files to use.

the over-ride divider shortcode will work if i delete the original divider shortcode from the unyson plugin which i do not want to do .

the reason for this over-ride is so i can maintain a consistent work flow where each shortcode has a list of views to choose from.

for now, i have disabled the divider shortcode and added a new divider shortcode which i had to name **dividers** which i feel is abit of a hack to get this functionality working!

**Comment by thednp** [comment]
You cannot override the `class-fw-shortcode-divider.php` and it's no real need. You can simply override all the following files:
* `divider/options.php` - the options file
* `divider/views/view.php` - the view file to work with your own options
* `divider/static.php` - the static file, I usually need no additional CSS for a divider
* `divider/static/css/style.css` - if your `static.php` needs a specific CSS file, it should be here

Good luck.
