### ISSUE TITLE
How do I get rid of unwanted fw-row wrapper?

### ISSUE THREAD

**Issue by oligazar** [ThemeFuse/Unyson#1812]
Hi! For medium screens I have markup with 6 "1/3" columns inside a Container wrapper. So for middle screens it looks like this:
{1, 2, 3
 4, 5, 6}
For small screens I want it to look like this:
{1, 2
 3, 4
 5, 6}
So I've added these lines in extensions/builder/config.php: 
'1_3' => array(
		// ...
		'frontend_class' => 'fw-col-xs-12 fw-col-sm-6 fw-col-md-4',
	), 
But on small screens it looks like:
{1, 2
 3
 4, 5
 6}
Because of fw-row div that groups and wraps every 3 columns. What can I do to get rid of that unwanted wrapper? Or is there another way to achieve what I want? 
Sorry for my english. Hope you can understand me. Thanks!

**Comment by thednp** [comment]
https://github.com/ThemeFuse/Unyson/issues/991

**Comment by oligazar** [comment]
Thanks, but I don't get how it can help me. I don't want to change fw- prefix. That fw-row wrapper appears automatically and I want to understand where does it get from and filter/remove/get rid of it in my html, if it's possible.

**Comment by thednp** [comment]
You need a wrapper class no matter what, that's something that cannot be changed.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1768#issuecomment-232637377

[This parameter](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/fdde7872e598d64a7bca186bd253fd5bb1dcfc63/config.php#L35) will be available in [next PageBuilder extension release](https://github.com/ThemeFuse/Unyson-Extensions-Approval).
