### ISSUE TITLE
Slow server response >20 seconds

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1813]
Today I get a problem with my theme and the client server. 
With Unyson & page builder activated, the site takes 20 seconds to load, 
![Alt text](https://monosnap.com/file/VCye4Hrmvz7iiHHUgx1IZEwfEvu1yU.png)
![Alt text](https://monosnap.com/file/OYD0RbJQrAld8UHIizCgjbi2ZLgbVe.png)

It reduces to 2 seconds when Unyson is deactivated
![Alt text](https://monosnap.com/file/CYHVoteefLE2FBsDtSO9niUBOZIciO.png)

What could be the problem?

**Comment by moldcraft** [comment]
Comment [this line](https://github.com/ThemeFuse/Unyson/blob/v2.5.10/framework/helpers/class-fw-db-options-model.php#L159) and right under it put `$options = array();`.

Then let us know if there are some changes in load time. If not, can you give me admin/ftp access for that site?

**Comment by moldcraft** [comment]
Also try to comment [these lines](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/class-fw-extension-page-builder.php#L53-L56)

**Comment by moldcraft** [comment]
Also try to comment [these lines](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.5/class-fw-extension-page-builder.php#L344-L346)

**Comment by duongancol** [comment]
It makes some error but the load time reduces to 2 seconds. Does that help? 
Please let me know if you need other information!

**Comment by moldcraft** [comment]
> It makes some error

Which error?

----

So you did 1. or 2. ?

1. Comment [this line](https://github.com/ThemeFuse/Unyson/blob/v2.5.10/framework/helpers/class-fw-db-options-model.php#L159) and right under it put `$options = array();`
2. Comment [these lines](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.5/class-fw-extension-page-builder.php#L344-L346)

**Comment by duongancol** [comment]
I did both. 
This is screenshot
![Alt text](https://monosnap.com/file/OgqCsR6KEjVcP092dcmbmXiopvvaT3.png)

**Comment by moldcraft** [comment]
Please do only 2.

**Comment by moldcraft** [comment]
Can you give me admin/ftp access?

**Comment by duongancol** [comment]
I sent
Please check it!

**Comment by moldcraft** [comment]
I will let you know when I am done inspecting the site.

**Comment by moldcraft** [comment]
The site works fast when I activate a default WP theme, so I am searching the problem in theme. Meanwhile a made [a few optimizations](https://github.com/ThemeFuse/Unyson/issues/1813#ref-commit-7fafacc) in Unyson

**Comment by duongancol** [comment]
Yes, I see, I'm still searching too. This problem only happens with my theme, Unyson and his server.

**Comment by moldcraft** [comment]
I disabled PageBuilder extension and the site is still slow.

**Comment by duongancol** [comment]
please check in the front-end, not back-end only

**Comment by moldcraft** [comment]
I know.

**Comment by duongancol** [comment]
It's still slow response here

**Comment by moldcraft** [comment]
Please don't touch the site, let me finish the inspection.

**Comment by duongancol** [comment]
ok, sure!

**Comment by moldcraft** [comment]
I added [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.10/framework/helpers/general.php#L1065)

```php
$t = time();
json_decode($saved_data['fonts']);
fw_print(time() - $t);
```

and it shows `13` seconds.

I did the same on my localhost and it shows `0`. Please try on your localhost or on one of your sites and tell us the result.

----

Which hosting packet your client uses?

**Comment by duongancol** [comment]
I tested on my localhost and it showed 0
They use hosting package from https://www.mochahost.com/

**Comment by moldcraft** [comment]
I don't know how to fix this. Seems like a hosting issue.

**Comment by duongancol** [comment]
So What could be the conflict here? I need an anwser to give to the client.

**Comment by moldcraft** [comment]
`json_decode()` works very slow on his server.

**Comment by duongancol** [comment]
I'll try to ask them contact to hosting provider. Thanks for your time!
