### ISSUE TITLE
How to remove DIV with class fw-page-builder-content

### ISSUE THREAD

**Issue by Mopsan** [ThemeFuse/Unyson#1815]
How to remove DIV with class fw-page-builder-content?

Is
![image](https://cloud.githubusercontent.com/assets/20639056/17096723/768b5876-5263-11e6-941d-da16583bf85c.png)

Need
![image](https://cloud.githubusercontent.com/assets/20639056/17096797/cda87a3a-5263-11e6-9c1b-3f0e08bdf5c4.png)

$cfg['disalbe_correction'] = true; with [#455](https://github.com/ThemeFuse/Unyson/issues/455) not work

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.5/class-fw-extension-page-builder.php#L212-L219

**Comment by acze** [comment]
@moldcraft where you paste it ?

**Comment by moldcraft** [comment]
@acze In theme.

**Comment by acze** [comment]
@moldcraft i mean where you include this file

**Comment by moldcraft** [comment]
Which file? Have you ever used WordPress filters?

**Comment by Bilyachenko** [comment]
Hi
>How to remove DIV with class fw-page-builder-content?
is actual

_amework-customizations/extensions/shortcodes/extensions/page-builder/config.php_
```
<?php if ( ! defined( 'FW' ) ) {
    die( 'Forbidden' );
}

$cfg = array();
$cfg['disalbe_correction'] = true;
```

Perhaps somehow another can be removed wrapper _fw-page-builder-content_?

**Comment by mhsohag11** [comment]
**### If you want to remove fw wrapper from your custom specific shortcode.**
add this on your shortcode config.php file 

> your-theme/framework-customizations/extensions/shortcodes/shortcodes/{my-shortcode-name}/config.php

	**`'disable_correction' => true,`**
It will remove the fw default **fw-container** div and **fw-row** div.

```
$cfg['page_builder'] = array(
	'disable_correction' => true,
	'title'       => __( 'My shortcode', 'fw' ),
	'description' => __( 'desc', 'fw' ),
	'tab'         =>  __( 'My Element', 'fw' ),
);
```

Next past below code on the same file (config.php) and it will remove fw default main wrapper div 
```
<div class="fw-page-builder-content">
</div>
```
```
**add_filter ( 'fw_ext_page_builder_output_content_wrapper', function(){
	return false;
} );**
```
