### ISSUE TITLE
Bug or really nested columns?

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#1816]
Hello and sorry for my English.
It happened a strange thing with your framework and, if confirmed, could be really useful.
mistakenly I dragged an item fw-col-6 inside a item fw-col-12, and I saw that it worked!!!!! I thought I had seen bad, and then I repeated the attempt. after 3 or 4 times that I tried, it worked again. l'element fw-col-6 is located inside of l'element fw-col-12.
Now, I know that this feature is not planned in your framework, but would be extremely nice to have and, even if only for a bug, in some cases it seems to work.
Would it be possible to implement it? 
Thankyou so much

**Comment by moldcraft** [comment]
Hello,

It is a bug. Please show us a video or a screenshot how to reproduce it and how it looks in frontend.

**Comment by sandromattei** [comment]
Ok, this is a screenshot. in fact, it is not saved 
![schermata 2016-07-25 alle 17 14 13](https://cloud.githubusercontent.com/assets/15032250/17106430/9141f706-528b-11e6-907f-810f9a6d49c4.jpg)

**Comment by moldcraft** [comment]
It is a bug in jQuery sortable. Sometimes [this event](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/includes/option-types/builder/static/js/builder.js#L502) is not executed which contains [this code](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/includes/option-types/builder/static/js/builder.js#L594-L595) that doesn't allow column in column.

**Comment by sandromattei** [comment]
please please please...add this feature on unyson...:)
