### ISSUE TITLE
Edit page HTML

### ISSUE THREAD

**Issue by sdaugirdas** [ThemeFuse/Unyson#1817]
Hey guys,

Great framework, overall!

I've a question regarding how to edit page HTML with Unyson. My website is www.dainorelisapp.com. See the section below the "INTRODUCTION" section, which is using a "Services" block in the backend. On the frontend, the icons are all hyperlinked...even though the icon "URL" field is left blank in the backend.

(In the image below, the mouse is hovering over the House icon)

 
![hover](https://cloud.githubusercontent.com/assets/20646560/17109849/5b13d374-525f-11e6-9efa-69a7776f6dd9.png)

In the backend, here's the empty URL field...

![url](https://cloud.githubusercontent.com/assets/20646560/17110611/6a797068-5263-11e6-8b35-da698802fd59.png)

When viewing the page source, I can see the code that I need to edit to remove the hyperlink...

![source](https://cloud.githubusercontent.com/assets/20646560/17110665/b16489d6-5263-11e6-8a68-8b65b8881d23.png)

But I can't edit the page HTML via WordPress dashboard...

![editor](https://cloud.githubusercontent.com/assets/20646560/17110767/315b0890-5264-11e6-89a2-d6b990949baf.png)

I tried going into my database and editing page 192, but I still don't see the raw HTML.

Any ideas, guys?

Thank you,

Sarunas

**Comment by moldcraft** [comment]
Hello,

Please contact theme author to fix that problem. He must check in shortcode view if link is empty then to not output `<a>`
