### ISSUE TITLE
Demo Content Installation Time Out Error

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#1818]
Hi Support,

I am trying to install demo content but its long time loading then show time out error. Though our server max execution time 300 but show that's kind of error.

See the screenshot : http://prntscr.com/bxl5nm

**Comment by andreiglingeanu** [comment]
@anisur210 can you give me your ftp/ssh account on email: andrei.glingeanu@gmail.com? I would like to take a look.

**Comment by anisur210** [comment]
I have sent details in your mail box.

**Comment by andreiglingeanu** [comment]
@anisur210 It looks like we're getting timeout at the phase of the `Database restore`, ins't it?

**Comment by anisur210** [comment]
Yes! We are getting this error at the phase of  the database restore.

**Comment by moldcraft** [comment]
@andreiglingeanu Make sure the Backup extension is [up-to-date](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L540). To debug, you can add 

```php
return new WP_Error('test', 'Some message');
```

or

```php
file_get_contents('requestb.in/...')
```

in [this method](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L41), to find the point where the execution is stopping.

**Comment by andreiglingeanu** [comment]
@moldcraft Got it. I'll check.

**Comment by andreiglingeanu** [comment]
> Make sure the Backup extension is up-to-date.

It is.

<hr>

[Edited `execute()` method.](https://gist.github.com/andreiglingeanu/dda26d2ed70f2400b54da236f5169dcf)

On the `requestb.in` we never receive `init_state` request. That is we never get to [this](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L70) point, for some reason. Don't see why it may be like this. Maybe `$state` is everytime not `empty()`? In this case I don't know why we don't get any [`WP_Error`](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L805). Maybe it is suppressed somehow?

**Comment by moldcraft** [comment]
Inspecting...

**Comment by moldcraft** [comment]
I added [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L370-L371)

```php
file_get_contents('https://hookb.in/...?time='. (time() - $started_time));
```

and the maximum value it showed is `10`. So the timeout when db restore is executing is `10` seconds. I have no idea why this happens, in

```php
fw_print(ini_get_all(), ini_get('max_execution_time'));
phpinfo();
```

there is nothing related to `10`.

-----

`ini_get('max_execution_time');` shows `2147483648` but If found that php timeout actually is `120` with this script:

```php
sleep(119); // with 120 I get Server 500 Error Timeout page
echo 'OK';
```

still the `10` timeout is not applied, so I have no idea where it comes from.

----

#### Why it wasn't working

1. The task is started in background via a [non blocking internal ajax request](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L613-L632)
2. [Execution starts](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L548)
3. The task takes care [to not reach the timeout](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L368-L370). In this case timeout `2147483648` [exceeds max_timeout](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/class-fw-extension-backups.php#L57) and and it is set to [`600`](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/config.php#L75)
4. PHP dies after `10` seconds of execution. It is not possible to catch php timeout and [the shutdown function](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L540) is not executed (to mark the task as error and to display the error message).
5. The extension waits for the task to continue until the [timeout value is reached](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L307-L309) (`600` seconds), which means the task failed.

----

Please tell your hosting provider this story. Maybe they miss-configured the hosting, or maybe there is a security setting that kills a process that loads the CPU more that 10 seconds.

**Comment by moldcraft** [comment]
@anisur210 Which hosting are you using?

**Comment by duongancol** [comment]
is this problem fixed? Today I got the same problem. But couldn't find any error in error.log file

**Comment by moldcraft** [comment]
@duongancol [The fix](https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/b5a04d2d2033cc933ea575ecbc4432b6f0bd8b0c) is released.
Please add the below code in `{theme}/functions.php`

```php
add_action('admin_notices', function(){
    fw_print(ini_get('max_execution_time'));
});
```

and tell us what it shows.

**Comment by duongancol** [comment]
sure

**Comment by duongancol** [comment]
The result is  600. Any problems?

**Comment by moldcraft** [comment]
It's ok.
I don't know how to fix, I need to inspect your site. Please send admin and ftp details to `moldcraft[at]email.com`.

**Comment by duongancol** [comment]
I sent, please check it!

**Comment by moldcraft** [comment]
@duongancol On your site the process is stopped on Image Sizes Restore. I have made [this improvement](https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/39bf619c58ef76bfe5575cfad03a348160a47604) but it doesn't help. Before the fix the generation of all sizes at once took ~9 seconds, now only one size per step si generated and it takes 1-2 seconds, the generation works quite slow on that server. Every time it stop on [this image](http://i.imgur.com/x524YPU.jpg) (attachment_id=16) when it tries to generate the `medium_large` or `large` size.

There is no error.log in FTP.

PHP memory limit is 256M, I have tested with this script:

```php
if (isset($_GET['test'])) {
add_action('admin_notices', function(){
	fw_print(ini_get('memory_limit'));

	$x = '';
	while(true) {
		echo "<br/>";
		echo "not real: ".(memory_get_peak_usage(false)/1024/1024)." MiB\n";
		echo "real: ".(memory_get_peak_usage(true)/1024/1024)." MiB\n\n";
		$x .= str_repeat(' ', 1024*25); //store 25kb more to string
	}
});
}
``` 

I have no idea why it stops on that image, **I need php error.log**.
Please ask your hosting to send you the error.log.

----

The demo is installed, only the image sizes needs to be generated, so I installed Regenerate Thumbnails plugin and started the process for all images

```
/wp-admin/tools.php?page=regenerate-thumbnails
```

but it is very slow, about 10-25 seconds per image and there are 300+ images, I can't wait that much.

![screenshot from 2016-10-03 23-37-07](https://cloud.githubusercontent.com/assets/1475489/19053163/60988cdc-89c2-11e6-8616-b451b1ccee6b.png)

**Comment by duongancol** [comment]
that's weird, I checked the error.log in the hosting but it showed nothing

**Comment by duongancol** [comment]
I added this code in wp-config.php 
define( 'WP_DEBUG_LOG', true );
Please try go to wp-content/debug.log, there're a lots of messages here.  Hope it helps!

**Comment by moldcraft** [comment]
@duongancol I checked debug.log but there are no errors related to image sizes.

There are only:

1. A notice from plugin

    ```
    PHP Notice:  Trying to get property of non-object in /.../wp-content/plugins/a2-optimized-wp/A2_Optimized_OptionsManager.php on line 1564
    ```

2. A database error

    ```
    WordPress database error Duplicate entry '\x00-\x00' for key 'PRIMARY' for query INSERT INTO _fwbk_wpkzef_wfCrawlers ( ...
    ```

    we know about it and [treat it](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/39bf619c58ef76bfe5575cfad03a348160a47604/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L822-L834)

----

I deleted `debug.log`, started Regenerate Thumbnails an waited for a failure

![screenshot from 2016-10-04 14-24-09](https://cloud.githubusercontent.com/assets/1475489/19072528/543b66fe-8a3e-11e6-9e53-f1d62ded574c.png)

then in debug.log has appeared only this warning

```
PHP Warning:  filesize() [<a href='function.filesize'>function.filesize</a>]: stat failed for /.../wp-content/uploads/2016/09/bg-mega-mn-600x345.png.tmp.png in /home/maurisah/public_html/topseo2/wp-content/plugins/ewww-image-optimizer/common.php on line 1666
```

----

I don't see this an Unyson problem, because Regenerate Thumbnails fails too. So it is a server problem, please ask your hosting support why this happens.

**Comment by duongancol** [comment]
Thanks, mate!, I'll get back when have more information.

**Comment by duongancol** [comment]
Hi!  I can import the demo content in my localhost and use Regenerate Thumbnail without the above problem but It takes about 5 minutes in Image size restore process. My image folder is about 30mb. 
What does Image size restore process for?
And Can we optimize this for better speed?

**Comment by danyj** [comment]
Yes Image resize keeps on spinning on my end for loooong time after demos are installed, and not only my demos but you can also test The Core or any of your theme demos, its spinning way to long and it will cause may users to get mad about. Especially if you have shop,, magazine or photography theme.

**Comment by moldcraft** [comment]
> What does Image size restore process for?

Each image `hello.jpg` has [4+ sizes](https://github.com/WordPress/WordPress/blob/4.6.1/wp-includes/media.php#L757) (themes can register more sizes), so in `uploads/` you have:

```
hello.jpg
hello-100x100.jpg
hello-250x250.jpg
hello-300x100.jpg
hello-....jpg
```

On Content Backup, image sizes are excluded (not included in zip) so demo zip size is decreased dramatically. After the demo has been installed, the script will loop through each image and restore/regenerate its sizes, so the frontend will not have 404 error images.

> And Can we optimize this for better speed?

We did our best and don't know how to optimize it more. Please [test the latest upcoming version](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/289), maybe it will work better on your server.

**Comment by danyj** [comment]
> image sizes are excluded (not included in zip) so demo zip size is decreased 

understood, but can we ( developers  ) be the ones to make that decision?

**Comment by danyj** [comment]
than  you you dont have to recreate the images , demo installs are "faster" , no endless spinning ,

**Comment by duongancol** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1818#issuecomment-251994766
I agree, the total size will be bigger but I guess the total time will be decreased, not sure

**Comment by danyj** [comment]
just checked , even with some compression files that are left from testing and my own 7 custom image size , 2000+ images ( not standard, just accumulated over 2 years )  are in my uploads folder and the size is 120MB,   on our Joomla demos we have standard 50-80mb demo size  , so I think we should be ok with this option.

**Comment by moldcraft** [comment]
Initially our theme demos were with sizes include, but a lot of users encountered unzip errors on slow/cheap hosting server, that's why we implemented images sizes remove/restore.

**Comment by moldcraft** [comment]
@danyj @duongancol regarding my argument in previous comment, please confirm that you still need [this feature](https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/30)? (so I will allocate time and start working on it)

**Comment by duongancol** [comment]
I'm still concerned. If we do this feature. What is the solution if the user has problem with Unzip function?
>https://github.com/ThemeFuse/Unyson/issues/1818#issuecomment-252008722

**Comment by moldcraft** [comment]
> What is the solution if the user has problem with Unzip function?

There is no solution. Unzip can't be made in steps, the whole zip file must be loaded in memory and processed/unzipped.

**Comment by duongancol** [comment]
>the whole zip file must be loaded in memory and processed/unzipped.

Sorry, I don't understand this step

**Comment by danyj** [comment]
@duongancol , @moldcraft ,  this is how I would like to be able to use the feature disable image resize , 

give us a filter or something that e can control trough theme settings , this way if users have Unzip issues , they can go in advanced theme settings and enable/disable the image resize function for demos.

**Comment by danyj** [comment]
not sure if we can do this in manifest 

```
if(some_theme_option){

   $manifest['enable_demo_image_resize'] = true; 
}
```

**Comment by danyj** [comment]
@moldcraft ,  why cant you do chunks unzip ?

**Comment by danyj** [comment]
@moldcraft if you decide to do chunks unzip  http://stackoverflow.com/a/1229696/594423

we used that since long time now and had no issues

**Comment by moldcraft** [comment]
Let's continue the discussion [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/30#issuecomment-252233424)

@danyj I will test if that solution works with already created zip files.

**Comment by moldcraft** [comment]
> @danyj https://github.com/ThemeFuse/Unyson/issues/1818#issuecomment-252062092

I don't understand how to use that code. What it does is convert a zip file to another file with exactly the same size, which on my OS it is detected as zip and on double click it is opened as zip. It is not extracted and directories and files must be created.

**Comment by moldcraft** [comment]
> @danyj https://github.com/ThemeFuse/Unyson/issues/1818#issuecomment-252062092

I don't understand how to use that code. What it does is convert a zip file to another file with exactly the same size, which on my OS it is detected as zip and on double click it is opened as zip. It is not extracted and directories and files must be created.

![screenshot from 2016-10-07 15-18-19](https://cloud.githubusercontent.com/assets/1475489/19189799/8bde2d60-8ca2-11e6-8168-7ce23607fed0.png)
