### ISSUE TITLE
Widgets showing broken code, drag and drop not working correctly

### ISSUE THREAD

**Issue by charlesjohn2004** [ThemeFuse/Unyson#1819]
Hi,
The Unyson drag and drop widgets are showing broken codes instead of names. They work fine though. Please check the screenshot - http://themes.layero.com/olamwp/wp-content/uploads/2016/07/screenshot.png

I also encounter problems with drag and drop not working correctly. Please advice.

Thanks,
Charles

**Comment by moldcraft** [comment]
Hello,

Please make sure Unyson plugin and Unyson extensions are up-to-date, then do force refresh on page (Ctrl+R) to reload javascript.

**Comment by charlesjohn2004** [comment]
I did, but it is not working. Is this a common problem? Any other solutions?

**Comment by charlesjohn2004** [comment]
I did, but it is not working. Is this a common problem? Any other solutions?

Best Regards,
Charles John.

**Comment by moldcraft** [comment]
Delete Unyson plugin and install it back.

**Comment by LarsFinley** [comment]
Will this not delete all the settings and data from all of the Unyson extensions?

**Comment by LarsFinley** [comment]
Will this not delete all of the settings and data from all of the Unyson extension?

**Comment by danyj** [comment]
no , it just deletes the files , not DB data,
