### ISSUE TITLE
[QUESTION] How does the sample data import really works?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#182]
I see the classes include alot of SQL manipulation code and the auto-install folder has a full db SQL dump. I also checked the video introduction to the sample data import feature and looks neat and simple but that's a nightmare for a developer really :)

So I need to know what the import does after first time theme activation because I can try to hook some actions to it.

Here's how I think of it:
* after the theme activation it will display a notice to install sample data
* when you click install sample data, the TGM plugin kicks in and installs the required plugins: Unyson with all theme supported extensions, I AM NOT SURE ABOUT THIS
* deletes existing menus, posts, comments, widgets settings, wp and theme settings
* processes the SQL file (with proper replacements) and imports all data: wp settings, widgets settings, theme settings, metabox values NOT SURE ABOUT THIS EITHER
* copies the attachments to proper folders
* display WP message "Finished"

I made it easy for you so you can simply copy paste and correct my mistakes, please also fill in any valuable info on the process, we may be able to improve it.

Thanks for any reply.

**Comment by sergiubagrin** [comment]
Hi @thednp,

1. after the theme activation it will display a notice to install the TGM plugin kicks in and installs the required plugins: Unyson after this we will receive a message in case you want to install all theme supported extensions: http://screencast.com/t/SwcHB7JU

2. After this you click on Import Demo Content (a. first of all Import Demo Content Extension will save users data, general site data(url, title, description) b. deletes existing menus, posts, comments, widgets settings, wp and theme settings - all DB data c. import dummy data from sql file d. replace general site date with yours + users data (processes the SQL file (with proper replacements) and imports all data: wp settings, widgets settings, theme settings, metabox values copies the attachments to proper folders display WP message "Finished"

Finish :)

**Comment by thednp** [comment]
Thank you.
