### ISSUE TITLE
How to disallow builder on certain post types/ extensions and how to auto activate the builder?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1820]
@moldcraft , I know that we can turn page builder on /off  in builder settings , 
http://prntscr.com/bxnybs
but how do we hide some of those checkboxes like for example , forum , events etc ? 

Also ,  can we auto activate the builder for specific post types like , portfolio?

**Comment by andreiglingeanu** [comment]
@danyj https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/9b33254617e646f5fb695dabf667dbd5a279f3f0/helpers.php#L28

**Comment by danyj** [comment]
@andreiglingeanu , thnx for that , how about the auto activation ?

**Comment by andreiglingeanu** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/9b33254617e646f5fb695dabf667dbd5a279f3f0/settings-options.php#L15

**Comment by danyj** [comment]
@andreiglingeanu  Bless your heart my friend!

**Comment by andreiglingeanu** [comment]
@danyj Also you may want to consider adding post support manually, as later as possible. [As seen here.](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/9b33254617e646f5fb695dabf667dbd5a279f3f0/hooks.php#L16)
