### ISSUE TITLE
Woocomerce plugin and color-picker option type

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1822]
The color picker doesn't work well when Woocomerce plugin is activated. I think it must be conflict with woocomerce plugin javascript file. 
Please see the video here: http://take.ms/gvqkI

**Comment by moldcraft** [comment]
I can't reproduce it https://vid.me/nNDI

**Comment by duongancol** [comment]
Sorry, I found that not woocomerce, please test with this plugin: https://wordpress.org/plugins/yith-woocommerce-wishlist/

**Comment by moldcraft** [comment]
* Open [this file](https://plugins.svn.wordpress.org/yith-woocommerce-wishlist/tags/2.0.16/plugin-fw/lib/yit-plugin-panel-wc.php)
* Search `'woocommerce_settings'`. So the plugin includes on Theme Settings page the `settings.js` script from WooCommerce, which is designed only for WooCommerce Settings Page
* That `settings.js` script contains [this code](https://github.com/woothemes/woocommerce/blob/2.6.4/assets/js/admin/settings.js#L39-L41) which hides the picker after you click on input.

**Comment by moldcraft** [comment]
Please report this problem to plugin author.

**Comment by duongancol** [comment]
It seems that they don't give the support. So I tried to deregister this js file in Edit page. I tested this code but it didn't work.

```php
add_action( 'admin_enqueue_scripts', 'topseo_deregister_woocommerce_setting', 10, 1 );
function topseo_deregister_woocommerce_setting(){
	wp_deregister_script( 'woocommerce_settings' );
}
```
any suggestions?

**Comment by danyj** [comment]
I opened a ticket https://wordpress.org/support/topic/please-remove-unecessary-scripts/

**Comment by duongancol** [comment]
@danyj If you see the history of support forum, I don't think the author take the support. That's why I try to figure out the solution.

**Comment by danyj** [comment]
try this 

    add_action( 'admin_enqueue_scripts', 'topseo_deregister_woocommerce_setting', 99);

I used that to remove jquery-ui-style


	if( is_admin() ){ 
		function _thz_action_remove_woo_jquery_ui_css() {
		
			if ( class_exists( 'WooCommerce' )  ) {
				wp_dequeue_style( 'jquery-ui-style' );
			}
		}
	
		add_action( 'admin_enqueue_scripts', '_thz_action_remove_woo_jquery_ui_css', 99 );
	}

**Comment by danyj** [comment]
are you sure that the handle is woocommerce_settings ?

**Comment by duongancol** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1822#issuecomment-238208119

I checked in page source and it was right.

**Comment by duongancol** [comment]
I don't know why but change to 99 and it works. I set 100 in the beginning but It did not. 
Thank @danyj

**Comment by duongancol** [comment]
So now it's my solution for this problem. Hope it helps someone!
```php
add_action( 'admin_enqueue_scripts', 'topseo_deregister_woocommerce_setting', 99 );

	function topseo_deregister_woocommerce_setting(){
		$screen = get_current_screen();
		if ( $screen->post_type == 'page' ){
				wp_deregister_script( 'woocommerce_settings' );
		}
	}
```

**Comment by tuan-ph** [comment]
Many thanks to @duongancol , it works, i'm finding detailed reason to customize it fit with my project.

**Comment by duongancol** [comment]
@tuan-ph You're welcome, bro!

**Comment by biklik** [comment]
thanks @duongancol!

**Comment by duongancol** [comment]
@biklik You're welcome.
