### ISSUE TITLE
Customizer fw_get_db_customizer_option() problems since v2.5.10

### ISSUE THREAD

**Issue by lineardesign** [ThemeFuse/Unyson#1823]
Hi Moldcraft,

I have a function which which uses the "customize_save_after" hook. 

In the function I have small separate array file referenced which holds important  customizer values for comparison against the next time the customizer is used. If any of those important values change then fires a SASS compiler plus saves the new values to the array file.

Up to v2.5.8 this solution worked fine. Any time someone made a change and clicked the save & publish button, those newly updated values were available before the "customize_save_after" hook to compare against in the old values in the array file. Which would then fire the SASS compiler.

in v2.5.10 it seems that the "customize_save_after" hook fires before whatever function/operation is being used to save the fw_db_customizer_option(). So, my saved comparison array doesn't see a change until someone hits the save & publish button a second time. If you take that logic further, my function is always one step out of sync.

Any suggestions as to how I might resolve this?

**Comment by moldcraft** [comment]
Hello,

In v2.5.10 was added [this feature](https://github.com/ThemeFuse/Unyson/issues/1551), and [customizer functions use `FW_Db_Options_Model`](https://github.com/ThemeFuse/Unyson/blob/88a2de6b106d9111019e5b04b475124336fab907/framework/helpers/database.php#L397-L417), which [loads the options](https://github.com/ThemeFuse/Unyson/blob/88a2de6b106d9111019e5b04b475124336fab907/framework/helpers/class-fw-db-options-model.php#L156) array when you call `fw_get|set_db_customizer_option()`.

I can't help you without inspecting your code, because it's a bit complicated. Can you give me admin/ftp access or send me your theme and give the steps to reproduce the problem and in which file should I look to check the problem? If yes, send the details to `moldcraft[at]email.com`

**Comment by lineardesign** [comment]
Hi Moldcraft, 

First step is for me to use the material you've just provided to see if I can find a solution myself. I'll be in touch again within a day to let you know how things have gone.

Thank you for the pointers. :)

**Comment by lineardesign** [comment]
Hi Moldcraft, sorry for the delay on responding about this. Your pointers helped but the solution required a lot of digging on my end. I ended up dissecting my template and found two items which were causing that 1 step delay. I've now fixed them so this wasn't a problem with your update, rather some small issues with my template. 

Just a couple of points about them: 

1. Calling a value from fw_get_db_customizer_option('foo_bar') inside a function which registers a sidebar will cause the 1 step delay. 
2. In hooks.php, I originally used a foreach statement to move all of my customizer settings to postMessage. This used to work fine before but the only solution I found was to write each $wp_customize->get_setting("fw_options[foo_bar]")->transport = "postMessage"; for each of my settings. If you are curious about what I had which caused a 1 step delay here is the code ( if you have any recommendations on what I might try instead then feel free to let me know) :
```
    function _action_customizer_live_fw_options( WP_Customize_Manager $wp_customize ) {
          
        $customizer_keys = array_keys(fw_get_db_customizer_option());
      
        if ($wp_customize->get_setting('fw_options[brand_primary]')) {
          
            foreach($customizer_keys as $key){
                          
              if (null !==( $wp_customize->get_setting('fw_options['.$key.']'))) {
                
                $wp_customize->get_setting('fw_options['.$key.']')->transport = 'postMessage';
               
              }  
                   
            }         
                                  
          add_action( 'customize_preview_init', '_action_customizer_live_fw_options_preview', 1 );
            
        }
        
    }
```

Thank you again for your help, it was appreciated.

**Comment by danyj** [comment]
@lineardesign 

> Calling a value from fw_get_db_customizer_option('foo_bar') inside a function which registers a sidebar will cause the 1 step delay.

excellent find! Was kicking myself not knowing what is causing the delay.
