### ISSUE TITLE
Custom query in db from meta_key & meta_value

### ISSUE THREAD

**Issue by acidcrash2005** [ThemeFuse/Unyson#1825]
Hello!

I need create custom query in db for select posts with same dates. The date I put like option field of Unyson Date Picker. So the date recorded in DB like jsone object in meta_key with name fw_options.

How I can select post with options Date Picker equal for example Feb, 2016, 21, 08.

Thanks!

**Comment by moldcraft** [comment]
```
'your_option_id' => array(
    'label' => __('Hello Date', '{domain}'),
    'type'  => 'datepicker',
    'fw-storage' => 'post-meta',
)
```

after post save, check database for post meta named `fw:opt:your_option_id`

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-storage/type/class-fw-option-storage-type-post-meta.php
