### ISSUE TITLE
Need help setting up section options array

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1826]
@moldcraft  @andreiglingeanu , I am refactoring builder section options to lower the array size,  currently I have over 20 section option where 15 of them are custom options like animation effects , parallax, video bg etc. 

So the idea is to setup default 5 and rest of them add to an addable option type, thing is that I will endup with 10/15 empty arrays which is much better than current setup but still no reason for those to be in there,   

http://prntscr.com/by4tn9

question is how can I add set of custom option for the section that would contain ONLY selected effect( options set ) , this is what I need kinda , if user selects animation, parallax and video bg , options  array should be this 

```
'custom' => array (
	'animation'=> array(),// animation options
	'videobg' => array(),// videobg options
	'parallax'=> array(), // parallax options
),
```

if user selects only animation array would be this 

```
'custom' => array (
	'animation'=> array(),// animation options
),
```

currently I cant figure out the best unyson option types combo that could accomplish this. In each case , addable popup , multi, multi-picker ,  I endup having the options/arrays  that are not even used. 

Any help is appreciated.

**Comment by thednp** [comment]
I have something similar in mind, I believe creating a hidden shortcode to be used only for the section's specific settings for parallax, animation etc.

I am also considering creating something like this for all content shortcodes, similar to the table button shortcode, give it a button to edit stuff, and not repeat same settings over and over. Still, some items need a specific type of animation, could complicate things a bit, but it should be doable.
