### ISSUE TITLE
Load option types only when used

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1827]
Initially option-types were loaded on every page load. Then we created lazy load (option types loaded only when requested. I couldn't make lazy load for all option-types because there was some problems. We need to investigate if it is possible to make lazy load for all option-types, if not, to explain why.

**Comment by andreiglingeanu** [comment]
Please post more details here. I'll be interested to take a look.

**Comment by moldcraft** [comment]
I forgot why it was not possible to make all option-types lazy loaded, so I can't give details at the moment, I need to inspect.

**Comment by danyj** [comment]
@moldcraft , because  option defaults maybe?

**Comment by moldcraft** [comment]
@danyj That was something related to builder I think. I will inspect and let you know.

**Comment by moldcraft** [comment]
P.S. I did commits in many extensions.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/258
