### ISSUE TITLE
Builder section/column collapse feature sugestion

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1829]
There is this nifty collapse row option in VC, 
http://take.ms/WdZAh

it would be great  if we can add something like that and leave just section name visible 
like this  http://take.ms/6m5TQ

**Comment by duongancol** [comment]
Great Idea! 👍

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/pull/64
