### ISSUE TITLE
Mega menu hide checkbox removes a column

### ISSUE THREAD

**Issue by elecstorm** [ThemeFuse/Unyson#1830]
Hi!
I have wordpress 4.5.3, default theme "twenty sixteen" and unyson with last updates. No other plugins.
I made the mega menu with some columns and test pages in it (without hide checkbox).
![mega menu1](https://cloud.githubusercontent.com/assets/20688268/17206329/da13d12e-54b7-11e6-800d-e6984d4f1451.jpeg)
It looks like this:
![before](https://cloud.githubusercontent.com/assets/20688268/17206217/50ac83ae-54b7-11e6-9816-1d72b3fe1034.png)
But when I place a mouse arrow under the "Page Example" nothing happens. This is the first problem.

When I set hide checkbox to the column and press Save Menu - it removes:
![mega menu2](https://cloud.githubusercontent.com/assets/20688268/17206836/58215ba2-54ba-11e6-8739-5d222712fc84.jpeg)

And menu's structure breakes:
![after](https://cloud.githubusercontent.com/assets/20688268/17206867/7e57e462-54ba-11e6-87ed-1f43bc872c72.jpeg)
This is the second problem.
I tryed do it with wordpress's release for this ticked: [https://core.trac.wordpress.org/ticket/36590#ticket](https://core.trac.wordpress.org/ticket/36590#ticket) and last developer release - 4.6-RC1-38170, with some other themes: the same picture.
Maybe I lost something in mega menu settings?

**Comment by pandvm** [comment]
Same issue

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/pull/12

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/244
