### ISSUE TITLE
Show event posts in a custom shortcode

### ISSUE THREAD

**Issue by gaiagilder** [ThemeFuse/Unyson#1831]
Hello,

It would be possible to display  individually posts created with the event extension?

For example whit this piece of code i can display only those that come from the main loop

    `$post_title = array();
     $args=array('order'=>'ASC','posts_per_page'=>1000);
     $posts = get_posts( $args );
     if ( $posts ) {
     foreach ( $posts as $post ) {
       $post_title[$post->post_title] = $post->post_title;
     }
     }

    $options = array(
	'title'		=> array(
		'label'   => __( 'Title', 'domain' ),
		'type'    => 'select',
		'desc'    => __( 'Select from the posts.', 'domain' ),
		'choices' => $post_title
	),
    );`

***EDIT***

Possible solution:

    `$post_title = array();
     $args=array(
	//'name'           => $the_slug,
	'post_type'      => 'fw-event',
	'post_status'    => 'publish',
	'posts_per_page' => 1000
      );

    $posts = get_posts( $args );
    if ( $posts ) {
    foreach ( $posts as $post ) {
       $post_title[$post->post_title] = $post->post_title;
    }
    }

    $options = array(
	'title'		=> array(
		'label'   => __( 'Title', 'namaste-lite' ),
		'type'    => 'select',
		'desc'    => __( 'Select from the posts.', 'namaste-lite' ),
		'choices' => $post_title
	),
    );`

**Comment by moldcraft** [comment]
That seems to be the solution
