### ISSUE TITLE
"Invalid request method" message when activating or deactivating extensions

### ISSUE THREAD

**Issue by pandvm** [ThemeFuse/Unyson#1832]
When i activate or deactivate any extension there is "Invalid request method" message appears on top of a Unyson Extensions page.

WordPress 4.5.3
Unyson 2.5.10

No any plugins installed.

**Comment by moldcraft** [comment]
Please replace [this](https://github.com/ThemeFuse/Unyson/blob/v2.5.10/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L1830) and this [line](https://github.com/ThemeFuse/Unyson/blob/v2.5.10/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2047) with

```php
$error = __('Invalid request method.', 'fw') .': '. $_SERVER['REQUEST_METHOD'];
```

and tell us what it shows.

**Comment by pandvm** [comment]
issue may be closed. problem resolved. it was my fault, sorry :)

**Comment by moldcraft** [comment]
@pandvm Please tell us what was the problem, it may help other users

**Comment by pandvm** [comment]
After reinstalling the framework it works as it should again :) i do not know what was that unfortunately. i think i have messed up thomething in the framework when i was learning more about it.
