### ISSUE TITLE
Make image responsive

### ISSUE THREAD

**Issue by LevyMarketing** [ThemeFuse/Unyson#1834]
I use the visual page builder and use the section with an image to create a background image. How do I make these background images responsive? Right now, they just duplicate if the screen is larger than them and they cut off in size. 

Also, how do I access the html of specific pages when they are in visual page builder? 

Thanks!

**Comment by ahm-3d** [comment]
you can over-ride the section css by adding framework-customizations/extensions/shortcodes/shortcodes/section/static/css/background.css and apply a no-repeat to the background

**Comment by LevyMarketing** [comment]
How do I add the framework customizations, though? Can you provide me a step by step please.

Thanks!

**Comment by moldcraft** [comment]
Hello,

Please read the docs http://manual.unyson.io/en/latest/extension/shortcodes/index.html

**Comment by ahm-3d** [comment]
if you only installed unyson plugin, then you will need to look at the documentation: http://manual.unyson.io/en/latest/index.html#content
easiest way, is to install the scratch theme from the unyson website. this already has the framework-customizations folder built into it. it is quiet self explanatory from here on how the framework works as there are some examples within the framework-customizations/extensions/shortcodes/shortcodes/

**Comment by LevyMarketing** [comment]
If I upload the scratch theme, you're suggesting just to leave it as inactive, but then the files will be there? When I go into the editor for the plugin the only active file is unyson/unyson.php so the manual isn't much help to me because it seems very different then what my options are. Thank you ahm-3d!
