### ISSUE TITLE
Google Map not working properly

### ISSUE THREAD

**Issue by natejoyner** [ThemeFuse/Unyson#1836]
Events posts as well as the map short code is unable to display map, alert box shows up with a message:

"This page was unable to display a Google Maps element. Please contact the site administrator. If you are the administrator of this site, please check the JavaScript console or check the following page for troubleshooting: http://g.co/mapsJSApiErrors"

I have attached screenshots of the alert message as well as the console errors.

I am also using the flavour theme as well.

![console log screen shot 2016-07-28 at 5 18 11 pm](https://cloud.githubusercontent.com/assets/4603796/17229971/f7305dce-54e7-11e6-8a55-d513db8518be.png)
![popup screen shot 2016-07-28 at 5 17 44 pm](https://cloud.githubusercontent.com/assets/4603796/17229970/f72dc096-54e7-11e6-9481-b901e3532c32.png)

**Comment by Ataurr** [comment]
Use latest version Unyson and extensions.

Create a new map api key and add within map shortcode

**Comment by andreiglingeanu** [comment]
Fix in [backend](https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228821014) and [frontend](https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228732020).
