### ISSUE TITLE
Contact Form Not Sending Emails 

### ISSUE THREAD

**Issue by claireswalker** [ThemeFuse/Unyson#1837]
I am using Unyson Contact form. Want the emails sent to my google Apps email account, which is hosted through a different website than the one hosting my wordpress website. I tried setting it up that way, and kept getting error codes. So I have the contact form send the email to the wordpress host (bluehost), and I set up that bluehost email account to forward to my google apps account. Now when I send an email, it says success, but I am not getting the message in either account. I have looked through all of the google apps- contact form advice on wordpress and I don't think the issue applies to my situation since I am not using the same domain host for the wordpress website as my google apps account. Any ideas??

Reply

**Comment by thednp** [comment]
Does contact form 7 work for you? If that doesn't work as well, it's a server issue you might have to google for. In any case, make sure to check the server logs to spot why emails don't go your way.

**Comment by moldcraft** [comment]
> Now when I send an email, it says success, but I am not getting the message in either account.

Please test the latest Forms extension. There was a [weird problem](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/197ff258a4243c198ceef36f9a1e3e9a36e867bc): If the Subject is "New message", you get success message but the email didn't come.
