### ISSUE TITLE
Demo install issue. Cannot create file: 

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1838]
Hello
we are trying to install demo content on of our client site. and getting this error. 

![screen shot 2016-07-29 at 11 26 24 am](https://cloud.githubusercontent.com/assets/6223399/17238662/5f10c45a-557f-11e6-828b-9c95727b5b76.png)

**Comment by moldcraft** [comment]
Hello,

You are able to upload images in WP Media Library?

Check `wp-content/uploads` directory permissions.

**Comment by Ataurr** [comment]
Yes i can upload image in media library. And hosting from wpengine

And here is the uploads folder permission https://puu.sh/qiG8B/e814037d79.png

**Comment by Ataurr** [comment]
I have found the solution to install demo content Wpengine server.
I have tried [This way](https://static.md/6d488c764f6503f12620a43b4c50623c.png) but no luck. 

But staging process work fine.  so i have created a [screencast](https://youtu.be/bb2dU59Mumw) from my clients

**Comment by moldcraft** [comment]
WpEngine has a too restrictive security system. We had many problems with WpEngine related to Backup, but haven't found the exact source of the problem. We contacted WpEngine tech supported and even they didn't understood why our Backup is not working.

But thanks to your video now it makes sense, they have set restrictions on the production version of the site, if you want to change files (what Demo Install does) you need to create a staging (sandbox) project, do all the changes there, and deploy to production when you are ready.

Thank you very much!
