### ISSUE TITLE
Respect .gitignore

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#1839]
What about respecting `.gitignore` file [here](https://github.com/ThemeFuse/Unyson/blob/master/framework/extensions/update/class-fw-extension-update.php#L15-L19)?

There may be `node_modules`, `bower_components` or whole mbs of files from other package managers. `.gitignore` is like a de-facto standard for all of this issues.

<hr>

Yes, I understand that globs from `.gitignore` may be somehow not that straightforward to implement. But using [`glob()`](http://md1.php.net/manual/en/function.glob.php), it is totally doable.

**Comment by moldcraft** [comment]
It is something minor. You can create a pull request and test if extensions update works fine (for e.g. what happens if a `.gitignore` si in a sub directory, or if `.gitignore` exists in update zip)
