### ISSUE TITLE
Automatic extension activation

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#184]
Hi 
How can activate an extension without clicking activate button?
![capture](https://cloud.githubusercontent.com/assets/7946657/5885763/2abd8c24-a3a1-11e4-90e7-4141a99293fa.JPG)

I hope these options are saved using settings api.
Thanks

**Comment by moldcraft** [comment]
When you click the "Activate" button [this code](https://github.com/ThemeFuse/Unyson/blob/f3c9de97634fef250e77edd631b841b9c3df73ab/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L1392-L1439) activates the extension(s)

**Comment by moldcraft** [comment]
Or maybe you will find an answer [here](https://github.com/ThemeFuse/Unyson/issues/185)
