### ISSUE TITLE
display page builder content for blog archive

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1840]
hi,

i have created a blog page which will act as the front page for all my blog posts. however i have added some elements within the blog main page. is there a built in way within unyson that enables me to display the page builder elements of any page id or slug?

**Comment by ahm-3d** [comment]
i have used this piece of code in my index.php hoping that it would display the page builder content for the blog page:

```
<?php $wp_query->posts = array();?>
	<?php $wp_query->posts[] = $wp_query->queried_object;?>

	<?php while ( have_posts() ) : the_post();
			the_content();
		endwhile;?>
```
however this is turning to be a hopeless endeavour. the page builder element will only show if i dont set the blog page as a static page for posts which i can live with except the monkeys in my head are constantly telling me that i am not building my theme to it's full potential and as long that 
static page for posts is available without a way to disable it, then my theme has an option available that could break the site. that is why i am trying apply a code that could potentially ignore that setting

**Comment by ahm-3d** [comment]
ok so, i managed to get what i wanted working by adding the following to index.php:

```
<?php $object = get_queried_object();
	$query = new WP_Query( array('post_type'=>'page','p'=>$object->ID) );
	while ( $query->have_posts() ) : $query->the_post();
		the_content();
	endwhile;?>
```
can some one confirm that this approach is perfectly fine or utter nonsense. thanks

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/58#issuecomment-236877609
