### ISSUE TITLE
Phone Number Issues

### ISSUE THREAD

**Issue by damerms** [ThemeFuse/Unyson#1842]
Phone errors. Maybe it need to be more user friendly. 

1. Must be valid. I did enter a valid number. 
2. Still gives me the error even though I made it unrequired.
3. Says it must be a min. of 20.

Seems like validation is all messed up. 

![voila_capture 2016-07-30_05-43-46_pm](https://cloud.githubusercontent.com/assets/352276/17273582/c7dfcf2a-567f-11e6-9c90-5b4ec3b9cf4b.png)

**Comment by thednp** [comment]
The `773-333-5555` is NOT a number, it's a string because `-` character. You must set the field type to string in most cases.

**Comment by damerms** [comment]
I am talking about setting up in the user interface. You have two choices digits or values either one you select gives the error. 

See atached recording. 
[Voila_Capture 2016-08-01_07-06-01_AM.mov.zip](https://github.com/ThemeFuse/Unyson/files/393674/Voila_Capture.2016-08-01_07-06-01_AM.mov.zip)

**Comment by thednp** [comment]
Yes @damerms, `digits` means **number**, while value is sort of **string**.

**Comment by damerms** [comment]
No matter which I select, I get the error. I simply want someone to enter
their phone number.
ᐧ

Thanks
David

Shaping Connected Experiences
 Linkedin <http://www.linkedin.com/in/merms> | 773.744.0760

“Before jumping right into solving a problem, we should step back and
invest time and effort to improve our understanding of it.”

- Albert Einstein

**Comment by thednp** [comment]
So use a simple text field and problem solved, meanwhile perhaps devs would look into it and fix it.

**Comment by damerms** [comment]
Sure I will do that hack for now, but I would suggest fixing the number
field so that it is not broken.
ᐧ

Thanks
David

Shaping Connected Experiences
 Linkedin <http://www.linkedin.com/in/merms> | 773.744.0760

“Before jumping right into solving a problem, we should step back and
invest time and effort to improve our understanding of it.”

- Albert Einstein

**Comment by moldcraft** [comment]
The field is called Number, not Phone Number, it accepts only digits.

**Comment by moldcraft** [comment]
You can submit pull requests to improve options labels and descriptions
