### ISSUE TITLE
Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (couldn't connect to host)

### ISSUE THREAD

**Issue by ahmadjod** [ThemeFuse/Unyson#1843]
please I have this issue while I Install Compatible Extensions

Downloading the "Shortcodes" extension...

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (connect() timed out!)

Downloading the "Breadcrumbs" extension...

Failed to access Github repository "ThemeFuse/Unyson-Breadcrumbs-Extension" releases. (couldn't connect to host)

Downloading the "Backup & Demo Content" extension...

Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (couldn't connect to host)

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (connect() timed out!)
Failed to access Github repository "ThemeFuse/Unyson-Breadcrumbs-Extension" releases. (couldn't connect to host)
Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (couldn't connect to host)

please help me with it

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1691#issuecomment-229382498
