### ISSUE TITLE
widgets in page builder

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1844]
Hi,

currently the widgets section is managed in it's own section where you can create sidebars for specific pages and add widgets to those sidebars.
the page builder also has the page builder element to specify which sidebar to add.
having those 2 features seem redundant as i can specify for a sidebar to be displayed in one group but yet i can still add it to the page which i haven't specified.

as all my post types will be created via the page builder, i am trying to simplify this process by introducing a new element type called 'Widgets', here it will load all the widgets that are currently displayed in the widgets.php so they can be added anywhere in the page builder. by doing so, we can eliminate the purpose of having sidebars and a separate widgets section as everything will be managed within the page builder.

currently my idea will work if i manually create a new shortcode for each widget and add it to the 'Widgets Element' tab. however it would be nice if unyson can automatically populates those widgets into the builder but i believe this may not be possible as those section write to different tables in the database and therefore have a different code base. is this correct?

**Comment by ahm-3d** [comment]
ok, so i believe i may be wrong...
if i duplicate the widget-area shortcode and add it to my framework-customization folder, then rename it to 'widgets', so essentailly i am creating a new shortcode called 'widget'. then modify the class so it is:

```
class FW_Shortcode_Widgets extends FW_Shortcode
{
	public static function get_widgets()
	{
		global $wp_registered_widgets;
		$result = array();
		foreach ( $wp_registered_widgets as $widget ) {
			$result[ $widget['id'] ] = $widget['name'];
		}

		return $result;
	}
}
```
this will automatically display all registered widgets. i will just need to add a piece of code in my options.php to populate the options available for each selected widget and then the view could possibly output the selected widget via the_widget(). just need to figure out how to output the widget object name so i can add it to this function.

**Comment by thednp** [comment]
I think you're doing great for the community, I would recommend digging even further on the issue and post a `How to` tutorial here, I did and devs supported my actions.

I think we need to have a look at how page builder by site origin works with widgets, I always found it to be a great built in functionality.

**Comment by dmbostan** [comment]
@thednp  so you got this working ?

**Comment by thednp** [comment]
@dmbostan Unfortunately I haven't had the time to dig into it.
