### ISSUE TITLE
Unyson Shortcodes button for wp-editor option type

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1846]
Hi, guys!

Is there any way to add Unyson Shortcodes button for [wp-editor](http://manual.unyson.io/en/latest/options/built-in-option-types.html#wp-editor) option type? 
It would be cool to run shortcodes inside shortcodes i believe :)

Thank you!
![1](https://cloud.githubusercontent.com/assets/12991525/17278980/ad620124-5772-11e6-91e0-5aff0585c815.jpg)

**Comment by thednp** [comment]
https://github.com/ThemeFuse/Unyson/issues/1807

**Comment by andreiglingeanu** [comment]
And [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/62#issuecomment-230768886), particularly.

**Comment by WPJobs** [comment]
sorry, as i read, it requires "WordPress Shotcodes" extension, can i add into theme manifest something like this (currently this is not working)

```
$manifest['supported_extensions'] = array(
   'wp-shortcodes' => array()
);
```

to allow users auto-install this extension? Thank you!

**Comment by andreiglingeanu** [comment]
@WPJobs Check extensions screen, you don't have this extension there? What's the version of Unyson you've got?

**Comment by moldcraft** [comment]
@andreiglingeanu Nope, the release will be tomorrow https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/240

**Comment by moldcraft** [comment]
@WPJobs Yes, you can add [`wp-shortcodes`](https://github.com/ThemeFuse/Unyson/blob/v2.5.11/framework/core/components/extensions/manager/available-extensions.php#L21) to supported extensions
