### ISSUE TITLE
Issue regarding Forms - sending mails 

### ISSUE THREAD

**Issue by virvazir** [ThemeFuse/Unyson#1847]
Is it possible to send mails via sendgrid? I see only two options smtp & wp-mail

If not, can you tell me how i can set the reply to address to the email submitted in the form?

Also the name of the email comes as %First_name%

How can I change it to the First Name submitted in the form?

Can I customize the result mail further as right now its only the entry fields with no heading at all. I would like to add a heading.

We removed the field names for each field to customize it & use placeholder as a guidance for our guests. How could I have the form response email to show (placeholder) followed by the response instead of {Field Name): Response ? 

https://wordpress.org/plugins/unyson/

**Comment by andreiglingeanu** [comment]
Use `smtp` section. You'll have to enter your Sendgrid credentials there. [Sendgrid docs](https://sendgrid.com/docs/Classroom/Basics/Email_Infrastructure/recommended_smtp_settings.html). [Unyson docs regarding Forms](http://manual.unyson.io/en/latest/extension/forms/index.html), you can basically replace every template from the [main](https://github.com/themefuse/Unyson-Forms-extension) extension.

**Comment by virvazir** [comment]
Can you tell me how i can set the reply to address to the email submitted in the form as that received in the mail?

**Comment by moldcraft** [comment]
@virvazir It is added [automatically](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/extensions/contact-forms/class-fw-extension-contact-forms.php#L154-L162)

**Comment by virvazir** [comment]
I wanted to set the reply to address to that entered in the form. How could I do that?

**Comment by moldcraft** [comment]
Just add an Email field in your form (not Text) and [it will be set automatically as reply-to](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/f2bc695e0fcfd381db788e68054eb39175520fd5/extensions/contact-forms/class-fw-extension-contact-forms.php#L154-L162)
