### ISSUE TITLE
Auto activation extensions on install unyson or active the theme?

### ISSUE THREAD

**Issue by AminulBD** [ThemeFuse/Unyson#185]
Is this possible to do auto install and activation extensions when install unyson as plugin or active the theme?

**Comment by moldcraft** [comment]
No. The framework can't install/download anything in background, especially when ftp credentials are required.

But it's possible to specify [a list of extensions supported by your theme](https://github.com/ThemeFuse/Scratch-Theme/blob/9c47c07b83516441a802a529825c8bfa9ab9ea86/scratch-parent/framework-customizations/theme/manifest.php#L9) and the user will be redirected to a page to install those extensions after plugin was activated.
