### ISSUE TITLE
Javascript error in admin after update

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#1853]
Hello.
I just updated unyson with the new extension, “Editor of Shortcodes" and now I cannot make the switch between editor and html by getting this javascript error:
Uncaught TypeError: Cannot read property 'canvas' of undefined

**Comment by andreiglingeanu** [comment]
@sandromattei It is in main post editor or an `wp-editor` option type?

**Comment by sandromattei** [comment]
wp-editor option type

**Comment by sandromattei** [comment]
text-block

**Comment by andreiglingeanu** [comment]
Show your option array.

**Comment by sandromattei** [comment]
default text-block shortcode

**Comment by andreiglingeanu** [comment]
Your unyson version? Have you tried to reproduce this in Scratch?

I believe that's a long gone error that has been solved long time ago.

**Comment by sandromattei** [comment]
i have updated unyson today...
the problem started after the update

**Comment by andreiglingeanu** [comment]
Please send me your credentials at `andrei.glingeanu@gmail.com`.

**Comment by sandromattei** [comment]
credentials?

**Comment by andreiglingeanu** [comment]
I mean your WordPress admin panel login/password, to take a quick look at your issue.

**Comment by sandromattei** [comment]
wordpress is installed locally on my computer

**Comment by andreiglingeanu** [comment]
Okay. Please test the same shortcode with Scratch theme. If you have any hooks that customise `wp-editor` - let me know.

**Comment by sandromattei** [comment]
ok, I download the theme and try to.
in short, I will have you know

**Comment by andreiglingeanu** [comment]
Any plugin installed that add some button to the `wp-editor`?

**Comment by sandromattei** [comment]
I had installed the plugin wp-better-attachments but l'I deactivated and the problem continues

**Comment by andreiglingeanu** [comment]
Could you zip all of your `plugins` directory from `wp-content` and give me a link?

**Comment by sandromattei** [comment]
yes, just a moment

**Comment by sandromattei** [comment]
https://mega.nz/#!jRQVHTIC

!Bx36UB1oYSry7LfH3sDM45qS8ExIDUI1ekGJ-k835Kg

**Comment by sandromattei** [comment]
Thank's

**Comment by sandromattei** [comment]
this is the error on my console.
load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,heartbeat,autosave,wp-ajax-response,jquery…:11 Uncaught TypeError: Cannot read property 'canvas' of undefinedb.closeAllTags @ load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,heartbeat,autosave,wp-ajax-response,jquery…:11d @ load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,heartbeat,autosave,wp-ajax-response,jquery…:751(anonymous function) @ load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,heartbeat,autosave,wp-ajax-response,jquery…:751e @ wp-tinymce.php?c=1&ver=4310-20160418:3m @ wp-tinymce.php?c=1&ver=4310-20160418:3

**Comment by andreiglingeanu** [comment]
Remove `plugins/unyson/framework/extensions/shortcodes` folder.

Then install the `Page Builder` and `WP Shortcodes` once again.

**Comment by sandromattei** [comment]
Faaaantastic!!!!! it work!
Thankyou so much!!!
