### ISSUE TITLE
All widget areas aren't shown in Theme Options

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1856]
I have registered sidebars using addable popup options. The added sidebar shows except theme settings. 
Here is what I did

```
        function fotogruf_register_sidebar_widgets() {
            if (defined('FW')) {

                $customsidebars = fw_get_db_settings_option('sidebar', '');
                if (! empty($customsidebars) && sizeof($customsidebars) > 0) {
                    foreach ($customsidebars as $customsidebar) {
                        $widget_areas = esc_attr($customsidebar['sidebar_id']);

                            register_sidebar(array(
                                'name' => $widget_areas,
                                'id' => $widget_areas,
                                'before_widget' => '<section id="%1$s" class="widget %2$s">',
                                'after_widget'  => '</section>',
                                'before_title'  => '<h2 class="widget-title">',
                                'after_title'   => '</h2>',
                            ));

                    }
                }
        }
    }
```

This register the sidebars properly. But the sidebar isn't visible on theme options panel . 
![untitled2](https://cloud.githubusercontent.com/assets/12174913/17340059/6fbc9b28-5910-11e6-847c-684ec8fec863.png)
![untitled1](https://cloud.githubusercontent.com/assets/12174913/17340060/6fc1bf18-5910-11e6-905f-e615c5d3d247.png)

To show the widget area on theme option I have used

```
                'archive_sidebar' => array(
                    'label'   => __( 'Sidebar', 'fotogruf' ),
                    'desc' => __('Select unique sidebar for search page', 'fotogruf'),
                    'type'    => 'select',
                    'choices' => FW_Shortcode_Widget_Area::get_sidebars()
                ),
```

**Comment by moldcraft** [comment]
Hello,

Please try to find the solution and create a pull request. We don't have time to investigate this issue at the moment.

**Comment by bensigel** [comment]
Hello,

Can not see elements of widget the https://themeforest.net/item/evoke-wordpress-theme/11827132 theme.

Can you help me ?!

**Comment by moldcraft** [comment]
I can't buy the theme just to test the widget. Send me admin/ftp details to `moldcraft[at]email.com` please.

**Comment by GheorgheP** [comment]
You need to ask the plugin authors if they register the sidebar respecting the wordpress rules, and by this I mean:

 - The sidebar is registered with [register_sidebar](https://codex.wordpress.org/Function_Reference/register_sidebar) function.
 - The sidebar is registered on [widgets_init](https://developer.wordpress.org/reference/hooks/widgets_init/) or at least [init](https://developer.wordpress.org/reference/hooks/init/) action.
