### ISSUE TITLE
Visual builder content not displayed

### ISSUE THREAD

**Issue by ziuzea87** [ThemeFuse/Unyson#1857]
Hey there, I'm using Unyson for a custom template and I have a query where I some specific custom posts content. There is used Visual builder inside those posts and until today everything worked fine, the_content() displayed content for each post and everything worked perfectly. Now, nothing displayed for the posts. Will appreciate some help on this matter. Thanks.

**Comment by moldcraft** [comment]
Hello,

Please edit 

```
wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/class-fw-extension-page-builder.php
```

replace [this line](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/9b8c6f3eccf8cda5bf4372b352510d0d41eeb6c1/class-fw-extension-page-builder.php#L374) with

```php
} else {
	foreach ($posts as &$post) {
		$post->post_content = $this->get_post_content_shortcodes($post);
	}
}
```

and let us know if it fixes the problem.

**Comment by Ataurr** [comment]
Look like its working.  Let me try my clients site as well

**Comment by ziuzea87** [comment]
Yep, that did the trick. Thanks.

**Comment by moldcraft** [comment]
I [removed](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/7fafacc5f3245b1bb0a5e1eda216f3dbd221d11f) that `foreach` as a performance improvement but I will add it back because it breaks some themes.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/245

**Comment by Ataurr** [comment]
Please release as soon as.
