### ISSUE TITLE
Cannot log in after Unyson update

### ISSUE THREAD

**Issue by johnvdwalt** [ThemeFuse/Unyson#1858]
Hi

After installing the Unyson update, I can no longer log into my Wordpress site.  I can only log in if I physically delete the Unyson plugin.

Please send me an email address to contact so that I can provide URL and FTP details.

Thank you

John

**Comment by thednp** [comment]
Check if your have the file called `maintenance` maybe [this would help](https://www.google.ro/search?q=disable+maintenance+in+wordpress&oq=disable+maintenance+in+wordpress&aqs=chrome..69i57.5715j0j7&sourceid=chrome&ie=UTF-8).

**Comment by moldcraft** [comment]
`moldcraft[at]email.com`

**Comment by johnvdwalt** [comment]
Hi

 

Negative – I don’t have a file called maintenance.

 

John

**Comment by thednp** [comment]
The file is hidden, it's `.maintenance`, just like the `.htaccess` file.

**Comment by moldcraft** [comment]
There is something strange with your server. I deleted Unyson but still can't login through `http://SITE/wp-login.php`. I can't disable Unyson extensions, I get "Invalid nonce" error. I can't activate/deactivate plugins via checkboxes

![](https://static.md/18746c1d6ae7b0b63f19a6ad5dbddcb8.png)

I press "Apply", the page refreshes but the plugins are not activated.

Please ask your hosting why plugins can't be activated/deactivated via checkboxes and why you can't login from `http://SITE/wp-login.php`.
