### ISSUE TITLE
Using Page Builder in theme_pages

### ISSUE THREAD

**Issue by cojocaru3** [ThemeFuse/Unyson#1859]
Hello ! Is there a way to enable Page Builder for theme pages, created with add_theme_page ?

**Comment by moldcraft** [comment]
PageBuilder is just [an option-type](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.6.1/class-fw-extension-page-builder.php#L113)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/73
