### ISSUE TITLE
Problem Downloading Extensions

### ISSUE THREAD

**Issue by mikebens** [ThemeFuse/Unyson#186]
Trying to add extensions I get - 
Downloading the "Media" extension...
Cannot download the "Media" extension zip.

with debug true returns - 
Deprecated: Function ereg_replace() is deprecated in /public_html/wordpress/wp-admin/includes/class-ftp-pure.php on line 113

**Comment by moldcraft** [comment]
Can you add

```php
fw_print($response);
```

after [this line](https://github.com/ThemeFuse/Unyson/blob/6db4abf276f2ff50f70b7e9a3736372040a91d67/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L1825) (inside that `if`) ?

**Comment by mikebens** [comment]
Thanks & my apologies looks like server problem - 

WP_Error
(
    [WP_Error:errors] => array
    (
        [http_failure] => array
        (
            [0] => 'There are no HTTP transports available which can complete the requested request.'
        )
    )
    [WP_Error:error_data] => array()
)

**Comment by moldcraft** [comment]
[Thank you, too](https://github.com/ThemeFuse/Unyson/commit/367449656fb7554ba057ec536f6b3396a70e915d)
