### ISSUE TITLE
Trouble Polylang plugin and Options 

### ISSUE THREAD

**Issue by acidcrash2005** [ThemeFuse/Unyson#1863]
Hello!

I have a problem with options fields when create tranlation width Polylang plagin. If i create page, filling all my castom fileds that I create through Unyson. After than I create the translation of this page and options filed is have ralation with original post.

If I create a translation of one page, then all will have same options. If I change one of them, are changing all.

Help pleas!

**Comment by moldcraft** [comment]
It works on my side https://vid.me/KWbH

Please create a video how to reproduce the problem
