### ISSUE TITLE
WPMU non working with fw_get_db_post_option after update to 2.5.12

### ISSUE THREAD

**Issue by NazarkinRoman** [ThemeFuse/Unyson#1864]
Hi.

Today I have updated Unyson to the latest(2.5.12) version on my wordpress network installation and my theme stopped working. After some investigation turned out that `fw_get_db_post_option` function simply does not return any value from database. In case of this `fw_ext_page_builder_is_builder_post` function is also broken.

I have checked my database, here is actual value of `fw_options` metakey from some post:
```
a:5:{s:12:"page-builder";a:2:{s:4:"json";s:2:"[]";s:14:"builder_active";b:1;}s:11:"header_mode";s:4:"hide";s:10:"page_title";s:0:"";s:22:"seo-titles-metas-title";s:0:"";s:28:"seo-titles-metas-description";s:0:"";}
```

When I'm change some custom field, like `header_mode` or `page_title` - it saves successfully and I can see changes in database, but framework does not handle it.

Is there any way to debug this?

**Comment by andreiglingeanu** [comment]
> Is there any way to debug this?

The base class for all of this logic is [`FW_Db_Options_Model`](https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/class-fw-db-options-model.php). All of the DB helpers are defined in [this](https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/database.php) file. That's a starting point of an investigation of the problem, if you mind taking some time to break it down.

**Comment by NazarkinRoman** [comment]
@andreiglingeanu is some logic inside `FW_Db_Options_Model` was changed in latest version? Because everything is working properly on `2.5.10`, but after upgrade everything breaks up.

**Comment by moldcraft** [comment]
@NazarkinRoman Can you send me your admin/ftp details to `moldcraft[at]email.com`?

**Comment by NazarkinRoman** [comment]
@moldcraft sent email to you. Check inbox.

**Comment by moldcraft** [comment]
@NazarkinRoman Thank you. Inspecting...

**Comment by moldcraft** [comment]
I added in `{theme}/functions.php`

```php
if (isset($_GET['test'])) {

add_action('wp_head', function(){
	fw_print(
		fw_get_db_post_option(), 
		fw_get_db_post_option(null, 'header_mode')
	);
});

}
```

and it works fine

![](https://static.md/b166425f2c16659af08b86c0b6a212c4.png)

----

Please give the exact steps to reproduce the problem.

**Comment by NazarkinRoman** [comment]
It is wrong values. I have changed value of `header_mode` and it still returning default value(`automatically`).

Also, I have added next code to the `{theme}/content-page.php` file which is being called to render pages:
```
$header_mode = fw_get_db_post_option( null, 'header_mode', 'automatically' );
$is_builder = fw_ext_page_builder_is_builder_post();

var_dump($header_mode, $is_builder);
```

The output is `automatically` and `false` for front page, which is built with builder.

**Comment by danyj** [comment]
according to docs http://manual.unyson.io/en/latest/helpers/php.html#database

    fw_get_db_post_option($post_id, $option_id, $default_value = null)

try , 

    fw_get_db_post_option(get_the_ID(),'header_mode', 'automatically');

**Comment by NazarkinRoman** [comment]
@danyj tried this just before create issue. Does not work too.

**Comment by moldcraft** [comment]
@NazarkinRoman I can't login in your wp-admin anymore. I sent you an email with details

**Comment by moldcraft** [comment]
It still works on my side

![](https://static.md/b4bd2fc567240651e006b5e483f93b34.png)

![](https://static.md/3e982fda750695e8f38a7ef0e6fb44e1.png)

**Comment by NazarkinRoman** [comment]
I haven't tested it under `wp_head` action and it is simply useless for me to use it inside actions. I'm using framework's functions(`fw_get_db_post_option` and `fw_ext_page_builder_is_builder_post`) inside `content-page.php` which is being included into `loop.php` for page post type only(checked via `is_singluar()` and `is_page()`) after `the_post()` function call.

Then, inside `content-page.php` file those functions returns wrong results. In a previous version of Unyson(2.5.10) they was working perfectly. Please check this case.

**Comment by NazarkinRoman** [comment]
Many thanks, not it is working perfectly.
