### ISSUE TITLE
Slider images missing browser protocol

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1865]
There seems to be a bug  when slider images are added , 
they all endup without a protocol 

should be 

`http://localhost/wp/wp-content/uploads/img.jpg`

but they endup being 

`//localhost/wp/wp-content/uploads/img.jpg`

since I need to pick some colors from those images via imagecreatefromstring , this is causing alot of trouble , 

here is data example of slide image and slide thumb when saved 
http://prntscr.com/c2v16d

thumb has the protocol and the actual slide does not 

this is the print http://prntscr.com/c2uzqa

**Comment by andreiglingeanu** [comment]
http://stackoverflow.com/a/9646435/3220977

Look for a filter or request one in the extension's repository, I believe there is some infrastructure ready of the customisations to be made.

**Comment by danyj** [comment]
@andreiglingeanu  no no ,  that can be ok for  external links but not for internal images and everywhere else in every image picker and throughout WP images are loading with protocol. 

we cant use any GD functions because of this , here a simple getimagesize fails


http://prntscr.com/c2ysc2


`fw_print(getimagesize('//localhost/Development/WordPress/wp-content/uploads/2016/08/slide2.jpg'));
`

and this returns what is needed 

`fw_print(getimagesize('http://localhost/Development/WordPress/wp-content/uploads/2016/08/slide2.jpg'));
`


![screenshot_10](https://cloud.githubusercontent.com/assets/2340172/17472395/ce6b2818-5d4a-11e6-8b0c-2f7e4010d7c9.jpg)

**Comment by andreiglingeanu** [comment]
@danyj What about making a general purpose helper that will prepend the protocol (`http:` or `https:`) to the URL if it starts with `//`?

**Comment by danyj** [comment]
@andreiglingeanu  well we can do that , I was looking for a function but the point is that this is the only place ( slider )  where images are save without the protocol, everywhere else they are ok

**Comment by moldcraft** [comment]
> @andreiglingeanu What about making a general purpose helper

It already [exists](https://codex.wordpress.org/Function_Reference/set_url_scheme)

```php
echo set_url_scheme('//hello.world/wp-content/.../image.jpg');
```

**Comment by danyj** [comment]
thnx for the function but the question still stands , why is this the only place in the complete framework where images are saved without protocol , it is same image picker used everywhere

**Comment by moldcraft** [comment]
We thought it will prevent problems/warnings when the user will want to switch his site from http to https, or the site to work on both http and https

**Comment by andreiglingeanu** [comment]
> on both http and https

And it definitely will. I'm for leaving it as it is.
