### ISSUE TITLE
Multiple font variant for same font 

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#1866]
Sometimes we need to add multiple font variant of same font . Is it possible to convert select into multi select? Say we can add 300,500,700 

![untitled](https://cloud.githubusercontent.com/assets/12174913/17468246/e53224c8-5d47-11e6-9c5e-a2cd285f30c8.png)

**Comment by ashraf92** [comment]
I think we can make checkboxes instead of dropdown

**Comment by moldcraft** [comment]
Hello,

Thank you for suggestion but we can't change that select (string) to be a multi select (array) because a lot of users already have saved in db string value and themes expect the value to be string, so it will be come incompatible.

You can copy that option-type and create your own.
