### ISSUE TITLE
Content missing after moving page to another domain

### ISSUE THREAD

**Issue by sunrise85** [ThemeFuse/Unyson#1867]
Hi,
I have a page which has unyson installed with a theme (https://themeforest.net/item/berg-multipurpose-responsive-theme/13210984). And everything worked great until my page was moved from test server to new domain (production server). Now on the frontend I can see my content, but in backend content is missing.
For example, contact page frontend: http://hotelstyl70.pl/kontakt/ 
And backend: http://screenshooter.net/102753546/grwgvis
Can you please help me?
Regards!

**Comment by thednp** [comment]
You should contact the theme author for support as this is a public development portal.
