### ISSUE TITLE
Can't change the event time interval

### ISSUE THREAD

**Issue by Breakern** [ThemeFuse/Unyson#1868]
Hi, I have tried adding this to my theme funtions.php to change the event time intervals

```
add_filter('fw_option_type_event_datetime_pickers', function($data){
    $data['from']['step'] = 10;
    $data['to']['step'] = 10;

    return $data;
});
```

 and I have also tried editing class-fw-option-type-event.php directly to add

`'step' => 10`

but can still only add event times in 30 minute intervals.

Where am I going wrong? Thanks.

**Comment by Breakern** [comment]
Any response to this? Thanks.

**Comment by player0k** [comment]
Where did you get information about "step" parameter?

**Comment by Breakern** [comment]
Hi @player0k  it was posted here -

https://github.com/ThemeFuse/Unyson-Events-Extension/issues/15

**Comment by player0k** [comment]
Do you have last version of events extension?

**Comment by player0k** [comment]
1.0.10 or 1.0.9 ?

**Comment by Breakern** [comment]
1.0.10 Yes.

**Comment by Breakern** [comment]
With the lack or responses, am I to accept that event times are limited to 30 minute intervals, and a one hour minimum?

**Comment by moldcraft** [comment]
@Breakern Unfortunately at the moment, yes. Maybe we will create Events v2 and fix all issues related to date https://github.com/ThemeFuse/Unyson/issues/1722

**Comment by moldcraft** [comment]
Or you can inspect the code and come with a solution with pull request

**Comment by Breakern** [comment]
Thank you. Beyond my capapbilites unfortunately.
