### ISSUE TITLE
unyson pagebuilder conflict with event manager plugin

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1869]
i have just installed this event manager plugin: https://en-gb.wordpress.org/plugins/events-manager/

what i am trying to achieve is to build my single event page within page builder and adding dynamic elements generated by the events manager i.e:
1 columns that displays the title and text and then another sidebar that displays a map and image.

also to mention, i have customized my unyson framework so i can also add a header and a footer to my page builder, so i am literally building the whole page every time in the page builder and utilizing the save template so i don't have to repeat this process every time. building my framework in this way has made very versatile in terms of how to customize the page.

so into the problem...

the events manager seems to be stripping all the elements that i added to the page builder from any div and displays it in the text editor

**Comment by moldcraft** [comment]
Hello,

Please give a screenshot and the exact steps to reproduce the problem, or a video/screencast.

**Comment by ahm-3d** [comment]
after installing the event manager plugin, add a new event, add a title and select event dates, then build the page using the page builder by adding few elements then click on publish. the page refreshes back to the wp-editor and if you click back on the page builder you will see all the page elements that were added have dissapeared and a text element is added.

[event-manager-unyson-conflict.mp4.zip](https://github.com/ThemeFuse/Unyson/files/429087/event-manager-unyson-conflict.mp4.zip)

**Comment by moldcraft** [comment]
Please report this problem to event manager plugin. It looks like they include their own jquery-ui styles and break/overwrite other/our styles
