### ISSUE TITLE
custom post type as an extension

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1870]
hi, i would like to add a new custom post type as an extension just like the unyson event and lesson extensions. is there a particular framework i need to follow to achieve this?

i know i could simply add the new cpt in the posts.php but i am going to have meta boxes associated to the cpt so i would like to contain everything in their respective directory.

i am thinking of duplicating the events extension and stripping it down to what i need but i am worried that could take some time as it is a big extension

**Comment by thednp** [comment]
You should be checking the `portfolio` extension's code for a complete, fully fledged extension, also checking the code of the extensions you mentioned is good enough.
`site/wp-content/plugins/unyson/framework/extensions/EXTENSION_NAME`

**Comment by ahm-3d** [comment]
none of the extensions fully follow the structure specified within the documentation: http://manual.unyson.io/en/latest/extensions/introduction.html#directory-structure

**Comment by ahm-3d** [comment]
the point i dont understand from the extension structure documentation is this: 

options/ - A directory containing option files: post types, taxonomies or custom options. The framework will not automatically pick them (like theme options), only the extension decides how to use these options. You can access them through the $ext->get_[...]_options() methods. Users can overwrite in the theme any file from the options/ directory, by creating {theme-name}/framework-customizations/extension/{extension-name}/options/{file-name}.php

**Comment by thednp** [comment]
That's why I'm saying: look at the existing code, the extensions we have now are great starting points to just about anything we need, really.

**Comment by danyj** [comment]
@moldcraft  ,  @ahm-3d  has a point there should be a mechanism for it. we cant use 
    
    register_post_type

within theme since it is plugin territory and TF theme check fails

**Comment by danyj** [comment]
@moldcraft  @andreiglingeanu ,  do you guys think you can come up with built in plugin function that would let us add custom post type from the theme folder and in same time pass TF check? 

@ahm-3d  and I would like to create either extension or just a cpt but from the theme , not adding own plugin for it. 


this does not pass TF check if added in any theme files 



	function thz_custom_post_type() {
	
	
		$base = 'thzsection';
		$label = esc_html__('Thz Section','fw');
	
		// custom type
		register_post_type($base,
			// options
			array(
				'labels' => array(
					'name' => $label,
					 /* This is the Title of the Group */
					'singular_name' => sprintf(esc_html__('%s Post', 'fw') , $label),
					 /* This is the individual type */
					'all_items' => sprintf(esc_html__('All %s', 'fw') , $label),
					 /* the all items menu item */
					'add_new' => esc_html__('Add New', 'fw') ,
					 /* The add new menu item */
					'add_new_item' => sprintf(esc_html__('Add New %s', 'fw') , $label),
					 /* Add New Display Title */
					'edit' => esc_html__('Edit', 'fw') ,
					 /* Edit Dialog */
					'edit_item' => sprintf(esc_html__('Edit %s', 'fw') , $label),
					 /* Edit Display Title */
					'new_item' => sprintf(esc_html__('New %s', 'fw') , $label),
					 /* New Display Title */
					'view_item' => sprintf(esc_html__('View %s', 'fw') , $label),
					 /* View Display Title */
					'search_items' => sprintf(esc_html__('Search %s', 'fw') , $label),
					 /* Search Custom Type Title */
					'not_found' => esc_html__('Nothing found in the Database.', 'fw') ,
					 /* This displays if there are no entries yet */
					'not_found_in_trash' => esc_html__('Nothing found in Trash', 'fw') ,
					 /* This displays if there is nothing in the trash */
					'parent_item_colon' => ''
				) ,
				 /* end of arrays */
				'public' => false,
				'publicly_queryable' => true,
				'exclude_from_search' => true,
				'show_ui' => true,
				'query_var' => false,
				'menu_position' => 9,
				'menu_icon' => 'dashicons-tagcloud',
				 /* you can specify its url slug */
				'has_archive' => false,
				'capability_type' => 'post',
				'hierarchical' => true,
	
				/*  what's enabled in the post editor */
				'supports' => array(
					'title',
					'editor',
					'author',
					'revisions',
				)
			)
		/* end of options */
		);
		/* end of register post type */
	
		// custom categories 
		register_taxonomy(
			'thzsection_category',
			'thzsection',
			array(
				'hierarchical' => true,
				'public' => false,
				'show_ui' => true,
				'show_admin_column' => true,
				'show_in_nav_menus' => true,
				'labels' => array(
					'name' => sprintf(esc_html__( '%s Categories', 'fw') , $label), /* name of the custom taxonomy */
					'singular_name' => sprintf(esc_html__( '%s Category', 'fw') , $label), /* single taxonomy name */
					'search_items' =>  sprintf(esc_html__( 'Search %s Categories', 'fw') , $label), /* search title for taxomony */
					'all_items' => sprintf(esc_html__( 'All %s Categories', 'fw') , $label), /* all title for taxonomies */
					'parent_item' => sprintf(esc_html__( 'Parent %s Category', 'fw') , $label), /* parent title for taxonomy */
					'parent_item_colon' => sprintf(esc_html__( 'Parent %s Category:', 'fw') , $label), /* parent taxonomy title */
					'edit_item' => sprintf(esc_html__( 'Edit %s Category', 'fw') , $label), /* edit custom taxonomy title */
					'update_item' => sprintf(esc_html__( 'Update %s Category', 'fw') , $label), /* update title for taxonomy */
					'add_new_item' => sprintf(esc_html__( 'Add New %s Category', 'fw') , $label), /* add new title for taxonomy */
					'new_item_name' => sprintf(esc_html__( 'New %s Category Name', 'fw') , $label) /* name title for taxonomy */
				),
				'rewrite' => array( 'slug' => $base . '_cat' ),
			)
		);
	}

**Comment by andreiglingeanu** [comment]
@danyj I think defining them from an extension that is active only within your theme is just fine.

**Comment by danyj** [comment]
@andreiglingeanu ,  get the TF theme check plugin and you get warning

![screenshot_13](https://cloud.githubusercontent.com/assets/2340172/17638988/c3cda000-60ee-11e6-8b1e-32b2dd9c0f61.jpg)

**Comment by andreiglingeanu** [comment]
@danyj Obviously, this plugin do a static analysis on the code. It knows nothing about how it works under the hood. The only way to know this is to ask the TF guys about this particular use case.

**Comment by danyj** [comment]
@andreiglingeanu  bud , I would be the first to argue with them but when it comes to this and they have option to delay or refuse the theme , I dont want to risk to write bunch of lines of code for Unyson and at the end I have to move it to a plugin. Thus I am asking for mechanism that would save us all the trouble. 


I posted a simple question a year ago about escaping and never had gotten any answers, even worse my post was flagged as spam 
https://forums.envato.com/t/output-sanitizing-issue-we-need-theme-reviewers-input-please-advise/11854/3

because I mentioned  Unsyon and this git , so I think you understand what I mean here.

**Comment by andreiglingeanu** [comment]
@danyj Of course, we are also taking the path of moving the heavy logic in the extensions, while storing them in the Theme itself. Having a plugin to bring extensions into the theme looks like a non-sense to me, even if extensions have 0 value without a good integration from the Theme itself.

We better formulate a request to them, with a list of good things this gives to users. Having lots of guys who will argue against their sceptical look at all of this is what we all need in order to get Unyson ideas moving forward.

**Comment by duongancol** [comment]
@andreiglingeanu , @danyj This requirement is not only from TF it's from WordPress.org. You can read this [post](http://justintadlock.com/archives/2013/09/14/why-custom-post-types-belong-in-plugins) to know more about the reason.

**Comment by thednp** [comment]
@ahm-3d have you seen [this](https://github.com/ThemeFuse/Unyson/issues/1407).

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/1870#issuecomment-238289628
>
> the point i dont understand from the extension structure documentation is this:
>
> `options/` - A directory containing option files: post types, taxonomies or custom options. The framework will not automatically pick them (like theme options), only the extension decides how to use these options. You can access them through the `$ext->get_[...]_options()` methods. Users can overwrite in the theme any file from the options/ directory, by creating {theme-name}/framework-customizations/extension/{extension-name}/options/{file-name}.php

[`$extension->get_post_options()`](https://github.com/ThemeFuse/Unyson/blob/v2.5.12/framework/core/extends/class-fw-extension.php#L431-L433) -> [`$extension->get_options()`](https://github.com/ThemeFuse/Unyson/blob/v2.5.12/framework/core/extends/class-fw-extension.php#L325-L327) uses `locate_path()` so it searches for the file in theme and the user can overwrite it. It is extension author decision to allow options overwrite in theme or to store them hardcoded somewhere in `includes/...` directory.

If the docs is confusing, you can improve it https://github.com/ThemeFuse/Unyson-Documentation/blob/master/extensions/introduction.rst

> built in plugin function that would let us add custom post type from the theme folder and in same time pass TF check?

It is cheating. If they will find this they can ban Unyson or restrict the function we created. Better play by the rules or request TF to change the rules.

----

You can create post types in extension [`posts.php`](https://github.com/ThemeFuse/Unyson/blob/v2.5.12/framework/core/components/extensions.php#L597-L601) or in extension class `add_action('init', ...)`.
