### ISSUE TITLE
[MegaMenu] How to add option to add image background

### ISSUE THREAD

**Issue by ttn10** [ThemeFuse/Unyson#1872]
Hi, i have Megamenu like this:
http://i.imgur.com/lKsurV2.jpg?1
how to add image background for it?
eg: http://i.imgur.com/gzbBPRl.jpg

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/240

**Comment by ttn10** [comment]
Hi @danyj
I tried this code: https://github.com/ThemeFuse/Unyson/issues/240#issuecomment-188760551
but on megamenu not button options: http://i.imgur.com/Ok8Js24.png
You can give me example?

**Comment by danyj** [comment]
I did not test that lately but you right , the options are not there anymore. There must have been some changes in meantime,  @moldcraft  might find time for it.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/commit/20bc79926e99438ee71794d48f68b5d8557a653b

**Comment by moldcraft** [comment]
The changes were in a separate git branch that I forgot to merge.

Use [this filter](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/20bc79926e99438ee71794d48f68b5d8557a653b/helpers.php#L69)

**Comment by ttn10** [comment]
hi @moldcraft ,
i added my option, check this image: http://i.imgur.com/QOU1x4Z.png, http://i.imgur.com/Fsp42Ew.png
How to view this option into frontend, tks

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/commit/20bc79926e99438ee71794d48f68b5d8557a653b#diff-37103b40d038920dbb5e8b957d21a0c8R82

**Comment by ttn10** [comment]
Hi, I got item option value from the database by using `fw_ext_mega_menu_get_db_item_option`
my code wp-theme\inc\helpers.php
`function fw_add_option_megamenu($item) {
$options = array(
'bg_megamenu' => array(
'label' => esc_html__('Mega Menu background', 'fw'),
'desc' => esc_html__('Choose image', 'fw'),
'type' => 'upload',
)
);
return $options;
}
add_filter( 'fw:ext:megamenu:item-options', 'fw_add_option_megamenu' );

function fw_title_add_background($opt) {
$opt['title'] = esc_html__('Add background', 'fw');
return $opt;
}
add_filter( 'fw:ext:mega-menu:item-options:popup-option', 'fw_title_add_background');

$bg = function_exists('fw_ext_mega_menu_get_db_item_option') ? (fw_ext_mega_menu_get_db_item_option($item, 'bg_megamenu')) : '';
fw_print($item->object_id);`
Menu in back-end:
http://i.imgur.com/czeXGYn.png
Menu front-end:
http://i.imgur.com/Ybe9fRp.png
In Elements:
http://i.imgur.com/714888F.png
How do like this:
http://i.imgur.com/THlmuAR.png or using css inline
I want add background image for megamenu in ul.sub-menu.mega-menu-row, tks

**Comment by danyj** [comment]
@ttn10 , stop what you are doing , the release has been canceled , options must be separated 

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/259
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/issues/14
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/issues/13

**Comment by ttn10** [comment]
thank you, now wait, right?

**Comment by danyj** [comment]
yes wait , there will be different hooks to do this

**Comment by moldcraft** [comment]
@ttn10 https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/issues/14#issuecomment-247705743

**Comment by ttn10** [comment]
Tks
I had options in backend...
http://i.imgur.com/kSGY5aI.png
http://i.imgur.com/fWKKztd.png
but i don't understand
`3. Get db value using these functions (the value structure is similar to multi-picker option-type)`
you can give me a example?

**Comment by moldcraft** [comment]
```php
fw_print(fw_ext_mega_menu_get_db_item_option($item_id));
```

**Comment by ttn10** [comment]
Hi,
[http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi-picker-get-db-value](http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi-picker-get-db-value)
this link not working!

**Comment by moldcraft** [comment]
@ttn10 Thanks for reporting. I recently [refactored options docs](https://github.com/ThemeFuse/Unyson-Documentation/commit/0e94b0cf4d36cbde4449d9323beac94705e6a033)

**Comment by dobromir-hristov** [comment]
@moldcraft Maybe you should mention in the docs, as an example, that to access a mega menu custom option value you have to point to the `menu_type/option_id` because i was banging my head for a good hour to figure out it was as simple as `fw_ext_mega_menu_get_db_item_option($item_id, 'column/my_custom_option')`. 
Also if someone is to lets say add markup to the mega menu, he should copy the walker and override it, right?

**Comment by moldcraft** [comment]
[The docs](http://manual.unyson.io/en/latest/extension/megamenu/index.html#item-custom-options) contains a small code snippet. To find the the structure of the value just `fw_print($values);`.

Yes, you should overwrite the walker (which also is described in the docs)

**Comment by dimavrn** [comment]
> 
> 
> [The docs](http://manual.unyson.io/en/latest/extension/megamenu/index.html#item-custom-options) contains a small code snippet. To find the the structure of the value just `fw_print($values);`.
> 
> Yes, you should overwrite the walker (which also is described in the docs)

How i can get value from database? In last version it is retirn 'default'
