### ISSUE TITLE
page builder functions are not working

### ISSUE THREAD

**Issue by seevidyadhar** [ThemeFuse/Unyson#1873]
Hello there, I am not a programmer and don't know coding part. But looking at description and overview tutorial I found it easy to use as non-programmer. However, I installed unyson plugin and activated all extensions including pagebuilder. But when I started trying it on new page, the page builder elements would not allow me to edit. Like I could insert layout columns and content elements or media elements but when it comes to editing, it simply gives transparent screen with options inside. And when I click on any field options it just goes off. I uninstalled plugin and reinstalled zip file downloaded from git repository but no improvement. I don't know if I m doing some mistake in using it or there is any bug.
Please help.

**Comment by thednp** [comment]
Have some screenshots?

**Comment by seevidyadhar** [comment]
Thanks for quick response. The issue was due to conflict with another page builder plugin. I uninstalled it and now unyson works perfectly. 
It looks great for use of non-programmer like me. So thank u for such great product. I have one question though. Is it possible to send on site real-time notifications like facebook about activities of other users of site? I want to create community website where users can ask questions and discuss some issues. So I need to give them facility to notify user groups they want to inform about their updates. Please help

**Comment by seevidyadhar** [comment]
Also where can I found video tutorials about how to use Unyson for maximum result. Like the tutorials on your site seems to be more advanced and only programmer can understand how to make theme.

**Comment by thednp** [comment]
> I have one question though. Is it possible to send on site real-time notifications like facebook about activities of other users of site? I want to create community website where users can ask questions and discuss some issues. So I need to give them facility to notify user groups they want to inform about their updates.

No. The framework is here mainly for theme options, page builder as well as other content extensions, SEO, google analytics, etc. To my knowledge there is no framework to be able to do this. You should find other plugins in the [wordpress](https://wordpress.org/plugins/) repository.

> Also where can I found video tutorials about how to use Unyson for maximum result. Like the tutorials on your site seems to be more advanced and only programmer can understand how to make theme.

http://manual.unyson.io/
