### ISSUE TITLE
Page Builder generated HTTP ERROR 500

### ISSUE THREAD

**Issue by LiFux-sk** [ThemeFuse/Unyson#1876]
If Page Builder is active, i get an HTTP Error 500 for all pages.

WP-Debug:

> Fatal error: Uncaught Error: Call to undefined function menu_page_url() in /var/www/vhosts/creativa-fotografie.de/www/creativa-fotografie.de/wp-content/themes/exposure-parent/framework-customizations/theme/options/posts/page.php:3 Stack trace: #0 /var/www/vhosts/creativa-fotografie.de/www/creativa-fotografie.de/wp-content/plugins/unyson/framework/helpers/general.php(555): require() #1 /var/www/vhosts/creativa-fotografie.de/www/creativa-fotografie.de/wp-content/plugins/unyson/framework/core/components/theme.php(74): fw_get_variables_from_file('/var/www/vhosts...', Array) #2 /var/www/vhosts/creativa-fotografie.de/www/creativa-fotografie.de/wp-content/plugins/unyson/framework/core/components/theme.php(116): _FW_Component_Theme->get_options('posts/page') #3 /var/www/vhosts/creativa-fotografie.de/www/creativa-fotografie.de/wp-content/plugins/unyson/framework/helpers/database.php(132): _FW_Component_Theme->get_post_options('page') #4 /var/www/vhosts/creativa-fotografie.de/www/creativa-fotografie.de/wp-content/plugins/unyson/fra in /var/www/vhosts/creativa-fotografie.de/www/creativa-fotografie.de/wp-content/themes/exposure-parent/framework-customizations/theme/options/posts/page.php on line 3

**Comment by moldcraft** [comment]
> Fatal error: Uncaught Error: Call to undefined function menu_page_url() in /var/www/vhosts/creativa-fotografie.de/www/creativa-fotografie.de/wp-content/**themes/exposure-parent/framework-customizations/theme/options/posts/page.php**:3

It seems to be a theme issue. Please report it to theme author

**Comment by andronic90** [comment]
Hello,
please make sure that you have the latest version of "Exposure" installed ( Dashboard/ Updates/ Check updates). If the problem persist please contact the support team : http://support.themefuse.com/hc/en-us/requests/new
