### ISSUE TITLE
Cant get addable-popup template to work

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1877]
@moldcraft , @andreiglingeanu  I have addable popup option in slider custom.php  and one option by name b inside, 

4 slides and I get all b options listed in console via 

    'template' => '{{ if(b){ console.log(b) } }}',

but at the end I get 

    ReferenceError: b is not defined
    at eval

http://prntscr.com/c3q4j7

I tried all possible if undefined , typeof  checks but same issue. Not sure what triggers it.

**Comment by danyj** [comment]
this is the option


		'btns' => array(
			'type' => 'addable-popup',
			'value' => array(),
			'label' => __('Add button', 'fw'),
			'desc'  => __('Add slide button.', 'fw'),
       		'template' => '',
			'popup-title' => __('Slide button settings', 'fw'),
			'size' => 'large',
			'add-button-text' => __('Add', 'fw'),
			'sortable' => true,
			'limit' => 2,
			'popup-options' => array(
				'b' => array(
					'type' => 'thz-button',
					'value' => array(),
					'label' => false,
				),
					
			),
		)

**Comment by andreiglingeanu** [comment]
@danyj Do a `console.log(values)` [here](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/addable-popup/static/js/addable-popup.js#L111) and see what you get.

**Comment by danyj** [comment]
8 objects , http://prntscr.com/c4073m  same as my console log

**Comment by danyj** [comment]
@andreiglingeanu , is there a way to get the number of added popups , that would help me build a template like 

Popup 1
Popup 2

**Comment by danyj** [comment]
@moldcraft  @andreiglingeanu  ,sorry  to bump this but I need a solution to move one , 

 since I cant find what the bug is with this b var thing is there a way  for template do say something like 


     'template' => '{{ if(popup.length){ Popup popup.index } }}',

wich should make template be 


Popup 1 
Popup 2 

?

**Comment by andreiglingeanu** [comment]
@danyj Apply this eb21e20b97f3cca684ee305145f8d703567b86fa to your unyson and use this:

```
'template' => 'Popup {{= _itemsWrapper.find(".item").length + 1 }}',
```

**Comment by danyj** [comment]
js error http://prntscr.com/c4cf15

**Comment by danyj** [comment]
and getting same bug I had in beginning with 
       'template' => 'Popup {{ console.log(_itemsWrapper)}}',


see last line
http://prntscr.com/c4cfmf

**Comment by danyj** [comment]
this is definitely bug within the slider extension , 
I moved the option to theme settings and no js errors plus I am getting the log for your workaround and my b option name ,

**Comment by andreiglingeanu** [comment]
@danyj My workaround doesn't work correctly after page refresh. I just checked. But you have a starting point.

And yes, seems like you have a bug from outside but I don't know what's happening inside the slider extension. I will re-open the issue.

**Comment by danyj** [comment]
to test add your addable popup with template console log here 
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/media/extensions/slider/extensions/bx-slider/options/custom.php

I just did this within the theme settings 

    'template' => '{{ console.log(JSON.parse(b.json))}}',

and my option json is coming back as expected 

http://prntscr.com/c4ck51

**Comment by moldcraft** [comment]
![bvuwrxq](https://cloud.githubusercontent.com/assets/1475489/17597187/74835c02-5ffd-11e6-9ee4-09880cd7059f.jpg)

**Comment by danyj** [comment]
:100:

**Comment by moldcraft** [comment]
> Popup 1
> Popup 2

This https://github.com/ThemeFuse/Unyson/commit/1d0d558196754955868c727e8c459dda3d92982c allows you to do this trick

```php
$options = array(
	'btns' => array(
		'type' => 'addable-popup',
		'value' => array(),
		'label' => __('Add button', 'fw'),
		'desc'  => __('Add slide button.', 'fw'),
		'template' => '{{ if (b) { }}<span class="n">{{- b }}</span>{{ } }}',
		'popup-title' => __('Slide button settings', 'fw'),
		'size' => 'large',
		'add-button-text' => __('Add', 'fw'),
		'sortable' => true,
		'limit' => 2,
		'popup-options' => array(
			'b' => array(
				'type' => 'text',
				'label' => false,
			),
		),
	),
);
```

```css
.fw-option-type-slides .fw-option-type-addable-popup .items-wrapper > .item:nth-child(1) .content .n:after {
    content: " 1";
}
.fw-option-type-slides .fw-option-type-addable-popup .items-wrapper > .item:nth-child(1) .content .n:after {
    content: " 2";
}
```

**Comment by andreiglingeanu** [comment]
Or even [this](https://davidwalsh.name/css-counters), if @moldcraft touched CSS side.

**Comment by danyj** [comment]
@moldcraft 

css should be this 


```
.fw-option-type-slides .fw-option-type-addable-popup .items-wrapper .item:first-of-type .content .n:after {
    content: " 1";
}
.fw-option-type-slides .fw-option-type-addable-popup .items-wrapper > .item:last-of-type .content .n:after {
    content: " 2";
}
```

since there is an input in between http://prntscr.com/c4i1tw  and counts as first:child

**Comment by moldcraft** [comment]
> since there is an input in between

Again https://github.com/ThemeFuse/Unyson/issues/1877#issuecomment-239228887

**Comment by danyj** [comment]
got it thnx !

**Comment by danyj** [comment]
And same bug with scratch theme bx-slider
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/media/extensions/slider/extensions/bx-slider/options/custom.php



```
<?php if (!defined('FW')) die('Forbidden');
$options = array(
	'subtitle' => array(
		'type' => 'text',
		'label' => __('Subtitle', 'unyson'),
		'value' => '',
		'desc' => __( 'Choose a subtitle for your slide.', 'unyson' )
	),
	'btns' => array(
		'type' => 'addable-popup',
		'value' => array(),
		'label' => __('Add button', 'fw'),
		'desc'  => __('Add slide button.', 'fw'),
		'template' => '{{ if(b){ console.log(b);} }}',
		'popup-title' => __('Slide button settings', 'fw'),
		'size' => 'large',
		'add-button-text' => __('Add', 'fw'),
		'sortable' => true,
		'limit' => 2,
		'popup-options' => array(
			'b' => array(
				'type' => 'text',
				'label' => false,
			),
		),
	)
);

```
http://prntscr.com/g3ket4
