### ISSUE TITLE
wp-editor warning with some parameters

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1880]
In wp-editor if I pass `tinymce' => false or  true`  I get an error.

`Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/unyson/framework/includes/option-types/wp-editor/includes/class-fw-wp-editor-settings.php on line 185`

Also `quicktags` option has no effect.

unyson: 2.5.12
wp : 4.5.3

**Comment by ivandotv** [comment]
I've just dropped the `wp-editor` option code from the documentation and added those extra properties.
In scratch theme.

**Comment by andreiglingeanu** [comment]
@ivandotv Okay. I will come back with a solution a bit later.

<hr>

By the way, why would you want to remove `tinymce` or `quicktags` tab?

**Comment by ivandotv** [comment]
I'm using it as an option field for the user to make a gallery. "Add media" is the only thing that is shown.
And later I use regex to extract the gallery shortcode.

Also , it appears that `'quicktags' option works (probably because of the `tinymce` error , it didn't work)

**Comment by andreiglingeanu** [comment]
> And later I use regex to extract the gallery shortcode.

That's from JS? If yes, you are [doing](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/v1.0.0/static/js/plugin.js#L205-L217) it [wrong](https://github.com/WordPress/WordPress/blob/efb315afb904f73102943a769e51c5252aba422d/wp-includes/js/shortcode.js#L7).

<hr>

I'll come back tomorrow with a solution for this.

**Comment by ivandotv** [comment]
I'm extracting the code via php.
How would you do it?
Also, editor errors have nothing to do with what I'm doing.

**Comment by andreiglingeanu** [comment]
Issue fixed.

<hr>

@ivandotv Use [those](https://codex.wordpress.org/Shortcode_API#Shortcode_API) functions.
