### ISSUE TITLE
[bug] shortcodes with hyphen in the tag cannot be used as components for other shortcodes, similar to `button` inside `call-to-action` 

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1881]
I tried to replicate the functionality of the `call-to-action` shortcode as it uses the `button` shortcode as a content component, but my component shortcode is `social-network` so it doesn't work. If I rename it to `social_network` it works just fine.

**Comment by moldcraft** [comment]
Please give the exact steps to reproduce the problem (maybe with screenshots).

**Comment by thednp** [comment]
Steps to reproduce:
* make a new shortcode out of `call-to-action` called `call-to-action-test` or something
* replace the `button` with `media-image` in the `call-to-action-test/options.php` like below

```javascript
'media-image' => ( $img = fw()->extensions->get( 'shortcodes' )->get_shortcode( 'media-image' ) )
	? array(
		'type'          => 'popup',
		'popup-title'   => __( 'Add image', 'fw' ),
		'button'        => __( 'Configure Image', 'fw' ),
		'popup-size'   => 'large',
		'popup-options' => $img->get_options()
	) : array()
```
* now  go edit some page and see the error

**Comment by moldcraft** [comment]
Better don't use in shortcode options ids with hypen.

**Comment by thednp** [comment]
It doesn't matter the `id`. It seems the it should match the shortcode tag name.

**Comment by moldcraft** [comment]
Try

```php
( ( $img = fw()->extensions->get( 'shortcodes' )->get_shortcode( 'media-image' ) )
    ? array(
        'media-image' => array(
            'type'          => 'popup',
            'popup-title'   => __( 'Add image', 'fw' ),
            'button'        => __( 'Configure Image', 'fw' ),
            'popup-size'   => 'large',
            'popup-options' => $img->get_options()
        )
    )
    : array()
)
```

**Comment by thednp** [comment]
Not good, the error vanished but no `media-image` option.

**Comment by moldcraft** [comment]
It seems that the `'media-image'` shortcode is loaded after your shortcode. Better create your custom option type that will use `'media-image'` shortcode options on render and `_get_value_from_input()`

**Comment by thednp** [comment]
No need, it already works, just without hyphen. That is the point. I would have to disable all shortcodes with hyphen and recreate them all without hyphen to be able to use them as components for other shortcodes.

**Comment by moldcraft** [comment]
I think this is the problem/fix

```php
add_action('fw_init', function(){
	fw_print(
		fw()->extensions->get( 'shortcodes' )->get_shortcode( 'media-image' ),
		fw()->extensions->get( 'shortcodes' )->get_shortcode( 'media_image' )
	);
});
```

**Comment by thednp** [comment]
Where is this fix supposed to go?

Will it solve the issue for other hyphen shortcode tags such as `media-video`?

**Comment by moldcraft** [comment]
You are allowed to create shortcodes (directory names) with hyphen, but internally the hyphen will be replaced with `_`, so don't use `->get_shortcode( 'shortcode-name' )` but use `->get_shortcode( 'shortcode_name' )`

**Comment by thednp** [comment]
Let me try that right away. Meanwhile what about the fix you wrote above?

**Comment by moldcraft** [comment]
How a `fw_print()` can be a fix? I meant the fix is to not use `->get_shortcode( 'shortcode-name' )`

**Comment by thednp** [comment]
I see, so the core coding already knows `shortcode-name` is actually `shortcode_name` when it comes to internals. That's good.
