### ISSUE TITLE
Theme options not saving on live server

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1883]
@moldcraft  Testing on live server admin-ajax.php in theme save response is 0.
I can provide user info if u skype me

**Comment by danyj** [comment]
even reset options , same thing

**Comment by andreiglingeanu** [comment]
@danyj Test if your option types has ajax actions in them, you should load them while `defined('DOING_AJAX')`.

https://github.com/ThemeFuse/Unyson/blob/f38bd9c81d61cb6b515fcbc119340db8924b9270/framework/includes/hooks.php#L18

**Comment by danyj** [comment]
everything works on local , this is my friends  hosting trial and I am testing his live server with unyson , nothing is saving  or reseting http://prntscr.com/c43q1c., I tested on my own dedicated and it works , so no idea what this is

**Comment by andreiglingeanu** [comment]
It returns `0` only when it reaches [this](https://github.com/WordPress/WordPress/blob/master/wp-admin/admin-ajax.php#L104).

That is, for some reason, ajax actions don't get attached. First step is to check with `has_action()` [here](https://github.com/WordPress/WordPress/blob/master/wp-admin/admin-ajax.php#L81).

**Comment by danyj** [comment]
http://take.ms/dBZfB,  how to tesdt and what ?

**Comment by danyj** [comment]
max_input_vars  seems like it ,  1000  is set as limit
