### ISSUE TITLE
Add Portfolio Category to permalink

### ISSUE THREAD

**Issue by asier-laukoa** [ThemeFuse/Unyson#1885]
Hi,

is there any way of adding portfolio category to the portfolio permalink. Now I have something like this:

http://mydevdomain.com/game/submarine-arrow/

and I need something like this:

http://mydevdomain.com/game/simulator-game/submarine-arrow/

I've been looking through the documentation and Google, but I could not get any answer to this problem.

Any idea of how can I get this working?

Thanks!

**Comment by moldcraft** [comment]
Hello,

I don't know the answer.

This question is not related to Unyson because the extension just registers a post type (portfolio) and everything else is handled by WP. So better to ask this question on http://wordpress.stackexchange.com/

**Comment by asier-laukoa** [comment]
Hi again,

This question is related to Unyson because when you register a custom post type (portfolio) you can edit the "rewrite" argument to say the slug format, for example:

'rewrite'		=> array('slug' => 'portfolio/%fw-portfolio-category%'),

But I don't know if Unyson plugin has a hook available to overwrite the register_post_type function.

Thanks!

**Comment by moldcraft** [comment]
@asier-laukoa Can you provide a pull request?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1917
