### ISSUE TITLE
Theme Integration - Shortcode Options

### ISSUE THREAD

**Issue by Mopsan** [ThemeFuse/Unyson#1886]
In manuals Theme Integration on the [link](http://manual.unyson.io/en/latest/options/integrate.html#content) describes how to integrate in **{theme}/functions.php** **Customizer Options** (use fw_get_db_customizer_option), **Settings Options** (use fw_get_db_settings_option) and **Post Options** (use fw_get_db_post_option).
But how can integrate in **{theme}/functions.php** options with **Shortcode Options** (Ex. {theme}/framework-customizations/extensions/shortcodes/shortcodes/icon-box/options.php).

**Comment by moldcraft** [comment]
Hello,

There is no way/function to get options values of some shortcode in some page. Shortcodes options are available only in shortcode `view.php` as `$atts` array. http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content
