### ISSUE TITLE
cant display custom buttons on wp-editor type

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1888]
Hi, i am having trouble customising the wp-editor, can some one advise me where i am going wrong?

```
'description' => array(
	'type'  => 'wp-editor',
	'shortcodes' => true,
	'media_buttons' => false,
	'tinymce' => array(
		'theme_advanced_buttons1' => 'bold, italic, ul, ol',
		'theme_advanced_buttons2' => '',
		'theme_advanced_buttons3' => '',
		'theme_advanced_buttons4' => '',
	),
	'label' => __('Description', 'fw')
```

**Comment by andreiglingeanu** [comment]
What's really going on wrong? Buttons are not showing?

**Comment by ahm-3d** [comment]
i only want to display the buttons that i choose. in the scenario above i just want the bold, italic, ul, ol buttons. and no media buttons option.

**Comment by ahm-3d** [comment]
currently the code above is showing the default editor style without the media button and ignoring what i have specified withing the tinymce array

**Comment by andreiglingeanu** [comment]
That's how you do this:

```php
'text' => array(
	'type' => 'wp-editor',
	'shortcodes' => true,
	'media_buttons' => false,
	'tinymce' => array(
		// can be groupped with | or ,
		'toolbar1' => 'bold | italic, bullist | numlist | unyson_shortcodes',
		'toolbar2' => '',
		'toolbar3' => '',
		'toolbar4' => '',
	),

	'quicktags' => false // or true, to enable the text tab
)
```
![Result](https://cloud.githubusercontent.com/assets/2979628/17643805/4e1d8cfa-617d-11e6-9a2b-7caf1e80f3d5.png).

Please refer to this [from](https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/class-wp-editor.php#L58) now on.
Full list of TinyMCE options can be found [here](https://www.tinymce.com/docs/advanced/editor-control-identifiers/#toolbarcontrols).
