### ISSUE TITLE
Options for only one type of page

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#1889]
Hi there,

I'm looking for some advice. I want to create page options for just one type of page. This page is using a different template file (page-contact.php). At first I was wondering if it was possible to create page options the same way as page templates as WordPress supports, so I created a file like this for Unyson: "../framework-customizations/theme/options/posts/page-contact.php"

This didn't work, so I have to find another way. Because of the unique template file property of this page I reckon it's best to use this to my advantage. I've created a normal page.php file in the above mentioned directory and inserted this code:

`if ( get_page_template_slug ( get_the_id() ) == 'page-contact.php') {
$options = array(...)
}`

This works, but I wonder if this is the best way to go, or does Unyson support a better way?

**Comment by moldcraft** [comment]
Hello,

We don't have/support this feature.

https://github.com/ThemeFuse/Unyson/issues/827

**Comment by warudin** [comment]
OK, pity.

Thanks for the answer, for now I will go with the solution in the OP. ;)
