### ISSUE TITLE
Option to remove query strings from CSS and JS

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#189]
Can we please have an option to remove query strings from styles and js files. 
This is very badly rated on site speed.
http://www.webpagescreenshot.info/i3/54c7856d42ad50-60275936

**Comment by moldcraft** [comment]
The query string is used to reset browser cache and load the latest script/style after the user updated an extension or the framework. For e.g. [we use framework version in all admin styles](https://github.com/ThemeFuse/Unyson/blob/fce9d3786d3e76c9daad51fde9d2645fefc61390/framework/core/components/backend.php#L219) and scripts.

----

You can use [this filter](https://github.com/WordPress/WordPress/blob/f7aef5b69a84ade5a54a256ab434e86fa9f136a3/wp-includes/class.wp-styles.php#L218) to remove the query string

```php
/**
 * Remove '?ver=...' from styles url
 * @param string $src    The source URL of the enqueued style.
 * @param string $handle The style's registered handle.
 * @return string
 * @internal
 */
function _filter_theme_remove_query_arg_from_styles($src, $handle) {
	return remove_query_arg('ver', $src);
}
add_filter('style_loader_src', '_filter_theme_remove_query_arg_from_styles', 10, 2);
```
