### ISSUE TITLE
Plugin activation

### ISSUE THREAD

**Issue by lidplussdesign** [ThemeFuse/Unyson#1890]
I can't activate new installed v2.5.12 version, v2.5.11 version works absolutely fine.

Warning: require_once(/my_path/wp-content/plugins/unyson/framework/includes/term-meta/function_fw_term_meta_setup_blog.php): failed to open stream: No such file or directory in /my_path/wp-content/plugins/unyson/unyson.php on line 42

**Comment by moldcraft** [comment]
The file is there https://github.com/ThemeFuse/Unyson/blob/v2.5.12/framework/includes/term-meta/function_fw_term_meta_setup_blog.php

Also on wp.org https://downloads.wordpress.org/plugin/unyson.2.5.12.zip it is there.

Try to reinstall the plugin.
