### ISSUE TITLE
Unyson extensions get deactivated

### ISSUE THREAD

**Issue by clusterthemes** [ThemeFuse/Unyson#1891]
Hi. Unyson extensions get periodically deactivated on their own. Like once in 2 weeks or 3 weeks.

I have the latest version of plugin and extensions, error_log is clean, no issues, I'm on Bluehost.

Can you let me know what the issue could be?

**Comment by duongancol** [comment]
Hi! I used to get the same problem. It's because hosting has the function to update plugins automatically. Maybe your problem is the same.

**Comment by clusterthemes** [comment]
Hi. Thanks for your input. How you managed to solve it?

**Comment by moldcraft** [comment]
@clusterthemes Please try to reproduce the problem using [these steps](http://wordpress.stackexchange.com/a/198358/60424)
