### ISSUE TITLE
color-palette option type

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#1893]
Hello, I purchased The Core theme a while back and it has a great option type called color-palette.

I'm looking for something similar to add to a theme, am I allowed to use this option type in my own themes?

Thanks

**Comment by Ataurr** [comment]
You can use this one #1654

**Comment by martinburdon** [comment]
@Ataurr Thanks I'll check it out 👍

**Comment by martinburdon** [comment]
Is it possible for me to use the one from The Core if required or are there plans for one to be added to Unyson? The one linked looks good but doesn't quite handle what I'm wanting to do

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1204#issuecomment-211282883

**Comment by onebelarusianguy** [comment]
@martinburdon just wondering: what the one linked can't handle what you want to do?

**Comment by martinburdon** [comment]
Hey @onebelarusianguy 😄 , what I want to be able to do is in my theme options, have for example 3 rgba pickers where the user can set brand color 1, color 2 and color 3 for the site. Then wherever they want to use a color, such as in a shortcode in the visual editor, be able to select one of these 3 colors for use. Then if the user went back to their theme settings and changed the colors it would update on the site without the user having to go back and re-select colors in the shortcodes.

I couldn't seem to do this when I played around with it, apologies if this is possible in the option types you shared with us and great work on it 👍

**Comment by onebelarusianguy** [comment]
@martinburdon You can do it, if I understood you correctly.
1. Create 3 color options in Theme Settings
2. In your shortcodes just get the color value from db like this:
`$color1 = fw_get_db_settings_option('color1_option');`

**Comment by moldcraft** [comment]
@onebelarusianguy When you use `fw_get_db_settings_option()` in options file provide, the second parameter, a default value `fw_get_db_settings_option('option_id', 'Default Value')`.

**Comment by onebelarusianguy** [comment]
@moldcraft usually I set default value through options array :)
