### ISSUE TITLE
implementing a box shortcode

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1894]
currently we have an icon box shortcode that allows us to have an icon and  title in the same block, although we can add those seperately as they have their own respective shortcodes.

that in mind, i would like to implement a block shortcode that would allow me to add and order other shortcodes within in it so it would essentially act as a container that could be inserted into a column.

i assume the block shortcode would need to work like the form builder shortcode, but how would allow all the other shortcodes to be added to it.

an easy workaround would be to have the wp-editor option type in the block shortcode as the wp-editor allow for other shortcodes to be inserted into it, however i would need an option within the wp-editor to only display the shortcodes button option and to disable all the other wp-editor options including the ability to add text.

**Comment by thednp** [comment]
I think you might be able to achieve what you want using the code from `call-to-action` shortcode, it's a combination of text/textarea options and a nested `button` shortcode, check it out.

**Comment by ahm-3d** [comment]
@thednp, the call-to-action shortcode is just another shortcode with a combination of 2 post options so i dont understand how i can achieve what i want with this. i have already created numerous shortcodes that involve a combination of different post options.

i need a shortcode (or perhaps a custom builder) that will allow me to drop in other shortcodes into it via the page builder.

essentially, i would like to turn every post option into an independent shortcode which i can just drag and drop into the custom block shortcode and possibly save it as a template. just like how we save columns and sections as templates.

A column should contain a series of block elements that could possibly contain different combinations of post options.

**Comment by thednp** [comment]
> the wp-editor inserts empty p tags between texts and shortcodes and therefore the front-end markup becomes messy.

I never encountered that. The `wp-editor` works just fine. If you enable the `wp-shortcodes` extension you can then run any other content shortcode inside, it's just the best way to put it.

Now I am trying to understand your need, I kinda feel the same in many ways, I would want to do everything my mind can think of, like nested columns, template builders (site header, footer, content, sidebars) etc, but still, the framework is huge as it is, it outperforms others in many many criteria.

I'm thinking why don't you see the obvious that most complicated ideas have simplest solutions, why not focus on what you can actually do and stop digging into time consuming effort.

**Comment by ahm-3d** [comment]
i appreciate that the framework is huge and i have no objections about how it outperforms other frameworks. i love unyson. there is no reason why we cant make a great framework greater. just because i want something to work in a certain way does not mean everyone else needs to agree, but the fact that you also relate to what i am trying to achieve could potentially mean that there is always room for improvement. maybe add my request as an enhancement.

i think having the block shortcode where i can insert other elements into it is important feature as it would save me from constantly creating independent shortcodes that can achieve the same result as a combination of individual post options as shortcodes.

please test the wp-editor with unyson shortcode enabled and add a mix of shortcodes and texts, then check the front end markup. i keep getting `<p> </p>` (empty paragraph) in between the paragraph texts and the inserted shortcodes.

**Comment by moldcraft** [comment]
> however i would need an option within the wp-editor to only display the shortcodes button option and to disable all the other wp-editor options

Try https://github.com/ThemeFuse/Unyson/issues/1888#issuecomment-239624314

> i keep getting `<p> </p>`

try to set the [`wpautop` parameter](https://github.com/ThemeFuse/Unyson/blob/030b3d331ffe4383c6e7a75007651502f32282f0/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L20) to `false` 

----

At the moment I don't have a solution for what you are trying to achieve.

A complicated and correct solution would be to create a sub extension of the `shortcodes` extension in your theme in 

```
{theme}/framework-customizations/extensions/shortcodes/extensions/{your-prefix}-single-shortcode/
```

similar to [WP Shortcodes extension](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension) which is installed in

```
unyson/framework/extensions/shortcodes/extensions/wp-shortcodes
```

that way it will be disabled in the `shortcodes` extension is disabled.

And to created there your option-type, a hybrid between `wp-editor` and WP-Shortcodes functionality.
