### ISSUE TITLE
Blank Page On Save

### ISSUE THREAD

**Issue by Rossco24** [ThemeFuse/Unyson#1896]
When I make or edit a page and click update the browser window goes blank. Any ideas? This obviously is making it impossible the save any pages.

I have checked the hosting and it seems to have the correct versions of PHP and MySQL.

Regards
Ross

**Comment by Rossco24** [comment]
It seems to be an issue with Revolution Slider. Page only goes blank on update when I have a Revolution Slider on the page. Any ideas of how to resolve this?

Regards
Ross

**Comment by boxingfit** [comment]
Same problem !!!

**Comment by moldcraft** [comment]
Make sure you have `WP_DEBUG` set to `true`, if it still doesn't show any error message, then ask your hosting to give you server error.log (or find it yourself). We can't help without a error message.

btw Which theme are you using?

**Comment by Rossco24** [comment]
Thanks moldcraft, here's the error

Fatal error: Call to undefined function putRevSlider() in /home/miladmin/public_html/wp-content/themes/everglades/framework-customizations/extensions/shortcodes/shortcodes/rev-slider/views/view.php on line 10

I'm using a theme called Everglades

Cheers
Ross

**Comment by moldcraft** [comment]
The error comes from theme, so report it to theme author.

**Comment by Rossco24** [comment]
Thanks Moldcraft
