### ISSUE TITLE
Hook for modifying options before they are saved

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1897]
I've looked to in the documentation on your site, but I can't find what I'm looking for.

I need an hook when the options are saved on the post/page / settings page / customizer but before they are **saved** to the database.
So basically what I need is when the user hits the *save* button, I need a way to get fresh options before they are saved to the database, so I can to one final manipulation of the data.

Why I need this.
I want to manipulate some options data when the data is saved, so I don't need to manipulate that data in the front end, I can just get the data from the options.

**Comment by moldcraft** [comment]
Usage

```php
add_action('fw_settings_options_update', '_theme_action_settings_options_update');
function _theme_action_settings_options_update($data) {
    $option_id = 'my_magic_option';
    
    if ($data['option_id'] !== $option_id) {
        return;
    }
    
    // prevent recursion
    remove_action('fw_settings_options_update', '_theme_action_settings_options_update');
    
    $value = fw_get_db_settings_option($option_id);
    
    $value = mega_extra_magic_function($value);
    
    fw_set_db_settings_option($option_id, $value);
    
    add_action('fw_settings_options_update', '_theme_action_settings_options_update');
}
```

**Comment by andreiglingeanu** [comment]
@moldcraft Shortcodes options are not covered here, right?

**Comment by moldcraft** [comment]
`framework/helpers/database.php` has settings, customizer, post and term options `get/set` functions.

Shortcodes don't have their database store location (post and term options have a separate post meta `fw_options`, settings and customizer have a separate wp_option) they are stored inside options where you place them.
