### ISSUE TITLE
[Feature] force unique values in repeatable option types

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1898]
I feel we need a way to enforce unique values for repeatable `addable-box` and `addable-popup`.

Here an example
```php
'stuff' => array(
  'label'		=> __( 'Stuff', 'fw' ),
  'type'		=> 'addable-popup',
  'size'		=> 'large',
  'value'		=> array(),
  'desc'  => '',
  'popup-options'  => array(
    'sub_stuff' => array(
      'label' => __( 'Sub stuff', 'fw' ),
      'type'  => 'select',
      'value' => 'a',
      'help'  => '',
      'desc'  => '',
      'choices' => array(
        'a' => __( 'A', 'fw' ),
        'b' => __( 'B', 'fw' ),
      )
    ),
  )
)
```
* for each instance of `'stuff'` we can only have a unique option value at a time of each of the `'sub_stuff'` option
* adding new instances of `'stuff'` will omit already selected values of `'sub_stuff'`

Is that achievable in any way?

**Comment by moldcraft** [comment]
Hello,

There is no simple way to achive this, only javascript hacks.

At the moment I don't know a solution. You can inspect `addable-popup` code and maybe figure out something.
