### ISSUE TITLE
Map shortcode issue

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#1899]
I know this bug is fixed but I don't know why Map shortcode doesn't work in my client site. On my site, it's working.
![Alt text](https://monosnap.com/file/tr3mb32DN3LBhoEwDqXVijBjHvDeNy.png)
How to fix it?

**Comment by thednp** [comment]
Perhaps because the domain change, and while the API keys are supposed to be secret, they get stripped from db, just guessing.

**Comment by duongancol** [comment]
@moldcraft any ideas?

**Comment by duongancol** [comment]
Could you take a look?

**Comment by moldcraft** [comment]
![](https://static.md/2dec87980e98abcbb5b00927b1d60fc5.png)

https://github.com/ThemeFuse/Unyson/blob/v2.5.12/framework/includes/option-types/map/class-fw-option-type-map.php#L38

Where you set your API key?

**Comment by duongancol** [comment]
I have no idea. Do you set default API key for Map option type? Because at my localhost, it works without setting the API key.

**Comment by player0k** [comment]
@duongancol , may be this api key bouded only for localhost domain

**Comment by duongancol** [comment]
@player0k do you know how to check it?

**Comment by player0k** [comment]
@duongancol , have no idea. Try to generate your own api key in the google settings
, read this solutions for the [backend](https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228821014) and for the [frontend](https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228732020)

**Comment by duongancol** [comment]
@player0k I guess that @moldcraft set the default API in the latest version. Waiting for  the confirm.

**Comment by danyj** [comment]
is not fixed , you still have to do this 
https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228732020

API is currently empty

**Comment by andreiglingeanu** [comment]
> is not fixed , you still have to do this 
> [#1675 (comment)](https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228732020)

Right, that's the way to fix it.

@duongancol Let us know if fixes your problems.

**Comment by moldcraft** [comment]
You can add in map shortcode or in Theme Settings [this option type](https://github.com/ThemeFuse/Unyson/blob/v2.5.12/framework/includes/option-types/simple.php#L1211) and it will be [used](https://github.com/ThemeFuse/Unyson/blob/v2.5.12/framework/includes/option-types/map/class-fw-option-type-map.php#L103)

**Comment by mbtocalli** [comment]
I'm still having issues with the backend map option in a custom post type (as a metabox, not as a shortcode). I applied the suggested code in my functions.php but I still get the following error in my backend: "Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error"
Do I have to put my API Key in plugins/unyson/framework/includes/option-types/map/class-fw-option-type-map.php?

**Comment by moldcraft** [comment]
@mbtocalli Please give the exact steps to reproduce the problem, with code snippets.

**Comment by mbtocalli** [comment]
First of all, I create a custom post type metabox by adding this script to mytheme/framework-customizations/theme/options/CPT-box.php

```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}
$options = array(
	'cpt_location'                    => array(
		'label'        => __( 'Location Map', 'unyson' ),
		'type'         => 'map',
		'value' => array(
			'coordinates' => array(
				'lat'   => -34,
				'lng'   => 150,
			),
		),
		'label' => __('Location', 'unyson'),
		'desc'  => __('Enter the current location', 'unyson'),
		'help'  => __('Location will be visible to other members.', 'unyson'),
	),
);
```

Then I add the code suggested by moldcraft ([#1675](https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228821014)) in mytheme/functions.php

```
/**
 * Dequeue default google maps option type script wich doesn't have API key
 * and enqueue one with an API key
 */
function _action_theme_replace_gmaps_script() {
    $handle = 'google-maps-api-v3';

    if (!wp_script_is($handle)) {
        return;
    }

    // https://github.com/ThemeFuse/Unyson/blob/v2.5.6/framework/includes/option-types/map/class-fw-option-type-map.php#L32-L38
    {
        wp_dequeue_script($handle);
        wp_deregister_script($handle);
    }

    wp_enqueue_script(
        $handle,
        'https://maps.googleapis.com/maps/api/js?'. http_build_query(array(
            'v' => '3.15',
            'libraries' => 'places',
            'language' => substr( get_locale(), 0, 2 ),
            'key' => 'YOUR_KEY'
        )),
        array(),
        fw()->manifest->get_version(),
        true
    );
}

function _action_theme_fw_init() {
    // https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/a780e1789e6ff454e3382ac71dd98c78b7844037
    if (version_compare(fw_ext('page-builder')->manifest->get_version(), '1.5.6', '>=')) {
        add_action('admin_enqueue_scripts', '_action_theme_replace_gmaps_script', 20);
    } else {
        add_action('admin_print_scripts', '_action_theme_replace_gmaps_script', 20);
    }
}

add_action('fw_init', `'_action_theme_fw_init');
```

Of course, I replace 'YOUR_KEY' with my actual API key obtained from Google

I finally use the option type 'gmap-key' on my Theme Settings, which I complete with my API.

```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$options = array(
	'general' => array(
		'title'   => __( 'General', 'webiliaria' ),
		'type'    => 'tab',
		'options' => array(
			'general-box' => array(
				'title'   => __( 'General Settings', 'webiliaria' ),
				'type'    => 'box',
				'options' => array(
					'gmap-key' => array(
						'label' => __( 'Google Maps API Key', 'unagui' ),
						'type'  => 'text',
						'value' => '',
						'desc'  => __( 'Enter your Google Maps API Key.', 'unagui' ),
					),
				)
			),
		)
	),	
);
```

I didn't changed plugins/unyson/framework/includes/option-types/map/class-fw-option-type-map.php

**Comment by moldcraft** [comment]
[This solution](https://github.com/ThemeFuse/Unyson/issues/1675#issuecomment-228821014) is outdated.

## How to fix Google Maps error

* **Backend**: Add in Theme Settings (or in any other place)

    ```
    'google-maps-api-key' => array(
        'type' => 'gmap-key',
    ),
    ```

    Once this options will be saved, it will be [used automatically in backend](https://github.com/ThemeFuse/Unyson/blob/v2.6.7/framework/includes/option-types/map/class-fw-option-type-map.php#L38).

* **Frontend**: Add in

    ```
    {theme}/framework-customizations/extensions/shortcodes/shortcodes/map/static.php
    ```

    the following code

    ```php
    wp_enqueue_script(
    	'google-maps-api-v3',
    	'https://maps.googleapis.com/maps/api/js?' . http_build_query(array(
    		'v' => '3.23',
    		'libraries' => 'places',
    		'language' => substr( get_locale(), 0, 2 ),
    		'key' => method_exists('FW_Option_Type_Map', 'api_key')
    			? FW_Option_Type_Map::api_key() 
    			: '' // You can set here some default key
    	)),
    	array(),
    	'3.23',
    	true
    );
    ```

**Comment by mbtocalli** [comment]
Great! My issue was fixed. Thanks @moldcraft

**Comment by danyj** [comment]
@moldcraft  , we need to check if this is  empty or not

    FW_Option_Type_Map::api_key()


 , otherwise fallback to ,

    // You can set here some default key

so


     method_exists('FW_Option_Type_Map', 'api_key') && !empty(FW_Option_Type_Map::api_key())


or 


	$key = method_exists('FW_Option_Type_Map', 'api_key') ? FW_Option_Type_Map::api_key() :'';
	wp_enqueue_script(
		'google-maps-api-v3',
		'https://maps.googleapis.com/maps/api/js?' . http_build_query(array(
			'v' => '3.23',
			'libraries' => 'places',
			'language' => substr( get_locale(), 0, 2 ),
			'key' => !empty($key)
				? $key
				: 'ADD_DEFAULT' // You can set here some default key
		)),
		array(),
		'3.23',
		true
	);

**Comment by danyj** [comment]
and I get x of undefined in events map 
http://prntscr.com/coq1io

the map and api is not set in backend , cant find it in html

**Comment by moldcraft** [comment]
@danyj  I updated the above code.

At the left of error message there is an arrow which shows the execution stack, click on it and check where exactly there error happens.

**Comment by UxLabByNinja** [comment]
@moldcraft Here is google map API in shortcode: http://prntscr.com/cpu8dc , Here is in shortcode options http://prntscr.com/cpu9fq and here is static.php full code: http://prntscr.com/cpuacs what wrong I am doing? Google map API js is not enqueuing in front end getting console error. Please help. 

@mbtocalli Can you please how do fix that issue. I can't figure out what is the problem. Thanks in advance.

**Comment by moldcraft** [comment]
@UxLabByNinja 

1. Check if `static.php` is executed
2. Remove `'jquery'` from the dependencies array

**Comment by UxLabByNinja** [comment]
@moldcraft Thanks, 
1. static.php is executing perfectly. 
2. Without 'jquery' dependency api js not enqueuing. With jquery api js enqueuing but I need to enqueue that js before my plugins.js. So, how can I do that? http://prntscr.com/cq6ozj

**Comment by moldcraft** [comment]
> Without 'jquery' dependency api js not enqueuing.

Can you find out why? (Strange, it should)

**Comment by moldcraft** [comment]
I see in your screenshot that the script is enqueued and api key is present in url, so the Unyson part related to this issue works fine. Now you have to play with dependencies and figure out why it is not enqueued. You can test scripts with [`wp_script_is()`](https://codex.wordpress.org/Function_Reference/wp_script_is)

**Comment by danyj** [comment]
@moldcraft 
http://prntscr.com/cqa5bl
http://prntscr.com/cqa5fu

**Comment by moldcraft** [comment]
@danyj It works on my side

![screenshot from 2016-11-04 10-19-18](https://cloud.githubusercontent.com/assets/1475489/19998944/400c7860-a278-11e6-9bae-fe2aafd3f94a.png)

**Comment by sandrodz** [comment]
why not add solution to documentation? I had to dig this up and go through multiple outdated solutions.

**Comment by moldcraft** [comment]
@sandrodz You can contribute to documentation via pull requests https://github.com/ThemeFuse/Unyson-Documentation

**Comment by hlaporthein** [comment]
Hello @moldcraft ,  The solution you mentioned above, it is working ok with theme setting page but, it won't work if I create **'type' => 'gmap-key',** in customizer. Just for my temporary, I did like below

```
if ( !function_exists( 'fw_get_db_customizer_option' ) ) :

	/**
	 * Copy google map api key from customizer to option value
	 */
	function _fw_update_google_map_api_key_to_option() {

		$google_map_api_key = fw_get_db_customizer_option( 'map_api_key' );
		$map_opt_val        = get_option( 'fw-option-types:gmap-key' );

		if ( ! empty( $google_map_api_key ) && ( $google_map_api_key !== $map_opt_val ) ) {
			update_option( 'fw-option-types:gmap-key', $google_map_api_key );
		}

	}

	add_action( 'customize_save_after', '_fw_update_google_map_api_key_to_option' );

endif;
```

That would be great if  **'type' => 'gmap-key',**  work for customizer.  I tried to find **fw-option-types:gmap-key** save place before pull requests. But, I have no idea where it is working from.
