### ISSUE TITLE
Error when publishing page while using page builder

### ISSUE THREAD

**Issue by braginteractive** [ThemeFuse/Unyson#190]
I am using the page builder extension and when I published the page I sometimes get this error. 

Catchable fatal error: Argument 1 passed to fw_get_options_values_from_input() must be of the type array, null given, called in /wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/extensions/editor-shortcodes/class-fw-extension-editor-shortcodes.php on line 111 and defined in /wp-content/plugins/unyson/framework/helpers/general.php on line 683

**Comment by sergiubagrin** [comment]
Hi @braginteractive,

> I am using the page builder extension and when I published the page I sometimes get this error.

Can you give us more details, PHP, Apache, MySQL, verisions OS (Win, Mac). Also add your page content or a zip file with your wordpress folder + SQl files

Thanks

**Comment by braginteractive** [comment]
Using the plugin locally with WordPress Version 4.1 | Unyson 2.1.18.

WP_BUG set to True

PHP 5.6.2

**Comment by moldcraft** [comment]
Fixed in https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/0469d390091ed453d6dadfd110f6d9fb142ce95b

We will let you know when a new version with this fix will be released.

**Comment by moldcraft** [comment]
Fixed in [PageBuilder v1.3.2](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/releases/tag/v1.3.2). If you update regularly Unyson extensions, you already have the the fix.
