### ISSUE TITLE
extension specific shortcodes

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1900]
i cant remember if i asked this question before but worded it differently...

how to enable extension specific shortcodes.

i have created a custom post type via an extension that i built following the unyson extension structure. how do i go about enabling a shortcode so it is accessible within the builder from the extension level. at the moment i can only enable or disable shortcodes via the hooks.php that sits inside the shortcodes directory

**Comment by moldcraft** [comment]
create the shortcode in `{extension}/shortcodes/{shortcode}` with `$config['page_builder'] = ...` http://manual.unyson.io/en/latest/extension/shortcodes/index.html#creating-a-new-shortcode
it should be loaded in page builder
