### ISSUE TITLE
wp-editor acquires focus on options modal open

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1901]
when you open Icon Box the focus is set set to wp-editor which is not first option http://joxi.net/8238nGWcOQOaAO
and the modal scroll is changed

**Comment by andreiglingeanu** [comment]
Probably due to the fact that tinymce is initialized at that point.

**Comment by andreiglingeanu** [comment]
@moldcraft That's because of [this](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/wp-editor/static/scripts.js#L107).
