### ISSUE TITLE
fw_collect_options() callback parameter

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1902]
Usually we do:

1. `fw_collect_options($collected, $options, $params)`
2. `foreach`
3. do something with `$option`

it can be done in one step

```php
fw_collect_options($collected, $options, array('callback' => 'do_something_with_option'));
```

**Comment by andreiglingeanu** [comment]
It's a thing that should be implemented?

**Comment by moldcraft** [comment]
Yes, I will implement it and use it in core. Just created the issue to not forget about it.
