### ISSUE TITLE
fontawesome library fonts outdated

### ISSUE THREAD

**Issue by oliver-graetz** [ThemeFuse/Unyson#1904]
The fontawesome libarry in Unyson 2.5.12 comes with the CSS for fontawesome 4.6.3 but the fonts inside the fonts directory are older versions. These need to be updated to the most recent fontawesome version or you cannot display all glyphs defined in the CSS.

**Comment by andreiglingeanu** [comment]
@oliver-graetz Thanks for repport.

**Comment by andreiglingeanu** [comment]
Done.
