### ISSUE TITLE
How to add custom options set per population method switch?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1907]
I need to switch options based on the slider population method change, 
this illustrates the issue 

![5ae604174ac9415db4876960d96ccc59](https://cloud.githubusercontent.com/assets/2340172/17802991/cb8b7556-65f3-11e6-992d-e0264ae4d6e1.png)

**Comment by danyj** [comment]
Or here would be preferred
![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/17803715/605a65e4-65f8-11e6-8667-25ea4e1d037d.jpg)

**Comment by danyj** [comment]
@moldcraft  OK , this https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/master/extensions/bx-slider/options/categories.php

does not work with default setup

you cant see these 2 options anywhere , 

looks like we should be able to add options set for population method , custom,posts,categories,tags 

but currently only custom.php works https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/master/extensions/bx-slider/options/custom.php

**Comment by danyj** [comment]
@moldcraft  @andreiglingeanu  please take a look 
http://take.ms/4xtIP

**Comment by danyj** [comment]
@moldcraft  I dug a bit and added 

    fw_print($options);

here

https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/2c962321bc66a62a39f114aae7aed76993148727/class-fw-extension-slider.php#L422


in slider admin I see the custom options coming from   file posts.php  that I placed here

https://github.com/ThemeFuse/Unyson-Sliders-Extension/tree/master/extensions/bx-slider/options

![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/17831107/8670e5bc-66e0-11e6-9ad8-d013f62b99e9.jpg)


but thy are not rendered anywhere, 

I see here that that function is merged with default options 

https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/2c962321bc66a62a39f114aae7aed76993148727/class-fw-extension-slider.php#L392


but  this function ,  get_slider_population_method_options  is not including the custom options,  it could be the filter name that is wrong but i am not sure.

**Comment by andreiglingeanu** [comment]
@danyj I haven't yet looked into the `Slider` extension. And I don't have any idea about what the **Population Methods** may mean. I know, some way of fetching posts from categories, but I don't know details, at least yet.

**Comment by andreiglingeanu** [comment]
> I need to switch options based on the slider population method change, 
this illustrates the issue

Looks like you need some more dynamic option type than the current `multi-picker`. There's no publicly available one that will make this possible.

**Comment by llemurya** [comment]
@danyj I tested and you a right, in the `categories.php` and other population methods files the merge didn't work, only in `custom.php` options are merged. I hope in this week I become with an pull request that will fix this bug.

**Comment by danyj** [comment]
@llemurya thnx bud , drove nuts!

**Comment by danyj** [comment]
Anything new on this?

**Comment by danyj** [comment]
@llemurya , @andreiglingeanu , @moldcraft  Anyone please take a look , it has been 3 weeks.

**Comment by llemurya** [comment]
@danyj please wait because until Friday, because I am busy with an project, I said to @moldcraft that last friday it will be fixed but I didn't fixed it.

**Comment by danyj** [comment]
@llemurya  this Friday maybe?

**Comment by danyj** [comment]
can we please get this fixed , I cant finish the sliders options without it.

**Comment by andreiglingeanu** [comment]
@danyj I'm not able to help with that. We gave up on using Sliders extension.

**Comment by danyj** [comment]
@andreiglingeanu , thnx for the reply , do you mean "we"  your team or Unyson ?

**Comment by andreiglingeanu** [comment]
> do you mean "we" your team or Unyson

Our team, not Unyson

**Comment by danyj** [comment]
Well by the looks of the 0 support on this particular extension  we will have to drop it also. 
Imagine customer  waiting this long for a fix.

**Comment by andreiglingeanu** [comment]
We didn't dropped it because of the lack of support (which is just temporary, everyone's busy on other things). We dropped it because of the fact that it introduces lots of complicated stuff for such a simple feature - sliders.
