### ISSUE TITLE
Vertical Mega Menu

### ISSUE THREAD

**Issue by Inved** [ThemeFuse/Unyson#1908]
Please how do i create a vertical mega menu in unyson?

**Comment by moldcraft** [comment]
Please give a screenshot.

**Comment by Inved** [comment]
Please see attached.

Thanks

**Comment by moldcraft** [comment]
Please comment on Github and attach the image in comment.

At the moment we don't see the attachments you sent via email.

**Comment by Inved** [comment]
![vertical mega menu](https://cloud.githubusercontent.com/assets/21122448/17811157/23cb377c-6619-11e6-99db-4289d7ceea22.png)


Please see screenshot above

**Comment by moldcraft** [comment]
I don't see anything complicated here. It is a regular menu. Second level are columns and the 4th column starts a new row. Then just customize the html with css. http://manual.unyson.io/en/latest/extension/megamenu/index.html#html-css

You tried to achieve the above design but without success, or you didn't tried and you are just asking?

**Comment by Inved** [comment]
Thanks for your response.

I tried, but couldn't. I did not know how to go about it



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=2daystelecom@gmail.com&idSignature=22>
