### ISSUE TITLE
Why the editor ShortCode is not Separate from Page builder?

### ISSUE THREAD

**Issue by MoBadawy** [ThemeFuse/Unyson#191]
When I saw the editor ShortCode in trello, I thought it will be a separate extension from page builder extension with own settings and ShortCodes for editor.
What is the benefit from it now ?

**Comment by sergiubagrin** [comment]
Hi MoBadawy,

Editor ShortCode use the same shortcodes like page buider. I decided to add it to page builder  because it is more easily to explain users from my point of view how to activate more options for pages with one extension. 

1. Why do you think it is needed to be a separate extension?
2. with own settings and ShortCodes for editor. Can you give me examples of specific settings for editor Shortcodes?

Thanks

**Comment by MoBadawy** [comment]
I need in "blog posts" editor ShortCodes not page builder .
And I need it with own "blog posts" ShortCodes, I don't need for example  "table" or "tabs" in "blog posts".

Why do you think it is needed to be a separate extension? Can you give me examples of specific settings?
- To control it like where it will be Activate?, and for developer what ShortCodes it will has?.

**Comment by moldcraft** [comment]
@MoBadawy Please follow [this repository](https://github.com/ThemeFuse/Unyson-Extensions-Approval) to test/review extensions before they are going to be released in order to prevent such confusions, as described in this issue

**Comment by sergiubagrin** [comment]
@MoBadawy - I will think about this

Thanks

**Comment by danyj** [comment]
Same thing here , I was hoping  to find ad least the shortcodes snippet like 
this 
http://screencast.com/t/HIXnQ3AOxVH
for  testimonial or accordion to add to widget area or blog post but no go.

**Comment by duongancol** [comment]
I agree with @MoBadawy.
Some users only need shortcode in page like a shortcode picker. They don't need to use page builder.

**Comment by thednp** [comment]
I would address this simple: make a post type selector for shortcodes and a separate one for page builder. Simple.

**Comment by sergiubagrin** [comment]
@thednp - We will think about this. We have a lot of tasks in to do to improve right now.

**Comment by moldcraft** [comment]
> Why the editor ShortCode is not Separate from Page builder?

We thought it was a good idea: To make it hidden and pre-installed with PageBuilder so the users will not need to install a second extension.

We can't change that, can't move it as a separate extension.
