### ISSUE TITLE
Text blocks turned blank

### ISSUE THREAD

**Issue by duyenie** [ThemeFuse/Unyson#1911]
Hi,

I’m using the Unyson plugin on my website.

This website is a multilingual one (french/english/spanish) and uses the WPML plugin to manage translations.

I don’t know what happened but all my text blocks editor turned blank (cf. screenshot) but the text still appears on the website.

This problem happened just after an update of the database. And once the database updated, I've changed the domain name and updated the WordPress version to 4.6.

If someone has a solution about that, it would be very helpful!

Thanks in advance!

![651514capture](https://cloud.githubusercontent.com/assets/21168086/17845863/4c87891c-6845-11e6-9438-6a4dd4597be3.png)

**Comment by andreiglingeanu** [comment]
Hi. Please open Chrome DevTools on the JavaScript tab and show us a screenshot of it. 

Which version of unyson you are using, nu the way?

**Comment by duyenie** [comment]
I'm using 2.5.10 version of Unyson.

Don't see any JS tab in the Chrome DevTools ?

Do you want that screenshot on the website or on the unyson plugin ? 

Thanks for your answer !

**Comment by andreiglingeanu** [comment]
When you see the blanked wp-editor, press F12. Then move to the **Console** tab. Share a screenshot of that.

**Comment by duyenie** [comment]
![capture2](https://cloud.githubusercontent.com/assets/21168086/17847688/a2f09f78-684f-11e6-98b5-8f5a3d07d350.PNG)
![capture1](https://cloud.githubusercontent.com/assets/21168086/17847690/a30f6ee4-684f-11e6-8e2c-9febbff61d84.PNG)

Thank you a lot !

**Comment by andreiglingeanu** [comment]
Nothing interesting there. Are you able to give me access to your site? If yes, send credentials toandrei.glingeanu@gmail.com please.

**Comment by duyenie** [comment]
Don't think I can... There's the website, if it helps : http://bit.ly/2bvFc00

**Comment by andreiglingeanu** [comment]
@duyenie In this case, can you reproduce this behavior with Scratch Theme? Maybe someone else noticed the bug?

**Comment by duyenie** [comment]
I've finally found the problem... Unyson has some compatibility problems with WooCommerce Multilingual. I've disabled it and the texts were back in their text blocks !

**Comment by andreiglingeanu** [comment]
Glad to hear this! Gonna close this now. Feel free to open another issue if you find something interesting. The problems with multilingual plugins are over-discussed (and no solution is found yet) and you should check those threads out.
