### ISSUE TITLE
custom post types not showing in page builder settings

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson#1912]
the page builder doesnt display any custom post types in the settings that are set to public => false. i need the custom post types to be displayed in the settings so i can enable the page builder for them.

the custom post types that i want to add are going to be sub content of an existing page, therefore those custom post types should not have an active url and that is why i need to set them to public => false

**Comment by player0k** [comment]
Page builder was developed for post_types which able to display on frontend

**Comment by ahm-3d** [comment]
the custom post types that i am creating will be displayed in the front end, but they will be a sub content of an existing page

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.6.1/helpers.php#L28
