### ISSUE TITLE
Can't delete elements

### ISSUE THREAD

**Issue by ricoaschi** [ThemeFuse/Unyson#1914]
If I delete an element on a content site on wordpress (Unyson Page Builder, Version 2.5.12), the element disappears. But if I click on "update" to save the modifications the deleted element appears anew. It seems that the content is write-protected but I can't explain me why and where I could change the required settings?

Thank you for your help.

**Comment by moldcraft** [comment]
* Please check your browser console if there are errors
* Make sure Unyson extensions are up-to-date (check the Dashboard > Updates page)

**Comment by ricoaschi** [comment]
@moldcraft thank you very much for your help! Problem resolved. I didn't see that the Unyson extensions must be updated by a particular check at the dashboard and not conventionally under "Plugins".

![remove](https://cloud.githubusercontent.com/assets/21170822/17854332/11888050-6872-11e6-835f-95db43bf669b.jpg)
