### ISSUE TITLE
Add Portfolio Category to permalink  - Issue #1885 re-opened

### ISSUE THREAD

**Issue by asier-laukoa** [ThemeFuse/Unyson#1917]
Hi again,

This question is related to Unyson because when you register a custom post type (portfolio) you can edit the "rewrite" argument to say the slug format, for example:

'rewrite' => array('slug' => 'portfolio/%fw-portfolio-category%'),

But I don't know if Unyson plugin has a hook available to overwrite the register_post_type function.

Thanks!

**Comment by asier-laukoa** [comment]
Hi,

I found a solution but I had to change the plugin, I changed the file called "class-fw-extension-portfolio.php" as follows:

`				'rewrite'            => array(
					'slug' => $this->slug.'/%'.$this->taxonomy_name.'%',
					'with_front' => true
				),
`

And I had to add 2 filter functions in my functions.php:

`
function portfolio_add_rewrte_rules( $rules ) {
  $new = array();
  $new['videojuego/([^/]+)/(.+)/?$'] = 'index.php?fw-portfolio=$matches[2]';
  $new['videojuego/(.+)/?$'] = 'index.php?fw-portfolio=$matches[1]';

  return array_merge( $new, $rules ); // Ensure our rules come first
}
add_filter( 'rewrite_rules_array', 'portfolio_add_rewrite_rules' );

function portfolio_filter_post_type_link( $link, $post ) {
  if ( $post->post_type == 'fw-portfolio' ) {
    if ( $cats = get_the_terms( $post->ID, 'fw-portfolio-category' ) ) {
      $link = str_replace( '%fw-portfolio-category%', current( $cats )->slug, $link );
    }
  }
  return $link;
}
add_filter( 'post_type_link', 'portfolio_filter_post_type_link', 10, 2 );
`

Is there any way of changing the "_action_register_post_type" function without changing the code of the plugin. Because when the plugin updates I will lose this changes.

Thanks!

**Comment by andreiglingeanu** [comment]
@asier-laukoa Please create a pull request with your changes on the [Portfolio Extension](https://github.com/ThemeFuse/Unyson-Portfolio-Extension). We'll review and give more feedback to you because we'll be able to see some real code.

**Comment by asier-laukoa** [comment]
The problem with this is that maybe not everyone wants this format of URL, so I think that the best way of doing this would be with an option in the Unyson plugin options. But you don't have a configuration page for Portfolio extension.

If I have time I will try to do it properly and then I will create a pull request. If you want to develop this for the next plugin update, you have my code changes above.

Thanks!
