### ISSUE TITLE
Migrating from addable-option to addable-popup

### ISSUE THREAD

**Issue by ansfazi** [ThemeFuse/Unyson#1918]
Hi,

We have used 'addable-option' for a list. Now we need to add link with the list title. How can i change it to addable-popup and populate the old data in addable-popup.

**Comment by moldcraft** [comment]
There is no simple solution. Only hacks (every time you need to check if the value has old structure, convert it to new and update in db)

**Comment by ansfazi** [comment]
is there any hook for this? so i can check if data is in old structure i can restructure?

**Comment by moldcraft** [comment]
No hook. You have to do it manually.
