### ISSUE TITLE
schema.org tags get stripped in Unyson WP editor

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1921]
I made a theme options page with several WP editors for variable texts through out a website I'm making. In one of those editors I want to put contact info, with schema.org tags included.

But, when I add these, they get stripped from the content.

There's a solution that works in the original WordPress editor (see: https://snipt.net/jamesw/prevent-tinymce-from-stripping-schemaorg-attributes-in-wordpress/), but not in the Unyson WP editor.

Is there a way to fix this?

**Comment by andreiglingeanu** [comment]
@noesteijver Are you getting this behavior when you enable shortcodes in `wp-editor`?

I mean when you add `'shortcodes' => true`.

**Comment by noesteijver** [comment]
@andreiglingeanu the solution I found throws an error for the Unyson WP editor. 

If I try it without that solution, and see if the addition of shortcodes => true makes a difference, than my answer is no. The addition of shortcodes => true doesn't make it work..

**Comment by andreiglingeanu** [comment]
> @andreiglingeanu the solution I found throws an error for the Unyson WP editor.

Show it.

**Comment by noesteijver** [comment]
@andreiglingeanu I used the following solution: https://snipt.net/jamesw/prevent-tinymce-from-stripping-schemaorg-attributes-in-wordpress/

It throws the following error: 
` Notice: Undefined index: extended_valid_elements in C:\Wamp\www\prettiglezen\wp-content\themes\prettiglezen\functions.php on line 270`

**Comment by andreiglingeanu** [comment]
@noesteijver Give me some DEMO content I can insert into my `wp-editor` in order to test.

**Comment by noesteijver** [comment]
@andreiglingeanu I first tried it with openingHours:

`<div itemscope itemtype="http://schema.org/Pharmacy">
  <h1 itemprop="name">Philippa's Pharmacy</h1>
  <p itemprop="description">A superb collection of fine pharmaceuticals for your beauty and healthcare
    convenience, a department of Delia's Drugstore.</p>
  <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th 09:00-12:00">Monday-Thursday 9am-noon</span></p>
  <p>Phone: <span itemprop="telephone" content="+18005551234">(800)555-1234</span></p>
</div>`

The spans with itemprop get erased from the WP editor (the spans themselves, not what they contain)

**Comment by andreiglingeanu** [comment]
@noesteijver As usual. Nothing wrong about `wp-editor`. You guys write your actions in a non-safe way. 

It may happen so that that some other plugin, but no `Unyson` included a **WordPress Editor** that has no `extended_valid_elements` key in its settings. Just be more strict when writing your checks. 

```php
function schema_TinyMCE_init($in) {
	$props = '@[id|class|style|title|itemscope|itemtype|itemprop|datetime|rel],div,dl,ul,dt,dd,li,span,a|rev|charset|href|lang|tabindex|accesskey|type|name|href|target|title|class|onfocus|onblur]';

	if (isset($in['extended_valid_elements'])) {
		if (! empty($in['extended_valid_elements'])) {
			$in['extended_valid_elements'] .= ',';
		}

		$in['extended_valid_elements'] .= $props;
	} else {
		$in['extended_valid_elements'] = $props;
	}

	return $in;
}

add_filter('tiny_mce_before_init', 'schema_TinyMCE_init' );
```

**Comment by noesteijver** [comment]
@andreiglingeanu aha, I should check the solutions better before copy/paste. Thanks for noticing that.

But, with the code you provided, do the spans stay in the WP editor? If I use your code, the spans still get deleted..

**Comment by andreiglingeanu** [comment]
https://wordpress.org/support/topic/prevent-span-tags-from-being-removed

That's the right place to ask for it.

**Comment by noesteijver** [comment]
I tested a little further. With the function/filter you improved, the standard WP editor from Blogposts or any other post type, the spans stay in the editor after updating.

But, the WP editor that Unyson provides as an option type still deletes the spans.

What is / could be the difference that causes this behaviour?

**Comment by andreiglingeanu** [comment]
I'll check it a bit later. Will come back with a response.

**Comment by andreiglingeanu** [comment]
1. Scratch theme with this [`settings.php`](https://gist.github.com/andreiglingeanu/acc32213d88a392184858537915aa230).
2. Paste [this](https://gist.github.com/andreiglingeanu/7ad37f3246779f7c4cb47a483096dd50) HTML in editor
3. In `index.php` of scratch: `<?php fw_print(fw_get_db_settings_option());`
4. In `inc/hooks.php`

```php
function schema_TinyMCE_init($in) {
    $props = '@[id|class|style|title|itemscope|itemtype|itemprop|datetime|rel],div,dl,ul,dt,dd,li,span,a|rev|charset|href|lang|tabindex|accesskey|type|name|href|target|title|class|onfocus|onblur]';

    if (isset($in['extended_valid_elements'])) {
        if (! empty($in['extended_valid_elements'])) {
            $in['extended_valid_elements'] .= ',';
        }

        $in['extended_valid_elements'] .= $props;
    } else {
        $in['extended_valid_elements'] = $props;
    }

    return $in;
}

add_filter('tiny_mce_before_init', 'schema_TinyMCE_init' );

```

Result:

```php

array
(
    [abc] => '<div itemscope itemtype="http://schema.org/Pharmacy"><h1 itemprop="name">Philippa's Pharmacy</h1><p itemprop="description">A superb collection of fine pharmaceuticals for your beauty and healthcare<br />    convenience, a department of Delia's Drugstore.</p><p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th 09:00-12:00">Monday-Thursday 9am-noon</span></p><p>Phone: <span itemprop="telephone" content="+18005551234">(800)555-1234</span></p></div>'
)
```

Nothing got stripped. Without the code in step 4, the attributes got stripped down. Please try to test this a bit more.
