### ISSUE TITLE
Sidebar Picker not working when Visual Builder is disable

### ISSUE THREAD

**Issue by zohaib87** [ThemeFuse/Unyson#1922]
Hi,

Sidebar picker is not working on those post type on which Visual Builder is disabled. It display select option type without any options. Here is a screen shot: http://prntscr.com/ca4dw5

Regards,

**Comment by mowshon** [comment]
Hi!

I try to reproduce this issue, but on my side `Sidebar Picker` works well, even if `Page Builder` is disable. I think you have old version of Unyson or Sidebar extension. Try to update.

**Comment by danyj** [comment]
@zohaib87  looking at the image seems like select options are there but their color is white , show html

**Comment by mowshon** [comment]
@danyj `Sidebar Picker` works with image-picker option type. The same bug was with old version of Unyson once. Unyson doesn't execute this part.

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/image-picker/class-fw-option-type-image-picker.php#L48-L72

Now I don't have this bug.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/253
