### ISSUE TITLE
Unyson not working properly

### ISSUE THREAD

**Issue by deffeniel** [ThemeFuse/Unyson#1923]
Hi there,

I must say that I'm impressed after seeing live demo.

But...

When I downloaded Unyson to try it by bulding my own websites, I felt something is wrong.

I can't import Demo content (i don't even have an option to do that), some Media Elements and Content Elements are missing, when i'm creating new page, i can't decide which theme to use (there is no such option at all!).  What's the matter?

Thanks for your help in advance.

**Comment by moldcraft** [comment]
Hello,

Please give more exact steps to reproduce the problem (maybe screenshots or video/screencast).

----

> when i'm creating new page, i can't decide which theme to use (there is no such option at all!)

Yes, WP doesn't have such possibility. Have you seen somewhere that possibility on a WP site?

**Comment by deffeniel** [comment]
Sorry, I meant template, but I wrote theme :) 

![screenshot2](https://cloud.githubusercontent.com/assets/21239789/17967560/480565a0-6ac8-11e6-980e-c77b6882a33c.png)
![screenshot3](https://cloud.githubusercontent.com/assets/21239789/17967562/49d3212e-6ac8-11e6-8f33-21cb00d421b1.png)
![screenshot4](https://cloud.githubusercontent.com/assets/21239789/17967563/4bb537d4-6ac8-11e6-8fb4-d11f66e5018d.png)
![screenshot2](https://cloud.githubusercontent.com/assets/21239789/17967577/5ff035f0-6ac8-11e6-8794-5329d6251dda.png)

**Comment by moldcraft** [comment]
Sorry, What is wrong is the above screenshots?

**Comment by deffeniel** [comment]
Wel,, I compared some things with Live Demo and although both version of Unyson are the same, some things arent.

On live demo
![livedemo1](https://cloud.githubusercontent.com/assets/21239789/17967682/0f9f9536-6ac9-11e6-96af-8e5606e6aa84.png)
![livedemo2](https://cloud.githubusercontent.com/assets/21239789/17967683/10ead504-6ac9-11e6-9850-94d0f711b7d5.png)

At my website
![mine1](https://cloud.githubusercontent.com/assets/21239789/17967716/443e7e2e-6ac9-11e6-9d9c-4e05fef5ba8b.png)
![mine2](https://cloud.githubusercontent.com/assets/21239789/17967717/45995d02-6ac9-11e6-96dc-8ace4af81061.png)

**Comment by deffeniel** [comment]
Well, I can send you access to this website, it would be the fastest way for you to see, if everything is all right. I would be grateful.

**Comment by danyj** [comment]
@deffeniel  what did you install?  only Unyson or Unyson and scratch theme? 
if only Unyson , than that is the issue since theme control's the templates and the rest of options/shortcodes etc.

**Comment by deffeniel** [comment]
Well, thanks, newbie move I made :) But now i have installed scratch theme also, but still i'm missing some options in Page Builder compared to what I saw in TestLabs demo.

**Comment by danyj** [comment]
bud , you must be specific , we dont know what theme you are testing ,  looks to me like Core , and you installed Scratch ,  every theme has own options sets thus you see different things live and on local.

**Comment by deffeniel** [comment]
So Core theme is not available?

**Comment by danyj** [comment]
http://themefuse.com/the-core-multi-purpose-wordpress-theme/

it is commercial theme ,   not free
