### ISSUE TITLE
How to create own container type ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1924]
@moldcraft  I see same pattern in container-type as option-type ,
https://github.com/ThemeFuse/Unyson/tree/master/framework/includes/container-types/tab

I copied  tab container and changed required strings from 

tab to thz-tab but it does not work. 

Any ideas ?

**Comment by moldcraft** [comment]
Have you included the file? https://github.com/ThemeFuse/Unyson/blob/v2.5.12/framework/includes/hooks.php#L31-L42

**Comment by danyj** [comment]
duh!!!!  sorry , thank you!, 
closing but one question if you can , 

I am trying to create a container that is not affected by lazy_tabs,
because of this , 
https://github.com/ThemeFuse/Unyson/issues/1491

 basically it should be always available and not wait for lazy_tab,  is there a class , something that this is hooked to ?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/backend-options.js#L121-L124

**Comment by danyj** [comment]
thnx , found it , commented out the lazy_tabs conditionals , https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/container-types/tab/view.php#L37-L45

**Comment by danyj** [comment]
now loking at it , there should be an option in tab container itself to disable the zly for specific tab , like @andreiglingeanu  did for icons v2

**Comment by moldcraft** [comment]
It will work only for first level tabs, because you can't know what is inside a tab until you init it.
