### ISSUE TITLE
Any way to use the page-builder on the frontend ?

### ISSUE THREAD

**Issue by tlartaud** [ThemeFuse/Unyson#1925]
Hi,

This is not an issue, but more likely a feature request as I don't think that what i'm asking right now is doable out of the box.

I have some forms on the frontend of my theme that include some rich-editors (using summernote editor, but the question should be the same with tinyMCE).
Are we actually able to use the page builder engine on the frontend to get the page builder's forms showing and the dialog modals as it does on the admin side, to allow my users to use the shortcodes ?

Would this be doable ? If yes, do you have any documentation ? If not, do you have any suggestion on how I could achieve that. My theme include a private area where users can post some private contents. It would be simply awesome to give them the same writing functionnalities as we have already on the backend with the page-builder.

Thank you for all your work, I really appreciate your stuffs.
Regards.

**Comment by thednp** [comment]
I believe this must be on the roadmap sometime later this year, IDK. I understand there are some optimizations to be implemented as well as improvements to the customizer support and overall extensions set's functionality.

From what I can tell, this feature would go well with customizer together, just some JS and minor CSS adaptations would be required for this feature to be implemented.

Ultimately perhaps the community will get involved and contribute with PRs on this FR. I am also interested to join the development, but also later, I am also busy with implementation.

**Comment by moldcraft** [comment]
Unyson admin functionality can't be used in frontend and we don't have any plans to implement that, sorry.

You can create your own super awesome frontend builder and submit it to us for a review.
