### ISSUE TITLE
How to disable mega menu for specific theme location?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1926]
Currently mega menu options and frontend mega menu output are enabled on all theme location, how can we activate it for specific location only?

**Comment by danyj** [comment]
@moldcraft  this is probably due to this change https://github.com/ThemeFuse/Unyson/issues/233, but now all menus get mega menu markup and mega cant be disabled

**Comment by danyj** [comment]
I was able to restrict the frontend markup to top menu only  with this in hook.php megamenu override 



```
// replace default walker
{
    remove_filter('wp_nav_menu_args', '_filter_fw_ext_mega_menu_wp_nav_menu_args');

    /** @internal */
    function _filter_theme_ext_mega_menu_wp_nav_menu_args($args) {
        
		if($args['theme_location'] !=='topmenu'){
			return $args;
		}
		
		$args['walker'] = new FW_Ext_Mega_Menu_Walker();

        return $args;
    }
    add_filter('wp_nav_menu_args', '_filter_theme_ext_mega_menu_wp_nav_menu_args');
}
```


but the menu edit still shows mega menu options on all menus.

**Comment by danyj** [comment]
I was wrong , still cant override the frontend, mega rows and columns class names are still printed. 
Please advise

**Comment by danyj** [comment]
OK I am stuck here , this is dumb example , I want a custom walker for my footer menu , something like 
https://gist.github.com/kosinix/5544535

even if I do this in  `wp_nav_menu`  args

    'walker'           => new Thz_Footer_Menu_Walker(),

it does not work and prints full FW mega menu 

    FW_Theme_Menu_Walker

hijacks any try to override menu or use custom walker

**Comment by moldcraft** [comment]
How to treat this case?

![1475684006459](https://cloud.githubusercontent.com/assets/1475489/19121624/d89a428e-8b2f-11e6-88f1-a276448049be.jpg)

**Comment by duongancol** [comment]
Is this option necessary?

**Comment by danyj** [comment]
@duongancol  the mega menu markup is everywhere , in sidebar menus , widget menus etc , that is why we need it. 

@moldcraft , hm that is tricky ,

**Comment by danyj** [comment]
ok seems like we cant get away from megamenu settings for specific menu , how about this in config.php

    $cfg['enable-only']   = array('topmenu');

ad least the markup would be restricted to one location and it is BC

**Comment by duongancol** [comment]
I still don't understand, the markup of mega menu only shows up when we active in Menu option. So why you want to add it in Menu location?

**Comment by danyj** [comment]
no bud , publish any WP menu in sidebar , left right anywhere , and it has mega menu markup , rows , column all the class names that should not be there

**Comment by moldcraft** [comment]
> publish any WP menu in sidebar , left right anywhere , and it has mega menu markup , rows , column all the class names that should not be there

So MegaMenu should enable its walker only if at least one menu item has "Use as MegaMenu" checked?

**Comment by danyj** [comment]
> So MegaMenu should enable its walker only
Kinda , but not sure what everything depends on it , icons ?

**Comment by moldcraft** [comment]
> So MegaMenu should enable its walker only if at least one menu item has "Use as MegaMenu" checked?

What if some theme uses menu item custom options but no "Use as MegaMenu" is checked? (item options can be set to [non MegaMenu items](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.1.1/options/default.php))

**Comment by danyj** [comment]
that is what i meant by 

>not sure what everything depends on it , icons

**Comment by GheorgheP** [comment]
Don't you think if the menu in header uses mega-menu and you want it in footer without mega-menu, those are already 2 different menus? This is menu, is something that is added once only, and may be once in few months you change something.

**Comment by GheorgheP** [comment]
Hey @danyj, this was a question from my side so I want to know your opinion, I mean, it may be really make sense.

**Comment by danyj** [comment]
problem is that if user  enables mega menu in footer or somewhere else other than header all the mega class names were included , here The Core, http://prntscr.com/eq8uwg

I solved this on my end
