### ISSUE TITLE
Unyson oembed option is making unnecessary http requests

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1929]
In admin, it appears that Unyson makes one **http** request for every **oembed** field/option even when the field is empty.

**Comment by andreiglingeanu** [comment]
@ivandotv Nice! Please refer to #1920 and post all of them there as you find more subtile details like that one.

**Comment by mowshon** [comment]
Add URL validation.
Waiting for this merge too.
https://github.com/ThemeFuse/Unyson/pull/1930

**Comment by mowshon** [comment]
@ivandotv can you check now?
