### ISSUE TITLE
Button Text

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#193]
Let's modify the Visual Page Editor button to Visual Page Builder: http://joxi.ru/brRnEqgU7JbNr1 
We've added some names in the template section and it's more accurate and easy to grasp when you say "Visual Builder Template" and we want the users to make the correlation between the button "Visual Page Builder" and the template name "Visual Builder Template".

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/e8dcee5fbf74fc540419b5725d28da84ff394358
