### ISSUE TITLE
Custom Styles not displaying in Format dropdown within Unyson wp-editor.

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#1932]
Using **tiny_mce_before_init** to add Custom Styles no longer seems to work. My custom styles dropdown show up when using the normal WP editor, but nothing shows within a Unyson wp-editor. Here is the code I am using:

<pre>
if( !function_exists('focus_wysiwyg_buttons') ) {
function focus_wysiwyg_buttons( $buttons ) {
  $buttons[] = 'styleselect';
  
  return $buttons;
}
}
add_filter( 'mce_buttons_2', 'focus_wysiwyg_buttons' );
</pre>
<pre>
if( !function_exists('focus_wysiwyg_styles') ) {
function focus_wysiwyg_styles( $settings ) {
	
	// Create array of new styles
	$new_styles = array(
		array(
			'title'	=> __( 'Custom Styles', 'focus' ),
			'items'	=> array(
				array(
					'title' => '.widget-title',
					'selector' => 'h1, h2, h3, h4, h5, h6',
					'classes'	=> 'widget-title'
				),
			),
		),
		array(
			'title'	=> __( 'Custom Margins', 'focus' ),
			'items'	=> array(
				array(
					'title' => '.no-margin',
					'selector' => 'h1, h2, h3, h4, h5, h6, p, ul, ol',
					'classes'	=> 'no-margin'
				),
				array(
					'title' => '.small-margin',
					'selector' => 'h1, h2, h3, h4, h5, h6, p, ul, ol',
					'classes'	=> 'small-margin'
				),
			),
		),
	);

	// Merge old & new styles
	$settings['style_formats_merge'] = true;

	// Add new styles
	$settings['style_formats'] = json_encode( $new_styles );

	// Return New Settings
	return $settings;
}
}
add_filter( 'tiny_mce_before_init', 'focus_wysiwyg_styles' );
</pre>

Thanks for the help!

**Comment by noesteijver** [comment]
I'm experiencing the same issue at the moment. Customization works well in the normal WP editor, but not in the Unyson version.

**Comment by andreiglingeanu** [comment]
@noesteijver We'll get it fixed, as well as your #1921. I had no time to deal with it.

**Comment by noesteijver** [comment]
@andreiglingeanu No problem. If there's anything I can do to assist, please let me know!

**Comment by andreiglingeanu** [comment]
```php
if( !function_exists('focus_wysiwyg_buttons') ) {
function focus_wysiwyg_buttons( $buttons ) {
  $buttons[] = 'styleselect';
  
  return $buttons;
}
}
add_filter( 'mce_buttons_2', 'focus_wysiwyg_buttons' );
```

[Without it.](https://cloud.githubusercontent.com/assets/2979628/18342509/def45c2e-75b7-11e6-8de5-f38ed7b3e4de.png) [With it.](https://cloud.githubusercontent.com/assets/2979628/18342536/f93ff4bc-75b7-11e6-87d5-4fcecd159e12.png)

<hr>

[And you second snippet totally works on my side.](https://cloud.githubusercontent.com/assets/2979628/18342882/995b6cc8-75b9-11e6-9396-fcc900368290.png).

Please try to reproduce your bug in scratch theme (if you can't - it's your codes problem) and come up with a response here. Till then - I see no problem in it.

**Comment by meta4creations** [comment]
Thanks for looking into this. I did create a new theme, still using the same code above, and it does work now in the new theme. I'm not sure what the difference may be between my themes, but I'm just going to leave it be unless I run into the issue again.

**Comment by yura-x** [comment]
Hello! Formats dropdown appears in "wp-editor", but it has default styles:
[http://prntscr.com/dixlua](http://prntscr.com/dixlua)
In default editor it looks like this
[http://prntscr.com/dixmcr](http://prntscr.com/dixmcr)

Here is my code:

`//adding custom styles to TinyMCE
// Callback function to insert 'styleselect' into the $buttons array
if ( ! function_exists( '_filter_mce_theme_format_insert_button' ) ) :
	function _filter_mce_theme_format_insert_button( $buttons ) {
		array_unshift( $buttons, 'styleselect' );

		return $buttons;
	} //_filter_mce_theme_format_insert_button()
endif;
// Register our callback to the appropriate filter
add_filter( 'mce_buttons_2', '_filter_mce_theme_format_insert_button' );
// Callback function to filter the MCE settings
if ( ! function_exists( '_filter_mce_theme_format_add_styles' ) ) :
	function _filter_mce_theme_format_add_styles( $init_array ) {
		// Define the style_formats array
		$style_formats = array(
			// Each array child is a format with it's own settings
			array(
				'title'   => esc_html__( 'Excerpt', '' ),
				'block'   => 'p',
				'classes' => 'entry-excerpt',
				'wrapper' => false,
			),
			array(
				'title'   => esc_html__( 'Paragraph with dropcap', '' ),
				'block'   => 'p',
				'classes' => 'big-first-letter',
				'wrapper' => false,
			),
			array(
				'title'   => esc_html__( 'Main theme color', '' ),
				'inline'  => 'span',
				'classes' => 'highlight',
				'wrapper' => false,
			),

		);
		// Insert the array, JSON ENCODED, into 'style_formats'
		$init_array['style_formats'] = json_encode( $style_formats );

		return $init_array;

	} //_filter_mce_theme_format_add_styles()
endif;
// Attach callback to 'tiny_mce_before_init'
add_filter( 'tiny_mce_before_init', '_filter_mce_theme_format_add_styles' );`

Thank you!

**Comment by moldcraft** [comment]
@yura-x I added your code in `{theme}/functions.php` and it works fine

![screenshot from 2016-12-19 13-49-57](https://cloud.githubusercontent.com/assets/1475489/21311867/151e8d6c-c5f2-11e6-83ba-265afa15d5d6.png)
