### ISSUE TITLE
Bugs in getting google webfonts

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#1934]
I have used the this method to enqueue google web fonts .
https://github.com/ThemeFuse/Unyson/issues/836

But it works only for first time. If I change the font family it does not load that font . Moreover I inspect the database and found that ```fw_theme_google_fonts_link``` the link values are saved . I have deleted that  option value and upon saving from admin the value is not updated. It remains blank . But ```update_option``` create specific option evenif it was deleted. Isn't unyson do the same ?

**Comment by moldcraft** [comment]
Hello,

Please give the exact steps to reproduce the problem on our side with code snippets.

**Comment by webangon** [comment]
I just sent you wp admin access.

**Comment by webangon** [comment]
Here is the screenshot. Also if I change font , it acts weird. 
![capture](https://cloud.githubusercontent.com/assets/7946657/18050406/432e9c90-6e10-11e6-9d45-0ed773189915.PNG)
![untitled](https://cloud.githubusercontent.com/assets/7946657/18050420/4d45e134-6e10-11e6-978c-367217393916.png)

**Comment by moldcraft** [comment]
In your code there was

```php
add_action('fw_settings_form_saved',array(&$this, 'google_fonts', 999, 2));
```

I fixed it

```php
add_action('fw_settings_form_saved',array($this, 'google_fonts'), 999);
```

----

Now it throws server 500 error from this function `fw_theme_get_remote_fonts()`. Now it is up to you to fix it, because it is not a Unyson problem.
