### ISSUE TITLE
How to display Image Picker in a file view.php ?

### ISSUE THREAD

**Issue by Dark-Scorpion** [ThemeFuse/Unyson#1935]
'image' => array(
    'type'  => 'image-picker',
    'value' => 'image-2',
    'attr'  => array(
        'class'    => 'custom-class',
        'data-foo' => 'bar',
    ),
    'label' => __('Label', '{domain}'),
    'desc'  => __('Description', '{domain}'),
    'help'  => __('Help tip', '{domain}'),
    'choices' => array(
        'value-1' => get_template_directory_uri() .'/images/thumbnail.png',
        'value-2' => array(
            // (required) url for thumbnail
            'small' => get_template_directory_uri() .'/images/thumbnail.png',
            // (optional) url for large image that will appear in tooltip
            'large' => get_template_directory_uri() .'/images/preview.png',
            // (optional) choice extra data for js, available in custom events
            'data' => array(...)
        ),
        'value-3' => array(
            // (required) url for thumbnail
            'small' => array(
                'src' => get_template_directory_uri() .'/images/thumbnail.png',
                'height' => 70
            ),
            // (optional) url for large image that will appear in tooltip
            'large' => array(
                'src' => get_template_directory_uri() .'/images/preview.png',
                'height' => 400
            ),
            // (optional) choice extra data for js, available in custom events
            'data' => array(...)
        ),
    ),
    'blank' => true, // (optional) if true, images can be deselected
)

**Comment by andreiglingeanu** [comment]
```php
fw()->backend->option_type('image-picker')->render($id, $option, $data);
```

Inspect [this](https://github.com/ThemeFuse/Unyson/blob/v2.6.0/framework/includes/option-types/image-picker/class-fw-option-type-image-picker.php#L77) for more info.

**Comment by Dark-Scorpion** [comment]
Thank you!

**Comment by antonweb15** [comment]
please could you write an example (real syntax)?

**Comment by danyj** [comment]
```
	echo fw()->backend->option_type('image-picker')->render(
		$id,
		array( 
			'value' => $option['value'],
			'choices' => array(),//http://manual.unyson.io/en/latest/options/built-in/image-picker.html
		),
		array(
		   'value'		 => $data['value'],
		   'id_prefix'   => $data['id_prefix'],
		   'name_prefix' => $data['name_prefix']
		)
	);
```

**Comment by antonweb15** [comment]
OK
I will try it
Thank you!

**Comment by antonweb15** [comment]
does not work

**Comment by antonweb15** [comment]
I add option Image Picker

**Comment by antonweb15** [comment]
array(
    'type'  => 'image-picker',
    'value' => 'image-2',
    'attr'  => array(
        'class'    => 'custom-class',
        'data-foo' => 'bar',
    ),
    'label' => __('Label', '{domain}'),
    'desc'  => __('Description', '{domain}'),
    'help'  => __('Help tip', '{domain}'),
    'choices' => array(
        'value-1' => get_template_directory_uri() .'/images/thumbnail.png',
        'value-2' => array(
            // (required) url for thumbnail
            'small' => get_template_directory_uri() .'/images/thumbnail.png',
            // (optional) url for large image that will appear in tooltip
            'large' => get_template_directory_uri() .'/images/preview.png',
            // (optional) choice extra data for js, available in custom events
            'data' => array(...)
        ),
        'value-3' => array(
            // (required) url for thumbnail
            'small' => array(
                'src' => get_template_directory_uri() .'/images/thumbnail.png',
                'height' => 70
            ),
            // (optional) url for large image that will appear in tooltip
            'large' => array(
                'src' => get_template_directory_uri() .'/images/preview.png',
                'height' => 400
            ),
            // (optional) choice extra data for js, available in custom events
            'data' => array(...)
        ),
    ),
    'blank' => true, // (optional) if true, images can be deselected
)

**Comment by antonweb15** [comment]
it works correctly

**Comment by antonweb15** [comment]
How to display Image Picker in a HTML ?

**Comment by antonweb15** [comment]
I need to output a URL
