### ISSUE TITLE
Failed to access GitHub repository (Response code: 403)

### ISSUE THREAD

**Issue by rodolfocangiotti** [ThemeFuse/Unyson#1938]
Hi all,
I have just installed the Unyson framework on my Wordpress blog.
When I try to install an extension, your plug-in returns:
`Failed to access GitHub repository (path) releases (Response code: 403)`

Here is a sample screenshot:
![schermata 2016-08-29 alle 20 45 25]
(https://cloud.githubusercontent.com/assets/21317516/18063023/92b1f8d4-6e29-11e6-9f63-20a206255d9e.png)

Is it possible to solve this issue?
Waiting for your reply, I thank you in advance.
Regards.

**Comment by moldcraft** [comment]
Hello,

Most probably your hosting is blocking requests to `http://github-api-cache.unyson.io/`, to check if it is so, add the blow code in your `{theme}/functions.php`:

```php
add_action('admin_notices', function(){
    fw_print(wp_remote_get('http://github-api-cache.unyson.io/'));
});
```

**Comment by Fabiok89** [comment]
I also have the same problem even after entering the string of code you posted.
I am building my site on altervista and then buying the domain just finished
How can I solve this inconvenience?
