### ISSUE TITLE
One Click Install of Sample Data Creates Database Errors

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#1939]
Hello,

The One-click Sample Data install produces the database error “One or more database tables are unavailable. The database may need to be repaired”.

I can’t provide FTP details. I’m building the site on my local computer (via  XAMPP 7.0.8).  It will be moved to a live server when it’s completed.
Here are the localhost server details: Apache 2.4.18, MariaDB 10.1.13 (MYSQL 5.6), PHP 7.0.8, phpMyAdmin 4.5.1.

**Comment by moldcraft** [comment]
Try to delete all your database tables and install WP. Then run again demo install. Maybe your tables are indeed corrupt.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/2019#issuecomment-256016071
