### ISSUE TITLE
fw_ext_shortcodes_enqueue_static doesn`t work

### ISSUE THREAD

**Issue by BarsTheme** [ThemeFuse/Unyson#1941]
my shortcode name is navmenu
here is my static.php file

```php
<?php if (!defined('FW')) die('Forbidden');

$shortcodes_extension = fw_ext('shortcodes');

wp_enqueue_style(
	'theme-shortcode-navmenu',
	$shortcodes_extension->locate_URI('/shortcodes/navmenu/static/css/styles.css')
);

if (!function_exists('_action_theme_shortcode_navmenu_enqueue_dynamic_css')):

function _action_theme_shortcode_navmenu_enqueue_dynamic_css($data) {

    $shortcode = 'navmenu';
    $atts = shortcode_parse_atts( $data['atts_string'] );

    wp_add_inline_style(
        'theme-shortcode-'. $shortcode,
        '#navmenu_'. $atts['id'] .' { '.
            'background-color:#ff0000;'.
        ' } '
    );
}

add_action(
    'fw_ext_shortcodes_enqueue_static:navmenu',
    '_action_theme_shortcode_navmenu_enqueue_dynamic_css'
);

endif;
```

wp_enqueue_style works fine but add_action doesn`t work
i do not understand what i am missed. This code is from your documentation.

i have a last version Unyson Framework and WP 4.6

**Comment by moldcraft** [comment]
Hello,

Add [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/55084e1f005dc9697d1055b5a0f13504c9e1da85/class-fw-extension-shortcodes.php#L225) `fw_print($tag);` to check if the action is triggered (if your shortcode is parsed)

**Comment by BarsTheme** [comment]
i`ve added fw_print($tag); but nothing is happening :)

**Comment by BarsTheme** [comment]
well... i am actually use page builder in my custom post type and it doesn`t work but if i use it in common WP Post it works fine

**Comment by BarsTheme** [comment]
well... if i print my custom post by direct link it works properly, but if i print my custom post by WP_Query then inline styles doesn`t work

**Comment by moldcraft** [comment]
Please give me admin/ftp access to your site (`moldcraft[at]email.com`) or give the exact steps how to reproduce the problem (with code snippets).

**Comment by BarsTheme** [comment]
i am on local hosting unfortunately but i will try to explain

Step 1: in my header.php i call

    $theme = BT_Theme::getInstance();
    $theme::get_theme_block( 'site_header_template' );

Step 2: in my BT_Theme class i have

    public static function get_theme_block( $block_name ){
		$site_block_template_id = self::$block_name( '' ); // gets custom post id
		if ( '' == $site_block_template_id ){
			return;
		}

		$the_query = new WP_Query( array(
			'post_type'	=> 'fw-siteblocks', // 'siteblock' custom post type
			'p'		=> $site_block_template_id, // id of 'siteblock' post
		) );

		if ( $the_query->have_posts() ) {
			while ( $the_query->have_posts() ) {
				$the_query->the_post();
				the_content(); // displays 'siteblock' post content
			}
			wp_reset_postdata();
		}
	}
it displays my 'siteblock' custom post with given id which contains my shortcode named 'navmenu' inserted by Builder.

my static.php of 'navmenu' is

    <?php if (!defined('FW')) die('Forbidden');

    $shortcodes_extension = fw_ext('shortcodes');
    wp_enqueue_style(
        'theme-shortcode-navmenu',
        $shortcodes_extension->locate_URI('/shortcodes/navmenu/static/css/styles.css')
    );

    if (!function_exists('_action_theme_shortcode_navmenu_enqueue_dynamic_css')):

    function _action_theme_shortcode_navmenu_enqueue_dynamic_css($data) {
        $shortcode = 'navmenu';
        $atts = shortcode_parse_atts( $data['atts_string'] );

        wp_add_inline_style(
            'theme-shortcode-'. $shortcode,
            '#navmenu_'. $atts['id'] .' { '.
             'background-color:#ff0000;'.
            ' } '
        );
    }

    add_action(
        'fw_ext_shortcodes_enqueue_static:navmenu',
        '_action_theme_shortcode_navmenu_enqueue_dynamic_css'
    );

    endif;

in this file wp_enqueue_style works and puts my styles.css in site page but add_action does not work( see below ).

other options from options.php of 'navmenu' work fine.

if i display my 'siteblock' custom post by direct link or pressing 'Preview changes' button in post editor it works with inline styles( add_action works fine ).
if i display my 'siteblock' custom post from WP_Query ( as shown above ) it does not put inline styles on site page( add_action doesn`t work ).

**Comment by moldcraft** [comment]
1. `fw_ext_shortcodes_enqueue_static:{shortcode}` Is executed on [this action](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/414de6c22339b0a37edda83cea45a6abb5e95b75/class-fw-extension-shortcodes.php#L59-L60)
2. It uses `global $post;` content to extract the shortcodes ([code](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/414de6c22339b0a37edda83cea45a6abb5e95b75/class-fw-extension-shortcodes.php#L210-L216))

In your case it has no idea that you do a custom query in your template and display another post.

The solution is to execute [this function](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/414de6c22339b0a37edda83cea45a6abb5e95b75/helpers.php#L30) with your post content on `wp_enqueue_scripts` action.

Something like this:

```php
function _action_theme_enqueue_custom_post_shortcode_assets() {
    if (!function_exists('fw_ext_shortcodes_enqueue_shortcodes_static')) {
        return;
    }
    
    if (!SOMETHING) {
        // execute this code only when needed
        return;
    }

    $the_query = new WP_Query( array(
        'post_type' => 'fw-siteblocks', // 'siteblock' custom post type
        'p'     => $site_block_template_id, // id of 'siteblock' post
    ) );

    if ( $the_query->have_posts() ) {
        while ( $the_query->have_posts() ) {
            $the_query->the_post();
            global $post;
            fw_ext_shortcodes_enqueue_shortcodes_static($post->post_content);
        }
        wp_reset_postdata();
    }
}
add_action(
    'wp_enqueue_scripts',
    '_action_theme_enqueue_custom_post_shortcode_assets'
);
```
