### ISSUE TITLE
lack of functionality on my instalation

### ISSUE THREAD

**Issue by Panibrat** [ThemeFuse/Unyson#1943]
I installed Unyson package on my clean WordPress 4.6 and found out lack of setting in Page Builder's elements.
For example: button element has only 3 fields of settings.
I got trial site from on http://testlabs.themefuse.com/. Here button element has 18 settings.

What wrong with functionality from the box?
How get full functionality?

Thank you!

**Comment by moldcraft** [comment]
Unyson is free plugin/framework, TheCore is a commercial theme.
