### ISSUE TITLE
function (n){return o.call(this,n,m)}

### ISSUE THREAD

**Issue by koorazy** [ThemeFuse/Unyson#1944]
Hi

I am having the issue with the builder not displaying section names instead everything is function (n){return o.call(this,n,m)}. I have read all the other post about this issue, i  have the latest version on wordpress, i have reinstalled unyson, i have deactivated all plugins, i have refreshed the browser and logged in on other browser that i have never used but still the issue persists. 

Any help? I need to show my client how to update the pages themselves as soon as possible and it would be very difficult for them the way it is displaying.

Thanks

**Comment by moldcraft** [comment]
1. Do you have any cache plugin active?
2. Can you give admin/ftp access to your site? `moldcraft[at]email.com`

**Comment by koorazy** [comment]
thanks, i have emailed you, let me know if there is anything else you need.

**Comment by koorazy** [comment]
Oh i actually figured it out..
I had update the new unyson plugin, but need to update the builder... so it is working now.

**Comment by kenloke** [comment]
hi pls help i have this issue in my wordpress. help pls!

**Comment by moldcraft** [comment]
Please reinstall Unyson plugin and clear browser cache.

**Comment by kenloke** [comment]
hi thanks. yes done that but not working.
my wordpress version is the latest 4.6.1 also the Unyson.

help!
thanks

**Comment by moldcraft** [comment]
Try to activate a default WP theme, maybe the problem comes from your theme. If you have a cache plugin, please disable it.
