### ISSUE TITLE
Column width in its shortcode options

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#1945]
Hi,
Is it possible to get width of current column in shortcode "column" options? Just want to to do some stuff depending on it ...

**Comment by moldcraft** [comment]
In `options.php` ?

**Comment by onebelarusianguy** [comment]
@moldcraft  in its `options.php`, exactly

**Comment by moldcraft** [comment]
It is not possible. `options.php` is loaded once for all columns.

**Comment by onebelarusianguy** [comment]
@moldcraft thanks, then js-crutches :D
