### ISSUE TITLE
front end multi upload

### ISSUE THREAD

**Issue by vladimir-boyko** [ThemeFuse/Unyson#1946]
Hello, please tell me how to get to the front end multiapload.

upload show `<img src="<?php echo $atts['image']['url']; ?>"`

show multi upload?

**Comment by moldcraft** [comment]
Hi, Use `fw_print($atts);` to see the structure of the array.

**Comment by vladimir-boyko** [comment]
moldcraft
```
array(
    'type'  => 'multi-upload',
    'value' => array(
     ),
    'label' => __('Label', '{domain}'),
    'desc'  => __('Description', '{domain}'),
    'help'  => __('Help tip', '{domain}'),
    'images_only' => true,
)
```
Here is an array, but his lead me View.php file front end?

**Comment by vladimir-boyko** [comment]
I programming is weak, I use ready-made solutions

**Comment by moldcraft** [comment]
Please learn PHP before doing WordPress themes.

**Comment by vladimir-boyko** [comment]
moldcraft,
And where is php if in the official documentation of the framework is not written as the output multi upload option

**Comment by vladimir-boyko** [comment]
moldcraft <https://github.com/moldcraft>?

2016-08-31 18:48 GMT+03:00 moldcraft <notifications@github.com>:

**Comment by vladimir-boyko** [comment]
Very nice  support in the framework(((((((((((((((((((((((((((((((((((((((((((

**Comment by sergiu-radu** [comment]
@vladimir-boyko if you don't know PHP or your programing skills are week this doesn't mean that the support of the framework is bad! 
The guys that maintain this framework are solving day by day more important problems than yours.

**Comment by bafamet** [comment]
foreach($atts['image'] as $key => $value) {
    echo $value['image'], '<img src="', $value['url'], '" alt="before after"><br />';
    
   }
