### ISSUE TITLE
Plugin list not displaying after deactivating unyson plugin

### ISSUE THREAD

**Issue by dimple921** [ThemeFuse/Unyson#1947]
I am using this plugin on my client's website and when I deactivate this plugin, the admin panel don not show the plugins list. It just display the blank screen. I have also checked using debug mode it is showing an error of maximum execution time expired, But after increasing maximum execution time it still showing blank screen. Please help.

**Comment by danyj** [comment]
If plugin is deactivated it is not  used anymore, it could be your theme requiring something from Unyson  without checking properly and ending up in recursion. Disable the theme and check.

**Comment by dimple921** [comment]
Sorry I have missed some points.
When I deactivate the plugin from dashboard it shows message plugin deactivated but plugin still shows there activated. 
And when renamed it through ftp it shows blank page in dashboard's plugin page.
I have tried after disabling the theme. but still not working

**Comment by moldcraft** [comment]
If you delete the plugin folder via ftp the problem is till there? Then it's a hosting problem.
Also try to disable all plugins, maybe th
