### ISSUE TITLE
Unyson and Google’s Places Autocomplete

### ISSUE THREAD

**Issue by RoyDev01** [ThemeFuse/Unyson#1948]
I would like to add  Google’s Maps Autocomplete feature to a search box of Drop-Off and Pick-Up locations for car rental, instead of entering each city manually. How can I do that? Is there any short way? Is it already embedded in the template ?
I know Google publishes their API of Places Autocomplete so it’s just a Javascript code to insert.

Thanks,

Roy.

**Comment by moldcraft** [comment]
Hello,

Can you give a screenshot of what you want to achieve?

**Comment by RoyDev01** [comment]
![area](https://cloud.githubusercontent.com/assets/21357406/18145405/c6137d50-6fd3-11e6-8a7f-5659e6550368.png)

So this is my Drop-off/Pick-up rental location and I want it to autocomplete places names.
So, basically I want to insert google's places API which is available here. btw its Javascript.
https://developers.google.com/places/web-service/autocomplete#example_autocomplete_requests
This is an example https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

**Comment by moldcraft** [comment]
This is frontend, it has nothing to do with Unyson option-types. We don't provide support for custom work.
