### ISSUE TITLE
Latest master fw_option_types_init issue

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1949]
Getting message about ,  Please register option-types on 'fw_option_types_init' action, 

checked and all my options are on it 

    add_action('fw_option_types_init', '_action_theme_include_custom_option_types');

**Comment by danyj** [comment]
@andreiglingeanu do u mind checking this , I am sure all my options are on the right filter , maybe you forgot something while commiting, https://github.com/ThemeFuse/Unyson/issues/1949

**Comment by andreiglingeanu** [comment]
@danyj Update every Unyson extension.

**Comment by danyj** [comment]
o boy!

**Comment by danyj** [comment]
@andreiglingeanu   do you or anyone around has the complete bundle with extensions , this is just pane to go one by one, seems like plenty of changes

**Comment by moldcraft** [comment]
Delete all extensions and use [this script](https://github.com/ThemeFuse/Unyson/blob/master/framework/extensions/clone-all.bash) to clone then all, or [this script](https://gist.github.com/moldcraft/54778d4b0cfb4bc8d5b7) to execute `git pull` in all extensions

**Comment by danyj** [comment]
I made an option type based on it more than year ago ,   


`class FW_Option_Type_ThzSectionBuilder extends FW_Option_Type_Builder {`

**Comment by danyj** [comment]
@moldcraft    thnx!!  ,   


@andreiglingeanu    eveyrthing updated , still same msg error  

    Please register option-types on 'fw_option_types_init' action

**Comment by moldcraft** [comment]
Try with a default WP theme

**Comment by andreiglingeanu** [comment]
@danyj Probably because you're registering `FW_Option_Type_ThzSectionBuilder` too early. Do you have other option types you can try to remove in order to test?

**Comment by danyj** [comment]
no no ,  that one has nothing to do with this, is just option type that needed a class and @moldcraft fixed it , 

the issue was this 
https://github.com/ThemeFuse/Unyson/issues/654#issuecomment-110740927

before we had to use fw_init on any option that was doing some ajax , now we cant and must use 

    fw_option_types_init

for those also , 

Il test and advise if  now with the new requirement ajax returns 0  which was the case before ,

**Comment by moldcraft** [comment]
> before we had to use fw_init on any option that was doing some ajax

No need anymore https://github.com/ThemeFuse/Unyson/blob/76e399f9f823b8ac18f7fa8d4e3c9a14f43e693d/framework/includes/hooks.php#L18-L28

**Comment by danyj** [comment]
looks ok ! thank you , and happy holiday!

**Comment by nandlal-tjm** [comment]
I updated hooks.php but still get same notice
`Please register option-types on 'fw_option_types_init' action`

**Comment by moldcraft** [comment]
@nandlal-tjm Make sure Unyson extensions are up-to-date

**Comment by nandlal-tjm** [comment]
yes, I deleted and activated compatible extension with my theme. but got same error.

`Please register option-types on 'fw_option_types_init' action`

further more I got error on activate breadcrumb extension

`Cannot move "E:/xampp/htdocs/my-theme/wp-content/plugins/unyson/tmp/Unyson-Breadcrumbs-Extension-1.0.12/static" to "E:/xampp/htdocs/my-theme/wp-content/plugins/unyson/framework/extensions/breadcrumbs/static".`

**Comment by eyeswizard** [comment]
@nandlal-tjm  i'm also facing the same problem see: https://github.com/ThemeFuse/Unyson/issues/1993

**Comment by stevedapper** [comment]
Guys, can you help me! I have the same problem but can't seem to fix it! I need to go online public wit my website tomorrow and I'm stuck with this error msg, thus cannot edit my pages :(

Love ya!

**Comment by fotoviral** [comment]
I got the same msg... Please register option-types on 'fw_option_types_init' action
How to solve??

**Comment by paulpachingel** [comment]
just updated the unyson plugin and now i'm seeing this notification at top of the dashboard and the website itself: "Please register option-types on 'fw_option_types_init' action"
PLEASE HELP!

**Comment by eyeswizard** [comment]
don't worry guys i have reported @moldcraft here https://github.com/ThemeFuse/Unyson/issues/1993 and he will provide us with the fix update in the next hours...

**Comment by moldcraft** [comment]
Have anybody ever tested Unyson here https://github.com/ThemeFuse/Unyson-Extensions-Approval ?

**Comment by eyeswizard** [comment]
no i didn't!

**Comment by danyj** [comment]
@moldcraft always testing new versions, see  https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/258#issuecomment-246147309

**Comment by stevedapper** [comment]
Thx for helping out, @moldcraft

ᐧ

*Steve Tarantola*
*Vice President of Operations*
*AZ Pneumatics LLC*
100 Cambridge Street, 14th Floor
Boston, MA 02114
Office: +1 (617) 861-6309 | Mobile: +1 617-319-9864
web: www.azpneumatica-usa.com

Twitter: www.twitter.com/azpneumaticausa | Facebook:
www.facebook.com/azpneumaticausa | Youtube: www.youtube.com/azpneumaticausa |
Instagram: www.instagram.com/azpneumaticausa

**Comment by fotoviral** [comment]
Hi, this error was FIXED here:
http://support.xpeedstudio.com/knowledgebase/unyson-update-issue/

Just update the mencioned file!!

**Comment by Zuzor** [comment]
Hi all,

Hoping someone can help me. I updated the class-fw-extension-page-builder.php file but now I'm getting this error: 

Fatal error: Call to undefined method FW_Option_Type_Undefined::_get_shortcode_notation() in /home/content/a2pnexwpnas03_data03/26/3552726/html/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/class-fw-extension-page-builder.php on line 322

Line 322 says "$option_type->_get_shortcode_notation(self::get_access_key(), $builder_data['json'])"

How can I fix this?

**Comment by coreycanestrare** [comment]
I am having the same issue as @Zuzor

**Comment by moldcraft** [comment]
There is no `$option_type->_get_shortcode_notation(self::get_access_key(), $builder_data['json'])` in [`class-fw-extension-page-builder.php on line 322`](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.6.3/class-fw-extension-page-builder.php#L322)

> I updated the class-fw-extension-page-builder.php file

What do you mean you update the file? You updated it manually? Why?

**Comment by coreycanestrare** [comment]
He means he downloaded the zip unpacked it and uploaded it! @moldcraft

**Comment by moldcraft** [comment]
Which zip? Where you have downloaded it from?

**Comment by coreycanestrare** [comment]
@moldcraft http://support.xpeedstudio.com/knowledgebase/unyson-update-issue/

**Comment by moldcraft** [comment]
Why we should provide support for unknown download sources? Who said that is the right fix? Please use only official Unyson extensions and make sure they are up-to-date, if you still have problems/error, please report and we will fix them.
At this moment this issue is fixed and you don't need to download and install manually any files.

**Comment by coreycanestrare** [comment]
What must I do to fix this issue?

**Comment by coreycanestrare** [comment]
I only tested that download. When I realized it didn't work I went back to my original class-fw-extension-page-builder.php.

**Comment by moldcraft** [comment]
1. Make sure all Unyson extensions are up-to-date
2. Activate a default WP theme and check if the warning disappears, if it does, then it's a theme issue. Please tell theme author that he should register option-type on [this action](http://manual.unyson.io/en/latest/options/create-option-type.html#create-option-type).

**Comment by coreycanestrare** [comment]
I tested this already with Twenty Fifteen Version: 1.6 and it........FAILED still!

**Comment by moldcraft** [comment]
Can you send me admin and ftp details to `moldcraft[at]email.com`?

**Comment by coreycanestrare** [comment]
@ "email".com ??

**Comment by moldcraft** [comment]
Yes

**Comment by coreycanestrare** [comment]
Cool. Email has been sent!

**Comment by moldcraft** [comment]
I went to **Dashboard > Updates** menu, clicked on **Check Again** button, and extensions updates have appeared. After I [update the extensions](https://cloud.githubusercontent.com/assets/1475489/18487076/811455fc-79fc-11e6-9237-5ba2acd0de39.png) the warning is gone.

**Comment by coreycanestrare** [comment]
ughhhhhh....wow...thanks

I literally just updated it before I made these comments. That's weird!

Thank you for your help!

**Comment by Zuzor** [comment]
I had already updated all the extensions and was still occasionally getting that same error. It was strange because 1 out of maybe 5 page refreshes the error would show up. Anyway, reinstalling the and updating it seemed to fix it.

**Comment by fotoviral** [comment]
Hi, this error was FIXED here:
http://support.xpeedstudio.com/knowledgebase/unyson-update-issue/

Just update the mencioned file!!



Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=carlostargon@gmail.com&idSignature=22>

Obrigado

Carlos Targon

2016-09-14 7:03 GMT-03:00 Zuzor <notifications@github.com>:

**Comment by Achrafkrissi** [comment]
Just Update  Unyson Plugin and you will get the update and issue fixed instantly
