### ISSUE TITLE
Help me view in front end (view.php) multi upload option

### ISSUE THREAD

**Issue by vladimir-boyko** [ThemeFuse/Unyson#1950]
Hello. I have option.php file with the option of multi upload.
```
images =>array(
    'type'  => 'multi-upload',
    'value' => array(
     ),
    'label' => __('Label', '{domain}'),
    'desc'  => __('Description', '{domain}'),
    'help'  => __('Help tip', '{domain}'),
    'images_only' => true,
)
```
How do I properly display images from an array of options in this file Viev.php

This embodiment does not work((((
`<Img src = "<php echo $ atts [ 'images'] [ 'url']; ?>`/>

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1946
