### ISSUE TITLE
forbidden site when deactived the unyson plugin

### ISSUE THREAD

**Issue by nand2k13** [ThemeFuse/Unyson#1951]
forbidden site when deactived the unyson plugin. See like below image.
![deactivated](https://cloud.githubusercontent.com/assets/5101781/18145093/20996762-6fe3-11e6-9a8c-b18d8636d213.png)

I have this line of code except framework-customization 
<?php if ( ! defined( 'ABSPATH' ) ) { die( 'Direct access forbidden.' ); }

**Comment by danyj** [comment]
theme developer is responsible for that , theme framework override is active.

**Comment by andreiglingeanu** [comment]
@nand2k13 Find any occurrence of `die( 'Direct access forbidden.' )` in your theme and remove this one by one, Unyson's not responsible for that kind of errors.

**Comment by nand2k13** [comment]
@danyj @andreiglingeanu Thanks,
Yes this is not unyson issue, I switch other unyosn theme work fine . Sorry for creating this issue.
I create this theme from unyson demo scratch. how to diagnose this error?? Any help ??

**Comment by nand2k13** [comment]
solved
