### ISSUE TITLE
Demo Content

### ISSUE THREAD

**Issue by khangdoan03121993** [ThemeFuse/Unyson#1952]
Hi everyone, When I install the demo content there is an error: Failed insert row from line 156. Duplicate entry 'theme_mods_ht-guardian' for key 'option_name'
What to do?

![2016-09-01_06-19-02](https://cloud.githubusercontent.com/assets/15787361/18161305/96b15e6e-705b-11e6-8137-9cbaf61de725.png)

**Comment by moldcraft** [comment]
Please open your demo `database.json.txt` and search for string `theme_mods_ht-guardian`:

1. if it will be found 2 times then the problem is in demo content (a bug in Content Backup)
2. if it will be found once then it is a bug in Demo Install

In both cases I need to reproduce the problem, so send me your theme or admin/ftp details to `moldcraft[at]email.com`

**Comment by moldcraft** [comment]
Thanks for the email. I will take a look tomorrow.

**Comment by Ataurr** [comment]
One of our buyer also face same issue.
![screen shot 2016-09-05 at 4 47 38 pm](https://cloud.githubusercontent.com/assets/6223399/18245701/8ad6efd4-7388-11e6-9c59-16b9af8a255f.png)


I have check our json file only one available `theme_mods_book-child` 

Did you found any solution ?

**Comment by khangdoan03121993** [comment]
It worked. Thank you so much!

2016-09-05 22:19 GMT+07:00 moldcraft <notifications@github.com>:

**Comment by moldcraft** [comment]
This is the fix https://github.com/ThemeFuse/Unyson-Backups-Extension/compare/1be855780f85edacc0cd172a9bd357f56df6a5b2...5efdf975f7b27e80b5dc468a9c280c83b826240c

@khangdoan03121993 Thank you for sending me your theme so I was able to detect these problems on my localhost (working via FTP is pain)

**Comment by Ataurr** [comment]
This issue not resolved yet. 

I am just update one of our theme extensions and tried to install demo content and facing same issue one of my demo content install.

**Comment by moldcraft** [comment]
@Ataurr Have you installed the [latest dev version of Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension/archive/master.zip) in `wp-content/plugins/unyson/extensions/backups`?

**Comment by Ataurr** [comment]
Ops Sorry. Dev version work fine now

Thanks very much
