### ISSUE TITLE
Popup js needs "pre render" and "pre close" events

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1956]
**Render event**
I have a situation when the popup is opened, I'm manipulating option elements inside the popup , but 
`fw:option-type:popup:render` event is too late, because the user can see the options being manipulated (removed).
So there should be a `pre-reneder` event or `pre-animation` event, when all options are initialized and ready to go , but they are still wainting to be animated in (opacity).
And after that event  fw:option-type:popup:render` event should be fired in [deferred manner](http://underscorejs.org/#defer)

**Close event**
I need a close event, so I can clean up the code that I'm using inside the popup (click events etc..)
But `fw:option-type:popup:close` is fired **after** you have removed all elements from the popup.
So I'm left with memory leaks.

**Comment by andreiglingeanu** [comment]
@ivandotv What really are you trying to achieve? Are you trying to hook up on the shortcode modals? Or you are trying to build some widget that happens to be located in a modal?

If you are trying to build something general-purpose in a modal, I'd suggest you to take a look at how to extend `fw.Modal` in an manageable way - [here](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon-v2/static/js/icon-picker-v2.js). It has everything - [data preload and html pre-render](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon-v2/static/js/icon-picker-v2.js#L151-L156) and event listeners that work [correctly](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon-v2/static/js/icon-picker-v2.js#L200-L214) even if you have multiple instances of the same widget on the same page.

<hr>

> So I'm left with memory leaks.

You can dettach delegated events to `$(document)` even after element was removed from the DOM, if you keep the same reference to the event listener.

Good luck!

**Comment by danyj** [comment]
@andreiglingeanu I am sure he is trying to do same things like many of us which is hide specific popup option depending on the current theme/page option value and yes he is right when he says that render fires to late 

.Not only that but the modal itself has been changed so many times since about 5 months that I personally have no idea what event to use anymore and are forced to come up with own independent script or delays that would simply hide a darn thing when popup opens.

https://github.com/ThemeFuse/Unyson/issues/1236#issuecomment-175726129
https://github.com/ThemeFuse/Unyson/issues/1042

if you are so sure that this is doable, than please provide a snippet that we can all use (  and stick with it once and for all ) and put this issue to the end.

**Comment by andreiglingeanu** [comment]
I'm pretty sure you've got problems with `lazy_tabs`, be sure to render them before trying to manipulate the DOM in any way. That's the only problem that may arise.

**Comment by danyj** [comment]
popup:render should take care of that on its own and know if lazy_tabs is on or not since the render event was created for this particular use and that is let us manipulate the popup content before everything is shown

**Comment by andreiglingeanu** [comment]
> popup:render should take care of that on its own and know if lazy_tabs is on or not

You're not correct here. What if the popup is big enough and you don't want to suffer the BIG delay of rendering tabs for every tab, just for the sake of rendering an event a _bit_ more consistently.

**Comment by danyj** [comment]
Than whats the use of the render at all and or lazy_tabs if none of them work together the way they should?

But all in all seems like we are wrong , lazy_tabs is not the issue , render is simply late , 


this worked perfect couple months back 

			fwEvents.on('fw:builder-type:page-builder:item-type:simple:options-modal:render', function(data){
				
				if (data.shortcode != 'calendar') {
					return;
				}
				
				var calendar_options =  data.modal.get('values');

				
				console.log(calendar_options);
							
								
			});



I just turned lazy_off  and this still does not work , it returns and empty object

http://prntscr.com/cd72ve

**Comment by andreiglingeanu** [comment]
@danyj They always worked like that. Save the modal and open it once again - you'll get an object full of options.

**Comment by danyj** [comment]
Please stop being so defensive, none of us are talking about he/she did this and that , we are simply looking for solution and are bit tired of undocumented changes 


no it was not like that , this is exact code I used before to hide some options and it is from here 
https://github.com/ThemeFuse/Unyson/issues/1042#issuecomment-159859716

**Comment by andreiglingeanu** [comment]
I'm just telling you that you code actually works in a correct way. No one's messing with already documented events.

<hr>

Aside from this discussion:

I just tried to access all of the HTML from modal with this code. With `lazy_tabs` off. Worked just fine.

```javascript
fwEvents.on('fw:builder-type:page-builder:item-type:simple:options-modal:render', function(data){
    if (data.shortcode != 'counter') {
        return;
    }

    console.log(data.modal.frame.$el.html());
});
```

**Comment by danyj** [comment]
ok , looks like no matter what I am trying to say it goes the other way , I provide a non working snippet , say lazy_tabs is off and you say your code works. bud ,  do you think we are making things up and spend our time here to mess with you. why is it that you dont want to try the code I provided , it is calendar shortcode , 

and I did not ask for html at all , I advised and gave you snippet that worked ,  not getting html but getting the modal option values which worked without issues before.

**Comment by ivandotv** [comment]
I have a `switch` option, that hides and show elements. And sometimes elements need to start hidden.

**Comment by andreiglingeanu** [comment]
@ivandotv You're having a custom option type with a modal created in your JS?

**Comment by ivandotv** [comment]
@andreiglingeanu 
No I have my own js code that hooks in to your `switch` component, and hides/shows other options.
But we are getting of the topic.
The point of this issue is that we need to be able to edit the contents of the modal window before the content is shown.

**Comment by danyj** [comment]
@ivandotv  try with this change , 
https://github.com/ThemeFuse/Unyson/issues/1042#ref-commit-75199c0

options should be available before render now, did not test

**Comment by ivandotv** [comment]
As I posted in this issue #1957 we definitively need a way to do a cleanup before all the elements are removed.
One example need is to tear down the tinymce editor before the popup elements are removed from the DOM, or there will be a bunch of errors with that library.

**Comment by moldcraft** [comment]
> One example need is to tear down the tinymce editor before the popup elements are removed from the DOM, or there will be a bunch of errors with that library.

This is [already done](https://github.com/ThemeFuse/Unyson/blob/719c5d0d38938f38cabbd4f2eee7d7e0af267636/framework/includes/option-types/wp-editor/static/scripts.js#L97-L98)

**Comment by moldcraft** [comment]
[Render is triggered right after options init](https://github.com/ThemeFuse/Unyson/blob/eeb6d2351eb512b5f6765ad4daf8869f4edc803d/framework/static/js/fw.js#L647-L649). Please privide a pull request with your desired behavior because I don't know how to fix this (how to add a `pre-render` event)

**Comment by moldcraft** [comment]
> I need a close event, so I can clean up the code that I'm using inside the popup (click events etc..)

All jQuery elements fire the `remove` event when the modal html is cleared, so you can use that instead of a modal `close` event

```js
jQuery('#YOUR-ELEMENT').on('remove', function(){ console.log('Before Remove'); });
```

**Comment by ivandotv** [comment]
@moldcraft As I have shown in the #1957 obviously something is not getting cleaned up.
Please note that the wp-editor is inside the multi-picker.

**Comment by moldcraft** [comment]
wp-editor glitches is a separate discussion

**Comment by andreiglingeanu** [comment]
@ivandotv Please refer to https://github.com/ThemeFuse/Unyson/issues/1957#issuecomment-245191804.
