### ISSUE TITLE
Migration to native term meta #1745

### ISSUE THREAD

**Issue by hlaporthein** [ThemeFuse/Unyson#1958]
Hello Unyson group, 
 According to 2.6.0 plugin update, you moved to native term meta table. So, Is fw_termmeta table still necessary? Could I remove it if it doesn't no longer use. But, I still found some of my meta_value column like below 

`a:3:{s:13:"banner_slider";a:0:{}s:22:"seo-titles-metas-title";s:0:"";s:28:"seo-titles-metas-description";s:0:"";}`

I have tested banner_slider option, seo title and description, any of them didn't save in fw_termmeta. So, let me know fw_termmeta is still needed or not. Thanks in advance.  :)

**Comment by andreiglingeanu** [comment]
The old will be here for a while till we'll be sure we no longer need it. We are deprecating old table and moving data to new table progressively - we can't introduce breaking changes. That's the only way to go.

**Comment by moldcraft** [comment]
The data is lazy migrated until the table remains empty then it is deleted

https://github.com/ThemeFuse/Unyson/blob/v2.6.0/framework/helpers/database.php#L344-L371

**Comment by hlaporthein** [comment]
Thanks @andreiglingeanu and @moldcraft
