### ISSUE TITLE
fw_ext_wp_shortcodes_data is not defined  

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1959]
Getting this in page builder with latest master for unyson and all extensions

 http://prntscr.com/cd73c5
http://prntscr.com/cd73gp

**Comment by andreiglingeanu** [comment]
You don't have latest *WP Shortcodes*.

**Comment by danyj** [comment]
Just got the latest again and same bug http://prntscr.com/cd7848

**Comment by andreiglingeanu** [comment]
[This](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/master/static/js/plugin.js#L376-L392) should match your `static/js/plugin.js`.

**Comment by danyj** [comment]
it matches

**Comment by danyj** [comment]
http://prntscr.com/cd796x

**Comment by danyj** [comment]
who ever has theme overrides and on first wp-shortcodes did this 
https://github.com/ThemeFuse/Unyson/issues/1807#issuecomment-234638082
in static.php

need to change it to this now 


```

if (is_admin()) {
	wp_register_script(
		'fw-ext-shortcodes-editor-integration',
		fw_ext('shortcodes')->get_uri('/static/js/aggressive-coder.js'),
		array('fw'),
		fw_ext('shortcodes')->manifest->get('version'),
		true
	);

	wp_enqueue_script(
		'fw-ext-shortcodes-load-shortcodes-data',
		fw_ext('shortcodes')->get_uri('/static/js/load-shortcodes-data.js'),
		array('fw'),
		fw_ext('shortcodes')->manifest->get('version'),
		true
	);
}
```
