### ISSUE TITLE
Builder page templates

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#1960]
Good morning...
I wanted to know if there is some trick to save a template page on multisite.
for example, unyson has a hook like "save_template_hook"?
thank's

**Comment by WPJobs** [comment]
Hi, @sandromattei !

Template can be saved via page builder, it works fine for me on Multisite too
![2016-09-05_10-52-01](https://cloud.githubusercontent.com/assets/12991525/18240866/e36ecc66-7356-11e6-8f81-8a48d5f3135f.png)

**Comment by moldcraft** [comment]
You can create predefined templates via [this filter](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/d74366487f42fcc56bf3342b65470f6eced18a85/includes/option-types/builder/includes/templates/class-fw-ext-builder-templates-component.php#L69) https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/33
