### ISSUE TITLE
Unyson 2.6.0: WordPress Shortcodes module breaks Editor

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1961]
Hello!

After upgrading to Unyson 2.6.0, if WordPress Shortcodes module is active, i can't switch Page Builder to Default editor, also, i can't create any page in default WP editor mode, i always see Visual Editor and there is not button to switch between editors
![2016-09-02_13-07-23](https://cloud.githubusercontent.com/assets/12991525/18200653/85fcab9c-710e-11e6-8c5e-661190d525c5.png)

**Comment by WPJobs** [comment]
Console screenshot 
![2016-09-02_13-10-24](https://cloud.githubusercontent.com/assets/12991525/18200678/aa8a50cc-710e-11e6-9311-b3760140fade.png)

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/1959#issuecomment-244309318

**Comment by danyj** [comment]
or delete  static.php  from shortcodes/     folder in theme overrides

**Comment by WPJobs** [comment]
sorry, but i don't have static.php file in shortcodes folder, only hooks.php

**Comment by andreiglingeanu** [comment]
Update your shortcodes extension please.

**Comment by WPJobs** [comment]
i did, i'm using latest Unyson and latest extensions :)

**Comment by andreiglingeanu** [comment]
Check WP shortcodes then. It must be outdated in this case. You should download latest GitHub version.

**Comment by WPJobs** [comment]
that's strange, i copied "Unyson" folder from another website and now it works, but when i installed Unyson & Extensions from WP admin panel it caused an error, anyway, thank you for your quick reply and for your help!

**Comment by moldcraft** [comment]
Ctrl+Shift+R or Updates page > Check Again button
