### ISSUE TITLE
From & to value of datetime range in fw-storage

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#1963]
Is it possible to put the from & to value of a datetime range in a separate fw-storage?

I managed to put the serialized array of the datetime range option in a fw-storage, but I need the separate from & to value for my meta query.

Is there a way to do this with fw-storage?

**Comment by moldcraft** [comment]
You have to [create](https://github.com/ThemeFuse/Unyson/blob/eeb6d2351eb512b5f6765ad4daf8869f4edc803d/framework/helpers/fw-storage.php#L100) a new fw-storage type. Here is an example: [Create](https://github.com/ThemeFuse/Unyson-Sidebars-Extension/blob/f4d6c9063146877eb85670463b14288a188bbd5a/class-fw-extension-sidebars.php#L71) & [Use](https://github.com/ThemeFuse/Unyson-Sidebars-Extension/blob/f4d6c9063146877eb85670463b14288a188bbd5a/class-fw-extension-sidebars.php#L123)
