### ISSUE TITLE
Get data from custom post type options

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#1964]
Hi guys,

I'm using some theme/page settings on a custom post type which is fine. The issue I'm having is pulling any data at all.

I usually use the following to pull data from theme options which work fine, but not in this case.

```php
$footer = ( function_exists( 'fw_get_db_settings_option' ) ) ? fw_get_db_settings_option('footer') : '';
echo wp_kses_post($footer);
```

Here are the options for my custom post type -

```php
$options = array(
	'service' => array(
		'title' => __( 'Service Settings', 'cultivators' ),
		'type'  => 'tab',
		'priority' => 'high',
		'options' => array(
			'service-box' => array(
				'title'   => __( 'Update Settings', 'cultivators' ),
				'type'    => 'box',
				'options' => array(
					'thumbnail' => array(
						'label' => __( 'Thumbnail', 'cultivators' ),
						'desc'  => __( 'Upload a thumbnail image to display on other service pages.', 'cultivators' ),
						'type'  => 'upload'
					),
					'description'    => array(
						'label' => __( 'Description', 'cultivators' ),
						'type'  => 'textarea',
						'desc'  => __( 'Type a short description to display on other serve pages.', 'cultivators' ),
					),
				)
			),
		)
	)
);
```

Any help would be awesome as I couldn't find any docs to help.

Thanks!

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/helpers/php.html#fw-get-db-post-option

**Comment by klvmedia** [comment]
Thanks for pointing me in the right direction,
`$service = ( function_exists( 'fw_get_db_post_option' ) ) ? fw_get_db_post_option('service') : '';`

This works perfectly fine for options of the page you're viewing - but I have a custom post type loop on the page and I'm trying to get the info from those custom posts. 

All I can seem to get is the options for the landing page, hope this makes sense.

**Comment by moldcraft** [comment]
> `fw_get_db_post_option('service')`

You call this function wrong, the first parameter is post_id and the second is option_id.
