### ISSUE TITLE
WordPress shortcodes one more bug

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1965]
Hi again!

I've just noticed a bug in the latest Unyson / WP shortcodes extension, how to reproduce it:

1) Create the page, switch to default WP editor

2) Click on Shortcodes button, choose "Forms"

3) Get an error in the console
![2016-09-02_17-46-54](https://cloud.githubusercontent.com/assets/12991525/18207804/54579e04-7135-11e6-9839-73196a0def62.png)

after that, i can't switch default WP editor to text mode / Unsyon page builder

**Comment by andreiglingeanu** [comment]
And one again, you are having outdated extensions. @moldcraft are those changes released?

**Comment by WPJobs** [comment]
@andreiglingeanu be sure that these extensions are latest, WP shortcodes manifest says version "1.3.19"

**Comment by andreiglingeanu** [comment]
You may need to get latest versions from GitHub, if they're not yet released. Let's wait for @moldcraft.

**Comment by WPJobs** [comment]
I checked GitHub version of WP shortcodes https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/manifest.php, Manifest has version 1.3.19 too

ok, let's wait :)

**Comment by moldcraft** [comment]
These versions are released

* https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/tree/v1.0.1
* https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/v1.3.19

**Comment by WPJobs** [comment]
Guys, definetely, there are some problems with update.

I just deleted the whole "Unyson" folder from /wp-content/plugins/, and installed Unyson Again using Plugins screen, then i downloaded and installed Unyson extensions via WP Admin -> Unyson screen.

Now i get [this bug](https://github.com/ThemeFuse/Unyson/issues/1961) again

**Comment by moldcraft** [comment]
@WPJobs Maybe you have a cache plugin active?

**Comment by WPJobs** [comment]
@moldcraft i cleaned browser cache and both problems are gone, sorry for this! Have a great weekend!
