### ISSUE TITLE
Forms question

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1966]
Hi!

I was just wondering, is there a simple way to run Forms Editor via JavaScript and save this data to some field (e.g. hidden field) / and load this data to form builder later? 

You have a great form builder, but there is no way to add a form to the footer as a widget, for example :)

Thank you all and have a great weekend!

**Comment by moldcraft** [comment]
Hello,

There is no simple way. You can inspect the [Contact Form shortcode](https://github.com/ThemeFuse/Unyson-Forms-Extension/tree/26b57ec4f255452ec8b8adcfd37a4ce6295f5eb8/extensions/contact-forms/shortcodes/contact-form) and maybe figure out a solution.
