### ISSUE TITLE
500 Error?

### ISSUE THREAD

**Issue by abinterfaces** [ThemeFuse/Unyson#1967]
The moment I updated to Unyson v2.6.0 I got a server 500 error. If I remove the plugin the site comes back. Activate the plugin I get the error again (every time).

How can I fix this?

PS - I looked for the previous version to download and see if that helps but can't find it.

**Comment by moldcraft** [comment]
Please check server error log or give me admin/ftp access `moldcraft(at)email.com`

**Comment by abinterfaces** [comment]
Brand new to GitHub. How do I send you a private message with this info??

**Comment by moldcraft** [comment]
I have given you my email, send a simple email. (Github doesn't have private messages)

**Comment by moldcraft** [comment]
The problem is from file-cache

I added a fix on your server, but I am not sure 100% if it will not happen again.
If it will happen, please report that and we will try something else (maybe delete file-cache)

**Comment by moldcraft** [comment]
Similar issue https://github.com/ThemeFuse/Unyson/issues/1968

**Comment by abinterfaces** [comment]
Can you please fix this site for me too? This new site is now down. It’s the same problem as the other site. It just went blank (500 error) because of the Unyson plugin (I assume the same caching issue).

 

WordPress:                                      

www.colonialconnections.com/wp-admin <http://www.colonialconnections.com/wp-admin> 

Un: moldcraft

Pw: 4YH0vx)35YyRWacp9S4N6r2k

 

FTP:

Host: colonialconnections.com

Un: f239276.moldcraft

Pw: m8f#84=59Sj6aA#l

 

PS – Is this going to be an issue for all of my sites moving forward that use this plugin?

 

Sincerely,


Anthony Bennett
CEO & President

Website Specialists
757-741-2737
 <mailto:info@abinterfaces.com> info@abinterfaces.com


Visit Our Website:  <http://www.abinterfaces.com/> www.abinterfaces.com

 <http://eepurl.com/u_xM9> eNewsletter
 <http://www.facebook.com/pages/AB-INTERFACEScom/312327072101> Facebook
 <https://twitter.com/abinterfaces> Twitter
 <http://www.abinterfaces.com/blog/> Blog

 <http://www.abinterfaces.com/>

**Comment by moldcraft** [comment]
You have given you ftp details to the public.

The solution: Delete `wp-content/uploads/fw/file-cache.php`

**Comment by abinterfaces** [comment]
How the heck did I do that?? By not changing the subject line I guess and it got posted I guess?

 

Oh well, deleted the file and the access. Thank you so much!
