### ISSUE TITLE
[Feature Request] Allow html on Icon box title and content

### ISSUE THREAD

**Issue by rubengc** [ThemeFuse/Unyson#1969]
Really this feature can be applied to other content elements

In most elements you can enter a title, label or description the framework detects the html tags as plain text

This prevents from many content elements (such as the icon box) can not enter a bold text or a link in their content

It makes me having to manually enter all the html element manually when all I need is a simple link

**Comment by moldcraft** [comment]
Hello,

We can't change the default behavior because a lot of themes rely on it.

The only solution is to overwrite shortcodes views in your theme and allow html _(do not htmlentity or strip tags)_

**Comment by rubengc** [comment]
precisely, if they know this behavior they have used only plain text so any current theme would be affected
