### ISSUE TITLE
Multi picker label layout inside popup

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1972]
Currently multi-picker layout doesn't look good inside the popup.
It is all pushed to the right.
Also there are two labels (as there should be) mulit-picker, and select.
However if I use empty string for `select` label in order to move the select to the left. It still uses certain width via css. And empty `multi-picker` label also uses certain width.
![selection_001](https://cloud.githubusercontent.com/assets/390700/18249534/35daf1dc-737f-11e6-8c4c-b9d1da9e67af.png)

**Comment by danyj** [comment]
only way I was able to remove it is with false and use the label and desc of the select


```
				'type' => 'multi-picker',
				'label' => false,
				'desc' => false,
```

**Comment by ivandotv** [comment]
Thanks , that is the way to go.
I was using an empty string, because I though that will be evaluated to `false` but it seems that the framework strictly  wants the real false value.

**Comment by andreiglingeanu** [comment]
@ivandotv There's no better way to check it than the [source](https://github.com/ThemeFuse/Unyson/blob/master/framework/views/backend-option-design-default.php#L89)
