### ISSUE TITLE
oembed inside popup not working

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1973]
Just put a `oembed` option inside popup and paste in youtube url.
It will trigger js error and nothing will be displayed.
Some kind of ajax oembed error.
file: oembed.js
line :26

**Comment by mowshon** [comment]
I put `oembed` inside the `popup-options` and everything is fine. Maybe is something wrong with server response where video is hosted.

**Comment by mowshon** [comment]
Can you give your `options` structure and video link ?
