### ISSUE TITLE
Portfolio extension

### ISSUE THREAD

**Issue by vladimir-boyko** [ThemeFuse/Unyson#1975]
Hello, How to display portfolio 8 posts on the main page in the page builder?

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/1140

**Comment by vladimir-boyko** [comment]
dannyj not help( you can please more instruction and tutorial plese.....((

**Comment by player0k** [comment]
Read this [Unyson documentation](http://manual.unyson.io/en/latest/)

**Comment by danyj** [comment]
Is it so hard to read bud?   
![screenshot_6](https://cloud.githubusercontent.com/assets/2340172/18264305/c378d1e0-740f-11e6-9442-eba3fd3bb09b.jpg)

Which than takes you to  https://wordpress.org/support/topic/filter-portfolio-items-by-categories-in-page-builders-gallery-portfolio/#post-7682966

You are in a wrong place if you think that anyone here would tutor you. We all give each hints , links , small snippets etc, but we dont provide full blown "this is how to code" tutorials.
