### ISSUE TITLE
Shortcodes not working since the last update in Default Editor

### ISSUE THREAD

**Issue by Alex-Ascet** [ThemeFuse/Unyson#1976]
Hi there,
Just to inform you that the shortcodes does not work in the Default Editor since the last update. Once you save the page, shortcodes disappear. Annoying.
This is happening on several websites in my case.
Thank you.

**Comment by moldcraft** [comment]
Hello,

Please create a video or give a screenshot of your browser Console (maybe there are errors).
Or give the exact steps to reproduce the problem.

**Comment by Breakern** [comment]
I have the same problem, error -

`Uncaught ReferenceError: fwShortcodesAggressiveCoder is not defined  plugin.js?wp-mce-4401-20160726:249 `

**Comment by moldcraft** [comment]
Make sure Unyson Extensions are up-to-date then clear browser cache and refresh page.

**Comment by Breakern** [comment]
Deleted extension and re-installed. Working now. Thanks.
