### ISSUE TITLE
Woocommerce page import not importing page builder elements

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#1977]
I am trying to import the content of my new woocommerce theme using WordPress XML import. Well, the unyson page builder elements is not showing up on import. I tried another xml from one of my other WordPress theme and it works like charm. 

Can you please give me an insight about this?

**Comment by linjo** [comment]
Update: I doubt this is an issue with the export, i had an old export file which worked fine. The newly exported files are the ones that doesnt work.

Thanks

**Comment by moldcraft** [comment]
Hello,

We don't support WordPress XML export/import. We recommend [Demo Content Install](http://manual.unyson.io/en/latest/extension/backups/index.html#content)

**Comment by linjo** [comment]
I think themeforest wont approve theme without the demo content import. Will themeforest approve themes with the Unyson Demo Content Install?

**Comment by danyj** [comment]
Yes they will , https://themeforest.net/tags/unyson , they all use Unyson demo and it has been tailored to be approved on TF
