### ISSUE TITLE
Alternative for multi-picker

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#1978]
We all know that multi picker is very heavy and builds unnecessary arrays when you simply need to hide option or two. 

Here is small JS script  that can save you time and data size in your options.
**Please  feel free to refine it and share better solution/fix/suggestion.**

Add this  in your admin script if you have one or anywhere where you feel it fits  

	function ThzAddName( $selector, $elements ){
		
		var $addon = '#fw-backend-option-fw-option-';
		
		if($selector.parents('.media-frame-content').length){
			$addon = '#fw-backend-option-fw-edit-options-modal-';
		}
		
		var $replace = new Array();
		var $leave = new Array();
		
		if($elements){
			var $all_el = $elements.split(',');
			
			
			
			$.each($all_el,function(index,el){
				
				if(el.indexOf('.') == -1 && el.indexOf('#') == -1){
					
					$replace.push($addon + el);
					
				}else{
					
					$leave.push( el );
				}
				
				
			});
		}
		var $new_elements = $leave.concat($replace).join(',');
		
		return $new_elements;
	}
	
	
	setTimeout(
		function(){
			fwEvents.on('fw:options:init', function(data){
	
				if (data.lazyTabsUpdated && !data.lazyTabsUpdated){
					 return;
				}
	
				
				$('.thz-select-switch:not(.thz-switch-initialized)').each(function(i, el) {
					
					var $ldisable = ThzAddName($(this), $(this).find('option:selected').attr('data-disable'));
					var $lenable = ThzAddName($(this),$(this).find('option:selected').attr('data-enable'));
					var $lcheck = ThzAddName($(this), $(this).find('option:selected').attr('data-check'));
	
					$($ldisable).not( ".is_done" ).hide().addClass('is_done');
					$($lenable).not( ".is_done" ).show().addClass('is_done');
	
												
					$(this).on('change', function(e) {
						var $disable = ThzAddName($(this), $('option:selected', this).attr('data-disable'));
						var $enable = ThzAddName($(this), $('option:selected', this).attr('data-enable'));
						var $check = ThzAddName($(this), $('option:selected', this).attr('data-check'));
						
						if($check){
							$($check).find('select').trigger('change');
						}
	
						$($disable).hide();
						$($enable).show();	
						e.stopImmediatePropagation();
					});
	
				}).addClass('thz-switch-initialized');
				
				
				
			})
		},20);
	

The usage ( See comments for more details  );

	'test_switch' => array(
		'label' => __('Test switch', 'fw'),
		'desc' => __('Testing', 'fw'),
		'type' => 'select',
		'value' => 'option1',
		'attr' => array(
			'class' => 'thz-select-switch'
		),
		'choices' => array(
			'option1' => array(
				'text' => __('Option 1','fw'),
				'attr' => array(
				
					'data-disable' =>'test2', 
					/* comma separate more options like test1,tes2,test3
					   can also use id or class name like, #something,.something_else
					*/
					'data-enable' =>'test1',
					/*
					'data-check' =>'', 
					  this is used when you have thz-select-switch inside thz-select-switch
					  to nudge the insider to initiate enable/disable own elements.
					  needs the inside select name, id , or class
					*/
				),					
			),
			'option2' => array(
				'text' => __('Option 2','fw'),
				'attr' => array(
					'data-disable' =>'test1',
					'data-enable' =>'test2',
				),					
			),
						
		)
	 ),	
	
	'test1'    => array(
		'type'  => 'text',
		'label' => __( 'Test 1', 'fw' ),
		'value' => 'My name is option test 1',
	),
	
	'test2'    => array(
		'type'  => 'text',
		'label' => __( 'Test 2', 'fw' ),
		'value' => 'And I am option test 2',
	),

here is demo  video http://take.ms/IzA3Q

**Comment by Ataurr** [comment]
Great job mate 🉑  🎯

**Comment by thednp** [comment]
To be honest, I was expecting Unyson to work this way from the start, but I'm grad it works somehow and I got used to it.
