### ISSUE TITLE
[suggestion] Ajax save  theme options

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#198]
Have you guys considered the ajax save option for theme options page?
The save and reload is kinda out of most frameworks and plugins out there.

**Comment by moldcraft** [comment]
At the moment you can include this script from your theme to make the form ajax submittable

```javascript
/**
 * Settings form ajax submit
 */
(function(){
    var $form = jQuery('form.fw_form_fw_settings');
    
    if (!$form.length) {
        return;
    }
    
    var $pageTitle = jQuery('.wrap h2:first'),
        isBusy = false;

    $form.on('submit', function(e){
        e.preventDefault();
        
        if (isBusy) {
            alert('Wroking... Please wait.');
            return;
        }

        if ($pageTitle.next().is('.fw-flash-message')) {
            $pageTitle.next().remove();
        }
        
        var $submitButton = jQuery(this).find('input[type="submit"][name]:focus');
        
        isBusy = true;
        
        jQuery.ajax({
            method: 'post', 
            data: $form.serialize() + ($submitButton.length ? '&'+ $submitButton.attr('name') +'='+ $submitButton.attr('value') : '')
        })
        .done(function(html){
            isBusy = false;
            var $messages = jQuery(html).find('.fw-flash-message');
            
            if ($messages.length) {
                $pageTitle.after($messages);
            } else {
                $pageTitle.after('<div class="error"><p>Oops! Something went wrong.</p></div>');
            }
        })
        .fail(function(xhr, status, err){
            isBusy = false;
            $pageTitle.after('<div class="error"><p>Oops! Something went wrong. '+ status +' '+ err.toString() +'</p></div>');
        });
    });
})();
```

----

We will reply later if we will implement this feature or not.

**Comment by danyj** [comment]
thank you!

**Comment by sergiubagrin** [comment]
Hi @danyj, 

I added it to "To DO list"

Thanks

**Comment by moldcraft** [comment]
@sergiubagrin Where I can find the "To Do list" ?

**Comment by danyj** [comment]
:+1:   @moldcraft next to bucket list :)

**Comment by moldcraft** [comment]
@sergiubagrin @danyj 

* How the user or developer will switch between standard form submit and ajax submit (a config parameter in the theme) ?
* @sergiubagrin [Design] How the save process will look, there will be some loading animation effect? How the success/error message will look?

**Comment by sergiubagrin** [comment]
> How the user or developer will switch between standard form submit and ajax submit (a config parameter in the theme) ?

For theme setting it is not needed switch. Always will be used Ajax submit

> @sergiubagrin [Design] How the save process will look, there will be some loading animation effect? How the success/error message will look?

We can add flash message after Theme Settings

**Comment by moldcraft** [comment]
> @sergiubagrin We can add flash message **after** Theme Settings

[Like this?](http://static.md/5c0a031393f6eef868b9d0d1e3a255d5.png)

**Comment by danyj** [comment]
@moldcraft looks OK to me ,  if we have a popup in admin somewhere would also be nice
like http://screencast.com/t/kqM9MIxfzv1D

**Comment by sergiubagrin** [comment]
Yes but after Page Title (Theme Settings): http://screencast.com/t/hflK0DRr3Tn

**Comment by danyj** [comment]
What ever you opt for please add a progress bar or preloader, 
progress example http://screencast.com/t/UsbwTXMW2

**Comment by danyj** [comment]
@sergiubagrin ,  you have only few options there , 
if user has half of the options you have in scratch demo he wont see the msg 
example http://screencast.com/t/DPJLz5h1I1
so somewhere next above or under save button is better

**Comment by moldcraft** [comment]
> @sergiubagrin Yes but after Page Title (Theme Settings): http://screencast.com/t/hflK0DRr3Tn

In your screenshot the page is very small (2 options) switch to Demo Options tab, go down and press "Save", [the user won't see the message](http://static.md/b55aac299ffbeaf5795b0ee9aeedb43d.png) under title. So I think there should be a message centered on the screen (like in themefuse old framework).

**Comment by moldcraft** [comment]
@danyj How the "Reset" button will work: It will replace the form html from javascript or do a page refresh?

**Comment by danyj** [comment]
@moldcraft didn't we cover reset button here
https://github.com/ThemeFuse/Unyson/issues/197#issuecomment-72047778
reset should just reset form values to its defaults , no page reload, no saving 
add msg that values have been reset aka " Options have been reset. Please hit save button to save them"

**Comment by moldcraft** [comment]
> just reset form values to its defaults

The defaults are on the server.
I have to make an ajax to:
1. Delete (reset) all database values
* Generate form html with default values
* Show it in the browser

ok, I will replace the form html from javascript.

**Comment by danyj** [comment]
I managed that  "issue" on our framework with js array of default values that are always loaded in admin backend . http://screencast.com/t/Hfz5gCRxvt
And on reset the form just gets that array and puts the values back .
But I had xml defaults that I was able to read and pull out default values.
Not sure how you will get the defaults for unyson.

**Comment by moldcraft** [comment]
All your (json) values seems simple.
We have some complicated options (for e.g. addable popup, addable box) that can't be reset from js. 
The only solution is to render their html on the server side (this is how our [options modal](https://github.com/ThemeFuse/Unyson/blob/35c9078d77bb3c0fb5e95a925d0fd86eddca0c11/framework/static/js/fw.js#L510) works).

**Comment by danyj** [comment]
I see what you mean. I had my complex values managed trough js templating. Basically made the option frame in js,  and on reset I get the option name from that json, see what type of form element it was and  call that option template in to view, so is easier for me to put them back the way they were.

**Comment by moldcraft** [comment]
This feature was added in [v2.1.22](https://github.com/ThemeFuse/Unyson/releases/tag/v2.1.22). Please update and let us know if it works as expected.

**Comment by danyj** [comment]
Very nice! Thank you.
