### ISSUE TITLE
Required post options

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#1981]
Hi,

I was wondering if it's possible to prevent a post from being published when one or multiple post options aren't filled.

I thought maybe adding a required attribute to a certain option would've worked, but I'm still able to save the post without any value in the option:

`'attr' => array('required' => 'required'),`

**Comment by moldcraft** [comment]
WordPress doesn't have the validate functionality, so we haven't created one too. And we don't have plans.

**Comment by warudin** [comment]
Ok, thanks for your answer!
