### ISSUE TITLE
[bug] - new show/hide page builder feature breaks layouts for sections

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1983]
**Steps to replicate**:
* create 2 columns with some lorem ipsum
* create a new section below with duplicated columns above
* clone the above 2 columns and move them under the section
* check front-end, probably should be OK
* now hide the section and check again, should NOT be OK, the **second row of columns should be outside of a section**, as set in the below screenshot
![section-hide-bug](https://cloud.githubusercontent.com/assets/6761246/18327114/a33bfa0e-7551-11e6-892a-fbf6746b0bda.png)
* same must happen with _full width_ section

**Here is how the html looks like**
![hidden-section-bug-render](https://cloud.githubusercontent.com/assets/6761246/18327387/eccb5826-7552-11e6-9ef5-2809ddf4d08b.png)

**Possible causes**: 
* For hidden sections there could be an additional/missing `<div>` tag. Perhaps the `if ("section is hidden") {}` ends before the ending `</div>` tag.
* Perhaps this happens for those who have overridden the `section` view file.

**Comment by danyj** [comment]
I have an override for sections and I am not sure if this show/hide is hiding via some filter or do I need to add  an if check in my view override? I dont see any switch here 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/views/view.php
so ?

**Comment by thednp** [comment]
IRDK about that, the thing is, I also have no idea how is this feature going to work when hiding columns.

**Comment by danyj** [comment]
never mind , it works , checked , column hide works , section hide works, 
cant confirm braking layout for now.

**Comment by thednp** [comment]
I've updated the steps to replicate, please try to follow the same steps and confirm, I really think it's a problem.

**Comment by thednp** [comment]
Oh, one of my shortcodes had a missing `</div>` tag. Please disregard.

**Comment by sergiu-radu** [comment]
@thednp I repeated all those steps, everything is ok, no problems with layout...
![localhost_8888_wordpress2__p_3668_preview_true](https://cloud.githubusercontent.com/assets/8998558/18349209/b934a194-75d8-11e6-9179-6ba15051b33c.png)
