### ISSUE TITLE
short codes ajax button load more post portfolio

### ISSUE THREAD

**Issue by vladimir-boyko** [ThemeFuse/Unyson#1984]
Hello
I created shortcod. The basis of this example taken 
https://github.com/ThemeFuse/Unyson/issues/737 

I'm trying to add a button to show more from the ajax loading. Prompt or give advice, which it is better to choose the way? Since those methods that have the network required to connect to the theme files, I also need a short code that works without a theme file. I would be very grateful!

**Comment by vladimir-boyko** [comment]
Something like this, but I do not have navigation. Unfortunately, this script is attached to the navigation(((((((((
http://www.problogdesign.com/wordpress/load-next-wordpress-posts-with-ajax/

**Comment by vladimir-boyko** [comment]
In my shortcode navigation may not be as it is displayed on a static home page(

**Comment by moldcraft** [comment]
Hello,

This is not a bug in Unyson and not a feature request. This is custom work. You can contact [this team](http://themefuse.com/custom-work/)
