### ISSUE TITLE
wp-editor: html tags `<p><br>` are removed

### ISSUE THREAD

**Issue by khangdoan03121993** [ThemeFuse/Unyson#1985]
I built text block shortcode, I use ' type => "wp-editor" '.  When I save text in a text content element, all breaks are removed. So everything gets condensed into one large paragraph. I have to put <br> tags to force the breaks, but once I save and go back into the content element to edit text, all of the <br> tags are gone. 

*Before saving:
![screenshot](https://cloud.githubusercontent.com/assets/15787361/18337296/73348fe8-75b9-11e6-88a7-d6ea11f390ea.png)
*After saving:
![screenshot](https://cloud.githubusercontent.com/assets/15787361/18337314/93f45448-75b9-11e6-8a2c-d3ab9dd19100.png)

How do I fix this issue. Thanks!

**Comment by andreiglingeanu** [comment]
Maybe because you have `<br>` there? That's not like this in the post editor?

**Comment by moldcraft** [comment]
![](https://static.md/c81dd919bd33331317bdbb64ac45d50b.png)

**Comment by khangdoan03121993** [comment]
this is Grammarly that helps me check grammar

**Comment by moldcraft** [comment]
Can you give me your options array or admin/ftp access (`moldcraft[at]email.com`) ?

**Comment by moldcraft** [comment]
Test content:

```
<p>Hello</p><br/><p>World</p>
```

**Comment by khangdoan03121993** [comment]
Sorry, I don't understand, can you explain detail. Thanks

2016-09-09 16:36 GMT+07:00 moldcraft <notifications@github.com>:

**Comment by moldcraft** [comment]
Never mind, I just posted the test text from your screenshot to be able to make copy/paste while tested.
I haven't found the solution yet.

**Comment by moldcraft** [comment]
Info for devs: I have added `console.log(editor.getContent());` on init https://github.com/ThemeFuse/Unyson/blob/a072d728f6bb3ddb25012226c34d3939c98f9f07/framework/includes/option-types/wp-editor/static/scripts.js#L43-L87
and it shows `<p>Hello</p><br/><p>World</p>`
so the removal happens somewhere deeper (in tinymce/js scripts)

**Comment by moldcraft** [comment]
@khangdoan03121993 Thank you for admin/ftp details, I don't need them anymore. I can reproduce the problem on my localhost

**Comment by reverbunit** [comment]
do I add the above code to the scripts file to remedy this issue? It is stripping out all my CSS/HTML.
https://advancedroboticsgroup.com/available-arg-positions/
<img width="860" alt="screen shot 2018-02-03 at 11 05 30 am" src="https://user-images.githubusercontent.com/36110009/35769558-9cd79d4c-08d2-11e8-902e-3232a1cb5bf6.png">
