### ISSUE TITLE
blank pages when logout

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#1986]
Hi...(sorry for my english).
i have a urgent problem with unyson.
when i logged in into wp, the site display correctly, but when logout, i show only blank pages in frontend and backend.
I am forced to remove the plugin folder unyson to again view the site.
error_log not showing errors.

i have the latest wp version and plugin.
please help me. thank's.

PS
the plugin reports an extension updates , but after the update, continue to indicate the presence of an update

**Comment by danyj** [comment]
WP_DEBUG on ?

**Comment by sandromattei** [comment]
yes...

**Comment by danyj** [comment]
did you try disabling the theme? is the theme unyson based? what other plugins do you have? info info info, we cant help without.

**Comment by sandromattei** [comment]
i have only one theme
the list of plugins is:
menghi (my plugin with theme settings)
multisite-language-switcher
multisite-media-share (my plugin to share media on all sites of network)
post-type-archive-links
regenerate-thumbnails
remove-blog-slug
rename-wp-login
wp-better-attachments
wp-remove-category-base
unyson

**Comment by moldcraft** [comment]
Please send admin/ftp details to `moldcraft[at]email.com`

**Comment by sandromattei** [comment]
e-mail sent

**Comment by moldcraft** [comment]
[This plugin](https://github.com/sandromattei/multisite-media-share/blob/164e0df247acb51f1948007232552b18ace4f613/multisite-media-share.php#L13) triggered the problem.
