### ISSUE TITLE
wp-shortcodes issue with wp-editor in text-block shortcode

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#1989]
I use a `wp-editor` with `'shortcodes' => true` for my `text-block` and all other content shortcodes, it was working fine some time ago, right now it gets me aggressiveCoder errors and strips nested shortcodes from the content of the `text-block` and any other content shortcode that use `'shortcodes' => true`.
Probably related to https://github.com/ThemeFuse/Unyson/issues/1985

Video https://vid.me/0Z1K

**Comment by thednp** [comment]
I have uninstalled the Unyson plugin and all extensions then reinstalled and redownloaded all extensions and seems fine, but still, what's going on?

**Comment by reverbunit** [comment]
I am not seeing a solution to this issue anywhere. it is stripping out all HTML and CSS on my build.
https://advancedroboticsgroup.com/available-arg-positions/

<img width="860" alt="screen shot 2018-02-03 at 11 05 30 am" src="https://user-images.githubusercontent.com/36110009/35769540-3c75c212-08d2-11e8-9633-26fc067965b1.png">
![screen shot 2018-02-03 at 11 05 45 am](https://user-images.githubusercontent.com/36110009/35769542-3ea8ca8e-08d2-11e8-92c0-738adbf5ca29.png)
