### ISSUE TITLE
Why is there no 1/5 column?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#199]
Is there any particular reason why you did not add 
1/5 column = 5x 20% in the page builder. 
I mean you have all combos there  from 1-6 but 1/5 is missing. 
Is just odd to have 1/4 = 4x25  and 1/6 = 6x 16.66666666666667%   but leave 20% out. 
Can we please have it?

**Comment by sergiubagrin** [comment]
@danyj - I will think about this.

**Comment by danyj** [comment]
About 70 of my themes use the 5 columns layout and this would  help me tremendously and I do not have to extend the page builder backend to add something that seems like is just missing.

**Comment by danyj** [comment]
could someone please revisit this.

**Comment by danyj** [comment]
any update on this?

**Comment by moldcraft** [comment]
We made columns sizes like in bootstrap, where all sizes are made of `1 / 12 * size`. And the class names are `.col-{device}-{1..12}`: `.col-xs-1` means 1/12, `.col-xs-7` means 7/12, etc. If all sizes are made of `1/12` parts, then you can combine different sizes easy to get a full width row http://getbootstrap.com/css/#grid-example-basic

1/5 size can't be combined with 1/12 size. You can only place 5 of 1/5 in one row. So it's not practical.
Run [this script](https://gist.github.com/moldcraft/0232edf3d1266dc83587) in your browser console to check if two grid sizes are compatible.

**Comment by danyj** [comment]
You cant honestly force us to use this grid output. Every and I mean every page builder gives you an option to add 5 or more columns without excluding the order. What developer does with it in frontend is developer problem and framework should not command this. 

If user has 4 columns and just want one more he cant do that. By this logic he must add 2 more.You cannot be serious about this.

**Comment by danyj** [comment]
Here just few top ones used
Beaver http://screencast.com/t/m335uVUfTH4i
Avia and fusion http://screencast.com/t/IQflsvtvf
Site origin http://screencast.com/t/uaZD9hGo65OX

**Comment by danyj** [comment]
And this is just few css lines that you can add in your grid to achieve it.
http://stackoverflow.com/a/22799354/594423
http://www.wearesicc.com/quick-tips-5-column-layout-with-twitter-bootstrap/

**Comment by moldcraft** [comment]
> What developer does with it in frontend is developer problem and framework should not command this.

The framework allows you to change/replace the [default grid](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/9855e25e68041fac8a715cc182cbd28807d22840/config.php#L13) via [this filter](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/d9164fc9705394fcb8fbf18ce7d704440b298004/helpers.php#L22).

```php
// file: {theme}/inc/hooks.php

function _filter_theme_grid_add_1_5_column($grid) {
    $grid['1_5'] = array(
		'title'          => '1/5',
		'backend_class'  => 'custom-backend-grid-1_5',
		'frontend_class' => 'custom-frontend-grid-1_5',
	);

    return $grid;
}
add_filter('fw_builder_item_widths:page-builder', '_filter_theme_grid_add_1_5_column');
```

**Comment by danyj** [comment]
Yes I know , 
http://screencast.com/t/mU1PUqOg
but than I need to mess with your js/css to adjust the column in the builder. 
As I stated before , when you loko at the builder columns , it just looks like it is missing.

**Comment by moldcraft** [comment]
Also note that all themes that was built with bootstrap or our grid, suddenly (after framework update) will have 1/5 column that has no styles (and it will have 100%).

**Comment by danyj** [comment]
Now that makes no sense. If you just add the 1/5  with the css I posted above everything will be in it's place. And it is beyond me why you are mentioning bootstrap when framework is not based on it and is not outputting it. No where in unyson are bs class names or components. And who ever wanted to make  theme with unyson and bootstrap he must  change the sections/rows output in order to do it since they are all prefixed with fw.

**Comment by moldcraft** [comment]
> Now that makes no sense. If you just add the 1/5 with the css I posted above everything will be in it's place. And it is beyond me why you are mentioning bootstrap when framework is not based on it and is not outputting it. No where in unyson are bs class names or components. And who ever wanted to make theme with unyson and bootstrap he must change the sections/rows output in order to do it since they are all prefixed with fw.

That's why I deleted my comment :) And now your ...

**Comment by DimiBaitanciuc** [comment]
Let us discuss this our HTML guys and we'll figure something out :), we'll keep you in the loop. One of our guys tells me that a 1/5 could be added as a non standard bootstrap.

Let us look a bit more into it and I'll get back and let you know exactly.

**Comment by DimiBaitanciuc** [comment]
Done, the scratch will come with a 1/5 column as well.

**Comment by danyj** [comment]
+1BN !!! thank you!

**Comment by moldcraft** [comment]
*We will close this when 1/5 column will be added*

**Comment by GheorgheP** [comment]
- framework - https://github.com/ThemeFuse/Unyson/commit/8042f56067327cc530256e77c40fe8989ea5f78e
 - builder - https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/78d175f56f5259f4471761b2b2dc384634b563ad

**Comment by danyj** [comment]
:100:
