### ISSUE TITLE
Unyson extensions deactivates on WordPress update

### ISSUE THREAD

**Issue by ansfazi** [ThemeFuse/Unyson#1990]
Hi, I have observed that the extensions deactivates on each WordPress update. Yesterday WordPress got updated automatically and the extensions again got deactivated.
What could be the issue
Thanks

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/search?q=extensions+deactivates&type=Issues&utf8=%E2%9C%93

this bug is just persistent and scary at the same time.

**Comment by moldcraft** [comment]
Try [these steps](http://wordpress.stackexchange.com/a/198358/60424) to reproduce the problem.

**Comment by ansfazi** [comment]
It deactivates on WordPress auto update not unyson update.

**Comment by moldcraft** [comment]
Can you (reproduce the problem) install an older version of WP, trigger somehow auto-update and check if extension deactivate?
