### ISSUE TITLE
Please register option-types on 'fw_option_types_init' action

### ISSUE THREAD

**Issue by AlphabetoPT** [ThemeFuse/Unyson#1991]
Hello i just updated unyson through wordpress as it was requesting and suddenly my backend says the following error:

http://prntscr.com/cgfhto

Also on page:
http://prntscr.com/cgfhyi

My website is www.pokemap.com.br.

Thanks

**Comment by moldcraft** [comment]
Hello,

Are Unyson extensions up-to-date?

**Comment by moldcraft** [comment]
If Unyson plugin and Unyson extensions are up-to-date, then the problem is in theme (you can test by activating a default WP theme).

Which theme are you using?

**Comment by AlphabetoPT** [comment]
I bought DW Gamez and was using it perfectly before the new update.

**Comment by AlphabetoPT** [comment]
Fixed.
Extensions were not updated.
Sorry to boder you.
Thank you

**Comment by aminkhm** [comment]
hello AlphabetoPT 
can you please explane how can i update Extensions?
thanks

**Comment by moldcraft** [comment]
@aminkhm 

Open admin menu **Dashboard > Updates**, click on the **Check Again** button, then scroll down until the **Unyson Extensions** section and it will show if extensions are up-to-date or not.

**Comment by aminkhm** [comment]
@moldcraft
Thank you for your help, 
Maybe you can help me with something else, i try to change the language with poedit and it is not going, do you have time to do a teamviewer if you have done that before?
Thank you

**Comment by moldcraft** [comment]
@aminkhm Sorry, I am not experienced in translations and working with poedit.

**Comment by aminkhm** [comment]
@moldcraft
thank you so much for your help
