### ISSUE TITLE
Error: "Please register option-types on 'fw_option_types_init' action"

### ISSUE THREAD

**Issue by rafr3** [ThemeFuse/Unyson#1992]
Every time after install and activate Unyson plugin I see this message in Wordpress Dashboard. I installed it second time using completely fresh Wordpress instance with default templates and plugins. I installed Unyson, activated them and I downloaded all the extras from Unyson tab like "Page Builders" and etc.
What should I ido to remove this alert and be able to make changes without error messages?

**Comment by moldcraft** [comment]
Please enable a default WP theme and check if the error is still there. If not, then the cause is your theme.

Which theme are you using?

**Comment by rafr3** [comment]
You're right, the cause is theme called Everglades. Tested using TwentyFifteen and works without errorrs. Thx

**Comment by onebelarusianguy** [comment]
@moldcraft the same error(actually warning) on 2.6.2 version. it also appears on all default themes, so it's not about theme.

P.S. I've tried 2.6.2 before it was released but faced with this => returned to 2.6.1, because thought it will be fixed, but it also occurs in this release

**Comment by onebelarusianguy** [comment]
@moldcraft Solved. The problem was in not updated extension.

**Comment by royaltlife** [comment]
I have the same issue, started yesterday after updating Unyson's plugin.
Just updated everything now and still see the same warning message.
Any ideas?

**Comment by moldcraft** [comment]
@royaltlife Try to activate a default WP theme. If the error is gone then the problem is in theme, and you should report the problem to theme author.
