### ISSUE TITLE
Remove `is_admin()` when doing `add_action()` and `add_filter()`

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#1995]
It is quite [dangerous](https://github.com/ThemeFuse/Unyson/issues/263#ref-commit-a12ee0f) because the site can be accessed via cron or via API like Jetpack and in such cases `is_admin()` is `false` and some logic can be broken. Also it is useless because just calling `add_filter()` and `add_action()` is not resource consuming.

_I am thinking that this can be the cause of PageBuilder suddenly disabled for some pages._

**Comment by andreiglingeanu** [comment]
Hm, that's interesting. How we're supposed to handle those checks in that case?

**Comment by moldcraft** [comment]
I think you are talking about something else. Please give an example that looks confusing for you.

I mean this case

```php
if (is_admin()) {
    add_action('foo', ...);
} else {
    add_action('bar', ...);
}
```

If you are 100% sure that those actions are required to be used only like that, then ok. If you are not sure that `'foo'` action may be triggered when `!is_admin()` or vice versa, then better change to

```php
add_action('foo', ...);
add_action('bar', ...);
```

**Comment by thednp** [comment]
I never encountered sudden page builder blank pages and I use alot of `is_admin()`, but I guess that's server settings related, don't you think?

**Comment by moldcraft** [comment]
> I guess that's server settings related, don't you think?

I have no idea.

----

Today a user encountered a problem: one page had PageBuilder disabled (switched to default editor). All PageBuilder elements were there, I recovered the page: in default editor SelectAll>Delete, switch to PageBuilder, Update/save page.

Unfortunately (as always) in cPanel I couldn't find a good error log.
