### ISSUE TITLE
Unable to download breadcrumbs extension

### ISSUE THREAD

**Issue by nandlal-tjm** [ThemeFuse/Unyson#1996]
I can't download breadcrumbs extension. I got following error.

`Cannot move "E:/xampp/htdocs/themekarni/wp-content/plugins/unyson/tmp/Unyson-Breadcrumbs-Extension-1.0.12/static" to "E:/xampp/htdocs/themekarni/wp-content/plugins/unyson/framework/extensions/breadcrumbs/static".`

![breadcrumbs](https://cloud.githubusercontent.com/assets/5101781/18419498/dad1afc8-7875-11e6-8c12-babdf918edbe.png)

I installed latest version of unyson. I can not move files from temp folder to my plugin folder. I also delete other extensions and download again, are all works fine.

**Comment by moldcraft** [comment]
Can you send your admin and ftp details to `moldcraft[at]email.com`?

**Comment by nandlal-tjm** [comment]
I am on local host, I just sent you FTP details.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1602
