### ISSUE TITLE
Conclusion article announcement

### ISSUE THREAD

**Issue by GolyginSpace** [ThemeFuse/Unyson#1997]
Good evening. I bring the announcement of articles by the template <?php the_excerpt('new_excerpt_length', 30); ?>, But using page builder text is captured, how to solve this problem?

**Comment by pursuance** [comment]
With preg_replace which filter set?

**Comment by moldcraft** [comment]
[`the_excerpt()`](https://github.com/WordPress/WordPress/blob/109ffb9390efacf25d7a46c8aa78ed6d817d2e39/wp-includes/post-template.php#L351) doesn't accept any parameters, why you set 2 parameters and what they mean?

So you want get the_excerpt of a page made with PageBuilder. What do you expect to see, how WordPress should decide how to cut the html of the page?
