### ISSUE TITLE
Can't Activate plugin

### ISSUE THREAD

**Issue by cesasol** [ThemeFuse/Unyson#200]
Using lighttpd opensuse and MariaDB as server and I am unable to activate the plugin giving me this error: " Fatal error: Call to undefined function mb_strtoupper() in /home/cesasol/public_html/wordpress/wp-content/plugins/unyson/framework/helpers/general.php on line 1026"

**Comment by danyj** [comment]
You need to enable mb_strlen() in your PHP 
http://stackoverflow.com/a/6419126/594423

**Comment by llemurya** [comment]
@danyj  thanks for your answer.
