### ISSUE TITLE
Deprecated notice 2.6.3

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#2000]
Hi there,

After latest 2.6.3 version update, when debug is true, it shows these errors:

Deprecated: Non-static method FW_File_Cache::_reset_blog_id() should not be called statically in /home/test/public_html/wp-includes/plugin.php on line 524

Deprecated: Non-static method FW_File_Cache::_reset_blog_id() should not be called statically in /home/test/public_html/wp-includes/plugin.php on line 524

Deprecated: Non-static method FW_File_Cache::_reset_blog_id() should not be called statically in /home/test/public_html/wp-includes/plugin.php on line 524

_(in total more that 40 lines of this and appears in all pages)_

**Comment by moldcraft** [comment]
Please [test](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/274)
