### ISSUE TITLE
Map shortcode:: ReferenceError: google is not defined

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#2001]
I have used map shortcode api but its not working.
https://puu.sh/r8wea/b64873becb.png

```
ReferenceError: google is not defined
 /wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/map/static/js/scripts.js?ver=2.6.3:18
```

**Comment by moldcraft** [comment]
You load Google Maps API script from a wrong url

![](https://static.md/c9b9904302b96a45b231ac610a29420e.png)

It must be [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/414de6c22339b0a37edda83cea45a6abb5e95b75/shortcodes/map/static.php#L22)

**Comment by xperter** [comment]
Found the issue.  Buyer using this plugin 	
`Root Relative URLs`

Thanks
