### ISSUE TITLE
The ID of 'wp-editor' field cannot contain dashes

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#2002]
If there is a dash in the ID of a `wp-editor` field, the content is lost on page publishing/updating.

``` php
'left-content' => array(
    'type'   => 'wp-editor',
    'label'  => esc_html__( 'Left Column Content', 'domain' ),
),
```

It works when it's renamed to `'left_content'`.

**Comment by moldcraft** [comment]
The above array is used in shortcode options on first level? If yes, then it is correct, you can't use dashes in that case

**Comment by pe6o** [comment]
Ah, alright. Didn't know that.
