### ISSUE TITLE
[discussion] What is your server environment and how does Unyson perform?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2003]
Lately I have seen some huge performance lags from Unsyon version to version , just last 2.6.2 update added up to 1sec of load time. This made me retest all possible local/live host scenarios. So here are my tests 

Test 1
Apache 2.22
MySQL 5.1.36
PHP 5.4.17

--- Page load 2.20sec - 2.80sec

Test 2

Apache 2.4.18
MySQL 5.7.11
PHP  5.6.19

--- Page load 1.80sec - 2.20sec //  with opcache on  1.25sec - 1.30sec

Test 3

Apache 2.4.18
MySQL 5.7.11
PHP  7.0.4

--- Page load 1.20sec - 1.4sec //  with opcache on  600ms - 900ms

I know that WP req is php 5.6  or grater for both php and MySql https://github.com/ThemeFuse/Unyson/issues/new

but I was just wondering , what do you have and what is your average load time experience and or what your customers are experiencing .

**Comment by andreiglingeanu** [comment]
Huh, I've got almost ~8sec full page load, on my local setup, which has a dump server that is very slow. 

I've seen lots of improvements of the Unyson performace, and I can't agree with 
> I have seen some huge performance lags from Unsyon version to version , just last 2.6.2 update added up to 1sec of load time

I'm totally not experiencing it.

**Comment by moldcraft** [comment]
@danyj I remember your HDD was slow. [File Cache is reset and recreated if you are logged in as admin](https://github.com/ThemeFuse/Unyson/blob/486b3373309c8ce643c40ae009f82e228d226e41/framework/helpers/class-fw-file-cache.php#L198-L203), maybe that is the problem in your case.

Please open your site in Incognito and do a few refreshes.

**Comment by danyj** [comment]
@moldcraft , changed it before those tests , it is SSD now , and all tests above were in incognito tab , no cache no admin
