### ISSUE TITLE
Can't edit testimonials slider

### ISSUE THREAD

**Issue by royaltlife** [ThemeFuse/Unyson#2005]
Hello there,
I have a site in development, on Wordpress 4.61 platform, and Recover theme by wplab.
Unyson page builder came with the theme.

Mostly all working great, fantastic builder, except for the testimonials slider which I can't edit, though it is running predefined testimonials, due to an error:undefined.

All versions, top to bottom (i.e. Wordpress, theme, plugins, browser, etc.) are up to date.

I've read thru the forums, and though find some issues that seem alike, and tried some of the recommended solutions, couldn't find a working solution.

Thanks,
Roy

**Comment by moldcraft** [comment]
Hello,

Also note that Unyson [testimonials shortcode default options](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/414de6c22339b0a37edda83cea45a6abb5e95b75/shortcodes/testimonials/options.php) doesn't have anything related to slider, so most likely it's a theme problem.

Can you inspect server response with browser developer tools?

![](https://static.md/d70eb8dcba636c95d8189c2a7bfe0418.png)
