### ISSUE TITLE
Repeater Option

### ISSUE THREAD

**Issue by vladimir-boyko** [ThemeFuse/Unyson#2009]
Hello, tell me please, in this framework, there is an option similar to - Advance Custom Field - Repeater. If there is, what kind of an example of the output codes. Thank you in advance

**Comment by moldcraft** [comment]
Please show us a screenshot, we don't know about the Repetear option and how it works.

**Comment by vladimir-boyko** [comment]
moldcraft,
https://www.advancedcustomfields.com/resources/repeater/

**Comment by moldcraft** [comment]
We have similar option-types: `addable-popup` and `addable-box`.
