### ISSUE TITLE
Text Editor in pop-ups 

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#201]
Can we make the editor box a bit wider in the pop-us? something like this: http://joxi.ru/J2bXNdxT0VD8r6

**Comment by moldcraft** [comment]
@DimiBaitanciuc or maybe to make it horizontally resizable?

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson/commit/1d609a3f7b16535bfc655741f9db4ddd34b26d9e
