### ISSUE TITLE
How to change unopened popup option

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2010]
@moldcraft , @andreiglingeanu , Is there an easy way to change unopened popup option? 

I am working on color palette and need to affect this 
![screenshot_11](https://cloud.githubusercontent.com/assets/2340172/18506850/15bb99c4-7a6e-11e6-8df3-8d68283eee6e.jpg)

before the popup opens

**Comment by moldcraft** [comment]
```js
var data = JSON.parse($el.attr('data-for-js'));
data['whatever'] = 'hello';
$el.attr('data-for-js', JSON.stringify(data));
```
