### ISSUE TITLE
How did you connect color palette?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2011]
@moldcraft , @andreiglingeanu 

Can any of you explain the color palette process, 
I made color palette option with 5 colors and when color 1 is changed all options that use that color should be affected , but I cant figure out how to make php connection to them

like you explained here 
http://docs.themefuse.com/exposure/your-theme/styling-2/the-color-palette

example my color palette 

```
$palette = array(
	'color_1' => '#11111',
	'color_2' => '#405869',
	'color_3' => '#eeeeee',
	'color_4' => '#1b1b1b',
	'color_5' => '#cccccc'

);

```

than I use that array to setup default values for palette option type , and than 
in theme options for link color I set this up 

	'test_palette2' => array(
		'type' => 'thz-color-picker',
		'title' => __('Test palette', 'fw'),
		'box' => false,
		'value' => fw_get_db_settings_option('theme_palette/color_2', null),
	),

now I have defaults , but when I change the color 2 in the palette itself I need to reflect the change in front  (  for test_palette2  output)  also. Backend will be done via JS, but frontent  , is what is giving me trouble now.  

How did you set it up?

**Comment by danyj** [comment]
I mean , did you go trough your theme and for frontend did this 

    h1{color:'.fw_get_db_settings_option('theme_palette/color_2', null).'}


if yes , how is user going to use own color?

if no , are you affecting database directly when palette color is changed and how?

Im not asking for the option itself just need the process explained if you dont mind.

**Comment by andreiglingeanu** [comment]
> I mean , did you go trough your theme and for frontend did this
> h1{color:'.fw_get_db_settings_option('theme_palette/color_2', null).'}

Yes, we just did it in a bit more elegant manner. You're on the right track.

> if yes , how is user going to use own color?
Just create a color picker that will include a color palette and a custom color.

**Comment by danyj** [comment]
> Just create a color picker that will include a color palette and a custom color.

have that already , but im still baffled as to how in the core theme they managed to do this even for shortcodes to be affected by theme settings color change,|

so if I understand this something like , 

    if custom color is empty , use palette  color_2  else , use custom color , right?

**Comment by danyj** [comment]
@moldcraft , @andreiglingeanu   I need you help in this for a sec ,   I think I found better way without hard coding checks , idea is this 


option type pallete changes one of the 5 colors, on its color changes via js it changes all color option types to use the color key it changed to ,  like color_1, trough color_5

color picker _get_value_from_input  checks for that value and this is tested and works 



	protected function _get_value_from_input( $option, $input_value ) {
		
		$palette = fw_get_db_settings_option('theme_palette', null);

		if (is_null($input_value)) {
			
			return $option['value'];
			
			
		} else {

			if (strpos($input_value, 'color_') !== false) {
				if(isset($palette[$input_value])){
					$input_value = $palette[$input_value];
				}				
			}else{
				
				$input_value = trim($input_value);
						$input_value = (
							preg_match( '/^#[a-f0-9]{3}([a-f0-9]{3})?$/i', $input_value )
							||
							preg_match( '/^rgba\( *([01]?\d\d?|2[0-4]\d|25[0-5]) *\, *([01]?\d\d?|2[0-4]\d|25[0-5]) *\, *([01]?\d\d?|2[0-4]\d|25[0-5]) *\, *(1|0|0?.\d+) *\)$/', $input_value )
						) ? $input_value : $option['value'];				
				
			}
			
			return (string) $input_value;
		}
	}


this works fine on first change but if I change color picker again, I have to save twice since I am late on the 

    $palette = fw_get_db_settings_option('theme_palette', null);

can you please help out. 


P.S.  dont worry about validation now , I just want the frontend to work than il work on the rest. 

I am open to other suggestions , 

Thing I dont want to do is hardcode check like if palette color is picked use it , otherwise use custom color. With that I would need to recode all instances of colors which is madness. We already have palette and know what they are , the color picker  _get_value_from_input  should check for it and use it .

**Comment by danyj** [comment]
Or , maybe add a hidden option in color picker , but than I would be getting an array out instead of single value , just thinking out loud. I need something that would tell if color picker has choosen palette color or not.

**Comment by danyj** [comment]
almost there ,  this saving is killing me , the palette and color picker are saving at the same time so this works on second save only 

		if (is_array($option['value'])) {
			
			$palette = fw_get_db_settings_option('theme_palette', null);
			
			if ( is_array( $input_value ) ) {
				
				$value = $input_value;
	
			} else {
				
				$value = $option['value'];
			}
			
			
            if(isset($palette[$value['p']])){
                $value['c'] = $palette[$value['p']];
            } 			
			
			return $value;
		}

I now have color picker as an array 

		'value' => array(
			'c'=>fw_get_db_settings_option('theme_palette/color_2', null),
			'p'=> 'color_2'
		
		),

and second one is hidden input ,  so if it is set the color picker should use the palette color 2 instead own color ,   but like said using 

    fw_get_db_settings_option

inside 

    _get_value_from_input

is to late , is there any alternative?

**Comment by danyj** [comment]
darn man , works perfect in front , 

	function thz_process_color($value){
		
		if(!is_array($value)){
			return $value;
		}
		
		$palette = fw_get_db_settings_option('theme_palette', null);
		
		
		if(isset($palette[$value['p']])){
			$value  = $palette[$value['p']];
		}	
		
		return $value ;
	}
    $current = fw_get_db_settings_option('test_palette8', null);
    fw_print( thz_process_color ( $current ) );

**Comment by andreiglingeanu** [comment]
Have you found a solution for that, at the end?

**Comment by danyj** [comment]
@andreiglingeanu , kinda working on it still 

color picker faked ( removed name attr )
under faked picker  added input type hidden that gets the color picker value on change 

if color from palette is picked , hidden value gets   **color_1**  value , picker keeps the visual color
reference and get value from input is this one 

		protected function _get_value_from_input( $option, $input_value ) {
		
		
			if (is_null($input_value)) {
		
				return $option['value'];
		
		
			} else {
		
				if (strpos($input_value, 'color_') !== false) {
					
					$input_value = $input_value;
					
				}else{
		
					$input_value = trim($input_value);
							$input_value = (
								preg_match( '/^#[a-f0-9]{3}([a-f0-9]{3})?$/i', $input_value )
								||
								preg_match( '/^rgba\( *([01]?\d\d?|2[0-4]\d|25[0-5]) *\, *([01]?\d\d?|2[0-4]\d|25[0-5]) *\, *([01]?\d\d?|2[0-4]\d|25[0-5]) *\, *(1|0|0?.\d+) *\)$/', $input_value )
							) ? $input_value : $option['value'];                
		
				}
		
				return (string) $input_value;
			}
		}



in front colors will be processed with this function 



```
	$test_palette4 = fw_get_db_settings_option('test_palette5', null);			
	
	function thz_palette_color($value){
		
		if (strpos($value, 'color_') !== false) {
			
			$palette = thz_get_theme_option('theme_palette', null);
			
			if(isset($palette[$value])){
				$value = $palette[$value];
			}               
		}
		
		return $value ;
	}
	fw_print( $test_palette4 );

```

was not able to make it work via the array and it was to much , 
this way I get to keep string and than process it via the function 
some overrides are due to function introduction but is okis'

backedn js is what I am on now, frontend works

**Comment by danyj** [comment]
and like said usage of get_option in get value from input does not work , fires to late , 

if we could get that working than it would be much easier
