### ISSUE TITLE
Nested columns

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#2012]
Hi there,

I've seen a few posts for people requesting nested columns but you're not planning to incorporate this feature at all. Do you know of an alternative way I can use nested columns?

Thanks

**Comment by thednp** [comment]
You can create a new shortcode to do `row` and `column` stuff combined and use them in any `wp-editor` option type. Haven't tried it, but I believe it should work.

**Comment by klvmedia** [comment]
Awesome,  thanks for the tip :)

**Comment by andreiglingeanu** [comment]
> Haven't tried it, but I believe it should work.

You [can't](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/master/class-fw-extension-wp-shortcodes.php#L26).

**Comment by thednp** [comment]
Yes, I know it won't work because of using the same namespace, but of you create a shortcode with something like `nrow` and `ncolumn` as names it should be fine.

**Comment by Bogdan808** [comment]
Very sad that this is not possible. I have to invent different solutions for my layout. ((
