### ISSUE TITLE
Get “Style” and “Weight” Typography v2

### ISSUE THREAD

**Issue by elissonkario** [ThemeFuse/Unyson#2013]
Hello , thank you for your framework. It is really amazing. I am adding Option “Typography v2” in a Shortcode my thema . But I’m having trouble call options “style” and ” weight” . The other attributes are ok . However, these two attributes always return to “false” . Which way to implement these attributes in order to use them in view file?

```
array
(
    [google_font] => true
    [subset] => ‘latin’
    [variation] => ‘100italic’
    [family] => ‘Lato’
    [style] => false
    [weight] => false
    [size] => false
    [line-height] => ’35’
    [letter-spacing] => ‘0’
    [color] => ‘#000000’
)
```

**Comment by moldcraft** [comment]
Hello,

When it is Google font, you must use the `variation` parameter instead.

Thank you for the kind words. Cheers!
