### ISSUE TITLE
Warning: copy(): The first argument to copy() function cannot be a directory in

### ISSUE THREAD

**Issue by pohoglobal** [ThemeFuse/Unyson#2014]
Hi there. I am trying to install the unyson packages on localhost server and get the above error accompanied with "cannon move... towhich is preventing me from installing Mega Menu, Shortcodes and Demo Content. All other themes and plugins are working fine. 

![image](https://cloud.githubusercontent.com/assets/22207117/18534792/c977a82a-7b42-11e6-9b38-71dc2993a676.png)

![image](https://cloud.githubusercontent.com/assets/22207117/18534799/d7738f3e-7b42-11e6-86d3-28a0936d2e19.png)

**Comment by moldcraft** [comment]
On my side everything works fine

![staticshot_15-09-2016_14-41-36](https://cloud.githubusercontent.com/assets/1475489/18548643/867a8f32-7b52-11e6-91a6-de610b021fde.png)

I need to debug the code, but the problem is on your localhost so I can't access it via ftp. Can you give me TeamViewer access? `moldcraft[at]email.com`

**Comment by pohoglobal** [comment]
Done. Thanks

**Comment by moldcraft** [comment]
@pohoglobal I haven't seen you online on TeamViewer. How should I reach you to reproduce the problem?

**Comment by pohoglobal** [comment]
Hey, thanks for following up but Im sorted now. Ive switched to Mac
recently and there is no issue there at all.

**Comment by gillesgauthier** [comment]
I'm having the same issue using WAMP or XAMPP on Windows 10 Professional. Was anyone able to solve this problem?

**Comment by gillesgauthier** [comment]
I'm having the same issue using WAMP or XAMPP on Windows 10 Professional. Was anyone able to solve this problem?

**Comment by gillesgauthier** [comment]
Other than switching to mac, has anyone found a solution to this?

**Comment by johndavemanuel** [comment]
I am also having problem in this issuw on XAMMP windos 10? any help?
