### ISSUE TITLE
Bug with 'addable-popup' option after last update

### ISSUE THREAD

**Issue by RodalErmakov** [ThemeFuse/Unyson#2015]
Hi)
I have addable-popup option in my theme:
<img width="624" alt="2016-09-15 18 37 30" src="https://cloud.githubusercontent.com/assets/14311916/18551821/8b822ff0-7b73-11e6-9a52-e461ef307fbd.png">

Every time when I add  1 item (in page builder) it adds 2 items.
<img width="771" alt="2016-09-15 18 39 09" src="https://cloud.githubusercontent.com/assets/14311916/18551947/0796d366-7b74-11e6-8758-e15c1ecfe522.png">

It happens only in first time. I've checked several times and with different options in page builder including your options.

Thanks)

**Comment by andreiglingeanu** [comment]
Fixed https://github.com/ThemeFuse/Unyson/issues/1998#issuecomment-246348369
