### ISSUE TITLE
Multi-select in popup doesn't work after last update

### ISSUE THREAD

**Issue by RodalErmakov** [ThemeFuse/Unyson#2016]
Hi)
I have multi select option in popup
<img width="643" alt="2016-09-15 19 12 13" src="https://cloud.githubusercontent.com/assets/14311916/18553015/6468f2dc-7b78-11e6-8ed8-20039fbfacee.png">

After last update it doesn't work.
When I print the option:
<img width="712" alt="2016-09-15 19 13 57" src="https://cloud.githubusercontent.com/assets/14311916/18553101/aaf0e35e-7b78-11e6-86d1-57abc0c94cb6.png">

It gets null:
<img width="1147" alt="2016-09-15 19 15 01" src="https://cloud.githubusercontent.com/assets/14311916/18553122/bccd9040-7b78-11e6-819c-85bf16b7968a.png">

Multi-select outside popup is working fine.
Thanks)

**Comment by danyj** [comment]
test this 
https://github.com/ThemeFuse/Unyson/issues/1998#ref-commit-0fc0b2c

**Comment by mowshon** [comment]
Try to print this code:
```php
fw_print( fw_get_db_settings_option() );
```

After that, find your `footer_menu` in array hierarchy. Maybe you have some changes in your structure and `path` to `posts` is different.

**Comment by RodalErmakov** [comment]
<img width="442" alt="2016-09-15 19 55 35" src="https://cloud.githubusercontent.com/assets/14311916/18554696/77e21f40-7b7e-11e6-9b4d-8f9627c32b4d.png">
No, footer_menu array is empty.

**Comment by moldcraft** [comment]
@RodalErmakov Why in the above screenshot everything is uppercase?

----

On my side everything works fine:

* `.../settings.php`

```php
'test_option' => array(
	'type' => 'popup',
	'popup-size' => null,
	'size' => 'small',
	'popup-options' => array(
		'posts' => array(
			'type' => 'multi-select',
			'population' => 'posts',
			'source' => 'page',
			'prepopulate' => 100,
			'limit' => 1,
		),
	),
),
```

* `{theme}/header.php`

```php
<?php fw_print(fw_get_db_settings_option('test_option/posts')); ?>
```

![1477397768123](https://cloud.githubusercontent.com/assets/1475489/19685562/f9a9b888-9ac5-11e6-8e8f-ecc911467edd.jpg)
