### ISSUE TITLE
Element titles not correct in theme builder

### ISSUE THREAD

**Issue by nate-kobe** [ThemeFuse/Unyson#2018]
I have upgraded to wordpress 4.6.1 which created some problems with Unyson's theme builder. I then upgraded to Unyson 2.6.4 which solved some errors. Now the theme builder is working but the element box does not show the type of the element but just some code. (Please see screenshot)

I also get the following error on the top of the back-end : "Please register option-types on 'fw_option_types_init' action" but I think this has already been reported.

![bug-report-unyson](https://cloud.githubusercontent.com/assets/3728107/18576530/9c62047a-7be2-11e6-8c17-6ce60ebe724a.png)

**Comment by moldcraft** [comment]
Hello,

Make sure Unyson extensions are up-to-date by opening admin menu **Dashboard > Updates** and pressing the **Check Again** button, then scroll down to see if there are Unyson Extensions updates.
