### ISSUE TITLE
Can I use 'fw_ext_sidebars_conditional_tags' filter to add multiple tags?

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2020]
I'm trying to add all custom post type archives to the selectbox for sidebars. 

I found this filter: fw_ext_sidebars_conditional_tags (http://manual.unyson.io/en/latest/extension/sidebars/)

Can I use this filter to add multiple custom post types to the selectbox? I've tried several ways, but I only manage to add 1..

**Comment by moldcraft** [comment]
Show us your code please.

**Comment by noesteijver** [comment]
`function _filter_fw_ext_sidebars_add_conditional_tag($conditional_tags) {
    
    $conditional_tags['is_archive_page_slug'] = array(
        array(
	        'order_option' => 2,
	        'check_priority' => 'last',
	        'name' => __('Products archive', '{domain}'),
	        'conditional_tag' => array(
	            'callback' => 'is_post_type_archive',
	            'params' => array('products')
	        )
	    ),
	    array(
	        'order_option' => 2,
	        'check_priority' => 'last',
	        'name' => __('Services archive', '{domain}'),
	        'conditional_tag' => array(
	            'callback' => 'is_post_type_archive',
	            'params' => array('services')
	        )
	    ),
    );

    return $conditional_tags;

}
add_filter('fw_ext_sidebars_conditional_tags', '_filter_fw_ext_sidebars_add_conditional_tag' );`

**Comment by noesteijver** [comment]
This only saves the last (eg 'services' post type):

function _filter_fw_ext_sidebars_add_conditional_tag($conditional_tags) {
    
    $conditional_tags['is_archive_page_slug'] = array(
        'order_option' => 2,
        'check_priority' => 'last',
        'name' => __('Products archive', '{domain}'),
        'conditional_tag' => array(
            'callback' => 'is_post_type_archive',
            'params' => array('products')
        )
    );
    $conditional_tags['is_archive_page_slug'] = array(
        'order_option' => 2,
        'check_priority' => 'last',
        'name' => __('Services archive', '{domain}'),
        'conditional_tag' => array(
            'callback' => 'is_post_type_archive',
            'params' => array('services')
        )
    );

    return $conditional_tags;

}
add_filter('fw_ext_sidebars_conditional_tags', '_filter_fw_ext_sidebars_add_conditional_tag' );

**Comment by moldcraft** [comment]
Why you set the same array key two times?

```php
$conditional_tags['is_archive_page_slug'] = ...
$conditional_tags['is_archive_page_slug'] = ...
```

**Comment by noesteijver** [comment]
I didn't know that these should be unique. That solved it for me, thanks!
