### ISSUE TITLE
If Plugin Unyson framework is activate all site go down.

### ISSUE THREAD

**Issue by herbertcarlos1** [ThemeFuse/Unyson#2022]
the website was working fine but  this week went down I called the host and they found a problem with the plugin unyson framework and deactivate the plugin. the site working again but all the content on the page is gonne if I try to activate the site not working. Could somebody help me I will appreciate.

**Comment by moldcraft** [comment]
Hello,

Please connect via FTP and delete

```
wp-content/uploads/fw/file-cache.php
```

**Comment by herbertcarlos1** [comment]
Hi, moldcraft thanks for help me . after I deleted that cache.php, can activate the plugin?

**Comment by moldcraft** [comment]
Yes. I am not sure 100% that is the problem, but it is most likely to be it.

If it will not work, please check server's error.log and show us the error messages

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/74e13487e1ece9742af3ec85f0c7803f2a03b1bf

**Comment by herbertcarlos1** [comment]
I did still not working. ( i delete that file)
I have to disable because if enable the whole site stop working.
Please help.

**Comment by moldcraft** [comment]
@herbertcarlos1 Please add `return false;` in file-cache, like [here](https://github.com/ThemeFuse/Unyson/commit/74e13487e1ece9742af3ec85f0c7803f2a03b1bf)

https://github.com/ThemeFuse/Unyson/issues/2038#issuecomment-248899356
