### ISSUE TITLE
Extending a form item

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#2023]
Do you have any examples on extending a form item? I'm attempting to extend the text item, but I can't seem to get it working. I just want to add in an extra option. I have run through http://manual.unyson.io/en/latest/extension/forms/index.html#create-form-builder-item-type and am able to add an additional form item. But, when I try to extend an existing item I keep getting path errors (for external files), or "Fatal error: Builder item already processed (type: text)" or "unregistered item type" depending on what I'm trying.

This is all I have in my class file right now (until I get past these errors):

```

<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

class FW_Option_Type_Form_Builder_Item_Texticon extends FW_Option_Type_Form_Builder_Item_Text {
	
	public function get_type() {
		return 'texticon';
	}
	
}

FW_Option_Type_Builder::register_item_type( 'FW_Option_Type_Form_Builder_Item_Texticon' );
```

Here are some of the errors I see:
<img width="1161" alt="screen shot 2016-09-17 at 3 44 14 pm" src="https://cloud.githubusercontent.com/assets/1682207/18610872/a669256e-7ced-11e6-93bd-133eef6c0eb6.png">

Thanks for any and all help!

**Comment by moldcraft** [comment]
> extend the **text item**, but I can't seem to get it working. I just want to **add in an extra option**.

1. https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/457601d75cc68a9763e3e6ce2e005fe6a231fcf1/includes/option-types/form-builder/items/text/class-fw-option-type-form-builder-item-text.php#L188
2. https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/457601d75cc68a9763e3e6ce2e005fe6a231fcf1/includes/option-types/form-builder/extends/class-fw-option-type-form-builder-item.php#L69-L81

**Comment by meta4creations** [comment]
Sweet, thanks!
