### ISSUE TITLE
Icon V2 is not working in Customizer

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#2024]
I'm trying to add an icon-v2 option in the customizer but the selection popup shows up blank. It works fine in theme and post settings.

Thanks!

**Comment by andreiglingeanu** [comment]
64ad78efc3e5235a634669f296012609ddd7f331

**Comment by meta4creations** [comment]
Thanks! That does seem to resolve the issue. I am seeing another issues now, though. If I add the icon option to an addable popup, the icon popup shows up behind the addable popup.

<img width="1084" alt="screen shot 2016-09-27 at 10 32 54 am" src="https://cloud.githubusercontent.com/assets/1682207/18880557/e151bcce-849d-11e6-8904-b21499263723.png">

**Comment by andreiglingeanu** [comment]
@meta4creations Follow up here please https://github.com/ThemeFuse/Unyson/issues/1743.

**Comment by meta4creations** [comment]
Ok, thank you.
