### ISSUE TITLE
Color pickers resetting back to default values when value is empty

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2025]
The color pickers are resetting back to default value if empty value is saved. 

http://take.ms/QU8In

	'ddda' => array(
		'label' => __( 'RGBA Color Picker', 'unyson' ),
		'type'  => 'rgba-color-picker',
		'value' => '#ff6600',
		'desc'  => __( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
			'unyson' ),
		'help'  => sprintf( "%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
			__( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
				'unyson' ),
			__( 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
				'unyson' )
		),
	),

You are left with visual reference that the value is empty until you refresh the page. 
Users should be able to delete color value if they need to . Think of it this way, you set default blue color for button and user wants a button with no background.  With current pickers they will never be able to do so.

**Comment by moldcraft** [comment]
Please test

**Comment by danyj** [comment]
What about this one 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/class-fw-option-type-rgba-color-picker.php#L74

**Comment by danyj** [comment]
@moldcraft  tested color picker , works thnx!
rgba color picker needs same fix

**Comment by danyj** [comment]
Rgba color picker , frontend works , backend still shows default value on page refresh
http://take.ms/7vhQR

**Comment by danyj** [comment]
this needs fixing 
https://github.com/ThemeFuse/Unyson/blob/fa88a77bb52a63fd1a8c8bc3bc943d53a9865ec0/framework/includes/option-types/rgba-color-picker/class-fw-option-type-rgba-color-picker.php#L56

**Comment by danyj** [comment]
this works for that line 

    $option['attr']['value'] = is_null($data['value']) ? $option['value'] : $data['value'];
