### ISSUE TITLE
How can I show seo meta from my admin panel?

### ISSUE THREAD

**Issue by voxtermen** [ThemeFuse/Unyson#2026]
Hello!

In my wordpress post I have two fields for SEO (title and description). How can I get this fields for show on page? Like get_meta_desriprion.

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson-SEO-Extension/issues/5

**Comment by voxtermen** [comment]
Thank you! But I mean not title and description for site, I mean about current post seo meta title and description

**Comment by moldcraft** [comment]
[`fw_get_db_post_option($post_id, 'seo-titles-metas-title')`](https://github.com/ThemeFuse/Unyson-SEO-Extension/blob/296dbec52b25c070931be60a697952f1abde27b6/extensions/seo-titles-metas/class-fw-extension-seo-titles-metas.php#L581)
