### ISSUE TITLE
Redundant comment in /fw/file-cache.php

### ISSUE THREAD

**Issue by blackyangell** [ThemeFuse/Unyson#2029]
Hi. After updating to 2.6.5 I got the following error:

"Warning: Unterminated comment starting line 259 in ***/wp-content/uploads/fw/file-cache.php on line 259"

Thire is a comment there:
/* 

I delete it, but it appears again and again.

**Comment by moldcraft** [comment]
Strange, it doesn't appear on my side. We include that file with [`@` (suppress warnings)](https://github.com/ThemeFuse/Unyson/blob/f821fabed94cfd66eee16392b2b5cc9cce7e4ffa/framework/helpers/class-fw-file-cache.php#L136).

Can you send me your admin and ftp access to `moldcraft[at]email.com`?

**Comment by blackyangell** [comment]
I use php 5.6.26. Sorry, can't give access, it's vpn. 
Can I just remove this comment someway? It's not good to suppress any errors in my case, themeforest doesn't allow any php errors.

**Comment by moldcraft** [comment]
We will remove file-cache in the next update (this week)

**Comment by blackyangell** [comment]
Thank you!
