### ISSUE TITLE
Help to active editor shortcodes

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#203]
Hi,

Please guide me active editor shortcodes, I updated to the latest version of plugin but can not find the Unyson button at default editor of posts 

Thanks

**Comment by moldcraft** [comment]
Hello,
Try to reinstall the Page Builder extension.

*I think this is a bug, we will investigate in soon.*

**Comment by maiakhoa** [comment]
Hi @moldcraft 

Thanks so much, it's working after reinstalling Page Builder.

**Comment by maiakhoa** [comment]
One more question, is it integrated with wp-editor ? Like I want to add other shortcodes in text block shortcodes.

**Comment by moldcraft** [comment]
No, it's not integrated.

**Comment by maiakhoa** [comment]
Thanks @moldcraft

**Comment by moldcraft** [comment]
[v2.1.19](https://github.com/ThemeFuse/Unyson/releases/tag/v2.1.19) released

**Comment by AdelDima** [comment]
the problem is still on !!

**Comment by moldcraft** [comment]
@AdelDima Please give us more details and how to reproduce the problem.

**Comment by AdelDima** [comment]
It's work now after re install Page Builder , i use WordPress 4.1.1
