### ISSUE TITLE
Forms problem and fix proposal

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2033]
Hi guys!

Currently i'm faced one more problem: if i use more than one form on the same page (without AJAX), when i submit second form, i see form errors on the first form, not on second.
![2016-09-19_20-41-29](https://cloud.githubusercontent.com/assets/12991525/18642495/8704f71c-7ea9-11e6-94f9-d917ec9f8bd9.png)

Second one, i propose to replace this line [https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw-form-helpers.js#L55](url) from fw-form-helpers.js file to

`$input.parents('.form-builder-item').append(message);`

it helps to be sure than error message will be always at the end of the field. Current code is not working with custom (replaced via third-party JS libs) checkboxes / radios

![2016-09-19_20-47-02](https://cloud.githubusercontent.com/assets/12991525/18642690/530b2a98-7eaa-11e6-994e-044ad3f8d386.png)

![2016-09-19_20-49-56](https://cloud.githubusercontent.com/assets/12991525/18642765/acc5baa8-7eaa-11e6-906e-acd0b72dee74.png)

thank you for your attention :)

**Comment by moldcraft** [comment]
To test download Unyson and Forms extension latest dev version.

**Comment by moldcraft** [comment]
> Second one, i propose to replace this line from fw-form-helpers.js file to
>
> `$input.parents('.form-builder-item').append(message);`

I can't do that because `FW_Form` and `fw-form-helpers.js` are used not only for form builder forms but for any forms created with `FW_Form` where the `.form-builder-item` class doesn't exist.

You can overwrite the [`onErrors` method](https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw-form-helpers.js#L35).
