### ISSUE TITLE
Getting default option values

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2034]
Shouldn't this return default value if option is not saved?

    fw_get_db_settings_option('option_name',null)

on page reset or first time theme install i'm trying to get default values with that and it returns null

is this why it does not work anymore? 
https://github.com/ThemeFuse/Unyson/issues/1676

**Comment by moldcraft** [comment]
If you call that function in options file where the actual options are, [it will not work](https://github.com/ThemeFuse/Unyson/blob/66a3dc2cb3e3f363db208ce0399a0d0b81fc1550/framework/helpers/class-fw-db-options-model.php#L155)

**Comment by danyj** [comment]
I am not , I am calling it in framework/static.php and few files "outside"  theme options

**Comment by danyj** [comment]
@moldcraft  I get Allowed memory size   with this fix alone ( seeing one file change )  , what do I need to delete before applying  the fix?

tried wp-content\uploads\fw  but same thing

**Comment by moldcraft** [comment]
> tried wp-content\uploads\fw\file-cache.php but same thing

In latest dev file-cache is disabled.

> what do I need to delete before applying the fix?

Just download or `git pull` latest dev.

> I get Allowed memory size

Please give the full error message (in which file it happens).

**Comment by danyj** [comment]
unyson\framework\helpers\class-fw-cache.php on line 258


got this whole pack https://github.com/ThemeFuse/Unyson/releases/tag/v2.6.6

samte thing

**Comment by danyj** [comment]
php version 7.0.4

**Comment by danyj** [comment]
im out. back in 2h to test

**Comment by moldcraft** [comment]
On my side I don't have `Allowed memory size`. I will try to reproduce the problem tomorrow.

**Comment by danyj** [comment]
Check in theme settings page. That is where the bug appears. 

Best Regards
Dan Casky
Youjoomla Customer Service
+1727-388-6653
5044 17th street N
Saint Petersburg ,FL
33714
-------------------------------
Youjoomla LLC
www.youjoomla.com
Professional Joomla Web Design Services

**Comment by ivandotv** [comment]
This is a major bug.
There are so many regression issues lately.

**Comment by moldcraft** [comment]
@ivandotv [Have you tested your theme](https://github.com/ThemeFuse/Unyson-Extensions-Approval)?

**Comment by danyj** [comment]
im back

**Comment by danyj** [comment]
checked all fw_get_db_settings_option   used in theme/shortcode options , they all have either default value set or null  as default

**Comment by danyj** [comment]
and need to note , tested on php 5.6.19  ,   `Allowed memory size`  is only `64b`, in 7.0.4 is  `268435456 `  and in both versions opcache is on

**Comment by moldcraft** [comment]
I added

```php
fw_get_db_settings_option('test');
fw_get_db_settings_option();
```

at the beginning of `settings.php` and no errors. I can't reproduce.

**Comment by danyj** [comment]
line 258 is 

    throw new FW_Cache_Not_Found_Exception();

so what is the cache looking for?

**Comment by danyj** [comment]
http://prntscr.com/ckc44m

    fw_print($value);


here   https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/class-fw-cache.php#L257

**Comment by moldcraft** [comment]
@danyj Download Unyson latest dev and try to debug again (because your error in screenshot is not related to this issue) https://github.com/ThemeFuse/Unyson/commit/ef26cd32b1a315172a8a1e429646403e2e81477a

**Comment by danyj** [comment]
```
FW_Cache_Not_Found_Exception
(
    [*:message] => ''
    [Exception:string] => ''
    [*:code] => 0
    [*:file] => 'T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\class-fw-cache.php'
    [*:line] => 88
    [Exception:trace] => array
    (
        [0] => array
        (
            [file] => 'T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\class-fw-cache.php'
            [line] => 305
            [function] => '_init'
            [class] => 'FW_Cache'
            [type] => '::'
            [args] => array()
        )
        [1] => array
        (
            [file] => 'T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\bootstrap.php'
            [line] => 31
            [args] => array
            (
                [0] => 'T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\class-fw-cache.php'
            )
            [function] => 'require'
        )
        [2] => array
        (
            [file] => 'T:\wamp64\www\Development\WordPress\wp-includes\plugin.php'
            [line] => 524
            [function] => '_action_init_framework'
            [args] => array
            (
                [0] => ''
            )
        )
        [3] => array
        (
            [file] => 'T:\wamp64\www\Development\WordPress\wp-settings.php'
            [line] => 395
            [function] => 'do_action'
            [args] => array
            (
                [0] => 'after_setup_theme'
            )
        )
        [4] => array
        (
            [file] => 'T:\wamp64\www\Development\WordPress\wp-config.php'
            [line] => 101
            [args] => array
            (
                [0] => 'T:\wamp64\www\Development\WordPress\wp-settings.php'
            )
            [function] => 'require_once'
        )
        [5] => array
        (
            [file] => 'T:\wamp64\www\Development\WordPress\wp-load.php'
            [line] => 39
            [args] => array
            (
                [0] => 'T:\wamp64\www\Development\WordPress\wp-config.php'
            )
            [function] => 'require_once'
        )
        [6] => array
        (
            [file] => 'T:\wamp64\www\Development\WordPress\wp-blog-header.php'
            [line] => 13
            [args] => array
            (
                [0] => 'T:\wamp64\www\Development\WordPress\wp-load.php'
            )
            [function] => 'require_once'
        )
        [7] => array
        (
            [file] => 'T:\wamp64\www\Development\WordPress\index.php'
            [line] => 17
            [args] => array
            (
                [0] => 'T:\wamp64\www\Development\WordPress\wp-blog-header.php'
            )
            [function] => 'require'
        )
    )
    [Exception:previous] => null
)
```

**Comment by moldcraft** [comment]
Please `fw_print($keys);`

**Comment by danyj** [comment]
http://prntscr.com/ckcja5

**Comment by danyj** [comment]
found it but is strange and makes no sense plus everything worked on all versions before today 


```
function thz_get_option($id,$default = null){
	
    return fw_get_db_settings_option($id,$default);

}
```

causes error , this lets it go trough 



```
function thz_get_option($id,$default = null){

		return $default;
		// default theme option
		return fw_get_db_settings_option($id,$default);


}
```

**Comment by danyj** [comment]
well what ever it is is not good. up to this version everything works without any issues , and I dont see why the function above should cause trouble. What ever you have done here https://github.com/ThemeFuse/Unyson/commit/7be2d928360bc5b8b64ffb5ccfc6f7c221330aef

is messing everything up

**Comment by moldcraft** [comment]
I need to reproduce the problem with a default theme

**Comment by danyj** [comment]
I am sorry but I dont know what it is that you are saying exactly. What does this mean ?
>I need to reproduce the problem with a default theme 

does it mean the bug I see and report wont get looked further unless you see it on your local and if I have the issue makes no difference. 

Me spending hours testing , reporting and being so far the only one who is testing latest build does not matter? 

I advised that this 
```
function thz_get_option($id,$default = null){

    return fw_get_db_settings_option($id,$default);

}

```
   is where the error happens , 

and like you see it makes no sense. I have been using that function since almost 2 years now and now that I reported that  null value does not work since whatever was changed in previous versions and you :fixed" that I should not use my function anymore. 

Yes , i am loosing it a bit.

**Comment by danyj** [comment]
here is the bug , 

I have custom option type that resembles the form option type 

add big JSON  here as default value 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/8a344bcfd8ac48bdbd3384e95c9a389af550347b/extensions/contact-forms/shortcodes/contact-form/options.php#L21

and you will get an error 

http://prntscr.com/ckea91

if I remove it the bug is gone. 

that worked on all previous versions

I even tried json_encode  http://prntscr.com/ckee7m same thing 


another strange thing is that this data is already saved in DB and I am getting the option like this 

    fw_get_db_settings_option('footer_section',array())

so no null

**Comment by danyj** [comment]
I dug deeper and this is where the issue starts 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/checkboxes/class-fw-option-type-form-builder-item-checkboxes.php#L76

I have this 

	private function get_options() {
		
		$options = fw_get_variables_from_file(dirname ( __FILE__ ).'/thz_builder_section_options.php', array('options' => array()));
		
		return array(
				$options['options']
		);

	}

in thz_builder_section_options.php


I have 2 instances of fw_get_db_settings_option with default value set


		'padding' => array(
			'top' => '0',
			'right' => fw_get_db_settings_option('columns_spacing',0),
			'bottom' => '0',
			'left' => fw_get_db_settings_option('columns_spacing',0)
		)


again , none of those caused issue before and this option is in use since Unyson 2.2 which is a year back. 
the issue is not visible if default value is empty.

**Comment by danyj** [comment]
if these are removed 

    fw_get_db_settings_option('columns_spacing',0)

recursion does not happen, but makes no sense as to why when default is set

i tested different default value same thing

**Comment by danyj** [comment]
and here is the loop that uses the option 
https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/checkboxes/class-fw-option-type-form-builder-item-checkboxes.php#L173

so recursion starts there

by uncommenting that loop recursion stops , default value can be used , all items have their options,

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/af17f15eb24bfe32c8f59e7d22ba0cea07a19f26

Try now

**Comment by danyj** [comment]
@moldcraft  now it works.  can you explain the fix ? am I doing something wrong ?

**Comment by moldcraft** [comment]
It was

1. Get values from db and cache
2. Get options array and cache
3. Process options and values (fw-storage)
4. Call `$option_type->storage_load(...)` Here somehow `fw_get_db_settings_option()` is called again and it produces a recursion
5. Cache step 3.

The fix: Switch step 5. and step 4. so first the cache is set and will not allow recursive execution

**Comment by danyj** [comment]
thnx. sorry for the blurb , I was tired and couldn't find the issue on my end.
