### ISSUE TITLE
How to create custom theme settings page?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2035]
@andreiglingeanu  couple days ago you posted a sample of a tab that loads custom settings pages. Basically separating tab from theme settings page

I found this https://github.com/ThemeFuse/Unyson/issues/250

but I need custom theme settings page.  Can you please remind me . Thnx!

**Comment by danyj** [comment]
Found it https://github.com/ThemeFuse/Unyson/issues/1491#issuecomment-242065823

**Comment by danyj** [comment]
Does anyone know how to make the actual replica of settings page with side tabs ? 
The samples above make this kind of demo settings

![screenshot_16](https://cloud.githubusercontent.com/assets/2340172/18798309/2c2ae6ae-81d2-11e6-9437-59fd383c37d6.jpg)


but I rather have this 

![screenshot_17](https://cloud.githubusercontent.com/assets/2340172/18798340/5c060cc8-81d2-11e6-87d3-b869b339d5d0.jpg)

**Comment by moldcraft** [comment]
Side tabs is hardcoded for Theme Settings

Ctrl+F `side` https://github.com/ThemeFuse/Unyson/blob/master/framework/views/backend-settings-form.php

**Comment by danyj** [comment]
@andreiglingeanu   

>  I gave up the idea of making Theme Settings a monster and I moved some of my options onto other page

OK , but were you able to preserve the sidetabs or do you have tabs above 

if you still have the sidetabs how did you override the form default view?

**Comment by andreiglingeanu** [comment]
> preserve the sidetabs

I did. Just copy some CSS classes around and you're done.

**Comment by danyj** [comment]
cmon bud show example ,   

I have 10 side tabs , 

could keep 3  on one page and move others to other pages

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/2112#issuecomment-255769799
