### ISSUE TITLE
fw.FW_URI is not defined

### ISSUE THREAD

**Issue by vladimir-boyko** [ThemeFuse/Unyson#2036]
I'm trying to add the path to the folder in the shortcode js file but records the variable does not work?
How do I do this, use the wp_localize_script or have a correct method?

Why fw is not defined
`var uri = fw.FW_URI+'/extensions/shortcodes/shortcodes/portfolio';`

**Comment by moldcraft** [comment]
Because you call it earlier than `fw.FW_URI` is defined. Add `fw` as a requirement in your script `wp_enqueue_script()`
