### ISSUE TITLE
Why  do we need options pages when admin is not logged in? 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2037]
@andreiglingeanu  @moldcraft   Thnx to small php warning I was able to see this. Why are we loading theme options pages in frontend when admin  is not logged in? 

I tought  we are getting the theme options from the DB ? 

![screenshot_14](https://cloud.githubusercontent.com/assets/2340172/18658916/12dd0fe2-7f07-11e6-8acb-60442b409803.jpg)

**Comment by ivandotv** [comment]
As I understand options are always loaded, because the framework uses them to return 'default' values.
That's why all options are always loaded. both frontend and backend.

**Comment by danyj** [comment]
@ivandotv sure that makes sense when DB settings are empty, but if settings are there I dont see a reason.

**Comment by moldcraft** [comment]
Because we need to find and [process `fw-storage` parameter in all options](https://github.com/ThemeFuse/Unyson/blob/66a3dc2cb3e3f363db208ce0399a0d0b81fc1550/framework/helpers/class-fw-db-options-model.php#L152-L178).
