### ISSUE TITLE
Site down when activating Unyson plugin

### ISSUE THREAD

**Issue by karla-kincamp** [ThemeFuse/Unyson#2038]
Until the last update (4 days ago), my website was working fine. Whenever I activate the plugin, the white screen of death appears :(

I had to deactivate the plugin so the site can work again, but Im using flypage theme, so I necessarily need the plugin.

I've tried connecting via FTP and deleting `wp-content/uploads/fw/file-cache.php` as was suggested in [this Issue](https://github.com/ThemeFuse/Unyson/issues/2022), but it doesn't work. I've also tried to check server's error.log and debugging but it doesn't show anything. 

Any help is welcome!

**Comment by moldcraft** [comment]
Hello,

WP_DEBUG is active?

**Comment by karla-kincamp** [comment]
Yes

**Comment by studio500** [comment]
Exact same problem, white screen nothing else.

**Comment by moldcraft** [comment]
Please send me your admin and ftp credentials to `moldcraft[at]email.com` and I will inspect it.

**Comment by karla-kincamp** [comment]
Thanks! I've just send them to you :)

**Comment by moldcraft** [comment]
The problem was in file-cache. In next version it will be [disabled](https://github.com/ThemeFuse/Unyson/commit/74e13487e1ece9742af3ec85f0c7803f2a03b1bf).

https://github.com/ThemeFuse/Unyson/issues/2029
