### ISSUE TITLE
Issue in contact-form

### ISSUE THREAD

**Issue by khangdoan03121993** [ThemeFuse/Unyson#2039]
How can I change the style of email from contact-form? Please help me, thanks!
![capture_03](https://cloud.githubusercontent.com/assets/15787361/18697688/cb84f24e-7fed-11e6-809b-d10671c74245.jpg)

**Comment by WPJobs** [comment]
Hi!

You can override following template `/wp-content/plugins/unyson/framework/extensions/forms/extensions/contact-forms/views/email.php`

see lines #38 and #46, just remove the <pre> tag

**Comment by khangdoan03121993** [comment]
Hi!

I check email.php file. This is form of contact-form. I want to style content of email. Thanks!

**Comment by duongancol** [comment]
@khangdoan03121993 check this link http://manual.unyson.io/en/latest/extension/forms/index.html pls
