### ISSUE TITLE
multi-picker select error

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#204]
Looks like multi picket select is not letting me use numeric values
only textual 
I used this option 
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/theme/options/demo-2.php#L893-L940

and changed the 
 'phone' to 1 or '1' 
'laptop' to 2   or '2'

This is what I get 

error
http://screencast.com/t/F48Te77x

code
http://screencast.com/t/YUs3OTTCoqHG

**Comment by moldcraft** [comment]
The fix will be available in the next framework version.

For now, to be able to continue developing, you can replaced [this file](https://github.com/ThemeFuse/Unyson/blob/4139d7ee85de7deeb75d260fe07f11b785d3494a/framework/helpers/general.php) manually.

**Comment by danyj** [comment]
Perfect. Thnx for the fix!

**Comment by moldcraft** [comment]
[v2.1.19](https://github.com/ThemeFuse/Unyson/releases/tag/v2.1.19) released
