### ISSUE TITLE
Buttons ID's in Pricing Tables are duplicated

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2040]
I have just noticed that if i add several Pricing Tables on the same page (copied one table to another in Page Builder and then changed table content, and buttons titles), some buttons have the same ID's, hovewer, my Button shortcode contains

`'id' => array( 'type' => 'unique' ),`

it has become clear in the last Unyson update. is there a way to be sure than all buttons has unique ID's? 

![2016-09-21_11-02-51](https://cloud.githubusercontent.com/assets/12991525/18702598/163c54b0-7feb-11e6-8a0b-04d69a1b97a8.png)
![2016-09-21_11-03-24](https://cloud.githubusercontent.com/assets/12991525/18702597/162ffac6-7feb-11e6-9cb3-be330a7af377.png)

**Comment by moldcraft** [comment]
[This](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/fc19d07193b2124dda427385a7547dfdbc46aab5/shortcodes/table/includes/fw-option-type-table/class-fw-option-type-table.php#L100-L132) should have fixed this problem. Maybe you have [overwritten the table option type](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/fc19d07193b2124dda427385a7547dfdbc46aab5/shortcodes/table/class-fw-shortcode-table.php#L15-L21) in your theme and it doesn't contain the fix?

**Comment by WPJobs** [comment]
Thank you so much, Moldcraft!

**Comment by WPJobs** [comment]
Hi, again @moldcraft 

The same problem if i use Unyson Shortcodes -> Button element in textarea
![2016-09-22_17-00-44](https://cloud.githubusercontent.com/assets/12991525/18751035/2b2c356a-80e6-11e6-9da5-d2848f81a35a.png)

once i duplicate row with shortcode that uses Button in textarea, button ID duplicates too

**Comment by WPJobs** [comment]
Any update on this? Thank you
