### ISSUE TITLE
Failed to load resource with Feedback extension

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#2041]
Our client site could not load the javascript file of Feedback extension. So the feedback function doesn't load. I think that It could be the problem with https server. 
Can you take a look [here](http://take.ms/CwTPn)?

**Comment by moldcraft** [comment]
[There](https://github.com/ThemeFuse/Unyson-Feedback-Extension/tree/a6d0fb55780b8968842fc2c475b8fe37abf30d44/extensions) is no [`rssback-stars` extension](https://cloud.githubusercontent.com/assets/1475489/18709021/8a99b454-8006-11e6-9b06-57d111da78e6.png)

**Comment by moldcraft** [comment]
I did a search in all Unyson files and there is no matching for the word `rssback`, so most probably it is a theme issue.

**Comment by duongancol** [comment]
No, it's in Unyson plugin. Please check the link [here](https://www.klugscheissen.com/course/how-to-become-a-good-founder-7/) for more detail

**Comment by duongancol** [comment]
so where call this file? It's so weird.

**Comment by moldcraft** [comment]
I can't see that page, it requires me to log in.

**Comment by duongancol** [comment]
I sent you an email

**Comment by moldcraft** [comment]
There is a plugin that does `preg_replace()` in page html. I tested this code

```
add_action('wp_head', function(){
	fw_print(
		fw_ext('feedback')->get_uri(),
		json_encode(fw_ext('feedback')->get_uri())
	);
});
```

and it shows

![staticshot_21-09-2016_18-26-08](https://cloud.githubusercontent.com/assets/1475489/18717529/e0f52ac8-8028-11e6-9a52-e7be7f368159.png)

**Comment by duongancol** [comment]
will try to deactivate all current plugin to find this plugin, thanks for your time!
