### ISSUE TITLE
Shortcode button problem in WordPress editor

### ISSUE THREAD

**Issue by acidcrash2005** [ThemeFuse/Unyson#2042]
Hello,
When I use shortcode button in WordPress editor it does not work, In console, I have error http://joxi.ru/zANe5MyC0dbE29

load-scripts.php:371 Uncaught SyntaxError: Invalid regular expression: /\[(\[?)(row_\)(?![\w-])([^\]\/]*(?:\/(?!\])[^\]\/]*)*?)(?:(\/)\]|\](?:([^\[]*(?:\[(?!\/\2\])[^\[]*)*)(\[\/\2\]))?)(\]?)/: Unterminated group

Please help!

**Comment by moldcraft** [comment]
Hi,
Please disable all plugins except Unyson and check if the error persists.

**Comment by acidcrash2005** [comment]
No changes. Error remained. When I turn on WordPress Shortcodes this error is are. Even if I disabled all plugins

**Comment by acidcrash2005** [comment]
This error came when I update unison

**Comment by moldcraft** [comment]
![staticshot_21-09-2016_17-03-13](https://cloud.githubusercontent.com/assets/1475489/18714077/4c8ea824-801d-11e6-9fd5-039fc238796a.png)

**Comment by acidcrash2005** [comment]
Done - http://joxi.ru/vAWlYW4CL5nWrW

**Comment by moldcraft** [comment]
I did a search in all Unyson files and there is no `refreshEachUnysonPanel` function

![staticshot_21-09-2016_17-29-31](https://cloud.githubusercontent.com/assets/1475489/18715180/060faa3e-8021-11e6-9b5f-21513f71c64f.png)

1. Please reinstall the WordPress Shortcodes extension
2. Which theme are you using?

**Comment by moldcraft** [comment]
If found that function in an older WordPress Shortcodes version https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/v1.0.1/static/js/plugin.js#L13

Please update Unyson extensions or reinstall the WordPress Shortcodes extension and clear browser cache.

**Comment by acidcrash2005** [comment]
So strange, when I reinstall WordPress Shortcodes extension it is load older version of extension.

**Comment by moldcraft** [comment]
Which version?

**Comment by acidcrash2005** [comment]
The Unyson version is 2.6.5, the Shortcodes extension is 1.0.3 but in file plugin.js I have refreshEachUnysonPanel function http://joxi.ru/eAOe4ElCl8MBmo yeat.

**Comment by moldcraft** [comment]
Oh, sorry, [it was removed](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/commit/d4c5812fa74866500f1d10d8d3648bbca361347a) in latest dev version which is not released yet.

Please test it and I will create a release on Friday:

1. Uninstall WordPress Shortcodes extension
2. [Download](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/archive/master.zip) latest dev
3. Extract latest dev in `unyson/framework/extensions/shortcodes/extensions/wp-shortcodes`

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/277

**Comment by acidcrash2005** [comment]
So strange, I updated the WordPress Shortcodes extension but nothing was change. Now error in refreshEachEditor function. http://joxi.ru/a2XWelxUWY6jmg

**Comment by moldcraft** [comment]
Can you send admin and ftp details to `andrei.glingeanu@gmail.com` ?

**Comment by acidcrash2005** [comment]
Sended. Отправил.

**Comment by moldcraft** [comment]
@acidcrash2005 Please test the latest dev again

1. Uninstall WordPress Shortcodes extension
2. [Download](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/archive/master.zip) latest dev
3. Extract latest dev in `unyson/framework/extensions/shortcodes/extensions/wp-shortcodes`

**Comment by acidcrash2005** [comment]
Nothing changes - http://joxi.ru/EA4Kpd9I6p852b.
I did all this:

1. Uninstall WordPress Shortcodes extension
2. Download latest dev
3. Extract latest dev in unyson/framework/extensions/shortcodes/extensions/wp-shortcodes
4. Clear browser cache

**Comment by andreiglingeanu** [comment]
Hi @acidcrash2005. Sorry for taking it so long to get over this.

Can you please do this:

1. Confirm that you are testing with latest master on WP Shortcodes extension
2. If so, send me one more email with your ftp _and_ wordpress admin access on `andrei.glingeanu@gmail.com`. Also send me links to the **pages** that are broken, both on admin and frontend side.

**Comment by acidcrash2005** [comment]
Hi, Andrei. I use 'version' => '1.0.4', of WP Shortcodes extension. The problem wasn't resolved. Please help me, my client, very angry for that. I'm in a panic, what wrong?
The access sent on andrei.glingeanu@gmail.com. 
Thank you very march!

**Comment by andreiglingeanu** [comment]
@acidcrash2005 

1. First, I can't login into your ftp account to check your code
2. at second, it looks like you've got a shortcode named [`row_\`](https://cloud.githubusercontent.com/assets/2979628/19036703/3578d040-897a-11e6-9362-fdca8ff45180.png) that brokes the `new Regexp(string)` syntax.

```javascript
new RegExp("\\[(\\[?)("+a+")(?![\\w-])([^\\]\\/]*(?:\\/(?!\\])[^\\]\\/]*)*?)(?:(\\/)\\]|\\](?:([^\\[]*(?:\\[(?!\\/\\2\\])[^\\[]*)*)(\\[\\/\\2\\]))?)(\\]?)","g")
```

<hr>

You somehow managed to get a shortcode named `row_\`. We don't support having shortcodes named that way. Please contact your theme author or the dev that is responsible for that in order to get rid of this shortcode.

**Comment by acidcrash2005** [comment]
OMG!!! Thanks, thanks, thanks!!! I found this folder and deleted it, and all working well now! You are the Best! 

Sorry for disturb!
