### ISSUE TITLE
Why are we saving html option types?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2043]
Can you please advise why are we saving html option type html? 
It is just an html output and it should not be in DB. We can simply remove name attribute from the option type and it wont save it.

**Comment by moldcraft** [comment]
Maybe some developers already have created custom options based on that input.
For example [here](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/bcd08d2765b96edec47e523a32542c3f87b734b0/includes/option-type-mailer/class-fw-option-type-mailer.php#L111-L127) I used option-type html but haven't used that input, but maybe other developers are using it.

**Comment by danyj** [comment]
true, cant do it now ,  will make my own but saving that one kinda makes no sense
