### ISSUE TITLE
Restore Failed

### ISSUE THREAD

**Issue by spfskyline** [ThemeFuse/Unyson#2044]
I am having an issue restoring from a full backup I get the error:
Database restore: Failed to decode line 1605 from db file. Syntax error, malformed JSON

Any way to salvage the backup?

[Screenshot](https://www.dropbox.com/s/b4vyhh1hyrovavq/Screen%20Shot%202016-09-20%20at%203.00.48%20PM.png?dl=0)

**Comment by moldcraft** [comment]
You can open FTP, copy the zip, open it and remove that line from `database.json.txt`.

Or send me your admin and ftp details to `moldcraft[at]email.com` and I will inspect the problem.

**Comment by spfskyline** [comment]
Thanks! Site is local right now but I could send you the Json directly to look at. Line 1605 is blank along with the following approx 3000 lines. Not sure what to make of that.

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.0.74&pv=10.0.1&source=email_footer_2]
On Thu, Sep 22, 2016 at 8:01 AM, moldcraft <notifications@github.com> wrote:
You can open FTP, copy the zip, open it and remove that line from database.json.txt .

Or send me your admin and ftp details to moldcraft[at]email.com and I will inspect the problem.

**Comment by moldcraft** [comment]
If the lines are blank then the problem is in backup, not in restore. But I need to inspect the code somehow, on our side everything works fine.

**Comment by spfskyline** [comment]
I can send you the database.json.txt if you want? or do you need access to
the local site as well?

**Comment by spfskyline** [comment]
would teamviewer access help?

**Comment by moldcraft** [comment]
Yes. Send the details to `moldcraft[at]email.com`

**Comment by moldcraft** [comment]
I am off for today. Better send the details tomorrow.

**Comment by moldcraft** [comment]
Or inspect the problem by yourself. [Here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/3df146519af25b5784a0c85395c66c9957f81e2a/includes/module/tasks/type/class-fw-ext-backups-task-type-db-export.php) is the code, search for `fwrite(`.

P.S. Maybe you don't have the `php-json` extension installed? Try this code:

```php
var_dump(json_encode(array('hello' => 'world')));
```

**Comment by spfskyline** [comment]
You are over my head on the code. I will talk tomorrow and maybe you can take a look.
Thanks for the help.
