### ISSUE TITLE
Is there a file path/uri probing function?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2045]
I am not sure but I thought that we have a file path/uri probing function that we can use for theme CSS/JS files like we have for extensions/shortcodes ` locate_URI`. 

Need something like that for child-themes

**Comment by andreiglingeanu** [comment]
https://github.com/ThemeFuse/Unyson/blob/v2.6.6/framework/core/extends/class-fw-extension.php#L178-L202

http://manual.unyson.io/en/latest/helpers/php.html#fw-locate-theme-path-uri
https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/general.php#L485-L531

**Comment by danyj** [comment]
hm , what if Unyson is disabled? We cant use FW_File_Cache than, 

TF requires themes to work without Unyson 
they dont allow TGMPA force_activation  so all those will not work and will trow error on theme install 

I made this while waiting for answer and to be honest dont see much of a difference between cache and no cache . What do you think ?


	function thz_theme_file_uri( $file_name ){
		
		if(is_child_theme()){
			
			$file_in_child_dir = get_stylesheet_directory() . $file_name;
			
			if( is_file( $file_in_child_dir ) ){
				
				return get_stylesheet_directory_uri() . $file_name;
				
			}else{
				
				return  get_template_directory_uri() . $file_name;
			}	
				
		}else{
			
			return  get_template_directory_uri() . $file_name;
			
		}
	
	}


@andreiglingeanu  welcome back :)

**Comment by andreiglingeanu** [comment]
> to be honest dont see much of a difference between cache and no cache

That's really the only difference. You are welcome to use your own function, for the cases when Unyson is not around.

**Comment by danyj** [comment]
> you are welcome to use your own function

true , small mod to my function and use fw if enabled . thnx!
