### ISSUE TITLE
How to dequeue frontend-grid.css file?

### ISSUE THREAD

**Issue by ttn10** [ThemeFuse/Unyson#2046]
Hi, 
I gross entire all css file of unyson into style.css file, i used:
`function dequeue_css() {
	wp_dequeue_style('fw-font-awesome');
	wp_dequeue_style('fw-ext-builder-frontend-grid');
	wp_dequeue_style('fw-ext-forms-default-styles');
	wp_deregister_style('fw-font-awesome');
}
add_action('wp_enqueue_scripts','dequeue', 100);`

but this code not working with `wp_dequeue_style('fw-ext-builder-frontend-grid');`
in frontend:
`<link
rel='stylesheet' id='fw-ext-builder-frontend-grid-css'  `
How i can do it?
https://varvy.com/pagespeed/images/combine-css-small-c.png

**Comment by danyj** [comment]
read the docs please
http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid

**Comment by andreiglingeanu** [comment]
We're okay to close, no?

**Comment by ttn10** [comment]
Yes, it working with `wp_deregister_style('fw-ext-builder-frontend-grid')` not `wp_dequeue_style('fw-ext-builder-frontend-grid');`
Thanks for support
