### ISSUE TITLE
Backend: enqueue_options_static optimization.

### ISSUE THREAD

**Issue by mowshon** [ThemeFuse/Unyson#2047]
I have a proposal on backend optimization. Some days ago, I test the Unyson productivity with xdebug profiler.

So, this is what I got.
![Initial](https://i.gyazo.com/5957d37e56d75dbbf55cdc50037723eb.png)
_( Image: 1 )_

**File:** unyson/framework/core/components/backend.php [line: 1534]
**Method:** enqueue_options_static()

This method get `type` from options-array and depends on this `type` he execute `enqueue_static()` for container or option types.

We can see in `Image 1` that all this stuff a very expensive in time and calls.

------------------------
I try to fix this with simple regular expresion that search in JSON all types and execute his `enqueue` method.

The result:
![Final](https://i.gyazo.com/421f9be245c060df77466b13b647825e.png)
**1551** less calls and save ~1 sec for Unyson execution.
------------------------
You can try my fork: https://github.com/mowshon/Unyson
My fix: https://github.com/mowshon/Unyson/blob/master/framework/core/components/backend.php#L1565-L1580

**Comment by danyj** [comment]
@mowshon  kiss your brain bud :)

**Comment by moldcraft** [comment]
1. Please add [here](https://github.com/mowshon/Unyson/blob/master/framework/core/components/backend.php#L1573)

    ```php
    } elseif (array_key_exists($type, $this->option_types )) {
    ```

    To prevent 'Undefined option-type' warning in case it will find an ordinary parameter `"type"` not related to option types (inside some option parameters).

2. We have `popup` [option-type](https://github.com/ThemeFuse/Unyson/tree/8272b75bf54fbc5ba30061c5dd878290b3b8d6d6/framework/includes/option-types/popup) and [container-type](https://github.com/ThemeFuse/Unyson/tree/8272b75bf54fbc5ba30061c5dd878290b3b8d6d6/framework/includes/container-types/popup), the above code will enqueue only container-type.

3. Wouldn't be [faster](http://stackoverflow.com/a/13483548/1794248) to store the already enqueued types as array key instead of [array value](https://github.com/mowshon/Unyson/blob/master/framework/core/components/backend.php#L1577) which does a [linear search in array](https://github.com/mowshon/Unyson/blob/master/framework/core/components/backend.php#L1570) on every cycle? So:

    1. Replace [this](https://github.com/mowshon/Unyson/blob/master/framework/core/components/backend.php#L1577) with:

        ```php
        $this->required_static[$type] = true;
        ```

    2. Replace [this](https://github.com/mowshon/Unyson/blob/master/framework/core/components/backend.php#L1570) with:

        ```php
        if( ! isset( $this->required_static[$type] ) ) {
        ```

4. There are option types like `multi`, `multi-picker`, `addable-*` which contain other options in their parameters, those parameters are sent to

    ```php
    fw()->backend->option_type( $type )->enqueue_static($id, $option);
    ```

    then option-type does the necessary `wp_enqueue_script()` and `wp_localize_script()` for inner options data.

    We are fine with `wp_enqueue_script()`, because you extract everything related to `"type"` and it will pick also the inner options, but I am not sure about options that does `wp_localize_script()` with data from options parameters, they will always contain the default parameters.

**Comment by mowshon** [comment]
1. Ok.

```
2) We have popup option-type and container-type, the above code will enqueue only container-type.
```

Yeah, in this case I don't know how script will understand that this is container-type or option-type. Only with new prefix for one of them or enqueue both.

**3**. Good idea, will do that.

4. I'm afraid that someone maybe use `wp_localize_script` in his custom option-type. 😕

**Comment by danyj** [comment]
> 'm afraid that someone maybe use wp_localize_script 

I am the first on who does it

**Comment by moldcraft** [comment]
@danyj Can you show your code?

**Comment by danyj** [comment]
wp_localize_script('fw-option-'. $this->get_type(), 'thz_typo', array(
				'fonts' => $this->thz_typogrpahy_print_fonts(),
				'notFound' => __('Oops, nothing found!','fw')
			)
		);

this is typo,  fonts var prints json fonts , 

my button option type has about 15 vars and there are few others

**Comment by mowshon** [comment]
@danyj i don't see `$option` variable to be used. In this case everything will be fine.

Or you can try to clone Unyson from my repo and test your theme on errors.
https://github.com/mowshon/Unyson

**Comment by mowshon** [comment]
@moldcraft I update the code.
https://github.com/mowshon/Unyson/blob/5f2788ee990130a8ddd9131693f4eed4261749e4/framework/core/components/backend.php#L1568-L1582

And now `popup` will be enqueued as container and option types.

**Comment by mowshon** [comment]
@moldcraft After your advice to ignore `in_array` functions, the method become faster.
Old `Own Time`: 131
Old `Time`: 1.259 ms

![new](https://i.gyazo.com/d72c6924d0812906b8c2783715bfc29d.png)
New `Own Time`: 12
New `Time`: 946 ms

**Comment by moldcraft** [comment]
> @mowshon After your advice to ignore in_array functions, the method become faster.

I always use array keys where possible.

**Comment by moldcraft** [comment]
@mowshon Please add in your code a note about `wp_localize_script()` and any other important info for other developers (as compact as possible).

**Comment by danyj** [comment]
tested , looks ok so far. checking all option types

**Comment by danyj** [comment]
check options in customizer please , I get this 
`
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class '_FW_Component_Backend' does not have a method '_callback_fw_collect_options_enqueue_static' in T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\general.php on line 914`

**Comment by moldcraft** [comment]
@danyj in @mowshon's version, is called [this method](https://github.com/mowshon/Unyson/blob/5f2788ee990130a8ddd9131693f4eed4261749e4/framework/core/components/backend.php#L1938) but it doesn't exist. It [exists](https://github.com/ThemeFuse/Unyson/blob/39af36b2a37cc869d72b4f68a173004d7aa6df26/framework/core/components/backend.php#L1575) in official version.

**Comment by mowshon** [comment]
Ups, I will return this method back.

**Comment by danyj** [comment]
You might want to check portfolio also , this is another bug I get with your version 

Warning: Invalid option: fw-portfolio in T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\general.php on line 921


Undefined index: type in T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\core\extends\class-fw-option-type.php on line 338

**Comment by danyj** [comment]
sorry \i get that on current Unyson , checking

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/pull/2048
