### ISSUE TITLE
Fatal error after updating extensions

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#205]
I am getting a funny error right after the last update 30the Jan 2015

<pre>Fatal error: Declaration of FW_Extension_Contact_Forms::process_form() must be compatible with FW_Extension_Forms_Form::process_form($form_values, $data) in ..site\wp-content\plugins\unyson\framework\extensions\forms\extensions\contact-forms\class-fw-extension-contact-forms.php on line 166
</pre>

**Comment by GheorgheP** [comment]
What version of contact form you have?
Please send a .zip file with your currently installed Unyson version.
There is not line 166 in the current version.
https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/v2.0.0/extensions/contact-form/shortcodes/contact-form/class-fw-shortcode-contact-form.php

**Comment by thednp** [comment]
Oops, too late, I already deleted the forms folder. But I think it was just the previous one. Perhaps some more users would confirm this issue.

**Comment by moldcraft** [comment]
We are very sorry.

The extension name was `contact-forms`, but in v2.0.0 was renamed (by mistake) to `contact-form`. On update the directories were merged and now you have

```text
forms/
    extensions/
        contact-form/ # <- this is wrong
        contact-forms/
```

we will fix the 2.0.0 release quick.

**Comment by thednp** [comment]
I updated previous comment please check.

**Comment by moldcraft** [comment]
We know about that. In some minutes we will fix it.

**Comment by thednp** [comment]
Remember, if you want your framework to go mainstream, we must not allow such issue, never. I wonder if this kind of issue would interfere with custom extensions built into themes.

**Comment by moldcraft** [comment]
fixed

**Comment by thednp** [comment]
Alright, waiting for the update to kick in.

**Comment by moldcraft** [comment]
Sorry, I forgot to mention: There will be no v2.0.1, we made changes in v2.0.0.
So reinstall the Page Builder or [install Forms](http://static.md/6d0ffb8588e4b5a38db115c78672968d.png).

**Comment by thednp** [comment]
I uninstalled everything and reinstalled Unyson plugin with all Scratch theme required extensions, still there is no forms extension in the Unyson Extensions page, but the folder is there though.

**Comment by moldcraft** [comment]
Forms extension in v2.0.0 is hidden.
It will be installed when the page-builder extension is installed.

**Comment by thednp** [comment]
Just like the Shortcodes extension.
