### ISSUE TITLE
Blank screen when activate Unyson Plugin

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#2052]
We are attempting to install  WP 4.6.1 with following PHP and mySQL versions. When we installed the plugin for Unyson 2.6.5 and activate the WP dashboard panel and website display goes blank. We experienced this problem with the latest version upgrade of Unyson.

What should I do now?

**Comment by moldcraft** [comment]
> What should I do now?

1. Check error.log
2. Make sure it is latest version, Unyson 2.6.6
3. Send me your admin and ftp credentials to `moldcraft[at]email.com` and I will inspect the problem.
