### ISSUE TITLE
Customizer not change preview values 

### ISSUE THREAD

**Issue by biklik** [ThemeFuse/Unyson#2053]
I  have this basic code (from the example) in my **../options/customizer.php** file:

            'section_1' => array(
                'title' => __('Unyson Section #1', '{domain}'),
                'options' => array(

                    'option_1' => array(
                        'type' => 'text',
                        'value' => 'Default Value',
                        'label' => __('Unyson Option #1', '{domain}'),
                        'desc' => __('Option Description', '{domain}'),
                    ),

                ),
            ),

And to get the changed value, I use **echo fw_get_db_customizer_option('option_1')** but nothing change. Only when I click in the save button the value is changed.

Can you help me?

Thanks

**Comment by moldcraft** [comment]
Hello,

I added in `{theme}/header.php`

```php
<?php fw_print(fw_get_db_customizer_option('option_1')); ?>
```

and [it works](https://vid.me/pALS).

**Comment by biklik** [comment]
I don't know if something is wrong in my project, but I'm having the problem yet.

You can see [here...](https://vid.me/1Bzx#3s)

**Comment by moldcraft** [comment]
@biklik Can you send me your admin and ftp details to `moldcraft[at]email.com` ?

**Comment by biklik** [comment]
Ok!

**Comment by moldcraft** [comment]
Thank you. Inspecting...

**Comment by moldcraft** [comment]
I made [the fix](https://github.com/ThemeFuse/Unyson/commit/281ed039b5bc2261d7212fcb208592ae8749cc97) on your site. It will be included in next Unyson release.

How Customizer preview works: At some point, the `get_theme_mod()` result is replaced with data from `$_POST`.

The problem: You called `fw_get_db_customizer_option()` earlier than the replace happened, the value  was cached, next time you call `fw_get_db_customizer_option()` (in `header.php`) the cached value is returned.

The fix: I reset the cache on `customize_preview_init` (when the customizer values replace happens).

**Comment by biklik** [comment]
Thanks!!!! ;))
