### ISSUE TITLE
Foreach loop within config title_template?

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#2054]
Is there a way to run a foreach loop within a shortcode's config file for the title template? I would like to display options saved in addable popups, etc...

I know we can use if statements like:

<pre>'title_template' => '{{- title }}: {{- o.label }}{{ if (o.target == "_blank") { }} <span class="dashicons dashicons-external"></span>{{ } }}',</pre>

But, I'm not figuring out how to run a loop, if it is possible.

Thanks!

**Comment by moldcraft** [comment]
Template syntax:

* `{{= var }}` Output a variable
* `{{- var }}` Output a variable html escaped
* `{{ console.log(var); }}` Execute any javascript code

So `{{ for (var i = 0; i < data.length; i++) { }}Hello {{- data[i] }}{{ } }}`

**Comment by meta4creations** [comment]
Perfect. Thanks again!
