### ISSUE TITLE
Is there global fw.soleModal.close ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2055]
I am having trouble with closing fw.soleModal when ajax is done

Made my custom modals 

        /*
         Custom msg
        */
        customMsg: function(title, msg, id) {

            var self = this;
			var modal_html = '<div class="thz-template-msg-holder">';
            modal_html += '<h2 class="thz-template-msg-title">';
            modal_html += title;
            modal_html += '</h2>';
            modal_html += '<div class="thz-template-msg">';
			modal_html += '<div class="thz-template-msg-in">';
			modal_html +=  msg;
			modal_html += '</div>';
			modal_html += '</div>';
			modal_html += '</div>';
			
            return fw.soleModal.show('thz_modal_template_custom_' + id, modal_html, {
                autoHide: 5000,
                allowClose: true,
            });

        },

        customMsgClose: function(id) {
            return fw.soleModal.hide('thz_modal_template_custom_' + id);
        }

and use it like 
 
```
  self.customMsg('title','msg','updatingmodal');

 //  ...ajax
 success: function(response, status, xhr) {
   // render done
    self.customMsgClose('updatingmodal');
}
```

but when ajax returns , it renders the admin options html and something changes in between so the modal stays opened. 

Is there a global 

` fw.soleModal.hide();`

that would close all opened modals?

**Comment by andreiglingeanu** [comment]
Nope, I think there isn't. You should keep references to your modal objects by yourself.

**Comment by danyj** [comment]
just needed a delay , fixed it. 

it was 

msg close 
msgopen 

and layload was bugging it , 

added delay in between and ok for now
