### ISSUE TITLE
[bug] table shortcode

### ISSUE THREAD

**Issue by wildwoodfalls** [ThemeFuse/Unyson#2056]
Attempts at using the  table, this error occurs upon saving:

```
Warning: Invalid option: button in /home/content/p3pnexwpnas02_data03/37/3598037/html/wp-content/plugins/unyson/framework/helpers/general.php on line 921

Warning: Invalid option: button in /home/content/p3pnexwpnas02_data03/37/3598037/html/wp-content/plugins/unyson/framework/helpers/general.php on line 921

Warning: Cannot modify header information - headers already sent by (output started at /home/content/p3pnexwpnas02_data03/37/3598037/html/wp-content/plugins/unyson/framework/helpers/general.php:921) in/home/content/p3pnexwpnas02_data03/37/3598037/html/wp-admin/post.php on line 197

Warning: Cannot modify header information - headers already sent by (output started at /home/content/p3pnexwpnas02_data03/37/3598037/html/wp-content/plugins/unyson/framework/helpers/general.php:921) in/home/content/p3pnexwpnas02_data03/37/3598037/html/wp-includes/pluggable.php on line 1174
```

When viewing the page, this error shows:

```
Warning: Invalid option: button in /home/content/p3pnexwpnas02_data03/37/3598037/html/wp-content/plugins/unyson/framework/helpers/general.php on line 921

Warning: Cannot modify header information - headers already sent by (output started at /home/content/p3pnexwpnas02_data03/37/3598037/html/wp-content/plugins/unyson/framework/helpers/general.php:921) in /home/content/p3pnexwpnas02_data03/37/3598037/html/wp-includes/pluggable.php on line 1174
```

**Comment by moldcraft** [comment]
Hello,

Please report this problem to theme author. There should be an invalid option like:

```
'button' => array(), // This array must not be empty
```

**Comment by wildwoodfalls** [comment]
Woffice

**Comment by moldcraft** [comment]
I don't have that theme. You can report the problem to theme author or send me your admin and ftp details to `moldcraft[at]email.com` and I will inspect the problem.

**Comment by moldcraft** [comment]
Sorry for the delay.

I inspected your site and it has some weird behavior.

1. Unyson plugin is disabled but it is active in menu

    ![c8a5ac7557](https://cloud.githubusercontent.com/assets/1475489/18850007/4a2cf44e-843e-11e6-93b4-77beac67d672.jpg)

2. Something is wrong with table shortcode

    ![1474920034100](https://cloud.githubusercontent.com/assets/1475489/18850022/5c4d3652-843e-11e6-8662-7b11256eb6cf.jpg)

----

I activated a default WP theme and everything is fine

![1474920301902](https://cloud.githubusercontent.com/assets/1475489/18850048/6e23ad2a-843e-11e6-9a21-6db75594e549.jpg)

So the problem is in theme, please report this to theme author.

**Comment by wildwoodfalls** [comment]
I will report this to the theme author.

Thank you for reviewing the issue!

**Comment by wildwoodfalls** [comment]
The theme developer has said that removing the following from the /extension/shortcode/hooks will resolve the issue:

 $to_disable[] = 'button';

I have done so, and it seems to do the trick. Do you see any conflict in this action?

Thank you.

**Comment by moldcraft** [comment]
Do you mean `(theme)/framework-customizations/extensions/shortcodes/shortcodes/hooks ?

**Comment by 2Fwebd** [comment]
Hi @moldcraft, 

Sorry for being a bit late on this issue, we've a few customers with this issue. As @wildwoodfalls pointed out it's only when you use a table shortcode. 

Thanks to your good recommandations, I've spotted that issue in : 
`/framework-customizations/extensions/shortcodes/shortcodes/hooks`

We used this line to remove the button shortcode as we're using a custom one with more options. It's a copy/past but with more options and a different layout. 

Please let me know if you need any other detail here. 

I can give you dev access or theme if you need. 

Thanks for the help and great support as always ! 👍

**Comment by moldcraft** [comment]
@2Fwebd So we should make the table shortcode to not throw errors and self disable button support if button shortcode is disabled?

**Comment by 2Fwebd** [comment]
@moldcraft I think so, because the issue is that the error is thrown on every page save containing the table element and not even the button shortcode itself. 

By the way, is there any way to run shortcodes within the cell ?

**Comment by moldcraft** [comment]
> is there any way to run shortcodes within the cell ?

Nope.

**Comment by moldcraft** [comment]
@2Fwebd Please test: [Download](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/archive/master.zip) and extract in `unysoin/framework/extensions/shortcodes`

**Comment by moldcraft** [comment]
Use [this filter](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/9129a84bcd590bf16d44aa9fadde89f543309c87/shortcodes/table/class-fw-shortcode-table.php#L116-L120) to add your custom button shortcode in table.

**Comment by 2Fwebd** [comment]
Sorry for the delay here, that's done. Within the shortcode's config.php file, is that the right place ? I don't really get how I'm supposed to test it. 

Thanks for all the help

**Comment by moldcraft** [comment]
Near the filter that disables the button shortcode.

**Comment by 2Fwebd** [comment]
```
function _filter_change_table_btn(){
    return 'woffice_button';
}
add_filter('fw:ext:shortcodes:table:button-shortcode-name', '_filter_change_table_btn');
````
Did the trick just fine, thanks a bunch @moldcraft !
