### ISSUE TITLE
Installation failed: 503 Service Unavailable Service Unavailable The server is temporarily unable to service your request due to maintenance downtime or capacity problems

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#2058]
**When we tried to install unyson top getting this error.**
_Installation failed: 503 Service Unavailable Service Unavailable The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later. Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request._

**And after refresh this error showing on top**
_Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request._

**buyer said this issue from here** 
_Line 82 plugins/unyson/framework/core/extends/class-fw-extension.php ._

**Comment by danyj** [comment]
looks like the extension your theme developer has made is not setup properly and path for overrides is wrong. 
https://github.com/ThemeFuse/Unyson/blob/master/framework/core/extends/class-fw-extension.php#L82

you need to contact the theme developer. 

have you tried disabling the theme? does Unyson work than?

**Comment by xperter** [comment]
This issue start when we tried to install extensions.
list showing all extension list. and when click to install extension this issue occurred.

We have tested in others server and its work fine.

**Comment by moldcraft** [comment]
@xperter Can you send me your admin and ftp credentials to `moldcraft[at]email.com` ?
