### ISSUE TITLE
How reliable is fw_get_google_fonts_v2 instance?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2060]
I am wondering if there is a time frame when `fw_get_google_fonts_v2() `can be empty. 
Is the font set on Unyson install, activation or ?

**Comment by moldcraft** [comment]
When you first install Unyson and the request to google fonts api failed

https://github.com/ThemeFuse/Unyson/blob/8509570f545b0039d55a79f46f0d1ce689576f1b/framework/helpers/general.php#L1087-L1096
