### ISSUE TITLE
Buttons ID's are duplicate when using WP Shortcodes extension

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2061]
Hi

When i use WP Shortcodes Unyson extension and i add Button element to the text editor, then i clone this element, Button ID remains the same as in it's clone. Even manually changing do not help, when i change button ID manually, it changes in cloned element too

![2b2c356a-80e6-11e6-9da5-d2848f81a35a](https://cloud.githubusercontent.com/assets/12991525/18838330/c15b7fe2-840f-11e6-9f25-41e119038eac.png)

**Comment by WPJobs** [comment]
Hi, @andreiglingeanu! Any update for this issue? Thanks!

**Comment by andreiglingeanu** [comment]
Hey @WPJobs. I'm no longer able to reproduce this bug, it appears to me that it is fixed already. Let me know if it is not fine please.
