### ISSUE TITLE
Unyson + Bootstrap

### ISSUE THREAD

**Issue by elissonkario** [ThemeFuse/Unyson#2062]
Hello.
I'm developing my theme using Bootstrap framework. When I enqueue the css and js bootstrap in my file functions, the bootstrap js is no work. When I Unyson plugin disable it works ... Is there any special way to use client boostrap on the front and with unyson?

**Comment by eyeswizard** [comment]
try this

```php

add_action( 'wp_enqueue_scripts', 'prefix_enqueue_scripts' );
function prefix_enqueue_scripts() {
wp_enqueue_script( 'prefix_bootstrap', 'bootstrap_uri', array( 'jquery' ), '1.0', true );
}

```

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid
