### ISSUE TITLE
fw_get_db_post_option() - ID change - (this is not an issue)

### ISSUE THREAD

**Issue by eyeswizard** [ThemeFuse/Unyson#2063]
hello
first i want to thank all unyson developers for the great framework and, specially @moldcraft who helped me a lot of times and inspected my code.

i have created a theme using unyson framework and uploaded it to themeforest.net and they gave me a soft-reject because of the theme name (Window) due to the copy right issues.

i changed the name to WindowMag and that is okay.

the things that are not okay that i named the IDs for the metaboxes with (window_) prefix
like `fw_get_db_post_option( get_the_ID(), 'window_post_cover');`

so how can i change this prefix without losing the data in the demo?
i have a lot of data stored with this prefix, so anyone can help me with this ?

any help will be appreciated,
thank you.

**Comment by moldcraft** [comment]
Hi,

Thank you for the kind words.

Unfortunately I don't know an easy solution to option ids rename.
You will have to make manually a script that loop through all db post meta, unserialize > renamed ids > serialize and save.

**Comment by eyeswizard** [comment]
i thought that there is an script can do this, i don't have much time to make one.
thank you
