### ISSUE TITLE
enqueue admin scripts for custom shortcode

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#2065]
Hi!
how i do enqueue_admin_scripts form my custom shortcode?
for frontend i used add_action( 'fw_ext_shortcodes_enqueue_static:{myshortcodename}', '_action_theme_shortcode_{myshortcodename}_enqueue_dynamic_script');
Thank's.

**Comment by mowshon** [comment]
You can  create own class for shortcode.
http://manual.unyson.io/en/latest/extension/shortcodes/index.html#class-file

And enqueue in **_init()** method.
