### ISSUE TITLE
Disable Megamenu

### ISSUE THREAD

**Issue by elissonkario** [ThemeFuse/Unyson#2067]
Hello. Do you have any way to disable the extension "Megamenu" in thema / framework-customizations / megamenu / ... or anywhere else?

**Comment by moldcraft** [comment]
Hi,
You don't you just disable it from Unyson Extensions page?

**Comment by elissonkario** [comment]
I want to disable it by default because megamenu extension conflicts with the standard menu of my theme.

**Comment by moldcraft** [comment]
You can hide it from css (it has an html id in Unyson Extensions page).
