### ISSUE TITLE
Cannot Import Demo Data

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#2068]
I’m trying to import the demo content but I’m getting an error while doing it. Please try it. I need the one page demo.

Error Screenshot : http://prntscr.com/cn8rr9

Regards
anisur

**Comment by moldcraft** [comment]
Hello,

Can you send me your admin and ftp details to `moldcraft[at]email.com`?

**Comment by anisur210** [comment]
Hi

I have sent my credential details into your email.

**Comment by moldcraft** [comment]
Inspecting...

**Comment by moldcraft** [comment]
@anisur210 Your db table prefix is `cTwBwP_`. You set it like that or it was generated automatically?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/279
