### ISSUE TITLE
Switch type inside other shortcode doesn't work

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#2069]
After some updates (or I missed this and it not worked ever) I can't use switch type(at least) in other shortcode.

To reproduce:
Some shortcode options:
```
$options = array(
	'button' => array(
		'type'          => 'popup',
		'popup-title'   => __( 'Button', 'your awesome domain' ),
		'button'        => __( 'Edit', 'your awesome domain' ),
		'popup-options' => fw_ext('shortcodes')->get_shortcode('button')->get_options()
	),
),
```
Where is button shortcode options are:
```
$options = array(
	'group_id' => array(
		'type' => 'group',
		'options' => array(
			'bold' => array(
				'type'  => 'switch',
				'label' => __( 'Button Weight', 'your awesome domain' ),
				'value' => 'false',
				'left-choice' => array(
					'value' => 'false',
					'label' => __( 'Thin', 'your awesome domain' ),
				),
				'right-choice' => array(
					'value' => 'true',
					'label' => __( 'Bold', 'your awesome domain' ),
				),
			),
		),
	),
);
```
Button shortcode itself works well, but inside other **right choice(true) will be never saved**.

P.S. Жду ответа, как соловей лета :)

**Comment by danyj** [comment]
it always had issues with booleans
http://prntscr.com/cnb0n0
https://github.com/ThemeFuse/Unyson/issues/1083#issuecomment-164524195

**Comment by onebelarusianguy** [comment]
@danyj I specially did it string, not boolean :) So it should work. As I said it works with shortcode itself and I use it in many other places - no problems

**Comment by danyj** [comment]
P.S.  your demo site is down

**Comment by onebelarusianguy** [comment]
@danyj which site?

**Comment by danyj** [comment]
nowdays and in general likeaprothemes ,

**Comment by onebelarusianguy** [comment]
@danyj hm, it's odd. Cause I check it right now. It works on my side. Root should redirect to ThemeForest :)

**Comment by onebelarusianguy** [comment]
@danyj Yeah, seems like the problem was in "boolean words". Thanks for the idea!
