### ISSUE TITLE
Theme Settings Reset deletes all builder templates

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#207]
After pressing [the Reset button](http://static.md/7208e2beda32ac0396733dbcf5df9087.png) all builder templates [disappear](http://static.md/8948026668df17cab7779a698894edf8.png) because they are stored in [the same database option](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/0d3cfde1069ab38222c5c55c7c80faf5881d7127/includes/option-types/builder/includes/template-saving.php#L15)

**Comment by danyj** [comment]
:+1: nice find , I was about to report it. My reset was emptying that array.
