### ISSUE TITLE
Cant extract demo archive

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2070]
Demo archives  come down damaged . Unexpected end of archive. How to troubleshoot?

**Comment by danyj** [comment]
Recreated demo few times , cant open the archives

**Comment by danyj** [comment]
this might help 

    Allowed memory size of 268435456 bytes exhausted (tried to allocate 133001216 bytes) in T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\extensions\backups\class-fw-extension-backups.php on line 587

**Comment by danyj** [comment]
yes , is the download function , on my end it points to this 
https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/class-fw-extension-backups.php#L599

the file in uploads/fw-backup can be opened with no issues

**Comment by moldcraft** [comment]
Please add `flush();` after [this line](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/c92890095a832dee8713b19f65fb4d919400a128/class-fw-extension-backups.php#L599)

```php
while (!feof($f)) {
	echo fread($f, 1000000);
	flush();
}
```

**Comment by danyj** [comment]
>Please add flush();

does not help ,  file is 320 943 kB ,  only half of that came down

**Comment by moldcraft** [comment]
Another try: Replace [these lines](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/c92890095a832dee8713b19f65fb4d919400a128/class-fw-extension-backups.php#L598-L600) with `readfile($archive['path']);`

**Comment by danyj** [comment]
same ,

**Comment by danyj** [comment]
http://prntscr.com/cngr9a

**Comment by danyj** [comment]
with readfile  only 270b  came down

**Comment by moldcraft** [comment]
What is your server and php memory limit?

**Comment by danyj** [comment]
win 10, wamp64 ,  memory_limit = 128M

**Comment by danyj** [comment]
php 7.0.14 ,  apache 2.4.18

**Comment by moldcraft** [comment]
> Allowed memory size of **268435456** bytes ...

&nbsp;

> with readfile only 270b came down

**268435456** bytes == 256 megabytes

Anyway, [this](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/c92890095a832dee8713b19f65fb4d919400a128/class-fw-extension-backups.php#L595-L596) should do the trick but in your case everything is loaded in php memory. I don't know another solution.

**Comment by danyj** [comment]
I dont need to download it via browser , just testing for everyone , making sure users dont get stuck. 
Yes i I can increase the limit to fix it but that is not an issue here. User sees download button , click , save , does not work.

**Comment by moldcraft** [comment]
Thanks.

I will try to: `open_file()` -> `seek_to_previous_step_line()` -> `read_data_and_output()` -> `repeat()`

**Comment by moldcraft** [comment]
Please test.

**Comment by moldcraft** [comment]
`flush()` is not working on my side. It should print one digit every second, instead the page is loading until all digits are printed and show everything at once. You can test by adding the below code in an empty php file

```php
<?php

header('Content-Type: text/plain');

for ($i = 0; $i < 5; $i++){
	echo "$i\n";
	flush();
	sleep(1);
}
```

**Comment by danyj** [comment]
> flush() is not working 

same here , I get full list , not one by one

**Comment by moldcraft** [comment]
The download is working too (with latest dev) ?

**Comment by danyj** [comment]
just tested , no same thing 

Allowed memory size of 268435456 bytes exhausted (tried to allocate 133001216 bytes) in T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\extensions\backups\class-fw-extension-backups.php on line 611

https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/830b9ec24dfd2f7726afb567b204a8dee7721c51/class-fw-extension-backups.php#L611

125MB came down , just like memory_limit in php.ini

**Comment by moldcraft** [comment]
I will try [this solution](http://stackoverflow.com/a/1395724/1794248)

**Comment by moldcraft** [comment]
`flush()` works

```php
header('Content-Type: text/plain');

$output_buffer_size = (int)ini_get('output_buffering');

for ($i = 0; $i < 5; $i++){
	echo str_pad("\n$i", $output_buffer_size, '-');
	flush();
	sleep(1);
}
```

**Comment by moldcraft** [comment]
It may not fix the problem, but I don't know another solution.

**Comment by moldcraft** [comment]
This fixes the problem on my side https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/da4ddedd6041936f96dff6a698673c1a7d1add74

Please test

**Comment by danyj** [comment]
that works!
