### ISSUE TITLE
"Unyson Page Builder" Settings won't update

### ISSUE THREAD

**Issue by Designstudio-Neuhausen** [ThemeFuse/Unyson#2072]
When I'm trying to update the "activate for"-settings  of the page builder and click on 'save' it leads me to the wordpress login page without saving the changes. Is this a known problem? I tried it with Wordpress 4.5 and 4.6 and with different browsers. Is there another possibility to change those settings? Maybe through phpmyadmin or FTP?

Best regards from Germany 

Markus

<img width="776" alt="bildschirmfoto 2016-09-29 um 11 46 42" src="https://cloud.githubusercontent.com/assets/22519209/18949159/6ddfa122-863a-11e6-9862-65abbb01ccd4.png">

**Comment by danyj** [comment]
that seems like customized list , contact theme developer please. we do not have this issue in plugin itself

**Comment by andreiglingeanu** [comment]
Also wasn't able to reproduce.

**Comment by moldcraft** [comment]
One of our colleagues have found the problem: Form's action attribute contains the domain without `www` (or vice versa) and the submit is sent to another subdomain which doesn't not contain current user cookies. https://github.com/ThemeFuse/Unyson/blob/7de5ae9f0e9fd65e49e71284d983e497e3d9e172/framework/helpers/class-fw-form.php#L109

@Designstudio-Neuhausen Can you send me your admin and ftp details to `moldcraft[at]email.com`?

**Comment by Designstudio-Neuhausen** [comment]
@moldcraft You are awesome! That was the point! I only changed the home-url or the WP-Page to the address without the "www" and so it saved the cookie right! Thank you so much!
