### ISSUE TITLE
Feature request: option to  remove "Reset" button from popup

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2073]
This "reset" button is so confusing, I can't see why it is useful since if the options are not in the popup , 
they can't be reset (double standards :) )
And also I need to maintain two different options value stacks in the popup. The one in the popup options elements itself, and the one in default values for the popup.
It would be nice if we could at least disable the button via popup options.
Also looking at the html , I see that the "reset" button has no special class on it so it can't be targeted via css without affecting possible future buttons in that toolbar. 
Maybe add a class to the button, so it could be hidden via css (it's a hack I know, but if there is no other way...)

**Comment by ivandotv** [comment]
Also the "save" button text is not actually saving anything, so that is misleading also.
I've personally made those mistakes a couple times, thinking that when the save button is clicked, the options are actually saved.
In case of the customizer at least it does a refresh. But in case of theme settings it doesn't make any sense.

**Comment by andreiglingeanu** [comment]
Agree, I'd also like to remove the Reset button from some popups.

<hr>

https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw.js#L1177-L1213

@ivandotv Why not to try your hand at submitting a pull request for that? It is not that hard. I'll happily review it.

**Comment by moldcraft** [comment]
In js was added [this parameter](https://github.com/ThemeFuse/Unyson/blob/17a8b3a56abef3db188ea769caac3d0130c23dc0/framework/static/js/fw.js#L1220). Do you need a parameter for shortcode page_builder config?

**Comment by andreiglingeanu** [comment]
Yeah, in JS it works fine and I'm using that.

> Do you need a parameter for shortcode page_builder config?

Too bad we'll have to set it for every shortcode

**Comment by moldcraft** [comment]
> Too bad we'll have to set it for every shortcode

Than a filter for default value? The value will be set in php and sent to js via `wp_localize_script('fw', ...)` and will be used only if `settings.disableResetButton` is undefined

**Comment by danyj** [comment]
> Too bad we'll have to set it for every shortcode

it is a shortcode config so it should be there , going trough own shortcodes would take few min. 
makes no sense to have disable_correction, popup_size and so on and than use filter for disable_reset

**Comment by andreiglingeanu** [comment]
> Than a filter for default value?

Yeah, I'm okay having a filter _just_ for _default_ value. Then we can have `disable_reset` in each shortcode.

@danyj Okay with that?

**Comment by danyj** [comment]
> Then we can have disable_reset in each shortcode.

sure if @moldcraft  does not mind the extra filter I am ok .

**Comment by moldcraft** [comment]
The filter https://github.com/ThemeFuse/Unyson/commit/442e5fdd789ec61715a732fa6345612d15a00966

**Comment by andreiglingeanu** [comment]
@moldcraft I like how the filter doesn't limit itself to just shortcode modals 👍

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/0058b670ef04bee47a09d7886eebca8a3e38d919

In shortcode config add

```php
$cfg = array(
	'page_builder' => array(
		// ...
		'disable_modal_reset_btn' => true,
	)
);
```
