### ISSUE TITLE
datetime-picker doesn't accept text formats

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2075]
Hi!

The datetime-picker supports formatting options ('Y/m/d H:i' by default). For a certain project I want to output the date like this: '30 sep-2016', so I figured I'd use this format: 'd M-Y'.

When selecting a date it works, but after saving the entry it's emptied. Is this just unsupported, a bug or am I doing something wrong?

This is the code I used for the option type:
`'datum' => array(
				'type'  => 'datetime-picker',
				'value' => '',
				'format' => 'd M-Y',
				'label' => __('Datum', 'project'),
				'hide-bottom-border' => true,
				'datetime-picker' => array(
					'format'        => 'd M-Y',
					'maxDate'       => false,
					'minDate'       => false,
					'timepicker'    => false,
					'datepicker'    => true, 
				),
			),`

**Comment by andreiglingeanu** [comment]
Known issue #1722.

**Comment by warudin** [comment]
Thanks, didn't come across that one. For now I've solved the issue by converting the dates with PHP.
