### ISSUE TITLE
WordPress  Shortcodes extension as requirement in theme manifest

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2076]
How do we set WordPress  Shortcodes to be required 

is this the index 

		'wp-shortcodes' => array(
            'min_version' => '1.0.0',
            //'max_version' => '2.99.9'
        ),

or?

**Comment by moldcraft** [comment]
```php
$manifest['requirements'] = array(
	//...
	'extensions' => array(
		'wp-shortcodes' => array(),
	)
);
```
