### ISSUE TITLE
Can we add max/min versions to  manifest supported_extensions 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2077]
http://manual.unyson.io/en/latest/manifest/theme.html#content

I see that we can add versions for extensions  but not for supported_extensions

**Comment by moldcraft** [comment]
I think it's a good idea to support all versions. Why do you want to constraint versions?

**Comment by danyj** [comment]
Same reason as https://github.com/ThemeFuse/Unyson/issues/1062
