### ISSUE TITLE
Should child theme DB options be separated

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2078]

**Comment by moldcraft** [comment]
Theme Settings?

**Comment by moldcraft** [comment]
Anyway, we can't change the default behavior because it will reset a lot of themes settings.

**Comment by danyj** [comment]
no, sorry I was bit confused , yes it is ok  that child theme options are separated

**Comment by danyj** [comment]
@moldcraft  sorry to bring this up but something does not add up , 

so you have a theme , take for instance TheCore ,   in core as you mentioned in other post you have custom CSS textarea which you guys have premodified ( in DB )  http://prntscr.com/csj2rq   for the theme demo  ,  

users are than advised to make customization in child-theme ,  
you activate child theme and that textarea is empty.

shouldn't you adleast duplicate default theme options for the child first?

**Comment by danyj** [comment]
hm , how did you do this ?  ,  the core is using same db table for child and parent 

`fw_theme_settings_options:the-core 
`

mine is using 2 
```

fw_theme_settings_options:theme
fw_theme_settings_options:theme-child
```

**Comment by moldcraft** [comment]
1. https://github.com/ThemeFuse/Unyson/blob/721cbee55402410768b41750a024b735491bb0fe/framework/helpers/database.php#L20
2. http://manual.unyson.io/en/latest/manifest/theme.html#content
3. TheCore has set manually `$manifest['id'] = 'the-core';`

**Comment by danyj** [comment]
thank you!
