### ISSUE TITLE
Extensions blacklist does not work

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2079]
I thought this will make the listed extensions not visible, 

    $cfg['extensions_blacklist'] = array('styling','feedback','learning','sidebars','social');

http://prntscr.com/co5zz4

**Comment by moldcraft** [comment]
I searched in all Unyson files and there is no match for `extensions_blacklist`. Where did you find this parameter?

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/24#issuecomment-59513960

**Comment by moldcraft** [comment]
That comment is posted on **Oct 17, 2014** when [Unyson was **v1**](https://github.com/ThemeFuse/Unyson/releases?after=v1.4.2) _(not as plugin)_

**Comment by moldcraft** [comment]
At the moment the only solution is to hide the extensions with css (every extension in html has an id)
