### ISSUE TITLE
Missing general theme options page

### ISSUE THREAD

**Issue by nenadmk** [ThemeFuse/Unyson#208]
First of all thanks for creating this framework. It's unbelievably easy to work in. I am loving it. Now, I am building a professional theme and I can't use separate folder for framework customizations. So I've copied everything from the /framework-customizations folder into the /framework folder and removed the customizations one. Now everything works the same without problems except that I've just noticed the general theme options page is missing? Is there something else that I need to change so that the theme options are read from the main /framework/theme/options/settings.php file? Thank you!

**Comment by levan1993** [comment]
Unyson works with framework-customizations folder. so you can't move files from this folder, because Unyson will search this files in framework-customizations folder, in case of general theme options page it will search for  framework-customizations/theme/options/settings.php file, if it doesn't exists page won't be created.

**Comment by sergiubagrin** [comment]
Hi @nenadmk

> Is there something else that I need to change so that the theme options are read from the main /framework/theme/options/settings.php file? Thank you!

Unyson works with framework-customizations folder. Scratch theme is a good example how to use it. Download it from GitHub: https://github.com/ThemeFuse/Scratch-Theme

In case you want to rename this folder we need to think about this. Can you give me more detaiuls why you need to rename it?

Thanks

**Comment by danyj** [comment]
I dont see this as a bad request. Every dev wants to be unique in some way no matter if he/she uses someone else's framework. This would give the dev kinda "white label" option and it would be cool to name the folder 

admin
cooltheme-options

etc.

Consider this . You start with underscore theme and there you already have inc folder, 
it would be cool if I can just add unyson options inside that folder and get on with it , but I cant I must make the custom folder for it. 


so something easy as 

load_unyson( 'themename', get_template_directory() . '/inc' );
inside functions.php could say that unyson options are inside the inc folder.

**Comment by moldcraft** [comment]
@danyj It will look unique, but when the user will ask us something or will read the unyson docs, there everything is explained with `framework-customizations/`, and this will be confusing.

**Comment by danyj** [comment]
I think dev should be responsible for the support of it's own theme.
And if you add in docs that folder for the theme option is changeable I doubt anyone would have an issue with it.

**Comment by danyj** [comment]
And if you add an article to your docs 
How to add unyson to your theme? 
With clear instructions it would be a win win.

**Comment by nenadmk** [comment]
I have actually no problems renaming the framework customizations folder. It looks like all I need to do is change the path in 4 functions into the /framework/bootstrap-helpers.php file. I needed that folder to be gone completely. But since that is not possible I guess I'll have to live with it.

One last question. Why the /theme/options folder exists then in the main framework directory when it does nothing and those options specified there can not be loaded?

**Comment by moldcraft** [comment]
> One last question. Why the /theme/options folder exists then in the main framework directory when it does nothing and those options specified there can not be loaded?

[Where?](https://github.com/ThemeFuse/Unyson/tree/master/framework)

**Comment by nenadmk** [comment]
Ah sorry. It looks like it doesn't exist in the original. :) I must have added it myself when I've copied everything from the customizations folder.
