### ISSUE TITLE
What request is WordPress sending on Update themes button click?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2080]
I started busting on this https://github.com/ThemeFuse/Unyson/issues/621#issuecomment-107908384
and almost got it finished but need the last piece. 

Made my own update checker and if update is available it serves the theme update file. Thing is that the package info reveals the link to file like

```
array
(
    [new_version] => '1.0.5'
    [url] => 'http://someurl'
    [package] => 'directlinktoupdatefile.zip'
)
```
I can make the md5 + salt and all mambo jumbo but
what I need to find is what request is WordPress sending when you click on this button 

http://prntscr.com/coc9lb

 in order to protect direct link , 

My download scripts checks the $_GET , for example 

```
if(isset($_GET['start_download'])){
...
 readfile( $file_path );
exit;
}
```

what I would like to do is 

```
if(isset($_GET['start_download']) && isset($_GET['the_request_wp_sends_when_you_click_update_themes_button'])){
...
 readfile( $file_path );
exit;
}
```

**Comment by moldcraft** [comment]
This is not related to Unyson. Debug WordPress
