### ISSUE TITLE
Saving as template is not working?

### ISSUE THREAD

**Issue by zenics** [ThemeFuse/Unyson#2082]
Using the latest version, saving any element as template is currently not working. Can anyone confirm that its not only me having the issue.

Thanks

**Comment by andreiglingeanu** [comment]
What's really not working?

If you're talking about the missing **Templates** button - was fixed by this https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/92e2bbaa7f6aa7f7635bc8669835989788a64c7f.

Please let me know.

**Comment by moldcraft** [comment]
@zenics This week we will release an update including this fix, please follow https://github.com/ThemeFuse/Unyson-Extensions-Approval

**Comment by andreiglingeanu** [comment]
@moldcraft I'm not sure if that was the actual problem.

Let's keep this open till @zenics confirm that everything's fine.

**Comment by zenics** [comment]
Just Updated, no luck, still not working guys.

**Comment by andreiglingeanu** [comment]
@zenics 
> What's really not working?

<hr>

Send me ftp and admin details at `andrei.glingeanu@gmail.com`.
