### ISSUE TITLE
Fatal Error: Class 'ZipArchive' not found?

### ISSUE THREAD

**Issue by erinsorganics** [ThemeFuse/Unyson#2083]
I recently updated Unyson and was greeted by this error:

Fatal error: Class 'ZipArchive' not found in /home/erinsorg/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php on line 430

Any ideas what this means? I can bs my way through most tech issues but not with coding.

**Comment by danyj** [comment]
ZipArchive()   is missing on your server 

https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/class-fw-extension-backups.php#L430

http://stackoverflow.com/a/3872578/594423

compile PHP with zip support

**Comment by danyj** [comment]
@moldcraft  yes he should have it already but I think we should also check for ZipArchive class  existence since Unsyon does not require it to function.

**Comment by erinsorganics** [comment]
Thank you for the quick fix! My hosting just upgraded their servers and reset php extensions to default. For whatever reason, zip was not enabled.

Thanks guys!
