### ISSUE TITLE
fw_option_type_builder:{builder-type}:register_items

### ISSUE THREAD

**Issue by jacobriprap** [ThemeFuse/Unyson#2084]
I updated Unyson and reinstalled the page builder plugin, but now no sections are show on the website (are visible in backend) and where the sections should be I instead get this message:

Please register builder types on 'fw_option_type_builder:{builder-type}:register_items' action

I have tried to search for an answer, but have not been successfull

**Comment by moldcraft** [comment]
Please go to Dashboard > Updates and click on Check Again button, then scroll down to see if there are Unyson Extensions update and update them.

**Comment by jacobriprap** [comment]
Hi!

Thanks for your fast reply.


I already tried that, and it didnt work out.


I have also tried to deactivate / remove the page builder plugin, and re install it.


Still same probem


Med Venlig Hilsen
Jacob Rasmussen


________________________________
Fra: moldcraft <notifications@github.com>
Sendt: 3. oktober 2016 15:10
Til: ThemeFuse/Unyson
Cc: jacobriprap; Author
Emne: Re: [ThemeFuse/Unyson] fw_option_type_builder:{builder-type}:register_items (#2084)


Please go to Dashboard > Updates and click on Check Again button, then scroll down to see if there are Unyson Extensions update and update them.

-

**Comment by moldcraft** [comment]
Try to activate a default WP theme.

**Comment by jacobriprap** [comment]
I re-installed the entire unyson plugin, and now the different section are visible, however, i now have three "errors"
Please register builder item-types on 'fw_option_type_builder:{builder-type}:register_items' action
Please register builder types on 'fw_option_type_builder:{builder-type}:register_items' action
Please register builder types on 'fw_option_types_init' action

and all sections shows:
function (n){return o.call(this,n,m)}

The most important thing is that it works, but if anyone have experienced the same problems or found a solution, please let me know

**Comment by moldcraft** [comment]
Can you send me your admin and ftp details to `moldcraft[at]email.com`?

**Comment by MikeiLL** [comment]
I am having the same issue. Latest version of Unyson and in my custom theme I followed Docs to [create a custom builder](http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid) because I want to use full width grid.

The docs doesn't mention adding hook to register the option type, which I have also tried, but I'm not sure how that differs from the include statement in `theme/inc/includes/lists-builder.php`.

```
// inc/includes/hooks.php
if ( defined( 'FW' ) ):
  /** @internal */
  function _action_theme_include_custom_option_types() {
      require_once dirname(__FILE__) . '/includes/option-types/class-fw-option-type-new.php';
      require_once dirname(__FILE__) . '/includes/option-types/lists-builder/class-fw-option-type-lists-builder.php';
  }
  add_action('fw_option_types_init', '_action_theme_include_custom_option_types');
endif;
```
Otherwise my process has been:
```
// file: theme/inc/includes/option-types/lists-builder/class-fw-option-type-lists-builder.php

class FW_Option_Type_Lists_Builder extends FW_Option_Type_Builder
{
    public function get_type() {
        return 'lists-builder';
    }
}
FW_Option_Type::register('FW_Option_Type_Lists_Builder');

```
And 
```
// file: theme/inc/includes/lists-builder.php

/** @internal */
function _action_include_demo_lists_builder() {
    if (!fw_ext('builder')) {
        /**
         * Lists Builder requires the FW_Option_Type_Builder class
         * which does not exist if the 'builder' extension is not active.
         *
         * You can install and activate the 'builder' extension by installing any extension that uses it,
         * for e.g. Page Builder or Learning (which has the Learning Quiz Builder sub-extension)
         */
        return;
    }

    require_once dirname(__FILE__) .'/option-types/lists-builder/class-fw-option-type-lists-builder.php';
}
add_action('fw_init', '_action_include_demo_lists_builder', 9);

```

**Comment by MikeiLL** [comment]
I also deleted all the extension and replaced using this [helper script](https://github.com/ThemeFuse/Unyson/blob/master/framework/extensions/clone-all.bash). Still same errors:

    Please register option-types on 'fw_option_types_init' action
    Please register builder types on 'fw_option_types_init' action

**Comment by MikeiLL** [comment]
I have just repeated my process in the [Scratch Parent theme](https://github.com/ThemeFuse/Scratch-Theme). Same error. I am probably doing something wrong. Well - obviously doing _something_ wrong. By the way this framework is beautiful!

**Comment by moldcraft** [comment]
@MikeiLL The documentation was outdated, I [fixed](https://github.com/ThemeFuse/Unyson-Documentation/commit/8dd05694ca3e1c20f31a9027f07a712e8bd52cf7) it. Thank you for reporting

**Comment by MikeiLL** [comment]
You rock, friend. That solved the first error message, but still getting `Please register builder types on 'fw_option_types_init’ action`.

**Comment by moldcraft** [comment]
Perhaps you have option-types registered on `fw_init` action, they [must be registered on `fw_option_types_init`](http://manual.unyson.io/en/latest/options/create-option-type.html#content)

**Comment by MikeiLL** [comment]
Nothing is registered on `fw_init` action. That action call does not occur in my theme at all at this point. The error goes away when I remove the `inc/includes/` directory, the only contents of which — at this point — are:

```
//lists-builder.php
<?php
/** @internal */
function _action_include_demo_lists_builder() {
    if (!fw_ext('builder')) {
        /**
         * Lists Builder requires the FW_Option_Type_Builder class
         * which does not exist if the 'builder' extension is not active.
         *
         * You can install and activate the 'builder' extension by installing any extension that uses it,
         * for e.g. Page Builder or Learning (which has the Learning Quiz Builder sub-extension)
         */
        return;
    }

    require_once dirname(__FILE__) .'/option-types/lists-builder/class-fw-option-type-lists-builder.php';
}
add_action('fw_option_types_init', '_action_include_demo_lists_builder', 9);

?>
```
 and within `lists-builder` dir:

*Ah!*

`lists-builder.php` wasn't _inside_ of the `option-types` directory! 

```
inc/includes/
└── option-types
    ├── lists-builder
    │   └── class-fw-option-type-lists-builder.php
    └── lists-builder.php
```

Thanks for your time, sir!

**Comment by moldcraft** [comment]
Please see [the fix](https://github.com/ThemeFuse/Unyson-Documentation/commit/8dd05694ca3e1c20f31a9027f07a712e8bd52cf7), the priority `9` was removed but you set it.
