### ISSUE TITLE
using backup to move site to new server, restore results in ajax errors

### ISSUE THREAD

**Issue by danbpc** [ThemeFuse/Unyson#2085]
I am using bitnami xampp and wordpress to develop a new site locally, my first site with wordpress.  I am able to backup and restore on the xampp site no problem.  I have 2 times now tried to use the full backup feature in my unyson theme (the core from themefuse) to move the site to bluehost.  Both times it totally trashed the bluehost wp installation.  I think that the problem may have to do with the file paths in the backup not being the same on the xampp site as on the bluehost site.  I get ajax errors when I attempt to restore site.

**Comment by danbpc** [comment]
any suggestions on how to proceed to move the site to production would be very helpful.  I have backup buddy, it makes a 2 gb backup file which is not happy when attempting to ftp to bluehost.

**Comment by danbpc** [comment]
This is the 1st time using this system and closed my question by error

**Comment by moldcraft** [comment]
Hello,

You can't restore full backup on another site. You can only migrate your content [this way](http://manual.unyson.io/en/latest/extension/backups/index.html#demos-bundled-in-theme).
