### ISSUE TITLE
Fatal Error on Blog

### ISSUE THREAD

**Issue by alysanger** [ThemeFuse/Unyson#2086]
Fatal error received on the blog after activating the plugin. Site works fine everywhere else, but when opening a blog post the below error is received:

Fatal error: Call to undefined function get_term_meta() in /home/icingi2/public_html/blog/wp-content/plugins/unyson/framework/helpers/database.php on line 255

**Comment by moldcraft** [comment]
Hello,

Please add [here](https://github.com/ThemeFuse/Unyson/blob/7de5ae9f0e9fd65e49e71284d983e497e3d9e172/framework/helpers/database.php#L254):

```php
echo '<pre>'; debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS); echo '</pre>';
```

activate again the plugin and show us the output.

**Comment by alysanger** [comment]
The following displays:

#0  FW_Db_Options_Model_Term->get_values() called at [/home/icingi2/public_html/blog/wp-content/plugins/unyson/framework/helpers/class-fw-db-options-model.php:128]
#1  FW_Db_Options_Model->get() called at [/home/icingi2/public_html/blog/wp-content/plugins/unyson/framework/helpers/database.php:419]
#2  fw_get_db_term_option() called at [/home/icingi2/public_html/blog/wp-content/themes/the-core-parent/theme-includes/helpers.php:1133]
#3  the_core_header_image() called at [/home/icingi2/public_html/blog/wp-content/themes/the-core-parent/single.php:7]
#4  include(/home/icingi2/public_html/blog/wp-content/themes/the-core-parent/single.php) called at [/home/icingi2/public_html/blog/wp-includes/template-loader.php:74]
#5  require_once(/home/icingi2/public_html/blog/wp-includes/template-loader.php) called at [/home/icingi2/public_html/blog/wp-blog-header.php:16]
#6  require(/home/icingi2/public_html/blog/wp-blog-header.php) called at [/home/icingi2/public_html/blog/index.php:17]

**Comment by moldcraft** [comment]
@alysanger Which WordPress version do you have installed?

**Comment by alysanger** [comment]
Looks like the latest wordpress update has resolved this issue. Thank you!
