### ISSUE TITLE
Multilingual?

### ISSUE THREAD

**Issue by keesjanssen** [ThemeFuse/Unyson#2087]
Are there any possibilities to cooperate with WPML or Goglobus to make my Wordpress website Multilingual? Both plugins gives errors.

**Comment by moldcraft** [comment]
Hello,

More details about multilingual plugins https://github.com/ThemeFuse/Unyson/issues/1603#issuecomment-222282449

I will ask my colleagues if they have WPML and I will try to test it. And I will also test WPGlobus plugin.

> Both plugins gives errors.

You can help us by giving as much details as you can. (with screenshots)

**Comment by moldcraft** [comment]
I am not sure if we will be able to make WPGlobus compatible because it doesnt create separated pages for each language, but the edit happens on the same page with js tricks https://vid.me/wQUN
We will inspect it and will figure out if it's possible or not.

**Comment by keesjanssen** [comment]
Thanks. Is there any plugin which works with Unyson so i can create my multilingual site?

**Comment by moldcraft** [comment]
@keesjanssen Have you tried Polylang?

**Comment by keesjanssen** [comment]
Not yet. I will try it immediately!

**Comment by keesjanssen** [comment]
Seems that Polylang is compatible with Unyson! I will translate my website, and will let you know if i find errors or not.
