### ISSUE TITLE
Moved servers, kept exact DB and URLs but page builder images are all broken

### ISSUE THREAD

**Issue by kyle-jennings** [ThemeFuse/Unyson#2088]
WordPress 4.6.1
Uyson 2.6.5 then upgraded to 2.6.7

We are moving our WordPress site to another server but any and all images served by Unyson's page builder seem to be broken.  The images do not render, but the image ID is displayed.

[for example](http://imgur.com/a/GXUlX)

choosing to display the image in a new tab shows the URL of mysite.com/19011

We are using the exact same database (made a sql dump and imported it) and the site URLs are all the same.  I experience the same issue locally, where I _did_ modify the database but I replaced mysite.com with mysite.loc so serialized data should not be effected

Some things I tried: I removed the image completely and saved the post.  Then I went back in and re-added the original image and it still does not work.

Then I uninstalled page builder and reinstalled it, i got a notification that I had to update the shortcode extension as well so I just went ahead and updated the entire unyson plugin.  Then I reactivated the page builder extension but it was no good. Still doesn't work.

Finally, I took at look at my database (the posts table) at see that page builder is just inserting the image IDs into the post content:

`<img src="19011" alt="19011" width="400" height="358" />`

However, the postmeta table for that post shows the following:
`"atts":{"image":{"attachment_id":"19011","url":"\/\/mysite.com\/files\/2016\/07\/About_mysite.jpg"},"`

So the page builder doesnt seem to be saving the proper image urls in the post

**Comment by moldcraft** [comment]
> I replaced mysite.com with mysite.loc

It will not work, our Database Restore script does an [advanced url replace process](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/6d9041ddafec06a9c8573e6438c3e0c656eab219/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L424-L546) while importing new data.

Please do content migration using our [Demo Install functionality](http://manual.unyson.io/en/latest/extension/backups/index.html#demos-bundled-in-theme).

**Comment by kyle-jennings** [comment]
wait a second, we **also** are having this problem on a newly built mirror of the live server. The **database is exactly the same, so no URLs were changed.**


Does the Demo install functionality or URL replace process work on Mulitisite? a few months ago we tried it on our staging platform and it removed all the users from all the sites

**Comment by moldcraft** [comment]
> Does the Demo install functionality or URL replace process work on Mulitisite?

It should. We have it installed on [ThemeFuse Testlabs](http://testlabs.themefuse.com/) which is a multisite where simple users can test our themes with Demo Install and we haven't problems with deleted users.

1. The [exported tables](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/6d9041ddafec06a9c8573e6438c3e0c656eab219/includes/module/tasks/type/class-fw-ext-backups-task-type-db-export.php#L286-L348) doesn't contain users and other important multisite tabled
2. On db restore/import, those tables are also [skipped](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.15/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L372-L398)

**Comment by moldcraft** [comment]
> Does the Demo install functionality or URL replace process work on Mulitisite?
> ...
> a few months ago we tried it on our staging platform and it removed all the users from all the sites

It should. We have it installed on [ThemeFuse Testlabs](http://testlabs.themefuse.com/) which is a multisite where simple users can test our themes with Demo Install and we haven't had problems with deleted users.

1. The [exported tables](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/6d9041ddafec06a9c8573e6438c3e0c656eab219/includes/module/tasks/type/class-fw-ext-backups-task-type-db-export.php#L286-L348) doesn't contain users and other important multisite tables
2. On db restore/import, [those tables](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.15/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L372-L398) are also skipped [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.15/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L603-L605) and [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.15/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L676-L678)

**Comment by kyle-jennings** [comment]
I just tried to run the Backup tool but it never completed (our database is about 2 gigs and we are hosting over 60 sites).

Do you at least know why Page Builder is only inserting the image ID instead of the GUID (which I see from newly uploaded images is used).

Maybe I could adjust my DB or setup to work around this issue.

**Comment by moldcraft** [comment]
Usually the theme uses [this function](https://codex.wordpress.org/Function_Reference/wp_get_attachment_url). So find in template the code that generates this html `<img src="19011" alt="19011" width="400" height="358" />` and debug it.
