### ISSUE TITLE
The web page cannot show the function of code

### ISSUE THREAD

**Issue by khangdoan03121993** [ThemeFuse/Unyson#2089]
I use the code  "" in the text block
but the web page is not show the function. How do I fix that?

![1](https://cloud.githubusercontent.com/assets/15787361/19144448/dae60718-8bd3-11e6-805f-70d725532b45.png)

![2](https://cloud.githubusercontent.com/assets/15787361/19144452/e3d8e53e-8bd3-11e6-8ea8-a7d3cfec6990.png)

Thanks!

**Comment by moldcraft** [comment]
[The comment is not removed](https://vid.me/6RFP)

> but the web page is not show the function.

Which function?

**Comment by khangdoan03121993** [comment]
when I choose function 'more' in the text block, it doesn't work

**Comment by duongancol** [comment]
@khangdoan03121993 Did you test in default theme?

**Comment by moldcraft** [comment]
@khangdoan03121993 Please test in default post editor.

**Comment by khangdoan03121993** [comment]
I tested in the default post editor but it still doesn't work

![screenshot](https://cloud.githubusercontent.com/assets/15787361/19176514/b6383750-8c6a-11e6-98a2-ee207fe5f526.png)

![screenshot 1](https://cloud.githubusercontent.com/assets/15787361/19176516/ba06a66e-8c6a-11e6-8a05-06cc57bb09b2.png)

**Comment by khangdoan03121993** [comment]
Can you solve my case? Our client need urgently. Thanks

**Comment by duongancol** [comment]
@khangdoan03121993 It's not an error. Please check your ticket!
