### ISSUE TITLE
Frontend options examples

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#209]
Can we have some examples on how to access options or builder options in frontend. 

For example I see that 
fw_get_db_settings_option('get_styles') is an array

```
Array
(
    [gadget] => blue
    [blue] => Array
        (
            [link_color] => #40b1e2
        )
    [red] => Array
        (
            [link_color] => #ff6600
        )
)
```

and I need to get current style and its link color so Is this ok 

```php
$options= fw_get_db_settings_option();
$style = $options['get_styles']['gadget'];
$style_color = $options['get_styles'][$style]['link_color'];
```

I am getting the wanted result ,

 or should we use something along these lines 

`fw_get_db_settings_option('get_styles/gadget')`... ?  what next? 
I am sure you made your own way to access deep array vars but I cant find the docs for it. 

And about the builder , for example I have a section in the page where the Full Width is set to yes 
I need to access this in frontend in order to make the layout
`fw_get_db_post_option()` gives me the array with page-builder json , so how do I go by accessing those options without me doing json_decode and stuff?

**Comment by moldcraft** [comment]
> fw_get_db_settings_option('get_styles/gadget')... ?  what next? 
> I am sure you made your own way to access deep array vars but I cant find the docs for it.

Nothing special, we just use often the [fw_akg()]( http://manual.unyson.io/en/latest/helpers/php.html#fw-akg) function.

*(incomplete response)*

**Comment by moldcraft** [comment]
> And about the builder , for example I have a section in the page where the Full Width is set to yes 
> I need to access this in frontend in order to make the layout
> fw_get_db_post_option() gives me the array with page-builder json , so how do I go by accessing those options without me doing json_decode and stuff?

The `json_decode` is wrong approach for shortcodes.

Overwrite the [section shortcode view](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/views/view.php#L21) in your theme. In `$atts` are all shortcode options that appear in popup when you edit the shortcode.

**Comment by danyj** [comment]
I did not mean that, not trying to change section output but rather get info if section on a page is 
full or boxed in order to adjust the area outside the section which is not a builder. 

Example 
page_container class has max width of 1200px
<div class ="page_container"> 
<section .....
</div>

if section on that page has full width I would do this 

<div class ="page_container_full"> 

but all in all , how do we get those options, that was the question.

**Comment by danyj** [comment]
I am back to this one. 
Sorry but I just cant agree with 99% of wp themes html coding style. I am used to have html be html and CSS/JS be separated. Something like this is a nightmare in my eyes http://screencast.com/t/HPEDYL3Oyt
  
I always place CSS either in a file or in  head via 
    
    wp_add_inline_style

And now I am trying to "cleanup"  the sections from inline style attribute. 
All of my scripts, styles and dynamic styles are located in   theme/inc/static.php 
And I need to access the page builder json, to get the sections ID's and background settings 

If I do this in inc/ststic.php
    print_r(json_decode(fw_get_db_post_option(get_the_ID(),'page-builder/json')));

I see the object perfectly and can use it to add section settings css to my wp_inline...




	Array
	(
		[0] => stdClass Object
			(
				[type] => section
				[atts] => stdClass Object
					(
						[sectionid] => someid
						[section_background_type] => stdClass Object
							(
								[gadget] => none
								[color] => stdClass Object
									(
										[bg_type_color] => #fafafa
									)
	
								[pattern] => stdClass Object
									(
										[bg_type_pattern] => pattern1.jpg
										[bg_repeat] => repeat
										[bg_position_x] => 0%
										[bg_position_y] => 0%
										[bg_attachment] => scroll
									)
	
								[image] => stdClass Object
									(
										[bg_type_image] => background1.jpg
										[bg_repeat] => repeat
										[bg_position_x] => 0%
										[bg_position_y] => 0%
										[bg_attachment] => scroll
									)
	
								[uploadimage] => stdClass Object
									(
										[bg_type_uploadimage] => 
										[bg_repeat] => repeat
										[bg_position_x] => 0%
										[bg_position_y] => 0%
										[bg_attachment] => scroll
									)
	
								[video] => stdClass Object
									(
										[bg_type_video] => 
									)
	
							)
	
					)
	
				[_items] => Array

so the question again is , is there easier way for me to get to those without json_encode or am I forced to use it? 


Optimal would be if I could do wp_inline from within the section view.php  but I was not able to get it to work.
