### ISSUE TITLE
bug , options order

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2090]
Create addable popup , 

in options add any options , under the options add set of options

    
			'title'    => array(
				'type'  => 'text',
				'label' => __( 'Title', 'fw' ),
				'desc'  => __( 'Icon title', 'fw' ),
			)
			fw()->theme->get_options('some_options_set')

set options show up first instead last.

**Comment by moldcraft** [comment]
Options array is converted to json to be used in javascript, javascript object keys order is not preserved. Try

```php
array(
    'title'    => array(
        'type'  => 'text',
        'label' => __( 'Title', 'fw' ),
        'desc'  => __( 'Icon title', 'fw' ),
    )
),
fw()->theme->get_options('some_options_set')
```
