### ISSUE TITLE
Page Builder Images rely on GUID?

### ISSUE THREAD

**Issue by kyle-jennings** [ThemeFuse/Unyson#2091]
Does the Page Builder extension rely on the attachment's GUID to render on the page?

It appears to use the GUID (contains the URL) instead of the wp_get_attachment_url hook, which causes compatibility issues with other plugins such as Offload S3.

After installing and using the Offload S3 plugin, and then attempting to upload an image. The Page Builder inserted the image using the GUID url and thus the image did not load.  I then  manually changing the GUID to the proper S3 url and then the image loaded correctly.

**Comment by moldcraft** [comment]
`upload` option-type stores the value as array

```php
array(
    'attachment_id' => 3,
    'url' => 'http://....jpg'
)
```

in themes the image url is accessed like this

```php
echo wp_get_attachment_url($val['attachment_id']);
```

I think the problem is in Offload S3 plugin, it should use filter to replace/change image url when it is accessed via `wp_get_attachment_url()`
