### ISSUE TITLE
New update broke my custom page builder elements Vol 2

### ISSUE THREAD

**Issue by Jelena1** [ThemeFuse/Unyson#2092]
This issue happens again, I already had opened this issue few months ago: https://github.com/ThemeFuse/Unyson/issues/1855

What is going on with newest update? Again same happens, broken custom elements. Please help.

**Comment by danyj** [comment]
are you doing this in custom elements ? 

```
		fw()->backend->option_type('multi')->enqueue_static();
		fw()->backend->option_type('addable-option')->enqueue_static();
		fw()->backend->option_type('switch')->enqueue_static();
```

some of mine custom elements are based on others so I have to require all of them. In your screenshots I see that styles/js are missing. 

and this one also , what are you using for uri in the _enque_static, I do this 


```
	$uri = get_template_directory_uri() . '/inc/includes/option-types/' . $this->get_type();

	wp_enqueue_style(
		'fw-option-' . $this->get_type(),
		$uri . '/static/css/styles.css',
		array(),
		fw()->theme->manifest->get_version()
	);

```

**Comment by KenJames0322** [comment]
I just updated Unyson and Unyson extensions on my site and now the site content is in total disarray.  There is no styling and everything appears overly large.  It's just totally broken. The dashboard elements look fine, it is the web page itself that is messed up:  www.jandtassociates.biz  I really need this fixed. Thanks.

**Comment by Jelena1** [comment]
http://rayoflightthemes.com/wordpress-themes/insurance-agency-business-and-insurance-wordpress-theme/  this is my theme demo where issue occurs when I updated Unyson. @danyj I don't really understand that. I don't use anything that is not recommended by Unyson documentation for creating custom elements. They already had similar issue (link in first message) when I reported this issue first time few months ago. Not it happens again.

**Comment by moldcraft** [comment]
@Jelena1 Have you [tested latest extension updates](https://github.com/ThemeFuse/Unyson-Extensions-Approval)?

Please comment [this line](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/df34d50217441da32581bff463e8b83a10e42ab3/class-fw-extension-page-builder.php#L369) and let us know if it fixes the problem.

**Comment by Jelena1** [comment]
@moldcraft can you add full path to that file please? I can't find it in Unyson plugin folder.

**Comment by moldcraft** [comment]
```
wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/class-fw-extension-page-builder.php
```

**Comment by Jelena1** [comment]
@moldcraft yes it fixes the problem!

**Comment by moldcraft** [comment]
Can you send me your ftp and admin credentials to `moldcraft(at)email.com`?

**Comment by Jelena1** [comment]
@moldcraft email sent.

**Comment by moldcraft** [comment]
I will inspect it tomorrow, off for today

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/releases/tag/v1.6.5

**Comment by Jelena1** [comment]
Same error after newest update, can you  please check this? Thanks.

**Comment by moldcraft** [comment]
Please replace [this line](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/7e9a097ec6b4c959575bf29e489d3065ba6548f2/class-fw-extension-page-builder.php#L370) with

```php
fw_print(get_option('posts_per_page'), count($posts)) || true
```

**Comment by Jelena1** [comment]
That doesn't help, only adds divs with class rw_print_r_group

**Comment by moldcraft** [comment]
It's not a fix for the problem, it's a debug. (I need to understand why in your case it doesn't work)

**Comment by Jelena1** [comment]
I've sent you email

**Comment by KenJames0322** [comment]
Can you please remove me from this thread?  This does not involve me. Thank you.

**Comment by moldcraft** [comment]
@KenJames0322 I can't. You must click on this button

![staticshot_20-12-2016_14-48-28](https://cloud.githubusercontent.com/assets/1475489/21351063/6935ce3e-c6c3-11e6-95ec-4e2ab4dcce64.png)

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/2092#issuecomment-267959015

On your side `count($posts)` is `12` and `get_option('posts_per_page')` is `3`.

**Comment by moldcraft** [comment]
I will try to create [extension approvals](https://github.com/ThemeFuse/Unyson-Extensions-Approval) this week.

**Comment by Jelena1** [comment]
thanks

**Comment by Jelena1** [comment]
Any update on this?

**Comment by moldcraft** [comment]
@Jelena1 Do you follow [this respository](https://github.com/ThemeFuse/Unyson-Extensions-Approval)?

**Comment by Jelena1** [comment]
Didn't follow before but now I will. Will there be update on this issue?

**Comment by moldcraft** [comment]
Have you checked the issues on that repository?

**Comment by moldcraft** [comment]
You can [contact GitHub](https://github.com/contact) and tell them the zip contains virus.

**Comment by Jelena1** [comment]
This is answer I got from Github support: 

_"Hi Jelena,

I'm sorry, but this address is for GitHub support. You may have been looking for support for a specific project hosted on GitHub.

https://github.com/ThemeFuse/Unyson

If you have issues or questions with a project hosted on GitHub.com, please check the project's README file for an official website or contact information. Alternatively, you can either use the GitHub project's issue tracker, contact the project's mailing list (if it has one), or contact the project owner directly by checking their GitHub profile for contact details.

Cheers,
Petros"_

What do you suggest?

**Comment by moldcraft** [comment]
I haven't uploaded any file. That archive file is automatically generate from the code on github. I think your antivirus is wrong or you have a virus that infects the archive file while it is downloaded via your browser.

**Comment by Jelena1** [comment]
This is first time in five years I have such problem with uploading files on my hosting so I don't think that is issue. Question is why Github support refuses to at least scan those files. I don't use Github much so I'm not much familiar with it, sorry for my ignorance.

I don't know how could I participate in this testing, please if you need ftp and access to my theme let me know. (although version you set last time on my hosting works well, if that means something...)

**Comment by moldcraft** [comment]
I didn't meant you to test the extension, I wanted to show you how and when the new version will be released (because you asked "Any update on this?")

I am publishing the new versions now.

**Comment by Jelena1** [comment]
@moldcraft  unfortunately problem is still there with new version. I'm sending you ftp and details in email.

**Comment by moldcraft** [comment]
I fixed this by deleting all optimizations https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/015b14dd26eb1092e200fad3b7990a0f343917e0

I somebody will complain about the performance I will try to introduce the optimizations again, at the moment they generate only bug reports like this.

----

On your side you have a custom post type for page sections and in frontend theme template you do a not limited wp query to get all those posts and display them all on frontpage. Current optimization has had a limit of posts that will be processed, but in your case it must process all posts.

**Comment by danyj** [comment]
I kinda dont understand whos bug is this now. Ours for limiting the loop or @Jelena1  for not properly limiting the query ?

**Comment by moldcraft** [comment]
Ours
