### ISSUE TITLE
Help me understand multiple demos mechanisam

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2093]
OK , I am struggling here and digging trough all premium themes to figure out how they did this. 

So you have a multipurpose theme, have many options in theme admin all nice and dandy., But you still have to write 10/20 lines of CSS  for specific cases. 

So your default theme has a small CSS file ( lets call it style.css )  in its CSS folder 

`themes/theme_name/css/style.css // has 20 specific lines`

this file is called in theme head. 

Now you go ahead and create lest say a Magazine concept theme based on your default theme  and  in the creation process you add/remove/change few more lines to the style.css ,  

Now the trouble comes. 
You create demo , but Unyson is not  packing or touching your theme and is not packing that customized style.css.  You need to move that file somehow to the theme css folder  in order to give the user exact Magazine demo. 

Thnig here is that the "demos"  are just DB content and uploads folder , not the modified theme. 
You cant just add that style.css to demo zip , you cant rely that you will be allowed by the server to override the existing style.css already located in themes folder. 

How did you do this in your theme? 
How did you make the mechanism that changes the actual theme when demo is installed? 

Any help is appreciated!

**Comment by moldcraft** [comment]
Hi,

In TheCore theme there is a textarea in theme settings for Custom Css.

**Comment by danyj** [comment]
@moldcraft thnx for the reply , I have that to , but kinda think that that should not be used by us but the users,

**Comment by thednp** [comment]
@danyj I think there are some multi-site plugins to help out with that, but as for CSS, I would have a different approach.

I would have a back-end switch `Demo Mode: On/Off` and this would allow you to do some dynamic CSS file per page. Let me know if that doesn't make much sense.

**Comment by danyj** [comment]
@thednp , I have per page CSS also , that is not an issue here , 
check this out bud ,  this is my concern ,  

small example , 

by default post meta items ( date, author etc 6 of them )  have no icons next to them , 

than when making magazine theme you as developer would add something like 


```
.thz-entry-author a:before{
	font-family:'Thzicons';
    content: "\e0d1";
    margin-right:5px;	
}

```
than  , some sidebar menu items have an arrow icon and you want it gone ,  

you do 

`.thz-sidebar .thz-menu-item a:before {disaply:none;}`


now all these should be in theme demo specific style , but we cant do that because of reasons explained above. instead you have to stuff theme settings with unnecessary things. 


I see now that all premium theme have overloaded their themes with unused stuff and reason behind it is the demo presentation issue  and or not being able to modify the actual theme files on demo install. ,

**Comment by thednp** [comment]
I think I solved most of the issues with bloated CSS by using LESS. I think you didn't get my idea: you can create several `style.css` and add them dynamically for each page you want with some PHP, as I explained above. This is the way to go, I don't think doing multiple wp installs would really make your life easy.

**Comment by danyj** [comment]
> you can create several style.css

depends on what type of multi theme you have , 
if you are making something like undesign than yes that works , since the base is same on all pages

but betheme, avada,enfold , bridge and many more have actual demos not demo pages , and that is same direction we are going thus the issue with that one extra file,

**Comment by ivandotv** [comment]
I'm also looking how to solve this problem. 
My thinking about this:
1. There needs to be a switch to differentiate between demo and pure theme install.
2. There could be code for the demo that is not distributed with original theme ( you run in for the demo)
3. As moldcraft suggested, you could use custom css area, and when the theme is activated you take that css code and append it to the original style.css file (and use the new file).
4. Or have multiple css files and depending on the demo , use that css file. That is one more css request, but honestly who cares wordpress is already bloated via plugins, so I don't think your users will mind.
I don't know if any of this is violating TF requirements.

On a side note, I'm also interested in dynamically generated css (right now I'm using a php sass compiler and dumping everything inside style tag) we could also discuss about that...

**Comment by danyj** [comment]
@ivandotv I made compression for dynamic scripts and theme css files so no issues there, all theme files are compiled and I tested yesterday , this is without compression plugins 
http://prntscr.com/cswwga

and with Franks autoptimize + W3C  total cache I get 100/94

 , but this little bugger got me going 
https://github.com/ThemeFuse/Unyson/issues/2078#issuecomment-252982660

now I made child use the parent DB and custom textarea CSS  is ok'sh but again , I hate to use it since it is not for me but users. 

Now what I also have is all points that you numbered 

Demo install , 
Only theme options install

so now im thinking on that style per demo + hidden option that says , 

magazine or blog and I could append the magazine.css or blog.css 

P.S.   jesi bio na WPNS ?  trebali smo na kafu otici  :)

**Comment by danyj** [comment]
@ivandotv  I just read this again 
>  when the theme is activated you take that css code and append it to the original style.css file (and use the new file)

that is the biggest issue ,   we cant rely on it , if server blocks access to it you out of luck , only folder that is always accessible is the uploads folder, 

but when you think about it is the dumbest thing ,   CSS files are always accessible right?

**Comment by danyj** [comment]
@moldcraft , cmon bud help us out , is there no way we can move one css file to theme folder on demo install?

**Comment by moldcraft** [comment]
Demo install doesn't require FTP credentials when you press install (on some servers to modify files outside uploads/ dir you need FTP credentials)

**Comment by danyj** [comment]
@moldcraft  ok , so we back to that one again , thnx bud!  will keep thinking.

**Comment by ivandotv** [comment]
@danyj I haven't been to the meetup maybe next time :)


If most popular themes do it, then I don't see that being an issue for the buyers.

Also there is an issue of the `demo options`:
Let's say that you have three different header designs, and you want to show them all inside one theme installation, how would you do it ?

**Comment by danyj** [comment]
>If most popular themes do it, 

that is the thing , they are not doing it , there is something else going on with avada, betheme,enfold that I just cant see.  I caught maybe 2 lines of css in textareas but the amount of change from demo to demo is simply huge. Maybe they just do per page CSS. Don't know. 


>how would you do it 

you are looking for my template option type , will share after release , http://prntscr.com/cszskq

it collects group of options and makes "template" set out of them

**Comment by danyj** [comment]
sorry to mention it,  but in this case I miss Joomla ( uuups, yes I said it )  , very easy demo installs and no theme folder restrictions

**Comment by ivandotv** [comment]
>that is the thing , they are not doing it , there is something else going on with avada, betheme,enfold that I just cant see. I caught maybe 2 lines of css in textareas but the amount of change from demo to demo is simply huge. Maybe they just do per page CSS. Don't know.

I don't have those themes available to me, but maybe you could check via network panel what css files the theme loads in its `raw` state, and after the demo, and see if you could spot any difference (size, filepath)

> it collects group of options and makes "template" set out of them

I don't really understand that part. Does that mean you can show the same blog page with different layouts and other options ( e.q blog post as grid, or as simple listing)?

**Comment by danyj** [comment]
>  page with different layouts and other options

yes , that is exactly what it does ,  you setup options as you usually do , than insert thz-template and tell it what set to collect , 
for the pagination template it collects about 10 options I have setup for pagination and makes templates out of them. 

> see if you could spot any difference

not one theme file gets changed on demo install,  everything seems in DB , and I cant believe that they were able to pack ALL possible CSS options inside

**Comment by danyj** [comment]
@moldcraft , ok I am trying with everything I have but I dont see way out. Even TheCore theme has same bug and I dont know if you guys have noticed it. 

Install any TheCore demo ,   it works 

Go in theme settings hit reset ,  it resets to the hard coded options array instead of the demo theme options array and user is not able to get the options back as they were meant to be. 

This comes to the same issue I have which is not able to assign some kind of outside theme hook to be used as main preset/theme options. 

I think we need outside fw_db_theme_settings option to be saved and used for this or maybe change the storage for one particular option. Not sure but the demo + reset combo is not working as it should.

**Comment by danyj** [comment]
fw-storage seems like is working for me for this particular option ( still testing )  but as mentioned TheCore  should reset the options to current demo options set not hardcoded defaults.

**Comment by ivandotv** [comment]
@danyj Regarding how the do it. Maybe you should check theme files after installation and demo setup. and see "last modified/created" time. To see what and if anything gets updated.

regarding the textarea for custom css. Does that mean that you are putting all that custom css in the style tag on the page?

- What about providing multiple child themes with custom css?

**Comment by danyj** [comment]
>  Maybe you should check theme files after installation

as advised above I did that , they not chaging files , 

avada adds few lines in textarea everything else is options
thecore lines in textarea 
bridge lines in textarea 
enfold dont know 


now all those dont matter anymore because we have huge reset bug  https://github.com/ThemeFuse/Unyson/issues/2093#issuecomment-253463031

and no matter what way you choose to give your users the demo/preset , once they click on  reset theme options button they will see your hardcoded options array and the textareas or what ever you picked to server specific CSS is gone for good until the reinstall the demo.

**Comment by danyj** [comment]
>  What about providing multiple child themes with custom css?

as I see it , child-themes are for users not us but if I was to provide child-themse than I rather just make extra CSS files for each demo and keep it in parent theme

**Comment by moldcraft** [comment]
> @danyj https://github.com/ThemeFuse/Unyson/issues/2093#issuecomment-253463031

Use [this filter](https://github.com/ThemeFuse/Unyson/blob/6293d80b967f5ac5ac2204b3cef6c7d7ec445374/framework/core/components/backend.php#L1362) to keep the custom css textarea value

**Comment by danyj** [comment]
>  Use this filter 
thnx but that is one option now , the bug is bigger than one option , test TheCore and you will see what I mean.

**Comment by ivandotv** [comment]
@danyj 
Try project wide search for a piece of code (html element, css class) that you are sure it came from the demo. Maybe that will give you some clues.
Alos maybe ask this question on TF forum.

**Comment by ivandotv** [comment]
@danyj 
I'm hoping to finish my theme in next two weeks, and then I will start to investigate how to package multiple demos and dynamic css.
Also we could setup a chat room for unyson on gitter, so we could share code and demos.

**Comment by danyj** [comment]
@ivandotv  sure bud , let me know , I managed to fix the above issues and finally got my hook. Will serve one extra CSS per demo since I just dont see the use of the textarea and it seems unprofessional. It should be used by users and we ( devs ) should not rely on it.
