### ISSUE TITLE
Bug between Divider shortcode & new update Page-Builder extension

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#2094]
When I update Page builder extension, The divider shortcode that i**nside a section and in the button of section** didn't work. It only happens with current content. It works well if I create a new section and shortcode.
I made a screencast here http://take.ms/5oqi4
Tell me if you need more information.

**Comment by duongancol** [comment]
I have to restore the old version because other shortcodes disappeared not only divider shortcode

**Comment by moldcraft** [comment]
Please [test](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension)

**Comment by duongancol** [comment]
I tested but it still didn't work

**Comment by moldcraft** [comment]
I remember you have a cache plugin installed, please reset the cache or disable the plugin

**Comment by duongancol** [comment]
I know but I tested in localhost, you could test in the account I gave you. Try to update page-builder extension. It's in old version currently

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/2094#issuecomment-252418846

I meant to test lates dev version from github

**Comment by duongancol** [comment]
ok, hold on

**Comment by duongancol** [comment]
work like a charm , can you make a release?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/releases/tag/v1.6.6

I will show up as update in dashboard in 12-24 hours

**Comment by duongancol** [comment]
Thank you!
