### ISSUE TITLE
Visual Page Builder (VPB) is not correctly loading in Portfolio

### ISSUE THREAD

**Issue by mrLucianoii** [ThemeFuse/Unyson#2095]
VPB is loading correctly in the admin portal in all page types except Portfolio. 
![screen shot 2016-10-07 at 11 17 43 pm](https://cloud.githubusercontent.com/assets/5217630/19210893/4ba78b5a-8ce4-11e6-9932-e0aa0933d0cd.png)

This div that holds the form for VPB is not loaded.  HTML is there in the DOM upon element inspect:
![screen shot 2016-10-07 at 11 20 59 pm](https://cloud.githubusercontent.com/assets/5217630/19210917/d1412c8a-8ce4-11e6-9cd5-5d57c67b013e.png)

I can force open the div by changing the class from .closed to .open from the DOM.  The issue is then somewhere with the Toggling between "Default Editor" and "Visual Page Builder" button.  Once I change the class, then the toggling functions correctly.  Upon refresh of the page, the toggling class is incorrect.

**Comment by moldcraft** [comment]
Hello,

Please execute this in browser console

```js
jQuery('#fw-options-box-page-builder-box > .hndle').trigger('click');
```

on box click an ajax is made and WP will save the box state
