### ISSUE TITLE
Unyson page builder

### ISSUE THREAD

**Issue by Kotisivutvirosta** [ThemeFuse/Unyson#2097]
Hey!

I'm using Woffice WordPress theme and it has Unyson framework.

Your pagebuilder doesn't have lightbox option, which I really need (for example - http://fancyapps.com/fancybox/#examples -> various types -> Ajax). Is there some kind of plugin, that works with your framework? If not, can you suggest workarounds?

Best regards,
KSV

**Comment by moldcraft** [comment]
Hello,

You [can create your shortcode](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#creating-a-new-shortcode) in theme.
