### ISSUE TITLE
Slider option in addable box

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#210]
Hi!
I did create addable-box for custom post type. 
Everything fine with text, select,.. except **slider**.
I added slider to addable-box , it only showed title, description, help.
Check my screenshot here: http://i.imgur.com/icUFxAg.png 
Thanks!

**Comment by duongancol** [comment]
I tried to create slider option without addable-box in custom post type, 
It's also hidden.

**Comment by valeriuzdrobau** [comment]
Try to clean the cache, and please tell me what version of framework and in which browser you have tested.

**Comment by duongancol** [comment]
I use the latest version of Chrome, wordpress 4.1, and Unyson 2.1.9

**Comment by moldcraft** [comment]
@duongancol I can't reproduce this. Everything works fine on my side.
Can you give us your options array?

**Comment by valeriuzdrobau** [comment]
Thank you for your cooperation.

**Comment by duongancol** [comment]
Great!, thank for your great framework.
