### ISSUE TITLE
Custom columns for builder are not working anymore

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2100]
I've added custom columns for the page builder. After the latest update, it shows this error in the console:

`builder.js?ver=1.2.5:910 Failed to recover items from input TypeError: Cannot read property '$el' of undefined(…)`

The error causes the page builder not to show the output of the shortcodes.

Am I doing something wrong, or is this a known error?

WordPress: 4.6.1
Unyson: 2.6.7

**Comment by andreiglingeanu** [comment]
Hi.

Send me your ftp and admin credentials at `andrei.glingeanu@gmail.com`.

**Comment by noesteijver** [comment]
I emailed you all the credentials! Let me know if they don't work.

The error has changed:

- When looking at the admin side of a page (for example: home), where I use the pagebuilder, I see the custom columns in the toolbar. But they aren't working in the builder. There are only the standard columns.

I do see this error:
`
Uncaught TypeError: Cannot read property 'body' of undefined
`
This error is located in tinymce.min.js

**Comment by noesteijver** [comment]
I saw some changes in the Builder extension via https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/config.php

My idea was not to use the standard columns, but add my own (some of them are the same as the standard columns) in a specific order. This is my code:

`
$cfg = array();

/**
 * Default item widths for all builders
 *
 * It is better to use fw_ext_builder_get_item_width() function to retrieve the item widths
 * because it has a filter and users will be able to customize the widths for a specific builder
 *
 * @see fw_ext_builder_get_item_width()
 */
$cfg['grid.columns'] = array();

/**
 * @since 1.2.0
 */
$cfg['grid.row.class'] = 'fw-row';


/**
 * Custom item widths for all builders
 */
add_filter( 'fw_builder_item_widths:page-builder', '_filter_theme_custom_page_builder_columns' );

if ( ! function_exists( '_filter_theme_custom_page_builder_columns' ) ) :

    function _filter_theme_custom_page_builder_columns($columns) {
        
        $columns['1_6'] = array(
            'title'             => '1/6',
            'backend_class'     => 'fw-col-md-2',
            'frontend_class'    => 'fw-col-xs-12 fw-col-md-2',
        );
        $columns['1_4'] = array(
            'title'             => '1/4',
            'backend_class'     => 'fw-col-md-3',
            'frontend_class'    => 'fw-col-xs-12 fw-col-md-3',
        );
        $columns['1_3'] = array(
            'title'             => '1/3',
            'backend_class'     => 'fw-col-md-4',
            'frontend_class'    => 'fw-col-xs-12 fw-col-md-4',
        );
        $columns['5_12'] = array(
            'title'             => '5/12',
            'backend_class'     => 'fw-col-md-5',
            'frontend_class'    => 'fw-col-xs-12 fw-col-md-5',
        );
        $columns['1_2'] = array(
            'title'             => '1/2',
            'backend_class'     => 'fw-col-md-6',
            'frontend_class'    => 'fw-col-xs-12 fw-col-md-6',
        );
        $columns['7_12'] = array(
            'title'             => '7/12',
            'backend_class'     => 'fw-col-md-7',
            'frontend_class'    => 'fw-col-xs-12 fw-col-md-7',
        );
        $columns['2_3'] = array(
            'title'             => '2/3',
            'backend_class'     => 'fw-col-md-8',
            'frontend_class'    => 'fw-col-xs-12 fw-col-md-8',
        );
        $columns['3_4'] = array(
            'title'             => '3/4',
            'backend_class'     => 'fw-col-md-9',
            'frontend_class'    => 'fw-col-xs-12 fw-col-md-9',
        );
        $columns['1_1'] = array(
            'title'             => '1/1',
            'backend_class'     => 'fw-col-xs-12',
            'frontend_class'    => 'fw-col-xs-12',
        );
        return $columns;

    }

endif;
`

**Comment by noesteijver** [comment]
I've found the solution.

I tried to add extra columns with a filter (https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/f57ebc5623407277f1c2d22365fe0a74cff22b36/helpers.php#L22-L24). But now I've added them in the array with default items. I didn't know this was possible.

Maybe this should be mentioned in the manual?

**Comment by andreiglingeanu** [comment]
@noesteijver Great! I thought it was a problem from our side with out [optimisations](https://github.com/ThemeFuse/Unyson/issues/1920#issuecomment-246719371).

<hr>

> Maybe this should be mentioned in the manual?

I'll happily review a pull request in this [repo](https://github.com/ThemeFuse/Unyson-Documentation), if you don't mind taking a couple of minutes to come up with one.
