### ISSUE TITLE
Can't add a column

### ISSUE THREAD

**Issue by JuniorJet** [ThemeFuse/Unyson#2102]
Visual Editor won't "Add Column" NOTHING happens when clicked. I can add rows fine, shouldn't have to be asking/posting this but %^&$* happens...

**Comment by thednp** [comment]
Do you have any console.log error? Perhaps some JS got scrambled during upload/update.

**Comment by moldcraft** [comment]
Hello @JuniorJet 

Please press in browser F12, go to Console tab, make a screenshot and post it here

**Comment by JuniorJet** [comment]
Tried again this morning and added a column no prob - must have been some kind of preview/cache glitch? No worries, thanks for the reply.

**Comment by moldcraft** [comment]
I don't know. Glad it works now
