### ISSUE TITLE
Add loop with counter or include custom text to title from custom extension

### ISSUE THREAD

**Issue by acze** [ThemeFuse/Unyson#2105]
How can i add custom title for each extension for example textarea in page builder view. For example if i have title of extenstion 'Textarea' i want to change it to 'Textarea $variable' and $variable should get title from input in this extension. Is it possible to make it easy? Maybe its possible with loop counter?
http://stackoverflow.com/questions/39977961/unyson-for-wordpress-add-extenstion-title-to-builder-list
Here is image i want to make first (orginal) example look like second.
I know how to make loop but where should i do it for this extension.

**Comment by moldcraft** [comment]
Hello,
I see you got [the answer](http://stackoverflow.com/a/39978497/1794248).

**Comment by acze** [comment]
Yeah thanks.
