### ISSUE TITLE
Multi upload not working inside popup

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2106]
Multi upload works correctly inside metabox, however inside popup it doesn't work.
What happens:

Everything works correctly except, when the page is saved and popup is opened. Multi option is empty, both in front-end and in backend ( visual and php code returns empty string).

What is interesting is that when the multi-upload is populated and popup is closed, and reopened again, **withouth** saving (reloading) the page. It has all selected options , and in correct order.
**Only** when the page/post gets **updated** (reloaded) multi-upload is empty inside the popup.

Image one:
First Multi upload inside the popup, second one inside the tab. 
![selection_004](https://cloud.githubusercontent.com/assets/390700/19281637/758b4e3e-8feb-11e6-86ad-af81c8eb44e9.png)

Image two:
Popup inside the multi-picker option.
![selection_003](https://cloud.githubusercontent.com/assets/390700/19281667/9d150ca6-8feb-11e6-86ca-9909f621ed8c.png)

WP:4.6.1
Unyson: 2.6.7

**Comment by moldcraft** [comment]
Hi,

I added in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/accordion/options.php`

```php
$options = array(
	'test' => array(
		'type' => 'multi-upload',
	),
	//...
);
```

and the images do not disappear after post save.

Please give the exact steps to reproduce the problem with code snippets.

**Comment by ivandotv** [comment]
'{theme}/framework-customizations/theme/options/posts'

    'project_section' => array(
        'type' => 'box',
        'title' => __('Project Section', '{domain}'),
        'options' => array(
            'popup_test' => array(
                'type' => 'popup',
                'value' => array(),
                'label' => __('POPUP TEST', '{domain}'),
                'popup-title' => __('Project asset popup title', '{domain}'),
                'button' => __('setup', '{domain}'),
                'size' => 'medium', // small, medium, large
                'popup-options' => array(
                    'images' => array(
                        'type' => 'multi-upload',
                        'label' => __('Images', '{domain}'),
                        'desc' => __('Choose images for the grid.', '{domain}'),
                        'images_only' => true
                    )
                )
            )
        ));

**Comment by moldcraft** [comment]
Please test Unyson latest dev version from Github. Also test if other popup and multi-upload options in other places work fine.

**Comment by ivandotv** [comment]
Everything works.
