### ISSUE TITLE
Pubslish/Update Buttons Not Showing

### ISSUE THREAD

**Issue by bitb98** [ThemeFuse/Unyson#2107]
I thought this might have been a theme issue, but I think it's a problem with Unyson (please correct me if I'm wrong).

In the past I've had issues with the "publish" button disappearing. I would go to fix something else, and when I came back to it a few hours later, it would reappear. This has happened several times now. This is only an issue now because while I was working on my page the publish button disappeared once again, and I can't afford to wait a few hours for it to fix itself.

I tried:

-Disabling and reactivating plugin
-Deleting and reactivating plugin
-Deleting active theme
-Disabling all plugins
-Deleting all plugins
-Deleting existing pages and media
-Different browser
-Clearing cache
-Reinstalling backup

Just to note, when I deleted pretty much everything from my site and reinstalled Unyson, it worked. Then when I activated "Page Builder" I had the same issues again. When I disabled "Page Builder" only, it worked, so I can only assuming this is a "Page Builder" issue.

Here is what I see in the source code:

<div id="publishing-action">
<span class="spinner"></span>
        <input name="original_publish" type="hidden" id="original_publish" value="Publish" />
        <input type="submit" name="publish" id="publish" class="button button-primary button-large" value="Publish"  /></div>

<div class="clear"></div>

I'm not sure why it's "hidden" or what could be causing this issue, so if you need any additional info, please let me know.

edit:

-I'm on WordPress v. 4.6.1 and Unyson  v 2.6.7
-I was messing with "Page Builder" settings and the issues only happens when "Blog" and/or "Pages" are activated.

edit 2:

Roughly 2 hours after reporting it shows up again.  It'll go away after some time, so still need help in getting a permanent fix.

**Comment by moldcraft** [comment]
Hello,

Sorry that you have spent so much time investigating this issue. The fastest solution would be to report the issue and send me your admin and ftp credentials to `moldcraft[at]email.com`.

Why we hide the Publish button: On slow servers it takes a few seconds until the builder is fully initialized, but some users click very fast on Publish button while the builder is not initialized and that causes content loss. It was noticed here https://github.com/ThemeFuse/Unyson/issues/647#issuecomment-215964026
So we decided to hide the Publish button until the builder is fully initialized.

How it works in code:

1. We add [an inline css in page head](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.6.6/includes/page-builder/class-fw-option-type-page-builder.php#L87-L94) to hide the Publish button (it has a html id attribute)
2. In javascript after the builder is fully initialized, that [inline css is removed](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.6.6/includes/page-builder/static/js/editor_integration.js#L215-L219)

You can debug the javascript to find out why it is not removed in your case, or send me your credentials.

**Comment by bitb98** [comment]
Ah that makes sense. I did notice the page builder didn't seem to fully load as well (the button to switch to the default editor was also missing as well). I was going to troubleshoot some more when I got home, but everything was back to normal and I got everything setup fine.

It seems to be an issue that pops up randomly and somehow fixes itself after waiting for a bit - which isn't always ideal.. Unfortunately, I don't know how to trigger this issue to show up again, so when you login and check around, everything might be back to normal, but I'll send some temp login details in the morning so you can check it out

Thanks for the quick and detailed response!
