### ISSUE TITLE
Event Extension

### ISSUE THREAD

**Issue by khangdoan03121993** [ThemeFuse/Unyson#2108]
I have a question. How do I turn the default options of Events extension off?

Thanks

![screenshot 1](https://cloud.githubusercontent.com/assets/15787361/19306157/851b792e-909e-11e6-9a03-883451be92f2.png)

**Comment by moldcraft** [comment]
There is a [filter](https://github.com/ThemeFuse/Unyson-Events-Extension/blob/80bcf56b44201e9a8d0ee7cedaf9eb47be59dbf7/class-fw-extension-events.php#L309) `fw_ext_events_post_options`.
