### ISSUE TITLE
Map Of Event Extension

### ISSUE THREAD

**Issue by khangdoan03121993** [ThemeFuse/Unyson#2109]
Map of event extension doesn't work? How do I solve this trouble? Thanks

![events-map-1](https://cloud.githubusercontent.com/assets/15787361/19312811/4c10680e-90be-11e6-9543-ea51c583a3d8.jpg)

![events-map-2](https://cloud.githubusercontent.com/assets/15787361/19312817/4f593766-90be-11e6-8d55-cdeb7965b4a3.jpg)

**Comment by moldcraft** [comment]
Hi,

Have you [configured](https://github.com/ThemeFuse/Unyson/issues/1899#issuecomment-250143028) the Google Maps API Key?

**Comment by khangdoan03121993** [comment]
I fixed the trouble. Thank you so much!
