### ISSUE TITLE
image-picker width limit

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#211]
Can we please get the max width set for this option like you have for background option 
http://screencast.com/t/CFtAgo0J2S

Currently it looks like this 
http://screencast.com/t/IcGT74I6

**Comment by moldcraft** [comment]
```php
array(
	'type' => 'image-picker',
	'attr' => array(
		'class' => 'fw-backend-option-fixed-width',
	),
	...
)
```

**Comment by danyj** [comment]
thank you!
