### ISSUE TITLE
Full width shortcode

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson#2111]
Hello , 

thanks for great fw. 

I am trying to crate a full width shortcode. Read this issue #455 and added the config.php file in extenstions/page-builder . That removed the wrapping collumn but padding from `fw-container-fluid` still persists as you see in screenshot.
What I do in dashboard : add a section, set it as full width. Drag my shortcode in that section.

My fixes would be :

* add `fw-row` to my shortcode main div
* add margin -15px to my shortcode main div

Are there any other reasonable fixes for this ?

Thanks.
![home](https://cloud.githubusercontent.com/assets/3755796/19344962/011243f4-9145-11e6-8ad5-8e71b5e08159.png)

**Comment by moldcraft** [comment]
Hello,

We are glad you like it.

I know only these solutions:

* If you need some changes in grid css, [overwrite it](http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid).
* If you need some special behavior for section shortcode, [overwrite](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes) its options and view.

> but padding from fw-container-fluid still persists

Can you find out why?

You are talking about [this 15px padding](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/3fc599a94b7607088ed684335b97d827ddb2d422/static/css/frontend-grid.css#L124-L130)?

**Comment by toleabivol** [comment]
Yes, that padding.
Let me reformulate the question : how would you do a full width section with a new shortcode (created in `fc/extensions/shortcodes/shortcodes/new_shortcode/`) using unison's page-builder ?

**Comment by moldcraft** [comment]
If you place a shortcode in page-builder on first level (not inside section > row) it will be automatically wrapped in section>row by [this corrector](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/includes/page-builder/includes/items-corrector/class-page-builder-items-corrector.php#L204-L230). As you can see, it doesn't do the correction of the shortcode has set `$cfg['page_builder']['disable_correction'] = true;`

**Comment by toleabivol** [comment]
:astonished: that works ! 
Tried that first but without disabling correction and it didn't work.
Thanks for pointing out.
