### ISSUE TITLE
Can we please have usable reset/save functions

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2112]
The idea of framework is to have specific functions/classes/markups in order to build on it. We have MANY useful things in Unyson but is beyond me why we dont have 2 main things and why are they hardcoded and mixed with bunch of alerts and warnings. 

https://github.com/ThemeFuse/Unyson/blob/46e919faeada2eb654baaa4757bafd6a3acf5c37/framework/views/backend-settings-form.php#L200

just like we have modals , builders ,fw.events  we also need clean save and reset theme options functions like 

    fw_save_theme_options();
    fw_reset_theme_options();

without any alerts and modals. 

I would like to use it like 

	$(document).on("click", 'some_button', function(e, status) {
		
		fw_reset_theme_options();
		
	});
	
	$(document).on("click", 'some_button', function(e, status) {
        
		fw_save_theme_options();
		
	});

currently if I do 

      $('.submit-button-save').trigger('click');	
      $('.submit-button-reset').trigger('click');

I get bunch of alerts and modals.  or I am forced to initiate all tabs, set timeouts  and think of thousand ways to do those 2 simple tasks. Save and reset !

Instead we have to build those on our own and cant ever be sure that they will be ok or that some Unyson change might brake them .  

Utilizing core save/reset functions would helps us and will set standard that we can build on.

**Comment by andreiglingeanu** [comment]
[That's](https://github.com/ThemeFuse/Unyson/blob/f821fabed94cfd66eee16392b2b5cc9cce7e4ffa/framework/static/js/fw-form-helpers.js#L139) what helped me when I was fiddling around with Theme Settings. I gave up the idea of making Theme Settings a monster and I moved some of my options onto other page - which was a great idea, I really didn't wanted to fiddle around with this form submit mechanism.

**Comment by danyj** [comment]
> Pull requests welcome ; 

Yes but what if you dont know what the proper way is , especially by looking at that code my head is spinning. Year ago I asked about silent save https://github.com/ThemeFuse/Unyson/issues/360
which worked until lazy_tabs came , now I have to initiate all tabs, combine with timeouts and so on. 

I ask for these 2 to be built by someone who knows Unyson in and out and can think of all possible options that are needed for these functions.  I tried on my own but like said I am not 100% sure that this is the way and since this is a framework it should have those mechanisms in place already.

**Comment by danyj** [comment]
@andreiglingeanu  , 

>That's what helped me

and just like always ,  we get shown a  line to look at and than think around what/how/why ,  you know i'm not lazy when it comes to building my own scripts , but core functionalities should be in already especially in framework that is 2 years old and we should not try to build some magic functions for base form tasks.

**Comment by danyj** [comment]
@moldcraft  what do you think bud? will be able to help with this?

**Comment by moldcraft** [comment]
I haven't investigated this yet. I don't have any eta.

**Comment by moldcraft** [comment]
I have create the `FW_Settings_Form` [class](https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/class-fw-settings-form.php) and migrated [Theme Settings](https://github.com/ThemeFuse/Unyson/blob/a0fc5ffdadc711d9d2f487dd65b6d74cf5b31524/framework/core/components/backend/class-fw-settings-form-theme.php) on it.

### How to create your Settings Options page

1. Extending the `FW_Settings_Form` class. Create `{theme}/class-fw-settings-form-test.php`:

    ```php
    <?php if (!defined('FW')) die('Forbidden');

    class FW_Settings_Form_Test extends FW_Settings_Form {
    	public function get_values() {
    		return get_option('test_fw_settings_form', array());
    	}
    
    	public function set_values($values) {
    		update_option('test_fw_settings_form', $values, false);
    	}
    
    	public function get_options() {
    		return array(
    			'tab1' => array(
    				'type' => 'tab',
    				'title' => 'Tab #1',
    				'options' => array(
    					'opt1' => array(
    						'type' => 'text',
    						'label' => 'Option #1'
    					),
    					'opt2' => array(
    						'type' => 'textarea',
    						'label' => 'Option #2'
    					),
    				),
    			),
    			'tab2' => array(
    				'type' => 'tab',
    				'title' => 'Tab #2',
    				'options' => array(
    					'tab2_1' => array(
    						'type' => 'tab',
    						'title' => 'Sub Tab #1',
    						'options' => array(
    							'opt2_1' => array(
    								'type' => 'text',
    								'label' => 'Sub Option #1'
    							),
    						),
    					),
    					'tab2_2' => array(
    						'type' => 'tab',
    						'title' => 'Sub Tab #2',
    						'options' => array(
    							'opt2_2' => array(
    								'type' => 'textarea',
    								'label' => 'Sub Option #2'
    							),
    						),
    					),
    				),
    			),
    		);
    	}
    
    	protected function _init() {
    		add_action('admin_menu', array($this, '_action_admin_menu'));
    		add_action('admin_enqueue_scripts', array($this, '_action_admin_enqueue_scripts'));
    
    		$this->set_is_side_tabs(true);
    		$this->set_is_ajax_submit(true);
    	}
    
    	/**
    	 * @internal
    	 */
    	public function _action_admin_menu() {
    		add_menu_page(
    			'Test FW Settings Form',
    			'Test FW Settings Form',
    			'manage_options',
    			/** used in @see _action_admin_enqueue_scripts() */
    			'test-fw-settings-form',
    			array($this, 'render')
    		);
    	}
    
    	/**
    	 * @internal
    	 */
    	public function _action_admin_enqueue_scripts() {
    		$current_screen = get_current_screen(); // fw_print($current_screen);
    
    		// enqueue only on settings page
    		if ('toplevel_page_'. 'test-fw-settings-form' === $current_screen->base) {
    			$this->enqueue_static();
    		}
    	}
    }
    ```

2. Include and initialize your class. Add in `{theme}/functions.php`:

    ```php
    add_action('fw_init', '_action_theme_test_fw_settings_form');
    function _action_theme_test_fw_settings_form() {
    	if (class_exists('FW_Settings_Form')) {
    		require_once dirname(__FILE__) . '/class-fw-settings-form-test.php';
    		new FW_Settings_Form_Test('test');
    	}
    }
    ```

**Comment by moldcraft** [comment]
@danyj Let me know if this is enought or you still need

```
fw_save_theme_options();
fw_reset_theme_options();
```

**Comment by danyj** [comment]
What you made is **very** usable and solves other issue , but I dont see how that solves this  issue. I need  those 2 js functions  in js files  used in some of the theme options so that I dont have to make something that might end up being incompatible with future updates which already happened  once the lazy_tabs were introduced.

**Comment by andreiglingeanu** [comment]
@moldcraft Maybe listen onto every `FW_Settings_Form`'s `form` html element a custom event `fw:settings-form:silent-submit`?

**Comment by moldcraft** [comment]
@danyj 

1. Save

    ```js
    var $form = jQuery('form[data-fw-form-id="fw-settings-form:theme-settings"]:first');

    jQuery.ajax({
        url: ajaxurl,
        method: 'post',
        dataType: 'json',
        data: $form.serializeArray()
    }).done(function(r){
        console.log(r.success);
    }).fail(function(x,y,error){
        console.error(String(error));
    });
    ```

2. Reset

    ```js
    var $form = jQuery('form[data-fw-form-id="fw-settings-form:theme-settings"]:first');

    jQuery.ajax({
        url: ajaxurl,
        method: 'post',
        dataType: 'json',
        data: jQuery.merge(
            $form.serializeArray(),
            // add Reset button
            // https://github.com/ThemeFuse/Unyson/blob/a0fc5ffdadc711d9d2f487dd65b6d74cf5b31524/framework/helpers/class-fw-settings-form.php#L272
            [{
                'name': $form.find('.fw-settings-form-reset-btn:first').attr('name'),
                'value': 'true'
            }]
        )
    }).done(function(r){
        console.log(r.success);
    }).fail(function(x,y,error){
        console.error(String(error));
    });
    ```

I don't think we need functions for these. Ajax form submit via jQuery is always

```js
jQuery.ajax({ ..., data: $form.serializeArray() })....
```

**Comment by sattar3001** [comment]
> @danyj Let me know if this is enough or you still need
> 
> ```
> fw_save_theme_options();
> fw_reset_theme_options();
> ```
