### ISSUE TITLE
WordPress Shortcodes in editor small modal bug

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2113]
Shortodes inside editors when clicked, open small modal even if shortcode popup_size is set to be large or medium.

**Comment by danyj** [comment]
anything on this?

**Comment by andreiglingeanu** [comment]
https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/commit/6c900fa306d73c384c13d35a619378bab14a55b9

**Comment by danyj** [comment]
confirmed fix , thnx!
