### ISSUE TITLE
Whats the best way to handle built-in WooCommerce shortcodes? 

### ISSUE THREAD

**Issue by sunnyville** [ThemeFuse/Unyson#2115]
Hi, 

I'm creating a premium theme that supports WooCommerce, and I am just lost at how I should handle the built in shortcodes that WooCommerce provides like [recent_products] or [add_to_cart].

I really want to provide these shortcodes in the Page Builder, but I have no idea how I can do that and the only two ways that I can think of are:

1. Let the user paste in the shortcodes into a 'Text Block', with the attributes. (Lame!)
2. De-register the built-in shortcodes and create custom shortcodes, perhaps with the same names, and create options and views for them as I normally would.

I would like to do it the second way, as I would be able to add-to or remove the default options (or attributes), but I'm not sure if this is the right way to do it.

Please let me know about this.
Thanks!

**Comment by duongancol** [comment]
Yes you should create custom shortcodes
