### ISSUE TITLE
Demo install hooks

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2116]
Are there any demo install hooks that we can use like install start and install end ?
I need to clean file logs after the demo install has finished like. 

    add_action( 'fw_demo_install_done', 'thz_clear_files_log' );

**Comment by moldcraft** [comment]
> install has finished

1. https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/c82006b5b1c14c3bc0b7ac5455eb8d0aa968fba0/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L342
2. https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/c82006b5b1c14c3bc0b7ac5455eb8d0aa968fba0/extensions/backups-demo/class-fw-extension-backups-demo.php#L56

or

https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/c82006b5b1c14c3bc0b7ac5455eb8d0aa968fba0/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L346

Also the user can do Abort

https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/c82006b5b1c14c3bc0b7ac5455eb8d0aa968fba0/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L951


> install start

I can add an action in [this method](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/c82006b5b1c14c3bc0b7ac5455eb8d0aa968fba0/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L725)

**Comment by danyj** [comment]
something simpler would be preferred since I dont know what collection is or how to get i'ts ID

**Comment by moldcraft** [comment]
* Demo finish (can be success or fail)

    ```php
    add_action('fw:ext:backups:tasks:finish:id:demo-content-install', ...);
    ```

* Demo success

    ```php
    add_action('fw:ext:backups:tasks:success:id:demo-content-install', ...);
    ```

* Demo abort

    ```php
    add_action('fw:ext:backups:tasks:cancel:id:demo-content-install', ...);
    ```

* Demo start

    There is no such action. If you need it, let me know.

**Comment by danyj** [comment]
Demo start , I dont know about other but I could have a use for it to set adjust some theme options when demo install has started , send a hook like magazine install start etc..

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/a77ad0534112e20db09a2e39278e3a1c9ec4365b

```php
add_action('fw:ext:backups:tasks:start:id:demo-content-install', ...);
```
