### ISSUE TITLE
Any way to install available extensions when unyson plugin install  ?

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#2117]
Hello
Is it possible to install all extensions when unyson plugin install our theme ? 

Now some clients confused and they just install unyson plugin and tried to install demo content. and after they contact support they dont find demo content installation menu on tools section.

So it will be perfect if when unyson plugin install auto extension will be install on site.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/07be8b1f4b50eaf0f1f7e85ea1c6912a0415d241#diff-199eb92d43a1633a67f9557c84467866R3456

**Comment by danyj** [comment]
I think ( looking for the post ) we are not allowed to do this becuase of TF 

 > In order for this to work, int TGM config must be set: 'is_automatic' => true

again , I am not sure , I know that there was some kind of restriction about it. Digging.

**Comment by xperter** [comment]
Works perfect. 

@Dan We already using  TGMPA `'is_automatic'=> true,`  feature in our theme. It Shouldn't  be issue in theme review process.

**Comment by danyj** [comment]
> It Shouldn't be issue in theme review process.

I am not sure which one it is cant find it ,  one of the TGM settings does not sit well with TF.

**Comment by Ataurr** [comment]
`force_activation` and '`force_deactivation' => true`, not allwoed in TF
