### ISSUE TITLE
Section Copy One Page To Another Page

### ISSUE THREAD

**Issue by UxLabByNinja** [ThemeFuse/Unyson#2118]
Hi, I have seen there is no option to copying one section to another page. Will we get that option in near future or not?

**Comment by thednp** [comment]
You can save sections as templates, then use the templates on other pages. Simple.

**Comment by andreiglingeanu** [comment]
> then use the templates on other pages

Please let us know if templates are working reliably, there was some issues going around this feature, thanks.

**Comment by thednp** [comment]
I believe the issues pop when the options structure are changed after saving the template. But I haven't tried the feature, but will eventually run into it very soon and I will prepare a detailed report.

**Comment by andreiglingeanu** [comment]
> I believe the issues pop when the options structure are changed

Interesting edge case. Frankly, I've not really got into how this feature works and _don't_ use it internally, we replaced it with our proprietary implementation, which kinda should cover this edge case.

I just wanted to make sure that by old changes didn't broke something by accident.

**Comment by onebelarusianguy** [comment]
I'm too lazy, so I wrote some stuff to save it automatically :D

**Comment by danyj** [comment]
@onebelarusianguy  

>, so I wrote some stuff to save it automatically

dont be like that , share the cookies :)

**Comment by onebelarusianguy** [comment]
@danyj I'm not sure that it will be suitable for everyone, cuz it's not really automatically: you should go to console, call the function, make a tea. Aaand it assumes that you have some page with all sections to save. Also naming is not much intellectual :D if you still interested, I'll share it when I'll be at PC

**Comment by danyj** [comment]
>  make a tea.
love it. sure share maybe we can together  come up with something usable for everyone.

**Comment by onebelarusianguy** [comment]
> make a tea.

> love it.

My favorite part too.

Well, keep in mind that it will erase all of your current saved _section_ templates.

```
/**
 * Save Shortcode Templates
 * @author Pavel Marhaunichy
 */
function saveTemplates() {
	var templatesBtn = document.querySelector('.template-btn'),
		templatesSections,
		templatesSectionTitle,
		templatesSectionItems;

	templatesBtn.click();
	//delay to show data
	setTimeout(function () {
		templatesSections = document.querySelector('.fw-builder-templates-type[data-type="section"]');
		templatesSectionTitle = templatesSections.querySelector('.fw-builder-templates-type-title');
		templatesSectionItems = templatesSections.querySelectorAll('li');

		//clean current data
		for (var i = 0; i < templatesSectionItems.length; i++) {
			templatesSectionItems[i].querySelector('[data-delete-template]').click();
		}

		var sections = document.querySelector('.builder-items').children, //1st level items only
			shortcodeNames = [],
			saved = [],
			n = 1;

		for (var i = 0; i < sections.length; i++) {
			//you can rewrite this part depending on your needs

			//retrieve only 1st item
			//and exclude parallax shortcode name if its not the only one shortcode in section
			var shortName = sections[i].querySelectorAll('.pb-item-type-simple')[0].textContent.toLocaleLowerCase() === 'parallax' && sections[i].querySelectorAll('.pb-item-type-simple')[1] ? sections[i].querySelectorAll('.pb-item-type-simple')[1] : sections[i].querySelector('.pb-item-type-simple');

			shortcodeNames.push(shortName);
		}

		var j = 0,
			interval = setInterval(function () {
				if (j < sections.length) {
					loop(j);
					j++;
				} else {
					clearInterval(interval);
					return;
				}
			}, 1000);

		function loop(i) {

			//click save icon
			sections[i].querySelector('.fw-shortcode-section-save').click();

			var name = shortcodeNames[i].textContent + '-' + n;


			if (!saved.length) {
				//push 1st time
				saved.push(name);
			} else {
				saved.forEach(function (item) {
					if (item === name) {
						n++;
						name = shortcodeNames[i].textContent + '-' + n;
					}
				});

				name = shortcodeNames[i].textContent + '-' + n;
				saved.push(name);
				n = 1;
			}


			//need delay again
			setTimeout(function () {
				document.getElementById('fw-edit-options-modal-template_name').value = name;
				//save this
				document.querySelector('.media-modal-content').querySelector('.button-primary').click();
			}, 400);

		}

	}, 500);
}
window.saveTemplates = saveTemplates;
```

**Comment by danyj** [comment]
> Well, keep in mind that it will erase all of your current saved section templates.

thnx for heads up
