### ISSUE TITLE
How to add additional font-family to typography option?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#212]
How can we add additional font-family to this  option?
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography/class-fw-option-type-typography.php#L22

I am trying to do font-family combos like 
"Helvetica Neue", Helvetica, Arial, sans-serif

note: you have a typo here , 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography/class-fw-option-type-typography.php#L29

should be Tahoma

**Comment by valeriuzdrobau** [comment]
I added the filter 'fw_option_type_typography_standard_fonts', now you can add standard fonts in the following way: ```php <?php function your_theme_slug_push_typography_standard_fonts( $fonts ) {
	array_push( $fonts, "'Helvetica Neue', Helvetica, Arial, sans-serif" );
	return $fonts;
}
add_filter( 'fw_option_type_typography_standard_fonts', 'your_theme_slug_push_typography_standard_fonts' );  ```

**Comment by danyj** [comment]
:+1: great , can I completely rebuild the standards array or only add?

**Comment by moldcraft** [comment]
you can rebuild

**Comment by grek84805** [comment]
Друзья всем привет я начинающий разработчик, сейчас разрабатываю тему для WordPress  с помощью плагина unyson подскажите как подключить шрифты на body , ?
