### ISSUE TITLE
Can addable option print associative array?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2121]
Is there any way  for addable option to print associative array? 

Current print does this 

```
array
(
    [0] => '#454545'
    [1] => '#40b1e2'
    [2] => '#ffb401'
)
```

I need 

```
array
(
    [color_1] => '#454545'
    [color_2] => '#40b1e2'
    [color_3] => '#ffb401'
)
```

**Comment by andreiglingeanu** [comment]
We won't change core option types behavior - especially their output structure. 

Please write a function that does this transformation and call it whenever you need to.

**Comment by danyj** [comment]
@andreiglingeanu  I did not ask for a change. 
I asked a question. Take it easy and stop assuming the worst.

**Comment by andreiglingeanu** [comment]
> stop assuming the worst

It is a good practice to assume the worst in most cases :)

<hr>

aside from this, most obvious way to make your change:

```php
function my_helper($input) {
  $result = array();

  $i = 0;
  foreach ($input as $color){
    $result['color_' . ($i++)] = $color;
  }

  return $result;
}

```

**Comment by danyj** [comment]
thank you!
