### ISSUE TITLE
[bug] Hitting enter in input triggers theme options save

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2123]
Place cursor inside input box , hit enter , options save is triggered.

**Comment by thednp** [comment]
That's the default forms behavior.

**Comment by danyj** [comment]
> That's the default forms behavior.
implicit submission should not be done in theme settings especially if ajax submit is enabled. 
save options click is there to fire it

**Comment by andreiglingeanu** [comment]
That's how forms behave, no matter what's the saving strategy, be it AJAX or regular full POST request.
