### ISSUE TITLE
FA icons script is wrong

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2124]
This , https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon/README.md

gives back 730 icons , I checked FA yaml and the count is 634

**Comment by andreiglingeanu** [comment]
@danyj I bet the DOM structure for font awesome website was changed. Can you show me an example of a JSON structure of what the first version of the `icon` option type expects?

I may be able to come up with a better script for getting those icons.

<hr>

You still forced to use first version of icon picker?

**Comment by danyj** [comment]
glass , http://prntscr.com/cv9p2r

**Comment by danyj** [comment]
> JSON structure of what the first version of the icon option type expects

you lost me.  I am not using it for Unyson icon type, I needed something to collect just icon names and was testing that script.

**Comment by andreiglingeanu** [comment]
Use [this](https://github.com/ThemeFuse/Unyson/blob/v2.6.7/framework/includes/option-types/icon-v2/includes/class-fw-icon-v2-packs-loader.php#L214-L266) as a blueprint. You basically can pass a long CSS to it and it'll come back with an array of icon names. 

That's all I can help you with, maybe someone can come up with a PR that will fix that script.

**Comment by danyj** [comment]
@andreiglingeanu  thnx , was looking at that one also but needed something fast onsite copy/paste , will try yours now.

**Comment by andreiglingeanu** [comment]
Re-open if you find some problem with my script from `icon-v2`.

**Comment by danyj** [comment]
yours works 634 , I redid it to be used  outside Unyson if needed 


	<?php
	
	function icons_list() {
			
			
		$icon_list = array();
		
		$icon_packs = array(
		
			'font-awesome' => array(
				'css_class_prefix' => 'fa',
				'css_file_uri' => 'https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css',
			)	
	
		);
		
		
		
		
		foreach ($icon_packs as $pack_name => $pack) {
	
			$css = file_get_contents(
				$pack['css_file_uri']
			);
			$parser_matches = array();
			preg_match_all(
				'/(?ims)([a-z0-9\s\,\.\:#_\-@]+)\{([^\}]*)\}/',
				$css,
				$parser_matches
			);
			foreach ($parser_matches[0] as $i => $x) {
				$selector = trim($parser_matches[1][$i]);
				$value = trim($parser_matches[2][$i]);
				$is_correct_prefix = substr(
					$selector, 0,
					strlen('.' . $pack['css_class_prefix'])
				) === '.' . $pack['css_class_prefix'];
				$is_with_pseudo_element = is_numeric(strpos($selector, ':'));
				$has_content_for_pseudo = is_numeric(strpos($value, 'content'));
				/**
				 * It's probably an icon definition at this point.
				 */
				$selector_is_icon = $is_correct_prefix &&
									$is_with_pseudo_element &&
									$has_content_for_pseudo;
				if ($selector_is_icon) {
					$icon = explode(':', ltrim($selector, '.'));
					$icon = $icon[0];
					$icon_list[] = $icon;
				}
			}
		}
		
		return $icon_list;
			
	}
	
	print_r( icons_list() );

**Comment by andreiglingeanu** [comment]
Great!
