### ISSUE TITLE
Unyson as a part of a theme

### ISSUE THREAD

**Issue by xcoded** [ThemeFuse/Unyson#2125]
Hi!

Is it possible to build a theme and Unison as a part of a theme and sell it f ex in the Themeforest?

Br, 

Eeva

**Comment by thednp** [comment]
You don't need to include the framework inside your theme, it makes updates terrible.

**Comment by xcoded** [comment]
Sorry I am a newbe, but can I build a theme with help of the plugin?

**Comment by thednp** [comment]
Boy you sure can, http://manual.unyson.io/en/latest/

**Comment by xcoded** [comment]
Hi, I will check the manual. Thank You very much for Your help.
