### ISSUE TITLE
How to translate Theme Options?

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2127]
I'm building a multilingual theme. For this theme I've made several theme options.  Some of them don't require translation, like social media url's. But some of the theme options do require translation, like intro texts for post types.

What I can do is make the same theme options for every language. But that doesn't seem like the nicest way to do this. 

Is there a nicer way to make these options translatable? What are my options?

**Comment by onebelarusianguy** [comment]
Framework does nothing with this. You should use `__()` or other functions and act in accordance with the WordPress Codex

**Comment by noesteijver** [comment]
@onebelarusianguy one of my options is a WP Editor. So I can't really use a simple string translation on that? Or is there a way I don't know of?

**Comment by onebelarusianguy** [comment]
@noesteijver  What do you want to translate?
```
	'text' => array(
		'type'   => 'wp-editor',
		'teeny'  => true,
		'reinit' => true,
		'label'  => __( 'Content', 'domain-text' ), // these lines are
		'desc'   => __( 'Enter some content for this text block', 'domain-text' ) // translatable in your theme options
	),
```
You can't translate editor output

**Comment by noesteijver** [comment]
@onebelarusianguy I'm looking for a way to translate the editor output..

I'll figure something out, thanks!

**Comment by thednp** [comment]
@noesteijver most translation plugins rely on specific attributes 
```php 
'attr'  => array('class' => 'custom-class', 'data-foo' => 'bar'),
```
Now for each textarea, textbox, wp-editor option you can give it a translation plugin specific attribute to target it for multi-language content.

**Comment by moldcraft** [comment]
Hello,

I don't know how to do that and I don't think it is related to Unyson.
