### ISSUE TITLE
Get option ID inside the builder item extend

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2128]
@moldcraft  @andreiglingeanu 

I used this https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/form-header-title/class-fw-option-type-form-builder-item-form-header-title.php

as template for one option and I need to get the actual option ID that is initiating the type 

```
'this_is_my_id' => array(
    'label' => false,
    'type'  => 'thz-list-builder'
),
```

in that file I am trying to get the   `this_is_my_id`,  I cant find any reference in those extends.  Thnx!

**Comment by danyj** [comment]
Preferably inside this method 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/form-header-title/class-fw-option-type-form-builder-item-form-header-title.php#L57


since I need to remove some options if specific ID is called

**Comment by moldcraft** [comment]
The most stupid/simple solution is to set/duplicate that id as array parameter

```php
'this_is_my_id' => array(
    'label' => false,
    'type'  => 'thz-list-builder',
    'data-id' => 'this_is_my_id',
),
```

`get_options()` is a private method not part of the API, it is called many times in that class and it will be hard to implement what you have request.

**Comment by danyj** [comment]
>  id as array parameter

that can be used for JS only , but I need it in the method that prints the options , and that s very tricky since the builder is "reading" the options from the localize.options. I tried making  double sets of options but than this one 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/form-header-title/class-fw-option-type-form-builder-item-form-header-title.php#L74

is bringing them back. 

it is very hard since the options are trown  around in the class and enques_static method does not have any attributes. At the end I  was forced to duplicate the option. 

what would help tremendously is this 

	'this_is_my_id' => array(
		'label' => false,
		'type'  => 'thz-list-builder',
		'optionsset'  => 'path_to_set'
	),
instead of this 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/form-header-title/class-fw-option-type-form-builder-item-form-header-title.php#L58
