### ISSUE TITLE
Ecommerce solution thats compatible

### ISSUE THREAD

**Issue by nuGzo** [ThemeFuse/Unyson#2130]
Is there an ecommerce plugin that is compatible with unyson? I've tried woocommerce, but it seems its not compatible with unyson

**Comment by danyj** [comment]
Woo is 100% compatible with Unyson on my end. What is the issue you have?

**Comment by nuGzo** [comment]
Sorry, my mistake. The theme i had originally gotten did not have initial support for woocommerce. I have now modified it to make it compatible
