### ISSUE TITLE
Constant error messages while trying to edit

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#2131]
Hello,

I get constant error messages while trying to edit homepage’s section Package Gallery – ‘error’ or ‘unknown error’ (see attachment). How can we solve this?

I’m using Safari under MacOS 10.12.

My site URL : http://www.quintasantonio.com

Regards
anisur210

**Comment by moldcraft** [comment]
Hello,

Please inspect ajax server response using browser developer tools, also check error.log, or send me your admin and ftp credentials to `moldcraft[at]email.com`

**Comment by anisur210** [comment]
Hi

I have sent your email.

**Comment by moldcraft** [comment]
On my side everything works fine `/wp-admin/post.php?post=115&action=edit` https://vid.me/AaDQ

**Comment by thednp** [comment]
I think you're getting error because your session expired.
