### ISSUE TITLE
Portfolio random order

### ISSUE THREAD

**Issue by t4bbo** [ThemeFuse/Unyson#2132]
Hi there,

trying to display portfolio list items ordered by random.
The best way would be a button in the backend plugin to set the orderby argument.
Quick and dirty would be to hardcode it into an template file.
I can't get neither of both to work.

Any suggestions on how to get it to work?

Best

Philipp

**Comment by moldcraft** [comment]
Hello,

Portfolio is just an post type. You can use WordPress hooks to change the query (google it).
And you can add a [post option](http://manual.unyson.io/en/latest/options/introduction.html#options-files) (switch) to enable Random mode and change the wp query based on its value.

**Comment by t4bbo** [comment]
Sorry to revoke this threat.
i still need a little help here. 
Can't find the loop query where i can put in the orderby => rand...
Any suggestions? Not in the .../the-core-child/framework-customizations/extensions/portfolio/views/archive.php nor in the specific loop-styleX.php

Greets

Philipp
