### ISSUE TITLE
Problem with events extension

### ISSUE THREAD

**Issue by charlesjohn2004** [ThemeFuse/Unyson#2135]
![capture](https://cloud.githubusercontent.com/assets/12762009/19557343/e608a3de-96e2-11e6-90c2-9b9b5b45a003.PNG)

Hi,
How do one add the location? Is that by entering the cordinates or adding the address? Both ways didn't work for me? Also the map freezes when I try to zoom. is this a known issue? pls check - http://www.outcrafter.com/graha2/events/open-house-11953-dorothy-st-los-angeles-ca-90049/

Thanks,
Charles

**Comment by moldcraft** [comment]
It looks like you have js errors and options are not initialized (that checkbox must be switch option). Please check browser console and show us a screenshot. Also try to disable all plugins except Unyson.
