### ISSUE TITLE
Getting 'cURL error 28' when I try to install extensions

### ISSUE THREAD

**Issue by jsrothwell** [ThemeFuse/Unyson#2137]
Hi,

Im trying to install the extensions to a new copy of Unyson. I am getting a cURL error 28 whenever I try to download the Page Builder and its throwing up all sorts of errors about other extensions like mailer and forms not being activated.

**Comment by duongancol** [comment]
Hi! The same problem here.

**Comment by jsrothwell** [comment]
Looks like it was the bit DDOS attack this morning. Just got the extensions to upload at noon PST.

**Comment by andreiglingeanu** [comment]
Right. Everyone had problems with GitHub powered services today.
