### ISSUE TITLE
Issue on Unyson 

### ISSUE THREAD

**Issue by LuqueASZ** [ThemeFuse/Unyson#2138]
Hi,

My name is Luque, from Spain.

I've Unyson installed on my wordpress site. From many months ago, I'm not able edit contents. The page builder Unyson doesn't wok. See attached image please
![image](https://cloud.githubusercontent.com/assets/20113124/19645993/c9e3bd16-99f7-11e6-9669-f50282cc4946.png)

Thanks and regards,

**Comment by moldcraft** [comment]
Hello,

1. Make sure Unyson plugin and Unyson Extensions are up-to-date (go to **Dashboard > Updates** and press the **Check Again** button)
2. Open browser console (F12) and check for javascript errors. If there are some, please show us the screenshot

**Comment by sandrodz** [comment]
having same issue?

![14795701_978674722244600_1897452139_o](https://cloud.githubusercontent.com/assets/8479569/19647356/c4dc3854-9a0e-11e6-87cd-cce25f16afa4.jpg)

**Comment by moldcraft** [comment]
@sandrodz Same steps https://github.com/ThemeFuse/Unyson/issues/2138#issuecomment-255736134

**Comment by LuqueASZ** [comment]
Hi moldcraft. Thank you for your help!

Here you are the screenshot. There are many javascript error after having refresh the Unyson plugin.

Thanks, and regards.

![image](https://cloud.githubusercontent.com/assets/20113124/19648559/b26c9648-9a02-11e6-925a-7ec6093fc5dc.png)

**Comment by moldcraft** [comment]
@LuqueASZ Inspect page html and try to find the cause of the problem, or send me your admin and ftp credentials to `moldcraft[at]email.com` and I will do that myself

**Comment by LuqueASZ** [comment]
Hi. i've sent you an email.

Thanks, and regards.

**Comment by moldcraft** [comment]
There is a plugin or server configuration that doesn't allow some javascript files to be loaded. When I try to access this url

```
http://{SITE}/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/includes/item-types/simple/static/js/scripts.js?ver=1.6.7
```

it does redirect to

```
http://{SITE}/?ver=1.6.7
```
