### ISSUE TITLE
When installing the module "breadcrumbs" site stops working

### ISSUE THREAD

**Issue by Maxim850** [ThemeFuse/Unyson#2139]
`When installing the module "breadcrumbs" site stops working
`Instead of white page site with an error type:
Parse error: syntax error, unexpected T_FUNCTION in /home/xxxxx/xxxx/xxxxx/public_html/wp-content/plugins/unyson/framework/extensions/breadcrumbs/includes/class-breadcrumbs-builder.php on line 279
The problem is solved only by removing the plugin folder.

**Comment by moldcraft** [comment]
Please [download this version](https://github.com/ThemeFuse/Unyson-Breadcrumbs-Extension/releases/tag/v1.0.14) and extract in `unyson/framework/extensions/breadcrumbs` and test it. Let me know if it works and I will publish  live the new version asap.

**Comment by Maxim850** [comment]
Thank you friend! The site earned. But now there is a new error when you click on the "Installation" breadcrumbs. Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in / home / xxx / xxx / dimage / xxx / public_html / wp-content / plugins / unyson / framework / core / components / extensions / manager / includes /parsedown/Parsedown.php on line 1479

**Comment by moldcraft** [comment]
@Maxim850 I have made the fix https://github.com/ThemeFuse/Unyson/commit/bd975222ef4fee06f1adb0ad87b37020fd8050e1 it will be available in the next Unyson version
