### ISSUE TITLE
After Unyson update, something missing

### ISSUE THREAD

**Issue by paul-fan** [ThemeFuse/Unyson#2140]
After the Unyson update, my wordpress editior seems someting wrong, it is not display anything on the editior...
![image](https://cloud.githubusercontent.com/assets/22587674/19652281/cd918ee8-9a42-11e6-9cce-99f9bcc2e255.png)

![image](https://cloud.githubusercontent.com/assets/22587674/19652346/07a64420-9a43-11e6-9a72-f1f2cb152bd1.png)

Please advise

Best Regards
Paul

**Comment by moldcraft** [comment]
Please open the Console tab (on the right) and make a screenshot again.

**Comment by paul-fan** [comment]
here you go
![image](https://cloud.githubusercontent.com/assets/22587674/19653023/8620d796-9a45-11e6-97c9-64f019a431e3.png)

**Comment by paul-fan** [comment]
additional screen cap
![image](https://cloud.githubusercontent.com/assets/22587674/19653075/b4c2a4a8-9a45-11e6-9b7e-61e09c58d3f4.png)

**Comment by moldcraft** [comment]
Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by paul-fan** [comment]
send! thanks for the investigation

**Comment by moldcraft** [comment]
All ajax responses are empty

![screenshot from 2016-10-24 19-21-19](https://cloud.githubusercontent.com/assets/1475489/19653932/12af1492-9a1f-11e6-97bb-33e8c479d62d.png)

When I open this url

```
http://{DOMAIN}/wp-admin/admin-ajax.php
```

it comes as a empty file download. I disabled all plugins (except Unyson) but the problem persists. Please contact your hosting support and ask them what's the problem.

**Comment by moldcraft** [comment]
Sorry, I disabled Unyson and ajax requests work. Investigating...

**Comment by moldcraft** [comment]
The problem was in file cache. I deleted `wp-content/uploads/fw/file-cache.php` and it works now. For some reason the script wasn't able to delete that file, [this code](https://github.com/ThemeFuse/Unyson/blob/a0fc5ffdadc711d9d2f487dd65b6d74cf5b31524/framework/helpers/class-fw-file-cache.php#L85) triggered a lot of warnings.

**Comment by paul-fan** [comment]
Thanks moldcraft. I will keep on eye of the cache problem.
