### ISSUE TITLE
Open icon-v2 twice error

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson#2141]
If you open a icon-v2 twice in an addable-box type , there is a JS error :

`Uncaught TypeError: Cannot read property 'scrollIntoViewIfNeeded' of undefined
http://localhost/skyplex/wp-content/plugins/unyson/framework/includes/option-types/icon-v2/static/js/icon-picker-v2.js?ver=2.6.7 line 296`

To replicate : create multiple boxes with icon-v2 in it and complete them, save , then refresh and trey to open one of it , close, and then another one.

**Comment by andreiglingeanu** [comment]
@toleabivol Give me options array please.

**Comment by toleabivol** [comment]
Seems to be working now . If I replicate it again I will report and re-open.

**Comment by andreiglingeanu** [comment]
> If I replicate it again I will report and re-open.

Yes, please.
