### ISSUE TITLE
responsive page not working

### ISSUE THREAD

**Issue by dalelegacy** [ThemeFuse/Unyson#2142]
Hi guys, i have designed this webpage header and looks fine on desktop but on ipad and mobile it doesnt display well. 

I have other aspects on other pages that work well on devices but cant see any way to make things appear differently.

I dont have much coding experience.

any suggestions?

**Comment by moldcraft** [comment]
Hi,

How is this related to Unyson?

**Comment by thednp** [comment]
My suggestion: learn how to code YOUR own theme before customizing another one that may not be responsive design ready.

**Comment by duongancol** [comment]
I'm confusing too!

**Comment by dalelegacy** [comment]
Because it's part of the theme. Some aspects are responsive some aren't. I was seeing if there is an option I cannot see

**Comment by thednp** [comment]
In that case I would suggest to find the theme developer and report the issue to him, this here is only a development portal for the framework.
