### ISSUE TITLE
Modify how options render in box view

### ISSUE THREAD

**Issue by gabyferman** [ThemeFuse/Unyson#2143]
Hi,

this is maybe just a design issue, but I'm creating some options for a post type and I would like for the description to show under the labels instead of the fields. Or maybe change the labels to show above the fields for when I'm using options like "multi", is there a way to customize this views? Is there a function or do I have to create a new custom option?

![fireshot capture 23 - add new slide grupo mo_ - http___molecular eyecandy mx_wp-admin_post-new php](https://cloud.githubusercontent.com/assets/1626284/19713203/f02ec0c2-9af8-11e6-890f-09bccc274295.png)

In this image, **Show Slide Title** is a multi-picker type option, from which **Title Link** depends, which is a multi type option. Most of this modifications can be made with css, except moving the description label.

**Comment by moldcraft** [comment]
```php
add_filter('fw:backend-option-view:design-default:desc-under-label', '__return_true');
```

**Comment by gabyferman** [comment]
Thank you! Works great :)

**Comment by gabyferman** [comment]
Another question, is there a way to modify the view for option types? Like with typography v2, if I wanted to customize the view.php without changing the original files, maybe using the framework-customization folder the same way we can modify the extensions.

**Comment by moldcraft** [comment]
We can't allow that because in future we may change/fix something in it but you will have an outdated/wrong version. Better create your option-type

**Comment by gabyferman** [comment]
Ok, thanks again :)

**Comment by gabyferman** [comment]
Hi, is there a way to modify or remove the classes for backend options in metabox, ex. eliminate or modify `fw-backend-option-label fw-col-xs-12 fw-col-sm-3 fw-col-lg-2`

**Comment by gabyferman** [comment]
I found this filter:
```
apply_filters( 'fw:backend-option-view:design-default:responsive-classes', array(
    'label' => 'fw-col-xs-12 fw-col-sm-3 fw-col-lg-2',
    'input' => 'fw-col-xs-12 fw-col-sm-9 fw-col-lg-10', 
));
```
and I added it like this on my theme:
```
add_filter( 'fw:backend-option-view:design-default:responsive-classes', array(
    'label' =>  'class1' , 
    'input' => 'class2',
));
```
But it's throwing an error

**Comment by gabyferman** [comment]
Solved it! Just adding it here for future reference in case someone else needs it or if I there's a mistake please tell me.

```
function change_classes( $classes ) {
	$classes = array(
		'label' => 'this-label',
		'input' => 'this-input',
	);
	return $classes;
}
add_filter( 'fw:backend-option-view:design-default:responsive-classes', 'change_classes', 10, 1 );
```

![screenshot 28 _li](https://user-images.githubusercontent.com/1626284/31435196-b0487a12-ae33-11e7-9f1a-59a6b5d5e9b1.jpg)

**Comment by ViorelEremia** [comment]
I checked everything is fine!
