### ISSUE TITLE
Correct way to call scripts when overwriting a shortcode

### ISSUE THREAD

**Issue by MikeiLL** [ThemeFuse/Unyson#2144]
Hi when I follow to [docs](http://manual.unyson.io/en/latest/extension/shortcodes/#overwriting-shortcodes) to extend a shortcode, I think I am missing a step.

I duplicated the extension shortcode from unyson into `my-theme/framework_extensions/extensions/shortcodes/shortcodes/map`:

```
framework-customizations/extensions/shortcodes/shortcodes/map/
├── class-fw-shortcode-map.php
├── config.php
├── options.php
├── static
│   ├── css
│   │   └── styles.css
│   ├── img
│   │   └── page_builder.png
│   └── js
│       ├── scripts.js
│       └── tab.js
├── static.php
└── views
    └── view.php
```

But `$shortcodes_extension->get_uri` is pulling the script from Unyson.

I can use `get_template_directory_uri() .'/framework-customizations/extensions/shortcodes/shortcodes/map/static/js/scripts.js'`. 

Is that the way it's meant to be done?

**Comment by moldcraft** [comment]
1. You can't overwrite `class-fw-shortcode-map.php` so you can delete it from your theme, it is useless and confusing.
2. `$shortcodes_extension->get_uri()` It returns [the uri where the extension was defined](https://github.com/ThemeFuse/Unyson/blob/b30c9f6c562df29cb7130a2952631618e37e5777/framework/core/extends/class-fw-extension.php#L262-L264)
3. To work with shortcode uri you must use its [instance](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/2867e082813cc242b4d4f2b8cdf2b64744dee3ce/class-fw-extension-shortcodes.php#L21)

    ```php
    $map_shortcode = fw_ext('shortcodes')->get_shortcode('map');
    ```

4. To search the overwritten file in theme, use [this method](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/2867e082813cc242b4d4f2b8cdf2b64744dee3ce/includes/class-fw-shortcode.php#L113)

    ```php
    $uri = $map_shortcode->locate_URI('/static/js/scripts.js');
    ```

**Comment by MikeiLL** [comment]
OK. Thank you! 

I _think_ I see. What I ended up with in static.php is:

```
wp_enqueue_script(
	'fw-mzoo-shortcode-map-script',
	$shortcodes_extension->locate_uri('/shortcodes/map/static/js/scripts.js'),
	array('jquery', 'underscore', 'google-maps-api-v3'),
	fw()->manifest->get_version(),
	true
);
```

Some of the testing code:

```

$map_shortcode = fw_ext('shortcodes')->get_shortcode('map');
$uri = $map_shortcode->locate_URI('/static/js/scripts.js');
$test = $shortcodes_extension->get_uri('/shortcodes/map/static/js/scripts.js');
$here = $shortcodes_extension->get_declared_path();
print_r($uri);
```
