### ISSUE TITLE
Failed to copy: on demo content install

### ISSUE THREAD

**Issue by themeheap** [ThemeFuse/Unyson#2145]
Hi, I am getting following error on demo content install.
Failed to copy: /home/storage/a/a8/51/***/public_html/web/wp-content/uploads/index.php

**Comment by moldcraft** [comment]
Hello @themeheap 

I need your admin and ftp credentials to inspect the problem. Please send them to `moldcraft[at]email.com`

**Comment by themeheap** [comment]
It was fixed, upload/index.php was with strange file permission, fixed permission and solved the issue.
Thanks
