### ISSUE TITLE
How to check if Pagebuilder is Used on page?

### ISSUE THREAD

**Issue by dobromir-hristov** [ThemeFuse/Unyson#2146]
Because I am using Zurbs Foundation, and its `.row` element constraints content to 1200px, I need to know if a page uses the Page Builder, and if so I should know whether to include this class above the `the_content()` function call, or leave the builder do its thing. 
This is mostly a problem with the use of full-width sections from inside the builder.

**Comment by thednp** [comment]
https://github.com/ThemeFuse/Unyson/issues/1479

**Comment by dobromir-hristov** [comment]
Silly me ...
