### ISSUE TITLE
Failed to install demo content in Localhost

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#2147]
Hi

I have tried to install my demo content from localhost but failed to install. I have found like this error : 
`http://prntscr.com/czjbud` What should I do for that? I have already increase the maximum execution time to 180 from php.ini file.

Thanks for your advance help!

Regards
anisur210

**Comment by moldcraft** [comment]
When you set 180 in php.ini, the error still shows 10 seconds? If yes, then check you .htaccess or wp-config.php, maybe there is set 10 seconds (such timeout value is too low)

**Comment by pear1** [comment]
Hi, 

I have similar issue installing demo content, it shows this message bellow, but it should be 300 seconds.
`Maximum execution time of 29 seconds exceeded in /www/public/wp-includes/class-wp-image-editor-imagick.php on line 352`

**Comment by pear1** [comment]
Another new error for my demo site:
`Imported url "http://demosite.com" is prefix of current url`
This happens when installing http://demosite.com created demo content back to http://demosite.com

**Comment by moldcraft** [comment]
> ... prefix of current url

https://github.com/ThemeFuse/Unyson/issues/2114#issuecomment-253971305

Can you send me your admin and ftp details to `moldcraft[at]email.com`?
