### ISSUE TITLE
Error In Unyson Slider

### ISSUE THREAD

**Issue by khangdoan03121993** [ThemeFuse/Unyson#2149]
I created slider in the backend from Appearance->Slider. And added in home page template. But we are getting 
Warning: Invalid option: page in
/home/swatapestcom/public_html/wp-content/plugins/unyson/framework/helpers/general.php on line 929

How do I solve this problem? Thanks

**Comment by moldcraft** [comment]
Hello @khangdoan03121993 

1. Which theme you are using?
2. Can you make a screenshot or screencast/video of the problem?

**Comment by khangdoan03121993** [comment]
Info of site: http://swatapest.com.au/

![screenshot](https://cloud.githubusercontent.com/assets/15787361/19803655/11247820-9d34-11e6-9dae-d32a90f2d835.png)

Can you check it?

**Comment by moldcraft** [comment]
> Info of site: http://swatapest.com.au/ Can you check it?

How to check without admin and ftp?

**Comment by duongancol** [comment]
@khangdoan03121993 I think you should test the problem in theme default at first

**Comment by khangdoan03121993** [comment]
Thanks, I fixed the problem. Have a nice weekend!
