### ISSUE TITLE
Extensions installation impossible (no release, 403)

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#215]
Hello,

I got some customers who can't not use my theme because they can't install the page builder extension...And all the others btw : 
http://ticksy_attachments.s3.amazonaws.com/6906860160.png
http://ticksy_attachments.s3.amazonaws.com/7785854718.png

1) Do you have any idea from where it is from ? Seems new, from the latest releases in my mind ...
2) Do I have to edit anything in the theme files (let me know if you need any detail or file)
3) Is there a way to install at least the page builder manually ? (I have tried many ways but no success yet...)

Thank you for your help, let me know what can I do please, It's a really important issue for me....

Regards,
2F

**Comment by moldcraft** [comment]
The api seems to work fine. The Shortcodes extension [has releases](http://github-api-cache.unyson.io/repos/themefuse/unyson-shortcodes-extension/releases) and [megamenu](http://github-api-cache.unyson.io/repos/themefuse/unyson-megamenu-extension/releases) too.

Try add to debug [`fw_print($response)`](https://github.com/ThemeFuse/Unyson/blob/master/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L1725)

**Comment by 2Fwebd** [comment]
Thank you @moldcraft for the fast reply !  Well yes and it works on my own server too so it's really weird. I can send you private access (to the customer Wordpress) by message if you want to see it. You can click on any extension and there is the box : ...has no releases.
Where do I past the fw_print function please ? I tried many places and I see no difference.
Thanks ! ;)

**Comment by moldcraft** [comment]
You can send me a message to unyson[at]email.com

**Comment by 2Fwebd** [comment]
Done ;) Thanks

**Comment by pe6o** [comment]
When this is fixed, please write what caused the issue. Just want to know in case it suddenly appears on some of my clients, thanks!

**Comment by moldcraft** [comment]
How to debug `The "Abc" extension ... has no releases.` or `Cannot access repository ... (Error code 403)`:

1. Add `fw_print($response)` on [this line](https://github.com/ThemeFuse/Unyson/blob/1f78a1dc5074671474d23e77921ace28ee5bbdee/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L1729)
2. Open `/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=page-builder` and click "Install"
3. You will see the dump

----

@2Fwebd In your case, the dump is [this](http://plink.link/bac6b6a8d8d82aa92351b6896fb6aec7/html):

```text
array
(
    [headers] => array
    (
        [server] => 'squid/2.5.STABLE14'
        [mime-version] => '1.0'
        [date] => 'Tue, 03 Feb 2015 09:42:12 GMT'
        [content-type] => 'text/html'
        [content-length] => '1183'
        [expires] => 'Tue, 03 Feb 2015 09:42:12 GMT'
        [x-squid-error] => 'ERR_ACCESS_DENIED 0'
        [x-cache] => 'MISS from hproxy.world4you.com'
        [connection] => 'close'
    )
    [body] => '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The requested URL could not be retrieved</TITLE>
<STYLE type="text/css"><!--BODY{background-color:#ffffff;font-family:verdana,sans-serif}PRE{font-family:sans-serif}--></STYLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The requested URL could not be retrieved</H2>
<HR noshade size="1px">
<P>
While trying to retrieve the URL:
<A HREF="http://github-api-cache.unyson.io/repos/ThemeFuse/Unyson-Shortcodes-Extension/releases">http://github-api-cache.unyson.io/repos/ThemeFuse/Unyson-Shortcodes-Extension/releases</A>
<P>
The following error was encountered:
<UL>
<LI>
<STRONG>
Access Denied.
</STRONG>
<P>
Access control configuration prevents your request from
being allowed at this time.  Please contact your service provider if
you feel this is incorrect.
</UL>
<P>Your cache administrator is <A HREF="mailto:root">root</A>. 


<BR clear="all">
<HR noshade size="1px">
<ADDRESS>
Generated Tue, 03 Feb 2015 09:42:12 GMT by hproxy.world4you.com (squid/2.5.STABLE14)
</ADDRESS>
</BODY></HTML>
'
    [response] => array
    (
        [code] => 403
        [message] => 'Forbidden'
    )
    [cookies] => array()
    [filename] => null
)
```

So it looks like the hosting server is not allowing requests to http://github-api-cache.unyson.io/

**Comment by danyj** [comment]
@moldcraft suggestion , add a debug that we can turn on to troubleshoot unyson instead of going trough plugin files and printing the requests.

**Comment by moldcraft** [comment]
@danyj If this will happen often, I will do something like that.

**Comment by 2Fwebd** [comment]
Hello @moldcraft,

Thank you for your help and the explanations. You're right ! Both of my clients send messages to their hosts. For one, they allowed the URL and everything works perfectly. But for the other one :

> not working......they said it won't work on plesk on their server. I would have to switch to a Linux based system. In other words I would have to buy a whole new separate hosting package.

I don't know how to fix this issue...I agree it is really rare. But anyways, I'm looking for a way to **install manually the page builder and the shortcode extensions (directly in the theme)** that could fix everything (it works for the megamenu but not for them...)

Thank you

**Comment by moldcraft** [comment]
Hello @2Fwebd 

> not working......they said it won't work on plesk on their server. I would have to switch to a Linux based > system. In other words I would have to buy a whole new separate hosting package.

What is actually not working? The hosting doesn't want to allow requests to `http://github-api-cache.unyson.io/` *(More details please)*

> install manually the page builder and the shortcode extensions (directly in the theme)

Sure, you can copy the extensions from the framework to your theme, `unyson/framework/extensions/{extension}` to `{theme}/framework-customizations/extensions/{extension}` *(not tested, but theoretically it should work)*, but your theme won't pass themecheck and TF approval (plugin territory).

**Comment by danyj** [comment]
I researched this yesterday and both of your clients have not setup the squid correctly ( or their host did not ) 
http://ubuntuforums.org/showthread.php?t=1946358
by default squid allows connection to itself only

https://wiki.archlinux.org/index.php/Squid#Configuration

see http_access  directives

**Comment by danyj** [comment]
@moldcraft what do you think about install extension pack option (aka: upload extenson zip ) ?

**Comment by moldcraft** [comment]
> @danyj I researched this yesterday and both of your clients have not setup the squid correctly ( or their host did not ) 

I think they configured it to allow requests only to trusted sites. Maybe to `wordpress.org` only (if it's a hosting packet exclusively for wordpress) Because they installed somehow Unyson, I don't think they installed it via zip upload.

**Comment by danyj** [comment]
@moldcraft ok am I missing something here or "install" only downloads the extension master and unzips them to unyson/extensions ?
@2Fwebd if this is the case than just pack all the extensions from unyson/extensions  folder and FTP to your client site.

**Comment by danyj** [comment]
I just downloaded 
https://github.com/ThemeFuse/Unyson-Breadcrumbs-Extension/archive/master.zip
extracted to breadcrumbs ,  FTP the folder to  unyson/extensions and works perfect
http://screencast.com/t/8b2RkAgtpW

**Comment by moldcraft** [comment]
> am I missing something here or "install" only downloads the extension master and unzips them to unyson/extensions ?

If the extension has no parent extension, then to `unyson/extensions`.
If it does, the parent extensions chain is resolved from [this array](https://github.com/ThemeFuse/Unyson/blob/87afbdf78c5c382018c3702095ff4b3f99397f07/framework/core/components/extensions/manager/available-extensions.php#L83) and first are installed (or checked if installed) parent extensions, the the extension is installed into its parent extension directory, for e.g. the `page-builder` is installed in `unyson/extensions/shortcodes/extensions`

**Comment by danyj** [comment]
ok, so @2Fwebd can pack unyson plugin from his demo with all bells and whistles  and FTP to client site for temp workaround

**Comment by moldcraft** [comment]
@danyj sure

**Comment by 2Fwebd** [comment]
Thank you @danyj and @moldcraft for all the help here !!! 

So : 

* In fact it seems that this is the servers not based on Linux which cause the issue
* I didn't thought to send directly the plugin files and it seems perfect for me :) **I'll do that and keep you informed**
* However when I try to install the extensions directly from the /framework-customizations/extensions/ you're right it only works with the extensions without parent. But even if I wrap them as @moldcraft  said I'm still having errors (with the latest version of Unyson) : 

> Cannot activate hidden standalone extension Shortcodes

and
 
> Cannot activate the Builder extension because it is not installed.

When I add the builder extension, it asks the contact form one and then the mailer one ...

Thank you :+1:

**Comment by moldcraft** [comment]
> @danyj what do you think about install extension pack option (aka: upload extenson zip ) ?
>
> if the install fails, present admin with upload zip option or something like that.

Some extensions requires other extensions, and those extensions requires other extensions etc. ( @2Fwebd mentioned that in the previous comment ) so installing them manually (one by one) will be tedious.

I hope this problem with hosting restricting requests will not happen that often to force us to implement that upload feature.
