### ISSUE TITLE
RTL issue in a Form Builder

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2151]
Hello!

I noticed one problem using Form Builder in RTL mode, for example:

i have a form with 4 rows, first 3 rows have 70% width, last row has 100%, in RTL mode these fields should be aligned to the right, but in fact, they aligned to the left, is there any way to resolve this, please

![2016-10-29_14-47-09](https://cloud.githubusercontent.com/assets/12991525/19829361/02e1aac2-9de7-11e6-8758-909edf1444c9.png)

**Comment by moldcraft** [comment]
Hello,

Can you provide the fix as a pull request?

**Comment by WPJobs** [comment]
Hi, @moldcraft 

I though about the fix, but currently it is impossible to fix just via CSS, i'll try to explain why:

If i add following code:

```
body.rtl .form-builder-item {
  float: right;
}
```

it fixes first 3 rows but it also makes the last row not 100% width due to the float rule, and the last row doesn't have any unique CSS class that i can use to make it 100% in width (float: none)

![2016-10-31_10-56-20](https://cloud.githubusercontent.com/assets/12991525/19848875/dc8a4bc2-9f58-11e6-827d-8ab1c4372b56.png)

![2016-10-31_10-56-54](https://cloud.githubusercontent.com/assets/12991525/19848878/e35722ae-9f58-11e6-8e3c-dfda67dc0d3a.png)

**Comment by moldcraft** [comment]
I have made a few fixes related to rtl. Please test latest [Builder](https://github.com/ThemeFuse/Unyson-Builder-Extension) and [Forms](https://github.com/ThemeFuse/Unyson-Forms-Extension) extensions

**Comment by WPJobs** [comment]
Thank you so much, @moldcraft i have tested this and it works like a charm

**Comment by WPJobs** [comment]
just one question: i'm not sure, in RTL mode, should columns swap their places? For example:

![2016-11-02_14-58-45](https://cloud.githubusercontent.com/assets/12991525/19929651/ff97dc6e-a10c-11e6-883e-d86ecc66c93f.png)

![2016-11-02_14-59-12](https://cloud.githubusercontent.com/assets/12991525/19929654/04418530-a10d-11e6-9ea2-dfc6a2961f62.png)

**Comment by moldcraft** [comment]
Yes, `float: right` on rtl is `float: left` and vice versa.
