### ISSUE TITLE
[Demo content]Keep long loading in Unzip step

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#2155]
The demo content keeps long time loading in Doing Unzip step. 
I sent you an email with site account to check it. 
Thanks!

**Comment by duongancol** [comment]
I have the long loading in Extract file process with another client hosting. I sent you an email so hope you can figure out the problem.

**Comment by moldcraft** [comment]
First, the Files Export step was blocked randomly (some times it succeeded), on random files (I tested with `error_log($file)`), I fixed that by limiting manually the timeout to 10 seconds (similar to [this issue](https://github.com/ThemeFuse/Unyson/issues/1818#issuecomment-235711685)). Now the process stops at Archive Zip and I have no idea why. Nothing shows up in `wp-content/debug.log` and I don't know what to do next.

In this situation our support team (ThemeFuse) would do the Demo Install manually:

1. Configure your localhost so client's domain will work locally (by changing the `etc/hosts` file)
2. Do Demo Install on your localhost
3. Export all MySql tables (except users and usermeta)
4. Import MySql tables and `uploads/` directory on client server

**Comment by duongancol** [comment]
I know the another way to install demo content but our client want to install it manually. Thank for your time!

**Comment by moldcraft** [comment]
If there will be a specific place when the script stops and we would have an error message, it will be easy to fix. But unfortunately it stops randomly or without error message. I don't know what to do, sorry.

**Comment by duongancol** [comment]
yeah, I see
