### ISSUE TITLE
Copying a page that is build in Unyson does not work?

### ISSUE THREAD

**Issue by jeroenverburgt** [ThemeFuse/Unyson#2158]
Hi,

I'm using the Duplicate Post plugin in order to copy posts, which works out fine with any Theme I have ever tested....except for The Core. If I copy a page, the visual builder code is not simply not copied..?

**Comment by thednp** [comment]
https://github.com/ThemeFuse/Unyson/issues/2118

**Comment by moldcraft** [comment]
The builder value is stored in post meta named `fw:opt:ext:pb:page-builder:json`. On duplicate the value is changed/corrupted and can't be `json_decode()`.

[The value before and after duplicate](https://www.diffchecker.com/tHj7ct5o)

You should report this problem to plugin author.
