### ISSUE TITLE
Wordpress Shortcode within a Unyson Shortcode

### ISSUE THREAD

**Issue by viorelrj** [ThemeFuse/Unyson#2160]
Hello, I have started developing an one-page styled theme with unyson using custom shortcodes - great experience and it eases the process very much. I use also a plugin that generates automatically shortcodes in default wordpress style, like this: [shortcode_name] . How can I call a default wordpress shortcode in a view file of a unyson shortcode?

**Comment by andreiglingeanu** [comment]
Just do this in `view.php`:

```php

echo do_shortcode('[your_awesome_shortcode']');

```
