### ISSUE TITLE
Extension loading

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson#2161]
Framework includes the extension class file before checking the extension requirements.
There is the `php` requirement and the authors may use some specific coding format, in the extension class file, supported by the required php version.

May Should check only for class file name, without including it.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/15beda691b17a9861fd5e8cdb0fca5eef4120f3c

Needs good testing. This change is very important.
