### ISSUE TITLE
Can't overwrite class class-fw-shortcode-column.php 

### ISSUE THREAD

**Issue by iulianflst** [ThemeFuse/Unyson#2162]
I have added padding and margin options to section and now I want to move all the inline css into an external css file via my css manager  but I can't overwrite class \extensions\shortcodes\shortcodes\column\class-fw-shortcode-column.php 

I created a new class in : \framework-customizations\extensions\shortcodes\shortcodes\column\class-fw-shortcode-column.php  and the class is simply ignored.

I tried to copy the class but it doesn't work. I tried the same thing with section and  I got the same problem.

Options.php file is working.

Creating new extension is possible so why is not working overwriting the parent shortcode class ?

Regarding nested rows, are you planing to add support in the future ?

**Comment by moldcraft** [comment]
Hi,

You can't overwrite the shortcode class file. Please inspect the class code, add a hook (action/filter) where you would like to extend its functionality and provide a [pull request](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/column/class-fw-shortcode-column.php).
