### ISSUE TITLE
Extensions requirements enforced only at the UI level

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#2163]
https://github.com/ThemeFuse/Unyson/blob/v2.6.8/framework/core/components/extensions/manager/views/extension.php#L186-L350

The main logic for the requirements checking are mixed up with the view logic. There's no way to check those requirements away from the main Unyson page.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/pull/2164#event-846311210
