### ISSUE TITLE
Can we add custom modal events for addable popup

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2165]
I need to check an option before addable popup modal opens, 

    fwEvents.debug(true);

shows only fw:opt:init

I know that @andreiglingeanu  was adding some custom events for modals but not sure what it was for and cant find the post. 
Any help is appreciated.

**Comment by danyj** [comment]
@andreiglingeanu   can you help with this? I need to finish the options , 

trying to hide specific multi select options if some are already picked and need to check the multi select list when that popup is opened

**Comment by andreiglingeanu** [comment]
@danyj Do a `fwEvents.debug(true);`

```javascript

fwEvents.on('fw:option-type:addable-popup:options-modal:open', function (data) {
  var frame = data.modal.frame.$el;
  frame.find('.your-option-to-hide').hide();
});

```

**Comment by danyj** [comment]
do you mind trowing in the actual option name , like 

`fw:option-type:addable-popup:options-modal:myname:open
`
this way we can target specific addable popup and not run check on all of them

**Comment by andreiglingeanu** [comment]
@danyj There's no easy way of doing that. Please do checks in your event handlers.

**Comment by danyj** [comment]
ok , thnx , I thought it would be accessible. np the current events help
