### ISSUE TITLE
[bug] Options save takes to long and browsers advise to kill the page

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2166]
Not sure what is going on but since latest release seems like lazy_tabs  init runs on every options save no matter if tabs are already activated. First save used to be slow but every next fast, now every save is slow. Did I miss some changes?

**Comment by danyj** [comment]
And it is in Chrome only , IE, FF are ok. Not sure what this is.

**Comment by danyj** [comment]
Here video http://take.ms/jst23

more tabs/options you add , the slower second and every consecutive save is, 

I tested with your The Core , and any Unyson based theme , plus the scratch , same issue, the freeze is very noticeable in Chrome.  IE and FF  starts giving you "kill page" notice if the save does not finish within certain time period. 

FF
http://prntscr.com/d3sguv


IE 
http://prntscr.com/d3shm8


this has just started since 2.6.8 release, it was not the case before. 

with lazy tabs off the issue is immediate on every save , not just second and up.

**Comment by danyj** [comment]
there are no server or php error logs , there is some kind of timeout and nothing moves in network or anywhere until the popup shows up , than save finishes within 1sec

**Comment by andreiglingeanu** [comment]
Are `lazy_tabs` enabled?

**Comment by danyj** [comment]
either way , enabled disabled , 
http://prntscr.com/d44nxw

**Comment by andreiglingeanu** [comment]
Try to disable AJAX for Theme Settings.

**Comment by danyj** [comment]
> Try to disable AJAX for Theme Settings.

just did and ti is same 

freeze , than save

**Comment by danyj** [comment]
here scratch theme , 20 takes to initiate the save with ajax off 

http://take.ms/PoHL7

**Comment by andreiglingeanu** [comment]
I think that's because of lazy tabs

**Comment by danyj** [comment]
man you stubborn 


```
$cfg['lazy_tabs'] = false;
$cfg['settings_form_side_tabs'] = true;
$cfg['settings_form_ajax_submit'] = false;
```

watch this till the end , lazy off , ajax off, is horible

http://take.ms/U1gfC

with lazy off it is IMMEDIATE freeze, try it please , get scratch , load many tabs

**Comment by danyj** [comment]
meanwhile tested on live server and also mac chrome to make sure it is not my machine or some browsr bug, same thing

**Comment by andreiglingeanu** [comment]
I'm able to reproduce this. After getting a substantial amount of options in Theme Settings even this first load of that page is _VERY_ slow, the submit is also very slow.

Can you confirm that this behavior is after some particular update? If you can let me know which version introduced that I may be able to track it down better.

**Comment by danyj** [comment]
I tried to nail the update down , went all the way to 2.6.0 and same thing, 
dont know which one it is. seems like this " slipped " by somehow

**Comment by danyj** [comment]
something else to look at , 
options cache if one is used in theme settings ,  I started disabling tabs one by one and the save now takes longer,

**Comment by danyj** [comment]
found the possible issue,  when commented out 

https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/backend-options.js#L112


save works normally, it does not send all the data but only visible tab,  buts seems like initiation fires also when tabs are initiated. 

this recursive to be precise 
https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/backend-options.js#L106-L107

**Comment by danyj** [comment]
yes , that while is killing everything
https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/backend-options.js#L105

 , do console log inside and you will see that for some reason it keeps on finding the tabs even if all are initiated.

**Comment by danyj** [comment]
@andreiglingeanu , test this bud , 

clear browser cache or open incognito chrome and test , 

I was just messing with the loop above , set everything back , 
cleared cache , restarted chrome and now is faster again. 
same options same tabs. 
something strange is going on and looks like this is connected to the cache . not sure why.

**Comment by danyj** [comment]
after about hour browsing the bug is back , opened theme settings in incognito and everything is fine, so looks like it is connected to the cache or some tab cookies

**Comment by andreiglingeanu** [comment]
> do console log inside and you will see that for some reason it keeps on finding the tabs even if all are initiated.

That was helpful. I think there's a useless computation going on. I'll make a hard check before doing any action, this should speed things up I think. Thank you.

**Comment by danyj** [comment]
@andreiglingeanu  also please , check the incognito now ,  I am still kinda sure about the cache , in incognito is fast as hell

**Comment by danyj** [comment]
so far I know jQuery tabs UI  used cookies before 1.9 http://jqueryui.com/upgrade-guide/1.9/#deprecated-cookie-option

but WP seems to still used them , and this bug might have come from actual WP upgrade. 
Sorry for just trowing things at you, just trying to nail this since the "normal" Chrome tab is currently completely unusable for me.

**Comment by andreiglingeanu** [comment]
Ah! That was it. And in incognito you don't actually have those cookies, got it. 

Why would they want to use cookies persistence for a dead simple tabs component?

Anyway, glad things are clear now.

**Comment by ivandotv** [comment]
I can confirm this bug . Update/save on post/page and customizer freezes browser tab.
Also when using select dropdown, when it opens, the page frezes, and when something is selected in the dropdown, it freezes again. Both on post/page settings and in customizer.
Also this happens in the customizer, when navigating between sections.

**Comment by danyj** [comment]
@andreiglingeanu  @moldcraft  any news on this?

**Comment by moldcraft** [comment]
I have tested with Scratch Theme and these `settings.php` options

```php
$options = array();

for ($i = 1; $i != 10; ++$i) {
	$options['t_'. $i] = array(
		'title'   => 'T#'. $i,
		'type'    => 'tab',
		'options' => array(
			'c_'. $i => array(
				'label'   => false,
				'type'    => 'multi',
				'inner-options' => array(
					fw()->theme->get_options( 'demo' ),
				),
			),
		),
	);
}
```

and it works fine https://vid.me/1tJt

I can't reproduce.

**Comment by danyj** [comment]
3 of us tested with same result and are waiting for solution since 11 days , please ask @andreiglingeanu  how to reproduce,  turn on sidetabs and lazy_tabs also , side tabs might have something to do with it.

**Comment by moldcraft** [comment]
with side tabs works fine too.

@andreiglingeanu please give the exact steps to reproduce (with code)
