### ISSUE TITLE
[bug] Addable popups are not reused but added to page html

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2167]
Downloaded latest master, 

add addable popup , inside its options add one more , 
set both addable popups limit to 1 ( not required , just to make sure we dont have more than one popup ) 

Now , add  one main , and one sub popup , and save modal

now reopen the main popup , click on sub popup and observe popups in page html continue to stack causing backdrop z-index issues and adding additional popups on every popup open 

this is what I endup with by opening and closing sub popup 3 times http://prntscr.com/d3j7hn

there should be only 2 popups in html

**Comment by moldcraft** [comment]
Please test

**Comment by moldcraft** [comment]
Please test

**Comment by danyj** [comment]
on it

**Comment by danyj** [comment]
works. thnx!
