### ISSUE TITLE
Theme Settings Save Action

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#2168]
Is there a Action to hook into when the Theme Settings save? I have a transient setup on the front-end based on data from the Theme Settings page. I would like to delete the transient data ever time the Theme Settings are saved by the user.

Thanks!

**Comment by danyj** [comment]
add_action('fw_settings_form_saved', array( $this, '_thz_action_clean_option' ));

**Comment by meta4creations** [comment]
Thanks!
