### ISSUE TITLE
Help breadcrumbs bug

### ISSUE THREAD

**Issue by Maxim850** [ThemeFuse/Unyson#2169]
by clicking on the instructions for setting up breadcrumbs gives an error: 
Инструкции по установке   -	Настройки "Хлебные крошки"
 Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in /home/xxx/xxx/xxx/public_html/wp-content/plugins/unyson/framework/core/components/extensions/manager/includes/parsedown/Parsedown.php on line 1479

**Comment by mowshon** [comment]
You have old PHP version. The ability to use `new static()` was introduced in PHP 5.3.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/bd975222ef4fee06f1adb0ad87b37020fd8050e1

The fix will be included in next Unyson version.
