### ISSUE TITLE
Strict Standards warning in php 5.4

### ISSUE THREAD

**Issue by kowsar89** [ThemeFuse/Unyson#2171]
In my php 5.4 installation while debug mode is on, i see this warning:

`Strict Standards: Declaration of FW_Db_Options_Model_Post::get_cache_key() should be compatible with FW_Db_Options_Model::get_cache_key($key, $item_id, array $extra_data = Array) in E:\xampp-php5.4\htdocs\site\wp-content\plugins\unyson\framework\helpers\database.php on line 243`

This is happening because of the number of parameters aren't same in parent class method and child class method i guess. Please fix this.

**Comment by andreiglingeanu** [comment]
@kowsar89 Should be fine now.
