### ISSUE TITLE
Layout issues with modal window inside customizer.

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2172]
When we have tabs and content overflows the modal, scrollbar doesn't appear.
I believe this is the code that is causing problems.
https://github.com/ThemeFuse/Unyson/blob/6fb4a05a095ba62243f75674577c3c53a27d2833/framework/static/js/fw.js#L961

**Comment by moldcraft** [comment]
Please provide the options array so we will test it on our side.

**Comment by ivandotv** [comment]
Hi I'm testing this and basically not every time, but it happens on occasion that the scroll bar doesn't appear, especially when I have tabs in the modal window, and I switch to a tab and there should be a scrollbar because the content of that tab is bigger than the modal window height. But the scrollbar doesn't appear.
I believe that it has something to do with this issue #2166

**Comment by ivandotv** [comment]
Can't reproduce it consistently, closing the issue for now.
