### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by hdurandb** [ThemeFuse/Unyson#2173]
I installed a theme, that required a redux framework. Developer suggest an update http://bliccathemes.com/planter/demos/wp-admin/admin-ajax.php?action=redux_download_options-planter_theme_options&secret=df49841a1284b3d1a70656b3c3593a70 once i made it, i got a white screen. Only when i deactivate the Redux Framework i can see the page, otherwise i got a white screen. Any help?

**Comment by danyj** [comment]
bud ,   you are posting in Unyson , a completely different framework git.

**Comment by hdurandb** [comment]
duh!, sorry
