### ISSUE TITLE
Demo content XML

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#2175]
Hello

Please let me know, where is problem with activating demo content via WP administration. I want to activate one page form demo, but there is this error: Failed to create tmp table _fwbk_dk_commentmeta. Unknown storage engine \’InnoDB\’ Please write to me, where is the problem if I want to activate demo content again myself. 

Here is the screenshot : http://prntscr.com/d4xwp9

Regards
anisur210

**Comment by Ataurr** [comment]
Add this code here [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L429)

`$sql = str_replace('InnoDB', 'MyISAM', $sql);`

@moldcraft it will be great if you check server which db engine using. and set a condition will help to install demo content in innodb server

**Comment by anisur210** [comment]
Hello Ataurr,

Thanks! Its working !!

**Comment by andreiglingeanu** [comment]
@Ataurr Good suggestion.
