### ISSUE TITLE
How get option label?

### ISSUE THREAD

**Issue by acidcrash2005** [ThemeFuse/Unyson#2176]
Hello!

I have option:
`'buh_1_t1' => array(
    'type'  => 'text',
    'label' => 'Some label',
),`

When I use` fw_get_db_post_option()` see `[buh_1_t1] => 'some valuse'`.

How can I get the label of this option? In the array, I don't have any information about the label.

Thanks!

**Comment by danyj** [comment]
why would you need a label in frontend?

**Comment by acidcrash2005** [comment]
I create a table, name of the column I want to get from the label of options and the data of column from value.

**Comment by acidcrash2005** [comment]
Like this - http://joxi.ru/eAOe4ElCVWpxmo

**Comment by danyj** [comment]
option labels are used in backend only and there is no frontend output , you need to figure out the way to accommodate your fronted , maybe add column lablel option next to the value, 

see this as  alternative https://github.com/ThemeFuse/Unyson/issues/1065

**Comment by moldcraft** [comment]
1. Load your options array http://manual.unyson.io/en/latest/components/theme.html#content
2. Extract only options as one level array http://manual.unyson.io/en/latest/helpers/php.html#fw-extract-only-options
3. Access your option by id and get the label
