### ISSUE TITLE
register form

### ISSUE THREAD

**Issue by tiderdev** [ThemeFuse/Unyson#2178]
at page builder there are components named register form : 
where i can change the email template from this register form ?
and can i change the link submission off this form ?

please need help here, i have searched on the docs but can't find a thing..

**Comment by mowshon** [comment]
You use clean Unyson or some Theme that extend Unyson functionality?
I'm asking because Unyson don't have `Register Form` component.

**Comment by moldcraft** [comment]
Email template is [this](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/f1b3304fe24984a8a4953b0302c782269c4b872c/extensions/contact-forms/views/email.php) and can be overwritten in

```
{theme}/framework-customizations/extensions/forms/extensions/contact-forms/views/email.php
```

----

Redirect link is [this](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/f1b3304fe24984a8a4953b0302c782269c4b872c/class-fw-extension-forms.php#L195), it is hardcoded. Should I add a filter for you?

**Comment by GheorgheP** [comment]
I think that we can cloe the issue for now,due to the fact that we do not get any response.
