### ISSUE TITLE
FW_Settings_Form does not work

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson#2181]
```
add_action('fw_init', '_action_theme_test_fw_settings_form');
function _action_theme_test_fw_settings_form() {
	if (class_exists('FW_Settings_Form')) {
		require_once dirname( __FILE__ ) . '/inc/classes/class-fw-settings-form-header.php';
		new FW_Settings_Form_Test('test');
	} else { print_r('not working');}
}
```
I was trying to implement [this](http://manual.unyson.io/en/latest/helpers/settings-form.html), but it seems that the class is not loaded.

**Comment by dmbostan** [comment]
anyone?

**Comment by danyj** [comment]
use this one 
https://github.com/ThemeFuse/Unyson/issues/2112#issuecomment-255769799

**Comment by dmbostan** [comment]
@danyj  thank you, but I already have the class. 

The issue is that it does not pass the `class_exists` condition,

**Comment by danyj** [comment]
are you using the current master or stable version ?

    FW_Settings_Form

was added 22 days ago 
latest stable release was 26 days ago

**Comment by dmbostan** [comment]
:)))))))))))))))))) using the official plugin from WP.org

Let me try it & thank you :D

**Comment by dmbostan** [comment]
@danyj once again, thank you! Closing the issue.
