### ISSUE TITLE
Theme called for 9 extensions, but Unyson only installed 4

### ISSUE THREAD

**Issue by ctnsamo** [ThemeFuse/Unyson#2182]
Theme called for 9 extensions, but Unyson only installed 4. I deleted and reinstalled and got the same thing. (Page Builder, Backup, SEO, and Analytics) Please advise.

**Comment by thednp** [comment]
Please **delete** Unyson plugin and reinstall, try again and let us know. If not, email the lead here @moldcraft.

**Comment by ctnsamo** [comment]
Thanks. I tried that a few times but it didn't help. I also chose to manually install from the list, and it gave me 6 extensions. Then after downloading each, it showed 4 being installed. I'll check with the theme author, then the lead.

**Comment by moldcraft** [comment]
A lot of extensions are hidden. Only important extensions that are relevant for the user to be able to enable/disable are visible, other extensions are just required by those important extensions.

_[Note](http://manual.unyson.io/en/latest/manifest/extension.html#content) the `$manifest['display']` parameter._
