### ISSUE TITLE
reCaptcha in Forms bug

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2184]
Hello!

I noticed a small bug in contact form with reCaptcha using AJAX: 

You can't send e-mail if you used Captcha and if you had made any mistake in contact form. Even if you correct your error (for example e-mail) you will be still informed that you have to fill captcha field. You couldn't fill it because it was done before :-) You have to refresh page and fill all fields again.

![2016-11-15_09-56-01](https://cloud.githubusercontent.com/assets/12991525/20297565/ceac5ee2-ab19-11e6-9283-9d242133e0eb.png)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1283#issuecomment-184128749

**Comment by WPJobs** [comment]
Thank you, @moldcraft !
