### ISSUE TITLE
WordPress functions within config title_template?

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#2186]
Is it possible to use WordPress or PHP functions within a title_template? I'm using a Multi-Select as an option to choose posts. I would like to display the post's title in the title_template as opposed to the post ID of the post. Is this possible?

I've tried multiple combinations of the following, but it just produces errors:

`'title_template' => '{{ get_the_title(o.location) }}'`

Thanks for the help!

**Comment by moldcraft** [comment]
It's not possible.

**Comment by meta4creations** [comment]
Ok, thanks for clearing that up.
