### ISSUE TITLE
Video not working in slider function

### ISSUE THREAD

**Issue by apansoy** [ThemeFuse/Unyson#2189]
I am trying to add a webM to the slider function from Vimeo, but the video won't show up on my page. How do I remedy this?

**Comment by moldcraft** [comment]
Hi,

Please give a test video link.

**Comment by apansoy** [comment]
https://player.vimeo.com/external/191525310.hd.mp4?s=f6def50fd4b2fe97ac78276485c624ae2208342d&profile_id=119

*Ashley Pansoy  // *Visual Arts Communications Coordinator

The Creative Department *...bringing revival to the church and the arts.*
*P* 916.780.2273 <9167802273> ext. 255 // *W *destinychurchlife.com

**Comment by moldcraft** [comment]
Hi,

The slider works only with regular public videos.

```php
add_action('admin_notices', function(){
	fw_print(
		wp_oembed_get(
			'https://fpdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/3305/7/191525310/637441775.mp4?token=58344513_0x27c2fb9d254709f151a78f06bb6dede54d5c3afb'
		),
		wp_oembed_get('http://vimeo.com/23924346') // regular url
	);
});
```

I added the possibility to display videos with direct link https://github.com/ThemeFuse/Unyson-Sliders-Extension/commit/620aee1080e4ac869af3ff2c6f56d896c9bad41b
but it doesn't look good 
![screenshot from 2016-11-22 14-35-04](https://cloud.githubusercontent.com/assets/1475489/20524026/e144496e-b0c0-11e6-9f77-9a484f9f9493.png)
