### ISSUE TITLE
Extension Settings Save Action

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#2190]
I asked a similar question about theme options here #2168, but now I'm wondering about Extension options.

Is there a Action to hook into when an extension's settings are saved? I need to modify a few things every time the settings for one of my extensions is saved.

Thanks!

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/b8fe85a13fc94a309976569569c050735c08f541/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2416
