### ISSUE TITLE
Install Compatible Extension with ajax request

### ISSUE THREAD

**Issue by dinhtungdu** [ThemeFuse/Unyson#2191]
Hi,
I want to make a feature that user just need one click to install Unyson and compatible extensions. I've done with the Unyson plugin but not extensions.

I'm trying to make a POST request with nonce to `/wp-admin/admin.php?page=fw-extensions&sub-page=install&supported` but it always swtiches to GET request. Can you give me some hints?

**Comment by dinhtungdu** [comment]
Making a post request to `/wp-admin/admin.php?page=fw-extensions&sub-page=install&supported` with nonce solved this!

**Comment by moldcraft** [comment]
```php
if (
	fw()->extensions->manager->can_install()
	&&
	FW_WP_Filesystem::is_ready()
) {
	$result = fw()->extensions->manager->install_extensions(array(
		'page-builder' => array()
	));
}
```
