### ISSUE TITLE
Failed to load files (js and css)

### ISSUE THREAD

**Issue by deniseqn** [ThemeFuse/Unyson#2193]
Unyson isn't working right. I installed the plugin and but when editing a page, I can't add any element or slider. Only the layout elements are working. I get a lot of errors when inspecting the page. All these errors refer to the elements that aren't working (I think). I get the error: "Failed to load resource: the server responded with a status of 500 (Internal Server Error)". When I open one of the links from the error, there's nothing there. I even checked the File Manager from my webhost, but there are no such things installed by the Unyson plugin.

Is it possible all these stylesheets and javascripts are missing in the downloadfile from Unyson? Because I can't find them, not even when searching true the zip-file on my computer. Or could the problem be something else?

Hope you can help me out.

![2016-11-20 4](https://cloud.githubusercontent.com/assets/23617116/20464592/38477c40-af4a-11e6-962e-53e3ef157080.png)
![2016-11-20 5](https://cloud.githubusercontent.com/assets/23617116/20464594/44f87750-af4a-11e6-855b-ce927645dee0.png)

**Comment by danyj** [comment]
they are not missing , that is 500 server error not 404 , click on one of them and get the error response.

**Comment by deniseqn** [comment]
I get that, but when looking in my file directory. They are missing. Can't find where them at the spot where they should be according to the error.

**Comment by moldcraft** [comment]
Hi

1. Disable all plugins except Unyson
2. Check if file permissions are correct

If nothing helps, send me your admin and ftp credentials to `moldcraft[at]email.com`

**Comment by GheorgheP** [comment]
I think we can close this issue for now, as there is no reply form author.
