### ISSUE TITLE
Unyson Shortcodes module doesn't work in Addable Popup option type

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2194]
Hey

I have just noticed that i can't use Unyson Shortcodes in Addable Popup option type, please look at screenshot attached, Unyson loads CSS stylesheet from a wrong URL (it doubles domain name)

http://mydomain.com//%20http://mydomain.com/mytheme/wp-content/plugi…codes/extensions/wp-shortcodes/static/css/content.css?wp-mce-4401-20160726 

![2016-11-21_09-26-54](https://cloud.githubusercontent.com/assets/12991525/20474023/091636c2-afcd-11e6-853f-042f1d84c245.png)

**Comment by andreiglingeanu** [comment]
```php
'addable'    => array(
	'type'  => 'addable-popup',

	'popup-options' => array(
		'an-editor' => array(
			'type' => 'wp-editor',
			'shortcodes' => true
		)
	)
),
```

This array works on my side fine. Please check any plugins that may modify the way your assets are enqueued, your URL to `content.css` looks strange.

**Comment by WPJobs** [comment]
sorry, i have found the problem

**Comment by andreiglingeanu** [comment]
Great!
