### ISSUE TITLE
Question: Is there a way to hook in to the array that generates options?

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2196]
Let's say a have a drop-down that has some options in it. And when a particular plugin is active, I need to be able to modify those drop-down options from plugin code. Basically I need a hook to add and remove options.

**Comment by moldcraft** [comment]
Why not do `apply_filters('your_filter', $dropdown_options)`?

**Comment by ivandotv** [comment]
Ok, so I have to do my own custom filter. No problem. Thanks.
