### ISSUE TITLE
font-awesome enqueue_style name causes duplicate include of css library

### ISSUE THREAD

**Issue by rrecurse** [ThemeFuse/Unyson#2198]
Due to the use of prefix **fw**-font-awesome within wp_enqueue_style(), if using font-awesome from other plugins or themes, the css libraries are duplicated and parsed to source.

WordPress is nifty in that if properly en-queuing scripts, they won't be duplicated, WP relies on the $handle parameter of `wp_enqueue_style()` to perform this check and avoid parsing duplicate libraries. 

For example, the plugin Revslider uses font-awesome, as does user-role-editor and many other WP plugins. But they all enqueue 'font-awesome', without any prefixes, so only one instance of the library is ever loaded (highest version, is always loaded).

Several Unyson extensions reference this **fw**-font-awesome handle, but in our case, we only use megamenu. 

We modified `/wp-content/plugins/unyson/framework/extensions/megamenu/static.php`, changing:

```php
if (!is_admin()) {
	wp_enqueue_style(
		'fw-font-awesome',
		fw_get_framework_directory_uri('/static/libs/font-awesome/css/font-awesome.min.css'),
		array(),
		fw()->manifest->get_version()
	);
}
```

to 

```php
if (!is_admin()) {
    wp_dequeue_style('fw-font-awesome');
    wp_enqueue_style(
        'font-awesome',
	fw_get_framework_directory_uri('/static/libs/font-awesome/css/font-awesome.min.css'),
	array(),
	fw()->manifest->get_version()
	);
}
```

This change resolved the duplicate css inclusion issue for us. Obviously other references to fw-font-awesome should be updated to use only "font-awesome", allowing WordPress itself to determine best version to use.

Just imagine the performance nightmare if every plugin included its own instance of jQuery (or other widely used libs). Unless this Unyson font-awesome library is customized, it makes little sense to include it as its own standalone version.

This is a revision request.

**Comment by danyj** [comment]
than remove it from mega static via override  and use the WP one in theme static

**Comment by TheMangoTrain** [comment]
Is this resolved?

It's Jan 8 2018 and I still see multiple font-awesome files being downloaded to my browser, including Unyson's. Essentially it's a useless 60kb extra on every page load. I have latest versions for WP and all plugins.

**Comment by danyj** [comment]
@TheMangoTrain check your theme provider, Unyson issue has been resolved and handle is font-awesome as seen here https://github.com/ThemeFuse/Unyson-Feedback-Extension/commit/114b6392ebb9ba3291fc681bf20f5fed92c49697#diff-d9562dc9a0e305f53a6ef22cedcf5d40R151
