### ISSUE TITLE
After installing the demo content, the site doesn't show anything at all

### ISSUE THREAD

**Issue by khangdoan03121993** [ThemeFuse/Unyson#2199]
Hi, I just installed all the required plugins and extensions. Then installed the demo content too but the site shows nothing. Here is the link to the site: http://jobsatsight.com/predictera/ and here is the demo site:
http://planup.haintheme.com/

Can you please check and let me know what's wrong.

**Comment by duongancol** [comment]
Did you enable wp_debug and what is the error?

**Comment by khangdoan03121993** [comment]
As I checked debug.log file, they announced that:
PHP Notice:  Undefined index: site_url in /home/jobsatsight/public_html/predict/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/testimonials/views/view.php on line 53

**Comment by moldcraft** [comment]
This link http://jobsatsight.com/predictera/ doesn't open on my side (endless loading).

**Comment by moldcraft** [comment]
![1479894447159](https://cloud.githubusercontent.com/assets/1475489/20557083/a11c1756-b172-11e6-8308-862265361afc.jpg)

Page html is not fully generated, there is a fatal error in template.

1. Please enable a default WP theme and check if it works.
2. If it doesn't work with a default WP theme, send me your admin and ftp details and I will debug the plugin code.
3. If it works with a default WP theme, then the problem is in your theme (debug it).

**Comment by khangdoan03121993** [comment]
Hi, I checked on the default theme, I got the same problem. How do I send your FTP and admin?

**Comment by moldcraft** [comment]
`moldcraft[at]email.com`

**Comment by moldcraft** [comment]
Only Homepage doesn't work, other pages are working

* http://jobsatsight.com/predictera/register-form/ 
* http://jobsatsight.com/predictera/ht_speakers/

I see that PageBuilder for Homepage contains a lot of elements. Maybe the hosting doesn't have enough memory to process the builder elements? How much RAM the current hosting plan has?

_I enabled `WP_DEBUG` and `WP_DEBUG_LOG` but nothing shows up._

**Comment by moldcraft** [comment]
Also when do Update post for Homepage I get 500 Internal Error.

**Comment by khangdoan03121993** [comment]
The memory of RAM is 512

**Comment by moldcraft** [comment]
@khangdoan03121993 Can you try to create a page front scratch and keep adding and saving build elements until you will reproduce the problem? I think that the problem can be in an inefficient shortcode but I don't know a fast solution to detect that.

**Comment by duongancol** [comment]
hello! we could not find what's exactly the problem come from but here is the error from error.log
`
 in /home/jobsatsight/public_html/predictera/wp-content/plugins/unyson/framework/helpers/class-fw-file-cache.php on line 277`

**Comment by duongancol** [comment]
@moldcraft any news on this, I activated the default theme and this error happen when I added some shortcodes to page builder. and the error.log only showed the errors above. Should we send you the cpanel?

**Comment by moldcraft** [comment]
@duongancol Yes, please send all the credentials again (I deleted the previous email).

**Comment by khangdoan03121993** [comment]
Do you have any update?

**Comment by moldcraft** [comment]
@khangdoan03121993 No, sorry. I am inspecting it now

**Comment by moldcraft** [comment]
1. The `[shortcodes]` string is successfully generated [here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/bf214a754c75294d95cc8260fabd6703881e538b/class-fw-extension-page-builder.php#L341)
2. I saved the resulting string in `wp-content/plugins/unyson/text.txt`
3. I added in `wp-content/plugins/unyson/unyson.php`

	```php
	add_action('wp_head', '_test');
	function _test() {
		fw_print('begin');
		$shortcodes = file_get_contents(dirname(__FILE__) .'/test.txt');
		fw_print($shortcodes);
		fw_print(do_shortcode($shortcodes));
		fw_print('end');
	}
	```

	and it fails

	![screenshot from 2016-11-30 16-22-36](https://cloud.githubusercontent.com/assets/1475489/20755952/968d19be-b719-11e6-93a6-db8a32a33797.png)

----

Inspecting...

**Comment by moldcraft** [comment]
1. `ini_get('memory_limit')` is `64M`
2. I added [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/ceda40e4eef511798ca6ee1811f1384040e3fbea/includes/class-fw-shortcode.php#L151)

    ```php
    wp_ob_end_flush_all();
    fw_print($this->tag, (memory_get_usage(true) / 1024 / 1024) .' MiB');
    ```

    and it fails because of memory limit

    ![screenshot from 2016-11-30 16-38-12](https://cloud.githubusercontent.com/assets/1475489/20756454/67890ec8-b71b-11e6-8c26-5ace9bdf7e80.png)
