### ISSUE TITLE
What is display controls in builder items?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2200]
I found this icon http://prntscr.com/darp4e  but it does not seem to do anything on my end. 
Can someone please explain what it is for.

**Comment by moldcraft** [comment]
On your side it is always visible or you manually made it show up?

It appears on small builder items to not cover the item resize buttons https://vid.me/Ns8g

**Comment by danyj** [comment]
It appears immediately no matter what size items are, even full section, I did not touch any settings or resized the browser, I am on  2560 x 1440  screen
