### ISSUE TITLE
Widget appear closed when is dragged

### ISSUE THREAD

**Issue by biklik** [ThemeFuse/Unyson#2201]
Hi!

I'm trying to grad widgets to the sidebars in backend, but in the firts time when is dragged, it appears closed. Ia the widget os saved, it works fine, but not in the first time. You can see here an image...

https://postimg.org/image/iowyz5a2l/

Thanks!

**Comment by moldcraft** [comment]
https://vid.me/7tWQ

**Comment by biklik** [comment]
Ok! I try in Twenty Sixteen theme and it works.

Maybe is my custom theme, but it does not working yet...
