### ISSUE TITLE
How to check if a Shortcode Exists or Active

### ISSUE THREAD

**Issue by Shahab2905** [ThemeFuse/Unyson#2202]
We have a helper function for extensions:

fw( 'extension_name' ) 

Do we have one for Shortcodes? Since shortcode name is unique, however any extension can contain the shortcode. I have used below for the Shortcode Extension Shortcodes but what about a function independent of the extension?

fw()->extensions->get( 'shortcodes' )->get_shortcode( 'shortcode_name' )

Can we not have one:

fw_shortcode('shortcode_name')

Any help is appreciated.

**Comment by moldcraft** [comment]
We can't have a function in Unyson core related to extensions shortcode. Or you mean to add a helper function [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/ceda40e4eef511798ca6ee1811f1384040e3fbea/helpers.php)?

**Comment by moldcraft** [comment]
If you already have a theme released, you will have to check `if (function_exists(...))` because the users may not have latest shortcodes extension installed.

**Comment by Shahab2905** [comment]
I currently use:

https://gist.github.com/Shahab2905/aed903dcb1586b6305a9a0f4ada288dc

It works as long as the Shortcode Extension exists and the shortcode is part of the shortcode extension. However it wont work if the shortcode is part of another extension. 

Lets say if I have 10 extensions and each contains shortcodes, I will need to know the exact name of the extentions and the shortcode.

My request is, since shortcode names are unique and only one can exist with the same name. Can unyson keep track of all the Shortcodes like Extensions, so that we can easily check if it exists just like Extensions.

fw_ext('extention_name')

fw_shotcode('shortcode_name')

**Comment by moldcraft** [comment]
Hm, it should work this way (all shortcodes should be accessible via Shortcodes extensions). I will check

**Comment by moldcraft** [comment]
I create a shortcode in

```
unyson/framework/extensions/blog/shortcodes/s1
```

and it works

```php
add_action('admin_notices', function(){
	/** @var FW_Extension_Shortcodes $shortcodes */
	$shortcodes = fw_ext('shortcodes');

	fw_print(
		$shortcodes->get_shortcode('s1'),
		array_keys($shortcodes->get_shortcodes())
	);
});
```

![screenshot from 2016-11-24 16-54-51](https://cloud.githubusercontent.com/assets/1475489/20602613/c93bdd6c-b266-11e6-9595-d0362ab952b1.png)

**Comment by Shahab2905** [comment]
Thank you @moldcraft , the method $shortcodes->get_shortcodes() is life saver 👍

**Comment by moldcraft** [comment]
A good IDE with autocomplete is life saver. 

_I recommend [PhpStorm](https://www.jetbrains.com/phpstorm/)_
