### ISSUE TITLE
How to change select option value based on value in another box.

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#2203]
I've a seasons `addable-box`. Inside I've a select `season` with values `winter/summer`.

<img width="697" alt="screen shot 2016-11-23 at 6 56 38 pm" src="https://cloud.githubusercontent.com/assets/8479569/20566512/ce298706-b1ae-11e6-8c39-5286ccafbac3.png">

<img width="444" alt="screen shot 2016-11-23 at 6 56 58 pm" src="https://cloud.githubusercontent.com/assets/8479569/20566532/d8e110ba-b1ae-11e6-903a-3e9fdb3fab01.png">

problem is, that both cannot have same value!

<img width="679" alt="screen shot 2016-11-23 at 6 56 53 pm" src="https://cloud.githubusercontent.com/assets/8479569/20566554/e27e1848-b1ae-11e6-927c-6d08a71794da.png">

Is there anything I can do about this using unyson? Or I just trust user is not an idiot :)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1898#issuecomment-241036398
