### ISSUE TITLE
Map option type - get continent

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2204]
The map option type supplies all kinds of details about a certain location, such as country and city. But as far as I can see it doesn't return the continent for the location. What would be the best way to retrieve that detail?

**Comment by moldcraft** [comment]
Hi,

`map` option-type was created by a developer that is no longer in our team. I am not an expert in Google Maps API and I can't tell if the API returns the continent or not. You can inspect the Google Maps API, inspect option-type's code and figure out if it's possible to add a `'continent'` filed in its value, then come with a pull request.

**Comment by GheorgheP** [comment]
I'm the developer of the Map option type.
I think you need to use the coordinates provided by the option and location the continent.

http://stackoverflow.com/questions/26183873/google-maps-api-get-continent-where-the-country-is-located
http://stackoverflow.com/questions/7627828/coordinates-of-world-continents
