### ISSUE TITLE
[question] fw_framework_customizations_dir_rel_path and DIRECTORY_SEPARATOR

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2206]
Do I need to use the DIRECTORY_SEPARATOR when responding to this filter?

**Comment by moldcraft** [comment]
Please provide a code example.

Yes, you can use `/` or `DIRECTORY_SEPARATOR`, anyway they will be [converted to UNIX style](https://github.com/ThemeFuse/Unyson/blob/3f2f81c22d11e289390fcfcfbca6040ed2b115ea/framework/bootstrap-helpers.php#L7-L18).

**Comment by ivandotv** [comment]
I am developing on unix based system, a was actually concerned about windows directory separators.
Thanks.

**Comment by moldcraft** [comment]
UNIX styles works on windows too (vice versa doesn't work)
