### ISSUE TITLE
Disabling shortcodes

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2208]
Hello!

I'm trying to add an option to disable shortcodes using admin panel, here is my code from `/extensions/shortcodes/hooks.php`:

```php
function _filter_disable_unyson_shortcodes( $to_disable ) {
	$to_disable[] = 'call_to_action';
	$to_disable[] = 'icon';
	$to_disable[] = 'icon_box';
	$to_disable[] = 'team_member';
	$to_disable[] = 'notification';
	$to_disable = array_merge( $to_disable, fw_get_db_settings_option( 'disabled_unyson_shortcodes' ) );	
	return $to_disable;
}

add_filter( 'fw_ext_shortcodes_disable_shortcodes', '_filter_disable_unyson_shortcodes' );
```

this code causes an error: `Undefined option type: table` in admin panel, but if i remove this string, all works fine:

```php
$to_disable = array_merge( $to_disable, fw_get_db_settings_option( 'disabled_unyson_shortcodes' ) );
```

it seems it is impossible to use fw_get_db_settings_option function in disable shortcodes hook?

Thank you in advance

**Comment by moldcraft** [comment]
Please add `fw_print($to_disable);` before `return $to_disable;` and provide the screenshot (or the output code).

**Comment by WPJobs** [comment]
Hi, Modlcraft!

Please look at screenshots, the first is a result of following code:

```
	//$to_disable[] = 'calendar';
	$to_disable[] = 'call_to_action';
	$to_disable[] = 'icon';
	$to_disable[] = 'icon_box';
	$to_disable[] = 'team_member';
	$to_disable[] = 'notification';
	
	fw_print($to_disable);
		
	return $to_disable;

```

the second:

```
	//$to_disable[] = 'calendar';
	$to_disable[] = 'call_to_action';
	$to_disable[] = 'icon';
	$to_disable[] = 'icon_box';
	$to_disable[] = 'team_member';
	$to_disable[] = 'notification';
		
	$to_disable = array_merge( $to_disable, fw_get_db_settings_option( 'disabled_unyson_shortcodes' ) );
	
	fw_print($to_disable);
		
	return $to_disable;
```

![2016-11-28_15-34-48](https://cloud.githubusercontent.com/assets/12991525/20670208/8f4bbab0-b580-11e6-8170-8b905dea87c6.png)
![2016-11-28_15-35-37](https://cloud.githubusercontent.com/assets/12991525/20670211/91a8f872-b580-11e6-8525-42bca4de7067.png)

**Comment by moldcraft** [comment]
1. Do you use option-type `table` in Theme Settings?
2. It will be faster if I will debug the code. Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by WPJobs** [comment]
No, i don't use Table option type in theme settings, i have table shortcode overridden only, but if i remove it from framework-customizations directory, the problem remains. 

I develop website locally, so sorry, i can't get FTP access

**Comment by moldcraft** [comment]
1. This happens with default WP theme?
2. Can you zip your theme and send me the download link to `moldcraft[at]email.com`?

**Comment by WPJobs** [comment]
Sorry for a long-time response, it is possible that we work in different time zones :)

I have uploaded test theme with a minimal code to reproduce, please [download it here](https://drive.google.com/open?id=0Bz6XVdLE4r1fNG1EVTR3dkYxMVk)

How to reproduce an error:

1) Activate "Test" theme
2) Go to Appearance > Theme settings and disable "Widget area" shortcode
3) Go to Pages screen and try to edit any page or create new one

![2016-11-29_10-45-53](https://cloud.githubusercontent.com/assets/12991525/20702570/08145c72-b621-11e6-936b-7f8b40759cde.png)

**Comment by WPJobs** [comment]
@moldcraft could you take a look at my previous message please

**Comment by moldcraft** [comment]
1. [Here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/ceda40e4eef511798ca6ee1811f1384040e3fbea/class-fw-extension-shortcodes.php#L201) shortcodes are not loaded.
2. In filter you call `fw_get_db_settings_option()` which [requires option-types](https://github.com/ThemeFuse/Unyson/blob/3fb4a132bd8e5597ac56a9162c53250d3fbeb70f/framework/helpers/class-fw-db-options-model.php#L181) and option-types are initialized.
3. [Here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/ceda40e4eef511798ca6ee1811f1384040e3fbea/class-fw-extension-shortcodes.php#L202) the shortcodes are loaded (the `table` shortcode too). **But** [this action](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/ceda40e4eef511798ca6ee1811f1384040e3fbea/shortcodes/table/class-fw-shortcode-table.php#L10) in table shortcode will never be executed because option-types were already loaded.

----

Thinking for a solution...

**Comment by WPJobs** [comment]
@moldcraft thank you for looking! Maybe it will be better to use **get_option** instead of **fw_get_db_settings_option**

**Comment by moldcraft** [comment]
That definitely will work. I don't have any idea at the moment how to fix this

**Comment by WPJobs** [comment]
Thank you for your time, @moldcraft 

If someone else needs a solution:

Theme options code:

'disabled_shortcodes' => array(
	'type'  => 'multi-select',
	'value' => array(),
	'label' => __('Disable Shortcodes', 'textdomain'),
	'desc'  => __('Check shortcodes to disable', 'textdomain'),
	'population' => 'array',
	'source' => '',
	'prepopulate' => false,
	'choices' => array( 
		'widget-area' => __('Widget area', 'textdomain')
	),
  'fw-storage' => array(
    'type' => 'wp-option',
    'wp-option' => 'disabled_shortcodes',
  ),
),

shortcodes hooks.php

function _filter_disable_unyson_shortcodes( $to_disable ) {
	
	//$to_disable[] = 'calendar';
	$to_disable[] = 'call_to_action';
	$to_disable[] = 'icon';
	$to_disable[] = 'icon_box';
	$to_disable[] = 'team_member';
	$to_disable[] = 'notification';
		
	$to_disable = array_merge( $to_disable, get_option('disabled_shortcodes') );		
	return $to_disable;
}

add_filter( 'fw_ext_shortcodes_disable_shortcodes', '_filter_disable_unyson_shortcodes' );

**Comment by moldcraft** [comment]
Nice!

One note: The option name is very general `disabled_shortcodes` and can conflict with some plugin. Better prefix it with your theme slug, so it will affect only your theme:

```php
fw()->theme->manifest->get_id() .':disabled_shortcodes'
```

or

```php
get_template() .':disabled_shortcodes'
```
