### ISSUE TITLE
Typography filters does not work

### ISSUE THREAD

**Issue by mintaras** [ThemeFuse/Unyson#2211]
Hi,

Any of typography filters does not work on my project.. Any ideas? 
I'm using The Core theme. Added filters to hook.php, tried on functions.php too

> function test_typography_v2_value($fonts) {
>     array_unshift($fonts, 'Default', 'proxima-nova');
>     return $fonts;
> }
> add_filter('fw_option_type_typography_v2_standard_fonts', 'test_typography_v2_value');

I have other theme which uses Unyson (Wink) and this filter works..

**Comment by mintaras** [comment]
It seems The Core theme has separate custom class for typography where I can add my custom fonts.

**Comment by giathinh910** [comment]
Same issue here. The hook doesn't work anymore. Have you figured out yet?

**Comment by mintaras** [comment]
I have included my fonts inside the-core/theme-includes/includes/option-types/tf-typography/class-fw-option-type-tf-typography.php in get_fonts() method.

**Comment by GheorgheP** [comment]
Did you test with the scratch theme or a default wordpress theme?
The fact is that I just tested and all seems to work fine.

**Comment by giathinh910** [comment]
@mintaras Well, how can we modify the class? I think we can only modify template, can't we? Could you show me more detail?

@GheorgheP I'm working with scrath theme.

**Comment by GheorgheP** [comment]
On the scratch theme the first standard font should be `Arial` adding this function in `functions.php` in child theme should remove the Arial font from fonts list:

```php
function _filter_test_fonts_list( $fonts ) {
	unset( $fonts[0] );
	return $fonts;
}

add_filter( 'fw_option_type_typography_v2_standard_fonts', '_filter_test_fonts_list' );
```

**Comment by giathinh910** [comment]
@GheorgheP I've just tried, it seems still working but not in my includes file (it used to work), I have to move it in functions.php.

Thanks for you help @GheorgheP @mintaras
