### ISSUE TITLE
Is there a way to attach the visual Page Builder to a custom wysiwig field?

### ISSUE THREAD

**Issue by Norskes** [ThemeFuse/Unyson#2213]
Hello
My frontpage has a complicated structure, so it has several custom fields (created with ACF plugin) containing wysiwig editors and grouped by tabs. This is very useful for editing, so I'd like to keep them separated. Is there any way to turn each of those editors into a separate visual constructor (supporting sections, coloumns etc)?

Thanks!

**Comment by moldcraft** [comment]
Hello,

At the moment it's not possible. The wysiwig integration is supported/[hardcoded](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/bf214a754c75294d95cc8260fabd6703881e538b/includes/page-builder/static/js/editor_integration.js#L17) only for main post content editor.
