### ISSUE TITLE
Dissecting map shortcode values. 

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#2215]
I want to customize google map . I have seen that `$map_data_attr` holds the all variables. 
Is there any way to get these values specially latitude values like others?
it seems `var_dump($atts['data_provider'])` returns null. I would like to get these variable in separate variables  say `$lat=$atts['data_provider']['lat']`

**Comment by moldcraft** [comment]
[Here](http://manual.unyson.io/en/latest/options/built-in/map.html#content) is `map` option-type value array structure
