### ISSUE TITLE
Bunch of undefined indexes after update to 2.6.9 stable

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2216]
again  db model is changing 
bunch of notices for Undefined index: from 

https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/class-fw-db-options-model.php#L199

and 

https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/class-fw-db-options-model.php#L147

what is changed this time? 

default vale are set , what now?

**Comment by danyj** [comment]
@moldcraft  the reference removal messed up the indexes on my end 
https://github.com/ThemeFuse/Unyson/pull/2180

**Comment by WPJobs** [comment]
This also happens for me 
![2016-11-29_10-20-23](https://cloud.githubusercontent.com/assets/12991525/20701835/aadac170-b61d-11e6-8f4d-d691c30aae58.png)

**Comment by andreiglingeanu** [comment]
I'm also able to confirm that this is a thing.

**Comment by danyj** [comment]
@WPJobs  how are you calling that maintenance_mode variable , can yo show me please. Thnx , 
without reference the fw_akg seem like overriding second param unless we are doing something funky when calling the options.

**Comment by moldcraft** [comment]
So I can delete [this repository](https://github.com/ThemeFuse/Unyson-Extensions-Approval)?

**Comment by moldcraft** [comment]
How to test/reproduce? I don't have any notices

Maybe because I use PHP 7 ?

**Comment by danyj** [comment]
> So I can delete this repository?

dont get mad , looks like many of us did not see the approval for this version 


look at my email 
http://prntscr.com/dd5n0c

and when you changed the ref I changed the same thing on the copy of your function thz_akg and had no issues with it , so I assumed that the core one would be ok. 


as for php version I am on 7.0.4

**Comment by danyj** [comment]
I dont know how to reproduce it thus I asked @WPJobs , 

I will try to find a way now . few min

**Comment by moldcraft** [comment]
> look at my email http://prntscr.com/dd5n0c

I disabled email notifications, I use only notifications on github site, they are grouped by repository 
![screenshot from 2016-11-29 13-30-03](https://cloud.githubusercontent.com/assets/1475489/20708335/13fe8d5c-b638-11e6-9a98-5b78a75f705e.png)

**Comment by danyj** [comment]
this might help to test , add to functions.php



```
function thz_test_option($id = null,$default= null){
	
	
	global $thz_posthook;
	
	if($thz_posthook){
		
		return fw_get_db_post_option(get_the_ID(),$id ,$default);
		
	}else{
		
		return fw_get_db_settings_option($id ,$default);
	}
	
	
}
```


and this in hooks 


```
function _thz_action_load_options_hooks() {
	
	global $thz_posthook;
	
	$thz_posthook 		= false;
	 if ( !is_admin() ) {
		 
		$post_options 		= fw_get_db_post_option(get_the_ID(),'custom_post_options/0',array());

		
		if(!empty ($post_options)){
			$thz_posthook = true;
		}


	 }
	
}

add_action( 'wp', '_thz_action_load_options_hooks' );
```




than call some option via 


```
$someoption = thz_test_option ('mustbe/an/array', array());


if(!empty($someoption )){
    return 'something';
}
```


undefined indexes come from  fw_get_db_settings_option  and not from  fw_get_db_post_option so far I can tell , not sure why.

**Comment by danyj** [comment]
and test that on blog category page

**Comment by moldcraft** [comment]
```php
function _test_action_debug() {
	fw_print(fw_get_db_post_option(get_the_ID(), 'hello'));
	fw_print(fw_get_db_settings_option('hello'));
}
add_action('wp_head', '_test_action_debug');
add_action('admin_notices', '_test_action_debug');
```

still no warning.

@danyj So when you add back [the reference](https://github.com/ThemeFuse/Unyson/pull/2180) the warning is gone?

**Comment by danyj** [comment]
easier test 

add this in theme/static.php


	// bugs
	$someoption= fw_get_db_settings_option('someoption/something',array());
	$someoption2= fw_get_db_post_option(get_the_ID(),'someoption/something',array());
	
	// no bugs
	$someoption3= fw_get_db_settings_option('someoption',array());
	$someoption4= fw_get_db_post_option(get_the_ID(),'someoption',array());

**Comment by danyj** [comment]
yes when I add ref back error is gone

**Comment by danyj** [comment]
dont use actual existing options , use as something

**Comment by moldcraft** [comment]
@danyj Thank you!

```
Notice: Undefined index: someoption in /.../wp-content/plugins/unyson/framework/helpers/class-fw-db-options-model.php on line 147

Notice: Undefined index: someoption in /.../wp-content/plugins/unyson/framework/helpers/class-fw-db-options-model.php on line 147
```

**Comment by moldcraft** [comment]
```php
function _test() {
	fw_get_db_settings_option('someoption/something', array());
	fw_get_db_post_option(get_the_ID(), 'someoption/something', array());
}
add_action('admin_notices', '_test');
```

**Comment by danyj** [comment]
dont forget to test with number values like 

```
function _test() {
	fw_get_db_settings_option('someoption/something/0', array());
	fw_get_db_post_option(get_the_ID(), 'someoption/something/1', array());
}
add_action('admin_notices', '_test');
```

**Comment by moldcraft** [comment]
```php
function _test() {
	function _test_value($value) {}
	function _test_reference(&$value) {}

	$arr = array('existing_key' => true);
	fw_print(1, $arr);

	_test_value($arr['existing_key']);
	_test_value($arr['not_existing_key']);
	fw_print(2, $arr);

	_test_reference($arr['existing_key']);
	_test_reference($arr['not_existing_key']); // This will create the key!
	fw_print(3, $arr);

	_test_value($arr['existing_key']);
	_test_value($arr['not_existing_key']);
	fw_print(4, $arr);
}
add_action('admin_notices', '_test');
```

![giphy](https://cloud.githubusercontent.com/assets/1475489/20709855/427a0c6c-b640-11e6-8da1-df5e933f4a27.gif)

**Comment by danyj** [comment]
http://stackoverflow.com/a/2030924/594423

by ref is overriding the existing array

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/318

**Comment by danyj** [comment]
> ThemeFuse/Unyson-Extensions-Approval#318

:)  saw it now

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/2216#issuecomment-263559928

I know, when you pass the actual/whole array. [The confusing part](https://github.com/ThemeFuse/Unyson/issues/2216#issuecomment-263558132) is when you pass a not existing key

```php
_test_reference($arr['not_existing_key']); // This will create the key!
```

**Comment by WPJobs** [comment]
@danyj sorry for the late reply basically, i do not call maintenance mode in my code, unyson activates maintenance mode when i update extensions, sorry, can't help you with that :)

**Comment by danyj** [comment]
@WPJobs , we got it sorted out. 

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/318

thnx!
