### ISSUE TITLE
Unyson is causing a conflict with the Elementor page builder

### ISSUE THREAD

**Issue by damjanuzelac** [ThemeFuse/Unyson#2217]
**Unyson is causing a conflict with the Elementor page builder plug-in**
I've tried disabling plugins and unyson is the problem. The CSS of the page gets messed up when unyson is activated.

the settings: http://pastebin.com/Qe3DjZBE
the site: http://humanea.birtija.org/kurikulum/
the plugin: https://github.com/pojome/elementor

I hope someone can help...?

**Comment by danyj** [comment]
be precise bud , what exactly is messed up , before and after screens plus link to the page with error

**Comment by damjanuzelac** [comment]
I've narrowed it down to the SEO extension.
Here are the before and afters: 
![image](https://cloud.githubusercontent.com/assets/18301852/20709886/0348eeda-b638-11e6-86a2-e10814a9537b.png)

**Comment by danyj** [comment]
> plus link to the page with error

**Comment by danyj** [comment]
we cant troubleshoot css from images , need to see what was added/removed

**Comment by damjanuzelac** [comment]
all pages on the site except _landing_ and _blog_ get broken when the SEO extension is active - here's a link http://humanea.birtija.org/kurikulum/

**Comment by moldcraft** [comment]
@damjanuzelac Can you [debug the extension](https://github.com/ThemeFuse/Unyson-SEO-Extension) and find out which action/filter breaks your images?

**Comment by damjanuzelac** [comment]
Sorry, I'm not a programer - how do I do that?

**Comment by moldcraft** [comment]
If you are not a programmer you will not be able to debug it.

Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by moldcraft** [comment]
It works fine on my side https://vid.me/r8kq

**Comment by Freshark** [comment]
Your recent update is conflicting with elementor on my website
I can't edit with elementor shows white screen
Pages are not loading properly
