### ISSUE TITLE
Cursor changes to arrow from small hand pointing to links

### ISSUE THREAD

**Issue by djderex** [ThemeFuse/Unyson#2218]
Cursor changes to arrow from small hand pointing to links after the last Unyson update, at WordPress 4.6.1 running Recover theme.

How to fix this ? 

Thanks

**Comment by moldcraft** [comment]
Hello,

1. Have you reported the problem to theme author?
2. How to test the problem? Can you provide a screenshot or create a video?

**Comment by GheorgheP** [comment]
I think we can close it for now as there are not any additional information about the issue.
