### ISSUE TITLE
Warning: session_start(): Cannot send session cache limiter

### ISSUE THREAD

**Issue by kowsar89** [ThemeFuse/Unyson#2219]
This error comes when i open Visual Composer fronend editor in php 7:

```
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at E:\wamp64\www\wp\wp-includes\script-loader.php:1304) in E:\wamp64\www\wp\wp-content\plugins\unyson\framework\helpers\class-fw-session.php on line 13
```

Please fix

**Comment by moldcraft** [comment]
Please make a screenshot of the page, I think there are more errors.

Also test [this version](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/318) maybe it's related

**Comment by kowsar89** [comment]
I checked version 2.6.10 and this error still exists in frontend editor mode. My visual composer version is 5.0.

You can't see this error normally because it's hidden behind the screen. You can see it when you open "view source" mode of that page. Here's a screenshot:

![screenshot_1](https://cloud.githubusercontent.com/assets/6196149/20741542/258bc5f4-b6f5-11e6-93c6-b5f39161695f.jpg)

Here's a clean version of this screenshot:

![screenshot_2](https://cloud.githubusercontent.com/assets/6196149/20741577/6a14f54c-b6f5-11e6-909b-3c4f0f3fea94.jpg)

**Comment by moldcraft** [comment]
```
output started at E:\wamp64\www\wp\wp-includes\script-loader.php:1304
```

https://github.com/WordPress/WordPress/blob/4.6.1/wp-includes/script-loader.php#L1304

----

I don't know why it happens. I need to debug the code. Can you send me your admin and ftp credentials to `moldcraft[at]email.com`

**Comment by kowsar89** [comment]
I've done my testing in localhost(while wp debug mode is on). Can't you replicate the issue?

**Comment by moldcraft** [comment]
I don't have visual composer

**Comment by kowsar89** [comment]
Sent you email yesterday, hopefully you found it

**Comment by moldcraft** [comment]
There is no warning on my side https://vid.me/EZ6C

**Comment by kowsar89** [comment]
Your screenshot is from backend editor. Try frontend editor instead

**Comment by moldcraft** [comment]
Still no warnings

![screenshot from 2016-12-02 15-58-39](https://cloud.githubusercontent.com/assets/1475489/20836599/c6333212-b8a8-11e6-8e6c-95dccac61c75.png)

**Comment by kowsar89** [comment]
Please check page source while you're in frontend editor mode

**Comment by moldcraft** [comment]
Check for what?

**Comment by kowsar89** [comment]
You can use find tool or ctl+f from browser and search for text 'warning'.  I already sent a screenshot previously which was taken from page source

**Comment by kowsar89** [comment]
Alternatively you can search inside 'inspect element' tool too

**Comment by moldcraft** [comment]
No warning in html https://vid.me/T3w7
No warning in error.log

**Comment by kowsar89** [comment]
Just sent admin details in your email. Please log in from there.

Then visit this link: [view-source:http://kowsarhossain.com/staging/test/wp-admin/post.php?vc_action=vc_inline&post_id=2&post_type=page](view-source:http://kowsarhossain.com/staging/test/wp-admin/post.php?vc_action=vc_inline&post_id=2&post_type=page)

Check line 162

**Comment by moldcraft** [comment]
1. I clicked on the link in email
2. Enter my email
3. I got message "Check your email for the confirmation link."
4. I haven't received any confirmation link.

**Comment by kowsar89** [comment]
Sorry for your trouble. Please check your email again, this time i included all details

**Comment by moldcraft** [comment]
I need to change the code. Please send me ftp credentials

**Comment by kowsar89** [comment]
Sent
