### ISSUE TITLE
Shouldn't this be yellow sidebar ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#222]
If this is blue
http://screencast.com/t/wW7VS86nUD8j
And this is 
http://screencast.com/t/XAw8OJHdw
blue - yellow

than shouldn't this be yellow 
http://screencast.com/t/tt617SDNgx7

with current setup I end-up not having the sidebar because I am expecting the right one 

	<?php if ($current_position == 'right' || $current_position == 'left_content_right'): ?>
	<div id="rightblock" class="sidebars">
		<div class="inside-container">
			<?php echo fw_ext_sidebars_show('yellow'); ?>
		</div>
	</div>
	<?php endif; ?>

**Comment by danyj** [comment]
do you guys mind labeling this so that I could know if it is going to be worked on. thank you.

**Comment by danyj** [comment]
@sergiubagrin frate! Help me on this one :)

**Comment by sergiubagrin** [comment]
@danyj 

> than shouldn't this be yellow http://screencast.com/t/tt617SDNgx7

When we started with sidebars extension we decided that all pages in the same project will include the same number of sidebars Ex: 0, 1, 2, 3, 4.  

I will explain a project with 2 sidebars (Left & Right):
We can create 5 types of pages when we have 2 sidebars:

1. 0 sidebars: Full Width Page
2. 1 sidebar: Page with Left or Right Sidebar
3. 2 sidebars: Page with Left and Right Sidebar

HTML for 0 sidebars 

```
<div class="content">CONTENT</div>
```

HTML for 1 sidebar: 

```
<div class="blue-sidebar">BLUE SIDEBAR</div>
<div class="content">CONTENT</div>
```

```
<div class="content">CONTENT</div>
<div class="blue-sidebar">BLUE SIDEBAR</div>
```

HTML for 2 sidebars

```
<div class="blue-sidebar">BLUE SIDEBAR</div>
<div class="content">CONTENT</div>
<div class="yellow-sidebar">YELLOW SIDEBAR</div>
```

```
<div class="yellow-sidebar">YELLOW SIDEBAR</div>
<div class="content">CONTENT</div>
<div class="blue-sidebar">BLUE SIDEBAR</div>
```

PHP for this type of page:

```php
<?php 
// https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/sidebar.php
if (function_exists('fw_ext_sidebars_get_current_position')) : ?>
	<?php $current_position = fw_ext_sidebars_get_current_position()?>
	<?php if ( $current_position !== 'full' ) : ?>
		<?php if ($current_position === 'left' or $current_position === 'left_right' ) : ?>
			<?php echo fw_ext_sidebars_show('blue'); ?>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>

<div class="content">CONTENT</div>

<?php 
// https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/sidebar-content.php
if ( function_exists('fw_ext_sidebars_get_current_position') ) : ?>
	<?php $current_position = fw_ext_sidebars_get_current_position();?>
	<?php if ($current_position !== 'full') : ?>
		<?php if ($current_position === 'right') :?>
			<?php echo fw_ext_sidebars_show('blue'); ?>
		<?php endif;?>
		<?php if ($current_position === 'left_right') :?>
			<?php echo fw_ext_sidebars_show('yellow'); ?>
		<?php endif ?>
	<?php endif;?>
<?php endif; ?>
```

Scratch theme sidebars:

https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/sidebar.php
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/sidebar-content.php

**Comment by sergiubagrin** [comment]
@danyj 

> than shouldn't this be yellow http://screencast.com/t/tt617SDNgx7

When we started with sidebars extension we decided that all pages in the same project will include the same number of sidebars Ex: 0, 1, 2, 3, 4.  

I will explain a project with 2 sidebars (Left & Right):
We can create 4 types of pages when we have 2 sidebars:

1. 0 sidebars: Full Width Page
2. 1 sidebar: Page with Left or Right Sidebar
3. 2 sidebars: Page with Left and Right Sidebar

HTML for 0 sidebars 

```
<div class="content">CONTENT</div>
```

HTML for 1 sidebar: 

```
<div class="blue-sidebar">BLUE SIDEBAR</div>
<div class="content">CONTENT</div>
```

```
<div class="content">CONTENT</div>
<div class="blue-sidebar">BLUE SIDEBAR</div>
```

HTML for 2 sidebars

```
<div class="blue-sidebar">BLUE SIDEBAR</div>
<div class="content">CONTENT</div>
<div class="yellow-sidebar">YELLOW SIDEBAR</div>
```


PHP for this type of page:

```php
<?php 
// https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/sidebar.php
if (function_exists('fw_ext_sidebars_get_current_position')) : ?>
	<?php $current_position = fw_ext_sidebars_get_current_position()?>
	<?php if ( $current_position !== 'full' ) : ?>
		<?php if ($current_position === 'left' or $current_position === 'left_right' ) : ?>
			<?php echo fw_ext_sidebars_show('blue'); ?>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>

<div class="content">CONTENT</div>

<?php 
// https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/sidebar-content.php
if ( function_exists('fw_ext_sidebars_get_current_position') ) : ?>
	<?php $current_position = fw_ext_sidebars_get_current_position();?>
	<?php if ($current_position !== 'full') : ?>
		<?php if ($current_position === 'right') :?>
			<?php echo fw_ext_sidebars_show('blue'); ?>
		<?php endif;?>
		<?php if ($current_position === 'left_right') :?>
			<?php echo fw_ext_sidebars_show('yellow'); ?>
		<?php endif ?>
	<?php endif;?>
<?php endif; ?>
```

Scratch theme sidebars:

https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/sidebar.php
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/sidebar-content.php

**Comment by danyj** [comment]
Maybe I do not see the logic here but to me your HTML 1  second code example should be

<div class="content">CONTENT</div>
<div class="blue-sidebar">YELLOW SIDEBAR</div>

You are calling them left and right yet in your code no matter if you have the condition for left or right you are  calling blue every time.

When you call them both  you have 

left - content - right   
OR
yellow - content - blue 

but when you call them one by one you always call blue. 

Makes no sense code or design wise.

**Comment by sergiubagrin** [comment]
If i have a project with 1 sidebar this sidebar will be BLUE. Second sidebar on the same page will be Yellow. Color means sidebar number not position. Developer will decide where sidebar will be displayed. 

Examples: http://screencast.com/t/qu5hxYMJxe 
Page example: http://screencast.com/t/WaFCc510

In next scratch theme we will exclude names like left, right

**Comment by danyj** [comment]
that is exactly what is trowing me off ,
you color coded the number of sidebars
full = 0 sidebars
blue = 1 sidebar
yellow = 2 sidebars
and so on  but diagram looks like sidebars  left and right layout  and says Choose the position for your sidebar(s)  not choose number of sidebars. 

So I am lost now as I am sure users would be also. 
Not sure if I should use your sidebar 
http://screencast.com/t/oi4gDz7u
for  left content right  layouts   or add my own option 
http://screencast.com/t/SLDy4GHRM

I wanted to use yours since it lets user assign different layout on different pages but 
the logic is different than standard left - right combos. 

Look at this video , http://screencast.com/t/wFZncMxeurn and you will see the issue I am facing.

**Comment by danyj** [comment]
And now if I dont use your sidebar_positions array and add 2 or 3 more sidebars http://screencast.com/t/6kMnh0mnM
this adds more to the confusion and the sidebar extension becomes a burden rather than solution.
