### ISSUE TITLE
add explanatory images to short code builder popup

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#2220]
How can I include explanatory images on the shortcode popup?

Ideally when user clicks shortcode builder and popup opens, I'd like to have header image explaining what each input controls.

![unnamed](https://cloud.githubusercontent.com/assets/8479569/20711023/dd9efd18-b656-11e6-8b90-8e00f28c8963.png)

**Comment by moldcraft** [comment]
Hi,

At the moment it's not possible.

**Comment by sandrodz** [comment]
@moldcraft any hacky way you can think of? I could create a description on container with img tag, would that work? inside popup itself I mean.

**Comment by moldcraft** [comment]
Somewhere in your theme use an array

```
'shortcode_name' => 'http://.../explanatory-image.jpg'
```

then wp_localize_script that array and from javascript on [this even](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/a578f874b8cbd31d0c65aa09bb84efeba078af0a/includes/option-types/builder/static/js/initialize-builder.js#L452)

```js
jQuery(document.body).on('fw:option-type:builder:init', function(e, data){
    console.log(data); // ...
});
```

find in DOM and init the thumbnails with tooltips containing your images

![staticshot_29-11-2016_15-55-24](https://cloud.githubusercontent.com/assets/1475489/20712484/dff33124-b64c-11e6-8298-f24b02bb5edf.png)

**Comment by sandrodz** [comment]
got it! thx. I will hack it in, but it would still be awesome to see this as a feature.

My interfaces are sometimes complicated and images clarify more than words.
