### ISSUE TITLE
Can we have shortcode views folder php files "see" shortcode $atts ( options )  ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2221]
Is there any way to get a specific builder shortcode atts ( options ) outside the shortcode view.php? 

For example via some id pull shortcode data? 

I need to use all atts inside the ajax and would like to send the shortcode "ID" ( if there is such thing )  to ajax function and than pull all its saved options.

**Comment by danyj** [comment]
@moldcraft  or even better is there a way for shortcode views files to get the atts ? 

example I have 


`shortcode/views/ view.php  `


and 

`shortcode/views/post-item.php`


inside the view there is a  post query and within its loop I am doing 




` fw_render_view ('path_to_post-item.php', $options);`


the $options are passed to the post-item file via 



`$options = array('atts' => $atts);`



this works fine on normal page view and post-item.php has all options 

but if I than try to call the post-item.php via ajax  I have no other way to send the options to it but to have them be embeded as json in html , sent via ajax and read again. 

a perfect solution would be that any php vile placed within shortcode/views folder

like here https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/master/shortcodes/icon-box/views

 should be able to "see" that shortcode options , otherwise we have to think of funky ways to find the shortcode options within depended files.

**Comment by danyj** [comment]
If we can get this than I can use a recommended way  

`get_template_part()`

to include the file within the loop and everything would be according to standards.

**Comment by danyj** [comment]
or if you dont like the idea of "every" file , give as a  template hook for additional views like a comment 

/**
 Template Name: Some part
 */

**Comment by danyj** [comment]
or auto pass the $atts to any vile with name or part name view like 

```
view.php
view-post-item.php
view-post-filter.php
```

@moldcraft  @andreiglingeanu  cmon bud,  it is a huge workaround when I need to create posts shortcode that loads items via ajax. Almost impossible to follow WP coding guidelines , pass options to including files files  and use ajax at the same time. 

This shortcode improvement would help everyone.

**Comment by danyj** [comment]
or please help me ad least get the atts_string  in included file via 

    get_queried_object_id()


than I could use 

    fw_ext_shortcodes_decode_attr

anything please.

**Comment by andreiglingeanu** [comment]
There's no easy of getting data for a specific shortcode identified by an ID. You would need at least the post ID in order to extract the data.

Provided the fact that you've got somehow the `post_id` you can extract data about _every_ shortcode this post contains:


```php
// Here's all the data you may need
// You'll have to figure out a way to find filter all of those items by ID
// This should be done recursively, because shortcodes may be contained in sections/columns
// And please be aware of the fact that the structure of this JSON _may_ change over time
fw_print(fw_get_db_post_option($your_post_id, 'page-builder')['json']);
```

**Comment by danyj** [comment]
yes but that gives , me the whole  pagebuilder options , with all sections 

I tried already 

```
$pageop = fw_get_db_post_option(get_queried_object_id(),'page-builder/json');
fw_print(json_decode($pageop,true));
```

and cant risk it to pull so much data in each item and loop trough

thnx for respinse.

**Comment by andreiglingeanu** [comment]
> and cant risk it to pull so much data in each item and loop trough

There's no risk to break something, as long as you're making this looping in one single AJAX request. If you are doing this multiple times for multiple items -- provide a cache for this big JSON.

There's really no other way of doing that. Besides, of course, encoding shortcode atts in the HTML itself, which I wouldn't even consider.

**Comment by danyj** [comment]
>  atts in the HTML itself, which I wouldn't even consider.

yes a dumb thing that works and pisses me off that I cant send the data out any other way

**Comment by danyj** [comment]
>  long as you're making this looping in one single AJAX request

hm , will try but this is just pain to loop trough the complete page builder code , seems like no one has tought ahead that shortcodes would use ajax

**Comment by andreiglingeanu** [comment]
Unyson doesn't even provide an unique ID by default for each shortcode - developers have to add it for themselves. Of course there wouldn't be a centralized storage for each shortcode. Of course I can create some sort of function that will loop through each post till it will find such an ID, but this will create more problems than solutions.

**Comment by danyj** [comment]
> , but this will create more problems than solutions.

I know it will , just thinking out loud here to find some hook to use

**Comment by danyj** [comment]
Posts via ajax  is the most widely spread shortocde , http://www.kriesi.at/themes/enfold/portfolio/masonry-portfolio/

and for us as a framework  not to have access to the data in every shortcode file is bad

**Comment by andreiglingeanu** [comment]
> hm , will try but this is just pain to loop trough the complete page builder code

Not that hard after you understand how the Page Builder structures its data, there can't be more than 3 level of shortcodes:

```
section -> column -> simple
section -> simple
column -> simple
simple
```

> just thinking out loud here to find some hook to use

Sadly, there's no such hook

**Comment by danyj** [comment]
yeah , I have to dig deeep  to find it , 
http://prntscr.com/ddok9c
http://prntscr.com/ddokp6

and think of all ways , 
is it inside the section , 
outside 
inside the column and so on , 

pure pain in the ...

**Comment by andreiglingeanu** [comment]
I didn't run the code. That's just the outline of it.

```php
// Usage

$searcher = new SearchJson($your_shortcode_id); // probably pass here post_id for JSON search
$search->parse();
$search->get_result(); // item

class SearchJson {
	public function __construct($id) {
		$this->id = $id;
		$this->result = null;
	}

        public function get_result () {
            return $this->result;
        }

	public function parse() {
		$json = $this->read_json();

		$this->parse_options($json);
	}

	private function parse_options($json) {
		foreach ( $json as $item ) {
			if ( 'column' === $item['shortcode'] ) {
				$this->parse_options($item['_items']);
			} elseif ( 'section' === $item['shortcode'] ) {
				$this->parse_options($item['_items']);
			} else {
				$this->parse_options_simple($item);
			}
		}
	}

	private function parse_options_simple($item) {
		if ($item['unique_id'] === $this-id) {
			$this->result = $item;
		}
	}
}
```

**Comment by danyj** [comment]
I think we are missing a method 

read_json


I have this in shortcode options 


			'id' => array(
				'type' => 'unique',
				'length' => 8
			),

and also can use 

    get_queried_object_id()

here 

`$searcher = new SearchJson($your_shortcode_id);`


right ?

**Comment by andreiglingeanu** [comment]
I didn't tried to provide a working code, please change it as you want and need. The `read_json` method should return the whole Page Builder structure from the `fw_get_db_post_option($post_id, 'page-builder/json')`. And yes, you are right about `get_queried_object_id`, you can try to use that in order to extract data.

**Comment by danyj** [comment]
kiss your brain my friend! thank you!!!!!

**Comment by andreiglingeanu** [comment]
Welcome!
