### ISSUE TITLE
In unyson latest version 2.6.10 Page Builder extension showing php error when create new page?

### ISSUE THREAD

**Issue by therakib7** [ThemeFuse/Unyson#2224]
Hello,
Yesterday I updated unyson latest Version 2.6.10 and unyson Page Builder extension  is activated.  when creating new page showing error like this. 
Notice: Undefined index: builder_active in http://domain.com\wp-content\plugins\unyson\framework\extensions\shortcodes\extensions\page-builder\includes\page-builder\includes\option-storage\class-fw-option-storage-type-post-meta-page-builder.php on line 28

I don't know what's the problem is.
Have you any solution?

Thanks

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/319
