### ISSUE TITLE
Request failed. Error code: 403

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2227]
I am trying to install demo content on server.  But problem is I am getting this error on server "Request failed. Error code: 403"
![GitHub Logo](https://puu.sh/sCGHP/5cbfd1ed90.png)

**Comment by moldcraft** [comment]
Try this

```php
add_action('admin_notices', function(){
    fw_print(wp_remote_get('YOUR_DEMO_URL'));
});
```
