### ISSUE TITLE
how to configure reserbation form in welcomeinn template ?

### ISSUE THREAD

**Issue by sr-source** [ThemeFuse/Unyson#223]
After moving my templaete to other server reservation form doesn't work. Please tell me where i can configure it.

**Comment by ziuzea87** [comment]
Hi,

all questions related the our themes need to be asked via our website or send an email to support[at]themefuse.com. Here can be asked questions only related to Unyson framework which doesn't have anything to do with with welcome inn theme.

Cheers,
Max.
