### ISSUE TITLE
Adding Cc, Bcc and Other Mail Headers ?

### ISSUE THREAD

**Issue by dam62500** [ThemeFuse/Unyson#2230]
hi, 
It's possible to add mail headers like Bcc?

**Comment by moldcraft** [comment]
Hello,

At the moment it's not possible. I will add this feature but can't give any eta.

**Comment by moldcraft** [comment]
Please test

1. [Download](https://github.com/ThemeFuse/Unyson-Mailer-Extension) and extract the Mailer extension in `unyson/framework/extensions/mailer`
2. [Download](https://github.com/ThemeFuse/Unyson-Forms-Extension) and extract the Forms extension in `unyson/framework/extensions/forms`
3. Use [these filters](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/cd3a90467e3d77e613a90f2a59d9f1d83983b7e0#diff-ec141aa42759cc0c7735796a2c061f60R151)
