### ISSUE TITLE
extension installation errors

### ISSUE THREAD

**Issue by anisur210** [ThemeFuse/Unyson#2231]
Hi

Getting this error when trying to download extensions. Thanks!

Screenshot : `http://support.xpeedstudio.com/?wpas-attachment=16503`

**Comment by danyj** [comment]
it means that custom option types from your theme need to be registered on 

    fw_option_types_init


action

**Comment by anisur210** [comment]
Hi

We are using the Unyson latest version 2.6.10 then how we will register it?

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/options/create-option-type.html#content

**Comment by anisur210** [comment]
Hi
But we are not using any custom option types only use default option types. I am really confused how I solve this issue?

**Comment by moldcraft** [comment]
What is your error message?

**Comment by anisur210** [comment]
`http://prntscr.com/dgem3u`

**Comment by moldcraft** [comment]
This is an old issue https://github.com/ThemeFuse/Unyson/issues/2096#issuecomment-252485193
