### ISSUE TITLE
Contact form labels

### ISSUE THREAD

**Issue by pionir** [ThemeFuse/Unyson#2232]
Hello everyone. 
I am working with the contact forms and I found a little bug I think.

When I add a filed for example, single line text, and I don't want to show the label I need to make the element not mandatory field so the label is not shown. But after that the label is still inside the HTML and it's creating a space. 

`<label for="id-1"></label>`

Also when I want to make the field, mandatory field and don' want to show the label text, the star * is still showing inside the label. 

`<label for="id-2"><sup>*</sup></label>`

**Comment by danyj** [comment]
bug confirmed.
