### ISSUE TITLE
Showing error when a add tab in a tab in customizer settings field

### ISSUE THREAD

**Issue by therakib7** [ThemeFuse/Unyson#2233]
Hello,
When I add a tab in a tab it works fine in Theme Settings Field. Like the following screenshot.
http://prntscr.com/dgbfi9

But when  add the same type of field in customizer settings showing an error. like this.
Warning: id_name panel can't have a parent (parent_id_name) in http://domain.com\wp-content\plugins\unyson\framework\core\components\backend.php on line 1781

Have you any solution to solve the problem?
Advance Thanks

**Comment by moldcraft** [comment]
Hello,

Have you [read this](http://manual.unyson.io/en/latest/options/customizer.html#content)?
