### ISSUE TITLE
fw-storage for term_meta

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#2234]
Hi,
to save taxonomy options in separate locatio ( single term_meta ) is necessary to create a new class to extend FW_Option_Storage_Type?
if yes, how can get current term id to retrive option value in method "load_value"?
(e.g. get_term_meta( ???, 'key', 'value' ))

thanks

**Comment by moldcraft** [comment]
Hello,

I will add the built-in possibility to save in separate term_meta

**Comment by moldcraft** [comment]
Done https://github.com/ThemeFuse/Unyson/commit/731e5dafb0ed7813ab0f8781961b4adc6d8a8a25

Please test Unyson latest dev version.
