### ISSUE TITLE
Sortable does not work properly in popups and or builder

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2235]
I made custom sortable checkboxes option type which works fine in theme settings, 
you can sort the order of checkboxes and the output array is sorted by the user order , 

this does not work if option is inside the popup since it seems like the checkbox array stays the same but only the values are updated on popup save. 

to test you can simply add this in console 

`   $('.fw-option-type-checkboxes-inline').sortable();`

when popup is saved and reopened the order is correct , but when page is saved the order returns to what it is by default. 

Is there any way to update the builder/popup json for the order?

**Comment by danyj** [comment]
correction , in popup it works , the builder is not getting updated on popup save

**Comment by moldcraft** [comment]
Checkboxes option-type is rendered based on hardcoded `choices` option parameter, not based on db value https://github.com/ThemeFuse/Unyson/blob/43b6a1e1dee556c9934dd2acc065d53948cb4d15/framework/includes/option-types/simple.php#L484

**Comment by danyj** [comment]
how come it works in theme options than , 
the sorting and array output , can I send you the option type?

**Comment by moldcraft** [comment]
Sure, always provide an easy way to reproduce the problem.

**Comment by danyj** [comment]
thnx!

add this test option in theme settings , reorder items and check output , and than add it inside a shortcode option and do same. 


test option 


```
'test_checkbox' => array(
	'type' => 'thz-checkboxes',
	'value' => array(
		'option1' => true,
		'option5' => true,
	),
	'label' => __('Elements', 'fw'),
	'choices' => array(
		'option1' => __('Option 1', 'fw'),
		'option2' => __('Option 2', 'fw'),
		'option3' => __('Option 3', 'fw'),
		'option4' => __('Option 4', 'fw'),
		'option5' => __('Option 5', 'fw')
	),
	'inline' => true,
	'sortable' => true
),
```


I sent you the option type on skype


you check option js file , yesterday I borrowed the script from sorable option , but below is simplified version of mine , either way it works only in theme settings

**Comment by moldcraft** [comment]
I will inspect this later.

**Comment by moldcraft** [comment]
When I click popup Save, the server response is

```
{"success":true,"data":{"values":{"test_checkbox":{"option5":true,"option4":true,"option2":true,"option1":true},"text":"","text_color":"red"}}}
```

but the js decoded value is

![screenshot from 2016-12-09 14-23-46](https://cloud.githubusercontent.com/assets/1475489/21049033/23998e16-be1b-11e6-8cfc-818f0c44ec34.png)

because of this http://stackoverflow.com/q/5525795/1794248

----

If your values are always `true`, maybe instead of

```php
'value' => array(
	'option1' => true,
	'option5' => true,
),
```

change the structure to

```php
'value' => array('option1', 'option5'),
```

?

**Comment by moldcraft** [comment]
I don't know a good solution for this problem

**Comment by moldcraft** [comment]
P.S. Recently I created [this function](https://github.com/ThemeFuse/Unyson/commit/e378efd45e4d6b7435ebac5a836a7556c866a920#diff-1a10d08376d32331dbdc651256766d37R1654). In your option-type instead of 

```php
$uri = get_template_directory_uri() .'/inc/includes/option-types/'. $this->get_type() .'/static';
```

you can do

```php
$uri = fw_get_path_url(dirname(__FILE__)) .'/static';
```

and the option-type will be portable (no hardcoded url).

_Of course that function does some computation and the hardcoded way is faster._

**Comment by danyj** [comment]
thnx , for the path !
as for the order , il check more

**Comment by danyj** [comment]
strange , than seems like `OptionsModal `save is doing this ,  in theme settings we dont have the conversion , data is sent directly to server , 
![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/21075959/b5eb016e-bf1f-11e6-9498-27acf939a334.png)

but strange thing is that the actual data is correct ,


![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/21075955/949af816-bf1f-11e6-8e1d-0c8195a2b77f.png)

**Comment by danyj** [comment]
solved. new option type for sorting checks. thnx!
