### ISSUE TITLE
Access Shortcode Option within page-builder-section-item Script Display in column-title

### ISSUE THREAD

**Issue by MikeiLL** [ThemeFuse/Unyson#2236]
Hi We are using a lot of Sections and I have each one named in a shortcode option.

I would love for the Admin to be able to see what that name is _without_ having to open the Section options modal.

I see that the Section modal is build by `page-builder-section-item/static/js/scripts.js`.

Can you recommend a way to expose the options within that script so that I can display one of them in the modal?

**Comment by MikeiLL** [comment]
Came up with adding this to the javascript:

```
var title = this.templateData.title + ' ' + this.model.get('atts').section_name,
```

Around line 110 in `render: function () {`

**Comment by moldcraft** [comment]
Hi,

Do you know about the [`title_template` config parameter](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file)?
