### ISSUE TITLE
anchored accordion tabs

### ISSUE THREAD

**Issue by gabrielevlt** [ThemeFuse/Unyson#2238]
Hello! Is the accordion title anchorable? Let me explain what I mean:

in an arbitrary page I have a link, let's say http://www.domain.ext/page#tabname ;

Inside the page "page" I've built an accordion with tabs, let's say tabA, tabB, tabC.

Is it possible to associate an anchor to the accordion tab title so when one clicks the link http://www.domain.ext/page#tabB the page will load with the tabB open?

the same with http://www.domain.ext/page#tabC, the link will load the page with tabC open and so on...

How can I achieve something like this? is it feasable?

**Comment by danyj** [comment]
this is js question not unyson related but here is what you would need
`
someurl/#opentab`

```
			if (location.href.match('opentab')) {
				
				$('.tab_to_open_class').trigger('click');
			}
```

**Comment by gabrielevlt** [comment]
Thank You very much @danyj .

I am new to Unyson and I am trying to learn as mush as I can.

Are You that kind to help me to understand where I need to insert this snippet?

**Comment by danyj** [comment]
is not a snippet , it is a suggestion ,  you need to "read" the browser link ,  match the hook and execute the tab click. I dont know your theme and what files you have , your best bet is to contact theme provider.

**Comment by gabrielevlt** [comment]
oh, OK! Now it is more clear to me. Thank You!
