### ISSUE TITLE
Errors appearing on the front-end and back-end.

### ISSUE THREAD

**Issue by tiagocaus** [ThemeFuse/Unyson#2239]
Errors appearing on the front-end and back-end.

> Please register builder item-types on 'fw_option_type_builder:{builder-type}:register_items' action
> Please register builder types on 'fw_option_type_builder:{builder-type}:register_items' action
> Please register builder types on 'fw_option_types_init' action

Image 1: http://image.prntscr.com/image/80ca600041b34892988f8733854615e2.png

Image 2: http://image.prntscr.com/image/80ca600041b34892988f8733854615e2.png

**Comment by moldcraft** [comment]
Hi,

1. With a default WP theme the errors persist?
2. Are Unyson extensions up-to-date? (Go to Updates page and click Check Again)

**Comment by tiagocaus** [comment]
It's not a theme issue. The error is in the admin "wp-admin".

This all updated "Unyson 2.6.10".

**Comment by moldcraft** [comment]
Please try to delete Unyson plugin and install it back.

**Comment by tiagocaus** [comment]
How to do this?

**Comment by moldcraft** [comment]
1. Go to `/wp-admin/plugins.php` and press Delete
2. Go to `/wp-admin/plugin-install.php` and install Unyson
3. Go to `/wp-admin/admin.php?page=fw-extensions` and install the extensions

**Comment by tiagocaus** [comment]
One of the errors disappeared, but there is still another:

`Please register builder types on 'fw_option_type_builder:{builder-type}:register_items' action`

Image: http://image.prntscr.com/image/994a6e6ec9694111b0a553b6e6651b79.png

**Comment by moldcraft** [comment]
@tiagocaus Activate a default WP theme and check if the error persists. If it persists -  you have outdated extension, if no - then your theme is outdated and you should contact the theme author.
