### ISSUE TITLE
Contact Form Produce "Notice" in debug bar

### ISSUE THREAD

**Issue by indopixel** [ThemeFuse/Unyson#2240]
Hi,

My contact form producing "NOTICE" in debug bar but didn't affect the functionality. It send emails successfully. I was using SMTP in the mailer setup. This is the complete message from debug bar : 

```
NOTICE: wp-includes/functions.php:325 - unserialize(): Error at offset 2365 of 41663 bytes
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/teatime/page-templates/smpixel-page-nosidebar.php'), get_template_part, locate_template, load_template, require('/themes/teatime/content-page-nosidebar.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, FW_Shortcode->render, FW_Shortcode->_render, fw_render_view, require('/plugins/simplepixel-teatime-extension/extensions/shortcodes/shortcodes/section/views/view.php'), do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, FW_Shortcode->render, FW_Shortcode->_render, fw_render_view, require('/plugins/simplepixel-teatime-extension/extensions/shortcodes/shortcodes/column/views/view.php'), do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, FW_Shortcode->render, FW_Shortcode_Contact_Form->_render, FW_Extension_Contact_Forms->_set_form_db_data, _FW_Ext_Contact_Form_DB_Data::set, _FW_Ext_Contact_Form_DB_Data::delete_data_from_old_location, FW_Extension->get_db_data, fw_get_db_extension_data, FW_WP_Option::get, get_option, maybe_unserialize, unserialize
```

Thank you

Best Regards,
Bismoko Widyatno

**Comment by danyj** [comment]
> themes/teatime

please contact theme provider , this is framework support , your theme provider has extended the framework and the errors are coming from those extends.

**Comment by indopixel** [comment]
Hi,

I'm the theme provider, I didn't touch any of the contact form class, I'm just changing the form html structure. 

The error didn't show up in the localhost. When I upload to my hosting server (shared hosting), this error comes up.

**Comment by indopixel** [comment]
Hi again, 

I didn't know what the cause of this issue but when I tried to create a new demo content from my localhost then run it on my hosting server this problem didn't show up again.

Thank you so much for the great plugin. I'm closing this issue. :)
