### ISSUE TITLE
Form submit error but message is sent

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#2241]
When submitting a contact form I'm seeing an alert with the error `Ajax error (more details in console)`. The console error is shown below.
While I'm getting this error the email **does** actually send to the recipient.
Site: http://www.bluemoondiscos.co.uk/
![image](https://cloud.githubusercontent.com/assets/4599099/21031376/02553f0a-bd9b-11e6-8cdf-34baaa2a7e0f.png)

**Comment by moldcraft** [comment]
Hi,

Please go to `/wp-admin/options-general.php` and check if **WordPress Address (URL)** and **Site Address (URL)** are the same.

**Comment by moldcraft** [comment]
Ajax response is empty

![screenshot from 2016-12-12 13-38-20](https://cloud.githubusercontent.com/assets/1475489/21098103/4a0d7d30-c070-11e6-86d3-8b3b7d3eba15.png)

You need to debug if execution reaches [this point](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/6c98fd4b5cc73b9a9cc374c088df11a7ff74dc7d/class-fw-extension-forms.php#L237), or send me your admin and ftp credentials to `moldcraft[at]email.com`

**Comment by martinburdon** [comment]
Thanks @moldcraft.
I had an email reply (that's not showing up on this thread for some reason, deleted?) that said:
`Please go to /wp-admin/options-general.php and check if WordPress Address (URL) and Site Address (URL) are the same.`
This turned out to be the issue, the addresses did not match, one had `www` the other didn't, corrected and tested and all is working now.

Thanks 👍
