### ISSUE TITLE
Problem with extensions 

### ISSUE THREAD

**Issue by alicjamarciniak** [ThemeFuse/Unyson#2242]
Hello,
I've just update Unyson and I'm using Jevelin theme. Few days ago everything was fine. Now I found few problems: 
1) In editing site section (all sites -> edit site) SEO in almost not appearing (only empty bordered box) and page builder lost graphical interface. In fact - almost every extension is crushed somehow... 

![2](https://cloud.githubusercontent.com/assets/15956876/21033225/558c7b7a-bdaf-11e6-80b4-bba43d70b02e.png)
![3](https://cloud.githubusercontent.com/assets/15956876/21033224/558c442a-bdaf-11e6-86f0-b05277c03ab1.png)
![4](https://cloud.githubusercontent.com/assets/15956876/21033223/558c3ff2-bdaf-11e6-9bd4-35794099b91f.png)
---------------------------------------------

2) Page builder settings cannot render 

![1](https://cloud.githubusercontent.com/assets/15956876/21033226/558ccc1a-bdaf-11e6-8b9e-bc07a7d19747.png)
---------------------------------------------

3) Theme editing suported by Unsydon cannot load - it freezes in loading state (img:

![5](https://cloud.githubusercontent.com/assets/15956876/21033227/558d2552-bdaf-11e6-9c57-9563bc94ccd2.png)

------------------------------------------------

I tested if this issue appear with default wordpress theme - unfortunately yes... And only components connected with Unyson have those problems. 

I would greatly appreciate if you could help me with those problems.
Thank you in advance!

**Comment by alicjamarciniak** [comment]
I've already overcome those problems.
#1 (everything beside invisible page builder) and #2 - was caused by some additional plugin - I supose the sticky social icons plugin
#1 (page builder) - and this is thing I would highly suggest you to fix. It's described in this post: https://github.com/ThemeFuse/Unyson/issues/1362 - arrow which is not displayed sometimes.

**Comment by moldcraft** [comment]
Hello,

Without error messages and the exact steps to reproduce the problem I can't help.
