### ISSUE TITLE
In what case is this fwForm  html used?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2243]
On my end all 

    ajaxData.flash_messages

are returning something so I dont know why is this hardcoded. 

https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw-form-helpers.js#L78

**Comment by moldcraft** [comment]
I don't remember. Can you make a pull request?

**Comment by moldcraft** [comment]
In case it doesn't return anything, the user must see some "Success" instead of empty box.

**Comment by moldcraft** [comment]
I can't translate it because that javascript is being included by others in frontend with their own `wp_enqueue_script()` function call.
