### ISSUE TITLE
Button Sent for Contact Form

### ISSUE THREAD

**Issue by LeoMoshko** [ThemeFuse/Unyson#2245]
Hello,
if there is a possibility to place a button in line with the field?

![image](https://cloud.githubusercontent.com/assets/9072581/21054147/b7a61096-be2c-11e6-85dd-4eafc6351ed6.png)

Thank for  help
Leo

**Comment by moldcraft** [comment]
Hello,

Form html is generated [here](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/4361bc5c26b79cc113ed553085c6e16abc6945e8/class-fw-extension-forms.php#L68) and submit button is printed [here](https://github.com/ThemeFuse/Unyson/blob/35db8bda12b4fc1cfecdc2a015370106f8fdd157/framework/helpers/class-fw-form.php#L471-L478). Can you figure out a solution and come up with a pull request?
