### ISSUE TITLE
'population' => 'taxonomy' is not show 'source' items after update the page.

### ISSUE THREAD

**Issue by NiloySarker** [ThemeFuse/Unyson#2246]
Hi,
I made Course Tab by using unyson shortcode .
Here is the backend Preview : http://prntscr.com/dhy69q &
Here is the Frontend Preview :  http://prntscr.com/dhy6pc
Everything is working fine as I expect but the problem is start when I save it and update the page :(
Here are the screenshots below after save and update the shortcode.
- I just select 2 categories from the source > http://prntscr.com/dhy7je and then save it.
- After then when I again open this shortcode for editing the categories than as you can see there is only two categories what i was saved in last time http://prntscr.com/dhy81m .
- But it's  need to show all categories like this http://prntscr.com/dhy69q

Here is the backend code i use for this http://prntscr.com/dhy8l6 .
I am confused at this stage .
am i missing something or it's a Bug ?

**Comment by moldcraft** [comment]
Hello,

I added in button shortcode this option

```php
$options = array(
	'test' => array(
		'type' => 'multi-select',
		'population' => 'taxonomy',
		'source' => 'category',
	),
	//...
);
```

and everything works fine https://vid.me/czvE

Please provide the exact steps to reproduce the problem.

**Comment by NiloySarker** [comment]
Hi,
please check this video
https://www.youtube.com/watch?v=P7osz2Jyxe8

**Comment by danyj** [comment]
I can confirm this , same on my end 

http://take.ms/x9GOe

**Comment by danyj** [comment]
@moldcraft , is not after save , but after popup close , you dont see any additional tax but the one you have selected

**Comment by moldcraft** [comment]
Fixed. Please download latest Unyson dev version and test

```php
$options = array(
	'test_1' => array(
		'label' => 'Taxonomy',
		'type' => 'multi-select',
		'population' => 'taxonomy',
		'source' => 'category',
	),
	'test_2' => array(
		'label' => 'Pages',
		'type' => 'multi-select',
		'population' => 'posts',
		'source' => 'page',
	),
	'test_3' => array(
		'label' => 'Users',
		'type' => 'multi-select',
		'population' => 'users',
	),
	'test_4' => array(
		'label' => 'Users Administrators',
		'type' => 'multi-select',
		'population' => 'users',
		'source' => 'administrator',
	),
	'test_5' => array(
		'label' => 'Array',
		'type' => 'multi-select',
		'population' => 'array',
		'choices' => array(
			'choice-1' => __('Choice 1', '{domain}'),
			'choice-2' => __('Choice 2', '{domain}'),
			'choice-3' => __('Choice 3', '{domain}'),
		),
	),
);
```

**Comment by Energeticthemes** [comment]
Hi guys,
Stile facing this issue. 
Unyson v2.6.16

 check this video
https://monosnap.com/file/Z783rAFKtSZYdF5FCwaPSfMKuYFyaV

**Comment by GheorgheP** [comment]
Please provide the options array you use.

**Comment by Energeticthemes** [comment]
I used this one array.

	'test_1' => array(
		'label' => 'Taxonomy',
		'type' => 'multi-select',
		'population' => 'taxonomy',
		'source' => 'category',
	),

**Comment by GheorgheP** [comment]
This does work properly for sure. Please activate a WordPress default theme and try one more time.

**Comment by Energeticthemes** [comment]
I checked it with Scratch Parent Version: 1.0.7 By ThemeFuse.
Only Unyson plugin activated not any other.
Here is video check it out. 
https://monosnap.com/file/1XR6JBXegadI1FybjqOherGLviSDE3

**Comment by GheorgheP** [comment]
No, this is a mistake made in the scratch theme settings options.
In the **Demo Options** tab are 2 sub-tabs **Without Box** and **With Box**, they have same options, and same ids for options. So you select the posts for `multi-select` in **Without Box** tab, but in **With Box** you did not select anything, and because they have same name, on submit is taken the value of the `multi-select` from  **With Box** tab, because it is rendered after the `multi-select`  **Without Box** tab. If you would select posts in `multi-select` of the  **With Box** tab, after refresh they will appear in the  **Without Box** tab too.

**Comment by NiloySarker** [comment]
When this bug will fixed ?
