### ISSUE TITLE
Is gallery reserved pagebuilder shortcode name?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2248]
I made gallery shortcode but there is no frontend output. When I change the folder name to anything else but gallery everything is ok. Is this reserved name? Are there more reserved names?

**Comment by mowshon** [comment]
Try to remove shortcode first.
```
remove_shortcode('gallery');
```

**Comment by danyj** [comment]
@mowshon  thnx for reply , I am talking about the page builder shortcodes ,

**Comment by moldcraft** [comment]
We should create all our shortcodes prefixed with `fw_` but we realized that after the release and there was already content created by users. Other plugins may also define shortcodes without prefix. So the safest way is to prefix all your shortcodes `thz_gallery` to prevent conflicts.

**Comment by danyj** [comment]
thnx, np, so basically there is conflict with default gallery shortcode as @mowshon  said right?

**Comment by andreiglingeanu** [comment]
> basically there is conflict with default gallery shortcode as @mowshon said right

Yep. Unyson shortcodes are registered in the same namespace with [WordPress](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/class-fw-extension-shortcodes.php#L212) ones. They only differ in flexibilities they provide.
