### ISSUE TITLE
Gallery edit buttons z index higher than options popup

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2249]
Our options popup has lower z-index than gallery edit buttons 

![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/21082062/8fa86a3c-bfd3-11e6-895d-809bb6069054.png)

**Comment by moldcraft** [comment]
Hello,

Where to find this? Can you provide the options array?

**Comment by danyj** [comment]
no options array , create post gallery ,  after gallery add unyson shortcode  from editor and open it , 
or open any available options popup you might have on post edit page


mine are in postbox-with-fw-options,

**Comment by moldcraft** [comment]
The steps to reproduce

1. Add an image in post content
2. Add an Unyson WP Shortcode
3. Click on image to show the image edit toolbar
4. Click on Unyson shortcode to open the shortcode options modal
5. The image edit toolbar will be on top of Unyson modal

**Comment by moldcraft** [comment]
I don't know how to access from js that image edit toolbar to hide it.

**Comment by moldcraft** [comment]
In wp-editor option-type was a similar problem with link editor toolbar, we have found how to access it from js and call the `.close()` method https://github.com/ThemeFuse/Unyson/blob/35db8bda12b4fc1cfecdc2a015370106f8fdd157/framework/includes/option-types/wp-editor/static/scripts.js#L104-L120

**Comment by danyj** [comment]
funny thing is if you see the bug and click on f12 , it hides it , so maybe trigger window resize after render?
not sure if that would effect something else.

**Comment by moldcraft** [comment]
1. Open Inspector (F12)
2. Do https://github.com/ThemeFuse/Unyson/issues/2249#issuecomment-266723618
3. `jQuery(window).trigger('resize');` The toolbar is still there

**Comment by moldcraft** [comment]
Also when I do manual resize to window the toolbar doesn't hide.
