### ISSUE TITLE
Time Slider Option

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#225]
I want to custom slider option like this: http://i.imgur.com/rsOMHsR.png
But when I followed instruction on IonRangeSlider site it showed number instead of value of array(http://i.imgur.com/TpZSrhA.png)
My custom code here:
  `'pre_hour' => array(
                     'type'  => 'slider',
                         'properties' => array(
                         'type' => 'double',
                         'min' => 'aloha',
                         'max' => 'bloha',
                        'values' => array('aloha', 'bloha', 'cloha')
                    ),
                ),`

**Comment by valeriuzdrobau** [comment]
We made a few [changes](https://github.com/ThemeFuse/Unyson/commit/731ff26cd2fbf0ea0a3c5ad820239107b31fa39c) and it is now possible to do what you wanted you, but be aware that we have two options ['slider'](http://manual.unyson.io/en/latest/options/built-in-option-types.html#slider) for single and[ 'range-slider'](http://manual.unyson.io/en/latest/options/built-in-option-types.html#range-slider) for double (parameter 'type' of properties is not taken into consideration ). Example of use for 'range-slider':   
```php 
'period' => array(	
    'type' => 'range-slider',
    'properties' => array(
	   'values' => array(
	       'May',
	       'June',
	       'July',
	       'August',
	       'September',
	       'October',
	       'November',
	      'December'
	 )
     ),
   'value'     => array(
	'from'  => 'August',
	'to'    => 'November'
      )
)```

**Comment by duongancol** [comment]
Thank you! 
Actually I want a slider for timeline like : http://i.imgur.com/qJba5tY.png
And I know it's really difficult to customize slider option like this. But it's ok now.
I hope that you'll create a slider option for timeline, maybe other users'll need it like me.

**Comment by sergiubagrin** [comment]
@duongancol - we will analyse this option in future right now we have a lot of work to so on different extenstions. Thanks
