### ISSUE TITLE
google map routes

### ISSUE THREAD

**Issue by saeidnr** [ThemeFuse/Unyson#2250]
hey everybody
i am trying to add a from field so they can select from with area they are coming and they can see a route to my direction like this: https://google-developers.appspot.com/maps/documentation/javascript/examples/directions-panel
i did changed everything but at last there is a error "initMap is not a function" what can i do?
( i did add defer async ass well)
thanks

**Comment by moldcraft** [comment]
Hello,

Debug the code and find why `initMap` is defined too late.
