### ISSUE TITLE
unyson visual builder for themefuse the core in no longer appearing 

### ISSUE THREAD

**Issue by peloloro** [ThemeFuse/Unyson#2256]
Howdy guys, can you please help me?
Daily I've been using unyson visual builder to update the sections of my website, in wordpress, using thecore theme, but suddenly today it simply stopped appearing on the pages, either to create a new page or to edit some existing page.
In fact, I can no longer view the elements/shortcodes of content, media, etc. In Visual Builder.
I use the latest version of wordpress, theme and also unyson.
Your help here will be much appreciated.
See the print below, hope it helps.
![unyson issue 1](https://cloud.githubusercontent.com/assets/24557588/21167142/8ff728b0-c191-11e6-8491-dc8a333ac3e7.jpg)
![unyson issue 2](https://cloud.githubusercontent.com/assets/24557588/21167143/8ffb933c-c191-11e6-8e39-56627a2b8a4d.jpg)

**Comment by Ataurr** [comment]
First, deactivate all 3rd party plugin and try again.

Same issue occurred when I used itheme securty plugin.

**Comment by danyj** [comment]
also ,  get used to ,  chrome , F12 , console log,  looking at pretty interface does not help much.

**Comment by llemurya** [comment]
One of our customer have the same issue. I tried to find the problem and I hope this [video](http://www.screencast.com/t/ii3UNOeWlig) will help, also this [link](https://core.trac.wordpress.org/ticket/27697) will be helpful.

**Comment by andreiglingeanu** [comment]
@llemurya 4082e4d2313283dd25b3af6776ce54e3dcd91d76

**Comment by moldcraft** [comment]
Hi,

Run this code in browser console

```js
jQuery('#fw-options-box-page-builder-box > .hndle').trigger('click');
```
