### ISSUE TITLE
blank page : Notice: Undefined offset: 0 class-wp-query.php on line 3080

### ISSUE THREAD

**Issue by schroll** [ThemeFuse/Unyson#2259]
Hello,
There is a conflict between Unyson and my theme, when I activate Unyson, my site is inaccessible if I am not logged to the admin.
Thank you for your help.
http://le1513.com/

**Comment by albertso** [comment]
Disable all extensions and see if any are causing the problem.
It's strange that Unyson is causing this.
What theme are you using?

If you read the error message, look in [Wordpress' class-wp-query.php line 3080](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php#L3080):

    $this->post = $this->posts[$this->current_post];

Wordpress is not finding the current post in the array of posts, the index is probably too big.

Your theme could be using the_post() too many times.
Look in {yourtheme}/index.php, {yourtheme}/page.php, {yourtheme}/archive.php, etc. 
Check that have_posts() is being used in [the loop](https://codex.wordpress.org/The_Loop).

**Comment by moldcraft** [comment]
Hi,

The problem was in theme, caused by the Coming Soon script.
