### ISSUE TITLE
How to bulk update posts or update via external script

### ISSUE THREAD

**Issue by pr0fess0r** [ThemeFuse/Unyson#226]
Hey guys

I'm working with a theme built based on Unyson. It's a vehicle trading site that uses WP All Import to bring in vehicles via XML. Editing individual vehicles (posts with a type of vehicle) and clicking Update will push the vehicle to the front end of the theme and populate a table called tf_autotrader_seek_index_posts
However with a number of vehicles being imported, this isn't practical, so I'm trying to write an external PHP script to run via cron to update all vehicles and thus publish them to the front end after an import.

Calling wp_update_post() via my script doesn't do the same thing as clicking Update in the Edit Posts page.

How can I call the required functions to emulate a click on the Update button and publish more than one post at once?

Many thanks in advance and if I've posted int eh wrong place I apologise, and would appreciate any assistance on where to post.

Cheers

Lucas

**Comment by sergiubagrin** [comment]
> Calling wp_update_post() via my script doesn't do the same thing as clicking Update in the Edit Posts page.

Sorry but i don't see how Unyson can help you to import remote data to a WP. Can you give me more details?

**Comment by pr0fess0r** [comment]
Hi
The data import is working fine.
What I need help with is being able to update posts via an external PHP file (i.e. via  cron job)
The imported vehicles are turned into posts.
These posts do not appear on the front end of the website until you edit each individual post and click the Update button.
We need a way to update all posts at once without having to update them manually.
Calling wp_update_post() via an external script doesn't do the same thing as clicking Update in the Edit Posts page.
Clicking update seems to call a lot of functions in wp-admin/post.php
How can we replicate that functionality in a scheduled task?
I'd be happy to provide the login details for the site if you like.
Thanks again for your help :)

Lucas

**Comment by sergiubagrin** [comment]
@pr0fess0r - i understand what you mean. Sorry but i don't see how Unyson plugin (this github repository is related to Unyson plugin) can help you to import remote data to a WP. 

Maybe it is a theme/ wordpress problem not Unyson plugin issue?

**Comment by moldcraft** [comment]
This is a question about [Auto Trader theme](http://themefuse.com/wp-themes-shop/auto-wordpress-theme/) and has nothing with Unyson framework (the theme is not built with Unyson). Please contact ThemeFuse support.
