### ISSUE TITLE
Google maps showing wrong place, Unyson Event Extension

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#2260]
Google map not appearing correctly in this page

http://www.outcrafter.com/graha2/events/opn-house-2917-michigan-ave-los-angeles-ca-90033/

I've given this co-ordinates -40.7143528,-74.0059731

But this is what it is showing , any insights would be helpful
![001](https://cloud.githubusercontent.com/assets/11642633/21222783/bd93f6e6-c2e9-11e6-9ad6-1027c699379c.png)

**Comment by moldcraft** [comment]
Hello,

I see in demo the maps work fine http://themes.layero.com/grahaneo/contact-us/

Can you debug the map shortcode scripts to detect the problem?

**Comment by linjo** [comment]
Hi

I am saying about the Unyson EVENTS extension and in the single events page

http://www.outcrafter.com/graha2/events/opn-house-2917-michigan-ave-los-angeles-ca-90033/

I've checked events extension folder in the plugins.

plugins/unyson/framework/extensions/events

Looks like there is an issues in  the helpers.php  fw_ext_events_render_map() function

I dont see where this values comes from,

	'lat' => $options['event_location']['coordinates']['lat'],
	'lng' => $options['event_location']['coordinates']['lng']

When I var_dump the value it looks like the value is hardcoded

 Array ( [lat] => -34 [lng] => 150 ) ) 

I've not given this value anywhere.

Please assist asap

**Comment by moldcraft** [comment]
I enabled a default WP theme then I added here

```php
```

**Comment by moldcraft** [comment]
I enabled a default WP theme then I added [here](https://github.com/ThemeFuse/Unyson-Events-Extension/blob/1f2c6d1bc24eac9819a7461cbd76287855aec3d5/helpers.php#L41)

```php
fw_print($options['event_location']['coordinates']);
```

and it works fine

![staticshot_20-12-2016_09-18-51](https://cloud.githubusercontent.com/assets/1475489/21341474/57055d0c-c695-11e6-9055-baf02bf49fe5.png)

**Comment by GheorgheP** [comment]
Usually this problem comes from the Maps API Key, you have to renew it. This may happen because you reached the API limits.
