### ISSUE TITLE
Options popup click page jumps

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2261]
We had this issue before with builder elements 
https://github.com/ThemeFuse/Unyson/issues/815

but now every options popup jumps the page , even in theme settings,

http://take.ms/2e8zE

**Comment by moldcraft** [comment]
This happens with WP Upload modal too (and we use wp modal js api)

**Comment by moldcraft** [comment]
https://vid.me/Ctfs

**Comment by moldcraft** [comment]
This should be reported to WP devs

**Comment by danyj** [comment]
https://core.trac.wordpress.org/ticket/39460#ticket

**Comment by andreiglingeanu** [comment]
Yeah, can confirm that. I've got a long exploration of `wp.media` internals while building the modal for `icon-v2` option type. I've got no luck in solving that problem, but that was not my goal, to be honest.

I'll probably give it one more shot soon.

**Comment by moldcraft** [comment]
cc @andronic90
