### ISSUE TITLE
a lot of images with Drag & Drop Page Builder -  the page cannot be saved and displayed

### ISSUE THREAD

**Issue by shurhotvalery** [ThemeFuse/Unyson#2262]
Hello, I use the Journal theme with UNYSON FRAMEWORK, and I was faced with the problem:
I create some page, and when I place more, then 25 pictures on this page under Drag & Drop Page Builder, the page cannot be saved and displayed, and I receive the message like this:
**Can not display this page
ERR_CONNECTION_RESET**

PS: pictures are 240width x 340height and theirs sizes from 24kb to 160kb

**Comment by moldcraft** [comment]
Hello,

> then 25 pictures on this page under Drag & Drop Page Builder

How? Slider, wp-editor gallery, Image shortcodes? How to reproduce the problem?

**Comment by shurhotvalery** [comment]
Hello, thank you for reply.  I was offline for several days...
It is when I add "Image" elements from "Media Elements" tab in Visual Page Builder. Of course I put them in one of Content Elements

**Comment by moldcraft** [comment]
I works fine on my side https://vid.me/mGrF

Check your server error.log
