### ISSUE TITLE
Theme Check plugin shows an error because of Unyson

### ISSUE THREAD

**Issue by maryslen** [ThemeFuse/Unyson#2263]
Hi,

We checked our theme using Theme Check plugin and it shows a required for fixing issue:
```
Line 28: * Sends a POST request to the reCAPTCHA service, but makes use of fsockopen() 
Line 86: if ($this->socket->fsockopen('ssl://' . self::RECAPTCHA_HOST, 443, $errno, $errstr, 30) !== fa
WARNING: fsockopen was found in the file Socket.php possible file operations.
Line 36: * fsockopen
Line 38: * @see http://php.net/fsockopen
Line 46: public function fsockopen($hostname, $port = -1, &$errno = 0, &$errstr = '', $timeout = nul
Line 48: $this->handle = fsockopen($hostname, $port, $errno, $errstr, (is_null($timeout) ? ini_get('
REQUIRED: The theme uses the register_taxonomy() function, which is plugin-territory functionality.
REQUIRED: The theme uses the register_post_type() function, which is plugin-territory functionality.
```

We checked that fsockopen is used in our theme only in Captcha shortcode that is obligatory in unyson. The same with 'register_pots_type' - it is used only in unyson portfolio.  How we can get rid of those errors? 

Thanks a lot!

**Comment by danyj** [comment]
you should be using Unyson as a plugin not in theme if you want it on WP or TF,

**Comment by maryslen** [comment]
We are using unyson as a plugin and still we have framework-customizations folder for styling only. We use unyson as it is described in unyson documentation.

**Comment by danyj** [comment]
ok than you must have moved some files to customization that should not be there , 

I also have portfolio and forms overrides and have no theme check errors

**Comment by maryslen** [comment]
I have CAPTCHA error, but i never stylized it or created new files in that shortcode folder.

**Comment by danyj** [comment]
what folder/file exactly please

**Comment by thednp** [comment]
@maryslen can we please have some info on this? I am getting none of that on my setup.

Ultimately, I highly recommend checking with the boss here @moldcraft moldcraft@email.com

**Comment by GheorgheP** [comment]
I know that the **Theme Check** would recommend to use the `wp_get_remote` function or something similar, but in our case this is impossible, as the `fsockopen` function is called in the official  **Google ReCaptcha** php library, and e cannot modify it.
And the ThemeForest support should look in deeper in the code where the warning appear rather just send back you the theme because the id did not pass **Theme Check** test.
