### ISSUE TITLE
PHP Notice since WP 4.7 update

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2264]
Hi, after updating to WP 4.7, on Unyson extensions installation screen, now PHP notice displays :)

Notice: class-wp-upgrader-skins.php is deprecated since version 4.7.0! Use class-wp-upgrader.php instead. in \test.com\wp-includes\functions.php on line 3911

**Comment by moldcraft** [comment]
The url to see the problem `/wp-admin/admin.php?page=fw-extensions&sub-page=delete&extension=page-builder`
