### ISSUE TITLE
How to use fw-storage in Theme Options and Customizer

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2265]
Hi!

Sorry for this questions, but it is still not clear how to use fw-storage to make same options in customizer and theme options screen

https://github.com/ThemeFuse/Unyson/issues/2170
https://github.com/ThemeFuse/Unyson/issues/1388

i'm trying to save Customizer and Theme Options in same location, my option has following code:

```
'top_bar_enabled' => array(
	'type' => 'multi-picker',
	'label' => false,
        'fw-storage' => array(
                'type' => 'wp-option',
                'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
                'key' => 'top_bar_enabled',
    	 ),
	'picker' => array(
		'enabled' => array(
			'label' => esc_html__( 'Enable Top Bar', 'mytheme' ),
			'type' => 'switch',
			'left-choice' => array(
				'value' => 'no',
				'color' => '#ccc',
				'label' => esc_html__( 'No', 'mytheme' )
			),
			'right-choice' => array(
				'value' => 'yes',
				'label' => esc_html__( 'Yes', 'mytheme' )
			),
			'value' => 'no',
		)
	),
	'choices' => array(
		'yes' => array(
		
			'top_bar_content' => array(
				'type'  => 'text',
				'label' => esc_html__('Content', 'mytheme'),
				'value' => '',
			),
		
		)
	)
),
```

this saves Theme options, but doesn't affect an option in Customizer, i always get Top Bar disabled in customizer but it enabled in Theme Options

Also i have a question: how to use fw-storage for Addable Popup option type, should i use parent_option/current option schema for key? Currently it doesn't work for me at all

```
'fw-storage' => array(
  'type' => 'wp-option',
  'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
  'key' => 'parent_option/current_option',
),
```

please could you help with that?

**Comment by WPJobs** [comment]
One more question, if i'll use fw-storage > wp option for customizer options, does it mean that i can't use fw_get_db_customizer_option() to get an option saved in this way?

**Comment by moldcraft** [comment]
> this saves Theme options, but doesn't affect an option in Customizer

* Add in Theme Options

```php
'top_bar_enabled' => array(
	'type' => 'multi-picker',
	'label' => false,
        // ...
```

(no `fw-storage` here)

* Add in Customizer

```php
'top_bar_enabled' => array(
	'type' => 'multi-picker',
	'label' => false,
	'fw-storage' => array(
                'type' => 'wp-option',
                'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
                'key' => 'top_bar_enabled',
    	 ),
	// ...
```

**Comment by moldcraft** [comment]
> Currently it doesn't work for me at all

How `fw-storage` works:
-- Dear Unyson, please save (and load) this option's value in a separate wp_option.
-- Ok grand master WP developer, please tell me in which wp_option to save it. Also would you like to overwrite the wp_option or just save the value in a separate array key?

> `'key' => 'parent_option/current_option',`

What is parent and current?

> One more question, if i'll use fw-storage > wp option for customizer options, does it mean that i can't use fw_get_db_customizer_option() to get an option saved in this way?

All `fw_get_db_..._option()` [are aware](https://github.com/ThemeFuse/Unyson/blob/ea4a4ec7afe31554305ababf22fe78007ac979ea/framework/helpers/class-fw-db-options-model.php#L181) of the `fw-storage` parameter, so it will work fine, this is the intended way.

**Comment by WPJobs** [comment]
Sorry, @moldcraft but it doesn't work for me. Please look at attached theme (it contains just one theme option and one customizer option), try to save this option in customizer and then go to Theme options and check

Test theme https://drive.google.com/open?id=0Bz6XVdLE4r1fYlhtTEI0bjBiMTQ

![2016-12-20_17-17-41](https://cloud.githubusercontent.com/assets/12991525/21355859/4b9c5bbc-c6d8-11e6-82e8-f0454041f1b4.png)

![2016-12-20_17-17-56](https://cloud.githubusercontent.com/assets/12991525/21355875/50ddf04a-c6d8-11e6-9c3f-807897c9bc84.png)

Customizer.php code:

`<?php

$options = array(
  'header' => array(
    'title' => esc_html__('Header', 'mytheme'),
    'type' => 'tab',
    'options' => array(
    
		  'top_bar' => array(
		    'title' => esc_html__('Top bar', 'mytheme'),
				'type' => 'box',
		    'attr' => array(
	        'class' => 'prevent-auto-close'
		    ),
		    'options' => array(
		    
					'top_bar_enabled' => array(
						'type' => 'multi-picker',
						'label' => false,
						'fw-storage' => array(
						  'type' => 'wp-option',
						  'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
						  'key' => 'top_bar_enabled',
						),
						'picker' => array(
							'enabled' => array(
								'label' => esc_html__( 'Enable Top Bar', 'mytheme' ),
								'type' => 'switch',
								'left-choice' => array(
									'value' => 'no',
									'color' => '#ccc',
									'label' => esc_html__( 'No', 'mytheme' )
								),
								'right-choice' => array(
									'value' => 'yes',
									'label' => esc_html__( 'Yes', 'mytheme' )
								),
								'value' => 'no',
							)
						),
						'choices' => array(
							'yes' => array(
							
								'top_bar_elements' => array(
									'type'          => 'addable-popup',
									'label'         => esc_html__( 'Top Bar Elements', 'mytheme' ),
									'popup-title'   => esc_html__( 'Add/Edit', 'mytheme' ),
									'desc'          => esc_html__( 'Add some top bar content', 'mytheme' ),
									'template'      => '{{if( type.elem_type == "text" ) return type.text.content; if( type.elem_type == "text_icon" ) return type.text_icon.content; if( type.elem_type == "social_icons" ) return type.social_icons.content; }}',
									'fw-storage' => array(
									  'type' => 'wp-option',
									  'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
									  'key' => 'top_bar_elements',
									),
									'popup-options' => array(
									
										'type' => array(
											'type' => 'multi-picker',
											'label' => false,
											'desc' => false,
											'value' => array(
												'elem_type' => 'text',
											),
											'picker' => array(
												'elem_type' => array(
													'label' => esc_html__( 'Element type', 'mytheme' ),
													'type' => 'radio',
													'choices' => array(
														'text' => esc_html__( 'Text', 'mytheme' ),
														'text_icon' => esc_html__( 'Text and Icon', 'mytheme' ),
														'social_icons' => esc_html__( 'Social icons', 'mytheme' ),
													),
												)
											),
											'choices' => array(
												'text' => array(
												
													'content' => array(
														'type'  => 'text',
														'label' => esc_html__('Content', 'mytheme'),
														'value' => '',
													),
													'move_right' => array(
														'label' => esc_html__( 'Move to the right', 'mytheme' ),
														'type' => 'switch',
														'left-choice' => array(
															'value' => 'no',
															'color' => '#ccc',
															'label' => esc_html__( 'No', 'mytheme' )
														),
														'right-choice' => array(
															'value' => 'yes',
															'label' => esc_html__( 'Yes', 'mytheme' )
														),
														'value' => 'no',
													),
												
												),
												'text_icon' => array(
												
													'content' => array(
														'type'  => 'text',
														'label' => esc_html__('Content', 'mytheme'),
														'value' => '',
													),				
													'icon' => array(
												    'type'  => 'icon-v2',
													),
													'move_right' => array(
														'label' => esc_html__( 'Move to the right', 'mytheme' ),
														'type' => 'switch',
														'left-choice' => array(
															'value' => 'no',
															'color' => '#ccc',
															'label' => esc_html__( 'No', 'mytheme' )
														),
														'right-choice' => array(
															'value' => 'yes',
															'label' => esc_html__( 'Yes', 'mytheme' )
														),
														'value' => 'no',
													),
												
												),
												'social_icons' => array(
												
													'content' => array(
														'type'  => 'hidden',
														'value' => esc_html__('Social Icons', 'mytheme'),
													),		
													'facebook_url' => array(
														'type'  => 'text',
														'label' => esc_html__('Facebook URL', 'mytheme'),
														'value' => '',
													),
													'twitter_url' => array(
														'type'  => 'text',
														'label' => esc_html__('Twitter URL', 'mytheme'),
														'value' => '',
													),
													'linkedin_url' => array(
														'type'  => 'text',
														'label' => esc_html__('LinkedIn URL', 'mytheme'),
														'value' => '',
													),
													'google_plus_url' => array(
														'type'  => 'text',
														'label' => esc_html__('Google Plus URL', 'mytheme'),
														'value' => '',
													),
													'youtube_url' => array(
														'type'  => 'text',
														'label' => esc_html__('YouTube URL', 'mytheme'),
														'value' => '',
													),
													'move_right' => array(
														'label' => esc_html__( 'Move to the right', 'mytheme' ),
														'type' => 'switch',
														'left-choice' => array(
															'value' => 'no',
															'color' => '#ccc',
															'label' => esc_html__( 'No', 'mytheme' )
														),
														'right-choice' => array(
															'value' => 'yes',
															'label' => esc_html__( 'Yes', 'mytheme' )
														),
														'value' => 'no',
													),
												
												),
											)
										),
										
									)
								),
							
							)
						)
					),
					
				)
			)
			
		)
	),

);`

Settings.php code

`<?php

	if ( ! defined( 'FW' ) ) {
		die( 'Forbidden' );
	}

	$options = array(
		array(
		  'header' => array(
		    'title' => esc_html__('Header', 'mytheme'),
		    'type' => 'tab',
		    'options' => array(
		    
				  'top_bar' => array(
				    'title' => esc_html__('Top bar', 'mytheme'),
						'type' => 'box',
				    'attr' => array(
			        'class' => 'prevent-auto-close'
				    ),
				    'options' => array(
				    
							'top_bar_enabled' => array(
								'type' => 'multi-picker',
								'label' => false,
								'picker' => array(
									'enabled' => array(
										'label' => esc_html__( 'Enable Top Bar', 'mytheme' ),
										'type' => 'switch',
										'left-choice' => array(
											'value' => 'no',
											'color' => '#ccc',
											'label' => esc_html__( 'No', 'mytheme' )
										),
										'right-choice' => array(
											'value' => 'yes',
											'label' => esc_html__( 'Yes', 'mytheme' )
										),
										'value' => 'no',
									)
								),
								'choices' => array(
									'yes' => array(
									
										'top_bar_elements' => array(
											'type'          => 'addable-popup',
											'label'         => esc_html__( 'Top Bar Elements', 'mytheme' ),
											'popup-title'   => esc_html__( 'Add/Edit', 'mytheme' ),
											'desc'          => esc_html__( 'Add some top bar content', 'mytheme' ),
											'template'      => '{{if( type.elem_type == "text" ) return type.text.content; if( type.elem_type == "text_icon" ) return type.text_icon.content; if( type.elem_type == "social_icons" ) return type.social_icons.content; }}',
											'popup-options' => array(
											
												'type' => array(
													'type' => 'multi-picker',
													'label' => false,
													'desc' => false,
													'value' => array(
														'elem_type' => 'text',
													),
													'picker' => array(
														'elem_type' => array(
															'label' => esc_html__( 'Element type', 'mytheme' ),
															'type' => 'radio',
															'choices' => array(
																'text' => esc_html__( 'Text', 'mytheme' ),
																'text_icon' => esc_html__( 'Text and Icon', 'mytheme' ),
																'social_icons' => esc_html__( 'Social icons', 'mytheme' ),
															),
														)
													),
													'choices' => array(
														'text' => array(
														
															'content' => array(
																'type'  => 'text',
																'label' => esc_html__('Content', 'mytheme'),
																'value' => '',
															),
															'move_right' => array(
																'label' => esc_html__( 'Move to the right', 'mytheme' ),
																'type' => 'switch',
																'left-choice' => array(
																	'value' => 'no',
																	'color' => '#ccc',
																	'label' => esc_html__( 'No', 'mytheme' )
																),
																'right-choice' => array(
																	'value' => 'yes',
																	'label' => esc_html__( 'Yes', 'mytheme' )
																),
																'value' => 'no',
															),
														
														),
														'text_icon' => array(
														
															'content' => array(
																'type'  => 'text',
																'label' => esc_html__('Content', 'mytheme'),
																'value' => '',
															),				
															'icon' => array(
														    'type'  => 'icon-v2',
															),
															'move_right' => array(
																'label' => esc_html__( 'Move to the right', 'mytheme' ),
																'type' => 'switch',
																'left-choice' => array(
																	'value' => 'no',
																	'color' => '#ccc',
																	'label' => esc_html__( 'No', 'mytheme' )
																),
																'right-choice' => array(
																	'value' => 'yes',
																	'label' => esc_html__( 'Yes', 'mytheme' )
																),
																'value' => 'no',
															),
														
														),
														'social_icons' => array(
														
															'content' => array(
																'type'  => 'hidden',
																'value' => esc_html__('Social Icons', 'mytheme'),
															),		
															'facebook_url' => array(
																'type'  => 'text',
																'label' => esc_html__('Facebook URL', 'mytheme'),
																'value' => '',
															),
															'twitter_url' => array(
																'type'  => 'text',
																'label' => esc_html__('Twitter URL', 'mytheme'),
																'value' => '',
															),
															'linkedin_url' => array(
																'type'  => 'text',
																'label' => esc_html__('LinkedIn URL', 'mytheme'),
																'value' => '',
															),
															'google_plus_url' => array(
																'type'  => 'text',
																'label' => esc_html__('Google Plus URL', 'mytheme'),
																'value' => '',
															),
															'youtube_url' => array(
																'type'  => 'text',
																'label' => esc_html__('YouTube URL', 'mytheme'),
																'value' => '',
															),
															'move_right' => array(
																'label' => esc_html__( 'Move to the right', 'mytheme' ),
																'type' => 'switch',
																'left-choice' => array(
																	'value' => 'no',
																	'color' => '#ccc',
																	'label' => esc_html__( 'No', 'mytheme' )
																),
																'right-choice' => array(
																	'value' => 'yes',
																	'label' => esc_html__( 'Yes', 'mytheme' )
																),
																'value' => 'no',
															),
														
														),
													)
												),
												
											)
										),
									
									)
								)
							),
							
						)
					)
					
				)
			),
		)
	);
`

**Comment by WPJobs** [comment]
p.s. is it not possible to use the same config file for Customizer and Theme Options, if i should specify fw-storate only for customizer?

it would be better to have something like this in Settings.php

```
	$options = array(
		fw()->theme->get_options( 'general' ),
	  'customizer_settings' => array(
	    'title' => esc_html__('Customizer Options', 'mytheme'),
	    'type' => 'tab',
	    'options' => array(
				fw()->theme->get_options( 'customizer' ),
			)
		),
	);
```

and a question regarding nested settings, if i have MultiPicker, how KEY parameter should look?

```
'top_bar_enabled' => array(
	'type' => 'multi-picker',
	'label' => false,
	'fw-storage' => array(
	  'type' => 'wp-option',
	  'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
	  'key' => 'top_bar_enabled',
	),
	'picker' => array(
		'enabled' => array(
			'label' => esc_html__( 'Enable Top Bar', 'mytheme' ),
			'type' => 'switch',
			'left-choice' => array(
				'value' => 'no',
				'color' => '#ccc',
				'label' => esc_html__( 'No', 'mytheme' )
			),
			'right-choice' => array(
				'value' => 'yes',
				'label' => esc_html__( 'Yes', 'mytheme' )
			),
			'value' => 'no',
		)
	),
	'choices' => array(
		'yes' => array(
		
			'content' => array(
				'type'  => 'text',
				'label' => esc_html__('Content', 'mytheme'),
				'value' => '',
				
				/**
				 * Which key should be specified for child settings?
				 * "top_bar_enabled/content" or just "content"?
				 **/
				
				'fw-storage' => array(
				  'type' => 'wp-option',
				  'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
				  'key' => 'top_bar_enabled/content',
				),
			),			
		
		)
	)
),
```

**Comment by moldcraft** [comment]
- In Theme Settings options you say: Unyson, save this option in theme settings wp_option under this key.
- In Customizer options you say: Unyson, save this option by default in customizer wp_option.

How you expect this to sync?

**Comment by moldcraft** [comment]
This shows the correct values

```php
add_action('admin_notices', function(){
	fw_print(
		fw_get_db_settings_option(),
		fw_get_db_customizer_option()
	);
});
```

but [this](https://github.com/ThemeFuse/Unyson/blob/1ba15e9b141fbe79c33f0dbcf099d6950383e3b5/framework/includes/customizer/class--fw-customizer-control-option-wrapper.php#L14) returns the db value without processing the `fw-storage` param.

[Fixed](https://github.com/ThemeFuse/Unyson/commit/12a28c1af90e2d9d062a76184321631f2fe61c0d#diff-0816b70fb07ea631adcacdc5a8a759dcR44), please test.

**Comment by WPJobs** [comment]
@moldcraft thank you so much, it works like a charm now!

**Comment by WPJobs** [comment]
p.s. please answer on my last question

is it not possible to use the same config file for Customizer and Theme Options, if i should specify fw-storate only for customizer?

it would be better to have something like this in Settings.php

```
	$options = array(
		fw()->theme->get_options( 'general' ),
	       'customizer_settings' => array(
	               'title' => esc_html__('Customizer Options', 'mytheme'),
	               'type' => 'tab',
	               'options' => array(
				fw()->theme->get_options( 'customizer' ),
			)
		),
	);
```

**Comment by moldcraft** [comment]
It should work fine in both options.

**Comment by WPJobs** [comment]
Thank you! xD
![forever-alone-happy](https://cloud.githubusercontent.com/assets/12991525/21382416/377c7630-c769-11e6-9c09-487cfa4ce317.jpg)

**Comment by moldcraft** [comment]
Where did you get my photo?

**Comment by moldcraft** [comment]
`fw()->theme->get_options()` [has a second parameter](https://github.com/ThemeFuse/Unyson/blob/752144468eff8628e9a7e1a75f61a425a8c864f8/framework/core/components/theme.php#L64) in which you can pass custom variables to be available in the options files that is going to be loaded. In `settings.php` you ca do

```php
fw()->theme->get_options( 'customizer', array( 'no_fw_storage' => true ) )
```

then in `customizer.php` do

```php
'my_option' => array(
	'type' => 'text',
	'fw-storage' => isset($no_fw_storage) ? null : array(
		'type' => 'wp-option',
		'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
		'key' => 'top_bar_enabled',
	),
),
```

**Comment by WPJobs** [comment]
Worked perfectly, thank you so much again and again

**Comment by WPJobs** [comment]
@moldcraft Sorry, but after closer testing of this feature i noticed following problem:

now fw_get_db_customizer_option('top_bar_enabled') always returns saved value, and live preview in customizer now working until i click on "save" button :(

**Comment by moldcraft** [comment]
I felt there may be problems with preview. In [the method I have overwrote](https://github.com/ThemeFuse/Unyson/commit/12a28c1af90e2d9d062a76184321631f2fe61c0d#diff-0816b70fb07ea631adcacdc5a8a759dcR52) there was [`if ($this->is_previewed)`](https://github.com/WordPress/WordPress/blob/4.7/wp-includes/class-wp-customize-setting.php#L731) but I ignored it hoping it will work fine. I will inspect this.

**Comment by moldcraft** [comment]
Please test

**Comment by WPJobs** [comment]
It works now, thank you!

**Comment by WPJobs** [comment]
@moldcraft sorry that's me again

It seems now it works only for one page in Customizer, e.g. if i change header style, it changes, but when i click on any link in preview area, changes doesn't appear like i didn't change this option

**Comment by WPJobs** [comment]
also, if you have several panels in customizer:

- change some setting on first panel
- navigate to second panel and change any option, you will lost your settings in preview area from first panel

**Comment by moldcraft** [comment]
@WPJobs Please send me again a test theme with test options. I have tried on my side with some options and can't reproduce the problem.

**Comment by WPJobs** [comment]
@moldcraft sorry I'm on vacation now, I'll send you the test theme few days later

**Comment by WPJobs** [comment]
@moldcraft Hi, hope you're well!

Please check this test theme https://drive.google.com/open?id=0Bz6XVdLE4r1fbGtuRERtN0d1Mm8

it has only two options (Header and Footer) in two panels, try to change Some Header Option in customizer and then try to change Some Footer Option

the problem can be here:

```
'fw-storage' => isset($no_fw_storage) ? null : array(
  'type' => 'wp-option',
  'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
  'key' => 'some_header_option',
),
```

once i remove ternary operator and split settings into two files (settings.php and customizer.php) , it works

```
'fw-storage' => array(
  'type' => 'wp-option',
  'wp-option' => 'fw_theme_settings_options:'. fw()->theme->manifest->get_id(),
  'key' => 'some_header_option',
),
```

but, if i store all settings in customizer.php and load these settings in settings.php

```
	$options = array(
	  'customizer_settings' => array(
	    'title' => esc_html__('Customizer Options', 'mytheme'),
	    'type' => 'tab',
	    'options' => array(
				fw()->theme->get_options( 'customizer', array( 'no_fw_storage' => true ) ),
			)
		),
	);
```

it doesn't work

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/b32428c430674b80e0a27866d0b78c987cf8591d

Please test

**Comment by WPJobs** [comment]
it works fine now! thank you so much again, wish you all the best in 2017 and happy new year :)
