### ISSUE TITLE
qtranslate issue

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#2266]
Whenever I put [:ka] [:en] [:ru] tags inside shortcode input fields the whole shortcode stops working on other languages, the whole section disappears and only appears on last language.

If I put sequence: [:ka] [:en] [:ru] - section appears only on russian. If I change sequence to [:ka] [:ru] [:en] - it only appears on english.

I used previously unyson with this plugin and it was working fine.

**Comment by andreiglingeanu** [comment]
Can't say anything about qTranslate but I'm sure that Polylang works just fine in combination with Unyson

**Comment by sandrodz** [comment]
Unfortunately I've implemented whole project with unyson + qtranslate-x and since it worked before I didn't test it. I cannot move to polylang at this moment.

Problem occurs only with shortcodes.

**Comment by andreiglingeanu** [comment]
This happened after an update or what?

**Comment by sandrodz** [comment]
No it worked few month back when i used this combo in another project. In a new one currently I'm working on it fails this way. 

The whole shortcode disappears and displays only on 1 language. Which is strange.

**Comment by sandrodz** [comment]
if @moldcraft could take a look I'm sure he could say how I could fix this.

Problem occurs with short-codes in builder. Everything works fine with meta boxes and options made using unyson.

I also noticed that all shortcodes fail n

**Comment by moldcraft** [comment]
I added one Text Block shortcode with this content `[:en]English Text[:de]Deutsch[:]` and there are no errors in frontend, it displays `English Text`

**Comment by moldcraft** [comment]
I added one Text Block shortcode with this content `[:en]English Text[:de]Deutsch[:]` and there are no errors in frontend, it displays `English Text`. On `{site}/?page_id=123&lang=de` it shows `Deutsch`
