### ISSUE TITLE
Unyson events extension options not showing after WordPress 4.7 update and unyson update

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#2267]
Hi ,

I updated the WP and unyson today, but after all the options are not showing in the events post page (admin side).

The options are generated in the source code, but hidden somehow.

Please help.

![00236](https://cloud.githubusercontent.com/assets/11642633/21347236/b6fa2e3a-c6cd-11e6-9c5a-bdaf0e88bde1.png)

**Comment by andreiglingeanu** [comment]
Seems this is same as https://github.com/ThemeFuse/Unyson/issues/2256#issuecomment-267317595

**Comment by linjo** [comment]
My issue is with events extension, not the page  builder. Page builder is working fine.

Check this screenshot, the event box options are generating in the source, but not showing up . Also the code is converted to special characters, is that what causing the issue?

Please assist.
![uny](https://cloud.githubusercontent.com/assets/11642633/21379618/6cc9744e-c775-11e6-8936-681d05f1d091.jpg)

**Comment by moldcraft** [comment]
@linjo Note that gray border, that should be your metabox with event options, but it is closed and the toggle bar is not visible (because the box doesn't have a title).

Please execute this code in your browser console:

```js
jQuery('#fw-options-box-main > .hndle').trigger('click');
```
