### ISSUE TITLE
restore revision doesn't work with page builder shortcodes

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#2268]
I'd expect restore revision would work with page builder shortcoes, but it doesn't. Error is displayed: `The shortcode text_block not found.`

**Comment by moldcraft** [comment]
I just tried and it works for me. Please give the exact steps to reproduce the problem.

**Comment by sandrodz** [comment]
Try this: go back to revision, notice that your sent back with page builder disabled - if you click on page builder button to turn it on, the error will be shown. IF after revision checkout you refresh the page instead of clicking page builder it works fine.

**Comment by moldcraft** [comment]
Everything works on my side https://sendvid.com/hkx9sqvn
