### ISSUE TITLE
Options popup close lost fade out 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2269]
Latest master fade out is missing on options popup close
http://take.ms/F1J8x

backdrop is fading out first than popup closes abruptly

**Comment by moldcraft** [comment]
Reproduced with `fw.soleModal.show('test', 'Hello World');` (then click on Close button).

In 2.6.9 works fine.

**Comment by moldcraft** [comment]
The changes made to `fw.js` from v2.6.10 until 12a28c1af90e2d9d062a76184321631f2fe61c0d _(the most recent commit)_

http://pastebin.com/UF6UiYci

**Comment by andreiglingeanu** [comment]
I'm on this. Small typo.

**Comment by andreiglingeanu** [comment]
@danyj Please give it a spin.

**Comment by moldcraft** [comment]
It's ok now. Thanks

**Comment by andreiglingeanu** [comment]
In general, I gave up on having the `fwGrowIn` animation to be applied at every point of a modal lifetime:

- we apply `fwGrowIn` just on `fw-modal-opening`
- `fwGrowOut` just on `fw-modal-closing`
- other custom modal animations for additional user feedback manually

The only downside of that is that we have to not forget to manually remove `fw-modal-opening` and `fw-modal-closing` after `300ms`.

**Comment by danyj** [comment]
not quite ,  now on open the fadein backdrop takes longer and popup is abrupt
http://take.ms/OlSiX

**Comment by danyj** [comment]
and there is also a significant delay before the popup opens , nothing moves for those 0.3s
it was instant before

**Comment by andreiglingeanu** [comment]
> popup is abrupt

That was looong before that. Even the standard WP Media modal has this bug.

I'll handle the animation delay, though. Thanks for reporting that.

**Comment by danyj** [comment]
maybe I am not explaining it right but please test on previous versions , 
when you click on shortcode you see immediate action , now there is delay

**Comment by andreiglingeanu** [comment]
Hey @danyj! Able to take this new fix for a quick test?

**Comment by danyj** [comment]
in few min

**Comment by danyj** [comment]
works now. thnx!
