### ISSUE TITLE
Unyson Icon Font

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#227]
We have the font icon ready to be integrated in Unyson. I am thinking we'll include it in the options like this: http://joxi.ru/Dr89WzaHojq3m6 (sorry for FA, but we'll need to place our 1600+ icons option first :P)

Consider this:
- developers will get full access to use them in their themes (they will be separated on 26 categories)
- we'll use this icons to replace the shortcodes images and make them icon font: http://joxi.ru/nAy6LlpUgVnlrZ
- we've included our brand icons: http://joxi.ru/LmGpqOgcwKkE2l that we'll be able to use in places like menus, footers, where we need it. 

I want us to move away from images in regarding to icons, especially when we are talking about admin icons. Hit me up on Skype for all the files and further discussion.

**Comment by danyj** [comment]
@DimiBaitanciuc  Are you saying that FA will be out?

**Comment by DimiBaitanciuc** [comment]
No of course not, I've said "we'll need to place" our option first, place it as in position it first in the option list. I meant it as a joke ... :)

**Comment by danyj** [comment]
ah ok , I saw  > sorry for FA  so kinda looked like is going out

**Comment by moldcraft** [comment]
* Demo is on

    ```
    http://{your-host}/wp-content/plugins/unyson/framework/static/libs/unycon/demo/
    ```

* To use it

    ```
    wp_enqueue_style('fw-unycon');
    ```

    or add it to your style dependencies

    ```
    wp_enqueue_style(
        'your-handle',
        '.../your-style.css',
        array('fw-unycon'),
        fw()->manifest->get_version()
    );
    ```

**Comment by moldcraft** [comment]
[This](http://joxi.ru/Dr89WzaHojq3m6) has not been done.

**Comment by danyj** [comment]
I was about to ask where the unyson font is in icons

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/227#issuecomment-125912509

It will be in option type `icon-v2`
