### ISSUE TITLE
Failed to access Github repository

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2270]
Don't know what's wrong happened. 

I can't Update extensions from GitHub repo in my localhost. 

I have tested with 
```
add_action('admin_notices', function(){
    fw_print(wp_remote_get('http://github-api-cache.unyson.io/repos/ThemeFuse/Unyson-Shortcodes-Extension/releases/latest'));
});
```

But still same issue. 

![hello](https://puu.sh/sWjSw/c114027a57.png)

**Comment by moldcraft** [comment]
I restarted the server on github-api-cache.unyson.io and it seems to work fine.

_There was an error: Name lookup timed out_
