### ISSUE TITLE
Wrong overflow for color picker inside customizer.

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2275]
If the color picker is the last option in the customizer panel, you can clearly see the issue when the color picker pops up. Panel displays scrollbar bar, and cuts of the color picker, then you need to scroll to see the 
full color picker.

![selection_001](https://cloud.githubusercontent.com/assets/390700/21428681/97b184e4-c85b-11e6-9389-cccf47ca630c.png)

**Comment by moldcraft** [comment]
This is actually the fix to the previous problem, when the color picker was half visible and there was no scroll bar.

Now I will fix this by adding additional padding-bottom to color picker if it's last option in customizer panel.

**Comment by moldcraft** [comment]
https://vid.me/098A
