### ISSUE TITLE
Multi-select prepopulation bug

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2279]
Hi, i have noticed another bug in Multi-select option. This code doesn't work

```
'test_item' => array(
  'type'  => 'multi-select',
  'label' => esc_html__('Choose the page', 'mytheme'),
  'population' => 'posts',
  'source' => 'page',
  'prepopulate' => 10,
  'limit' => 1,
),
```

i can't select the page, it doesn't prepopulate pages

![2016-12-22_23-50-45](https://cloud.githubusercontent.com/assets/12991525/21441592/820eb74c-c8a1-11e6-8c4a-67617c6bbbca.png)

**Comment by moldcraft** [comment]
Please test
