### ISSUE TITLE
How to: Add more options to "Add Slide" screen

### ISSUE THREAD

**Issue by icypixels** [ThemeFuse/Unyson#228]
Hey, I also have a question, which it seems I can’t find the solution to so therefore I’m going to ask you guys :)

If I would want to add more Options to the “Add Slides” screen, aside from the Image, Title and Description, how would I go around this (Screenshot with screen I’m referring to: https://www.dropbox.com/s/nekxjafp2vpdolh/Screenshot%202015-02-06%2012.31.01.png?dl=0)

Would I have to extend the “custom.php” of the population methods extensions?

Paul

**Comment by moldcraft** [comment]
Have you tried [this solution](http://manual.unyson.io/en/latest/extension/slider/index.html#options) *(To create `framework-customizations/extensions/slider/extensions/{slider-type}/options.php`)* ?

**Comment by llemurya** [comment]
You must follow the instruction from this [picture](http://static.md/905ce01947ccfd2e38e6a94382bfef26#) and you will see the next [result](http://static.md/e0d479d1adfe926473aac8a49b75c5df#) . Hope this will resolve your problem.

**Comment by icypixels** [comment]
Well, I think we're not using the same environment. So here's a little context: 
Local Dev, WP 4.1, Unyson as a plugin.

I get the following error when creating the "slider" folder, let alone anything more than that:

<code>Fatal error: Extension "slider" is already defined in "E:\Dropbox\Development\xampp-portable\htdocs\wp-content\plugins\unyson\framework/extensions/media/extensions/slider" found again in "E:\Dropbox\Development\xampp-portable\htdocs/wp-content/themes/minim/framework-customizations/extensions/slider" in E:\Dropbox\Development\xampp-portable\htdocs\wp-content\plugins\unyson\framework\core\components\extensions.php on line 133</code>

Looks like we can't override the slider extension from my end. By the way, followed the exact same structure as you pointed out in the screenshot.
Here's screen from Sublime text: 
https://www.dropbox.com/s/zngutscm6vszbcw/Screenshot%202015-02-06%2014.08.15.png?dl=0

Apropo, multumesc de raspunsuri :)

**Comment by moldcraft** [comment]
Cu plăcere ;)

**Comment by icypixels** [comment]
Totusi, ramane problema cu redeclararea folder-ului slider in interiorul temei :)

**Comment by moldcraft** [comment]
Nu puteți rescrie întreaga extensie în `framework-customizations/`, doar unele fișiere. Deci nu copiați din plugin tot folderul, dar creați un folder gol `framework-customizations/extensions/media/extensions/slider/extensions/{slider-type}` și deja în el puteți crea de exemplu `options/options.php` pentru a adăuga niște opțiuni suplimentare pentru slider (sau alte fișiere descrise în documentație).

**Comment by icypixels** [comment]
Mersi mult, acum am priceput :) Va salut si spor sa aveti!
