### ISSUE TITLE
Contact Form Icon Disappear In The Shortcode Pop-Up Box

### ISSUE THREAD

**Issue by indopixel** [ThemeFuse/Unyson#2280]
Hi,

The contact form shortcode icon doesn't show in the shortcode pop-up box (attachment included) but it show up when I'm using page builder (in Content Elements). I'm using Twenty Sixteen themes and disabled all plugins.

Thank you

Best Regards,
Bismoko Widyatno
![contact-form-no-logo](https://cloud.githubusercontent.com/assets/18467378/21450774/5dee65e8-c92c-11e6-9101-d8c37d4c9e03.jpg)

**Comment by andreiglingeanu** [comment]
@indopixel Thanks for your report!

This issue really belongs to the [WordPress Shortcodes](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension) repository, but I've [fixed](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/commit/6c216d3ba58c3b48692f0e351bff049ddcb61226) though.
