### ISSUE TITLE
Looking for your suggestion to improve/correct my shortcode: adding a helper class

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#2281]
I made a `class-fw-shortcode-shortcodeName.php` to do some value processing needed for the front-end

```php
<?php if (!defined('FW')) die('Forbidden');

class FW_Shortcode_Shortcodename extends FW_Shortcode
{
  public function _init() {} // nope, not here

  // example utility functions
  public function format_number($n, $precision = 2) {
    // return some computed value here
  }
}
```
then I do this in the `view.php` to access these methods
```php
$shortcode = fw_ext( 'shortcodes' )->get_shortcode( 'shortcodeName' );

$someValueNeeded = $shortcode->format_number($anotherVariable);
```

**QUESTION**
Is the `$shortcode->format_number($anotherVariable);` the only way to access the shortcode's internal public methods or is there a better way?

**Comment by moldcraft** [comment]
You can make the `format_number()` method static and call it like this 

```php
FW_Shortcode_Shortcodename::format_number(...)
```

the class will be [autoloaded](http://php.net/manual/en/function.spl-autoload-register.php)

**Comment by thednp** [comment]
Thank you @moldcraft. Isn't it autoloaded the way I use it?

**Comment by moldcraft** [comment]
The way you use it, yes.

You asked some other ways and I provided one. If you will use the method only in shortcode view then there is no need for autoload because in view the shortcode is already loaded.
