### ISSUE TITLE
Megamenu custom options

### ISSUE THREAD

**Issue by biklik** [ThemeFuse/Unyson#2282]
Hi!

Is any solution to improve columns size or any custom option for the megamenus, like a popup with options for example? I try with #240 solutions but it does not work for me.

thanks!

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/issues/14#issuecomment-247705743

**Comment by biklik** [comment]
Thanks! It works perfectly!
