### ISSUE TITLE
is there is a problem with default value of the field when i use fw-storage

### ISSUE THREAD

**Issue by eyeswizard** [ThemeFuse/Unyson#2283]
hello,
i'm facing a problem with the following code

```php
'meta_activation_key'           => array(
				'type'       => 'text',
				'value'      => smart_random_string( 10 ),
				'label'      => __( 'Activation Key', '{domain}' ),
				'fw-storage' => array(
					'type'      => 'post-meta',
					'post-meta' => 'meta_activation_key',
				)
			)

```

```php
function smart_random_string( $length = 10 ) {
	$characters       = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
	$charactersLength = strlen( $characters );
	$randomString     = '';
	for ( $i = 0; $i < $length; $i ++ ) {
		$randomString .= $characters[ rand( 0, $charactersLength - 1 ) ];
	}

	return $randomString;
}
```

i'm trying to create a metabox with a default value (string) but it doesn't work when i add fw-storage to the code
using (localhost) unyson 2.6.10 and wordpress 4.7
Thank you,
Best regards

**Comment by moldcraft** [comment]
You learned how to highlight the php code with

```
    ```php
    $your = "code";
    ```
```

![rsz_265020b8-9b3b-4982-937c-c79caca84622](https://cloud.githubusercontent.com/assets/1475489/21540787/8550b8f6-cdba-11e6-857a-915ae9e80ec4.png)

**Comment by moldcraft** [comment]
> but it doesn't work

more details please (maybe a video or the exact steps to reproduce).

I added the above code in `{theme}/framework-customizations/theme/options/settings.php` and it works fine.

**Comment by eyeswizard** [comment]
@moldcraft check this video https://youtu.be/wyys3MWL6gY

**Comment by moldcraft** [comment]
@eyeswizard Oh, there is `'post-meta'` fw-storage but I tested it in Theme Settings. Now I added that option in post options and the value is empty. Checking...

**Comment by eyeswizard** [comment]
```php
echo 'Thank you moldcraft  :D';
```
