### ISSUE TITLE
Request to add extra background option field.

### ISSUE THREAD

**Issue by therakib7** [ThemeFuse/Unyson#2285]
Hello,
I need a background option field like the following parameter.

background-color: '';
background-image: '';
background-repeat: '';
background-position: '';
background-size: '';
background-attachment: ''; 
background-repeat: '';
background-attachment: '';

I request you to add an extra background option field like that.
Advance Thanks

**Comment by moldcraft** [comment]
Hello,

We will not add it soon. (first we need to decide if we will add it or not).

Until then, you can [create your own option-type](http://manual.unyson.io/en/latest/options/create-option-type.html#content).

**Comment by albertso** [comment]
@therakib7 You can build complex options of simpler options, you don't always need to create a new option type. It's better sometimes to combine and extend existing option types with custom classes and javascript.

To reuse options, use [`fw()->theme->get_options( $option, $variables );`](http://manual.unyson.io/en/latest/components/theme.html).

This function reads $options array in files located in ´framework-customizations/theme/options´, so you can easily organize different settings amd option structures, in separate files and folders.

For example, you could create `options/background.php`, and build your complex background option there, and use it any where you like with `fw()->theme->get_options('background');`

The best thing, you can pass an array of $variables to the option file, and they will be extracted and available in the option file.

It's super versatile

Similar `get_..._options()` functions exist for extension options, shortcode options, etc.

Of course a custom option-type would be ideal, but this other method will take you very far.
