### ISSUE TITLE
Multisite Contact Form Error

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson#2286]
Hello , 

when on a multisite and using a contact form , when viewing the page as a superadmin I get this error :

`Fatal error: Cannot redeclare class FW_Option_Type_Form_Builder_Item in /wp-content/plugins/unyson/framework/extensions/forms/includes/option-types/form-builder/extends/class-fw-option-type-form-builder-item.php on line 82`

All is well when viewing the page not loged-in or on a simple WP (not multisite).

**Comment by toleabivol** [comment]
The error also appears when updating the post in the dashboard breaking it

**Comment by agaco** [comment]
and mine is also about form builder but:

Fatal error: Call to undefined method Kinder_Option_Type_Form_Builder_Item_Text_With_Icon::get_item_localization() in /wp-content/plugins/unyson/framework/extensions/forms/includes/option-types/form-builder/class-fw-option-type-form-builder.php on line 52

**Comment by toleabivol** [comment]
The issue __persists__ if I change my user's role for current site (e.g. as subscriber).
But I found that the error __disappears__ if I remove my superAdmin user from the current site.

**Comment by indopixel** [comment]
Same problem with mine but in my case the issue still persist even I have removing the super admin from the current site .

**Comment by indopixel** [comment]
Same problem with mine, it only happen on multisite. I tried on my single site and it didn't happen.

**Comment by moldcraft** [comment]
Please test https://github.com/ThemeFuse/Unyson/archive/master.zip

**Comment by toleabivol** [comment]
Hi , 
the error is fixed but I had to remove `.maintenance` file (had correct permissions - FTP user, and updating other plugins or WP core do not have this issue) and then reinstall extensions :
![unyson skyplex wordpress](https://cloud.githubusercontent.com/assets/3755796/21749842/4ab79414-d5b0-11e6-9999-97f43cffd59b.jpeg)

**Comment by toleabivol** [comment]
Hi , 

the `.maintenance` not being removed was a bug from `vsftp 3.0.2` and `Debian` - solution was to install the latest unstable version.
