### ISSUE TITLE
Extensions Titles

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#229]
Something changed here, the extension titles are too big: http://joxi.ru/p27E6pZiK9VNr7 
The titles need to be 18px.

**Comment by danyj** [comment]
you sure you did not ++ the browser? 
http://screencast.com/t/PaFcLoeT0Am
looks fine to me

**Comment by moldcraft** [comment]
@DimiBaitanciuc is this still happens in Unyson 2.2.x ?

**Comment by DimiBaitanciuc** [comment]
Solved.
