### ISSUE TITLE
page editing broken

### ISSUE THREAD

**Issue by essentialshift** [ThemeFuse/Unyson#2290]
I love this plugin, but after this last update I can not edit any pages. It just loads a white screen. Any help?

**Comment by moldcraft** [comment]
If you have the same theme as this user, the it’s the same problem https://wordpress.org/support/topic/fatal-error-2392/

Is WP_DEBUG enabled in wp-config.php ? We need an error message, "I can not edit any pages" it's not very helpful.

If you can't find any error message, can you send me your admin and ftp credentials to `moldcraft[at]email.com`? and I will inspect the problem

**Comment by essentialshift** [comment]
Yes, I am using the same theme, Berg

**Comment by essentialshift** [comment]
I see you told him you will be releasing an update again, I will wait for that.
