### ISSUE TITLE
Unyson contact Forum map dispaly

### ISSUE THREAD

**Issue by aceofspace** [ThemeFuse/Unyson#2293]
Hi I am new to Github and not a programmer. 
I have installed Unyson on the Journal theme. Wordpress 4.7.

I created a page then form the  "Content Elements" selected  "Add a map".
I have inserted the address but I get a Gray shape with an exclamation mark and the following message:
**Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.**

The Java console on Chrome shows: "Failed to load resource: the server responded with a status of 404 (Not Found)"

How do I go about resolving this. Is this a Unyson issue or wordpress? 
Is there a tutorial that shows how to set up a map? 

Thanks for any help and directions

**Comment by moldcraft** [comment]
Hello,

You need to add in `{theme}/framework-customizations/theme/settings.php` or in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/map/options.php` an option

```php
'gmap-api-key' => array( 'type' => 'gmap-key' ),
```

[It is there by default](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/b6674bee2131c29a614068765f96b69aa249651a/shortcodes/map/options.php#L22-L42), but it looks like the theme has been overwritten the options file.

_Unfortunately we don't provide support for the Journal theme._

**Comment by aceofspace** [comment]
Thanks. 
I don't know php but i see the code in the  options.php
'gmap_key' => array(
		'label' => __( 'API Key', 'fw' ),
		'type'  => 'gmap-key',
		'desc' => sprintf( __( 'Create an application in %sGoogle Console%s and add the API Key here.', 'fw' ),

I guess I would need to create  and API key for this map to work?
I guess alternatively I can also insert an <iframe> to display the map. 
Thank you.

**Comment by moldcraft** [comment]
You need to create an API key.
