### ISSUE TITLE
Unyson changes my files in framework-customization folder

### ISSUE THREAD

**Issue by maryslen** [ThemeFuse/Unyson#2298]
Hi,

After Unyson update i've noticed that 'update' affects my own files in framework-customization. For ex. i've changed 'esc_html()' function to 'echo' because Theme Check doesn't allow to use 'esc_html()'. Why it happens and how i can block this?

**Comment by moldcraft** [comment]
Hello,

Please provide the exact steps to reproduce the problem.

**Comment by Eynsteyn** [comment]
Theme Review Team soft rejected my theme with reason

Data Validation issues have been found in your theme. All dynamic data must be correctly escaped for the context where it is rendered. - All dynamic data must be escaped with esc_attr() before rendered in an html attribute. - Whenever you are rendering a url to the screen its value must be passed through esc_url() first. - If dynamic data is rendered inside an attribute that triggers a JavaScript event, it must be escaped with esc_js(). Please make sure you read these articles: https://make.wordpress.org/themes/tags/writing-secure-themes/ http://codex.wordpress.org/Data_Validation http://developer.wordpress.com/themes/escaping/ http://code.tutsplus.com/articles/data-sanitization-and-validation-with-wordpress--wp-25536 https://vip.wordpress.com/documentation/best-practices/security/validating-sanitizing-escaping/ 

I changed all the data in a "framework-customizations" folder in accordance with the requirements of Wordpress, like this 

```
<label for="<?php echo $choice['id'] ?>"><?php echo $choice['value'] ?></label>
<label for="<?php echo esc_attr($choice['id']) ?>"><?php echo esc_html($choice['value']) ?></label>
```

Today I downloaded the update extensions, and I replaced(reverted) all my changes

**Comment by moldcraft** [comment]
> I downloaded the update extensions

How you downloaded it? It is hidden (it is not visible in Unyson Extensions page)

**Comment by Eynsteyn** [comment]
![d92b9373c6a94ce0a6e3d76742d592f1](https://cloud.githubusercontent.com/assets/7722113/21673101/80487d88-d32f-11e6-9835-8049362d2492.png)

**Comment by moldcraft** [comment]
Can you send me your admin and ftp credentials or your theme to `moldcraft[at]email.com`?

**Comment by Eynsteyn** [comment]
I sent you a mail with theme archive

**Comment by moldcraft** [comment]
Thanks. I will take a look today.

**Comment by moldcraft** [comment]
When I activated the theme I got:

```
Fatal error: Cannot redeclare _action_fw_ext_forms_option_types_init() (previously declared in /.../wp-content/plugins/unyson/framework/extensions/forms/hooks.php:17) in /.../wp-content/themes/point_theme/framework-customizations/extensions/forms/hooks.php on line 17
```

I see that you copied a lot of extensions from unyson to your theme (all files). Why did you did that?

**Comment by maryslen** [comment]
We did it for stylizing those extension in our theme design.

**Comment by moldcraft** [comment]
You should add only the file you want to overwrite, do not copy the entire extension (with class and manifest files). Also the function names must be [unique](http://manual.unyson.io/en/latest/convention/prefixes.html#theme). The error above shows that you used the same function name as in original extension.
