### ISSUE TITLE
Contact form / paragraph text default width problem

### ISSUE THREAD

**Issue by micronpn** [ThemeFuse/Unyson#2299]
I am using the free version of Unyson, I have a problem with the message field of the contact form. It is the only paragraph text widget in the page, it is a 1/2 column width widget but its width is about 1/2 of the space it could occupy so it is not aligned with the single text line over it (the message field seems to be squared) also if it is possible to manually enlarge it.

Is there anyway to fix its width to be the same as the single text line?

This is the link to the test website:
https://micronengineering.000webhostapp.com/en/contacts/

I would like also to have fields of text with a different heigth (the margine between the font and the border is too much in my opinion) is there any way to change it?

**Comment by moldcraft** [comment]
Until we will release a new version of the Forms extensions, you can add in your theme this css:

```css
.wrap-forms textarea {
    width: 100%;
}
```

**Comment by moldcraft** [comment]
> I would like also to have fields of text with a different heigth (the margine between the font and the border is too much in my opinion) is there any way to change it?

You should be able to change that from css too.

**Comment by moldcraft** [comment]
> "additional css", is it the right place?

Yes.

Sorry, this is not related to some Unyson problem. What you ask is custom work, you should learn how to code or [find a developer](https://themefuse.com/custom-work/)
