### ISSUE TITLE
Disable Google Maps scrolling on mobile layout

### ISSUE THREAD

**Issue by elissonkario** [ThemeFuse/Unyson#2300]
Hello. Thank you for sharing this great framework. Is there a way to block the touch on the map when viewed by the cell phone? The map occupies the entire screen and when the site is navigated in the mobile phone, when you arrive on the map, scrolls the map instead of the screen.

**Comment by moldcraft** [comment]
Try to add [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/b6674bee2131c29a614068765f96b69aa249651a/shortcodes/map/static/js/scripts.js#L19)

```js
draggable: !("ontouchend" in document)
```

_[source](http://stackoverflow.com/a/34181432)_

If it works I will include the change and soon we will release a new version of the Shortcodes extension.

**Comment by GheorgheP** [comment]
https://stackoverflow.com/questions/27268744/disable-dragabble-on-google-maps-in-mobile#answer-27269673
