### ISSUE TITLE
can't unselect drag and drop elements

### ISSUE THREAD

**Issue by clemfren** [ThemeFuse/Unyson#2301]
Hi,

I'm using Version 4.7 | Unyson 2.6.11 | Woffice 2.1.2

When I try to create a new page using the page builder, I  can't unselect a drag and drop element after I select it.

Could you please tell me how I can fix that problem.

Thanks for your help

Clement

**Comment by moldcraft** [comment]
Hello,

Please provide a screenshot or a video, I don't understand what you mean by "I can't unselect a drag and drop element after I select it"

**Comment by clemfren** [comment]
![unyson issue](https://cloud.githubusercontent.com/assets/24933999/21675998/4bd4cb06-d334-11e6-81e3-6126d2878769.jpg)

**Comment by clemfren** [comment]
For instance, in that situation, once I dropped the "1/5", it's still selected and I can't do anything but drop it again and again if that makes sense

**Comment by moldcraft** [comment]
I think you have a js error. Please open browser developer tools console (F12) and show us the screenshot. If there are error, they will be with red text.

Also try to activate a default WP theme and check if the problem in builder persists.

**Comment by clemfren** [comment]
I have tried to use Chrome instead of Firefox and it works. Problem solved! Thank you for your help.

**Comment by moldcraft** [comment]
On my side the builder works fine in chrome. Maybe the problem comes from some plugin js
