### ISSUE TITLE
Display multi-select category values

### ISSUE THREAD

**Issue by ibrahimkholil** [ThemeFuse/Unyson#2302]
i cant display selected category post :
this is `option.php`

```php
'cat' => array(
    'type'  => 'multi-select',
    'label' => __('Select Categorys', 'b'),
    'desc'    => __('Select categories to be shown, choose none to show all', 'b'),
    'population' => 'taxonomy',
    'source' => 'category',
    'prepopulate' => 9999,
    'limit' => 9999,
),
```

my post loop: 

```php
$cats = $atts['cat'];
$query_args = array(
					'post_type'      => 'post',
					'paged'          => $paged,
					'posts_per_page' => $num_post,
					'category_name'  => $cats, 	
				);
```

also i used `fw_get_db_post_option($post->ID, 'cat');` that function, Please help me how to displaying select category posts??

**Comment by NiloySarker** [comment]
Try This `<?php foreach ($atts['cat'] as  $cat) : 
 echo $cat;
endforeach; /?> `

**Comment by moldcraft** [comment]
Do `fw_print($atts['cat']);` to see the array structure, then transform it how you need (to be suitable for query args structure)

**Comment by ibrahimkholil** [comment]
i saw array structure , but how to show post using selected category give me example

**Comment by moldcraft** [comment]
> https://codex.wordpress.org/Class_Reference/WP_Query
>
> Display posts that have these categories, using category id:
> 
>     $query = new WP_Query( array( 'cat' => '2,6,17,38' ) );
>
> Display posts that have these categories, using category slug:
>
>     $query = new WP_Query( array( 'category_name' => 'staff,news' ) );
> 
> Display posts that have "all" of these categories:
>
>     $query = new WP_Query( array( 'category_name' => 'staff+news' ) );

**Comment by ibrahimkholil** [comment]
i understood. but i want when user select multiple category from backed, then how value come in front end?? 
$cats = $atts['cat'];
 	$query_args = array(
					'post_type'      => 'post',
					'paged'          => $paged,
					'posts_per_page' => $num_post,
					'category_name'  =>$ct, 	
				);
			
		$wp_query = new WP_Query($query_args);
its not working dynamically,  i select category from backed how to show its fronted ??
