### ISSUE TITLE
[suggestion] Oembed option type limit types

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2303]
Is there any way that we could limit the types to a specific embed type like video or audio only ?

These are all types , https://codex.wordpress.org/Embeds

but I cant seem to find a way to limit the oembed to videos. 
This option type is great when used in media types shortcodes but if for example you use it in video shortcode it will also let you use Twitter links or any other embed types.

**Comment by GheorgheP** [comment]
The Oembed option type is not specifically made for the media only, theoretically you can put there any kind of content, for example a link to a site and you'll get an iframe to that site, sure it doesn't looks properly now, but this better would be fixed then restricted.

In your case you if you want to use only for media, you can extend the `FW_Option_Type_Oembed` option type class and create your own version where you'll restrict the input values to some valid only resources.
