### ISSUE TITLE
Cannot redeclare class FW_Option_Type_Form_Builder_Item

### ISSUE THREAD

**Issue by mintaras** [ThemeFuse/Unyson#2305]
After adding Contact form shortcode to page I am having 

> Cannot redeclare class FW_Option_Type_Form_Builder_Item

`http://portal.6w2s.com.au/register/`

This is only for pages with Contact form shortcode, after trying to save page.

I am on multisite network.

**Comment by moldcraft** [comment]
Hello,

This problem was fixed. Please update Unyson plugin to version 2.6.12

**Comment by mintaras** [comment]
Thanks. Now, after update I am having 
> Fatal error: Call to a member function get_uri() on a non-object in /wp-content/themes/empowered/theme-includes/helpers.php on line 3552

Code looks like this

$shortcodes_extension = fw_ext( 'shortcodes' );
$shortcodes_extension->get_uri( '/shortcodes/section/static/js/core.js' )
