### ISSUE TITLE
Manual Install of Extensions

### ISSUE THREAD

**Issue by CoverJ** [ThemeFuse/Unyson#2307]
Hey guys,

I'm having some trouble installing specifically the demo/backup extension through the wordpress backend. I get:

Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 7: )

So I thought maybe it would be easier to just manually install it?

Thanks.

**Comment by Ataurr** [comment]
Hello,

Add in `{theme}/functions.php`

```
add_action('admin_notices', function(){
    fw_print(wp_remote_get('http://github-api-cache.unyson.io/repos/ThemeFuse/Unyson-Shortcodes-Extension/releases/latest'));
});
```

**Comment by davidami** [comment]
Hello,

i add in a functions.php, appear a console code:

array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary
    (
        [*:data] => array
        (
            [date] => 'Tue, 17 Jan 2017 11:16:50 GMT'
            [server] => 'Apache'
            [content-type] => 'text/plain'
        )
    )
    [body] => 'Host di destinazione non consentito, sblocca la connessione nel pannello di AlterVista (Risorse > Impostazioni PHP)'
    [response] => array
    (
        [code] => 403
        [message] => 'Forbidden'
    )
    [cookies] => array()
    [filename] => null
    [http_response] => WP_HTTP_Requests_Response
    (
        [*:response] => Requests_Response
        (
            [body] => 'Host di destinazione non consentito, sblocca la connessione nel pannello di AlterVista (Risorse > Impostazioni PHP)'
            [raw] => 'HTTP/1.0 403 Forbidden
Date: Tue, 17 Jan 2017 11:16:50 GMT
Server: Apache
Content-Type: text/plain

Host di destinazione non consentito, sblocca la connessione nel pannello di AlterVista (Risorse > Impostazioni PHP)'
            [headers] => Requests_Response_Headers
            (
                [*:data] => array
                (
                    [date] => array
                    (
                        [0] => 'Tue, 17 Jan 2017 11:16:50 GMT'
                    )
                    [server] => array
                    (
                        [0] => 'Apache'
                    )
                    [content-type] => array
                    (
                        [0] => 'text/plain'
                    )
                )
            )
            [status_code] => 403
            [protocol_version] => 1
            [success] => false
            [redirects] => 0
            [url] => Requests_IRI
            (
                [*:scheme] => 'http'
                [*:iuserinfo] => null
                [*:ihost] => 'github-api-cache.unyson.io'
                [*:port] => null
                [*:ipath] => '/repos/ThemeFuse/Unyson-Shortcodes-Extension/releases/latest'
                [*:iquery] => null
                [*:ifragment] => null
                [*:normalization] => array
                (
                    [acap] => array
                    (
                        [port] => 674
                    )
                    [dict] => array
                    (
                        [port] => 2628
                    )
                    [file] => array
                    (
                        [ihost] => 'localhost'
                    )
                    [http] => array
                    (
                        [port] => 80
                    )
                    [https] => array
                    (
                        [port] => 443
                    )
                )
            )
            [history] => array()
            [cookies] => Requests_Cookie_Jar
            (
                [*:cookies] => array()
            )
        )
        [*:filename] => null
        [data] => null
        [headers] => null
        [status] => null
    )
)
![schermata 2017-01-17 alle 12 18 16](https://cloud.githubusercontent.com/assets/25160663/22018419/10ecc0fa-dcaf-11e6-9631-d2fb143a9a38.png)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/2332#issuecomment-273190702

**Comment by csas64** [comment]
Hello, I had the same error. I inserted the code you mentioned above and I have this message: 
WP_Error
(
    [errors] => array
    (
        [http_request_failed] => array
        (
            [0] => 'cURL error 7: '
        )
    )
    [error_data] => array()
)

Can you please tell me how to solve it? 
Thank you!

**Comment by JustinGuese** [comment]
still not solved, same issue
