### ISSUE TITLE
How to enable comments for portfolio CPT ?

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson#2309]
Hello , 

I tried removing action then adding my own action but have some issues. Maybe there's a better way?

```php
add_action('fw_init', '_action_skyplex_fw_init');
function _action_skyplex_fw_init() {
    $portfolio = fw()->extensions->get( 'portfolio' );
    remove_action( 'init', array( $portfolio, '_action_register_post_type' ) );
    add_action( 'init', '_action_skyplex_register_post_type_portfolio' );
}
``` 
then in `function _action_skyplex_register_post_type_portfolio()` I copied the array from framework and added comments to support.

**Comment by moldcraft** [comment]
Try

```
add_action('init', '_action_skyplex_register_post_type_portfolio', 20);
function _action_skyplex_register_post_type_portfolio() {
    // https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/42a34749de462a52b643d79813ff6ed1cb6dfc14/class-fw-extension-portfolio.php#L197
    unregister_post_type('fw-portfolio');

    // ...
}
```

**Comment by toleabivol** [comment]
Hi , 
unfortunately this solution will throw error in Theme Check and eventually theme won't be accepted by TF

`REQUIRED: The theme uses the register_post_type() function, which is plugin-territory functionality.`

To bypass this we can make a plugin.
But would be great just to have a filter there in Unyson's post array that we could overwrite.

**Comment by danyj** [comment]
I could have sworn that this worked before 

`add_post_type_support( 'fw-portfolio', 'excerpt' ,'comments');`


but now this one works and passes TF check


```
function _thz_filter_activate_projects_comments( $data ) {
    
	if( $data['post_type'] == 'fw-portfolio' ) {
        $data['comment_status'] = 'open';
    }

    return $data;
}
add_filter( 'wp_insert_post_data', '_thz_filter_activate_projects_comments' );
```

but I think filter here 
https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/fd0c1fbbbbd71ba7ac5f7713e17f13455b34e409/class-fw-extension-portfolio.php#L231

would fix this and we dont have to intercept things after the register_post_type

**Comment by danyj** [comment]
actually it is strange  , this still works 

    add_post_type_support( 'fw-portfolio', 'excerpt' );

and even the cpt does not have it I was able to enable excerpts

**Comment by danyj** [comment]
it works man , I was going nuts 


```
/**
 * CPT supports
 */
function _thz_action_fw_post_types_supports() {
	add_post_type_support( 'fw-portfolio', array( 'excerpt','comments') );
	add_post_type_support( 'fw-event', array( 'excerpt','comments') );
}

add_action( 'init', '_thz_action_fw_post_types_supports' );
```

**Comment by toleabivol** [comment]
Thanks a lot,
nice and short solution :+1:
