### ISSUE TITLE
Shorter way to get settings?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#231]
I've been tinkering with Unyson. Great, great framework. Some of the ways that it works are very original. Going to implement in my next project.

I have a simple question. Looking at the Scratch theme - is there a shorter way to get an option. For example this one:
```
$favicon = ( function_exists( 'fw_get_db_settings_option' ) ) ? fw_get_db_settings_option('favicon') : '';
	if( !empty( $favicon ) ) :
	?>
	<link rel="icon" type="image/png" href="<?php echo $favicon['url'] ?>">
	<?php endif ?>
```
Is there a way to do it without the `function_exists` part or it's very risky?

**Comment by danyj** [comment]
Make own set of functions that check for unyson functions. That is how I did it. It did bother me also the length of the function names but I made my own. Plus function_exists makes sure that the function exists like when plugin is disabled. 


You could do something along these lines  


	function theme_favicon(){
		if(!function_exists( 'fw_get_db_settings_option' )) return;
		
		$favicon = fw_get_db_settings_option('favicon');
		
		if( !empty( $favicon ) ) {
	   
			$html ='<link rel="icon" type="image/png" href="'.$favicon['url'].'">';
			
			echo $html;
		}
	}


inside https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/inc/helpers.php


and just call the theme_favicon() function instead.

**Comment by danyj** [comment]
And to actually  answer , yes you can use only this 

    fw_get_db_settings_option('favicon')

but problem with that is if for whatever reason the plugin is disabled , you theme user will have error on his front-end. So to avoid this issue , check for function is there.

**Comment by moldcraft** [comment]
@danyj Thank you *(I have nothing else to add)*

**Comment by pe6o** [comment]
Thanks for the super fast reply!
That gives me an idea. So I can do something like this:
```
function prefix_get_option($id){
    if(!function_exists( 'fw_get_db_settings_option' )) return;

    if ( !empty( fw_get_db_settings_option($id) )  ) {
        return fw_get_db_settings_option($id);
    }

}
```
And then I can remove the checks from the theme files. Using the example above:
```
$favicon = prefix_get_option('favicon');
if( !empty( $favicon ) ) :
?>
<link rel="icon" type="image/png" href="<?php echo $favicon['url'] ?>">
<?php endif ?>
```

This way I think everything should be alright?

**Comment by danyj** [comment]
that looks ok to me, even better than my example. leads me to list default options in my own default array and call them like you just did. This way everything stays in tact if plugin is disabled. @moldcraft anything you might want to add to this ?

**Comment by moldcraft** [comment]
> @danyj anything you might want to add to this ?

Nope, everything is right

**Comment by pe6o** [comment]
Just wanted to clarify if anyone stumbles on this. It's better to use:

```php
 if ( fw_get_db_settings_option($id)  ) {
        return fw_get_db_settings_option($id);
    }
```
instead of:
```php
 if ( !empty( fw_get_db_settings_option($id) )  ) {
        return fw_get_db_settings_option($id);
    }
```
Because in the second case you may get:
```
Fatal error: Can't use function return value in write context 
```

**Comment by moldcraft** [comment]
@pe6o better is just to

```php
return fw_get_db_settings_option($id); // by default it will return NULL
```

You can have option values like `''` (empty string), `false`, `0`.

----

Here is my version of the function:

```php
function fw_theme_get_option($option_id, $default_value = null) {
    if ( function_exists( 'fw_get_db_settings_option' ) ) {
        return fw_get_db_settings_option($option_id, $default_value);
    }

    return $default_value;
}
```

**Comment by danyj** [comment]
I use this 

	 /**
	 * Check if framework is loaded
	 * @return void
	 */
	function c_fw_loaded(){
		
		if(function_exists('fw_get_db_settings_option')){
			
			return true;
		}
	}
	
	
	 /**
	 * Get options value
	 * if framework is missing , load defaults
	 * @return option value
	 */
	function c_get_option($id,$default = ''){
		
		if (c_fw_loaded()) {
			
			
			return fw_get_db_settings_option($id);
			
			
		}else if(!empty( $default )){
			
			return $default;
			
		}
	
	}

and define option like 

    c_get_option('style','green')
