### ISSUE TITLE
Unyson issue in windows server

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2310]
Hello
Unyson extensions Page not working properly. 
Its broken 

![hello](https://puu.sh/thpnE/9a3b22918c.png)

If I check in console extension image path showing from our theme path, not plugin path. 

![plugin path](https://puu.sh/thpvd/dbaf574234.png)

If I check Page builder on the page, it's not available in the editor. Showing at the bottom of the editor. 

![page builder](https://puu.sh/thpq9/1f4f4096bf.png)

I have sent login details to your email.

Thanks

**Comment by moldcraft** [comment]
The site is loading very very very slow. Why is that?

**Comment by moldcraft** [comment]
On your server the file paths are network paths which begin with `//`, at the moment Unyson doesn't work with such paths (it works with `/linux/path` and `C:\windows-style\paths`).

Thank you for FTP details. I will try to fix it. My work day is already ending, so I will inspect this tomorrow.
