### ISSUE TITLE
disable_correction order  bug

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2312]
Strange one ,  

set 2 builder elements one after another , place them outside sections/columns 

in shortcode config.php  for first one set  

`'disable_correction' => true,`

save , disable_correction works 

move the one with disable_correction true under the other and save , 
disable_correction for the first element does not work.

**Comment by moldcraft** [comment]
![staticshot_11-01-2017_10-22-12](https://cloud.githubusercontent.com/assets/1475489/21840753/d49afbc4-d7e7-11e6-8cf3-9a867bbcceca.png)

![screenshot from 2017-01-11 10-22-47](https://cloud.githubusercontent.com/assets/1475489/21840765/ed1c7560-d7e7-11e6-9f0a-75cc9d8f0d62.png)

It works on my side _(or you provided poor reproduction steps)_

**Comment by danyj** [comment]
please test with button and another element that does not have correction disabled, not column or section ,

**Comment by danyj** [comment]
here test like this , 

add 'disable_correction' => true  to button ,  

than add button and call to action 


![78b189ebc3594e91b2ecad25601abc09](https://cloud.githubusercontent.com/assets/2340172/21850565/803e5778-d80b-11e6-976d-11da7d4a9faa.png)


correction works 

![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/21850567/868b9bc2-d80b-11e6-8272-80b3dfea6510.png)


change their order 

![screenshot_8](https://cloud.githubusercontent.com/assets/2340172/21850578/9913c706-d80b-11e6-994b-1751cdad5329.png)


and it does not


![screenshot_9](https://cloud.githubusercontent.com/assets/2340172/21850605/af71bdf0-d80b-11e6-9a4a-b5ad0722a3ce.png)
