### ISSUE TITLE
Issues with using icon-v2 and adding new font pack

### ISSUE THREAD

**Issue by saeedshabani** [ThemeFuse/Unyson#2313]
hello, i want to add a new font pack to Unyson. first add this code to functions.php of theme

```
add_filter('fw:option_type:icon-v2:packs', '_add_my_pack');

function _add_my_pack($default_packs) {

    global $theme_url;

    /**
     * No fear. Defaults packs will be merged in back. You can't remove them.
     * Changing some flags for them is allowed.
     */
    return array(
      'lamnoosh_pack' => array(
        'name' => 'lamnoosh', // same as key
        'title' => 'lamnoosh Pack',
        'css_class_prefix' => 'icon-lm',
        'css_file' => $theme_url.'/assets/fonts/lamnoosh/style.css',
        'css_file_uri' => $theme_url.'/assets/fonts/lamnoosh/style.css'
      )
    );
}
```

then in use this option

```
        'ios_app_icon' => array(
            'type'  => 'icon-v2',
            'preview_size' => 'medium',
            'modal_size' => 'medium',
             'value' => array(
                'type' => 'icon-font',
                'icon-class' => 'icon-lm',
                'icon-class-without-root' => false,
                'pack-name' => 'lamnoosh',
                'pack-css-uri' => false
             ),
            'label' => __('IOS icon', 'unyson'),
            'desc'  => __('select ios app icon', 'unyson'),
            'help'  => __(''),
        ), 
```

but when i select this font pack from icon fonts pake get `TypeError: pack is undefined` error in console log of browser.

**Comment by andreiglingeanu** [comment]
> `'name' => 'lamnoosh', // same as key`

correct that to `lamnoosh_pack`

>         'css_file' => $theme_url.'/assets/fonts/lamnoosh/style.css', // this should be file system path to the file, not URL! That's important.
>         'css_file_uri' => $theme_url.'/assets/fonts/lamnoosh/style.css' // this should be network accessible URL

**Comment by saeedshabani** [comment]
thanks now my icon pack is ok, but when select it, i cant see any icon

**Comment by andreiglingeanu** [comment]
1. Check if your CSS class prefix is fine (try to inspect specific icons and look if CSS is applied fine for them)
2. Look for any errors in JavaScript console, it may be that you've mistyped path to your fonts in CSS
