### ISSUE TITLE
Could anyone help me reset button for customize?

### ISSUE THREAD

**Issue by hlaporthein** [ThemeFuse/Unyson#2314]
Hello everyone,

I would like to add reset button in customizer. If we use  **theme setting** options, it has already that one.  I also saw there is a plugin called [Customizer Reset
](https://wordpress.org/plugins/customizer-reset-by-wpzoom/). Is that button available in unyson framework customizer?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/576#issuecomment-105047334
