### ISSUE TITLE
Text block is blank

### ISSUE THREAD

**Issue by gerardhserra** [ThemeFuse/Unyson#2316]
Hi everyone,

I have researched around the topics and I've found problems similar to this, but none has provided any solution for my issue. When I try to write in a Text Block, this is what I see:

<img width="1440" alt="captura de pantalla 2017-01-11 a les 23 13 38" src="https://cloud.githubusercontent.com/assets/25067770/21870378/06e8e43a-d854-11e6-8908-6c805f0428a6.png">

I've tried many things: I've updated to the latest version of Wordpress and Unyson, I've desactivated all plugins, I've tried to install old versions of Wordpress and Unyson... But nothing changes. Can anybody help me?

Thank you.

**Comment by moldcraft** [comment]
Hello,

Have you looked in browser Console or Network tab (to see the ajax response on modal open) ?

**Comment by gerardhserra** [comment]
Looking in browser Console that is what I see:

<img width="994" alt="captura de pantalla 2017-01-12 a les 14 48 07" src="https://cloud.githubusercontent.com/assets/25067770/21894198/33bdebfe-d8d6-11e6-9444-21e6be213169.png">

I've google it and adding `define( 'CONCATENATE_SCRIPTS', false );` to wp-config.php has solved the problem. Thanks!
