### ISSUE TITLE
errors after update 12-01-2017

### ISSUE THREAD

**Issue by iulianflst** [ThemeFuse/Unyson#2317]
Strict Standards:  Only variables should be passed by reference in framework\extensions\builder\includes\option-types\builder\extends\class-fw-option-type-builder.php on line 216

**Comment by moldcraft** [comment]
Hello,

This is [that line](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/v1.2.7/includes/option-types/builder/extends/class-fw-option-type-builder.php#L216).

Is Unyson up-to-date?

**Comment by iulianflst** [comment]
I just update it few hours ago

**Comment by moldcraft** [comment]
`fw_akg()` Doesn't use reference parameter anymore

https://github.com/ThemeFuse/Unyson/blob/v2.6.12/framework/helpers/general.php#L161

you for sure have an older version of unyson

**Comment by iulianflst** [comment]
As I said I went to Wordpress Dashboard-> Updates and I clicked the button update extensions

After update I got version 2.6.8

Today I downloaded the version from git: Unyson 2.6.12

I included the framework in my plugin **so it would be best if I could disable update extension** (I will update it manually every time is the case ) Is anyway I can do that ?

Here is a print screen

<img src="https://www.sodasi.com/bug.jpg" alt="unyson bug" />

**Comment by moldcraft** [comment]
> I included the framework in my plugin so it would be best if I could disable update extension (I will update it manually every time is the case ) Is anyway I can do that ?

Include it without the `framework/extensions/update` directory.
