### ISSUE TITLE
Upload option type missing image sizes

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2318]
When I add image via default wp-editor I can see image sizes to select from , 

![screenshot_11](https://cloud.githubusercontent.com/assets/2340172/21895762/1c9e74a8-d8e4-11e6-999f-b5f26e95da27.png)

but when I use upload option type those are not available so the user is always forced to pick original image

![screenshot_12](https://cloud.githubusercontent.com/assets/2340172/21895793/45b61698-d8e4-11e6-835c-ff79e7c8d31b.png)

**Comment by moldcraft** [comment]
As far as I know, the upload option is saving the `attachment_id` (also the image `url` in case you need it in backend right away to be used in js). In frontend template you use `attachment_id` to retrieve the image url of a given size https://developer.wordpress.org/reference/functions/wp_get_attachment_image_src/

**Comment by danyj** [comment]
I can retrieve it just right and mangle with attachment_id but think of this , I use the upload as a background image for sections/columns or anything ,  user uploads very large image 4kx4k which gets auto processed on upload for smaller images ,  now in order for user to use one of the processed sizes I must create additional option for them , than  on output mess with attachment_id , 

all this would not be necessary if we had the sizes option visible and let the user automatically pick the image size

**Comment by moldcraft** [comment]
That sounds like a new option-type which will save only image size url, without attachment_id (to prevent the developer to mess the user expectations - use only the selected size)

**Comment by andreiglingeanu** [comment]
@danyj This sounds like a legit addition to existing `upload` option type. Indeed, having to manually insert image sizes is a pain for the user. I'll try to inspect this.

**Comment by danyj** [comment]
@andreiglingeanu I ended up adding it via filter, `attachment_fields_to_edit`

![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/23580662/22dff0f4-0106-11e7-8392-41e0d058d5a3.jpg)

**Comment by andreiglingeanu** [comment]
Got it. Too bad it doesn't work on any Unyson install. I'll look that up anyway

**Comment by danyj** [comment]
>  Too bad it doesn't work on any Unyson install , 

true , the upload option should have setting for it

**Comment by avdan** [comment]
@danyj I'm quite interested in how you achieved this. I would really appreciate it if you could tell me, I'm trying to add this option to the image element in Unyson and I'm not really making any progress with it.

**Comment by andreiglingeanu** [comment]
Yes, the correct way for that is to use a filter, no need for a special option from Unyson's option type.

@avdan Look for that `attachment_fields_to_edit` filter and how to use it properly.

**Comment by danyj** [comment]
@avdan , @andreiglingeanu , dont use it ,  

there are implications ,   I used it originally but ended up creating own  image upload with  the selection 
reason being ,  if you use the `attachment_fields_to_edit `and you select the image size to be used in that specific post and than use same image for something else ,  you endup with same image sizes in every post and are bound to it especially if you have unified function that prints the image output with size. 

what I did at the end is created own image upload with `wp.media.frames`   and  `frame: 'post',` instead select , 

			thz_media_frame = wp.media.frames.thz_media_frame = wp.media({

				className: 'media-frame thz-media-frame',
				frame: 'post',
				state:    'insert',
				multiple: false,
				title: thz_image.title,
				library: {
					type: 'image'
				}

			});

  that one shows the image size, 

http://prntscr.com/g1ef1o

 than on save   I save attachment ID ,  user selected image URL and image size,   this way I am not bound to image post size selection but get actual user select url.

**Comment by avdan** [comment]
Thank you both for taking the time to answer!
I'll try your solution, although in the meantime I found a simpler workaround: instead of inserting the image through the image element, I can do it (in this case) by using a text element, where I already had the size options.
