### ISSUE TITLE
How to extend/change megamenu markup?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#232]
I need to surround sub-menu ul's with a div, change few class names and add some additional markup to a elements like span etc. What would be the best way to do this ?

**Comment by moldcraft** [comment]
I was thinking to create more filters for this, but you want to make so many changes that it will be simpler to just extend the mega-menu walker and change whatever you want.

I explained here [how to extend the default walker](https://github.com/ThemeFuse/Unyson/issues/79#issuecomment-74970280)
