### ISSUE TITLE
Demo-Install from console

### ISSUE THREAD

**Issue by mowshon** [ThemeFuse/Unyson#2320]
We work on WP CLI integration in Unyson: https://github.com/ThemeFuse/Unyson/issues/2277
And next step that we want to have in Unyson CLI is to install demo content from console.

```
wp unyson demo install my-demo-slug
```

The problem is that Unyson demo content install process is realised in frontend. JS script run tasks step by step.

@moldcraft can we make some backend tools for demo-content install from terminal?

**Comment by mowshon** [comment]
This code put the demo-content in install queue, but the result of procces is avaible only on demo-content page in admin panel.

```php
$demos = fw_ext('backups-demo')->get_demos();
fw_ext('backups-demo')->do_install($demos['demo-slug']);
```

**Comment by moldcraft** [comment]
1. https://github.com/mowshon/Unyson/commit/0d7f0dcfc95fff64c2c99ade4e15e6045700642b
2. https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/1ac353751d5617c9eb754b81f0760fdd7b29df6b
