### ISSUE TITLE
Unyson Content-backup from WP-CLI

### ISSUE THREAD

**Issue by mowshon** [ThemeFuse/Unyson#2321]
Commit: https://github.com/ThemeFuse/Unyson/pull/2278/commits/913fb2710bdd51557cc9e53e12a69bc1b7215123

Content backup from terminal:
```
wp unyson backup content
wp unyson backup full (not done yet)
```

This tool will help us to create the `content backup` and `full backup` from Unyson WP-CLI.

### Some problems & questions
1. I use some system tools to copy files and create zip arhive.
https://github.com/mowshon/Unyson/blob/913fb2710bdd51557cc9e53e12a69bc1b7215123/framework/wp-cli/commands/fw-cli-command-backup.php#L64-L74
`cd, mkdir, rm` and php function `shell_exec`

2. Need new method like: `_get_task_type` without `FW_Access_Key` check (create database dump).
https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/313a2767f248c20cdb8c6f639a420da74a839bdf/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L115

@moldcraft what do you think about this?

**Comment by moldcraft** [comment]
I will take a look at this later (it's not a priority)

**Comment by ivandotv** [comment]
@mowshon Why do we need a special "backup" option for unyson?
WP-CLI can already do backups.

**Comment by andreiglingeanu** [comment]
@ivandotv The main goal of this issue is not really to be able to do backups from cli. What we really is to be able to execute [`schedules`](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/schedule/class--fw-ext-backups-module-schedule.php) of tasks for cli. This, by extent, will provide us with a way to do Unyson backups from cli, and also a way to apply demo contents (and way more, potentially) in a scriptable way -- that's where the power of this feature resides.

**Comment by mowshon** [comment]
@ivandotv yes, WP CLI by himself can make backups, but this backups can't be importend from Unyson Backups web interface in admin panel. With Unyson-CLI all backups will apere here in "Archives":

![Backups](https://i.gyazo.com/9589cade3be89c160307bf792d94d33f.png)

**Comment by moldcraft** [comment]
Shouldn't the backup command live in backups extension directory?

**Comment by andreiglingeanu** [comment]
@moldcraft Let's not separate CLI commands. We'll build a separated `wp-cli` package specifically for unyson which will contain all of that code with proper checks.

**Comment by moldcraft** [comment]
Okay

_P.S. I am working on backup command now._

**Comment by andreiglingeanu** [comment]
Great!

**Comment by moldcraft** [comment]
https://github.com/mowshon/Unyson/pull/1/commits/deeaa9d6e19ae5e27997ba4d2c921ce3e5a91598

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/9425a7acc26d9c3b39e99be4d3d0f7cebf8b12a9
