### ISSUE TITLE
Upgrading php version

### ISSUE THREAD

**Issue by runpatboyrun** [ThemeFuse/Unyson#2322]
Hey there, 
When upgrading to a more recent version of PHP, I'm getting a fatal error message and my site is not loading.

Fatal error: Class 'ZipArchive' not found in /home/playfulpen1/public_html/staging/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php on line 418

It seems to be concerning the Unyson plugin but I'm not sure how to deal with this.

Help?

**Comment by Ataurr** [comment]
Contact your hosting provider to enable Zip Extension on your server.

**Comment by moldcraft** [comment]
[The line 418](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.18/class-fw-extension-backups.php#L418) is empty in latest version, so you have an outdated extension installed. Please update Unyson extensions.

**Comment by runpatboyrun** [comment]
I have updated Unyson and I still can't upgrade to PHP 5.5
I get a fatal error every time I try!!

**Comment by runpatboyrun** [comment]
Warning: Class ZipArchive not found. Please install php zip extension in /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php on line 446

Warning: Class ZipArchive not found. Please install php zip extension in /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php on line 446

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-content/plugins/wise-chat/src/dao/user/WiseChatUserSessionDAO.php on line 95

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-login.php on line 394

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-login.php on line 407

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 915

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 916

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 917

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 918

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 919

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 920

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 923

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 924

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 925

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 926

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 929

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 930

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 931

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 932

Warning: Cannot modify header information - headers already sent by (output started at /home/playfulpen1/public_html/wp-content/plugins/unyson/framework/extensions/backups/class-fw-extension-backups.php:446) in /home/playfulpen1/public_html/wp-includes/pluggable.php on line 1179

**Comment by moldcraft** [comment]
Please install `php-zip` package
