### ISSUE TITLE
Is it possible to add a link to an icon box?

### ISSUE THREAD

**Issue by micronpn** [ThemeFuse/Unyson#2323]
I would like to have the possibility to link another page to an icon box so that clicking on it the user may navigate to the corresponding page. Is it possible?

**Comment by Ataurr** [comment]
Yes possible. You have to modify this view.php
wp-content/themes/Your Theme Name/framework-customizations/extensions/shortcodes/shortcodes/icon-box/view/view.php

**Comment by thednp** [comment]
And also the `options.php` for an `URL` option ;)

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content
