### ISSUE TITLE
help me please!!

### ISSUE THREAD

**Issue by aligatorec** [ThemeFuse/Unyson#2326]
The execution failed. Please check error.log i have this problem with my template  Jevelin

![image](https://cloud.githubusercontent.com/assets/25142709/21969782/ae6bec58-db6e-11e6-9c98-71c6bdff7243.png)

**Comment by moldcraft** [comment]
Hello,

On which step this happens (Database restore or Image Sizes Restore) ?

**Comment by moldcraft** [comment]
Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by anilhada** [comment]
error with your demo file compressing. select demo file and use  right click and than compress.
