### ISSUE TITLE
Hide slider population method if only one method

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2329]
Since this does not work https://github.com/ThemeFuse/Unyson/issues/1907
I am forced to use only one population method 

    $cfg['population_methods'] = array('custom');

can we hide the Population Method select if only one method is available ?

![screenshot_13](https://cloud.githubusercontent.com/assets/2340172/21997434/9bf724a4-dc2f-11e6-8192-cd975675ccc8.png)

**Comment by moldcraft** [comment]
I will revert this change because in our theme it triggers errors after slider add.

**Comment by danyj** [comment]
ok , thnx for heads up , I did it via CSS
