### ISSUE TITLE
Possible megamenu theme_location bug

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#233]
If I use theme_location  primary like you have in scratch-theme the mega menu div container apears
http://screencast.com/t/UaiO52l7NFl
If I have own location like 

	/**
	 * Register theme menus
	 */
	 register_nav_menus( array(
	 
		'topmenu'   => __( 'Top Menu', 'fw' ),
		'sidemenu' => __( 'Secondary menu in sidebar', 'fw' ),
		)
		
	);

and use topmenu as theme_location  the mega menu container and menu items fa icons are gone

http://screencast.com/t/DkrCSnXC

**Comment by danyj** [comment]
Same thing with scratch theme 
changed 

https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/header.php#L60
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/inc/menus.php#L8

to topmenu

http://screencast.com/t/H4786zojT

assigned the menu 

http://screencast.com/t/ulMwLoy1Skg

Back to primary 
http://screencast.com/t/nMGe6AEXJZ0u

**Comment by moldcraft** [comment]
@danyj Please install manually [v1.0.4](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/releases/tag/v1.0.4) to `plugins/unyson/framework/extensions/megamenu` I removed that hardcode. Now mega menu should work for any theme_location

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/23
