### ISSUE TITLE
Can't download extensions to dashboard

### ISSUE THREAD

**Issue by Jelena1** [ThemeFuse/Unyson#2332]
One of my customers reported this issue (I've checked and have the same issue on my server). 

When trying to download any of Unyson extensions, this error appears:

_Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Resolving timed out after 5002 milliseconds)_

Can you please check this issue?

Thanks.

**Comment by moldcraft** [comment]
Hello,

Test with this code if your server is able to access our server

```php
add_action('admin_notices', function(){
    fw_print(wp_remote_get('http://github-api-cache.unyson.io/repos/ThemeFuse/Unyson-Backups-Extension/releases/latest'));
});
```

**Comment by Jelena1** [comment]
After adding the code in functions.php this appears in dashboard:

WP_Error
(
    [errors] => array
    (
        [http_request_failed] => array
        (
            [0] => 'cURL error 28: Resolving timed out after 5004 milliseconds'
        )
    )
    [error_data] => array()
)

**Comment by davidami** [comment]
Hello everyone,

I'm the Jelena's customer, all console error is:

array
(
[headers] => Requests_Utility_CaseInsensitiveDictionary
(
[:data] => array
(
[date] => 'Tue, 17 Jan 2017 11:16:50 GMT'
[server] => 'Apache'
[content-type] => 'text/plain'
)
)
[body] => 'Host di destinazione non consentito, sblocca la connessione nel pannello di AlterVista (Risorse > Impostazioni PHP)'
[response] => array
(
[code] => 403
[message] => 'Forbidden'
)
[cookies] => array()
[filename] => null
[http_response] => WP_HTTP_Requests_Response
(
[:response] => Requests_Response
(
[body] => 'Host di destinazione non consentito, sblocca la connessione nel pannello di AlterVista (Risorse > Impostazioni PHP)'
[raw] => 'HTTP/1.0 403 Forbidden
Date: Tue, 17 Jan 2017 11:16:50 GMT
Server: Apache
Content-Type: text/plain
Host di destinazione non consentito, sblocca la connessione nel pannello di AlterVista (Risorse > Impostazioni PHP)'
[headers] => Requests_Response_Headers
(
[:data] => array
(
[date] => array
(
[0] => 'Tue, 17 Jan 2017 11:16:50 GMT'
)
[server] => array
(
[0] => 'Apache'
)
[content-type] => array
(
[0] => 'text/plain'
)
)
)
[status_code] => 403
[protocol_version] => 1
[success] => false
[redirects] => 0
[url] => Requests_IRI
(
[:scheme] => 'http'
[:iuserinfo] => null
[:ihost] => 'github-api-cache.unyson.io'
[:port] => null
[:ipath] => '/repos/ThemeFuse/Unyson-Shortcodes-Extension/releases/latest'
[:iquery] => null
[:ifragment] => null
[:normalization] => array
(
[acap] => array
(
[port] => 674
)
[dict] => array
(
[port] => 2628
)
[file] => array
(
[ihost] => 'localhost'
)
[http] => array
(
[port] => 80
)
[https] => array
(
[port] => 443
)
)
)
[history] => array()
[cookies] => Requests_Cookie_Jar
(
[:cookies] => array()
)
)
[*:filename] => null
[data] => null
[headers] => null
[status] => null
)
)

Thanks for help

**Comment by moldcraft** [comment]
Your hosting is blocking requests to our site `http://github-api-cache.unyson.io`

> Host di destinazione non consentito, sblocca la connessione nel pannello di AlterVista (Risorse > Impostazioni PHP)

```
Host of unauthorized destination, unlock the connection in AlterVista panel (Resources> PHP Settings)
```
