### ISSUE TITLE
UNYSON SEO not working

### ISSUE THREAD

**Issue by OguzhanGonel** [ThemeFuse/Unyson#2333]
Hi guys,

I am using the UNYSON framework and wanted to use its SEO extension rather than yoast for a change. It's been 4 days, and the website still does not show up on google. Any ideas?

I also have a current website that's been around for 1 year and that one shows but the seo extension for that one doesn't work as well.

Thanks in advance.

**Comment by moldcraft** [comment]
Hello,

It's hard to say what's not working. Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by mowshon** [comment]
Your site have 4 days only?
In this case is nothing wrong with seo extension, just waiting for Google robot.

**Comment by OguzhanGonel** [comment]
Ah I see, ok thanks mowshon.

Moldcraft, I'll wait a few more days to see if works.

Thanks guys :)

**Comment by mowshon** [comment]
You can:
- Put the Google Analytics code on your site.
- Create the sitemap.xml (use some plugin) and put the link in your robots.txt
- Create some groups in Facebook, Twitter, Google+ and share with links from your site

This is few tips will make Google Robot to visit youre site.
Read some articles for SEO.

**Comment by OguzhanGonel** [comment]
Sweet, thanks :)
