### ISSUE TITLE
option-type - wp-link

### ISSUE THREAD

**Issue by yanickvanbarneveld** [ThemeFuse/Unyson#2337]
Is it hard to implement the WordPress build-in popup wp-link in a option type so I can use it in the page builder?

**Comment by yanickvanbarneveld** [comment]
Hi Moldcraft,

How is it going with this one?

**Comment by moldcraft** [comment]
Hello,

I don't have plans to start working on this soon. _I just attached the issue to myself._

**Comment by yanickvanbarneveld** [comment]
Almost working solution, sometimes returns an strange error.

`<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

class FW_Option_Type_WPLink extends FW_Option_Type
{
    public function get_type()
    {
        return 'wplink';
    }

    /**
     * @internal
     */
    protected function _enqueue_static($id, $option, $data)
    {
		wp_enqueue_script('wplink');
    	wp_enqueue_style('editor-buttons');
    }

    /**
     * @internal
     */
    protected function _render($id, $option, $data)
    {
        /**
         * $data['value'] contains correct value returned by the _get_value_from_input()
         * You decide how to use it in html
         */
        $option['attr']['value'] = (string)$data['value'];

        /**
         * $option['attr'] contains all attributes.
         *
         * Main (wrapper) option html element should have "id" and "class" attribute.
         *
         * All option types should have in main element the class "fw-option-type-{$type}".
         * Every javascript and css in that option should use that class.
         *
         * Remaining attributes you can:
         *  1. use them all in main element (if option itself has no input elements)
         *  2. use them in input element (if option has input element that contains option value)
         *
         * In this case you will use second option.
         */

        $wrapper_attr = array(
            'id'    => $option['attr']['id'],
            'class' => $option['attr']['class'],
        );

		$html = fw()->backend->option_type('text')->render(
            'attr',
            array(
                'type'  => 'text',
                'value' => (isset($option['value']['attr'])) ? $option['value']['attr'] : '',
                'attr'  => array(
                    'class' => 'attr',
					'style' => 'display: none;'
                )
            ),

            array(
                'value'	=> (isset($data['value']['attr'])) ? $data['value']['attr'] : $option['value']['attr'],
                'id_prefix'   => $data['id_prefix'] . $id . '-',
                'name_prefix' => $data['name_prefix'] . '[' . $id . ']',
            )
        );

		$name = $data['id_prefix'] . $id . '-text';

		$html .= fw()->backend->option_type('text')->render(
            'text',
            array(
                'type'  => 'text',
                'value' => (isset($option['value']['text'])) ? $option['value']['text'] : '',
                'attr'  => array(
                    'class' => 'wplink-text'
                )
            ),

            array(
                'value'	=> (isset($data['value']['text'])) ? $data['value']['text'] : $option['value']['text'],
                'id_prefix'   => $data['id_prefix'] . $id . '-',
                'name_prefix' => $data['name_prefix'] . '[' . $id . ']',
            )
        );

		require_once ABSPATH . "wp-includes/class-wp-editor.php";
		_WP_Editors::wp_link_dialog();

		 $html .= '
		 <script type="text/javascript">
	 		var ajaxurl = "' . admin_url( 'admin-ajax.php') . '";
	 		jQuery(document).ready(function() {
		 		jQuery("#'.$data['id_prefix'] . $id . '-text'.'").click(function() {
					jQuery("#'.$data['id_prefix'] . $id .'-text").val("");
					jQuery("#'.$data['id_prefix'] . $id .'-attr").val("");

					wpLink.open("'.$data['id_prefix'] . $id .'-text");
		 		});

				jQuery("#wp-link-submit").click(function() {
					var val = wpLink.textarea.value;
					var url = "href=\"" + jQuery(val).attr("href") + "\"";

					if (typeof jQuery(val).attr("target") != "undefined") {
						url = url + " target=\"" + jQuery(val).attr("target") + "\"";
					}

					var text = jQuery(val).text();

					jQuery("#'.$data['id_prefix'] . $id .'-text").val(text);
					jQuery("#'.$data['id_prefix'] . $id .'-attr").val(url);
				});
	 		});
 		</script>';


        return $html;
    }

    /**
     * @internal
     */
    protected function _get_value_from_input($option, $input_value)
    {
        /**
         * In this method you receive $input_value (from form submit or whatever)
         * and must return correct and safe value that will be stored in database.
         *
         * $input_value can be null.
         * In this case you should return default value from $option['value']
         */

		 if (is_array($input_value)) {
         $value = array();
		 $value['attr'] = '';
		 $value['text'] = '';

         if (isset($input_value['attr'])) {
             $value['attr'] = $input_value['attr'];
         }

         if (isset($input_value['text'])) {
             $value['text'] = $input_value['text'];
         }

         return $value;
     }

     return $option['value'];
    }

    /**
     * @internal
     */
    protected function _get_defaults()
    {
        /**
         * These are default parameters that will be merged with option array.
         * They makes possible that any option has
         * only one required parameter array('type' => 'new').
         */

        return array(
            'value' => array(
				'text' => '',
				'attr' => ''
			)
        );
    }
}

FW_Option_Type::register('FW_Option_Type_WPLink');
`
