### ISSUE TITLE
Image gallery deforms image thumbnails

### ISSUE THREAD

**Issue by nzurita** [ThemeFuse/Unyson#2339]
Hello, when inserting an image gallery into a post, all formats offered (all of them are some kind of masonry), deform the image thumbnail to fit gallery format.

Is it possible to avoid this and respect original image proportions?

![capture-gallery](https://cloud.githubusercontent.com/assets/921345/22100524/415d44c6-de30-11e6-9cda-d20f33a0fa36.png)

**Comment by ivandotv** [comment]
This is not a framework issue.
Try asking for a solution on [Wordpress stack exchange ](http://wordpress.stackexchange.com/)

**Comment by nzurita** [comment]
Sorry, I may have misunderstood what Unyson is, isn't this gallery part of Unyson? Do you know where they come from? If I find the real source maybe I find better help than in StackExchange.

Thanks!

![unyson](https://cloud.githubusercontent.com/assets/921345/22142009/e316c8f4-def4-11e6-9bc9-3af0ce9b7f25.jpg)

**Comment by moldcraft** [comment]
The Gallery shortcode is not part of Unyson default shortcodes, it's part of your theme. Please report this to theme author.
