### ISSUE TITLE
 No default view (views/view.php) found for shortcode: section in /opt/wordpress-4.5.2.php56-0/apps/wordpress/htdocs/wp-content/plugins/unyson/framework/extensions/shortcodes/includes/class-fw-shortcode.php on line 196

### ISSUE THREAD

**Issue by codalpayalshah** [ThemeFuse/Unyson#2341]
No default view (views/view.php) found for shortcode: section in /opt/wordpress-4.5.2.php56-0/apps/wordpress/htdocs/wp-content/plugins/unyson/framework/extensions/shortcodes/includes/class-fw-shortcode.php on line 196

i am facing this issue because of this website down completely .
please help me as soon as.

**Comment by moldcraft** [comment]
https://wordpress.org/support/topic/view-php-file-not-found/#post-8673397
