### ISSUE TITLE
Time zone support for Events?

### ISSUE THREAD

**Issue by sandervenema** [ThemeFuse/Unyson#2343]
Hi, 

I was wondering whether the Unyson Events module contains time zone support? I tried looking elsewhere (also on your site) but cannot find a definitive answer on it, and after a quick glance there seems to be no time zone handling code in the source code of the module, so it doesn't seem like it supports it.

The use case I have is for that a U.S.-based organisation that operates nation-wide posts events to their site based in various time zones, and the event times are very confusing without time zones. Also, sometimes events are more naturally expressed in the time zone in which they take place (EST, PDT, etc.) so setting just one time zone for the entire site (like the time zone on the Wordpress settings page) is no option, and there is no option to select a specific time zone per event. Even just a static time zone select that shows the time zone selected on the front-end next to the times would help I think.

For this client I will probably code in a time zone select box that shows that value on the front end, but I was wondering whether there was support for this already.

**Comment by moldcraft** [comment]
Hello,

Unfortunately there is no support for time zones.

https://github.com/ThemeFuse/Unyson/issues/1722

**Comment by sandervenema** [comment]
Hi, okay, no problem. Are there any plans for maybe adding support in the future? I can imagine more people maybe would like time zone support.

**Comment by moldcraft** [comment]
No plans at the moment.

**Comment by sandervenema** [comment]
OK thanks.
