### ISSUE TITLE
Unyson trying to load font from old site

### ISSUE THREAD

**Issue by colinmcparland** [ThemeFuse/Unyson#2344]
Hi there,
We're using Unyson on our site.  We recently moved the site to a new URL, everything updated properly but there is one area that is trying to fetch a .ttf font from the old URL, at the wrong path to boot.

I tried disabling all plugins except for Unyson and the problem persisted, it even persisted when I reverted back to a default theme.

Another curious issue here is that on the page that is requesting the .ttf, the back-end editor is in a custom font, so I imagine the issue is deep seeded.  Ive attached a couple of screenshots illustrating our errors, any feedback would be very much appreciated.  Thank you!!

This is the error that is showing:

![screen shot 2017-01-19 at 12 12 31 pm](https://cloud.githubusercontent.com/assets/7502241/22123473/9502b25e-de40-11e6-8a52-e94c63ecb7cd.png)

This is the code that is causing the timeout:
![screen shot 2017-01-19 at 12 11 54 pm](https://cloud.githubusercontent.com/assets/7502241/22123487/9fd78d58-de40-11e6-8318-dcbcb9353e1b.png)

**Comment by danyj** [comment]
that is revolution slider script , did you change links in rev slider ?

**Comment by colinmcparland** [comment]
Ah yes there was an unchanged style buried in Rev Slider.  Thanks for your quick support!!
