### ISSUE TITLE
Error with sidebars extension

### ISSUE THREAD

**Issue by eyeswizard** [ThemeFuse/Unyson#2345]
Hello,
one of our clients reported this error in sidebars extension:

> Warning: Parameter 2 to _filter_fw_ext_sidebars_title_like_posts_where() expected to be a reference, value given in /home/...../public/.../wp-includes/class-wp-hook.php on line 298”

What is the wrong with the following function?

```php
function _filter_fw_ext_sidebars_title_like_posts_where( $where, &$wp_query ) {
	/**
	 * @var WPDB $wpdb
	 */
	global $wpdb;

	if ( $post_title_like = $wp_query->get( 'fw_ext_sidebars_post_title_like' ) ) {
		$where .= $wpdb->prepare(' AND ' . $wpdb->posts . '.post_title LIKE %s', '%'. $wpdb->esc_like( $post_title_like ) .'%' );
	}

	return $where;
}
add_filter( 'posts_where', '_filter_fw_ext_sidebars_title_like_posts_where', 10, 2);
```

WP 4.7.1 PHP 7.1

Best regards...

**Comment by moldcraft** [comment]
Remove `&` from `&$wp_query`

**Comment by eyeswizard** [comment]
@moldcraft  i tried to reproduce the error but it didn't happen, so i copied this function from
> C:\xampp\htdocs\window\wp-content\plugins\unyson\framework\extensions\sidebars\hooks.php

for more help

**Comment by moldcraft** [comment]
Sorry, I thought it's in your theme.

**Comment by moldcraft** [comment]
Please test. If it works I will create a new version asap.

**Comment by eyeswizard** [comment]
thank you, i will test it now

**Comment by eyeswizard** [comment]
it's working with no errors on my development environment. but you have to know that i wasn't able to reproduce the error.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Sidebars-Extension/releases/tag/v1.0.16
