### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xasuo** [ThemeFuse/Unyson#2346]
I use docdirect theme and when i try to any page with visual page builder, it shows me this page(attached).
<img width="960" alt="problememptypage" src="https://cloud.githubusercontent.com/assets/25246182/22150037/ff556222-df27-11e6-871c-e10a4ef86a45.png">

**Comment by moldcraft** [comment]
Hello,

There is no `require()` on [line 685](https://github.com/ThemeFuse/Unyson/blob/v2.6.13/framework/helpers/general.php#L685).

Please update Unyson plugin. If the error persists, then activate a default WP theme and check again, if the error is gone then it's a theme problem and you should report it to theme author.

**Comment by xasuo** [comment]
<img width="960" alt="problem2" src="https://cloud.githubusercontent.com/assets/25246182/22159438/f27de8e2-df51-11e6-8285-95bb423af564.png">
<img width="960" alt="problem3" src="https://cloud.githubusercontent.com/assets/25246182/22159437/f27db994-df51-11e6-8f47-ff75d55a8c8b.png">
<img width="960" alt="problem1" src="https://cloud.githubusercontent.com/assets/25246182/22159436/f27d808c-df51-11e6-8f60-ae64cb6a6343.png">

**Comment by xasuo** [comment]
I reinstall unyson an hour ago.Now it says "Unyson backup needs php zip extension",but i already install all extensions available in Unyson Extensions

**Comment by xasuo** [comment]
<img width="960" alt="problem5" src="https://cloud.githubusercontent.com/assets/25246182/22159723/53966f40-df53-11e6-9678-431dcc61bf2d.png">

I changed the theme and create a trial page,it seems ok now? Do you think problem has been caused by Docdirect theme?

**Comment by moldcraft** [comment]
Yes, the problem seems to be caused by your theme.

I will fix the Backup warning.
