### ISSUE TITLE
Multiple widget instance are not displaying.

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#2347]
I have created widget. For one widget it display perfectly but if widget is more than one it doesn't display. 
Also if same two widgets present, values always display from first widget. 
![untitled-2](https://cloud.githubusercontent.com/assets/7946657/22154269/09625c52-df55-11e6-966d-3ab59aa1f4c4.jpg)

**Comment by GheorgheP** [comment]
Hmmm, Unyson doesn't really deal with widgets directly, so does your widget work properly without Unyson, or the widget is somehow related with Unyson?

**Comment by webangon** [comment]
I have created the widget field using unyson.

**Comment by moldcraft** [comment]
How to test this? Can you make a video or the exact steps to reproduce the problem?
