### ISSUE TITLE
How to show only Google Fonts in Typography v2?

### ISSUE THREAD

**Issue by iulianflst** [ThemeFuse/Unyson#2348]
I need to show up only Google fonts in typography v2, how can I do it?

**Comment by moldcraft** [comment]
Hello,

Have you tried [this filter](https://github.com/ThemeFuse/Unyson/blob/7b202c8f9ca207f311c72e50afe2b6a1c4b0a598/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php#L56)?

**Comment by iulianflst** [comment]
yes, it works. Thank you!

**Comment by zenics** [comment]
how do you limit to google fonts to be only the selected ones?

**Comment by iulianflst** [comment]
try with filter fw_option_type_typography_v2_standard_fonts

**Comment by zenics** [comment]
@iulianflst I know that can be dealt with the filter but, I am not a dev, so any way you can give me the function to set the loaded fonts to be 2  selected ones?

**Comment by iulianflst** [comment]
function _filter_theme_typography_standard_fonts( $fonts ) {

   	return array here 
   
}
add_filter( 'fw_option_type_typography_v2_standard_fonts', '_filter_theme_typography_standard_fonts' );

Talk with the theme author.

**Comment by yura-x** [comment]
Hello! Thanks for your great work! Got following requirement from theme reviewer:

> It is recommended that theme options do not include a drop down list of all Google Fonts, as this can be confusing for users

It seems that this filter can only limit 'standard' key of fonts array, but not 'google' .  Can we limit number of Google fonts with certain fonts that we choose? 
Thank you!
