### ISSUE TITLE
How to Render google fonts <link> from Typography settings without styling extension

### ISSUE THREAD

**Issue by azharijelek** [ThemeFuse/Unyson#235]
Hi... I'm almost done finishing my theme. I'd like to say that using this framework has save me a lot of time.

well, I see that styling extension will automatically (and smarter) to render <link> to request google webfont url.

But the problem is, I don't like to use styling extension. I just want users styling the theme via theme settings page. That's all. 

Thank you in advance. :)

**Comment by azharijelek** [comment]
Nevermind, I've made my own class (simple and easy). Thank you. :). 

I close this thread.

**Comment by invisiblevision** [comment]
Hey Can you please share the class?
