### ISSUE TITLE
is there is any way to auto install extensions updates?

### ISSUE THREAD

**Issue by bbioon** [ThemeFuse/Unyson#2351]
as the title says : is there is any way to auto install extensions updates?

**Comment by moldcraft** [comment]
At the moment no.

**Comment by eyeswizard** [comment]
Thanks 👍

**Comment by GheorgheP** [comment]
I don;t think we will implement this as auto update may break the site functionality, so the update should be made manually by the administrator, so in case something will go wrong to restore back.
