### ISSUE TITLE
Demo install - Failed to copy: ../fw-backup/tmp/manifest.php

### ISSUE THREAD

**Issue by mintaras** [ThemeFuse/Unyson#2354]
Hi,

I am having error on demo content install on multisite network.
Error:

` Failed to copy: ../wp-content/uploads/sites/28/fw-backup/tmp/manifest.php`

Thanks

**Comment by moldcraft** [comment]
Hello,

Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?
