### ISSUE TITLE
Cant change background unless padding block is ticked

### ISSUE THREAD

**Issue by Dorvalla** [ThemeFuse/Unyson#2358]
When developping a site, we found an issue that our background color / background images only could be displayed if block padding in the items was ticked on. While we dont want the block padding, or a different ammount (which is also not settable) we found this a very big limitation of the Unyson Frame Builder. Any fix for this?

**Comment by GheorgheP** [comment]
Hmm, Unyson doesn't have any `Unyson Frame Builder`, may be do you mean the Page Builder?
What kind of block you are about? By default the only shortcode with background image/color is the `Section` shortcode, but it doesn't have the `padding` option, usually this option is added by the theme developers to extend the Section functionality.

As you said that you are the developer, I guess you added the padding functionality. I'm not sure about your code, but there may be more a CSS styling problem, What I mean is that when you enable the padding, you may be add the padding style `padding-bottom: 10px` and do not put the `;` at the end and you get this result, and the CSS work until first error, after that, all styles are ignored:

```
.my-section{
	padding: 10px
	background: #fff;
}
```

In case I did not get right your issue, can you provide more info better with some screens and code lines.
