### ISSUE TITLE
Auto post/tax options for CPT

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2359]
Current framework structure allows  us to add post/tax options on per cpt basis like 

```
framework/theme/options/posts/my_cpt.php
framework/theme/options/taxonomies/my_tax.php
```
is there a way to add custom options for any CPT automatically ?

**Comment by danyj** [comment]
to be more precis with redux your post options are auto visible for CPT like this 

http://prntscr.com/e0ke3j

and we must create files for it.

**Comment by GheorgheP** [comment]
Please check out the [fw_post_options](http://manual.unyson.io/en/latest/hooks/index.html?highlight=fw_post_options#fw-post-options) filter, you get the current options array and the `post_type` as second parameter. In case you want to add for any posts, you can just ignore the `$post_type` parameter:

```
function _filter_fw_options_for_any_post_type( $options ) {
	$my_options = array(/*Your options array goes here*/ );
	return array_merge( $options, $my_options );
}

add_filter( 'fw_post_options', '_filter_fw_filter' );
```


In case for any CPT except standard WordPress post types `post`, `page` and `attachment`, you just need to check by them only:

```
function _filter_fw_options_for_any_post_type( $options, $post_type ) {
	//This excludes some standard WordPress post types
	if ( in_array( $post_type, array( 'post', 'page', 'attachment' ) ) ) {
		return $options;
	}

	$my_options = array(/*Your options array goes here*/ );

	return array_merge( $options, $my_options );
}

add_filter( 'fw_post_options', '_filter_fw_filter', 10, 2 );
```
