### ISSUE TITLE
How to create new post with option from front-end?

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#236]
Hi!
I created option for custom pos type and I want to let user insert post from front-end.
If using wp_insert_post() function, it's only support some default fields.
How can I insert options of this post from front-end?
Thanks!

**Comment by moldcraft** [comment]
Hi,

1. When you make `wp_insert_post()` do you have an array of option values?
2. Do you display [post options](http://static.md/bc2ef3fe4a02308619b967c6cc50f3c1.png) in frontend?

Can you give us a screenshot or screencast of how your frontend looks like (to understand better what are trying to achieve) ?

**Comment by duongancol** [comment]
I have a custom post type name: "Recipe" to let admin uploading or editing with some options, you can see here: http://i.imgur.com/dLWeo80.png
It'll be showed in frontend after publishing for all users.
In my site, I have user with contributor role who only upload new recipe from frontend.
So I need to create a page  in frontend to let them do that. You can see here:http://i.imgur.com/YBBJTmb.png
Please note that, contributor can't logged in backend.

**Comment by moldcraft** [comment]
[This is the code that saves post options](https://github.com/ThemeFuse/Unyson/blob/4408cc30df2ed691d51868301af4459d37ac0413/framework/core/components/backend.php#L569-L582)

The key moment here is the `fw_get_options_values_from_input($options, $POST_values = array())` function.

For your case, it will be something like this:

*Note: This code is not final and not tested, just to give you an idea.*

```php
/**
 * @param int  $post_id
 * @param WP_Post $post
 * @internal
 */
function _action_theme_save_recipe_post($post_id, $post) {
    if (
        $post->post_type 
        !== 
        'your-post-type-name' // fixme
    ) {
        return;
    }
    
    // fixme: maybe some verification, for e.g. check if current user is allowed to save these options
    {
        $allowed = ...;
    
        if (!$allowed) {
            return;
        }
    }
	
	/**
	 * fixme: get option values from POST
	 * 
	 * important: values structure must have the same structure as option types in backend http://static.md/180cfe2fc57017dd4ac6e8b5539f4042.png
	 *            in order for fw_get_options_values_from_input() to work and extract option values correctly
	 */
	$raw_POST_values = FW_Request::POST('some_key...');

	$old_values = (array)fw_get_db_post_option($post_id);
	$new_values = fw_get_options_values_from_input(
		fw()->theme->get_post_options($post->post_type),
		$raw_POST_values
	);
	
	fw_set_db_post_option(
	    $post_id, 
	    null, // this means it will replace all option values, not only a specific option_id
	    array_merge($old_values, $new_values)
    );
}
add_action('save_post', array($this, '_action_theme_save_recipe_post'), 11, 2);
```

**Comment by duongancol** [comment]
Thanks for your suggestion!
It work well now. And it help me know more helper functions.
