### ISSUE TITLE
Translation Extension Issue in Menu.

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#2360]
Hello,

The Translation extension is work in Pages, Posts, Widgets except for Menus.

Here is the Image Below.
![2017-01-27_1257](https://cloud.githubusercontent.com/assets/12461946/22364099/c4830546-e490-11e6-9eb4-7e9a47d1aae6.png)

When i create the menu for specific Language it just refresh the page nothing happened then.
The left side of add menu items still disable.

Kindly provide some solution for this.

Looking Forward.

**Comment by wpthemes786** [comment]
@llemurya 
Hello Can you answer my question

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/2366

**Comment by wpthemes786** [comment]
Thanks
