### ISSUE TITLE
Cannot edit/preview/publish pages

### ISSUE THREAD

**Issue by andreipintica** [ThemeFuse/Unyson#2361]
Hello,

I have updated a page from my website that I want to develop it and I have encountered this error:

Warning: require(): Filename cannot be empty in /home/discove1/public_html/w/wp-content/plugins/unyson/framework/helpers/general.php on line 690

Fatal error: require(): Failed opening required '' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/discove1/public_html/w/wp-content/plugins/unyson/framework/helpers/general.php on line 690

I have downloaded and uploaded the unyson plugin but the problem still persist. Also I have tried to restore a revision post and it does the same thing now. The page is using Visual Builder.

**Comment by moldcraft** [comment]
Hello,

Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by andreiglingeanu** [comment]
Is this still relevant?
