### ISSUE TITLE
Builder doesn't load on edit screen at first

### ISSUE THREAD

**Issue by pcicommunication** [ThemeFuse/Unyson#2362]
I ve upgraded the extensions and now when I go to edit any post/page, the page builder (the layout with it) loads for a sec and goes back the default editor. here is what I got on console;

`Uncaught ReferenceError: optionTypePageBuilder is not defined (editor_integration.js:146)
    at Object.fixOnFirstShowOrHide 
    at Object.<anonymous> (editor_integration.js:249)
    at Object.<anonymous> (load-scripts.php:435)
    at Object.<anonymous> (load-scripts.php:432)
    at _ (load-scripts.php:435)
    at m (load-scripts.php:435)
    at f (load-scripts.php:435)
    at Object.u.trigger (load-scripts.php:435)
    at Object.hideBuilder (editor_integration.js:81)
    at Object.initButtons (editor_integration.js:93)`

Anyone having the same problem?

**Comment by ursulamurua** [comment]
Me too. Starting today.

**Comment by moldcraft** [comment]
Please try with a default WP theme. On my side I don't get any errors.

**Comment by ursulamurua** [comment]
I use this https://themeforest.net/item/candidate-political-wordpress-theme/2909293

**Comment by moldcraft** [comment]
I can't buy the theme just to test this problem.

Have you tried to activate a default WP theme and check if builder works?

**Comment by pcicommunication** [comment]
another update and same thing happened. all the builder layout gone. it flicks for a second goes to default editor. I cant save any layout. Note: I am using the unyson from my theme folder. ()updated the freamwork folder already)

**Comment by danyj** [comment]
@pcicommunication

>  I am using the unyson from my theme folder

which means that you need to update that folder with latest Unyson

I strongly recommend not using it in theme but as a plugin

**Comment by pcicommunication** [comment]
I have updated the framework folder, anything else needs to be updated?

**Comment by danyj** [comment]
> anything else needs to be updated?

all latest extensions ?

**Comment by pcicommunication** [comment]
i did deactivated them and downloaded them again yes

**Comment by moldcraft** [comment]
@pcicommunication Try to disable the framework from your theme and install the official Unyson plugin from admin and check if the error persists.

**Comment by duongancol** [comment]
Hello! I guess that in your theme folder, under framework-customiztion has builder folder. You can try to delete it. I found this error in my theme and just deleted and it worked. This folder probably's added from Unyson theme framework.

**Comment by pcicommunication** [comment]
Hey @duongancol , the folder you are talking about contains all the custom modules I've created, our site is custom build (pcicom.com). I fixed the problem by downloading the latest framework folder, deleting the extentions and installing them again.
