### ISSUE TITLE
Dashboard drafts show Wp_shorcode shortcode

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2363]
See this please http://prntscr.com/e13kq1

**Comment by moldcraft** [comment]
WP Shortcodes are saved as a regular text in post_content.

What do you expect to see there? How other (regular or other plugin) shortcodes do show there?

**Comment by danyj** [comment]
>  How other (regular or other plugin) shortcodes do show there?

not sure but this just looks bad is all I am saying

**Comment by andreiglingeanu** [comment]
@danyj Yeah, thanks for reporting. It really looks very strange, 

I'll try to look up some filters for customizing the look of the draft, maybe we can figure something out.

**Comment by andreiglingeanu** [comment]
@danyj This is totally normal and I agree that it looks pretty strange. There's nothing we can do about that sadly.

![](https://d2ppvlu71ri8gs.cloudfront.net/items/443i3Q440s2J390Q212a/Screen%20Recording%202017-04-25%20at%2003.51%20PM.gif?v=8070aeee)
