### ISSUE TITLE
Warning: session_start(): Cannot send session cache limiter

### ISSUE THREAD

**Issue by GrantNieddu** [ThemeFuse/Unyson#2364]
1.) I installed the Unyson theme.
2.) I received the following errors in the header of the front end:

> Warning: session_start(): open(/home/content/p3pnexwpnas16_data01/38/3807538/tmp/sess_k7cl8s3l9miqr3cahjka760070, O_RDWR) failed: No such file or directory (2) in /home/content/p3pnexwpnas16_data01/38/3807538/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 256
> 
> Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/content/p3pnexwpnas16_data01/38/3807538/html/wp-content/plugins/unyson/framework/includes/hooks.php:256) in /home/content/p3pnexwpnas16_data01/38/3807538/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 256

3.) I received the following errors in the footer:

> Warning: Unknown: open(/home/content/p3pnexwpnas16_data01/38/3807538/tmp/sess_k7cl8s3l9miqr3cahjka760070, O_RDWR) failed: No such file or directory (2) in Unknown on line 0
> 
> Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on line 0

4.) I received the following errors in the back end, too.

> Warning: session_start(): open(/home/content/p3pnexwpnas16_data01/38/3807538/tmp/sess_k7cl8s3l9miqr3cahjka760070, O_RDWR) failed: No such file or directory (2) in /home/content/p3pnexwpnas16_data01/38/3807538/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 228
> 
> Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/content/p3pnexwpnas16_data01/38/3807538/html/wp-content/plugins/unyson/framework/includes/hooks.php:228) in /home/content/p3pnexwpnas16_data01/38/3807538/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 228

5.) I've read through the other tickets and cannot make heads or tails of it. I am not a programmer so it doesn't make all that much sense to me.

Is there any simple, direct way to resolve these issues?

**Comment by Ataurr** [comment]
It looks like some files missing. 
If you upload via FTP then try to reupload the file again.

**Comment by moldcraft** [comment]
https://www.google.com/search?q=php+Warning%3A+session_start()%3A+open()

**Comment by moldcraft** [comment]
There is an issue with your server.
