### ISSUE TITLE
Multi option type keep tabs structure

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2367]
Multi option type should be used to group options under one array and that works fine , issue is if I use this as a top array for tabs/subtabs the tabs design changes 

without multi 

![screenshot_16](https://cloud.githubusercontent.com/assets/2340172/22396418/7ba56584-e559-11e6-8921-cfadfcdcb07d.png)

with multi

![screenshot_17](https://cloud.githubusercontent.com/assets/2340172/22396419/81ac74f4-e559-11e6-884e-b068228d51b0.png)

how can I group set of options in to an array and keep same design structure?

**Comment by moldcraft** [comment]
Hello

Can you provide the test options array?

**Comment by danyj** [comment]
sorry did not see reply 
here , place this inside theme settings , side tab 



```
'this_is_main_tab' => array(
	'title' => __('Main tab', 'creatus') ,
	'type' => 'tab',
	'options' => array(
		'sometab' => array(
			'title' => __('I am tab', 'fw') ,
			'type' => 'tab',
			'options' => array(
				'subtabopt' => array(
					'type' => 'text',
					'label' => __('Subtab opt', 'fw') ,
					'desc' => __('Icon title', 'fw') ,
				)
			) ,
		) ,
		'sometab2' => array(
			'title' => __('I am tab2', 'fw') ,
			'type' => 'tab',
			'options' => array(
				'subtabop2t' => array(
					'type' => 'text',
					'label' => __('Subtab opt2', 'fw') ,
					'desc' => __('Icon title', 'fw') ,
				)
			) ,
		) ,
		'tabsinmulti' => array(
			'type' => 'multi',
			'attr' => array(
				'class' => 'fw-option-type-multi-show-borders',
			) ,
			'label' => false,
			'inner-options' => array(
				'sometab' => array(
					'title' => __('I am tab', 'fw') ,
					'type' => 'tab',
					'options' => array(
						'subtabopt' => array(
							'type' => 'text',
							'label' => __('Subtab opt', 'fw') ,
							'desc' => __('Icon title', 'fw') ,
						)
					) ,
				) ,
				'sometab2' => array(
					'title' => __('I am tab2', 'fw') ,
					'type' => 'tab',
					'options' => array(
						'subtabop2t' => array(
							'type' => 'text',
							'label' => __('Subtab opt2', 'fw') ,
							'desc' => __('Icon title', 'fw') ,
						)
					) ,
				) ,
			)
		) ,
	) ,
) ,
```


my output 

![screenshot_19](https://cloud.githubusercontent.com/assets/2340172/22518044/7c0e13d6-e8ab-11e6-8f13-a6bc8fcead11.png)

**Comment by moldcraft** [comment]
At the moment it's not possible. This comes [from css](https://github.com/ThemeFuse/Unyson/blob/1f343863304ca5a3f178403cad44419d4c10efef/framework/static/css/backend-options.css#L138-L202) for immediate children tabs.
I will add a special class that you will add to make the tabs look as second level tabs.
