### ISSUE TITLE
Ical export

### ISSUE THREAD

**Issue by bert677** [ThemeFuse/Unyson#2371]
Hi Guys,

When I click the iCal export button i get the following error when trying to add to calendar app.

"Calendar can’t read this calendar file. No events have been added to your calendar"

I have changed the extension from .ics to .vcs and it will then work... or if i edit the .ics file and change it from version 1.0 to version 2.0 then all is good.
but I cant expect the average use to know how to do this...
How do i get it to export a .vcs file instead of .ics or change it from version 1.0 to version 2.0 without editing the actual .ics file.

Thanks
Barrett

**Comment by moldcraft** [comment]
Hello,

There is no such think as "iCal export button" in Unyson. I think you reported the problem to the wrong project.

**Comment by bert677** [comment]
Hi,

So who would I contact for the Events extension?
see attachment.

**Comment by danyj** [comment]
@moldcraft  yes there is and it was working before but not anymore 
https://github.com/ThemeFuse/Unyson-Events-Extension/blob/7a5e9883f2180fb68f81e1ebcfa7fbc6ad95f60c/views/content.php#L17

**Comment by bert677** [comment]
@danyj thanks man! 
@moldcraft, so how would I resolve this?

**Comment by moldcraft** [comment]
@bert677 Are you a developer? Can you inspect this problem and come up with a solution?

**Comment by bert677** [comment]
No, I’m not a developer… hence why I am asking for help.

**Comment by danyj** [comment]
@moldcraft ,  sorry I am busy with something else right now , this is on my to do list. If I finish current task fast I will take a look

**Comment by moldcraft** [comment]
As I understand iCal is only for Mac which I don't have.

**Comment by player0k** [comment]
> As I understand iCal is only for Mac which I don't have.

Yes iCal format v.1.0 for old Mac OS systems and some old versions of Microsoft Outlook calendar 


I think, need to add some filter for this  [switch case](https://github.com/ThemeFuse/Unyson-Events-Extension/blob/7a5e9883f2180fb68f81e1ebcfa7fbc6ad95f60c/class-fw-extension-events.php#L517-L525
)

**Comment by bert677** [comment]
Hi,

Sorry for the good questions… is this a fix?

**Comment by player0k** [comment]
> is this a fix?

No this is not a fix, this is problem place. If you need a hot fix just copy this extension in theme-root-dir/framework-customizations/extensions/  rename the main class extension and modify code whatever you like.
