### ISSUE TITLE
Run jQuery ajax request after theme settings data is submited

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson#2372]
Hey, guys!

Is there a way to run an ajax request after I submit the theme settings into the database? 

I run the ajax request on 'Save Changes', but it runs before the data is stored.

Any ideas how to fix this ?

**Comment by mowshon** [comment]
You can use action `fw_settings_form_saved`

```php
function do_something_after_data_is_stored() {
        $value = fw_get_db_settings_option( 'link_color' );
        // code...
}

add_action( 'fw_settings_form_saved', 'do_something_after_data_is_stored' );
```

Yes, this is not ajax request but will work with new stored data from Theme Settings.

**Comment by dmbostan** [comment]
@mowshon strange issue:
`fw_settings_form_saved` is not working for me, but `fw:settings-form:id:saved` does.

I was wondering about jQuery manipulation, since i would like to notify user about errors and stuff.
However, i think it will do for now.

Thank you!

**Comment by dmbostan** [comment]
Even if I use the hook, it would return the old values and the ones freshly saved in the database.
