### ISSUE TITLE
The problem Customizer due to class .fw-pull-left

### ISSUE THREAD

**Issue by Bogdan808** [ThemeFuse/Unyson#2373]
Hi! We have an problem when using the optins. Need to kill of this class. This can be functionally? I don't want to cancge core code.

Attach:
http://clip2net.com/s/3H5iipa

**Comment by moldcraft** [comment]
Hello,

I added this code in `customizer.php`

```php
$options = array(
	'z' => array('type' => 'slider'),
);
```

and it works fine

![staticshot_06-02-2017_16-09-39](https://cloud.githubusercontent.com/assets/1475489/22650174/ade76356-ec86-11e6-96b8-270036efda96.png)

**Comment by GheorgheP** [comment]
Can you confirm that the issue is still present on your side?

**Comment by meta4creations** [comment]
I have this issue as well in the customizer. Text fields, multi-select, and probably others have a "fw-pull-left" class added to the "fw-inner" container which throws off the display of these options.

<img width="323" alt="screen shot 2017-07-12 at 10 47 34 am" src="https://user-images.githubusercontent.com/1682207/28126608-91b3146c-66ef-11e7-9328-3a36874849bc.png">
<img width="393" alt="screen shot 2017-07-12 at 10 48 09 am" src="https://user-images.githubusercontent.com/1682207/28126623-a093fc1c-66ef-11e7-8484-b28046b325a5.png">

**Comment by gigit95** [comment]
The same problem here. Did you solve it?

![sliderproblem](https://user-images.githubusercontent.com/11440530/29250364-a6532f2c-8041-11e7-8805-0377a795e70d.jpg)

**Comment by gigit95** [comment]
I've changed a little bit "backend-option-design-customizer.php" and it seems to be fixed. A simple if-else...
![123](https://user-images.githubusercontent.com/11440530/29254991-79fcf5be-809d-11e7-8cf1-b1237608b003.JPG)
![gb](https://user-images.githubusercontent.com/11440530/29255012-c108a688-809d-11e7-8385-447341383071.JPG)



	<?php if ($option['type'] == 'slider'): //If it's a slider dont put in 'fw-pull-left'?>
		<div class="<?php echo esc_attr($classes['input']) ?>">
			<div class="fw-inner fw-clearfix">
				<div class="fw-inner-option">
					<?php echo fw()->backend->option_type($option['type'])->render($id, $option, $data); ?>
				</div>
			</div>
		</div>
	<?php else: // else leave it as it was before?>		
		<div class="<?php echo esc_attr($classes['input']) ?>">
			<div class="fw-inner fw-pull-<?php echo is_rtl() ? 'right' : 'left'; ?> fw-clearfix">
				<div class="fw-inner-option">
					<?php echo fw()->backend->option_type($option['type'])->render($id, $option, $data) ?>
				</div>
			</div>
		</div>
	<?php endif;?>
