### ISSUE TITLE
Unable to save value for the options of comment.

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#2374]
I made some options for the comments of the site:
framework-customizations/theme/options/posts/comment.php
When I go edit a comment, change the options then click update, the site returns to the list of comments table as normal, but the options are not saved.

**Comment by moldcraft** [comment]
Hello,
It is a mistake that the options from `posts/comment.php` are loaded in comment edit page, [I disabled that](https://github.com/ThemeFuse/Unyson/commit/48881dc9712b064ffe81067698aab9a74bf103a6).

**Comment by TrangDinhVan** [comment]
Okay, so we are expecting" fw options" for users and comments here!
