### ISSUE TITLE
custom css?

### ISSUE THREAD

**Issue by csomiccarletti** [ThemeFuse/Unyson#2377]
I'm trying to find out how I need to format the custom css fields for sections and layout blocks. I've tried adding both the selector and declarations, and I've also tried just adding the declarations, but neither seem to work.

**Comment by moldcraft** [comment]
Hello,

Have you tried [this solution](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head)?
