### ISSUE TITLE
Https issue in youtube video background thumbnail

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2378]
When youtube video load one thumbnail also load for fallback. 

Fallback thumbnail load with http://. and found wallpaer.js here 
![thumb](https://puu.sh/tNGIf/44be925ee5.png)

**Comment by GheorgheP** [comment]
Here's a pull request to fix this: https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/pull/72
