### ISSUE TITLE
How can I add extra class to first mega-menu-col UL ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#238]
I am trying everything but it is just to complicated to add an additional class to the 
first mega-menu-col ul 
http://screencast.com/t/1H3mD8lVIT

I need that class to be sub-menu group-holder, not all sub-menu , but only first one who's parent is mega-menu-col 

   wp_nav_menu_args  
does not work since the megamenu is overriding everything, 
I cant get my head around extending the FW_Extension_Megamenu class,
I copied it to themes\creatus\framework-customizations\extensions\megamenu, can anyone just point me in the right direction please.

**Comment by duongancol** [comment]
I also want to customize the menu walker of mega menu, but I can't find the way to do it

**Comment by duongancol** [comment]
So I did copy the class-fw-theme-menu-walker.php in megamenu folder to new location, renamed it and call a new 'walker' in wp_nav_menu function, for example: 

wp_nav_menu(array('walker' => new fw-custom-menu()))

I think it's the best way now.

**Comment by danyj** [comment]
I did that as advised here 
https://github.com/ThemeFuse/Unyson/issues/79#issuecomment-73740987

my problem is that I need additional loop here 

https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/4a1516f86cf4de7e9be8b5b12836f42756b07a7f/includes/class-fw-theme-menu-walker.php#L154

or here 
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/4a1516f86cf4de7e9be8b5b12836f42756b07a7f/class-fw-extension-megamenu.php#L185

but the separation of those 2 is beyond me. I do not see why was the menu class creation and markup separated in 2 different files.

**Comment by moldcraft** [comment]
@danyj Please install manually [v1.0.4](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/releases/tag/v1.0.4) to `plugins/unyson/framework/extensions/megamenu` and try [this filter](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.0.4/includes/class-fw-ext-mega-menu-walker.php#L181-L188)

Create `{theme}/framework-customizations/extensions/megamenu/hooks.php`

```php
<?php if (!defined('FW')) die('Forbidden');

function _filter_theme_mega_menu_start_lvl_classes($classes, $data) {
	if ($data['depth'] == 0) {
		$classes['group-holder'] = true;
	}

	return $classes;
}
add_filter('fw_ext_mega_menu_start_lvl_classes', '_filter_theme_mega_menu_start_lvl_classes', 10, 2);
```

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/23
