### ISSUE TITLE
Discussion: "Save" button text inside popup is misleading 

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2381]
When inside customizer , clicking on "save" button in the popup is somewhat okay because it reloads the site to reflect the changes.
But on admin pages it's misleading because clicking on "save" button just closes the popup, and the user needs to click on global "update" button in order for the changes to be saved.
Maybe better text would be "done" or an option for the text to be arbitrary changed.

**Comment by moldcraft** [comment]
Thank you!

**Comment by moldcraft** [comment]
Hm, recently I added the Save All button https://vid.me/9uuV
Does "Done All" sound ok?

**Comment by ivandotv** [comment]
I haven't seen this before, probably because I'm not using page builder.
I was specifically referring to popup windows. So when you close the popup by clicking on "save" button, you think the options are saved in the database, but in fact they are not.
And that is misleading.

**Comment by danyj** [comment]
> Hm, recently I added the Save All button
anything special that needs to be done for it to be visible  or is just comes when second level popup shows up ?

**Comment by moldcraft** [comment]
You have to have Unyson 2.6.14 then it just comes when second level popup shows up only in Page Builder.

**Comment by danyj** [comment]
ok , one more , is save all saving all popups only , or all popups and page?

**Comment by moldcraft** [comment]
all popups only

**Comment by danyj** [comment]
ok , than I would say that " Save all popups" instead save all .

**Comment by moldcraft** [comment]
That's a good point. I will discuss that will our UX designer

**Comment by ivandotv** [comment]
What about the original issue?

**Comment by moldcraft** [comment]
Our designer is off for a few days, so this issue will be delayed.

**Comment by moldcraft** [comment]
@ivandotv I will add a filter on that text so you will be able to change it from theme

**Comment by ivandotv** [comment]
awesome. :1st_place_medal:

**Comment by moldcraft** [comment]
@ivandotv https://github.com/ThemeFuse/Unyson/commit/a86da9a59adac3ce6b564872719cd8ebaba32e47#diff-8e628e2362d97faf414c064ad2478754R364

**Comment by danyj** [comment]
thnx but why isn't save all in the list?

**Comment by moldcraft** [comment]
Save` All` is in PageBuilder

1. https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/f1c9cc6e6a4e9ad8bac82605a96e9fe2c7cad476/includes/page-builder/class-fw-option-type-page-builder.php#L154
2. https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/f1c9cc6e6a4e9ad8bac82605a96e9fe2c7cad476/includes/page-builder/static/js/modal-save-all.js#L60

**Comment by Ataurr** [comment]
I would Prefer a button "Save All & Publish" Or only "Publish" (Which will save all the popup and publish the page)
Or something like this #2306

**Comment by andreiglingeanu** [comment]
And for the ones who want to disable that in their themes, quick tip:

```php
add_filter('fw:ext:page-builder:modal-save-all', '__return_false');
```
