### ISSUE TITLE
Shortcode Google font print issue with theme option google fonts

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#2384]
I Have tried to combine shortcode google font with theme option google font in single google font link. 
But now problem is when i saved only Special heading, last font style (last col-md-6) are saved in custom update option. and first special heading (col-md-6) style and theme option font style not working. 
![Fontss](https://puu.sh/tS0pX/873ea5f851.png)

 * Here is Google Fonts complete 3 functions
```
if ( !function_exists( '_action_bizcraft_process_google_fonts' ) ) {

	function _action_bizcraft_process_google_fonts( $fonts ) {

		$include_from_google = array();
		$google_fonts		 = fw_get_google_fonts();
		$body_font			 = fw_get_db_settings_option( 'body_font' );

		if ( isset( $google_fonts[ $body_font[ 'family' ] ] ) ) {
			$include_from_google[ $body_font[ 'family' ] ] = $google_fonts[ $body_font[ 'family' ] ];
		$google_fonts_links = bizcraft_get_remote_fonts( $include_from_google );
		// set a option in db for save google fonts link
		update_option( 'fw_theme_google_fonts_link', $google_fonts_links );
	}
	add_action( 'fw_settings_form_saved', '_action_bizcraft_process_google_fonts', 999, 2 );
}
```

```
if ( !function_exists( 'bizcraft_get_remote_fonts' ) ) :
	function bizcraft_get_remote_fonts( $include_from_google ) {
		if ( !sizeof( $include_from_google ) ) {
			return '';
		}
		$family = "";
		foreach ( $include_from_google as $font => $styles ) {
			$family .= str_replace( ' ', '+', $font ) . ':' . implode( ',', $styles[ 'variants' ] ) . '|';
		}
		$family = substr( $family, 0, - 1 );

		return $family;
	}

endif;
```

```
	function _action_bizcraft_print_google_fonts_link() {
		/**
		 * enque google fonts link
		 */
		$font_url			 = '';
		$google_fonts_family = get_option( 'fw_theme_google_fonts_link', '' );
		if ( $google_fonts_family != '' && defined( 'FW' ) ) {
			$family = $google_fonts_family;
		} 

		
		if ( 'off' !== esc_html_x( 'on', 'Google font: on or off', 'bizcraft' ) ) {
			$font_url = add_query_arg( 'family', $family . '&subset=latin,latin-ext', "https://fonts.googleapis.com/css" );
		}

		wp_enqueue_style( 'bizcraft-fonts', $font_url, array(), BC_VERSION );
	}

	add_action( 'wp_enqueue_scripts', '_action_bizcraft_print_google_fonts_link' );
```

//end google font load

### Special Heading Shortcode enqueue fonts

```
function bizcraft_action_shortcode_special_heading_enqueue_dynamic_css( $data ) {
		$shortcode				 = 'special_heading';
		$atts					 = shortcode_parse_atts( $data[ 'atts_string' ] );
		$atts					 = fw_ext_shortcodes_decode_attr( $atts, $shortcode, $data[ 'post' ]->ID );
		$custom_heading_styles	 = '';

		$xsid = '.xs-heading-' . $atts[ 'xs_id' ];
			
			if ( isset( $atts[ 'heading_typography' ][ 'family' ] ) && !empty( $atts[ 'heading_typography' ][ 'family' ] ) ) {
				$custom_heading_styles .= bizcraft_shortcode_advanced_font_styles( $xsid . ' .fw-special-title{'.$atts[ 'heading_typography' ] ).'}';
			}
	
		if ( empty( $custom_heading_styles) ) {
			return;
		}

		wp_add_inline_style(
		'bizcraft-style', $custom_column_styles
		);
	}
	add_action(
	'fw_ext_shortcodes_enqueue_static:special_heading', 'bizcraft_action_shortcode_special_heading_enqueue_dynamic_css'
);
```
### Shortcode font load with "fw_theme_google_fonts_link" option and this function process shortcode fonts

```
function bizcraft_shortcode_advanced_font_styles( $style ) {
		global $post, $google_fonts_links;
		if ( isset( $style[ 'family' ] ) && $style[ 'family' ] != '' ) {

			$heading_title_family	 = $style[ 'family' ];
			$heading_title_style	 = $style[ 'style' ];

			if ( $heading_title_style === 'regular' ) {
				$heading_title_style = '400';
			}
			if ( $heading_title_style == 'italic' ) {
				$heading_title_style = '400italic';
			}
			$heading_title_font_style	 = ( strpos( $heading_title_style, 'italic' ) ) ? 'font-style: italic;' : '';
			$heading_title_font_weight	 = 'font-weight: ' . intval( $heading_title_style ) . ';';
			$heading					 = 'font-family: '.$heading_title_family.';'. $heading_title_font_style.' '. $heading_title_font_weight;

			$include_from_google = array();
			$google_fonts		 = fw_get_google_fonts();
			if ( isset( $google_fonts[ $style[ 'family' ] ] ) ) {
				$include_from_google[ $style[ 'family' ] ] = $google_fonts[ $style[ 'family' ] ];
			}

			$google_fonts_links = bizcraft_get_remote_fonts( $include_from_google );

			update_option( 'fw_theme_google_fonts_link', $google_fonts_links );
		}

		return $heading_style;
	}
```

If i deactivated **bizcraft_shortcode_advanced_font_styles** function or  comment `update_option( 'fw_theme_google_fonts_link', $google_fonts_links );` line and then save theme option again.  after Body font change with google font. 
![bodyfont](https://puu.sh/tS0oy/26a2edcad8.png)

This is confusing me lot. Cant findout any solution from last issues

@GheorgheP @moldcraft Please help me to fix this issue.

**Comment by GheorgheP** [comment]
I think the problem is in `bizcraft_shortcode_advanced_font_styles` as there you update the fonts `update_option( 'fw_theme_google_fonts_link', $google_fonts_links );` by this overwriting the settings fonts, but you do not get the current settings fonts that are set in theme settings to merge theme.

I would really recommend you to not use global in your code as the global `$google_fonts_links` may not be defined and it comes `null`.

**Comment by xperter** [comment]
I have tried Lot of ways last two days. 

How we should  merge theme setting fonts with Shortcodes fonts right way ?

I am little bit confused  with this. :(

**Comment by GheorgheP** [comment]
How do you get the current settings fonts?
What function do you use for this?
Also, did you check if the `update_option` executes successfully?
I would recommend you to print the `$google_fonts_links` before updating and then print  the `get_option( 'fw_theme_google_fonts_link')` after updating to see what was really saved.

I'm talking about the `bizcraft_shortcode_advanced_font_styles` function now.

**Comment by xperter** [comment]
I did like this way.

### Theme settings value saved in "`fw_theme_google_fonts_link`" option

### Shortcode fonts save value in "`fw_theme_google_fonts_shortcode`" option

```
function bizcraft_shortcode_advanced_font_styles( $style ) {
	global $post, $google_fonts_links;
	if ( isset( $style[ 'family' ] ) && $style[ 'family' ] != '' ) {

		$heading_title_family	 = $style[ 'family' ];
		$heading_title_style	 = $style[ 'style' ];

		if ( $heading_title_style === 'regular' ) {
			$heading_title_style = '400';
		}
		if ( $heading_title_style == 'italic' ) {
			$heading_title_style = '400italic';
		}
		$heading_title_font_style	 = ( strpos( $heading_title_style, 'italic' ) ) ? 'font-style: italic;' : '';
		$heading_title_font_weight	 = 'font-weight: ' . intval( $heading_title_style ) . ';';
		$heading					 = 'font-family: ' . $heading_title_family . ';' . $heading_title_font_style . ' ' . $heading_title_font_weight;

		$include_from_google = array();
		$google_fonts		 = fw_get_google_fonts();
		if ( isset( $google_fonts[ $style[ 'family' ] ] ) ) {
			$include_from_google[ $style[ 'family' ] ] = $google_fonts[ $style[ 'family' ] ];
		}
//Shortcodes old saved fonts
		$sc_old_fonts	 = get_option( 'fw_theme_google_fonts_shortcode' );
Merge old fonts with new change fonts
		$fonts			 = bizcraft_array_merge( $include_from_google, $sc_old_fonts );
		update_option( 'fw_theme_google_fonts_shortcode', $fonts );
	}
	return $heading_style;
}
```

And print the google font like this

```
function _action_bizcraft_print_google_fonts_link() {
//Shortcodes Fonts
	$shortcodes_fonts	 = get_option( 'fw_theme_google_fonts_shortcode' );
//Settings fonts
	$settings_fonts		 = get_option( 'fw_theme_google_fonts_link' );

// Merge Settings and Shortcodes fonts
	$fonts = bizcraft_array_merge( $settings_fonts, $shortcodes_fonts );
	

	$google_fonts_family = bizcraft_get_remote_fonts( $fonts );

	/**
	 * enque google fonts link
	 */
	$font_url = '';
	if ( $google_fonts_family != '' && defined( 'FW' ) ) {
		$family = $google_fonts_family;
	} else {
		$family = "Lato:400,300,300italic,400italic,500,700,700italic";
	}

	if ( 'off' !== esc_html_x( 'on', 'Google font: on or off', 'bizcraft' ) ) {
		$font_url = add_query_arg( 'family', $family . '&subset=latin,latin-ext', "https://fonts.googleapis.com/css" );
	}
	wp_enqueue_style( 'bizcraft-fonts', $font_url, array(), ERSION );
}
add_action( 'wp_enqueue_scripts', '_action_bizcraft_print_google_fonts_link', 99 );
```

But Now problem is if i change the fonts from shortcodes. old font still remain the same. as i have merge the old font with new font in `bizcraft_shortcode_advanced_font_styles`. 

Is there Any way i can remove the old shortcodes fonts which already change with new font ?

If I am not merge the old shortcodes fonts with new shortcodes fonts.  new shortcodes font overwrite old  shortcodes fonts. 

Its really confusing me. :(

**Comment by moldcraft** [comment]
@xperter I am working on helper class that will ease the enqueue process of google fonts.

**Comment by xperter** [comment]
@moldcraft Thanks very much.  I am waiting.

**Comment by moldcraft** [comment]
_I assume you use [Theme Includes](https://github.com/ThemeFuse/Theme-Includes)_

1. Add this code in `{theme}/inc/hooks.php`

	```php
	spl_autoload_register('_theme_includes_autoload');
	function _theme_includes_autoload($class) {
		switch ($class) {
			case 'Unyson_Google_Fonts':
				require_once dirname(__FILE__) .'/includes/unyson-google-fonts/class-unyson-google-fonts.php';
				break;
		}
	}
	```

2. Create `{theme}/inc/includes/unyson-google-fonts/class-unyson-google-fonts.php`

	```php
	<?php if ( ! defined( 'FW' ) ) { die( 'Forbidden' ); }
	
	class Unyson_Google_Fonts {
		static private $data = array(
			'subset' => array(),
			'family' => array(),
		);
	
		public static function add_typography_v2($value) {
			if (in_array($value['google_font'], array(true, 'true'), true)) {
				self::$data['family'][ $value['family'] ]['variants'][ (string)$value['variation'] ] = true;
				self::$data['subset'][ $value['subset'] ] = true;
			}
		}
	
		public static function clear() {
			self::$data = array();
		}
	
		public static function generate_url() {
			/**
			 * Example:
			 *
			 * <link href="
			 * https://fonts.googleapis.com/css?
			 * family={Family}|{Family}:{variant},{variant}
			 * &amp;
			 * subset=cyrillic-ext,greek,vietnamese
			 * " rel="stylesheet">
			 */
	
			if (empty(self::$data['family'])) {
				return false;
			}
	
			$query = array(
				'family' => array(),
				'subset' => implode(',', array_keys(self::$data['subset'])),
			);
	
			foreach (self::$data['family'] as $family => $family_data) {
				$query['family'][] = $family .':'. implode(',', array_keys($family_data['variants']));
			}
			$query['family'] = implode('|', $query['family']);
	
			return 'https://fonts.googleapis.com/css?'. build_query($query);
		}
	
		public static function output_url() {
			if ($url = self::generate_url()):
				?><link href="<?php echo esc_attr($url) ?>" rel="stylesheet"><?php
			endif;
		}
	}
	
	add_action('wp_print_styles', array('Unyson_Google_Fonts', 'output_url'), 9999);
	```

3. Use it anywhere you want before `'wp_print_styles'` action and it will add automatically in `<head>` the google font style.

	```php
	add_action(
		'fw_ext_shortcodes_enqueue_static:button',
		'_theme_action_shortcode_button_enqueue_dynamic_css'
	);
	function _theme_action_shortcode_button_enqueue_dynamic_css() {
		Unyson_Google_Fonts::add_typography_v2($atts['YOUR_TYPOGRAPHY-V2_OPTION_ID']);
	}
	```

**Comment by danyj** [comment]
@moldcraft  

> Since WordPress 3.3 wp_print_styles should not be used to enqueue styles or scripts. 

https://codex.wordpress.org/Plugin_API/Action_Reference/wp_print_styles

**Comment by moldcraft** [comment]
@danyj [Updated](https://github.com/ThemeFuse/Unyson/issues/2384#issuecomment-278637077) with `'wp_enqueue_scripts'` Thanks

**Comment by moldcraft** [comment]
@xperter Let me know if it works as expected.

**Comment by danyj** [comment]
@moldcraft  

I did this long time ago and seems like you did same process in this class ,  accumulate all google fonts and print the link ,  one thing you might want to check is that the names are unique, 

example 

2 different buttons , select same font name , with current link you endup with 

    family=Open Sans|Open Sans 

what I did is `array_unique`


    $all_google_fonts = implode( '|', array_unique( ThzDochead::getDocument()->dochead['googlefont'] ) );

**Comment by moldcraft** [comment]
@danyj I store everything as array keys

```php
self::$data['family'][ $value['family'] ] = ...
```

instead of 

```php
self::$data['family'][] = $value['family']
```

**Comment by danyj** [comment]
you sure ? http://prntscr.com/e6ixk2

**Comment by moldcraft** [comment]
Yes

**Comment by danyj** [comment]
yes sorry , way up there. just looking up

**Comment by xperter** [comment]
@moldcraft  Its work with shortcode fonts but theme settings fonts not working.

**Comment by moldcraft** [comment]
> but theme settings fonts not working

How are you adding theme settings fonts? Show your code and where you place it.

**Comment by danyj** [comment]
must be at 90  for theme dynamic css,  I had issue with that before until @moldcraft  helped 


    add_action('wp_enqueue_scripts', '_thz_action_enqueue_dynamic_scripts',90);


browse these https://github.com/ThemeFuse/Unyson/issues/750

**Comment by xperter** [comment]
Everything works great. 
Should we encode the  "|" (pipe) ?
`Baloo Tamma:regular|Astloch:regular`

**Comment by danyj** [comment]
> Should we encode the "|" (pipe) ?

yes use  urlencode

**Comment by danyj** [comment]
and I would use   

     //fonts.googleapis.com

instead 


    https//fonts.googleapis.com

**Comment by danyj** [comment]
this i what I use if you nee a ref 

    $google_font_url  = add_query_arg( 'family', urlencode( $all_google_fonts ), "//fonts.googleapis.com/css" );

**Comment by moldcraft** [comment]
> Should we encode the "|" (pipe) ?

Google Fonts sites provides the url with `|`. So I think you shouldn't.

Also the above code generates the url with `build_query()` then [it is escapend/encoded by `wp_enqueue_style()`](https://github.com/WordPress/WordPress/blob/d33301821b26b26fc730d9b3de171ce62a77e5ba/wp-includes/class.wp-styles.php#L355)

**Comment by danyj** [comment]
you should , it will not pass html validation with |

**Comment by danyj** [comment]
http://stackoverflow.com/a/22469221/594423

**Comment by Ataurr** [comment]
@moldcraft  :heart: you, buddy  :umbrella:

Thanks, @danyj  :gift_heart:

**Comment by xperter** [comment]
Thanks All 🍺

**Comment by stivoox** [comment]
I Have tried to make this works with the customizer but won't work.
I have replaced this 
`add_action(
	'fw_ext_shortcodes_enqueue_static:button',
	'_theme_action_shortcode_button_enqueue_dynamic_css'
);
with this 
`add_action(
	'customize_save_after',
	'_theme_action_shortcode_button_enqueue_dynamic_css'
);`

Any Idea ??
`
