### ISSUE TITLE
Contact Forms 7 Upload Field

### ISSUE THREAD

**Issue by MCHLHF** [ThemeFuse/Unyson#2386]
I bought LOOK Themeforest theme which has Unyson and Contact Forms 7 integrated. When inserting a form using the Unyson builder there are 9 form fields to choose from. The form field that I am missing is for uploading a file.

It is a modelling site and it is evident that when a new model applies it needs to send it's picture, which obviously needs to be uploaded.

Kindly your assistance in how to add a upload form field to Unyson / Contact Form 7.

**Comment by moldcraft** [comment]
Hello,

This is on our TODO list but I can't give any eta https://github.com/ThemeFuse/Unyson-Forms-Extension/issues/22

**Comment by MCHLHF** [comment]
I tried to contact CF7, but no response so far. 

Is there any other way for me to realise this? It is the highest priority and the core of the website. Without it it is useless.

**Comment by moldcraft** [comment]
It's not easy, that's why I delayed this task/feature (I am not sure yet how to do it properly).

I see that [CF7 has upload field](https://www.google.com/search?q=contact+form+7+upload)

**Comment by MCHLHF** [comment]
CF7 does have upload field, I know, I found this on the internet as well, but I have no idea how to do this since my theme is build on Unyson. So the forms that I have built in/with Unyson are not visible under [Contact Forms] and therefore can also not be edited. Building the upload button is appearantly not the problem, integrating with Unyson is.

**Comment by moldcraft** [comment]
@MCHLHF Ask your theme author if he can create a Contact Form 7 shortcode for Page Builder. A lot of themes have it and it's easy to create.

**Comment by duongancol** [comment]
@MCHLHF I think the problem come from the theme style. I'm using Unyson with CT7 without any problems with Upload field.

**Comment by baturkacamak** [comment]
any news for the upload field?

**Comment by Datagirlcmr** [comment]
I have the same problem, and it is for a modeling website too. Please how did you solve this?
