### ISSUE TITLE
Fatal error: Call to undefined function (Themeforest Wordpress Item) Unyson Framework 

### ISSUE THREAD

**Issue by NiloySarker** [ThemeFuse/Unyson#2387]
Hi,
I got a soft-reject for this issue: http://envato.d.pr/5wYq/36MZbsGe2
actually, it's come because I use Unyson framework1 and unyson plugin is not active yet.
I told the reviewer you should active this plugin because it's required some functions which come from Unyson plugin.
then I re-submit the theme again and they said "Themes are required to function without the use of outside plugins. Please resolve. "
Now my question is how should I fix this issue. even I have downloaded a theme from TF.That theme also used Unyson framework and that theme still has this issue and the issue will be gone when I active the plugin.
I also try to add this plugin into my theme folder by following this article http://manual.unyson.io/en/latest/index.html#content (Install anywhere)
but then it will raise many errors on theme check http://prnt.sc/e5rutt2
Please help me if anyone know the solution.
Thanks,
Niloy

**Comment by GheorgheP** [comment]
It's very simple.

You don't have to use the Unyson or Unyson's extensions functions directly in theme templates, you can define a intermediate function:

```php
function my_theme_foo() {
	return defined( 'FW' ) ? fw_get_db_settings_option( 'my-option' ) : 'SOME DEFAULT VALUE';
}
```

I usually make a function `is_fw()` to use instead of `defined( 'FW' )`:

```php
function is_fw() {
	return defined( 'FW' );
}

function my_theme_foo() {
	return is_fw() ? fw_get_db_settings_option( 'my-option' ) : 'SOME DEFAULT VALUE';
}
```

**Comment by NiloySarker** [comment]
Thanks
