### ISSUE TITLE
No more shortcodes in Page Builder?

### ISSUE THREAD

**Issue by icypixels** [ThemeFuse/Unyson#239]
WP Version 4.1
Unyson 2.1.22

While activating the Page Builder module on a blank installation of WordPress with the default theme active, the only shortcode available in the Page Builder is the Contact Form. Everything else is gone. The sections, the columns ... well, everything :)

Screenshot: https://www.dropbox.com/s/at18s2l0kly87di/Screenshot%202015-02-11%2021.38.00.png?dl=0

**Comment by GheorgheP** [comment]
Hi,

I tested my installation and with new installations and I cannot reproduce this problem.

You can send your ftp details on `unyson[at]email.com`, and I will take a look on the problem.

**Comment by icypixels** [comment]
Hi Gheorghe,

Just tested on more configurations. It seems it has something to do with my local server environment. Sorry to bother you.

Paul
