### ISSUE TITLE
Importing content

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#2392]
Hi guys,

I have a client with many pages which follow a specific structure which I can recreate with the page builder and shortcodes. Is there a way I can create a CSV file and import the data into pages and shortcodes? I want to avoid the standard WordPress importer if possible.

Thanks

**Comment by danyj** [comment]
there is backup and demo content extension that you can use 
http://manual.unyson.io/en/latest/extension/backups/index.html#content

**Comment by klvmedia** [comment]
Hi,

Yes the backup module works great for moving sites or demo content, what I'd like to do is import a csv that fills the data into specific shortcodes on a page. If that makes sense.

Thanks

**Comment by moldcraft** [comment]
Hello,

There is no support for CSV. You can only create [predefined templates](https://github.com/ThemeFuse/Unyson/issues/1960#issuecomment-244716848)
