### ISSUE TITLE
Slider Image Option Disappeared

### ISSUE THREAD

**Issue by Hardbower** [ThemeFuse/Unyson#2393]
When creating or editing a slider, the image Population Method is set to "Manually, I'll upload the images myself".
I believe there used to then be an option to actually upload my images, but that option has disappeared. I have everything checked on the Screen Options dropdown, but I no longer see a way to upload an image.
Any information would be incredibly helpful. Thank you!

**Comment by moldcraft** [comment]
Hello @Hardbower 

Please try to activate a default WP theme and check if the upload option is still not appearing.

**Comment by Hardbower** [comment]
Okay. I went on to my dev site to try changing the theme, and the image changing options are there!
Something strange is going on. Under screen options on the working version, it has checkboxes for
1. Slider Configuration
2. Slug
3. Click to edit / Drag to reorder
The add image options are inside the Click to edit / Drag to reorder box.

Under the broken version it has these options:
1. Slug
2. Slider Settings

Here are some screenshots of the pages. I'm not sure why I've got different screen options here.
There are other people editing this site, so it's definitely possible that human error is in play.

![screen shot 2017-02-14 at 3 49 48 pm](https://cloud.githubusercontent.com/assets/11821180/22948644/4f9e113a-f2cd-11e6-8ee0-fd7c852eec48.png)
![screen shot 2017-02-14 at 3 50 06 pm](https://cloud.githubusercontent.com/assets/11821180/22948645/4f9e3282-f2cd-11e6-9c7e-8c5f51dc1714.png)

**Comment by moldcraft** [comment]
Please Inspect Element to see if the options are hidden from css.

**Comment by Hardbower** [comment]
It's not hidden.

**Comment by moldcraft** [comment]
Maybe there are js errors in browser console?
Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by migastudio** [comment]
I have similar problem witg sliders. I do not see any settings, and can't changing photos. I have the newest version of unison and theme "The Journal"
![image](https://cloud.githubusercontent.com/assets/25879027/23101691/d4a61402-f699-11e6-8952-502fad0bdca1.png)

**Comment by moldcraft** [comment]
@migastudio Please open browser Console (F12) and check if there are js errors.

**Comment by migastudio** [comment]
![image](https://cloud.githubusercontent.com/assets/25879027/23120200/a7df770c-f75b-11e6-8c15-4607d73cbca9.png)

**Comment by moldcraft** [comment]
In Inspector (the one on the right) click on Console tab (there you can see if there are errors)

**Comment by migastudio** [comment]
![image](https://cloud.githubusercontent.com/assets/25879027/23124549/f9080ea2-f76d-11e6-9069-562f457d0179.png)

**Comment by moldcraft** [comment]
@migastudio There is an error. I need to inspect it. Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by moldcraft** [comment]
@migastudio You had outdated Unyson Extensions 

![screen](https://static.md/c352ceb8000e48c7452de783a5028402.png)

I updated them and now everything works fine.

**Comment by Hardbower** [comment]
Okay, so I found some time to track down the difference in the code.
Inside ' unyson > framework > extensions > media > extensions > slider ' is a file called class-fw-extension-slider.php
On like 366, an $options variable is created, which contains an array. Within this array, I found the following difference in code:

![screen shot 2017-02-27 at 10 53 40 am](https://cloud.githubusercontent.com/assets/11821180/23368216/1cc60aca-fcdb-11e6-9659-256c2db5b8bf.png)

![screen shot 2017-02-27 at 10 53 51 am](https://cloud.githubusercontent.com/assets/11821180/23368217/1ccaf562-fcdb-11e6-86cd-beea06c10cf0.png)

The first image is of the correctly functioning version. The second one is missing the slider options.
Do you know why this difference would exist? Is this related to some option in an admin screen?
I could obviously copy the code from the working one, but I don't really want to do that because I don't understand what's going on there.

I hope this information helps, and thanks for all of your time. Your customer service is really amazing!

**Comment by migastudio** [comment]
I really do not know how it happened.  I changed the background color strings with the help of a friend. Also removed the counter comments because I do not use. After the change everything was ok. Trouble came after the update.

**Comment by Hardbower** [comment]
Okay, so I found some time to track down the difference in the code.
Inside ' unyson > framework > extensions > media > extensions > slider ' is a file called class-fw-extension-slider.php
On like 366, an $options variable is created, which contains an array. Within this array, I found the following difference in code:

![1](https://cloud.githubusercontent.com/assets/11821180/23863352/fac8389c-07e5-11e7-8fae-6d03ae5cff8f.png)

![2](https://cloud.githubusercontent.com/assets/11821180/23863366/00242f80-07e6-11e7-826a-bfcfefd3c447.png)

The first image is of the correctly functioning version. The second one is missing the slider options.
Do you know why this difference would exist? Is this related to some option in an admin screen?
I could obviously copy the code from the working one, but I don't really want to do that because I don't understand what's going on there.

I hope this information helps, and thanks for all of your time.
