### ISSUE TITLE
wp-editor/tinymce option-type in customizer not functioning properly

### ISSUE THREAD

**Issue by xeifire** [ThemeFuse/Unyson#2395]
In customizer, 

- option-type: wp-editor w/ tinymce turned on

The defaullt Tiny MCE plugins/buttons appear in the wp-editor, but the click events are not triggering/displaying the dropdown menu for the corresponding clicked options. 

ie:
fontselect
fontsizeselect
text color picker (forecolor)

NOTE:

- buttons were added on 

filter: **mce_buttons_2**

- dropdown options were added on 

filter: **tiny_mce_before_init**

My hunch is that it has something to do with the javascript files possibly not loading at the right time? 

ie:
includes/option-types/wp-editor/class-fw-opion-type-wp-editor.php

```
	protected function _enqueue_static( $id, $option, $data ) {
		if (! wp_script_is('editor')) {
			ob_start();
			wp_editor('', fw_rand_md5());
			ob_end_clean();
		}
		/**
		 * The below styles usually are included directly in html when wp_editor() is called
		 * but since we call it (below) wrapped in ob_start()...ob_end_clean() the html is not printed.
		 * So included the styles manually.
		 */
		{
			wp_enqueue_style(
				/**
				 * https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/script-loader.php#L731
				 * without prefix it won't enqueue
				 */
				'fw-option-type-' . $this->get_type() .'-dashicons',
				includes_url('css/dashicons.min.css'),
				array(),
				fw()->manifest->get_version()
			);

			wp_enqueue_style(
				/**
				 * https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/script-loader.php#L737
				 * without prefix it won't enqueue
				 */
				'fw-option-type-' . $this->get_type() .'-editor-buttons',
				includes_url('/css/editor.min.css'),
				array('dashicons', 'fw-unycon'),
				fw()->manifest->get_version()
			);
		}

		$uri = fw_get_framework_directory_uri(
			'/includes/option-types/' . $this->get_type() . '/static'
		);

		wp_enqueue_script(
			'fw-option-type-' . $this->get_type(),
			$uri . '/scripts.js',
			array('jquery', 'fw-events', 'editor', 'fw'),
			fw()->manifest->get_version(),
			true
		);

		wp_enqueue_style(
			'fw-option-type-' . $this->get_type(),
			$uri . '/styles.css',
			array('dashicons', 'editor-buttons'),
			fw()->manifest->get_version()
		);

		do_action('fw:option-type:wp-editor:enqueue-scripts');
	}

```

**Comment by moldcraft** [comment]
> buttons were added on filter: mce_buttons_2
>
> dropdown options were added on filter: tiny_mce_before_init

Please provide us the working code samples of filters that you use so we will be able to reproduce the problem on our side.

**Comment by xeifire** [comment]
**How to test/reproduce?**
 - Look at the behavior for the tinymce buttons in post.php and compare it to the tinymce buttons in customizer

Here is a list of the tinymce buttons that are not working in customizer. 

w/o adding any filters/actions:

**paragraph** dropdown 
**Text color** button and dropdown 
**insert edit link** - when clicked, an input field is supposed to appear to enter in the URL
**unyson shortcodes**
**Special Characters**
**Keyboard Shortcodes**


**added buttons through filter:  mce_buttons_2**

The following enables dropdown selections. They appear if you click "toolbar toggle", but the dropdown menu does not appear when clicked

```

add_filter('mce_buttons_2', 'show_hidden_mce_buttons');
function show_hidden_mce_buttons($buttons){

                $buttons[] = 'fontselect ';
		$buttons[] = 'fontsizeselect ';
		$buttons[] = 'styleselect ';

		return $buttons;

}

```

**Comment by moldcraft** [comment]
I think it's a WP problem with z-index. On Customizer page click on Formats wp-editor drop-down then open browser console and execute this code

```js
jQuery('.mce-panel.mce-menu').css('z-index', '999999')
```

**Comment by moldcraft** [comment]
You should report this problem to WP devs.
