### ISSUE TITLE
Assigning ID to section

### ISSUE THREAD

**Issue by herofive2424** [ThemeFuse/Unyson#2396]
Hello,

in the page builder it is possible to assign a class to a section. Is it also possible to assign an ID somehow?

Thank you!

**Comment by moldcraft** [comment]
Hello,

You can add a custom input in section options for class/id or [assign an id automatically](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head)
