### ISSUE TITLE
[bug] wp-editor not adding brakes on first save 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2397]
Video 
https://monosnap.com/file/H664TMolqSEzHyTEs76zqi1o7p2Ghg

options to test 

```
			'text' => array(
				'type' => 'wp-editor',
				'size' => 'large',
				'editor_height' => 200,
				'shortcodes' => true,
				'editor_type' => 'tinymce',
				'wpautop' => false,
				'label' => __('Content', 'fw'),
				'value' =>''
			),
```

on first save I get this 

![screenshot_20](https://cloud.githubusercontent.com/assets/2340172/22865010/a1de4d16-f15b-11e6-9a9a-c0307250df66.png)

on second save I see brakes and even the p , 

as you can see in option `wpautop `is `false`

![screenshot_21](https://cloud.githubusercontent.com/assets/2340172/22865012/a9da8516-f15b-11e6-8501-a91db202ca4f.png)

the wpautop has been lingering around this option since the first release. 
It would be great to be fixed once and for all.

https://github.com/ThemeFuse/Unyson/issues/1621

**Comment by danyj** [comment]
I tried to do ,  `nl2br`  but on second save we have trouble since brakes and p are added so with  nl2br  second save gets 2 brakes each , and third one cleans it up. It is very hard to get this working. 

Also the p is trouble inside headings , so there is no way to fix any of the issues until wpautop is fixed and we either get new line or brakes not both and not different on every save.

**Comment by moldcraft** [comment]
The problem is [here](https://github.com/ThemeFuse/Unyson/blob/bdcaf7e913ef2e48214c51034514ae9057d92724/framework/includes/option-types/wp-editor/static/scripts.js#L93-L95). I haven't figured out a solution yet.

More details https://sendvid.com/zjlvgc0u

**Comment by moldcraft** [comment]
No need to save the post, it happens on modal save https://sendvid.com/zjlvgc0u

_I haven't figure out a solution yet._

**Comment by moldcraft** [comment]
Please test

**Comment by danyj** [comment]
ok wpautop seems like it works , but now we have no more brakes but new lines when wpautop is false right? 
so we must accommodate those with  nl2br ?
![screenshot_24](https://cloud.githubusercontent.com/assets/2340172/22972178/dfbd1170-f378-11e6-83a4-4b482fceca44.png)

**Comment by danyj** [comment]
ok I see you did try replacing it here 
https://github.com/ThemeFuse/Unyson/commit/eba92e5e9d1ff857c3b8c7b13fa611d1ab080829#diff-58175d25bee5fa21b5af04e384540b24R83

maybe this one works better ?
http://stackoverflow.com/a/7467863/594423   ?

**Comment by danyj** [comment]
@moldcraft  and this text/ visual tab bug , please see this till end 
http://take.ms/i7NFH

tab works on first load until you save the popup, once you save popup and reopen tabs dont work anymore

**Comment by moldcraft** [comment]
When autop is off there are no `<br>` added.

[This code](https://github.com/ThemeFuse/Unyson/commit/eba92e5e9d1ff857c3b8c7b13fa611d1ab080829#diff-58175d25bee5fa21b5af04e384540b24R83) is executed once on editor init.
You can delete editor content and write new text with new lines and it will not add `<br>

**Comment by moldcraft** [comment]
Tabs work fine on my side. Please check browser console, maybe there is an error.

**Comment by danyj** [comment]
there are no errors I am looking at it , see the video please , you must save the popup to see the bug , not just open/close

**Comment by moldcraft** [comment]
I have saved it a few times.

**Comment by danyj** [comment]
ok fixed the tab , it was my typography option had this on doc click  `event.stopImmediatePropagation();`
sorry thnx for looking at that now to the br's and line brakes 

autop is false  


do this on   line 84  https://github.com/ThemeFuse/Unyson/blob/eba92e5e9d1ff857c3b8c7b13fa611d1ab080829/framework/includes/option-types/wp-editor/static/scripts.js#L84



    console.log(initialContent.replace(/\r?\n/g, '<br />'));



I see this 

![d957459d42eb466792f3dfce902be530](https://cloud.githubusercontent.com/assets/2340172/22973812/8f4ac92e-f37f-11e6-81e4-b17b8530bb1f.png)


but output is

![55de31ddaf7c4beeb2791626a4a7f759](https://cloud.githubusercontent.com/assets/2340172/22973827/9b9fcc42-f37f-11e6-85d8-65454e87c4ba.png)


so I have to accommodate and check if br is there if not do nl2br


what I am sayings that when autop is false , we should replace new lines with brakes 
if autop is true editor would do this automatically right?

**Comment by moldcraft** [comment]
> console.log(initialContent.replace(/\r?\n/g, '<br />'));

Initially I set the editor content with `<br>` because there is no other way to preserve new lines in editor. If I set `"Hello\r\nWorld"` the editor shows one line.

> check if br is there if not do nl2br

It should be always without br

> if autop is true editor would do this automatically right?

Yes.

**Comment by danyj** [comment]
im bit lost now but all I am trying to do is match the visual to the output and currently we dont have that unless we massage the output 

so if you have autop false and to this 


```
one 
two
three
```

your output is this 


`one two three`


if autop is true

visual 

```
one 
two
three 
```

output 

```
<p>
one <br />
two <br />
three
</p>
```


in my opinion   autop false should produce this 



```
one <br />
two <br />
three
```

since autop false does not mean strip all tags but strip p tag

**Comment by moldcraft** [comment]
autop is a WP feature, you should contact WP core devs to ask for feature requests.

This this in browser console

```js
var text = "Hello\r\nWorld\r\nFoo",
    textautop = wp.editor.autop(text);
console.log(textautop);
console.log(wp.editor.removep(textautop));
```

output

```
<p>Hello<br />
World<br />
Foo</p>

Hello
World
Foo
```

**Comment by danyj** [comment]
>  you should contact WP core devs to ask for feature requests.

cmon man dont be so harsh , I am trying to make sense out of it and you must admit that it makes no sense to see one thing in editor and get different result

**Comment by moldcraft** [comment]
I tried to disable auto for default post content editor via this filter

```php
add_filter('tiny_mce_before_init', function ($mceInit) {
	$mceInit['wpautop'] = false;
	return $mceInit;
});
```

but it doesn't disable autop. In js the parameter is set

```js
tinyMCEPreInit.mceInit['content'].wpautop
```

I tried to disable autop for default editor to show that it works the same as I described above (without br)
