### ISSUE TITLE
The Blog Extension

### ISSUE THREAD

**Issue by kaxigt** [ThemeFuse/Unyson#2398]
Hi, how do I activate the blog extension? I have made it visible in manifest.php but in back end only a blue square shows up, nothing else. No taxonomy, nothing. If I don't set up $manifest['display'] = true; it doesn't show up at all so I can chose to use it.

I downloaded free scratch theme the_journal and saw new elements in the builder, how can I implement those in the stand alone plugin? I'm thinking of "latest post" and the ability to chose how many posts that would be visible.
Tnx =)

![fw_blog-posts](https://cloud.githubusercontent.com/assets/867315/22866031/7ef29c44-f16f-11e6-9f17-7399e31d87ca.jpg)

**Comment by moldcraft** [comment]
> how do I activate the blog extension?

[Blog extension](https://github.com/ThemeFuse/Unyson/tree/master/framework/extensions/blog) is built-in Unyson and is visible in Extensions page, just press Activate.

> No taxonomy, nothing

[Which taxonomy](https://github.com/ThemeFuse/Unyson/blob/master/framework/extensions/blog/class-fw-extension-blog.php)?

> new elements in the builder, how can I implement those in the stand alone plugin?

You can create a plugin that will contain Unyson extensions which will be loaded via [this filter](http://manual.unyson.io/en/latest/extensions/introduction.html#custom-load-locations).

**Comment by kaxigt** [comment]
Hi!
Nope, it's not visible in the Extensions Page. I have only activated the builder and shortcodes and as you can see on the pic the Blog Post extension is not even available.
![fw-extensions](https://cloud.githubusercontent.com/assets/867315/22878792/61f57fe6-f1db-11e6-879c-ba736e3981e4.jpg)

**Comment by moldcraft** [comment]
Ops, sorry, I was confused. You are right, it's not visible.

[It is activated automatically](https://github.com/ThemeFuse/Unyson/blob/302a6fa4decb9b89b5f50695fdbb1ad2411968ce/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L639-L644) because it is `hidden` and `standalone`.

**Comment by kaxigt** [comment]
tnx =)
