### ISSUE TITLE
[MegaMenu] Item Options

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#240]
If at all possible it would be great to have 
Widget  inside megamenu column and 
mega-menu-row background image with position attributes ( consider wp_add_inline_style please )
so that we can do something like this
http://screencast.com/t/ZXEGoCEFPz4s
from inside the menu setup instead css

**Comment by danyj** [comment]
I dont want to open another issue but it would be nice if you guys can show us how to add / remove options inside the mega menu. I do see that they are hardcoded but not sure if we should override the admin class.

**Comment by moldcraft** [comment]
@danyj Do you mean this?

![s](http://static.md/d707505786061dd920865700e6817a23.png)

**Comment by danyj** [comment]
yes , how we can add own options to it

**Comment by moldcraft** [comment]
Currently there is no possibility to do that.

I will come back with a reply soon, if we will do that or not.

**Comment by danyj** [comment]
also in general , not depending to the mega menu check

example ,  when user click on  Use Mega Menu  I would show them the input box to define the container width 

And beside that I wold like to add a sub description for all menu items like this 
http://screencast.com/t/a7DGwF1f0YVJ

**Comment by sergiubagrin** [comment]
> Widget inside megamenu column

In our old framework we had this option. Old framework was ugly unfriendly. I added analyse tag to this topic.

> mega-menu-row background image with position attributes ( consider wp_add_inline_style please )

This option is interesting we have it in our to do list.

> so that we can do something like this http://screencast.com/t/ZXEGoCEFPz4s from inside the menu setup instead css

Right know it is possible to create a MegaMenu like in your screen: http://screencast.com/t/6MxbG6Zs

>from inside the menu setup instead css 

What you mean from inside the menu?

**Comment by sergiubagrin** [comment]
> And beside that I wold like to add a sub description for all menu items like this 
http://screencast.com/t/a7DGwF1f0YVJ

It is possible to add description on all megamenu levels: http://screencast.com/t/r0rrjQq1r

**Comment by danyj** [comment]
"from inside the menu"  I was talking about adding the bg image from inside the menu, sorry if I was not clear enough.

**Comment by danyj** [comment]
about description ,  it is available for megamenu items only , not all menu items

**Comment by sergiubagrin** [comment]
> about description , it is available for megamenu items only , not all menu items

Can you give me a screen?

> "from inside the menu" I was talking about adding the bg image from inside the menu, sorry if I was not clear enough.

Yes. We planned this. We added it to ToDo List

**Comment by danyj** [comment]
@sergiubagrin sure here it is , 
http://prntscr.com/6ag9dtenu item Layouts does not have it but Mega menu -> Group 1 does

**Comment by shonnamartell** [comment]
Is there a easy hack or a way to hide the description option in the mega menu?

**Comment by moldcraft** [comment]
todo (note) : There can be options, like a single checkbox near "Use as Mega Menu", that do not depend on that checkbox and should be always visible

**Comment by moldcraft** [comment]
Please test: Download [this version](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/tree/item-options) and use [this filter](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/924cf84385a1f57689b56918f792f1ab9fae4ecb/helpers.php#L69) to add options for menu items.

P.S. Show/Hide depending on the "Use as Mega Menu" checkbox is not working yet.

Please give all the details about how you imagine this feature should work.

**Comment by moldcraft** [comment]
Maybe to not show options below, but just add a button and it will open a popup with options (to not consume space)

**Comment by moldcraft** [comment]
All items to have the same options or options should be changed depending on item type (post, taxonomy, manual link) and item level?

**Comment by danyj** [comment]
>Maybe to not show options below, but just add a button and it will open a popup with options (to not consume space)
yes , popup with options would be better ,  you can move this in that popup

![screenshot_6](https://cloud.githubusercontent.com/assets/2340172/13227239/fe8ad6bc-d995-11e5-88d7-9f406626db65.jpg)

and have button say , options or something. Than we can add/remove options from that popup directly

**Comment by danyj** [comment]
I am not sure if I am doing this right 


	/**
	 * Add menu options
	 */
	function _thz_filter_menu_item_options() {
		
		$options = array(
		
			'testswitch' => array(
				'label' => __('Label', 'fw'),
				'desc' => __('Desc', 'fw'),
				'type' => 'switch',
				'right-choice' => array(
					'value' => 'hide',
					'label' => __('Hide', 'fw')
				),
				'left-choice' => array(
					'value' => 'show',
					'label' => __('Show', 'fw')
				),
				'value' => 'show'
			)
		
		);
		
		return $options;
	}
	add_filter( 'fw:ext:megamenu:item-options', '_thz_filter_menu_item_options' );


returns option with no unyson option style 

![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/13227476/1f8bc848-d997-11e5-9bd6-28255b27fea8.jpg)

looks like options css and js are not included

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/commit/81a2293a83604275ada17b1c32a28d66b4a83842

Check now

**Comment by danyj** [comment]
ok , now we have customize button , can we get hook  popup size ?  I see the one for btn txt, but instead doing 3 filters for 3 different things

options 
btn text
popup size 


can you sum all of them in to one ?

**Comment by moldcraft** [comment]
Done.

P.S. Please Watch the MegaMenu extension to get notifications https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/watchers

**Comment by danyj** [comment]
size does not work 

http://prntscr.com/a7q3uk


and I still have to run 2 filters


	/**
	 * Add menu options
	 */
	function _thz_filter_menu_item_options() {
		
		$options = array(
			'testswitch' => array(
				'label' => __('Label', 'fw'),
				'desc' => __('Desc', 'fw'),
				'type' => 'switch',
				'right-choice' => array(
					'value' => 'hide',
					'label' => __('Hide', 'fw')
				),
				'left-choice' => array(
					'value' => 'show',
					'label' => __('Show', 'fw')
				),
				'value' => 'show'
			)
		
		);
		
		return $options;
	}
	add_filter( 'fw:ext:megamenu:item-options', '_thz_filter_menu_item_options' );
	
	function _thz_filter_menu_item_popup_options($opt) {
		
		$opt['title'] = __('Menu item options', 'fw');
		$opt['size']  = 'large';
		
		fw_print($opt);
		return $opt;
	}
	
	
	add_filter( 'fw:ext:mega-menu:item-options:popup-option', '_thz_filter_menu_item_popup_options');


am I missing something?



I was thinking about this  rather 



	function _thz_filter_menu_item_popup_options($opt) {
		
		$options = array(
			'testswitch' => array(
				'label' => __('Label', 'fw'),
				'desc' => __('Desc', 'fw'),
				'type' => 'switch',
				'right-choice' => array(
					'value' => 'hide',
					'label' => __('Hide', 'fw')
				),
				'left-choice' => array(
					'value' => 'show',
					'label' => __('Show', 'fw')
				),
				'value' => 'show'
			)
		
		);
		
		
		$opt['title'] = __('Menu item options', 'fw');
		$opt['size']  = 'large';
		$opt['popup-options']  = $options;
		
		return $opt;
	}

**Comment by moldcraft** [comment]
Both filters are independent and do one specific thing.

----

https://github.com/ThemeFuse/Unyson/blob/v2.5.0/framework/includes/container-types/popup/class-fw-container-type-popup.php#L46-L50

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/commit/20bc79926e99438ee71794d48f68b5d8557a653b
