### ISSUE TITLE
Required extensions manifest notices need improvemant

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2401]
We asked for this https://github.com/ThemeFuse/Unyson/issues/2117  so that we can **autoinstall    all extensions**. that our themes work with,  now that this works I think we need to extend the notices for those , example of my manifest 

    'extensions' => array(
		'page-builder' => array(
            'min_version' => '1.0.0',
        ),
		'slider' => array(
            'min_version' => '1.0.0',
        ),
		'breadcrumbs' => array(
            'min_version' => '1.0.0',
        ),
		'shortcodes' => array(
            'min_version' => '1.0.0',
        ),
		'megamenu' =>  array(
            'min_version' => '1.0.0',
        ),
		'portfolio' => array(
            'min_version' => '1.0.0',
        ),
		'events' => array(
            'min_version' => '1.0.0',
        ),
		'backups' => array(
            'min_version' => '1.0.0',
        ),
		'wp-shortcodes' => array(
            'min_version' => '1.0.0',
        ),
    )

with that I tell unyson to install all these on first time install ,  

now when user disables Portfolio,   he/she sees the notice that this extension is required

, ![screenshot_22](https://cloud.githubusercontent.com/assets/2340172/22890207/f124e58c-f20b-11e6-95c9-421ee61efe38.png)

 but that is not actually true , the theme works fine without it so I propose something that would show appropriate notice or hide it completely

    'extensions' => array(
		'portfolio' => array(
            'min_version' => '1.0.0',
			'notice' => 'recommended'// required | recommended | hide
        ),
    )

**Comment by danyj** [comment]
or we can add this in manifest 


	'autoinstall' => array(
		'page-builder',
		'slider',
		'breadcrumbs',
		'shortcodes',
		'megamenu',
		'portfolio',
		'events',
		'backups',
		'wp-shortcodes',
	)


than we can do this instead notices checks 


    'extensions' => array(
		'page-builder' => array(
            'min_version' => '1.0.0',
        ),
		'breadcrumbs' => array(
            'min_version' => '1.0.0',
        ),
		'shortcodes' => array(
            'min_version' => '1.0.0',
        ),
		'megamenu' =>  array(
            'min_version' => '1.0.0',
        ),
		'backups' => array(
            'min_version' => '1.0.0',
        ),
		'wp-shortcodes' => array(
            'min_version' => '1.0.0',
        ),
    ),
	'autoinstall' => array(
		'page-builder',
		'slider',
		'breadcrumbs',
		'shortcodes',
		'megamenu',
		'portfolio',
		'events',
		'backups',
		'wp-shortcodes',
	)

**Comment by moldcraft** [comment]
Requirements are for required stuff (without which the theme doesn't work).

Why don't just use [`$manifest['supported_extensions']`](http://manual.unyson.io/en/latest/manifest/theme.html#content)?

**Comment by danyj** [comment]
> Why don't just use $manifest['supported_extensions']?

because supported_extensions does not autoinstall extensions. 

only requirements > extensions does

**Comment by danyj** [comment]
if you could make  supported_extensions  to do autoinstall than we wold be ok

**Comment by moldcraft** [comment]
1. https://github.com/ThemeFuse/Unyson/blob/bdcaf7e913ef2e48214c51034514ae9057d92724/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L3442-L3459
2. https://github.com/ThemeFuse/Unyson/blob/bdcaf7e913ef2e48214c51034514ae9057d92724/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2747
3. https://github.com/ThemeFuse/Unyson/blob/bdcaf7e913ef2e48214c51034514ae9057d92724/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2715-L2717

**Comment by danyj** [comment]
Oh , ok , I tought that they installed via required not supported. Thank you!

**Comment by ivandotv** [comment]
@danyj 
So if I understood correctly `$manifest['requirements']` is just for *nagging* the user that not all `supported` extensions are installed?
