### ISSUE TITLE
Introducing fw:options:teardown event

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#2403]
We often find ourselves to want to teardown some complex option type in a modal so that we don't leak memory. This event gives you a chance to do so, right before the modal containing your option type will get closed and its HTML will be cleared out.

Syntax:

```javascript
fwEvents.on('fw:options:teardown', function (data) {
  var $el = data.$elements; // just like with fw:options:init
  var modal = data.modal; // you have access to the modal instance here

  // $el is the container for each option type in the modal
  
  var optionTypes = $el.find('.my-special-option-type').toArray();

  _.each(optionTypes, _.compose(teardownOptionType, $))
});

// this function will contain the logic for destroying a single option type
function ($optionTypeEl) {
  // in most common cases you just have to remove a class
  $optionTypeEl.removeClass('initialized');

  // in complicated option types you'll also have to do more house keeping,
  // like clearing out global storages for that option type or things like that
  // or destroying jQuery plugins
}
```

cc. @moldcraft @GheorgheP @danyj What do you guys think about that?

**Comment by andreiglingeanu** [comment]
@moldcraft Can we trigger this event right before we submit a reset request in Theme Settings?
Or, really, in any other TS-like page.

**Comment by moldcraft** [comment]
So the solution is to do

```js
fwEvents.trigger('fw:options:teardown', {$options: $el});
```

before each `$wrapper.remove()` or `$wrapper.html(newOptionsHtml)` _(in TS reset script, in `addable-*` option-types, in modal, etc.)_ ?

**Comment by andreiglingeanu** [comment]
@moldcraft Right. `addable-*` and any modals are done. TS reset script is left and a couple of corner cases I may not know about.

**Comment by moldcraft** [comment]
Ok

**Comment by ivandotv** [comment]
@andreiglingeanu 
Wait , I though that modals are only created once , and then are just hidden,  and shown again.

**Comment by danyj** [comment]
@ivandotv  

> modals are only created once

they are emptied on close 
https://github.com/ThemeFuse/Unyson/blob/0196aa401e3426b9b2bbae51a131597a57786059/framework/static/js/fw.js#L911


@andreiglingeanu  

> What do you guys think about that?


I was looking for this the other day ,  I have  a color palette that is constantly present in HTML and moved to opened color picker when needed.   The modal close is deleting the html on close  thus also removing my palette with that so it is no longer available for next opened color picker

So yes , we definitely need something before close and HTML removal.

**Comment by andreiglingeanu** [comment]
Nope, on each modal close its html is cleaned out and that thing is configurable. The only thing we are doing is a simple cache for the html received from server. 

That is, javascript for initialising an option type is called each time you open the modal.

**Comment by andreiglingeanu** [comment]
@danyj right, we definitely need that and this event is already implemented in the master version of unyson.

**Comment by ivandotv** [comment]
Okay, great. 
I can use this because I have js code that uses "switch" option to show/hide other options. But I never bothered to clean up all the events that I'm attaching to the "switch" option. 
I figured it's on admin site, so who cares :)

**Comment by danyj** [comment]
@ivandotv 
I think this will also help you with this https://github.com/ThemeFuse/Unyson/issues/1956

**Comment by andreiglingeanu** [comment]
The DOM nodes are actually removed so you probably don't need that event removal. Though, if you use event delegation, those events will stick to the body element even after the node destroy, causing a memory leak that way. 

Actually, you should care about performance on the admin side because you can easily get it to be VERY slow.

**Comment by ivandotv** [comment]
I've noticed that admin gets slow, but that's because of the amount of options and all html that it needs to render. 
Popups  (JS) always work okay.

**Comment by andreiglingeanu** [comment]
Yeah. And a great solution for that is client side templating for option types.

**Comment by andreiglingeanu** [comment]
Teardown is currently working fine while closing modals and TS reset. Probably **Reset** in modals should also be implemented. 

Can you think about other places this might be required?

**Comment by andreiglingeanu** [comment]
[Implemented for modals.](https://github.com/ThemeFuse/Unyson/blob/b01dfcf709ea070bb497ddeeadc87dc5108e3a8b/framework/static/js/fw.js#L969-L974)
