### ISSUE TITLE
shortcode in the text widget (woffice)

### ISSUE THREAD

**Issue by CriBou** [ThemeFuse/Unyson#2404]
Hello, 
I've tried to use the shordcode
[list style="list-circle" content="array('Item 1', 'Item 2', 'Item 3')"/] in the sidebar in a text widget without success.
I found this shortcode here https://alkaweb.ticksy.com/article/5293/ but the support of woffice tells me you provided that lisr, and they didn't manage make it work either.
Could you help me for this ?
Thank you
Chris
www.les-multipotes.com

**Comment by moldcraft** [comment]
Hello,

Text Widget is built-in WP (it not defined in Unyson). You can alter its the output via [this filter](https://github.com/WordPress/WordPress/blob/0bcfc08b3f62d765f6f26ed2771b0e44242482ae/wp-includes/widgets/class-wp-widget-text.php#L62)

```php
add_filter('widget_text', '_filter_theme_text_widget_text');
function _filter_theme_text_widget_text($text) {
	return do_shortcode($text);
}
```
