### ISSUE TITLE
Download extensions ? Hell ! Why ?

### ISSUE THREAD

**Issue by tlartaud** [ThemeFuse/Unyson#2405]
Hi,

I'm wondering why you packaged Unyson extensions outside of your plugin itself. It's a huge breaking process for automated deployments.

My Production and Staging websites are deployed using Shipit (custom homemade WP stack), and I use some WP Constants to not allow plugin installations or additions into the backend (I can only install plugins on dev environments). So, I simply can't download the extensions on my staging and production environments. My plugins are installed trough composer, so, when my site get deployed, unyson is install as a fresh install, without the extensions. Each time I deploy my sites, a fresh copy of my site's repository is cloned and an automatic `composer install` is ran, then everything get copied to my remote via rsync.
However, that way, Unyson extensions are not installed. After the deploy, I have to manually upload the extension folder to my remote.

What's the point of doing that ? Why don't you use standards plugins as extensions ? It will break so many things, and we should never download a plugin or extension on a staging or a prod environment, files within the plugins or themes folder should never be modified except if I redeploy everything in a new folder and make a new symlink to activate the new site version (shipit act like capistrano : current, releases and shared folder).

The only solution I see for now is too install unyson locally, push to my repo, with all the extensions included. I really don't like pushing wp plugins to my repos, and downloading extensions from staging or production is rly not good.

Do you have a solution for installing unyson through composer and get the extensions downloaded in the same time ?

Plus, if Unyson is included in a theme with the `bootstrap.php` where are the extension going, in the theme folder ?

Do you have any recommendation about using Unyson with composer ? Or do you have any tip to let the available extensions automatically get installed ? I really don't like to ask my theme users to activate themselves the theme dependencies. It would be easier to manage if your extensions were simple plugins, and not in-built extension systems :(

Cheers, and thank you for this amazing plugin !

**Comment by moldcraft** [comment]
Hello,

I have never used composer for WP projects.

Maybe you can run [this script](https://github.com/ThemeFuse/Unyson/blob/master/framework/extensions/clone-all.bash) after Unyson plugin install? [There](https://github.com/ThemeFuse/Unyson/blob/f491860a1bcf632513230603f95895dc626a5f58/framework/extensions/clone-all.bash#L47) is used `git@...` urls, but we can add a parameter to change it to `https` (so you will not be prompted to enter your ssh key password)

**Comment by andreiglingeanu** [comment]
> Or do you have any tip to let the available extensions automatically get installed ?

There's some work done on WP CLI unyson package, which gives you a command to do just that.

There you have it `wp unyson extensions install` - this package is soon to be released in Unyson, but it is still in an experiment phase.

https://github.com/ThemeFuse/Unyson/issues/2277#issuecomment-271877262

With this script (if you use capistrano) you'll be able to run it right before capistrano does a symlink into the `current` folder and you'll have to correct extensions installed.

Let us know if this looks like a solution for you.

**Comment by tlartaud** [comment]
Hi guys,

Thanks a lot for theses really usefull tips. i'm going to try this on Monday and let you know if that worked for me.

**Comment by tlartaud** [comment]
Hi @moldcraft,

The script is working great. I can now deploy Unyson plugin installed with Composer in one single command with Shipit.

The script is not included in the plugin from WPackagist, but I copied it to my repo.
Looks a bit hacky, but it works, and will do the job, at least for updating and deploying my personal site. Will make the code looks better later.

The above means : When Shipit finished to fetched my repository, it will run some commands like `composer install` to fetch the plugins, and then install unyson extension. Then the folder will be ready to be rsynced to the remote server.

```
    grunt.shipit.on('fetched', function () {
        grunt.task.run(['publish:dependencies']);
        if (options.app.theme !== "") {
            grunt.task.run(['publish:dependencies_theme']);
        }
    });
    grunt.registerTask('publish:dependencies', function () {
        // Build Unyson extension
        if(grunt.file.exists(options.app.webRoot + "/app/plugins/unyson/unyson.php")) {
            unyson = " && cp /var/www/config/mastack/shell/unyson-install.bash " + grunt.shipit.config.workspace + "/" + options.app.webRoot +  "/app/plugins/unyson/framework/extensions/clone-all.bash && cd '" + grunt.shipit.config.workspace + "/" + options.app.webRoot + "/app/plugins/unyson/framework/extensions" + "' && ./clone-all.bash";
        }

        // Run dependencies installation
        grunt.shipit.local(
            "cd '" + grunt.shipit.config.workspace + "' && composer install" + unyson + ";", this.async()
        );
    });
```

Thanks for that !
Regards.
