### ISSUE TITLE
I want to change the column class

### ISSUE THREAD

**Issue by alymohamedhassan** [ThemeFuse/Unyson#2406]
I want to change the column class from fw-col-sm-* to fw-col-MD-*

so, I get things a more responsive

**Comment by TrangDinhVan** [comment]
Please override the file config.php of the extension builder. Meaning that you will copy that file and paste and edit it in
framework-customizations/extensions/builder/config.php

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid
