### ISSUE TITLE
GIF thumbnails?

### ISSUE THREAD

**Issue by filange** [ThemeFuse/Unyson#2407]
Hi, I'm having an issue using the Portfolio Grid with the 1st option (transparent color and text on hover) where GIF thumbnails weren't working. A static image is displayed on the grid, but no animation. Wondering if it's just not supported through Unyson or am I doing something wrong? 

It's a 43kb gif

**Comment by moldcraft** [comment]
The image is resized and the animation is lost. This also happens when you insert a gif in Blog Post via Add Media button from WP.
