### ISSUE TITLE
The core  auto setup

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2408]
Your The core theme has a nice auto setup,  
http://docs.themefuse.com/media/32/Install-Theme-4.jpg

Is this publicly available somewhere?  can we use that in our themes?

**Comment by Ataurr** [comment]
Looks nice 👍

**Comment by duongancol** [comment]
absolutely agree with this feature

**Comment by Ataurr** [comment]
[envato-wp-theme-setup-wizard](https://github.com/dtbaker/envato-wp-theme-setup-wizard) have same like this.  But it will be messed up with unyson backup extension. 

Hope Unyson❤️  will introduce this feature for us.

**Comment by duongancol** [comment]
Yep! In fact, many uses don't read the documentation and they usually get stuck after installation extension part. They don't know what is next step to install demo content so I hope this feature will be released public soon. It's helpful for all user.

**Comment by Ataurr** [comment]
Yeah, I know. "Purethemes" said a few days ago. After he is using Dtbaker setup wizard theme installation support drop to zero.

**Comment by moldcraft** [comment]
Hello,
We don't have plans to release this feature publicly.

**Comment by danyj** [comment]
@moldcraft   

> We don't have plans to release this feature publicly.

ok , how about if we buy the core and than copy the auto setup folder to our theme? Is that ok for you?

**Comment by ivandotv** [comment]
Well if it's gpl , "get inspired" by the code. and make a plugin/extension.
I like this a lot.

**Comment by danyj** [comment]
> Well if it's gpl

I did not want to say it ,  but yes , I know I could just swing it.

**Comment by ivandotv** [comment]
Well regardless of this issue. I will also need to tackle this "feature"
I am thinking it could be made like this.
1. Theme queries your site.
2. gets back json with available demos ( or you could bundle json with a theme )
3 builds user interface for those demos ( from json)
4. User selects demo content.
5. Theme starts setup process ( install plugins , import content)
6. Done. 

@danyj 
What do you think about this ? 

on a side note:
I'm using docker and I did made a special wordpress image that looks for a `setup.json` file
And installs plugins , themes , imports data,  and setups initial user. 
I've done it via relatively simple php script, and wp-cli.

The key is **wp-cli**, If we could somehow have something similar to wp-cli running via plugin, setting this kind of functionality could be done.

**Comment by danyj** [comment]
@ivandotv

>What do you think about this ?

the demo extension install process does that already 
http://manual.unyson.io/en/latest/extension/backups/index.html#demo-content-install
http://docs.themefuse.com/the-core/your-theme/getting-started/how-to-install-the-demo-content

and it works fine but I am after this thing 

Themefuse , or should I say @moldcraft ( looks like his handy work :)  ) 

made a great setup for the core theme 

After theme activation you are moved to auto setup screen

http://docs.themefuse.com/media/32/Install-Theme-4.jpg


and the extension does everything else , 

what I like most and it should also be available in the demo extension is this nifty thing that lets you define plugins based on the demo , 

![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/23165005/5051d7b6-f83a-11e6-8274-43dbbd29d59b.jpg)

**Comment by Ataurr** [comment]
Wow, Install plugin according to theme demo. And this install process is crazy Feature 😍.

**Comment by ivandotv** [comment]
@danyj 
Well that's basically what I'm proposing, just use json  so it could be parsed with javascript also.
I don't know how much is your theme integrated ( depended ) on unyson.
In my case I'm using unyson only for backend options ( visual composer for page building)
So It all works without unyson.
That's why when I'm thinking about this feature, I'm not thinking about unyson.
The best thing for this feature is to be independent of unyson ( it should be able to install unyson as a dependency)
If you are interested we could pull the resources and develop this thing together ( I'm interested in doing all things JavaScript) and I could do php backend.

edit:
After further inspection of unyson I see that backup functionality has many options and corner cases. So this might not be so easy to create ( in general everything is always more complicated than it seems on the first glance )

**Comment by danyj** [comment]
> visual composer for page building

cheater! :) 

I went Unyson all the way and yes theme works without it also. 

>  If you are interested we could pull the resources and develop this thing together

I am in the last stage , DOCS !, packing and hoping for the best. After the release we should get together.

**Comment by ivandotv** [comment]
@danyj 
Great, but what about demo options import?
You are shipping without that?

**Comment by xperter** [comment]
@ivandotv Maybe @danyj  using Unyson own backup extension which is really easy to setup demo. Options and everything easily imported. 

@danyj  How authors highlight the Demo wizard to [item description ](https://d1a6a9r46cnyll.cloudfront.net/6674a7776647a356946cfe04cbd46ae30bf94ebc/687474703a2f2f74686573696d706c652e656c6c657468656d65732e636f6d2f707265735f315f6769662e676966 )

This is really an impressive feature. Waiting reply from unyson team about this 🥇

**Comment by danyj** [comment]
@ivandotv 

>Great, but what about demo options import

Unyson demo does all that , complete DB with options, you should try it

**Comment by DimiBaitanciuc** [comment]
Hey guys, good news. We've been talking about this and decided you can use the auto setup from our The Core theme. 

As for including it natively with Unyson we'll have to see about that in the future. To my understanding, it requires some modifications and a bit of work. @moldcraft can shed some light on what it implies. 

In the meantime you can use our The Core auto install with no problem and adapt it to your needs. Hope this helps.

Cheers.

**Comment by Ataurr** [comment]
Thanks very much @DimiBaitanciuc & @moldcraft ❤️

**Comment by moldcraft** [comment]
To make it publicly officially available (in Backup extension) there is work to do. Maybe someday we will implement this feature, till then just copy/paste it in your theme and adapt.

**Comment by danyj** [comment]
YEAHHHHHH, mine works :)

**Comment by danyj** [comment]
ok here we go 

copy 
```

the-core-parent\theme-includes\includes\sub-includes   //folder
the-core-parent\theme-includes\includes\sub-includes.php  
```

 from  the-core theme 

to   your theme includes folder , 

since mine is in 

`theme_name/inc/includes , `

I moved it there , and modified

`sub-includes.php `  to fix the path 

`load_template( get_template_directory().'/inc/includes/sub-includes/auto-setup/class-fw-auto-install.php', true ); `



next open 

`sub-includes\auto-setup\class-fw-auto-install.php`

and also change the path to your includes folder on line 20 and 21

```

	$this->file_uri    = get_template_directory_uri() . '/inc/includes/sub-includes/auto-setup';
	$this->file_path   = get_template_directory() . '/inc/includes/sub-includes/auto-setup';
```


while you there you can also change the `$page_slug` ( line 6)   and` $_prefix` ( line 16 ) 


last   open `sub-includes\auto-setup\config\config.php  `

and make changes to reflect your demos , plugins and child theme 



THANK YOU THEMEFUSE!!!!

**Comment by danyj** [comment]
oh , @everyone else , play fair , give some credit http://prntscr.com/ebz7n3 where is due , this extension is worth much more.

**Comment by Ataurr** [comment]
I can't buy from themefuse.com :/ it's redirected to TF

@danyj  You bought from themefuse.com?

**Comment by danyj** [comment]
>  You bought from themefuse.com?

yes directly ,   clear cache 

https://sites.fastspring.com/themefuse/product/thecore?coupon=40FH45T&_ga=1.32497406.1570644331.1487767656

**Comment by danyj** [comment]
or , https://themefuse.com/the-core-multi-purpose-wordpress-theme/#pricing

**Comment by danyj** [comment]
@moldcraft  , there is small issue with github master files , example if in config plugin is set as 


		array(
			'name'   => 'Unyson',
			'slug'   => 'unyson',
			'source' => 'https://github.com/ThemeFuse/Unyson/archive/master.zip'
		),

the installation folder ends up being 


`plugins/Unyson-master`

seems like the slug should be used for folder names and not the extracted folder

is there something I am missing here?
