### ISSUE TITLE
Speed Issue with Wordpress 4.5 running WOffice theme

### ISSUE THREAD

**Issue by benavege** [ThemeFuse/Unyson#2409]
Hello,

I am having issues with speed when it comes to loading pages on our company's intranet, which is running on Wordpress 4.5 using the W Office theme that uses the Unyson framework. Our intranet is locally hosted on one of our web servers and is not facing the internet. I ran a scan of the site and it takes around 4 seconds to load a page and 2 of those 4 seconds are due to the Unyson framework. Would there be any reason for this?

Thank you,
George

**Comment by Ataurr** [comment]
https://alkaweb.ticksy.com/article/5816/

Or contact theme author: https://alkaweb.ticksy.com/
