### ISSUE TITLE
Contact Form information persistence

### ISSUE THREAD

**Issue by olumideadebayo** [ThemeFuse/Unyson#2410]
HI, I'm using the Contact Form and was wondering if it'll be possible to save the submitted info in database?  Is this something you plan to submit down the line?

**Comment by moldcraft** [comment]
Hello,
We don't have plans to add this feature.
From code you can use [this action](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/bcac0e9978762b0b3461b440e7d9e3e5191b211b/class-fw-extension-forms.php#L227) to create your custom post and populate it with form data.
