### ISSUE TITLE
Wordpress WYSIWYG Editor don't show in Accordion, Tabs, etc.

### ISSUE THREAD

**Issue by Aaron-Refox** [ThemeFuse/Unyson#2412]
I installed Unyson on an existing (non unyson) theme.
Unyson seems to work fine, only i miss some options.

When i want to add an accordion of a tab element i can give it an title and i can in content.
Only i get just a text block and not the Wordpress WYSIWYG editor.
So i can't add an image or something in the content.

I think/hope it's just a small setting that i don't know.
Hope someone can help me.

Thanks a lot!

**Comment by moldcraft** [comment]
Hello,
Please provide your options array and we will test the problem on our side.

**Comment by Aaron-Refox** [comment]
Hello,

Where / in which file i can find the options array?
(Mabye that is what's going wrong?)

I just installed Unyson via Wordpress > Plugins > Add New, that it.
Do i need to add or change some of the php files?

Thank you so far!

**Comment by moldcraft** [comment]
> When i want to add an accordion of a tab element i can give it an title and i can in content.

Which accordion, which tab, what title?

**Comment by Aaron-Refox** [comment]
![unyson](https://cloud.githubusercontent.com/assets/25869474/23131180/68a39ee6-f789-11e6-8d8b-7af8c68be73c.jpg)

I make i screenshot/picture from what i mean.
I hope you understand what is not working.

The textboxes in the Content Elements are just text boxes.
On another site (with is a supported Unyson theme) i get WYSIWYG editors in the textboxes.
Is it possible to make that work in a just a random theme?

(Also got a lot more options in the Jelevin theme, but if only the WYSIWGY editor will work on the text boxes at the Accordion & Tabs options will work, i will be very happy.)

Thanks for your time!

**Comment by moldcraft** [comment]
Those are [shortcodes](http://manual.unyson.io/en/latest/extension/shortcodes/index.html). They have [default options](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/master/shortcodes) in `unyson/framework/extensions/shortcodes/shortcodes` but themes can overwrite the options and view files and change the options in `{theme}/framework-customizations/extensions/shortcodes/shortcodes`
