### ISSUE TITLE
BIG problem after latest update

### ISSUE THREAD

**Issue by kaxigt** [ThemeFuse/Unyson#2413]
After the latest update many parts on my site disappeared (I'm using a child theme). In back-end it is as it was before but in front end I got images and text loss, and it seems to be random. I have tried to re-publishing texts and images, with no success. And i have re-installed the plugin, still problems. I even got the same problem if i change to a standard theme. What happened? Yesterday everything worked as charm...

![after-update1](https://cloud.githubusercontent.com/assets/867315/23137351/cf9a745e-f7a1-11e6-8691-9426e2da1d52.jpg)
![after-update2](https://cloud.githubusercontent.com/assets/867315/23137352/cf9bb9e0-f7a1-11e6-90ef-b79ce4d6514a.jpg)
![after-update3](https://cloud.githubusercontent.com/assets/867315/23137350/cf97a9b8-f7a1-11e6-8dd2-36b931599758.jpg)

**Comment by moldcraft** [comment]
Hello,

1. Check your server error.log
2. Use browser inspect to check why images are not visible
3. If you can't find the answer, send me your admin and ftp credentials and I will inspect

**Comment by thednp** [comment]
You should do some `var_dump()` in the view files of both theme and your child and see what's missing or out of date. Some functions may have been deprecated.

**Comment by kaxigt** [comment]
SOLVED//
Error log doesn't show anything important and I'm always working in dev mode using moz dev version. Even when i inactivated all plugins the problem didn't disappeared so I uninstalled and re-installed the theme and unyson plugin. And now suddenly I found the problem. The plugin Image Lazy Load in wordpress.org are not compatible any longer, it is fluktuating. Just so you now if someone else ends upp with the same problem.

Tnx for feedback though =)
