### ISSUE TITLE
Please register builder types on 'fw_option_type_builder:{builder-type}:register_items' action

### ISSUE THREAD

**Issue by tiagocaus** [ThemeFuse/Unyson#2416]
One of the errors disappeared, but there is still another:

Please register builder types on 'fw_option_type_builder:{builder-type}:register_items' action

Image: http://image.prntscr.com/image/994a6e6ec9694111b0a553b6e6651b79.png

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/2239#issuecomment-281663784
