### ISSUE TITLE
Create responsive form

### ISSUE THREAD

**Issue by tiagocaus** [ThemeFuse/Unyson#2417]
It could allow you to create responsive form.
Allow upload, input fields, selections, text and how to write JavaScript, PHP Code.

**Comment by moldcraft** [comment]
Unyson forms are responsive.
Upload filed is in todo https://github.com/ThemeFuse/Unyson-Forms-Extension/issues/22

**Comment by tiagocaus** [comment]
My request has nothing to do with the contact form you already have.

Thinking of being free to assemble what you want, the way you want my request is the most correct and sensible.

Reopen my request, as it is different from what you have in the contact form.

**Comment by moldcraft** [comment]
Please describe more your feature request (if possible, with examples)

**Comment by tiagocaus** [comment]
On my site I would need to create a form for calculating and consuming material.

The customer would put the size of the house, the size of the brick and the system would calculate the consumption of the materials we have.

It would have tabs separating the products and their thickenings.

How would you have put up a form in html5 + js.


Something free to do as we need and not limit as the form of contact, because one thing has nothing to do with the other.


You see?

**Comment by moldcraft** [comment]
The easiest way is to build the estimation form on a [specialized site](https://www.google.com/webhp#q=estimator+builder+online) and embed it in your site (as iframe or js).

The hardest solution is to dig in [builder extension](http://manual.unyson.io/en/latest/extension/builder/index.html) code and figure out how to build your own estimation form builder
