### ISSUE TITLE
How to make a full section size in the builder?

### ISSUE THREAD

**Issue by yerzhigit** [ThemeFuse/Unyson#2418]
I can't found need information. Screen
<a href='http://hostingkartinok.com/show-image.php?id=5f530377ad7266fb56b8f13d2a83d59a' title='хостинг фото'><img src='http://s8.hostingkartinok.com/uploads/thumbs/2017/02/5f530377ad7266fb56b8f13d2a83d59a.png' /></a>

**Comment by moldcraft** [comment]
Section by default has [this option](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/54c26a63df9cf734ddefdf38d9d5b333479c18c2/shortcodes/section/options.php#L6-L9) which changes [the class in html](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/54c26a63df9cf734ddefdf38d9d5b333479c18c2/shortcodes/section/views/view.php#L27) which uses [these styles](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/static/css/frontend-grid.css#L102-L132).
