### ISSUE TITLE
[bug] fw_get_db_settings_option inside after_setup_theme does not add image size

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2419]
To see output do this in  `theme/settings.php  ` on top  and in frontend `static.php `

`fw_print(get_intermediate_image_sizes());
`

frontend sees new image size , but theme admin does not

Funny bug , If you do this  after theme setup  the image size will not be visible in theme admin 

	function _something_something() {
	
		$img_max = fw_get_db_settings_option( 'something',null);// does not matter if null or value
	
		// register image sizes
		add_image_size('my-custom-size', 500, 300, true); 
	
	}
	
	add_action('after_setup_theme', '_something_something');

if you change it to get_option it is added ,   

	function _something_something() {
	
		$img_max = get_option( 'something',null);
	
		// register image sizes
		add_image_size('my-custom-size', 500, 300, true); 
	
	}
	
	add_action('after_setup_theme', '_something_something');

if you change order , it is added 

	function _something_something() {

		// register image sizes
		add_image_size('my-custom-size', 500, 300, true); 
	
		$img_max = fw_get_db_settings_option( 'something',null);
	

	
	}
	
	add_action('after_setup_theme', '_something_something');

**Comment by danyj** [comment]
if I do 

    add_action('after_setup_theme', '_something_something',9);

everything "seems" ok , but I am not sure if I should do that.

**Comment by moldcraft** [comment]
When you call `fw_get_db_settings_option()` then `theme/settings.php` is loaded and `fw_print(get_intermediate_image_sizes());` is executed. After that you register the image size

**Comment by danyj** [comment]
ok but why does it  work when priority is 9 ?

**Comment by moldcraft** [comment]
The framework is loaded on [the same action](https://github.com/ThemeFuse/Unyson/blob/81c0fc7287982b086c4f60c0e9f3f5c42458a163/framework/bootstrap.php#L14) you can debug the order of execution.

**Comment by danyj** [comment]
ok bud I understand what you are saying but something makes no sense 

framework is executed on after_setup_theme and default priority is 10 , 

I call theme option there and add_image_size after, no go 

I change priority to 9 ,  get the option DB value and size is added 

that this 

> When you call fw_get_db_settings_option() then theme/settings.php is loaded and 

kinda makes no sense anymore since I am calling settings again and getting the DB , ( not the default ) value back.

**Comment by moldcraft** [comment]
On my side when I add in `{theme}/functions.php`

```php
function _something_something() {
	fw_get_db_settings_option( 'something', null);
	add_image_size('my-custom-size', 500, 300, true);
}
add_action('after_setup_theme', '_something_something', 9);
```

I get error

```
Fatal error: Uncaught Error: Call to undefined function fw_get_db_settings_option()
```

**Comment by moldcraft** [comment]
Maybe better to use the `fw_init` action?

**Comment by danyj** [comment]
you right , I see whats going on , I am using thz_get_theme _options which defaults to my way of getting options if fw is not init 

> Maybe better to use the fw_init action

this is real catch 22 , 

idea behind this is to  have add_image_size  set in theme admin and let admin add new sizes there which works fine for **adding new sizes,** 

the problem is to **get the list** of all default and custom sizes  for image size select choices population, 

this works everywhere else except the theme admin since add_image_size and the admin are on the same hook. hard one and no it is not a bug
