### ISSUE TITLE
How to add custom Icons for Markers

### ISSUE THREAD

**Issue by dobromir-hristov** [ThemeFuse/Unyson#242]
I wanted to share how to add Custom Map Pin Icons.
Note: Dont edit directly the shortcode, but override the Map shortcode in your theme. 
File: class-fw-shortcode-map.php
Where load_data func is bellow the thumb:
```php
private function load_data()
.....
'thumb' => array(
	'label'       => __('Location Image', 'fw'),
	'desc'        => __('Add location image', 'fw'),
	'type'        => 'upload',
),
'icon' => array(
	'label'       => __('Pic Icon', 'fw'),
	'desc'        => __('Add Marker Pin image', 'fw'),
	'type'        => 'upload',
)
```
then in _callback_get_custom_locations  under the thumb
```php
$result[$key]['icon']  = fw_resize(wp_get_attachment_url(fw_akg('icon/attachment_id', $row)), 64, 64, true);
```
I have added 64px because that is a pretty nice size. It can be set dynamic if added as an option above.
Then in the JS add.
File: scripts.js
```js
var marker = new google.maps.Marker({
	position: gMapsCoords,
	map: map						
});
if ('undefined' !== location.icon && location.icon.length) {
	marker.setIcon(location.icon); //Check if Icon exists and add it to the Marker
}
```
Thought sharing would help someone. Maybe it can find its way into the framework :)

**Comment by dobromir-hristov** [comment]
Apparently 
```php
$map_shortcode = fw_ext('shortcodes')->get_shortcode('map');
```
gets the `class-fw-shortcode-map.php` of the original extension and not the extended one from framework-customizations.
What is the proper way to get my edited `class-fw-shortcode-map.php`  and use its _get_picker_dropdown_choices(), _get_picker_choices(),
Thank you.

**Comment by dobromir-hristov** [comment]
Any news on the question above ?

**Comment by GheorgheP** [comment]
Hi,

Sorry, for a such big delay.

You cannot overwrite the shortcode class. Just create a new shortcode, and the current one add in the banned list:
```php
/**
 * @param array $shortcodes
 *
 * @return array
 */
function _filter_disable_map_shortcode( $shortcodes ) {
	$shortcodes[] = 'map';
    return $shortcodes;
}

add_filter( 'fw_ext_shortcodes_disable_shortcodes', '_filter_disable_map_shortcode' );
```
