### ISSUE TITLE
ShortCode not render properly

### ISSUE THREAD

**Issue by gleisonfelipe** [ThemeFuse/Unyson#2420]
Even with the plugin up to date the shortcodes doesnt render properly in frontend

![screenshot-d1lado com br 2017-02-23 01-44-49](https://cloud.githubusercontent.com/assets/15713186/23245262/f528eeac-f969-11e6-81b1-a2d747c72d07.png)

**Comment by moldcraft** [comment]
Hello,
Please contact the theme author, perhaps the theme must `do_shortcode()` for that text.
