### ISSUE TITLE
Backup download Zip file error

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson#2423]
As of lately (today for me) the zip files downloaded from the Backups screen will not unzip. I am on a Mac and my Archive Utility gives an error:

`Unable to expand "fw-backup-....zip" into "Downloads".`

I have also attempted to unzip the file using the Terminal, which produces this error:

```
End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/joeanderson/Downloads/fw-backup-2017_02_23-19_26_04-2.0.22.zip or
        /Users/joeanderson/Downloads/fw-backup-2017_02_23-19_26_04-2.0.22.zip.zip, and cannot find /Users/joeanderson/Downloads/fw-backup-2017_02_23-19_26_04-2.0.22.zip.ZIP, period.
```

This may have something to do with #2044... Although, that seems to be a database issue.

Thanks!

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Backups-Extension/releases/tag/v2.0.23

**Comment by meta4creations** [comment]
Great work, as always!
