### ISSUE TITLE
Visual Page Builder content disappearing after clicking 'Update'

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#2424]
Hello,

I have a user who is installing some demo content, then when clicking 'Update' in the page builder (without changing anything), when the page reloads the content has all disappeared. Could you give me some pointers as to what to look into here please, I'm not really sure what could be causing this.

Thanks in advance

**Comment by moldcraft** [comment]
Hello,

Set [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/ce9e7f307d79c9aaa17c7aeee1649692224e058b/includes/page-builder/class-fw-option-type-page-builder.php#L22) to `false` and check if it helps

**Comment by martinburdon** [comment]
Thanks for the reply, I'll see if I can get some FTP details from them to change it and give it a try 👍

**Comment by martinburdon** [comment]
Hey @moldcraft, unfortunately that didn't make a difference.
What is odd is that after everytime you install the demo content, then go to the WP admin area, you're asked to update the database as in this screenshot:
![image](https://cloud.githubusercontent.com/assets/4599099/23411391/758ab7bc-fdd2-11e6-8c80-573086d1d45b.png)
I wonder if this is causing the issue, any ideas?

I can supply login and FTP details if needed.

Cheers

**Comment by GheorgheP** [comment]
Does this happen every time you click on the Update button?
If you can provide the dashboard and ftp details would be great.

About the demo content install update notice, this is normal, no need to worry.

**Comment by martinburdon** [comment]
Yeah it's every time you click update.

So you install demo content
Go to home page in editor
Without even changing anything, hit update
All page content is gone

Thanks, could you give me an email to send the details to please.

**Comment by GheorgheP** [comment]
Please send the details on pisarenco.gh@gmail.com
Set the subject: **Unyson Page Builder Problem** also provide al ink to this issue in the message.

**Comment by martinburdon** [comment]
Thanks, just sent them 👍🏼

**Comment by GheorgheP** [comment]
Hi @martinburdon 

I investigated the problem, but it seems that the homepage page-builder json is not valid. Are you sure that this content worked properly before? As the JSON format is corrupt.

The only recommendation I have is to re-build it.
Or you can parse JSON manually and fix it.

**Comment by martinburdon** [comment]
Thanks for looking into that @GheorgheP 

Yep it worked properly before, infact it works properly right now I've just tried it with a local install of the theme, my local install and my customers both pull the demo content from the same place on my server so you'd think if it was corrupt JSON that I would see the issue on all instances of my theme 🤔

**Comment by martinburdon** [comment]
Also, I've just noticed that if you go to the page in the Visual Page Builder before the content is cleared, if you click into one of the custom shortcodes, the popup doesn't show the form but you get the error **Error: Wrong options** instead. Again, this isn't happening locally when I'm testing or on any other sites as far as I can tell

**Comment by martinburdon** [comment]
Hey @GheorgheP, do you have any other ideas on this?

I've tried even creating pages from scratch (not using the content import) and when you hit update/publish it clears the content.

I first tried adding a section and column inside, hit update and the section/col remained.
I then added a background image to the section in its settings and hit update, that then caused the content to be cleared.

Not sure if that helps at all?

Thanks

**Comment by danyj** [comment]
> ...JSON that I would see the issue on all instances of my theme

check execution limit and Max Input Vars on your customer server,  

I am leaning toward Max Input Vars,  if your JSON is big and he has default of 1000  than it will cut off after the limit and you will endup with missing data.

**Comment by danyj** [comment]
see this https://github.com/ThemeFuse/Unyson/issues/1883

**Comment by danyj** [comment]
in my case it was not returning anything and I am on nginx, it would not show errors , no bugs , just missing bunch of data until I finally  changed the  max_input_vars on live server. Locally as you say , no issues at all.

**Comment by danyj** [comment]
sorry for multi posts but see this https://github.com/ThemeFuse/Unyson/issues/1545#issuecomment-218143531 ,  that is when I had the missing data issue. Just trying to help since you been on this one for a while now.

**Comment by martinburdon** [comment]
Thanks for the input @danyj, all thoughts welcome 👍 
I'll check that out.



>I've tried even creating pages from scratch (not using the content import) and when you hit update/publish it clears the content.

> I first tried adding a section and column inside, hit update and the section/col remained.
I then added a background image to the section in its settings and hit update, that then caused the content to be cleared.

Could `max_input_vars` be the issue even considering the above?

**Comment by danyj** [comment]
yes , because your builder can have well over 1000 input vars and his server limits this ,  see also post_max_size  which again is 1000 by default and a full blown builder page with not carefully tought out  option arrays will kill that in a second.  I had this issue so I moved over 50% of options in to addable popups to lower the data size.  Il digg tough my post with this issue . few min

**Comment by martinburdon** [comment]
Hmm, looks like `max_input_vars` is set to 5000 🤔 
`post_max_size` is set to 64M

**Comment by danyj** [comment]
try this filter if you dont have it on 

https://github.com/ThemeFuse/Unyson/issues/838#issuecomment-173174261

**Comment by martinburdon** [comment]
Do you mean I should add `add_filter('fw_db_big_data_update_enable', '__return_true');`?
Where should this be added, in `unyson/framework/helpers/database.php`? I don't seem to be able to see any kind of reference to `fw_db_big_data_update_enable` throughtout Unyson 😕

**Comment by danyj** [comment]
nope , in you hooks or functions 

I added this n theme hooks.php



	/**
	 * Big data builder update
	 * https://github.com/ThemeFuse/Unyson/issues/838
	 */
	function _thz_filter_big_updates() {
		return true;
	}
	add_filter( 'fw_db_big_data_update_enable', '_thz_filter_big_updates' );


after that I had no more page save limit issues

**Comment by martinburdon** [comment]
Added that in my theme `hooks.php` but no luck I'm afraid 😞

**Comment by danyj** [comment]
>I don't seem to be able to see any kind of reference to

hmmm , you seem to be right 
is not in database.php anymore 


@moldcraft    has this

https://github.com/ThemeFuse/Unyson/blob/163454379a82d2d5fdbbe1d4b9ebd0be8ab755db/framework/helpers/database.php#L766 

 been removed ?

**Comment by danyj** [comment]
ok , seems like is in builder core now , 
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/search?q=fw_db_update_big_data&type=Commits&utf8=%E2%9C%93

**Comment by martinburdon** [comment]
hey @danyj, thanks for your help so far. If I'm not being too cheeky would you mind taking a look at the site if I send you over some details? This still has me scratching my head 😕

**Comment by danyj** [comment]
@martinburdon  sure ,   themezly at gmail

**Comment by martinburdon** [comment]
Thanks @danyj, just sent them over 👍

**Comment by danyj** [comment]
got it , login in , will reply back

**Comment by danyj** [comment]
admin pass is no go

**Comment by martinburdon** [comment]
hmm, wonder if it's been changed or removed. I'll ask and get back to you 👍

**Comment by martinburdon** [comment]
He said he's completely dumped the database and started from scratch and all seems to be working for him now.

Thanks for all the help guys 👍  appreciated!
