### ISSUE TITLE
Pricing table description error

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson#2426]
Hello , 
when I use the built-in shortcode table as a pricing table and add a description column I get this error :

`Notice: Undefined index: textarea in .../unyson/framework/extensions/shortcodes/shortcodes/table/views/pricing.php on line 24`

**Comment by GheorgheP** [comment]
I just made some test and wasn't able to reproduce this.
Can you create a content backup so I could test this on my local machine?

**Comment by toleabivol** [comment]
Did you try with a button row maybe ?
Here is the content backup.
[fw-backup-2017_03_06-15_31_02-2.0.23.zip](https://github.com/ThemeFuse/Unyson/files/821591/fw-backup-2017_03_06-15_31_02-2.0.23.zip)
