### ISSUE TITLE
What  has been escaped?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2429]
Trying to cleanup everything and need to know what is escaped so that I dont do  double escaping. 

Page builder elements config.php values?
Options titles, desc , help ?

I know that tabs titles have been escaped 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/container-types/tab/view.php#L16

box seems like it is not 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/container-types/box/class-fw-container-type-box.php#L30

so can we gather a list please.

**Comment by danyj** [comment]
for options seems like labels are escaped but desc and help are not ,

**Comment by Ataurr** [comment]
“late escaping” makes reviewers more efficient, which means customer code is reviewed and deployed faster

https://vip.wordpress.com/documentation/vip/best-practices/security/validating-sanitizing-escaping/#always-escape-late

Better search global with `echo $ `

**Comment by danyj** [comment]
@Ataurr I am mainly talking about backend here but yes the echo $ helps also

**Comment by Ataurr** [comment]
Got it.

The reviewer does not care it's already escaped or not. They Globally search with `echo $` and tell us to escape this :/
Also, Most of the time They don't read the comments >_<

**Comment by andreiglingeanu** [comment]
@danyj After digging this, can you come up with a short list of best practices of escaping?

Everything in `view.php` should be escaped, with some rare exceptions...

**Comment by danyj** [comment]
So far , 

container types titles have been escaped 
http://manual.unyson.io/en/latest/options/introduction.html#containers

as for option this is what I did

```
$options = array(

	'some_option'    => array(
		'type'  => 'some-option-type',
		'value' => '',
		'label'  => __( 'Label', 'fw' ), // already escaped
		'desc'  => esc_html__( 'Desc', 'fw' ),
		'help'  => esc_html__( 'Help', 'fw' ),
		
		// addable-popup 
		'popup-title' => esc_html__( 'Popup title', 'fw' ),
		
		// addable-popup ,addable-box, addable-option
		'add-button-text'=> esc_html__( 'Button', 'fw' ),
		
	)
);
```

in  custom option view.php  you need to escape on your own
