### ISSUE TITLE
Icon in Megamenu

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#243]
Hi!
I have 2 main locations for menu:
```php

// This theme uses wp_nav_menu() in 2 locations.
register_nav_menus( array(
	'primary' => __( 'Top Right menu', 'mauris' ),
	'footer' => __( 'Buttom Footer menu', 'mauris' ),
) );
```

I actived megamenu extension and set icon for some menu links but it only showed in Nav with location `primary` . It didn't appeare with other Nav that had different location. 

I tried to change name of location from `primary` to others, It be also hidden.
For the screenshot: 
![screen shot 2015-02-12 at 10 09 19 pm](https://cloud.githubusercontent.com/assets/1773011/6169997/dea02442-b303-11e4-917b-2baf17e888f2.png)

**Comment by danyj** [comment]
see this bud  #233

**Comment by duongancol** [comment]
thank you!
Hope it'll be fixed soon!
