### ISSUE TITLE
ThemeForest soft reject issue

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#2431]
Hello,

Thought I best share this here in case others get the same.
My latest theme has been soft rejected on ThemeForest with the following message:

> When loading files themes should not load the unknown, no arbitrary loading. Now what themes can't do is use the wildcard such as: http://envato.d.pr/9mxh/3vI6agoE see we that, anything can be loaded.
![8](https://cloud.githubusercontent.com/assets/4599099/23414587/c3dd724c-fddc-11e6-8a1f-eccb69ed6d2f.png)

This is from something I copied over from the Scratch theme within init.php
Few questions I have to fix this for my review (and others that might face the same).

1. What does it do?
2. How can we change it so that it satisfies the above soft reject message?

Thanks

**Comment by andreiglingeanu** [comment]
1. It is loading every php file from the `$path` variable.
2. You can create an `init.php` file and require each needed file manually from there.

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Theme-Includes/issues/1

**Comment by danyj** [comment]
who is the reviewer?

**Comment by danyj** [comment]
this should be changed , there are other ways than wildcard since this is second time they reject it ,  

we could check for file php extension and than included it. this wold remove the use of wild card since it is obviously bothering TF.

**Comment by martinburdon** [comment]
Thanks for that link @danyj 
So from my understanding that's loading everything from the `includes` directory.
From this screenshot of my theme dir, you can see the only file I have in there is `content-width.php`.
So am I right in thinking I can just replace the contents of `include_all_child_first` and link direct to the `content-width.php` file?

![image](https://cloud.githubusercontent.com/assets/4599099/23416781/85464bb4-fde4-11e6-9054-98f3a7b6a9a6.png)

**Comment by martinburdon** [comment]
@danyj @andreiglingeanu while we're on the subject of TF soft rejects. I have another I wonder if you guys could help me with.

It's regarding `Theme needs to properly load files, but also to be consistent as well.` and quotes using the likes of `get_template_directory`, `get_template_directory_uri` etc.

I think the reviewer may be talking about the following function using `basename` and `dirname` but I don't seem to be able to successfully replace them.
Have you guys come across this before?

```
	private static function get_rel_path($append = '')
	{
		if (self::$rel_path === null) {
			self::$rel_path = '/'. basename(dirname(__FILE__));
		}

		return self::$rel_path . $append;
	}
```

**Comment by danyj** [comment]
I have no idea what he meant by that

**Comment by danyj** [comment]
why dont you try to copy https://github.com/ThemeFuse/Theme-Includes/issues/1#issuecomment-248822022

or event better ask @Ataurr  what he did to get it approved.

**Comment by martinburdon** [comment]
Yeah so I've got the first issue sorted, the wildcard from copying that thread. I ended up just replacing the function with `	self::eternityparent_include_isolated('includes/content-width.php');`.

In regards to the question above about `basename` and `dirname`, @Ataurr how did you get around that if you don't mind me asking? Looks like we had the same reviewer.

**Comment by martinburdon** [comment]
Oh actually, I've just noticed the other question was solved in that thread. My bad 😄 

I'll get this sorted and re-submitted, fingers crossed!

Thanks for the help and quick reply guys, much appreciated 👍

**Comment by duongancol** [comment]
@martinburdon Here you go 

```
private static function academica_get_rel_path($append = '')
	{
		if (self::$rel_path === null) {
			self::$rel_path = '/'. basename(get_template_directory().'/inc/');
		}

		return self::$rel_path . $append;
	}
```

**Comment by danyj** [comment]
see this , I made a small change that you might be able to use and still make the includes folder function as it was intended 

https://github.com/ThemeFuse/Theme-Includes/issues/1#issuecomment-283317371

**Comment by danyj** [comment]
congrats!, where is the link ?

**Comment by martinburdon** [comment]
Thanks - https://themeforest.net/item/eternity-responsive-wedding-wordpress-theme/19476183
Eagerly awaiting my first sale, hate this bit haha 😬

**Comment by danyj** [comment]
> Eagerly awaiting my first sale,

it will come , 

how long did you work on this ?

**Comment by martinburdon** [comment]
It's hard to say, I have a job I work 9-5:30 and a 3 year old so I do bits when I can on a night or over my lunch hour at work.

The last theme I released was in May (my first with Unyson), so I set up kind of a theme framework and shortcodes for my themes so this one didn't take as long as my first.
I'm going to try and push the design a bit on my next theme, once I have a design (the hardest bit) then it shouldn't take too long to get it into code.

**Comment by danyj** [comment]
you lucky , most of us are working on monsters, @andreiglingeanu  , @ivandotv ,@duongancol  and I are in for 1-2 years by now and not done lol :) 
congrats and good luck!

**Comment by martinburdon** [comment]
Haha thanks, all the best to you guys too 👍

How come it's taking you that long? Are you's going for a large multifunctional type theme?

**Comment by danyj** [comment]
> How come it's taking you that long?

We have Joomla templates club with 150 templates that we need to move to WP, so we must think of all possible scenarios plus limit the coding to minimum.

**Comment by Ataurr** [comment]
Congrats mate :)

Dan what's your username in TF?

**Comment by martinburdon** [comment]
Ah I see, good luck!

I remember starting out with themes and Joomla back when I was younger and just getting into all this web dev stuff.

Thanks @Ataurr 👍

**Comment by danyj** [comment]
@Ataurr , themezly ,  nothing there , if you looking for this https://www.youjoomla.com/

**Comment by danyj** [comment]
> When your monster will live?

cant say
working on demos and docs now ,  the docs are big time pain. 

once out il let you guys know with a HUGEEEEEE post :)  if themefuse team does not mind.

**Comment by Ataurr** [comment]
Don't forget to tag me. ;) I would love to see your monster.

**Comment by martinburdon** [comment]
Same here!

**Comment by duongancol** [comment]
Congrats @martinburdon ! Nice theme ;)

**Comment by martinburdon** [comment]
Thanks @duongancol :) still waiting for its first sale, been 24 hours now 😬
