### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by CreditRepairConnection** [ThemeFuse/Unyson#2432]
I have a WordPress site with Unyson framework.
I wanted to update to PHP 7. 
I ran the PHP Compatibility plugin: https://wordpress.org/plugins/php-compatibility-checker/ 
I received the following errors:

`FILE: /nas/content/live/tbroker/wp-content/plugins/unyson/framework/extensions/backup/includes/lib/srdb.class.php
-----------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------------
 1196 | ERROR | preg_replace() - /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0
 1201 | ERROR | preg_replace() - /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0
-----------------------------------------------------------------------------------------------------------------`

False positive?

Or... is Unyson framework compatible with PHP 7?

Thanks!

**Comment by danyj** [comment]
it is compatible , im on 7.0.4 and runs without issues , 

as for preg_replace 

https://github.com/ThemeFuse/Unyson-Backups-Extension/search?utf8=%E2%9C%93&q=preg_replace

i dont see any /e modifier .

**Comment by CreditRepairConnection** [comment]
Thanks!

**Comment by danyj** [comment]
wait , what backup version do you have , I dont see that lib in there 

there is actually no lib folder 
https://github.com/ThemeFuse/Unyson-Backups-Extension/tree/a28fcbb4c791c079e55ffde55c7db18f67243419/includes

**Comment by danyj** [comment]
the mentioned class has that issue , https://github.com/interconnectit/Search-Replace-DB/blob/master/srdb.class.php

but it is not used by Unyson backup

**Comment by CreditRepairConnection** [comment]
Plugin running: Version 2.6.15

**Comment by danyj** [comment]
not Unyson , backup , what version

**Comment by CreditRepairConnection** [comment]
Sorry, i don't know what you mean :(  <--- not a dev

**Comment by CreditRepairConnection** [comment]
Oh, the extension. I actually have it deactivated. Trying to find the version. But, I did see that there is an update.

**Comment by danyj** [comment]
go to Unyson, and hover over Backup extension title , the version will be in tooltip

**Comment by CreditRepairConnection** [comment]
Sorry, already updated. V 1.0.13. I can check in staging if you need to know for support purposes.

**Comment by danyj** [comment]
that is bad version 

current is 2.0.23 ,  update all Unsyon extensions before moving to 7

**Comment by CreditRepairConnection** [comment]
K.
