### ISSUE TITLE
"Error: Wrong options" and PageBuilder content not showing after server change

### ISSUE THREAD

**Issue by luisfe7** [ThemeFuse/Unyson#2433]
So I have a couple of issues:

The content I created with the PageBuilder is not appearing on certain pages. For example in the frontpage and others I only see the Header and the Footer. Apparently there's nothing on the main div:
![image](https://cloud.githubusercontent.com/assets/26152825/23532534/bdf43d2c-ff60-11e6-85b2-4e47d4f69398.png)
When I go to edit the page, there is no content on the PageBuilder either, but everything I had shows up on the Default Editor. Thus, if I deactivate the plug-in, the whole content appears without any format/functionality.

And on the PageBuilder of pages that show up fine, I can't edit anything by clicking on the elements because it shows nothing but **"Error: Wrong options"**:
![image](https://cloud.githubusercontent.com/assets/26152825/23532380/122b9094-ff60-11e6-9141-5bf2d41f38f3.png)

CONTEXT:
I had my new WP site at "2017.website.com" and I wanted to put it in place of "website.com".
I swapped them via the Hosting panel (1&1) and changed the WP siteurl and home options, and everything seemed to work well except for the "Error: Wrong options" thing. 
Then I installed the Velvet Blues plug-in to update the URLs (which I thought were the problem), and updated "http://2017.website.com" to "http://website.com", "2017.website.com" to "website.com" and "//2017.website.com" to "//website.com" everywhere but in the GUIDs. That's when the content stopped showing on some pages.

Any help will be greatly appreciated.
Thanks!

**Comment by GheorgheP** [comment]
Do you have the old site still available? I would recommend you to use the [Backups](https://github.com/ThemeFuse/Unyson-Backups-Extension) extension in order to migrate the site.

Here is a good article abut how to use our Backup in order to migrate the site: https://themefuse.com/how-to-move-your-wordpress-site-manually/#unyson_backup_option

**Comment by luisfe7** [comment]
Yes, I probably messed up something in the migration, so I will do a clean one again.

Thanks for the link, just one question: If I just install a clean WordPress on the new site, the Unyson Backups extension will do the whole thing for me? (migrate plug-ins, pages, media, posts, everything?)

Otherwise I'd prefer to do everything manually.

**Comment by GheorgheP** [comment]
Yes, for this you'll have to do a **Full Backup** and the extension will export all content from the datab base and the `wp-content` folder. The **Content Backup** exports the content from the database and the `uploads` folder only.
