### ISSUE TITLE
Create shortcode which can has others inside

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#2436]
Hi,
Just wondering: is there simple/rational way to create shortcode like section/column which can has other shortcodes inside? i.e would be available for drag-n-drop to itself.

didn't google similar questions...

**Comment by andreiglingeanu** [comment]
The most obvious thing is to just copy the `section` shortcode, rename it to something else and see how far you can get just with that. This will involve fiddling around with a lot of JS code and you'll have to understand how to define new page builder item types.

Not quite straightforward but it is totally doable.

**Comment by danyj** [comment]
Doable , everything is prefixed or suffixed with section , https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/master/shortcodes/section

**Comment by onebelarusianguy** [comment]
okay, got it. thanks. can be closed
