### ISSUE TITLE
Unsyon plugin and direct install both causing problem

### ISSUE THREAD

**Issue by fady-mh** [ThemeFuse/Unyson#2438]
Hi,

I tried installing unyson along with the scratch theme and the plugin is not working at all. While i did install all the extension no options are showed e.g columns or anything really. and the wordpress page tab when add new is clicked the place where i add content is broken as the picture shows 
![untitled-4](https://cloud.githubusercontent.com/assets/26221778/23608550/f4901956-027a-11e7-9f6a-1f04ecf3f709.jpg)

**Comment by GheorgheP** [comment]
Does all works properly if you deactivate Unyson?
Or did you try to switch the theme to a default WordPress theme?

Also what php version are you using?

**Comment by fady-mh** [comment]
Yes when I deactivate it, everything works well whether or not I change the theme. My php version is 5.5.12

**Comment by GheorgheP** [comment]
Try to set the `WP_DEBUG` and `WP_DEBUG_LOG` to true to see if you don't get any errors.

**Comment by fady-mh** [comment]
nope. no errors

**Comment by fady-mh** [comment]
Also, if I wanna add a slider or something no options are being displayed

**Comment by GheorgheP** [comment]
Can you provide a link to your site and dashboard login details, and ftp to `pisarenco.gh@gmail.com`

**Comment by fady-mh** [comment]
Its a local host using wamp not a live website/blog

**Comment by GheorgheP** [comment]
Please look in the browser console then if you get any errors

**Comment by fady-mh** [comment]
apparently, there are two errors as shown belo
![untitled-7](https://cloud.githubusercontent.com/assets/26221778/23609200/ed804ff2-027d-11e7-8832-c160212a8e0c.jpg)
w

**Comment by fady-mh** [comment]
The issue has been resolved
