### ISSUE TITLE
Unyson theme -- the Core -- Unable to edit text box and sidebar widget not displaying

### ISSUE THREAD

**Issue by anniedanberg** [ThemeFuse/Unyson#2439]
I moved my site from a subfolder into the root directory. Since that time, I cannot edit pages -- the text box comes up blank (see screen capture) my side bar widgets don't display and only one of my 3 footers is displaying. http://anniedanberg.com
![screen shot 2017-03-06 at 12 46 53 pm](https://cloud.githubusercontent.com/assets/26233506/23637177/fc77aed6-028e-11e7-90cd-654e6848b273.png)

**Comment by anniedanberg** [comment]
I've resolved the widgets and footers issue.

**Comment by GheorgheP** [comment]
Let's continue discussion here #1085
