### ISSUE TITLE
Fixed builder header

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#244]
When you build a page with big content, it's inconvenient to scroll up and down while you adding shortcodes.

![s](http://static.md/8429a832df5c89786872a49abc5893f3.png)

**Comment by dobromir-hristov** [comment]
Attach to top sounds awesome. An "add element" button to each section would make it look like every other builder out there, confusing and easy to click by mistake when rearranging.

**Comment by danyj** [comment]
Yes , add element is overrated , the foxed builder makes sense

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/20
