### ISSUE TITLE
Can we fix the post previews?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2441]
Post previews do not work consistently , sometimes you see the change but most of the time you dont. 
Custom post options when changed cannot be seen at all unless you save the post. 
With builder you might see the changes unless you update the post , once you update any further changes are not seen.

**Comment by danyj** [comment]
@GheorgheP  anything on this

**Comment by danyj** [comment]
@andreiglingeanu  we talked about this and if I remember  correctly you said you will have a look.  Can you please try to fix this.

**Comment by danyj** [comment]
@andreiglingeanu  @ViorelEremia   can someone please look at this 

we have page options that simply do not work in preview if you have already save the page once. 

if you create new page and dont save it all previews work , builder , page template switch and page options 
if you save the page , only builder preview works and sometime you have to click on preview up to 3 times to actually see it. 

It has been 7 months since I reported this I think is time that someone takes a look at it.

**Comment by danyj** [comment]
@ViorelEremia   can you please advise why is this not addressed at all? it s a bug reported 8 months ago. What do I need to do to get this acknowledged?

**Comment by ViorelEremia** [comment]
I tested and did not notice any problems, @danyj please test

**Comment by danyj** [comment]
on it

**Comment by danyj** [comment]
Notice: Only variables should be passed by reference in T:\wamp64\www\Creatus\Clean\wp-content\plugins\unyson\framework\helpers\class-fw-db-options-model.php on line 114

**Comment by danyj** [comment]
change , and seems to work

```
if ( is_preview() && is_main_query() ) {
	$item_id = ( $rewisions = reset( wp_get_post_revisions( $item_id ) ) ) && isset( $rewisions->ID ) ? $rewisions->ID : $item_id;
}
```


to 

```
if ( is_preview() && is_main_query() ) {
	$reset_get_rev = wp_get_post_revisions( $item_id );
	$item_id = ( $rewisions = reset( $reset_get_rev) ) && isset( $rewisions->ID ) ? $rewisions->ID : $item_id;
}

```

**Comment by danyj** [comment]
page template switch does not work but builder options and page options seem ok

**Comment by danyj** [comment]
@ViorelEremia  cant help but notice that page load seems bit slower than before is this becuase you are emptying the fw cache or is it just my server

**Comment by danyj** [comment]
@ViorelEremia  GREAT WORK ALL IN ALL!!!!!

**Comment by ViorelEremia** [comment]
Templates for me is working well.
Where is slower in preview or frontend

**Comment by danyj** [comment]
> Where is slower in preview or frontend

frontend

**Comment by danyj** [comment]
OH MANNN MIRACLE!!!! LOVE YOU @ViorelEremia !!!!!!!

we have created templates for user that include complete page options , on one click , now they all work awesome in preview!!!!

**Comment by ViorelEremia** [comment]
No i don't touch query only this function is working for frontend https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/query.php#L0
is_preview

**Comment by danyj** [comment]
just for me the page template switch is not in , but I think that is oki'sh, 

> No i don't touch query

cold well be my server

**Comment by danyj** [comment]
just fix the   passed by reference when you get to it and we seem golden

**Comment by danyj** [comment]
on another install I get 

`Notice: is_main_query was called incorrectly. In pre_get_posts, use the WP_Query->is_main_query() method, not the is_main_query()`

**Comment by danyj** [comment]
```
		global $wp_the_query;

		if ( is_preview() && $wp_the_query->is_main_query() ) {


```

fixes that 

they confused me completely here
https://core.trac.wordpress.org/ticket/25680

**Comment by danyj** [comment]
could you reopen this please , 

I think it needs more tests , every few posts im getting  memory errors , 

lowed memory size of 268435456 bytes exhausted (tried to allocate 8192 bytes) 

`wp-includes\class-wp-query.php on line 626`

**Comment by ViorelEremia** [comment]
@danyj please test

**Comment by danyj** [comment]
on it

**Comment by danyj** [comment]
I get same issue , getting Allowed memory size of 26843545  on every **first time**  preview click , 
New page click on preview

second one recovers,  will test more

**Comment by danyj** [comment]
I updated the content of the affected page and now it seems ok , leave it for now please il do more testing

**Comment by danyj** [comment]
I think is 

`wp_get_post_revisions
`
noticed that if I have an autosave  http://prntscr.com/h9vf0o

it trows error on first preview

try this ,

1. open post with builder 
2. change something 
3. reload the the post edit page so that you get the auto save 
4. click preview

**Comment by danyj** [comment]
oh , and try with  a latest posts shortcode from Themefuse the core ,  

it has 

`$query = new WP_Query($args);`


in view 

that might be the clash with this  

https://github.com/ThemeFuse/Unyson/commit/87bba5ddb4d2352bf3aa04728e06128973ee6ac2#diff-121f963fe59dd04be62beacd8a9219e1R114

**Comment by ViorelEremia** [comment]
I cant reproduce any issue, what errors do yyou have?

**Comment by danyj** [comment]
no errors just memory , i commented out the wp_get_post_revisions( $item_id )  and works , now digging trough revisions to see what the issue is , turning xdbug on

**Comment by danyj** [comment]
ok xdbug says 

`Fatal error: Maximum function nesting level of '256' reached, aborting`

**Comment by danyj** [comment]
which for me lands here 

https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php#L447

**Comment by ViorelEremia** [comment]
https://stackoverflow.com/questions/4293775/increasing-nesting-function-calls-limit
Try to comment wp_get_post_revisions in unysoin after run code in page.php `$reset_get_rev = wp_get_post_revisions( get_the_ID() );
				$item_id = ( $rewisions = reset( $reset_get_rev) ) && isset( $rewisions->ID ) ? $rewisions->ID : $item_id;` 
If error still exists when is no way to solve it is an error php extension.

**Comment by danyj** [comment]
I already set it at 500 and every time it is  the wp_get_post_revisions

> after run code in page.php 


? can you try to explaint that agin ?


you want me to comment this out 


```
		if ( is_preview() ) {
			global $wp_query;

			if ( $wp_query->queried_object && ( $wp_query->is_single( $item_id ) || $wp_query->is_page( $item_id ) ) ) {
				$reset_get_rev = wp_get_post_revisions( $item_id );
				$item_id = ( $rewisions = reset( $reset_get_rev) ) && isset( $rewisions->ID ) ? $rewisions->ID : $item_id;
			}
		}
```

and ?

**Comment by danyj** [comment]
if you mean if I tested without revesions , than yes , 

I set the xdbug limit to 500 ,   with this wp_get_post_revisions

it dies , without it runs 

the confusion is why does it do this on a first click only , if I click again on preview it goes trough

**Comment by danyj** [comment]
look , it just loops trough
![screenshot_28](https://user-images.githubusercontent.com/2340172/32732615-7a80f246-c88d-11e7-9808-f6c0f24c9108.jpg)

**Comment by danyj** [comment]
I think i got it , stupid search limits ,   it was running with everything


![screenshot_29](https://user-images.githubusercontent.com/2340172/32733714-5fb61718-c890-11e7-95a0-31312e405a23.jpg)

**Comment by danyj** [comment]
so the latest version seem ok

**Comment by ViorelEremia** [comment]
So, is working latest version?

**Comment by danyj** [comment]
> So, is working latest version?

yes looks like it , il do more testing today but since I disabled search filter in previews it is working

**Comment by danyj** [comment]
But note this ,  the preview of page options works now as intended , but for the **builder itself** ,  I still **sometimes** must click on preview 2-3 times to see the change. Maybe refreshing the nonce ?

**Comment by ViorelEremia** [comment]
The nonce is updated automatically. I can't reproduce that. Maybe you have something that I dont have

**Comment by danyj** [comment]
@ViorelEremia  this preview orks well but only if page/post is built with page builder , can we make it work on normal pages?

**Comment by danyj** [comment]
And in portfolio extension page options or builder previews do not work , we must save to see them
