### ISSUE TITLE
Tablepress Conflict

### ISSUE THREAD

**Issue by robertthought** [ThemeFuse/Unyson#2444]
Hi Everyone

The tables provided with the Unyson are very limited. We need to use TablePress in order to create the correct format for our pricing

After getting tablepress to load, we are getting 

> 
Warning: Invalid argument supplied for foreach() in printinghut.com/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/table/class-fw-shortcode-table.php on line 54

Example below
http://d.pr/i/zxDN

Does anyone have any insight on this?

**Comment by danyj** [comment]
that is shortcode name clash , they also use [table  shortcode ,  http://prntscr.com/ehjo05,  try this since you are not using unyson table  shortcode

/** @internal */
function _filter_disable_shortcodes($to_disable)
{
	$to_disable[] = 'table';
	return $to_disable;
}
add_filter('fw_ext_shortcodes_disable_shortcodes', '_filter_disable_shortcodes');

**Comment by robertthought** [comment]
Hi @danyj Thanks for your help!

What / Where would I paste this code?

Thanks!

**Comment by danyj** [comment]
in theme functions.php

**Comment by robertthought** [comment]
@danyj no luck with that :(

Does this look right? http://d.pr/i/13uTD

Thanks!

**Comment by danyj** [comment]
looks right , when you go in page builder do you see table shortcode?

**Comment by robertthought** [comment]
Hmmm seems to have removed the error. Now the only way to use TablePress is with the default editor, not the visual editor. 

Any idea how to use table press in Visual Editor?

Thanks for all your help!

**Comment by danyj** [comment]
you cant  have 2 shortcodes with same name , especially cant use tablepress shortcode  in unyson page builder unless you make shortcode for it, only way you might be able to use it is via text shortcode trough the editor if tablepress has shortcode built in it

**Comment by robertthought** [comment]
Makes sense, is there  an easy way to make a **TablePress** shortcode for Unyson?

If I use the Content Element > Text and insert the short code. It is displaying like this when published

http://d.pr/i/mce4

**Comment by robertthought** [comment]
Anyone have any idea on this?

Just need to figure how to get this to display in visual editor

See below
http://d.pr/i/QiQJ

**Comment by robertthought** [comment]
Does anyone know a solution for this? Or is anyone available for hire to fix this?

**Comment by GheorgheP** [comment]
If you want to have the Table Press table shortcode in Unyson.
You have to overwrite the current table shortcode options and view.

You can start from the Shortcode Extension documentation: http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content

**Comment by KeesCBakker** [comment]
You can disable the table using the following code;

```
function _filter_theme_disable_default_shortcodes($to_disable) {
    $to_disable[] = 'table';

    return $to_disable;
}
add_filter('fw_ext_shortcodes_disable_shortcodes', '_filter_theme_disable_default_shortcodes');
```
You can add it to the functions of the theme or install a plugin to add it dynamically as a function (https://nl.wordpress.org/plugins/my-custom-functions/).

**Comment by point111** [comment]
https://tablepress.org/extensions/table-shortcode/ - Change the [table] Shortcode

Installed as a plugin. After setting, [table id = 1 /] will change to [tp_table id = 1 /].
ATTENTION! If you have TablePress tables hosted on your site, you need to update their Shortcode.
