### ISSUE TITLE
Problem include a stored template and reuse it in other templates.

### ISSUE THREAD

**Issue by Rosherh** [ThemeFuse/Unyson#2446]
I apologize if already was such a topic. But I have not long started to learn this framework and encountered a problem.
Severstal section with custom components, I saved this section and add name section-service.tpl.
 Can I somehow reuse this piece saved template in other .php files? For example, fw_render_template_part('name_template_part');
Thanks!

**Comment by Ataurr** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/33#issuecomment-131866126
