### ISSUE TITLE
fw_resize not work any more.

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#2447]
Very recent versions of wordpress (From 4.7.1) I found that the function fw_resize never work anymore. It's my favorite function!

**Comment by GheorgheP** [comment]
I'm on WP 4.7.3 and just tested and all works fine.

Could you provide more info? Do you get any errors?

**Comment by duongancol** [comment]
@TrangDinhVan when you change the post thumbnail size image, you should use [this plugin](https://wordpress.org/plugins/regenerate-thumbnails/)

**Comment by TrangDinhVan** [comment]
Ah, sorry for not tested twice before making this thread. Ah, this case I do not use thumbnail size and other sizes, I removed all the image sizes and just use FW_RESIZE where needed.
1. If I create posts and upload the images manually, then the fuction FW_RESIZE will work properly with these images.
2. If I create posts and upload the images by tool, this is a plugin I wrote myself to get sample posts from other site, the PHP script I used to get the images from url and then upload them to WordPress Library here: http://wordpress.stackexchange.com/questions/107346/download-an-image-from-a-webpage-to-the-default-uploads-folder/107352#107352 . Then, the function FW_RESIZE will never work with these images, maybe it relates to the file permission.

**Comment by TrangDinhVan** [comment]
Okay, we should use function media_sideload_image to get the image from url to WordPress Library instead of the function from here: http://wordpress.stackexchange.com/questions/107346/download-an-image-from-a-webpage-to-the-default-uploads-folder/107352#107352
