### ISSUE TITLE
Long server wait times across two different hosts

### ISSUE THREAD

**Issue by Brendon-Mariposa** [ThemeFuse/Unyson#2448]
I've been experiencing long server wait times on my sites when unyson is enabled. This is a problem across two different sites both hosted with separate hosts.

(for reference, my current WP theme is Reel Story by Themefuse updated to the current version 1.6)

Here are the URLs of both of these sites:
http://e89.60f.mwp.accessdomain.com/
http://trianglejinc.com/

Here are some screenshots of speed tests run through gtmetrix for both domains, with and without unyson enabled.

http://e89.60f.mwp.accessdomain.com/

With Unyson

![with-unyson](https://cloud.githubusercontent.com/assets/26418623/23920774/5a444986-08d2-11e7-9496-57b31b6ea8b5.PNG)

Without Unyson

![without-unyson](https://cloud.githubusercontent.com/assets/26418623/23920795/6b68a81a-08d2-11e7-94db-8a6e66ae01de.PNG)

http://trianglejinc.com/

With Unyson

![with-unyson2](https://cloud.githubusercontent.com/assets/26418623/23920813/8023a386-08d2-11e7-9e52-9483dc8a3fb2.PNG)

Without Unyson

![without-unyson2](https://cloud.githubusercontent.com/assets/26418623/23920817/85dbf832-08d2-11e7-8f7d-8c20959e69f4.PNG)

Of course, the issue in question is the top-most bar in those screenshots. With unyson enabled, I'm seeing a significant increase in server wait time.

-------------------------------------------------------------------------------------------------------------------

Through a little digging myself, I think I've pinned this down to a caching issue.. On one domain, http://trianglejinc.com/ I was able to get the following results by introducing the WP-Super-Cache plugin into the installation:

![with-unyson-and-cache](https://cloud.githubusercontent.com/assets/26418623/23920915/f1ecf008-08d2-11e7-8f94-1c34722bbd8e.PNG)

But, even with this caching solution, I am still experiencing inconsistent page speed across this entire domain. Sometimes it'll load fast, sometimes it'll take forever. 

-------------------------------------------------------------------------------------------------------------------

I considered testing with different themes, but decided against it when I discovered that I could get these sorts of readings from a separate site of mine using the exact same setup (unyson+reel story theme) on a third hosting platform:

![with-unyson-seperate-host](https://cloud.githubusercontent.com/assets/26418623/23921549/65e6390e-08d5-11e7-8300-bf64606c3f27.PNG)

This is the ideal performance I'd expect from unyson, and these results lead me to believe this is indeed a hosting issue with the former two hosting providers. HOWEVER, I'm not sure how to approach this issue with these hosting companies.. and am not 100% certain this is THE issue.

Some guidance on this issue would be greatly appreciated - I am willing to provide credentials for investigation if needed.

**Comment by danyj** [comment]
the best test is the one without the theme , 

disable the theme and test page speed , leave unyson on and make a page with default unyson shortcodes 
if is faster without the theme based on unyson than check the theme loops , and  first check server error logs

**Comment by danyj** [comment]
waiting is more than half of the load is it is server performance http://prntscr.com/ek1l57

**Comment by Brendon-Mariposa** [comment]
Thank you for the response. I will try this tomorrow and get back to you
ASAP.

**Comment by Brendon-Mariposa** [comment]
Okay - I've tested with a default theme and the results are significantly better. However, I'm not sure how to check the theme loops, nor do I think this is 100% a theme problem. 

As I pointed out above, I have a similar site with the same theme and unyson installed that does not exhibit these same issues (on a different host). Is there any strong evidence that I can bring to the hosting companies of the problem sites that will help them help me fix this problem?

**Comment by danyj** [comment]
look here , if same theme , same homepage and same demo loads here in 980ms 

http://demo.themefuse.com/reel-story/

than it is hosting

**Comment by Brendon-Mariposa** [comment]
Okay. Please keep this ticket open for now (if not against the rules). I'd like to discuss this with the hosting providers and bounce back any issues they crop up.

**Comment by Brendon-Mariposa** [comment]
After some more investigation, we've discovered that our long server wait times are caused by our homepage setting cookies for non-logged in users and, therefore, causing cache misses.

We've narrowed down this issue with the PHPSESSID cookie assignment to the unyson plugin and were wondering if this is something we can prevent or disable so we can better address these long server wait times.

**Comment by Brendon-Mariposa** [comment]
Does anyone have an answer for this? Can we get someone assigned here to help?

**Comment by GheorgheP** [comment]
What file and line specifically you refer?

**Comment by Brendon-Mariposa** [comment]
I'm not 100% - but I think the PHPSESSID cookie is assigned by the "class-fw-session.php" file.

Is there any edit that can be made so that non-admin or non-logged in users can be excluded from the cookie setting?

**Comment by GheorgheP** [comment]
Hmmm, interesting why server is creating the sessions file so slow, this looks more like a server issue.
We cannot disable the session as we are using it.
Sure, there is a good point to review, but at the moment this is not possible.
