### ISSUE TITLE
Missing page attributes when creating  a page

### ISSUE THREAD

**Issue by vikramjb** [ThemeFuse/Unyson#2449]
Hi

I installed the Unyson plugin and got all the extensions loaded. When I go to create a new page, I see only three options as Page Attributes

![image](https://cloud.githubusercontent.com/assets/191545/23928642/f64ecdea-0974-11e7-8a9d-cef1df09bfef.png)

However, in most examples that I find online, I see couple of other options. Am I missing something here os is this how its supposed to be ?

**Comment by GheorgheP** [comment]
This doesn't have to do anything with wordpress. You need to create page templates and they will appear in this list.
Yes most of the developers that use Unyson create many page templates, for page with Page Builder, for page without Page Builder, for Full Width Builder pages, for Blank templates... But by default Unyson doesn't provide any additional page templates, this depends only on theme developer.

Here you can find a detailed article about [Creating Custom Page Templates in WordPress](https://premium.wpmudev.org/blog/creating-custom-page-templates-in-wordpress/)

**Comment by vikramjb** [comment]
Thank You @GheorgheP
