### ISSUE TITLE
Update Google Fonts json to the latest version

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#245]
> @azharijelek
> Hi, I think we should update google font .json file. Because I can't find few fonts such as merriweather, > fairplay display, etc. Though I can add them manually by filtering fw_google_fonts, but that'd be better if > the core plugin using the latest google fonts database.

**Comment by thednp** [comment]
Please make sure to include all the fonts' glyph data such as <strong>character sets</strong>, font-style, etc.

Thank you

**Comment by thednp** [comment]
Any news on this?

**Comment by sergiubagrin** [comment]
@thednp 

@valeriuzdrobau will be on monday and we will analyse this issue/feature

**Comment by thednp** [comment]
@sergiubagrin I have this done, I have a custom option type with included gfonts file updated to latest. Just needs a small fix with repopulating the saved variant and subset.

So my option type is called webfonts, it uses:
* family
* variant
* subsets (this can also be improved as I have it, it will need to be a multi-select or checkbox, so users can select more than one subset)

Interested? Drop me a line.

**Comment by azharijelek** [comment]
Hi @thednp ... would you like to share your own option type?

**Comment by thednp** [comment]
I would give it to the developers to update theirs if they want. It may not suit your needs.

**Comment by sergiubagrin** [comment]
send a pull request and we will analyse it thanks

**Comment by thednp** [comment]
@sergiubagrin, my option type is not called typography anymore, but webfonts, and does not include standard fonts, for that I created a separate option type because it addresses specific settings as they don't have any way to control the charset for instance.

**Comment by sergiubagrin** [comment]
@thednp - ok. We will analyse what to do with Google Fonts in future from Typography option. From my point of view 600+ fonts is more than enough. Maybe to use a custom option with specific fonts than to add all fonts just to be in this list.

**Comment by thednp** [comment]
Here you go, I implemented my custom fields into the framework and I fully tested, please take a minute and test and let me know.

https://github.com/ThemeFuse/Unyson/pull/288

**Comment by thednp** [comment]
@azharijelek 

Please download my trunk version and test it out, let me know how it goes.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1243
