### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson#2451]
Functions like `fw_akg`, `fw_get_db_extension_data`, `fw_get_db_post_option`... should pass the `$default_value` via `fw_call()` on return.

Why so? Usually developer do something like this:

```
fw_get_db_post_option(
	get_the_ID(),
	'enable-image',
	fw_get_db_settings_option( 'posts/enable-image', true )
);
```

This is a normal usage as in case that option is not defined for that specific post, you may have a settings option that enables for all. The problem is that the `fw_get_db_settings_option( 'posts/enable-image', true )` will be always called regardless to the fact that the option is defined in post or not, so we can make this works lazy using the code like this:

```
fw_get_db_post_option(
	get_the_ID(),
	'enable-image',
	fw_callback( 'fw_get_db_settings_option', array( 'posts/enable-image', true ) )
);
```

Or for **PHP 5.3>**:

```
fw_get_db_post_option(
	get_the_ID(),
	'enable-image',
	fw_callback( function () {
		return fw_get_db_settings_option( 'posts/enable-image', true );
	} )
);
```

So the `fw_get_db_settings_option` will be called only if the post option will be `null`.

**Comment by GheorgheP** [comment]
Now you can even do this:

```
fw_get_db_post_option(
	get_the_ID(),
	'enable-image',
	function () {
		return fw_get_db_settings_option( 'posts/enable-image', true );
	}
);
```

No need to wrap the closure in `fw_callback`.

**Comment by danyj** [comment]
so basically `fw_call  `is used only if requested value is null right ?

**Comment by GheorgheP** [comment]
Yes
