### ISSUE TITLE
Links replacement

### ISSUE THREAD

**Issue by isloboda** [ThemeFuse/Unyson#2455]
Hi!

Moved website from http to https, all links were change directly in database and through "better search replace" plugin but images that are set up as section browser keep loading from http (http://prntscr.com/ekfi7j). It gets to https but only when you re-add image.

Question:
Where links are stored? Because changing each image is takes quite a lot of time

Thanks

**Comment by danyj** [comment]
you should have used demo
http://manual.unyson.io/en/latest/extension/backups/index.html#content

**Comment by isloboda** [comment]
Any way to replace links now?

**Comment by GheorgheP** [comment]
Yes, is possible. I usually use this script: https://interconnectit.com/products/search-and-replace-for-wordpress-databases/

The links in page builder are escaped so if the link looks like this: `http://mysite.com/wp-content/uploads/2017/03/testimage.jpg`, in page builder it woul looks something like this:  `http:\\\/\\\/mysite.com\\\/wp-content\\\/uploads\\\/2017\\\/03\\/testimage.jpg`, but I cannot tell how it specifically will be as it depends on nesting level, but you don't need to worry about that.

Using the provided tool above you cna search and replace using regular expressions.
You need to search for this `http:([\\]*\/[\\]*\/mydomain\.com)` and replace with this `https:$1`.

Sure you will replace the `mydomain` with your domain name and the `.com` with your [TLD](https://en.wikipedia.org/wiki/Top-level_domain) in case it is not `.com`

First I highly recommend to use the `Dry run` option to preview what will be replaced and with what, and all is fine, you can use the `Live run` option.

![](https://static.md/bd0508261f25f3f1f8fc9057ebea0da9.png)

**Comment by andreiglingeanu** [comment]
The official way of doing `search-replace` in the DB is by using the [`wp search-replace`](http://wp-cli.org/commands/search-replace/). It was developed and optimized just for that. Use it. And yes, it comes with a support for regexes too.
