### ISSUE TITLE
When ever WordPress updates, unyson extension get inactivated

### ISSUE THREAD

**Issue by ansfazi** [ThemeFuse/Unyson#2458]
Hi,

I have been facing this issue many times. When ever my WordPress get updated. Unyson extensiono get inactivated.

Here is the screenshot.
![screen shot 2017-03-16 at 11 12 44 pm](https://cloud.githubusercontent.com/assets/9020387/24012106/a3c21d04-0a9e-11e7-9fb3-585a1ded21ba.png)

**Comment by GheorgheP** [comment]
They are deactivated or entirely removed?

Can you send to me the DataBase and entire WordPress installation folder so I could test?
You can send them on `pisarenco.gh[[at]]gmail.com`

**Comment by kaxigt** [comment]
I have the same problem in a MU install.

**Comment by ansfazi** [comment]
@GheorgheP I have enabled it, let me check if i have any setup with same problem

**Comment by dmbostan** [comment]
As an idea, you can try [TGM Plugin Activation](http://tgmpluginactivation.com/). This way, you can force Unyson or any other plugin stay active.
