### ISSUE TITLE
Feedback Extension: ability to reply

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2461]
We would like to use the Feedback extension to give users the ability to rate a certain location. This works fine, but there seems to be no possibility to enable other users to comment on a rating.

The `comment_reply_link()` function isn't working so at the front end I'm not able to generate a link to respond to a comment.

The back-end of the Feedback extension seems to support the ability to respond to a comment, but the comment can't be submitted. When submitting the action gets cancelled and there's almost no feedback apart from a red '1' beneath the comment field (see screenshot).

![schermafbeelding 2017-03-17 om 14 37 03](https://cloud.githubusercontent.com/assets/1815847/24045478/8eefd336-0b1f-11e7-943a-7cdc93ca4aa9.png)

Is this ability obstructed on purpose?

Edit: excuse me for not adding this issue to the Feedback extension repository, I saw too late and can't delete/move this issue now.

**Comment by ViorelEremia** [comment]
I tested with the scratch theme and it is working, I added to file: scratch-parent\framework-customizations\extensions\feedback\extensions\feedback-stars\views\listing-review-html5.php function ```get_comment_reply_link( array( 'depth' => $depth, 'max_depth' => $args['max_depth'] ) )``` all variables are available here in this file. Maybe you forgot to send them in function get_comment_reply_link.
