### ISSUE TITLE
No common class for elements

### ISSUE THREAD

**Issue by AlexandruDoda** [ThemeFuse/Unyson#2465]
The page builder elements do not have a common class that they can be styled through. Sometimes you may wanna have the same margin on all elements or something.

<img width="1179" alt="screen shot 2017-03-18 at 4 00 34 am" src="https://cloud.githubusercontent.com/assets/8274669/24068787/97ac71f8-0b8f-11e7-88e0-57649e71ab1d.png">

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/12b3fc627343bed009cf71b6d5276770cdafef5e
