### ISSUE TITLE
The contact form element does not follow the usual naming structure

### ISSUE THREAD

**Issue by AlexandruDoda** [ThemeFuse/Unyson#2466]
Compared to other elements, apparently the contact form doesn't start with "fw-"

<img width="1179" alt="screen shot 2017-03-18 at 4 00 34 am" src="https://cloud.githubusercontent.com/assets/8274669/24068791/b30a294a-0b8f-11e7-8ed9-c614436965ee.png">

**Comment by GheorgheP** [comment]
I keep the `contact-form` class, as it may be used by themes developers already.

**Comment by AlexandruDoda** [comment]
Wouldn't it be wiser to keep the class but perhaps also add a standardized class to it for consistency?

**Comment by GheorgheP** [comment]
That's what i did there: https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/12b3fc627343bed009cf71b6d5276770cdafef5e
