### ISSUE TITLE
The comments section is affected by Unyson even with the Feedback extension disable

### ISSUE THREAD

**Issue by AlexandruDoda** [ThemeFuse/Unyson#2467]
Original (without Unyson enabled)
<img width="780" alt="screen shot 2017-03-18 at 4 08 38 am" src="https://cloud.githubusercontent.com/assets/8274669/24068831/a4ba9aa4-0b90-11e7-83ff-69e117c0734d.png">

After (with Unyson enabled and no Feedback)
<img width="773" alt="screen shot 2017-03-18 at 4 08 26 am" src="https://cloud.githubusercontent.com/assets/8274669/24068833/ab5e170a-0b90-11e7-8f11-7397e86db588.png">

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/1789

should have been fixed

**Comment by AlexandruDoda** [comment]
The theme I am using alongside Unyson is using a custom comments.php file, but it shouldn't alter anything unless the "Feedback" extension is enabled, correct?
