### ISSUE TITLE
Cannot create backup

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#2469]
Hi guys,

In one of my client sites I just cannot create a backup to export, it just fails constantly. Is there another way I can copy the database? I've pulled a copy of the database and imported it locally but it just breaks the pagebuilder.

https://ibb.co/djrXFa

Thank you

**Comment by klvmedia** [comment]
The host will not install php zip because of "Security" issues, so we cannot create a backup. I was hoping I could copy the code from the default editor like Visual composer but there isn't any displayed.

Any advice would be much appreciated.

Thanks

**Comment by danyj** [comment]
First time I heard of that zip creation is sec issue for the host. Change the host is what I would do.

**Comment by klvmedia** [comment]
Managed to resolve it with wo migrate dB and updating the extensions. Wasn't ideal as I had to manually fix some stuff but did the trick!

Yep, I'll be recommending my client move their site.

**Comment by TrangDinhVan** [comment]
I would like to recommend plug in "All In One WP Migration": https://vi.wordpress.org/plugins/all-in-one-wp-migration/
If it's okay please close this ticket.

**Comment by GheorgheP** [comment]
I'm not sure the plugin is compatible with our Page Builder and will be able to replace the URLs.
