### ISSUE TITLE
Cannot create temporary directory: wp-content/plugins/unyson/tmp

### ISSUE THREAD

**Issue by infotau** [ThemeFuse/Unyson#2470]
Hello,

Its kinda weird that this error appear every now and then, also i see that in your response to the old errors you take the FTP and inspect the error then me as a reader and before i contact you i don't really know how to fix it myself, can you please explain how me or any new one facing the error can fix it ourselves ?

Thanks

**Comment by AlexandruDoda** [comment]
Hey Infotau,

I think it might be related to your server permissions.

Check the following resources which may help:
https://www.ostraining.com/blog/wordpress/file-permissions/
http://stackoverflow.com/questions/18352682/correct-file-permissions-for-wordpress
https://codex.wordpress.org/Changing_File_Permissions

Cheers!

**Comment by GheorgheP** [comment]
I agree with @AlexandruDoda 

In case you are using the [WP Engine](https://wpengine.com/) or something similar to it, you should know that the extensions installation or backups, or demo content install should be made on on staging, as the server configuration has some serious security restrictions on live stage, and other folders except `wp-content/uploads` are usually restricted to be edited, and even `uploads` folder has a lot of limitations.
