### ISSUE TITLE
How to disable sub extension (slider type)?

### ISSUE THREAD

**Issue by zaxap83** [ThemeFuse/Unyson#2471]
Hi! 
I had make own slider type in "/framework-customizations/extensions/media/extensions/slider/extensions", its works fine, but i want to disable some other types from "/framework/extensions/media/extensions/slider/extensions/". How can I do it?
I tried to add manifest.php with "$manifest['display'] = false" to "/framework-customizations/extensions/media/extensions/slider/extensions/bx-slider", but nothing has happened, this type is still wisible on sliders page.

**Comment by GheorgheP** [comment]
There is filter `fw_ext_slider_activated`, where you can choose desired types:

```
function _filter_disable_slider_types( $sliders ) {
	//Disable desired types
	return $sliders;
}

add_filter( 'fw_ext_slider_activated', '_filter_disable_slider_types' );
```

PS: Do not add cofig options in extension `config.php` if they are not specified in the extension documentation.
