### ISSUE TITLE
Any way to create "hidden" shortcode?

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#2472]
What I mean: create shortcode which I will use only as some options storage i.e. using - `fw_ext('shortcodes')->get_shortcode('shortcode')->get_options()` to prevent repeating code in various shortcodes.
I.e. it should be not hooked to any tab in `config.php` and be invisible in Builder, but it's required parameter...
The only I have idea is to create separate tab for this kind of things and hide it through CSS, but it's ugly. Any thoughts?

Thanks

**Comment by GheorgheP** [comment]
A shortcode that is not visible cannot be added or removed as it is not visible, so it doesn't have to do anything with builder, you can add it in builder content during the `save_post` action.

What is the meaning of such shortcode?

**Comment by onebelarusianguy** [comment]
@GheorgheP 
The meaning is in storing options which are repeating from shortcode to shortcode.
So when I'll decide to add something in these options set I will have to do it in each shortcode instead do in one place.

**Comment by GheorgheP** [comment]
In this case I think you need to create a new option type that will store all options in one place. Like the `mailer` options type. And when you edit it in one place, it it updated in all. But in this case it will be updated in all pages, not just in current one.

**Comment by onebelarusianguy** [comment]
@GheorgheP yeah, this is the right way. Can be closed.
