### ISSUE TITLE
Content disappearing from Visual Builder

### ISSUE THREAD

**Issue by woodson75** [ThemeFuse/Unyson#2473]
I keep having issues whereby I save a page and then out of nowhere all the content in the visual builder just disappears:
![visual_builder_content_gone](https://cloud.githubusercontent.com/assets/26532922/24170472/daf3bf94-0ee5-11e7-9dd8-4d1f89b6c626.jpg)

I found this error in the error log (there are literally hundreds of instances of this error):

PHP Warning:  Invalid argument supplied for foreach() in /home/xxx/public_html/xxxx/xxxx/wp-content/plugins/unyson/framework/extensions/seo/extensions/seo-webmasters/class-fw-extension-seo-webmasters.php on line 118

When I disable various plugins within the Unyson framework (starting with the seo plugin), it seems to fix the issue for a while, but then it randomly re-appears.

Please fix!!!!!   :)

Thanks.

**Comment by GheorgheP** [comment]
Did you edit the `/plugins/unyson/framework/extensions/seo/extensions/seo-webmasters/config.php` config file? There must be an array as value: 
```php
$cfg['webmasters'] = array( 'google', 'bing' );
```

**Comment by woodson75** [comment]
Thanks for your reply GheorgheP. There is though no config.php file at that location??

**Comment by GheorgheP** [comment]
But it should be there as: https://github.com/ThemeFuse/Unyson-SEO-Extension/tree/master/extensions/seo-webmasters

**Comment by fkond** [comment]
i have smilar issue.

when i select one of saved template from templates menu over the page it looks over the page but after save its disappearing.

im try to save that page in mysql screen but i think its not saving there becouse my changing doesn't effect the original page.

**Comment by GheorgheP** [comment]
@fkond does this happen on all pages or only on big ones?

**Comment by fkond** [comment]
@gheorheP i saw this problem a few different home page samples. But if i see the problem one time after decrease the content in same page its continue. 

When i see first time that issue its going to continus for all day. İ spend 8-10 hours in same page to find solution but i cannot.

**Comment by GheorgheP** [comment]
Can you provide dashboard login details and a link to a page where you have this problem?
Here is may email: `pisarenco[dot]gh[at]gmail[dot]com`.
