### ISSUE TITLE
How to cropped thumbnail image without distorting it?

### ISSUE THREAD

**Issue by xttn** [ThemeFuse/Unyson#2474]
Hi, i have this image, size: `852x421`
![http://i.imgur.com/3ZANTfJ.jpg](http://i.imgur.com/3ZANTfJ.jpg)

I used `fw_resize($thumbnail_id, 362, 421, true);` to cropped size: `362x421`, but it is distorted

#----------------------View page
![http://i.imgur.com/roJ0r33.jpg](http://i.imgur.com/roJ0r33.jpg)

#----------------------I want this image:
![http://i.imgur.com/7X83I1a.jpg](http://i.imgur.com/7X83I1a.jpg)

**Comment by TrangDinhVan** [comment]
I always use $image_url in stead of image id for this function, so please try 
 fw_resize($img_src, 362, 421, true);
instead.

**Comment by xttn** [comment]
Yes, I replaced the ID by URL, but the results has not changed, the image is still distorted

**Comment by TrangDinhVan** [comment]
So strange, did you try the the hook "keep the quality of the image in cropping"?

`function _filter_zing_image_full_quality( $quality ) {
    return 100;
}
add_filter( 'wp_editor_set_quality', '_filter_zing_image_full_quality' );
add_filter( 'jpeg_quality', '_filter_zing_image_full_quality' );`

**Comment by duongancol** [comment]
I think you should try this plugin before change image size https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by xttn** [comment]
Yes, i used Regenerate Thumbnails plugin and it worked really well, thanks for the help!! :+1:
