### ISSUE TITLE
Exporting a post or page - missing content

### ISSUE THREAD

**Issue by obertscloud** [ThemeFuse/Unyson#2475]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.
Standard Wordpress Export  select custom - select a page that was built using the Unison Plugin.
the xml has content, when you import it , back into the live site, there is nothing on the page. It is missing all the elements, it does have a custom field with content and a few other things, but main content is gone.

**Comment by obertscloud** [comment]
I talked to Unyson via chat they said this should not be a problem.  when you export a single page using  WordPress Exporter , its there in the xml, but not on the import,  even using a paid version of pro wordpress exporter  still the import is missing the links .. looks like Unyson  uses  child posts (inherit posts) ,  and those are not getting linked or imported or something.. ,  however duplicate page works.. just export and import  -  i recommend that Unyson fix this or create one of their own plugins to it, that allows exporting anykind of content,  custom selected posts, pages, portfolio, etc..  that actually works.. .. the reason is several 
1)  updating or creating a new site, the development domain, can publish changed content, to the live site vise versa , or testing debuging purposes...
2)  in our case we have we work in the film industry with celebrities, so we have multiple different sites that share content between sites, so we minimize development time in recreating the same content, for example, venues, services, galleries, etc.. some of them are exact duplicates, and change often..  if export and import using wordpress standard xml for different post types, or individual posts etc.. worked we could minimize time

I have seen other people post similar issues, but the case was closed by a moderator with no explanation

**Comment by GheorgheP** [comment]
The issue is fixed partially as the attachment import doesn't work currently and also the attachments URLs are not replaced.

**Comment by obertscloud** [comment]
GheorgheP -- can you explain what do you mean by partially? how do we get an update for the fix, so we can start exporting specific pages and posts ? Has the developer for our theme contacted you? When will it be fully fixed ? Thank you please notify other users with these problems also I am sure they will be happy if it is fixed.

**Comment by obertscloud** [comment]
i searched for in the plugin, this class-fw-extension-page-builder.php  but I don't find it, where do I get the fixed version ?

**Comment by andreiglingeanu** [comment]
@obertscloud You'll find this file inside the [PageBuilder](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension) extensions repository.

**Comment by obertscloud** [comment]
ok but that has nothing to do with my bug i filed,  .. how do i export a single page for our live site, or a single post..  when i use the wordpress export and import  i dont get the elements that your plugin created no content on the page.

**Comment by GheorgheP** [comment]
@obertscloud, First thing's first, the pages created with our page builder, are available only for our page builder, so when you port the page and import it on other site, that should have the Unyson and the Page Builder extension installed, in other case the content will not be rendered, as only the Page Builder can render it.
At the moment, you are right, when you import using WordPress importer the content of the page is erased, so I fixed this in the commit from above, the only thing is missing, is the attachments import.
