### ISSUE TITLE
bvarrone

### ISSUE THREAD

**Issue by Bvarrone** [ThemeFuse/Unyson#2478]
Hi, I have this problem with Builder: if I use it to add columns,  I cannot then see them on the page, I see only one-column. I'm using Wordpress 4.7.3 and Theme Curiosity Lite. If I look for the theme directory structure  I don't find the file extensions → builder . Thanks

**Comment by GheorgheP** [comment]
What theme are you using? Did you test by activating a default wordpress theme?

**Comment by Bvarrone** [comment]
Curiosity Lite, I will do the test, thanks

**Comment by GheorgheP** [comment]
Did you make the tests?
