### ISSUE TITLE
Side tabs options settings

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#248]
Thnx for this addon!
Can you give us details on

how to turn on dark tabs version 
how to add icons
how to add sub tabs

Like here
https://trello.com/c/HxmZZYIp/53-theme-settings-vertical

**Comment by moldcraft** [comment]
> how to turn on dark tabs version

We decided not to make dark version. You can include you own css from the theme and change colors.

> how to add icons

The posibility to add icons to tabs will be added later.

> how to add sub tabs

Just put tabs inside tabs. Check the Scratch theme demo options

**Comment by moldcraft** [comment]
> how to add sub tabs

Sorry i forgot abot sub-menus/tabs from the screenshot on trello, we also decided to not make them
