### ISSUE TITLE
Installing plugins via composer (bedrock project) install extensions via composer too?

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#2480]
Hi,

I use unyson extensively, the only gripe I've about it is that I cannot install extensions via composer like I do unyson itself and other dependencies.

I use bedrock project.

on a related note. if I install old version of plugin, does unyson download correct extension version? or are extensions downloaded always the recent?

**Comment by GheorgheP** [comment]
At the moment we developer the [Unyson CLI](https://github.com/ThemeFuse/Unyson-CLI) and you'll be able to install extensions via command line `wp unyson ext backups install`. I cannot tell if we will develop instillation via composer, at least we do not plan it in near future.

**Comment by MikeiLL** [comment]
Hey @sandrodz are you still using Unyson extensively? I just posted about is at [Roots Discourse](https://discourse.roots.io/t/unyson-framework-plugin-with-bedrock-trellis/17670).

**Comment by sandrodz** [comment]
> Hey @sandrodz are you still using Unyson extensively? I just posted about is at [Roots Discourse](https://discourse.roots.io/t/unyson-framework-plugin-with-bedrock-trellis/17670).

Not really, I use ACF-pro and WordPlate.
