### ISSUE TITLE
assets are loaded from wrong dir

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#2481]
Using bedrock.

From version `>=2.6.11` to latest, assets are loaded from themes dir. and plugin doesn't work.

![screen shot 2017-03-24 at 11 27 55 am](https://cloud.githubusercontent.com/assets/8479569/24284829/b0a78868-1086-11e7-87c9-2174a78a8cb8.png)

version `<=2.6.10` works fine.

**Comment by sandrodz** [comment]
this seems like a possible culprit: https://github.com/ThemeFuse/Unyson/commit/e378efd45e4d6b7435ebac5a836a7556c866a920#diff-1a10d08376d32331dbdc651256766d37R1654

**Comment by GheorgheP** [comment]
Are there some specific steps I need to do in order to view the problem.
I just made an bedrock install and all seems to look properly.

![](https://static.md/3138f31ac6f7ab33acdeaa2c0f525cc4.png)
