### ISSUE TITLE
Wrong sidebar is showing up

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2482]
I currently have the following situation:

- I have a parent page and assigned a new sidebar to it
- The parent page has several child pages, and I assigned another new sidebar to them

The sidebar assigned to the child pages now shows up on the parent page as well. But I specifically assigned a different sidebar to that page. 

Does it have something to do with the parent/child structure? 
Is this a bug or am I doing something wrong here?

I have the latest version of WordPress and the latest version of Unyson. I'm using the Unyson Sidebars extension.

**Comment by GheorgheP** [comment]
I just made a test and all works fine. Could you try this on our [scratch theme](https://github.com/ThemeFuse/Scratch-Theme) to make sure that the problem doesn't come from the theme development?

**Comment by noesteijver** [comment]
This seems to be fixed now, thanks!
