### ISSUE TITLE
Unclear error

### ISSUE THREAD

**Issue by GoldenFILL** [ThemeFuse/Unyson#2484]
![upload](https://cloud.githubusercontent.com/assets/26322552/24318912/940048f0-1151-11e7-897a-37ff103f55c8.jpg)
Why does this error occur?
I did not edit the source code (I did not even open it)

**Comment by GheorgheP** [comment]
Does this error occurs just in IDE?
The IDE may interpret the code as invalid HTML code and it warns you.

**Comment by GoldenFILL** [comment]
Yes. It shines in NetBans, at the same time it was immediately after installation on the Wordpress Unison plug-in
There are no errors on the web (http) server
(I write through an interpreter, I ask for a possible bad vocabulary).

**Comment by GoldenFILL** [comment]
Is it possible to neutralize in NetBeans the response to this error?

**Comment by GheorgheP** [comment]
To be honest, I did not ever use NetBans, ans I just tried to install it and didn't manage even to create a PHP project with it. May be you could look in the settings and something. It doesn't like the `<% %>` tag and the `print` function in them.
