### ISSUE TITLE
Created inner column how can I add ustom correction

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2485]
@andreiglingeanu  @GheorgheP  I was under impression that we wont need column in column but must admin that I was wrong , 

Layouts like this are impossible to do **via builder** 

![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/24358449/6cc5819a-1301-11e7-9f52-7accfd500390.jpg)

so I created the inner column shortcode wich works well

![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/24358481/8ac7f394-1301-11e7-80b1-9f595e24bbc9.jpg)

the problem I have is that in **frontend** I need to wrap inner columns inside the row  like @moldcraft  did originally for columns 

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/34eb9c48456833a823ae3a90ecc0ffe353249211/includes/page-builder/includes/items-corrector/class-page-builder-items-corrector.php#L14

does anyone knows a built in  way to do this ?

ping https://github.com/ThemeFuse/Unyson/issues/2436

**Comment by andreiglingeanu** [comment]
@danyj Why not do this in your shortcodes `render` function? I don't think you need special support from unyson for that.

**Comment by danyj** [comment]
thnx for reply I would have to do that but was wondering if you know built in way like moldcraft used or do I need to copy the parts of that class he mad

**Comment by andreiglingeanu** [comment]
Well, the built in items corrector is hard-coded for the original `row` and `column` shortcodes. You'll gain a lot more flexibility by doing that by yourself, that's my opinion about it.

**Comment by danyj** [comment]
@andreiglingeanu   

> render function 

did you mean here  https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/column/views/view.php#L6


I dont see any other place in the class for render , only inside the view

**Comment by andreiglingeanu** [comment]
Hm, I just looked it over a bit more and I see that it is pretty hard to do that in the `view.php`. 

You can actually override that [_render](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/includes/class-fw-shortcode.php#L210) method for changing the way you interpret that `$content` variable. That's one option.

Another one will be that:

- Force items to require correction [here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/9a4976299c7cf0f38725b0e3a9a26b48e9797b53/includes/page-builder/class-fw-option-type-page-builder.php#L294) by adding a hook in that `needs_correction()` method
- Wrap this call inside one more corrector object which would parse you structure and wrap your custom columns in native row shortcodes, right [here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/9a4976299c7cf0f38725b0e3a9a26b48e9797b53/includes/page-builder/class-fw-option-type-page-builder.php#L298)

That's a bit involved, I know. I'll be able to get a quick snippet for you tomorrow in the morning, with the required unyson filters already in place. Or you can try your hand at it while you're at reading Unyson's source.

**Comment by andreiglingeanu** [comment]
Anyway, I'll just create an infrastructure for chaining correctors. You'll be responsible for the actual parsing of the whole structure. I shared with you a class for easily doing that a couple of months ago .

**Comment by danyj** [comment]
thnx bud!

**Comment by danyj** [comment]
this would have been easier 

			fwEvents.on('fw:builder:page-builder:column:filter:allow-incomming-type', function(data){		

					if(data.type =='column'){
						data.allow = true;
						
						console.log(data);
					}
			});

but the layout is mess in front 


and there is trailing /column from shortcode

http://prntscr.com/ep2xv1
http://prntscr.com/ep2xz1

**Comment by danyj** [comment]
@andreiglingeanu 

> You can actually override that _render method for changing the way you interpret that $content variable. That's one option.



that one wont work since I would have to change the render for the column , not for innercolumn 


so what is needed is to  check **column** shortcode $content  for **innercolumn** existence and if there are any , add row around them .

**Comment by danyj** [comment]
simple preg_replace like this work oki'sh in column 


```
if (strpos($content, 'innercolumn') !== false) {
	$find = array('/\[innercolumn/s', '/innercolumn]$/');
	$replace = array('[row][innercolumn', 'innercolumn][/row]');
	$content = preg_replace($find, $replace, $content,1);
}
```

but im kinda uncertain about it

**Comment by andreiglingeanu** [comment]
@danyj Well it totally depends on what you actually allow to be dragged in into your columns. If you're not allowing rows -- you should be just fine.

**Comment by danyj** [comment]
> depends on what you actually allow to be dragged

The inner column is allowed only inside the column and accepts everything except section and column

![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/24377886/400accba-1341-11e7-87d9-e417d713998c.jpg)


and the snipp above outputs great with this regex 

```
if (strpos($content, 'innercolumn') !== false) {
	$find 		= array('/\[innercolumn/s', '~innercolumn](?!.*innercolumn])~');
	$replace 	= array('[row][innercolumn', 'innercolumn][/row]');
	$content 	= preg_replace($find, $replace, $content,1);
}
```

http://prntscr.com/ep7xlk

now the trouble is this one 


![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/24377923/5f3487a2-1341-11e7-92b2-53c673630b36.jpg)


it should put first 2 innercolumns and last 2 inner innercolumns  in row  but it places complete snipp inside the row  because the regex matches beginning and ending of the innercolumn  not paying attention to widths


http://prntscr.com/ep7z38

**Comment by andreiglingeanu** [comment]
This thing is harder than you thing. I'm afraid approaching it with regexes won't make it. You need a proper array parsing. You'll have to detect groups of shortcodes and wrap each of them in rows.

That is, in [this](https://cloud.githubusercontent.com/assets/2340172/24377923/5f3487a2-1341-11e7-92b2-53c673630b36.jpg) concrete example, you'll have to wrap the initial structure like that (not providing exact notation):

```
[row]
  [col 1/2][text-block/][/ 1/2]
  [col 1/2][text-block/][/ 1/2]
[/row]
[row]
  [col 1/1][text-block/][/ 1/2]
[/row]
[row]
  [col 1/2][text-block/][/ 1/2]
  [col 1/2][text-block/][/ 1/2]
[/row]
```

And your initial structure looks like that:

```
[col 1/2][text-block/][/ 1/2]
[col 1/2][text-block/][/ 1/2]
[text-block/]
[col 1/2][text-block/][/ 1/2]
[col 1/2][text-block/][/ 1/2]
```

And you'll have to do that under certain conditions, specifically only when a regular column contains a nested one.

**Comment by danyj** [comment]
@mowshon   bud can you take a look at this? I can release the shortcode after we  fix this

**Comment by andreiglingeanu** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/002672e2520ccf002cc0d553b8fed7882a1d6466

```php
add_filter(
  'fw:ext:page-builder:json-structure-needs-correction',
  '_action_enforce_correction_for_inner_column', 10, 2
);

function _action_enforce_correction_for_inner_column($default_needs_correction, $items) {
  // here check recursively if $items contains a nested column
  if (items_contain_nested_column($items)) {
    return true;
  } else {
    return $default_needs_correction;
  }
}

add_filter(
  'fw:ext:page-builder:json-structure-correction',
  '_action_inner_column_corrector', 10, 2
);

function _action_inner_column_corrector($items_to_correct, $items_before_any_correction) {
  // modify $items_to_correct in such a way that you wrap columns with inner columns
  // in rows

  // there's a $items_before_any_correction available, for reference
  return $items_to_correct;
}
```

**Comment by danyj** [comment]
thnx for this but Im still lost in it , how would you go ahead if the filter is used to correct default column by using unyson default correct functions ?

**Comment by danyj** [comment]
can anyone help on this last bit , I managed to get all column widths for correction just need proper function to put them in place ,  this one almost had it but he is not calculating the width but just checking if rows are there 

http://stackoverflow.com/questions/43126779/build-grid-rows-based-on-columns-widths-array-php

cmon @andreiglingeanu  , I know you can get this one right , I came this far. 

I am sure that there is built in function for this , inside the corrector just down know how to use it .

**Comment by mowshon** [comment]
@danyj interesting way to extend column functionality. Can you share with me with this shortcode and I'll try to help you.

email: mowshon@gmail.com

**Comment by danyj** [comment]
@mowshon   skype me   :  youjoomla

**Comment by danyj** [comment]
@andreiglingeanu  ,   I think we need a mod for this 
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/includes/page-builder/static/js/visual-elements.js#L120

this is  hard coded and only way to add show hide icon is copy the file with all functions and add own

**Comment by andreiglingeanu** [comment]
@danyj I think I got it... Let's get the row wrappers working first then I'll do the part of getting the icons right for the column.

**Comment by danyj** [comment]
and you right ,  if there is 1  innercolumn , inside column 

anything in that column should be in row ,   if it is not innercolumn it should be in own row and inside column  like 




```
[row] innercolumn,innercolumn[/row]
[row][column]  some shortcode [/column]   [/row]
[row] innercolumn,innercolumn[/row]
[row][column]  some shortcode [/column]   [/row]
```

**Comment by danyj** [comment]
that is how I did it in my ThzWrapInnerColumns class

**Comment by danyj** [comment]
@andreiglingeanu  ok seems like we got it.  can you take a look at this  https://github.com/ThemeFuse/Unyson/issues/2485#issuecomment-290728626

**Comment by danyj** [comment]
thank you @mowshon !!!

**Comment by danyj** [comment]
@andreiglingeanu  do you have time to look at this  https://github.com/ThemeFuse/Unyson/issues/2485#issuecomment-290733039

**Comment by andreiglingeanu** [comment]
@danyj On it now.

**Comment by andreiglingeanu** [comment]
@danyj Added one more [hardcode](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/fa904e3d11167f9731e2ea48e664e9805c2726b2#diff-bac3f5f9d79eaa219b17a86854016c8aR113) there for innercolumn temporarily. Probably will think about something better for it later.

@GheorgheP Sorry for the hardcode 😅

**Comment by danyj** [comment]
@andreiglingeanu  can we posobly find actual fix for this 
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/fa904e3d11167f9731e2ea48e664e9805c2726b2#diff-bac3f5f9d79eaa219b17a86854016c8aR113

I added few more custom wrappers shortcodes and this is only thing that is missing.

**Comment by yanickvanbarneveld** [comment]
Where/how can I download this shortcode? This looks amazing and I am interested aswell!

**Comment by danyj** [comment]
@yanickvanbarneveld wait until  our theme comes out

**Comment by danyj** [comment]
@ViorelEremia   @andreiglingeanu   waiting for fix please respond to my April 20 post https://github.com/ThemeFuse/Unyson/issues/2485#issuecomment-295878488

**Comment by yanickvanbarneveld** [comment]
How is it going with these inner columns? 
Is it already implemented in the theme?

**Comment by dominicht** [comment]
> @ViorelEremia @andreiglingeanu waiting for fix please respond to my April 20 post [#2485 (comment)](https://github.com/ThemeFuse/Unyson/issues/2485#issuecomment-295878488)

Hi @danyj Any chance you can share your progress on inner columns?

**Comment by danyj** [comment]
@dominicht we have them in our pro version https://themezly.com/docs/inner-column/

**Comment by dominicht** [comment]
Thanks @danyj. I'll go get that!
