### ISSUE TITLE
JS error of icon v2

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson#2487]
Icon-v2 option throws a JS error in WP admin. 

http://prntscr.com/epdugy

**Comment by dmbostan** [comment]
Need to mention that it is used in Appearance > Widgets.

**Comment by andreiglingeanu** [comment]
Give me a quick reproduction of it please. An array of options and a place to put it would be awesome. I'll be able to fix it afterwards.

**Comment by andreiglingeanu** [comment]
@dmbostan You able to give me a quick step-by-step reproduction for this bug?

**Comment by dmbostan** [comment]
1. I used [this](http://dinhtung.info/creating-widgets-unyson-options-type/) code to add options to widgets
2. Add default [icon-v2 options](http://manual.unyson.io/en/latest/options/built-in/icon-v2.html).
3. See console.

**Comment by andreiglingeanu** [comment]
Thank you.
