### ISSUE TITLE
"Forbidden" after sent message via the contact form Unyson

### ISSUE THREAD

**Issue by MartijnHeijmans** [ThemeFuse/Unyson#2488]
I can't find a solution to this:

When I've setup the whole contact form via WP-mail, the 'intern' test does work. But when I test the contact form on the website itself, I get the message like the picture below.

[http://i64.tinypic.com/os6hed.png](url)

Does anyone know how to resolve this problem?

**Comment by NiloySarker** [comment]
Hello, I remember you :) 
you are using Academic Theme.
Please update Theme to the latest version 1.2.6.
 I fixed This Problem.
Thanks

**Comment by MartijnHeijmans** [comment]
Haha didn’t knew you where the developer of this plugin. It works! thanks :)
