### ISSUE TITLE
How can i add custom class in contact form 

### ISSUE THREAD

**Issue by chetnath** [ThemeFuse/Unyson#2489]
How can i add custom class for width in contact form single line and paragraph text field div?

![screenshot_20170328_155236](https://cloud.githubusercontent.com/assets/5096985/24400711/0dae67d4-13cf-11e7-9b98-1926f2003469.png)
![wordpress_-_2017-03-28_12 17 48](https://cloud.githubusercontent.com/assets/5096985/24404741/074fd51a-13e0-11e7-9d78-bd3989ff82b3.png)

**Comment by GheorgheP** [comment]
By using the `fw_builder_item_widths:form-builder` filter:

```php
/**
 * @param array $widths
 *
 * @return mixed
 */
function _filter_fw_filter( $widths ) {
	
	//Edit form-builder widths

	return $widths;
}

add_filter( 'fw_builder_item_widths:form-builder', '_filter_fw_filter' );
```

But this applies to all items in the form builder.

**Comment by chetnath** [comment]
Okay Thanks
