### ISSUE TITLE
hooks.php not working.

### ISSUE THREAD

**Issue by AminulBD** [ThemeFuse/Unyson#249]
Hi,

I'm going to rename and move the "Theme Settings" from appearance menu.

I've tried with this bellow code in /framework-customizations/theme/hooks.php file. But its not working. When Put this code in functions.php file its working fine.

Here is my code you given in pastebin.

```
if (!function_exists('_action_theme_custom_framework_settings_menu')):
        function _action_theme_custom_framework_settings_menu($data) {
                add_menu_page(
                        __( 'Unyson', 'fw' ),
                        __( 'Unyson', 'fw' ),
                        $data['capability'],
                        $data['slug'],
                        $data['content_callback']
                );
        }
endif;
add_action('fw_backend_add_custom_settings_menu', '_action_theme_custom_framework_settings_menu');

```
Can you check hooks.php file working or not?

Thank you.

**Comment by moldcraft** [comment]
Hi,
See the [ghangelog](https://wordpress.org/plugins/unyson/changelog/) for v2.1.0
