### ISSUE TITLE
Unyson WP plugin issue

### ISSUE THREAD

**Issue by tvthiel** [ThemeFuse/Unyson#2492]
I have the Unyson WP plugin installed and use the visual pagebuilder for one of my pages. In this page I use the Content Element "Map". 

Whatever I enter in the location settings of this map I get a location in the middle of Kanangra-Boyd National Park in Australia. If I enter nothing I get some address in Florida USA.

I want to point to this location: https://www.google.nl/maps/place/ODIRIS/@52.2106714,5.188815,17 but it isn't working. Can anybody help?

Regards,
Tom...

**Comment by GheorgheP** [comment]
In such cases I would recommend to use the map marker and drag it to the desired location on map, then edit the location addresses in case they are not specifically correct.

![](https://static.md/f3b2241deb79a553b94cabacf0a70774.png)

**Comment by martinburdon** [comment]
Not sure if this is the same issue but I've noticed if you don't add the API key, then save the shortcode and update the page, then it won't return any locations (or correct locations).

So:
1. Get an API key and add it to the API key field in the shortcode.
2. Save the shortcode and hit Update on the page.
3. Go back into the map shortcode and try searching for a location, auto suggest should now kick in and pick up the location you're looking for.
