### ISSUE TITLE
Backup extension issue

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2493]
Hello!

I have noticed a problem with Backups extension. I've just made a fresh content backup, and when i try to install it on another domain i get following error:

**Failed to insert row from line 1963 into table _fwbk_wp_terms. Unknown column 'term_order' in 'field list'**

How can i avoid this problem? Thank you

**Comment by andreiglingeanu** [comment]
Hey @WPJobs, what kind of a hosting you've got this problem on?
