### ISSUE TITLE
The grid max-width:100% CSS affects other things on the site as well

### ISSUE THREAD

**Issue by AlexandruDoda** [ThemeFuse/Unyson#2495]
The grid `max-width:100%` CSS affects other things on the site as well. There are 3 elements that have max-width: 100% globally and it affects certain components. In this case, it happens with the media-object in Bootstrap 3.

<img width="241" alt="screen shot 2017-04-01 at 2 56 05 am" src="https://cloud.githubusercontent.com/assets/8274669/24573016/cc5b8be4-1686-11e7-9e83-3f5521009803.png">

<img width="127" alt="screen shot 2017-04-01 at 3 05 27 am" src="https://cloud.githubusercontent.com/assets/8274669/24573134/1fc6dc42-1688-11e7-90e2-08c545d56481.png">

**Comment by danyj** [comment]
missing width auto inthat decleration

**Comment by AlexandruDoda** [comment]
It's in the Unyson grid file.

<img width="285" alt="screen shot 2017-04-01 at 1 53 08 pm" src="https://cloud.githubusercontent.com/assets/8274669/24578194/3ebb9320-16e4-11e7-9e62-10b70b9569e3.png">

**Comment by danyj** [comment]
it should be there but is just missing the width:auto; so that it wold not affect the default

**Comment by danyj** [comment]
@GheorgheP @andreiglingeanu  this needs to be added in
