### ISSUE TITLE
[Feature request] Add x_crop and y_crop functionality to FW_Resize::process 

### ISSUE THREAD

**Issue by jonmlas** [ThemeFuse/Unyson#2496]
Hi Guys, 

I'm using fw_resize for all my images on my theme. However, I think It's missing a must-have functionality which is the crop position. I would like this to be implemented just like in https://developer.wordpress.org/reference/functions/add_image_size/

Cheers!

**Comment by andreiglingeanu** [comment]
I am not very familiar with `FW_Resize` but if you mind taking some time to try a possible implementation of your feature request I'll happily review it.

**Comment by jonmlas** [comment]
ok. Thanks for the fast reply. I'll try it.

**Comment by GheorgheP** [comment]
@andreiglingeanu I created new branch [fw-resize](https://github.com/ThemeFuse/Unyson/tree/fw-resize), in case you'll start looking on this.
