### ISSUE TITLE
Move page title below header

### ISSUE THREAD

**Issue by fasonera** [ThemeFuse/Unyson#2497]
Hi!

I´m using The Core theme and would like to move the page title so it doesn´t is placed on top of the heade image but below the header. I want this to be changed on pages using the standard template. Does anyone know which code and file in the theme I have to change?

Best regards
Peter Lundvik

**Comment by GheorgheP** [comment]
I'm not really familiarized with The Core templates, but there is a folder `/wp-content/themes/the-core-parent/templates/headers`, here are all header templates, depending on what header type are you using, you need to edit the `header-TYPE.php` file. Do not forget to make the change in child theme, not in parent.

You make the changes in child theme by creating the `/templates/headers` directory in `/wp-content/themes/the-core-child/` and copying the desired header template file there.

For more help or information you can open a ticket on official [support page](http://support.themefuse.com/hc/en-us/requests/new) of Theme Fuse.

**Comment by fasonera** [comment]
I can´t find any information about the title in 
/wp-content/themes/the-core-parent/templates/headers
Does anynone else knows which file that controls where the page title is placed?
