### ISSUE TITLE
Unyson broken after migration from localhost to domain

### ISSUE THREAD

**Issue by rozkqu** [ThemeFuse/Unyson#2498]
I've developed some WP theme using Unyson WP Plugin. Chosen Unyson for visual builder in that inner company theme.

After migration from localhost to web serwer and domain Unyson was broken. I've done it like many times before - change siteurl and home in DB and update urls via Velvet Blues Plugin, and it works fine. In this case have some serious issues:

- in dashboard - Unyson builder is hidden (have to active it in "display options")
- after some changes in page layout, page breaks, all sections and bootstrap HTML gone out

Have any ideas what had happened and how to fix it?

**Comment by GheorgheP** [comment]
Please use the [Backup](https://github.com/ThemeFuse/Unyson-Backups-Extension) extension in order to migrate the site, is much faster and safer.

You can find a good tutorial about how to do that on our blog: https://themefuse.com/how-to-move-your-wordpress-site-manually/#unyson_backup_option

**Comment by rozkqu** [comment]
I've followed that tutorial step by step and it didn't work. 

Mayby it's my fault, because i didn't describe my issue properly. Now the same problem ocurs on localhost instalation - after some (iven small like text corrections) changes in page layout (via Unyson builder) the entire page breaks, all <sections> makups and bootstrap HTML gone out since builder on dashboard looks fine and it's still editable.

I do not have a cule to fix it. Switch off all plugins, and it did'n work, so its not a plugin conflict.
Sorry for my English. I need some help.

**Comment by GheorgheP** [comment]
Could you create a full backup using the Unyson Backup and share it with me on `pisarenco.gh[[at]]gmail[[dot]]com`?

**Comment by rozkqu** [comment]
After couple of hours i have figured it out. Trial and error method result was that some files of plugin has to been damaged.

After update plugin to current version, import everything via Unyson Backup and upload my custom shortcodes, builder backed on tracks.

I'm still not sure what exactly went wrong. Thanks for your time and involvement.
