### ISSUE TITLE
latest update won't download

### ISSUE THREAD

**Issue by monicaamarillis** [ThemeFuse/Unyson#2499]
Hi, I found in the plugin updates of my website the notice to update the Unyson plugin, but when I try to do it, it  always responds with an error and that the plugin won't download. What to do?

**Comment by monicaamarillis** [comment]
the version to which it won't update is the 2.6.16

**Comment by GheorgheP** [comment]
Yes, e are on it now, it seems something went wrong on WordPress side.

**Comment by GheorgheP** [comment]
It works. It seems there was an issue from WordPress.

**Comment by monicaamarillis** [comment]
Ok! :)
