### ISSUE TITLE
[Feature request] making elementor the default page builder

### ISSUE THREAD

**Issue by stylethemes** [ThemeFuse/Unyson#2500]
so I do really like the unyson framework but I think that the page builder doesn't live up to the level of the framework 
so I was thinking why not include the elementor page builder as the default page builder for unyson and make it work seamlessly with all the extensions of the framework
Ps: its open source

**Comment by danyj** [comment]
Unyson is developer framework ( like redux but much more advanced ) , your theme developer should make the best of it not you. 
Developers use the Unsyon MVC and make the best thing for you and to be honest it has the best MVC I have seen in ANY builder. . 

Elementor  is anyone's framework and it is extended to what their developers think is right for their users. 
It is not aimed at developers but end users.

So these 2 should  **NEVER** be combined in to one framework. Yes they can be used together but not combined.

**Comment by danyj** [comment]
and this is not a feature request but an ask to abandon Unyson core in favor of Elementor which I would not agree ever.  If you think this would be a good fit you can fork Unyson and Elementor and try to combine them.

**Comment by thednp** [comment]
I would do it this way: use the Unyson to get the best out f it without over-bloating it with other codes. With other words, customize it's extensions to your liking, especially the included Page Builder.

>why not include the elementor page builder as the default page builder for unyson and make it work seamlessly with all the extensions of the framework

There are some features of the framework that may not (or probably ever) going to integrate / work with other codes. Even if you do end up with some code that works the way you want, it will be a hell of a hustle to maintain in the long run.

**Comment by GheorgheP** [comment]
I think we can close this issue as we do not intend to integrate the Elementor with Unyson.
