### ISSUE TITLE
Contact form shortcodes names make no sense

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2507]
In contact form we have shortcodes like 

Single line text and Paragraph text where in fact these are 

![screenshot_12](https://cloud.githubusercontent.com/assets/2340172/24830778/d3e4ae5c-1c8c-11e7-8eaf-e1c8215b336f.jpg)

Single input, input box or text input ,   and textarea and they should be named properly. 

![screenshot_13](https://cloud.githubusercontent.com/assets/2340172/24830784/e12b3f36-1c8c-11e7-97e5-4c65e25361e2.jpg)

**Comment by GheorgheP** [comment]
Hmmm, you may be right, but here's a catch, many users translated it already and if we will change the text, we may break the translation, does it worth this?

**Comment by danyj** [comment]
> does it worth this

it sure does since it makes no sense, and it is 2 lines change , I think everyone is k with that much

**Comment by danyj** [comment]
can we  get a filter to change the text?

**Comment by duongancol** [comment]
I didn't see any users who translate the backend, they usually translate the theme so I think it's worth.

**Comment by danyj** [comment]
I made docs videos yesterday and it just makes no sense when I say paragraph  and single line text and showing input and textarea

**Comment by danyj** [comment]
@ViorelEremia why is this closed without a fix. Those names still make no sense.

**Comment by ViorelEremia** [comment]
I see its attached a release

**Comment by danyj** [comment]
no , in there I asked same question why that was not fixed. It is still like it was when I opened this issue

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/349#issuecomment-303920077.
