### ISSUE TITLE
Color grouping option

### ISSUE THREAD

**Issue by BassemN** [ThemeFuse/Unyson#2508]
Hello,

I'm new to Unyson :)
is there any color group option, for example, one option to handle link regular, hover, visited colors without creating one option for each color like the below example
![image](https://cloud.githubusercontent.com/assets/3768012/24838814/b6813a56-1d4f-11e7-8eff-10b4baa5683e.png)

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/1065

**Comment by andreiglingeanu** [comment]
Safe to close?

**Comment by BassemN** [comment]
@danyj Thank you very much :+1:  I'll follow the other issue.
@andreiglingeanu Yes, you close this issue.
