### ISSUE TITLE
Contact form printing empty row

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2509]
Contact form is printing empty row, not sure if it is because of this https://github.com/ThemeFuse/Unyson/issues/1576

but I have 5 elements in 3 rows ,  http://prntscr.com/eufkuf

and getting 4 rows out 

http://prntscr.com/euflvr

**Comment by andreiglingeanu** [comment]
It is probably unrelated... But who knows.

**Comment by GheorgheP** [comment]
I just tested all works fine.
Did you test on a default WordPress theme?
Also with previous Unyson version does it work properly?

**Comment by danyj** [comment]
@GheorgheP 
![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/24852137/a942b9c8-1dd6-11e7-8d27-4cbd0864782c.jpg)

**Comment by GheorgheP** [comment]
I'm sorry @danyj, I misunderstood your report.
Yes, there appears an empty row, and this is because of the header title section.

**Comment by danyj** [comment]
this filter should take care of that than  https://github.com/ThemeFuse/Unyson/issues/1576#issuecomment-221259500

**Comment by GheorgheP** [comment]
Yes, that's why the issue is still open.

**Comment by danyj** [comment]
@ViorelEremia  waiting for fix please respond
