### ISSUE TITLE
Vertical settings page not same as trello screenshots

### ISSUE THREAD

**Issue by AminulBD** [ThemeFuse/Unyson#251]
Hi,

I love the new theme settings page. But there no has great documentation. Also, when Enabled the vertical settings page then I'm getting auto collapsed my box under the settings.

Check this shot:
http://s13.postimg.org/eovgehe87/screenshot_2.png

How i can create title as http://s13.postimg.org/own6idf7r/screenshot_3.png

**Comment by moldcraft** [comment]
> Vertical settings page not same as trello screenshots

Yes. The designer draw something in photoshop, then on the implementation phase we made some changes.

>  when Enabled the vertical settings page then I'm getting auto collapsed my box under the settings.

The boxes are always auto-collapsed with or without side tabs enabled. I think you just noticed this now, but it was always like that.

----

Like it's now, it's final version and there are no other possibilities or hidden features. You can only enable/disable side tabs style. 
If you want, you can enqueue your own css from theme and customize/change the styles.

**Comment by pe6o** [comment]
I can't find how to Enable the vertical sidebar option. Is it in the Docs?

**Comment by moldcraft** [comment]
It's not in the docs, it's in [changelog](https://wordpress.org/plugins/unyson/changelog/) https://github.com/ThemeFuse/Unyson/releases/tag/v2.1.23

**Comment by pe6o** [comment]
Thanks!

Guys, do you even sleep? :O

**Comment by moldcraft** [comment]
We don't sleep at 4 PM :)

**Comment by pe6o** [comment]
Nice! 4 PM here too, yesterday las a lot later and you still were on track.

Keep up the good work!
