### ISSUE TITLE
Visual Page Builder defaulting to standard editor

### ISSUE THREAD

**Issue by James3090** [ThemeFuse/Unyson#2510]
Hi, I updated the Unyson plugin this morning on my site, but now all my pages and posts built using the visual editor have changed to the default WP editor.

Creating a new post or page with the visual page builder is possible and works fine, but then on publishing, the editor changes back to the default.

Just wondering what I need to go and do to stop this from happening. Thanks very much in advance.

**Comment by GheorgheP** [comment]
Hi,

This is wired, plase make sure the Page Builder is installed and activated in **Unyson** section.

**Comment by James3090** [comment]
Thanks for the quick response, however page builder is installed and active as per screenshots below and the issue remains.

![unyson1](https://cloud.githubusercontent.com/assets/27205113/24857922/e1d5d5ee-1de1-11e7-8d42-e2d2735dc3c4.png)
![unyson2](https://cloud.githubusercontent.com/assets/27205113/24857923/e1db0c08-1de1-11e7-8877-1972c2d53183.png)

**Comment by GheorgheP** [comment]
Please provide a link to the site, dashboard login details and ftp details.
Please send them on `pisarenco.gh[[at]]gmail[[dot]]com`.

**Comment by James3090** [comment]
I've done some further investigation, the problem only occurs when attempting to edit in a Chrome browser. In Firefox there is no issue, the visual page builder loads correctly.

**Comment by GheorgheP** [comment]
Please open the browser console and look if there may be any errors or warnings.

**Comment by James3090** [comment]
No errors or warnings as far as I can see. Looks like it was a weird problem with the cache. Force refresh fixed the issue, but why it happened in the first place I have no idea!
