### ISSUE TITLE
Is this filter safe for interception?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2511]
@andreiglingeanu 

Bud , is this filter
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/includes/page-builder/includes/items-corrector/class-page-builder-items-corrector.php#L61

 safe to intercept and modify the array before the print? 

Is that after all corrections meaning that the row will always be in ? 

I am trying to add a class to section columns  if specific section option is set

```
function _thz_check_section_layout ($items,$attr2,$attr3){
	
	foreach($items as $s => $item){
		
		if('section' == $item['type']){
			
			
			if('default' == $item['atts']['mode']){
				
				foreach($item['_items'] as $r =>  $row){
						
						
					foreach($row['_items'] as $c => $column){
						
						if('column' == $column['type']){
							$items[$s]['_items'][$r]['_items'][$c]['atts']['cmx']['c'] = 'thz-default';
						}
					}
				}
				
			}
			
		}
		
	}

	return $items;
	
}

add_filter( 'fw_ext_page-builder_items_correction_complete', '_thz_check_section_layout',10,3 );
```

**Comment by andreiglingeanu** [comment]
Yeah, the rows will be in place after this filter.

But, [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/002672e2520ccf002cc0d553b8fed7882a1d6466/includes/page-builder/class-fw-option-type-page-builder.php#L302), this filter will be executed _before_ executing **any** additional correctors, like the ones we defined for inner columns in #2485.

Probably we'll have to defer the complete filter to be executed _after_ the additionals correctors. What do you think?

cc. @GheorgheP

**Comment by danyj** [comment]
> Probably we'll have to defer the complete filter to be executed after the additionals corrector

thing is that I looked for a intercept for long time , we should be able to "see" what is inside section/column without hassle and yes we should see everything at **the very end** so that we can modify it if needed.

**Comment by andreiglingeanu** [comment]
I'll move the `complete` filter by the end of tomorrow's day. Feel free to play with it as it is right now, it is usable.

**Comment by andreiglingeanu** [comment]
@danyj You better use `fw:ext:page-builder:json-structure-correction:complete` instead.

**Comment by danyj** [comment]
thnx!

**Comment by danyj** [comment]
bug ,  

should be 

**apply_filters**  instead filteR

https://github.com/andreiglingeanu/Unyson-PageBuilder-Extension/blob/3b4f0be370e8c78c00de5ab748470bd00431184b/includes/page-builder/class-fw-option-type-page-builder.php#L319

**Comment by danyj** [comment]
we cant modify  row atts? 

see this 

```
function _thz_filter_check_section_layout ($items,$items_types){
	
	foreach($items as $s => $item){
		
		if('section' == $item['type']){
			
			if(!empty($item['atts']['sl']) && isset($item['_items'])){
				
				foreach($item['_items'] as $r =>  $row){
						
					$items[$s]['_items'][$r]['atts']['something'] = $r;
					
				}
				
			}
			
		}
		
	}
	fw_print($items);
	return $items;
	
}

add_filter( 'fw:ext:page-builder:json-structure-correction:complete', '_thz_filter_check_section_layout',10,2 );
```

adds atts to the row 

![screenshot_8](https://cloud.githubusercontent.com/assets/2340172/24904778/d7cc94fe-1eb1-11e7-877a-36bd6d0a23f8.jpg)


but in row view.php  $atts stays empty 


via this filter I can modify sections and columns atts but not row 


even if I add options.php in row and any option inside it stays empty. 


could you extend this 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/row/includes/page-builder-row-item/class-page-builder-row-item.php#L27


to be 

```

		return array(
			'tag'  => $this->get_type(),
			'atts'  => $atts
		);
```

**Comment by andreiglingeanu** [comment]
> should be
> apply_filters instead filteR

Fixed.

**Comment by andreiglingeanu** [comment]
@danyj Ah, it probably should be like [column](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php). [There you go.](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/1b888f46c4609fecea2c1f81204bf828e8205009)

**Comment by danyj** [comment]
ah thnx bud but I made mistake it should be something like 


		if ( isset( $atts['atts'] ) ) {
			$atts = $atts['atts'] ;
		}
		return array(
			'tag'  => $this->get_type(),
			'atts' => $atts
		);


since $atts returns    $atts['atts']   see

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php#L126
