### ISSUE TITLE
Contact Form 7 short code not working

### ISSUE THREAD

**Issue by fairmedia** [ThemeFuse/Unyson#2514]
I am trying to use the Contact Form 7 instead of the built in contact form and have inserted the short code inside the page builder by adding the short code to a text block. But it doesn't appear to work, it only shows the short code. Should I insert this in a different way?

**Comment by danyj** [comment]
it should , the output is printing shortcode unless the theme developer did an override and changed that. 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/text-block/views/view.php#L9

**Comment by fairmedia** [comment]
I had to hard code a change into the theme itself.
From this `<?php echo $atts['text'] ?>`
to
this `<?php echo do_shortcode( $atts['text'] ); ?>`
The client is using the theme «Cherry» by Haintheme
