### ISSUE TITLE
Using propopulate with addable option

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2516]
Hi guys,

I want to use a multi-select as an addable option (code below). When I press 'add' the addable option is added as should, but the prepopulate doesn't work. When clicking outside the field and focusing on the field again, the prepopulate function did it's working as intended. See below for a screen capture.

![ezgif-3-0a49a24057](https://cloud.githubusercontent.com/assets/1815847/24955997/ffe0e7f4-1f85-11e7-812f-521b67964e6e.gif)

```
$options = array(
    'dossier_box' => array(
        'type' => 'box',
        'title' => __('A title', 'ppp'),
        'options' => array(
        	'option_id' => array(
        	    'type'  => 'addable-option',
        	    'label' => __('Selecteer artikelen', 'ppp'),
        	    'option' => array(
	        	    'type'  => 'multi-select',
	        	    'population' => 'posts',
	        	    'source' => 'artikelen',
	        	    'prepopulation' => 10,
	        	    'limit' => 1,
        	    ), // option
        	    'add-button-text' => __('Toevoegen', 'ppp'),
        	    'sortable' => true,
        	), // option_id
        ),
    ),
);
```

**Comment by pnpetroff** [comment]
It seems 37a2cf1 is still not included in the latest update?

**Comment by GheorgheP** [comment]
We will release a new version soon.
