### ISSUE TITLE
Suggestion: fw_print to console

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2519]
I'd like to use a function similar to fw_print (fw_log?), which sends data to the console window.
I'm not sure if I can just put this in a pull request for Unyson?

It would work something like this:

```
fw_log($post);

function fw_log($data) {
	?><script>
	    console.log(<? echo json_encode($data); ?>);
	</script><?php
}
```

**Comment by GheorgheP** [comment]
Why would you need such functionality?

**Comment by warudin** [comment]
I mean when working with big arrays, by the way. Console is more flexible and also has the option to minimise certain keys and their data.

**Comment by GheorgheP** [comment]
Mmmm, I think this is somehow confusing.
The fact is that the data is rendered on the server, the you want it to be printed on console.

For few yes ago I had same problem, buy I stylized the `fw_print()` under my needs and it worked properly.

But this should be what do you need:

```php
function fw_log() {
	$args = func_get_args();
	add_action( 'shutdown',
		function () use ( $args ) {?>
            <script>
              <?php array_map( function ( $value ) {
                  ?>console.log( <?= json_encode( $value ) ?> );
              <?php }, $args) ?>
            </script>
		<?php } );
}
```

**Note**
I use anonymous function, so it works for php 5.3+ only.

**Usage**:

```php
fw_log( 'Hi, fw_log' );
fw_log( [1,2,3,4,5] );
fw_log( get_posts() );
```

Or you can pass multiple parameters at once:

```php
fw_log( 'Hi, fw_log', [1,2,3,4,5], get_posts() );
```
And it will print out:
![](https://static.md/f2d24ee8b1ffa07936047b00318e1e34.png)

**Comment by warudin** [comment]
That looks very nice!

**Comment by danyj** [comment]
@GheorgheP 
god bless you! :) 

@warudin  you to bud!

got tired of long fw_prints, not that they dont help but this is great

**Comment by ivandotv** [comment]
Lol, anyone doing proper debugging? :)
This should not be put inside unyson.

**Comment by danyj** [comment]
> Lol, anyone doing proper debugging? :)

sorry "master" debugger , we did not know that there is a proper way. care to enlighten the lost souls?

> This should not be put inside unyson.

no one asked for this to be in unyson

**Comment by andreiglingeanu** [comment]
@ivandotv Using a dynamically injected [psysh](http://psysh.org/) shell for that - better than any `print_r`s or `fw_print`s. You have to use PHPs built in server for that's the single downside of it.

**Comment by ivandotv** [comment]
@danyj chill dude

**Comment by GheorgheP** [comment]
I think we are all satisfied.

**Comment by warudin** [comment]
I guess this will not be implemented in Unyson by default? It's not a big problem for me, I'll just put Ghoerghe's code in functions.php when needed in a project. Of course it'd be nice if it'd be there by default!

**Comment by GheorgheP** [comment]
There are few facts why we wll not add this function in the core of Unyson.

 - This is not really a good practice for debugging.
 - This is a very specific need that I'm not sure many developers would need it or even think about such approach during debugging or testing.
 - This solution requires **php 5.3+**, but the Unyson framework at the moment guarantees the **php 5.2.4+** compatibility.

**Comment by warudin** [comment]
OK, thanks for clearing that up!
