### ISSUE TITLE
Only load selected google fonts not all?

### ISSUE THREAD

**Issue by zenics** [ThemeFuse/Unyson#2520]
Is there an easy way to limit google fonts to load only selected ones?

**Comment by GheorgheP** [comment]
I think this the same question https://github.com/ThemeFuse/Unyson/issues/1775#issuecomment-293581057

**Comment by zenics** [comment]
I have done that but still getting the full list. Can you please help me @GheorgheP . I ve purchased the lifetime support for $179 and cant get this done somehow. Using the core theme again.

I just try this in the child themes function.php file and on the theme settings page I still get the full list. What am I doing wrong?
