### ISSUE TITLE
multi-select not sortable

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2521]
It would be awesome if users would be able to sort the currently selected items in a multi-select option.

**Comment by GheorgheP** [comment]
Hmmmm, do you think this is such a needed thing?
I mean, the choices are saved in the order the user picked them, think being the best approach I think.

But I understand that in some cases you need to change the order.
I think it's easier to extend the `multi-select` option type and just to change the render method there adding the order you need to the selected items.

You can even replace the `multi-select` option type in the options you have with this new type, as you do not change the I/O of the option, but just the items order during rendering.

**Comment by warudin** [comment]
We use a multi-select to make a selection of posts which will be used in a slider. Over time the user would like to change them, remove some, put some new posts between others, etc.

**Comment by warudin** [comment]
I'm a bit confused about why the 'addable-option' supports this ability, while the 'multi-select' doesn't.

**Comment by GheorgheP** [comment]
I understand this, but comparing the `addable-option` and `multi-select` I think is not correct as they are made for different tasks.

I will think about this and if we will decide to implement this, we will do that.
