### ISSUE TITLE
Error when doing ajax inside customizer

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2522]
Using latest wp , and unyson versions.
Inside customizer when doing ajax (loading more blog posts), ajax call executes successfully, but I get a `warning` regarding unyson.
This warning only happens when I change **any** option inside customer, and **then** do `ajax` call.
If I don't change any options inside customizer there are no errors with ajax calls.

error:
`Warning: json_decode() expects parameter 1 to be string, array given in /var/www/html/wp-content/plugins/unyson/framework/includes/customizer/class--fw-customizer-setting-option.php on line 21`

this is the call stack:
```
#	Time	Memory	Function	Location
1	0.0005	292856	{main}( )	.../admin-ajax.php:0
2	0.0007	310072	require_once( '/var/www/html/wp-load.php' )	.../admin-ajax.php:22
3	0.0008	320992	require_once( '/var/www/html/wp-config.php' )	.../wp-load.php:37
4	0.0017	447312	require_once( '/var/www/html/wp-settings.php' )	.../wp-config.php:97
5	0.7681	59853400	do_action( )	.../wp-settings.php:470
6	0.7681	59854072	WP_Hook->do_action( )	.../plugin.php:453
7	0.7681	59854168	WP_Hook->apply_filters( )	.../class-wp-hook.php:323
8	0.7682	59856232	call_user_func_array:{/var/www/html/wp-includes/class-wp-hook.php:298} ( )	.../class-wp-hook.php:298
9	0.7682	59856680	WP_Customize_Manager->wp_loaded( )	.../class-wp-hook.php:298
10	1.4723	75430696	WP_Customize_Setting->preview( )	.../class-wp-customize-manager.php:746
11	1.4723	75431384	WP_Customize_Setting->post_value( )	.../class-wp-customize-setting.php:293
12	1.4723	75431384	WP_Customize_Manager->post_value( )	.../class-wp-customize-setting.php:509
13	1.4725	75432040	_FW_Customizer_Setting_Option->sanitize( )	.../class-wp-customize-manager.php:1489
14	1.4725	75432136	json_decode ( )	.../class--fw-customizer-setting-option.php:21
```

**Comment by GheorgheP** [comment]
Could you provide the customizer options array?

**Comment by ivandotv** [comment]
Yeah, forgot about that.
The array is **always**  empty.

**Comment by GheorgheP** [comment]
How is empty? you have array of options in customizer.

**Comment by ivandotv** [comment]
yes, but that array is empty. Every single time.

**Comment by GheorgheP** [comment]
Wait, I'm asking for customizer options array you have. I want to test on my side.

**Comment by ivandotv** [comment]
I have a ton of options inside the customizer. 
I was referring to the value that gets passed to the `sanitize` method of `_FW_Customizer_Setting_Option` class on line 21, that value is always empty array.

I'm thinking that when doing ajax inside the customizer, unyson doesn't know it's running via ajax call inside the customier, and it's trying to do some customizer stuff that it does on regular customizer page loads.

**Comment by ivandotv** [comment]
For a quick fix we could check if the array is empty and return null as you already do.
But you do it after you try to do `json_decode`

**Comment by GheorgheP** [comment]
Could you point me to the line of code you refer?

**Comment by ivandotv** [comment]
I've made a pull request for this issue.
Like I said, sometimes an `array` is passed to `sanitize` method of `_FW_Customizer_Setting_Option` class, but that method expects a `string`.
So I made just a check if it is an array passed, then immediately return null.
Probably the real issue is somewhere else, this is just a quick fix.
