### ISSUE TITLE
Pages and posts frezzing a few seconds in BO

### ISSUE THREAD

**Issue by Oazar** [ThemeFuse/Unyson#2524]
Hello there,

I installed a theme called woffice which  uses Unyson.

As soon as I activated Unyson the whole website got slow (although it was empty). I found a post here suggesting to upgrade to PHP7, and it worked..

Still, there is an issue with posts and pages **in the BO** : when I display them (or update them), there is a few seconds freezing before I can edit. The screen is not blank, I can see all features, but I have to wait 4 to 5 seconds before eing able to edit or use any button of the BO (preview...)

This issue only concerns pages and posts, the rest of he BO pages are loading fast and no freezing.

Thanks for your help

**Comment by GheorgheP** [comment]
What do you mean by BO? Possible the page has many options and they need to load before they are available for work.

**Comment by Oazar** [comment]
Thanks for your answer;

I mean backoffice, on front end here is no problem.

So you think this is a theme issue that would happen when I activate unyson ?

**Comment by GheorgheP** [comment]
No, I didn't say that, I'm just asking, if there a re many options.
Did you contact the theme developers to ask about this issue?

**Comment by Oazar** [comment]
Yes there are some options only visible in backoffice.
And yes, I did ask support from the theme developpers but for the time being they just answered  with a generic post bout optimizing wordpress, using a cache, whether my server is shared or not...
