### ISSUE TITLE
Problem with center button of UNYSON?

### ISSUE THREAD

**Issue by treashdox** [ThemeFuse/Unyson#2525]
I made a modification of content element "divider" but it does not work for me adding a center class via swich switch spit out only 0 or 1 code below ..

    <?php if ( ! defined( 'FW' ) ) {
	    die( 'Forbidden' );
    }

    $options = array(
	    'style' => array(
		    'type'     => 'multi-picker',
		    'label'    => false,
		    'desc'     => false,
		    'picker' => array(
			    'ruler_type' => array(
				    'type'    => 'select',
				    'label'   => __( 'Ruler Type', 'fw' ),
				    'desc'    => __( 'Here you can set the styling and size of the HR element', 'fw' ),
				    'choices' => array(
					    'line'  => __( 'Line', 'fw' ),

					    'space' => __( 'Whitespace', 'fw' ),
				    )
			    )
		    ),
		    'choices'     => array(
			    'space' => array(
				    'height' => array(
					    'label' => __( 'Height', 'fw' ),
					    'desc'  => __( 'How much whitespace do you need? Enter a pixel value. Positive value will increase the whitespace, negative value will reduce it. eg: \'50\', \'-25\', \'200\'', 'fw' ),
					    'type'  => 'text',
					    'value' => '50'
				    )
			    ),
			    'line' => array(
				    'height' => array(
					    'label' => __( 'Height', 'fw' ),
					    'desc'  => __( 'How much line height do you need? Enter a pixel value.', 'fw' ),
					    'type'  => 'text',
					    'value' => '2'
				    ),
				    'width' => array(
					    'label' => __( 'Width', 'fw' ),
					    'desc'  => __( 'How much line width do you need? Enter a pixel value.', 'fw' ),
					    'type'  => 'text',
					    'value' => '85'
				    ),
				    'centered'  => array(
					     'type'  => 'switch',
					    'label' => __('Centered', 'fw'),
					    'right-choice' => array(
						    'value' => 'center',
						    'label' => __('Yes', 'fw'),
					    ),
					    'left-choice' => array(
						    'value' => 'none',
						    'label' => __('No', 'fw'),
					    ),
				    ),

			    ),
		    ),
	    ),
    );

**Comment by GheorgheP** [comment]
I just tested your options array and the `center` value is saved properly.
It's already up to you how you add it to the `divider` shortcode.
Here is the result when I extract options values:

![](https://static.md/8c2701f09157966e654aba50c68482be.png)

**Comment by treashdox** [comment]
Below is what my view.php looks like and when I switch "Yes" "No" with my button displays me a value of "1" or "0" instead of "center" or "none"? Dawa so it happens?
  
  <?php if ( ! defined( 'FW' ) ) {
	    die( 'Forbidden' );
    }

    if ( 'line' === $atts['style']['ruler_type'] ): ?>
	    <div class="fw-divider-line fw-divider-line-<?php echo (int) $atts['style']['line']['centered']; ?>"     style="height: <?php echo (int) $atts['style']['line']['height']; ?>px; width: <?php echo (int) $atts['style']['line'] ['width']; ?>px;"></div>
    <?php endif; ?>

    <?php if ( 'space' === $atts['style']['ruler_type'] ): ?>
	    <div class="fw-divider-space" style="padding-top: <?php echo (int) $atts['style']['space']['height']; ?>px;"></div>
    <?php endif; ?>

**Comment by GheorgheP** [comment]
Please print out the the `$atts` variable to see the value.

```php
fw_print( $atts );
```

**Comment by treashdox** [comment]
Ok, i'll check it out
