### ISSUE TITLE
Content Element Dragging/Positioning Issues

### ISSUE THREAD

**Issue by hoscheck** [ThemeFuse/Unyson#2526]
# ISSUE 01
When dragging a Content Element to Layout Element, a duplicate Content Element is put into every proceeding Layout Element. Obviously, over time, these build up and have to be stripped out of all proceeding Layout Elements

### EXAMPLE
_Action_
Dragging Special Heading across Header to Sub-Section

_Result_
Special Heading drops into Sub-Section, but also drops a duplicate into Header

# ISSUE 02
When dragging a Content Element to Layout Element, regardless of where the UI indicates you will position the Content Element, it always goes to the bottom of the targeted Layout Element and has to be repositioned.

## NOTE
The image below shows several three additional Special Headings that dropped into the Header while being dragged across.

![image](https://cloud.githubusercontent.com/assets/25201153/25046659/4da7f07c-20f8-11e7-9b1a-bc39207e23a7.png)

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/bee85c9681751633a64ff0e1aa5d9d7b1e9e8f0f
