### ISSUE TITLE
Layout Element Drag Issue

### ISSUE THREAD

**Issue by hoscheck** [ThemeFuse/Unyson#2527]
# ISSUE
If Layout Elements are collapsed, dragging a Layout Element will only land in one of the following locations:
- Top slot
- Second slot (shown in image below)
- Bottom slot

This forces one of the following:
- Elaborate Layout Element rearrangement ordering to position one in the middle
- Expand the Layout Elements (which has its own issues on lengthy pages)

![image](https://cloud.githubusercontent.com/assets/25201153/25046773/f4faf734-20f8-11e7-8f8c-03b4fc0de46b.png)

**Comment by GheorgheP** [comment]
@hoscheck could you explain the issue one more time or create a demonstration video? I don't really understand it.

**Comment by danyj** [comment]
@GheorgheP  I just ran across this,  collapsed section reorder works only on first 2 , 

if you have 5 sections and need to place  5th on top all others it wont work , only first 2 can be reodered

**Comment by GheorgheP** [comment]
Hmmm, I just tested and it works, but yes, I observed a bit o lagging.
I'm now working on a new d&d algorithm and it should solve this issue too.
