### ISSUE TITLE
backend-option-design-customizer.php

### ISSUE THREAD

**Issue by 9585999** [ThemeFuse/Unyson#2529]
Hi, how can I change the output of the html code of the backend-option-design-customizer.php file without touching the plug-in files?

**Comment by GheorgheP** [comment]
You cannot, but why do you need to change it?

**Comment by 9585999** [comment]
It generates a class fw-pull-left, and it produces an incorrect display of elements...
![img 2017-04-18 11 45 08](https://cloud.githubusercontent.com/assets/16165904/25122257/ee01025c-242c-11e7-9a8d-b704a31b16cc.PNG)
![img 2017-04-18 11 45 27](https://cloud.githubusercontent.com/assets/16165904/25122258/ee0dbba0-242c-11e7-93a4-223c6dabab9c.PNG)
![img 2017-04-18 11 45 44](https://cloud.githubusercontent.com/assets/16165904/25122259/ee0ffdf2-242c-11e7-80be-aeef5f20add2.PNG)

If the class fw-pull-left delete everything is fine ...

**Comment by 9585999** [comment]
In principle, the problem can be solved through css ...

![img 2017-04-18 12 27 56](https://cloud.githubusercontent.com/assets/16165904/25123851/7d5bb992-2432-11e7-8da7-154e0fc41035.PNG)

But what's the point with this class? ...
