### ISSUE TITLE
Custom option buttons initiating save

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#253]
I created custom option by exactly following this tut
http://manual.unyson.io/en/latest/options/create-option-type.html#content

1 it creates double button ( second one is empty )

http://screencast.com/t/5JkHItru
http://screencast.com/t/mNzXTS7iv

2 it activates save on that button click , with or without js 

so any button used in custom option will activate save action.

**Comment by moldcraft** [comment]
Thank you for reporting this

**Comment by danyj** [comment]
That fixed the save action but not the double button

**Comment by danyj** [comment]
And that second empty button when clicked still activates save action. 
See this http://screencast.com/t/lJfytelCetwO

**Comment by moldcraft** [comment]
[fixed](https://github.com/ThemeFuse/Unyson-Documentation/commit/14bfadca07289f0304218be64318dff93b6149d1)

**Comment by danyj** [comment]
Duhhh, :)  sometimes is just there and you dont see it. 
Thnx !
