### ISSUE TITLE
shortcode without builder in tinymce?

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#2530]
Is it possible to have shortcode in tinymce editor and not in the builder?

I mean unyson shortcode, with popup etc.

**Comment by danyj** [comment]
Yes , 
http://manual.unyson.io/en/latest/extension/wp-shortcodes/index.html#content

enable/install WP Shortcodes extension

and if used in option type WP editor enable the shortcodes by setting 

`'shortcodes' => true,
`
in option settings 



@GheorgheP   missing info about it here

http://manual.unyson.io/en/latest/options/built-in/wp-editor.html

**Comment by danyj** [comment]
but the layout shortcodes are not available , sections,columns

**Comment by sandrodz** [comment]
@danyj sweet! I swear I've looked through the manual and didn't find anything about it. Maybe I was looking at wrong section.

**Comment by danyj** [comment]
See this also 
https://github.com/ThemeFuse/Unyson/blob/43b6a1e1dee556c9934dd2acc065d53948cb4d15/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L24


@GheorgheP   that part should be in the manual http://manual.unyson.io/en/latest/options/built-in/wp-editor.html

**Comment by sandrodz** [comment]
@danyj Do you want to keep issue open for @GheorgheP  to amend docs?

**Comment by danyj** [comment]
Sure but I think he will see it :)

**Comment by sandrodz** [comment]
I declared `wp-shortcodes` in the manifest.php loaded / installed it.

I've created an empty shortcode dir with view/config/options.php files.

What do I need to put in config.php to make it appear inside wp-editor? doc is not saying anything.

**Comment by sandrodz** [comment]
<img width="1172" alt="screen shot 2017-04-16 at 3 52 26 pm" src="https://cloud.githubusercontent.com/assets/8479569/25070979/cff1aae4-22bc-11e7-9262-a857675fd3b2.png">

This is my base shortcode, how do I make it appear in tinyMce?

**Comment by danyj** [comment]
your config is bad 
follow this please 
http://manual.unyson.io/en/latest/extension/shortcodes/#creating-a-new-shortcode

**Comment by andreiglingeanu** [comment]
@sandrodz Please make sure that your shortcode works correctly in the page builder itself first. After this you can use the method @danyj suggested for adding it into the tinymce.

**Comment by sandrodz** [comment]
<img width="1186" alt="screen shot 2017-04-16 at 10 49 45 pm" src="https://cloud.githubusercontent.com/assets/8479569/25073399/07dca7bc-22f7-11e7-9713-6e8bda0a2304.png">
Okay, so I'v built a normal page builder shortcode. What is the next step?

**Comment by sandrodz** [comment]
p.s. I don't want to use it in option type editor. I want these shortcodes in normal blog post editor.

**Comment by andreiglingeanu** [comment]
@sandrodz Are you seeing your new shortcode in the Unyson Shortcodes popup?

**Comment by sandrodz** [comment]
@andreiglingeanu I see it in page-builder, I don't see `Unyson Shortcodes` in wp editor.

<img width="913" alt="screen shot 2017-04-17 at 10 36 08 am" src="https://cloud.githubusercontent.com/assets/8479569/25081185/dae2163a-2359-11e7-80e3-2aecdeb7b347.png">
<img width="912" alt="screen shot 2017-04-17 at 10 36 44 am" src="https://cloud.githubusercontent.com/assets/8479569/25081183/dae0d1bc-2359-11e7-94bb-fc42064879cd.png">
<img width="910" alt="screen shot 2017-04-17 at 10 36 48 am" src="https://cloud.githubusercontent.com/assets/8479569/25081186/dae7e484-2359-11e7-8c39-c38fec112bb1.png">

![screen shot 2017-04-17 at 10 37 15 am](https://cloud.githubusercontent.com/assets/8479569/25081200/f315c59e-2359-11e7-8612-a9c1d810c755.png)

**Comment by andreiglingeanu** [comment]
I suspect that's because you are trying on a custom post type. Can you try to [activate page builder](https://cl.ly/k1bK) for your _articles_ post type and see if `Unyson Shortcodes` will be back.

I'm 70% it won't help because `Unyson Shortcodes` are completely separated from page builder and they don't depend on each other, thus the problem should be somewhere else for you. Can you confirm that you are on latest version for all extensions and unyson itself?

**Comment by sandrodz** [comment]
Can you show me how that button looks in editor?

I'm on Version 2.6.10 unyson.

**Comment by andreiglingeanu** [comment]
Hey @sandrodz!

Sorry for late reply. Here's a [screen](https://cl.ly/kExx) of that button. 

I don't think bedrock might be an issue here. You might want to check if this [tinymce plugin](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/338da915a754ac5870d86fbc517dcc8b4e302123/class-fw-extension-wp-shortcodes.php#L48-L51) got loaded correctly.
