### ISSUE TITLE
WP Shortcodes dynamic CSS info

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2531]
@andreiglingeanu   bud , this here says no dynamic CSS

![screenshot_10](https://cloud.githubusercontent.com/assets/2340172/25064895/0023b04e-2205-11e7-8d3a-a50c1e772011.jpg)

how if  static.php is yes?

**Comment by andreiglingeanu** [comment]
It means that you'll have to manually parse options in `static.php` (which you can't as far as I know, `$atts` are not passed there) and enqueue the shortcodes from `wp-editor`, as in example for case _3_.

The idea is that you need `$atts` in `static.php` in order to enqueue dynamic CSS correctly for `wp-editor` shortcodes.

**Comment by danyj** [comment]
> , $atts are not passed there

I have this in every shortcode  static.php


```
if(!function_exists('_thz_shortcode_name_css')){
	
	function _thz_shortcode_name_css ($data) {
	
		$atts 			= _thz_shortcode_options($data,'shortcode_name');
		
		
		fw_print( $atts );

	}
	
	add_action('fw_ext_shortcodes_enqueue_static:shortcode_name','_thz_shortcode_name_css');
}
```


and this is the helper that gets them 


```
function _thz_shortcode_options($data,$shortcode){
	
	$atts = shortcode_parse_atts( $data['atts_string'] );
	$atts = fw_ext_shortcodes_decode_attr($atts, $shortcode, $data['post']->ID);
	
	return $atts;
}
```

**Comment by andreiglingeanu** [comment]
@danyj Okay, and what's the issue all about then?

**Comment by danyj** [comment]
>what's the issue all about then?

I have none, is just that for me is natural that if static.php is in the dynamic css is in also , and your table above states otherwise, even here 
http://manual.unyson.io/en/latest/extension/shortcodes/#enqueue-shortcode-dynamic-css-in-page-head

the recommended usage is as I described above so it is automatic that dynamic css is in if static.php is included. 

or am I missing something?

**Comment by andreiglingeanu** [comment]
@danyj I think I encountered some problems with `shortcode_parse_atts` some time ago. I agree, this looks very nice but it didn't worked automatically for _all_ cases, if I recall correctly.

Please do us know if you find any parsing issues with your method. If it is good enough -- worth adding it into the framework itself -- I'd be happy to.

**Comment by danyj** [comment]
ok , will let you know if there are issues but so far this has worked ok for me since @moldcraft  explained the usage which is more than year ago.

**Comment by thednp** [comment]
@danyj is this implemented yet?

**Comment by danyj** [comment]
@thednp  implemented? you mean builder shortcode and dynamic CSS?   yes I have been using it for long time now
