### ISSUE TITLE
Can't activate slider

### ISSUE THREAD

**Issue by eatwalklearn** [ThemeFuse/Unyson#2532]
Hello
I have created a row on my page that is 1/2 shape.
In the first cell, I have a text box.
In the second cell, I have a slider element.
When I click on the slider element, it tells me to create a new slider.
I have created two new sliders.
On the menu bar, I see "Slider."
When I go to "Slider", I can see my two newly created sliders.
But I can't figure out how to actually activate the slider
When I go back to my page and go to the second cell, when I click on Slider, I'm expecting it to ask me which slider I want to use, but instead it keeps telling me there are no sliders and I need to create a new one.

Please advise.

**Comment by GheorgheP** [comment]
Are you working on our scratch theme or on an author related theme?
I guess on an author related, you need to contact the theme author for that, there may be some filters on the slider type you can add using the slider shortcode or may be other constrains.
