### ISSUE TITLE
Gmaps retired version

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson#2534]
In console I get this message when using gmap from unyson

Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

```
You may have supplied a retired version in your script element. The versions 3.0 - 3.25 have been retired, and you might be receiving 3.26 instead. Please update your application to use one of the available versions.
```

**Comment by danyj** [comment]
@GheorgheP   this needs to be changed to latest gmap version 3.27

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/map/static.php#L7
