### ISSUE TITLE
Backup pages

### ISSUE THREAD

**Issue by Bodrosh** [ThemeFuse/Unyson#2535]
Hi. Can I make a backup of one page? I first use a local server, then I upload it to the Internet. Each time to make a full backup copy is inconvenient, and if users add information to the site, when restoring my local copy, everything is deleted.

**Comment by GheorgheP** [comment]
At the moment this is not possible.

**Comment by Bodrosh** [comment]
Is there any way to transfer one page to another server? Use a plugin or export from a database? I tried to export records from this page from wp_post, but it did not work. Apparently the data is stored in linked tables?

**Comment by Bodrosh** [comment]
@GheorgheP, Is there any way to transfer one page to another server? Use a plugin or export from a database? I tried to export records from this page from wp_post, but it did not work. Apparently the data is stored in linked tables?

**Comment by danyj** [comment]
export with this 

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/33#issuecomment-131866126

**Comment by Bodrosh** [comment]
@danyj, Thanks, where are the templates stored? It can be transferred to another project, to another hosting?
