### ISSUE TITLE
Unyson css hide publish button 

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2537]
One of my our sites publish button gone after the update the unyson plugin.

And when we inspect the issue. and found unyson CSS hide the button with CSS. If i disable Unyson plugin everything work fine.

![aa](https://puu.sh/vq8Wm/e0a8cdedbe.png)

### Also, there is no Default editor button as well.

![aa](https://puu.sh/vq93r/f24ddf1e33.png)

### Console error 

![aa](https://puu.sh/vq96Q/30957d1a25.png)

### wpeditor also not working
![aa](https://puu.sh/vq9qw/16bb7afb2c.png)

If unyson plugin deactivate everything working fine.

**Comment by GheorgheP** [comment]
This is because of that error from console. Please check out if you do not have any plugins that may create this problem.

**Comment by Ataurr** [comment]
If you want to check I will give you login details to check.

**Comment by Ataurr** [comment]
I have tested with default WordPress theme. And disable all plugins. Still same issue.
Only Work if disable unyson plugin.

**Comment by GheorgheP** [comment]
Please provide the login details on `pisarenco[[dot]]gh[[at]]gmail[[dot]]com`

**Comment by itlike** [comment]
Helo. I have the same problem. How can I solve it?
