### ISSUE TITLE
Error on Unyson plugin activation

### ISSUE THREAD

**Issue by nwestwick** [ThemeFuse/Unyson#2540]
Purchased the Alkaweb WOffice 2.4.1 theme from Themeforest.net, installation of which requires the Unyson framework.

Downloaded & installed Unison 2.6.16.  Whenever I try to activate the plugin I get the following error message:
---------------
Parse error: syntax error, unexpected '[' in /web/intra/htdocs/wp-content/themes/woffice/framework-customizations/extensions/woffice-time-tracking/helpers.php on line 99 
---------------

Github readme states Unyson min requirements:
Wordpress 4.4 or greater - 4.7.4 running
PHP 5.2.4 or greater - 5.3.17 running

Any pointers?

**Comment by danyj** [comment]
contact woffice theme developer , this is not framework related

**Comment by GheorgheP** [comment]
It seems that the developers of **Alkaweb WOffice** use the php 5.4 array style `[]` instead of classic `array()`, but you have php 5.3 or less. They should specify the required php version in theme requirements as they do not respect wordpress php compatibility.
