### ISSUE TITLE
Cannot configure plugins on a Multisite Multi-network

### ISSUE THREAD

**Issue by UberNomad** [ThemeFuse/Unyson#2543]
I've tried all kinds of different configurations. I have two main networks, and I have network activated Unyson, on both networks, I have activated on network sites only etc, but I can only configure plugins on the main network / site.

If I try to configure anything on the second network / site, the values just revert to null values, when you try to save anything...

Any ideas anyone, I've re-created these networks twice from the ground up already.

Thanks !

**Comment by GheorgheP** [comment]
What do you mean by 2 main networks? Also what do you mean by configuring plugin?

**Comment by UberNomad** [comment]
a Multi-network, running two Multisite Networks. 

Configuring the plugins, I should mention that I use WOffice, and they extend Unyson with additional functionality, or additional plugins. None of these plugins would retain any values in the second site, only the main site. Using Ron's multi network code, the BBPress multi-networks stuff etc.

I actually reverted back to a single network, that runs the two sites now, and it's functioning, not my ideal setup, but working ..

**Comment by GheorgheP** [comment]
Could you provide a video showing what is not working as I do not really understand what do you mean?

**Comment by UberNomad** [comment]
Basically, the Woffice extensions does not handle the multi-network setup properly. It's about activating inside one network, the main network, which is fine, and is cool for sub-sites inside that network, but as soon as you activate inside a second network, you have problems. There is only one master table set. ..

**Comment by GheorgheP** [comment]
Did you test this with default WordPress theme to be sure the problem comes from Unyson and not from Woffice? Because I have multiple network installations and I don;t have any problems with them.
