### ISSUE TITLE
Hopepage all sections elements are collapsed into Textblock Shortcode

### ISSUE THREAD

**Issue by github10011** [ThemeFuse/Unyson#2547]
Hi

My homepage all sections element are collapsed into a shortcode like Textblock. What should I do now for that? Please its very urgent for me.

Screenshot : http://prntscr.com/f0km03

My homepage should look like this : http://deepbloo.com/en/homepage/
But its appear look this ones due to collapsed every section into a Textblock Shortcode : http://deepbloo.com/en/home/

Kind Regards
github10011

**Comment by github10011** [comment]
Hi
Its already 2 days gone but did not get any notification about my issue. Why

**Comment by GheorgheP** [comment]
We are aware about this issue, but we cannot reproduce it. It happens in very specific conditions.
Unfortunately the only solution is re-build the broken page.
