### ISSUE TITLE
Editor wp-shortcodes  double clone save all button

### ISSUE THREAD

**Issue by pionir** [ThemeFuse/Unyson#2548]
Add text block shortcode to builder make sure that wp-shortcodes is enabled.
Inside the builder editor add any of your shortcodes via unyson shortcode editor button.
Click on save all, re-open text block, click on your editor shortcode and the popup comes with double save button and js error. 

http://prnt.sc/f0o1y6
http://prnt.sc/f0o24o

**Comment by andreiglingeanu** [comment]
Hey @pionir. This issue is already fixed here: https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/pull/87

**Comment by andreiglingeanu** [comment]
Can be safely closed, I think.
