### ISSUE TITLE
Updating the framework broke the whole plugin

### ISSUE THREAD

**Issue by dobromir-hristov** [ThemeFuse/Unyson#255]
Hi. Today I updated to the latest version of the plugin and good thing i tried on local first.
After updating I had to re Enable the extensions i use. Upon installing Page Builder i get this:
 Fatal error: Class 'FW_Option_Type_Builder' not found in {something something}\wp-content\plugins\unyson\framework\extensions\forms\includes\option-types\form-builder\class-fw-option-type-form-builder.php on line 9
I tried downloading Unyson from github and added it clean. Again on downloading the Page Builder I got this error.
Edit
Adding the Builder Extension manually fixed the issue.

**Comment by sergiubagrin** [comment]
@dobromir-hristov - i will check it right now

**Comment by sergiubagrin** [comment]
@dobromir-hristov - can you give me more details? 

I tested it on Windows/ PHP 5.5.2: http://screencast.com/t/mkGiyLxJTbdg

Right now i test it on more devices

**Comment by sergiubagrin** [comment]
We found something. We start test it right now. On some devices Forms is loading before Builder extensions.

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/471cde3673f8c0039d69069f00857a329ee11744

**Comment by blackyangell** [comment]
I have the same error. After installing Unyson and Extensions, there is a link "Update extensions". After clicking it I get: 

"Class 'FW_Option_Type_Builder' not found in {something something}\wp-content\plugins\unyson\framework\extensions\forms\includes\option-types\form-builder\class-fw-option-type-form-builder.php on line 9"

I use TGM Plugin Activation in my theme to call Unyson installation.

Please, tell me, what I'm doing wrong? Thank you.
