### ISSUE TITLE
Visual Page Builder: Shortcodes are giving a notice

### ISSUE THREAD

**Issue by Rokito** [ThemeFuse/Unyson#2551]
Hi,

I keep getting a notice on some of the shortcodes that come with the Visual Page Builder. Do you guys have any idea what's going on?

Example:
: Invalid argument supplied for foreach() in /wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/accordion/views/view.php on line 6

**Comment by danyj** [comment]
where is the notice, back/front? 

did you add accordions?
