### ISSUE TITLE
Color palette in typography v2

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2552]
Typography v2 has a color-picker option, but I can't find a way to add a palette to this picker. 
Is it possible?

**Comment by GheorgheP** [comment]
You cannot, but you can copy the `typography-v2` option folder in your theme/plugin, rename it and create a new `typography` option where you'll replace the color picker with palette.

**Comment by warudin** [comment]
OK, that's a pity. The same goes for Typography v1?

**Comment by GheorgheP** [comment]
Unfortunately, yes.

When I will have time I will review this, as the options types have a lock of modularity
