### ISSUE TITLE
LastPass slowing down theme admin tab switch if you have many input fields

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2553]
This is on live servers only , I did not notice it on local but live is very noticeable, 

here is The core theme demo ,   tabs show/hide is slower once you click on save , 

and it gets slower with every save

http://take.ms/Pi176

the more tabs you have the slower it gets . Looks like lazy_tabs bubbling to me.

**Comment by danyj** [comment]
this is not related to lazy_tabs , turn them off in theme config and every tab is slow

**Comment by danyj** [comment]
OK this one is huge and is not Unysn issue , 

Chrome LastPass extension ,  gets attached to each input in theme settings KILLING  the tabs show/hide

this

chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js


http://prntscr.com/f1j4ob

related 
https://forums.lastpass.com/viewtopic.php?f=6&t=103635
http://stackoverflow.com/questions/21841850/javascript-scroll-function-slow-lots-of-timer-fired-onloadwff-js310-weasel

**Comment by GheorgheP** [comment]
Please try out with this version https://github.com/ThemeFuse/Unyson/tree/issue%232494, tell me if it will help.

**Comment by danyj** [comment]
@GheorgheP , this is not related to Unyson at all ,   
I tested everything is not lazy_tabs ,   LastPass Chrome extensions 100%,  
they want us to do autocompete off in theme form and adjust settings per user in LastPass ,  
Unyson cannot fix this


> Please try out with this version

 I see you made  change because of https://github.com/ThemeFuse/Unyson/issues/2494

il test in few min  it and let you know

**Comment by GheorgheP** [comment]
You see, when the save  button is hit, there were initialized all tabs and may be this event creates this problem.

**Comment by danyj** [comment]
> You see, when the save button is hit, there were initialized all tabs and may be this event creates this problem.

No this is exactly what goes on 

On first load I see first tab only which has about 8-12  text input fields , so the LastPass is ok with that amount and is not slowing anything down , 

when I hit save , all   tabs init with 300 options and bunch of text inputs , 
now LastPass is trying to autofill each of them .  


I disabled lazy_tabs and the tab swith lag is immediate , because all inputs are there and LP is messing with them . 

If I disable LastPass everything works , 


this  should work in LastPass , wich is setting to not do anything for given domain/url 

![ddedwed](https://cloud.githubusercontent.com/assets/2340172/25528359/b688b308-2c1d-11e7-9ba6-ba6b4a013a08.jpg)


but id does not work 

how I finally got it to work , is to add domain to each of those select options , and only than can I keep LastPass on and no lag in theme admin 

doing this **tremendously** increased every option popup load time also , since LastPass was messing with inputs in popup as well

**Comment by andreiglingeanu** [comment]
Is their extension code available somewhere? Or it is closed source?

**Comment by danyj** [comment]
@andreiglingeanu  I am not sure   but when you install the extension this file is the culprit 

chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js

**Comment by danyj** [comment]
@andreiglingeanu  see this http://stackoverflow.com/a/41280595/594423

these are that LastPass is targeting 

`!c.form && ("text" == c.type || "password" == c.type || "url" == c.type || "email" == c.type) && lpIsVisible(c))


so ANY text basically
`

**Comment by andreiglingeanu** [comment]
Well yeah, the problem is in the extension itself, you are right. There's nothing really Unyson can do about it. The only solution is to ignore pages with theme settings from LastPass settings. Or get LastPass to make its Chrome extension better :)
