### ISSUE TITLE
Unyson Backup Hanging PHP 7.0

### ISSUE THREAD

**Issue by RtypeStudios** [ThemeFuse/Unyson#2554]
I've installed unyson via theme fuse on my blog. The application is getting stuck at the directory clean up:

When I try and install the demo content:

![image](https://cloud.githubusercontent.com/assets/990114/25513353/184932a0-2c07-11e7-8a11-9e9928fe08f1.png)

or when taking a backup we get the same issue:

![image](https://cloud.githubusercontent.com/assets/990114/25513361/23292270-2c07-11e7-97d1-6f030af1214f.png)

I've left it for hours doesn't seem to recover, just sites there polling without ever finishing.

No errors are appearing in:
wordpress debug
nginx logs
php-fqm logs

I'm running Ubuntu 16.04 with PHP 7.0 running behind nginx 1.10.0. 

Also running on a multisite install.

**Comment by GheorgheP** [comment]
You are on local machine or live serve?

**Comment by RtypeStudios** [comment]
It is running on a live server.

**Comment by GheorgheP** [comment]
Could you provide the details on `pisarenco[[dot]]gh[[at]]gmail[[dot]]com`?
WordPress login, ftp.

**Comment by RtypeStudios** [comment]
Fixed by a complete reinstall of wordpress. Thanks for your help.
