### ISSUE TITLE
Is there a way to change post_meta / option_name(s) (fw_options, etc.)

### ISSUE THREAD

**Issue by NoahjChampion** [ThemeFuse/Unyson#2555]
Hi. 

**Thanks for this awesome Framework.** 

I've made my first custom theme which was on a different framework and now I'm switching to Unyson as the future of that framework is kind of uncertain and I don't want to have the first updates of my theme release to be changing a framework, haha. But this is good because I got to read more and see the completeness and power of Unyson. Ok, moving from chit chat. 💯 

I've migrated my `post_meta` options over, but I see all the options are stored in `fw_options` for post meta. I'm trying to avoid rewriting various parts of my theme if possible, while switching to Unyson. So after searching and working for about the last 24 hours, my initial question is this...

Question 1: Is there a filter or config option that will allow me to have my post meta option name changed from `fw_options` to something else for the metabox rendered?

If not this is a suggestion/feature request. 

In my previous Framework I had an option like this for setting the post_meta option name or page settings option name for each instance of settings rendered. 

```php
$options = 
array(
	
	'option_name' => 'this_value_changes_fw_options_to_my_post_meta_option_name',
	
	array(
		'title'   => __('Main_Tab_1', $text_domain),
		'type'    => 'tab',
		'options' => 
		array(
			
		),
	),
	
);
```

Or maybe something like this would be more sensible considering it is the "settings" file instead of the "options" file.

```php
$options = 
array(
	
	// Post Meta Settings
	
	fw()->theme->get_options('postmeta-settings', 'this_value_changes_fw_options_to_my_post_meta_option_name'),
	
);

```

**Comment by andreiglingeanu** [comment]
Hey @NoahjChampion!

You should really give a read to [Custom Save Locations](http://manual.unyson.io/en/latest/options/storage.html#content). I think you would not need a filter for `fw_options` after you digest this material.

Good luck.

**Comment by NoahjChampion** [comment]
@andreiglingeanu Thanks man!!! 

Ok, awesome, great thinking. I see this allows for each type to have custom save location. That's powerful. 

Is there a set global way so all options within an option array to save to the custom location rather than having to specify it for each type rendered?

**Comment by andreiglingeanu** [comment]
@NoahjChampion Yeah, it is pretty powerful.

There's no global setting for `fw-storage`, each specific file has a default _location_ to be saved in. But, you can easily write a function which will receive an array of options and recursively add a `fw-storage` key to it.

Also, [here's](https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/database.php#L163-L169) the getters and setters for the post options. You can come up with a pull request which will introduce a filter in them, I'll be happy to review it. By using this filter you'll be able to get a specific meta name (which is currently `fw_options`) and you can even do this dynamically - you are receiving the current post you're saving options for.

Your imagination is the limit.

**Comment by NoahjChampion** [comment]
@andreiglingeanu 

Ok, understood. Could you provide an example of what that will look like? Then I can dig deeper into it. I would be new to a recursive function which I only gained some knowledge of via various StackOverflow forums. But concept I think I get what you're saying. 

Ok, about the getters and setters. Looks simple enough. Just need to get more familiar with the workings of everything. 

What I'm going to do/work on, if you don't mind is creating video walk throughs? I can learn the basics (non-very-advanced) get familiar then do vids for that, then do the deeper ones as I do them. For me I find that is lacking or is there a channel for the such? And create maybe a full demo sample data install? 

For example: I couldn't find how to add a metabox title to the metabox. I only found it by see it in the video and paused the video to copy that settings information which worked. When I searched the site for the metabox title it brought up links but nothing I saw that explained that simple part. Wrong? The video I watched is @ http://manual.unyson.io/en/latest/options/introduction.html?highlight=metabox

This is the best vid I found otherwise, but it's not English @ https://www.youtube.com/watch?v=WFEgmNfvpnw 💯

**Comment by NoahjChampion** [comment]
And just in testing the custom save location for types. Is there something I'm missing? 

When simply saying... 

`'fw-storage' => array('type'  => 'post-meta', 'post-meta' => '123',),`

Can I only do that for one type?

I was hoping that if I set various types to save to the same location that data would be saved in the array for multiple type values, but it seems to only work with on type value saved. So what I mean is if I specific two type values to save to the same location only one saves, causing the value to be the value for the other types as well.

**Comment by andreiglingeanu** [comment]
@NoahjChampion I understand the fact that there is a need for more material on the subject.

About that `fw-storage` thing. I think you should wrap all you options inside a [`multi`](http://manual.unyson.io/en/latest/options/built-in/multi.html) and apply the `fw-storage` to the multi itself. It is a bit restricting, yeah, but that's the best of the both worlds.

**Comment by NoahjChampion** [comment]
@andreiglingeanu 

Thanks!!! Ok, I saw that option actually earlier, went back looking for it, but directly relate the title to the feature it applies. But got it now. 

Ok, so is there room/need/room for creating video tutorials on Unyson?

**Comment by andreiglingeanu** [comment]
> Ok, so is there room/need/room for creating video tutorials on Unyson?

Definitely do that if you feel like having desire for doing so! A lot of the issues here are just questions about the framework, not issues per say. Having some high quality material to link those beginners to is a nice thing.

**Comment by NoahjChampion** [comment]
@andreiglingeanu 

Thanks for this!! 

After understanding the `multi` which took some time. The demo file provided more context for rather than the doc :D So, like I mentioned with the video tutorials, I can help with that. 

Back to this though, the `multi` still leaves me the issue because I need to change the option name for the post_meta, meaning the `fw_options`. See screenshot. 

![image](https://cloud.githubusercontent.com/assets/6123260/25559886/d4d4c95a-2d12-11e7-99cb-1c8e7c590c09.png)

I created a solution for now (for me) and when I can add the filter should be pretty easy to migrate/switch over to when using the filter. Here is just an example of the code I created to provide context and for someone else interested.

It's simply getting the `fw_options` values during the `save_post` action and copying that data to my own option name (in this example, `__new_data__`). Then later when the filter is added for custom option names I can write some routine to delete the fw_options as it wouldn't be being used, at least in my theme then. 

```php
add_action('save_post', 'save_post', 10, 3);
function save_post($post_id, $post, $update) {
	
	// Set our old data exists related variables
	
	$old_data_exists = get_post_meta($post_id, 'fw_options');
	
	// If our old data exists variable is TRUE
	
	if ($old_data_exists) {
		
		// Set our various data related variables
		
		$old_data        = $old_data_exists[0];
		$update_new_data = update_post_meta($post_id, '__new_data__', $old_data);
		
		// If our add new data variable is TRUE add our new data otherwise update our new data then delete our old data
		
		$update_new_data;
		
		// Set our data related variables
		
		// $new_data        = get_post_meta($post_id,    '__new_data__');
		// $delete_old_data = delete_post_meta($post_id, 'fw_options');
		
		// If our old data still exists let's delete it
		// @Todo->when filtered applied to Framework
		
		// if ($old_data_exists) { }
		
	}
	
}
```

**Comment by NoahjChampion** [comment]
Hmmm... I'm actually re-reading and seeing you said to add the fw-storage to the multi, which I didn't do after taking awhile to see where in the array the multi should be, haha. Ok, so I'm going to go back and try this to, just to confirm and update.

**Comment by NoahjChampion** [comment]
@andreiglingeanu 

Ha, ok. This works too. Lol. 

Using multi and adding the `fw-storage` to the multi itself. Thank again. Appreciate it.

**Comment by andreiglingeanu** [comment]
Yeah, the idea was to use `multi` with `fw-storage` attached to it. I'm glat you got it working, good luck!

**Comment by danyj** [comment]
@NoahjChampion   what is that inspector option bud ?

**Comment by NoahjChampion** [comment]
@andreiglingeanu 

Yeah, thanks! Simple once I got a hold of it! 💯 

@danyj 

Old plugin I've been using for 2+ years I think. I may be the only one, lol. But it's saves sooo much time. @ https://wordpress.org/plugins/inspector/

**Features**

* View/Delete option via Ajax
* View/Delete post meta via Ajax
* View current admin screen information
* View current user information
* View admin menu items

I made about a 60 second screencast for you to see its options and where they're located.
@ [Video - Option Inspector](https://www.youtube.com/watch?v=e9Lq4kGPmLM&feature=youtu.be). Since it has no screenshots, I took a risk, but well worth ever since. 

![image](https://cloud.githubusercontent.com/assets/6123260/25564309/5e4a71c4-2d7e-11e7-940a-5936a03e65bf.png)

**Comment by NoahjChampion** [comment]
@andreiglingeanu 

I had some other ideas, just thought I would mention them and see what you think. 

Regarding this same issue but alternative choices for a solution. 

An option for: 
```php
// Which would stop the default data storage methods for this instance, 
// used in the top level of the array
`'storage' => FALSE`

// Which would stop the default data storage methods for this instance
`'fw-storage' => array('default' => FALSE, 'type' => 'post-meta', 'post-meta' => '__TEST__',)`

// The filter which we spoke about
// I think I had another idea but don't recall it off hand right now. 
```

**Comment by danyj** [comment]
@NoahjChampion  thank you!

**Comment by NoahjChampion** [comment]
@danyj Welcome!!

**Comment by andreiglingeanu** [comment]
@NoahjChampion I think having helpers for assigning `fw-storage` in individual arrays is better because of:

1. You can easily document those helpers and you don't loose them. Those keys can easily lost or mistyped.
2. By having only helpers around you can scope this `fw-storage` rewrite for parts of `options.php` files. Implementing that flexibility in terms of array keys is a lot harder and is error prone.

Those keys look nice in theory but you can't beat a function call, especially if that function is cached properly and it is fast.

**Comment by NoahjChampion** [comment]
@andreiglingeanu 

Ok, sounds good. Thanks!

**Comment by andreiglingeanu** [comment]
@NoahjChampion Welcome! Hope I was helpful.
