### ISSUE TITLE
HOOKS.PHP ...HELP?!?!

### ISSUE THREAD

**Issue by lennondesignllc** [ThemeFuse/Unyson#2556]
I am currently experiencing this error on multiple sites.
I need help to remedy ASAP. Thank you!

Warning: session_start(): open(/home/214451/data/tmp/sess_30480c43ea96fa013c8d7fe9f9ee8344, O_RDWR) failed: No such file or directory (2) in /nfs/c12/h01/mnt/214451/domains/utahpodcastnetwork.com/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 256

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /nfs/c12/h01/mnt/214451/domains/utahpodcastnetwork.com/html/wp-content/plugins/unyson/framework/includes/hooks.php:256) in /nfs/c12/h01/mnt/214451/domains/utahpodcastnetwork.com/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 256

**Comment by GheorgheP** [comment]
You need to contact your hosting provider as there seems to be a problem with session file read/write permissions. When the `session_start()` functions is called, php tries to create/open the session file.
