### ISSUE TITLE
Addable Popup with Fw Storage Issue (storage id not processed)

### ISSUE THREAD

**Issue by NoahjChampion** [ThemeFuse/Unyson#2558]
When using `addable-popup` and `fw-storage` the option_id of the addable popup is not processed in the stored array data. 

Screenshot of code example... 

![image](https://cloud.githubusercontent.com/assets/6123260/25569962/c6c8c3d0-2ded-11e7-87f9-8400c680b4e2.png)

The stored data which is generated from the `fw-storage` setting screenshot... 

![image](https://cloud.githubusercontent.com/assets/6123260/25569982/f59f3270-2ded-11e7-9fcb-ae3324f43be7.png)

But when when not using `fw-storage` the array results looks like... 

![image](https://cloud.githubusercontent.com/assets/6123260/25570000/1b266fa4-2dee-11e7-95ea-c7488847956c.png)

Just reporting as it's probably an issue with the framework? Or is there something I could do to adjust this? I would like the array key of `layout_settings` to be used in combination with my `fw-storage` setting.

**Comment by andreiglingeanu** [comment]
@NoahjChampion I was not the guy who initially implemented that storages mechanism but I'll try to inspect that problem, it seems to me that this really might be an issue in framework. I'll get back with more info soon.

**Comment by NoahjChampion** [comment]
@andreiglingeanu Thanks. Appreciate it!

**Comment by andreiglingeanu** [comment]
@NoahjChampion You will have to test if the `post-id` is inferred correctly. When you are not specifying the `post-id` in `fw-storage` the storage type tries to infer it automatically, check that [here](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-storage/type/class-fw-option-storage-type-post-meta.php#L76-L80). The logic which actually extracts a `post-id` when you are not passing one is [here](https://github.com/ThemeFuse/Unyson/blob/d9bc9acb56bd98ce4ec99e35945ae84f1fec88b3/framework/helpers/database.php#L171-L173).

Try to pass a hardcoded `post-id` like that, for testing purposes and see if the setting happens that way:

```php
'fw-storage' => array(
  'type' => 'post-meta',
  'post-meta' => 'name-for-field',
  'post-id' => 'SOME_HARDCODED_ID'
)
```

**Comment by NoahjChampion** [comment]
@andreiglingeanu Ok, thanks. Got it. Works perfect. Appreciate it. Apologies about the delay. 

In regard to browsing the sources, that's where I think the online documentation should shine. 1 for new comer ease, but surely for newer devs who would get more confused trying to figure things our from code source, as online step by step instructions would be what they're looking for. 

But no problem, I will try to help with presenting that.

**Comment by andreiglingeanu** [comment]
Awesome, You're welcome!

Yeah, extensive docs for that feature would be awesome but they take a lot of time and we're onto other things (which will also improve the way we are handling option types).

**Comment by NoahjChampion** [comment]
@andreiglingeanu ok, sounds good! 

Yep, I understand. Thanks! Appreciate it!
