### ISSUE TITLE
Shortcode inside Pricing table

### ISSUE THREAD

**Issue by Thomaswebstich** [ThemeFuse/Unyson#2559]
Does anyone know a way I can use shortcode or HTML inside a pricing table elements?

**Comment by GheorgheP** [comment]
To render HTML you just need to write html code in the description field. What about shoertcodes, you need to modify the pricing table view, as we are just printing the field content: https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/table/views/pricing.php#L24

But you need to do something like: 

```php
echo do_shortcode(fw_akg( 'textarea', $atts['table']['content'][ $row_key ][ $col_key ], '' ))
```
