### ISSUE TITLE
codeload.github.com error

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#256]
Latest update does not work properly. Previous 5 worked ok. 

http://screencast.com/t/iv8Qf4vX8PbD
I cannot activate any extensions. 
Also uninstalled the plugin completely , Installed via Add plugin page 

After clicking on install extensions I got the alert that  it cannot access the github page with error 443 

10 min later 
http://screencast.com/t/ZHN5Mtga

and than this again 
http://screencast.com/t/VNgqAdEZxZ

**Comment by danyj** [comment]
And builder says that sidebars is disabled where in fact you can see is active 

http://screencast.com/t/E4qZhnR3qpa

**Comment by moldcraft** [comment]
There is nothing special in the last update https://github.com/ThemeFuse/Unyson/compare/v2.1.23...v2.1.24

I think it's a github (temporary) problem, I am also getting the "Connection timed out" error.
I am investigating this now.

**Comment by moldcraft** [comment]
There is similar issue with codeload.github.com https://github.com/wbond/package_control/issues/551

**Comment by danyj** [comment]
See this process 
http://www.fastswf.com/ejZ5btA

Looks like your extensions that depend on other extensions have issue installing first.

**Comment by moldcraft** [comment]
> Looks like your extensions that depend on other extensions have issue installing first.

First we have to download and install the extension, then look in its `manifest.php` to find the extensions it depends on, the install them (there no other way to know which extensions it depends on). So the dependency install is working fine.

**Comment by danyj** [comment]
I think you did not understand me , 
Builder depends on shortcodes 
Slider depends on population method
those 2 are causing first trouble

**Comment by danyj** [comment]
wait a sec the manifest is not asking for the hidden ones , let me try adding them to the manifest

**Comment by danyj** [comment]
That did not do it , what I did notice is if installed from extensions page it is ok , 
if installed from  Install Compatible Extension page than they fail.

**Comment by moldcraft** [comment]
> Builder depends on shortcodes

This is impossible and has no sense.

> Slider depends on population method

Yes. First the Slider extension is downloaded, then the script reads [its manifest.php](https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/master/manifest.php#L12) and starts to download the pupulation method extension.

**Comment by moldcraft** [comment]
> if installed from Install Compatible Extension page than they fail.

I tried many times and it fails randomly. Some times it fails on second extension, some times on last extension, some times all extensions are installed fine.

I hope it's just a temporary `codeload.github.com` issue and will be fixed soon. The worst case is that they will limit request per IP to codeload.github.com (like they did it with Github API) and we will need host the extensions zip on our servers.

P.S. I wrote them an email and asked if it's something wrong today with codeload.github.com. I will let you know when they will reply.

**Comment by danyj** [comment]
I mentioned it before and saying again , if you need any kind of hosting let me know , I have dedicated boxes. We must eliminate this issue otherwise we all will have hands full with crying customers.

**Comment by moldcraft** [comment]
Hosting the extensions on github is very convenient and easy. Only in the worst case we will begin to host extensions on our servers.

**Comment by moldcraft** [comment]
It seems that even github.com have some lags today.
Today when I posted a comment it took some seconds loading before it was posted.
And now I tried to edit a comment and after some second of loading it showed me [this](http://static.md/38be6ef47a579dbf3f7d40f4ea384c67.png).

**Comment by danyj** [comment]
strange but also scary knowing that we depend on it

**Comment by moldcraft** [comment]
Again a lag when I tried to assign another user to an issue

![screenshot from 2015-02-17 19 10 23](https://cloud.githubusercontent.com/assets/1475489/6233039/dcb5e350-b6d8-11e4-9832-ccef1af7e4aa.png)

----

Even when I tried to upload the above screenshot for this comment

![screenshot from 2015-02-17 19 11 55](https://cloud.githubusercontent.com/assets/1475489/6233050/efc46714-b6d8-11e4-8bcf-1cc683631a9d.png)

**Comment by moldcraft** [comment]
The extensions install is working fine now on my side (the download is fast).

**Comment by danyj** [comment]
Tested 2.1.25, worked well
