### ISSUE TITLE
Unyson Backups extension doesn't work properly on Multisite

### ISSUE THREAD

**Issue by DKudleichuk** [ThemeFuse/Unyson#2561]
Hi

I have noticed that Unyson Backups extension doesn't work properly on multisite (i'm running multisite on local machine). I tried to create content backup and then restore it on another site from my multisite installation. All posts etc were imported, but without any images. Pages were not imported. Image files are in "uploads" folder, but WP media library is empty. Hope you can resolve this problem, thank you

**Comment by DKudleichuk** [comment]
Hi again! It there any change to fix this issue?

**Comment by GheorgheP** [comment]
Actually Backups extension handles multisite very good.
Try to debug the export process, may be it fails somewhere.

**Comment by DKudleichuk** [comment]
The best support ever! Will look for another framework, thanks

**Comment by GheorgheP** [comment]
@DKudleichuk, I understand that you are frustrated, but you just told us that backup doesn't work on multi-site without any other details, not log file, not server/php specs. 
I'm one of the Unyson/Backup developers and I can guarantee that backup works on multisite, but I don;t deny that fact that it in your case may be some problems, but this already requires debugging.
