### ISSUE TITLE
FEATURE: Grid Layout Options and New Option Types

### ISSUE THREAD

**Issue by NoahjChampion** [ThemeFuse/Unyson#2562]
See screenshot below for Grid Example.
The below has a 2 column layout and non grid based option type to compare when using both
This grid supports all columns sizes. 

![image](https://cloud.githubusercontent.com/assets/6123260/25644015/23a3bce8-2f71-11e7-8e01-79c14844892f.png)

You just supply one of preference for operation... 

```php
'grid' => 'open' // This starts the grid with its opening div tag
'grid' => 'start' // This starts the grid with its opening div tag
```
```php
'grid' => 'end' // This ends the grid with its closing div tag
'grid' => 'close' // This ends the grid with its closing div tag
```

Along with those and any options types in between the grid start and grid end you can place an option type or option types in a column like layout by passing the span. 

You just supply...

```php
'span' => 1 // Creates a column equal to 1/12
'span' => 2 // Creates a column equal to 2/12
'span' => 3 // Creates a column equal to 3/12
'span' => 4 // Creates a column equal to 4/12
'span' => 4 // Creates a column equal to 5/12
'span' => 6 // Creates a column equal to 6/12
'span' => 7 // Creates a column equal to 7/12
'span' => 8 // Creates a column equal to 8/12
'span' => 9 // Creates a column equal to 9/12
'span' => 10 // Creates a column equal to 10/12
'span' => 11 // Creates a column equal to 11/12
'span' => 12 // Creates a column equal to 12/12
'span' => 20 // Creates a 5 column equal to 20% width
```

The `'label' => 'value'` and `'desc' => 'value'` have some different styling which places the content of the option type over to the right with the label on the left. To fix that on columns I just added (like a website) a...

```php
'header' => 'value' // Works like label in grid layouts (spans the size of the column)
'footer' => 'value' // Works like description in grid layouts (spans the size of the column)
```

Screenshot example...

![image](https://cloud.githubusercontent.com/assets/6123260/25644448/11e4aa6e-2f74-11e7-943e-041a099d1281.png)

I made this because I had just made it for my previous framework a few weeks ago before switching to Unyson. So I needed this. So I added it, but did it in a way where I can touch it up and do a pull request. Just thought I would get your initial thoughts on it first. You also know to do this I couldn't use a new option type. I did that before in the previous framework before adjusting it. The reason is a new option type requires a separate before and after each option type (the open, span, close). That just gets clunky. But that method also makes it confusing because when doing multiple columns you sometimes have to organize the arrays in a reverse type of order to get what you want on the right side of the column. Might not make sense in hearing it, but I did it already so I know, haha. 

NOTE: The styling can always be changed, etc. The header and footer are more so to highlight the full span. Especially the footer. Below is something maybe more practical/inline.

![image](https://cloud.githubusercontent.com/assets/6123260/25644857/192c8532-2f77-11e7-9d54-9b3da734d01f.png)

**Comment by NoahjChampion** [comment]
Just to add.. here is a older screenshot I had from my previous framework with the layout options I added. This screenshot just showcases more of the grid layout options. 

![image](https://cloud.githubusercontent.com/assets/6123260/25644992/3d51a37e-2f78-11e7-90cd-f6ec2fc14664.png)

**Comment by danyj** [comment]
you are thinking to much and forgetting that you have a full framework behind you , 

this should be done with builder, see contact form in builder

![5b737aaec6854757ba7fbc3e83eeb647](https://cloud.githubusercontent.com/assets/2340172/25652122/dba460e8-2fe6-11e7-8a18-1fb7ef0e6e36.png)

**Comment by NoahjChampion** [comment]
@danyj Thanks!

You'd have to be more specific if you can because I can't fully connect your idea to my idea. I don't see how they completely relate. I see them as 2 different focuses. I just looked at the contact form in the demo, same result. I think you are missing what I'm saying or could you explain more? This is a grid for presenting option types, not for the user to build a grid layout. Currently option types are presented in vertical format. This allows for horizontal and vertical layouts for option types. Which

**Comment by danyj** [comment]
> not for the user to build a grid layout.

that is what I tought this was 

if you are looking for horizontal options I did this 
https://github.com/ThemeFuse/Unyson/issues/1065

**Comment by GheorgheP** [comment]
@NoahjChampion the idea is interesting, but I think for the moment we will not implement it in Unyson core.
Here is why. The fact the Unyson option type are in vertical order did not appear just as a random idea. We try to keep the WordPress design line as close as possible, and wordpress tends to present the options like this.
To make it clear, we don't want people to see any differences between wordpress options and Unyson options.
More then that, WordPress intends to change their design line and we will have to keep up with them.

We create inline options as sub options o fa specific options type, like `typography-v2`, but this far away from your idea.

**Comment by NoahjChampion** [comment]
### Thanks for listening!! 💯  👍  🥇 

@danyj Thanks for the reference. Not exactly what I'm looking for. I need more flexibility, not just inline but row, column, span organization. I also don't like left side labels which inline is a compliment to. But in all, I'm already used to this method, haha. 

@GheorgheP I agree things should stay inline with WP. I'm all for that. 💯  I've done the same for my theme. Aside from the UI today it is rather old school, not unique and limiting. My thoughts, but I do agree all the way. One thing I actually hate about Wordpress is the multiple inconsistent admin editing experiences. I'm used to it, and I think it overall it just not made a priority or looked at overall, but you can't go get a pre-made website service and have nearly 100's of different admin interfaces. It would be ideal It think if Wordpress provided that so devs wouldn't feel such the need to create a different and many times better admin option page editing experience. Even Unyson does that on it's option pages, providing a better UX than Wordpress itself. 

However, since you say this is interesting, I will submit that consider Wordpress does have this in its own, but limited way and this kind of grouping is still presenting options vertically and horizontally. 👍  I also share this for context so if it is ever revisited it is here to reference. I'm cool with it not being implemented as core.

I'm using a lighter, simpler version of **Flexbox** as I already did this for my previous framework. It supports all Flexbox properties as shown @ http://flexboxgrid.com/

Consider in the Wordpress post edit screens... 
There is the Left Side (#post-container-1). 
There is the Right Side (#post-container-2). 
This style of layout is also in the Widgets screen.
This layout style is along the lines what I'm saying but with more flexibility of course.

I needed this kind of column organization because for my Body Layout options I have options for the left sidebar and right sidebar. I want those options to reflect or be more relative to the frontend. Left Sidebar Options on the Left and Right Sidebar options on the Right. And within, options are still vertical. 

@screenshot without annotation

![image](https://cloud.githubusercontent.com/assets/6123260/25941676/466d3e96-3608-11e7-976c-5817164a7848.png)

@screenshot with annotation

![image](https://cloud.githubusercontent.com/assets/6123260/25960720/cd972430-3645-11e7-9fc6-adc8fc60fadc.png)

Here's another example... 
@screenshot with annotation

![image](https://cloud.githubusercontent.com/assets/6123260/25941140/5748ce1c-3606-11e7-9735-033d410e08b0.png)

I also rather detest fixed width left side labels for everything. I don't like the title sentence overlapping like in the screenshot below... 

![image](https://cloud.githubusercontent.com/assets/6123260/25962966/b09144f8-364d-11e7-80a3-3135bd078c70.png)

So I'm closing the issue, but maybe it will come back around or up.

**Comment by NoahjChampion** [comment]
Hi. I also updated the initial comment/post in here to reflect that array code since I updated and to give more context.

**Comment by GheorgheP** [comment]
@NoahjChampion I think we should wait for new WordPress ui redesign. As for current design, to be honest, it cannot be named as WordPress design line, is just a a bunch of inputs in a table style.

So my current thoughts for now is to wait for new WordPress design release, then we'll decide next step.

**Comment by NoahjChampion** [comment]
@GheorgheP ok, sounds good! 

Question, this new design you mention, do you have a link to Wordpress comments on it? I searched online real quick, nothing came up. Is it a trac?

Ok, I did find this.. is this supposed to maybe passed to .org? @ https://developer.wordpress.com/calypso/

**Comment by GheorgheP** [comment]
There was just a mention in wordpress slack I think, there is not any official version for this.

**Comment by NoahjChampion** [comment]
@GheorgheP Haha, ok, thanks! 

Sigh... was maybe going to get excited. Not worth the excitement until more is behind it, haha. 

It looks like the new Wordpress.com UI/UX would be an improvement across the board.

Appreciate it!
