### ISSUE TITLE
unyson plugin - error after wp update - any ideas? login site " white now

### ISSUE THREAD

**Issue by walterj1966** [ThemeFuse/Unyson#2567]
Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/vhosts/1/100413/webspace/httpdocs/miklautz.com/wp-config.php:1) in /var/www/vhosts/1/100413/webspace/httpdocs/miklautz.com/wp-content/plugins/unyson/framework/includes/hooks.php on line 256 Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/vhosts/1/100413/webspace/httpdocs/miklautz.com/wp-config.php:1) in /var/www/vhosts/1/100413/webspace/httpdocs/miklautz.com/wp-content/plugins/unyson/framework/includes/hooks.php on line 256

**Comment by GheorgheP** [comment]
You should get a message above this one telling that it cannot create/read the session file from `tmp` folder due to permissions. You have to contact the hosting provider and ask to set proper permissions for session files directory.
