### ISSUE TITLE
Unyson with read-only rights (pantheon.io)

### ISSUE THREAD

**Issue by fungi-fungi** [ThemeFuse/Unyson#2568]
pantheon.io has kind of strict restrictions on live and test environments as far as I understand they force `define( 'DISALLOW_FILE_MODS', true );` in wp-config.php. So basically, once I deploy from dev to test two extensions Builder and Shortcodes immediately going missing. Since codebase and DB are exactly the same the problem is with write rights. After I've changed capability requirements in `public function can_install()` to `manage_options` extensions at least appeared in Available Extensions but Unison still require me to download then even when they are both already installed. Please let me know fi you had to solve similar problem

**Comment by GheorgheP** [comment]
You say that the shortcodes extension is installed in `/wp-content/plugins/unyson/framework/extensions/shortcodes` and Page Builder in `/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder`, but Unyson still requires their installation? 

Could you make sure that they are installed in provided directories?

[WP Engine](https://wpengine.com/) has same concept of staging and live state and installation/updates/demo-install/backup can be done in staging phase, but after migrating the staging version to live, all works fine.

**Comment by fungi-fungi** [comment]
According to Pantheon.io support, Unyson is not compatible with their infrastructure the only solution they've suggested is to use symlink to `/wp-content/uploads` in order to  'simulate' write rights to `plugins/unyson/framework/extensions/` here is [more about his](https://pantheon.io/docs/assuming-write-access/). Although I really like their workflow idea it's probably not going to work for me at last for this project. So I am moving to wp-engine for now ). Just posting here in case someone will have similar problem. @GheorgheP  thx for response

**Comment by GheorgheP** [comment]
Thank you @fungi-fungi for info.
I contacted the Pantheon support regarding to this problem.

**Comment by ivandotv** [comment]
@GheorgheP Keep us posted about this issue.

**Comment by GheorgheP** [comment]
Is the same classic problem as with WP Engine service. Pantheon has a well defined steps n order to go to production:
 
 - Development
 - Testing
 - Production

You can update/install/remove plugin, theme, or extensions only in development stage, same goes for the backup. The solution here is to notify the user in back-end that he needs to switch to development mode in order to do any of those actions.

Specifically talking about **Pantheon**, there is another issue the we should solve, [Avoid session usage](https://github.com/ThemeFuse/Unyson/issues/2582).

**Comment by zepner** [comment]
There is a feature in Unyson to change the extensions directory, possibly into the uploads directory, which is writable:
http://manual.unyson.io/en/latest/extensions/introduction.html#load-locations

**Comment by iajay** [comment]
Was this ever resolved
I tried all types of symlinks and also the custom folder for extensions.. nothing works :(

**Comment by GheorgheP** [comment]
@iajay, actually this issue still remains for me a bit mysterious. You have the Unyson extensions installed in the proper directory but they are not visible in dashboard? The fact is that in production mode you should not be able to install/remove/update the plugins/extensions, this is a fact, but they should be readable. You can contact me on my private email _pisarenco[dott]gh[att]mail[dott]com_, in order to provide me details of your account to see it.

**Comment by iajay** [comment]
I sent an email to you, but received mailer deamon. Can you confirm ur mail
mine is ajaynagle[att]gmail[dott]com
This is what I sent
Hi
This is regarding the unyson plugin not working in pantheon
Can you provide any help here
I am CCing Matt. Matt has setup your account on the pantheon site
Let me and Matt know what else you need to help
Regards

**Comment by GheorgheP** [comment]
Sorry @iajay, is `gmail`.

**Comment by iajay** [comment]
I have provided you pantheon access, Did you get a chance to check this?
If this does not work, then we will have to drop the theme/unyson and look for something that works on pantheon
regards

**Comment by carl-alberto** [comment]
The Unyson extensions seems to have some .gitignore files lying around and it prevents all of the codes being deployed in the platform: https://github.com/ThemeFuse/Unyson/issues/3615. Hopefully the author can remove it in their production version so it won't mess up with hosts that has built in version control like Pantheon.

**Comment by GheorgheP** [comment]
@iajay, I will take a look today, sorry for delay.

@carl-alberto, can you confirm that the problem is from `.gitignore` file?

**Comment by iajay** [comment]
I can confirm that I was able to make the test and live site work after I
deleted the gitignore files on dev site and the pushed to test
Actually I deleted the unyson plugin, committed to dev, deployed to test,
then installed the plugin , removed the gitignore files, committed to dev
and pushed to test

**Comment by carl-alberto** [comment]
@iajay Thanks for the confirmation of the workaround :)

@GheorgheP Yes, that .gitignore file that contains the `extensions/*` causes the additional Extensions to be deployed in TEST and LIVE environments in Pantheon. In best practices, adding git files to plugins and themes that is distributed to wp.org is not recommended: https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/#notes
