### ISSUE TITLE
Override view file in FW_Settings_Form::_form_render

### ISSUE THREAD

**Issue by guydumais** [ThemeFuse/Unyson#2569]
Hi, 

awesome framework by the way! I was looking for a page builder only but I finally integrated the whole UNYSON framework for my theme project because of all the features which are excellent time-savers. Congratulations, great work!

I'm currently trying to override the view file in the **FW_Settings_Form::_form_render** class which is located in **framework/helpers/class-fw-settings-form.php**. My goal is to use my own view file in my framework-customizations folder. 

The only solution I've found so far to achieve my goal is by replacing the code at line #236 :
`		fw_render_view( fw_get_framework_directory( '/views/backend-settings-form.php' ), array(
`

 with this code:
```
$view = fw_get_framework_directory( '/views/backend-settings-form.php' );
if ( file_exists(fw_get_template_customizations_directory('/views/backend-settings-form.php')) ) {
	$view = fw_get_template_customizations_directory( '/views/backend-settings-form.php' );
}

fw_render_view( $view, array(

```
Since I know that it's not a good practice to modify the framework code, what would you recommend me to achieve the same result?

Thanks in advance!

A new UNYSON fan!

**Comment by GheorgheP** [comment]
> Since I know that it's not a good practice to modify the framework code
This is a very bad practice ;)

Do you want to modify the settings form everywhere or only for Theme Settings?

**Comment by guydumais** [comment]
For now only for Theme Settings.

**Comment by GheorgheP** [comment]
There is an action `fw_settings_form_render` that is fired before the settings form rendering, you can print the desired HTML before settings form.
Also you can use the `html` option type to render some HTML element within options array.
