### ISSUE TITLE
Please change updates strategy

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#257]
I think that you need to change your updates strategy to avoid broken sites due to update bugs. 
Please let developers get a nightly builds or something before you push the version bumps. 
Or give heads up before you release the update to test the actual pack you are about to submit. 

The way it is now will give  developers and their customers headache.

**Comment by moldcraft** [comment]
For extensions we have this https://github.com/ThemeFuse/Unyson-Extensions-Approval
