### ISSUE TITLE
Updating WordPress from 4.3.10 to 4.7.4 breaks shortcodes

### ISSUE THREAD

**Issue by justinwhall** [ThemeFuse/Unyson#2570]
Inherited a very out of date site. The theme is scratch version 1.0.0. Unyson framework is included included in the parent theme.

version appears to be `$manifest['version'] = '1.4.20';` according to manifest.php.

Upon WordPress upgrade, I get a bunch of broken shortcodes that render as text. Example:

```
[arrow header title=”TU9WSU5HIEJVU0lORVNTRVM=” headline_link=”L21vdmluZy1idXNpbmVzc2Vz” subtitle=”TEVBUk4gTU9SRQ==” icon=”YnVpbGRpbmc=”][arrow header title=”U1RPUkFHRSBTT0xVVElPTlM=” headline_link=”L3N0b3JhZ2U=” subtitle=”TEVBUk4gTU9SRQ==” icon=”c2FmZQ==”][arrow header title=”TE9HSVNUSUNT” headline_link=”L21vdmluZy1zdG9yYWdlLWxvZ2lzdGljcw==” subtitle=”TEVBUk4gTU9SRQ==” icon=”dHJ1Y2s=”]
```

'/framework/bootstrap.php' *is* being included by the theme. 

Could I be pointed in the direction of how to upgrade Unyson from what appears to be a legacey version.

**Comment by GheorgheP** [comment]
First of all you need to know that we do not maintain compatibility of the first version of Unyson with the second one.

Also form what I remember, we did not have such shortcode `[arrow]` in first version too, but even it it was, we don't have it anymore and also the shortcode signature is not compatible.

You need to migrate shortcodes manually.

**Comment by justinwhall** [comment]
I was able to upgrade WordPress. The extensions added by the previous developer had some strange casing and as it turns out the shortcode they were using was [arrow header]. Notice the space.

I'd still like to get them upgraded to 2.6.16. Other than migrating custom shortcodes, will the default shortcodes still work or are we stuck with 1.4.20.

Thanks for you time.

**Comment by GheorgheP** [comment]
As i mentioned, the only way to migrate the shortcodes is to do it manually, as they are not compatible with version 2.

**Comment by danyj** [comment]
@justinwhall  is not that hard to merge ,  

post link to git with shortcode folder we might be able to give you instructions

**Comment by justinwhall** [comment]
Thanks @danyj [repo](https://gitlab.com/windsor-digital/johnson-storage)

My major pain point here is upgrading and assuring framework-custimizations > theme > shortcodes still work. I see no mention of the 'theme' directory in any of the docs.

**Comment by danyj** [comment]
sorry I have no gitlab acc, post on hub or somewhere public please

**Comment by justinwhall** [comment]
Apologies. Set to public.

**Comment by danyj** [comment]
they all looks ok I would rename  Instant Quote 

 to instant-quote , or instantquote no space 

other than that copy  **contents** of   

`theme/shortcodes `folder 

move it to 

`framework-custimizations\extensions\shortcodes\shortcodes`

**Comment by justinwhall** [comment]
Just to be clear. You are saying:

1. replacing `framework` with the latest stable version
2. move `theme/shortcodes` -> `framework-custimizations\extensions\shortcodes\shortcodes`

Already renamed the "instant quote". Not sure what that was all about.

**Comment by danyj** [comment]
DO LOCAL TEST

1.  Install framwork as a plugin 
2.  Remove theme bootstrap , 
3. move `theme/shortcodes `-> `framework-custimizations\extensions\shortcodes\shortcodes
`

**Comment by danyj** [comment]
> Already renamed the "instant quote

there are few more  with spaces in folder names

**Comment by danyj** [comment]
all these 
https://gitlab.com/windsor-digital/johnson-storage/tree/master/wp-content/themes/scratch-parent/framework-customizations/theme/shortcodes

should be here 

https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-parent/framework-customizations/extensions/shortcodes/shortcodes

**Comment by danyj** [comment]
all these 
https://gitlab.com/windsor-digital/johnson-storage/tree/master/wp-content/themes/scratch-parent/framework-customizations/theme/shortcodes

should be here 

https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-parent/framework-customizations/extensions/shortcodes/shortcodes

**Comment by justinwhall** [comment]
Ah. Thank you. Although now I'm getting "The shortcode text_block not found." Tried renaming the `text-block` directory to `text_block` with no success.

**Comment by danyj** [comment]
it should be text-block 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/master/shortcodes

but looks like your page was saved when it was text_block   so you need to redo page and save the new text-block

**Comment by justinwhall** [comment]
a serach-replace solves that. Unyson is now picking up default shortcodes but not shortcodes located here: https://gitlab.com/windsor-digital/johnson-storage/tree/master/wp-content/themes/scratch-parent/framework-customizations/extensions/shortcodes/shortcodes

**Comment by danyj** [comment]
and all plugin extensions activated? bootstrap removed from theme?

**Comment by justinwhall** [comment]
Yes. At this point, I'd be interested in bringing in someone experienced working with Unyson. Email me @ justinwhall @ me -dot- com if interested or if you could put me in touch with someone who might be. Thanks.
