### ISSUE TITLE
Cannot Download extensions 

### ISSUE THREAD

**Issue by tjrw99** [ThemeFuse/Unyson#2571]
Hi

I am using filezilla as my ftp and so cannot use the wordpress dashboard. This means i cannot install and use the extensions in your plugin. is there a way around this? 

Thanks

**Comment by GheorgheP** [comment]
Yes, the simplest way is to make an install on your local machine and install it, then upload the extensions folder.

Or you can use this zip with all extensions.
https://www.dropbox.com/s/upqdbmgty4sz0ga/extensions.zip?dl=0

**Comment by tjrw99** [comment]
And where would i upload that extensions folder? as you know once the plugin is installed you have to download each individual extension using the built in wordpress FTP page however my host only allows SFTP. 

So where would i install these extensions so they wont need downloading?

Thanks

**Comment by GheorgheP** [comment]
You need to download the provided zip file and unzip it, then upload all extensions in `/wp-content/plugins/unyson/framework/extensions`

**Comment by tjrw99** [comment]
The extensions are installed what im trying to get across to you is that once installed i cannot activate them on the wordpress dashboard as i can only use filezilla because my host uses SFTP

**Comment by GheorgheP** [comment]
Having SFTP access there are a lot of ways to activate them.

But the best way is this, add this code in `functions.php` from theme, and after activation, remove it:

```php
function _action_activate_unyson_extensions() {

	/**
	 * 
	 * $extensions = array(
	 *  'page-builder' => array()
	 * );
	 * 
	 * $extensions = fw()->extensions->manager->get_available_extensions();
	 */
	
	$extensions = fw()->extensions->manager->get_supported_extensions();
	fw()->extensions->manager->activate_extensions( $extensions );
}

add_action( 'init', '_action_activate_unyson_extensions' );
```

As you can see in code comment, `$extensions` variable can either be a list of extensions, or all available extensions, or the theme supported extensions (that I set by default).

PS: To be honest you could even install them like this, without my archive file.
