### ISSUE TITLE
Page Builder - Gallery Extension Shortcode Modification

### ISSUE THREAD

**Issue by RamiWH** [ThemeFuse/Unyson#2572]
Hello All,

I was wondering if someone can point me in the right direction.

I am trying to figure out how to edit the Gallery shortcode so that I am able to make the images clickable/linkable (Like in the Image Box Extension), while retaining all other options such as; layout, behaviour and lightbox.

I am using the Construction Wordpress theme by CIAOThemes.

I have a basic understanding on how the shortcodes work and their directories.

Thanks for the help!

**Comment by danyj** [comment]
Unyson does not have gallery shortcode by default , contact your theme provider.

**Comment by GheorgheP** [comment]
The issue is not related to Unyson, but to theme provider.
In case you are a developer, you can check out **Unyson Shortcodes** extension [documentation](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content) about how to create/edit shortcodes.
