### ISSUE TITLE
fw:ext:megamenu:icon-option filter does not work anymore

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2573]
this filter was added so that we can replace default icon option with ours 
https://github.com/ThemeFuse/Unyson/issues/880

```
// use thz-icon option
function _thz_filter_menu_item_icon($icon) {
	
	$icon['type'] = 'thz-icon';
	$icon['label']  = esc_html__('Select icon', 'creatus');
	
	return $icon;
}
	
add_filter( 'fw:ext:megamenu:icon-option', '_thz_filter_menu_item_icon');
```

it worked for a while but now the popup opens and closes abruptly, and in modal content I cant see the icon option

http://take.ms/oAU24

no js errors

**Comment by danyj** [comment]
The issue is with close frame triggered here 
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/static/js/admin.js#L97-L123


for some reason when modal is opened the change event is triggered , 

in theme settings my icons option does not trigger any change on load or init,  but in that modal seems like it does 

it is connected to fontIconPicker  script wich triggers the change , but again , this happenes in this particualr modal only, 

https://github.com/micc83/fontIconPicker/blob/3d3a621008e51fc5a56ca5246daeb713398e826c/jquery.fonticonpicker.js#L697

I tested my icon option in   builder and theme settings and no change is triggered on option load 


this is basic option setup 

```
(function ($, fwEvents) {

	fwEvents.on('fw:options:init', function (data) {
		data.$elements.find('.fw-option-type-thz-icon:not(.thz-option-initialized)').each(function(index, element) {

			var $element 				= $(element);
			var $iconsholder 			= $element.find('.thz-icon-input');
			
			var $thz_icon_picker = $iconsholder.fontIconPicker();

		}).addClass('thz-option-initialized');
	});

})(jQuery, fwEvents);
```

**Comment by GheorgheP** [comment]
What was the problem?

**Comment by danyj** [comment]
you fire modal close on change https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/static/js/admin.js#L96-L123

I am using fonticonpicker for mine which fires the change in order to show currently selected icon

https://github.com/micc83/fontIconPicker/blob/master/jquery.fonticonpicker.js#L697

I changed their script not to fire change here https://github.com/micc83/fontIconPicker/blob/master/jquery.fonticonpicker.js#L660

since the input already has the icon,  just show it , dont trigger change

**Comment by pnpetroff** [comment]
Is this working in the latest release?
