### ISSUE TITLE
Widget title not show in Backend.

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#2574]
Please have a look at [

This picture](http://nimb.ws/r5q8Bj)

In short words, the title of the widgets (inc/widgets) will never show in Backend.

**Comment by GheorgheP** [comment]
You should add the id for the text input that contains the wirdget title in `form()` method `id="<?php echo $this->get_field_id( 'title' ); ?>"`

```php
<input
        type="text"
        name="<?php echo $this->get_field_name( 'title' ); ?>"
        id="<?php echo $this->get_field_id( 'title' ); ?>"
        class="widefat"
        id="<?php $this->get_field_id( 'title' ); ?>"
        value="<?php echo esc_attr( $title ); ?>"
/>
```
