### ISSUE TITLE
Mega menu isn't working as expected

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#2575]
Hi guys,

I'm using the latest Unyson plugin and am currently testing the mega menu with the default theme. I've follwed the video demo but the mega menu doesn't appear to work on the frontend, although the  settings seem correct.

https://ibb.co/hQMuBQ
https://ibb.co/gVUEBQ

**Comment by GheorgheP** [comment]
The fact is that you need to create the necessary styles for the mega menu.
I would recommend to start developing using the scratch theme: https://github.com/ThemeFuse/Scratch-Theme
