### ISSUE TITLE
Unique option type not updating 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2576]
Not sure which of the function is not looking deeper , `fw_collect_options`

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/simple.php#L1130

or something else but if you have the unique option like a set below , 

only the  unique outside multi-picker gets refreshed when you **clone**  https://github.com/ThemeFuse/Unyson/pull/2557 the popup

here is my output of cloned popup , 
![fc18f021a3d94b6e9872bb6e4840bb7a](https://cloud.githubusercontent.com/assets/2340172/25780897/6fd28d20-3330-11e7-8cb2-4dc651bd4e58.png)

first unique ( green arrow )  got refreshed , 
the ones in multi ( red arrow )  did not 

**test option**

```
	'testunique' => array(
		'type' => 'addable-popup',
		'label' => __('Add', 'fw'),
		'popup-title' => esc_html__('Add/Edit', 'fw'),
		'template' => 'New',
		'size' => 'medium',
		'popup-options' => array(
		
			'idout' => array(
				'type' => 'unique',
				'length' => 8
			),								
			'multi' =>array(
				'type' => 'multi-picker',
				'label' => false,
				'desc' => false,
				'picker' => array(
					'picked' => array(
						'label'   => __( 'Pick something', 'fw' ),
						'type'  => 'short-select',
						'value' => 'option1',
						'choices' => array(
							'option1'      => __('Option 1', 'fw'),
							'option2'  => __( 'Option 2', 'fw' ),
						)
					)
				),
				'choices' => array(
					'option1' => array(
						'idone' => array(
							'type' => 'unique',
							'length' => 8
						),	
						'title'    => array(
							'type'  => 'text',
							'label' => __( 'Title 1', 'fw' ),
						)				
					),
					
					'option2' => array(
						'idtwo' => array(
							'type' => 'unique',
							'length' => 8
						),	
						'title'    => array(
							'type'  => 'text',
							'label' => __( 'Title 2', 'fw' ),
						)				
					)
				)									
			
			),
		)
```

### Side note :  Unique is not listed in built in option types http://manual.unyson.io/en/latest/options/built-in/introduction.html#content

**Comment by GheorgheP** [comment]
The unique option type doesn't work on addable, I will review this issue.
If you look at the `unique` option type code, it is generated from php during rendering.
So the first unique is generated because it makes an ajax request in order to render, of the other it uses the cache.

**Comment by danyj** [comment]
hm , to me looks like this   method runs 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/simple.php#L1123

specifically for addable popup https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/simple.php#L1027

**Comment by danyj** [comment]
@ViorelEremia  waiting for fix please respond
