### ISSUE TITLE
Unyson issue

### ISSUE THREAD

**Issue by blucloudsrl** [ThemeFuse/Unyson#2577]
Hello,
we have a serious problem with the Unyson builder: in some pages it is completely broken, and edit a post or page is actually impossible; in these cases we see only the code on the page, and click on unyson builder makes that all the code goes inside a text element.
In other pages the unyson builder is showed, but it is hard to edit or move elements, and for each title element we see: function (n) {return o.call(this,n,m)}.

Currently it is installed 
 - wordpress 4.7.4
 - Unyson 2.6.16
 - theme: Apital by nrgthemes

Thank you

**Comment by danyj** [comment]
you need to post in Apital by nrgthemes  support,   if you disable their theme and check builder you will see that it behaves  ok ,   their theme must have custom shortcodes or option types that do something they should not.

**Comment by Ataurr** [comment]
before I faced the same issue
Make sure your all unyson extension are up to date.

**Comment by GheorgheP** [comment]
You have to update extensions to the latest version. In your case, specifically the Builder and Page Builder.
