### ISSUE TITLE
WP Shortcode inline

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2580]
We'd like to enable users to enhance their texts with annotations such as images, video's and links. These additions would show up at the side of the text, as a side note. Of course the notes are bound to a certain text fragment.

I would like to use a WP Shortcode in the WP-editor to achieve this, so I've created one with some options. This all works pretty nice. 

However, my problem is that the Unyson WP Shortcodes get pushed down to the end of a paragraph and therefore it can't be bound to a position after a certain word or text fragment. Is there a possibility to disable this behaviour for a certain shortcode so a shortcode can really be placed inline?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1815847/25888788/c87a64e6-3567-11e7-8800-8cec50f0dd57.gif)

**Comment by danyj** [comment]
first step is to remove width , 
![screenshot_18](https://cloud.githubusercontent.com/assets/2340172/25889264/77661698-3569-11e7-806a-784a790c6a39.jpg)


than   we need to tell editor not to wrap the shortcode i p because that is what droops it down 


@andreiglingeanu , I am all up for this ,  since I also have inline shortocde that should be place inline within the editor, 


we could add a hook in shortcode config 

	$cfg['wp_shortcode'] = array(
		'display' => 'inline' // block
	);

**Comment by warudin** [comment]
Thanks for your reply!

I know how to customize the width of a shortcode in the editor (I did it with an admin stylesheet) but I'm not sure how to disable the automatic paragraphs.

**Comment by danyj** [comment]
@warudin I was not implying that you should do this , @andreiglingeanu  could take a look and give us this,

**Comment by andreiglingeanu** [comment]
There's no reason for having inline shortcodes. They'll be rendered as block elements in frontend.

I can allow putting those elements in paragraphs but I see no reason to because almost any shortcode will look awkward while being in a `p` tag in frontend.

**Comment by danyj** [comment]
> They'll be rendered as block elements in frontend.

who says? 

is our layout , we decide the output and can override the corrections

**Comment by danyj** [comment]
why would a span ( icon ) or button ( inline ) be awkward in p?

**Comment by andreiglingeanu** [comment]
That is probably right.

The fact is that you'll have to define a particular set of shortcodes to be used as inline. And you'll have to provide that particular array of shortcodes for editors. 

A better option is to be able to mark a single shortcode as `inline` in `shorcodes`:

```php
array(
  'type' => 'wp-editor',
  'shortcodes' => array('shortcode_1', 'shortcode_2'),
  'inline_shortcodes' => array('inline_shortcode_1', 'inline_shortcode_2')
)
```

And by default you'll have no inline shortcodes. Yeah, good idea.

cc. @GheorgheP

**Comment by danyj** [comment]
@andreiglingeanu   I would do this as global  wp-shortcodes filter instead each shortcode

**Comment by danyj** [comment]
because all we need to do is tell wp-shortodes what shortocde is inline

**Comment by andreiglingeanu** [comment]
Why not give users possibility to use both block and inline shortcodes in a same editor?

**Comment by danyj** [comment]
I did not mean that 

by default now editor assumes that all  shortcodes are block , 

if we tell editor that the shortcode is inline ,  like icon shortcode ,  than we dont say it every time , 

icon shortcode is always inline on my end , so why go in each editor where I allowed shortcodes and add additional array to say that icon shortcode is inline?

**Comment by danyj** [comment]
we are thinking about 2 different setups 

you want to tell each editor how to display each shortcode

I want to advise editor that specific shortcode is inline element

**Comment by GheorgheP** [comment]
I don't think we'll add this feature.
The `wp-shortcodes` means blocks, and in general, the wordpress shortcodes have a meaning of block, not an inline content.

**Comment by andreiglingeanu** [comment]
Yeah, even all shortcodes in core WordPress are block-wise:

* playlist
* gallery
* video
* embed/embedURL

**Comment by warudin** [comment]
I get your point of view, but the WP Editor also features some inline interactivity with the 'insert/edit link' functionality. I believe we currently can't replicate such behaviour with Unyson, right?

For what I want to achieve It might not a big problem if inline shortcodes won't happen in default Unyson installations, now I've got the solution @danyj proposed, combined with [this](https://github.com/ThemeFuse/Unyson/issues/2581) from @andreiglingeanu.

**Comment by andreiglingeanu** [comment]
@warudin We can get draggable shortcodes working properly (by switching the implementation a bit) but I am afraid the solution @danyj proposed for inline shortcodes might not work anymore.

Do you desperately need inline shortcodes?

**Comment by warudin** [comment]
Maybe there are other solutions but the use case is like in this image:
![schermafbeelding 2017-06-02 om 11 04 02](https://cloud.githubusercontent.com/assets/1815847/26719022/386f4f96-4783-11e7-953e-d182b6bd941b.png)

We need to give users the option to enhance their texts with images, links, notes and such. Users should be able to add these in an easy way, so without code. These enhancements are relating to a small portion or just a few words of the complete article and therefore it'd be awesome if they could be inline.

**Comment by andreiglingeanu** [comment]
I'd suggest you to look into how to customize the link popup from WordPress core.

- [Check that](https://cl.ly/kjhi)
- [One more screen](https://cl.ly/kjcX)
