### ISSUE TITLE
Avoid using sessions

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson#2582]
WordPress core doesn't use sessions, and some hosting providers do not enable this too, or enable with some restrictions. There is even a plugin for sessions: https://wordpress.org/plugins/wp-native-php-sessions/

We should remove sessions usage from unyson core.

**Comment by andreiglingeanu** [comment]
What is the whole purpose of `FW_Session`? Just to be able to set flash messages from contact forms?
