### ISSUE TITLE
Filter 'fw:ext:megamenu:icon-option' Doesn't Work

### ISSUE THREAD

**Issue by pnpetroff** [ThemeFuse/Unyson#2583]
It seems the following code doesn't work.

```php
function _filter_mega_menu_icon_customizations($option) {
    $option['label'] = __('Hello', 'fw');

    return $option;
}
add_filter( 'fw:ext:megamenu:icon-option', '_filter_mega_menu_icon_customizations' );
```

I want to add my own custom icon font and an additional option field to the Mega Menu extension but it seems I am not able to do so.

**Comment by GheorgheP** [comment]
Your code works for sure.
Please make sure the file where you added the filter is loaded before the filter fires.

Try to add the code in `functions.php` of the theme, just to test.
Also keep in mind, the filter affects the **Select Icon** option label text, not the **Edit Icon** button.

![](https://static.md/87c69f36881ae92c06f4778500445334.png)

**Comment by pnpetroff** [comment]
Oh, I was thinking that it will change the Add Icon field. Yes, it works.

I was thinking if I could add option fields in the menu itself. For example, a background image option field here:
![image](https://cloud.githubusercontent.com/assets/1108563/25970682/29514164-36a2-11e7-89b5-8e8f6ca4d847.png)

**Comment by GheorgheP** [comment]
You can sue the `wp_nav_menu_item_custom_fields` action, but you need to keep in mind that you control the rendering of those options and saving.

```php
function _action_add_options_in_nav_menu_item( $item_id, $item, $depth, $args ) {
	//Render the options you need
}

add_action( 'wp_nav_menu_item_custom_fields', '_action_add_options_in_nav_menu_item', 10, 30 );
```

Please refer this issue ThemeFuse/Unyson-MegaMenu-Extension/issues/5

**Comment by pnpetroff** [comment]
I managed to get it working like this:

```php
add_action( 'wp_nav_menu_item_custom_fields', '_action_my_add_options_in_nav_menu_item', 10, 30 );

function _action_my_add_options_in_nav_menu_item( $item_id, $item, $depth, $args ) {
?>
	<!-- more fields here -->
	<input type="hidden" name="<?php echo _fw_ext_mega_menu_admin_input_name($item_id, 'image') ?>?>" value="<?php echo esc_attr(fw_ext_mega_menu_get_meta($item, 'image')) ?>">
<?php
}
```
```php
add_action('wp_update_nav_menu_item', '_action_my_wp_update_nav_megamenu_item', 11, 3);

function _action_my_wp_update_nav_megamenu_item($menu_id, $menu_item_db_id, $args)
{
	if (!isset($_POST['menu']) || !isset($_POST['action'])) {
		return; // this is not a form submit
	}

	$meta = _fw_ext_mega_menu_admin_input_POST_values($menu_item_db_id);
	$meta = array(
		'image' => isset($meta['image']) ? (string)$meta['image'] : '',
	);

	fw_ext_mega_menu_update_meta($menu_item_db_id, $meta);

}
```

But I'm not sure if this is the correct way...
