### ISSUE TITLE
Enqueue Icon v2 ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#2584]
Hello @moldcraft, @llemurya 

I am currently using unyson icon version 2 library.
I have successfully enqueued the icons css using this function.
fw()->backend->option_type('icon-v2')->packs_loader->enqueue_frontend_css();

But if i have used only linearicons then it should only linearicons css file.
Kindly guide me which hook should i wrote or modify to accomplish this task.

Regards.

**Comment by andreiglingeanu** [comment]
Hey @wpthemes786!

There are instructions for the option type and they are located [here](http://manual.unyson.io/en/latest/options/built-in/icon-v2.html).

In your case you have to use `fw:option_type:icon-v2:filter_packs` filter.

```php
function _custom_packs_list($current_packs) {
    /**
     * $current_packs is an array of pack names.
     * You should return which one you would like to show in the picker.
     */
    return array('font-awesome', 'unycon');
}

add_filter('fw:option_type:icon-v2:filter_packs', '_custom_packs_list');
```
