### ISSUE TITLE
Elements error:not found

### ISSUE THREAD

**Issue by flutterworksforyou** [ThemeFuse/Unyson#2588]
This error happens with every element I open but was working fine the other day.  Can not edit anything on page yet everything is still there when you preview page.

![screencapture-spartanindustrialservices-wp-admin-post-php-1494539453018](https://cloud.githubusercontent.com/assets/28636169/25974116/34ef76da-3675-11e7-9c26-e2d5901739c1.jpg)

**Comment by GheorgheP** [comment]
Please open the Developer tools and looks at the response you get from the ajax request when you open the popup. Usually the problem comes from the hosting security restrictions or limits of the request body size. In this case you need to contact the hosting provider and ask why the request is blocked.

**Comment by flutterworksforyou** [comment]
This is the error i get in developer tools

JQMIGRATE: Migrate is installed, version 1.4.1
/wp-admin/admin-ajax.php Failed to load resource: the server responded with a status of 404 (Not Found)

I have several sites on these same servers and have never had this problem with them

**Comment by Ragnarosh91** [comment]
I've had the same issue and I've just solved it asking the provider to check the security rules. Some elements of the template triggered the restriction and they had to whitelist them.

**Comment by GheorgheP** [comment]
Usually all our clients that had this problem was the same as @Ragnarosh91  mentioned.
Please check out it the **SUHOSIN** is not installed as it may create this.
