### ISSUE TITLE
Memory when import content demo

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#259]
Hi,

Do we have any solution to improve import content demo ? I have a db file about 5mb, and it always occur lack of memory and IO when importing. I purchase a package with 1024MB memory and 1MB IO.

**Comment by sergiubagrin** [comment]
Can you share it with me dropbox? Dropbox account: sergey.roxigo@gmail.com

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
