### ISSUE TITLE
WP Image Editor preview conflict

### ISSUE THREAD

**Issue by SynapsisIT** [ThemeFuse/Unyson#2590]
I just had a client that had images upside down, so I went to Media>Library to rotate the clients image. However I did notice that in the edit section of the images the image preview would not work. Disabling all the plugins seems to fixed it, while activating the plugins one by one the error persisted again once i activated Unyson.

Has anyone had a similar issue? or is it just me?

**Comment by GheorgheP** [comment]
You need to rotate it, wordpress creates a new image, but not editing the current one.
In case your code uses the `upload` option type, in code is used the `url` key that saves the original url to the image. What do you need to do it to use the `attachment_id` key, to get the attachment id and then with it to use the `wp_get_attachment_image_url()` function to get the image url, in this case you'll get the rotated image url.

```php
$id  = fw_get_db_post_option( 610, 'werter/attachment_id' );
$src = wp_get_attachment_image_url( $id, 'full' );
```

**Comment by SynapsisIT** [comment]
The problem is in the Wordpress Edit Image panel and not front end. In the front-end however I double checked and made sure I called the images with the wp_get_attachment_image_url function on those 2 instances that it was present, but it doesn't seem to fix the problem in the backend. Or am I perhaps looking into this the wrong way?

**Comment by GheorgheP** [comment]
I just tested the this and it works properly. But if in your case doesn't work something, it may be from wordpress, not from Unyson.

**Comment by SynapsisIT** [comment]
That is weird, because I am testing it both on local installation and on live website, the result is always the same until I disable unyson.

http://prntscr.com/f7077f

But you might be right. This seems to be theme related, switchin to twentysixteen theme and leaving unyson installed the image editor seems to be working fine. I just need to track down to what in my theme is getting in conflict.
