### ISSUE TITLE
Customizer not working with Sage Starter Theme

### ISSUE THREAD

**Issue by 9585999** [ThemeFuse/Unyson#2591]
Hi, I'm using Unyson framework with [Sage 9.0.0-beta.3](https://github.com/roots/sage). 
I ran into a problem that does not work customizer options if I add them through `{framework-customizations-dir}/theme/options/customizer.php`

**Here is a sample code that I add**
![img 2017-05-12 12 26 12](https://cloud.githubusercontent.com/assets/16165904/25992674/0029617c-3710-11e7-9a05-dfa2d3de1fb0.PNG)
**Here is the result... `http://example.dev/wp-admin/customize.php`**
![img 2017-05-12 12 26 15](https://cloud.githubusercontent.com/assets/16165904/25992730/2a636b36-3710-11e7-8aac-0d358e9b708a.PNG)
**With the same code**
![img 2017-05-12 12 26 25](https://cloud.githubusercontent.com/assets/16165904/25992856/91dbc862-3710-11e7-9b5c-36f06e3b67f2.PNG)
**Here is the result... `http://example.dev/wp-admin/customize.php`**
![http---example dev-wp-login php redirect_to http---example dev-wp-admin-customize php return 2fwp-admin 2fadmin php 3fpage 3dfw-extensions reauth 1 2017-05-12 12-27-31](https://cloud.githubusercontent.com/assets/16165904/25992908/c384120c-3710-11e7-82e6-66d2e2bbb1e2.png)
I understand that maybe this is due to the peculiarities of [roots/sage](https://github.com/roots/sage) error, but still decided to write first to you.

Is there a solution to this problem?

**Comment by GheorgheP** [comment]
Did you enable the debugger? There are any error in the log file?

**Comment by 9585999** [comment]
if enable `define('WP_DEBUG', true);`

![img 2017-05-12 14 09 08](https://cloud.githubusercontent.com/assets/16165904/25995769/9cee269e-371c-11e7-9912-13c266f35aa1.PNG)

**Comment by 9585999** [comment]
Strangely, I looked at the file that is listed in the error message, on the 22 line swears php-linter atom...
![img 2017-05-12 14 35 24](https://cloud.githubusercontent.com/assets/16165904/25996576/a6734984-3720-11e7-831e-de19eb9407c7.PNG)
For the sake of interest, I commented on it
![img 2017-05-12 14 35 42](https://cloud.githubusercontent.com/assets/16165904/25996594/c3d92444-3720-11e7-883f-2bbfe94e469d.PNG)
**Here is the result**
![img 2017-05-12 14 41 11](https://cloud.githubusercontent.com/assets/16165904/25996660/169c1420-3721-11e7-8bf0-33e10e931a66.PNG)
![img 2017-05-12 14 41 13](https://cloud.githubusercontent.com/assets/16165904/25996663/1ba8c058-3721-11e7-9d18-e6932fa6ccb3.PNG)
**Customizer working**
And even I doubt the correctness of this approach ...

**Comment by andreiglingeanu** [comment]
@ivandotv is the hero of that incident :)

https://github.com/ThemeFuse/Unyson/commit/869fa4449fd90a5d3cfc7fbe779de6002816abd8

**Comment by GheorgheP** [comment]
@9585999 You didn't even think about it, but you are the day

**Comment by 9585999** [comment]
I did not notice the missing `)`
**Thanks for the help!**

**Comment by ivandotv** [comment]
@andreiglingeanu  @GheorgheP 
My apologies.
That's not the first time this happens to me.
Forking the project, editing directly in the browser, and lack of coffee are the culprits.

**Comment by GheorgheP** [comment]
No problems @ivandotv, it was my mistake from my side as did not review the code properly and test it.

Like @andreiglingeanu mentioned yesterday in a tack with me: _Another proof why we should do unit tests_

**Comment by ivandotv** [comment]
@GheorgheP @andreiglingeanu 
I see that you have some kind of continuous integration going on, what does it do then?

**Comment by andreiglingeanu** [comment]
@ivandotv We have a couple of tests but apparently they don't have enough coverage to spot syntax errors everywhere. This situation should be definitely improved.
