### ISSUE TITLE
title_template doesn't work for WP Shortcodes

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2594]
I've got this config:

```
$cfg['page_builder'] = array(
	'title'       => __( 'A title', 'ppp' ),
	'tab'         => __( 'PPP Elements', 'ppp' ),
	'icon'		=> 'fa fa-star',
	'popup_size'	=> 'large',
	'title_template' => '{{- title}} lorem ipsum',
);
```

The title_template does work in the Page Builder, but when using the shortcode as a WP Shortcode the main title is not replaced by the title_template.

**Comment by danyj** [comment]
I noticed this but did not report due to extended titles I have in builder and I think they might look bad inside the editor

**Comment by ViorelEremia** [comment]
I think we will not do this because this editor will not be in the future; when Gutenberg is going to be in the core of wordpress then we will think.
