### ISSUE TITLE
Website suddenly lost fullscreen

### ISSUE THREAD

**Issue by JeroenSmeets1995** [ThemeFuse/Unyson#2595]
Hi all,

Yesterday, I updated my website and it all went well. Today, I opened my website, and my page lost its fullscreen view. On the sides, there is +/- 30% empty space on each side, and on top +/- 10%. If I zoom in, the space shrinks and eventually turns into mobile view. If I scroll down, the upper space gets pushed away.

I tried the following:
- Revisions from yesterday, from a week ago, a month and two months;
- Check several settings in the 'Theme settings' menu.

None of this worked. Furthermore, yesterday I tried to insert a metatag to improve SEO by typing a line in code, not in the visual editor. Each time I tried to save my website, it disappeared and I tried again but it didn't stay there.

Is there anyone who faced the same problem or anyone who knows how to fix it?
Thank you so much in advance. If you like to check the exact error: www.jeroensmeetsmedia.nl this is the website.

Regards,
Jeroen

**Comment by GheorgheP** [comment]
Hmmm, it looks fine:
![](https://static.md/da475303db76194b141275ab36a48029.png)

I don't think that the problem may come from Unyson as it is not responsible for site design.
Sure there may be a small probability of fact that PageBuilder may be down. Did you check out if the pages in backend look fine?
