### ISSUE TITLE
 pages were saved multiple times without the page builder enabled so it went to flat shortcodes

### ISSUE THREAD

**Issue by TomofHack** [ThemeFuse/Unyson#2596]
Our website, http://www.stuartsaudio.com/,  displays the Unyson  site properly but we cannot edit it. 
According to the developer, this is caused by the fact that pages were saved multiple times without the page builder enabled so it went from page builder element to flat shortcodes. It seems that Unyson can't make it back. 
Is there anything that can be done to re-enable Unyson? We inherited the site  and don't want to have to rebuild a great looking but unworkable site.

**Comment by GheorgheP** [comment]
But the Page Builder extension is active?

**Comment by TomofHack** [comment]
Yes, page builder extension is currently active. Pages display fine. But making any change changes the writing of the code as visible in revision view only from the good'
[text_block text="&lt;p style=&quot;text-align: center;&quot;&gt;Cables are an ...
to the bad
[text_block text="&lt;p style="text-align: center;"&gt;Cables are an...

There may be other changes that wordpress is making.

**Comment by GheorgheP** [comment]
I do not see any difference between the good and bad examples.
Also to understand the page looks wired or the revision view?

**Comment by TomofHack** [comment]
Sorry...didn't catch the change as the code was html and got rewritten by this editor. In the good version  there is the html for a double quote, &quot ; (in text as well as visual view). This time i am deliberately leaving a space between the t and ; so it won't get rewritten. In the bad, rewritten version, wordpress is rewriting the html for double quotes into double quotes that the is not  being recognized.

**Comment by GheorgheP** [comment]
The fact is that you cannot return back the broken page. And it even doesn't have to do anything with the fact that page was saved multiple times with page builder. The fact is that somehow the builder content is removed from the post/page meta and it doesn't see it, or was submitted a corrupt format.

I'm aware of this issue, but at the moment we do not know how to reproduce it. It happens occasionally and there is not a common cause.
