### ISSUE TITLE
Using video backgrounds in builder sections

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#260]
Is there anything special about using video background for sections? 
I added the link to mp4 file , seems like output is ok 
http://screencast.com/t/hsP9gdaPn6B

but there is no video. 
Am I missing something?

**Comment by moldcraft** [comment]
At the moment I have info that sections were tested with youtube and vimeo videos and to use uploaded videos you/we will have to make some changes in js.

We will come back with more details later.

*(I am busy with megamenu now)*

**Comment by llemurya** [comment]
Please see in shortcodes - the section shortcode javascript files and change it in order to work with this [plugin](http://formstone.it/components/Wallpaper/demo/index.html) , he works with .mp4 format . Hope this help you

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/static/js/scripts.js#L2

**Comment by danyj** [comment]
Vimeo does not work , tested these videos
https://vimeo.com/50700106
https://vimeo.com/8733915

Youtube works with this one 
https://www.youtube.com/watch?v=tKONNhMvPtI

but is not showing it as background , it kills all rows inside the section 

no video 
http://screencast.com/t/hsP9gdaPn6B

with youtube video 
http://screencast.com/t/8x55h2FdYGsC

**Comment by llemurya** [comment]
Yes we know that this plugin don't work with vimeo , please see this [issue](https://github.com/Formstone/Wallpaper/issues/13)

**Comment by llemurya** [comment]
in future release we will fix this bug , in order to work with local files. If you want to work with vimeo please suggest another plugin that make this work and contribute. Thanks a lot!

**Comment by danyj** [comment]
@llemurya look at moldcraft post , 
https://github.com/ThemeFuse/Unyson/issues/260#issuecomment-74870456
I was testing what he said and advised of the issue. 
and more pressing bug is that it kills the rows inside the section

**Comment by llemurya** [comment]
@danyj i said that we will fix that.Don't worry.

**Comment by danyj** [comment]
Fix for the missing rows 

add 

    .fw-main-row.background-video .fw-container-fluid 

to this one 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/static/css/styles.css#L1


you just forgot that the container can be switched to fluid

**Comment by llemurya** [comment]
@danyj please download [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/d1146d0ffd8652c4f67c3941a918fffae397779d/shortcodes/section/views/view.php) file , replace it and see if it work normally for .mp4 format. In next realease it will be in production. Thanks a lot for your help!

**Comment by danyj** [comment]
sweet check for filetypes , excellent , works well
:100:

**Comment by danyj** [comment]
small bug , this 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/d1146d0ffd8652c4f67c3941a918fffae397779d/shortcodes/section/views/view.php#L19

should be ogv  not ogg

**Comment by llemurya** [comment]
@danyj Yes you are right. I will fix it.

**Comment by llemurya** [comment]
@danyj  thanks for help, I fixed bug and tested with .ogv file format and it works. In previous version it fails because plugin wants object in [this](http://static.md/31f31f4971d028b38a118e23e4efb006#) format.

**Comment by danyj** [comment]
ok makes sense, 
please remove the extra space you have before the class attribute 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/27e646c459eedfdab4b25ffe6d8b952e96067575/shortcodes/section/views/view.php#L28
http://screencast.com/t/bBsByStX

**Comment by llemurya** [comment]
@danyj Yes this is my fault . I didn't pay attention after reformat code, that PhpStorm set this space. @moldcraft  already commited and fix this. Thanks a lot for feedback.
