### ISSUE TITLE
[bug] Not able to override contact form shortcode config

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2600]
I am changing icons and  can't override contact-form config within the theme 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/extensions/contact-forms/shortcodes/contact-form/config.php

try with 

`    'icon' => 'fa fa-play-circle-o'`

**Comment by GheorgheP** [comment]
The icon should be an image and it should be located in `/static/img/page_builder.png`

**Comment by danyj** [comment]
no , icon can be  class also 
http://manual.unyson.io/en/latest/extension/shortcodes/index.html#creating-a-new-shortcode


        /*
        // Icon examples
        // Note: By default is loaded {your-shortcode}/static/img/page_builder.png
        'icon' => 'http://.../image-16x16.png', // background color should be #8c8c8c
        'icon' => 'dashicons dashicons-admin-site',
        'icon' => 'unycon unycon-crown',
        'icon' => 'fa fa-btc',
        */


and works in all other shortcodes , 


besides  that , take the config , drop in override and change image or text inside the config and it wont take

**Comment by danyj** [comment]
@GheorgheP  can you please take a look at this , I need to do finish docs and all other shortcodes are using icon class and are ovewrittable  except this one

**Comment by danyj** [comment]
@GheorgheP can this get fixed please? I would do it if I knew where to look. But at the moment I need to finish the docs and this shortcode is only one that  I have to manually css in order to continue with docs.

**Comment by danyj** [comment]
Thnx but the fix you did  is for shortcode item in Content elements tab , 

The one for shortcode https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/extensions/contact-forms/shortcodes/contact-form/class-fw-shortcode-contact-form.php#L102

within page builder is still not working
![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/26348137/064c94c6-3fac-11e7-9218-5f3ba0d3ac73.jpg)

so now we have 2 different icons showing.


and there seems to be a commit  from 5 months ago that was not released. Last release was  12/2016

https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/ff86c48f1c4aa049c8b6f13fe654cbfbd081e2b2
