### ISSUE TITLE
Multi-select - post type reference

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2604]
I'm using multi-select like below:

```php
'highlights' => array(
	'type'          => 'multi-select',
	'label'         => __( 'Highlighs', 'fw' ),
	'population'    => 'posts',
	'source'        => array( 'artikelen', 'nieuws', 'wetenschapsartikelen' ),
	'prepopulation' => 10,
	'limit'         => 3,
), // highlights
```

When having multiple post types as source, sometimes it's not so easy to recognize a post type by the title. Is it possible to have the post type as a reference behind the title?

**Comment by noesteijver** [comment]
Thanks @GheorgheP for the addition!

I tried adding this to my multi-select option code:

`'show-type' => true`

But when looking at the option in the backend, I see no post type or taxonomy reference.

Could you please have a look at this? If I can do anything to help, just let me know!

**Comment by GheorgheP** [comment]
Did you try with development version from Github or form WordPress.org?
We did not create a plugin version release right now.

**Comment by noesteijver** [comment]
Aha. No, I've been using the WordPress.org version. I'll keep an eye out on the next release, thanks!
