### ISSUE TITLE
Url blocked by robots.txt

### ISSUE THREAD

**Issue by bgw123** [ThemeFuse/Unyson#2605]
I keep getting this sitemap problem. I turned off all plugin it works fine, when i turn on your plugin I get this warning. not sure what to do, because I like your plugin, but i need my sitemap. please help. Website is simplifycomplexity.org

thanks Brian

**Comment by GheorgheP** [comment]
From the message the sitemap is blocked by the `robots.txt` file. Unyson doesn't generate this file.
But if you look in [http://simplifycomplexity.org/robots.txt](http://simplifycomplexity.org/robots.txt), you'll that the sitemap is specified with `https` protocol, but your site doesn't support `https`.
