### ISSUE TITLE
'multi-select' doesn't auto-populate

### ISSUE THREAD

**Issue by pnpetroff** [ThemeFuse/Unyson#2608]
I have a `multi-select` option field that I dynamically populate with all posts with `'choices' => fw_theme_get_post_names()`

The problem is that when the shortcode is opened in the visual builder, it is automatically focused but there is no drop down. It must be clicked outside and then inside again to refresh.

See this gif:

![unyson](https://cloud.githubusercontent.com/assets/1108563/26165438/a3d792fe-3b38-11e7-9d47-290a81e74b14.gif)

**Comment by GheorgheP** [comment]
It seems to be same issue: https://github.com/ThemeFuse/Unyson/issues/2516

**Comment by pnpetroff** [comment]
Ah, sorry. There is even a GIF too in that thread :D
