### ISSUE TITLE
How to implement multiple demo installation?

### ISSUE THREAD

**Issue by charlesjohn2004** [ThemeFuse/Unyson#2609]
I am a theme developer who uses Unyson framework. I have multiple demos for a theme. Is there anyway I can let the buyer choose any demo to install without actually adding all the demo files to the theme file? Adding all the demo files will make the theme bulky. I am looking for a 1 click installation method, is that possible?

**Comment by charlesjohn2004** [comment]
Any ideas?

**Comment by DevWael** [comment]
check this http://manual.unyson.io/en/latest/extension/backups/index.html#demo-content-install

**Comment by charlesjohn2004** [comment]
Thank you!
