### ISSUE TITLE
demo site crashed

### ISSUE THREAD

**Issue by shiruken1** [ThemeFuse/Unyson#261]
Hey guys! My demo site crashed when I activated the Scratch Parent theme. Here's the error: 

Fatal error: Cannot redeclare fw_fix_path() (previously declared in /home/tfuselab/public_html/wp-content/themes/scratch-parent/framework/bootstrap.php:14) in /home/tfuselab/public_html/wp-content/plugins/unyson/framework/bootstrap-helpers.php on line 12

Also, I added a portfolio entry on my local build, and then added it's category to the sidebar menu, but when I click on it it gives me a 404.

Any ideas? Thanks!

**Comment by danyj** [comment]
crashed how? any errors? post more info and link please.

**Comment by shiruken1** [comment]
I was just updating the comment LOL

**Comment by moldcraft** [comment]
@shiruken1 It's on ThemeFuse TestLabs or on your localhost?

**Comment by shiruken1** [comment]
Portfolio error on localhost.
Theme activation error on TestLabs

**Comment by sergiubagrin** [comment]
@shiruken1 - Can you give me a screen with this error?

**Comment by sergiubagrin** [comment]
Link to Scrach Theme v2.0: https://github.com/ThemeFuse/Scratch-Theme 

Scratch Theme v.1.0 is not compatible with Unyson plugin. In first version Unyson was build-in theme

**Comment by shiruken1** [comment]
Sure thing. Here you go: http://testlabs.themefuse.com/andrescardonllcnet

**Comment by shiruken1** [comment]
Let me know if you still want an actual screenshot

**Comment by sergiubagrin** [comment]
@shiruken1  

Yes i need it. On Testlabs is v1.0 of Unyson i wanted to change it when Scratch Theme v.2.0 will be finished. I wil eliminate testlabs from Unyson page 

Give me a screenshot.

**Comment by shiruken1** [comment]
Nevermind! Just updated to the version that just came out and all works as supposed.

Thanks for the support, though! Especially if you were the one who fixed it with the new update :)

AWESOME framework, btw. I'll definitely be learning to work it. Would you guys be interested in outside theme developers for your store?

**Comment by sergiubagrin** [comment]
@shiruken1

Q: Would you guys be interested in outside theme developers for your store?
A: We build all our themes in house.
