### ISSUE TITLE
Is it possible to retrieve specific option using get_options method?

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#2610]
Would be great to make it possible fw_ext('shortcodes')->get_shortcode('parallax')->get_options( 'key' ).
Thanks!

**Comment by GheorgheP** [comment]
You'll have to use `fw_ext('shortcodes')->get_shortcode('parallax')->get_option( 'key' )` instead of `->get_options('key')`

**Comment by onebelarusianguy** [comment]
@GheorgheP thanks for the answer. It will be available in update?

**Comment by onebelarusianguy** [comment]
@GheorgheP thanks!
