### ISSUE TITLE
Select with dynamic options - no validate

### ISSUE THREAD

**Issue by chigancas** [ThemeFuse/Unyson#2611]
Guys.. i've been trying so hard make this work... i have two selects in a form and both get the options dynamically..but when i send the form shows me this error "Submitted data contains not existing choice".

how can i disable the validation? which files i have to edit?

PS.: Sorry for my english

**Comment by GheorgheP** [comment]
I would recommend to extend the select input type class and overload the `frontend_validate` method and write your own rules.
Same goes for radio and checkboxes.
