### ISSUE TITLE
Date-picker as year-picker?

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2614]
Is there a way to use the date-picker as a year-picker?

It would be great to use this, as it is a fool-proof way to select a year.

Any thoughts?

**Comment by GheorgheP** [comment]
I think you can make very easy an year picker using the `multi-select` option and provide the available years.

**Comment by noesteijver** [comment]
Yes, I think it's do-able with a solution like that, thanks!

I was just wondering if it was an available option within the date-picker, that's all!
