### ISSUE TITLE
Backup needs php zip - need help

### ISSUE THREAD

**Issue by andrenalin282** [ThemeFuse/Unyson#2615]
Hi,
i would like to load demo data, but i get the message php zip is needed.

unyson V 2.6.16
wp 4.7.5

phpinfo:
zip: enabled
version: 1.12.5
libzip: 0.11.2

has someone any idea to solve this problem?

best regards

**Comment by GheorgheP** [comment]
Unyson uses the [ZipArchive](http://php.net/manual/en/class.ziparchive.php) class, plase make sure that class exists.

**Comment by andrenalin282** [comment]
it´s installed...
can i check the class easily?

**Comment by danyj** [comment]
not just zip  but Zlib ,  ZipArchive  requires zlib 

http://php.net/manual/fr/book.zlib.php
![screenshodewdt_1](https://cloud.githubusercontent.com/assets/2340172/26401178/e646f6ba-4084-11e7-8c82-6af6c914db6a.jpg)

by default php 7.x  has it disabled so it needs to be enabled and recompiled. Your host should do that .

https://www.digitalocean.com/community/questions/php-7-0-ziparchive-library-is-missing-or-disabled

**Comment by GheorgheP** [comment]
You can check with this php code:

```php
echo class_exists('ZipArchive') ? 'Installed' : 'Not Installed';
```

**Comment by GheorgheP** [comment]
Thank you @danyj, I didn't notice this.

**Comment by danyj** [comment]
I had trouble with it few weeks ago , went from 5.6 to 7.x  and did not know that is disabled by default. had to recompile again trough whm

**Comment by danyj** [comment]
@andrenalin282    ZipArchive   on/off has been placed on its own , so if you are recompiling on your own than all 3 must be enabeled , zip, zlib ( these 2 should be on already) and ZipArchive .  If you are not hosting on your own , tell your host to enable ZipArchive  for php 7.x

**Comment by andrenalin282** [comment]
i just updatet to php 7.0 to check if it works with a newer version :-)
class_exists gives us the right answer... does not exist!

now we will enable it and check it again!
thanks a lot for the fast help 👍

**Comment by GheorgheP** [comment]
Please confirm that the issue is solved.

**Comment by andrenalin282** [comment]
Hey,
need to work a little outside.
Now after some package installations everything works, i don´t now what exactly 
but i think the lib was not installed.

thanks for the fast support!!!
best regards
