### ISSUE TITLE
Page builder active suggestion

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2617]
I did this in my own admin script but it would be great if framework would do this on its own. 

If page builder is active  in page/post edit screen  , add a class to html. 

I use it to hide some settings via CSS instead of constantly look for the builder on/off and hide things via JS. 

```
	fwEvents.on('fw:ext:page-builder:editor-integration:show', function () {
		
		$('html').addClass('fw-page-builder-active');
		
	});	
	
	fwEvents.on('fw:ext:page-builder:editor-integration:hide', function () {
		
		$('html').removeClass('fw-page-builder-active');
		
	});	

```

**Comment by GheorgheP** [comment]
Hmmm, for me sounds good, it is like wordpress `body_class` usage.
@andreiglingeanu, what do you think abut that?

**Comment by andreiglingeanu** [comment]
Looks okay but would like to make it that way:

- I think the class should be added to the `body` element
- The class should be named `fw-page-builder-editor-integration-active`, just to be clear that it refers to the builder being integrated with the main post editor

**Comment by danyj** [comment]
reason why I added class to html is because some plugins add modals/tooltips  outside the body ( crazy )  , this way you can catch them all.

**Comment by andreiglingeanu** [comment]
> outside the body

That is completely crazy. Which plugins do that?

**Comment by GheorgheP** [comment]
@andreiglingeanu I know such modals that go outside of the body because hey want to affect the body, let's say when the modal is open, to apply the CSS `blur` filter on the body so the entire body will be blur.

@danyj I understand that there are some exceptions, but that doesn't mean that we should violate the standards because others do it too, that class name should be added in the body.

**Comment by andreiglingeanu** [comment]
@GheorgheP Most of them (the ones that I know about, and I've worked with a lot of them) just create a special `backdrop` element which is positioned on top of everything and no need to insert elements outside of `body`.

**Comment by GheorgheP** [comment]
@andreiglingeanu I know, but there are some cases when developers create their own modals and do such things too. But it doesn't matter, as I mentioned, we should not violate the standards because others do it.

**Comment by danyj** [comment]
what ever you do works for me ,   

> violate the standards

how is a html class standard violation? 

Modernizr does it and is not one but docents of classes. 
https://css-tricks.com/why-use-classes-or-ids-on-the-html-element/

**Comment by GheorgheP** [comment]
In HTML is not allowed to add elements outside the `body` and `head` tags.
More then that, all content elements should be added in `body` tag only.
