### ISSUE TITLE
custom icon set in mega menu disappeared after update

### ISSUE THREAD

**Issue by sandrodz** [ThemeFuse/Unyson#2618]
This worked great before update:
<img width="1280" alt="screen shot 2017-05-25 at 6 02 33 pm" src="https://cloud.githubusercontent.com/assets/8479569/26453438/c47f1738-4174-11e7-9be7-f1cc79631776.png">

**Comment by Bogdan808** [comment]
What is wrong now?

**Comment by sandrodz** [comment]
Icomoon list is not displayed in the dropdown.

**Comment by sandrodz** [comment]
<img width="159" alt="screen shot 2017-05-25 at 7 16 54 pm" src="https://cloud.githubusercontent.com/assets/8479569/26456645/c684622c-417e-11e7-9067-7d5d0a5b570d.png">
<img width="462" alt="screen shot 2017-05-25 at 7 17 07 pm" src="https://cloud.githubusercontent.com/assets/8479569/26456646/c6b39588-417e-11e7-84e9-74515873e343.png">

**Comment by GheorgheP** [comment]
Are you sure it worked before?
The `icon` option type has the `set` property, where you specify which set to be used, by default is used the `font-awesome`, in order to change the icon set you need to specify it.

```php
function _filter_iconmoon( $option ) {
	$option['set'] = 'iconmoon';

	return $option;
}

add_filter( 'fw:ext:megamenu:icon-option', '_filter_iconmoon' );
```

**Comment by sandrodz** [comment]
@GheorgheP  yes I'm pretty sure it worked. Looked at the empty icon in the first screenshot. Custom icon was set, was used, than it stopped working.

**Comment by sandrodz** [comment]
@GheorgheP can I've both? fa and icomoon? this is how it worked before, I had all icon fonts available.

While filter worked, font itself is not being included automatically.

<img width="784" alt="screen shot 2017-05-26 at 1 45 46 pm" src="https://cloud.githubusercontent.com/assets/8479569/26489717/a739c3da-4219-11e7-8763-b099e7eee6e5.png">

**Comment by sandrodz** [comment]
@GheorgheP is there a way to have fa + icomoon together?

**Comment by sandrodz** [comment]
@GheorgheP any clues would be appreciated.

**Comment by GheorgheP** [comment]
At the moment this is not possible with `icon` option type, but it wasn't possible before too.
I will make an commit adding this possibility.

**Comment by sandrodz** [comment]
any luck here?

**Comment by GheorgheP** [comment]
I'm sorry, at the moment we run out of time. I will implement this feature in a later update.
