### ISSUE TITLE
Font Uploader: Is this planned?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#262]
I was just curious, do you have any plans of adding a Custom Font Uploader option?

**Comment by moldcraft** [comment]
Give us an example please.

**Comment by pe6o** [comment]
I read somewhere ( a long time ago) in the redux framework that they've worked on a custom font uploader that allows you to just upload a zip and auto-adds the font to the typography module. I think they never finished it though.

I was thinking, what do you think of such idea?

**Comment by moldcraft** [comment]
You want to implement such feature in your theme, how it should work (more details please) ?

**Comment by pe6o** [comment]
I was thinking:

An Upload button in the Typography field. The user uploads *.otf or other font file type, it's then uploaded on the server and it appears on the typography fields as a drop down Font Family option.

Okay, now it sound to me too complex..

**Comment by moldcraft** [comment]
Sorry, I think this option will be weird/complicated/confusing.
