### ISSUE TITLE
section count and index

### ISSUE THREAD

**Issue by iulianflst** [ThemeFuse/Unyson#2620]
Hello,

in the shortcode view I want to be able to get:

1. Total count of sections in a page (I need to close and open some tags in order to have a div full width)
2. I need to have index ( for instance section 1 = 0, section 2 = 1, section 3 = 2 etc ) 

can anyone point me in the right direction ?

**Comment by thednp** [comment]
Iulian @iulianflst this kind of stuff have been discussed before, [no solution was found](https://github.com/ThemeFuse/Unyson/issues/1750#issuecomment-231447553) so far.

**Comment by danyj** [comment]
```
function _thz_filter_check_section_layout ($items,$items_types){

	fw_print($items);
	return $items;
	
}

add_filter( 'fw:ext:page-builder:json-structure-correction:complete', '_thz_filter_check_section_layout',10,2 );
```

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/2511
