### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Mark2312** [ThemeFuse/Unyson#2621]
Hello!

Tell me please, where can I find the Translation extension? In video tutorials it is present, the site also has a mention of it http://manual.unyson.io/en/latest/extension/translation/index.html#content, but in the plug-in itself this extension is for some reason missing (Maybe I'm not Or do I need to download it separately?

**Comment by thednp** [comment]
The development for this extension has been put on hold, but you can still download it and upload it to your `site/wp-content/plugins/unyson/extensions` folder.

**Comment by GheorgheP** [comment]
I would recommend to use the [WPML](http://wpml.org/) or the free plugin [Polylang](https://wordpress.org/plugins/polylang/) to translation, because we are not sure if we'll continue the Translation extension development/maintenance.
