### ISSUE TITLE
can i make a premium template and sell from this framework

### ISSUE THREAD

**Issue by techashish12** [ThemeFuse/Unyson#2622]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.

**Comment by thednp** [comment]
Yes, like any other open source software. 

But you should not include it into your theme folders, but rather use the plugin and the Wordpress update capability.

**Comment by GheorgheP** [comment]
There are more then 150 themes on ThemeForest made on Unyson: https://themeforest.net/search?referrer=homepage&term=unyson&utf8=%E2%9C%93
I would recommend by instigating Unyson [documentation](http://unyson.io/), also you can start building the theme using our [Scratch Theme](https://github.com/ThemeFuse/Scratch-Theme).
