### ISSUE TITLE
Height of slider not correctly

### ISSUE THREAD

**Issue by xttn** [ThemeFuse/Unyson#2623]
Hi, I render slider front-end follow document here: http://manual.unyson.io/en/latest/extension/slider/index.html?highlight=slider#frontend-render
```
$render_slide = fw()->extensions->get('slider')->render_slider(69, array(
    'width'  => 1920,
    'height' => 700
 ));
```
Slider on website only height 550px though i changed this to other value. Does anyone have an idea on how to fix this?

**Comment by GheorgheP** [comment]
Did you solve the issue? What it was?

**Comment by xttn** [comment]
Yes, I have a little confusion, sorry
