### ISSUE TITLE
Page Builder functional is unavailabe

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#2625]
One of my clients faces with the issue that VPB stopped working after a while.
I've re-intsalled Unyson with VPB extension with no success.
VPB is enabled for pages as well:

![download](https://cloud.githubusercontent.com/assets/13021107/26721886/652eb91e-4796-11e7-9f89-8c4f49da41c7.png)

But I still see:
![download 1](https://cloud.githubusercontent.com/assets/13021107/26721888/68898d64-4796-11e7-8da9-1b7b34399c06.png)

No additional plugins.

Any thoughts? Thanks

**Comment by GheorgheP** [comment]
The problem is that out VPB is dependent of the `Visual` tab in tinymce. In our case the client disabled it.
You need to enable back it from **Dashboard>Users>Your Profile** by disabling **Visual Editor** option:

![](https://static.md/845223997022087eefa801c93ef3f8e2.png)

**Comment by onebelarusianguy** [comment]
@GheorgheP Oh, didn't know about this option, thanks!
