### ISSUE TITLE
Can't figure out how to change names of sections in builder

### ISSUE THREAD

**Issue by gigit95** [ThemeFuse/Unyson#2629]
It's not an issue but does Unyson team plan to develop a possibility to add a custom text in the section name in "builder"? I mean "change name" option.
![unyson](https://cloud.githubusercontent.com/assets/11440530/26741559/1d0abf04-47da-11e7-97c0-954aa28393b3.JPG)

**Comment by danyj** [comment]
add in options 


			'section_title' => array(
				'type' => 'text',
				'label' => __('Sorting title', 'fw'),
				'value' => '',
				'desc' => __('Desc', 'fw')
			),


add in config.php

```
$cfg = array(
	'page_builder' => array(
		'tab'         => __('Layout Elements', 'fw'),
		'title'       => __('Section', 'fw'),
		'title_template' => '{{-title}}{{ if (o.section_title) { }} : <strong>{{= o.section_title}}</strong>{{ } }}',
		'description' => __('Add a Section', 'fw'),
		'popup_size'  => 'large',
		'type'        => 'section' // WARNING: Do not edit this
	)
);
```

**Comment by danyj** [comment]
see also 
https://github.com/ThemeFuse/Unyson/issues/759

**Comment by gigit95** [comment]
THANK YOU SIR! Just a big "THANK YOU"! And a little question: is there any forum or some FB group where I could ask for help? I think, here, on github, it's more for issues and I don't want to be annoying.

**Comment by danyj** [comment]
just ask away. this is the best olace for it.

**Comment by Toggenburger** [comment]
Sorry, newbie question :-(
Can someone point me to the correct file locations, please?
If I have a theme child the config is within the child-themes framework-customizations, correct?
But where is the config file? :-O
Thx.
