### ISSUE TITLE
Demo content location inside plugin instead of theme  

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#2630]
Is it possible to locate demo content inside plugin? Say I have "theme-extra" plugin and I want to put demo content inside it rather than putting inside theme folder. 
```
add_filter('fw_ext_backups_demo_dirs', 'magnews_demo_dir');
  function magnews_demo_dir($dirs) {
    $dirs[get_template_directory() .'/framework/demo-content'] = get_template_directory_uri() .'/framework/demo-content';
   return $dirs;
}

**Comment by GheorgheP** [comment]
Sure, and you did all right, except to one thing, you should replace the `get_template_directory()` and `get_template_directory_uri()` with functions that returns path other `demo-content` folder of your plugin.
