### ISSUE TITLE
Unyson how set icons  on my header??

### ISSUE THREAD

**Issue by zxdWp** [ThemeFuse/Unyson#2631]
span class="border-ico">i class="fa fa-facebook" aria-hidden="true"></i></span
span class="border-ico">i class="fa fa-twitter" aria-hidden="true"></i></span
span class="border-ico">i class="fa fa-pinterest-p" aria-hidden="true"></i></span
span class="border-ico">i class="fa fa-instagram" aria-hidden="true"></i></span

I have this html code ,How to do it so I can add them to the theme option?
Thanks ! Sorry for my English!

**Comment by GheorgheP** [comment]
Could you explain in more details what do you want to do?
