### ISSUE TITLE
Bug: Datetime Picker popup interferes with ACF Date Time Picker

### ISSUE THREAD

**Issue by Saxtone** [ThemeFuse/Unyson#2635]
I'm currently creating a countdown shortcode where I have added a **Datetime field** for the time. Everything here is working as it should. The problem occurs when I try to use the **ACF Date Time Picker** field type [(link)](https://www.advancedcustomfields.com/resources/date-time-picker/). ACF is using a different JS popup container for the datetime, but when I have both plugins active the **Unyson Datetime popup overwrites the ACF one**.

If there is no Unyson `datetime-picker` field used anywhere in the theme, everything is working as it should (the popup isn't loaded and ACF displays its popup). But once there is a such field added the ACF popup stops triggering and only the Unyson one is displayed.

I tried looking into both plugins code and see how the Datetime JS popup is loaded, but I can't seem to find the problem. The Unyson Datetime popup should target only its container with the Unyson classes, but somehow it is being displayed on the ACF Datetime field too.

**Comment by GheorgheP** [comment]
I just tested the ACF and Unyson `datetime-picker`, and seems to work fine.

![](https://static.md/0ea1141112fe80173df03a08d491f419.png)
![](https://static.md/5342c64b6825bda4345f8775c21ab978.png)

**Comment by Saxtone** [comment]
It works fine with the ACF **Date Picker**, which you are testing with. There is another field type **Date Time Picker**, which loads the Unyson Picker instead of the ACF one: https://www.advancedcustomfields.com/resources/date-time-picker/

**Comment by pnpetroff** [comment]
+1
Having the same problem with the date-time picker field.

**Comment by pnpetroff** [comment]
Is there any fix for this issue?
