### ISSUE TITLE
Pages restored from Unyson backup file lack content

### ISSUE THREAD

**Issue by delappdesign** [ThemeFuse/Unyson#2636]
We're in the process of attempting to recover a site built using Unyson and a premium theme, Ciao. We have a "full backup" file exported from Unyson, but attempts to restore the site using this file have resulted in a site partially rebuilt: pages are restored but lack content in the page builder, menus are recreated but not associated with menu locations, and some (but not all) media files are missing.

The page content is the biggest concern. I believe the needed page content is in the Unyson backup, as I have expanded the zip file, opened the "database.json.txt" file in a text editor, and found relevant text and media file references among the JSON. 

Here are the steps taken to recover the site:

1. Create a clean install of WordPress with a new database
2. Install the Unyson plugin
3. Manually copy the Unyson full backup zip file to /wp-content/uploads/fw-backup
4. Go to Dashboard > Tools > Backup, select the one backup file now listed on this page, then click "Restore"
5. Unyson via it's AJAX update indicates it is expanding the zip, updating the database, etc. I can see themes, media files, and plugins being added to the wp-content folder, and new entries added to the database.
6. Upon completion, WordPress requests I "Update the database to continue", so I click "Update".
7. I'm returned to the Dashboard, and see the pages restored, Ciao theme installed, etc. But, editing a page shows the Visual Builder with no blocks, content, or anything else. 

Side note: Some pages do have a revision history, and viewing past revisions (that typically predate the addition of Unyson to the site) show pre-Unyson content for pages. Restoring those past revisions will add the content as a "Text Block" block in the Visual Builder. But again, the versions of those pages built with the Unyson Visual Builder are not appearing. 

Is there a step or process I'm missing? There is not other backup we're aware of for the site -- only this Unyson backup file.

**Comment by GheorgheP** [comment]
Can you share the backup file to me on `pisarenco[dot]gh[at]gmail[dot]com`
