### ISSUE TITLE
Demo content install issue. The execution failed. Please check error.log

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2638]
One of our clients tried to install demo content and getting this error. "The execution failed. Please check error.log"

![ff](https://puu.sh/wdaNL/826fc90c26.png)

I have checked console but nothing there. This site max execution set to 300 but still not working.

Here Is the requestb URL https://requestb.in/11gnkca1?inspect

**Comment by GheorgheP** [comment]
Can you make a little debugging and see on what step it stops? Also did you enable the `WP_DEBUG` and `WP_DEBUG_LOG`?

**Comment by ViorelEremia** [comment]
Try: ThemeFuse/Unyson-Backups-Extension@f8d5f6a...841413f
