### ISSUE TITLE
We nee to re think how Content Install works

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#264]
Content install is a bit of a pain to do, we'll need to re think how to do it in way that is part of the install process. Now you install everything and you need to go to Tools > Content Install (was Auto Install, but we've change it to make it more clear) in order to import the content from our servers.

**Comment by thednp** [comment]
I am curious, do the replacements also manage the local network IP instead of localhost? Thanks

**Comment by sergiubagrin** [comment]
@thednp 

Remote Content Demo Install was added to trello to do list: https://trello.com/c/6EAny3WJ/54-content-demo-install-remote-server

**Comment by thednp** [comment]
@sergiubagrin 

On a locahost site, usually your wp site uses these general settings:

WordPress Address (URL) and Site Address (URL)
http://localhost/my-wp-site

in my current development install I use

http://192.168.1.120/my-wp-site

**Comment by sergiubagrin** [comment]
It will replace old General settings with new General Settings for example:

Example 1 (http://localhost/wp): Replace http://localhost/wp -> http://yoursite.com
Example 2 (http://192.168.1.1/wp): Replace http://192.168.1.1/wp -> http://yoursite.com
Example 3 (http://mysite.com/wp): Replace http://mysite/wp -> http://yoursite.com

**Comment by thednp** [comment]
@sergiubagrin thanks so much. Any news on this development?

**Comment by sergiubagrin** [comment]
It is in work like you can see in Trello Roadmap: https://trello.com/c/6EAny3WJ/54-content-demo-install-remote-server

On trello is only Remote server but we added more options. On this version if a user will install a theme with unyson and developer added in config that Unyson plugin and extensions must be installed by default user on activation will receive a full working theme

Right now it is working in next way:

1. Install Theme (manually)
2. Activate Theme (manually)
3. Install Unyson (manually)
4. Activate Unyson (manually)
5. Install Extensions (compatible) (manually)
6. Install Demo Content Install (manually)

In next versions it will be: 

1. Install Theme (manually)
2. Activate Theme (manually)
3. Install Unyson (automatically if this one was added to theme config file)
4. Activate Unyson (automatically if this one was added to theme config file)
5. Install Extensions (compatible) (automatically if this one was added to theme config file)
6. Install Demo Content Install (manually)

Thanks

**Comment by thednp** [comment]
Very well. I would also move the sample content installer into an option type and move everything in there, with option to delete the "autoinstall" folder after installation.

**Comment by sergiubagrin** [comment]
We have this option on out list but i don't know if this is a good solution.

**Comment by thednp** [comment]
We can develop and test of course, but surely this could be done perfectly. I mean I did it for other framework and I am sure Unyson can do even better.
