### ISSUE TITLE
Option Icon v2 problem

### ISSUE THREAD

**Issue by 9585999** [ThemeFuse/Unyson#2641]
Hi, I ran into a problem when I tried to use the icon v2 option, that's what I get when I try to call this option.

![img 2017-06-10 16 27 06](https://user-images.githubusercontent.com/16165904/27003157-3cc84494-4dfa-11e7-91f7-76d9c72a9bfb.PNG)

At the same time, the icon option works well ...

![img 2017-06-10 16 26 47](https://user-images.githubusercontent.com/16165904/27003177-78b50c8a-4dfa-11e7-81d5-b1a7ef8131b0.PNG)

I use:
[Sage](https://github.com/roots/sage),
[Bedrock](https://github.com/roots/bedrock),
Wordpress 4.8

**What could be the problem?**

**Comment by andreiglingeanu** [comment]
Are you able to reproduce it with other than your theme?

**Comment by 9585999** [comment]
![img 2017-06-18 0 47 10](https://user-images.githubusercontent.com/16165904/27256507-b36e14f0-53bf-11e7-86b3-f8e0d1b9c951.PNG)

**Comment by andreiglingeanu** [comment]
I mean the JavaScript console itself, not the DOM nodes.

**Comment by 9585999** [comment]
with theme twenty seventeen in chrome.
![img 2017-06-19 11 53 43](https://user-images.githubusercontent.com/16165904/27277274-70952b5a-54e6-11e7-9bec-b4b5fe0598dc.PNG)
With my theme the same thing, the errors that were in the safari - from the installed plugins in the safari ...

**Comment by andreiglingeanu** [comment]
I definitely doesn't happen for me. All working fine, I put the option in `posts/page.php` too.
