### ISSUE TITLE
Shortcode for specific post type only

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#2642]
Is it possible to add shortcode element only for certain post type ?

**Comment by NiloySarker** [comment]
Probably, Not possible

**Comment by andreiglingeanu** [comment]
Sure thing. Just create a shortcode and disable it in every post type but the one you need it to be present in. Refer to this [issue](https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/issues/8#issuecomment-327734404) as a way to disable shortcodes.
