### ISSUE TITLE
How to Remove the default shortcode css

### ISSUE THREAD

**Issue by NiloySarker** [ThemeFuse/Unyson#2643]
Hi,
when i add shortcodes into any pages there are some default .css files will add into the frontend.
Is thre any why to remove them ? because all of my shortcode design come from theme-base.css . So i don't need them.
<img src="https://image.prntscr.com/image/YxcNf3SRS2G7QFWaAO7JZg.png" />

**Comment by 2Fwebd** [comment]
Hi there, 

You can use this WP function in your theme / child theme hooks.php file: 

https://codex.wordpress.org/Function_Reference/wp_dequeue_style

The `$handle` is most likely the ID you see on these `<link>`tags :)
