### ISSUE TITLE
Theme Update Service

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson#2644]
Hello,
Is it possible to update the theme via Unyson ? 
I saw in code there is only github service, but then our theme must be public.
Currently we run our VCS on a private gitlab server, but also a zip is made available to those that bought the theme on a frontend server.

Maybe someone did something in this direction or if not Any suggestions on what would be the correct way to implement it ?

PS: specifically for ThemeFuse guys : how you do it at ThemeFuse ? Is it a custom service extending Unyson-Update-Extension ?

PPS: I saw this issue https://github.com/ThemeFuse/Unyson/issues/797 and solutions posted in it. I am waiting for a way to do it through unyson though.

Thanks!

**Comment by 2Fwebd** [comment]
Hi there, 

Actually it's pretty easy to develop using the Unyson extension pattern and a simple API on your server. 

I am attaching here what we WERE using in the past before building a more complex API for our [woffice](https://woffice.io) product.  

Have a quick look on it, it's quite old and is not used on our side anymore but that does the job just fine :)

Any question, let me know!

[woffice-updater.zip](https://github.com/ThemeFuse/Unyson/files/1082566/woffice-updater.zip)
[API.zip](https://github.com/ThemeFuse/Unyson/files/1082569/API.zip)

**Comment by danyj** [comment]
Unyson The Core Theme has extension for it http://prntscr.com/fkvr2y

**Comment by toleabivol** [comment]
I did it by extending the FW update extension class as it does with github update extension and it calls our server's API.

https://gist.github.com/toleabivol/0322558cc4615ebeae9518f4030b7d1e

Thanks everyone for sugestions.

**Comment by danyj** [comment]
@toleabivol ,  you mind sharing the API ?

**Comment by toleabivol** [comment]
@danyj it's a bit of a security thing to make that public ... I will see if I can obfuscate all needed.

**Comment by ViorelEremia** [comment]
http://manual.unyson.io/en/latest/extensions/cookbook.html?highlight=custom%20update

**Comment by ViorelEremia** [comment]
@toleabivol That is working and for theme update

**Comment by ViorelEremia** [comment]
http://manual.unyson.io/en/latest/extensions/cookbook.html#download-udpate-extension-via-custom-server

**Comment by danyj** [comment]
@ViorelEremia 

>That is working and for theme update

how about our own plugins ? They dont have manifest

**Comment by danyj** [comment]
The custom index makes no sense , 
it says you can list multiple extensions 



```
 /*
 *  If you have many extensions or themes, check if you have it.
 *  item - is name of extension or id of theme from manifest.php
 */
$my_products = array(
    'extension' => array( 'extension_name', 'extension_name1' ),
    'theme'     => array( 'scratch', 'scratch1' ),
);
```

but in the middle advises to pull the version for one theme/etension


```
/**
 * Extract latest version for theme or extension.
 */
$version = '1.0.1';
```

**Comment by danyj** [comment]
that doc is incomplete, you say is working for themes but there is no info on where to provide the extensions type or list multiple extensions versions. We should not be guessing these things especially if the doc is written. 

evens some comments make no sense like 

 *  If you have many extensions or themes, **check if you have it.**

what am I supposed to do with that?


Please someone complete that doc with working files and correct instructions for all updatable file types, 
extensions,themes etc.

**Comment by toleabivol** [comment]
@ViorelEremia interesting ! When was this added ? And what would be the pros/cons if compared to my solution ( extending `FW_Ext_Update_Service` ).
