### ISSUE TITLE
Error on Download Full Backup: This site can’t be reached

### ISSUE THREAD

**Issue by PhoenixMaximus** [ThemeFuse/Unyson#2645]
Hello,
I am receiving an error when I try to download any full backup in the list on a specific site. This site previously had issues with the scheduler not creating backups automatically, and I had to add some code and it worked fine. Now I receive the following error when I try to download a full backup (database backup downloads fine):

---
This site can’t be reached

The webpage at x.com might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
---

As a general comment, this plugin looks and behaves differently between the two simple sites I have it on. One site calls it a content backup and full backup, while the other calls it database backup and full backup. On one site I can click the download link normally and the download begins; on the other site, I have to right click the download link and use Save Link As.

Advice is greatly appreciated.

**Comment by ViorelEremia** [comment]
you can try with latest version should works: https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/368
