### ISSUE TITLE
Taxonomies Option data not display value

### ISSUE THREAD

**Issue by NiloySarker** [ThemeFuse/Unyson#2646]
I add new option for taxonomies 
1. https://prnt.sc/fj8rwe
2. http://prntscr.com/fj8wy0
as I can see the label value is saved in the backend. but when I try to echo the value on taxonomy-fw-portfolio-category.php and signle.php page not show nothing?
I Try both for echo this value 
`fw_get_db_term_option($term_id, $taxonomy, $option_id, $default_value = null)`
--
` $team_option = fw()->theme->get_taxonomy_options('fw-portfolio-category');
                  fw_print($team_option['tax_icon'] );`
but unfortunately, it's show the deafault value 
http://prntscr.com/fj902j

Am i miss something ?

**Comment by danyj** [comment]
try ,  this
```
function thz_get_term_option($id,$default = null){
	
	$tax = is_tax() ? get_queried_object()->taxonomy :'category';
	return fw_get_db_term_option(get_queried_object_id(),$tax,$id,$default);
		
}
fw_print( thz_get_term_option('tax_icon','default'));
```
