### ISSUE TITLE
Text block go out of margin

### ISSUE THREAD

**Issue by nmbugedo** [ThemeFuse/Unyson#2647]
Hi! I'm having problem in a "text block" cause I wrote a large paragraph and it doesn't show in different lines.. it shows like 1 line really long that goes off the page margins.

![captura de pantalla 2017-06-13 a la s 11 24 12](https://user-images.githubusercontent.com/26467242/27090479-4ad266ae-502b-11e7-94be-9ea548fe05bc.png)

**Comment by 2Fwebd** [comment]
Hello, 

It's most likely a CSS issue from your theme. 

You can try the following CSS change: 
````
p{
     word-wrap:break-word;
}
````

That should do the job.
