### ISSUE TITLE
Please turn on selectize remove_button plugin in  multi select option type

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2649]
Curenlty in multi select when you select 5 items for example and want to remove 3rd  one,  you have to delete the 4 and 5,   if you add this 

    plugins: ['remove_button'],

here https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/multi-select/static/js/scripts.js#L51-L58

```
			$this.selectize({
				maxItems: ( limit > 0 ) ? limit : null,
				plugins: ['remove_button'],
```

it tuns on the remove button and you can pick what needs to be removed without deleting  anything else 
![screenshot_1](https://user-images.githubusercontent.com/2340172/27142201-a9131a10-512a-11e7-99e8-3b8f09ce78e7.jpg)

**Comment by duongancol** [comment]
absolutely +1 for this feature

**Comment by danyj** [comment]
pull submitted, https://github.com/ThemeFuse/Unyson/pull/2651
