### ISSUE TITLE
How to retrieve page options?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#265]
I have 7 tabs in my theme options. One of those

    fw()->theme->get_options( 'layout' )

is also included in framework-customizations/theme/options/posts/page.php

	$options = array(
		'main' => array(
			'title'   => false,
			'type'    => 'box',
			'options' => array(
				fw()->theme->get_options( 'layout' ),
			),
		),
	);

and I see it in page settings
http://screencast.com/t/ck5PkA67k

How do I retrieve those options in frontend? 

For theme options I can use 

    fw_get_db_settings_option('option_name')

but how do I do it for page options?

**Comment by moldcraft** [comment]
[`fw_get_db_post_option($post_id, $option_id, $default_value = null)`](http://manual.unyson.io/en/latest/helpers/php.html#fw-get-db-post-option)
