### ISSUE TITLE
How do we get section attributes from the row item view file

### ISSUE THREAD

**Issue by guydumais** [ThemeFuse/Unyson#2652]
I need to access the attributes ($atts['parameter'] available in the view file for a SECTION 
`fw\extensions\shortcodes\shortcodes\section\views\view.php` from the view file for a ROW 
`fw\extensions\shortcodes\shortcodes\row\views\view.php`.

When I do a var_dump($atts) from  the view file for a ROW, I'm getting an empty array.

I tried `fw_ext('shortcodes')->get_shortcode('section')->get_options();` but this gives me only the default config value which are always the same.

I need it because I have to include a css class at a specific place in the view file for the row. It cannot be injected at the section level with a css class, which would have been much easier.

Thanks in advance for your great help, See you!

P.S.: These view files are overridden in my framework-customization folder.

**Comment by danyj** [comment]
you cant access inner/outer shortcodes within view, only that shortode atts are available, use this 

https://github.com/ThemeFuse/Unyson/issues/2511

**Comment by guydumais** [comment]
ok thanks @danyj, 

#2511 is a very good post that I keep for later usage but for now I've just found this quick fix for what I need. Here's my fix in case it could help :

In the **view.php** for the section I save the $atts in a GLOBAL variable by adding this line at the beginning: `$GLOBALS['section_atts'] = $atts;` and then simply retrieve them with` $atts = $GLOBALS['section_atts'];` in the view.php for the row.
