### ISSUE TITLE
[bug] Color pickers cant reach 000000

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2653]
Both our color pickers cant reach 000000 with drag, 
![screenshot_2](https://user-images.githubusercontent.com/2340172/27205051-ca5ce9c6-522e-11e7-9646-d5b0b9d73298.jpg)

I checked default iris and it works ok http://automattic.github.io/Iris/

**Comment by andreiglingeanu** [comment]
That's a CSS only issue, as far as I remember. We managed to fix it in our color picker.

**Comment by danyj** [comment]
> changing few layout properties

care to share the fix?

**Comment by terzom** [comment]
Any update?
