### ISSUE TITLE
Slider Error on WordPress 4.8

### ISSUE THREAD

**Issue by rafiul** [ThemeFuse/Unyson#2655]
Showing this error after WordPress Updated to 4.8

Warning: htmlspecialchars() expects parameter 1 to be string, array given in /home/xxxxx/public_html/xxxxxx.com/wp-content/plugins/unyson/framework/helpers/general.php on line 1372
value="" name="fw_options[posts_per_page]" />

**Comment by danyj** [comment]
What version of Unyson do you have? Are all extension up to date?

**Comment by rafiul** [comment]
My version is  **2.6.16**. Yes all extension also updated.

**Comment by danyj** [comment]
I suggest you contact your theme provider they would know more about  it. Looks like they used 

```
function fw_htmlspecialchars( $string ) {
	return htmlspecialchars( $string, ENT_QUOTES, 'UTF-8' );
}
```

function and are passing the array to it instead of the string.
