### ISSUE TITLE
Uncaught exception 'FW_Cache_Not_Found_Exception'

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#2656]
Hi! 
My client site stops working after activating Unyson plugin. 
When I checked the error_log, it showed
`PHP Warning:  Uncaught exception 'FW_Cache_Not_Found_Exception' in /home/agenci38/public_html/wp-content/plugins/unyson/framework/helpers/class-fw-cache.php:262`
Here is the [screenshot](https://monosnap.com/file/f3crjZ3lPTZgotjTqizg8xaymbEhN5)
Why the error happen?
Thanks!

**Comment by duongancol** [comment]
I found another issue. 
`Illegal string offset 'content' in /home/agenci38/public_html/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/testimonials/views/view.php on line 38`

**Comment by GheorgheP** [comment]
The `FW_Cache_Not_Found_Exception` is thrown when someone searches for a key in `FW_Cache` and it is not found.
It doesn't need to be related with the second issue.

In first case it seems you have an infinite loop. Doe this happen with default wordpress theme?
Please provide full log report.

About second issue, it seems that the testimonial was not saved properly and the `content` key is missing, you can remove it and add one more time.

**Comment by duongancol** [comment]
It's weird that the first issue doesn't show up when I activate the default theme. 
But I'm thinking it could be related to this issue https://github.com/ThemeFuse/Unyson/issues/2199
What do you think?

**Comment by duongancol** [comment]
the memory limit is 128 so I don't think it's the problem. Should I send you the site account?
Please give me your email address!

**Comment by duongancol** [comment]
I increase php memory limit to 256 and it seems to fix this problem.
Thanks for your time!

**Comment by danyj** [comment]
> I increase php memory limit to 256

that hides the issue. @GheorgheP  is right there is a bad loop somwhere

**Comment by duongancol** [comment]
I'm not sure. It still works on my local with 128mb memory limit.

**Comment by danyj** [comment]
see this issue I had with default values 
https://github.com/ThemeFuse/Unyson/issues/2034
