### ISSUE TITLE
Contact Form > How to override the view.php for an item?

### ISSUE THREAD

**Issue by guydumais** [ThemeFuse/Unyson#2657]
What I'm trying to do is to add a css class into a `<label>` element of the contact form.

What I found so far is a view file for a text item here :
`\extensions\forms\includes\option-types\form-builder\items\text\view.php`

When I put this file in my customization directory it doesn't seems to be overriden at all. 

I also looked for filters and actions but didn't find any css class filters or actions to do it.

Any suggestion or clue to help me achieve this?

Thanks in advance!

**Comment by danyj** [comment]
path should be 

theme_name\framework-customizations\extensions\forms\extensions\contact-forms\views\

there you email , form  and submit

https://github.com/ThemeFuse/Unyson-Forms-Extension/tree/master/extensions/contact-forms/views

**Comment by guydumais** [comment]
ok thanks, but from there, how do I override or customize a TEXT ITEM in the form? I mean, if I create a subfolder named **text** with the **view.php** in it, it doesn't work!

**Comment by danyj** [comment]
what are you trying to override? frontend or backend?

**Comment by guydumais** [comment]
FRONTEND.

In the HTML here, for example:
```
<div class="field-text">
    <label for="id-1">Name<sup>*</sup></label>
    <input type="text" name="text_8be1476" placeholder="" value="" id="id-1" required="required" >
</div>
```

I want to inject a css class here in the label element:
```
<div class="field-text">
    <label class="my-css-class-goes-here" for="id-1">Name<sup>*</sup></label>
```

**Comment by danyj** [comment]
tough on but here it is 

**create** folder name **form-builder** here 

`theme_name\framework-customizations\extensions\forms\
`

inside 
`theme_name\framework-customizations\extensions\forms\form-builder
`
copy **views** folder from here

https://github.com/ThemeFuse/Unyson-Forms-Extension/tree/master/includes/option-types/form-builder

and `create `folder name **items** 

go to 

`theme_name\framework-customizations\extensions\forms\form-builder\items  create folder 
`
text

go to  

`theme_name\framework-customizations\extensions\forms\form-builder\items\text
`
and copy this file to it 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/text/view.php


here is video of folders/files structure 
http://take.ms/9yXhe

@GheorgheP   this should be in the docs.

**Comment by guydumais** [comment]
Many thank @danyj, It's working now! 👍 

But I had to fix the folder name for the text view which should be VIEWS instead of view:
`theme_name\framework-customizations\extensions\forms\form-builder\items\text\views`

instead of

`theme_name\framework-customizations\extensions\forms\form-builder\items\text\view`

**Comment by danyj** [comment]
> But I had to fix the folder

true , I fixed it above , 


please change the issue title to 

How to override form extension elements in frontend ,  so that others can find it.

**Comment by guydumais** [comment]
Done 👍
