### ISSUE TITLE
Add font without prefix class

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson#2659]
Hello , 
trying to add ionicons to icon-v2 option.
All good but it displays the prefix class twice like for FA 
`<i class="ion ion-flex">` which should be `<i class="ion-flex">`
Tried with `apply_root_class => false` from https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon-v2/includes/class-fw-icon-v2-packs-loader.php#L118
But no luck. It's not a big issue though.

Edit: `'css_class_prefix' => ''` worked but am afraid it is still needed for the css file reading, no ?

**Comment by toleabivol** [comment]
Any news on this ?

**Comment by andreiglingeanu** [comment]
Sorry for getting back so late on that one!

#3192 will actually implement `apply_root_class` option & you will get only the icon class in HTML in backend **AND** in DB value for the option type. Be careful on that one.

Yes, `css_class_prefix` is needed for correctly parsing the CSS file at the phase of computing icons list.
