### ISSUE TITLE
Entering in a <script> html tag?

### ISSUE THREAD

**Issue by macdonjo** [ThemeFuse/Unyson#2660]
I'd like to place a Calendly calendar on my site. I'm not sure how exactly this can be done, as every method I try, it doesn't show anything on the site, or HTML.

```
<!-- Calendly inline widget begin -->
<div class="calendly-inline-widget" data-url="https://calendly.com/mike/30min" style="min-width:320px;height:580px;"></div>
<script type="text/javascript" src="https://calendly.com/assets/external/widget.js"></script>
<!-- Calendly inline widget end -->
```

**Comment by danyj** [comment]
Sorry bud but this is framework support corner. For custom html/css/js  issues please contact your theme provider.
