### ISSUE TITLE
Invalid option problem.

### ISSUE THREAD

**Issue by stiv1256** [ThemeFuse/Unyson#2661]
Hello! I am newbie and create my first project based on video No1 on page http://manual.unyson.io/en/latest/options/introduction.html#content . I got problem at the monent shown at the moment 1min 03 sek. of video replay. 1st problem  - I don't see a 'type' option of 'main'=>'Posts Options'. 2. If i create file post.php on above mentioned video (1min. 03 sek) :

```

<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$options = array(
     'main'=> 'Posts Options',
     'title'  =>'box'
     'options' => array(
     	$options => array(
             'demo_text_2' => array(
		        'label' => __('Text', 'unyson'),
		        'type'  => 'text',
		        'value'=>  'sfdkjbadfi ugheraigheri', 
		        'desc'  => __('sdvfdsgadfgadfbadfb', 'unyson'),
             ),
             'demo_textarea_2' => array(
		        'label' => __('Textarea', 'unyson'),
		        'type'  => 'textarea',
		        'value'=>  'sfdkjbad fi ugher aigheri',
		        'desc'  => __('sdvfdsgadfgadfbadfb', 'unyson'), 
   	         ),
	),
 ),
);
```
(I splited image into two files - it is too big).
https://user-images.githubusercontent.com/29522625/27274709-18429068-54dd-11e7-9396-3780e5cd18fc.jpg
https://user-images.githubusercontent.com/29522625/27274708-1840ef88-54dd-11e7-86ca-27c7edc7fdad.jpg
But if i changed my file like this
```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$options = array(
	 'Main'=> array(
     'label'  => __('Posts Options', 'unyson'),
     'type'  =>'box',
     ),
	  
             'demo_text_2' => array(
		        'label' => __('Text', 'unyson'),
		        'type'  => 'text',
		        'value'=>  'sfdkjbadfi ugheraigheri', 
		        'desc'  => __('sdvfdsgadfgadfbadfb', 'unyson'),
             ),
             'demo_textarea_2' => array(
		        'label' => __('Textarea', 'unyson'),
		        'type'  => 'textarea',
		        'value'=>  'sfdkjbad fi ugher aigheri',
		        'desc'  => __('sdvfdsgadfgadfbadfb', 'unyson'), 
   	         ),

);
```
I see something different: 
https://user-images.githubusercontent.com/29522625/27275136-cf980b16-54de-11e7-9dbb-9f06d8d87fe1.jpg 
/* UNDEFINED OPTION TYPE */ - only. 
I would be very appretiated if you will help me to fix this problem...

P.S.  I tried to attach archive of my theme (theming-lesson.zip) but this window replied me:"We don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."(I attach ZIP- file!) 
P.S.2 I used empty theme theming -lesson  generated by Underscores.me....

**Comment by ViorelEremia** [comment]
You have an error here: ```$options => array(```
