### ISSUE TITLE
Column stacking order on mobile

### ISSUE THREAD

**Issue by mintaras** [ThemeFuse/Unyson#2662]
Hi,

Do you have a column stacking order on mobile? (https://www.elegantthemes.com/blog/divi-resources/how-to-change-divis-column-stacking-order-on-mobile-devices)

I found that CSS classes (`fw-col-*-push-4, fw-col-*-pull-4`) 
already exists but could not find selection in front-end page builder..

Any ideas how I could achieve this?

Thank you.

**Comment by Ataurr** [comment]
You have to create a custom option in the column shortode.

**Comment by mintaras** [comment]
@Ataurr Thanks. I did that. It kind of works but I need to switch columns (content) by default, like this:
`<div class="row">
    <div class="col-md-4 col-md-push-4">
        <div class="alert alert-danger">B</div>
    </div>
    <div class="col-md-4 col-md-pull-4 col-sm-6">
        <div class="alert alert-info">A</div>
    </div>
    <div class="col-md-4 col-sm-6">
        <div class="alert alert-info">C</div>
    </div>
</div>`

Where I can do that? I could not find anything in row shortcode..

Thanks.

**Comment by Ataurr** [comment]
You have to customize column shortcode with bootstrap Column ordering

http://getbootstrap.com/css/#grid-column-ordering

**Comment by mintaras** [comment]
Thanks. I told client to switch content manually. I was asking because it seems this feature works mobile-first only.
