### ISSUE TITLE
Cant stop the backup

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2663]
There is no way to stop the backup once it has been initiated.  
I created backup schedule few days ago and today went to create quick content backup to pack a demo but the schedule activated and now it is spinning for more than 30min. I have no way of stopping it , there are no errors and I cant create content backup until this is finished.  Tried to kill the schedule and reload page and or server but nothing helps. Once I go in backups it is autoinnitiated and I can forget about  doing anything else. 

![8k8q_e7psmcn9dlqfrpkag](https://user-images.githubusercontent.com/2340172/27331573-5bbfbf00-55be-11e7-9b79-f25ec913def2.png)

there need to be a way to stop the script and do the task we need.

**Comment by danyj** [comment]
crazy , I had to delete all   fw:backup DB tables to stop this.  There should be a button to cancel current task

**Comment by andreiglingeanu** [comment]
Refer to https://github.com/ThemeFuse/Unyson/issues/2671#issuecomment-339240504
