### ISSUE TITLE
Is there any way to speed up demo installs?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2664]
Demo installs are very useful but our demo install is by far **the slowest** compared to ALL theme providers. 
I am making video tutorials and had timed the demo of **56MB** to run for **11 minutes**.  This is not ok. I know that the process is complicated but so is with any other theme . Enfold, Avada , betheme and everyone else run the full demo content install under 1min  with larger sites , zips and all this on same server. Please see what you can do.

**Comment by thednp** [comment]
One of my suggestions was to replace post images with grey dummy images, **one** per post type (assuming each post type uses different width X height). Thy said they'll look into it. 

This would drastically reduce size, speed up installation, and you don't have to hustle with copyrighted images.

**Comment by danyj** [comment]
I separately timed the steps , 

```
Plugins install : 42sec
From database export to archive ( backup )  : 43sec
Downloading increments of 32MB 3MB per step : 60sec ( crazy! it takes 4sec via browser ) 
Unzipping archive : 7sec
Files & DB restore: 38sec
Images restore ( 180 ) : 6m 28sec 
```

**that is 9m 38s**  


> One of my suggestions was to replace post images with grey dummy images

I used all Unsplash images so no issues with CP and most other providers either blur or use free images , but never the less have MUCH larger demos than the one I tested and are 90% faster.

**Comment by thednp** [comment]
This means they're not using a traditional import script, they might do an SQL update.

**Comment by danyj** [comment]
http://take.ms/D96Yh   avada 27 sec

Enfold kills everyone , not even full 4sec  http://take.ms/s4p70

**Comment by thednp** [comment]
That's SQL right there.

**Comment by danyj** [comment]
I know , none of them are doing backup or half of what Unyson does to secure the site but I still think that we could use some improvement like Download increments should be used only if server is slow, images restore seems like it needs most improvement.

**Comment by thednp** [comment]
How much would it take to import same with Wordpress Importer? I think it might be same as with the Unyson backup feature.

**Comment by danyj** [comment]
I found something else just now , 

I have 5 custom image sizes set 
than WP has + 3 , large, medium , thumbnail
and Woo adds another 3 

So extra 6 images sizes are created x 180 images ,  adds extra 3min do sizes restore

**Comment by thednp** [comment]
you don't use any custom image resize?

**Comment by danyj** [comment]
> you don't use any custom image resize?

what do you mean?

**Comment by thednp** [comment]
Something like aquaresize?

**Comment by danyj** [comment]
no I use add_image_size

**Comment by danyj** [comment]
@GheorgheP  Dug bit deeper and came back to this 
https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/30#issuecomment-253008320

and used 

     fw:ext:backups:add-restore-task:image-sizes-restore

filter to disable images sizes restore, 

it speed up the demo install but we have another issue now ,  

image-sizes-remove   **only removes the image files,** never removing the image size reference in **DB** 

so if I disable the image sizes restore my get_image function will  find the image-size ref in DB and try to load image resulting in no image. 

If the DB image size ref would also be removed on image-sizes-remove than my get_image would not find the image size and would fall back to original image.

**Comment by thednp** [comment]
Interesting finding @danyj, I hope UNyson devs take a look at the matter and analyze all options.
