### ISSUE TITLE
Section's Custom Css Class

### ISSUE THREAD

**Issue by fuzzytake** [ThemeFuse/Unyson#2665]
Hi everyone,

I have got three 1/3-column section elements aligned horizontally and would like them to be closer each other to have a linear effect between "Text Box" > "Search Box" > "Text Box"

I don't want to edit the styles of the columns as this will break other layouts.

I would like to add a custom class for the 'section' that contains these columns and then alter the styles of these colums based on the section class. 

What code can I add to the Section's Custom Css Class to reach this goal? I imagine I should decrease the width in some way.

Many thanks

**Comment by danyj** [comment]
http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head

**Comment by fuzzytake** [comment]
Hi Danyi

thanks for the link. 

So you are suggesting I need to go through an additional step before I can fill the Section's Custom Css Class with some code?

This additional step would be to add some code to "config.php, options.php, static.php and view.php" Is that correct?

The example from your link looks like it is for customizing the color. Do you have any example for customizing what I need, e.g., the 1/3-column section elements?

Many thanks

**Comment by danyj** [comment]
the example is for dynamic css, if you just need additional class than override the shortcode and add a class in view.php

http://manual.unyson.io/en/latest/extension/shortcodes/#overwriting-shortcodes

**Comment by danyj** [comment]
if you are using a theme based on Unyson than override shortcode within child-theme if your theme provides one

**Comment by ill-ink** [comment]
I'm not proficient in php; I had a crack at editing the php files but I break my site as I don't know where to place the extra lines of code in each file. I really like the Unyson tool but it's unusable in it's current form
