### ISSUE TITLE
[feature] Let us import/export users on demo and backup

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2666]
Few of us had a talk and agreed that we need an option for users to be exported/imported with  backups. 
It should be off by default but we should be able to decide what to do with users DB. 

@GheorgheP  let us know what you think.

**Comment by warudin** [comment]
Would be great to have this, per example to migrate an installation from one domain to another.

**Comment by warudin** [comment]
Seems like the users are even available in the export, but are not being restored. So I guess we'll mainly need an option for when we're restoring/importing the backup.

**Comment by andreiglingeanu** [comment]
Yes, you are right. [`users` and `usermeta`](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/f46f93c867c1ec2eb52f3084b2243a2b35414cfa/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L399-L402) tables are indeed manually skipped from the restore process.

Could any of you try to empty out that array and see if the users get imported properly?

That is definitely not something everyone will want so that won't be a default for sure, maybe a hook for configuring skipped tables in the import/export.

**Comment by warudin** [comment]
Sorry for the delay. I've had a moment to try this out today and indeed: the users are being imported when this array is empty. The tables are being overwritten completely, so any existing users are being removed.

I guess it would be a nice option to be able to import the user- and usermeta-table, but I get the problems with this. On the other hand, the user details are in the backup anyhow. Nonetheless this is very good to know, so thanks for this workaround, @andreiglingeanu!

**Comment by andreiglingeanu** [comment]
That sounds awesome and it looks like a nice opportunity for helping Unyson back with a pull request :)

**Comment by danyj** [comment]
Guys I'm completely lost , what changed where is it and what was done. Trying to pick up peaces but see no commits.

**Comment by warudin** [comment]
Nothing has changed, but now we know that it's possible to export and import the users en users-meta table with the Backup-function in Unyson. This can be done by clearing the $skip_tables array in [this file](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/f46f93c867c1ec2eb52f3084b2243a2b35414cfa/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L399-L402).

**Comment by danyj** [comment]
@warudin  clearing how , there is no filter?

**Comment by warudin** [comment]
At the moment by editing the file itself, that's why @andreiglingeanu was asking for a pull request with a better solution.

**Comment by danyj** [comment]
ok , got it , up to speed now :)
