### ISSUE TITLE
Add tracking code in form builder

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2667]
Hi, I’ve setup multiple forms on the theme through unyson’s “form” builder. However, there doesn’t seem to be a way to add conversion tracking snippet from AdWords as well as adding analytics events to the forms. Do you know if the form in unyson is able to do this, or is there a way to add a third party form into the unyson editor that will allow us to add these tracking codes on submit.

Thanks

**Comment by andronic90** [comment]
Hi, you are free to use a third-party plugin that offer the tracking on submit, or you can do this with javascript, it depends on what you need to do.

you can use redirect to a thank you page with custom code and Message after form submit or another solution.
