### ISSUE TITLE
Show / Hide an option if a function exists

### ISSUE THREAD

**Issue by guydumais** [ThemeFuse/Unyson#2669]
In **Theme Settings Options** Page, is it possible to show an option only if a function exists? For example, I'd like to show some options only if BuddyPress is installed. Is there any FILTER or HOOK? If so, how can I achieve this?

Here's the lazy way to quickly explain what I want to do:

```
if ( function_exists( 'bp_is_active' ) ) {
    $options = array(
        'option_id' => array(
            'type' => 'text'
            ....
        )
    );
}
```
Again, thanks in advance for your fast response time Buddies 🥇

**Comment by danyj** [comment]
I did this in theme/options/settings.php
https://github.com/ThemeFuse/Scratch-Theme/blob/6665e525a060741f7f78908af03e61c4d974851e/scratch-parent/framework-customizations/theme/options/settings.php

```
$thz_bb_tab 	= array();
if ( class_exists( 'bbPress' ) || class_exists( 'BuddyPress' )  ) {
	$thz_bb_tab = fw()->theme->get_options( 'bb_tab' );
}
```
bb_tab.php   is standalone with set of options for BB wrapped in a tab

and than in the settings.php I call

`$thz_bb_tab,
`

**Comment by guydumais** [comment]
Thanks again @danyj 🥇
