### ISSUE TITLE
[QUESTION] - when do we have the vertical options page

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#267]
As described <a href="http://themeforest.net/forums/thread/meet-unyson-the-free-drag-drop-wordpress-framework/141818?page=12&message_id=1198341#1198341">here</a>

**Comment by moldcraft** [comment]
It's already implemented. Look at the changelog [v2.1.23](https://github.com/ThemeFuse/Unyson/releases/tag/v2.1.23)

**Comment by thednp** [comment]
Thank you :)
