### ISSUE TITLE
Question about custom taxonomy options.

### ISSUE THREAD

**Issue by nltm** [ThemeFuse/Unyson#2672]
I created an option for custom taxonomy

<pre>$options = array(
  'select-type' => array(
    'label' => __( 'Select type', $theme_text_domain ),
    'type' => 'select',
    'value' => 'select',
    'desc' => __( '...', $theme_text_domain ),
    'help' => '',
    'choices' => array(
        'select' => __( 'Select', $theme_text_domain ),
        'image-picker' => __( 'Image picker', $theme_text_domain ),
        'color-picker' => __( 'Color picker', $theme_text_domain ),
    )
  )
);</pre>
then I used `fw_get_db_term_option` to get the value. The question is: how can I get "Select"/"Image picker"/"Color picker" instead of  `select/image-picker/color-picker`.
Any help would be appreciated. Thanks.

**Comment by ViorelEremia** [comment]
If you have not found the answer yet write here and we will find a solution.
