### ISSUE TITLE
Set datetime picker minDate

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2673]
I guess this is not really an issue, but I wanted to run it by you guys anyways.

I'm currently making something that involves events. An event has a start datetime. An event can also have a 'program'. This is an addable box with 2 options: title (type: text) and time (type: datetime picker).

Is it possible to set the minDate of the 'program' datetime picker with the value of the start datetime (even before a post is saved)? I'm thinking it would roughly work like the title template of an addable box, where you choose an option to use as the title.

Is this already possible? Or should it be?

**Comment by ViorelEremia** [comment]
if you have not found the answer yet write here and we will find a solution

**Comment by noesteijver** [comment]
I haven't found a way to do this yet. If this would become a feature, I would certainly use it!

-Kevin
