### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by LaraKroeker** [ThemeFuse/Unyson#2674]
Is it possible to create a form from the unyson framework that sends to multiple email addresses based on the answer on the drop down?  OR do I need to use a different form?

Lara

**Comment by LaraKroeker** [comment]
There is a list of 10 email addresses and I want them to go to different people based on the city they choose.
<img width="694" alt="screen shot 2017-06-23 at 9 50 53 am" src="https://user-images.githubusercontent.com/29662970/27492370-d9e4e246-57fa-11e7-8b5d-2755f1b628f6.png">

**Comment by ViorelEremia** [comment]
No, you can't you must rewrite option type mailer.
