### ISSUE TITLE
Addable-box with php function

### ISSUE THREAD

**Issue by Jlomaka** [ThemeFuse/Unyson#2675]
I have such an interesting question, in Addable Box there is such line fw:option-type:addable-box:control:click as I understood so that with its help you can access the event by clicking on the icon that you previously created, so the question At me in that I have here such line it has 2 parameters in an array 
`
'box-controls' => array( 
'create-post-link' => '<small class="dashicons dashicons-admin-links" title="CREATE"></small>',
'delete-post-link' => '<small class="dashicons dashicons-editor-unlink" title="DELETE"></small>',
),
`
and I want that at pushing on certain from them the php function of a current box was fulfilled and passed some values.
That is, when we click on CREATE, we call the function `post_build_new($sh_name,$sol_name)`, сode part of the function

`function post_build_new($sh_name,$sol_name){
    $file_name = $sh_name;
    $file_title = $sol_name;
    $file_base = get_template_directory();
    $page = fopen ("$file_base/page-$file_name.php", "w+");`

That is, from the written it can be understood that when you click on the icon we have to transmit a multiple value of THIS block and pass to the function which then immediately after the transfer will be launched.
On your FAQ could dig up such information. But I can not understand some values.

`
$elements.on('fw:option-type:addable-box:control:click', function(e, data){
			
			if (data.controlId != 'clone') {
				return;
			}
			
			var $name		= $elements.find('.fw-option-type-hidden').attr('name');
			var $button   	= $elements.find('.fw-option-boxes-add-button');
			var $increment 	= parseInt($button.attr('data-increment'));
			var $clonedBox 	= data.box.$box.closest('.fw-option-box').clone(true, true);
			var $prefix		= $($clonedBox).attr('data-name-prefix');
			var $newprefix  = $name + '['+ $increment +']';
			
			$($clonedBox).find(':input').each(function() {
				this.name = this.name.replace($prefix,$newprefix);
			});
			
			$clonedBox.addClass('fw-animation-zoom-in');
			data.box.$box.closest('.fw-option-boxes').append($clonedBox);
	
			setTimeout(function(){
				$clonedBox.removeClass('fw-animation-zoom-in');
				$button.attr('data-increment', $increment + 1);
			}, 300);
	
	});
`
I can not understand that we have a controller through which we pass in order to catch the event and how this event understands to which block it belongs. And what does $elements ?

**Comment by ViorelEremia** [comment]
If you did not solve it please reopen it
