### ISSUE TITLE
Vertical options page with submenus question

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#268]
I am trying to figure out how to add submenus/subtabs to my options page and couldn't figure it out, maybe I am missing something. I always get tabs and not submenus. I am working on your scratch theme parent. Please help.

**Comment by moldcraft** [comment]
https://trello.com/c/HxmZZYIp/53-theme-settings-vertical

Check the last comment

**Comment by thednp** [comment]
Thanks.
