### ISSUE TITLE
fw <title> element won't work since a few days

### ISSUE THREAD

**Issue by gstipps** [ThemeFuse/Unyson#2680]
Dear community,
i am not an expert and i am not sure whether it is an issue of unyson or my theme (woffice.io). So i write to both....
A few days ago, after i updated the theme and some Plugins, the <title> element does't work anymore. I placed some content (always TITLE BOX followed by TEXT BOX), but the style, produced by the theme disappeared. Just a bigger font but no style. Sourcecode says class=heading, style=H2. All correct but it doesn't look like it should/like it did.
Could it be a new conflict between fw and theme? Or is it maybe a "newbie/greenhorn" thing?
Greetings,
Bobby
i.e. [https://www.grundschul.tips/zeugnisse/](https://www.grundschul.tips/zeugnisse/)
website status is draft. i am working on it...
![screenshot_20170629-004510](https://user-images.githubusercontent.com/29762058/27663806-63aecf60-5c64-11e7-9303-06deacf257c3.jpg)

**Comment by 2Fwebd** [comment]
Hello, 

That's not from Unyson. 

It's from the last Woffice update, we made a lot of changes on the design. I'm replaying to your email in the next  hour 👍 

Thanks for your patience! 

Kind regards

François
