### ISSUE TITLE
Issues with Mobile version of Child Core theme

### ISSUE THREAD

**Issue by penhktemp** [ThemeFuse/Unyson#2681]
Hi, ThemeFuse/Unyson team. I am using your Child Core theme, but I am having issues with the mobile version. When I open the menu, the categories or pages just bleed into the descriptions. Can you help me fix this? I have attached an image for your reference.

(https://user-images.githubusercontent.com/29773042/27681749-c6b5c634-5cf2-11e7-9fae-dae10d7bdc5b.png)

**Comment by andronic90** [comment]
Please write to the support team: http://support.themefuse.com/hc/en-us/requests/new
