### ISSUE TITLE
Page not visible after updating Unyson

### ISSUE THREAD

**Issue by Danielbeat** [ThemeFuse/Unyson#2682]
Hello, I have a serious problem, my site is not seen, only the blue background of the page appears. This has happened after updating the Unyson plugin.

Theme: Unicum
Web: http://wprc.compuarte.net.mx

Any solution, please?

**Comment by danyj** [comment]
contact theme developer , the preloader is on top of the site , this is theme issue.

**Comment by Danielbeat** [comment]
Ok, thanks!
