### ISSUE TITLE
Backup restore stop suddently

### ISSUE THREAD

**Issue by antoniomangiacapra** [ThemeFuse/Unyson#2685]
Hello there,

I am using unyson backup extension on many sites but from a while it doesn't work on one specific site anymore.

I have not any problem when I save a new backup, but when I restore it, the restore is suddently stopped. It seems not to be very consistent: sometime it stops at "unzip archive", sometime at "database restore" and sometime at "files restore". Anyway in every case, if I check the content, just nothing happened.

I've attached the log file, also if I cannot see any relevant error. If there is any way I can provide more details, please let me know.

Thank you in advance.
Best Regards.

[debug.zip](https://github.com/ThemeFuse/Unyson/files/1122535/debug.zip)

**Comment by andreiglingeanu** [comment]
Could you provide the values from `php.ini` for that keys:

- `max_execution_time`
- `memory_limit`
- `max_input_time`

What kind of a host you are using?

I can't see anything useful in your 200k lines of logs, just a bunch of repeated errors that come from your code.
