### ISSUE TITLE
How can I reinitialize the multiselect option?

### ISSUE THREAD

**Issue by jdnimavat** [ThemeFuse/Unyson#2686]
I want to use multiselect field as widget form field, I have created filed by adding a class for input and enqueue multiselect script.

`<p>`
`    <label><?php _e( 'categories' ); ?> </label>`
`    <input type="text" data-options="<?php echo esc_attr($categories); ?>" name="<?php echo esc_attr( $this->get_field_name( 'categories_included' ) ); ?>"`
`	value="<?php echo esc_attr( $instance['categories_included'] ); ?>" class="fw-option-type-multi-select widefat" id="<?php esc_attr( $this->get_field_id( 'categories_included' ) ); ?>"/>`
`</p>`

It works fine and provide me multiselect in widget form but when I save it the value replaced by ids like 12/*/14/*/18 etc. and field become simple textbox.

So How can I reinitialize it and again change it to multiselect after save?

**Comment by jdnimavat** [comment]
Any one here? any solution to solve out this issue?

**Comment by ViorelEremia** [comment]
Use 
```
fwEvents.trigger('fw:options:init', {
	$elements: jQuery( '.fw-option-type-multi-select' )
});
```
