### ISSUE TITLE
There is an error after moving the site to a new hosting

### ISSUE THREAD

**Issue by Jlomaka** [ThemeFuse/Unyson#2687]
In view of the circumstances, I had to move the site from one hosting to another, I've done this before, but today there was such an error during the transfer 

`Class 'FW_Option_Storage_Type_Post_Meta' not found in /home/user/site.com.ua/www/wp-content/plugins/unyson/framework/helpers/fw-storage.php on line 100`

Has looked Google did not help anything .As I understood, an error is produced for searching the path through the directory, but I can not figure out where to dig what would solve this issue. Version Unyson 2.6.16

**Comment by ViorelEremia** [comment]
How you did what? with backup extension?
