### ISSUE TITLE
Installing Page Builder Crashes WP

### ISSUE THREAD

**Issue by justritedesign** [ThemeFuse/Unyson#269]
Unyson 2.1.25
I am trying to install the Page Builder part of Unyson and the problem is that when I do the whole site crashes. I get a page that is trying to load "http://www.justritedesign.com/jrp/wp-admin/admin.php?page=fw-extentions" ... The page is just white and then when I try to look at the site itself or log back in to WP all pages associated with WP are coming up plain white ... nothing else. This only happens when installing the Page Builder plugin.

I end up deleting the Unyson folder and I can then get back in. But it would seem that Page Builder is the problem as no other component causes the problem.

Any thoughts?

Michael Moyers
Just Rite Design

**Comment by moldcraft** [comment]
Hello Michael,
Can you look in apache error.log to see if there is any fatal error?

**Comment by justritedesign** [comment]
I should have mentioned that this is on a Microsoft Server. This may or not be helpful.

**Comment by moldcraft** [comment]
Ok, then look in Microsoft Server error log.

**Comment by justritedesign** [comment]
OK forgive my ignorance here. I have attained access to the Server log. I am unsure what to look for and not sure what to post here that may help. 
What do you need?

**Comment by danyj** [comment]
The error log bud

**Comment by justritedesign** [comment]
I'm too new to this. There are entries both GET and POST and I do not see any actual errors. But this is the last two entries. As I write this it seems more and more that it is not what you may need.
--------------------
GET /jrp/wp-admin/themes.php page=tgmpa-install-plugins&plugin=unyson&plugin_name=Unyson&plugin_source=repo&tgmpa-install=install-plugin&_wpnonce=76ac5f792a 80 - 64.83.205.134 Mozilla/5.0+(Windows+NT+6.1;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/40.0.2214.115+Safari/537.36 http://www.justritedesign.com/jrp/wp-admin/themes.php?page=tgmpa-install-plugins 200 0 0 22864 1161 9434
-------------------
POST /jrp/wp-admin/admin-ajax.php - 80 - 64.83.205.134 Mozilla/5.0+(Windows+NT+6.1;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/40.0.2214.115+Safari/537.36 http://www.justritedesign.com/jrp/wp-admin/themes.php?page=tgmpa-install-plugins&plugin=unyson&plugin_name=Unyson&plugin_source=repo&tgmpa-install=install-plugin&_wpnonce=76ac5f792a 200 0 0 516 1373 671

**Comment by moldcraft** [comment]
@justritedesign this seems like access log, not error log.

-----

Another problem may be file path limit on Windows. Our extensions are nested and full path of the file some times is long and may be bigger that path limit. Try to find the path limit on your server and try to increase it if it's too low.

**Comment by justritedesign** [comment]
Error Log Entry:

- System 
  - Provider 
   [ Name]  Zend Loader 
 
  - EventID 5 
   [ Qualifiers]  0 
 
   Level 2 
 
   Task 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 
   [ SystemTime]  2015-02-22T18:12:04.000000000Z 
 
   EventRecordID 747345 
 
   Channel Application 
 
   Computer RAPTOR16 
 
   Security 
 
- EventData 
   Unable to create file mapping 
   Access is denied.  
 
 
The description for Event ID 5 from source Zend Loader cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
If the event originated on another computer, the display information had to be saved with the event.
The following information was included with the event: 
Unable to create file mapping
Access is denied.

**Comment by moldcraft** [comment]
@justritedesign Sorry, I have no idea what that error means.

We haven't tested the framework on Microsoft Server (actually never used it, I thought it can't run PHP, only ASP.NET).

I can't tell you when we will test it on Microsoft Server (or if we will do it ever). Maybe you can find someone who is familiar with it and will figure out what's the problem.

**Comment by justritedesign** [comment]
Yes Microsoft servers run PHP ... OK many thanks for your input. I have moved everything to a Linux server and everything is running fine. A couple small ticks in the template it's tied into but I will work that out with them. 

Thanks again,
Michael Moyers
Just Rite Design
Just Rite Productions
