### ISSUE TITLE
Page Builder pages in Search Results

### ISSUE THREAD

**Issue by mlaw93** [ThemeFuse/Unyson#2690]
I am using woffice Theme which comes with Unyson.  I have noticed that if I use the page builder on a wiki page, then search for content that would be found on that wiki, that the results contain only the title of the page and now actual preview of the page contents.  Any ideas how to make the search results more meaningful?

**Comment by yura-x** [comment]
Have same issue. Did you resolve your problem?

**Comment by ViorelEremia** [comment]
Need to edit file search.php from theme it is responsible for that, you can use excerpt page to extract "meaningful" and featured image, but to extract something from builder content is a bike that I do not recommend, so add support excerpt for wiki and extract it in search.php or contact theme developer -
 this is their responsibility to do.

**Comment by yura-x** [comment]
Here is simple function to create an excerpt for page that was created with page builder:

```
function fw_get_excerpt_for_page_with_unyson_builder() {
	$excerpt = get_the_excerpt();
	if ( empty( $excerpt ) ) {

		$content = get_the_content();
		$content = strip_tags( str_replace( ']]>', ']]&gt;', apply_filters( 'the_content', get_the_content() ) ) );
		$excerpt = substr( $content, 0, 200) . ' [...]';
	}
	return $excerpt;
}
```

content-page.php:

```
<?php if ( is_search() ) : ?>
	<div class="entry-summary">
		<?php echo wp_kses_post( fw_get_excerpt_for_page_with_unyson_builder() ); ?>
	</div><!-- .entry-summary -->
<?php endif; ?>
```
