### ISSUE TITLE
Give section names of backend?

### ISSUE THREAD

**Issue by treashdox** [ThemeFuse/Unyson#2691]
Is it possible to give your own section names to be visible on the backend? So that in the session settings we have a section name field and after entering it is visible as in the attached image.

![layout_elements - section_name](https://user-images.githubusercontent.com/27485119/27948499-5164a9b4-62fa-11e7-9064-79ce7f5a0ef0.jpg)

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/2629

**Comment by treashdox** [comment]
Thanks a lot .. I just needed it and I could not find it :)
