### ISSUE TITLE
add xing link to team member social

### ISSUE THREAD

**Issue by jeanoz** [ThemeFuse/Unyson#2693]
Hi. Adding a g+ or linkedin link is easy but i need to add xing profiles as well. if i add the link in the team member module, it is not shown on the published website. Is there a way to add Xing with icon to that module?

![linkedin icon](https://user-images.githubusercontent.com/29978103/27956644-04656df8-631b-11e7-8f93-25295ee50e37.jpg)

**Comment by ViorelEremia** [comment]
By default, unyson doesn't have the option link; it is a theme issue, contact your theme developer.
