### ISSUE TITLE
Page Builder doesn't show up.

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#2694]
Hi!
Unyson and Page builder are activated but I could not find the Visual editor tab when edited the page. 
I selected the Page from Unyson -> Page builder
Test on Unyson & Twenty seventeen theme
There's no error from console. 

Any advises!

**Comment by andreiglingeanu** [comment]
Are you on the `master` version?

**Comment by duongancol** [comment]
yes, I downloaded from wp.org. 
I don't have the same problem on my site. It's my client site so I guess there're something wrong in hosting configuration. 
Should I send you the account?

**Comment by duongancol** [comment]
OMG, I found the solution. He disabled the visual editor from Profile account. 
Just unselect that option
