### ISSUE TITLE
Map change marker on own?

### ISSUE THREAD

**Issue by treashdox** [ThemeFuse/Unyson#2695]
Hi,

is it possible to add an option to upload graphics to change the marker on the map itself?

**Comment by Dias25** [comment]
does not work your decision

**Comment by andronic90** [comment]
We use this in The Core theme and works fine.

**Comment by Dias25** [comment]
there can i add this code?
i add field in theme/framework-customizations/extensions/shortcodes/shortcodes/map/option.php 
then your code in theme/framework-customizations/extensions/shortcodes/shortcodes/map/views/view.php
but this does not work

**Comment by andronic90** [comment]
put fw_print($atts); in view.php and see the structure and inspect where is the problem.

you need to put this code: https://screencast.com/t/mg92s3y1Jm in: "/framework-customizations/extensions/shortcodes/shortcodes/map/static/js/scripts.js"

first you need to copy this file from Unyson to rewrite the file

**Comment by Dias25** [comment]
i copy scripts.js from unyson in "/framework-customizations/extensions/shortcodes/shortcodes/map/static/js/scripts.js
then change code but it dosnt work, why? it works if change original file

**Comment by andronic90** [comment]
try to include in static.php in the parent folder:

```
$shortcodes = fw_ext( 'shortcodes' );
$shortcode  = $shortcodes->get_shortcode( 'map' );

wp_enqueue_script(
	'fw-shortcode-map-script',
	$shortcode->locate_URI( '/static/js/scripts.js' ),
	array( 'jquery', 'underscore' ),
	fw()->manifest->get_version(),
	true
);
```

**Comment by Dias25** [comment]
Yeah now it works, thanks you!!!

**Comment by andronic90** [comment]
OK
