### ISSUE TITLE
fw-backend-option-descriptor wrap killing options JS

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2697]
@andreiglingeanu  `fw-backend-option-descriptor `is being wrapped around every  form element now thus killing option types that were reading some values from parent or child elements via JS like 

`$(el).parent();`

**Comment by danyj** [comment]
or 

`    $element.next('.some-class')`

**Comment by danyj** [comment]
sow now we must do 

   ` $element.parent().find('.some-class')`

or look for  fw-backend-option-descriptor


there should have been information about this before implementing  additional wraps for every input

**Comment by andreiglingeanu** [comment]
This is true, they were introduced for the reactivity thing and they are pretty necessary, sorry about not announcing about it. Are those `fw-backend-option-descriptor` divs such a big problem?

How many devs out there have custom option types and they depend on a certain HTML structure?

@GheorgheP Had to put a blog post about this feature but it was postponed for some reason.

**Comment by andreiglingeanu** [comment]
Contact form got affected by that to, [fixed](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/fbdd3c82ee67502c2b1cb3597993619786bb27c7) it.

**Comment by danyj** [comment]
> How many devs out there have custom option types and they depend on a certain HTML structure?

I say everyone who made an option type and includes a JS for it. 

I had few so far but in general there should have been info and instructions before implementation

**Comment by andreiglingeanu** [comment]
@danyj I do understand. What can we make now to improve the situation?

**Comment by danyj** [comment]
to be honest not sure but expect issues after this master release.

**Comment by andreiglingeanu** [comment]
It is what it is, let's hope for the best.
