### ISSUE TITLE
Custom class in <p>

### ISSUE THREAD

**Issue by Jengas** [ThemeFuse/Unyson#2702]
Hello! I have problem. I did for section and for image function "custom class" and "custom id" like this

`$custom_class = ( isset( $atts['customclass'] ) && $atts['customclass'] ) ? '' . $atts['customclass'] .'': '';
$custom_id = ( isset( $atts['customid'] ) && $atts['customid'] ) ? '' . $atts['customid'] .'': '';`

`<section<?php echo $custom_id ?> class="fw-main-row <?php echo $custom_class ?><?php echo esc_attr($section_extra_classes) ?>" <?php echo $section_style; ?> <?php echo $bg_video_data_attr; ?>>`

But i want to do this for Text block. But in textblock i can see only `<?php echo do_shortcode( $atts['text'] ); ?>`

What to do? I have tryed to display it but in end it gives me like this:
`<p class="123" id="test">
<p>Hello World!</p>
</p>
`
Help me please

**Comment by ViorelEremia** [comment]
Hi Jengas,
I do not understand you why do you want to do that. If I understand correctly you want to give a custom class for tags p from do_shortcode to do that i think is a wrong way you can only do something like that .fw-text-inner p { proprrety css  } or you can add div higher with your class. 
The function do_shortcode has a lot of filters one of them is the_content that also has some filtres 
`add_filter( 'the_content', 'wptexturize'                       );
add_filter( 'the_content', 'convert_smilies',               20 );
add_filter( 'the_content', 'wpautop'                           );
add_filter( 'the_content', 'shortcode_unautop'                 );
add_filter( 'the_content', 'prepend_attachment'                );
add_filter( 'the_content', 'wp_make_content_images_responsive' );`
As you see hook "wpautop" add this p https://codex.wordpress.org/Function_Reference/wpautop
Be very careful I do NOT recommend this method.
