### ISSUE TITLE
[bug] fw_current_url()  adding double domain to url

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2703]
Go in Unyson any extension that has settings, like breadcrumbs, builder seo etc, click on save button , 

seems like there is extra trailing slash in form or something 

breadcrumbs link 

`http://192.168.0.21/Development/WordPress/wp-admin/admin.php?page=fw-extensions&sub-page=extension&extension=breadcrumbs`

when saved goes to 

`http://192.168.0.21/Development/WordPress/Development/WordPress/wp-admin/admin.php?page=fw-extensions&sub-page=extension&extension=breadcrumbs`

**Comment by danyj** [comment]
checked stable version and it is ok , the bug is in current master

**Comment by danyj** [comment]
@GheorgheP   

https://github.com/ThemeFuse/Unyson/commit/daf4ef9bf337b8295bafbdb06c753fd57aa8f6db#diff-1a10d08376d32331dbdc651256766d37

**Comment by antoniomangiacapra** [comment]
Is it assumed that this has been fixed in the version 2.6.16? Because I can reproduce it right now with Unyson 2.7.6 and WP 4.8.1.

Also some users of our theme have suddenly faced the issue.

**Comment by danyj** [comment]
it has been broken since the last change https://github.com/ThemeFuse/Unyson/commit/daf4ef9bf337b8295bafbdb06c753fd57aa8f6db

**Comment by GheorgheP** [comment]
@andreiglingeanu @danyj @ViorelEremia
Please test out it too:
- Simple install: `http://mysite.com`
- SSL: `https://mysite.com`
- Subdomain: `http://my.site.com`
- Subdirectory: `http://site.com/my`
- Subdomain subdirectory: `http://my.site.com/wp`
- Local installation: `http://localhost/mysite` || `http://127.0.0.1/mysite`

**Comment by danyj** [comment]
tested works

**Comment by 2Fwebd** [comment]
@GheorgheP any plan to release that? Not sure why it's only happening since a few weeks but we're getting a lot of tickets about that.
