### ISSUE TITLE
Customize builtin option types output

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#2704]
Hi,
is possible to customize the output of the builtin option types?
If yes, how?
Thank's!

**Comment by GheorgheP** [comment]
I depends.

If you just want to apply some css styling, then just add the `class` attribute in the option `attrs` and apply the styles on option depending on that class: http://manual.unyson.io/en/latest/options/introduction.html#content

But in case you want to modify the view or functionality, then you cannot do this directly on option.

You have to create yor own option type extending the desired one and make the changes on your option type: http://manual.unyson.io/en/latest/options/create-option-type.html#content
