### ISSUE TITLE
[Feature Request] Preview of content on Backend

### ISSUE THREAD

**Issue by oddtober** [ThemeFuse/Unyson#2707]
I love what you guys have created and I am almost using it almost exclusively for my customers.
Something that bugged me, on the backend, when you create a long page, is that you do not see a preview of what your content is.

When we use a "Special Heading", it shows "Special Heading". When we use a "Text Block", it says "Text Block". Will be good if it shows the preview so it is easier to manage when you are managing the content.

Hope that will come soon! Thank you!

**Comment by oddtober** [comment]
Just like to check if there anyone managing this?

**Comment by danyj** [comment]
yes there is but you are asking for visual page builder in backend which will not be added as far as I know.
