### ISSUE TITLE
[Suggestion] Grouping options are not useful

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#271]
The grouping options are pretty much useless without some attributes to control itself and the inner-options.

OK here's what we can do:
* let us build our own typography like option types just by using the <code>group</code> and without overrides or custom developed field types. What if I want to combine a slider field with a text and a multiselect select without writing code myself?
* The <code>group</code> should be able to control it's options wrappers attributes with some sort of template system.

How can I create my own GROUP container OR where should I start?

**Comment by moldcraft** [comment]
> The grouping options are pretty much useless without some attributes

You can add attributes to a group

```php
array(
    'type' => 'group',
    'attr' => array( 'class' => 'whatever', 'data-test' => 'ok' ),
    'options' => array(...),
)
```

> let us build our own typography like option types just by using the group and without overrides or custom developed field types.

Option-types comes with some extra styles or scripts and have some logic in their class (in render and get_value_from_input methods)

> What if I want to combine a slider field with a text and a multiselect select without writing code myself?

You can use [option-type `multi`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi) to group any number of options within a single option value.

```php
'option-id' => array(
    'type'  => 'multi',
    'inner-options' => array(
        'option-1' => array( 'type' => 'slider' ),
        'option-2' => array( 'type' => 'text' ),
        'option-2' => array( 'type' => 'multi-select' ),
    )
)
```

> The group should be able to control its options wrappers attributes with some sort of template system.

More details and examples please.

> How can I create my own GROUP container OR where should I start?

Tabs, Boxes and Groups are hardcoded and you cannot create new container elements. You can only [create your own option types](http://manual.unyson.io/en/latest/options/create-option-type.html#content) *(if the option-type `multi` does not fit your needs)*.

**Comment by thednp** [comment]
Man I didn't see that, I would give you that. Still the CSS is badly done, no proper cascade styling.

<blockquote>
<blockquote>
<p>The group should be able to control its options wrappers attributes with some sort of template system.</p>
</blockquote><p>More details and examples please.</p>
</blockquote>
I mean control the inner-options wrapping, especially their classes and HTML structure.
Example:

<pre>
'attr' => array(
        'strip-classes' => array('class1','class2'), // option to skip adding certain classes to inner options
        'options-wrapper' => '<div class="proper framework classes or user classes">' // this to control the last all inner-options wrapper
        'option-wrapper-option-1' => '<div class="proper framework classes or user classes">' // this to control the option-1 wrapper
         'option-wrapper-option-2' => '<div class="proper framework classes or user classes">' // this to control the option-2 wrapper
)
</pre>

Here some examples, I may be talking crazy or unrealistic, that's because I don't know all the Unyson code yet, but thanks anyway, your reply may be good enough.

**Comment by thednp** [comment]
PS: I closed this by mistake, we need to talk about this :)

**Comment by thednp** [comment]
Please disregard this, I will make own custom option types to manage what I need and where groups + multis cannot manage.
