### ISSUE TITLE
Informations errase

### ISSUE THREAD

**Issue by tib07** [ThemeFuse/Unyson#2711]
Hello folks

I'm currently having a problem as I'm working on a client website that uses Unyson theme.

As I have difficulty to customize a page with the visual builder, I made a page both with html and Unyson shortcodes.

The problem is that after a time, not doing anything in particular, all the information I saved in the Unyson shortcodes (through the Unyson interface) disappear...

I really don't know why...

Could you help plz ?

Here is the link : [http://innership.com/front-2/](http://innership.com/front-2/)

**Comment by andronic90** [comment]
Have you the last plugin and extension version?

You can try to disable auto update in WordPress
