### ISSUE TITLE
Sliders extension script buggy with latest master

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2712]
In edit slider screen 

![screenshot_1](https://user-images.githubusercontent.com/2340172/28492435-33055bec-6f04-11e7-80d4-7d23a857a439.jpg)

**Comment by andreiglingeanu** [comment]
Not happens with Scratch theme. Can you please debug your JS more closely? Maybe you are listening for some slides-specific events in your theme?

Indeed, from that stack trace, [it looks like](https://github.com/ThemeFuse/Unyson-PopulationMethods-Extension/blob/346718509fe8396e3aa4067dea6ffd039c9683dc/extensions/population-method-custom/includes/slides/static/js/slides.js#L65-L71) the code is failing when trying to compile the JS template. It should be from your JS.

**Comment by danyj** [comment]
here , this is the bug 
https://github.com/ThemeFuse/Unyson/issues/1877

**Comment by danyj** [comment]
in slider extension add this option


```
'btns' => array(
    'type' => 'addable-popup',
    'value' => array(),
    'label' => __('Add button', 'fw'),
    'desc'  => __('Add slide button.', 'fw'),
    'template' => '{{ if(b){ console.log(b); } else { console.log(false); } }}',
    'popup-title' => __('Slide button settings', 'fw'),
    'size' => 'large',
    'add-button-text' => __('Add', 'fw'),
    'sortable' => true,
    'limit' => 2,
    'popup-options' => array(
        'b' => array(
            'type' => 'text',
            'label' => false,
        ),
    ),
)

```

**Comment by danyj** [comment]
this was the fix for it 
https://github.com/ThemeFuse/Unyson/commit/3ccee198eb3e979ec4c262da7eaf57fae91a91e8

**Comment by danyj** [comment]
@andreiglingeanu  error is easy triggered if you just do this as popup template 

`'template' => '{{ console.log(b)}}',`

so no json or anything http://prntscr.com/g0hjn5

**Comment by danyj** [comment]
@andreiglingeanu @GheorgheP  can we please get this looked at.

**Comment by andreiglingeanu** [comment]
Is that happening only inside slider extension? I can't reproduce that in Theme Settings.

**Comment by danyj** [comment]
only in slider , see the old post https://github.com/ThemeFuse/Unyson/issues/1877 , not theme settings , 
you must have changed something that brought the bug back

**Comment by danyj** [comment]
@moldcraft  fixed it here , https://github.com/ThemeFuse/Unyson/issues/1877#issuecomment-239222028

but since the reactive something has changed

**Comment by danyj** [comment]
this is the changed that brought it back 
https://github.com/ThemeFuse/Unyson/commit/e2e4c4d9c9bfac659436d96c5947dcebba328c79

**Comment by andreiglingeanu** [comment]
I [see](https://cl.ly/lpuo) no issue here, really. Are you on latest master?

**Comment by danyj** [comment]
I dont know what you adding , here same thing with the core theme 

`framework-customizations\extensions\media\extensions\slider\extensions\easy-carousel\options
`in custom.php   there are 2   options 



```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}
$options = array(
	'link' => array(
		'type'  => 'text',
		'label' => __( 'Link', 'the-core' ),
		'value' => '',
		'desc'  => __( 'Enter the link', 'the-core' )
	),
	
	'btns' => array(
		'type' => 'addable-popup',
		'value' => array(),
		'label' => __('Add button', 'fw'),
		'desc'  => __('Add slide button.', 'fw'),
		'template' => '{{ if(b){ console.log(b);} }}',
		'popup-title' => __('Slide button settings', 'fw'),
		'size' => 'large',
		'add-button-text' => __('Add', 'fw'),
		'sortable' => true,
		'limit' => 2,
		'popup-options' => array(
			'b' => array(
				'type' => 'text',
				'label' => false,
			),
		),
	)
);
```



http://prntscr.com/g3k8i5

**Comment by danyj** [comment]
And same bug with scratch theme bx-slider
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/media/extensions/slider/extensions/bx-slider/options/custom.php



```
<?php if (!defined('FW')) die('Forbidden');
$options = array(
	'subtitle' => array(
		'type' => 'text',
		'label' => __('Subtitle', 'unyson'),
		'value' => '',
		'desc' => __( 'Choose a subtitle for your slide.', 'unyson' )
	),
	'btns' => array(
		'type' => 'addable-popup',
		'value' => array(),
		'label' => __('Add button', 'fw'),
		'desc'  => __('Add slide button.', 'fw'),
		'template' => '{{ if(b){ console.log(b);} }}',
		'popup-title' => __('Slide button settings', 'fw'),
		'size' => 'large',
		'add-button-text' => __('Add', 'fw'),
		'sortable' => true,
		'limit' => 2,
		'popup-options' => array(
			'b' => array(
				'type' => 'text',
				'label' => false,
			),
		),
	)
);

```
http://prntscr.com/g3ket4

**Comment by danyj** [comment]
@andreiglingeanu  can you please take another look , I confirmed this in scratch, core and any unyson based theme with latest master. please use the above code to see the issue.

**Comment by andreiglingeanu** [comment]
Again, it works with your above code. Please check that you are on latest versions everywhere.
