### ISSUE TITLE
I can't found Page Builder extension

### ISSUE THREAD

**Issue by anvar9991** [ThemeFuse/Unyson#2713]
Hi, 
I've installed Unyson plugin. I need to install Page Builder extension. I can't found where to do that.
please help

![unyson](https://user-images.githubusercontent.com/25155566/28497115-0cdf5bf4-6f98-11e7-8e12-7a38b7736800.JPG)

**Comment by NiloySarker** [comment]
Did you click this button?  <img src="https://image.prntscr.com/image/nUe65FBMR7_TftSQhcNuug.png" />

**Comment by anvar9991** [comment]
sorry, but  this button is not there at all. see attachment
[image: Встроенное изображение 1]

2017-07-24 13:28 GMT+05:00 Niloy Sarker <notifications@github.com>:

**Comment by andronic90** [comment]
I think you need to activate default WP theme and if this extension appear with default theme the problem is in the theme and you need to contact the theme author, maybe is not compatible with the theme and disabled this extension.

**Comment by anvar9991** [comment]
thank you for the response.
yes, I've contacted theme author. they solve the problem.
thank you again for your time

2017-07-26 13:11 GMT+05:00 Andronic Vlad <notifications@github.com>:

**Comment by andronic90** [comment]
OK
