### ISSUE TITLE
I have fed up with Unyson plugin

### ISSUE THREAD

**Issue by prasanth8889** [ThemeFuse/Unyson#2714]
Unyson plugin, i have installed via WP and even uploaded via FTP  many times from last day , but after installed the plugin, i couldn't access my word press dashboard, what i have to do, i could't replace the plugin becuase my design concept is depend upon the plugin, so please help me someone from this f***g issue.

Thanks in advance.

**Comment by andronic90** [comment]
Have you put the debug to true? What error give? What theme do you using, this problem appear and with default WP theme?
