### ISSUE TITLE
Mail Chimp Integration with Page Builder Forms

### ISSUE THREAD

**Issue by ElizPB** [ThemeFuse/Unyson#2717]
Hello,

I have been using Unyson to create my Wordpress website. I love the drag and drop page builder. I have especially loved the customization I can do with the "contact form" in the drag and drop page builder. 

Is there any way to connect those forms to an external CRM system, specifically MailChimp, so that each sign-up is imported into a list and initiates a series of automated emails? To initiate those emails is the main reason I have a sign-up form on my page.

I have done this process with other plugins, but I don't see how to do it with Unyson forms.

If this is possible, would you please let me know,
Thanks!

**Comment by ViorelEremia** [comment]
Hi, you can do this only programmatically something like 
`// Hook then message is sent successfully.
add_filter( 'fw:ext:contact-forms:sent', function( $entry_data ) {
	// The message is sent.
	// $entry_data contain all that you need, email filds etc
	//fw_print( $entry_data );
	// do stuff whith api compain services mailchimp api here https://github.com/drewm/mailchimp-api
	
	die();
} );`
add to functions.php

**Comment by ElizPB** [comment]
Okay, thanks. Where do I put that code?

**Comment by ViorelEremia** [comment]
You can put it in functions.php
