### ISSUE TITLE
Group options container cant be hidden

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2718]
Group container as  described is mostly used to 

"Group options into a wrapper div. Has no design. Usually used to show/hide a group of options from javascript"

http://manual.unyson.io/en/latest/options/introduction.html#containers

but if we do that and even add a class to our group container the class is pinned to inner container wich leaves this 

http://prntscr.com/g1119k
http://prntscr.com/g111sq

try  this in theme/options/posts/page.php

	'some_group' => array(
		'type' => 'group',
            'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
		'options' => array(
			// add some options
		),
	),

you can see here https://github.com/ThemeFuse/Unyson/blob/0cf758c23c9e2e97e6035aae4b752afa2bfcc47c/framework/core/components/backend.php#L677

that only box gets additional data

**Comment by ViorelEremia** [comment]
Hi, Dan
I try to understand you but I can't.
What I only understand is the line
`'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),`  will not work  http://manual.unyson.io/en/latest/options/introduction.html#Restrictions

Can you explain in other words

**Comment by danyj** [comment]
@ViorelEremia I think I was detailed enough with code , and image blocks

in simple terms the class should be added to top container not inner container if we would to use it to show/hide the container via JS

add the class and see where the output is 



the container class 
```
<div class="parent SHOULD BE HERE">
 <div class="inner BUT IS HERE">
 ...
</div>
</div>
```

**Comment by goran468** [comment]
Seems to be after last patch tabs not working in cpt-options.
For example, adding this to /theme/options/page.php:

```

$options = array(
         'general' => array(
		'title'   => __( 'General', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			'general-box' => array(
				'title'   => __( 'General Settings', 'unyson' ),
				'type'    => 'box',
				'options' => array(
					'logo'    => array(
						'label' => __( 'Logo', 'unyson' ),
						'desc'  => __( 'Write your website logo name', 'unyson' ),
						'type'  => 'text',
						'value' => get_bloginfo( 'name' )
					),
					'favicon' => array(
						'label' => __( 'Favicon', 'unyson' ),
						'desc'  => __( 'Upload a favicon image', 'unyson' ),
						'type'  => 'upload'
					)
				)
			),
		)
	)
);
```

not working at all.

If I insert just simple type => 'box' without tabs - all works.

Problem occurred today after update 2.7.9

**Comment by danyj** [comment]
@goran468  this issue is here since July bud ,  please join testing so that things like this do not happened. 
This should have been properly tested https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/362
