### ISSUE TITLE
Undefined option type flash msg in front and admin

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#272]
I created new option type for custom logo with this tut 
https://github.com/ThemeFuse/Unyson-Documentation/blob/master/options/create-option-type.rst
and the option works fine on an install I made few weeks ago and did on time updates with new framework versions. 
Everything is same as in the tut except the option name. 
Now I tested the theme on clean install to make sure there are no errors on first time install. 
Theme installed fine no issues. But when I installed Unyson I am getting 

Undefined option type: thzlogo  in admin and in frontend
http://screencast.com/t/4C3Kx4eRkQR

front
http://screencast.com/t/rGH3kvYw4t2E

strange thing is that the option still works 
http://screencast.com/t/UawgtgyW

I checked the files few times , made sure the option name is correct but I cant find the issue.

**Comment by danyj** [comment]
And this is what I got on first save 
http://screencast.com/t/p2wpFKFAe

AFter saving first time and refreshing the admin the msg is gone.

**Comment by moldcraft** [comment]
This happens when option type is access before it is defined. *In your case (I am pretty sure) it happens [here](https://github.com/ThemeFuse/Unyson/blob/89ff5792a35c86feafba1010f4eff8e67944ce91/framework/helpers/database.php#L38-L41)*

How do you include the option? On which action?

**Comment by danyj** [comment]
The option is located in theme settings and nowhere else

framework-customizations\theme\options\settings.php  is calling the tab logo


	'logo' => array(
		'title'   => __( 'Logo', 'fw' ),
		'type'    => 'tab',
		'options' => array(
			'sub_tab_1' => array(
				'title'   => __( 'Logo options', 'fw' ),
				'type'    => 'box',
				'options' => array(
					fw()->theme->get_options( 'logo' ),
				),
			),
		),
	),


logo.php  has the option


$options = array(
    'logo_image' => array(
        'type' => 'thzlogo',
        'value' => '',
        'label' => __('Logo', 'fw'),
        'help' => __('You can use pixels ( px ) or percentage ( % ). If no operator is added px is default.', 'fw')
    ),

**Comment by danyj** [comment]
you see now this #266 would come in handy in order to see the bug again
now since I saved it I must delete everything from DB in order to see the bug and work on it.

**Comment by moldcraft** [comment]
Show me please the code that does this

```php
require_once dirname(__FILE__) . '/.../class-fw-option-type-....php';
```

**Comment by danyj** [comment]
it is your upload  option with additional 3 buttons
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/upload/class-fw-option-type-upload.php

I just renamed upload to thzlogo and respected the case 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/upload/class-fw-option-type-upload.php#L3

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/upload/class-fw-option-type-upload.php#L11

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/upload/class-fw-option-type-upload.php#L207

and added buttons here

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/upload/views/images-only.php#L27

**Comment by moldcraft** [comment]
Please show me the code that includes the option-type class.

```php
require_once dirname(__FILE__) . '/.../class-fw-option-type-....php';
```

I has nothing with option-type structure/changes. Just when do you include it, on which action?

**Comment by danyj** [comment]
on fw_init
as described in the tut 
this is option-types.php  located inside 

inc/includes

	/** @internal */
	function _action_theme_include_custom_option_types() {
		if (is_admin()) {
			require_once dirname(__FILE__) . '/option-types/thzlogo/class-fw-option-type-thzlogo.php';
		}
	}
	add_action('fw_init', '_action_theme_include_custom_option_types');

**Comment by moldcraft** [comment]
It seems like some `fw_get_db_settings_option()` is called before `'fw_init'` action.
Most likely this is not in a template (because templates are loaded later).
So you should find that `fw_get_db_settings_option()` and if it's possible call/use it later.
Also try to change priority for `add_action()` below to be executed earlier (in case the function also is called inside a `fw_init` action).

```php
add_action('fw_init', '_action_theme_include_custom_option_types', 9);
```

If the described above will not (help) be possible, I will make/find an action that will be called as early as possible just for `FW_Option_Type::register('...');` to work (and update the docs).

**Comment by danyj** [comment]
add_action('fw_init', '_action_theme_include_custom_option_types',9);
does not make any difference , msg is still there .  Now note that this is only on first time install beofore you save the theme options for the first time. 

thing is the fw_get_db_settings_option  is not called in admin anywhere and I am not even trying to get the logo option from DB. my logo.php tab is just setting up the option. So I do not see where I should make any changes.

**Comment by danyj** [comment]
wait , 

    add_action('fw_init', '_action_theme_include_custom_option_types',9);

did remove it , I did save the file after change. sorry.  
So yes the execution order was important in this one.

**Comment by moldcraft** [comment]
Good. Then the problem is fixed?

> and I am not even trying to get the logo option from DB

I doesn't matter which option you try to get with `fw_get_db_settings_option()`. If not values are in the database, all settings options are loaded, and for each is called the `_get_value_from_input()` method.

**Comment by danyj** [comment]
yes , is fixed with the order of execution. ok Il check all my options and make sure the option outputs come only after unyson is "alive" 

fw_init is what we should look for or something later?

**Comment by moldcraft** [comment]
> ok Il check all my options and make sure the option outputs come only after unyson is "alive"



> fw_init is what we should look for or something later?

`'fw_init'` [is triggered](https://github.com/ThemeFuse/Unyson/blob/master/framework/bootstrap.php#L95) right after the entire framework is loaded. It fires inside [`after_setup_theme`](https://github.com/ThemeFuse/Unyson/blob/master/framework/bootstrap.php#L14) (you can find it in [all wp actions list](http://codex.wordpress.org/Plugin_API/Action_Reference))

**Comment by danyj** [comment]
ok , will check further, or rather check first if framework options exist in DB and than let everything else fire. 
small update to this 
    add_action('fw_init', '_action_theme_include_custom_option_types',9);
on docs would come in handy to others.

**Comment by danyj** [comment]
hm , exactly , now that I think about it , can you create an even that will tell us that settings exist in DB ?

**Comment by danyj** [comment]
Look here 
I do this to check if unyson is loaded 

	function thz_fw_loaded(){
		
		if(function_exists('fw_get_db_settings_option')){
			
			return true;
		}
	}
and than I use that function before any of the options is used. 
Instead of me checking for the class , it would be better to check if options are in DB.

**Comment by moldcraft** [comment]
> add_action('fw_init', '_action_theme_include_custom_option_types',9);

> http://codex.wordpress.org/Function_Reference/register_post_type
> It will not work if called before 'init'

So better

```php
add_action('init', '_action_theme_include_custom_option_types');
```

**Comment by danyj** [comment]
init   still display the msg

**Comment by moldcraft** [comment]
Oops, sorry. I read it `_action_theme_include_custom_post_types`. Put back `fw_init`.

**Comment by danyj** [comment]
I did. Maybe a custom action specific for custom options would the best thing after all.

**Comment by thednp** [comment]
I also use my own option type and I figured something. I am not getting any "unidentified option type" error, but accessing my option type value in the front-end is not possible directly when used inside a multi-picker. I think this is the way the picker works, I found no resource on how to access variable values in front-end though.

**Comment by danyj** [comment]
@thednp , did you do clean install ,   no fw options should be in DB, this happens on first time theme install before you have saved options.

**Comment by danyj** [comment]
@thednp print this one in frotend or inc/static.php

    fw_get_db_settings_option()
    
    fw_get_db_settings_option('option_name')

**Comment by moldcraft** [comment]
> Maybe a custom action specific for custom options would be the best thing after all.

I updated [the docs](http://manual.unyson.io/en/latest/options/create-option-type.html#content) and just added that `9` priority. Better to keep things simple.

> hm , exactly , now that I think about it , can you create an even that will tell us that settings exist in DB ?
>
> fw_init just tells us that unyson is active , but it would come in handy to know that user has already saved the options.
>
> Look here 
> I do this to check if unyson is loaded
> 
> ```php
> function thz_fw_loaded(){
> 
>     if(function_exists('fw_get_db_settings_option')){
> 
>         return true;
>     }
> }
> ```
> and than I use that function before any of the options is used. 
> Instead of me checking for the function, it would be better to check if options are in DB.

I think the `function_exists()` approach is fine for this case.

----

But in case you really want to check if settings are saved in db or not:

```php
if (FW_WP_Option::get('fw_theme_settings_options:' . fw()->theme->manifest->get_id())) {
    // saved
} else {
    // not saved
}
```

**Comment by danyj** [comment]
@moldcraft  thank you!
