### ISSUE TITLE
Can't add a sidebar to the Tag pages

### ISSUE THREAD

**Issue by steve-themefuse** [ThemeFuse/Unyson#2721]
The option to a add a sidebar to a tag page does not work: https://static.md/978391e559749bd831761661a6ce79b8.png. It takes the sidebar from the archive page instead.

**Comment by GheorgheP** [comment]
I just tried and it work properly.
Did you try with the Unyson scratch theme? May be the problem is from the theme you use.

**Comment by steve-themefuse** [comment]
Tried witch scratch theme as well, does not work if you add a sidebar to a tag page. Only works if you add a sidebar to the archive page, so the same sidebar is used for the tag pages as well.

**Comment by GheorgheP** [comment]
Sorry, you were right. I tested with sidebar for all tags not for specific one.
Fixed in this pull request: https://github.com/ThemeFuse/Unyson-Sidebars-Extension/pull/16
