### ISSUE TITLE
Can I use the select label instead of the select value?

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2722]
I'm using the select on a multilingual website. I've translated all the labels. But when I display the selected option, it displays the value (not the label).

I guess it would be good to have a choice in using the value or the label.

Or is there another way to properly make this translatable?

**Comment by GheorgheP** [comment]
It can be done simple, you just need to associate the value with the text, and the same text use for label too:

```php
function my_options() {
	return array(
		'test-1' => __( 'Test 1', 'fw' ),
		'test-2' => __( 'Test 2', 'fw' ),
		'test-3' => __( 'Test 3', 'fw' ),
		'test-4' => __( 'Test 4', 'fw' ),
		'test-5' => __( 'Test 5', 'fw' ),
		'test-6' => __( 'Test 6', 'fw' ),
	);
}
```

Then use it to generat the select:

```php
$options = array(
	'test-options' => array(
		'type'    => 'select',
		'value'   => 'test-1',
		'label'   => __( 'Select', 'fw' ),
		'desc'    => __( 'Select an option', 'fw' ),
		'choices' => my_options(),
	)
);
```

Then extract the value text:

```php
$text = fw_akg( fw_get_db_post_option( get_the_ID(), 'test-options' ), my_options() );
```
