### ISSUE TITLE
Youtube javascript CDN Problem

### ISSUE THREAD

**Issue by Skyepose** [ThemeFuse/Unyson#2725]
We really hope the youtube CDN link can be optimize because of the youtube CDN javascript file loading, the this framework can hardly be used in Asia countries, may be you can consider make it as local js file. 
<img width="1440" alt="screen shot 2017-07-23 at 4 50 15 pm" src="https://user-images.githubusercontent.com/9482245/28815921-8cdd5632-76d5-11e7-829c-609c3c36130f.png">
<img width="1440" alt="screen shot 2017-07-23 at 7 12 40 pm" src="https://user-images.githubusercontent.com/9482245/28815926-90158842-76d5-11e7-8215-7ec4df97d2cd.png">

**Comment by danyj** [comment]
that is normal Youtube API behavior and has nothing to do with the framework.

**Comment by andreiglingeanu** [comment]
And I'm pretty sure there is no way to make the script local, YouTube will never allow that.

**Comment by ViorelEremia** [comment]
As I see it is loaded only from background.js when section has background video. To rewrite file location it is not recommended, but if for you is very very important you can do that just rewrite(http://manual.unyson.io/en/latest/extension/shortcodes/index.html) shortcode section or others shortcodes who use this file.
So you need to rewrite some files from plugin just copy them from location in your folder(folowing the folders arhitecture) customizations 
1. unyson/framework/extensions/shortcodes/shortcodes/section/config.php
2. unyson/framework/extensions/shortcodes/shortcodes/section/static/js/background.js

Now you need to replace from file config.php code:
`wp_enqueue_script(
		'fw-shortcode-section-formstone-background',
		$shortcodes_extension->get_uri( '/shortcodes/section/static/js/background.js' ),
		array( 'jquery' ),
		false,
		true
	);`

with something like that: 

'// Register your own iframe_api.js
	wp_register_script( 'fw-shortcode-section-formstone-background', "{$js_uri}/background.js", array( 'jquery' ), false, true );
	wp_localize_script( 'fw-shortcode-section-formstone-background', 'BACKGROUND', array( 'iframeJsUri' => "{$js_uri}/iframe_api.js" ) );
	wp_enqueue_script( 'fw-shortcode-section-formstone-background' );'

And in background.js you need to find `'<script src="//www.youtube.com/iframe_api"></script>'`
and repalce it with `'<script src="' + BACKGROUND.iframeJsUri + '"></script>'`

And that's all :) but this is not all, wordpress has own url triggered in wp-custom-header.js or somthing like what it is used for youtube shortcode inn tinymce.

**Comment by andreiglingeanu** [comment]
Yes, section shortcode has the `background.js` script loaded, which comes from [Formstone](https://github.com/Formstone/Formstone/tree/0.8.x) library. Rewriting some of the `section`'s files is a legit fix for that. One more thing to do is to remove [`video`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.27/shortcodes/section/options.php#L22-L26) option and [coresponding](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.27/shortcodes/section/views/view.php#L15-L24) PHP logic of it.
