### ISSUE TITLE
Page preview with builder not effective unless saved

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#273]
Seems like page preview when using page builder is not effective at all unless we publish/update the page. 
Default editor without page builder works fine.

**Comment by gustavarrhenius** [comment]
Is there any progress on this bug? Would be really nice if the Preview button worked :)

**Comment by GheorgheP** [comment]
Hi, 

Sorry for a such big delay, we are working on this.

**Comment by danyj** [comment]
np ,   in meantime some of the previews were okis, the bug appears now in textblock shortcode 
http://prntscr.com/6hhooe
