### ISSUE TITLE
How to create a paragraph in the team member module 

### ISSUE THREAD

**Issue by kloudis** [ThemeFuse/Unyson#2730]
When I input copy into the team member module, it's just wall to wall running copy. 

How can I create paragraphs to break up the copy?

WP Zoom says:
Unfortunately, about break up the copy on the About page, it's beyond our support.
CSS code cannot do that so as HTML tags. We tried, none of that works.
It seems Unyson Builder stripped HTML tags from the Team Members module.

Please help, thank you!
Kristin
![screen shot 2017-08-02 at 11 17 59 am](https://user-images.githubusercontent.com/30665294/28885796-5cbf96b4-7774-11e7-8a72-d80fb374a3d3.png)

**Comment by danyj** [comment]
nothing is being escaped in shortcode , they pulling your leg, 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/team-member/views/view.php#L19

option is textarea so is probabbly escaped on  save , 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/team-member/options.php#L26

if you override it to be wp-editor instead it will print all editor html

**Comment by kloudis** [comment]
I’m a beginner at this and don’t understand all of this. Can you please help me with the correct CSS and where I should enter it?

Thank you-
Kristin

**Comment by danyj** [comment]
did you try `<br />  `  in textarea like 


```
loremipsum 
<br />
loremipsum 
```

works fine 

http://prntscr.com/g3kivn

http://prntscr.com/g3kj53

**Comment by kloudis** [comment]
ok great, that works great, thank you!

now how do I create a space after the paragraph?

**Comment by danyj** [comment]
http://lmgtfy.com/?q=html+space

https://www.w3schools.com/html/html_entities.asp

**Comment by kloudis** [comment]
Thanks for this info, much appreciated!
Kristin
