### ISSUE TITLE
wp-editor tools select z-index low for options popup

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2732]
Latest master , see this 

http://take.ms/3b5sK

**Comment by danyj** [comment]
select z-index is 65535

http://prntscr.com/g4h95m

and our modal is  100003

http://prntscr.com/g4h9px

**Comment by danyj** [comment]
for time being untill the fix is out add this in   any backend css file 


```
.mce-menu-align{
	z-index:2000000!important;
}
```

it can be your option type css , admin or any CSS file that runs when builder is on

**Comment by kevinviner** [comment]
Tried this and didn't seem to work. Can you give a specific CSS file to try? Sorry if this is a naive question.

**Comment by danyj** [comment]
at the end of this one 
https://github.com/ThemeFuse/Unyson/blob/master/framework/static/css/backend-options.css#L1297

than do hard refresh

http://prntscr.com/g5tzkw

**Comment by kevinviner** [comment]
THANK YOU!

**Comment by ivandotv** [comment]
I haven't noticed this bug until recently. 
It wasn't there before?
@danyj Thanks for the fix

**Comment by danyj** [comment]
> It wasn't there before?

came with 4.8.1,

**Comment by arielzusya** [comment]
@danyj - Thanks for the post. That fixed it for the "Paragraph" dropdown for me. Looks like the same issue exists for other dropdowns (like the font color). Any suggestions on a workaround for that until the issue is resolved? Thanks!

**Comment by danyj** [comment]
@arielzusya 

```

.mce-menu-align,.mce-floatpanel{ 
    z-index:2000000!important; 
}
```

**Comment by danyj** [comment]
this one fixes both 


```
.mce-container{
 z-index:2000000!important; 
}
```


they are all outside of the body 

![screenshot_8](https://user-images.githubusercontent.com/2340172/29454244-b9e41da2-840c-11e7-95ec-77e51c9a9faa.jpg)

**Comment by danyj** [comment]
this one is more suitable, 


```
.mce-container.mce-panel.mce-menu,
.mce-container.mce-panel.mce-popover{
 z-index:2000000!important; 
}
```


![screenshot_8](https://user-images.githubusercontent.com/2340172/29455957-a721c4ec-8413-11e7-9afe-b0b9f591a942.jpg)

**Comment by arielzusya** [comment]
That did it. Thank you!

**Comment by mtmcgreg** [comment]
do I just put this:

.mce-container.mce-panel.mce-menu,
.mce-container.mce-panel.mce-popover{
 z-index:2000000!important; 
}

in the custom CSS file for my theme?
