### ISSUE TITLE
Can't Change Font Sizes

### ISSUE THREAD

**Issue by kevinviner** [ThemeFuse/Unyson#2733]
When I'm in the page builder, I can't change the font size or heading style. The arrow simply moves up/down and the dropdown doesn't appear. Any thoughts? I've tried uninstalling and reinstalling Unyson, as well as wordpress.

**Comment by danyj** [comment]
@andreiglingeanu  @ViorelEremia 

https://github.com/ThemeFuse/Unyson/issues/2732
