### ISSUE TITLE
Serious problem with VPB - options appear behind editor window/ are not working - screencast

### ISSUE THREAD

**Issue by andrewberman** [ThemeFuse/Unyson#2735]
Hi. Since the 4.8.1 update (I think), popup options in the Visual Page Builder are appearing BEHIND the main window (e.g., shortcodes, advanced hyperlink, etc.) If I close the main editor, the options window appears briefly behind it and then closes. Also, the drop down menus do not work (e.g., to set the text as H1, H2, etc) in that they don't reveal the menu when clicked.

See the screencast:
http://take.ms/KGldC

Please help!

Thanks

**Comment by kevinviner** [comment]
#2732 #2733
