### ISSUE TITLE
'Unyson Shortcodes' overwrites other TinyMCE custom buttons.

### ISSUE THREAD

**Issue by AlexandruDoda** [ThemeFuse/Unyson#2736]
When enabling the Unyson Shortcodes extension, my custom plugin's TinyMCE buttons get removed from the editor. See attached below:

**Code**

<img width="704" alt="screen shot 2017-08-07 at 9 16 22 am" src="https://user-images.githubusercontent.com/8274669/29014324-1ec9551c-7b51-11e7-8b13-b2276df23bd7.png">

**Without Unyson Shortcodes**

<img width="847" alt="screen shot 2017-08-07 at 9 16 57 am" src="https://user-images.githubusercontent.com/8274669/29014347-41d8c3f8-7b51-11e7-8aee-b0a22d6f2de9.png">

**With Unyson Shortcodes**

<img width="780" alt="screen shot 2017-08-07 at 9 17 53 am" src="https://user-images.githubusercontent.com/8274669/29014368-5e1f2eda-7b51-11e7-82d5-1b5482a587db.png">

As you can see my button is no longer there. What can I do to make sure they both work simultaneously and Unyson doesn't overwrite mine?

**Comment by ViorelEremia** [comment]
Hi Alexandru,
You can drop your code here so I can see what's happening.

**Comment by AlexandruDoda** [comment]
Hey @ViorelEremia 

The only code related to the functionality I am describing is the one in the screenshot above. I have also [pasted it here](https://pastebin.com/YRJsny6D) for convenience.

Thank you!
Alexandru Doda

**Comment by AlexandruDoda** [comment]
Hey @ViorelEremia, any news on this?

**Comment by ViorelEremia** [comment]
My code:
`add_action( 'after_setup_theme', 'mythemeslug_theme_setup' );

if ( ! function_exists( 'mythemeslug_theme_setup' ) ) {
	function mythemeslug_theme_setup() {
		/********* Registers an editor stylesheet for the theme ***********/
		add_action( 'admin_init', 'mythemeslug_theme_add_editor_styles' );
		/********* TinyMCE Buttons ***********/
		add_action( 'init', 'mythemeslug_buttons' );
	}
}

/********* Registers an editor stylesheet for the theme ***********/
if ( ! function_exists( 'mythemeslug_theme_add_editor_styles' ) ) {
	function mythemeslug_theme_add_editor_styles() {
		add_editor_style( 'custom-editor-style.css' );
	}
}

/********* TinyMCE Buttons ***********/
if ( ! function_exists( 'mythemeslug_buttons' ) ) {
	function mythemeslug_buttons() {
		if ( ! current_user_can( 'edit_posts' ) && ! current_user_can( 'edit_pages' ) ) {
			return;
		}

		if ( get_user_option( 'rich_editing' ) !== 'true' ) {
			return;
		}

		add_filter( 'mce_external_plugins', 'mythemeslug_add_buttons' );
		add_filter( 'mce_buttons', 'mythemeslug_register_buttons' );
	}
}

if ( ! function_exists( 'mythemeslug_add_buttons' ) ) {
	function mythemeslug_add_buttons( $plugin_array ) {
		$plugin_array['columns'] = get_template_directory_uri() . '/ae-editor.js';

		return $plugin_array;
	}
}

if ( ! function_exists( 'mythemeslug_register_buttons' ) ) {
	function mythemeslug_register_buttons( $buttons ) {
		array_push( $buttons, 'columns' );

		return $buttons;
	}
}
`
ae-editor.js code:
`(function() {
	tinymce.PluginManager.add( 'columns', function( editor, url ) {

		editor.addButton( 'columns', {
			title: 'My test button',
			type: 'menubutton',
			icon: 'wp_code',
			menu: [
				{
					text: 'Menu item I',
					value: 'Text from menu item I',
					onclick: function() {
						editor.insertContent(this.value());
					}
				},
				{
					text: 'Menu item II',
					value: 'Text from menu item II',
					onclick: function() {
						editor.insertContent(this.value());
					},
					menu: [
						{
							text: 'First submenu item',
							value: 'Text from sub sub menu',
							onclick: function(e) {
								e.stopPropagation();
								editor.insertContent(this.value());
							}
						},
						{
							text: 'Second submenu item',
							value: 'Text from sub sub menu',
							onclick: function(e) {
								e.stopPropagation();
								editor.insertContent(this.value());
							}
						}
					]
				},
				{
					text: 'Menu item III',
					value: 'Text from menu item III',
					onclick: function() {
						editor.insertContent(this.value());
					}
				}
			]
		});
		/*editor.addCommand('columns', function() {
			var selected_text = editor.selection.getContent({
				'format': 'html'
			});
			if ( selected_text.length === 0 ) {
				alert( 'Please select some text.' );
				return;
			}
			var open_column = '<div class="column">';
			var close_column = '</div>';
			var return_text = '';
			return_text = open_column + selected_text + close_column;
			editor.execCommand('mceReplaceContent', false, return_text);
			return;
		});*/

	});
})();`
For me it works perfectly in both cases in default editor tinymce and modal text block.

**Comment by AlexandruDoda** [comment]
So this is with the "Shortcodes" module enabled:
![image](https://user-images.githubusercontent.com/8274669/31443793-6a766726-ae68-11e7-9bb3-c9660850d670.png)

And this is with the "Shortcodes" module disabled. Notice that the button gets overwritten by Unyson's Shortcodes functionality (when enabled):
![image](https://user-images.githubusercontent.com/8274669/31443864-897f1e10-ae68-11e7-9d92-7f06145a6b73.png)

They should both be visible even if Shortcodes is enabled.

**Comment by AlexandruDoda** [comment]
Okay I think it may be a filter priority issue or something. Tested with your code theme-side and it works. Trying to debug and apply it plugin-side to my framework.

**Comment by AlexandruDoda** [comment]
All right, all good, thanks @ViorelEremia - apparently it was because of the $typenow thing.

**Comment by ViorelEremia** [comment]
I have encountered a similar problem with plugin easyReservations I'll take a look on Monday
