### ISSUE TITLE
Input required attribute not working in options modal

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#274]
I need a required option attribute that will not let user save the options unless the option  has been filled out. 
I am using short-text or text, but in general is there and attribute we can add to make user fill out the option before save?

**Comment by moldcraft** [comment]
Try

```php
array(
    'type' => 'text',
    'attr' => array('required' => 'required'),
)
```

**Comment by danyj** [comment]
It does show required 
http://screencast.com/t/FkB6KD0F
but saving still goes trough without warning.

**Comment by moldcraft** [comment]
You did not specified that options are inside modal.
At the moment the required attribute won't work in modal. I will take a look to see if it's possible to make it work.

**Comment by levan1993** [comment]
Hi,
I found a solution for required attributes. You need a hidden submit input inside form.
when you click save button than trigger click on hidden submit input > event.preventDefault() > call your ajax handler and finally return false. I tested this solution and it works fine!

**Comment by moldcraft** [comment]
@levan1993 Thank you for the suggestion. Yes, for the question with required inputs inside options modal this is the solution.
But I am thinking a way to auto-generate a unique id without bothering the user to enter manually one for each section/column.

**Comment by levan1993** [comment]
Do you want to generate unique id while building page or on post save ?

**Comment by moldcraft** [comment]
@levan1993 I don't know yet. I will let you know when I will decide.

**Comment by levan1993** [comment]
Do you need these ids for CSS stuff?

**Comment by moldcraft** [comment]
Ops, I thought this is https://github.com/ThemeFuse/Unyson/issues/275

The solution for this issue is https://github.com/ThemeFuse/Unyson/issues/274#issuecomment-77163019 I will fix it soon.

**Comment by moldcraft** [comment]
I can't solve [this](http://sourcebox.io/e134ae47d67ce87e48c7e224556d9ec4/html)

**Comment by danyj** [comment]
Hack but works
http://jsfiddle.net/r8haxLyj/

**Comment by danyj** [comment]
This combo might help also for multiple required 
http://stackoverflow.com/a/8409472/594423

**Comment by moldcraft** [comment]
The user will not understand why modal is not closing when he clicks the Save button. The warning popup must be displayed.

**Comment by moldcraft** [comment]
P.S. Is this feature still needed if [section id](https://github.com/ThemeFuse/Unyson/issues/275) will be generated automatically?

**Comment by danyj** [comment]
adding a class to required on click if it is empty can help there, like here 
http://joomlatemplates.youjoomla.info/eximium/index.php/pages/user-pages/login-form

like this 
http://jsfiddle.net/r8haxLyj/1/

**Comment by danyj** [comment]
well no it is not needed for me if I have the ID but someone else might want to use required in popup.

**Comment by moldcraft** [comment]
> well no it is not needed for me if I have the ID but someone else might want to use required in popup.

If will be needed I will reopen this. *(There are other important issues in pending)*

**Comment by levan1993** [comment]
My solution shows browser native validation ( shows native bubbles ), for example :
if input is required it will show : please fill out this field,
if input is url and it'not valid it will show : Please enter a URL. 
And so on.

I will modify your fw.OptionsModal and upload it
