### ISSUE TITLE
Database helper issues

### ISSUE THREAD

**Issue by Benajax** [ThemeFuse/Unyson#2742]
I have a site ( hosted on wordpress 4.8 and php 7.1 ) and uses the unyson plugin which works fine
on my dev server but the database helpers shuch as fw_get_db_settings_option are only returning default
values and they don't seem to be retrieving the values from the mysql database.

Any suggestions will be helpful

BenAjax

**Comment by andronic90** [comment]
Have you try on PHP 7.0?

**Comment by Benajax** [comment]
Tried php 7 no luck - only getting back default values

**Comment by danyj** [comment]
what is the setup in the option ,  how are you retrieving the data?  code please

**Comment by ViorelEremia** [comment]
I can't reproduce this, give us more details or you can create some temporary credentials and drop here viorel[at]themefuse.com

**Comment by Benajax** [comment]
Hi ViorelEremia,


I will send you  ftp credentials for you to look at the issue


Thanks


Ben


________________________________

**Comment by Benajax** [comment]
Hi ViorelEremia, 

I have dropped some credentials in your inbox as requested.

Thanks
Ben
