### ISSUE TITLE
Unyson demo content install fails

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2743]
Hello!

I faced a problem with Unyson backups extension: 

i have WordPress **Multi-Site** installation and i made few demos using Unyson Backups extension.

When i test demo content installation on a **single site** (using Tools > Demo content install screen) i get following error (on a database restore step) each time

![2017-08-08_18-58-07](https://user-images.githubusercontent.com/12991525/29081594-a3d580ee-7c6b-11e7-800a-22d578ad09ed.png)

Demo content file size is above 83Mb, i'm working on localhost PHP7 x64, mySQL 5.7 x64

Does it mean that i can't install demo data on single site installation if it was created on multi-site installation? Is there a way to fix this problem? Please help as soon as possible

**Comment by WPJobs** [comment]
Hey guys, do you still provide support for Unyson Framework? If not, will you fix possible bugs in the future or you stopped on working on it? Please answer at least this question

**Comment by andronic90** [comment]
Hi,

You can try to view what is in this line in JSON.

By the way, have you remove the revisions and another data that is unused (I use Better delete revisions plugin).

**Comment by WPJobs** [comment]
Hello again!

I have tried to remove revisions, but this did not help. I noticed that this problem happens only when i try to install demo content from website ID = 1, another demo content from websites from my multiste installation works fine. I tried on different hostings and locally, the problem is same: Unknown column 'order' in field list, table _fwbk_term_taxonomy

Also i tried some of plugins from WordPress repo, and all of them have problems with cloning website ID = 1, what can i do, could you help please? This problem makes me crazy

**Comment by WPJobs** [comment]
I have found an error https://github.com/ThemeFuse/Unyson/issues/2872
