### ISSUE TITLE
Need help with the form on Unyson exporting to CSV/Google Sheets on "Submit"

### ISSUE THREAD

**Issue by tplaza9** [ThemeFuse/Unyson#2744]
I want to be able to have the contact information I'm gathering from the form and have it populate to a google sheet document so I can run an export every month and upload to our email distribution service. Is there any way to customize this? Currently have the forms going to a gmail in the account.

**Comment by andronic90** [comment]
You can export the gmail contacts in this case

**Comment by andronic90** [comment]
As far as I know the Contact Form from Unyson doesn't store emails in database and this is normal practice, because contact form only send the data to the email.

You can make a custom functions called with ajax on form submit and use this data like you want.

**Comment by ViorelEremia** [comment]
Here is a solution  https://github.com/ThemeFuse/Unyson/issues/2717
