### ISSUE TITLE
custom naming of elements

### ISSUE THREAD

**Issue by Toggenburger** [ThemeFuse/Unyson#2745]
It would be a VERY welcome addition, if you could name the content elements. The possibility to name the sections is not enough, by far 😉

Thx, regards

**Comment by danyj** [comment]
More details please. What do you mean by naming?

**Comment by Toggenburger** [comment]
Having multiple content elements, all with the same name, is not very helpful to keep them apart.
see screenshot, I hope this makes it clear?

thx

<img width="1190" alt="screen shot 2017-08-09 at 13 44 49" src="https://user-images.githubusercontent.com/8643433/29120066-0d942a38-7d09-11e7-893e-3fa06cdef87e.png">

**Comment by danyj** [comment]
Browse posts and manual please 

https://github.com/ThemeFuse/Unyson/issues/2629
http://manual.unyson.io/en/latest/extension/shortcodes/index.html?highlight=title_template#config-file

**Comment by andreiglingeanu** [comment]
Yeah, your use case should be covered by custom templates. Everything is doable from the theme's side.

Thanks @danyj

**Comment by Toggenburger** [comment]
Frankly said, you must be kidding! :-)
I have by now means the ability to change something that deep inside the codes. :-O
I would need a step by step solution how and where to do what.
As far as I can see, I am not the only one wishing for something like that, so why not include it out of the box?
It would be greatly appreciated if you could comply with my request.

**Comment by danyj** [comment]
No  we are not kidding. This is a framework , not ready to use theme so you need to get you hands dirty to get what you need or have your theme developer do it for you. 

And beside that how do you expect us to know what your options name would be and what you want to be displayed as a name?

**Comment by Toggenburger** [comment]
Just to make this clear, the possibility to name the sections has been done by the theme developer?

**Comment by danyj** [comment]
> by the theme developer

yes , devs are responsible for it
