### ISSUE TITLE
Icon box, change Icon colour

### ISSUE THREAD

**Issue by kharis-au** [ThemeFuse/Unyson#2747]
Hi,

I have 3 icon boxes on my site and I can't seem to find the option of changing the colour of the icons. Can somebody please let me know where to change this, and apologies in advance if it's something really easy and I've missed it. I just want to be able to change the icons from green to another colour.

![image](https://user-images.githubusercontent.com/11371945/29149292-9129c2b0-7db6-11e7-8f11-de7d44709332.png)

**Comment by ViorelEremia** [comment]
Hi, 
by default unyson does not have option to change color but you can but you can do what programmatically with custom css or you can overwrite shortcode see here how : http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes
