### ISSUE TITLE
Icon v2 refactoring and improvements

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#2748]
This is the issue for tracking the progress on improving the `icon-v2` option type experience.

### XDebug profiler data

[Here](https://send.firefox.com/download/7418e68219/#54mQBs5F6wH2bQuGOUntgg) is a XDebug profile data for [AJAX actions](https://github.com/ThemeFuse/Unyson/blob/d14c74c390d8f375b739c66ae4f2a894bbb56948/framework/includes/option-types/icon-v2/includes/class-fw-icon-v2-favorites.php#L11-L24) from `icon-v2`. They take quite some time and can be improved.

<img width="1340" alt="screen shot 2017-08-10 at 12 08 50 pm" src="https://user-images.githubusercontent.com/2979628/29163303-bbf7f5a8-7dc4-11e7-97e5-ba56ece4a5cd.png">

### Frontend modal

The time it takes to open a modal with a lot of icons rendered in a list is horrible. We need some kind of a virtual list for keeping this modal tiny. Try:

* [hyperlist](https://github.com/tbranyen/hyperlist)
* [virtual-list](https://github.com/sergi/virtual-list)

<hr>

_Other ideas still to come..._

**Comment by thednp** [comment]
You can also have a look at my [bootstrap.native](https://github.com/thednp/bootstrap.native) for tiny little things ;)
