### ISSUE TITLE
I don't see any extensions to activate

### ISSUE THREAD

**Issue by PatSchmid** [ThemeFuse/Unyson#2749]
Hello,

I'm on WP 4.7.5 and installed the Jevelin theme. For this theme Unyson Plugin is required. I installed this as well (downloaded the installation package and uploaded with ftp). After activation of the Plugin, I can see Unyson in the left menu. But the areas for "activated extensions" and "available extensions" are empty.

Any idea what is wrong with it?

**Comment by ViorelEremia** [comment]
Hi, 
please contact Jevelin theme support if they determine that the error is from unyson thhen you can re-open issue.
