### ISSUE TITLE
Do you provide support?

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2752]
Hello!

Do you provide support, and will you fix possible bugs in the future? It looks like you stopped working on Unyson, is it right?

**Comment by danyj** [comment]
how is this stopped working? 

https://github.com/ThemeFuse/Unyson/commits/master

it is vacation time , some devs will be back soon

**Comment by WPJobs** [comment]
Thanks @danyj, it really great that you still work on it :)
