### ISSUE TITLE
WordPress REST API - JSON "Rendered" Content Incorrect when Page Filtered by ID

### ISSUE THREAD

**Issue by stuajnht** [ThemeFuse/Unyson#2754]
## Summary
When using the WordPress REST API, the page content isn't generated correctly in the JSON response when filtered by a page ID, but is generated correctly when the full list of pages are requested.

## Versions
**WordPress**: 4.8+
**Unyson Plugin**: 2.6.16
**Components**: Page builder and WordPress REST API

### Steps to Reproduce

1. Create a new page, and using the page builder, add any shortcode to the page (e.g. a section). You can also customise the section to help it stand out more 
2. Browse to `<server>/wp-json/wp/v2/pages` and take note of the rendered content value
3. Browse to `<server>/wp-json/wp/v2/pages/<page_id>` and take note of the rendered content value

### Expected Results
The content should be identical for both requests - the generated page HTML.

### Actual Results
The list of pages content section generates the correct page HTML, while the filtered page only generates the `post_content` text (shown when the default editor is used in text view).

### JSON Responses
(Snipped for brevity)
#### `<server>/wp-json/wp/v2/pages`
```json
[
  {
    "id":4,
    "content":{
      "rendered":"<div class=\"fw-page-builder-content\"><section class=\"fw-main-row \" style=\"background-color:#000000;\" >\n\t<div class=\"fw-container\">\n\t\t\t<\/div>\n<\/section>\n<\/div>\n",
      "protected":false
    }
  }
]
```

#### `<server>/wp-json/wp/v2/pages/<page_id>`
```json
[
  {
    "id":4,
    "content":{
      "rendered":"<div class=\"fw-page-builder-content\">\n<p><!-- 1b18ac05135e34eedc0577096e29776f --><\/div>\n",
      "protected":false
    }
  }
]
```

## Additional Info
After searching the WordPress code for a while, this seems to be the line in WordPress core that generates the JSON rendered content: [https://github.com/WordPress/WordPress/blob/b140e8f5742c7eb82624d02e51e697409a160868/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1451](https://github.com/WordPress/WordPress/blob/b140e8f5742c7eb82624d02e51e697409a160868/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1451).

For testing, adding `die($post->post_content);` temporarily after the if statement so it becomes:
```php
if ( ! empty( $schema['properties']['content'] ) ) {
  $data['content'] = array(
    'raw'       => $post->post_content,
    /** This filter is documented in wp-includes/post-template.php */
    'rendered'  => post_password_required( $post ) ? '' : apply_filters( 'the_content', $post->post_content ),
    'protected' => (bool) $post->post_password,
  );
}
die($post->post_content); // **ADDED TEMPORARILY**
```

This then shows the following responses:
#### `<server>/wp-json/wp/v2/pages`
```
[section is_fullwidth="" background_color="#000000" background_image="{&quot;type&quot;:&quot;custom&quot;,&quot;custom&quot;:&quot;&quot;,&quot;predefined&quot;:&quot;&quot;,&quot;data&quot;:{&quot;icon&quot;:&quot;&quot;,&quot;css&quot;:&#91;&#93;}}" video="" auto_generated="" first_in_builder="1" _array_keys="{&quot;background_image&quot;:&quot;background_image&quot;}" _made_with_builder="true"][/section]
```

#### `<server>/wp-json/wp/v2/pages/<page_id>`
```
<!-- 1b18ac05135e34eedc0577096e29776f -->
```

**The problem therefore seem to be `$post->post_content` differing for some unknown reason when accessing a single page over the REST API.**

(P.S. I have recently found out about and starting developing with Unyson, and I would just like to say a "thank you" to the framework developers)

**Comment by andreiglingeanu** [comment]
Hey @stuajnht, thanks for a lot of details and for trying to dig in.

So, to address your problem. To summarize, when you access `wp-json/wp/v2/pages` (which is a collection of posts) - you get normal `post_content`. When you access individual pages, with `wp-json/wp/v2/pages/<page_id>` you get that [strange md5](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/2d452d866c157a348154c77b82445d6af9997262/class-fw-extension-page-builder.php#L188-L191) hash.

That is not normal behavior but it is expected.

The idea is that `Unyson-Shortcodes` extension, just before displaying the posts in frontend, tries to dynamically compute the `$post->post_content` and insert mutate the `$post` object at runtime (there is a reason behind that decision an it is not worth mentioning that here). It does that by hooking into [`the_posts` and `get_pages`](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/2d452d866c157a348154c77b82445d6af9997262/class-fw-extension-page-builder.php#L60-L63) filters and [modifies](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/2d452d866c157a348154c77b82445d6af9997262/class-fw-extension-page-builder.php#L371-L377) the `post_content` field.

I tend to think that the WordPress REST API doesn't pass the result of a singular endpoint through those two filters, thus the reason behind that strange response you got.

If you're willing to help and if you are familiar with REST API code, you can try to figure out a filter upon which we can get the `Unyson-Shortcodes` to mutate singular resources just before sending them to the API clients.

Let me know if any of that is helpful.

**Comment by stuajnht** [comment]
Hi @andreiglingeanu, and thanks for responding so quickly.

Your summary is pretty much correct, although the individual pages may also include some content, such as this test page:
```html
<div class="fw-page-builder-content">
  <p>Text block 1</p>
  <p>
    <a href="http://localhost/unyson-rest/test-one/">test one</a>
  </p>
  <p>
    <a href="http://localhost/unyson-rest/test-three/">Test 3</a>
  </p>
  <p>
    <a href="#fw-tabs-596e90ba7fb39-1">Tab 1</a>
    <br />
    <a href="#fw-tabs-596e90ba7fb39-2">Tab 2</a>
    <br />
    <a href="#fw-tabs-596e90ba7fb39-3">Third Tab</a>
  </p>
  <p>This is my first tab!</p>
  <p>My second tab!</p>
  <p>Thought I&#8217;d change it up a bit with the name of this one!</p>
  <p>
    <!-- cd6ccdebbac2f83fcbf673e9ce1b522c -->
  </div>
```

Which should actually be:
```html
<div class="fw-page-builder-content">
  <section class="fw-main-row "  >
    <div class="fw-container">
      <div class="fw-row">
        <div class="fw-col-xs-12 fw-col-sm-4">
          <p>Text block 1</p>
          <p>
            <a href="http://localhost/unyson-rest/test-one/">test one</a>
          </p>
          <div class="fw-divider-line">
            <hr/>
          </div>
          <p>
            <a href="http://localhost/unyson-rest/test-three/">Test 3</a>
          </p>
        </div>
        <div class="fw-col-xs-12 fw-col-sm-8">
          <div class="fw-tabs-container" id="fw-tabs-598dbf38a9fe5">
            <div class="fw-tabs">
              <ul>
                <li>
                  <a href="#fw-tabs-598dbf38a9fe5-1">Tab 1</a>
                </li>
                <li>
                  <a href="#fw-tabs-598dbf38a9fe5-2">Tab 2</a>
                </li>
                <li>
                  <a href="#fw-tabs-598dbf38a9fe5-3">Third Tab</a>
                </li>
              </ul>
            </div>
            <div class="fw-tab-content" id="fw-tabs-598dbf38a9fe5-1">
              <p>This is my first tab!</p>
            </div>
            <div class="fw-tab-content" id="fw-tabs-598dbf38a9fe5-2">
              <p>My second tab!</p>
            </div>
            <div class="fw-tab-content" id="fw-tabs-598dbf38a9fe5-3">
              <p>Thought I'd change it up a bit with the name of this one!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
```

I can't guarantee that I'll be able to get anywhere, but thanks for your help with pointing me in the direction of the needed code so that I can have a look, and for information on how the framework works.

**Comment by andreiglingeanu** [comment]
The content you are receiving in `$post->post_content` is pretty much useless. All the data relevant data is located in that JSON blob.

Please let me know if you get to make it!

**Comment by stuajnht** [comment]
Hi again @andreiglingeanu,

I've had a look at getting this to work, and I believe that I now have it working correctly. Please see the pull request: https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/pull/95

The content 'rendered' in the JSON now includes the processed shortcode HTML, rather than the incorrect responses that were being returned.

**I have only limited testing environments, so please test thoroughly**. However, testing with a few test (and one live) sites seem to generate the responses correctly. If you require any information on how it works, please let me know.
