### ISSUE TITLE
Is it possible to get  "fw_get_db_settings_option('field_id')" value in custom widget ?

### ISSUE THREAD

**Issue by mhsohag11** [ThemeFuse/Unyson#2756]
simply i caught database value by using  ` echo fw_get_db_settings_option('field_id')` in index.php
but i want to show the value in my custom widget.
how to bring this theme option value in custom widget ?

**Comment by ViorelEremia** [comment]
you can get it in widget, unyson is initialized on hook after_setup_theme after this hook with priority default you can use much of his functions. Hook widget_init is executed after after_setup_theme so you can use function fw_get_db_settings_option('field_id') in your class widdget but do not register your widget directly in function.php i mean before hook after_setup_theme register widget like here https://codex.wordpress.org/Widgets_API then you can use this function even in construct function of widget
