### ISSUE TITLE
Upload option type  images only SVG JS bug

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2758]
I know that SVG is not allowed by default in WP but if you use a plugin like Safe SVG and upload a file , upon closing you get the 

`Cannot read property 'url' of undefined`

here , https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/upload/static/js/images-only.js#L162

but if you save the page and reopen the upload option you get to see the icon preview and there are no JS errors 

![screenshot_2](https://user-images.githubusercontent.com/2340172/29239775-b050c2e6-7f56-11e7-93f0-6ac2c927f66f.jpg)

**Comment by andreiglingeanu** [comment]
SVG support in core is landing soon: https://core.trac.wordpress.org/ticket/24251

I believe the uploader should support it too, right.

**Comment by danyj** [comment]
YEAHHHH!!!

**Comment by andreiglingeanu** [comment]
That is working already, implemented by #2757! Make sure you have a solution for allowing SVGs.
