### ISSUE TITLE
Renaming fn.datetimepicker() to fn.unyson_datetimepicker()

### ISSUE THREAD

**Issue by pnpetroff** [ThemeFuse/Unyson#2761]
I have two datetimepicker js plugins (one from Unyson and one from 3rd party plugin) and I want to create some kind of compatibility with Unyson.

Is it possible to rename the name of the plugin or in some way to overwrite the datetime picker option  type js without creating problems?

**Comment by danyj** [comment]
what file are you talking about , dateime picker that we have is this 
https://github.com/ThemeFuse/Unyson/blob/f821fabed94cfd66eee16392b2b5cc9cce7e4ffa/framework/includes/option-types/datetime-picker/static/js/jquery.datetimepicker.js


and is default jquery UI date time picker 

https://jqueryui.com/datepicker/

**Comment by danyj** [comment]
what conflict/issues do you have , be precise please post bug info if any

**Comment by pnpetroff** [comment]
It's connected to this problem - https://github.com/ThemeFuse/Unyson/issues/2635

As I'm also using ACF and the Unyson datepicker is overwriting the ACF one (Date Time Picker field). It's because ACF makes a call to fn.datetimepicker and it starts the Unyson one and not the ACF one.
