### ISSUE TITLE
Text block modal problem 

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#2762]
Hi! 
The modal in Text block shortcode doesn't visible. 
I think it's wrong z-index CSS
http://take.ms/DqCUB

Can you check it? 
Thanks!

**Comment by danyj** [comment]
browse @duongancol  :) 

https://github.com/ThemeFuse/Unyson/issues/2732

**Comment by duongancol** [comment]
Thank @danyj 
Why don't you make a pull request?

**Comment by danyj** [comment]
> Why don't you make a pull request?

if you look at the code the z-index is auto generated by editor so there is more to it than what we see, 
it should be looked at properly. the "fix" is just a temp patch that I used.

**Comment by duongancol** [comment]
Yeah, I see. The z-index probably is generated from JS. 
Anyway, it's weird that this problem doesn't be fixed. It should be a high priority. Are they busy?

**Comment by danyj** [comment]
looks like it + vacation time

**Comment by duongancol** [comment]
@danyj da
your custom CSS code doesn't work for Unyson shortcode, do you have a solution? 
![add new service ubonline wordpress 2017-08-24 14-49-37](https://user-images.githubusercontent.com/1773011/29655528-8b0a177e-88db-11e7-9393-6eb7ce32c748.png)

**Comment by danyj** [comment]
```
.mce-container.mce-panel.mce-menu,
.mce-container.mce-panel.mce-popover,
#mce-modal-block {
 z-index:2000000!important; 
}

.mce-fw-shortcodes-window {
 z-index:2000001!important; 
}
```

**Comment by duongancol** [comment]
the css works for the popup but I can not click to the shortcode

**Comment by danyj** [comment]
@andreiglingeanu , @GheorgheP   I posted on slack  just now that these must be fixed 
the issue is not just z-index , is the modal itself so it should be looked at by devs,  
im just patching it but those are not real fixes

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2732
