### ISSUE TITLE
With the update of latest version, no longer can access theme option page 

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#2763]
![capture](https://user-images.githubusercontent.com/7946657/29419152-2dafc0ce-8390-11e7-9ef2-d728bc497744.PNG)

**Comment by andreiglingeanu** [comment]
Hey @webangon, email me your ftp credentials. I'll get a hotfix for you until someone from ThemeFuse will fix the update.

**Comment by webangon** [comment]
Thank you . Sent the email .

**Comment by andreiglingeanu** [comment]
In one hour the new version will get uploaded on wordpress.org with a fix.

**Comment by akguthal** [comment]
I'm getting this issue too, thanks for the prompt response! The new update fixing this issue will be for Unyson right?

**Comment by danyj** [comment]
testing

**Comment by danyj** [comment]
@andreiglingeanu , yes ,  

same here , updated to org version 2.7.3 ( how, where are release packs ? ) same bug

**Comment by danyj** [comment]
same bug https://github.com/ThemeFuse/Unyson/issues/2764

**Comment by samirosman2** [comment]
same issue even after updating to 2.7.4 same please help dear I am using real property theme
