### ISSUE TITLE
The latest version of Unyson renders customizer unusable

### ISSUE THREAD

**Issue by Becca800** [ThemeFuse/Unyson#2766]
I downloaded the latest version and now my customizer is not working. It is completely blank under options such as header and others (not all, but most). Initially I thought it was perhaps a plugin issue. So I tested by deactivating all. then I went to one of my other sites and tested the customizer and it was working. I downloaded the latest version of Unyson on that site and boom - customizer is broken. Need this fixed ASAP.

**Comment by danyj** [comment]
@Becca800  browse before posting please https://github.com/ThemeFuse/Unyson/issues/2764

**Comment by Becca800** [comment]
I read that one. Thanks for "explaining" this to me. But the issues were different. My issue is the customizer, his is the editor.

**Comment by danyj** [comment]
issue is same everywhere
