### ISSUE TITLE
Can't add new elements (articles, services etcc..)

### ISSUE THREAD

**Issue by BigVisionItalia** [ThemeFuse/Unyson#2767]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.
Hi after the last updat of unyson plugin i can't add new articles, services and other. Debug mode give me 

Notice: Undefined index: _shortdesc in /Applications/MAMP/htdocs/pannelli/wp-content/themes/energy/inc/mods/mod-metabox/mod-metabox.php on line 47

but if i deactivate Unyson everything come back to work, i tried to deactivate themes and plugins and i detected that the problem is caused from unyson.

How can i fix this? Thanks

**Comment by ViorelEremia** [comment]
Try updating the plugin if the problem still exists reopen issue

**Comment by BigVisionItalia** [comment]
Hi! i tried but still not working.

**Comment by ViorelEremia** [comment]
Looks like it's a theme error. 
What theme do you use?

**Comment by ViorelEremia** [comment]
Drop some temporary credentials, so I can inspect the problem viorel[ at ]themefuse.com
