### ISSUE TITLE
fw-reactive-options-registry.js Not Found

### ISSUE THREAD

**Issue by indopixel** [ThemeFuse/Unyson#2769]
Hi,

I have just updating my Unyson a few minutes ago. But suddenly it displays error in admin page. The errors mainly said that it could not get the fw-reactive-options-registry.js

![error](https://user-images.githubusercontent.com/18467378/29427404-e6af644e-83b3-11e7-98c0-f4e4d9a872dd.jpg)

Best Regards,
Bismo

**Comment by elissonkario** [comment]
Hello. I have the same problem here after updating the plugin.

**Comment by alexluncashu** [comment]
#2764
