### ISSUE TITLE
Sounds Like I am Not Alone

### ISSUE THREAD

**Issue by daesmodus** [ThemeFuse/Unyson#2772]
As soon as I updated Unyson my page builder stopped working, disappeared from the editor tab, and all the Page Builder widgets are gone. My entire site is built on Page builder. Also, because Unyson is required for my Theme once I updated it the Theme Options disappeared from Settings on the Dashboard.

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
