### ISSUE TITLE
 Unyson Version 2.7.6 completely hosed the site editor

### ISSUE THREAD

**Issue by rjgoldstein** [ThemeFuse/Unyson#2774]
About one hour ago I updated a working site at www.we-gp.com to Unyson Version 2.7.6. After the update, all of my pages in the page editor are empty!! The site still works but I was debugging a problem in editor mode and after the update the Unyson framework and all of the page information when in edit mode disappeared!!!
Now I was screwed!!! I cannot create pages with Unyson activated and when I deactivate Unyson the page formatting is 100% crap!!!
I tried going backwards to a backup that I did before updating the Unyson plugin but it does not go back to the previous version!!!
I need a fix ASAP!!!

If you need FTP access please email me asap at rjgoldstein@dimenxional.com

The site is running WP 4.8.1
Here are all of my plugins
Antispam Bee
Deactivate | Edit | Settings
Easy and extremely productive spam-fighting plugin with many sophisticated solutions. Includes privacy hints and protection against trackback spam.

Version 2.7.1 | By pluginkollektiv | View details | Donate | Support
Select Contact Form Builder	
Contact Form Builder
Deactivate | Edit
Contact Form Builder is an advanced plugin to add contact forms into your website. It comes along with multiple default templates which can be customized.

Version 1.0.60 | By WebDorado | View details
Select Database Browser	
Database Browser
Deactivate | Edit
Easily browse the data in your database, and download in CSV, XML, SQL and JSON format

Version 1.4 | By Chris Taylor | View details
Select Debug Bar	
Debug Bar
Deactivate | Edit
Adds a debug menu to the admin bar that shows query, cache, and other helpful debugging information.

Version 0.9 | By wordpressdotorg | View details
Select Debug Bar Console	
Debug Bar Console
Deactivate | Edit
Adds a PHP/SQL console to the debug bar. Requires the debug bar plugin.

Version 0.3 | By koopersmith | View details
Select Debug Bar Cron	
Debug Bar Cron
Deactivate | Edit
Adds information about WP scheduled events to Debug Bar.

Version 0.1.2 | By Zack Tollman, Helen Hou-Sandi | View details
Select Debug Bar Extender	
Debug Bar Extender
Deactivate | Edit
A minimalistic profiler / debugging class that hooks into the debug bar and can be implemented easily

Version 0.5 | By Thorsten Ott, Automattic | View details
Select Developer	
Developer
Deactivate | Edit
The first stop for every WordPress developer

Version 1.2.6 | By Automattic | View details
Select Duplicate Page	
Duplicate Page
Settings | Donate | Deactivate | Edit
Duplicate Posts, Pages and Custom Posts using single click.

Version 2.3 | By mndpsingh287 | View details
Select File Manager	
File Manager
Pro | File Manager | Support | Deactivate | Edit
Manage your file the way you like. You can upload, delete, copy, move, rename, compress, extract files. You don't need to worry about ftp. It is realy simple and easy to use.

Version 4.1.6 | View details
Select LayerSlider WP	
LayerSlider WP
Activate | Edit | Delete
LayerSlider is the most advanced responsive WordPress slider plugin with the famous Parallax Effect and over 200 2D & 3D transitions.

Version 6.1.0 | By Kreatura Media | Visit plugin site
Select Log Deprecated Notices	
Log Deprecated Notices
Deactivate | Edit
Logs the usage of deprecated files, functions, hooks, and function arguments, offers the alternative if available, and identifies where the deprecated functionality is being used. WP_DEBUG not required (but its general use is strongly recommended).

Version 0.4 | By Andrew Nacin | View details
Select Log Viewer	
Log Viewer
Deactivate | Edit
This plugin provides an easy way to view log files directly in the admin panel.

Version 14.05.04 | By Markus Fischbacher | View details
Select Modular Custom CSS	
Modular Custom CSS
Deactivate | Edit
Manage and live-preview theme-specific and plugin-specific Custom CSS in the Customizer.

Version 2.0 | By Nick Halsey | View details
Select Ninja Forms	
Ninja Forms
Deactivate | Edit
Ninja Forms is a webform builder with unparalleled ease of use and features.

Version 3.1.9 | By The WP Ninjas | View details
Select Participants Database	
Participants Database
Deactivate | Edit | Settings
Plugin for managing a database of participants, members or volunteers

Version 1.7.5.3 | By xn*au webdesign | View details
There is a new version of Participants Database available. View version 1.7.5.7 details or update now.
Select Postman SMTP	
Postman SMTP
Settings | Deactivate | Edit
Email not reliable? Postman is the first and only WordPress SMTP plugin to implement OAuth 2.0 for Gmail, Hotmail and Yahoo Mail. Setup is a breeze with the Configuration Wizard and integrated Port Tester. Enjoy worry-free delivery even if your password changes!

Version 1.7.2 | By Jason Hendriks | View details
Select ProfileGrid	
ProfileGrid
Activate | Edit | Delete
ProfileGrid adds user groups and user profiles functionality to your site.

Version 2.4.2 | By profilegrid | View details
There is a new version of ProfileGrid available. View version 2.4.4 details or update now.
Select Redirection	
Redirection
Settings | Deactivate | Edit
Manage all your 301 redirects and monitor 404 errors

Version 2.6.6 | By John Godley | View details
There is a new version of Redirection available. View version 2.7.1 details or update now.
Select Shortcodes Ultimate	
Shortcodes Ultimate
Activate | Edit | Delete
Supercharge your WordPress theme with mega pack of shortcodes

Version 4.10.2 | By Vladimir Anokhin | View details
Select Simple 301 Redirects	
Simple 301 Redirects
Deactivate | Edit
Create a list of URLs that you would like to 301 redirect to another page or site. Now with wildcard support.

Version 1.07 | By Scott Nellé | View details
Select Slider Revolution	
Slider Revolution
Deactivate | Edit
Slider Revolution - Premium responsive slider

Version 5.3.1.5 | By ThemePunch | Visit plugin site
Activate Slider Revolution for Premium Benefits (e.g. Live Updates).
A new version of Slider Revolution is available.
Select TLS 1.2 Compatibility Test	
TLS 1.2 Compatibility Test
Deactivate | Edit
Verify TLS 1.2 support for included API endpoints and diagnose a solution to enable compatibility.

Version 1.0.1 | By Stranger Studios | View details
Select Trigger Scheduled Events	
Trigger Scheduled Events
Deactivate | Edit
Trigger any scheduled event now instead of waiting until WP cron tells it to run. Handy for debugging.

Version 1.0 | By Scott Nelle | View details
Select Unyson	
Unyson
Unyson | Deactivate | Edit
A free drag & drop framework that comes with a bunch of built in extensions that will help you develop premium themes fast & easy.

Version 2.7.6 | By ThemeFuse | View details
Select UpdraftPlus - Backup/Restore	
UpdraftPlus - Backup/Restore
Activate | Edit | Delete
Backup and restore: take backups locally, or backup to Amazon S3, Dropbox, Google Drive, Rackspace, (S)FTP, WebDAV & email, on automatic schedules.

Version 1.13.4 | By UpdraftPlus.Com, DavidAnderson | View details
There is a new version of UpdraftPlus - Backup/Restore available. View version 1.13.5 details or update now.
Select User Switching	
User Switching
Deactivate | Edit
Instant switching between user accounts in WordPress

Version 1.0.9 | By John Blackbourn | View details
Select Users Ultra Lite	
Users Ultra Lite
Activate | Edit | Delete
This is a powerful user profiles plugin for WordPress.

Version 1.5.94 | By Users Ultra | View details
Select Users Ultra Pro	
Users Ultra Pro
Activate | Edit | Delete
This is a powerful user profiles plugin for WordPress. This versatile plugin allows you to create user communities in few minutes. It comes with tons of useful shortcodes which give you the capability to customize any WordPress Theme.

Version 1.3.0 | By Users Ultra Pro | Visit plugin site
Select W3 Total Cache	
W3 Total Cache
Activate | Edit | Delete
The highest rated and most complete WordPress performance plugin. Dramatically improve the speed and user experience of your site. Add browser, page, object and database caching as well as minify and content delivery network (CDN) to WordPress.

Version 0.9.5.4 | By Frederick Townes | View details
Select Wordfence Security	
Wordfence Security
Activate | Edit | Delete
Wordfence Security - Anti-virus, Firewall and Malware Scan

Version 6.3.15 | By Wordfence | View details
There is a new version of Wordfence Security available. View version 6.3.16 details or update now.
Select WP Email SMTP	
WP Email SMTP
Settings | Deactivate | Edit
WP Email SMTP plugin allows you to connect any SMTP for sending emails from your WordPress site.

Version 1.0.4 | By FormGet | View details
Select WP Full Stripe Free	
WP Full Stripe Free
Deactivate | Edit | Settings | Upgrade
Free version of WP Full Stripe, a Stripe payments plugin.

Version 1.5.1 | By Mammothology | View details
Select WP Social Plugin	
WP Social Plugin
Settings | Deactivate | Edit
WP Social Plugin - A Social Feed Solution for WordPress

Version 3.0.9 | By Gold Plugins | View details | Settings | Pro Support | Upgrade to Pro
Select WP-DBManager	
WP-DBManager
Deactivate | Edit
Manages your WordPress database. Allows you to optimize database, repair database, backup database, restore database, delete backup database , drop/empty tables and run selected queries. Supports automatic scheduling of backing up, optimizing and repairing of database.

Version 2.79 | By Lester 'GaMerZ' Chan | View details

**Comment by danyj** [comment]
please browse before posting

https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
