### ISSUE TITLE
Unyson Language

### ISSUE THREAD

**Issue by sessionstudio** [ThemeFuse/Unyson#2775]
Hello! Congratulations on making a great plugin!
I use WordPress in Spanish, but Unyson does not take the translated file to that language
In WP-CONFIG I have defined: define (' WPLANG ', ' Es_ES '); But the translation still doesn't show.
Any help? Thank you!

**Comment by ViorelEremia** [comment]
Hi, 
You can change language from dshboard -> settings -> general - site language 
Don't use this constant no longer needed.

**Comment by sessionstudio** [comment]
Yes, Spanish is selected.
In any language only the first tab appears translated (Spanish, French, etc,)
![unyson](https://user-images.githubusercontent.com/5034241/29459528-73184e0a-83fa-11e7-882c-456600b144ac.JPG)

**Comment by ViorelEremia** [comment]
Drop me credentials to viorel[ at ]themefuse.com i can't reproduce this issue on my end.

**Comment by ViorelEremia** [comment]
All the strings which do not translate are rewritten from theme, use a plugin to translate as Loco Translate.
All strings are located in theme/language/theme-name.pot
