### ISSUE TITLE
Page builder disappears after updating, urgent!

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2776]
Hello!

There is a big problem for users who use themes with Unyson, after updating, Unyson Page Builder disappears on admin side, hovewer on a front side all content remains, please fix ASAP!

![2017-08-18_10-20-15](https://user-images.githubusercontent.com/12991525/29448351-e6daded0-83fe-11e7-8f1b-db55a4b81ea9.png)
![2017-08-18_10-20-29](https://user-images.githubusercontent.com/12991525/29448350-e6d6dab0-83fe-11e7-9efe-d84ff90ff393.png)

**Comment by andreiglingeanu** [comment]
#2764
