### ISSUE TITLE
Visual Page Builder blank after latest plugin update

### ISSUE THREAD

**Issue by mthamill** [ThemeFuse/Unyson#2777]
Hi, I installed the latest update Version 2.7.6 of the the visual page builder plugin & my existing content is now blank on all pages.  I cannot edit any page with the visual page builder; I can add a new page & edit but that's all.  All was working great before this.

Thanks for you help

**Comment by pnpetroff** [comment]
Same here. I'm experiencing this issue too.

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by mthamill** [comment]
Updated Unyson extensions - thanks danyj

**Comment by jrockmedia** [comment]
#2764 doesn't work for me updates have no release 
"Shortcodes" extension github repository "ThemeFuse/Unyson-Shortcodes-Extension" has no releases.
