### ISSUE TITLE
extensions cURL 7 error

### ISSUE THREAD

**Issue by csas64** [ThemeFuse/Unyson#2778]
Hello, 
2 days ago I installed unyson on my site, but I could not activate the extensions.
I found on your forum an old  extensions archive (2016) and uploaded it via ftp. 
Everything was fine until this morning when I updated the unyson. Since then, it does not make any visible changes, as if page builder does not exist. 
I saw in the forum that extensions should be updated as well and this would solve the problem, but since I can't update the extensions via the wordpress admin dashboasrd, could I download the updated extesions somewhere so I can use ftp for upgrade again? 
Thanks!

**Comment by danyj** [comment]
yes , download them from git one by one ,  

these 2 are most important

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension
