### ISSUE TITLE
Adding theme option panel and metabox for page

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#278]
Hi
When I was using the scratch-parent theme there were options for metabox and theme option panel.How can I use it again?  I haven't seen any extension like thiese.

**Comment by moldcraft** [comment]
The `Appearance > Theme Settings` menu appears only if your theme has `{theme}/framework-customizations/theme/options/settings.php` with some options in it.

I hope I have understood you correctly.

**Comment by webangon** [comment]
Hi 
Thank you . Yes this is what I want. Is there anyway to put this folder inside plugin folder? I mean inside framework/extensions/

**Comment by moldcraft** [comment]
> Is there anyway to put **this folder** inside plugin folder? I mean inside framework/extensions/

Which folder?

**Comment by webangon** [comment]
Yes inside framework/extensions/ folder

**Comment by moldcraft** [comment]
Why do you want to move options folder to plugin directory?

**Comment by webangon** [comment]
I want to keep  this organised.This create dependency that I must activate the plugin otherwise the options will not work. If I move folder into plugin directory then on plugin activation this option will be available. 

I think it is better to make theme options and metabox as extension

**Comment by moldcraft** [comment]
Sorry it's very confusing what are you trying to explain.

-----

The theme must work without any plugin. Use TGM Plugin Activation to warn/inform users to install Unyson to be able to use all theme features (look in [scratch theme](https://github.com/ThemeFuse/Scratch-Theme/blob/fb3ec6e4beb716d58394dda3d0ae437f1103699f/scratch-parent/functions.php#L8-L26) how to use TGM).

**Comment by moldcraft** [comment]
> Is there anyway to put this folder inside plugin folder?

No. You can't put anything in plugin folder.

> Thank you . Yes this is what I want.

You are welcome. I am closing this.
