### ISSUE TITLE
Back up help

### ISSUE THREAD

**Issue by lifestylegr** [ThemeFuse/Unyson#2780]
Hi.  I have a major problem with the unyson backup on my WP site.  I installed Jevelin Theme by shufflehound and then unyson.  I thought all my backups were working fine but when I have had a problem and tried to restore, they fail.  I get this message:

_Files Restore: Failed to remove dir: /wpcom-132877384/wp-content/plugins/vaultpress_

Wordpress support say there is some conflict with vaultrpress and I had no idea that was running too.  
I am not a tech and now WAY out of my depth.  I need to know how to sort this restore problem as my site is now ruined.  Please help

**Comment by andronic90** [comment]
Hi, try to use only Content Backup in this case.

If you need to use a Full Backup here at the first view is a conflict with this "vaultpress" folder, you can try to move the folder temporary in "wp-content/" and try one more time, maybe this helps.
