### ISSUE TITLE
Bug In RGBA Color Picker After Updating to Unyson 2.7.6

### ISSUE THREAD

**Issue by indopixel** [ThemeFuse/Unyson#2781]
Hi,

I have noticed that there is a bug in the RGBA Color Picker. When I slide the transparency bar to 0, the value keep displaying 1, it should be 0 ( screenshot provided ). This behavior also occurs when I click reset in the RGBA color picker, I set the default value to rgba( 255, 255, 255, 0.1 ). 

![error](https://user-images.githubusercontent.com/18467378/29463506-15561348-845d-11e7-868b-b6c546eee4d6.jpg)

Best Regards,
Bismo

**Comment by ivandotv** [comment]
Can confirm this.
