### ISSUE TITLE
Unyson Plugin Updated but nothing happens

### ISSUE THREAD

**Issue by Okie23** [ThemeFuse/Unyson#2782]
I updated my Unyson plugin and nothing has changed.
In the plug in info page it shows new features but these aren't added to my wordpress unyson plugin page.
What can I do?

**Comment by charlesjohn2004** [comment]
Hi, when I updated the plugin today I lost all layouts I built, the pages display correctly on front end but the backend page builder are is blank. Did this happen for you?

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by ViorelEremia** [comment]
Try this #2790 (comment)
