### ISSUE TITLE
All page content gone but site is live and working

### ISSUE THREAD

**Issue by nolan2017** [ThemeFuse/Unyson#2783]
have  been going through every step I can find in forums to solve my issue with no resolve.
Issue:
Noticed after update of wordpress all of the content for my page which I believe now is connected with Unyson has disappeared.  The page works fine but none of the build is there.  I've tried doing test pages and making changes to the existing page and nothing sticks.  Trying clearing every cache I could find and disabling all plug ins.  Disabling plug ins brings a text back but none of the unyson build content.  Activated just unyson and all content disappears.  Have a meeting scheduled with the admin of my server to try to follow one possible solution found through forums in the phpmyadmin files.

Any help is appreciated.

Also reverting back to an earlier site build had no effect which surprised me, thought for sure that would at least get the old content back.

**Comment by adamosborne** [comment]
Having the same issue. But mine happened before updating WordPress. Did the update in hopes that it would fix, and no luck. Content shows up fine on the front end, nothing in the back end.

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
