### ISSUE TITLE
Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (cURL error 7: )

### ISSUE THREAD

**Issue by csas64** [ThemeFuse/Unyson#2784]
Hello, I had the same error. I inserted the code you mentioned in another message and I have this message:
WP_Error
(
[errors] => array
(
[http_request_failed] => array
(
[0] => 'cURL error 7: '
)
)
[error_data] => array()
)

Can you please tell me how to solve it?
Thank you!

**Comment by ViorelEremia** [comment]
Try this #2790 (comment)
