### ISSUE TITLE
Extension option save form not working

### ISSUE THREAD

**Issue by sabujdas94** [ThemeFuse/Unyson#2787]
Extension options save form not working after updating the plugin for SUBDOMAIN installation. 
The new link look like this http://192.168.5.109/sbudomain/sbudomain/wp-admin/***** insted of http://192.168.5.109/sbudomain/wp-admin/*****

Thanks and waiting for solve the issue.

**Comment by ViorelEremia** [comment]
Give us more details it looks like this issue: https://github.com/ThemeFuse/Unyson/pull/2835

**Comment by sabujdas94** [comment]
Suppose I install WordPress  http://localhost/wp and install Unyson plugin and active Breadcrumbs extensions. When i am going to change **Text for Homepage** and click save it's not working.  But it's working if i install in top label domain. The reason behind this in subdomain installation it's add a extra parameter in form action url. that's why the url become http://localhost/wp/wp-admin/*** instead of http://localhost/wp/wp-admin.
Thanks

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/pull/2835
