### ISSUE TITLE
Page builder elements disappeared after updating to the latest version

### ISSUE THREAD

**Issue by charlesjohn2004** [ThemeFuse/Unyson#2789]
Hi,
I updated my Unyson plugin to the latest version and all the elements in the page builder area (the area to which I drag and drop elements) disappeared. When I view that page from the Fron-end everything is fine but if I try to edit the page it doesn't have any contents to edit. Pls help.

Thanks,
Charles

**Comment by ViorelEremia** [comment]
Hi,
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
