### ISSUE TITLE
[Question] - how can I replace the font select in my_typography option type?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#279]
I want to place a slider instead of the select for the font size. After many attempts and critical errors, I came with the idea to do it differently. I have no idea if it's gonna work.

Should I use <code>FW_Option_Type_Slider::_render</code> inside my_typography option type's <code>_render</code> function? I would be happy to get a hardcoded idea, I would be happy to try.

I am thinking about this kind of structure:
<pre>
'demo_typography' => array(
	'label' => __( 'Typography', 'unyson' ),
	'type'  => 'my_typography',
	'value' => array(
		'size'   => array( 
			'value' => 14, 
			'properties' => array('min' => 10, 'max' => 16, 'step' => 1),
		),	
		'other_field' => 'value'
	),
	'desc'  => '',
	'help'  => '',
),
</pre>
I just have no idea in mind on how to write the functions, have to hack it all up.

Please just give me some suggestion, I would appreciate it and hopefully helps others too.

**Comment by moldcraft** [comment]
An option-type can be rendered [like this](https://github.com/ThemeFuse/Unyson/blob/01fd6b878cce513a27d54283685596977199d748/framework/includes/option-types/addable-option/view.php#L25-L33) and its value can be exctracted [like this](https://github.com/ThemeFuse/Unyson/blob/01fd6b878cce513a27d54283685596977199d748/framework/includes/option-types/addable-option/class-fw-option-type-addable-option.php#L76-L79)

**Comment by thednp** [comment]
Thanks @moldcraft I managed to make it work with hard coding, but I will look into it, your suggested code seems more clean.

**Comment by thednp** [comment]
I am getting this JS error <code>Uncaught ReferenceError: fwEvents is not defined</code>, but the HTML looks ok. Just no visible and the slider related script doesn't fire.

**Comment by thednp** [comment]
Please disregard previous, the default <code>$components</code> values were set wrong. I am not using your suggested code, but it's working fine, will try some testing in the front-end.

If anyone interested in the custom typography option-type, drop me a line.

Thanks again.
