### ISSUE TITLE
Unyson "Customize" Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ebuzzell** [ThemeFuse/Unyson#2791]
This issue recently arose after the latest update. I have also updated the extensions I believe (fixed the other page builder issue already ;)) 

When I go to customize a page, this error appears at the top, and several of the normal customize options show nothing but a blank page when you click on them. 
"Warning: Invalid argument supplied for foreach() in /home/liveyo11/public_html/wp-content/plugins/unyson/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php on line 148"

**Comment by ViorelEremia** [comment]
Try this #2790 (comment)
