### ISSUE TITLE
Page Builder is blank despite having content in it

### ISSUE THREAD

**Issue by helilabs** [ThemeFuse/Unyson#2792]
Hi
i've been encountering this problem since yesterday after updating Unyson plugin 
Page Builder is completely blank despite that meta field related to page builder isn't empty
![Blank page builder](http://helilabs.com/1.png)

![Page Builder meta field](http://helilabs.com/2.png)

please help

**Comment by ViorelEremia** [comment]
you did https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
