### ISSUE TITLE
URGENT - Not Saving Page Content

### ISSUE THREAD

**Issue by patriziavergassola** [ThemeFuse/Unyson#2795]
Hello,
I've updated Unyson to the latest version but page content is not saved after I published/updated it.
Can you please help?
Thank you in advance,
Patrizia

**Comment by ViorelEremia** [comment]
Hi,
Create temporary credentials from your site so I can inspect the problem. Drop them here: viorel[ at ]themefuse[ dot ]com

**Comment by patriziavergassola** [comment]
Hi,
just sent them to email address indicated 👍

**Comment by ViorelEremia** [comment]
Now everything is fine I tested a new page and shw is worked you did not update unyson extensions. 
I noticed that you don't have php extension zip installed if you want to use extension backup please install this extension. If you are not familiar with PHP Zip module, please contact your hosting provider.
