### ISSUE TITLE
Loading Data to edit page

### ISSUE THREAD

**Issue by DineWhere** [ThemeFuse/Unyson#2797]
Hi, 

First, i have to say that unyson is amazing, it's very user-friendly and easy to use.
we build our website using this plugin.

but now we are facing one issue with that. whatever we build in pages is not loading in the backend to edit that.
we can see the content that we build in our web site front end, but to edit that its empty.
As example, our front end address is: http://korona.cards/get-korona-card/
but as you can see in attached file backend is empty, so I can not edit that

We need help, how we can solve this.

<img width="1678" alt="screen shot 2017-08-21 at 4 47 29 pm" src="https://user-images.githubusercontent.com/15108314/29519993-794cc0c4-8690-11e7-839b-f1f4f31b2115.png">

**Comment by DineWhere** [comment]
Issue with page builder #2764

**Comment by etwordpress01** [comment]
Hi, Guys. I am facing same issue : https://github.com/ThemeFuse/Unyson/issues/2798

Please help me for this issue.

Thanks again

**Comment by ViorelEremia** [comment]
Try this #2790 (comment)
