### ISSUE TITLE
Page Builder Issue with release 2.7.6 Urgent

### ISSUE THREAD

**Issue by etwordpress01** [ThemeFuse/Unyson#2798]
hi, Thank  you very much for a great Framework for WordPress.

I am using this framework from last 2 years. For the fist time i have faced a major issue. Today i have updated Unyson plugin and its extensions. After update page builder extension stop working.  It clean my page builder data and whenever i update page by adding new shortcode then it does't save shortcodes.

![i1](https://user-images.githubusercontent.com/31212934/29522274-1af6be50-86a2-11e7-8575-a20fcb883511.png)

I edit a page which was created before update and switch Visual Page builder to default editor. It rendered shortcode in WordPress content area. 
![i2](https://user-images.githubusercontent.com/31212934/29522261-13194a7c-86a2-11e7-9cfb-2fee17a3bba5.png)

Please help me as soon as possible. 

Thanks

**Comment by alexdotte** [comment]
I'm having similar problem.. page builder is throwing javascript error parsing JSON from the google font loader and showing blank page:
<img width="1267" alt="screen shot 2017-08-21 at 12 42 12 am" src="https://user-images.githubusercontent.com/29446261/29523626-3c8a10c0-8653-11e7-8d4f-091973efb24d.png">

**Comment by alexdotte** [comment]
It seems to be related to the response returned by the URL in the fw_get_google_fonts_v2() method:
http://google-webfonts-cache.unyson.io/v1/webfonts

**Comment by alexdotte** [comment]
Gracias
