### ISSUE TITLE
error using unyson

### ISSUE THREAD

**Issue by hkao2000** [ThemeFuse/Unyson#2799]
I installed a fresh version of WP along with the Jevelin theme onto my 1and1 account. Jevelin requires Unyson to work. So i installed Unyson and all its extensions. When trying to load my site www.realappprofits.com i get the following:

Warning: Invalid argument supplied for foreach() in /homepages/14/d682319459/htdocs/clickandbuilds/RealAppProfits/wp-content/plugins/unyson/framework/helpers/general.php on line 1258

Any idea how i can resolve this issue?

**Comment by ViorelEremia** [comment]
Try this https://github.com/ThemeFuse/Unyson/issues/2790#issuecomment-323770195
