### ISSUE TITLE
Custom option values not saving

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#280]
Sorry to bug but I am trying to make custom option for a border style and have used gradient option as template plus trying to understand http://raw-test.readthedocs.org/en/latest/components/backend.html 

The option output in backend work fine but saving data does not work. I always get the defaults back

in my option class the render is 

	protected function _render($id, $option, $data)
	{
		$output = fw_render_view(dirname(__FILE__) . '/view.php', array(
			'id' => $id,
			'option' => $option,
			'data' => $data
		));

		return $output;
	}

and default is 

	protected function _get_defaults()
	{
		return array(
			'value' => array(

				'border' => array(
					'border-size' => '0px',
					'border-style' => 'solid',
					'border-color' => '',
				) ,
			)
		);
	}

Instead of posting the whole view here, this is just a bit for border-color , other 2 are same except for the option name 

		<?php
		echo fw()->backend->option_type( 'color-picker' )->render(
			'border-color',
			array(
				'type'  => 'color-picker',
				'value' => ( isset( $option['value']['border']['border-color'] ) )? $option['value']['border']['border-color'] : '',
				'attr'  => array(
					'class' => 'border-color'
				)
			)
		);
		?>

This is option used in the back 

	'header_border' => array(
		'type' => 'thzborder',
		'label'        =>'',
		'value' => array(
	
			'border' => array(
				'border-size' => '0px',
				'border-style' => 'solid',
				'border-color' => '',
			) ,
		)

what am I missing here?

**Comment by moldcraft** [comment]
An option-type can be rendered [like this](https://github.com/ThemeFuse/Unyson/blob/01fd6b878cce513a27d54283685596977199d748/framework/includes/option-types/addable-option/view.php#L25-L33) and its value can be exctracted [like this](https://github.com/ThemeFuse/Unyson/blob/01fd6b878cce513a27d54283685596977199d748/framework/includes/option-types/addable-option/class-fw-option-type-addable-option.php#L76-L79) *( similar question https://github.com/ThemeFuse/Unyson/issues/279 )*

----

P.S. I think it's better/cleaner

```
        'border' => array(
            'size' => '0px', // without 'border-' prefix
            'style' => 'solid',
            'color' => '',
        )
```

On render you have to specify `id_prefix` and `name_prefix`, so on form submit, in `$_POST`, the value will be sent within your option value `fw_options[your_option_id][border][color]: '#fff'` instead of `fw_options[color]: '#fff'`.

```php
echo fw()->backend->option_type( 'color-picker' )->render(
	'color',
	array(...), // same as in your example above
	array(
		'value' => fw_akg('boder/color', $data['value']),
		'id_prefix' => $data['id_prefix'] .'-border-', // here will come 'color'
		'name_prefix' => $data['name_prefix'] .'[boder]', // here will come '[color]'
	)
);
```

Then in `_get_value_from_input()` you extract that border color value 

```php
$color = fw()->backend->option_type( 'color-picker' )->get_value_from_input(
    array(...), // the same array as in view
    fw_akg('border/color', $option_input_value)
);

// then return the same array structure as in `_get_defaults()['value']`
```

**Comment by danyj** [comment]
Thnx for the reply, reason why I left border-color border-size is because I am just imploding the array key and value from the option and generating the css. This way I can do complete box model and dont have to rewrite prefixes. Now if I understood correctly 

This should be my view

		<?php
		echo fw()->backend->option_type( 'color-picker' )->render(
			'border-color',
			array(
				'type'  => 'color-picker',
				'value' => ( isset( $option['value']['border']['border-color'] ) )? $option['value']['border']['border-color'] : '',
				'attr'  => array(
					'class' => 'border-color'
				)
			),
			array(
				'value' => fw_akg('border/border-color', $data['value']),
				'id_prefix' => $data['id_prefix'] .'-border-color-', // here will come 'color'
				'name_prefix' => $data['name_prefix'] .'[border-color]', // here will come '[color]'
			)
		);
		?>


My  _get_value_from_input()

	protected function _get_value_from_input($option, $input_value)
	{
		
		
		$color = fw()->backend->option_type( 'color-picker' )->get_value_from_input(
			'border-color',
			array(
				'type'  => 'color-picker',
				'value' => ( isset( $option['value']['border']['border-color'] ) )? $option['value']['border']['border-color'] : '',
				'attr'  => array(
					'class' => 'border-color'
				)
			),
			fw_akg('border/border-color', $input_value)
		);
		
		return array(
			'value' => array(

				'border' => array(
					'border-size' => '0px',// will be added if this works
					'border-style' => 'solid',// will be added if this works
					'border-color' => $color,
				) ,
			)
		);
	}

I tried but still no luck.

**Comment by danyj** [comment]
also tried your way without border prefix same thing. I must be missing something in the id_prefix and name_prefix

**Comment by moldcraft** [comment]
Try `'name_prefix' => $data['name_prefix'] .'[border]'`

**Comment by danyj** [comment]
tried all combos

	'value' => fw_akg('border/border-color', $data['value']),
	'id_prefix'   => $data['id_prefix'] . $id . '-border-',
	'name_prefix' => $data['name_prefix'] . '[border]',


	'value' => fw_akg('border/border-color', $data['value']),
	'id_prefix'   => $data['id_prefix'] . $id . '-border-',
	'name_prefix' => $data['name_prefix'] . '[' . $id . '][border]',


	'value' => fw_akg('border/border-color', $data['value']),
	'id_prefix'   => $data['id_prefix']'-border-',
	'name_prefix' => $data['name_prefix'] [border]',

and so on, 
the option name is printed correctly 
fw_options[header_border][custom][border][border-color] ( is inside multi-picker) 

but no luck saving

**Comment by danyj** [comment]
Here visual 
http://screencast.com/t/l5KcRdw8Ikk

the name does look like the built array.

**Comment by moldcraft** [comment]
Sorry,  I forgot to mention: in render,  $data['value']  is value from database, so use it instead of $option['value']

**Comment by danyj** [comment]
yes I am using it and I looked in DB , the values are not being saved as new values , only the defaults


    6:"border";a:3:{s:11:"border-size";s:3:"0px";s:12:"border-style";s:5:"solid";s:12:"border-color";s:0:"";

**Comment by moldcraft** [comment]
What `_get_value_from_input()` returns,  that goes in the database

**Comment by danyj** [comment]
Thing is I used default gradient option as template , and ass soon as I changed the primary and secondary values to be arrays instead of the string , the options were not saving anymore
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/gradient/class-fw-option-type-gradient.php#L84


Second code block here is _get_value_from_input

https://github.com/ThemeFuse/Unyson/issues/280#issuecomment-75861317

**Comment by thednp** [comment]
I think you should have a look at the typography option-type. It's a great idea on how to have an option with array() value. Just saying.

**Comment by danyj** [comment]
@thednp thnx for the info bud Il look in to it but I think it has an issue with 2/3 dimensional arrays 
In my option this here 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography/class-fw-option-type-typography.php#L124

Is an array and that is where the problem begins. 
See my previous post https://github.com/ThemeFuse/Unyson/issues/280#issuecomment-75871442

**Comment by thednp** [comment]
That's a bad example. Take the typography option type and rename everything to your need, works better. I have 3 custom option types working perfect based on it.

**Comment by thednp** [comment]
Personally I don't think I would need a border-settings option type, I do all stuff with LESS now. but I could do an option type to work for you.

**Comment by danyj** [comment]
@thednp if you could mange to get just this to work it would be great , I can continue from there. 
But this array must match since I will continue from there 


	protected function _get_defaults()
	{
		return array(
			'value' => array(

				'border' => array(
					'border-size' => '0px',
					'border-style' => 'solid',
					'border-color' => '',
				) ,
			)
		);
	}

**Comment by thednp** [comment]
he 
man the border size thing you can do a <code>$data['border']['size'].'px'</code> for your back-end values display. I don't think you need to complicate things though.

**Comment by danyj** [comment]
:100:

**Comment by moldcraft** [comment]
@danyj try to return a hardcoded value from `_get_value_from_input()`,  that differs from default value, just to test if it will be saved in the database,  if it does, then inspect why your `_get_value_from_input()` is not working properly
*(I cant test it because I am on mobile now)*

**Comment by danyj** [comment]
will do , is 3am here and graphic  card just blew. what a day. will have to continue tomorrow.

**Comment by thednp** [comment]
I almost have it working.

**Comment by danyj** [comment]
im stil here bud replying from lap and the machine is dead till tomorow.

**Comment by thednp** [comment]
Here you go
http://www.filedropper.com/border-settings

At <code>[theme]/inc/includes/option-types.php</code> you need this
<pre>
function _action_theme_include_border_settings() {
    if (is_admin()) {
        require dirname(__FILE__) . '/option-types/border-settings/class-fw-option-type-border-settings.php';
    }
}
add_action('fw_init', '_action_theme_include_border_settings');
</pre>

Your option looks like this:
<pre>
'standard_border' => array(
	'label' => __( 'Border Settings', 'unyson' ),
	'type'  => 'border-settings',
	'value' => array(
		'width' => '2px',
		'style'  => 'regular',
		'color'  => '' // this can be unset
	),
	'desc'  => 'Here\'s another thing!',
	'help'  => 'Momo!!',
)
</pre>

Check the view file, you can add more border width if you want or border styles.

Have fun.

**Comment by danyj** [comment]
thank you much bud . will test as soon as i fix the comp

**Comment by thednp** [comment]
OK, just let me know how it goes, it works for me.

**Comment by danyj** [comment]
since u at it. did you test with value arrary->array since that is where my problem has. begun.

**Comment by thednp** [comment]
Man, after save, I get all saved values back into the fields. So I don't have to test or var_dump anything else. I'm sure this goes smooth.

**Comment by danyj** [comment]
ok bud tomorow than, if u need anything in joomla or from youjoomla.com let me know il be glad to help

**Comment by thednp** [comment]
I am sure I can help you do Joomla better than you do today :)

**Comment by danyj** [comment]
I doubt that but thank you for the help.

**Comment by thednp** [comment]
Let me know how it goes ok?

**Comment by thednp** [comment]
Well you didn't close the issue, you still having trouble?

**Comment by danyj** [comment]
just got the gtx 970, gtx 660 blew last night. On to test now.

**Comment by danyj** [comment]
This is not a go. Your option does work but it does not help me exp[lain the issue in my option. I appreciate the effort but I have same issue as before , 
My option array is inside the value array https://github.com/ThemeFuse/Unyson/issues/280#issuecomment-75875791
 and is not an array on its own like the typography components array. 

Yes I am bit stubborn here and dont want to make an option like this 
		return array(
			'value' => false,
			'border' => array(
				'border-size' => '0px',
				'border-style' => 'solid',
				'border-color' => '',
			) ,
		);

since it is beyond me why would this return/save value 

	$data['border']['border-color']


And this 

		return array(
			'value' => array(
				'border' => array(
					'border-size' => '0px',
					'border-style' => 'solid',
					'border-color' => '',
				) ,
			)
		);


	$data['value']['border']['border-color']

Would fail. 

There is a reason behind the array setup since this option is much more than just a border setting. It is complete box model, margin, padding etc, I used border as an example to try to understand the process of creating complex options. Thing  is that none of the core options follow the same coding pattern thus I am not ale to find the bug in my option.  I compared typography, gradient and switch and all 3 use different methods or array population. 


what I figured is that my $data in view or  $input_value from _get_value_from_input is empty all the time thus the options ends up using the default values. 

and by reading #283  $input_value should return the DB saved value and $data in view should do the same. 


@moldcraft do you mind if I send you what I have? Could you spare few min?
.

**Comment by moldcraft** [comment]
@danyj you can send me the zip to `unyson[at]email.com`

**Comment by danyj** [comment]
Thank you much! Email sent. I need just 1 working example of any of the options and will continue from there.

**Comment by danyj** [comment]
@moldcraft  Sorry , see line 74 and line 227  in view.php , only those 2 were tested for DB values. Others are not complete.

**Comment by moldcraft** [comment]
@danyj Done (email sent). The key moments:

```php
// file: view.php

echo fw()->backend->option_type( 'short-text' )->render(
	'border-size',
	array(
		'type'  => 'short-text',
		'value' => fw_akg('border/border-size', $option['value']),
		'attr'  => array(
			'class' => 'border-size'
		)
	),
	array(
		'value' => fw_akg('border/border-size', $data['value']),
		'id_prefix' => $option['attr']['id'] .'-border-',
		'name_prefix' => $option['attr']['name'] . '[border]',
	)
);
```

```php
// file: class-fw-option-type-....php

...

/**
 * @internal
 */
protected function _get_value_from_input($option, $input_value)
{
	if (!is_array($input_value)) {
		return $option['value'];
	}

	$value = $this->_get_defaults();
	$value = $value['value'];

	foreach ($value as $property => $sub_props) {
		foreach ($sub_props as $sub_prop => $sub_prop_default_value) {
			if (isset($input_value[$property][$sub_prop])) {
				$value[$property][$sub_prop] = (string)$input_value[$property][$sub_prop];
			}
		}
	}

	return $value;
}

/**
 * @internal
 */
protected function _get_defaults()
{
	return array(
		'value' => array(
			'padding' => array(
				'padding-top' => '0px',
				'padding-right' => '0px',
				'padding-bottom' => '0px',
				'padding-left' => '0px',
			) ,
			'margin' => array(
				'margin-top' => '0px',
				'margin-right' => '0px',
				'margin-bottom' => '0px',
				'margin-left' => '0px',
			) ,
			'border' => array(
				'border-size' => '0px',
				'border-style' => 'solid',
				'border-color' => '',
			) ,
		)
	);
}
```

**Comment by danyj** [comment]
:100: THANK YOU!

**Comment by danyj** [comment]
I am going nuts here!

why doesn't this simply work? 

I added additional key to the default array , it should not be set by user but is auto generated . It works perfect on save  but  not on reset or first load without a save. 


	/**
	 * @internal
	 */
	protected function _get_value_from_input($option, $input_value)
	{
		if (!is_array($input_value)) {
			return $option['value'];
		}
	
		$value = $this->_get_defaults();
		$value = $value['value'];
	
		foreach ($value as $property => $sub_props) {
			foreach ($sub_props as $sub_prop => $sub_prop_default_value) {
				if (isset($input_value[$property][$sub_prop])) {
					$value[$property][$sub_prop] = (string)$input_value[$property][$sub_prop];
				}
			}
		}
		$value['css'] = 'BY LOOKING AT THE LOOP AND CODE THIS SHOULD WORK';
		return $value;
	}
	
	/**
	 * @internal
	 */
	protected function _get_defaults()
	{
		return array(
			'value' => array(
				'padding' => array(
					'padding-top' => '0px',
					'padding-right' => '0px',
					'padding-bottom' => '0px',
					'padding-left' => '0px',
				) ,
				'margin' => array(
					'margin-top' => '0px',
					'margin-right' => '0px',
					'margin-bottom' => '0px',
					'margin-left' => '0px',
				) ,
				'border' => array(
					'border-size' => '0px',
					'border-style' => 'solid',
					'border-color' => '',
				) ,
				'css'=>''
			)
		);
	}

**Comment by danyj** [comment]
@moldcraft  and this is the print front 
http://prntscr.com/7ajsw6

and back 

http://prntscr.com/7ajt5v

if saved  works

http://prntscr.com/7ajtb1

**Comment by danyj** [comment]
unless you are cleaning it up somewhere and requiring all array values to be set by user , this should work 

		$value['css'] = $input_value['css'];
		return $value;

**Comment by danyj** [comment]
this is the additional option in case you wondering 


		echo fw()->backend->option_type( 'text' )->render(
			'css',
			array(
				'type'  => 'text',
				'value' => $optioncss,
				'attr'  => array(
					'class' => 'thz-boxmodel-css'
				)
			),
			array(
				'value' => $datacss,
				'id_prefix' => $option['attr']['id'].'-',
				'name_prefix' => $option['attr']['name'],
			)
		);

it works when saved , names , id's values everything works when saved, but I need it to be outputted on reset as well.

**Comment by danyj** [comment]
to late and i think im coming to my senses now , if is reset and css value has not been added by the user in options array, it cant output anything. right? long day!

**Comment by danyj** [comment]
@moldcraft   could you please spare a sec here and give me a pointer , 

ok , so I have everything working as I need but I would also like to add an option for the user to show this options set inside a popup, for example 

http://prntscr.com/7b2yqh
I have 2 views  now , 1 normal and second one should be popup .  
Reason behind popup is that is compact  and admin renders faster 

What way should I follow to do this properly , 

I tried adding data-template to the button and display options like this 


		if($option['popup']){
			
	
	
			$theview = fw_render_view(dirname(__FILE__) . '/views/'.$view.'.php', array(
				'id' => $id,
				'option' => $option,
				'data' => $data,
				'optioncss'=> $print_css->ThzGenerateCss($option['value']),
				'datacss'=> $print_css->ThzGenerateCss($data['value']),
			));
					
			$renderview ='<a href="#" class="button button-primary thz-boxstyle-popup" data-option="';
			$renderview .=fw_htmlspecialchars($theview);
			$renderview .='">';
			$renderview .= $option['button-text'];
			$renderview .='</a>';
			
			

			
			
		}


problem with this is if user does not click on the button and saves the option will be empty since the template has not been rendered, 
so looks like I need another hidden input to do this. 

I am trying to stay away from your popup option since I have to add all options inside the popup and it will be another array than. 

Hope you can give me the idea to finish this.
