### ISSUE TITLE
All content disappeared from page after update

### ISSUE THREAD

**Issue by zapptaa** [ThemeFuse/Unyson#2800]
I updated the plugin and then went to the page and all the page content that I had added wasn't there anymore although the site content still appears when you view the site. homepage content still there online - but not when you go to the dashboard and then the page everything is blank. 

Do you have a previous version repository? that I can install the previous version. 
Current version - Version: 2.7.6 - I need to re-install the previous Version: 2.7.5.

**Comment by zapptaa** [comment]
I managed to find you previous version repository and installed 2.7.5. All the content is back so won't be able to update until the new version works properly by not making all the content disappear. Let me know when you sort this out until then I m making a backup and using your old 2.7.5 plugin.

**Comment by duongancol** [comment]
I rolled back 2.7.5 version and it still didn't work.

**Comment by duongancol** [comment]
I activated ad-word plugin and it works. 
Thanks!

**Comment by ViorelEremia** [comment]
@zapptaa try to update to latest version unyson plugin and also extensions. I think the last version did not work for you because you did not update extensions.
