### ISSUE TITLE
Warning: Invalid argument supplied for foreach at /typography-v2/class-fw-option-type-typography-v2.php on line 148

### ISSUE THREAD

**Issue by radawebs** [ThemeFuse/Unyson#2801]
can you please any help me for some reason when i updates the unyson plugin, after a while started to show the following. 

Warning: Invalid argument supplied for foreach() in /home4/bhysen/public_html/wp-content/plugins/unyson/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php on line 148

on top of the website. the website with the issue is www.radawebs.com

if someone know the problem please help me to fix it.

thanks

**Comment by ViorelEremia** [comment]
See here https://github.com/ThemeFuse/Unyson/issues/2790#issuecomment-323770195

**Comment by radawebs** [comment]
Thanks, now just fixed.
