### ISSUE TITLE
Trouble 

### ISSUE THREAD

**Issue by cottonglass** [ThemeFuse/Unyson#2802]
I'm having trouble using your plug-in. I can't use the unyson plugin on my administration panel and i'm getting this error on my website:

Warning: Invalid argument supplied for foreach() in /home/cottongl/public_html/wp-content/plugins/unyson/framework/helpers/general.php on line 1247

Warning: in_array() expects parameter 2 to be array, null given in /home/cottongl/public_html/wp-content/themes/the-core-parent/theme-includes/helpers.php on line 2169

You can check it out on www.cottonglass.com

Thank you

**Comment by danyj** [comment]
contact theme support ,
