### ISSUE TITLE
Not working to send emails through Forms

### ISSUE THREAD

**Issue by sweb27** [ThemeFuse/Unyson#2804]
Hello, I recently started using your wonderful framework, so beautiful! But I can not get emails through my contact form from the site... please Tell me what am I doing wrong?
 Screenshot of settings:  http://prntscr.com/gbg3sj

Screenshot of the server settings: http://prntscr.com/gbg4di

**Comment by ViorelEremia** [comment]
Looks like everything is fine as you set it up. I have tested on my end and there are no problems. Try to test the email and play with the server settings.

**Comment by sweb27** [comment]
If I give you access to a test account, do you want to check the operation of the framework Unyson personally? I tested different plugins, the problems found, and with Unyson unfortunately there is... On what email can I send the data for testing?

**Comment by ViorelEremia** [comment]
viorel [ a ] themefuse [ dot ] com

**Comment by sweb27** [comment]
ViorelEremia
Good morning, I have written a letter to your mail, did it you?
