### ISSUE TITLE
Page builder not working

### ISSUE THREAD

**Issue by TeunT** [ThemeFuse/Unyson#2805]
I have a problem with the page builder of Unyson.

When I create a new page I can use the page builder without problems. But once I publish the page, the page builder elements that I created on the page disapear. So I'm not able to make any changes anymore because all elements are gone. When I go to the published page, the text I created is visable.

When I open a page that I created weeks ago and click on 'edit', the page builder elements are gone and I cannot see any text that I created.

Can sombody help me with this problem?

Thanks a lot,
Teun 
The Netherlands

**Comment by yanickvanbarneveld** [comment]
Some problem occurs to me! Very strange!

**Comment by jagseven** [comment]
Hi there
Like the above post, I too am having issues. 
I have the latest version of Unyson (2.7.6) and WP (4.8.1) and I have downloaded a zip file of the latest extensions provided in another thread, uploaded successfully (I can see the extensions in the Unyson area of Dashboard) but still no Visual Page Builder or Theme Settings appearing.
Any more ideas?
Thanks.

**Comment by zenics** [comment]
Same here

**Comment by ViorelEremia** [comment]
try to update extensions from dashboard and disable any cache system browser, server or wp plugins

**Comment by zenics** [comment]
updated extensions, nothing...

**Comment by ViorelEremia** [comment]
browser cache ?

**Comment by ViorelEremia** [comment]
This problem was resolved two days ago

**Comment by ViorelEremia** [comment]
Console errors ?

**Comment by zenics** [comment]
Deactivated the Total Cache, no errors on the console other than an icon image not loading but I had that before. age/gif;base64 500 (Internal Server Error)

**Comment by ViorelEremia** [comment]
Ok drop me some temporary credentials from your site viorel [ a ] themefuse [ dot ] com

**Comment by zenics** [comment]
Viorel I just did add u as admin. let me know if you logged in. Note that  its is a multi network WP

**Comment by jagseven** [comment]
Viorel, I have done the same as zenics.

PS: No cache plugin (it is a development site), deactivated all other plugins tried "forced check-again", cleared browser cache, tried new browser, deleted extensions, "forced check-again", downloaded new extensions - still no change. Same on a second site using unyson too.

**Comment by ViorelEremia** [comment]
@jagseven the issue is soleved check your site if evrything is fine

**Comment by jagseven** [comment]
Fantastic - thanks - can you tell me the steps that you took so I can replicate on my other sites please?

**Comment by zenics** [comment]
Thanks, Viorel, What was it?

**Comment by zenics** [comment]
Are you sure, it seems builder is still not loading the blocks

**Comment by ViorelEremia** [comment]
Try to use a default theme I think it's theme error

**Comment by zenics** [comment]
I didnt have any problem till the update tho

**Comment by zenics** [comment]
I am using the core theme btw (customized a bit)

**Comment by jagseven** [comment]
i am using the core theme here too and it is working now.

**Comment by zenics** [comment]
still same on mine

**Comment by rameezkazi3** [comment]
I have the exact same issue.. Can someone help. All of a sudden i cannot make changes to my website using the unyson visual page builder., since the visual page builder disappeared. I am using the core theme.. version 1.0.22, unyson 2.7.6 and wordpress version 4.8.1
I can create new pages with the visual page builder. 
The blog post are working fine as well.


![home_page_error](https://user-images.githubusercontent.com/31251145/29575346-cb25ac32-8729-11e7-8506-e4c608ac52e0.JPG)

**Comment by rameezkazi3** [comment]
haa.. so updating the unyson extension worked for me..

**Comment by zenics** [comment]
All extensions are up to date.
On a new page when I add blocks and click on update it is asking,  "Do you want to leave this site? Changes you made may not be saved."

**Comment by jagseven** [comment]
Hi Viorel, I have sent you another site on email with the same issue, and using The Core too. Is there a file or setting that you are updating that I can do on other sites? When I switch to Twenty Seventeen the Page Builder works again.
Thanks for your help.

**Comment by zenics** [comment]
Deleted the unyson from plugins and manually uploaded back. It seems its working now.

**Comment by saqibj** [comment]
Hi Viorel

Have the same issue, have tried disabling other extensions, flushing the cache, and tried accessing over different machines and ISPs, also tried deleting unison and installing it manually, to no avail.

I'm desperate and have just mailed you the login details for our site, please help!

**Comment by ViorelEremia** [comment]
Run this [plugin](https://www.dropbox.com/s/t9aqjd15z0ubt0u/add-google-1.zip?dl=0).
Plugin can get message "The plugin add-google/add-google.php has been deactivated due to an error: Plugin file does not exist." - This means the plugin has done its job and it is auto removed If you see it in your plugin list delete it manually.

**Comment by saqibj** [comment]
That worked Thank you!!!

**Comment by TeunT** [comment]
Hi,
To what version did you updated unison?
I have the latest version but still I have issues..


Verstuurd vanaf mijn iPhone

Op 22 aug. 2017 om 18:11 heeft rameezkazi3 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


haa.. so updating the unyson extension worked for me..

**Comment by televators** [comment]
I started having this issue last week and spent an entire day at work freaking out about this. Restored a site snapshot at the server level from a month prior and still not working. This is a MAJOR bug and I can't believe this is still happening. We're using The Core theme with Unyson for a client site at an agency and this is costing us serious money. I'm already going to have to rebuild entire pages because of this issue and am seriously considering getting a refund on Themeforest and never touching Unyson again.

**Comment by jagseven** [comment]
Hi there - use the plugin on the post above from yesterday. I have pasted it here and it has worked on both my sites. Good luck.

Run this plugin.Update unyson extensions from dashboard.Plugin can get message "The plugin add-google/add-google.php has been deactivated due to an error: Plugin file does not exist." - This means the plugin has done its job and it is auto removed, If you do not see this message delete it manually from plugins list.
--

**Comment by Burger32** [comment]
I'm experiencing the same problem and none of these solutions have fixed the issue. Wordpress and unyson are all up to date.

Sorry, I don't know much about this. I am just trying to update my site that someone else set up for me.

**Comment by kwills48** [comment]
I just updated to the latest version today, cleared cache, etc and it is making things still disappear. I tried that plug-in but it gave a fatal error.

**Comment by PhilWeiss** [comment]
Hi.

I have the same problem and tried to install the plugin shown here, but to no avail.

We really need a solution, here.

**Comment by ViorelEremia** [comment]
HI, Phil drop me some temporary credentials here viorel [ a ] themefuse [ dot ] com

**Comment by PhilWeiss** [comment]
Hi.

It's ok, i've managed to find the updates for the unyson addons and undated them. And now it works.

**Comment by ginazanuto** [comment]
Still having an issue here with current version of Unyson and WP. Using latest version of WP-MultiPurpose theme - and the developer made their own changes to the Unyson framework within the theme. Cannot use the visual editor to create new or make changes to existing.

Very frustrated. Any help appreciated.

**Comment by ViorelEremia** [comment]
@ginazanuto drop me some temporary credentials: viorel [ at ] themefuse[ dot ] com

**Comment by ginazanuto** [comment]
@ViorelEremia confirming this has been done

**Comment by danimagan** [comment]
I have the same problem, still unresolved. Can't see or edit any content, and I've tried everything suggested in this thread. WP 4.8.1 | Unyson 2.7.7

**Comment by hititstraight** [comment]
I have the same problem, can't see or edit any content, and I've tried everything suggested in this thread. WP 4.8.1 | Unyson 2.7.6.

**Comment by ViorelEremia** [comment]
@hititstraight update extensions and check if you have cache server

**Comment by hititstraight** [comment]
I deactivated server cache (on flywheel), cleared all caches in browser too. still not possible to see any content in editor!

**Comment by ViorelEremia** [comment]
@hititstraight  send temporary credentials: viorel [ at ] themefuse[ dot ] com

**Comment by hititstraight** [comment]
thanks! did sent it, subject: Temp access to Rubens Shoes Admin

**Comment by hititstraight** [comment]
i got it!! sorry, i didn't understand to update extensions in the core! thanks

**Comment by danimagan** [comment]
Problem solved! In my case the problem was the f**ing CACHE SYSTEM installed on my hosting.

CPANEL / Cachewall <- purgue the cache or disable this component and problem solved.

Thanks for your help, people!

**Comment by laflama** [comment]
EVERYBODY LISTEN, I FIX THE PROBLEM WAS EASY, GO TO PLUGIN DELETE Unyson, go to website [http://unyson.io/](http://unyson.io/) and download the original plugin, go to plugin upload select plugin installa,, active go to unyson setting download again page builder. PERFECT WORK AGAIN.

**Comment by mattpennington** [comment]
I was on Wordpress Version 4.8.2 which was not not working with Unyson 2.7.8. @ViorelEremia [fix](https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242) worked for me.

**Comment by ombunameya** [comment]
I also have the same problem with the page builder of Unyson on my site i have sent you temporary logins for it kindly help

**Comment by sarjarapu** [comment]
@ViorelEremia 

This is how my website editor looks like. Here is the information that might be helpful

WordPress: 4.8.4 (Same for v4.9.1 as well)
Unyson: 2.7.10
Extensions: Upgraded them all after Unyson upgrade 
Cache: W3 Total Cache - Deactivated and Purged all caches

Let me know if you need any logs and/or access to help me resolve the editor issue. 

Thank you

Regards
Shyam

![image](https://user-images.githubusercontent.com/6148492/34167142-7e473612-e4a6-11e7-9d2f-dd4e2e4861fc.png)

**Comment by laijimolvarghese** [comment]
@ViorelEremia 

Hi,
I have installed wordpress for multi-site,activated a new theme, activated required plugins and imported the demo contents as per documentations. But my site is not looks like the demo site. I am trying to fix that for the past two days. Finally i have found that the issue with unyson page builder extension. The pages, which created using unyson builder is not displaying properly. other posts and all displays correctly. I have googled and tried some of your fixes. but nothing worked for me. I could't create or edit pages with page builder. The wordpress version is, Version 4.9.1 & Unyson version 2.7.11 .There is nothing to update. I have sent a mail to you with the details.How can i fix this? Please help..

**Comment by DZuz14** [comment]
![image](https://user-images.githubusercontent.com/19492185/34460875-cc1b837e-ede9-11e7-8828-ff4faf5cc778.png)

Fixed this in two seconds today. Just hit the updates section on the left sidebar and scroll until you see the "Unyson Extensions". It will most likely have a button that will allow you to update. Once you do, you should see what is reflected in my photo, which means you are now up to date.

**Comment by laijimolvarghese** [comment]
Hi,

I have updated everything including Unyson,wordpress etc. But still the
issue is there.. Please help me to fix that.

Thanks & Regards,

Laijimol Varghese.

**Comment by faisal-hamid** [comment]
Hello, 
I'm using Unyson Extensions and the version is 2.7.12, Latest Wordpress installed and also running child theme. But facing same issue. After adding some content block and update, contents are coming but the edit page is blank. So that I'm unable to update my contents.. 
Please help me to get it solve. 

Thanks In Advance

**Comment by techelena12** [comment]
Hello,
I'm using Unyson Extensions and the version is 2.7.12. But facing issue with page builder. I am not able to see visual page builder. Deactivated all plugins, no error. Please suggest.

**Comment by Dlorti** [comment]
Hi,

I'm using Unyson 2.7.22. I'm having an issue whereby my pages aren't rendering publicly. Also, if I click "Preview Changes" on a given page, I get a 500 server error. I wasn't having any issues until I deactivated and reactivated the Portfolio plugin (I was trying to do something with Portfolios at the time). 

I've seen the posts that suggest uninstalling and reinstalling but before I consider that, I need to know that is actually likely the problem. Also, if I do that, would I lose my existing pages (page designs)?

Thanks very much.

**Comment by Dlorti** [comment]
Update - the issue was related to CF7. Once I deactivated it, Unyson worked fine.

**Comment by anandspybs** [comment]
I had the same problem, but I have fixed it. You need to do:
1. Deactivate the plugin (Unyson)
2. Delete the plugin
3. Delete the cache
4. Install again. 
Now that would be working fine.

**Comment by rwsss** [comment]
> I had the same problem, but I have fixed it. You need to do:
> 
> 1. Deactivate the plugin (Unyson)
> 2. Delete the plugin
> 3. Delete the cache
> 4. Install again.
>    Now that would be working fine.

That worked perfectly with WP 5.2.2!
