### ISSUE TITLE
Multi-Picker (Theme Option) not working and shows fatal error after updating Unyson

### ISSUE THREAD

**Issue by macthecoder** [ThemeFuse/Unyson#2806]
Everything was completely okay before updating (21st August, 2017) Unyson. As I updated Unyson, I got this fatal error message:
"Fatal error: Uncaught TypeError: Argument 1 passed to fw_extract_only_options() must be of the type array, boolean given, called in C:\xampp\htdocs\testing\wp-content\plugins\unyson\framework\includes\option-types\multi-picker\class-fw-option-type-multi-picker.php on line 422 and defined in C:\xampp\htdocs\testing\wp-content\plugins\unyson\framework\helpers\general.php:803 Stack trace: #0 C:\xampp\htdocs\testing\wp-content\plugins\unyson\framework\includes\option-types\multi-picker\class-fw-option-type-multi-picker.php(422): fw_extract_only_options(false) #1 C:\xampp\htdocs\testing\wp-content\plugins\unyson\framework\core\extends\class-fw-option-type.php(296): FW_Option_Type_Multi_Picker->_get_value_from_input(Array, NULL) #2 C:\xampp\htdocs\testing\wp-content\plugins\unyson\framework\helpers\class-fw-db-options-model.php(200): FW_Option_Type->get_value_from_input(Array, NULL) #3 C:\xampp\htdocs\testing\wp-content\plugins\unyson\framework\helpers\database.php(65): FW_Db_Options_Model->get(NULL, NULL, NULL) #4 C:\xampp\htd in C:\xampp\htdocs\testing\wp-content\plugins\unyson\framework\helpers\general.php on line 803".

I have  checked whether I did any mistake or not. For that checked the same theme options with different version of Unyson , like updated version (21st August 2017) and my previous version (may be it was downloaded previous month). It workes on previous version and not works on latest version. I have to use "multi-picker" option type for my theme option. 
What should I do?
I badly need a solution for completing my theme and submitting it to themeforest.

**Comment by andreiglingeanu** [comment]
Please show your options array which fails here. I'll try to inspect it.

**Comment by macthecoder** [comment]
'scroll_status_options' => array(
                'type' => 'multi-picker',
                'label' => false,
                'desc' => false,
                'picker' => array(
                    'scroll_status_item' => array(
                        'label' => esc_html__('Enable / Disable Top Scroll', 'inova'),
                        'type' => 'switch',
                        'right-choice' => array(
                            'value' => '1',
                            'label' => esc_html__('Enable', 'inova')
                        ),
                        'left-choice' => array(
                            'value' => '2',
                            'label' => esc_html__('Disable', 'inova')
                        ),
                        'value' => '1',
                        'desc' => esc_html__('Select whether you wish to set your site in maintenance mode or not.', 'inova'),
                    )
                ),
                'choices' => array(
                    '1' => array(
                        'scroll_top_bg_color' => array(
                            'type' => 'color-picker',
                            'value' => '#666',
                            'label' => esc_html__('Background Color', 'inova'),
                            'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
                        ),
                        'scroll_top_border_color' => array(
                            'type' => 'color-picker',
                            'value' => '#666',
                            'label' => esc_html__('Border Color', 'inova'),
                            'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
                        ),
                        'scroll_top_color' => array(
                            'type' => 'color-picker',
                            'value' => 'rgba(255, 255, 255, 0.75)',
                            'label' => esc_html__('Icon Color', 'inova'),
                            'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
                        ),
                        'scroll_top_hover_color' => array(
                            'type' => 'color-picker',
                            'value' => '#ffffff',
                            'label' => esc_html__('Icon Hover', 'inova'),
                            'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
                        ),
                    ),
                    'show_borders' => false,
                ),
            ),

Here is one of my multi-picker implementations.

**Comment by andreiglingeanu** [comment]
If you'd format your code better, you'll see that you need to move the `show_borders` a bit lower down the array.

<details><summary>BEFORE</summary><p>

```php
'scroll_status_options' => array(
	'type' => 'multi-picker',
	'label' => false,
	'desc' => false,
	'picker' => array(
		'scroll_status_item' => array(
			'label' => esc_html__('Enable / Disable Top Scroll', 'inova'),
			'type' => 'switch',
			'right-choice' => array(
				'value' => '1',
				'label' => esc_html__('Enable', 'inova')
			),
			'left-choice' => array(
				'value' => '2',
				'label' => esc_html__('Disable', 'inova')
			),
			'value' => '1',
			'desc' => esc_html__('Select whether you wish to set your site in maintenance mode or not.', 'inova'),
		)
	),

	'choices' => array(
		'1' => array(
			'scroll_top_bg_color' => array(
				'type' => 'color-picker',
				'value' => '#666',
				'label' => esc_html__('Background Color', 'inova'),
				'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
			),
			'scroll_top_border_color' => array(
				'type' => 'color-picker',
				'value' => '#666',
				'label' => esc_html__('Border Color', 'inova'),
				'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
			),
			'scroll_top_color' => array(
				'type' => 'color-picker',
				'value' => 'rgba(255, 255, 255, 0.75)',
				'label' => esc_html__('Icon Color', 'inova'),
				'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
			),
			'scroll_top_hover_color' => array(
				'type' => 'color-picker',
				'value' => '#ffffff',
				'label' => esc_html__('Icon Hover', 'inova'),
				'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
			),
		),

		'show_borders' => false,
	),
),

```

</p></details>

<details><summary>AFTER</summary><p>

```php
'scroll_status_options' => array(
	'type' => 'multi-picker',
	'label' => false,
	'desc' => false,
	'picker' => array(
		'scroll_status_item' => array(
			'label' => esc_html__('Enable / Disable Top Scroll', 'inova'),
			'type' => 'switch',
			'right-choice' => array(
				'value' => '1',
				'label' => esc_html__('Enable', 'inova')
			),
			'left-choice' => array(
				'value' => '2',
				'label' => esc_html__('Disable', 'inova')
			),
			'value' => '1',
			'desc' => esc_html__('Select whether you wish to set your site in maintenance mode or not.', 'inova'),
		)
	),

	'choices' => array(
		'1' => array(
			'scroll_top_bg_color' => array(
				'type' => 'color-picker',
				'value' => '#666',
				'label' => esc_html__('Background Color', 'inova'),
				'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
			),
			'scroll_top_border_color' => array(
				'type' => 'color-picker',
				'value' => '#666',
				'label' => esc_html__('Border Color', 'inova'),
				'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
			),
			'scroll_top_color' => array(
				'type' => 'color-picker',
				'value' => 'rgba(255, 255, 255, 0.75)',
				'label' => esc_html__('Icon Color', 'inova'),
				'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
			),
			'scroll_top_hover_color' => array(
				'type' => 'color-picker',
				'value' => '#ffffff',
				'label' => esc_html__('Icon Hover', 'inova'),
				'desc' => esc_html__('Pick color for your social account icon.', 'inova'),
			),
		),

	),

	'show_borders' => false,
),

```

</p></details>

Why it worked with older Unyson versions is unknown, probably it behaved in a wrong way. You're not supposed to use options in un-documented way like you did with `show_borders` in the array you sent.

**Comment by macthecoder** [comment]
Don't know how did I made this mistake? How stupid I am!
Thanks you very much.

**Comment by andreiglingeanu** [comment]
No problem!
