### ISSUE TITLE
Unyson problems with changing type style in page builder

### ISSUE THREAD

**Issue by mtmcgreg** [ThemeFuse/Unyson#2807]
I can't change my type from paragraph to h1, or anything else. It doesn't give me the option to change it, if it is "paragraph" it only gives me the paragraph option. I have tried what people in past threads have told me to do, and it doesn't work. I haven't heard back since I commented. 

I am about to build two more new websites, and I'm afraid to use Unyson again if this problem isn't fixed.

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2732
