### ISSUE TITLE
Slider not owrking in Digitboost Theme

### ISSUE THREAD

**Issue by josepharbeit** [ThemeFuse/Unyson#2808]
Hello,

Every time i try and make a new slide, i choose to manually upload the images and give it a title and click create, it just reloads the same screen. It does not take me to the screen to upload images and perform any other actions with the slider. I would check to see if the slider is published in the slider tab under appearance and it is, but with 0 images. I click to see if i can add images and have no luck. I am currently using this on a live website as well as a staging website using wp stage coach.

Any help would be greatly appreciated.

Thanks.

**Comment by ViorelEremia** [comment]
Contact your Digitboost Theme theme support, is a theme error not from Unyson
