### ISSUE TITLE
Caching of failed/faulty requests (google font API)

### ISSUE THREAD

**Issue by fealXX** [ThemeFuse/Unyson#2810]
The fw_get_google_fonts_v2 has a minor issue:
If http://google-webfonts-cache.unyson.io/v1/webfonts gives an empty / faulty response with http status 200 the value is cached anyways for 7 days.
If one is using a google font, that breaks the site for the caching period.

Quick Workaround is to change $ttl in /unyson/framework/helpers/general.php:1281 to 0, reload the page and change it back to 7 * DAY_IN_SECONDS

Symptoms are:
**in the settings panel:**
invalid argument supplied for foreach() /unyson/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php on line 148
**on the main page:**
invalid argument supplied for foreach() /unyson/framework/helpers/general.php on line 1258

**Comment by andreiglingeanu** [comment]
Hey @fealXX, we can create an action/filter for the `$ttl` value, if you want to manually shorten the period. Would you mind to come up with a pull request for that? I will happily merge it, in case we're good.

**Comment by fealXX** [comment]
I'd suggest parsing the JSON and checking for non-empty array.
Lowering the period would not fix the issue, just shorten the time the error occurs.

If you can provide information on the api and in which cases it could occur that invalid data is provided without an error code, I'll happily provide a pull request :)

**Comment by andreiglingeanu** [comment]
[Here's](https://github.com/MmdBundles/GoogleWebfontsCacheBundle) the source code for the proxy server that performs that Google Fonts caching. As you can see [here](https://github.com/MmdBundles/GoogleWebfontsCacheBundle/blob/master/Controller/DefaultController.php#L18) it caches the requests for one hour. I don't why it sometimes responds with an empty set of fonts.

Let me know if you need more help during the tracing of the problem.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
