### ISSUE TITLE
Invalid argument supplied for foreach() after update to 2.7.6

### ISSUE THREAD

**Issue by bigpurplebox** [ThemeFuse/Unyson#2813]
I now get 2 error messages after updating from 2.6.16 to 2.7.6 , one within WP in relation to Google fonts

Warning: Invalid argument supplied for foreach() in /homepages/5/d689645716/htdocs/clickandbuilds/InspireMeEquestrian/wp-content/plugins/unyson/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php on line 148

and a second on the live web page 

Warning: Invalid argument supplied for foreach() in /homepages/5/d689645716/htdocs/clickandbuilds/InspireMeEquestrian/wp-content/plugins/unyson/framework/helpers/general.php on line 1258

Which also is Google font related.

**Comment by ViorelEremia** [comment]
See here https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242
