### ISSUE TITLE
Multiple demo install options possible with Unyson or not ?

### ISSUE THREAD

**Issue by bridgemove** [ThemeFuse/Unyson#2814]
Is it possible to provide option to install a demo from multiple possible options like demo one, demo two, demo three etc ?
If, yes, then how ?

Thanks

**Comment by Ataurr** [comment]
Yes, Create a folder in your theme **/demo-content**and add your demo folder like this
/demo-content/{demo-name}/
http://manual.unyson.io/en/latest/extension/backups/index.html#contents
