### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in /wp-content/plugins/unyson/framework/helpers/general.php on line 1258

### ISSUE THREAD

**Issue by vinoddalvi** [ThemeFuse/Unyson#2815]
Just search on google this issue and you will find many websites are facing it which are using unyson plugin.

I get this issue in site front end.

Also some errors are getting in the admin area theme options as shown in this attached screenshot.
![screenshot 7](https://user-images.githubusercontent.com/5412913/29621464-6fde7d16-883e-11e7-9de2-c11928d26c8d.png)

**Comment by ViorelEremia** [comment]
see here https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242
