### ISSUE TITLE
Latest update 

### ISSUE THREAD

**Issue by bomzass** [ThemeFuse/Unyson#2816]
Hello having issue unyson working with another plugin called events made easy. When unyson is activated other plugin does not work properly.
Already did all the possible extension updates and so on. 
<a href="https://ibb.co/ncRUsQ"><img src="https://preview.ibb.co/enmjRk/error_unyson.jpg" alt="error_unyson" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>quick image upload</a><br />

**Comment by ViorelEremia** [comment]
Give us more details where you find these errors 
I tried that plugin and can't reproduce
