### ISSUE TITLE
Help with typography-v2.php

### ISSUE THREAD

**Issue by AlaySMP** [ThemeFuse/Unyson#2817]
Hi, my website is having issue with typography. 
Warning: Invalid argument supplied for foreach() in wp content/plugins/unyson/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php on line 148:

![code](https://user-images.githubusercontent.com/31303197/29652393-7a777768-8862-11e7-9c9e-4a3573f9b5e2.PNG)

**Comment by ViorelEremia** [comment]
see here https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242

**Comment by germanrandhawa** [comment]
Hi @ViorelEremia I am having the same problem here https://www.procolor.com/. I tried your suggestion but seems like some suggested files are missing/deleted from dropbox. Could you please help me SAP.

**Comment by tikyta** [comment]
@germanrandhawa I´m trying to find a solution too? Do you have luck?

**Comment by germanrandhawa** [comment]
@tikyta Nothing yet. I Hope @ViorelEremia will help all of us on #4260

**Comment by tikyta** [comment]
@germanrandhawa 

this solution works for me... add an array to the line 148..
let me know if works for you or you have any suggestion...

	public function get_google_font( $font ) {
		$fonts = $this->get_fonts();

		foreach ( (array)  $fonts['google']['items'] as $g_font ) {
			if ( $font === $g_font['family'] ) {
				return $g_font;
			}
		}

		return false;
	}

**Comment by germanrandhawa** [comment]
> public function get_google_font( $font ) {
> 	$fonts = $this->get_fonts();
> 
> 	foreach ( (array)  $fonts['google']['items'] as $g_font ) {
> 		if ( $font === $g_font['family'] ) {
> 			return $g_font;
> 		}
> 	}
> 
> 	return false;
> }

@tikyta It works. Thanks!

**Comment by tikyta** [comment]
> > public function get_google_font( $font ) {
> > $fonts = $this->get_fonts();
> > foreach ( (array)  $fonts['google']['items'] as $g_font ) {
> > if ( $font === $g_font['family'] ) {
> > return $g_font;
> > }
> > }
> > return false;
> > }
> 
> @tikyta It works. Thanks!

Great @germanrandhawa !!! you´re welcome ;)

**Comment by mp3pintyo** [comment]
for me, the mentioned code still indicated an error, but if we modify it, it is perfect:
```function get_google_font($font) {
    $fonts = $this->get_fonts();
    if (isset($fonts['google']['items']) && is_array($fonts['google']['items'])) {
        foreach ((array) $fonts['google']['items'] as $g_font) {
            if ($font === $g_font['family']) {
                return $g_font;
            }
        }
    }
    return false;
}
