### ISSUE TITLE
http://prntscr.com/gct52j  in visual editor wp editor paragraph dropdown not working

### ISSUE THREAD

**Issue by waqasalampk** [ThemeFuse/Unyson#2819]
http://prntscr.com/gct52j  in visual editor wp editor paragraph dropdown not working 
@andreiglingeanu

**Comment by waqasalampk** [comment]
@Burger32 @ViorelEremia

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/2732
