### ISSUE TITLE
How to collapse accordion tabs? 

### ISSUE THREAD

**Issue by dimavrn** [ThemeFuse/Unyson#2820]
Hello colleagues! 
How to close all tabs in accordion ? 

First tab already opened. But I want to change the default state for this tab "closed" 

Or if i need to click to this tab two times i want to close it.. . like Jquery accordion.

**Comment by dimavrn** [comment]
Please help guys!

**Comment by dimavrn** [comment]
i tried   $( function() {
    $( ".fw-accordion" ).accordion({
      collapsible: true
    });
  } );


but nothing happen

**Comment by dimavrn** [comment]
if i connect jquery-ui library collapsing works! but only first tab collapsing normally , other tabs not expanded..

**Comment by dimavrn** [comment]
In dev manual i saw information about default state of accordion tab,but nothing about what option i need to write in options.php

**Comment by dimavrn** [comment]
everything is found!

**Comment by Sipoke123** [comment]
how to collapse first accordion unyson by default, please help
