### ISSUE TITLE
page builder does not work

### ISSUE THREAD

**Issue by wandrot** [ThemeFuse/Unyson#2821]
Hi I cannot work with my site as, out of a sudden approx 3-4 weeks ago, the page builder stopped to show. I have a blank window without any content. Page buileder is not active. After switching off Unysson I can see the html format, but this is unworkable form me. 
The template is PLAN UP by Haintheme. site www.edu21.pl.  The developer recommended to check the problem with Unyson support directly.
Attached screenshot with the problem  
Please help. The site needs urgent and important updates.

**Comment by duongancol** [comment]
I tested your site again and deactivated all your plugins and the builder worked. 
So I think it's the conflict with a plugin. 
You can try to activate plugin one by one to find where the conflict comes from.
