### ISSUE TITLE
Invalid argument supplied to foreach for google fonts

### ISSUE THREAD

**Issue by afwiski** [ThemeFuse/Unyson#2823]
Warning: Invalid argument supplied for foreach() in /home/content/54/6691654/html/safeharbor.02132017/wp-content/plugins/unyson/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php on line 148 

receiving that warning in the Styling section on the Jevelin theme appearance setup form. The dropdown for the font choices is not pulling in any options or displaying the saved option. When I went to check it out in the inspector the stack trace told me to come here and provide a screenshot.

Thank you for your time.  

![screen shot 2017-08-25 at 11 51 12 am](https://user-images.githubusercontent.com/5691199/29721713-43ad3526-898c-11e7-95a6-fe75511175d3.png)

**Comment by andronic90** [comment]
Hi, have you the last Unyson and extension version?

**Comment by ViorelEremia** [comment]
see here https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242
