### ISSUE TITLE
updating plugin breaks extensions if PHP can't write in plugins dir

### ISSUE THREAD

**Issue by davidsword** [ThemeFuse/Unyson#2824]
Pagebuilder and Slidershow randomly broke on a The Core theme using Unyson.

Turns out when Unyson upgraded vi WP-CLI, all `/extensions/*` where removed and not replaced. In the dashboard UI, it just showed none extensions existed, as if none ever did.

Forgive for not doing more research I'm assuming this is what happened, but I imagine theres a hook in Unyson that re-downloads extensions on Unyson upgrade, however my setup I've hardened to disallowed PHP from writing anywhere expect `wp-content/uploads/` (as a handful of people do), so the extensions didn't re-download.

1) Can Unyson check-and-warn if `../unyson/framework/extensions/`isn't writeable, notifying me that it's not? (so i can give it the writing permission it needs)

2) Can Unyson warn when the previously activated extensions aren't present in the `/extensions/` folder to make troubleshooting for anyone else with the issue easier.

**Comment by andreiglingeanu** [comment]
I believe updating through WP-CLI doesn't preserve extensions, that's of course a bug. Updating the Unyson through the `wp-admin` UI _do_ preserve extensions and it doesn't delete them. This happens through the [`merge_extensions(..)`](https://github.com/ThemeFuse/Unyson/blob/f821fabed94cfd66eee16392b2b5cc9cce7e4ffa/framework/extensions/update/class-fw-extension-update.php#L523-L675) method.

I would recommend performing updates through the [Unyson-CLI](https://github.com/ThemeFuse/Unyson-CLI) package, but it doesn't do extensions preserve _just yet_ too. 

The best way of solving that would be to abstract the `merge_extensions(...)` logic and use it both from the `wp-admin` upgrader and from WP CLI too. That's of course quite some work to do.

<hr>

Unyson uses regular [Filesystem API](https://codex.wordpress.org/Filesystem_API) and it asks for FTP/SSH access in case you don't give write access to `wp-content` dir. That's unfortunately not implemented from the CLI.

**Comment by davidsword** [comment]
Thank you for the info, good to know.

**Comment by davidsword** [comment]
any progress on this bug? 

I have over 100 plugins in my network that upgrade via wpcli fine - unyson losses it's extensions so Ive had to change its permissions to just error out on updates. then have to do manual sftp update.
