### ISSUE TITLE
Unyson Error Generated On Homepage

### ISSUE THREAD

**Issue by danrocklin** [ThemeFuse/Unyson#2825]
I'm getting the following error on my homepage:

Warning: Invalid argument supplied for foreach() in /home/afictrig/public_html/wp-content/plugins/unyson/framework/helpers/general.php on line 1258

Warning: in_array() expects parameter 2 to be array, null given in /home/afictrig/public_html/wp-content/themes/philanthropy-parent/theme-includes/helpers.php on line 2169

You can view it [here](http://africaictright.org/). Any insight would be much appreciated. Thanks!

**Comment by danrocklin** [comment]
I should add that everything has been updated.

**Comment by andronic90** [comment]
Hi, please contact the theme support with your dashboard details: http://support.themefuse.com/hc/en-us/requests/new

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242
