### ISSUE TITLE
Argument 1 passed to fw_extract_only_options() must be of the type array

### ISSUE THREAD

**Issue by saiful-droit** [ThemeFuse/Unyson#2826]
Hi, I am develop a wp theme and using unyson few day age show this message: 
Fatal error: Uncaught TypeError: Argument 1 passed to fw_extract_only_options() must be of the type array, boolean given, called in E:\xamp\htdocs\faded\wp-content\plugins\unyson\framework\includes\option-types\multi-picker\class-fw-option-type-multi-picker.php on line 422 and defined in E:\xamp\htdocs\faded\wp-content\plugins\unyson\framework\helpers\general.php:803 Stack trace: #0 E:\xamp\htdocs\faded\wp-content\plugins\unyson\framework\includes\option-types\multi-picker\class-fw-option-type-multi-picker.php(422): fw_extract_only_options(false) #1 E:\xamp\htdocs\faded\wp-content\plugins\unyson\framework\core\extends\class-fw-option-type.php(296): FW_Option_Type_Multi_Picker->_get_value_from_input(Array, NULL) #2 E:\xamp\htdocs\faded\wp-content\plugins\unyson\framework\helpers\class-fw-db-options-model.php(200): FW_Option_Type->get_value_from_input(Array, NULL) #3 E:\xamp\htdocs\faded\wp-content\plugins\unyson\framework\helpers\database.php(65): FW_Db_Options_Model->get(NULL, NULL, NULL) #4 E:\xamp\htdocs\faded\wp-conten in E:\xamp\htdocs\faded\wp-content\plugins\unyson\framework\helpers\general.php on line 803

How can i solve this problem. Please assist me. Thank you.

**Comment by saiful-droit** [comment]
Solve this issues

**Comment by andronic90** [comment]
Hi, I think you need to send in "fw_extract_only_options( $array )", but you give a boolean value, that is specified in this error.
