### ISSUE TITLE
Page content does not show but demo data successfully uploaded.

### ISSUE THREAD

**Issue by saiful-droit** [ThemeFuse/Unyson#2827]
Hi, Team,

Our Theme demo data successfully uploaded but when we check the page content does not show. It is happen when we updata unyson plugins after page content does not show. Please assist us. Here is Screenshot: 
![screenshot_3](https://user-images.githubusercontent.com/20698608/29749095-6f41cb00-8b46-11e7-98d0-76cec21d47af.png)

**Comment by dzucohuynh** [comment]
this is my issue!!!! :(( why??

**Comment by andronic90** [comment]
have you the latest Unyson and extensions?

**Comment by PhilWeiss** [comment]
Hi.

I have exactly the same issue...

**Comment by ViorelEremia** [comment]
Check the console if you have errors
update unyson extensions
A possible similar issue: https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242
