### ISSUE TITLE
SQL changes are not taken into account

### ISSUE THREAD

**Issue by sstorme** [ThemeFuse/Unyson#2828]
Hi all,

I have an unexpected behaviour with the Unyson builder.

I have a website with a lot of URL's in each page, and i want to change there configuration in one step
http://url.com/oldfolder to http://url.com/newfolder

I did that directly on the database (mysql) but the change is not visible on the website, neither on the frontend nor in the backend (unyson builder)
If i turn off the unyson plugin, URL are good, and if i turn on, it's old URL...

Could you explain me what i miss ?
Is there a cache somewhere ?

Thanks, and sorry for my english, it's not my mother tong
Regards,
Serge

**Comment by andronic90** [comment]
Hi, if you use the backup extension from Unyson this links are replaced automatic. Problem is that in some cases in the DB is saved a json encoded URL or with doubles slashes "//"
