### ISSUE TITLE
[QUESTION] - the difference between $input_value and $option['value']

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#283]
The <code>_get_value_from_input()</code> has them and I need to know what is it different about them?

**Comment by moldcraft** [comment]
If you have this option array in settings options

```php
'hello' => array(
    'type' => 'text',
    'value' => 'Hello World'
),
```

then you open Theme Settings page and change input value to 'Lorem ipsum'

in `_get_value_from_input()`

* `$option['value']` will be `Hello World`
* `$input_value` will be `Lorem ipsum`

**Comment by thednp** [comment]
Thank you.
