### ISSUE TITLE
Customization shortcode tabs for bootstrap 4

### ISSUE THREAD

**Issue by sweb27** [ThemeFuse/Unyson#2830]
Hello, I want to customize the tabs shortcode, I want to make it work with bootstrap styles put 4 tabs in the folder mytheme\framework-customizations\extensions\shortcodes\shortcodes .
```
In the file: view.php did so: <?php if (!defined('FW')) die( 'Forbidden' ); ?>
<?php $tabs_id = uniqid('fw-tabs-'); ?>
<?php
?>
<div class="fw-tabs-container" id="<?php echo esc_attr($tabs_id); ?>">
<!-- Nav tabs -->
<ul class="nav nav-tabs nav-justified font-weight-bold" role="tablist">
<?php foreach (fw_akg( 'tabs', $atts, array() ) as $key => $tab) : ?>
<li class="nav-item">
 <a class="nav-link" data-toggle="tab" href="#<?php echo esc_attr($tabs_id . '-' . ($key + 1)); ?>" role="tab"><?php echo $tab['tab_title']; ?></a>
</li>
<?php endforeach; ?>
</ul>
<!-- Tab panes -->
<!-- Tab panes -->
<div class="tab-content text-center" data-aos="fade" data-aos-anchor-placement="top-bottom">
<?php foreach ( $atts['tabs'] as $key => $tab ) : ?>
<div class="tab-pane" id="<?php echo esc_attr($tabs_id . '-' . ($key + 1)); ?>" role="tabpanel">
<?but this do_shortcode php echo( $tab['tab_content'] ) ?>
</div><!--//tab-pane-->
<?php endforeach; ?>
</div><!--//tab-content-->
</div><!--//fw-tabs-container-->
```
Everything works, but in the <a class="nav-link active" data-toggle="tab" href="#selling-tab" role="tab"Tab name</a> There is a style "active" where the first tab should be active with that style active

You have this function performs the style "ui-tabs-active ui-state-active" in "li"

**Comment by andronic90** [comment]
Hi, you can add in foreach a $count++ and if( $count == 1 ) { $class = 'active'; } or something like this.

By the way, this is not related to the Unyson, you are free to make a custom shortcode and style like you want.
