### ISSUE TITLE
Tables not allowing text entry

### ISSUE THREAD

**Issue by Mikie020** [ThemeFuse/Unyson#2831]
I have gone into the admin section to update a table on one of my pages. I can no longer edit or amend tables. The text boxes and images appear to be ok

**Comment by andronic90** [comment]
Hi, have you try this with the default WP Theme?

**Comment by Mikie020** [comment]
Hi!

Thanks for the response. I have actually managed to fix my issue.

Thanks again!

Maya

**Comment by andronic90** [comment]
OK

**Comment by noesteijver** [comment]
@Mikie020 how did you manage to get it working again? I'm having the same problem at the moment..

**Comment by Mikie020** [comment]
Hi!

Yes I did! I cleared down the cache and browsing history and just checked
that my firewall wasn't blocking anything

Good luck!!

**Comment by M-Tony** [comment]
Hi,

I have the same problem, but this did not help me.
I can add new rows and columns, but cannot enter any information in the table fields.

Can someone help me, please?

Thanks

**Comment by ViorelEremia** [comment]
@M-Tony Drop me some temporary credentials (admin, ftp) and issue: viorel [ a ] themefuse [ dot ] com

**Comment by M-Tony** [comment]
Hi Eremia,

I sent you temporary credentials on your e-mail 2 days ago.
Did you get it, and will you help me, please?

Thanks,
Toni

**Comment by ViorelEremia** [comment]
Those are from admin dashboard I need for ftp server see in cpanel from
hosting provider
