### ISSUE TITLE
[bug] Multi-Select  prepopulate deleting items

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2833]
if you have set prepopulate option to 10 items 
http://manual.unyson.io/en/latest/options/built-in/multi-select.html

 and during items selection you select more lets say 15 , next time you re save  the option it will delete the other five ,  leaving you always with 10 items. 

This is not supposed to happened , prepolutation has nothing to do with how many items you can select.

**Comment by ViorelEremia** [comment]
How you can select 15 items if prepopulate option is 10 items. I have tested this option type and I did not notice any problems.

**Comment by danyj** [comment]
> How you can select 15 items if prepopulate option is 10 items

what do you mean?  

prepopulate and   selection have nothing to do with eachother 


prepopulate  shows selected number of items when select is opened

**Comment by danyj** [comment]
set prepoluate to 3   and select 5 items , after save other 2 wont show

**Comment by ViorelEremia** [comment]
If I set prepopulate to 3 when how I can select 5 items, I don't understand, here is my code
`'test_one' => array(
				'type'  => 'multi-select',
				'value' => array( 'choice-1', 'choice-3' ),
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __('Label test one', '{domain}'),
				'desc'  => __('Description', '{domain}'),
				'help'  => __('Help tip', '{domain}'),
				/**
				 * Set population method
				 * Are available: 'posts', 'taxonomy', 'users', 'array'
				 */
				'population' => 'posts',
				/**
				 * Set post types, taxonomies, user roles to search for
				 *
				 * 'population' => 'posts'
				 * 'source' => 'page',
				 *
				 * 'population' => 'taxonomy'
				 * 'source' => 'category',
				 *
				 * 'population' => 'users'
				 * 'source' => array( 'editor', 'subscriber', 'author' ),
				 *
				 * 'population' => 'array'
				 * 'source' => '' // will populate with 'choices' array
				 */
				'source' => 'post',
				/**
				 * Set the number of posts/users/taxonomies that multi-select will be prepopulated
				 * Or set the value to false in order to disable this functionality.
				 */
				'prepopulate' => 3,
				/**
				 * An array with the available choices
				 * Used only when 'population' => 'array'
				 */
				'choices' => array(
					'choice-1' => __('Choice 1', '{domain}'),
					'choice-2' => __('Choice 2', '{domain}'),
					'choice-3' => __('Choice 3', '{domain}'),
				),
				/**
				 * Set maximum items number that can be selected
				 */
				'limit' => 100,
			),`

**Comment by danyj** [comment]
start typing to get more items

			'exclude' => array(
				'type' => 'multi-select',
				'value' => array(),
				'label' => __('Exclude posts', 'fw'),
				'desc' => esc_html__('Start typing the post names.', 'fw'),
				'population' => 'posts',
				'prepopulate' => 3,
				'source' => array('post','page')
			)

**Comment by ViorelEremia** [comment]
Ok, I can't select more items than is predefined in key prepopulate, how you can select 5 items when prepopulate has value 3. prepopulate param set the limits to extracted items.
![multi_slelect](https://user-images.githubusercontent.com/28967378/31999035-8c2132c4-b99a-11e7-94e0-1bf765162ef5.png)

**Comment by danyj** [comment]
bud , start typing to search for other item  it should show you more posts, prepolutae is not a limit on what is shown and if it is for you that is another bug
