### ISSUE TITLE
UNYSON ACCORDION HOW TO COLLAPSE TABS ???OR CHANGE DEFAULT STATE ON FIRST TAB CLOSED?  

### ISSUE THREAD

**Issue by dimavrn** [ThemeFuse/Unyson#2834]
What option i need to use for hide accordion tab if i click on it ?

`If i use $('.fw-accordion').accordion({ 
    collapsible: true,
});`

Collapsible function working but content in ACTIVE DIV SET WRONG HEIGHT 1px if it ACTIVE and tab cannot open!
This is a bug or what? 
I have a littli fix for this      `ui-accordion-content-active{ height: auto !important}`
but after that transition effect is GONE! 

SORRY FOR MY ENGLISH but i not find any working solution for this in WEB! !!

**Comment by dimavrn** [comment]
sorry guys... i found solution ))))

**Comment by golenopolsky** [comment]
What did you do?? I NEEEED HELP

**Comment by Sipoke123** [comment]
how to collapse first accordion unyson by default, please help

**Comment by Sipoke123** [comment]
how to collapse first accordion unyson by default, please help
