### ISSUE TITLE
problem with saving

### ISSUE THREAD

**Issue by 7aduta** [ThemeFuse/Unyson#2836]
when i try to save i get the following problem

SyntaxError: Unexpected token < in JSON at position 0

and the error from the ajax request

Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Warning: Cannot modify header information - headers already sent in Unknown on line 0

i tried to upload the framwork again and the wordpress it self 

and no luck still get the same error

**Comment by ViorelEremia** [comment]
try to change theme, disable all plugins, reset to default .htaccess, verify error log php

**Comment by 7aduta** [comment]
the problem gone after uninstall the them and active anther theme with unyson and reinstall the theme once again ! 

i think the main problem here that i have
1235 form data the sent through ajax
when it's empty nothing happing

**Comment by 7aduta** [comment]
the problem was in php version and mysql limitation

**Comment by ViorelEremia** [comment]
@7aduta Thanks for such good information I will try to solve this problem in the future.
