### ISSUE TITLE
Social counters no longer working

### ISSUE THREAD

**Issue by rodolfomirandatapia** [ThemeFuse/Unyson#2837]
We are using the social network widget, and suddenly we get ZERO in the facebook counter

1) Facebook counter shows zero
![image](https://user-images.githubusercontent.com/31458519/29849376-0c5081ec-8cec-11e7-8d35-2d8975d5ae74.png)

2) Here is the configuration page:
![image](https://user-images.githubusercontent.com/31458519/29849397-36b1defe-8cec-11e7-8888-f8a583a161e1.png)

Thank you in advance!

**Comment by andronic90** [comment]
Hi,

please contact the theme author
