### ISSUE TITLE
Visual Page Builder not displaying in WP 4.8.1

### ISSUE THREAD

**Issue by upsweptcreative** [ThemeFuse/Unyson#2839]
The Visual Page Builder is no longer working since I updated Wordpress to its latest version. I'm using WordPress 4.8.1 / PHP 5.6 / MySQL 5.6 / Multisite installation.

The content blocks are not displaying where they would normally display (as in the screenshot below):
![iixdvsr](https://user-images.githubusercontent.com/5839369/29882035-bfea2248-8d60-11e7-9e2b-be4ffae3866b.png)

And, when I try to create new content blocks, errors are thrown, as in this screenshot:
![screenshot 2017-08-30 15 14 03](https://user-images.githubusercontent.com/5839369/29882036-bfefcd56-8d60-11e7-9a05-7caad06dcd45.png)

Any help?

Thank you!

**Comment by jesspritchard** [comment]
I'm having a similar issue where the content blocks are not displaying. This was happening on WordPress 4.8, updating to 4.8.1 did not fix the issue. I seem to be adding new content blocks without any issue.

I've disabled all other plugins and still experience the issue.

**Comment by Mausom** [comment]
Facing the same issue. Creating a new page and adding anything new using Visual Page Builder is not getting saved. But if the default editor is used it is getting saved and in Visual Page Builder it is showing as a Text Box. Please help.

**Comment by ViorelEremia** [comment]
Possibly issues: https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242

**Comment by Mausom** [comment]
@ViorelEremia Yeah running the plugin and updating it actually solved the issue. Thanks a lot!

**Comment by himyous** [comment]
Having the same problem and running the plunning+updating didn't do trick.

<img width="1050" alt="screen shot 2017-09-03 at 18 39 12" src="https://user-images.githubusercontent.com/31594600/30004891-41013640-90d7-11e7-80dd-06eaca207f6d.png">

**Comment by ViorelEremia** [comment]
@himyous try to update extensions from admin dashboard. The issue has been resolved for all.
