### ISSUE TITLE
Cannot install DEMO content

### ISSUE THREAD

**Issue by grkosky** [ThemeFuse/Unyson#2840]
This is the message what i recived while install demo content

Failed to create tmp table _fwbk_wptm_woocommerce_log. Unknown collation: 'utf8mb4_unicode_520_ci'

**Comment by ViorelEremia** [comment]
Demo content hasbeener exported from old version mysql, contact your theme developer to change collation from utf8mb4_unicode_520_ci to utf8_general_ci, your mysql don't support this collation utf8mb4_unicode_520_ci.
