### ISSUE TITLE
session_start

### ISSUE THREAD

**Issue by hayatkhawar** [ThemeFuse/Unyson#2841]
I have faced the issue (session_start(): open(/var/cpanel/php/sessions/ea-php56\sess_t6v53g542tii0riaqt8jsgjug4, O_RDWR) failed: No such file or directory (2) in E:\home-server\htdocs\demo-site\wp-content\plugins\unyson\framework\includes\hooks.php on line 256)
Since last update for unyson  issue display when debugger on .  i have remove the browser cache  but issue is still same . I faced this issue in xampp local server. Kindly guide me to resolve this issue.

**Comment by andronic90** [comment]
Hi, have you disabled all plugins except the Unyson and the problem persist?

**Comment by hayatkhawar** [comment]
I have checked all the plugin disabled except the Unyson but still faced the same issue  kindly help me to solved this issue.
 (session_start(): open(/var/cpanel/php/sessions/ea-php56\sess_t6v53g542tii0riaqt8jsgjug4, O_RDWR) failed: No such file or directory (2) in E:\home-server\htdocs\demo-site\wp-content\plugins\unyson\framework\includes\hooks.php on line 256)

**Comment by andycapachi** [comment]
Im with the same problem, does anyone have a solution?

**Comment by ViorelEremia** [comment]
It looks that your configure session path is not correct, try to investigate form [here](http://php.net/manual/en/session.configuration.php#ini.session.save-handler). 
Also if you use an operating system like Linux check who run the Apache process. 
Session path you can find in php.ini
