### ISSUE TITLE
Can Unyson add options to only concrete custom template page ?

### ISSUE THREAD

**Issue by xfg** [ThemeFuse/Unyson#2843]
For example I created the custom template page within my theme for the page of contacts. Now I want to show field for the enter address in the admin panel for the post type `page` but only if a user picked `Contacts` template. I read the framework documentation but not found how to do it. Is it possible to do with unyson?

**Comment by DevWael** [comment]
I did this before but with javascript (Hiding and showing fields with display: none)

```javascript
jQuery(document).ready(function () {
    /*''''''''''''''''''''''''''''''''''''' /   Standard Optns  */
    "use strict";
    var standerOptions = jQuery('#no_options'); //metabox ID
    var standerTrigger = jQuery('#post-format-0'); //post format ID
    standerOptions.css('display', 'none');

    /*''''''''''''''''''''''''''''''''''''' /   Quote Optns  */

    var quoteOptions = jQuery('#fw-options-box-window_quote');
    var quoteTrigger = jQuery('#post-format-quote');
    quoteOptions.css('display', 'none');

    /*''''''''''''''''''''''''''''''''''''' /   Video Optns  */

    var videoOptions = jQuery('#fw-options-box-window_video');
    var videoTrigger = jQuery('#post-format-video');
    videoOptions.css('display', 'none');

    /*''''''''''''''''''''''''''''''''''''' /   Gallery Optns  */

    var galleryOptions = jQuery('#fw-options-box-window_gallery');
    var galleryTrigger = jQuery('#post-format-gallery');
    galleryOptions.css('display', 'none');

    /*''''''''''''''''''''''''''''''''''''' /   Link Optns  */

    var linkOptions = jQuery('#fw-options-box-window_link');
    var linkTrigger = jQuery('#post-format-link');

    linkOptions.css('display', 'none');

    /*''''''''''''''''''''''''''''''''''''' /   Audio Optns  */

    var audioOptions = jQuery('#fw-options-box-window_audio');
    var audioTrigger = jQuery('#post-format-audio');
    audioOptions.css('display', 'none');

    /*''''''''''''''''''''''''''''''''''''' /   Image Optns  */

    var imageOptions = jQuery('#no_options');
    var imageTrigger = jQuery('#post-format-image');
    imageOptions.css('display', 'none');

    /*''''''''''''''''''''''''''''''''''''' /   Core  */

    var group = jQuery('#post-formats-select input');
    group.change(function () {
        if (jQuery(this).val() == 'video') {
            videoOptions.css('display', 'block');
            reyHideAll(videoOptions);

        } else if (jQuery(this).val() == '0') {
            standerOptions.css('display', 'block');
            reyHideAll(standerOptions);

        } else if (jQuery(this).val() == 'quote') {
            quoteOptions.css('display', 'block');
            reyHideAll(quoteOptions);

        } else if (jQuery(this).val() == 'gallery') {
            galleryOptions.css('display', 'block');
            reyHideAll(galleryOptions);

        } else if (jQuery(this).val() == 'link') {
            linkOptions.css('display', 'block');
            reyHideAll(linkOptions);

        } else if (jQuery(this).val() == 'image') {
            imageOptions.css('display', 'block');
            reyHideAll(imageOptions);

        } else if (jQuery(this).val() == 'audio') {
            audioOptions.css('display', 'block');
            reyHideAll(audioOptions);

        } else {
            standerOptions.css('display', 'none');
            quoteOptions.css('display', 'none');
            linkOptions.css('display', 'none');
            imageOptions.css('display', 'none');
            videoOptions.css('display', 'none');
            audioOptions.css('display', 'none');
            galleryOptions.css('display', 'none');
        }
    });

    if (standerTrigger.is(':checked'))
        standerOptions.css('display', 'block');

    if (quoteTrigger.is(':checked'))
        quoteOptions.css('display', 'block');

    if (videoTrigger.is(':checked'))
        videoOptions.css('display', 'block');

    if (galleryTrigger.is(':checked'))
        galleryOptions.css('display', 'block');

    if (imageTrigger.is(':checked'))
        imageOptions.css('display', 'block');

    if (linkTrigger.is(':checked'))
        linkOptions.css('display', 'block');

    if (audioTrigger.is(':checked'))
        audioOptions.css('display', 'block');

    function reyHideAll(notThisOne) {
        videoOptions.css('display', 'none');
        standerOptions.css('display', 'none');
        quoteOptions.css('display', 'none');
        galleryOptions.css('display', 'none');
        imageOptions.css('display', 'none');
        audioOptions.css('display', 'none');
        linkOptions.css('display', 'none');
        notThisOne.css('display', 'block');
    }
});
```

so I have used that code to show and hide unyson fields depending on user post format selection so you can change it to the selection of the page template and do the rest.

**Comment by nicolaelitvac** [comment]
I do this with a function I've added in functions.php
`if ( ! function_exists( 'mg_maybe_include' ) ) :
    function mg_maybe_include( $conditions ) {
        // Include in back-end only
        if ( ! defined( 'WP_ADMIN' ) || ! WP_ADMIN ) {
            return false;
        }

        // Always include for ajax
        if ( defined( 'DOING_AJAX' ) && DOING_AJAX ) {
            return true;
        }

        if ( isset( $_GET['post'] ) ) {
            $post_id = $_GET['post'];
        }
        elseif ( isset( $_POST['post_ID'] ) ) {
            $post_id = $_POST['post_ID'];
        }
        else {
            $post_id = false;
        }

        $post_id = (int) $post_id;
        $post    = get_post( $post_id );



        foreach ( $conditions as $cond => $v ) {
            // Catch non-arrays too
            if ( ! is_array( $v ) ) {
                $v = array( $v );
            }

            switch ( $cond ) {
                case 'id':
                    if ( in_array( $post_id, $v ) ) {
                        return true;
                    }
                break;
                case 'parent':
                    $post_parent = $post->post_parent;
                    if ( in_array( $post_parent, $v ) ) {
                        return true;
                    }
                break;
                case 'slug':
                    $post_slug = $post->post_name;
                    if ( in_array( $post_slug, $v ) ) {
                        return true;
                    }
                break;
                case 'template':
                    $template = get_post_meta( $post_id, '_wp_page_template', true );
                    if ( in_array( $template, $v ) ) {
                        return true;
                    }
                break;
                case 'not_template':
                    $template = get_post_meta( $post_id, '_wp_page_template', true );
                    if ( in_array( $template, $v ) ) {
                        return false;
                    } else {
                        return true;
                    }
                break;
            }
        }

        // If no condition matched
        return false;
    }
endif;`

Then when adding the metabox I use it like this:
`if ( function_exists( 'mg_maybe_include' ) ) :
    if( mg_maybe_include( array('template' => array( 'front-page.php' )) ) ) :
        $options[] = array(
            'home-options' => array(
                'type' => 'box',
                'title' => __('Home Page Options', '{domain}'),
                'options' => array(
                    'welcome-text' => array(
                        'type'  => 'wp-editor',
                        'value' => '<h1>Real-time location tracking.<br /> <span class="text-primary">Delivered.</span></h1>',
                        'attr'  => array( 'class' => 'hz', 'data-foo' => 'bar' ),
                        'label' => __('Welcome Section', '{domain}'),
                        'desc'  => __('This is the first thing the users will see.', '{domain}'),
                        'help'  => __('Add H1 header.', '{domain}'),
                        'size' => 'large', // small, large
                        'editor_height' => 300,
                        'wpautop' => true,
                        'editor_type' => false, // tinymce, html
                        'editor_class'        => ''
                    )
                ),
            )
        );
    endif;
endif;`
