### ISSUE TITLE
Using Unyson Shortcodes in Widget

### ISSUE THREAD

**Issue by DrDanHall** [ThemeFuse/Unyson#2845]
Capability question: Is it possible to use a Unyson shortcode in a Widget? Specifically, I wanted to use a Unyson alert in a widget. 
Thank you.

**Comment by nicolaelitvac** [comment]
You can do that by adding a filter in functions.php
`add_filter('widget_text', 'do_shortcode'); // Allow shortcodes in Dynamic Sidebar`
