### ISSUE TITLE
 Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 2048 bytes) in /home/public_html/wp-content/plugins/unyson/framework/helpers/class-fw-cache.php on line 262

### ISSUE THREAD

**Issue by shankarbandaru** [ThemeFuse/Unyson#2846]
hi i am facing this problem can any one help me 
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 2048 bytes) in /home/public_html/wp-content/plugins/unyson/framework/helpers/class-fw-cache.php on line 262

**Comment by danyj** [comment]
try your theme provider , possible issue is bad loop

**Comment by ViorelEremia** [comment]
try to add define( 'WP_MEMORY_LIMIT', '256M' ); in wp-config.php before the line - That’s all, stop editing! Happy blogging, after that if error still exists when edit your php.ini value memory_limit.
