### ISSUE TITLE
Page Builder Extension assumes write access to Plugins directory

### ISSUE THREAD

**Issue by briangervais** [ThemeFuse/Unyson#2847]
The hosting platform we are using does not allow write access to the plugins directory, which seems to be required in order to use / install / update the page builder extension.

Is there a workaround for this?  Does anyone know the specific directory that needs write access so that we might symlink it to writeable location?

**Comment by ViorelEremia** [comment]
Filter: apply_filters( 'fw_tmp_dir', fw_fix_path( WP_CONTENT_DIR ) . '/tmp' )
You can find all paths in extension update.

**Comment by nydame** [comment]
We are having the exact same problem @briangervais reported. Thank you for coming up with a fix, but I have a quick question: should I put the apply_filters(...) command in class-fw-extension-page-builder.php alongside the other filters? And if not there, where?

**Comment by ViorelEremia** [comment]
You can put it in functions.php or class, function what is loaded only in admin( is checked by function is_admin() ) try:
`add_filter( 'fw_tmp_dir', function( $path ) {  return $your_custom_path  } );`

**Comment by nydame** [comment]
Awesome! Your quick response is very much appreciated!

**Comment by nydame** [comment]
By $your_custom_path, I assume you do not mean the plugin directory in the new environment. Is it a temporary directory that can be anywhere?

**Comment by ViorelEremia** [comment]
Yes.

**Comment by nydame** [comment]
Perfect -- thanks!
