### ISSUE TITLE
Get post types in theme settings

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2848]
Is it possible to retrieve all the post types in the Theme Settings file?

I tried to use get_post_types, but it returns an empty array because the post types are registered after the Theme Settings page is rendered.

Is there a way or workaround to do this?

**Comment by ViorelEremia** [comment]
For me it works correctly
`
global $wp_post_types;

$options = array(
	'general' => array(
		'title'   => __( 'General', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			'post_type' => array(
				'type'  => 'select',
				'value' => '',
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __('Label', '{domain}'),
				'desc'  => __('Description', '{domain}'),
				'help'  => __('Help tip', '{domain}'),
				'choices' => array_map( function( $post_type ) { return $post_type->labels->singular_name; }, $wp_post_types ),
				/**
				 * Allow save not existing choices
				 * Useful when you use the select to populate it dynamically from js
				 */
				'no-validate' => false,
			)
		)
	)
);`
