### ISSUE TITLE
Multi picker with show_borders padding bug

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#285]
When we have multi-picker option with borders 

    'show_borders' => true,

the 0 padding-bottom should be removed. 

Currently looks like this 
http://prntscr.com/69uuvr

Should be like this 
http://prntscr.com/69uvp2

**Comment by moldcraft** [comment]
Duplicate https://github.com/ThemeFuse/Unyson/issues/296#issuecomment-77714936
