### ISSUE TITLE
Update fw_option post meta field with API

### ISSUE THREAD

**Issue by nicolaelitvac** [ThemeFuse/Unyson#2851]
Hi,
I'm trying to save `fw_option`  post meta using REST API.
API update_callback function I'm using is:
```php
public function cpt_update_meta( $value, $object, $field_name ) {
    if ( ! $value || ! is_string( $value ) ) {
        return;
    }

    return update_post_meta( $object->ID, $field_name, strip_tags( $value ) );
}
```

I'm trying to submit this json: `{"price9kt":"111","price14kt":"222","price18kt":"333"}`.
But before sending the json I execute this `serialize(json_decode( $json, true ))`.

The value stored in the data base is `s:91:"s:83:"a:3:{s:8:"price9kt";s:3:"111";s:9:"price14kt";s:3:"222";s:9:"price18kt";s:3:"333";}";";`.
So I see the value in "Custom Fields" when editing the post, but the values in framework's meta-boxes are empty.

The value that should be stored in the data base should be: `a:3:{s:8:"price9kt";s:3:"111";s:9:"price14kt";s:3:"222";s:9:"price18kt";s:3:"333";}`, but I'm not sure how to achieve that.
How to properly update post meta for the `fw_option` created by the framework?

If someone can help me, that would be great.
Thanks

**Comment by andreiglingeanu** [comment]
Hey, give a read to [database helpers](http://manual.unyson.io/en/latest/helpers/php.html#database) section of the manual.
