### ISSUE TITLE
How to bring in site template "Option Addable" ?

### ISSUE THREAD

**Issue by sweb27** [ThemeFuse/Unyson#2852]
Hello, how to bring in the needed template file of my site the option "Addable Option" ? 

Need a code taken from here: http://manual.unyson.io/en/latest/options/built-in/addable-option.html

**Comment by ViorelEremia** [comment]
Where you want to show and get values for this option type? 
I understand you can't extract values from "Addable Option"?
What is template file for you? ex: single.php - `fw_get_db_post_option( get_the_ID(), 'test' )`
http://manual.unyson.io/en/latest/options/integrate.html#content
http://manual.unyson.io/en/latest/helpers/php.html#database
`'test' => array(
				'value' => array('Value 1', 'Value 2', 'Value 3'),
				'type'  => 'addable-option',
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __('Label', 'the-core'),
				'desc'  => __('Description', 'the-core'),
				'help'  => __('Help tip', 'the-core'),
				'option' => array( 'type' => 'text' ),
				'add-button-text' => __('Add', 'the-core'),
				'sortable' => true,
			),`
I want to help you but give more details what do you want to do.

**Comment by sweb27** [comment]
In \framework-customizations\theme\optionsgeneral-settings.php has created the option: 

```
'advan' => array(
						'type'  => 'addable-option',
						'value' => array('Преимущество 1', 'Преимущество 2', 'Преимущество 3', 'Преимущество 4'),
						//'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
						'label' => __('Преимущества', '{domain}'),
						'desc'  => __('Преимущества перечисленные в header сайта на главной странице', '{domain}'),
						//'help'  => __('Help tip', '{domain}'),
						'option' => array( 'type' => 'text' ),
						'add-button-text' => __('Добавить', '{domain}'),
						'sortable' => true,
						)
```
Want to bring in template header.php how to do it correctly?

**Comment by ViorelEremia** [comment]
See here:
http://manual.unyson.io/en/latest/options/integrate.html#settings-options
http://manual.unyson.io/en/latest/helpers/php.html#database
in your case fw_get_db_settings_option( 'advan' );

**Comment by sweb27** [comment]
<?php echo fw_get_db_settings_option ('advan'); ?>   ??? 

Alas, I tried... does Not work, prints "Array"

Screenshot: http://prntscr.com/gguxcg

**Comment by ViorelEremia** [comment]
Yes is an array you need to cycle it. 
I don't know what you are building but this option type offers the opportunity to add multiple values in a value.
`$addables = fw_get_db_settings_option ( 'advan' );

foreach( $addables as $addable ) {
	// echo $addable;
}`

**Comment by sweb27** [comment]
Thanks friend, it worked.
