### ISSUE TITLE
RGBA color picker - can't add value manually 

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#2855]
I can't directly add the color to the rgba color picker (can't edit input)
Regular color picker works okay.

This is the [offending code](https://github.com/ThemeFuse/Unyson/blame/master/framework/includes/option-types/rgba-color-picker/static/js/scripts.js#L150)

Only problem when that line of code is removed, is that if I manually enter `1` for opacity, it will change value from `rgba` to `hex` which was always the way the rgba color picker has worked.
As for the #2587 ( which complains about the hex value), maybe the solution is to save the internal data as rgba. Or if you need to manipulate color further there are simple `php` and `javascript` functions that convert `hex` to `rgba`

In this state the picker is technically unusable because I believe that majority of user have a particularly color value in mind that they want, so entering the value manually is the easiest way.
I've tried to do make `iris` accept rgba value, but I couldn't do it.

**Comment by ViorelEremia** [comment]
@ivandotv Ivan please check with your pull request and my latest commit into master

**Comment by colinduwe** [comment]
This is still an issue after latest 2.7.7 tag. If the user brings focus to the input the default hex value turns to rgba. If the user places the cursor in the value and changes it the cursor is moved to the end of the value after the first character change event. It is not possible to set an opacity value.

**Comment by ivandotv** [comment]
@ViorelEremia testing in `2.7.7` the issues still exists.
Manually adding values regardless if rgba or hex it can't be done.

**Comment by ivandotv** [comment]
Not sure what exactly is going on with the code.
But the logical steps should be.
1. If the user is trying to inter code manually there is no need to update the picker itself, wait untill the field looses focus to parse the value.
2. If the value is wrong , revert to previous value (or default value)
3. If the value is wright, update picker UI to reflect the new color.

**Comment by colinduwe** [comment]
This is not fixed in 2.7.8. Same behavior as before. (I installed the update via WP Admin menu page but I assume I'm getting the same code as on Github)

**Comment by ViorelEremia** [comment]
@colinduwe  This will be in the next version, but you are free to download the next version from github

**Comment by ivandotv** [comment]
@ViorelEremia 
If was putting of solving this myself in hopes that somebody else will do it :)
Thank you for this. I will test it first thing Monday.

**Comment by YAKUTH** [comment]
I added jquery-minicolors plugin as an option type and @ViorelEremia solution didn't work for me.

**Comment by ivandotv** [comment]
@YAKUTH Can you share the code?

**Comment by YAKUTH** [comment]
@ivandotv here is the code https://github.com/YAKUTH/minicolors. Just insert into your theme folder under /theme-includes/includes/option-types/minicolors/ and call it from functions.php or hooks.php. It can be a good alternative until they fix it it.

**Comment by ivandotv** [comment]
@yakuthemes thanks
I will look at it later today
