### ISSUE TITLE
How to show N-posts on a page created in unyson?

### ISSUE THREAD

**Issue by Alecto** [ThemeFuse/Unyson#2856]
I want to show, for example, 10 records in a section on a unyson page.
But, I dont see the built-in shortcodes for this.
Will the standard PHP WordPress functionality work in a custom shortcode?
Or where can I find the documentation describing the output of the posts on the unyson page?

Thanks for help.

**Comment by andronic90** [comment]
Hi,

you can create a custom shortcode "Latest Posts" and in view.php write a custom query and get the latest "N"-posts.

**Comment by Alecto** [comment]
I understand, thanks a lot for the advice!
