### ISSUE TITLE
Special heading and text over backgroud parallax or video

### ISSUE THREAD

**Issue by ro-nin** [ThemeFuse/Unyson#2857]
Is it possible to have a section with a background parallax effect (or youtube playback) and write some text over it? When i set a section with background and then add some text in the same, i can see the background being place in front of the text

**Comment by hlaporthein** [comment]
The two simple ways that I know, one is overwriting default section and another way is creating an new element and customize that as you wish. Here is a [useful link](http://manual.unyson.io/en/latest/extension/shortcodes/#overwriting-shortcodes) that could help you for those two method.
