### ISSUE TITLE
Visual Editor Malfunctioning

### ISSUE THREAD

**Issue by ginazanuto** [ThemeFuse/Unyson#2858]
Visual editor is not loading or saving properly. When I try to save/update, it thinks I am leaving the website (closing the browser) and does not save any of my content, returning to a completely blank page.

Backend monitor shows multiple plugin errors.

![error example](https://user-images.githubusercontent.com/31667659/30076139-38fc4872-9235-11e7-838c-e05a3973bc2d.png)

**Comment by nwillimek** [comment]
I've had the same issue.

I updated to WordPress 4.8.1, WP showed no content in content builder.
So I deleted the theme folder via ftp, downloaded the latest version on github, uploaded it, and now it seems to work again.

**Comment by ginazanuto** [comment]
Hi nwillimek! Thanks for responding! We sort of simulated this already by refreshing the permalink cache and deactivating/reactivating it, and that did not fix the problem. Have re-downloaded the Unyson master version from here and will do what you described manually. Thanks again!

**Comment by ViorelEremia** [comment]
It seems to be an error in js, check your console and try - https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242

**Comment by ViorelEremia** [comment]
Try to change max_input_vars in php.ini or .htaccess this should help.

**Comment by ginazanuto** [comment]
Hey Viorel,

I tried the plugin you provided in another thread prior to speaking with you. It did not work. As far as the max_input - we have someone from the theme development looking into the site now. Will let you know what they find. Thanks again!

**Comment by ViorelEremia** [comment]
@ginazanuto I'm very interested in this issue drop me some temporary credentials so I can detect easier this problem.

**Comment by ginazanuto** [comment]
@ViorelEremia  We have someone on the theme development team in there now (WP-MultiPurpose). I was thinking it was probably not a good idea to have multiple people working on the same site from different organizations at once?

**Comment by ViorelEremia** [comment]
Okay, I fight for this plugin, to make this plugin as good as possible, let me now ifit's something for me.
Thank you for quick answer.
