### ISSUE TITLE
Content elements customization

### ISSUE THREAD

**Issue by marcingoralczyk** [ThemeFuse/Unyson#2859]
Hi,
I'm trying to customize the "team" element. (carousel with team -> image, title, work hours, and **button**). 
I need to change name of the button. I was looking for answer yesterday about one hour, and nothing. Maybe someone can guide me step by step how to change button "Read Profile" to custom text.

**Comment by hlaporthein** [comment]
It would be great if you overwrite default team elements. If you overwrite, you could customize it as wish. Here is how you could [overwrite on content elements.](http://manual.unyson.io/en/latest/extension/shortcodes/#overwriting-shortcodes)

**Comment by marcingoralczyk** [comment]
Thank you, I was red about this few times yesterday... and but "cogs' in my brain stuck :). I made some changes right now. 
Thanks again

In the same way (different shortcode folder etc.) will I be able to add more icons?

**Comment by hlaporthein** [comment]
Hi @marcingoralczyk , Sure, you could add as much as you would like to. Please close if it could solve you.
