### ISSUE TITLE
Dropdown menus not working

### ISSUE THREAD

**Issue by mathewacreman** [ThemeFuse/Unyson#2860]
Hi,

I'm using unyson on my WordPress site and am having issues with the dropdown menus (change font / change font colour) not expanding when I click on them. I've tried reinstalling WordPress and deactivating and reactivating the unyson plugin.

Do you have any advice on resolving this?

Many Thanks

**Comment by hlaporthein** [comment]
Hello @mathewacreman , I think that it is not unyson plugin problem. Make sure that you understand wordpress [wp_nav_menu](https://developer.wordpress.org/reference/functions/wp_nav_menu/) function well. If you use unyson mega menu, please read [it documentation in here](http://manual.unyson.io/en/latest/extension/megamenu/index.html#content). Good luck in your code. 

If the above solutions doesn't work, you would need to show your site link to be able to help you more.

**Comment by ViorelEremia** [comment]
Give more details some screenshots and check your console for errors.

**Comment by ivandotv** [comment]
Is this the problem?
   [wp-editor tools select z-index low for options popup #2732](#2732)

**Comment by ecksite** [comment]
@invadotv: your link reference is broken. Thats the right link
[https://github.com/ThemeFuse/Unyson/issues/2732](https://github.com/ThemeFuse/Unyson/issues/2732)
