### ISSUE TITLE
Bug multi-select option type is no longer working in custom post type

### ISSUE THREAD

**Issue by hlaporthein** [ThemeFuse/Unyson#2862]
I used multi-select option with custom post type, it was ok before but after updating latest unyson version. It is not working anymore. I also tested with unyson scratch theme. It doesn't work either. **Has that code deprecated?** Here is below code that worked fine before I upgrade latest version.

```
    'suggested_items' => array(
        'label'         => __('Suggested Tours', CO_THEME_LANG),
        'type'       => 'multi-select',
        'population' => 'posts',
        'source'     => 'tours',
        'desc'          => __('Enter tour title to show the site visitors other tours.', CO_THEME_LANG),
    ),
```

**Comment by hlaporthein** [comment]
Hello @moldcraft , I found why it is not working, 

In unyson plugin **class-fw-option-type-multi-select.php** file. I found two errors in that file. One is line number 75 **query_posts functions** 

```
$ids =  wp_list_pluck($wpdb->get_results(
	$prepare
		? $wpdb->prepare($sql, $prepare)
		: $sql,
	ARRAY_A
), 'ID');
//the return ids are string.
```
I think we need to make sure that ids array value are integer or not. So, I checked ids is integer if not, I set it to integer.

```
if ( !empty($ids) ) {
	foreach( $ids as $id ) {
		$ids_int[] = ( is_int($id) ) ? $id :  (int) $id;
	}
	$ids = $ids_int;
}
```

Another problem, **get_posts function** in line number 119 in that class-fw-option-type-multi-select.php file. I think we would need to change **post_type => 'any'** to specific custom post type. That's why suggestion is not coming out in autocomplete. I created an example function why **post_type => 'any'** cannot work. Check below, please

```
function post_type_tester() {

	$query = new WP_Query( array(
		'post_type'      => 'any',
		'post__in'       => array(448,449, 450, 451, 452, 453, 454),
		'posts_per_page' => 10,
		'fields'         => 'ids'
	) );
d($query->get_posts());


}
add_action('init', 'post_type_tester', 999);
//it would return empty. so, we would need to define specific custom post type.
```

Please review it, Thank you. Have a great day in codes

**Comment by ivandotv** [comment]
@hlaporthein 
Why not make a pull request?

**Comment by ViorelEremia** [comment]
@hlaporthein please test if everything is fine

**Comment by hlaporthein** [comment]
Hello @ivandotv , I made a pull request please check it. #2873

**Comment by ViorelEremia** [comment]
Hi @hlaporthein I have tried to do this, please test me https://github.com/ThemeFuse/Unyson/commit/302f5a5fdf8156fdd8b6983763d5502909634506

**Comment by hlaporthein** [comment]
Found the error. When we register **custom post type**, don't set **'exclude_from_search' => true**. If you set it true, it can't search in **WP_Query** with ** post_type => 'any' arguments. Thanks @ViorelEremia .
