### ISSUE TITLE
Can´t see content inside 

### ISSUE THREAD

**Issue by koloro** [ThemeFuse/Unyson#2865]
Hello guys,
I´m working in a theme "flavor" all good but just now can´t see the content edit inside each page. The website looks fine but when tried to change something in the panel control of each page nothing appear.

**Comment by ViorelEremia** [comment]
Try to update extensions after try this : https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242

**Comment by khanhcu** [comment]
I also have the same problem. My Unyson version is fully updated but I cant still see any content from edit page

**Comment by koloro** [comment]
Hi, I uninstall the plugin Unyson and re install, and later add plugin
Unyson and solve the problem!






*Pablo Medina U. */ Director Ejecutivo

  pablo.medina@koloro.cl /   + 569 6604 8859 <+56966048859>


  www.koloro.cl
  Of.: 2 2672 8293 <(2)%202672%208293>
<https://www.facebook.com/koloro.cl>   <https://cl.pinterest.com/juutkah/>


2017-09-12 16:31 GMT-03:00 khanhcu <notifications@github.com>:
