### ISSUE TITLE
Not getting templates

### ISSUE THREAD

**Issue by Tott3** [ThemeFuse/Unyson#2866]
I'm trying to get this to work, I got a fresh WP install. I installed the plugin and all the extensions. However when making a new page, I can't chose "Homepage (Unyson Builder)" template as in your video. I also downloaded the Scratch theme and it looks all weird, like a really old plain HTML page.

**Comment by ViorelEremia** [comment]
Scratch theme it works well for all and what video. Please provide more more details, so we can see where you are wrong.

**Comment by Tott3** [comment]
I noticed now that when I'm trying to upload the Zip instead of using the file explorer, it says that the stylesheet.css is missing.

**Comment by ViorelEremia** [comment]
What you upload entire folder from github? You need to upload only scratch-parent folder or scratch-child depends on what you want to do. Read this https://codex.wordpress.org/Theme_Development

**Comment by Tott3** [comment]
I've tried upload the entire folder, as well as only the parent/child folders alone.

**Comment by ViorelEremia** [comment]
Again I tested both parent/child theme everything is fine: create a zip from scratch-parent, increase upload_max_size in php.ini, install theme via admin dashbord. Scrathes theme are created according to wordpress standards with the purpose for developers can get started more easily with Unyson don't think you're gonna find a premium design etc.
