### ISSUE TITLE
"Latest posts" column shows two instead of three

### ISSUE THREAD

**Issue by fasonera** [ThemeFuse/Unyson#2867]
A strange thing happend on my Unyson site with The Core-theme, and I can´t figure out what.

When I moved my site from the test-space to the real hosting, the "latest post"-shortcode started act strange on this page http://www.lissmark.com/blogg/
The three-column postlists is suddenly two columns with lots of space to the right. But only when surfing from a Lenovo yoga 3 computer.

The columns works fine on the test-space http://jl.fasonera.se/blogg/ 

Please, does anyone know what could gone wrong. Why does the columns work as it should from most of the computers?

Best regards
Peter

**Comment by fasonera** [comment]
![image](https://user-images.githubusercontent.com/26872968/30182556-87ff1344-9417-11e7-93b2-19c1737f9c94.png)
This is how it looks like on the Lenovo yoga 3 computer

**Comment by andronic90** [comment]
Hi, please contact the theme support: https://support.themefuse.com/hc/en-us/requests/new .

I recommend to check the updates initial.
