### ISSUE TITLE
Builder empty although content available and visible

### ISSUE THREAD

**Issue by swietek** [ThemeFuse/Unyson#2869]
Hi,

a customer is asking me why he cannot edit his pages anymore. I have following issue. The website is display all content correctly. The content was set about 5 months ago and looks as it should. But when I try to edit a page, there are no builder items.

The div with class="builder-items fw-row fw-border-box-sizing ui-sortable" is completely empty. Also I don't get any error messages in the console. That's why its really strange for me.

I'm using WP Version 4.8.1 | Unyson 2.7.6

As there are no error messages and the builder is empty I don't know how to solve this issue. Tried it with newest Chrome & Safari. Appreciate your help.

Regards,
Konrad

**Comment by gigit95** [comment]
After updating the plugin go to https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/releases/tag/v1.6.14 download and unzip ... see the image
![dsfgvdsfxgvdsfx](https://user-images.githubusercontent.com/11440530/30235251-cd914338-9506-11e7-862f-534857714e76.JPG)

For me that worked.

**Comment by Ataurr** [comment]
Update your extensions. https://prnt.sc/giy40a

**Comment by swietek** [comment]
Thanks, it worked!
