### ISSUE TITLE
Built-in Extension: Slider

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson#287]
Hello there, 
I always get this error
<code>Fatal error: Call to a member function get_multimedia_types() on null in .../wp-content/plugins/unyson/framework/extensions/media/extensions/slider/class-fw-extension-slider.php on line 271</code> when I "Save" slide after adding a new one.
I have no idea why I get this. Any helps would be appreciated !
Thanks.

**Comment by llemurya** [comment]
@RayNguyen I want to ask If you make update of the Slider Extension?

**Comment by llemurya** [comment]
I think that you have an old version of the slider extension, please see at this [screen](http://static.md/cbcf87cc3f0d143ee3a8f1f95d0a936e#)
