### ISSUE TITLE
Incorrect img URL in src

### ISSUE THREAD

**Issue by helen31** [ThemeFuse/Unyson#2871]
Hello!
I'm using form page builder in Unyson. When I add section and then add media element Image and put update I get wrong URL path in html in img src, like img src="40" alt="40" width="300" height="200", insted of  img src="http://jurist.loc/wp-content/uploads/2017/09/84_main_new.1504178335-1.jpg" alt="" width="300" height="200".
Where should I look at to solve this problem?
I will be grateful if somebody helps me.

**Comment by ViorelEremia** [comment]
Hi Helen,
 mybe is a issue with our function fw_resize 40 in attr src i guess is attachement id but icant reproduce this can you give me credentials from your dashboard and ftp: viorel [ at ] themefuse [ dot ] com
