### ISSUE TITLE
Backups bug: Unknown column 'term_order' in 'field list'

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#2872]
Hello again

I wrote following ticket days ago https://github.com/ThemeFuse/Unyson/issues/2743 

and now this problem happens on my another themes when i updated demo content.

Any of my users can't install demo content due to this error: Failed to insert row from line 2047 into table _fwbk_wp_terms. Unknown column 'term_order' in 'field list'

Guys, please help, how can i resolve this? It worked fine in the past but doesn't work now at all

**Comment by WPJobs** [comment]
I have found the problem, it seems WP database structure from my old WP installation and new test installation differ. First database has a column "term_order" in "wp_terms" table, but new fresh WP installation doesn't have this column and this caused an error. I removed "term_order" column and re-created demo content install and now all works fine! 🥇

**Comment by danyj** [comment]
I was about to go cray. Thank you!

**Comment by danyj** [comment]
Another way to fi is install plugin Category Order and Taxonomy Terms Order again , activate it and than run the install. I had the plugin on when demo was created and it added the row to wp_terms.
