### ISSUE TITLE
Unyson Framework Full Content Backup Error

### ISSUE THREAD

**Issue by ispirLee25** [ThemeFuse/Unyson#2874]
4 dakika ago Files Restore: Timed out
27 dakika ago Archive Unzip: Timed out
7 saat ago Database restore: Failed insert row from line 19027
7 saat ago Archive Unzip: Timed out
2 hafta ago Files Restore: Timed out
3 hafta ago Archive Unzip: Timed out
3 hafta ago Archive Unzip: Timed out

**Comment by ViorelEremia** [comment]
Increase your timeout in php.ini
