### ISSUE TITLE
Current design of widgets not showing up on backend of wordpress, front end working fine

### ISSUE THREAD

**Issue by sheleenwithit** [ThemeFuse/Unyson#2875]
I have cleared cache, done everything suggested including downloading the plugin from the dropbox folder and updating the version of Unyson.

I need to change the images in the widgets ASAP- please assist!

**Comment by ViorelEremia** [comment]
Update extensions not only Unyson plugin.

**Comment by MiriShehu** [comment]
I have the same problem. I just updated all extensions, but it's still not working.

**Comment by ViorelEremia** [comment]
@MiriShehu https://github.com/ThemeFuse/Unyson/issues/2805

**Comment by ViorelEremia** [comment]
try: https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242
check if you don't have cache on server, installed plugins wordpress clear all caches
