### ISSUE TITLE
change directory in child theme

### ISSUE THREAD

**Issue by Basilou38** [ThemeFuse/Unyson#2876]
Hi,

I use the Woffice theme, it uses Unyson. I would like to customize the projects.js file located in the following directory :
`woffice/framework-customizations/extensions/woffice-projects/static/js/projects.js`

I would like to put the projects.js file "in my child theme to keep the file after updating the theme, but it does not work in child theme, I have created the following directory :
`woffice-child-theme/framework-customizations/extensions/woffice-projects/static/js/projects.js`

Is it possible to customize this file and put it in the child theme ? I would like it to work

**Comment by gigit95** [comment]
I'm not sure for the JS file, but for shortcodes it works. I think it ll work for the js too. See the link...
http://manual.unyson.io/en/latest/extension/shortcodes/#overwriting-shortcodes
Just cut and paste your framework-customizations folder in the child-theme folder and try to do some modifications.

**Comment by Basilou38** [comment]
Si tu parle Français je suis preneur :-)

I do not understand your answer, sorry I do not speak English, I use google translation to write (I'm French)

I would like to modify the file projects.js because the calendar is not in French, I have to replace a piece of code by this piece of code :

`	//DATEPICKER EN FR :
	$.fn.datepicker.dates['fr'] = {
        days: ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
        daysShort: ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
        daysMin: ["d", "l", "ma", "me", "j", "v", "s"],
        months: ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
        monthsShort: ["janv.", "févr.", "mars", "avril", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."],
        today: "Aujourd'hui",
        monthsTitle: "Mois",
        clear: "Effacer",
        weekStart: 1,
        format: "dd/mm/yyyy"
    };
    $('.row .datepicker').datepicker({
        format: 'dd-mm-yyyy',
        todayHighlight: true,
        clearBtn: true,
        orientation: 'bottom',
        language: 'fr'
    });`

I do not want to put the folder "woffice-projects" in my child theme because the developer of Woffice often update, it will be painful to modify the files, there is a lot of file in the folder "woffice-projects"

I would like to put only the file modify projects.js in my child theme.

**Comment by gigit95** [comment]
Oui, je parle un peu )) .
Comme je suis un débutant, peut être je n'ai pas de raison, mais ne devais pas tu avoir la structure suivante ... 
( framework-customizations/extensions/shortcodes/shortcodes/calendar/static/js/ tes js ici ) pour modifier le calendar???
Je sais que pour modifier les shortcodes il faut avoir cette structure-là. 
A propos, sur mon site le calendrier est traduit par wordpress ...
![gfvbdfgvdfg](https://user-images.githubusercontent.com/11440530/30340309-625fefb2-97f2-11e7-8782-741d279ee9a3.JPG)

Et si tu mets tes fichiers dans le dossier child-theme, normalement ils ne sont pas affectés par les mises à jour ou je n'ai rien compris sur le fonctionnement des child-theme. Ne me juge pas sévèrement, je ne suis qu'un débutant et j'essaie à t'aider comme je peux.

**Comment by gigit95** [comment]
Je viens d'essayer de modifier les shortcodes dans le dossier framework-customizations, tout fonctionne sauf le calendar. Rien ne marche, je ne sais pas pourquoi. J'ai réussi de modifier en ajoutant des fonctionnements les: section, icon-box, media-image etc, mais ce calendar ne veut pas. Désolé.

**Comment by 2Fwebd** [comment]
Hello, 

Woffice dev here, question is simply how to override a simple extension file from a child theme. 

Like
**theme/framework-customizations/extensions/foo/static/js/bar.js**

Would be ideally
**theme-child/framework-customizations/extensions/foo/static/js/bar.js**

Just looking for some clarifications here :)

**Comment by ViorelEremia** [comment]
it should be work, make sure you created child theme [correctly ](https://codex.wordpress.org/Child_Themes) and active.
If extension use to include files js something like that:
`fw()->extensions->get( 'extensionName' )->locate_js_URI( 'bar.js' );
//or
fw_ext( 'extensionName' )->get_uri( '/static/js/bar.js' );`
I don't have this theme butit should be work
