### ISSUE TITLE
noindex nofollow

### ISSUE THREAD

**Issue by Mosmuving** [ThemeFuse/Unyson#2879]
Hello! How in the jungle can you close categories, articles from indexing?

**Comment by ViorelEremia** [comment]
You use seo extension and you want to remove some archive pages, articles from indexing?

**Comment by Mosmuving** [comment]
Yes. How to close pages from the robot, so that it is not indexed

**Comment by ViorelEremia** [comment]
Settigns from seo extension tab sitemap does not help you?

**Comment by Mosmuving** [comment]
Unfortunately no. The code on the page is not listed. It's not just

**Comment by Mosmuving** [comment]
It should be like this. There is a plugin yoast
![default](https://user-images.githubusercontent.com/31875690/30326852-8cb40ad4-97d2-11e7-8a3f-2d855a55a055.png)

**Comment by ViorelEremia** [comment]
You use multisite installation?

**Comment by Mosmuving** [comment]
How to understand? can be in more detail please.

**Comment by ViorelEremia** [comment]
@Mosmuving Try to add this line in your seo extension: https://github.com/ThemeFuse/Unyson-SEO-Extension/commit/f171a79b7e322f24ae2d5c90969710d960ea80ce.
Let us know if everything is fine.

**Comment by Mosmuving** [comment]
Thank you for your support and attention. But with UNISON the site will not be made for CEO. I'll have to use Yoast SEO
![default](https://user-images.githubusercontent.com/31875690/30387581-9bc88552-98b5-11e7-90d1-60e654c6ee7c.png)
.

**Comment by Mosmuving** [comment]
![default](https://user-images.githubusercontent.com/31875690/30387732-2c4c2d54-98b6-11e7-8c13-d546db47a9a3.png)

![default](https://user-images.githubusercontent.com/31875690/30387713-16660f64-98b6-11e7-89aa-c39c7c51bb5c.png)
It was not working
![default](https://user-images.githubusercontent.com/31875690/30387679-fae10c6c-98b5-11e7-929e-b848ae99ac88.png)

**Comment by Mosmuving** [comment]
Thank you very much. You helped me very badly. Everything is working. Super!!!!
