### ISSUE TITLE
Theme icon set. 

### ISSUE THREAD

**Issue by marcingoralczyk** [ThemeFuse/Unyson#2880]
Hello, half of the day I'm fighting with icons for Icon shordcode and icon-box shortcode. 
Right now I just added to existing function with icon set 5th font style. 

And now, I can see it in icon-box labet, I can pick one of my icons -> save -> update changes.

But when I refresh site, nothing happend.... I can see new classes of my new icons, but they are empty. There is no :before pseudo element etc. just class and nothing else... 

Maybe I miss something?
I make changes only to function.php file, new code to function with $sets['fw-icon'] = 

(My icons are visible in choose label)

**Comment by ViorelEremia** [comment]
How did you rewrite it? if is empty when file css is not loaded. Give more details.
