### ISSUE TITLE
Import/Load Settings

### ISSUE THREAD

**Issue by PalThemes** [ThemeFuse/Unyson#2882]
First, sorry if this topic has been discussed before, but i've search for this topic and I can't find it.

I have one question about Theme Settings.
Is it possible to import or load settings for Theme Settings?
Because, when I create a theme with multiple demos, I just can recomend the buyer to install demo content if they wanna make their website looks like my demo website. And the problem is, when they installs demo content, they will lost their current posts and even all old datas on their website.
So, how can I create an option on theme settings to load or import theme settings? So this option works just like a "preset".

Thank you.

**Comment by danyj** [comment]
there is no other way but to create own import/export functionality

https://github.com/ThemeFuse/Unyson/issues/2004

**Comment by PalThemes** [comment]
@danyj nice, I will try this. Thank you brother :)
