### ISSUE TITLE
Repeater fields

### ISSUE THREAD

**Issue by psics** [ThemeFuse/Unyson#2884]
Hi,
How can I create repeater custom fields? And how I can get it?

**Comment by ViorelEremia** [comment]
http://manual.unyson.io/en/latest/options/built-in/introduction.html
See:
http://manual.unyson.io/en/latest/options/built-in/addable-option.html
I understand you correctly

**Comment by psics** [comment]
Yes, thanks. I don't want open new Issue. Can you tell me - how I can add a custom field with a number? Input[type=number]. And after sort by this field in wp_query?

**Comment by ViorelEremia** [comment]
You can't add a type number but you can create your option type: http://manual.unyson.io/en/latest/options/create-option-type.html#content or you can use option type text: http://manual.unyson.io/en/latest/options/built-in/text.html
 and get it depends on where you add it read carefully the documentation here are functions to extract options: http://manual.unyson.io/en/latest/helpers/php.html#content

**Comment by psics** [comment]
Thanks for the help. But you don't understand me.
For example, I have custom field - price. I must filter posts by this field (from 100 to 200 $). How can I get filtered posts? If I use wp_query `'meta_query' => array(
	'book_color' => array(
		'key'     => 'price',
		'value'   => array(100, 200),
		'compare' => 'BETWEEN',
	),
),`
