### ISSUE TITLE
Filter posts by custom fields

### ISSUE THREAD

**Issue by psics** [ThemeFuse/Unyson#2885]
I must filter posts by this field (from 100 to 200 $). How can I get filtered posts? If I use wp_query 'meta_query' => array( 'book_color' => array( 'key' => 'price', 'value' => array(100, 200), 'compare' => 'BETWEEN', ), ),

`			'price'                      => array(
				'label' => __( 'Price', 'unyson' ),
				'type'  => 'text',
				'value' => '',
				),`

**Comment by ViorelEremia** [comment]
add option in \framework-customizations\theme\options\posts\post.php :
`$options = array(
	'box_id' => array(
		'title'   => __( 'Box Title', '{domain}' ),
		'attr'    => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
		'type'    => 'box',
		'options' => array(
			'price' => array(
				'type'  => 'text',
				'value' => 5,
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __('Label', '{domain}'),
				'fw-storage' => array(
					'type'      => 'post-meta',
					'post-meta' => 'price',
				)
			),
			'testone' => array(
				'type'  => 'text',
				'value' => 5,
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __('Test one', '{domain}'),
			)
		)
	)
);`

Extract posts: 
`add_filter( 'after_setup_theme', function() {
	$query = new WP_Query( array(
		'post_type'  => array( 'post' ),
		'meta_query' => array(
			array(
				'key'     => 'price',
				'value'   => array( 10, 20 ),
				'type'    => 'numeric',
				'compare' => 'BETWEEN'
			)
		)
	) );
	fw_print( $query );
} );`
http://manual.unyson.io/en/latest/options/storage.html#content
