### ISSUE TITLE
PHP Zip module installed, still not working

### ISSUE THREAD

**Issue by kiskrtek** [ThemeFuse/Unyson#2890]
Hi, I receive the message "Oops, Unyson Backup requires PHP Zip module but it is not enabled on your server. "

But the ZIP and the lib are installed.
See here the php configuration of the server:
http://server.intronetx.hu/

Thanks!

**Comment by ViorelEremia** [comment]
I see Libzip is installed Libzip is required for zip archive to works but I don't see version of your zip, please contact your hosting. 
If zip module is enabled then it should show me the version.

**Comment by JustIrinel** [comment]
Hi there. @ViorelEremia I have the same problem. I activated Archive zip from cPanel (PHP ZIP) but the plugin told me the same message. Thanks

**Comment by ViorelEremia** [comment]
@JustIrinel if your site is on the cloudflare.com then try to clear the cache also if you have any cache then clear if that does not help then send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by Pransh20** [comment]
@JustIrinel Were you able to find the solution, I activated Archive zip from cPanel (PHP ZIP) but the plugin told me the same message

**Comment by MarioWagant** [comment]
Any solution for this? It's been some times from fist post and there is no solution. I bought  this template yesterday and I'm blocked :(
