### ISSUE TITLE
addable-option limits

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#2892]
Is it possible to set limit to the number of options that can be added to addable-options shortcode? This option is currently available for addable-popup and addable-box

**Comment by danyj** [comment]
http://manual.unyson.io/en/latest/options/built-in/addable-popup.html

browse manual

**Comment by mbtocalli** [comment]
Thanks danyj.
As I said, limit option is already available in addable-popup, but can it be included in addable-option? Maybe in a next release?

**Comment by ViorelEremia** [comment]
why do you need that?

**Comment by mbtocalli** [comment]
I want the user can choose what items to display in the blog archive (title, thumb, excerpt, author, etc) and in which specific order

**Comment by ViorelEremia** [comment]
@mbtocalli ok I will be glad to receive a pull request from you.

**Comment by mbtocalli** [comment]
I have no idea how to do that
