### ISSUE TITLE
HTML-Text Editor in combination with Page Builder

### ISSUE THREAD

**Issue by ecksite** [ThemeFuse/Unyson#2893]
WP Version 4.8.1
Unyson 2.7.6 (installed in theme, not by using the plugin)
Installed Plugins: none
Activated Unyson Extensions: Page Builder
Theme functions: minimal, also tried commenting out my theme functions or using a wp default theme

**Issue:**
After saving a post type while the (html)-editor is activated, the html editor seems to remain activated (tab activated), but the editors toolbar switches to wysiwyg tinyMCE-editor. 
Due to that, the quicktag buttons appear in the bottom left corner and the wp-editor tab is unactive, so you cant switch to tinymce (but tinyMCEs buttons are active). 

In order to get the default behaviour you got to switch to the html-editor, which then restores the correct view... After saving the post with html text editor is activated, the same happens... 

I made a video:
[https://youtu.be/tWrQjpdlDc0](https://youtu.be/tWrQjpdlDc0)

**EDIT:**
I changed my theme structure to require unyson as plugin (by using [tgmp](http://tgmpluginactivation.com)) instead of require it via theme path. Sadly this did not change anything...

**Comment by ViorelEremia** [comment]
Tgmp does not play any role here you have some special configurations which generates this, I can't reproduce. Check your console, enable debug, deactivate all plugins, try to inspect deeper to give us more information, otherwise, we will not be able to help you

**Comment by ecksite** [comment]
Thanks for your fast reply.

As I said before, there is no plugin or theme issue I can tell you about.

To eliminate every influences, I made a completly new local wordpress installation (downloaded some minutes ago), activated debug mode, and installed unyson from the official wordpress plugin directory. 

Again I made a video, which shows the issue: [Youtube Video - blank installation](https://youtu.be/BrfcVG4-vHU)
There is **NO issue, showing up in console, at all.**..

information regarding my local maschine:
installed locally on my Apple MacBook Pro Mid 2015, Mac OS 10.12 by using MAMP:
MAMP version 4.1.1, PHP 5.6.30 (no Caching), MySQL 5.6.35, Database collation utf8_general_ci

Wordpress Version 4.8.1 language de-DE (German), no plugins (only the default aksimet & hello dolly plugins installed but not activated by default).

**Comment by ange007** [comment]
This problem is not solved yet?
In version 2.7.7 in case of reset in a character mode - the visual mode with the moved-down buttons of the text editor is displayed.

![_039](https://user-images.githubusercontent.com/2736539/31073809-32c9fdcc-a776-11e7-8375-6b9dd6a3b791.png)
