### ISSUE TITLE
Dropdown menu in text editor page builder element doesn't work

### ISSUE THREAD

**Issue by Jelena1** [ThemeFuse/Unyson#2894]
I have client who reported me this issue. 
Dropdown menu for h tag and font family doesn't work in text editor page builder element.

I'm not sure when this issue occurs, maybe it was there for a while but it is a huge issue for customers without html knowledge.

I checked with WP default theme activated and issue is still there.

Can you please help with this?

Thanks.

**Comment by rosasmk** [comment]
Correction, all the dropdown menus are broken, not only H tags and font family all of them are not working, the dropdown menus open beneath the lightbox so the user can not access them. also the page/post contents desappear when not using the page builder
video here:
https://www.youtube.com/watch?v=QauuFJSFko8

**Comment by ecksite** [comment]
this has been reported in [https://github.com/ThemeFuse/Unyson/issues/2732](https://github.com/ThemeFuse/Unyson/issues/2732)

at the moment there is a workaround: see [https://github.com/ThemeFuse/Unyson/issues/2732#issuecomment-323322812](https://github.com/ThemeFuse/Unyson/issues/2732#issuecomment-323322812)

**Comment by rosasmk** [comment]
I just pasted this code in aditional CSS and did not work:

.mce-container.mce-panel.mce-menu,
.mce-container.mce-panel.mce-popover{
 z-index:2000000!important; 
}

**Comment by Jelena1** [comment]
please add that comment on github and ask plugin author for help. he will
login to your dashboard if needed to check that.

**Comment by rosasmk** [comment]
Sorry to hear that.

after all we purchased the theme from you and you have not given any support at all, you should be the one contacting the plugin author (you chose it for your theme) asking him for help and finally fixing the issue in your theme. I guess you are not that kind of developer. I will write a very detailed review of your performance.


R

**Comment by Jelena1** [comment]
it is damn sunday evening here! other developers wouldn't talk with you at
all during weekend

**Comment by rosasmk** [comment]
I used the css attributes to change z-index in the classes showed in a previous post:

.mce-container.mce-panel.mce-menu,
.mce-container.mce-panel.mce-popover{
z-index:2000000!important;
}

It didnt help the dropdowns still beneath the lightbox, wordpress version 4.8.1 unyson version 2.7.6

I know it is a sunday, I will wait for your kind response until a working day, cheers!!! :)

**Comment by Jelena1** [comment]
@ecksite sorry for @rosasmk and mine comments, we made mistake commenting here. 

Can you please check why workout that you suggested didn't work for my client @rosasmk? He can give you admin access to his site if needed. Thanks.

**Comment by ViorelEremia** [comment]
Today will be an update if you cannot wait for update it manually: https://github.com/ThemeFuse/Unyson/releases/tag/v2.7.7
