### ISSUE TITLE
Why the short codes of Unyson is hidden on home page?

### ISSUE THREAD

**Issue by mazedulislam27** [ThemeFuse/Unyson#2896]
When we created short code with Unyson, those were working fine. But suddenly all short codes are hidden from home page. Why?

**Comment by ViorelEremia** [comment]
More details please are hidden from home page where in admin or in front. Check if you have latest version of unyson and extensions, also try this plugin https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242

**Comment by mazedulislam27** [comment]
Oh! I forgot to mention. It is hidden from admin.

**Comment by ViorelEremia** [comment]
Try to update extension and clear all caches.

**Comment by mazedulislam27** [comment]
Thank you so.................. much.......... it works. 👍
