### ISSUE TITLE
In wordpress folders, where the backups that I do with unyson are stored

### ISSUE THREAD

**Issue by AGCOPA** [ThemeFuse/Unyson#2897]
Hello. One quetion. In wordpress folders, where the backups that I do with unyson are stored

**Comment by Ataurr** [comment]
`wp-content/uploads/fw-backup`

**Comment by charlesraj** [comment]
How i can restore the the unyson backup. when try to restore " 1 min ago Content restore " as a result activity log showing this message but there is no effect on website.

**Comment by nicholas0g** [comment]
@apollygon did you find a way to restore database from json?
