### ISSUE TITLE
Street number is not showing on location picker

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#2898]
I'm using the location picker on some projects and only lately noticed that a specific location  (let's say: Amsterdam Arena) doesn't return the street number, which is important for a lot of locations that are added.

When looking at the result from the same location in Google Maps: Place autocomplete, there is a street number.

https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete

Is there a reason the street number isn't added to the location picker? Or is this a bug?

**Comment by ViorelEremia** [comment]
If I understood you correctly in my end the autocomplete works the same on both in builder and on google https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete
![google](https://user-images.githubusercontent.com/28967378/30650102-ba4d9b5a-9e2a-11e7-8dce-ed7b257363d9.jpg)
![local](https://user-images.githubusercontent.com/28967378/30650103-ba7bcc96-9e2a-11e7-9642-3a7a191e585c.jpg)

**Comment by noesteijver** [comment]
That's not what I meant. I was talking about the location picker option type.

Here is my situation:

![2017-09-21](https://user-images.githubusercontent.com/10668469/30689370-0ab01eba-9ec1-11e7-847b-2948710d2a28.png)

This is what Google gives back:

![2017-09-21 1](https://user-images.githubusercontent.com/10668469/30689445-3e167164-9ec1-11e7-85e7-242b981b11a0.png)

In the Google result, you see the house number. I don't see that when I use the location picker option type.

**Comment by noesteijver** [comment]
I'm still having issues with this. Locations that have a house number in Google Maps, show up in your location picker without the house number.

Is there a way to fix this?

**Comment by noesteijver** [comment]
I'll try and elaborate some more:

**Google Place Autocomplete**

![2018-02-28 2](https://user-images.githubusercontent.com/10668469/36791958-6e5f59c0-1c99-11e8-849b-7384bea93536.png)

![2018-02-28 3](https://user-images.githubusercontent.com/10668469/36791959-714dd788-1c99-11e8-85fc-ef74d2e9740e.png)

**Unyson option type: map**

![2018-02-28](https://user-images.githubusercontent.com/10668469/36791980-7dce57da-1c99-11e8-8a75-be116dde7a52.png)

![2018-02-28 1](https://user-images.githubusercontent.com/10668469/36791982-8010fdd6-1c99-11e8-8489-a5bff859aa71.png)

My conclusion: the Google Place Autocomplete is working fine. As you can see, the number (40) is given back when looking for 'Noeste IJver'. But when I search for 'Noeste IJver' in the map option type, the number isn't showing. Seems like this gets lost along the way between getting the results from Google and showing them in the map option.

Is this a known bug? Hopefully you can fix this soon!

Thanks in advance,
-Kevin

**Comment by ViorelEremia** [comment]
This is not a bug the option type map doesn't support infowindow you can see in autocomplete google demo html for infowindow:
```
 <div id="infowindow-content">
      <img src="" width="16" height="16" id="place-icon">
      <span id="place-name"  class="title"></span><br>
      <span id="place-address"></span>
    </div>
```
code that build the infowindow:
```
 infowindowContent.children['place-icon'].src = place.icon;
 infowindowContent.children['place-name'].textContent = place.name;
 infowindowContent.children['place-address'].textContent = address;
 infowindow.open(map, marker);
```
I think this is not important but it was not hard to do that so you can try the commit below. If you want to create your format adress you need to rewrite script.js I don't know how to do it. The function that buil address is ```option.getComputedLongAddress()``` from ```framework/includes/option-types/map/static/js/scripts.js```

**Comment by noesteijver** [comment]
When I try the code, I get an infowindow. But it doesn't give me the house number.

When I look at the updateFields() function in scripts.js, I see the variable current. When I look at this variable with console.log, I see that the house_number value is passed back. That's the thing I need!

Could you incorporate the house number in the map option type? Logically, it would be a separate field (or placed behind the address).

Hopefully you can help me out!
-Kevin

**Comment by ViorelEremia** [comment]
No, I can't add a separate field for house number because I need a migration action for all site that already has these implementations and also some devs rewrite the map script.js and now this field in their scripts is unknown etc. so that is not possible; try to rewrite this option type in your theme/extension here I can not help you anymore.
