### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson#2899]
![image](https://user-images.githubusercontent.com/5270333/30593859-b36c38c2-9d54-11e7-8b06-f45f35abad3f.png)

Hi!
There this thing in the console. The page builder is not showing up. Any ideas?

Using the latest Wp and Unyson version.

**Comment by ViorelEremia** [comment]
Try to see what is in jquery.qtip.min.js click on error in console first error I can't reproduce this

**Comment by dmbostan** [comment]
How do you guys minify the js files? It is a minification issue, I think.

http://prntscr.com/gnhcrl

**Comment by ViorelEremia** [comment]
who does that? by default qtip is minified, if you use a cache plugin check if it has options like exlude file
