### ISSUE TITLE
Customising column shortcode

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#290]
Hey guys,

I'm trying to find where to edit the column shortcodes so that I can add my own text field so that an edn user can add a custom class, but I can't find an options file to edit the existing,

Any help would be great.

Thanks!

**Comment by sergiubagrin** [comment]
> I'm trying to find where to edit the column shortcodes

You mean column options? https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/shortcodes/shortcodes/column/options.php

**Comment by klvmedia** [comment]
Ah how did I miss this??

Thank you!
