### ISSUE TITLE
Page Builder testimonials - no option for slider

### ISSUE THREAD

**Issue by amandamrosen** [ThemeFuse/Unyson#2901]
I'm wondering how can I get the testimonials to act as a slider in the visual page builder? I don't have that option, it seems. Is there a line of code I can add somewhere to accomplish this? We are not using Unyson framework - just the plugin for the page builder. I've attached a screenshot and you can see my only options are to add testimonials (and to add a title). Within the testimonials, I can specify all the content but there's no option anywhere to make the testimonial a slider which is what I want it to do. 

Any help is greatly appreciated!
![screen shot 2017-09-19 at 11 30 23 am](https://user-images.githubusercontent.com/32103712/30600656-0ccbf88e-9d2e-11e7-838e-35ea8f1b27e8.png)

**Comment by ViorelEremia** [comment]
By default testimonials appear as simple carousel 
![screen](https://user-images.githubusercontent.com/28967378/30635134-289ec466-9dfa-11e7-9937-62b4f8db08a1.png).
Theme developer can overwrite it from theme or child theme. If is overwriteen when you can't use the default behavior. So there is no line of code how you think but if you want to use a specific slider you need some knowledge of html,css, js, php.
