### ISSUE TITLE
Bug with the last version (2.7.7) ?

### ISSUE THREAD

**Issue by agalvaire** [ThemeFuse/Unyson#2902]
Hi,
My website use Unison framework v2.6.15 and all works done.
But after update with the v2.7.7, all sections desepears on the back-office page ?!
Is it normal ? :/
![capture](https://user-images.githubusercontent.com/32121845/30629900-7d2bcf18-9dde-11e7-9424-4f70d1f22290.jpg)

Anthony

**Comment by ViorelEremia** [comment]
Send me the credentials from your site: viorel [ at ] themefuse [ dot ] com

**Comment by claudiozappi** [comment]
Same problem!

**Comment by ViorelEremia** [comment]
viorel [ at ] themefuse [ dot ] com - I can't see from images what is the problem

**Comment by ViorelEremia** [comment]
Please update Unyson extensions not only extensions.

**Comment by claudiozappi** [comment]
??

Claudio Zappi
web designer

**Comment by ViorelEremia** [comment]
Update Extensions not only Unyson plugin.

**Comment by agalvaire** [comment]
Hi,
What do you mean ? ... i juste have the plugin Unison, no other extension from Unison.
(My theme : Woffice V: 1.8.5)
Anthony

**Comment by ViorelEremia** [comment]
Unyson has extensions, page builder is one of theme.
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by agalvaire** [comment]
So,
I just have this from Unyson:
![capture-2](https://user-images.githubusercontent.com/32121845/30633685-e1bb47ca-9dec-11e7-903d-231522f56c24.jpg)
Anthony

**Comment by wpthemes786** [comment]
Try to deactivate the plugin and then delete the plugin.
Then click on Add new button and search unyson plugin.
Install and activate plugin it will resolve your issue.

**Comment by JPain** [comment]
I did what @wpthemes786 suggested. I deactivated the Unyson plugin and deleted it. Then reinstalled it.
After checking the site after reinstall, it looked completely messed up until I saw a prompt from Unyson that said 'Your site could benefit by installing these recommended extensions'. I let it do that, and it now all works.

Uninstalling the plugin is a risky move by the looks of it, but it worked for me.

**Comment by danyj** [comment]
> I let it do that, and it now all works

in short ,   updated plugin , did not update extensions

**Comment by JPain** [comment]
@danyj You're not wrong. However, I tried to find how to update the extensions but I couldn't see how. Can you explain how to do that?

**Comment by danyj** [comment]
next time as soon as you update plugin , go back to updates and look at the bottom of the page for button, after themes , to update unyson extensions
