### ISSUE TITLE
fw_resize + WP 4.4 responsive images

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#2904]
I'm trying to use fw-resize function to crop my images and get a reponsive image as supported in WP 4.4, served with srcset and sizes markup. Is that possible?
I'm trying this code:
`<img src="<?php echo fw_resize( wp_get_attachment_url( get_post_thumbnail_id() ), 1110, 354, true ); ?>"  srcset="<?php echo esc_attr( $srcset ); ?>" sizes="<?php echo esc_attr( $sizes ); ?>" />`
but I'm not getting the cropped image

**Comment by ViorelEremia** [comment]
At the moment this is not possibile but you can made something like that: 
`$attachmentId = get_post_thumbnail_id();
$imgMeta      = wp_get_attachment_metadata( $attachmentId );
$width        = 1110;
$height       = 354;
$attrs        = array(
	'src' => fw_resize( wp_get_attachment_url( $attachmentId ), $width, $height, true ),
	'alt' => get_post_meta( $attachmentId, '_wp_attachment_image_alt', true )
);

if ( is_array( $imgMeta ) ) {
	$sizeArr = array( absint( $width ), absint( $height ) );
	$attrs['srcset']  = wp_calculate_image_srcset( $sizeArr, $src, $imgMeta, $attachmentId );
	$attrs['sizes']   = wp_calculate_image_sizes( $sizeArr, $src, $imgMeta, $attachmentId );
}

echo fw_html_tag( 'img', $attrs );`
