### ISSUE TITLE
Cant remove RGBA color from box. version 2.7.7

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2906]
It's worked before but the last update I cant remove color. if I remove this auto add into RGBA color picker box.
Why I need this? I have Global RGBA picker for overlay in theme settings. I give this option to change page also. Now I tried to remove this from the page. so if any color selected from theme settings this color will show in front.

Here is the issue https://gyazo.com/75029d234dedbb885f3c8630e29e2cf8

**Comment by ivandotv** [comment]
This is a know issue
[RGBA color picker - can't add value manually](https://github.com/ThemeFuse/Unyson/issues/2855)
