### ISSUE TITLE
Why messed up the icon-v2 of Unyson?

### ISSUE THREAD

**Issue by mazedulislam27** [ThemeFuse/Unyson#2907]
icon-v2 is messed up in my created short code as this: https://prnt.sc/gp0da9. Why? I mention here I'm using the update version of Unyson.

**Comment by mazedulislam27** [comment]
Hey, I found the reason of messed up. Please check this link: https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon-v2/static/css/picker.css  and see the line number 306 and please give up the comment up for " height : 65px; " so that messed up will fix. :D

**Comment by saddamwp** [comment]
hello

**Comment by andreiglingeanu** [comment]
Hey @mazedulislam27! Can you show a before/after screenshot of that small change? If you could package it in a pull request that would be great.

**Comment by sergiu-radu** [comment]
Hey @mazedulislam27 in which browser are you encountering this bug?
