### ISSUE TITLE
Can't add specific class for shortcodes who's already registered/exists

### ISSUE THREAD

**Issue by sawwd** [ThemeFuse/Unyson#2908]
I want to add a class for media-image shortcode just for the sake of readability and specificity of my code (in my case), but I can't do that. So, why?

`framework-customizations/extensions/shortcodes/shortcodes/media-image/`

```
├── class-fw-shortcode-media-image.php.
├── config.php
├── options.php
├── static
│   ├── css
│   │   └── styles.css
│   ├── img
│   │   └── page_builder.png
│   └── js
│       ├── scripts.js
├── static.php
└── views
    └── view.php
```

From what I've see in the code, Unyson loads only classes who are in the `framewok `context, but why? Why Unyson doesn't load them in reverse order (`child/parent/framework`)? Is there a good reason?

I think the right approach here is to let the developer to do what it needs to do (create for them a free world):

1. Let them add class for shortcodes who's already registered;
2. Let them overwrite classes who's registered;
3. Let them write clean, organized code:

Imagine I want to overwrite `_render()` method in `framework/extensions/shortcodes/shortcodes/map/class-fw-shortcode-map.php` who can I do that? Because I don't want to create another shortcode just for the sake of a little change, I don't want my code project to smell, I want to maintain it DRY.

**Comment by danyj** [comment]
NIce one! Should have had this long ago
