### ISSUE TITLE
Please also add the possibility to have developer added fonts.

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson#291]
Please also add the possibility to have developer added fonts.

basic configuration

font_lib { fontawesome, unyson, dev_added }
font_src { link to font css } //for dev added only

PS: I'ma gonna terrorize you all :D

https://trello.com/c/Vz7ktAg9/57-themefuse-icon-font-to-unyson

**Comment by NazarkinRoman** [comment]
Nice feature. +1

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/371
