### ISSUE TITLE
Override Column .... styles.css

### ISSUE THREAD

**Issue by gigit95** [ThemeFuse/Unyson#2911]
I would like to override ...
MY_THEME\framework-customizations\extensions\shortcodes\shortcodes\column\includes\page-builder-column-item\static\css\styles.css, but can't find any useful information about it.

**Comment by steve-themefuse** [comment]
Contact your theme's author or use a child theme.

**Comment by gigit95** [comment]
It's "Column" shortcode from Unyson, what for contact theme's author?

**Comment by ViorelEremia** [comment]
you cant rewrite this file by path try to use like that: 
`add_action( 'admin_enqueue_scripts', function() {
	wp_dequeue_style( 'page-builder_item_type_column' );
} );`

**Comment by gigit95** [comment]
@ViorelEremia Sorry, I didn't explain correctly what I want to do.
**I want to use** 
MY_THEME\framework-customizations\extensions\shortcodes\shortcodes\column\includes\page-builder-column-item\static\css\styles.css
**Instead of**
wp-content\ **plugins** \ **unyson** \framework\extensions\shortcodes\shortcodes\column\includes\page-builder-column-item\static\css\styles.css

It's for modifications of a copy of "original" styles.css from unyson folder.

Will your code do the job?

**Comment by ViorelEremia** [comment]
try:
`add_action( 'admin_enqueue_scripts', function() {
	wp_dequeue_style( 'page-builder_item_type_column' );
	//wp_deregister_style( 'page-builder_item_type_column' );
	wp_enqueue_style( 'page-builder_item_type_column', 'MY_THEME\framework-customizations\extensions\shortcodes\shortcodes\column\includes\page-builder-column-item\static\css\styles.css' );
} );`

**Comment by gigit95** [comment]
Perfect ! Thank you ! 
And a little additional question : did I understand correctly, that I can do the same with all others "css" from shortcodes?

**Comment by ViorelEremia** [comment]
above code works :) ? Yes, you can but for the others shortcodes you can use method to override by paths" \framework\extensions\shortcodes\shortcodes\buton\blabla" Column has another structure maybe in the future I will inspect this issue deeper

**Comment by gigit95** [comment]
```
add_action( 'admin_enqueue_scripts', function() { wp_dequeue_style( 'page-builder_item_type_column' ); 
wp_deregister_style( 'page-builder_item_type_column' ); 
wp_enqueue_style( 'page-builder_item_type_column', get_template_directory_uri() .'/framework-customizations/extensions/shortcodes/shortcodes/column/includes/page-builder-column-item/static/css/styles.css' ); } );
```
The code, if someone someday wants just copy paste :) . Thanks again @ViorelEremia .
