### ISSUE TITLE
Pages opening in "Default Editor", Visual Page Builder broken

### ISSUE THREAD

**Issue by ShaunaJ23** [ThemeFuse/Unyson#2912]
I purchased a Theme for a client, which included Unyson Visual Template Builder (Version 2.7.7). I built out the home page using the Visual Template Builder and it was working fine. I went back into to edit it and it started to load the Visual Template Editor and then switched to Default Editor. If I try and switch it back to the Visual Template Builder, all I get is a single text block (see screenshot). 

I've been thru other threads on this, but they all seem to be older threads and I am using newer versions of WP (WordPress 4.8.2 running Philanthropy Child theme.) and the plugin.

I have tried the add-google plugin recommendation, in another thread, deleted and re-added a newly downloaded version of Unyson, cleared my cache and disabled potentially conflicting plugins, to no avail.

![screenshot-adelesovertherainbowbaskets org-2017-09-25-14-01-36](https://user-images.githubusercontent.com/5587736/30828231-36101060-a1fa-11e7-8bd2-450562344dd1.png)

**Comment by steve-themefuse** [comment]
Hi, try restoring an older revision of the respective page, and for the future do not switch between the default WordPress editor and the visual page builder when the page is already published.

**Comment by ShaunaJ23** [comment]
I didn't switch it to the default editor, it did it automatically. I just tried to switch it back. I have tried restoring earlier versions and it does the same thing. I have reinstalled Unyson and made sure everything was updated. I've followed other similar threads and links provided - ie. https://wordpress.org/support/topic/important-support-is-on-github-not-here/, to no avail. This is really frustrating.

**Comment by ViorelEremia** [comment]
@ShaunaJ23 I know about this issue this is happened under certain conditions which I can't catch, can you remember what you did(the sequence of steps), each detail is important so I can reproduce on my side.

**Comment by ShaunaJ23** [comment]
Unfortunately, no. I was just editing my home page and it was all working fine. I went back in to edit mode and it started to load the page with the Visual Page Builder Template and then switched to Default Template, on it's own, when the page fully loaded. 
I have since rebuilt the page, as I have a client waiting for this.
