### ISSUE TITLE
Display metabox tabs into side

### ISSUE THREAD

**Issue by gonzela2006** [ThemeFuse/Unyson#2915]
Hello,

Thanks for this awesome extension :)

I have a question, Is it possible to display metabox tabs into side?

Thanks again

**Comment by ViorelEremia** [comment]
Try:
`'box_id' => array(
		'title'   => __( 'Box Title', '{domain}' ),
		'attr'    => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
		'type'    => 'box',
		'context' => 'side',
		'options' => array(
			'tab_id' => array(
				'type' => 'tab',
				'options' => array(
					'option_id'  => array( 'type' => 'text' ),
				),
				'title' => __('Tab Title', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
			),
			'tab_id_2' => array(
				'type' => 'tab',
				'options' => array(
					'option_id_2'  => array( 'type' => 'text' ),
				),
				'title' => __('Tab Title #2', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
			)
		)
	),`

**Comment by gonzela2006** [comment]
Sorry if not be accurate but I need to display the tabs into side like Theme Settings as you can see in the below image
![screenshot from 2017 09 28 14 57 23](https://user-images.githubusercontent.com/3768012/30967808-015eaf52-a466-11e7-808c-0020aeba23fd.png)

**Comment by ViorelEremia** [comment]
No, you can't only horizontally, but you cant rewrite them in theme see docs

**Comment by gonzela2006** [comment]
Thank you :)
