### ISSUE TITLE
Google map with wp_deregister_script('jquery')

### ISSUE THREAD

**Issue by pakiam** [ThemeFuse/Unyson#2916]
Hi, when I disable built-in jquery on frontend, Google map stop working.
How can I fix that ?

**Comment by steve-themefuse** [comment]
Hi,  why have you disabled the built-in jquery  in the first place?

**Comment by ViorelEremia** [comment]
Google map is depending on jquery see here: Unyson\framework\extensions\shortcodes\shortcodes\map\static.php used in Unyson\framework\extensions\shortcodes\shortcodes\map\static\js\scripts.js
you can do that but is not a easy way, first you need to overwrite shortcode map: http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content
you need to rewrite scripts.js in pure javasacript to initialize map. 
I do not know what you are building but I think you're doing something wrong if you deregister default wp jquery, I do not see any reasons to do this, if you use cdn use hooks to replace urls if you want latest version of jquery again use hooks to replace default path jquery with your jquery version.
