### ISSUE TITLE
Can't add a background image in sections

### ISSUE THREAD

**Issue by fitacrom** [ThemeFuse/Unyson#2917]
We can not add any background-image on sections. We have the posibility to add the image in the section setting, but definetely it is not working when we save the page and see the changes.

Anybody knows anything for this issue?

Thanks and best regards!

**Comment by steve-themefuse** [comment]
Hi,  have you tried testing this with a default WordPress theme or the Unyson scratch theme? If the issue does not happen on these themes, then the problem comes from the theme that you are using.
