### ISSUE TITLE
Unyson select type Question 

### ISSUE THREAD

**Issue by alaminsobuj** [ThemeFuse/Unyson#2918]
how to select single post category in Unyson theme option please help me . thanks a lot

**Comment by ViorelEremia** [comment]
you mean this: http://manual.unyson.io/en/latest/options/built-in/multi-select.html

**Comment by alaminsobuj** [comment]
No .

**Comment by alaminsobuj** [comment]
I need a single category.

**Comment by steve-themefuse** [comment]
Hi, please provide a few more details to what exactly are you referring to

**Comment by alaminsobuj** [comment]
![screenshot](https://user-images.githubusercontent.com/22912018/30920895-ec35a170-a3c6-11e7-93f7-e2e4b6f4a280.png)

**Comment by alaminsobuj** [comment]
![screenshot](https://user-images.githubusercontent.com/22912018/30920957-0eafa61a-a3c7-11e7-9b88-d8827baae2fe.png)

**Comment by alaminsobuj** [comment]
please i need quick help .

**Comment by ViorelEremia** [comment]
`'cat' => array(
				'type'  => 'select',
				'value' => 'choice-3',
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __('Label', '{domain}'),
				'desc'  => __('Description', '{domain}'),
				'help'  => __('Help tip', '{domain}'),
				'choices' => wp_list_pluck( get_terms( 'category' ), 'name', 'slug' )
			),`

**Comment by alaminsobuj** [comment]
Thank Your #ViorelEremia  Now working 
I'll show you how to output. If you had the output code

**Comment by ViorelEremia** [comment]
Please read unyson documentation: http://manual.unyson.io/en/latest/
`fw_get_db_settings_option( 'cat' )`
http://manual.unyson.io/en/latest/helpers/php.html#database

**Comment by alaminsobuj** [comment]
Thank u I got all solution
