### ISSUE TITLE
What is the way to get slider in front-end?

### ISSUE THREAD

**Issue by AminulBD** [ThemeFuse/Unyson#292]
Hi,

I've created a slider in with the slider unyson extension. Its working perfect when I'm adding slider with using page builder. But i want get slider in my php files without page builder.

Can you tell me how can i do this?

Thanks!

**Comment by thednp** [comment]
That is what you do in the front-end with your desired CSS/HTML framework. The UNYSON framework and it's extensions only manage options and values.

**Comment by llemurya** [comment]
@AminulBD yes you can do it. Please read the [documentation](http://manual.unyson.io/en/latest/extension/slider/index.html?highlight=slider#frontend-render).

**Comment by llemurya** [comment]
```php
\\ Important the first parameter is the slider post id, the second parameter is array with dimensions of the image if you want to resize images.
fw()->extensions->get('slider')->render_slider(10, array(
    'width'  => 300,
    'height' => 200
));
```
