### ISSUE TITLE
Unyson contact form - Send E-Mail confirmation email to sender?

### ISSUE THREAD

**Issue by LanceButters** [ThemeFuse/Unyson#2920]
Hey, I would like to know if it's possible to send a confirmation email to the sender.

**Comment by ViorelEremia** [comment]
Try:
`// Hook then message is sent successfully.
add_filter( 'fw:ext:contact-forms:sent', function( $entry_data ) {
	// The message is sent.
	// $entry_data contain all that you need, email filds etc
	//fw_print( $entry_data );
	// do stuff whith api compain services mailchimp api here https://github.com/drewm/mailchimp-api
	// https://developer.wordpress.org/reference/functions/wp_mail/
	die();
} );`

**Comment by LanceButters** [comment]
In which file should I add this?
