### ISSUE TITLE
Error: Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by sdondley** [ThemeFuse/Unyson#2922]
I upgraded to Wordpress 4.8.2. Things were a bit wonky (page editor wasn't displaying) after the upgrade. To try to correct, I upgraded the Unyson extensions which broke the site entirely with a white screen of death with the following error:

Cannot redeclare class OAuthException in /usr/share/php/OAuth.php on line 8

I deactivated all plugins as well as Unyson and then tried reactivating but got "Plugin could not be activated because it triggered a fatal error".

Can someone please offer some guidance on how to get this issue resolved? Thanks.

**Comment by sdondley** [comment]
For now I just blanked out the file below <?php ... }.I don't use twitter on the site.

**Comment by ViorelEremia** [comment]
This is from extension socials but i don't understand why, try to remove on your server folder: unyson/framework/extensions/social
or you can send me credentials from your ftp, admin to: viorel [ a ] themefuse [ dot ] com
