### ISSUE TITLE
Travis build failing on PHP7

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson#2924]
Hello,

Currently the Travis build is failing when [trying to run the tests on PHP7](https://travis-ci.org/ThemeFuse/Unyson/jobs/280306424). The problem here is with the support of PHP 5.2 from [Travis](https://docs.travis-ci.com/user/languages/php#PHP-5.2(.x)-and-5.3(.x)-support-is-available-on-Precise-only).

@ViorelEremia Could you try to investigate that a bit and fix the situation?

That's important because everyone is moving on from support PHP 5.2 and 5.3.

**Comment by ViorelEremia** [comment]
Ok, in the afternoon I'll take a look.

**Comment by andreiglingeanu** [comment]
It fails anyway on PHP 7: https://travis-ci.org/ThemeFuse/Unyson/builds/280403394?utm_source=github_status&utm_medium=notification

**Comment by ViorelEremia** [comment]
I forgot to link here the committees that solved the problem https://travis-ci.org/ThemeFuse/Unyson
