### ISSUE TITLE
Contact Form Test Connection generated an error

### ISSUE THREAD

**Issue by vinoddalvi** [ThemeFuse/Unyson#2927]
When we click on the "Send a test email" button in the contact form Mailer settings then the following javascript error is generated and the test email doesn't get sent.

Uncaught TypeError: Cannot read property 'split' of undefined

![screenshot 51](https://user-images.githubusercontent.com/5412913/30972599-a2416924-a488-11e7-92de-eab9178e8e82.png)

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson-Mailer-Extension/commit/93828a57b88d1f05394ae67bf6f74f6eed4d6235
or wait for the next update
