### ISSUE TITLE
calendar

### ISSUE THREAD

**Issue by DavidCastro91** [ThemeFuse/Unyson#2928]
Can someone help me translate calendars events into my country's pt-BR language? I do not know where to exchange file locale.

**Comment by gigit95** [comment]
In `plugins\unyson\framework\languages`
You can translate with POEDIT.
In POEDIT : create new translation=>open **fw.pot** => choose your langage => translate => save as pt-BR.po

**Comment by DavidCastro91** [comment]
I appreciate your help, unfortunately it's a bit difficult to understand what you wrote because I use the translator, I do not speak your language.

However I did find a workaround, in the file =>

Z: \site\wp-content\themes\philanthropy-parent\framework-customizations\extensions\shortcodes\shortcodes\calendar\ static.php

I changed the $ locale array and it worked right here, for example, the 'm8' => 'September' attribute I changed to my language and got 'm8' => 'September'.
gigit95 Do you understand what I did? if you have a better way, please explain to me, I did not understand much of what you wrote.

Thank you.

**Comment by gigit95** [comment]
Wordpres translates the site using language files ( ***.po  and ***.mo)
![dfgg](https://user-images.githubusercontent.com/11440530/31165079-ebbb6fd6-a8e9-11e7-9995-3b083736bf04.JPG)

And, **Unyson** does the same.
Unyson ones are located in `YouSite\wp-content\plugins\unyson\framework\languages`.
![dfgvdsggfgfg](https://user-images.githubusercontent.com/11440530/31166745-0e44abde-a8f0-11e7-8f16-38263b9e0da3.JPG)

So, if your wordpress uses a language, for example French, you should have fw-fr_FR.po and fw-fr_FR.mo
files in  `YouSite\wp-content\plugins\unyson\framework\languages`.

In you case that will be fw-pt_BR.po and fw-pt_BR.mo ...

Download and install PoEdit (it's free) next => ![rtyhrt](https://user-images.githubusercontent.com/11440530/31166971-d65bf88e-a8f0-11e7-9763-6bf07572dd8d.JPG)

next => ![rtyhrtyh](https://user-images.githubusercontent.com/11440530/31167001-eda9dd44-a8f0-11e7-83fe-9e0bc9cec128.JPG)

then => 
![sqfdsfg](https://user-images.githubusercontent.com/11440530/31167240-b1e4009a-a8f1-11e7-9683-e96a2c6c8621.JPG)

after => 
![regftsdrg](https://user-images.githubusercontent.com/11440530/31167275-d5c4ca80-a8f1-11e7-9b20-26a06ffb4f70.JPG)

AND .... Voilà

![fthfgh](https://user-images.githubusercontent.com/11440530/31167401-36a387e2-a8f2-11e7-9d80-4533918c0c5b.JPG)


I hope it's clear enough ;)
