### ISSUE TITLE
Adwords tracking wordpress

### ISSUE THREAD

**Issue by Ahruhn** [ThemeFuse/Unyson#2929]
Hi there,

I've been asked to add some tracking code after the "submit" button on my client's contact page. I've been given the below documentation however I can't find where this code should be added in the framework. Please can I have some guidance?

Thanks in advance,

Aaron

Form Button:

Below is the HTML for the button on your SubmitForm on URL:
https://thetileandbathroomwarehouse.com/contact/

<input type="submit" value="Send Message">

Please amend this to include our onClick Handler as follows: (under the above place this
code).
"javascript:kenshoo_conv('contact','value','orderId','promocode','GBP');"

**Comment by ViorelEremia** [comment]
You can rewrite file submit.php in theme or child theme create in your child theme path: childTheme\framework-customizations\extensions\forms\extensions\contact-forms\views\submit.php and paste code here, here is the render of button submit by default if isnt rewritten.
http://manual.unyson.io/en/latest/extension/shortcodes/index.html?highlight=shortcodes#overwriting-shortcodes
