### ISSUE TITLE
Please consider these for typography option

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#293]
Issue 1:

Currently all fonts, standard and Google are merged. 
If we do 

    print_r(fw_get_db_settings_option('body_font'));

the array  returns these 4

	Array
	(
		[size] => 
		[family] => Open Sans
		[style] => 300
		[color] => 
	)

Now we need to build query for the Google font link which is ok given those 2 populated indexes , 
But if user switches to one of the standard fonts , than I have to check all existing standard fonts and not build the link for Google fonts. 

This would help us tremendously

	Array
	(
		[size] => 
		[family] => Open Sans
		[style] => 300
		[color] =>
		[type] => google
	)
	
	Array
	(
		[size] => 
		[family] => Arial
		[style] => normal
		[color] =>
		[type] => standard
	)

this way we can hook on the type and know what kind of font is user looking for and than build or not build Google font query. 

Issue 2 
I asked previously about adding custom standard font or rebuilding existing one here #212 and thnx for the help but the problem now is that the fonts array is not associative array so if I add my custom font variant like 
    
    array_push( $fonts, "'Helvetica Neue', Helvetica, Arial, sans-serif" );

I dont have font preview anymore  http://prntscr.com/6aokmd

This would help 

	function _filter_theme_typography_standard_fonts( $fonts ) {
	
		$newfonts = array('Helvetica' => "'Helvetica Neue', Helvetica, Arial, sans-serif" );
		$new_fonts_array = array_merge( $fonts,$newfonts );
		return $new_fonts_array;
	}

The font name and preview  can still  say  Helvetica but the output would be font with fallback. 

Please advise if you would be able to do any of these or should I build my own typo option.

**Comment by sergiubagrin** [comment]
Hi @danyj 

On monday we will check this. Thanks

**Comment by danyj** [comment]
And one more , this is much bigger issue and now I see what @thednp #181 #288 was talking about , this option is not setup properly at all. 

Style and weight should be separated , 
If you select Arial  and than from dropdown chose Thin/Italic , your style index output is this 

    300italic

So in order to set the css properly we need to separate the style from weight. 
Same goes for all google fonts , they are all separated by weight and style in stylsheet, see this 

as an example  http://fonts.googleapis.com/css?family=Anonymous+Pro%3Aregular%7CAbril+Fatface%3Aregular%7CAlfa+Slab+One%3Aregular

So our typo array should say something like this


	Array
	(
		[size] => 
		[family] => Open Sans,
		[general-family] => sans-serif // General font family sans,sans-serif,cursive,fantasy or monospace
		[weight] => 600
		[style] => italic
		[link]  => //fonts.googleapis.com/css?family=Open+Sans%3A600italic
		[color] =>
		[type] => google
	)
	
	Array
	(
		[size] => 
		[family] => Arial,
		[general-family] => sans-serif
		[weight] => 300
		[style] => normal
		[link]  =>
		[color] =>
		[type] => standard
	)



See this for  general-family
http://prntscr.com/6avhh1

**Comment by thednp** [comment]
@danyj you can do that yourself, with your own option type and generate your own array cache. My issue/need was with color and font-size into same setting, also the lack of fonts and their charsets.

My PR is really solving all that and works really well. Super tested everything.

**Comment by thednp** [comment]
The <code>300italic</code> can be easily split though. Just I think it's not needed for WEB font icons, that's the variant of the font.

**Comment by danyj** [comment]
the typo option needs rework from ground up , it is slow , missing subsets, buggy, not able to update the google font array , so , new one is in works
