### ISSUE TITLE
Polylang plugin conflict?

### ISSUE THREAD

**Issue by mricche** [ThemeFuse/Unyson#2930]
I am using WordPress 4.8.2 running Jevelin v 2.5.3 theme and the Polylang plugin Version 2.2.3. 
Unyson is ver. 2.7.7 wit six extensions: Page Builder v. 1.6.14, Demo& content v.20.24, Mega menu v. 1.1.3
WP shortcodes v.1.07, Portfolio v.1.08, SEO v.1.0.10
It worked with no problems with many posts and categories. But now I am unable to use Polylang anymore. 
The workflow is: as usual, I create a post in the first language, then the pair in second language, both using the unyson visual page builder within jevelin. I check the post everything is Ok. Then if I link the two post with Polylang (e,g. from the post in the first language) the post in the second language becomes blank. If I open (with edit from the WP dashboard) the post in the second language , it is actually blank in the visual builder editor. Tried with many new posts with no success. I can recover the content from the post revisions but when I update, the same “blank issue” appears in the post in the other language.
The same issue apply to the old post that were perfectly showing up before the issue appeared. Of course no problem arises if I deactivate Polylang
Thanks for Your support!

**Comment by steve-themefuse** [comment]
Hi, I can not simulate the issue on my end, I have tried with the default Scratch theme and a default WordPress theme and the visual page builder shows up in the post in both languages. May be there is something that I'm missing?
