### ISSUE TITLE
Issue with pagebuilder

### ISSUE THREAD

**Issue by psics** [ThemeFuse/Unyson#2931]
http://prntscr.com/grtpeq
Version 4.8.2 | Unyson 2.7.7

**Comment by psics** [comment]
https://www.youtube.com/watch?v=bh9TqxCFvpw

**Comment by ViorelEremia** [comment]
You have a strange structure of html tinymce where is iframe prefiexes mce_. you are using some plugin i guess what plugins i cant reproduce.

**Comment by psics** [comment]
http://prntscr.com/gtfqd2

**Comment by ecksite** [comment]
Isn't that exactly the same issue, that i have reported in [#2893](https://github.com/ThemeFuse/Unyson/issues/2893#issuecomment-333498048)?!
@ViorelEremia I am confused, that you refer to a possible plugin incompatibility, although you have already worked on this issue (?)
