### ISSUE TITLE
How to create a new shortcode based on the section?

### ISSUE THREAD

**Issue by Alecto** [ThemeFuse/Unyson#2932]
I need a completely redesigned shortcode for creating rows and containers, the standard shortcode section even with modifications is not entirely suitable for this.

I cloned the shortcode section folder and gave it a new name, for example, "container".

The paths are correct, other custom shortcodes work correctly.

But, I do not see a new shortcode on my tab. The only thing I did to connect the shortcode, I changed the config.php file:

```
<?php if (!defined('FW')) die('Forbidden');

$cfg = array(
	'page_builder' => array(
		'tab'         => __('Custom Elements', 'unyson'),
		'title'       => __('Container', 'unyson'),
		'description' => __('Add a Container', 'unyson'),
		'type'        => 'section', // WARNING: Do not edit this
	)
);
```

what am I doing wrong? How do I create a copy of the section for further rework?
thank you in advance.

**Comment by ViorelEremia** [comment]
should work, you checked tab custom elements and it doesnt exists ? provide more details about your structure, where you cloned? etc, rewriting works i checked.

**Comment by Alecto** [comment]
the folder structure for the theme is shown below
https://image.prntscr.com/image/ITfYGKJxTIuRQvxPRXc7Fg.png

I copied the folder of the shortcode "section" and called its "container" (highlighted)

in new folder "container" i change only config.php
```
<?php if (!defined('FW')) die('Forbidden');

$cfg = array(
	'page_builder' => array(
		'tab'         => __('Custom Elements', 'unyson'),
		'title'       => __('Container', 'unyson'),
		'description' => __('Add a Container', 'unyson'),
		'type'        => 'section', // WARNING: Do not edit this
	)
);
```
https://image.prntscr.com/image/CyK5ZlJZTIOqRWCrnbfsBQ.png

but in my custom tab i dont see new cloned element "container", although other elements are present there.
https://image.prntscr.com/image/PUpPjkLxSc6QocFV-uuTjA.png

**Comment by ViorelEremia** [comment]
Ok, you changed the folder name but 'type' in config is the same 'section', change it to 'container' should work.

**Comment by Alecto** [comment]
I did. did not help ((
https://image.prntscr.com/image/--vwQgJcSdexI2GJ9p_iCg.png
https://image.prntscr.com/image/UI_3m0gyQP2PQ87QjYM_bQ.png

**Comment by ViorelEremia** [comment]
ok, if you want to overwriting a shortcode read here: http://manual.unyson.io/en/latest/extension/shortcodes/index.html?highlight=shortcodes#overwriting-shortcodes
 you changeed the name of shortcode then the core cant know that your name is assigned to another
default shortocode so if you want to rewrite the default shortcode you do not have to rename the folder or type key from config.php. In your case you create another shortcode so read here: http://manual.unyson.io/en/latest/extension/shortcodes/index.html?highlight=shortcodes#creating-a-simple-shortcode

**Comment by Alecto** [comment]
in fact of the matter, I rewrote the standard shortcode section and added the options I needed.
here there are no problems.
I do not want to rewrite the shortcode section, I want to create its clone to be able to manage the markup inside.
I could not duplicate the shortcode section.
the only thing I need is to add shortcodes to the inside of the shortcode, I can not add anything to the my own shortcodes.

**Comment by ViorelEremia** [comment]
I do not understand what does not work for you and I do not understand what you want to do, in my end i can change everything in section from theme
" I want to create its clone to be able to manage the markup inside" - in my end i can change the view js css understand you want to make some changes in shortcode unyson so overwrite it and this works.

**Comment by Alecto** [comment]
Unyson use a bootstrap-like grid, pre-defined containers and rows.
But I do not use the bootstrap grid, I use flax-box and smart grids.
So I need to be able to set my own structure, different from the pre-installed.
That's why I wanted to create my own versions of the section and blocks, where I could manually set the structure of section, containers, rows and blocks, use my own classes everywhere.

To do this, I need to create copies of the elements of the section and blocks that I could deal with. But for some reason I can not do it, although I do according to the instructions.

**Comment by ViorelEremia** [comment]
There are no issues with overwrite shortcode section to do copy folder from unyson\framework\extensions\shortcodes\shortcodes\section in theme\framework-customizations\extensions\shortcodes\shortcodes\ here you can change everything if you want to use your files css, js edit file static.php change paths etc, view.php it automatically loads from here. I said that you changed the folder name from sectiion to conatiner in this case unyson see it as a new shortcode, please read carefully the documentation and your code or be more explicit if I did not understand what you want to do.

**Comment by Alecto** [comment]
>>> ere you can change everything
I did just that, the screenshot below.
other shortcodes work that way.
section - does not work.
https://image.prntscr.com/image/--vwQgJcSdexI2GJ9p_iCg.png

>>> I did not understand what you want to do.
I just want to see here a new element - a copy of the section.
https://image.prntscr.com/image/UI_3m0gyQP2PQ87QjYM_bQ.png

**Comment by ViorelEremia** [comment]
If you want to overwriting shortcode section you can overwriting: views, config, options, static files
If you want to create new shortocode see documentation. We have many themes what overwrite shortcode section and evrething is fine.

**Comment by Olegborodko** [comment]
Can I create cusom section? .. Or another container, that can have inside it another shortcodes?
