### ISSUE TITLE
error: Forbidden in Text Group

### ISSUE THREAD

**Issue by FedeM** [ThemeFuse/Unyson#2933]
Hello, I have recently had problems with the Page Builder, more precisely with the Text Group, when I log in I get the error "Error: Forbidden" and in the console I get the following error:

POST /wp-admin/admin-ajax.php 403 (Forbidden)

I have tried disabling all the plugins except Unyson and trying to edit the Text Group block and it has kept telling me the same error.

What can be the problem? From already thank you very much.

**Comment by steve-themefuse** [comment]
Please check with your hosting provider you have mod_security enabled on your server, if it is activated then it might restrict the access to the respective file

**Comment by FedeM** [comment]
Thanks for the reply, apparently my server does not have mod_security or any apache configuration. I will contact my hosting provider to see what they tell me.

**Comment by FedeM** [comment]
I reviewed the apache configuration and it has the active modules but it still does not work. How should I restrict access to the file?

**Comment by FedeM** [comment]
I already managed to solve the problem, I leave the solution in case someone else happens to him.

It should be clarified that if or if you require access to the server since you must modify Apache files:

Enter **/opt/ pache/logs/error_log** and check the ID you are sending as an attacker, copy the ID and add it to the file **/opt/apache/conf/extra/crs/activated_rules/modsecurity_crs_99_whitelist.conf** in  **<LocationMatch "/wp-admin/admin-ajax.php">** It looks something like this:

SecRuleRemoveById 950020 973330 973324 958028
