### ISSUE TITLE
Site dont come up when Unyson is activated

### ISSUE THREAD

**Issue by ZimmermannLeon** [ThemeFuse/Unyson#2934]
Hello,

if i try to activate the Unyson Plugin, my site get an HTTP 500 Error.
I try to deactivate all other plugins but only if i deactivate the Unyson Plugin my site comes up.
But when i activate a other theme then my site comes up with unyson.

The ErrorLog file:
`04.10.2017 16:49:12 mynvt.de [client 195.145.114.0] PHP Fatal error:  Out of memory (allocated 195035136) (tried to allocate 262144 bytes) in Unknown on line 0`

The memory Limit is at 256M...

Can you please help me?

Kind Regards
Léon

**Comment by Ataurr** [comment]
Increase your memory limit 512M and restart your apache.

**Comment by ViorelEremia** [comment]
Also try to change it in php.ini memory_limit=256M
