### ISSUE TITLE
SEO extension doesn't have sitemaps per language?

### ISSUE THREAD

**Issue by webprom** [ThemeFuse/Unyson#2935]
I'm using wpml to add a second language to a site. Activated SEO extension and expected to have a sitemap per language, but only have English sitemap with many duplicates. Can't it work with languages in directories?

Example here: http://www.vivid.co.il/sitemap-page.xml

thanks.

**Comment by ViorelEremia** [comment]
At the moment extension does not support any multi language plugin and is not planned in the near future but you can try to do that I will be very happy to receive from you a pull request.

**Comment by webprom** [comment]
I see, but since my pages have hreflang tags, maybe it would be enough...
thanks.
