### ISSUE TITLE
After upgrading sections all pages gone

### ISSUE THREAD

**Issue by zuiver** [ThemeFuse/Unyson#2936]
I have upgraded the plugin unyson and now i don't see my existing sections while editing a page. All i can do is add new sections. On the outside the sections on the pages are still working i just can't see them.

![image](https://user-images.githubusercontent.com/32538964/31220141-bd6a1124-a9bf-11e7-974e-861752a79e1a.png)

http://mooiinuistraling.nl

**Comment by gigit95** [comment]
Have you already read that? #2805

**Comment by gigit95** [comment]
Have you already read that? #2865

**Comment by iotashan** [comment]
I'm having the same issue. I upgraded to the new Unyson, and sections are missing from the editor. The public-facing website still has some content, but it's no longer properly formatted. When I look at my slider I put together, I see "Population method does not exist". 

Yes, I have tried both updating the Unyson extensions, and just deleting the entire unyson directory from plugins and re-installing everything. Nothing is working.

**Comment by iotashan** [comment]
When I try to edit that slider, I see "This slider was created correctly, but the code implementation was delete from source code or blocked from filter.Delete this post or recovery slider implementation"

**Comment by ViorelEremia** [comment]
@iotashan this error occurs when you have a slider type that not exists, by default are three types: box, nivo, owl so the first cause is you don't have correct slider type usually theme developers add their custom sliders from this results the second the child extension or this slider type is not loaded after update why I can't say I need to see the code, if you havee a premium theme try to ask theme developers   or you can drop me crdentials from your site and i take o look: viorel [ at ] themefuse [ dot ] com

**Comment by iotashan** [comment]
I solved my issue. While it presented similarly to this, and it happened at the same time as when I updated the plugin, it was due to database corruption (of my own doing).
