### ISSUE TITLE
Database recovery: Failed to insert row from line

### ISSUE THREAD

**Issue by Pierewiet** [ThemeFuse/Unyson#2937]
I have uploaded the demo content for the whistle theme from themeforest and all was well and good, until I decided to put back the back-up, earlier made, from the original website. All I get is an error notification:
_Failed to insert row from line 1903 into table _fwbk_uXBiR2pG3_wd_fb_data_

If anybody is willing, I could sure use some help.

**Comment by ViorelEremia** [comment]
Show what has this row, or drop me this backup and link with issue: viorel [ at ] themefuse [ dot  ] com

**Comment by Pierewiet** [comment]
This:

`{"type":"row","data":{"table":"wd_fb_data","row":{"id":"7","fb_id":"1","from":"326179544241941","object_id":"326179544241941_618298901696669","name":"Foto's uit het bericht van Buro Daad-Kracht","description":"","type":"photo","message":"Erg leuke workshop weerbaarheid en zelfverdediging gegeven aan deze vriendengroep 50+\ud83d\udcaa\ud83c\udffb\ud83d\udcaa\ud83c\udffb\ud83d\udcaa\ud83c\udffb\nWil je dit ook eens als activiteit of teambuilding neem gerust contact op met mij.","story":"Buro Daad-Kracht heeft 10 nieuwe foto's toegevoegd.","place":"","message_tags":"","with_tags":"","story_tags":"[{\"id\":\"326179544241941\",\"name\":\"Buro Daad-Kracht\",\"type\":\"page\",\"offset\":0,\"length\":16}]","status_type":"added_photos","link":"https:\/\/www.facebook.com\/burodaadkracht\/photos\/a.389150584611503.1073741833.326179544241941\/618298708363355\/?type=3","source":"","thumb_url":"","main_url":"","width":"","height":"","created_time":"2017-04-08T10:34:14+0000","updated_time":"2017-04-09T14:24:24+0000","created_time_number":"1491647654","reactions":"","comments":"{\"data\":[{\"created_time\":\"2017-04-09T14:24:24+0000\",\"from\":{\"name\":\"Luuk Driessen\",\"id\":\"10158276253810007\"},\"like_count\":1,\"message\":\"Nice, gas erop bij 50+\",\"comment_count\":0,\"id\":\"618298901696669_618860111640548\"}],\"paging\":{\"cursors\":{\"before\":\"MQZDZD\",\"after\":\"MQZDZD\"}},\"summary\":{\"order\":\"ranked\",\"total_count\":1,\"can_comment\":false}}","shares":"{\"count\":3}","attachments":"{\"data\":[{\"subattachments\":{\"data\":[{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/17799463_618298708363355_53504723480137312_n.jpg?oh=c718b6490b5aedfd5aa77872055c5b41&oe=5A7A2228\",\"width\":720}},\"target\":{\"id\":\"618298708363355\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298708363355\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298708363355\\\/?type=3\"},{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/17862464_618298721696687_6909523082132734681_n.jpg?oh=b4ef62cc4be2c808f42837438d9afd29&oe=5A413314\",\"width\":720}},\"target\":{\"id\":\"618298721696687\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298721696687\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298721696687\\\/?type=3\"},{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/17523060_618298745030018_4475335270467364945_n.jpg?oh=183087fb924160009021790f35ad39b3&oe=5A4BAEEA\",\"width\":720}},\"target\":{\"id\":\"618298745030018\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298745030018\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298745030018\\\/?type=3\"},{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/17634390_618298765030016_7287835359096502072_n.jpg?oh=e2427165283b7129e2fa282e2804abe9&oe=5A45FF3C\",\"width\":720}},\"target\":{\"id\":\"618298765030016\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298765030016\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298765030016\\\/?type=3\"},{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/17796599_618298768363349_2230898068046747254_n.jpg?oh=594c34a38ca62000879ae2ca251faa77&oe=5A7C53AA\",\"width\":720}},\"target\":{\"id\":\"618298768363349\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298768363349\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298768363349\\\/?type=3\"},{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/17800358_618298798363346_4957001645859024082_n.jpg?oh=d9b637b590c8991b5de385e46935dad0&oe=5A77A3A4\",\"width\":720}},\"target\":{\"id\":\"618298798363346\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298798363346\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298798363346\\\/?type=3\"},{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/984008_618298811696678_2619220516765332535_n.jpg?oh=00fd0203000781ee26e9222056bd5dbe&oe=5A4A482C\",\"width\":720}},\"target\":{\"id\":\"618298811696678\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298811696678\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298811696678\\\/?type=3\"},{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/17861730_618298838363342_8055992505278158575_n.jpg?oh=0f54d0b4e40239a5419e38669428647d&oe=5A863096\",\"width\":720}},\"target\":{\"id\":\"618298838363342\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298838363342\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298838363342\\\/?type=3\"},{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/17799077_618298858363340_8153100574306331336_n.jpg?oh=8f29b4cc6412568f6fdc74135f336e69&oe=5A77BBFC\",\"width\":720}},\"target\":{\"id\":\"618298858363340\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298858363340\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298858363340\\\/?type=3\"},{\"media\":{\"image\":{\"height\":540,\"src\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-0\\\/p180x540\\\/17800407_618298888363337_334953124548264311_n.jpg?oh=4d1815b57d362e77e568a6156ebf6a1c&oe=5A75C8C7\",\"width\":720}},\"target\":{\"id\":\"618298888363337\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298888363337\\\/?type=3\"},\"type\":\"photo\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/photos\\\/a.389150584611503.1073741833.326179544241941\\\/618298888363337\\\/?type=3\"}]},\"target\":{\"id\":\"618298901696669\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/posts\\\/618298901696669\"},\"title\":\"Foto's uit het bericht van Buro Daad-Kracht\",\"type\":\"album\",\"url\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/posts\\\/618298901696669\"}]}","who_post":"{\"picture\":{\"data\":{\"is_silhouette\":false,\"url\":\"https:\\\/\\\/scontent.xx.fbcdn.net\\\/v\\\/t1.0-1\\\/p50x50\\\/11042989_342023335990895_3696537030280669728_n.jpg?oh=0a6f96f094e5faf75a0c6ab603c018d6&oe=5A435CBA\"}},\"name\":\"Buro Daad-Kracht\",\"link\":\"https:\\\/\\\/www.facebook.com\\\/burodaadkracht\\\/\",\"id\":\"326179544241941\"}"}}}`

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/368
