### ISSUE TITLE
want to remove white space between titlebar and slider

### ISSUE THREAD

**Issue by dhiren4ur** [ThemeFuse/Unyson#2938]
i m using unyson pagebuilder with jevelin theme. there is some extra space between titlebar and slider, how to remove this.
similarly how to remove white space between other two section
for review attaching link
[https://discountcouponsgallery.com/](url)
pl support me as soon as possible

**Comment by ViorelEremia** [comment]
We can't help you because is theme sapace is not from unyson, theme authors create aditioanal code above unyson, try to contact javelin theme support, you can add some custom css but it can broke something else on your site, shortly ask theme authors I'm sure they'll help.
