### ISSUE TITLE
[QUESTION] How does the icon option type use/initiate the scroller?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#294]
I checked the files and there is no mention of any script requested or fired.

**Comment by sergiubagrin** [comment]
Hi @thednp 

``CSS

.fw-option-type-icon .option-type-icon-list {
margin-top: 1em;
padding-left: 1px;
padding-bottom: 1px;
overflow: auto;
max-height: 10.1em;

``
http://screencast.com/t/YNExCsL9Jw

**Comment by thednp** [comment]
Thank you, it's a new CSS3 for scrollbar elements, well new things to learn everyday :)
