### ISSUE TITLE
Fatal error: Cannot redeclare _fw_core_autoload()

### ISSUE THREAD

**Issue by inquota** [ThemeFuse/Unyson#2940]
Hi there,

When I activate the plugin, it came when the following error:

Fatal error: Cannot redeclare _fw_core_autoload();

I use version: 2.7.8

How to solve this problem?

Thanks!

**Comment by ViorelEremia** [comment]
I can not imagine how this happens, give me more details what theme do you use? is framework unyson packed in theme?

**Comment by inquota** [comment]
yeah sure, Im using the theme 'Faded' (1.0) on WP 4.9. Yes its packed in the theme.

**Comment by ViorelEremia** [comment]
Have you multisite? If unyson is packed in the theme then you can't use and unyson as a plugin. Have you a  folder in the theme - framework?

**Comment by inquota** [comment]
No its not a multisite. U can see here the folders: https://www.dropbox.com/s/jtmkk4742xxr0vf/Schermafdruk%202017-10-09%2010.25.56.png?dl=0

**Comment by ViorelEremia** [comment]
Plugin faded_theme_helper is activated ?

**Comment by inquota** [comment]
Yes! https://www.dropbox.com/s/fbp7wwyjoq7dc0u/Schermafdruk%202017-10-09%2010.35.11.png?dl=0

**Comment by ViorelEremia** [comment]
If you diable it everything is fine?

**Comment by inquota** [comment]
I disabled all plugins except the helper. When I activate the plugin Unyson the same fatal error occurs.

**Comment by ViorelEremia** [comment]
If you disable Faded Helper plugin everything is fine?

**Comment by inquota** [comment]
No it still occurs :(

**Comment by ViorelEremia** [comment]
Ok, give me your credentials(ftp, dashboard) and I'll take a look: viorel [ at ] themefuse [ dot ] com

**Comment by ViorelEremia** [comment]
I solved your problem, it was from your wordpress installation I don't now why you use an untested version of wordpress I moved wordpress to the current version and everything is fine, please don't use this version(for developers) if you do not have a very good knowledge of how to work with it.

**Comment by inquota** [comment]
Thanks for the help and sorry for the inconvenience!
