### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by Basilou38** [ThemeFuse/Unyson#2941]
I use the theme woffice, the theme uses Unyson, I encounter a language problem on the anniversary dates, the months of the year are in English, I would like the months to be displayed in French, I do not understand not why ?

Here is a video capture:
http://recordit.co/xN922lF1Oz

I thought the problem was related to buddypress, but not because it is very well translated

**Comment by ViorelEremia** [comment]
I tried woffice live demo: https://demos.alka-web.com/woffice/allinone/members/demo/profile/edit/group/1/ and I don't see unyson's classes css maybe these strings come from theme, try to ask theme developers, and let us to know from where does error come.

**Comment by Basilou38** [comment]
I have already asked the developer, he tells me it's buddypress, yet buddypress is translated to 100%, I thought the problem came from Unyson. I do not understand

**Comment by ViorelEremia** [comment]
Eh, drop me some temporary credentials ftp and dashboard: viorel [ a ] themefuse [ dot ] com

**Comment by ViorelEremia** [comment]
The isssue is from buddypress:
![ffffs](https://user-images.githubusercontent.com/28967378/31381737-165bbec0-adbe-11e7-8394-36a620fa7cb5.png)
This is custom format date buddypress need to use some functions as date_i18n try to ask them how to translate, now you can be sure it's not from unyson.
