### ISSUE TITLE
Logged in subscribers can’t see the body of the page only the header and footer. 

### ISSUE THREAD

**Issue by MWBartko** [ThemeFuse/Unyson#2942]
Logged in subscribers can’t see the body of the page only the header and footer. The exception is the blog which they can see fine. When they’re logged out they can see the body fine. Admins can see everything fine. This issue goes away only if I deactivate Unyson.

The page I need help with: https://solidarity-party.org/

**Comment by ViorelEremia** [comment]
I tested in my end and everything is fine. Maybe is an incompatibility of plugins. Try to deactivate one by one and see what results are

**Comment by MWBartko** [comment]
I did the only one that allows the body to show when turned off is Unyson. 

Strangely it doesn't seem to be just admins who can see normally as I thought. Anyone I manually edit no longer experiences the problem. But I have some 3,000 and the edit that fixes it it changing their role from the profile editor. https://solidarity-party.org/wp-admin/user-edit.php?user_id=1&wp_http_referer=%2Fwp-admin%2Fusers.php
