### ISSUE TITLE
Page Builder - All Content Has Disappeared

### ISSUE THREAD

**Issue by stevo324** [ThemeFuse/Unyson#2945]
Hello,

As of 2 days ago, when editing a page using the visual page builder - all my content has gone.
The content is still visible on the website itself, but cannot be seen or edited in the visual builder. Have not performed any updates or changes immediately prior to this happening.

Steps I have taken:
1) Updated the plugin and extensions to latest version
2) Cleared cache
3) Hard refresh

![screen shot 2017-10-10 at 4 20 04 pm](https://user-images.githubusercontent.com/32663436/31370453-eb24a8ca-add6-11e7-9497-525fe5b1ac61.png)

Any help or tips?

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by squatto** [comment]
Was this ever resolved? I'm having the same problem. I can give you access @ViorelEremia too if that would help.

**Comment by ViorelEremia** [comment]
@squatto Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by squatto** [comment]
@ViorelEremia You should have an email from my site (loganutdentist.com). Thank you!

**Comment by ViorelEremia** [comment]
@squatto you don't update the extensions. https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
check if everything is fine.

**Comment by squatto** [comment]
@ViorelEremia looks great! That's good to know about the extensions - I didn't see anywhere that indicated that I needed to update them. Maybe put a number on the menu item showing that there are updates?

Thank you for your help!

**Comment by jsonvega** [comment]
Hi, 
I also have this problem, the content of the page builder also is missing.

Please help, thanks

**Comment by squatto** [comment]
@jsonvega Check if you have Unyson extension updates to install. Go to Dashboard > Updates and scroll to the bottom of the page.

**Comment by jsonvega** [comment]
Hi,
Its all updated. what to do?

![screenshot from 2017-10-17 01-20-15](https://user-images.githubusercontent.com/18676593/31628045-9e56fb6c-b2d9-11e7-844d-344025293e71.png)

**Comment by squatto** [comment]
You will need to work with @ViorelEremia to get that fixed. Create an account on your WP admin for viorel@themefuse.com and set it as an admin

**Comment by jsonvega** [comment]
ok @squatto already emailed him. thanks

**Comment by zenics** [comment]
Ok,  @ViorelEremia could you give us a clear guide of what to do with this page  builder issue. I ve updated everything. even uninstall and upload the files directly but no luck.

**Comment by ViorelEremia** [comment]
@zenics Most popular of them: cache server/plugin wordpress, error request js to access tinymce.php, Unyson/extensions is not updated(the presence of some plugins as manage updates, or unyson is included as framework directtlly in theme), a bad development of the theme.

**Comment by ArmandHeijder** [comment]
@ViorelEremia i send you an email about my problem regarding the empty pages in unyson, coud you please help me.. thanks in advance
