### ISSUE TITLE
Page builder elements are getting disappeared when trying to edit on safari browser

### ISSUE THREAD

**Issue by Neer171** [ThemeFuse/Unyson#2946]
Hi, I'm using TopSEO wordpress theme on my website, I was trying to edit content but page builder is not loading content inside it. I attached screenshot link below
https://i.imgur.com/1KUAIcD.png

Here is screenshot for my console errors:

![image](https://user-images.githubusercontent.com/10610301/31385118-8ec90202-addf-11e7-9888-9c0eac855e4f.png)

even I.m getting this issue on chrome and Mozilla on some windows computers

**Comment by ViorelEremia** [comment]
If you disable Unyson does the issue stil persist? More specifically I'm interested in the first error - "can't find variabile URL"

**Comment by Neer171** [comment]
i'm getting console error only in safari but getting blank page builder in editor on some computers

https://i.imgur.com/1KUAIcD.png

**Comment by ViorelEremia** [comment]
If you disable Unyson does the issue stil persist? More specifically I'm interested in the first error - "can't find variabile URL" -- you tried that

**Comment by Neer171** [comment]
yeah, still showing ssame error

**Comment by ViorelEremia** [comment]
then is a server error if unyson doesnt exists then somenthin is wrong with your server

**Comment by Neer171** [comment]
this issue is occurring only in safari

**Comment by Neer171** [comment]
i'm getting console error only in safari but getting blank page builder in editor on some computers

https://i.imgur.com/1KUAIcD.png

**Comment by ViorelEremia** [comment]
I don't unserstand, on chrome for exemple everthing is fine?

**Comment by ViorelEremia** [comment]
Or error is showing only on safari?

**Comment by Neer171** [comment]
on some computers page builder is working fine 
![image](https://user-images.githubusercontent.com/10610301/31388688-6d421bc0-adec-11e7-8271-1bf55e6f3fc1.png)

but on some computers showing blank elements
![image](https://user-images.githubusercontent.com/10610301/31388647-4cdeea98-adec-11e7-9557-48966318abe2.png)

**Comment by ViorelEremia** [comment]
What you mean "computers"? I tested just now in safari browser and everything is fine.
