### ISSUE TITLE
Enable Unyson for Editors

### ISSUE THREAD

**Issue by hiraku-san** [ThemeFuse/Unyson#2947]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.
We are using Unyson for a project where by a number of users will add Wiki articles via the front end of the website. 

Unfortunately it appears that Unyson doesn't show in the front end for users to be able to use in their posts. Is this option available anywhere?

**Comment by ViorelEremia** [comment]
You mean what you want to use options types in frontend for post type wiki as described here: http://manual.unyson.io/en/latest/options/introduction.html#options-files, or you want to use page builder in frontend for custom type wiki?

**Comment by hiraku-san** [comment]
Looking to allow page builder to be used in the frontend, or at least rendered. Currently if I create a page in the backend and someone goes to edit it via the frontend they see the shortcodes.

I would it so that people can use the frontend with the same functionality as the backend.

**Comment by ViorelEremia** [comment]
it is possible maybe but very very difficult, sorry but I can't help you, and I suggest you give up this idea.
you will encounter many problems and to solve them you will have to invent different bicycles.
