### ISSUE TITLE
Not every Section goes to 

### ISSUE THREAD

**Issue by Parnable** [ThemeFuse/Unyson#2949]
I`m creating the landing page with Page Builder which consists of screens (section elements), and only 2 of 6 sections goes to wrapping "fw-page-builder-content" div. The 3-rd one goes to #fullpage div which is hardcoded in page.php of my WP theme, the other are going outside at all.
![strange_1](https://user-images.githubusercontent.com/18091921/31462375-3e40911e-aed5-11e7-9ec3-57957a88e916.jpg)

For nobody has a doubt that magic is inside some of my WP files, here is page.php code:

<?php
/**
 * Blablablabla
*
 */

get_header(); ?>

    <div id="fullpage">

            <?php
            while ( have_posts() ) : the_post();

                get_template_part( 'template-parts/content', 'home' );

            endwhile; // End of the loop.
            ?>

    </div>

<?php
get_sidebar();
get_footer();

the included tamplate-part (home) code is primitive: it only calls the_content(). That's all

ANd of course my visual builder page in admin:
![strange_2](https://user-images.githubusercontent.com/18091921/31462496-a1d48e56-aed5-11e7-8703-2cecd61e2eba.jpg)
Does anybody have any idea what can cause that issue? Thanks!

**Comment by danyj** [comment]
contact your theme developers, they did framework override

**Comment by Parnable** [comment]
Thank you, Danyj! Will try to figure it out
