### ISSUE TITLE
Install Package not available

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#295]
I'm trying to install Unyson using TGM Plugin Activationition with the following settings:
```
array(
			'name'     				=> 'Unyson',
			'slug'     				=> 'unyson',
			'source'   				=> '', 
			'required' 				=> true,
			'version' 				=> '', 
			'force_activation' 		=> false,
			'force_deactivation' 	=> false,
			'external_url' 			=> ''
		)
```

How ver it gives me **Install package not available**

Any idea what maybe wrong?

**Comment by sergiubagrin** [comment]
Hi @pe6o 

Please check this file: https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/functions.php  in scratch theme. You can download it and see how it is working

**Comment by pe6o** [comment]
THanks.

I removed the `'source' => ''` line and it worked!

**Comment by sergiubagrin** [comment]
@pe6o - good :)
