### ISSUE TITLE
Issue with the editing Mode

### ISSUE THREAD

**Issue by timdhrng** [ThemeFuse/Unyson#2950]
<img width="1558" alt="bildschirmfoto 2017-10-11 um 10 16 34" src="https://user-images.githubusercontent.com/32739275/31497876-9a3ab432-af60-11e7-8105-efa61b21d6d3.png">
As seen above I cant edit existing Sites - no elements are shown in the editor. Everything is up to date. Anyone have a solution for this?

**Comment by squatto** [comment]
I am experiencing this same issue. We're discussing it here: https://github.com/ThemeFuse/Unyson/issues/2945

**Comment by steve-themefuse** [comment]
Are the Unyson extensions updated as well? You can drop me your credentials at steven [ @ ] themefuse [ dot ] com and I will take a look.

**Comment by squatto** [comment]
@steve-themefuse that was the issue. I didn't see any indication that there were updates available - should it tag the "Updates" menu with a number?

**Comment by ViorelEremia** [comment]
@squatto I'm thinking about this, next week I'll fix.

**Comment by squatto** [comment]
@ViorelEremia sounds great, thank you for your help
