### ISSUE TITLE
Post and taxonomy options meta key

### ISSUE THREAD

**Issue by gonzela2006** [ThemeFuse/Unyson#2951]
Hello,

I noticed that post and taxonomy options are saved in a key called `fw_options` and there is no filter to change it to fit my theme as if anyone switched to another Unyson theme then the key will be overwritten and the old post/taxonomy settings will be lost upon updating a post or taxonomy. Is there any way to apply a filter on this key `fw_options`.

Please accept my apology if there is an already filter for this.

Thanks

**Comment by ViorelEremia** [comment]
No need hook here, you can remove hook that saves meta `remove_action( 'create_{your_taxonomy_name}', array( '_FW_Component_Backend', '_action_save_taxonomy_fields' ), 9 );` you can find [here](https://github.com/ThemeFuse/Unyson/blob/master/framework/core/components/backend.php#L765) and other methods or hooks.

**Comment by gonzela2006** [comment]
@ViorelEremia Thanks for getting back to me :)
I don't want to remove the save action, I'm asking about a way to change this key `fw_options` for taxonomy and posts to fit my theme and to prevent any conflict with any other Unyson theme.

**Comment by ViorelEremia** [comment]
Try to understand that: http://manual.unyson.io/en/latest/options/storage.html I think it is what you need
