### ISSUE TITLE
Cant spot learning module after installing unyson

### ISSUE THREAD

**Issue by aniruddha2907** [ThemeFuse/Unyson#2952]
I cant seem to find the learning module forms module after installing unyson. I could see it in the demo video. Plz guide.

**Comment by Ataurr** [comment]
Did you enable from supported extensions?
http://manual.unyson.io/en/latest/manifest/theme.html?highlight=supported_extensions

http://manual.unyson.io/en/latest/extension/learning/index.html

**Comment by aniruddha2907** [comment]
I did not get you. Are you suggesting to get a theme that supports these
hidden extensions.

If so can you suggest a theme. I am not a programmer so did not understand
what and where to do it.

Please bear with me.

Regards
Dean

**Comment by steve-themefuse** [comment]
@aniruddha2907,  yes you are right, you should get a theme that supports the extension, unfortunately I don't know any.

**Comment by aniruddha2907** [comment]
Oh. Yes that is why I wasn't able to get the learning modules. I was not
able to upload the scratch theme either.
