### ISSUE TITLE
Fix for collapsed items draging

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2954]
This bug might not be visible to everyone but we had 2 cases where it was and each had  own shortcode override. 

https://github.com/ThemeFuse/Unyson/issues/2696
https://github.com/ThemeFuse/Unyson/issues/2527

The issue is that the collapsed section builder **items** are still at their full height even if we dont see them 

http://prntscr.com/gx0a1m

so when you try to drag from bottom to top you kinda get in their space  and the drag /move is rejected by the builder. 
http://prntscr.com/gx0b9x

The bug is not in js but CSS and fix is very simple 

```
[class*="-collapsed"] .builder-items,
[class*="-collapsed"] .builder-items *{
	height:0;
	display:none;
}
```

I know that this is " somehow" custom work but the builder should collapse everything that is inside the collapsed item , not only the collapsed item wrapper.

**Comment by ViorelEremia** [comment]
I cant reproduce, how?

**Comment by danyj** [comment]
@ViorelEremia  Make huge  list of items inside the section , than collapse that section 

make copies of it , now move around from bottom to top
