### ISSUE TITLE
Social Extension Not Working

### ISSUE THREAD

**Issue by RixBtrfly** [ThemeFuse/Unyson#2956]
Whenever I try to download the social extension, the site goes blank. Won't let me in the backend. Both it and frontend dissapear to a blank white page. I've tried it twice. Both times I deleted the plugin using FileZilla. Most other items (except video which I'm posting a second ticket for) work fine until I try to install that extension.

http://tjstaste.com/essentialoils/

**Comment by ViorelEremia** [comment]
Enalble pphp debug: on your WordPress root folder, edit the wp-config.php and set the value of WP-DEBUG to true or you can install plugin Debug Bar, extension works fine in my end.
