### ISSUE TITLE
dont know how to use unyson to upload a pdf file

### ISSUE THREAD

**Issue by khanhcu** [ThemeFuse/Unyson#2958]
Hello all,
I am trying to upload a pdf file to my website using unyson. But i dont know how
i hope anyone can kindly show me how

**Comment by steve-themefuse** [comment]
@khanhcu, you can use the Add Media option from the text block shortcode: https://static.md/68d767f92fa5aa08970eae609e687549.png.

**Comment by ViorelEremia** [comment]
Also add format pdf to support formats media admin dashboard->settings->media another way doesnt exists with unyson.
