### ISSUE TITLE
Containers inside multi-picker do not work

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#296]
Never mind. Found a fix

**Comment by danyj** [comment]
Yeah , I thought I had this one but no, I cant nest the group/tab/box   inside multi-picker. 
Can someone show me a working example please. Mine is either giving me an error unefined type tab or not saving the data/

**Comment by danyj** [comment]
Here the error screen 
http://prntscr.com/6be693

Even tried add this example  http://raw-test.readthedocs.org/en/latest/options/containers.html


				array(
					'type'    => 'box',
					'title'   => __('Container Title', 'fw'),
					'attr'    => array('class' => 'custom-class', 'data-foo' => 'bar'),
					'options' => array(
						'id'  => array( 'type' => 'text' )
					)
				),	


inside the choice option and same error.

**Comment by sergiubagrin** [comment]
Hi @danyj 

1. Post Options array on first level can have only box containers: http://screencast.com/t/6WFywEtpM6
2. Options that have no value and contain other options in the options parameter are containers. If an option has the options parameter, it is considered a container.: http://screencast.com/t/1QNlJJlX

**Comment by danyj** [comment]
@sergiubagrin  So what you are saying I cant group anything inside the multi-picker ?

**Comment by sergiubagrin** [comment]
@danyj - I will investigate this.

**Comment by danyj** [comment]
Only reason for this is because each of the tabs/box/group that I am adding inside the multi  has multiple options.
So instead of doing this 
http://prntscr.com/6bf3io
I rather do this 
http://prntscr.com/6bf3yd

**Comment by danyj** [comment]
Sorry for pushing this but I am completely stuck here. 
I cant continue at all and have exhausted all possible options. Even tried this as last resort but it will be same as listing all options in one line #297 

I have 1 multi-picker that should control everything. 


layout
header
menu
footer
colors
logo
typography

When style is changed , each of these option groups should change with it. 

Problem I have is that  with current multi picker I cant group anything and only way to get the multi to work is to present all groups options in one strait line and it looks ridiculous and confusing. I cant have any kind of container . 

I am after something like this 
http://prntscr.com/6btk9q
http://prntscr.com/6btl48

and with current multi-picker is not doable. 
I cant continue at all since I dont know how the options array will be nested until this is resolved.

**Comment by moldcraft** [comment]
Hello @danyj 

Please apply [this fix](https://github.com/ThemeFuse/Unyson/commit/8aaa80a8ca45d8c0005f30313771341237c9938a#diff-4502a3ccfb8598bb6f004e4e4d191435R245) manually, or [download](https://github.com/ThemeFuse/Unyson/archive/master.zip) and install manually the latest version from github and let us know if it fixes the problem.

----

Note that you have in both tabs options with same id

```php
'id'  => array( 'type' => 'text' )
```

change them to be unique

```php
'id-...'  => array( 'type' => 'text' )
```

**Comment by danyj** [comment]
Bless your heart!!!!!!!  THANK YOU!
Yes it is fixed in options and post options , works fine. Still testing but I think is ok. tab/group/box work
Only in post options looks bit silly but cssing those is not an issue 

box 
http://prntscr.com/6bx1u0

tab
http://prntscr.com/6bx2m7
tabs still work they are just not styled


about the id's you mentioned,  I was just testing.

**Comment by moldcraft** [comment]
Please [download](https://github.com/ThemeFuse/Unyson/archive/master.zip) the latest Unyson from Github and let us know if the silly look was fixed or not.

**Comment by danyj** [comment]
No is worse now. 
Multi pickers and few other elements have double borders  in page edit and in theme options
http://prntscr.com/6e0su2
http://prntscr.com/6e0v10

boxes and tabs 
http://prntscr.com/6e0tqy

**Comment by moldcraft** [comment]
Can you give me please your options array?

**Comment by danyj** [comment]
O boy , is complicated , it is a maze of 70+ options , il try to simplify it



	<?php
	
	//options/settings.php
	
	$options = array(
		'general' => array(
			'title'   => __( 'General settings', 'fa' ),
			'type'    => 'tab',
			'options' => array(
				'sub_tab_1' => array(
					'title'   => __( 'General settings', 'fa' ),
					'type'    => 'group',
					'options' => array(
						fw()->theme->get_options( 'general' ),
					),
				),
			),
		),
	);	
	
	
	
	//options/posts/page.php
	
	$options = array(
		'main' => array(
			'title'   => __( 'Page options', 'fw' ),
			'type'    => 'box',
			'options' => array(
	
				// group
				'page_option_tab1' => array(
					'title'   => false,
					'type'    => 'group',
					'options' => array(
						'custom_post_style'       => array(
							'type'         => 'multi-picker',
							'label'        => false,
							'desc'         => false,
							'picker'       => array(
								'gadget' => array(
									'label'   => __( 'General options', 'fw' ),
									'type'    => 'radio',
									'value' => 'defaults',
									'choices' => array(
										'defaults'  => __( 'Use theme defaults', 'fw' ),
										'custom' => __( 'Set custom options', 'fw' )
									),
									'desc' => __('Set custom options for this page.', 'fw'),
								)
							),
							'choices'      => array(
								'custom'  => fw()->theme->get_options( 'general' ),
							),
							'show_borders' => true,
						),
	
					),
				),// end group
				
			),
		),
	);
	
	
	
	//options/general.php
	
	$options = array(
	
		'get_styles'       => array(
			'type'         => 'multi-picker',
			'label'        => false,
			'desc'         => false,
			'picker'       => array(
				'gadget' => array(
					'label'   => __( 'Default Style', 'fw' ),
					'type'    => 'select',
					'choices' => array(
						'red' => __( 'Red', 'fw' )
					),
					'desc'    => __( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
						'fw' ),
					'help'    => sprintf( "%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
						__( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
							'fw' ),
						__( 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
							'fw' )
					)
				)
			),
			'choices'      => array(
	
				'red' => array(
				
					'layout' => array(
						'title'   => __( 'Footer', 'fw' ),
						'type'    => 'tab',
						'options' => array(
							fw()->theme->get_options( 'footer' ),
						),
					),
				),
			),
			'show_borders' => true,
		),	
	
	);
	
	
	
	
	//options/footer.php
	
	/**
	
	multi-picker
		radio
		choices
			text
			color-picker
			color-picker
			color-picker
			color-picker
			color-picker
	
	/*

**Comment by moldcraft** [comment]
[Try again](https://github.com/ThemeFuse/Unyson/archive/master.zip) please.

**Comment by danyj** [comment]
One more left in theme options the border above the tabs 
http://prntscr.com/6e8rlc

and same set in page options , the style for sub tab is missing but the tabs work fine 

http://prntscr.com/6e8qjq

**Comment by danyj** [comment]
about border above the tabs in theme options 

if I set that first multi-picker to be     'show_borders' => false, 
the tabs are "hitting" the multi-picker description 

http://prntscr.com/6e8uw0

**Comment by moldcraft** [comment]
[Fixed](https://github.com/ThemeFuse/Unyson/commit/6429423f63d910802baaaf6fbffc38fdde0f6fb9). [Test again](https://github.com/ThemeFuse/Unyson/archive/master.zip) please

**Comment by moldcraft** [comment]
[Fixed](https://github.com/ThemeFuse/Unyson/compare/c6dabde60d95acc526385197fdd96b654a24eb59...a911569a3dfb5f8a24ee65f3e220cfc4ffadc9e3). [Test again](https://github.com/ThemeFuse/Unyson/archive/master.zip) please

**Comment by danyj** [comment]
Yes , border is fixed, but sub tabs on page edit are still without style

**Comment by danyj** [comment]
oh , now the sub tabs on page options are also without a style

before last fix http://prntscr.com/6e8rlc

after http://prntscr.com/6eabcw

**Comment by moldcraft** [comment]
I decided that [this](http://prntscr.com/6eabcw) is better than [this](http://prntscr.com/6e8rlc). [All side tabs levels](http://static.md/6e35d9ea6083f08889ed73eb0fafc50f.png).

P.S. What is [that gray](http://prntscr.com/6eabcw), you selected tab with the mouse, or it's something from css?

**Comment by danyj** [comment]
the gray is selection , not a part of it, well looked better to me before, only reason why is because the sub tabs are not recognizable. You dont know that it is a tab unless you click on it.

**Comment by moldcraft** [comment]
Look in [scratch theme settings](http://static.md/6e35d9ea6083f08889ed73eb0fafc50f.png) they were always like that. I didn't invented anything.

**Comment by moldcraft** [comment]
Look in [scratch theme settings](http://static.md/06571f7a9bea33bfaa15a53f2b05d6e1.png) they were always like that. I didn't invented anything.

**Comment by moldcraft** [comment]
I will discuss with @DimiBaitanciuc about [this design](http://static.md/6e35d9ea6083f08889ed73eb0fafc50f.png) tomorrow.

**Comment by danyj** [comment]
I will css it myself is not an issue just need to know if it will stay like this. 
Something along these lines looks natural to me.
http://prntscr.com/6eawk6
http://prntscr.com/6eb0l5
http://blog.ezofficeinventory.com/wp-content/uploads/2014/02/Selection_286.png

Sure it is user preference

**Comment by moldcraft** [comment]
> just need to know if it will stay like this

The tabs html was and will be the same.

----

> @moldcraft I will discuss with @DimiBaitanciuc about this design tomorrow.

We will leave them as they are now, no changes for level 3+ tabs.

**Comment by danyj** [comment]
Not a problem, I will add few custom css lines. As long as they wont change ( the class names )  I am ok.
