### ISSUE TITLE
fw-stroage does not working for post-meta

### ISSUE THREAD

**Issue by saiful-droit** [ThemeFuse/Unyson#2960]
Hi, 
this is my code : 
'is_section_status' => array(
                        'label' => esc_html__('Is Section?', 'dem-data'),
                        'type' => 'switch',
                         'fw-storage' => array(
                            'type' => 'post-meta',
                            'post-meta' => 'fw_option:is_section_status',
                        ),
                        'left-choice' => array(
                            'value' => 'no',
                            'label' => esc_html__('No', 'dem-data')
                        ),
                        'right-choice' => array(
                            'value' => 'yes',
                            'label' => esc_html__('Yes', 'dem-data')
                        ),                        
                        'value' => 'yes',                       
                        'desc' => esc_html__('Do you want to show this page a section in home page? Change   the status "Yes".', 'dem-data'),
                    ),
Output:
![metaoptions_4](https://user-images.githubusercontent.com/20698608/31584823-2da9eeda-b1d8-11e7-86eb-b1fa09f2f654.png)
But problem is when we change something page contents than it switch to no. Every time So what i do.

**Comment by ViorelEremia** [comment]
I tested adn is good what do you change in page.
