### ISSUE TITLE
Unyson options not effective in preview unless saved

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#2961]
When the user added some content to custom options for a post, but didn't save the post yet, the post preview doesn't show these custom content yet.

Steps to reproduce:
- create new post with custom options;
- add some content to custom options;
- open post preview.

To me this seems to be related to this issue, but we're not using the page builder: https://github.com/ThemeFuse/Unyson/issues/273

**Comment by danyj** [comment]
I  have been on it since months 
https://github.com/ThemeFuse/Unyson/issues/2441

**Comment by warudin** [comment]
Ah, excuse me. I've tried to look and see if a topic about this was already present, but didn't stumble upon this one.

**Comment by danyj** [comment]
@ViorelEremia  I see you closing double pots but can you also acknowledge opened ones so that we know what is going on ? The silent close without acknowledgment is not telling us anything and makes us all think that there is no one to turn to when we need help.
