### ISSUE TITLE
Class 'FW_Extension_Forms_Form' not found

### ISSUE THREAD

**Issue by Franz765** [ThemeFuse/Unyson#2962]
I have installed Wordpress Version 4.8.2–de_DE and tried to update unyson. It failed. I then reinstalled unyson. When trying to activate it, I get the following error:
Fatal error: Class 'FW_Extension_Forms_Form' not found in .../cms/wp-content/themes/alaya/framework-customizations/extensions/forms/extensions/contact-forms/class-fw-extension-contact-forms.php on line 5
Please help!

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com. I can't understand what's going on
