### ISSUE TITLE
Gmaps retired version 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2963]
Please update 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/map/static.php#L7

https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

latest is 3.29

**Comment by danyj** [comment]
We might also not need specific versioning but a release version which is v3

https://developers.google.com/maps/documentation/javascript/versions

**Comment by thednp** [comment]
It's only the `static.php` need to be updated with new version. No breakers so far.

**Comment by thednp** [comment]
I wonder, how can I feed IE8 an older gmaps version.

**Comment by danyj** [comment]
@thednp our  sniffer 
https://github.com/YJSGframework/yjsg/blob/1c7eea963ddc401820f46ffc53cd12a42cef0bfd/includes/yjsgcore/classes/yjsg.browser.class.php#L27

```

$browser 			= new YjsgBrowser;

fw_print($browser->Version);
```

**Comment by thednp** [comment]
Thanks, but I think you're missing one name there "Trident" is the name under the Edge/IE11-IE12.

**Comment by danyj** [comment]
modify to your needs

**Comment by thednp** [comment]
;)

**Comment by danyj** [comment]
But I say ,anyone who is supporting under IE10  and below a year after it has been gone 
https://www.infoworld.com/article/3020534/security/microsoft-will-end-support-for-internet-explorer8-9-and-10.html

is making it harder to let that crap go. Lead your customers to better things
