### ISSUE TITLE
Blank Slide Editor Page

### ISSUE THREAD

**Issue by wroman** [ThemeFuse/Unyson#2965]
I am unable to edit sliders. Please see screenshots below. Wordpress 4.8.2 and Unyson 2.7.8 with all extensions updated.

![screen shot 2017-10-18 at 12 09 53 am](https://user-images.githubusercontent.com/1353902/31701854-c3d6d5dc-b398-11e7-97d8-9a791f26b644.png)

![screen shot 2017-10-18 at 12 11 09 am](https://user-images.githubusercontent.com/1353902/31701900-0b24a392-b399-11e7-802e-14e7cc7d2130.png)

![screen shot 2017-10-18 at 12 12 14 am](https://user-images.githubusercontent.com/1353902/31701908-0e5f962a-b399-11e7-8801-339e9beec08b.png)

**Comment by ViorelEremia** [comment]
Try to deeactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, I think it's a plugins conflict
