### ISSUE TITLE
Page builder doesn't work

### ISSUE THREAD

**Issue by Ricsen** [ThemeFuse/Unyson#2966]
I've created a Wordpress platform site with a theme that included Unyson Extensions Page Builder in the dashboard and the site worked regularly up to the latest updates. I currently cannot use Page Builder because don't appear the items in the editor, while in the default editor regularly appears the code. I tried all the steps I have read in last posts, finally Page editor does not work.
Can you help me to solve this problem?
Riccardo
Italy

**Comment by thednp** [comment]
Alot of people could help if you could provide some sort of info. I think what's best to do is to download latest Unyson, upload over your existing install and override all existing files.

Maybe your server timed out during update and the actual update wasn't really successful.

**Comment by Ricsen** [comment]
Resolved, thank you for the quick answer
