### ISSUE TITLE
drag&drop doesnt work correctly

### ISSUE THREAD

**Issue by tazotodua** [ThemeFuse/Unyson#2967]
When there is i.e. 2/3 and i want to drag 1/3 , while dragging, the incorrect area is highlighted:

https://i.imgur.com/i9Qo0jz.png

although when i release mouse, it is positioned correctly:
https://i.imgur.com/H44QD7D.png

however, it's annoying that previewer doesnt work correctly, so, should be fixed.

**Comment by thednp** [comment]
From JavaScript perspective this might be doable, however, from what I've observed about the behavior it's likely that until you `mouseup`, the new element doesn't exist, it's a feature to optimize the load time of the settings pages.

I wouldn't worry about that at all.

**Comment by ViorelEremia** [comment]
@tazotodua @thednp @danyj please test I think it's an important change.

**Comment by thednp** [comment]
Seems changed a little bit, but I cannot tell which one is better.

**Comment by ViorelEremia** [comment]
@thednp technically is better but is less as user friendly, I agree with you, another solution I don't see.

**Comment by danyj** [comment]
@ViorelEremia   , does not work for custom made column width

: Cannot read property 'backend_class' of    

on line 410  buklder.js

http://prntscr.com/h04g56

**Comment by danyj** [comment]
@ViorelEremia    in builder override config add  own column with own class like 

https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/d9164fc9705394fcb8fbf18ce7d704440b298004/config.php#L8


I have 3 custom one with my own grid class like 


```
	'3_5' => array(
		'title'          => '3/5',
		'backend_class'  => 'thz-col-3-5',
		'frontend_class' => 'thz-column thz-col-3-5',
	),
```

so is not reading any of those

**Comment by danyj** [comment]
>  less as user friendly
I think is ok ,  and it should display what you are dragging

**Comment by ViorelEremia** [comment]
I tested a few sites with this method and is bad, ssome users create how it comes in their head custom clases and there are too many problems. I return the code as it was earlier.

**Comment by ViorelEremia** [comment]
I reverted commit to the stable version, for us this issue has a low priority maybe in the future I'll take a look, but who thinks it is important can open a pull request, and I'll take care to test to be compatible with all the themes.
