### ISSUE TITLE
Scrolling not functioning on HP Elite X2 and HP Elite X360

### ISSUE THREAD

**Issue by roaerts86** [ThemeFuse/Unyson#2968]
The framework doesn't let devices like HP Elite X2 and HP Elite X360 scroll down.
Already tried several browsers like (Chrome, IE) and both browsers won't allow scrolling at all for these devices. The scrolling does work properly when using a Macbook Pro or Samsung Galaxy S5. Does anyone have any suggestions on how this can be fixed?

**Comment by danyj** [comment]
contact theme provider , this is framework support
