### ISSUE TITLE
Multi picker not saving theme component group of options.

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#297]
In order to simplify the group of options I want to use (ideally #296 )

    fw()->theme->get_options('group_name');

which would turn this

	$options = array(
	
		'get_styles'       => array(
			'type'         => 'multi-picker',
			'label'        => false,
			'desc'         => false,
			'picker'       => array(
				'gadget' => array(
					'label'   => __( 'Default Style', 'unyson' ),
					'type'    => 'select',
					'choices' => array(
						'blue'  => __( 'Blue', 'unyson' ),
						'red' => __( 'Red', 'unyson' )
					),
					'desc'    => __( 'Desc.','unyson' ),
				)
			),
			'choices'      => array(
				'blue'  => array(
				
					'text_color'  => array(
						'type'  => 'color-picker',
						'value' => '#444444',
						'label' => __( 'Text color', 'unyson' ),
						'desc' => __( 'Set default text color', 'unyson' )
					),
					'link_color'  => array(
						'type'  => 'color-picker',
						'value' => '#40b1e2',
						'label' => __( 'Primary color', 'creatus' ),
						'desc' => __( 'Set default color for links and accent elements', 'unyson' )
					),
					'link_hover_color'  => array(
						'type'  => 'color-picker',
						'value' => '#454545',
						'label' => __( 'Highlight color', 'unyson' ),
						'desc' => __( 'Set default color for hovers', 'unyson' )
					),
					'headings_color'  => array(
						'type'  => 'color-picker',
						'value' => '#454545',
						'label' => __( 'Headings color', 'creatus' ),
						'desc' => __( 'Set default color for headings (H1, H2, H3, H4, H5 & H6 )', 'unyson' )
					)
				),
				// next choice
			),
			'show_borders' => true,
		),	
	
	);

this is the color options array printed 

	Array
	(
		[text_color] => #444444
		[link_color] => #1e73be
		[link_hover_color] => #454545
		[headings_color] => #454545
	)

in to 

	$options = array(
	
		'get_styles'       => array(
			'type'         => 'multi-picker',
			'label'        => false,
			'desc'         => false,
			'picker'       => array(
				'gadget' => array(
					'label'   => __( 'Default Style', 'unyson' ),
					'type'    => 'select',
					'choices' => array(
						'blue'  => __( 'Blue', 'unyson' ),
						'red' => __( 'Red', 'unyson' )
					),
					'desc'    => __( 'Desc.','unyson' ),
				)
			),
			'choices'      => array(
				'blue'  => array(
				
					fw()->theme->get_options( 'colors' ),
				),
				// next choice
			),
			'show_borders' => true,
		),	
	
	);

and colors.php being this 

	$options = array(
	
		'text_color'  => array(
			'type'  => 'color-picker',
			'value' => '#444444',
			'label' => __( 'Text color', 'unyson' ),
			'desc' => __( 'Set default text color', 'unyson' )
		),
		'link_color'  => array(
			'type'  => 'color-picker',
			'value' => '#40b1e2',
			'label' => __( 'Primary color', 'creatus' ),
			'desc' => __( 'Set default color for links and accent elements', 'unyson' )
		),
		'link_hover_color'  => array(
			'type'  => 'color-picker',
			'value' => '#454545',
			'label' => __( 'Highlight color', 'unyson' ),
			'desc' => __( 'Set default color for hovers', 'unyson' )
		),
		'headings_color'  => array(
			'type'  => 'color-picker',
			'value' => '#454545',
			'label' => __( 'Headings color', 'creatus' ),
			'desc' => __( 'Set default color for headings (H1, H2, H3, H4, H5 & H6 )', 'unyson' )
		)
	);

but in fact this when saved end up being empty

		Array
	(
		[0] => Array
			(
			)
	
	)

I think that this bug is also connected to #296 .  As you can see I am trying to simplify the multitude of options and group them but looks like multi-picker options does not let me use any kind of grouping options that we have,

**Comment by danyj** [comment]
Thing here is that the visual is ok , you wont see a bug in admin and options nesting looks same in both cases.

**Comment by moldcraft** [comment]
The fix for https://github.com/ThemeFuse/Unyson/issues/296 also fixes this
