### ISSUE TITLE
Haven theme: problems with admin-ajax.php and install demo.

### ISSUE THREAD

**Issue by erremancini** [ThemeFuse/Unyson#2970]
Hi everybody.

I'm using Haven theme from ThemeFuse, installed on a subdomain. I cannot install demos and I see this error message:

> "Important: HTTP Loopback Connections are not enabled on this server. If you need to contact your web host, tell them that when PHP tries to connect back to the site at the URL `http://aduepassidastesicorosuites.a-catania.net/wp-admin/admin-ajax.php` and it gets the error `Response code: 500`. There may be a problem with the server configuration (eg local DNS problems, mod_security, etc) preventing connections from working properly."

I've looked for a solution in your list of issues and I haven't found the proper answer: same error message, but different cases (it would appear so).
How can I fix it?

Thank you for help!
Erre

**Comment by danyj** [comment]
contact theme provider please , this is framework support only

**Comment by erremancini** [comment]
Oh, sorry! Thank you!
