### ISSUE TITLE
Posts Categories disappears from the list

### ISSUE THREAD

**Issue by Sammael1106** [ThemeFuse/Unyson#2971]
Hi there! Thanks for your products.

Help me please, a have a huge problem with Posts Categories. 
I have some categories, it's OK without Unyson Plugin:
https://prnt.sc/gzso85

But when I install it (the latest version), my categories disappeared from the list:
https://prnt.sc/gzsmk5
https://prnt.sc/gzsmwz
But it is still available in post quick edit and filter
https://prnt.sc/gzsnue

There is no other plugins https://prnt.sc/gzsp2c
I also tried to remove Blog-extension and had no profit. What can I do?

**Comment by ViorelEremia** [comment]
Hi, drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by ViorelEremia** [comment]
also what theme do you use? try tochange the theme with one of defaults wordpress themes

**Comment by Sammael1106** [comment]
@ViorelEremia thanks a lot! I use my own custom theme, and you were right - when I switch to default theme, categories will appear. 

Now I just need to find where is the problem in my theme...

**Comment by ViorelEremia** [comment]
Ok, try and comment code by code, I think it's an incorrectly added hook. good luck :)
