### ISSUE TITLE
Can I submit a theme in wordpress.org which is based on Unyson?

### ISSUE THREAD

**Issue by therakib7** [ThemeFuse/Unyson#2972]
I know WordPress mandatory to use customizer settings API for every WordPress theme. Now my question is if I added customizer settings field by unyson plugin. Is any restriction in WordPress policy?

**Comment by thednp** [comment]
It can get accepted if it works with specific Wordpress features, without alteration.

**Comment by ViorelEremia** [comment]
Yes, you can submit it to .org, but you need to respect these rules: https://developer.wordpress.org/themes/getting-started/ 
And your theme must works fine without unyson plugin installed, I mean without errors or disign differences.
There are some themes created with unyson on .org.
