### ISSUE TITLE
Having trouble targeting CSS for accordion in Unyson

### ISSUE THREAD

**Issue by thebais** [ThemeFuse/Unyson#2973]
I have found the shortcode in the usual place but in trying to target the class .panel-group fw-accordion, it doesn't seem to be working (even though I now am definitely refreshing and not using the cache :) )
Ive also tried copying the accordion shortcode into the chid and changing the class to something simple and still not getting any result.
Any ideas?

**Comment by thebais** [comment]
Update: to be more accurate, Ive managed to hit the actual detail of the accordion by putting a custom class in it, however, its the header that I want to modify and it doesn't seem to be affected with the custom class. AS I've said before, trying to target items in a framework is a nightmare if you don't know how its constructed, can someone help please?

**Comment by thednp** [comment]
You better override the template view of the shortcode. You can search the issues you might find the answer.

**Comment by gigit95** [comment]
May be [this](https://github.com/ThemeFuse/Unyson/issues/2911) will help you.

**Comment by ViorelEremia** [comment]
Copy accordion folder from plugins/unyson/framework/extensions/shortcodes/shortcodes/ to your child theme: themes/scratch-child/framework-customizations/extensions/shortcodes/shortcodes/
Here in child theme add in static.php: 
`<?php defined( 'FW' ) or die();

$shortcodes_extension = fw_ext( 'shortcodes' );

wp_enqueue_script(
	'fw-shortcode-accordion',
	$shortcodes_extension->get_shortcode( 'accordion' )->locate_URI( '/static/js/scripts.js' ),
	array( 'jquery-ui-accordion' ),
	false,
	true
);
wp_enqueue_style(
	'fw-shortcode-accordion',
	$shortcodes_extension->get_shortcode( 'accordion' )->locate_URI( '/static/css/styles.css' )
);
`
It allow you to overrite file js and css from plugin in child theme or you can add in theme parent anyway it will work.
As I understand from you you want to rewrite style.css and views. I just changed in static.php the uri from `$shortcodes_extension->get_declared_URI('/shortcodes/accordion/static/js/scripts.js'),` to `$shortcodes_extension->get_shortcode( 'accordion' )->locate_URI( '/static/js/scripts.js' ),` but you can use any wordpress method to extract uri to your file.

**Comment by thebais** [comment]
Thank you for your answer ViorelEremia :)
Actually i had found a way to do it, but it was bizarre to say the least.. I found some website showing an accordion built on aria tabs.. copied the css verbatim and it worked! lol 
but to be honest I thought I'd better do it your way just in case the other caused issues further down the line. Thanks again
