### ISSUE TITLE
Unyson bug error - blog posts crash

### ISSUE THREAD

**Issue by sarcoiduk** [ThemeFuse/Unyson#2975]
Blog posts and (page with blog post feed) crash site when opened. No error message but loading page changes to black screen and crashes the whole browser.
Error does not occur when Unyson is deactivated. However lots of other content and functionality is lost in this state.
Can't find any similar issues to learn from.
All advice appreciated. 

Screenshot shows page when crashing:
![image](https://user-images.githubusercontent.com/33065930/31955199-9bcf5982-b8df-11e7-911b-d592476f877b.png)

**Comment by sarcoiduk** [comment]
ok i think I have identified the error: 
_PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version.To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0_
I don't know what that means though...

**Comment by ViorelEremia** [comment]
By default PHP 5.6 ships with a configuration that throws deprecated notices. System administrators configures that to 1 do not show deprecated errors. A way to fix this is to add that to your php.ini:  always_populate_raw_post_data=-1 or you can migrate your php to the newest version maybe will fix that.

**Comment by sarcoiduk** [comment]
Thanks for your advice @ViorelEremia 
Contacted domain host who advised: _"This looks to be due to the actual PHP settings and limitations on the account. Because you have a shared hosting account we cannot lift these restrictions. Unfortunately the only way to make them higher would be to have a VPS or Dedicated server and then you could change them to anything."_
I don't want to have to upgrade my hosting package just for this error...is there any possible  workaround?

**Comment by ViorelEremia** [comment]
I don't now how to fix what. We use functionality from wordpress so if you have big limitations when you will have many troubles in the future with plugins what use post requests. Drop me some temporary credentials admin, ftp: viorel [ a ] themefuse [ dot ] com I will try to find a solution, but I can't guarantee if it exists.
