### ISSUE TITLE
EDITOR EMPTY after update of Wordpress AND Unyson

### ISSUE THREAD

**Issue by snowlionrep** [ThemeFuse/Unyson#2976]
After updating to WordPress 4.8.2 and Unyson 2.5.3, when I open pages to edit, the default editor box is empty, as is the visual and text boxes.  I can no longer edit my site.

I am not a developer, a coder, or anything - just a total regular person who would appreciate any ideas on how to immediately fix this as the site is time sensitive and must be fixed.  HELP!

**Comment by Ataurr** [comment]
Make sure your all Extensions are up to date.
Go to dadhboard-> updates. At the bottom have an option "Unyson Extensions"
Update all the extensions.

**Comment by ViorelEremia** [comment]
If is not working after update extensions check console for errors if there is a error with undefinded tinymce or request faild to tinymce.php when contact your hosting provider.

**Comment by snowlionrep** [comment]
Thanks I finally figured that out and think I got it working with a manual install.  Appreciate it much!


Margit Ahlin
Producing Director
Snowlion Repertory Company
(207) 518-9305
www.snowlionrep.org



-----Original Message-----
