### ISSUE TITLE
Can we addon options to existing WP post box?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2978]
Does anyone know a way to add additional options to existing WP post box. The featured image one. I have 2 options I need to add and currently I am using Unyson group to make them and than via JS move the options to the #postimagediv. 

I rather add the 2 options to the box directly if possible.

**Comment by ViorelEremia** [comment]
Try this hook: apply_filters( 'admin_post_thumbnail_html', $content, $post->ID, $thumbnail_id );

**Comment by danyj** [comment]
Thnx  but Unyson options dont render there , I need to render them as html to add on 
https://developer.wordpress.org/reference/hooks/admin_post_thumbnail_html/#user-contributed-notes

**Comment by danyj** [comment]
Ok something like this works but must be repeated for each option

```
function filter_featured_image_admin_text( $content, $post_id, $thumbnail_id ){
	$help_text = array ( 
		'label' => __('Label', 'fw'),
		'desc' => esc_html__('Select the featured image size to be used.', 'fw'),
		'value' => 'original',
		'type' => 'short-select',
		'choices' => array()
	);
	
	$options  = fw()->backend->render_option('demo_option',$help_text);
	
    return $content .$options;
}
add_filter( 'admin_post_thumbnail_html', 'filter_featured_image_admin_text', 10, 3 );
```

**Comment by warudin** [comment]
Looks like this solution doesn't work to actually save option values, correct?

**Comment by danyj** [comment]
@warudin I ended up using 

`'type' => 'group'`

than moving it via JS to the post box
