### ISSUE TITLE
Default shortcode preview in PageBuilder

### ISSUE THREAD

**Issue by ange007** [ThemeFuse/Unyson#2979]
Hello.

For a long time there was a discussion of a preview of short-codes.
And even such feature has been added with the help - `title-template`:
https://github.com/ThemeFuse/Unyson/issues/759
https://github.com/ThemeFuse/Unyson/issues/1305

But for any reason this functionality hasn't been added to standard short-codes. It is necessary to redefine default short-codes for such opportunity.
Why? Perhaps this involves some difficulties?

**P.S.** Is it possible to add a `title-template` without overriding all the shortcodes?

**Comment by danyj** [comment]
> Is it possible to add a title-template without overriding all the shortcodes?

no you must override and it is not in by default because this is a framework and no default options are set, you can always change them. But when you do an override you control what is seen.

**Comment by ange007** [comment]
> no you must override and it is not in by default because this is a framework and no default options are set, they are just examples, you can always change them. But when you do an override you control what is seen.

Maybe you know a way like this:
```
add_action( 'fw_admin_enqueue_scripts:post', function( )
{
	$opt = fw_ext( 'shortcodes' )->get_shortcode( 'text_block' )->get_options( );	
	$opt[ 'general' ][ 'title_template' ] = '{{-content}}{{ if (o.content) { }} : {{-o.content.replace(/(<([^>]+)>)/ig,"")}}{{ } }}';
}
```
It would be great to simplify the task.

**Comment by danyj** [comment]
I dont know of any action that does that

**Comment by ange007** [comment]
Perhaps someone else knows the solution without having to duplicate shortcodes with their settings?

**Comment by zakirsajib** [comment]
If you want to show the preview of contents for text-block shortcode then following would work:

`$cfg = array(
	'page_builder' => array(
		'title'       => '   ' . esc_html__( 'Text Block', 'jevelin' ),
		'description' => esc_html__( 'Add a Text Block', 'jevelin' ),
		'tab'         => esc_html__( 'Content Elements', 'jevelin' ),
		'popup_size'  => 'medium',
		'icon' => 'fa fa-btc',
        'title_template' => '
        	<b>{{= title }}</b>
        	<div class="sh-builder-item-desc">

	        	{{ if( typeof o.content != "undefined" && o.content ) { }}
	        	{{- o.content.replace(/(<([^>]+)>)/ig,"").split(/\s+/, 25).join(" ") }}
	    		{{ } }}

        	</div>',
	)
);`

You may change **o.content** to **o.text** if you didn't override the default wp-editor which is in options.php file of text-block.

**Comment by ViorelEremia** [comment]
Now you can use the hook ```fw_ext:shortcodes:config_shortcode```: 
```
add_action( 'fw_ext:shortcodes:config_shortcode', 'config_shortcode', 10, 2 );
function config_shortcode( $config, $tag ) {

	$configs = array(
		'button' => array(
			'title_template' => '
	            <b>{{= title }}</b>
	            <div class="item-desc">
		            {{ if( typeof o.label != "undefined" && o.label ) { }}
		            {{- o.label.replace(/(<([^>]+)>)/ig,"").split(/\s+/, 25).join(" ") }}
		            {{ } }}
	            </div>',
		),
	);

	if ( isset( $configs[ $tag ] ) ) {
		$config = array_merge( $config, $configs[ $tag ] );
	}

	return $config;
}
```

**Comment by ange007** [comment]
> Now you can use the hook fw_ext:shortcodes:config_shortcode:

Why this feature may not work?
I do not see the operation of this filter.

```php
add_filter( 'fw_ext:shortcodes:config_shortcode', function( $config, $tag ) 
{
	fw_print( [ $config, $tag ] ); // not show

	$configs = [
		'button' => [
			'title_template' => '
				<b>{{= title }}werer</b>
				<div class="item-desc">
					{{ if( typeof o.label != "undefined" && o.label ) { }}
					{{- o.label.replace(/(<([^>]+)>)/ig,"").split(/\s+/, 25).join(" ") }}
					{{ } }}
				</div>',
		],
	];

	if( isset( $configs[ $tag ] ) ) 
	{
		$config = array_merge( $config, $configs[ $tag ] );
	}

	return $config; // no change
}, 
10, 2 );
```
