### ISSUE TITLE
[suggestion] Edit page update/save ajax

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#298]
Not sure how others  feel  about this but it would be great if you could add page edit screen save/update to be ajax instead of page refresh.

**Comment by moldcraft** [comment]
Theme Settings page is created from scratch with our html and save functionality.

But page update/save is created by WordPress and we just use the `save_post` action. I don't know if it's a good idea to make page update/save with ajax. There are some plugins that does that?

**Comment by danyj** [comment]
No I dont know any plugins that do this , but is pain when you have a page with builder setup and have several builder elements + post options , you get lost when the refresh occurs. Thus I was asking if you were thinking about something like this.

**Comment by moldcraft** [comment]
Maybe we will do this, but someone should investigate if it's possible to do this "in a WordPress way" without writing weird code. Personally I give this issue low priority.

You can try to open a ticket in [WordPress bug-tracker](https://core.trac.wordpress.org/tickets/latest) to see what they think about this idea (or ask on stackoverflow or something similar)

**Comment by moldcraft** [comment]
I am sure this issue will be open for a very long time without activity. So I am closing it.
If you will find some plugins that implements post ajax save or someone from WordPress bug-tracker will provide some information, feel free to reopen it.
