### ISSUE TITLE
Recent Posts not showing all category options

### ISSUE THREAD

**Issue by tmattevc** [ThemeFuse/Unyson#2980]
On the recent posts content I'm putting in pages using the Visual Page Builder I'm only seeing the option for 10 categories (shown in alphabetical order) in the dropdown menu under

Blog Categories
Choose which blog categories you want to show

The site I'm working on has around 20 categories and I'm unable to select a category I want to use. Any idea why this might be?

**Comment by ViorelEremia** [comment]
I think this option is from theme some option types have the possibility to set max nr of categories such as for exemple multi select, or if is used option type like select then is set a limit to param choices try to contact you theme developer, if you are theme developer then remove limit on this option type: http://manual.unyson.io/en/latest/options/built-in/introduction.html#content
