### ISSUE TITLE
Blank Page (Error 500) after Unyson Page Builder or Shortcodes extensions activation

### ISSUE THREAD

**Issue by aryhenrique** [ThemeFuse/Unyson#2981]
Hello All,
I am facing a problem with a fresh installation of a Theme ([Shoom](https://themeforest.net/item/shoom-creative-multipurpose-wordpress-theme/20276754)) I just bought and that came with Unysion Plugin Integration. I just finished install everything. but, when I click to add a new page, or edit an existing one, I am getting a entire blank page with an Error 500, as you can see in the print below.

If I deactivate (inside Unyson) the extensions: Page Builder and Wordpress ShortCodes, the Page Editor works fine. Could you, please, help me understanding if I am doing something wrong?

**I am using PHP 5.4 and Unyson 2.7.8 versions**

**Before extensions activation:**
![brfore-plugin](https://user-images.githubusercontent.com/8583400/32066552-ea1fb728-ba5e-11e7-82f2-4a88b47acd82.jpg)

**After extensions activation:**
![after-plugin](https://user-images.githubusercontent.com/8583400/32066460-924ae50e-ba5e-11e7-9c97-0d28fb46b728.jpg)

Thanks in advance!

**Comment by ViorelEremia** [comment]
First try to use unyson with a default wordpress theme to check if unyson doesn't have with your server, if everthing is allright then I think is a theme problem. Usually error 500 is generated by a fatal error in php.
