### ISSUE TITLE
SyntaxError JSON parse

### ISSUE THREAD

**Issue by vizard777** [ThemeFuse/Unyson#2982]
I encountered an error in page builder upon editing a section.
![pagebuildererror](https://user-images.githubusercontent.com/33133957/32071610-61d03de8-bac2-11e7-82a2-2bfdf5203afc.JPG)

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com
