### ISSUE TITLE
Max Table Shortcode Rows

### ISSUE THREAD

**Issue by stanislav-chechun** [ThemeFuse/Unyson#2984]
I have a problem with table shortcode:

When I adding more 21 row table now showing 22,23 etc, in admin panel I have 21 row too. Can you help me with it?

**Comment by ViorelEremia** [comment]
Increase [max upload file](http://docs.themefuse.com/the-core/your-theme/theme-settings/how-to-set-a-maximum-file-upload-size) and [max input vars](http://docs.themefuse.com/the-core/your-theme/theme-settings/how-to-increase-the-maximum-input-variables-limit)
