### ISSUE TITLE
Broken Content 

### ISSUE THREAD

**Issue by GEORGE10779** [ThemeFuse/Unyson#2985]
Hey guys, please help. Ive already contacted support with no luck. 
-When viewing the Unyson testimonials plugin, the background image has gone grey and I cannot change the image. Please show me how to change that background image. 
-When submitting a form using the Unyson form creator, I get this message "Sorry you are an error in ajax, please contact the administrator of the website"

Please help urgently.

**Comment by ViorelEremia** [comment]
What theme do you use? These are theme issues we can't help you if you don't provide more info.

**Comment by GEORGE10779** [comment]
The Core

**Comment by GEORGE10779** [comment]
Ive managed to sort out issue one. But the contact form is still very broken. Ive tried disabling all the other plugins with no luck. I also tried disabling modsecurity but bluehost says they cant do this.

**Comment by andronic90** [comment]
Hi, please contact the theme support:  https://support.themefuse.com/hc/en-us/requests/new or write an email to: support@themefuse.com
