### ISSUE TITLE
 Slow UNYSON WOOCOMMERCE

### ISSUE THREAD

**Issue by ank01000** [ThemeFuse/Unyson#2987]
Hello, I have a sluggish level of adding to cart items, ordering process .. if I disable more problem.

Here is the site concerned: https://www.vieonaturelle.com

I disabled one by one all modules is unyson that is involved.

**Comment by ViorelEremia** [comment]
I don't understand if you disable unsyson the problem still exists? Or you mean all unyson extensions one by one?

**Comment by ank01000** [comment]
Hello, if I disable UNYSON, the site and around the shop becomes more fluid. This is the Unyson LAYOUT module, which is in question

**Comment by ViorelEremia** [comment]
Ok, you mean "Unyson LAYOUT" is an extension in your unyson's extensions list? I don't have your theme so i tested with the default wordpress themes and woocommerce and everything is fine. For inspect this issue I need more information.

**Comment by ank01000** [comment]
For me it's called l ayout copy screen and my theme is FlyCofee. I provide it to you if you want?
![ok](https://user-images.githubusercontent.com/33287714/32376773-11a31522-c0a6-11e7-9076-7058f66a230a.jpg)

**Comment by ViorelEremia** [comment]
viorel [ a ] themefuse [ dot ] com

**Comment by ank01000** [comment]
not understood ?

**Comment by ViorelEremia** [comment]
Drop your wordpress theme I'll take a look: viorel [ a ] themefuse [ dot ] com

**Comment by ank01000** [comment]
thank you very much

https://drive.google.com/file/d/0BzXJYBVbPghNdkNKMEo1eFlDWEE/view?usp=sharing

**Comment by ank01000** [comment]
Hello, you found something?

**Comment by ViorelEremia** [comment]
I tested on our test server and everything is fine, I can't understand why it is happening on your see here: http://test.themefuse.com/viorel/product-category/clothing/
What configurations has your server?

**Comment by ank01000** [comment]
First of all thanks for the tests, here is the server configuration
![serveur](https://user-images.githubusercontent.com/33287714/32439022-134c6b14-c2ed-11e7-9914-c4b0c8e5ece9.jpg)

**Comment by ViorelEremia** [comment]
I mean others configurations like: ram, cpu

**Comment by ank01000** [comment]
![serveur](https://user-images.githubusercontent.com/33287714/32440934-9dffe706-c2f5-11e7-95f2-2e250386fdd7.jpg)

**Comment by ViorelEremia** [comment]
Ok it is good, you need to inspect on your server who consumes so much time. If you disable unyson plugin then add to cart button is much faster?

**Comment by ank01000** [comment]
Indeed if I disable UNYSON the addition to the cart is immediate

**Comment by ViorelEremia** [comment]
Ok, drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com
I have tried on our test server and can't see any problems.

**Comment by ank01000** [comment]
Hello, I'm sorry but my client does not want me to provide access to her site to third parties. Thank you for all the tests.
