### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by w4rlock-9000** [ThemeFuse/Unyson#2988]
Can't apply Russian language for Unyson plugin, .po and .mo are present.

![local](https://user-images.githubusercontent.com/33316244/32321801-0b16dcf6-bfcb-11e7-8bd0-6a580f7e22a0.JPG)

**Comment by ViorelEremia** [comment]
I do not know what you want to do, if you want to change language just change from admin dashboard -> settings ->language then these files are loaded if you want to change something use plugins like polylang, wpml, loco
