### ISSUE TITLE
how to use get_post_meta and option upload

### ISSUE THREAD

**Issue by Alikke** [ThemeFuse/Unyson#2989]
Hi, Unyson !
Is this possible using the type "upload" . I expected that after you download the images are saved, the values in arbitrary fields, but it didn't work. How to auto save before and after ?

This is my code:

` 'demo-option-id'  =>  array ( 
'type'  =>  'upload, 
'fw-storage'  =>  array ( 
        'type'  =>  'post-meta', 
        'post-meta'  =>  'demo_option-id', 
    ), 
) `

**Comment by ViorelEremia** [comment]
I do not understand what do you want to do.

**Comment by ViorelEremia** [comment]
You mean: `get_post_meta(get_the_ID(), 'demo_option-id', true)`

**Comment by Alikke** [comment]
I want to do so using the upload option to save values post-meta in custom fields. 
**Empty to load the image**
![edit post 1 wordpress](https://user-images.githubusercontent.com/21213426/32366757-c62a099e-c0a9-11e7-81e9-cf5a742d30c4.png)


**And with the value after loading the image**

![edit post 2 wordpress](https://user-images.githubusercontent.com/21213426/32367046-e8b437c2-c0aa-11e7-8008-be0ae4f84179.png)



Sorry I have elementary English level

**Comment by ViorelEremia** [comment]
Ok, you want after saving to have a new custom field "demo_option-id" with value attachment id from option type unyson upload?

**Comment by Alikke** [comment]
yeah right, after saving appeared after the closure is removed

**Comment by ViorelEremia** [comment]
You can find some hooks in unyson/framework/helpers/meta.php but why you need that?

**Comment by Alikke** [comment]
I want to add an image to entries in a standard format

**Comment by ViorelEremia** [comment]
Why you want to do it?
