### ISSUE TITLE
Columns not getting CSS classes on front end

### ISSUE THREAD

**Issue by jeffstahlin** [ThemeFuse/Unyson#299]
I have been struggling with this issue for the past day and can't seem to find any way to resolve it. In the page builder I have set up a page with a section, within which I have a text box and then below I want to add three columns with icon boxes. Everything works just fine other than the columns that do not have any CSS classes applied on the front end, meaning all my icon boxes span the whole width of the page. 

I've tried adding an options file for the columns in the *framework-customizations/extensions/shortcodes/shortcodes/column* folder, which worked fine, however overriding the view to take on the new values from the options was impossible. It never takes on any changes that I make. I even went into the *framework/extensions/shortcodes/shortcodes/column* folder to see if changing anything there would work, but again, nothing.

I'm quite lost right now and without being able to use a grid in the page builder it feels kind of useless. This is the only thing keeping me from moving ahead in my project, any ideas on what the issue could be here? If you need any more information just let me know.

**Comment by moldcraft** [comment]
I created `{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/views/view.php`, added a test class and the changes were reflected in frontend.

It's weird that on your side columns doesn't have default grid classes. Can you give me a link to your site or send me your theme zip to `unyson[at]email.com` so I can inspect it?

**Comment by moldcraft** [comment]
Bootstrap shortcodes plugin and Unyson creates the same shortcode `[column]`, and bootstrap shortcode overwrites it.

If you go to `{theme}/inc/bootstrap-shortcodes/bootstrap-shortcodes.php` and comment line `84`

```php
// 'column',
```

the Unyson columns will start to work.

**Comment by jeffstahlin** [comment]
Thank you moldcraft, this worked. Really appreciate your time.
