### ISSUE TITLE
PHP Zip issue

### ISSUE THREAD

**Issue by kimiekat76** [ThemeFuse/Unyson#2990]
I have GoDaddy as a provider, PHP zip module is active. I tried to update it and was told it was the most updated version. I updated all the plugins and newest version of wordpress. I still get the same error:

"Oops, Unyson Backup requires PHP Zip module but it is not enabled on your server. If you are not familiar with PHP Zip module, please contact your hosting provider."

I tried a different site on GoDaddy and got the same issue. It fails to start even though the module is loaded and active.

**Comment by ViorelEremia** [comment]
Get phpinfo and paste it here.

**Comment by kimiekat76** [comment]
Module Name Version
Archive_Zip 0.1.2

Is this what you need?

ViorelEremia wrote:

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by kimiekat76** [comment]
Set you up via the wordpress users section. Do you also need access to 
godaddy?

ViorelEremia wrote:

**Comment by kimiekat76** [comment]
I assume you would need access since all my websites on my hosting 
package is failing. I do have another site on a lower end godaddy 
package that works.

ViorelEremia wrote:

**Comment by ViorelEremia** [comment]
Ok I tried to log in and it isn't working

**Comment by kimiekat76** [comment]
Which login failed? WordPress or ftp?

**Comment by ViorelEremia** [comment]
You sent me a message with title - "An invitation to manage resources"? When i try to log in they ask me to log in so when i try create an account, and a field is rquired "Support PIN". The second link is not working "Authentication failed. You entered an incorrect username or password."

**Comment by kimiekat76** [comment]
Sent an invite via godaddy to access account


ViorelEremia wrote:
>
> viorel [ a ] themefuse [ dot ] com

**Comment by ViorelEremia** [comment]
I cant access your account godaddy maybe there is an access limitation territoryal? 
Authentication failed. You entered an incorrect username or password.

**Comment by kimiekat76** [comment]
It says you access is pending. I didn't set up a username or a password. 
It should send you an email and have you do the setup for those two items


ViorelEremia wrote:

**Comment by ViorelEremia** [comment]
![asdfasdfasdf](https://user-images.githubusercontent.com/28967378/32446988-4f514e10-c313-11e7-970c-b121e4d47db9.png)
When i click on the button "Authentication failed. You entered an incorrect username or password."

**Comment by ViorelEremia** [comment]
Please when you have all credentials send them to me with nr of issue from github

**Comment by kimiekat76** [comment]
I'll contact godaddy and see what's up. Then we'll proceed from there. I 
will keep you posted.

ViorelEremia wrote:
