### ISSUE TITLE
Missing colour picker fields

### ISSUE THREAD

**Issue by zomfg-zombie** [ThemeFuse/Unyson#2991]
As of 2.7.9, cannot pick background or border colours for buttons. Field is completely missing.

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by gertvanw** [comment]
Same problem here, is there a fix for it?

**Comment by gertvanw** [comment]
For me, it also stopped working since the last update (I'm now on 2.7.9)

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2997

**Comment by alemran94** [comment]
I faced the issue on builder's shortcode. Also, the option type is working fine in Customizer as you mentioned.  

I think it's a CSS issue, here is a quick fix (not permanent)  [#2997](https://github.com/ThemeFuse/Unyson/issues/2997#issuecomment-342111744)
