### ISSUE TITLE
Postype Options Not working

### ISSUE THREAD

**Issue by quocvietht03** [ThemeFuse/Unyson#2992]
Hi Team,
I used Unyson and update to version 2.7.9
Post Options function not working http://prntscr.com/h5lkz9
Please, check it and update in next version.

**Comment by ViorelEremia** [comment]
What is not working? I tested, everything is fine.

**Comment by quocvietht03** [comment]
Hi again!
I have added post options in post working fine in version 2.7.7.
But i update in version 2.7.9 not show. You can see in video [here](https://drive.google.com/file/d/1kRCHFAE-m2HxkSeSOyz_ZmlLORK18pt_/view?usp=sharing)
Thank you for see!

**Comment by ViorelEremia** [comment]
I tested in my end and everything is fine can you share your post.php's options code

**Comment by quocvietht03** [comment]
my file post.php option [here](https://drive.google.com/file/d/1Ls0LFkSU2Qs3oLeP_Dx-kwHoZ_kinvIu/view?usp=sharing)

**Comment by ViorelEremia** [comment]
@quocvietht03 replace backend.php.
@danyj  please test

**Comment by quocvietht03** [comment]
Perfect! It's working fine now, thanks for your help!

**Comment by danyj** [comment]
@ViorelEremia looks like they did not nest the options properly 
http://prntscr.com/h6uia4

looking at that image that is not  a box and it should be  ,  I just did an update and mine are still visible

**Comment by ViorelEremia** [comment]
@danyj you mean container type: https://drive.google.com/file/d/1Ls0LFkSU2Qs3oLeP_Dx-kwHoZ_kinvIu/view

**Comment by ViorelEremia** [comment]
For our themes everything is good with all container types

**Comment by danyj** [comment]
exactly , should be like this http://prntscr.com/h6unw1

```
box 
    tab
    tab
```

**Comment by ViorelEremia** [comment]
Ok guys, I don't understand anymore, is there any issue?

**Comment by danyj** [comment]
on my end it works ok ,   @TrangDinhVan @quocvietht03 show options array please
