### ISSUE TITLE
[bug] Contact form Test connection trows js error

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2993]
See this please , 

`Cannot read property 'split' of undefined`
looking for nameprefix wich is not there

![screenshot_10](https://user-images.githubusercontent.com/2340172/32399753-1b4e3cfc-c0f9-11e7-9869-f3c774a2f0e7.jpg)

**bug trace**

![screenshot_5e](https://user-images.githubusercontent.com/2340172/32399740-f4076060-c0f8-11e7-88cb-639d8dd76bb5.jpg)

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson-Mailer-Extension/commit/93828a57b88d1f05394ae67bf6f74f6eed4d6235

**Comment by danyj** [comment]
@ViorelEremia  Same bug again 

http://prntscr.com/i4mnbe


your previous fix is in
