### ISSUE TITLE
[bug] SEO tags meta name  bug

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2994]
SEO  tags are marked as description , so if you have description and tags the last one counts which end up being tags used instead of the actual description.  

Add both on a page than scrape the page via Facebook debugger, you will see that it shows the keywords as description , 

meta name should be 

`<meta name="keywords"`

for keywords

**Comment by ViorelEremia** [comment]
I can't reproduce that. in front I have two meta keywords with keyword and description with description or is something else.

**Comment by danyj** [comment]
Add both , description and keywords ,  in html you will see 

2   <meta name="description"

**Comment by danyj** [comment]
Strange , I dont see it on my local , but live I see this 


![screenshot_30](https://user-images.githubusercontent.com/2340172/32789867-226bb584-c95d-11e7-8a7d-5a4d624317d4.jpg)


![screenshot_31](https://user-images.githubusercontent.com/2340172/32789887-3246045a-c95d-11e7-8485-35e2a3331f51.jpg)

**Comment by danyj** [comment]
ok , if you have it set in page SEO options + in Unyson  SEO settings and than you set that page as home , you get double description

**Comment by ViorelEremia** [comment]
I did that because it was easy, but in the future we may no longer support that extension.
