### ISSUE TITLE
Bug In RGBA Color Picker After Updating to Unyson 2.7.9

### ISSUE THREAD

**Issue by shahinurcse** [ThemeFuse/Unyson#2996]
in version 2.7.9, the rgba color picker is not visible.
my all theme is broken, i've tried to look into the core Unyson but couldn't find the issue.

**Comment by ViorelEremia** [comment]
Share your code.

**Comment by shahinurcse** [comment]
sorry, i've fixed it.

**Comment by shahinurcse** [comment]
its solved :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by xttn** [comment]
are you check it on WP 4.9 and Unyson 2.7.10 ?

**Comment by shahinurcse** [comment]
yes
