### ISSUE TITLE
problem with option type "rgba-color-picker" after updating to v2.7.9

### ISSUE THREAD

**Issue by alemran94** [ThemeFuse/Unyson#2997]
After updating to 2.7.9, the rgba-color-picker type ain't working properly. all it shows a blank space. i've attached an screenshot and code. Please take a look.
Note: i'm testing with previous version (2.7.8) which is working fine.

```
'color_xyz' => array(
            'label' => __('color s', 'eventcastle'),
            'desc' => __('Select the background color', 'eventcastle'),
            'value' => '',
            'type' => 'rgba-color-picker'
        ),
```

![image](https://user-images.githubusercontent.com/32483285/32431709-b2298e9a-c2fe-11e7-902d-868485200ac9.png)

**Comment by ViorelEremia** [comment]
Inspect why is it happening? I tested with your code and is fine in my end.

**Comment by liondekam** [comment]
We can report the same issue. After updating to 2.7.9 on chrome issue appears.
Seems some script hide input field.
http://d.pr/i/xEgiBH

**Comment by liondekam** [comment]
Seems other users already reported this issue 3 days ago
https://github.com/ThemeFuse/Unyson/issues/2991

We can send you credentials for installation where issue appears.

**Comment by ViorelEremia** [comment]
@liondekam drop here: viorel [ a ] themefuse [ dot ] com

**Comment by alemran94** [comment]
I've added a few line of CSS and it fixed the rgba-color-picker issue. Hopefully it will help to solve issue permanently.

```
.fw-backend-option-input-type-rgba-color-picker .wp-color-result{
	display: block;
	width: 45px !important;
	height: 16px !important;
	position: relative;
}
```

Also, the predefined color palates looks mis-sized because of the following CSS:

```
.fw-backend-option-input-type-rgba-color-picker .iris-palette {
    height: 33px !important;
    width: 33px !important;
}
```

![image](https://user-images.githubusercontent.com/32483285/32437451-9f5698ae-c311-11e7-9ab4-4cf6bf662eeb.png)

:)

**Comment by ViorelEremia** [comment]
Guys can someone tell me wtf is with this option type. I tested with some themes and everything is fine.
![optionsfasdf](https://user-images.githubusercontent.com/28967378/32447226-211612a0-c314-11e7-8c89-8986f20fea68.png)

**Comment by pear1** [comment]
Some issue here and multiple other Unyson users.
Waiting for the fix, because CSS snippets doesn't work so well.

**Comment by ViorelEremia** [comment]
@pear1 the problem will not be fixed because I can not see it, if you want to be fixed give me more information. It would be good today because it will be an update for unyson.

**Comment by pear1** [comment]
@ViorelEremia What kind of information do you need?

**Comment by ViorelEremia** [comment]
would be ideal if i had ftp and admin credentials from a site what has this issue

**Comment by pear1** [comment]
At the moment I don't have any test server to give credentials (only local), but I can set it up for your test site if that is possible.

**Comment by ViorelEremia** [comment]
Can you inspect who rewrites the styles

**Comment by pear1** [comment]
Can you please try this bellow?
1. Install clean WordPress installation
2. Install stratch-parent theme
3. Install Unyson
4. Go to: Appearance - Theme Settings - Demo Options - RGBA Color Picker
![colorpicker](https://user-images.githubusercontent.com/10400351/32488252-b253992c-c3b4-11e7-9bf0-ee02b1418e93.png)

**Comment by ViorelEremia** [comment]
![asdfasdf-df](https://user-images.githubusercontent.com/28967378/32488634-091ce942-c3b6-11e7-9875-cc1ed98ebc20.png)
![asdfasdfsdafasd](https://user-images.githubusercontent.com/28967378/32488636-0939e98e-c3b6-11e7-9fdc-e5106d517822.png)

**Comment by pear1** [comment]
Are you using Unyson version directly from WordPress.org?

**Comment by pear1** [comment]
If it still doesn't work, where can I send WordPress login data? (I will create installation for you)

**Comment by pear1** [comment]
@ViorelEremia Did you manage to replicate it?

**Comment by ViorelEremia** [comment]
@pear1 can you try this css in: plugins\unyson\framework\includes\option-types\rgba-color-picker\static\css\styles.css
`.fw-backend-option-input-type-rgba-color-picker .fw-option-help-in-input {
    top: 2px !important;
}
.fw-backend-option-input-type-rgba-color-picker .wp-picker-holder {
    position:absolute;
    z-index:99999;
}
.fw-backend-option-input-type-rgba-color-picker .wp-picker-clear {
    height: 23px !important;
}
.fw-backend-option-input-type-rgba-color-picker .wp-color-result {
    height: auto;
    box-shadow:none;
}
.fw-backend-option-input-type-rgba-color-picker input {
    max-width: 140px !important;
}
#customize-controls .customize-pane-child .customize-control:last-child .fw-backend-customizer-option .fw-backend-option-type-rgba-color-picker {
    padding-bottom: 220px;
}
/* Picker WP style */
.wp-color-result {
     background-color: #f7f7f7;
     border: 1px solid #ccc;
     -webkit-border-radius: 3px;
     border-radius: 3px;
     cursor: pointer;
     height: 22px;
     margin: 0 6px 6px 0;
     position: relative;
     -webkit-user-select: none;
     -moz-user-select: none;
     -ms-user-select: none;
     user-select: none;
     vertical-align: bottom;
     display: inline-block;
     padding-left: 30px;
     -webkit-box-shadow: 0 1px 0 #ccc;
     box-shadow: 0 1px 0 #ccc;
     top: 0;
 }
.wp-color-result:focus,
.wp-color-result:hover {
    background: #fafafa;
    border-color: #999;
    color: #23282d;
}
.wp-color-result:after {
    background: #f7f7f7;
    -webkit-border-radius: 0 2px 2px 0;
    border-radius: 0 2px 2px 0;
    border-left: 1px solid #ccc;
    color: #555;
    content: attr(title);
    display: block;
    font-size: 11px;
    line-height: 22px;
    padding: 0 6px;
    position: relative;
    right: 0;
    text-align: center;
    top: 0;
}
.wp-color-result.wp-picker-open:after {
    content: attr(data-current);
}
.wp-color-result:focus:after,
.wp-color-result:hover:after {
    color: #23282d;
    border-color: #a0a5aa;
    border-left: 1px solid #999;
}
.wp-picker-open+.wp-picker-input-wrap {
    display: inline-block;
    vertical-align: top;
}
.wp-picker-container input[type=text].wp-color-picker {
    width: 65px;
    height: 25px;
    font-size: 12px;
    font-family: monospace;
    line-height: 16px;
    margin: 0;
}
.wp-picker-container .button {
    margin-left: 6px;
}`

**Comment by pear1** [comment]
It is working now, but color picker layout still is somewhat broken.

![screenshot_2](https://user-images.githubusercontent.com/10400351/32494970-6351dba0-c3cc-11e7-9a4b-55392eb88006.png)

**Comment by ViorelEremia** [comment]
Try to remove cahse browser is still the same

**Comment by pear1** [comment]
Yes, it still is the same.
But at the moment the only issue is with those color blocks size, other than that everything works.

**Comment by ViorelEremia** [comment]
@pear1 Can you inspect who is overwrite styles for colors
![asdfasdfasdf](https://user-images.githubusercontent.com/28967378/32495437-4edbf942-c3ce-11e7-9285-7bb24f2401a1.png)

**Comment by pear1** [comment]
![screenshot_3](https://user-images.githubusercontent.com/10400351/32495587-f19a2096-c3ce-11e7-96d1-4c9939717c84.png)

Yes, here you can see that.

**Comment by ViorelEremia** [comment]
@pear1  Remove all css from: plugins\unyson\framework\includes\option-types\rgba-color-picker\static\css\styles.css 
and replace all with:
`.fw-backend-option-input-type-rgba-color-picker .fw-option-help-in-input {
    top: 2px !important;
}
.fw-backend-option-input-type-rgba-color-picker .wp-picker-holder {
    position:absolute;
    z-index:99999;
}
.fw-backend-option-input-type-rgba-color-picker .wp-picker-clear {
    height: 23px !important;
}
.fw-backend-option-input-type-rgba-color-picker .wp-color-result {
    height: auto;
    box-shadow:none;
}
.fw-backend-option-input-type-rgba-color-picker input {
    max-width: 140px !important;
}
#customize-controls .customize-pane-child .customize-control:last-child .fw-backend-customizer-option .fw-backend-option-type-rgba-color-picker {
    padding-bottom: 220px;
}
/* Picker WP style */
.wp-color-result {
     background-color: #f7f7f7;
     border: 1px solid #ccc;
     -webkit-border-radius: 3px;
     border-radius: 3px;
     cursor: pointer;
     height: 22px;
     margin: 0 6px 6px 0;
     position: relative;
     -webkit-user-select: none;
     -moz-user-select: none;
     -ms-user-select: none;
     user-select: none;
     vertical-align: bottom;
     display: inline-block;
     padding-left: 30px;
     -webkit-box-shadow: 0 1px 0 #ccc;
     box-shadow: 0 1px 0 #ccc;
     top: 0;
 }
.wp-color-result:focus,
.wp-color-result:hover {
    background: #fafafa;
    border-color: #999;
    color: #23282d;
}
.wp-color-result:after {
    background: #f7f7f7;
    -webkit-border-radius: 0 2px 2px 0;
    border-radius: 0 2px 2px 0;
    border-left: 1px solid #ccc;
    color: #555;
    content: attr(title);
    display: block;
    font-size: 11px;
    line-height: 22px;
    padding: 0 6px;
    position: relative;
    right: 0;
    text-align: center;
    top: 0;
}
.wp-color-result.wp-picker-open:after {
    content: attr(data-current);
}
.wp-color-result:focus:after,
.wp-color-result:hover:after {
    color: #23282d;
    border-color: #a0a5aa;
    border-left: 1px solid #999;
}
.wp-picker-open+.wp-picker-input-wrap {
    display: inline-block;
    vertical-align: top;
}
.wp-picker-container input[type=text].wp-color-picker {
    width: 65px;
    height: 25px;
    font-size: 12px;
    font-family: monospace;
    line-height: 16px;
    margin: 0;
}
.wp-picker-container .button {
    margin-left: 6px;
}`

**Comment by pear1** [comment]
Thanks, it works great.
Please include that in this update.
