### ISSUE TITLE
v2.7.9 does not recognize post type option anymore

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#2998]
After upgrading v2.7.9, Unyson does not work with the options defined in 
`framework-customizations\theme\options\posts\post.php, post-type.php` anymore.
I tried downgrading to 2.7.8 and it worked as normal, please fix.

**Comment by danyj** [comment]
> does not work
what does not work? 
backend , frontend , you cant see options , what ?

**Comment by ViorelEremia** [comment]
is related to https://github.com/ThemeFuse/Unyson/issues/2992 ?

**Comment by TrangDinhVan** [comment]
That's true @ViorelEremia , sorry for not searching first. And the solution is that we need to replace the file backend.php in the wp-content/plugins/unyson folder? I did it and the problem solved now but working with plugins folder must not be the way we can do.

**Comment by ViorelEremia** [comment]
Ok, this is going to be an update this week.
