### ISSUE TITLE
2 Issues/ recomandations on ThemeForest

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson#300]
@Unyson

First to say that I like this framework, especially page builder and I would like to use it in my themes.

However I have 2 issues with it.

1. It is not really an issue but I noticed that theme’s custom post types need to have defined menu position 4 or greater number because if they don’t have menu position defined or have 2 or 3 then first of them is somehow rewrited by Unyson link in Dashboard. It somehow disappears. But everything is fine if menu position is 4.

2. Is it possible that custom created shortcodes (inside folder “framework-customizations/etc…”) can be added via plugin, not in theme? I would like to create new shortcodes but since we got official response from Themeforest staff that framework will be allowed only as plugin I’m not sure is it allowed to add this customization in theme?

http://themeforest.net/forums/thread/meet-unyson-the-free-drag-drop-wordpress-framework/141818?page=18&message_id=1222034#1222034

**Comment by thednp** [comment]
Basically you create your own extensions/shortcodes anywhere outside your theme, include them in your plugins, make sure to use same folder structure as the UNYSON plugin except the <code>framework</code> will be <code>framework-customizations</code> and give it a swirl. 

I will go like that and I think it's gonna be the same recommendation from Unyson team.

**Comment by moldcraft** [comment]
> Is it possible that custom created shortcodes (inside folder “framework-customizations/etc…”) can be added via plugin, not in theme?

In [v2.2.0](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/39) it's possible to create extensions from plugins (or any directory)

**Comment by GheorgheP** [comment]
Hi

About first problem, the problem come from wordpress, they even describe it in [add_menu_page()](http://codex.wordpress.org/Function_Reference/add_menu_page#Parameters). Unfortunately you cannot set decimals to `menu_position` of custom posts.
