### ISSUE TITLE
Cannot edit Main Color in Everglades Theme

### ISSUE THREAD

**Issue by coggicc** [ThemeFuse/Unyson#3000]
I tried to update the Main Color in Appearance/Theme Settings/Styling.  Upon clicking the Styling tab on the left side, I got an error in Chrome as outlined below.  I am not able to change the Main Color.

![error](https://user-images.githubusercontent.com/17034403/32451992-e549aefc-c2dd-11e7-8fc1-d6b001886c6d.PNG)

**Comment by danyj** [comment]
contact the theme developer , this is framework support.

**Comment by pear1** [comment]
It could be related to https://github.com/ThemeFuse/Unyson/issues/2997 when all color pickers are gone.
