### ISSUE TITLE
Form submission loader

### ISSUE THREAD

**Issue by onisiforos7** [ThemeFuse/Unyson#3002]
Is it possible to have a loader after submitting a form? its not user friendly that it just wait for the page to reload. if the request is slow then the user has no idea if the form was submitted or not.

Thank you

**Comment by ViorelEremia** [comment]
By default unyson dosen't have it but you can add some js for submit form event.
`$( ".fw_form_fw_form" ).submit(function( event ) {
  your preloader.
});`

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/blob/f821fabed94cfd66eee16392b2b5cc9cce7e4ffa/framework/static/js/fw-form-helpers.js#L266
