### ISSUE TITLE
Addable popup dynamic title

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#3003]
Hi guys,

I just wondered if this is possible, or if you have any suggestions on displaying a CPT title in an addable popup, here's my code.

`$options = array(`
`     'tabs' => array(`
`		'type'          => 'addable-popup',`
`		'label'         => __( 'Tabs', 'movie-star' ),`
`		'popup-title'   => __( 'Add/Edit Tab', 'movie-star' ),`
`		'desc'          => __( 'Create your tabs', 'movie-star' ),`
`		'template'      => get_the_title('{{=movies}}'),`
`		'popup-options' => array(`
`			'movies'  => array(`
`			    'type'       => 'multi-select',`
`				'label'      => esc_attr__( 'Movies', 'movie-star' ),`
`				'population' => 'posts',`
`				'source'     => 'movie',`
`				'limit' 	 => false,`
`				'desc'       => esc_attr__('Select 1 or more movies.', 'movie-star'),`
`			),`
`		),`
`	)`
`);`

If I just use "movies" it'll just return the ID.

Thanks

**Comment by ViorelEremia** [comment]
The template param is not for add any option type output, it is added so you can rename the collapsed item I mean you can add only a text input so user can name the item. I tried to solve it to work with more options but is very complicated. The only way is to add an option type text so user can alone to insert a name which he wants.

**Comment by klvmedia** [comment]
Thanks for your response and efforts, appreciated.
