### ISSUE TITLE
Internal error 500 after activating Unyson with vanilla WP 2.8.3 and standard theme

### ISSUE THREAD

**Issue by VedmakGitHub** [ThemeFuse/Unyson#3004]
Dear All,
I have vanilla WP 4.8.3 without any plugins and non-standard themes, Windows hosting (GoDaddy). Activating Unyson plugin (2.7.10) results in WP showing error 500, WP dashboard is also becomes inaccessible. I tried both PHP 5.4 and 5.6. 
Appreciate your feedback and advise to resolve the issue.

Thank you in advance.

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com
On windows server I never tested unyson.

**Comment by andronic90** [comment]
You can put the wp_debug to true in wp-config.php and inspect this problem

**Comment by VedmakGitHub** [comment]
Hi,
Sorry for no reply. I decided to go an easy way and migrated to Linux
hosting. Hopefully issue will not persist.

P.S. I will leave a comment on the forum

Kind regards,
Mikhail
