### ISSUE TITLE
Unyson builder not showing

### ISSUE THREAD

**Issue by stevenheathmusic** [ThemeFuse/Unyson#3005]
Hey. The Unyson Builder is not showing on my homepage on my website. The website itself is fine but I cannot see the builder to make changes. Everything is updated to current versions.

![screen shot 2017-11-09 at 13 46 42](https://user-images.githubusercontent.com/33519335/32608507-7a66c1d2-c554-11e7-96f1-164f6029f4ba.png)

**Comment by brandlective** [comment]
I am having the same issue. I need to edit our website content urgently. Unyson can you assist us ASAP?

**Comment by ViorelEremia** [comment]
Check if you have latest versions for unyson extensions.
Check console for errors, if there is an error related to tinymce.php contact your hosting support.
Remove cache browser, plugins wordpress, server.
after if problem still exists drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by brandlective** [comment]
<img width="1483" alt="screenshot at nov 10 14-01-22" src="https://user-images.githubusercontent.com/33545556/32659582-a8c7dd1a-c61f-11e7-9d88-60737233ad99.png">

This is the only thing I can think of. I've tried everything you suggested - How can we verify this?

**Comment by ViorelEremia** [comment]
Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

**Comment by brandlective** [comment]
This has made the front end of our site even worse - it's looks completely different (even when all plugins have been restored to activated. This is extremely frustrating, what are we supposed to do now?

**Comment by golderpearl** [comment]
Same Issue I have been facing since I have updated Unyson

**Comment by golderpearl** [comment]
I only have Unyson plugin activated and facing same issue

**Comment by ViorelEremia** [comment]
@golderpearl  update extensions and remove any cache browser, wordpress plugins, server

**Comment by golderpearl** [comment]
I have clear cache browser and cookies too and i have only Unyson plugin activated for now and i am using it on my localhost server also please tell me how do i update extensions?

**Comment by brandlective** [comment]
^ the advice from the contributor here made my problem even worse, so be careful. Go on Themeforest and look up Unyson's proper support page. This worked for us: 

https://haintheme.freshdesk.com/support/solutions/articles/24000013745-visual-page-builder-is-empty-unyson-2-7-6-

**Comment by ViorelEremia** [comment]
@golderpearl 
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
I don't understand why is not working for you, enable debug and check browser console, use theme default wordpress

**Comment by brandlective** [comment]
VirolEremia was very rude in emails, very abrupt and showed ZERO care concerning the problem he or she actually made worse. I would strongly recommend pursuing other sources of support.

**Comment by ViorelEremia** [comment]
@brandlective can you show me what these email?
 ` was very rude in emails` ?

**Comment by ViorelEremia** [comment]
also @brandlective you know what is an open source?

**Comment by duongancol** [comment]
@golderpearl I'm the author of the article above and I'm sure that the solution of @ViorelEremia works well. My solution from the article works but it's outdated option. I'll update it soon.

**Comment by fredand** [comment]
I also have the same problem, tried

* Disable all plugins but unyson
* Change theme
* Have no caching
* No JavaScript errors 

Drawing blanks here, appreciate the help!

**Comment by ViorelEremia** [comment]
@fredand try that: https://github.com/ThemeFuse/Unyson/issues/2805#issuecomment-324139242

**Comment by fredand** [comment]
@ViorelEremia  Tried that, no luck :( have a multisite tho, maybe something to investigate?

**Comment by ViorelEremia** [comment]
@fredand is your site online?

**Comment by fredand** [comment]
@ViorelEremia  Nah sorry about that... i have troubleshooted somewhat in the SQL-server and found that one of the posts includes some CSS that isn't enclosed within "<style>" declaration tags, is that right?

**Comment by ViorelEremia** [comment]
No this is wrong all css must be wrapped in style tags what css? can you show it

**Comment by fredand** [comment]
Its a large "page" that are a fixed landing page. I have "marked white" some sensitive info tho. You can only see the beginning of the post because of its length.

![image](https://user-images.githubusercontent.com/3303610/32835125-4046a0fc-ca05-11e7-9630-767bd31d37a4.png)

**Comment by fredand** [comment]
.rpwe is from the plugin "recent post widget" i think.

**Comment by ViorelEremia** [comment]
@fredand I don't understand.
You said that all plugins have been disabled. Try to remove that css and let me know if everything is fine and please share link of this plugin.
