### ISSUE TITLE
[bug]  Select picks 2 similar selections at once

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3008]
Selects  cant determine  if the value is full match and looks like it cant distinguish between string and number 

test
```

'test' => array(
	'label' => __('Test', 'fw'),
	'type' => 'select',
	'value' => 700,
	'choices' => array(
		700 => __('700', 'fw'),
		'700italic' => __('700italic', 'fw'),
	)
),
```

selected value should be  700 , visual shows 700italic 
![screenshot_26](https://user-images.githubusercontent.com/2340172/32692230-7b35c880-c714-11e7-92f4-26d14ff3f5f3.jpg)

and the select has 2 values selected

![screenshot_27](https://user-images.githubusercontent.com/2340172/32692245-9ed2d896-c714-11e7-9492-07c93abdb6b4.jpg)

I even tried to make the 700 as string but same issue 

`'700' => __('700', 'fw'),
`

**Comment by danyj** [comment]
it works if I force both all choices and selected value to a string , but the list comes from google fonts and select should be able to distinguish between these 2

**Comment by ViorelEremia** [comment]
Please test
