### ISSUE TITLE
Unyson Page Builder

### ISSUE THREAD

**Issue by peterbestinclasss** [ThemeFuse/Unyson#3010]
Page Builder Problem on Unyson.  I cannot view the Unyson Page Builder.  All of my Plugins have been updated.  All Unyson Plugins have been updated.   Still Not Working.    Unyson developer.  Please Advise. 
( I usually use Visual Composer )

**Comment by golderpearl** [comment]
Exactly same issue i am facing with page builder

**Comment by ViorelEremia** [comment]
Can someone to drop me latest version visual composer: viorel [ a ] themefuse [ dot ] com

**Comment by csas64** [comment]
We also have a problem with the Unyson page builder after the update. It was perfect with the wp zoom delicio theme, now it's error and we can not upload any photos, slider do not wotk. Huge problem. Need urgent help. When we try to upload images, it gives an error message. 
Thanks.

**Comment by ViorelEremia** [comment]
@csas64  is it related to https://github.com/ThemeFuse/Unyson/issues/3019?

**Comment by csas64** [comment]
The error message is like in attach.

**Comment by ViorelEremia** [comment]
Have you latest unyson extensions up to date?

**Comment by csas64** [comment]
Yes. everything is updated.

**Comment by ViorelEremia** [comment]
You mean this attach: https://user-images.githubusercontent.com/7818038/32904272-564a3876-caf7-11e7-9635-ac8eb3d0d4db.png

**Comment by csas64** [comment]
<img width="1219" alt="screen shot 2017-11-18 at 11 36 51" src="https://user-images.githubusercontent.com/31131102/32979003-a558e7a0-cc55-11e7-9b10-773ed221648c.png">

**Comment by ViorelEremia** [comment]
Try to replace file on your server: https://github.com/ThemeFuse/Unyson/blob/a36762d8ecbfa0ffd1cf8d772fdabbc97cfe1e7a/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php
Let me know if everything is fine

**Comment by csas64** [comment]
We replaced, but it’s still the same error.

**Comment by csas64** [comment]
We deleted the cache and now it is working. Thank you!

**Comment by philippos-hero** [comment]
am having the same issue.

i have replaced the file and clear the cach but i can't edit in page builder.
my wordpress has been updated to Version 4.9.1 and the Unyson is 2.7.10.

**Comment by snaever** [comment]
I am getting a similar error: `parsererror: SyntaxError: Unexpected token ﻿ in JSON at position 0`

I have tried to deactivate all plugins except Unyson and set the theme to the standard WordPress. I have also tried to change the file you suggested earlier and of course cleared cache, but no luck.
