### ISSUE TITLE
'template' parameter for popup built in option type

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#3011]
`addable-popup` comes with parameter `'template'`, eg: `'template' => '{{=name}}'`,
but `popup` option type does not ([More detail](http://manual.unyson.io/en/latest/options/built-in/popup.html)). That's why we cannot see a part information of its without clicking to trigger it open.
Any advice? Thanks!

**Comment by danyj** [comment]
popup only has a button, it is not adding anything for you to see the picked values when is closed

**Comment by ViorelEremia** [comment]
You mean that you want to add next to edit modal button a value which is predefined by key template. This is a good idea, but for us it has low priority, so you can create aa pull request if it is important to you.
And also this is not easy to do you need to consider every option type defined by template for exemple if templated key define a value that is an attachement id or select etc you need to add diferent render: for image an image for select no value select but value selected option etc.
