### ISSUE TITLE
How to update extensions manually

### ISSUE THREAD

**Issue by roseyazman** [ThemeFuse/Unyson#3012]
Thanks for this great plugin. I need to update extensions manually as my hosting provider did not support plugins, themes and extension installed automatically through wordpress dashboard. 
Please let me know how to update unyson extensions manually. 

regards

**Comment by ViorelEremia** [comment]
Download and unzip them: https://drive.google.com/uc?id=1shfKtwm2QJPauNCSFYFzunwwpiGdApf4&export=download
replace in unyson/framework/extensions/

**Comment by roseyazman** [comment]
thanks for your support... 
regards

**Comment by roseyazman** [comment]
Hi Dear
Once again I need to update extensions manually. Please send me updated files.
regards

**Comment by ViorelEremia** [comment]
You can create a test site on localhost and install unyson and extensions, after that you can copy them in your not supported plugins site so it will be faster and more qualitative.
https://drive.google.com/file/d/1p5M5M8tAu2TGCPrECosiMCA7k2TQqy3R/view?usp=sharing
