### ISSUE TITLE
Page builder shortcode option

### ISSUE THREAD

**Issue by msd1310** [ThemeFuse/Unyson#3013]
In Unyson page builder shortcode,Accordion and tabs doesnt show me type option to choose,only tabs option seen.pls help on this ASAP
Thank you

**Comment by ViorelEremia** [comment]
I don't understand what is not showing give us more details.

**Comment by msd1310** [comment]
As shown below ..To  click options in shortcodes of accordion,Type,Tabs,Custom class suppose to be seen..but i can see only Tabs option when i click on Accordion shortcode,cant see Type option to select.



Click on the shortcode to bring up the options:

Type - lets you select the color your accordion will have. We've built a couple of colors from you to choose from.

Tabs - lets you add content to your accordion. Click the Add button in order to add a tab to your accordion. You can input the title, the content, choose if your your tab's default state (opened or closed) or add an icon.

Custom Class - you can use this option to add a class and further style the shortcode by adding your custom CSS in the style.css file.

**Comment by ViorelEremia** [comment]
Ok, it's not clear yet. You are a developer or you want to use unyson for your website? 
You added some options that is not showing in shortcode accorodion or tabs is not clear.
Show some screenshots, what theme do you use?
I must understand you before can I help you.

**Comment by msd1310** [comment]
![screenshot from 2017-11-14 13-54-44](https://user-images.githubusercontent.com/13584849/32823402-1de66580-ca03-11e7-95e4-1693e0f0417c.png)
you can see in above screenshot,in Accordion shortcode..it starts with type..i cants see type option at my side
Below is screenshot ,what i can view
![screenshot from 2017-11-14 18-20-46](https://user-images.githubusercontent.com/13584849/32823486-69fcf240-ca03-11e7-8f85-02c14c7c3376.png)
can you pls help me on this,how to get that TYPE option in accordion.
Thank you

**Comment by msd1310** [comment]
I am using Modular theme.

**Comment by ViorelEremia** [comment]
Oook, this is a theme issue, write theme developer support here is only unyson plugin support. Unyson is a plugin which developers of wordpress themes can build their own shortcod or extend existing shortcodes, so here we don't know what did they or how they did that. Write theme dev support they are obliged to help you, we can't help you.

**Comment by msd1310** [comment]
ok.Thank you for reply !
