### ISSUE TITLE
White box SLIDER-OPTIONS, Theme 39694372-blink 

### ISSUE THREAD

**Issue by geier64** [ThemeFuse/Unyson#3015]
This was your answer:
Next update will solve this, or you can replace on your server file: framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php with this file:
https://github.com/ThemeFuse/Unyson/blob/4de7870e50543d54fe4fe5f7d6dbf4eb9bd53471/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php
After that remove any cache: browser, server, plugins.

# BUT:

**Comment by ViorelEremia** [comment]
Hey is not simple to do that here are conflicts between plugins in tinymce object js. I have seen that it does not work from your previous message and im tring to solve it now

**Comment by geier64** [comment]
Ok, Thank You. Sorry.

**Comment by ViorelEremia** [comment]
Can you try again? and let me know if everything is fine.

**Comment by geier64** [comment]
Hi, my colleague will try it later and I write you tomorrow morning, ok? Thank you for your help.

**Comment by ViorelEremia** [comment]
Ok

**Comment by geier64** [comment]
Hey there, it works. :-) Thank you so much.
