### ISSUE TITLE
Add a new tab to builder for own shortcodes

### ISSUE THREAD

**Issue by ImprobableCode** [ThemeFuse/Unyson#3017]
Is it possible for me to add a new tab next to Media Elements to add my own custom shortcodes?

**Comment by ViorelEremia** [comment]
Yes, you can read here: http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file
see param `tab`. It allow you to change tab what will be alphabetically arranged in admin. To choose the position of the tab is not possible.
