### ISSUE TITLE
parsererror: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by dobak** [ThemeFuse/Unyson#3019]
Hello,

when I'm tying to edit any element I got error;

![image](https://user-images.githubusercontent.com/7818038/32904272-564a3876-caf7-11e7-9635-ac8eb3d0d4db.png)

all is updated 
 WordPress 4.9 | Unyson 2.7.10 | Theme 1.0.27 (extensions too)

Please help

**Comment by ViorelEremia** [comment]
If you can't wait for next update(on Tuesday) try to edit this file: https://github.com/ThemeFuse/Unyson/commit/a36762d8ecbfa0ffd1cf8d772fdabbc97cfe1e7a
Let me know if everything is fine.

**Comment by csas64** [comment]
<img width="1219" alt="screen shot 2017-11-18 at 11 36 51" src="https://user-images.githubusercontent.com/31131102/32978981-725a3d9a-cc55-11e7-825c-b3151e3b0c56.png">

**Comment by snaever** [comment]
I am getting a similar error: `parsererror: SyntaxError: Unexpected token ﻿ in JSON at position 0`

I have tried to deactivate all plugins except Unyson and set the theme to the standard WordPress. I have also tried to change the file you suggested earlier and of course cleared cache, but no luck.
