### ISSUE TITLE
Shortcodes in text-blocks

### ISSUE THREAD

**Issue by ierpe** [ThemeFuse/Unyson#302]
Adding regular extension shortcodes (like [myshortcode name="test"]) in text-blocks is not working, any idea on how to fix this?

**Comment by moldcraft** [comment]
Do you mean [this](http://static.md/ab91f63be1c0cf7ab8c102f8d92ba40d.png)?

**Comment by ierpe** [comment]
yes

**Comment by ierpe** [comment]
Any update on this ?

**Comment by moldcraft** [comment]
It should work https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.9/shortcodes/text-block/views/view.php#L9
