### ISSUE TITLE
Unyson Portfolio - How to stop it cropping my images to a smashed crab?

### ISSUE THREAD

**Issue by testo88** [ThemeFuse/Unyson#3022]
I'm trying to add a portfolio of previous work. but it keeps cropping my featured photos to fit within 1170x780px
I tried accessing the /public_html/wp-content/themes/parkstyle/framework-customizations/extensions/portfolio/config.php and changing the pixel values to what i wanted (1024x768px) but after i re-overwrite the config.php file. It doesnt do anything..

Do i need to reboot the website somehow for it to acknowledge the changes..? or should it do it automatically like i'm assuming?

Or do i need to adjust another file aswell. After 5 hours of trying to fix something so minor i'm at a point where powering up my stihl chainsaw and driving it through my PC genuinely seems like a more productive option. Please help.

**Comment by andronic90** [comment]
Hi,

in loop-projects.php you need to have something like this:
```
$thumbnails_params = $loop_data['image_sizes'][ $image_size ];
$thumbnail_id            = get_post_thumbnail_id();
if ( ! empty( $thumbnail_id ) ) {
	$thumbnail       = get_post( $thumbnail_id );
	$image           = fw_resize( $thumbnail->ID, $thumbnails_params['width'], $thumbnails_params['height'], $thumbnails_params['crop'] );
}
```

fw_resize() function make this resize in view.

**Comment by testo88** [comment]
Thanks for the reply.
So all i need to do is copy and paste that code into loop-projects.php ?

Im not near a computer to test it, but is the file location of loop-projects.php the same as config.php ?
Tia

**Comment by andronic90** [comment]
this is code for image resize the you can use $image variable where you want, you can check if is empty to show something else (a default image or nothing).

**Comment by testo88** [comment]
I've accessed /public_html/wp-content/themes/parkstyle/framework-customizations/extensions/portfolio/views/loop-item.php

I assume thats what you ment by "loop-projects.php" (correct me if i'm wrong).

This is whats currently written inside:

`<?php if ( ! defined( 'FW' ) ) {

	die( 'Forbidden' );

}



$loop_data = get_query_var( 'fw_portfolio_loop_data' );



$thumbnails_params = $loop_data['image_sizes']['featured-image'];

$thumbnails_params_big = $loop_data['image_sizes']['gallery-image'];



$thumbnail_id = get_post_thumbnail_id();

if ( ! empty( $thumbnail_id ) ) {

	$thumbnail       = get_post( $thumbnail_id );

	$image           = fw_resize( $thumbnail->ID, $thumbnails_params['width'], $thumbnails_params['height'], $thumbnails_params['crop'] );

	$image_big       = fw_resize( $thumbnail->ID, $thumbnails_params_big['width'], $thumbnails_params_big['height'], $thumbnails_params_big['crop'] );

	$thumbnail_title = $thumbnail->post_title;

} else {

	$image           = fw()->extensions->get( 'portfolio' )->locate_URI( '/static/img/no-photo.jpg' );

	$image_big       = fw()->extensions->get( 'portfolio' )->locate_URI( '/static/img/no-photo.jpg' );

	$thumbnail_title = $image;

}



?>`

**Comment by andronic90** [comment]
In this line: 
`$image           = fw_resize( $thumbnail->ID, $thumbnails_params['width'], $thumbnails_params['height'], $thumbnails_params['crop'] );`  come the image width and height for resize.

and the $image_big also has parameter for resize you need to inspect what image are you using.

I recommend to contact the Theme Author for support in this case.

**Comment by testo88** [comment]
ok so do I just make the following adjustments 
from:

 `$image = fw_resize( $thumbnail->ID, $thumbnails_params['width'], $thumbnails_params['height'], $thumbnails_params['crop'] );`

to: 

`$image = fw_resize( $thumbnail->ID, $thumbnails_params['1024'], $thumbnails_params['768'], $thumbnails_params['crop'] );`

?

**Comment by andronic90** [comment]
you need to change something like this:
`$image = fw_resize( $thumbnail->ID, 1024, 768, true );`
or
`$image = fw_resize( $thumbnail->ID, 1024, 768, false );`

The theme author can recommend better how to rewrite this to not lose data on theme update.

**Comment by testo88** [comment]
didnt work unfortunately.

If you goto aokmowing.com.au and scroll down to the photos.. you'll notice photo "tried 2" keeps forcibly cropping my photo. I dont want any photos to be cropped. I just want them all the resize the thumbnail so they are symetrical and then when opened resize to their default size.

**Comment by andronic90** [comment]
Please contact the Theme Author.

**Comment by ViorelEremia** [comment]
Must work how andronic90 says if doesn't work we can't help you, try better to inspect your code or contact you theme dev.
