### ISSUE TITLE
All in one wp-migration bug

### ISSUE THREAD

**Issue by Maden-maxi** [ThemeFuse/Unyson#3024]
When Import backup from old site to new via All in one wp migrate in Page builder images contain url from old site.
1. Do backup via All in one wp-migration.
2.Import backup on new host
3. Go to page which contain images and we will see broken images

I use Wordpress 4.9.0 and Unyson 2.7.10

**Comment by andronic90** [comment]
Hi,

you can use Backup extension from Unyson to move the website.

**Comment by ViorelEremia** [comment]
We can't add compatibility with all migrate plugins, here's why we create extension backup, but if you often use all in one migrate plugin you can try to create a pull request.
