### ISSUE TITLE
Action after demo install

### ISSUE THREAD

**Issue by zaxap83** [ThemeFuse/Unyson#3025]
Hi! I need to update permalinks after demo install, but how can i do it? In old version of Unyson-Backup-Extension ( https://github.com/ThemeFuse/Unyson-Backup-Extension ) was an opportunity to add action 'fw_ext_backup_after_import_demo_content', but it's not working in new version...

**Comment by ViorelEremia** [comment]
Use this hook ```fw:ext:backups:tasks:finish:id:demo-content-install```

**Comment by danyj** [comment]
>  I need to update permalinks after demo install, 

@ViorelEremia   this is not a bad idea at all , why aren't we doing it automatically ?

**Comment by ViorelEremia** [comment]
Can you test with that: https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/e8fcafb4b79d3282e840d524266aa30aa5914e8e

**Comment by zaxap83** [comment]
Thanks a lot!
