### ISSUE TITLE
Page content no longer visible

### ISSUE THREAD

**Issue by schmittfee** [ThemeFuse/Unyson#3027]
Page content no longer visible. Unable to save any changes. Builder not working. I'm using the Unyson page builder 2.7.10 and Wordpress 4.9. Since last wp-update (4.9) it doesn't work.
I had deactivated all other plugins, no difference. Please help!

**Comment by Ataurr** [comment]
Did you update the unyson extensions?

**Comment by schmittfee** [comment]
For the extensions are not updates available. If I click on settings, the screen is empty. Also I cannot deactivate any extension.

**Comment by schmittfee** [comment]
We can't edit our Site http://intelligente-stadt.com/!! What we can do?

**Comment by schmittfee** [comment]
The original theme is Lakshmi 1.1.0. 
Now I tryed with wp-themes twenty fifteen, sixteen, seventeen, also the same bugs. The Unyson Plugin doesn't work with wp 4.9!!
If you can't fix it, we have to build a new site completly. Incredible!!!

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by ViorelEremia** [comment]
The problem is here: https://core.trac.wordpress.org/ticket/42574
To solve that change language to english from wordpress admin settings.

**Comment by vinsdgreat** [comment]
Mine also stopped working and no longer visible. I already updated unyson extension and it doesnt help at all.

This error is found in my console.
![image](https://user-images.githubusercontent.com/16427110/33793328-033554c0-dcf1-11e7-9cee-a1276231d145.png)
