### ISSUE TITLE
FacebooK TF Widget: No Bueno/Blank

### ISSUE THREAD

**Issue by grabassenstein** [ThemeFuse/Unyson#3029]
Using the Unyson Framework with Core Theme. Facebook TF widget is completely blank. I've tried entering the FB link several ways: https://facebook.com/page_name, facebook.com/page_name, just page_name, and even @page_name to no avail. 

On a side-note: the Instagram feed works, but also seems to display a random period above the Title (See image).

Both of these widgets are being inserted into 1/2 columns (side-by-side) on the Visual Builder Template.

Cheers.
![screen shot 2017-11-21 at 10 18 47 am](https://user-images.githubusercontent.com/26425684/33083597-6c4634a2-cea5-11e7-8b2f-2cd7e83959d2.png)

**Comment by danyj** [comment]
This is framework only git , for theme widgets support contact Themefuse

**Comment by grabassenstein** [comment]
Fair enough.
