### ISSUE TITLE
Can we please have options for columns

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#303]
Can we please have options for builder columns. Currently we can only manipulate the section but if we want a 2-3 tone ( different bg image or color) columns we cant do this unless it is hard code CSS. 
So currently we cant have something like this unless we hard code it. 
http://prntscr.com/6c8z2y
http://prntscr.com/6c8zyy
http://prntscr.com/6c90hi
http://prntscr.com/6c90we
http://prntscr.com/6c927o

**Comment by danyj** [comment]
Not asking you to add set of options, just a possibility for devs to add it.

**Comment by moldcraft** [comment]
Currently I have [scratch-theme](https://github.com/ThemeFuse/Scratch-Theme) and [column has options](http://static.md/bee2c7d410c771f42e5378bec04e5997.png), or you mean something else?

**Comment by danyj** [comment]
AH , I never noticed it. Built my own without the columns options and it does not have it. Ok now. works fine. Thank you!
