### ISSUE TITLE
Make something only if option default values changed

### ISSUE THREAD

**Issue by sollerpolt** [ThemeFuse/Unyson#3031]
Hi all.

I searched a bit, but not found solution.

I want to print inline styles only if default values are changed. Of course I can manage a lot amount of If and compare existing values with defaults, but maybe someone can advice me build-in ore more smart solution?

**Comment by ViorelEremia** [comment]
Hi, 
It is not possible only if you comare its with default values or you can use a function to extract vars from file like fw_get_variables_from_file see doc about it, after that you can do merge or some actions php to manipulate these arrays to remove default values. I think you do not have to think about that we have big themes with a lot of options and it doesn't affect sensitively speed site, arbitrary extract only changed values can cause many bugs, your time, memory consumption etc.
