### ISSUE TITLE
Page Section is not visible when Page Builder is activated

### ISSUE THREAD

**Issue by nerdhousedesign** [ThemeFuse/Unyson#3035]
Hi,

My WordPress recently updated to 4.9 and now my Unyson 'Page Builder' isn't working when trying to edit page and blog pages. All I receive is an empty white browser window.

I deleted and reinstalled the plugin but still having issues viewing the page and blog editors in my WordPress site.

When I deactivate the 'Page Builder' the page and blog post editors loads.

Any ideas?

WordPress 4.9 running Shoom theme.
Running PHP version: 7.1.9

**Comment by ViorelEremia** [comment]
What language for your site do you use? see here: https://github.com/ThemeFuse/Unyson/issues/3027#issuecomment-346281958
Remove any cache server or wp plugins, update extensions, 
if is still dosen't work replace file on your server with: https://github.com/ThemeFuse/Unyson/issues/3010#issuecomment-345431017

**Comment by nerdhousedesign** [comment]
I cleared the cache and deactivated all the plugin except Unyson and still the issue with Page Builder.

I replaced the file in #3010 but still the same issue so have reverted to the default.

I looked at #3027 but don't really understand what would fix my issue.

Unyson Version 2.7.10
WordPress 4.9 running Shoom theme.
Running PHP version: 7.1.9
Installed on GoDaddy Linux Hosting

**Comment by ViorelEremia** [comment]
Any console errors?

**Comment by nerdhousedesign** [comment]
How would I find that out?

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by nerdhousedesign** [comment]
I sent you an email

**Comment by ViorelEremia** [comment]
Ok, I installed default wordpress theme -Twenty Seventeen and is working, try to conatact theme developer maybe they know what is wrong in their theme

**Comment by nerdhousedesign** [comment]
Hi,

Thanks for looking into that. I just switched themes and yes, it does work. Seems the issue is with the Shoom theme - argh.

Back to the developer I go. 

I will let you know the result.

Thanks,
David

Nerd House Design
9/310 Lonsdale Road, Toronto, Ontario, Canada. M4A 1X4
647-290-1303 
david@nerdhousedesign.com <mailto:david@nerdhousedesign.com>

Website <http://www.nerdhousedesign.com/> l Facebook <https://www.facebook.com/nerdhousedesign> l Twitter <https://twitter.com/NerdHouseDesign> l Instagram <https://www.instagram.com/nerdhousedesign/> l Behance <https://www.behance.net/nerdhousedesign> l Linkedin <http://ca.linkedin.com/in/nerdhousedesign/> l Skype <skype:nerdhousedesign>

**Comment by ViorelEremia** [comment]
Ok
