### ISSUE TITLE
Layout type customizer

### ISSUE THREAD

**Issue by ionut2014** [ThemeFuse/Unyson#3036]
Hello,
I try to make 2things , using theme twentyseventeen:
- in every page when edit page in admin, to have option to choose if my layout will be :default (with padding like normal site ), box layout
- the same layout to be in customizer (i added in customizer.php but i don't know where to add next, to work)

Thank you.
PS: i read documentation, but is first time on Unyson and is little hard to understand all.

**Comment by ViorelEremia** [comment]
If you add in both sides how do you will know which is valid option. You will have two options from customizer and from metabox rezult a conflict between options. You can do via multiple ways for exemple to add a class to body use hook body class: 
`function prefix_body_class( $classes ) {
	$customizer_boxed = fw_get_db_customizer_option( 'boxed' );
	$metabox_boxed    =  fw_get_db_post_option( $page_id, 'boxed' );
         $classes[] = 'prefix_class';
}
add_action( 'body_class', 'prefix_body_class' );`
if you want to add only for page use fw_get_db_post_option( $page_id, 'boxed' ); in page.php if you want option from customizer in page.php use fw_get_db_customizer_option( 'boxed' );

**Comment by ionut2014** [comment]
Hi, Thank you.
So what do you recommand is to use only one? customiser or metabox?

Your example is for customiser? Can you tell me please, where i need to add your code?
Can you help me with this?
I add in my page 2sections, section with text and image full width as background and second sections for title icon description in 3rows
1. I use section image background (later i want to add option for parallax, now i dont see in documentation how to add option to section builder) if i set full width, still is boxed.
2. I have this customizer.php https://jsfiddle.net/vx0ch12g/ background change is ok, is working.
For change color background, i added code in fuction.php , like in your doc.

For typography nothing changes in page, 
For layout, what i need to add and in which file to work? 
In the future i want to have Typography for body/menu

After this i will be on my own :D Just to understand how is working.

**Comment by ionut2014** [comment]
Many thanks

**Comment by ionut2014** [comment]
Nothing?

**Comment by danyj** [comment]
And this http://manual.unyson.io/en/latest/helpers/php.html#options
on how to set and get options , those are keys for you layout questions
