### ISSUE TITLE
section "recent posts" is empty

### ISSUE THREAD

**Issue by neo-flashman** [ThemeFuse/Unyson#3037]
version of plugin 2.7.10
WP 4.9
all updates are installed
--
the recent posts are not displayed, although previously everything was ok.
http://clip2net.com/s/3PIs32W and
http://clip2net.com/s/3PIsbN4
screenshots of page
WP Rocket Cash plugin was removed
how can I solve this problem?

**Comment by ViorelEremia** [comment]
We don't know how to solve your problem try to contact your theme developer. In last uupdate we don't touch any wordpress query or custom.
