### ISSUE TITLE
Slider height is weird on mobile/tablet

### ISSUE THREAD

**Issue by aaron0080** [ThemeFuse/Unyson#3038]
Hello!

My slider height reduces massively when viewing on mobile or tablet (see image). Currently the height is set to 'auto' for the section and panel. 

I'm not sure why it's doing it?

http://elberry-staging.buzzwordcreativetest.co.uk/marchbank/

Can you help as we'd really like to launch the site : )

Aaron
<img width="788" alt="screenshot 2017-11-23 10 16 56" src="https://user-images.githubusercontent.com/33927944/33168240-2763c8ec-d038-11e7-93b8-f8ad9ebaec49.png">

**Comment by ViorelEremia** [comment]
Please contact theme developer. themefuse.com/support
