### ISSUE TITLE
WordPress stops rendering because of Unyson -> No Publish Button -> Stack Trace added

### ISSUE THREAD

**Issue by daniellubos** [ThemeFuse/Unyson#3041]
TypeError
columnNumber: 7
fileName: "https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/static/js/editor_integration.js?ver=1.6.14"
lineNumber: 266
message: "init is undefined"
stack: "tinyMceInit@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/static/js/editor_integration.js?ver=1.6.14:266:7\ninit/<@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/static/js/editor_integration.js?ver=1.6.14:343:13\ndispatch@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:3:12392\nadd/r.handle@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:3:9156\ntrigger@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:3:11571\na.event.trigger@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:9:8273\ntrigger/<@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:3:18983\neach@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:2879\neach@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:844\ntrigger@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:3:18962\ninitSingleBuilder@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:514:4\ninitBuilderDelayed/</<@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:302:5\nthen/</</<@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:28766\ni@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:27444\nadd@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:27748\nthen/</<@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:28738\neach@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:2879\nthen/<@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:28684\na.Deferred@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:9:9928\nthen@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:28661\ninitBuilderDelayed/<@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:301:4\neach@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:2879\neach@https://www.drink-pearlins.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9:2:844\ninitBuilderDelayed@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:288:3\ninit/<@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:273:4\ndispatchSingleEvent@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.10:169:6\nfwEvents</this.trigger/<@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.10:147:7\nobjectMap@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.10:250:18\nfwEvents</this.trigger@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.10:131:3\n@https://www.drink-pearlins.com/wp-content/plugins/unyson/framework/static/js/option-types.js?ver=2.7.10:3:3\n"
__proto__: Object { stack: "", … }
fw-events.js:156:7

**Comment by ViorelEremia** [comment]
Try to replace this file on your server: https://github.com/ThemeFuse/Unyson/commit/a36762d8ecbfa0ffd1cf8d772fdabbc97cfe1e7a
Let me know if is fine
