### ISSUE TITLE
Home page error at top

### ISSUE THREAD

**Issue by gpjevach** [ThemeFuse/Unyson#3042]
Hello,

My homepage suddenly has the following error at the top:

Warning: in_array() expects parameter 2 to be array, null given in /home2/gpjevach/public_html/wp-content/themes/the-core-parent/theme-includes/helpers.php on line 2169

When I disable the Unyson plugin the error goes away. However, I need your plugin for my layout. It has worked fine to date. This happened suddenly. I have tried enabling Unyson and disabling all other plugins and the problem stays. So, I don't think there is a conflict with another plugin.

Please help me resolve the issue.

Thank you.

George Pjevach
Maestro melody Music School
407-790-5087
gpjevach@maestromelody.org

**Comment by ViorelEremia** [comment]
Please contact http://themefuse.com/support here is only plugin support.
