### ISSUE TITLE
How do we get the theme settings form FW_Settings_Form strings?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3043]
There is a string

https://github.com/ThemeFuse/Unyson/blob/d37f258d9f45849315a2c50fa5a82b5e375b5a08/framework/helpers/class-fw-settings-form.php#L76

 that is used to check if reset or cancel has been clicked on form reset and it is not used as localize script but is hard printed in the forml html 

https://github.com/ThemeFuse/Unyson/blob/master/framework/views/backend-settings-form.php#L120

I need to get this string to check confirmation within JS file so need to add it to wp_localize_script in my backend , 

how can I get this string from FW_Settings_Form class to use it in admin_enqueue_scripts?

**Comment by danyj** [comment]
There should be proper event on reset confirmation, 
if the reset is clicked than we should fire something like `trigger('resseting-form');` 

`fw:settings-form:reset`  is fired after the reset

https://github.com/ThemeFuse/Unyson/blob/2e568472af387819f0b3c36a570a37d8cb0f8fd3/framework/views/backend-settings-form.php#L339


 but we have nothing to tell us if the reset confirmation is clicked  or canceled

**Comment by ViorelEremia** [comment]
That satisfies your needs(replace it in https://github.com/ThemeFuse/Unyson/blob/master/framework/views/backend-settings-form.php#L104 ) and check console when is clicked confirm:
```
<script type="text/javascript">
	jQuery( function ( $ ) {

		$( document.body ).on( 'fw:settings-form:cancel-reset', function( selector, data ) {
			console.log( data );
        } );
		$( document.body ).on( 'fw:settings-form:before-reset', function( selector, data ) {
			console.log( data );
        } );

		$( document.body ).on(
			'click.fw-settings-form-reset-warning',
			'<?php echo $js_form_selector ?> input[name="<?php echo esc_js( $input_name_reset ) ?>"]',
			function ( e ) {
				/**
				 * on confirm() the submit input looses focus
				 * fwForm.isAdminPage() must be able to select the input to send it in _POST
				 * so use alternative solution http://stackoverflow.com/a/5721762
				 */
				$( this ).closest( 'form' ).find( '[clicked]:submit' ).removeAttr( 'clicked' );
				$( this ).attr( 'clicked', '' );

                var resetWarning = '<?php echo esc_js( $form->get_string( 'reset_warning' ) ); ?>',
                    data         = { 'reset_warning': resetWarning };

				if ( ! confirm( resetWarning ) ) {
					e.preventDefault();
					$( document.body ).trigger( 'fw:settings-form:cancel-reset', data );
					$( this ).removeAttr( 'clicked' );
				} else {
					$( document.body ).trigger( 'fw:settings-form:before-reset', data );
                }
			}
		);
	} );
</script>
```

**Comment by danyj** [comment]
@ViorelEremia bless you !

Exactly what I needed , I dont need the data now since you added event , now I can do 

		$(document.body).on({
			'fw:settings-form:before-reset': function (data) {
				$(this).addClass('fw-resetting');
			}
		});

**Comment by danyj** [comment]
can this make it in next version ?
