### ISSUE TITLE
RGBA Color Picker not working in customizer WP 4.9

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#3044]
I have just cloned the master branch [`958a98087b38e514e7c904c3d4c38bfb4db9b787`](https://github.com/ThemeFuse/Unyson/commit/958a98087b38e514e7c904c3d4c38bfb4db9b787)
`RGBA color picker` is not working inside the customizer.
It works on admin pages. But inside the customizer it doesn't. 
Theme is not getting refreshed after changing the color, and also **javascript** code that listens for updates (to update the color without refreshing the theme) is not getting triggered.

**Comment by ViorelEremia** [comment]
For us is working well, and what is this hash is one of commits. Are you sure you pulled all changes?

**Comment by ivandotv** [comment]
That commit hash is just a reference where was `master` branch when I cloned it.
I am up to date with `origin/master` and this problem is still there.

Please take a look at this video to see what I am talking about.
https://drive.google.com/file/d/11DtaAvqnY8BabI-nEJe_N64XhVTWYqrl/view?usp=drivesdk
Video explanation:
I will try to change the button background and text via customizer.
Colors are updated live via javascript ( customizer standard procedure `transport='postMessage'`)
You will see that **button text** color changes are reflected immediately ( it uses standard color picker), but background color (RGBA color picker) is not working.

Also on a side note what does that `clear` button should do? Because it just clears all the colors, it doesn't revert to last saved color.

**Comment by ViorelEremia** [comment]
@ivandotv Can you test?
If you want default color reset etc create a pull request, improving this option type has low priority for us.

**Comment by ivandotv** [comment]
It's working. Thanks.
I wasn't sure about functionality of the `clear` button in RGBA color picker. Should it behave as the `reset` button in regular color picker?

**Comment by ViorelEremia** [comment]
clear button I added it because some users said it would be good to be. Reset checkbox in regular color picker it's a bug

**Comment by ivandotv** [comment]
Reset in regular color picker is actually a good thing because is resets to original value.
