### ISSUE TITLE
Unyson portfolio: displayed date on portfolio item frontend page is wrong

### ISSUE THREAD

**Issue by danionescu2007** [ThemeFuse/Unyson#3045]
Hello!

I am using Unyson with a theme I purchased (Seosight).
The displayed date on portfolio item frontend page is wrong. I think it should be the published article date. Instead it is the last save date, which cannot be modified in wp backend.

I attached a screenshot which depicts the date I am talking about.
Please advise.
Thank you!

![screenshot_wp](https://user-images.githubusercontent.com/4688610/33297366-41b8ceae-d3e9-11e7-82c7-8ebafe468dfc.png)

EDIT: reading other issues from other users, I tried with a default theme and the date field is not even shown. I realize my issue could be theme related. If so please confirm so that I adress the theme authors.

**Comment by danyj** [comment]
Contact theme provider please , this is framework git only.

**Comment by danionescu2007** [comment]
Thank you. I thought that the Portfolio plugin, which is part of the framework, is retrieving the date field.
