### ISSUE TITLE
Unyson Framework & Cloudflare

### ISSUE THREAD

**Issue by anythingpixel** [ThemeFuse/Unyson#3046]
Hello. I am running a premium theme that is using the Unyson framework and the King Composer page builder. Everything was working fine. Then I added Cloudflare to the mix and now the site seems to go down every time I active Unyson. I've troubleshot with turning off all the plugins and then turn them back on one by one. It seems the Unyson plugin is the issue. Anyone else having a similar experience? I'm hosting on GoDaddy Managed Pro hosting.

**Comment by ViorelEremia** [comment]
Can you share the link of your site? I don't understand "down every time".

**Comment by anythingpixel** [comment]
It's https://www.anythingpixel.com

On Nov 28, 2017 2:59 AM, ViorelEremia <notifications@github.com> wrote:

Can you share the link of your site? I don't understand "down every time".

**Comment by ViorelEremia** [comment]
Maybe is a fatal error on your site and cloudflare can't get html try to change theme your theme also can have some incompatibilities. We tested unyson with php7 and cloudflare.

**Comment by anythingpixel** [comment]
Ok, let me try. Thanks



On November 28, 2017 at 8:23:53 AM, ViorelEremia (notifications@github.com<mailto:notifications@github.com>) wrote:

Maybe is a fatal error on your site and cloudflare can't get html try to change theme your theme also can have some incompatibilities. We tested unyson with php7 and cloudflare.
