### ISSUE TITLE
New backup cant proceed because of tmp folder

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3047]
Error

 mkdir(): File exists in  class-fw-ext-backups-task-type-dir-clean.php on line 35

`2 mins ago Directory Cleanup: Cannot create directory: .../wp-content/uploads/fw-backup/tmp`

you might want to check if dir exists first

**Comment by ViorelEremia** [comment]
Is this folder empty? before to create that folder the script is trying to remove it. Check the line 27, if file_exists sees that folder, and if the function fw_ext_backups_rmdir_recursive works right.

**Comment by andreiglingeanu** [comment]
Yeah, that's the first time I encounter that issue... Any more errors for you @danyj?

**Comment by danyj** [comment]
not that I noticed but the tmp is important

**Comment by andreiglingeanu** [comment]
Yeah, sure it is important

Have you tried to manually remove it and retry the process? Maybe you have permissions issues?

**Comment by danyj** [comment]
> Have you tried to manually remove it and retry the process? 
yes I did that

it proceeded afterwards , lets keep it open, if I see the issue again il try to find more details
