### ISSUE TITLE
fw_ext_page_builder_content_wrapper_class Filter

### ISSUE THREAD

**Issue by stanislav-chechun** [ThemeFuse/Unyson#3048]
Hello, I trying use fw_ext_page_builder_content_wrapper_class filter, but it's doesn't work, can you show me example how I can change div class into functions.php? 
Thanks a lot!

**Comment by danyj** [comment]
As it states here , 
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/c8ed3b7b6182e5529ad93bb30e2fd2e867d81a73/class-fw-extension-page-builder.php#L268

add filter to wrap $content
