### ISSUE TITLE
Unyson info

### ISSUE THREAD

**Issue by yupii1986** [ThemeFuse/Unyson#3049]
Hi,
I want to start my theme with Unyson,
What is your recomandation for a theme light, fast, with few options like: in builder parallax, padding, choose sidebar and menu 👍 Underscore+ Unyson , default wp theme +Unyson or something else+Unyson?

I want to make themes for themeforest (i have experience with WP)
Also Can we use The journal theme to build our theme to sell on themeforest?

Thank you.

**Comment by danyj** [comment]
Any theme + Unyson =  magic :)

> Also Can we use The journal theme to build our theme to sell on themeforest

That is unethical.

**Comment by yupii1986** [comment]
Thank you

I started with scratch theme but i see i have default sidebar left black and style theme as box

How can i delete that sidebar from left and to have it only when i added it from admin?

Thank you.
I don't understand how is made this scratch

**Comment by yupii1986** [comment]
Can you help me with an example, how to make section option in page builder when choose full with, to be full width that section?

I read how to create an option, i made, but i don't understand ..

In option.php from section i add

$options = array(
	'is_fullwidth'       => array(
		'label' => esc_html__( 'Full Width Section', 'my_theme' ),
		'type'  => 'switch',
		'desc'  => 'full width?',
	),
But what i need to add in other places for section to be width?

Many thanks

**Comment by andreiglingeanu** [comment]
They @yupii1986, you can read more about that on the official manual. You're looking for a way to overwriting shortcodes. [Check here](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes).
