### ISSUE TITLE
Deletion of an extension removes child extensions from framework-customizations/

### ISSUE THREAD

**Issue by abeleev** [ThemeFuse/Unyson#305]
I have some problem with Slider custom extensions placed in the theme folder.
I create custom extension for Slider and placed it in the Slider extension folder in theme (mytheme/framework-customizations/media/slider/extensions/myext/).
Then, if I delete Slider in Unyson admin panel, my extension removes from theme folder too, but default Slider extensions is not.
I inspect all code of extensions deletion and haven't found any hook or option to prevent this behavior.
I think it would be good to have some option for prevent remove of custom extensions in theme folder.

**Comment by thednp** [comment]
That is why you should give the extension a different name, say abl_slider?

**Comment by moldcraft** [comment]
@thednp I copied 

`plugins/unyson/framework/extensions/media/extensions/slider/extensions/bx-slider` 

to

`{theme}/framework-customizations/extensions/media/extensions/slider/extensions/test-slider`

then deleted (from admin) the Slider extension, and `test-slider` was deleted too.

So this is a bug.

**Comment by thednp** [comment]
OK, a bug is a bug.

**Comment by moldcraft** [comment]
[The fix](https://github.com/ThemeFuse/Unyson/commit/955a7aaa0da39d48f6f777107c0c43778004deec) will be available in the next Unyson release. Until then, you can remove manually [these lines](https://github.com/ThemeFuse/Unyson/blob/5bd763ffeee5b7da3fd765d98aaee63efa5ed08c/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L1415-L1420).

**Comment by abeleev** [comment]
Thank a lot!
