### ISSUE TITLE
[bug] Multi select lists unwanted post types

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3050]
I have multi-select setup to show custom post types and it works fine , but when I start searching for post  it lists unwanted post type ( page ) 

![screenshot_1](https://user-images.githubusercontent.com/2340172/33343463-a6eeb008-d485-11e7-968d-d8950af0c73a.jpg)

	'fpb' => array(
		'type' => 'multi-select',
		'value' => '',
		'label' => __('Test', 'fw'),
		'population' => 'posts',
		'source' => 'thz-pageblock',
		'prepopulate' => 10,
		'limit' => 1,
	),

**Comment by danyj** [comment]
@ViorelEremia   thnx for the commit but can you adjust your IDE please , it is spacing the commits every time so we cant see where the change was , example here im sure the change was in one line but commit shows 57 addons and deletions
https://github.com/ThemeFuse/Unyson/commit/3609cdfe169cbfdb6cb8e3c5534ba63cce0dd2e3

**Comment by ViorelEremia** [comment]
ok
