### ISSUE TITLE
[bug] ReferenceError: tinymce is not defined on Blog Posts page

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3051]
Assign Posts page
in post options add editor you will get fw-events.js?ver=2.7.10:156 ReferenceError: tinymce is not defined
http://prntscr.com/hgkw8c

it is because blog posts page does not have editor enabled so if we want to use any option with editor in there editor needs to be instantiated.

**Comment by ViorelEremia** [comment]
you tried: https://github.com/ThemeFuse/Unyson/commit/a36762d8ecbfa0ffd1cf8d772fdabbc97cfe1e7a

**Comment by danyj** [comment]
yes , is in already since that commit 
http://prntscr.com/hgryd1

**Comment by danyj** [comment]
false alarm , that was another install that did not have the new commit. sorry
