### ISSUE TITLE
How to remove action fw_ext_shortcodes_enqueue_static ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3053]
@andreiglingeanu  @ViorelEremia 

I have a compression scripts that combines all inline CSS when enabled and when is done I need to disable shortcode fw_ext_shortcodes_enqueue_static,  https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/414de6c22339b0a37edda83cea45a6abb5e95b75/class-fw-extension-shortcodes.php#L251

I tried all priorities but cant get it to work . 
Or even better how to disable the actual static.php files inclusion all at once for shortcodes?

**Comment by danyj** [comment]
I see we cant disable statics 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/efb988cc467826e3fd1f9c9bbabf5afd62f74e4a/class-fw-extension-shortcodes.php#L275

**Comment by danyj** [comment]
@andreiglingeanu   any insight on this ?

**Comment by andreiglingeanu** [comment]
I see no way of doing that in a clean way. The simplest solution right now is to override each and every `static.php` file for each shortcode.

**Comment by ViorelEremia** [comment]
Deregister them with wp_deregister_script ?

**Comment by ViorelEremia** [comment]
you tried something like that:
add_action( 'wp_enqueue_scripts', function(){ wp_deregister_script( 'fw-shortcode-button' ); }, 31 );

**Comment by danyj** [comment]
all  the orders tried thus I stated in original post 

> I tried all priorities but cant get it to work .

**Comment by danyj** [comment]
ah , no I did not try tricks , went for deregister directly , will try and advise

**Comment by ViorelEremia** [comment]
Try:
```
function test_theme_name_scripts() {
	wp_dequeue_style( 'fw-shortcode-button' );
	wp_dequeue_script( 'fw-shortcode-buttons' );

}
add_action( 'fw_shortcode_render_view', 'test_theme_name_scripts' );
add_action( 'fw:ext:shortcodes:enqueue_shortcodes_static:after', 'test_theme_name_scripts' );
```
with scratch theme is working.

**Comment by danyj** [comment]
@ViorelEremia I am not talking about wp_dequeue_style, 

but about this particular action 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/efb988cc467826e3fd1f9c9bbabf5afd62f74e4a/class-fw-extension-shortcodes.php#L292

which I use like this in shortcode static.php


`add_action('fw_ext_shortcodes_enqueue_static:button','_thz_button_shortcode_css');
`

in order to disable it I have to go trough 50 shortcodes static.php and do 


	if( _thz_inline_css_is_not_cached() ){
		
		add_action('fw_ext_shortcodes_enqueue_static:NAME','_thz_NAME_shortcode_css');
	
	}
`

we should be able to do this globaly via remove_action or something simlper that does not have to be repeated for each shortcode.

**Comment by danyj** [comment]
almost , 

in scope 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/efb988cc467826e3fd1f9c9bbabf5afd62f74e4a/class-fw-extension-shortcodes.php#L58-L69

this works 

`remove_action( 'wp_enqueue_scripts', array( $this, '_action_enqueue_shortcodes_static_in_frontend_head' ), 30 );`


outisde I tried 

`remove_action( 'wp_enqueue_scripts', array( 'FW_Extension_Shortcodes', '_action_enqueue_shortcodes_static_in_frontend_head' ), 30 );`


no luck

**Comment by danyj** [comment]
for anyone who needs it 

`remove_action( 'wp_enqueue_scripts', array( fw()->extensions->get( 'shortcodes' ), '_action_enqueue_shortcodes_static_in_frontend_head' ), 30 );`
