### ISSUE TITLE
Portfolio duplicates images on load more

### ISSUE THREAD

**Issue by lamm1200** [ThemeFuse/Unyson#3054]
Hi,

I really like the unyson pagebuilder but I have one issue with the portfolio.
When I click on the load more button it generates duplicates of the images that were already there.
Any idea how to fix it?

<img width="923" alt="screen shot 2017-12-01 at 19 19 57" src="https://user-images.githubusercontent.com/9111436/33497070-e21d63f6-d6cc-11e7-8b66-1d60cee77d36.png">

<img width="883" alt="screen shot 2017-12-01 at 19 20 07" src="https://user-images.githubusercontent.com/9111436/33497077-e62f1944-d6cc-11e7-9cc6-952c1d5ec3c9.png">

**Comment by danyj** [comment]
your theme provider is responsible for that , this is framewok git only.
