### ISSUE TITLE
disabling table shortcode

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#3055]
I'm disabling shortcodes via the fw_ext_shortcodes_disable_shortcodes filter, just as is stated in the documentation http://manual.unyson.io/en/latest/extension/shortcodes/index.html#disabling-shortcodes. However, this is not working for the 'table' shortcodes.

This is my hooks.php file located in {my-theme}/framework-customizations/extensions/shortcodes/hooks.php

```
<?php if (!defined('FW')) die('Forbidden');

function _filter_theme_disable_default_shortcodes($to_disable) {
	$to_disable[] = 'accordion';
	$to_disable[] = 'button';
	$to_disable[] = 'calendar';
	$to_disable[] = 'call_to_action';
    $to_disable[] = 'contact_form';
    $to_disable[] = 'icon';
    $to_disable[] = 'icon_box';
    $to_disable[] = 'map';
    $to_disable[] = 'tabs';
    $to_disable[] = 'team_member';
    $to_disable[] = 'testimonials';
    $to_disable[] = 'table';

	return $to_disable;
}
add_filter('fw_ext_shortcodes_disable_shortcodes', '_filter_theme_disable_default_shortcodes');
```

The table shortcode is still present in the Content Elements
![image](https://user-images.githubusercontent.com/10368841/33500565-ffa7405a-d6b7-11e7-9975-a02f1b7a7faf.png)

**Comment by ViorelEremia** [comment]
I tried your code it works. Try to inspect function load line15:
unyson\framework\extensions\shortcodes\includes\class-fw-shortcodes-loader.php
And here: 
framework/extensions/shortcodes/class-fw-extension-shortcodes.php line 201.
