### ISSUE TITLE
[bug] wp_localize_script in option type loading multiple times

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3056]
Add wp_localize script in option type  _enqueue_static  method

`wp_localize_script('fw-option-' . $this->get_type().'thz-add-link', '_thz_add_link', array(...)`

check head , it loads for every instance 

same goes for  these actions

```

fw_admin_enqueue_scripts:settings
fw_admin_enqueue_scripts:post
fw_admin_enqueue_scripts:term
```

**Comment by andreiglingeanu** [comment]
Hm, what do you mean for every instance? If you repeat that particular option type in `options.php`, the `wp_localize_script` gets repeated?

**Comment by danyj** [comment]
I think is more for every enqueue_scripts instance , I found 3 instances of same localize vars  on a page for a link , where link option is used more than 3 times.

**Comment by andreiglingeanu** [comment]
Is that for a custom option type, right?

Really worth checking `$call_next_time` flag which is configured via `_enqueue_static()` of your custom option type:

https://github.com/ThemeFuse/Unyson/blob/3609cdfe169cbfdb6cb8e3c5534ba63cce0dd2e3/framework/core/extends/class-fw-option-type.php#L283

```php
// call _enqueue_static() multiple times, for each instance
return true;

// call it once
return false;
```

This mechanism is very important to understand. Also, try to check how many times the `_enqueue_static` method of your option type gets called.

**Comment by danyj** [comment]
ha! never saw it till now. will check. thnx !

**Comment by danyj** [comment]
@andreiglingeanu  can you show use example , I dont understand it,  third param is data

**Comment by andreiglingeanu** [comment]
You have to return `true | false` from your method in order to indicate the behavior, just like the `multi-picker` explicitly requires its every instance to be enqueued separately in a non-cached way

https://github.com/ThemeFuse/Unyson/blob/3609cdfe169cbfdb6cb8e3c5534ba63cce0dd2e3/framework/includes/option-types/multi-picker/class-fw-option-type-multi-picker.php#L63-L65

**Comment by danyj** [comment]
nah man , we don't need to return anything , enque it is called once by default , in multi you might want to do it but looking at the code it is called once, 
I had one more instance of the var in another option type thus it was twice , my bad
