### ISSUE TITLE
Widgets screen in RTL mode

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#3058]
Hello!

Please add this code 
```
body.rt div.widget-liquid-left {
  float: right;
}
```
into /wp-content/plugins/unyson/framework/extensions/sidebars/static/css/sidebar.css

to fix RTL mode

**Comment by DKudleichuk** [comment]
Hi again!

Sorry, but this bug does not appear without Unyson Plugin enabled, this file /wp-content/plugins/unyson/framework/extensions/sidebars/static/css/sidebar.css breaks widgets layout, please check again, this is not core bug, i have checked twice

**Comment by DKudleichuk** [comment]
i mean, in RTL mode only

**Comment by ViorelEremia** [comment]
@WPJobs, @DKudleichuk create a pull request if you want to solve the problem sooner.

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson-Sidebars-Extension/commit/73527b77be97a2ae1c0314e7e6d77bb8c217364f
