### ISSUE TITLE
removed Unyson extension and cannot retrieve it

### ISSUE THREAD

**Issue by mindacrobats** [ThemeFuse/Unyson#3059]
I removed the footer extension from the Unyson plugin and cannot retrieve it. Even after deleting the plugin and reinstalling it the footer extension is no longer available.

Best regards

**Comment by ViorelEremia** [comment]
Unyson by default dosen't have any extension footer, maybe it's a custom extension from your theme. is your theme a premium theme? are you developer of this theme?
