### ISSUE TITLE
Feedback extension does not work

### ISSUE THREAD

**Issue by dameer** [ThemeFuse/Unyson#306]
Did you try to post more than one comment by using this extension? The list of comments always shows only the latest comment posted as if there's no comments loop!
Comment REPLY link is missing which means no real discussion.

Just noticed another issue...
Feedback extension is not "compliant" with comments posted before Unyson plugin installed, Feedback section in Admin panel is full of errors!

Trying to get property of non-object "blah/blah/wp-includes/capabilities.php", lines #1129, #1130, #1133 
and then
Trying to get property of non-object "blah/blah/wp-admin/includes/class-wp-comments-list-table.php", line #567

On a side note...
Why is the "rating field" mandatory? That's kinda annoying and not suitable for a regular blog, I mean it's OK if there's something to be rated but bad for those who just want to discuss.

**Comment by sergiubagrin** [comment]
> Did you try to post more than one comment by using this extension?

It is a feedback/ rating system not a simple comment form. From this point of view it is possible to ad only one review/ feedback to a specific post/ page/ product. All review systems work in the same way on BestBuy, Aliexpress, ...

> Why is the "rating field" mandatory? That's kinda annoying and not suitable for a regular blog, I mean it's OK if there's something to be rated but bad for those who just want to discuss.

Why you try to activate feedback extensions for a blog? It is needed to activate it for specfic pages that needs a rating system for example products, affiliates product page, ...

**Comment by dameer** [comment]
I'm just following a simple routine which will be followed by a thousands of other users who will have to install Unyson plugin with the theme:

Install Unyson plugin and it'll self-install feedback extension and automatically replace default comments system.

I mean, I know what's going on but 99% of non-developers won't and they will say there's something wrong.

**Comment by sergiubagrin** [comment]
> Install Unyson plugin and it'll self-install feedback extension and automatically replace default comments system.

Feedback extension will be available only for custom posts that was selected from Unyson feedback settings: http://screencast.com/t/Qydsf34B In this case for Blob posts will be comments and for events will be review/ feedback

**Comment by dameer** [comment]
I know about settings but still there's a question why "Activate for Blog posts" is selected by default?

I also tried to remove Feedback ext. from "framework-customizations/theme/manifest.php" by assuming it'll either deactivate it or even Remove from the list of available extensions, however, it looks like the theme manifest doesn't work that way.

Do you have any other suggestions on how to automatically deactivate or even remove "unwanted" extensions?

Just wanted to say THANKS for all your efforts and great work!!!

**Comment by sergiubagrin** [comment]
> I know about settings but still there's a question why "Activate for Blog posts" is selected by default?

In case all extensions are disabled "Blog Posts" custom posts is on all time :) Joke.

Ok. 

1. We have an issue that will display in Available extensions only compatible extensions: https://github.com/ThemeFuse/Unyson/issues/307
2. If a theme added Feedback extensions as Compatible (for example for events) it is possible to rewrite extensions Config File and change default Custom Posts for this specific theme (For Ex: Learning) 

I will add an example in 20-30 min

**Comment by dameer** [comment]
Nice joke :) 
As for the other half - great! Thanks a bunch once again!

**Comment by sergiubagrin** [comment]
> I will add an example in 20-30 min

This one was a new joke :) We have a bug with method i will open a new issue regarding point (2)
====
If a theme added Feedback extensions as Compatible (for example for events) it is possible to rewrite extensions Config File and change default Custom Posts for this specific theme (For Ex: Learning)

**Comment by sergiubagrin** [comment]
Added: https://github.com/ThemeFuse/Unyson/issues/308

**Comment by dameer** [comment]
No big deal, take your time :)
