### ISSUE TITLE
Page builder stopped working 

### ISSUE THREAD

**Issue by rayg17** [ThemeFuse/Unyson#3060]
I uploaded a new logo for website, saved it, and then continued to home page to edit but the page builder is not loading. 
Now homepage layout doesn't appear correctly.

**Comment by rayg17** [comment]
When the homepage loads on the dashboard the page builder with my content stacked in sections appears momentarily and then goes away to WP default builder and page builder option is not available

**Comment by ViorelEremia** [comment]
Check browser console for errors, enable wp debug, disable plugins we need more information
