### ISSUE TITLE
[bug] wp-shortcode decode inside editor in theme settings issue

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3061]
Worked in previous version , updated to latest master 

![screenshot_1](https://user-images.githubusercontent.com/2340172/33629128-4bb5c716-da03-11e7-9b69-5f89aa51d7c8.jpg)

**Comment by danyj** [comment]
It also happens right after you click on any Unyson shortcode from editor

**Comment by ViorelEremia** [comment]
I tested it right now, but this is not happening to me. Some details?

**Comment by danyj** [comment]
add this in theme settings option 

```

	'main' => array(
		'title'   => false,
		'type'    => 'box',
		'options' => array(
			'test-addable-vc' => array(
				'type' => 'addable-popup',
				'value' => array(),
				'label' => __('Addable Popup', '{domain}'),
				'template' => '{{- option_1 }}',
				'popup-title' => null,
				'size' => 'small', // small, medium, large
				'limit' => 0, // limit the number of popup`s that can be added
				'add-button-text' => __('Add', '{domain}'),
				'sortable' => true,
				'popup-options' => array(
					'option_1' => array(
							'type' => 'wp-editor',
							'size' => 'large',
							'editor_height' => 200,
							'shortcodes' => true,
							'editor_type' => 'tinymce',
							'wpautop' => false,
							'label' => __('Content', 'creatus'),
							'desc' => esc_html__('Enter some content for this text block', 'creatus'),
							'value' => 'Praesent ut accumsan est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras volutpat, ligula quis mollis elementum, ex nisi interdum ante, eu posuere sem sem et tortor.'
					),

				),
			)
		),
	),
```


click on add popup , 

in popup editor find Unyson shortcode button 
open shortcodes 
click on any of them , 
bug is in console 

http://prntscr.com/hn02yh

**Comment by ViorelEremia** [comment]
it is working. I saved, refresh, add new shortcodes save refresh.

**Comment by danyj** [comment]
no js bugs while adding?

**Comment by ViorelEremia** [comment]
no

**Comment by ViorelEremia** [comment]
is it happening with other shortcode?

**Comment by danyj** [comment]
all of shortcodes , 

latest wp-editor option, let me update the option again i might have missed something

**Comment by danyj** [comment]
ok false alarm , I must have missed a script, re-downloaded and works, sorry for the trouble

**Comment by danyj** [comment]
sorry mate , is still there , I had console off ,
bug is there for me , now I did not pull shortcode extension if that has something to do with it since it

**Comment by danyj** [comment]
and I see no updates to the extension https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension

**Comment by ViorelEremia** [comment]
I tested(both versions of extension) with the core and scratch and i don't see that.

**Comment by danyj** [comment]
hm ,  il try to trace it but all I can see is that is going back to this line 
https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/master/static/js/plugin.js#L178

**Comment by danyj** [comment]
ok i dont know what this is but files are mismatched , 

I deleted the wp-shortcodes via unyson and downloaded and activated again 
what I see on line 303  

is on line 316 

https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/master/static/js/plugin.js#L316

I cleared cache several times 
**than I deleted Unyson completely** 

installed again 
than had to  get the wp-editor from git since the one delivered has a  bug 
and the error is now back again , line 303  on the mismatched file

**Comment by danyj** [comment]
100% missmatch 

the release  1.07 https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/releases/tag/v1.0.7

does not match the master https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension/blob/v1.0.7/static/js/plugin.js

which was changed a year agao

**Comment by danyj** [comment]
@andreiglingeanu  

Several bugs with the wp-shortocode

it is looking for some depenedncies ,  



here is the issue , 
use this file as settings.php 

https://gist.github.com/danyj/6a97d703d9083d3a3b9685b97fc49c2e#file-settings-php

for scratch-parent 


in option add popup , and try what you did , you will see the bug 


issue 2:

use icon as shortcode image ,   once the popup opens ,  the wp-shortcodes will look for image instead of icon you set in shortcode config
