### ISSUE TITLE
Unyson Github extension fetch problem.

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#3062]
Hello @moldcraft 
I have created the unyson extension and hosted on github.
and define the path in extension manifest file.
![article](https://user-images.githubusercontent.com/12461946/33646618-4827ddfe-da72-11e7-99c2-49a5c6258716.png)

Now when i have created the tags on github for latest relaease and download from github the code already  has updated version but when unyson fetches from gihub its fetch the old 1.0 release.

![art-2](https://user-images.githubusercontent.com/12461946/33646667-97a92ea0-da72-11e7-82ce-385d9b55edb6.png)

Kindly i need urgent help.

Looking Forward.

**Comment by ViorelEremia** [comment]
I don't understand what did you do, I see you have one tag release https://api.github.com/repos/etwordpress01/articles/releases/latest

**Comment by wpthemes786** [comment]
https://api.github.com/repos/etwordpress01/articles/releases/latest
We have created the tag and now the version is 1.1.
But all we want to know that when we fetch from unyson extension its fetch the old v1.0 version not v1.1.

Looking Forward.
