### ISSUE TITLE
Add metabox via plugin

### ISSUE THREAD

**Issue by NiloySarker** [ThemeFuse/Unyson#3063]
Hello,
i know that with `fw_extensions_locations` filter we can easily override anything from the _extensions_ folder from custom-plugin.
but i want to add some new meta box fields  into this location via plugin `theme/options/posts/{post-type}.php`
So i want to know, is there have any option to do this like the `fw_extensions_locations`  filter for the override or adding new meta box fields from custom-plugin?

**Comment by ViorelEremia** [comment]
Use this hook: https://github.com/ThemeFuse/Unyson/blob/master/framework/core/components/theme.php#L111

**Comment by NiloySarker** [comment]
@ViorelEremia Could you please explain it. I am not understood how this hook work from the plugin folder?

**Comment by ViorelEremia** [comment]
Add in your plugin for custom post type post:
```
add_action( 'fw_post_options:post', function( $options ) {
      // merge your new settings with $options.
} );
```

**Comment by NiloySarker** [comment]
Great! 
I also found this http://manual.unyson.io/en/latest/hooks/index.html?highlight=fw_post_options#actions
I was thinking to use cmb2 for this issue if no one comments here. but I was quite sure about it that unyson has a filter for this but I don't know the name. 
Thanks a lot, @ViorelEremia .
