### ISSUE TITLE
Database restore: Syntax error, malformed JSON

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#3064]
When using the Backup extension to do a restore from the live environment to my local testing environment, I'm getting the following error:
`Database restore: Failed to decode line 93460 from db file. Syntax error, malformed JSON`

I'm getting this error when doing a content backup as well as a full backup.

When inspecting the database.json.txt file, I see multiple empty lines. In fact, when inspecting the full file, it has something like 7000 empty lines. 

After removing all empty lines and re-zipping the file I tried a new restore, now I'm getting the following errors:
``3 mins ago Database restore: The execution failed. Please check error.log
3 mins ago Database restore: Failed to insert row from line 46697 into table _fwbk_wp_dynamo_icl_string_translations. Unknown column 'mo_string' in 'field list'``

In the error.log I'm finding the following:
``[06-Dec-2017 10:45:04 UTC] WordPress database error Unknown column 'mo_string' in 'field list' for query INSERT INTO _fwbk_wp_dynamo_icl_string_translations ( 
`id`, `string_id`, `language`, `status`, `value`, `mo_string`, `translator_id`, `translation_service`, `batch_id`, `translation_date` 
) VALUES ( 
'1', '9984', 'en', '10', 'events', '', '', '', '0', '2017-07-28 15:11:27' 
) made by do_action('wp_ajax_nopriv_fw:ext:backups:continue-pending-task'), WP_Hook->do_action, WP_Hook->apply_filters, _FW_Ext_Backups_Module_Tasks->_action_ajax_continue_pending_task, _FW_Ext_Backups_Module_Tasks->execute_pending_task, FW_Ext_Backups_Task_Type_DB_Restore->execute, FW_Ext_Backups_Task_Type_DB_Restore->do_import``

Does anyone have an idea what's going wrong and how to fix/bypass it?

**Comment by danyj** [comment]
What I have noticed is , if you have ANY plugin that is altering DB on install and you do a backup on that site,  once you try to restore it on a site that **does not have these plugins** installed the restore/install will fail with similar msg  `Unknown column.` 

See this https://github.com/ThemeFuse/Unyson/issues/2872

**Comment by warudin** [comment]
Hey danyj, thanks for your response. As far as I could see, the restore process was failing for WPML tables. I've activated all related plugins before doing another restore and now the restoring process is continuing until after the database restore process. So I guess you are right about this. 

So far I was under the impression that the Backup-extension is quite robust. I'm not sure how obscure this problem is?

**Comment by danyj** [comment]
>  Backup-extension is quite robust

yes , but so far I noticed is not paying attention if there is a column or not , it just tries to insert into DB and if the columns are not matched it fails,

@ViorelEremia  @andreiglingeanu  could take a look at it,  we had few issues like this already .

**Comment by andreiglingeanu** [comment]
Hm, that's interesting

> What I have noticed is , if you have ANY plugin that is altering DB on install and you do a backup on that site, once you try to restore it on a site that does not have these plugins installed the restore/install will fail with similar msg

WooCommerce will do? Do you have a step by step reproduction you could share please?

**Comment by danyj** [comment]
@andreiglingeanu  

install Category Order and Taxonomy Terms Order plugin , 
reorder some posts  so that the DB column is created , 
create content backup 
go on clean install without the plugin install Unsyon and try to do restore

**it will fail** 
now on clean install ,   install Category Order and Taxonomy Terms Order plugin 
and try restore again 
goes trough

**Comment by danyj** [comment]
> WooCommerce will do

only if you add it as requirement in demo install

**Comment by danyj** [comment]
basically if you have full blown demo with plugins that add columns to DB 
you will never be able to import on clean install without those plugins being installed before you do demo install or restore

**Comment by ivandotv** [comment]
@danyj offtopic:
Are you in production? Have you released your theme yet? 
Let us have a look :)

**Comment by danyj** [comment]
@ivandotv  finishing docs , will be out soon 
https://themezly.com/

**Comment by ivandotv** [comment]
I believe that plugins should add their own tables , and not modify default WP tables.
Maybe the solution to this is to have a list of default WP tables. And when new table needs to be inserted,  if it's not on the list. The table can be skipped, or created.
