### ISSUE TITLE
Formatting button size (width) and Alignment

### ISSUE THREAD

**Issue by rjgoldstein** [ThemeFuse/Unyson#3065]
I have a simple page using the Unyson framework. The page consists of:
* a section layout element where inside the element I have 
**A (1/1) text Box and below the text box i have
*** A (1/4) box then a (1/2) box and then a (1/4) box
in each (1/4) box there is one button. The left (1/4) box the button is labeled "Previous" and the right side button is labeled "Next"
Unfortunately the button controls are only
Button Label
Button Link
Open Link in new window
Button color
I need button width so that both the left and the right buttons can be the same width, and I need to be able to align the button right because the default seems to be align left and there are no controls to change this.
On a previous project where I used Unyson Framework these controls were available. Where did they go?
the previous project used ThemeFuse; Philanthropy. 
![unyson button issue](https://user-images.githubusercontent.com/1416187/33663661-da38229e-da5e-11e7-948b-4084c7062752.PNG)

**Comment by ViorelEremia** [comment]
By default unyson dosent have button align contact theme author support.
