### ISSUE TITLE
Multi-picker in option-type

### ISSUE THREAD

**Issue by ange007** [ThemeFuse/Unyson#3067]
Hello.
I wrote my option-type, but it behaves in some strange behavior.

**view.php:**
```php
echo fw( )->backend->render_option(
'gradient-animate',
[
	'type'		=> 'multi-picker',
	'label'		=> false,
	'desc'		=> __( 'Animate', 'default' ),
	'picker' => [
		'active' => [
			'type' => 'switch',
			'value' => 'off',
			'label' => false,
			'left-choice' => [
				'value' => 'off',
				'label' => __( 'Off', 'default' ),
			],
			'right-choice' => [
				'value' => 'on',
				'label' => __( 'On', 'default' ),
			]
		],
	],
	'choices' => [
		'on' => [
			'gradient-animate-angle' => [
				'type'		=> 'slider',
				'label'		=> false,
				'desc'		=> __( 'Scroll Angle', 'default' ),
				'properties' 	=> [ 'min' => 0, 'max' => 100, 'step' => 1 ],
			], 
			'gradient-animate-speed' =>	[
				'type'		=> 'slider',
				'label'		=> false,
				'desc'		=> __( 'Speed', 'default' ),
				'properties'	=> [ 'min' => 0, 'max' => 100, 'step' => 1 ],
			], 
		],
	]
],
[ 
	'value'		=> $animate_values, 
	'id_prefix'		=> $data[ 'id_prefix' ] . $id . '-',
	'name_prefix'	=> $data[ 'name_prefix' ] . '[' . $id . ']', 
]
```

**class.php:**
```php
protected function _get_value_from_input( $option, $input_value )
{
...
if( $input_value[ 'gradient-animate' ][ 'active' ] === 'on' ) { echo 'true'; } // not work
if( $input_value[ 'gradient-animate' ][ 'active' ] === '"on"' ) { echo 'true'; } // work
...
}
```

What could be the reason?

**Comment by danyj** [comment]
> some strange way

we cant guess  what " strange way" means , be precise , say what the issue is.

**Comment by ange007** [comment]
Sorry for my english.

It is strange that in the parameter `$input_value[ 'gradient-animate' ][ 'active' ] ` contains the text in brackets.

**Comment by ViorelEremia** [comment]
I don't understand what view.php and ```echo fw( )->backend->render_option(``` 
Share whole your option type. I tested your array and it's fine.

**Comment by ange007** [comment]
Here is the component: [custom-background.zip](https://github.com/ThemeFuse/Unyson/files/1556389/custom-background.zip)


After applying the parameters in the array is

```
$input_value[ 'gradient-animate' ][ 'active' ] === '"on"'
/// and
$input_value[ 'image-attach' ][ 'active' ] === '"yes"'
```

**Comment by andreiglingeanu** [comment]
Hey @ange007, you have to do a proper `get_value_from_input` before using the values of the switch. This step will ensure that you are dealing with plain strings and not JSON strings.

Here's an example from `multi-picker`:

https://github.com/ThemeFuse/Unyson/blob/f60dc51b4d5d767bd8bac22d1c2721361affa167/framework/includes/option-types/multi-picker/class-fw-option-type-multi-picker.php#L406-L409

Another option is to do `json_decode($input_value[ 'image-attach' ][ 'active' ])` which will indeed yield `'yes' | 'no'`, just like you expect but that's _very_ inflexible and error prone, in case we get to change the way switch option type gets implemented.

**Comment by danyj** [comment]
@ange007  Did you try my way?

https://github.com/ThemeFuse/Unyson/issues/670#issuecomment-111555891

I dont have issue with the quotes

here class 

https://gist.github.com/danyj/30ec82131c7cebe0c563a52de3411c06

and view 

https://gist.github.com/danyj/c1425abdadfddd948ddcf2027722b55c

**Comment by ange007** [comment]
@andreiglingeanu @danyj
I have not tried it yet, but I will definitely try it. 
Thanks.

**Comment by danyj** [comment]
ok , just pay attention here 
https://gist.github.com/danyj/30ec82131c7cebe0c563a52de3411c06#file-thz-animation-class-L129

you just want to add own select choices ,  I use custom function that I am reusing elsewhere
