### ISSUE TITLE
Trouble with fw_ext_shortcodes_decode_attr

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3072]
@andreiglingeanu  @ViorelEremia 
we are using `fw_ext_shortcodes_decode_attr` to decode shortcodes

https://github.com/ThemeFuse/Unyson/issues/1933
https://github.com/ThemeFuse/Unyson/issues/2531

by looking at the function it asks for post id 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/a5816de8e8594cd77cc8c3e18183b381236cf9b2/helpers.php#L10

than it checks if it can decode , 

so shouldn't the `fw_ext_shortcodes_decode_attr  `return false if no ID is set? 

I am asking because I have some shortcodes decoded on search results and 404 page , but since these pages  have no post->ID the post id was returning `null` and was generating warnings  `Trying to get property of non-object
`
```
function _thz_shortcode_options($data,$shortcode){
	
	$atts = shortcode_parse_atts( $data['atts_string'] );
	$atts = fw_ext_shortcodes_decode_attr($atts, $shortcode, $data['post']->ID);
	
	return $atts;
}

```

now I am doing this and it seems to work 

```
function _thz_shortcode_options($data,$shortcode){
	
	$atts 		= shortcode_parse_atts( $data['atts_string'] );
	$post_id 	= isset( $data['post']->ID ) ? $data['post']->ID : false;
	$atts 		= fw_ext_shortcodes_decode_attr( $atts, $shortcode, $post_id );
	
	return $atts;
}
```

I just need to make sure that I am doing this right , this is the data that comes down

![screenshosst_1](https://user-images.githubusercontent.com/2340172/33850877-94981e28-deb5-11e7-8796-1ce08c88630b.jpg)

and I see similar thing done here 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/a5816de8e8594cd77cc8c3e18183b381236cf9b2/includes/class-fw-shortcode.php#L206

what do you suggest ?

**Comment by andreiglingeanu** [comment]
No, actually the `$post_id` is _optional_ for that function and is not required at all for getting the decoding process to work. It is made so intentionally for making it possible to handle atts decoding outside of the main WordPress loop. You are probably doing it correctly.
