### ISSUE TITLE
Editor blank, while content still there un page, cant change or update the page

### ISSUE THREAD

**Issue by rosasmk** [ThemeFuse/Unyson#3075]
I just updated and I found the code in editor is missing, the page shows fine to visitor but neither default editor or page builder show how to change content, any ideas?

**Comment by ViorelEremia** [comment]
See here: https://github.com/ThemeFuse/Unyson/issues/3035
Check console for errors, update unyson extensions.

**Comment by rosasmk** [comment]
the version is up to date the console shows this:
![screen shot 2017-12-12 at 10 40 08 am](https://user-images.githubusercontent.com/32020447/33893275-066e1ba6-df29-11e7-9bc5-97a29e8ed02f.png)

**Comment by ViorelEremia** [comment]
Any cache server or plugins, are you sure you have latest extensions? extensions do not update with unyson 
Drop me some temporary credentials (admin): viorel [ a ] themefuse [ dot ] com
