### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by weddream** [ThemeFuse/Unyson#3076]
Hello!
Step by step I will describe and show the problem on the example of my site flart.ru

1. After another update Wordpress lost visual blocks
![bj4jsdwfskcmhlituurvna](https://user-images.githubusercontent.com/34505247/33930604-8e8e2cda-dffe-11e7-855a-3b901971dd62.jpeg)

2. Update the WP to a newer version
![2](https://user-images.githubusercontent.com/34505247/33930687-c5f6ca88-dffe-11e7-84e3-c1804b28e3a4.jpeg)

3. Update all plugins
![3](https://user-images.githubusercontent.com/34505247/33930713-e2af145a-dffe-11e7-98c7-b4ae8e7550d6.jpeg)

![4](https://user-images.githubusercontent.com/34505247/33930734-fa928eda-dffe-11e7-985f-3903c8040f72.jpeg)

4. We're watching. Blocks did not appear.
![5](https://user-images.githubusercontent.com/34505247/33930761-0b9405d8-dfff-11e7-8be8-eeb3e2cb181a.jpeg)

5. Watch the preview
![6](https://user-images.githubusercontent.com/34505247/33930762-0bc32890-dfff-11e7-9085-a4c4a22dd86d.jpeg)

6. Blocks can not be seen, but the page is displayed correctly
![7](https://user-images.githubusercontent.com/34505247/33930763-0bf03560-dfff-11e7-8c76-98324a701998.jpeg)

7. It's strange. Then let's update the extensions
![8](https://user-images.githubusercontent.com/34505247/33930764-0c1e6a02-dfff-11e7-81f1-cd55d29202b0.jpeg)

![9](https://user-images.githubusercontent.com/34505247/33930765-0c4d1cf8-dfff-11e7-82b5-8b7423260b9c.jpeg)

8. At last the text appeared. But there are no visual blocks (visual layout)
![10](https://user-images.githubusercontent.com/34505247/33930766-0c7dbd72-dfff-11e7-95cd-e25b121a2d18.jpeg)

9. Let's look at the preview
![11](https://user-images.githubusercontent.com/34505247/33930768-0cb20e24-dfff-11e7-891b-888d86c0a4cd.jpeg)

10. All has moved down!
![12](https://user-images.githubusercontent.com/34505247/33930769-0ce02e3a-dfff-11e7-9ab3-583e47a87968.jpeg)

11. We look, that not all additions have downloaded. Download, activate.
![13](https://user-images.githubusercontent.com/34505247/33930770-0d0e6d68-dfff-11e7-85fc-7564fb6fe20b.jpeg)

12. All OK
![14](https://user-images.githubusercontent.com/34505247/33930772-0d727c54-dfff-11e7-9219-22ab72a81133.jpeg)

13. See how the page looks. The text has changed a little, but there are no visual blocks.
![15](https://user-images.githubusercontent.com/34505247/33930774-0da0a926-dfff-11e7-967c-c91eb9ad6835.jpeg)

14. Watch the preview
![16](https://user-images.githubusercontent.com/34505247/33930775-0dce434a-dfff-11e7-89d2-e186e4d165ad.jpeg)

Site
http://flart.ru/services-3/
Template
https://themeforest.net/item/modesto-portfolio-photography-agency-powerful-wordpress-theme/16964965?s_rank=1

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by weddream** [comment]
Server on linux.

Can you leave me your e-mail, where can I send access?

**Comment by ViorelEremia** [comment]
viorel@themefuse.com

**Comment by weddream** [comment]
Thank you!
