### ISSUE TITLE
Error importing backup on remote Dreamhost server

### ISSUE THREAD

**Issue by jorgerc85** [ThemeFuse/Unyson#3077]
Hi, I created a backup locally and tried importing it in my Dreamhost server. After a few seconds I get this error `Invalid byte position (current: 0, received: 0)`.

This is the code I used:
```
// config.php
$cfg = array(
	'files' => array(
          'lasfuentes-backup' => dirname(__FILE__) .'/backup.zip',
	),
);
```
```
// hooks.php
/**
 * @param FW_Ext_Backups_Demo[] $demos
 * @return FW_Ext_Backups_Demo[]
 */
function _filter_theme_fw_ext_backups_demos($demos) {
    $demos_array = array(
        'lasfuentes-backup' => array(
            'title' => __('Backup Las Fuentes', '{domain}'),
            'screenshot' => 'https://domain.com/demo/screnshot.png',
            'preview_link' => 'https://domain.com/demo/lasfuentes-backup',
        ),
        // ...
    );

    $download_url = 'http://www.domain.com/demo/';

    foreach ($demos_array as $id => $data) {
        $demo = new FW_Ext_Backups_Demo($id, 'piecemeal', array(
            'url' => $download_url,
            'file_id' => $id,
        ));
        $demo->set_title($data['title']);
        $demo->set_screenshot($data['screenshot']);
        $demo->set_preview_link($data['preview_link']);

        $demos[ $demo->get_id() ] = $demo;

        unset($demo);
    }

    return $demos;
}
add_filter('fw:ext:backups-demo:demos', '_filter_theme_fw_ext_backups_demos');
```
One thing I find odd is that going to the route `http://www.domain.com/demo/` gives me a code 200 and lets me explore the folder. I read in a different issue that this route should give a code 400 and a blank page.

Another thing I think might be worth mentioning is that importing the demos included with the theme (Woffice) doesn't work either. The same files work fine in a local setup.

Any help or guidance on how to deal with this would be much appreciated. Thanks!

**Comment by ViorelEremia** [comment]
Hi,
did you find the solution to your problem?

**Comment by nosferatv** [comment]
> Hi, I created a backup locally and tried importing it in my Dreamhost server. After a few seconds I get this error `Invalid byte position (current: 0, received: 0)`.
> 
> This is the code I used:
> 
> ```
> // config.php
> $cfg = array(
> 	'files' => array(
>           'lasfuentes-backup' => dirname(__FILE__) .'/backup.zip',
> 	),
> );
> ```
> 
> ```
> // hooks.php
> /**
>  * @param FW_Ext_Backups_Demo[] $demos
>  * @return FW_Ext_Backups_Demo[]
>  */
> function _filter_theme_fw_ext_backups_demos($demos) {
>     $demos_array = array(
>         'lasfuentes-backup' => array(
>             'title' => __('Backup Las Fuentes', '{domain}'),
>             'screenshot' => 'https://domain.com/demo/screnshot.png',
>             'preview_link' => 'https://domain.com/demo/lasfuentes-backup',
>         ),
>         // ...
>     );
> 
>     $download_url = 'http://www.domain.com/demo/';
> 
>     foreach ($demos_array as $id => $data) {
>         $demo = new FW_Ext_Backups_Demo($id, 'piecemeal', array(
>             'url' => $download_url,
>             'file_id' => $id,
>         ));
>         $demo->set_title($data['title']);
>         $demo->set_screenshot($data['screenshot']);
>         $demo->set_preview_link($data['preview_link']);
> 
>         $demos[ $demo->get_id() ] = $demo;
> 
>         unset($demo);
>     }
> 
>     return $demos;
> }
> add_filter('fw:ext:backups-demo:demos', '_filter_theme_fw_ext_backups_demos');
> ```
> 
> One thing I find odd is that going to the route `http://www.domain.com/demo/` gives me a code 200 and lets me explore the folder. I read in a different issue that this route should give a code 400 and a blank page.
> 
> Another thing I think might be worth mentioning is that importing the demos included with the theme (Woffice) doesn't work either. The same files work fine in a local setup.
> 
> Any help or guidance on how to deal with this would be much appreciated. Thanks!

hi, have u gotten solution to this error? i got same error too. pls help me. thank you
