### ISSUE TITLE
wp-content/plugins/unyson/framework/core/components/extensions.php on line 429

### ISSUE THREAD

**Issue by dreyzeroo** [ThemeFuse/Unyson#3079]
Hi i always get the wp-content/plugins/unyson/framework/core/components/extensions.php on line 429 error in addition with wp-content/plugins/unyson/framework/includes/hooks.php on line 228 every time i try to install the slider extension.

Cloudflare and siteground are being used twenty fifteen is the theme no additional plugins

**Comment by danyj** [comment]
what is the error?

**Comment by dreyzeroo** [comment]
I get these messages on my WP page and in the top section of the backend

**Comment by ViorelEremia** [comment]
Have you php 7.2? 
Replace all files from unyson/framework with https://github.com/ThemeFuse/Unyson/tree/master/framework and try again to install extensions.

**Comment by dreyzeroo** [comment]
Wow thank you so much :D

**Comment by ViorelEremia** [comment]
so it works?

**Comment by ViorelEremia** [comment]
Or you can replace only these files: https://github.com/ThemeFuse/Unyson/commit/b35a2a7a1553d18309e7f98d1b62b6d77d773eb5

**Comment by dreyzeroo** [comment]
Yes works
