### ISSUE TITLE
Rewrite Extensions settings default options

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson#308]
If a theme added Feedback extensions as Compatible (for example for events) it is needed to rewrite extensions Config File and change default Custom Posts for this specific theme (For Ex: events)

**Comment by moldcraft** [comment]
We don't provide the possibility to completely overwrite Extension Settings Options because they are used in extension core functionality, not in theme. If you need some additional options in some extension, let us know and we will add a filter.
