### ISSUE TITLE
SiteGround shared hosting install demos issue

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3080]
One of the customers tried to install the demo 
and got its WP wiped 

` One or more database tables are unavailable
`
max execution time by default on SG is 120

php 7.0.26
MySQL 5.6.26 

can anyone test on default SG if backups/restore/demos work right ?

**Comment by danyj** [comment]
it has been reported that this happened while the demo was downloading , so the install did not even start
which tells me that cleanup and backup ran before it, so it must be backup utility issue

**Comment by danyj** [comment]
Looks like this one cam back 
https://github.com/ThemeFuse/Unyson/issues/579

**Comment by danyj** [comment]
Demo database.json.txt unicode

utf8mb4_unicode_520_ci

**Comment by danyj** [comment]
@ViorelEremia 

We got another user demo issue and seems like MySQL coalition 

http://prntscr.com/i18vbc

**Comment by ViorelEremia** [comment]
can I directly inspect the server with the problem?

**Comment by ViorelEremia** [comment]
some temporary credentials (admin, ftp): viorel@themefuse.com

**Comment by danyj** [comment]
I am waiting for @MeganRuthJones  reply , and will advise what demo sql coalition is for these tables 

demo was created on MySQL 5..7.11

**Comment by ViorelEremia** [comment]
Try something from here: https://stackoverflow.com/questions/42385099/1273-unknown-collation-utf8mb4-unicode-520-ci

**Comment by danyj** [comment]
already checking those but cant proceed until I get the server info

**Comment by danyj** [comment]
This was collation issue  , fix

https://stackoverflow.com/a/44122258/594423
 https://www.youtube.com/watch?v=Ot2QZ6Kv0tw&vl=en
