### ISSUE TITLE
Archive Zip: Cannot close the zip file

### ISSUE THREAD

**Issue by brianlean** [ThemeFuse/Unyson#3082]
When I try to make a backup the backup runs but I get this error:   Archive Zip: Cannot close the zip file.

I developed my site on my desktop and copied it to my ec2 environment.  Do I need to clean something out to make this work?

**Comment by ivandotv** [comment]
probably memory or drive space is insufficient.

**Comment by ViorelEremia** [comment]
There are many reasons why this would happen one of them can be the file is not created via function ```$zip->addFile``` you need to check if file_exists or is_readable here: unyson\framework\extensions\backups\includes\module\tasks\type\class-fw-ext-backups-task-type-zip.php line 126
Or it can be empty. Also you can check what is happening with setCompressionName.
