### ISSUE TITLE
icon-v2 backend style bug in Firefox

### ISSUE THREAD

**Issue by damnedqueen** [ThemeFuse/Unyson#3083]
![firefox_bug](https://user-images.githubusercontent.com/5311721/34073103-a7d53592-e2a3-11e7-8f03-18b80767aa3d.png) 

How fix it?

**Comment by ViorelEremia** [comment]
Is it related to this issue: https://github.com/ThemeFuse/Unyson/issues/3089

**Comment by andreiglingeanu** [comment]
@ViorelEremia Not really, it is a CSS problem which affects only Firefox

**Comment by damnedqueen** [comment]
yes, its problem with flexbox in Firefox.

**Comment by andreiglingeanu** [comment]
Here's the fix #3132.
