### ISSUE TITLE
cURL error 6: name lookup timed out

### ISSUE THREAD

**Issue by onebelarusianguy** [ThemeFuse/Unyson#3086]
Hi,
One of my customer has an issue with downloading extensions:
`Failed to access Github repository "ThemeFuse/Unyson-PageBuilder-Extension" releases. (cURL error 6: name lookup timed out)`
Any thoughts?
Thanks in advance.

**Comment by ViorelEremia** [comment]
I think it's a hosting issue that is blocking the connection to github.
has curl extension latest version?
check dns config?

**Comment by marcooliva** [comment]
I am also having the same problem.
![unyson_install_compatible_extensions](https://user-images.githubusercontent.com/27739743/34481958-ea1b2978-efac-11e7-90ce-bcc4d0902abf.png)
![unyson_install_compatible_extensions2 png](https://user-images.githubusercontent.com/27739743/34481961-ef468ec4-efac-11e7-9bd1-b96fa2f842d5.png)

**Comment by marcooliva** [comment]
My problem is solved.
I updated the PHP version from 5.6 to 7, and then tried to install again.
It worked!
