### ISSUE TITLE
Problem with width Jetpack tiled gallery in Unyson builder

### ISSUE THREAD

**Issue by lyudrummer** [ThemeFuse/Unyson#3088]
Hello,

I have an issue regarding Jetpack tiled gallery. When I put this tiled gallery within the Unyson Builder, there is an issue with the width, it doesn't take all the space.

For example, this page has the issue (at the bottom) : https://honeypackbags.com/fr/guide-pays/sri-lanka/

You'll find below the screenshot of the issue.
![capture](https://user-images.githubusercontent.com/34675211/34147397-cff01e60-e49d-11e7-8113-81f714fac1e4.PNG)

I contacted first the support of my theme ([wp zoom inspiro](https://www.wpzoom.com/themes/inspiro/)). They tried to force a width in functions.php with the following code:

`function wpzoom_custom_tiled_gallery_width() { return '1200'; } 
add_filter( 'tiled_gallery_content_width', 'wpzoom_custom_tiled_gallery_width' ); `

However it doesn't work the Builder.

Below is their message about it:

> Hello Florian,

> The problem is that you must set content width for that full-width unyson builder template in order Jetpack Tiled Gallery to work well the Unyson Builder. The code lines I added was for that purpose, unfortunately it doesn't work the Builder.

> **We have set content width for other templates in the theme however it needs something within the builder to make it work with Jetpack Tiled Gallery.**

> We recommend you to contact the author of Unyson Builder, you can ask their help here:
https://github.com/ThemeFuse/Unyson/issues

Could you help me out here?

Many thanks

Florian

**Comment by danyj** [comment]
Unyson provides base framework which is same as bootstrap
gallery adds own width which  is limiting the container , 
http://prntscr.com/hpmy6n

if you look closely column is completely stretched http://prntscr.com/hpmz4q, 
so i would go back 
1. WP zoom , theme dev
2. Jetpack  "support " who did not care to look at the code

**Comment by llemurya** [comment]
@lyudrummer  please close the issue, the support will become with an answer, it is a Jetpack issue, it is not from Unyson.

**Comment by lyudrummer** [comment]
ok thank you for your quick answer
