### ISSUE TITLE
icon v2 doesn't display SVG files

### ISSUE THREAD

**Issue by DKudleichuk** [ThemeFuse/Unyson#3089]
Hi there

after updating, i cant choose SVG icon, it is not displayed in backend

![screenshot_2](https://user-images.githubusercontent.com/1137721/34172774-d3568658-e4fb-11e7-9cdb-49e4fbdefd98.png)

even when i select this empty field

![screenshot_3](https://user-images.githubusercontent.com/1137721/34172809-f234ab18-e4fb-11e7-8aa7-7d30ca89289d.png)

**Comment by DKudleichuk** [comment]
Hey guys, is there any update on this? Thank you

**Comment by DKudleichuk** [comment]
An issue was posted one month ago, no reaction. I think your framework is dead since you don't support it. Going to find something better that this fucking shit

**Comment by andreiglingeanu** [comment]
There's no need to be mean here. That's just not how open source works.
