### ISSUE TITLE
How i print multi picker ?

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#309]
Hi
first of all thank you so much for this awesome Theme options
i have found how to create multipicker here http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi-picker
but i dont find any doc how i will print for show data from db  for multipicker

can you please share how i can use data from db  for multipicker

Thank you in advance

**Comment by danyj** [comment]
print_r(fw_get_db_settings_option('option_name'));

**Comment by moldcraft** [comment]
Hi,
Thank you for the kind words.

Use [these functions](http://manual.unyson.io/en/latest/helpers/php.html#database) to get option values from the database.

**Comment by xperter** [comment]
Hell yeah  thanks @moldcraft  :) :100:
