### ISSUE TITLE
Working with static.php files in shortcodes without defalut static file

### ISSUE THREAD

**Issue by vivalafit** [ThemeFuse/Unyson#3091]
Greetings to everyone ! 
I was customizing a `media-image` section and i wanted to add custom css like in this issue : #3085 
But the main problem was - i haven't seen any `static.php` file **_so_** regarding to @danyj and his referenced issue to my previous one : #1871 i came up with viable solution
So, i decided to create `static.php` file in path `themename\frameworkcustomizations\extensions\shortcodes\shortcodes\media-image\`
 and i wrote such code to this file : 
```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}
$shortcodes_extension = fw_ext( 'shortcodes' );
// WORKS
wp_enqueue_style(
	'fw-shortcode-media-image',
	$shortcodes_extension->locate_URI( '/shortcodes/media-image/static/css/styles.css' )
);
//media-image adding style to css - DOESN'T WORK
if (!function_exists('_action_theme_shortcode_media_image_enqueue_dynamic_css')){
//start
function _action_theme_shortcode_media_image_enqueue_dynamic_css($data) {
    $shortcode = 'media-image';
    $atts = shortcode_parse_atts( $data['atts_string'] );
    $atts = fw_ext_shortcodes_decode_attr($atts, $shortcode, $data['post']->ID);
	//css fragmenets
	
	//
	$custom_css = '#spaceText_done	 img{
	   position:relative;
	   left:40%;
	   margin-top:100px;
	}';
    //
    wp_add_inline_style(	
        'fw-shortcode-media-image',
         $custom_css 
    );
}
	add_action(
		'fw_ext_shortcodes_enqueue_static:media-image',
		'_action_theme_shortcode_media_image_enqueue_dynamic_css'
	);
}
```
The problem is : style is enqueued succesfully and i can write and style there properly , **_but_** functions and other stuff dont work either  . So , i checked almost everywhere - i wrote correct shortcode name and i can't get why code does not work properly . 

**_Second problem_** - i want to get a section id/class in which this image is located . As you can see from this fragment  : 
```
//css fragmenets
	
	//
	$custom_css = '#spaceText_done  img{
	   position:relative;
	   left:40%;
	   margin-top:100px;
	}';
```
In `$custom_css` variable i have `#spaceText_done` identifier , in which my image is alocated and i am eager to know how to get a `section_id` in a separate variable or is it actually possible ,because i was looking for something similar in Unyson documentation and didn't manage to find any essential info about my issue.

How my `$custom_css` variable supposed to look after i recieve `section_id` ,where my image is located:
```
        //css fragmenets
        $outer_section_id = // logic to get identifier of section that wraps image
	//
	$custom_css = '#' . $outer_section_id . '  img{
	   position:relative;
	   left:40%;
	   margin-top:100px;
	}';
```

**_Third problem_** : also it would be perfect to know how to show special options in page builder shortcodes like sections,images and others - depending on were previous options set true or not . For example  : 
![image](https://user-images.githubusercontent.com/24575491/34220401-36974f4c-e5bd-11e7-8845-e0593f9605c1.png)
If background image is set - we show options like image position and similiar to previous one .

Thanks to everyone for help!

**Comment by andreiglingeanu** [comment]
Adding actions (via `add_action('HOOK_NAME', _callable_name)`) won't work in `static.php` because `static.php` is invoked at the `wp_enqueue_scripts` time, that is you're performing the action too late. You'll have to move the logic somewhere in your `functions.php`.

<hr>

For second problem: Use `unique` option type, like so:

```php
// options.php

$options = array(
  'unique' => array('type' => 'unique')
);

// view.php (or your custom CSS hook)
$unique_id = fw_akg('unique', $atts);
```

<hr>

Learn about [`'type' => 'multi-picker'`](http://manual.unyson.io/en/latest/options/built-in/multi-picker.html).

**Comment by vivalafit** [comment]
@andreiglingeanu in `add_action` function i changed : 
`'fw_ext_shortcodes_enqueue_static:media-image'` to 
`'fw_ext_shortcodes_enqueue_static:media_image'` - and after that all functions worked as intended 
Do i have to move logic to `functions.php` or i can leave this like this as it worked for me ?

**Comment by danyj** [comment]
@andreiglingeanu it works in shortcode/static.php , @moldcraft  made sure  that it loads on time ,  I am using it


```
<?php if (!defined('FW')) die('Forbidden');

/*
	custom css for text block

*/

if(!function_exists('_thz_text_block_css')){
	
	function _thz_text_block_css ($data) {
	
		$atts 		= _thz_shortcode_options($data,'text_block');
		$id 		= thz_akg('id',$atts);
		$css_id 	= thz_akg('cmx/i',$atts);
		$id_out		= !empty($css_id) ? str_replace(' ','',$css_id): 'thz-text-block-'.$id;
		$bs			= thz_print_box_css(thz_akg('bs',$atts));
		$h			= thz_typo_css(thz_akg('h',$atts));
		$t			= thz_typo_css(thz_akg('t',$atts));
		$l			= thz_typo_css(thz_akg('l',$atts));
		$lh			= thz_akg('l/hovered',$atts);
		$add_css 	= '';
		
		
		if($bs !='' || $t !=''){
			$add_css .= '#'.$id_out.'.thz-text-block.thz-shc{';
			$add_css .= $bs;
			if($t !=''){
				$add_css .= $t;
			}
			$add_css .='}';
		}
		
		if($h !=''){
			$add_css .='#'.$id_out.' h1{'.$h.'}';
			$add_css .='#'.$id_out.' h2{'.$h.'}';
			$add_css .='#'.$id_out.' h3{'.$h.'}';
			$add_css .='#'.$id_out.' h4{'.$h.'}';
			$add_css .='#'.$id_out.' h5{'.$h.'}';
			$add_css .='#'.$id_out.' h6{'.$h.'}';
		}
		
		if($l !=''){
			$add_css .= '#'.$id_out.'.thz-text-block.thz-shc a{';
			$add_css .= $l;
			$add_css .='}';			
		}
		
		if($lh !=''){
			$add_css .= thz_hover_css('#'.$id_out.'.thz-text-block.thz-shc a',$lh);			
		}
				
		if(!empty($add_css)){
			ThzDoc::set( 'cssinhead', $add_css );
		}		
	}
	
	add_action('fw_ext_shortcodes_enqueue_static:text_block','_thz_text_block_css');
}
```

**Comment by danyj** [comment]
here the atts getter 


```
function _thz_shortcode_options($data,$shortcode){
	
	$atts 		= shortcode_parse_atts( $data['atts_string'] );
	$post_id 	= isset( $data['post'] ) ? $data['post']->ID : 0 ;
	$atts 		= fw_ext_shortcodes_decode_attr( $atts, $shortcode, $post_id );
	
	return $atts;
}
```

**Comment by danyj** [comment]
now pay attention , 
I have a collector class , that collects all CSS  from all shortcodes ,  the  `ThzDoc:set`

that one is than used in theme static.php  , here is detailed info 


https://github.com/ThemeFuse/Unyson/issues/750#issuecomment-124056941

this way I get ALL  dynamic CSS in one big array and output it in one place, making it available for print or modifications

**Comment by danyj** [comment]
@andreiglingeanu  you are somehow right , I am just sending CSS to my class

**Comment by danyj** [comment]
> add_action function i changed :

yes , all dashes must be changed to underscore 

`text-block` = `text_block`

and so on

**Comment by vivalafit** [comment]
@danyj do you have any ideas how i can get custom id of my section from element inside the section - like image or anything else ?
For example : 
![image](https://user-images.githubusercontent.com/24575491/34231122-6a451a7e-e5e3-11e7-9e70-3fb73c8101ed.png)
I have section with `custom_Id`  variable and in this section i have an image
![image](https://user-images.githubusercontent.com/24575491/34231175-9ed270ca-e5e3-11e7-80d0-3fefa98230a3.png)
So , i want to change styles only for images that located in this section . Does framework have any options to do like that if i want to achieve something like this  : 
```
//css fragmenets
        $outer_section_id = // logic to get identifier of section that wraps image
	//
	$custom_css = '#' . $outer_section_id . '  img{
	   position:relative;
	   left:40%;
	   margin-top:100px;
	}';
```

**Comment by danyj** [comment]
look what I did in static.php

		$atts 		= _thz_shortcode_options($data,'text_block');
		$id 		= thz_akg('id',$atts); // this one is uniqueid  option type
		$css_id 	= thz_akg('cmx/i',$atts); //  this is the USER inputed
		$id_out		= !empty($css_id) ? str_replace(' ','',$css_id): 'thz-text-block-'.$id;



than in view.php   you do the same 


```
$id 			= fw_akg('id',$atts);
$css_id 		= fw_akg('cmx/i',$atts);
$id_out			= !empty($css_id) ? str_replace(' ','',$css_id): 'thz-text-block-'.$id;
```

and as html ID you would use   `$id_out	`

`<div id="<?php echo esc_attr( $id_out ) ?>"`

**Comment by danyj** [comment]
put this in shortcode options.php 


	'id' => array(
		'type' => 'unique',
		'length' => 8
	),

**Comment by vivalafit** [comment]
should i put option in section or in inner image?

**Comment by vivalafit** [comment]
just want to make it clear for me

**Comment by danyj** [comment]
I have that option in every shortcode , and use it for CSS and HTML ID if user did not input its own

**Comment by vivalafit** [comment]
and what if i have already custom_id and i want to have an acces from image to outer section id?

**Comment by vivalafit** [comment]
shall i use `$_SESSION` variable on some section variable like the same `custom_id` variable to acces from image's `static.php` file?

**Comment by danyj** [comment]
you cant "see"  section ID in inner shortcode , you need to come up with own logic
or see if corrections could help you out 

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/002672e2520ccf002cc0d553b8fed7882a1d6466
