### ISSUE TITLE
Getting error with Unyson Plugin when activated and installed extensions

### ISSUE THREAD

**Issue by webright2015** [ThemeFuse/Unyson#3093]
Setup all the required theme configurations. When installed all the plugins, evrything was working fine. When installed extensions of Unyson plugin, page builder extension doesnt download. Locally everything working fine but on server it's throwing an error "Notice: Undefined index: id in /var/www/sparklegenepr_dev/releases/20171221120823/content/plugins/unyson/framework/extensions/update/extensions/custom-update/class-fw-extension-custom-update.php on line 252"

I'm using the wp-deploy script. Tried putting all the files using FTP but still the same error. I also re-installed everything but still failing.

This is my error log on server:

[Thu Dec 21 12:34:53.653194 2017] [:error] [pid 16986] [client 103.210.48.87:48673] PHP Notice:  Undefined index: id in /var/www/sparklegenepr_dev/releases/20171221123113/content/plugins/unyson/framework/extensions/update/extensions/custom-update/class-fw-extension-custom-update.php on line 252, referer: http://dev.sparklegenepr.com/wordpress/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=page-builder

![screen shot 2017-12-21 at 5 49 04 pm](https://user-images.githubusercontent.com/34305840/34285339-16d66f4c-e6ff-11e7-8aaf-d3d448cafbcb.png)
![screen shot 2017-12-21 at 5 48 47 pm](https://user-images.githubusercontent.com/34305840/34285340-17191cb6-e6ff-11e7-9767-55f243c4365e.png)

PS: When Unyson is activated with other themes its working fine. When Unicum theme activated, it throws this error.

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by carlosromanxyz** [comment]
Same issue here, i'm getting Error 500 when plugin was activated.

**Comment by webright2015** [comment]
Apologies for the delay @ViorelEremia .
username: guest_admin
password: NelhlSyJ(mhkAFQsUDxeteqp

url: http://dev.sparklegenepr.com/wordpress/wp-admin/

**Comment by webright2015** [comment]
@ViorelEremia I have sent the credentials on your mail.

**Comment by webright2015** [comment]
@ViorelEremia Any success with the issue?

**Comment by ViorelEremia** [comment]
Hi,
have you right permission for folder wp-content?
and i can't connect via ftp or sftp error "Connection to 'sftp://
139.59.87.161' failed. Port number is missing from URI "ftps://sftp://
139.59.87.161:21/"." - tried to add port number but nothing is happening.
Is this path on your server valid? try and check it out:
var/www/sparklegenepr_dev/releases/20171223074038/content/plugins/unyson/

**Comment by webright2015** [comment]
Can you provide me your ssh key so that I can give you access to my server?

Warm Regards,

**Comment by webright2015** [comment]
@ViorelEremia Any update on this issue?

**Comment by webright2015** [comment]
I changed the permissions on the Unyson plugin folder and I'm able to install and update the Page Builder Plugin. But the error is still there.

**Comment by webright2015** [comment]
Hello @ViorelEremia , I updated the theme file 

Modified the lines as follows:
`$theme_id = isset( $manifest['id'] ) ? $manifest['id'] : '';
return isset( $manifest ) ? $this->data_manifest( $manifest, 'theme', $theme_id ) : array();`

Now its working fine.

**Comment by musatoktas** [comment]
> Hello @ViorelEremia , I updated the theme file
> 
> Modified the lines as follows:
> `$theme_id = isset( $manifest['id'] ) ? $manifest['id'] : ''; return isset( $manifest ) ? $this->data_manifest( $manifest, 'theme', $theme_id ) : array();`
> 
> Now its working fine.

Hello dear Ghost,
I am facing "Cannot create temporary directory" error while trying while installing an Unyson Extension. So I would like to ask Which part of  the Unyson plugin file you have edited?

Cheers,
Musa
