### ISSUE TITLE
PHP 7.2 bugs

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3095]
How do we fix this for 7.2 ? 
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/inc/init.php#L22

just remove or ?

**Comment by ViorelEremia** [comment]
```
public function include_isolated_callable($path) {
	include $path;
}

call_user_func( array( $this, 'include_isolated_callable' ), $path );
```

**Comment by ViorelEremia** [comment]
Remove self::$include_isolated_callable

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/commit/b35a2a7a1553d18309e7f98d1b62b6d77d773eb5

**Comment by danyj** [comment]
does not work ,  first bug  
`$this when not in object context`


than if I call it with `self::include_isolated_callable($path)`

`all_user_func() expects parameter 1 to be a valid callback, no array or string given i
`
test it please

that var was used here 


https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/inc/init.php#L100-L103

**Comment by ViorelEremia** [comment]
try static ``` public static function include_isolated_callable( $path )```
```call_uer_function( array( __CLASS__, 'include_isolated_callable' ), $path )```

**Comment by danyj** [comment]
ok that worked for the theme , but cant update to unyson 2.7.11  due to existing 7.2 bugs which I see you fixed but if user is already on 7.2 the download is not proceeding

**Comment by danyj** [comment]
use 2.7.10 , switch to php 7.2 and try t update to 2.7.11

**Comment by danyj** [comment]
give me few more min maybee is my 7.2 ini,

**Comment by ViorelEremia** [comment]
what error? now I can't to switch to 7.2

**Comment by danyj** [comment]
http://prntscr.com/hr0lks

**Comment by danyj** [comment]
http://prntscr.com/hr0mtb

**Comment by danyj** [comment]
I think I need openssl ,  checking

**Comment by danyj** [comment]
nope , is on and curl , this is not unyson bug ,  something with 7.2 and wp , testing will advise once fixed

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Scratch-Theme/commit/6ad21caa154319fe82d9f6816b74f2355154c70e

**Comment by danyj** [comment]
if anyone runs in to win10/ wamp issue with php 7.2 

Apache 2.4.18 for some reasn does not load php 7.2 curl

I updated my Apache to 2.4.29 and curl loaded instantly

**Comment by danyj** [comment]
@ViorelEremia , ok 7.2  and Unyson 2.4.11 your bug fixes work 
lets leave this one  open for now in case someone has php 7.2 issue to report

**Comment by danyj** [comment]
`fw_ext_page_builder_get_post_content`
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/aec7bb41437316b8a798ec229147c43d6e78d1eb/helpers.php#L36-L49

returns null in some cases which than causes  

`Warning: count(): Parameter must be an array `

https://core.trac.wordpress.org/ticket/42814

try to do 

`echo do_shortcode( fw_ext_page_builder_get_post_content( $pb_id ) );`

on   tags archive page

**Comment by danyj** [comment]
@ViorelEremia  this needs to be looked at https://core.trac.wordpress.org/ticket/42814 ,  the issue comes from get_post and it might start causing trouble

**Comment by danyj** [comment]
@ViorelEremia  Reopen this please , I just tested with a blank page , nothing on it and this shows up. The sec I disable Unyson is gone. It does not happen on every page but it is happening and seems like they will not fix it.  Jetpack also has same issue and they are trying to rectify on it own  https://github.com/Automattic/jetpack/issues/8420

**Comment by danyj** [comment]
it is on every page ,    in The Core Theme also 

http://prntscr.com/jp3cmc

Wamp 3.0
Apache 2.4.9
Php 7.2.0
