### ISSUE TITLE
I have installed SSL and the unyson plugin is blocking SSL

### ISSUE THREAD

**Issue by Simedya** [ThemeFuse/Unyson#3096]
unyson SSL blocked
unyson uninstall.
I uploaded again
it did not work
ssl and unyson not working together
What do you recommend?
help please 
thank you

**Comment by danyj** [comment]
what theme? 
did you try switching theme to non Unyson theme?

**Comment by Simedya** [comment]
theme name Seosight 
homepage no problem
sub page problems
I do not have SSL in my new pages
UnySon works when I uninstall
is not a problem with different themes
https://yadi.sk/i/LjaNxLsa3QsQNr
https://yadi.sk/i/_pV-ngPo3QsQLS
www.simedya.com

**Comment by danyj** [comment]
than contact theme provider
