### ISSUE TITLE
Can't set HEX color in a color picker

### ISSUE THREAD

**Issue by DKudleichuk** [ThemeFuse/Unyson#3097]
Hi there

I do not quite understand, why did you remove a field in an RGBA color picker option type where i can set color manually?

![screenshot_1](https://user-images.githubusercontent.com/1137721/34341274-c314bcba-e99c-11e7-8f3f-fc1122d21ff2.png)

this makes theme options totally unusable, please get this field back

**Comment by ivandotv** [comment]
Strange, I'm running the latest  version from `master` and both **color picker** and **rgba color picker** work correctly.

**Comment by sollerpolt** [comment]
I had same issue.

**Comment by ivandotv** [comment]
try cloning the `master` branch , and see if the problem persists.

**Comment by ViorelEremia** [comment]
Inspect that input and check who hide it

**Comment by DKudleichuk** [comment]
how can i check "who hides it"? i see that it doesn't display on Unyson settings panel

**Comment by ViorelEremia** [comment]
@DKudleichuk Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/commit/5ad39b79953d58440b7cab543c89d581875320ea
