### ISSUE TITLE
Unison issue 

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#3098]
I'm getting this error on fresh wordpress installation
php: `7.1.8`
wordpress: `4.9.1`
unyson:`2.7.11`

`NOTICE: wp-content/plugins/unyson/framework/extensions/update/extensions/custom-update/class-fw-extension-custom-update.php:252 - Undefined index: id
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/test-theme/index.php'), get_footer, locate_template, load_template, require_once('/themes/test-theme/footer.php'), wp_footer, do_action('wp_footer'), WP_Hook->do_action, WP_Hook->apply_filters, wp_admin_bar_render, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, wp_admin_bar_updates_menu, wp_get_update_data, apply_filters('wp_get_update_data'), WP_Hook->apply_filters, FW_Extension_Update->_filter_update_data, FW_Extension_Update->get_updates, FW_Extension_Update->get_theme_update, FW_Extension_Custom_Update->_get_theme_latest_version, FW_Extension_Custom_Update->get_clean_theme_manifest`

**Comment by ViorelEremia** [comment]
Try this commit: https://github.com/ThemeFuse/Unyson/commit/a129166a5074dfa7870195166ef3bb74633a63a8

**Comment by ivandotv** [comment]
Tried the master branch, the error is gone. :+1:
