### ISSUE TITLE
Unyson closes the Visual Builders in Wordpress

### ISSUE THREAD

**Issue by naisw** [ThemeFuse/Unyson#3099]
When Unyson is activated in my theme (Moodshop) pressing Appearance >> Customize closes the Visual Builder.

I can't edit anything related to Unyson.

**Comment by ViorelEremia** [comment]
Give us more details I don't understand what is not working.

**Comment by naisw** [comment]
I purchased the Moodshop theme.
I'm using the demo install.
Unyson is a required plugin.
When Unyson is installed and activated I can't use "Appearance >> Customize" as it disappear almost immediately when selected.

Click "Appearance >> Customize"
![untitled-1](https://user-images.githubusercontent.com/26445903/34440531-c3ce4f24-ec83-11e7-8b0e-7f79b041b4d9.png)

This page disappear after a couple of seconds
![untitled-2](https://user-images.githubusercontent.com/26445903/34440532-c3db8040-ec83-11e7-89e0-8bef95450585.png)

This is where the page goes afterward and all the editing options doesn't work.
![untitled-3](https://user-images.githubusercontent.com/26445903/34440533-c3e831aa-ec83-11e7-8d3c-f52141c96aec.png)

Opening WPBakery Page Builder
![untitled-4](https://user-images.githubusercontent.com/26445903/34440535-c3f42f96-ec83-11e7-9c56-613527685ed4.png)

WPBakery Page Builder close automatically and ends up here
![untitled-5](https://user-images.githubusercontent.com/26445903/34440536-c4048ee0-ec83-11e7-92da-583cb773a335.png)

When Unyson is uninstalled everything is working as expected.

**Comment by danyj** [comment]
this is theme related , contact your theme provider

**Comment by ViorelEremia** [comment]
I close this issue now if your theme provider detected, that is a plugin issue you can reopen it again.
