### ISSUE TITLE
Register Sidebar Translation Trouble

### ISSUE THREAD

**Issue by fatihsari** [ThemeFuse/Unyson#3103]
Hello, i developing theme with Unyson. This is my first theme with Unyson.
Once, i thank all those who contributed. Unyson FW is really great!

I noticed simple trouble, and fix with myself for my theme.

in hooks.php, `_action_theme_widgets_init` function called with `widgets_init`. But language files load with `_action_theme_setup` function and this function called with `init`.

I think on **Widgets Page** _(wp-admin/widgets.php)_ `widgets_init` run before than `init` hook.
Therefore, our __(), _e() functions not working in Widgets Page.

Again thanks all TF developers.

**Comment by fatihsari** [comment]
Hello again, i re-checked call sequence of hooks(`widgets_init` and `init`). As i said,  `widgets_init` calling before `init`.

```
add_action('init', function(){
    echo "init";
});
add_action('widgets_init', function(){
    echo "w_init_";
});
```

You can use this for testing.

**Comment by ViorelEremia** [comment]
You can read here about sequence of hooks widgets_init and init: https://codex.wordpress.org/Plugin_API/Action_Reference
```Used to register sidebars. Fired at 'init' priority 1 (and so before 'init' actions with priority ≥ 1!)```
