### ISSUE TITLE
problem in form extention

### ISSUE THREAD

**Issue by mohammadghasemi7** [ThemeFuse/Unyson#3104]
hi
i use form extention in my site. but no send form info.
but on another site on other host it work good???
this extention need setting in host???
thanks

**Comment by ViorelEremia** [comment]
Do you use wp-mail or SMTP? check with contact form 7 if it is working

**Comment by mohammadghasemi7** [comment]
Yes contact form 7 working.

در تاریخ ۳ ژانویهٔ ۲۰۱۸ ۶:۴۱ ب.ظ، "ViorelEremia" <notifications@github.com>
نوشت:

Do you use wp-mail or SMTP? check with contact form 7 if it is working

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ThemeFuse/Unyson/issues/3104#issuecomment-355035458>,
or mute the thread

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com
