### ISSUE TITLE
Change portfolio permalink

### ISSUE THREAD

**Issue by FedeM** [ThemeFuse/Unyson#3105]
Hi, I'm using the Portfolio extension on my website and going to Settings> Permalink> Optional and changing "Project base" is not reflected on my site, if I enter by the name I put, for example, products instead of portfolio, automatically redirects to portfolio.

How could I make this not happen?

I am currently using Unyson 2.7.11

From already thank you very much.

**Comment by ViorelEremia** [comment]
I tested on the multisite installation/nonmultisite and is not happening to me. Can you try to disable all plugins and to change the current theme to one of defaults WordPress themes.

**Comment by FedeM** [comment]
Thank you very much for the answer, I'm going to try to deactivate all the plugins to see if any are generating conflict and comment if any in particular generates conflict with Unyson.
