### ISSUE TITLE
Page Builder gone

### ISSUE THREAD

**Issue by yoangov** [ThemeFuse/Unyson#3106]
Hello,

The page is appearing as it should be, but the page builder is gone. I tried de-activating all plugins and it turns out it's the Unyson builder.

I have tried the Dashboard > Updates > Check Again > Update Extensions solution, but I'm getting this error:

<img width="1487" alt="screen shot 2018-01-03 at 12 27 40" src="https://user-images.githubusercontent.com/22469492/34516926-8f4dc9da-f081-11e7-9e2d-e74680d3d75d.png">

Before I get this error, I update the extensions:
<img width="1489" alt="screen shot 2018-01-03 at 12 27 48" src="https://user-images.githubusercontent.com/22469492/34516974-c8f806fa-f081-11e7-835d-93e0c8194ddc.png">

Here is what my page builder looks like. I have a very obvious typo which I can't fix for about a month now :(
<img width="1220" alt="screen shot 2018-01-03 at 12 23 17" src="https://user-images.githubusercontent.com/22469492/34516950-accc91ee-f081-11e7-8c6f-fc1997f7dbc6.png">

**Comment by ViorelEremia** [comment]
Try again to update your extensions. We solved this issue.
