### ISSUE TITLE
Can't download extensions (cURL error 28)

### ISSUE THREAD

**Issue by JavierGerona** [ThemeFuse/Unyson#3107]
Hello,

I've just installed Unyson and I can't install extensions. I'm trying to do this in local host with XAMPP.

> cURL error 28: Operation timed out after 5000 milliseconds with 0 bytes received

I need the extension to import a demo.

Any help is appreciated.

**Comment by ViorelEremia** [comment]
Try again to install the extensions. We solved this issue.

**Comment by JavierGerona** [comment]
Thanks, fixed!
