### ISSUE TITLE
Newest Updates Breaks Plugin

### ISSUE THREAD

**Issue by JackelynThompson** [ThemeFuse/Unyson#3108]
I just updated my wordpress version and the plugin and now when I go to edit any page on my website, I don't have the ability to edit any of the modules that exist...

![untitled-1](https://user-images.githubusercontent.com/6353169/34540355-1be0b54a-f089-11e7-8bcb-16631af46d7a.jpg)

**Comment by ViorelEremia** [comment]
Have you some updates for extensions?

**Comment by revurb** [comment]
I have this exact same issue. No response from the developer in two days?? Can't update the content on pages in my site.

**Comment by revurb** [comment]
it doesnt appear that the extension needs an update. Yes, cleared cache, etc.

**Comment by ViorelEremia** [comment]
@revurb drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by revurb** [comment]
@ViorelEremia just did, thanks.

**Comment by revurb** [comment]
were you able to determine anything?

**Comment by ViorelEremia** [comment]
@revurb check your site

**Comment by revurb** [comment]
yes, I just did and its working. Thank you!
What was the fix?

**Comment by ViorelEremia** [comment]
@revurb I don't remember what the problem was but I think something with the updates of unyson extensions or plugin conflicts

**Comment by revurb** [comment]
Well I appreciate the fix but after giving someone admin access to my site it would be nice to know what was changed.

**Comment by ViorelEremia** [comment]
@revurb I updated the extensions: https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by revurb** [comment]
So can you tel me why there was no indication within the extension 
settings area that there was an update needed? No button to "update", no 
version number, etc?

-- 
Jason Powell
Powell Design Works
802-793-3227
powelldesignworks.com <http://www.powelldesignworks.com>
