### ISSUE TITLE
Design of popup windows is broken on category pages

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#3109]
WooCommerce is creating their custom options on category pages ( product categories)
and they are adding their `css` file `jquery-ui.min.css` and that file is messing up `unyson` popup window.
![selection_009](https://user-images.githubusercontent.com/390700/34583463-268770d2-f198-11e7-909e-f9c362e5afee.jpg)

**Comment by danyj** [comment]
cmon , you should know this :)

https://github.com/ThemeFuse/Unyson/issues/1481
