### ISSUE TITLE
Problem with Page Builder content when importing

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#311]
Hi,

When I export the content of Portfolios and import to another site, the content of Page Builder is shown empty, anyone occur this issue ?

**Comment by sergiubagrin** [comment]
Can you send me .zip file to: dev-team@unyson.io and a screen with existing page. Thanks

**Comment by maiakhoa** [comment]
Hi @sergiubagrin 

I sent you zip file.

**Comment by sergiubagrin** [comment]
ok. Thanks

**Comment by sergiubagrin** [comment]
I need more time to investigate this.

**Comment by maiakhoa** [comment]
Thank @sergiubagrin

**Comment by maiakhoa** [comment]
Do you have any news about this @sergiubagrin ?
