### ISSUE TITLE
Wordpress/Magemto integration and unyson shortcodes

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#3111]
Hello and sorry for my english!!!
This is my problem:
When integrating wordpress with magento, the unyson shortcodes conflict with magento (session?)...
I do not know why, I only know that an error occurs in the session.

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by sandromattei** [comment]
i work in my local machine.
This is the situation:
I have installed only unyson shortcodes and use every shortcode directly in my wp-editor.
this is the error_log.
[Fri Jan 05 10:09:01.687915 2018] [:error] [pid 4659] [client 127.0.0.1:64956] PHP Fatal error:  Mage_Core_Model_Session_Abstract::getMessages(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;Mage_Core_Model_Message_Collection&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition  in /Users/Grafica08/Sites/testshopping/shop/app/code/core/Mage/Core/Model/Session/Abstract.php on line 215
[Fri Jan 05 10:09:04.740754 2018] [:error] [pid 4662] [client 127.0.0.1:64984] PHP Fatal error:  Mage_Core_Model_Session_Abstract::getMessages(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;Mage_Core_Model_Message_Collection&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition  in /Users/Grafica08/Sites/testshopping/shop/app/code/core/Mage/Core/Model/Session/Abstract.php on line 215

if uninstall unyson all work fine

**Comment by ViorelEremia** [comment]
I never used Magento. 
Can you guide me how did you integrate Wordpress/Magento?
