### ISSUE TITLE
Reverse Countdown or CountUP widget

### ISSUE THREAD

**Issue by shahzisme** [ThemeFuse/Unyson#3115]
I'm planning to add a widget that includes a "days since" event widget.

There is a "countdown" widget but once it reaches the date, it just stops there at zero.

Either we could have a "count-up" widget?
or
Maybe an option in the existing countdown widget to stop at zero or continue counting after the target date reaches, in which it becomes a count-up widget.

Would really appreciate this feature.

**Comment by ViorelEremia** [comment]
I don't understand.
```There is a "countdown" widget but once it reaches the date....``` - what widget maybe you mean post type event where you can choose start/end event.
And also ```existing countdown widget`` - has unyson this widget or widget is shortcode or element.
Can you show us more detailed what you mean?

**Comment by shahzisme** [comment]
Sorry, my bad for the confusion. I shouldn't call it a widget. Refer to "countdown" **content element**. After dragging the content element, it gives us options to add a date. This is the date until when the countdown ends (X days, X hours, X minutes, X seconds). 

The problem is, I want a "start date" and it counts FROM that date, how many days, hours, minutes and seconds have elapsed.

**Comment by ViorelEremia** [comment]
Unyson by default doesn't have shortcode countdown, I don't see it, maybe your theme adds it.
