### ISSUE TITLE
Backup/Content Backup not working after installing PHP Zip Module

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#3116]
Hey guys,

I was suddenly seeing the following message when I went to make a content backup:

`Oops, Unyson Backup requires PHP Zip module but it is not enabled on your server. If you are not familiar with PHP Zip module, please contact your hosting provider.`

I've enabled it (I think!) and the message has disappeared, however I still don't get a backup, the spinner pops up as if it's making the backup, it lasts a little longer than normal so the `Abort` message pops up, then it just disappears with no error.

Has anyone else seen this happen or know why this might be happening?

Thanks

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com

**Comment by martinburdon** [comment]
Thanks @ViorelEremia, I've just sent you an email 👍
