### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by bigpurplebox** [ThemeFuse/Unyson#3118]
I want to move the previous/next arrows to the bottom of the testimonials content, can I edit this in the template? What do I need to edit? it's set to style1 currently.

**Comment by ViorelEremia** [comment]
You need to have some skills of js/css. 
You need to copy file(/var/www/html/wp/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/testimonials/views/view.php) in [see here where](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes) and possibly this file: /var/www/html/wp/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/testimonials/static/css/styles.css
By default unyson doesn't have some style1, style2 ... so if you are not the developer of theme contact theme developer.
