### ISSUE TITLE
When updated page backend isn't working correctly

### ISSUE THREAD

**Issue by djgkidd** [ThemeFuse/Unyson#3119]
After doing an update to the newest version, when I goto update a page all of my content is blank and missing from the backend. 

How do I fix this issue?

**Comment by ViorelEremia** [comment]
Go to update page and find update extensions, remove browser cache, plugin cache, server cache.

**Comment by djgkidd** [comment]
I'm not sure where exactly I can find these options to update extentsions,
remove browser cache, plugin cache and server cache.

please help.

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by djgkidd** [comment]
Perfect that worked! However, there are some (not all) sections with
missing content elements in them however they do show up on the actual
website front-end.

**Comment by ViorelEremia** [comment]
@djgkidd drop me some temporary credentials (admin, ftp): viorel@themefuse.com

**Comment by djgkidd** [comment]
Credentials created:

Url: http://www.ezrbiz.com/wp-admin
wordpress username: viorel@themefuse.com
wordpress password: viorel@themefuse.com

Ftp Credentials:

host: ezrbiz.com
username: viorel@ezrbiz.com
password: P@ssw0rd!

Thanks.

**Comment by ViorelEremia** [comment]
@djgkidd I do not see what does not work. Maybe you have not noticed that they are collapsed.
![bla-bla-bla](https://user-images.githubusercontent.com/28967378/34957564-cb152c74-fa36-11e7-8ef5-8ec745186f69.png)

**Comment by djgkidd** [comment]
Wow, I'm sorry lol. Thank you, It's been a long week, can't believe I
didn't realize that.

Thank you.
