### ISSUE TITLE
How can I add Import xml in Backup extension ?

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#312]
Hi,

I would like to add Import xml function to my theme, so Can we have a way to add a button to Backup extension ? Beside "Edit Backup Schedule" and "Create Full Backup Now". Due to I don't want users have to remove their old data like "Content Demo Install".

Thanks

**Comment by sergiubagrin** [comment]
Hi @maiakhoa 

It is not possible to add XML file to Backup extension. Content Demo Install is working in a different way: http://manual.unyson.io/en/latest/extension/contentdemoinstall/index.html

**Comment by maiakhoa** [comment]
Hi @sergiubagrin 

Thanks for your feedback, I will guide users to Wordpress Import plugin.

**Comment by sergiubagrin** [comment]
Wordpress import is working only for Custom Posts it is not working for Posts Options, Widgets, Config files, etc... With our Content Demo Install all is working 100%

**Comment by maiakhoa** [comment]
@sergiubagrin yes, I understand. The reason I would like to custom Backup extension to add Import all of theme instead of fresh Content demo install that remove all old data.

**Comment by sergiubagrin** [comment]
> Due to I don't want users have to remove their old data like "Content Demo Install".

Right now this is our solution for Import Demo Content. In case this option will be useless in future we will think to change it. Thanks

**Comment by maiakhoa** [comment]
Thank you too
