### ISSUE TITLE
Error after update page in a Visual Page Builder mode

### ISSUE THREAD

**Issue by bguisoli** [ThemeFuse/Unyson#3120]
Fatal error: Uncaught Error: [] operator not supported for strings in /xxx/wp-content/themes/event-organizer/framework-customizations/extensions/shortcodes/shortcodes/section/views/view.php:141 Stack trace: #0 /xxx/wp-content/plugins/unyson/framework/helpers/general.php(745): require() #1 /xxx/wp-content/plugins/unyson/framework/extensions/shortcodes/includes/class-fw-shortcode.php(226): fw_render_view('/Library/WebSer...') #2 xxx/wp-content/plugins/unyson/framework/extensions/shortcodes/includes/class-fw-shortcode.php(191): FW_Shortcode->_render(Array, '[row][column wi...') #3 /xxx/wp-includes/shortcodes.php(345): FW_Shortcode->render(Array, '[row][column wi...', 'section') #4 [internal function]: do_shortcode_tag(Array) #5 /xxx/wp-includes/shortcodes.php(223): preg_replace_callback('/\\[(\\[?)(column...', 'do_shortcode in /xxx/wp-content/themes/event-organizer/framework-customizations/extensions/shortcodes/shortcodes/section/views/view.php on line 141

**Comment by ViorelEremia** [comment]
After which update? 
Extensions or plugin?

**Comment by bguisoli** [comment]
The error appears when I modify the page in Visual Page Builder mode and update it to preview.

**Comment by ViorelEremia** [comment]
It's atheme isssue, contact your theme provider result from the first error located in theme "event-organizer":
/xxx/wp-content/themes/event-organizer/framework-customizations/.....
I think it is not declared some vars as arrays.
