### ISSUE TITLE
iOS browser freezes mobile ( unless unyson disabled )

### ISSUE THREAD

**Issue by stagediver115** [ThemeFuse/Unyson#3121]
Feedthechildrennow.org 

.Doing Seo and edit for a client

Mobile version on iOS and safari browser does not work , page would load and scroll for 3 seconds and then freeze

Desktop / laptopwork work fine

I disabled all plugins one by one and when I disabled unyson the mobile version loaded but the problem is all the attributes and java script is not displayed which I’m
Assuming website was built off of

Would appreciate any type or help I currently have unyson disabled still

**Comment by danyj** [comment]
did you contact the theme provider?

**Comment by stagediver115** [comment]
Just did and theme is also
Up to date

**Comment by stagediver115** [comment]
Had it running for about 13 seconds , scrolling and working and then it seems when site fully loads on brower it stops working and won’t scroll or navigate

**Comment by ViorelEremia** [comment]
Try to activate the default wordpress theme. I see you have a big image 1.8mb(18sec).
