### ISSUE TITLE
Add options to row shortcode.

### ISSUE THREAD

**Issue by nicolaelitvac** [ThemeFuse/Unyson#3124]
Is their a way to add options to **row** shortcode?
This is what I want to add:
```PHP
$options = array(
	'custom_class' => array(
		'label' => __('Custom Classes', 'insignety-rings'),
		'desc'  => __('Enter additional classes for row if needed.', 'domain'),
		'type'  => 'text',
	),
	'row_id' => array(
		'label' => __('Custom ID', 'insignety-rings'),
		'desc'  => __('Enter ID for row if needed.', 'domain'),
		'type'  => 'text',
	)
);
```

**Comment by ViorelEremia** [comment]
No, you can't row is an internal builder item type you can only rewrite it. It isn't rendered in admin like as common shortcodes(accordion, button...). You can see that it doesnt have config.php so if you addd it then it will be shown as a simple shortcode. Use the section options.

**Comment by Taimurian** [comment]
Unfortunately, You can't add options to the row shortcode that's why I added them to the section options as a separate tab.
![untitled-2](https://user-images.githubusercontent.com/1550077/35476096-e43a636a-03b2-11e8-85b5-98ce62c46809.png)
