### ISSUE TITLE
Why Demo content install issue: The execution failed. Please check error.log

### ISSUE THREAD

**Issue by adeputras** [ThemeFuse/Unyson#3125]
i have issues with demo content install, in my localhost i have no issue, but when i tried to install on my domain hosting i get the error.
please help me figure this out
i am new about unyson plugin

**Comment by ViorelEremia** [comment]
What error?
How did you that import?
Give us more information.

**Comment by adeputras** [comment]
@ViorelEremia  
sorry for my language, 
what i mean with error is i get notification like issue https://github.com/ThemeFuse/Unyson/issues/2257 and https://github.com/ThemeFuse/Unyson/issues/2638 "The execution failed. Please check error.log" when i install demo content in my domain hosting but when i install it in my localhost there is no problem and i can get the demo content install

**Comment by ViorelEremia** [comment]
ok, tomorrow(UTC+2) I'll make a commit that can solve your problem too

**Comment by adeputras** [comment]
thank you,
best regards

**Comment by ViorelEremia** [comment]
Try: https://github.com/ThemeFuse/Unyson-Backups-Extension/compare/f8d5f6a1c1...841413f0d6

**Comment by adeputras** [comment]
thank you for your help

**Comment by ViorelEremia** [comment]
is working?

**Comment by adeputras** [comment]
unfortunately still not working :(
i will contact the hosting provider to figure it out or maybe change the hosting provider.
thank you for your help.

Best Regards

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel@themefuse.com
