### ISSUE TITLE
Demos are not compressed properly

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3128]
@ViorelEremia  @andreiglingeanu  

Just found this and we should fix the demo compression type , 

Demo packed via backup utility is 98MB ,  if I take files out of zip and put them back in 
the size goes down by more than 40% 

watch 

http://take.ms/4Wkht

**Comment by danyj** [comment]
With same process a 220MB demo with 500 images packed without remove/resize images goes down by 50MB

**Comment by ViorelEremia** [comment]
1. I created a backup via backup extension.
2. I extracted archive on my desktop.
3. Extracted files I compressed via OS. 
4. Tested on windows/linux.

The sizes are the same.

**Comment by danyj** [comment]
I showed you the video , I am not doing anything different 

wamp, php 7.2

**Comment by danyj** [comment]
I found the cultprit 

read the notes 

https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-zip.php#L130-L142


I removed that snip , recompressed a demo that was compressed previously to 53MB and no size is 30MB 


http://prntscr.com/i1njnh

**Comment by danyj** [comment]
so store "speeds" up the zip by sacrificing the file size , I dont think that the speed is improved by that much to be worth the file size , and by now everyone is on php 7 min wich increases the speed anyway

**Comment by danyj** [comment]
this flag `CM_STORE` creates a zip without compression the files

**Comment by andreiglingeanu** [comment]
It says there that this flag saves some speed on slow servers. I think this has a bigger priority compared to demo content zip size. We can always have a filter for that, though.

**Comment by danyj** [comment]
> some speed on slow servers

how much?  if server is already using php7  than WP is faster and OPcache is on which is tremendous improvement already. I would understand this on php 5 ( which did not have that flag ) but on 7 makes no sense,   I timed on my localhost and see no difference in compression time

**Comment by danyj** [comment]
And we are using this extension since the time of php 5 ,  we did not hear users arguing about the backup compression or time. If they did not complain than than they sure wont complain on 7 so again this makes no sense

**Comment by andreiglingeanu** [comment]
In this case, if @ViorelEremia is okay with that, let's remove this flag

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/283a42365f50251f58bf9a8ace7a06512bb4c4d6
