### ISSUE TITLE
Demo should not fail if recommended plugin is not installed 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3129]
This is one issue we must fix , going in production with unreliable demo installer is a big no no. 

Install category reorder , or Layer  slider , Rev slider  on your demo, export your demo 

Set these plugins as recommended and not auto installable via demo interface or TGMPA , basically user should install them before clicking on demo install button. 

Now since your demo sql  contains tables or columns from these plugins the demo will fail because the plugins are not installed, they add on columns and if their tables are not in DB than that is it. 

In joomla we make demos with drop table if exists since we are already replacing all the content for DB than there is no need to check for columns or do inserts http://prntscr.com/i19ygo

this is the most reliable way of installing content, inserts or any other type of install cant match all possible missing columns or coalitions scenarios.

**Comment by ViorelEremia** [comment]
How that is happening? 
I created a test item in rev.slider after I exported content via backup extension(http://manual.unyson.io/en/latest/extension/backups/index.html#demos-bundled-in-theme). Further I created a new site and i installed demo content whithout to install revolution everything works well. After install demo content I activated revolution and my test slider was imported.

**Comment by danyj** [comment]
Install Category Order and Taxonomy Terms Order plugin 

activate it , and reorder posts or cats 

export your demo 
install it 
it fails

https://github.com/ThemeFuse/Unyson/issues/2872

I went from old Rev and layer slider versions like 7 months old and could not install demo untill I update plugins , re-export demo and install

**Comment by ViorelEremia** [comment]
please test.

**Comment by danyj** [comment]
on it

**Comment by danyj** [comment]
@ViorelEremia  the backup restore is same as demo install right ?

**Comment by ViorelEremia** [comment]
Yes

**Comment by danyj** [comment]
seems ok now   http://prntscr.com/i5cqhq

**Comment by danyj** [comment]
is this https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/2da0013a549770da584bbd03de20e44011e6161f#diff-3c5fc3af6c96cc923c455995d18fbb25R731

fox for https://github.com/ThemeFuse/Unyson/issues/3080

**Comment by ViorelEremia** [comment]
Yes, it should work can you try?

**Comment by danyj** [comment]
> can you try

just did , finishing image resize seems ok

**Comment by danyj** [comment]
Looks ok on my end , il try some shared hosting in next day or two but this look good

**Comment by danyj** [comment]
ok tested on live server **without the fix** and got the old error I mentioned earlier

![screenshot_5](https://user-images.githubusercontent.com/2340172/35387590-a35ad886-01d0-11e8-9a3f-3fbfdb8cc17d.jpg)


added the fix and it went trough

![screenshot_6](https://user-images.githubusercontent.com/2340172/35387612-bf73a9ee-01d0-11e8-83c6-de9744aec5e3.jpg)

so this seems like it is fixed. 


thank you @ViorelEremia !

**Comment by danyj** [comment]
can we have a release for this extension so that ziping size fix and this are in faster?
