### ISSUE TITLE
Fallback to non mb_...() functions if php mbstring is not installed

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson#313]
Every time I try to install Unyson and activate it, it crashes my site. The entire site is just blank. I have to go into the CPanel and delete the Unyson files.

https://wordpress.org/plugins/unyson/

https://wordpress.org/support/topic/installation-of-unyson-crashes-site?replies=4#post-6651977

**Comment by kateburch** [comment]
Where do I add WP_CONFIG = TRUE?

**Comment by moldcraft** [comment]
@kateburch  Add in `wp-config.php`

```php
define( 'WP_DEBUG', true );
```

Sorry for the WP_CONFIG typo.

**Comment by sergiubagrin** [comment]
Please read this post: http://codex.wordpress.org/Debugging_in_WordPress

**Comment by kateburch** [comment]
Ok done. Now what should I do? Reinstall the plugin then check the error log?

**Comment by moldcraft** [comment]
Check the log and maybe some error will be displayed on the page (instead of blank page)

**Comment by kateburch** [comment]
Fatal error: Call to undefined function mb_strtoupper() in /home/si6258/public_html/wp-content/plugins/unyson/framework/helpers/general.php on line 1055

**Comment by moldcraft** [comment]
We will add `if (function_exists('mb_strtoupper')) ...` in the next Unyson release. But for now, as a temporary fix, please replace `wp-content/plugins/unyson/framework/helpers/general.php` with [this file](https://raw.githubusercontent.com/ThemeFuse/Unyson/80718543f0f1fea54c4938d9639e7c32ee86a1bd/framework/helpers/general.php) and let us know if it helped.

**Comment by kateburch** [comment]
It's working now! But I get this message... Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/si6258/public_html/wp-includes/functions.php:3378) in /home/si6258/public_html/wp-content/plugins/unyson/framework/helpers/class-fw-flash-messages.php on line 211

Anything to worry about?

**Comment by danyj** [comment]
You are missing more than just mb_strtoupper, complete set of mb functions is not there so there might be more errors. 
See this please http://stackoverflow.com/a/6419126/594423
And session start issue means that there was an error printed on that page before the session has started.  Look at the page again there will be one more error.

**Comment by moldcraft** [comment]
> You are missing more than just mb_strtoupper, complete set of mb functions is not there so there might be more errors.

I know, [I checked](https://github.com/ThemeFuse/Unyson/commit/80718543f0f1fea54c4938d9639e7c32ee86a1bd) all `mb_str...` functions.
