### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by atokyuz** [ThemeFuse/Unyson#3130]
I updated the old version, it has not improved. I've done manual loading and it continues to give the same error again. The plugin is not active, I tried to set up different places but it still fails.

Warning: require_once(/home/ahmettokyuz/public_html/otel/wp-content/plugins/unyson/framework/core/components/extensions/manager/class--fw-extensions-manager.php): failed to open stream: No such file or directory in /home/ahmettokyuz/public_html/otel/wp-content/plugins/unyson/framework/autoload.php on line 42

Fatal error: require_once(): Failed opening required '/home/ahmettokyuz/public_html/otel/wp-content/plugins/unyson/framework/core/components/extensions/manager/class--fw-extensions-manager.php' (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home/ahmettokyuz/public_html/otel/wp-content/plugins/unyson/framework/autoload.php on line 42

**Comment by ViorelEremia** [comment]
I think it's a server error try to contact hosting provider ```include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear'```

**Comment by atokyuz** [comment]
@ViorelEremia I have been in support for them, but in reply, if there is anything we can tell you from where the problem originated, they respond accordingly.

What is the problem with server side restriction? According to him, I will wait for them to be told and corrected.

**Comment by atokyuz** [comment]
@ViorelEremia "(/home/ahmettokyuz/public_html/hotel/wp-content/plugins/unyson/framework/core/components/extensions/manager/class--fw-extensions-manager.php)" The manager.php file that should be in this directory path no. There are only available-extensions.php files and include, static, views folders.

![github](https://user-images.githubusercontent.com/35506603/35036160-81a6cc1a-fb84-11e7-9f72-77afb235f39e.png)

**Comment by ViorelEremia** [comment]
I don't undeerstand try to upload right unyson folder structure

**Comment by ViorelEremia** [comment]
From your image i don't see backend.php, extensions.php etc. They should be in folder components.

**Comment by atokyuz** [comment]
I also tried from the Wordpress plugin installation menu, I tried manual loading and the result is the same in all. The file path that differs from the file you specify is different.
![1](https://user-images.githubusercontent.com/35506603/35036804-8e116fc6-fb86-11e7-8a0f-5a77b2587716.png)

**Comment by atokyuz** [comment]
![2](https://user-images.githubusercontent.com/35506603/35036875-c36f2b54-fb86-11e7-899f-54abb175d128.png)

**Comment by ViorelEremia** [comment]
Maybe your file manager is not configured right try to upload unyson manually download it from wordpress.org and upload it by filezilla

**Comment by atokyuz** [comment]
I did it already. I downloaded it from Wordpress.org and downloaded the screenshots to you and the program FileZilla program. There is no problem in the installation, when you want to activate, it fails and does not activate the plugin.

**Comment by ViorelEremia** [comment]
Drop me some temporary credentials (admin, ftp): viorel@themefuse.com

**Comment by atokyuz** [comment]
I have sent you, you can check your mail box.

**Comment by atokyuz** [comment]
Are you doing anything? According to him I will take care of different things if it will take a long time.

**Comment by atokyuz** [comment]
What is the last situation? Is there any relevant improvement in the solution to the problem?

**Comment by ViorelEremia** [comment]
I think it's your file permissions. It is probably that your apache isn't able to open the files with permission 0644 and directories 0755.
Also you can try to increase phpversion to 7.1.
Unyson is working from subfolders, we have some servers like yours.

**Comment by atokyuz** [comment]
What do you want me to do with the permits? I will talk to the server company and ask for support for updating. Is there anything I should do other than that?

**Comment by ViorelEremia** [comment]
wait for hosting answer. There is nothing I can do to help. Maybe when we find out more information from hosting provider.

**Comment by rasitozdemir** [comment]
remove this line in "class-fw-settings-form-theme.php"
		 * Usage example http://pastebin.com/gvAjGRm1
and remove this line in "class--fw-extensions-manager.php"
		 * Usage example http://pastebin.com/2iWVRPAU
