### ISSUE TITLE
Unyson rgba option type bug.

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#3134]
Hello @moldcraft 

I am using latest unyson Version 2.7.11 and latest wordpress release.
And i am using rgba option type in one of my meta fields but its through the error.
On front end side its through the array to string fatal error which is.
Notice: Array To String Conversion In \Wp-Content\Plugins\Unyson\Framework\Includes\Option-Types\Rgba-Color-Picker\Class-Fw-Option-Type-Rgba-Color-Picker.Php On Line 86
And in backend where the field actually rendered through the script error which is.
![2018-01-23_1353](https://user-images.githubusercontent.com/12461946/35266342-d0534874-0044-11e8-990a-dea2c6d551f4.png)
And also the when we click on rgba field its no longer work now.
Kindly this is urgent problem that we have facing right now as we have almost used latest unyson in our themes.

Looking forward for your quick response.

**Comment by ViorelEremia** [comment]
Try github development version, i can't reproduce that.

**Comment by wpthemes786** [comment]
Hi @ViorelEremia 
Let me check that version and i will inform you shortly.

**Comment by wpthemes786** [comment]
Hello @ViorelEremia 
No the github version did not resolve my issue.
Please provide my solution for this.

**Comment by ViorelEremia** [comment]
I can't reproduce that, send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by ViorelEremia** [comment]
It is working for me:
![screenshot from 2018-01-23 15-52-51](https://user-images.githubusercontent.com/28967378/35279834-f1923038-0056-11e8-85ba-33192362d98f.png)
