### ISSUE TITLE
Issue with displaying more than 6 services.

### ISSUE THREAD

**Issue by MegDuff** [ThemeFuse/Unyson#3136]
When I use the services element in a page, I can only display six services regardless of how many categories I select or how many  entries I have chosen to display. I have it set to 12 but it will only display six. When I have the option of displaying category choices, it will. But when I choose a category that way, it only shows me the services of that category that was displayed in the original six. 
![snip services 1](https://user-images.githubusercontent.com/35745436/35301581-e890b862-0059-11e8-8be9-c2a3d1737c27.JPG)

**Comment by ViorelEremia** [comment]
That is a theme issue, contact your theme developer, unyson is a plugin that allows developers to build fast and easy their wordpress themes. Your element "services" doesn't exists as a default element in the plugin, so it is created by theme developer.

**Comment by MegDuff** [comment]
Thank you!! Will do!
