### ISSUE TITLE
loss setting deactivation

### ISSUE THREAD

**Issue by HDInfautre** [ThemeFuse/Unyson#3137]
Hi,
By changing the theme (wOffice), I am obliged to deactivate new unyson modules that do not serve me (80%)
Regards

**Comment by ViorelEremia** [comment]
I don't understand what do you mean?
What is "new unyson modules"?

**Comment by HDInfautre** [comment]
Hi,
Thank you for your prompt response.
The best is to explain in pictures
I disable extensions
I change theme (including parent)
I need to disable extensions again
https://screenshots.firefox.com/qNZpsgOHCp1C7bFJ/null

**Comment by ViorelEremia** [comment]
So you mean then you activate theme(after disabled extensions) the new activated theme install some extensions again?

**Comment by HDInfautre** [comment]
yes I have to turn everything off again

**Comment by ViorelEremia** [comment]
Yes, you are right

**Comment by ViorelEremia** [comment]
It isn't a bug, in this way unyson is working we think it is the right way. Some users activate/deactivate themes after they go in frontend and see that some theme features do not work. That is happening because theme required extensions are not installed and they think that it is a bug in theme/unyson. But you can change this behavior something like that:
```
remove_action( 'after_switch_theme', array( '_FW_Extensions_Manager', '_action_theme_switch'  )  )
```

**Comment by HDInfautre** [comment]
Hi,
I respect your opinion even if I think it's up to the webmaster to make the choice.
I installed your code but it does not work!

**Comment by ViorelEremia** [comment]
Use ```add_filter( 'fw_after_switch_theme_activate_exts', '__return_false' );```

**Comment by HDInfautre** [comment]
HI,
It works with you? Not with me !!
Thanks for your help

**Comment by HDInfautre** [comment]
Hi,
Still does not work.
I am with a child theme of wOffice. When I change my parent theme or theme to do a test. I have to fix everything again when I put the child theme back.
We need to remove 90% of unysson extensions that do not serve us
Thank you for solving this problem
Regards
