### ISSUE TITLE
Not displaying images

### ISSUE THREAD

**Issue by obertscloud** [ThemeFuse/Unyson#3138]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.
Not sure how to describe but the home front page with all images are not displaying images, any more, deactivated all plugins, re-copied wordpress and the theme back 
http://www.gayweddingsspain.com/
Last time this happened we switched to lower than php7 and it worked.  but then over time it starts this strange behavior again

**Comment by ViorelEremia** [comment]
Unyson is tested with php7, if you dezactivate unyson what is happening?

**Comment by obertscloud** [comment]
i deactivated, well then there is no content because content relies on it, if i delete and reinstall plugin same problem.

**Comment by obertscloud** [comment]
i made a test page,  with the page builder elements

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by obertscloud** [comment]
Ok I am sending you an email with instructions and what the home page post is,  interestingly,  
when i start from scratch recreating a new post which is a lot of work to get the design like it is, the images show up, which leads me to believe something in the post is corrupted. Had this issue before the theme developer logged in and tried fix it, last July but I do know what he did to fix it, it is something that reoccurred more than once.

**Comment by ViorelEremia** [comment]
I don't know why your images are loaded externally. If you inspect browser console you can see that the browser is trying to load images from another server not yours ```http://paradiseeventproductions.com/```
In your admin also these urls are are hardcoded for exemple see image below.
![edit page gay weddings spain lgbtiq paradise event productions wordpress](https://user-images.githubusercontent.com/28967378/35430803-869ad14e-0282-11e8-9d0c-e5829164cf70.png)
If you try to edit the image you will see that it does not exist on your sever.
Also I tryied to deactivate unyson from your server and the issue is stiil persist. I think is a external server isssue, please contact your theme provider it isn't a plugin issue.

**Comment by obertscloud** [comment]
Sure some of the images are external to our mother website.  I have been slowing changing them to this server.  But even when I change them to our server, the problem exists. Let me try another idea I get back to you.  I am redoing the page, manually and it is having some problems.  But I think the media manager has the wrong links.  I don't know how that happened.  I will try something else and get back to you, thank you for your help.

**Comment by ViorelEremia** [comment]
If images exists on server "mother website" and urls on child server are correct to mother server then mother can block directly request by .htaccess or server configurations.

**Comment by obertscloud** [comment]
ok  so how can i bulk search and replace those external links, i tried a plugin but it is not changing in your custom field

**Comment by obertscloud** [comment]
ok i see this  "url":"\/\/paradiseeventproductions.com\/gay\/wp-content\/uploads\/2017\/02\/486254-01-02.jpg"}
i want to replace it to gayweddingsspain.com\ exclude the subdirectory /gay  
i am trying a test but i dont know if i have it right

**Comment by ViorelEremia** [comment]
Test it before to go in production site run it to phpmyadmin:
```
update wp_posts set post_content = replace(post_content, 'oldUrl', 'newUrl');
update wp_postmeta set meta_value = replace(meta_value, 'oldUrl', 'newUrl');
```

**Comment by obertscloud** [comment]
ok thanks

**Comment by obertscloud** [comment]
that did not work, in your custom field is still the wrong urls

**Comment by ViorelEremia** [comment]
Should work i tested in my end and it is woking

**Comment by ViorelEremia** [comment]
Show me some code that you tried

**Comment by obertscloud** [comment]
i am manually replacing photos, but some of the photos are on our server, not the remote server but do not work, when i replace the photos with the same photo manually they appear, it has to be a bug

**Comment by obertscloud** [comment]
ok  this custom field  fw:opt:ext:pb:page-builder:json, has a lot of code in it, even though I change the photo manually through the elements , this custom code is not changing , you will still see some not from our server  for example  `{"name":"Wedding in Spain","weddingvero_ceremonies_image":{"attachment_id":"1084","url":"\/\/paradiseeventproductions.com\/gay\/wp-content\/uploads\/2017\/02\/LGBT-Civil-Union-Photo-4.jpg"}`

**Comment by obertscloud** [comment]
why this was closed, I opened another issue about this
