### ISSUE TITLE
Breadcrumbs extension bugs

### ISSUE THREAD

**Issue by dameer** [ThemeFuse/Unyson#314]
bug #1 : when page not found (404 error)
" Undefined index: REQUEST_SCHEME in /blah/blah/plugins/unyson/framework/extensions/breadcrumbs/includes/class-breadcrumbs-builder.php on line 110 "

bug #2 : is_date() case
*Year* will always be returned regardless the date/month selected (for instance from Calendar widget)

Just a thought: implementation if Justin Tadlock's breadcrumb-trail class ( https://github.com/justintadlock/breadcrumb-trail ) might bring a whole bunch of improvements

**Comment by GheorgheP** [comment]
Hi,
Sorry for big delay,

Bug 1 was solved in this commit: https://github.com/ThemeFuse/Unyson-Breadcrumbs-Extension/commit/60b47d1784c6f01c381d896404f5e81c7c4e4494

About the second, could you provide more info, with a screen if it is possible?

**Comment by dameer** [comment]
Thanks for resolving #1.

As for the second one... OK, just put an Archive widget in (any) sidebar and then the Calendar widget too. Get back to frontend, select monthly archive first and watch what's been rendered in breadcrumbs. Now select any date containing posts from Calendar and watch the breadcrumbs. In both cases only the year will be shown. Hope it does make sense, I doubt any screenshot helps in this case.
