### ISSUE TITLE
fw_ext_sidebars_current_position_get() not working

### ISSUE THREAD

**Issue by hammadmunir** [ThemeFuse/Unyson#3140]
Fatal error: Uncaught Error: Call to undefined function fw_ext_sidebars_current_position_get() in

**Comment by ViorelEremia** [comment]
```Call to undefined function fw_ext_sidebars_current_position_get() in``` where in?
Unyson dosen't have that function check where it is called.

**Comment by hammadmunir** [comment]
// file: sidebar-content.php

<?php if (!defined('FW')) die('Forbidden');

$current_position = fw_ext_sidebars_current_position_get();

if ($current_position !== 'position-id') {
    echo fw_ext_sidebars_show('green');
}

if ($current_position === 'position-id-2') {
    echo fw_ext_sidebars_show('blue');
}

if ($current_position === 'position-id-3') {
    echo fw_ext_sidebars_show('yellow');
}

[Ref. Link](http://manual.unyson.io/en/latest/extension/sidebars/index.html#configuration)

**Comment by ViorelEremia** [comment]
It is wrong name function use ```fw_ext_sidebars_get_current_position```

**Comment by hammadmunir** [comment]
yeah but it's written on docs. thats why i was asking.

**Comment by hammadmunir** [comment]
btw thanks.
