### ISSUE TITLE
Builder 2 fw_options[random-2]

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3141]
Bug 

![screenshot_1](https://user-images.githubusercontent.com/2340172/35333246-50f0b786-010e-11e8-8a6a-c3332aa2c6a0.jpg)

first instance 

![screenshot_2](https://user-images.githubusercontent.com/2340172/35333300-8af2f78c-010e-11e8-9374-f51dd0f795a4.jpg)

second instance is in contact form 

![screenshot_4](https://user-images.githubusercontent.com/2340172/35333350-b422b08e-010e-11e8-8d74-1c162dca9d18.jpg)

**Comment by andreiglingeanu** [comment]
@danyj Please try this: https://github.com/ThemeFuse/Unyson-Builder-Extension/pull/26

**Comment by danyj** [comment]
that fixes it , but I would add a prefix ,  

`'builder-'. fw_rand_md5() => array(`

**Comment by danyj** [comment]
or this is better 
`'thumbnails-'. fw_rand_md5()`

**Comment by andreiglingeanu** [comment]
Why would you need it?

**Comment by danyj** [comment]
> Why would you need it

just as dev reference , 

> This is never read

we just did :)
