### ISSUE TITLE
Cannot Install Demo Content

### ISSUE THREAD

**Issue by dpattison** [ThemeFuse/Unyson#3142]
We get the following error when trying to install any of the demo content. I added the extra error detail based on info in another post.

Failed to create tmp table _fwbk_wp_fw_termmeta | wpdb->last_error: Got error 1 from storage engine | SQL: CREATE TABLE `_fwbk_wp_fw_termmeta` ( `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `fw_term_id` bigint(20) unsigned NOT NULL DEFAULT '0', `meta_key` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `meta_value` longtext COLLATE utf8_unicode_ci, PRIMARY KEY (`meta_id`), KEY `fw_term_id` (`fw_term_id`), KEY `meta_key` (`meta_key`(250))) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**Comment by ViorelEremia** [comment]
Can you test with that commit: https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/2da0013a549770da584bbd03de20e44011e6161f

**Comment by dpattison** [comment]
Hello, I updated with the new file and am now getting: 

Failed to create tmp table _fwbk_wp_commentmeta. Got error 1 from storage engine

**Comment by dpattison** [comment]
Detailed error:

Failed to create tmp table _fwbk_wp_commentmeta | wpdb->last_error: Got error 1 from storage engine | SQL: CREATE TABLE `_fwbk_wp_commentmeta` ( `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `comment_id` bigint(20) unsigned NOT NULL DEFAULT '0', `meta_key` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `meta_value` longtext COLLATE utf8_unicode_ci, PRIMARY KEY (`meta_id`), KEY `comment_id` (`comment_id`), KEY `meta_key` (`meta_key`(191))) ENGINE=MyISAM AUTO_INCREMENT=114 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by dpattison** [comment]
ftp://waws-prod-mwh-009.ftp.azurewebsites.windows.net
davedeploy
mission21

www.smartbuytk.com/wp-admin
viorel@themefuse.com
p2vrcMZg52cIyYUL38w1V0eA

Dave Pattison │ Director, Information Technology
Office: (805) 691-2590
717 EAST YANONALI ST │ SANTA BARBARA, CA 93103 │ www.missionlinen.com<http://www.missionlinen.com/>


[cid:image002.png@01D1A79F.3BBBFF30]<http://www.missionlinen.com/>

[cid:image004.png@01D1A79F.3BBBFF30]

[cid:image006.png@01D1A79F.3BBBFF30]<https://www.facebook.com/missionlinen1>[cid:image008.png@01D1A79F.3BBBFF30]<https://twitter.com/Mission_Linen>[cid:image010.png@01D1A79F.3BBBFF30]<https://plus.google.com/+MissionLinenSupply>[cid:image012.png@01D1A79F.3BBBFF30]<https://www.linkedin.com/company/mission-linen-supply>[cid:image014.png@01D1A79F.3BBBFF30]<https://www.youtube.com/c/MissionLinenSupply>

**Comment by ViorelEremia** [comment]
Can you contact your hosting support with the error below, you can see it [here](http://www.smartbuytk.com/wp-admin/tools.php?page=fw-backups-demo-content) as admin notice and your ftp is not working I tried through several programs.
```
HTTP Loopback Connections are not enabled on this server. 
If you need to contact your web host, tell them that when PHP tries to connect back to 
the site at the URL`http://www.smartbuytk.com/wp-admin/admin-ajax.php` 
and it gets the error 
`cURL error 28: Operation timed out after 2016 milliseconds with 0 bytes received`. 
There may be a problem with the server configuration (eg local DNS problems, mod_security, etc)
 preventing connections from working properly.
```

**Comment by dpattison** [comment]
Hello, the ftp login I sent is not correct. The correct login is ‘smartbuytk\davedeploy’.

I don’t believe the error about the http loopback is causing this issue.

Dave Pattison │ Director, Information Technology
Office: (805) 691-2590
717 EAST YANONALI ST │ SANTA BARBARA, CA 93103 │ www.missionlinen.com<http://www.missionlinen.com/>


[cid:image002.png@01D1A79F.3BBBFF30]<http://www.missionlinen.com/>

[cid:image004.png@01D1A79F.3BBBFF30]

[cid:image006.png@01D1A79F.3BBBFF30]<https://www.facebook.com/missionlinen1>[cid:image008.png@01D1A79F.3BBBFF30]<https://twitter.com/Mission_Linen>[cid:image010.png@01D1A79F.3BBBFF30]<https://plus.google.com/+MissionLinenSupply>[cid:image012.png@01D1A79F.3BBBFF30]<https://www.linkedin.com/company/mission-linen-supply>[cid:image014.png@01D1A79F.3BBBFF30]<https://www.youtube.com/c/MissionLinenSupply>

**Comment by ViorelEremia** [comment]
I'll check in the morning in my country it is late night

**Comment by ViorelEremia** [comment]
I try to connect to your server and it rejects me and I can not log in to your admin

**Comment by dpattison** [comment]
Hello, I sent new credentials in a separate email.

Dave Pattison │ Director, Information Technology
Office: (805) 691-2590
717 EAST YANONALI ST │ SANTA BARBARA, CA 93103 │ www.missionlinen.com<http://www.missionlinen.com/>


[cid:image002.png@01D1A79F.3BBBFF30]<http://www.missionlinen.com/>

[cid:image004.png@01D1A79F.3BBBFF30]

[cid:image006.png@01D1A79F.3BBBFF30]<https://www.facebook.com/missionlinen1>[cid:image008.png@01D1A79F.3BBBFF30]<https://twitter.com/Mission_Linen>[cid:image010.png@01D1A79F.3BBBFF30]<https://plus.google.com/+MissionLinenSupply>[cid:image012.png@01D1A79F.3BBBFF30]<https://www.linkedin.com/company/mission-linen-supply>[cid:image014.png@01D1A79F.3BBBFF30]<https://www.youtube.com/c/MissionLinenSupply>

**Comment by danyj** [comment]
@dpattison stop including email reply's please , you are exposing to much info here , this is public git

**Comment by ViorelEremia** [comment]
@dpattison it's done

**Comment by jorgeherrera9103** [comment]
# Failed to create tmp table 

Hi, I have an issue when I try to import the demo content.

- - - - - - - 
Failed to create tmp table _fwbk_wp_rg_form_meta. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'longtext COLLATE utf8mb4_general_ci `confirmations` longtext COLLATE utf8mb4_ge' at line 4
- - - - - - -

Thanks for you help!

**Comment by ViorelEremia** [comment]
@jorgeherrera9103 see the: https://github.com/ThemeFuse/Unyson/issues/3491#issuecomment-402465577
