### ISSUE TITLE
Colossal Theme - Sample Data

### ISSUE THREAD

**Issue by JBRusnack** [ThemeFuse/Unyson#3143]
I've contacted my hosting provider, Flywheel, to increase the memory limit to 300s. Now when I go to import the sample data this error shows up: Invalid source dir: /www/wp-content/uploads/fw-backup/tmp/f

Please help! 
:)

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by JBRusnack** [comment]
Thank you! This is the documentation I'm trying to follow: http://colossal1.cactusthemes.com/doc/docs/installation/import-sample-data-one-click-install/

**Comment by ViorelEremia** [comment]
Importing on your site is implemented with another plugin not with unyson, please contact the author of your theme(you have many errors on your site that come from that plugin
![cactus welcome page ridgeline medical supply wordpress](https://user-images.githubusercontent.com/28967378/35404822-e391110e-020c-11e8-94b0-3c654ab16a6f.png)
).

**Comment by JBRusnack** [comment]
Thank you!!
