### ISSUE TITLE
Unyson Images only offer up http URL, not https

### ISSUE THREAD

**Issue by TonySchwartz1028** [ThemeFuse/Unyson#3147]
My site uses https

Here is a page where I use the Images media element within Unyson: https://tonyschwartzmcdj.com/services/

Despite the fact my images are all coming from Amazon S3 and are served with https, Unyson rewrites the URL to to https.

Thus, my site isn't secure for certain pages.

How do I fix this?

<img width="1591" alt="screen shot 2018-01-26 at 12 23 49 pm" src="https://user-images.githubusercontent.com/35851079/35459136-d20a5224-0293-11e8-9298-277a88fadd6f.png">

**Comment by danyj** [comment]
contact your theme provider , they created the shortcode for it
