### ISSUE TITLE
Divider line weight missing

### ISSUE THREAD

**Issue by donorsi** [ThemeFuse/Unyson#3148]
There seems to be some missing parameters from Divider screen. There is no way to set a line thickness (as shown [in the docs](http://docs.themefuse.com/the-core/your-theme/shortcodes/divider-1), so divider never shows up.

![capture](https://user-images.githubusercontent.com/2372727/35461288-e4223d58-02ef-11e8-8afe-200d76166212.JPG)

**Comment by ViorelEremia** [comment]
It's a theme issue, please contact the [theme author](https://support.themefuse.com/hc/en-us/requests/new).
Unyson is a plugin that allows theme authors to create fast and easy WordPress themes. Some of the issues come from themes.
