### ISSUE TITLE
Shortcode settings not saved when wp_editor used  inside metabox

### ISSUE THREAD

**Issue by dameer** [ThemeFuse/Unyson#315]
Case scenario:
Create page options (page-options.php) under "framework-customizations/theme/options" and throw in wp-editor, like so:
```
if ( ! defined( 'FW' ) ) die( 'Forbidden' );
$options = array(
	'page_banner' => array(
		'type'    => 'group',
		'options' => array(
			'page_banner_text' => array(
				'label' => __( 'Text', 'unyson' ),
				'type'  => 'wp-editor',
				'value' => '',
				'desc'  => __( 'Enter text', 'unyson' ),
			),
		),
	),
);
```
Default Unyson shortodes are available for use with wp_editor so try to insert any available. Save/Publish Page and go check inserted shortcode settings. It's back to defaults.

**Comment by sergiubagrin** [comment]
Can you give me more details? I don't understand what you mean Also add some screenshots.  Thanks

**Comment by dameer** [comment]
Here's an example ( http://goo.gl/qsvH5H ) ! Just try to get the value of "page_banner_text" option in "page.php" template. As I recall it should be : 
fw_get_db_post_option( get_the_ID(), 'page_banner_text' );

**Comment by GheorgheP** [comment]
Hi,

I just tested with your attachment, all works properly, make sure that you call `get_the_ID` in [The Loop](https://codex.wordpress.org/The_Loop)
