### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by elarion83** [ThemeFuse/Unyson#3150]
Hi,

I've updated unyson and I can't log with my admin credentials. Website tell me that the user is not found.

Please help asap this is important.

**Comment by ViorelEremia** [comment]
Here is not the unyson involved we do not affect anything that is related to the users.
If you have ftp credentials run this code on your server
```
 wp_insert_user( array(
    'user_login'   =>  'new_user_login',
    'user_pass'   =>  'your_new_password',
    'role'             => 'administrator'
) ) ;
```

**Comment by elarion83** [comment]
Hi,


I don't wan't to create an account by ftp<ftp://ftp>.. I wan't to be able to log in.


When unyson is active I can't log in. When unyson is deactivate I can log in so Unyson is invovled in this issue.


________________________________
De : ViorelEremia <notifications@github.com>
Envoyé : samedi 27 janvier 2018 12:44
À : ThemeFuse/Unyson
Cc : elarion83; Author
Objet : Re: [ThemeFuse/Unyson] Can't log in (#3150)


Here is not the unyson involved we do not affect anything that is related to the users.
If you have ftp credentials run this code on your server

 wp_insert_user( array(
    'user_login'   =>  'new_user_login',
    'user_pass'   =>  'your_new_password',
    'role'             => 'administrator'
) ) ;

**Comment by elarion83** [comment]
What's going on ? Why is this issue marked as closed ?

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by ViorelEremia** [comment]
why do you have two plugins?
![screenshot from 2017-12-26 23-01-07](https://user-images.githubusercontent.com/28967378/35472022-fbc5f848-036f-11e8-86a3-4ee9d0603b2a.png)

**Comment by elarion83** [comment]
Got one since the start and thesecond since yesterday , since the problem shows up

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by elarion83** [comment]
Normally I don't have two plugins, It was just for debugging since yesterday :)

________________________________
De : ViorelEremia <notifications@github.com>
Envoyé : samedi 27 janvier 2018 13:40
À : ThemeFuse/Unyson
Cc : elarion83; Author
Objet : Re: [ThemeFuse/Unyson] Can't log in (#3150)


why do you have two plugins?
[screenshot from 2017-12-26 23-01-07]<https://user-images.githubusercontent.com/28967378/35472022-fbc5f848-036f-11e8-86a3-4ee9d0603b2a.png>

[https://user-images.githubusercontent.com/28967378/35472022-fbc5f848-036f-11e8-86a3-4ee9d0603b2a.png]

**Comment by ViorelEremia** [comment]
I can't find what is going on, if i disable all of these custom extensions from unyson extensions page your data will be lost?
I think this is because of one of them

**Comment by elarion83** [comment]
I don't know if my data will be lost, you think this come from an extension of unyson ? Maybe this come from the multiple unyson ?


________________________________
De : ViorelEremia <notifications@github.com>
Envoyé : samedi 27 janvier 2018 14:20
À : ThemeFuse/Unyson
Cc : elarion83; Author
Objet : Re: [ThemeFuse/Unyson] Can't log in (#3150)


I can't find what is going on, if i disable all of these custom extensions from unyson extensions page your data will be lost?
I think this is because of one of them

**Comment by elarion83** [comment]
Hey WHAT DID YOU DO TO MY SITE ?!!!


________________________________
De : ViorelEremia <notifications@github.com>
Envoyé : samedi 27 janvier 2018 14:20
À : ThemeFuse/Unyson
Cc : elarion83; Author
Objet : Re: [ThemeFuse/Unyson] Can't log in (#3150)


I can't find what is going on, if i disable all of these custom extensions from unyson extensions page your data will be lost?
I think this is because of one of them

**Comment by ViorelEremia** [comment]
I did not touch your site I just checked the plugins you installed, theme, extensions and the theme you are using and nothing more, that's what I checked Saturday on 9 o'clock UTC/GMT +2 hours. If you think that I broke your site you have to inspect yourself the issue. You should ask the theme/extensions developer if he did not add some functionality on login wp hooks when Unyson is enabled. You use simple membership plugin to create the page with log in which I have also installed on a local host for testing. When i try to log in via page "Member Login" it does not allow me although unyson isn't installed.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
