### ISSUE TITLE
How to get the output of the icon v2.

### ISSUE THREAD

**Issue by Kraantje85** [ThemeFuse/Unyson#3152]
I can't get icon v2 on the frontend working! I have it working on the backend but when you select a icon and save it i get only the output 'Array' back, what do it wrong?

view.php
```
<div class="fw-iconbox-image">
	<i class="<?php echo esc_attr($atts['icon']); ?>"></i>
</div>
```
i also tryed `<?php echo esc_attr($atts['icon']['icon-font']); ?>` but that wont work also...

options.php
```
$options = array(
	'icon'    => array(
		'type'  => 'icon-v2',
		'preview_size' => 'medium',
		'label' => __('Choose an Icon', 'fw'),
	),
);
```

Thanks for helping.

**Comment by andreiglingeanu** [comment]
At first, please do a `fw_print(fw_akg('icon', $atts))`, just so you can see what's the data structure you're dealing with. It is a bit more complicated just to allow advanced use cases for icons, for the ones who need it.

Most of the times your output will look like that:

```php
<?php

$icon = fw_akg('icon', $atts);
$icon_class = '';

if (fw_akg('type', $icon) === 'icon-font') {
  $icon_class = fw_akg('icon-class', $icon);
}

if (fw_akg('type', $icon) === 'custom-upload') {
  // you may want to handle the case of custom upload here,
  // by accessing url of the uploaded image
}
?>

<div class="fw-iconbox-image">
	<i class="<?php echo esc_attr($icon_class); ?>"></i>
</div>
```

Also, make sure to put this snippet of code in your `functions.php`, in order to load icon packs CSS files.

```php
fw()->backend->option_type('icon-v2')->packs_loader->enqueue_frontend_css();
```

**Comment by stivoox** [comment]
@andreiglingeanu But when we put this in function.php : 
fw()->backend->option_type('icon-v2')->packs_loader->enqueue_frontend_css();
this error appear : Fatal error: Call to undefined function fw()

**Comment by kevmul** [comment]
@stivoox Were you able to figure this out? I am currently looking for the answer to this too.

**Comment by andreiglingeanu** [comment]
@stivoox @kevmul This probably happens because Unyson is not activated on your side.

Try that:


```php
if (function_exists('fw') {
  fw()->backend->option_type('icon-v2')->packs_loader->enqueue_frontend_css();
}
```

**Comment by kevmul** [comment]
Thank you @andreiglingeanu. I will definitely be leveraging that code.

I am creating a child theme from a Unyson theme and I just found what I wanted. That was `add_action( 'after_setup_theme', 'function_that_uses_fw())` This will trigger after the theme sets up and I would have access to the `fw()` function.
