### ISSUE TITLE
Warnings showing up on website

### ISSUE THREAD

**Issue by befree920** [ThemeFuse/Unyson#3153]
The following warning shows up at the top of my website (idylwoodgrill.com) and at the top of my WP backend editor. When I disabled Unyson, the warning text went away, but the website's features also went away. Please help!

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /home/content/93/11718193/html/wp-content/plugins/unyson/framework/includes/hooks.php:256) in /home/content/93/11718193/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 256

Warning: Unknown: open(/home/content/93/11718193/tmp/sess_f0ltsu6tgpil5oaivk4fkseag0, O_RDWR) failed: No such file or directory (2) in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on line 0

**Comment by danyj** [comment]
Contact your host and send them this 
https://stackoverflow.com/a/3262756/594423
