### ISSUE TITLE
Form builder issue: Messsage sent! Could not send the email

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#3154]
@ViorelEremia I am facing issue with Unyson form builder. I saw the last update of the mailer and still that not fixed.

## _Mail send but we still get an error message. Message sent! Could not send the email_

![aa](https://dha4w82d62smt.cloudfront.net/items/3A0P231b0f152Z0e2a3U/%5B60850f8b3c3e236f38c63a10c2e78d07%5D_Screen%2520Shot%25202018-01-29%2520at%252011.40.43%2520AM.png)

### _I have tried to override this error message from admin but still showing same error sent notice._

![aa](https://dha4w82d62smt.cloudfront.net/items/2m210f3v1J1e2L171X3z/Screen%20Shot%202018-01-29%20at%2011.43.28%20AM.png)

Can you please look into this issue.

Thanks

**Comment by ViorelEremia** [comment]
I can not reproduce this issue can you give me more details?
