### ISSUE TITLE
Using Duplicator for Staging Site

### ISSUE THREAD

**Issue by obertscloud** [ThemeFuse/Unyson#3155]
I am using duplicator for staging to live, but for some reason, the code in your custom field that is generated from updating elements is not getting searched and replaced properly.  This use to work fine, but now it does not. (mostly the paths to the images, or icons)
1) is there an option now i need in duplicator ?
2) or do you recommend other backup restore plugin?

**Comment by obertscloud** [comment]
attachments which the problem here.. show this
:{“attachment_id”:”2407″,”url”:”\/\/gayweddingsspain.com\/gaytesting\/wp-content\/uploads\/2018\/01\/gay-marriage-wedding-vows-100815-02-1.jpg”},
so your normal search and replace  via duplicator does get the \/\/ 
I think this is true for any staging, duplication, migration, backup database plugin
I don't know why the authors of Unyson have done this

**Comment by steve-themefuse** [comment]
Try the backup tool from Unyson: https://themefuse.com/how-to-move-your-wordpress-site-manually/#unyson_backup_option.

**Comment by obertscloud** [comment]
I appreciate that but it is to complex, we have 50 websites using Unyson themes and from staging to testing to live,  everyday..  if it was more streamlined like Duplicator then it would be no problem.    Can you not work with them ?  or streamline your backup tool ?
