### ISSUE TITLE
typography-v2 in customizer 

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#3156]
I have tried to use typography-v2 in customizer but its not working.

last couple of field showing invalid option 

![aa](https://dha4w82d62smt.cloudfront.net/items/2b0e2i0F2a1d1U370P0T/Image%202018-01-29%20at%203.39.57%20PM.png?X-CloudApp-Visitor-Id=170646faeef5ffa7fc1efbce81290e56)

I didn't change anything just copy the options field from unyson docs.

**Comment by Ataurr** [comment]
Also Addobale popup add remove given invalud value error.

![add](https://dha4w82d62smt.cloudfront.net/items/0P1V2z1O1W3G1n0H2d3e/Screen%20Shot%202018-01-29%20at%204.38.56%20PM.png?X-CloudApp-Visitor-Id=1674463&v=36f721a1)

**Comment by ViorelEremia** [comment]
I tested and everything is working well.
![customize wp just another wordpress site](https://user-images.githubusercontent.com/28967378/37644541-d38c1f98-2c2c-11e8-80db-c1a7724b6988.png)
