### ISSUE TITLE
Theme Settings in wrong capability?

### ISSUE THREAD

**Issue by kevinbrands** [ThemeFuse/Unyson#3157]
Hello,

I only want to make the Theme Settings available for certain user roles. When looking at the standard capabilities available, there is one called 'Edit Theme Options'. This would be great (and logical) for the Theme Settings.

But: this capability doesn't work with your Theme Settings. When looking further, I noticed that the capability 'Manage Options' does show/hide the Theme Settings upon granting/denying.

Are the theme settings matched with the wrong capability? Or is this as designed?

Is there another way to make the Theme Settings available/not available to certain user roles?

Thanks in advance!
-Kevin

**Comment by ViorelEremia** [comment]
I tested with scratch theme and i don't see any issues:
```
function test_theme_caps() {
	$role = get_role( 'editor' );
	$role->add_cap( 'manage_options' );
}
add_action( 'admin_init', 'test_theme_caps');
```
I addet to role editor capabillity to manage options so he can to activate/deactivate extensions and change theme options.
But some plugins allow to do some things that you don't want to allow editors if you have those plugins installed so here you need to do very carefully and i don't understand why you need that.

**Comment by kevinbrands** [comment]
What I was wondering, is why these things are assigned to the 'manage_options' capability, and not to the 'edit_theme_options' capability. That capability would be more logical to use..

If I grant the 'manage_options' capability to a user or a userrole, then too much other stuff will be available to change. That's not what I want.

**Comment by kevinbrands** [comment]
I've managed to find a workaround: I enable the 'manage_options' capability and make a few custom capabilities to achieve what I want. Thanks anyway!

-Kevin
