### ISSUE TITLE
Padding & Margin

### ISSUE THREAD

**Issue by deepakweb2** [ThemeFuse/Unyson#3158]
i can't see any where padding & margin setting in page builder like(sections, rows, cols, elements ets).. is there any solution for that asap.... and also missing the feature for background images size, positions etc.. please give me a possible solution... or any code ref. which help me..

**Comment by ViorelEremia** [comment]
Honestly I do not understand you. You want to build a theme with unyson and you don't know how to start?
Or you have a theme what doesen't have those features?
Are you a developer?
Or your theme has a bug?

**Comment by deepakweb2** [comment]
i am a beginner theme developer... i am using a unyson framefork in my theme.. but it does't have a padding & margin features in page builder.. can you please guide me how to get or create this feature in page builder..  
![divi-row-module-equalize-column-heights](https://user-images.githubusercontent.com/34815378/35632260-2c2336fe-06cc-11e8-9325-938da9acf588.jpg)

**Comment by ViorelEremia** [comment]
This code add for all shortcodes a new tab with options but you can filter them by var $shortcode if you want not for all shortcodes:
```
function test_add_options( $options, $shortcode ) {

	$options = array(
		'default_options' => array(
			'type' => 'tab',
			'options' => $options,
			'title' => __('Tab Title', '{domain}'),
			'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
		),
		'tab_id' => array(
			'type' => 'tab',
			'options' => array(
				'option_id'  => array( 'type' => 'text' ),
			),
			'title' => __('Tab Title', '{domain}'),
			'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
		)
	);

	return $options;
}

add_action( 'fw_shortcode_get_options', 'test_add_options', 10, 2 );
```

**Comment by danyj** [comment]
> This code add

**Comment by danyj** [comment]
@ViorelEremia thank much for this info but
why is this not in any docs?  http://manual.unyson.io/en/latest/search.html?q=fw_shortcode_get_options

we coded our ... off for 50 shortcodes where now I see could have been done much easier

**Comment by deepakweb2** [comment]
i m getting an error "Undefined option type: tab

"
