### ISSUE TITLE
I updated "core" theme of themefuse and now unyson expired

### ISSUE THREAD

**Issue by xMattiax** [ThemeFuse/Unyson#3159]
Hi, on my website barberluxury.it I used unyson to create my pages, and now they expired because I can't see unyson in page editor anymore after update.
How can I solve this bug?

**Comment by xMattiax** [comment]
I tried to reinstall theme, and other things like these... I don't want to lose my pages.. Pls help..

**Comment by ViorelEremia** [comment]
did you try to update the extensions?

**Comment by xMattiax** [comment]
Yes, I tried..

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by xMattiax** [comment]
Sent now.. thanks, dude.

**Comment by xMattiax** [comment]
Alert me when you are working on and I stop trying solutions.

**Comment by ViorelEremia** [comment]
If you see in edit page admin editor like that:
![edit page wp wordpress](https://user-images.githubusercontent.com/28967378/35612721-7141d2f4-0672-11e8-9306-59369e27da8d.png)
When go to your admin dashboard -> Users -> Your Profile and if your option "Disable the visual editor when writing" is checked then uncheck it and click "Update Profile". 
If it is unchecked then check it and save the profile after that again uncheck it and save profile again, that is something like trigger value option.

**Comment by xMattiax** [comment]
Ok really thanks bro.
Bye.

Mattia Palmitesta.
________________________________
