### ISSUE TITLE
Portfolio doesn't work

### ISSUE THREAD

**Issue by bogdanzurac** [ThemeFuse/Unyson#316]
After creating 2 projects, when accessing each project page, I get "Oops! That page can’t be found."
Also, where the hell is the option to view *all* projects on a single page ?

Furthermore, when trying to install your own theme, the WP installer complains that there is no style.css inside the .zip file.

Quite a failure, nothing seems to work.

**Comment by sergiubagrin** [comment]
> After creating 2 projects, when accessing each project page, I get "Oops! That page can’t be found."

It is working fine for me: http://screencast.com/t/3J7I70vbGx9p We tested a lot of time this extensions and it was working fine. Can you try to install Unyson Plugin on a new Wordpress Install or try to disable all plugins. Can you give more details (OS, PHP, Apache version), errors logs?

> Also, where the hell is the option to view all projects on a single page ?

Yes. It is needed to create a category exactly like on a standart wordpress Blog section 

> Furthermore, when trying to install your own theme, the WP installer complains that there is no style.css inside the .zip file.

I tested Our scratch theme and all is working fine. style.css is missing is a very common issue please check this posts: 

https://support.truethemes.net/?faq=theme-install-failed-the-theme-is-missing-the-style-css-stylesheet

http://www.kriesi.at/support/topic/just-downlaod-habitatthe-theme-is-missing-the-style-css-stylesheet/

So all is working fine, check again :)
