### ISSUE TITLE
Undefined option type: - what do i wrong?

### ISSUE THREAD

**Issue by Kraantje85** [ThemeFuse/Unyson#3160]
Hello, 

I am trying to make a new '[type](https://github.com/ThemeFuse/Unyson-Documentation/blob/master/options/create-option-type.rst)' I using the same directory structure and still i getting the message 'Undefined option type: number' so what do i wrong?

theme-name/inc/hooks.php
```
<?php
	function _action_theme_include_custom_option_types() {
		require_once dirname(__FILE__) .'/includes/option-types/number/class-fw-option-type-number.php';
	}
	add_action('fw_option_types_init', '_action_theme_include_custom_option_types');
?>
```
And in `theme-name/inc/includes/option-types/number/class-fw-option-type-number.php` i have standing all the code for the new type but i still getting the undefined message.

**Comment by danyj** [comment]
did you include it 
http://manual.unyson.io/en/latest/options/create-option-type.html#content

is your type set 

http://prntscr.com/i84uxo

**Comment by Kraantje85** [comment]
@danyj 

```
class FW_Option_Type_Number extends FW_Option_Type {
	public function get_type() {
		return 'number';
	}
}
FW_Option_Type::register('FW_Option_Type_Number');
```

This is good right?

**Comment by danyj** [comment]
> This is good right?

yes , is the file included
http://prntscr.com/i84x9c

**Comment by danyj** [comment]
do `fw_print('hi') `on top of the file to make sure is there

**Comment by Kraantje85** [comment]
@danyj 
I putted fw_print('hi'); inside of the class file and get no output so i think something is going wrong in the hooks.php file?

```
<?php
	function _action_theme_include_custom_option_types() {
		require_once dirname(__FILE__) .'/includes/option-types/number/class-fw-option-type-number.php';
	}
	add_action('fw_option_types_init', '_action_theme_include_custom_option_types');
?>
```

But this is the path to the file? (copied from filezilla: `/inc/includes/option-types/number/class-fw-option-type-number.php`

**Comment by danyj** [comment]
I never used that hook , instead I have option-types.php http://prntscr.com/i8513d 

 here

https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-parent/inc/includes

and file s is included in init.php

https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/inc/init.php

**Comment by Kraantje85** [comment]
@danyj 
When i include the [init.php](https://github.com/ThemeFuse/Theme-Includes/blob/master/init.php) i get a HTTP ERROR 500

**Comment by Kraantje85** [comment]
Or when i delete the content of the hook:

```
function _action_theme_include_custom_option_types() {
		require_once dirname(__FILE__) .'/includes/option-types/number/class-fw-option-type-number.php';
	}
	add_action('fw_option_types_init', '_action_theme_include_custom_option_types');
```

The backend is working again then. So there is something wrong in the hooks.php. Because when i delete the class (type) file that i made i get the 500 error still.

**Comment by Kraantje85** [comment]
I deleted all the files and uploaded one by one and now all is working. 

I dont know what it was but it is working :)
