### ISSUE TITLE
Backup   preg_match(): No ending delimiter '|'

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3164]
Updated yesterday , backup is filling the log with 

`PHP Warning:  preg_match(): No ending delimiter '|' found in T:\wamp64\www\Creatus\Clean\wp-content\plugins\unyson\framework\extensions\backups\includes\module\tasks\type\class-fw-ext-backups-task-type-zip.php on line 118`

https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-zip.php#L118

and zip Archiving never ends

**Comment by danyj** [comment]
@ViorelEremia  do this and it will kick it off

```
/**
 * Disable removal of image sizes
 */
function _thz_filter_disable_demo_img_sizes_removal($do, FW_Ext_Backups_Task_Collection $collection ) {

	return false;
}
add_filter('fw:ext:backups:add-backup-task:image-sizes-remove', '_thz_filter_disable_demo_img_sizes_removal', 10, 2);
```

**Comment by danyj** [comment]
2 hours and still going

![backup_pilingup](https://user-images.githubusercontent.com/2340172/35682619-942a39b0-0761-11e8-9698-26c081708845.gif)

**Comment by ViorelEremia** [comment]
You mean i need to to disable removal of image sizes and i can see that error?

**Comment by danyj** [comment]
no I dont think you do , 
this happened yesterday also I just did not see it, 
today I tested remove image sizes and it kicked it. 

try with or without

windows 10
apache 2.4.29
php 7.2

**Comment by danyj** [comment]
can you believe that this is still going 6h later?  1.6GB  error log

**Comment by danyj** [comment]
same bug again written in log 1024 times but
![screenshot_14](https://user-images.githubusercontent.com/2340172/35710433-b804f2ca-07b7-11e8-99e9-2c45c8d5bd0d.jpg)
 zip finished,

**Comment by Ataurr** [comment]
I am also facing the same issue...

**Comment by ViorelEremia** [comment]
can you test? for me everything is fine
and i can't reproduce that but i think it's from eding separator

**Comment by Ataurr** [comment]
If you need I can share you the login details if you want.

**Comment by Ataurr** [comment]
After add **|** in regex this error now showing 
[02-Feb-2018 13:26:41 UTC] PHP Warning:  preg_match(): Unknown modifier 'd' in backups/includes/module/tasks/type/class-fw-ext-backups-task-type-zip.php on line 118

**Comment by danyj** [comment]
testing  fix

**Comment by danyj** [comment]
fix confirmed for normal state , testing now with image sizes remove disabled

**Comment by danyj** [comment]
can this be released please , I have to copy the git install in every demo I make .

**Comment by pnpetroff** [comment]
Some of my clients have the same problem...
