### ISSUE TITLE
Enqueue Static does not work when shortcode is used outside of post content.

### ISSUE THREAD

**Issue by qutub-bharmal** [ThemeFuse/Unyson#3165]
Hello,

I have added a wp editor in page meta to allow add content on the top banner. also I have customised all the shortcode to with adding some extra parameters, like: background color, text color etc.

To manage all this dynamic css I am using hook / action: fw_ext_shortcodes_enqueue_static:SHORTCODE and add style with WordPress "wp_add_inline_style" function.

The dynamic CSS works fine once I am using the shotcode in default visual editor which is embeded with page content editor. but if I use same shortcode in page meta editor.

Can you please check and fix asap.

Thanks.

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/62#issuecomment-233979434

**Comment by qutub-bharmal** [comment]
Thank you.

**Comment by danyj** [comment]
np, close the issue please
