### ISSUE TITLE
Extend Events extension with additional options

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#3166]
Hi guys,

I'm using the events extension, and copied the extension over into my theme /framework-customisations/ and would like to add some additional fields to the events. When I add these to "class-fw-option-type-event.php" within my theme, no additional fields show, if I edit the same file within the plugin my additional fields display.

Could you tell me how to add them in my theme.

Thank you

**Comment by ViorelEremia** [comment]
Try(is not tested):
```
if (!function_exists('test_filter_fw_ext_events_post_options')) :
	/**
	 * Add extra options for post event
	 */
	function test_filter_fw_ext_events_post_options($event_options = array())
	{
		$test_admin_url = admin_url();
		$event_options['events_tab']['options'] = array_merge($event_options['events_tab']['options'],
			array(
				'ticket_group' => array(
					'type' => 'group',
					'options' => array(
						'ticket_price' => array(
							'label' => esc_html__('Ticket Price', 'test'),
							'desc' => esc_html__('Enter the ticket price', 'test'),
							'help' => esc_html__('Event currency options can be found in Theme Settings', 'test'). ' > <a href="' . $test_admin_url . 'themes.php?page=fw-settings#fw-options-tab-posts" target="_blank">' . esc_html__( 'Posts', 'test' ) . '</a>, ' . esc_html__( 'on the Events tab.', 'test' ),
							'type' => 'text',
						),
						'ticket_link' => array(
							'label' => esc_html__('Ticket Link', 'test'),
							'desc' => esc_html__('Enter the ticket link', 'test'),
							'type' => 'text',
						),
						'ticket_number' => array(
							'label' => esc_html__('No. of Available Tickets', 'test'),
							'desc' => esc_html__('Enter the number of available tickets', 'test'),
							'type' => 'text',
						),
					)
				)
			)
		);

		return $event_options;
	}
endif;
add_filter('fw_ext_events_post_options', 'test_filter_fw_ext_events_post_options');
```
Also you can see in class-fw-option-type-event.php filters:
```fw_option_type_event_popup_options:before```
```fw_option_type_event_popup_options:after```

**Comment by danyj** [comment]
in `theme\options\posts`  add file` fw-event.php ` in there add options like this 

https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/theme/options/posts/post.php

**Comment by klvmedia** [comment]
Awesome, thanks so much @ViorelEremia 

What do you use to retrieve the data in the template, I'll usually use -

$options = fw_get_db_post_option($post->ID, fw()->extensions->get( 'events' )->get_event_option_id());

Or

$page = ( function_exists( 'fw_get_db_post_option' ) ) ? fw_get_db_post_option() : '';

$options['link']
$page['link']

Thanks

**Comment by ViorelEremia** [comment]
Use any functions documented: http://manual.unyson.io/en/latest/helpers/php.html#database
