### ISSUE TITLE
Page Builder - All Content Has Disappeared 

### ISSUE THREAD

**Issue by MarkDavidTurner** [ThemeFuse/Unyson#3167]
Hi There,

The content on all my pages aren't showing in the CMS but still displaying on my site.
<img width="1280" alt="screen shot 2018-02-01 at 9 47 45 pm 1" src="https://user-images.githubusercontent.com/11669195/35699757-a8687e86-0799-11e8-8988-1576c38bcc52.png">
I've tried looking online for threads and came across a thread on this issue but it didn't help much on how to solve it. https://github.com/ThemeFuse/Unyson/issues/2945

Any assistance would be highly appreciated 

Thanks

**Comment by ViorelEremia** [comment]
Udate extensions, check browser for errors clear any cache wp plugin or server

**Comment by MarkDavidTurner** [comment]
Hi @ViorelEremia 

I have updated my plugin and checked the browser for any errors and to no avail.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by MarkDavidTurner** [comment]
@ViorelEremia  Emailed you

**Comment by ViorelEremia** [comment]
Fixed: https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
