### ISSUE TITLE
Is there a way to start the box option type closed?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#317]
Is there a specific way , class or anything that we can use to start a 
options container box 
http://manual.unyson.io/en/latest/options/containers.html
closed, not open?

**Comment by sergiubagrin** [comment]
Right now it is not possible.

**Comment by danyj** [comment]
O , thnx , can we added it to wish list please? Something like

	$options = array(
		array(
			'type'    => 'box',
			'options' => array(),
			'attr'    => array('class' => 'start-closed'),
		)
	)

**Comment by sergiubagrin** [comment]
OK . We will think about this.

**Comment by moldcraft** [comment]
@sergiubagrin It's possible

```php
'test' => array(
	'title'   => 'Hello',
	'type'    => 'box',
	'attr'    => array('class' => 'closed'),
	'options' => array(
		'test' => array('type' => 'text'),
	),
),
```

But `attr` will not work for post options because on post edit page [boxes are added using `add_meta_box()`](https://github.com/ThemeFuse/Unyson/blob/b755f909de9064f60a3532d87ac0d34230310381/framework/core/components/backend.php#L532-L544) and there is no way to specify custom attributes in that function.

**Comment by azharijelek** [comment]
I've tried to add 'attr' to add closed class, but it seems the javascript will remove that class once the DOM is ready, or the page has finished loading.

I think this is the script, right?

<pre>
jQuery(function ($) {
		var execTimeoutId = 0;

		fwEvents.on('fw:options:init', function(data){
			// use timeout to be executed after the script from backend-options.js
			clearTimeout(execTimeoutId);
			execTimeoutId = setTimeout(function(){
				// undo not first boxes auto close
				data.$elements.find('.fw-backend-postboxes > .fw-postbox:not(:first-child)').removeClass('closed');
			}, 10);
		});
	});
</pre>

**Comment by gabyferman** [comment]
Did someone find a solution for this?

**Comment by moldcraft** [comment]
@gabyferman By default [only the first box is open](https://github.com/ThemeFuse/Unyson/blob/v2.4.17/framework/static/js/backend-options.js#L101-L106)

Or give me the exact steps to reproduce the problem.

**Comment by danyj** [comment]
@moldcraft   they are all open by default , 

`settings_form_side_tabs true`

	'sidetab1' => array(
		'title'   => __( 'Tab', 'fw' ),
		'type'    => 'tab',
		'options' => array(
			'subbox1' => array(
				'title'   => __( 'Options 1', 'fw' ),
				'type'    => 'box',
				'options' => array(
					fw()->theme->get_options( 'some_set' ),
				),
			),
			'subbox2' => array(
				'title'   => __( 'Option 2', 'fw' ),
				'type'    => 'box',
				'attr'    => array('class' => 'closed'),
				'options' => array(
					fw()->theme->get_options( 'some_set2' ),
				),
			),
		),
	),

**Comment by danyj** [comment]
And see please if you can make this a full toggle (or add an option ) , one tab opens on click, other tabs close , 

Currently we have a layout that overwhelms the user with information so if none of the tabs are closing when user selects specific one, it just to much info at once

**Comment by moldcraft** [comment]
> @danyj they are all open by default

https://github.com/ThemeFuse/Unyson/blob/v2.5.5/framework/views/backend-settings-form.php#L366-L382

**Comment by moldcraft** [comment]
> And see please if you can make this a full toggle (or add an option ) , one tab opens on click, other tabs close ,
> 
> Currently we have a layout that overwhelms the user with information so if none of the tabs are closing when user selects specific one, it just to much info at once

Sorry, I don't quite understand. Please give a screenshot or reformulate.

**Comment by danyj** [comment]
this 
https://jqueryui.com/accordion/
one accordion opens , another closes,  but as an option when you get to it , dont have to force it
