### ISSUE TITLE
Theme Options in multiple language

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#3171]
The content of Theme Options doesn't seem to be ready to be translated in any way. Of course the labels are translatable by using translatable strings, but what about their content? How to add texts for multiple languages?

An example to make this more clear:
We give our customers an option to add some text in the footer. Imagine they want to add some text about their terms and conditions, the text and the link to the PDF is different for every language.

English: "View our terms and conditions"
Germen: "Sehen Sie sich unsere AGB an"
French: "Voir nos termes et conditions"
Dutch: "Zie onze algemene voorwaarden"

Of course another customer could decide to add text about their copyright, so we can't solve this challenge with translation files, because we don't know what text the customer is going to enter. So I imagine every text, textarea and wp-editor needs something like tabs to insert every language.

What are the options to achieve this? Do we currently have a way to do it?

**Comment by ViorelEremia** [comment]
With what translate plugin? This [plugin](https://wordpress.org/plugins/translatepress-multilingual/) we added it as "extension" to extension page list. It is a plugin which allows you to translate strings directly in frontend. So you don't need to create additional fields. If you want to use polylang or wpml you need to add a xml with that db name of your string I do not remember details search for them on their site.

**Comment by warudin** [comment]
This would be with WPML or Polylang, indeed. 

It would be best to be able to manage everything in one place. So editing an XML would not be ideal for our customers.

**Comment by ViorelEremia** [comment]
Your customers will not edit this file, this is the developer of the theme.  
```
<key name="fw_theme_settings_options:the-core">
    <key name="posts_settings">
        <key name="button_options">
            <key name="label" />
        </key>
    </key>
</key>
```
You can see here in that xml that ```fw_theme_settings_options:the-core``` is the key into db with(array) all our options from theme options ```posts_settings``` is the key into that array ```button_options``` is the next key in array with key ```posts_settings``` and ```label``` value will show into translable strings wpml. 
Please read how you can translate your theme via xml on wpml site.
