### ISSUE TITLE
Setting up unyson contact form - please help

### ISSUE THREAD

**Issue by testo88** [ThemeFuse/Unyson#3172]
Hi,
I cant seem to get the contact form to work. When i use the test connection in the configuration box, it sends me a test message successfully to my email. However when I try to use the actual contact form itself, it comes up with "oops something went wrong. Invalid method".  Keep in mind, i've bought this theme and have limited knowledge on coding/networking etc.

I'll be honest, I havent a clue what anything means when setting up this contact form. Can someone please be nice enough to tell me what i need to type in each field for this to work. I included screenshots of the configuration box.
I want the emails to be sent to my gmail account if that helps.

![cintact forum mailer](https://user-images.githubusercontent.com/33804466/35802848-72d86f0c-0abd-11e8-9069-7d0872fbed33.jpg)
![contact form error msg](https://user-images.githubusercontent.com/33804466/35802849-7307b6ae-0abd-11e8-8354-0618094e383a.jpg)
![contact form mailer smtp](https://user-images.githubusercontent.com/33804466/35802850-7337d2f8-0abd-11e8-97f3-21e6036b9ae3.jpg)
![contact forum options](https://user-images.githubusercontent.com/33804466/35802851-7366e336-0abd-11e8-9b50-e5a37a683044.jpg)

**Comment by ViorelEremia** [comment]
It's strange should work, can you send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by testo88** [comment]
I've just sent through login info to your email address. Thanks for helping.
