### ISSUE TITLE
[bug] Over 2000 wp_options from contact form?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3173]
@ViorelEremia 

what is this? I have over 2k of these in DB 

![screenshot_16](https://user-images.githubusercontent.com/2340172/35874108-ed93bebe-0b6b-11e8-8065-d21f5980094f.jpg)

and they seem like from forms

**Comment by danyj** [comment]
crazy

![screenshot_17](https://user-images.githubusercontent.com/2340172/35874257-5683950c-0b6c-11e8-87ed-ef4aee2d441b.jpg)

**Comment by danyj** [comment]
It comes from here 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/extensions/contact-forms/includes/helper/class--fw-ext-contact-form-db-data.php#L13


but why 2K  entries?

**Comment by danyj** [comment]
This is very bad. 

Add  contact form in builder , change options, hit preview few times 

2 DB entries are in 

now save  a third one goes in 

now delete , all 3 stay in DB polluting the DB with thousands of entries

**Comment by danyj** [comment]
@ViorelEremia  can you have look at this please?

**Comment by ViorelEremia** [comment]
Now i can't tommorw morning UTC+02:00

**Comment by ViorelEremia** [comment]
You are right, when the form is deleted field with its data is not removed from table options.
About polluting the DB with thousands of these fields is not happening to me.

**Comment by ViorelEremia** [comment]
I removed all fields with form ```fw:ext:cf:fd:``` from db after that I created a new page with form shortcode clicked multiple times to preview. I also tried to change something in builder, drag, add new shortcode, etc always I used button preview changes

**Comment by ViorelEremia** [comment]
I think your form id is changed, this id is created via unique id input hidden into form settings why it is changed after preview changes i don't know? Maybe you've changed something for that option type? It seems from your db that this id is changed for every form render.

**Comment by danyj** [comment]
> he DB with thousands of these fields is not happening to me.

we are creating demos with 5, 6  contact forms and we use preview to check the look , every time we do so we get min 2 , 3 entries for each. 


> Maybe you've changed something for that option type?

Nothing is changed , there is override but option ID's are same http://prntscr.com/icax3m as here 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/extensions/contact-forms/shortcodes/contact-form/options.php#L10

**Comment by ViorelEremia** [comment]
Ok I don't understand.
You mean I have to check once and execute that function:
```
if ( current_action() === 'fw_post_options_update' ) {
	$extension->_set_form_db_data( $atts['id'], $atts );
}
```
framework/extensions/forms/extensions/contact-forms/shortcodes/contact-form/class-fw-shortcode-contact-form.php line 60

**Comment by danyj** [comment]
> Ok I don't understand.

Add 5 contact forms , 

preview few times , than save  ,  there should be only 5 entries

delete them all, all should be gone

that should be the process

Now imagine this ,  we give users template for contact forms , about 15 of them ,  
they import template check to see if they like , 2-3 entries in DB, 
they add another and so on , 
until they finish the page they might endup with min 10-15 entries for one page. 


The preview should use expiring transient in my opinion , not the actual option save

**Comment by danyj** [comment]
Is this going to be fixed?

**Comment by danyj** [comment]
> all of them 

explain please , I dont follow

**Comment by ViorelEremia** [comment]
When you save the page  i do shomething like that:
```
add_action( save_post, function() {
// check if the builder is enabled bla bla
global $wpdb;
$wpdb->query( "DELETE FROM wp_options WHERE option_name LIKE '%fw:ext:cf:fd:%'" )
}  );

**Comment by danyj** [comment]
that would remove all contact form settings from the site, how is that going to fix the duplication? 

it just removes all forms in DB

**Comment by ViorelEremia** [comment]
Can you try?

**Comment by danyj** [comment]
few min , doing page options , will reply after i test

**Comment by danyj** [comment]
on this now

**Comment by danyj** [comment]
this seems like it is doing the right job , 

2 forms 2 options on preview and save 

on delete , one option or none if all gone
