### ISSUE TITLE
Shortcodes doesn't work on the  term/category/taxonomy admin page

### ISSUE THREAD

**Issue by poltorrr** [ThemeFuse/Unyson#3174]
Shortcodes doesn't work on the admin term/category page (tables, image upload, ...).

http://joxi.ru/EA4NBnRSw1L44m - this is how "Table" shortcode looks, and nothin's going on when I click Add Column button

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson/issues/2544
