### ISSUE TITLE
Editor Blank After Update

### ISSUE THREAD

**Issue by davsaved** [ThemeFuse/Unyson#3175]
I'm needing some help with this pretty fast, I did the most recent update and all my editor areas are blank. The only good news is all my content still exist on the published website but I can't edit any thing. 

Can I get some direction on a fix or where to download the previous version?

**Comment by ViorelEremia** [comment]
Try to update your unyson extensions see here how: https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by normiinspire** [comment]
hi, I'am also facing the same problem. i just install it new, and no extention update available. but the problem still occured.

**Comment by ViorelEremia** [comment]
@normiinspire have you latest versions of extensions?

**Comment by normiinspire** [comment]
@ViorelEremia i think so.. since no update available for it.
Unyson Extensions
You have the latest version of Unyson Extensions.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by erc67** [comment]
Hi, I've got the same Problem. Unfortunately white Screen and no way to edit the sites after update. The Content is still existing and shown on Website. But no Chance to edit the Content. And I've done all updates so I have latest Version of extensions. #2764 already considered but do not work for me.
 Any quick help?

**Comment by ViorelEremia** [comment]
@erc67 Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by normiinspire** [comment]
@ViorelEremia .

hi.. i send you an email to access my wordpress.

tiendasoux.store


the funny part is some page can be edit / open using visual some can't

let me give sample of page which can be open and which not

1. some name of the problematic page.
Your ocean of posts
More waters to explore

2. page with no problem/issue at all.
Home Landing 1
Home Shop

**Comment by erc67** [comment]
@vioreleremia

Just send an email with credentials.
Thank you in advance.

**Comment by ViorelEremia** [comment]
@erc67 what pages you have the issue? I don't see any issues.

**Comment by ViorelEremia** [comment]
@normiinspire are you sure you have something on this page ```Your ocean of posts```? 
Your site is after demo install? 
Is that page created with demo install? 
Maybe this page is not created with the unyson builder because it is rendered via templates, can you ask your theme developer how that page should work.
![screenshot from 2018-02-05 15-02-17 1](https://user-images.githubusercontent.com/28967378/35966674-329f2488-0cc7-11e8-83f4-67beb4052046.png)

**Comment by normiinspire** [comment]
ok noted

**Comment by erc67** [comment]
![9200e237-6a59-4bd0-9013-eb54b9f54225](https://user-images.githubusercontent.com/36237743/35973878-521885d8-0cd7-11e8-8939-d888bf6dfb49.png)


@ViorelEremia 

Look at this screenshot. Could this issue be related to the desktop browser (internet explorer)? I deleted already cache and temporary files. 
But good news: On my mobile (Safari Browser) is it working well.

Maybe any idea for make it working with internet explorer?

**Comment by ViorelEremia** [comment]
What ie version do you have?
edge?

**Comment by erc67** [comment]
@vioreleremia

I‘m using ie 11 Version:11.0.9600.18893

**Comment by ViorelEremia** [comment]
@erc67 Why ie 11? 
Use edge i checked some big pages and is working well. 
Microsoft does not support older versions anymore, so i don't want to spend my time for something that will be removed.

**Comment by erc67** [comment]
Alright, is it working with edge.
Is it also working well with chrome.
I‘m happy, thanks.

**Comment by corizzo** [comment]
Having the same issue. Tried to roll back to last version of Unyson. No luck. tried with the extensions not installed. no change. am unable to update any page. Tried in firefox as well- no luck. sending log in to ViorelErmia.

**Comment by ViorelEremia** [comment]
@corizzo what log I did not get anything.

**Comment by corizzo** [comment]
am creating it now. Please hang on a moment.

**Comment by Yourgoods** [comment]
Same for me doesn't work in IE11, does works in Edge

**Comment by ViorelEremia** [comment]
@corizzo it solved. Your theme was not updated

**Comment by corizzo** [comment]
Why wouldn’t i get a notice of updating my theme then? That’s very strange.

**Comment by LuisGC81** [comment]
hello @ViorelEremia,

After install unyson I can not edit any pages. When i try it, It show a blank page.

**Comment by georges-2000** [comment]
Same problem here, the editor is blank in the backend after last update.

Content is here on the front though

Please advise

**Comment by georges-2000** [comment]
<img width="901" alt="screen shot 2018-03-16 at 10 32 24" src="https://user-images.githubusercontent.com/2392657/37513422-5bc7b636-2905-11e8-8ca3-7e60d520e5f6.png">

**Comment by georges-2000** [comment]
There is content within fw:opt:ext:pb:page-builder:json field
but neither in the classic editor nor the builder

**Comment by ViorelEremia** [comment]
do you have latest unyson extensions

**Comment by georges-2000** [comment]
All my plugins are up to date

**Comment by ViorelEremia** [comment]
I mean extensions? https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by ViorelEremia** [comment]
Remove any cache: plugin wp, server, browser

**Comment by georges-2000** [comment]
Ok sorry I was starting panicking

For the one who have the same problem go to:

**Unyson tab > Update all extensions**

_(they don't appear in the main Extensions tab)_

Thanks @ViorelEremia

**Comment by northerner80** [comment]
I'm having the same issue with WPVersion 4.9.5, Unyson 2.7.12, pages shows as blank in back end, and there is only one text block,, inside that text box is 
I've cleared all server side cache, tried different browsers, updated to the latest extensions.  Any ideas? Thank you.

**Comment by anandspybs** [comment]
I had the same problem, but I have fixed it. You need to do:
1. Deactivate the plugin
2. Delete the plugin
3. Delete the cache
4. Install again. 

I hope this will work for you.
