### ISSUE TITLE
Settings options values if they don't already exist?

### ISSUE THREAD

**Issue by Taimurian** [ThemeFuse/Unyson#3176]
What's the best way for setting theme settings values if they don't already exist?

Is it safe to use

`$color = $option['color'] ?: 'blue';`

Instead of 

``$color = isset($option['color']) ? $option['color'] : 'blue';``

**Comment by ViorelEremia** [comment]
Try function ```fw_get_db_settings_option($option_id, $default_value = null)```: http://manual.unyson.io/en/latest/helpers/php.html#database
Ex: ```$color = fw_get_db_settings_option( 'color', 'blue' );```

**Comment by Taimurian** [comment]
This works fine if I want to get an option from a one dimensional settings array. but in the case of multi-dimensional array how can we make sure if an option has a value and set a default value instead.

How can I write this in a more clean/valid way :

```
$header_settings = defined( 'FW' ) ? fw_get_db_customizer_option( 'header_settings' ) : array();
$layout = isset($header_settings['layout_picker']['layout_type']) ? $header_settings['layout_picker']['layout_type'] : 'offcanvas';
```

**Comment by ViorelEremia** [comment]
Use like that: ```fw_get_db_settings_option( 'key1/key2/color', 'blue' )```
You can find other helpers in unyson/framework/helpers each file is quite clear what purpose it has
