### ISSUE TITLE
Got error message 413

### ISSUE THREAD

**Issue by siamres** [ThemeFuse/Unyson#3177]
I'm using UNYSON plugin, which is included in The CORE theme.

The error occurs when I press update button on one specific page. Other pages is working fine.

the error message is

Request Entity Too Large

The requested resource
/wp-admin/post.php
does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

Any suggestion

**Comment by ViorelEremia** [comment]
Try to increase post_max_size: http://docs.themefuse.com/the-core/your-theme/theme-settings/how-to-set-a-maximum-file-upload-size

**Comment by ViorelEremia** [comment]
If you can't solve that issue, please write to theme author: https://support.themefuse.com/hc/en-us/requests/new
