### ISSUE TITLE
Problem with AJAX Contact form

### ISSUE THREAD

**Issue by krek95** [ThemeFuse/Unyson#3179]
Good afternoon!
Sorry for my bad english, but I need help.

I need help with connecting AJAX to the contact form.

Following the tip [here](https://github.com/ThemeFuse/Unyson-Forms-Extension/issues/8#issuecomment-77432623).

But this method does not work for me. The script included, but does not work.
The page still refresh after submitting the form.

**Comment by krek95** [comment]
Hey, anyone can't help me?

**Comment by danyj** [comment]
Browse the docs please 

http://manual.unyson.io/en/latest/helpers/form.html

https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw-form-helpers.js

**Comment by krek95** [comment]
Thank you.
I checked the documents.

But I still have one stupid question: since I'm just starting the development of websites, I don't understand why i'm need code for rendering, validating and saving my form?

If they are needed for the work of Ajax in this case, where do I need to add it? In functions.php?

**Comment by danyj** [comment]
bud , this is developers git and bit higher level than a start is required to understand the process. We can point you in the direction , show you the examples used but we will not have much time for explanations of files order and where what should go.

**Comment by krek95** [comment]
ok, i'm understand you.
