### ISSUE TITLE
Extensions won't install - cannot create temporary directory

### ISSUE THREAD

**Issue by rplumlee** [ThemeFuse/Unyson#3181]
I am using the Jevelin wordpress theme, and it is working great on localhost. When I used all-in-one wp migration to move it to AWS, the Unyson plugin broke. I tried deleting the folder and reinstalling to no avail.

Every extension fails with the message "cannot create temporary directory" on install.  

I saw that this bug has happened to several people over the years - I wasn't able to fix based on those threads.  Is there a known issue with AWS free wordpress hosting and Unyson? If not, do you have any ideas of what I could do to fix it?

**Comment by ViorelEremia** [comment]
Other errors you do you have? Somthing like that ```Cannot create temporary directory: a error message```
That is happening when the class ```FW_WP_Filesystem``` can't create folder tmp that viea wp_filesystem
Try to inspect into that class check that is happening with ```$wp_filesystem->mkdir( $path )``` file ```framework/helpers/class-fw-wp-filesystem.php``` function ```mkdir_recursive``` line 305. 
Check are there any errors from $wp_filesystem with ```$wp_filesystem->errors```
Have you right permission for tmp folder?

**Comment by rplumlee** [comment]
So upon WP_DEBUG, I get this: 

Warning: Cannot create directory "". It must be inside "/opt/bitnami/wordpress" or "/opt/bitnami/wordpress/wp-content" or "/opt/bitnami/wordpress/wp-content/plugins" or "/opt/bitnami/wordpress/wp-content/themes" in /bitnami/wordpress/wp-content/plugins/unyson/framework/helpers/class-fw-wp-filesystem.php on line 276

it looks like $path is returning false within the mkdir_recursive class.  I'm still not sure how to fix it.

**Comment by ViorelEremia** [comment]
I think there is wrong file permission try to run:
```
sudo chown -R bitnami:daemon /opt/bitnami/apps/wordpress/htdocs/wp-content
sudo chmod -R g+w /opt/bitnami/apps/wordpress/htdocs/wp-content
```
When that happens? When you try to activate/install extension?

**Comment by rplumlee** [comment]
That didn't help - 

I think the issue is it's trying to create the directory with an empty path, instead of it being inside /opt/bitnami/wordpress. In my error above it says Cannot create directory "".  Doesn't that mean the $path variable is empty after iterating over the base dirs map? (class-fw-wp-filesystsem.php, line 264)

Could this be an issue with the bitnami AMI image I chose? for example, my file structure is /opt/bitnami/wordpress/wp-content - it doesn't have the apps or the htdocs directories in the path.

I am using the Bitnami AMI ID: ami-1942677c

**Comment by rplumlee** [comment]
To clarify, after running those permissions commands, I get the same error I copied above ^^

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please specify github url issue in the message.
When that happens? when do you try to update/install extension?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.

**Comment by JohannesKopetschke** [comment]
@rplumlee Did you manage to solve this? I have the same issue :(

**Comment by musatoktas** [comment]
I am also facing the same problem, does anyone has a solve?

**Comment by chnbrs** [comment]
Same issue here,

After activating unyson plugin then go on unyson page and clicking the link "Install theme compatible extensions" there is Install Compatible Extension page it shows Backup & Demo Content. I clicked yes, install this extension then it throws ;

Warning: Cannot create directory "". It must be inside "/opt/bitnami/wordpress" or "/opt/bitnami/wordpress/wp-content" or "/opt/bitnami/wordpress/wp-content/plugins" or "/opt/bitnami/wordpress/wp-content/themes" in /bitnami/wordpress/wp-content/plugins/unyson/framework/helpers/class-fw-wp-filesystem.php on line 275
Cannot create temporary directory:

Cannot create temporary directory:
Return to Extensions page

**Comment by mcampetta** [comment]
This issue was resolved for me by adding `define('WP_CONTENT_DIR', realpath(ABSPATH . './wp-content/'));` to my wp-config.php at the bottom. The idea is that it replaces the definition before it which is made by the WP instillation automatically. 

Installing the extensions fails because ABSPATH is an empty string and this sets ABSPATH to your ./wp-content subdir 

Issue referenced from #4186
