### ISSUE TITLE
Builder previews dont work on custom post types

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3182]
Builder preview does not work at all on custom post types like event or portfolio projects, 
you are forced to save to see changes

**Comment by firogit** [comment]
Can't find Portfolio Extension inside page builder under Content Elements

**Comment by danyj** [comment]
@firogit  no hijacking , please check where you post

**Comment by firogit** [comment]
you can help me on my issue as mentioned?

**Comment by firogit** [comment]
If not,leave it

**Comment by danyj** [comment]
@firogit This is not you personal chat group , stay away from other users post unless you have something to contribute otherwise you will get blocked.  

Now delete those replies and continue in yours.

**Comment by danyj** [comment]
can someone please take a look at this , 
it has been fixed for posts and pages but not for CPT's
https://github.com/ThemeFuse/Unyson/issues/2441#issuecomment-345545847

**Comment by ViorelEremia** [comment]
Can you try?
What custom post type do you use? from extension portfolio and events?

**Comment by danyj** [comment]
portfolio and events or any custom post type whee you allow builder, 
example , create some post type than go in builder settings and allow it on that post type

will test this

**Comment by danyj** [comment]
and since last version the fix for pages we had few weeks ago is failing again,  I have to click 3 times on preview to see the change and most of the time I am forced to click update

**Comment by ViorelEremia** [comment]
add support for them: https://codex.wordpress.org/Function_Reference/register_post_type#supports

**Comment by ViorelEremia** [comment]
Try now should work

**Comment by danyj** [comment]
> add support for them:

revisions right?

**Comment by ViorelEremia** [comment]
Yes in your register array: 
```
'supports' => array(
	'title',
	'editor',
	'thumbnail', 
	'revisions'
)
```

**Comment by danyj** [comment]
works now for events and portfolio but pages is still buggy 
https://github.com/ThemeFuse/Unyson/issues/3182#issuecomment-368504045

3 clicks seem to be a must

**Comment by ViorelEremia** [comment]
For options or for builder

**Comment by danyj** [comment]
> For options or for builder

complete page ,  I add sections columns elements and must click 3 times

**Comment by danyj** [comment]
sec Il make a video

**Comment by ViorelEremia** [comment]
I tested with scratch theme and the core and is working well

**Comment by danyj** [comment]
well now it is stubborn and works , 10sec ago did not
can this be some cache?

**Comment by ViorelEremia** [comment]
Mybe I changed and some js files

**Comment by danyj** [comment]
ok lets leave it as is for now, il close this

**Comment by danyj** [comment]
thank you!

**Comment by danyj** [comment]
What ever you changed today is messing up Media upload option values , 

I just opened an item that should have 5 images like this 

http://prntscr.com/ik5yvo

and that option value is empty showing no image , 

I then reverted back to previous version before today and the value and images came back. 

Please check

**Comment by danyj** [comment]
the option is located inside shortcode element options and array is like this 

```
addable-popup
---multi-picker
-----choices
-------(choice) images
---------multi-upload
```

**Comment by danyj** [comment]
here is code example just add multi-upload in one of the choices and select several mages , save popup , reopen, images not there

**Comment by danyj** [comment]
yes , other options to , reporting error like undefined variable $value within option types , 3 so far, please check

**Comment by danyj** [comment]
fix confirmed
