### ISSUE TITLE
Demo content install issue: The execution failed. Please check error.log

### ISSUE THREAD

**Issue by MPC13** [ThemeFuse/Unyson#3184]
Hi there,

For WP design purposes, I am trying to install a Demo of a theme called Teatime but I keep on getting an error "The execution failed. Please check error.log" whenever the installation is in the "Archive Zip" stage.

I tried searching for some fixes here and I even extracted a commit made by @ViorelEremia but I still get this issue.

My WP installation is hosted on GoDaddy with the standard package.

Could someone give me a hand on this? Has anyone experienced this after trying out a different commit to the Backups folder and also setting get_timeout to -20?

Thanks!
M

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
