### ISSUE TITLE
Can we use multiple fw-storage on one option?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3185]
@ViorelEremia  @andreiglingeanu I need to set post-meta and wp_option  for same option 

this is what I have now 

```
'type'  => 'select',
'value' => 'unassigned',
'label' => __('Position', 'fw'),
'desc'  => esc_html__('Select position.', 'fw'),
'fw-storage' => array(
    'type' => 'wp-option',
    'wp-option' => 'thz_positions',
    'key' => $post->ID
),...
```

but I need 

```
'type'  => 'select',
'value' => 'unassigned',
'label' => __('Position', 'fw'),
'desc'  => esc_html__('Select position.', 'fw'),
'fw-storage' => array(
    'type' => 'wp-option',
    'wp-option' => 'thz_positions',
    'key' => $post->ID
),

'fw-storage' => array(
    'type' => 'post-meta',
    'post-meta' => 'position',
),
```

or any other way to add the same option value to the post-meta on post save.

**Comment by danyj** [comment]
@ViorelEremia  not even a hint bud?

**Comment by andreiglingeanu** [comment]
The only option I can see is to register a new `fw-storage` & combine the two into one

**Comment by danyj** [comment]
yeah , I was trying to avoid that

**Comment by ViorelEremia** [comment]
No, you can't do that. 
It's too dangerous to do that at the moment in unyson, I can destroy too many sites because ```FW_Option_Storage_Type``` is extended very far. So I agree with Andrei you need to register a new storage.

**Comment by danyj** [comment]
np ,  will see what I can do , thnx.
