### ISSUE TITLE
Importing from a different theme

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson#3186]
Hello,
I need to import a backup from a theme that has a different slug but has exactly the same configs/options/php files (so basically only CSS is different).

I identified that I could change the `"option_name":"fw_theme_settings_options:xxxxx"` from the exported `database.json.txt` to my new theme slug and that will import the Theme Options. What else should be done ? I noticed for example that the menus locations won't get updated, though they have the same ids/names.

**Comment by toleabivol** [comment]
It is creating the menus alright but not assigning them to the corresponding nav_menu_locations

**Comment by toleabivol** [comment]
OK, found how to deal with menus:
`theme_mods_xxxxx`  change to new slug   `theme_mods_yyyyy`
Anything else I should account for ?

**Comment by ViorelEremia** [comment]
I think that's enough should work.
