### ISSUE TITLE
Error when updating on the builder

### ISSUE THREAD

**Issue by carlosbehrens** [ThemeFuse/Unyson#3187]
Hello, i have an issue. I am customizing my Home page, but everytime i hit Update on the builder, the website starts loading and then after a while it takes me to the posts section with the error "this site can´t be reached". I have no idea why this is happening. i'm working with the Mickhel theme.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```

**Comment by carlosbehrens** [comment]
Thank you for replying! It seems that it was a temporary issue. It's working now. If this happens again, i will let you know. Thank you again
