### ISSUE TITLE
Page Bulider not loading after update 2.7.11 -> 2.7.12

### ISSUE THREAD

**Issue by medijan** [ThemeFuse/Unyson#3188]
I already downgraded to 2.7.11 to make the Backend work again. I tried twice to update. Contents seems disappeard, the Page Bulider isn't loading...

Here is the full Error Stack from firebug:
---
SyntaxError: expected expression, got ')'
https://domain.de/wp-content/plugins/unyson/framework/static/js/fw-reactive-options-registry.js?ver=4.9.4
Line 236

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/static/js/fw-reactive-options-undefined-option.js?ver=4.9.4
Line 3

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/static/js/fw-reactive-options-simple-options.js?ver=4.9.4
Line 19

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/static/js/fw-reactive-options.js?ver=4.9.4
Line 69

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/includes/option-types/addable-popup/static/js/scripts.js?ver=2.7.12
Line 244

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/includes/option-types/multi-picker/static/js/multi-picker.js?ver=2.7.12
Line 214

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/includes/option-types/map/static/js/scripts.js?ver=1.0
Line 435

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/includes/option-types/upload/static/js/images-only.js?ver=2.7.12
Line 213

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/includes/option-types/wp-editor/static/scripts.js?ver=2.7.12
Line 158

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/includes/option-types/image-picker/static/js/scripts.js?ver=2.7.12
Line 5

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/includes/option-types/multi-upload/static/js/images-only.js?ver=2.7.12
Line 197

unreachable code after return statement
https://domain.de/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/static/js/editor_integration.js?ver=1.6.14
Line 236

 [Events] Exception raised. Please contact support in https://github.com/ThemeFuse/Unyson/issues/new. Don't forget to attach this stack trace to the issue.

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12
Line 142

TypeError: fw.options is undefined
https://domain.de/wp-content/plugins/unyson/framework/includes/option-types/switch/static/js/scripts.js?ver=2.7.12
Line 50
---

This Error ist also present in 2.7.11, but Page Builder is working:

unreachable code after return statement
https://domain.de/wp-content/plugins/unyson-2.7.11/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/static/js/editor_integration.js?ver=1.6.14
Line 236

**Comment by ViorelEremia** [comment]
There are no syntax errors in fw-reactive-options-registry.js 
Have you installed any cache plugin or script compression plugin?

**Comment by medijan** [comment]
No, not yet. Site is currently in development. iThemes Secuity, Event Espresso, and several eea add-ons are installed. Theme is panino from subsolar. The errors above comes after updating unyson.

**Comment by david1629** [comment]
I am also facing the same issue since I have updated the Unyson to 2.7.12 plugin. No cache plugin installed on my website. Plz help..

**Comment by ViorelEremia** [comment]
@david1629 
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please specify github url issue in the message.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.

**Comment by zoltanseer** [comment]
IE throws error because of an extra comma in /framework/static/js/fw-reactive-options-registry.js

```
function __unsafePatch (type, hintObject) {
    allOptionTypes[type] = jQuery.extend(
        {}, defaultHintObject(),
        (allOptionTypes[type] || {}),
        hintObject || {}, // <- this comma should be deleted
    );
}
```

**Comment by pnpetroff** [comment]
A client of our is also experiencing this issue. On Mac using Safari and Firefox. We cannot reproduce it on our end.

![scrrr](https://user-images.githubusercontent.com/1108563/38161161-54713320-34d2-11e8-8944-c34168d8a03b.png)

**Comment by pnpetroff** [comment]
@ViorelEremia I can provide credentials for further investigations on this problem.
