### ISSUE TITLE
Can't find Portfolio Extension inside page builder under Content Elements -issue

### ISSUE THREAD

**Issue by firogit** [ThemeFuse/Unyson#3189]
Hi,
I can't find Portfolio Extension inside page builder under Content Elements.And i have already done in admin
"Select the posts you want the Page Builder extension to be activated for"
Please help me the same.
Thank you.

**Comment by danyj** [comment]
This is not you personal chat group , stay away from other users post unless you have something to contribute otherwise you will get blocked.

**Comment by steve-themefuse** [comment]
You need to contact your theme author and ask them if they have a Portfolio shortcode, by default the Unyson page builder does not come with one. 

What you have selected from Unyson->Page Builder Settings only activates the page builder for blog posts and custom post types.
