### ISSUE TITLE
Option set before tabs container display after

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#319]
Try this in theme options

				'aaaaa' => array(
					'type' => 'short-text',
					'value' => '300',
					'label' => __('AAAA', 'unyson'),
				),			
				'layout' => array(
					'title'   => __( 'Layout', 'unyson' ),
					'type'    => 'tab',
					'options' => array(
						//fw()->theme->get_options( 'layout' ),
					),
				),

The aaa option will be displayed after the tab instead before

http://prntscr.com/6d0g0n

**Comment by moldcraft** [comment]
The [`fw()->backend->render_options()` method](https://github.com/ThemeFuse/Unyson/blob/80718543f0f1fea54c4938d9639e7c32ee86a1bd/framework/core/components/backend.php#L948-L1049) works in this way:

1. Collect first level tabs,boxes,groups,options
2. Display all collected tabs

    ```html
    <div class="fw-options-tabs-wrapper">
        <div class="fw-options-tabs-list">...tab1...tab2...tabX...</div>
        <div class="fw-options-tabs-contents">...tab1content...tab2content...tabXcontent...</div>
    </div>
    ```

3. Display all collected boxes

    ```html
    <div class="fw-backend-postboxes metabox-holder">...box1...box2...boxN...</div>
    ```

4. Display all collected groups and options

I thought no one will want to display options outside tabs, that there will be only regular settings pages: 

`tab -> (box ->) option`

----

This is critical for you or you just noticed that while experimenting with options?

**Comment by danyj** [comment]
Not critical but I wanted to add #318 before the tabs since I have nested tabs 

	Tab1(selected), Tab2, Tab3
	Description (318 ) 
	Sub tab1 , Sub tab2, Sub tab3

http://prntscr.com/6d0uas

**Comment by moldcraft** [comment]
I will take a look and see if a can display tabs,boxes,groups,options exactly in the order they are in array.

**Comment by moldcraft** [comment]
[Done](https://github.com/ThemeFuse/Unyson/commit/5bd763ffeee5b7da3fd765d98aaee63efa5ed08c?diff=split)

Please [download](https://github.com/ThemeFuse/Unyson/archive/master.zip) the latest version of Unyson from Github and test with these options:

```php
$options = array(
	'tab-1' => array(
		'title'   => __( 'Tab1', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			't1t' => array('type' => 'text'),
		),
	),
	'tab-2' => array(
		'title'   => __( 'Tab2', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			't2t' => array('type' => 'text'),
		),
	),
	'group-1' => array(
		'type'    => 'group',
		'options' => array(
			'g1t' => array('type' => 'text'),
		),
	),
	'text1' => array('type' => 'text'),
	'tab-3' => array(
		'title'   => __( 'Tab3', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			't3t' => array('type' => 'text'),
		),
	),
	'box-1' => array(
		'title'   => __( 'Box1', 'unyson' ),
		'type'    => 'box',
		'options' => array(
			'b1t' => array('type' => 'text'),
		),
	),
	'text2' => array('type' => 'text'),
	'tab-4' => array(
		'title'   => __( 'Tab4', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			't4t' => array('type' => 'text'),
		),
	),
	'tab-5' => array(
		'title'   => __( 'Tab5', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			't5t' => array('type' => 'text'),
		),
	),
	'group-2' => array(
		'type'    => 'group',
		'options' => array(
			'g2t' => array('type' => 'text'),
		),
	),
);
```

**Comment by danyj** [comment]
Thank you my friend. I just shutdown for the day. Will test and reply tomorow.

**Comment by danyj** [comment]
Excellent. Thank you!
