### ISSUE TITLE
Global post type options

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3190]
Is there any way to have global options set for any post type instead of 
creating the  files like 

```
theme/options/posts/fw-event.php
theme/options/posts/fw-portfolio.php
theme/options/posts/post.php
```

**Comment by danyj** [comment]
or maybe we have an event like this 
https://github.com/ThemeFuse/Unyson/issues/3158#issuecomment-362590573

somewhere that we are not aware of

**Comment by danyj** [comment]
>  because you dont have templates for them

in my theme any CPT is using default single post template if there is no template for it, 
and that is why all my page options work on them. 

but the question has nothing to do with the templates itself, but the admin options for any post type,

**Comment by ViorelEremia** [comment]
add_action( 'fw_post_options', function( $post_type ){
//if my post type
return arraywithoptions
 );

**Comment by danyj** [comment]
for example any premium theme has set of option in CPT to override theme defaults 

  http://prntscr.com/iemx4k


we do that to with a difference that we have to re-declare the same tab for every post type

**Comment by danyj** [comment]
> fw_post_options

il try that thnx!


should I assume that we also have 


`fw_term_options`

**Comment by danyj** [comment]
I found an old reply for thiswhich I forgot about  but the second param is not returning post type , is always null 

https://github.com/ThemeFuse/Unyson/issues/2359#issuecomment-275592560

@ViorelEremia  check please

**Comment by danyj** [comment]
@ViorelEremia  never mind , it is filter , not action

**Comment by ViorelEremia** [comment]
don't matter what is filter, action should work

**Comment by danyj** [comment]
action returns null for post_type attribute ,

**Comment by ViorelEremia** [comment]
You know how to do that https://github.com/ThemeFuse/Unyson/issues/2359 is opened by you

**Comment by danyj** [comment]
no you right , was missing the  second attribute in the action call

**Comment by danyj** [comment]
>You know how to do that 

that is what I said above , I forgot about it. 


do we have something like this for taxonomy options ?

**Comment by danyj** [comment]
yes we do ,  https://github.com/ThemeFuse/Unyson/blob/3529c9ac209e1dc00122718669bebab3b9afbd5b/framework/core/components/theme.php#L135


thank you @ViorelEremia
