### ISSUE TITLE
I updated to the new Unyson 2.7.12 and now all the backend pages are blank. The framework is gone. I am using the latest Core Theme and am also using 4.9.4 WP version. 

### ISSUE THREAD

**Issue by rroots** [ThemeFuse/Unyson#3191]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.

**Comment by ViorelEremia** [comment]
1.Update unyson extensions: https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
2. Remove any cache from server or wp plugins

**Comment by ViorelEremia** [comment]
viorel@themefuse.com

**Comment by rroots** [comment]
I added you as an administrator, email sent to you. The site is SIHC.net

**Comment by ViorelEremia** [comment]
What page doesn't work?
I checked home page and is working.
What browser do you use?

**Comment by rroots** [comment]
The content is on the site. It is the inside that is blank, not loading. I am using Chrome.

**Comment by ViorelEremia** [comment]
![edit page sigma institute of health careers broward county florida wordpress](https://user-images.githubusercontent.com/28967378/36221781-de437942-11c7-11e8-99a3-401488706306.png)

**Comment by rroots** [comment]
I don't see that when I open the page to edit. Mine is blank. I think I know the problem. I am using an XP windows version. I just sent another pdf showing what I see. Is it possible it is my XP computer?

**Comment by rroots** [comment]
The attached pdf shows you what I see. Is it because I am using XP? Robert Roots- Speaker, Consultant and Author of Child Support is more than Money! (and) Success Secrets from The Three Little PigsRobertRoots.com

**Comment by ViorelEremia** [comment]
yes, chrome is not more supported for xp there is nothing to do i can't help you here you need to upgrade your computer or use another OS like https://lubuntu.net/ for old computers

**Comment by ViorelEremia** [comment]
You can try to remove browser cache if is not working then you need another computer
