### ISSUE TITLE
Text Editor removes line breaks and paragraphs 

### ISSUE THREAD

**Issue by juliahermel** [ThemeFuse/Unyson#3193]
I found that when editing / adding text in the accordion element, line breaks and paragraphs are removed upon save. As seen in the screenshot of the text mode, there are no `<p>` or `<br>` tags to be seen. It only works if I add every `<p>` manually, which is very tedious. It also seems to be the case in regular Text Blocks. Maybe the wpautop filter was disabled where it shouldn't have been? Is this behavior intentional? Insights on this would be very much appreciated.

Many thanks,
Julia

![accordion-editor-01](https://user-images.githubusercontent.com/35395560/36252003-8a627978-1243-11e8-851b-6fb66debc0e9.PNG)
![accordion-editor-02](https://user-images.githubusercontent.com/35395560/36252004-8a83e1bc-1243-11e8-9e17-b6b27e5ae885.PNG)
![accordion-frontend](https://user-images.githubusercontent.com/35395560/36252005-8aa1a864-1243-11e8-9061-7f792951f54b.png)

**Comment by danyj** [comment]
are you working with a specific theme or core default Unsyon framework ?

if theme than theme provider should have done enabled the full format 

shortocde itself has no restrictions 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/accordion/views/view.php#L9

and in backend there is no editor for accordions 

http://prntscr.com/if38c3

**Comment by danyj** [comment]
you ca try to modify the shrotcode 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/accordion/options.php#L17-L20

and use this instead 

```
	'tab_content' => array(
		'type' => 'wp-editor',
		'size' => 'large',
		'editor_height' => 250,
		'editor_type' => 'tinymce',
		'shortcodes' => true,
		'value' => 'Hello',
		'label' => __('Content', 'fw')
	)
```

**Comment by juliahermel** [comment]
@danyj Thanks for your reply. We're using the Page Builder extension and a paid theme. The whole page has been built with the help of the Page Builder without any actual code. As it's a pre-installed theme that's being used, I can't edit the code.

**Comment by danyj** [comment]
you should be able to do shortcode override in the child theme if developer has used the Unyson MVC, 
best bet is ask the dev to add the functionality in

**Comment by ViorelEremia** [comment]
There is no way to do that. If you want to use html in option type editor add a textarea or you can try to use tags <p class="someClass"></p> with classes. The issue occurs because we use some triggers js events like click, resize to refresh editor we tried several methods but no result has been obtained.
