### ISSUE TITLE
Sticky footer on pages with short content

### ISSUE THREAD

**Issue by mikegoodstadt** [ThemeFuse/Unyson#3195]
Hi Unyson team!
I am using the scratch theme but some of my pages have little content and so do not occupy the full browser height. I would like to have a sticky foot unless the page is longer than the browser height. Which method would you recommend to achieve this? (if, that is, you consider any possible or compliant within the Unyson framework :) )
Many thanks for this great resource.
Mike

**Comment by ViorelEremia** [comment]
You mean something like that: https://css-tricks.com/couple-takes-sticky-footer/ ?
I don't think it is a good idea to add it in theme scratch. Scratch theme is a theme with demo option types,  a starting point for developers or an idea how to start your theme based on unyson plugin. So if you are a developer of themes you can easy do that. If you use a premium theme you can ask theme developer for this feature.
