### ISSUE TITLE
Session Start Error

### ISSUE THREAD

**Issue by rmoskow1** [ThemeFuse/Unyson#3197]
I'm having errors with activating the plugin entirely. When I activate, I get the following error messages at the top of the dashboard, and on the site:

Warning: session_start() [function.session-start]: open(/home/content/07/12901407/tmp/sess_8dcdd79fdc0f32576de33dc614dc8691, O_RDWR) failed: No such file or directory (2) in /home/content/07/12901407/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 228

Warning: session_start() [function.session-start]: Cannot send session cookie - headers already sent by (output started at /home/content/07/12901407/html/wp-content/plugins/unyson/framework/includes/hooks.php:228) in /home/content/07/12901407/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 228

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /home/content/07/12901407/html/wp-content/plugins/unyson/framework/includes/hooks.php:228) in /home/content/07/12901407/html/wp-content/plugins/unyson/framework/includes/hooks.php on line 228

I'm on the most recent versions - I deactivated every one of my plugins, and I'm on a default theme (Twenty-Sixteen). The whole Word Press dashboard is glitchy too - the sidebar menu has large gaps and i can't scroll down fully. I also can't click on many of the widgets. 
This isn't an error I've gotten with any other theme or plugin at all. PLEASE HELP

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please specify github url issue in the message.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
