### ISSUE TITLE
Typography vs Typography-v2

### ISSUE THREAD

**Issue by Kraantje85** [ThemeFuse/Unyson#3199]
Hi, 

I have the question wich one is the better one to use? 

The v2 is the newest but i don't want that people can select the subset, spacing and so. So for the options i like the v1 better but i saw on Github some issues with the performance of the v1 is that fixed or?

Thank you for the anwsers.

**Comment by ViorelEremia** [comment]
> but i saw on Github some issues with the performance of the v1

what are they?
We use typography v1 in the core theme used by thousands of people and I did not notice any perfomance problems.

**Comment by Kraantje85** [comment]
Hi @ViorelEremia,

I found a topic last week trough Google can't find it anymore it was on Github. It a topic from 2015 or 2016 so maybe its already fixed for v1... It was just a question what is the better option to go with.

But for my issue i made my own typograpy thing :-)

![mine](https://user-images.githubusercontent.com/13745732/36373502-a56e232a-1568-11e8-94ae-a1c88b79d429.png)
