### ISSUE TITLE
Page Builder: "parsererror: SyntaxError: Unexpected token ﻿ in JSON at position 0"

### ISSUE THREAD

**Issue by sparrowsloan** [ThemeFuse/Unyson#3200]
After a week I wanted to edit my site, and now, even though I didn't change anything and it was working just fine a week ago, I get the message
"parsererror: SyntaxError: Unexpected token ﻿ in JSON at position 0"
I just can't edit any frame (see screenshot). How can I fix this?

My slider (Slider Revolution) suddenly appears very scaled as well.

Everything is updated, deactivating the plugins didn't help.
Tried different themes as well.

Plugins I use:
Unyson Page Builder
Coming Soon Page & Maintenance Mode by SeedProd
Envato WordPress Toolkit
Slider Revolution
![1](https://user-images.githubusercontent.com/36575064/36345345-e2cab846-1428-11e8-84bd-1041920a3c71.JPG)
![2](https://user-images.githubusercontent.com/36575064/36345347-e535a69a-1428-11e8-93a0-089b1989b4c6.JPG)

**Comment by sparrowsloan** [comment]
Jetpack is installed as well but deactivated and can't be activated anymore.

`The Jetpack server could not communicate with your site's XML-RPC URL. Please check to make sure http://julia-fuge.de/xmlrpc.php is working properly. It should show 'XML-RPC server accepts POST requests only.' on a line by itself when viewed in a browser and should not have any blank lines or extra output anywhere. Find out how to fix this issue here: https://jetpack.com/support/getting-started-with-jetpack/what-do-these-error-messages-mean/blank-lines-xmlrpc/`

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
