### ISSUE TITLE
Image Switch in Images on Page Builder on Unyson

### ISSUE THREAD

**Issue by CatBrown22** [ThemeFuse/Unyson#3201]
I have built a website with Unyson before and was able to use Image Switch when adding a image so I could create an image based hover effect. 

I am building a new website and the image switch option is no longer there as an option- how do I get it back?

**Comment by ViorelEremia** [comment]
Unyson dosen't have this option image switch, mybe the theme adds it. Check what extensions and theme you used on the previous site.
