### ISSUE TITLE
Demo importing problem for CHARSET and COLLATE

### ISSUE THREAD

**Issue by therakib7** [ThemeFuse/Unyson#3203]
Hello, Dear Unyson Support Team,
First I would like to thanks for your great plugin. But sometimes my client was facing demo import problem for CHARSET and COLLATE. I know that some MySql database support utf8mb4  and some support utf8.
So when database CHARSET and COLLATE had not match it shows error.  

Sometimes I fixed the problem by opening the file database.json.txt and text replace with utf8mb4 => utf8 and
utf8mb4_unicode_520_ci => utf8_general_ci
This solution is hesitating to me. 

So If you have any great solution please inform me so that it would auto import by checking database type. that will be helpful for us.
Thanks

**Comment by ViorelEremia** [comment]
This issue was solved in this line: https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L748
have you tried to see what this variable is turning?
Also you can inspect bellow that var this if:
```
if ( ! isset( $collations[ $collate ] ) || ! array_search( $charset, $collations ) ) {
	$sql = str_replace( array( $collate, $charset ), array( 'utf8_general_ci', 'utf8' ), $sql );
}
```

**Comment by ViorelEremia** [comment]
Closed due to inactivity.

**Comment by warudin** [comment]
I've experienced this problem today with the latest available extension of the Backups-extension. After updating [to this version](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L748) the problem was gone.
