### ISSUE TITLE
Install Compatible Extension

### ISSUE THREAD

**Issue by dobby323** [ThemeFuse/Unyson#3204]
I need help in adding these features
![img](https://user-images.githubusercontent.com/24942997/36394543-74cc4c06-15bd-11e8-9bc4-141717845f74.jpg)

**Comment by ViorelEremia** [comment]
You mean you want to add some supported extensions for your theme?
Add a file to ```/YourTheme/framework-customizations/theme/manifest.php```
with code:
```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$manifest = array();

$manifest['id'] = 'scratch';

$manifest['supported_extensions'] = array(
	'page-builder' => array(),
	'slider' => array(),
	'styling' => array(),
	'breadcrumbs' => array(),
	'events' => array(),
	'feedback' => array(),
	'learning' => array(),
	'megamenu' => array(),
	'portfolio' => array(),
	'sidebars' => array(),
);

```

**Comment by dobby323** [comment]
Thank you very much your suggestions decided my problem. And even better ... it automatically installed all the necessary extensions
