### ISSUE TITLE
get this error parsererror: SyntaxError: Unexpected token ﻿ in JSON at position

### ISSUE THREAD

**Issue by skysolution** [ThemeFuse/Unyson#3206]
On hellesandersen.dk I have upgarded to latest unyson version and if I try to edit the (page) setup all ellements i got an error, see subject

**Comment by ViorelEremia** [comment]
Usually this error occurs when is a error in ajax response. Are you a developer? Do you know how to inspect an error in ajax?

**Comment by skysolution** [comment]
No im only a little tecnical, but you can try guide me

**Comment by ViorelEremia** [comment]
Can you send me some temporary credentials (admin): ```viorel@themefuse.com``` ?
Please specify github url issue in the message.

**Comment by skysolution** [comment]
I have mailed

**Comment by ViorelEremia** [comment]
Solved BOM charater in wordpress installation.
