### ISSUE TITLE
shortcodes json file missing for icontext 

### ISSUE THREAD

**Issue by sergiustan** [ThemeFuse/Unyson#3209]
When trying to add some  Icontext shortcodes i get this error, please help. i reinstalled the extension from wp and manualy and  still not working.

![capture](https://user-images.githubusercontent.com/19977328/36534201-8a0143a2-17ce-11e8-843d-9d1d02e6b889.JPG)

**Comment by ViorelEremia** [comment]
What theme do you use? unsyon doesn't have by default any json file for icons.

**Comment by sergiustan** [comment]
vivian theme by subsoladesigns, http://www.subsolardesigns.com/vivian/

**Comment by ViorelEremia** [comment]
did you try to write them? try to write them because I think it is a theme issue

**Comment by sergiustan** [comment]
how to write them manualy? in the text editor? if so, how do i get to know the id of the icon i want to use?
thank you

**Comment by ViorelEremia** [comment]
write them, if they find it is an issue in unyson you can reopen this thread.
