### ISSUE TITLE
color-picker dont set to default value if saved empty

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#321]
I am using color picker for several backgrounds/colors and user should have an option to set it as blank as well.  Otherwise I must use multi-picker with 2 options , one for color and another to says something like " No background" which makes no sense. 

With current setting if color-picker option is saved  empty 

http://prntscr.com/6d58dg

it resets to default value which in bottom options would be #ffffff

	'submenu_bg'  => array(
		'type'  => 'color-picker',
		'value' => '#ffffff',
		'label' => __( 'Submenu background', 'fw' ),
		'desc' => __( 'Set submenu background', 'fw' )
	),

The default value should be used only if the options are reset or on first time options load, not when the color option is saved blank

**Comment by valeriuzdrobau** [comment]
Try to use RGBA-color-picker option,it allows you to set the opacity of the color. Not long ago I made a [small correction](https://github.com/ThemeFuse/Unyson/commit/fe0b51c6d05cb161be4e80e3c84b7fe14dc3eba0), pull the latest version.

**Comment by danyj** [comment]
Cant do that  it still returns values , I need it to be empty . I am checking if the color value is not empty and than add backrgound-color or color.

**Comment by danyj** [comment]
I dont know but maybe add a component to the array transparent on/off, the way it is now it requires you to always have color value or you must add an additional option which is to much. 

Imagine 20 color options, and for each adding on/off switch or using multi-picker, you end up with 40+ options just because we cant leave the color empty.

Thing is the value in DB is empty , it is this check that resets to default 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/color-picker/class-fw-option-type-color-picker.php#L56-L58

**Comment by valeriuzdrobau** [comment]
Values from 'color-picker' option type commonly used in views, and I think it's not fair that all users every time when they want to use this value to make a check in addition just because a small number of them need some more special. If you do not want to solve this problem using the option 'multi-picker', you can do an option for you and put it in 'framework customizations'.

**Comment by danyj** [comment]
how does this make any sense?   the values saved in DB is not the value that is show, makes no sense to show default if DB is something else

**Comment by danyj** [comment]
It is a bug not a feature if that is what you mean.

**Comment by danyj** [comment]
A simple  

    if(is_null($input_value)){  


instead of this 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/color-picker/class-fw-option-type-color-picker.php#L56

fixes this and works fine, reset, start default value and saves an empty value in db 

I made my own option with just this one line change but to me it is a bug.
