### ISSUE TITLE
Unyson shortcodes don't work in WP anymore...

### ISSUE THREAD

**Issue by velocharlevoix** [ThemeFuse/Unyson#3210]
I can select and insert any of the Unyson shortcodes in a new page or post content but they're not effective and I can't open their settings, duplicate nor delete them.  

In a previously (before the issue) laid-out page or post, they're effective/operational but I still l  can't open their settings, duplicate nor delete them. 

![image](https://user-images.githubusercontent.com/28760317/36557192-978bba14-17d5-11e8-9ca1-f4ed63c638f5.png)

Anyone knows how to fix this? Thanks!

P

**Comment by ViorelEremia** [comment]
Try to inspect browser console.  We can't see any error from your image. How to see chrome console errors see here: https://developers.google.com/web/tools/chrome-devtools/

**Comment by velocharlevoix** [comment]
@ViorelEremia Thanks! Here are the results:

![image](https://user-images.githubusercontent.com/28760317/36598120-248563c2-1879-11e8-943f-0ddc2713a819.png)

**Comment by ViorelEremia** [comment]
can you try to disable plugins? this is an error from jetpack.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
