### ISSUE TITLE
Changes in informations

### ISSUE THREAD

**Issue by pawelwasilenko** [ThemeFuse/Unyson#3211]
When I try to change the information (text), the page is up, I can change it, it's hard to reverse the version because it does not work either

**Comment by ViorelEremia** [comment]
Give us more information because it's not clear what you mean.

**Comment by pawelwasilenko** [comment]
Ok.
I dont know  what is going  on but my page  looks like this
[image: Obraz w treści 1]
and it shouldnt..
i got  informations in
 [image: Obraz w treści 2]
Header
about
contact .
there are informations  and it works good  but when i change phone numer my
page get crashed ..
idk that  is demo version and i need to buy pro version of your tool ?

when i set my informations and  i want to do map how to drive i have
information " Oooops! something went wrong " or sth


2018-02-23 14:58 GMT+01:00 ViorelEremia <notifications@github.com>:

**Comment by ViorelEremia** [comment]
I don't see anything, load the images correctly. Please describe the issue with as much details as you can. 
We can not help you if we do not understand what's happening on your site.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
