### ISSUE TITLE
Unyson Pagebuilder extension and Woocommerce not working

### ISSUE THREAD

**Issue by ScottShulman** [ThemeFuse/Unyson#3212]
I am running the architek theme, Unyson plugin and Woocommerce. all 3 work fine together on a workstation with traditional browser, but doesn't render on an ipad.

if I disable pagebuilder extension, site renders on ipad, but theme formatting goes to heck
if I uninstall woocommerce, then pages render correctly on pc and on ipad

ive setup a dev instance, and tried every combination. i'm at my witts end. 

Any help would be most appreciated.

Versions:
theme - Architekt ChildVersion: 1.0
woocommerce 3.3.3
unison 2.7.12
hosted on godaddy 4.9.4

**Comment by ViorelEremia** [comment]
It's a theme issue, please contact the theme author.
Unyson is a plugin that allows theme authors to create fast and easy WordPress themes. Some of the issues come from themes.
