### ISSUE TITLE
Database restore: Failed  duplicated entry

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3213]
DB restore fails 

![screenshot_20](https://user-images.githubusercontent.com/2340172/36633104-c766dd70-198f-11e8-8c4b-aa9839c5fbed.jpg)

DB has only one entry but the sql 2 

![duplicated_entry](https://user-images.githubusercontent.com/2340172/36633107-cfebbe48-198f-11e8-9a2c-34c34b903d22.jpg)

**Comment by danyj** [comment]
if you pay close attention it inserted wrong  tax ID

![screenshot_21](https://user-images.githubusercontent.com/2340172/36633134-5299545e-1990-11e8-9cba-231d03b5bf15.jpg)

**Comment by ViorelEremia** [comment]
I checked the code that exports rows I do not see anything that could generate duplication of the rows. I tested content backup with big db I have no duplicate rows. How can I get that?

**Comment by danyj** [comment]
> How can I get that

I dont know  the images above show the issue ,  I manually changed the SQL and restore/demo proceeded

**Comment by ViorelEremia** [comment]
can you try this commit

**Comment by danyj** [comment]
will do

**Comment by danyj** [comment]
just had this again , doing new test now

**Comment by danyj** [comment]
fix works , issue update please

**Comment by danyj** [comment]
@ViorelEremia  while the fix works I think it is just patching the error not to be trown not fixing the bug 

the bug is that backup process is mixing up the ID's as advised here 

https://github.com/ThemeFuse/Unyson/issues/3213#issuecomment-368244472

**Comment by danyj** [comment]
and the demo I made was just created couple min ago and the backup process still mixed the ID's up

**Comment by ViorelEremia** [comment]
I checked the code and I can not imagine how this could happen. The export to json is happening here: https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-db-export.php#L223 it is a simple extract of rows like ```SELECT * FROM wp_term_relationships ORDER BY object_id LIMIT 0,100```
Can you send me the ftp credentials? or if that is not possible can you try to inspect here what is happening

**Comment by danyj** [comment]
In few days il give you DB but this is  unbelivaleble ,  

actual DB values

![image](https://user-images.githubusercontent.com/2340172/40588943-7b477a00-61e5-11e8-9546-eb6f61515859.png)



exported json 

![image](https://user-images.githubusercontent.com/2340172/40588938-609a4b56-61e5-11e8-81aa-f7c0567ba311.png)

**Comment by danyj** [comment]
@ViorelEremia  Dimi has the theme now ,   please install 

Clean ( developer demo ) ,  

![screenshot_17](https://user-images.githubusercontent.com/2340172/41410889-35b3fd16-6fdb-11e8-8009-be172f3581c1.jpg)



than do demo export/backup for it and  try to import , 
it is always same bug on same term_taxonomy_id

**Comment by danyj** [comment]
and that term ID 106 is WooCommerce related

**Comment by ViorelEremia** [comment]
Ok, I imported demo data(developer demo), then I created a content backup, then I restored the backup and I don't see any issue, everything is the same before import/export, my debug is clean. In the file json I have:
```
{"type":"row","data":{"table":"term_relationships","row":{"object_id":"106","term_taxonomy_id":"5","term_order":"0"}}}
{"type":"row","data":{"table":"term_relationships","row":{"object_id":"106","term_taxonomy_id":"29","term_order":"0"}}}
{"type":"row","data":{"table":"term_relationships","row":{"object_id":"106","term_taxonomy_id":"54","term_order":"0"}}}
{"type":"row","data":{"table":"term_relationships","row":{"object_id":"106","term_taxonomy_id":"111","term_order":"0"}}}
{"type":"row","data":{"table":"term_relationships","row":{"object_id":"106","term_taxonomy_id":"115","term_order":"0"}}}
{"type":"row","data":{"table":"term_relationships","row":{"object_id":"106","term_taxonomy_id":"117","term_order":"0"}}}

```
this is fine, and in db also is fine:
![screenshot from 2018-06-21 15-15-30](https://user-images.githubusercontent.com/28967378/41718637-2dc86322-7566-11e8-93e7-4d655d55ff5f.png)

**Comment by danyj** [comment]
and you were able to install the demo ?

**Comment by danyj** [comment]
strange , I have that one demo on local and every time I export I have to go in sql file and change the values. I am not sure what to do at this point. If I pack the demo and give it to you you can only see install error for dup entry ,

**Comment by danyj** [comment]
do you want me to give yo the full demo SQL dump from DB and than you try to create demo ?

**Comment by ViorelEremia** [comment]
Ok, send it to my email: ```viorel@themefuse.com```

**Comment by danyj** [comment]
sent, thank you!  added drop if exists in export
