### ISSUE TITLE
Image sizes restore and WooCommerce

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3214]
This is continuence of this https://github.com/ThemeFuse/Unyson/issues/2664   and this https://github.com/ThemeFuse/Unyson/issues/3081

but must separate it to get a clear anwser and instruction for everyone. 

If you did not noticed , even if you do not add image sizes in theme via `add_image_size`
but you have Woo Commerce  in the demo you will end up with 7 additional image sizes 

```
			'shop_thumbnail',
			'shop_catalog',
			'shop_single',
			'woocommerce_thumbnail',
			'woocommerce_single',
			'woocommerce_gallery_thumbnail',
			'woocommerce_thumbnail_2x',
```

add to that the "invisible" new default size `medium_large` and you have additional **8** images that are being created on demo content install/db restore. 

@andreiglingeanu  @ViorelEremia 

can we somehow hook in to the image sizes restore and tell what image size to create, or unset ( preferred )  the ones above just for the restore process ?

**Comment by danyj** [comment]
can I please get a hint

**Comment by ViorelEremia** [comment]
You want a hook here: https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-image-sizes-restore.php#L112 
so you can delete any of the sizes?

**Comment by danyj** [comment]
yes , so that we can just allow specific sizes to be made on demo install

**Comment by ViorelEremia** [comment]
Try

**Comment by danyj** [comment]
will do , but I would change the name to 

`fw_ext_backups_restore_exclude_img_sizes`

this 

`fw_ext_backups_exclude_img_sizes
`

sounds like we are excluding them when we are doing the backup

**Comment by ivandotv** [comment]
@danyj 
I'm a little bit confused, haven't worked with demo content yet.
So, if you use this filter, and disable woocommerce images, how is woocommerce going
to get preferred image sizes?

**Comment by danyj** [comment]
>  how is woocommerce going to get preferred image sizes?

I am not sure how you have setup your woo or theme but the way I did is if we are calling specific image size and the size exists in `get_intermediate_image_sizes `but the image is not there , the function recreates it

is kinda like `fw_resize` but it looks for get_intermediate_image_sizes also

**Comment by danyj** [comment]
on my end all image_src are coming from global function this way I can manipulate, recreate or show placeholder if needed

**Comment by ViorelEremia** [comment]
I quickly created a small function that creates the size of the image if not exists:
```
function prefix_img_url( $id, $img_size ) {

	$img = wp_get_attachment_image_src( $id, $img_size );

	if ( ! strpos( $img[0], implode( 'x', array( $img[1]['width'], $img[2] ) ) ) ) {

		if ( ! function_exists( 'wp_crop_image' ) ) {
			include( ABSPATH . 'wp-admin/includes/image.php' );
		}

		wp_update_attachment_metadata( $id, wp_generate_attachment_metadata( $id, get_attached_file( $id ) ) );

		return prefix_img_url( $id, $img_size );
	}

	return $img[0];
}
```
or you can handle that function to a hook from wp like ```wp_get_attachment_image_src```

**Comment by danyj** [comment]
@ivandotv  there you go

**Comment by danyj** [comment]
on it now

**Comment by danyj** [comment]
Works perfectly!

tested with 

```
function _thz_filter_demo_install_exclude_img_sizes( $sizes ) {
	
	return array('thumbnail');

}

add_filter( 'fw_ext_backups_exclude_img_sizes', '_thz_filter_demo_install_exclude_img_sizes' );
```

only thumbs were created and restore took 30sec for 500 images

**Comment by ivandotv** [comment]
@danyj 
If I understand this process correctly, you should exclude **all** image sizes. There is no need for images
to be generated again, they are all contained in the backup?

**Comment by danyj** [comment]
@ivandotv ,  no , I did that ( no sizes restore  )  with another hook for specific demos only

```
/**
 * Disable demo image sizes restore
 * https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/15
 * https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/30
 */
if ( ! function_exists( '_thz_filter_disable_demo_img_sizes_restore' ) ) {
	function _thz_filter_disable_demo_img_sizes_restore( $do, FW_Ext_Backups_Task_Collection $collection ) {
		
		$demos_list = _thz_get_demos_list();
		
		if (
			$collection->get_id() === 'demo-content-install'
			&&
			($task = $collection->get_task('demo:demo-download'))
			&&
			($task_args = $task->get_args())
			&&
			isset($task_args['demo_id'])
			&&
			isset($demos_list[$task_args['demo_id']]['sizes_removal'])
			&&
			$demos_list[$task_args['demo_id']]['sizes_removal'] === false
		) {
			$do = false;
		}
	
		return $do;
	}
}
add_filter('fw:ext:backups:add-restore-task:image-sizes-restore', '_thz_filter_disable_demo_img_sizes_restore', 10, 2);
```

`fw_ext_backups_exclude_img_sizes  `is just for demos that are allowed resize restore  but we need to make sure that we dont get 10 image sizes restored but only the ones we need

**Comment by danyj** [comment]
demos list than says if we should or shouldn't do resize


```
/**
 * List of full demos
 */
function _thz_get_demos_list(){
	
    $demos_list = array(

        'clean' => array(
            'title' => esc_html__('Title', 'creatus'),
            'screenshot' => 'IMG URL',
            'preview_link' => 'https://clean.creatus.io',
	    'sizes_removal'	=> false
        ),
		

    );	
	
	return $demos_list;
	
}
```

**Comment by ivandotv** [comment]
@danyj That code can be in `functions.php` of the theme that is being restored?
Also, how does unyson extension behaves with multisite?
Does it backups the whole uploads directory or just the uploads directory of the site I want to backup?

**Comment by danyj** [comment]
> That code

is in the theme hooks.php


not sure about multisite @ViorelEremia  should know more about it

**Comment by ViorelEremia** [comment]
@ivandotv everything is fine with extensions on multisite. About backups, it clones the entire uploads folder.

**Comment by ivandotv** [comment]
@ViorelEremia So basically I can't do a backup on multisite, because it downloads assets from all sites in the network?
This can be gigs of data

**Comment by ViorelEremia** [comment]
@ivandotv everything is fine with backup on multisite I was wrong about backup clones the entire uploads. It clones only the current site, not all sites.
