### ISSUE TITLE
Demo download config overwritten in backup 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3215]
According to the config instructions for demo downloads 

https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/download/type/piecemeal/server/index.php#L22

we should be able to overwrite this 

 https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/e84912c9fcb2b8c6f744c5bf0a2d11d3bcd1225f/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php#L93

I would like to increase the 3MB in 23sec limit

**Comment by danyj** [comment]
Manual 
http://manual.unyson.io/en/latest/extension/backups/index.html#create-demos

http://prntscr.com/im8w79

**Comment by danyj** [comment]
the peacemeal is in the backup extension , you see the link


https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php

**Comment by danyj** [comment]
the filter you ref , how is it used , 

I dont understand the point of the size key in this $cfg  here 

https://raw.githubusercontent.com/ThemeFuse/Unyson-Backups-Extension/master/includes/module/tasks/type/download/type/piecemeal/server/index.php

please give detail instructions because manual does not have any of this info

**Comment by ViorelEremia** [comment]
Meaning of this value is to download the demo zip without going beyond the maximum value of the maximum execution time when user server downloads demo zip archive. User's server requests only a piece of 3mb from demo zip archive and in the first step, the position of the file is zero your server receives this request and checks what size must return and return only 3mb from zip ```$data = fread($f, $cfg['size'])``` in the header is returned the current position of the file zip ```header('X-Position: '. ($data_length ? ($position + $data_length) : '-1'));``` next request user server sends again all params and now we have another position indicator of the file that is set by your server via function fseek:
```
if (-1 === fseek($f, $position)) {
    header('HTTP/1.1 500 Internal Server Error');
    exit;
}
```
I don't think you must change this value because 3mb is a reasonable value so by increasing this value you can pass the max execution time. We also use this script and we never had any issues.

**Comment by danyj** [comment]
OK but can you please  explain how to use this 

https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php#L119

because I did not see where these arg are used in the demos array setup 


```
					$default_query_args = array(
						'id' => urlencode($args['file_id']),
						'position' => $state['position'],
						'size' => $state['piece_size']
					),
```

**Comment by ViorelEremia** [comment]
These args are not from some configs they are hardcoded. The download is a task object so it is executed multiple times when is hapening demodata import. What you want to do? you want to send other values on download like username etc?

**Comment by danyj** [comment]
> What you want to do?

I just want to raise the download step  limit to 6

currently slowest measured network speed is 6mb / sec

https://www.fastmetrics.com/internet-connection-speed-by-country.php

we are to slow on the downloads and I want it to be faster

**Comment by ViorelEremia** [comment]
On your server ignore user size request remove this if: https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/download/type/piecemeal/server/index.php#L64
and add here 6: https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/download/type/piecemeal/server/index.php#L22
should work

**Comment by danyj** [comment]
I did exactly that  
http://prntscr.com/innb1w

thus I said it does not work

**Comment by danyj** [comment]
ah , wait no I did not remove the if ,  will do than report back , thnx
