### ISSUE TITLE
Unyson Page Builder not working problem

### ISSUE THREAD

**Issue by MVBravo** [ThemeFuse/Unyson#3217]
Unyson Page Builder stopped working properly and now I just see one "text" block. 

I tried many things but no results:
-Re-activated and Re-installed some plugins and Wordpress. Reinstalled Unyson.
-Cleared Cache everywhere
-Updated some server items for higher capacity
-Added a backup (public_html2) for weeks ago when the website was working fine but the same problem occurs.

![image](https://user-images.githubusercontent.com/36825332/36646197-7a36626a-1a42-11e8-9cc9-a97268d518c5.png)

**Comment by ViorelEremia** [comment]
I know about that issue but I can't understand when is happening and how.
Send me some temporary credentials (admin) I will try to restore your content: ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by MVBravo** [comment]
I simply used prior revisions to restore. Solved.

**Comment by ViorelEremia** [comment]
You use an old backup version: https://github.com/ThemeFuse/Unyson-Backup-Extension we no longer support it.
You have to delete the current version of backup and install our new backup version: https://github.com/ThemeFuse/Unyson-Backups-Extension

**Comment by MVBravo** [comment]
I wasn't able by looking at the link to update the backup extension.

Can it be updated from within WP?
How do I see version I am using and most updated version source?

Thank you

**Comment by ViorelEremia** [comment]
You must ask the author of your theme. But you can try to remove it from server site and install again from unyson page extensions list, after that on your server you must check for folder backups in path ```wp-content/plugins/unyson/framework/extensions/backups/``` also you can check the file manifest.php from that folder if you have line ```$manifest['version'] = '2.0.26';``` then everything is fine. If after install from unyson extensions list you have another version it results that the theme author has rewritten the list of extensions.
