### ISSUE TITLE
Display error on Chrome browser after updating WordPress and Unyson 

### ISSUE THREAD

**Issue by erraticeuphoria** [ThemeFuse/Unyson#3218]
I'm having a display error (content alignment) on my site after updating Wordpress version (4.9.4) and Unyson (2.10) page builder. However it only occurs on Chrome browser, i've checked with Edge / Firefox, the display turned out OK.

Proper view
![metadata-unyson02](https://user-images.githubusercontent.com/36848348/36670621-793b63d0-1b2b-11e8-8937-7c4e7c45cb99.jpg)

Improper view
![metadata-unyson01](https://user-images.githubusercontent.com/36848348/36670623-797373f6-1b2b-11e8-9ef8-c995481f935a.jpg)

Can anyone help me figure out what's the issue?

Thanks!

**Comment by danyj** [comment]
contact theme provider, this is framework git

**Comment by ViorelEremia** [comment]
It's a theme issue, please contact the theme author.
Unyson is a plugin that allows theme authors to create fast and easy WordPress themes. Some of the issues come from themes.
