### ISSUE TITLE
Why  are we loading page HTML in backend?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3219]
I tought we had revisions for this but seems like we load complete page HTML in 
backend together with the builder 

http://prntscr.com/ik6a7k

is this because of Yoast ?

https://github.com/ThemeFuse/Unyson/issues/2129
https://github.com/ThemeFuse/Unyson/issues/845

if yes can we please   check if the Yoast is installed and only than do this. Or find a solution not to overload backend with this.

**Comment by ViorelEremia** [comment]
I think that is right. There are many wordpress seo plugins, so we must add a big array with plugins slugs to check them on each request. If you want to change that you need to check with all wp seo plugins or use this hook: ```apply_filters('fw:ext:page-builder:generate-post-content-html', true, $post_id)```
