### ISSUE TITLE
Just updated and got some error with response time again

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#322]
An automated WordPress update has failed to complete - please [attempt the update again now].

**Comment by moldcraft** [comment]
Why do you think this is related to Unyson?

**Comment by thednp** [comment]
I don't know for sure, perhaps maintenance mode kicked in and didn't wake up, but wait there's more: now I got 2 MegaMenu extensions, clicked the second to activate and VOILA

Fatal error: Cannot redeclare class FW_Ext_Mega_Menu_Admin_Walker in D:\xampp-portable\htdocs\wp\unyson\wp-content\themes\scratch-parent\framework-customizations\extensions\megamenu_full\includes\class-fw-ext-mega-menu-admin-walker.php on line 253

**Comment by moldcraft** [comment]
[We didn't have](https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-parent/framework-customizations/extensions) `scratch-parent\framework-customizations\extensions\megamenu_full`

**Comment by thednp** [comment]
Well, we use what we got and we got what we got from you :)

When do we have an update on the good old scratch? When do we have the new?

**Comment by thednp** [comment]
OH no, please disregard, it is my own copy paste there, just I don't know why it triggered this issue.

Anyways, not your fault :+1:
