### ISSUE TITLE
Spacing is all wrong

### ISSUE THREAD

**Issue by tpaul25** [ThemeFuse/Unyson#3220]
I'm setting up a page as normal. When I go to view it, the spacing is completely off. What's going on? Here is what the admin of the page looks like:
![image](https://user-images.githubusercontent.com/36909065/36769116-20a7928a-1bf7-11e8-8192-f8c989012f9d.png)

Here is what it looks like on the front end:
![image](https://user-images.githubusercontent.com/36909065/36769135-3f04d490-1bf7-11e8-9c52-6405165db36d.png)

The image is too far to the left. The space between the copy and the button is too much. I have no spacer modules between the text and the button.

There are several other pages on the site that seem to work correctly. I've looked for CSS classes added to the pages but there is nothing. I'm using FlyCoffee theme as the child. What gives? Any help would be appreciated.

**Comment by ViorelEremia** [comment]
It's a theme issue, please contact the theme author.
Unyson is a plugin that allows theme authors to create fast and easy WordPress themes. Some of the issues come from themes.
