### ISSUE TITLE
Update extension through BitBucket or GitLab

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#3222]
Hi,

Lately, we've been looking into developing Unyson extensions for the first time. For distributing updates I only see options for GitHub by using $manifest['github_update'] and $manifest['github_repo'].

Normally we're using BitBucket as our version control system, so the question is: is it also possible to update extensions through BitBucket? And what about GitLab?

**Comment by ViorelEremia** [comment]
http://manual.unyson.io/en/latest/extensions/cookbook.html

**Comment by warudin** [comment]
Hi ViorelEremia,

I guess you are referring to `'source' => 'custom'`?
That approach doesn't really apply to BitBucket/GitLab, or am I missing something here?

**Comment by ViorelEremia** [comment]
No, custom is for your own server. For BitBucket/GitLab you must create your own update type. Create a child extension for extension update: http://manual.unyson.io/en/latest/extensions/introduction.html#child-extensions
Create a class that extends class [FW_Ext_Update_Service ](https://github.com/ThemeFuse/Unyson/blob/master/framework/extensions/update/includes/extends/class-fw-ext-update-service.php)exemple: https://github.com/ThemeFuse/Unyson/tree/master/framework/extensions/update/extensions/custom-update
or https://github.com/ThemeFuse/Unyson/tree/master/framework/extensions/update/extensions/github-update
They are child extensions for extension update.

**Comment by ViorelEremia** [comment]
if everything is clear close the issue

**Comment by warudin** [comment]
OK, thanks for answering and good to know. I solved it for now by using [GitHub Updater](https://github.com/afragen/github-updater). This seemed the easier way to go for now.

**Comment by notrealdev** [comment]
Hi, i'm also stuck here, how can I download and update my  extension via bitbucket repository ( public )?

**Comment by warudin** [comment]
As long as Unyson doesn't support repository management sites other than GitHub, I'd recommend using the above mentioned GitHub Updater plugin.

That's not to say that it'd be very nice if Unyson would also support BitBucket and GitLab.

**Comment by ViorelEremia** [comment]
@notrealdev check the bitbucket/gitlab API docs and paste here the url for fetching the latest version of a repository and the url for download the latest version of a zip archive after I will check if it is possible to adapt the custom download class to work with this services. About the private repository, I don't know if that is possible usually they required an authentification that you must paste into the theme or extension so if your user has your premium theme there is no reason to keep the extension as a private repository.

**Comment by notrealdev** [comment]
Hi again, the latest tag
https://bitbucket.org/maurisvn/ht-tours/get/1.0.7.zip

**Comment by ViorelEremia** [comment]
So how unyson should know that is the latest tag? I must know that is the latest tag to compare with the currently installed version; if bitbucket tag is bigger than currently installed version when is starting the update. On install extension also unyson must know which is the latest tag to download it.

**Comment by warudin** [comment]
@notrealdev, you must add some tag like 'latest' to your repo and then move that tag every time you release a stable version. That way the link to the newest stable version will stay the same.

So it will become something like:
https://bitbucket.org/maurisvn/ht-tours/get/latest.zip

**Comment by notrealdev** [comment]
Because Unyson not supported Bitbucket (or i have not figured out the solution), I am updating my plugin manually through TGM plugin.
```php
array(
    'name'               => esc_html__( 'HT Tours', 'tour' ),
    'slug'               => 'ht-tours',
    'source'             => 'https://bitbucket.org/maurisvn/ht-tours/get/1.0.7.zip',
    'required'           => true,
    'version'            => '1.0.7'
),
```
// quite inconvenient 😄

**Comment by warudin** [comment]
And that way you'll also need to update the url in 'source' every time you'lll release a new version, right? So that's why you should use a 'latest' tag in your repository. ;)

**Comment by notrealdev** [comment]
Yes, i have not figured out the solution

**Comment by ViorelEremia** [comment]
Guys, guys why so hard to understand that. No need to have three urls or more the requires urls are two one for extract latest tag release and another is url for download zip usually is something like that ```serviceUrl/tagRelease.zip```(for bitbucket we have it ```https://bitbucket.org/maurisvn/ht-tours/get/1.0.7.zip```). In this way is working almost of programs what have updater. So the program check is there a new tag via the latest tag url so the program check via compare is the currently installed version is lowest than version extracted from git servers then it builds the url for the new tag zip and it starts to download it. On installation extension is the same way unyson check for the latest release after build the url for the zip and starts to download, install etc. That is the way how updater works for all programs. So I do not have time to read the gitlab/bitbucket docs for how I can extract the latest release tag That is why I divided this task: a part(url) you and the part of the implementation I

**Comment by warudin** [comment]
I tested this with another repo on BitBucket (I have no public repo's) and this should be the download link if a tag called 'latest' is used for the repo:
https://bitbucket.org/maurisvn/ht-tours/get/latest.zip

But first for this to work @notrealdev actually has to add this tag to a commit. Alternately he/she could give me access (dominique@noesteijver.nl) to that repo so I can do it for him.

**Comment by notrealdev** [comment]
Hi, what do I do if I want to update to a newer version?

**Comment by ViorelEremia** [comment]
@notrealdev try(first of all pull all changes from unyson github): 
theme/framework-customizations/theme/available-extensions.php
```
<?php defined( 'FW' ) or die();

$extensions = array(
	'test' => array(
		'display'     => true,
		'parent'      => null,
		'name'        => __( 'Test', 'fw' ),
		'description' => __( 'Extension description test.', 'fw' ),
		'thumbnail'   => 'pathToThumbnail/thumbnail.jpg',
		'download'    => array(
			'source' => 'bitbucket',
			'opts'   => array(
				'user_repo' => 'eremia_viorel/test',
			),
		),
	),
);
```
Extension manifest:
```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$manifest = array();

$manifest['name']        = __( 'Text Extension', 'fw' );
$manifest['description'] = __( 'Description test ext', 'fw' );
$manifest['bitbucket'] = 'eremia_viorel/test';
$manifest['author'] = 'viorel';
$manifest['version'] = '1.2.3';
$manifest['display'] = true;
$manifest['standalone'] = true;
```

**Comment by notrealdev** [comment]
Hi @ViorelEremia, thank for your reply.
Seems the code does not work
```php
$extensions = array(
    'test' => array(
        'display'     => true,
        'parent'      => null,
        'name'        => esc_html__( 'Test', 'goto' ),
        'description' => esc_html__( 'Extension description test.', 'goto' ),
        'thumbnail'   => 'dashicons-palmtree',
        'download'    => array(
            'source' => 'bitbucket',
            'opts'   => array(
                'user_repo' => 'maurisvn/ht-tours',
            ),
        ),
    ),
);
```

But the below code works
```php
$extension = new FW_Available_Extension();
$extension->set_title( esc_html__( 'HT Tours', 'goto' ) );
$extension->set_name( esc_html__( 'HT Tours', 'goto' ) );
$extension->set_description( esc_html__( 'Tour management system plugin', 'goto' ) );
$extension->set_thumbnail( 'fa fa-user' );
$extension->set_download_source(
    'bitbucket',
    array(
        'user_repo' => 'maurisvn/ht-tours'
    )
);

$register->register( $extension );
```

But can not to activate extension ( Unyson has downloaded my extension in my theme )
```
Install Compatible Extension
Downloading the "HT Tours" extension...

Installing the "HT Tours" extension...

The HT Tours extension has been successfully installed.

Activating extension...

Extension "HT Tours" does not exist.
```

My manifest.php file
https://bitbucket.org/maurisvn/ht-tours/src/master/extensions/tour/manifest.php

Maybe I'm missing something...

**Comment by ViorelEremia** [comment]
I test with your repository is working with both methods. Your file hierarchy is not right you have a plugin, not an extension this is why it does not activate. Try again.
>  Unyson has downloaded my extension in my theme

Unyson does not download it in the theme but in ``plugins/unyson/framework/extensions/``

**Comment by ViorelEremia** [comment]
https://wordpress.stackexchange.com/questions/4520/incompatible-archive-pclzip-err-bad-format-10/43785?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by ViorelEremia** [comment]
Today or tomorrow will be a pre-release.

**Comment by ViorelEremia** [comment]
That is a prerelease today will be a new version of unyson
