### ISSUE TITLE
Ups! we found an error Could not send the email

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#3223]
I can't send any mail. When I tried to send I am receiving this error "Ups! we found an error Could not send the email"

If I check console network tab same error showing there as well.

![screen shot 2018-02-28 at 8 54 43 pm](https://user-images.githubusercontent.com/6223399/36794164-c9b3bcd2-1cc9-11e8-97a8-470c8f429ca7.png)

Can you please help me to fix this issue.

**Comment by xperter** [comment]
I have also faced the same issue. But it was working fine before.

**Comment by ViorelEremia** [comment]
Unyson dosent have this error message also I see it is done by ajax check on your server from where it comes because as it sounds does not help us to understand what is the issue

**Comment by Ataurr** [comment]
@ViorelEremia  This is modified failure message from contact form settings.

If you want I can share login details via mail.

Please help us to fix this.

Thanks
