### ISSUE TITLE
Post Excerpt Messed Up

### ISSUE THREAD

**Issue by username202** [ThemeFuse/Unyson#3224]
website:  www.mihaipuscas.com
-Post excerpt is replaced with un-enclosed javascript. I am using jevelin theme, the developer said the issue comes from unyson.
-Is there a way to downgrade to an older version ? I am currently on the latest wordpress, jevelin theme and unyson plugin. Are you going to release an update soon ?

**Comment by ViorelEremia** [comment]
It is not clear what is happening.
Send me some temporary credentials admin: ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
It is a theme issue, your theme author sent you here without checking what is happening. Issue is in file ```jevelin/content.php``` line 163 code: ```<?php echo wp_trim_words( get_the_content() , '17' ); ?>``` in all elseifs everything is fine it is ```the_excerpt();```. Please contact theme author and tell him to check before sending his clients here.
