### ISSUE TITLE
What version of woo-commerce is Unyson compatible with?

### ISSUE THREAD

**Issue by brucec111** [ThemeFuse/Unyson#3225]
The problem i have been seeing with Unyson websites is that it doesn't keep up being compatible with woo-commerce updates.   At least from most templates i have seen are always 2 or more versions old from woo-commerce because of compatibility issues between unyson and woo-commerce.   Or is it a theme make r issue not keeping theme updated.   Before i start making my own themes using Unyson i need to know about updates and compatibility with woo-commerce.  Because all of my projects are ecommerce and cant afford to have compatibility issues.

Thanks
Bruce Carroll

**Comment by danyj** [comment]
theme devs are responsible for theme updates not Unsyon. Contact your theme provider please.

**Comment by brucec111** [comment]
Yes but what version of woocommerce is compatible with Unyson ?

Bruce Carroll

**Comment by danyj** [comment]
All.  There is no special shortcode or style for it so it is supported by any WC version.
