### ISSUE TITLE
Translation Switches from EN to RO when pressing the Contact page from MENU

### ISSUE THREAD

**Issue by stefanwebdevity** [ThemeFuse/Unyson#3228]
Hi there!

So, i installed Translate press plugin. I used it before, and i thank you for that.

I used it on this website today: http://cmplaw.ro
Everything works great, and if i switch from RO to EN, the site is translated as necessary. 
 But when I press the 'contact' menu button, the site switches automatically from EN to RO.
I then have to manually switch from RO to EN, so that the CONTACT page shoul be in EN.

Please advise!

Thanks a lot!

**Comment by ViorelEremia** [comment]
Hi, please open an issue here: https://wordpress.org/support/plugin/translatepress-multilingual
