### ISSUE TITLE
Date time picker range issue with specific time 

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#3229]
Hi! It's weird that the date time picker range doesn't support specific time
like we can only select 2.00am and how about 2.30, 2.15
Can we custom it? 
Thanks!

**Comment by duongancol** [comment]
Thank you for the fast solution. I'll test ti.

**Comment by duongancol** [comment]
Hi! One more question, How can I apply this change to Event extension?
I need to edit the Date time field in an event.

**Comment by ViorelEremia** [comment]
Yes, you can.
