### ISSUE TITLE
Also, I would like two languages for my website, so will it be hard? (+ Calendar)

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson#323]
Also, I would like two languages for my website, so will it be hard? (+ Calendar)

https://github.com/ThemeFuse/Unyson-Events-Extension/issues/4#issuecomment-77415188

**Comment by sergiubagrin** [comment]
It is possible to add 2 or more languages with a specific plugin like WPML or Polylang

**Comment by Nic787** [comment]
ok so it's possible to change the language for another page without changing the default language?

Thank you very much.

**Comment by sergiubagrin** [comment]
> ok so it's possible to change the language for another page without changing the default language?

With WPML or Polylang it is possible to add more than one language to your project. Each page can be cloned in a new language. 

P.S. This questions is not related to Unyson framework.

**Comment by Nic787** [comment]
Ok thank you. I was just trying to know if I need to touch something in the Unyson files to change the language. I will try with WPML thank you :)
