### ISSUE TITLE
Font Awesome Pro 5

### ISSUE THREAD

**Issue by yanickvanbarneveld** [ThemeFuse/Unyson#3230]
I am trying to add Font Awesome 5 Pro to the Uyson icon-v2 option type. But the new Font Awesome has multiple prefix classes such as:
```
<i class="far fa-address-card"></i>
<i class="fab fa-wheelchair"></i>
<i class="fas fa-address-card"></i>
```
I am inserting the icons as following and most of them are found. But ofcourse some dont work because the prefix class:

```
function _action_theme_add_icons($default_packs) {
    return array(
      	'fontawesome' => array(
        	'name' => 'fontawesome',
        	'title' => 'Font Awesome 5',
        	'css_class_prefix' => 'fa',
        	'css_file' => get_template_directory() . '/assets/styles/vendors/fontawesome.min.css',
			'css_file_uri' => get_template_directory_uri() . '/assets/styles/vendors/fontawesome.min.css',
		)
  	);
}

add_filter('fw:option_type:icon-v2:packs', '_action_theme_add_icons');
```

Anyone else managed to do this correctly?

**Comment by danyj** [comment]
well that was dumb from them , should have prefixed the "pro" with fapro or fap

looks like you will have to separate them in multiple packs and add the prefix for each
