### ISSUE TITLE
 cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by mnks** [ThemeFuse/Unyson#3231]
Cannot download the "Media" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Cannot download the "Shortcodes" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Cannot download the "SEO" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Cannot download the "Backup & Demo Content" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Cannot download the "Forms" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Cannot download the "Mailer" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Cannot download the "Analytics" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Cannot download the "Media" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by ViorelEremia** [comment]
Update your OpenSSL to 1.0.2, if this will solve the problem close the issue.

**Comment by mnks** [comment]
Any Manual performance?
because It is on shared hosting,it will take much time.

**Comment by ViorelEremia** [comment]
Go to localhost install all unyson extensions move everything from localhost/wp-content/plugins/unyson/framework/extensions to the same path on your server and run this code:
```
update_option( 'fw_active_extensions', json_decode( '{"blog":[],"update":[],"github-update":[],"shortcodes":[],"page-builder":[],"editor-shortcodes":[],"builder":[],"forms":[],"contact-forms":[],"mailer":[],"wp-shortcodes":[],"sidebars":[],"media":[],"slider":[],"owl-carousel":[],"bx-slider":[],"nivo-slider":[],"population-method":[],"population-method-categories":[],"population-method-custom":[],"population-method-tags":[],"population-method-posts":[],"social":[],"social-twitter":[],"social-facebook":[],"seo":[],"seo-webmasters":[],"seo-sitemap":[],"seo-titles-metas":[],"events":[],"events-tags":[],"megamenu":[],"breadcrumbs":[],"backups":[],"backups-demo":[],"portfolio":[],"analytics":[],"feedback":[],"feedback-stars":[]}', true ) );
```

**Comment by mnks** [comment]
Thanks @ViorelEremia 
It worked 👍

**Comment by JacobMakau** [comment]
Hi @ViorelEremia one quick one, where do I run this code? In my command line?

**Comment by ViorelEremia** [comment]
@JacobMakau you can paste it into functions.php and refresh any page from your site admin or frontend

**Comment by JacobMakau** [comment]
Thank you @ViorelEremia

**Comment by ViorelEremia** [comment]
Don't forget to remove it after refresh

**Comment by JacobMakau** [comment]
Alright, I sure will...thanks!

**Comment by JacobMakau** [comment]
Hi @ViorelEremia so, I tried the above and it did not work. At some point, I even thought cURL is disabled, but I have confirmed with the hosting company that it is enabled.
Can I give you the CPanel credentials you check this out for me? I am at a dead end...please!

**Comment by ViorelEremia** [comment]
drop them here: ```viorel@themefuse.com```

**Comment by JacobMakau** [comment]
Done so... thanks!

**Comment by ViorelEremia** [comment]
There are two solutions to solving this problem:

1. Update your OpenSSL to 1.0.2, if this will solve the problem close the issue.
2. Check the php version; some servers use a too old version of php usually 5.2.

**Comment by JacobMakau** [comment]
Updating php worked! 

Thanks a bunch. Cheers!

**Comment by p-burnet** [comment]
Hi, I have the same problem, but I'm a beginner so I don't know how to resolve it. First, my website is localhost. Normally, my php version is already updated (version 7.0.8.). And for the OpenSSL I don't know how to update it. Can you help me @ViorelEremia ?

**Comment by ViorelEremia** [comment]
@p-burnet what os do you have?

**Comment by ViorelEremia** [comment]
@p-burnet If you are a beginner use prebuild server installation like xampp or wampp they already have everything installed. Later you will understand how to do everything yourself.

**Comment by p-burnet** [comment]
I have OS Sierra. 
I already have a server called MAMP. So I think it's already installed no?

**Comment by ViorelEremia** [comment]
Did you try these steps?: https://stackoverflow.com/questions/32431465/mamp-ssl-error-error14077410ssl-routinesssl23-get-server-hellosslv3-alert?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa#answer-32431466

**Comment by p-burnet** [comment]
So I tried but it was a little bit difficult. So I deinstalled MAMP and reinstalled with the newest version, and it worked. Thanks so much, @ViorelEremia.

**Comment by OOMMYY** [comment]
I solved this by updating the curl. (place check the curl version and openssl version, they may not match)

curl 7.12.1 need OpenSSL/0.9.7a  but my OpenSSL is 1.0.2m.

details:
`~ $ curl -V
curl 7.12.1 (x86_64-redhat-linux-gnu) libcurl/7.12.1 OpenSSL/0.9.7a zlib/1.2.1.2 libidn/0.5.6
Protocols: ftp gopher telnet dict ldap http file https ftps
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
~ $ openssl version
OpenSSL 1.0.2m  2 Nov 2017`
