### ISSUE TITLE
Linking elements 

### ISSUE THREAD

**Issue by ricardososa8** [ThemeFuse/Unyson#3233]
Hi guys! 

I need to create a page with just one element (Countdown). But what I really want is when someone edit the page changing the date, this change the same element in another page. Why? Because I´m going to hide the pages because final users always change something and crack the page, but they need to change some elemental information as the date of the counter. What I want is to create a link between elements of the same type. Actually I need replicate dat of just two elements Countdown and Timeline.

Thanks in advance

**Comment by ViorelEremia** [comment]
Are you a developer? I gave you all the information how you can do it here: https://github.com/ThemeFuse/Unyson/issues/3216, all you have to do is just adapt it to your code, get some prints of jsons, analyze, etc. We can't know what code you have, user role, etc ... there is a lot of work to do. If you have no knowledge of php with wordpress you can't do that.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
