### ISSUE TITLE
multiple choices - contact form - UNYSON

### ISSUE THREAD

**Issue by dkrumpar** [ThemeFuse/Unyson#3234]
Hello,

sorry for asking newbie question, I have a contact form listed here:

"**<fieldset class="register-form">
<div class="col md-round">
<i class="fa fa-user"></i>[text* full-name class:form-control id:full-name class:text-uppercase placeholder "Vaše meno"]
</div>

<div class="col md-round"><i class="fa fa-envelope"></i>[text* email id:email class:form-control class:text-uppercase placeholder "Váš email"]</div>

<div class="col md-round"><i class="fa fa-list"></i>[select* menu-862 id:package class:text-uppercase class:jcf "Termín" "15.6. - 25.6." "26.6 - 5.7." "6.7. - 15.7."]</div>

<div class="col md-round"><i class="fa fa-list"></i>[select* menu-862 id:package class:text-uppercase class:jcf "Mesto zájazdu" "Len v 1 meste" "1-2 mestá" "3 a viac miest"]</div>

<div class="col md-round"><i class="unycon unycon-office-chair"></i>[text* seats id:seats class:form-control class:text-uppercase placeholder "Počet osôb"]</div>

<div class="col md-round"><i class="fa fa-list"></i>[select* menu-862 id:package class:text-uppercase class:jcf "Varianty zájazdu" "Ubytovanie a transfer" "Sprievodný program" "Sprievodkyňa"]</div>

<button class="btn-primary md-round text-uppercase" type="submit"><i class="icofont unycon unycon-office-chair md-round text-center"></i> Odoslať</button>
</fieldset>**"

In this part:
"<div class="col md-round"><i class="fa fa-list"></i>[select* menu-862 id:package class:text-uppercase class:jcf "Varianty zájazdu" "Ubytovanie a transfer" "Sprievodný program" "Sprievodkyňa"]</div>"

- I need to have multiple to click & send. Everything stays the way it is, but I really need to have the option to choose 1 or 2 or 3 options, not just one of them.

Thanks in advance

**Comment by ViorelEremia** [comment]
I don't understand you. Theese are settings for contact form plugin what is the connection with Unyson?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
