### ISSUE TITLE
Editing mobile layout

### ISSUE THREAD

**Issue by Roi1207** [ThemeFuse/Unyson#3236]
Hello,
If you take a look here: https://hackerman.co.il/
On the part where there are numbered sections from 1-6 (see picture here: https://snag.gy/Udur6V.jpg)
When viewed in mobile, it shows the order 3-2-1-6-5-4. How can I edit it to be correctly ordered?

**Comment by ViorelEremia** [comment]
I see two ways to do that one of them is easy another you must have some knowledge of flex box you can read here what is it:https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox
The first way is to create two sections one for desktop other for mobile so you need to write a custom css that will hide on mobile the desktop section and vice versa. I don't see what theme do you use but you must add a unique class for these sections if you do not have this opportunity ask your theme developer or if you are a developer you can read in the unyson documentation how you can add new options for the section shortcode.
