### ISSUE TITLE
Addable boxes with empty title are hidden

### ISSUE THREAD

**Issue by puyaalexxx** [ThemeFuse/Unyson#324]
After update unyson , the addable-box option appears like this http://awesomescreenshot.com/0ba4k5ld18

**Comment by moldcraft** [comment]
I can't reproduce that. Can you please Inspect element and find which css causes that?

**Comment by puyaalexxx** [comment]
Add this class fw-postbox-without-name  to postbox fw-postbox  fw-postbox-initialized closed

**Comment by moldcraft** [comment]
The fix will be available in the next Unyson release. Until then, please replace [this file](https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/backend-options.js) manually.
