### ISSUE TITLE
Page builder reverts to default editor

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#3240]
Hi there,

We are building a site based on The Core and using the Unyson Page Builder. Everything was fine on our testing environment, but on the live environment (different host) there's a problem with the Visual Builder. 

When saving a page, the Page Builder is reverted to the default WordPress editor with just plain HTML text in it. When swithcing back to the visual editor, all content is shown in a single block; all blocks have disappeared. It doesn't really seem to matter what content was in the Page Builder, but it mainly seems to happen when there are multiple section-blocks.

before saving:
![schermafbeelding 2018-03-07 om 09 04 17](https://user-images.githubusercontent.com/1815847/37080728-7f21b6a6-21e7-11e8-9080-ee7bb5baf390.png)

after saving (reverted back to default editor)
![schermafbeelding 2018-03-07 om 09 04 38](https://user-images.githubusercontent.com/1815847/37080729-7f408d42-21e7-11e8-977f-389f935d23b6.png)

switching back to Page Builder
![schermafbeelding 2018-03-07 om 09 05 29](https://user-images.githubusercontent.com/1815847/37080730-7f58db04-21e7-11e8-8bb2-485a0bdd737a.png)

We've tried various different things, but the problem still persists:
- updating all plugins and extensions
- removing and reinstalling Unyson plugin
- removing and reinstalling Page Builder extension
- switching to Twenty Seventeen
- enabling the WP debug log, but bo errors are showing up

I've made a full backup of the site (with the Unyson extension) and imported it in the testing environment, but the problem doesn't turn up there, so I guess it's something to do with the server of the live environment, but I don't know what to do about it.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by warudin** [comment]
I've sent you the asked credentials!
