### ISSUE TITLE
Unyson: Upgrading Unyson Mega Menu icons disappear (Avada)

### ISSUE THREAD

**Issue by Miguelos2** [ThemeFuse/Unyson#3243]
Upgrading Unyson Mega Menu icons disappear (Avada) Please help

**Comment by ViorelEremia** [comment]
Avada also uses awesome icons so it is a conflict between icons, so you need to add compatibility with it. Can you try to download the latest awesome fonts: https://fontawesome.com/v4.7.0/ and replace everything in the path: unyson/framework/static/libs/font-awesome and check if it is working.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
