### ISSUE TITLE
RAW Code element hides Visual Builder on update

### ISSUE THREAD

**Issue by jgulzinski** [ThemeFuse/Unyson#3246]
Unyson v2.7.12
The CORE Child Theme v1.0.31 by ThemeFuse
WordPress v4.9.4

1) Standard page built with Visual Builder
2) Add Section element
3) Add 1/1 Column element
4) Add RAW Code element
5) Add ANY custom script (typically <iframe> code)
6) Click Update button
7) **Visual Builder DISAPPEARS**
8) Must refresh the page for Visual Builder to reappear
9) Visual Builder disappears with every Update

**Comment by danyj** [comment]
there is no raw code element in default framework , contact theme provider please

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/master/shortcodes
