### ISSUE TITLE
Failed to recover items from input Version 2.7.12

### ISSUE THREAD

**Issue by patricktresp** [ThemeFuse/Unyson#3248]
Hey all,

i believe with one of the latest updates of unyson using with Wordpress i now get blank editor Pages as described here: https://github.com/ThemeFuse/Unyson/issues/406

I already tried this:

- deactivating all other wordpress-plugins
- reinstall components manually of the plugin as described at https://github.com/ThemeFuse/Unyson/issues/406
- deactivating and reactivating unyson plugin

If i could understand the error that comes with it, or how it occurs, i might code something around it:

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Stack trace:
initialize@https://www.my-domain.com/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/builder.js?ver=1.1.17:809:20
e.Model@https://www.my-domain.com/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,underscore,utils,jquery-ui-widget,jquery-ui-position,jquery-ui-core,jquery-ui-mouse,jquery-ui-menu,wp&load%5B%5D=-a11y,jquery-ui-autocomplete,backbone,moxiejs,plupload&ver=4.9.4:84:4450
n@https://www.my-domain.com/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,underscore,utils,jquery-ui-widget,jquery-ui-position,jquery-ui-core,jquery-ui-mouse,jquery-ui-menu,wp&load%5B%5D=-a11y,jquery-ui-autocomplete,backbone,moxiejs,plupload&ver=4.9.4:84:22929
@https://www.my-domain.com/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/builder.js?ver=1.1.17:1060:19
each@https://www.my-domain.com/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,underscore,utils,jquery-ui-widget,jquery-ui-position,jquery-ui-core,jquery-ui-mouse,jquery-ui-menu,wp&load%5B%5D=-a11y,jquery-ui-autocomplete,backbone,moxiejs,plupload&ver=4.9.4:2:2879
each@https://www.my-domain.com/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,underscore,utils,jquery-ui-widget,jquery-ui-position,jquery-ui-core,jquery-ui-mouse,jquery-ui-menu,wp&load%5B%5D=-a11y,jquery-ui-autocomplete,backbone,moxiejs,plupload&ver=4.9.4:2:844
@https://www.my-domain.com/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/builder.js?ver=1.1.17:1034:3
dispatchSingleEvent@https://www.my-domain.com/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:169:6
fwEvents</this.trigger/<@https://www.my-domain.com/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:147:7
objectMap@https://www.my-domain.com/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:250:18
fwEvents</this.trigger@https://www.my-domain.com/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:131:3
@https://www.my-domain.com/wp-content/plugins/unyson/framework/static/js/option-types.js?ver=2.7.12:3:3
builder.js:811:7`

Is there anything i can do?

Best,

Patrick

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
