### ISSUE TITLE
Unyson Page Builder completely failed

### ISSUE THREAD

**Issue by paul-view** [ThemeFuse/Unyson#3249]
The pages on my website www.tennace.com could not be edited due to the Unyson Page Builder failure. By deactivating it we could see the content of the pages, but with it activated absolutely nothing, not even a Visual or Text viewer.

**Comment by danyj** [comment]
contact theme provider please

**Comment by ViorelEremia** [comment]
https://support.themefuse.com/hc/en-us/requests/new
