### ISSUE TITLE
Lightbox Content

### ISSUE THREAD

**Issue by tmattevc** [ThemeFuse/Unyson#3252]
Hi, I'm wondering if there's something built in or if anyone knows a trick to doing this - I'd like to set something where content comes up in a lightbox when I click on an image or button. 

For example a team bio section. I don't really like built in Team Member layouts. Would like to set something up where I have an image of the team member and when you click on that (or possibly a 'Read Bio' button) the content comes up in a lightbox window instead of needing to go to a new page to read the bio.

**Comment by andronic90** [comment]
try Bootstrap Modal for something in modal: https://www.w3schools.com/bootstrap/bootstrap_modal.asp

for image bigger you can use: prettyPhoto or photoswipe or something else
