### ISSUE TITLE
Vimeo video

### ISSUE THREAD

**Issue by ruk72** [ThemeFuse/Unyson#3257]
Hello I am currently using your framework with SAN wordpress theme. 
I have a few large videos loading on home page (over 40mb) and it is slowing down my page load.

But with your framework I only have 2 options for video 1. upload video to wordpress (slow) or 2. use youtube which doesn't allow HD only SD.

What I would like to use is Vimeo for loading my videos. How can I use your framework to load vimeo videos?

**Comment by ViorelEremia** [comment]
![vadfasdf](https://user-images.githubusercontent.com/28967378/37328822-2bd870fe-26a4-11e8-8202-6a690661cf2a.png)
![asdfasdfasdfasd](https://user-images.githubusercontent.com/28967378/37328821-2bb6f5dc-26a4-11e8-8500-15b5ec394587.png)
Open shortcode video from builder page and in input "Insert Video URL" insert Vimeo link by default it is working we tested. If you don't have this input it means that the video shortcode is rewritten by your theme author so you have to contact him.
