### ISSUE TITLE
Not able to edit pages 

### ISSUE THREAD

**Issue by vangjo** [ThemeFuse/Unyson#3258]
We have three admin account on one of the account everything works normal but on the other 2, we cant edit pages with. All the Layout Elements are missing

**Comment by ViorelEremia** [comment]
Try to update unyson extensions: https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
Remove any cache: server, wp plugin or server.
On old internet explorer page builder doesn't work.

**Comment by vangjo** [comment]
can I use a plugin such as "WP Fastest Cache" or is there another plugin that you recommend?

**Comment by ViorelEremia** [comment]
Yes, you can use wp fastest cache plugin should work. Did you solve your problem?

**Comment by vangjo** [comment]
yes, it seems to be working now. Thank you for your advice
