### ISSUE TITLE
Remove Theme Settings Menu

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#3259]
Hi,
how can i delete Theme Settings Menu?? i'm not using the theme option. i'm  using the customizer. So i want to delete this menu. i already delete all theme settings but still the menu is appear.
http://prntscr.com/ir25tt

**Comment by ViorelEremia** [comment]
Add in your theme functions.php:
```
add_action( 'admin_menu', 'remove_unyson_theme_settings', 999 );
function remove_unyson_theme_settings() {
	remove_submenu_page( 'themes.php', 'fw-settings' );
}
```
