### ISSUE TITLE
WPML compatibility

### ISSUE THREAD

**Issue by valeriuzdrobau** [ThemeFuse/Unyson#326]
In the event of a doubling of taxonomies using wpml not copy settings.

**Comment by Nic787** [comment]
it could be nice to support .pot files to translate stuffs ourself.

**Comment by valeriuzdrobau** [comment]
@Nic787 it is open on another [issue](https://github.com/ThemeFuse/Unyson-Events-Extension/issues/4)

**Comment by andronic90** [comment]
When is duplicated a post then post related categories is duplicated in this specific language, but the options are not copied. Please inspect this.
