### ISSUE TITLE
No Builder and update

### ISSUE THREAD

**Issue by delphinehaha** [ThemeFuse/Unyson#3260]
Hey,
I can not have the builder extension to transform my pages, it's integrate on my page, activate, but doesn't appear. Problem appear after update
 as i know i have to update all Unyson extension but they give me an error message.
"Dowload extension event...
You cannot dowload  zip : extension event ."

for all the extensions. 

PLease help me

**Comment by ViorelEremia** [comment]
I think you have a server issue with file permission. Or you can try to contact theme author there are no issues with update extensions. Or you can download them from this [link ](https://github.com/ThemeFuse/Unyson/issues/3241)and replace them in unyson/framework/extensions/ through ftp
