### ISSUE TITLE
Getting data from a class that extends the FW_Settings_Form 

### ISSUE THREAD

**Issue by shunope** [ThemeFuse/Unyson#3262]
Hello. I'm new to Unyson (and github, so please tell me if this is the wrong place to ask this kind of questions) and have a problem at hand. I tried the part of the documentation where it explains how to extend the FW_Settings_Form (see here manual.unyson.io/en/latest/helpers/settings-form.html). I added my options and in the backend everything seems to be fine. But now I have two questions: 

A) How do I get the data from the values I entered in the backend? I tried fw_get_db_settings_option() and checked what fw()->theme->get_settings_options(); provided too, but in both cases I can only get values that I entered in the theme/options/settings.php where I set up some backend options before. 

B) Is the extension of the FW_Settings_Form the right way to set up backend options? As said before, I already tried the settings.php and built a couple of options, but when I tried the documentation part about the extension of the FW_Settings_Form, I noticed that the settings the FW_Settings_Form generates look much sleeker and prettier, so I would prefer the build the backend settings with this functionality. 

Again, I'm sorry if this is the wrong place to ask this questions. Since this is not a code related issue, is there another place/community to talk about the Unyson builder and ask questions like this?

**Comment by shunope** [comment]
OK, I think I got it sorted out. 

get_option() did it.

**Comment by ViorelEremia** [comment]
No, is not a wrong place to ask such questions. There is no another place/community to talk about unyson here is the only place where you can talk about it in any case we do not know about another place.
The page ```theme/options/settings.php``` is also created via FW_Settings_Form, add a file in path: ```/theme/framework-customizations/theme/config.php```  add here: ```$cfg['settings_form_side_tabs'] = true;```, to extract values see docs: http://manual.unyson.io/en/latest/helpers/php.html#database

**Comment by shunope** [comment]
Thank you, Viorel. I set it up as you said with the config.php and now my theme settings (settings.php) look as good as the settings I created with the other file. I'm just scratching the surface but what you and all the other contributers did with Unyson is awesome.  Keep up the good work!
