### ISSUE TITLE
How to set background for setting extension?

### ISSUE THREAD

**Issue by notrealdev** [ThemeFuse/Unyson#3264]
Hi, i have a custom extension and a few setting for it, how to set background for setting area like Breadcrumbs setting?

`Breadcrumbs setting` has white background color

![breadcrumbs](https://i.imgur.com/NThTFvG.png)

`My setting`

![my-setting](https://i.imgur.com/XpqOJng.png)

Any filter or option for it? Tks

**Comment by ViorelEremia** [comment]
How did you add this box? is it a custom settings page? is it in edit admin page? show your code that generates these settings.

**Comment by notrealdev** [comment]
`...\plugins\my-plugin\extensions\worked-place\settings-options.php`
```php
$options = array(
    'unit'      => array(
        'label' => esc_html__( 'Unit', 'goto' ),
        'type'  => 'select',
        'choices' => array(),
    ),
    'ctf7' = array(
        'label' => esc_html__( 'Contact form', 'goto' ),
        'type'  => 'select',
        'choices' => array(),
    );
);
```
Here my code

**Comment by ViorelEremia** [comment]
How do you load it? What hook? where do you want to show these settings?

**Comment by notrealdev** [comment]
Can i send you my plugin via email and you can check it?

**Comment by ViorelEremia** [comment]
```viorel@themefuse.com```

**Comment by ViorelEremia** [comment]
Use in this way: 
```
$options = array(
	'box' => array(
		'title'   => false,
		'type'    => 'box',
		'options' => array(
			'unit'      => array(
				'label' => esc_html__( 'Price unit', 'goto' ),
				'type'  => 'select',
				'choices' => $c,
				'value' => 'USD'
			),
		)
	)
);

```

**Comment by ViorelEremia** [comment]
See here for more details: http://manual.unyson.io/en/latest/options/introduction.html#containers

**Comment by notrealdev** [comment]
Yes, thank you ^^
