### ISSUE TITLE
Visual Page Builder Update Causing Eye To Appear

### ISSUE THREAD

**Issue by emilymilling** [ThemeFuse/Unyson#3265]
Hi,

I just updated Unyson on two websites and noticed an eyeball looking back at me in the top right. There are also column widths appearing in the front end where they should be hidden. 

Is there a plan to fix this issue for the next update, and when will the next update be? 

I managed to hide the eyeball by using the following css:

`.sh-unyson-frontend-test {
	display:none;
}`
<img width="108" alt="screen shot 2018-03-16 at 6 08 55 pm" src="https://user-images.githubusercontent.com/37459244/37546990-a9116406-2945-11e8-81b1-6a4bab83c53f.png">

Thanks!

edit:

It's not column width causing the sudden appearance of "100px"/"10px" etc., it's the empty space modules. I removed it with this:

`.sh-empty-space {
display:none;
}`

**Comment by ViorelEremia** [comment]
I can't understand what you see on your site. Please provide more details. What is that prefix ```sh```? unyson doesn't have this class prefix. Try to inspect maybe issue is caused by your theme.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
