### ISSUE TITLE
Publish/Save button disapeared

### ISSUE THREAD

**Issue by josefsirucka** [ThemeFuse/Unyson#3266]
Hi

I have problem with loading of the page builder. When i go to menu, click on Pages and then select any page, page is loaded, but button Publish/save is missing.

Unfortunately i don't know what was it what preceded it. (i remember only that i did update of Unyson - Backup & Demo Content.

I have Wordpress: 4.9.4 and Unyson: 2.7.12

I found, that when i load the page there is stack error in Javascript console: 

unreachable code after return statement[Zjistit více]
editor_integration.js:236:6
Načtení prvku <script> ze zdroje „https://www.joska.rocks/wp-includes/js/tinymce/wp-tinymce.php?c=1&ver=4607-20180123“ se nezdařilo.
post.php:3035
ReferenceError: tinymce is not defined[Zjistit více]
post.php:3037:1
<anonymní>
https://www.joska.rocks/wp-admin/post.php:3037:1
ReferenceError: tinyMCE is not defined[Zjistit více]
wp-langs-en.js:235:2
<anonymní>
https://www.joska.rocks/wp-includes/js/tinymce/langs/wp-langs-en.js:235:2
<anonymní>
https://www.joska.rocks/wp-includes/js/tinymce/langs/wp-langs-en.js:6:3
ReferenceError: tinymce is not defined[Zjistit více]
post.php:3106:37
load_ext
https://www.joska.rocks/wp-admin/post.php:3106:37
<anonymní>
https://www.joska.rocks/wp-admin/post.php:3116:3
 [Events] Exception raised. Please contact support in https://github.com/ThemeFuse/Unyson/issues/new. Don't forget to attach this stack trace to the issue.
fw-events.js:150:6
ReferenceError: tinymce is not defined
Stack trace:
tinyMceInit@https://www.joska.rocks/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/static/js/editor_integration.js?ver=1.6.14:296:7
init/<@https://www.joska.rocks/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/static/js/editor_integration.js?ver=1.6.14:343:13
dispatch@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:3:12392
add/r.handle@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:3:9156
trigger@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:3:11571
a.event.trigger@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:9:8273
trigger/<@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:3:18983
each@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:2879
each@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:844
trigger@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:3:18962
initSingleBuilder@https://www.joska.rocks/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:514:4
initBuilderDelayed/</<@https://www.joska.rocks/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:302:5
then/</</<@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:28766
i@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:27444
add@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:27748
then/</<@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:28738
each@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:2879
then/<@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:28684
a.Deferred@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:9:9928
then@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:28661
initBuilderDelayed/<@https://www.joska.rocks/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:301:4
each@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:2879
each@https://www.joska.rocks/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.4:2:844
initBuilderDelayed@https://www.joska.rocks/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:288:3
init/<@https://www.joska.rocks/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/initialize-builder.js?ver=1.2.10:273:4
dispatchSingleEvent@https://www.joska.rocks/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:169:6
fwEvents</this.trigger/<@https://www.joska.rocks/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:147:7
objectMap@https://www.joska.rocks/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:250:18
fwEvents</this.trigger@https://www.joska.rocks/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:131:3
@https://www.joska.rocks/wp-content/plugins/unyson/framework/static/js/option-types.js?ver=2.7.12:3:3
fw-events.js:156:7
unreachable code after return statement[Zjistit více]
editor_integration.js:236:6

Do you have any ideas what is to root cause of this and how to fix that? 

Unfortunately i am not able to add/edit pages anymore, becuase also Blogs add/edit are not working at all (becuase of the same problem)
<img width="952" alt="error" src="https://user-images.githubusercontent.com/8895101/37556783-0b090852-29fb-11e8-8e39-c58de0a78259.PNG">

**Comment by ViorelEremia** [comment]
Try to contact your hosting provider. These errors occur because of tinymce is not loading this is usually caused by file permission in wordpress core.
