### ISSUE TITLE
Theme issues with Unyson 2.7.12 after installation

### ISSUE THREAD

**Issue by toddel-71** [ThemeFuse/Unyson#3267]
Following installation:
Version 4.9.4 | WellnessCenter 2.9.3 | Unyson 2.7.11

When I install the Unyson version 2.7.12, following errors occur:

- On the Design tap / Theme settings - The Unyson loading symbol is shown, but the page is empty
- On all pages the default editor is not shown anymore, page modification is not possible anymore
- On the Form builder page - also here issues with updates happens

If further details are necessary please let me know what I should publish.

**Comment by OmnidexExchange** [comment]
Getting this error on the form. I have the fields. I set them to required and turned them off, same issue.

Before sending, please make sure to provide your name, email, and message.

**Comment by Ataurr** [comment]
Make sure your all unyson extensions are up to date.
Most of time i found this issue due to extensions.

Go to dashboard -> updates tab

**Comment by ViorelEremia** [comment]
Update extensions: https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456 
Remove any cache: wp plugins, browser, server. 
Duplicate: https://github.com/ThemeFuse/Unyson/issues/3175
