### ISSUE TITLE
Upgrade To Font Awesome 5 free 

### ISSUE THREAD

**Issue by mahmoud-asfour** [ThemeFuse/Unyson#3268]
I'm trying to upgrade font awesome to version 5 free in load-latest-fonts.php file but no thing happen , Is there any way to how to do that?

**Comment by andreiglingeanu** [comment]
`load-latest-fonts.php` script is not meant to provide a way to update to FA 5, it assumes the old FA repository structure, the one that we had with FA 4. 

Before fixing the `load-latest-fonts.php` script, we should figure out a way to use FA 5 with `icon-v2`, which is a bit tricky.

**Comment by danyj** [comment]
irresponsible from them

**Comment by ViorelEremia** [comment]
duplicate: https://github.com/ThemeFuse/Unyson/issues/3268
