### ISSUE TITLE
White screen after "Add New" or "Edit" page

### ISSUE THREAD

**Issue by maciejkakudlaty** [ThemeFuse/Unyson#3271]
I have problem with add new and edit existing pages. Appears white screen after clicking "Edit" or "Add New"

PHP 7.2.2 / Wordpress 4.9.4 / Unyson 2.7.12
Logs:
> [Fri Mar 16 14:13:21.982959 2018] [php7:warn] [pid 10557] [client 10.149.0.29:57988] PHP Warning:  Illegal string offset 'name' in /var/www/wordpress/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php on line 179, referer: https://kandydat.agh.edu.pl/wp-admin/edit.php?post_type=page
[Fri Mar 16 14:13:21.983037 2018] [php7:warn] [pid 10557] [client 10.149.0.29:57988] PHP Warning:  Illegal string offset 'id' in /var/www/wordpress/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php on line 180, referer: https://kandydat.agh.edu.pl/wp-admin/edit.php?post_type=page
[Fri Mar 16 14:13:21.983045 2018] [php7:warn] [pid 10557] [client 10.149.0.29:57988] PHP Warning:  Illegal string offset 'class' in /var/www/wordpress/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php on line 181, referer: https://kandydat.agh.edu.pl/wp-admin/edit.php?post_type=page
[Fri Mar 16 14:13:21.983052 2018] [php7:warn] [pid 10557] [client 10.149.0.29:57988] PHP Warning:  Illegal string offset 'value' in /var/www/wordpress/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php on line 186, referer: https://kandydat.agh.edu.pl/wp-admin/edit.php?post_type=page
[Fri Mar 16 14:13:21.983058 2018] [php7:warn] [pid 10557] [client 10.149.0.29:57988] PHP Warning:  Cannot assign an empty string to a string offset in /var/www/wordpress/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php on line 186, referer: https://kandydat.agh.edu.pl/wp-admin/edit.php?post_type=page
[Fri Mar 16 14:13:21.983151 2018] [php7:error] [pid 10557] [client 10.149.0.29:57988] PHP Fatal error:  Uncaught Error: Cannot unset string offsets in /var/www/wordpress/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php:193\nStack trace:\n#0 /var/www/wordpress/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php(281): FW_Option_Type->prepare('boxes', Array, Array)\n#1 /var/www/wordpress/wp-content/plugins/unyson/framework/core/components/backend.php(1474): FW_Option_Type->enqueue_static('boxes', Array)\n#2 /var/www/wordpress/wp-content/plugins/unyson/framework/helpers/general.php(1132): _FW_Component_Backend::_callback_fw_collect_options_enqueue_static(Array)\n#3 /var/www/wordpress/wp-content/plugins/unyson/framework/helpers/general.php(1097): fw_collect_options(Array, Array, Array, Array)\n#4 /var/www/wordpress/wp-content/plugins/unyson/framework/core/components/backend.php(1459): fw_collect_options(Array, Array, Array)\n#5 /var/www/wordpress/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/includes/item-types/simple/c in /var/www/wordpress/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php on line 193, referer: https://kandydat.agh.edu.pl/wp-admin/edit.php?post_type=page

**Comment by ViorelEremia** [comment]
What theme do you have? It seems that unyson is trying to load some wrong arrays

**Comment by maciejkakudlaty** [comment]
Helo,
I bought ECoursify teplate.<https://www.templatemonster.com/wordpress-themes/ecoursify-lms-for-online-courses-wordpress-theme-66906.html>
Installed here:
https://kandydat.agh.edu.pl

Regards,
Maciej


________________________________
Od: ViorelEremia <notifications@github.com>
Wysłane: 21 marca 2018 09:43
Do: ThemeFuse/Unyson
DW: maciejkakudlaty; Author
Temat: Re: [ThemeFuse/Unyson] White screen after "Add New" or "Edit" page (#3271)


What theme do you have? It seems that unyson is trying to load some wrong arrays

**Comment by ViorelEremia** [comment]
Try to contact your theme provider if he detects that it's a problem in unyson then let's open a new issue. From errors, it seems he uses wrong option types.

**Comment by maciejkakudlaty** [comment]
Thank You, for Your help.
Regards,
Maciej
________________________________
Od: ViorelEremia <notifications@github.com>
Wysłane: 21 marca 2018 13:59
Do: ThemeFuse/Unyson
DW: maciejkakudlaty; Author
Temat: Re: [ThemeFuse/Unyson] White screen after "Add New" or "Edit" page (#3271)


Try to contact your theme provider if he detects that it's a problem in unyson then let's open a new issue. From errors, it seems he uses wrong option types.
