### ISSUE TITLE
Can't override breadcrumb view in child theme

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#3272]
Hi! I could not override the breadcrumb view in the child theme. It works in the parent theme.
Here is my folder structure [http://take.ms/n6hlj](http://take.ms/n6hlj). It still loads the view from the parent theme.
Is there something wrong?
Thanks!

**Comment by duongancol** [comment]
Did you check my screenshot? It's in views folder already

**Comment by ViorelEremia** [comment]
By default with scratch/the-core theme it is working I'm sure of that, check your theme maybe you change something I see a file function .php what is it? What texteditor/ide do you use?
![file breadcrumbs php minera child 2018 03 21 11 29 41 png](https://user-images.githubusercontent.com/28967378/37711060-35f4c45a-2d18-11e8-8d75-21604e7ed1f7.png)

**Comment by duongancol** [comment]
It's my mistake. Thank you so much!
