### ISSUE TITLE
Forms not working unyson plugin

### ISSUE THREAD

**Issue by farajali** [ThemeFuse/Unyson#3273]
Sir/Mam.
I have used 3 forms on my website "http://brightonworldschool.org.in/", 2 forms on home page and 1 form is on contact us page. each of them not working properly i have contacted to theme forest support team they told me that i should forward this issue to unyson support team as they(themeforest) used unyson plugin to build forms. please look into the matter and its issue.

**Comment by duongancol** [comment]
Hi! This is the public forum so don't post your admin account here. Please remove it! Thanks!

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by farajali** [comment]
I am sent mail of your email id please check and solve my problem as soon as possible.

**Comment by ViorelEremia** [comment]
Solved it is a hosting issue.

**Comment by farajali** [comment]
I have contacted my hosting(godaddy team) they told me everything is alright in hosting they told it is scripting issue please check it and solve it as they tested their server by placing test script is working fine.

**Comment by ViorelEremia** [comment]
I tested with contact form 7 is not working, here is the link: http://brightonworldschool.org.in/?p=3363
Contact form is used by 5mil+ users it is tested very well.
Here is the link with test email plugin: http://brightonworldschool.org.in/wp-admin/tools.php?page=checkemail also is not working.
Here is the link with plugin WP Mail SMTP: http://brightonworldschool.org.in/wp-admin/options-general.php?page=wp-mail-smtp&tab=test aslo used by 800.000+ users.
So there are no mail plugins on wordpress.org that work with your site. Please read GoDaddy documentation how you can configure your mail on your site.

**Comment by farajali** [comment]
when i contacted to godaddy team they had given some setting to update it with script.
and they told that script would start working. setting is given below please find it and update accrodingly.

host: localhost
port: 25
ssl: false
authencation: none
