### ISSUE TITLE
Forms not working unyson plugin

### ISSUE THREAD

**Issue by farajali** [ThemeFuse/Unyson#3277]
Sir,
I am totally disappointed with the services given by theme support team.  I am receiving mail from home page forms but its format need to be fixed. There is  a form on contact us page which is not working if there were hosting issue, how would i receive mail from home page forms? By the way please tell me what is alternate solution to solve the issue?

**Comment by ViorelEremia** [comment]
Hey Sir, I checked again your home page contact form it is not working I don't see any message in your mailbox(```info@brightonworldschool.org.in```). The result of the contact form is true(```Message sent!```) but in your mailbox, there are no messages. so how did you test?

**Comment by farajali** [comment]
Sir, 
Please fix formatting of email which i receive through forms of my website. Refer 2 attached screenshots for detail. 

![query-form](https://user-images.githubusercontent.com/37611741/37827469-9f4fa054-2ebd-11e8-9f23-71767286770d.png)
![cotact us page form](https://user-images.githubusercontent.com/37611741/37827472-a3e25e9a-2ebd-11e8-854e-71353353043e.png)

**Comment by ViorelEremia** [comment]
You don't understand that is unyson. Unyson is a plugin for developers not for final users it allows devs to easily start a plugin or a premium/custom theme. So what you ask for it isn't possible directly from unyson to do you must rewrite some files if you want to customize received messages, or you can ask your theme developer. Reference: http://manual.unyson.io/en/latest/extension/forms/index.html?highlight=overwrite
