### ISSUE TITLE
Blank Pages in Firefox

### ISSUE THREAD

**Issue by bwagner182** [ThemeFuse/Unyson#3279]
I've gone through the normal troubleshooting of disabling all other plugins, extensions, caching, and activating a default theme. When the Unyson Page Builder extension is active, the page content, anything within the ``<div id="post-123" ...>`` is completely gone, but ONLY when using Firefox.

In Chrome, Safari, Edge, and IE everything works on the front end of the site, but in Firefox the page content is completely missing. 

If I go to the back end in Firefox I don't see the builder at all, simply the standard WordPress editor and all of my code in plaintext. 

WP version: 4.9.4
Unyson Version 2.7.12
Default theme tested: Twenty Seventeen
Unyson was included with or suggested by Pianino Theme from themeforest and that developer has refused to respond to any support requests.

**Comment by ViorelEremia** [comment]
I tested with multiple shortcodes in firefox and the theme Twenty Seventeen I don't see any issues. Give us more details about Twenty Seventeen, Unyson, and Firefox. About your premium theme, we don't offer support for.

**Comment by bwagner182** [comment]
Interestingly enough it appears to be something with the staging environment setup by our host. When on production it pulled up fine. I do apologize and will talk to their people to see what the issue is since the environments aren't as similar as they claim.
