### ISSUE TITLE
fw_get_db_post_option not working

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#328]
fw_get_db_post_option not working on my theme I have tried reinstalled again and check. 
i dont change anything from framework plugin
but fw_get_db_settings_option  work fine.

i have created custom function for get post meta. but still i wondering why fw_get_db_post_option not work for me. is there i need changed any settings. or i have doing any wrong.?

Thank you

**Comment by moldcraft** [comment]
I added to `{theme}/framework-customizations/theme/options/posts/post.php` a test option

```php
$options = array(
	// ...
	'test-box' => array(
		'type' => 'box',
		'options' => array(
			'test-option' => array('type' => 'text'),
		),
	),
);
```

I saved the post (with some value in test input).
The I added to `{theme}/content.php` this code

```php
fw_print(
	fw_get_db_post_option(get_the_ID(), 'test-option')
);
```

and the value was printed in frontend.

**Comment by xperter** [comment]
HI @moldcraft  
here is my option with multipicker 
<pre>
$options = array(
    'page_sections' => array(
        'type' => 'multi-picker',
        'label' => false,
        'desc' => false,
        'picker' => array(
            'xp_page_section' => array(
                'label' => __('This page is a section:', 'xs'),
                'type' => 'switch',
                'right-choice' => array(
                    'value' => 'yes',
                    'label' => __('Yes', 'xs')
                ),
                'left-choice' => array(
                    'value' => 'no',
                    'label' => __('No', 'xs')
                ),
                'value' => 'no',
                'desc' => __('If its a <b>Section</b>, please set this field to <b>on</b>. And if its page, set it to <b>off</b>', 'xs'),
                'help' => sprintf("%s \n\n'\"<br/><br/>\n\n <b>%s</b>", __('If its a <b>Section</b>, please set this field to <b>on</b>. And if its page, set it to <b>off</b>', 'xs'), __('For One page always will be <b>yes</b>', 'xs')
                ),
            )
        ),
        'choices' => array(
            'yes' => array(
                
                'hide_title_from_menu' => array(
                    'type' => 'switch',
                    'label' => __('hide from menu', 'xs'),
                    'right-choice' => array(
                        'value' => 'yes',
                        'label' => __('Yes', 'xs')
                    ),
                    'left-choice' => array(
                        'value' => 'no',
                        'label' => __('No', 'xs')
                    ),
                    'value' => 'no',
                    'desc' => __('Show the <b>Tile</b> when set to <b>yes</b>, otherwise it will be hide from page', 'xs'),
                ),
            ),
        ),
        'show_borders' => false,
    ),
);
</pre>
and i like to show data with <pre>if (fw_get_db_post_option(get_the_ID(), 'hide_title_from_menu') != 'yes') {...}</pre>


really appreciate you help :)

Thank you

**Comment by moldcraft** [comment]
> @xperter
>
> ```php
> $options = array(
>     'page_sections' => array(
>         'type' => 'multi-picker', // ???
>     ...
> ```

Is your option even visible on post edit page?

> http://manual.unyson.io/en/latest/options/restrictions.html#content
>
> > **Post Options** array on first level can have only **box** containers.

**Comment by xperter** [comment]
Opss sorry  i have removed unwanted code. i have deleted box code to.
here is the options all 
<pre> <?php

if (!defined('FW')) {
    die('Forbidden');
}

$options = array(
    'main' => array(
        'title' => false,
        'type' => 'box',
        'options' => array(
            'page_sections' => array(
                'type' => 'multi-picker',
                'label' => false,
                'desc' => false,
                'picker' => array(
                    'xp_page_section' => array(
                        'label' => __('This page is a section:', 'xs'),
                        'type' => 'switch',
                        'right-choice' => array(
                            'value' => 'yes',
                            'label' => __('Yes', 'xs')
                        ),
                        'left-choice' => array(
                            'value' => 'no',
                            'label' => __('No', 'xs')
                        ),
                        'value' => 'no',
                        'desc' => __('If its a <b>Section</b>, please set this field to <b>on</b>. And if its page, set it to <b>off</b>', 'xs'),
                        'help' => sprintf("%s \n\n'\"<br/><br/>\n\n <b>%s</b>", __('If its a <b>Section</b>, please set this field to <b>on</b>. And if its page, set it to <b>off</b>', 'xs'), __('For One page always will be <b>yes</b>', 'xs')
                        ),
                    )
                ),
                'choices' => array(
                    'yes' => array(
                        
                        'hide_title_from_menu' => array(
                            'type' => 'switch',
                            'label' => __('hide from menu', 'xs'),
                            'right-choice' => array(
                                'value' => 'yes',
                                'label' => __('Yes', 'xs')
                            ),
                            'left-choice' => array(
                                'value' => 'no',
                                'label' => __('No', 'xs')
                            ),
                            'value' => 'yes',
                            'desc' => __('Show the <b>Tile</b> when set to <b>yes</b>, otherwise it will be hide from page', 'xs'),
                        ),
                        
                    ),
                    
                ),
                'show_borders' => false,
            ),
        ),
    ),
);
</pre>

**Comment by moldcraft** [comment]
Add this in your template

```php
fw_print(
    fw_get_db_post_option(get_the_ID(), 'page_sections')
);
```

and inspect the multi-picker value.

**Comment by xperter** [comment]
Hi
Thanks for help.
I have seen array now but how i can get value easily xp_page_section yes or no ??
i know i am bothering you. :) i am just create a theme for me.. and i love your framework but its quite complicated for me :D 

Thank you

**Comment by moldcraft** [comment]
> I have seen array now but how i can get value easily xp_page_section yes or no ??

Yes, multi-picker values is a little confusing.

```php
array(
	'title' => false,
	'type' => 'box',
	'options' => array(
		'page_sections' => array(
			'type' => 'multi-picker',
			'label' => false,
			'desc' => false,
			'picker' => array(
				'xp_page_section' => array(
					'label' => __('This page is a section:', 'xs'),
					'type' => 'switch',
					'right-choice' => array(
						'value' => 'yes',
						'label' => __('Yes', 'xs')
					),
					'left-choice' => array(
						'value' => 'no',
						'label' => __('No', 'xs')
					),
					'value' => 'yes',
					'desc' => __('If its a Section, please set this field to on. And if its page, set it to off', 'xs'),
				),
			),
			'choices' => array(
				'yes' => array(
					'hide_title_from_menu' => array(
						'type' => 'switch',
						'label' => __('hide from menu', 'xs'),
						'right-choice' => array(
							'value' => 'yes',
							'label' => __('Yes', 'xs')
						),
						'left-choice' => array(
							'value' => 'no',
							'label' => __('No', 'xs')
						),
						'value' => 'yes',
						'desc' => __('Show the Tile when set to yes, otherwise it will be hide from page', 'xs'),
					),
				),
				'no' => array(
					'test' => array('type' => 'text'),
				),
			),
			'show_borders' => false,
		),
	),
),
```

```php
$sections = fw_get_db_post_option(get_the_ID(), 'page_sections');
fw_print(
	$sections[ $sections['xp_page_section'] ]
);
```

**Comment by moldcraft** [comment]
> i know i am bothering you. :) i am just create a theme for me.. and i love your framework but its quite complicated for me :D

No problem, we are here to help.

**Comment by xperter** [comment]
still i cant access yes no value for hide_title_from_menu
i receive array for xp_page_section how again i enter this array and grab the data for hide_title_from_menu yes no value :(

Thank you

**Comment by moldcraft** [comment]
`'hide_title_from_menu'` is inside `'yes'` value, `'hide_title_from_menu'` does not exist in `'no'` value.

P.S. After options array change, don't forget to save post to update database values.

**Comment by xperter** [comment]
Yeap i understand 
but dont need xp_page_section value
 i like to get value from hide_title_from_menu yes or no
$sections = fw_get_db_post_option(get_the_ID(), 'page_sections');
fw_print(
    $sections[ $sections['hide_title_from_menu'] ]
);

here is my code which i like to use 
<pre>if ( $sections[ $sections['hide_title_from_menu'] ] != 'yes') 
{.......}</pre>
 if no condition will work

I dont do this kind of nested array before. thats y confused :(

Thank you

**Comment by moldcraft** [comment]
* `$sections['xp_page_section']` contains `yes` or `no`
* `$sections[ $sections['xp_page_section'] ]` contains `'choices'['yes']` or `'choices'['no']`

try this

```php
$picked_value = $sections[ $sections['xp_page_section'] ];

if ($sections['xp_page_section'] == 'yes') {
    fw_print('yes', $picked_value['hide_title_from_menu']);
} else {
    fw_print('no', $picked_value['test']);
}
```

**Comment by xperter** [comment]
Thank you brother :+1:

**Comment by xperter** [comment]
Brother i need little help again.  i have created a simple shortocde
<pre> 'overlay_options' => array(
        'type' => 'multi-picker',
        'label' => false,
        'desc' => false,
        'picker' => array(
            'overlay' => array(
                'type' => 'switch',
                'label' => __('Overlay Color', 'fw'),
                'desc' => __('Enable image overlay color?', 'fw'),
                'value' => 'no',
                'right-choice' => array(
                    'value' => 'yes',
                    'label' => __('Yes', 'fw'),
                ),
                'left-choice' => array(
                    'value' => 'no',
                    'label' => __('No', 'fw'),
                ),
            ),
        ),
        'choices' => array(
            'no' => array(),
            'yes' => array(
                'background-image-overlay' => array(
                    'label' => __('Overlay', 'unyson'),
                    'type' => 'rgba-color-picker',
                    'value' => 'rgba(255, 0, 0, .5)',
                    'desc' => __('Lorem .', 'unyson'),
                    'help' => sprintf("%s \n\n'\"<br/><br/>\n\n <b>%s</b>", __('Lorem ', 'unyson')
                    ),
                )
            ),
        ),
    ), </pre>
i have tried to print rgba color  but nothing work :(
<pre>$overlays = $atts['overlay_options']['overlay'];
if ($overlays == 'yes') {
    $overlay = $atts['overlay_options']['overlay']['background-image-overlay'];
}</pre>

Appreciate your help :)
Thank you

**Comment by moldcraft** [comment]
```php
$overlays = $atts['overlay_options']['overlay'];
if ($overlays == 'yes') {
    $overlay = $atts['overlay_options'][ $overlays ]['background-image-overlay'];
}
```

**Comment by xperter** [comment]
Its work for me. but i am receiving a undefined notice
Notice: Undefined index: overlay_options in  

is there i need to connect anything from options.php page ??

Thank you

**Comment by moldcraft** [comment]
Inspect `fw_print($atts)`

**Comment by xperter** [comment]
Here is the atts print details
<pre>
array
(
    [overlay_options] => array
    (
        [overlay] => 'yes'
        [yes] => array
        (
            [background-image-overlay] => 'rgba(227,17,17,0.5)'
        )
    )
    [auto_generated] => ''
    [first_in_builder] => '1'
)
</pre>
and after bottom of the section Notice: Undefined index: overlay_options in 
<pre>array
(
    [auto_generated] => ''
)</pre>

**Comment by moldcraft** [comment]
I don't think it's an Unyson issue/bug. Please inspect the arrays more carefully before accessing the keys.

**Comment by sattar3001** [comment]
![15402892101rd7oabhxmgesvvwadsw](https://user-images.githubusercontent.com/29397625/48405254-247d5080-e75c-11e8-81df-f352edd4db19.jpg)
