### ISSUE TITLE
Mega menu multiple rows. How?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3283]
According to markup in the manual we can have multiple rows in the mega menu 

http://manual.unyson.io/en/1.x/extension/megamenu/index.html

```
li.menu-item-has-mega-menu
    div.mega-menu
        ul.mega-menu-row
            li.mega-menu-col
            li.mega-menu-col
            li.mega-menu-col
        ul.mega-menu-row
            li.mega-menu-col
            li.mega-menu-col
            li.mega-menu-col
        ul.mega-menu-row
            li.mega-menu-col
            li.mega-menu-col
            li.mega-menu-col
```

but once you set the top level item as mega menu , all items under can be columns only , not rows.

**Comment by ViorelEremia** [comment]
I don't understand what is not working for you I tested like that:
![menus wp wordpress](https://user-images.githubusercontent.com/28967378/38017300-52c6e86c-327a-11e8-85f3-3b829b5eace2.png)
![blabla](https://user-images.githubusercontent.com/28967378/38017309-55156ce2-327a-11e8-8d2f-10a4d9fd3b0d.png)
![untasdfitled](https://user-images.githubusercontent.com/28967378/38017491-e4a309a0-327a-11e8-92eb-8c21641b46b9.png)

**Comment by danyj** [comment]
thats what I am missing ,  I dont see the column start new row

**Comment by danyj** [comment]
closing , was hidden via CSS
