### ISSUE TITLE
Hello, the plug-in produces errors on the client's device

### ISSUE THREAD

**Issue by killprime** [ThemeFuse/Unyson#3284]
At me all works perfectly! But on the client's device, on any browser, the admin panel does not work correctly. The console has the following errors:
![rmq56w8zc8w](https://user-images.githubusercontent.com/37850674/37996291-7984a7ac-325a-11e8-8a70-272f2d21738b.jpeg)

**Comment by ViorelEremia** [comment]
What browser version do you have? Maybe it is an old version. We don't support anymore the old browser version I mean for the builder admin edit. From your screenshot, it seems that you have windows 7 that is not supported anymore by Microsoft.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
