### ISSUE TITLE
"SyntaxError: Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by mahmoud-asfour** [ThemeFuse/Unyson#3287]
this error is appearing during save theme settings changes

"SyntaxError: Unexpected token < in JSON at position 0"

**Comment by ViorelEremia** [comment]
Try to inspect what is in position 0. https://github.com/ThemeFuse/Unyson/search?q=Unexpected+token&type=Issues&utf8=%E2%9C%93

**Comment by mahmoud-asfour** [comment]
I have solved this error by increase "max_input_vars" in "php.ini" file :)

**Comment by ViorelEremia** [comment]
Thank you for your solution.
