### ISSUE TITLE
Could you add Shaped section dividers?

### ISSUE THREAD

**Issue by omimexico** [ThemeFuse/Unyson#3289]
A great idea would be to add in CONTENT ELEMENTS is a option called: SHAPE DIVIDERS.
This basically transforms your regular  flat sections into a beautiful shape. Rounded, angled, cloud, etc.

**Comment by danyj** [comment]
This is framework git for developers that has the basics only. There is manual that you can use to create anything that you need http://manual.unyson.io/en/latest/extension/shortcodes/#cookbook
