### ISSUE TITLE
unyson auto installer (class-fw-auto-install)

### ISSUE THREAD

**Issue by DevWael** [ThemeFuse/Unyson#3290]
Hi, I'm trying to integrate the auto installer in my new theme and this is my config file
```php
return array(
	/**
	 * Array for demos (Plugins depending on the selected demo)
	 */
	'demos'              => array(
		'terex'       => array(
			array(
				'name' => 'WooCommerce',
				'slug' => 'woocommerce',
			),
		),
		'keynote'     => array(
			array(
				'name' => 'WooCommerce',
				'slug' => 'woocommerce',
			),
		),
		'the-college' => array(
			array(
				'name' => 'WooCommerce',
				'slug' => 'woocommerce',
			),
		),
		'hope'        => array(
			array(
				'name' => 'Give - WordPress Donation Plugin',
				'slug' => 'give'
			),
		),
		'creed'       => array(
			array(
				'name' => 'Give - WordPress Donation Plugin',
				'slug' => 'give'
			),
		),
		'the-trip'    => array(
			array(
				'name' => 'WooCommerce',
				'slug' => 'woocommerce',
			),
		),
	),
	'plugins'            => array(
		//Plugins for all demos
		array(
			'name'   => esc_html__( 'Contact Form 7', 'terex' ),
			'slug'   => 'contact-form-7',
			'source' => 'https://downloads.wordpress.org/plugin/contact-form-7.5.0.1.zip'
		),
		array(
			'name'   => esc_html__( 'Font Awesome 4 Menus', 'terex' ),
			'slug'   => 'font-awesome-4-menus',
			'source' => 'https://downloads.wordpress.org/plugin/font-awesome-4-menus.zip'
		),
	),
	'theme_id'           => 'terex',
	'child_theme_source' => 'http://updates.themefuse.com/plugins/the-core-child.zip',
	'has_demo_content'   => true
);
```
i want to disable the installing of the child theme plus i failed to install the plugins from the wordpress repository and it stops on the following error:

```
Installing required plugins ...
Sorry, we've encountered some errors, try to access this page later. 
```

so can you help me with that ?!

**Comment by ViorelEremia** [comment]
I think no one can help you. This format of autoinstall is taken from the core theme it is not a default feature of unyson. To skip install of child theme you need to adapt the code there is a lot of work to do. Check everything again because somewhere you changed something which is not correct. Check that is happing in class FW_Installer_Helper function download_and_install_a_package there are many reasons that could cause such error.

**Comment by bladuneet** [comment]
Hi, I am facing issues installing Goza NGO theme and plugins. I get "Sorry, we've encountered some errors, try to access this page later" when I try to install plugins and execution error when importing demo data. This is really frustrating for me as I have tried many things such as increasing disk limit from 40 t0 256Mbs.
Any assistance will be highly appreciated.
Thanks
Gerald
