### ISSUE TITLE
Demo Content Install

### ISSUE THREAD

**Issue by jicouple** [ThemeFuse/Unyson#3291]
A client is complaining of the following error when trying to use the 1 Click Demo:

Important: HTTP Loopback Connections are not enabled on this server. If you need to contact your web host, tell them that when PHP tries to connect back to the site at the URL http://sitename.in/wp-admin/admin-ajax.php (http://sitename.in/wp-admin/admin-ajax.php%60) and it gets the error Operation timed out after 2000 milliseconds with 0 bytes received. There may be a problem with the server configuration (eg local DNS problems, mod_security, etc) preventing connections from working properly.

He contacted the server provider and they told him that HTTP Loopback is enabled. The server returns response when connecting to http://sitename.in/wp-admin/admin-ajax.php

We've never had such issues until now.

Is this a bug? Or something is causing this?

see it : http://prntscr.com/izrqzl

**Comment by ViorelEremia** [comment]
Go to your client demo import page and check the browser console for some ajax requests if the response is a json format without any extra code before see img bellow.
Edit this file: \wp-content\plugins\unyson\framework\extensions\backups\helpers.php line 19(function fw_ext_backups_loopback_test) check what does the var $response contain?
![fasdfasdf](https://user-images.githubusercontent.com/28967378/38245264-12bd0a3c-3746-11e8-812e-05dc1fcc484b.png)

**Comment by ViorelEremia** [comment]
If you are on localhost then you have not correctly configured your server

**Comment by ViorelEremia** [comment]
also you can try to update your php version

**Comment by jicouple** [comment]
thank you so!
i will try

**Comment by sardaralia** [comment]
hello sir

**Comment by sardaralia** [comment]
please help me same error but not this issue

**Comment by rainb3rry** [comment]
Any update guys, i got same error
