### ISSUE TITLE
[Events] Exception raised. Cannot set property 'setup' of undefined fw-event.js

### ISSUE THREAD

**Issue by nhatnam14i3** [ThemeFuse/Unyson#3292]
Hello Unyson Supporter!

I migrate host, I get error jw-events.js, follow image bellow
![image](https://user-images.githubusercontent.com/24579239/38235383-2dae3032-374b-11e8-9004-74b405f097ae.png)

Now, button public on page not showing. Then, I debug, I see css hide this div tag, I display it and public page, this page not follow code Unyson, break layout.

Please help me!! Thanks Unyson Supporter

**Comment by nhatnam14i3** [comment]
Leave a comment

**Comment by ViorelEremia** [comment]
Disable unyson and try to add a new page check if default wp editor is initialized you can check the browser console if there are some errors about tinyMce object.

**Comment by nhatnam14i3** [comment]
Hello ViorelEremia, Thank you repply!!

I try disable unyson, then I refresh page edit. Now, This page showing button public, and console chrome haven't error. But break code layout unyson.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by nhatnam14i3** [comment]
Thank you!!
