### ISSUE TITLE
Is it possible to use the Visual Page Builder in a blog post, too?

### ISSUE THREAD

**Issue by LanceButters** [ThemeFuse/Unyson#3293]
I'm wondering if it's possible to include the Visual Page Builder also into post edit page.

**Comment by ViorelEremia** [comment]
do you mean like that
![edit post wp wordpress](https://user-images.githubusercontent.com/28967378/38251376-f454bbee-3759-11e8-8ceb-985ddc02ccb5.png)

**Comment by LanceButters** [comment]
@ViorelEremia Yes! How to achieve that?

**Comment by ViorelEremia** [comment]
![edit post wp wordpress](https://user-images.githubusercontent.com/28967378/38251643-b5e7b298-375a-11e8-8c3d-95b004413117.png)

**Comment by LanceButters** [comment]
@ViorelEremia Thank you, this worked
