### ISSUE TITLE
How to add <li> id code in section for scroll menu

### ISSUE THREAD

**Issue by Farzan-Shahid** [ThemeFuse/Unyson#3294]
I want to make one page theme with scroll menu. I want to use data-scroll-nav in <li> and data-scroll-index in section with same ids:

`$item_output .= '<a class="smooth" data-scroll-nav="'. $item->ID .'" '. $attributes .'>';`

Above code adds id in <li> but i'm unable to add same id in section.

`<section class="fw-main-row bg-img-full main-banner <?php echo esc_attr($section_extra_classes); ?> <?php echo ($custom_classes); ?>" <?php echo ($custom_id); ?> <?php echo $bg_video_data_attr; ?> style="<?php echo $section_style; ?>" data-scroll-index="**i want same id here**">`
 
Please help me out????

**Comment by ViorelEremia** [comment]
if you want to create a landing page you must rewrite some section files see here how: http://manual.unyson.io/en/latest/extension/shortcodes/index.html you must add a new section option where to set the id and in view.php show it. Read carefully the documentation because it's easy to do it
