### ISSUE TITLE
Ralentissement avec le plugin Unyson

### ISSUE THREAD

**Issue by ank01000** [ThemeFuse/Unyson#3295]
Bonjour, j'ai fait énornement de test sur ce site : https://www.vieonaturelle.com et lorsque je désactive le plugin UNYSON, le site est beaucoup plus rapide. Avec j'ai des lenteurs sur la boutique, la page d'accueil.. j'ai l'impression d'avoir un script qui plante...

**Comment by ivandotv** [comment]
Write in English please.

**Comment by ank01000** [comment]
Hello, I did enornement test on this site: https://www.vieonaturelle.com and when I disable the plugin UNYSON, the site is much faster. With I have slowness on the shop, the home page .. I feel like I have a script that crashes ...

**Comment by ViorelEremia** [comment]
solved: theme issue + old php version
