### ISSUE TITLE
Unyson Framework WordPress plugin

### ISSUE THREAD

**Issue by pcb3designs** [ThemeFuse/Unyson#3298]
Hello,
My site page builder layout is acting a bit weird. Everytime I update one of my pages, the layout changes. Please see picture below 
<img width="1416" alt="screen shot 2018-04-07 at 1 52 15 pm" src="https://user-images.githubusercontent.com/38164410/38458334-2ee6f4de-3a6b-11e8-812e-4b784f469d1c.png">

Not sure whats going on? Can you please advise? Website is www.adsystech.com.

Thanks,
Paul

**Comment by pcb3designs** [comment]
Using theme Apital (https://themeforest.net/item/apital-ultra-premium-business-wordpress-theme/13541405)

**Comment by ViorelEremia** [comment]
have you tried to contact the author of your theme? for example, the search icon from the header is a theme feature.

**Comment by pcb3designs** [comment]
Yes I did and they said this (see attached)

<img width="958" alt="screen shot 2018-04-12 at 6 03 54 pm" src="https://user-images.githubusercontent.com/38164410/38706653-efa6fc0a-3e7b-11e8-9ca7-e3a134e01e63.png">

**Comment by pcb3designs** [comment]
Every page that is selected as "Visual Builder Template" won't appear. It shows up as a blank page.

**Comment by ViorelEremia** [comment]
what is the issue? Unyson supports php7 you do not need to shrink the version. you get an error 500 because htaccess was changed. Check browser console in admin edit page. Have you the button "Visual Page Builder"?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
