### ISSUE TITLE
[QUESTION] - making extensions as plugins

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#330]
Is it possible to create framework extensions such as sliders/portfolio outside the theme and packed as plugins? This is a requirement from Themeforest you know.

If yes, will it follow same folder structure (framework-customizations, etc)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/300

Not yet. Yes, it will follow the same structure (framework-customizations). But make sure to prefix your extension names to not conflict with others extensions.
