### ISSUE TITLE
Display events as a table

### ISSUE THREAD

**Issue by lineacurva** [ThemeFuse/Unyson#3305]
Hallo,
I'd like to have the events displayed as a table (with starting date and end date, and possibly select the event category (i.e. 2016)). Does anybody know how to tackle this issue or has already taken it into account?

I find it could be helpful to have more readable representation of the incoming (or past) event at a glance.

thank you for suggestions, guys,
Luca

**Comment by ViorelEremia** [comment]
You can show events as a table use shortcode calendar from its options choose Population Method as events
