### ISSUE TITLE
How to link an image using Image Box feature?

### ISSUE THREAD

**Issue by PlannedG** [ThemeFuse/Unyson#3308]
I am using Image Box feature for a Partners page:  https://tedxbocaraton.com/partners/

However, there is no way to link the images in the Image Box editor.  I find this to be an oversight in the development.  People want to link images all the time.  Please tell me how I can use the Image Box feature and link the images.  Only way I see is if I don't use the Image Box feature and use Text Block instead, but that seems rather retarded if I could just use Image Box to display an image.

**Comment by ViorelEremia** [comment]
It's a theme issue, please contact the [theme author](https://support.themefuse.com/hc/en-us/requests/new).
Unyson is a plugin that allows theme authors to create fast and easy WordPress themes. Some of the issues come from themes.
