### ISSUE TITLE
Failed to connect to codeload.github.com

### ISSUE THREAD

**Issue by VisualWorkSpace** [ThemeFuse/Unyson#3310]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.
Can not download zip extensions "SEO". cURL error 7: Failed to connect to codeload.github.com port 443: Connection refused
WTF ????????????

**Comment by ViorelEremia** [comment]
Contact your hosting provider there's a firewall or some issues in your network configuration.

**Comment by VisualWorkSpace** [comment]
> I have no problems with hosting provider
In two hours again everything began to work
Thank you for attention

**Comment by VisualWorkSpace** [comment]
I have no problems with hosting provider
In two hours again everything began to work
Thank you for attention

**Comment by DanelOfficial** [comment]
> I have no problems with hosting provider In two hours again everything began to work Thank you for attention

same

**Comment by Bluefire786** [comment]
same issue why the request times out and the error is that the connection is not secure and the site wont load

**Comment by olaemy** [comment]
@Bluefire786 @ViorelEremia 
what did you use to solve this issue currently i am having the same issue, all the packages are not downloading 

- Syncing laravel/framework (v11.37.0) into cache
        Failed to download laravel/pail from dist: curl error 60 while downloading https://codeload.github.com/laravel/pail/legacy.zip/353ac12134b98e2e7c3333d916bd3e523931e583: SSL: no alternative certificate subject name matches target host name 'codeload.github.com'
    Now trying to download from source
  - Syncing laravel/pail (v1.2.1) into cache

  74/110 [==================>---------]  67%    Failed to download laravel/pint from dist: curl error 28 while downloading https://codeload.github.com/laravel/pint/legacy.zip/8169513746e1bac70c85d6ea1524d9225d4886f0: Connection timed out after 332890 milliseconds
    Now trying to download from source
  - Syncing laravel/pint (v1.19.0) into cache
