### ISSUE TITLE
Extensions Installation Error

### ISSUE THREAD

**Issue by sofosgeo** [ThemeFuse/Unyson#3312]
Hi, I am trying to install the extensions and I get the following error: 

“Cannot download the “Shortcodes” extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version”

Can you help out?

Thank you

**Comment by ViorelEremia** [comment]
what version of php do you have? try to increase it to a newest; if that does not solve the issue contact hosting provider to update curl and openssl current is to old
