### ISSUE TITLE
Unyson Multilingual Plugin

### ISSUE THREAD

**Issue by antalvespo** [ThemeFuse/Unyson#3313]
Hi guys, Unyson it´s compatible with some multilingual plugin?
Wich one you recommend?
I use WP Multilang
Have some shortcodes to use in multilingual?

thanks!

**Comment by ViorelEremia** [comment]
There is a plugin in your unyson extensions list ```Translate Press``` try it. You can read here about it: https://wordpress.org/plugins/translatepress-multilingual/

**Comment by antalvespo** [comment]
thanks!!!
