### ISSUE TITLE
MP4 Hero Image? Supported?

### ISSUE THREAD

**Issue by JMeisterDesign** [ThemeFuse/Unyson#3314]
I am using version 2.7.12 of the Unyson Framework and needing to use an MP4 on our Hero section of the site.

The MP4 is uploaded into the media section of our Wordpress site but it is not showing up when selecting a hero header image.

I can't find any information on how to do this but the Hero section does say "Upload Animated Background"

If it doesn't support MP4, what formats of animated data does it support?

**Comment by DevWael** [comment]
did you tried this field?

```php
array(
    'type'  => 'upload',
    'value' => array(
        /*
        'attachment_id' => '9',
        'url' => '//site.com/wp-content/uploads/2014/02/whatever.jpg'
        */
        // if value is set in code, it is not considered and not used
        // because there is no sense to set hardcode attachment_id
    ),
    'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
    'label' => __('Label', '{domain}'),
    'desc'  => __('Description', '{domain}'),
    'help'  => __('Help tip', '{domain}'),
    /**
     * If set to `true`, the option will allow to upload only images, and display a thumb of the selected one.
     * If set to `false`, the option will allow to upload any file from the media library.
     */
    'images_only' => true,
    /**
     * An array with allowed files extensions what will filter the media library and the upload files.
     */
    'files_ext' => array( 'doc', 'pdf', 'zip' ),
    /**
     * An array with extra mime types that is not in the default array with mime types from the javascript Plupload library.
     * The format is: array( '<mime-type>, <ext1> <ext2> <ext2>' ).
     * For example: you set rar format to filter, but the filter ignore it , than you must set
     * the array with the next structure array( '.rar, rar' ) and it will solve the problem.
     */
    'extra_mime_types' => array( 'audio/x-aiff, aif aiff' )
)
```
as you can see, you can set the allowed file types

**Comment by JMeisterDesign** [comment]
That looks like what I might be after. I'm relatively new to Unyson so I'm not sure what to do with that.

The theme I'm using has a few files in the framework-customizations folders but not many. I'm not sure if I paste that in a pre-existing file or make a new one?

**Comment by ViorelEremia** [comment]
What theme do you have? If you don't have some skills in php/css/js then ask your theme author for this feature. We do not know your theme code/docs; where is ``hero section``; what options do you have; where is that section; and so on; If you want to do yourself you need to read carefully unyson docs: http://manual.unyson.io/en/latest/
