### ISSUE TITLE
[question] create option types as an array of other option types

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#332]
Basically I am thinking about creating a new option type to only have an array of 3-4 other option types inside, just like the ones configuring the theme options.

I was thinking about it to simplify the workflow and the option files as well.

**Comment by sergiubagrin** [comment]
> Basically I am thinking about creating a new option type to only have an array of 3-4 other option types inside, just like the ones configuring the theme options.

Add it in different files and include like in this example: http://screencast.com/t/tbvsvzpzKUqX

**Comment by thednp** [comment]
For instance, in the theme options I have a custom post type 

<pre>
	'demo_option'  => array(
		'label' => __( 'Icon', 'unyson' ),
		'type'  => 'my-custom-type',
		'desc'  => '',
		'help'  => '',
	),
</pre>

Inside my custom-option-type file I only have something like this
<pre>
'header_background_color' => array(
	'type'         => 'multi-picker',
	'label'        => false,
	'desc'         => false,
	'picker'       => array(
		'select' => array(
			'label'        => false,
			'type'         => 'radio',
			'choices' => array(
				'pl1' => __( 'Color', 'unyson' ),
				'pl2' => __( 'Background Color', 'unyson' ),
			),
			'value'        => 'pl1',
			'desc'         => '',
			'help'         => '',
			'inline'	   => true
		)
	),
	'choices' => array(
		'pl1' => array(
			'color'    => array(
				'label' => '',
				'desc'  => '',
				'help'  => '',
				'type'  => 'color-picker',
				'value' => '#e51c23',
			)					
		),	
		'pl2' => array(
			'background'    => array(
				'label' => '',
				'desc'  => '',
				'help'  => '',
				'type'  => 'color-picker',
				'value' => '#e51c23',
			)					
		)
	),
	'show_borders' => false,
),				

</pre>

**Comment by moldcraft** [comment]
@thednp Have you tried

```php
'demo_option'  => array(
    'type'  => 'multi',
    'inner-options' => fw()->theme->get_options( 'whatever' ), // framework-customizations/theme/options/whatever.php
),
```

----

Or try to copy the `multi` option type, and replace [`$option['inner-options']`](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/multi/class-fw-option-type-multi.php#L44) with `$this->get_inner_options()` ...

**Comment by thednp** [comment]
@moldcraft thank you, I think this should do, I believe both solutions are viable for me. I will close this one and will come back if anything.

Thanks again.
