### ISSUE TITLE
Getting error SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by vinoddalvi** [ThemeFuse/Unyson#3320]
I am getting an error "SyntaxError: Unexpected token < in JSON at position 0" on saving the Gillion theme settings which uses Unyson plugin to create theme options.

I tried the solution https://github.com/ThemeFuse/Unyson/issues/3287#issuecomment-377818969 but it didn't work.

**Comment by ViorelEremia** [comment]
Check what is in position 0? usually, it is a php error in ajax response what error you can see it in the browser console see here how: https://www.youtube.com/watch?v=WOQDrGrd9H8

**Comment by vinoddalvi** [comment]
Here is what i am getting.

![screenshot 53](https://user-images.githubusercontent.com/5412913/39032882-0f7f5f4c-448d-11e8-863e-abdeb0db2765.png)
![screenshot 54](https://user-images.githubusercontent.com/5412913/39032883-0fb0bb00-448d-11e8-894e-ac6036705415.png)
![screenshot 55](https://user-images.githubusercontent.com/5412913/39032885-0fe2a43a-448d-11e8-9467-b4639d34b77f.png)
![screenshot 56](https://user-images.githubusercontent.com/5412913/39032886-10140e8a-448d-11e8-81ad-2bd8adab1744.png)

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by vinoddalvi** [comment]
Sent the details.
