### ISSUE TITLE
RGBA color picker not working in metabox

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#3321]
Its also not working in meta box 

![dfeg](https://dha4w82d62smt.cloudfront.net/items/0K2T3h0p07222S2H0m2S/Screen%20Shot%202018-04-19%20at%2011.24.16%20AM.png?X-CloudApp-Visitor-Id=1674463&v=b94c505a)

I have update scripts.js with `el.change();`

also class file with 
```
wp_localize_script(
	'fw-option-' . $this->get_type(),
	'_fw_option_type_' . str_replace( '-', '_', $this->get_type() ) . '_localized',
	array( 'l10n' => array( 'reset_to_default' => esc_html__( 'Reset', 'fw' ) ) )
);
```

@ViorelEremia can you please

Thanks

**Comment by ViorelEremia** [comment]
I tested with scratch and the-core theme. I think you call colorpicker to early. have you rewrote some javascript code?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
