### ISSUE TITLE
Unyson Gutenberg compatibility

### ISSUE THREAD

**Issue by ImprobableCode** [ThemeFuse/Unyson#3322]
What are the plans for Gutenberg compatibility? 

At present, neither the page builder or meta boxes work. Just looking for info

**Comment by ViorelEremia** [comment]
Compatibility with Gutenberg will be added when they will have a more stable version. I did that once and after a new version everything was broken again, so I can't spend time on every new version. That is sure because our themes also build on unyson.

**Comment by elbisnero** [comment]
Any update on this? it seems that WordPress is getting ready to release the gutenberg builder

**Comment by mensmaximus** [comment]
As a work around you might disable Gutenberg for pages if unyson is active using the filter gutenberg_can_edit_post_type.

**Comment by lmpixelsteam** [comment]
> Compatibility with Gutenberg will be added when they will have a more stable version. I did that once and after a new version everything was broken again, so I can't spend time on every new version. That is sure because our themes also build on unyson.

When, approximately, will support Gutenberg appear?

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/pull/110

**Comment by stevish-com** [comment]
Updated most of my WordPress sites to 5.0.2, but the one that relies on the visual page builder doesn't work when I update it. The newest update to unyson extensions seems to make everything disappear when I try to edit the post. Is there a plan in place to be fully compatible with the Gutenberg editor? Is it already compatible and there's just something else wrong with my install?

**Comment by MartinW2** [comment]
> Is there a plan in place to be fully compatible with the Gutenberg editor?
Highly interested in this as well...
