### ISSUE TITLE
Unyson theme settings doesn't work under IE11

### ISSUE THREAD

**Issue by mviniciusbarreto** [ThemeFuse/Unyson#3323]
The Unyson theme settings doesn't work when using Internet Explorer 11 under Windows 7. Microsoft still supports IE11 so I was hoping the theme settings works with IE11 too not just Microsoft Edge.

**Comment by ViorelEremia** [comment]
We tested with ie 7 on windows ten and is working. What is not working?

**Comment by mviniciusbarreto** [comment]
I have tested it with IE11 under Windows 7 and in fact the Theme Settings doesn't load.

**Comment by ViorelEremia** [comment]
Give us more details. Check browser console. Try to use unyson downloaded from github: https://github.com/ThemeFuse/Unyson that version doesn't use in production just for test.

**Comment by Kuzmanov** [comment]
I'm having the same issue on IE 11. Also, this happens only on production, on my local machine it works fine. I've 

`
SCRIPT1002: Syntax error
fw-reactive-options-registry.js (236,3)
SCRIPT5007: Unable to get property 'register' of undefined or null reference
fw-reactive-options-undefined-option.js (3,2)
SCRIPT5007: Unable to get property 'register' of undefined or null reference
fw-reactive-options-simple-options.js (19,3)
SCRIPT5007: Unable to set property 'fetchHtml' of undefined or null reference
fw-reactive-options.js (69,2)
SCRIPT5007: Unable to get property 'register' of undefined or null reference
scripts.js (158,2)
SCRIPT5007: Unable to get property 'register' of undefined or null reference
images-only.js (213,2)
`

`TypeError: Unable to get property 'startListeningToEvents' of undefined or null reference
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'startListeningToEvents' of undefined or null reference",
      message: "Unable to get property 'startListeningToEvents' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'startListeningToEvents' of undefined or null reference
   at Anonymous function ([SITE URL]/unyson/framework/static/js/fw-events.js?ver=2.7.10:142:7)
   at objectMap ([SITE URL]/unyson/framework/static/js/fw-events.js?ver=2.7.10:250:4)
   at trigger ([SITE URL]/unyson/framework/static/js/fw-events.js?ver=2.7.10:131:3)
   at Anonymous function ([SITE URL]/unyson/framework/static/js/option-types.js?ver=2.7.10:3:3)"
   }
`

**Comment by ViorelEremia** [comment]
@Kuzmanov try to use unyson github version

**Comment by Kuzmanov** [comment]
@ViorelEremia Still getting the same errors, plus a new one:
`SCRIPT5009: 'fwForm' is undefined 
themes.php (1003,3)`

**Comment by ViorelEremia** [comment]
So that is a browser issue or is something else? have you latest extensions? check them https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
