### ISSUE TITLE
Contact form international phone number validation

### ISSUE THREAD

**Issue by mara9784** [ThemeFuse/Unyson#3324]
Hi!
I am having issue with international phone number validation. What I need is to add "+" in front of telephone number in order to enable international phone format, but whenever I try to do that I get error that phone format is not correct(when number is without + contact form works fine). I know a bit of js and php so if there is a way to solve this issue with custom coding let me know(I tried few things but it all failed) of if there is option to enable that in wp-admin.

Thanks

**Comment by ViorelEremia** [comment]
You can't change validation with a bit of php you must overwrite the item number from extension forms in the path ```framework/extensions/forms/includes/option-types/form-builder/items/number/class-fw-option-type-form-builder-item-number.php``` you can read in docs haw you cand do it http://manual.unyson.io/en/latest/extension/shortcodes/index.html. Another way edit contact form in builder page admin and change the type of input number to text.
![edit page wp wordpress](https://user-images.githubusercontent.com/28967378/39116435-1ffe62f2-46ed-11e8-86a7-ec6d0ca32bef.png)
