### ISSUE TITLE
TypeError: fw.options is undefined

### ISSUE THREAD

**Issue by mrahda** [ThemeFuse/Unyson#3325]
Hi
I have Woffice WordPress theme. In local intranet environment, theme setting page does not appear. The console panel shows this error:

" [Events] Exception raised. Please contact support in https://github.com/ThemeFuse/Unyson/issues/new. Don't forget to attach this stack trace to the issue."

TypeError: fw.options is undefined
Stack trace:
fwEvents</this.trigger/<@http://172.16.100.137/portalsarvak/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:142:7
objectMap@http://172.16.100.137/portalsarvak/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:250:1
fwEvents</this.trigger@http://172.16.100.137/portalsarvak/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:131:1
@http://172.16.100.137/portalsarvak/wp-content/plugins/unyson/framework/static/js/option-types.js?ver=2.7.12:3:1

I attached phpinfo() result for your informaion.
[phpinfo().zip](https://github.com/ThemeFuse/Unyson/files/1935905/phpinfo.zip)

**Comment by mrahda** [comment]
[phpinfo().zip](https://github.com/ThemeFuse/Unyson/files/1935903/phpinfo.zip)

**Comment by ViorelEremia** [comment]
Can you try to replace the file ``` framework/static/js/fw-reactive-options-registry.js``` from your server with https://github.com/ThemeFuse/Unyson/blob/57d407cdb013a378a3d792662e2115f9c3e609c4/framework/static/js/fw-reactive-options-registry.js

**Comment by mrahda** [comment]
Yes! Now it works.
Thanks a lot.
