### ISSUE TITLE
Why do we have a 8h old release?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3330]
@ViorelEremia  The extension approval for 2.7.12 was issued Feb 6 , closed on Feb 7  with 2.7.12 release 

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/369

the release for it looks like it was created 8h ago https://github.com/ThemeFuse/Unyson/releases

are we getting ready for 2.7.13 or what is going on ?

**Comment by ViorelEremia** [comment]
I forgot to publish the tag here on github but on wordpress.org is that version. After I pushed on .org the tag on github remained as annotation tag so I had to come here and click on the publish button. I'm sorry I forgot
