### ISSUE TITLE
Ajax error when trying to fw_print( $entry_data ) when form successfully sent

### ISSUE THREAD

**Issue by LanceButters** [ThemeFuse/Unyson#3333]
I'm trying to print the form fields after a form is successfully sent like this

```
add_filter('fw:ext:contact-forms:sent', function( $entry_data ) {
  fw_print( $entry_data );
});
```

But when submitting the form an alert appears "Ajax error (more details in console)".

![console-error](https://user-images.githubusercontent.com/30236221/39299245-91e5c1fa-4948-11e8-9650-08bed043edf9.PNG)

Any idea how to fix this?

**Comment by ViorelEremia** [comment]
So it is right you get an error when javascript gets an html response instead of json. https://www.youtube.com/watch?v=WOQDrGrd9H8 you must send a json response.
