### ISSUE TITLE
Site Speed Issues

### ISSUE THREAD

**Issue by grohde** [ThemeFuse/Unyson#3337]
Having site speed issues on my site [link](http://www.southhouseco.com).
Have Unyson 2.7.12 and only have the Page Builder extension active.

Never had such bad speed problems on sites other than this one using Unyson & Pagebuilder. If I did something incorrectly I'll be happy to correct, but don't think I did.

**Comment by danyj** [comment]
first make sure you have no 404's
http://prntscr.com/jazul2

than lower the umber of css file ( 22 ) currently and so on,

**Comment by grohde** [comment]
Thank you. Wasn't aware of that 404. 

I will attempt to reduce number of CSS files and report back.
