### ISSUE TITLE
Read more tag?

### ISSUE THREAD

**Issue by zoell** [ThemeFuse/Unyson#3338]
I am using v 2.7.6 

What I am trying is to create posts with the Unyson Pagebuilder but I cannot make the read more feature work.

In the first section of the post I added a simple Text Block and added my text, also the Read more tag. After this block I added couple of more elements etc, but in the Blog Posts list page the website displays all the contents of the post page.

Is there any way to make this read more feature work on the post list page?

Thanks

**Comment by ViorelEremia** [comment]
No, you can't. The more tag works then you are in the wp loop and global $post is defined and you use the function ```the_content( $buttonReadMore, true )``` then that function extracts the excerpt or the text until the read more tag. But your content isn't in the key the_content or excerpt it is saved in a json to another key in meta table or options. So you must extract that text and through another function, this function will not work. Read here about read more tag: https://codex.wordpress.org/Customizing_the_Read_More
I think you can use something like that: 
```
$content = fw_get_db_post_option( $post_id, 'page-builder' );
// finde here in json the wp-editor option type that you want to extract the content before more tag
$parts = get_extended( $content );
echo $content_parts['main'];
echo '<a>read more</a>';
```
