### ISSUE TITLE
ICS files for events

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson#334]
Hi,

Instead of the option to add an event to your google calendar, is it possible to have an option to download an .ics file to import in your outlook, google calendar?

If yes, is it possible to have a popup box to confirm the download with this text : "Download this event 'name' taking place at 'date'. This file is compatible with Outlook and Google calendar."

Thank you

**Comment by sergiubagrin** [comment]
Hi @Nic787 

> Instead of the option to add an event to your google calendar, is it possible to have an option to download an .ics file to import in your outlook, google calendar?

We don't plan to add this option soon.

**Comment by Nic787** [comment]
Ok
