### ISSUE TITLE
Can we fix post imports?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3340]
@ViorelEremia  I saw few posts about it 
https://github.com/ThemeFuse/Unyson/issues/1609
https://github.com/ThemeFuse/Unyson/issues/2475

Exported 5 posts with WP exporter and see all meta in the xml, but on import on another site no builder content is there , only the html post version 

http://prntscr.com/jbrbew

using backup does not help since I need only these 5 and not 100+ other, 

or , copy/paste functionality for builder would be even better, I think VC has it

**Comment by danyj** [comment]
strange , the json and meta is imported in db, but builder is not showing it 
http://prntscr.com/jbrdzq

**Comment by ViorelEremia** [comment]
Try to use the latest page builder ext. and unyson github version. After importing edit the page and try to enable the builder if it is empty refresh the page and try: https://github.com/ThemeFuse/Unyson/issues/3297#issuecomment-380389224

**Comment by ViorelEremia** [comment]
I tried now the wp importer and is working well. What is wp exporter? the default export/import wordpress tool? I tested with default wordpress toolt import
