### ISSUE TITLE
Event Add to Google Calendar gives time difference.

### ISSUE THREAD

**Issue by qutub-bharmal** [ThemeFuse/Unyson#3342]
When I am trying to add to calendar from event single page, it displays approx 5:30 hours time difference.

For example if my event at 10:30 AM it displays at 4:00 PM in google calendar.

**Comment by qutub-bharmal** [comment]
Hello,
Any update here ???

**Comment by ViorelEremia** [comment]
I tested with two theme scratch theme and the core theme and I can't reproduce the issue.
Can you give us more details? What theme do you use? When is a difference of time before to post on google calendar or after post?

**Comment by qutub-bharmal** [comment]
Please check video:
https://www.useloom.com/share/d2c65282b49249cab50b32ce75de3393

**Comment by ViorelEremia** [comment]
Try to replace file ```unyson/framework/extensions/events/static/js/single-scripts.js``` with ```https://github.com/ThemeFuse/Unyson-Events-Extension/blob/56060cb665e710cd5219a372d35bf5988962b301/static/js/single-scripts.js```
If your theme overwrites extension events and the file exists: ```framework-customizations/extensions/events/static/js/single-scripts.js``` then also replace it.

**Comment by ViorelEremia** [comment]
did you try to remove browser cache?

**Comment by qutub-bharmal** [comment]
Yes I have removed browser cache.

**Comment by ViorelEremia** [comment]
has your first url offset parameter? something like: ```http://localhost/wp/fw-event-slug/event-b/?row_id=0&calendar=google&offset=-10800```

**Comment by qutub-bharmal** [comment]
Nope It's like:
http://localhost/eventsuite/events/marketing-conference/?row_id=2&calendar=google

**Comment by ViorelEremia** [comment]
Ok that is the issue the offset is the time zone difference. Are you sure you don't have any cache plugin or browser because i fixed it in my end is working.

**Comment by qutub-bharmal** [comment]
Nope There is only 2 plugins are active.  WooCommerce and Unyson.

**Comment by qutub-bharmal** [comment]
Where can I find the code of creating this first URL?
http://localhost/eventsuite/events/marketing-conference/?row_id=2&calendar=google

let me check my end why offset is not passing, where can I see this offset code ?

**Comment by ViorelEremia** [comment]
It is generated with js in browser.
Try to add this code:
```
( function ( $ ) {

	var insertParam2 = function ( key, value, uri ) {

		key = encodeURI( key );

		var kvp = key + "=" + encodeURI( value ),
			r = new RegExp( "(&|\\?)" + key + "=[^\&]*" );

		uri += ( uri.length > 0 ? '&' : '?' ) + kvp;

		return uri
	};

	var initButton = function () {
		var $button = $( this ),
			uri = $button.data( 'uri' ),
			gmtOffset = new Date().getTimezoneOffset() * 60,
			options = "toolbar=yes,menubar=yes,location=yes,status=yes,scrollbars=yes,resizable=yes,width=800,height=600,left=0,top=0";

		uri = insertParam2( 'offset', gmtOffset, uri );

		window.open( uri, "calendar", options );
	};

	$( document ).ready( function () {
		$( '.details-event-button button' ).on( 'click', initButton );
	} );

} )( jQuery );
```

**Comment by qutub-bharmal** [comment]
Okay I have got the issue,

I didn't use the class "details-event-button" so JS code was not calling.
