### ISSUE TITLE
Trying to write a file on Save options in unyson

### ISSUE THREAD

**Issue by najeeb-finelayers** [ThemeFuse/Unyson#3343]
Hi,

I am trying to write a file on saving Options but unfortunately i am unable to do this. I think the issue is with the function 'request_filesystem_credentials'. Can anybody please help,  here is my code 

	if(!function_exists('dynamic_style_file_write')) {
		function dynamic_style_file_write(){
			$body_text = fw_get_db_settings_option('body_text');
			$custom_css = '
				body,p,ul,li {
					font-size:'.$body_text['size'].'px;
					font-family:'.$body_text['family'].';
					font-weight:'.$body_text['style'].';
					color:'.$body_text['color'].';
				} ';
			
			global $wp_filesystem;

			$method = ''; //leave this empty to perform test for 'direct' writing
			$context = get_template_directory_uri() . '/assets/css'; //target folder
			
			$form_url = 'themes.php?page=fw-settings';
			
			request_filesystem_credentials($form_url, $method, true, $context);
			
			$file_path = $context. '/inline-style.css';
			
			if ( ! $wp_filesystem || ! $wp_filesystem->put_contents( $file_path, $custom_css ) ) {
				error_log( 'Could not generate the dynamic stylesheet', E_USER_WARNING );
			}
		}
	}
    add_action('fw_settings_form_saved', 'dynamic_style_file_write');

**Comment by ViorelEremia** [comment]
Don't write files in theme use wp-content/upload; we have that thing implemented in our theme the core so we create a file in uploads folder; at the beginning we did the same as you but after a lot of issues we move it to uploads folder:
```
$upload_dir                     = wp_upload_dir();
$style_dir                      = $upload_dir['basedir'] . '/the-core-style.scss'  ;
$wp_filessytem->put_contents($style_dir, 'csshere');

if (file_exists($upload_dir['basedir'] . '/the-core-style.css')) {
	wp_enqueue_style(
		the_core_style_file_name(),
		$upload_dir['baseurl'] . '/the-core-style.css',
		array(),
		filemtime($upload_dir['basedir'] . '/the-core-style.css')
	);
}
```

**Comment by najeeb-finelayers** [comment]
Hi ViorelEremia,

Thank you very much for your feed back. I have implemented the code you given but it's not working with $wp_filesystem. It works fine when i use **file_put_contents**. I have attached the video link of all the process. Please have a look. https://www.screencast.com/t/EJab2ytna

Why $wp_filesystem is not working. It works fine without unyson. Any idea about this ?

Thanks in advance

**Comment by ViorelEremia** [comment]
Try that:
```
if ( ! function_exists( 'dynamic_style_file_write' ) ) {
	function dynamic_style_file_write() {

		FW_WP_Filesystem::init_file_system();

		$body_text = fw_get_db_settings_option( 'body_text' );

		$custom_css = '
			body,p,ul,li {
				font-size:' . $body_text['size'] . 'px;
				font-family:' . $body_text['family'] . ';
				font-weight:' . $body_text['style'] . ';
				color:' . $body_text['color'] . ';
			} ';

		$upload_dir = wp_upload_dir();
		$file_path  = $upload_dir['basedir'] . '/theme-prefix-generated-styles.css';

		$insert_result = FW_WP_Filesystem::put( $file_path, $custom_css );

		if ( is_wp_error( $insert_result ) ) {
			FW_Flash_Messages::add( $insert_result->get_error_code(), $insert_result->get_error_message(), 'error' );
		}
	}
}
add_action( 'fw_settings_form_saved', 'dynamic_style_file_write' );
```

**Comment by najeeb-finelayers** [comment]
Wao. It worked. You are awesome ViorelEremia. 

Thank you very much
