### ISSUE TITLE
Multi select cant see tax/term

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3344]
Not sure what is wrong it worked before,  but multi select does not list taxonimies anymore. 

			'categories' => array(
				'type' => 'multi-select',
				'value' => array(),
				'label' => __('Specific categories', 'fw'),
				'desc' => esc_html__('Start typing the category names', 'fw'),
				'population' => 'taxonomy',
				'source' => array(
					'category',
					'product_cat',
					'page_category',
					'fw-portfolio-category',
					'fw-event-taxonomy-name'
				)
			),

on load and search returns 

`{"success":true,"data":[]}
`

I have 5 woo cats ,  and 1 posts cat and none come back , same things go for users 
http://prntscr.com/jctjf8
http://prntscr.com/jctjm1

Tested on 4 demos ,  only 1  works , all others return nothing, same options same theme, no restrictions, no js or php errors. 

Terms or tax are simply not returned and worst thing is that I have no idea what to look for. 

Only multi that does work is posts and that one does see all post types 

http://prntscr.com/jctk7w

**Comment by danyj** [comment]
`I think you don't have the taxonomy page_category try
`
I have page_category ,   enabled via my plugin ,

**Comment by danyj** [comment]
hm strange , now when I remove the fix , they are there , 

is there a transient that is created when these are indexed? 

I used optimize DB plugin on those 4 installs and it has option to delete all transients 
https://wordpress.org/plugins/rvg-optimize-database/


that might cause this, not sure

**Comment by danyj** [comment]
ah , no o , it is that fix , which also works if do this 


`array_intersect_key( array_fill_keys( $names, true ), array() )`

**Comment by danyj** [comment]
confirmed , other 4 installs , the commit you mad is the fix  for the search,
prepopulation not
 
but on all users do not work, 

all this worked before , and it works on one big install with many taxs, terms, posts so I cant distinguish as to why

**Comment by danyj** [comment]
Other 4 installs are new empty WP  4.9.5 installs , 
the one that is ok , is very 2 years old updated install.

**Comment by ViorelEremia** [comment]
What for user is not working? Mine is working

**Comment by ViorelEremia** [comment]
```
'categories' => array(
				'type' => 'multi-select',
				'value' => array(),
				'label' => __('Specific categories', 'fw'),
				'desc' => esc_html__('Start typing the category names', 'fw'),
				'population' => 'users',
				//'source' => array( 'editor', 'subscriber', 'author' )
			),
```

**Comment by danyj** [comment]
something is off completely , 

now I see the category ID, where when I applied the fix hour ago I saw the name
http://prntscr.com/jd7num

and cant find the category by name ( Woman ) anymore

when I select Bags , and save I see this 

http://prntscr.com/jd7ox0

and when I remove it and search for it again , cant find it

could this be the effect 

https://make.wordpress.org/core/2016/10/29/wp_taxonomy-in-4-7/

**Comment by ViorelEremia** [comment]
try the last commit

**Comment by danyj** [comment]
just did , same thing

**Comment by ViorelEremia** [comment]
Try to add 
```'categories' => array(
				'type' => 'multi-select',
				'value' => array(),
				'label' => __('Specific categories', 'fw'),
				'desc' => esc_html__('Start typing the category names', 'fw'),
				'population' => 'taxonomy',
				'source' => array(
					'category',
					'product_cat',
					'page_category',
					'fw-portfolio-category',
					'fw-event-taxonomy-name'
				),
				'show-type'   => true
			),
```
There is no transient

**Comment by ViorelEremia** [comment]
TRy

**Comment by danyj** [comment]
forget users , 

'administrator' role was missing 
that works and prepopulates properly 

but tax peropluate is still buggy

**Comment by danyj** [comment]
that is it!

**Comment by danyj** [comment]
all there 

http://prntscr.com/jd879y

**Comment by ViorelEremia** [comment]
don't understaand what is with users? is working

**Comment by danyj** [comment]
is working , 

I have one user only , role administrator 

the option had this 

				'source' => array(
					'editor',
					'subscriber',
					'author',
				)

added administrator  to the list and it came up

**Comment by danyj** [comment]
thnx much for the help , I thought I was going crazy 

but do you know why it works on the one old install? 
what was changed so much that no tax showed up ?

**Comment by ViorelEremia** [comment]
I read again the entire thread and I checked the last committees for this file, but I can't say why. If you can send me credentials then I will understand why; if that is still happening.

**Comment by danyj** [comment]
Is not happening now , and everything is on local , once I go live I can get you the theme.
