### ISSUE TITLE
Demo Content Install

### ISSUE THREAD

**Issue by dariomisic** [ThemeFuse/Unyson#335]
Hello,
Where are can found demo content install on scratch theme? http://demo.unyson.io/?page_id=691

When I install scratch theme in my admin panel I don't have Demo Content in Tools.

Any help?

Thank you.

**Comment by thednp** [comment]
There is none available yet, they say there's gonna be one with the future version of the theme.

**Comment by sergiubagrin** [comment]
> Where are can found demo content install on scratch theme? http://demo.unyson.io/?page_id=691

demo.unyson.io was created with Unyson 1.0.0 it is not compatibble with Unyson 2.0.0 Right now we work under new Scratc Theme and it will be compatible with 2.0.0 

> When I install scratch theme in my admin panel I don't have Demo Content in Tools.

If you want to activate Demo Content Install Tool it is needed to check this message: This feature by default is turned off and is enabled only when the WP_DEBUG constant is defined and its value is true.

For more details see this page: http://manual.unyson.io/en/latest/extension/contentdemoinstall/index.html

**Comment by dariomisic** [comment]
When I expect the new version of scratch theme which be compatible with
2.0.0?

Thank you again.

**Comment by sergiubagrin** [comment]
We work on it right now. I don't have an eta right now. Thanks

**Comment by dariomisic** [comment]
Ok, thak you.

**Comment by srhnyldz** [comment]
Hi,
When the demo theme will be released?

Thank you

**Comment by moldcraft** [comment]
Sorry, still have an eta.
But it's in development.
