### ISSUE TITLE
Page builder text editor enable to open

### ISSUE THREAD

**Issue by robiul-shagor** [ThemeFuse/Unyson#3350]
Hey Guys,
I have faced an issue with unyson page builder text shortcode issue. See this screencast [http://prntscr.com/jeo0lu](url) and tell what the thing I can do?

**Comment by ViorelEremia** [comment]
I don't see any screencast 404 page not found

**Comment by robiul-shagor** [comment]
Ok. So the URL is - [http://prntscr.com/jeo0lu](http://prntscr.com/jeo0lu)

**Comment by ViorelEremia** [comment]
I think it is a server issue. You can see through the errors that tinymce is not defined. That means your server is blocking direct requests to file wp-tinyce.php or it has wrong permissions. Please contact your hosting provider.
