### ISSUE TITLE
Why event Map is not showing in the frontend ?

### ISSUE THREAD

**Issue by NiloySarker** [ThemeFuse/Unyson#3351]
Hi,
I notice from a few weeks ago that **Events Extension** is not working properly.
when I set google map location from event post type http://prntscr.com/jeyucu
The map is not shown in the frontend http://prntscr.com/jeyvd0
I also tried to switch the premium theme to WordPress default theme but it's still not showing on the frontend.

**Comment by ViorelEremia** [comment]
It is not showing because you don't have added templates that are required to work. Your premium theme must support extension events. For that the theme developers must add views in path ```framework-customizations/extensions/events/views/single.php``` More info read here: http://manual.unyson.io/en/latest/extension/events/index.html#views

**Comment by NiloySarker** [comment]
Thanks a lot @ViorelEremia 
i am not sure how the single.php file is deleted from that folder.
 BTW, i am the theme authour :)

**Comment by ViorelEremia** [comment]
are you sure it was there?

**Comment by NiloySarker** [comment]
Maybe because it's shown in the frontend before.

**Comment by ViorelEremia** [comment]
Ok, I don't understand what is wrong. Take a llook at this repository: https://github.com/ThemeFuse/Scratch-Theme

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-parent/framework-customizations/extensions/events/views
