### ISSUE TITLE
Fatal Error in Page Builder

### ISSUE THREAD

**Issue by chelonso** [ThemeFuse/Unyson#3353]
Hi

I just installed Unyson in a clean wordpress installation.
activate the Page Builder extension.

When I enter the page editor ... I get the following error

`Fatal error: Call to a member function load_shortcodes() on a non-object in /var/www/html/wordpress/wp-content/plugins/unyson/framework/extensions/page-builder/class-fw-extension-page-builder.php on line 141`

The error also appears in frontend

My version of Unyson is 2.7.12 and WordPress 4.9.5

The Unyson extensions are well installed and disable all other wordpress plugins.

What is the problem?

**Comment by ViorelEremia** [comment]
What theme do you use? try to switch to a default wordpress theme

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
Have you some custom extensions?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.

**Comment by swinggraphics** [comment]
Same problem here. What is the fix?
