### ISSUE TITLE
Plugin does not show edit gear.

### ISSUE THREAD

**Issue by omimexico** [ThemeFuse/Unyson#3355]
When I installed the plugin on the Twenty Seventeen theme, I noticed that the edit section and edit column section was missing.  

Is there a way to activate the edit abilities?

**Comment by ViorelEremia** [comment]
Have you any errors? Please, show some screenshots how they are missing.

**Comment by omimexico** [comment]
![unyson](https://user-images.githubusercontent.com/19225920/39791092-9a1b95ca-5307-11e8-851b-6fff05259622.png)

Steps to see the error:
1. Install a fresh WP.
2. Activate any of the WP themes
3. Install Unyson plugin
4. Activate the plugin
5. Activate unyson viewer on page
6. add section and a column
7. Review section an column menu options and there will be no edit gear.

**Comment by ViorelEremia** [comment]
What browser do you use? Check browser console if there are any errors: https://www.youtube.com/watch?v=QYw02Z9oUfs. Are you on a localhost or online?

**Comment by omimexico** [comment]
Online. IP restricted.
Checking the console for errors was the first thing I checked. There were no errors.
It is a problem with the code. Probably a config or functions php

**Comment by ViorelEremia** [comment]
Ok, now I understand. That is not an issue by default unyson doesn't have options for shortcode column to add them you must read the unyson docs and have some skills of php/css/js: http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes
I tested with the twenty theme and everything is fine so I think you think that and column should have options like section. If I did not understand you correctly then send me some temporary credentials (admin): ```viorel@themefuse.com```. Please provide a link to this thread in the message.
