### ISSUE TITLE
Section and column blocks vanish after plugin update

### ISSUE THREAD

**Issue by omimexico** [ThemeFuse/Unyson#3356]
I have been using this plugin for a year or so.
Some of my websites are now being updated to the latest version on unyson plugin.
Once plugin update is complete, the section and column blocks are no longer visible.
The screen shot is what it looks like AFTER the plugin has been updated.

Note: The website on the front end still looks properly as it should.  
What is the fix to get my blocks back?
![missing blocks](https://user-images.githubusercontent.com/19225920/39819129-a42f8ed6-5370-11e8-9c7d-aa813c3b0d89.png)

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
