### ISSUE TITLE
PHP Warnings for session_start() headers already sent

### ISSUE THREAD

**Issue by sparky672** [ThemeFuse/Unyson#3357]
I have an `error_log` file being generated within the `wp-admin` directory.

Every single line contains a warning that is generated by line 228 in `hooks.php`...

> 09-May-2018 17:04:32 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /xxxx/public_html/xxxxxx.com/wp-includes/functions.php:3170) in /xxxx/public_html/xxxxxx.com/wp-content/plugins/unyson/framework/includes/hooks.php on line 228

Since this all started sometime yesterday when I was working on the site, I think I may have inadvertently caused this problem.  I just don't know how.

Any suggestions appreciated.

**Comment by ViorelEremia** [comment]
I think that is happening because your hosting provider had changed or upgraded php version. Try and ask your hosting provider why this is happening.

**Comment by sparky672** [comment]
> I think that is happening because your hosting provider had changed or upgraded php version. Try and ask your hosting provider why this is happening.

Since this just happened yesterday, it's far more likely that I may have accidentally deleted a file or directory.  Otherwise, PHP version is still 5.6.30

**Comment by ViorelEremia** [comment]
Then remove unyson and install it again.

**Comment by sparky672** [comment]
> Then remove unyson and install it again.

Deactivate and activate ... or delete and reinstall?

**Comment by ViorelEremia** [comment]
Delete and install it again but I still think something changed on the server

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
