### ISSUE TITLE
After update plugin and wordpress visual page editor don't work

### ISSUE THREAD

**Issue by AfanasievAM** [ThemeFuse/Unyson#3358]
![2018-05-10 14 53 34](https://user-images.githubusercontent.com/39158173/39868391-084cfb46-5462-11e8-91e6-a06ab223edeb.png)

I can't edit any page on web site.  Visual page editor don't view content of page.

Pls help.

**Comment by ViorelEremia** [comment]
Try to update unyson extensions: https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
Remove any chache browser, wordpress, server
