### ISSUE TITLE
User Cannot Reset Password

### ISSUE THREAD

**Issue by OffsiderAU** [ThemeFuse/Unyson#3359]
Version 2.7.12 on WordPress 4.9.5

When we create a new user via the admin they are sent an email to set their password.  The link takes them to the reset screen.  When they click Reset, they get an error page (attached).  

We have determined that this is caused by Unyson.

When we disable Unyson, we can update the password, but it breaks the site.

![capture](https://user-images.githubusercontent.com/39158680/39873980-cd79863a-54af-11e8-990e-2ffb315de83c.JPG)

**Comment by danyj** [comment]
I doubt it is Unyson ,  it is more likely the theme? Did you disable the theme first?

**Comment by OffsiderAU** [comment]
No, as soon as we disabled Unyson we were able to enter the password.

**Comment by danyj** [comment]
yes but the theme was built on it and if developers have extended something in the theme that it is theme that control's it. 

leave Unyson on , switch to default theme than test

**Comment by OffsiderAU** [comment]
Yes, thank you for the insight,  we are reaching out to them for support.
