### ISSUE TITLE
[suggestion] sample data with one image per post type

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#336]
Providing themes with sample data doesn't require distributing demo sample images and if you do decide to go for, you need either license or watermark. Now I don't say don't buy licenses, do and support the photographers.

What I mean is: make the sample data installation lighter + smoother and context oriented. So think about a new option for your back-up extension to be able to export both:
- full site back-up
- sample data

The sample data in fact has
- one sample image for each post type
- we can even include a placehold.it image or internally generated image for the specified image size (that would be awesome)
- a bundle theme with sample data inside is 90-99% smaller size

Pretty neat, right?

**Comment by sergiubagrin** [comment]
> a bundle theme with sample data inside is 90-99% smaller size

I'm not sure about 90-99% but you are right. Right now we use photoshop filter which blur original images.  

I will think about this option. Thanks

**Comment by thednp** [comment]
Hey remember this?
Any plans or ideas on how to make it happen?

**Comment by thednp** [comment]
Buzz to @moldcraft or @andreiglingeanu.

**Comment by moldcraft** [comment]
Sorry, no plans.
