### ISSUE TITLE
How could I create RGBA gradient colors

### ISSUE THREAD

**Issue by shaonsina** [ThemeFuse/Unyson#3360]
I would like to create RGBA gradient colors. How could I create?

**Comment by ViorelEremia** [comment]
There are multiple option types in the scratch theme: https://github.com/ThemeFuse/Scratch-Theme
Gradient color see here: https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/theme/options/demo.php
