### ISSUE TITLE
How to remove Mobile Menu 

### ISSUE THREAD

**Issue by ActuallyAaron** [ThemeFuse/Unyson#3361]
I'm working on a website that is going to be mostly one page and I don't want a header menu. I removed the menu and it looks fine for desktop, but on mobile, there is a large container that appears at the top of the page where it would normally have the 3 horizontal lines that would allow users to navigate the header menu. Any thoughts on how to remove it?

**Comment by danyj** [comment]
Contact theme provider , this is framework git.
