### ISSUE TITLE
3rd party shortcodes in page builder not rendering as shortcodes

### ISSUE THREAD

**Issue by huhnej31** [ThemeFuse/Unyson#3363]
We recently had an agency build us a custom worpdress theme using Unyson using the page builder. What I found out after we got the site is that any new shortcode we try and insert using brackets such as [su_heading]This is heading.[/su_heading] , which you can see here - http://mkebrewingdev.wpengine.com/test-3/ does not render as a shortcode, but rather it renders as text. We are entering these into the "text block" element.

I've searched the backend, searched these forums, but can't figure out why shortcodes don't work using the page builder. If we don't use the page builder but rather the default editor, all third party shortcodes works just fine. I understand that third party plugins performance or formatting aren't supported, but since they don't render at all makes me think there is some type of problem. Any help would be greatly appreciated!!

**Comment by ViorelEremia** [comment]
I tested with 3 themes and shortcode text block is working with shortcode. is it rewritten by the theme?

**Comment by huhnej31** [comment]
Thanks for the reply. I cannot find anything that would strip it out, but I also don't know all the ways to do it. I've done things like search the entire site for "strip_shortcodes" but have had 0 results. Any suggestions of what could potentially disable shortcodes in only the page editor? Or if I provided you with FTP access would look to make sure it's not an error?

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
It is a theme issue. The shortcode text block is overwritten by theme so the theme author must change the return value of function ```pair_format_wp_editor_content``` from ```return $content_formatted; ``` to ```return do_shortcode( $content_formatted );``` File: ```themes/mke-brewing/inc/format-text-block.php```

**Comment by huhnej31** [comment]
THANK YOU!!! Very much appreciated.
