### ISSUE TITLE
Contact form not working in Wordpress theme

### ISSUE THREAD

**Issue by NoahSmits** [ThemeFuse/Unyson#3364]
Dear,

I have the Wordpress Theme ' Guardian' by the company 'Haintheme'.
They offer a contact form in their Theme which is generated by Unyson.

The contact form is not working. The guys from Haintheme checked it and say it's configured properly. They asked me to create a ticket here, since you guys can probably help me solve this issue.

I keep ketting the error that the message could not be send.
Can someone help me with this? I'll give my credentials in private I guess?

Best,

Noah Smits
www.abcongedierte.nl

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.
