### ISSUE TITLE
no css animations and other issues after upgrade

### ISSUE THREAD

**Issue by jesussanmol** [ThemeFuse/Unyson#3366]
Hi,

After upgrade to last version of unyson all pages components with css animations enbled not showing, I have to disable animations to get visible components again.
Other issue, when I configure an image component that have to open a video in a pop up does not work too; the video open in a new youtube page not in a pop up inside my site.

Any one can help me? I dont know where is the problem and I try everything I could

Thank you

**Comment by ViorelEremia** [comment]
did you contact the author of the theme? We have a repository here: https://github.com/ThemeFuse/Unyson-Extensions-Approval 
before each new unyson version, we create a prerelease so in this way, all developers of themes can test if everything is ok with the new version.
