### ISSUE TITLE
Contact form send mail with small fonts

### ISSUE THREAD

**Issue by BC08** [ThemeFuse/Unyson#3368]
Hello,
Unyson is great framework and I testing it now.
I have find bug. Wen I create a contact form with "paragraph text" field, email sent is with small wery small font for paragraph text. All other fields send normal text with normal fonts.

Pleas any one know were in code ore in settings I change this font size.
Thank you guys...

**Comment by ViorelEremia** [comment]
What do you use? wp-mail or smtp? I tested it and I don't see any small font.

**Comment by BC08** [comment]
I use wp-mail.
Thank you for your replay...

**Comment by BC08** [comment]
thank you for your replay,
I use wp-mail

**Comment by BC08** [comment]
pleas ViorelEremia help me

**Comment by ViorelEremia** [comment]
Try to inspect in your inbox who adds samall font size. do you know how to use browser inspect console?

**Comment by BC08** [comment]
yes I know. it is in gmail inbox. 
will try now

**Comment by BC08** [comment]
![1](https://user-images.githubusercontent.com/39338147/40121109-1870d79a-5921-11e8-9a35-716529c3c967.JPG)
here is screanshoot from my email, sent by form

**Comment by ViorelEremia** [comment]
Have you a file in path:```activeTheme/framework-customizations/extensions/forms/extensions/contact-forms/views/email.php``` This is the file where you can overwrite the email styles

**Comment by BC08** [comment]
Thank you for your replay,
in my folder extensions there is not folder forms. 
I use theme Scratch Parent Version: 1.0.7 from themeFuse
