### ISSUE TITLE
Latest update crashed site 

### ISSUE THREAD

**Issue by jmiszlay** [ThemeFuse/Unyson#3370]
Just attempted to update the Unyson plugin on my wordpress site. The update produced an error and then kicked me out of WP-admin and now the front end of the website is producing this error when trying to load it:
"This page isn’t working
website is currently unable to handle this request.
HTTP ERROR 500"

I had to go into my GoDaddy hosting and restore a previous back up to get the site working again. Any idea on what could be causing this crash? I also attached a screenshot of one of the errors I received when trying to load the site. 

![unyson error](https://user-images.githubusercontent.com/39347928/40139129-bf010bca-5903-11e8-8bb8-9678a1c5d814.PNG)

**Comment by ViorelEremia** [comment]
Enable wp debug and try again. I think you have a fatal error.
Add to wp-config.php in your site root:
```
define( 'WP_DEBUG_DISPLAY', true );
```
Change line with code: ```define( 'WP_DEBUG', false );``` to ```define( 'WP_DEBUG', true );```

**Comment by ViorelEremia** [comment]
if the problem is repeated then do the following.
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by vandettagroup** [comment]
Hello I need help. 

I recently bought Luxa theme and it comes with unyson plugin with Portfolio and demo content extensions. As soon as I manually installed unyson and extensions and activated them, the WP crashed totally without any chance for recovery. 

Here is the screenshot of error i get: https://www.awesomescreenshot.com/image/49875482?key=4a0bb349d43b047912c1ba3810413cc7
