### ISSUE TITLE
Unyson Builder: Request Entity Too Large

### ISSUE THREAD

**Issue by PrattisOC** [ThemeFuse/Unyson#3371]
For all my websites that use Unyson. Using the page builder and hitting update lead to this error
413 
![ss](https://user-images.githubusercontent.com/39362748/40158527-deea5742-5959-11e8-98e6-38ed92f954ed.png)

**Comment by ViorelEremia** [comment]
It is a server issue, increase post_max_size, upload_max_filesize: http://docs.themefuse.com/the-core/your-theme/theme-settings/how-to-set-a-maximum-file-upload-size

**Comment by PrattisOC** [comment]
This didnt help at all
