### ISSUE TITLE
Add a PHP code into page

### ISSUE THREAD

**Issue by magisterson** [ThemeFuse/Unyson#3372]
I am buliding website using UNYSON. I have reservation script made by programmer. Before it was using by  chooseing right template on right hand side on backend. templates where in /my_template_name/template_parts/PHP-file.php

Is there a way to put code from this PHP file into unyson "Text block"? Or i have to choose template from list on right hand side?

**Comment by ViorelEremia** [comment]
The text block shortcode doesn't support execution of the string code. If you want that feature you must contact your theme author. For unyson we can't do it because of security reasons I advise you not to use such a render type.
