### ISSUE TITLE
Issue deleting records of fw-event-search post type, when event is update.

### ISSUE THREAD

**Issue by qutub-bharmal** [ThemeFuse/Unyson#3373]
Please check function "_fw_remove_all_event_children_data" in file: https://github.com/ThemeFuse/Unyson-Events-Extension/blob/56060cb665e710cd5219a372d35bf5988962b301/extensions/events-tags/class-fw-extension-events-tags.php

It does not deleting all the records, I think you need to add parameter in $args array "posts_per_page" with value -1.

**Comment by qutub-bharmal** [comment]
I think you also need to change the status of all records in "fw-event-search" post types, when event trashed. I have checked it does not working.

**Comment by qutub-bharmal** [comment]
Also on Delete event, it does not delete all the records, here also requires parameter  "posts_per_page" with value -1.

**Comment by ViorelEremia** [comment]
About the status trash try this commit: https://github.com/ThemeFuse/Unyson-Events-Extension/commit/16670449486a5ad19fe61a07a2d3f4ad9c3cc3a3

**Comment by qutub-bharmal** [comment]
It will be in next update, correct?

I can't see still 'posts_per_page' argument. please check screenshot: https://prnt.sc/jjgkb9

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson-Events-Extension/commit/1077a0b3018add9b8211026b83be0516a18d49ab

**Comment by ViorelEremia** [comment]
you can download now from github and replace all files in unyson/framework/extensions/events
after uupdate that can not work so the better way is to test now

**Comment by qutub-bharmal** [comment]
Okay I have tested it works now,
But what do you mean by "after uupdate that can not work"?

It will be in next update and it should be work after update too, correct?

**Comment by ViorelEremia** [comment]
It will be in the next update. I mean for me can work well but for you can't so the better way is to test on both sides.

**Comment by qutub-bharmal** [comment]
Okay

**Comment by qutub-bharmal** [comment]
Still issue with deleting all search items when we have more than 20+ items.

By default it takes posts_per_page settings from WordPress settings, and that is 20 so it deletes only 20 items on update of event.

You need to add one more parameter there, posts_per_page = -1

Please check:
https://github.com/ThemeFuse/Unyson-Events-Extension/blob/56060cb665e710cd5219a372d35bf5988962b301/extensions/events-tags/class-fw-extension-events-tags.php#L349
