### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ) fw-reactive-options-registry.js:236 

### ISSUE THREAD

**Issue by qaavezatech** [ThemeFuse/Unyson#3374]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.

Getting following error in theme settings page
Uncaught SyntaxError: Unexpected token )
fw-reactive-options-undefined-option.js:3 Uncaught TypeError: Cannot read property 'register' of undefined
    at fw-reactive-options-undefined-option.js:3
    at fw-reactive-options-undefined-option.js:287
fw-reactive-options-simple-options.js:19 Uncaught TypeError: Cannot read property 'register' of undefined
    at https://gsbahub.eboardsolutions.com/stagegsbahub/wp-content/plugins/unyson/framework/static/js/fw-reactive-options-simple-options.js?ver=4.9.5:19:13
    at Array.map (native)
    at https://gsbahub.eboardsolutions.com/stagegsbahub/wp-content/plugins/unyson/framework/static/js/fw-reactive-options-simple-options.js?ver=4.9.5:18:15
    at https://gsbahub.eboardsolutions.com/stagegsbahub/wp-content/plugins/unyson/framework/static/js/fw-reactive-options-simple-options.js?ver=4.9.5:109:3
fw-reactive-options.js:69 Uncaught TypeError: Cannot set property 'fetchHtml' of undefined
    at fw-reactive-options.js:69
    at fw-reactive-options.js:274
images-only.js?ver=2.7.12:213 Uncaught TypeError: Cannot read property 'register' of undefined
    at images-only.js?ver=2.7.12:213
    at images-only.js?ver=2.7.12:252
scripts.js:5 Uncaught TypeError: Cannot read property 'register' of undefined
    at scripts.js:5
    at scripts.js:98
scripts.js?ver=2.7.12:158 Uncaught TypeError: Cannot read property 'register' of undefined
    at scripts.js?ver=2.7.12:158
    at scripts.js?ver=2.7.12:177
scripts.js?ver=2.7.12:50 Uncaught TypeError: Cannot read property 'register' of undefined
    at HTMLDocument.<anonymous> (scripts.js?ver=2.7.12:50)
    at i (load-scripts.php:2)
    at Object.fireWith [as resolveWith] (load-scripts.php:2)
    at Function.ready (load-scripts.php:2)
    at HTMLDocument.K (load-scripts.php:2)
fw-events.js?ver=2.7.12:150  [Events] Exception raised. Please contact support in https://github.com/ThemeFuse/Unyson/issues/new. Don't forget to attach this stack trace to the issue.
fw-events.js?ver=2.7.12:156 TypeError: Cannot read property 'startListeningToEvents' of undefined
    at fw-events.js?ver=2.7.12:142
    at objectMap (fw-events.js?ver=2.7.12:250)
    at Object.fwEvents.trigger (fw-events.js?ver=2.7.12:131)
    at option-types.js?ver=2.7.12:3
(anonymous) @ fw-events.js?ver=2.7.12:156

Version 4.9.5 | Unyson 2.7.12 | Woffice 2.4.1
How to fix this issue.

![unyson_js_errors](https://user-images.githubusercontent.com/39375308/40179239-70f07a3e-5a01-11e8-8198-517a4a059adb.png)

**Comment by ViorelEremia** [comment]
Have you the latest extensions? https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
