### ISSUE TITLE
how do I integrate some of my own columns with built-in columns

### ISSUE THREAD

**Issue by shaonsina** [ThemeFuse/Unyson#3375]
I would like to create some columns. like: 2/5, 3/5, 4/5 & 5/6.
I created **config.php** file. Located:
**theme-name\framework-customizations\extensions\builder\config.php**

![screenshot_4](https://user-images.githubusercontent.com/20015610/40181546-25ae4f60-5a0b-11e8-87e1-a9ee85265586.png)

Also created **static.php** file in **theme-name\framework-customizations\extensions\builder** folder 

![screenshot_5](https://user-images.githubusercontent.com/20015610/40182519-6caf8eea-5a0d-11e8-8147-3688c6654bfe.png)

and
**frontend.css** file in **theme-name\framework-customizations\extensions\builder\static** folder with my own classes.

then I created **config.php** & **options.php** files in **theme-name\framework-customizations\extensions\shortcodes\shortcodes\column** folder
and **thumbnails** folder with my own icons for each column item and **view.php** in **views** folder.
so the result is:

![screenshot_2](https://user-images.githubusercontent.com/20015610/40183566-fab7af54-5a0f-11e8-967f-f529d8ad4b5d.png)

But the problem is column items showing full width in builder window.

![screenshot_3](https://user-images.githubusercontent.com/20015610/40183793-80851b3a-5a10-11e8-8bae-208c1aa169d1.png)

So how do I integrate some of my own columns with built-in columns??
or
how do I integrate some CSS with built-in CSS in the backend for column items???

**Comment by ViorelEremia** [comment]
Load your file css to backend. Remove the if ( ! is_adminJ() )

**Comment by shaonsina** [comment]
How to load in the backend for **builder extension**???
Can you give a illustrate or screenshot??

**Comment by ViorelEremia** [comment]
You must remove the if from your static.php https://user-images.githubusercontent.com/20015610/40182519-6caf8eea-5a0d-11e8-8147-3688c6654bfe.png
```
wp_register_style(
	'fw-ext-builder-frontend-grid',
	get_template_directory_uri() . 'framework-customizations/extensions/builder/static/frontend-grid.css',
	array(),
	fw()->manifest->get_version()
);
```
And please don't paste code as images add code inside to three back quotes \`\`\`Youre code here\`\`\`

**Comment by shaonsina** [comment]
Thanks.
But the problem not solved.

![screenshot_3](https://user-images.githubusercontent.com/20015610/40237798-3feb4c5c-5ad3-11e8-8eef-19e771f08584.png)

This CSS file doesn't load in the backend. Only loading for the frontend.

**Comment by ViorelEremia** [comment]
You can't load in backend a file css without overwrite the main class of shortcode for exemple for colum you must rewrite this tthile: https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/column/class-fw-shortcode-column.php
in init function add your code added above.
