### ISSUE TITLE
Unyson Wont even load 

### ISSUE THREAD

**Issue by MarkEvans99** [ThemeFuse/Unyson#3377]
Hi. 

The unyson plugin won't even load on my site.
I cant build pages or anything and I have now missed a deadline.

Please, could someone assist with this problem as soon as possible?

Kind regards.

**Comment by MarkEvans99** [comment]
Hi.

I have updated, uninstalled, re-installed, cleared cache from everywhere.

Unfortunately, nothing has worked.

Kind regards.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by MarkEvans99** [comment]
Thank you.

I will email you shortly

**Comment by ViorelEremia** [comment]
Is your server on cloudways?

**Comment by MarkEvans99** [comment]
Not as far as i know

**Comment by MarkEvans99** [comment]
I have sent you an email
