### ISSUE TITLE
Trying to set custom options priority in posts

### ISSUE THREAD

**Issue by najeeb-finelayers** [ThemeFuse/Unyson#3379]
Hi,

I want to set the priority for custom options created with unyson. Currently the options are placed at the end of the page, after the excerpts, discussion, author ... 

The options should be shown after the WordPress Text Editor. Any idea how to achieve this ?

Here is a screenshot link for better understanding https://prnt.sc/jje1ii

**Comment by ViorelEremia** [comment]
By default, unyson creates meta boxes with priority default. Let say you want to change the priority of events meta box:
```
add_action( 'fw_post_options', function( $options, $post_type ) {
	if ( 'fw-event' !== $post_type ) {
		return $options;
	}

	$options['main']['priority'] = 'high';

	return $options;
}, 11, 2 );
``` 
Or you can change it in your theme: ```YourTheme/framework-customizations/theme/options/posts/post.php```
```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$options = array(
	'main' => array(
		'title'   => false,
		'type'    => 'box',
		'priority' => 'high',
		'options' => array(
			'fuck' =>  array (
				'label' => __('Label', 'fw'),
				'desc' => esc_html__('Desc', 'fw'),
				'value' => 'aaaa',
				'type' => 'text'
			),
		),
	),
);
```

**Comment by najeeb-finelayers** [comment]
Thank you very much. Both solution works :+1:
