### ISSUE TITLE
page builder not working

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#3384]
Hi, I've got errors in console when open a page to edit with page builder and avoids to show me the page builder. This error only happens with a particular page. I have another page created with page builder and I have no issues to edit it.
I got 44 errores in the console. The first 2 are:
Uncaught ReferenceError: jQuery is not defined at load-scripts.php?
Uncaught ReferenceError: fw is not defined at load-shortcodes-data.js?ver=1.3.27:15
I have no idea how to debug this.

**Comment by ViorelEremia** [comment]
Go to your account cloudflare and find the option "Rocket load", disable it.

**Comment by mbtocalli** [comment]
Thanks! That works!!!!!
