### ISSUE TITLE
Problems with www.youtube-nocookie.com/embed/video-id

### ISSUE THREAD

**Issue by Nepsha1986** [ThemeFuse/Unyson#3385]
www.youtube-nocookie.com/embed/video-id do not work on "section" background.

**Comment by ViorelEremia** [comment]
I don't know what is that, but i checked the google docs I can't find any words about this nocookie and also tried to load some videos with this url it is not working, also I find some issues with browser compatibility. So we think it is not a bug in unyson, if you want to add the support please read the unyson docs how you can overwrite unyson shortcodes.

**Comment by danyj** [comment]
it works only for embeds and you cant have it as video BG since it cant auto play, user must click on play button. This is GDPR thing
