### ISSUE TITLE
Fit2Fat Wordpress Theme - DEMO Content Install

### ISSUE THREAD

**Issue by CWingrove** [ThemeFuse/Unyson#3386]
Fit2Fat Wordpress Theme

I receive the following error whilst installing the DEMO content;

**Failed to create tmp table _fwbk_wpom_commentmeta. COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4'**

Have tried deactivating other plugins, same result.....

**Comment by CWingrove** [comment]
Thank you, I have sent you some details for you to login to my site as the update did not resolve the issue.

**Comment by ViorelEremia** [comment]
I have not received any messages with credentials

**Comment by ViorelEremia** [comment]
can you send me credentials for an ftp account?

**Comment by CWingrove** [comment]
Host: ftp.tigerfreestyle.co.uk

User: rampagekickboxing@tigerfreestyle.co.uk

Password: NeedleMouse230691


Quoting ViorelEremia <notifications@github.com>:

**Comment by danyj** [comment]
@CWingrove  if everything is ok change your site and FTP, passwords, everyone that follows this git has received an email with the credentials you posted live. Do not do this for your won sake.

**Comment by CWingrove** [comment]
Thanks, I have changed them all :-)
