### ISSUE TITLE
Brizy Visual Page Builder is Here. 

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#3387]
Hey guys, 

I'm super excited to tell you that we've launched Brizy, a visual page builder for WordPress that brings an unmatched ease of use to the table. Find out how it works and features here: https://brizy.io/. 

I think this is great for all of us since we have a great opportunity to bring all our themes to the new visual front end editing era. 
 
# How will Brizy impact Unyson

We've got a lot of questions if Brizy will replace Unyson and the answer is no. Not by a long shot. We'll continue to support and improve Unyson.

Maybe it will replace the current unyson page builder and not because we'll disable it but only because it will became irelevant in this new front end editing age. In my opinion the users will replace it eventually even if we want to or not. 

Not sure how long back-end editing will still be alive but in my mind is clear that it will disappear sooner rather than later. 

Here is how we see it:

## New developed Themes

We see Brizy working hand in had with Unyson: 
- you can create the theme with Unyson  (that we'll continue to support and improve)
- create the pages with Brizy

Tip: create any shortcodes you want or need with Unyson and bring them in the front end with the Brizy shortcode element. 

The back up extension will handle the demo import and it works with Brizy so you'll be able to give your clients a very easy way of editing the pages you create. I think it will be a great selling point as well. 

## Themes in development right now

If you are developing a theme right now and want to give your clients the power of modifying content on the front end with Brizy, then you'll need to re-create the pages with Brizy. There is no way around it because as I've touched here https://github.com/ThemeFuse/Unyson/issues/3237#issuecomment-372022676, an easy way to switch between the builders is not possible. 

The silver lining here is that you don't have clients yet so you will not get those questions "why can't I edit your pages on the front end?". 

Of course we don't force you to switch to Brizy, if you decide that the current visual builder is what you need, go ahead and use it, no problem. 

## Themes that are already launched 

If you have a theme already selling now, and want to update it on Brizy, you'll basically need to recreate all your pages in order for your clients to be able to edit them with Brizy. 

We have 54 themes on ThemeFuse and we've already started to move them on Brizy. It goes pretty fast because we only recreate the pages, all rest stays the same, 1-2 days per theme depending on the complexity and number of pages. 

Again, you don't need to switch to Brizy if you don't want to, use the current Unyson builder if it caters to your needs better. 

## Brizy in the near future

One of the reasons you might be reticent about Brizy is that there are certain features that are not in there yet but are working on them. Let me tell you what's coming and what we have on our list in the near future: 

- shadows
- animations
- section dividers
- woo commerce elements
- live padding control for sections
- a developer API to let you extend Brizy the way you want, same way as Unyson. (this is further down the line)
- live resize for certain elements: images, maps, videos, etc

Keep in mid that you can create any shortcodes you want or need with Unyson and bring it in the front end with the Brizy shortcode element. 

## Unyson update 

We've created a Brizy extension and we will update Unyson tomorrow so that every user will have the opportunity to use Brizy and create new pages for his / her website. 

(Later edit: I should have been more clear in my initial post, the Brizy install will happen automatically in all Unyson powered themes.)

**Comment by pear1** [comment]
Hello,

Congrats with your new front-end page builder. :)

I have a one question related to moving to Brizy.
I have more than 30 custom made shortcodes with my current theme (which is selling for some time) and I want to move my demo content to Brizy.

Will I be able to move/use my custom made Unyson shortcodes? As my demos are based only on those?

**Comment by danyj** [comment]
> 

Tip: create any shortcodes you want or need with Unyson and bring them in the front end with the Brizy shortcode element.


how ?

**Comment by danyj** [comment]
>bring them in the front end

mean it will just render them , you will not be able to do live edit on those right?

**Comment by alexluncashu** [comment]
Hi,

yes, you can add it but you can't edit http://jmp.sh/hFzRJML

**Comment by pear1** [comment]
That is option for some small shortcodes like in your example.
But what can I do if I have created Unyson page builder shortcodes/elements with 30+ options like dropdowns and so on?

**Comment by DimiBaitanciuc** [comment]
@pear1 RIght now the example Alex gave is the only way to render your shortcodes in the front end with Brizy. You can't edit them on the front end I'm afraid. 

When we'll have the API in the future, you'll be able to extend Brizy and create your own elements. 

We have a lot of custom shortcodes in our theme and we started recently to put all the pages on Brizy and to be honest we've made little to no compromise in order to make the pages fit Brizy's actual feature set. 

There are some small things that are missing, but we'll add those in the following weeks.

Can you please let me know some things that you want to do with Brizy and can't ? 
I bet you can do over 90+ % with Brizy. 

Some screens can help as well, no need to study the ins and outs of Brizy, just send 3-4 screens of sections or pages and I can take a look and tell you instantly if they can or can't do with Brizy. 

Cheers.

**Comment by danyj** [comment]
@alexluncashu , thnx for the demo but dont you think that that makes no sense. 

think of a simple text shortcode, if you add it in it wont show the text and you cant change it either, 
now think of something more complex like table, how would you set the rows? 

I understand that you guys have a new product and have to market it but as it looks now it will not help any current builder shortcodes since each of them has to be set and adjusted for look and feel ( style & layout ) in order to be displayed properly.

**Comment by danyj** [comment]
suggestion in this direction that I think could work is 
list the Unyson builder templates in that shortcode 

![screenshot_10](https://user-images.githubusercontent.com/2340172/40365478-ed3daaea-5dd4-11e8-9b5e-f32b7b266193.jpg)

**Comment by danyj** [comment]
I am getting ready to release the theme soon, once done I planed to start on Unyson frontend builder  with my team. We will certainly look at Brizy than and see if we can come up with something but by the looks of it now it is not possible.

**Comment by DimiBaitanciuc** [comment]
@danyj interesting idea, I'll discuss it with the guys.

**Comment by danyj** [comment]
that is just a patch suggestion , the user must still prep the shortcode and style it with page builder so is kinda double work

**Comment by DimiBaitanciuc** [comment]
@danyj of course, but still a step to make Brizy and the visual builder from Unyson to somehow communicate with each other. Not sure if it makes too much sense since you'll still need to style the shortcodes in the back end and it might be confusing and counter-productive. 

Maybe it would be better to use one or the other.

I'm still struggling to understand what options or features you have there that Brizy can't handle. Can you give me an example? We have over 200 pages in our themes that e recreate and we've encountered only a few things that you can't do right now (but you will in a couple of months.)

I understand that you've worked 3 years, I'm sure you've built something very solid, I'm just really curious for myself to understand if we've missed something. Thanks.

**Comment by danyj** [comment]
@DimiBaitanciuc  wait few more days , Il give you the theme , everything that you guys have been working on and see from the Brizy issue still working on( shadows,padding,imports/exports,templates, generators etc )  I have,  but to bad is made for builder.

**Comment by DimiBaitanciuc** [comment]
@danyj can't wait to see it, I know you've worked your ass off in the past years for this. Let us know when you launch. We'll be your first clients :) :P

**Comment by danyj** [comment]
> We'll be your first clients 
Thank you! :)

what you guys should have done is told us ( devs ) about Brizy the second you started on it, many of us could have pitched in and we all could change the course together. Now we must try to patch it. But i'm sure we will manage it , just to get this thing out than we will see.

**Comment by DimiBaitanciuc** [comment]
@danyj once we'll have an API for Brizy I think things will change since anyone will be able to extend it the way they want.

**Comment by marsi52** [comment]
Have you people lost your mind? You have updated the builder (even if the new one is better) without any notification or the option not to use brizy, just because you tested it on 200 of your pages and thought that everything will work for the rest of the websites? 
I can't edit my site's content at all unless I rebuild the pages (and there are 50 of them)!!! Am I supposed to recreate the pages in order to make it work? What makes you think that we have 2 or even 1 day to spend on something that used to work as it should be since we have already spent so much time when we were actually building the website at the very beginning? 
I need to edit my content NOW and I want to do it with the old unyson builder, I don't have time to rebuild the site!!!

**Comment by DimiBaitanciuc** [comment]
@marsi52 I'd take a deep breath :), the Unyson builder was not replaced with Brizy. 
You and your users can still use the Unyson page builder the same way you did until now.

**Comment by DimiBaitanciuc** [comment]
@marsi52 I'd love to help man, but it's beyond me. @ViorelEremia or @alexluncashu must take a look. I'd say you connect in private and let them help you. Cheers.

**Comment by ViorelEremia** [comment]
@marsi52 Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by marsi52** [comment]
@DimiBaitanciuc @ViorelEremia Just did, thank you both, I appreciate it :)

**Comment by ViorelEremia** [comment]
@marsi52 that is not a Brizy issue it is because you don't update your wordpress core to 4.9.6 and you don't have the latest unyson extensions. Please before posting an issue here check if you have everything up to date: https://wordpress.org/support/topic/important-support-is-on-github-not-here-2/
You can check your site now seems to be all right.

**Comment by DimiBaitanciuc** [comment]
@marsi52 @ViorelEremia ah I could have helped with that ... damn : )  : P

**Comment by marsi52** [comment]
@ViorelEremia @DimiBaitanciuc  I'm afraid it's not ok. I did have tried the updates, that's a backuped version you saw. The result was the same and it still is. Do you see the editor working properly?

**Comment by ViorelEremia** [comment]
@marsi52 what page? what browser do you use?
![edit page wordpress](https://user-images.githubusercontent.com/28967378/40917626-95490c5c-680c-11e8-9005-c7c5050b9624.png)

**Comment by marsi52** [comment]
Could you please remove tehe screenshot from the thread? It provides
personal info.

2018-06-04 15:33 GMT+03:00 ViorelEremia <notifications@github.com>:

**Comment by marsi52** [comment]
@DimiBaitanciuc @ViorelEremia Thanks for your time and help guys. It looks ok I can work with the previous editor now.

**Comment by Nepsha1986** [comment]
I wanted to say thanks to all developer team of Unyson Framework! You've created a really cool tool for developers to create custom themes. I'm working with Unyson about a year and I think it is one of the most powerful tools to create high-quality websites. I didn't work with Brizy yet, and I hope it is as powerful as the back-end page-builder. 
P.S. A lot of developers do not use frontent builder to create pages, because of some reasons, that is why please keep supporting back-end page builder, cause it is really handy and cool. Thanks

**Comment by jonmlas** [comment]
Great work on the Brizy Visual Page Builder guys! It looks cool.
Though I still wished you could have made the default Unyson page builder be able to edit on the frontend.
I still also would like to have Unyson a repository for extensions where we can download and for devs to share.
Unyson rocks!

**Comment by Critick-rbs** [comment]
Hello.
I've created a web-site with Brizy, it looks great at my local server, but after importing my website to the Internet all work was lost! The page made with Brizy is empty in its editor and looking only like simple text and 'broken' images in WP-editor.

Please, help me solve this problem.
![screenshot_2018-07-09](https://user-images.githubusercontent.com/24782391/42428038-527d2432-833a-11e8-82a5-b54a931d6650.png)

**Comment by ViorelEremia** [comment]
@Critick-rbs here is support only for unyson for brizy please open an issue here: https://github.com/ThemeFuse/Brizy/issues/new

**Comment by Critick-rbs** [comment]
Thank you.

**Comment by micski** [comment]
Hello all, hello @ViorelEremia or @alexluncashu. I have same issue as [marsi52 above](https://github.com/ThemeFuse/Unyson/issues/3387#issuecomment-394307209) in this thread.

> @DimiBaitanciuc I will and you are more than welcome to help me resolve this :) (maybe I'm missing something over here).
> 
> * The thing is that if I deactivate brizy I can't use the Unyson page builder. On the default option, text area is completely blank and on the Visual Page builder, I get no fields to edit.
> * If brizy is activated, and I try to edit the content using brizy, the game is lost and the content is gone. I have to rebuild the page. If I try to edit with the default editor (and haven't chosen brizy at all), ok content is there, and that's good. But I can't build the pages anymore because all I get is the shortcodes' code. For now, it's ok because I don't need to make any huge redesign on the pages, but it will be an issue in the future.
> 
> Also my menu, on the homepage alone, is gone when Brizy is active.
> 
> That's the way it should work?
> Thanks for your prompt reply.

In reply you suggested updating everything. In 1st reply he says it didnt work. Just below he thanks for solving problem. No other solution than updates mentioned there. In my case all is up to date already, still encounter issue. Please help.

**Comment by Dionnie123** [comment]
I just really hate Unyson page builder for many different reasons...and I know that you know that these are also the reasons why you switch on a page builder....
         - You're working  on the backend so you can't see the actually see the design -realtime
         - We always need to refresh the frontend to see the changes, always requesting heavy data on server
                              - switch tab - edit -refresh, switch tab - edit -refresh, switch tab - edit -refresh,.....
         - The odd column grid Problem,
         - The section top & bottom shape thing, NOT RESPONSIVE
         - The Richtext Editor Bug!!!!!

2020, any updates???
