### ISSUE TITLE
Speed issues / lack of cachability 

### ISSUE THREAD

**Issue by anasilvaoreilly** [ThemeFuse/Unyson#3388]
Having an issue with a site and theme developer directed us here 

Speed issues / lack of cachability 

Developer's apparently claim that the cache issue caused by the php cookie is not their fault, but here's the relevant code: wp-content/plugins/unyson/framework/helpers/class-fw-session.php: * Advantages: Do not session_start() on every refresh, but only when it is accessed wp-content/plugins/unyson/framework/helpers/class-fw-session.php: session_start(); wp-content/plugins/unyson/framework/includes/hooks.php: session_start(); wp-content/plugins/unyson/framework/includes/hooks.php: session_start(); Cookies set by session_start are very bad for performance and break all caching - page and database. 

We have a band-aid over the problem right now, but it does need addressing. Can someone help us?

**Comment by danyj** [comment]
test without the theme , if everything works , go back to developer and advise to fix the bug

**Comment by anasilvaoreilly** [comment]
Developer says it is not them... has been a constant pass the blame weekend..

**Comment by danyj** [comment]
I am trying to help and only way to do that is if you confirm that the bug is there when you turn off/switch  the theme. This way Unyson devs can check the issue on their end.

**Comment by anasilvaoreilly** [comment]
Absolutely and thank you Dan. I have asked the team to do so and see if we have any luck

**Comment by ViorelEremia** [comment]
Yes, I know about this issue with php sessions that were a bad idea to use php sessions in unyson. I plan to remove sessions next week but it is not easy because many unyson features are based on sessions.

**Comment by anasilvaoreilly** [comment]
Thank you for trying - we really appreciate it :)


Ana Silva O'Reilly
Luxury Travel Blogger, Marketer and Social Media Specialist

ana@mrsoaroundtheworld.com | +44 75 40567408 | https://mrsoaroundtheworld.com

**Comment by anasilvaoreilly** [comment]
Hi! Is there an update on this? My apologies, I do not mean to chase - I was just wondering!


Ana Silva O'Reilly
Luxury Travel Blogger, Marketer and Social Media Specialist

ana@mrsoaroundtheworld.com | +44 75 40567408 | https://mrsoaroundtheworld.com

**Comment by ViorelEremia** [comment]
@anasilvaoreilly can I have some details about your site? ```viorel@themefuse.com```
Unfortunately I do not have much time to solve this issue. Sso I can check your site and maybe do something temporary if it is possible

**Comment by anasilvaoreilly** [comment]
Editor
Florida22%&

https://luxurytravelmom.com/wp-admin <https://luxurytravelmom.com/wp-admin>

Try this :) and thank uou!


Ana Silva O'Reilly
Luxury Travel Blogger, Marketer and Social Media Specialist

ana@mrsoaroundtheworld.com | +44 75 40567408 | https://mrsoaroundtheworld.com

**Comment by anasilvaoreilly** [comment]
Did it work ok?


Ana Silva O'Reilly
https://mrsoaroundtheworld.com

Sent from my iPhone

On 7 Jun 2018, at 08:57, ViorelEremia <notifications@github.com> wrote:

I checked your website and I think I can disable the sessions on your site.
Send me some temporary admin credentials: viorel@themefuse.com

**Comment by ViorelEremia** [comment]
I removed sessions from your site but now you can't use the shortcode forms from unyson builder you will not see error or success messages on submitting the form. I see you use another plugin for contact form so it will not affect you.

**Comment by anasilvaoreilly** [comment]
Hi! I do use another one - so maybe this will then solve the issue! 
I will speak to the host and see what he says this week when I’m back in the U.K.

Thank you for your help! 


Ana Silva O'Reilly
https://mrsoaroundtheworld.com

Sent from my iPhone

On 11 Jun 2018, at 08:28, ViorelEremia <notifications@github.com> wrote:

I removed sessions from your site but now you can't use the shortcode forms from unyson builder you will not see error or success messages on submitting the form. I see you use another plugin for contact form so it will not affect you.

**Comment by abuzer-firdousi-confiz** [comment]
Hi,
We are running in similar issue, can you please share your experience, were you able to optimize the load time?

Thanks

**Comment by anasilvaoreilly** [comment]
The developers made a change to the code and all is working well. 


Ana Silva O'Reilly
https://mrsoaroundtheworld.com

Sent from my iPhone

On 14 Sep 2018, at 14:41, abuzer-firdousi-confiz <notifications@github.com> wrote:

Hi,
We are running in similar issue, can you please share your experience, were you able to optimize the load time?

Thanks

**Comment by BlackTurtle123** [comment]
@ViorelEremia How did you solve this? How did you remove it?
