### ISSUE TITLE
Border width, type and color not applied when set in table characteristics

### ISSUE THREAD

**Issue by EdwardCaulfield** [ThemeFuse/Unyson#3389]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.

Using 2.7.13 I created a Table. I am attempting to make the borders on the table vanish. If I change the border size to 0, the border type to none or the border color to white, the border remains black.

Only be editing the cells, one at a time, am I able to get the borders to change to the desired characteristic.

I tested this in both Visual Page Builder and the default editor. Both had the same result.

Best Regards,

Edward

**Comment by ViorelEremia** [comment]
By default, unyson doesn't have options like to change border color. I think it is a theme issue please contact your theme author.
