### ISSUE TITLE
Post Meta with Wordpress Importer Tool

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#339]
When using Wordpress Importer Tool to import pages or portfolios, I see that some of pages can not be imported with Post Meta "fw-options" so the Page Builder just show that content like text block. Anyone know about this issue ? Please help me to solve it

**Comment by thednp** [comment]
You need the Unyson plugin with Page Builder extension installed in order to see the content right. The Page Builder is basically a shortcodes editor.

**Comment by maiakhoa** [comment]
I already turned on Page Builder for Pages. But some of them work normally, and some of them with large Page Builder contents or large "fw-options" occurred the problem that I reported.

**Comment by maiakhoa** [comment]
I send you an example that occur that error.

https://drive.google.com/file/d/0B3UpdmJDvRHpVWUyNkw4UHd5U2s/view?usp=sharing

**Comment by sergiubagrin** [comment]
Thanks i will investigate this problem

**Comment by maiakhoa** [comment]
Thanks

**Comment by NazarkinRoman** [comment]
+1. same bug. If post meta `fw_options` is big - it does not imports with wp importer(at the end we get a blank meta with this name).

**Comment by moldcraft** [comment]
We don't support wp importer, use [Demo Install](http://manual.unyson.io/en/latest/extension/backups/index.html) to migrate content.

**Comment by NazarkinRoman** [comment]
@moldcraft when I was(is about 6 months ago) trying to use demo installer extension every time I got broken website as a result of some sql conflicts during import process. This is why we have moved to wp importer. 

Is that extension's work established for now?

**Comment by moldcraft** [comment]
We support it actively. Try it (read the docs)
