### ISSUE TITLE
Extension updates not installing

### ISSUE THREAD

**Issue by Lomic2** [ThemeFuse/Unyson#3390]
Hi,

I have an issue with the visual editor not showing in back office.

I was on version 2.7.12 so I updated to 2.7.13 but I was unable to update extensions.

If I try to update extensions I get this kind of message for each one :

> Dowloading xxx extension...
> You can't download zip : xxx extension.

I've tried to set wp_debug to see errors, I get this message : 

> Notice: class-wp-upgrader-skins.php is obsolete since version 4.7.0 ! Use class-wp-upgrader.php instead. in /home/escaledefy/www/wp-includes/functions.php on line 3968

But I am at the last WordPress version i.e. 4.9.6. (and maybe this notice is not the origin of the issue).

Thanks for your help.

**Comment by ViorelEremia** [comment]
I simulated right now update of some extensions and is ok. I checked if this skin is used and no result. Did you try to contact the authors of the theme?

**Comment by Lomic2** [comment]
Hi and thanks for the answer.

Since my question an update of the theme I am using has been issued, but it doesn't change the issue.

Theme : https://themefuse.com/wp-themes-shop/journal/

I updated every plugin, theme, wordpress, except Unyson extensions.

When I load a page to edit it, it is almost empty . Inside the source I see a div named "fw-backend-option-descriptor" with an input named "fw_options[page-builder]" that contains all the elements which should be visible in the visual editor (I see my texts, images, settings...)

Seems that something hides the visual editor.

Below I see the visual editor elements ready to be added (content elements, layout elements...).

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by Lomic2** [comment]
Hi Viorel,

Marcellina from ThemeFuse got in touch with me and fixed the issue by
uploading the extensions folder directly.

I forgot to close the GitHub ticket, I do it now !

Thanks !

2018-06-06 10:03 GMT+02:00 ViorelEremia <notifications@github.com>:

**Comment by Lomic2** [comment]
Issue solved by Marcelina from ThemeFuse by manually uploading the extensions update to my server.

Thanks/
