### ISSUE TITLE
Unyson options not working after update to 4.9.6

### ISSUE THREAD

**Issue by etwordpress02** [ThemeFuse/Unyson#3393]
I recently updated my WordPress to latest version which is 4.9.6 at the time of this question and my theme settings are gone. Unable to load my theme settings and its always loading while console shows some error which is shown below in screenshot url:
[http://prntscr.com/jl4gcg](http://prntscr.com/jl4gcg)
Can you help my out what's the issue and how to get out of this ?

Thanks

**Comment by yura-x** [comment]
Can you please clarify are you using 'wp-editor' option type in your theme settings?
[Another Issue](https://github.com/ThemeFuse/Unyson/issues/3382)

**Comment by etwordpress02** [comment]
Yes we use. But the issue only arises once I update WordPress to 4.9.6 and even if I revert back to 4.9.5 it works totally fine. The only issue is in WordPress 4.9.6 update. We usually use wp-editor in our theme settings and never got in to such issue, its a bit of weird actually :(
