### ISSUE TITLE
Theme Options not working correctly

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#3394]
Some of my theme options are behaving strange. And some panels are blank. Can someone help out?

The console gives back this error:

--

TypeError: tinymce.ui.FloatPanel is undefined

Stack trace: init@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/includes/option-types/wp-editor/static/scripts.js?ver=2.7.12:148:3 each@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2:2879 each@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2:844 @http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/includes/option-types/wp-editor/static/scripts.js?ver=2.7.12:152:3 dispatchSingleEvent@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:169:6 fwEvents</this.trigger/<@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:147:7 objectMap@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:250:18 fwEvents</this.trigger@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:131:3 initTab@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/backend-options.js?ver=2.7.12:69:6 create@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/backend-options.js?ver=2.7.12:121:7 _trigger@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:6175 _createWidget@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:3103 a.widget/a[j][b]@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:588 a.widget.bridge/a.fn[b]/<@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:2365 each@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2:2879 each@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2:844 a.widget.bridge/a.fn[b]@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:2270 @http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/backend-options.js?ver=2.7.12:119:5 dispatchSingleEvent@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:169:6 fwEvents</this.trigger/<@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:147:7 objectMap@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:250:18 fwEvents</this.trigger@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:131:3 @http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/option-types.js?ver=2.7.12:3:3

--

columnNumber: 3
​
fileName: "http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/includes/option-types/wp-editor/static/scripts.js?ver=2.7.12"
​
lineNumber: 148
​
message: "tinymce.ui.FloatPanel is undefined"
​
stack: "init@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/includes/option-types/wp-editor/static/scripts.js?ver=2.7.12:148:3\neach@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2:2879\neach@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2:844\n@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/includes/option-types/wp-editor/static/scripts.js?ver=2.7.12:152:3\ndispatchSingleEvent@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:169:6\nfwEvents</this.trigger/<@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:147:7\nobjectMap@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:250:18\nfwEvents</this.trigger@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:131:3\ninitTab@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/backend-options.js?ver=2.7.12:69:6\ncreate@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/backend-options.js?ver=2.7.12:121:7\n_trigger@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:6175\n_createWidget@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:3103\na.widget/a[j][b]@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:588\na.widget.bridge/a.fn[b]/<@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:2365\neach@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2:2879\neach@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2:844\na.widget.bridge/a.fn[b]@http://beta.agro-chemie.nl/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,&load%5B%5D=wp-color-picker,admin-bar,jquery-effects-core,svg-painter,heartbeat,wp-auth-check,thickbox,shortcode,wp-util,wp-backbone,media-m&load%5B%5D=odels,wp-plupload,jquery-ui-sortable,wp-mediaelement,wp-api-request,media-views,media-editor,media-audiovideo,mce-view,imgarease&load%5B%5D=lect,image-edit,postbox,jquery-ui-tabs,jquery-ui-position,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,editor,quicktags,wplink,&load%5B%5D=media-upload,wp-embed&ver=4.9.6:24:2270\n@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/backend-options.js?ver=2.7.12:119:5\ndispatchSingleEvent@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:169:6\nfwEvents</this.trigger/<@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:147:7\nobjectMap@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:250:18\nfwEvents</this.trigger@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/fw-events.js?ver=2.7.12:131:3\n@http://beta.agro-chemie.nl/wp-content/plugins/unyson/framework/static/js/option-types.js?ver=2.7.12:3:3\n"

**Comment by yura-x** [comment]
This happens after update WordPress to  #4.9.6
[Another Issue](https://github.com/ThemeFuse/Unyson/issues/3382)

**Comment by ViorelEremia** [comment]
Update unyson.

**Comment by rahul7yadav** [comment]
I updated unyson but still got same error TypeError: "tinymce.ui.FloatPanel is undefined"
