### ISSUE TITLE
[Events] Exception raised. Please contact support in https://github.com/ThemeFuse/Unyson/issues/new. Don't forget to attach this stack trace to the issue

### ISSUE THREAD

**Issue by smohdsalimansari** [ThemeFuse/Unyson#3398]
Exception raised. Please contact support in https://github.com/ThemeFuse/Unyson/issues/new. Don't forget to attach this stack trace to the issue

TypeError: "tinymce.ui.FloatPanel is undefined"

**Comment by yura-x** [comment]
Same [issue](https://github.com/ThemeFuse/Unyson/issues/3396)
It was fixed [here](https://github.com/ThemeFuse/Unyson/commit/8af18b9907e58fdc28bcee88bbcc10fb64e4e91f)
We are waiting for update release.

**Comment by ViorelEremia** [comment]
Update unyson.
