### ISSUE TITLE
jquery.js?ver=1.12.4:3 Mixed Content: This content should also be served over HTTPS.

### ISSUE THREAD

**Issue by obertscloud** [ThemeFuse/Unyson#3399]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.
hello, so because of GDPR we had to install SSL, however now the images are not being served over https even though in the search and replace we changed all to https, and force to https, but in your fw:opt:ext:pb:page-builder:json custom field, you don't determine an http ...  so the jquery is the culprit but how do we fix it?

**Comment by ViorelEremia** [comment]
if the images are saved without protocol(```//```) then there should be no problems. Or you mean jquery is loading without protocol or images are loaded with lazy load. Can you give us more details? the site url for example.

**Comment by obertscloud** [comment]
jquery.js?ver=1.12.4:3 Mixed Content: The page at 'https://paradiseeventproductions.com/' was loaded over HTTPS, but requested an insecure image 'http://paradiseeventproductions.com/wp-content/uploads/2016/11/gallery-day-5-800x800.jpg'. This content should also be served over HTTPS.
Sa @ jquery.js?ver=1.12.4:3

so I don't know in the page default editor there is no http://  it is all https://
in your custom field fw:opt:ext:pb:page-builder:json also  all is https

I checked with a wordpress plugin developer he said 


I notice that there’s some JavaScript-based responsive image handing happening on the page. This plugin cleans up regular image links and HTML5 responsive images, but your site's JavaScript-based responsive images are slipping through.

I recommend that you run Better Search and Replace to clean things up permanently, as described below. Remember to take a backup first!
 from  this plugin i use to fix insecure content https://wordpress.org/support/plugin/ssl-insecure-content-fixer/

I am stuck because on sites without unyson, this plugin, and setting wordpress options to https  
then there are no issues

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by obertscloud** [comment]
Hello, I sent you credentials,  I am not sure the theme developer uses your unyson builder to create
the page.  I am using cloudflare and a plugin for insecure content, I do not know if it is changing things, the only page with insecure content is the homepage.  Can you log in ?  Thank you

**Comment by obertscloud** [comment]
Hello ?  how can you close this, should I reopen it..

**Comment by ViorelEremia** [comment]
Your issue is solved. Today will be an update with your issue so there is no sense to open it.
