### ISSUE TITLE
Please explain the reset options process

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#340]
I am having bit of trouble with jquery events after the reset button has been clicked. 
All on/click/change events do not fire anymore and is bit tedious to do this 

		$(document.body).on('change','.element',function (){

			// do something

		});

instead of this 

	$('.element').on('change',function (){

		// do something
	});

and certain triggers do work properly like 

		$(document.body).on('change','.element',function (){

			// do something

		}).trigger('change');

where this works just fine 

	$('.element').on('change',function (){

		// do something
	}).trigger('change');

so the complete code base must be rewritten. 

I can only assume that your are removing the form from dom and load default one via ajax. 
Is there any way you can "give" us back the events after this?

**Comment by moldcraft** [comment]
Try

```javascript
fwEvents.on('fw:options:init', function(data){
    data.$elements.find('.element:not(.initialized)')
        .on('change', function(){ ... })
        .addClass('.initialized');
});
```

**Comment by danyj** [comment]
That one ends up being bit more complicated than 

    $(document.body)....

but thnx, looks like I have to stick with document.body
