### ISSUE TITLE
Issues with editing page in unyson

### ISSUE THREAD

**Issue by krcreations** [ThemeFuse/Unyson#3402]
We have found that in our site, http://thenurseempowerment.com,  wp_postmeta table in the database the1631201423509 is filled with fw_options and fw:opt:ext:pb:page-builder:json rows. 
There are over 4000 rows in that table. These rows are related to the plugin Unyson Version 2.7.13 which is used to create content on your site.

We optimized the database and now the database is 221Mb in size before optimization was 241Mb, but this didn't speed up page edit process. We also created .user.ini file and set up memory limit to 512Mb, but this also didn't speed up page edit process. https://www.screencast.com/t/x1y5Xvok

We can't be sure how Unyson plugin uses this database rows and we cant delete this rows manually because that may affect current site content. 
Please help us asap!! Thank you!

**Comment by ViorelEremia** [comment]
You mean when you want to edit a page with the builder? or in frontend? Multiple rows with the same content in the db are the revisions.To clear revisions you can use some free plugins from wordpress.org.
I think the optimization you have made will not significantly increase the page speed.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
