### ISSUE TITLE
Brizy fatal error  failed to open stream

### ISSUE THREAD

**Issue by Ric-01** [ThemeFuse/Unyson#3403]
Hi all,

I did an update of Unyson today, because it was offered in my Wordpress admin.

After that the WP admin shows a white page. 

This is the error:

Notice: Use of undefined constant __DIR__ - assumed '__DIR__' in /var/www/web1035/html/wordpress/wp-content/plugins/brizy/vendor/autoload.php on line 5

Warning: require_once(__DIR__/composer/autoload_real.php) [function.require-once]: failed to open stream: No such file or directory in /var/www/web1035/html/wordpress/wp-content/plugins/brizy/vendor/autoload.php on line 5

Fatal error: require_once() [function.require]: Failed opening required '__DIR__/composer/autoload_real.php' (include_path='.:/opt/php/5.2.17/share/pear:/usr/share/php/pear') in /var/www/web1035/html/wordpress/wp-content/plugins/brizy/vendor/autoload.php on line 5

I need help, what to do now?

Thanks and greetings, Erich

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by Ric-01** [comment]
Hi all, 
it was so simple and I feel blamed: the htaccess overrided the PHP version 7.2 with th 5.2. 
Sorry and best regards
Ric
