### ISSUE TITLE
Edit with Brizy ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3404]
Please do not push unasked adverts. This was one thing I always liked abut you and now you 
are pushing Brizy on themes that you dont even know that want it or are compatible with it. 

http://prntscr.com/jlthyb

Please make Brizy extension uninstalled by default, do not install unless asked for, like SEO and all others

**Comment by notrealdev** [comment]
Same issue here, please remove it by default!

**Comment by danyj** [comment]
Hm , this is not even an extension it is a plugin that is installed without us knowing. 
This is not and should not be allowed by default.  I do not want to take a risk of braking someones site for the code that I did not develop , tested and know how it works.  

**A minor Unyson bug update should have never done this.**

If we disable this within code and try to disable the plugin the theme will not be allowed on TF.  
Please provide immediate way to disable auto Brizy installation.

**Comment by danyj** [comment]
Anyone who does not want it now you can use this function , 
not that it **will NOT pass Theme requirements check**. 

We are waiting for team response

add in theme/hooks.php  or functions.php
```

/**
 * Disable plugins
 */
if (!function_exists('_thz_deactivate_plugins')){
	function _thz_deactivate_plugins() {
		
		deactivate_plugins(array(
			'brizy/brizy.php'
		));    
		
	}
}
add_action( 'admin_init', '_thz_deactivate_plugins' );
```

**Comment by Ataurr** [comment]
This is the completely terrible idea by Unyson team.. Our theme built with unyson backend builder and now they forced to install brizy with unyson. 

And already buyers asking how they edit with brizy by frontend same design :/  

Please give us hooks to disable Brizy to install with unyson.  Until we moved our design into brizy.  This is not easy to move  10+ theme within short time.

**Comment by NiloySarker** [comment]
_**Seriously!**_
I'm stocked when I see an unknown plugin into my plugin List. http://prntscr.com/jn6hvy
i thought my site is hacked by somehow but when I try to figure out that I found this on google https://github.com/ThemeFuse/Unyson/issues/3387
**_but without user permission, it does not right to add any plugin in Dashboard_** :(

**Comment by danyj** [comment]
@everyone  the team took a notice  and will rectify. it was a blink decision that came with forced bug fix and release of brizy extension at the same time. Lets give them time to fix it which they will as advised.

**Comment by soulard** [comment]
What the hell is that ???
A stupid guy click to install and enable it. We loose all website content and we need to restore old backup... Thanks ! 
Are you crazy ? Our dashboard are not ad zone for your stuff, even it's a good stuff...

**Comment by AlexandruDoda** [comment]
Tried that filter and the alert still shows up.

![image](https://user-images.githubusercontent.com/8274669/42181521-fd2bb632-7def-11e8-9b63-891144b815d9.png)

**Comment by nickihastings** [comment]
The alert STILL shows up and when I click the 'x' to get rid of it, it pops up again and again and again. Geez. And the one that says "New extensions updates available. Go to Updates page". No there aren't, there are only extensions that I don't need. Why aren't these alerts dismissible? Like forever dismissible. Very bad design here, come on guys.

**Comment by maxjutras** [comment]
Did anyone found out the proper way to remove the alert suggesting to activate Brizy? This is so annoying: 
@altechzilla 
Screenshot: https://d.pr/i/TFPFVu+

**Comment by altechzilla** [comment]
@maxjutras - you could setup a hook via your plugin or theme that removes the admin notice (how @notrealdev suggested), or via some admin CSS plugin.
