### ISSUE TITLE
Demo content install issue: The execution failed. Please check error.log 

### ISSUE THREAD

**Issue by jicouple** [ThemeFuse/Unyson#3406]
I have tried to install demo content one my server. but the problem is an error showing when tried to install demo content.
see it : http://prntscr.com/jm2pyt

**Comment by ViorelEremia** [comment]
Try to increase max input vars, max execution time, memory limit

**Comment by jicouple** [comment]
yes. but don't working 
see it : http://prntscr.com/jmh627

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by jicouple** [comment]
ok.pls check email
