### ISSUE TITLE
Visual page builder now broken.

### ISSUE THREAD

**Issue by philvant** [ThemeFuse/Unyson#3407]
The visual page builder option on my site is now broken (I'm using Child's Play theme).

Looks like it might have happened after I updated to the newest WordPress version? Not sure.

When I try to edit and re-save existing pages using the visual page builder, it completely destroys the content, mashes it all up into a mess in the default editor, and doesn't allow me to revert back to old versions.

My site will be okay as long as I don't update anything, I guess, but I'll have to go buy a new theme and completely re-design everything if I cant get this fixed.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
