### ISSUE TITLE
Mega Menu extension missing

### ISSUE THREAD

**Issue by normancates** [ThemeFuse/Unyson#3408]
I've just installed Unyson, and the Mega Menu extension is missing. It's not in the long lst of extensions available.

This is weird because previously when I've used Unyson, the Mega Menu option was there...

Thanks,
Norm

**Comment by ViorelEremia** [comment]
Is the same theme?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.

**Comment by Bibisfreak** [comment]
Hola... acabo de instalar la plantilla Hostinza que usa Unyson para varias extensiones en particular la de Mega Menú. Sin embargo, no me aparece esa extensión... quisiera saber que sucede, soy nueva en estos temas, Gracias.
![image](https://user-images.githubusercontent.com/48075730/53536181-54feb580-3ad3-11e9-8784-6d1636783f66.png)
