### ISSUE TITLE
Sliders not working properly

### ISSUE THREAD

**Issue by shaonsina** [ThemeFuse/Unyson#3410]
If I use **Type of Transition** vertical then it's not working.
If I use more than one slider on the same page then sliders design is broken

**Comment by ViorelEremia** [comment]
Can you try to add to end of the file ``unyson/framework/extensions/media/extensions/slider/extensions/bx-slider/static/js/bxslider.js``` code:
```
jQuery('document').ready(function () {
	jQuery('.bxslider').each(function(){
		jQuery(this).bxSlider();
	});
});
```
From the file ```unyson/framework/extensions/media/extensions/slider/extensions/bx-slider/views/bx-slider.php```
remove the script:
```
<script type="text/javascript">
		jQuery('document').ready(function () {
			jQuery('.bxslider').bxSlider();
		});
	</script>
```

**Comment by shaonsina** [comment]
issues solved!!!
