### ISSUE TITLE
Updating plugin error

### ISSUE THREAD

**Issue by paulthomson-me** [ThemeFuse/Unyson#3411]
after trying to update plugin from version 2.7.12 to 2.7.14, I get the following error:

`[Sun May 27 15:04:02.217958 2018] [proxy_fcgi:error] [pid 17703] [client 127.0.0.1:51902] AH01071: Got error 'PHP message: PHP Fatal error:  Cannot redeclare install_plugin_information() (previously declared in /home/***/public_html/wp-admin/includes/plugin-install.php:461) in /home/***/public_html/wp-admin/includes/plugin-install.php on line 461\n'`

PHP 7.2
MySQL 5.6

Thanks,

**Comment by ViorelEremia** [comment]
Update unyson
