### ISSUE TITLE
Brizy

### ISSUE THREAD

**Issue by jamestibbets** [ThemeFuse/Unyson#3413]
I really wish Brizy wasn't installed by default. I use a different page builder and uninstalling Brizy is just an extra step. Also, Brizy adds its own database table, which dirtys things up. Cut it out! If users want Brizy they can install Brizy; the rest of us want to use other parts of Unyson without getting our database messed with.

**Comment by danyj** [comment]
will get updated tomorow. 
https://github.com/ThemeFuse/Unyson/issues/3404

**Comment by jamestibbets** [comment]
Thanks
________________________________
