### ISSUE TITLE
Image widget link broken

### ISSUE THREAD

**Issue by danielvtan** [ThemeFuse/Unyson#3417]
Unyson version 2.7.16
Wordpress version 4.9.6

![unyson-screen](https://user-images.githubusercontent.com/2202701/40727153-dfddadf6-6459-11e8-86bd-bb5d401d6786.PNG)

Image widget not working after 2.7.16 update.
url src different from the image url uploaded.

**Comment by danielvtan** [comment]
We tried to install and reinstall the plugin and theme but its still not working.
we also tried to rollback the version of unyson to no avail.
we are using Social Activism theme

**Comment by ViorelEremia** [comment]
I don't understand; did you try to activate a default theme?

**Comment by danielvtan** [comment]
Yes we activated the default theme. we then changed it back but image problem still persist.

We previously used the image widget and it worked. now we dont know what happened.
We can't wait for the fix so we are using Text Block content element for the images.

Based on our test we probably did something that broke the image saving. So this might not be a unyson problem.

Thanks anyway!
