### ISSUE TITLE
How to Manually Upload Unyson Plugin in Wordpress?

### ISSUE THREAD

**Issue by sakshipruthi55** [ThemeFuse/Unyson#3418]
Hi,

I want to manually add unyson plugin in my wordpress admin. How can I do so??

Actually, I deleted unyson plugin by mistake from ftp and now I'm not able to upload it again and also old folder of unyson is also there and I'm not able to access it. Kindly help me through this.

Regards,
Sakshi

**Comment by ViorelEremia** [comment]
Remove the folder unyson from wp-content/plugins and install it again from the dashboard, or you don't have the direct method to install plugins from the dashboard.
