### ISSUE TITLE
Images aren't positioned right

### ISSUE THREAD

**Issue by kynoapea** [ThemeFuse/Unyson#3419]
On my homepage and blog posts, all the images now cover the text that was previously aligned below the image and when I created a table, the images are now hidden behind the table. I use Thrive Architect to build certain pages but this is happening on every page of my website. I got notified about this by comment yesterday, I'm not sure since when it started. 

I use the Core theme version 1.0.35
Unyson 2.7.16
Brizy 1.0.7
Wordpress 4.9.6

**Comment by ViorelEremia** [comment]
It's a theme issue, please contact the [theme author](https://support.themefuse.com/hc/en-us/requests/new).
Unyson is a plugin that allows theme authors to create fast and easy WordPress themes. Some of the issues come from themes.
