### ISSUE TITLE
Addable-box "image" in palce of box title

### ISSUE THREAD

**Issue by dameer** [ThemeFuse/Unyson#342]
If well understood addable-box title can be any option value, we just need to use:

`'template' => '{{- some_option_value }}'`

So let's say one of options of my addable-box is an image upload (single) and I want to put its thumbnail in place of the text so it'll be used as a visual representation of that very box when closed. 
What I can see there is 

`[object Object]`

...which means there's no handler for this type of data.

Is that normal or a bug? Is there a workaround for it?

**Comment by moldcraft** [comment]
[Upload option value](http://manual.unyson.io/en/latest/options/built-in-option-types.html#upload) is

```php
array(
        'attachment_id' => '9',
        'url' => '//site.com/wp-content/uploads/2014/02/whatever.jpg'
)
```

So try

```php
'template' => '{{- some_option_value.url }}'
```

**Comment by dameer** [comment]
That's awesome! Thanks a bunch, keep up the great work!

**Comment by dameer** [comment]
I closed it but found myself hitting the wall once again...

It's fine when I do

`'template' => '<img src="http:' . '{{- some_option_value.url }}' . '" alt="Preview" />'`

...however, one disadvantage of this method is the fact that full size image is loaded. I know, it can be scaled by CSS but still there's maybe a plenty of full size images to be loaded.

So another logical step would be to load just a thumbnail

`'template' => wp_get_attachment_image( '{{- some_option_value.attachment_id }}', 'thumbnail'  )`

...but nothing shows up.

Any ideas?

**Comment by moldcraft** [comment]
The `'template'` parameter is used only in js, `wp_get_attachment_image()` has no idea what `{{- some_option_value.attachment_id }}` is.

At the moment I don't know how to solve this.

**Comment by dameer** [comment]
No problem, thanks for the answer! It's too bad we can't use that attachment_id somehow...
