### ISSUE TITLE
Visual page builder mess up

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#3420]
Hi! Our client restored the revision of the page then the page builder is mess up into text-block, All is updated. 
I send you an email so hope you can help. 
Thanks!

**Comment by duongancol** [comment]
I found similar issue here https://github.com/ThemeFuse/Unyson/issues/3397
But it didn't resolve.

**Comment by NerinaMills** [comment]
I have a similar issue too - no idea what happened! Would like an answer too?
