### ISSUE TITLE
Unyson Content all Disappeared

### ISSUE THREAD

**Issue by NerinaMills** [ThemeFuse/Unyson#3421]
Hi there,

I made a small change to my home page content today via the Unyson page Builder, clicked update and all of a sudden ALL of my content from that page has disappeared. I tried to step but to a previous version of the page but none of my content is showing up.

Nothing on front-end or backend.

Yesterday I updated to your latest update - could this be the problem?

**Comment by ViorelEremia** [comment]
Have you the latest unyson extensions? https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
Remove any cache from server, browser, server.

**Comment by NerinaMills** [comment]
Hi there,

I am currently running the latest Unyson extensions - when I updated to the latest update, that is when the problem occurred.

I have got the latest version of wordpress, my themes and plugins running.

Once I cleared any cache from server and browser, I can see my content on the frontend and on the backend under the default text editor. However, when trying to use the Unyson Page Builder I just see a text block with this text in "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

I have also tried deactivating all of my other plugins to see if any of them are not compatible with Unyson page builder, however, this has not made any difference.

Could you please assist?
Thank you :)

**Comment by NerinaMills** [comment]
Is anyone able to help with this issue? I really need my page to be fixed.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by NerinaMills** [comment]
Thank you! I have sent you the credentials as well as a link to this thread.

**Comment by ViorelEremia** [comment]
Check your email. I wrote to you a day ago

**Comment by NerinaMills** [comment]
Apologies, your email was in my junk folder - I've sent you a response :) thank you!!

**Comment by ViorelEremia** [comment]
Solved: https://wpml.org/forums/topic/problem-in-media-translations-link-to-image/
Please update the wpml plugins.
