### ISSUE TITLE
Database corrupted after demo content install

### ISSUE THREAD

**Issue by goran468** [ThemeFuse/Unyson#3422]
Last two days we have many reports about database corruption after demo content installation. It's different hosting, servers and configurations. Demo content files haven't changed very long time. Several times it was MariaDB.

Is it only our problem? What information can help to debug this issue? Thanks

**Comment by andronic90** [comment]
What theme do you using? What plugins are active?

**Comment by yura-x** [comment]
Hello! Same issue.
During demo content installation progress appears blank popup with exclamation mark on red background. After page refresh appears WordPress message:
"One or more database tables are unavailable. The database may need to be repaired.":
[https://prnt.sc/jpftst](https://prnt.sc/jpftst)
It seems that the problem appears after WordPress update to 4.9.6

**Comment by yura-x** [comment]
UPDATE: have tested demo content install on WordPress versions 4.9.5 and 4.9.4 and got same issue

**Comment by andronic90** [comment]
Can you give more details? What theme do you use, what plugins?

**Comment by goran468** [comment]
I am theme developer, it doesn't depends on theme and plugins. About five our themes have same issue and themes and demo wasn't updated long time. No plugins installed except Unyson. MariaDB also doesn't causes this problem, seems to be. And this problem isn't always exists, we can't repeat it on our servers and some users have correct installations.

Demo Content installation breaks on database restore, after that some required tables still have _fwbk_ prefix, but some tables were renamed.

We continue to debug, will write later with more details, thanks.

**Comment by yura-x** [comment]
I'm using Greenscape theme.
It has WooCommerce tables, maybe problems with them.
Here is my tables after corrupted demo content installation

+-------------------------------------------------------+
| Tables_in_wp_greenscape                               |
+-------------------------------------------------------+
| _fwbk_wp_commentmeta                                  |
| _fwbk_wp_comments                                     |
| _fwbk_wp_fw_termmeta                                  |
| _fwbk_wp_links                                        |
| _fwbk_wp_options                                      |
| _fwbk_wp_postmeta                                     |
| _fwbk_wp_posts                                        |
| _fwbk_wp_term_relationships                           |
| _fwbk_wp_term_taxonomy                                |
| _fwbk_wp_termmeta                                     |
| _fwbk_wp_terms                                        |
| _fwbk_wp_woocommerce_api_keys                         |
| _fwbk_wp_woocommerce_attribute_taxonomies             |
| _fwbk_wp_woocommerce_downloadable_product_permissions |
| _fwbk_wp_woocommerce_log                              |
| _fwbk_wp_woocommerce_order_itemmeta                   |
| _fwbk_wp_woocommerce_order_items                      |
| _fwbk_wp_woocommerce_payment_tokenmeta                |
| _fwbk_wp_woocommerce_payment_tokens                   |
| _fwbk_wp_woocommerce_sessions                         |
| _fwbk_wp_woocommerce_shipping_zone_locations          |
| _fwbk_wp_woocommerce_shipping_zone_methods            |
| _fwbk_wp_woocommerce_shipping_zones                   |
| _fwbk_wp_woocommerce_tax_rate_locations               |
| _fwbk_wp_woocommerce_tax_rates                        |
| wp_usermeta                                           |
| wp_users                                              |
| wp_wc_download_log                                    |
| wp_wc_webhooks                                        |
| wp_woocommerce_downloadable_product_permissions       |
+-------------------------------------------------------+

**Comment by yura-x** [comment]
Yes, after deleting WooCommerce from required plugins demo content was successfully installed.
Got problems several days ago with WooCommerce. 
It was resolved by deleting this line of code from my database.json.txt file
`,"CONSTRAINT `wp_wc_download_log_ibfk_1` FOREIGN KEY (`permission_id`) REFERENCES `wp_woocommerce_downloadable_product_permissions` (`permission_id`) ON DELETE CASCADE"`

**Comment by goran468** [comment]
Confirming. Message before about WooCoomerce wasn't installed wrong. WooCommerce deactivation allows demo to be installed.

**Comment by yura-x** [comment]
Got this error while installing demo content that was created on last versions of WordPress, Unyson and WooCommerce :
**Failed to create tmp table _fwbk_mwt_wc_download_log. Cannot add foreign key constraint**
Had to delete following code from **database.json.txt** to install demo
`
,"CONSTRAINT \`wp_wc_download_log_ibfk_1\` FOREIGN KEY (\`permission_id\`) REFERENCES \`wp_woocommerce_downloadable_product_permissions\` (\`permission_id\`) ON DELETE CASCADE","CONSTRAINT \`wp_wc_download_log_ibfk_2\` FOREIGN KEY (\`permission_id\`) REFERENCES \`wp_woocommerce_downloadable_product_permissions\` (\`permission_id\`) ON DELETE CASCADE"
`

**Comment by skenzo34** [comment]
Hello!
We have the problem in the new Unyson version. After the demo content installation, the database is broken and needs to repair. 
If the demo content install without WooCommerce plugin - all is good. But if WooCommerce plugin is active - db go down and you can't access even to the admin panel. 
How to fix this problem? In the later versions there is no problem like this :(

**Comment by ViorelEremia** [comment]
Can someone test the commit: https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/129c6c0a7eb5058eba823dd06f627dc5d4db2b77

**Comment by yura-x** [comment]
@ViorelEremia Thank you! Your commit have fixed our problem - demo content that was created on old version of WooCommerce now was successfully installed on fresh WordPress installation with last version of WooCommerce (Version 3.4.2)
Do you planning to create an extension update with this commit?
Thank you once again!

**Comment by ViorelEremia** [comment]
I did

**Comment by ViorelEremia** [comment]
@yura-x can you test with the latest committees backup?

**Comment by yura-x** [comment]
I have tested on same theme with old demo content (using extension with your latest commits) and demo was installed successful.

**Comment by MaiHoThi** [comment]
> Hello! Same issue.
> During demo content installation progress appears blank popup with exclamation mark on red background.
> https://prnt.sc/jpg39a
> After page refresh appears WordPress message:
> "One or more database tables are unavailable. The database may need to be repaired.":
> https://prnt.sc/jpftst
> It seems that the problem appears after WordPress update to 4.9.6

Same problem! Who can't solve this problem
