### ISSUE TITLE
Disable auto fill color option

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#3423]
Hi! In color option, when user types the color code, it suggests the color code automatically. 
The way it generates the code is not good. How can I disable it? 
Thanks!

**Comment by ViorelEremia** [comment]
You can't disable it. I don't know how to fix it there are too many issues around it. In customizer and modal page builder, it was modified to work with them so on every change event is triggered an another evernt into iris and iris change again the input. So it is very ugly but i can't do it right. Better if you have clients that need to write directly in the input then create your own option type there are many scripts on the net.
