### ISSUE TITLE
Page builder broken after plugins update

### ISSUE THREAD

**Issue by tom762** [ThemeFuse/Unyson#3424]
Hi,
after looking for help on the web I see there are numerous similar problems like mine...

So, after the last (could've been the previous, when Brizy auto-installed) update of all plugins, including Unyson, page editor is broken, the content box and all text-edit buttons are gone, only white box remains. I can't even switch to text editor.
The content of the pages is still there, I just can't edit it.
I tried to disable all plugins and default WP editor works fine, but as soon as I enable Unyson, it all breaks again. It used to work fine before this update. Also, whole back-end works painfully slow now with Unyson enabled.
I tried to delete the cache plugin, browser cache, completely uninstalled and re-installed Unyson, still no change.
All plugins (including Unyson extensions), WP and themes (Core) are updated to the last version. Unyson 2.7.16, WP 4.9.6, Core theme 1.0.35.
I need to edit some pages quite urgently but I can't. If I don't solve this issue soon, I'll have to rebuild all pages from scratch on some other theme.

Could someone suggest any solution please?
Thanks.

![capture](https://user-images.githubusercontent.com/8026193/40879894-f8ea812a-66a7-11e8-906c-1312db2dc8f4.JPG)

**Comment by danyj** [comment]
dont rebuild anything , first check if you have any JS errors in admin edit page and if you do post them here so that we can take a look, next step is disabling any other plugins but Unyson and see if that fixes anything

**Comment by tom762** [comment]
Thanks, I tried to disable all plugins but Unyson any Brizy, no difference. As soon as Unyson is enabled, the editor doesn't work and whole back-end works very slow.
Unfortunately I don't know how to check for JS errors. If it matters, I use Firefox.

**Comment by tom762** [comment]
Hi, not sure if this is it, but here's what error console spits out:

``
Firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data.  rest-proxy:7:6925
Error: ID already exists: convert  ext-menus.js
Error: ID already exists: append  ext-menus.js
Error: ID already exists: convert  ext-menus.js
Error: ID already exists: append  ext-menus.js
Error: ID already exists: convert  ext-menus.js
Error: ID already exists: append  ext-menus.js
Error: ID already exists: convert  ext-menus.js
Error: ID already exists: append  ext-menus.js
Error: ID already exists: convert  ext-menus.js
Error: ID already exists: append  ext-menus.js
ReferenceError: jQuery is not defined  load-scripts.php:1:1
ReferenceError: jQuery is not defined  media.js:94:1
ReferenceError: jQuery is not defined  script.js:1:1
ReferenceError: fw is not defined  load-shortcodes-data.js:15:1
ReferenceError: jQuery is not defined  tracks-ajax.js:57:1
ReferenceError: jQuery is not defined  jetpack-jitm.min.js:2:1
ReferenceError: jQuery is not defined  backend-options.js:12:1
ReferenceError: jQuery is not defined  option-types.js:1:1
TypeError: Backbone is undefined  backbone-relational.js:65:3
Loading failed for the <script> with source “https://www.xyz.com/wp/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/static/js/builder.js?ver=1.2.10”.  post.php:3214
ReferenceError: jQuery is not defined  initialize-builder.js:577:1
ReferenceError: Backbone is not defined  helpers.js:42:1
ReferenceError: jQuery is not defined  fullscreen.js:130:1
ReferenceError: jQuery is not defined  history.js:121:1
ReferenceError: jQuery is not defined  scripts.js:8:1
ReferenceError: jQuery is not defined  scripts.js:4:1
ReferenceError: jQuery is not defined  scripts.js:9:1
ReferenceError: jQuery is not defined  scripts.js:9:1
ReferenceError: jQuery is not defined  scripts.js:10:1
ReferenceError: fwEvents is not defined  scripts.js:22:1
ReferenceError: jQuery is not defined  scripts.js:1:1
ReferenceError: jQuery is not defined  scripts.js:1:1
ReferenceError: jQuery is not defined  multi-picker.js:6:1
ReferenceError: jQuery is not defined  popup.js:2:1
ReferenceError: jQuery is not defined  scripts.js:271:1
ReferenceError: fw is not defined  aggressive-coder.js:4:1
ReferenceError: jQuery is not defined  scripts.js:175:1
ReferenceError: jQuery is not defined  jquery.adaptive-switch.js:38:2
ReferenceError: jQuery is not defined  scripts.js:1:1
ReferenceError: jQuery is not defined  images-only.js:252:1
ReferenceError: jQuery is not defined  any-files.js:169:1
ReferenceError: jQuery is not defined  image-picker.js:13:2
ReferenceError: fw is not defined  scripts.js:5:2
ReferenceError: jQuery is not defined  jquery.datetimepicker.js:1:6082
ReferenceError: jQuery is not defined  script.js:43:1
Loading failed for the <script> with source “https://www.xyz.com/wp/wp-content/plugins/unyson/framework/includes/option-types/map/static/js/scripts.js?ver=1.0”.  post.php:3242
ReferenceError: jQuery is not defined  images-only.js:8:1
ReferenceError: jQuery is not defined  any-files.js:5:1
ReferenceError: jQuery is not defined  scripts.js:468:1
ReferenceError: jQuery is not defined  scripts.js:29:1
Loading failed for the <script> with source “https://www.xyz.com/wp/wp-content/plugins/unyson/framework/includes/option-types/background-image/static/js/scripts.js?ver=2.7.16”.  post.php:3247
ReferenceError: jQuery is not defined  scripts.js:1:1
ReferenceError: fwEvents is not defined  scripts.js:258:1
ReferenceError: jQuery is not defined  scripts.js:469:1
ReferenceError: fwEvents is not defined  scripts.js:263:1
ReferenceError: fwEvents is not defined  scripts.js:228:1
unreachable code after return statement  editor_integration.js:215:3
ReferenceError: jQuery is not defined  editor_integration.js:320:1
ReferenceError: jQuery is not defined  visual-elements.js:135:1
ReferenceError: jQuery is not defined  modal-save-all.js:106:1
ReferenceError: fwEvents is not defined  scripts.js:1:1
ReferenceError: fwEvents is not defined  scripts.js:1:1
ReferenceError: fwEvents is not defined  scripts.js:1:1
ReferenceError: fwEvents is not defined  scripts.js:4:1
ReferenceError: jQuery is not defined  scripts.js:1:1
ReferenceError: fwEvents is not defined  scripts.js:1:1
ReferenceError: fwEvents is not defined  scripts.js:1:1
ReferenceError: fwEvents is not defined  scripts.js:1:1
ReferenceError: fwEvents is not defined  scripts.js:1:1
ReferenceError: fw is not defined  scripts.js:1:1
ReferenceError: fwEvents is not defined  scripts.js:1:1
ReferenceError: jQuery is not defined  scripts.js:79:1
ReferenceError: jQuery is not defined  theme-admin.js:1:1
ReferenceError: jQuery is not defined  notes-common-v2.js:158:1
ReferenceError: _ is not defined  admin-bar-v2.js:2:38
ReferenceError: jQuery is not defined  jquery.leanModal.min.js:7:1
ReferenceError: jQuery is not defined  leanmodal.init.js:2:1
ReferenceError: jQuery is not defined  admin.js:13:1
ReferenceError: jQuery is not defined  jquery.ck.js:18:1
ReferenceError: jQuery is not defined  post.php:3290:1
TypeError: QTags is not a constructor  load-scripts.php:11:30
Error: ID already exists: convert  ext-menus.js
Error: ID already exists: append  ext-menus.js
ReferenceError: jQuery is not defined  plugin.js:69:1
ReferenceError: jQuery is not defined  editor_plugin.js:1:1
Error: ID already exists: convert  ext-menus.js
Error: ID already exists: append  ext-menus.js
Loading failed for the <script> with source “https://www.xyz.com/wp/wp-includes/js/media-views.min.js?ver=4.9.6”.  post.php:1
TypeError: t.view.Settings is undefined  gallery-settings.min.js:5:29
Error: ID already exists: convert  ext-menus.js
Error: ID already exists: append  ext-menus.js
Error: ID already exists: convert  ext-menus.js
Error: ID already exists: append  ext-menus.js
Firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data.  rest-proxy:7:6925

``

I hope this is it, if you need anything else, please let me know. Thank you.

**Comment by danyj** [comment]
to me it looks like a script is trying to use jQuery  before it is actually loaded. Did you open a ticket at themefuse? This is The Core theme and they should help you with it. What was that page built with? Brizy or Unsyon page builder? If page builder , try temp unplublish Brizy.

**Comment by tom762** [comment]
I just opened the ticket at Themefuse now just in case. However I tried to switch theme Twenty Seventeen and the problem appears to remain the same.
My pages were all built with Unyson, none with Brizy. Now Brizy is disabled, but there's no difference. It seems that the issue starts only when Unyson is enabled.
If it helps, I can set up a temp access to the site/ftp?

**Comment by danyj** [comment]
Sorry I cant mess with others code , just trying to guide you until you get help from the devs. 

Did you update all extensions? 

Go to WP updates and make sure that everything is updated 
http://prntscr.com/jqai64

**Comment by tom762** [comment]
I did. They're obviously all updated. I guess it must be something else.

**Comment by ViorelEremia** [comment]
Disable the option "Rocket loader(beta)" in your account Cloudflare.

**Comment by tom762** [comment]
Excellent! It works! :+1: 
Thank you!

**Comment by mlt0882** [comment]
Hi, having this exact same issue [here](https://github.com/ThemeFuse/Unyson/issues/3721) except I don't have the Rocket Loader enabled so this solution is not relevant to my site. Actually followed each step of this process up until that point.

Is there anything else that could be causing this issue? I disabled Cloudflare temporarily just to see and that didn't work either.
