### ISSUE TITLE
Color scheme edit?

### ISSUE THREAD

**Issue by retlaw7** [ThemeFuse/Unyson#3427]
Hi, I want to edit the color schemes of the builder, but I can't find it anywhere, anybody knows where I can edit it?

**Comment by jonmlas** [comment]
You can just create a css for the editor and just override the colors.

**Comment by ViorelEremia** [comment]
What color scheme I don't understand. You mean the palettes, color of shortcodes, modals ?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
