### ISSUE TITLE
Compatibility issue with Give Donation Plugin

### ISSUE THREAD

**Issue by najeeb-finelayers** [ThemeFuse/Unyson#3428]
Hi, 

I am developing a theme using Unyson framework. I got an issue with this plugin. I am using give donation plugin for managing donations. Give updates it's database automatically using ajax technology whenever it is updated but when Unyson is installed it gives error. I have attached the screenshot of the error i got. If i disable the plugin Unyson then give updates it's database and the error is removed. 
![give_issue](https://user-images.githubusercontent.com/38913495/40955824-fcc79d1e-68a5-11e8-96ff-4771ed6085fa.png). 

Is this a bug ?? Any solution to this ?

**Comment by najeeb-finelayers** [comment]
Hi Unyson team. Is there anyone to reply me. I have posted a question 3 days ago but no answer yet. Please reply to my query. 

Thank you

**Comment by ViorelEremia** [comment]
I installed it, added a form, I don't see any errors into ajax. How can I get this notification?

**Comment by najeeb-finelayers** [comment]
Hi,

It will not show every time. It only shows whenever give updates it's database. I am using it from last 10 days. It appears almost ever day. Maybe Whenever i  do something with the give plugin.

**Comment by ViorelEremia** [comment]
Try to ask the author of plugin I have left it active until now and I don't see any updated db. Or if your site is not localhost:
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
