### ISSUE TITLE
Theme & Extension Updates from Custom Server

### ISSUE THREAD

**Issue by hlaporthein** [ThemeFuse/Unyson#3429]
I can't figure out how I should update **multi extensions & themes with different versions**.

Doc said to define like below. 
`$version = '1.0';`

Could anyone should me an example codes? I have spent some hours. Plugins & themes that I would like to updates

- menucard extension version 2.5
- construction extension version 1.8
- listing extension version 1.9
- rino theme version 1.3
- rino-child theme version 1.1 

How could I configure the codes in my server for those different versions. Below are my codes in server

```

<?php
$set = json_decode( file_get_contents( 'php://input' ), true );

$vars = array(
	'pull' => array( 'version', 'zip' ),
	'type' => array( 'theme', 'extension' )
);

foreach( $vars as $key => $values ) {
	if ( ! isset( $set[ $key ] ) || ! in_array( $set[ $key ], $values ) ) {
		die( json_encode( array( 'error' => 'Something went wrong. Please contact support team.' ) ) );
	}
}


$my_products = array(
	'extension' => array( 'menucard', 'construction', 'listing' ),
	'theme'     => array( 'rino', 'rino-child' ),
);

if ( ! isset( $set['item'] ) || ! in_array( $set['item'], $my_products[ $set['type'] ] ) ) {
	die( json_encode( array( 'error' => 'This item doesn\'t exists.'  ) ) );
}


$version = '1.0';


if ( $set['pull'] === 'version' ) {
	die( $version );
}


$path = dirname( __FILE__ ) . "/{$set['item']}.{$version}.zip";

if ( ! file_exists( $path ) ) {
	die( json_encode( array( 'error' => 'File zip doesn\'t exists.' ) ) );
}

header( 'Content-Type: application/zip' );
header( 'Content-Disposition: attachment; filename=' .  basename( $path ) );
header( 'Content-Length: ' . filesize( $path ) );
readfile( $path );

die();

```

**Comment by ViorelEremia** [comment]
Did you find a solution to your question?
Let say 'donor' is your server with the latest versions of extensions and the 'sucker' is the user server. 

> Doc said to define like below.
$version = '1.0';


The donor must have this version so you must create a function on your server something: 
```
// $set['item'] - is the name of extension or theme in your case extension.
getLatestVersionOfExtension( $set['item'] )
``` 
--- will return the latest version of extension.
Bellow you see: 
```
// Client's server asked for version just return it.
if ( $set['pull'] === 'version' ) {
    die( $version );
}
```
With your function it must look:
```
$version = getLatestVersionOfExtension( $set['item'] );

// Client's server asked for version just return it.
if ( $set['pull'] === 'version' ) {
    die( $version );
}

```
In short I do not know how to explain you better.

**Comment by hlaporthein** [comment]
I understand your explanation. I thought documentation guideline works perfectly for that. Maybe, one day, doc would update for that. I hope.

**Comment by Niloys7** [comment]
Hi @hlaporthein  & @ViorelEremia ,
what it is actually doing? (see screenshot: https://prnt.sc/t0sdnm )

- is it download and active theme from the server or something else. if yes, then how should it called in the manifest.php or somewhere else?
Thanks
