### ISSUE TITLE
Backend Character Limit

### ISSUE THREAD

**Issue by tharindu93** [ThemeFuse/Unyson#3430]
Is there any method for limit character of wp-editor from backend?

**Comment by rdanusha** [comment]
Waiting for a answer...

**Comment by ViorelEremia** [comment]
No, there is no such kind of method. But why do you need this?

**Comment by rdanusha** [comment]
I have developed some custom shortcodes. I need to limit characters of some input text fields. Is there any possibilities to do this?

**Comment by ViorelEremia** [comment]
Every input has an id you hanlde it example for length 5:
```
$( document ).on( 'change', '#your input id', function () {
	var val = $( this ).val();

	if ( val.length > 5 ) {
		$( this ).val( val.substr( 0, 5 ) );
	}
} );
```

**Comment by tharindu93** [comment]
Thank you. I will try this.
