### ISSUE TITLE
Shortcode Fields Validation

### ISSUE THREAD

**Issue by rdanusha** [ThemeFuse/Unyson#3433]
Is there any tutorials to explain how to validate shortcode fields ?

**Comment by jonmlas** [comment]
I'm afraid you have to create your own ajax validator. You can use attr to add class to an option field.

**Comment by ViorelEremia** [comment]
There are no validation tutorials and generally, unyson has no validation methods. The only way is to create your own validator on save post, or on ajaxd request
on save post the options are as an array to extract it use function ```fw_get_db_post_option($post->ID, 'page-builder'))```
