### ISSUE TITLE
Theme Settings issue. jQurey is not defined

### ISSUE THREAD

**Issue by etwordpress01** [ThemeFuse/Unyson#3434]
One of our client is facing Theme Settings issue.  There are errors in Console. jQuery and fw not defined.

We deactivate all plugins and try to check but still Theme Settings is not loading.

I have attached screenshot, anyone can help?

![1](https://user-images.githubusercontent.com/31212934/41084638-2f3f61ce-6a4e-11e8-82ab-03559aaee10b.png)
![2](https://user-images.githubusercontent.com/31212934/41084639-2f6fb612-6a4e-11e8-8ec2-7d0e4094ef55.png)
![3](https://user-images.githubusercontent.com/31212934/41084640-2fb0448e-6a4e-11e8-9e79-e7dcce920cf5.png)

We have latest version of WordPress, Theme and Unyson plugin.

Thanks

**Comment by ViorelEremia** [comment]
Is your site on cloudflare?

**Comment by etwordpress01** [comment]
Hi, Yes site is on cloudflare?

**Comment by ViorelEremia** [comment]
Go to your cloudflare account and find the option something "Rocket load(beta)" and disable it. latger I'll be looking for a solution that will work with this enabled option

**Comment by etwordpress01** [comment]
Hi, One thing more that if we skip some settings then settings start working.  To debug, i just try to comment some settings and it get start working for few settings. When i uncomment other settings same issue occur.

Might be a server issue? or something else. I tried to resolve issue but fail.

Could you please help me
![4](https://user-images.githubusercontent.com/31212934/41085527-bf877a12-6a50-11e8-9f4e-78639b124810.png)

Thanks

**Comment by ViorelEremia** [comment]
No, I don't think is a server issue you just commented options who require jquery that's why the error disappears. Disable rocket load and refresh the page should work

**Comment by etwordpress01** [comment]
Hi, Thank you for your quick response.  My issue has resolved. 

You guys are awesome. Thank you very much for helping me.

Thanks again
