### ISSUE TITLE
More options for plugin 

### ISSUE THREAD

**Issue by sschristina** [ThemeFuse/Unyson#3435]
Hello,

I have used Unyson with "The Core" theme and it's great and has lots of options.

I have just installed Unyson on my blank theme and most of the added options are not there. 

Is there somewhere I can buy the Unyson plugin with all the options to use on my blank theme?

**Comment by andronic90** [comment]
Hello,

The Core theme is a Premium WordPress Theme build on Unyson Plugin.

You can buy developer license https://goo.gl/JLS6oG and use for unlimited websites, but if you need to create a theme form scratch you can use the [Journal Free Theme](https://themefuse.com/wp-themes-shop/journal/)  or you can use a blank theme and [Unyson Docs](http://manual.unyson.io/en/latest/)
