### ISSUE TITLE
How to change the color of the overlay of the single images?

### ISSUE THREAD

**Issue by matteoraggi** [ThemeFuse/Unyson#3438]
How to change the color of the overlay of the single images?
To me it is light blue and I don't know how to change it.
![image](https://user-images.githubusercontent.com/14081756/41138250-3e5e4606-6ae0-11e8-8dae-0c50d71f8059.png)

**Comment by ViorelEremia** [comment]
By default, unyson doesn't have overlay of the single images. This is what your theme is doing we do not know how the developer has implemented it, so please contact your theme developer here is only unyson framework issues
