### ISSUE TITLE
Section Titles

### ISSUE THREAD

**Issue by sschristina** [ThemeFuse/Unyson#3439]
Hello,

Please see the attached images - I have the box option where I can add the section names, but for some reason, they are not showing up? I would like to name each section if possible?

<img width="943" alt="screen shot 2018-06-08 at 09 31 26" src="https://user-images.githubusercontent.com/39095137/41147610-caaebb9a-6afe-11e8-9a9d-e5868af04730.png">

<img width="650" alt="screen shot 2018-06-08 at 09 31 37" src="https://user-images.githubusercontent.com/39095137/41147611-cac63072-6afe-11e8-8fec-e9a10c2c16a0.png">

**Comment by sschristina** [comment]
Can anyone help with the above at all?

**Comment by ViorelEremia** [comment]
I don't see your config.php from section:
```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$cfg = array(
	'page_builder' => array(
		'title'          => __( 'Section', 'domain' ),
		'description'    => __( 'Add a Section', 'domain' ),
		'popup_size'     => 'medium',
		'title_template' => '{{ if (!o.section_name) { }} {{- title}} {{ } }} {{ if (o.section_name) { }} {{- o.section_name}} {{ } }}',
		'type'           => 'section' // WARNING: Do not edit this
	)
);
```

**Comment by sschristina** [comment]
Hello,

Please see below:

<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$cfg = array(
	'page_builder' => array(
		'title'          => __( 'Section', 'the-core' ),
		'description'    => __( 'Add a Section', 'the-core' ),
		'popup_size'     => 'medium',
		'title_template' => '{{ if (!o.section_name) { }} {{- title}} {{ } }} {{ if (o.section_name) { }} {{- o.section_name}} {{ } }} {{ if (o.background_options.background == "color" && o.background_options.color.background_color.id == "fw-custom") { }} <span class="fw-theme-option-presentation-color" style="background-color:{{- o.background_options.color.background_color.color}}"></span> {{ } else if(o.background_options.background == "color"){ }} <span class="fw-theme-option-presentation-color fw_theme_bg_{{- o.background_options.color.background_color.id}}"></span> {{ } }}',
		'type'           => 'section', // WARNING: Do not edit this
		'popup_header_elements' => '<a class="fw-docs-link" target="_blank" href="http://docs.themefuse.com/the-core/your-theme/shortcodes/sections-1"><span class="fw-docs-info dashicons dashicons-editor-help"></span>'.__('Go to Docs', 'the-core').'</a>',
	)
);

**Comment by sschristina** [comment]
Do I need to change this?

**Comment by sschristina** [comment]
Can anyone help with the above?

**Comment by ViorelEremia** [comment]
@sschristina I gave the working code: 
```
$cfg = array(
	'page_builder' => array(
		'title'          => __( 'Section', 'domain' ),
		'description'    => __( 'Add a Section', 'domain' ),
		'popup_size'     => 'medium',
		'title_template' => '{{ if (!o.section_name) { }} {{- title}} {{ } }} {{ if (o.section_name) { }} {{- o.section_name}} {{ } }}',
		'type'           => 'section' // WARNING: Do not edit this
	)
);
```
it is working i'm sure. "section_name" should it must coincide with the setting key for the section name paste it in your section/config.phnp.

**Comment by sschristina** [comment]
Hello,

I have added:

$cfg = array(
	'page_builder' => array(
		'title'          => __( 'Section', 'domain' ),
		'description'    => __( 'Add a Section', 'domain' ),
		'popup_size'     => 'medium',
		'title_template' => '{{ if (!o.section_name) { }} {{- title}} {{ } }} {{ if (o.section_name) { }} {{- o.section_name}} {{ } }}',
		'type'           => 'section' // WARNING: Do not edit this
	)
);




but it has broken the website - please see attached screenshot. 

![screenshot 2018-06-18 10 44 00](https://user-images.githubusercontent.com/39095137/41529349-ca18363c-72e4-11e8-9f6f-abdc3ea221d8.png)

**Comment by sschristina** [comment]
I put the above in the /section/config.php file

**Comment by danyj** [comment]
did you forget php opening on top of the file?

`<?php`

**Comment by sschristina** [comment]
I did! Thank you so much :---)
