### ISSUE TITLE
[question] Do you have a helper function that is processing options form names and values

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#344]
I am browsing Unyson helper functions and looking for a function/method to convert the options form
names and values 

	fw_options[text_color] | '#40b1e2'
	fw_options[link_color] | '#333333'
	fw_options[heading_color] | '#454545'
	fw_options[layout_type][gadget] | 'boxed'

to something like this 

	'link_color' => '#40b1e2',
	'text_color' => '#333333',
	'heading_color' => '#454545',
	'layout_type-gadget' => 'boxed',

I am sending the form options names and values via ajax  

	$.ajax({
		type: "post",
		dataType: "json",
		url: ajaxurl,
		data: {
			'action': 'thz_convert_options',
			'thzoptions': self.thzoptions()
		},
		 success: function() {
		  //Do stuff here
		 }
	});

	function thz_convert_options (){
		
	
		if(!is_admin() && !isset($_POST['thzoptions']) ) return;
		
		$options = 	function_to_convert ( $_POST['thzoptions'] );	
		
		//wp_send_json here as response
		print_r($options);
		
	}
	add_action("wp_ajax_thz_convert_options", "thz_convert_options");

and before I convert those values myself I was wondering if there is a similar function that can do this  or something close to it. 

Any help is appreciated.

**Comment by levan1993** [comment]
function thz_convert_options (){


    if( ! is_admin() || ! isset( $_POST['thzoptions'] ) ) return;

    $options =  FW_Request::POST( fw_html_attr_name_to_array_multi_key( 'thzoptions' ), array() ); 

    //wp_send_json here as response
    print_r($options);

}

**Comment by danyj** [comment]
lol,  was just about to say that this helped
https://github.com/ThemeFuse/Unyson/blob/5bd763ffeee5b7da3fd765d98aaee63efa5ed08c/framework/helpers/general.php#L753

thnx bud!

**Comment by levan1993** [comment]
also change this
  if(!is_admin() && !isset($_POST['thzoptions']) ) return;
to this 
  if( ! is_admin() || ! isset( $_POST['thzoptions'] ) ) return;

**Comment by danyj** [comment]
why ? I am checking if is admin AND the thzoptions is sent via post than run the function , otherwise if I use || the post "could"  be sent from frontend as well. Or am I mistaking ?

**Comment by levan1993** [comment]
you are checking if is not admin and doesn't isset your options, so this 
     if(!is_admin() && !isset($_POST['thzoptions']) ) return; will always return false

**Comment by levan1993** [comment]
you are using && insted of -  ||

**Comment by danyj** [comment]
Function works fine as I have it now , maybe I dont understand you but this is how I am seeing this

	something function (){
	
		if is NOT admin AND there is not set thzoptions return (dont run the function )
		
		//  this IS admin AND thzoptions is SET continue
		
	}

**Comment by levan1993** [comment]
oops! I missed "!"

**Comment by danyj** [comment]
never mind , new set of eyes is always welcome :)

**Comment by levan1993** [comment]
insted of return you can write - wp_send_json_error();

**Comment by moldcraft** [comment]
I think this is a better (browser native) solution, instead of sending custom data structure

```php
$.ajax({
    type: "post",
    dataType: "json",
    url: ajaxurl,
    data: jQuery.param( // "fw_options%5Btext_color%5D=%2340b1e2&fw_options%5Blink_color%5D=%23333333&action=thz_convert_options"
        jQuery.extend(
            {'fw_options[text_color]':'#40b1e2','fw_options[link_color]':'#333333'} // self.thzoptions()
        ), 
        {'action': 'thz_convert_options'}
        )
    ),
    success: function() {
        // Do stuff here
    }
});
```

then on php side you will have

```php
FW_Request::POST('fw_options') == array(
    'text_color' => '#40b1e2',
    'link_color' => '#333333',
);
```

**Comment by danyj** [comment]
@moldcraft im having bit of the trouble with that one.   
with your example as far as I can see I need to do form.serializeArray()  or form.serailize() but nothing is returned 

			$.ajax({
				type: "post",
				dataType: "json",
				url: ajaxurl,
				data: $.param(
					$.extend(
						$('.fw-settings-form').serializeArray(), // or $('.fw-settings-form').serialize()
						{'action': 'thz_convert_options'}
					)
				),
				success: function() {
					// Do stuff here
				}
			});


combo of $param and $extend lost me a bit.

**Comment by moldcraft** [comment]
If you would execute `jQuery('.fw-settings-form').serializeArray()` and `$('.fw-settings-form').serialize()` in console you would notice that both doesn't return object.

So try 

```js
data: $('.fw-settings-form').serialize() +'&action=thz_convert_options'
```

**Comment by danyj** [comment]
I tried the problem is that the $('.fw-settings-form').serialize()  or serializeArray runs a save automatically instead of running my action check this out 


This 


			$.ajax({
				type: "post",
				dataType: "json",
				url: ajaxurl,
				data: $.param(
					$.extend(
						{'fw_options[text_color]':'#40b1e2','fw_options[link_color]':'#333333'}, 
						{'action': 'thz_convert_options'}
					)
				),
				//data: values +'&action=thz_first_load',
				success: function() {
					// Do stuff here
				}
			});



	function thz_convert_options(){
		
		$return = array(
			'message'	=> FW_Request::POST('fw_options'),
		);	
		wp_send_json($return);
		
	}
	add_action("wp_ajax_thz_convert_options", "thz_convert_options");


Returns what I expect http://prntscr.com/6fub4b


This 

			$.ajax({
				type: "post",
				dataType: "json",
				url: ajaxurl,
				data: $.param(
					$.extend(
						$('.fw-settings-form').serializeArray(), 
						{'action': 'thz_convert_options'}
					)
				),
				//data: values +'&action=thz_first_load',
				success: function() {
					// Do stuff here
				}
			});


returns 
http://prntscr.com/6fubh6

**Comment by moldcraft** [comment]
The save happens because of 

```html
<input type="hidden" name="fwf" value="fw_settings">
```

Try to remove it

```js
data: $('.fw-settings-form').serialize().replace('fwf=', '_=') +'&action=thz_convert_options'
```

**Comment by danyj** [comment]
OK ok,   thnx that works well!. It is a long form and I was looking for culprit.
