### ISSUE TITLE
How could I load google fonts??

### ISSUE THREAD

**Issue by shaonsina** [ThemeFuse/Unyson#3441]
I have made a theme which has an option for the user to select google fonts. But the problem is how to load the google fonts which has selected the users??

For example, Two type of fonts have selected the user (screenshot)
![screenshot_3](https://user-images.githubusercontent.com/20015610/41203069-2f4bcfb0-6cf4-11e8-9c32-79dabc82ba4f.png)

and I want to load these fonts in the front-end.

**Comment by ViorelEremia** [comment]
Please read here: https://github.com/ThemeFuse/Unyson/issues/2384
