### ISSUE TITLE
Unable to download Translate Press plugin.

### ISSUE THREAD

**Issue by Wuruwhi** [ThemeFuse/Unyson#3442]
Hi,

Great plugin, I really love it.
On one of my sites, Unyson got installed by a theme I added, it then asked to install 4 Unyson plugins (which worked perfectly) but now I do not seem to be able to add Translate Press. I wanted to enable the Translate Press, but clicking on the download button only brings up a white empty little popup window.

I tried deactivating and activating back the Unyson plugin but no luck.

Any idea how I could install this plugin or fix this behaviour?

Cheers,

**Comment by ViorelEremia** [comment]
Thanks for reporting. Today will be an update that will solve the issue.
