### ISSUE TITLE
Call to undefined function fw_get_db_customizer_option()

### ISSUE THREAD

**Issue by GreenLightSM** [ThemeFuse/Unyson#3443]
Hi, i've created "style.php" file and trying to get colors from customizer like this: "$first_color = fw_get_db_customizer_option('bg-color-1');", but i have an error: "Call to undefined function fw_get_db_customizer_option()". What should i do? Thank you!

**Comment by ViorelEremia** [comment]
Where do you include style.php? if directly in functions.php you can't because of unyson is available to hook ```after_setup_theme```. 
```
function _action_theme_after_setup_theme() {
	// include here your file.

}
add_action( 'after_setup_theme', '_action_theme_after_setup_theme', 11 );
```

**Comment by GreenLightSM** [comment]
Oh, thanks! Gonna try it:)

пн, 11 июн. 2018 г. в 17:13, ViorelEremia <notifications@github.com>:
