### ISSUE TITLE
Page Builer in Posts Page

### ISSUE THREAD

**Issue by mltcorp** [ThemeFuse/Unyson#3445]
The Update button doesn't show and have a JS error.
<img width="1913" alt="screen shot 2018-06-11 at 14 31 18" src="https://user-images.githubusercontent.com/20816799/41247352-2692980a-6d84-11e8-8344-8cc2d475b133.png">

**Comment by ViorelEremia** [comment]
Have you the latest unyson version?  this issue has been solved a month ago

**Comment by mltcorp** [comment]
Hi,
Yes, I have latest version, I use WordPress 4.9.6 | Unyson 2.7.17

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
I don't see any issue. Where is the issue? what page?

**Comment by mltcorp** [comment]
Right
Wordpress Acess:
viorel@themefuse.com
IL!QsEl1sET4M5I&iyW5YNej

SFTP acess PORT: 5507
user: themefusion
pass: wordpress

Page builder in post pages don't work

Compartilhe conosco sua opinião e nos ajude a aprimorar nossos serviços e
atendimento clicando aqui <https://goo.gl/RDZrYH>.

Atenciosamente,

Equipe MLTCorp
Tel.: +55 11 3711-5628
MLTCorp - Uma empresa verde.



2018-06-13 10:42 GMT-03:00 ViorelEremia <notifications@github.com>:

**Comment by mltcorp** [comment]
Right
Wordpress Acess:
homolog.comtele.com.br/wp-admin
viorel@themefuse.com
IL!QsEl1sET4M5I&iyW5YNej

SFTP acess PORT: 5507
user: themefusion
pass: wordpress

Page builder in post pages don't work

Compartilhe conosco sua opinião e nos ajude a aprimorar nossos serviços e
atendimento clicando aqui <https://goo.gl/RDZrYH>.

Atenciosamente,

Equipe MLTCorp
Tel.: +55 11 3711-5628
MLTCorp - Uma empresa verde.



2018-06-13 11:03 GMT-03:00 Thales Maria <thales.maria@mltcorp.com.br>:

**Comment by ViorelEremia** [comment]
I don't see any issue. Where is the issue? what page?

**Comment by mltcorp** [comment]
You need to activate blog posts page builder and try to use page builder in
any blog posts.

Compartilhe conosco sua opinião e nos ajude a aprimorar nossos serviços e
atendimento clicando aqui <https://goo.gl/RDZrYH>.

Atenciosamente,

Equipe MLTCorp
Tel.: +55 11 3711-5628
MLTCorp - Uma empresa verde.



2018-06-13 11:06 GMT-03:00 ViorelEremia <notifications@github.com>:

**Comment by ViorelEremia** [comment]
Have you the option "Rocket load" enabled in your account cloudflare.com?

**Comment by ViorelEremia** [comment]
Go to your account cloudflare and clear the cache.

**Comment by mltcorp** [comment]
No this option disabled in my cloudflare.

​

Compartilhe conosco sua opinião e nos ajude a aprimorar nossos serviços e
atendimento clicando aqui <https://goo.gl/RDZrYH>.

Atenciosamente,

Equipe MLTCorp
Tel.: +55 11 3711-5628
MLTCorp - Uma empresa verde.



2018-06-13 11:12 GMT-03:00 ViorelEremia <notifications@github.com>:

**Comment by mltcorp** [comment]
Ok, I already do it.
Do you have a Skype account?
Please add suporte.mltcorp

Compartilhe conosco sua opinião e nos ajude a aprimorar nossos serviços e
atendimento clicando aqui <https://goo.gl/RDZrYH>.

Atenciosamente,

Equipe MLTCorp
Tel.: +55 11 3711-5628
MLTCorp - Uma empresa verde.



2018-06-13 11:14 GMT-03:00 ViorelEremia <notifications@github.com>:

**Comment by mltcorp** [comment]
Have any update?

Compartilhe conosco sua opinião e nos ajude a aprimorar nossos serviços e
atendimento clicando aqui <https://goo.gl/RDZrYH>.

Atenciosamente,

Equipe MLTCorp
Tel.: +55 11 3711-5628
MLTCorp - Uma empresa verde.



2018-06-13 11:15 GMT-03:00 Thales Maria <thales.maria@mltcorp.com.br>:

**Comment by ViorelEremia** [comment]
do you clear the cache in cloudflare? It seems you have an old cache because this issue was solved a long time ago. Also the unyson js files are minified unyson doesn't have minified files.

**Comment by mltcorp** [comment]
Yes,

I already do it.

Compartilhe conosco sua opinião e nos ajude a aprimorar nossos serviços e
atendimento clicando aqui <https://goo.gl/RDZrYH>.

Atenciosamente,

Equipe MLTCorp
Tel.: +55 11 3711-5628
MLTCorp - Uma empresa verde.



2018-06-13 12:08 GMT-03:00 ViorelEremia <notifications@github.com>:

**Comment by mltcorp** [comment]
Hi Viorel,
You have any update?

**Comment by ViorelEremia** [comment]
I'm sorry I do not remember what was your site I have dozens of emails but I don't see your thread in any of them. What is your site? something with ```homolog```

**Comment by mltcorp** [comment]
homolog.comtele.com.br

Compartilhe conosco sua opinião e nos ajude a aprimorar nossos serviços e
atendimento clicando aqui <https://goo.gl/RDZrYH>.

Atenciosamente,

Equipe MLTCorp
Tel.: +55 11 3711-5628
MLTCorp - Uma empresa verde.



2018-06-14 9:07 GMT-03:00 ViorelEremia <notifications@github.com>:

**Comment by ViorelEremia** [comment]
I write to your developer @duongancol about the issue. There is a cache or something similar like redirects to another files on your server or compresion which loads old unyson files. Write to your server administrtor it is not a unyson issue.

**Comment by mltcorp** [comment]
Viorel,
I'm server administrator and the server doesn't have cache modules, and my subdomain do not resolve to cloudflare server.
In my server have nginx + mysql + php 7 only

**Comment by ViorelEremia** [comment]
then why when I try to change a file it does not change in the browser? 
why does the server give the browser an old file?
this issue was solved here you can see there was three versions ago.
https://github.com/ThemeFuse/Unyson/commit/8af18b9907e58fdc28bcee88bbcc10fb64e4e91f

**Comment by mltcorp** [comment]
Viorel,
I already resolve, in my server x-page-speed is active in nginx, and conflict with your theme (it's very disappointing).
Thanks for your assitance
