### ISSUE TITLE
Update Button problems in Pages Udpate

### ISSUE THREAD

**Issue by mltcorp** [ThemeFuse/Unyson#3446]
Hi,
I have a problem with page biulder unyson, when I update page with any changes.
Before I update two buttons show, after update, only one button shows and I can not change anything else.
I need change any text, in text block, and the page that I editing broken.
![pass1](https://user-images.githubusercontent.com/20816799/41248554-c8d561b2-6d87-11e8-8663-97c768908c26.jpg)
![pass2](https://user-images.githubusercontent.com/20816799/41248562-cd56942c-6d87-11e8-8811-db4d7a1af998.jpg)

**Comment by jonmlas** [comment]
Have you tried to disable other plugins?

**Comment by mltcorp** [comment]
Yes, I already do it.

Compartilhe conosco sua opinião e nos ajude a aprimorar nossos serviços e
atendimento clicando aqui <https://goo.gl/RDZrYH>.

Atenciosamente,

Equipe MLTCorp
Tel.: +55 11 3711-5628
MLTCorp - Uma empresa verde.



2018-06-13 11:38 GMT-03:00 Jon-Michael Lastimosa <notifications@github.com>:
