### ISSUE TITLE
Demo content installation damage DB

### ISSUE THREAD

**Issue by skenzo34** [ThemeFuse/Unyson#3447]
Hello!
We have the problem in the new Unyson version. After the demo content installation, the database is broken and needs to repair.
If the demo content installs without WooCommerce plugin - all is good. But if WooCommerce plugin is active - DB go down and you can't access even to the admin panel.
How to fix this problem? In the later versions, there is no problem like this :(

**Comment by ViorelEremia** [comment]
Duplicate: https://github.com/ThemeFuse/Unyson/issues/3422
