### ISSUE TITLE
Page Builder Extension Error

### ISSUE THREAD

**Issue by tmcwilliams** [ThemeFuse/Unyson#3449]
I am trying to install the Page Builder extension, but continue to get this message:

Cannot download the "Shortcodes" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Am I doing something wrong?

**Comment by ViorelEremia** [comment]
That is not a unyson issue try: https://github.com/ThemeFuse/Unyson/issues/3231
Sometimes it is solved if you increase your php version.
