### ISSUE TITLE
Can't edit previously added images in the gallery. Looks like this:

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#345]
![gallery](https://cloud.githubusercontent.com/assets/11438910/6615896/f89e9834-c8b0-11e4-8eda-943ba260fe61.png)

**Comment by moldcraft** [comment]
This [was fixes](https://github.com/ThemeFuse/Unyson/issues/324) but we didn't published the new release, I will publish it today. Until then, you can try to add a non empty [`template` parameter](http://manual.unyson.io/en/latest/options/built-in-option-types.html#addable-box) to that option, for e.g.

```php
'template' => '{{- some_box_option_id }}'
```

or

```php
'template' => '&nbsp;'
```

**Comment by moldcraft** [comment]
> @moldcraft I will publish it today

Sorry, the release will be delayed until tomorrow.
