### ISSUE TITLE
Custom HTML

### ISSUE THREAD

**Issue by sschristina** [ThemeFuse/Unyson#3450]
Hello,

How would I add the 'custom html' or 'raw code' option into the Unyson options at the top?

**Comment by sschristina** [comment]
Also the 'space' option?

**Comment by jonmlas** [comment]
You can do so with this array http://manual.unyson.io/en/latest/options/built-in/html.html

**Comment by sschristina** [comment]
Thank you, where would I need to put this HTML for it to work on my page builder?

array(
    'type'  => 'html',
    'value' => 'default hidden value',
    'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
    'label' => __('Label', '{domain}'),
    'desc'  => __('Description', '{domain}'),
    'help'  => __('Help tip', '{domain}'),
    'html'  => 'My <b>custom</b> <em>HTML</em>',
)
