### ISSUE TITLE
multi-select post order

### ISSUE THREAD

**Issue by mbtocalli** [ThemeFuse/Unyson#3451]
I'm using a multi-select option to retrieve posts. It works as expected.. when I start typing it retrieves all posts with that keyword, however, I would like to get the retrived posts ordered by date. Is that possible? I don't understand the current order of the retrieved posts

**Comment by jonmlas** [comment]
I'm afraid it only retrieves the keyword as per manual http://manual.unyson.io/en/latest/options/built-in/multi-select.html.

**Comment by ViorelEremia** [comment]
It's not possible. I've analyzed the multi-select code now and it is possible but it's hard to maintain compatibility with those who have already used this option type. There are too many issues related to it so at the moment I think it would be good to make a new option type and adapt it to your desire.
