### ISSUE TITLE
Getting JS error ( TypeError: Cannot set property 'format' of undefined ), Event Extension

### ISSUE THREAD

**Issue by qutub-bharmal** [ThemeFuse/Unyson#3452]
Please check below error:

```
TypeError: Cannot set property 'format' of undefined
    at scripts.js?ver=2.7.17:31
    at dispatchSingleEvent (fw-events.js?ver=2.7.17:169)
    at Array.map (<anonymous>)
    at fw-events.js?ver=2.7.17:147
    at objectMap (fw-events.js?ver=2.7.17:250)
    at Object.fwEvents.trigger (fw-events.js?ver=2.7.17:131)
    at HTMLDivElement.init (script.js?ver=4.9.6:14)
    at Function.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2)
    at a.fn.init.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,underscore,backbone,moxiejs,plupload&ver=4.9.6:2)
    at script.js?ver=4.9.6:271
```

That's because of I have overwrite script file ( https://github.com/ThemeFuse/Unyson-Events-Extension/blob/master/includes/option-types/event/static/js/scripts.js#L14 )

```
var $dateTimeFirstWrapper = data.el.find('.xyzprefix-event-dates .fw-option-type-datetime-picker:first'),
$dateTimeLastWrapper = data.el.find('.xyzprefix-event-dates .fw-option-type-datetime-picker:last'),
```

I need to overwrite this lines because I have added another date rage picker options and when we change the All day event, it change format to other date range picker also.

Can you please provide possible solutions.

**Comment by qutub-bharmal** [comment]
Any update here ?

**Comment by ViorelEremia** [comment]
I think your jquery object, not exists. I mean: ```$dateTimeFirstWrapper = data.el.find('.xyzprefix-event-dates .fw-option-type-datetime-picker:first')``` you must have an object that has an attr ```data-datetime-attr``` with a json like: ```data-datetime-attr="{"format":"Y\/m\/d H:i","extra-formats":["Y\/m\/d"],"moment-format":"YYYY\/MM\/DD HH:mm","maxDate":"2038\/01\/19","minDate":"1970\/01\/01","timepicker":true,"datepicker":true,"defaultTime":"08:00","fixed":true,"scrollInput":false}"``` 
If the ```$dateTimeFirstWrapper```  is undefined then the var ```dateTimeFirstAttrs``` is also undefined(so you get an error of undefined ```format``` in line ```dateTimeFirstAttrs.format = format;```). Check if jquery can find something by your class ```.xyzprefix-event-dates .fw-option-type-datetime-picker:first``` is it in the object backbone ```data.el```?

**Comment by qutub-bharmal** [comment]
Hello, 

It is there to parent div element with class fw-option-type-datetime-picker

`data-datetime-attr="{"format":"Y\/m\/d H:i","extra-formats":["Y\/m\/d"],"moment-format":"YYYY\/MM\/DD HH:mm","maxDate":"2118\/06\/18","minDate":"1918\/06\/18","timepicker":true,"datepicker":true,"defaultTime":"08:00","fixed":true,"step":15,"scrollInput":false}"`

**Comment by qutub-bharmal** [comment]
By the way I have user date rage piker array to create meta object and also add class using parameter in that array. so I have inherits unyson format and code only. It is working fine with select dates etc. it just give error of JS.

**Comment by ViorelEremia** [comment]
I don't understand.
are you sure you changed only two lines of code? paste here the file scripts.js

**Comment by qutub-bharmal** [comment]
`
(function($, fwe) {


	var init = function() {
		var $eventOptionEl = $(this),
			$allDaySwitch = $eventOptionEl.find('[id="fw-option-general-event-all_day"] input'),
			$eventsPopup = $eventOptionEl.find('.fw-backend-option-input-type-addable-popup');


		/**
		 * Update date_time format consider checkbox value
		 */
		fwe.on('fw:options:datetime-range:before-init', function(data){
			var $dateTimeFirstWrapper = data.el.find('.xyzprefix-event-dates .fw-option-type-datetime-picker:first'),
				$dateTimeLastWrapper = data.el.find('.xyzprefix-event-dates .fw-option-type-datetime-picker:last'),
				$dateTimeFirstInput = data.el.find('input'),
				$dateTimeLastInput = data.el.find('input'),
				dateTimeFirstAttrs = $dateTimeFirstWrapper.data('datetime-attr'),
				dateTimeLastAttrs = $dateTimeLastWrapper.data('datetime-attr'),
				format = 'Y/m/d H:i',
				newMomentFormat = 'YYYY/MM/DD HH:mm',
				timepicker = true;

			if ($allDaySwitch.is(':checked')) {
				format = 'Y/m/d';
				newMomentFormat = 'YYYY/MM/DD';
				timepicker = false;

			}

			dateTimeFirstAttrs.format = format;
			dateTimeLastAttrs.format = format;
			dateTimeFirstAttrs.timepicker = timepicker;
			dateTimeLastAttrs.timepicker = timepicker;

			$dateTimeLastWrapper.data('datetime-attr',dateTimeLastAttrs);
			$dateTimeFirstWrapper.data('datetime-attr',dateTimeFirstAttrs);

			$dateTimeFirstInput.data('moment-format', newMomentFormat);
			$dateTimeLastInput.data('moment-format', newMomentFormat);

		});

		/**
		 * Update values with new format
		 */
		fwe.on('fw:options:datetime-picker:before-init', function(data){

			if (data.el.parents('.fw-option-type-datetime-range').length){
				var newMomentFormat = 'YYYY/MM/DD HH:mm';

				if ($allDaySwitch.is(':checked')) {
					newMomentFormat = 'YYYY/MM/DD';
				}

				if (data.el.val()) {
					var value = moment(data.el.val(), data.el.data('moment-format')).format(newMomentFormat);
					data.el.val(value);
					data.options.value = value;
				}
			}

		});

		$allDaySwitch.on('change', function(){
			var momentFormat = 'YYYY/MM/DD HH:mm',
				allDay = false;

			if ($allDaySwitch.is(':checked')) {
				momentFormat = 'YYYY/MM/DD';
				allDay = true;
			}

			$eventsPopup.find('.item:not(.disabled)').each(function(){
				var data = $.parseJSON($(this).find('input').val());
				if (data.event_date_range.from !== "" && data.event_date_range.to !== "" ) {
					var from = new Date(data.event_date_range.from),
						to = new Date(data.event_date_range.to);

					if (allDay) {
						$(this).find('input').data('from-time', moment(from.toISOString()).format('HH:mm') );
						$(this).find('input').data('to-time', moment(to.toISOString()).format('HH:mm'));
					} else {
						var fromTime = moment($(this).find('input').data('from-time'), 'HH:mm').toDate(),
							toTime = moment($(this).find('input').data('to-time'), 'HH:mm').toDate();

						from.setHours(fromTime.getHours());
						to.setHours(toTime.getHours());
						from.setMinutes(fromTime.getMinutes());
						to.setMinutes(toTime.getMinutes());

					}

					data.event_date_range.from = moment(from.toISOString()).format(momentFormat);
					data.event_date_range.to =  moment(to.toISOString()).format(momentFormat);

					$(this).find('input').val(JSON.stringify(data));
					$(this).find('.content').text(data.event_date_range.from + ' - ' + data.event_date_range.to);
				}
			})

		});

	}

	fwe.on('fw:options:init', function(data) {
		data.$elements
			.find('.fw-option-type-events:not(.fw-option-initialized)')
			.each(init)
			.addClass('fw-option-initialized');
	});

})(jQuery, fwEvents);
`

**Comment by ViorelEremia** [comment]
Paste again ```console.log($dateTimeFirstWrapper);``` you paste above the console object 
```a.fn.init [selector: ".xyzprefix-event-dates .fw-option-type-datetime-picker:first", prevObject: a.fn.init(1), context: div#fw-edit-options-modal-event_date_range.fw-option.fw-option-type-datetime-range.eventastic-event-…]```
Open it and check the length. Js is ok i checked it.

**Comment by qutub-bharmal** [comment]
Here is:

`a.fn.init [selector: ".eventastic-event-dates .fw-option-type-datetime-picker:first", prevObject: a.fn.init(1), context: div#fw-edit-options-modal-event_date_range.fw-option.fw-option-type-datetime-range.eventastic-event-…]`

**Comment by qutub-bharmal** [comment]
Why length is zero?

`context: div#fw-edit-options-modal-event_date_range.fw-option.fw-option-type-datetime-range.eventastic-event-dates.fw-option-initialized
length: 0`

**Comment by ViorelEremia** [comment]
Because jquery can't find it.
Is the div with class xyzprefix-event-dates the parent of fw-option-type-datetime-picker?

**Comment by qutub-bharmal** [comment]
So How can I resolve issue?
It show / hide time for other date range picker available as event meta ?

**Comment by ViorelEremia** [comment]
Try:
```var $dateTimeFirstWrapper =  data.el.find('.xyzprefix-event-dates .fw-option-type-datetime-picker:first').length > 0 ? data.el.find('.xyzprefix-event-dates .fw-option-type-datetime-picker:first') : data.el.find('.fw-option-type-datetime-picker:first'),```
Do the same for ```$dateTimeLastWrapper```

**Comment by qutub-bharmal** [comment]
Okay got the issue, it add the class at the same level element:

I have added below code at top and it works, so now function is:

`fwe.on('fw:options:datetime-range:before-init', function(data){
	**if( ! data.el.hasClass('xyzprefix-event-dates') ) {
		return;
	}**

	var $dateTimeFirstWrapper = data.el.find('.fw-option-type-datetime-picker:first'),
		$dateTimeLastWrapper = data.el.find('.fw-option-type-datetime-picker:last'),
		$dateTimeFirstInput = data.el.find('input'),
		$dateTimeLastInput = data.el.find('input'),
		dateTimeFirstAttrs = $dateTimeFirstWrapper.data('datetime-attr'),
		dateTimeLastAttrs = $dateTimeLastWrapper.data('datetime-attr'),
		format = 'Y/m/d H:i',
		newMomentFormat = 'YYYY/MM/DD HH:mm',
		timepicker = true;

	if ($allDaySwitch.is(':checked')) {
		format = 'Y/m/d';
		newMomentFormat = 'YYYY/MM/DD';
		timepicker = false;

	}

	dateTimeFirstAttrs.format = format;
	dateTimeLastAttrs.format = format;
	dateTimeFirstAttrs.timepicker = timepicker;
	dateTimeLastAttrs.timepicker = timepicker;

	$dateTimeLastWrapper.data('datetime-attr',dateTimeLastAttrs);
	$dateTimeFirstWrapper.data('datetime-attr',dateTimeFirstAttrs);

	$dateTimeFirstInput.data('moment-format', newMomentFormat);
	$dateTimeLastInput.data('moment-format', newMomentFormat);
});`

**Comment by ViorelEremia** [comment]
Maybe is good but not enough for pickers without class ```xyzprefix-event-dates``` will not work. Try better what I gave you.

**Comment by qutub-bharmal** [comment]
I think hide or show time should be only work for event dates settings, not for other.

**Comment by ViorelEremia** [comment]
Ok, so everything is fine?

**Comment by qutub-bharmal** [comment]
Yes

**Comment by qutub-bharmal** [comment]
It should be resolve from Unyson plugin it self. it is good if you will include in next update.

**Comment by ViorelEremia** [comment]
What to include is not clear to me

**Comment by qutub-bharmal** [comment]
The issue need to resolve, if any another meta of event uses date range picker is there it also hide show for that meta also.

For example I have added date time range picker schedule meta for event then it hide show the time picker fort that meta also even I have keep disable the time picker.

**Comment by ViorelEremia** [comment]
CAn you share some screenshots what you did? I think I imagined something wrong or you did something wrong. The option type ```FW_Option_Type_Event``` it is an internal option type for extension event so you cant use it in other parts of the site or to extend it.

**Comment by qutub-bharmal** [comment]
1ST OPT:
Just use same options for event dates which default it comes in event post type, check screenshot: https://prntscr.com/jwle3y.

2ND OPT:
I have added another meta box in same event post type only for the event schedule, please check screenshot: https://prntscr.com/jwldg6

Now, if I change "All Day Event?" option ( from 1ST OPT ), from Yes to No or No to Yes, it hide or show only times ( disable enable timepicker ) in "Date and Time" option ( from 1ST OPT ).

But, it also hide or show times in 2ND OPT date range also. even I have disable time picker by parameter here screenshot: https://prnt.sc/jwlh94.

URL of option type I have use from unyson is: http://manual.unyson.io/en/latest/options/built-in/datetime-range.html

Got it ?

**Comment by ViorelEremia** [comment]
Ok, I fiexed it here: https://github.com/ThemeFuse/Unyson-Events-Extension/commit/fbcc9ed345a51e37d3b9b9f7e4174e919890b284
