### ISSUE TITLE
Unison slowing down page loads?

### ISSUE THREAD

**Issue by ikir83** [ThemeFuse/Unyson#3453]
Hi! I've build www.leleniky.it for a friends who gets married, a wordpress website, we choosed a theme which is Glanz Wedding Theme which use Unyson.
https://themeforest.net/item/glanz-wedding-theme/20284445

Graphics is quite heavy but it seems something is wrong in loading, when Unyson is active the browser takes even 13 seconds to load homepage. I've tried to disable many plugins which I actually don't use even if needed y the theme/unyson but no luck. Could be a hosting issue with some PHP version or something else? Could be something I've destroyed with my little experience in wordpress?
Any hint would be very appreciated, thanks.

**Comment by ViorelEremia** [comment]
Try to install this plugin: https://wordpress.org/plugins/query-monitor/
Check that page load do you have
![wp just another wordpress site](https://user-images.githubusercontent.com/28967378/41348392-1f17f6f0-6f15-11e8-9df9-f0f543623ec7.png)

**Comment by jonmlas** [comment]
Upon checking your site, I don't see it as Unyson problem. It is a theme problem.

The theme author is using incredibly large image size!

Take for example the flower on the upper left of your homepage, that alone is almost 454kb!
http://www.leleniky.it/wp-content/themes/glanztheme/images/flowers_slider/fl1_c1.png

The images are not optimized for web.

**Comment by ikir83** [comment]
Ok i will try to lower them! Thanks for your help!

**Comment by ikir83** [comment]
Photos themselves were to big, even if php resized them, it looks to much time. I've scaled all photos and now the website is fast. thanks
