### ISSUE TITLE
Extensions Installation Error

### ISSUE THREAD

**Issue by bipedeverde** [ThemeFuse/Unyson#3454]
Hi, I am trying to install the extensions and I get the following error:

“Cannot download the "Shortcodes" extension zip. cURL error 35: Peer reports incompatible or unsupported protocol version.”

Can you help out?

Maybe it is something similar to [this issue](https://github.com/ThemeFuse/Unyson/issues/3312)?

Thank you

**Comment by jonmlas** [comment]
I had that cURL problem before. The problem was the hosting and my server has a lower version of cURL.

Try to ask your hosting provider to upgrade cURL or migrate your Wordpress site to an upgraded server.

**Comment by ViorelEremia** [comment]
Update cURL extensions and OpenSSL or increase your php version if you have the option in cpanel no contact your hosting provider or server adminstrator
