### ISSUE TITLE
Witrh last upgarde widgets disappear as well as translation

### ISSUE THREAD

**Issue by Oazar** [ThemeFuse/Unyson#3456]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.

Hello I just upgraded Unyson to latest version, and many widgets disppeared in my sidebars (but not all)
My website uses translate press, and all widgets translations had to be made all over again

So I have 2 others websites using unyson and translate press. Do you think somethinbg may be done so I can upgrade and avoid these problems ? It is long for me to do all this work again...

thanks

**Comment by ViorelEremia** [comment]
After update do you check if all unyson extensions are active as before the update? Whqat theme do you use? 
Some widgets are added by unyson extensions and during updating unyson copy the extensions to the tmp folder after selfupdated unyson copy the extensions back in unyson/framework/extensions and if there is no access to write then extensions are not enabled and your widgets will disappear.

**Comment by Oazar** [comment]
Hello and thanks for your answer,

Yes I always check if all I need is activated after upgrades

  I am using woffice theme : https://themeforest.net/item/woffice-intranetextranet-wordpress-theme/11671924

The widgets which have disappeared with last upgrade (they usually don't) are the projects widget, and the wiki widget. I checked both the tmp folder and the extension folder and both are set on 755, which should be OK ?
this is the first time this happens although i upgraded unyson several times since during the last year. Since then I added other extensions, the lastest being translate press extension. do you think this might be linked to this extension ? Should I desactivate it before upgrading maybe ?

**Comment by ViorelEremia** [comment]
I tested it right now and is working well. I see the extensions what was disabled on your site are not unyson extensions what means everything is fine with copy to tmp folder and back. The theme extensions are not in the path unyson/framework/extensions/... but in yourTheme/framework-customizations/extensions/..., on the unyson update, they are not moved to tmp folder, they are not touched at all. 
Can you send me the theme to: ```viorel@themefuse.com``` . I'll try to do some tests
