### ISSUE TITLE
cURL error 7: Failed to connect to github-api-cache.unyson.io port 80: Connection refused

### ISSUE THREAD

**Issue by marlebs** [ThemeFuse/Unyson#3457]
Hello, 
After update the wordpress site and Unyson plugin i receive this message: cURL error 7: Failed to connect to github-api-cache.unyson.io port 80: Connection refused

Could you help? My server ip is 67.225.209.185

**Comment by ViorelEremia** [comment]
How do you see this error? in admin dashboard or frontend? or on update extensions?
What hosting server do you have? are you the server administrator?
Can you try to add the below code in your functions.php of your theme:
```
add_action( 'wp_head', function () {
	$remote = wp_remote_get('https://api.github.com/');
	fw_print( $remote['body'] );
	$http = new WP_Http();
	$response = $http->get('https://api.github.com/');
	fw_print( $response['body'] );
} );
```
make a screenshot of frontend and post it here

**Comment by marlebs** [comment]
Hello, 

This error occurs in admin dashboard after the update plugin. On the server i have only CPANEL administration. After insert the above code, i receive the following message in frontend:

'{"current_user_url":"https://api.github.com/user","current_user_authorizations_html_url":"https://github.com/settings/connections/applications{/client_id}","authorizations_url":"https://api.github.com/authorizations","code_search_url":"https://api.github.com/search/code?q={query}{&page,per_page,sort,order}","commit_search_url":"https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}","emails_url":"https://api.github.com/user/emails","emojis_url":"https://api.github.com/emojis","events_url":"https://api.github.com/events","feeds_url":"https://api.github.com/feeds","followers_url":"https://api.github.com/user/followers","following_url":"https://api.github.com/user/following{/target}","gists_url":"https://api.github.com/gists{/gist_id}","hub_url":"https://api.github.com/hub","issue_search_url":"https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}","issues_url":"https://api.github.com/issues","keys_url":"https://api.github.com/user/keys","notifications_url":"https://api.github.com/notifications","organization_repositories_url":"https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}","organization_url":"https://api.github.com/orgs/{org}","public_gists_url":"https://api.github.com/gists/public","rate_limit_url":"https://api.github.com/rate_limit","repository_url":"https://api.github.com/repos/{owner}/{repo}","repository_search_url":"https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}","current_user_repositories_url":"https://api.github.com/user/repos{?type,page,per_page,sort}","starred_url":"https://api.github.com/user/starred{/owner}{/repo}","starred_gists_url":"https://api.github.com/gists/starred","team_url":"https://api.github.com/teams","user_url":"https://api.github.com/users/{user}","user_organizations_url":"https://api.github.com/user/orgs","user_repositories_url":"https://api.github.com/users/{user}/repos{?type,page,per_page,sort}","user_search_url":"https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"}'

Thanks

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
did you get my message?

**Comment by marlebs** [comment]
Hello,

Ιs there anything newer about it?

**Comment by ViorelEremia** [comment]
Your theme author uses an [old extension](https://github.com/ThemeFuse/Unyson-Backup-Extension) that we do not support anymore. There are three years since we no longer support, now we are using a better [backup extension ](https://github.com/ThemeFuse/Unyson-Backups-Extension) that's why the author of your theme must migrate the theme to the newest backup extension. 
can you write them to solve this issue?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
