### ISSUE TITLE
Add translatable .pot in unyson.

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson#346]
Need to add the the translatable .pot file in unsyon languages folder. Also solve the with extensions translation.

**Comment by Nic787** [comment]
Also be able to translate in visual builder page when writing in text block. Now if I change from french to english in the visual builder, I have the same thing.

**Comment by Nic787** [comment]
No comment from devs?

**Comment by sergiubagrin** [comment]
Hi @Nic787 

Right now we have a lot of issues. It will take some time to analyse this one. Thanks

**Comment by moldcraft** [comment]
https://wordpress.org/support/topic/multilanguage-21

**Comment by GheorgheP** [comment]
Hi @Nic787 

I know that you are using the qTranslate plugin, but am aware of full compatibility of that plugin with our framework, at the moment we are developing our translation system, so will be better if you will begin to use our translation extension.

We cannot guarantee the future compatibility of the Unyson with qTrsnlate plugin.

**Comment by moldcraft** [comment]
> so will be better if you will begin to use our translation extension.

Translation is not released yet. @llemurya will let us know whet it will be ready.
