### ISSUE TITLE
LiteSpeed webserver backup 

### ISSUE THREAD

**Issue by yonjah** [ThemeFuse/Unyson#3460]
After installing a theme that installed Unyson I was pointed to the following page to 
see instruction on how to solve backup issues 

http://manual.unyson.io/en/latest/extension/backups/index.html#litespeed-webserver

The fix -
```
RewriteRule .* - [E=noabort:1]
```

Will prevent abort on all php scripts instead of just the backup.
Wont it be better to include a list of files that require this fix instead ?

**Comment by ViorelEremia** [comment]
I don't understand what you mean?

> Wont it be better to include a list of files that require this fix instead ?

This code must be added to the .htaccess file. I think it's pretty clear writing. 
What a list of files?

**Comment by yonjah** [comment]
We'll if I check LightSpeed Docs -
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:run-without-timeouts
The  change suggested for the .htaccess will allow every single script to run uninterrupted basically completely disabling this feature.

LightSpeed docs also has an example of how to only allow specific scripts to run unlimited -

>     For wp-cron.php, backupbuddy.php, and importbuddy.php only.
> 
> ```
>  RewriteEngine On
> RewriteRule (wp-cron|backupbuddy|importbuddy)\.php - [E=noabort:1]
> ```

Isn't there a specific backup.php file for Unyson that can be white listed as above to get the backup working so there is no need to disable the limits completely ?

**Comment by ViorelEremia** [comment]
can you try:
```
RewriteRule (wp-cron|class-fw-extension-backups|class--fw-ext-backups-module-tasks)\.php - [E=noabort:1]
```

**Comment by yonjah** [comment]
What is the best way to test it ?
Is manually making a full backup is good enough ? (will it trigger the wp-cron file ?)
How can I be sure that backup process was long enough to actually fail if the override didn't work ?

**Comment by ViorelEremia** [comment]
Add a daily schedule or create a full backup and restore it, but restore it not on the ready site try on test subdomain

**Comment by yonjah** [comment]
I've setup a daily backup and I'll check it tomorrow 
Is there a way to verify the backup without doing an actual  restore ?

**Comment by ViorelEremia** [comment]
No, the best it is a real restore.

**Comment by ViorelEremia** [comment]
Have you tested? is it working?

**Comment by yonjah** [comment]
I just checked now.
The backup seemed to be created fine. Size look similar to other backups I had, and the zip file looks valid. Also the JSON dump for the db look correctly formatted with recent records.
So I think the backup went well but I'm not sure if I'll have the time to actually setup a test site to check a real restoration on.
