### ISSUE TITLE
Unyson - This page isn’t working 

### ISSUE THREAD

**Issue by erinrose2004** [ThemeFuse/Unyson#3461]
After initial installation of Jevelin and installing the demo page 'foodie', the home page worked and displayed as normal. However, when trying to create a new slider on slider revolution, when I refreshed the homepage this error occured:

This page isn’t working
... didn’t send any data.
ERR_EMPTY_RESPONSE 

The only way I can get the site to remotely work is to deactivate the Unyson plug in - which obviously I need in order to create content on the pages. 

Please help!

**Comment by ViorelEremia** [comment]
We need more information.
I think you have a php function deprecated or a fatal error. Try to enable the wp_debug constant: https://codex.wordpress.org/Debugging_in_WordPress

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
