### ISSUE TITLE
Unable to have a default 'open' tab for "Tabs" Content Element in Page Builder Extension

### ISSUE THREAD

**Issue by TotalCSR** [ThemeFuse/Unyson#3462]
We really want to leverage Tabs, but all the content within the tabs are shown as hidden UNTIL the tab is clicked. How do I have a "default" tab open right away?

**Comment by ViorelEremia** [comment]
By default, Unyson leaves the first tab open it has no opportunity to choose what tab to leave open. But developers of themes rewrite the default functionality. So what means if you do not have this opportunity you can make a request to the author of the theme to add this possibility.
If your tabs all of them are closed then it's an issue by default I tested is fine. does your theme overwrite the default tabs shortcode? what theme do you use? have you any errors in browser console?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
