### ISSUE TITLE
Page Builder issue

### ISSUE THREAD

**Issue by JEFFMACC** [ThemeFuse/Unyson#3464]
when i use the "page builder" and try to save changed ot a page over 8mg it will not let me - now of i turn off your page builder i can save pages or posts over 40mg as i have all my server settings and wordpress settings so i can do so, 

if i try to update any of my pages that are over 8 mg i get this error below only when using your "page builder"

Request Entity Too Large
The requested resource
/wp-admin/post.php
does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

i have reinstalled it and i still get the same issue.

**Comment by ViorelEremia** [comment]
How did you calculate the amount of data send in the post request? This issue is related to directive post_max_size usually it is 16mb but sometimes it is 8mb or less. Usually, if you increase these three directives solve the issue:
```
@ini_set( 'upload_max_size' , '64M' );
@ini_set( 'post_max_size', '64M');
@ini_set( 'max_execution_time', '300' );
```
Some servers don't allow to play with the php directives in this case you must contact them.

**Comment by JEFFMACC** [comment]
​we changed these settings to 50+ mg and still have the issue,  - we had 10
pages on the website that all of a sudden stopped letting us update them
and we are getting that error unless  content deleted untill page is under
8 mg.   https://gtmetrix.com/ we used to find out the page sides.

it only happens on useing your page builder. ​not other page builders.

**Comment by ViorelEremia** [comment]
are you sure they are increased? please check it in your cpanel. Also, you can check via php function ```ini_get( 'post_max_size' )``` on some servers this limit is 2mb and they don't allow you to change it. If these are increased then this can happen from this directive for server apache: https://httpd.apache.org/docs/2.0/mod/core.html#limitrequestbody and ngix server: https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
usually, you can change them only the server administrator can.
We had this kind of problem on some premium themes and we have solved the issue by enlarging these directives, clear cache, remove revisions, but most importantly if directives(post_max_size, etc) are increased then remains only the limitrequestbody.

**Comment by ViorelEremia** [comment]
have you found a solution to your issue?

**Comment by JEFFMACC** [comment]
Hi, we found the issue with the "wp rocket" blocking the option to save
website pages with your builder, thanks
