### ISSUE TITLE
Shortcode's bug in post.

### ISSUE THREAD

**Issue by krol1k** [ThemeFuse/Unyson#3466]
After opening the saved post the settings in it are reset.

**Comment by ViorelEremia** [comment]
What setting do you mean? What theme do you use? what post type in page or post? do you mean shortcode settings in modal or from the metabox?

**Comment by krol1k** [comment]
Icon Box - aligment, text, etc. Theme - The Core. Post type. Shortcode in the standart wp content editor.

**Comment by ViorelEremia** [comment]
It's a theme issue, please contact the [theme author](https://support.themefuse.com/hc/en-us/requests/new).
Here are only the unyson plugin issues
