### ISSUE TITLE
Uncaught TypeError: Cannot set property 'setup' of undefined

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#3467]
Hi
When we saved the page and with builder content after publishing nothing in builder. 
I cannot get pagebuilder to work. When I create a new page, insert sections, insert content elements, type in text or insert images and save, everything vanishes. Nothing is saved on the page. 

[Check this](https://youtu.be/5tzuO1Wco0M)

If I check console I found a error" 

> TypeError: Cannot set property 'setup' of undefined
>  /wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/pagebuilder/includes/page-builder/static/js/editor_integration.js?ver=1.6.1:209

I have tested with deactivate all third party plugin also deactivate unyson plugin alws same

**Comment by ViorelEremia** [comment]
I testted now on multisite and onesite installation on the local and online server but that is not happening to me.
Why do you have ```js/editor_integration.js?ver=1.6.1``` when the current version is ```1.6.16``` also in line 209 is nothing: https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/includes/page-builder/static/js/editor_integration.js#L209
Have you the latest extension version?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
