### ISSUE TITLE
Page options not compatible with Gutenberg 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3468]
Just installed and tested Gutenberg plugin and got

`T:\wamp64\www\Development\WordPress\wp-content\plugins\unyson\framework\core\components\backend.php`

http://prntscr.com/jy5jri

**Comment by ViorelEremia** [comment]
Use the classic editor to edit pages created with unyson page builder. Total compatibility I will add when he will be more stable and merged into wp core.
