### ISSUE TITLE
Forms Extension Missing Despite Installer Saying it Installed

### ISSUE THREAD

**Issue by GNAOnline** [ThemeFuse/Unyson#3469]
I have a theme installed in WordPress, but I am unable to properly edit the contact form in the theme. Any attempt to access full editing capabilities for the form leads to a message saying I must be in the admin view. But when I click the subsequent link to the Forms page, I get a WP error saying it doesn't exist.

I contacted the theme developer, who said I needed to deactivate, delete, then install and activate Unyson again to correct this. I have done so, and I have added all available extensions, and Unyson says the Forms extension is installed. But it never appears in the Unyson menu. It does not appear among the available extensions. Forms simply does not exist.

WP also said that I still needed to install a Unyson update, and I did that, and it downloads and installs a Unyson update from the theme developer, but nothing changes. Forms is still missing from the available extensions.

I have little to no WP experience, so I need help to understand how and why this is happening and how to fix it without overwriting or harming the website I have already been developing in WP. I don't believe I can update the theme without overwriting all the changes I have made to it, so that is not an option. There may have been a child theme available, but I don't know that my original developer used it. All the changes might be made to the main theme itself.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by GNAOnline** [comment]
Sorry, I am not sharing admin credentials with a total stranger online. That is not a secure or viable solution.

**Comment by ViorelEremia** [comment]
why do we need to respond to what your developer did? Contact him ask him why did he use a child theme? Ask why he did that ```it downloads and installs a Unyson update from the theme developer```. 
How can we know what he did? There are hundreds of reasons why he could do that. There are hundreds of ways he could do that. So how can we help you?

**Comment by GNAOnline** [comment]
The developer was terminated, so it is not possible to ask that person questions. The Unyson installer was saying it successfully installed the Forms extension, but it would not appear in WordPress. As it turns out, this had nothing to do with anything the developer did. Apparently there was a problem between the theme and Unyson. I still do not know exactly what caused it, but the theme creators were able to provide some updates to fix the issue. I am still mystified as to how Unyson could install an extension but have it be invisible in WordPress. But I don't code Unyson or the theme.
