### ISSUE TITLE
Form builder calculator

### ISSUE THREAD

**Issue by jonmlas** [ThemeFuse/Unyson#3471]
Hi, 

Can we create calculators using the form builder? Right now, what I see is that it can only creates contact forms.

I want to make something like this http://www.calculator.net/payback-period-calculator.html

Basically, it's just form fields and the values will be calculated and displayed to another page.

If it's possible, could you please show me the code? I'm not sure where to make calculations on the values passed.

The tutorial in http://manual.unyson.io/en/latest/extension/forms/ only teaches how to create the yes or no builder item type. I couldn't find other tutorials regarding Unyson forms.

Cheers!

**Comment by ViorelEremia** [comment]
Basically, it is possible to do so; but it is very hard you have to overwrite to much code and I don't have enough time to help you. I suggest you to try to find a free plugin because with unyson you will lose a lot of time until you get a result.

**Comment by jonmlas** [comment]
Thank you @ViorelEremia. Yeah, better use a plugin for that.
