### ISSUE TITLE
Cannot put information into table

### ISSUE THREAD

**Issue by mtmcgreg** [ThemeFuse/Unyson#3473]
I just updated my unyson plugin, as well as the extensions. Now I  cannot put information into a table, nor can I edit information within a table. Can you please help me resolve this?

**Comment by ViorelEremia** [comment]
How you can't put information into the table? Have you any errors in browser console? What do you mean table? is it a shortcode or a meta box options?

**Comment by mtmcgreg** [comment]
When I am using the page editor to create my layout for my pages, and I
place a table- when I open it I cannot click on the cells to edit them, or
enter information into them.

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
Something is cover you cells I think if you don't have skills of some programming languages it will be hard to find out

**Comment by ViorelEremia** [comment]
Solved restart of laptop

**Comment by lineacurva** [comment]
Hi guys, same issue here. Tables fields can't be edited. Only "buttons" can be edited. Extensions are up to date and I also rebooted. Any idea?
