### ISSUE TITLE
Demo Install issue

### ISSUE THREAD

**Issue by suhashininithy** [ThemeFuse/Unyson#3475]
Hi., 

When we have tried to import the demo via xampp server after unyson update it causes this issue 

[Tue Jun 26 14:58:13.147457 2018] [:error] [pid 11196:tid 1704] [client ::1:57700] PHP Fatal error:  Maximum execution time of 10 seconds exceeded in D:\\xampp\\htdocs\\theme-new\\theme-name\\wp-includes\\wp-db.php on line 1924, referer: http://localhost/theme-new/theme-name/wp-admin/admin-ajax.php

At the same time when import the demo via wamp it working fine. 

How to fix the issue ., too urgent ., 

Any one help me.,

**Comment by ViorelEremia** [comment]
Duplicate: https://github.com/ThemeFuse/Unyson/issues/3472

**Comment by suhashininithy** [comment]
Hi., 

Thank you for your fast response. I have applied this solution but it does same , 

Refer : http://prntscr.com/jzh24s 

And i could not understand the http://prntscr.com/jzh2ew , so can you please help me to sortout the issue. Plzzzz

Thank you in advance

**Comment by suhashininithy** [comment]
Hi., 

Sorry for the trouble , i know you are quite busy. If you don't mind please give knowledge for how to resolve this issue ?

**Comment by danyj** [comment]
@suhashininithy  we are testing here #3472, watch that post and lets continue there
