### ISSUE TITLE
Failed to access Github repository

### ISSUE THREAD

**Issue by FreshspaceHQ** [ThemeFuse/Unyson#3476]
Hi,

Getting this error message whilst trying to install Unyson extensions:

> Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 7: Failed to connect to github-api-cache.unyson.io port 80: Connection refused)

Added this code to functions.php:

add_action( 'wp_head', function () {
	$remote = wp_remote_get('https://api.github.com/');
	fw_print( $remote['body'] );
	$http = new WP_Http();
	$response = $http->get('https://api.github.com/');
	fw_print( $response['body'] );
} );

Which outputs as follows:

'{"current_user_url":"https://api.github.com/user","current_user_authorizations_html_url":"https://github.com/settings/connections/applications{/client_id}","authorizations_url":"https://api.github.com/authorizations","code_search_url":"https://api.github.com/search/code?q={query}{&page,per_page,sort,order}","commit_search_url":"https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}","emails_url":"https://api.github.com/user/emails","emojis_url":"https://api.github.com/emojis","events_url":"https://api.github.com/events","feeds_url":"https://api.github.com/feeds","followers_url":"https://api.github.com/user/followers","following_url":"https://api.github.com/user/following{/target}","gists_url":"https://api.github.com/gists{/gist_id}","hub_url":"https://api.github.com/hub","issue_search_url":"https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}","issues_url":"https://api.github.com/issues","keys_url":"https://api.github.com/user/keys","notifications_url":"https://api.github.com/notifications","organization_repositories_url":"https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}","organization_url":"https://api.github.com/orgs/{org}","public_gists_url":"https://api.github.com/gists/public","rate_limit_url":"https://api.github.com/rate_limit","repository_url":"https://api.github.com/repos/{owner}/{repo}","repository_search_url":"https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}","current_user_repositories_url":"https://api.github.com/user/repos{?type,page,per_page,sort}","starred_url":"https://api.github.com/user/starred{/owner}{/repo}","starred_gists_url":"https://api.github.com/gists/starred","team_url":"https://api.github.com/teams","user_url":"https://api.github.com/users/{user}","user_organizations_url":"https://api.github.com/user/orgs","user_repositories_url":"https://api.github.com/users/{user}/repos{?type,page,per_page,sort}","user_search_url":"https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"}'

**Comment by danyj** [comment]
now 

> Failed to access Github repository "ThemeFuse/Unyson-Update-Extension" releases. (Response code: 404)

**Comment by FreshspaceHQ** [comment]
Great, thanks for the update

Dan wrote on 27/06/2018 11:28:

**Comment by yura-x** [comment]
Same issue
[https://prnt.sc/jzx99j](https://prnt.sc/jzx99j)

**Comment by lmiftakhov** [comment]
Same issue.

**Comment by ViorelEremia** [comment]
It's solved. We've changed some things on our servers
