### ISSUE TITLE
error: Not Found on elements

### ISSUE THREAD

**Issue by 5or5i** [ThemeFuse/Unyson#3478]
Hi when i want to edit an Element, the popup says error Not Found
![helppp](https://user-images.githubusercontent.com/40644973/42000324-99f5b24e-7a60-11e8-80e1-95ce8b081e7c.PNG)
Please Help

**Comment by ViorelEremia** [comment]
Do you know how to check an ajax in browser console? if you know, check what ajax returns in response, enable wp-debug or install [this plugin](https://wordpress.org/plugins/query-monitor/), this is not a typical error if it is hard for you to inspect then:
Send me some temporary credentials admin: ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
