### ISSUE TITLE
Responsive column in Pagebuilder

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#348]
Hi!
I have problem with column shortcode in page builder.
I saw that it's base on grid 12 column of Bootstrap. So I can create layout 1 to 12 column with class fw-xs-{number}. 

So how about other devices? I want add class fw-md, fw-sm or even offset to adjust column for different screen sizes. I think it's very important. 

Thank you

**Comment by moldcraft** [comment]
You can overwrite [this array](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/96753224c62b192a7bbb70406c0cf836422a2117/config.php#L13) in `{theme}/framework-customizations/extensions/builder/config.php` and create any columns you want. Also you can overwrite [this file](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/96753224c62b192a7bbb70406c0cf836422a2117/static.php) in `{theme}/framework-customizations/extensions/builder/static.php` and include your own grid css.

**Comment by duongancol** [comment]
It worked for me.

One more question, how about if column or section shortcode have option like margin, padding?

**Comment by moldcraft** [comment]
> how about if column or section shortcode have option like margin, padding?

Try this solution https://github.com/ThemeFuse/Unyson/issues/275

**Comment by duongancol** [comment]
thank you!
