### ISSUE TITLE
How can I get mega menu settings data

### ISSUE THREAD

**Issue by shaonsina** [ThemeFuse/Unyson#3482]
I've made a mega menu with my custom markup.
Now I want to get mega menu settings data. Which options select the users from the settings popup box.
So how can I get??

**Comment by ViorelEremia** [comment]
Use ```get_post_meta($item_id, 'mega-menu', true)``` to get all meta of an item menu or you can use any function from the helper file ```framework/extensions/megamenu/helpers.php``` like ```fw_ext_mega_menu_get_meta``` for example if want to get the icon of an item:
```fw_ext_mega_menu_get_meta( $item_id, 'icon' )```

**Comment by shaonsina** [comment]
I can't get item's all meta with `get_post_meta($item->ID, 'mega-menu', true)`
Cause all data store in the database with this meta key `'fw:ext:mm:io:' . basename(get_template())`
If I use `get_post_meta($item->ID, 'fw:ext:mm:io:' . basename(get_template()), true)` then it returns all meta data.

**Comment by shaonsina** [comment]
I can't get item's all meta with `get_post_meta($item->ID, 'mega-menu', true)`
Cause all data store in the database with this meta key `'fw:ext:mm:io:' . basename(get_template())`
So, if I use `get_post_meta( $item->ID, 'fw:ext:mm:io:' . basename(get_template()), true )` then it returns all meta.
