### ISSUE TITLE
Theme customizer options are not loading due to javascript error

### ISSUE THREAD

**Issue by vinoddalvi** [ThemeFuse/Unyson#3484]
One of my client is getting below javscript error in the theme customizer causing theme options not to load. 

```
[Events] Exception raised. Please contact support in https://github.com/ThemeFuse/Unyson/issues/new. Don't forget to attach this stack trace to the issue.
fw-events.js?ver=2.7.18:156 ReferenceError: tinyMCEPreInit is not defined
```

![screenshot 5](https://user-images.githubusercontent.com/5412913/42121582-64f0181e-7c4f-11e8-9a25-e5e0e404a838.png)

**Comment by ViorelEremia** [comment]
I think the error comes from scripts.js the first line in your error that is loaded from option type wp-editor but I'm not sure of that
![42121582 64f0181e 7c4f 11e8 9a25 e5e0e404a838 png 1126x561](https://user-images.githubusercontent.com/28967378/42149509-0a033f30-7ddf-11e8-9ec6-5802516312c5.png)

**Comment by vinoddalvi** [comment]
It is an Unyson plugin file as shown in the below screenshot.

![screenshot 10](https://user-images.githubusercontent.com/5412913/42163496-6f4390e8-7e20-11e8-973b-13732f4ed1c1.png)

**Comment by ViorelEremia** [comment]
I teste wp-editor option type and is working for me. Did you try to disable all plugins? What theme do you use? Do your theme overwrite any option type? That is not happening to me I tested on our servers and on localhost installation.

**Comment by vinoddalvi** [comment]
> I teste wp-editor option type and is working for me. Did you try to disable all plugins?

Yes I tried disabling all plugins.

> What theme do you use?

I use this theme https://themeforest.net/item/jevelin-multipurpose-premium-responsive-wordpress-theme/14728833

> Do your theme overwrite any option type?

Not sure exactly.

**Comment by ViorelEremia** [comment]
Send me the theme: ```viorel@themefuse.com```

**Comment by vinoddalvi** [comment]
Sent but please note the issue only occurs on client's site and not on my site.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
