### ISSUE TITLE
Customiser not working 

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#3485]
Hi
Everything working except customizer not working properly.

I have check console found JS error

![sdfg](https://dha4w82d62smt.cloudfront.net/items/420a2i2F122H3Z2a2p3b/Screen%20Shot%202018-06-30%20at%205.12.22%20PM.png)

If you want to check I can send you login details

**Comment by ViorelEremia** [comment]
Why are these errors before the unyson error? Have you any cache? I think is something related to them.
Is your site on cloudflare.com try to clear the cache or to disable the option rocket load.

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
