### ISSUE TITLE
Images can not be loaded (Brizy)

### ISSUE THREAD

**Issue by i6tet** [ThemeFuse/Unyson#3486]
hi
I can not upload my images from the media library.
After selecting the image, only the preloader of the download is visible .. And nothing more happens, the image is not added.
What could be the problem?

**Comment by i6tet** [comment]
**UPD**
This is somehow connected with hosting.
On another hosting, everything works.

**Comment by ViorelEremia** [comment]
HI,
please open another issue here: https://github.com/ThemeFuse/Brizy/issues/new 
Here is only for unyson plugin, Brizy has another repository
