### ISSUE TITLE
Fatal error urgent 

### ISSUE THREAD

**Issue by suhashininithy** [ThemeFuse/Unyson#3488]
Falla al crear tabla tmp _fwbk_wp_woocommerce_api_keys. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`permissions` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL, `consumer_key` c' at line 5

Can you plz send the fix ? tooo urgent

**Comment by suhashininithy** [comment]
Hi., 
Please respond me ., it is too urgent

**Comment by danyj** [comment]
more details , where is the error?

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by suhashininithy** [comment]
Hi., 

Sorry , we can't provide login details. it is too confidential.

**Comment by ankitasarkar97** [comment]
Dear sir / mam, after installing successfully the theme. when i going to install demo content for the charity the "HOPE" layout i am getting this error "Failed to create tmp table _fwbk_wo_woocommerce_api_keys. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'permissions varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL, consumer_key c' at line 5"

![screen-17 48 57 03 07 2018](https://user-images.githubusercontent.com/40797342/42221904-568decc0-7ef1-11e8-84c7-32131f4087ed.png)
![screen-11 29 44 03 07 2018](https://user-images.githubusercontent.com/40797342/42221905-56c01682-7ef1-11e8-983f-5e3f37dd84c8.png)

**Comment by ViorelEremia** [comment]
ankitasarkar97 if it is urgent try with [version](https://github.com/ThemeFuse/Unyson-Backups-Extension/releases/tag/v2.0.28) to install demo conttent downlload it and replace all files in unyson/framework/extensions/backup
Please, follow this thread
Duplicate: https://github.com/ThemeFuse/Unyson/issues/3491#issuecomment-402224114

**Comment by ankitasarkar97** [comment]
ok sir let me check @ViorelEremia

**Comment by ankitasarkar97** [comment]
@ViorelEremia now its says "

The execution failed. Please check error.log
--

"

![Uploading screen-22.47.41[03.07.2018].png…]()

**Comment by ankitasarkar97** [comment]
@ViorelEremia please tell me what i do now

**Comment by suhashininithy** [comment]
Hi., 

We can't download this file Backups 2.0.30

What can i do now

**Comment by suhashininithy** [comment]
Hi., 

Many of my clients are complaining this issue , please i need solution ASAP!!

**Comment by ViorelEremia** [comment]
@suhashininithy send me your file database.json.txt

**Comment by suhashininithy** [comment]
Hi., 

Thank you , here we have attached my json file .
File Link : https://www.dropbox.com/s/ckvkggy7lt31hzv/database.json.txt?dl=0
Waiting for your reply. Plz reply ASAP!!!!!

**Comment by ViorelEremia** [comment]
@suhashininithy are you sure you have the latest version of the backup extension?

**Comment by ViorelEremia** [comment]
I tested your json for me it is working well

**Comment by suhashininithy** [comment]
Hi., 

Yes ,i have got your updated extension file , and it working fine. 

Thank you so much for your precious time. 

I had one more issue , when i have import demo via xampp it causes the maximum execution time exceeded issue . How can i fix this issue.

Once again thanks for your all help. Too impressive support!!!

**Comment by suhashininithy** [comment]
Hi., 

No need , all issues are fixed in your new extension , thanks a lot. 

Superb Job!!! Keep It UP!!

**Comment by suhashininithy** [comment]
Hi.,

When you have release this plugin update for backup extension ?

**Comment by ViorelEremia** [comment]
I want to fix another issue in this update: https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/379

**Comment by suhashininithy** [comment]
Hi., 

We have met many issues continuously , 

Issue 1 : We got this issue , Failed to create tmp table _fwbk_wp_duplicator_pro_entities. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`id`), KEY `type_idx` (`type`)) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET' at line 5

Issue 2 : After your update for backup extension we met , Failed to create tmp table _fwbk_wp_duplicator_pro_entities. Index column size too large. The maximum column size is 767 bytes.

Now we are facing https://snag.gy/plBIZq.jpg this issue ., 

Many of our clients are getting disappointed., Plz Help me,

**Comment by suhashininithy** [comment]
Hi., 

Anyone response my query ...

**Comment by ViorelEremia** [comment]
Hi, @suhashininithy for every new release I create an issue [here](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/380) that everyone can test the new release why didn't you test? why do I have to waste time for each of you?
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by suhashininithy** [comment]
Hi., 

We are always try to test your fixes , 2 days before also we have used your updated files and reported to you http://prntscr.com/k3m2pi , each day you have released new download how can i know that update ??? you mean each day i have to spend an hour to know about your updates ? i am not wasting your time . i am enquiring and reporting  **You peoples are having Very bad communication**

**Comment by danyj** [comment]
> every day i have to spend an hour to know about your updates

Yes you do if you want to keep your code up  to date

Signup for extension approval https://github.com/ThemeFuse/Unyson-Extensions-Approval

and before the update is out you will get an email what is coming so that you can test just like we all do. 

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues?q=is%3Aissue+is%3Aclosed

**Comment by ViorelEremia** [comment]
@suhashininithy can you send me your theme?

**Comment by suhashininithy** [comment]
Hi..,

This is suha., 

We have met this issue after updating the version 2.0.32 Failed to create tmp table _fwbk_wp_media_file_manager_log. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci ROW_FORMAT=DYNAMIC' at line 3

JSON File : https://www.dropbox.com/s/ckvkggy7lt31hzv/database.json.txt?dl=0

**Comment by suhashininithy** [comment]
Hi ., 

Sorry for the disturbance , it is quite urgent can anyone help me to resolve this issue

**Comment by ViorelEremia** [comment]
@suhashininithy I'll be available in an hour

**Comment by suhashininithy** [comment]
Hi., 

Yes ,thank you. 

Waiting for your reply.

**Comment by suhashininithy** [comment]
Hi., 

Any updates????

**Comment by ViorelEremia** [comment]
I'm working on it now

**Comment by ViorelEremia** [comment]
@suhashininithy try the last commit.

**Comment by suhashininithy** [comment]
Hi., 

Any one there ??

**Comment by ViorelEremia** [comment]
@suhashininithy what Any one there ?? didi you try the commit?

**Comment by suhashininithy** [comment]
Hi., 

Ohh!! Sry i have not refreshed the page ,, 

Thank you ,  i will try now!!!

**Comment by suhashininithy** [comment]
Hi., 

It does not working 

http://prntscr.com/k7ykdf
http://prntscr.com/k7ykmq

**Comment by ViorelEremia** [comment]
are you sure you uploaded the file to the server?

**Comment by suhashininithy** [comment]
Hi., 

s i am working on right path

**Comment by suhashininithy** [comment]
Hi..,,,

It is working now ., 

Thanks a lot dude ., 

Excellent!! Thank you

**Comment by suhashininithy** [comment]
Hi., 

We noticed ydy you have released updated version of unyson , but now we can't take create content backup now , it exist the process on database export , what to do ? http://prntscr.com/k8wbd5

**Comment by ViorelEremia** [comment]
@suhashininithy What error have you? We tested it and it is working for us

**Comment by suhashininithy** [comment]
Hi., 

There is no issue , Thank you

**Comment by suhashininithy** [comment]
Hi., 

We met this issue  Failed to create tmp table _fwbk_wp_commentmeta. Unknown storage engine 'InnoDB'

**Comment by rajugani** [comment]
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci ROW_FORMAT=DYNAMIC 
![image](https://user-images.githubusercontent.com/44260126/47147163-41ed0500-d2eb-11e8-93a4-7f14c88deffa.png)
![image](https://user-images.githubusercontent.com/44260126/47147178-4addd680-d2eb-11e8-802a-bb76cc3c0d37.png)

**Comment by rajugani** [comment]
plz help me out of this problem

**Comment by rajugani** [comment]
@ViorelEremia

**Comment by rajugani** [comment]
@suhashininithy

**Comment by rajugani** [comment]
anybody there?
its urgent
