### ISSUE TITLE
ufter Unyson builder fresh the page not loading

### ISSUE THREAD

**Issue by Kelta74** [ThemeFuse/Unyson#3489]
Helo,

I have updated Unison, since the contents of the pages have not been uploaded, and I can not make pages in the admin.

4.9.6 version | Unyson 2.7.18

https://oldlakeman3athlon.hu/

Please help me!

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by Kelta74** [comment]
Helo, 

I sent the requested information, thank you very much for your help!
Subject of the letter: https://oldlakeman3athlon.hu

Best regards, 
Tamás

**Comment by Kelta74** [comment]
Helo, thank you very much!

But the site css is not oke now:
https://oldlakeman3athlon.hu/

attached screen
![kep_3](https://user-images.githubusercontent.com/40794258/42266556-0b45970a-7f77-11e8-929b-dec3d8f0cd1e.jpg)
