### ISSUE TITLE
Unyson - Fatal Error

### ISSUE THREAD

**Issue by MVBravo** [ThemeFuse/Unyson#3490]
Fatal error: Call to undefined method FW_Shortcode_Section::get_shortcode_config() in /home4/bhostels/public_html/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php on line 20

	private function get_shortcode_config()
	{
		return fw_ext(
			'shortcodes'
		)->get_shortcode('section')->get_shortcode_config();

(Last line #20)

**Comment by edd677** [comment]
Same here.

**Comment by edd677** [comment]
@MVBravo did you find a fix for this or receive support?

**Comment by edd677** [comment]
I know that this started after I updated my extensions, just 1 hour ago. I get this fatal error when trying to edit a page.

**Comment by camilapnhr** [comment]
Same here

**Comment by camilapnhr** [comment]
Same here @edd677, all this after update the extensions.

**Comment by edd677** [comment]
I swapped the extensions folder in /home/-site-name/public_html/wp-content/plugins/unyson/framework/extensions/ with the one from our backup, and it fixed it. Must be a pretty nasty bug with the new update. We'll watch this space I guess!

**Comment by ViorelEremia** [comment]
I'm checking now

**Comment by camilapnhr** [comment]
@edd677 Can you please send me the unyson file from backup you got? can't find mine's

**Comment by edd677** [comment]
[extensions.zip](https://github.com/ThemeFuse/Unyson/files/2160138/extensions.zip)

Please note: if this isn't urgent, you're possibly better off waiting for @ViorelEremia to update the extension on WordPress with the bug fix, and then updating it again from WordPress.

**Comment by ViorelEremia** [comment]
I think I fixed the issues I tested on some sites. Now Im waiting for our servers to remove extensions cache I have no access to them so they usually in a half an hour renew their cache after that you will be able to update the extensions.

**Comment by ViorelEremia** [comment]
Can someone update the extensions? The cache is removed.
https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456

**Comment by MVBravo** [comment]
Problem Solved after updating the last version. Thank you all!

**Comment by edd677** [comment]
@ViorelEremia 

I just tried updating in WP and got:

`Downloading the Backup & Demo Content extension...

Installing the Backup & Demo Content extension...

The Backup & Demo Content extension has been successfully updated.

Downloading the Shortcodes extension...

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (Response code: 404)`

**Comment by camilapnhr** [comment]
@edd677 I got this same error twice, then i just deleted the plugin and installed again so it worked

**Comment by TechInRed** [comment]
I just swapped the extension folder /home/-site-name/public_html/wp-content/plugins/unyson/framework/extensions/ with the extensions.zip provided by @edbeecroft but I still could not activate the plugin. What should i do next guy?
@ViorelEremia Help please.

Thank you for quick and immediate attention!
