### ISSUE TITLE
 when trying to install demo content getting error

### ISSUE THREAD

**Issue by ankitasarkar97** [ThemeFuse/Unyson#3491]
Dear sir / mam, after installing successfully the theme. when i going to install demo content for the charity the "HOPE" layout i am getting this error "Failed to create tmp table _fwbk_wo_woocommerce_api_keys. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`permissions` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL, `consumer_key` c' at line 5"

Please help me as quick as possible.

Thanks, 
Ankita Sarkar
![screen-17 48 57 03 07 2018](https://user-images.githubusercontent.com/40797342/42221857-2f111924-7ef1-11e8-9f3f-271a3ab61492.png)
![screen-11 29 44 03 07 2018](https://user-images.githubusercontent.com/40797342/42221858-2f457f48-7ef1-11e8-8950-b959949f5cbd.png)

**Comment by eduplessis** [comment]
I've got the kind of the same error


`Failed to create tmp table _fwbk_wp_pmxi_posts. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`product_key` text COLLATE utf8mb4_general_ci `iteration` bigint(20) NOT NULL D' at line 6Failed to create tmp table _fwbk_wp_pmxi_posts. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`product_key` text COLLATE utf8mb4_general_ci `iteration` bigint(20) NOT NULL D' at line 6`

![image](https://user-images.githubusercontent.com/398245/42232997-2cdc8bbc-7ebe-11e8-8ee3-77987208705b.png)

**Comment by ViorelEremia** [comment]
Tomorrow it will be fixed(in ten hours)

**Comment by eduplessis** [comment]
Thanks

**Comment by ankitasarkar97** [comment]
thanks sir.

**Comment by ViorelEremia** [comment]
I tested on some servers everything is fine.
can someone test it?
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/379

**Comment by jorgeherrera9103** [comment]
I'll try  it, thanks.

**Comment by danyj** [comment]
testing now

**Comment by danyj** [comment]
works for me

**Comment by eduplessis** [comment]
get some errors

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/379#issuecomment-402485954

**Comment by jorgeherrera9103** [comment]
I found another one when I try to install the demo content:
- - - - - - -
![100bytes](https://user-images.githubusercontent.com/19397980/42292947-eb71db8a-7f9b-11e8-89af-4a684e053982.PNG)
- - - - - - -
Thanks a lot.

**Comment by ViorelEremia** [comment]
@jorgeherrera9103 is your backup version 2.0.30?

**Comment by jorgeherrera9103** [comment]
Hi, no I'll trying to install the demo content.

**Comment by ViorelEremia** [comment]
@jorgeherrera9103 you can try the next release should fix the issue: https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/380

**Comment by eduplessis** [comment]
@ViorelEremia I've change the version of the demo file to 2.0.31 and I got the error message

'Failed to create tmp table _fwbk_wp_wc_download_log. Can't create table 'local._fwbk_wp_wc_download_log' (errno: 150)'

**Comment by ViorelEremia** [comment]
@eduplessis 
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ViorelEremia** [comment]
@eduplessis can you test this commit: https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/9fc1a538513ecc8c01e228c82debd1e8a4647fc6

**Comment by rafiul** [comment]
Hi, I have got this error:

"Failed to create tmp table _fwbk_wp_wc_download_log. Access denied; you need (at least one of) the SUPER privilege(s) for this operation"

WP Version 4.9.7 | Unyson 2.7.18

**Comment by ViorelEremia** [comment]
@rafiul can you remove these two lines and try again to import?
https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/9fc1a538513ecc8c01e228c82debd1e8a4647fc6
Let me know if it solves the issue.

**Comment by ViorelEremia** [comment]
@rafiul try:
 
1. Revert: https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/9fc1a538513ecc8c01e228c82debd1e8a4647fc6
2. Remove ```GLOBAL``` keyword from the first query: ```$wpdb->query( 'SET FOREIGN_KEY_CHECKS=0' );```
3. Remove the whole third line: ```$wpdb->query( 'SET GLOBAL FOREIGN_KEY_CHECKS=1' );```

If it is not working you must wait until tomorrow.

**Comment by rafiul** [comment]
yah! It's  Working 👍 

Thanks

**Comment by eduplessis** [comment]
@ViorelEremia the last commit fixed all https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/48ee86afdb8dd837944f30b31889af9cc2958ebd

Thanks

**Comment by Jaydeep-Trivedi** [comment]
I have checked and verified that the above fix is present in the code. Even then, I am facing this issue.

`Failed to create tmp table _fwbk_wp_2_wc_download_log. Cannot add foreign key constraint`

Could you please let me know what else can be done about this?

**Comment by rockstarhiten** [comment]
Getting this error while installing demo content :

Failed to drop tmp table _fwbk_wp_xyztable_brizy_logs. DROP command denied to user 'xyztablename'@'localhost' for table '_fwbk_wp_xystable_brizy_logs'

Theme: Baxton

Please Help

**Comment by xeonz168** [comment]
> Tomorrow it will be fixed(in ten hours)

Can you help me with this : Failed to create tmp table _fwbk_wp9c_wc_download_log. Can't create table `sean8622_wp806`.`_fwbk_wp9c_wc_download_log` (errno: 121 "Duplicate key on write or update")

**Comment by super-frankie-lamps** [comment]
Getting this error while installing demo content: `Failed to create tmp table _fwbk_wp_wc_download_log. Duplicate foreign key constraint name 'fk_wp_wc_download_log_permission_id'`

**Comment by radicitushaereticus** [comment]
I'm getting this error: 
Failed to create tmp table _fwbk_wp_wc_download_log. Duplicate foreign key constraint name 'fk_wp_wc_download_log_permission_id'

what can I do to fix it ?

**Comment by Hykeos** [comment]
I have the same problem. Error: "Failed to create tmp table _fwbk_wp_wc_download_log. Duplicate foreign key constraint name 'fk_wp_wc_download_log_permission_id'". What is the solution?

**Comment by yura-x** [comment]
@xeonz168 , @super-frankie-lamps , @radicitushaereticus 

> I have the same problem. Error: "Failed to create tmp table _fwbk_wp_wc_download_log. Duplicate foreign key constraint name 'fk_wp_wc_download_log_permission_id'". What is the solution?

It seems that this error appears when backup was created on the old version on WooCommerce and you restore it on the new version:

```wp-content/plugins/woocommerce/includes/wc-update-functions.php``` line 1918

I have fixed this by adding an additional check here on line 761:
```wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php```

Try to replace this code:
```
foreach ( $line['data']['indexes'] as $index ) {
	if ( ! strpos($index,'fk_wp_wc_download_log_permission_id')){
		$cols_sql[] = $index;
	}
}
```
To this one:

```
foreach ( $line['data']['indexes'] as $index ) {
	if ( ! strpos($index,'fk_wp_wc_download_log_permission_id')){
		$cols_sql[] = $index;
	}
}
```

This worked for me

**Comment by weexdigital** [comment]
can any one hellp me and get me any Video explanation for this problem really im stopping for this steep :(

**Comment by kukoman** [comment]
> @xeonz168 , @super-frankie-lamps , @radicitushaereticus
> 
> > I have the same problem. Error: "Failed to create tmp table _fwbk_wp_wc_download_log. Duplicate foreign key constraint name 'fk_wp_wc_download_log_permission_id'". What is the solution?
> 
> It seems that this error appears when backup was created on the old version on WooCommerce and you restore it on the new version:
> 
> `wp-content/plugins/woocommerce/includes/wc-update-functions.php` line 1918
> 
> I have fixed this by adding an additional check here on line 761:
> `wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php`
> 
> Try to replace this code:
> 
> ```
> foreach ( $line['data']['indexes'] as $index ) {
> 	$cols_sql[] = $index;
> }
> ```
> 
> To this one:
> 
> ```
> foreach ( $line['data']['indexes'] as $index ) {
> 	if ( ! strpos($index,'fk_wp_wc_download_log_permission_id')){
> 		$cols_sql[] = $index;
> 	}
> }
> ```
> 
> This worked for me

worked for me... thank you!!!

**Comment by oussjarrousse** [comment]
I am seeing the same error as well... I will try the fix suggested by @xeonz168 and let you know

**Comment by oussjarrousse** [comment]
The fix worked for me !

> @xeonz168 , @super-frankie-lamps , @radicitushaereticus
> 
> > I have the same problem. Error: "Failed to create tmp table _fwbk_wp_wc_download_log. Duplicate foreign key constraint name 'fk_wp_wc_download_log_permission_id'". What is the solution?
> 
> It seems that this error appears when backup was created on the old version on WooCommerce and you restore it on the new version:
> 
> `wp-content/plugins/woocommerce/includes/wc-update-functions.php` line 1918
> 
> I have fixed this by adding an additional check here on line 761:
> `wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php`
> 
> Try to replace this code:
> 
> ```
> foreach ( $line['data']['indexes'] as $index ) {
> 	$cols_sql[] = $index;
> }
> ```
> 
> To this one:
> 
> ```
> foreach ( $line['data']['indexes'] as $index ) {
> 	if ( ! strpos($index,'fk_wp_wc_download_log_permission_id')){
> 		$cols_sql[] = $index;
> 	}
> }
> ```
>
> This worked for me

**Comment by yura-x** [comment]
I guess that there is a better solution.
It seems that in the newer version of MySQL query results returned  as uppercase values.

So in the file
`wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php`

below line 1213 which contains this code:
```
if ( false !== array_search( $foreign['referenced_table_name'], $drop_sql ) ) {
	$wpdb->query( "ALTER TABLE {$foreign['table_name']} DROP FOREIGN KEY {$foreign['constraint_name']}" );
}
```

you should also add a UPPERCASE version:
```
if ( false !== array_search( $foreign['REFERENCED_TABLE_NAME'], $drop_sql ) ) {
	$wpdb->query( "ALTER TABLE {$foreign['TABLE_NAME']} DROP FOREIGN KEY {$foreign['CONSTRAINT_NAME']}" );
}
```
here is a full result with a foreach wrapper:

```
foreach ( $foreigns as $foreign ) {
	if ( false !== array_search( $foreign['referenced_table_name'], $drop_sql ) ) {
		$wpdb->query( "ALTER TABLE {$foreign['table_name']} DROP FOREIGN KEY {$foreign['constraint_name']}" );
	}
	if ( false !== array_search( $foreign['REFERENCED_TABLE_NAME'], $drop_sql ) ) {
		$wpdb->query( "ALTER TABLE {$foreign['TABLE_NAME']} DROP FOREIGN KEY {$foreign['CONSTRAINT_NAME']}" );
	}
}
```

**Comment by hjtempelaar** [comment]
I have fixed this by adding an additional check here on line 761: wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php

Try to replace this code:

`foreach ( $line['data']['indexes'] as $index ) {
	$cols_sql[] = $index;
}`

To this one:

`foreach ( $line['data']['indexes'] as $index ) {
	if ( ! strpos($index,'fk_wp_wc_download_log_permission_id')){
		$cols_sql[] = $index;
	}
}`

**Comment by jiminoc** [comment]
This was the only thing that seemed to work for me: 

Create a temporary mysql user:

```
CREATE USER tmpuser@localhost IDENTIFIED BY 'foobar!!';
GRANT ALL ON *.* TO tmpuser@localhost;
FLUSH PRIVILEGES;
```

now replace your current db user name in wp-config.php with this new username;

after the install is complete you can delete the temp user and go back to  your previous db user name

**Comment by depawlur** [comment]
> I have fixed this by adding an additional check here on line 761: wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php
> 
> Try to replace this code:
> 
> `foreach ( $line['data']['indexes'] as $index ) { $cols_sql[] = $index; }`
> 
> To this one:
> 
> `foreach ( $line['data']['indexes'] as $index ) { if ( ! strpos($index,'fk_wp_wc_download_log_permission_id')){ $cols_sql[] = $index; } }`

Whoever is managing this Unyson, can you please fix  ^^^^^

it's been 3 years this post's been going on and I literally had to google and edit plugin's code to get this going... 

thanks
