### ISSUE TITLE
Unyson - Fatal Error

### ISSUE THREAD

**Issue by edd677** [ThemeFuse/Unyson#3492]
I just updated my extensions and 1) every page on my site is blank, and 2) I can't get into the edit page screen.

Here is the error:

`Fatal error: Uncaught Error: Call to undefined method FW_Shortcode_Section::get_shortcode_config() in /home/getmagni/public_html/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php:20 Stack trace: #0 /home/getmagni/public_html/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php(54): Page_Builder_Section_Item->get_shortcode_config() #1 /home/getmagni/public_html/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/includes/item-types/class-page-builder-item.php(14): Page_Builder_Section_Item->get_thumbnails_data() #2 /home/getmagni/public_html/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/extends/class-fw-option-type-builder.php(577): Page_Builder_Item->get_thumbnails() #3 /home/getmagni/public_html/wp-content/plugins/unyson/framework/extensions/ in /home/getmagni/public_html/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php on line 20`

It would be great if you could please help asap, this is a pretty bad one!

**Comment by ViorelEremia** [comment]
Please follow this thread: https://github.com/ThemeFuse/Unyson/issues/3492

**Comment by ViorelEremia** [comment]
sorry this thread: https://github.com/ThemeFuse/Unyson/issues/3490
