### ISSUE TITLE
Last update on unyson or backup extension causes issue with demo content install.

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#3493]
Last night our 3 clients face the same issue.. they cant import content due to this error.

![issue](https://cl.ly/3I2H2V2Z460i/Screen%20Shot%202018-07-04%20at%2011.59.56%20AM.png)

But When I use an old version of unyson. Its work fine. And I have installed the content with old version.

**Comment by ViorelEremia** [comment]
Can you try to update you mysql version? I know about it but until I haven't a fix for it.

**Comment by Ataurr** [comment]
I have faced the issue in 3 sites today.. And I have installed the demo content with old version of "unyson" 2.7.17 and "Backup & Demo Content" 2.0.28

So I believe you did something wrong in last Backup extension update.

Others users also faced the same issue in future. It's really hard to tell them every user update the Mysql version for this. Where its work with the old version. You should fix this buddy.

**Comment by Ataurr** [comment]
Found  another one 
![sdf](https://cl.ly/402i0H2t3W42/Screen%20Shot%202018-07-04%20at%202.45.08%20PM.png)

**Comment by ViorelEremia** [comment]
I'm working on this now

**Comment by ViorelEremia** [comment]
I tested on some servers everything is fine.
can someone test it?
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/379

**Comment by Ataurr** [comment]
This issue still not fixed.
I have updated all extension and trying to install demo content again. But Still same issue

If you need I can send you the login details via mail.

Thanks

**Comment by ViorelEremia** [comment]
@Ataurr send me your file ```database.json.txt```

**Comment by Ataurr** [comment]
@ViorelEremia  here you are https://www.dropbox.com/s/u9c2yhkv8pq4ajd/database.json.txt?dl=0

**Comment by ViorelEremia** [comment]
@Ataurr 
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by ankit97733** [comment]
any update on this ?

**Comment by Ataurr** [comment]
@ankit97733 This issue already resolved.
If you still faced the same issue please update your extension.
