### ISSUE TITLE
Fail to import theme demo data

### ISSUE THREAD

**Issue by docrechard** [ThemeFuse/Unyson#3498]
I tried several times to import demo data in my website but each time it shows an error message.
Here is the screenshot: http://prntscr.com/k4scmu
Can anyone from the support help me to fix the issue?

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/381

**Comment by ViorelEremia** [comment]
@docrechard did the next version of backup solve your issue?
