### ISSUE TITLE
Calendar not working

### ISSUE THREAD

**Issue by mileticslobo** [ThemeFuse/Unyson#3499]
The calendar stopped working after the last update
http://ausmontecatone.org/

**Comment by mileticslobo** [comment]
Ok, 
i did...

**Comment by ViorelEremia** [comment]
And is everything all right?

**Comment by mileticslobo** [comment]
No, as you can see, the event calendar not working.
on the home page and here http://ausmontecatone.org/attivita/eventi/
There is no numbers...

**Comment by ViorelEremia** [comment]
It's a theme issue, please contact the [theme author](https://support.themefuse.com/hc/en-us/requests/new).
Here is only for unyson
