### ISSUE TITLE
 Image Sizes Restore: The execution failed. Please check error.log

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3504]
On backup restore 

`PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 17179869283 bytes) in T:\wamp64\www\Development\Brizy\wp-includes\functions.php on line 5231`

http://prntscr.com/k68ner

WP memory limit is at default 40 MB

**Comment by danyj** [comment]
tried with 

`define( 'WP_MEMORY_LIMIT', '128M' );`

same thing

**Comment by ViorelEremia** [comment]
try up to 256

**Comment by danyj** [comment]
I will but we are talking about same demos we were testing for couple weeks now and they did not need more memory before

**Comment by danyj** [comment]
same thing, 

474 images 
stops at 96

**Comment by ViorelEremia** [comment]
Maybe you changed something in your code or you have a big image. The code of the image resize I never changed

**Comment by danyj** [comment]
Size of demo is same 
try it yourself please, backup Creatus demo and do restore

**Comment by ViorelEremia** [comment]
I tested on 3 servers two online and localhost it's working
one of them has memory limit is 96M
Steps: install demo data creatus(main demo), backup content, restore

**Comment by danyj** [comment]
ok , thnx
