### ISSUE TITLE
How to refresh inline CSS in customizer?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3505]
@ivandotv  @ViorelEremia  

This customizer example http://manual.unyson.io/en/latest/options/customizer.html#content
shows hot to change inline text, 

does anyone know how to refresh the inline CSS instead?

**Comment by ViorelEremia** [comment]
What inline css

**Comment by danyj** [comment]
any,  just need to reload it

**Comment by ViorelEremia** [comment]
it is not still clear to me give me an example

**Comment by ivandotv** [comment]
I'm not sure what you are trying to do.
Are you try change some options and then change theme css immediately?
