### ISSUE TITLE
Can't edit Table Contents

### ISSUE THREAD

**Issue by lineacurva** [ThemeFuse/Unyson#3506]
I can't edit table contents anymore with Page Builder Editor.

As long as I click "edit" on a table element, I can only add rows and columns, but edit the content (or add content to new row/column) is not possible.

My extensions are up to date (even if my Events extension is slightly customised in order to display some custom contents, but also keeping the native version the problem is there!).

The editor seems to work smoothly with other functions.

I saw in an old issue something like that has been solved "restarting the laptop", I tried a reboot also, but it didn't quite work.

Any idea?

**Comment by ViorelEremia** [comment]
Have you some errors in the browser console? 
Did you try to disable all plugins?
Did you try to switch the theme to one wp default?
What browser do you use?
Do you have any cache browser/server/wpPlugin? remove it
