### ISSUE TITLE
Contact form shortcode not submitting in wordpress

### ISSUE THREAD

**Issue by RodrigoAMercadoElgueta** [ThemeFuse/Unyson#3508]
Hello
Have a wordpress with the Moto theme v3 which includes Unyson Shortcodes.
It is a single page site (page Servicio aquacero) with the Contact Form shortcode, to submit to an already created email within the same domain.
After submitting, it returns "Method not valid" in red letters in spanish over the header banner.
No message is received in the email account.

http://aquacero.cl/wp-login.php
account:     admin
password:   =be#M4QcTe

**Comment by ViorelEremia** [comment]
Hi, I checked your mail form and I can't see too much from admin but I suppose your mail server is not configured try to check in your cpanel maybe there are some settings for it.
And please change your password everyone have now your credentials from your site.

**Comment by ViorelEremia** [comment]
Did you find the issue?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.

**Comment by RodrigoAMercadoElgueta** [comment]
Asking to hosting support, they deactivated the function mail( ) from PHP, for security reasons (but they did not informed that). That was stopping the mail delivery.
So the solution was to set WP Mail SMTP plugin for Wordpress with the SMTP configuration given by support.

**Comment by ViorelEremia** [comment]
Thank you.
