### ISSUE TITLE
Text block in PageBuilder

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#351]
Hi!
when i added content in text block like this:
<pre>
abcd
defg
abce
</pre>
I saved and reopened text block the content show like this:
<pre>
abcd

defg

abce
</pre>
So how can I prevent text block add space between each line?
Thanks

**Comment by levan1993** [comment]
it's because wordpess applies auto "p" tag to this textarea... to turn it off try to add 'wpautop' => false to textblock option array

**Comment by duongancol** [comment]
Thank @levan1993 , it worked for me.
