### ISSUE TITLE
Demo content install issue. 

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#3510]
Demo Content not installed in our site. 

After this nothing working 

![sdf](https://cl.ly/0u3s1O1W3m45/Screen%20Shot%202018-07-17%20at%204.50.31%20PM.png)

XHR request

![](https://cl.ly/3E2e1g1N151C/Screen%20Shot%202018-07-17%20at%204.51.46%20PM.png)

**Comment by ViorelEremia** [comment]
What is after this is running infinitely or what?

**Comment by Ataurr** [comment]
It's running infinitely

**Comment by danyj** [comment]
I had this also yesterday , reloaded the install few times untill it  proceeded , mine was stuck on ziping

**Comment by shaonsina** [comment]
Demo content not working.
![screenshot_6](https://user-images.githubusercontent.com/20015610/42835962-d9e4bfa6-8a1b-11e8-97d6-83aa569dd85c.png)

**Comment by ViorelEremia** [comment]
@Ataurr have any results?

**Comment by Ataurr** [comment]
@ViorelEremia  I have told him to use different server
