### ISSUE TITLE
Sidebar on translation

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#3511]
I have a multilanguage site where I use the Sidebars extension.

I've set a sidebar with content for a specific page (that has a translation).

When I look at the original page, I see the right sidebar.
But when I look at the translation, I see the wrong sidebar.

I've inspected this with wp_get_sidebars_widgets(). And I see that the sidebar 'sidebar-1' on the original page is filled with the right widgets. But when I look at the translation, I see the wrong widgets.

Is there a solution for this? It seems to me this is a bug in the Sidebars extension.

Hopefully someone can help me out, thanks in advance!
-Kevin

**Comment by ViorelEremia** [comment]
What plugin do you use for translations? I have to know it to implement the issue on my part

**Comment by noesteijver** [comment]
I use WPML for translations.

**Comment by ViorelEremia** [comment]
I have tested it now but mine is working well.
How did you set the sidebar for the pages? 
I see in the "Manage Sidebars" I must choose the sidebar for each page translated and original page.

**Comment by noesteijver** [comment]
I've tested this, that works! Thanks for the instruction.
