### ISSUE TITLE
page-builder says not installed while it is installed

### ISSUE THREAD

**Issue by GertjanBrouwer** [ThemeFuse/Unyson#3512]
Hi,

I coppied my whole wordpress folder to a ubuntu LAMP-stack and got it all up and runnning. Now when I log into the back-end it says I have to install page-builder. But locally (same code) it says I have page builder installed already? 

Where in the code does this check happen so I can check out where the problem is?

Or am I just forgetting something after I moved my site?

**Comment by ViorelEremia** [comment]
Check the class ```framework/core/components/extensions.php``` and ```framework/core/components/extensions/manager/class--fw-extensions-manager.php``` 
But I think you can remove them and install again.
Check these db options: ```get_option( 'fw_extensions_activation' )``` or ```get_option( 'fw_active_extensions' )```
