### ISSUE TITLE
Heading H3 on title blog

### ISSUE THREAD

**Issue by mltcorp** [ThemeFuse/Unyson#3516]
Hi,
I need to know how change to h1 my blog
 title, because default is h3 and it is very bad to SEO because my articles does't have h1 tag.
<img width="1230" alt="screen shot 2018-07-20 at 11 10 09" src="https://user-images.githubusercontent.com/20816799/43007017-873e56b0-8c0d-11e8-9dd3-f1349bb2fc01.png">

**Comment by ViorelEremia** [comment]
We don't know how you can change this title. If your theme doesn't provide an option for it then you must change some files through ftp manager depending it depends on which url you are for example if you are on the author archive you must change the file author.php or if you are in the single page you must change the page.php from your theme root.
The best way I recommend you is to contact the author of your theme.
