### ISSUE TITLE
URGENT - Setting admin menu not showing in multisite 

### ISSUE THREAD

**Issue by Niloys7** [ThemeFuse/Unyson#3518]
Hi,
i use this resource below for making a plugin option by using unyson framework.
http://manual.unyson.io/en/latest/helpers/settings-form.html

Everything is working fine if I run this code in single site but when I active this plugin into multisite the admin_menu is not showing.
also, it's not only about the menu, I think FW_Settings_Form is not triggered in multisite.

Single site dashboard screesnhort: http://prntscr.com/k94tge
Multisite dashboard screenshots:
1. http://prntscr.com/k94tzv (Network Active)
2. http://prntscr.com/k94u6q (No Admin menu)

Thanks,
Niloy

**Comment by NiloySarker** [comment]
@danyj can you help me with this?

**Comment by danyj** [comment]
> can you help me with this?

sorry but , slammed, 

did you also make sure that on particular site plugin is active 

on my end network active activates the plugin but I can deactivate on 
site basis also

**Comment by ViorelEremia** [comment]
@NiloySarker then you copy some docs read the code what you copied. The example from the docs it is for theme and for a single installation wordpress or a site in a multisite. But to add a submenu page in admin network you must use the hoook ```network_admin_menu``` not ```admin_menu``` see the function ```_init``` in your copied class.
Try my class below I tested it is working: 
```
<?php if (!defined('FW')) die('Forbidden');

class FW_Settings_Form_Test extends FW_Settings_Form {
	public function get_values() {
		return get_option('test_fw_settings_form', array());
	}

	public function set_values($values) {
		update_option('test_fw_settings_form', $values, false);
	}

	public function get_options() {
		return array(
			'tab1' => array(
				'type' => 'tab',
				'title' => 'Tab #1',
				'options' => array(
					'opt1' => array(
						'type' => 'text',
						'label' => 'Option #1'
					),
					'opt2' => array(
						'type' => 'textarea',
						'label' => 'Option #2'
					),
				),
			),
			'tab2' => array(
				'type' => 'tab',
				'title' => 'Tab #2',
				'options' => array(
					'tab2_1' => array(
						'type' => 'tab',
						'title' => 'Sub Tab #1',
						'options' => array(
							'opt2_1' => array(
								'type' => 'text',
								'label' => 'Sub Option #1'
							),
						),
					),
					'tab2_2' => array(
						'type' => 'tab',
						'title' => 'Sub Tab #2',
						'options' => array(
							'opt2_2' => array(
								'type' => 'textarea',
								'label' => 'Sub Option #2'
							),
						),
					),
				),
			),
		);
	}

	protected function _init() {
		add_action('network_admin_menu', array($this, '_action_admin_menu'));
		add_action('admin_enqueue_scripts', array($this, '_action_admin_enqueue_scripts'));

		$this->set_is_side_tabs(true);
		$this->set_is_ajax_submit(true);
	}

	/**
	 * @internal
	 */
	public function _action_admin_menu() {
		add_menu_page(
			'Test FW Settings Form',
			'Test FW Settings Form',
			'manage_options',
			/** used in @see _action_admin_enqueue_scripts() */
			'test-fw-settings-form',
			array($this, 'render')
		);
	}

	/**
	 * @internal
	 */
	public function _action_admin_enqueue_scripts() {
		$this->enqueue_static();
	}
}
```

**Comment by Niloys7** [comment]
Hi @ViorelEremia ,
Thanks for your reply. but _network_admin_menu_
i not working in my iste

**Comment by ViorelEremia** [comment]
How is not working? did you try the class above? If you want to show on the entire network I mean for every site in the multisite and for the network dashboard you must add two hooks one for network admin and one for singe site in the multisite: 
```
protected function _init() {
		add_action('network_admin_menu', array($this, '_action_admin_menu'));
		add_action('admin_menu', array($this, '_action_admin_menu'));
		add_action('admin_enqueue_scripts', array($this, '_action_admin_enqueue_scripts'));

		$this->set_is_side_tabs(true);
		$this->set_is_ajax_submit(true);
	}
```
And you must enable the plugin for the entire network

**Comment by Niloys7** [comment]
i use the same class above.
if you don't mind, Please send me your email address.
i will send you the login details. so you can check.

**Comment by Niloys7** [comment]
yes.
>
    class FW_Settings_Form_Test extends FW_Settings_Form {
        public function get_values() {
            return get_option('test_fw_settings_form', array());
        }

        public function set_values($values) {
            update_option('test_fw_settings_form', $values, false);
        }

        public function get_options() {
            return array(
                'tab1' => array(
                    'type'    => 'tab',
                    'title'   => 'Tab #1',
                    'options' => array(
                        'opt1' => array(
                            'type'  => 'text',
                            'label' => 'Option #1',
                        ),
                        'opt2' => array(
                            'type'  => 'textarea',
                            'label' => 'Option #2',
                        ),
                    ),
                ),
                'tab2' => array(
                    'type'    => 'tab',
                    'title'   => 'Tab #2',
                    'options' => array(
                        'tab2_1' => array(
                            'type'    => 'tab',
                            'title'   => 'Sub Tab #1',
                            'options' => array(
                                'opt2_1' => array(
                                    'type'  => 'text',
                                    'label' => 'Sub Option #1',
                                ),
                            ),
                        ),
                        'tab2_2' => array(
                            'type'    => 'tab',
                            'title'   => 'Sub Tab #2',
                            'options' => array(
                                'opt2_2' => array(
                                    'type'  => 'textarea',
                                    'label' => 'Sub Option #2',
                                ),
                            ),
                        ),
                    ),
                ),
            );
        }

        protected function _init() {
            add_action('network_admin_menu', array($this, '_action_admin_menu'));
            add_action('admin_menu', array($this, '_action_admin_menu'));
            add_action('admin_enqueue_scripts', array($this, '_action_admin_enqueue_scripts'));

            $this->set_is_side_tabs(true);
            $this->set_is_ajax_submit(true);
        }

        /**
         * @internal
         */
        public function _action_admin_menu() {
            add_menu_page(
                'Test FW Settings Form',
                'Test FW Settings Form',
                'manage_options',
                /** used in @see _action_admin_enqueue_scripts() */
                'test-fw-settings-form',
                array($this, 'render')
            );
        }

        /**
         * @internal
         */
        public function _action_admin_enqueue_scripts() {
            $this->enqueue_static();
        }
    }

**Comment by ViorelEremia** [comment]
Send

**Comment by Niloys7** [comment]
Hi @ViorelEremia ,
I forgot to comment. the issue is solved.
somehow the code is working now :)
Thanks
