### ISSUE TITLE
License usage and themeforest

### ISSUE THREAD

**Issue by Bilyachenko** [ThemeFuse/Unyson#3519]
Can I use Unyson for build wordpress theme and sell it on themeforest?

**Comment by danyj** [comment]
U mean like this https://themeforest.net/item/creatus-ultimate-multipurpose-wordpress-theme/22280821  :)

**Comment by danyj** [comment]
Go crazy!

**Comment by Bilyachenko** [comment]
danyj

yes 
exactly this

**Comment by ViorelEremia** [comment]
@Bilyachenko there are many unyson themes on themeforest: 
https://themeforest.net/item/jevelin-multipurpose-premium-responsive-wordpress-theme/14728833
https://themeforest.net/item/woffice-intranetextranet-wordpress-theme/11671924
