### ISSUE TITLE
Selecting only one post instead of multipost

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#352]
Hi 
I am thinking to select only one post/page instead of multi-post/page. Here code that does select multi post. Is there any filter/option to select only one post?
<pre><code>
	'demo_multi_select_posts_2' => array(
				'type' => 'multi-select',
				'label' => __('Multi-Select: Posts', 'fw'),
				'population' => 'posts',
				'source' => 'post',
				'desc' => __('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'fw'),
				'help' => sprintf("%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
					__('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'fw'),
					__('Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', 'fw')
				),
			),
</code></pre>

**Comment by GheorgheP** [comment]
Hi,

You can use the `limit` property of `multi-select` option-type: http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi-select
