### ISSUE TITLE
cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by dokicode** [ThemeFuse/Unyson#3520]
Hi!

During installation of modules (f.e. Page Builder) I faced with following error message:
Zip-extention with module couldn't be downloaded: cURL error 60: SSL certificate problem: self signed certificate in certificate chain.

I have following environment:
- last version of WP 4.9.7
- XAMPP with PHP 7.0.13 and curl 7.51.0 on board

I've already tried to edit the php.ini file (parameter curl.info)  to attach CA certificate from Mozilla https://curl.haxx.se/docs/caextract.html, but it didn't help.

Thanks in advance for any help!

**Comment by ViorelEremia** [comment]
I don't know how you have got this curl error but did you try to reinstall xampp or try something from here: https://stackoverflow.com/questions/21187946/curl-error-60-ssl-certificate-issue-self-signed-certificate-in-certificate-cha
Also I think you duplicate the issue. https://github.com/ThemeFuse/Unyson/issues/3528
Let's continue the discussion there.
