### ISSUE TITLE
Event grid categories doesn't save settings

### ISSUE THREAD

**Issue by blursquare** [ThemeFuse/Unyson#3524]
In the builder, the settings of the event grid section doesn't save when we select a categorie and save it. The field is still empty.

**Comment by ViorelEremia** [comment]
What is the event grid section? Unyson by default doesn't have event grid section. Maybe it is a theme issue did you contact your theme developer?

**Comment by blursquare** [comment]
Well, it's eventastic (eventsPlus). I will contact us.
