### ISSUE TITLE
Demo install leave option hook needed

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3525]
the hook `fw_ext_backups_db_export_exclude_option` helps us to exclude option on export ,  

but the demo install wipes all wp_options and we need to keep one option there. 
so we need a hook for demo install to leave an option in wp_options table

something like 

`fw_ext_backups_db_import_exclude_option`

**Comment by ViorelEremia** [comment]
I think there is a filter for that: https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L1100
Did you try it?

**Comment by danyj** [comment]
Never did , will do. Closing till test

**Comment by danyj** [comment]
Tried it and it does not work 

```
/**
 * Keep specific options on DB restore
 */
function _thz_filter_db_keep_options($keep = array(), $is_full_backup ) {
    
	$opt = get_option('option_name');
	error_log ($opt ,0);
	
	$keep = array(
		'option_name',
	);
	
    return $keep;
}

add_filter( 'fw_ext_backups_db_restore_keep_options','_thz_filter_db_keep_options',10, 2);
```


maybe I am not using the hook right but I tested and the error_log is writing the option value to a file before the return so the hook should be skiping the option

**Comment by danyj** [comment]
@ViorelEremia  could you please check this. Thnx!

**Comment by danyj** [comment]
@ViorelEremia  can I please get a hint for this.

**Comment by ViorelEremia** [comment]
Try: 
```
function _thz_filter_db_keep_options( $keep, $is_full_backup ) {

	$keep = $keep + array(
			'keep_my_option' => true,
		);

	return $keep;
}

add_filter( 'fw_ext_backups_db_restore_keep_options', '_thz_filter_db_keep_options', 10, 2 );
```

**Comment by danyj** [comment]
thnx works, juts saw that is asked for key.
