### ISSUE TITLE
I cant see the image product in my shop. 

### ISSUE THREAD

**Issue by Tempitos** [ThemeFuse/Unyson#3527]
Hello, www.tempito.es, if i go to "comprar" i can see the productos, but if i go to buy one, now, i dont see them. I dont know what the f*** happend.

Please, help me!!

**Comment by ViorelEremia** [comment]
It is a theme issue or your js is dead. Please contact your theme author.
Your div with class ```woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-4 images``` has opacity: 0 it is something with css animation maybe
