### ISSUE TITLE
Ajax based contact form

### ISSUE THREAD

**Issue by xpeeder** [ThemeFuse/Unyson#353]
Hi there.
it will be great if contact form will be ajax based. so no need to refresh curent page after submit the contact form. 
also another issue i have found after submit the form. we dont receive any notification like  "form submit successfully" after refresh the page

btw Thanks for this great framework :)

**Comment by danyj** [comment]
:+1:

**Comment by xperter** [comment]
:+1:

**Comment by duongancol** [comment]
like you, I don't see any notification after submitting contact form.

**Comment by xpeeder** [comment]
another issue i have found in text area. i just need little css to make it full width like others field. 
others filed work according to col width except text area field.

**Comment by duongancol** [comment]
@xpeeder :  textarea still work with 'col' width in my local site.

**Comment by xpeeder** [comment]
@duongancol  but its not displayed full width in my localhost :( maybe  i have replaced something.. i will try with fresh copy again.
btw thanks :)

**Comment by duongancol** [comment]
you can check the output in view.php(plugin/unyson/framework/extension/form/includes/option-types/form-builder/items/textare/) or you can override it by following the documentation.

**Comment by moldcraft** [comment]
You can use [this script](https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw-form-helpers.js#L12) to make the form ajax submittable.

By default [form errors are displayed by this code](https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/helpers/class-fw-form.php#L514-L546) and (notifications) [flash messages by this code](https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/class-fw-flash-messages.php#L221-L297).

I have in todo to improve form messages display, but haven't got there yet.

**Comment by xpeeder** [comment]
Hi
@moldcraft you have added this in form ? 
it will be better if you include this directly in form. so everyone can use this without asking you how to make ajaxable form . 
Thank you

**Comment by levan1993** [comment]
@moldcraft it's better to iclude it in config : $cfg['ajax_submitable'] = true;

**Comment by xpeeder** [comment]
@moldcraft  I  Have enqueue fw-form-helpers.js in theme. but still relaod the contact page.
is there i am missing something ??

Thanks

**Comment by moldcraft** [comment]
@xpeeder just enqueue the script is not enought, you have to call the initialization script, here is [an example](https://github.com/ThemeFuse/Unyson/blob/6b24a0aacadce17ac17b3b9a3ee4c49d1e9bf18f/framework/views/backend-settings-form.php#L147-L148)

Try this (with all default options)

```javascript
fwForm.initAjaxSubmit({
	//selector: 'form[some-custom-attribute].or-some-class'
});
```

all [options that you can overwrite](https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/static/js/fw-form-helpers.js#L14-L76)

**Comment by moldcraft** [comment]
> @xpeeder we dont receive any notification like "form submit successfully" after refresh the page

I tested it on one of wp default theme and [the success message is showing](http://static.md/0bf2f5e22d082f31a268ad268a2951fb.png)

**Comment by moldcraft** [comment]
The success message is displayed through `FW_Flash_Messages` helper, please read [this comment](https://github.com/ThemeFuse/Unyson/issues/397#issuecomment-85994609) to understand how it works and how to display manually/better flash messages in your theme.

**Comment by moldcraft** [comment]
Added info in docs http://manual.unyson.io/en/latest/helpers/php.html#fw-form-ajax-submit

**Comment by moldcraft** [comment]
> @levan1993 it's better to iclude it in config : $cfg['ajax_submitable'] = true;

I will not add such cfg.

There are something else I can do/help on this issue? I am thinking to close it.

**Comment by xpeeder** [comment]
Hi @moldcraft  :)
its work for me. but  i thing if you include this on form that will be good for everyone. cause no one want refreshing the page. 

Thank you

**Comment by moldcraft** [comment]
There are already themes that assume forms are not ajax submittable, so I can't change the default behavior (for e.g. our current Scratch Theme has some custom scripts for making ajax forms).

**Comment by martin-bede** [comment]
Hey @xpeeder, you said you had this working – wonder if you could help me out (or anyone else).
I'm enqueuing `fw-form-helpers.js` and running the init script:

```
fwForm.initAjaxSubmit({
    selector: 'form.fw_form_fw_form'
});
```

But when I submit the form I get a console error that `wp-admin/admin-ajax.php` cannot be found. Did you or anyone else ever come up against this issue or know how to solve it?

Cheers

**Comment by moldcraft** [comment]
Specify [this parameter](https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw-form-helpers.js#L15)

```
fwForm.initAjaxSubmit({
    selector: 'form.fw_form_fw_form',
    ajaxUrl: '...'
});
```

**Comment by martin-bede** [comment]
Thanks for the speedy reply @moldcraft.

I have added the line `ajaxUrl: (typeof ajaxurl == 'undefined') ? '/wp-admin/admin-ajax.php' : ajaxurl` but I still seem to get the error.

**Comment by moldcraft** [comment]
> I have added the line `ajaxUrl: (typeof ajaxurl == 'undefined') ? '/wp-admin/admin-ajax.php' : ajaxurl` but I still seem to get the error.

That is the default value, you should specify manually the url to `/wp-admin/admin-ajax.php` on your site

For .e.g. `ajaxUrl: 'http://yousite.com/.../wp-admin/admin-ajax.php'`

**Comment by martin-bede** [comment]
Ahhh I see, cheers :+1: 

For anyone else that comes up against this, I used `ajaxUrl: '<?php echo admin_url("admin-ajax.php"); ?>'` to get the path to `admin-ajax`
