### ISSUE TITLE
[question] How are you putting back image-picker html

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#354]
I am trying to refresh image-picker options via ajax and I end-up getting fresh set of options but the picker UL is missing.  This one here 
http://prntscr.com/6g932w

I looked at your reset function here 
https://github.com/ThemeFuse/Unyson/blob/e925c16f5929b46568429d6a6da8201b5b35bb81/framework/views/backend-settings-form.php#L231

and cant figure out what you do differently

	jQuery.ajax({
		type: "GET",
		dataType: 'text'
	}).done(function(html){
	
			var selectcontent = $(html).find("#fw-option-get_styles").html(); 
			console.log(selectcontent);
	
	}).fail(function(jqXHR, textStatus, errorThrown){
	
		console.error(jqXHR, textStatus, errorThrown);
		alert('Ajax error (more details in console)');
	});

**Comment by moldcraft** [comment]
1. Replace form html received from server
2. Init options in that "raw" html https://github.com/ThemeFuse/Unyson/blob/e925c16f5929b46568429d6a6da8201b5b35bb81/framework/views/backend-settings-form.php#L268

**Comment by danyj** [comment]
Thnx for replying, I tried that also after the replacement 

    fwEvents.trigger('fw:options:init', {$elements:$("#fw-option-get_styles")});

or init the complete form but it does not work for me. 


	jQuery.ajax({
		type: "GET",
		dataType: 'text'
	}).done(function(html){
	
		var selectcontent = $(html).find("#fw-option-get_styles").html(); 
		$("#fw-option-get_styles").html(selectcontent);
		fwEvents.trigger('fw:options:init', {$elements:$("#fw-option-get_styles")});
	
	}).fail(function(jqXHR, textStatus, errorThrown){
	
		console.error(jqXHR, textStatus, errorThrown);
		alert('Ajax error (more details in console)');
	});

**Comment by moldcraft** [comment]
All listeners of the `fw:options:init` event, extract the elements they need using `data.$elements.find('.css-selector')`. You send in `$elements` the option div, and the scripts will search inside it.

Try this in browser console:

```js
var $elements = jQuery('body');
console.log( $elements.find('body').length );
console.log( $elements.parent().find('body').length );
```

So try:

```js
fwEvents.trigger('fw:options:init', {$elements: $("#fw-option-get_styles").parent()});
```

**Comment by danyj** [comment]
Strange 
http://prntscr.com/6g9fpe

**Comment by danyj** [comment]
this is only way it works , you cant replace the picker holder html , only the select and run imagepicker again, otherwise you dont get anything



				jQuery.ajax({
					type: "GET",
					dataType: 'text'
				}).done(function(html){
				
					var selectcontent = $(html).find("#fw-option-get_styles select").html(); 
					$("#fw-option-get_styles select").html(selectcontent);
					$("#fw-option-get_styles select").imagepicker();
				
				}).fail(function(jqXHR, textStatus, errorThrown){
				
					console.error(jqXHR, textStatus, errorThrown);
					alert('Ajax error (more details in console)');
				});
