### ISSUE TITLE
Page builder, and backups dont working

### ISSUE THREAD

**Issue by BroodD** [ThemeFuse/Unyson#3553]
Hello I do not understand the problem, maybe this is due to the hosting, I can not use page builder and backup, in my localhost all work, 
for three days it can not be done

![image](https://user-images.githubusercontent.com/29702996/43881814-25b318dc-9bb6-11e8-88a3-131719078900.png)
-------------------------------
and bottom
![image](https://user-images.githubusercontent.com/29702996/43881865-4c74bd36-9bb6-11e8-85bf-7307803c4222.png)

-------------------------------
errors
![image](https://user-images.githubusercontent.com/29702996/43882095-1c7876c6-9bb7-11e8-8df7-4fa258f43e84.png)

-------------------------------
Please help me...

**Comment by ViorelEremia** [comment]
Update unyson extensions: https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
Check if you have updated theme
Remove any cache server, wordpress plugin, browser, compressor scripts.
After all these things you can disable your plugins one by one to check if isn't a conflict between plugins
