### ISSUE TITLE
Ready to work with Gutenberg

### ISSUE THREAD

**Issue by ange007** [ThemeFuse/Unyson#3555]
Hello.
Since Wordpress very soon will completely switch to Gutenberg - is it planned to implement the transfer of shortcodes Unyson to a new editor?

Perhaps some kind of community help is needed in this?

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/3468

**Comment by ange007** [comment]
> #3468
It is not entirely clear what is being done, how it is done and when it will be ready.
