### ISSUE TITLE
Multi-select values erased in different language

### ISSUE THREAD

**Issue by noesteijver** [ThemeFuse/Unyson#3561]
I'm using WPML on a multilanguage website.

I've made several Theme Options with a multi-select to choose a page.

Situation:
- I fill out the multi-select in the original language (Dutch) and save the Theme Options
- Then: I add some content in English
- Then: I go to the Theme Options to change something (I'm in English mode now)
- I don't see any of my values in the multi-selects
- I save the Theme Options, and the values are still not showing

After further inspecting this, I noticed the values get erased from the multi-selects after saving them in English when I first filled them with Dutch pages.

This seems like a problem to me.

Possible solutions:
- Maybe is it possible to have posts of all languages showing in the multi-select with a language reference?

Hope to hear from you, thanks in advance!
-Kevin

**Comment by noesteijver** [comment]
Hello,

We are experiencing this issue on multiple websites.

Is there a possible solution for this?

If we can help out in any way, just let us know!

Thanks in advance,
-Kevin

**Comment by noesteijver** [comment]
Hi @ViorelEremia ,

This fixes the issue for me, for the most part.

There is a situation possible where the original page name and translated page name are the same. So when we use the multiselect and look for this page by name, we get two results with exactly the same title and no easy way to distinguish these results. 

Would it be possible to place a reference behind the title? Maybe in the same way like the reference to the post type when using input from multiple post type sources.

Thanks in advance!
-Kevin

**Comment by noesteijver** [comment]
@ViorelEremia 

Is it possible to add the language reference (like you did with the post type reference)?

Or is it possible for me to make this, so you can add this?

Thanks in advance!
-Kevin

**Comment by ViorelEremia** [comment]
Please try the attached commit

**Comment by noesteijver** [comment]
Hi @ViorelEremia ,

That seems to do the trick, very nice!

Will this be in the next release?

Thanks again!
-Kevin
