### ISSUE TITLE
How to dynamical set typography font?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#357]
I have tried many options and this selctize is lots of trouble. 
How do I set  the selected font . Normal select is 

    $('select').val('Arial').trigger('change);

But according to selectize api we need to recreate the whole html again. So I need to do this whole thing  

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography/static/js/scripts.js#L5

rebuild the select, set new selectize value

        
	var $select 	= $('select').html(fontsHTML).selectize();
	var selectize 	= $select[0].selectize;
	selectize.setValue(value);

And that adds on again to the page speed.

Another issue is this  timeout

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography/static/js/scripts.js#L40

which completely kills my 

   $(document).on('ready'....

and in order to set the font again I must do timeout of about 2/3 sec. 

Please provide some kind of solution.

**Comment by valeriuzdrobau** [comment]
It is not necessary to generate the html and respectively to set a timeout.
Try the following in the console:

     var $ = jQuery;
     var $mySelect = $('select[name="fw_options[theme_style][header][h1][family]"')[0].selectize;
     $mySelect.setValue('Arial');
     alert($mySelect.getValue());

     $mySelect.addOption({value:'foo',text:'Foo'});
     $mySelect.refreshItems();
     $mySelect.setValue('foo');

**Comment by danyj** [comment]
Works in console because load is done, 

Place it in js file and it will not fire. You will have to do timeout.
This is files order 

http://prntscr.com/6gpsq8

thztypo is same as your typography 
thz.admin.js  is placed last and on 
doc ready I am trying to change the select value. 

I placed your code in thz.admin.js and it does not fire unless there is timeout. 

If I dont use selectize 
A simple 

	$('select').val('Arial').trigger('change);

in thz.admin.js works perfect.

**Comment by valeriuzdrobau** [comment]
[I added an event](https://github.com/ThemeFuse/Unyson/commit/f43eee216f84d247546a166811e84d633841356f) is executed when the load fonts.
Try now to put this code in thz.admin.js

    (function($){
    $(document).ready(function(){

        var $mySelect = $('select.your-typography-select');
        $mySelect.on('selectizeLoaded', function(event, selectize){
            selectize.setValue('Arial');
            alert(selectize.getValue());

            selectize.addOption({value:'foo',text:'Foo'});
            selectize.refreshItems();
            selectize.setValue('foo');
        });
    });
})(jQuery);

**Comment by danyj** [comment]
That works. Thank you . And it seems i need it for sliders also. The  slider.update(value) does not work. http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html

Sliders are simple hidden inputs and change works with 

    el.val(value).trigger('change');


But it is beyond me why none of the fwEvents.trigger  work.  this should basically work instead of the workaround we have now
	
	
	
	$mySelect.val(value).trigger('change');
    fwEvents.trigger('fw:options:init', {$elements: $mySelect});
	
	
	$mySlider.val(value).trigger('change');
    fwEvents.trigger('fw:options:init', {$elements: $mySlider});
	
	

and it should work for every option that we have and I think that is where the bug is. 

Shouldn't that be the case? 

Select , inputs, image pickers , color picker all work fine with simple 

    el.val(value).trigger('change');

radios work with 

    el.filter('[value="' + value + '"]').prop('checked', true).trigger('change');

**Comment by danyj** [comment]
This is slider I am talking about
http://jsfiddle.net/k341o15d/2/
that does not work on our slider options
