### ISSUE TITLE
Issue editor wordpress used unyson

### ISSUE THREAD

**Issue by marcelof1984** [ThemeFuse/Unyson#3577]
other theme function good editor wp: the wordpress editor works well, look here: https://monosnap.com/file/q2Y50qQb5oY0OAU3JnUFI4PrFavHI0
------------
with the theme creatus and unison when I give enter in a post creates spaces, I can not insert multimedia content either.
the developer of creatus is aware of this and asked me to open a ticket about this problem.
video description problem editor unyson: https://monosnap.com/file/pryU8Z1ATESmpRz47nqJC54eCAzmdF

**Comment by danyj** [comment]
This is not insert issue but the editor CSS files contains a br rule that should not be in the editor but on frontend only ,  sent info in the ticket . You can close this.
