### ISSUE TITLE
Empty option containers

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson#358]
In the is an option type container like: box, tab, group, and it doesn't have any option, it should not render at all.

There may be cases where the options from inside are generated dynamically.

http://screencast.com/t/a2hCpdGx

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson/issues/358

**Comment by moldcraft** [comment]
Tested with the following options in

* `{theme}/framework-customizations/theme/options/settings.php`
* `{theme}/framework-customizations/theme/options/posts/post.php`

```php
't1' => array(
	'type' => 'box',
	'title' => 'Empty box',
	'options' => array(),
),
't2' => array(
	'type' => 'box',
	//'title' => 'No title',
	'options' => array(),
),
't4' => array(
	'type' => 'box',
	'title' => 'Box',
	'options' => array(
		'o2' => array('type' => 'text'),
	),
),
't3' => array(
	'type' => 'box',
	//'title' => 'No title',
	'options' => array(
		'o1' => array('type' => 'text'),
	),
),
```
