### ISSUE TITLE
Version 2.2.0 issues .... 

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#359]
Hi there, 
I'm testing my theme for the version **2.2.0** so I updated : 

* The Framework 
* The page builder extension
* The shortcode extension

Then, in a first time it seems that my changes over the extensions located in theme/framework-customizations/extensions were ignored (not all)... And when I edited a page I could seen the shortcode codes generated and the layout was broken on the wordpress editor page.

Then I updated again, and now I get this : 
> Fatal error: Call to a member function get_shortcodes() on a non-object in .../wp-content/plugins/unyson/framework/extensions/shortcode/extensions/page-builder/extensions/editor-shortcodes/class-fw-extension-editor-shortcodes.php on line 85

Did I missed something ? 

I can send you access/screenshot if you need to take a look ;) 

Thank you for the help,
2F

**Comment by moldcraft** [comment]
> Then, in a first time it seems that my changes over the extensions located in theme/framework-customizations/extensions were ignored (not all)

More details please.

> And when I edited a page I could seen the shortcode codes generated and the layout was broken on the wordpress editor page.

* What is actually broken?

> Then I updated again

What did you updated?

> I can send you access/screenshot if you need to take a look ;)

Send me access to `unyson[at]email.com` please.

**Comment by 2Fwebd** [comment]
Thanks @moldcraft !

So first, 
* I downloaded the latest release of Unyson from there : (https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/39). 
* Removed the latest from wp-content/plugins/
* Uploaded the new folder
* Reinstalled page builder extension (from the extensions page) and then :
Page builder was broken : no result only the shortcodes codes in the frontend. Wordpress editor was broken (sorry I didn't take any screenshot, my bad!:/) but : Wordpress editor was filled with shortcodes codes from the page builder, the drag & drop system was below and broken too (no styles/no alignements ...).
* Then, I followed the extensions here : https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/41
* And here : https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/40 
Then I got the error ...

**Comment by 2Fwebd** [comment]
Fixed, sorry @moldcraft  ... :/

**Comment by moldcraft** [comment]
> `Fatal error: Call to a member function get_shortcodes() on a non-object in .../wp-content/plugins/unyson/framework/extensions/shortcode/extensions/page-builder/extensions/editor-shortcodes/class-fw-extension-editor-shortcodes.php on line 85`

The method [`fw_ext( 'shortcodes' )->get_shortcodes()`](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/213ade44aa2140ea2def9bc7fa155ec843bdc69c/extensions/editor-shortcodes/class-fw-extension-editor-shortcodes.php#L85) exists [in the Shortcodes extension](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/8176afff6a8cf471046ce8ac9e8227c809e6bd85/class-fw-extension-shortcodes.php#L25).

So I think the problem is not in code.

**Comment by moldcraft** [comment]
> Fixed, sorry @moldcraft ... :/

What was the problem?

**Comment by 2Fwebd** [comment]
I replied by email, the extension was not well named ... in unyson/framework/extenions there was 
* shortcodes
* shortcode
All works fine now... my mistake sorry!
2F

**Comment by moldcraft** [comment]
No problem. Thank you for testing.
