### ISSUE TITLE
[Events extension] : Event custom post type front end strings not translated (or translatable)

### ISSUE THREAD

**Issue by 5patttttes** [ThemeFuse/Unyson#3595]
Hi there,

I can't locate meta labels for the event custom post type (details, time, price, categories), which are not translated in the front end, even though the default language for my wordpress install is French, in the framework .pot file. Could you let me know how to proceed with their translation ?

Thx

**Comment by danyj** [comment]
HI there , you sure there are not in creatus.pot ?  

Please post screenshot of the exact strings you need translated , I am not sure what strings you need

**Comment by 5patttttes** [comment]
Hi Dany,

My bad : the free online Loco translate tool only allows for 1000 strings therefore I couldn't find the ones I was looking for. The strings indeed are in the creatus.pot file.

Thx (sorry about the false alarm)
