### ISSUE TITLE
[question] Is there a silent save ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#360]
Is there any silent save that will not open the modal "Saving"

these  both show the modal 

	$($form).submit();
	$('[name="_fw_save_options"]').trigger('click'); // executes console Working... Try again later.

I also tried 

	fw.soleModal.hide('fw-options-ajax-save-loading');

but it still shows it for a sec

**Comment by danyj** [comment]
Or an ajax maybe


	$.ajax({
		type: "post",
		dataType: "json",
		url: ajaxurl,
		data: values.replace('fwf=', '_=') + '&action=some_FW_default_SAVE',
		success: function() {
			// Do stuff here
		}
	});

**Comment by moldcraft** [comment]
Why do you need silent save?

**Comment by danyj** [comment]
I need to auto save theme options on ready. Because of this #333 I was forced to reconstruct the options based on style, and I have them saved in a file for each style as json. Basicaly each style has a file with it's custom options set. 

Now on theme options ready I need to reset the form and set the default style. This is all done . 
Now I am saving it but the modal is showing.

**Comment by moldcraft** [comment]
The simplest solution is to do the silent save "manually" with ajax

```js
jQuery.ajax({
	type: "POST",
	data: $form.serialize(),
	dataType: 'json'
}).done(function(r){ ... }).fail(function(jqXHR, textStatus, errorThrown){ ... });
```

*instead of triggering the original save and trying to hide the modal or other things with weird hardcoded solutions*.

**Comment by danyj** [comment]
ah and I was jumping trough hoops


	$.ajax({
		type: "post",
		dataType: "json",
		url: ajaxurl,
		data: $form.serialize().replace('fwf=', '_=') + '&action=thz_save_options',
		success: function() {
			// Do stuff here
		}
	});


and on he other end


	fw_set_db_settings_option(null,FW_Request::POST('fw_options'));

and some of the options were not properly saved.

**Comment by moldcraft** [comment]
>     fw_set_db_settings_option(null,FW_Request::POST('fw_options'));

Omg, never do that, never save in the database raw (not verified, unsafe) `$_POST` or `$_GET` values.

[Look](https://github.com/ThemeFuse/Unyson/blob/f5fdf742ada319e85bfe516c2ded97451722372a/framework/core/components/backend.php#L966-L971) how settings options are saved in the database, the values are extracted with `fw_get_options_values_from_input()`.

----

Anyway, doing https://github.com/ThemeFuse/Unyson/issues/360#issuecomment-80562692 should fire the default save.

**Comment by danyj** [comment]
Thnx for the heads up but I tough this takes care of it 

    FW_Request::POST

**Comment by moldcraft** [comment]
This just removes `\'` added by WordPress. Also some database values differ by structure from POST values.

**Comment by danyj** [comment]
Thnx much , will keep this in mind

**Comment by danyj** [comment]
@moldcraft   since I activated lazy_tabs this silent save does not work anymore , is there something else I can do now ?

I used this and it works fine when lazy tabs are off 


            $.ajax({
                type: 'post',
                dataType: 'json',
                url: ajaxurl,
                data: $('.fw-settings-form').serialize()

            }).done(function(data) {

                if (typeof callBack == 'function') {
                    callBack('done');
                }

            }).fail(function(jqXHR, textStatus, errorThrown) {
                console.error(jqXHR, textStatus, errorThrown);
            });

**Comment by danyj** [comment]
something is off because of lazy_tabs, seems like even if all tabs are initiated not all options are being saved

**Comment by danyj** [comment]
ok I found the issue that is causing me trouble , I have template option that is using ajax to render options and return their html ,  within that html I had to find specific element  and change its value , 
now since lazy_tabs is on all ajax render html comes back as special chars so I cant find an element 

this is the  ajax success peace 

```
                                var $newHtml = $(response.data.html);
                                $newHtml.find('.thz-save-template').attr('data-firstload', 0);
                                newtemplate = $newHtml.prop('outerHTML');
```

is there js  helper function like fw_specailchars that I can use to format the html back  ?

**Comment by danyj** [comment]
il close it for now , I ran init all tabs before that ajax and it is working okish now . if I ran in to trouble again il let you know
