### ISSUE TITLE
Images not saving

### ISSUE THREAD

**Issue by sueanned3** [ThemeFuse/Unyson#3600]
I can upload and image and it shows in the image holder setting. But it won't show where the image is supposed to be on the page itself and won't save either.

I'm using Genesis as my theme.

Love your builder!
Sue
![about new brizy successful blogging](https://user-images.githubusercontent.com/43273083/45554277-05b61880-b804-11e8-8dd3-e40dd4cc9cfc.png)

**Comment by NataliaBB** [comment]
Hi @sueanned3 

Please write a post on Brizy repository https://github.com/ThemeFuse/Brizy/issues

Thanks!
Regards, Natalia
