### ISSUE TITLE
Please solve this.

### ISSUE THREAD

**Issue by K-Vidya** [ThemeFuse/Unyson#3605]
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 80 bytes) in /home/arrowadvt/public_html/wp-content/plugins/unyson/framework/helpers/general.php on line 1271

**Comment by ivandotv** [comment]
increase php memory

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/general.php#L1271

looks like theme developer is using the fonts function in a loop

**Comment by ViorelEremia** [comment]
add in your functions.php ```delete_option( 'fw_google_fonts' );``` refresh any page on your site go back to functions.php remove added code and refresh again the error must dissapear
