### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by jordivuong** [ThemeFuse/Unyson#3607]
Hello,

I cannot install extensions, it returns me this message :

> Cannot download the "Shortcodes" extension zip. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

How can I fix this ?
Thanks

**Comment by lmiftakhov** [comment]
Hello. I think the problem is that your host uses the old version of PHP (version <5.6).

**Comment by ViorelEremia** [comment]
Update your open ssl or contact your server provider
