### ISSUE TITLE
Will you add .po files to "events" and other extension? Need some french translation :)

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson#362]
Will you add .po files to "events" and other extension? Need some french translation :)

https://trello.com/c/Et3obJ1x/44-multi-language-translations

**Comment by moldcraft** [comment]
We have added [translations](https://github.com/ThemeFuse/Unyson/tree/master/framework/languages), you can contribute https://www.transifex.com/themefuse/unyson/
