### ISSUE TITLE
Possible speed improvement for theme and customizer options

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3620]
A very strange bug, it is not Unyson related but Chrome and Opera. 

If you are adding options to customizer and anywhere in your CSS you have a nested specific CSS attribute separated by a space 

`[class*='something'] [class*='else'] {...}`

your backend options tabs and customizer panels will be very slow. It is browser rendering related. Here is video https://monosnap.com/file/hrdFWrFqizkx1Cxtra1TIzHdckxuSo

I tested more and nailed it to that specific space . So even if you have this, your panels performance will suffer. 

`.someclas  [class*='else'] {...}`

this however 

`.someclas[class*='else'] {...}`

does not affect anything.

**Comment by ivandotv** [comment]
CSS selectors are read **right to left**.
[Rendering CSS](https://css-tricks.com/efficiently-rendering-css/)
Maybe that's is the issue.

**Comment by danyj** [comment]
> Maybe that's is the issue.

well it should not be doing that , it has something to do with specific selectors 

this is not affecting it

`.someclas .elseclass
`
only 

`.someclas [ANYTHING] 
`
I know that contain is bit more expensive but declaring only one specific does not slow it either

`[class*='else']`

however it is strange.
