### ISSUE TITLE
Unsyon google fonts are sheduled for deletion. API is blocked. 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#3625]
This is big issue now. 

https://google-webfonts-cache.unyson.io/v1/webfonts

Who ever has created the API please visit this link to stop deletion 

Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project

Or tell us what to do now.

**Comment by alexluncashu** [comment]
we'll check

**Comment by alexluncashu** [comment]
fixed

**Comment by danyj** [comment]
Bless your heart bud!

**Comment by danyj** [comment]
Anyone else if you come  across the issue again and need quick fix , create own dev API for Google fonts
https://developers.google.com/fonts/docs/developer_api
 and add this in your theme functions.php


```
function _thz_filter_fw_googleapis_webfonts_url() {
    return 'https://www.googleapis.com/webfonts/v1/webfonts?key=YOUR_API_KEY';
}

add_filter('fw_googleapis_webfonts_url', '_thz_filter_fw_googleapis_webfonts_url');
```

ref 

https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/general.php#L1305

**Comment by lolla87** [comment]
@danyj Thank you soooooooooooo much for this advice!!! I've been struggling for 4 days to get Google Fonts loaded in the backend, then finally your comment came across and now it's working! 

Many thanks!!!
