### ISSUE TITLE
Default value in Select Option

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#364]
Hi!
How can I set default value for Select option type?

Thanks!

**Comment by levan1993** [comment]
Hi,
$option['value'] = 'some_value';

**Comment by duongancol** [comment]
@levan1993 : So I have to override this option?

**Comment by levan1993** [comment]
@duongancol : if no value found in database for this option, then $option['value'] will be used as fallback

**Comment by duongancol** [comment]
I want to create a post with select option from frontend. It's saved with a post. But when I go to this post from backend, the select option value is not value that 's saved from frontend.

**Comment by levan1993** [comment]
how are you saving post in frontend?

**Comment by duongancol** [comment]
I used fw_set_db_post_optionoption() helper function.

**Comment by levan1993** [comment]
what arguments are you passing to this function?

**Comment by duongancol** [comment]
For example: 
<pre>
$input_values = array(
'select' => 'Abc',
...
);
$old_values = (array)fw_get_db_post_option($post_id);
$new_values = fw_get_options_values_from_input(
$options,
$input_values
);
 fw_set_db_post_option(
 $post_id, 					  
 null,
array_merge($old_values, $new_values)
 );
</pre>
I make sure that the value is saved.

**Comment by levan1993** [comment]
with your setup it should save options.

**Comment by duongancol** [comment]
I know, but I want this save options can show in backend, for example, I have select option:
<pre>
option 1
option 2
option 3
</pre>
I create a post with option 2 with name Post 1, but when I go to wp-admin to edit Post 1, the value of select option is option 1 although it's actually option 2.

**Comment by moldcraft** [comment]
Show me `fw_print($options)` please.

**Comment by duongancol** [comment]
it's :
<pre>
           'options' => array(
						//Difficulty level
						'level' => array(
							'type' => 'select',
							'value' => 'hard',
							'label' => __('Difficulty level', 'mauris'),
							'choices' => array(
								'easy' => 'Easy',
								'hard' => 'Hard',
								'master' => 'Master',
							)
						),
</pre>

**Comment by moldcraft** [comment]
In the example above you showed

```php
'select' => 'Abc',
```

Note the Upper case, this is unusual for select value because the value saved in the database is the choice key, not title.

```
'choices' => array(
    'easy' => 'Easy',
    'hard' => 'Hard',
    'master' => 'Master',
)
```

So in the database can be saved `easy`, 'hard' or `master`, but not `Easy`, 'Hard', 'Master'.

**Comment by duongancol** [comment]
Thanks for your help!
