### ISSUE TITLE
Wordpress default customizer

### ISSUE THREAD

**Issue by stivoox** [ThemeFuse/Unyson#3648]
Hi friends.
After adding some panels and sections to the customizer I see that teh default wordpress panel/sections still on the customizer , how to remove them ?.
Regards

**Comment by yura-x** [comment]
Hello!
Unyson customizer options does not remove default customizer options, they are extend them. 
You can try to hide standard sections via CSS or via actions:
[https://graphicsandcodes.wordpress.com/2017/09/05/remove-wordpress-default-theme-customizer-sections-settings-control/](https://graphicsandcodes.wordpress.com/2017/09/05/remove-wordpress-default-theme-customizer-sections-settings-control/)
