### ISSUE TITLE
[question] How to convert Unyson options json to option names in JS?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#366]
I was wondering if Unyson has a way to convert  the 

    fw_get_db_settings_option()

to an array of option names in JS? like 

    name="fw_options[option][gadget][custom]

or ad-least the

    [option][gadget][custom]

I started the convert but the json data from ajax request are deep so extracting the exact name is bit of trouble. First levels are oki'sh but further than that is troublesome. 

			$.ajax({
			  type : 'get',
			  dataType : 'json',
			  url: ajaxurl,
			  data: {
				'action': 'thz_get_default_options',  
			  }
			  
			  }).done(function(data){
				  
				  console.log(data.options);  
				  for(var x in data.options) {
					  for(var y in data.options[x]) {
						console.log( "name of "+x+" is: "+data.options[x][y] );
					  }
				  }

				  
			  }).fail(function(jqXHR, textStatus, errorThrown){ 
			  		console.error(jqXHR, textStatus, errorThrown);
			  });

php

function thz_get_default_options() {
	
	$options = fw_get_db_settings_option();

	$return = array(
		'options'	=> $options,
	);	
	wp_send_json($return);
}

add_action("wp_ajax_thz_get_default_options", "thz_get_default_options");

**Comment by moldcraft** [comment]
There is no sense to convert the database values directly to html inputs, because database values are not converted directly to html inputs, option types convert them, and simple option types and values may be converted to the same structure (html structure == database structure) but more complicated/different option types can have (html structure != database structure), for e.g. this is how option type `addable-popup` workflow:

1. Get settings values from the database

    ```php
    array(
        array('foo' => 'bar'),
        array('foo' => 'baz'),
    )
    ```

2. Get settings options from file

    ```php
    array(
        'type' => 'addable-popup',
        'popup-options' => array(
            'foo' => array( 'type' => 'text' ),
        ),
    )
    ```

3. Them option type, from option array and database value, [generates the html](https://github.com/ThemeFuse/Unyson/blob/f43eee216f84d247546a166811e84d633841356f/framework/includes/option-types/addable-popup/views/view.php#L31)

    ```html
    ...
    <input name="fw_options[test][]" value="{&quot;foo&quot;:&quot;bar&quot;}" ...>
    ...
    ```

4. On form submit, the option type receives html input value and [convert it](https://github.com/ThemeFuse/Unyson/blob/f43eee216f84d247546a166811e84d633841356f/framework/includes/option-types/addable-popup/class-fw-option-type-addable-popup.php#L108) to database value.

**Comment by danyj** [comment]
Im losing it a bit but I am trying to make this whole thing faster than it is since I cant use multi #333 . 

I cant continue at all now since everything comes back to speed  and multiple styles and all I am trying to do is reset the darn form to my default values.  The way you are resetting the form depends on the form values being written as options in a php file. They way I am trying to do is reset them according to my json response. 

I get the json  like this 


    {"foo":"123","bar":"456","rows":[{"column1":"hello","column2":"hola","column3":"bonjour"},{"column1":"goodbye","column2":"hasta luego","column3":"au revoir"}],"test1":{"test2":{"test3":"baz"}}}


now I want to find the form options and set their values according to that json.

**Comment by danyj** [comment]
I am not sure if you realized this but the more style options you have the admin becomes unusable thus I am trying to simplify all of this but because of the depth of array options it just gets complicated.

**Comment by danyj** [comment]
Maybe I am just not explaining the right way what I am doing now since your repose looks like something else than what I am doing. 


Your form option save button sends data to DB in this way 


    fw_options[layout_type][boxed][body_background_type][color][bg_type_color]:#dd9191


http://prntscr.com/6hkmec

the corresponding name for that input is 
    fw_options[layout_type][boxed][body_background_type][color][bg_type_color]


http://prntscr.com/6hkmtt

the array from fw_get_db_settings_option() returns it as 
http://prntscr.com/6hknjb

my json response is 
http://prntscr.com/6hko4j

    layout_type":{"gadget":"boxed","boxed":{"body_background_type":{"gadget":"color","color":{"bg_type_color":"#dd9191"}

so now all I am trying to do is convert the json response , to corresponding form inputs names and set their values according to json.

I am not recreating html , just giving back the values

**Comment by danyj** [comment]
If you can just help me convert the php fw_get_db_settings_option()  to return 

    [layout_type][boxed][body_background_type][color][bg_type_color]:#dd9191

I have 2 levels so far

	  foreach($array as $key => $value){
			//If $value is an array.
			if(is_array($value)){
				//loop through it.
				thz_return_deep($value,'['.$key.']');
				
			} else{
				//It is not an array, so print it out.
				echo $newlevel.'['.$key.']='.$value.'','<br />';
			}
		}

**Comment by moldcraft** [comment]
> Your form option save button sends data to DB in this way

No. Data is sent to option-types `_get_value_from_input()`, then the returned value is sent to db.

What are you doing may work for some time, because db values of your current options has the same structure as html values. But in the future, when you will use new options or something will change in an option-type you currently use, your code will grow with hacks.

> I have 2 levels so far

Are you familiar with recursions?

```php
function thz_array_to_html_input_names(&$data, &$result, $_current_prefix = '') {
	foreach ($data as $key => &$val) {
		if (empty($val)) {
			$val = '';
		}

		if (is_array($val)) {
			thz_array_to_html_input_names($val, $result, 
				$_current_prefix .'['. htmlspecialchars($key) .']'
			);
		} else {
			$result[ $_current_prefix .'['. htmlspecialchars($key) .']' ] = (string)$val;
		}
	}
}

$data = array(
	'foo' => 'bar',
	'hello' => array(
		'foo' => 'bar',
		'hello' => array(
			'foo' => 'bar',
			'hello' => array(),
		),
	),
);

$result = array();

thz_array_to_html_input_names($data, $result);

print_r($result);
```

**Comment by moldcraft** [comment]
(There was a little mistake in the function, I edited the comment)

**Comment by danyj** [comment]
Thank you much for the function! I fixed the double [] and see now that you redid it.  But please explain further about the change? 

I looked trough all the options you have and they use same patterns, form names are in same order and I do not see why and how would DB info change.  I am not manipulating the DB saved options at all. Not even touching them ,but merely trying to get the corresponding options names. 

Where exactly do you think issue could be. I rather tackle all this and to be honest I dont mind reconstruction everything again if you see a bigger problem now.

**Comment by moldcraft** [comment]
For e.g. now you expect that (and can confirm that)

```
fw_options[layout_type][boxed][body_background_type][color][bg_type_color]
```

was generate from the database value and exists in the html, so your replace script works.

But after some time, for example we will change/improve the color-picker option type, and in html will be

```
fw_options[layout_type][boxed][body_background_type][color][bg_type_color][type]
fw_options[layout_type][boxed][body_background_type][color][bg_type_color][hex]
fw_options[layout_type][boxed][body_background_type][color][bg_type_color][rgba]
```

`type` will be a switch that will show/hide hex/rgba color picker. The database value will remain the same (of course, to not have fatal errors in all themes that uses it) but only the html/js will be changes. (this is just an example, we don't have any such plans for color-picker now)

My idea is that we do not guarantee that options html will remain the same over time (db values will do), and the input names that you generate manually from db values, now exists and works, but in the future they may not exist and your replace script will not work.

Unfortunately I don't know a solution for this issue, just want you to understand my warning.

**Comment by danyj** [comment]
I see what you mean. For now this works ok , will keep this in mind and try to find better ways to do this but once I am done il send you the theme than you will be able to see the reason for all of this. Again I wish I would be able just to use the default multi for all options but currently I cant.

**Comment by danyj** [comment]
@moldcraft  You were right about it,  got almost all options squared away except the image upload/upload, it does what you said it will and I can only assume that there will be more of those

it switches the option name from 

    [upload]

to 

    [upload][atachment_id]




Do you mind if I pick your brain a bit about this. 

The idea of the switch is great , the issue is the array of options is not same as the options printed. What I would like to do is copy the way you do Reset options. So far I have seen it does this 

1. On reset click it empties DB 
2. You get the form HTML via ajax 
3. since there are no options in DB you load options from input or should I say it loads the default value


My idea for number 3 

look in the stylename file for options array,
apply  _get_value_from_input to the options and load those instead of the defaults. 

Do you think this would be doable and what would be best approach?

**Comment by danyj** [comment]
Or , a way ti intercept the data right before it is saved and serialized in DB, than my array will be 100% same as in DB . For now I am saving it via form.serializeArray() thus the inconsistency with the actual DB data.

**Comment by moldcraft** [comment]
1. Can you explain what's the problem with the default reset?

2. > **The idea of the switch** is great , the issue is **the array of options is not same as the options printed**.

    I don't understand this. Please try again to explain.

3. > My idea for number 3
    >
    > look in the stylename file for options array, apply _get_value_from_input to the options and load those instead of the defaults.

    I think now [it works exactly as you want](https://github.com/ThemeFuse/Unyson/blob/b2229ea1e5ac953989f22556cfdd77177f6e5e40/framework/helpers/database.php#L37-L38)

> **my array** will be 100% same as in DB.

    Which array, and why it should be exactly as db array?

**Comment by danyj** [comment]
No problems with  reset at all.  Il send you an email and video. You must see this.

**Comment by danyj** [comment]
Never mind for now. Before going live il send you the theme and  it will make sense.  Sorry for wasting your time.

**Comment by moldcraft** [comment]
Sorry that I don't understand all what you are trying to explain.

**Comment by danyj** [comment]
Not a problem bud. Honestly. It is just peace of the engine that works for now. I managed to get all options reset . Once done I would like  you to take a look and if you think that it can be improved we can talk about it.

**Comment by stivoox** [comment]
Hi. I want to pass shortcodes data from php to javascript. any idea??
