### ISSUE TITLE
impossible to edit pages after wordpress 5 update

### ISSUE THREAD

**Issue by fran56** [ThemeFuse/Unyson#3664]
Hello,
I'm using Unyson with The core theme (Unyson 2.7.20 | Theme 1.0.15)
Since I have updated to wordpress 5, I have a blank page when I try to edit pages.
The default edit page opens, then there is a refresh of the page and it finally opens an error page.
I have tried to install the classic-editor plugin as I have read on another post but with no success.
I also need to add that when I try to update The Core parent theme to the new version, I have the message "Update failed: The package could not be installed".
This is VERY annoying as I have an important update to do for my client.
Can you please urgently help.
Thanks

**Comment by ViorelEremia** [comment]
It's a theme issue, please contact the [theme author](https://support.themefuse.com/hc/en-us/requests/new).
