### ISSUE TITLE
How to fetch category field data. I am doing something wrong?

### ISSUE THREAD

**Issue by ahmmob** [ThemeFuse/Unyson#367]
<pre>

$args = array(
  'orderby' => 'name',
  'order' => 'ASC'
  );
$categories = get_categories($args);
  foreach($categories as $category) { 
    echo '<div style="width:250px; margin:10px; float:left; background:#f2f2f2;">';
      echo ( function_exists('fw_get_db_settings_option') ) ?
fw_get_db_settings_option('new') : ''; 
    echo '<p>Category: <a href="' . get_category_link( $category->term_id ) . '" title="' . sprintf( __( "View all posts in %s" ), $category->name ) . '" ' . '>' . $category->name.'</a> </p> ';
    echo '<p> Description:'. $category->description . '</p>';
    echo '<p> Post Count: '. $category->count . '</p></div>';  } 
</pre>

**Comment by moldcraft** [comment]
Try `fw_get_db_term_option($category->term_id, $category->taxonomy, 'new')`
http://manual.unyson.io/en/latest/helpers/php.html#database

**Comment by ahmmob** [comment]
Thanks. Issue is resolved :+1:
