### ISSUE TITLE
Custom ID / class to grid(fw-row/fw-col)

### ISSUE THREAD

**Issue by Frost0x** [ThemeFuse/Unyson#3674]
Hi, everyone.

Really need your help with the following question:
How do I add the ability to specify a custom class and ID for grid elements using the page Builder?
I have already made a custom class for the partition, but the classes with FW-rw and fw-col elements are defined by a different algorithm.

Tell me how to make a custom class for grid elements fw-row fw-col? 

I attach screenshots, they do not have the edit button in the grid elements, and I need to add. And in the settings should be a custom class and ID.
<a href="https://ibb.co/9wFd9fj"><img src="https://i.ibb.co/9wFd9fj/1.jpg" alt="1" border="0"></a>
<a href="https://ibb.co/1X87CqH"><img src="https://i.ibb.co/1X87CqH/2.jpg" alt="2" border="0"></a>
<a href="https://ibb.co/b5sxxXk"><img src="https://i.ibb.co/b5sxxXk/3.jpg" alt="3" border="0"></a>

**Comment by yura-x** [comment]
Hello! Do you need your custom class displayed on front end or back end?
If I understand you right, you need to create a file
`YOURTHEME/framework-customizations/extensions/builder/config.php`

with following code (live example of overriding default CSS classes in our themes):

```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$cfg = array();

/**
 * Default item widths for all builders
 *
 * It is better to use fw_ext_builder_get_item_width() function to retrieve the item widths
 * because it has a filter and users will be able to customize the widths for a specific builder
 *
 * @see fw_ext_builder_get_item_width()
 * @since 1.2.0
 *
 * old $cfg['default_item_widths'] https://github.com/ThemeFuse/Unyson-Builder-Extension/issues/8
 * https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/v1.1.17/config.php#L13
 */
$cfg['grid.columns'] = array(
	'1_6' => array(
		'title'          => '1/6',
		'backend_class'  => 'fw-col-sm-2',
		'frontend_class' => 'col-xs-12 col-12 col-lg-2',
	),
	'1_4' => array(
		'title'          => '1/4',
		'backend_class'  => 'fw-col-sm-3',
		'frontend_class' => 'col-xs-12 col-12 col-lg-3',
	),
	'1_3' => array(
		'title'          => '1/3',
		'backend_class'  => 'fw-col-sm-4',
		'frontend_class' => 'col-xs-12 col-12 col-lg-4',
	),
	'1_2' => array(
		'title'          => '1/2',
		'backend_class'  => 'fw-col-sm-6',
		'frontend_class' => 'col-xs-12 col-12 col-lg-6',
	),
	'2_3' => array(
		'title'          => '2/3',
		'backend_class'  => 'fw-col-sm-8',
		'frontend_class' => 'col-xs-12 col-12 col-lg-8',
	),
	'3_4' => array(
		'title'          => '3/4',
		'backend_class'  => 'fw-col-sm-9',
		'frontend_class' => 'col-xs-12 col-12 col-lg-9',
	),
	'1_1' => array(
		'title'          => '1/1',
		'backend_class'  => 'fw-col-sm-12',
		'frontend_class' => 'col-xs-12 col-12',
	),
);

/**
 * @since 1.2.0
 */
$cfg['grid.row.class'] = 'row';

/**
 * @deprecated since 1.2.0
 * if this is empty fw_ext_builder_get_item_width() will use $cfg['grid.columns']
 */
$cfg['default_item_widths'] = false;

```

**Comment by Frost0x** [comment]
Thank you very much, I have already studied this option.

I needed to be able to define different classes for grid elements in different blocks. 
For example, to be able to do so in one block <div class="row mx-5 mx-md-0"><div class="col-md-6 col-lg-5 mt-4 mt-lg-0"> and so in another <div class="row mt-md-5"><div class="col-md-4">.

**Comment by yura-x** [comment]
There is no visible shortcode for Bootstrap row, so I guess you need to put additional options for 'section' and for 'column' shortcode:  
`YOURTHEME/framework-customizations/extensions/shortcodes/shortcodes/column/options.php`
`YOURTHEME/framework-customizations/extensions/shortcodes/shortcodes/section/options.php`
and then catch these additional classes in views:
`YOURTHEME/framework-customizations/extensions/shortcodes/shortcodes/column/views/view.php`
`YOURTHEME/framework-customizations/extensions/shortcodes/shortcodes/section/views/view.php`
For rows this solution will require additional CSS, for example:
`section.row-mx-5 > .row { margin-left: 5rem, margin-right: 5rem; }`
Or you can put additional classes for row in 'section' shortcode and also catch them in 'section' shortcode view.

**Comment by Frost0x** [comment]
Hi, thank you for your reply.

Yes, I had to do as you wrote - it can be seen in my screenshots, I have already made a custom Class and custom ID for the section. And for row, I added all the properties I needed in css.

I wanted to make sure there was no other way, thank you for explaining it to me.
