### ISSUE TITLE
Unyson Extensions

### ISSUE THREAD

**Issue by qfengnh** [ThemeFuse/Unyson#369]
"Available Extensions

No extensions activated yet
Check the available extensions below"

All cannot download

**Comment by sergiubagrin** [comment]
Hi @qfengnh 

It is working fine on my side. I tested on Windows and Mac OS.

1. Can you check PHP/ Apache error log?
2. Can you give me a screen with more details?

**Comment by qfengnh** [comment]
WordPress.
Show nothing before Press download,but not install.
2015年3月17日 下午4:01于 "sergiubagrin" <notifications@github.com>写道：

**Comment by moldcraft** [comment]
@qfengnh Check now please.

If it's still happening, feel free to reopen this issue.
