### ISSUE TITLE
PHP Version 7.3 Compatibility issue with continue statement 

### ISSUE THREAD

**Issue by etwordpress01** [ThemeFuse/Unyson#3695]
Hello,
We recently faced an issue with PHP version 7.3

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/host/public_html/wp-content/plugins/unyson/framework/core/components/extensions/manager/class--fw-extensions-manager.php on line 3682

![download](https://user-images.githubusercontent.com/31212934/51687747-fdbd7f00-2014-11e9-86bc-24c316706216.png)

Can you please help me to solve this issue?

Thanks

**Comment by etwordpress01** [comment]
Hello @danyj 

Is that issue is with plugin or theme side issue? Can you please help me to sort it out? If i made the change in plugin is that will resolve the issue? 

Looking forward

**Comment by danyj** [comment]
@etwordpress01 that is plugin side. yes it should fix the warning

**Comment by etwordpress01** [comment]
Hi, @danyj  Thank you for the quick response. I will wait for the unyson plugin update. 

Thanks

**Comment by xperter** [comment]
@danyj  Please update the code to wordpress.org.
Hope you understand that it's causing troubles to so many sites out there.  👍

**Comment by shahinurcse** [comment]
I have install latest version , but still now same issues, please resolve it asap, please

![screenshot_1](https://user-images.githubusercontent.com/31178593/52254927-79cf9500-293a-11e9-8c4a-f37769f6ad83.png)

**Comment by SirLouen** [comment]
https://wiki.php.net/rfc/continue_on_switch_deprecation

**Comment by danyj** [comment]
pull created , @andreiglingeanu  https://github.com/ThemeFuse/Unyson/pull/3716
