### ISSUE TITLE
How to add additional input field for author image when creating new user

### ISSUE THREAD

**Issue by ahmmob** [ThemeFuse/Unyson#370]
Is there any way to add author image in author profile?

**Comment by sergiubagrin** [comment]
Hi @ahmmob 

This question is not related to Unyson framework we don't have a user extension

Articles:

1. https://wordpress.org/support/topic/extended-author-profiles?replies=7
2. http://www.thecreatology.com/how-to-extend-contact-details-of-author-profile-in-wordpress.html
3. http://www.sitepoint.com/11-of-the-best-wordpress-author-bio-plugins/
