### ISSUE TITLE
Can I add my own icons to icons list?

### ISSUE THREAD

**Issue by ahmmob** [ThemeFuse/Unyson#371]
I want to add more icon fonts. How can I add new fonts?

Thanks in advanced :)

**Comment by moldcraft** [comment]
You can add new fonts (or we call them sets) via [this filter](https://github.com/ThemeFuse/Unyson/blob/b4aedf8cb0aecc5f1c64710e2a090f983cff8d42/framework/includes/option-types/icon/class-fw-option-type-icon.php#L128).

**Comment by ahmmob** [comment]
sorry. can you elaborate it little bit please

**Comment by moldcraft** [comment]
```php
function _filter_theme_new_icon_set($sets) {
        $sets['font-awesome-2'] = array(
    	'font-style-src' => fw_get_framework_directory_uri('/static/libs/font-awesome/css/font-awesome.min.css'),
    	'container-class' => 'fa-lg', // some fonts need special wrapper class to display properly
    	'groups' => array(
    		'web-app' => __('Web Application Icons', 'fw'),
    		'transport' => __('Transportation Icons', 'fw'),
    	),
    	'icons' => array(
    		// Web Application Icons
    		'fa fa-adjust' => array('group' => 'web-app'),
    		'fa fa-anchor' => array('group' => 'web-app'),
    		'fa fa-ambulance' => array('group' => 'transport'),
    	),
    );

    return $sets;
}
add_filter('fw_option_type_icon_sets', '_filter_theme_new_icon_set');
```

Then in options array specify the set

```php
array(
    'type' => 'icon',
    'set' => 'font-awesome-2',
)
```

**Comment by ahmmob** [comment]
I am trying to add above code buy I am getting error. Here is the complete file
https://www.dropbox.com/s/d95j22w8qhtj218/class-fw-option-type-icon.php?dl=0
Can you tell me where I am doing mistake?

**Comment by moldcraft** [comment]
Why are you changing the `icon` option-type class?
Try to add [that piece of code](https://github.com/ThemeFuse/Unyson/issues/371#issuecomment-82525378) to your `{theme}/functions.php`.

**Comment by ahmmob** [comment]
oh sorry. It works :+1: 
I want new fonts into existing one. Is this possible.
![icon](https://cloud.githubusercontent.com/assets/11507856/6735167/509579c2-ce7e-11e4-8afa-034025ecc211.jpg)
![fonts](https://cloud.githubusercontent.com/assets/11507856/6735191/75b98b9e-ce7e-11e4-9e65-f28be9388322.jpg)

**Comment by moldcraft** [comment]
Sure, [use the filter](https://github.com/ThemeFuse/Unyson/issues/371#issuecomment-82525378) ...

**Comment by ahmmob** [comment]
<pre>
function _filter_theme_new_icon_set($sets) {
        $sets['font-awesome-2'] = array(
        'font-style-src' => fw_get_framework_directory_uri('/static/libs/font-awesome/css/font-awesome.min.css'),
        'container-class' => 'fa-lg', // some fonts need special wrapper class to display properly
        'groups' => array(
            'web-app' => __('Web Application Icons 2', 'fw'),
            'transport' => __('Transportation Icons 2', 'fw'),
        ),
        'icons' => array(
            // Web Application Icons
            'fa fa-adjust' => array('group' => 'web-app'),
            'fa fa-anchor' => array('group' => 'web-app'),
            'fa fa-ambulance' => array('group' => 'transport'),
        ),
    );
    return $sets;
}
add_filter('fw_option_type_icon_sets', '_filter_theme_new_icon_set');
</pre>
I am already using this filter but it creates separate filed instead of merging it into default icons set.

**Comment by moldcraft** [comment]
`fw_print($sets);`

**Comment by ahmmob** [comment]
fw_print($sets); is not working.
if you don't mind, can you send complete code please.

**Comment by ahmmob** [comment]
can I have a complete code please. Because I am little confused. I completed everything in my theme except this one :+1:

**Comment by moldcraft** [comment]
Sorry, there was a [bug in option-type `icon`](https://github.com/ThemeFuse/Unyson/commit/6b24a0aacadce17ac17b3b9a3ee4c49d1e9bf18f) that made [`enqueue_static()` call only on first option](https://github.com/ThemeFuse/Unyson/blob/6b24a0aacadce17ac17b3b9a3ee4c49d1e9bf18f/framework/core/extends/class-fw-option-type.php#L205-L213).
The fix will be included in the [next release](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/45).

----

Glyphicons example

```php
// file: {theme}/functions.php or {theme}/inc/hooks.php

function _filter_theme_glyphicons_icon_set($sets) {
	$sets['glyphicons'] = array(
		'font-style-src' => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css',
		'container-class' => '', // some fonts need special wrapper class to display properly
		'groups' => array(
			'currency' => __('Currency', 'fw'),
			'directional' => __('Directional', 'fw'),
		),
		'icons' => array(
			// Web Application Icons
			'glyphicon glyphicon-euro' => array('group' => 'currency'),
			'glyphicon glyphicon-bitcoin' => array('group' => 'currency'),
			'glyphicon glyphicon-yen' => array('group' => 'currency'),
			'glyphicon glyphicon-ruble' => array('group' => 'currency'),
			'glyphicon glyphicon-menu-left' => array('group' => 'directional'),
			'glyphicon glyphicon-menu-right' => array('group' => 'directional'),
			'glyphicon glyphicon-menu-down' => array('group' => 'directional'),
			'glyphicon glyphicon-menu-up' => array('group' => 'directional'),
		),
	);

	return $sets;
}
add_filter('fw_option_type_icon_sets', '_filter_theme_glyphicons_icon_set');
```

```php
// file: {theme}/framework-customizations/theme/options/settings.php

$options = array(
	'my-icon' => array(
		'type' => 'icon',
		'set'  => 'glyphicons',
	),
);
```

**Comment by ahmmob** [comment]
I tried your settings but in result I got blank icon spaces
![screenshot_1](https://cloud.githubusercontent.com/assets/11507856/6883230/e398fa8e-d5c5-11e4-9081-1663c8eb7efe.jpg)

can I use this in categories instead of settings.php?

**Comment by moldcraft** [comment]
What Unyson version do you have?

**Comment by ahmmob** [comment]
I updated to latest version. Now they are showing. But due to placing code in settings.php they are showing at the end of every tab http://prntscr.com/6oa33b
But Thing is that I want new icon group inside plugin existing fonts group http://prntscr.com/6oa3vh.
Hope I am clear.

**Comment by moldcraft** [comment]
> But due to placing code in settings.php they are showing at the end of every tab http://prntscr.com/6oa33b

That was just an example, place the option wherever you want.

> But Thing is that I want new icon group inside plugin existing fonts group http://prntscr.com/6oa3vh.

Use the filter and add your group in `$sets['font-awesome']['groups']`.

**Comment by ahmmob** [comment]
<blockquote>
<p>Use the filter and add your group in $sets['font-awesome']['groups'].</p>
</blockquote>
Can I get complete code please if you don't mind.

**Comment by ahmmob** [comment]
I am not much expert in php. So I will highly appreciate if you can send me complete code that I can just copy.

**Comment by moldcraft** [comment]
Sorry, we don't have time to teach people php and to write code for them, we can help you if have some issues with the Unyson itself.

**Comment by duongancol** [comment]
the same question, How can I merge new icon to existing icon set instead of create a new icon option. ?

**Comment by moldcraft** [comment]
@duongancol So you want to merge some custom (or other font) icon to font-awesome icons? And the classes will be

```
fa fa-...
fa fa-...
fa fa-...
something-different
fa fa-...
...
```

----

P.S. Just use [the filter](https://github.com/ThemeFuse/Unyson/blob/b4aedf8cb0aecc5f1c64710e2a090f983cff8d42/framework/includes/option-types/icon/class-fw-option-type-icon.php#L128), make `fw_print($sets);` and inspect the array. You are allowed to change that array however you want.

**Comment by duongancol** [comment]
Got it, but when I added other icons, for example glyphicons, the css file of glyphicons affected to wp-admin. Please look at this http://prntscr.com/7evu4a, http://prntscr.com/7evudo

**Comment by moldcraft** [comment]
You have to build your own glyphicon css file by removing everything that is not icon related.

**Comment by duongancol** [comment]
Perfect! Thank @moldcraft
