### ISSUE TITLE
WP 5 update, custom post type white screen

### ISSUE THREAD

**Issue by CodeWavePro** [ThemeFuse/Unyson#3715]
After WP updates to latest versions (5+) I can't edit or add my posts in Unyson custom post type extension (can see only white screen). When I installed Classic editor plugin - all is fine. How to solve this problem without classic editor plugin?

**Comment by danyj** [comment]
https://gist.github.com/danyj/ec00057550fd6f73995ab2f8fc8b729f

**Comment by CodeWavePro** [comment]
Thank you very much, it helps!
