### ISSUE TITLE
Weird Strong Tag

### ISSUE THREAD

**Issue by stivoox** [ThemeFuse/Unyson#3723]
Hi Friends .
I just Want to know how to remove this Strong around Sections in the page builder : https://imgur.com/a/XnuTmZe
regards

**Comment by danyj** [comment]
what theme?

**Comment by stivoox** [comment]
@danyj my own theme that i'm building

**Comment by danyj** [comment]
not sure what you did there but there is no strong tag in section view

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/views/view.php

**Comment by danyj** [comment]
maybe you forgot the closing in another element and dev tools is showing own closing, do ctrl+u  to see actual code

**Comment by stivoox** [comment]
@danyj That's true in the source view there's no strong tag that's weird

**Comment by stivoox** [comment]
@danyj Thanks a lot , it's caused by a not closed strong tag .
