### ISSUE TITLE
accordion help for customization

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson#373]
Hi,

I would like to know if someone know the code to have an accordion with tabs on top like these pictures : http://www.freebiewebresources.com/wp-content/uploads/2012/12/Pofi-Accordion-Menu.jpg 
http://s27.postimg.org/kggghq28j/Untitled_1.jpg

I would like that with a kind of fade-in fade-out effect when changing these tabs.

Thank you

**Comment by dameer** [comment]
This is called Tabs, you have tabs shortcode already available but you obviously need to style it up a bit differently.

**Comment by GheorgheP** [comment]
Hi,

The solution in the first part of the request was provided in this issue: https://github.com/ThemeFuse/Unyson/issues/374

About effects already you have to use the [jQuery Accordion](http://api.jqueryui.com/accordion/) documentation and on tab load add the desired effect.
