### ISSUE TITLE
Rendering shortcodes twice

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#375]
Hi,

Anyone have the problem that the shortcodes in a page is rendered twice after upgrade to 2.2.0 ?

Thanks

**Comment by moldcraft** [comment]
Hi,

Give me more details how to reproduce this. Also a link to a site, screenshot, or screencast.

**Comment by danyj** [comment]
I have the latest also and cant see this.

**Comment by maiakhoa** [comment]
Sorry about this if it's not right. 
- As I can see, the first time you render the shortcode via this action "wp_enqueue_scripts"  by this method "_action_enqueue_shortcodes_static_in_frontend_head"
- And the second time when render the content of post.

**Comment by moldcraft** [comment]
I thought you see double content on the page.

The first render in `wp_enqueue_scripts` action is done to include css/js in page `<head>` #153

**Comment by maiakhoa** [comment]
no, just one content on the page. But I think that it's wasted when you rendering twice the shorcodes on the page

**Comment by moldcraft** [comment]
We don't know a solution to include css/js in `<head>` and to not render the shortcodes twice.

https://github.com/ThemeFuse/Unyson/issues/153#issuecomment-69726302

**Comment by maiakhoa** [comment]
Can you cache the first result rendering and re-use for the second ?

**Comment by moldcraft** [comment]
I don't know, the second render is done by default by WordPress `do_shortcode($post_content);`.

**Comment by maiakhoa** [comment]
As I can see, in the method "_action_enqueue_shortcodes_static_in_frontend_head", we did the same :
do_shortcode($post->post_content);

**Comment by moldcraft** [comment]
I know...

If you will find a solution for this, let us know.

**Comment by maiakhoa** [comment]
yes, Thanks for your feedback
