### ISSUE TITLE
Unyson page builder doesn't work

### ISSUE THREAD

**Issue by Adriana1359** [ThemeFuse/Unyson#3752]
Hi,
The Unyson page builder doesn't work anymore, even if I create a new page and edit something with Unyson it doesn't save the work.

All my pages are created with the builder and I can't even edit them anymore.
I used the theme acommodation, and I saw that the theme was removed from Envato market.

I'm waiting for a solution.
Thank you,

**Comment by qutub-bharmal** [comment]
I have the same issue, I checked the console it gives JS error:

`Uncaught TypeError: wp.editor.removep is not a function`

screenshot: https://prnt.sc/mu3gkv

JS file: https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/wp-editor/static/scripts.js#L89

It gives the error when we edit the TinyMCE editor text from page meta section and then update the page. it works fine in text shortcode of the editor.

I am using Eventastic theme and only Unyson plugin is activated.

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/113#issuecomment-470149512

**Comment by kcarissimi** [comment]
Were you able to resolve this? My clients are having the same issue.
