### ISSUE TITLE
can not create slider type in slider extension

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#376]
When I created slider in framework-customization folder, it show an error:
<pre>
Fatal error: Extension "slider" is already defined in "/srv/www/culinier/htdocs/wp-content/plugins/unyson/framework/extensions/media/extensions/slider" found again in "/srv/www/culinier/htdocs/wp-content//themes/culinier/framework-customizations/extensions/slider" in /srv/www/culinier/htdocs/wp-content/plugins/unyson/framework/core/components/extensions.php on line 166
</pre>
I'm using the latest version of Framework.

**Comment by moldcraft** [comment]
Check this issue, maybe you will find an answer https://github.com/ThemeFuse/Unyson-Sliders-Extension/issues/9

**Comment by llemurya** [comment]
@duongancol try create your extension in `framework-customizations/extensions/media/extensions/slider/extensions/` not in `framework-customizations/extensions/slider/extensions/`, the difference is that `media` folder is missing. Soon we will update the documentation ,Sorry for this wrong description in the documentation.

**Comment by duongancol** [comment]
Got it, thank you guys, hope it will be fixed soon

**Comment by danyj** [comment]
Am I reading this right ? So the override folder for all extensions should be 


    framework-customizations/extensions/media/extensions/


and NOT

    framework-customizations/extensions/

or is this just for slider?

**Comment by duongancol** [comment]
It's just for slider extension

**Comment by llemurya** [comment]
@danyj  It's just for the slider extension as @duongancol said.
