### ISSUE TITLE
Can't delete Page or Post in admin while Unyson activated

### ISSUE THREAD

**Issue by dameer** [ThemeFuse/Unyson#377]
I don't know whether you noticed or not, there's no Trash for Pages and Posts in WP Admin when Unyson activated. And if you try to delete the page (trash it) - it just stays put. Tho, WP does the message about page being deleted, however it never happens.

**Comment by danyj** [comment]
You sure you dont have some other plugin doing that ? 
http://prntscr.com/6i7y1d
I just tested and delete works fine

**Comment by dameer** [comment]
Yeap, here's my screenr: https://www.screenr.com/U6fN

Does it have anything to do with my PHP version on my server that is 5.5.19 ?

**Comment by danyj** [comment]
Not sure, im on 5.4, 5.3, did not test on 5.5 till now

**Comment by GheorgheP** [comment]
Hi, @dameer, hi @danyj 

I will investigate this and give you an answer. 
Just 2 questions.
 - Did you test this on a default wordpress theme?
 - Did you test this by deactivating all other plugins/theme features?

**Comment by dameer** [comment]
Yeap, it was me screwed it up in code, no problem persist with the default WP theme. My apologies for the false alarm!
