### ISSUE TITLE
"Warning: include(): Filename cannot be empty in"

### ISSUE THREAD

**Issue by PatrikSelin** [ThemeFuse/Unyson#378]
Warning: include(): Filename cannot be empty in /home/patrikselin/public_html/wp-content/themes/materialwp-materialwp/framework-customizations/extensions/portfolio/static.php on line 9

Warning: include(): Filename cannot be empty in /home/patrikselin/public_html/wp-content/themes/materialwp-materialwp/framework-customizations/extensions/portfolio/static.php on line 9

Warning: include(): Failed opening '' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/patrikselin/public_html/wp-content/themes/materialwp-materialwp/framework-customizations/extensions/portfolio/static.php on line 9

When I downloaded the Unyson extensions, and then the error message appeared. What should I do?

**Comment by GheorgheP** [comment]
Hi,

Replace this code from line 9:
``` php
include $other_existing_paths['framework'];
```
And replace with this code:
``` php
fw_include_file_isolated( fw()->extensions->get( 'portfolio' )->get_path( '/static.php' ) );
```
