### ISSUE TITLE
fw.soleModal backdrop not showing

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#379]
I see that backdrop is set in fw.soleModal
https://github.com/ThemeFuse/Unyson/blob/31abfab92d44d38b5f59966f6b9db2988eefd4be/framework/static/js/fw.js#L1223

but it is not showing up

			fw.soleModal.show('show_modal', modal_html, {
				autoHide: 1500,
				allowClose: false
			});

also is there a callback function for it ?

**Comment by moldcraft** [comment]
That was designer's decision to make it transparent.

**Comment by moldcraft** [comment]
> is there a callback function for it ?

event/callback on open and close?

**Comment by danyj** [comment]
yes, so that I could do something like 


	fw.soleModal.show('show_modal', modal_html, {
		autoHide: 1500,
		allowClose: false
	},function(){
	
	 // is open do somethig
	});
	
	
	
	fw.soleModal.close('show_modal',function(){
	
	 // is closed do somethig
	});

**Comment by moldcraft** [comment]
Hi, sorry for that late reply. Download the latest github version of Unyson and try in console this code:

```javascript
fw.soleModal.show('1', 'Hello 1', {
    afterOpen: function(){ console.log('Open 1'); },
    afterClose: function(){ console.log('Close 1'); }
});
fw.soleModal.show('2', 'Hello 2', {
    afterOpen: function(){ console.log('Open 2'); },
    afterClose: function(){ console.log('Close 2'); }
});
```

**Comment by moldcraft** [comment]
Feel free to reopen this if something is not working as expected.
