### ISSUE TITLE
[Unyson Docs] Niste lucruri care trebuie facute/discutate

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#380]
Salut,

Avem asa la Unyson Docs:

1.  De facut template-ul default cu header mai mic ceva de genul asta: http://joxi.ru/D2PyVNgikxEwA3 (uite un export cu care m-am jucat eu doar ca nu am pus search-ul ca nu stiu cum: https://dl.dropboxusercontent.com/u/10589764/UnysonDocs%20Template.zip)

2. ~~De sters toate articolele vechi de la import si pus astea noi~~

2. (de stabilit care intra la import si care nu, da-mi un semn sa stabilim impreuna).

3.  De implementat un serach la media - http://joxi.ru/DrlM7xKhVLkNmP (am incercat sa inlocuiesc cateva imagini, a trebuit sa merg pagina cu pagina sa le gasesc)

4.  Nu exista o metoda usoara sa importi toate articolele dintr-un proiect si sa poti sa le modifici creand astfel un articole noi. Avand in vedere standardizarea, noi o sa avem documentatii in principiu la fel pentru toate proiectele, dar o sa difere pozele in anumite articole cum ar fi majoritatea articolelor de shortcodes. Cum pot eu sa import articolele si doar sa schimb pozele? Da-mi un semn sa vorbim mai mult despre asta. 

5.  De adaugat posibilitatea de selectie a tuturor articolelor: http://joxi.ru/a2XYajlCw5OPAg

6. Cred ca functionalitatea din meniu ar trebui sa fie la fel la Projects cum e la Articles: http://joxi.ru/4AkE0XLioE43mq

7. Link pe numele proiectului > te duce la edit project: http://joxi.ru/bmob6yRc3v8ory

8. Link pe numele articolelor > te duce la detalii articol: http://joxi.ru/xAeXNZyTRxOa2y

9. Link pe numele FAQ > te duce la detalii FAQ: http://joxi.ru/1A5JQELUDy3RrE

10. De regandit afisarea pe dashboard http://joxi.ru/KAxMd0phZXOZr8 poate de adaugat si niste explicatii scurte despre ce o sa gaseasca userii in video-uri

11. De trecut prin video-uri si aranjat textul

12. Culoarea asta de la meniu inchis http://joxi.ru/L21Jpg5URy10AX ar trebui sa fie la fel ca la meniu deschis http://joxi.ru/12Mx7ygClbNLmJ

13. De implementat icon selector in admin http://joxi.ru/52aeNWXHE3pY20 ca sa putem selecta usor icons

14. Pop-up-ul de login tre sa fie in centrul ecranului: http://joxi.ru/Y2LDp1lT7J0a26

15. Themes - http://joxi.ru/gmvV6M1TvbJ1ma

16. De scos categoria standard de la FAQ - http://joxi.ru/n2Y0RpLUZ6dym6 astfel daca nu avem nici o categorie adaugat de user, sectiunea FAQ din home sa nu apara

17. Cred ca trebuie creat un nou mod de import cu o filtrare cumva - http://joxi.ru/8238nGWcDjGkAO e clar ca daca ai multe articole si topics cum e acum e greu de folosit

18. Pagina de 404 din site-ul themefuse, trebuie scoasa - http://joxi.ru/L21Jpg5UgxgYAX. Ar trebui sa ramana doar pagina de 404 standard de la unyson http://joxi.ru/MAje7ndHxOkk2e

**Comment by danyj** [comment]
Sure , lets address it, but I  dont understand it. Or should this have been a private conversation?

**Comment by sergiubagrin** [comment]
@danyj - Yes. It is for our internal use.

> 2. De sters toate articolele vechi de la import si pus astea noi

Done

**Comment by DimiBaitanciuc** [comment]
@danyj - don't worry about it, this is something we need to do for Uyson Docs. All the issues that are of general interest are and will be written in English ;)

**Comment by danyj** [comment]
@sergiubagrin @DimiBaitanciuc   I understood that when it was posted. Dont take this personal please , we all are multilingual but in a public repo not speaking common language seems unfair to others. Imagine developers in Wordpress /Drupal/Joomla repos not speaking the lang you understand. I have a forum of 100K+ Joomla users , 5 devs and we all speak same lang when addressing public. For private things we have private channels and speak our native language there. Again nothing personal but everyone watching this repo got the notification saying "Things we need to address" and it ends up being something else. And third time, do not take it personal.

**Comment by DimiBaitanciuc** [comment]
Makes sense, I'll close this one, and continue privately. I never take it personally, no worries.

**Comment by sergiubagrin** [comment]
1. http://joxi.ru/l2ZYnzKCE5xLmJ
