### ISSUE TITLE
[Template Error] Can't find variable: objectives_title

### ISSUE THREAD

**Issue by ioandrozd** [ThemeFuse/Unyson#3821]
Hi community, i need your help, I have read the manual but I don't check the bug.

I get this error if I create new element in Shortcodes
<div class="content">[Template Error] Can't find variable: objectives_title</div>

see the screenshot
<img width="942" alt="image" src="https://user-images.githubusercontent.com/7299019/60754011-5b4df280-9fdb-11e9-9472-3f68009cb0a4.png">

**Comment by klvmedia** [comment]
Hey there,

How is your code looking? You should have something like this -

`'careers' => array(
		'type'          => 'addable-popup',
		'label'         => esc_attr__( 'Careers', 'usl' ),
		'popup-title'   => esc_attr__( 'Add/Edit Careers', 'usl' ),
		'desc'          => esc_attr__( 'Add new job', 'usl' ),
		'template'      => '{{=title}}',
		'popup-options' => array(
			'icon-group' => array(
				'type'    => 'group',
				'options' => array(
					'title' => array(
						'type'  => 'text',
						'label' => esc_attr__('Job Title', 'usl')
					),
					'content'       => array(
						'label' => esc_attr__( 'Job Description', 'usl' ),
						'desc'  => false,
						'type'  => 'wp-editor',
					),
				),
			),
		),
	),`

**Comment by ioandrozd** [comment]
Thank You, I have change:
 `'template' => '{{=title}}',` and it`s working.

I have use before with minus {{-title}}
