### ISSUE TITLE
Unyson Causing Issues with LogIn

### ISSUE THREAD

**Issue by nunsarch1** [ThemeFuse/Unyson#3836]
I have a Wordpress 5.2.2 site running Philanthropy child theme with Unyson 2.7.22 framework. Recently my non-admin users started getting the white screen of death when they tried to log in. My host believes Unyson is causing the problem and deactivated the plugin completely. This fixed the back-end problem but completely broke the front-end of my site and caused all the pages that had been created with Unyson to initially return not found or file removed/renamed errors then 500 errors. I restored a back-up and reactivated the plug-in which resolved the front-end issues but my non-admin users are once again having log-in issues. Any suggestions on how to resolve this issue without having to rebuild the pages with a different page builder?

**Comment by danyj** [comment]
Contact your theme provider. That is where your host should start, not Unyson

**Comment by nunsarch1** [comment]
Thanks! I have reached out to them and they are responding!
