### ISSUE TITLE
Error: multi-select option with population

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#384]
Hi!
I used multi-select option with list of users and posts, but it didn't work.
here is my code: 
<pre>

'demo_multi_select_posts'      => array(
				'type'       => 'multi-select',
				'label'      => __( 'Multi-Select: Users', 'unyson' ),
				'population' => 'users',
				'source'     => array('author')',
				'desc'       => __( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
					'unyson' ),
				'help'       => sprintf( "%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
					__( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
						'unyson' ),
					__( 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
						'unyson' )
				),
			),
</pre>

**Comment by duongancol** [comment]
Is there any fixes?

**Comment by duongancol** [comment]
I updated the plugin and the multi-select still did not work with users and posts

**Comment by moldcraft** [comment]
@duongancol the fix is not included in the latest release yet, so when you update the plugin from wordpress admin it will not contain the fix. We will create a new release later. Until then, you can [download](https://github.com/ThemeFuse/Unyson/archive/master.zip) and install the plugin manually in `wp-content/plugins/unyson/`

**Comment by duongancol** [comment]
hi @moldcraft : I did clone unyson framework and replaced to wp-content/plugin/unyson. It still did not work.

**Comment by GheorgheP** [comment]
Hi,

By what name are you searching for? Now the option is made to search by user `user_nicename`

**Comment by duongancol** [comment]
@GheorgheP : It worked for me.
One more question, is there any way to list all usesr when I click to input tag? I mean not by searching. 
It look like when you set population with array. I think it more convenient. For example my site has a lot of user. It's quite difficult to remember user's nick name

**Comment by GheorgheP** [comment]
Hi,

In this case just use the population as array, and in `choices` set a function that will return all users and that's all.

In future we plan to add functionality with pre-population with some items ( posts, terms, posts ), but this is not that you, as it will populate with a limited number of items.

**Comment by duongancol** [comment]
Hope it will be released soon!. Thanks
