### ISSUE TITLE
rgba-color-picker not returning default value 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#385]
rgba-color-picker is not returning default value when options are reset

		'option_name'  => array(
			'type'  => 'rgba-color-picker',
			'value' => '#f7f7f7',
		),

is empty, if this option is switched to color-picker it returns #f7f7f7

**Comment by danyj** [comment]
checking against isset instead of empty fixes this 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/class-fw-option-type-rgba-color-picker.php#L54


		if ( ! isset( $input_value ) ) {....

**Comment by valeriuzdrobau** [comment]
Thanks @danyj

**Comment by danyj** [comment]
any time bud , thnx for helping me on my issues.
