### ISSUE TITLE
Bug: Page Builder extension and WooCommerce

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson#388]
Hi there,
You can run the test with steps:
1. Install latest version of <code>scratch-parent</code> theme, install Unyson, then install WooCommerce.
2. Open Shop page (front-end), try to add some products to cart.
3. Go to Cart page, enter random code into Coupon field, then apply it and you will see everything working just fine (showing error message if the code is wrong).
4. Go to back-end and install Page Builder extension, then try step 3 again, you won't see any message that should be displayed.
This bug is also on my theme.
Any helps would be appreciated. Thanks !

**Comment by nickkuijpers** [comment]
Same problem with [woocommerce_one_page_checkout template="product-list" product_ids="25"] Woocommerce One Page Checkout.

**Comment by nickkuijpers** [comment]
Fixed when adding [[woocommerce_one_page_checkout template="product-list" product_ids="25"]] after reading code. Thanks!

**Comment by nickkuijpers** [comment]
Nope, sorry, still isn't working :(

**Comment by nickkuijpers** [comment]
The problem also exists when disabling the page builder, if i disable de plugin completely, it works. At the default theme the problem also exists.

**Comment by danyj** [comment]
@nickkuijpers  did you download and install the latest , builder, shortcode and unyson ? 
not the releases but masters ?

**Comment by nickkuijpers** [comment]
I've installed thru Wordpress Plugins. Is there a other posibility?

**Comment by nickkuijpers** [comment]
I've installed Version 2.2.7

**Comment by danyj** [comment]
yes and that is why you still have a bug , 
the fix that was added was after the latest release, 
download the masters 
Unyson https://github.com/ThemeFuse/Unyson/archive/master.zip
Shortcode https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/archive/master.zip
Page builder https://github.com/ThemeFuse/Unyson-Builder-Extension/archive/master.zip


extract and replace 

Unsyon is in 

    plugins/unyson 
  
Shortcode 

    plugins\unyson\framework\extensions\shortcodes

Builder

    plugins\unyson\framework\extensions\shortcodes\extensions\page-builder

**Comment by nickkuijpers** [comment]
Thanks! Downloading it now, right before u send me the message, Didn't know that. Thanks for the info. be right back!

**Comment by nickkuijpers** [comment]
Fatal error: Cannot redeclare class FW_Option_Type_Builder in /home/revengegif/domains/revengegift-dev.nl/public_html/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/option-types/builder/extends/class-fw-option-type-builder.php on line 451 :/

**Comment by nickkuijpers** [comment]
I install unyson with page builder, then i go to then maps and replace the current files with the masters. Is that right?

**Comment by danyj** [comment]
you must have mixed up the folders, I used the masters yesterday and they work fine, delete and try again ,

copy unyson master first 
dont install/uninstall

**Comment by nickkuijpers** [comment]
Oké but when i dont install them from unyson dashboard, they wont get activated. Will try again. brb

**Comment by danyj** [comment]
do this than 

install unyson  via plugins , activate all your extensions 


than 
copy paste masters ,   unyson,shortcodes,builder

**Comment by nickkuijpers** [comment]
Yep, i did. Its giving me that error. Would you like to take a look? I will send u FTP. Got a email?

**Comment by nickkuijpers** [comment]
Trying again with no install from Wordpress. brb

**Comment by nickkuijpers** [comment]
Unyson master installed, no problems. Now adding shortcodes.

**Comment by nickkuijpers** [comment]
Installed Shortcodes, no probs.

**Comment by nickkuijpers** [comment]
Installed page-builder, all no problem but i cant active them in Unyson Dashboard and i cannot install them anymore.

**Comment by nickkuijpers** [comment]
- Cannot active hidden standalone extension Shortcodes

**Comment by moldcraft** [comment]
Check if php has permissions to read directories that you extracted from zip. Or set recursive chmod 755 manually

**Comment by nickkuijpers** [comment]
Nope, made the whole plugin 777 for testing but still the same error. Got any other ideas? When will new 2.2.8 be released?

**Comment by moldcraft** [comment]
Zip your wp-content/plugins/unyson/ directory and send me to `unyson[at]email.com`

**Comment by nickkuijpers** [comment]
Send!

**Comment by moldcraft** [comment]
You have only the shortcodes and page-builder extension there. But they requires other extensions. To install all requirements manually it's to much work to do. Instead, delete all extensions then install PageBuilder from Unyson admin page, the installation script will install all requirements. Then repeat [the procedure](https://github.com/ThemeFuse/Unyson/issues/388#issuecomment-94274104)

**Comment by nickkuijpers** [comment]
Thanks for checking out. I've done that but then i get the following error: 

Fatal error: Cannot redeclare class FW_Option_Type_Builder in /home/revengegif/domains/revengegift-dev.nl/public_html/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/option-types/builder/extends/class-fw-option-type-builder.php on line 451

**Comment by moldcraft** [comment]
[The PageBuilder extension has no `/includes/option-types/builder` directory](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/tree/1bfd3147baa19f1911c0910f2ca4ea76e06932e0/includes)
So I think you extracted/copied the files in the wrong place

**Comment by danyj** [comment]
i did that 2 days ago thus I gave you right paths , the builder is located in  shortcodes/extensions folder and his folder name is not builder but page-builder ,  check the paths I gave you again

**Comment by nickkuijpers** [comment]
I think its working, Dayj, you've giving me the following path but this wasn't the right one, this is the right one right?

plugins/unyson/framework/extensions/builder

Builder

plugins\unyson\framework\extensions\shortcodes\extensions\page-builder

**Comment by moldcraft** [comment]
[Shortcodes](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension)

    plugins\unyson\framework\extensions\shortcodes

[Page Builder](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension)

    plugins\unyson\framework\extensions\shortcodes\extensions\page-builder

**Comment by nickkuijpers** [comment]
Well i've try'd it all but WooCommerce One Step Checkout still ain't working. Think its a bug somewhere. When i place the shortcode in the normal page editor its working, but when i paste it in the page builder its not working. It shows but the extra ajax requests with payments etc isn't showing. After installing the master files, the error of not showing at all is gone but there are new bugs.

**Comment by nickkuijpers** [comment]
![schermafbeelding 2015-04-19 om 23 12 41](https://cloud.githubusercontent.com/assets/5340923/7221394/a1e23652-e6e9-11e4-80de-82392da22d55.png)
![schermafbeelding 2015-04-19 om 23 12 22](https://cloud.githubusercontent.com/assets/5340923/7221395/a1e65980-e6e9-11e4-9569-b1d338789bc4.png)
![schermafbeelding 2015-04-19 om 23 14 11](https://cloud.githubusercontent.com/assets/5340923/7221400/d082a10e-e6e9-11e4-81da-c350006eecca.png)
![Uploading Schermafbeelding 2015-04-19 om 23.13.26.png . . .]()

**Comment by nickkuijpers** [comment]
![schermafbeelding 2015-04-19 om 23 13 26](https://cloud.githubusercontent.com/assets/5340923/7221406/f2542c80-e6e9-11e4-8690-4b89e5a811de.png)

**Comment by nickkuijpers** [comment]
1st and 2nd image are working, third and fourth arent.

**Comment by danyj** [comment]
the paths I gave you are correct.  

and you have #424

**Comment by nickkuijpers** [comment]
No that aint the problem. The problem is WooCommerce wont load the Ajax or something in the visual page editor. Please install WooCommerce One Step Checkout and try it out. There is a difference between normale page editor and visual page editor. It is missing elements like the count of products and the payment methods. Those are loaded in afterwards the page is loaded.

**Comment by GheorgheP** [comment]
Hi,

We contacted the WooCommerce team and asked for Woo Plugins dev access, waiting for the response.

We will try to solve as soon as possible.

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/20
