### ISSUE TITLE
[suggestion] Create global fw js event.

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#390]
Can you please create one time global fw event , something like this 

    fw:options:init

but to fire once after everything is being loaded and to bind elements added via js or ajax. Basically something like 

    jQuery.on(....

reason why is that you killed the on even with fw:options:init since all options js is wrapped inside of it, and nothing works with jquery default on event , you can test simple 

    $(element)on('click'    

after you hit reset button it wont fire. It has to be wrapped. 
and , 

    fwEvents.on('fw:options:init'...

fires multiple times ( so I was told ). 

I am not looking for this either 

    $(document.body).on('something, 'element'

I am calling several js classes , and inside of them I am using on to bind some arrays with data and it is pain to use that.  So please give us a replacement for jQuery.on.

**Comment by moldcraft** [comment]
Have you tried 

```
fwEvents.on('fw:options:init', function(data.$elements){
    data.$elements.find('#your-element')....
});
```

?

Or you can try `fwEvents.one('fw:options:init', ...` *(but the better solution is the above)*

**Comment by danyj** [comment]
yes I am using fw:options:init , and it works , but I cant find the post where I mentioned this method and I think you or someone from the team advised not to use it since it fires more than once,

**Comment by moldcraft** [comment]
[Similar reply](https://github.com/ThemeFuse/Unyson/issues/340#issuecomment-78112097)

> but I cant find the post where I mentioned this method and I think you or someone from the team advised not to use it since it fires more than once

[Here it is](https://github.com/ThemeFuse/Unyson/issues/327#issuecomment-77691083). But there is a difference, there you did

```javascript
fwEvents.on('fw:options:init', function (data) {
    /**
     * The `fw:options:init` is fired multiple times for different elements
     * but you select the same element on the page every time
     */
    var $range = $("#fw-option-get_styles-base-tm_tl_height input");
});
```

but here I recommended this

```javascript
fwEvents.on('fw:options:init', function (data) {
    /**
     * The `fw:options:init` is fired multiple times for different elements
     * but you search your element only in currently initialized elements (not in the entire page)
     */
    var $range = data.$elements.find("#fw-option-get_styles-base-tm_tl_height input");
});
```

**Comment by danyj** [comment]
ah ok than , we are good to go, closing this.
