### ISSUE TITLE
disable extension in slider 

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#391]
How can I disable owl-carousel extension in slider?
I tried to edit manifest.php in framework-customization/extension/media/slider/extension/owl-carousel/:
<pre>
$manifest = array();
$manifest['name']        = __( 'Owl Slider', 'fw' );
$manifest['description'] = __( 'Owl Slider', 'fw' );
$manifest['version'] = '1.0.0';
$manifest['display'] = false;
$manifest['standalone'] = false;
$manifest['thumbnail'] = null;
</pre>
But it didn't work.

**Comment by duongancol** [comment]
I also tried to change preview and thumb images, but nothing happen.

**Comment by llemurya** [comment]
Please try this solution : 
```add_filter( 'fw_ext_slider_activated' , function($sliders){
			$key = array_key_exists('owl-carousel', $sliders);
			unset($sliders[$key]);
			return $sliders;
		});```

**Comment by duongancol** [comment]
it worked, thank you!

**Comment by duongancol** [comment]
Sorry, It disable bx-slider in default, I just want to disable owl-carousel slider.

**Comment by llemurya** [comment]
@duongancol , try this solution ```add_filter( 'fw_ext_slider_activated' , function($sliders){ $key = array_search('owl-carousel', $sliders); unset($sliders[$key]); return $sliders; });```

**Comment by llemurya** [comment]
replace `array_key_exists` with `array_search`

**Comment by duongancol** [comment]
Yeah, it's all I want, but as I said that, I couldn't change preview and thumb of bx-slider extension.

**Comment by llemurya** [comment]
@duongancol  please create your slider in `framework-customizations/extensions/media/extensions/slider/extensions/bx-slider` and replace your preview and thumb from `static/images`

**Comment by duongancol** [comment]
I tried but It still loaded default images.

**Comment by llemurya** [comment]
your images must be names `preview.jpg` and `thumb.jpg`

**Comment by duongancol** [comment]
Yes, I added 2 images with exact name like preview.jpg and thumb.jpg in bx-slider/static/images folder of<pre> framework-customizations/extensions/media/extensions/slider/extensions. </pre>
It still loaded the default images.

**Comment by llemurya** [comment]
@duongancol ,yes you are right. I already fixed this bug. It will be released on v.1.1.7 of slider on 25.03.2015. Thanks for bug report.

**Comment by duongancol** [comment]
@llemurya : I'll wait for that. Thank you!

**Comment by duongancol** [comment]
@llemurya some of my customers got the problem with function:
<pre>
add_filter( 'fw_ext_slider_activated' , function($sliders){ $key = array_search('owl-carousel', $sliders); unset($sliders[$key]); return $sliders; });
</pre>
It shows an error with that function :<pre>
Parse error: syntax error, unexpected T_FUNCTION
</pre>
Any suggestion?

**Comment by llemurya** [comment]
@duongancol I give this example as a demo , you may know that anonymous functions in php versions below 5.3 is not supported as you can see above in the comments I edited that in order to be compatible with all versions please take a look at that comment.
