### ISSUE TITLE
Creating custom extension through Plugin

### ISSUE THREAD

**Issue by akshaya-rane** [ThemeFuse/Unyson#394]
Hi,

I have created plugin with following structure,

`<plugin_folder_name>/framework-customizations/extensions/<extension_name>`

I have added below code in main plugin file,
```
function _wdm_filter_my_plugin_extensions($locations) {
$locations[dirname(__FILE__) . '/framework-customizations/extensions/'] = plugin_dir_url( __FILE__ ) . 'framework-customizations/extensions/';
	return $locations;
}
add_filter('fw_extensions_locations', '_wdm_filter_my_plugin_extensions');
```
If I add extension, in theme 'extensions' folder, it worked well. 

Can you please give a step by step approach for creating extension via a plugin?

**Comment by moldcraft** [comment]
Create directory `<plugin_folder_name>/extensions`

```php
function _wdm_filter_my_plugin_extensions($locations) {
    $locations[dirname(__FILE__) . '/extensions'] 
    =
    plugin_dir_url( __FILE__ ) . 'extensions';
    
    return $locations;
}
add_filter('fw_extensions_locations', '_wdm_filter_my_plugin_extensions');
```

**Comment by akshaya-rane** [comment]
Thank you.

**Comment by moldcraft** [comment]
> If I add extension through plugin, will it be visible in Unyson 'Available' / 'Active' extension list.

Sorry, at the moment no *(I forgot about that)*. I am fixing this right now.

**Comment by moldcraft** [comment]
Please [download the latest Unyson dev version](https://github.com/ThemeFuse/Unyson/archive/master.zip), extract in `plugins/unyson/` and let me know if plugin extensions are visibile on the Unyson Extensions page.

**Comment by moldcraft** [comment]
P.S. To set extension image, add this in manifest

```php
$manifest['thumbnail'] = 'http://placehold.it/256x256&text=hello';
```

**Comment by duongancol** [comment]
Hi @moldcraft 
I followed above step to create extension from plugin folder. 
It worked well but it had problem with other extension function for example: fw_ext_feedback_stars_get_post_rating().

It showed: 
<pre>
Fatal error: Call to undefined function fw_ext_feedback_stars_get_post_rating() in /plugins/ht-recipes/extensions/recipes/views/single.php on line 124
</pre>
Any suggestions?

**Comment by moldcraft** [comment]
>     Fatal error: Call to undefined function fw_ext_feedback_stars_get_post_rating() in /plugins/ht-recipes/extensions/recipes/views/single.php on line 124

Before calling any extension function, first you need to check if it is enabled/exists

```php
if (fw_ext('extension_name')) {
   fw_ext_extension_name_whaterver_function();
}
```

**Comment by duongancol** [comment]
Thanks for your help!

**Comment by akshaya-rane** [comment]
Hi,

Sorry for the delay.

I checked with new version, it works well. Great !!

**Comment by martin-bede** [comment]
Hi, I'm just about to implement this so my shortcodes are in a plugin rather than the framework-customizations folder.

When I submit my theme to ThemeForest would I just include the plugin with the theme and let the user install my plugin when setting up the theme or must the plugin be hosted with WordPress.org in their plugin directory?

Thanks

**Comment by moldcraft** [comment]
Included

**Comment by martin-bede** [comment]
Thanks

**Comment by martin-bede** [comment]
Is there anyway I can have more than one plugin with shortcodes? I'm wanting to have one plugin which contains core shortcodes which I'm going to reuse on each theme. I then want another plugin with theme specific shortcodes tailored to the themes genre.

As far as I'm aware I can't use the `fw_extensions_locations` filter on more than one plugin.

Is there a way I can achieve this?

**Comment by moldcraft** [comment]
You can use the filter how much you want, in any plugin you want (No limits/restrictions)

----

For e.g. you can have multiple directories with extensions in the same plugin:

```php
function _wdm_filter_my_plugin_extensions($locations) {
    $locations[ dirname(__FILE__) . '/core-extensions' ] 
    =
    plugin_dir_url( __FILE__ ) . 'core-extensions';

    $locations[ dirname(__FILE__) . '/theme-extensions' ] 
    =
    plugin_dir_url( __FILE__ ) . 'theme-extensions';

    return $locations;
}
add_filter('fw_extensions_locations', '_filter_{plugin-id}_extensions');
```

**Comment by Shahab2905** [comment]
Hi,

It seems we can only declare shortcodes in one extension at a time, if loaded from the plugins.

Example:

we have a plugin which loads one extension name 'our-core' and also shortcodes ( 'our-core-shorcode' )

Now lets create another plugin and load another extension name 'our-core-secondary' and also shortcodes ( 'our-core-secondary-shortcode' )

Both extensions are being loaded via two different plugins but only one will support shortcodes. not both? Unless the extension name is the same.

How can we have multiple plugins with its own extensions and its own shortcodes, as it seems only one plugin can support shortcodes at a time, the second is simply ignored for shorcodes.

Any help is appreciated @moldcraft

**Comment by moldcraft** [comment]
@Shahab2905 I created 2 plugins with one shortcode in each, everything works fine

![1479893110764](https://cloud.githubusercontent.com/assets/1475489/20556387/84876468-b16f-11e6-83b7-cf58636a7a1f.jpg)

You can test the plugins on your side
[Download](https://github.com/ThemeFuse/Unyson/files/608472/p1-and-p2-plugins.zip)

**Comment by Shahab2905** [comment]
@moldcraft Thank you, Indeed its is working. 

I will look into my code again and see whats been done wrong.
