### ISSUE TITLE
After update framework my shortcodes not displyed in visual editor

### ISSUE THREAD

**Issue by xpeeder** [ThemeFuse/Unyson#395]
Hi
Today i have updated framework with latest version. and i saw my shortcodes which i customised and create newly all are gone. only showing which available with plugin.

is there i am missing something ?? i have update direct from update now button.

Thanks

**Comment by llemurya** [comment]
@xpeeder Where you create your shortcodes? In `framework/extensions/shortcodes/shortcodes` or in `framework-customizations/extensions/shortcodes/shortcodes`

**Comment by xpeeder** [comment]
I am using same structure in scratch theme
<pre>framework-customizations/extensions/shortcodes/shortcodes</pre>

**Comment by llemurya** [comment]
@xpeeder thanks for feedback. We will fix it.

**Comment by xpeeder** [comment]
@llemurya  Thank you brother. 
I am really disappointed. 90% work already done.
today when i saw changelog in framework.  i just update to see whats change last few update ( my version was 2.1.14). mainly i like to see group order. 

hope your team will fix this asap .

Thanks again

**Comment by llemurya** [comment]
I tested an for me it works. You updated the shortcodes extension, please look what version of shortcodes you have in manifest file, my version is v1.2.10.

**Comment by xpeeder** [comment]
from plugin shortcode folder manifest file 'version' => '1.2.9',

**Comment by llemurya** [comment]
Please make update for shortcodes extension and give us a feedback if it works .

**Comment by xpeeder** [comment]
@llemurya  Its work with v1.2.10. 
but i am not satisfied this way. When people update framework they dont update manually again others extension. 
So that time your update framework not compatible with some old extension file which also need update with framework.  better add together or if need update any extension with new version. it will show a popup message: this extension should be update with new version.
Or add  same text on extension.  Compatible with your current framework. or this extenstion not Compatible with your current framework please update this extension .

You have better experince then me :) when something wrong happened buyer try to kill us :D every time not possible to login his dashboard to update my self or check this kind of issue.
it will be better if we embed framework with theme :(. but still TF not accept embed your framework.
 
BTW Thank you so much for this help. :)

**Comment by llemurya** [comment]
@xpeeder I understand your warning , it is argumented, we will add your suggestion in new features. Thanks for feedback!
