### ISSUE TITLE
Can't open website - wordpress login opening instead

### ISSUE THREAD

**Issue by LaraChap** [ThemeFuse/Unyson#3956]
Hi there!
I'm building a website on wordpress. I used the woffice theme and this theme only works with Unyson. When Unyson isn't installed, i can't access the website (it says the page is under construction). When Unyson is installed and I try to access my website by putting the domain in my browser, it automatically asks me for my wordpress login (without putting /wp-admin in the domain). This means that no one can access my website. Anyone know how to fix this problem?

**Comment by dwinterhalter72** [comment]
What did you do to fix this?
