### ISSUE TITLE
"fw-flash-messages" logic

### ISSUE THREAD

**Issue by dameer** [ThemeFuse/Unyson#397]
Been playing around with form builder a little bit and have noticed a couple of really weird things...

(1) some of the input fields (like text or website) are validated in place by displaying some sort of pop-overs which is OK

(2) another inputs (like email) use different logic because validation message gets displayed in ".fw-flash-messages" DIV element. The worst of all is that DIV with the class ".fw-flash-messages" gets kinda randomly nested (for no special reason it's showed up above site logo).

So, is there a way to uniform these two because it might be really confusing for people?

I have also noticed that ".fw-flash-messages" DIV is hardcoded in "framework/helpers/class-fw-flash-messages.php" and can't be overwritten in "framework-customizations".

**Comment by moldcraft** [comment]
> (1) some of the input fields (like text or website) are validated in place by displaying some sort of pop-overs which is OK
> 
> (2) another inputs (like email) use different logic because validation message gets displayed in ".fw-flash-messages" DIV element. 

(1) is done by default by browser, this is just the `<input required ... />` attribute.

----

Here is how form errors are displayed:

1. The `FW_Form` script [check if errors were not accessed/displayed](https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/helpers/class-fw-form.php#L526-L529) then move them to flash messages.
2. The `FW_Flash_Messages` script [check if messages were not accessed/displayed](https://github.com/ThemeFuse/Unyson/blob/c663745acd83b206f3c86a65f3eecca2c3c92b62/framework/helpers/class-fw-flash-messages.php#L236-L238) then try to find a div on the page closer to the content and inject them in it.

I did not found a better solution to display form errors and flash messages by default. Also there is no explanation in the docs about how to customize both in your theme, sorry about that.

----

1. Hm, for form erros I think I have an idea, I will display by default the errors [here](https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/helpers/class-fw-form.php#L360-L362) (above the form) but I will add an `add_action()` to allow theme developers to overwrite the default display (for e.g. to change form errors html). I will add that possibility today and it will be available in the [next release](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/45).
2. You can display flash messages anywhere in your theme (before the `wp_footer` action) like this

    ```php
    if (defined('FW')) { FW_Flash_Messages::_print_frontend() }
    ```

**Comment by dameer** [comment]
(1) Yeap, I know it comes from browser, I just thought it would be great to maybe omit "required" attribute (validate input instead) and make all error messages uniform. For example stack them all in ".fw-flash-messages" DIV.
No matter what, your idea about adding an action that allows overwriting of default display is great! And of course, putting it above the form is much better than trying to "guess" container ID or class name.

(2) Got it, thanks!

**Comment by moldcraft** [comment]
Here is [that action](https://github.com/ThemeFuse/Unyson/blob/24c41fcd11e1b1ff1c4f381adea5a95f418427e7/framework/helpers/class-fw-form.php#L388).

**Comment by moldcraft** [comment]
Docs: Added [info about forms and flash messages](http://manual.unyson.io/en/latest/helpers/php.html#fw-form-customize-errors)
