### ISSUE TITLE
Not able to deselect icon from icon option

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#398]
There is no way to deselect icon from icon options. 
I am using it as additional icon to be selected. If the option is empty no icon will be shown. The starting value is empty. 

	'icon' => array(
	    'type'  => 'icon',
	    'value' => '',
	    'label' => __('Select an icon', 'fw'),
	    'desc'  => __('Choose your icon', 'fw'),
	),
If selected and saved once , you cant deselect it anymore.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/145#issue-53504068
> On click you deselect an icon from this option: http://joxi.ru/p27E6pZio7kgr7. I think it will be better from the usability stand point if the hover will actually disappear when you click to deselect the icon. Another option will be to make a different color the selected icon state only: #64bd1f
> 
> How it works now is it stay the same and you don't actually know if the icon is deselected or not when you click on it (that's until you move the mouse away).

**Comment by danyj** [comment]
thnx,
