### ISSUE TITLE
vulnerability?

### ISSUE THREAD

**Issue by itxp2008** [ThemeFuse/Unyson#399]
Hi,

I've received a couple of visits from this referrer

http://sourcebox.io/6035455e4acf19612b71c4adf9c854a9/markdown

my site is http://icydiablog.com

I haven't tested the procedure and i don't know why my site is targeted with this eploit

Check the first link for details.

**Comment by danyj** [comment]
Confirmed , regular logged user can execute this
http://prntscr.com/6lxetp

this should be fixed asap.

**Comment by danyj** [comment]
This code should not run at all unless the option is in use. I don't  have the option runnable enabled anywhere. add_action should be added  only if option is enabled and not automatically 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/runnable/class-fw-option-type-runnable.php#L139
