### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by daniel89fg** [ThemeFuse/Unyson#3996]
I have installed wordpres 5.4.2, but the Unyson plugin was not working. I have seen that its maximum tested version was for wordpres 5.3.4.

So I have installed wordpress 5.3.4, and it doesn't work either.

This is the error in 5.3.4:

Se ha producido un error del tipo E_ERROR en la línea 229 del archivo /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-content/plugins/unyson/framework/includes/hooks.php. Mensaje de error: Uncaught RedisException: Connection closed in /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-content/plugins/unyson/framework/includes/hooks.php:229 Stack trace: #0 /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-content/plugins/unyson/framework/includes/hooks.php(229): session_start() #1 /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-includes/class-wp-hook.php(288): _action_fw_flash_message_backend_prepare() #2 /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters() #3 /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-includes/plugin.php(478): WP_Hook->do_action() #4 /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-admin/includes/class-wp-screen.php(412): do_action() #5 /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-admin/includes/screen.php(241): WP_Screen->set_current_screen() #6 /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-admin/admin.php(207): set_current_screen() #7 /var/www/vhosts/lavaderoelrubio.com/httpdocs/wp-admin/index.php(10): require_once('/va

**Comment by daniel89fg** [comment]
I have even tried version 4.9.4 of wordpress, watching their installation video, I realized that they used that version. Well it doesn't work either !!!

**Comment by w3bdesign** [comment]
The last update to Unyson was in 2019.

**Comment by Ruslan2205** [comment]
Everything works well for me. This time I installed it from the WordPress repository. Version WP 5.4.2, Unyson 2.7.23
