### ISSUE TITLE
Getting saved metabox values.

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#40]
Thank you for this awesome framework.However I am unable to get the meta values.How can I get the meta value of this?

``` php
    'demo_addable_option_2' => array(
        'label' => __('Addable Option', 'fw'),
        'type'  => 'addable-option',
        'option' => array(
            'type' => 'text',
        ),
        'value' => array('Option 1', 'Option 2', 'Option 3'),
        'desc'  => __('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'fw'),
        'help'  => sprintf("%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
            __('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'fw'),
            __('Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', 'fw')
        )
    ),
```

**Comment by NwpDeveloper** [comment]
Is fw_get_db_post_option() used for blog posts or can I use it to return all options in page-builder?

When I print fw_get_db_post_option(0) it returns all options for the page_id and shows 'btn_color' inside the json array. 

If I print fw_get_db_post_option(0, 'btn_color')  it returns null. 

If not how can I get the page-builder options like $atts in shortcode view?

**Comment by moldcraft** [comment]
> return all options in page-builder

It's not possible. page-builder options are available only in shortcode `view.php`

**Comment by NwpDeveloper** [comment]
Ok Thanks.
Then is fw_get_post_option() only for blog posts because it returns the current pages options if printing from the view?

**Comment by moldcraft** [comment]
Yes, `fw_get_post_option()` is only for post options (any post type, not only blog posts)
