### ISSUE TITLE
Demo content install

### ISSUE THREAD

**Issue by maod321** [ThemeFuse/Unyson#400]
When loading demo content I get the following error
Fatal error: Call to a member function quote() on a non-object in /home15/ommanage/public_html/blog/wp-content/plugins/unyson/framework/extensions/backup/includes/lib/srdb.class.php on line 608

**Comment by valeriuzdrobau** [comment]
This error is most likely because the method[ quote()](http://php.net/manual/ro/pdo.quote.php) requires PECL and you do not have it enabled. Activate extension and try again. Meanwhile we think of a solution.

**Comment by valeriuzdrobau** [comment]
Fixed in [1.0.4 realise](https://github.com/ThemeFuse/Unyson-Backup-Extension/releases/tag/v1.0.4) of [Unyson-Backup-Extension](https://github.com/ThemeFuse/Unyson-Backup-Extension).
