### ISSUE TITLE
Unyson not working since page was saved through WP Block editor

### ISSUE THREAD

**Issue by orvelus** [ThemeFuse/Unyson#4002]
Hi, I have a little problem with Unyson.
Link to website: (https://thalasso-wellness.hr/) 

So, my client wanted to update their homepage, and they did so by updating page through WordPress Block editor. They did not launch Unyson and edited the page that way, but they made changes through WP Block editor, saved the page and since then it seems as the website is crashed. I think the problem is saved page through WP editor and not Unyson (the page was created with Unyson). That may not be the source of the problem, but I don't know what else could be. 

I tried several fixes, but none of them worked for me. Tried fixes: 

- updating Unyson
- updating extensions
- switching to the TwentyTwenty theme
- deactivating all of the plugins except Unyson
- set the required properties for Unyson to work

The console is not showing any problems with Unyson, so I don't know what else to try. Please someone help, the page is broken for 3 days already and that's not acceptable. I can provide you with any required access, just want to resolve this issue.

Thanks in advance!

**Comment by 95mediawebsolutions** [comment]
@orvelus having checked your website URL the page does not seems to be broken.

**Comment by orvelus** [comment]
Yes, I found and fixed the problem in the meantime, I just forgot to close the issue. Turns out, it wasn't a theme problem, sorry for the false alarm and thanks anyway for your response.
