### ISSUE TITLE
Extension notifications

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#401]
Hi guys,

I am working on my new theme with unyson. I need the pagebuilder and porfolio extensions to be installed along with the plugin. Is there anyway to show the notification(alert) for the users (like the tgm plugin)?

Thanks

**Comment by thednp** [comment]
I know you need to edit the theme manifest file for that. You should check the documentation on theme supported extensions anyway.

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/manifest/theme.html#content

```php
// file: framework-customizations/theme/manifest.php

/**
 * Extensions compatible with the theme
 * After plugin activation, the user will be redirected to a page to install these extensions
 */
$manifest['supported_extensions'] = array(
    'page-builder' => array(),
    'porfolio' => array(),
);
```

**Comment by linjo** [comment]
Thanks guys! 
Got  it resolved. Pleas close the thread.
The support has been incredible ! Keep it up!
