### ISSUE TITLE
Unyson Pagebuilder is not showing up in back end on editing pages

### ISSUE THREAD

**Issue by zugeschmiert** [ThemeFuse/Unyson#4025]
Hi,
I used unyson pagebulder for a while, but now it is not working anymore and I don't understand why.
Normally I open a page and I can edit it with unyson pagebuilder, but since a few days, I did not see the unyson pagebuilder editor when I edit pages. Screenshot: 
The console log shows one 404 error, which can be easily deleted, when the pagebuilder is working again. The error comes from an old matomo plugin for deactivating tracking. 

Things that I tried: 
1. Wordpress and all plugins, extensions or addons are up to date
2. Tipps from user users:
Deactivate the plugin (Unyson)
Delete the plugin (in wordpress and ftp, both tested)
Delete the caches
Install Unyson again with activated Extensions Page Builder, Portfolio, Mega Menu and Backup & Demo Content

But it did not helped me. Therefore I tried the following too in combination with the above instructions:

3.  deactivated all plugins
4.  reinstalled the theme (codecanyon Unique with documentation instructions) 
5. use .htaccess with minimal wordpress settings
6. deactivated Gutenberg Editor

Do you or @ViorelEremia have any further suggestions to me?

Thank you very much in advance!

Best regards,
Norman

**Comment by Ruslan2205** [comment]
Try to decrease php version

**Comment by zugeschmiert** [comment]
@Ruslan2205 I changed it to 5.6 and 7.0 and nothing changed. The backend shows the same editor, which is not unyson.

**Comment by Ruslan2205** [comment]
Enable Debug in wp-config.php Errors may appear.  It is not very clear now.

**Comment by zugeschmiert** [comment]
I added these to wp-config, but there are not errors visible. Please see here: https://ibb.co/hRTmtdT

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);

**Comment by zugeschmiert** [comment]
The error_log file in root shows the following:
[03-Aug-2020 17:15:29 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in /home/normansc/public_html/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13
[03-Aug-2020 17:15:29 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in /home/normansc/public_html/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13
[03-Aug-2020 17:15:29 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in /home/normansc/public_html/wp-content/plugins/unyson/framework/helpers/class-fw-session.php on line 13

**Comment by Ruslan2205** [comment]
You need to specify define ('WP_DEBUG_DISPLAY', true);  so that errors are displayed on the screen.

**Comment by Ruslan2205** [comment]
You need to specify define ('WP_DEBUG_DISPLAY', true);  so that errors are displayed on the screen. In general, it seems that your visual editor is disabled somewhere in the code.

**Comment by zugeschmiert** [comment]
Sorry, I forget to change the code. I changed it to true, but there is no error visible.

**Comment by zugeschmiert** [comment]
> In general, it seems that your visual editor is disabled somewhere in the code.

How can I check it? Do you have an example code?

**Comment by zugeschmiert** [comment]
https://ibb.co/K5ykhLt

**Comment by zugeschmiert** [comment]
> In general, it seems that your visual editor is disabled somewhere in the code.

You are totally right! The visual editor was disabled within profile! Thank you so much!
I am totally happy now! :dancing_men:

**Comment by zugeschmiert** [comment]
How can I say thank you?

**Comment by Ruslan2205** [comment]
I'm glad you found the cause of the error)) I just gave a little hint)

**Comment by zugeschmiert** [comment]
The little hint, was exactly what I need today. Thank you so much, bro! I was looking for brutal errors and then it was a little checkbox. Yes, the php error is not there anymore. Debug mode disabled and php in highest mode is running and unyson is working again. :100:  :+1:
