### ISSUE TITLE
Action for option types init

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#404]
Now option types are loaded/required on every page load, even in frontend ([code](https://github.com/ThemeFuse/Unyson/blob/245699fb376df213142479577fbe9c2c696626cb/framework/includes/option-types.php#L871-L895)).

Option types are used/need only when `fw()->backend->option_type()` is called. So when this method is called for the first time, there should be an `do_action('fw_option_types_init');`.

Here is how the action will be used:

```php
// file: {theme}/inc/hooks.php

function _action_theme_init_option_types() {
    require_once dirname(__FILE__) .'/includes/option-types/.../class-fw-option-type-....php';
    require_once dirname(__FILE__) .'/includes/option-types/.../class-fw-option-type-....php';
    ...
}
add_action('fw_option_types_init', '_action_theme_init_option_types');
```

This action will be optional but recommended, just for those who are looking for speed and improvement. 

This feature will not affect/break anything, if you want, you can continue to include option types on every page load and don't use the action.

**Comment by moldcraft** [comment]
*I don't know why this idea came in my head that late.*

**Comment by moldcraft** [comment]
*This idea should came to me earlier (seems obvious).*

**Comment by duongancol** [comment]
So if I add this action , all option types are loaded in only page is called ?

**Comment by moldcraft** [comment]
> So if I add this action

At the moment the action doesn't exist yet, I will add it later and it will be available in the next plugin version.

> all option types are loaded in only page is called

sorry I don't understand this part.

**Comment by duongancol** [comment]
For example, I create page A and page B. 
Page A is saved with some option types.
Page B is just title and description.

Normally, option types are always loaded in page A and B
Did you mean that if I add  this function in the future, option type is only called on page A?

**Comment by moldcraft** [comment]
> Did you mean that if I add this function in the future, option type is only called on page A?

yes

**Comment by duongancol** [comment]
why it's not enabled in default?

**Comment by moldcraft** [comment]
it will be enabled by default.

**Comment by duongancol** [comment]
it's great :+1:
