### ISSUE TITLE
Use latest version 2.2.5 Get blank editor

### ISSUE THREAD

**Issue by herususanto** [ThemeFuse/Unyson#406]
imported .xml file from another site then I got blank editor when I check any page from admin page editor.. here's the screenshot
![blank-pe](https://cloud.githubusercontent.com/assets/6581837/6885371/fc95c3be-d647-11e4-92a5-09a43a2b210e.png)

but it's really strange since I can see the content on front side

**Comment by herususanto** [comment]
Update* .. after deactivate/activate plugins and refresh I got something like this :
![backtotextblock](https://cloud.githubusercontent.com/assets/6581837/6885405/a2e91ec2-d649-11e4-9b13-966d56408b84.png)

**Comment by GheorgheP** [comment]
Hi,

The new version of page builder will be released after tomorrow, in that version was solved similar problems: https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/48

Please test with this [version](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/48) of builder and tell us if all works fine or not.

**Comment by herususanto** [comment]
I've tested with https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/48 but still get blank screen on the visual editor.

From the console I see js error:
"Failed to recover items from input" SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 1 column 9640 of the JSON data
Stack trace:
Builder<.initialize@ ---- my path URL ---- /framework/extensions/builder/includes/option-types/builder/static/js/builder.js?ver=2.2.5:794:20

**Comment by GheorgheP** [comment]
Can you send me the XML file? Also, what importer do you use, the Wordpress standard import method?

**Comment by herususanto** [comment]
I've sent the .xml file to you. Yes I use Wordpress standad import

**Comment by GheorgheP** [comment]
Hi @herususanto,

I just tested on my local and all works fine. Please try to install the pending versions of:
* [Unyson](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/51)
* [Builder](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/49)
* [Page Builder](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/48)

**Comment by GheorgheP** [comment]
Can I close this issue, or the problem still persists?

**Comment by herususanto** [comment]
Ok.. fixed
