### ISSUE TITLE
Undefined index when editing existant post

### ISSUE THREAD

**Issue by kraymond70** [ThemeFuse/Unyson#407]
Hi,
I am getting an undefined index when previewing an *existant post*.
Preview works well when creating a post using the page builder.
But when editing an existant post, I get an undefined index error.

![undefined_index](https://cloud.githubusercontent.com/assets/1266755/6886332/812bcd74-d631-11e4-90eb-83f68c4db500.png)

**Comment by GheorgheP** [comment]
Hi,

The new version of page builder will be released after tomorrow, in that version was solved similar problems: https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/48

Please test with this [version](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/48) of builder and tell us if all works fine or not.

**Comment by kraymond70** [comment]
Hi,
I tested the last version and Yes all works fine.

Thanks.
