### ISSUE TITLE
Do we have such option?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#408]
I see that we have addable popups options and such but is there an option that  can open a set of options in a popup ?

Example , I will have several custom headers with their image preview (image picker) , lest say 10 , now I dont want to list all of them in a full list in options tab but would rather have user click on button "Select header" and choose from selection. I guess addable popup would do this right?

**Comment by danyj** [comment]
I am trying to make this with addable popup , 

issue 1  the button says ,  "Add" , I need ti to say Select header, 
issue 2 , how do I set default selected ? 

I tried this 

    'value' => array('type' => 'image-picker'),

I think that is what I should use here 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/addable-popup/class-fw-option-type-addable-popup.php#L116

but getting template error

**Comment by danyj** [comment]
OK default is solved 


			'value' => array(
				array(
					'headers' => 'header1',
				)
			),

But this keeps on adding popups 
http://prntscr.com/6n8msb
 I guess I need to make custom option

**Comment by moldcraft** [comment]
There is [option-type `popup`](https://github.com/ThemeFuse/Unyson/tree/master/framework/includes/option-types/popup) but we forgot about it (also how it works), it is missing in the docs and ScratchTheme DemoOptions. @GheorgheP will have a look at it and will add it in both.

Meanwhile you can try it, maybe it's exactly what you are looking for (it should).

**Comment by danyj** [comment]
ok , checking

**Comment by danyj** [comment]
usage is bit unclear , cant get it to open popup , will wait for instructions

**Comment by danyj** [comment]
@GheorgheP  can I please get some info on how to use the popup option.

**Comment by GheorgheP** [comment]
Hi,

In few minutes I will update the [Unyson Documentation](http://manual.unyson.io/en/latest/options/built-in-option-types.html#content)

But the option is easy to use. This is similar to [addable-popup](http://manual.unyson.io/en/latest/options/built-in-option-types.html#addable-popup) option type, but doesn't have the ***addable*** feature.

IE:
```php
'my-popup' => array(
	// Option label
	'label' => __( 'Text Option', 'fw' ),

	//Option description
	'desc'  => __( 'Add some desription', 'fw' ),

	'type'  => 'popup',

	//Popup button text
	'button' => __( 'Edit Option', 'fw' ),

	//Popup text that will appear in the popup header
	'popup-title' => __( 'My Option', 'fw' ),

	//Array of options yo uwan to have in the popup
	'popup-options' => array(
		'text' => array(
			'label' => __( 'Example Option', 'fw' ),
			'type'  => 'text',
		),
	),
),
```

In the next version of Unyson we will add the `size` parameter, to be able to set desired popup size, like for the `addable-popup` option type.

**Comment by danyj** [comment]
@GheorgheP  That is what I tried bud , the popup does not open

**Comment by GheorgheP** [comment]
Please take a look in the browser console, there may be an error.

**Comment by danyj** [comment]
that is first thing I checked , no js bugs,
 http://prntscr.com/6nlw2n
http://prntscr.com/6nlw5y

ahh , found the culprit , 

I added option and hit reset button,  the events are killed 
on page refresh popup works

**Comment by danyj** [comment]
thank you , closing

**Comment by danyj** [comment]
This option does not show default values 


	'testpopup' => array(
		// Option label
		'label' => __( 'Text Option', 'fw' ),
		'desc'  => __( 'Add some desription', 'fw' ),
		'type'  => 'popup',
		'button' => __( 'Edit Option', 'fw' ),
		'popup-title' => __( 'My Option', 'fw' ),
		'popup-options' => array(
			'text' => array(
				'label' => __( 'Example Option', 'fw' ),
				'type'  => 'text',
				'value' =>'Testing option'
			),
		),
	),

do reset and print the  testpopup, it wont return anything, 
only if saved it returns value

I think this one should work like the containers since it is just a container for set of options

You see I am having huge issue with a page load in admin and it is because of the multi selects and image pickers. I disabled large previews , cut down image sizes , did everything I could to speed it up but it is just not happening.  

to explain , 
i have a set of options to adjust 
bg color or image , kinda like background-image but is extended and gives user an option to adjust 
repeat, attachment etc, 
now this set consists out of    14 options, 
now i am using it on body , header, footer and each time I use it the load is just to much, I sit for about 6-7 sec until the admin loads and I am on a monster machine here. 

So I was thinking to add those in a popup , but popup does not return default values so I am stuck and being forced to cut down on options which I just cant.

**Comment by danyj** [comment]
Thnx for default fix but please advise why is it that this is not a container? 
Makes no sense to call  nested the options inside the  popup array since the popup array is not an option with values but a container 

So if I just want to move set of options in popup I should not be doing this  to get the options

	fw_get_db_settings_option('testpopup/optioninpopup');
	
but this 
	
	fw_get_db_settings_option('optioninpopup');

**Comment by danyj** [comment]
uploadimage option does not work in popup

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/408#issuecomment-90838034

Popup is an option type, not a container.
Yes you will have to do `fw_get_db_settings_option('testpopup/optioninpopup');`.

**Comment by danyj** [comment]
but cant we make it to be a container, it is not an option, it does not return values but a set of options just like tabs and boxes

**Comment by moldcraft** [comment]
Sorry, we can't.

**Comment by danyj** [comment]
ok, is there info on how to make a container than ?

**Comment by moldcraft** [comment]
I can't make containers, they are hardcoded in core.

**Comment by danyj** [comment]
ok than please check uploadimage bug when you get to it. 

I am really trying here but hitting walls no matter what way I choose ( talking in general not because of container ) . You see I am dancing around here since 2.5 months but slowly looks like unyson is made for small themes with limited amount of options. 
I currently have 93 ( not even half of what top tf themes have )  options and admin is just sluggish. Looking for workarounds does not help either. It is perfect for radios/selects/inputs but as soon as you start with multi-picker , image-picker and options that should do things right it slows down. Talking mainly about admin area. 

Don't take this as a rant but rather as crying for help from someone that is trying to make this right.  
I rearranged the admin 10 times by now because of the speed but it is just not happening.

**Comment by moldcraft** [comment]
I will make this https://github.com/ThemeFuse/Unyson/issues/442
Then we will test if it helps to make the settings page less slower.

**Comment by moldcraft** [comment]
How many multi-picker,image-picker do you have?

**Comment by danyj** [comment]
il reply on 442 ok ?

**Comment by moldcraft** [comment]
ok, and give there more details if you have.
