### ISSUE TITLE
How can I detect if page is using builder

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#409]
I need to check if page is using unyson page builder , something similar you do here 
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/4db5677c897a5584996c23aa701fe464d083a28e/class-fw-extension-page-builder.php#L156

but need to check this in theme static.php or hooks/helper files

**Comment by moldcraft** [comment]
[The method is public](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/4db5677c897a5584996c23aa701fe464d083a28e/class-fw-extension-page-builder.php#L179) feel free to use it:

```php
if (fw_ext('page-builder') && fw_ext('page-builder')->is_builder_post()) {
    // ...
}
```

**Comment by danyj** [comment]
excellent , I  completely forgot about fw_ext...   and tried to use the class directly. thank you!
