### ISSUE TITLE
Unyson theme transfer options

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#411]
Hi guys,

I didn't find any theme transfer option in the theme setting for unyson, can you please tell me how to achieve this so that I can easily import the theme options from one instance to another instance.

Thanks

**Comment by valeriuzdrobau** [comment]
Hi, try our [content demo  install module](http://manual.unyson.io/en/latest/extension/contentdemoinstall/index.html).

**Comment by linjo** [comment]
Is there anyway to transfer the theme options alone, as json or something?

**Comment by moldcraft** [comment]
Theme settings are saved in wp option with name `'fw_theme_settings_options:' . fw()->theme->manifest->get_id()`.

**Comment by linjo** [comment]
But is there any inbuilt option inside the theme options that can achieve this autamatically ? Like in Redux Framework? Please check the image below

![redux](https://cloud.githubusercontent.com/assets/11642633/6915755/7141ab16-d7b4-11e4-867b-339819d8f5b0.jpg)

**Comment by linjo** [comment]
Hi guys any update about this??

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/2004#issuecomment-250145979
