### ISSUE TITLE
Could you extend the slider option?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#412]
We have a slider option which is very appealing but is bit hard to work with precise values. 
Example you have slider from 0 to 500, and you want to set it to 278, it will take you a bit to get it right. 
So can we please have an optional input next to the slider to set it at desired value , something like this 
http://prntscr.com/6nm9h7

**Comment by DimiBaitanciuc** [comment]
We'll look into it, can't promise anything.

**Comment by danyj** [comment]
Never mind , I made my own.
