### ISSUE TITLE
Spinner option suggestion

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#413]
Would it be possible for you to add a spinner option, like 
https://jqueryui.com/spinner/
or http://prntscr.com/6nmcuw

**Comment by danyj** [comment]
never mind , made my own

**Comment by llemurya** [comment]
@danyj can you make a pull request with this option type?

**Comment by moldcraft** [comment]
@llemurya just creating the option is easy. More important is the design. But @DimiBaitanciuc is busy. (Also I think this option is not that important)

**Comment by danyj** [comment]
@llemurya  I prefixed the name to thzspinner and can send you this if you need it 

default 
http://prntscr.com/6o1tiw
with add-on
http://prntscr.com/6o1sj0

usage 

	'testspinner' =>array(
		'type'  => 'thzspinner',
		'value' => 50,
		'addon' =>'em',
		'min'=>10,
		'max'=>500,
		'step'=>10,
		'label' => __('Label', 'fw'),
		'desc'  => __('Description', 'fw'),
		'help'  => __('Help tip', 'fw'),
	),  

email youjoomla at gmail

@moldcraft  dont take this wrong but every option is important to the person who needs it ,  this is an options framework after all.
