### ISSUE TITLE
US Hour format question

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#415]
Love the framework. How do you change the time format from European to US (12-hour)?

Reply from <a href="http://themeforest.net/forums/thread/meet-unyson-the-free-drag-drop-wordpress-framework/141818?page=19&message_id=1241391#1241391">TF forum</a>.

**Comment by llemurya** [comment]
@thednp we wrote at [TF forum](http://static.md/da03971781316c08dc001e310afd1d51.png) to explain more explicit the problem, but @campochristina didn't answer at our question what is why we close this issue.
