### ISSUE TITLE
Change position for feedback stars 

### ISSUE THREAD

**Issue by akshaya-rane** [ThemeFuse/Unyson#416]
I need to change position of 'Rating' stars to another hook. In class, 'class-fw-extension-feedback-stars.php' below code is added,

`add_action( 'comment_form_logged_in_after', array( $this, '_action_additional_fields' ) );`
`add_action( 'comment_form_after_fields', array( $this, '_action_additional_fields' ) );`

I have created similar folder structure in theme's 'framework-customizations' folder. It allowed to overwrite view. 

I have tried following code in 'hooks.php' ,

```add_action('init','wdm_remove_action');

function wdm_remove_action() {
 remove_action( 'comment_form_logged_in_after', array( 'FW_Extension_FeedBack_Stars', '_action_additional_fields' ) );
 remove_action( 'comment_form_after_fields', array( 'FW_Extension_FeedBack_Stars', '_action_additional_fields' ) );
}
```
Even I tried to add custom class and load it via 'hooks.php' file. But these action didn't get rendered well. Kindly can you suggest some way for it?

**Comment by valeriuzdrobau** [comment]
Hi , try the code below:  

` function wdm_remove_action(){
        $feedback_stars_instance = fw()->extensions->get('feedback-stars');
        remove_action('comment_form_logged_in_after', array($feedback_stars_instance, '_action_additional_fields'));
        remove_action('comment_form_after_fields', array($feedback_stars_instance, '_action_additional_fields'));
    }
    add_action('fw_extensions_init', 'wdm_remove_action');`

**Comment by akshaya-rane** [comment]
Hi,

Thank you, that works Great.
