### ISSUE TITLE
Warning: Recursive shortcodes load in /wp-content/plugins/unyson/framework/extensions/shortcodes/class-fw-extension-shortcodes.php on line 68

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#418]
Hi
Today i have update my plugin and receive this warning 
Warning: Recursive shortcodes load in /wp-content/plugins/unyson/framework/extensions/shortcodes/class-fw-extension-shortcodes.php on line 68

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/396#issuecomment-85886079
