### ISSUE TITLE
Hide available extensions 

### ISSUE THREAD

**Issue by xpeeder** [ThemeFuse/Unyson#421]
Hi
Is there any way can hide available extensions  list ?? i only show which i have set on supported_extensions array. 
 $manifest['supported_extensions'] = array()

Only can activate those which i have set to supported_extensions. and others extension willl be hide in available extensions

Thank you

**Comment by moldcraft** [comment]
I am working on this right now https://github.com/ThemeFuse/Unyson/issues/307

**Comment by moldcraft** [comment]
I think it's already done.
Please [download the latest dev version of Unyson](https://github.com/ThemeFuse/Unyson/archive/master.zip) and extract in `wp-content/plugins/unyson/`.
At the bottom of the extensions list will be a "Show/Hide" button, let me know if it's fine how it works, this feature will be included in the next Unyson version.

**Comment by xpeeder** [comment]
@moldcraft  its look good. 
But i thing if this extension not showing there that will be better for us. 
Otherwise people will ask how they can use this to. (people will check what available there)  it will be better only available which i have set to supported_extensions.
or you can another $cfg to hide what i dont like to show this list

Thanks

**Comment by moldcraft** [comment]
You can hide [that button](https://github.com/ThemeFuse/Unyson/blob/02ccb848072e7d7ac80f3c721cbdf77fa568448e/framework/core/components/extensions/manager/views/extensions-page.php#L175) from css

```css
#fw-extensions-list-wrapper .toggle-not-compat-ext-btn-wrapper {
    display: none;
}
```

**Comment by xpeeder** [comment]
Great Thanks mate

**Comment by danyj** [comment]
> You can hide 

but how to enque stylesheet only on the unyson extensions page? 

fw_admin_enqueue_scripts  works on settings, term and post ,

**Comment by andreiglingeanu** [comment]
@danyj 

```php
add_action('admin_enqueue_scripts', '_enqueue_scripts');

function _enqueue_scripts() {

  // skip pages that are not extensions_page
  // also is_extension_page is available, but you won't need it
  if (! fw()->extensions->manager->is_extensions_page()) {
    return;
  }

  // perform your enqueue
}

```
