### ISSUE TITLE
fw_get_db_settings_option stopped working in 2.7.25

### ISSUE THREAD

**Issue by goran468** [ThemeFuse/Unyson#4211]
In the new update 2.7.25 fw_get_db_settings_option stopped working and now returns null in all sites. It causes a lot of problems.

Am I the only one with this bug?

**Comment by SAngieS** [comment]
I think i have the Same Issue my Theme's Settings are reset and no changes i make stay the way i want them. Parts of my Theme that i build with the Unyson builder work anymore

**Comment by sarah-regard** [comment]
Yes same here. All of our theme settings reverted and are having to be manually fixed again one by one. Restoring an old version of the plugin only worked on one of our sites and not the others, but Unyson is the common denominator.

**Comment by goran468** [comment]
The error is in file **[framework/helpers/class-fw-wp-option.php]:24**

2.7.24:
`$value = get_option($option_name, null);`

2.7.25:
`$value = get_option($option_name = '', null);`

Empty value always sent now instead of $option_name.

It looks like it goes with this commit:
https://github.com/ThemeFuse/Unyson/commit/904d3a1da4325ab4a902bb4aa3d1b9951b8c7ec5

**Comment by goran468** [comment]
@ViorelEremia could you look into it please? The problem is quite critical.

Thank you.

**Comment by SAngieS** [comment]
A Version Rollback fixed the "saving Changes" Issues. Still have to change all my settings back manually tho

**Comment by ViorelEremia** [comment]
Ihave just relased a new version can you try it

**Comment by goran468** [comment]
@ViorelEremia now everything works correctly. Thank you for rapid reaction and have a nice weekend!

**Comment by ViorelEremia** [comment]
thank you, you too

**Comment by mwtemplates** [comment]
Sorry, that was my fault.
I was fixed this locally, but forgot to push this fix and add to my pull request.

https://github.com/mwtemplates/Unyson/commit/a5bf9b8dfa29a390486bbd2d4a5e99f17d1f5d93
