### ISSUE TITLE
googleapis_webfonts_url does not work anymore

### ISSUE THREAD

**Issue by goran468** [ThemeFuse/Unyson#4217]
The default link webfonts link:
**https://google-webfonts-cache.unyson.io/v1/webfonts**

returns

**"API key not valid. Please pass a valid API key.".** 

Could you update the API key on your side please? It is possible to create a standalone solution, but for old sites which are using default Unyson webfonts url it could lead to the problem.

Thank you in advance.

**Comment by onebelarusianguy** [comment]
`//Make Google fonts work again

if ( !function_exists( 'nowadays_filter_fw_googleapis_webfonts_url' ) ) :
	function nowadays_filter_fw_googleapis_webfonts_url() {
		return 'https://www.googleapis.com/webfonts/v1/webfonts?key=XXXXX';
	}
endif;

add_filter('fw_googleapis_webfonts_url', 'nowadays_filter_fw_googleapis_webfonts_url');`

where **XXXXX** is your API key.
