### ISSUE TITLE
[from TF] Unyson extensions are showing as available with no active extensions

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#422]
http://themeforest.net/forums/message/go_to/1239049

Hi guys
I am using Unyson on my Wordpress site and in particular the page builder extension which is brilliant.

I have found however on a few occasions after checking some of my pages when say for instance using the accordion feature that that area renders as HTML

I have found that when I check my Wordpress dashboard, although Unyson is still present the page builder extension seems to have deactivated itself?
If I reactivate the extension the page works again…. any ideas why?
Just did this again today, the Unyson extensions are showing as available with no active extensions? It driving me mad and mucking up my website all the time? Is anyone else experiencing this? Perhaps I need to alter some setting in my Wordpress?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/263

**Comment by discover247** [comment]
Hi moldcraft

I have read through issue 263 and in my understanding of what was discussed the issue wasn't resolved,  perhaps we can reopen the issue for further discussion and investigation as clearly this problem was not an isolated incident and needs sorting?

**Comment by moldcraft** [comment]
Hi @discover247 
It wasn't resolved because we can't (have no idea how to) reproduce it.

**Comment by danyj** [comment]
@discover247  did you and #263 use same theme or do you host on same server?

**Comment by discover247** [comment]
He/she was with hostgator I'm with ipage cant see any mention of his/her theme but I am using DIFSTHEME as a base

**Comment by danyj** [comment]
@discover247  post more info , php version, server info , unyson version

**Comment by discover247** [comment]
PHP Version: 5.3.13;
Web Server: Apache
Unyson version 2.2.6

**Comment by discover247** [comment]
Wordpress 4.1.1

**Comment by moldcraft** [comment]
> http://themeforest.net/forums/thread/meet-unyson-the-free-drag-drop-wordpress-framework/141818?page=20&message_id=1242861#1242861
> @discover247 and now issue 263 has been closed too

#263 was never closed and we are waiting for someone who will give us some tips how to reproduce it

**Comment by discover247** [comment]
Well it was showing with a padlock symbol earlier today, if you need some help then I will help as much as I can

**Comment by moldcraft** [comment]
> if you need some help then I will help as much as I can

Ideally would be if you give us exact steps how to reproduce the problem.

For e.g.

```
1. Create an account on whatever-hosting.site
2. Install ...
...
x. Then you will see that the extensions are gone from the Installed extensions
```

**Comment by discover247** [comment]
Hmmm that seems very involved and time consuming.
What if I monitor it closely and tell you the moment I notice the extension has deactivated.... are you pushing automatic updates? Maybe that is the root of the problem

**Comment by moldcraft** [comment]
> are you pushing automatic updates? Maybe that is the root of the problem

[No](https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-75110349). I recommend to move the discussion to #263 .

**Comment by discover247** [comment]
OK thats fine by me can we merge the existing comment on this thread over  there to?

**Comment by moldcraft** [comment]
> can we merge the existing comment on this thread over there to

No. Only manually to post new comments there.
