### ISSUE TITLE
Fatal error: .../class-fw-option-type-multi-select.php on line 11 reproduced

### ISSUE THREAD

**Issue by zaneyu** [ThemeFuse/Unyson#423]
Hi it's me again reporting the same issue I reported yesterday and I believe I've found the way to reproduce it...

*Fatal error: ...wp-content/plugins/unyson/framework/includes/option-types/multi-select/class-fw-option-type-multi-select.php on line 11*

I think the error is to a great extend associated with the incompatibility between the Unyson extension Mega Menu  (lateset version I believe) and  [jonradio Multiple Themes](https://wordpress.org/plugins/jonradio-multiple-themes/) (version 7.1), using multiple themes and different (or same) navigation menus as the respective primary menu.

In my case, I was setting my site home page to use theme ***A***, and another page, say, the bbpress forum page to use theme ***B***. Initially in ***A*** I set a navigation menu as its primary menu, and everything worked fine.
Then I did the same thing in ***B*** (i.e. setting another navigation menu as ***B***'s primary menu), and that fatal error occurred.

I deleted the Mega Menu folder through SFTP and the fatal error disappeared. Then I successfully set the two primary menus with respectively different navigation menu. 

You may follow the above procedure and see if it is really the problem.

**Comment by moldcraft** [comment]
Please [download the latest Unyson dev version](https://github.com/ThemeFuse/Unyson/archive/master.zip), install in `wp-content/plugins/unyson/` and let us know if it fixes the problem.

**Comment by moldcraft** [comment]
This seems to be fixed https://github.com/ThemeFuse/Unyson/issues/432

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/52
