### ISSUE TITLE
Sidebar extensions console log intentional ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#425]
There is a console log  in sidebar extensions 
https://github.com/ThemeFuse/Unyson-Sidebars-Extension/blob/master/static/js/sidebar-general.js#L787

making sure you intended to do that

**Comment by llemurya** [comment]
@danyj we removed console logs from source, please see this [commit](https://github.com/ThemeFuse/Unyson-Sidebars-Extension/commit/67f3024d735f02f8d0345e6a80671846639a5eb3), in next release it will be in production, thanks for feedback.
