### ISSUE TITLE
unyson.io is down

### ISSUE THREAD

**Issue by jer872** [ThemeFuse/Unyson#4256]
My site is trying to reach https://google-webfonts-cache.unyson.io/v1/webfonts and getting an error because unyson.io wasn't renewed. Is this something that you can take care of?

**Comment by ItsAndrea** [comment]
Hello, I hope to help you. Regarding the question:

As you can see when you click "renew now" you go to this page where it says "unyson.io expired on 08/19/2022 and is not available at this time." This means the owner hasn't renewed it's domain contract and there's nothing we can do. 
I don't know what are you trying to achieve, however I suggest to look for another available option.

![expired](https://user-images.githubusercontent.com/85640313/185771148-bee26901-3458-4c4b-aedb-5749042957c2.png)
 
This is the answer I arrived at with the information you provided, if it was helpful please mark this as complete or provide more information.

**Comment by jer872** [comment]
Yeah I found the same thing. I thought this was the place to ask about it, sorry if it is not
