### ISSUE TITLE
Help - plugin Unison error framework

### ISSUE THREAD

**Issue by infoimage** [ThemeFuse/Unyson#4260]
This bug just occured on our website  https://www.prazakjidelna.cz/ . I cant find any solution to this. Could you please help me? 
![www prazakjidelna cz](https://user-images.githubusercontent.com/89975483/185881575-7fe755e5-064e-49f7-a784-edd811e88e50.png)

**Comment by infoimage** [comment]
Warning: Invalid argument supplied for foreach() in /www/prazakjidelna.cz/prazakjidelna.cz/wp-content/plugins/unyson/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php on line 148

Warning: Invalid argument supplied for foreach() in /www/prazakjidelna.cz/prazakjidelna.cz/wp-content/plugins/unyson/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php on line 148

Warning: Invalid argument supplied for foreach() in /www/prazakjidelna.cz/prazakjidelna.cz/wp-content/plugins/unyson/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php on line 148

**Comment by Tom2710** [comment]
Same problem
and i search a solution for this

**Comment by bartlomiejmatlega** [comment]
Same problem

**Comment by IamOri** [comment]
Same problem here. 
Looks like Google Fonts API key is invalid on unyson chache site. Tried to generate my own api key and change url directly to google, but it looks like the old response is saved in some kind of cache. 
Idea how to clear the cash?

**Comment by germanrandhawa** [comment]
> 

Did you get the solution?

**Comment by tikyta** [comment]
Same issue... anyone found a solution? Thanks

**Comment by Tom2710** [comment]
@germanrandhawa  No I search a solution too

**Comment by infoimage** [comment]
> This bug just occured on our website https://www.prazakjidelna.cz/ . I cant find any solution to this. Could you please help me? ![www prazakjidelna cz](https://user-images.githubusercontent.com/89975483/185881575-7fe755e5-064e-49f7-a784-edd811e88e50.png)

**Comment by infoimage** [comment]
Solutions that work!

https://github.com/ThemeFuse/Unyson/issues/4261#issuecomment-1222734960
