### ISSUE TITLE
How to render fw()->backend->option_type   with label

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#427]
I made custom option that can show 4 color pickers, but I would like to display them as they are normally display 4 options with 4 labels , description and help 
kinda  like this 
http://prntscr.com/6pubmv

but since I merged them in to one option ,  the labels and desc/help do not render

this is the snip from the view 

		<?php
		echo fw()->backend->option_type( 'rgba-color-picker' )->render(
			'text_color',
			array(
				'type'  => 'rgba-color-picker',
				'label' => __('Text color','fw'),
				'value' => fw_akg('text_color', $option['value']),
				'desc' => __( 'Set default text color', 'fw' ),
				'attr'  => array(
					'class' => 'text-color'
				)
			),
			array(
				'value' => fw_akg('text_color', $data['value']),
				'id_prefix' => $option['attr']['id'].'-',
				'name_prefix' => $option['attr']['name'],
			)
		);
		?>

this is how it looks like
http://prntscr.com/6pucop

I know I can add text and labels but were wondering if this is a bug or intended, 

the option is setup like this 

	'footer_colors'  => array(
		'type'  => 'thzcolorset',
		'value' => array(
			'text_color'=>'#444444',
                        //and more
		),
		'label' =>false,
		'desc' => false
	),

so the default option label and desc is hidden.

**Comment by levan1993** [comment]
Hi @danyj 
you can use 
    fw()->backend->render_options( $options_array, $values, $options_data = array(
        'id_prefix' => $option["attr"]["id"] . '-',
        'name_prefix' => $option["attr"]["name"]
    ) );

**Comment by danyj** [comment]
Thnx much bud , almost there , I think I am missing a class here 
http://prntscr.com/6pvbnz

**Comment by danyj** [comment]
OK managed this with 

	/**
	 * @internal
	 */
	public function _get_backend_width_type()
	{
		return 'full';
	}

and left padding css reset on the container which I dont like since the css is included just because of that one line and I cant reach default design top container. 

thank you much @levan1993 .  
I'l leave it open for a day if someone else from the team has time to look it over and advise if this approach is ok.

**Comment by moldcraft** [comment]
The approach is ok.
For e.g. it is used in the option-type `multi`: [options render](https://github.com/ThemeFuse/Unyson/blob/34a01f9261989e42e5294124e8df2ac0a1ca98bd/framework/includes/option-types/multi/class-fw-option-type-multi.php#L44), [padding fix](https://github.com/ThemeFuse/Unyson/blob/34a01f9261989e42e5294124e8df2ac0a1ca98bd/framework/includes/option-types/multi/static/css/styles.css#L1-L3).

Thank you @levan1993

**Comment by danyj** [comment]
@moldcraft  thnx for looking over. all works fine
