### ISSUE TITLE
Unyson extensions

### ISSUE THREAD

**Issue by AlexRivasGit** [ThemeFuse/Unyson#4275]
Unyson extensions throw the following error: 

Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Operation timed out after 5000 milliseconds with 0 out of 0 bytes received)

**Comment by mwtemplates** [comment]
https://github.com/ThemeFuse/Unyson/issues/4249#issuecomment-1275826387

**Comment by ViorelEremia** [comment]
Fixed in the latest update
