### ISSUE TITLE
Theme Setting in Menu

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#428]
Hi!
Is there any ways to make Theme Setting appear on Menu Top bar of Admin?
![screen shot 2015-04-06 at 11 08 26 am](https://cloud.githubusercontent.com/assets/1773011/7000461/8ff0bcbc-dc4d-11e4-93b8-2c3302706b45.png)

**Comment by llemurya** [comment]
@duongancol  at the moment is not posible to do this from framework, please try this solution
```php
add_action("admin_bar_init", "create_my_menu");

function create_my_menu(){

	global $wp_admin_bar;

	$wp_admin_bar->add_menu( array(
		'parent' => 'appearance',
		'id'     => 'theme-settings',
		'title'  => __('Themes Settings'),
		'href'   => 'http://google.com/',//set your url
		'meta'   => array(
			'class' => 'hide-if-no-customize',
		),
	) );
}
```
I tested , and for me works. Try this and say if it work for you. I wrote the code in `functions.php` in theme.

**Comment by duongancol** [comment]
@llemurya Thanks for your custom code, it works now, but I hope it is more flexible.
For example, some users can rename it to "Theme Option", "Settings",...
And hide or show it from admin bar.
I'll more convenient  if can do from framework.

**Comment by llemurya** [comment]
@duongancol please open a new ticket with label feature and describe how you see this feature. And we will make a decision in order to make this feature available.

**Comment by duongancol** [comment]
Ok, How can I create ticket with label feature?

**Comment by llemurya** [comment]
@duongancol  just open a ticket and i will label it!

**Comment by duongancol** [comment]
I did, thank you! https://github.com/ThemeFuse/Unyson/issues/430

**Comment by moldcraft** [comment]
You can get the slug for Theme Settings page with

```php
fw()->backend->_get_settings_page_slug()
```

The @llemurya 's code a bit changed would look like this:

```php
// file: {theme}/functions.php or {theme}/inc/hooks.php https://github.com/ThemeFuse/Theme-Includes

function _action_theme_admin_bar_menu_theme_settings () {
	global $wp_admin_bar;

	$wp_admin_bar->add_menu( array(
		'parent' => 'appearance',
		'id' => 'theme-settings',
		'title'  => __('Themes Settings'),
		'href' => admin_url( 'admin.php?page=' . fw()->backend->_get_settings_page_slug() ),
		'meta' => array(
			'class' => 'hide-if-no-customize',
		),
	) );
}
add_action("admin_bar_init", "_action_theme_admin_bar_menu_theme_settings");
```
