### ISSUE TITLE
Page Content not visible

### ISSUE THREAD

**Issue by ananthhaniman** [ThemeFuse/Unyson#4287]
Hi, this is my WordPress site https://harijeyan.com/

after the Unyson latest updates, page contents are not visible. 

Wordpress Version 6.1.1 | Unyson 2.7.28 | PHP 7.4

**Comment by erichomiak** [comment]
I'm having the exact issue. All page content disappeared after updating to WordPress 6.1.1 with Unyson 2.7.28.

**Comment by ananthhaniman** [comment]
i have downgraded my Wordpress version to fix this issue. You can downgrade your Wordpress version using plugin.
