### ISSUE TITLE
WP Customizer options disappeared

### ISSUE THREAD

**Issue by PioPas** [ThemeFuse/Unyson#4288]
I have just noticed there are not visible WP Customizer options. I have found also an error in console log.

![image](https://user-images.githubusercontent.com/120340504/206930263-fd8a61c0-702d-4647-9927-5378ee12fefb.png)

**Comment by PioPas** [comment]
I have found this topic. I did what is describe. When I deleted the value in DB I have got this. I refreshed page a few times and the option in DB is not updated.

![image](https://user-images.githubusercontent.com/120340504/206930827-bd8a823f-1f3e-4359-b3ba-3d28bc725415.png)
![image](https://user-images.githubusercontent.com/120340504/206930837-6ecd7df7-7725-4315-8f99-5f47b9cfae80.png)

**Comment by PioPas** [comment]
Ok, so there is an error in api used in general.php - it doesn't get the API result. So temporally I replace the $body with the string from bkp. So it is "refreshing" database value but the value is hardcoded not get from the API. It works for me but it is not a solution. Hope API will be fixed soon.

**Comment by IamOri** [comment]
You can try load them directly from google api. [https://developers.google.com/fonts/docs/developer_api](https://developers.google.com/fonts/docs/developer_api)
Unyson api is just cache without token authenitication.

**Comment by PioPas** [comment]
> You can try load them directly from google api. https://developers.google.com/fonts/docs/developer_api Unyson api is just cache without token authenitication.

Thanks. It worked for me as a hardcoded string in php now but I have a felling I am not the only user who faced this issue with Unyson API. There is still "Error : Failed to get Google Fonts".

The question is if there is Unyson API error in general or something wrong with my WP?

I am asking about it:
	$response = wp_remote_get( apply_filters( 'fw_googleapis_webfonts_url',
	'https://google-webfonts-cache.unyson.io/v1/webfonts' ) );

**Comment by PioPas** [comment]
> When i open that link i can see correct json, so thats probably ok. I also tried to reload it by removing font data from db on my site, and that works fine too. You can try to call api in separate script with curl (your.site/api-test.php), to see if your server get response from api. If you get valid response, then problem is probably somewhere in your wp. Maybe you could try load it with that wp_remote_get function in some of the functions.php file and see what it returns.

Thanks a lot!

I have checked and it worked like that 	
```
$response = wp_remote_get( 'https://google-webfonts-cache.unyson.io/v1/webfonts' );
$body     = wp_remote_retrieve_body( $response );
```

but by design is like that and I haven't change it. No idea why but I will keep digging... 
```
$response = wp_remote_get( apply_filters( 'fw_googleapis_webfonts_url',
			'https://google-webfonts-cache.unyson.io/v1/webfonts' ) );
```

**Comment by PioPas** [comment]
Ok, I have found a reason. It is in my template extra filter which redirect to the different url.
