### ISSUE TITLE
Installation Failing & Demo Not Working

### ISSUE THREAD

**Issue by WhitneyWPHFB** [ThemeFuse/Unyson#429]
I've downloaded files from github and directly from the site and both are failing to install saying there is no style.css file (there is though, I looked in both the parent & child theme and its there).

Second issue: the demo isn't working. Admin is default wp options and when you try to activate or view the live site of any theme including any of the unyson themes it returns and error message.

Also side note, the contact form on your website hasn't been working for weeks.

Really excited to start using this though, I've been through 100's of themes and frameworks and yours is the one I love!

**Comment by valeriuzdrobau** [comment]
1. Try to download the theme again on github, afterwards copy just Scratch-Parent folder in `wp-content/themes` and try to activate the theme again. Let us know what errors occur.
2. Please provide me more details about errors that occur, if possible, attach a screenshot.

**Comment by valeriuzdrobau** [comment]
I close this issue, because there is no feedback from the user.
