### ISSUE TITLE
Some options for Theme Setting

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#430]
Hi! 
It'll be great if Theme Setting has options to appear on admin bar, rename and appear on sidebar of wp-admin(not in Appearance). 
The reason is that if users from frontend, if they want change setting of Theme setting, they have to go to wp-admin->Appearance-> Theme Setting. It take time. If they hover to admin bar -> click to Theme Setting, it is more convenient. 
I know we can use custom code to hook to admin_bar_init function with static url.
However some users would like to rename "Theme Setting" to "Theme Option", "Setting", "Abc theme Setting",.. others want to move Theme Setting in sidebar of wp-admin instead of in Appearance. 
So I suggest 3 features option of Theme Setting:
1. Hide/Show on admin bar
2. Rename
3. Move outside of Appearance 

Thank you.

**Comment by moldcraft** [comment]
1. You can use [this action](https://github.com/ThemeFuse/Unyson/blob/cc3541d3ef26e7abaecc386a332dc8eebbea6462/framework/core/components/backend.php#L411) to move the Theme Settings menu wherever you want. **(closed)**
2. To add Theme Settings menu in admin bar without static url, use [this code](https://github.com/ThemeFuse/Unyson/issues/428#issuecomment-90116368).

I more people will add +1/request/vote for 2. , I will add that code in framework and a theme config parameter to enable/disable it (disabled by default).

**Comment by duongancol** [comment]
Thank you, it work for me.
:+1:

**Comment by duongancol** [comment]
Hi! @moldcraft : is there any way to add Styling into Theme Setting?

**Comment by llemurya** [comment]
@duongancol  try this solution.
```php
add_action("admin_bar_init", "_action_theme_admin_bar_menu_theme_settings");

function _action_theme_admin_bar_menu_theme_settings () {
	global $wp_admin_bar;

	$wp_admin_bar->add_menu( array(
		'parent' => 'appearance',
		'id' => 'styling',
		'title'  => __('Styling'),
		'href' => admin_url( 'themes.php?page=fw-styling' ),
        'meta' => array(
            'class' => 'hide-if-no-customize',
        ),
    ) );
}
```

**Comment by llemurya** [comment]
@duongancol I don't understand you want to add styling page in theme-settings page as a tab? Please be more explicit how you see that ?

**Comment by moldcraft** [comment]
> @duongancol Styling into Theme Setting?

No. The `styling` option type was created hardcoded only for the Styling page and it will work with bugs and glitches on the Theme Settings page (or any other page).

**Comment by duongancol** [comment]
@moldcraft : It's ok

**Comment by valeriuzdrobau** [comment]
[Also on this question.](https://github.com/ThemeFuse/Unyson/issues/115)
