### ISSUE TITLE
How to remove default demo sliders?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#431]
Playing with the Slider extension I stumbled on the following problem..
When I install the extension and create a new slider, ir shows 3 already built ones (the 3 thumbnails). I copied the bx slider from the scratch theme into my framework-customization s directory but it doesn't show up.

How can I remove the 3 already built ones amd make it show my bx slider?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/391#issuecomment-84968569

**Comment by pe6o** [comment]
Tried:

```php
function _filter_theme_disable_sliders($sliders){
    unset($sliders['owl-carousel']);
    return $sliders;
}
add_filter( 'fw_ext_slider_activated' , '_filter_theme_disable_sliders');
```

But it didn't work. It still shows the three thumbnails. Tried putting and removing the bx-slider from Scratch theme in `framework-customizations/extensions` and still to no avail.

**Comment by moldcraft** [comment]
@llemurya Please add in docs "How to disable default sliders"

**Comment by llemurya** [comment]
@pe6o try this solution ```php
add_filter( 'fw_ext_slider_activated' , function($sliders){ $key = array_search('owl-carousel', $sliders); unset($sliders[$key]); return $sliders; });
```

**Comment by moldcraft** [comment]
`function($sliders){ ...`  this won't work in php 5.2

**Comment by moldcraft** [comment]
@pe6o I fixed [the code in your comment](https://github.com/ThemeFuse/Unyson/issues/431#issuecomment-90206681), try again.

**Comment by pe6o** [comment]
Thanks for the fast response! It removed one of the sliders. Itried this one:

```php
function _filter_theme_disable_sliders($sliders){ 
	$key = array_search('owl-carousel', $sliders); 
	unset($sliders[$key]);  
	$key = array_search('bx-slider', $sliders); 
	unset($sliders[$key]); 
	$key = array_search('nivo-slider', $sliders); 
	unset($sliders[$key]); 
	return $sliders; 
}
add_filter( 'fw_ext_slider_activated' , '_filter_theme_disable_sliders');
```And it removed them.

But the code is very funny...

**Comment by moldcraft** [comment]
The "compressed" version

```php
function _filter_theme_disable_sliders($sliders){
    foreach (array('owl-carousel', 'bx-slider', 'nivo-slider') as $name) {
        $key = array_search($name, $sliders); 
        unset($sliders[$key]);  
    }
    return $sliders; 
}
add_filter( 'fw_ext_slider_activated' , '_filter_theme_disable_sliders');
```

**Comment by pe6o** [comment]
Ah, just ended up with this and was posting my solution. Thanks!
