### ISSUE TITLE
Updated on 4/4/2015 and have this issue

### ISSUE THREAD

**Issue by otfromtot** [ThemeFuse/Unyson#432]
I keep getting this

Fatal error: Cannot redeclare class fw_option_type_multi_select in /wp-content/plugins/unyson/framework/includes/option-types/multi-select/class-fw-option-type-multi-select.php on line 11

I tried changing fw_option_type_multi_select to fw_option_type_multi_selectx but I get the same error, just with it saying fw_option_type_multi_selectx cannot be redeclared.

**Comment by moldcraft** [comment]
Please [download the latest Unyson dev version](https://github.com/ThemeFuse/Unyson/archive/master.zip), install it in `wp-content/plugins/unyson/` and let us know if it fixes the problem.

**Comment by otfromtot** [comment]
oh wow that was a very fast response. Just uploaded the files and am testing now. It's intermittent but I will reply when testing is done. Thank you!

**Comment by otfromtot** [comment]
It loks like this did the trick, thank you very much!

**Comment by moldcraft** [comment]
Thank you for testing!
