### ISSUE TITLE
Widget-area shortcode sidebars don't render widgets properly

### ISSUE THREAD

**Issue by dameer** [ThemeFuse/Unyson#435]
Here's what I did:

1. Appearance > Widgets ... created 3 sidebars, "For group" - "All pages", Sidebar 01, Sidebar 02 and Sidebar 03. These sidebars showed up correctly on Appearance > Widgets admin screen.

2. Added WP default widgets to each of these new sidebars: Recent Comments, Recent Posts and Tags - respectively.

3. Created new Page and used Page Builder to add 3 columns. Each of these 3 columns contain "Widget Area" shortcode. At the end I assigned my sidebars to widgetized columns.

Front-end page source code shows that widgets are not rendered properly. Here's a screenshot

![rendered_sidebars](https://cloud.githubusercontent.com/assets/1826261/7021917/ccae577a-dd26-11e4-9155-c020f7fbd320.png)

...and here's how they should be rendered with registered sidebar:
```
if( function_exists( 'register_sidebar' ) ) {
	/* default sidebar */
    register_sidebar( array(
        'name' => __( 'Default sidebar', 'kazaz' ),
        'description' => __( 'Theme\'s default sidebar', 'kazaz' ),
        'id' => 'k-default-sidebar',
        'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
        'after_widget' => '</li>',
        'before_title' => '<h3 class="title-widget">',
        'after_title' => '</h3>'
    ) );
}
```
As you may see titles are not wrapped at all, "before_widget" and "after_widget" are gone as well.
Am I missing something?

**Comment by llemurya** [comment]
@dameer please read our [documentation](http://manual.unyson.io/en/latest/extension/sidebars/index.html?highlight=sidebars), pay attention at the `dynamic_sidebar_args` in `config.php` file, try it and say if it helps.

**Comment by dameer** [comment]
Ahhhh! Thanks a bunch man, I didn't know that "config.php" for sidebars extension is commented by default, I was expecting to see the sidebar code starting/ending with `<div></div>` - as seen on docs.

So I guess it's kinda MUST to create "sidebars" folder under "framework-customizations/extensions/" and include at least "config.php", otherwise it won't work.

Appreciate your suppr quick response!
