### ISSUE TITLE
Fatal error on events extension

### ISSUE THREAD

**Issue by ziuzea87** [ThemeFuse/Unyson#436]
I get this error on Events extension:
Parse error: syntax error, unexpected '[' in /home/tfuselab/public_html/wp-content/plugins/unyson/framework/extensions/events/extensions/events-tags/class-fw-extension-events-tags.php on line 394. Is there an update ready to solve the issue?

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Events-Extension/commit/303ed0315a56171ecbdf499496770ffa2b4031dd
