### ISSUE TITLE
Failed to Access GitHub Repository for Unyson Extensions

### ISSUE THREAD

**Issue by OdayRR** [ThemeFuse/Unyson#4363]
Error Details:
Failed to access GitHub repository "ThemeFuse/Unyson-Backups-Extension" releases.
(cURL error 28: Failed to connect to github-api-cache.unyson.io port 443 after 10010 ms: Timeout was reached)

Theme Details:

Theme: Workreap (you can search online for more details)
Unyson Version: 2.7.3.1 (latest version)
Steps Taken:

Attempted to upload the extension files via FTP.
After uploading, I clicked "Activate."
The entire WordPress site became inaccessible.
Any guidance or support on resolving this issue would be greatly appreciated.

Thank you!

**Comment by kifah4it** [comment]
I have same problem.. any suggetion please ?

**Comment by San27079** [comment]
I have same problem. I find 2 ways to repair it.
1. First https://manual.unyson.io/en/latest/extensions/cookbook.html?highlight=install#download-udpate-extension-via-custom-server
2. Second in file wp-content/plugins/unyson/framework/includes/hooks.php in function  _fw_filter_github_api_url add string return $url;

`function _fw_filter_github_api_url( $url ) {
    return $url;
	return 'https://github-api-cache.unyson.io';
}`


The problem occurs because this address https://github-api-cache.unyson.io is not available

**Comment by sawwd** [comment]
Guys, you only need to filter this hook (add in your theme functions.php):

`remove_filter( 'fw_github_api_url', '_fw_filter_github_api_url' );`

That snippet will remove their `https://github-api-cache.unyson.io` and will fallback to `https://api.github.com`

**Comment by geoffreytools** [comment]
@sawwd's solution worked for me. I only needed to run it at the appropriate time.

```php
function remove_unyson_github_filter() {
    remove_filter('fw_github_api_url', '_fw_filter_github_api_url');
}

add_action('after_setup_theme', 'remove_unyson_github_filter');
```

**Comment by kevinnate267** [comment]
@geoffreytools hi bro I don't know much about coding but I found the functions.php I just don't know where to paste the code could you please help me, thanks

**Comment by geoffreytools** [comment]
@kevinnate267 It should work anywhere. `add_action` will take care of executing your function *after* Unyson adds the filter.

There may be a more semantically correct action than `after_setup_theme` but it worked for me.

**Comment by kevinnate267** [comment]
@geoffreytools Thanks for responding. 

So I went from this error (initial): Failed to access GitHub repository "ThemeFuse/Unyson-Backups-Extension" releases.
(cURL error 28: Failed to connect to github-api-cache.unyson.io port 443 after 10010 ms: Timeout was reached)

To this error (current): Github error: API rate limit exceeded for 45.8.227.175. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

After inserting this code: 
![chrome-capture-2024-9-9](https://github.com/user-attachments/assets/68d4163f-6b61-4543-85d3-6eb397426019)

I'm sorry but I'm not very good at this, would appreciate any further assistance if possible

**Comment by geoffreytools** [comment]
@kevinnate267 I understand github-api-cache.unyson.io was precisely used to avoid this issue, so I guess you are out of luck. You can always try again later when the rate limit has reset. You can pat yourself on the back for having implemented the "fix" correctly though 😅

**Comment by kevinnate267** [comment]
@geoffreytools Thank you so much! You're the only one on the entire internet with a working solution :)

**Comment by OdayRR** [comment]
function remove_unyson_github_filter() {
    remove_filter('fw_github_api_url', '_fw_filter_github_api_url');
}

add_action('after_setup_theme', 'remove_unyson_github_filter');
