### ISSUE TITLE
What's Best and Easiest Way To Create A Commercial WP Template?

### ISSUE THREAD

**Issue by portiatheme** [ThemeFuse/Unyson#437]
There are many technologies, many workflows, many ways to create a commercial template with UNYSON? Can you share your recommendations?

- PSD to HTML to WP or directly inside WP?
- Which editor?
- Less, Sass, Stylus or old school CSS?
- All Steps

**Comment by duongancol** [comment]
I don't know which way is best, but it's my way:
- PSD to WP directly
- sublime text 3
- Less
- Storefront theme from Wootheme 
- Unyson framework

**Comment by portiatheme** [comment]
Thanks for your help.

I've created PSD and HTML templates for 2-3 years. I know HTML, CSS, JS, PHP. But, I am newbie at WP. I need to learn to create WP templates anymore. However, I must specify easiest and popular way for me.

Which tutorial resources are useful for current WP standarts?

**Comment by moldcraft** [comment]
> @portiatheme Which tutorial resources are useful for current WP standarts?

https://codex.wordpress.org/WordPress_Coding_Standards

**Comment by portiatheme** [comment]
Thank you so much for Unyson and for your help. But, I recommend you to make a one page WP template with unyson tutorial video from scratch, if you want to benefit to us newbies.
