### ISSUE TITLE
Warnings&Notice About Portfolio Extension

### ISSUE THREAD

**Issue by portiatheme** [ThemeFuse/Unyson#438]
Notice: Undefined variable: other_existing_paths in /Users/User/Documents/Sites/WP/wp-content/themes/unyson/framework-customizations/extensions/portfolio/static.php on line 9

Warning: include(): Filename cannot be empty in /Users/User/Documents/Sites/WP/wp-content/themes/unyson/framework-customizations/extensions/portfolio/static.php on line 9

Warning: include(): Filename cannot be empty in /Users/User/Documents/Sites/WP/wp-content/themes/unyson/framework-customizations/extensions/portfolio/static.php on line 9

Warning: include(): Failed opening '' for inclusion (include_path='.:/Applications/MAMP/bin/php/php5.5.18/lib/php') in /Users/User/Documents/Sites/WP/wp-content/themes/unyson/framework-customizations/extensions/portfolio/static.php on line 9

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/414
