### ISSUE TITLE
Crashing with Full Backup & Demo content install 

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#439]
Hi!
I have problem with backup extension. 
When I tried to create full backup,  it run but stop in creating archive with 17.47%
![screen shot 2015-04-07 at 11 21 48 pm](https://cloud.githubusercontent.com/assets/1773011/7028062/bc65782e-dd7d-11e4-8d0a-b916bbc5d45f.png)
 
About demo install, it'be also stopped in archive process. I'm using scrach theme. 

Thanks!

**Comment by valeriuzdrobau** [comment]
Hi,
Can you look in apache error.log to see which errors occur?

**Comment by duongancol** [comment]
where can I find this file?

**Comment by duongancol** [comment]
I'm using vagrant with vvv

**Comment by valeriuzdrobau** [comment]
See [here](https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Code-Debugging).

**Comment by duongancol** [comment]
there're not any special errors in .log file. When I upload to my hosting, I can create demo content. But when I try to install this demo content on my localhost. It showed an error:
<pre>Fatal error: Maximum execution time of 30 seconds exceeded in ..plugins/unyson/framework/extensions/backup/includes/helpers/class-fw-backup-helper-file-system.php on line 132</pre>

**Comment by duongancol** [comment]
When I increased max_execution_time on php_ini, it showed other error:
<pre>File already exists [/srv/www/wordpress-default/wp-content/uploads/backup] </pre>

**Comment by duongancol** [comment]
I tried import demo on other computer with other localhost, it showed the same issue, any suggestion?

**Comment by valeriuzdrobau** [comment]
Hi, sorry for the delay
Please check that your memory is still installed wordpress, somewhere may be forgotten a .zip file.

To list files that are added to the archive, try replacing [this portion of code](https://github.com/ThemeFuse/Unyson-Backup-Extension/blob/master/includes/helpers/class-fw-backup-helper-file-system.php#L131#L136) to the following:
```
  if (is_readable($file)) {
        $zip->addFile($file, $local_name);
        $feedback->set_task('Adding '. $file);
  }
  else {
       // $log->append("error: could not read file $file");
       $feedback->set_task("error: could not read file $file");
  }
```

**Comment by duongancol** [comment]
Thanks, it showed other error:
<pre>Could not delete directory: /srv/www/culinier/htdocs/wp-content//uploads.2015_04_10-11_18_36</pre>

**Comment by valeriuzdrobau** [comment]
You can give me access to this project?

**Comment by duongancol** [comment]
Did you use vvv? I didn't upload it to hosting so couldn't give you access permission. I can create Full backup and Demo Install now but also have problem with Import Demo Install 
But as I said that, I tried some ways, even use scratch parent theme to create demo install, but it didn't work in my virtual machine, It worked well on other localhost like MAMP, xamp

**Comment by valeriuzdrobau** [comment]
Sorry, but we do not use Vagrant, please try again but before that make sure you have set the correct [file permissions](https://codex.wordpress.org/Changing_File_Permissions), and please tell me the size of your archive with auto-install.

**Comment by duongancol** [comment]
it's about 120mb

**Comment by valeriuzdrobau** [comment]
I installed vvv and I reproduced this error. You investigate and error over a few days to come back with a solution.

**Comment by duongancol** [comment]
I didn't find a solution, I tried to set admin permmision for theme folder, but it didn't work. Hope you can find solution.

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
