### ISSUE TITLE
[Request] Multiple image uploading

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#440]
It will be nice when, for example, using the slider "Add New" image button is pressed and more than one image is uploaded, all of them are automatically selected. The Shift key could also be used for selecting additional items. Something similar to the ACF image upload.

**Comment by llemurya** [comment]
@pe6o at the moment it is not possible to select multiple images. In the next version of the slider that will be redesigned we will pay attention at your suggestion, now we thinking how to make the next version of slider extension more user friendly.Thanks for the suggestion.

**Comment by pe6o** [comment]
Maybe just stack all the images with their options one above the other.
