### ISSUE TITLE
Events list outside calendar

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson#441]
Hi,

Is it possible to make an event list oustide calendar (maybe another shortcode) 

For exemple, when you create an event, where you can decide of the location, date, etc. You should have a box to add a small description to the event.
On your event page, you should be able to add another option called "event list" and you will be able to decide :

How many events to show on the page.
Show or not show small description
Show date
Show location
Event color (to have some diversity in the list)
What I want is something like that : http://www.paolini.net/events/

Thank you very much.

**Comment by GheorgheP** [comment]
Hi,

You cab create your own shortcode, with no problems. Please refer out other shortcodes as reference about how to build your shortcode.
About the option, you can add it in `framework-customizatios/theme/options/post/fw-event.php`.

We cannot add this in the Events functionality, as this is outside of the extension requirements.

In case you'll need any help in order how to build the shortcode and option, ask us.
Also please refer out Unyson  [documentation](http://manual.unyson.io/en/latest/);

**Comment by Nic787** [comment]
Hi,

I don't really know that much about php and how to create shortcode (even if I read all documentations).

It could be great if someone can help me create that for events outside calendar.

**Comment by Nic787** [comment]
UP!

**Comment by moldcraft** [comment]
> I don't really know that much about php and how to create shortcode (even if I read all documentations).

You can pay a developer/freelancer to do that for you.

**Comment by Nic787** [comment]
ok thx

**Comment by Nic787** [comment]
I will do my best to find a solution, but if someone have the time to do something : 

What I have now : http://image.noelshack.com/fichiers/2015/16/1429273866-capture-d-ecran-2015-04-17-a-08-24-17.png
 
What I would like : http://image.noelshack.com/fichiers/2015/16/1429273867-capture-d-ecran-2015-04-17-a-08-23-50.jpg

**Comment by Nic787** [comment]
Hi,

can you look if it's ok?

I follow some instructions on your website, but I don't know if what I did is wrong or not...


Also, I need help for the "view.php" which I think allow you to show what you want on the page. If you can help me, it would be appreciate. I already post a screenshots of what I would like and if you look at my options in "options.php" you will understand what to do. What will be here by default and what's not.

Thank you

**Comment by Nic787** [comment]
![shortcode](https://cloud.githubusercontent.com/assets/11185348/7310332/31dc1f78-e9f8-11e4-94f4-acfdbf4599e2.png)

**Comment by Nic787** [comment]
Need help!

**Comment by rexeze** [comment]
did you get help on creatuing your short code?
