### ISSUE TITLE
[Themeforest] : Escaping question

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#443]
Hey,

I'm just in the process of using Unyson to create a new theme and noticed a post around here about escaping/sanitizing data and searching for <code>echo $</code> in order to fix those occurrences and pass review.

I noticed there's a few places in the framework, notably the section shortcode, where some classes, inline styles and URL's aren't escaped.

Is this going to be an issue come review time?

Cheers – keep up the great work,
Martin

Source: <a href="http://themeforest.net/forums/thread/meet-unyson-the-free-drag-drop-wordpress-framework/141818?page=20&message_id=1246712#1246712">here</a>

**Comment by GheorgheP** [comment]
Hi,

Thank you for reference, we will investigate this

**Comment by thednp** [comment]
No, I thank you, this issue fixed would also help me. So thank you.

**Comment by moldcraft** [comment]
I search in all extensions and framework `echo $` and made the fixes (see the above commit references).

If you will find some unescaped attributes, please report that.

P.S. Those fixes will be included in the next extensions update.
