### ISSUE TITLE
fw_akg set  value  upload option does not stay selected

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#444]
I made custom option  https://github.com/ThemeFuse/Unyson/issues/442#issuecomment-90922114 that combines several options in to one and all of them work well by using this render model
https://github.com/ThemeFuse/Unyson/issues/427#issuecomment-89816953

aka put options in to array   $options_array[] = array...:

	'color' => array(
		'label' => __($big_text . ' background color', 'fw'),
		'type' => 'rgba-color-picker',
		'value' => fw_akg('bg_color', $option['value']),
		'desc' => __('Set '.$small_text . ' background color', 'fw')
	),
     ////   and so on 

but the fw_akg does not set the upload option to the one from db and is forcing me to check data['value '] for attachment  where all other options ( image pickers, radios, containers,text) , work fine 

		$uploaded_image = fw_akg('uploadimage', $option['value']);
		if(isset( $data['value']['bgtype']['uploadimage']['bg_type_uploadimage'])){
			$uploaded_image = $data['value']['bgtype']['uploadimage']['bg_type_uploadimage'];
		}

		'bg_type_uploadimage' => array(
			'label' => __('Upload background image', 'fw'),
			'desc' => __('Custom ' . $small_text . ' background image', 'fw'),
			'type' => 'upload',
			'value' => array(
				'attachment_id' => $uploaded_image,
				'url' => ''
			),
		/*	'value' => $uploaded_image*/
			'images_only' => true,
		)

and the frontend does not return the array with attachment_id and url but only the attachment id 
http://prntscr.com/6r8iel

My default option values are this 

            'value' => array(
				'bgtype'=>'none',
				'color'=>'',// color code
				'image'=>'', // image name with suffix
				'uploadimage'=> '',//  upload image id

			),

and the get value from input works perfect with this for all options

	/**
	 * @internal
	 */
	protected function _get_value_from_input($option, $input_value)
	{
		if (!is_array($input_value)) {
			return $option['value'];
		}

		$value = $this->_get_defaults();
		$value = $value['value'];
		
		foreach ($value as $key=> $val){
			
			if (isset($input_value[$key])) {
				$value[$key] = $input_value[$key];
			}else{
				unset($value[$key]);
			}
			
		}

		return $value;

	}

what am I missing here?

**Comment by moldcraft** [comment]
Don't play "manually" with `$option['value']`, instead use the second parameter of `fw()->backend->render_options($options, $values)` [example](https://github.com/ThemeFuse/Unyson/blob/7f826f0854b01b97406b2e567c6be9cbe47cc865/framework/includes/option-types/multi/class-fw-option-type-multi.php#L44). Also your `_get_value_from_input()` method can be [improved](https://github.com/ThemeFuse/Unyson/blob/7f826f0854b01b97406b2e567c6be9cbe47cc865/framework/includes/option-types/multi/class-fw-option-type-multi.php#L62-L67)

**Comment by danyj** [comment]
that is what I am trying to do , not manipulate anything but get the defaults and  render as it should be done , look here , this is the view 


	$options_array[] = array(
		
		'bgtype' => array(
			'type' => 'multi-picker',
			'label' => false,
			'desc' => false,
			'attr' => array(
				'class' => 'thz-bg-switch'
			),
			'picker' => array(
				'gadget' => array(
					'label' => __($big_text . ' background type', 'fw'),
					'type' => 'radio',
					'value' => fw_akg('bgtype', $option['value']),
					'choices' => array(
						'none' => __('None', 'fw'),
						'color' => __('Color', 'fw'),
						'image' => __('Predefined Image', 'fw'),
						'pattern' => __('Predefined Pattern', 'fw'),
						'uploadimage' => __('Custom Image', 'fw'),
						'video' => __('Video', 'fw')
					),
					'desc' => __('Select ' . $small_text . ' background type.', 'fw'),
					'help' => sprintf("%s", __('Select ' . $small_text . ' background type.', 'fw'))
				)
			),
			
			'choices' => array(
				'color' => array(
					'bg_type_color' => array(
						'label' => __($big_text . ' background color', 'fw'),
						'type' => 'rgba-color-picker',
						'value' => fw_akg('color', $option['value']),
						'desc' => __($big_text . ' background color', 'fw'),
						'help' => sprintf("%s", __('Set ' . $small_text . ' background color.', 'fw'))
					)
					
				), // end color
				
				'image' => array(
					'bg_type_image' => array(
						'label' => __($big_text . ' background image', 'fw'),
						'type' => 'image-picker',
						'value' => fw_akg('image', $option['value']),
						'desc' => __($big_text . ' background image', 'fw'),
						'attr' => array(
							'data-height' => 50,
							'class' => 'fw-backend-option-fixed-width'
						),
						'choices' => $images,
						'help' => sprintf("%s", __('Set ' . $small_text . ' background poster.', 'fw'))
					)
					
				), // end image
				
				
				'pattern' => array(
					'bg_type_pattern' => array(
						'label' => __($big_text . ' background pattern', 'fw'),
						'type' => 'image-picker',
						'value' => fw_akg('pattern', $option['value']),
						'desc' => __($big_text . ' background pattern', 'fw'),
						'attr' => array(
							'data-height' => 50,
							'class' => 'fw-backend-option-fixed-width'
						),
						'choices' => $patterns,
						'help' => sprintf("%s", __('Set ' . $small_text . ' background pattern.', 'fw'))
					)
					
				), // end pattern
	
				'uploadimage' => array(
					'bg_type_uploadimage' => array(
						'label' => __('Upload background image', 'fw'),
						'desc' => __('Custom ' . $small_text . ' background image', 'fw'),
						'type' => 'upload',
						'value' => array(
							'attachment_id' => $uploaded_image,
							'url' => ''
						),
					/*	'value' => $uploaded_image*/
						'help' => sprintf("%s", __('Set custom ' . $small_text . ' background image.', 'fw')),
						'images_only' => true,
					)
					
					
					
				), // end uploadimage
	
				
				
				
			),
			//'show_borders' => false,
		)
		
	);


	// print options
	if (!empty($options_array)) {
		echo fw()->backend->render_options($options_array, $data['value'], array(
			'id_prefix' => $option["attr"]["id"] . '-',
			'name_prefix' => $option["attr"]["name"]
		));
	}

all those work fine except the upload

**Comment by moldcraft** [comment]
Instead of

```
'value' => fw_akg('bgtype', $option['value'])`
```

remove the `'value'` key from all options and try

```php
if (empty($data['value'])) {
    $value = $this->_get_defaults();
    $value = $value['value'];
} else {
    $value = $data['value'];
}

echo fw()->backend->render_options(
    $options_array,
    $value, 
    array(
        'id_prefix' => $option["attr"]["id"] . '-',
        'name_prefix' => $option["attr"]["name"]
    )
);
```

**Comment by moldcraft** [comment]
Instead of

```
'value' => fw_akg('bgtype', $option['value'])`
```

remove the `'value'` key from all options and try

```php
if (empty($data['value'])) {
    $value = $this->_get_defaults();
    $value = $value['value'];
} else {
    $value = $data['value'];
}

echo fw()->backend->render_options(
    $options_array,
    $value, 
    array(
        'id_prefix' => $option["attr"]["id"] . '-',
        'name_prefix' => $option["attr"]["name"]
    )
);
```

**Comment by danyj** [comment]
I see what you mean but my option setup is not like multi , meaning I dont have 

	'options' = > array (
		option type
		option type
		...
	)


I have 

	'value' = > array (
		value1 => '',// value for option type
		value2 => '',// value for option type
		...
	)

and I think that is why I am having trouble. Il send you the option via email and if you have a sec take a look . It is not a trouble , I think given the way the option is to be setup this is the only way to get the upload set value, what just bugs me is that is missing the attachment and url in the array but other than that all values , db values and option usage work ok.

**Comment by moldcraft** [comment]
Ok send me the option.

[Here](https://github.com/ThemeFuse/Unyson/issues/110#issuecomment-66299518) is explained why you can't (should not) set default value for an `upload` option manually.

**Comment by danyj** [comment]
I am not setting it as default , you will see it is empty , what I am talking about , once you select it , and hit save , refresh the page , the image will not stay preselected in admin ( no preview). now I fixed that with the check but something just rubs me wrong on that one,

**Comment by danyj** [comment]
and by the way , that is the option I am using 4 times on   #442 , sent

**Comment by moldcraft** [comment]
The problem is in the `_get_value_from_input()` method

```php
...
$value[$key] = $input_value[$key];
...
```

you store in the database the raw values from `$_POST` without passing them through option types `_get_value_from_input()`, which is wrong. I already explained (I think multiple times, for e.g. [here](https://github.com/ThemeFuse/Unyson/issues/387#issuecomment-84084032)) that form values and database values can have different data/array structure. In this case, the `upload` option type, the form value is

```php
'option_id' => '{attachment_id}'
```

and the database value is 

```php
'option_id' => array(
    'attachment_id' => '73',
    'url' => '//site.com/...png'
)
```

I fixed your `_get_value_from_input_method()` ([diff](https://www.diffchecker.com/ywgmd885)) and made some code refactor.

*(I'll send you a email in a few minutes)*

**Comment by danyj** [comment]
yes yes , that is it and thank you for busting on it. but admit , it is a nice option :) 
you could extend the image picker with _thz_listimages function or something similar to make it easier on others to list images, 

now that this is settled we need to make admin faster. I am using it 6 times now in admin and in sections and columns inside builder. it is a drag as you already know . thnx again for all the help.

**Comment by danyj** [comment]
well not quite done or should a say small bug , you removed all default values as you mentioned earlier but now they cant be predefined trough the option and bg positions inputs stay empty 


try this 

	'somepoption'  => array(
		'type'  => 'thz-background',
		'value' => array(
			'bgtype'=>'color',
			'color'=>'#ffffff',// color code
			'image'=>'', // image name with suffix
			'pattern'=>'',// image name with suffix
			'uploadimage'=> '',//  upload image id
			'video'=>'', // video path
			'bg_color' => '',// color code
			'bg_repeat' => 'repeat',
			'bg_position_x' => '0%',
			'bg_position_y' => '0%',
			'bg_size' => 'none',
			'bg_attachment' => 'scroll',
			'images'=>'images/backrounds/posters/',// path to images located in themes folder
			'patterns'=>'images/backrounds/patterns/', // path to patterns located in themes folder
		),
		'titles'=>'Body', // used for options names/desc/help
		'label' =>false,
		'desc' => false
	),	


that should preselect the white color and populate/set all other options, not sure if we should set the  fw_akg since that is what made them be predefined

**Comment by danyj** [comment]
I mean it works as it should if I put back default values and use fw_akg , as you found the bug I had was in get_input_from_values not the structure so much

**Comment by moldcraft** [comment]
I forgot to mention that: You are using `multi-picker` inside, but the `_get_defaults()['value']` has different structure, not like [multi-picker value](http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi-picker). Your get defaults should return something like this:

```
'value' => array(
    'bgtype'=> array(
        'gadget' => 'color',
        
        'color'=>'#ffffff',// color code
        'image'=>'', // image name with suffix
        'pattern'=>'',// image name with suffix
        'uploadimage'=> '',//  upload image id
        'video'=>'', // video path
    ),
    'bg_color' => '',// color code
    'bg_repeat' => 'repeat',
    'bg_position_x' => '0%',
    'bg_position_y' => '0%',
    'bg_size' => 'none',
    'bg_attachment' => 'scroll',
    'images'=>'images/backrounds/posters/',// path to images located in themes folder
    'patterns'=>'images/backrounds/patterns/', // path to patterns located in themes folder
),
```

*I am not sure if I made correctly the array, but you get the idea.*

So you decide, fix the `_get_defaults()['value']` or add back `fw_akg` and make manual hacks.

**Comment by danyj** [comment]
understand but even with restructure all those below the picker  do not have defaults set  because the value from options array is gone so the option just renders without presets

**Comment by danyj** [comment]
I am not so sure why you see it as a hack ,  here  you advised me to use it  on fw()->backend->option_type 
https://github.com/ThemeFuse/Unyson/issues/280#issuecomment-75854780
and on #427  we just moved single echos to an array and printed them. Not sure why you think that I am manipulating the option ,  I am setting the default one to user predefined , and once saved it is using the saved value or am I missing something here.

**Comment by moldcraft** [comment]
Yesterday I didn't tested the option very much, I am looking at it now and fixing the `_get_defaults()['value']`. Give me some minutes, I'll send you an email.

**Comment by danyj** [comment]
ok bud , thnx for looking over and dont rush I am ok for now, keep this option ready,  you can use it to test #442

**Comment by moldcraft** [comment]
`fw_print($data['value']);` inside `_render()` shows me this

```text
array
(
    [bgtype] => array
    (
        [gadget] => 'uploadimage'
        [color] => array
        (
            [bg_type_color] => '#ffffff'
        )
        [image] => array
        (
            [bg_type_image] => ''
        )
        [pattern] => array
        (
            [bg_type_pattern] => ''
        )
        [uploadimage] => array
        (
            [bg_type_uploadimage] => array
            (
                [attachment_id] => '85'
                [url] => '//wordpress.dev/wp-content/uploads/2015/04/1290153351522.jpg'
            )
        )
        [video] => array
        (
            [bg_type_video] => ''
        )
    )
    [bg_color] => ''
    [bg_repeat] => 'repeat'
    [bg_position_x] => '0%'
    [bg_position_y] => '0%'
    [bg_size] => array
    (
        [gadget] => 'none'
        [custom] => array
        (
            [bg_custom_size] => ''
        )
    )
    [bg_attachment] => 'scroll'
)
```

so that structure should be in `_get_defaults()['value']`.

----

Here is how the `_render()`, `_get_value_from_input()` and `_get_defaults()` methods looks now.


	/**
	 * @internal
	 */
	protected function _render($id, $option, $data)
	{
		return fw_render_view(dirname(__FILE__) . '/view.php', array(
			'id' => $id,
			'option' => $option,
			'data' => $data,
			'options' => $this->get_inner_options(
				$id, $option, $data,
				$this->_thz_listimages($option['images'],'small/',false),
				$this->_thz_listimages($option['patterns'],false,false)
			),
		));
	}

	/**
	 * @internal
	 */
	protected function _get_value_from_input($option, $input_value)
	{
		if (empty($input_value) || !is_array($input_value)) {
			return $option['value'];
		}

		$inner_options = $this->get_inner_options(
			'unknown', $option, array(),
			$this->_thz_listimages($option['images'],'small/',false),
			$this->_thz_listimages($option['patterns'],false,false)
		);

		$value = array();
		foreach (fw_extract_only_options($inner_options) as $inner_id => $inner_option) {
			$value[$inner_id] = fw()->backend->option_type($inner_option['type'])->get_value_from_input(
				$inner_option,
				isset($input_value[$inner_id]) ? $input_value[$inner_id] : null
			);
		}

		return $value;
	}


	/**
	 * @internal
	 */
	protected function _get_defaults()
	{
		return array(
			'value' => array(
				'bgtype' => array(
					'gadget' => 'none',

					'color' => array(
						'bg_type_color' => ''
					),
					'image' => array(
						'bg_type_image' => ''
					),
					'pattern' => array(
						'bg_type_pattern' => ''
					),
					'uploadimage' => array(
						'bg_type_uploadimage' => array(),
			        ),
			        'video' => array(
						'bg_type_video' => ''
					),
			    ),
			    'bg_color' => '',
				'bg_repeat' => 'repeat',
				'bg_position_x' => '0%',
				'bg_position_y' => '0%',
				'bg_size' => array(
					'gadget' => 'none',
					'custom' => array(
						'bg_custom_size' => ''
					),
			    ),
			    'bg_attachment' => 'scroll'
			),

			// I moved these outside 'value'
			'images' => 'images/backrounds/posters/', // path to images located in themes folder
			'patterns' => 'images/backrounds/patterns/', // path to patterns located in themes folder

			'titles' => 'container', // used for options names/desc/help
		);
	}


Seems to work. I pressed "Reset" then changed some values `_get_defaults()['value']` then added the `'value'` key in the option array, and the value is reflected on the page.

*Email sent.*

**Comment by danyj** [comment]
yes, I was trying to simplify the default  and not  "re array" it but looks like we should stick to it. ok bud thnx much for all the effort!
