### ISSUE TITLE
Time option type

### ISSUE THREAD

**Issue by martin-bede** [ThemeFuse/Unyson#448]
Hi,

Is there plans for a time option type similar to the date-picker option type?

Thanks,
Martin

**Comment by GheorgheP** [comment]
Hi,

Yes, we are planing to make a such option, but after we'll finish some important things framework.

**Comment by martin-bede** [comment]
I've actually just looked in the framework and it looks like there's already a `datetime-picker` type which seems to work fine.
Looks like it just needs adding to the docs here http://manual.unyson.io/en/latest/options/built-in-option-types.html#content

**Comment by martin-bede** [comment]
Is the previously mentioned `datetime-picker` safe to use or is there a reason it's omitted from the docs?
