### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#450]
Hi,

Thanks for the perfect framework.

When i create a sidebar and add it as page specific, its working okay. But when i refresh the page and i edit one page specific widget, i cannot save it anymore. It wont let me select the widget created for the specific pages.

**Comment by llemurya** [comment]
@nickkuijpers please make a screencast with all workflow ,because I tested and for me it is work perfect.

**Comment by nickkuijpers** [comment]
Its a theme based problem i see, will check out where. Thanks for the comment.
