### ISSUE TITLE
Icon option show one group

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#452]
Is there a way to show only one group of icons and not others for example only brand icons ?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/371

**Comment by danyj** [comment]
Was just about to say I managed with his 


	function _filter_theme_socials_icon_set($sets) {
		$sets['socials'] = array(
			'font-style-src'  => 'data:text/css;charset=utf-8;base64,LyoqLw==',
			'groups' => array(
				'socials' => __('Social icons', 'fw'),
			),
			'icons' => array(
				'fa fa-facebook' => array('group' => 'socials'),
				'fa fa-facebook-official' => array('group' => 'socials'),
				'fa fa-facebook-square' => array('group' => 'socials'),
			),
		);
	
		return $sets;
	}
	add_filter('fw_option_type_icon_sets', '_filter_theme_socials_icon_set');


but it would be nice to do this instead 


				'social_icon' => array(
					'type'  => 'icon',
					'value' => 'fa-facebook',
					'label' => __('Social icon', 'fw'),
					'group'  => 'brand',
				),

**Comment by moldcraft** [comment]
```
'font-style-src'  => 'data:text/css;charset=utf-8;base64,LyoqLw==',
```

I remember that I tried this but WordPress trasformed it to something like this

```
http://domain.com/data:test/css;...
```

**Comment by danyj** [comment]
Ahh you right I see is not picking it up

**Comment by danyj** [comment]
I thought  this would work 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon/class-fw-option-type-icon.php#L144

**Comment by danyj** [comment]
blank works  'font-style-src'  => '',  thx for point it out

**Comment by moldcraft** [comment]
Maybe we should open a ticket in WordPress code to fix this, to allow dataUri in `wp_enqueue_style|script()` ?

**Comment by danyj** [comment]
side note , if you leave out 

'font-style-src'  => ''

you get undefined index error , you might want to check that in

as for the dataUri , I am more concerned about theme check since it is using base64 and I have it inside the theme folder, it did pass dough.

**Comment by moldcraft** [comment]
you can create dataUri non base64 encoded

**Comment by danyj** [comment]
true,  but since I am just using few social icons and empty src is not showing errors  I think we are good or ?

**Comment by moldcraft** [comment]
it works only because on the same page there is another icon option that enqueued fontawesome (has it in 'font-style-src'). If you clear your options array and add only the icon option with empty 'font-style-src', the icons will not show because fontawesome is not enqueued (but I don't think this will happen in practice, just to let you know).

**Comment by danyj** [comment]
was just about to tell you that , it picks up the icons from fa but the style is smaller than the default ones

**Comment by moldcraft** [comment]
You did not specified the `container-class` parameter https://github.com/ThemeFuse/Unyson/issues/371#issuecomment-82525378

**Comment by danyj** [comment]
how do we go around it , need to link the style for it ? 
thnx for container point , they look ok now ,  

thing is I dont have any other icons set in theme admin , this is the only one 
It is picking them up from 
    wp_enqueue_style( 'fw-font-awesome' );
I loaded it in admin in case is needed, do you see a problem with it , I am using using your 


	add_action('fw_admin_enqueue_scripts:settings', '_thz_admin_scripts');
	add_action('fw_admin_enqueue_scripts:post', '_thz_admin_scripts');


and  fa is loaded inside  _thz_admin_scripts

**Comment by moldcraft** [comment]
Try

```
$sets['socials'] = array(
    'font-style-src'  => $sets['fontawesome']['font-style-src'],
    ...
);
```

**Comment by danyj** [comment]
nice save :)  :+1:
