### ISSUE TITLE
underscore templates `<%` in html are treated as php code on servers with `asp_tags` enabled

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#453]
http://php.net/manual/en/ini.core.php#ini.asp-tags

[This](https://github.com/ThemeFuse/Unyson/blob/f9beb0a861acfc09be2f86a116a9d3c37c3f374a/framework/includes/option-types/upload/views/images-only.php#L32) must be placed in a string.

----

Replace

```php
<br data-template="<?php ob_start(); ?>
Hello <%= someTemplateVar.someAttribute %>!
<?php echo fw_htmlspecialchars(fw_ob_get_clean()); ?>" />
```

with

```php
<br data-template="<?php fw_htmlspecialchars(
    'Hello <%= someTemplateVar.someAttribute %>!'; 
?>" />
```

**Comment by danyj** [comment]
leave ob start and end as is and just place the underscore  snip inside fw_specialchars? 
so in image option case replace this 

    <img src="<%= data.src %>" alt="<%= data.alt %>"/>

with 

    <?php echo fw_htmlspecialchars('<img src="<%= data.src %>" alt="<%= data.alt %>"/>') ?>

is that correct ?

**Comment by danyj** [comment]
OK so this 

	<br class="thumb-template-not-empty fw-hidden" data-template="
	<?php echo fw_htmlspecialchars('<img src="<%= data.src %>" alt="<%= data.alt %>"/><a href="#" class="dashicons fw-x clear-uploads-thumb"></a>') ?>" />

would be replacement for

https://github.com/ThemeFuse/Unyson/blob/f9beb0a861acfc09be2f86a116a9d3c37c3f374a/framework/includes/option-types/upload/views/images-only.php#L31-L34

correct ?

or should I leave the  a outside of the fw_specialchars ?

**Comment by moldcraft** [comment]
yes, the replacement is correct.

**Comment by moldcraft** [comment]
*The problem was only in `upload` and `multi-upload` option types.*
