### ISSUE TITLE
Full width shortcode

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#455]
Okay, I'm creating Hero Image shortcode but it's wrapped in a `cols-sm-12' which adds left and right padding that I don't want.

I guess it has something to do with overwriting:
`extensions\builder\config.php`
but it doesn't seem to work.

So how can I achieve a shortcode that's not wrapped in a `col` class - be it a hero image or a full width slider?

**Comment by martin-bede** [comment]
Hi,
I got around a similar issue by adding the section shortcode to my theme as you would if you were extending any other shortcode.
I then added an option for the user to make the section full width which when active adds a class to the container which removes padding and margin.

I'm now able to put a slider within and it can be full width.

Hope this helps,
Martin

**Comment by pe6o** [comment]
Tried this but it didn't work. It outputs:

```html
<div class="fw-container">	
	<div class="fw-row">
		<div class="fw-col-xs-12">
			<div class="hero-image"></div>
		</div>
	</div>
</div>
```

Anyway, it's strange workaround and I expect a lot of support question from my clients and I'll have to keep telling them to insert a section.

It will be nice if I could enter in **builder/config.php**:

```php
$cfg['default_item_widths'] = array(
	'hero_image' => array(
		'title'          => '1/1',
		'backend_class'  => false,
		'frontend_class' =>false
	),
);
```

**Comment by levan1993** [comment]
Hi 
you can create config file in your {theme_dir/framework-customizations/extensions/shortcodes/extensions/page-builder/config.php} and add $cfg['disalbe_correction'] = true;
This will force page-builder to output layout as it was build in backend without wrapping it into column.

**Comment by pe6o** [comment]
Created
*framework-customizations\extensions\shortcodes\extensions\page-builder*

Wrote:

```php
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$cfg = array();
$cfg['disalbe_correction'] = true;
```
But it doesn't work.

Why even in the class-fw-option-type-page-builder.php it's written disa**lb**e?

Anyway, even if this worked, I guess it would remove the wrapping of all shortcodes (which is not good)?

**Comment by GheorgheP** [comment]
Hi,

@martin-bede provided you the correct answer to the question. You have to create a section, make it full width and drop your shortcodes in that section.

**Why just like this?**
Because, by default is supposed that the page has a grid and if you did not disable the col-sm-12 grid from builder config, then you use the grid for sure. That means that the content you'll set in the page has to be set in that grid, that's why for all shortodes you set in the page content and don't give them a section and column because they needs to be rendered in grid. Full width items are more specific, so for those you have to specify manually that they needs to be full width.

In future we want to create the opportunity for developers to be able to specify if the shortcodes is full width or not, but at the moment this is not possible.

Now we cannot remove the auto  wrapping, as this will break all other users content.

**Comment by pe6o** [comment]
I supposed it's something like that. When Full Width is set to "Yes", the `.fw-container-fluid` is giving a padding left and right of `15px`. So I guess the solution is to add `margin-left: -15px` and `margin-right: -15px` to the shortcode?

**Comment by pe6o** [comment]
I supposed it's something like that. 

When Full Width is set to "Yes", the `.fw-container-fluid` is giving a padding left and right of `15px`. So I guess the solution is to add `margin-left: -15px` and `margin-right: -15px` to the shortcode?

Edit: Okay, it seems it's kind of the same - with or without Full Width checked. One is adding `fw-container` the other - `fw-container-fluid` which have the same properties. From bootstrap I know that they render different the columns width but in this example we don't have columns. So it seems in the end it doesn't matter if it's On or Off?

![section](https://cloud.githubusercontent.com/assets/1108563/7155933/5b352ea2-e36b-11e4-8cd4-48512232d380.png)

**Comment by GheorgheP** [comment]
Hi,

If I understand correctly, you do not want to set the items to be full width to entire screen, but for the items that are not in column to remove the 15px padding?

In this case you have to remove the padding of the col-12 items.

**Comment by pe6o** [comment]
Oh....!

*framework-customizations\extensions\shortcodes\extensions\page-builder\config.php*
```php
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$cfg = array();
$cfg['disalbe_correction'] = true;
```
This works! It seems earlier, I didn't click the Update button on the page.
Now the hero-image (and slider) is out of any wrappers
![ddd](https://cloud.githubusercontent.com/assets/1108563/7185410/1f5f11a8-e46b-11e4-9b9e-3ab23ea8d8be.png)

@levan1993 Thanks! I didn't do it earlier as it should be.
