### ISSUE TITLE
Multi Select Population?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#456]
It seems that when I create a `multi-select` field, I have to input the exact post name to select it.

Is there an option which I can use to add multiple posts, and allows me to search and browse the populated list with options. Something like this:

![opt](https://cloud.githubusercontent.com/assets/1108563/7101073/f55de50a-e04b-11e4-9f2e-549820eeb827.png)

-- or --

![relationship_input](https://cloud.githubusercontent.com/assets/1108563/7101074/13dae488-e04c-11e4-841e-c6792db22e4e.jpg)

**Comment by duongancol** [comment]
check it https://github.com/ThemeFuse/Unyson/issues/384

**Comment by pe6o** [comment]
So for now, the solution is to create a custom function that populates an array for the 'choices' key?

What should be in this array - post names, IDs?

**Comment by duongancol** [comment]
I think so
Actually , Unyson support population with posts, users, categories but you have to input keyword. It'll show suggestions. But it's not convenient, hope that @GheorgheP will consider this feature.

**Comment by danyj** [comment]
You might want to do this for sidebars also
http://prntscr.com/6sutlt

**Comment by pe6o** [comment]
Such thing would be very nice to when creating for example Featured Posts carousel/section.

**Comment by GheorgheP** [comment]
Hi,

Yes, we have this already in our task list, and we will do it, but first need to solve other serious things. But this will be done in next versions.

**Comment by pe6o** [comment]
That's s nice to know!

I'm in the middle of my project and was thinking - can you recommend the best option to implement a Featured Posts Shortcode?

A Shortcode with a field where the user selects which of his posts he wants to be shown as a carousel on the front page?

**Comment by pe6o** [comment]
For everyone else who stumbles on this thread one way or another..

For now I ended up with the following code in
*framework-customizations\theme\options\general-settings.php*

```php
$choices = array();

$args = array(
	'post_type' => 'post',
	'posts_per_page' => -1
);

$the_query = new WP_Query($args);

if ($the_query->have_posts()) : while ($the_query->have_posts()) : $the_query->the_post();

	$choices[get_the_ID()] = get_the_title();

endwhile; endif;

$options = array(
	'general' => array(
		'title'   => __( 'General', 'subsolar' ),
		'type'    => 'tab',
		'options' => array(
			'general-box' => array(
				'title'   => __( 'General Settings', 'subsolar' ),
				'type'    => 'box',
				'options' => array(
					'featured' => array(
						'type'  => 'multi-select',
						'label' => __('Label', 'fw'),
						'desc'  => __('Description', 'fw'),
						'population' => 'array',
						'choices' => $choices,
					)
				)
			),
		)
	)
);
```

Is there some better way for now or a better place that the array population code can reside in?

**Comment by pe6o** [comment]
(I know I'm posting three continuous posts but this is the best way that I can separate the different solutions.)

So yeah, for any future guys and gals that stumble on this thread. Another solution that I created is using the `addable-option` field. I'm populating it with `multi-select` fields with `'limit' => 1'. I don't use 'select' because it doesn't have search feature (it would be nice idea tho).

```php
'featured_posts' => array(
	'label'  => __( 'Featured Posts', 'subsolar' ),
	'type'   => 'addable-option',
	'attr'  => array( 'data-fw-repeatable' => 'no' ),
	'option' => array(
		'type'  => 'multi-select',
		'label' => __('Label', 'fw'),
		'desc'  => __('Description', 'fw'),
		'population' => 'array',
		'choices' => $choices,
		'limit' => 1,
	),
),
```

I think that this is the best that can be achieved for such functionality.
![featured2](https://cloud.githubusercontent.com/assets/1108563/7181459/905684f8-e453-11e4-907b-8bffd1487e76.png)

Only the above question stays - Is there some better way for now or a better place to put the array population code in (not on top of general-settings.php)?

**Comment by danyj** [comment]
putt population array in helpers.php inside a function and call it in option, this way you can always reuse it if needed for other option or anything elese

**Comment by pe6o** [comment]
By "call it in option" you mean the file where the $options array is?

**Comment by pe6o** [comment]
By "call it in option" you mean the file where the `$options` array is?

**Comment by danyj** [comment]
just as you did above but instead  variable  $choices you would use your new function

**Comment by duongancol** [comment]
Hi @GheorgheP : I tested and it worked well but I think you should add search box, so user can search in population list if they have to much page, taxonomy,...

**Comment by duongancol** [comment]
Hi @GheorgheP : is there any ways to get post that not in Trash? I use multi-select option with post population but don't want to get post from Trash
