### ISSUE TITLE
You don't initially get a list of pages when using the page population method

### ISSUE THREAD

**Issue by martin-bede** [ThemeFuse/Unyson#457]
When using the page population method you don't get a list of pages when clicking the drop down.
Instead you must start typing the page name in the input for it to appear.

**Comment by pe6o** [comment]
+1

Just proposed this yesterday. It would be nice. https://github.com/ThemeFuse/Unyson/issues/456

**Comment by danyj** [comment]
:+1:

**Comment by duongancol** [comment]
:+1:

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson/issues/457

**Comment by pe6o** [comment]
I suppose you mean https://github.com/ThemeFuse/Unyson/issues/456
