### ISSUE TITLE
wp_localize_script() have to be in inc/static.php?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#459]
I'm using the framework directory structure. I've created a function in **inc/hooks.php***:

```php
function _action_ajax_enqueue_scripts() {

	wp_localize_script( 'fw-theme-script', 'prefix', array(
		'ajaxurl' => admin_url( 'admin-ajax.php' )
		));

}
add_action( 'wp_enqueue_scripts', '_action_ajax_enqueue_scripts' );
```

And in **inc/static.php**:
```php
wp_enqueue_script(
	'fw-theme-script',
	get_template_directory_uri() . '/assets/js/scripts.js',
	array( 'jquery' ),
	'1.0',
	true
);
```
But it doesn't work. The main script is still not enqueued?

When I wrote `wp_localize_script` in **static.php** just after enqueuing the script, it worked. I thought that *static.php** is only for `wp_enqueue_script` and `wp_enqueue_style`?

**Comment by moldcraft** [comment]
Try

```
add_action( 'wp_enqueue_scripts', '_action_ajax_enqueue_scripts', 11 );
```

**Comment by pe6o** [comment]
Hmm, strange, still gives:

`Uncaught ReferenceError: prefix is not defined`

**Comment by moldcraft** [comment]
[Ops](https://github.com/ThemeFuse/Theme-Includes/blob/af796dd5b46880383ec4944750eb60a918040296/init.php#L41). Try

```php
add_action( 'wp_enqueue_scripts', '_action_ajax_enqueue_scripts', 21 );
```

**Comment by pe6o** [comment]
Heh, I tried with 15. Now it works!

**Comment by pe6o** [comment]
Okay, tried putting `wp_enqueue_script` in `if ( is_admin() )` in **inc/static.php**

... and it doesn't work...

**Comment by moldcraft** [comment]
It should work. Debug and find why it doesn't.

`inc/static.php` has nothing with Unyson.

**Comment by pe6o** [comment]
Hmm, I got it from the Scratch theme and saw just now that in `init.php` is written:

```php
if (!is_admin()) {
	add_action('wp_enqueue_scripts', array(__CLASS__, '_action_enqueue_scripts'),
		20 // Include later to be able to make wp_dequeue_style|script()
	);
}
```

I was with the impression that it enqueues admin scripts too. Gotta change it to include them.
