### ISSUE TITLE
Mega menu extension missing

### ISSUE THREAD

**Issue by wp-sysop** [ThemeFuse/Unyson#460]
After I installed Unyson 2.2.7, I went to install mega menu and it wasn't on the list of available extensions. Is this a known bug? Do I have to use a certain theme? I've tried a few; none work. What am I missing?

I'm running WP 4.1.1, PHP 5.6 and MySQL 5.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/392#issuecomment-85102904
