### ISSUE TITLE
How to get page options complete layout

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#461]
fw()->theme->get_settings_options()  gets the theme options with all tabs and options 
how do I do the same for page options ? 

    fw()->theme->get_post_options('page')

gets the builder and side meta boxes , I am only after 

Page options
this one
http://prntscr.com/6trzvy

lazy to dig :)

**Comment by moldcraft** [comment]
There is no such feature in Unyson, unfortunately you will have to dig.

But I see that box is on the first level (not somewhere inside other options) and you should be able to access it easy

```php
$page_options = fw()->theme->get_post_options('page');
$box = $page_options['{box_id}'];
```

**Comment by danyj** [comment]
yes yes , just saw it , thank you , closing!

**Comment by danyj** [comment]
for amyone else 


    $page_options = fw()->theme->get_post_options('page');
    $box = $page_options['{main}'];
