### ISSUE TITLE
Scratch theme officialy does not work at all with latest plugin version

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#462]
I just updated unyson and download latest scratch , there is a bug in face widget 
 Can't use method return value in write context in

    inc\widgets\facebook-page-stream\class-widget-facebook-page-stream.php on line 4

that should be something like 

	$fw_social_facebook =  fw()->extensions->get( 'social-facebook' );
	
	if ( defined( 'FW' ) && ! empty( $fw_social_facebook ) ) {

and one more 

include(): Filename cannot be empty i

t\framework-customizations\extensions\portfolio\static.php on line 9  fixed with #378

**Comment by valeriuzdrobau** [comment]
I [pushed ](https://github.com/ThemeFuse/Scratch-Theme/commit/609e4f2d518eada64a83c79bf64bc1921905fa42) for the Facebook widget changes. If and portfolio extension has problems, open a new issue.

**Comment by danyj** [comment]
i am not using it , just giving you heads up since new users will want to test the scratch that you are pushing in first unyson git paragraph
