### ISSUE TITLE
"Theme Settings" issue

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson#466]
Hi there,
When I have two <code>'type' => 'box'</code> in a tab, the second box will be forced to close. I just want to have it always opened whenever initialized. How can I do it ?
Any helps would be appreciated. Thanks.

**Comment by moldcraft** [comment]
At the moment you can't. I will add that possibility in the next release (soon).

**Comment by moldcraft** [comment]
```php
array(
	'type' => 'box',
	'attr' => array(
		'class' => 'prevent-auto-close'
	),
	'title' => 'Test',
	'options' => array(
		// ...
	)
)
```
