### ISSUE TITLE
Column config override texts not effective

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#467]
I extended section and columns shotcode in my theme , the  title override for section works fine 

http://prntscr.com/6ufyvh
for column it does not 

http://prntscr.com/6ufyzz
http://prntscr.com/6ufz3b

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/c5ea0e7441628ac861581aa820ec1d63868e3898
