### ISSUE TITLE
Shortcodes attributes are not decoded if page-builder is disabled

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#469]
How to reproduce:

1. Create a page with builder and add the calendar shortcode
2. Save the page and view it in frontend, everything is fine [screenshot](https://static.md/c59c0099e09424cd3b243daf88550010.png)
3. Deactivate Page Builder
4. Refresh the frontend and you will see notices [screenshot](https://static.md/31629fdc476730eaca7a5c57b1fb07b6.png)

@rockalife 
* Why [shortcode atts coder](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/1bfd3147baa19f1911c0910f2ca4ea76e06932e0/includes/class-fw-ext-page-builder-shortcode-atts-coder.php) was placed in Page Builder extension but not in Shortcodes?
* It will be ok if I will move the coder to the Shortcodes extension and do not check [this attr](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/1bfd3147baa19f1911c0910f2ca4ea76e06932e0/includes/class-fw-ext-page-builder-shortcode-atts-coder.php#L47), instead encode/decode everything?

**Comment by danyj** [comment]
is this going to make it in new release?

**Comment by moldcraft** [comment]
Not in this release.
@rockalife doesn't know a solution (it's complicated). I will inspect this and will try to find one. I will try to move the coder in the Shortcodes extension and make sure it will not break something.

**Comment by moldcraft** [comment]
I have no idea how to fix this. I think it doesn't have a solution.

----

By default the shortcodes attributes are not encoded at all

* The problem

    ```
    [button label="Hi" link="#" target="_blank"]
    ```
    
    When you store plain text values in attributes everything works fine.
    
    But when you have advanced shortcodes which need to store complex (array) values in attributes, the problems begins.
    You can test the above shortcode in a page (switch to default editor and copy/paste it).
    Next, try this shortcode with a json value attribute:
    
    ```
    [button label="Hi" json="[1,2,3]" link="#" target="_blank"]
    ```
    
    The problem: `[1` will be treated by WordPress as a shortcode start and it will break everything.

* Current solution

    We decided that the Shortcodes extension will generate and save the shortcodes attributes as they are, without making any changes/encoding.
    So the Shortcodes extension doesn't care about the above problem.
    But it provides [a filter](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/89597be5467cb7747a1983a5b7aff797a08c5c0a/includes/class-fw-shortcode.php#L138) for other extensions to make some corrections/changes in attributes.
    
    * The PageBuilder extension.
    
        Back in v1 attributes values were encoded with base64:
    
        ```
        [button label="SGk=" json="WzEsMiwzXQ==" link="Iw==" target="X2JsYW5r"]
        ```
        
        This works fine, but base64 is not allowed in WordPress. *Also the users complained about those weird strings.*
        
        In v2 we changed the encoding to [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/0f61b426f45dd4b70cb9013c56077a55ddeab2c4/includes/class-fw-ext-page-builder-shortcode-atts-coder.php#L33-L43)
        
        ```
        [button label="Hi" json="&#91;1,2,3&#93;" _made_with_builder="true" link="#" target="_blank"]
        ```
        
        Note: It adds the `_made_with_builder="true"` attribute to mark that the shortcode attributes were encoded with its method, and [does the decode only for the shorcodes which has that attribute](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/0f61b426f45dd4b70cb9013c56077a55ddeab2c4/includes/class-fw-ext-page-builder-shortcode-atts-coder.php#L47).
        
        This method also works fine. There was a problem with revisions but we [fixed it](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/0f61b426f45dd4b70cb9013c56077a55ddeab2c4/class-fw-extension-page-builder.php#L195-L222).

    * The EditorShortcodes extension.

        It stores attributes in a completelly different way:
        
        * In post content

            ```
            [button fw_shortcode_id="2"]

            &nbsp;
            
            [button fw_shortcode_id="1"]
            ```
        
        * In post meta
        
            ```
            {
                "button": {
                    "2":{"label":"Hi","link":"#","target":"_blank","color":""},
                    "1":{"label":"Submit","link":"#","target":"_blank","color":""}
                }
            }
            ```

    However, it doesn't matter how other extensions encode the shortcodes attributes, 
    the point is that they can use completelly different encoding methods and only they knows how the attributes were encoded and how to decode them.
    
    The problem: If you created a page with PageBuilder or EditorShortcodes, on frontend display, the extension that was used will take care to decode the attributes so they will work properly.
    If you disable that extension, the Shortcodes extension has no idea how to decode the attributes and will send in views (the [`$atts` variable](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/81ff13ae4ed787779752ceb392b221d0b6651b96/shortcodes/calendar/views/view.php#L8) within shortcode view)
    raw/encoded attributes and will cause notices/warnings/errors because the view expects that the `$atts` variable will contain [shortcode options values](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/81ff13ae4ed787779752ceb392b221d0b6651b96/shortcodes/calendar/options.php).
    
    This solution was created in Unyson v1 when the framework was built-in theme and the extensions were part of the framework (there was no Unyson Extensions page in admin where you can install/remove them), there was only one repository, it was all-in-one.
    That's why it wasn't designed to handle the case when the PageBuilder or the EditorShortcodes extension can be disabled.

**Comment by danyj** [comment]
ok cant you at least add a notice untill actual fix is found that user should enable that extension instead of just let them see php errors? 

so instead of this 
https://static.md/31629fdc476730eaca7a5c57b1fb07b6.png


show 

   Please enable Page builder extension

**Comment by moldcraft** [comment]
How the Shortcodes extension will know/detect that the attributes were encoded with PageBuilder or ShortcodeEditor *(or any other extension that can appear in the future)* ?

**Comment by danyj** [comment]
you have 

    _made_with_builder

and this brings us back to the original issue , why was shortcodes hooked to builder only in the first place. It should have been standalone so that we can use it anywhere and without the builder.

**Comment by danyj** [comment]
But we really need to clean things up , this is going to cause trouble 

Your git is ordered in the right way , you have unyson and extensions , but when we look in unyson backend you are mixing things up and downloading dependable's. 
To me this should have been clear 



Page Builder is an extension , show it in backend   ( builder class should be in core ) 
Shortcodes is an extension ( should be standalone ) show it in backend 

If I install builder only than I will have only sections and columns 


If I install shortcodes , than I will have additional shortcodes visible in page builder and those shortcodes should be in each editor trough out the site not depending on builder 


but you do this 


I install builder ,  you download shortocde

I disable the builder , my shordcodes dont work. Makes no sense.

**Comment by moldcraft** [comment]
> you have
>
>     _made_with_builder

Moving the PageBuilder logic to Shortcodes doesn't look fine. Of course the users doesn't care about this and we should do everything to prevent errors and sad clients.

----

Hmm, what if the Shortcodes extension will introduce it's own attribute

* `[button _fw_coder_ext="page-builder" ...]`
* `[button _fw_coder_ext="shortcode-editor" ...]`

that will store the extension id that made the encoding, and if that extension is not active, the shortcode will not be displayed/process, or a warning message will be displayed in frontend (like the one you suggested above).

I try to implement this.

**Comment by danyj** [comment]
honestly instead of going trough and fixing bugs that might kick us in the a.. in future , we need to order things in the right way. You did great with all other extensions but you made a bit of a mess with builder class , page builder and shortcodes

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/469#issuecomment-104883258

[This](https://static.md/70c9e4dcb9a20f4d6d99ef614e0f529a.png) is why the Shortcodes extension depends on Builder.

You can create a separate issue especially for reorganizing extensions and dependencies and describe all your ideas there. *But I am not sure if it will be possible to do that.*

**Comment by moldcraft** [comment]
I will move page-builder and editor-shortcodes coders in the shortcodes extensions, and the sub-extensions will be able to tell shortcodes extension which encode/decode method to use.

*That will not cause major changes and will work with already existing pages. But I will do that next week, I am busy with other project.*

**Comment by NazarkinRoman** [comment]
@moldcraft I use shortcodes inside Contact Form 7 plugin via this fix - http://wordpress.stackexchange.com/a/45307

But after a latest update, my shortcodes are not working with error: **Shortcode attributes decode error: No decoder found**

How can I make it work again? Thanks.
