### ISSUE TITLE
Demo Installer Keeps the original Site Address 

### ISSUE THREAD

**Issue by azharijelek** [ThemeFuse/Unyson#470]
Hi guys, really great work here.

I've finally released my theme on Themeforest and make a lot of sales. Thank you.

But, there are 2 customers of mine that complaining demo installer issue.

The main point is the installer doesn't change the original site address url (from database.txt) into their current site url. 

Let's say, I've generated my theme with demo content in it (using backup extension of course). 
And we know that the <strong>database.txt</strong> contains site address strings: <code>user-pc/olea</code> (it's basically like <code>localhost/mytheme</code>). 

But, when my customers installed the demo content, the site address is still <code>user-pc/olea</code>. 

For live example, I can provide you the site of my customer's: http://www.inspiredbycarli.com. If you view the source, you will understand what I mean. <code>user-pc/olea</code> is still there. They also can't login to their dashboard because once they access their wp-admin, the site will redirect to "http://user-pc/olea" too.

Why is that? is there something wrong with my method to generate the demo content?

Thank you in advance.

**Comment by azharijelek** [comment]
anyone?

**Comment by danyj** [comment]
@azharijelek  it is weekend bud , I'm sure team will look at it as soon as they get to work.

**Comment by valeriuzdrobau** [comment]
Hi, I need to see if there are some errors in errors.log, and if possible to have access to the dashboard and FTP.
