### ISSUE TITLE
using translation extension

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#471]
Hi!
I tried to add translation extension with my theme. 
When I followed Documentation, I didn't know how to make it work with my theme.
Could you describe more detail about that?

Thanks so much!

**Comment by llemurya** [comment]
@duongancol I made for you a video presentation https://youtu.be/hWgZmlXD4B8, please say if it helps and close the issue.

**Comment by duongancol** [comment]
It's totally helpful ! Thank you su much!

**Comment by danyj** [comment]
@llemurya :100:
