### ISSUE TITLE
Extend Mailer Extension

### ISSUE THREAD

**Issue by rawcreative** [ThemeFuse/Unyson#472]
Is it possible to extend the Mailer extension? I've tried a few different ways but non seem to work. I have two clients that I'd like for them to be able to use the Forms extension for the various contact forms on their site but both of them use other third party services for mailing (Mandrill & Mailgun). I was simply going to extend the Mailer extension to be able to use these two services but aside from modifying the actual mailer extension itself, I can't find a way to do this.

**Comment by moldcraft** [comment]
At the moment you can't extend it, those 2 send methods are hardcoded.
We will create that possibility (seems useful), but I can't tell you sure when (maybe in a few days, weeks, ...), sorry.

**Comment by moldcraft** [comment]
I added this feature.

Test it please and let us know if everything is fine we will release a new version of the Mailer extension.

* [Download](https://github.com/ThemeFuse/Unyson-Mailer-Extension/archive/d272e2eeb204bdeea861b376bbc646046b4425fd.zip) the latest Mailer extension (dev version)
* Extract the zip in `plugins/unyson/framework/extensions/mailer`
* Create your custom send method. Extend [this class](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/master/includes/classes/class-fw-ext-mailer-send-method.php). [Example](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/master/includes/send-methods/class-fw-ext-mailer-send-method-smtp.php)
* Include it

    ```php
    // file: .../extensions/mailer/hooks.php
    
    function _filter_fw_ext_mailer_custom_send_methods($send_methods) {
        require_once dirname(__FILE__) . '/includes/send-methods/class-fw-ext-mailer-send-method-{name}.php';
        $send_methods[] = new FW_Ext_Mailer_Send_Method_{Name};
    
        return $send_methods;
    }
    add_filter('fw_ext_mailer_send_methods', '_filter_fw_ext_mailer_custom_send_methods');
    ```

**Comment by rawcreative** [comment]
Extending works great, the only thing I think is lacking is that if the send method uses an api to send the message data or fields rather than sending the message body as a whole, extending doesn't do much good because there's no access to the field data. If the `fw_ext_mailer_send_mail` function had an additional parameter containing the array that is sent to the view, that eliminates this problem which would allow for much more control by the send method.

 I've submitted a PR to the mailer repo to fix an issue with the options not grouping properly as well as add the data array to the appropriate send methods.  I'll submit another PR with this change for the  forms extension so the data is sent.

**Comment by moldcraft** [comment]
I accepted the PR and [made the `$data` parameter optional](https://github.com/ThemeFuse/Unyson-Mailer-Extension/commit/333156594d2d8650abdf66ab7c595eb2742ce5e6). Please redownload the mailer extension to make sure everything works fine.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/53
