### ISSUE TITLE
Enqueuing an admin script in framework-customizations/theme/static.php doesn’t work

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#476]
Enqueuing an admin script in `framework-customizations/theme/static.php` doesn’t seem to work. I read here that it should - https://github.com/ThemeFuse/Unyson/issues/4#issuecomment-55379776

Tried the following code but it doesn't fire up:
```php
<?php if ( ! defined( 'ABSPATH' ) ) { die( 'Direct access forbidden.' ); }
/**
 * Include static files: javascript and css
 */

if ( is_admin() ) {
	wp_enqueue_script(
		'fw-admin-scripts',
		get_template_directory_uri() . '/framework-customizations/static/js/fw-admin-scripts.js',
		array( 'jquery' ),
		'1.0',
		true
	);
}
```

**Comment by moldcraft** [comment]
> https://wordpress.org/plugins/unyson/changelog/
>
> **2.1.0**
> Moved major theme functionality from `framework-customizations/theme/` to https://github.com/ThemeFuse/Theme-Includes , because the theme must work when the plugin is not installed.

**Comment by nand2k13** [comment]
Enqueuing an admin script in `{theme}/inc/static.php` is still not working,

Following code  in `{theme}/inc/static.php` file
```
if( is_admin() ) {
		wp_enqueue_style(
		    'tk-backend-styles',
		    get_template_directory_uri() . '/css/tk-backend-styles.css', 
		    array('fw', 'fw-backend-options')
		);
}
```
above code working fine in `framework-customizations/theme/options/settings.php`
Why this not working in my-theme/inc/static.php ?

**Comment by moldcraft** [comment]
> Why this not working in my-theme/inc/static.php ?

[because](https://github.com/ThemeFuse/Theme-Includes/blob/45065c4eae3e13ba5411bf26704f0c62508265ac/init.php#L37-L43)

**Comment by nand2k13** [comment]
Thank you for quick reply. I am still confuse I want to enqueue a admin stylesheet or javascript for my backend theme options e.g change the header color of settings page.

**Comment by moldcraft** [comment]
Use WordPress actions for that.

**Comment by nand2k13** [comment]
I am already using wordpress actions via function.php and working fine.

```
function _action_theme_custom_admin_scripts() {
		// add dashboard styles
        wp_register_style( 'custom_wp_admin_css', get_template_directory_uri() . '/css/dashboard.css', array('fw-backend-options'), '1.0.0' );
        wp_enqueue_style( 'custom_wp_admin_css' );
	}
	add_action( 'admin_enqueue_scripts', '_action_theme_custom_admin_scripts' );
```
But I follow your discussion and want to move this code in static.php or something else.
Would you tell me in which file I enqueue admin scripts? 
I move this code to setting.php and working fine.
I want to know best way in which file add admin script enqueue?
Thanks for your support.

**Comment by moldcraft** [comment]
just change inc/init.php however you want, for e.g. make the static.php file to be included on admin_enqueue_scripts

**Comment by danyj** [comment]
for admin styles and scripts use hooks.php  and action 

    fw_admin_enqueue_scripts:settings // post | term | settings

**Comment by nand2k13** [comment]
> just change inc/init.php however you want, for e.g. make the static.php file to be included on admin_enqueue_scripts

@moldcraft Sorry, I do not understand.

>  for admin styles and scripts use hooks.php and action
> 
> `fw_admin_enqueue_scripts:settings // post | term | settings`

@danyj Thanks, working. I add below code in hooks.php
```
/**
 * Enqueue Admin Theme Setting styles.
 * @internal
 */
add_action('fw_admin_enqueue_scripts:settings', '_action_theme_enqueue_scripts_theme_settings');
function _action_theme_enqueue_scripts_theme_settings() {
    wp_enqueue_style(
     	'tk-backend-styles',
        get_template_directory_uri() . '/css/tk-backend-styles.css', 
        array('fw'),
        fw()->theme->manifest->get_version()
    );
}
```
Thank you both, for support.

**Comment by danyj** [comment]
you have all these that you can use in case you need them 

  
```
   fw_admin_enqueue_scripts:customizer
   fw_admin_enqueue_scripts:post
   fw_admin_enqueue_scripts:term
   fw_admin_enqueue_scripts:settings
```
