### ISSUE TITLE
Fatal error: Allowed memory size  fw cache

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#477]
Fatal error: Allowed memory size of 134217728 bytes exhausted

plugins\unyson\framework\helpers\class-fw-cache.php on line 152

hit reset button and this came back , i

I dont want to do this 

    ini_set('memory_limit', '-1');

since I would rather understand what caused it and this should have been enough

https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/class-fw-cache.php#L37

**Comment by moldcraft** [comment]
I experienced this error several times in the past, and every time the cause was an infinite recursion.
Try to find where the recursion happens.

**Comment by danyj** [comment]
well it must be in addable popup, if removed everything is ok , 
addable popup with  4 tabs and 18 options, 
save works , everything ok ,  reset kills it

**Comment by danyj** [comment]
found it , I was calling another option default inside of  $options array via 

    fw_get_db_settings_option('optionanme')

**Comment by moldcraft** [comment]
P.S. In my case the problem was in settings options

```php
// file: .../settings.php

$options = array(
    'test' => array(
        'type' => 'text',
        'value' => fw_get_db_settings_option('test') // when db is empty, this will include again `.../settings.php` then again ...
    ),
);
```

**Comment by danyj** [comment]
thnx for the hint

**Comment by danyj** [comment]
heheheheh :100:  same bug lol

**Comment by danyj** [comment]
but how could I get other option value, is it possible at all ?

**Comment by moldcraft** [comment]
Only to specify default value (second parameter) so it will be returned when nothing found in database.

**Comment by danyj** [comment]
ah , ok got it , thnx!

**Comment by 2Fwebd** [comment]
Hi guys,

I got the same issue, thanks to your comments I know where it's from but I can't figure out what the proper way yo use PHP arrays in `settings-options.php` file. 

I got every time :
`Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 27 bytes)` 

Actually my goal is to have something like that : 
```php
'results' => array(
	'type'    => 'tab',
	'title'   => __( 'Results', 'fw' ),
	'options' => $array
)
```

`$array` is defined by : `$array = $ext_instance->woffice_poll_get_results_backend();` where the functions returns a correct array of options in the main extension file (generated by PHP codes). Even if the function returns and empty array the fatal error will be there ... it only disappears when the  `$ext_instance->woffice_poll_get_results_backend()` isn't in the file. 

**So what's the good way to use php array in this file. I've tried many things but no luck...**

And it was working great on an other Wordpress installation but when I created a new wordpress with the theme, the error comes in... I also tried to add `'value'` on all the options no result...

Thanks,

2F

**Comment by moldcraft** [comment]
It seems that inside `$ext_instance->woffice_poll_get_results_backend()` is called `fw_get_db_ext_settings_option()`. When db value is empty, the `settings-options.php` is loaded to extract default values from options array, then that method is called again, and again ...

**Comment by 2Fwebd** [comment]
Thanks for the fast answer, I'm still digging. But I don't understand something, yes you're right `fw_get_db_ext_settings_option()` is called by `woffice_get_poll_answers()` then why this wouldn't works

```php 
$answers = $this->woffice_get_poll_answers();
if (empty($answers)){
	return array('information' => array('label' => __( 'No results :', 'woffice' ),'type'  => 'html','html'  => 'There is not any result yet.'));
}
```

In fact, if that doesn't works I don't figure out how to fix this ..

Thank you very much @moldcraft  !! (Btw, I've created a bunch of other extensions and it looks really cool :+1:, Unyson extension class is just awesome and well documented for frontend dev)

2F

**Comment by moldcraft** [comment]
It doesn't matter if `$answers` are empty or not, if `fw_get_db_ext_settings_option()` then an infinite recursion happens and the execution will never reach `if (empty($answers)){`.

----

Thank you

**Comment by 2Fwebd** [comment]
Thank you for the explanations, yep I've created another function to add a default value in the database and the error is still there. So any way to by pass that issue ? Because, in fact I created a tab to display the poll results. And I don't get why on my other wordpress installation it's working great as you can see on the screenshot : 
![unyson_ _woffice_ _wordpress](https://cloud.githubusercontent.com/assets/5446124/7787830/9d5ff284-0220-11e5-8ba2-a5d2364c6875.jpg)
Thanks again !

**Comment by moldcraft** [comment]
If there are values in the database, the recursion doesn't happen (the options file is not loaded for defaults extraction).

**Comment by 2Fwebd** [comment]
OK so I have to save default values in `fw_ext_settings_options:woffice-poll` to fix this damn issue. However, that row doesn't exists yet, so I have to create it by myself right ? Because I can't find it in the wp_options table. Anything easier than `$wpdb` method :
```php
$wpdb->insert( 
	$wpdb->prefix . 'options', 
	array(
		'option_name' => 'fw_ext_settings_options:woffice-poll',
		'option_value' => json_encode($defaultvalue),
	), 
	array('%s','%s') 
);
```
I guess there is some Unyson PHP functions for that but I can't find them , any idea ? 
Thanks

**Comment by moldcraft** [comment]
Try to specify the default value in second parameter

```php
fw_get_db_ext_settings_option('ext_name', 'option_id', $default_value);
```

**Comment by 2Fwebd** [comment]
Works! :+1:  :+1:  !!! Thank you so much @moldcraft !!!
2F
