### ISSUE TITLE
Demo Install problem

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#479]
A client tries to install the theme and gets an error. Not the first time. Users on GoDaddy, also report problems with demo install.

![image](https://cloud.githubusercontent.com/assets/11438910/7240590/e24ebc2a-e7ba-11e4-8c47-0f2208b4a71e.png)

**Comment by valeriuzdrobau** [comment]
Hi, I made some [changes](https://github.com/ThemeFuse/Unyson-Backup-Extension/commit/c2af443d8d9d2f0e5ab088c5b4561cda53931bbe) that will be in the next version, please pull [backup extension](https://github.com/ThemeFuse/Unyson-Backup-Extension) with the modification and try to users with problems. If you still are having problems, try adding the following code in `wp-config.php`:
```
/* Setup a temporary folder for uploading and updating */
define( 'WP_TEMP_DIR', ABSPATH . 'wp-content/tmp/') ;
```
