### ISSUE TITLE
Ability to not remove form after submitting

### ISSUE THREAD

**Issue by martin-bede** [ThemeFuse/Unyson#480]
Does such an option exist to not remove the form content after it's been submitted _(for my use case I just don't want the page to jump when the form content is removed)_.

If an option is not available could you point me to the file(s) so I can customise this please.

**Comment by moldcraft** [comment]
I gave all the info here https://github.com/ThemeFuse/Unyson/issues/353#issuecomment-86149401

Everything is in [that script](https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/static/js/fw-form-helpers.js#L57-L76). You can overwrite any parameter, like [you already did with `ajaxUrl`](https://github.com/ThemeFuse/Unyson/issues/353#issuecomment-94309076)

**Comment by martin-bede** [comment]
Sorry – I totally should have checked that out first.
