### ISSUE TITLE
Sanity check for  add_query_arg and remove_query_arg

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#481]
Did you guys see this?
http://wptavern.com/xss-vulnerability-affects-more-than-a-dozen-popular-wordpress-plugin

I checked few uses and most of the are using esc_...
but they are few in admin backend and megamenu extension backend that I am not sure off. You might want to take a second look to make sure.

**Comment by duongancol** [comment]
I checked and I think megamenu extension is already escaped.
![screen shot 2015-04-27 at 10 11 37 am](https://cloud.githubusercontent.com/assets/1773011/7341114/ebacf218-ecc5-11e4-996d-eb2a8dfa51ad.png)
