### ISSUE TITLE
Mailer setup 

### ISSUE THREAD

**Issue by i-nu-it** [ThemeFuse/Unyson#482]
Hi, 

I have been trying to setup the mailer, but when I go to do it the mailer settings say "/* UNDEFINED OPTION TYPE */". 

Where do I change this? 

Thanks

**Comment by i-nu-it** [comment]
When saving the page with the contact form in it it says: "Undefined option type: mailer".

**Comment by moldcraft** [comment]
The option type `mailer` [is included on every page load](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/731eae4bb850a33c147da79740363446ecabdf0b/includes/sub-includes.php#L5).

* Or you have an old version of the Mailer extension. Please update the extensions from the WordPress Updates page).
* Or it's something else. Please zip the `wp-content/plugins/unyson` directory and send it to `unyson[at]email.com` and I will take a look.
