### ISSUE TITLE
"No sliders available" despite there are

### ISSUE THREAD

**Issue by bsusala** [ThemeFuse/Unyson#485]
Hi guys. When I create a slider (any of the three types) and I choose auto populate from categories, and I select media category (from another plugin), the slider is saved and does exist. However, when I try to insert into page(s), message is "No sliders available. etc." The only method to show up in dropdown is to add manually each slide. What could be wrong?

**Comment by llemurya** [comment]
@bsusala everything is ok, you just must add in your categories posts that have featured images, because algorithm verify if your population method is from categories and look if you have posts with featured images, if you haven't then in popup builder appear this message with `No sliders available` text. Thanks for the feedback, if my answer helped you , please close the issue.

**Comment by bsusala** [comment]
thanks @llemurya, but I am not using images that were assigned as featured for posts (and hence these posts having some category inherited), but instead I am using categories assigned to media in the library (through a separate plugin, there are many, I am using for example https://wordpress.org/plugins/wp-media-category-management/). So, the categories I am populating with are from Media, not from Posts. Everything is okay - I can select which categorie to choose from (either Posts or Media), which specific category, then I save, the slider is created and all smooth. Until want to use it: the message is that there is no slider available :) So, at least from an usability point of view, there is something unusual. Please advise, thanks.

**Comment by llemurya** [comment]
@bsusala I will investigate your case and give you an answer.

**Comment by llemurya** [comment]
@bsusala Sorry for the delay, I fixed that, in next version of the `population methods extension` it will be available and fix your problem, at the moment you can manually download and replace `/media/extensions/population-method/extensions/population-method-categories/class-fw-extension-population-method-categories.php` file and it will  works. Thanks for the feeback.
