### ISSUE TITLE
2 page builder on same page do not work

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#487]
Try this 

	'page-content' => array(
		'title'   => false,
		'type'    => 'box',
		'options' => array(
			'reservation-page' => array(
				'label' => false,
				'type'  => 'page-builder'
			),
			'reservation-page2' => array(
				'label' => false,
				'type'  => 'page-builder'
			),
		)
	),

second one will trow js error

**Comment by danyj** [comment]
Any progress on this?

**Comment by danyj** [comment]
can someone please take a look at this.

**Comment by moldcraft** [comment]
@GheorgheP will be available next week, sorry.

**Comment by GheorgheP** [comment]
When you want to render the page-builder content, you have to do ti like this:
```php
$content = fw_get_db_post_option( $post_id, 'OPTION-ID');
echo do_shortcode(str_replace('\\', '\\\\', fw_akg('shortcode_notation', $content) ));
```

**Comment by danyj** [comment]
this is not fixed ,  you cant have more that one builder on a page , I downloaded the latest pr and same issue.

**Comment by cristeamdev** [comment]
I just made some tests with multiple Page Builders in page and seems to work properly.

Here is an array of options that can be added for the page options: 

```
$options = array(
	'box'  => array(
		'title'   => __( 'Meta Box', 'asdasd' ),
		'type'    => 'box',
		'options' => array(
			'test' => array(
				'type'  => 'page-builder',
				'value' => array( 'json' => '' ),
				'label' => false,
				'desc'  => false,
			),
		),
	),
	'box2' => array(
		'title'   => __( 'Meta Box', 'asdasd' ),
		'type'    => 'box',
		'options' => array(
			'test2' => array(
				'type'  => 'page-builder',
				'value' => array( 'json' => '' ),
				'label' => false,
				'desc'  => false,
			),
		),
	),
);
```

Tested with enabled page builder on page, and disabled, also disabled page builder for page entirely, and got it working

**Comment by danyj** [comment]
@cristeamdev   there were so many changes since June last year
