### ISSUE TITLE
Date Picker Option Type, calendar issue 

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#488]
Hi there,

I'm encountering an issue with Date Picker option, actually I can't select any day from the current month (only next one), you can see it on the screenshot : 
![clock_menu](https://cloud.githubusercontent.com/assets/5446124/7283096/4d2b5cd6-e934-11e4-8a7e-ab4daeb68f01.jpg)
Do you have any idea about this issue ? Let me know if you need more details.
Thanks, 

2F

**Comment by martin-bede** [comment]
+1 I've also experienced this recently.

**Comment by llemurya** [comment]
@2Fwebd  and @martin-bede please check this solution,
```php
array(
    'type'  => 'date-picker',
    'label' => __('Label', 'fw'),
    'desc'  => __('Description', 'fw'),
    'min-date' => null, //date('d-m-Y'), // By default minimum date will be current day. Set a date in format d-m-Y as a start date
  )
```
If it helps please close the issue.

**Comment by 2Fwebd** [comment]
That did the job thanks @llemurya ! :)

**Comment by martin-bede** [comment]
I've not been able to give it a try yet but thanks in advance :)
