### ISSUE TITLE
How to get theme manifest ID in hooks or helpers ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#490]
I am trying to get the theme manifest id 

    fw()->theme->manifest->get('id')   

and I need it inside theme helpers or hooks file

**Comment by llemurya** [comment]
@danyj try this solution `fw()->theme->manifest->get_id()`

**Comment by danyj** [comment]
Call to undefined function fw() 

only way to do it is custom 

    thz_get_variables_from_file


but we should be able to see those inside helper and hooks

**Comment by llemurya** [comment]
@danyj try to hook at the action `fw_init` because I think you try to run it before the unyson is full loaded.

**Comment by llemurya** [comment]
```php
add_action('fw_init', function(){
   fw_print(fw()->theme->manifest->get_id());
});
```

**Comment by danyj** [comment]
This is my function.php


    include_once get_template_directory() .'/inc/init.php';


so I am not doing anything special , everything else is unyson
hooks.php and helpers.php  is where I need the manifest ID and they load after fw_int

so far I see that

**Comment by moldcraft** [comment]
> @llemurya 
> ```php
> add_action('fw_init', function(){
>    fw_print(fw()->theme->manifest->get_id());
> });
> ```

*plese do not recommend anymore anonymous functions. Our themes should work on php 5.2.*
