### ISSUE TITLE
Calendar not responsive

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson#491]
Hi,

Is it normal that I have something like that : 

http://image.noelshack.com/fichiers/2015/17/1429808374-responsive.png

Thank you

**Comment by valeriuzdrobau** [comment]
Yes, it is normal, we provide the back-end,every developer has to write for front-end style for his theme, theme scratch should be treated as an example of use of the possibilities they offer Unyson. Thank you for reporting, have a nice day!
