### ISSUE TITLE
Page builder template are not exported with demo install

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#492]
Just tested the demo install and noticed that save builder templates are not exported/imported

**Comment by valeriuzdrobau** [comment]
I tested now and everything is going well. Can you give me more details about the error? They are saved in the database and not found in database.txt?

**Comment by danyj** [comment]
That is right , I had one template
http://prntscr.com/6xj1ei

and in new demo install there are 0 

http://prntscr.com/6xj1ln

**Comment by valeriuzdrobau** [comment]
Please generate again demo content, open the file database.txt from auto-install folder, and check if you can find information about templates saved.

**Comment by danyj** [comment]
and what would be different now?  I did not install re-install anything, and what would I look for ?  
handle ?

**Comment by danyj** [comment]
i dont believe you sending me on a goose chase trough 22mb file,

**Comment by valeriuzdrobau** [comment]
Save a template named `export tpl 5678`, and then look for `export tpl 5678` in database.txt. I want to know if the problem is you import or export. Tell me please versions at: 
1. Unyson 
2. Backup
3. Builder
4. Page Builder

**Comment by danyj** [comment]
problem i in import 

export is there 
http://prntscr.com/6xjj75

always using latest masters , updating them as you release test releases

**Comment by valeriuzdrobau** [comment]
Put the following code in `functions.php`

```
function test_if_page_builder_templates_are_imported(){
	$templates = fw_get_db_extension_data('builder', 'templates', 'not imported!');
	fw_print($templates);
}

add_action('wp_footer', 'test_if_page_builder_templates_are_imported');
```
Do a refresh on the front end and give me a print screen with the bottom of the page.

**Comment by danyj** [comment]
no bud , I dont have time, working here ,  I gave you a valid bug, took screenshots , told you what the issue is  ,  if you like to fix it than test please. 
look at my bug reports record , daily I am helping out , some courtesy to look for issue when reported would be great but instead you want me to do what you should do. sending me on a testing spree will not do anything since I will not fix it ,  so is waste of my time either way.

**Comment by danyj** [comment]
here 
http://prntscr.com/6xz44g

**Comment by valeriuzdrobau** [comment]
If you really want to help solve this bug, please send me `fw_extensions` value from `wp_options` prior to export. Questions that you have upset you were generated by http://prntscr.com/6xj1ei, http://prntscr.com/6xj1ln, you know that they do not give too many details about the error.

**Comment by danyj** [comment]
http://themezly.com/fw_extensions.txt  , let me know when you have so I can remove it

**Comment by valeriuzdrobau** [comment]
I copied

**Comment by danyj** [comment]
and this is the fw_extensions table from new install 
http://prntscr.com/6xze0k

**Comment by valeriuzdrobau** [comment]
ok

**Comment by pe6o** [comment]
I can confirm thisbug. I'm in a process of creating a 1 Click installer and the template that I had is not there.
