### ISSUE TITLE
Typography Roboto Font missing  google font

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#493]
Hi 
Any possibility to include roboto font in typography next update  ? 
This font is missing in typography option

Thank you

**Comment by valeriuzdrobau** [comment]
You can use `fw_google_fonts` filter to expand the list of fonts from google. [Here ](https://github.com/ThemeFuse/Unyson/issues/100)you have an example.

**Comment by xperter** [comment]
Is there any way to add font small image (which display the font style) like others google font ??
Thank you

**Comment by valeriuzdrobau** [comment]
At the moment it is not possible.
