### ISSUE TITLE
Multiple demo install select option

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#495]
Is it possible to add a select option with demo name. and then select the demo name which i like to install.  and when i press <strong>Import demo content</strong>
This will catch the demo Which i have select  then install the demo content. 

We have created one page theme. so it will be great if i can select the demo which i like to install.

Thanks for your help

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Backup-Extension/issues/4

**Comment by duongancol** [comment]
Good idea! :+1:
