### ISSUE TITLE
Getting shortcode option value? How?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#497]
Okay, I have a custom shortcode with some options in `options.php`.

I'm creating a helper function to get the value of an option field of that shortcode.

Say I have in `framework-customizations/extensions/shortcodes/shortcodes/shortcode-name/options.php` :

```php
'color' => array(
	'label'  => __( 'Select Color' ),
	'type'   => 'color-picker',
),
```

How can I get the value of the field from a file different from  the `view.php` that is in the directory of the shortcode?

I'm trying the `fw_get_db_ext_settings_option()` function but can't get it to work...

**Comment by danyj** [comment]
fw_get_db_ext_settings_option('option_name');


in your case 

    fw_get_db_ext_settings_option('color');

**Comment by danyj** [comment]
my bad , that is for theme options

**Comment by pe6o** [comment]
@danyj Did you mean `fw_set_db_settings_option()`?

**Comment by duongancol** [comment]
You can try using class of your extension, for example: class-fw-extension-your-extension.php
using function render() to transfer all variable to your view file.
<pre>
public function render(){
$data['abc'];
$data['bcd'];

return $this->render_view('view', $data);
}
</pre>

**Comment by pe6o** [comment]
What I meant is how can I access the value (`$atts`) of a shortcode field in let's say ´functions.php´?

**Comment by duongancol** [comment]
my mistake, did you try function fw()->extension->get('name of extension). It wil get class extension so I think you can get option also.

**Comment by pe6o** [comment]
@duongancol Hmm, this gives me:
`Undefined property: _Fw::$extension`

**Comment by moldcraft** [comment]
fw()->extension**s**->get('name of extension')

**Comment by pe6o** [comment]
It's seems that I can't get an option field as `[FW_Shortcode:options]` is empty. Can I somehow get the IDs and the option field types of the shortcode? I want to send string with an option ID and get it's type.

```
 [my_shortcode] =&gt; FW_Shortcode
        (
            [FW_Shortcode:tag] =&gt; &#039;featured_deals&#039;
            [FW_Shortcode:path] =&gt; &#039;site-name/framework-customizations/extensions/shortcodes/shortcodes/my-shortcode&#039;
            [FW_Shortcode:uri] =&gt; &#039;site-name/framework-customizations/extensions/shortcodes/shortcodes/my-shortcode&#039;
            [FW_Shortcode:rewrite_paths] =&gt; array()
            [FW_Shortcode:rewrite_uris] =&gt; array()
            [FW_Shortcode:options] =&gt; null
            [FW_Shortcode:config] =&gt; null
        )
```

**Comment by moldcraft** [comment]
> How can I get the value of the field from a file different from the `view.php` that is in the directory of the shortcode?

You can't. (sorry for late reply)

----

Give us more details, why you need that?
You want to access the options array from `options.php`, or you want to access options values (from db, the `$atts`) ?

**Comment by pe6o** [comment]
Okay, here's what I'm trying to achieve.

I want to create a function that will make it easy and fast for me to input inline css in HTML attributes getting the values from the option fields of the shortcode.

**view.php** of the shortcode:
```html
<div class="bg-image" <?php fw_el_style( array('bg_image' => 'image','opacity' => 'img_opacity') ); ?>></div>
```

**shortcode-name/options.php**
```php
$options = array(
	'bg_image' => array(
		'label'  => __( 'Image' ),
		'type'   => 'upload',
		'images_only' => true
	),
	'img_opacity' => array(
		'label'  => __( 'Image Opacity'),
		'type'   => 'slider',
		'value' => 20,
		'properties' => array(
			'min' => 0,
			'max' => 100,
			'sep' => 5,
			),
	)
);
```

**theme-name/helpers.php**
```php
function fw_el_style($options = array()) {

	$output = 'style="';

	foreach ($options as $property => $option_id) {

		// get_option_value_by_option_id() searches in the options.php of the shortcode for the option with an ID of $option_id and returns its value
		$option_value = get_option_value_by_option_id( $option_id );

		if ( $property == 'bg_image' ) {
			$output = 'background-image: url("' . $option_value . '"); ';
		}

		if ( $property == 'opacity' ) {
			$output = 'opacity: ' . $option_value . ' ';
		}

	}

	$output .= '"';

	return $output;

}
```

So my question is how can I achieve the functionality of `get_option_value_by_option_id()`? Is there some way to access the values from outside? This would give great flexibility for extensions like this one..

**Comment by pe6o** [comment]
>You want to access the options array from options.php, or you want to access options values (from db, the $atts from view.php) ?

So yeah, is there a way that I can access the `options.php` array and the value of `$atts` from outside?

**Comment by moldcraft** [comment]
Please read this answer https://github.com/ThemeFuse/Unyson/issues/511#issuecomment-98319183

----

I think the solution would be

```php
<div class="bg-image" <?php fw_theme_el_style( array(
    'bg_image' => $atts['image'],
    'opacity' => $atts['img_opacity'])
); ?>></div>
```

P.S. Please [prefix](http://manual.unyson.io/en/latest/convention/prefixes.html#theme) your function. If someday we will create a function with the same name in Unyson, your theme will have a fatal error "function already defined".

----

P.P.S. [Here](https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-94061237) is an alternative to inline `style="..."`

**Comment by pe6o** [comment]
Oh, thanks. Gonna play with these functions now.

Hmm, I thought that when using the framework everything should be prefixed with `fw_`. Will replace them. So I guess the `actions` and `hooks` have to be prefixed too? `_action_fw_prefix_funcion_name`?

**Comment by moldcraft** [comment]
Everything is prefixed and everything about prefixes is on [this page](http://manual.unyson.io/en/latest/convention/prefixes.html#content)

**Comment by nayeem07007** [comment]
Is possible shortcode option value save as  meta value ?
