### ISSUE TITLE
How to output backend option to be used as a data template?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#498]
@moldcraft 

I made a option that consists of a radio switcher and few other options under , 
how can I take advantage of the same thing you used in multi-picker and output it inside the data attribute. 

example this 

		echo fw()->backend->option_type('thz-color-picker')->render(
			'background-color',
			array(
				'label' => false,
				'desc'  => false,
				'type' => 'thz-color-picker',
				'value' => $option['value']['background-color'],
			),
			array(
				'value' => $data['value']['background-color'],
				'id_prefix' => 'fw-option-' . $id . '-thz-background-',
				'name_prefix' => $data['name_prefix'] . '[' . $id . ']',
			)
		)

to be in data-template=""

I'm looking trough the multi but cant spot the difference between normal render and the render you used.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/76a945a8229c5e9f59252238aa3d29883dbab609/framework/includes/option-types/multi-picker/class-fw-option-type-multi-picker.php#L107

```php
<div date-template="<?php
    echo fw_htmlspecialchars(
        fw()->backend->option_type('thz-color-picker')->render(...)
    );
?>"></div>
```

----

*If the answer is too short, give me more details about the option-type you made.*

**Comment by danyj** [comment]
ok bud that is it, thnx !

**Comment by danyj** [comment]
I missed the fw_htmlspecialchars
