### ISSUE TITLE
Sidebar when Front page displays is set to static page

### ISSUE THREAD

**Issue by pudeco** [ThemeFuse/Unyson#50]
hi, 

i have issue related to sidebars. 

my front page settings are like this: a page for front page, and another static page for posts page.

after this, i cannot assign sidebar to blog posts page.

i tried to solve it like this : 

```php
if (is_home() && get_option('page_for_posts') != '0' && get_option('show_on_front') == 'page') {
	$data['type']     = $this->config->get_type_by_prefix(_FW_Extension_Sidebars_Config::POST_TYPES_PREFIX);
	$data['sub_type'] = 'page';
	$data['id']       = get_queried_object_id();

	$result = $this->get_preset_sidebars($data);
	if ( $result )
		return $result;
}
```

i am not sure if this is the right way. 

now i have second issue, i do have woo commerce installed, and have shop page.  from sidebars, i selects products from grouped pages and assign shop sidebar, and from specific pages, select shop page and assign the same sidebar. in product detail, the sidebar is shown, but in shop page, it is undefined. 

should i use something like `is_shop()` in `class-fw-extension-sidebars-frontend.php` ?

thanks a lot.

**Comment by llemurya** [comment]
@RayNguyen Can you see this [changelog](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/43) of the sidebars, I think that can help you with woocommerce page
