### ISSUE TITLE
Creating shortcode help

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson#501]
Hi,

can you look into that?
https://github.com/ThemeFuse/Unyson/issues/441#issuecomment-97093036

I would like to show event name, small description (the one below the visual editor) and the hours/date on the page. Also, I would like to only show the next # events (choice of the user).

I would like to know if what I did is ok.

**Comment by Nic787** [comment]
UP!

**Comment by Nic787** [comment]
So nobody want to help me.

Things I would like to show on the page with this shortcode :

- Title (name of the event)
- Date/hour
- Location --> OPTIONAL
- Description (SEO description) --> OPTIONAL

![description](https://cloud.githubusercontent.com/assets/11185348/7465184/25d000fa-f29a-11e4-8837-6025b753a6a9.png)

**Comment by llemurya** [comment]
@Nic787 you can edit the event view `framework-customizations/extensions/shortcodes/shortcodes/calendar/views/view.php`
