### ISSUE TITLE
can not install extension in Unyson page

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#502]
Hi!
My client can not install extension in Unyson page. I don't know why.
You can see image below.
![screen shot 2015-04-29 at 2 05 31 am](https://cloud.githubusercontent.com/assets/1773011/7378207/f972ce6c-ee15-11e4-9a25-78c7547a61e9.png)
![screen shot 2015-04-29 at 2 05 52 am](https://cloud.githubusercontent.com/assets/1773011/7378208/fb75a2ca-ee15-11e4-991c-5a8a127bce7f.png)
It just showed blank page when I input password and click to Proceed button. 
It's Unyson version 2.2.8

**Comment by moldcraft** [comment]
I can't reproduce this on my localhost. Can you on your localhost?
Can you send me the site link, admin login and password to `unyson[at]email.com`? Also I need the possibility to edit the files to debug the problem.

**Comment by duongancol** [comment]
I did send email, did you get it?

**Comment by moldcraft** [comment]
I get it

**Comment by moldcraft** [comment]
The php -> FTP connection isn't working. I can't install any plugin.

![~](http://static.md/d46de5e2503aca665199d19d71153a90.png)

----

When I add [here](https://github.com/ThemeFuse/Unyson/blob/a2f6c250c74f30490abf6a803d3c4ab8de23ada5/framework/helpers/class-fw-wp-filesystem.php#L79-L80)

```php
fw_print(
$context, 
$wp_filesystem->abspath(),
$wp_filesystem->wp_content_dir(),
$wp_filesystem->wp_plugins_dir(),
$wp_filesystem->wp_themes_dir(),
$wp_filesystem->find_folder($context)
);
```

I get

![~](http://static.md/35328a177f2a8305d1014ed77b9d42f4.png)

----

It would be better if instead of [boolean return value](https://github.com/ThemeFuse/Unyson/blob/a2f6c250c74f30490abf6a803d3c4ab8de23ada5/framework/helpers/class-fw-wp-filesystem.php#L10-L13), would also be `WP_Error` with error message in it. Unfortunately I can't change this method because it is used often. I will create a new one (later).

**Comment by duongancol** [comment]
Why I can access ftp via FileZilla?
So what is your solution now?, is there any to install extension with ftp? 
If can not install extension they can not use my theme.

**Comment by moldcraft** [comment]
The hosting is not configured properly. How they even installed Unyson?

**Comment by duongancol** [comment]
It's very confusing. I did email theme and asked the same question. Thanks for your help!

**Comment by duongancol** [comment]
Hi @moldcraft : please try again with username: cont@webxnow.com, I tried to install with default plugin, it worked. But it showed another error with Unyson extension:
<pre>
Downloading the "Media" extension...


Warning: Cannot create directory "/wp-content/plugins/unyson/tmp". It must be inside "" or "/wp-content" or "/wp-content/plugins" or "/wp-content/themes" in /home/ABC/public_html/cont2/wp-content/plugins/unyson/framework/helpers/class-fw-wp-filesystem.php on line 252
Cannot create temporary directory: /wp-content/plugins/unyson/tmp

Cannot create temporary directory: /wp-content/plugins/unyson/tmp
</pre>

**Comment by moldcraft** [comment]
I will try tomorrow when I will have a PC (now I am from  mobile)

**Comment by duongancol** [comment]
Ok

**Comment by moldcraft** [comment]
@duongancol Please send me again the credentials to `moldcraft[at]email.com`
*I don't have access to `unyson[at]email.com` at the moment.*

**Comment by duongancol** [comment]
I did, please check your email.

**Comment by moldcraft** [comment]
Sorry abut the bug and that it took so long to fix it.
I made the changes via ftp.
But now there is another problem with server configuration
![s](https://static.md/4441e50d7eefd473ff113e357781089c.png)

**Comment by duongancol** [comment]
I guess that there're something wrong with php5-curl. I'll contact with client to enable it. Thanks for your help!
