### ISSUE TITLE
How to call custom.php $attr on view.php for a custom slider?

### ISSUE THREAD

**Issue by Alex-Ascet** [ThemeFuse/Unyson#504]
Hi all,

I have created a custom slider with custom options. I have added my options in custom.php because it is a custom population slider. It works perfectly (see attached). But I do not understand how I can call and display these options on the view.php... I have tried <?php echo $atts['subtitle'] ?> <?php echo $options['subtitle'] ?> without any results. Could you please help me? Thank you in advance.

![screen shot 2015-04-29 at 2 15 06 pm](https://cloud.githubusercontent.com/assets/12162252/7384629/2e96ad70-ee7a-11e4-82e8-915b110e2cc6.png)

**Comment by llemurya** [comment]
@Alex-Ascet please read our [slider documentation](http://manual.unyson.io/en/latest/extension/slider/index.html?highlight=slider#template) to see the structure of the `$data` array, as a simple proof that you have your custom fields in frontend please run this code in your slider view.
```php
fw_print($data);
```
It will print all `$data`, please pay attention at the `slides key ` and at the inner `extra key` that is located in every slide. If it helps you , please close the issue.

**Comment by Alex-Ascet** [comment]
Thank you very much for your support.
It was very helpful, now it works.

Here the solution to display an option from custom.php:
<?php echo $slide['extra']['youroption'] ?>
