### ISSUE TITLE
Page Template for Portfolio

### ISSUE THREAD

**Issue by invisiblevision** [ThemeFuse/Unyson#505]
How to create Page Template for Portfolio Extension , Coping archive,php as it is not working i am using Scratch Theme Twenty fourteen

**Comment by llemurya** [comment]
@invisiblevision please read our documentation. It describres how to change portfolio view , please look at [this](http://manual.unyson.io/en/latest/extension/portfolio/index.html#views) article.If it helps, please close the issue.

**Comment by Alex-Ascet** [comment]
Hi there,

I have created a single.php under child/framework-customizations/extensions/portfolio/views/single.php and it does not overwrite the single.php from wordpress.
Any idea? Thank you for your time.

**Comment by GheorgheP** [comment]
Hi @Alex-Ascet,

Please make sure you created the correct directory, as I tested and all seems to work fine.
In the other case, please provide the ftp details on dev-team@unyson.io

Also, in next version of portfolio we made the ability to load the templates in the wordpress way.
So for the portfolio single you'll need to create the template with this name in the theme root: `single-fw-portfolio.php`
