### ISSUE TITLE
New typography option in works. Let me know what you think. 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#506]
@moldcraft 
OK I think this one will be usable and is easy to work with plus it lowers the page load. 
https://github.com/Themezly/ThzTypo

#Demos
- [Base demo](https://jsfiddle.net/cjLosm80/embedded/result/)
- [Bootstrap demo](https://jsfiddle.net/hk2Lqmkq/embedded/result/)
- [Uikit demo](https://jsfiddle.net/pxjzeh1o/embedded/result/)

The idea was to lower the site load and not repeat the reloading of 600+ google fonts in each option. 
So instead of your js font list , I made the one time load font preview that is used  on each  user interaction with typo option. 

https://github.com/Themezly/ThzTypo/blob/master/demo-base/thztypo.php#L162
https://github.com/Themezly/ThzTypo/blob/master/thztypo/assets/thztypo/thztypo.class.php

This can easily be used with 

    fw_htmlspecialchars();

and called when needed. 

Google font json is drop in updatable. 
https://github.com/Themezly/ThzTypo/tree/master/thztypo/assets/thztypo

So no worries about available fonts. I did not want to use API because of the future users possible lack of knowledge with DEV API. It is simple file replacement to update the fonts so this is ok for now. 

Let me know what you think or suggest improvement. 

Next stop , port to Unyson option.  I wont be submitting a PR for it but you are more than welcome to take the code and use it.

**Comment by moldcraft** [comment]
*Sorry, too many issues.
At the moment (starting with Monday) I will begin investigating the Customizer and how to integrate our options in it.*

You can leave the issues open, we will take a look later.
