### ISSUE TITLE
fatal error on create/edit pages

### ISSUE THREAD

**Issue by LThemes** [ThemeFuse/Unyson#507]
Hello

Great framework you guy's have, keep the good job.

i've updated the plugin to version 2.2.8 and i got this error message when creating/editing pages both in local host and online.

 Fatal error: Call to a member function prepare_settings_options_values() on a non-object in C:\xampp\htdocs\wp-testes\hscom\wp-content\plugins\unyson\framework\extensions\mailer\class-fw-extension-mailer.php on line 101

I've removed the plugin and installed it again, but the problem persists.

my localhost php version is 5.5.15

Regards

**Comment by grossemesser** [comment]
I got the exact same error! Found out today.
I would appreciate your attention to this very needed fix.
Thanks!

**Comment by moldcraft** [comment]
Strange. I tested it and everything was fine
Also the extensin was pending in approval for a few days https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/53

**Comment by moldcraft** [comment]
Sorry, I can't debug it now, I will be at my dev PC in a few hours

**Comment by moldcraft** [comment]
*If you found the fix, please make a pull request.*

**Comment by Alex-Ascet** [comment]
Same here. Thank you.

**Comment by moldcraft** [comment]
I created [the release](https://github.com/ThemeFuse/Unyson-Mailer-Extension/releases/tag/v1.2.1). After 2 hours, please open the Updates page and press **Check again**

![s](http://www.wpultimaterecipe.com/wp-content/uploads/2014/07/WordPress-Updates.png)

*Sorry for late fix*

**Comment by grossemesser** [comment]
Thank you!! It worked, I no longer get the error code!

**Comment by LThemes** [comment]
Thanks for the update.

**Comment by grossemesser** [comment]
And thanks for the where-to-update screenshot too!
