### ISSUE TITLE
Page builder fatal error in version 2.2.8

### ISSUE THREAD

**Issue by tbaggins** [ThemeFuse/Unyson#510]
Hi

I'm trying Unyson for the first time. I have setup two clean standard wordpress installations and installed the unyson plugin. No problems so far. I then download the page builder extension. Still no problems. When I try to add a new page I get this:

Fatal error: Call to a member function prepare_settings_options_values() on a non-object in /home/codinsyb/public_html/unyson/wp-content/plugins/unyson/framework/extensions/mailer/class-fw-extension-mailer.php on line 101

I've tried this on two brand new wordpress installations with nothing else going on. Just the unyson plugin and pagebuilder extensions activated, and then trying to create my first page.

Thanks.

**Comment by tbaggins** [comment]
Hi.

The problem seems to be linked to your latest update of the Mailer extension where you added the hooks.php file to allow custom send methods. I temporarily deleted the hooks.php file from that extension and the page editor loads fine now except for a small warning that reads: Undefined option type: mailer

Hope that helps a little in identifying the issue.

Thanks.

**Comment by moldcraft** [comment]
I created [the release](https://github.com/ThemeFuse/Unyson-Mailer-Extension/releases/tag/v1.2.1). After 2 hours, please open the Updates page and press **Check again**

![s](http://www.wpultimaterecipe.com/wp-content/uploads/2014/07/WordPress-Updates.png)

*Sorry for late fix*
