### ISSUE TITLE
Option type slider numbers messed up

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#512]
When I create an option type `slider` with the following code:

```php
'deals_per_row' => array(
		'label'  => __( 'Deals per row', 'fw' ),
		'type'   => 'slider',
		'value' => 4,
		'properties' => array(
			'min' => 2,
			'max' => 5,
			'sep' => 1,
			),
	)
```

This is what happens:
![slider](https://cloud.githubusercontent.com/assets/1108563/7445055/11be4b5c-f1ab-11e4-90a9-22e8e766d100.png)

**Comment by moldcraft** [comment]
Hello @pe6o 

Unfortunately @valeriuzdrobau will be busy for one week. We will try to look at this issue but didn't guarantee anything.

If you can find the fix, please make a pull request.

**Comment by llemurya** [comment]
@pe6o I opened an [issue](https://github.com/IonDen/ion.rangeSlider/issues/236) on the rangeSlider, when they resolve this bug we will update the option type.

**Comment by llemurya** [comment]
@pe6o please look at this [video](https://youtu.be/o6KINSDcMx4) and read this [answer](https://github.com/IonDen/ion.rangeSlider/issues/236).

**Comment by pe6o** [comment]
Nice! You guys are great. Is this `grid_snap` option going to be included in Unyson?

**Comment by llemurya** [comment]
@pe6o it is already in unyson , you must only add the grid_snap attribute and it will work , please make a try.

**Comment by pe6o** [comment]
Ah, sorry. Was on mobile and in a hurry...

**Comment by pe6o** [comment]
It seems that there is still bug with the slider when the numbers are below 5. It seems that:
```php
'columns_count' => array(
		'label'  => esc_html__( 'Number of columns', 'couponhut' ),
		'type'   => 'slider',
		'value' => 4,
		'grid_snap' => true,
		'properties' => array(
			'min' => 1,
			'max' => 4,
			'sep' => 1,
			)
	),
```
The slider numbers are 1,2,3,3,4. It seems the range slider must have at least 5 numbers or else it's bugged..
![slider](https://cloud.githubusercontent.com/assets/1108563/10164221/0599d31a-66c1-11e5-9483-78ac789c406f.png)
