### ISSUE TITLE
Is there a "starter theme" for Unyson?

### ISSUE THREAD

**Issue by sunny04** [ThemeFuse/Unyson#513]
Hi,

I've recently discovered this framework and I'm so glad to have found it and I really appreciate all the hard work that has been put into it.

Right now I'm going through the documentation, which seems great, but I feel like if there was a sample theme or a "starter theme" available for download then it would have been of great help in understanding it better.

So far I've figured that I'm going to use the TGM plugin to let users download and activate the plugin, and then have all the customization inside the 'framework-customization folder'. I'm going through the documentation and slowly understanding how I will make the customization, but I think if I had just a very basic theme to look at and test, then it would have been great.

Please let me know about this and thank you very much.

**Comment by moldcraft** [comment]
P.S. We are currently developing [Scratch theme v2](https://trello.com/c/BZr42P2Q/52-scratch-theme-new-design). Will be released soon
