### ISSUE TITLE
[question] is there a way to use only parts of the framework?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#515]
I am talking about including some field types and some custom field types and a very very basic structure into a plugin? I would want to create a plugin that has a minimal builder and the core coding should not go above 50k coding. 

Is this possible or doable?

**Comment by moldcraft** [comment]
There is no way. And I don't think it will be soon. We have more and more issues to fix and features to implement. We are taking care to make it work well as it is. We split the functionality into extensions, but splitting the core into pieces will be harder to maintain.

----

If you have time and will, you can try to dig into code and remove everything that you don't need.

----

Hypothetical, if you will be able to achieve this task, how will you provide updates for that piece of code in your theme? On every Unyson release you will inspect the diff and changelog, and apply the new changes and features manually then create an update for the theme?

**Comment by thednp** [comment]
@moldcraft your points are well said, for sure. Indeed the core gets more and more light, indeed, I'll think about it, maybe I bring some idea into focus.

Thanks for the reply :)
