### ISSUE TITLE
How to translate date format?

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson#516]
Hi,

how can I translate date format for the events?

Now it show like that : Start: 2015/04/21 18:30

But in french it should be like that : 21/04/2015

**Comment by llemurya** [comment]
@Nic787  open this file `unyson/framework/extensions/events/views/content.php` and covert the date, as a demo please run this line of code 
```php
echo date("d/m/Y", strtotime("2015/04/21 18:30"));
```
If it helps, please close the issue.
