### ISSUE TITLE
[QUICK TUTORIAL] how to require the Unyson Framework on your theme / plugin without TGM

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#517]
Here's it: 

* in your theme (functions.php) / plugin (plugin-name.php) file drop this

	```php
	// wp error messages system function
	function PLUGIN_NAME_requirement_admin_notice() {
		?>
		<div class="error">
			<p><?php _e( 'PLUGIN_NAME requires <a href="'.get_admin_url().'/plugin-install.php?tab=plugin-information&amp;plugin=unyson&amp;TB_iframe=true" class="thickbox" aria-label="More information about PLUGIN NAME" data-title="Unyson">Unyson Framework</a>', 'YOUR_TEXT_DOMAIN' ); ?></p>
		</div>
		<?php
	}
	// check framework and show message
	include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
	if ( is_plugin_inactive('unyson/unyson.php') ) {
		add_action( 'admin_notices', 'PLUGIN_NAME_requirement_admin_notice' );
	}
	```

* replace all <code>PLUGIN_NAME</code> with what it says
* replace all <code>PLUGIN_ID</code> with the exact plugin name, like <code>unyson</code>
* replace <code>YOUR_TEXT_DOMAIN</code> with your own

Disable / enable the UNYSON plugin to check if this code works (it's perfect for me).

**Comment by xpeeder** [comment]
Great I will try my next project :+1:

**Comment by xpeeder** [comment]
@thednp this is not enough flexibility. after inactive you have to go plugin option to active. but from header popup message you cant.
you have to use more condition here

**Comment by thednp** [comment]
It's an idea, you can develop your own unique stuff, it's simple and effective.

TGM code is very often the target of hacks and invulnerability issues.

**Comment by azharijelek** [comment]
<blockquote><strong>TGM code is very often the target of hacks and it's subject to various vulnerability issues.</strong></blockquote>
I didn't know about this, should we use this technique to require other plugins to themeforest?

**Comment by thednp** [comment]
Well this is a small little code you can use that could be a good alternative to TGM.
