### ISSUE TITLE
[Suggestion] Please improve the damn debug or stop the die all the time

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#518]
I'm trying to do some custom extension in a plugin, all well so far but every time I slept a minor typo, I get blank screen in the front and back of the development with "Forbidden" and I have no clue where to look for my minor issue.

**Comment by danyj** [comment]
same here but i look in my error log all the time

**Comment by thednp** [comment]
where is that? (I'm working local on XAMPP)

**Comment by danyj** [comment]
\xampp\php\logs\php_error_log

**Comment by thednp** [comment]
Thanks @danyj 

This is something I hate because I have some more errors with other disabled plugins, no problem, but it's hard to read the 105MB error log every change I make anything.

The problem is: why not use WP debug, I have it enabled and shows nothing, very strange.

**Comment by danyj** [comment]
delete the file , refresh page , new file will be made with exact error on latest page

**Comment by thednp** [comment]
Nop, no file.

**Comment by danyj** [comment]
than check js , js error will also result in blank page

**Comment by thednp** [comment]
Console is perfect white.

**Comment by thednp** [comment]
Now I got no console, no log, just Forbidden, how I have to delete everything and put back, right?
