### ISSUE TITLE
How to remove extenstions in child theme like ex: portfolio in unyson framework?

### ISSUE THREAD

**Issue by krishnavenip** [ThemeFuse/Unyson#519]
please provide the solution for our query requested.
Thanks and regards,
krishna

**Comment by moldcraft** [comment]
Do you mean to be able to delete/remove them from the Unyson Extensions page?

**Comment by krishnavenip** [comment]
yes

**Comment by moldcraft** [comment]
If the user will delete the extensions from the theme, it will be gone forever, he will not be able to install it again (like core extensions which are in available extensions array)

**Comment by krishnavenip** [comment]
ok is there any possibility to hide the extensions

**Comment by krishnavenip** [comment]
i just want to hide the extensions in child theme can you plz guide me to override available extensions array

**Comment by moldcraft** [comment]
> ok is there any possibility to hide the extensions

from css

```css
#fw-ext-EXTENSION_NAME {
    display: none;
}
```

> i just want to hide the extensions using child theme can you plz guide me to override available extensions array

Why you want to do that?

**Comment by krishnavenip** [comment]
i want to integrate only page-builder extension in our theme

**Comment by krishnavenip** [comment]
I am developing a theme for  themeforest marketplace where  i want to create a plugin like mytheme-core which includes a page-builder and my custom post types.

From your framework  i want to use only page-builder and event post type  with it's custom fields only other than that i  don't want to use any other extensions from unyson framework.

let me elaborate  my question 

Thanks
