### ISSUE TITLE
The 'style' component in the 'Typography' option seems to be broken.

### ISSUE THREAD

**Issue by sunny04** [ThemeFuse/Unyson#520]
Hi,

I have the following code for a typography type option.

	'body-font' => array(
	  'label' => __('Body', 'unyson'),
	  'desc'  => __('Body font properties.', 'unyson'),
	  'type'  => 'typography',
	  'value' => array(
	    'family' => 'Arial',
	    'size'   => 16,
	    'color'  => '#666',
	    'style' => '400'
	  ),
	),

All the defaults work correctly, except for the style field I get 'Thin' or sometimes '200' as the default value. This is true even when I have a value other than 400 in the above code. I also changed the name of the option from 'body-font' to a random name on every try, to make sure that an older value from the database was not being retrieved.

Also when I try to remove the style field completely, using the following code, it still doesn't work.

	'body-font' => array(
	  'label' => __('Body', 'unyson'),
	  'desc'  => __('Body font properties.', 'unyson'),
	  'type'  => 'typography',
	  'value' => array(
	    'family' => 'Arial',
	    'size'   => 16,
	    'color'  => '#666',
	    'style' => '400'
	  ),
	 'components' => array(
		'style' => false
 	 ),
	),

However, in one instance of my code, the style field is completely removed, but it is the one where I only wanted to have the 'size' field. Following is the code that only outputs the 'size' field which is what I wanted in that case.

	'heading-2' => array(
	  'label' => __('H2', 'unyson'),
	  'desc'  => __('Size for h2.', 'unyson'),
	  'type'  => 'typography',
	  'value' => array(
	      'size' => 30
	  ),
	 'components' => array(
	    'family' => false,
	    'size'   => true,
	    'color'  => false
	  ),
	),

Please tell me if this is a bug or if I've missed something. I just want to set a default value for the style component, or simply not have it.

Thanks!

**Comment by valeriuzdrobau** [comment]
Hi! Yes, it was a small error, I [corrected](https://github.com/ThemeFuse/Unyson/commit/df868b6b7b76d6771baec96e0603d822b2ae87a0) it. Thank you for reporting!

**Comment by sunny04** [comment]
@valeriuzdrobau Thank you for such a quick response and fix!
However, I assume this fix will not be in the stable version yet, so can you tell me if I can copy the updated file and paste it somewhere in my theme, so that it fixes the problem?

Thanks again.

**Comment by moldcraft** [comment]
[`unyson/framework/includes/option-types/typography/class-fw-option-type-typography.php`](https://github.com/ThemeFuse/Unyson/blob/df868b6b7b76d6771baec96e0603d822b2ae87a0/framework/includes/option-types/typography/class-fw-option-type-typography.php)

**Comment by sunny04** [comment]
@moldcraft I'm sorry I typed my last reply in a hurry and wasn't very clear. I actually wanted to know if I can paste that file inside my theme or should I just replace that file from the plugin. So perhaps I could paste the file inside the 'framework-customizations' folder in my theme so that it could overide the file in plugin.

I'm just curious if it can work that way; otherwise, since Im still developing I can just replace the file in the plugin with no problem.

Thanks.

**Comment by moldcraft** [comment]
Replace the file in plugin. The next release will be live in a week.

**Comment by sunny04** [comment]
@moldcraft @vbarbarosh I just replaced the file in the plugin, but I'm still having the same problem. The style is always 200, even if I set the default to any value or set it to false.

**Comment by valeriuzdrobau** [comment]
Please pull what is now on github, and tell me if there is error.

**Comment by valeriuzdrobau** [comment]
'style' component occurs with family component, now not exist the possibility to have 'family' without 'style'. 'style' component decide the properties 'font-weigh' and 'font-weight', but it is not right, it was done so because it drew the designer, to be simple to set up. There are several problems in typography, in the future we'll have another typography option type.

**Comment by valeriuzdrobau** [comment]
We recommend using [`typography-v2`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#typography-v2) option type.
