### ISSUE TITLE
Hmm population_method, or why I feel this framework is going bloatty all the way

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#521]
Here I am at the 5th attempt trying to create my own extension out of your core slider extension. 

Now I don't know how to do it anymore, puzzled.
* should I make an extension of the existing slider extension? just like the other extensions: owl-slider, bx-slider, etc... but this looks very much not very pro. I would only need a population method for a widget but not for a slider. IMO.
* should I continue trying to do it separate, what should I follow: the documentation, the examples, do you have a dummy example to start from?

Thanks for any reply :)

**Comment by llemurya** [comment]
@thednp population methods can't exists without sliders. Please describe more details about your extension and what you want to do and I'll give you an detailed answer

**Comment by thednp** [comment]
I want my own extension called <code>dnp_slider</code>, without population methods, and working it out of your existing sliders extension is very tricky and confusing. The sliders is in fact called <code>media</code> and is pretty hard to clean the population method coding I don't need. 

Above all, I'm sure gonna get stuck implementing some builder custom work on it. I wish the documentation would cover more or give some basic step by step on how to create some basic extension like your slider and your contact from builder. I basically want to build slides like building contact forms, and that's gonna get very messy.

**Comment by llemurya** [comment]
@thednp what you want to do is the next version of the slider that is in todo list, the one problem with this concept of creating sliders is that every time you build an slider you must create it from scratch, now you can reuse created sliders

**Comment by thednp** [comment]
You mean I cannot edit some slider I created previously?

**Comment by llemurya** [comment]
Sorry github was down for maintenance. We will think on an concept how you can create and reuse already created sliders.

**Comment by thednp** [comment]
So for me to know, what I'm looking for can be done, right?

**Comment by thednp** [comment]
@llemurya you said "you build an slider you must create it from scratch", you mean I can do what I want but I have to build everything from scratch
