### ISSUE TITLE
Can't install it on the latest WP

### ISSUE THREAD

**Issue by kahaeia1** [ThemeFuse/Unyson#523]
When I want to install the plugin in Azure, it fails saying:

Could not copy file. D:/home/site/wwwroot/wp-content/plugins/unyson/CONTRIBUTING.md

**Comment by valeriuzdrobau** [comment]
Seems to be a problem on your server Try to install it using FTP.

**Comment by valeriuzdrobau** [comment]
Due to inactivity I close this issue. Feel free to reopen it at any time.
