### ISSUE TITLE
Rendering shortcodes twice was disable

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#525]
Currently, I'm using the first rendering shortcodes to collect dynamic css, after upgrade to new version of Shortcodes Extension. It was turned off that functions. Anyone have the solutions for this case ?

**Comment by moldcraft** [comment]
Try [this action](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/90e527d8b6b548f93d742ec89ffb078a9bf09efd/class-fw-extension-shortcodes.php#L134)

**Comment by danyj** [comment]
see this  https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-94061237

I did this 

in 

    themes\themename\inc\unyson-extend-name\extensions\shortcodes

add file name hooks.php

inside add 


	function _thz_section_css($data) {
	
		$atts = _thz_shortcode_options($data);
		// my section inline css
	}
	add_action(
		'fw_ext_shortcodes_enqueue_static:section',
		'_thz_section_css'
	);

	/*
		get sortcode options
	
	*/
	function _thz_shortcode_options($data){
		
		$atts = shortcode_parse_atts( $data['atts_string'] );
		$atts = fw_ext('page-builder')->get_shortcode_atts_coder()->decode_atts( $atts );	
		
		return $atts;
	}

**Comment by moldcraft** [comment]
If you want to extract attributes encoded array values, use this https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-94076856

**Comment by maiakhoa** [comment]
Thank @moldcraft and @danyj 
it's the way that solve my case.
