### ISSUE TITLE
Unyson Content install problem

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#526]
Hi guys,

When installed the demo content using the content install module, it shows Fatal error: Class 'ZipArchive' not found in /home/musclepr/public_html/wp-content/plugins/unyson/framework/extensions/backup/includes/exports/class-fw-backup-export-full.php on line 14

Any idea how to resolve this? Well, the back up is importing fine in my localhost but not in my live server. Please give me a hand :)

**Comment by linjo** [comment]
Guys any updates?

**Comment by valeriuzdrobau** [comment]
You must install [zip extension](http://php.net/manual/en/book.zip.php).

**Comment by valeriuzdrobau** [comment]
Please tell me the result, to know if I can close this issue.

**Comment by linjo** [comment]
yea , please close

On 11 May 2015 at 11:43, Valeriu <notifications@github.com> wrote:

> Please tell me the result, to know if I can close this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/526#issuecomment-100783698>.
>



-- 
Linjo Joson
