### ISSUE TITLE
Looking for $hooks to add_action in custom Unyson extensions

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#527]
Hi there,

I'm building another extension for Unyson and for this, I need to *play with the database*. I'm writing in the database with the data set in Extension Settings page. It's almost working perfectly, but I'm stuck on a few points : 
*I'm looking for $hooks, to add my own functions in the good timing : *

* When the "Save" button is pressed (so I cab update my table with the new data)
* When the extension is activated 
* And also when an input from the addable-option is deleted (so I can update the database)

I got the PHP code, but I don't now where to hook it. For now, I run my functions with : `function _init()` but that's stupid ... 

Something like : 

> add_action("extension_enabled","poll_create_table");
add_action("data_saved","poll_update_table"); 

will be quite good :+1: 

I searched this morning for several hours in order to find those hooks, but nothing really works or I use them badly...
`activate_extension()` spotted but can't use it in my own extension or I don't get how.
`fw:option-type:addable-option:option:init`, nothing when we delete it ?

Thank you very much for your help, if you just have a quick snippet for me as an example that would be perfect ;)

Keep up the great work!

2F

**Comment by moldcraft** [comment]
Hi

* [When the "Save" button is pressed](https://github.com/ThemeFuse/Unyson/blob/df868b6b7b76d6771baec96e0603d822b2ae87a0/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2298)
* [When the extension is activated](https://github.com/ThemeFuse/Unyson/blob/df868b6b7b76d6771baec96e0603d822b2ae87a0/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L473)
* > And also when an input from the addable-option is deleted (so I can update the database)

    Do you mean a javascript event?

    P.S. I think a better solution would be to compare addable-option value [before save](https://github.com/ThemeFuse/Unyson/blob/df868b6b7b76d6771baec96e0603d822b2ae87a0/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2298) and after (`fw_get_db_ext_settings_option(...)`) and detect which elements were deleted.

**Comment by 2Fwebd** [comment]
Thanks @moldcraft ! 

I've tried, regarding the "save" buttons it works well :+1: 

Then, for the activation/deactivation, if I do this : 
public function _init() {
	add_action('fw_extensions_after_activation', array($this, 'poll_create_table'));
	add_action('fw_extensions_after_deactivation', array($this, 'poll_delete_table'));
	add_action('fw_extension_settings_form_saved:poll', array($this, 'poll_add_answers'));
} 
It'll run the functions for every move on the extension (if I disable the Page Builder extension for instance). And if I do like that :  
public function _init() {
	add_action('fw_extensions_after_activation:poll', array($this, 'poll_create_table'));
	add_action('fw_extensions_after_deactivation:poll', array($this, 'poll_delete_table'));
	add_action('fw_extension_settings_form_saved:poll', array($this, 'poll_add_answers'));
} 
Doesn't works ... any idea ? 

>P.S. I think a better solution would be to compare addable-option value before save and after (fw_get_db_ext_settings_option(...)) and detect which elements were deleted.

Great idea, sounds easier in my mind ;) ! I'll try that thanks !

2F

**Comment by moldcraft** [comment]
>     add_action('fw_extensions_after_activation', array($this, 'poll_create_table'));
>
> It'll run the functions for every move on the extensions
>
>     add_action('fw_extensions_after_activation:poll', array($this, 'poll_create_table'));
>
> Doesn't works ... any idea ?

Of corse it will not work because there is no such action...

[This action](https://github.com/ThemeFuse/Unyson/blob/df868b6b7b76d6771baec96e0603d822b2ae87a0/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L473) gives you an array of extensions, so you can check if your extension is there

```php
add_action('fw_extensions_after_activation', array($this, 'poll_create_table'));

public function poll_create_table($extensions) {
    if (!isset($extensions['EXTENSION_NAME'])) {
        return; // do nothing
    }

    // do something
}
```

----

I see that you named you extension `poll`, I recommend to prefix the name, for e.g. `2f_pool`, in case someday we will create an extension with the same name.

**Comment by 2Fwebd** [comment]
Thanks @moldcraft ! 
That's awesome !!
2F

**Comment by 2Fwebd** [comment]
Hey @moldcraft,

My extension is almost finish and works perfectly, but I'm still stuck on the : 

>P.S. I think a better solution would be to compare addable-option value before save and after (fw_get_db_ext_settings_option(...)) and detect which elements were deleted.

After, 3 hours of trying, trying, fail, fail, fail... a little help would be welcome ;) 

I tried almost everything in [this function](https://github.com/ThemeFuse/Unyson/blob/df868b6b7b76d6771baec96e0603d822b2ae87a0/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2298) nothing works for me ..

So, I have an array with the new options (from a `fw_get_db_ext_settings_option` call) in a variable `$data_new` and I want to delete the ones in the database (table name set in the class with WOFFICE_POLL_TABLE) which aren't in `$data_new`. Sounds easy like that but it drives me crazy since this morning...

Which is different that comparing `$data_new` with `$data_old` (that I can't get btw) with a 'array_diff' then get the row in the database table and delete them, right ? 

I hope that makes sense. Thank you.

2F

**Comment by moldcraft** [comment]
http://ideone.com/RE1IqC

I don't understand, what actually fails?

**Comment by 2Fwebd** [comment]
I don't understand how to get the old values -> $old_values : 
https://github.com/ThemeFuse/Unyson/blob/df868b6b7b76d6771baec96e0603d822b2ae87a0/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2298
with the action `fw_extension_settings_form_saved `, in fact just extract the `$options_before_save` inside. As all my function is located in a function triggered with `add_action('fw_extension_settings_form_saved:woffice-poll', array($this, 'woffice_poll_add_answers'));`
Thank you very much :+1:

**Comment by moldcraft** [comment]
Add an `fw_print($options_before_save)` and see what's inside, then extract what you need.

I think you are looking for this:

```
$removed_values = array_diff(
    $options_before_save['addable_option_id'],
    $this->get_db_settings_option('addable_option_id')
);
```

**Comment by 2Fwebd** [comment]
Thank you @moldcraft  !!! I'll work on that tonight and make it works.
2F
