### ISSUE TITLE
Popup option type can not save data

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#529]
Hi team,

Please help me this case. After upgrade to new version, popup option type can not save data, below is options :
```
'button' => array(
        'type'          => 'popup',
        'label'         => __( 'Button', 'fw' ),
        'button'        => __( 'Edit', 'fw' ),
        'desc'          => __( 'Here you can add, remove and edit your button.', 'fw' ),
        'popup-title'   => __('Edit button', 'fw'),
        'popup-options' => array(
            'label'  => array(
                'label' => __( 'Button Label', 'fw' ),
                'desc'  => __( 'This is the text that appears on your button', 'fw' ),
                'type'  => 'text',
                'value' => ''
            ),
        ),
    ),
```

**Comment by moldcraft** [comment]
The save works fine on my side. I added your array to `{theme}/framework-customizations/theme/options/settings.php`.

Make sure you don't have id conflict. Rename `'button' => array(...` to `'button' => array(...` and try again.

**Comment by maiakhoa** [comment]
I tried to change the id but it didn't work. That function worked normal on old versions of Unyson. Could you try it with shortcode option ?

**Comment by moldcraft** [comment]
It doesn't work in shortcode. I'm investigating this.

**Comment by maiakhoa** [comment]
Thank @moldcraft

**Comment by moldcraft** [comment]
[The fix](https://github.com/ThemeFuse/Unyson/commit/3ce41eecb2f5c4565204c699f653089ac3a1bcfd)

Please replace [this file](https://github.com/ThemeFuse/Unyson/blob/3ce41eecb2f5c4565204c699f653089ac3a1bcfd/framework/includes/option-types/popup/class-fw-option-type-popup.php) manually and test if it works fine.

I will create today a new [release approval](https://github.com/ThemeFuse/Unyson-Extensions-Approval) for Unyson.

**Comment by maiakhoa** [comment]
@moldcraft 
It's working fine now, but having another issue, that the multi-picker option type in popup don't work

**Comment by moldcraft** [comment]
The multi-picker works on my side.
Please give me your multi-picker option array.

**Comment by maiakhoa** [comment]
@moldcraft please get below option
```
'border' => array(
        'type'  => 'multi-picker',
        'label' => false,
        'desc'  => false,
        'picker' => array(
            'enable_border' => array(
                'label'   => __('Enable Border', 'fw'),
                'type'  => 'switch',
                'right-choice' => array(
                    'value' => 'no',
                    'label' => __('No', 'fw'),
                ),
                'left-choice' => array(
                    'value' => 'yes',
                    'label' => __('Yes', 'fw'),
                ),
                'value' => 'no',
            ),
        ),
        'choices' => array(
            'yes' => array(
                'border_color' => array(
                    'label' => __('Border Color', 'fw'),
                    'type'  => 'color-picker',
                    'value' => '',
                ),
                'border_width' => array(
                    'label' => __('Border width', 'fw'),
                    'type'    => 'select',
                    'value'   => '1',
                    'choices' => number_array(1, 10, 1),
                ),
                'border_style' => array(
                    'label' => __('Border style', 'fw'),
                    'type'    => 'select',
                    'desc'    => __( 'Style of border', 'fw' ),
                    'value'   => '1',
                    'choices' => array(
                        'solid'  => __('Solid', 'fw'),
                        'dashed'  => __('Dashed', 'fw'),
                        'dotted'  => __('Dotted', 'fw'),
                        'double'  => __('Double', 'fw'),
                        'groove'  => __('Groove', 'fw'),
                    ),
                ),
            ),
        ),
    ),
```

**Comment by moldcraft** [comment]
Works too.

Try to install [the latest Unyson dev version](https://github.com/ThemeFuse/Unyson/archive/master.zip) manually, also make sure you have the latest extensions: Go to updates page and click [Check Again](http://static.md/f461fcd84e465ff7f7314180177d6806.png) then make sure you install all the updates (if there are some)

**Comment by maiakhoa** [comment]
I tried to update manually the latest Unyson dev version but it doesn't work.
Actually, popup-options is getting by another shortcode's option like below 
```
$button = fw_ext( 'shortcodes' )->get_shortcode( 'button' );
$button_options = $button->get_options();

'button' => array(
        'type'          => 'popup',
        'label'         => __( 'Button', 'fw' ),
        'button'        => __( 'Edit', 'fw' ),
        'desc'          => __( 'Here you can add, remove and edit your button.', 'fw' ),
        'popup-title'   => __('Edit button', 'fw'),
        'popup-options' => $button_options
    ),
```

And in options's button, it include multi-picker option like the last one I sent you

**Comment by maiakhoa** [comment]
I saw that the value of picker is not saved, all values inside "Yes" choice is saved fine.

**Comment by moldcraft** [comment]
I placed 'border' it inside 'button' and it's not saving. I'm investigating this.

**Comment by moldcraft** [comment]
Please install again [the latest Unyson dev version](https://github.com/ThemeFuse/Unyson/archive/master.zip) manually and let me know if it works.

**Comment by maiakhoa** [comment]
Thank @moldcraft 
It works fine
