### ISSUE TITLE
Theme Settings - Options

### ISSUE THREAD

**Issue by MichaelRise** [ThemeFuse/Unyson#53]
Hey,

Thanks for this great framework.
I have one problem.

My settings.php code:

```
$options = array(
    'main_post' => array(
        'type'  => 'box',
        'options' => array(
            'post_header' => array( 
                'title' => __('General', 'fw'),
                'type'  => 'tab',
                'options' => array( 
                    'main_logo' => array(
                        'type' => 'upload',
                        'label' => __('Logo', 'unyson'),
                        'desc' => __('Please select the logo image.', 'unyson'),
                    ),
                    'main_logo_retina' => array(
                        'type' => 'upload',
                        'label' => __('Logo Retina', 'unyson'),
                        'desc' => __('Please select the logo image for Retina displays.', 'unyson'),
                    ),
                    'my_text' => array(
                        'type'  => 'textarea',
                        'label' => __( 'My Text', 'fw' ),
                        'desc'  => __( 'Write the heading subtitle content', 'fw' ),
                    ),
                ),
            ),
            'post_layout' => array( 
                'title' => __('Blog', 'fw'),
                'type'  => 'tab',
                'options' => array(

                ),
            ),
        ),
    ),
);
```

Get options:

```
$settings_options = fw()->theme->get_settings_options();
echo $settings_options['my_text'];
```

I do not know why but I have nothing.
So please help and sorry for my english.

**Comment by gaiagilder** [comment]
Hello,

I tried to set background image for the breadcrumbs section,

this is what is implemented:

**page_helpers.php**

    `'bdcrumbs_background' =>array(
     'type'  => 'upload',
     'label' => __('Breaddcrumbs Background', 'namaste-lite'),
     'desc'  => __('Set Breaddcrumbs Background', 'namaste-lite'),
     'images_only' => true,
     )`

**theme_function.php**

    `function _action_theme_wp_print_styles() {
    if(!defined('FW'))return;

    $option_value = fw_get_db_settings_option('bdcrumbs_background');

    ?>
    <div class="test"><?php echo $option_value; ?></div>
    <?php
    }
    add_action('wp_print_styles', '_action_theme_wp_print_styles');`
    ?>

The option in "Page Otions" is displayed and i can upload an image from gallery, the Thumbnail is displayed also, how can i get the url of the selected image? 

I tried  everything suggested in this post but I can not get out.

**Comment by moldcraft** [comment]
Where is `page_optons.php` used/included?

**Comment by gaiagilder** [comment]
Tried to look around but i does not find any requires or include rule in the tree directory of httpdocs, sry i'm not a good php guy, i only know that it can work partially because the test div element is rendered, also the css is generated but with nothing into url apices,

i also tried another approach but nothing:

    `function _action_theme_wp_print_styles() {
    if(!defined('FW')) return;
    
    $option_value = fw_get_db_settings_option('bdcrumbs_background');
    echo
    '<style type="text/css">'
    . '.breadcrumbs { '
    . '	background-image: url("'. esc_url($option_value['url']) .'"); '
    . '}'
    . '</style>';
     ?>
    <img class="test" src="<?php echo esc_url($option_value['url']);?>"/>

    <?php
    }
    add_action('wp_print_styles', '_action_theme_wp_print_styles');`

**Comment by moldcraft** [comment]
[Functions to get db value](http://manual.unyson.io/en/latest/helpers/php.html#database)

**Comment by Farzan-Shahid** [comment]
Please help me in following issue:
I'm unable to show icons in frontend.

My footer-setting.php code:
<?php
if (!defined('FW')) {
    die('Forbidden');
}
$options = array (
    'footer' => array (
        'title'   => esc_html__('Footer Settings' , 'swan') ,
        'type'    => 'tab' ,
        'options' => array (
            'footer_settings' => array (
                'title'   => esc_html__('Footer Settings' , 'swan') ,
                'type'    => 'box' ,
                'options' => array (                    
					'copy_rights' => array (
                        'type'  => 'text' ,
                        'value' => '2017 © Swan Lake. All rights reserved.' ,
                        'label' => esc_html__('Copy Rights' , 'swan') ,
                     ),
					'footer_icons' => array(
						'type'  => 'addable-box',
						'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
						'label' => __('Label', '{domain}'),
						'desc'  => __('Description', '{domain}'),
						'help'  => __('Help tip', '{domain}'),
						'template' => 'Hello {{- icon_footer }}', // box title
						'box-controls' => array( // buttons next to (x) remove box button
							'control-id' => '<small class="dashicons dashicons-smiley"></small>',
						),
						'limit' => 0, // limit the number of boxes that can be added
						'add-button-text' => __('Add', '{domain}'),
						'sortable' => true,
						'box-options' => array(					
							'icon_footer' => array (
								'type'  => 'icon',
								'value' => 'fa fa-facebook',
								'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
								'desc'  => __('Select icons', 'swan'),
								'help'  => __('Click to select and click to unselect', 'swan'),
							),	
						),		
					),					
                )
            ) ,
        ),
    )
);

My footer.php code to get icon:

<?php		
$footer = '';
if (!empty(fw_get_db_settings_option('icon_footer'))) {
    $footer = fw_get_db_settings_option('icon_footer');
}
?>	
<ul>
<?php echo	'<li><a href="#"><i class="' .  $footer  . '"></i></a></li>'; ?>
</ul>

But this is not working????
