### ISSUE TITLE
Checkbox values not saving in unyson pagebuilder

### ISSUE THREAD

**Issue by linjo** [ThemeFuse/Unyson#530]
Guys,

Some fields in my page builder is not saving the data. Well it saves the data when I save with the unyson dialogue box but when I update the page (in WordPress) it get back to the old value(the check box remain unchecked). Well other fields are saving good, but not this particular field.

FYI, I am working on an instance where I imported the contents through WordPress export/import as xml file. 

Please check this

![unyson](https://cloud.githubusercontent.com/assets/11642633/7535315/4938c2c0-f5a1-11e4-83ea-f1883578ab61.jpg)

**Comment by moldcraft** [comment]
[The fix](https://github.com/ThemeFuse/Unyson/commit/16e95cd78f8f3853029e5b8ea5c8f5f69de9e523)

Please replace [this file](https://github.com/ThemeFuse/Unyson/blob/16e95cd78f8f3853029e5b8ea5c8f5f69de9e523/framework/includes/option-types/simple.php) manually and test if it works fine.

**Comment by danyj** [comment]
same goes for switch when inside modal .  if I change the switch to select it works, 


switch 


	'contain' => array(
		'label' => __('Contain', 'fw'),
		'type' => 'switch',
		'right-choice' => array(
			'value' => 'yes',
			'label' => __('Yes', 'fw')
		),
		'left-choice' => array(
			'value' => 'no',
			'label' => __('No', 'fw')
		),
		'value' => 'yes',
								
		/*
		'type' => 'short-select',
		'value' => 'yes',
		'choices' => array(
			'yes' => __('Yes', 'fw'),
			'no' => __('no', 'fw')
		),*/
		
	)

**Comment by danyj** [comment]
the above option is also in builder , 
it  switch is somewhere inside multi-picker it works , if standalone it does not

**Comment by moldcraft** [comment]
I added the above array in shortcode options, on first level array also inside option-type popup options, the saw works fine.

**Comment by danyj** [comment]
is not in a popup option , it is in builder  section options, 

builder option inside theme settings, all other options work fine

**Comment by danyj** [comment]
I can send you the option and setup in few min if you like

**Comment by moldcraft** [comment]
send me pls

**Comment by danyj** [comment]
is to complicated cant digg it out , need to send like 5 more other options, 
I think is ajax save related , will test bit more

**Comment by danyj** [comment]
on options popup save it is saved as adjusted 
http://prntscr.com/738tdv

on ajax save header shows ok 
http://prntscr.com/738v1c

DB
 http://prntscr.com/738v9w

very strange , how is this possible if header sent   contain: no

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/529 had the same "very strange" behavior, and there was a mistake in option-type popup `_get_value_from_input()`

Just give me the options array to reproduce this.

**Comment by danyj** [comment]
o boy , it is  custom builder option with options inside , just like   your form builder, 

ok see this If option is setup like this 


	'dadadsaada' => array(
			'type'  => 'switch',
			'label' => __( 'Mandatory Field', 'fw' ),
			'desc'  => __( 'Make this field mandatory?', 'fw' ),
			'value' => true,
		),			

it works 

if setup with choices than it does not work

**Comment by moldcraft** [comment]
The option from https://github.com/ThemeFuse/Unyson/issues/530#issuecomment-100463590 is with choices, and it works on my  side. I can't reproduce this.

**Comment by danyj** [comment]
in theme options add 




		'something' => array(
			'label' => false,
			'type'  => 'form-builder'
		),


here  after required options 

https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/text/class-fw-option-type-form-builder-item-text.php#L85

or on your local go to 


    WordPress\wp-content\plugins\unyson\framework\extensions\forms\includes\option-types\form-builder\items\text\class-fw-option-type-form-builder-item-text.php

after  line 85 

add this 


	'contain' => array(
		'label' => __('Contain', 'fw'),
		'type' => 'switch',
		'right-choice' => array(
			'value' => 'yes',
			'label' => __('Yes', 'fw')
		),
		'left-choice' => array(
			'value' => 'no',
			'label' => __('No', 'fw')
		),
		'value' => 'yes',
	
	
	),



go in theme options and in form builder click on single line text 
http://prntscr.com/7394o7
single line text options will show the new one , now switch it to NO , save , refresh , it will stay on YES

**Comment by moldcraft** [comment]
@danyj [fixed](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/08376caca6644e1f6303abe8eff517df52eea984)

Please test if it works fine, then I will add the Forms extension to the approval.

**Comment by danyj** [comment]
nice one!  thank you bud , this one works so far , il test more but for now is ok.

**Comment by danyj** [comment]
I have  all option types in those popups so if something is wrong il report back
