### ISSUE TITLE
[bug]Builder sections dropable in to each other

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#531]
There is a visual bug on section drop , 

http://prntscr.com/72vpom

if section is dragged from top  under the next section , the next section accepts it,

**Comment by moldcraft** [comment]
Maybe [changing the sortable plugin](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25) will also fix this (I'll take a look at this later).

----

This happens in PageBuilder or in your own builder (I remember that you started developing one) ?

**Comment by danyj** [comment]
that s your page builder

**Comment by danyj** [comment]
and is also in mine since the bug is somewhere in builder.js

**Comment by danyj** [comment]
ok than do me HUGE favor please when you start on this improvement 
add the  indexes if at all possible, you hard coded your dragg/dropp inside builder.js  and I cant recreate new one to add indexes, must look for funky workarounds to do that.  A simple data-index to a draggable/droppable element would do me a huge favor. 
this is how I am using it 

http://prntscr.com/73xr9h
http://prntscr.com/73xrd6

but my version is bit buggy on delete and copy. 

take a look here http://mcpants.github.io/jquery.shapeshift/  turn on show index button to see what I mean

**Comment by moldcraft** [comment]
> if section is dragged from top under the next section , the next section accepts it

Please make a video how to reproduce this.

**Comment by moldcraft** [comment]
It's a problem with jquery-sortable plugin: Sometimes the needed events are not triggered.

I hope this problem will disappear when we will switch to [another plugin](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25#issuecomment-136669315).
