### ISSUE TITLE
Slider option type only 0-100 values?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#532]
OMG, this can't be true.

I have this option

<pre>
'logo_width' => array(
	'type'			=> 'slider',
	'label'			=> __('Width','unyson'),
	'desc'			=> '',
	'value'			=> 116,
	'min' 			=> 50,
	'max' 			=> 500,
	'step' 			=> 1,										
),
</pre>

The option is always 0-100?

<img src="http://s27.postimg.org/cqy5zu5zn/sample_width.gif" alt="">

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/options/built-in-option-types.html#slider

I see that min/max must be specified inside `properties` key.

**Comment by thednp** [comment]
Oh man, that was really scary. Thank you!

**Comment by duongancol** [comment]
Hi @moldcraft : I created an options.php in slider, So how can I get value from that in view file.
```php
$options = array(
    'slider-options' => array(
        'type' => 'short-text',
        'label' => __('Slider Speed', 'mauris'),
        'value' => '5000',
```

**Comment by llemurya** [comment]
@duongancol please read about [Unyson database helpers](http://manual.unyson.io/en/latest/helpers/php.html#database) .In dependency where is your options located, there are different methods to get saved values. If it is in `post.php` page, you must use `fw_get_db_post_option`. If is in an `theme-options.php` page you must use `fw_get_db_settings_option`. Please read the documentation and choose your method that resolve the problem.I'am waiting for your response.Thanks.

**Comment by duongancol** [comment]
I added these code to framework-customizations/extensions/media/extensions/slider/extensions/nivo-lightbox/options/options.php. So How can I get value in view folder. Please see here: http://prntscr.com/7qlk90

**Comment by llemurya** [comment]
@duongancol In the `view.php` of the sliders please run this code 
```php
fw_print($data);
```
And you will see your keys printed.I am waiting for your response.

**Comment by duongancol** [comment]
I tried but couldn't find my key. Please see here:
```php
array
(
    [slides] => array
    (
        [0] => array
        (
            [title] => 'BEING SMART CHEF EVERYDAY '
            [multimedia_type] => 'image'
            [src] => '//localhost/culinier/wp-content/uploads/2015/05/placeder.png'
            [attachment_id] => '640'
            [desc] => '10 RECIPES EVERY WEEK UPDATES'
            [extra] => array
            (
                [btn_title] => 'See All Recipes'
                [btn_link] => '#'
            )
        )
        [1] => array
        (
            [title] => 'CHOOSING YOUR FAUVORITE MENU'
            [multimedia_type] => 'image'
            [src] => '//localhost/culinier/wp-content/uploads/2015/05/placeder.png'
            [attachment_id] => '640'
            [desc] => 'THE BEST RECIPE WORDPRESS THEME EVER'
            [extra] => array
            (
                [btn_title] => 'Download Here'
                [btn_link] => '#'
            )
        )
    )
    [settings] => array
    (
        [title] => 'Gallery '
        [slider_type] => 'nivo-slider'
        [population_method] => 'custom'
        [post_id] => '218'
        [extra] => array()
    )
)
``

**Comment by llemurya** [comment]
@duongancol please watch [this screencast](https://youtu.be/bfTeD6a9FXk). For me it works, maybe you made something wrong.Please watch and give us an response.Thanks.

**Comment by duongancol** [comment]
Thank you so much for your screencast. I found that It's my mistake. Please close this issue for me.

**Comment by thednp** [comment]
Alright, finally.
