### ISSUE TITLE
Contact form builder problem

### ISSUE THREAD

**Issue by nenadmk** [ThemeFuse/Unyson#537]
Hello, I am having a bit of a problem with the forms extension. Please see the screenshot. When I try dragging any of the element types, nothing appears. I've captured the JavaScript errors too on the screenshot.
Thanks
![form](https://cloud.githubusercontent.com/assets/5454090/7554304/2221f746-f723-11e4-958f-4d0c962af3fa.jpg)

**Comment by moldcraft** [comment]
Do you have the latest version of extensions and Unyson plugin? (Check the Updates page)

**Comment by thednp** [comment]
Most importantly, do you have any other script conflicts shown in the console?

**Comment by GheorgheP** [comment]
@nenadmk, did you solve the issue so I can close it, or you still have problems?

**Comment by nenadmk** [comment]
I still have the problem and I am using the latest version of both the plugin the the framework. I will investigate in greater detail in two days and will let you know what was the problem.

**Comment by GheorgheP** [comment]
Did you try to disable all other plugins and to switch to a wordpress theme?

**Comment by GheorgheP** [comment]
Please reopen this issue in case the problem persists.

**Comment by nenadmk** [comment]
I've tried disabling all other plugins and that was basically only SmartSlider 2 and that didn't helped. Still 'cant find item type' problem. I've tried switching to another theme but that disables Unison altogether so not much use from that.
