### ISSUE TITLE
[bugs]Is multi select suposed to do this

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#539]
http://prntscr.com/73tcn2

it should list the pages only right?

**Comment by danyj** [comment]
and this also , http://prntscr.com/73tef6

    population post , nav_menu_item


it should not list the ones that have no title right ?

**Comment by danyj** [comment]
and there is small sql bug if multiple post types are selected 

http://prntscr.com/73tglw


    SELECT posts.ID, posts.post_title FROM wp_posts as posts WHERE post_type IN ('nav_menu_item', page') ORDER BY post_date DESC LIMIT 10


    'source' => array('nav_menu_item','page'),

**Comment by duongancol** [comment]
Right! It should not show the Draft Post.

**Comment by danyj** [comment]
thnx for the fix  of implode but there are 2 more bugs in this one
