### ISSUE TITLE
Live progress on Trello

### ISSUE THREAD

**Issue by AhmedBadawy** [ThemeFuse/Unyson#540]
Hello guys,
I discovered this framework a while ago and I fall in love with it really guys great job.

I want to ask about Trello It seems the activity stopped in February!
Is the framework still active for new features and improvements?

Thank you so much and keep up the good work

**Comment by danyj** [comment]
I dont think they use Trello anymore , all suggestions/bugs/support are handled here.

**Comment by moldcraft** [comment]
@sergiubagrin created the trello board and maintained it, but now he's busy with something else.
I will try to maintain it but not guarantee, I have enough issues to manage here on github.

The framework is active, we are here online every day.
