### ISSUE TITLE
Rich Text Editor in Theme Settings is broken after Resetting Options

### ISSUE THREAD

**Issue by hakimjaya06** [ThemeFuse/Unyson#541]
In Theme Settings, Rich Text Editor is broken after clicking on 'Reset Options.' Rich Text Box toolbars disappear and can see text in only 'Text' tab, and nothing shows in 'Visual' tab.

See the screenshots below:
![1](https://cloud.githubusercontent.com/assets/12388897/7558684/a6b40ab2-f7dc-11e4-8330-938553622aba.png)
![2](https://cloud.githubusercontent.com/assets/12388897/7558685/a6b8d380-f7dc-11e4-9cc2-88ec123fc3a6.png)

**Comment by hakimjaya06** [comment]
Tested with Unyson plugin from wordpress.org and ScratchTheme, and WordPress 4.1.5

**Comment by duongancol** [comment]
in framework-cusomization/theme/options/general-setting.php of Scrach theme, add to Rick text option with 
<pre>
'teeny'  => true,
'reinit' => true,
'wpautop' => false,
</pre>

**Comment by moldcraft** [comment]
Also in Customizer it doesn't work. (Tested with Scratch Theme demo options array)

**Comment by hakimjaya06** [comment]
@duongancol Your solution works. However, Rich Text Editor option is in demo.php and demo-2.php files.

**Comment by duongancol** [comment]
I think Unyson team did not add this to Scratch theme because they are busy with new version of Scratch theme. 
When you create rich text editor option, just add my settings above, it will work

**Comment by hakimjaya06** [comment]
@duongancol Agreed. Maybe I can close this issue?
