### ISSUE TITLE
[suggestion] Add widgets pages assignment rather than sidebar assignment . DEVS please participate

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#542]
In ref to #536 

Current sidebar extension lets us assign sidebars to different pages but I think we should rather have assignment for widgets itself than widget positions. 

My thoughts 

This should have been an option type that we can use in theme admin to set the layout on all or specific pages 
http://prntscr.com/73y29s
instead of the crap that other themes do like this 
http://prntscr.com/73y35v

this should be in widgets to let us create positions 

http://prntscr.com/73y2fs

this is where page assignment for widgets should be 
http://prntscr.com/73y2qe

I am not proposing a removal of sidebar or some drastic changes. I am asking for assignment for widgets itself nothing else.

jetpack has Widget Visibility

than you have list of bunch more plugins that do that 
http://www.wpstarted.com/wordpress-select-widgets-to-show/

let us know what you think.

**Comment by moldcraft** [comment]
> DEVS please participate

Not all devs participated in the development of the Sidebars extension (I know very little about it).
So currently only @llemurya knows better the topic.

**Comment by danyj** [comment]
no no , I meant , the unyson community developers, the active members here to give their opinion about this.

**Comment by llemurya** [comment]
@danyj I read the http://www.wpstarted.com/wordpress-select-widgets-to-show/ article, many of the plugins do exact the same thing as sidebars, plus If you specify the `$cfg['show_in_post_types'] = true;` in the `config.php` in the sidebars extension, you will be able to specifiy active sidebar only for this page or post. Here is a [screenshot](http://static.md/87b74660c60ff6f25d0102249597782f.png).

**Comment by danyj** [comment]
@llemurya , they dont do same thing ,  

I might  have 2 widgets in left sidebar , 
first  I want to show on homepage only 
second only in category  

with your logic I cant do that since it controls  position only not the widget itself and 
cfg['show_in_post_types']

does not show that meta on category/taxonmies

look only this one has over 200 reponses where people see how important that little bit is 
http://strategy11.com/display-widgets/

**Comment by llemurya** [comment]
@danyj finally I understand the main idea, It is a good purpose, we will talk about this idea and come with an answer.

**Comment by danyj** [comment]
dont get me wrong , I know I can do this for example 

http://prntscr.com/73ymmv

and than copy widgets from left sidebar than assign etc, so it is big workaorund wich is going to leave me with multiple sidebars 

where this is so much easier to understand 

http://prntscr.com/73yn4q

**Comment by danyj** [comment]
and if you decide to give us this widget assignment , please dont make it an extension or part of sidebar extension , make it as part of the framework  and active via 

   cfg['control_widgets'] = true; 

or something like that 

this way it is always present and we dont have to do extension active check.

**Comment by danyj** [comment]
Here for review , look how small that thing is 
https://github.com/Strategy11/display-widgets/blob/master/display-widgets.php

**Comment by llemurya** [comment]
@danyj we added this purpose in the concept of rethinking sidebars when we will start a new roadmap for sidebars.Now we have as priority other extensions that is in pending.
