### ISSUE TITLE
How do you set default value for addable-popup ? 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#544]
I have one option inside addable-popup and would like to set default addable poup. 
I see that it is an array 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/addable-popup/class-fw-option-type-addable-popup.php#L137
but dont know how to set it up

**Comment by moldcraft** [comment]
Do a `fw_print($addable_popup_db_value)` and that will be the array structure. Any option `'value' => ...` must have db value structure.

**Comment by danyj** [comment]
thank you!

**Comment by danyj** [comment]
one more sorry ,   my option is returning an array of options so my template comes as 

    [object Object]

is there something like 

    {{- array_of_options/option }}

that I can use for template?

**Comment by moldcraft** [comment]
Try

    {{- JSON.strigify(variable) }}

**Comment by danyj** [comment]
nailed it!

**Comment by danyj** [comment]
or anyone else 


    options_aray.option_you_want_to_show
