### ISSUE TITLE
Demo data install: Fatal error: Call to a member function quote() on a non-object in ......

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#545]
Hi
when i tried to install  demo data from  godaddy server i am receiving a fatal error from unyson plugin

Fatal error: Call to a member function quote() on a non-object in /home/content/p3pnexwpnas09_data03/21/2611821/html/wp-content/plugins/unyson/framework/extensions/backup/includes/lib/srdb.class.php on line 608

and now  when i tried to login again. its redirect to my localhost

**Comment by valeriuzdrobau** [comment]
This error is most likely because the method[ quote()](http://php.net/manual/ro/pdo.quote.php) requires PECL and you do not have it enabled. Activate extension and try again. Meanwhile we think of a solution.

**Comment by valeriuzdrobau** [comment]
To escape the redirect, add the following code in `functions.php`:

```
add_action('init', 'tfuse_repair_backup_redirect');

function tfuse_repair_backup_redirect(){
	$your_site_url = 'http://my-site.com';
	update_option('siteurl', $your_site_url);
	update_option('home', $your_site_url);
}
```
replace `http://my-site.com` with your address, and after login delete this code.

**Comment by xpeeder** [comment]
Thank you :)

**Comment by maiakhoa** [comment]
Hi @valeriuzdrobau,

Do we have any solution to solve this issue complete ? It very annoy if the site can be not accessed when occur this issue, and we can not add a piece of code to their site for temporary fix.

Thanks

**Comment by duongancol** [comment]
Hi @valeriuzdrobau : this problem appeared today again on my client site. This isn't first time So Is there any ways to fix it complete without add code to functions.php?

**Comment by valeriuzdrobau** [comment]
Send me please access details (FTP and phpmyadmin) to the email address valeriuzdrobau@gmail.com.

**Comment by duongancol** [comment]
I did, please check your inbox!
