### ISSUE TITLE
Adding Google reCaptcha noCaptcha to contact form builder?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#546]
I've recently discovered the Google reCaptcha noCaptcha API and was curious to know if anyone added / would be interested in developing such feature.

Currently there is such a feature for contact form 7 <a href="https://wordpress.org/plugins/google-no-captcha-recaptcha/">here</a>.

I can try to make some time for development and testing, who's in for the task?

**Comment by GheorgheP** [comment]
Hi,

We will add it in future.

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/c28934173d40bc438ad4f48f0ea0d3e6f08db361

**Comment by thednp** [comment]
Thanks so much, will test asap.
