### ISSUE TITLE
Selectize css missing style for optgroup

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#548]
without my css 

http://prntscr.com/745t98

with my css 
http://prntscr.com/745tkf

	.selectize-dropdown .optgroup-header{
		font-weight:bold;
		font-size:14px;
	}
	.selectize-dropdown .optgroup .option{
		padding-left:20px;
	}

**Comment by danyj** [comment]
updated css

**Comment by moldcraft** [comment]
https://github.com/brianreavis/selectize.js/issues/843
