### ISSUE TITLE
[Question] multi-picker choice sub-options repeated IDs

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#549]
I have a multi-picker option and the choice sub-options have same ID. I want to know if this would have any impact/issue. Example:

<pre>
'choices' => array(
	'choice1'  => array(
		'option1' => array(
			'type' => 'slider',
		),
		'option2' => array(
			'type' => 'slider',
		)
	),
	'choice2' => array(
		'option1' => array(
			'type' => 'slider',
		),
		'option2' => array(
			'type' => 'slider',
		)
	)
)
</pre>
Note: I am reworking a 3500 lines file, I cannot test this yet, at least not in my setup :)

**Comment by moldcraft** [comment]
No impact.
