### ISSUE TITLE
[TRIVIAL] "Forbidden" on framework update issue

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#551]
I just updated and got the same issue described here https://github.com/ThemeFuse/Unyson/issues/426#issuecomment-89968903, I have a screenshot
![issue](https://cloud.githubusercontent.com/assets/6761246/7592289/36204dba-f8db-11e4-8475-8a2bc1eb514a.gif)

**Comment by moldcraft** [comment]
WordPress updates the plugins, the framework does nothing in this case.

**Comment by thednp** [comment]
The site is stuck in maintenance mode, the only thing I need to do is to delete the Unyson plugin and reinstall everything again.

**Comment by moldcraft** [comment]
> the framework does nothing in this case.

I forgot, the framework on update begin, moves all extensions to a temporary directory, then on update finish, moves the extensions back.

I will try to reproduce this.

**Comment by thednp** [comment]
This issue very very annoying, I don't want to imagine thousands of angry users..

**Comment by moldcraft** [comment]
I don't know how to reproduce that error. On my side [the update works fine](https://static.md/95369f4a248d3198e7263c24dcaeea75.png).

Please open `plugins/unyson/unyson.php` and in comment, change `Version: 2.2.10` to a smaller version `2.2.1`. Then in admin you will get a notification to update the plugin, update it to check if that error will happen again.

**Comment by thednp** [comment]
I already changed the file. The site back and front-end show "Forbidden" and cannot do much unless I delete the theme and Unyson plugin.

**Comment by moldcraft** [comment]
Can you find the file the display that `Forbidden`? Or send me the admin and FTP details to `moldcraft[at]email.com` so I will search it myself?

**Comment by thednp** [comment]
I'm working localhost, I can share my screen via teamviewer or skype.

**Comment by thednp** [comment]
UPDATE: when updating the Unyson plugin via the Plugin Manager, (click the link update plugin now), no error even if I go different window or different tab, so I would suggest the issue only happens in WordPress updates page.

**Comment by thednp** [comment]
UPDATE: one of my files that's included from init.php (structure taken from your example theme includes) has this

<pre>
if (!defined('FW')) die('Forbidden');
</pre>

I think I should replace with

<pre>
if ( ! defined( 'ABSPATH' ) ) die( 'Direct access forbidden.' );
</pre>

For some reason, perhaps WP is doing this, the Unyson plugin is disabled, the theme files having the "Forbidden" conditional breaks the scripting of WP update while window is blurred (focusout).

I'll investigate and test everything, then will update here.

**Comment by moldcraft** [comment]
If that is the problem, if you disabled the plugin you should have that Forbidden on every page.

**Comment by thednp** [comment]
I replaced all instances of "Forbidden", now tested update again. Everything is fine.

For future notice: it's better to check for <code>ABSPATH</code> instead of <code>FW</code> for entire files and only check for <code>FW</code> for framework specific code ONLY.
