### ISSUE TITLE
Portfolio / How it works? Documentation improvment

### ISSUE THREAD

**Issue by Alex-Ascet** [ThemeFuse/Unyson#552]
Hi there,

First of all I would like to thank you for this incredible work.

I cannot figurate how the portfolio works, I have read the documentation and I have tried many things without any result.

I am wondering if you can take 10 minutes to explain clearly how to display all the projects on one page. I have tried to add the fw_ext_portfolio_get_gallery_images( $post_id ) function on a page template without result.

I have spent 4 hours on it. Honestly, I'm desperate. I am not a senior Php coder. Could you please explain me in clear steps how to manage the portfolio? I think that few people are waiting for this clear explanation.

Thank you for your time in advance. Really appreciate your support.

Regards

**Comment by Alex-Ascet** [comment]
Hi there,
I have spent few hours again on this Portfolio.. but I definitely need help. Thank you.

**Comment by arlensot** [comment]
Please! :+1:

**Comment by GheorgheP** [comment]
Hi,

Could you provide more info? Because about what you do not understand?

About the `fw_ext_portfolio_get_gallery_images()`, it should an array with images attachments of the portfolio post gallery. You ca check on the scratch theme the way it works: https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/portfolio/views/single.php#L49

**Comment by Alex-Ascet** [comment]
Hi,
I will provide more info:
We have got a template called single.php under portfolio/views/single.php My questions are:
How to use this template?
Where can I select this template to display the portfolio in the admin?
 
I have tried to display the portfolio via the "Menu" options by using the "Portfolio Categories" but nothing.

The way to use and display the template is not clear for me. Thank you so much for your support.

**Comment by GheorgheP** [comment]
Hi,

The template doesn't have anything with the admin are, the `single.php` is just the frontend template for the portfolio post. The `single.php` is the same template as you create in the root theme `single-fw-portfolio.php`. Here you just define the HTML that will be rendered in frontend page of the portfolio post.

What about the menu, I don't see any problems, go to Appearance > Menus and add the portfolio category in the menu: http://screencast.com/t/aFIBBHqI4

What about shortcode, we do not have one shortcodes for the portfolio. You can create one for you if you wish.

**Comment by duongancol** [comment]
hi @GheorgheP : how can I get category lists in single.php of portfolio?

**Comment by GheorgheP** [comment]
Hi @duongancol,

Let's continue here: https://github.com/ThemeFuse/Unyson/issues/589

**Comment by Alex-Ascet** [comment]
Hi GheorgheP,

Thank you for your answer. Apparently my question was not clear.

Here a summary:
- How can we create this page: http://demo.unyson.io/?fw-portfolio-category=portfolio

Thank you for your support I really appreciate.

Regards

**Comment by Alex-Ascet** [comment]
All good. The Permalinks were not setuo on "post name". Thank you
