### ISSUE TITLE
[css bug] Disabled option in select not style 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#555]
Disabled option inside select need bit lighter color 

my css 
http://prntscr.com/74rft3

	select option:disabled { 
		color: #ccc;
	}

yours 

http://prntscr.com/74rgg9

**Comment by creativejuiz** [comment]
Do you know accessibility? Color contrast means something for you?
More information, tools and reading: http://webaim.org/resources/contrastchecker/
Thank you.

**Comment by danyj** [comment]
@creativejuiz  what are you talking about? did you see the images. 
4 options under Home page are disabled 
http://prntscr.com/7g32h2

the disabled option are barely recognizable and I can see bunch of users  who are having trouble recognizing different color shades clicking on disabled option .  That is where accessibility  and color contrast come in play.  

the fix does not have to be #ccc but it needs to make a clear difference between disabled and enabled option.

**Comment by moldcraft** [comment]
> yours
> 
> http://prntscr.com/74rgg9

That is not our style, it's [browser's default style](https://static.md/16ebcb1d619a6f1b2e9b9e28d2040e94.png)

This is how on machine it look in:

* [Chrome](http://static.md/01f29bbdeb9a6868e68dd7a5ba8e1c07.png)
* [Firefox](http://static.md/2973d77c4af21e81428c43006b8ac962.png)

We will not add our custom style. The default is ok.
