### ISSUE TITLE
check function exit from functions.php

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#556]
I'm using Styling, so I add action hook to helpers.php like that to use quick css :
<pre>
add_action('wp_head', '_fw_action_print_additional_css', 100);

		// Add value of option from styling extension
		function _fw_action_print_quick_css()
		{
			if (fw_ext('styling')) {
				$quick_css = fw_ext_styling_get('quick_css', '');

				if (!empty($quick_css)) {
					echo '<style type="text/css">' . $quick_css . '</style>';
				}
			}
		}
</pre>
The problem is that when Unyson is inactivate, it will show an error " is not define function fw_ext...".
So is there any way to check function  fw_ext  before it's called. 
I tried function_exits('fe_ext) but it didn't work.

**Comment by valeriuzdrobau** [comment]
Hi,
please tell me exactly the code that you have, and an error screen. Because I see that the 'hook' you attached a function name, but below you told a function with another name.

**Comment by duongancol** [comment]
Ok, let me explain deeply, when I deactivated Unyson it showed an error:
<pre>Call to undefined function fw_ext()</pre>

I use function that I gave above in helpers.php. In that function, it had 
<pre> if (fw_ext('styling'))</pre>

fw_ext is function of Unyson framework, How can I check that function is exits from functions.php, helpers.php or hooks.php?

**Comment by moldcraft** [comment]
Try

```php
if (defined('FW')):
     add_action('wp_head', ... 
endif;
```

**Comment by duongancol** [comment]
it show other error: 
<pre>
Warning: define() expects at least 2 parameters, 1 given
</pre>

**Comment by valeriuzdrobau** [comment]
Try, to use this code: 

```
if(!function_exists('_fw_action_print_additional_css')) {
	add_action('wp_head', '_fw_action_print_additional_css', 100);

// Add value of option from styling extension
	function _fw_action_print_additional_css()
	{
		if (function_exists('fw_ext')) {
			error_log('fw_ext() exists');
			if(fw_ext('styling')){
				error_log('social extension is loaded');
				//echo Your CSS
			}
		}
	}
}
```

**Comment by valeriuzdrobau** [comment]
If you want to check if function `fw_ext` exists, use `function_exists('fw_ext')` at `init` action, or later.

**Comment by duongancol** [comment]
Thank @valeriuzdrobau and @moldcraft  . It work fine now. 
I will post my function here for people who want to use quick css of Styling. Hope it help
<pre>
if(!function_exists('_fw_action_print_quick_css')){
		// Add value of option from styling extension
		function _fw_action_print_quick_css()
		{
			if(function_exists('fw_ext')){
				error_log('fw_ext() exists');
				if (fw_ext('styling')) {
					$quick_css = fw_ext_styling_get('quick_css', '');

					if (!empty($quick_css)) {
						echo '<style type="text/css">' . $quick_css . '</style>';
					}
				}
			}
		}

		add_action('wp_head', '_fw_action_print_quick_css', 100);
	}
</pre>

**Comment by moldcraft** [comment]
> @duongancol https://github.com/ThemeFuse/Unyson/issues/556#issue-76196560
> I tried function_exits('fe_ext) but it didn't work.

function_exits('f**w**_ext**'**)

> @duongancol https://github.com/ThemeFuse/Unyson/issues/556#issuecomment-101967354
> it show other error:
>
>     Warning: define() expects at least 2 parameters, 1 given

if (define**d**('FW')):

**Comment by duongancol** [comment]
@moldcraft : it works too. Thank you!
