### ISSUE TITLE
Conflict with Wordpress SEO by Yoast

### ISSUE THREAD

**Issue by creativechaosweb** [ThemeFuse/Unyson#557]
Meta Descriptions don't appear with Yoast SEO when Unyson is enabled.

The title tags and other Yoast SEO header tags do get written, but the meta description does not.

We deactivated Unyson and the meta descriptions were correctly shown (but obviously it ruins the site formatting having this disabled)

With Unyson active, pages such as WooCommerce pages which aren't affected by Unyson do show the meta description generated by Yoast.

We do not use the Unyson SEO add-on.

This is occurring in the latest release of Unyson 2.2.10

**Comment by GheorgheP** [comment]
Hi,

Sorry fro big delay.

I just tested the with **Yoast SEO** plugin, and meta description appears properly.
Could you provide more info? Or send the your development site access login to *dev-team@unyson.io*, and I will check.

**Comment by GheorgheP** [comment]
In case someone will have this issue too, please, reopen it.

**Comment by xtinagp** [comment]
Hello @GheorgheP  Yoast can read the meta, but cannot read the content of the site. I always get "Poor" SEO light because according to Yoast, the content is empty.

Any ideas how to fix this?

Thank you
