### ISSUE TITLE
Download a file after submit contact form

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#559]
Anyone can guide me how to archive this. I need to customize Submit button action of Contact Form Builder that can download a file after submit successful.

Thanks

**Comment by moldcraft** [comment]
Hello
*(sorry for late reply)*

I added [this action](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/58d2b4c44085ec0e9a667512c9d9e575a6422d0d). 

Try to [output file and headers](http://stackoverflow.com/questions/7263923/how-to-force-file-download-with-php) then `exit();`
