### ISSUE TITLE
Translation Extension error

### ISSUE THREAD

**Issue by arlensot** [ThemeFuse/Unyson#561]
After installing the Translation Extension, my site went down

Parse error: syntax error, unexpected T_FUNCTION in /home/dcolores/www/wp-content/plugins/unyson/framework/extensions/translation/class-fw-extension-translation.php on line 41

Can you help me how to fix it? URGENT!

**Comment by moldcraft** [comment]
[There](https://github.com/ThemeFuse/Unyson-Translation-Extension/blob/fbc6fa08ce67c0d2d250bf675b26c8ab8a274bca/class-fw-extension-translation.php#L41-L43) is an anonymous function which doesn't not work in php 5.2.

We will fix it in the next release.

For now, you can fix it manually by replacing [those lines](https://github.com/ThemeFuse/Unyson-Translation-Extension/blob/fbc6fa08ce67c0d2d250bf675b26c8ab8a274bca/class-fw-extension-translation.php#L41-L43) with:

```php
add_action( 'widgets_init', create_function('', "register_widget( 'FW_Widget_Language_Switcher' );"));
```

**Comment by arlensot** [comment]
Thanks a lot!

**Comment by moldcraft** [comment]
Thank you for reporting.
