### ISSUE TITLE
Suggestion for color option and some other options

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#564]
Hi!
I'm using typography option. In default we can use function fw_get_db_setting_option() to get the value.
But I think it is better if we make typography and some options that relate to styling such as: color, color gradient,... in new way.

For example, with typography option:
<pre>
array(
    'type'  => 'typography',
   'output' => '.content h1'
)
</pre>
If we add 'output', it will be automatically hooked to wp_head() with : 
<pre><style>
.content h1{
//typography option here
}
</style></pre>
Hope you can get my idea.
Thanks!

**Comment by moldcraft** [comment]
```
[ Option Array ] -> [ Output HTML ] -> [ Transform User Input to DB Value ]
```

This is all an option-type does. 
Adding to it other features will make it to look like an extension.

What are you talking about is very similar to what the Styling extension does.

**Comment by danyj** [comment]
create a function that spits out  html based on the typo options , that is what I did 

    thz_typo_print($typo_array)

the array is the array of the typo option, mine is custom but still same idea

than I add it to my inline css 


   $h1_font 			= thz_typo_print(thz_get_option('h1_font'));
    h1{".$h1_font.";}

**Comment by duongancol** [comment]
@moldcraft : I used to use Styling with my previous theme. I think it is hard to control the output. I usually have to use 'before' option of Styling. But when I choose other color scheme and move back, the value of 'before' option did not change to default value. 
See more here: 
http://i.imgur.com/VBvpc7r.png
http://i.imgur.com/F7q4OwE.png
And now I want user can custom every part of theme from Customizer. That is reason why I don't want to use Styling anymore.
@danyj I can do the same function. But if we all need so why framework does not support in default. It is more convenient for you and I and other developers.

**Comment by duongancol** [comment]
Hi, As I suggested, Kirki now support this feature with prefix that make 'output' is more powerful, you can check it here: https://github.com/reduxframework/kirki/issues/200

**Comment by danyj** [comment]
@duongancol  yes and kirki logic from beginning was normal CSS handling in head, not embed , thus it is easy for them to add things to it. I doubt unyson will be able to do anything like that since it is concentrated on admin more than at frontend.  thus I am using my own classes for document handling and that function I was telling you about ended up being a full blown css print class.

**Comment by duongancol** [comment]
Here is my idea, for example in typography option
array(
    'type'  => 'typography',
   ''output'      => array(
            'element'  => 'body #page',
            'prefix'   => '@media ( max-width: 1000px ) {',
            'suffix'   => '}',
        )
)
If 'output''s exist, Unyson will add 'element' to <head> automatically. Almost my options of typo, color are added to <head>. So it's more convenient if I have a lot of option like that. 

If it isn't exist, It's ok. We can use function like you.

**Comment by moldcraft** [comment]
We will not add such functionality. In https://github.com/ThemeFuse/Unyson/issues/564#issuecomment-102607921 and https://github.com/ThemeFuse/Unyson/issues/564#issuecomment-111405304 is explained why
