### ISSUE TITLE
Image gallery

### ISSUE THREAD

**Issue by arlensot** [ThemeFuse/Unyson#565]
Is it possible to have one as an extension?

Thanks.

**Comment by llemurya** [comment]
@arlensot do you mean to have exact the same extension as sliders , but separate, or you want image gallery extension inside the sliders?

**Comment by arlensot** [comment]
I will like to create an image gallery from all the slides, so if I click the slider it will open a series of images as an image gallery.

Not clicking in each slide. @llemurya

**Comment by llemurya** [comment]
@arlensot at the moment our Slider extension don't have a bulk population method for create gallery.We will at this suggestion in the todo list.Thanks for the idea.
