### ISSUE TITLE
[wp question]Post types that have  archives  listed in admin differ from frontend.

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#567]
Sorry to ask this here but you should know more than anyone out there 

I am finishing my sidebars option and this one is bugging me 

this snip should show all post types that have archives 

	$post_types_archives = get_post_types(
		array(
			'public' => true,
			'has_archive' => true,
			//'_builtin' => FALSE 
		),
		'objects'
	);
	
	foreach ($post_types_archives as $type => $archive ){
		fw_print($archive->label);
	}

in admin the loop show this 
http://prntscr.com/768pf8

in frontend it also shows Post as a type that can have archives
http://prntscr.com/768po9

what am I missing ?

**Comment by llemurya** [comment]
@danyj  `'_builtin' => FALSE ` on the frontend and backend is commented?

**Comment by danyj** [comment]
yes is commented on both sides , take that snip and you will see it

**Comment by danyj** [comment]
here , I used it in a option and was forced to add Posts manualy 



	protected function thz_list_archives(){
		
		$archives = array();
		$allarchives = get_post_types(
			array(
				'public' => true,
				'has_archive' => true
			),
			'objects'
		);
		
		
		$archives['ar_post'] = __('Posts Archive', 'creatus');
		foreach ($allarchives as $type => $archive ){
			
			$label = $archive->label;

			$archives['ar_'.$type] = $label.__(' Archive','creatus');
		}
		unset($allarchives);
		return $archives;
	}

**Comment by llemurya** [comment]
@danyj If you want WordPress native(builtin) post types run this line of code : 
```php
$wp_post_types       = get_post_types( array( 'public' => true, '_builtin' => true ) );
```
If you want only custom post types run this line of code : 
```php
$custom_post_types   = get_post_types( array( 'public' => true, '_builtin' => false ) );
```

**Comment by danyj** [comment]
the idea is to get ALL posts types that have archive

thus 
    
    'has_archive' => true

**Comment by danyj** [comment]
is jut that  front does not match the admin in this case

**Comment by llemurya** [comment]
@danyj please read the documentation of [the get_post_types()](https://codex.wordpress.org/Function_Reference/get_post_types) function, the `has_archive` parameter don't exists.

**Comment by danyj** [comment]
register_post_type  has it  so it is returned by get_post_types   on all post types that have used it in order to activate archive

**Comment by danyj** [comment]
http://prntscr.com/76ky0n   on   my method 

    print_r($allarchives);
