### ISSUE TITLE
Page builder vs Builder confusion

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#572]
OK we have Page Builder which is a shortcode extension  and is extending FW_Extension and  Builder class, 

In backend when nothing is installed the requirements says to install Page Builder , 

where in fact it is installing Builder http://prntscr.com/76yk5f

now ,   I made an option based on Builder , not based on Page builder 

    class FW_Option_Type_ThzSectionBuilder extends FW_Option_Type_Builder 

but if user does not download Page builder extension , the builder is not installed either. 

so the builder , should be present all the time and my option should not be depending on Page builder but on builder , and there is no page builder extension in extension folder but   builder 

http://prntscr.com/76ykqo

where page-builder is rather a shortcode extension , so it belongs to shortcodes than 
http://prntscr.com/76ynsl

 can we please clear this up and can you deliver bare unison with builder  class please

    FW_Option_Type_Builder

like you did for blog and update.

**Comment by moldcraft** [comment]
You can put your option in an extension and in that extension manifest file require the builder extension

**Comment by danyj** [comment]
isn't that kinda dancing around the actual issue?  
you are doing hidden things where one extension depends on the other  without a reason. 
same thing is happening with shortcodes and builder.
