### ISSUE TITLE
Disabling Page Builder for some Templates?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#573]
Is it possible to disable the page builder for specific templates/posts/pages/etc?

**Comment by llemurya** [comment]
You can enable or disable Page Builder from extension settings , please see this [screenshot](http://static.md/546daf9756b30ebe943f6a186246c4c7.png).

**Comment by pe6o** [comment]
Is there some way to disable it on certain Page Templates?

**Comment by llemurya** [comment]
@pe6o at the moment it isn't possible to disable the Page Builder on certain Page Templates.

**Comment by moldcraft** [comment]
Hello,

I added this feature.

Now on [templates select](https://static.md/22be3dce6927aca91398833e8555493f.png) change, if the selected template supports page-builder, the builder will be enabled, else will be disabled. When the builder is enabled manually (clicked on "Visual Page Builder" button) the select value will be changed to firs template that supports builder.

To specify templates that support page-builder, use [this filter](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/004c868a30822b6b0d5bff36b656cb752468a0c8/includes/fw-option-type-page-builder/class-fw-option-type-page-builder.php#L81-L83).

If there are no templates specified, this feature will be disabled (so it is disabled by default).

Please test it: [Download](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/archive/004c868a30822b6b0d5bff36b656cb752468a0c8.zip) and extract in `unyson/framework/extensions/shortcodes/extensions/page-builder/`

**Comment by pe6o** [comment]
You guys neve cease to amaze me!
Gonna test it.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/99

**Comment by pnpetroff** [comment]
Itried using the hook like so:
```php	
add_filter('fw_ext_page_builder_templates', '_filter_theme_disable_page_builder_in_template');
function _filter_theme_disable_page_builder_in_template($templates) {
	$templates = array( 
		'template-blog.php',
		'template-contact.php',
	);
	return $templates;	}
```

These are all of my templates because I want to disable the builder on all of them except the Default Template. However, when I switch to a Template, the only thing that happens is that the **Visual Page Builder** button gets automatically clicked on.

**Comment by GheorgheP** [comment]
In this case just disable the Page Builder from that post type entirely, or use the [get_page_templates()](https://codex.wordpress.org/Function_Reference/get_page_templates) functions to specify all templates in filter.

**Comment by pnpetroff** [comment]
I want to enable the builder only for the Default Template, so I can't turn it off for all pages.

How can I disable it in the templates using `get_page_templates`? As long as I understand if I do:

```php
function _filter_vivian_disable_page_builder_in_template($templates) {
	$templates = get_page_templates();
	return $templates;
}
```
I will enable them. DOing this automatically switches to the page builder when I change Template.

**Comment by DevWael** [comment]
to select custom post types that the builder will work with and disable it for the other post types use the following code

```php
/**
 * Returns an associative array containing all the entries of array1 which have keys that are present in all the arguments when using their values as keys.
 *
 * @param array $array The array with master keys to check.
 * @param array $array2 An array to compare keys against its values.
 *
 * @return array $array2,... A variable list of arrays to compare.
 *
 */
if ( ! function_exists( 'array_whitelist_assoc' ) ) {
	function prefix_array_whitelist_assoc( Array $array1, Array $array2 ) {
		if ( func_num_args() > 2 ) {
			$args = func_get_args();
			array_shift( $args );
			$array2 = call_user_func_array( 'array_merge', $args );
		}

		return array_intersect_key( $array1, array_flip( $array2 ) );
	}
}

add_filter( 'fw_ext_page_builder_supported_post_types', 'prefix_limit_post_types_support', 1 );
function prefix_limit_post_types_support( $all_post_types ) {
	$white_listed_post_types = array( 'page' ); //allowed custom post type names
	$post_types              = prefix_array_whitelist_assoc( $all_post_types, $white_listed_post_types );

	return $post_types;
}
```

**Comment by GheorgheP** [comment]
@pnpetroff You have to play already with javascript. Our developer from The Core did something similar and when the page template is changed, they trigger the Page Builder switch button.
