### ISSUE TITLE
Error with wp-editor option

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#574]
I got an issue when I set properties of wp-editor option of Text block shortcode like that:
<pre>
'tinymce' => true,

'teeny' => false,

'reinit' => true,
</pre>
The problem is it is display both Text and Visual view when I open Text block shortcode. You can see here: http://prntscr.com/779ao8

Thanks!

**Comment by llemurya** [comment]
@duongancol you must set `'tinymce' => false` , please try,If it helps close the issue.

**Comment by duongancol** [comment]
I did but I remove both Text and Visual tab. http://prntscr.com/779e5v
I want to use both Text and Visual  tab. So I set teeny=>false for displaying Color picker. But it shows this error.

**Comment by llemurya** [comment]
@duongancol it is not an error , it is a normal behavior of option type wp-editor, it sets value from your active post if you dont set implicit a value, set `'value'=>'my custom content'` , create new page and test it.

**Comment by duongancol** [comment]
I quite understand, when I test it by adding 'value'. It's still not change, and It  only look like normal when I remove 'value'.

**Comment by llemurya** [comment]
@duongancol plese see this [video](https://www.youtube.com/watch?v=q6_yQCLxRYY&feature=youtu.be), test it when you create a new page , because when you edit the value is already set in database and wp-editor retrieve it from database not from default value.

**Comment by duongancol** [comment]
I got it, thank @llemurya  so much for screencast.
