### ISSUE TITLE
Video background isn't working

### ISSUE THREAD

**Issue by klvmedia** [ThemeFuse/Unyson#575]
Hi,

I'm trying to use the video background section on an element on my page but it doesn't seem to be working. I'm using an MP4 video and inputting the link as http://localhostmysite/wp-content/uploads/2015/05/homepage.mp4

The output in the html is..

data-wallpaper-options="{"source":{"mp4":"http:\/\/localhost\/harrisonfurniture\/wp-content\/uploads\/2015\/05\/homepage.mp4"}}"

There's no error in the console so I'm not too sure where to go from here.

Thank you

**Comment by llemurya** [comment]
@klvmedia you use only unyson plugin or unyson plugin with scratch theme?

**Comment by klvmedia** [comment]
@llemurya I'm only using the plugin

**Comment by llemurya** [comment]
It must works, see this [videot](https://www.youtube.com/watch?v=bqAgKSvwj5Y), maybe you have an javascript error on the page.
