### ISSUE TITLE
Reset button in Customizer

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#576]

**Comment by giathinh910** [comment]
:+1:

**Comment by moldcraft** [comment]
As a described the problem [here](https://github.com/ThemeFuse/Unyson/issues/410#issuecomment-104168361), it's complicated, and has more sense to be implemented by WordPress https://core.trac.wordpress.org/ticket/21666

**Comment by duongancol** [comment]
I'm testing kirki plugin for Customizer. And it supports "Reset" button to reset all settings to default value. 
I think you should look at this. 
http://prntscr.com/7bf3af
