### ISSUE TITLE
Detect when visual page editor is used

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#578]
Hi!

Is there a possibility to detect when the visual page builder is used on a page?

I now have created a custom page template and i need to select a different one to revolve styling issues.

Thanks!

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/79af389b84da2ad4d99bcdb218e5b085534d449e/helpers.php#L3-L9

**Comment by nickkuijpers** [comment]
Awesome fast reply! You guys are good! :)
