### ISSUE TITLE
Demo install. One or more tables in your database are unavailable. The database may need to be repaired

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#579]
Hi
 I have tried to install  a site with demo data. but when i tried to install demo data database connection lost. and first time showing white screen. and then if i go back or refresh showing database corrupt. 
here is the message 
<code>
One or more tables in your database are unavailable. The database may need to be repaired.</code>

and Frontend showing database connection lost

Within this week i have faced same issue twice.  two different server

Thanks

**Comment by valeriuzdrobau** [comment]
Hi! I need more detail to reproduce the error.

**Comment by xpeeder** [comment]
i have just re install and active the plugin
i have just receive a message in top <strong>Could not create post of type fw_backup</strong>

**Comment by xpeeder** [comment]
When i active and deactivate the backup extensions i have received this messgaed in top
<code>.","interval":"180"};var thickboxL10n = {"next":"Suiv.\u00a0>","prev":"<\u00a0Pr\u00e9c.","image":"Image","of":"sur","close":"Fermer","noiframes":"Cette fonctionnalit\u00e9 requiert des iframes. Les iframes sont d\u00e9sactiv\u00e9es sur votre navigateur, ou alors il ne les accepte pas.","loadingAnimation":"http:\/\/www.bga-location.fr\/wp-includes\/js\/thickbox\/loadingAnimation.gif"};/* ]]> */ </code>

**Comment by valeriuzdrobau** [comment]
ok, but to have a clearer picture of error, please do the following steps:
1. Enable debug;
2. Put the following code in [this if](https://github.com/ThemeFuse/Unyson-Backup-Extension/blob/master/includes/exports/class-fw-backup-export-database.php#L279):
```
if(is_wp_error($post_id)) {
	error_log($post_id->get_error_message());
}
```
3. Try to do a install content.
4. Tell me what appears in log file.

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
