### ISSUE TITLE
Possible sql inj?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#580]
I just had someone check my new plugin and in there I used same snippet like you have here 
https://github.com/ThemeFuse/Unyson/blob/b07200874e2560960d557b8506f4ae3345b4c53e/framework/includes/option-types/multi-select/class-fw-option-type-multi-select.php#L228

and was told that is a sql hole if someone knows how to force  $wpdb->get_results

do you think we have an issue there?

**Comment by moldcraft** [comment]
* `$source` is set in option array manually by the developer (safe).
* `$number` is `$number = (int) ( $option['prepopulate'] )` (safe).

**Comment by danyj** [comment]
thank you bud , I made mistake on my end
