### ISSUE TITLE
.fw-container media queries commented?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#581]
Why the queries of the both container classes are commented? At the moment `..fw-container` and `.fw-container-fluid` are the same (which in turn means that the section Full Width On/Off options are the same)
![image](https://cloud.githubusercontent.com/assets/1108563/7777476/0caad11e-00cc-11e5-8d87-31dba2634dd0.png)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/01a383b17b7f5659c87f1773f39b3418e36d3f1a/static/css/frontend-grid.css#L95-L117

**Comment by GheorgheP** [comment]
Hi,

This is because the fixed sizes are not compatible with all themes. 
For example [Twenty Twelve](https://wordpress.org/themes/twentytwelve/), here it looks like: [http://screencast.com/t/QhFl9BXNv3M](http://screencast.com/t/QhFl9BXNv3M)

**Comment by moldcraft** [comment]
@GheorgheP Please write the info above in that [css comment](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/01a383b17b7f5659c87f1773f39b3418e36d3f1a/static/css/frontend-grid.css#L95-L117) for other developers to be clear why it was commented.
