### ISSUE TITLE
Event Calendar Page Template 

### ISSUE THREAD

**Issue by brandonclementson** [ThemeFuse/Unyson#582]
Is there a php function I can use to call the event calendar view in a page template without using the page builder module?

Thanks!

**Comment by brandonclementson** [comment]
Any updates on this issue?

**Comment by GheorgheP** [comment]
Hi,

Sorry or the late response.

Sorry, but this is not possible, as the template is a part of the calendar shortcode.

It can be placed only by using the shortcode. You can create page builder templates.
