### ISSUE TITLE
Forms rows are in another row

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#583]
When I create a contact form with multiple rows that are 1/1 width (it's not necessary for them to be 1/1), they are wrapped in another row ( (`.fw-row >.fw-row`). This results in stacking of two negative `margin-left` and `margin-right`.

![image](https://cloud.githubusercontent.com/assets/1108563/7783353/87b2bce2-0148-11e5-9fc9-fc427c39813d.png)

Result: http://i.imgur.com/nOYTWL5.png

I removed the `fw-row` class from 
**framework-customizations\extensions\forms\form-builder\views\items.php**

but I'm not sure if it breaks anything.

**Comment by GheorgheP** [comment]
We removed the wrapper `fw-row` class
