### ISSUE TITLE
Please give us a preloader icon for admin and or customizer

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#585]
I can do this myself but I dont want to hack around and we need preloaders to be shown in themes admin 
until the options are loaded. The blank screen is just a pain too look at .

Since we now have customizer I can only imagine that we will slow it down with options so it would be nice to do same thing for it.

Something like this http://multifour.com/projects/select/multi-builder/index.html

maybe with unyson icon changing color while loading.

**Comment by duongancol** [comment]
the spin image of wordpress is nice idea. :+1:

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/0419938b0e7fa14db5696e5533929201482863af

Please install the latest dev version to test the loading.

**Comment by duongancol** [comment]
the loading works well on Theme Settings and Page builder. How about customizer?

**Comment by moldcraft** [comment]
The Customizer loading is from WordPress, we it has nothing to do with Unyson.

**Comment by danyj** [comment]
@moldcraft 
not ok ,   admin side tabs , you set header opacity to 0  so admin header is gone

http://prntscr.com/7hpv4k
http://prntscr.com/7hpupz

**Comment by danyj** [comment]
@moldcraft   please do not touch that header , I used it to customize the admin and I used all default divs you had since about 6 months , so please try not to move/disable things

**Comment by moldcraft** [comment]
@danyj [fixed](https://github.com/ThemeFuse/Unyson/commit/355915fe85565e354b8db1a69533893555bbae6e), sorry.

P.S. That opacity was deprecated because [the styles are not loaded in footer anymore](https://github.com/ThemeFuse/Unyson/issues/333#issuecomment-78052162) ([code comment](https://github.com/ThemeFuse/Unyson/commit/355915fe85565e354b8db1a69533893555bbae6e#diff-6ae529d62c26486ad784f55b6940d513L80)).

**Comment by danyj** [comment]
@moldcraft  now we got partials , 
http://prntscr.com/7hq8wl
header loads first , preloader under , than the rest fades in

**Comment by moldcraft** [comment]
I know, I thought that will be fine.
Ok, I will try to make everything to appear in the same time.

**Comment by danyj** [comment]
@moldcraft  please do !  and dont be so shy with that icon size 
make it bigger, go 128px   it is a big admin and lots of space

**Comment by moldcraft** [comment]
@DimiBaitanciuc decided the size

**Comment by danyj** [comment]
and I would color it  #edf7fc   your   page builder color

**Comment by danyj** [comment]
np ,   I can do the rest ,  just load everything at once please

**Comment by moldcraft** [comment]
> and I would color it #edf7fc

The icon is an `.svg` and I can't change it's color from css, so we adjusted the opacity to make it look gray.

> load everything at once please

done

**Comment by danyj** [comment]
@moldcraft  was this removed in 2.4 ?  there is no preloader anymore in latest version.
