### ISSUE TITLE
Event Calendar Page Template

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#586]
Is there a php hook I can use to call the event calendar view in a page template without using the page builder module?

> https://wordpress.org/support/topic/event-calendar-page-template

**Comment by brandonclementson** [comment]
Any updates on this issue?

**Comment by GheorgheP** [comment]
We already responded in this issue. At the moment this is not possible: https://github.com/ThemeFuse/Unyson/issues/582
