### ISSUE TITLE
Fullwidth Page Builder Option

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#587]
I have successfully modified the size of the text-block page builder popup - but I'm stuck on how to make each of the options run full width as well.

I have edited the text-block size by recreating the config file in my theme:
`'popup_size' => 'large'`

Here is an example http://i.imgur.com/wUYASjQ.png?1 - as you can see, I want the WYSIWYG editor to fill the entire popup.

> https://wordpress.org/support/topic/fullwidth-page-builder-option

**Comment by GheorgheP** [comment]
Hi,

Sorry for big delay. The `wp-editor` option type supports the parameter `size` with values:
 - small
 - large

```php
'text' => array(
	'type'  => 'wp-editor',
	'size'  => 'large',
	'label' => __( 'Label', 'fw' ),
	'desc'  => __( 'Description', 'fw' ),
)
```

We will reflect this parameter in documentation.

**Comment by ryan-presgeek** [comment]
Sorry for the super naive question here, but exactly where do I find the files in my Wordpress site that I need to change these values to enlarge the WYSIWYG edit window?
