### ISSUE TITLE
automatically deactivate unyson plugin

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#588]
I have setup a site in justhost server. after few min saw unyson deactivate automatically. 

and then again yesterday night setup again. and now morning again plugin deactivate. o.O 

what is the cause about this issue ??

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/263

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-123617310
