### ISSUE TITLE
can't get categories of Portfolio

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#589]
Hi!
This error in framework-customizatios/extensions/portfolio/views/archive.php of Scratch theme. 
fw_ext_portfolio_get_listing_categories() function is always return empty. 
So I couldn't get categories of portfolio by using this function.

**Comment by Alex-Ascet** [comment]
Hi there,

I have got the same issue. Each item (li) does not have a "category_*" class. So when I use the filter, I can display "All" or nothing when I click on one of the categories. See atached
![screen shot 2015-05-28 at 2 54 54 pm](https://cloud.githubusercontent.com/assets/12162252/7852937/a2e84234-0549-11e5-8eeb-7fb2f2954d75.png)
![screen shot 2015-05-28 at 2 55 04 pm](https://cloud.githubusercontent.com/assets/12162252/7852938/a2f120de-0549-11e5-8f22-d71557caa820.png)
![screen shot 2015-05-28 at 2 55 23 pm](https://cloud.githubusercontent.com/assets/12162252/7852939/a2f69fc8-0549-11e5-91ef-f5a2b0b28c5f.png)

**Comment by GheorgheP** [comment]
Hi,

Sorry for late response.

Could you please check the `fw_ext_portfolio_get_listing_categories` function, as it returns empty if the are no any categories of that taxonomy, or the taxonomy is invalid:
https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/master/helpers.php#L33#L35

Or could you provide the ftp and wp access details to check: dev-team@unyson.io

**Comment by duongancol** [comment]
Now I know how to setup portfolio and how fw_ext_portfolio_get_listing_categories() run. 
The category should be setup like that: http://prntscr.com/7dah2l
So parent category will be Archive page. 
But I hope you will add this to Doc. Many dev was confuse about setting up archive of portfolio page.

**Comment by leondwyer** [comment]
Hi GheorgheP
I'm leon I'm taking over resolving this issues here at work. 
We have set up a short code.  The explanation of the bug above is a little wrong. So I'll correct it. 

We have created extensions>portfolio>shortcodes>portfolio>views>view.php

Whats occuring is the <?php echo $category->term_id ?> seems to be retuning all categories in every loop leaving the last categorie set for all list items.   So all items are being set with the same category.
Before this we had an empty category so it was returning a blank string as you suggested.  

We need to insure that the loop is only returning the selected category for that item not all of them.

Here is our short code view.


<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}
?>
<?php $fw_ext_projects_gallery_image = fw()->extensions->get( 'portfolio' )->get_config( 'image_sizes' );
$fw_ext_projects_gallery_image = $fw_ext_projects_gallery_image['gallery-image']; ?>

<?php
global $wp_query;
$ext_portfolio_instance = fw()->extensions->get( 'portfolio' );
$ext_portfolio_settings = $ext_portfolio_instance->get_settings();

$taxonomy        = $ext_portfolio_settings['taxonomy_name'];
$term            = get_term_by( 'slug', get_query_var( 'term' ), $taxonomy );
$term_id         = ( ! empty( $term->term_id ) ) ? $term->term_id : 0;
$categories      = fw_ext_portfolio_get_listing_categories( $term_id );

$listing_classes = fw_ext_portfolio_get_sort_classes( $wp_query->posts, $categories );
$loop_data       = array(
	'settings'        => $ext_portfolio_instance->get_settings(),
	'categories'      => $categories,
	'image_sizes'     => $ext_portfolio_instance->get_image_sizes(),
	'listing_classes' => $listing_classes
);
set_query_var( 'fw_portfolio_loop_data', $loop_data );
?>

<?php if ( ! empty( $categories ) ) : ?>
<div class="container">
      <h1 class="section-title-h1 gray">AGG Products</h1>
      
    </div>
						<div class="wrapp-categories-portfolio">
							<ul id="categories-portfolio" class="portfolio-categories">
								<li class="filter categories-item" data-filter=".category_all"><a 
										href='#' class="link btn"><?php _e( 'All', 'unyson' ); ?></a></li>
								<?php foreach ( $categories as $category ) : ?>
									<li class="filter categories-item"
									    data-filter=".category_<?php echo $category->term_id ?>"><a
											href='#' class="link btn"><?php echo $category->name; ?></a></li>
								<?php endforeach; ?>
							</ul>
						</div>
					<?php endif ?>
					
					
<div class="entry-content">
					<section class="portfolio" id="Container">
					 <div class="w-section w-clearfix products">	
					 <ul id="portfolio-list" class="portfolio-list">		
<?php	
$args = array( 'post_type' => 'fw-portfolio', 'post_per_page' =>'20', 'order' => 'ASC','post_status' => 'publish');
$loop = new WP_Query( $args );
while ( $loop->have_posts() ) : $loop->the_post();?>
<li class="category_<?php echo $category->term_id ?> w-inline-block item stacked mix category_all portfolio-item">
		<a href="<?php the_permalink() ?>" data-ix="hover-arrow">
			<?php
			$thumbnail_id = get_post_thumbnail_id();
			if( !empty( $thumbnail_id ) ) {
				$thumb_id = get_post_thumbnail_id();
				$image = wp_get_attachment_image_src($thumb_id,'large', true);
			} else {
				$image = fw()->extensions->get('portfolio')->locate_URI('/static/img/no-photo.jpg');
				$thumbnail_title = $image;
			}
			?>
			
			<img src="<?php echo $image[0]; ?>" alt="<?php echo $thumbnail_title ?>"/>
			<div class="w-icon-slider-right arrow"></div>
			<h1 class="item-title"><?php the_field('product_title'); ?>  <?php echo $category->name; ?> <?php echo $category->term_id ?></h1>
			<div class="data"><?php the_field('product_excerpt'); ?></div>
		</a>
</li> 	
    <?php endwhile;?>
</ul>

**Comment by leondwyer** [comment]
<ul id="portfolio-list" class="portfolio-list">		
<?php	
$args = array( 'post_type' => 'fw-portfolio', 'post_per_page' =>'20', 'order' => 'ASC','post_status' => 'publish');
$loop = new WP_Query( $args );
while ( $loop->have_posts() ) : $loop->the_post();?>
<?php 
//print "<pre>";
//print_r($category); 
//print "</pre>";
?>


<?php foreach ( $categories as $category ) : ?>
<li class="category_<?php echo $category->name ?> 123 w-inline-block item stacked mix category_all portfolio-item">
		<a href="<?php the_permalink() ?>" data-ix="hover-arrow">
			<?php
			$thumbnail_id = get_post_thumbnail_id();
			if( !empty( $thumbnail_id ) ) {
				$thumb_id = get_post_thumbnail_id();
				$image = wp_get_attachment_image_src($thumb_id,'large', true);
			} else {
				$image = fw()->extensions->get('portfolio')->locate_URI('/static/img/no-photo.jpg');
				$thumbnail_title = $image;
			}
			?>
			<img src="<?php echo $image[0]; ?>" alt="<?php echo $thumbnail_title ?>"/>
			<div class="w-icon-slider-right arrow"></div>
			<h1 class="item-title"><?php the_field('product_title'); ?></h1>
			<div class="data"><?php the_field('product_excerpt'); ?></div>
		</a>
</li> 	
    <?php endforeach; ?>
    <?php endwhile;?>

</ul>
