### ISSUE TITLE
Add additional option to Form Builder field options

### ISSUE THREAD

**Issue by giathinh910** [ThemeFuse/Unyson#590]
Hi. Currently I'm working on contact form and I'm using the Contact form shortcode. When building the form, in each field, I 'd like to add additional icon to illustrate that field. I try to override the default class of each field. But when I add another options to class, it seems that there is no effect. So is there any way to add my custom option to customize field of that form builder extension.

**Comment by GheorgheP** [comment]
Hi,

The solution would be simple, you can extend the form item class to another item. The current problem is that you cannot exclude the form items ( in case you'll extend the `text` form item, sure you'll want to exclude the original one ).

We will work under this and provide a solution in the next versions.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/3e426231104ca66a200af73a6ae19658ac86cf61#diff-d60315b011e060469a0c931aedfa9980R114
