### ISSUE TITLE
Offsets and centering in builder?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#591]
Is it possible to center a column in the builder or create an offset similar to the Bootstrap one?

**Comment by duongancol** [comment]
My way is creating a new column like that 
<pre>
'2_3_off' => array(
		'title'          => '2/4(ofsset2)',
		'backend_class'  => 'fw-col-sm-12 fw-col-sm-8 fw-col-sm-offset-2',
		'frontend_class' => 'fw-col-xs-12 fw-col-sm-8 fw-col-sm-offset-2',
	),
</pre>
in fw-customization/extensions/builder/config.php 
The result look like below:
http://prntscr.com/793pgu

**Comment by moldcraft** [comment]
@duongancol Yes, this is the solution. Thank you

**Comment by duongancol** [comment]
You're welcome @moldcraft
