### ISSUE TITLE
How to attach image with radio button type like background image. 

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#592]
Hello .
I want to align text using radio button type and apply image on radio button type. is there any option like icon in background image for radio button type.

**Comment by moldcraft** [comment]
Maybe [`image-picker`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#image-picker) ?

**Comment by wpthemes786** [comment]
Thanks you saved my life. could you kindly tell me that what the exact purpose of custom events in image picker filed. when we will use this events in what situation.

**Comment by danyj** [comment]
@wpthemes786 ,   on change  works , it is a select

**Comment by wpthemes786** [comment]
Thanks @moldcraft , @danyj

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/592#issuecomment-105203630

I think those events were added when that option-type was used in the Slider extension (I don't know exactly how they were used, but [here is a tip](http://static.md/49d255644b027a753632c04332d04fd3.png)).
When you will make something advanced with that option-type, maybe those events will be useful.
