### ISSUE TITLE
Do we have an event on soleModal close?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#593]
For this guy 
https://github.com/ThemeFuse/Unyson/blob/39bb573a11a867c791415f45bdf6bb0a41166226/framework/static/js/fw.js#L1215

Is there an even that tells me that this was just closed? 

I have this 

	fw.soleModal.show('thz_name_exists', modal_html, {
	   autoHide: 5000,
	   allowClose: true
	});

and  need to run a script  on 

    $('.thz_name_exists')on('close'.....
        
        // run ajax

I cant use OptionsModal since it requires options

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/379#issuecomment-87654377

**Comment by danyj** [comment]
could not find it , thnx for ref

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/427fc20e88cbc6e49f097ab73f212b3654ad1538/framework/static/js/fw.js#L1324-L1331

**Comment by danyj** [comment]
got it , thank you much , senior moment :)
