### ISSUE TITLE
How to display some sections out of the page builder container ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#594]
Hello everyone,

I have a layout in which some portions are not using container. and those portions are full width. but when i used page builder the builder embed his own container in html structure and this will disturbing my layout.

Any quick solution will be very appreciated.

Thanks

Regards

**Comment by duongancol** [comment]
I think you can using the css to override fw-container class.

**Comment by danyj** [comment]
move builder to   

themename\ramework-customizations\extensions\builder
http://prntscr.com/796qkf

builder extension config 





	$cfg['default_item_widths'] = array(
		'1_6' => array(
			'title'          => '1/6',
			'backend_class'  => 'fw-col-sm-2',
			'frontend_class' => 'thz-col-1-6',
		),
		'1_5' => array(
			'title'          => '1/5',
			'backend_class'  => 'fw-col-sm-15',
			'frontend_class' => 'thz-col-1-5',
		),
		'1_4' => array(
			'title'          => '1/4',
			'backend_class'  => 'fw-col-sm-3',
			'frontend_class' => 'thz-col-1-4',
		),
		'1_3' => array(
			'title'          => '1/3',
			'backend_class'  => 'fw-col-sm-4',
			'frontend_class' => 'thz-col-1-3',
		),
		'1_2' => array(
			'title'          => '1/2',
			'backend_class'  => 'fw-col-sm-6',
			'frontend_class' => 'thz-col-1-2',
		),
		'2_3' => array(
			'title'          => '2/3',
			'backend_class'  => 'fw-col-sm-8',
			'frontend_class' => 'thz-col-2-3',
		),
		'3_4' => array(
			'title'          => '3/4',
			'backend_class'  => 'fw-col-sm-9',
			'frontend_class' => 'thz-col-3-4',
		),
		'1_1' => array(
			'title'          => '1/1',
			'backend_class'  => 'fw-col-sm-12',
			'frontend_class' => 'thz-col-1',
		),
	);


and adjust frontend_class to your class names,  

you would also need to do same for shortcodes , section, column 


http://prntscr.com/796qt0

**Comment by wpthemes786** [comment]
Thanks Guys. 
But in config file there is no fw-container class. and i have to play with main contaier class because the grid is working fine but container creates some problems. Kindly provide me exact solution. 

Thanks

**Comment by wpthemes786** [comment]
Here is a quick visual representation .
Kindly fint the following attached images.
![screenshot- domain date time](https://cloud.githubusercontent.com/assets/12461946/7798122/32b2bf44-030f-11e5-8442-3df34f04439c.png)

![screenshot-localhost 2015-05-25 18-53-17](https://cloud.githubusercontent.com/assets/12461946/7798139/7b0bd0f0-030f-11e5-97dc-78a4e1f2f9f0.png)

Thanks
