### ISSUE TITLE
List custom posts in multi select ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#595]
Hello,

I need to list my custom posts in multi select option type for shortcode purpose, Like user can select the post from multi select and save it. 

Is there any posibility to make this functionality.

Thank you guys for such a wonderfull framework.

**Comment by danyj** [comment]
use multi-select option 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/multi-select/class-fw-option-type-multi-select.php#L24

http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi-select

**Comment by wpthemes786** [comment]
Can my work done for just using multi select option type or i have to go through with multi-select.php file top to bottom. Actually just finished my project ASAP.

Thanks
