### ISSUE TITLE
[question]Style palette option

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#596]
I have seen here 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/multi-picker/class-fw-option-type-multi-picker.php#L146

mention of pallete option , are you guys planing on  sharing ?  :))

**Comment by Ataurr** [comment]
:+1:

**Comment by DimiBaitanciuc** [comment]
Not decided yet, we are still discussing it.

**Comment by danyj** [comment]
np , if you could at least describe the design pattern I can build it .   I cant wrap my head around  the concept  at the moment, just brainstorming. This is how kirki design it 
https://github.com/reduxframework/kirki/wiki/palette
but I think is missing associative index as to what element gets what.

**Comment by thednp** [comment]
@danyj, it's super easy to develop a color-palete picker. I personally use mine and another color picker than wp color picker, just they're gonna get merged into one option type.

**Comment by danyj** [comment]
@thednp , im not just thinking about picker , that is easy , I think of dependencies .  
let say you have typography option with color enabled and than you have bunch of color pickers on certain options + same again inside the option popups.  you need a way to connect the palette to all of those. I  see this http://docs.themefuse.com/exposure/your-theme/styling-2/the-color-palette
and it might be what I am after

**Comment by danyj** [comment]
@thednp care to share a screen or the idea behind yours?

**Comment by thednp** [comment]
Not at this point

**Comment by DimiBaitanciuc** [comment]
I'll let one of my colleagues look over the code example you gave, I'm the design guy :)
The idea behind it is that you'll set a color palette in the general settings - http://joxi.ru/Y2LDp1lTMER426 
and we've created an option that looks like this http://joxi.ru/Q2KqDkgSyvNzrj that is linked with the color palette from the general settings. 

This way it's very easy to keep a color consistency across the website, and of course when you change the color palette from the general settings, it will change the colors from the options across the admin. 

Hope this makes sense.

**Comment by danyj** [comment]
@DimiBaitanciuc  thnx and yes I assumed is something like that. 
so what I think you have is a palette for color picker something like this 
http://prntscr.com/79ipmb  but outside the box

what I am after is  this 


you setup up   such pallets  ( those are from redux ) 

http://prntscr.com/79iqkg

when you click on each of them ,  all pickers in theme admin adopt the assigned color ,
thing is I cant wrap my head around coding pattern for it.

**Comment by DimiBaitanciuc** [comment]
well, if we decide to included in Unyson, you'll not have to bother coding it :)
as soon as we decide about this we'll let you guys know

**Comment by danyj** [comment]
:) :+1:
