### ISSUE TITLE
Getting shortcode option value in static.php

### ISSUE THREAD

**Issue by abeel** [ThemeFuse/Unyson#597]
Hi,
in my shortcode static.php i will wp_enqueue_style just if the option in db equals a specified value.
my question is how to get options in static.php like $atts in view.php ?

**Comment by moldcraft** [comment]
`static.php` is not included for every shortcode in builder (for e.g. if you have 7 sections in bulder, it will not be included 7 times for each shortcode).
[It is included only once](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/90e527d8b6b548f93d742ec89ffb078a9bf09efd/class-fw-extension-shortcodes.php#L130) and has no direct connection with any shortcode.

**Comment by abeel** [comment]
ok,
how i can get the option ? i have the shortecode object like this:

       $shortcodes_extension = fw_ext ( 'shortcodes' );
	$team_member = $shortcodes_extension->get_shortcode("team_member");

but i can't access to saved db option what ihave is $team_member->get_Options() file

do you have any idea ?

**Comment by moldcraft** [comment]
You can't get shortcode value outside the view https://github.com/ThemeFuse/Unyson/issues/511#issuecomment-98319183

----

Try to use [this action](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/90e527d8b6b548f93d742ec89ffb078a9bf09efd/class-fw-extension-shortcodes.php#L134-L144)

**Comment by abeel** [comment]
thank you that solve my problem, for some one how had the same problem this is the solution:

in your static.php of your shortecode add this function:


    if (! is_admin ()) {
	if (! function_exists ( 'mytheme_fw_ext_shortcodes_enqueue_static' )) {
		function mytheme_fw_ext_shortcodes_enqueue_static($data) {
			error_log ( print_r ( $data, true ) );
		}
		add_action ( 'fw_ext_shortcodes_enqueue_static:<<your_shortecode>>',       'mytheme_fw_ext_shortcodes_enqueue_static' );
	}
      }

**Comment by moldcraft** [comment]
> in your static.php of your shortcode add this function:

`static.php` file is meant for ``wp_enqueue_*()`` functions, better (recommended) to add that code in ``{theme}/framework-customizations/extensions/shortcodes/hooks.php``.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/70 See the first line in changelog
