### ISSUE TITLE
Backup extension

### ISSUE THREAD

**Issue by apoutsiak** [ThemeFuse/Unyson#599]
Hello,
What server specifications are required for the Backup extension.
Thanks!

**Comment by valeriuzdrobau** [comment]
Hi,
Need [wordpress requirements](https://wordpress.org/about/requirements/), and
1. [ZipArchive class](http://php.net/manual/en/class.ziparchive.php)
2.[ PDO::quote](http://php.net/manual/ro/pdo.quote.php)
