### ISSUE TITLE
Can you help me find this please

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#603]
I wanted to test custom post type with the book example you have 
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/inc/posts.php

and it works ok , but once I added the tax  category to the menu , it shows me the category description 
http://prntscr.com/79y66t
under the menu  title 

http://prntscr.com/79y5gy

I am using your mega menu walker class
This is the menu setup 
http://prntscr.com/79y6pc

**Comment by danyj** [comment]
I found it but please can you explain the reason behind this 

https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/hooks.php#L129

why are you adding it inside the menu ?

**Comment by danyj** [comment]
Seems like a bug , so far I understand you want to add a description for mega menu holder
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/hooks.php#L117
 but as you can see that menu item is not a mega menu , it is a simple item

**Comment by moldcraft** [comment]
See if [this fix](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/commit/080a50af4be441ed01ffccb1d4cdb4ec395572a0) is good.

**Comment by danyj** [comment]
That's the one!
http://prntscr.com/7a5mjo

**Comment by danyj** [comment]
Fix works fine , but can you explain the reason behind that inside the menu please. I have my own override of mega menu and would like to know. Thnx!

**Comment by moldcraft** [comment]
I don't know (there are no comments "for humans" in [that code](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/080a50af4be441ed01ffccb1d4cdb4ec395572a0/hooks.php#L87-L88)).
@vbarbarosh can explain, he is the author.

**Comment by danyj** [comment]
Yeah , by the look of the print 
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/080a50af4be441ed01ffccb1d4cdb4ec395572a0/hooks.php#L104
seems like he intends to add cat description here 
http://prntscr.com/7a5pr8

wich kinda makes no sense. but lest see if @vbarbarosh had different idea behind it.
