### ISSUE TITLE
How to get the categories name using multi select from custom post type.

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#606]
I am using this scenario to retreive the categories $atts['categories'] , but its only returns Id's, an i need taxonomy name which will be pass into get_terms function.

Thanks

**Comment by wpthemes786** [comment]
Actually i want to retreive the taxonomy slug using multi select.

**Comment by abeel** [comment]
you can use wordpress function get_term:

https://codex.wordpress.org/Function_Reference/get_term

**Comment by wpthemes786** [comment]
@abeel  i am using multi select and its returns me category id's array

**Comment by abeel** [comment]
if i understand what you need:
   $result = array();
     foreach ($categories as $cat_ID) {
 	$category = get_term( $cat_ID, 'category' );
 	$result[$id] = ( $category ) ? $category->name : '';
    }

**Comment by wpthemes786** [comment]
$categories ? i didn't understand this logic. i have $atts['category'] from multi select.
and i am using $cat_sepration = implode(",", $atts['category']); this for adding , to each category id.

but the second line is not appropriate for me as i want only categories slugs. eg: i want to make an filterable portfolio using shortcode with multiselect option type. the user selected catgories only show in portfolio template and the result genereted according to selected catgories.

Any help kindly would be very appreciated. Thanks plz

**Comment by wpthemes786** [comment]
Any help @abeel
