### ISSUE TITLE
Page builder - row in row

### ISSUE THREAD

**Issue by web-master72** [ThemeFuse/Unyson#607]
Hi,
Love Unyson framework, great job! 
Is it possible to implement such a structure using Page builder?

![row](http://mycookroom.ru/dsfs2.jpg)

Thanks!

**Comment by moldcraft** [comment]
Hello,
We are glad you like it, Thank you.

It's not possible to have such structure. More details here https://github.com/ThemeFuse/Unyson/issues/230
