### ISSUE TITLE
multiselect for posts did not work?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#608]
Hello.

I am using multi select containing population method as posts and source as post.

if i var dump $atts['selected_posts'] its give me exact selected posts id's.

But when i use this method:

global $post;

$ids = fw_get_db_post_option($post->ID, 'selected_posts');

fw_print($ids);

$posts = get_posts(array(
    'include' => $ids
));

foreach($posts as $post){
    the_title();
}

its print all posts not the selected. 

Kindly sort me out. 

Thanks

**Comment by wpthemes786** [comment]
@GheorgheP  Kindly provide me solution

**Comment by llemurya** [comment]
@wpthemes786 pay attention at `$ids` variable it must be comma- or space-separated list of IDs as `string` or better an `array` `array(1,2,3,4,5,6)` with IDs.

**Comment by wpthemes786** [comment]
@llemurya  but when i fw_print($ids) its return me null. there is no ids if i print it out.

**Comment by llemurya** [comment]
@wpthemes786 If is `null` that means that 'selected_posts' key doesn't exist,please print post data to see the array structure
```php
fw_print(fw_get_db_post_option($post->ID);
```
If is empty array() that means you didn't save `post_options` and you may check if is empty or not.

**Comment by llemurya** [comment]
@wpthemes786 please don't open twice the same issue, if you think that issue is not resolve you can reopen it, and discribe the problem in the same issue.

**Comment by wpthemes786** [comment]
I need the urgent solution and you guys did not reply yesterday thats why i
create the new ticket, sorry it wont happened again.

**Comment by danyj** [comment]
try this 

	$selected_posts = $atts['selected_posts'] ;
	$args = array(
		'post__in' => $selected_posts,
		'orderby' => 'post__in'
	); 
	$posts = get_posts( $args );
	
	foreach($posts as $post){
		the_title();
	}

**Comment by wpthemes786** [comment]
@danyj @llemurya Thank you guys for the solution. The working Solution is below.

global $post;
$selected_posts = $atts['selected_posts'] ;

$args = array(
    'post_type'=> 'post',
    'post__in' => $selected_posts,
    'orderby' => 'post__in'
);
$posts = get_posts( $args );

foreach($posts as $post){
    the_title();
}


Thanks once again.

**Comment by danyj** [comment]
why are you calling global $post when is not used? 

and than  you do   $posts as $post(?)

**Comment by wpthemes786** [comment]
@danyj  if i remove the global $post then it will return me page title not the post title, in my case its return me features title two time, so if i put global $post at the top its return me exact post title with matching id's.

What is the logic behind this.

**Comment by danyj** [comment]
the_title();   should have id 

so you would do 

    the_title( $post->ID );

if you want the post title

**Comment by wpthemes786** [comment]
@ No its return me simple 478 post id not the title. if i do not use global $post. i do not know what's the logic behind this. Anyhow :+1: 

$selected_posts = $atts['selected_posts'] ;

$args = array(
    'post_type'=> 'post',
    'post__in' => $selected_posts,
    'orderby' => 'post__in'
);

$query = new WP_Query($args);

while($query->have_posts()) : $query->the_post();
    the_title();

endwhile; wp_reset_postdata();

This code is working fine for me. I do not use for each loop now because you are right that why we should declare post as global and also used in for each loop.

**Comment by wpthemes786** [comment]
@danyj 

Getting this error. when i use the above same code that worked for simple view when i create two views in shortcode and make a class for switching views. 

i have selected the posts in shortcode interface.
but when i check the page its give me this error.
i have this code in my a.php view file:

<?php if (!defined('FW')) die( 'Forbidden' ); ?>
<?php
$selected_posts = $atts['selected'] ;
print_r($selected_posts);


Notice: Undefined variable: atts in D:\xampp\htdocs\himalayan\wp-content\themes\himalayan\framework-customizations\extensions\shortcodes\shortcodes\demo\views\a.php on line 3
