### ISSUE TITLE
Multiselect for posts listing did not work.

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#609]
Hello.
i hope that anyone gonna reply to this thread,

I am using multi select containing population method as posts and source as post.

if i var dump $atts['selected_posts'] its give me exact selected posts id's.

But when i use this method:

global $post;

$ids = fw_get_db_post_option($post->ID, 'selected_posts');

fw_print($ids);

$posts = get_posts(array(
'include' => $ids
));

foreach($posts as $post){
the_title();
}

its print all posts not the selected.

Kindly sort me out.

Thanks

**Comment by llemurya** [comment]
see issue #608
