### ISSUE TITLE
Display multiselect post values

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#61]
Hi again .I was digging into the framework .I was unable to display  the  corresponding  posts.

``` php
'demo_multi_select_posts_2' => array(
    'type' => 'multi-select',
    'label' => __('Multi-Select: Posts', 'fw'),
    'population' => 'posts',
    'source' => 'post',
    'desc' => __('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'fw'),
    'help' => sprintf("%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
        __('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'fw'),
        __('Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', 'fw')
    ),
),
```

To display the posts I have tried in view.php

``` php
<?php echo do_shortcode( $atts['demo_multi_select_posts_2'] ) ?>
```

But it returns array I guess as I have this warning `WARNING: STRPOS() EXPECTS PARAMETER 1 TO BE STRING, ARRAY GIVEN IN C:\WAMP\WWW\EEE\WP-INCLUDES\SHORTCODES.PHP ON LINE 196` 

How this works I mean does it returns the id's of post?

Edit: To inspect element I used `<?php var_dump(['demo_multi_select_posts_2']); ?>` but it does not return the result.

**Comment by alaminsobuj** [comment]
Thank Nice work , My problem is solve
