### ISSUE TITLE
Getting Undefined variable: atts

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#610]
Hello.

I am using example demo three shortcode from your scratch theme.

This is my options file.

```php
$options = array(
	'view' => array(
		'label'   => __('View', 'unyson'),
		'desc'    => __('Choose what view file should the shortcode pick', 'unyson'),
		'type'    => 'select',
		'choices' => array(
			'a'    => __('View A', 'unyson'),
			'b'    => __('View B', 'unyson'),
			'c'    => __('View C', 'unyson'),
			'rand' => __('Random View', 'unyson')
		)
	),
    'my_posts' => array(
        'type'       => 'multi-select',
        'label'      => __( 'Multi-Select: Taxonomies', 'unyson' ),
        'population' => 'posts',
        'source'     => 'post',
        'desc'       => __( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            'unyson' ),
        'help'       => sprintf( "%s \n\n'\"<br/><br/>\n\n <b>%s</b>",
            __( 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                'unyson' ),
            __( 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
                'unyson' )
        ),
    ),
);
```

And this is my `a.php` file which is the view file. and in this file i have this.

```php
$posts = $atts['my_posts'];
print_r($posts);
```

And i am getting this error.

```
Notice: Undefined variable: atts in D:\xampp\htdocs\himalayan\wp-content\themes\himalayan\framework-customizations\extensions\shortcodes\shortcodes\demo-three\views\a.php on line 5
```

**Comment by wpthemes786** [comment]
And when i put the same code with out different view representation its worked. kindly tell me what i did  wrong.

**Comment by wpthemes786** [comment]
@llemurya @moldcraft  reply please

**Comment by llemurya** [comment]
@wpthemes786 please name your file as 'view.php' it is mandatory, and please read our [documentation](http://manual.unyson.io/en/latest/extension/shortcodes/index.html?highlight=create%20shortcode#creating-a-simple-shortcode) and many question will be clearer.

**Comment by wpthemes786** [comment]
@llemurya Thanks for your quick reply. Actually i forget to add these lines into my class file in shortcode.
return fw_render_view( $view_path, array(
                'atts'    => $atts,
                'content' => $content,
                'tag'     => $tag
            ) );
that's its give me undefined variable error.

I have to ask one question here please.

You said that view.php name must be as view but in my scenario i have two views when user switch it will change the view. 

What names should be in view folder for each file.

Thanks
