### ISSUE TITLE
Possible to fork this and use it for the framework of our own plugin

### ISSUE THREAD

**Issue by cmwwebfx** [ThemeFuse/Unyson#611]
Is it possible to use this as the framework for our own plugin? We are looking at needing a drag and drop builder, but not for a page builder. We would look at stripping out all the things not needed, then building on all the things we do need. Is this something we can do?

Looking forward to hearing back from the Unyson team.

**Comment by danyj** [comment]
It is GPL so forking is ok. I wanted to do exactly the same thing , but trust me when I say that it is not worth the trouble, Unyson team is backing us with all bug fixes and to be honest I would not want to go trough troubleshooting the core when someone else has coded it.

**Comment by cmwwebfx** [comment]
That is awesome. As we are not going to try recreate the wheel of a drag and drop builder it is better to start with an awesome framework like this. We can then strip out the guts of the builder elements and simply build in only the elements we need. Like any framework you need to be right up there with the way they have coded in order to take on a project like this one. 

We would be happier to do that than develop up just another element builder. Thank you for responding @danyj

**Comment by moldcraft** [comment]
Hello @cmwwebfx
I already replied to this question, see [this answer](https://github.com/ThemeFuse/Unyson/issues/515#issuecomment-99106285)

*If you have any ideas how to achieve this without making the things complicated, please share.*
