### ISSUE TITLE
Save layouts and reuse layouts

### ISSUE THREAD

**Issue by cmwwebfx** [ThemeFuse/Unyson#612]
Hi team,

In visual composer we use saving layout a lot in the work we do in building sites. Is this something that is going to be added to Unyson? It is a huge time saver to build a layout for a page, then simply on another page add the saved layout and presto. Complex page created in under a minute.

**Comment by danyj** [comment]
:+1: ,  @cmwwebfx  suggestion , change title to fronted visual page builder or something similar so that other devs can see it and possibly respond.

**Comment by cmwwebfx** [comment]
But I Am not talking about front end builder at all.  I am referring to being able to drag and drop elements until you have a layout that you will often use for other pages.  Then save that layout so that you can reuse the layout when building the next pages that might use that particular layout.

**Comment by moldcraft** [comment]
Hello, 
Have you tried Templates? (on the same line as undo/redo buttons)

**Comment by duongancol** [comment]
I think you can use Templates. See here please: http://prntscr.com/7be6p8

**Comment by martin-bede** [comment]
Is there a way to export these templates so I could bundle pre-made templates I've made with a theme for customers?

**Comment by llemurya** [comment]
@martin-bede our Backup extension export and import already saved templates, but it is a bug with this that is in working stage, https://github.com/ThemeFuse/Unyson/issues/492.
