### ISSUE TITLE
Demo Content Installation Issue

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#613]
Here is the message: 
Every time I’m trying to run the Demo Setup in my Child Theme I’m facing the following error messages:
<code>Warning: Invalid argument supplied for foreach() in /web/WebSites/d/c/h/i//htdocs/wp-content/plugins/unyson/framework/extensions/backup/includes/helpers/class-fw-backup-helper-file-system.php on line 210

Warning: copy(): The first argument to copy() function cannot be a directory in /web/WebSites/d/c/h/i//htdocs/wp-admin/includes/class-wp-filesystem-direct.php on line 23</code>

After displaying these messages the whole content of my website is corrupted. The system renames the existing folder wp-content to e.g. wp-content.2015_05_29-23_06_42

I dont know why my buyers facing issue with demo content installation :( others everything work fine. but this extension give us pain all the time.

**Comment by valeriuzdrobau** [comment]
Hi, sorry for the late response, try version 1.0.4, if the problem persists, give me access details for a server where exist this problem, because I cannot reproduce this error on my server. (you can sent  access details to the email address indicated in this profile)

**Comment by Ataurr** [comment]
I have manually setup the demo for buyer then :( this backup extension give us to much pain. 

hope 1.4 will save us this kind of issue.  i will inform again if i found issue again

Thanks much

**Comment by valeriuzdrobau** [comment]
Please give me more details about your server configuration, because they can not reproduce this error.

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
