### ISSUE TITLE
Is there any way for popup to return associative array?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#614]
Can you add an option for this or at least please advise how to do this 

Currently all options inside of the popup are grouped under one array , 

but I need this 

	'popup-options' => array(
	
		'padding' => array( // this is the parent array of the options under
			'paddingtab' => array(
				'title'   => __( 'Padding', 'fw' ),
				'type'    => 'tab',
				'options' => array(
					'padding-top' => array(
						'label' => false,
						'type'  => 'thzspinner',
						'addon' =>'px',
						'min'=>0,
						'value' => fw_akg('padding/padding-top', $option['value']),
						'attr'  => array(
							'class' => 'padding-top',

						),
						
					)
				),
			),
		),

so that my print comes out as 

http://prntscr.com/7b54au

instead of 

http://prntscr.com/7b54lh

**Comment by moldcraft** [comment]
Try [option-type `multi`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi)

**Comment by danyj** [comment]
argrgrhrhrhr!  GOD BLESS YOU!
and I'm looking for option array and trying to build it. Completely confused it with multi picker and multi select. Did not even look in it.

**Comment by danyj** [comment]
OK one more  please,  

this worked but I have a prob with the array build becasue of the get value from input 

if I  just return value here , in front I get 
http://prntscr.com/7bfefg


		if($option['popup']){
			
				if (empty($input_value) || !is_array($input_value)) {
					return $option['value'];
				}
		
				$inner_options = $this->get_popup_options('unknown', $option, array());
		
				$value = array();

				foreach (fw_extract_only_options($inner_options) as $inner_id => $inner_option) {
					$value[$inner_id] = fw()->backend->option_type($inner_option['type'])->get_value_from_input(
						$inner_option,
						isset($input_value[$inner_id]) ? $input_value[$inner_id] : null
					);

				}	

				
				return $value;		
			
		}



if I do this 


		return $value['thz-style-popup'];

in front I get correct array  with padding-top value 96  as set when saved

http://prntscr.com/7bfetl

but backend value is reset to default one 

http://prntscr.com/7bff1m

is there way to different array map for front and back ?

**Comment by moldcraft** [comment]
Try in `_render()` to `fw_print($data['value']);` to see if it's '96' or '235'

**Comment by danyj** [comment]
will do btt #615 is my problem , if that were container I would not have to do anything here anymore.

**Comment by danyj** [comment]
OK this is what I'm after , download this please 

https://www.dropbox.com/s/8391y8aq7d16jva/test-text-option.zip?dl=0  ( click cancel if popup opnes download should than start ) 

The twist is to make it output option value without a popup as parent array. 

it is a simple text option with an option to show it inside the popup  and it has 2 views 



			'test_text' =>	array(
				'type'  => 'test-text',
				'value' => 'Some value',
				'label' => __('Testext', 'fw'),
				'popup' => true,
			),




but in my view instead one textbox I have 12 options ,  I tried all possible ways I can think off , data-for-js , add popup than all options inside , like said anything that came in my mind. 4 days I cant get it to work and it is either listing the option under popup array or it does not work properly when saving.
