### ISSUE TITLE
Container types & `popup` container

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#615]
I asked in one of the comments before about this and was shut down fast . 
Please give it another look , I dont understand how you see popup option as a option and not as a container. This " option" does not do anything but puts our options inside a popup. 

It is a beautiful option but a horror to work with since it puts all options inside another array thus braking the  way we construct our arrays. If I can display a group of options inside a tab without loosing my array structure , I should be able to do same inside a popup or in future an accordion. 

I built my option that works flawlessly in any part of the admin and using it's array structure to print some css in front,  if I add it in a popup which I would love to, to eliminate the admin clutter and let user concentrate on this specific options set  , I have to reconstruct everything. 

All these should be containers and nothing else. 

	box
	group
	tab
	popup  // hoping for 
	accordion // hoping for 

You did this for builder options without thinking about it, section, columns options sets are inside a popup.
Please think about this.

**Comment by moldcraft** [comment]
I will try to allow containers to be created as option-types.
But I can't tell when, maybe in a week, maybe in a month, ...

**Comment by danyj** [comment]
ok , at least something.

**Comment by moldcraft** [comment]
A couple of days I was thinking (in background) what to do with custom containers that will be created by theme developers in Customizer. Now a `box` is converted to section and a `tab` is converted to panel. But what to do with custom container types?

Now this idea came to my mind: 

In Customizer, all containers will be automatically converted to:

* Panel - if container contains other containers
* Section - if container contains only options

That will change the current rules:

| Unyson | Customizer |
|---|---|
| `tab` | `panel` |
| `box` | `section` |

to

| Unyson | Customizer |
|---|---|
| `tab > option` | `section > control` |
| `box > option` | `section > control` |
| `tab > box > option` | `panel > section > control` |
| `tab > tab > option` | `panel > section > control` |
| `box > tab > option` | `panel > section > control` |
| `tab > tab > box > option` | `panel > ERROR` [info](http://wordpress.stackexchange.com/questions/160277/add-new-panel-inside-parent-panel-in-wp-customize) |

a generalized rule

| Unyson | Customizer |
|---|---|
| `container > option` | `section > control` |
| `container > container > option` | `panel > section > control` |

----

There are no other problems/consequences created by custom container types so I will start to create this feature/possibility.

**Comment by danyj** [comment]
so let say we have a popup container 

in admin we have 

    tab > tab > popup > options

in custimizer than 

    panel > section > popup > options 

right?

**Comment by moldcraft** [comment]
> popup container

if it's a container then it doesn't matter what type of container (the type is ignored), so your example

> tab > tab > popup > options

will match

| Unyson | Customizer |
|---|---|
| `container > container > container > option` | `panel > ERROR` [info](http://wordpress.stackexchange.com/questions/160277/add-new-panel-inside-parent-panel-in-wp-customize) |

**Comment by danyj** [comment]
so even this 


    panel > popup > options 


will not show the popup button but it will list the options, right ?

**Comment by moldcraft** [comment]
> in custimizer than
>
>    panel > section > popup > options 

also there is no popup element in Customizer. Or you mean to convert popup container to popup option? Then all the values will be grouped under an option value key, and this has no sense because the main reason for creating popup container is to not do that.

> https://github.com/ThemeFuse/Unyson/issues/615#issuecomment-112046056

Yes

**Comment by danyj** [comment]
the  point of posting this suggestion was to  have a popup container which  for me should be used as strait in replacement for option popup, but reading this seems like if we have a popup container , it will be useless in customizer since it will not be displayed.

**Comment by moldcraft** [comment]
I think this feature is finished.

* [The class](https://github.com/ThemeFuse/Unyson/blob/master/framework/core/extends/class-fw-container-type.php) that you have to extend in order to create a new container type. Registering a container type the same as registering an option type.
* [The action](https://github.com/ThemeFuse/Unyson/blob/a6cc2ea92fb235c8255663ac1f02162387558a1b/framework/includes/hooks.php#L33-L36) for registering container types.
* [Here](https://github.com/ThemeFuse/Unyson/tree/a6cc2ea92fb235c8255663ac1f02162387558a1b/framework/includes/container-types/popup) is the `popup` container.

```php
'test-popup' => array(
	'type' => 'popup',
	'options' => array(
		'test-option' => array('type' => 'text')
	),
),
```

**Comment by danyj** [comment]
excellent addon , im busy with designs at the moment and will test as soon as I get to it. does the popup container work as popup itself in customizer or is it displaying the options normally ?

**Comment by moldcraft** [comment]
It displays options normally (as I said above earlier).
