### ISSUE TITLE
Using the 'fw_init' to add dynamic styles from theme options doesn't seem to work

### ISSUE THREAD

**Issue by sunny04** [ThemeFuse/Unyson#616]
Hi,

I have created few options in the 'Theme Settings' that are suppose to change the css of the site, like Accent Color for example. And I have a css file enqueued in my functions.php in which I'd like to add some css code using the values from these options. Following is the code in which I try to do it using the 'fw_init' hook in functions.php:

    function _action_fw_equeue_theme_settigs() {
      $accent_color = fw_get_db_settings_option('accent_color');
      $custom_css .=
      'a { '.
          'color: '. $accent_color .';'.
      ' } ';
      wp_add_inline_style( 'theme-settings', $custom_css );
    }
    add_action('fw_init', '_action_fw_equeue_theme_settigs');

`theme-settings`, as you can imagine, is the handle of the css file that I have already enqueued using the `wp_enqueue_scripts` hook earlier in the functions.php file.

However, when I load any page of the site, I get the following error:

`Notice: wp_add_inline_style was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. Please see Debugging in WordPress for more information. (This message was added in version 3.3.) in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 3560`

Please let me know what I'm doing wrong. 
Thanks!

**Comment by moldcraft** [comment]
The error message says it all. The `fw_init` action is triggered very early. Use the `wp_enqueue_scripts` action with priority bigger than the one used to enqueue `theme-settings`.
