### ISSUE TITLE
In Progress

### ISSUE THREAD

**Issue by MoBadawy** [ThemeFuse/Unyson#617]
I want to know if this cards in trello cancelled?

https://trello.com/c/y9duY5Ud/55-theme-update-from-themeforest
https://trello.com/c/6EAny3WJ/54-content-demo-install-remote-server

**Comment by duongancol** [comment]
The same to me, and I'm really want Trello to come back.

**Comment by moldcraft** [comment]
![s](https://static.md/5cbf22a08a6970b4658b6d262f58e47d.png)

**Comment by duongancol** [comment]
RIP! :(

**Comment by danyj** [comment]
hahahah :+1:
