### ISSUE TITLE
Table columns

### ISSUE THREAD

**Issue by ziuzea87** [ThemeFuse/Unyson#620]
Is there a way to add more than 5 columns in the table with Visual Editor?

**Comment by llemurya** [comment]
Please see this [printscreen](http://static.md/85b53a1a40af6384d6e3905c32868b7a.png).

**Comment by moldcraft** [comment]
TODO: Add `wp_localize_script()` for that hardcoded value and apply filter on it.

**Comment by alvisir** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/2a7c10ba2f4d2650d7da42cf6a5b1c5aa11d16bc
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/e45a37344a7f97e8b5fbc76b7b9c6d401bb3690a

**Comment by alvisir** [comment]
In `functions.php` add this (ex: I want a maximum of 8 columns)

```php
add_filter( 'fw_ext_shortcodes_table_max_columns', 'fw_ext_shortodes_table_edit_max_cols'  );
function fw_ext_shortodes_table_edit_max_cols( $max ) {
	$max_cols = 8;
	return $max_cols;
}
```

**Comment by llemurya** [comment]
@alvisir thanks for contribution.
