### ISSUE TITLE
Theme update from themeforest

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#621]
OK , since our Trello board is gone , this was one of the tasks that many of us have waited for. 
Is this going to be realized ?

**Comment by alexluncashu** [comment]
For envato updates you can use this plugin for the moment:  https://github.com/envato/envato-wordpress-toolkit. Updates from own remote server we have done for our theme Exposure [http://themeforest.net/item/exposure-photography-wordpress-theme/10562504], but we plan to make one extension witch will update form different sources. For now we have other priorities, and you can use envato plugin or email us and we will send you extension for updates from you own server.

**Comment by Ataurr** [comment]
@alexluncashu  I am also looking same thing.  can you please send me to. here is my email hello@ataur.co

BTW i like to know why trello board gone ??

**Comment by danyj** [comment]
@alexluncashu  thnx for the info bud , I just wanted to keep this one alive since many of us have waited on it. will wait for our extension rather than using  third plugin.

**Comment by valeriuzdrobau** [comment]
Soon we will achieve such extension. But in the meantime please write a list of functions that it must fulfill.

**Comment by danyj** [comment]
@valeriuzdrobau  to be honest until now we have sold exclusively on youjoomla, this will be our first TF product so I dont even know the way TF construct products/sales/updates. someone that is already selling on TF might give us more info.

**Comment by duongancol** [comment]
The main functions are:
- validate purchase code
- add evanto APi account
- notify update
- update from themeforest or remote server

**Comment by Ataurr** [comment]
@duongancol  When it will be release ?? We are really excited with this extension 😇

**Comment by danyj** [comment]
@alexluncashu  bud , can I have this extension?  where to email ?

**Comment by moldcraft** [comment]
@danyj As I remember, you already have found the solution, a WP filter on google and implemented it in your theme, so this issue can be closed.

**Comment by andreiglingeanu** [comment]
Hi guys,

How do you test your ThemeForest API scripts without having an item that's approved and has purchases in there?

Maybe someone has some test account we can use in order to test this?
