### ISSUE TITLE
Create options to a custom post type in a plugin

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#623]
Hi,

I'm creating a plugin that creates a custom post type 'Websites'. I would like to include custom options already build in Unyson in this plugin so when i active the plugin, the custom options are at the custom post type Websites.

Is it possible to create them in the plugin file or do i need to create them in de theme?

**Comment by moldcraft** [comment]
Options files are loaded only from

```
{theme}/framework-customizations/theme/options/posts/{post-type}.php
```

but you can use [this filter](https://github.com/ThemeFuse/Unyson/blob/a686fe71c5e06f2003e12d08438a666af4af4537/framework/core/components/theme.php#L115).

**Comment by nickkuijpers** [comment]
Do you maybe have a example? Trying it but doesn't make sense yet :(

**Comment by moldcraft** [comment]
```php
/**
 * @internal
 */
function _filter_fw_ext_whatever_post_options($options, $post_type) {
    if ($post_type !== 'your-post-type') {
        return $options;
    }
    
    $variables = fw_get_variables_from_file(
        '/path/to/your/options.php', 
        array('options' => array())
    );
    
    return $variables['options'];
}
add_filter('fw_post_options', '_filter_fw_ext_whatever_post_options', 10, 2);
```

**Comment by nickkuijpers** [comment]
Thanks so much Moldcraft! Got any donation location?

**Comment by nickkuijpers** [comment]
It works :') :+1:

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/410#issuecomment-100496348

**Comment by nickkuijpers** [comment]
Haha okay :) Will do!

**Comment by nickkuijpers** [comment]
Hi,

You've send me a code for creating options in a plugin. I've made a little adjustment because the function you wrote replaces the currently existing options so i used array merge.

```
function _filter_fw_ext_whatever_post_options($options, $post_type) {
    if ($post_type !== 'niku_websites') {
        return $options;
    }

    $variables = fw_get_variables_from_file(
        dirname( __FILE__ ) . '/unysonoptions.php', 
        array('options' => array())
    );

    return array_merge( $options, $variables['options'] );
        
}
```

**Comment by SenikaIndo** [comment]
Gooddddd
