### ISSUE TITLE
Custom Post Type wont show up in Unyson -> Page Builder -> Settings 

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#624]
Hi!

How come my custom post type created in a plugin wont show up at activating custom post types for the page builder at Unyson -> Page Builder -> Settings ??

**Comment by moldcraft** [comment]
[settings options](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/5e5ef7cefc648f9f84f455563f7305c5af224287/settings-options.php#L13) -> [the function](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/5e5ef7cefc648f9f84f455563f7305c5af224287/helpers.php#L16)

**Comment by nickkuijpers** [comment]
Hmm, any change i can activate it for a public -> false post type?

I am building a multisite plugin that validates which URL is active by searching custom post type 'Websites' and retrieving the content by the 'website post' where domain = slug. So those 'Websites' dont need a page itself but do need the page builder.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/59e90aa2458229990e385f8c956a4c0a94e442bd

**Comment by moldcraft** [comment]
[This](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/59e90aa2458229990e385f8c956a4c0a94e442bd) solution is ok?

**Comment by nickkuijpers** [comment]
Awesome! Perfect mate!

**Comment by nickkuijpers** [comment]
Working!
