### ISSUE TITLE
Custom Post Type Archive view back-end filter custom options

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#625]
Hi,

Any possibility to create a function that can add the custom post types to the back-end archive view of a custom post type so the custom field is filterable and sortable?

**Comment by llemurya** [comment]
@nickkuijpers can you be more explicit , because I didn't understand clearly your question, and what kind of function you want to be implemented in Unyson. Thanks. I'am awaiting for your response.

**Comment by nickkuijpers** [comment]
When you create a custom post type in Wordpress, you have the possibility to create posts. All those posts are listed at the custom post page like wp-admin/edit.php or /edit.php?post_type=##CUSTOMPOSTTYPE## 

Now i would like to make headers above that table to filter the inserted posts with customs fields i've created with Unyson.

**Comment by llemurya** [comment]
@nickkuijpers I understand what you want, please give us wireframes how can you see this as a final concept.

**Comment by llemurya** [comment]
@nickkuijpers please answer.

**Comment by nickkuijpers** [comment]
Sorry, i've been away. Will do tonight!

**Comment by nickkuijpers** [comment]
Do you mean the following?

http://wordpress.stackexchange.com/questions/45436/add-filter-menu-to-admin-list-of-posts-of-custom-type-to-filter-posts-by-custo

**Comment by llemurya** [comment]
no I mean [wireframes](https://en.wikipedia.org/wiki/Website_wireframe), the whole concept how It will look as User Interface, what kind of options etc.

**Comment by nickkuijpers** [comment]
Hi,

Just like the default way WordPress does, see http://www.smashingmagazine.com/2013/12/05/modifying-admin-post-lists-in-wordpress/ we need to add a variabel to the built in option array with: "Sortable in overview". If this is enabled, the code in the link above will be added to the custom post type where the option is used for.

**Comment by llemurya** [comment]
Please look at this [printscreen](http://static.md/2e58a4ed1754ea5b5389732fc64a55e7.png). I am waiting for your response.

**Comment by nickkuijpers** [comment]
Sorry.. didn't know you meant that. I meant the most arrow in the right where u point to Uncategorized.

**Comment by llemurya** [comment]
How it will look, as a link or as a select , checkbox? Please make an printscreen How you see this implementation as  User Interface.

**Comment by nickkuijpers** [comment]
![schermafbeelding 2015-06-16 om 13 43 52](https://cloud.githubusercontent.com/assets/5340923/8182236/c285a3fa-142d-11e5-9a04-cd43896388d9.png)

Hi, here ya go! see THIS IS A CUSTOM FIELD that needs to be a built in option of Unyson

**Comment by llemurya** [comment]
@nickkuijpers what you want is an extra wrapper of the existing functional of the WordPress, this printscreen is a simple case with text, what we will do if in the metakey is an multi dimensional array, in that case we must make a render method that will call in the WordPress action.We try to be more close to WordPress API, I think this task you can resolve with the WordPress tools. However, we have an extension in development that will give us more feedback how to realize this concept in practice.

**Comment by nickkuijpers** [comment]
Ah awesome, i will try to do it in some time but i am currently very busy with some projects. If i get it ready i will send it.

Thanks for the service.

**Comment by nickkuijpers** [comment]
This is what i meant: https://github.com/upstatement/jigsaw
