### ISSUE TITLE
'type'  => 'wp-editor' & Page Builder?

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#626]
Hi,

Any change i can use the Page Builder on the wp-editor built in option?

![s](https://cloud.githubusercontent.com/assets/5340923/7940834/9e3b9b74-0953-11e5-9ef6-6863c814f0fc.png)

**Comment by GheorgheP** [comment]
Hi,

Do you want to use the page builder as option like wp-editor?
At the moment we have a bug on having multiple page-builders on page.

**Comment by nickkuijpers** [comment]
Yes indeed, that would be nice. What kind of bugs? Where is the issue list maybe i can help.

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson/issues/487

**Comment by nickkuijpers** [comment]
Thx!
