### ISSUE TITLE
addable-box full width

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#627]
Hi,

Can we remove the max-width on the fw-inner? Or can i change this somewhere? It would be nice to have this just 100%, the addable-box is now only half of the 'type'    => 'box', size.

```
.fw-backend-option-design-default > .fw-backend-option-input.width-type-fixed > .fw-inner, .fw-backend-option-design-customizer > .fw-backend-option-input.width-type-fixed > .fw-inner, .fw-backend-option-design-taxonomy > td > .fw-backend-option-input.width-type-fixed > .fw-inner, .fw-backend-option-fixed-width {
  width: 100%;
  /* max-width: 428px; */
}
```

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/options/create-option-type.html#option-width

`addable-box` has `fixed` width.

**Comment by nickkuijpers** [comment]
Hmm okay but aint it better to just make it 100% by default? Why is fixed choosen? Does this mean i have to remake the extension for addable-box?

**Comment by moldcraft** [comment]
It will be too wide 100%

Can you give me a screenshot, where you want it to make 100% ?

**Comment by nickkuijpers** [comment]
![schermafbeelding 2015-06-02 om 18 17 07](https://cloud.githubusercontent.com/assets/5340923/7940834/9e3b9b74-0953-11e5-9ef6-6863c814f0fc.png)
![schermafbeelding 2015-06-02 om 18 16 45](https://cloud.githubusercontent.com/assets/5340923/7940835/9e3cc03a-0953-11e5-8bea-bfa3f5670fc0.png)

**Comment by nickkuijpers** [comment]
Some other thing right away, when is the editor activated on Tekst (text) instead of Visual on page load?

**Comment by nickkuijpers** [comment]
Thanks!

**Comment by moldcraft** [comment]
We will create `addable-box-full` option-type later.

At the moment you can do add a special class to your option

```php
array(
    'type' => 'addable-box',
    'attr' => array('class' => 'something-unique'),
)
```

and make it 100% from css.

**Comment by nickkuijpers** [comment]
Perfect, thanks!
