### ISSUE TITLE
Storing Serialized Data in Database

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#629]
Hi,

Is there a reason why all custom fields are stored in a serialized array? Why dont we use the normalization? http://en.wikipedia.org/wiki/Database_normalization

Currently at a issue that i cant search for a string in the database, or alteast, it needs a workaround. 

Userstory: I have a custom post type which has a custom field 'Domain'. In a Query i am searching for a certain domainname in the post_meta and it wont work because its serialized. I now need to use a LIKE querie and need to revalidatie if its the right post i've found by unserlializing and checking the array.

http://stackoverflow.com/questions/11281130/how-to-search-string-stored-serialized

Editted: The problem is when a client of mine puts the same domainname in the content area of the page builder, the querie will also give me the return

Maybe there is a other way to go? I would like to search the post_meta and get the POST ID.

**Comment by moldcraft** [comment]
We store the options in a single post meta serialized for performance reasons.

You can copy your option in a separate meta by adding [this parameter](https://github.com/ThemeFuse/Unyson/blob/master/framework/core/components/backend.php#L824) in your option array.

**Comment by nickkuijpers** [comment]
You've really made it awesome :) Like really really.

**Comment by nickkuijpers** [comment]
Hey Moldcraft,

I see this function is @deprecated, is that correct? What is the solutions for saving custom fields as meta field?

**Comment by moldcraft** [comment]
Where you see that?

**Comment by nickkuijpers** [comment]
If you click the link you have send me, you see in the function description the notice About that.

Verstuurd vanaf mijn iPhone

**Comment by moldcraft** [comment]
That link is wrong now, it's an anchor but the code has been changed, and how it doesn't point to the right line.

[Here](https://github.com/ThemeFuse/Unyson/blob/a7c222be98c147b44e399d4f5eb02d646c050715/framework/core/components/backend.php#L937) is the right one (I also update the above one)

**Comment by nickkuijpers** [comment]
Ah i see!

Thanks alot!

Verstuurd vanaf mijn iPhone
