### ISSUE TITLE
Is addable option set possible?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#630]
Is there a way to add 2 addable options at once without having to use addable box ?

I have 4 options  

	text
	color
	---- here I need to add same set again , text + color at once 
	text
	color

**Comment by moldcraft** [comment]
Have you tried option type `multi` ?

**Comment by danyj** [comment]
hmm , u mean mixing multi and addable option . sec trying now

**Comment by danyj** [comment]
yap !  that works ,  
http://prntscr.com/7ce3sy
but sortable is in a way , please see my #631 

I can hide it but it kinda makes no sense being there if not needed

**Comment by Umeeshh** [comment]
Hi, danyj, would you share how did you make it to work the way from the screenshot?

regards
