### ISSUE TITLE
How to Get shortcode option value in theme file ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#632]
Hello.

I want to get the option value from shortcode in my theme file. i am using this.

echo $dataauto = fw_get_db_extension_data('shortcodes', $atts['data_autoplay'], $default_value = null);

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/511#issuecomment-98319183

**Comment by wpthemes786** [comment]
Is this not possible to do this ?

**Comment by moldcraft** [comment]
Nope

**Comment by wpthemes786** [comment]
Thanks @moldcraft
