### ISSUE TITLE
External plugin shortcodes being duplicated when edited with unyson active

### ISSUE THREAD

**Issue by riseoflex88** [ThemeFuse/Unyson#633]
Wordpress: 4.2.2 - Fresh WP Install
Unyson Version: 2.3.2 - Pagebuilder installed and active

I've spotted an issue with the default visual editor. 

If I use a plugin which places a shortcode which can then be edited again ([Forget About Shortcode Plugins](https://wordpress.org/plugins/forget-about-shortcode-buttons/) or the [WPViews API Demo Plugin](https://github.com/bainternet/bs3_panel_shortcode)) the shortcode is duplicated rather than replacing the original shortcode. 

I've got a few example gifs with each of the plugins mentioned above ([example 1](http://mmdev03.mmsite.co.uk/wp-content/uploads/2015/06/edit-button-shortcode.gif) & [example 2](http://mmdev03.mmsite.co.uk/wp-content/uploads/2015/06/edit-shortcode.gif)). When the edited shortcode is placed it doubles up (should be clear in the gifs). 

This only happens when unyson plugin is active (with the page builder installed), disable the plugin and the plugins work as expected.

**Comment by llemurya** [comment]
@riseoflex88 I reproduced it. Now I'am working on fixing it.

**Comment by riseoflex88** [comment]
@llemurya Bloody marvellous, thanks :+1:
