### ISSUE TITLE
How to get value from addable option in shortcode ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#634]

**Comment by moldcraft** [comment]
Shortcode options are available only in shortcode view as `$atts` array. 

Or your case is something else? Give more details

**Comment by wpthemes786** [comment]
I have simple addable option which is given in unyson documentation. An
addable option array and a text field in it.
All i want to know ho to get that text input field in shortcode view file.
I am using for each loop for this. For example.
foreach($atta['pricing_table_features'] as $features){
echo $features['what id pass here. '];
}

**Comment by moldcraft** [comment]
Make `fw_print($atts)` to see the array structure.

**Comment by wpthemes786** [comment]
array
(
    [0] => 'Web Design'
    [1] => 'Web Development'
    [2] => 'Photography'
    [3] => 'Email Marketing'
)

Thanks
