### ISSUE TITLE
fw_resize custom url

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#635]
Hi,

I would like to use fw_resize also on URLS instead of attachment ID's. I am now in need of https://gist.github.com/Pirenko/6734d0689b3629cd370f but it would be nice to remove the DRY :)

**Comment by valeriuzdrobau** [comment]
Hi, you can now use the URL of attachment instead if ID, or you want to use external URLs?

**Comment by nickkuijpers** [comment]
I would like to use URLS included in the theme map so those arent uploaded to the media bib.

**Comment by valeriuzdrobau** [comment]
I'm busy with another module, I will be introduce this possibility soon but you can contribute with a pull request if you have some free time.

**Comment by nickkuijpers** [comment]
Awesome, will do!
