### ISSUE TITLE
[question] Unyson translations

### ISSUE THREAD

**Issue by kinetikc** [ThemeFuse/Unyson#639]
Hi,

are there any language version of the plugin? If no - how can I create one?

**Comment by GheorgheP** [comment]
Hi,

At the moment we do not have any translations for the plugin.
You can use the [PoEdit](http://poedit.net/) to scan the theme of `_e()` and `__()` translatable strings, to generate the `.pot` file and also translate it.

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson/issues/346
