### ISSUE TITLE
hide the font size field in the typoghraphy

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#640]
Hi. Is there anyway to hide the font size field in the typoghraphy option because I always let user change font size base on section, not base on font-family. Thank you.

![screenshot_1](https://cloud.githubusercontent.com/assets/6775636/8001265/36dc1548-0b8e-11e5-90bd-f27918773d07.jpg)

**Comment by valeriuzdrobau** [comment]
Try to set `false`, the key `size` from [components](http://manual.unyson.io/en/latest/options/built-in-option-types.html#typography).

**Comment by giathinh910** [comment]
It worked. Thank you very much !!.
