### ISSUE TITLE
Lost value after import page content

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#641]
Anyone can support me to solve this issue ?
I exported a page by Exporter of WordPress, then using Importer plugin of WordPress to import that file. After that, I saw that some option type of shortcode can not get the data (like multi-picker).

Thanks

**Comment by valeriuzdrobau** [comment]
Send me please value for fw_options key, from table 'wp_postmeta',  of page with problem.(before export)

**Comment by maiakhoa** [comment]
Hi @valeriuzdrobau,

I'm sorry about this delay, I missed the notification email for this issue. 
Please get the file : https://dl.dropboxusercontent.com/u/44497652/fw_options.txt

Thanks

**Comment by valeriuzdrobau** [comment]
Sorry for the delay, test now with the latest versions of Unyson and Page Builder extension to see if the error still exists.

**Comment by valeriuzdrobau** [comment]
Due to inactivity I close this issue. Feel free to reopen it at any time.
