### ISSUE TITLE
Serious trouble with checkboxes  

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#642]
OK I dont know what you are doing to all options that are true or false but they dont work right either in popup or  outside 

	'type'  => 'checkbox',
	'text'  => __('Activate', 'fw' ),
	'value' => false,

in popup shows http://prntscr.com/7ddnb6

outside popup 
http://prntscr.com/7ddnh9

switch does same thing with another twist 

	'right-choice' => array(
		'value' => true,
		'label' => __( 'Activate', 'fw' )
	),
	'left-choice'  => array(
		'value' => false,
		'label' => __( 'No', 'fw' )
	),
	'value'        => false

when set to Yes which is true it shows  ON 

http://prntscr.com/7ddo2u

instead of true

**Comment by moldcraft** [comment]
I can't reproduce this. I added the below array to theme `settings.php` and everything works fine

```php
'test-outside' => array(
	'type'  => 'checkbox',
	'label' => __('Activate', 'fw' ),
	'value' => false,
),
'test-switch-outside' => array(
	'type'  => 'switch',
	'label' => __('Activate', 'fw' ),
	'right-choice' => array(
		'value' => true,
		'label' => __( 'Activate', 'fw' )
	),
	'left-choice'  => array(
		'value' => false,
		'label' => __( 'No', 'fw' )
	),
	'value'        => false
),
'test-popup' => array(
	'type' => 'popup',
	'label' => __('Test popup', 'fw'),
	'popup-options' => array(
		'test-in-popup' => array(
			'type'  => 'checkbox',
			'label' => __('Activate', 'fw' ),
			'value' => false,
		),
		'test-switch-in-popup' => array(
			'type'  => 'switch',
			'label' => __('Activate', 'fw' ),
			'right-choice' => array(
				'value' => true,
				'label' => __( 'Activate', 'fw' )
			),
			'left-choice'  => array(
				'value' => false,
				'label' => __( 'No', 'fw' )
			),
			'value'        => false
		),
	),
),
```

**Comment by danyj** [comment]
Sorry for the rant , i assumed that ,. looks like is coming from my popup,   data-for-js says false , json says false , print says false but visual is true.

**Comment by danyj** [comment]
ref #670
