### ISSUE TITLE
Theme setting tab icon

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#643]
Hello, 

Is it possible to add icons to theme setting tabs?

**Comment by moldcraft** [comment]
Hello,
It's not possible.

**Comment by pear1** [comment]
Then can I use Unyson extensions like page builder and others with Redux Framework theme options?

**Comment by moldcraft** [comment]
I haven't tested. I think you can.

**Comment by pear1** [comment]
Ok, last thing - is theme settings customizer compatible?

**Comment by moldcraft** [comment]
Theme Settings and Customizer are separated.
Usually a theme will have only Theme Settings or only Customizer settings.

* Theme Settings options are loaded from

    ```
    {theme}/framework-customizations/theme/options/settings.php
    ```

* [Customizer options](http://manual.unyson.io/en/latest/options/introduction.html#customizer) are loaded from

    ```
    {theme}/framework-customizations/theme/options/customizer.php
    ```

**Comment by pear1** [comment]
Thank you, but can I duplicate them, so one value would be shared in both places?

**Comment by moldcraft** [comment]
[Yes](https://github.com/ThemeFuse/Unyson/issues/410#issuecomment-101633999)

**Comment by pear1** [comment]
Thank you for your support.
Will try to stick with Unyson theme options.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/410#issuecomment-95681672

**Comment by pear1** [comment]
Yes, I know.
That was the main reason why I was asking for that kind of functionality.
