### ISSUE TITLE
Contact Form error isn't cleared when addressed

### ISSUE THREAD

**Issue by martin-bede** [ThemeFuse/Unyson#644]
When implementing a Contact Form and not filling a field in on the front end which is required, when you get the `This *Field Name* field is required` error, once the user fills the field the error still remains.

**Comment by moldcraft** [comment]
Is your form ajax submittable?

**Comment by martin-bede** [comment]
Yes using `fwForm.initAjaxSubmit`

**Comment by moldcraft** [comment]
I can't reproduce this.

* Open [this page](http://haintheme.com/demo/wp/culinier/contact/)
* Run [this script](https://raw.githubusercontent.com/ThemeFuse/Unyson/master/framework/static/js/fw-form-helpers.js) in browser console (copy/paste -> Enter)
* Run in console `fwForm.initAjaxSubmit({ajaxUrl: '../wp-admin/admin-ajax.php'});`
* Fill all contact form inputs with a space (to prevent browser required input warning) and press Submit

    All inputs will have errors.

* Fill some inputs with characters and press Submit.

    The errors will disappear.

----

P.S. See [this function](https://github.com/ThemeFuse/Unyson/blob/a2adef26229f5ad1ad015b0b74f657aa59f21235/framework/static/js/fw-form-helpers.js#L50-L52)

**Comment by martin-bede** [comment]
Thanks :+1:
