### ISSUE TITLE
All section that build with the page builder will be mixed together as one text box if we edit.

### ISSUE THREAD

**Issue by Energeticthemes** [ThemeFuse/Unyson#647]
Once we create a page and save it, there's no problem. But if we edit page that we create before, all section that build with the page builder will be mixed together as one text box. It will causes some error on that page.

**Comment by moldcraft** [comment]
* When this started to happen?
* This happens on any PC/Server or on a specific hosting?

**Comment by Energeticthemes** [comment]
I checked on 2 hosting and on PC its happen mostly when we update plugin or reactive Unyson plugin or some time when we go for edit page.

**Comment by moldcraft** [comment]
I can't reproduce this.

Please give the exact steps how to reproduce this (1. 2. 3. ...)

**Comment by greymavn** [comment]
+1 this. I have the exact same problem too. Wordpress hosted on Site5, happens to me just on the homepage. I could give you the raw text content that could not go back into Unyson page builder if you need it

**Comment by Energeticthemes** [comment]
Sorry moldcraft, well what is mean to  can't reproduce this?  
I am using Unyson plugin on a project and a lot clients asking to me about this issue.  How it can be resolved.

Thanks

**Comment by danyj** [comment]
@Energeticthemes   have your clients updated the Unyson plugin lately ? 
This bug was fixed long time ago ,  #161  ,  #484

**Comment by danyj** [comment]
@Energeticthemes  cant reproduce means that  he needs steps in order to see this bug , advise exact steps that he should take in order to see this as asked previously by moldcraft. simply saying it does not work is not how this can be fixed.

**Comment by llemurya** [comment]
@Energeticthemes @greymavn make an screencast with concrete todo steps in order to reproduce this bug and fix it.

**Comment by greymavn** [comment]
I've updated to the latest Unyson plugin. @llemurya  I can't reproduce it, it happens on the middle of my work randomly. Any way to change the default text syntax back to Page Builder? Mine is all now converted to default text and I haven't done anything to it. At least I'd like to make it back to page builder

**Comment by e-punkt** [comment]
Hi there, I'm a client of @Energeticthemes – and yes, I updated to Unyson 2.4.1 today, then saw the bug for the first time. When I open any one of my pages, everything I've built with Page Builder is shown as code in just one text block. When I tried to correct a typo in the code, the page fell apart in the frontend, code everywhere. Let me know how I can be of service to help resolve this @greymavn – thank you.

**Comment by danyj** [comment]
@Energeticthemes  @e-punkt  I think one of you should now go to 
Tools -> Backup  create demo install  and send it to @moldcraft  or @llemurya

**Comment by virtualgadjo** [comment]
hi,
i'have got exactly the same problem as epunkt in grand theme and it happens on two websites i've made with it, updated to the last release with no change...
i'm wondering if there is some thing i can do in my sql dump in text mode to fix it...
thanks for any advice

**Comment by moldcraft** [comment]
@virtualgadjo 

* PageBuilder extension is active?
* Have you tried to restore the page from Revisions?

**Comment by virtualgadjo** [comment]
@moldcraft 
thanks for your answer but, too bad, yes to both questions
unyson is active and i have the visual page builder button active, when i click on it i get a simple text block élément with exactly the same thing as what i have in the traditional editor

when it comes to the impacted pages i've tried to use a revision, didn't work

the weird thing is not all the pages are mixed up...

**Comment by moldcraft** [comment]
Which Unyson version did you have before update? Do you update regularly, or the last time you updated Unyson and Extensions is long time ago?

**Comment by moldcraft** [comment]
P.S. Sorry, I don't know hot recover those pages.

**Comment by virtualgadjo** [comment]
actually, i think i update the framework release after release so i'm constantly using the last one...
too bad for the pages but anyway, thanks for answering, i'll try to understand if i can see something logical in what doesn't work, unwanted html characters in shortcodes of things like that, who knows :)

**Comment by moldcraft** [comment]
Sure, if you'll find how to reproduce this, let us know.

**Comment by virtualgadjo** [comment]
i sure will :)

**Comment by chaley-warne** [comment]
I have been trying to replicated the fault/issue, On our test site we are running WP 4.3 and Unyson 2.4.7 with no problems at all. On the live site we have exactly the same setup but the Unyson extensions have been updated to the latest version (no idea what version they are running - how can you tell) and the error occurs.  Also interestingly if you try and restore the page with Safari it corrupts but if you restore on chrome the page can be restored.  Hope that help[s a little.  Is there anyway of copying the old Extensions to our live site to see if the fault clears?

**Comment by moldcraft** [comment]
> Unyson extensions have been updated to the latest version

They have been automatically updated or you pressed the "Update extensions" button?

> no idea what version they are running - how can you tell

https://github.com/ThemeFuse/Unyson/issues/728#issuecomment-122823967

> Is there anyway of copying the old Extensions

* If you just want to test if the extensions update causes this, open any extension `manifest.php` and decrease the version, then in dashboard should appear that you have new updates.
* If you want to test how the actual older version of the extension works
    
    * open any extension `manifest.php`
    * open: `https://github.com/` [`ThemeFuse/Unyson-NAME-Extension`](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/4ef780592cded57aad484a7476af564714fa052d/manifest.php#L29) `/releases`
    * choose any older release you want
    * download, extract the zip and replace the extension directory with the downloaded one

**Comment by chaley-warne** [comment]
Pressed the update extensions button within the Wp updates screen 

--

Chaley Warne
SocialWeb

Mobile: 0211 556 995
Web:     www.socialweb.co.nz

**Comment by chaley-warne** [comment]
Running the older version of the extensions made no difference. So now live and test are identical but we have the fault on live not test 


> On 18/09/2015, at 9:32 am, moldcraft <notifications@github.com> wrote:
> 
> Unyson extensions have been updated to the latest version
> 
> They have been automatically updated or you pressed the "Update extensions" button?
> 
> no idea what version they are running - how can you tell
> 
> #728 (comment) <https://github.com/ThemeFuse/Unyson/issues/728#issuecomment-122823967>
> Is there anyway of copying the old Extensions
> 
> If you just want to test if the extensions update causes this, open any extension manifest.php and decrease the version, then in dashboard should appear that you have new updates.
> If you want to test how the actual older version of the extension works
> 
> open any extension manifest.php
> open: https://github.com/ ThemeFuse/Unyson-NAME-Extension <https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/4ef780592cded57aad484a7476af564714fa052d/manifest.php#L29> /releases
> choose any older release you want
> download, extract the zip and replace the extension directory with the downloaded one
> —
> Reply to this email directly or view it on GitHub <https://github.com/ThemeFuse/Unyson/issues/647#issuecomment-141233718>.
> 

Chaley Warne
Technology Specialist

M: 0211 556 995
W: www.socialWEB.co.nz <http://www.socialweb.co.nz/>
 

 <http://www.socialweb.co.nz/>


CONFIDENTIALITY: This e-mail (including any attachments) may contain confidential, proprietary and privileged information, and unauthorised disclosure or use is prohibited.

If you receive this e-mail in error, please notify the sender and delete this e-mail from your system.




 <http://www.socialweb.co.nz/>

**Comment by moldcraft** [comment]
I just noticed a user clicking Update too fast, when the page builder elements are not initialized and having troubles with builder disabled after that https://youtu.be/6fYtUd6ImVU?t=3650

**Comment by moldcraft** [comment]
Please reopen if it happens again
