### ISSUE TITLE
Is fw.OptionsModal  removing option values that are empty arrays ? 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#648]
Let me understand this please , 
fw modal needs set of options and values to render options 
in your popup option example on FIRST load those are stored in data-for-js 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/popup/class-fw-option-type-popup.php#L52

on edit ( open popup first time, hit save  button in popup open again )  the options are than called from  the input value correct ? 

now my issue is that it seems like the edit is removing the index if it is an empty array , 
it is removing it completely from the options array . All other indexes that are not an empty array are ok. 

here option on first time open 

http://prntscr.com/7dx762  , that is an empty addable option not used yet 

I than hit save in popup and open it again the index is gone 

http://prntscr.com/7dx7q4

I look in input value the index is there http://prntscr.com/7dx7zi

I am using this exact script , 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/popup/static/js/popup.js

no changes and I tested with same option inside your popup. Same issue 

if option is not inside popup there are no issues and nothing is being removed.

**Comment by moldcraft** [comment]
I tried this in order to reproduce:

1. Added to `{theme}/framework-customizations/theme/options/settings.php`

    ```php
    'test_popup' => array(
    	'type' => 'popup',
    	'popup-options' => array(
    		'x' => array( 'type' => 'text', 'value' => 'Default' ),
    		'y' => array( 'type' => 'addable-option' ),
    	),
    ),
    ```

*. Added to `{theme}/header.php`

    ```php
    <?php fw_print(fw_get_db_settings_option('test_popup'));
    ```

*. Before Theme Settings save in frontend

    ```
    array
    (
        [x] => 'Default'
        [y] => array()
    )
    ```

*. After Theme Settings save in frontend

    ```
    array
    (
        [x] => 'Default'
        [y] => array()
    )
    ```

*. After changing/adding some values

    ```
    array
    (
        [x] => 'Custom'
        [y] => array
        (
            [0] => 'Hello'
            [1] => 'World'
            [2] => ''
        )
    )
    ```

Everything works fine.

----

The idea is: The value that is saved in the db matters, what tricks an option-type does in html doesn't matter.

----

If I understood you wrong. Please give more details about what you want to achieve, how you made those `fw_print()` from screenshots?

**Comment by danyj** [comment]
thnx for checking , this has nothing to do with frontend , this is all in backend , those prints are in view render
remember my background option you helped me with , this is it , I added  addable option types and having trouble with missing index and true/false options in general.

The trouble is only if I combine it with popup ,  I think I am having issue with _get_value_from_input 
now this all mixing combining is not default like you would use it inside settings.php

everything is inside view.php  and that is where trouble is,  il make an example option  and send it to you

**Comment by danyj** [comment]
I was able to remove all the clutter in order to show you the issue. This option calls another set of options ,  I sent an email   for includes with 2 option types and the option name  thz-box is the one 
that includes other options inside of a popup. 

    fw_print($data);

is inside class-fw-option-type-thz-box.php   line 96

 I dont need a rewrite of all options just the hint where the issue is which I assume is in   thz-box option  _get_value_from_input    when popup is on. Is either the json_decode or something that I am missing. 


Here is the video of the issue   and you can also see the ug I was telling you about with radio/switch options  or options that use true/false

http://screencast.com/t/4OkVVMc0a9




This is how to set it up inside the settings.php


		'test-bg-option' => array(
			'type' => 'thz-bg',
			'label' => __('Test box', 'fw'),
			'button-text' =>  __('Customize box', 'fw'),
			'popup' => false,
			'value' => array(
				'add-stop' => array(),
				'color' => '#ff0050',
			),

		),	
	
	
		'test-box-option' => array(
			'type' => 'thz-box',
			'label' => __('Test box', 'fw'),
			'button-text' =>  __('Customize box', 'fw'),
			'popup' => true,
			'value' => array(
				'boxshadow' => array(
					'active' => true,
				),
				'background' => array(
					'add-stop' => array(),
					'color' => '#ff6600',
				),
			),

		),

If you switch  the   thz-box option popup  to false you wont have any issues , 

Also if you automatically click on add button and save you wont have any issues. So the problem occurs only if you save the popup without previously click on add button.

**Comment by danyj** [comment]
@moldcraft  did you had time to look this over and did you get my email ? sent it 4 days ago

**Comment by danyj** [comment]
@moldcraft  disregard , got an email back looking over

**Comment by danyj** [comment]
Thnx for looking over that , reminder the fix you added for switch is also needed in checkbox and radio , any of them when using true/false fails the same way switch did. 

as for the options I am even more lost now since I cant use 
  
    get_inner_options

reason being is that all options need to be customized for html thus they were in view and that is where issues start.  That is also why I said that I dont need a rewrite. I am not placing them under each other but they are inside own containers + tabs . I slimmed it down for you to see the issue .
il look more closely and try to figure out the way to do this.

All in all , building and combining options is still a horror sorry to say. 
Everyone on your team has own way of coding them and developers get lost as to what is the right or wrong way. There is no clear guideline how to make an option and even if there is your team is not following it. Nothing against no one here but it is very confusing for us when we try to make complex options . When we start to compare  options that you have to each other , each is using different coding pattern. An the most confusing  of all is 

    _get_value_from_input

there are so many variations that I have seen in your options that my head spins. 
Don't take this small rant as me not being grateful for what you do , 
I AM very grateful  for everything you did , those are just hints as to what I think it could be improved.

**Comment by moldcraft** [comment]
> That is also why I said that I dont need a rewrite. I am not placing them under each other but they are inside own containers + tabs

Try in view

```php
<div>
    <div>
        <div><?php
        	echo fw()->backend->render_options(
        	    array('boxshadow' => $inner_options['boxshadow']), 
        	    $data['value'], 
        	    array(
            		'id_prefix' => $data['id_prefix'],
            		'name_prefix' => $data['name_prefix'],
            	)
        	);
        ?></div>
    </div>
    
    <div><?php
    	echo fw()->backend->render_options(
    	    array('background' => $inner_options['background']), 
    	    $data['value'], 
    	    array(
        		'id_prefix' => $data['id_prefix'],
        		'name_prefix' => $data['name_prefix'],
        	)
    	);
    ?></div>
</div>
```

> An the most confusing of all is `_get_value_from_input` there are so many variations that I have seen in your options that my head spins.

Maybe because it's flexible. The main idea is to return db value, that matches the same structure as `_get_defaults()['value']` and it doesn't matter how you extract/generate it.

At the moment I don't know a pattern/rule for how to write `_get_value_from_input`.

A recommendation, if you use other option types in your option, better to use the `fw_get_options_values_from_input()` function to get their values, instead of just returning raw `$input_value` without any (or poor) verification.

For example if you have many options in your view that are rendered in different html elements, try to generate in `_get_value_from_input()` a single array with all those options (to be the same as those in view) and just use `fw_get_options_values_from_input()` to extract their values, instead of parsing all those arrays manually and creating weird code.

**Comment by danyj** [comment]
+1000000 for  the snipp , now it makes more sense and I can juts line them out like that and get the benefits of  fw_get_options_values_from_input. I am sure that many of this makes less sense to you but once done you will get the idea.

**Comment by danyj** [comment]
sorry to bother bud , but your modifications are not saving the values at all for the options in popup. I was reading only without testing , but now I actually tested and values are not saved , they return default set values only. I know you you not 100% in the email. Just  advising.
