### ISSUE TITLE
Unyson seems to be messing up the WP_Query

### ISSUE THREAD

**Issue by sunny04** [ThemeFuse/Unyson#652]
While creating a theme, I came across this problem where the sticky posts were not showing at the top of the loop created using WP_Query in a custom page template. I asked [this question on StackExchange](http://wordpress.stackexchange.com/questions/190720/wp-query-doesnt-get-sticky-post-at-the-top-when-used-in-a-page-template?noredirect=1) and found that Unyson was causing this problem. 

After disabling Unyson, the sticky posts worked as expected.

The Accepted answer in that question suggests that it is because Unyson is creating custom filters which is messing up the WP_Query. 

I've tested this problem on my theme and also in the Scratch theme. And this problem occurs when I use a page created with the page template (that uses WP_Query) and set it to the Front page or even when I don't.

Please let me know about this.
Thanks.

**Comment by danyj** [comment]
do u have sidebars enabled?  what Unyson extension do u have on ?

**Comment by sunny04** [comment]
I had just the Page Builder extension enabled when I first noticed this problem. I deactivated the Page Builder extension without deactivating the plugin and the problem remained. 

It was only after I deactivated the plugin when it finally worked.

**Comment by danyj** [comment]
I just checked all unsyon extensions and plugin files and cant find but3 instances for is_home that are just checking if it is is_home or not http://prntscr.com/7em9h7  none that are messing with it, but it can be that there is instance of a WP_Query  that was not properly  unset after the loop

**Comment by sunny04** [comment]
I'm pretty sure that is the latter because even if the page with the WP_Query is not set as the 'Front page' or the 'Posts page' and just accessed as a normal page, then still you can see the problem of the sticky posts not appearing at the top (assuming is_home() returns false on a normal page).

**Comment by danyj** [comment]
those are instances of it , http://prntscr.com/7emi0v  and they are all inside extensions , none inside unyson , thus I asked if u have some extensions running, looks like team should try to find this one

**Comment by danyj** [comment]
I do see that some are using 

    wp_reset_postdata();

but I dont see 

    wp_reset_query()

  just giving hints

**Comment by danyj** [comment]
@sunny04  stupid question ,  what php version are you on ?

**Comment by sunny04** [comment]
@danyj It's actually a very good question as I haven't updated my Xampp in long time, which is what I'm devoloping on.

The Php version is 5.5.15

**Comment by danyj** [comment]
I asked because we ran in some namespace issues in form extension and php 5.2 so I thought those 2 could have same issue. I would explain step by step here on how to reproduce the issue and nudge @moldcraft  after you done.

**Comment by sunny04** [comment]
Just updated my Xampp installation to the latest version with Php 5.6.8, and the problem is the same.
You can reproduce the issue by creating a simple page template with the following code:

    <?php
    /*
      Template Name: Blog Default
    */
    get_header();

    $args = array(
      'post_type' => 'post',
      'posts_per_page' => -1,
      'ignore_sticky_posts' => 0
    );
    $custom_query = new WP_Query( $args ); ?>

    <ul class="posts">
      <?php
      if ($custom_query->have_posts()) : while($custom_query->have_posts()) : $custom_query->the_post();
        echo "<li>";
          the_title();
        echo "</li>";
        endwhile;
      endif;
      wp_reset_postdata();
      ?>
    </ul>

    <?php get_footer(); ?>

Now if you create a page using the 'Blog Default' page template and you have Unyson framework enabled (with or without any extensions), you will find that the sticky post doesn't appear at the top but at it's normal position according to it's published date, assuming you have few posts published after the sticky one.
However, if you disable Unyson Plugin and refresh the page then the sticky post will appear at the top as it should.

@moldcraft Please let me know it's just me that is having this issue.

Thank you.

**Comment by sunny04** [comment]
@danyj Thanks a lot for your help. However, can you please confirm me if you were able to reproduce this problem, I'm still not sure if it's just me that is having this issue.

Thanks again.

**Comment by danyj** [comment]
bud , I am user just like you and  helping where I can , @llemurya  @moldcraft  should take look at this.

**Comment by sunny04** [comment]
@danyj Right, I knew that you were just trying to help and I really do appreciate that. 
I was just not sure whether you, by any chance, reproduced the problem, not that you have to but I was just curious.

Anyway, thanks again and take care.

**Comment by danyj** [comment]
no bud , I did not test

**Comment by llemurya** [comment]
@sunny04 please read this [article](http://www.ciiycode.com/7imBSzWXWPXW/wordpress-global-post-changed-after-query) and say if it helps.

**Comment by duongancol** [comment]
Try my code: 
```
$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
$query = new wp_query('post_type=post&paged='.$paged);

<ul class="posts">
  <?php
  if ($query->have_posts()) : while($query->have_posts()) : $query->the_post();
    echo "<li>";
      the_title();
    echo "</li>";
    endwhile;
  endif;
  wp_reset_postdata();
  ?>
</ul>
```

**Comment by sunny04** [comment]
@llemurya @duongancol Thank you for your replies. 
However, I tried the solution in that article and also the code above but still the sticky posts are not showing up at the top of the list.

**Comment by llemurya** [comment]
@sunny04 First of all I want to know if you have created sticky posts? Because if the sticky posts don't exists, it is a normal behavior to show nothing. Please look at this [printscreen](http://static.md/8cef20ff66a58a638c0f58e446ff7088.png) and watch this [video](https://www.youtube.com/watch?v=mxNbW3ubtVY).If it will not help ,please make a description step by step how to reproduce this bug.I am waiting for your response.

**Comment by sunny04** [comment]
@llemurya I've made a video to show the exact steps of how I'm having this issue. In the video I've reproduced the issue with Theme Unit Data content, on the Twenty Fifteen theme and on my Xampp local host.

[Video on vid.me](https://vid.me/pplu)

Hope with this you can find out what I'm doing wrong or if this is indeed a bug.
Thank you very much.

**Comment by llemurya** [comment]
@sunny04 I reproduced this bug, it is from Unyson, soon we will fix it. Thanks for the video.
