### ISSUE TITLE
wp_ajax from option class does not work anymore

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#654]
I had an option that is using wp_ajax and this worked inside the option  class at the end 

	FW_Option_Type::register('FW_Option_Type_ThzContentLayout');
	
	add_action( 'wp_ajax_thz_action_get_ajax_posts',array( "FW_Option_Type_ThzContentLayout", 'thz_action_get_ajax_posts' ) );

since last update ( master , updated today ) it does not work 

the action is not loaded , 
if I move the action inside the  theme hooks.php  it works

**Comment by danyj** [comment]
anyone ?

**Comment by moldcraft** [comment]
When the above code is called/included?

**Comment by danyj** [comment]
at the end of  the class like you have it in multi-select 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/multi-select/class-fw-option-type-multi-select.php#L495

**Comment by moldcraft** [comment]
Do you know about [this](https://github.com/ThemeFuse/Unyson/blob/f6e2ce93f355c8b6909aa6380872f9c6d6031870/framework/includes/hooks.php#L15-L20) ?

**Comment by danyj** [comment]
no man did not , but  how did it work than?  worked for over 2 weeks

**Comment by danyj** [comment]
is that why you did     

    if ( ! class_exists( 'FW_Option_Type_Multi_Select' ) ):


in multi-select  ?


is that the only way to fire the action from  option ?

**Comment by moldcraft** [comment]
> no man did not , but how did it work than? worked for over 2 weeks

Maybe you had some code that requested option-types very early and that file was included then.

----

I did `if ( ! class_exists( '...' ) ):` because that file is included twice (to prevent fatal error class already defined).

**Comment by danyj** [comment]
ok , il reconstruct ,  but we should not been doing this , if we need to call the option from somewhere else in order for its ajax to work than what is the point of adding the ajax in the option at all.

**Comment by danyj** [comment]
where is default 

    FW_Option_Type


class ?

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/654#issuecomment-110291567

Just be in the same place. Yes, that ajax callback can be moved outside.

> https://github.com/ThemeFuse/Unyson/issues/654#issuecomment-110293419

https://github.com/ThemeFuse/Unyson/blob/master/framework/core/extends/class-fw-option-type.php

**Comment by danyj** [comment]
well that did not work for me since the FW_Option_Type is not there either 
if I add in hooks to require the option I get 

    Fatal error: Class 'FW_Option_Type' not found 

your hooks is initiating the classes before 
https://github.com/ThemeFuse/Unyson/blob/f6e2ce93f355c8b6909aa6380872f9c6d6031870/framework/includes/hooks.php#L13

**Comment by danyj** [comment]
ok , I moved it inside 

    add_action('fw_init'


function that I have for constants but I dont like this at all.  makes no sesne that we cant run actions from option class

**Comment by danyj** [comment]
ok found the issue now ,  


options are included on 

    add_action('fw_option_types_init', '_action_theme_include_custom_option_types');


if changed to 

    fw_init

it works

**Comment by danyj** [comment]
@moldcraft  please advise if you see an issue with this so that I can close this 


	function _action_theme_include_custom_option_types_have_ajax() {
		
		/*
		Options that have wp_ajax
		*/
		
		if (is_admin()) {
			require_once dirname(__FILE__) . '/option-types/thz-content-layout/class-fw-option-type-thz-content-layout.php';
		}
		
	}
	add_action('fw_option_types_init', '_action_theme_include_custom_option_types');
	add_action('fw_init', '_action_theme_include_custom_option_types_have_ajax');


first action load normal options without wp_ajax , second one loads on fw_init only the once that have wp_ajax

**Comment by moldcraft** [comment]
it's ok

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1949#issuecomment-243822407
