### ISSUE TITLE
Creating actions with Unyson

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#656]
Hi, 

What about a built in option to activate a action. I am currently writing a plugin based on Unyson but i am having issues with safely creating a action button that runs a function i've created.

Like the save button on the theme setting page, but then it has a other custom function.

Any ideas on this?

**Comment by llemurya** [comment]
You want an option type what will be an button and when you click on it , it will be call a custom function from php via ajax ?

**Comment by moldcraft** [comment]
We had such option https://github.com/ThemeFuse/Unyson/issues/399

**Comment by nickkuijpers** [comment]
That is awesome! Is it still in use?

**Comment by moldcraft** [comment]
Please read that issue. It had a vulnerability (any user was able to call any function from browser console) and we removed it.
We decided that it's better/safer to [create manually an ajax](https://codex.wordpress.org/Plugin_API/Action_Reference/wp_ajax_(action)) and call it from javascript.

For example use [option type `html`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#html):

```php
array(
    'type' => 'html',
    'html' => '<button onclick="my_ajax_function(); return false;">'. __('Call ajax', 'fw') .'</button>'
)
```
