### ISSUE TITLE
Font character sets

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#657]
Hello, 

I'm using your framework and I'm pretty happy with it.

As I'm migrating from Redux Framework I have few issues which I've found with Google fonts in typography option:
- Where does people will be able to set character to something like *Greek Extended* or *Latin Extended* for other languages than English? (maybe I just can't find them)
- How does those fonts get include in HTML front-end to load from Google servers (and how to load those specific characters)?

**Comment by valeriuzdrobau** [comment]
Hello, in next version,we will add a new option-type `typography-v2` that will be able to set character set(http://prntscr.com/7ey9rh). 
In front-end each themes developer will create its function to include them using the rules provided by Google. If it would include Unyson, one problem would be: these fonts usually should not be loaded on all pages, and many other problems. I think that the best solution is to let the developer to include them.

**Comment by pear1** [comment]
I just tested it and it works pretty well.
Only problem when I download latest version from github is the theme settings hangs on load and I can't get *typography-v2* value, because it returns all theme settings variables. Approximately when this feature will be ready?

**Comment by valeriuzdrobau** [comment]
Around two weeks. 
Do you want to take the value of the font family? If so, when the document is ready, you can take the value with $('.fw-option-typography-v2-option-family select[data-type="family"]')attr('data-value'), also, when selectize is initialized,  is [triggered ](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography-v2/static/js/scripts.js#L150)'selectizeLoaded' event.

**Comment by pear1** [comment]
Sorry, second issue was separated in the front-end using *fw_get_db_settings_option()* function.

**Comment by valeriuzdrobau** [comment]
Can I close this issue?

**Comment by pear1** [comment]
I am waiting for an answer about this last issue, when *fw_get_db_settings_option* function isn't working correctly which is very important. Is it clear why that kind of issue could appear or eventually this will be fixed?

My theme at this moment is half made, but I would love to continue development process with typography-v2 option.

**Comment by valeriuzdrobau** [comment]
I have tested and works fine, you can give me your code where you said option, and where extract value?

**Comment by pear1** [comment]
I'm not sure why, but now it's working (just updated everything).
Weird, anyway thank you for your time.

**Comment by farid-alfernass** [comment]
i'm still don't understand

**Comment by moldcraft** [comment]
We have created [`typography-v2`](http://manual.unyson.io/en/latest/options/built-in/typography-v2.html) and don't have any plans related to typography functionality (you can create your own option-type)
