### ISSUE TITLE
About Slider Extension in Unyson

### ISSUE THREAD

**Issue by koetsuji** [ThemeFuse/Unyson#658]
Hi, 

I contacted to theme maker of the Culinier Wordpress theme. They said the error I'm having is about the Unyson extension. This is the error I'm having: https://www.youtube.com/watch?v=wgp91_oJKqY

What may be the problem here? Thanks.

**Comment by duongancol** [comment]
hi @koetsuji : I did report this error to Unyson team, So you don't need to create one. After it's fixed, I'll be inform to you. https://github.com/ThemeFuse/Unyson/issues/650
