### ISSUE TITLE
Typography option style/weight echo?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#659]
It's very confusing that the typography options echoes `font-weight` and `font-style` together.

I mean, I cannot print the weight directly. For example I have `custom-styles.php`:
```
<?php
$heading_font = fw_ssd_get_option('heading-font');
?>

h1,
h2,
h3,
h4,
h5,
h6 {
  font-family: <?php echo $heading_font['family']; ?>;
  font-weight: <?php echo $heading_font['style'] ?>;
}
```

`fw_ssd_get_option()` is helper function:
```php
function fw_ssd_get_option($option_id, $default_value = null) {
    if ( function_exists( 'fw_get_db_settings_option' ) ) {
        return fw_get_db_settings_option($option_id, $default_value);
    }

    return $default_value;
}
```

The problem is that `$heading_font['style'] `returns sometimes the style (ex. Regular), sometimes the weight (ex. 700), and sometimes both (ex. 700talic).

So do I have to write my own regex function that takes the value and writes the corresponding css properties or is there already some helper function for this?

**Comment by valeriuzdrobau** [comment]
Unfortunately there is not a helper function, that will help in this regard. But I recommend you use the option `typography-v2` with wordpress customizer, this option will be available in the next version, when will publish a version to put and documentation for this [option](https://github.com/ThemeFuse/Unyson/commit/cf32bbc02a2536c0e55dd70d957fbbc6c85717fa).

**Comment by pe6o** [comment]
What you mean by saying that it has to be used with the wordpress customizer? Sorry I couldn't understand.

**Comment by valeriuzdrobau** [comment]
We've done another option for working with fonts, it is 'typography-2'. It is common option, use it where you want,in theme settings, posts options, even in wordpress customizer.

**Comment by pe6o** [comment]
That's nice!

If anyone stumbles on this thread, here is my helper function which echoes the `font-style` and `font-weight`:

```php
function fw_prefix_typography_css($field) {

	$output = '';

	if ( isset($field['style']) ) {
	
		$pattern = '/(\d+)|(regular|italic)/i';

		preg_match_all($pattern, $field['style'], $matches);

		foreach ($matches[0] as $value) {
			if ( $value == 'italic' || $value == 'regular' ) {
				$output .= 'font-style: ' . $value . ';';
				$output .= "\r\n";
			} else {
				$output .= 'font-weight: ' . $value . ';';
				$output .= "\r\n";
			}
		}

	}

	if ( isset($field['family']) ) {
		$output .= 'font-family: ' . $field['family'] . ';';
		$output .= "\r\n";
	}

	return $output;
	
}
```

**Comment by duongancol** [comment]
hi @valeriuzdrobau : why in typography-v2 I couldn't set default value for weight. For example, I set 'Raleway' font:
```php
                         'body_font'                      => array(
                                'label' => __( 'Body font', 'mauris' ),
                                'type'  => 'typography-v2',
                                'value' => array(
                                    'subset'         => false,
                                    'variation'      => false,
                                    'family'         => 'Raleway',
                                    'weight'         => '600',
                                    'size'           => 14,
                                    'color'          => '#000000'
                                ),
                                'components' => array(
                                    'letter-spacing' => false,
                                    'line-height' => false,
                                    'subset' => false,
                                    'style' => true,
                                    'weight' => true,
                                ),
                            ),
```
But the 'weight' showed 100 in default. You can see here: http://prntscr.com/7ipki8

**Comment by valeriuzdrobau** [comment]
Hi,you must use the following code:
```
                  'body_font' => array(
						'label'      => __('Body font', 'marius'),
						'type'       => 'typography-v2',
						'value'      => array(
							'subset'    => false,
							'variation' => 600,
							'family'    => 'Raleway',
							'size'      => 14,
							'color'     => '#000000'
						),
						'components' => array(
							'letter-spacing' => false,
							'line-height'    => false
						)
					)
```

Google fonts don't have `style` and `weight`, they have `subset` and `variation`.
The component list is as follows:
```
           'components' => array(
				'family'         => true,
				'size'           => true,
				'line-height'    => true,
				'letter-spacing' => true,
				'color'          => true
			)
```
`style`, `weight`, `subset` and `variation` are dependent on key `family`.

**Comment by duongancol** [comment]
@valeriuzdrobau : I did try with 'variation' but the 'weight' still couldn't set in default. Please check it.

**Comment by valeriuzdrobau** [comment]
Google fonts don't have style and weight, they have subset and variation. `Raleway` is a font from Google.

**Comment by valeriuzdrobau** [comment]
Work normally:

```
                   'body_font' => array(
						'label'      => __('Body font', 'marius'),
						'type'       => 'typography-v2',
						'value'      => array(
							'subset'    => false,
							'weight'    => 500,
							'family'    => 'Arial',
							'size'      => 14,
							'color'     => '#000000'
						),
						'components' => array(
							'letter-spacing' => false,
							'line-height'    => false
						)
					)
```
Try to pull the code that is now on github.

**Comment by duongancol** [comment]
@valeriuzdrobau try to use your code with 'Raleway' font, but the 'style' still is 100:
```php
'body_font' => array(
                        'label'      => __('Body font', 'marius'),
                        'type'       => 'typography-v2',
                        'value'      => array(
                            'subset'    => false,
                            'variation' => 600,
                            'family'    => 'Raleway',
                            'size'      => 14,
                            'color'     => '#000000'
                        ),
                        'components' => array(
                            'letter-spacing' => false,
                            'line-height'    => false
                        )
                    )
```
I also pulled the latest commit of Unyson and tested this code from Theme Setting . It didn't work.

**Comment by moldcraft** [comment]
The above array also doesn't work on my installation, [the `variation` is set to `100`](http://static.md/ead95809a36363d54497a211e613fb5e.png).

But after I set `'variation' => '600'` (note that 600 is a string) [it works](http://static.md/bb0168bad1bde623642247ccc949fc47.png).

@valeriuzdrobau I will not release [the new version](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/88) until this will be fixed. Actually now I am not sure if it is a bug or we just need to inform in documentation the users (also a comment in option type code) that the parameter must be a `string`, not an `int`.
