### ISSUE TITLE
how to disable the unyson menu from admin panel. 

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#661]
Hello.
Ni dont want to let user see that unyson menu in admin side. Because i want to sell on TF market. 
Need help. 
Thanks

**Comment by danyj** [comment]
@wpthemes786  why would you want to hide Unsyon from your customers? Your theme depends on it and showing that Unyson is behind it is a HUGE plus , not a loss.

**Comment by wpthemes786** [comment]
Thanks but i dont want let users to enable extensions. Like i am using only page builder right now i dont want to show other extension to users.
Thanks

**Comment by wpthemes786** [comment]
@danyj any luck

**Comment by duongancol** [comment]
I'm selling theme on TF too and it's not problem. You should not hide it. 
You can disable other extensions in framework-customization/theme/manifest.php
<php>
$manifest['supported_extensions'] = array(
	'page-builder' => array(),
}
</php>

**Comment by danyj** [comment]
use something like this than 

	$manifest['requirements'] = array(
		'wordpress' => array(
			'min_version' => '4.0'
		),
		'framework' => array(
			'min_version' => '1.0.0',
		),
		'extensions' => array(
			'page-builder' => array(),
			'slider' => array(),
			'breadcrumbs' => array(),
			'shortcodes' => array(),
			'megamenu' => array(),
			'portfolio' => array(),
		)
	);
	
	$manifest['supported_extensions'] = array(
		'page-builder' => array(),
		'slider' => array(),
		'breadcrumbs' => array(),
		'shortcodes' => array(),
		'megamenu' => array(),
		'portfolio' => array(),
	);

**Comment by wpthemes786** [comment]
And if i want to disable any extension i have to just false that extension
instead of array.

**Comment by wpthemes786** [comment]
@danyj  @duongancol 
I have 3 questions.
1. Can i change the framework customization folder name in my theme.
2. what is the preferred method to ship unyson with theme. i have to use tgm plugin to install unyson plugin when user activate the theme. or is there any method specific for TF. 
3. When user activate the theme the user move to the demo content installation method. Is user required to install unyson first and install backup extension first then he is able to auto install the demo content for his theme.

Thanks for your help for giving me suggestions.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/661#issuecomment-110639300

There is no possibility to set false. Extensions that are set as compatible, will be visible. Other extensions will be hidden under 'Show other extensions' button.

> https://github.com/ThemeFuse/Unyson/issues/661#issuecomment-110642125

1. https://github.com/ThemeFuse/Unyson/blob/40ae630a7bdf6317a1af53151d292f01447d95e2/framework/bootstrap-helpers.php#L29
2. tgm
3. Yes

**Comment by wpthemes786** [comment]
Thanks Guys Much Appreciated.

**Comment by wpthemes786** [comment]
Hello.
i have a question here, could i disable the show other extensions button on unyson page so user could not able to install other extensions which are not compatible with theme. so user did not confused that i install the slider extension and its did not render any where. because we did not allow compatibility of slider in theme,

How to resolve this scenario.
