### ISSUE TITLE
Page Builder suggestion.

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson#662]
Hi there,
It would be nice if you guys are going to add these features to current Visual Page Builder.
1. A button to temporary change the visibility state of element, making element be invisible/visible in front-end but still in Page Builder's area in back-end.
2. When we have a lot of elements built from the same shortcode, it's hard to find the right one to edit. Can we do something looks like <code>{template}</code> in <code>addable</code> options ?
Any helps would be appreciated. Thanks.
![screen shot 2015-06-10 at 10 31 39 am](https://cloud.githubusercontent.com/assets/3183635/8074414/776d0492-0f5c-11e5-85f6-7ab9a688ebac.png)

**Comment by duongancol** [comment]
yeah! vote it! :+1:

**Comment by danyj** [comment]
Id vote on second one for preview of the element in builder  but not on visibility , 
visibility in frontend should not be controlled by unyson at all. It should be done by developer design or an option that we add in item options.

**Comment by RayNguyen** [comment]
@danyj As you can see at my attachment in previous post, I have Section in Page Builder area, and I just want to test how the page looks in front-end with/without this Section. Could you please guide me what is the best way to do this ? Thanks !

**Comment by danyj** [comment]
ok it does make sense now , I thought you want to mess with css display, but what you want is , 

temporary disable the element in fronted , 

yes that makes sense , in that case when clicked on the eye the section/column/item should have opacity set to 0.5 or something to initialy indicate that it has been disabled , something like 


![oxwstiu](https://cloud.githubusercontent.com/assets/2340172/8076100/d3db3faa-0f48-11e5-9c95-8a745438e0cd.png)

**Comment by pear1** [comment]
I would also love to see these both features, which could make a huge improvement to Page Builder usability, especially in advanced shortcode structures.

**Comment by Ataurr** [comment]
:+1:

**Comment by pear1** [comment]
Are there any news about these features?

**Comment by moldcraft** [comment]
Sorry, nothing yet. I can't give any eta.

**Comment by moldcraft** [comment]
> When we have a lot of elements built from the same shortcode, it's hard to find the right one to edit. Can we do something looks like {template} in addable options ?

[Done](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/99)

**Comment by duongancol** [comment]
Hi @moldcraft : Can you add a Save button here: http://prntscr.com/7pr79g?
I think it's helpful with page builder that has a lot of shortcode. Currently, I have to scroll down , edit shortcode and scroll up to save changes.

**Comment by albertso** [comment]
1. Hadn't thought about that, being able to hide/show sections can be very useful in production.
2. The block preview was on my top rank of necessary features. Hurray for that!

I also have an extra suggestion for the Page Builder.

__Page Builder template content should be added at the end of existing content__ when loaded, not replace existing one. This way we can store, reuse and combine different template parts. Currently it's not possible to combine them, the whole content is replaced entirely with loaded template.

**Comment by NazarkinRoman** [comment]
+1 for title for sections. Sometimes it really hard to find right section in the list, titles will solve this :)

**Comment by moldcraft** [comment]
> @RayNguyen 
>
> 1. A button to temporary change the visibility state of element, making element be invisible/visible in front-end but still in Page Builder's area in back-end.
>
> As you can see at my attachment in previous post, I have Section in Page Builder area, and I just want to test how the page looks in front-end with/without this Section. Could you please guide me what is the best way to do this ? Thanks !

You can delete the section and press "Preview Changes"

![](http://static.md/44a69f2a2e72930e2882797f43b2adf1.png)

then Undo the delete.

![](http://static.md/4756e0ebd69ee4dd1b76bbd9553d6727.png)

**Comment by moldcraft** [comment]
Or you can add a simple switch option in section options "Visible: Yes/No"
and if it's not visible, display a special sign in section title

![](http://static.md/9989b5ff2042f5248f377461077dc054.png)

```php
'title_template' => '{{- title }}{{ if (!o.visible) { }} <span class="fa fa-eye-slash"></span>{{ } }}'
```

then of course use that option in section view to make it invisible in frontend.
