### ISSUE TITLE
Theme settings hangs in Opera, Chrome browsers

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#663]
Hello, 

When I open theme settings everything works for about 0.5-1 second and then whole tab hangs/freezes for about 3-4 seconds what is very annoying.

I just tested it in multiple Opera browser versions (stable, developer) without any extensions. Looks like in Chrome there are similar issue for me.

*I am using 5 tabs in the left side with about 30 options.*

**Comment by danyj** [comment]
@pear1  list the options please

**Comment by pear1** [comment]
Options:
- 3 upload *(with just label and desc)*
- 2 radio *(with just label, desc and few choices)*
- 4 switch *(with just label and desc)*
- 16 text *(with just label and desc)*
- 2 rgba-color-picker *(with just label and desc)*
- 6 typography

When I disabled tab with typography options then this issue disappeared.
```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$options = array(
	'styling' => array(
		'title'   => __( 'Styling', 'unyson' ),
		'type'    => 'tab',
		'options' => array(
			'styling-box' => array(
				'title'   => __( 'Styling', 'unyson' ),
				'type'    => 'box',
				'options' => array(

					/*'styling_h1' => array(
					    'type'  => 'typography-v2',
					    'value' => array(
					        'family' => 'Fira Sans',
					        'size'   => 32,
					        'style'  => '400',
					        'color'  => '#000000'
					    ),

					    'label' => __('H1', 'fw'),
					    'desc'  => __('Description', 'fw'),
					),*/

					'styling_h2' => array(
					    'type'  => 'typography',
					    'value' => array(
					        'family' => 'Fira Sans',
					        'size'   => 24,
					        'style'  => '400',
					        'color'  => '#000000'
					    ),
					   'components' => array(
					        'family' => true,
					        'size'   => true,
					        'color'  => true
					    ),
					    'label' => __('H2', 'fw'),
					    'desc'  => __('Description', 'fw'),
					),

					'styling_h3' => array(
					    'type'  => 'typography',
					    'value' => array(
					        'family' => 'Fira Sans',
					        'size'   => 18,
					        'style'  => '400',
					        'color'  => '#000000'
					    ),
					   'components' => array(
					        'family' => true,
					        'size'   => true,
					        'color'  => true
					    ),
					    'label' => __('H3', 'fw'),
					    'desc'  => __('Description', 'fw'),
					),

					'styling_h4' => array(
					    'type'  => 'typography',
					    'value' => array(
					        'family' => 'Fira Sans',
					        'size'   => 16,
					        'style'  => '400',
					        'color'  => '#000000'
					    ),
					   'components' => array(
					        'family' => true,
					        'size'   => true,
					        'color'  => true
					    ),
					    'label' => __('H4', 'fw'),
					    'desc'  => __('Description', 'fw'),
					),

					'styling_h5' => array(
					    'type'  => 'typography',
					    'value' => array(
					        'family' => 'Fira Sans',
					        'size'   => 14,
					        'style'  => '400',
					        'color'  => '#000000'
					    ),
					   'components' => array(
					        'family' => true,
					        'size'   => true,
					        'color'  => true
					    ),
					    'label' => __('H5', 'fw'),
					    'desc'  => __('Description', 'fw'),
					),

					'styling_h6' => array(
					    'type'  => 'typography',
					    'value' => array(
					        'family' => 'Fira Sans',
					        'size'   => 12,
					        'style'  => '400',
					        'color'  => '#000000'
					    ),
					   'components' => array(
					        'family' => true,
					        'size'   => true,
					        'color'  => true
					    ),
					    'label' => __('H6', 'fw'),
					    'desc'  => __('Description', 'fw'),
					),

					'styling_p' => array(
					    'type'  => 'typography',
					    'value' => array(
					        'family' => 'Fira Sans',
					        'size'   => 12,
					        'style'  => '400',
					        'color'  => '#000000'
					    ),
					   'components' => array(
					        'family' => true,
					        'size'   => true,
					        'color'  => true
					    ),
					    'label' => __('Paragraph', 'fw'),
					    'desc'  => __('Description', 'fw'),
					)

				)
			),
		)
	)
);
```

**Comment by danyj** [comment]
typography is what is killing your admin speed, https://github.com/ThemeFuse/Unyson/issues/333#issuecomment-77844857, 
it is preloading 600+ fonts and making selects out of it on page load. thus I was forced to make my own version ,  team is working on typography v2 but it has same issue 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography-v2/static/js/scripts.js#L5-L12

I proposed this 
https://github.com/Themezly/ThzTypo
https://jsfiddle.net/pxjzeh1o/embedded/result/

and made my option like that , it loads the font preview only once and is reusing it , 
but no one seems to be interested

**Comment by danyj** [comment]
this is what I made out of that script and it fly's
http://prntscr.com/7fbkto

**Comment by pear1** [comment]
If 6 typography options can leave that huge impact on loading performance, then with about 15 options *(for custom header, footer and other element styling)* theme settings wouldn't be usable at all.
 
Your demo looks pretty nice, but would be great what moderators think about this situation.

Interesting, but in Firefox browser even with 15 tabs there is no issue with loading theme settings.

**Comment by danyj** [comment]
@pear1 that was a reason behind #333 post , we were all trying to figure out what is killing the site speed and 1 was typo , 2 was color picker, i think that color pickers were fixed  but typo has an issue. 
i was stuck with the same problem you have now but kinda managed everything with custom options , making sure that the code does not load if there is no need for it. 

Next step was moving options inside popup which is HUGE performance increase , but popup option  has a downfall for me since it is adding options in additional array ( i think team is working on that ) #615

**Comment by pear1** [comment]
Thank you, at least the issue is now clear.

But why Firefox browser don't have this issue?

**Comment by danyj** [comment]
@pear1 I was just about to reply back , I now tested IE, Chrome , Opera , FF, Safari 

for me ,   it is double slower in  

IE
Opera
FF

Safary and Chrome load in 2.02sec , all other are 3.5, 4.2 sec, 
so for me is the other way around

**Comment by danyj** [comment]
I have all together about 73 options , 6 tabs,

**Comment by pear1** [comment]
I've just tested Redux Framework typography option with about 17 items and there was no issue to load them all with total about 70 options.
Interesting what they are doing differently, because they too have full dropdowns with all fonts loaded in every instance.

**Comment by pear1** [comment]
At this moment I managed to fix this issue for myself by removing some code from *typography-v2 scripts.js* file.
Now when using default HTML select dropdown there is not performance issue.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/663#issuecomment-110733143
> https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography-v2/static/js/scripts.js#L5-L12

I made [some improvements](https://github.com/ThemeFuse/Unyson/commit/b809532046c92fe630af9bf985d5e2548b666783) in [typography-v2 scripts](https://github.com/ThemeFuse/Unyson/blob/b809532046c92fe630af9bf985d5e2548b666783/framework/includes/option-types/typography-v2/static/js/scripts.js).

**Comment by pear1** [comment]
@moldcraft Awesome improvements for me and works much better.
Only the color picker inside typography-v2 isn't working anymore.

**Comment by valeriuzdrobau** [comment]
You can try now, I fixed the color-picker from typography-v2.

**Comment by pear1** [comment]
Thank you.
I can confirm that this issue is fixed.
