### ISSUE TITLE
Unyson plugin - always active

### ISSUE THREAD

**Issue by maryslen** [ThemeFuse/Unyson#664]
Hi, i am new in developing premium themes. Simple question: when i will put my 'unyson' theme on market the end user need to install unyson plugin with it and it always need to be active?

Thank you

**Comment by moldcraft** [comment]
Hello,

* The theme must work without framework. If you disable/delete the framework, the theme must not throw errors. So in the theme code, before calling a framework function or method, first you must check if it exists.

    ```php
    if (defined('FW')) { ... }
    ```

* The theme must work without any framework extension installed. So in the theme code, before calling an extension function or method, first you must check if it exists.

    ```php
    if (defined('FW') && fw_ext('breadcrumbs')) { fw_ext_breadcrumbs(); }
    ```

    or

    ```php
    if (function_exists('fw_ext_breadcrumbs')) { fw_ext_breadcrumbs(); }
    ```

So Unyson should be as a recommendation, not a requirement.

**Comment by wpthemes786** [comment]
What theme parts should work with out unyson. Like i have shortcodes built
using unyson. If its disabled its mean my theme broke. Like another example
i have portfolio or blog post and some settings are embed into blog and
portfolio templates, how could be disable unyson if theme totally depends
on unyson.
Thanks

**Comment by moldcraft** [comment]
The most important is to prevent fatal errors if unyson or some extensions are disabled. The parts that depends on unyson of course will not work.

**Comment by wpthemes786** [comment]
Thanks. Its mean u didnt get accepted on TF . if your theme didnt work if
unyson disabled or not installed., confusion here. Plz help or advice

**Comment by wpthemes786** [comment]
Also if i have some meta boxes and some theme settings on single.php file
and if i didnt install unyson. How could i avoid errors on this situation .

**Comment by moldcraft** [comment]
When an error can happen? When you call a function or a method that does not exist. So before calling it, first you need to [check if it exists](https://github.com/ThemeFuse/Unyson/issues/664#issuecomment-110782948). The idea is simple.

**Comment by wpthemes786** [comment]
How could i check if the meta box define with the help of unyson in single.php or any theme template file. Also could you please do a favor. I want to ask if i have a page which is home and totally developed by page builder using shortcodes. Should i create another home tempkate file in case user did not install unyson. Thanks for you kind help its my first theme on TF so i am worried that if i left any step in theme.
Thanks

**Comment by moldcraft** [comment]
> Also if i have some meta boxes and some theme settings on single.php file

> How could i check if the meta box define with the help of unyson in single.php or any theme template file

I don't understand, what metaboxes you have in theme templates?

> I want to ask if i have a page which is home and totally developed by page builder using shortcodes. Should i create another home tempkate file in case user did not install unyson.

I don't know the answer for this. Maybe an advanced theme developer can answer it.

Use [this function](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/helpers.php#L3-L9) to check if a page was made with page-builder (but again, first check if that function exists before calling it).

**Comment by duongancol** [comment]
@wpthemes786 Have you ever uploaded theme to TF?
