### ISSUE TITLE
This is not a FW_Form / Permission issues

### ISSUE THREAD

**Issue by adigital** [ThemeFuse/Unyson#666]
Hi,

For some reason i keep getting the error "This is not a FW_Form" in the console log when submitting a form.

 This happens when i add all required files/code to make it Ajax submittable. And when i try to make it without the Ajax files/code, i keep getting "You do not have sufficient permissions to access this page.".

So basically i'm not able to use the forms anywhere.

Here is the full code i'm using: https://gist.github.com/adigital/a5ec60b69d82d63b6d5c

And this is the custom class code used to get the options variables ($custom->addon->options()): https://gist.github.com/adigital/183c415119cdfb32ded8

Could you kindly help understand why submitting doesing work?

Thank in advance!

**Comment by moldcraft** [comment]
You forgot the `echo` https://gist.github.com/adigital/a5ec60b69d82d63b6d5c#file-gistfile1-php-L183

```php
selector: '<?php echo $this->form_selector; ?>',
```

**Comment by moldcraft** [comment]
> And when i try to make it without the Ajax files/code, i keep getting "You do not have sufficient permissions to access this page.".

https://github.com/WordPress/WordPress/blob/a676eda39594aa05390a12c00fe5341e151421d1/wp-admin/includes/menu.php#L329-L338

**Comment by adigital** [comment]
Amaaaziiiing, can't beleive that.. Let's blame it on late night coding :)

Thank you very much, so far you have the best Options Framework, hands down :+1: 

Take care!

**Comment by moldcraft** [comment]
Thank you :) Good luck with themes

**Comment by adigital** [comment]
Hmm, sorry to take away some time from you again, out of curiosity i just tried to reset the options form you just helped me fix, but it's not resetting.

The submit works now, but the reset just opens the modal, and that's it, the forms doesn't refresh and also the recent values saved remains.

Seems i might have missed something else?

I'm using the same code with updated 'echo', I would appreciate your further help.

Thank you again!

**Comment by moldcraft** [comment]
[Here](https://gist.github.com/adigital/a5ec60b69d82d63b6d5c#file-gistfile1-php-L129) you reset theme settings instead of [demo settings](https://gist.github.com/adigital/a5ec60b69d82d63b6d5c#file-gistfile1-php-L137).

> the form doesn't refresh

Inspect why it doesn't enter in [this if](https://gist.github.com/adigital/a5ec60b69d82d63b6d5c#file-gistfile1-php-L261)

**Comment by adigital** [comment]
Ok, refresh has been fixed, now the options refreshes on reset: https://gist.github.com/adigital/a5ec60b69d82d63b6d5c#file-gistfile1-php-L263

I have also corrected the options to reset: https://gist.github.com/adigital/a5ec60b69d82d63b6d5c#file-gistfile1-php-L129

But, the values still remains the recently saved options.. Hmm, any further idea?

Thank you

**Comment by moldcraft** [comment]
> But, the values still remains the recently saved options

Event after full page refresh?

**Comment by adigital** [comment]
Hmm, sorry i don't understand what you intend by Event after..

Do you intend if i see any event logged after i refresh the whole page? if so, nothing is logged.

Thank you

**Comment by moldcraft** [comment]
Sorry, typo Even (not Event) I updated the comment.

**Comment by adigital** [comment]
Oh Ok, gat you.. Yes even after refresh.

**Comment by moldcraft** [comment]
> I have also corrected the options to reset: https://gist.github.com/adigital/a5ec60b69d82d63b6d5c#file-gistfile1-php-L129

How? `FW_WP_Option::set( 'demo_settings_options', null, array());` ?

**Comment by adigital** [comment]
Ha, wonderful.. Now resetting. 

I can't thank you much.. Seriously, i really appreciate your time and help!

Keep up with the great work!

**Comment by moldcraft** [comment]
P.S. Please rename these actions: [1](https://gist.github.com/adigital/a5ec60b69d82d63b6d5c#file-gistfile1-php-L143), [2](https://gist.github.com/adigital/a5ec60b69d82d63b6d5c#file-gistfile1-php-L135).

**Comment by adigital** [comment]
Oh yes, Awesome.

Thank you very much again!

**Comment by adigital** [comment]
Hi,

Could you kindly let me know how to get values from my custom settings forms? such as this: https://gist.github.com/adigital/a5ec60b69d82d63b6d5c

In this case does 'fw_get_db_settings_option($id)' still applies?

Thank you

**Comment by moldcraft** [comment]
> In this case does 'fw_get_db_settings_option($id)' still applies?

No. You have to make your own function. Try to copy the fw_get_db_settings_option() function, rename it,  make it read db value from your wp option,  and load your options file in order to extract default values (whed db value is empty)

**Comment by adigital** [comment]
Wonderful.. Got it, it's working!! Love how you made everything customizable.. amazing!!

My other issue is, for some reason the post options is not loading to the admin post edit page.

There is no metabox loaded. Taxonomies, Customizer options are both been loaded. What do you think it could be?

Basically i'm using the whole framework except the Extensions part, i excluded it from my theme as i already have built in functions alike.

Does the post options has anything to do with the Extensions part?

Thank you

**Comment by moldcraft** [comment]
Nice :) Good Luck

> Basically i'm using the whole framework except the Extensions part

If you started to delete parts of the core and use only parts that you need, we don't provide support for that, it is all up to you, fork it and create your own framework.

> for some reason the post options is not loading to the admin post edit page.
> 
> There is no metabox loaded

Just creating `{theme}/framework-customizations/theme/options/{post-type}.php` and adding `box` options in it should display them on post edit page.

Can you provide your post options array (or a part of it) ? And we will test if it works on our side

**Comment by adigital** [comment]
I understand that, i had already built a framework with everything i already needed in, but i was blown away by your options types, especially Addable options, which can't be find anywhere, so i decided to swap my existing options and use yours, as it also works for Post Meta, Taxonomy meta, Customizer, i just couldn't go pass it.. Everything is working great except the Post Meta not loading.

Sure, here it is. It's basically your demo options just for testing purpose: https://gist.github.com/adigital/72718bf80ee5e725a595

Kindly let me know.

Thank you

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/options/introduction.html#restrictions

**Comment by adigital** [comment]
Ah, wonderful.. I never noticed those restrictions.. Everything is working now.

Classic.. Thank you!

**Comment by moldcraft** [comment]
In the next Unyson release, that restriction will disappear https://github.com/ThemeFuse/Unyson/commit/0dc794ae0396e9049fe0d7666b02bd966dba09b8

**Comment by adigital** [comment]
Ok, that's nice.. Thanks for letting me know..

I was thinking, how about an option type that basically lists all registered Post Types and Taxonomies? Something like the Multi-Select, but this should basically list the Registered objects, so one can list them and users can select Post Types or Taxonomies to exclude from example Sitemap etc.. 

Thank you

**Comment by adigital** [comment]
And also, i noticed you didn't include Export and Import capability of the options, i can build one with the help of json_encode and json_decode respectively, but i just wanted to make sure you don't have plans of including such function anytime soon?

Thanks again man!

**Comment by moldcraft** [comment]
> I was thinking, how about an option type that basically lists all registered Post Types and Taxonomies? 

I don't think it will be used frequently. So better to use a simple `checkboxes` option and generate the choices array with post types and taxonomies yourself.

Or use [`multi-select` with `'population' => 'array'`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi-select).

> but this should basically list the Registered objects, so one can list them and users can select Post Types or Taxonomies to exclude from example Sitemap etc..

Sitemap already has the "Exclude" functionality

[ ![s](http://static.md/9f8f9fcf8f6b592e07793e552c7f8879.png) ](http://static.md/9f8f9fcf8f6b592e07793e552c7f8879.png)

> And also, i noticed you didn't include Export and Import capability of the options, i can build one with the help of json_encode and json_decode respectively, but i just wanted to make sure you don't have plans of including such function anytime soon?

We don't have plans.

[Similar question](https://github.com/ThemeFuse/Unyson/issues/387)

P.S. All Theme Settings options are stored in a wp_option with [this name](https://github.com/ThemeFuse/Unyson/blob/46109fbf2ee41b6e661e7b17acd7876433ee8c84/framework/helpers/database.php#L18).

**Comment by adigital** [comment]
Hi, you have really helped me a lot, so i thought i would share this with you to contribute to your hard and amazing work: Your helper function fw_current_url(), on my multisite subdomain setup running on Nginx it doesn't work well, it actually just gets the main url domain instead of the subdomain, so i fixed it by adding a few lines: https://gist.github.com/adigital/0d056268a3c31d002e6d

Hope you find it useful!

Thanks man!

**Comment by moldcraft** [comment]
With the above fix doesn't work on my multisite with path based sites (not subdomain)

![s](https://static.md/0b909933c88b985965129640cc97b2fc.png)

**Comment by adigital** [comment]
Hmm.. I think i just solved it.. By simply letting the above fix fire on only subdomain installs: https://gist.github.com/adigital/0d056268a3c31d002e6d

Please test it again if you can as i don't have a path based install.

**Comment by moldcraft** [comment]
I added your [fix](https://github.com/ThemeFuse/Unyson/commit/9a9b245765c43a8a24179073c7c2f8c9a83288df), Thank you.

Please [test it](https://github.com/ThemeFuse/Unyson/blob/9a9b245765c43a8a24179073c7c2f8c9a83288df/framework/helpers/general.php#L1035-L1072).

**Comment by adigital** [comment]
Yes, it's working perfectly on my install too.

You are welcome, keep up with the good work!!

**Comment by adigital** [comment]
Hi, i've been struggling with this for a while and thought of sharing with you if you could kindly help with dynamic Select choices:

basically i want to fill the choices with looped items, here is the current code i'm using:
https://gist.github.com/adigital/9d5f872a238811ccda08

The select choices counts the number arrays correctly, but it doesn't output anything, when i look at the Source html, i see values are just numbers from 0:  

<span class="selecter-item selected" data-value="">Choose Site</span>
<span class="selecter-item" data-value="0"></span>
<span class="selecter-item" data-value="1"></span>
.......................

Note the data-value are numbers and the span is empty. But in reality it's suppose to be something like: 
<span class="selecter-item selected" data-value="">Choose Site</span>
<span class="selecter-item" data-value="U-111111-1">www.mysite.com</span>
<span class="selecter-item" data-value="912457">Site Name</span>
......................

Could you kindly help on Dynamically populating the Choices from a foreach loop?

Thank you

**Comment by moldcraft** [comment]
```php
$option_tracking_id['choices'][ $property['id'] ] = $property['name'];
```

**Comment by adigital** [comment]
Wonderful.. it works, Thanks!

**Comment by adigital** [comment]
Hi, im having problems saving the options which has the select dropdown populated with foreach loop '$option_tracking....', basically i have two select options, which are both populating perfectly with the solution you helped me with, but when i select an option from the dropdown and save, only the second dropdown option gets its selected choice saved, the first dropdown doesn't get saved, it remains the default empty value : array( '' => 'Choose Site' ).

Please look at the updated gist with the options and kindly let me know if could have an idea what it is, i find it hard to understand what it could be as they are both basically the same except for the data return. Maybe i'm missing something?

https://gist.github.com/adigital/9d5f872a238811ccda08

Thank you

**Comment by moldcraft** [comment]
Check if `$profiles` are not empty on POST save request.
I don't know where that variable comes from, maybe it is empty when the save happens.
