### ISSUE TITLE
Question about theme styling ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#668]
Hello.

i am facing some difficulties to get the job done, i have some styling options in option panel.
and i have a dynamic.php file in which i get those fields and apply like this:
<?php if(function_exists('fw_get_db_settings_option')) : ?>
    <?php
    $background = fw_get_db_settings_option('background');
    fw_print($background);
    ?>
<style>

    .fix-bg {background: url(<?php echo $background['url']; ?>) no-repeat;}

</style>
<?php endif; ?>

and i include this php file into my functions file. but nothing happened it just did not worked.
Any help what i did wrong here. i have value in my variable but its not printing,

And also my 2nd question is what is the best way to apply or override custom styling from option panel. is there any other way to do this which is accepted by theme forest.

Thanks Guys you are very helping people. 
I look forward to here from you soon.

Thanks

**Comment by valeriuzdrobau** [comment]
Hi, Try this:

```
add_action('wp_head', '_action_theme_print_some_css');

function _action_theme_print_some_css(){
	//your code
}
```

**Comment by wpthemes786** [comment]
No i have a file with css settings and that file did not work.

**Comment by valeriuzdrobau** [comment]
What do you mean, when you say that the file is not working? If it is loading, check what value returns this code:  code `if(function_exists('fw_get_db_settings_option')) `, this verification must be performed after actiuniunea `init`.

**Comment by wpthemes786** [comment]
add_action('wp_head', '_action_himalayan_print_css');

function _action_himalayan_print_css(){
    require_once (get_template_directory()  . '/inc/dynamic-styles.php');
}

Worked Thanks
