### ISSUE TITLE
Default for typography-v2

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#669]
Hello, 

How can I add a variable to typography-v2?
I need to add *Default* font option, therefore there would be no need to set up font for every item manually like h1,h2,h3,h4...

**Comment by moldcraft** [comment]
Try

```php
array(
    'type' => 'typography-v2',
    'value' => array(
        'family' => 'Arial',
        // here you can overwrite any of these keys http://bit.ly/1B6aaFp
    )
)
```

**Comment by pear1** [comment]
I try, but this doesn't work:
```
array(
    'type' => 'typography-v2',
    'value' => array(
        'family' => 'Default',
    )
)
```

**Comment by valeriuzdrobau** [comment]
Hi, I have tried with bellow code, all works fine.

```
'test-typography-v2'    => array(
	'type'  => 'typography-v2',
	'value' => array(
		'family' => 'Arimo',
		'subset' => 'greek',
		'variation' => 'italic',
		'size'      => 8,
		'line-height'   => 13,
		'letter-spacing' => -2,
		'color' => '#ff0000'
	)
)
```

Maybe you have inserted a font that is not listed. To expand the list of fonts you can use  `fw_option_type_typography_v2_standard_fonts` and `fw_googleapis_webfonts_url` filters.

**Comment by pear1** [comment]
Sorry, looks like I do not know how to describe my issue.
Yes, actual fonts works great, but I need either to add fake font with name "Default" or just blank option. Can I add fake font values through these filters? I tried this code below, but it didn't work for me.

```
function test_typography_v2_value($fonts) {
    $fonts['Default']  = array(
        'family'    => 'Default',
        'variants'  => array(),
    );
    return $fonts;
}
add_filter('fw_option_type_typography_v2_standard_fonts', 'test_typography_v2_value');
```

**Comment by valeriuzdrobau** [comment]
Try this:

```
function test_typography_v2_value($fonts) {

	array_unshift($fonts, 'Default');
	return $fonts;
}
add_filter('fw_option_type_typography_v2_standard_fonts', 'test_typography_v2_value');
```

**Comment by pear1** [comment]
It works now.
Is it possible to remove Style and Weight attributes and leave to blank for 'Default'?
