### ISSUE TITLE
checkbox and radio problems with boolean values

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#670]
When used by/inside other options and in `fw.OptionsModal`, boolean values in POST are sent as strings `'true'` and `'false'` and [this script](https://github.com/ThemeFuse/Unyson/blob/d6336058dbae09109daa53d9a913ff776600d132/framework/core/components/backend.php#L993-L1022) can't fix them because they are inside arrays and it doesn't know if they are used as booleans and to which option-types they belong.
So [this kind of fix](https://github.com/ThemeFuse/Unyson/blob/d6336058dbae09109daa53d9a913ff776600d132/framework/includes/option-types/switch/class-fw-option-type-switch.php#L77-L134) should be in `checkbox` and `radio`.

https://github.com/ThemeFuse/Unyson/issues/648#issuecomment-111431860

**Comment by moldcraft** [comment]
Note that you can't use booleans as array keys, [they are converted to int](http://3v4l.org/cK5II).
So it's impossible to have boolean [choices](http://manual.unyson.io/en/latest/options/built-in-option-types.html#checkboxes).

In choices seems to work fine, I tested with this options array

```php

'test-popup' => array(
	'type' => 'popup',
	'popup-options' => array(
		'test-multi' => array(
			'type' => 'multi',
			'label' => false,
			'inner-options' => array(
				'test-switch' => array(
					'type' => 'switch'
				),
				'test-checkboxes' => array(
					'type' => 'checkboxes',
					'choices' => array(
						'text' => 'Text',
						1 => '1',
						0 => '0',
					),
				),
				'test-radio' => array(
					'type' => 'radio',
					'choices' => array(
						'text' => 'Text',
						1 => '1',
						0 => '0',
					),
				),
			),
		),
	),
),
```

**Comment by danyj** [comment]
@moldcraft   thnx,  there should be a note about it than, i must convert bunch of options now .

**Comment by moldcraft** [comment]
I didn't knew about that transformation. I will add comments in docs and code.

**Comment by danyj** [comment]
nice find either way , was causing a lot of trouble , 

0 for false and 1 for true should behave same way here than 

    if($option_value){ //  do something if  option value is 1  aka: true

correct ?

**Comment by moldcraft** [comment]
> should behave same way **here**

where?

**Comment by danyj** [comment]
anywhere where I was using    


    if($option_value){   //  do something  if true


so that I dont have to do 


    if($option_value == 1){

**Comment by danyj** [comment]
wait a sec , we are mixing things up here ,   the true/false were not used as array keys , they were used as  option values

**Comment by danyj** [comment]
echo fw()->backend->option_type( 'switch' )->render(
	'active',
	array(
		'type'  => 'switch',
		'label' => __('Activate', 'fw' ),
		'right-choice' => array(
			'value' => true,
			'label' => __( 'Activate', 'fw' )
		),
		'left-choice'  => array(
			'value' => false,
			'label' => __( 'No', 'fw' )
		),
		'value'  => fw_akg('boxshadow/active', $option['value']),
		'attr'   => array(
			'class' => 'boxshadow-active'
		),
	),
	array(
		'value' => fw_akg('boxshadow/active', $data['value']),
		'id_prefix' => $option['attr']['id'] .'-boxshadow-',
		'name_prefix' => $option['attr']['name'] . '[boxshadow]',
	)

**Comment by danyj** [comment]
and this 


	array(
		'type'  => 'checkbox',
		'value' => true, // checked/unchecked
		'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
		'label' => __('Label', 'fw'),
		'desc'  => __('Description', 'fw'),
		'help'  => __('Help tip', 'fw'),
		'text'  => __('Yes', 'fw'),
	)

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/670#issuecomment-111554727

At the moment radio value is not strict checked with `===` but with `==` ([code](https://github.com/ThemeFuse/Unyson/blob/875f5177d072c484778dd3ef84221635e91cb949/framework/includes/option-types/simple.php#L605)). Also the value is forced to string ([code](https://github.com/ThemeFuse/Unyson/blob/875f5177d072c484778dd3ef84221635e91cb949/framework/includes/option-types/simple.php#L637)).
I will try to make it work with int.

> https://github.com/ThemeFuse/Unyson/issues/670#issuecomment-111555891

I fixed the `switch`. It still doesn't work with booleans?

> https://github.com/ThemeFuse/Unyson/issues/670#issuecomment-111556530

I [fixed](https://github.com/ThemeFuse/Unyson/commit/b6a5839e452db55e165ae4a6d54b91eb1620049d) `checkbox`

**Comment by danyj** [comment]
@moldcraft 

here test this one , checkbox does not work right,   open popup ,  uncheck checkbox , save poppup , open again it is checked


switch is fixed   today , radios seems ok 


	'test-popup' => array(
		'type' => 'popup',
		'popup-options' => array(
			'test-multi' => array(
				'type' => 'multi',
				'label' => false,
				'inner-options' => array(
					'test-switch' => array(
						'value'=> true,
						'type'  => 'switch',
						'label' => __('Activate', 'fw' ),
						'right-choice' => array(
							'value' => true,
							'label' => __( 'Activate', 'fw' )
						),
						'left-choice'  => array(
							'value' => false,
							'label' => __( 'No', 'fw' )
						),
						'value'  => true,
					),
					'test-checkboxes' => array(
						'type'  => 'checkbox',
						'value' => true,
						'label' => __('Label', 'fw'),
						'text'  => __('Yes', 'fw'),
					),
					'test-radio' => array(
						'type' => 'radio',
						'value'=> 'active',
						'choices' => array(
							'text' => 'Text',
							'active' => true,
							'inactive' => false,
						),
					),
				),
			),
		),
	),

**Comment by moldcraft** [comment]
> ```
> 'test-radio' => array(
>     'type' => 'radio',
>     'value'=> 'active',
>     'choices' => array(
>         'text' => 'Text',
>         'active' => true,
>         'inactive' => false,
>     ),
> ),
> ```

`choices` is 

```php
value => 'Label'
```

not

```
'label' => value
```

**Comment by danyj** [comment]
just saw that ,   never the less the checkbox is the one that is bugging

**Comment by moldcraft** [comment]
Read https://github.com/ThemeFuse/Unyson/issues/670#issuecomment-111559737 I fixed checkbox

**Comment by danyj** [comment]
ok ok ,  downloading

**Comment by danyj** [comment]
works , thnx !

**Comment by moldcraft** [comment]
I can't make `radio` to detect if key is int or string (`1` or `'1'`) [here's why](http://3v4l.org/7LMiU) so I will leave it unchanged (it will force values to string) https://github.com/ThemeFuse/Unyson/issues/670#issuecomment-111559737

**Comment by danyj** [comment]
ok , il stay away from boolean  in there

**Comment by danyj** [comment]
@moldcraft  Heads up ,  the info about boolean values is not in the docs 
http://manual.unyson.io/en/latest/options/built-in-option-types.html#checkboxes
and docs still say to use true or false , 

now another dev has issue with checkboX  ( single ) 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/issues/31
