### ISSUE TITLE
is there any heading option type in unyson ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#671]

**Comment by moldcraft** [comment]
more details please

**Comment by wpthemes786** [comment]
@moldcraft  i want to add a section heading like separator which differentiate the different sections with their settings.

**Comment by moldcraft** [comment]
Have you tried boxes?

```php
'box_1' => array(
    'type' => 'box',
    'options' => array(
        'option_1' => array('type' => 'text'),
        'option_2' => array('type' => 'text'),
    ),
),
'box_2' => array(
    'type' => 'box',
    'options' => array(
        'option_3' => array('type' => 'text'),
    ),
),
```

**Comment by wpthemes786** [comment]
Can you give more completed example. like i have to make page meta boxes with different sections.

**Comment by wpthemes786** [comment]
@moldcraft  Thanks i figured it out. :)

**Comment by moldcraft** [comment]
You can use any combination of `tab` and `box`, even nested.

**Comment by wpthemes786** [comment]
Sorry i forget to ask one question? could i use two types of context levels in meta boxes like one i would like side and one is advanced

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/options/introduction.html#box-parameters-in-post-options

**Comment by wpthemes786** [comment]
hmm its supports on first array level. have u planned in future ?

**Comment by moldcraft** [comment]
sorry, what?

**Comment by wpthemes786** [comment]
sorry nothing just mixed things in my mind. thanks its worked

**Comment by wpthemes786** [comment]
is there any option that the metaboxes default behavior is closed not open

**Comment by moldcraft** [comment]
[Yes](https://github.com/ThemeFuse/Unyson/issues/466#issuecomment-93797869)

**Comment by moldcraft** [comment]
At the moment first boxes are open, and the reset are closed.

**Comment by moldcraft** [comment]
At the moment first boxes are open, and the reset are closed. And if you wan a box to not be closed automatically, you can use [this solution](https://github.com/ThemeFuse/Unyson/issues/466#issuecomment-93797869).

Why do you want all to be closed?

**Comment by wpthemes786** [comment]
no you just cleared me now actually i just put one box thats why i thought thanks.
