### ISSUE TITLE
getting the page option values issue

### ISSUE THREAD

**Issue by c0sm1n87** [ThemeFuse/Unyson#674]
So, I added a type text option for pages, it renders in the backend , I add some text to it and save the page.

In the frontend I'm trying to get the value using some snippet found here:

 $page_options = fw()->theme->get_post_options('page');
 $box = $page_options['main'];
 fw_print($box, true);

and I can see the array with the option I just added, however it has no value.. i must be doing smth wrong but can't figure out where.

I found this post as well:
https://github.com/ThemeFuse/Unyson/issues/143

but I can't seem to figure it out.

**Comment by danyj** [comment]
use this 

    fw_get_db_post_option(get_the_ID(),'option_name');

**Comment by c0sm1n87** [comment]
ur awesome, thanks :) :+1:
