### ISSUE TITLE
[rant] Are you aware of Unyson advantage?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#675]
Just a small rant. I am excited to have figure it out that I have to share this. 

We know that Unyson is better because we have all in one , theme options , page builder etc  but we all still kinda looking "over"  at redux + visual composer.

Now here is an icing to Unyson cake,  

Visual composer is useless in custom themes because the frontend visual part of the composer works only with composer native elements , so all the themes that you see on TF that come out with ONE line of custom code for VC , have to turn off the frontend editor since it does not work. 

So the bellowed VC becomes nothing else than an ugly backend page builder which we here know  cannot compare  to the Unsyon page builder style by a looooong mile.   

Here is the note from X theme about it 
http://prntscr.com/7gsmbe

I have purchased few others and just could not find the fronted button for VC.  

1 thing we lack is few more seconds of speed ,  VC popup is faster than ours options popups , other than that THANK YOU  UNYSON!

**Comment by c0sm1n87** [comment]
Yeah guys, awesome work!

**Comment by RayNguyen** [comment]
Agree with you @danyj (y) !
In my opinion, I don't like to packed VC in my themes because itself has a lot of options that ruining user experience. Things I love most in Unyson framework:
1. Directory structure.
2. Built-in Slider.
3. And yes, Page Builder.
These save me tons of time. Many thanks to you guys behind Unyson for your aaawesome work !!

**Comment by DimiBaitanciuc** [comment]
Thanks a lot guys, it means a lot to us.

**Comment by moldcraft** [comment]
> 1 thing we lack is few more seconds of speed , VC popup is faster than ours options popups

I made [a little improvement](https://github.com/ThemeFuse/Unyson/commit/a6521e192c36891be495b135b5d488a704a83a37) for this.

Now on `fw.OptionsModal` open the following happens

```
if ( isset( htmlCache[ md5( modal.options + modal.values ) ] ) ) {
    // display html from cache
} else {
    // make an ajax request to get the html and save it in cache
    // so on second (and later) modal open there will be no ajax request
    // unless a value will be changed
}
```

**Comment by danyj** [comment]
@moldcraft  I was just reading about it :)   nice , a cache for modal options + 1000000

**Comment by danyj** [comment]
I am just now dedicating a section for Unsyon on our new theme landing page :)

**Comment by pe6o** [comment]
And one big thank you guys from me. Great framework and superb support!

As I'm going to release a theme soon, is there somewhere a button to buy you a few beers? =)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/410#issuecomment-100496348

**Comment by pe6o** [comment]
Alright, so be it then. Keep up the awesome work!

**Comment by moldcraft** [comment]
Hey there,

Those who enjoy using Unyson, please feel free to share and tweet [this article](http://themefuse.com/infographic-unyson-the-best-wordpress-framework-for-developers/). 
Each of your contributions counts. 
Help us build a larger community and improve our amazing framework together!

**Comment by pe6o** [comment]
Done!

**Comment by moldcraft** [comment]
@pe6o Thank you!

**Comment by kaxigt** [comment]
Tweeyed and Done!
But i wonder where the styling ability are because i can't find it when installed. I'm using latest version of WP. Tip?

**Comment by moldcraft** [comment]
@kaxigt Styling is gone https://github.com/ThemeFuse/Unyson/issues/874
