### ISSUE TITLE
Conditional options

### ISSUE THREAD

**Issue by c0sm1n87** [ThemeFuse/Unyson#676]
Hello, 

Bare with me i am writing this from my phone. I would like to ask you guys if I could create the page/theme option fields by adding another nested array in the fields as per this example

$options = {
.....
Type= 'text,
Conditional ={
  By = dependancy,
Condition = value is something
  }
}
Basically, i want to create a switch and if it's toggled yes, display a certain field. The js would be a walk in the park and i could hardcode it somehow but i would prefer an expert's opinion on this. 

Usecase scenario:

Create a group for custom header with a toggle to allow selection of a certain slider or a normal header. although it can be done at the current moment, it would provide a more intuitive interface for the customer.

Most of the time when we develop smth, we get the impression that others would understand our thought process which, most of the time, is wrong.

**Comment by llemurya** [comment]
@c0sm1n87 please read [this](http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi-picker). Hope this can help you.

**Comment by c0sm1n87** [comment]
Hello,

Yes it's exactly what I need. Should have looked thoroughly before posting this :)
