### ISSUE TITLE
Metaboxes and custom templates

### ISSUE THREAD

**Issue by c0sm1n87** [ThemeFuse/Unyson#678]
Hello,

Related to this issue: https://github.com/ThemeFuse/Unyson/issues/584

Although it's clearly stated that it's not supported, can you provide a little direction on how I could implement this scenario?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/573 I will add this feature later (right now I am busy with [other issue](https://github.com/ThemeFuse/Unyson/issues/615))

> can you provide a little direction on how I could implement this scenario?

I didn't investigated this so I am not sure yet how to implement it.

**Comment by c0sm1n87** [comment]
Hello @moldcraft,

I found an easy solution that can be used to render metaboxes for different page templates.

First I created the default layout for the Homepage here - 

page-templates\homepage.php:

and in here the options for Homepage (filenames must match):

framework-customizations\theme\options\homepage.php

I went to this file: 

\framework-customizations\theme\options\posts\page.php

and grabbed the template's name (new to wp functions, but I trimmed the result as per my need):

global $post;
list($template, $ext) = explode('.', basename(get_post_meta( $post->ID, '_wp_page_template', true )));

I added a new array under 'main' like this:

'template' => array(
	'title'   => false,
	'type'    => 'box',
	'options' => array(
		fw()->theme->get_options( $template ),
	),
)

and as far as I can see, it's working (this is a "draft", eventually 'template' array will be added based on some conditions).

Do you think this method of grabbing options would result in errors (as far as I can see, if it does not have a correspondent option page it just returns an empty metabox)?

**Comment by moldcraft** [comment]
What will happen when the user will change the template in select on edit post page?

----

As I said, I am busy with other issue and don't have time to investigate this to give you a solution.

**Comment by c0sm1n87** [comment]
Nothing will happen, when the template is changed, the new custom meta boxes are loaded. 

PS: I appreciate that you are busy doing some other cool stuff for this framework, I posted this hoping I might get some feedback from the community as well, you don't have to rub it in my face that you're busy :+1: 

cheers
