### ISSUE TITLE
How to design backend option panel and page builder ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#679]

**Comment by moldcraft** [comment]
Give more details please. I don't understand what you mean.

**Comment by wpthemes786** [comment]
Actually i have created the option panel and use page builder for my theme. i want to know is it necessary to design option panel or page builder for themeforest. or we can use default look on themeforest.

**Comment by valeriuzdrobau** [comment]
You can use default look on themeforest.
