### ISSUE TITLE
error with database after importing  demo content.

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#680]
After importing demo content, My client site showed list of error as below picture:
http://prntscr.com/7hjze7
And wordpress couldn't access the database. 
What do you think about it?

**Comment by valeriuzdrobau** [comment]
Send me please access details (FTP and phpmyadmin) to the email address valeriuzdrobau@gmail.com, to examine the issue.

**Comment by valeriuzdrobau** [comment]
To support the `utf8mb4_unicode_ci` collation, your users need to have MySQL 5.5.3 or higher. 

To avoid this problem, I recommend, when you  create demo content make sure you use: `CHARSET=utf8 COLLATE=utf8_unicode_ci`;

If the product is already on the client, he uses an older version of MySQL and encounter this problem, you can replace in database.txt:  
* from `utf8mb4` to `utf8`;
*  from `utf8mb4_unicode_ci` to `utf8_unicode_ci`.

**Comment by duongancol** [comment]
Thank you so much!
