### ISSUE TITLE
2/5 and 3/5 column shortcode.

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson#681]
Hello there,
I know that we can use 1/5 column shortcode, but I cannot figure out how to use 2/5 and 3/5 column shortcode to fullfil the grid. Could you please help me how to do that?
Any helps would be appreciated. Thanks.

**Comment by moldcraft** [comment]
You added `2/5` and `3/5` in [config](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/78d175f56f5259f4471761b2b2dc384634b563ad/config.php#L13) (by creating `{theme}/framework-customizations/extensions/builder/config.php`) and

> I cannot figure out how to use 2/5 and 3/5 column shortcode to fullfil the grid

Sorry, I don't understand what you can't figure out (maybe my English is not so advanced). More details please.

**Comment by RayNguyen** [comment]
Hey @moldcraft 
Thanks for your response.
After adding 2/5 and 3/5 column shortcode  in <code>config.php</code>, I will have to add custom CSS for <code>.fw-col-sm-25</code> and <code>.fw-col-sm-35</code> in backend right ?

**Comment by moldcraft** [comment]
Yes

**Comment by duongancol** [comment]
I think you have to add css for .fw-col-sm-25 because the backend grid is using bootstrap grid

**Comment by RayNguyen** [comment]
Just one more question, column icons are your custom design ? Or I can find it somewhere ?
Thanks so much @moldcraft !

**Comment by moldcraft** [comment]
Custom design
