### ISSUE TITLE
Backup issue & Shortcode issue

### ISSUE THREAD

**Issue by c0sm1n87** [ThemeFuse/Unyson#684]
Hello,

Tried to move the template on a remote server so I can access it when I'm not at home, so I tried the method with create demo install (which failed - it hung up and if I refreshed the page I had the "download" link available put the zip archive was corrupted).

I didn't really care about the demo install, I just wanted the template so I copied the template folder to the remote server - i activated it, it required the needed plugins, I installed them and went to see if it's working.

Everything seemed ok until I checked the visual editor, it seems that some created shortcodes (half I think) are available while others do not show up.

Any thoughts (ps, i tried the trick from the Slider to deactive and reactivate, maybe rebuild the tree but it's not working)? 

Later edit: i tried to remove unyson plugin and create a clean install. However, when I click download on the Page Builder extension it just refreshes my page and nothing happens.

**Comment by GheorgheP** [comment]
Hi,

How did you move the database from local to live server?

Could you provide access details to the remote server?
- wordpress login details
- ftp details;

Send them on dev-team@unyson.io

**Comment by c0sm1n87** [comment]
Hello,

I didn't move the database files, I simply copied the template folder (the database is mostly full of development crap at the current moment) and wanted to see how it looks on a fresh wp install.

I'll create a FTP account and mail you the details.

**Comment by GheorgheP** [comment]
Hi,

I checked the installation. First I noticed that the Page Builder extension was not installed at all.
Then I checked few shortcodes and they seems to work properly. Could you tell me what are the shortcodes that doesn't work?

**Comment by c0sm1n87** [comment]
I tried installing the Page builder extension but it didn't allowed it. 

"However, when I click download on the Page Builder extension it just refreshes my page and nothing happens."

also I was telling you that the shortcodes I created (the last tab, Saiph elements). For example, the Progress Bars (you can find the folder in the right place, along with the others).

**Comment by moldcraft** [comment]
> However, when I click download on the Page Builder extension it just refreshes my page and nothing happens.

Can you please look in `error.log` to see if there is an error or warning?

**Comment by c0sm1n87** [comment]
At the current moment I am at work and can't check "properly" but i had a quick look at the log and I can't see anything (warning or error).

**Comment by GheorgheP** [comment]
About the page builder installation. I will check this problem, I appears rarely and is not possible to reproduce, at least we did not find a way now.

About shortcodes. Please respect the wordpress folder naming convention: `wp-config` and not `wpConfig`.

**Comment by c0sm1n87** [comment]
I don't want to sound stupid, but please provide more details on this : "wp-config and not wpConfig."  If you are referring to the file, I can assure you that is named wp-config.

**Comment by llemurya** [comment]
@c0sm1n87  please read [Wordpress Coding Standards](https://make.wordpress.org/core/handbook/coding-standards/php/#naming-conventions).

**Comment by c0sm1n87** [comment]
:) yes, I know what you mean - I was lost in the "example" and before I edited the post you replied :D it's working now :+1:
