### ISSUE TITLE
Mega Menu remove div class

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#686]
Hello, 

How to remove ```<div class="mega-menu">..</div>``` in the Mega Menu markup and directly show ```<ul class="sub-menu mega-menu-row">..</ul>``` ?

**Comment by moldcraft** [comment]
You can [replace the default walker](https://github.com/ThemeFuse/Unyson/issues/79#issuecomment-74970280) and [change this logic](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/f429520598fbea4efd0ef39dccdcc49b1a864833/includes/class-fw-ext-mega-menu-walker.php#L156-L166).

**Comment by pear1** [comment]
Thank you.

**Comment by xttn** [comment]
Hi @pear1  are you complete your code to remove `<div class="mega-menu">` `</div>`?
