### ISSUE TITLE
[Question] Backup Extension: Import demo content hooks?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#687]
When a Demo Install is created, I see that it creates an auto-install directory. Are any other files changed?

If I create some changes to the theme it's not needed to generate Demo Install zip again, right?

Oh, and is it possible to not export the non-activated plugins because they give error on a clean Wordpress install as the plugins are not present there? Bug?

**Comment by valeriuzdrobau** [comment]
`auto-install` folder containts database (stored in `database.txt` file) without `wp_users` table, and uploads folder.
Regarding plugins, it can be made the information about them to not import, so that they will remain untouched. What do you think?

**Comment by pe6o** [comment]
Yes, that would be handy. How can it be achieved?

**Comment by valeriuzdrobau** [comment]
Starting with version [1.0.4 ](https://github.com/ThemeFuse/Unyson-Backup-Extension/releases/tag/v1.0.4) should be possible, using the following code:
```
if ( ! function_exists( '_filter_theme_fw_ext_backup_import_skip_options' ) ) {
    function _filter_theme_fw_ext_backup_import_skip_options( $options ) {
        return array_merge( $options, array(
                'active_plugins',
                'uninstall_plugins',
                'uninstall_plugins',
                'recently_activated',
                '_site_transient_update_plugins'
            )
        );
    }

    add_filter( 'fw_ext_backup_import_skip_options', '_filter_theme_fw_ext_backup_import_skip_options' );
}
```

**Comment by pe6o** [comment]
Is it possible to not include `active_plugins` in the array?

**Comment by valeriuzdrobau** [comment]
You can use above filter to keep certain values from `wp_option` table. If you exclude `active_plugins` key, will be imported information about active plugins from the WordPress instance from where you did export.

**Comment by pe6o** [comment]
Nice, thank you. And last question:

Is there a hook so I can `flush_rewrite_rules()` after the content is imported?

**Comment by valeriuzdrobau** [comment]
I have now [created](https://github.com/ThemeFuse/Unyson-Backup-Extension/commit/0d16c7b8a421706bd9021fe7e13f27649cd86653) such action, in the next version you can attach to it.

**Comment by pe6o** [comment]
That's great! Added filter to that hook already in my theme, so it will work when the new update is released =)

**Comment by valeriuzdrobau** [comment]
Hooks have been introduced in version [1.0.5 ](https://github.com/ThemeFuse/Unyson-Backup-Extension/releases/tag/v1.0.5) of [Unyson-Backup-Extension](https://github.com/ThemeFuse/Unyson-Backup-Extension).
