### ISSUE TITLE
Cannot redeclare class _fw_ext_seo_sitemap_builder

### ISSUE THREAD

**Issue by darklight3it** [ThemeFuse/Unyson#688]
I' m experiencing this error after updating your framework through wow [theme](http://themeforest.net/item/wow-multi-concept-one-page-wordpress-theme/11268415)

Fatal error:  Cannot redeclare class _fw_ext_seo_sitemap_builder in [path] on line 583

Please Help

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/82

**Comment by GheorgheP** [comment]
Hi,

Could you provide access to your worpdress installation? As the in the last version of the SEO this class was removed entirely.
It may require ftp access too.

You can provide details on: dev-team@unyson.io

**Comment by darklight3it** [comment]
No I can't, i'm working on my local dev. I can provide a zip of your plugin instead.

**Comment by GheorgheP** [comment]
Ok, provide it

**Comment by darklight3it** [comment]
Zip sent!!! From a quick overview _FW_Ext_Seo_Sitemap_Builder seems still present on class-sitemap-buolder.php line 8. I think the problem can be resolved removing the file completely, but I can wait a cleaner solution from you.

**Comment by GheorgheP** [comment]
I received the file, also tested by installing the SEO and updating it. All seems to work fine.
Could you chekc if the `_FW_Ext_Seo_Sitemap_Builder` class is not present in other place in the theme?

**Comment by darklight3it** [comment]
Thanks for your hint,

the theme works well after upgrading the seo plugin. The class seems not
present in other part of the theme.

I suggest to try catch the include block in order to prevent blocking
errors when user upgrades only the core framework.



2015-06-22 16:03 GMT+02:00 Gheorghe <notifications@github.com>:

> I received the file, also tested by installing the SEO and updating it.
> All seems to work fine.
> Could you chekc if the _FW_Ext_Seo_Sitemap_Builder class is not present
> in other place in the theme?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/688#issuecomment-114113839>.
>



-- 
*Davide* *Melfi*

*"Cowards die many times before their deaths, The valiant never taste of
death but once."*

*William Shakespeare - Julius Caesar -*
