### ISSUE TITLE
How to add options on Taxonomy Term Edit Page through extension plugin?

### ISSUE THREAD

**Issue by akshaya-rane** [ThemeFuse/Unyson#689]
I have following folder structure, 

{plugin folder name}/extensions/{extesion_name}/options/taxonomies/category.php

If I add file in, following folder structure in theme

{theme}/framework-customizations/theme/options/taxonomies/{$taxonomy}.php

options get added successfully. Can we add options for taxonomy through custom plugin?

**Comment by moldcraft** [comment]
Use [this filter](https://github.com/ThemeFuse/Unyson/blob/3dfa4f5dd5b6d88045653898206a3cc2fd218412/framework/core/components/theme.php#L130-L133).
