### ISSUE TITLE
Can i use option types into my plugin settings page ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#691]
Hello @moldcraft 

I want to know that if there is a flexibility in unyson that we can also embed option types in plugin page just like we did for post,page,taxonomies as a meta box or in theme settings page. 

Thanks

**Comment by moldcraft** [comment]
Hello, 

You want to create a settings page for your plugin?

**Comment by wpthemes786** [comment]
Yes i have a plugin with setting page and i want to use unyson option types in my plugin setting page.

**Comment by moldcraft** [comment]
I will create a tutorial "How to create a settings page" and will add it in documentation, today or tomorrow.

**Comment by duongancol** [comment]
Following :+1:

**Comment by wpthemes786** [comment]
Thanks @moldcraft. I love unyson thats why do not go to another frameworks who supports plugin settings also. i want this framework have this option.

Thanks

**Comment by wpthemes786** [comment]
@moldcraft when would you ready the docs i need it urgently as i have to develop plugin with unyson.

**Comment by moldcraft** [comment]
Try [this](https://github.com/ThemeFuse/Unyson/issues/250)

**Comment by wpthemes786** [comment]
no i have to make a seperate plugin in which i want to embed unyson option types on my setting pge.

**Comment by moldcraft** [comment]
You want to include Unyson into your plugin?

**Comment by moldcraft** [comment]
You want to include Unyson into your plugin so it must work even if Unyson plugin is not installed?

**Comment by wpthemes786** [comment]
Yes exactly @moldcraft

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/515

**Comment by wpthemes786** [comment]
No that something else. like titan framework have the ability to work in plugins like we can create admin menus and settings pages with the help of titan framework. i just need this from you guys because i want to use unyson not comfortable with titan framework. That's why asking from you guys if there is any possibility in unyson.

**Comment by moldcraft** [comment]
You can include Unyson in your plugin http://manual.unyson.io/en/latest/#install-anywhere
But it will be the full framework, not only option types.

**Comment by wpthemes786** [comment]
Ok if i include in plugin using this teachnique how would i create the
admin pages and assign options to them

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/691#issuecomment-114854315

**Comment by wpthemes786** [comment]
Anyhow @moldcraft its not that much easy like theme settings using bunch of arrays in unyson. I have seen your recomendation its fairly nit too easy get ready the page in seconds. 
Thanks

**Comment by moldcraft** [comment]
I thought the tutorial will be big and with a lot of text, then I decided just to make a working piece of code and let users inspect it, so here it is http://manual.unyson.io/en/latest/helpers/php.html#create-settings-page

It's just a little improved version of [this](https://github.com/ThemeFuse/Unyson/issues/250) (it has a Reset button).

**Comment by yongkiagustinus** [comment]
hi @moldcraft checked http://manual.unyson.io/en/latest/helpers/php.html#create-settings-page but it seems not there anymore, is there a new link ?

**Comment by andreiglingeanu** [comment]
@yongkiagustinus [Here](http://manual.unyson.io/en/latest/helpers/settings-form.html) it is.
