### ISSUE TITLE
Theme customizer - 'Live Preview' problem on internal pages.

### ISSUE THREAD

**Issue by akshaya-rane** [ThemeFuse/Unyson#692]
Hi,

I have added custom options through 'customizer.php' file, it get reflected correctly. 

I have added 'theme-customizer.js' file on, 'customize_preview_init' action. When user views, 'Theme customizer'  page, live preview changes works properly, but when user move to other page through navigation menu or other link, this 'js' file was not getting added. 

If you check WordPress default - 'twentyfifteen' or 'twentyfourteen' theme's customizer, correspnding javascript files 'customize-preview.js' or 'customizer.js' added properly, can check through 'Network' panel. 

Also, how to hide 'Admin bar' in theme customizer internal pages? 

What could be the reason for this? Kindly provide your views.

**Comment by moldcraft** [comment]
Hello,

That js file is included properly when Unyson is disabled?

**Comment by akshaya-rane** [comment]
Hi,

I tried by deactivating Unyson, there is still problem with js file include on customizer page itself. 

I have made use of Unyson functions therefore there is fatal error for it.  Could you suggest something?

**Comment by moldcraft** [comment]
> I tried by deactivating Unyson, there is still problem with js file include on customizer page itself.

So it has nothing with Unyson.

> I have made use of Unyson functions therefore there is fatal error for it. Could you suggest something?

Check if function exists before calling it.
