### ISSUE TITLE
Extensions will not download

### ISSUE THREAD

**Issue by GetSetWeb** [ThemeFuse/Unyson#693]
Hi there,

I've just uploaded the unyson plugin and none of the extensions will download. Im using the most upto date version of wordpress and it say my extensions are up to date although it seens to be missing the megamenu. Any help would be most appreciated

It also shows a popup with no message in the box so I cant even tell you if there is an error code etc Please see attached screenshot, any help will be most appreciated as i was really looking forward to trying out this plugin.

Regards

Steve
![screen shot 2015-06-25 at 13 46 43](https://cloud.githubusercontent.com/assets/13049456/8354687/d49246a0-1b41-11e5-8854-703a28abcd95.png)

**Comment by moldcraft** [comment]
Hello,

Can you send me the access details for your site to `moldcraft[at]email.com` so I can inspect and find the problem, because on my side everything works fine (I can't reproduce it).

**Comment by moldcraft** [comment]
[Here](http://manual.unyson.io/en/latest/extension/megamenu/index.html) is explained how to make megamenu visible.

**Comment by moldcraft** [comment]
Thank you for access details.

I found the problem, your hosting is not allowed to make requests to [this url](http://github-api-cache.unyson.io/repos/ThemeFuse/Unyson-Empty-Extension/releases/latest), here is the error:

```
WP_Error
(
    [errors] => array
    (
        [http_request_failed] => array
        (
            [0] => 'couldn't connect to host'
        )
    )
    [error_data] => array()
)
```

Try to contact your hosting company support.

**Comment by GetSetWeb** [comment]
Thanks for the prompt reply I will get into my hosts.

Can you envisage any reason why they would deny this URL??

Regards

Steve

**Comment by moldcraft** [comment]
I don't know, some sort of security
