### ISSUE TITLE
Auto-enqueue static files can be disabled?

### ISSUE THREAD

**Issue by NazarkinRoman** [ThemeFuse/Unyson#695]
Hello!

For example, I need to create a custom slider. I take `bx-slider` and fork it via child extensions mechanism. But if I remove some static files from my child directory, framework takes it from source directory. But if I don't need these files, how can I unregister them?

Thanks.

**Comment by llemurya** [comment]
If you want to disable the default sliders, the next snippet will help you.
```php
function _filter_theme_disable_sliders($sliders){
    foreach (array('owl-carousel', 'bx-slider', 'nivo-slider') as $name) {
        $key = array_search($name, $sliders); 
        unset($sliders[$key]);  
    }
    return $sliders; 
}
add_filter( 'fw_ext_slider_activated' , '_filter_theme_disable_sliders');
``` 
If you create your custom slider with an custom name for ex: (my-custom-slider) ,and you have it in child directory and in the parent directory, the child files have priority other parent files. If you removes the child files, the parent files will be loaded. It is a core mechanism of the Unyson framework.

**Comment by NazarkinRoman** [comment]
I tried to create custom-named slider and place it in my theme's `framework-customizations` folder, but Unyson does not see them.. So, I can fork only existing sliders?

**Comment by llemurya** [comment]
@NazarkinRoman please read this https://github.com/ThemeFuse/Unyson/issues/673 issue.I think that you will find the answer.Pay attention at the comment with the trick.If it helps, please close the issue.

**Comment by NazarkinRoman** [comment]
Oh, thank you. :)
