### ISSUE TITLE
What happened if the plugin is updated ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#696]
Hello @moldcraft 
i have recently asked a question about how to disable the show other extensions in unyon page. and you guys help me out in this provide me solution.

<?php if ($something_displayed && apply_filters('fw_extensions_page_show_other_extensions', false)): ?>

Case : if user update the unyson plugin is this possible that my code changing in extension-page.php file will be override.

Thanks

**Comment by moldcraft** [comment]
On plugin update, all files are replaced.

That filter will be part of the next version, so don't worry about it. Or are you speaking about some other changes that you made in `extension-page.php` ?

**Comment by wpthemes786** [comment]
Nope just this change which i mentioned above to hide show other extensions on unyson page.

i have another question that is when we create demo install folder, so is user required to enable wp debug to true so he could see auto install option.

**Comment by valeriuzdrobau** [comment]
Hi, there is no need. It must activate debug mode when we create demo content.

**Comment by wpthemes786** [comment]
Kindly provide guideline to me.
I am using page builder and backup extesion in unyson. should i use tgm method and make a package of my unyson plugin along with two extensions as a zip and include into my theme directory. so user dont have to install extensions.

**Comment by valeriuzdrobau** [comment]
It is easier to add the following code in `hooks.php` or in `functions.php`

```
if ( ! function_exists( '_filter_theme_fw_extensions_page_show_other_extensions' ) ) {
	function _filter_theme_fw_extensions_page_show_other_extensions( $show_other_extensions ) {
		return false;
	}

	add_filter( 'fw_extensions_page_show_other_extensions', '_filter_theme_fw_extensions_page_show_other_extensions' );
}

```

**Comment by wpthemes786** [comment]
But you are telling me that how to hide show other extensions button from unyson page.
My real question is that i have a theme built on unyson and i just use page builder and backup extension.
and i create the demo install. should i suppose to zip my unyson plugin and put into theme directory and allow tgm to install on activate and then after this i create the demo install.

So when user activate the theme the two extensions backup and page builder will be automatically installed or not?

Thanks

**Comment by moldcraft** [comment]
* [Require Unyson with TGM](https://github.com/ThemeFuse/Scratch-Theme/blob/df32deb4d3c41df2c847f7514c157833485e5a0a/scratch-parent/functions.php#L8-L26)
* After Unyson plugin will be installed and activated, the user will be redirected to a page to install [extensions supported by your theme](https://github.com/ThemeFuse/Scratch-Theme/blob/df32deb4d3c41df2c847f7514c157833485e5a0a/scratch-parent/framework-customizations/theme/manifest.php#L9-L20).
