### ISSUE TITLE
Media Setting Options

### ISSUE THREAD

**Issue by ankitaraikundalia** [ThemeFuse/Unyson#698]
How can I create the below options using Unyson?

![image-settings](https://cloud.githubusercontent.com/assets/9928664/8425884/247a9bd8-1f28-11e5-8c4d-7ed3e9978040.png)

I want to add image sizes for my CPT from these options.

**Comment by moldcraft** [comment]
Do you mean [this](http://static.md/3bfc1e2dacdd0fbec1eb38696ffbebde.png)?

If yes, we don't have that, we have `slider` option type.

----

Or you want exactly the same design to be achieved using Unyson options?

If yes, using existing built-in options, you can't.

You can create your own option type.

**Comment by ankitaraikundalia** [comment]
@moldcraft , I followed the instructions on http://manual.unyson.io/en/latest/options/create-option-type.html to create a new option type and I got the below output:

![new-option-type](https://cloud.githubusercontent.com/assets/9928664/8429183/e4753dde-1f42-11e5-8112-79d015a74f1f.png)

What could be the possible error?

**Comment by moldcraft** [comment]
Can you show us your option-type code?

**Comment by ankitaraikundalia** [comment]
@moldcraft , I had written the wrong function name while doing add_action in hooks.php. The issue is resolved now.

However, I found 2 errors in your documentation.
1: In `{theme}/inc/hooks.php`, we define the `function _action_theme_include_custom_option_types()`.
In this function, the path for the class file should be:

```require_once dirname(__FILE__) . '/includes/option-types/new/class-fw-option-type-new.php';```

`/includes` is mising in the documentation.

2: In the class file `class-fw-option-type-new.php` , the path to scripts.js file is wrong. It should be:

```
wp_enqueue_script(
            'fw-option-'. $this->get_type(),
            $uri .'/js/scripts.js',
            array('fw-events', 'jquery')
        );
```
