### ISSUE TITLE
wp-editor did not render shortcodes ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#699]
Hello @moldcraft 

i am using option type wp-editor and when i put any shortcode in editor it did not work even its did not render any result. first its shows me direct shortcode just like [galler] on front end side. then i wrap the variable just like this echo do_shortcode($variable); its hide the direct shortcode syntax but did not render any results.

Thanks for help

**Comment by llemurya** [comment]
@wpthemes786  please read [WordPress Documentation](https://codex.wordpress.org/Function_Reference/do_shortcode). Pay attention at these phrase
```php
// Use shortcode in a PHP file (outside the post editor).
echo do_shortcode( '[gallery]' );
```

**Comment by wpthemes786** [comment]
Yes i have read the documentation. in my scenario i put the shortcode in your unyson wp-editor and when i get the content it will not display the shortcode content.

**Comment by llemurya** [comment]
@wpthemes786 I made an [screencast](https://youtu.be/mGZmlQe6U9s) as a proof that it works.

**Comment by llemurya** [comment]
@wpthemes786 please make an screencast how to reproduce this bug.Thanks.

**Comment by llemurya** [comment]
@wpthemes786 any progress ?

**Comment by wpthemes786** [comment]
@llemurya  Sorry i didn't make screen cast of this issue.
i can tell you in simple steps.

1. i am using wp-editor option in addable-popup option type in my custom post type.
2. And i am getting the wp-editor value on from end using fw db post option. but its just print the text.but when i put any shortcode in visual mode of the wp-editor the shortcode as it is printed and its not rendered.

Thanks

**Comment by ankitaraikundalia** [comment]
@wpthemes786 , Visual mode will print the content as it is. You will have to write the shortcode in text mode to render it properly.

**Comment by llemurya** [comment]
@wpthemes786 I think that @ankitaraikundalia answer at your question. If you rewatch the video that I post above you can see that I post the shortcode in the text mode. Please verify and give us an answer in order to resolve this issue.Thanks.
