### ISSUE TITLE
Kindly provide steps for installing demo content ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#701]
Hello.

i have created the backup with backup extension and extract that backup and use that theme into another wordpress installation.

Then i activate the theme its prompt me to install unyson.
I install unyson and install the page builder and backup extension.

So i did not see any install demo content page. 

what step i left in this procedure.

Kindly guide me

Thanks

**Comment by valeriuzdrobau** [comment]
Hi, if you followed the steps on page http://manual.unyson.io/en/latest/extension/contentdemoinstall/index.html in main menu must appear page Tools-> Install Content.

**Comment by wpthemes786** [comment]
Let me clear my self. when we shipped theme with unyson as a zip with tgm plugin. are the users required to install unyson first before installing demo content. or is backup extension is must required for demo content installation.

**Comment by wpthemes786** [comment]
Is fresh wp install necessary for this purpose.

**Comment by valeriuzdrobau** [comment]
Backup extension is must required for demo content installation. Is not necessarily a fresh wordpress install.

**Comment by wpthemes786** [comment]
And is backup extension is required for auto install method

**Comment by valeriuzdrobau** [comment]
To import the demo content, it needs to activate `backup` extension.
