### ISSUE TITLE
Unyson extension installation error

### ISSUE THREAD

**Issue by olekb** [ThemeFuse/Unyson#702]
Problem is that I just wanted to start using framework. It works when put on remote server but can't install any extension when using wamp as server on my windows machine. I click to download extension and JS alert box is generated with no text only with ok button. After cliccking ok no extension is installed, tried with all extension and with different wp versions. Please advise what to check

**Comment by moldcraft** [comment]
Can you look in apache `error.log` to see if there is any error?

**Comment by olekb** [comment]
i only have this error multiple times, dont really know how to resolve 

[Wed Jul 01 15:33:56.404153 2015] [access_compat:error] [pid 8136:tid 1620] [client 192.168.2.169:51287] AH01797: client denied by server configuration: C:/wamp/www/

**Comment by moldcraft** [comment]
I don't know how to reproduce this and find the problem. It's not on a live server so I can't access your site to inspect the problem.

Can you open in browser (F12) `Inspect element -> Network` and inspect the ajax response when you click the install button, and try to find any error?

**Comment by olekb** [comment]
![przechwytywanie](https://cloud.githubusercontent.com/assets/8269728/8462609/562c0ed8-2035-11e5-87ff-829b608b00b6.PNG)
first just to show how it look like,

**Comment by olekb** [comment]
{"wp-auth-check":true,"server_time":1435777805}

this is how ajax response looks like for admin-ajax.php

what else can i show. it goes only here, if it is better I can share my machine via teamviewer to check because i would prefer to use it locally first

**Comment by moldcraft** [comment]
Send me please teamviewer details to `moldcraft[at]email.com`.
I will be online for a few hours.

**Comment by olekb** [comment]
The error is

```
No available HTTP transports that could be used to execute the command.
```

**Comment by olekb** [comment]
On the server wasn't enabled php curl extension, after enabling it everything works.

Anyway it's strange that wordpress plugin stall download worked, but any other download not.

Here is a debug

```php
fw_print(
    wp_remote_retrieve_response_code($http->request('http://downloads.wordpress.org/plugin/buddypress.2.3.2.1.zip')), // strange: this works					wp_remote_retrieve_response_code($http->request('https://wordpress.org/latest.tar.gz')) // this not
);
```

If anyone knows why this happens please share. At the moment it's a mistery.

**Comment by olekb** [comment]
once can be closed, works after php_curl extension is loaded but after restarting wamp server fully. thanks for moldcraft help with resolving problem.

**Comment by moldcraft** [comment]
P.S. I copied your ajax response content, and will inspect it to find out why the empty error happens, it should display that error message that we saw on extension install page https://github.com/ThemeFuse/Unyson/issues/702#issuecomment-117804755
