### ISSUE TITLE
Instructions on how to build or include extensions without FTP

### ISSUE THREAD

**Issue by mingle2** [ThemeFuse/Unyson#703]
We don't use FTP so any documentation for installing the plugin and extensions without FTP would  be helpful....

**Comment by mingle2** [comment]
Again on this page need ftp access:

"Make you theme look exactly like our demo"

**Comment by moldcraft** [comment]
If php on your server has access to modify files directly, it will not ask you ftp credentials, else, it will show you the ftp credentials form.

To make things more clear, please give us some links to documentation with ftp that you want to be without ftp.

**Comment by mingle2** [comment]
For example I have a theme that I want to "import 

On this page here:

/wp-admin/tools.php?page=auto-install

I select "import demo content"

I have looked and all the data is there in the auto-install directory in the theme.  However every time I'm taken to this screen:

/wp-admin/tools.php?page=auto-install&_wpnonce=2f138bd511

Connection Information

To perform the requested action, WordPress needs to access your web server. Please enter your FTP credentials to proceed. If you do not remember your credentials, you should contact your web host.

**Comment by mingle2** [comment]
"If php on your server has access to modify files directly"

Which files?

**Comment by moldcraft** [comment]
All files except `wp-content/uploads` (when you upload an image in media library, you will never be required to enter ftp details, that's because `wp-content/uploads` is writable by all (permissions `777`), and at any time, from you php script you can create files there)

**Comment by mingle2** [comment]
chmod -R 777 the wp-content directory and still get the ftp prompt.   sigh hehe.....

What if I just do a manual mysql source import on the database.txt and replace the uploads folder will that work?

**Comment by mingle2** [comment]
I dont care about the backup extensions, I just want to import the demo content.

**Comment by moldcraft** [comment]
`chmod -R 777` is a bad practice. The ftp thing was made to secure your site files, so not any malicious plugin cannot change/delete/add any file in background until you enter ftp details.

> I just want to import the demo content.

So your questions is about demo content. I redirected this issue to @valeriuzdrobau he is the maintainer of the Backup extension and knows better how demo content works.

**Comment by valeriuzdrobau** [comment]
Hi, try to install a free  plugin from wordpress.org repository, and tell me if appear form to put FTP details.

**Comment by valeriuzdrobau** [comment]
Due to inactivity I close this issue. Feel free to reopen it at any time.
