### ISSUE TITLE
Feature request - is it possible to add location filters for "framework-customizations" folder?

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#704]
Hello, creators!

I really need this because i want to use Unyson as a part of my plugin. Indeed, it would be cool to change location of "framework-customizations" directory via filters into my plugin folder, for example. 

Could you add these filters to the official Unyson release?

Thank you for a great product!

```
	/**
	 * Full path to the child-theme framework customizations directory
	 * @param string $rel_path
	 * @return null|string
	 */
	function fw_get_stylesheet_customizations_directory($rel_path = '') {
		if (is_child_theme()) {
			return get_stylesheet_directory() . fw_get_framework_customizations_dir_rel_path($rel_path);
		} else {
			// check is_child_theme() before using this function
			return null;
		}
	}

	/**
	 * URI to the child-theme framework customizations directory
	 * @param string $rel_path
	 * @return null|string
	 */
	function fw_get_stylesheet_customizations_directory_uri($rel_path = '') {
		if (is_child_theme()) {
			return get_stylesheet_directory_uri() . fw_get_framework_customizations_dir_rel_path($rel_path);
		} else {
			// check is_child_theme() before using this function
			return null;
		}
	}
```

**Comment by moldcraft** [comment]
Hello,
it has no sense. framework-customizations is for theme. If you will do that, any theme with framework-customizations will not work.

Why do you need to change that, why you are trying to achieve? More details please

**Comment by WPJobs** [comment]
I planned to use your framework as a part of plugin (just for creating necessary options pages and options for custom post types), not a part of theme :)

Is any way to hook plugin options from another plugin, not from theme?

Thank you for fast response!

**Comment by moldcraft** [comment]
Yes [1](https://github.com/ThemeFuse/Unyson/blob/3dfa4f5dd5b6d88045653898206a3cc2fd218412/framework/core/components/theme.php#L85), [2](https://github.com/ThemeFuse/Unyson/blob/3dfa4f5dd5b6d88045653898206a3cc2fd218412/framework/core/components/theme.php#L100), [3](https://github.com/ThemeFuse/Unyson/blob/3dfa4f5dd5b6d88045653898206a3cc2fd218412/framework/core/components/theme.php#L115), [4](https://github.com/ThemeFuse/Unyson/blob/3dfa4f5dd5b6d88045653898206a3cc2fd218412/framework/core/components/theme.php#L130)

**Comment by WPJobs** [comment]
Thank you for your response again, but, what do you think, it would be much easier to create the configuration in my plugin directory like i can create config with theme options, insted of making a hook, isn't right? Why to not add a possibility to re-locate "framework-customizations" directory, it will take 2 strings of code and 2 minutes. 

If i can copy your plugin into my app and re-locate it's path, why i can't re-locate customization folder path, it's not entirely clear to me :)

If you do not agree with this, let me know, but in any case, thank you for your great framework!

**Comment by WPJobs** [comment]
Thank you for a fast response! I had to check on the availability of these hooks before asking here. Sorry for your time!

**Comment by moldcraft** [comment]
No problem.
Good luck with the plugin
