### ISSUE TITLE
widget areas in Customizer

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#705]
I don't know why Widgets section in Customizer only shows 3 widget location although I registers 5 widget location in hooks.php. 
You can see here: http://prntscr.com/7nv6sj and http://prntscr.com/7nv70o
Here is full code:
```php
function _action_theme_widgets_init() {
	register_sidebar( array(
		'name'          => __( 'Sidebar Widget Area', 'unyson' ),
		'id'            => 'sidebar-2',
		'description'   => __( 'Appears in the sidebar of the site.', 'unyson' ),
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

	register_sidebar( array(
		'name'          => __( 'Pre-footer column 1', 'unyson' ),
		'id'            => 'prefooter-col-1',
		'description'   => __( 'Appears in the prefooter section of the site.', 'unyson' ),
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

	register_sidebar( array(
		'name'          => __( 'Pre-footer column 2', 'unyson' ),
		'id'            => 'prefooter-col-2',
		'description'   => __( 'Appears in the prefooter section of the site.', 'unyson' ),
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

	register_sidebar( array(
		'name'          => __( 'Pre-footer column 3', 'unyson' ),
		'id'            => 'prefooter-col-3',
		'description'   => __( 'Appears in the prefooter section of the site.', 'unyson' ),
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

	//Add shop sidebar widget
	if(function_exists('woocommerce_get_page_id')){
		/**
		 * Creates a sidebar
		 * @param string|array  Builds Sidebar based off of 'name' and 'id' values.
		 */
		$args = array(
			'name'          => __( 'Sidebar Shop', 'royalty' ),
			'id'            => 'sidebar_shop',
			'before_widget' => '<div class="%2$s" id="%1$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h2>',
			'after_title'   => '</h2>'
		);

		register_sidebar( $args );

	}
}

add_action( 'widgets_init', '_action_theme_widgets_init' );
```

**Comment by llemurya** [comment]
Maybe because some widget areas are empty? Can you see if it is as I said?

**Comment by duongancol** [comment]
I checked and make sure it's not empty

**Comment by llemurya** [comment]
@duongancol okay , I will reproduce this and give you an answer.

**Comment by duongancol** [comment]
ok, I'll wait it. Thank you

**Comment by llemurya** [comment]
On more question , can you see if the Unyson Sidebar  Extension is enabled in your WordPress install.Thanks!

**Comment by duongancol** [comment]
I only activated Page builder, Backup and Event extension.

**Comment by llemurya** [comment]
But If you disable the Unyson Plugin the result is the same? Please make a try. I'am waiting for your response.

**Comment by duongancol** [comment]
I tried and when I did it, the widget setion didn't show in Customizer

**Comment by llemurya** [comment]
@duongancol I don't understand what kind of widget section you put, the native WordPress widget , try put the code with register sidebars in function.php in theme and disable the Unyson Plugin to see if this problem is from Unyson or from WordPress. Thanks. I'am awaiting for your response.

**Comment by duongancol** [comment]
I moved code to functions.php
When Unyson is activated : http://prntscr.com/7nwn4c, 
When Unyson is not activated: http://prntscr.com/7nwnp0 . No widget section

**Comment by llemurya** [comment]
@duongancol Widgets appear in the Customizer, but only if you are on the page that they are used on.In your case the page you open don't have in the templates 
```php
dynamic_sidebar( 'sidebar-2' );
dynamic_sidebar( 'sidebar_shop' );
```
Please visit the pages that have these code in the templates and it will appear.It is the normal WordPress behavior. Please verify and close the issue. Thanks.

**Comment by duongancol** [comment]
You're totally right. Thank you so much for this.
