### ISSUE TITLE
Where can i find this?

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#707]
Hi,

On the website http://docs.themefuse.com/exposure/your-theme/shortcodes/columns i see options for blocks, where can i find or activate those? Those arent in WP yet?

**Comment by moldcraft** [comment]
Hello

> options for **blocks**

Which blocks?

**Comment by nickkuijpers** [comment]
Please see the following screenshots. The first 2 are on your website, the last one is my page builder. I dont see the option to change the block options.

<img width="906" alt="schermafbeelding 2015-07-03 om 15 06 36" src="https://cloud.githubusercontent.com/assets/5340923/8499642/29b99abc-2195-11e5-9d58-1b3423ad1ae3.png">
<img width="623" alt="schermafbeelding 2015-07-03 om 15 06 21" src="https://cloud.githubusercontent.com/assets/5340923/8499643/29bdff94-2195-11e5-9358-222bb5204278.png">
<img width="636" alt="schermafbeelding 2015-07-03 om 15 06 16" src="https://cloud.githubusercontent.com/assets/5340923/8499644/29c3b9ac-2195-11e5-892a-9919e0fdf0b7.png">

**Comment by moldcraft** [comment]
Try to create

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/options.php
```

with

```php
$options = array(
    'test' => array('type' => 'text'),
);
```

**Comment by nickkuijpers** [comment]
Aye, its working! Where can i find your options.php and view.php? With all the options you describe on the link ive sent?

**Comment by moldcraft** [comment]
[Here](http://themeforest.net/item/exposure-photography-wordpress-theme/10562504)

**Comment by nickkuijpers** [comment]
Awesome! Thx!
