### ISSUE TITLE
Error Js after upgrade to latest version

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#708]
Hi,

I got below error message at Theme Setting page after upgrade to latest version of Unyson :
Uncaught ReferenceError: fw is not defined at this line of code "fw.loading.show(fwLoadingId);"

Then I tried again with scratch-parent theme and it's working fine with the icon loading.

Please help me to solve this problem

Thanks

**Comment by moldcraft** [comment]
I need to debug the code, adnib and ftp access.

**Comment by maiakhoa** [comment]
sorry it's running on my computer, so I will send you a package, please give me your email

**Comment by moldcraft** [comment]
`moldcraft@email.com`

**Comment by maiakhoa** [comment]
Hi @moldcraft 
I sent it to your email

**Comment by moldcraft** [comment]
I will take a look after a few hours, now I am not at my PC.

**Comment by maiakhoa** [comment]
Thank @moldcraft

**Comment by moldcraft** [comment]
I get 

```
Fatal error: Cannot redeclare class FW_Option_Type_Style in /var/www/wordpress/public_html/wp-content/themes/{theme}/inc/includes/option-types/style/class-fw-option-type-style.php on line 0
```

Why do you have the same option type (the same type and class name) as in Styling extension? Why don't you prefix your option types with your unique prefix to prevent such errors?

**Comment by maiakhoa** [comment]
Hi @moldcraft 
Sorry, I forgot to remove that options type that was created on another one. I will correct it.
So you means I just need to correct that problem to fix the js issue, right ?

Thanks

**Comment by moldcraft** [comment]
> So you means I just need to correct that problem to fix the js issue, right ?

No, I just notice that.
P.S. Also you have `font` option type. Better to prefix it, for e.g. `mkh-font`.

----

I [fixed](https://github.com/ThemeFuse/Unyson/commit/b79b23bbc0aebe57a646d3c1fa2e76b52b9a8722) the problem. I don't know why this happens only on your theme.

One question: That theme is already live, I mean you finished it and it's already on sale, or it is still on development?
I am asking because the next Unyson release will not be soon, because we made some big changes and it will be `2.4.0`. But if this error is in production, I will create a custom urgent release `2.3.4`.

**Comment by maiakhoa** [comment]
Hi @moldcraft 
Thank for suggestion and asking. I will correct the font prefix.
Regarding the issue, this occur on the new one and have not released yet. I think it should be included in the next big release of framework 2.4.0
The old one is already on sale, but I think it's not a big problem now.

Thank so much for you support @moldcraft

**Comment by moldcraft** [comment]
On the old theme (that is already on sale) this error doesn't happen?

**Comment by maiakhoa** [comment]
It occurs too, I have 2 theme and both of theme occurs this issue, but I mean that it does not affect to the main functions such as showing and saving data. So it could be delayed the fix to the next big release. 

Thanks

**Comment by moldcraft** [comment]
Thank you
