### ISSUE TITLE
Multisite Issues 

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#709]
Hello,

I'm having trouble with my theme (Unyson powered) integration on Multisite installation. I've seen the other issues about this but they're quite old, so with all the changes on Unyson (good things btw! ;)) there is new issues about that (according to customers and some of my researches) : 

* We can't deactivate Unyson while the theme is activated (so we have to switch theme before activating Multisite option)
* the Unyson installation is directly set as the "Main site"
* the Megamenu extension isn't working -> parse error and the menus are down

Do you have any ideas about how we can fix that ? Thanks :)

Best regards

2F

**Comment by moldcraft** [comment]
Hello

> Do you have any ideas about how we can fix that ?

Nope. I made some multisite fixes some time ago, and that's all. I will investigate this.

Thank you for details. If you have more, give everything you have.

**Comment by 2Fwebd** [comment]
Hello @moldcraft,

Thanks for the fast reply and sorry for the late reply, but yep I have more : 

* Regarding the menu issue, it says : 
`The given object ID is not that of a menu item.` and the parse error is here when you try to add an icon (in the popup). 

* From my customer : 

> 1. the Network Activation...somehow it activates itself on the entire network, It should NOT do this, If you have other sites and different frameworks on the network

> 2. It assigns itself as the Main site, even though I already have a main site assigned.

* I think the issue will be, how the extensions will be managed across the networks, like if we have 2 websites with Unyson, how the extensions are managed ? 

I'll do more testing on WPMU to see if there is any difference ;)

2F

**Comment by moldcraft** [comment]
> We can't deactivate Unyson while the theme is activated (so we have to switch theme before activating Multisite option)

I can't reproduce that https://www.youtube.com/watch?v=iihAdmGIocA

> the Unyson installation is directly set as the "Main site"

I don't know why this happens. 
On `/wp-admin/network/plugins.php?plugin_status=inactive` Unyson is in Inactive tab.
But when I add `var_dump(__FILE__);` in `wp-content/plugins/unyson/unyson.php` it is executed

![s](https://static.md/b731c5d58bb0a96378a4534e638230f9.png)

If I add that `var_dump(__FILE__);` in other inactive plugins, it is not executed. Very strange.

> the Megamenu extension isn't working -> parse error and the menus are down

I can't reproduce that https://www.youtube.com/watch?v=4eHMu609Aio

> I think the issue will be, how the extensions will be managed across the networks, like if we have 2 websites with Unyson, how the extensions are managed ?

Last time when I made multi site fixes, I made the behavior like for themes: Only Super Admin can install extensions, sub-admins can only activate/deactivate extensions.

----

Please provide exact steps how to reproduce the problems (if you can, create videos)

**Comment by 2Fwebd** [comment]
Thank you @moldcraft,

I'll work on that tomorrow and provide you videos with the issues and exact steps ;) 

Thanks again,

2F

**Comment by 2Fwebd** [comment]
Hi @moldcraft,

Sorry for the late reply... I just made more testing with 2 customers and it was caused by conflicts with other plugins. Unyson is definitely Multisite ready !!

2F
