### ISSUE TITLE
Missing shortocode content and Undefined index error for posts that are imported from an xml file

### ISSUE THREAD

**Issue by sunnyville** [ThemeFuse/Unyson#710]
Hi,

My issue is that when I create a new post and enter shortcodes in it, everything works fine. But when I export the content through xml and import it to another site with the same setup (same server, theme and Unyson activated), I get the following error where the shortcodes' 'view' content is supposed to show up:

**Notice: Undefined index: *shortcode_name* in C:\xampp\htdocs\wordpress\wp-content\plugins\unyson\framework\extensions\shortcodes\extensions\page-builder\extensions\editor-shortcodes\class-fw-extension-editor-shortcodes.php on line 201**

This is for my local server, but I've also tested this on a live site.

And when I go to edit page of the imported post (or even page), I find that all data for the shortcode is missing. And then when I edit the shortcode and put the content again, it works fine.

I'm not sure if I've missed something in the documentation or not. But to me it seems like the shortcodes only get registered when they are first saved from a Post or Page.

Please let me know if someone can reproduce this problem and know how to fix this. I will really appreciate that.

Thank you very much.

**Comment by valeriuzdrobau** [comment]
Hello, please tell me which version you use, on:
* Unyson
* Shortcodes extension
* Page Builder extension

**Comment by sunnyville** [comment]
In my Admin it says that everything is up to date, including all the plugins and Unyson Extensions.

The Unyson framework I can tell is Version 2.3.3. But I'm not sure where to find the version of the extensions.

**Comment by valeriuzdrobau** [comment]
send me please access details to the valeriuzdrobau@gmail.com email address

**Comment by valeriuzdrobau** [comment]
Due to inactivity I close this issue. Feel free to reopen it at any time.
