### ISSUE TITLE
How to get submit contact message ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#712]
Hello ! @moldcraft 

I want to show submitted contact form message using ajax. 

Thanks

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/helpers/php.html#ajax-submit

**Comment by wpthemes786** [comment]
Thanks @moldcraft  i will look into this shortly and reply you back.

**Comment by wpthemes786** [comment]
@moldcraft  Where should  i enqueue this js script on front end?

**Comment by moldcraft** [comment]
Yes

**Comment by wpthemes786** [comment]
You referenced js file in docs. shouldi first download it or is this file already reside in form shortcode directory.

**Comment by moldcraft** [comment]
You can [enqueue it directly from framework](http://static.md/ac6d066fb18ca88f84e2ad8119fd80b2.png) or download a copy in your theme and enqueue it from there.

**Comment by wpthemes786** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found).
http://localhost/himalayan/wp-content/plugins/unyson/framework/extensions/forms/extensions/contact-forms/shortcodes/contact-form/static/css/style.css?ver=4.2.2

I checked the path there is no css file there. its just not relevant to above question i just checked my console so i have found this error.

**Comment by wpthemes786** [comment]
Fatal error: Call to undefined function fw_get_framework_directory_uri() in D:\xampp\htdocs\himalayan\wp-content\themes\himalayan\functions.php on line 390

Facing this error when put this code into my theme functions file.
if (!is_admin()) {
    wp_enqueue_script(
        'fw-form-helpers',
        fw_get_framework_directory_uri('/static/js/fw-form-helpers.js')
    );
}

**Comment by moldcraft** [comment]
In `functions.php` the framework is not fully loaded yet.
Also you use the `wp_enqueue_script()` function wrong, it should be used on (or after) the `wp_enqueue_scripts` action https://codex.wordpress.org/Function_Reference/wp_enqueue_script#Notes
You should check if `fw_get_framework_directory_uri()` function exists before calling it, in case the user will disable the Unyson plugin, you theme should work without fatal errors.

**Comment by wpthemes786** [comment]
@moldcraft  Thanks. Also i am getting 404 error that there is no css file found at this location and i checked i could not find that file on this location.
http://localhost/himalayan/wp-content/plugins/unyson/framework/extensions/forms/extensions/contact-forms/shortcodes/contact-form/static/css/style.css?ver=4.2.2

**Comment by wpthemes786** [comment]
@moldcraft  Also how to define the location of flash message below contact form fields or above fields

**Comment by wpthemes786** [comment]
@moldcraft  There is no css file in at '/shortcodes/contact-form/static/css/style.css' this location

**Comment by moldcraft** [comment]
I [fixed](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/caa2dd339ba88759af145377bc8e44749f82c8ae) that.

----

> Also how to define the location of flash message below contact form fields or above fields

Overwrite [these functions](https://github.com/ThemeFuse/Unyson/blob/2319dcd074afcb2683446bc32c700cac08061335/framework/static/js/fw-form-helpers.js#L29-L76) and place the messages wherever you want.

**Comment by wpthemes786** [comment]
Hey @moldcraft  could you guide me through or help me to send some example code to worked with ajax form submission. i am not frequently use jquery so could you guide me how to do this. i do not know where to put this piece of code.

jQuery(function(){
    fwForm.initAjaxSubmit({
        //selector: 'form[some-custom-attribute].or-some-class'

        // Open the script code and check the `opts` variable
        // to see all options that you can overwrite/customize.
    });
});

**Comment by moldcraft** [comment]
Put it anywhere you want (in your js file or run it in browser console)
