### ISSUE TITLE
There is a way to disable auto-tags for textarea?

### ISSUE THREAD

**Issue by NazarkinRoman** [ThemeFuse/Unyson#713]
Hello!

If we have some option with `textarea` type and type into it some text with line-breaks, system will automatically add `<br>` and `<p>` tags in this text. 

It there any way to disable this behavior? I need to put into this textarea some HTML & JS code and this code is not working with this tags.

Thanks.

**Comment by moldcraft** [comment]
Hi,
Are you sure it's `textarea` and not [`wp-editor` option type](http://manual.unyson.io/en/latest/options/built-in-option-types.html#wp-editor)?

**Comment by NazarkinRoman** [comment]
@moldcraft `wp-editor` also adding some markup to the output even if `autop` attribute is set to false. :/

**Comment by moldcraft** [comment]
It is in Text mode?

**Comment by NazarkinRoman** [comment]
Hmm. Text mode? How to enable this?

**Comment by moldcraft** [comment]
![s](http://static.md/2b785010addca6a90e7199ad8fbd95fb.png)

**Comment by NazarkinRoman** [comment]
Yes, in text mode it also adds markup. My settings:
```
$options = array(

	'code' => array(
		'type'  => 'wp-editor',
		'label' => __('HTML', 'fw'),
		'tinymce' => true,
		'media_buttons' => false,
		'teeny' => true,
		'wpautop' => false,
		'reinit' => false,
		'size' => 'large', // small | large
	)

);
```

It is a shortcode settings. I use them in view via `$atts['code']`.

**Comment by llemurya** [comment]
@NazarkinRoman  why you don't use simple [textarea](http://manual.unyson.io/en/latest/options/built-in-option-types.html?highlight=textarea#textarea) option-type, textarea don't add `<p>` or `<br/>` tags?I tested and in database is everything clear.

**Comment by llemurya** [comment]
@NazarkinRoman please answer if it helps and close the issue?

**Comment by NazarkinRoman** [comment]
Hi again. Thanks for assistance, but this problem is still exists when I use `textarea` option type. 

Let me explain: I am trying to implement simple page builder shortcode that just will display my HTML code and no more :) I've tried to use `wp-editor`(explained above) and `textarea` as well, but in view file under `$atts` variable I am getting a value with markup anyway..

**Comment by llemurya** [comment]
@NazarkinRoman yes you are right, @moldcraft fixed it in [this commit](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/69c5583d32b2cd6b41ecbc0a7c102f0485d25397) .You can wait for the new extension release, or you can do it manually, the instructions how to do this is are on the [next link](http://sourcebox.io/74202a88bba20688ebba3f4474ca037d/markdown).
