### ISSUE TITLE
Rich Text Editor - cannot use Visual tab when used in shortcodes

### ISSUE THREAD

**Issue by martin-bede** [ThemeFuse/Unyson#714]
When using the Rich Text Editor in a shortcode only the Text tab can be used. It does work when used in Theme Settings however.

Looks like the error is `Uncaught TypeError: Cannot read property 'canvas' of undefined`.

**Comment by llemurya** [comment]
@martin-bede please read our [documentation](http://manual.unyson.io/en/latest/options/built-in-option-types.html#wp-editor).If you set `'reinit' => true` it will works.

**Comment by llemurya** [comment]
@martin-bede please answer if it helps and close the issue. Thanks!

**Comment by martin-bede** [comment]
That's great thank you :)
