### ISSUE TITLE
Unyson Page Builder Plugin is not Working

### ISSUE THREAD

**Issue by dbubello** [ThemeFuse/Unyson#715]
Hi there, I am using the GIST WP theme and i have activated Unyson plugin v2.3.3, and its not working, see URL below.

http://nollywoodworkshops.org

Any idea as to why? The Theme developer is under the impression it is working fine, any help would be appreciated.

Dean

**Comment by moldcraft** [comment]
Is the PageBuilder extension active?

**Comment by dbubello** [comment]
Yes it is

**Comment by dbubello** [comment]
Sorry, I Meant GRAND WP theme!

**Comment by moldcraft** [comment]
Can you give me access to your site (admin and ftp details) ? Send them to `moldcraft[at]email.com`

**Comment by dbubello** [comment]
Jest sent you via email

**Comment by moldcraft** [comment]
I can't log in. The admin password is wrong. Please send again a working password.

**Comment by moldcraft** [comment]
I see that the site is working now. Is this fixed?

**Comment by dbubello** [comment]
WTF?? It is fixed....I have no idea why?! OK well sorry for bothering you!

On Tue, Jul 7, 2015 at 4:15 PM, moldcraft <notifications@github.com> wrote:

> I see that the site is working now. Is this fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/715#issuecomment-119321837>.
>



-- 

*Dean Bubello*
*Owner, Creative Director*

6 Lamphere Circle  |  Framingham, MA 01701
*rwbstudio.com <http://rwbstudio.com>*  |  508-656-0494
Twitter: @DeanBubello
Facebook: /RedwhiteblueStudio <http://www.facebook.com/RedwhiteblueStudio>

**Comment by moldcraft** [comment]
No problem. We are here to help.

**Comment by dbubello** [comment]
thanks again.

On Tue, Jul 7, 2015 at 4:18 PM, moldcraft <notifications@github.com> wrote:

> No problem. We are here to help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeFuse/Unyson/issues/715#issuecomment-119323140>.
>



-- 

*Dean Bubello*
*Owner, Creative Director*

6 Lamphere Circle  |  Framingham, MA 01701
*rwbstudio.com <http://rwbstudio.com>*  |  508-656-0494
Twitter: @DeanBubello
Facebook: /RedwhiteblueStudio <http://www.facebook.com/RedwhiteblueStudio>
