### ISSUE TITLE
Published page error after data is entered by user and send 

### ISSUE THREAD

**Issue by ramshinde** [ThemeFuse/Unyson#716]
Invalid destination email (please contact the site administrator)

Hi

Tried activating/deactivating plugins and adding/removing widgets.. setup email using WP SMTP mail plugin but the error continues .. also can someone help me where the data is residing after send button 

Website is simple with 6 boxes and contact form  like name , surname, phone number and e mail id etc..

**Comment by moldcraft** [comment]
Destination email is set here

![s](http://static.md/4d766f1db4485524b6d7d5a1211ab49b.png)

> also can someone help me where the data is residing after send button

more details please

**Comment by ramshinde** [comment]
thanks .. it worked but now gives "Oops something went wrong" error. i am just a user and not a IT person and do not know programming

**Comment by ramshinde** [comment]
using postman SMTP and test outgoing mail is OK

**Comment by moldcraft** [comment]
Select with the mouse "Oops something went wrong ....." and you should see a hidden message.

![s](http://static.md/2c9eec686b2c7a4aa8c4ccffafe93d34.png)

for e.g. this means that SMTP details are wrong.

> setup email using WP SMTP mail plugin

Contact form doesn't communicate with that plugin, it has its own SMTP settings

![s](http://static.md/98e2ed9b3ea7e2b9cd9a354df6c7a768.png)

**Comment by ramshinde** [comment]
Yes.. it is SMTP.. smtp.gmail.com.. no secure connection SMTP port 465

**Comment by ramshinde** [comment]
thnaks .. it worked
