### ISSUE TITLE
How to switch of page refresh after form submit?

### ISSUE THREAD

**Issue by qiip** [ThemeFuse/Unyson#717]
I am using Contact Form 7 instead instead standart unyson form. Contact Form 7 use ajax and there is no need to reload page, but some of unyson scripts triger the refresh of the page and when user clicks on "Submit" button page is reloading. Maybe some one know, where can I switch of this thing?

**Comment by moldcraft** [comment]
[This](http://manual.unyson.io/en/latest/helpers/php.html#ajax-submit) script is used to make Unyson forms ajax submittable. It doesn't make page refresh, [it replaces the form html with a success message](https://github.com/ThemeFuse/Unyson/blob/74cb4a6eff06d62352d4a24420b5ac787a031cb8/framework/static/js/fw-form-helpers.js#L63-L71). But I don't which theme are you using, perhaps it has a custom script (or the above script with modified parameters) and it makes page refresh.

Which theme are you using, or you are building your own theme?
How can I reproduce this problem?

**Comment by qiip** [comment]
Hello moldcraft,


Thank you for your help. The problem reproduce only when I use Contact Form 7 in unysone page builder block.
I'm using this theme - http://themeforest.net/item/-webapp-app-saas-wordpress-theme/11139630
You can reproduce this problem on the website http://www.test.taxionfly.com/, click on button Contact Form 7 on the mane page.

**Comment by moldcraft** [comment]
It seems that this is fixed

![](https://static.md/bdeb6ad93d3b5bcb3a3eb6020db731e8.png)

There was no refresh after the form was submitted.

**Comment by qiip** [comment]
No, all problem fixed, I have used a modal window, not a popover.
