### ISSUE TITLE
How to install Unyson theme on wordpress

### ISSUE THREAD

**Issue by Rishabhgoyal17** [ThemeFuse/Unyson#719]
There is an error while i am uploading the theme at wordpress

Below is the text of the error:
"
Installing Theme from uploaded file: unyson (1).zip
Unpacking the package…
Installing the theme…
The package could not be installed. The theme is missing the style.css stylesheet.
Theme install failed.
"
Below is the screenshot of the error:

![image](https://cloud.githubusercontent.com/assets/13250627/8589763/5fafab24-2637-11e5-9419-4537c7645401.png)

**Comment by Rishabhgoyal17** [comment]
I need to install the theme for an existing domain

**Comment by duongancol** [comment]
where you download unyson.zip? I guess that it's plugin, not theme
