### ISSUE TITLE
Blog post formats support?

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#721]
Hi,

Does the framework handle any of the blog post formats such as audio or video?
I can't seem to see anything in the docs.

If not, is there planned support for it anytime soon or should I roll my own solution?

Thanks

**Comment by duongancol** [comment]
You can use Unyson option in Blog post as Metabox, and create any post formats. For example, creating post.php in framework_customizations/theme/options/posts/
```php
<?php
	/**
	 * Option metabox for Blog post
	 * @var array
	 */
	$options = array(
	    'pf-video' => array(
			'type'     => 'box',
			'title'    => __('Video', 'mauris'),
			'priority' => 'high',
			'attr'    => array('class' => 'custom-class', 'data-foo' => 'barrr'),
			'options'  => array(
				'youtube' => array(
					'type' => 'short-text',
					'label' => __('Youtube Video', 'mauris'),
					'desc' => __('Paste ID of the video here', 'mauris'),
					"help" => __("Just paste the bold part of the video's URL: https://www.youtube.com/watch?v=<b style='color: yellow;'>4SYlLi5djz0</b>","mauris")
				),
				'vimeo' => array(
					'type' => 'short-text',
					'label' => __('or Vimeo Video', 'mauris'),
					'desc' => __('Paste ID of the video here', 'mauris'),
					"help" => __("Just paste the bold part of the video's URL: https://vimeo.com/channels/staffpicks/<b style='color: yellow;'>121428012</b>","mauris")
				),
			)
	    ),
     );
```

**Comment by pear1** [comment]
Hello, 

I've just tested your code, but I can't create a metabox which would show only for a **video** blog post format. This code shows up for every selected blog post format.

**Comment by moldcraft** [comment]
We don't have such functionality. I don't think we will do something like that.
