### ISSUE TITLE
How to call option on front-end?

### ISSUE THREAD

**Issue by nickostyle** [ThemeFuse/Unyson#723]
Hi, and thanx for this framework.

I have read docs, but i dont understand how to call option from template? I have option that changes container background image

```php
if ( function_exists( 'fw_get_db_settings_option' ) ) {
	$header_bg_img           = fw_get_db_settings_option( 'h_c_bg_image_option' );
}

<style>
<?php if ( ! empty ( $header_bg_img ) ) : ?>
	.site-header { background-image: url(<?php echo $header_bg_img['url'] ?>); } 
<?php endif; ?>
</style>
```

And it works fine! 

But next option must add background-size: cover depends on switch position
Here is option code

```php
// Background image cover option
'h_c_bg_image_cover_option' => array(
      'label' => __( 'Background image 100% cover', 'unyson' ),
      'desc'  => __( 'Choose "Yes" to have the header background image display at 100% in width and height and scale according to the browser size.', 'unyson' ),
      'type'  => 'switch',
      'left-choice' => array(
           'value' => 'disable',
           'label' => __('No', 'fw'),
        ),
       'right-choice' => array(
            'value' => 'enable',
            'label' => __('Yes', 'fw'),
          ),
),
```

Im trying to call it in template

```php
<?php   if ( function_exists( 'fw_get_db_settings_option' ) ) {
$header_bg_img_cover     = fw_get_db_settings_option( 'h_c_bg_image_cover_option' );
}
?>

<?php if ( $header_bg_img_cover['right-choice'] ) : ?>
	.site-header { background-size: cover; } 
<?php endif; ?>
```

And nothing! What i do wrong?

**Comment by llemurya** [comment]
@nickostyle can you set the second parameter of the `fw_get_db_settings_option` for example 
```php
$tmp = fw_get_db_settings_option( 'h_c_bg_image_cover_option' , 'default_value');
fw_print($tmp);
```
If you obtain the `default_value` string, this means that the options is not saved in database.

**Comment by llemurya** [comment]
@nickostyle please answer in order to resolve this issue.

**Comment by nickostyle** [comment]
i got "Disable"! But what doest it mean?

**Comment by llemurya** [comment]
It means the value of the option
```php
'h_c_bg_image_cover_option' => array(
      'label' => __( 'Background image 100% cover', 'unyson' ),
      'desc'  => __( 'Choose "Yes" to have the header background image display at 100% in width and height and scale according to the browser size.', 'unyson' ),
      'type'  => 'switch',
      'left-choice' => array(
           'value' => 'disable',
           'label' => __('No', 'fw'),
        ),
       'right-choice' => array(
            'value' => 'enable',
            'label' => __('Yes', 'fw'),
          ),
),
```
You set  value `disable` of the `left-choice` and value `enable` of the `right-choice`.You must change your if statement
```php
<?php if ( $header_bg_img_cover === 'enabled' ) : ?>
    .site-header { background-size: cover; } 
<?php endif; ?>
```
Please say if it helps and close the issue.

**Comment by nickostyle** [comment]
i did the same, i told u it doesnt work

code

<style>
<?php if ( $header_bg_img_cover === 'enabled' ) : ?>
		    .site-header { background-color: #ea3838; } 
		<?php endif; ?>
</style>

do nothing.

**Comment by llemurya** [comment]
@nickostyle it is a normal behavior that it doesn't work because you have the value `disable` in the `$header_bg_img_cover`,You must change value to `enable` and save it  and it will works, or If you want to work on `disabled` change the `value` in `if statement`.
```php
<?php if ( $header_bg_img_cover === 'disable' ) : ?>
    .site-header { background-size: cover; } 
<?php endif; ?>
```

**Comment by llemurya** [comment]
@nickostyle please answer and close the issue.
