### ISSUE TITLE
TRANSLATE Module Crashed my site

### ISSUE THREAD

**Issue by ariehwagner** [ThemeFuse/Unyson#724]
I added the TRANSLATION module to my UNYSON platform.
Now I can not access WP admin any longer.

Any help?
thanks

www.starguest.com

**Comment by moldcraft** [comment]
Put this code in `{theme}/functions.php`: 

```
delete_option('fw_active_extensions');
```

Refresh the page, then delete it.

**Comment by ariehwagner** [comment]
WOW! Thanks for the super fast response!
I wil try and do this .... I am no expert in this....so I need to ask someone for help...

many thanks!!!

**Comment by ariehwagner** [comment]
I did what you asked me to do.
Now the site is back up. 

Resulting Problem: 
PORTFOLIO Elements (In Theme: EXPOSURE)  don't work any longer. 

See: 
http://starguest.com/project/the-grove-2/

Would you know why?

**Comment by ariehwagner** [comment]
It started working again!

**Comment by llemurya** [comment]
@ariehwagner can you provide an ftp details at dev-team@unyson.io in order to inspect the bug from Translation Extension.Thanks.

**Comment by ariehwagner** [comment]
sent
