### ISSUE TITLE
Warning message in metaboxes

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#725]
Hello, 

I am using metaboxes in the pages, but there is a warning message:

**Output:**
Label
Warning: htmlspecialchars() expects parameter 1 to be string, array given in C:\Web\www\wp-content\plugins\unyson\framework\helpers\general.php on line 914
Description

**Code:**
```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}
$options = array(
    'page-tab-blog' => array(
        'type'     => 'box',
        'title'    => __('Test', 'fw'),
        'priority' => 'high',
        'options'  => array(
            'page-blog' => array(
                'type'  => 'select',
                'value' => 'choice-3',
                'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
                'label' => __('Label', 'fw'),
                'desc'  => __('Description', 'fw'),
                'help'  => __('Help tip', 'fw'),
                'choices' => array(
                    '' => '---',
                    'choice-1' => __('Choice 1', 'fw'),
                    'choice-2' => array(
                        'text' => __('Choice 2', 'fw'),
                        'attr' => array('data-foo' => 'bar'),
                    ),
                    array( // optgroup
                        'attr'    => array('label' => __('Group 1', 'fw')),
                        'choices' => array(
                            'choice-3' => __('Choice 3', 'fw'),
                            // ...
                        ),
                    ),
                ),
                /**
                 * Allow save not existing choices
                 * Useful when you use the select to populate it dynamically from js
                 */
                'no-validate' => false,
            )
        )
    ),
);
```

**Comment by llemurya** [comment]
@pear1 please watch [this video](https://youtu.be/HmHhWwPa34Q). It is a proof that everything works well.Please see maybe you have other options that generate this error message.I'am waiting for your response.

**Comment by pear1** [comment]
Hello, 

I paste this code under page.php file not post.php

**Comment by llemurya** [comment]
@pear1 I will test it in `page.php` and I'll give you an answer.

**Comment by llemurya** [comment]
@pear1 I tested, it works, please see [this video](https://youtu.be/9HgrsN2cl9I).Please make an screencast how to reproduce it , because for me it works.

**Comment by pear1** [comment]
This issue appears when the option type is saved with some kind of value, but after the theme update the option type is change to something other, for example slider is changed to typography.

**Comment by llemurya** [comment]
@pear1 If you change for example an option-type `typography` to `slider` and the key name of the option-type remains the same you will got the error, in this case you must change not only option-type but the key name of the option.
