### ISSUE TITLE
HELP: style.css stylesheet missing???

### ISSUE THREAD

**Issue by RoyalTer** [ThemeFuse/Unyson#727]
I'm using SiteGround hosting with the WordPress plugin. After I downloaded the Unison zipfile to my computer and then tried to upload it to my dashboard (Appearance> Add New Theme> Upload Theme), I keep getting the error message that says "The package could not be installed. The theme is missing the style.css stylesheet." This is my first time even dealing with both SiteGround and WordPress. I'm trying to teach myself. Maybe I'm doing it wrong. I NEED HELP!!!

**Comment by moldcraft** [comment]
unyson is a plugin not a theme

**Comment by RoyalTer** [comment]
I'm just ready to started building my site. Can you please tell me how do I get to that point? I've activated the Unyson plugins? Is there a theme that I use with it?
Thanks

**Comment by moldcraft** [comment]
1. Install [the plugin](https://wordpress.org/plugins/unyson/) from your admin Plugins page.
2. Read [the documentation](http://manual.unyson.io/)
