### ISSUE TITLE
Cannot download the Unyson Framework

### ISSUE THREAD

**Issue by jmaucvdg** [ThemeFuse/Unyson#733]
Installation says that is no style.css archive on zip file. What can I do? I´m new in wordpress :(

**Comment by duongancol** [comment]
Please go to wp-admin -> Plugins -> Upload. Unyson is plugin. It's not a theme. I think you should learn more about wordpress, especially theme and plugin before working with Unyson.

**Comment by jmaucvdg** [comment]
Hehehehe told you I´m new with wordpress!! :P Thank you very much! I promise to learn a lot. Cheers!
