### ISSUE TITLE
Multi-upload option is not working

### ISSUE THREAD

**Issue by maryslen** [ThemeFuse/Unyson#734]
Hi,
I've tested Multi-upload option in Portfolio extension and even tried to add this option as an option to custom posts: upload option appear but i can select only one image. No 'multi' feature. Any ideas how to fix this?

Thank you

**Comment by llemurya** [comment]
@maryslen please watch [this video](https://youtu.be/wHCzreqT90M).It works.You must press the `ctrl` key and click on the images.
