### ISSUE TITLE
How to active unyson shortcodes without the page? read more -->

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#735]
I am retrieveing the content from a other custom post type. The page is built with Unyson there but i want to change the main the_content of only the homepage with that unyson shortcode content in the custom post type but if i apply_filter or do do_shortcode, i get nothing but a error

**Comment by nickkuijpers** [comment]
***
$newcontent = get_post_field('post_content', NIKU_WEBSITEID);
$newcontent = apply_filters('the_content', $newcontent );
$newcontent = do_shortcode( $newcontent );
***

**Comment by moldcraft** [comment]
Which error?

**Comment by nickkuijpers** [comment]
It won’t display anything, no error nothing. not even in de php logs. Just a white screen of ...

Vanaf maandag 20 juli’15 tot en met vrijdag 14 augustus'15 voeren wij geen programmering werkzaamheden uit wegens vakantie. Indien aanwezigheid van storing wordt u vriendelijk verzocht hier melding van te maken doormiddel van een sms te versturen naar het telefoonnummer: 06-26967629 waarbij u kort uitlegt wat de storing is en waar deze zich plaatsvindt. Onze servers worden 24/7 gemonitord. Heeft u even geduld voordat u de melding verstuurt zodat u zeker weet dat dit een aanhoudende storing is. Is uw website off-line? Controleer of deze storing alleen voor u van toepassing is doormiddel van de volgende website te gebruiken: http://ishetonline.nl <http://ishetonline.nl/>.

**Comment by moldcraft** [comment]
If Unyson is disabled, that `do_shortcode()` works?

**Comment by nickkuijpers** [comment]
Yep, even when i just remove the content and put in "testcontent" as hardcoded. So when loading the content string with the shortcodes in it, it bugs.

**Comment by moldcraft** [comment]
Can you give me the exact steps how to reproduce this?

*I tried `echo do_shortcode( '[button label="Hello"]' );` and it works.*

**Comment by nickkuijpers** [comment]
I have a custom post type, called Websites.

At those custom post type i’ve created a post “Test.nl <http://test.nl/>”. In Test.nl <http://test.nl/>, i have placed multiple shortcodes and grids in the main content area.

I’ve put the following content in the homepage of the normal custom post type “Pages”: {{replacecontent}}

I have replaced that {{replacecontent}} with the content of the Test.nl <http://test.nl/> so i can show different content for each domain. Then the error comes.

Vanaf maandag 20 juli’15 tot en met vrijdag 14 augustus'15 voeren wij geen programmering werkzaamheden uit wegens vakantie. Indien aanwezigheid van storing wordt u vriendelijk verzocht hier melding van te maken doormiddel van een sms te versturen naar het telefoonnummer: 06-26967629 waarbij u kort uitlegt wat de storing is en waar deze zich plaatsvindt. Onze servers worden 24/7 gemonitord. Heeft u even geduld voordat u de melding verstuurt zodat u zeker weet dat dit een aanhoudende storing is. Is uw website off-line? Controleer of deze storing alleen voor u van toepassing is doormiddel van de volgende website te gebruiken: http://ishetonline.nl <http://ishetonline.nl/>.

**Comment by moldcraft** [comment]
Can you give me FTP and admin details so I can debug your code?

**Comment by nickkuijpers** [comment]
Hi, Sorry im on holiday now, will do in one month!

Vanaf maandag 20 juli’15 tot en met vrijdag 14 augustus'15 voeren wij geen programmering werkzaamheden uit wegens vakantie. Indien aanwezigheid van storing wordt u vriendelijk verzocht hier melding van te maken doormiddel van een sms te versturen naar het telefoonnummer: 06-26967629 waarbij u kort uitlegt wat de storing is en waar deze zich plaatsvindt. Onze servers worden 24/7 gemonitord. Heeft u even geduld voordat u de melding verstuurt zodat u zeker weet dat dit een aanhoudende storing is. Is uw website off-line? Controleer of deze storing alleen voor u van toepassing is doormiddel van de volgende website te gebruiken: http://ishetonline.nl <http://ishetonline.nl/>.
