### ISSUE TITLE
The package could not be installed. The theme is missing the style.css stylesheet

### ISSUE THREAD

**Issue by taggsfam** [ThemeFuse/Unyson#736]
I get this error when I try and load the Unyson Theme to WordPress:
Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme install failed.

Any help?
Mike
taggsfam@gmail.com

**Comment by moldcraft** [comment]
There is no Unyson Theme. Unyson is a plugin.

**Comment by taggsfam** [comment]
Ugh...I found it on a "best of" wordpress site and it was free.
I am new to the wordpress deal and I am looking for a nice/quality free theme to learn and play with. Some are very learn and understand. Any suggestions?

**Comment by moldcraft** [comment]
Try this https://github.com/ThemeFuse/Scratch-Theme

**Comment by taggsfam** [comment]
I get the same error.

**Comment by moldcraft** [comment]
Can you upload and extract the zip via FTP? Or if it's on your localhost, extract it in `wp-content/themes`

**Comment by taggsfam** [comment]
I am logged in my WordPress site through my browser:
http://www.xxxxxxxxxx.com/wordpress/wp-admin
I am trying to add it the "normal" way through the WP site.
