### ISSUE TITLE
Portfolio - Categories Menu Issue

### ISSUE THREAD

**Issue by rodowns** [ThemeFuse/Unyson#738]
Hey there 

Site: http://easterngautengchamber.test.afrihost.com/
Click on forums(portcat)
Then I get this error since the last update ....

Catchable fatal error: Argument 2 passed to fw_ext_portfolio_get_sort_classes() must be of the type array, string given, called in /home/easteyve/public_html/wp-content/themes/vGlacier/framework-customizations/extensions/portfolio/views/archive.php on line 13 and defined in /home/easteyve/public_html/wp-content/plugins/unyson/framework/extensions/portfolio/helpers.php on line 65

Help appreciated ??

In fact, even when I create a page unsing the PORTFOLIO GRID it seems to function for the first two Items in the category but after that none of the items (categories) function. If you click on them they show nothing ....

Please help ....What do you need from me ??

**Comment by moldcraft** [comment]
Hello,
sorry for very late reply.

Address this question to vGlacier theme developer. I can't find in unyson useages of the `fw_ext_portfolio_get_sort_classes()` function.
