### ISSUE TITLE
ALL GRAY - No options to add anything

### ISSUE THREAD

**Issue by taggsfam** [ThemeFuse/Unyson#739]
I am just starting out, I finally got the Scratch Theme loaded and (thought) working. Started with a new page, went to media elements and added an image. I click on the image to pick one and it goes gray, it never flips the the option to add an image. I see it in the window behind the grayish looking overlay, but I can't click image and add anything.

**Comment by moldcraft** [comment]
I can't reproduce this. https://vid.me/JKV5

> I click on the image to pick one and it goes gray

That popup for picking and uploading images comes from WordPress, not from Unyson. Maybe your `wp-content/uploads` directory is not writable or something. Try to look in apache `error.log`, maybe there is an error.

**Comment by taggsfam** [comment]
one of the other themes I used (and the basic wordpress site) I am able to upload and pick an image easily. This is the first time I am unable to do anything with images.

**Comment by moldcraft** [comment]
I need a way to reproduce this, or an error message.

**Comment by taggsfam** [comment]
No error message, just gray screen....sticks on gray screen.

**Comment by taggsfam** [comment]
GRRRR...I can not attached an image or drag it in.

**Comment by llemurya** [comment]
@taggsfam can you see in the browser dev tool what error is in the console?

**Comment by taggsfam** [comment]
![screen shot 2015-07-20 at 8 43 27 am](https://cloud.githubusercontent.com/assets/13405239/8777180/f4abdb30-2ebb-11e5-91d5-6ab61aa11203.jpg)

**Comment by taggsfam** [comment]
Still very new to this...not sure what/where the browser dev tool is.

**Comment by llemurya** [comment]
@taggsfam can you give us an ftp details , send an email to the dev-team@unyson.io in order to inspect this bug.Thanks.

**Comment by taggsfam** [comment]
give you my FTP info??? Log and pass???

**Comment by moldcraft** [comment]
How else can we help if we can't reproduce the problem? and you can't inspect it yourself...

Browser dev tool is: Press `F12`, goto to `Console` tab. Tell us if you see any error there.

**Comment by taggsfam** [comment]
![screen shot 2015-07-20 at 7 00 05 pm](https://cloud.githubusercontent.com/assets/13405239/8790278/ad5aeb08-2f11-11e5-8296-b8c812a4962c.png)

**Comment by taggsfam** [comment]
Nothing listed.

**Comment by llemurya** [comment]
@taggsfam can you disable all plugins and enable the Unyson. See if the problem persists? I'am waiting for your response.

**Comment by taggsfam** [comment]
BINGO!!!!! That did it!!!! :) Thank you!!!
