### ISSUE TITLE
How to remove 'Project Gallery' meta box on project edit screen?

### ISSUE THREAD

**Issue by blackmekemeke** [ThemeFuse/Unyson#74]
I want to replace 'Project Gallery' meta box with my own custom meta box. Thanks

**Comment by danyj** [comment]
info above is wrong , this is a filter now
https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/master/class-fw-extension-portfolio.php#L227

 not an action so to remove it you should use 


	/**
	 * Remove portfolio project "Project Gallery" metabox
	 */
	function fw_remove_portfolio_project_gallery_metabox() {
		remove_filter( 'fw_post_options', array( fw()->extensions->get( 'portfolio' ), '_filter_admin_add_post_options' ) );
	}
	
	add_action( 'init', 'fw_remove_portfolio_project_gallery_metabox' );
