### ISSUE TITLE
What does fw_collect_options do ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#740]
Just like title says, can you please explain what doe the fw_collect_options do. 
Thnx!

**Comment by moldcraft** [comment]
You give it an array of options (multi level arrays, with any option and container) and it returns you

```
'id' => array(/* option */),
'id' => array(/* option */),
...
```

You can put limits, for e.g.:
* Return only type `text` and `select` options
* Return only type `box` containers
* Return only type `textarea` options from the first level array

It's a replacement for `fw_collect_first_level_options()` and `fw_extract_only_options()`.
[Here](https://github.com/ThemeFuse/Unyson/blob/c6604d6787cf8219a8e66584a4b7246f7d41a7f8/tests/unit/main.php#L23-L356) are the tests.
