### ISSUE TITLE
Addable-Box : [Ajax Error] Wrong options

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#742]
Hello,

With the latest update I got issues with all the `addable-box` options in my theme & extensions. All was working fine and now I go this : 
![theme_settings_ _woffice_dev_ _wordpress](https://cloud.githubusercontent.com/assets/5446124/8795121/51dfc07c-2f8a-11e5-8e6f-bf4a16f5a8de.jpg)

I've seen that : https://github.com/ThemeFuse/Unyson/issues/631

But I can't find any update in the documentation about it and I think that's there is another issue somewhere ... 

Here is one the declaration 

```
'funfacts' => array(
					    'type'  => 'addable-box',
					    'value' => array(
					        array(
					            'fact_content' => 'Anything you like here...',
					            'fact_icon' => 'fa-star',
					        )
					    ),
					    'label' => __('Fun facts', 'woffice'),
					    'desc'  => __('They will be displayed as in a slider within the widget, you can use for any other purpose than fun facts.', 'woffice'),
					    'box-options' => array(
					        'fact_content' => array(
					        	'type' => 'textarea',
					        	'title'   => __( 'Content', 'woffice' ),
					        ),
					        'fact_icon' => array(
					        	'type' => 'icon',
					        	'title'   => __( 'Icon', 'woffice' ),
					        ),
					    ),
						'template' => 'Item', // box title
					    'box-controls' => array( // buttons next to (x) remove box button
					        'control-id' => '<small class="dashicons dashicons-smiley"></small>',
					    ),
					    'limit' => 18, // limit the number of boxes that can be added
					)
```

Please keep me updated all these options are broken for now ... Let me know if you need more details.

Best regards

2F

**Comment by duongancol** [comment]
Hi @moldcraft My client site got this error and it's solved when they updated Unyson to the latest version. The problem is all data that saved in addable-box before were lost. Is there any way to get it back?

**Comment by moldcraft** [comment]
Sorry, no.
