### ISSUE TITLE
Add options to slider shortcode?

### ISSUE THREAD

**Issue by tuputupu** [ThemeFuse/Unyson#743]
Hi,

How can I add new options to slider shortcode? If I add options in options.php they appear in the slider shortcode but how can I echo it out in slider/extensions/owl-carousel/views/owl-carousel.php?

**Comment by llemurya** [comment]
@tuputupu you must add options to `slider/extensions/owl-carousel/options/options.php` but it will rendered on the Slider Add / Edit pages, in the shortcode only shows the sliders what was created.Read our documentation about [options in slider](http://manual.unyson.io/en/latest/extension/slider/index.html?highlight=slider#options).I'am waiting for a response.

**Comment by tuputupu** [comment]
Thnx, I'll do it that way.
