### ISSUE TITLE
redeclare class ReCaptchaResponse

### ISSUE THREAD

**Issue by thanhluu** [ThemeFuse/Unyson#744]
I'm using another plugin with the same `ReCaptchaResponse` class and I got this error:
> Fatal error: Cannot redeclare class ReCaptchaResponse in /.../wp-content/plugins/unyson/framework/extensions/forms/includes/option-types/form-builder/items/recaptcha/includes/ReCaptcha/Response.php on line 31

Can you check.
Thanks

**Comment by llemurya** [comment]
@thanhluu can you say what plugin you use in order to reproduce this bug ,please give us a link.Thanks.

**Comment by moldcraft** [comment]
It doesn't matter.
Many plugins can include ReCaptcha library, better to check `if (class_exists('...'))` before including the file with class.

**Comment by thanhluu** [comment]
Yes I think so. The plugin was conflict with Unyson is EDD Frontend Submissions

**Comment by wtfiwtz** [comment]
https://github.com/mcguffin/wp-recaptcha-integration/issues/49
