### ISSUE TITLE
Extensions are deactivating every 2 days

### ISSUE THREAD

**Issue by McCABRUS** [ThemeFuse/Unyson#745]
Hi, I bought a Wordpress theme (Exposure by ThemeFuse) with the Unyson plugin.

The extensions are deactivating every day or every 2 days and I don't know why, I have to download and re-activate every single extensions of my webpage (christianbodensiek.com) because without those extensions my page is useless, what can I do?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-123617458
