### ISSUE TITLE
Customize column class for responsive design

### ISSUE THREAD

**Issue by thanhluu** [ThemeFuse/Unyson#746]
Is there a way to customize the column class as follows:
For desktop, I set the column width: 2/3 - 1/3
For tablet, I wish to have the columns width: 1/2 - 1/2
Kindly advice. Thanks!

**Comment by moldcraft** [comment]
You can overwrite [this array](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/config.php#L13) via [this filter](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/helpers.php#L22).
