### ISSUE TITLE
Pre-Built

### ISSUE THREAD

**Issue by taggsfam** [ThemeFuse/Unyson#747]
SO...I am still learning and working in Wordpress, I love your theme and want to continue to use it. One question though, are there pre-build pages you can load in, something already done that I can then update with my info/pictures? Is that even possible in WP?

I have a couple sites that are old and need updating, and I need to get them out fast. I'd like to just move the info into pages that are already created to save on time. 

Possible?

Thanks again for the time and help.
Mike

**Comment by moldcraft** [comment]
Unyson has Demo install, it works like this:

* You have a theme with customized default shortcodes, also it can contain custom/new shortcodes
* You build some pages with shortcodes, configure them
* Then you create a demo install to give it someone else

The install process works like this:

* It creates a full backup of your site
* It deletes everything on site and replace it with demo contents

----

Try WordPress default export tool `/wp-admin/export.php`. I am not familiar with it and I can't say if it will work fine with pages made with builder.

----

If it will not work, try to search a plugin that does what are you looking for.
