### ISSUE TITLE
Shortcodes inside text block shortcode

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#748]
We have a default shortcodes in page builder but we cant add any additional shortcodes inside the text block. 
I need to add special heading , testimonial , blockqote inside of that text block. 

Currently none of that is possible since the editor does not give me the option to add those 

Desired outcome 
http://prntscr.com/7vpzlo

current setup

http://prntscr.com/7vpzs4

http://prntscr.com/7vpzyc

this is where we need shortcodes  http://prntscr.com/7vq0h7

**Comment by danyj** [comment]
Yes I can brake it apart but it just seems like common sense the second you see the editor in there

**Comment by albertso** [comment]
This would be useful for all textareas like the ones in accordions and tabs.

**Comment by danyj** [comment]
@albertso yes , when shrotcodes were introduced we original thought that this would be the case. but they are still bound to page builder only.

**Comment by Alex-Ascet** [comment]
+1

**Comment by c0sm1n87** [comment]
This would be useful :+1:

**Comment by danyj** [comment]
@c0sm1n87  #756 , is coming
