### ISSUE TITLE
What is the shortcode tag for special-heading?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#749]
I am using this action  to output  dynamic CSS 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/3c8461e70192a0ff9d391f411a81a70353eaee59/class-fw-extension-shortcodes.php#L154

in shortcodes/hooks.php 

it works perfect for columns  and sections 

	add_action('fw_ext_shortcodes_enqueue_static:column','_thz_column_in_css');

but seems like it does not work for special-headings

	/*
		custom css for special headings
	
	*/
	function _thz_special_heading_css($data) {
	
		$atts = _thz_shortcode_options($data);
		
		fw_print($data);
		
		
	}
	
	add_action('fw_ext_shortcodes_enqueue_static:special-heading','_thz_special_heading_css');

this is not outputting anything

**Comment by moldcraft** [comment]
WordPress shortcodes can't contain the `-` character. Try `special_headings`.

**Comment by danyj** [comment]
I did , tried all 

underscore , without underscore but no go

**Comment by danyj** [comment]
works 

    special_heading
