### ISSUE TITLE
Preview does not work again

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#752]
Not sure if anyone has noticed but after the first time page save the preview does not work at all. 

Try it with scratch theme ,
 add new page 
add section 
add special heading 

click preview it works 
http://prntscr.com/7w2o5c

publish that page , close the preview tab 
change the special heading title
http://prntscr.com/7w2nzt

hit preview 
no change

**Comment by danyj** [comment]
@moldcraft   here is video  http://screencast.com/t/nxzFV6uNyli

I tested with different install/pages and it seems like some pages work and some dont.

**Comment by moldcraft** [comment]
Please download the latest [PageBuilder](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension) extension and test this.

**Comment by danyj** [comment]
@moldcraft  on it

**Comment by danyj** [comment]
@moldcraft  seem ok now!

**Comment by danyj** [comment]
I'l reopen this one since it is same issue, while the builder preview works now ,  
the  page option change or template change does not work , 

see this please 
http://screencast.com/t/lJYJDiMNqqt

I emailed you the new scratch with blank template and page option so that you can test

**Comment by danyj** [comment]
@moldcraft  tested but still does not work for me 
see this , switch between templates
http://screencast.com/t/M0sH5XqjKkM

**Comment by moldcraft** [comment]
The **Template** has nothing with Unyson. You can open an issue in [WordPress bug tracker](https://core.trac.wordpress.org/).

**Comment by danyj** [comment]
Sorry but it appears it does , I tested twentytwelve , avada , enfold , divi , X , _s  and on all of them the template preview works , if I use Unyson scratch the template preview does not work as well as mine.

In template I have this  

    Template Name: name of the template

same as everyone else.

**Comment by moldcraft** [comment]
I tested with "Twenty Fifteen" theme, with Unyson disabled. And the Template select doesn't work with Preview https://vid.me/nUfd
