### ISSUE TITLE
wp-editor option missing tiny mice

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#753]
'text' => array(
		'type'  => 'wp-editor',
		'value'	=> 'This is text before',
		'tinymce' => true,
		'teeny' => true,
		'label' => __( 'Text before', 'fw' ),
		'desc'  => __( 'Add text before the heading', 'fw' ),
	),

outputs

http://prntscr.com/7w3gti

desired output 

http://prntscr.com/7w3gze
http://prntscr.com/7w3h3x

**Comment by danyj** [comment]
@moldcraft   note , this one inside the   special headings options , so the option is located in popup
http://prntscr.com/7w3hlt

**Comment by danyj** [comment]
js error found when clicking on visual tab in editor 

http://prntscr.com/7w3ibd

**Comment by moldcraft** [comment]
Try

```
'reinit' => true,
```

**Comment by danyj** [comment]
@moldcraft  I did ,  read this 
http://prntscr.com/7w3j3n

same thing

**Comment by danyj** [comment]
@moldcraft   did it again 

    'reinit' => true,

 and "hard" refresh ,   works now

**Comment by danyj** [comment]
Sorry for reopening , but the media does not work
see this please  http://screencast.com/t/KOgjreBKk

**Comment by moldcraft** [comment]
I tried with "Text block" shortcode and it works.

**Comment by danyj** [comment]
@moldcraft   yes , I tested that now also and it works , but try to add this to special heading options 

	'text' => array(
		'type' => 'wp-editor',
		'tinymce' => true,
		'teeny' => true,
		'reinit' => true,
		'wpautop' => false,
		'value' => 'This is text after',
		'label' => __('Text after', 'fw'),
		'desc' => __('Add text after the heading', 'fw')
	)

**Comment by danyj** [comment]
I think I found it 

    'wpautop' => false,

kills the insert media 

if I remove it it work but it auto adds p element

**Comment by danyj** [comment]
Something is definitely off with that one ,  it works  once , than I open , remove the image , add new one and it does not want to add anymore 
see this  http://screencast.com/t/pxO0eob3ul
and it also keeps on opening the text version no matter if you close  when visual is selected

**Comment by danyj** [comment]
@moldcraft    ah , crucial detail ,   this option is inside multipicker , not standalone as text block

**Comment by danyj** [comment]
Also missing several editor options like links , color etc , 

original blog post editor 
http://prntscr.com/7wjk7g

wp-editor option 

http://prntscr.com/7wjksy

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/753#issuecomment-124600440

https://github.com/ThemeFuse/Unyson/issues/509#issuecomment-102322805

**Comment by danyj** [comment]
@moldcraft  thnx

**Comment by danyj** [comment]
@llemurya  @moldcraft   I will post this one here so that I dont have to open another issue , 
when you look at the things above please look also at wpautop , 

it works only if  text layout is selected , if visual layout the wpautop does not work , 
but thing now is that  when I open popup the visual layout is auto selected and in order to remove the p I have to reselect  text layout every time I am adjusting settings

**Comment by llemurya** [comment]
@danyj I tested it in multi-picker option in pop-up with `wpautop=> false` and it works, here is a [video](https://youtu.be/yXpRqc3mBU0).Please tell what i do wrong. I'm wainting for your response.

**Comment by danyj** [comment]
I have no idea bud , as you can see here there was a clear bug 
 http://screencast.com/t/pxO0eob3ul

now I have this 



	'title' => array(
		'type' => 'wp-editor',
		'tinymce' => true,
		'size' => 'large',
		'reinit' => true,
		'wpautop' => false,
		'value'=>'This is dummy heading text',
		'label' => __('Heading Title', 'fw'),
		'desc' => __('Add heading text', 'fw')
	),

and it seems to work fine


I removed tweeny  since than ( what does it do ? )  and 2 days now no issues

**Comment by danyj** [comment]
@llemurya lets , close this one and if I see it again il reopen, 
since you on the editor it would be great if you can take a look at this 
https://github.com/ThemeFuse/Unyson/issues/757

**Comment by llemurya** [comment]
@danyj  in documentation of unyson is described what the new parameters do, please take a look at [wp-editor documentation](http://manual.unyson.io/en/latest/options/built-in-option-types.html#wp-editor).
