### ISSUE TITLE
Megamenu description

### ISSUE THREAD

**Issue by shonnamartell** [ThemeFuse/Unyson#754]
Is there a easy hack or a way to hide the description option in the mega menu?

**Comment by hunter74** [comment]
Hey sorry for answering on this post..  The Descritions can be hided on the standard WP Options at the upper right. 
![bildschirmfoto 2015-08-20 um 10 00 21](https://cloud.githubusercontent.com/assets/8243517/9378514/571036f8-4722-11e5-9084-514e2d879a74.png)

**Comment by hunter74** [comment]
CAN YOU HELP ME?   Where can i activate the Megamenu?  In my selmade WP System I activated the standard Unysn Pagebuilder, but so I can not include the  Megamenu?

Do I have to Integrate / activate anything else? Do I need to add a plugin too?

**Comment by moldcraft** [comment]
@hunter74 See the **(i) Important** section http://manual.unyson.io/en/latest/extension/megamenu/index.html#contents
