### ISSUE TITLE
Registered users access to part of the website

### ISSUE THREAD

**Issue by ariehwagner** [ThemeFuse/Unyson#755]
Good day,
I am using EXPOSURE / UNYSON theme. 
Is it possible to have a section  on the website which are only accessible via password or registered users?

I am a catering company and we have many beautiful food photos of our menus. People want to look at them and use them for our competitor. We want to show them only to registered users. Is this possible?

**Comment by moldcraft** [comment]
You can add an option to section options

1. Add in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/section/options.php`

    ```php
    'only_registered_users' => array(
		'label' => __('Display for', 'fw'),
		'type'  => 'switch',
		'left-choice' => array(
			'value' => false,
			'label' => __('All visitors'),
		),
		'right-choice' => array(
			'value' => true,
			'label' => __('Registered users'),
		),
	),
    ```

2. Add in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/section/views/view.php`

    *At the beginning of the file*

    ```php
    if ($atts['only_registered_users'] && !is_user_logged_in()) {
        return;
    }
    ```

3. Add in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/section/config.php`

    ```
    $cfg = array(
        'page_builder' => array(
            ...
            
            'title_template' => '{{- title }}{{ if (o.only_registered_users) { }} <span class="dashicons dashicons-admin-users"></span>{{ } }}'
        )
    );
    ```

P.S. The icon in section title will look a little big, but I recently made [a fix](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/01bcadd2e437edc4254690163db047f7839fb516) and it will be available in the next Shortcodes extension release.
