### ISSUE TITLE
Do we have javascript html parser that we could use in title_template?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#759]
I am using this for builder element title

	'title_template' => '{{-title}}{{ if (o.title) { }} : {{-o.title}}{{ } }}',

which result in 
![screenshot_6](https://cloud.githubusercontent.com/assets/2340172/8881682/fd18495a-3241-11e5-9659-1ae3d06b5507.png)

I can clean it up with this 

    o.title.replace(/(<([^>]+)>)/ig,"")

![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/8881724/31cd622a-3242-11e5-87ce-48356041b46d.png)

but I rather display it as html. 

Is it possible ?

**Comment by moldcraft** [comment]
* `{{ console.log("Hello"); }}` - Execute any javascript code
* `{{- some.variable }}` - Print a variable html escaped
* `{{= some.variable }}` - Print a variable (no html escape)

**Comment by danyj** [comment]
Bless you !

![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/8884315/14a44650-3256-11e5-92b8-24a40fd82970.png)

**Comment by danyj** [comment]
Darn thing , was hoping to soon , see this 

http://screencast.com/t/ffnNXQaVYf

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25#issuecomment-124544398

**Comment by danyj** [comment]
+1000

**Comment by danyj** [comment]
@moldcraft  sorry for all new things , just picking up where I left off.

**Comment by moldcraft** [comment]
no problem.

*P.S. Next issue that I will do is [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/33) then [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25). Other issues may be inactive until I will finish those 2. If you have a free developer in your team, he can pick any issue and try to debug and resolve it, we accept pull requests :)*

**Comment by danyj** [comment]
thnx bud , will forward to team and help around. I know how messy all those issues can get. Thnx for all the help.

**Comment by danyj** [comment]
sorry but I need small help on this title thing , 

this , gets me the select option value for revolution slider 

    {= o.revslider}

http://prntscr.com/7xcx6l

but I am after the title not the value 

http://prntscr.com/7xcxib

the   o = object does not return anything else ,  this is console log for ti

    Object {revslider: "kenburns_fullwidth"}

I tried also with fw.opg  but no luck, is there any way to do this ?

**Comment by moldcraft** [comment]
At the moment, no.

**Comment by duongancol** [comment]
@danyj did you try with Text block and Image shortcode?
The code below seem didn't work with that shortcodes
<pre>
'title_template' => '{{-title}}{{ if (o.title) { }} : <strong>{{-o.title}}</strong>{{ } }}',
</pre>

**Comment by moldcraft** [comment]
Until the possibility will be added, you can localize script an array with all `choices` from `revslider` option `array('choice_id' => 'Choice Title')`

```
{{= _localizer_revslider_choices[ o.revslider ] }}
```

**Comment by danyj** [comment]
@duongancol  , yes above,  https://github.com/ThemeFuse/Unyson/issues/759#issuecomment-124717955

those work fine no issues , what I am talking about now  is the select option not textarea or text , 

example 

        'choice-1' => __('Choice 1', 'fw'),
        'choice-2' => array(
            'text' => __('Choice 2', 'fw'),
            'attr' => array('data-foo' => 'bar'),
        ),


this will than return   choice-1   instead the title  Choice 1

@moldcraft   I see what you mean. Will try that until the feature is added.

**Comment by danyj** [comment]
@duongancol   the confusion u might have is the o.title ,  I used that as option name 

use this for text-block 

    'title_template' => '{{-title}}{{ if (o.text) { }} : {{-o.text}}{{ } }}',

and this for image 

    'title_template' => '{{-title}}{{ if (o.image) { }} : {{-o.image}}{{ } }}',


u might want to tweak image  and add img tag around it if u want it displayed

**Comment by danyj** [comment]
in short ,  

    o.some_option_name 

is this for example 

http://prntscr.com/7xirrx

**Comment by duongancol** [comment]
@danyj when I add 
<pre>'title_template' => '{{-title}}{{ if (o.image) { }} : {{-o.image}}{{ } }}',</pre> 
to <strong>Image</strong> shortcode
It showed like that : http://prntscr.com/7y8mgh

**Comment by danyj** [comment]
@duongancol  this is console log for o.image 
http://prntscr.com/7zx7ci

so you would need  

    o.image.url

or 

	'title_template' => '{{-title}}{{ if (o.image) { }} :  <img  style=\'width:100px;height:auto;\' src=\'{{-o.image.url }}\' /> {{ } }}',


http://prntscr.com/7zxaeb

**Comment by duongancol** [comment]
Thank @danyj

**Comment by danyj** [comment]
@moldcraft   those notations are very space sensitive , you said 

>{{ console.log("Hello"); }} - Execute any javascript code


but that is not true , we must do those 

    {{ } , }}}
all the time , and if we space the code we get template error 

example I expect this to work 


	'template' => '{{
		var bgtype = background.bg_type;
		var hasimg = background.image;
		
		if (hasimg && bgtype == \'image\') { 
			
			\'<img style="width:80px;height:auto;" src=\'hasimg\'/>\';
			
		}  else { 
	 
			title
	 
		}	
	}}'

but it does not ,  than I  do this 


	'template' => '{{
		var bgtype = background.bg_type;
		var hasimg = background.image;
		
		if (hasimg && bgtype == \'image\') { }}
			
			\'<img style="width:80px;height:auto;" src=\'{{-hasimg}}\'/>\';
			
		{{ }  else { }}
	 
			{{=title}}
	 
	  {{ }	
		
	{{ } }}'

again error ,   

until I do 


	'template' => '{{var bgtype = background.bg_type;var hasimg = background.image;if (hasimg && bgtype == \'image\') { }}
			
			\'<img style="width:80px;height:auto;" src=\'{{-hasimg}}\'/>\';
			
		{{ }  else { }}
	 
			{{=title}}
	 
	  {{ }	
		
	{{ } }}'

**Comment by moldcraft** [comment]
I think it's related to new lines, not to spaces.

Something similar https://github.com/jashkenas/underscore/issues/35

Better do

```php
'template' => '{{ '
    .'var bgtype = background.bg_type; '
    .'var hasimg = background.image; '
    ...
```

**Comment by danyj** [comment]
right . lines , I misspoke ,  but what about the 

    {{ } }}'

we have to use them on any brackets  and variables?

**Comment by moldcraft** [comment]
I don't understand the question.

Do you prefer default [underscore templates](http://underscorejs.org/#template) syntax `<% } %>` ?

**Comment by danyj** [comment]
you see that maze with brackets is what I am talking about 

if I open up with 



    {{  

I should not have to do 

    {{  
	
	var something = somethinghere;
	var that = somethingelse; 
	
	if (something) { }} 
	
		do {{somethinghere}} 
		
	{{ } else { }} 
	
		do {{that }}
		
	{{ } }}

but this should work 


    {{   
		
		var something = somethinghere;
		var that = somethingelse; 
		
		if ( something ) { 
		
			do something
			  
		} else { 
		
			do that 
		}   
		
	}}

**Comment by moldcraft** [comment]
```javascript
var t = _.template(
    '<% '+
    'var x = 1; '+
    'var y = 2; '+
    'if (x == 1) { '+
    '    console.log("Hello"); '+
    '} else {'+
    '    console.log("Hi"); '+
    '} '+
    '%>'
);

console.log(t());
```

**Comment by moldcraft** [comment]
Or if 

```php
'{{ '
. 'hello; '
. 'world; '
. '}}'
```

is not convenient, try

```php
str_relpace("\n", '', '{{
hello;
world;
}}')
```

**Comment by danyj** [comment]
ok will  do , but is just  a hassle either way , especially when you want to do specific layout with conditions. starts looking like giberish instead of plain js

**Comment by danyj** [comment]
this is what I mean , look what he must do in order to get image with conditions 
https://github.com/ThemeFuse/Unyson/issues/923#issue-110548871

all that should be done in few lines

**Comment by moldcraft** [comment]
[There](https://github.com/ThemeFuse/Unyson/issues/923#issue-110548871) are a lot of `{{` without a reason, for e.g.

```
'{{ if (image.custom) { }}'.
    '{{ if (...
```

that can be done

```
'{{ if (image.custom) { '.
 'if
```

**Comment by danyj** [comment]
that is what I am trying to tell you , it does not work 
I was not able to get it to work without those brackets around else brackets

**Comment by moldcraft** [comment]
[Fixed](https://github.com/ThemeFuse/Unyson/commit/ff674ed3b529867bf279a5f0e4a812cd3c1d8754), sorry

**Comment by danyj** [comment]
you might want to test it i builder shortcode title_template  also

**Comment by moldcraft** [comment]
[Done](https://github.com/ThemeFuse/Unyson/issues/759#ref-commit-354ca2b)

**Comment by albertso** [comment]
`<% { %>` notation may be uglier but it can be read better by syntax highlighters.

I've noticed most highlighters interpret  (, [ and { even if the language is unknown, so one knows what bracket closes what by putting the cursor there.

With `{{ { }}` notation nesting cannot be read literally.

**Comment by moldcraft** [comment]
I don't remember exactly, but I am quite sure we changed the notation because on some clients were php parse errors because of http://php.net/manual/en/ini.core.php#ini.asp-tags

We can't change the notation back to original `<%` because a lot of themes are using `{{`

**Comment by albertso** [comment]
No prob, just commenting. {{ is fine!
