### ISSUE TITLE
[Question] Page template in extension's views/ directory

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#761]
Hi there,

I'm creating a new extension for my theme  **"Maintenance & Coming Soon"**. It's really easy, when the option is turned ON (in the extension's settings), all the pages redirect to the Maintenance page (all the data is set in the extension's settings : background, content, title..).

My issue is to replace the page content by the maintenance one. 2 ways in my mind : 

- Redirect the user to a page with a **page template (Maintenance)**, really easy to do in theory. However, I can't add a new page template file in the extension's "views/" files. I tried to name my file **page-maintenance.php** and add the  :
```
/**
* Template Name: Maintenance
*/
```  
But it doesn't work (whereas for content-somthing.php it works). I'm doing it in a bad way or it's normal that it doesn't work ? I checked all your extensions and can't find an example.

- Second way, was using the **Output Buffer** (as many Maintenance plugins do), so I'm using : 
```
function woffice_maintenance_callback() {
  $content = fw()->extensions->get( 'woffice-maintenance' )->render(locate_view_path( 'page-maintenance' ));
  return $content;
}

function woffice_buffer_start() { ob_start("woffice_maintenance_callback"); }

function woffice_buffer_end() { ob_end_flush(); }

add_action('wp_head', 'woffice_buffer_start');
add_action('wp_footer', 'woffice_buffer_end');
``` 

But I got an error which makes sense : `ob_end_flush(): Cannot use output buffering in output buffering display handlers in /.../wp-includes/functions.php on line 3282` according to : https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/general.php#L535-549

I hope it makes sense... do you have any idea about how can I have achieve this ? :) I'm in a deadlock...

Regards,

2F

**Comment by 2Fwebd** [comment]
no way ? 

2F

**Comment by moldcraft** [comment]
Sorry for later reply.

----

Templates with

```
/**
 * Template Name: ...
 */
```

are recognized only by WordPress, but it doesn't search in Unyson extensions views. You can tell WordPress to search in your custom directory via filter, you can find [an example in the Portfolio extension](c2cffd8945e0903132fdf286f5e5a0321f368c30).

**Comment by martinburdon** [comment]
Hey @2Fwebd,

I was going to be doing something like this too, will you be releasing this open source or anything?

Cheers,
Martin

**Comment by 2Fwebd** [comment]
Hello,

Thanks @moldcraft !! I've missed it, I'll give it a try tonight ;)

@martinburdon, Well, I've been working a lot on Unyson extensions : 

![screen_shot_2015-07-29_at_21_27_18](https://cloud.githubusercontent.com/assets/5446124/8967729/0c9ffb3e-3639-11e5-8c35-80f057f079bb.jpg)

If you (or anyone else), need to see how it works and use them for your theme, I'll be happy to share them ;) However, I'm not as talented as Unyson team, so it works but the code may not be the most optimized one, they're all commented. For a public release (to go on any theme without change), I'll need to work a bit more on them (pretty hard for now..)

Cheers,

2F

**Comment by danyj** [comment]
@2Fwebd  I hope you dont mind this side question here , 
you had few sales by now on TF and Unyson , what are your customers saying about Unyson , beside the public comments? How are they reacting to the framework itself ? I wont be done with mine by next year May or so, and it is just bugging me not knowing the public response about it. 
no offense to team here , I am sold as you know , 8 months in. Just need heads up that's all.

**Comment by 2Fwebd** [comment]
Hi @danyj,

To be honest I don't have that much feedbacks on the framework itself, except a few issues (rare!) all is working fine and I have excellent feedbacks from my customers on my 2 last items on TF (Starry and Woffice, 5/5 based on 17 reviews for the last one). So it said that everything (almost, but the problems from my side) is working fine and users love the Unyson environnement (theme settings, page builder, extensions). Then, yes I got once a bad comment on the page builder but it's 1, on more than 700 themes sold with Unyson so it's insignificant in my opinion. And Unyson has a really good future !! Best team (seriously the features are just awesome!), regular updates (it's also great for customers). Finally, I thinks the best feature that we need to develop (users love them) are extensions (you can add so much features) and users can switch in one click, it takes only a few hours to get a really good result. The documentation is also cool for that ! Yep, I could write a full article about how great is Unyson. It's also known by TF review team now. 

In a few words, users love the Theme and issues are really uncommon about the framework now.

I hope that helps :)

2F

**Comment by danyj** [comment]
@2Fwebd thnx much for the info. that is great news. This gives me more hope and I am looking forward to our release . Best of luck with further sales.

**Comment by 2Fwebd** [comment]
No problem @danyj !! Hope your theme will be a success and your work will pay off ! Thanks :)

@martinburdon, I just finished it and it's working really well !! I'll create a Rep in the next days but feel free to email me at help[at]2f-design.fr, I can send you the extension.

2F

**Comment by duongancol** [comment]
@moldcraft : How people can contribute their own extension? I think it good for Unyson community.

**Comment by 2Fwebd** [comment]
Yep, that'd be great to have a place where every author can share his extensions, even if they're adapted to his themes it can help other authors :)

**Comment by llemurya** [comment]
@2Fwebd, @duongancol we will discuss this suggestion.

**Comment by martinburdon** [comment]
@2Fwebd thanks that would be great. You should put them up on GitHub then we can help you get them release ready if you like :)

But yeah I'd definitely be interested in how they work, looks like you've got a good collection of extensions! Feel free to get in touch, support[at]rocketshipthemes[dot]co[dot]uk or martin870 on Twitter

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/761#issuecomment-126122146
> I just finished it and it's working really well !
