### ISSUE TITLE
Problem with page builder and Wordpress quick edit

### ISSUE THREAD

**Issue by Code-Divine** [ThemeFuse/Unyson#764]
When you edit a page with the the quick edit wordpress feature it looses the page builder as a default editing method and if you manually switch back to it it looses all of the components added through it. Actually it doesn't lose them but it packs them into one Text Block component as text in the form of shortcodes.

**Comment by moldcraft** [comment]
I can't reproduce this (maybe it was fixes)

Can you give the exact steps to reproduce this or make a video?

**Comment by c0sm1n87** [comment]
@moldcraft I stumbled on this issue when I used the import demo content functionality, when viewing the page it was all packed in a simple textblock (note that it does not happen everytime, but it has smth to do with the editor).

I don't actually know how and when the page builder is initiated, but this happened to me when I clicked the Update button my mistake when the page was not fully loaded. When the page refreshed, it was "broken", thus the conclusion that if the page is saved while not using the Visual Page Editor, it breaks the shortcode.

PS: you can reproduce this by spamming the Update :+1:

**Comment by danyj** [comment]
@c0sm1n87  we are on this issue for long time and I am not sure how can I spam update if button becomes disabled once clicked. I just tried several times and cant brake it. Will gladly test any suggestions.

**Comment by c0sm1n87** [comment]
@danyj I can reproduce this error pretty easily on a page that has lots of page builder content (for example a homepage). After the page is refreshed, it's a small window when if you click update again, the page will break.

Also, this happens on content demo install as well.

**Comment by Code-Divine** [comment]
I am no longer having this issue after several updates. I am not sure which Unyson version made the problem disappear but doesn't seem to happen anymore when using the quick edit feature.

However I did recreate @c0sm1n87 problem even with one element on the page. I've hit the update button the moment it appeared at which time the editor has still not initialized and the same problem happened. I think the problem is something with the way the page builder and the default WordPress editor save the quotes. Take a look at the photo below. Left is the content when the page builder worked, and right is the content after the page builder broke.

![Image of problem](https://cloud.githubusercontent.com/assets/5454090/10678871/483fb7fa-7915-11e5-9af1-2cd9faa24501.jpg)

**Comment by danyj** [comment]
I dont know what you guys are doing but I cant replicate it at all.  Are we talking about same update button in page edit ? http://prntscr.com/8u861s , I click like crazy with full page builder with 8 sections full with elements and cant recreate. Are you using some editing plugins ?

**Comment by moldcraft** [comment]
> @Code-Divine I think the problem is something with the way the page builder and the default WordPress editor save the quotes.

WordPress replaces `&quot;` with `"`. That problem is fixed here https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/2def54c8a1f63c4e7d175eb7f17f850f0e7a856e/class-fw-extension-page-builder.php#L200-L227

(Sorry, I don't have time to inspect this issue at the moment. Also if it happens when you click too early the Update button, this will happen rarely because users usually don't do that. So I set this issue a minor priority and will inspect it later)

**Comment by moldcraft** [comment]
This was fixed https://github.com/ThemeFuse/Unyson/commit/83c27256355ca9776c373abf47473309b5b858ea
