### ISSUE TITLE
Impossible to install the extension "Forms"

### ISSUE THREAD

**Issue by parsa12** [ThemeFuse/Unyson#766]
Hi, 
I've installed Unyson in Wordpress, and it is impossible the add the "Forms" extention.
So I can't use "Page builder".
I tryed on two computers and it is the same problem. 
When I click on the install button, it says "impossible to copy the file".

Can anybody help me to find a solution ?

thanks, 
Parsa

**Comment by danyj** [comment]
Check your server folder permissions. Make sure it is min 644

**Comment by parsa12** [comment]
Thank you danyj, 
I've checked and that's not the probklem. 
I managed to install other plugins and extentions, but for this one "Forms" there is a problem.

**Comment by danyj** [comment]
Can you give exact msg please . I am not finding anything with this "impossible to copy the file" 
trying to digg inside and check the conditions

**Comment by parsa12** [comment]
Ok, 
The message is in French, cause my wordpress edition is french.

I click on Unyson, and I see the extentions.
4 are activated and 2 are available.
![image-01](https://cloud.githubusercontent.com/assets/13522529/8910431/f3ec445c-3486-11e5-99e3-f1530e826772.jpg)

When I click on download "Forms"buton" , a popup window opens with no meassage., i just can close it. (I tried with firefox and Chrome, the same thing happens with both navigators)
![image-02](https://cloud.githubusercontent.com/assets/13522529/8910533/a5d14672-3487-11e5-9f53-45e5e5814c5a.jpg)


when I clck on view requirements for "Page Builder" Extension, I can also try to download "Forms" and it directs me in a new page.
![image-03](https://cloud.githubusercontent.com/assets/13522529/8910610/11b74fbc-3488-11e5-9fff-fa418951a00e.jpg)


if i click on "Yes install this extention" then I receiv the folowing message : "Impossible de copier le fichier" with can be translated by "impossible to copy the file"
![image-04](https://cloud.githubusercontent.com/assets/13522529/8910638/2eaabbc2-3488-11e5-9f71-2edf46b2d6d1.jpg)

Thanks again for your help.
Parsa

**Comment by moldcraft** [comment]
Can be Windows path length limit https://wordpress.org/support/topic/cannot-install-page-builder

**Comment by parsa12** [comment]
Thank you, 
I did the same thing as Mint : "I simply moved the software from C:\Program Files (x86)\EasyPHP etc.. to C:\EasyPHP\... this allowed me to cut many letters from the path lenght."

Thanks again
