### ISSUE TITLE
Is it possible to bring extensions settings to theme options tab?

### ISSUE THREAD

**Issue by Code-Divine** [ThemeFuse/Unyson#767]
For example I would like to move the settings from the breadcrumbs extension: wp-admin/admin.php?page=fw-extensions&sub-page=extension&extension=breadcrumbs

as a new tab in the theme options: /wp-admin/themes.php?page=fw-settings

**Comment by moldcraft** [comment]
It's not possible.

At the moment you can place in Theme Settings a link to breadcrumbs settings page

```php
'breadcrumbs-settings' => array(
	'type' => 'html',
	'label' => __('Breadrumbs', 'fw'),
	'html' => fw_html_tag(
		'a',
		array(
			'href' => fw()->extensions->manager->get_extension_link('breadcrumbs'),
			'target' => '_blank',
		),
		__('Configure', 'fw')
	),
),
```

I will try to figure out a solution, but don't guarantee that if I will find one (and when).

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/838

**Comment by danyj** [comment]
so this is still in works ? because here you are showing something else
http://demo.unyson.io/?page_id=135

**Comment by moldcraft** [comment]
That demo was created with Unyson v1, at that time there was no Unyson Extensions page.

**Comment by danyj** [comment]
@moldcraft  understood that is just bit misleading , but I was asking if that extension settings proxy is in works or ?

**Comment by moldcraft** [comment]
The issue is open https://github.com/ThemeFuse/Unyson/issues/838
Currently it's in pending, now I am busy with backup. I will start working on proxy right after backup.

**Comment by danyj** [comment]
@moldcraft  no stress bud , take your time.

**Comment by danyj** [comment]
sorry to come back at it , when you can take a look , 


why is this outputed in front ? 


I added 


	'breadcrumbs-settings' => array(
		'type' => 'html',
		'label' => __('Breadrumbs', 'fw'),
		'html' => fw_html_tag(
			'a',
			array(
				'href' => fw()->extensions->manager->get_extension_link('breadcrumbs'),
				'target' => '_blank',
			),
			__('Configure', 'fw')
		),
	),

in admin theme options and on homepage I see 


    Fatal error: Call to a member function get_extension_link() on a non-object

http://prntscr.com/8tpmgv

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/3abd0aaed8aa74badd32a0d1e7ed70bf12ab994c/framework/core/components/extensions.php#L96-L99

do

```php
fw()->extensions->manager ? fw()->extensions->manager->get_extension_link('breadcrumbs') : '#'
```

**Comment by danyj** [comment]
I understand  that extension is not "visible"  what I mean is why does the frontend see that particular option at all?   Does this mean that all theme options files are simply included in frontend also ? 

I mean this option is inside a tab in theme options , not processed and no output used in front. Kinda confusing. I was under impression that theme options and files used in there  are visible when you are in admin  but not when you are on homepage.

**Comment by moldcraft** [comment]
Please add in options file

```php
echo '<pre>';
debug_print_backtrace();
echo '</pre>';
```

and post the output here

**Comment by danyj** [comment]
darn , the hole thing is there , I think is  number 2 and 4 



	#0  require() called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\general.php:562]
	#1  fw_get_variables_from_file(D:\wamp\www\Development\WordPress/wp-content/themes/thztheme/inc/thzframework/theme/options/advanced.php, Array ([options] => Array ()), Array ()) called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\core\components\theme.php:74]
	#2  _FW_Component_Theme->get_options(advanced) called at [D:\wamp\www\Development\WordPress\wp-content\themes\thztheme\inc\thzframework\theme\options\settings.php:145]
	#3  require(D:\wamp\www\Development\WordPress\wp-content\themes\thztheme\inc\thzframework\theme\options\settings.php) called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\general.php:562]
	#4  fw_get_variables_from_file(D:\wamp\www\Development\WordPress/wp-content/themes/thztheme/inc/thzframework/theme/options/settings.php, Array ([options] => Array ()), Array ()) called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\core\components\theme.php:74]
	#5  _FW_Component_Theme->get_options(settings) called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\core\components\theme.php:86]
	#6  _FW_Component_Theme->get_settings_options() called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\database.php:39]
	#7  fw_get_db_settings_option(notcontained, ) called at [D:\wamp\www\Development\WordPress\wp-content\themes\thztheme\inc\helpers.php:89]
	#8  thz_get_option(notcontained) called at [D:\wamp\www\Development\WordPress\wp-content\themes\thztheme\inc\helpers.php:729]
	#9  thz_contained(notcontained, ) called at [D:\wamp\www\Development\WordPress\wp-content\themes\thztheme\inc\includes\thz-widgets-generator.php:199]
	#10 thz_widgets_grid_print(f, Array ([json] => [{"type":"section","shortcode":"section_39ae7d9","width":"","_items":[{"type":"columns","shortcode":"columns_056ed87","width":"1_4","options":{"widget_name":"Widget 1","widget_in_boxstyle":{"padding":{"padding-top":"0","padding-right":"0","padding-bottom":"0","padding-left":"0"},"margin":{"margin-top":"0","margin-right":"auto","margin-bottom":"0","margin-left":"auto"},"border":{"border-width":"0","border-style":"solid","border-color":""},"borderside":{"all":false,"top":false,"right":false,"bottom":false,"left":false},"boxsize":{"width":"","height":"","min-width":"","min-height":""},"borderradius":{"top-left":0,"top-right":0,"bottom-left":0,"bottom-right":0},"boxshadow":{"active":false,"inset":"no","horizontal-offset":"0","vertical-offset":"0","blur-radius":"0","shadow-color":""},"background":{"background-type":"none","background-color":"","background-image":"","background-repeat":"repeat","background-position":"left-top","background-size":"auto","background-attachment":"scroll","background-gradient-style":"linear","background-gradient-angle":"0","background-gradient-size":"farthest-corner","background-gradient-shape":"circle","background-gradient-h-poz":"50","background-gradient-v-poz":"50","background-gradient-start":"0","background-gradient-start-color":"#ffffff","background-gradient-add-stop":[],"background-gradient-end":"100","background-gradient-end-color":"#0074a2","video-link":""},"css":"padding:0px 0px 0px 0px;margin:0px auto 0px auto;"},"widgetid":"","widgetclass":"","widgetcss":"","widget_text_align":{"picked":"default","custom":{"align":"left"}},"widget_font_family":{"picked":"default","custom":{"widget_font":{"font":"Lato|regular|latin-ext","size":"14","lineheight":"1.618","letterspacing":"normal"},"widget_headings_font":{"font":"Open Sans|regular|vietnamese"}}},"widgetcolorset":{"picked":"default","custom":{"widget_colors":{"text_color":"","link_color":"","link_hover_color":"","headings_color":""}}}}},{"type":"columns","shortcode":"columns_63e998c","width":"1_4","options":{"widget_name":"Widget 2","widget_in_boxstyle":{"padding":{"padding-top":"0","padding-right":"0","padding-bottom":"0","padding-left":"0"},"margin":{"margin-top":"0","margin-right":"auto","margin-bottom":"0","margin-left":"auto"},"border":{"border-width":"0","border-style":"solid","border-color":""},"borderside":{"all":false,"top":false,"right":false,"bottom":false,"left":false},"boxsize":{"width":"","height":"","min-width":"","min-height":""},"borderradius":{"top-left":0,"top-right":0,"bottom-left":0,"bottom-right":0},"boxshadow":{"active":false,"inset":"no","horizontal-offset":"0","vertical-offset":"0","blur-radius":"0","shadow-color":""},"background":{"background-type":"none","background-color":"","background-image":"","background-repeat":"repeat","background-position":"left-top","background-size":"auto","background-attachment":"scroll","background-gradient-style":"linear","background-gradient-angle":"0","background-gradient-size":"farthest-corner","background-gradient-shape":"circle","background-gradient-h-poz":"50","background-gradient-v-poz":"50","background-gradient-start":"0","background-gradient-start-color":"#ffffff","background-gradient-add-stop":[],"background-gradient-end":"100","background-gradient-end-color":"#0074a2","video-link":""},"css":"padding:0px 0px 0px 0px;margin:0px auto 0px auto;"},"widgetid":"","widgetclass":"","widgetcss":"","widget_text_align":{"picked":"default","custom":{"align":"left"}},"widget_font_family":{"picked":"default","custom":{"widget_font":{"font":"Lato|regular|latin-ext","size":"14","lineheight":"1.618","letterspacing":"normal"},"widget_headings_font":{"font":"Open Sans|regular|vietnamese"}}},"widgetcolorset":{"picked":"default","custom":{"widget_colors":{"text_color":"","link_color":"","link_hover_color":"","headings_color":""}}}}},{"type":"columns","shortcode":"columns_a16a573","width":"1_4","options":{"widget_name":"Widget 3","widget_in_boxstyle":{"padding":{"padding-top":"0","padding-right":"0","padding-bottom":"0","padding-left":"0"},"margin":{"margin-top":"0","margin-right":"auto","margin-bottom":"0","margin-left":"auto"},"border":{"border-width":"0","border-style":"solid","border-color":""},"borderside":{"all":false,"top":false,"right":false,"bottom":false,"left":false},"boxsize":{"width":"","height":"","min-width":"","min-height":""},"borderradius":{"top-left":0,"top-right":0,"bottom-left":0,"bottom-right":0},"boxshadow":{"active":false,"inset":"no","horizontal-offset":"0","vertical-offset":"0","blur-radius":"0","shadow-color":""},"background":{"background-type":"none","background-color":"","background-image":"","background-repeat":"repeat","background-position":"left-top","background-size":"auto","background-attachment":"scroll","background-gradient-style":"linear","background-gradient-angle":"0","background-gradient-size":"farthest-corner","background-gradient-shape":"circle","background-gradient-h-poz":"50","background-gradient-v-poz":"50","background-gradient-start":"0","background-gradient-start-color":"#ffffff","background-gradient-add-stop":[],"background-gradient-end":"100","background-gradient-end-color":"#0074a2","video-link":""},"css":"padding:0px 0px 0px 0px;margin:0px auto 0px auto;"},"widgetid":"","widgetclass":"","widgetcss":"","widget_text_align":{"picked":"default","custom":{"align":"left"}},"widget_font_family":{"picked":"default","custom":{"widget_font":{"font":"Lato|regular|latin-ext","size":"14","lineheight":"1.618","letterspacing":"normal"},"widget_headings_font":{"font":"Open Sans|regular|vietnamese"}}},"widgetcolorset":{"picked":"default","custom":{"widget_colors":{"text_color":"","link_color":"","link_hover_color":"","headings_color":""}}}}},{"type":"columns","shortcode":"columns_865daf6","width":"1_4","options":{"widget_name":"Widget 4","widget_in_boxstyle":{"padding":{"padding-top":"0","padding-right":"0","padding-bottom":"0","padding-left":"0"},"margin":{"margin-top":"0","margin-right":"auto","margin-bottom":"0","margin-left":"auto"},"border":{"border-width":"0","border-style":"solid","border-color":""},"borderside":{"all":false,"top":false,"right":false,"bottom":false,"left":false},"boxsize":{"width":"","height":"","min-width":"","min-height":""},"borderradius":{"top-left":0,"top-right":0,"bottom-left":0,"bottom-right":0},"boxshadow":{"active":false,"inset":"no","horizontal-offset":"0","vertical-offset":"0","blur-radius":"0","shadow-color":""},"background":{"background-type":"none","background-color":"","background-image":"","background-repeat":"repeat","background-position":"left-top","background-size":"auto","background-attachment":"scroll","background-gradient-style":"linear","background-gradient-angle":"0","background-gradient-size":"farthest-corner","background-gradient-shape":"circle","background-gradient-h-poz":"50","background-gradient-v-poz":"50","background-gradient-start":"0","background-gradient-start-color":"#ffffff","background-gradient-add-stop":[],"background-gradient-end":"100","background-gradient-end-color":"#0074a2","video-link":""},"css":"padding:0px 0px 0px 0px;margin:0px auto 0px auto;"},"widgetid":"","widgetclass":"","widgetcss":"","widget_text_align":{"picked":"default","custom":{"align":"left"}},"widget_font_family":{"picked":"default","custom":{"widget_font":{"font":"Lato|regular|latin-ext","size":"14","lineheight":"1.618","letterspacing":"normal"},"widget_headings_font":{"font":"Open Sans|regular|vietnamese"}}},"widgetcolorset":{"picked":"default","custom":{"widget_colors":{"text_color":"","link_color":"","link_hover_color":"","headings_color":""}}}}}],"options":{"show_empty":"donotshow","section_name":"Section 1","section_boxstyle":{"padding":{"padding-top":"100","padding-right":"0","padding-bottom":"100","padding-left":"0"},"margin":{"margin-top":"0","margin-right":"auto","margin-bottom":"0","margin-left":"auto"},"border":{"border-width":"1","border-style":"solid","border-color":"#243645"},"borderside":{"all":"","top":"","right":"","bottom":"true","left":""},"boxsize":{"width":"","height":"","min-width":"","min-height":""},"borderradius":{"top-left":"0","top-right":"0","bottom-left":"0","bottom-right":"0"},"boxshadow":{"active":"on","inset":"no","horizontal-offset":"0","vertical-offset":"0","blur-radius":"0","shadow-color":""},"background":{"background-type":"color","background-color":"#13202c","background-image":"","background-repeat":"repeat","background-position":"left-top","background-size":"auto","background-attachment":"scroll","background-gradient-style":"linear","background-gradient-angle":"0","background-gradient-size":"farthest-corner","background-gradient-shape":"circle","background-gradient-h-poz":"50","background-gradient-v-poz":"50","background-gradient-start":"0","background-gradient-start-color":"#ffffff","background-gradient-end":"100","background-gradient-end-color":"#0074a2","video-link":""},"css":"padding:100px 0px 100px 0px;margin:0px auto 0px auto;border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:#243645;background-color:#13202c;"},"section_contained":"notcontained","widgets_boxstyle":{"picked":"default","custom":{"boxstyle":{"padding":{"padding-top":"0","padding-right":"15","padding-bottom":"0","padding-left":"15"}}}},"section_widgets_contained":"contained","sectionid":"","sectionclass":"","sectioncss":"","section_text_align":{"picked":"default","custom":{"align":"left"}},"section_font_family":{"picked":"default","custom":{"section_font":{"font":"Lato|regular|latin-ext","size":"14","lineheight":"1.618","letterspacing":"normal"},"section_headings_font":{"font":"Open Sans|regular|vietnamese"}}},"sectioncolorset":{"picked":"custom","custom":{"section_colors":{"text_color":"#889bae","link_color":"#889bae","link_hover_color":"#3bafda","headings_color":"#e6e9ed"}}}}}])) called at [D:\wamp\www\Development\WordPress\wp-content\themes\thztheme\footer.php:12]
	#11 require_once(D:\wamp\www\Development\WordPress\wp-content\themes\thztheme\footer.php) called at [D:\wamp\www\Development\WordPress\wp-includes\template.php:555]
	#12 load_template(D:\wamp\www\Development\WordPress/wp-content/themes/thztheme/footer.php, 1) called at [D:\wamp\www\Development\WordPress\wp-includes\template.php:514]
	#13 locate_template(Array ([0] => footer.php), 1) called at [D:\wamp\www\Development\WordPress\wp-includes\general-template.php:85]
	#14 get_footer() called at [D:\wamp\www\Development\WordPress\wp-content\themes\thztheme\index.php:51]
	#15 include(D:\wamp\www\Development\WordPress\wp-content\themes\thztheme\index.php) called at [D:\wamp\www\Development\WordPress\wp-includes\template-loader.php:75]
	#16 require_once(D:\wamp\www\Development\WordPress\wp-includes\template-loader.php) called at [D:\wamp\www\Development\WordPress\wp-blog-header.php:16]
	#17 require(D:\wamp\www\Development\WordPress\wp-blog-header.php) called at [D:\wamp\www\Development\WordPress\index.php:17]

**Comment by danyj** [comment]
no , its 11 , that is why I see the notice in the footer

**Comment by moldcraft** [comment]
`#9` ---> `#7` then the option value is not found in database, then options array is loaded to extract default values.

To prevent that, call `fw_get_db_settings_option()` with default value parameter

**Comment by danyj** [comment]
bless you heart my friend!

**Comment by moldcraft** [comment]
Add in `settings.php`

```php
$options = array(
	'ext:breadcrumbs' => !fw_ext('breadcrumbs') ? array( /* ext not active */ ) : array(
		'type' => 'multi',
		'label' => false,
		'inner-options' => fw_ext('breadcrumbs')->get_settings_options(),
		'fw-storage' => array(
			'type' => 'wp-option',
			'wp-option' => 'fw_ext_settings_options:breadcrumbs'
		),
	),
	'test' => array(
		'type' => 'text',
		'value' => 'Hello World',
	),
);
```

**Comment by Code-Divine** [comment]
This works perfectly while the extension is active but when it's disabled I get:
`Warning: Invalid option: ext:breadcrumbs`

**Comment by blackyangell** [comment]
Hi. How can I add my custom extensions options to theme settings?
Before the last update it worked that way: 

if (fw_ext('share')) {
    require_once( fw_locate_theme_path('/framework-customizations/extensions/share/theme-options.php') );
}

But after update it doesn't work. How can I deal with it now? Thank you.

**Comment by moldcraft** [comment]
Please inspect why `fw_locate_theme_path()` doesn't return the right path. Or give me admin/ftp access to your site and I will inspect it (send the details to `moldcraft[at]email.com`)

**Comment by blackyangell** [comment]
fw_locate_theme_path('/framework-customizations/extensions/share/theme-options.php') returns right path. But for some reason it stoped working using 'require_once( fw_locate_theme_path('/framework-customizations/extensions/share/theme-options.php') )'.

I tried to use 'require fw_locate_theme_path('/framework-customizations/extensions/share/theme-options.php')', and it works now :) I can see options of this extension on my theme settings page.

**Comment by moldcraft** [comment]
Options file is included multiple times, but require_once works only the first time.

**Comment by blackyangell** [comment]
How can I include my custom extension options to Theme Settings more correctly?

**Comment by moldcraft** [comment]
It's fine that way.
