### ISSUE TITLE
Shorter `unique` id

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#768]
Add `'length' => 7` parameter for option-type `unique` ([usage](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head))

**Comment by danyj** [comment]
:+1: , thx ,

**Comment by danyj** [comment]
@moldcraft  , any way to make this in 2.4.4 ? I am doing shortcodes and using this option in all of them. It will be pain to go back in few weeks to redo those iID's.

**Comment by moldcraft** [comment]
I already released 2.4.4. I will resolve this asap but it will be included in the next release. I will try to find some changed to be included in 2.4.5 and release it as soon as possible, it should be this week.

**Comment by danyj** [comment]
I saw that now , sorry , yes it will be great to add it in master , I can than download and use it till 2.4.5

**Comment by moldcraft** [comment]
Test it please

**Comment by danyj** [comment]
Perfect!. Thank you!
