### ISSUE TITLE
[suggestion] Suggestions to improve icon option

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#769]
The icon option currently features all FA fonts , over 500 ( 4.4 is out  reminder to update http://fontawesome.io/whats-new/), 

The icon size is small so is bit hard to find the icon we need,  now we have Unyson icons coming over 
https://github.com/ThemeFuse/Unyson/issues/227#issuecomment-125912509

It will be an overwhelming amount of icons and much harder to find the one you need. 

Can you please add something like this 
http://screencast.com/t/TCV5fvLcA

or any kind of icon search mechanism that makes it easier to find the icon. 
I know that some will argue category select but see this 
http://prntscr.com/7ycfuo
how is that user friendly ?

2 more issues
there is no width limit , for example 
icon-short like we have for select or text, so if you just plaster icon option this is what you get 

http://prntscr.com/7ycefa

desired would be something like 

http://prntscr.com/7ycg6z

again , some might argue to add additional class, but I think it should be option param

, when icons is selected ,  and you refresh the icon page , you have hard time knowing which one is  selected 
http://screencast.com/t/eqAkNau0LM1

in mega menu you added an indication as to which one is selected. 
http://prntscr.com/7yci1b

Please do advise if you will be able to do any of these suggestions so that I know if I should make own version of icon option. It is not a problem if you cant , I just need heads up . 

Thnx!

**Comment by danyj** [comment]
@moldcraft  im implementing the search ,  will show in a few

**Comment by danyj** [comment]
This is what I have 
http://screencast.com/t/FwZnxW06K4

**Comment by danyj** [comment]
OK , this is my final , let me know if you want me to send pull request
http://screencast.com/t/8zPNkJNdpqc

I created a pull if you are interested https://github.com/ThemeFuse/Unyson/pull/770

**Comment by moldcraft** [comment]
Thank you for the suggestions, I'll take a look later.
I am thinking to create option type `icon-v2` ...

**Comment by duongancol** [comment]
@danyj It's really helpful. I'm thinking to search shortcodes from page builder. What do you think?
