### ISSUE TITLE
Fatal error: Call to undefined method FW_Extension_Builder ....

### ISSUE THREAD

**Issue by jlsant921** [ThemeFuse/Unyson#772]
I just updated Unyson extensions and now I am getting this error when I try to view the site: http://sherpalocal.com 

Fatal error: Call to undefined method FW_Extension_Builder::get_uri() in /home/content/p3pnexwpnas05_data03/71/2543371/html/wp-content/themes/wp-multipurpose/framework/extensions/builder/static.php on line 6

I can access the WP backend just fine. I even disabled and renabled the page builder extension and still the same error keeps coming up. Can anyone help me figure out what's going on?

**Comment by moldcraft** [comment]
Which version of Unyson do you have?

**Comment by jlsant921** [comment]
Unyson 2.1.25

**Comment by moldcraft** [comment]
It's very old, please update (current version is 2.4.x).

**Comment by jlsant921** [comment]
Now I'm getting timed out errors. Why would this be?

**Comment by moldcraft** [comment]
You already update the plugin, or you get timeout when you try to update it?
On which page you get timeout and how to reproduce it?

**Comment by jlsant921** [comment]
I can no longer get into the backend. I was going to update Unyson when the front and backend started timing out.

**Comment by moldcraft** [comment]
Can you open phpMyAdmin, go to `wp_options` table and delete the row with `option_name = 'active_plugins'`?

**Comment by jlsant921** [comment]
I don't have access to phpMyAdmin at this time...can I update Unyson through Wordpress?

**Comment by moldcraft** [comment]
Of course you can.
The above was a method to disable all plugins, I thought Unyson is causing the timeout.

**Comment by jlsant921** [comment]
well, for some reason, I was able to get back into the WP backend. (crazy, right?!). What do I need to do now?

**Comment by moldcraft** [comment]
Just update the Unyson plugin and that's all.

**Comment by jlsant921** [comment]
THANK YOU THANK YOU THANK YOU! Everything is back to normal now!
