### ISSUE TITLE
sidebar extension didn't work

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#774]
I'm doing manage layout with sidebar extension but it didn't work in this situation
In page.php
```php
$fw_page_layout = (function_exists('fw_ext_sidebars_get_current_position')) ? fw_ext_sidebars_get_current_position() : 'full';
if($fw_page_layout == 'right') :
     echo '<div class="col-md-8">';
		get_template_part('content', 'page');
	echo '</div>';

	get_sidebar('content');
endif;
```
In sidebar-content.php
```php
$current_position = fw_ext_sidebars_get_current_position();  fw_print($current_position); 
echo fw_ext_sidebars_show('blue'); 
```
The problem is the $current_position returns <strong>null</strong>. See here: http://prntscr.com/7yrwp0

But It only works when I change position of <strong>get_sidebar</strong> to the top
```php
$fw_page_layout = (function_exists('fw_ext_sidebars_get_current_position')) ? fw_ext_sidebars_get_current_position() : 'full';
if($fw_page_layout == 'right') :
      get_sidebar('content');

     echo '<div class="col-md-8">';
		get_template_part('content', 'page');
	echo '</div>';
endif;
```
See here: http://prntscr.com/7yry67
So I guess that it's maybe conflict with content-page and here is all code of this: 
```php
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<div class="entry-content">
		<?php
		the_content();
		?>
	</div><!-- .entry-content -->
</article><!-- #post-## -->
```
So what is conflict here?

**Comment by llemurya** [comment]
@duongancol I reproduced this bug, but for me it works , see [this video](https://youtu.be/nyHdZ4XrzRU). I am wainting for your response.

**Comment by duongancol** [comment]
I found the reason. It only didn't work on a page that use my portfolio shortcode. So please give me your email. I'll send my portfolio shortcode for you.

**Comment by llemurya** [comment]
dev-team@unyson.io

**Comment by duongancol** [comment]
I did, please check your inbox!

**Comment by duongancol** [comment]
Hi @llemurya : any updates?

**Comment by moldcraft** [comment]
Hi
@llemurya will be offline for a few weeks and I am busy with other issues, sorry

**Comment by duongancol** [comment]
@moldcraft : it's ok, i'll try to find the problem while he's busy. 
One more question, is there any ways to manage sidebar layout like metabox of Pages instead of going to Appearance -> Widgets.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Sidebars-Extension/blob/30242f949aa8ef015639bdc4acf4a1b862fae747/config.php#L37-L40

**Comment by Alex-Ascet** [comment]
Hi @duongancol,

I have got the same issue. The sidebar doest not display only when the portfolio plugin has been added in my content. Did you find a solution? Thank you for your help.

**Comment by duongancol** [comment]
@Alex-Ascet : Sorry, I didn't find the solution :(
