### ISSUE TITLE
Too difficult to place elements within sections in the page builder

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#775]
I'm not sure if it's just me that has this problem but I can never manage to place an element within a container.
For example I have an empty section and a full width (1/1) layout element. I want to put this layout element within the section but it always snaps above or below the section and it's too difficult to actually place it within the section. Same goes for placing content/media elements within a layout block.

Is there anything that can be done to make this process easier?

Thanks,
Martin

**Comment by moldcraft** [comment]
At the moment you can only try to move the mouse faster to move the dragget element over the section/column and to make it element appear in it.

I will try to fix this in my [next task](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25#issuecomment-123647625).

P.S. At the moment I'm working on [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/33).

**Comment by martinburdon** [comment]
Thanks for the update.
Saving sections looks like a great idea I look forward to that feature being released.

Keep up the great work :+1:
