### ISSUE TITLE
Shortcode Button did not appear on wp-editor using unyson ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#777]
Hello @moldcraft 
Hope you guys are well with your coding.

I have a question here. i have created a custom post type and created the meta boxes using unyson.
in which one of my option type is wp-editor. And i have installed page break wordpress plugin.
the shortcode button option did not appear in unyson wp-editor but its appear in wordpress default posts. Is there any setting that i have missed so far. Kindly do let me know what i did wrong at this point.

Thanks

**Comment by moldcraft** [comment]
Hello

I don't think that the button should appear in wp-editor option type, it is a separated component and hooks that affects default post editor are not affecting wp-editor.

*P.S. I am not sure 100% because I am not familiar with wp-editor internals*

We will give a final reply later.

**Comment by moldcraft** [comment]
Option-type wp-editor was [fixed](https://github.com/ThemeFuse/Unyson/compare/87675985308a15da80e3167638a388647da50539...59c0d00f8c75f0b99c3b83cd31f63b06374a77a5?diff=split&name=59c0d00f8c75f0b99c3b83cd31f63b06374a77a5), it should work now. Please [download Unyson latest dev version](https://github.com/ThemeFuse/Unyson/archive/master.zip) and test.
