### ISSUE TITLE
Creating new predefined drop-down select option-types

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#778]
Hi ,This is an awesome framework . However i like to create a select dropdown menu. It renders correctly but the option values are not saving. 

My code to do that
```
	protected function _render( $id, $option, $data ) {
		$option['attr']['value'] = (string) $data['value'];
        $myArray2 = array('c'=>'Cat','m'=>'Mat','f'=>'Fat','h'=>'Hat'); 
		echo'<select name="Words">'; 
        foreach($myArray2 as $let=>$word){ 
        echo'<option value="'.$let.'">'.$word.'</option>'; 
        } 
        echo'</select>'; 
	}
```

This renders exactly what i want.
![untitled](https://cloud.githubusercontent.com/assets/7946657/9025968/c62b9e94-393d-11e5-865a-92726074be27.jpg)
But the values are not saving. Thanks

**Comment by moldcraft** [comment]
http://stackoverflow.com/questions/3518002

**Comment by webangon** [comment]
But this is not saving the selected value.

**Comment by moldcraft** [comment]
Also `<select name="Words">`, you must use `$option['attr']['name']`, and better to use `$option['attr']`, and not echo but return, so

```php
$html = '<select '. fw_attr_to_html($option['attr']) .'>';

// ...

return $html;
```

inspect [predefined option-types](https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/simple.php)

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/options/create-option-type.html#content
