### ISSUE TITLE
error with map shortcode

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#779]
I'm creating a page with map shortcode. It works but show this error:
<pre>
Notice: Unknown location provider "" specified for map shortcode in /Volumes/Data/MAMP/krystal/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/map/class-fw-shortcode-map.php on line 123
Map Placeholder
</pre>
P/s : I'm using the latest version of Unyson

**Comment by moldcraft** [comment]
I made a simple fix: Instead of warning display nothing (a html comment).

This happens because the map shortcode is not configured.
