### ISSUE TITLE
print subset google font

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson#780]
Hi 
i am trying to use typography-v2 for subset google font

but quite confused how to print this font with subset
here how i print google font

``<pre>if (!function_exists('_action_theme_process_google_fonts')) {

    function _action_theme_process_google_fonts() {
        $include_from_google = array();
        $google_fonts = fw_get_google_fonts();
        $body_font = fw_get_db_settings_option('body_font');
        if (isset($google_fonts[$heading_title['family']])) {
            $include_from_google[$heading_title['family']] = $google_fonts[$heading_title['family']];
        }
        if (isset($google_fonts[$body_font['family']])) {
            $include_from_google[$body_font['family']] = $google_fonts[$body_font['family']];
        }
        $google_fonts_links = fw_theme_get_remote_fonts($include_from_google);
        // set a option in db for save google fonts link
        update_option('fw_theme_google_fonts_link', $google_fonts_links);
    }
    add_action('fw_settings_form_saved', '_action_theme_process_google_fonts', 999, 2);
}
if (!function_exists('fw_theme_get_remote_fonts')) :
    function fw_theme_get_remote_fonts($include_from_google) {
        if (!sizeof($include_from_google)) {
            return '';
        }
        $html = "<link href='http://fonts.googleapis.com/css?family=";

        foreach ($include_from_google as $font => $styles) {
            $html .= str_replace(' ', '+', $font) . ':' . implode(',', $styles['variants']) . '|';
        }
        $html = substr($html, 0, - 1);
        $html .= "' rel='stylesheet' type='text/css'>";

        return $html;
    }
endif;

if (!function_exists('_action_theme_print_google_fonts_link')) :
    function _action_theme_print_google_fonts_link() {
        
        $google_fonts_link = get_option('fw_theme_google_fonts_link', '');
        if ($google_fonts_link != '') {
            echo $google_fonts_link;
        }
    }

    add_action('wp_head', '_action_theme_print_google_fonts_link');
endif;</pre>``

here how now print fro  google
`<link href='http://fonts.googleapis.com/css?family=|Roboto:300,400,500,700|Open+Sans:300,300italic,regular,italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'> </pre>`

but i want to print with subset like

`<link href='http://fonts.googleapis.com/css?family=Roboto:400,300&subset=latin-ext,latin' rel='stylesheet' type='text/css'>`

can you please help me to print subset  with my google font

Thank you

**Comment by duongancol** [comment]
There is a bug with the subset of typography-v2, some fonts return false with a subset. For ex: Time new Roman, Arial,...

**Comment by moldcraft** [comment]
Please provide a pull request with a fix (we don't have time to inspect this) https://github.com/ThemeFuse/Unyson/tree/master/framework/includes/option-types/typography-v2
