### ISSUE TITLE
What sanitization  method to use for unyson outputted variables  and when?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#781]
@moldcraft 
@llemurya 
@sergiubagrin 

OK this one is messing with me since I come from another CMS where we did not have to think as much about data sanitization since every option output was sanitized via one class but in WP I must pay very close attention to this.  

When I first started with WP my thought was and still is , why do we have to sanitize admin inputed outputs as much as we do ?  I understand sanitization of frontend inputs like comments , frontend forms etc, but backend  input goes in DB first and I would like to think that you guys did good job on sanitizing data before entering DB. 

So a bit insight  as to when and where to sanitize would be great. I assume that we should only use it when creating option types and sanitize data before entering DB but would just like a confirmation fro you guys. 

So here are few examples of unyson variables outputs and if someone can please advise what method to use where and if it should be used at all. 

First is textarea option, 
I will use native shortcode tabs as example 

Here we have  a title and textarea 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/tabs/options.php#L13-L20

but views have no sanitization https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/tabs/views/view.php

I added css class and id  ( text option types ) to tabs options and doing 

    esc_attr ()

on the id and this helper function for class names  since  sanitize_html_class is removing spaces if you use more than one class name 

	/**
	* Sanitize element class names
	*/
	
	function thz_sanitize_class($classnames){
		
		$classnames = explode(' ', $classnames);
		
		foreach($classnames as $k => $v){
			$classnames[$k] = sanitize_html_class($v);
		}
		
		return join(' ', $classnames);
	
	}

Question for those above is ,  am I doing to much and if what I am doing is ok?

Now I also added some custom style to those tabs and will end up printing CSS in head via shortcodes/ hooks.php 

so second question is , do I need to escape the class name and for example color-picker option type output before outputting in head also? 

This is the print that goes in head 

![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/9060909/4d5b0a28-3ab8-11e5-8057-cb97bd5bd2db.png)

Thank you!

**Comment by moldcraft** [comment]
> sanitizing data before entering DB

I think that in DB should be original input values (untouched) and on output you sanitize it (or not, depending where you use it)

> Here we have a title and textarea
> 
> https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/tabs/options.php#L13-L20
> 
> but views have no sanitization https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/tabs/views/view.php

Maybe because there is allowed to have content with html tags.

> Question for those above is , am I doing to much and if what I am doing is ok?

I think it's too much, `esc_attr()` should be enough.

> do I need to escape the class name and for example color-picker option type output before outputting in head also?

Better escape it.

----

I personally don't trust any user input so I escape/sanitize every time a do output (except cases when raw/html is allowed in that value).

These are the methods that I use to safe untrusted input:

* On db queries I do `$wpdb->prepare(...)`
* On value output in html

    * If it's for attr value `esc_attr()`
    * Other cases `fw_htmlspecialchars()` (this also works for attr value, but `esc_attr()` is shorter)

    Note that `esc_attr()` can change/"fix" your data and in cases when it must be exactly as the original value, better use `htmlspecialchars()`. In the past I had a problem with this http://wordpress.stackexchange.com/questions/162918

There are other escape/sanitize functions in WordPress, but I hadn't necessity to use them.

**Comment by danyj** [comment]
@moldcraft  thnx much for the info
