### ISSUE TITLE
Extend all builder shortcodes to set custom css class

### ISSUE THREAD

**Issue by tzimpel** [ThemeFuse/Unyson#786]
Hi,

I am quite new to unyson. I am trying to extent the page builder to display an input field in every shortcode where I can set a custon css class to the shortcode, which is then added to the html element in the front end view.

Is there a possibility to automatically add this functionality to all shortcodes, or do I have to extend each shortcode with this functionality? And do I have to copy the original shortcode to framework-extensions, or is it possible to hook into the existing shortcode to extend it?

**Comment by moldcraft** [comment]
The only way is to extend every shortcode.

* Copy `unyson/framework/extensions/shortcodes/shortcodes/{shortcode}/options.php` to `{theme}/framework-customizations/extensions/shortcodes/shortcodes/{shortcode}/options.php`

    and add your class option

    ```php
    'custom_class' => array('type' => 'text'),
    ```

* Then output that value in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/{shortcode}/views/view.php`

http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content
