### ISSUE TITLE
Required option inside multi-picker trows js error

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#788]
If you place a required option inside a multi-picker option that is not visible on different option select , we get js error 

    An invalid form control with name='fw_edit_options_modal[type][mfp-inline][modalid]' is not focusable.

video  http://screencast.com/t/4MtVAKFsEJ3g

**Comment by moldcraft** [comment]
Do you have any suggestion how to fix this?

**Comment by danyj** [comment]
@moldcraft   check if required is visible than check for input

**Comment by danyj** [comment]
check parents display / visiblity

**Comment by moldcraft** [comment]
1. What if that required option is in another tab, or is inside a closed box?
2. Can you make your modal without required options?

**Comment by danyj** [comment]
I can make my modal id to be always present yes, but others might run in to this 
we might get this to work 
http://stackoverflow.com/questions/123999/how-to-tell-if-a-dom-element-is-visible-in-the-current-viewport/7557433#7557433

http://jsfiddle.net/AndyE/cAY8c/

**Comment by moldcraft** [comment]
I will expand

> What if that required option is in another tab, or is inside a closed box?

For e.g. you have tabs in modal, inside the second tab there is a required option. The user doesn't open the second tab and press Save. What are you asking to implement, is to not display the warning if the option is not visible, then the required attribute you set for that option (that is inside the second tab) has no sense, it's like it is not required.

I would close this issue if you can make that option not required. If someday someone will face this problem again, we will reopen it and dispute how to fix it.

**Comment by danyj** [comment]
I understood that , no worries , I see what you are saying . Il work around it , if someone else has an issue we can continue.
