### ISSUE TITLE
ID's and Classes for Elements in builder

### ISSUE THREAD

**Issue by qamarr** [ThemeFuse/Unyson#789]
Hi,

I really like the builder so far. However it seems to be missing something essential in my opinion.
Most builders have the option to add an id or class name to an element which will really help in styling.

Otherwise great work and look forward to seeing some other extensions.

Qamar

**Comment by moldcraft** [comment]
Hello,
Thank you for the kind words.

> Most builders have the option to add an id or class name to an element which will really help in styling.

We think that such options are too complicated and has no sense for a regular (non developer) theme users.

You can add id or class manually from your theme, check [this tutorial](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head)
