### ISSUE TITLE
Add new Walker_Nav_Menu

### ISSUE THREAD

**Issue by gabyferman** [ThemeFuse/Unyson#79]
Hi,

I've started to play around with this framework and it looks good, only thing is I'm having trouble adding a new class to extend Walker_Nav_Menu, so I can modify the custom menu widget from wordpress. I've done it in other templates but I'm not sure where the code should go for it to work with this framework. Here is how I've been doing it until now:

custom_widgets.php
```PHP
require_once( 'custom_walker.php' );

class New_Nav_Menu_Widget extends WP_Nav_Menu_Widget {

	function widget( $args, $instance ) {
		// get menu
		$nav_menu = !empty( $instance['nav_menu'] ) ? wp_get_nav_menu_object( $instance['nav_menu'] ) : false;

		if ( !$nav_menu ) return;

		$instance['title'] = apply_filters( 'widget_title', empty( $instance['title'] ) ? '' : $instance['title'], $instance, $this->id_base );

		echo $args['before_widget'];

		if ( !empty($instance['title']) ) echo $args['before_title'] . $instance['title'] . $args['after_title'];

		wp_nav_menu( array(
			'menu' => $nav_menu,
			'walker' => new walker_nav
		) );

		echo $args['after_widget'];
	}

}
```

custom_walker.php
```PHP
class walker_nav extends Walker_Nav_Menu {

	public function start_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
		global $wp_query;

		$indent = ( $depth ) ? str_repeat( "\t", $depth ) : '';
		$class_names = $value = '';
		$classes = empty( $item->classes ) ? array() : ( array ) $item->classes;
		$classes = empty( $item->classes ) ? '' : $item->classes;
		$classes[] = ( $item->current ) ? 'active' : '';
		$class_names = join( ' ', apply_filters( 'nav_menu_css_class', array_filter( $classes ), $item, $args ) );
		$class_names = $class_names ? ' class="' . esc_attr( $class_names ) . '"' : '';
		$id = apply_filters( 'nav_menu_item_id', 'nav-item-'. $item->ID, $item, $args );
		$id = $id ? ' id="' . esc_attr( $id ) . '"' : '';
		$output .= $indent . '<li' . $id . $value . $class_names .'>';

		$attributes = !empty( $item->url ) ? 'href="' . esc_attr( $item->url ) . '"' : '';
		$attributes .= !empty( $item->target ) ? ' target="' . esc_attr( $item->target ) . '"' : '';
		$attributes .= !empty( $item->xfn ) ? ' rel="' . esc_attr( $item->xfn ) . '"' : '';

		switch ( $item->url ) {
			case '#separator' :
				$open_tag = '<span class="separator">';
				$close_tag = '</span>';
				break;
			default :
				$open_tag = '<a ' . $attributes . '>';
				$close_tag = '</a>';
				break;
		}

		$item_output = $args->before . $open_tag . $args->link_before;
		$item_output .= apply_filters( 'the_title', $item->title, $item->ID );
		$item_output .= $args->link_after . $close_tag . $args->after;
		$output .= apply_filters( 'walker_nav_menu_start_el', $item_output, $item, $depth, $args );

	}

	public function display_element( $element, &$children_elements, $max_depth, $depth, $args, &$output ) {
		if ( !$element ) return;

		$id_field = $this->db_fields['id'];

		// display this element.
		if ( is_object( $args[0] ) ) 	$args[0]->has_children = !empty( $children_elements[ $element->$id_field ] );

		parent::display_element( $element, $children_elements, $max_depth, $depth, $args, $output );
	}
}
```

functions.php
```PHP
if ( include( 'custom_widgets.php' ) ) {
	add_action( 'widgets_init', 'load_custom_widgets' );
}

function load_custom_widgets() {
	unregister_widget( 'WP_Nav_Menu_Widget' );
	register_widget( 'New_Nav_Menu_Widget' );
}
```

**Comment by danyj** [comment]
Same thing here , I can use my custom walker when megamenu is disabled but even with instructions above I cant add custom walker markup. Just like @gabyferman I dont want to disable the megamenu but rather add/change the current megamenu output. 

Like this http://wordpress.stackexchange.com/questions/177676/how-to-override-menu-markup/177679?noredirect=1#comment259199_177679

My custom walker is located in theme/inc/includes

**Comment by danyj** [comment]
You guys really need more instructions and docs. 
@gabyferman 

Copy class-fw-theme-menu-walker.php
to framework-customizations\extensions\megamenu\includes
rename the file to  class-fw-my-menu-walker.php
rename the class from 

    class FW_Theme_Menu_Walker extends Walker_Nav_Menu

to   

    class FW_My_Menu_Walker extends FW_Theme_Menu_Walker

add this in theme/inc/includes/menus.php

	add_filter('wp_nav_menu_args', '_topmenu_wp_nav_menu_args', 100);
	
	function _topmenu_wp_nav_menu_args($args){
		
		$args['walker'] = new FW_My_Menu_Walker ();
		return $args;
	}

now you can edit class-fw-my-menu-walker.php and add/remove additional markup to unyson megamneu

**Comment by moldcraft** [comment]
> You guys really need more instructions and docs. 

I added this task in todo but we are busy with other things and will review the docs later, sorry.

You are free to make pull requests to [documentation repository](https://github.com/ThemeFuse/Unyson-Documentation).

**Comment by moldcraft** [comment]
P.S. Currently I am investigating megamenu issues and I found a recommendation in [this comment](https://github.com/ThemeFuse/Unyson/issues/79#issuecomment-64547573) to add a class in `[/path/to/theme]/framework-customizations/extensions/megamenu/static.php`, it is not good to do that, [`static.php`](http://manual.unyson.io/en/latest/extensions/directory-structure.html#content) is mean to be used only for `wp_enqueue_style()` and `wp_enqueue_script()`. Better to create a file in `[/path/to/theme]/framework-customizations/extensions/megamenu/includes/manual/custom-walker.php`  and include it from `[/path/to/theme]/framework-customizations/extensions/megamenu/hooks.php` on some action.

P.P.S. I don't have a solution for this issue yet. Soon...

**Comment by moldcraft** [comment]
@gabyferman @danyj You can install manually [v1.0.4](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/releases/tag/v1.0.4) to `plugins/unyson/framework/extensions/megamenu` *(because it's not released yet)* and extend the mega-menu walker like this:

* Create `{theme}/framework-customizations/extensions/megamenu/includes/class-fw-ext-mega-menu-custom-walker.php`

```php
<?php if (!defined('FW')) die('Forbidden');

class FW_Ext_Mega_Menu_Custom_Walker extends FW_Ext_Mega_Menu_Walker
{
	function start_lvl( &$output, $depth = 0, $args = array(), $class = 'sub-menu' ) {
		fw_print('Hello');
		
		return parent::start_lvl($output, $depth, $args, $class);
	}

	// other customizations ...
}
```

* Create `{theme}/framework-customizations/extensions/megamenu/hooks.php`

```php
<?php if (!defined('FW')) die('Forbidden');

// replace default walker
{
	remove_filter('wp_nav_menu_args', '_filter_fw_ext_mega_menu_wp_nav_menu_args');

	/** @internal */
	function _filter_theme_ext_mega_menu_wp_nav_menu_args($args) {
		$args['walker'] = new FW_Ext_Mega_Menu_Custom_Walker();

		return $args;
	}
	add_filter('wp_nav_menu_args', '_filter_theme_ext_mega_menu_wp_nav_menu_args');
}
```

**Comment by danyj** [comment]
ok that worked also, had to change few private functions to protected since you changed them but the 
fa is not loading in frontend anymore. 

I see is moved to static.php but is not loading
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/static.php

**Comment by moldcraft** [comment]
[fixed](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/commit/f1ede2d03f72a208b9305f372149b70fdc737c5b)

**Comment by danyj** [comment]
works now. thnx!

**Comment by danyj** [comment]
question , I have a fallback walker in case unyson is disabled or not installed yet. 
is it ok if I used the 
    
     theme/inc/includes/menus.php

instead 
   {theme}/framework-customizations/extensions/megamenu/hooks.php

for this 

	/**
	 * Use custom walker
	 */
	function _thz_top_menu_walker($args){
		
		if(class_exists('FW_Walker_Topmenu_Menu')){
			
			$args['walker'] = new FW_Walker_Topmenu_Menu();
			
		}else{
			
			$args['walker'] = new Walker_Topmenu_Menu();
			
		}
		return $args;
	}
	
	add_filter('wp_nav_menu_args', '_thz_top_menu_walker', 100);

**Comment by moldcraft** [comment]
Yes. You can move the code from `{theme}/framework-customizations/extensions/megamenu/hooks.php` to `{theme}/inc/hooks.php` and make sure it will not throw errors if megamenu is disabled. *Placing the code in `{theme}/inc/includes/menus.php` will work, but `{theme}/inc/hooks.php` was created especially for actions and filters.*

**Comment by danyj** [comment]
ah , ok , thnx . I see your point.
