### ISSUE TITLE
Unyson giving issue

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#790]
The website was working fine for few days. But again the problem have been started.

1 thing i have observed, if i uninstall unyson and install it back the website works fine. Check this image

![website-issue](https://cloud.githubusercontent.com/assets/6223399/9197705/771c847c-4058-11e5-8136-80e4c38554a2.png)

**Comment by llemurya** [comment]
@Ataurr please describe more detailed how to reproduce this bug, and what you mean when you say that the problem have been started again?

**Comment by moldcraft** [comment]
Yesterday we released a new version. Today a colleague reported that on his site extensions disappeared. And now you report the same. So again it seems that it's related to WordPress auto-update functionality. Tomorrow we will release a new version with a little debug log for update https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/114 . Please update tomorrow, or install it now manually, and if this problem will happen again, give us your `fw-update.log`.

Let's continue the discussion in https://github.com/ThemeFuse/Unyson/issues/263

btw Which Unyson version do you have?
