### ISSUE TITLE
Divider shortcode whitespace should use margin

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#792]
You have padding set in divider for Whitespace option and advise users to use negative one 
http://prntscr.com/83s8pq
negative padding in CSS does not work , 

http://prntscr.com/83s8g8

switching this to a margin would work as expected. 

http://prntscr.com/83s8zd

**Comment by duongancol** [comment]
@danyj : The divider for whitespace should is height inline style, you can add padding or margin to option of colum or section

**Comment by danyj** [comment]
@duongancol  mine is different , this one is bug report for Unyson default divider, not question for help. There is no negative padding in CSS , only negative margin

**Comment by duongancol** [comment]
@danyj :+1:
