### ISSUE TITLE
Vimeo background video not working

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#795]
Using Vimeo as a video background in sections doesn't seem to be working, is Vimeo supported?

YouTube works fine however.

This is the output when using Vimeo:

```
<div class="wallpaper-container">
    <div class="wallpaper-media wallpaper-video" style="height: 420px; top: 0px;">
        <video loop="" muted=""></video>
    </div>
</div>
```

I've tried the following URLs as I'm not sure which one should be used:
- https://vimeo.com/lyndavimeo/aaron-draplin
- https://vimeo.com/113751583
- https://player.vimeo.com/video/113751583

Thanks

**Comment by llemurya** [comment]
@martinburdon we use a jQuery plugin by [Formstone](https://formstone.it/components/background/) , we answer them about vimeo support, the answer was that Vimeo can only get the json with video url if you have a [pro account](https://formstone.it/components/background/).

**Comment by martinburdon** [comment]
Ah ok so you must have a pro Vimeo account in order to use Vimeo with the section background?

**Comment by llemurya** [comment]
@martinburdon Yes the end user must have the pro Vimeo account, and must set the url of the video to the plugin ,not a vimeo url, but my opinion is that for an video background youtube is the right choice.I close the issue. Thanks

**Comment by martinburdon** [comment]
Thank you.
