### ISSUE TITLE
CSS Helper: Responsive Tools classes not working

### ISSUE THREAD

**Issue by tzimpel** [ThemeFuse/Unyson#796]
Hi,

I am trying to use the Responsive CSS Classes from http://manual.unyson.io/en/latest/helpers/css.html#responsive-utilities to hide some elements from mobile view. However, none of the classes are defined anywhere. Do I have to enqueue another CSS file? The frontend grid is working without problems.

**Comment by moldcraft** [comment]
Right [at the beginning](http://manual.unyson.io/en/latest/helpers/css.html#content) is shown how to enqueue css helpers.

* Add `fw` to your style dependencies

    ```php
    wp_register_style(..., ..., array('fw'));
    ```

* Or enqueue it explicitly

    ```php
    wp_register_style('fw');
    ```

The style is registered [here](https://github.com/ThemeFuse/Unyson/blob/a7c222be98c147b44e399d4f5eb02d646c050715/framework/core/components/backend.php#L308-L313)

**Comment by tzimpel** [comment]
* If I enqueue it explicidly, nothing gets enqueued. This is what I did before asking.
* If I add it as dependency to my style.css, neither the fw.css nor my style.css is enqueued.

I checked the backend.php and the fw.css and they both exist. Also, the backend.php should register the fw.css as 'fw'. Still, I can't enqueue it in my theme.

Any ideas? Do you need more information?

**Comment by moldcraft** [comment]
> I can't enqueue it in my theme

Do you want to use that style for frontend? I it not meant to be used in frontend, it is not registered in frontend. If you want, copy it in your theme, and enqueue it as your own theme style. Why are you not using bootstrap in frontend?

**Comment by tzimpel** [comment]
I believe this was a misunderstanding then. I believed I could also use that style for frontend. IIf it is not indended for frontend use, I'll switch to a customized version of bootstrap.
