### ISSUE TITLE
How to update theme with Unyson

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson#797]
Anyone have a solution to update theme with Unyson framework easily ?

**Comment by moldcraft** [comment]
Update via which service?

At the moment we have only theme update via github (but we never used it practically), so your theme should be open-source.

**Comment by valeriuzdrobau** [comment]
[WordPress offers this functionality](https://static.md/3d2e08e5171ef63a82a99b08ceb6f85e), only must use the [`pre_set_site_transient_update_themes`](http://www.badpenguin.org/wordpress-theme-repository) filter.

**Comment by maiakhoa** [comment]
Thank @moldcraft and @valeriuzdrobau
This is another way : http://w-shadow.com/blog/2011/06/02/automatic-updates-for-commercial-themes/
I'm finding the solution to update theme from private repository.

**Comment by valeriuzdrobau** [comment]
When you sell your theme you need to send a unique key for this sale, he should put it somewhere in the settings. When your client side script made a  request to your server side script, which should verify the key and  domain (to avoid the use of a single key on more domains than are allowed). If the key is valid and exists, is not exceeded maximum limit of allowed domains and exists a new version for your theme, your server side script need to send in response a dynamically generated link for downloading a zip with your update, the link must be temporary and only for that user. (You can use Amember and their SoftSale plugin)

**Comment by maiakhoa** [comment]
Thank @valeriuzdrobau for your suggestion and the name of tools you provided.
