### ISSUE TITLE
Can we have $cfg['disalbe_correction'] = true; for shortcodes not global ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#799]
I have seen this #455 but I need to disable wrapper on specific shortcodes only
not on all of them. 

can we have 

    $cfg['disable_correction'] = true;

in shortcode config.php not in page-builder/config.php ?

**Comment by danyj** [comment]
If you are wondering what kind of shortcode it is , it is an anchor shortcode used to scroll to it 


	<div class="fw-container">  
		<div class="fw-row">
			<div class="fw-col-xs-12">
				<div  id="anchorid" class="thz-menu-anchor"></div> //  hidden by default
			</div>
		</div>
	</div>

so I end up having wrapper containers around it which do have some margins and padding 

I need to output only 

    <div  id="anchorid" class="thz-menu-anchor"></div>

**Comment by danyj** [comment]
Same thing on dividers

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/e519b1bc316e3745f5a812f9c5f177e65218aa9b#diff-9e5e2527d69c009a81b8ecd730f3957eR12

Test it please

**Comment by danyj** [comment]
Will see to get portal xamp , by the way , masters cant be downloaded due to git issues , 
unyson should really get own cdn or something in case of fallouts like this. trying to get masters since 15 min http://prntscr.com/85s2dv

**Comment by danyj** [comment]
Due to Git being down that cant download theme required extensions , this is not ok 
http://prntscr.com/85s49z
i was able to install unyson since it is on wp, but cant get required extensions since they get pulled from git , and this is even worse 
http://prntscr.com/85s51j

cant save theme settings because required extension is not installed

**Comment by moldcraft** [comment]
Seems like all repositories on github have this problem now. I think it will be fixed soon because all developer are complaining about this right now.

**Comment by danyj** [comment]
I got that , that is not a biggy , but not being able to save theme because of missing extension , or not being able to get required extensions if git is down is an issue

**Comment by moldcraft** [comment]
I think the settings were saved, that popup just shows the first flash message.
Check please if the settings were saved.

**Comment by moldcraft** [comment]
https://status.github.com/

**Comment by danyj** [comment]
so far the fix does not work on custom shortcodes , 

added this in my anchor shortcode 

    $cfg['disable_correction'] = true;

still same output,

**Comment by danyj** [comment]
same on divider , 

this is output 
http://prntscr.com/85se2n 

my anchor and devider have section and columns around them

this is backend http://prntscr.com/85sees

and both of them don't have anything around them in view.php

**Comment by danyj** [comment]
here the config 
http://prntscr.com/85sf46

**Comment by moldcraft** [comment]
[The config is in page builder](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/e519b1bc316e3745f5a812f9c5f177e65218aa9b/config.php#L12), not in every shortcode

**Comment by moldcraft** [comment]
does not work on **custom shortcodes**

Shortcodes with custom builder item types (like column and section) ?

**Comment by danyj** [comment]
duh , i tough you added what I was asking for , ok testing that now

**Comment by moldcraft** [comment]
> in shortcode config.php not in page-builder/config.php

ops, missed that (tired at the end of the day)

I will try that tomorrow.

**Comment by moldcraft** [comment]
Or maybe leave it like it is now?

**Comment by danyj** [comment]
own shortcode config would be much better here is why , 
I never did override for page-builder , 
and have overrides for all shortcodes , so now in order for this to work I must add override 
for builder + config.php  and list shortcodes in there instead just adding a line in existing shortcode override config.php

**Comment by danyj** [comment]
strange 
I do this 

    $cfg['disable_correction'] = array('divider','menuanchor');

both corrections are disabled 

this 

    $cfg['disable_correction'] = array(''menuanchor');

none are disabled

try to get this in per config.php tomorrow please, 

    cfg['disable_correction'] = true;


much cleaner and easier

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/70e5842692e3fb4eadcc81143e328a0d9468c996/config.php#L13-L19

**Comment by danyj** [comment]
this is still no go 
http://prntscr.com/8jde66
http://prntscr.com/8jddts

added in divider config 

    $cfg['disable_correction'] = true;


as you can see it prints , section/row/column and than divider instead divider only

**Comment by Krystus** [comment]
Is there any update on this issue?

**Comment by danyj** [comment]
@Krystus  I think that backup extension has priority right now. after backup v2  those things will be cleaned up. I am waiting for this also.
