### ISSUE TITLE
Content Elements difficult to use

### ISSUE THREAD

**Issue by Delishable** [ThemeFuse/Unyson#800]
When putting content elements into the layout elements, the content icon jumps around and often won't let me place it where I want it. PLEASE fix this, as it makes it impossible to use easily, takes WAY too much extra time and is frustrating.
Thank you!

**Comment by moldcraft** [comment]
Hello,

This is the next task in my todo list.

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25
