### ISSUE TITLE
Unyson framework admin.js code is making other plugins in the backend not work if they have tabs

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#801]
Hey, the Unyson framework admin.js code is making other plugins in the backend not work if they have tabs.

YOAST SEO and WP Rocket settings have tabs, but those tabs do not work. When I inspect element and debug, I see admin.js appending:

(jQuery(document).ready(function($) {
    "use strict";
    jQuery('.fw_form_fw_extension_settings .fw-options-tabs-wrapper').tabs({ selected: 2 });

    jQuery(".fw_form_fw_extension_settings .fw-options-tabs-wrapper ul li:nth-child(2)").addClass("ui-tabs-active ui-state-active");)

**Comment by danyj** [comment]
it is just appending js for own tabs , and the one you show are for form extensions. 

do you have any js errors ?

**Comment by moldcraft** [comment]
We don't have such file named `admin.js` https://github.com/ThemeFuse/Unyson/tree/master/framework/static/js

Maybe it is a theme file?

**Comment by moldcraft** [comment]
* I can find the string `.fw_form_fw_extension_settings .fw-options-tabs-wrapper` in Unyson
* We don't have `admin.js` in Unyson https://github.com/ThemeFuse/Unyson/tree/master/framework/static/js

Are you sure `admin.js` is located in `unyson/` directory?

**Comment by darwinteam** [comment]
You're right guys, this is an issue related to the theme I guess. The admin.js file look like this:

`jQuery(document).ready(function($) {
    "use strict";

    var fw_page_header = jQuery('#fw-options-box-page-side');
    var fw_page_template = jQuery('#page_template');
    var fw_builder_button = jQuery('.page-builder-hide-button');
    var fw_default_editor_button = jQuery('#wp-content-media-buttons .button-primary');

    // if on page ready template is without sidebar hide header image option
    if(fw_page_template.val()=='page-builder.php'){
        fw_page_header.hide();
    }
    else{
        fw_page_header.show();
    }

    // on click visual page editor button set page template "visual page"
    jQuery('#wp-content-media-buttons').on('click', '.button-primary', function(){
        fw_page_template.val('page-builder.php');
        fw_page_header.hide();
    });

    // on click default editor button set page template "default template"
    jQuery('.page-builder-hide-button').on('click', function(){
        fw_page_template.val('default');
        fw_page_header.show();
    });

    // on change page template hide header image option
    fw_page_template.on('change', function(){
        if( fw_page_template.val() == 'default'){
            fw_page_header.show();
            fw_builder_button.trigger('click');
        }
        else{
            fw_page_header.hide();
            fw_default_editor_button.trigger('click');
        }
    });

    jQuery('.fw_form_fw_extension_settings .fw-options-tabs-wrapper').tabs({ selected: 2 });

    jQuery(".fw_form_fw_extension_settings .fw-options-tabs-wrapper ul li:nth-child(2)").addClass("ui-tabs-active ui-state-active");

});`

In Chrome Inspector the issue is on this line:     jQuery('.fw_form_fw_extension_settings .fw-options-tabs-wrapper').tabs({ selected: 2 });

Don't know what this an be related to.
