### ISSUE TITLE
Styling specific sections and columns from page builder

### ISSUE THREAD

**Issue by galkowskit** [ThemeFuse/Unyson#802]
OK, I can't seem to understand the way it should be done. If you take a look at ```scratch-parent/framework-customizations/extensions/shortcodes/shortcodes/column/options.php``` and the included ```README.md``` you can see that Unyson can add options for specific rows. What I want to do is add styling options there like background color, etc.

I can add new options just fine and let's say I want to go the easy and dirty way of including an internal ```<style></style>``` tag with all the options for a given page.

**How can I check for which section/row was the option actually used on?**

**Comment by moldcraft** [comment]
I hope [this is the answer](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head) for your question.

If not, please try to explain again in other words.

**Comment by galkowskit** [comment]
Ah! Yes. Exactly. Just one problem remains. Because ```(...)/shortcodes/shortcodes/column```'s view.php is being overwritten by my theme the widgetized container is gone. Any way to only add CSS  to existing shortcode without touching view.php? Or: is the code for original ```column/views/view.php``` available somewhere? I would like it to be able to contain other elements like it normally can.

**Comment by moldcraft** [comment]
Original view is in

```
wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/column/view.php
```

**Comment by galkowskit** [comment]
Got it, thanks for you help.
