### ISSUE TITLE
Left Side Tabs Like Theme Options in Post or Page Meta

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#803]
Hello @moldcraft 

Is there any possibility to move tabs on left side just like theme options settings.

Thanks

**Comment by llemurya** [comment]
@wpthemes786 , yes you can set at your container the parameter `'context' => 'side'` and it will be moved on left side.

**Comment by llemurya** [comment]
```php
		array(
			'context' => 'side',
			'title'   => __( 'Slider Configuration', 'fw' ),
			'type'    => 'box',
			'options' => array( /*your options */ )
		);

**Comment by moldcraft** [comment]
@wpthemes786 No, only Theme Settings page has this feature.

**Comment by wpthemes786** [comment]
@moldcraft  Thanks
