### ISSUE TITLE
fw_resize reduces image quality

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#804]
Hi!
As I said in the title when I used fw_resize to my attachment image of a post, it reduced the quality of an image.
Please see my example here:
Original: 
![screenshot at aug 18 11-12-06](https://cloud.githubusercontent.com/assets/1773011/9322218/3ffa9050-459a-11e5-96e7-6233ad169098.png)
After:
![screenshot at aug 18 11-12-34](https://cloud.githubusercontent.com/assets/1773011/9322220/470b9506-459a-11e5-8f0a-4a9775376e51.png)

**Comment by duongancol** [comment]
It's the same when fw_reisze function is used in Slider extension

**Comment by valeriuzdrobau** [comment]
Hello, `fw_resize()` uses `WordPress Image Editor`, so, you can use the following code to set the quality of your resized images:
```
add_filter( 'jpeg_quality', '_filter_theme_image_full_quality' );
add_filter( 'wp_editor_set_quality', '_filter_theme_image_full_quality' );

function _filter_theme_image_full_quality( $quality ) {
    return 100;
}
```
