### ISSUE TITLE
Set the sizes for fw_theme_post_thumbnail()

### ISSUE THREAD

**Issue by maryslen** [ThemeFuse/Unyson#806]
Hi,

Can't find anywhere options for fw_theme_post_thumbnail() function. Where can i set up different values for this?

Thank you!

**Comment by moldcraft** [comment]
That functions has nothing with Unyson. [It's in Scratch](https://github.com/ThemeFuse/Scratch-Theme/blame/f54cf0c2ed2a917f79414c67abcab0b76e5a4058/scratch-parent/inc/helpers.php#L301-L353) theme. I don't remember exactly it's origin, but most likely we just copied (and renamed) it from the [Twenty Fourteen](https://wordpress.org/themes/twentyfourteen/) theme.

----

`fw_theme_` [prefix](http://manual.unyson.io/en/latest/convention/prefixes.html#theme) is for theme functions.

----

If it's your theme, do whatever you want in your theme (delete or change it). If you bought a theme with this function, copy it in your child theme, rename and change it.
