### ISSUE TITLE
Cant download extensions after install, blank popup

### ISSUE THREAD

**Issue by petterannerwall** [ThemeFuse/Unyson#807]
After clicking install a blank popup appears, clicking ok makes the page refresh and the extension is not installed. This is happening using blank wordpress install.  

Any help would be much appreciated, was looking forward to trying unyson out!

![unyson_blank_popup](https://cloud.githubusercontent.com/assets/5909669/9363691/28ad6814-46a8-11e5-9adf-53d066850017.PNG)

**Comment by moldcraft** [comment]
Please open this url

```
/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=page-builder
```

and see if there is any error on extension install.

**Comment by petterannerwall** [comment]
Erhm, strange.... says i dont have sufficient permissions to view that page.

Im logged on as the user i created during the installation which of course is a administrator.

**Comment by moldcraft** [comment]
Maybe you replaced the entire url

![](https://static.md/8ab8b4044d5c5d17f0c14af42d7b090d.png)

**Comment by petterannerwall** [comment]
Sorry but i didnt :/

**Comment by moldcraft** [comment]
Can you give me access to your site? If yes, send the details to `moldcraft[at]email.com`

**Comment by petterannerwall** [comment]
Just sent you a mail!

**Comment by moldcraft** [comment]
I was able to open

```
http://www.___.se/core/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=page-builder
```

then I clicked install and I get an error

```
Cannot download the "Shortcodes" extension zip. There are no HTTP transports available which can complete the requested request.
```

**Comment by moldcraft** [comment]
The solution is to install php curl extension.
