### ISSUE TITLE
Extension download fail with empty message

### ISSUE THREAD

**Issue by Sungod3000** [ThemeFuse/Unyson#811]
Hi,

Im unable to download any of the extensions, I always get an empty error message. I didnt find any reports about it either.

![2015-08-21 08_12_32-greenshot](https://cloud.githubusercontent.com/assets/6022555/9402362/f26c5d88-47dc-11e5-9568-2b810955603c.jpg)

**Comment by danyj** [comment]
git again , see this
https://github.com/ThemeFuse/Unyson/issues/799#issuecomment-131954944

**Comment by moldcraft** [comment]
Hi,

Please open

```
/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=page-builder
```

click Install and see if there is any error message

**Comment by Sungod3000** [comment]
No, still cant get it. 

Im usually a joomly guy so I imagine there is a manual way of installing the extension packets via ftp?

**Comment by moldcraft** [comment]
1. Have you opened

    ```
    http://YOUR_SITE/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=page-builder
    ```

2. If yes. Have you clicked on the Install Extension button?
3. If yes. Is there any error message displayed?

> is a manual way of installing the extension packets via ftp?

Yes you can install extensions manually, but you have to know their path (because some are nested) and anyway you will need to update them when we release updates, so you still need to install them from the admin page.

If you are familiar with git, you can install them all with [this script](https://gist.github.com/moldcraft/dceae5f6081f72cc1153)

**Comment by Sungod3000** [comment]
Yes 

Downloading the "Shortcodes" extension...

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases.

    Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases.

**Comment by moldcraft** [comment]
The site where the script fetches the releases works

http://github-api-cache.unyson.io/repos/ThemeFuse/Unyson-Shortcodes-Extension

So the problem can be in your hosting denying requests to `github-api-cache.unyson.io`

Can you add in `{theme}/functions.php`

```php
if (is_admin()) {
    print_r(file_get_contents('http://github-api-cache.unyson.io'));
}
```

[Similar issue](https://github.com/ThemeFuse/Unyson/issues/215#issuecomment-72621874)

**Comment by Sungod3000** [comment]
Do I use on of the stadard themes for this and does it have to be active?

**Comment by moldcraft** [comment]
The theme has no impact on extensions install/uninstall process.

**Comment by Sungod3000** [comment]
ok i thought so as well. you wrote "Can you add in {theme}/functions.php" there are multiple functions.php, so i was wondering which of those I should add code to

**Comment by moldcraft** [comment]
I thought the easiest/known file is that. You can add that code anywhere you want, just execute it.

**Comment by Sungod3000** [comment]
Ok great, just put the whole thing on my paid hosting account and now it loads all the extensions. Thanks for the help
