### ISSUE TITLE
Unyson Translation plugin error

### ISSUE THREAD

**Issue by sensestudio** [ThemeFuse/Unyson#813]
Hi, 
i got this warning after activating Unyson translate plugin,
Warning: Missing argument 2 for FW_Extension_Translate_Posts::generate_translation_columns() in /home/myusername/public_html/wp-content/plugins/unyson/framework/extensions/translation/extensions/translate-posts/class-fw-extension-translate-posts.php on line 341

the plugin seem working well, i can add translation for my pages.
but i need to remove that warning because it showing more warning if i have more pages

Can anyone help me ? 
THank you

regards
YA

**Comment by llemurya** [comment]
@sensestudio can you send the ftp details at dev-team@unyson.io to inspect the bug , because normally it must works.Thanks.I am waiting for your response.

**Comment by sensestudio** [comment]
Hi, i sent an email with my FTP details to dev-team@unyson.io yesterday,
Thank you

**Comment by llemurya** [comment]
It was fixed in the latest version of the extension.
