### ISSUE TITLE
Options for Pages

### ISSUE THREAD

**Issue by maryslen** [ThemeFuse/Unyson#814]
Is it possible to set options for simple pages? For ex. for selecting page format with/without sidebar? Thank you!

**Comment by valeriuzdrobau** [comment]
Create a file with options: `framework-customizations/theme/options/posts/page.php` like `framework-customizations/theme/options/posts/post.php`.

**Comment by moldcraft** [comment]
* [This](https://static.md/5b8ccffb5ac49acf82f26f3455a4312b.png) is from WP not from Unyson
* with/without sidebar https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/43

**Comment by maryslen** [comment]
Thanks a lot!
