### ISSUE TITLE
add link preventdefaut() to builder elements

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#815]
All builder elements when clicked on jump the page up. Please add 

    e.preventdefault();

to prevent the jump

to test , add new page , scroll  about 100px down , click on section or any builder element and page will jump up

**Comment by moldcraft** [comment]
can't reproduce

maybe you have javascript errors in console?

**Comment by danyj** [comment]
no , no errors , no bugs or issues , I click on section or column and page goes up

**Comment by moldcraft** [comment]
https://vid.me/6npm

which browser do you use?

**Comment by danyj** [comment]
Im traveling , right now , macbook pro , chrome, will see to make a video

**Comment by danyj** [comment]
here it is  http://screencast.com/t/d6bM9f20C14

**Comment by moldcraft** [comment]
The page is scrolling at the end of the builder when you add a new element. This works fine and is useful when the builder is bigger than the page, but in your case it is confusing. I'll prevent the scroll if the builder end is visible.

**Comment by moldcraft** [comment]
Test please
