### ISSUE TITLE
Add custom classes to unyson form extension ? Urgent

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#816]
Hello @moldcraft 
I want to use bootstrap classes in unyson form extension. 
How it would be done. Needs Urgent Solution.

Thanks.

**Comment by moldcraft** [comment]
Hello

Have you tried this?
http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid

**Comment by wpthemes786** [comment]
Its very confusing for me. All i want to know how to change the html structure in form extension. 

@moldcraft Thanks

**Comment by moldcraft** [comment]
* [Here](https://github.com/ThemeFuse/Unyson-Forms-Extension/tree/master/includes/option-types/form-builder/items) are all form items
* To overwrite their views create [`{theme}/framework-customizations/extensions/forms/form-builder/items/{item-type}/views/view.php`](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/27d43834c26c4d5f88527d7d67bdb5e2c7926837/includes/option-types/form-builder/extends/class-fw-option-type-form-builder-item.php#L32). Each item renders in frontend [this way](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/d93b3d7d81f808da6426386d109edf6d5828d37a/includes/option-types/form-builder/items/email/class-fw-option-type-form-builder-item-email.php#L192)

**Comment by wpthemes786** [comment]
@moldcraft  Thanks. i will confirm you shortly about success and close the ticket if not i will disturb you again.

**Comment by moldcraft** [comment]
No problem.

**Comment by wpthemes786** [comment]
Hello @moldcraft .
Sorry to disturb you again.

I am bit confused how to do this.

Could you be more illustrative.

Many Thanks.

**Comment by moldcraft** [comment]
Create

```
{theme}/framework-customizations/extensions/forms/form-builder/items/email/views/view.php
```

with

```php
<?php echo 'Hello Wold';
```

**Comment by wpthemes786** [comment]
@moldcraft  you rocks.
The real question is how to override css classes on these fields.

**Comment by moldcraft** [comment]
which classes? give me a screenshot please

**Comment by wpthemes786** [comment]
i have not any screen shot. i am just struggling to make my structure to look like demo version.

And i need to little bit change in div structure or classes.

so i get the idea from you but do not know how to go further.

Your help is much appreciated.

Thanks

**Comment by moldcraft** [comment]
I am confused which html structure are you talking about, I need a screenshot to see which elements you want to change.

**Comment by wpthemes786** [comment]
ok @moldcraft here are the following screenshots.

![demo](https://cloud.githubusercontent.com/assets/12461946/9500541/800f44b4-4c3f-11e5-81ab-d5573e6657dd.png)

This is the demo which i want to exactly look like in my theme.

![changed_to_demo](https://cloud.githubusercontent.com/assets/12461946/9500552/98c9425c-4c3f-11e5-81cf-8ff829520420.png)

Thanks

**Comment by duongancol** [comment]
it seem that the options column of the multiple choice of Contact form didn't work. Please see here: http://prntscr.com/8965ti

**Comment by wpthemes786** [comment]
i need to put .form-control classes from css bootstrap in unyson form extension. and i dont know where  should i go.

**Comment by moldcraft** [comment]
> i need to put .form-control classes from css bootstrap in unyson form extension. and i dont know where should i go.

You can overwrite the views (I already explained how to do that twice)

Again: Copy the [original view](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/email/view.php) in

```
{theme}/framework-customizations/extensions/forms/form-builder/items/email/views/view.php
```

and change it however you want.

**Comment by wpthemes786** [comment]
@moldcraft  i have echoed helloworld in view.php file as u have already mentioned above.
i am confused here what code should i wrote on view.php file to overwrite the functionality.

Can you give me some example it will be very helpful for me.

Thanks for your kind help.

**Comment by wpthemes786** [comment]
@moldcraft  Many Thanks.
