### ISSUE TITLE
How can i change 'Add' text at Addable Box?

### ISSUE THREAD

**Issue by coderontheroad** [ThemeFuse/Unyson#819]
I try to use Addable Box. I want to make translate ready, but i can't find how can I change 'Add' button text?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/0f7cb050d7db8806f0773652907f3d6108567019/framework/includes/option-types/addable-box/class-fw-option-type-addable-box.php#L186

**Comment by coderontheroad** [comment]
Thank you very much.

**Comment by moldcraft** [comment]
You are welcome
