### ISSUE TITLE
How can i change Theme Settings default texts?

### ISSUE THREAD

**Issue by coderontheroad** [ThemeFuse/Unyson#820]
I am trying to implement Unyson for my new theme. Thats great framework i love it. But it has poor documantation. I don't know is it right way but I create options page like this;

    /* 
    file: framework-customizations/theme/options/settings.php
    Theme Settings Page 
    */

    $options = array(
    	'general_tab' => array(
    	    'type' => 'tab',
    	    'title' => 'General Settings',
    	    'options' => array(
    	        
    	    ),
    	),
    );

I can see Theme Settings page but how can I change 'Theme Settings' text in the left admin menu. And how can I change  buttons texts like 'Save Changes' or 'Reset Options'. And how can i change 'Blog Posts' or 'Blog Categories' texts. Or can i disable Blog prefix from posts?

I hope i learn Unyson first and then i can help for developing more rich documantation :)

**Comment by coderontheroad** [comment]
Okay i found from the core. components/backend.php at 509 line. It looks like this;
    __( 'Theme Settings', 'fw' ),

But this is problem for use in themes, because we can't translate with theme language files.
Is this like a bug? I solve my problem but i think that should be change.

**Comment by moldcraft** [comment]
> how can I change 'Theme Settings' text in the left admin menu.

You can use [this action](https://github.com/ThemeFuse/Unyson/blob/0f7cb050d7db8806f0773652907f3d6108567019/framework/core/components/backend.php#L478-L482) to register the Theme Settings menu in another position.

> And how can I change buttons texts like 'Save Changes' or 'Reset Options'.

At the moment you can't. I will add this possibility in the next version.

> And how can i change 'Blog Posts' or 'Blog Categories' texts.

To disable [these actions](https://github.com/ThemeFuse/Unyson-Blog-Extension/blob/10b8eca2314e5fc0e2a005fddc7095590a1e7b9b/class-fw-extension-blog.php#L13-L16)

```php
add_action('fw_init', '_action_theme_disable_fw_blog_ext_actions');
function _action_theme_disable_fw_blog_ext_actions() {
    $blog_ext = fw_ext('blog');

    if (!$blog_ext) return;

    remove_action( 'admin_menu', array( $blog_ext, '_admin_action_rename_post_menu' ) );
    add_action( 'init', array( $blog_ext, '_admin_action_change_post_labels' ), 999 );
    add_action( 'init', array( $blog_ext, '_theme_action_change_post_labels' ), 999 );
}
```

to change the texts, inspect [the same actions](https://github.com/ThemeFuse/Unyson-Blog-Extension/blob/10b8eca2314e5fc0e2a005fddc7095590a1e7b9b/class-fw-extension-blog.php#L13-L16) and use the same technique.

> I hope i learn Unyson first and then i can help for developing more rich documantation :)

That would be awesome!

**Comment by coderontheroad** [comment]
I am getting familiar with the core codes :) I found the 'Save Changes' and 'Reset Options' buttons at views/backend-settings-form.php and much much more for multilanguage like saving info popup.

Just hang in there a little time later i hope i can start answer the issues and helping people and you have more time for development :) Thanks for the informations...

**Comment by moldcraft** [comment]
> Just hang in there a little time later i hope i can start answer the issues and helping people and you have more time for development :)

![](https://static.md/8f4f57dd9aaaf17dd9f93904f8847328.png)

**Comment by toleabivol** [comment]
Now you should use `add_theme_page` instead of `add_menu_page`
