### ISSUE TITLE
html in text blocks renders as plain text

### ISSUE THREAD

**Issue by runebaas** [ThemeFuse/Unyson#821]
Hi there

i'm trying to make links in several different content elements with the page builder, but whenever i do it, it renders like this 

![like this](http://i.imgur.com/TkmZKDT.png)

I have tried to change the database entry and then it works, but those text fields get edited a lot and it's really annoying... Is there a solution to this, am i missing a settings toggle somewhere?

**Comment by moldcraft** [comment]
I tried on my side and this happens only when you paste html in wp-editor in visual tab mode.

How to reproduce this?

**Comment by runebaas** [comment]
It always happens, no matter if i use the visual or the text editor. Is it possible for the theme developer to change settings in the framework? (i'm using [this theme](http://themeforest.net/item/wow-landing-page-template-with-page-builder/9794602) currently.) When i create a page without the visual builder it render correctly.

**Comment by moldcraft** [comment]
It seems that theme developer did html escape in all shortcode views. So this is not an Unyson issue.

To prove that. Please do the following:

* Activate a WordPress default theme.
* Create a new page with some shortcodes containing that test html string
* Save the page and view it on frontend

If the html is displayed fine (and not escaped) then it's sure a theme issue.

**Comment by runebaas** [comment]
It is indeed a theme issue, i'll contact the theme dev in that case.

Thanks for your help :smile:
