### ISSUE TITLE
Text Block shortcode is hidden by CSS...opacity:0

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#823]
Hello, 

One of our customer has a really weird issue... All the shortcodes in the page builder are working fine, excepts the *Text Block* one. The issue is that the TinyMce editor isn't well initialised... After some research on Google it could be caused by location of the JS scripts in the HTML.

Here is the console : 
```
TypeError: Cannot read property 'execCommand' of undefined
    at HTMLDivElement.init

message: "Cannot read property 'execCommand' of undefined"
stack: "TypeError: Cannot read property 'execCommand' of undefined↵ at HTMLDivElement.init
```

And the HTML : 
![screen_shot_2015-08-27_at_22_22_06](https://cloud.githubusercontent.com/assets/5446124/9537113/f65b3f44-4d0a-11e5-8264-33931321c0dd.jpg)

Let me know if you need any more detail (I can send you the URL to the issue). First time I see that..

Thank you :)

Best regards,

2F

**Comment by moldcraft** [comment]
Hi,

wp-editor option has `'reinit' => true`

**Comment by moldcraft** [comment]
Hi,

wp-editor option has `'reinit' => true` ?

**Comment by Ballyhoopro** [comment]
@moldcraft 
Hello,
I am the customer experiencing that weird issue with text block shorcode.
To answer your question... wp-editor is set to 'reinit'        => false,

**Comment by moldcraft** [comment]
Hello @Ballyhoopro ,
Set it to true and check if it helps

**Comment by Ballyhoopro** [comment]
Ok so I went to ...unyson/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php
Changed to true, saved and then refreshed WP page, created a new page, added text bloc shortcode and still have the issue. Nothing changed.

**Comment by Ballyhoopro** [comment]
![screen shot 2015-08-28 at 9 54 59 am](https://cloud.githubusercontent.com/assets/14017114/9549304/e76a2a58-4d6a-11e5-87ae-c060c74b533e.png)

**Comment by moldcraft** [comment]
> I went to ...unyson/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php

no .... you must not change anything in plugin files (they will be overwritten on the next update)

Set it to `true` try in [`shortcodes/text-block/options.php`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/text-block/options.php)

```
{theme}/framework-customizations/extensions/shortcodes/text-block/options.php
```

**Comment by Ballyhoopro** [comment]
Ok that must be it... I went to .../framework-customizations/extensions/shortcodes/shortcodes and don't see any text-block directory!

**Comment by Ballyhoopro** [comment]
Can I upload text-block directory to shortcodes?

**Comment by moldcraft** [comment]
Can you give me admin and ftp access to your site?

If yes, send the details to `moldcraft[at]email.com`

**Comment by Ballyhoopro** [comment]
Done!

**Comment by moldcraft** [comment]
> Can I upload text-block directory to shortcodes?

All shortcodes are loaded from the plugin/framework directory, you copy them only when you need to customize something.

> I went to .../framework-customizations/extensions/shortcodes/shortcodes and don't see any text-block directory!

It's ok.

----

I received the email.

**Comment by Ballyhoopro** [comment]
Ok. thank you.

**Comment by levan1993** [comment]
@moldcraft 
you can set by default 'reinit' => defined('DOING_AJAX') && DOING_AJAX. This way on every ajax request it will automatically reinit

**Comment by moldcraft** [comment]
@levan1993 This has nothing with ajax

**Comment by levan1993** [comment]
@moldcraft  you are wrong. you need to reinit editor if it's rendered in popup editor, or addable options. you can check it

**Comment by levan1993** [comment]
@moldcraft I've remove 'reinit' from text-block options array and added  'reinit' => defined('DOING_AJAX') && DOING_AJAX to '_get_defaults' method in wp-editor option class and it works.

**Comment by moldcraft** [comment]
@levan1993 Do you have this problem on your side too?

**Comment by moldcraft** [comment]
So I investigated the problem on @Ballyhoopro site and on edit page in javascript `window.tinyMCE` is undefined. https://github.com/ThemeFuse/Unyson/blob/d83a6d2227a69d0c1b45c4782f3387bab4a89f3b/framework/includes/option-types/wp-editor/static/js/scripts.js#L28

On my side this doesn't happen. We will investigate his site on Monday to find the cause of the problem.

**Comment by levan1993** [comment]
no, I don't. I just wanted to suggest solution to remove reinit requirement

**Comment by Ballyhoopro** [comment]
Where are the rest of the shortcodes? I am getting an error that button shortcode not existant.
![screen shot 2015-08-28 at 1 50 26 pm](https://cloud.githubusercontent.com/assets/14017114/9554472/d10bd1fa-4d8b-11e5-93d9-3ef6103552cf.png)

**Comment by Ballyhoopro** [comment]
Hello
To update on the issue, I ended up using custom CSS  ".fw-backend-option opacity: 1 !important"
and that solved the problem.
