### ISSUE TITLE
WordPress Domain Change

### ISSUE THREAD

**Issue by tzimpel** [ThemeFuse/Unyson#825]
Hi,

When moving sites from our dev server to the final server and domain, I have issues changing all links in the database.

Usually I match for "//www.our-dev-server.com/projectname" and change this to "//www.final-domain.com" via SQL or this tool: https://interconnectit.com/products/search-and-replace-for-wordpress-databases/

However, the page builder seems to escape the slashes in URLs (e.g. for images) in the database, but not always the same way: sometimes, it's "\/", sometimes "\\/", ...

What search patterns can I use when I have to search for URLs that have a subdirectory, and I wand to change this to another domain without subdir?

It's very annoying when some links still point to a non-public dev server. For me, everything looks fine when I check the site, but for anyone outside our corporate network, the site is broken.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Builder-Extension/issues/6#issuecomment-132497608

**Comment by tzimpel** [comment]
Thanks
