### ISSUE TITLE
Input type button padding reset in modals

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#829]
this in options-types.css is messing up input button in modal 
https://github.com/ThemeFuse/Unyson/blob/master/framework/static/css/option-types.css#L121-L124

    .fw-modal .media-frame input, .fw-modal .media-frame textarea {
        padding: 3px 5px;
    }

with that 
http://prntscr.com/8aplni

without 

http://prntscr.com/8apluv

not sure why you are resetting input padding there ( they look fine to me )  but you might want to try 

    input[type=text]

instead resetting all inputs

**Comment by coderontheroad** [comment]
Are you using github version or stable version? I didn't check it but it is a bug if you didn't anything for causing this :)

**Comment by danyj** [comment]
@coderontheroad  git version , this appeared in 2.4.2 I think , and no there is nothing special 


    <input type="button">Click</button>
