### ISSUE TITLE
Do you prefer isset or fw_akg ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#830]
@moldcraft  This is very useful function 

https://github.com/ThemeFuse/Unyson/blob/master/framework/helpers/general.php#L6-L50

and I am borrowing it for my css generation class. 

In my class I need to check multidimensional array for key existence and its value. 
Do you see a performance issue between these 2 and which one would you prefer

		$padding_array = fw_akg('padding',$array,null);

		$padding_array = isset($array['padding']) ? $array['padding'] : '';

**Comment by moldcraft** [comment]
Sure `isset()` is faster. But if `fw_akg()` is not used intensively, I think it will not affect much.

**Comment by danyj** [comment]
@moldcraft  thnx. yes it will be use multiple times , about 40 array keys.

**Comment by danyj** [comment]
back to this for a sec , I am using it heavily in all shortcodes to get the values 

example 

    $id					= fw_akg('id',$atts);

and than for all options in shortcode ,  some shortcodes have 5 and some 20 options, some use multi-picker and than I think it gets deeper , you think is to heavy for this ?

**Comment by danyj** [comment]
Reason why I am asking  code performance questions is this , 

on a simple , no nothing page
http://prntscr.com/8rpyn6

 I get 2.0.6 sec load time , 
no google fonts , no admin bar , nothing special 

http://prntscr.com/8rpx15


look at the Waiting (TTFB)  is 1.4 sec and content download is 324.621 ms which is fast consider all the css and js , so the only question is how much are the shortcodes affecting this and is TTFB just home server related and I should not worry about it https://blog.cloudflare.com/ttfb-time-to-first-byte-considered-meaningles/   or do you think we can do something about this

**Comment by moldcraft** [comment]
Sorry, I don't know. Try to make some tests

**Comment by danyj** [comment]
10x slower fw_akg  

 color- by function --0s 0.026941299438477ms
   color- by array --0s 0.003814697265625ms

I used this class 
http://stackoverflow.com/a/31725915/594423
