### ISSUE TITLE
[Suggestion] Add default option to color-picker

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#831]
I'm creating Color section in my Customizer, they're a lot of sections to change, more than 10 values, and the problem is that I couldn't change the color of site back, because it's hard to remember the default value. So I recommend an option to reset value to default like that: http://prntscr.com/8b29vd

**Comment by danyj** [comment]
I did this in my version 
http://screencast.com/t/42rt8D4iAb1f

add button 


	  if (!$input.hasClass('initialized')) {
			
			
			var addhtml ='<div class="fw-alpha-container">';
				addhtml +='<div class="slider-alpha"></div>';
				addhtml +='<div class="transparency"></div>';
				addhtml +='<a href="#" class="resetcolor button">'+thz_picker_vars.reset_txt+'</a>';
				addhtml +='</div>';
			
		 $(addhtml).appendTo($input.next('.iris-picker'));

	  }


reset on click 

	  $input.next('.iris-picker:first').find('.resetcolor').on('click',function (e){
		e.preventDefault();
		e.stopPropagation();
		$input.iris('color', $input.attr('data-reset'));
		
	 });


in render methodadd data-reset with current val


	return '<input data-reset="'.$option['attr']['value'].'" type="text" ' . fw_attr_to_html( $option['attr'] ) . '>';

**Comment by moldcraft** [comment]
We will try to make something like this http://joxi.ru/LmGpqOgcZlBl2l

**Comment by moldcraft** [comment]
Hello,

We added this feature

![](https://static.md/2c394cd96ebf0ecad688222aa31c7bfb.png)

but now we are confused about what you mean by **default** color:

* Is it the color that developer set in option array `'value' => '#123'`
* Or is it the (current) color that was before the picker was opened

?

**Comment by moldcraft** [comment]
TODO: Click on text should also do the reset http://joxi.ru/4AkE0XLiVeNYmq

**Comment by duongancol** [comment]
The default color is color that developer set in option array 'value'. I tested your option, and it worked exactly but I want to suggest the UI for this. 
1. When user see option, it look like default: http://prntscr.com/8gh2xm
2. When user click to input, the default button will appear. Please check my screenshot here: http://prntscr.com/8gh1oy
This UI is better because you can do the same with rgba-color picker. And in customizer, the user does not to scroll down to reset color

**Comment by moldcraft** [comment]
We will not put any buttons near input, only inside picker. Because we use color picker in other options

http://joxi.ru/l2ZYnzKCVMEzmJ
http://joxi.ru/vAWeREWHRXgYmW

**Comment by duongancol** [comment]
Ok, Did reset button work on rgba-color-picker?

**Comment by moldcraft** [comment]
No

**Comment by danyj** [comment]
>but now we are confused about what you mean by default color:

suggestion 

		$reset_data = empty($option['value']) ? $option['attr']['value'] : $option['value'];

if we dont set the color but offer a color picker , default should be what was previously saved

**Comment by moldcraft** [comment]
* if default `'value' => '#f00'` is specified, the "Reset to default" button will appear
* if db value exists (input is not empty), the "Reset to initial" button will appear

The text "Reset to initial" is ok (intuitive) ?

**Comment by danyj** [comment]
@moldcraft  I say , just  "Reset" is enough , since word reset means go back to default

**Comment by moldcraft** [comment]
Just "Reset" for both cases, or only for "Reset to initial"?

**Comment by danyj** [comment]
both bud , you dont have to dance around it since they have same meaning, they are resetting

**Comment by moldcraft** [comment]
Done

**Comment by danyj** [comment]
Bud , why would you do this  https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/static/js/scripts.js#L233-L268

when place for the button can be right here without any issues
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/static/js/scripts.js#L164

http://prntscr.com/8sa247

and in your current one , on  page reset , another  link to reset is added since you are not checking if it is there

**Comment by danyj** [comment]
all I did was add a button and you dont have to mess with position or anything 


					+ '<div class="fw-alpha-container">' 
					+ /**/'<div class="slider-alpha"></div>'
					+ /**/'<div class="transparency"></div>'
					+ /**/'<div class="resetcolor button">'+helpers.localized.l10n.reset_to_initial+'</div>'
					+ '</div>'

**Comment by danyj** [comment]
And this instead of each works also 


				  $input.next('.iris-picker:first').find('.resetcolor').on('click',function (e){
					e.preventDefault();
					e.stopPropagation();
					$input.iris('color', $input.attr('data-default'));
				  });

**Comment by danyj** [comment]
and you have a bug here , 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/static/js/scripts.js#L275

the dot in addClass
