### ISSUE TITLE
How to achieve list layout in unyson contact form extension ? Urgent

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#832]
Hello @moldcraft 

I am creating form in unyson form extension,
My concern is that i want the form look just like demo form,

Kindly see the attached image for demo reference,

![contact_form_demo](https://cloud.githubusercontent.com/assets/12461946/9605005/6b1882f2-50d4-11e5-9295-c47b29b60267.png)

This above picture represent the code structure which i want to achieve,

![contact_form](https://cloud.githubusercontent.com/assets/12461946/9605016/8feff31c-50d4-11e5-993a-412c312099cb.png)

and this above picture is the above code result.

Thanks for your kind help.

**Comment by moldcraft** [comment]
Hello,

form-builder doesn't have columns as containers for form elements. At the moment form elements work as columns (they have width). So I don't know how to make this

![](https://static.md/6a66d96006c6adfbdb62892cd7cbde94.png)

----

I can try to implement a column item in form-builder but I can't make it right now (urgent).

Let me know if you really need a column item in form-builder so I will start thinking about it.

----

Maybe you can make a compromise and change form elements positions and make [something like this](http://demo.themefuse.com/exposure/contact/#section-55e5a9650690b) ?

**Comment by wpthemes786** [comment]
Ok Thanks yes i have to change the structure according to unyson.

Thanks
