### ISSUE TITLE
Change the our demo link in backup extension ? 

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#834]
![demo_content_link](https://cloud.githubusercontent.com/assets/12461946/9626536/ab40f898-5177-11e5-82b4-bfc5e11ae6b6.png)

Hello @moldcraft 
How to change this link.

Thanks

**Comment by coderontheroad** [comment]
I don't know the right way, i don't have time to look that but as a temprory solution you can hardcode it. Open the Backup extension files in views folder you can find auto-install-1-welcome.php and in that file if you modify this line;

    $demo_page_link = $backup->get_config('demo_page_link');

I think you get what you want. But don't forget this is not true way, in somewhere outside extension files you can set 'demo_page_link' property but i don't know where.

**Comment by moldcraft** [comment]
Create

```
{theme}/framework-customizations/extensions/backup/config.php
```

and add

```
$cfg = array();
$cfg['demo_page_link'] = 'https://your-link...';
```
