### ISSUE TITLE
Enqueue Google Fonts Properly for TF ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#836]
Hello @moldcraft 

I hope you are well.

I have a soft rejection for my theme and in my theme there is a point that enqueue properly google fonts. I am currently using this code. 

/**
 * Hook For Google Fonts
 */

if(!function_exists('_action_theme_process_google_fonts')) {
    function _action_theme_process_google_fonts()
    {
        $include_from_google = array();
        $google_fonts = fw_get_google_fonts();

        $h1_font = fw_get_db_settings_option('h1_font');
        $h2_font = fw_get_db_settings_option('h2_font');
        $h3_font = fw_get_db_settings_option('h3_font');
        $h4_font = fw_get_db_settings_option('h4_font');
        $h5_font = fw_get_db_settings_option('h5_font');

        // if is google font
        if( isset($google_fonts[$h1_font['family']]) ){
            $include_from_google[$h1_font['family']] = $google_fonts[$h1_font['family']];
        }
        if( isset($google_fonts[$h2_font['family']]) ){
            $include_from_google[$h2_font['family']] = $google_fonts[$h2_font['family']];
        }
        if( isset($google_fonts[$h3_font['family']]) ){
            $include_from_google[$h3_font['family']] = $google_fonts[$h3_font['family']];
        }
        if( isset($google_fonts[$h4_font['family']]) ){
            $include_from_google[$h4_font['family']] = $google_fonts[$h4_font['family']];
        }
        if( isset($google_fonts[$h5_font['family']]) ){
            $include_from_google[$h5_font['family']] = $google_fonts[$h5_font['family']];
        }

        $google_fonts_links = fw_theme_get_remote_fonts($include_from_google);
        // set a option in db for save google fonts link
        update_option( 'fw_theme_google_fonts_link', $google_fonts_links );
    }
    add_action('fw_settings_form_saved', '_action_theme_process_google_fonts', 999, 2);
}

if (!function_exists('fw_theme_get_remote_fonts')) :
    function fw_theme_get_remote_fonts($include_from_google) {
        /**
         * Get remote fonts
         * @param array $include_from_google
         */
        if ( ! sizeof( $include_from_google ) ) {
            return '';
        }

        $html = "<link href='http://fonts.googleapis.com/css?family=";

        foreach ( $include_from_google as $font => $styles ) {
            $html .= str_replace( ' ', '+', $font ) . ':' . implode( ',', $styles['variants'] ) . '|';
        }

        $html = substr( $html, 0, - 1 );
        $html .= "' rel='stylesheet' type='text/css'>";

        return $html;
    }
endif;

if (!function_exists('_action_theme_print_google_fonts_link')) :
    function _action_theme_print_google_fonts_link() {
        /**
         * Print google fonts link
         */
        $google_fonts_link = get_option('fw_theme_google_fonts_link', '');
        if($google_fonts_link != ''){
            echo $google_fonts_link;
        }
    }
    add_action('wp_head', '_action_theme_print_google_fonts_link');
endif;

And the TF guys said enqueue google fonts properly.

Any help ?

Thanks

**Comment by danyj** [comment]
this might be what they are after 


	wp_enqueue_style( THEME_NAME. '-google-font', esc_url( $google_font_url ) , false, null ,'all' );

no echos,   enque style the right way

**Comment by danyj** [comment]
with the echo there no one can remove the style via 

	wp_deregister_style

they have to digg for the variable .

**Comment by valeriuzdrobau** [comment]
I also think that the problem is that you use `echo()` instead `wp_enqueue_style()`.

**Comment by wpthemes786** [comment]
![Uploading screenshot-localhost 2015-09-03 11-49-27.png…]()

I have this in google font url. And i need only the url to properly enqueue the style.

**Comment by wpthemes786** [comment]
Thanks i found the solution.

Much Appreciate Your Help Guys.

**Comment by UxLabByNinja** [comment]
@wpthemes786 How did you you solved the problem? Can you share your code. I have the same problem.

**Comment by danyj** [comment]
This is proper way for GF 

https://github.com/Themezly/Creatus/blob/master/inc/includes/class-thz-dynamic-css.php#L624
https://github.com/Themezly/Creatus/blob/70bbf5bffc82e1ccb1bf38b0fb09195bd3f2807c/inc/fonts-utility.php#L873-L874

**Comment by danyj** [comment]
customizer has nothing to do with , 
your options need to be rewritten for it 

See this , 
I used this for all options 

https://github.com/Themezly/Creatus/blob/master/inc/helpers.php#L105

and for customizer I used this class to sinc back and forth between theme options panel and customizer

https://github.com/Themezly/Creatus/blob/master/inc/includes/utilities/customizer/class-thz-customizer.php

than in customizer preview check for it 

https://github.com/Themezly/Creatus/blob/master/inc/includes/class-thz-item-utility.php#L163
