### ISSUE TITLE
[Switch option] Custom color for text and circle

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#837]
Can we please add an option to the switch that would change the circle color and text 

example 

    'section_switch' =>array (

            'type'  => 'switch',
            'value' => 0,
            'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
            'label' => __('Label', 'fw'),
            'desc'  => __('Description', 'fw'),
            'help'  => __('Help tip', 'fw'),
            'left-choice' => array(
                'value' => 0,
                'label' => __('Active', 'fw'),
				'color' => 'green'
            ),
            'right-choice' => array(
                'value' => 1,
                'label' => __('Inactive', 'fw'),
				'color' => 'red'
            ),

    ),

When active 
http://prntscr.com/8c40h1

Inactive 

http://prntscr.com/8c40pq

**Comment by coderontheroad** [comment]
good idea :) i like it

**Comment by thednp** [comment]
I would use gray for inactive.

**Comment by moldcraft** [comment]
```php
array (
        'type'  => 'switch',
        'left-choice' => array(
            'color' => '#f00',
            //...
        ),
        'right-choice' => array(
            'color' => '#0f0',
            //...
        ),
        //...
),
```

**Comment by wpthemes786** [comment]
Hello @moldcraft 

That's wonderful for color option in switch option type.
Can you add another option for switch like the font-size and text-transform property so if i want to show only first letter capital and remaining in small that's would be wonderful.

Looking Forward
