### ISSUE TITLE
Enqueue google font from BUILDER

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#839]
Hi 

I have seen several solutions to use google webfonts from theme settings . But I have used font in shortcode bulider. How can I print/enqueue this font?

Thanks

**Comment by moldcraft** [comment]
Try:

* In `{theme}/framework-customizations/extensions/shortcodes/shortcodes/{shortcode}/static.php`

    ```php
    global $_theme_fw_shortcodes_google_fonts;
    if (empty($_theme_fw_shortcodes_google_fonts)) $_theme_fw_shortcodes_google_fonts = array();

    $_theme_fw_shortcodes_google_fonts['FONT_ID'] = array(/* font data */);
    ```

* In `{theme}/framework-customizations/extensions/shortcodes/hooks.php`

    ```php
    add_action('wp_enqueue_scripts', '_action_theme_fw_shortcodes_google_fonts', 9999);
    function _action_theme_fw_shortcodes_google_fonts() {
        global $_theme_fw_shortcodes_google_fonts;

        if (empty($_theme_fw_shortcodes_google_fonts)) return;

        // enqueue the fonts
    }
    ```

**Comment by webangon** [comment]
Thank you for reply. But I want it to be done within plugin. Is it possible?

**Comment by moldcraft** [comment]
It's not possible.

If you know a good, simple to use solution, please share.
