### ISSUE TITLE
Refresh Automatically after installing Unyson Plugin ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#840]
Hello @moldcraft 

Is there any provision that when we install the unyson plugin the dashboard automatically refreshed.
At now when we install plugin it did not refreshed and user cannot see the unyson tab. when we refreshed then unyson tab is displayed.

Is there any settings in unyson that is required to do this job.

Thanks.

**Comment by moldcraft** [comment]
Hello,

It was a refresh or a redirect to "Install compatible extensions page"?

**Comment by wpthemes786** [comment]
Yes Redirect will be more helpful. ?

**Comment by moldcraft** [comment]
> Is there any settings in unyson that is required to do this job

No.

----

You can only [set in theme manifest supported extensions](http://manual.unyson.io/en/latest/manifest/theme.html#content). After the plugin was installed, if some of those extensions are not installed, the user will be redirected to a page to install the missing extensions.
