### ISSUE TITLE
How to create a Multiple Choice Quiz?

### ISSUE THREAD

**Issue by skiler07** [ThemeFuse/Unyson#843]
As the title says, is this even possible using Unyson?

**Comment by moldcraft** [comment]
Hello,

[Here](https://github.com/ThemeFuse/Unyson-Learning-Extension/tree/master/extensions/learning-quiz/includes/option-types/quiz-builder/items/single-choice) is defined single-choice. You can copym inspect, modify and register it as a new item type

```php
add_action(`fw_init`, '_action_theme_fw_register_item_types');
function _action_theme_fw_register_item_types() {
    if (fw_ext('learning-quiz')) {
        require_once '/path/to/class-fw-option-type-quiz-builder-item-multiple-choice.php';
    }
}
```
