### ISSUE TITLE
esc_html__() in settings.php removes ampersands

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#844]
As sanitization is now very important, especially after the recent XSS attacks and themeforest is checking every new theme, a lot of stuff needs to be escaped. Using `esc_html__()` in `title` attribute of an option field converts the `&` to `&amp;` which is not normal escaping behavior.

![image](https://cloud.githubusercontent.com/assets/1108563/9742714/9ffdb686-566a-11e5-9e63-bcf8bab4dbe4.png)

![image](https://cloud.githubusercontent.com/assets/1108563/9742734/b9f9676a-566a-11e5-9d5f-b2d074334a59.png)

It just occured to me - is it already sanitized?

**Comment by moldcraft** [comment]
Yes, [it is already sanitized](https://github.com/ThemeFuse/Unyson/blob/3efe8f062d12c9db14298ac9e034404f68b98bbc/framework/includes/container-types/tab/view.php#L12)
