### ISSUE TITLE
Unyson + Yoast SEO

### ISSUE THREAD

**Issue by salttechno** [ThemeFuse/Unyson#845]
First thing I would like to say is: Unyson is just awesome. It gives amazing power with easy custmozation. Thanks for such a awesome framework.

I am working on a website where I want to use Yoast SEO plugin on pages built with Unyson Page Builder. SEO title, description works very well. But Yoast SEO plugin does not work with the content written in page builder fields.

How can we make it work?

**Comment by moldcraft** [comment]
Thank you

> But Yoast SEO plugin does not work with the content written in page builder fields.

Sorry, I don't understand, how **it doesn't work with the content**? Can you give me an example or more details?

**Comment by salttechno** [comment]
Thank you for quick response. 

Kindly check the screenshot. It shows ) words in body copy but I have content on this page.
![yoast-seo-unyson](https://cloud.githubusercontent.com/assets/6907136/9758507/bae5a450-5704-11e5-9546-719cdc556f44.png)


I have content written on the page. But this page is created using Unyson Page Builder. So, the content is in the option fields of elements.

**Comment by moldcraft** [comment]
I think Yoast SEO works only with simple text and doesn't extract content from shortcodes. Page builder saves everything as shortcodes (you can check post content in database).

So better to open an issue on Yoast SEO plugin and ask them why it doesn't extract content from shortcodes.

It should work with frontend output, strip html tags and extract content (like search engines do), not with raw database content where shortcodes are not parsed and the content is enclosed in shortcodes attributes.

**Comment by ierpe** [comment]
https://github.com/Yoast/wordpress-seo/issues/2815 

Apparently Visual Composer fixed it somehow...

**Comment by edvinbrobeck** [comment]
I am also facing the same issue with Yoast not parsing the content created with the page builder properly.

When digging through Unyson I found that _init() part of the class FW_Extension_Shortcodes() is only running and hence registering the shortcodes if the page request is either an ajax request ('DOING_AJAX'), or not at admin page (!is_admin()).

This prevents me from using the filters provided by yoast to do the page analysis in the dashboard since the shortcodes are not registered if it is not a front end request.

Is there a way around this?

**Comment by moldcraft** [comment]
>  registering the shortcodes if the page request is either an ajax request ('DOING_AJAX'), or not at admin page (!is_admin()).

That will be fixed in next Shortcodes release 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/3c9641767d5511562fa293c69a23bc6e595c485b

**Comment by nickkuijpers** [comment]
Hi Moldcraft, does this mean this is fixed so we can use SEO By Yoast with Unyson?

**Comment by moldcraft** [comment]
[Shortcodes v1.3.9](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/releases/tag/v1.3.9) hasn't been released yet. You can test it: Download and extract in `unyson/framework/extensions/shortcodes`. Check if everything works fine, if not, let us know.

**Comment by darwinteam** [comment]
Yoast SEO tabs do not work, so we can't see options.

**Comment by duongancol** [comment]
Hi! Today I test with Yoast SEO and it doesn't work. You could see [here](http://take.ms/S0dBn)

**Comment by duongancol** [comment]
[Here](http://take.ms/R8AHTH) is how the result looks in Visual Composer page.

**Comment by moldcraft** [comment]
@duongancol Thank you for inspecting. We will try to extract the text from the html generated from shortcodes (with strip tags) and update post content, but later.

It should be done [here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.5/class-fw-extension-page-builder.php#L166). You can try to find a solution and provide a pull request. _Note: Check if no duplicate Revisions are created._

**Comment by duongancol** [comment]
Thank for your info, I'll try too.

**Comment by duongancol** [comment]
tried to figure out but it's quite complicated. Could you open this issue?

**Comment by mariap69** [comment]
wrong! Yoast SEo works fine with many page builder and doesn't work only with Unyson.

**Comment by danyj** [comment]
@mariap69  no reason for hostilities, you can see that everyone is looking in to this and doing their best to help out. I am sure that it will be fixed soon.

**Comment by mariap69** [comment]
Ok I hope they fixed it soon. Unfortunately I bought a theme which use Unyson and I have many problems with it. I see this bug was already known to developer since september 2015. If they didn't fixed it until now I think they 'll never do it.

**Comment by moldcraft** [comment]
Test please: [Download](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/archive/master.zip) and extract in `unyson/framework/extensions/shortcodes/extensions/page-builder`

**Comment by mariap69** [comment]
Nothing is changed

**Comment by moldcraft** [comment]
@mariap69 Change something in builder and Update the page.

**Comment by moldcraft** [comment]
![](https://static.md/dedf9384b895f6b024034ac78f66c8cb.png)

**Comment by mariap69** [comment]
Yes, it works. Thank you!

**Comment by noesteijver** [comment]
I'm experiencing troubles with this. I still see the warning that there are 0 words on my page and the meta description remains empty.

Is there anything that I can do or anything that I should activate in order to make this work?

**Comment by moldcraft** [comment]
@noesteijver 

1. Make sure Unyson and extensions are up-to-date
2. Press page Update button
3. Check if there are still 0 words

**Comment by noesteijver** [comment]
@moldcraft I've tried this, but the problem still remains..

**Comment by moldcraft** [comment]
@noesteijver Sorry, I have a plenty of issues to fix and don't know when I will inspect this. You can try to inspect it by yourself: [This code](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/94bf1075461c3c319bd8d425868eab1bfff3fdfa/class-fw-extension-page-builder.php#L173-L186) is responsible for generating the post content, you can debug it and find out why it doesn't reach post content and why Yoast SEO doesn't see it.

**Comment by noesteijver** [comment]
@moldcraft I'm sorry, my situation is different from the one stated. I'm only using custom fields. So my comment wasn't relevant. My mistake.

**Comment by niklasfink** [comment]
This fix does not work anymore and crashes the whole framework. It is also **not** fixed in the newest updates. Still shows the wrong word count in Yoast!

**Comment by GheorgheP** [comment]
@niklasfink At the moment we cannot change this. The fact is that we generate real page content just after you publish/update it. Making the counter work on-fly will require a lot of browser performance usage, and it may not be necessary, just for a counter.

But I will review this problem as sson we can find a proper solution for this.

**Comment by rogerximenez** [comment]
Is this issue ever going to be fixed?
