### ISSUE TITLE
Auto deactivating

### ISSUE THREAD

**Issue by RomanHero** [ThemeFuse/Unyson#846]
The unyson plugins keep deactiving every two to three weeks. This is the third time this has happened. Can you please assist?

**Comment by moldcraft** [comment]
Hello,

* Which Unyson version do you have installed?
* Extensions were deactivated or uninstalled/deleted?

We had [this problem](https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-131184290) in the past but it was fixed in v2.4.6
