### ISSUE TITLE
Auto deactivating

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#847]
Unyson periodically deactivates on it's own. Please fix that.

Also, there are problems with hosting compatibility. Demo import doesn't work well on some hosting.

If that is possible, can you make layout builder like in Visual Composer: so for example you can put 1 column block, after this 2/3 columns block, after this 4 column block on the same page.

**Comment by moldcraft** [comment]
> Unyson periodically deactivates on it's own. Please fix that.

[Duplicate](https://github.com/ThemeFuse/Unyson/issues/846)

> Also, there are problems with hosting compatibility. **Demo import doesn't work well** on some hosting.

Please create new issue with more details and stepts to reproduce the problem.

> If that is possible, can you make layout builder like in Visual Composer: so for example you can put 1 column block, after this 2/3 columns block, after this 4 column block on the same page.

Sorry, I don't understand, do you mean [nested columns](https://github.com/ThemeFuse/Unyson/issues/230)?

**Comment by darwinteam** [comment]
Yes, nested columns. Lots of users want them.
