### ISSUE TITLE
[Suggestion ]  Reset Current Section Options

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#848]
Just a suggestion for a handy button that is present in Redux and it will be nice if it's presented in Unyson - "Reset Section Options" button.

For example if I have Styling tab with color fields, and I want to reset only the Styling section to its defaults and not lose everything else, button like this will be a lifesaver.

**Comment by moldcraft** [comment]
Give us a screenshot please.

**Comment by pe6o** [comment]
No problem. Here it is -> http://i.imgur.com/h2urvNV.png

**Comment by moldcraft** [comment]
Can you make a screenshot where you want to put the Reset button in Unyson options (how it will look, where it will be positioned) ?

**Comment by pe6o** [comment]
One more button at the bottom and some changes in the titles. Some thing like this? http://i.imgur.com/22iWw8O.png

**Comment by moldcraft** [comment]
I will try to investigate this later. This issue has low priority, sorry.

**Comment by moldcraft** [comment]
We have Reset button in Theme Settings and Modal
