### ISSUE TITLE
Creating Layout Elements Shortcodes. Possible?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#850]
Is it possible container shortcodes to be created (the ones in Layout Elements), such as 1/1, 1/2?

I know that I can put in 
*framework-customizations\extensions\builder\config.php*

```php
'section_block' => array(
        'title'          => 'Section Block',
        'backend_class'  => 'container',
        'frontend_class' => 'container',
    ),
```

But what if I want to output two elements, for example:
```html
<section class="page-section">
   <div class="container">
           <!-- content here -->
  </div>
</section>
```

**Comment by moldcraft** [comment]
You want to add width for sections?

**Comment by pe6o** [comment]
Yes, `width` and `margin-bottom`.

**Comment by moldcraft** [comment]
* Why do you want to do that? Why you are not using columns but want sections to behave like columns?
* Have you tried to create a new shortcode `section_1_2` ?

**Comment by pe6o** [comment]
I have a page builder block that has `viewp.php` consisting of:

```html
<div class="col-sm-4">
// Stuff
</div>
<div class="col-sm-8">
// Stuff
</div>
```

And I don't know what is the best way to proceed with wrapping it. I want them to be full width by default but if wanted, to be able to wrap them in a `.container  with `width: 1170px;` and `margin-bottom`.

**Comment by moldcraft** [comment]
> https://www.dropbox.com/s/srctv5x45y88hlj/page-section.zip?dl=0

Not that easy. Section is not a simple shortcode, it is a custom page-builder item. [Copy it](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/master/shortcodes/section), rename everything from `section` to `your_shortcode_name`, make sure it works, then start changing it however you want (add any custom functionality)

**Comment by pe6o** [comment]
Okay, I want to create my `page-section` shortcode instead of `section`. I want it to be the same as the default only without all the option fields but it seems renaming the original one to a custom one is harder than it seems...

Do I have to change it type `section` to the custom one `page-section`?

**Comment by moldcraft** [comment]
Yes

**Comment by pe6o** [comment]
So I guess a shortcode like that is the only way that a layout like this can be achieved? 

![section](https://cloud.githubusercontent.com/assets/1108563/10135329/9b9ebe88-65f5-11e5-89d4-c432ce285841.png)

**Comment by moldcraft** [comment]
> And I guess get_uri has to be replaced with fw_get_template_customizations_directory_uri?

I don't understand which get_uri your are talking about.

> So I guess a shortcode like that is the only way that a layout like this can be achieved?

Why you can't achieve that with a section with "Full Width" switch set to NO and two columns?

**Comment by pe6o** [comment]
Hmm,
```php
$shortcode_instance = fw_ext('shortcodes')->get_shortcode('page-section');
return $shortcode_instance->get_options();
```
gives `Fatal error: Call to a member function get_options() on a non-object`

> Why you can't achieve that with a section with "Full Width" switch set to NO and two columns?
I would like to remove options like background video upload and so on.

**Comment by moldcraft** [comment]
Try `'page_section'`

**Comment by pe6o** [comment]
Only one more question. Do I change this line:
```js
fwEvents.trigger('fw:page-builder:shortcode:section:controls', {
```
to
```js
fwEvents.trigger('fw:page-builder:shortcode:page_section:controls', {
```

**Comment by moldcraft** [comment]
Yes

**Comment by pe6o** [comment]
Okay, I settled with using the default `section` shortcode but Is there a simple way to add some kind of class to it? I want to insert `margin-bottom` but I don't want to put it globally for all `.fw-container` elements?

**Comment by moldcraft** [comment]
Add a switch/checkbox in options, if it's "Yes" then add margin or special css class that will add margin

**Comment by pe6o** [comment]
How can I add additional field to the default `section` shortcode?

Do I copy it in `framework-customizations`? If yes, do I have to rename something, because as I said above, renaming all instances of `section` makes it buggy.

**Comment by moldcraft** [comment]
> How can I add additional field to the default section shortcode?

Copy

```
unyson/framework/extensions/shortcodes/shortcodes/section/options.php
```

to

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/section/options.php
```

and add additional options

**Comment by pe6o** [comment]
Oh, alright, and using the same logic I can copy the `view.php` ?

**Comment by moldcraft** [comment]
Yes

**Comment by moldcraft** [comment]
Have you [read this](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#content)?

**Comment by pe6o** [comment]
Yeah, but I guess will read it again.

Thank you guys for all the time you are taking with thus framework and support. I'll make sure that  every theme I'm creating has link to your framework on a visible spot.

**Comment by moldcraft** [comment]
Thank you
