### ISSUE TITLE
Demo Content Install Issue Need Help

### ISSUE THREAD

**Issue by aamirs332** [ThemeFuse/Unyson#851]
Hello, hope so you are doing good. I have a problem with demo install. When i create a "Demo Install" its create a zip file. when i download it and install it locally. and go to my wp admin panel as "http://localhost/www/demo/wp-admin" it takes me to demo login at live site. could you please help me how to create a demo install to work it with any server?

http://prntscr.com/8ff8ck

![9qp0odx](https://cloud.githubusercontent.com/assets/5873187/9830963/967b1d5c-58f8-11e5-8b71-3eaf9b06eeb5.png)

**Comment by moldcraft** [comment]
Hi,

The developer that was responsible for the Backup extension is no longer in our team, and I have no idea how it works, yet.

I will start to reply questions related to Backup extension later, when I will inspect/understand how it works.

We are very sorry.

**Comment by aamirs332** [comment]
OK, thanks for your cooperation. :+1:

**Comment by duongancol** [comment]
I used to have experiences with this issue, please send me database.txt in an auto-install folder. Maybe I can help.

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
