### ISSUE TITLE
Passing post variable from builder

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#852]
I am using builder to display posts of certain catagory. The catagories are stored in variable . Now I need to pass the variable by wp localise script method.
 ``` 
if (fw_akg('style/ruler_type', $atts) === 'slider') {
    $icon_options = fw_akg('style/slider', $atts);
   // print_r( $icon_options['column']);

$catagory = '';
if ( ! empty( $icon_options['column'] ) ) {
	$catagory = $icon_options['column'];
}	
}
 ```
To localise the variable I have used in static.php
 ```
		wp_localize_script('fw-alt-block', 'ajax_custom', array(
		'ajaxurl' => admin_url('admin-ajax.php'),
		'nonce' => wp_create_nonce('cr_ajax'),
		'loading' => __('Loading...', 'cr'),
		'catagory' => $catagory,
		));
 ```
But I think the variable is not passing as I see null despite selecting catagory.

**Comment by moldcraft** [comment]
Sorry, I don't see this an Unyson problem.

Check and debug more careful your code and find where exactly is the problem.
