### ISSUE TITLE
Switch is not working in page builder correctly

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#853]
Hello, team, just a report:

this not working if i use numeric values for Switch (only in page builder, but works in Theme options):
```
'my_option' => array(
	'label' => __('Some option', 'textdomain'),
	'type' => 'switch',
	'value' => 0,
	'right-choice' => array(
		'value' => 1,
		'label' => __( 'Yes', 'textdomain' )
	),
	'left-choice' => array(
		'value' => 0,
		'label' => __( 'No', 'textdomain' )
	),
),
```
this works fine:
```
'my_option' => array(
	'label' => __('Some option', 'textdomain'),
	'type' => 'switch',
	'value' => 'no',
	'right-choice' => array(
		'value' => 'yes',
		'label' => __( 'Yes', 'textdomain' )
	),
	'left-choice' => array(
		'value' => 'no',
		'label' => __( 'No', 'textdomain' )
	),
),
```

any ideas how to use numeric values for Switch in Page builder? :)

**Comment by WPJobs** [comment]
p.s. why i need numeric values?

$var == 1 will work faster than $var == 'yes' isn't right?

**Comment by moldcraft** [comment]
I made [a fix](https://github.com/ThemeFuse/Unyson/commit/02525be20bfe343acc5db8f38b4948f2c1800c0f?diff=split)

Please test all your options, I hope it did not break other options.

**Comment by danyj** [comment]
works for now on the switch but not sure about other options 

tested  switch with 

    0 , 1 
    false, true
    'inactive','active'

worked  in all 3 inside section options and than deeper inside addable-popup

**Comment by WPJobs** [comment]
thank you so much! Can I hope that this fix will be included in the official release?

**Comment by moldcraft** [comment]
Let me know if this feature is critical and urgent for your and I will create a new [release approval](https://github.com/ThemeFuse/Unyson-Extensions-Approval) asap.

If not, we sure will include this in official release but later, when more features and bug fixes will accumulate.

**Comment by WPJobs** [comment]
it is not critical, thank you a lot for a quick response and fix! :+1:
