### ISSUE TITLE
Urgent : Language Extension Issue. ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#854]
Hello @moldcraft 

I am using language extension, everything seem to be working fine, but when i go to woocommerce shop page and click on language switcher at top bar its give me following error. Kindly see the below attach error picture.

Need Urgent Help. Thanks

![screenshot-triathlon themographics com 2015-09-14 16-12-54](https://cloud.githubusercontent.com/assets/12461946/9848549/9a04ef98-5afb-11e5-9c53-12a76d8fb704.png)

**Comment by llemurya** [comment]
@wpthemes786 I will investigate this bug, please wait a response, because the extension wasn't tested with other plugins.
