### ISSUE TITLE
Unyson Options Type in Widgets ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#855]
Hello @moldcraft 

I hope you are well.

Just want to now that is there any possibility to add unyson option types in wordpress widgets ? 

Thanks

**Comment by llemurya** [comment]
@wpthemes786 this task is in todo list, at the moment it is not possible , but we plan to do this in next versions , the @danyj also asked about this feature , please see this [topic](https://github.com/ThemeFuse/Unyson/issues/568), maybe it helps.

**Comment by wpthemes786** [comment]
Thanks @llemurya
