### ISSUE TITLE
Problem with AJAX Contact Form in SubDomain 

### ISSUE THREAD

**Issue by RodalErmakov** [ThemeFuse/Unyson#856]
Hi)
I have a contact form with Ajax submit. When I click send button Error message appeared (Ajax error (more details in console))
My site is located on subdomain.

I have found in this file wp-content\plugins\unyson\framework\static\js\fw-form-helpers.js this line
ajaxUrl: (typeof ajaxurl == 'undefined') ? '/wp-admin/admin-ajax.php' : ajaxurl,
and have added here '/wp-admin/admin-ajax.php' my subdomain.
Then the form has worked.

Could you please fix this problem and add to new update?
Thank you very much.

**Comment by moldcraft** [comment]
I don't know how to fix that, that's why I made possible to specify that url manually (in case the default value will not work).

Do you know how to fix it?

**Comment by moldcraft** [comment]
I made a [small change](https://github.com/ThemeFuse/Unyson/commit/f2c4c04bc5430af820ad6762f9c448916383fc1e). And added in [docs](http://manual.unyson.io/en/latest/helpers/php.html#ajax-submit)

```php
wp_localize_script('fw-form-helpers', 'fwAjaxUrl', admin_url( 'admin-ajax.php', 'relative' ));
```

This is all I can do for this issue.
