### ISSUE TITLE
Unyson Page Builder 

### ISSUE THREAD

**Issue by chaley-warne** [ThemeFuse/Unyson#858]
I have a number of pages built using Page Builder that have stopped working and are now showing as in the attachment. How can I fix this, I am new to wordpress so have limited knowledge. WP version 4.3 Unison 2.4.7 
![unyson](https://cloud.githubusercontent.com/assets/14324225/9924351/a95f9c64-5d52-11e5-9619-3e207c45dca8.png)

**Comment by llemurya** [comment]
@chaley-warne you must click on the Visual Page Builder button , to enable the page builder mode ,please try this and say if it helps.I am waiting for your response.

**Comment by chaley-warne** [comment]
When I do this I get the same code but shown in a text box within Unyson. If I make any modifications the the page shows a blank

--

Chaley Warne
SocialWeb

Mobile: 0211 556 995
Web:     www.socialweb.co.nz

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/647
