### ISSUE TITLE
Custom Option in Contact Form Shortcode ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#861]
Hello @moldcraft 

In Contact Form Shortcode i want to display the social media icons settings. So user will be able to on off those settings. Is there any overriding in framework-customization folder. 

Because $atts did not work i items.php file at this location. 
framework-customizations\extensions\forms\form-builder\views\items.php

I want to render the social media icons at this location. 

How its done ? 

Thanks

**Comment by moldcraft** [comment]
Can you give the exact steps to reproduce this, or social media icons settings options? So I can test this and see what can be done.

**Comment by wpthemes786** [comment]
Hello @moldcraft 
Sorry For the late replry, here is my structure.

I want to achive this scenario,
![demo](https://cloud.githubusercontent.com/assets/12461946/9953510/d170f8bc-5dfa-11e5-9a4b-3c7b5de2f356.png)

And in unyson contact form extension i have override options files, and the path is.

framework-customizations\extensions\forms\extensions\contact-forms\shortcodes\contact-form\options.php

And my array structure is .

![2015-09-18_1148](https://cloud.githubusercontent.com/assets/12461946/9953553/41cb58d2-5dfb-11e5-88ac-9a21d61124f1.png)

And the contact form shortcode result is .

![screenshot-localhost 2015-09-18 10-58-44](https://cloud.githubusercontent.com/assets/12461946/9953564/5464a386-5dfb-11e5-8539-ec656a6b0441.png)

Now i am putting the html code in this file and the structure is.

\framework-customizations\extensions\forms\form-builder\views\items.php

<div class="contact-form">
<?php echo force_balance_tags($items_html) ?>
	<ul class="social-icon theme-social-con pull-right">
		<li><a href="#"><i class="fa fa-facebook"></i></a></li>
		<li><a href="#"><i class="fa fa-twitter"></i></a></li>
		<li><a href="#"><i class="fa fa-tumblr"></i></a></li>
		<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
		<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
		<li><a href="#"><i class="fa fa-rss"></i></a></li>
	</ul>
</div>

Now what i want to achive.

See the contact form shortcod social settings.

I want to get the selected social links in this file and also a switch on / off settings.

Thanks for your kind help.

I hope there is no difficulty for you in this scenario,

Regards

**Comment by wpthemes786** [comment]
@moldcraft  Did you find any solution ?

**Comment by moldcraft** [comment]
I'm working on this now

**Comment by wpthemes786** [comment]
Thanks Much Appreciated Your Help.

**Comment by moldcraft** [comment]
Any extra options added in 

```
{theme}/framework-customizations/extensions/forms/extensions/contact-forms/shortcodes/contact-form/options.php
```

will be sent [here](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/175e6d652f9e381f1670e216f4e43e728ed9ccae/extensions/contact-forms/views/submit.php#L7) and [here](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/175e6d652f9e381f1670e216f4e43e728ed9ccae/extensions/contact-forms/views/form.php#L7)

**Comment by wpthemes786** [comment]
Hello @moldcraft 

I have followed Your instructions mentioned above.

And i have an array of options in options.php file.

Now i am fw_print the attribute in form.php file.

fw_print($atts['social_list']);

its returning me null.


Thanks

**Comment by moldcraft** [comment]
> Now i am fw_print the attribute in form.php file.
>
> fw_print($atts['social_list']);

The variable is not called `$atts`

> https://github.com/ThemeFuse/Unyson/issues/861#issuecomment-141685063
> 
> [here](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/175e6d652f9e381f1670e216f4e43e728ed9ccae/extensions/contact-forms/views/submit.php#L7) and [here](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/175e6d652f9e381f1670e216f4e43e728ed9ccae/extensions/contact-forms/views/form.php#L7)

**Comment by wpthemes786** [comment]
Now its fine.what i am doing wrong.

<pre>
<?php
if (!defined('FW')) {
    die('Forbidden');
}
/**
 * @var string $form_id
 * @var string $form_html
 * @var array $extra_data
 */
?>
<?php fw_print($extra_data['hello_text']); ?>
<div class="form-wrapper contact-form">
    <div class="row bg-light padding-left-right padding-top-bottom">
        <?php echo force_balance_tags($form_html); ?>
        <ul class="social-icon theme-social-con pull-right">
		<li><a href="#"><i class="fa fa-facebook"></i></a></li>
		<li><a href="#"><i class="fa fa-twitter"></i></a></li>
		<li><a href="#"><i class="fa fa-tumblr"></i></a></li>
		<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
		<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
		<li><a href="#"><i class="fa fa-rss"></i></a></li>
	</ul>
    </div>
    
</div>
</pre>

**Comment by wpthemes786** [comment]
Hello @moldcraft .

fw_print($extra_data['hello_text']);

This is not working

**Comment by moldcraft** [comment]
It works on my side.

* Create

    ```
    {theme}/framework-customizations/extensions/forms/extensions/contact-forms/shortcodes/contact-form/options.php
    ```

    with the following contents
    
    ```php
    <?php if (!defined('FW')) die('Forbidden');

    /**
     * @var FW_Extension_Shortcodes $shortcodes_extension
     */
    $shortcodes_extension = fw_ext('shortcodes');
    
    require $shortcodes_extension->get_shortcode('contact_form')->get_declared_path('/options.php');
    
    $options[] = array(
    	'hello' => array('type' => 'text'),
    );
    ```

* Create

    ```
    {theme}/framework-customizations/extensions/forms/extensions/contact-forms/views/form.php
    ```
    
    with the following contents
    
    ```php
    <?php if (!defined('FW')) die('Forbidden');
    /**
     * @var int $form_id
     * @var string $form_html
     * @var array $extra_data
     */

    // ...

    fw_print($extra_data);
    ```

* Added the Contact Form shortcode in builder. Added a value in that test input.

    On frontend I get
    
    ```
    array
    (
        [hello] => 'Hi'
    )
    ```

----

Are you using the latest dev version of [Forms extension](https://github.com/ThemeFuse/Unyson-Forms-Extension)?

**Comment by wpthemes786** [comment]
Forms v2.0.14 | Release date 24.09.2015 .
This version is not in unyson 2.4.8. 
So i have download this form extension and replace in framework. but what if when the plugin is updated and again files will be replaced so it will not display the shortcode content again.

Thanks

**Comment by duongancol** [comment]
@wpthemes786 : you just need to update Unyson and extensions. Don't need update manyally to get  custom option work on Contact form. Update extension here: http://prntscr.com/8mtfk5

**Comment by moldcraft** [comment]
@wpthemes786 https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/142

**Comment by wpthemes786** [comment]
@moldcraft  The way that you have taught me to display custom options in contact form builder shortcode. i have installed the 2.4.8 unyson . and i followed your instructions and when i print the custom hello value its return me null value. but when i download the developer contact form extension version and replace in unyson plugin its worked.

So my question is that 2.4.8 unyson is not include this Forms v2.0.14 | Release date 24.09.2015 this version ?

**Comment by moldcraft** [comment]
I already answered that https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/144#issuecomment-144963518

Please do the following:

* Open

```
unyson/framework/extensions/forms/manifest.php
```

* Decrease `$manifest['version'] = '2.0.13';`
* Open admin page. Did you see any [notification that an update is available](https://static.md/752cb1afa07396c0dcd300f4517e74d0.png)?
