### ISSUE TITLE
Translation extension: How to load the theme translation as well?

### ISSUE THREAD

**Issue by ameenC** [ThemeFuse/Unyson#862]
Hello everyone.
First of all, thank you very much for making such an awesome framework.
I've been experimenting with the translation extension lately and what I would like to do is to also load the theme translation based on what language was chosen on the front end.
For example, when I choose 'German' and go to a 404 page, I get the default English 404 message although the German translation (.mo files) are available.
What logic needs to be added to load_theme_textdomain()?
Thanks

**Comment by llemurya** [comment]
@ameenC at the moment in translation extension is not a built in mechanism to do this thing very easy, it was planned in next iteration of the translation. I will investigate your question and become with an answer.

**Comment by ameenC** [comment]
Okay, thank you @llemurya, looking forward to it.

**Comment by llemurya** [comment]
@ameenC i opened a new issue on translation https://github.com/ThemeFuse/Unyson-Translation-Extension/issues/15
