### ISSUE TITLE
Multi-picker Switch in custom option view is not taking custom choices 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#863]
@moldcraft  Creating a custom option with a multi-picker inside the view 

		echo fw()->backend->option_type( 'multi-picker' )->render(
			'animate',
			array(
				'label' => false,
				'desc' => false,
				'picker' => array(
					'picked' => array(
						'label' => 'Animate',
						//'type' => 'radio',
						'desc' => __('Add animation to the HTML container', 'fw'),
    /*						'type' => 'radio',
						'choices' => array(
							'active' => __('active', 'fw'),
							'inactive' => __('inactive', 'fw')
						),*/
						'type' => 'switch',

						'right-choice' => array(
							'value' => 'active',
							'label' => __('Yes', 'fw')
						),
						'left-choice' => array(
							'value' => 'inactive',
							'label' => __('No', 'fw')
						),
						'value' => fw_akg('animate/picked', $data['value'])
					)
				),....................

radio  and select work ok , but switch is returning empty and on  instead of my 
right-choice'  left-choice' wich are  active/inactive

see  [picked] value 
set to active
http://prntscr.com/8huiww

set to inactive 

http://prntscr.com/8hukwu

**Comment by moldcraft** [comment]
As I remember, 'on' is sent in POST value on submit (in html switch is a checkbox) but _get_value_from_input() does its job and returns the right value from right or left choice.

I am thinking that you do not extract correctly the value from POST, instead of using _get_value_from_input(), you save in db raw POST value.

Can you give all your code so I can test it on my side? (`moldcraft(at)email.com`)

**Comment by danyj** [comment]
sent , thank you,  look in view.php line 47, 

it is radio now

**Comment by moldcraft** [comment]
Just started to look at it (this is not a final answer), and notice this in `_get_value_from_input()`

```
foreach ($option['value'] as $key => $val){
			
	if (isset($input_value[$key])) {
				
		$value[$key] = $input_value[$key];
	}
}
```

why are you saving raw POST value (`$input_value`) in database, for me it's just wrong and unsafe. You should call option-type `get_value_from_input()` give it raw value and it will return a safe/correct value for database.

----

I already talked about this (not sure if it was explicit)

> https://github.com/ThemeFuse/Unyson/issues/648#issuecomment-111450878
>
> A recommendation, if you use other option types in your option, better to use the fw_get_options_values_from_input() function to get their values, instead of just returning raw $input_value without any (or poor) verification.
> 
> For example if you have many options in your view that are rendered in different html elements, try to generate in _get_value_from_input() a single array with all those options (to be the same as those in view) and just use fw_get_options_values_from_input() to extract their values, instead of parsing all those arrays manually and creating weird code.

&nbsp;

> https://github.com/ThemeFuse/Unyson/issues/444#issuecomment-90983017
>
> Also your _get_value_from_input() method can be [improved](https://github.com/ThemeFuse/Unyson/blob/7f826f0854b01b97406b2e567c6be9cbe47cc865/framework/includes/option-types/multi/class-fw-option-type-multi.php#L62-L67)

&nbsp;

> https://github.com/ThemeFuse/Unyson/issues/280#issuecomment-75854780
>
> Then in `_get_value_from_input()` you extract that border color value 

> ```php
> $color = fw()->backend->option_type( 'color-picker' )->get_value_from_input(
>     array(...), // the same array as in view
>     fw_akg('border/color', $option_input_value)
> );

> // then return the same array structure as in `_get_defaults()['value']`
> ```

**Comment by moldcraft** [comment]
The problems:

* I was right about the above `_get_value_from_input()`, the switch value wasn't saved correctly. I change the `_get_value_from_input()` code to this:

    ```php
    $inner_option = $this->get_inner_option();
    
    $value = fw()->backend->option_type($inner_option['type'])->get_value_from_input(
        $inner_option,
        $input_value
    );
    ```

* On option render you did this:

    ```php
    echo fw()->backend->option_type( 'multi-picker' )->render(
        'hardcoded_id', // <---
        array( 'type' => 'multi-picker', /* ... */ ),
    	array(
    		//'value' => ...,
    		'id_prefix' => $option['attr']['id'] .'-', // <---
    		'name_prefix' => $option['attr']['name'],  // <---
    	)
    );
    ```

    correct is:

    ```php
    echo fw()->backend->option_type( 'multi-picker' )->render(
        $id, // <---
        array( 'type' => 'multi-picker', /* ... */ ),
    	array(
    		//'value' => ...,
			'id_prefix' => $data['id_prefix'],     // <---
			'name_prefix' => $data['name_prefix'], // <---
    	)
    );
    ```

**Comment by danyj** [comment]
Ah , so clean and right! Thank you!

**Comment by moldcraft** [comment]
There are two elements with same id

![s](https://static.md/1180cdb683783a63d2b9698693cf7601.png)

In view change `'id_prefix'` to

```php
'id_prefix' => $data['id_prefix'] .'inner-',
```

**Comment by danyj** [comment]
done! thnx!
