### ISSUE TITLE
Allowed memory size error in previews

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#864]
Guys , today I started getting Fatal error: Allowed memory size errors while trying to preview page changes  always  wp-includes\formatting.php

but different lines , 499 , 2343  ,  if I save changes and go to page directly it is ok. 
I dont want to increase anything since I am sure some kind of a loop is in question. Everything worked okish no big issues . Did not make any changes. 

Does anyone know how I can actually find the thread / line that is causing it ?

**Comment by danyj** [comment]
If I switch to default editor error is gone , so something is going on within the builder

**Comment by moldcraft** [comment]
Try deactivating extensions one by one, or send your theme to `moldcraft(at)email.com`

**Comment by danyj** [comment]
OK , disabled all extensions I had , 
builder , 
sliders
breadcrumbs
mega menu
portfolio

Same thing , 

To rule out the builder I
saved builder template , made new page , inserted builder template 
everything works fine

Now this particular page I worked on for the past 3 months , it is kinda test page 
so I think this has something to do with autosaves and previous versions rather than anything else. 

Now with everything disabled , I can see actual shortcodes 
http://prntscr.com/8i1g7j

and is either something inside there or hm , dont know anymore

I also removed everything from that page now ,   and still same issue 
http://prntscr.com/8i1gy3


oh , error is different now 

\wp-includes\functions.php on line 295
https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.php#L295

these 2 were before 

https://github.com/WordPress/WordPress/blob/master/wp-includes/formatting.php#L499
https://github.com/WordPress/WordPress/blob/master/wp-includes/formatting.php#L2343


Only thing that lets me preview the page is deactivating Unyson completely , but now I dont know if it is theme or unyson.


I cant send you the complete theme now  since company does not allow it until is made public. only peaces is what I can share for now.

**Comment by moldcraft** [comment]
Have you tried with Unyson enabled but with a default WP theme?

**Comment by danyj** [comment]
ah ,  no did not try that , will do 
what I did try is disabled all my custom function one by one , and same thing, 
I have shortcodes overrides , will look in to those

**Comment by danyj** [comment]
OK , is not the theme 

http://prntscr.com/8i1mo5

**Comment by moldcraft** [comment]
Try to add `return;` [here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/1983f2cc540204feb12ea96bc675f6cd17a8750f/class-fw-extension-page-builder.php#L199)

Is your page content big, the page builder has a lot of shortcodes in it? Do you have a lot of `multi-picker` in your shortcode options?

**Comment by danyj** [comment]
yes I do , and yes it is big, If you dont mind , I sent you that page sql , can you see if it is also giving you trouble since I thing it is something in the sortcode that is doing it   be aware it has drop_table 

testing your return now

**Comment by danyj** [comment]
that return did not do anything , same bug

**Comment by danyj** [comment]
ok , i thin  I found something ,  

default theme , went to the page 
Undefined index: link   shortcodes\button\views\view.php on line 2

deleted 3. buttons I had , preview ok 

now testing on my theme , 
I remeber changing options to buttons and that might have caused it

**Comment by danyj** [comment]
disregard previous one ( deleted)  I was in page view not preview

**Comment by danyj** [comment]
Hm , empty page now ,  switched to my theme  same error now on 

\unyson\framework\includes\option-types\icon\class-fw-option-type-icon.php on line 299 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/icon/class-fw-option-type-icon.php#L299

**Comment by danyj** [comment]
strangest thing is that all other pages with that same builder template and other builder templates work just fine , this particular page is only one that is freaking out

**Comment by danyj** [comment]
614 revisions , I am sure that has something to do with ,

**Comment by danyj** [comment]
ok , stop what you doing here , 
I deleted all revisions and it works now , 
looks like my local DB was simply overloaded with all revisions 

Now in the monitn of this stupid revison thing , there is an extensions you guys can make , 

Control revisions and autosaves since none of those are in the core , 
Make an extensions for Unsyons  called Optimize WP or something and here we can keep on adding core features that we might need along the way 

so instead of me adding things in core like this 


	define('AUTOSAVE_INTERVAL', 300 ); // seconds
	define('WP_POST_REVISIONS', 2 );



unyson extension could do that

**Comment by danyj** [comment]
I had to use this 


	DELETE
	FROM wp_posts
	WHERE post_type = 'revision';

https://wordpress.org/support/topic/deleting-post-revisions-do-not-use-the-abc-join-code-you-see-everywhere?replies=3

since there is no native way to delete revisions, crazy
