### ISSUE TITLE
How to check if I am in section/column or theme options?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#865]
I am using a set of 30 options via 

	fw()->theme->get_options( 'optionset' )

same set can be used used in theme and  builder/sections, builder/columns  but just 2 or 3 need changing depending where I am 

in my optionset.php  I want to make a condition that says something like 

    if(section options ) show this option
    if(column options ) show that option
     if(theme options ) show other option 

options are added via 

    $options =array();
    $options []= an option 

this way I can do conditions around them

**Comment by moldcraft** [comment]
```php
fw()->theme->get_options( 'optionset', array('variable_name' => 'variable_value') )
```

```php
// file: .../optionset.php

if (isset($variable_name) && $variable_name == 'variable_value') {
    // ...
}

$options = array(...);
```

**Comment by danyj** [comment]
Like this right ?


	
	// in column
	fw()->theme->get_options( 'optionset', array('thzset' => 'column') )
	
	// in section
	fw()->theme->get_options( 'optionset', array('thzset' => 'section') )
	
	
	if (isset($thzset) && $thzset == 'column') {
		// column option
	}
	
	
	if (isset($thzset) && $thzset == 'section') {
		// section option
	}

**Comment by moldcraft** [comment]
Yes

**Comment by danyj** [comment]
What am I missing here ,   in 

theme/options/settings.php I have 

    fw()->theme->get_options( 'site' ,array('thz_sitetab' => 'themeoptions'))

in   theme/posts/page.php   I have 

    fw()->theme->get_options( 'site' ,array('thz_sitetab' => 'pageoptions'))


in     site.php   I do 


	if (isset($thz_sitetab) && $thz_sitetab === 'pageoptions') {
		fw_print('pageoptions');
	}
	
	if (isset($thz_sitetab) && $thz_sitetab === 'themeoptions') {
		fw_print('themeoptions');
	}


when in  theme settings it is doing it right I see only print for  themeoptions but in page I see both

http://i.imgur.com/HUOJkF5.png

same thing happens with else 


	if (isset($thz_sitetab) && $thz_sitetab === 'pageoptions') {
		fw_print('pageoptions');
	}else{
		fw_print('themeoptions');
		
	}



and side question , how do we detect this same thing , check if column/section/theme settings/page settings  from  custom option view ?

**Comment by danyj** [comment]
just when you can ,  I must detect where I am from option type class also , please let me know if there is a way. thnx!

**Comment by moldcraft** [comment]
> when in theme settings it is doing it right I see only print for themeoptions but in page I see both
> 
> http://i.imgur.com/HUOJkF5.png

* Maybe Theme Settings is not saved, then some code calls `fw_get_db_settings_option(...)` and the settings.php file is loaded to extract default values
* Or something else is loading it. Try to inspect the backtrace to find which script is loading the settings options

    ```php
    <?php echo '<pre>'; debug_print_backtrace(); echo '</pre>';
    ```

> how do we detect this same thing , check if column/section/theme settings/page settings from custom option type view ?

I am not sure I understood the question. I think you want a magic way to detect who included the file, I don't know such thing.

**Comment by danyj** [comment]
ok , to me loks like settings.php loading without being called in page edit 



see  number 4 



	#0  require() called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\general.php:562]
	
	#1  fw_get_variables_from_file(D:\wamp\www\Development\WordPress/wp-content/themes/newtheme/inc/thzframework/theme/options/site.php, Array ([options] => Array ()), Array ([thz_sitetab] => themeoptions)) called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\core\components\theme.php:74]
	
	#2  _FW_Component_Theme->get_options(site, Array ([thz_sitetab] => themeoptions)) called at [D:\wamp\www\Development\WordPress\wp-content\themes\newtheme\inc\thzframework\theme\options\settings.php:16]
	
	#3  require(D:\wamp\www\Development\WordPress\wp-content\themes\newtheme\inc\thzframework\theme\options\settings.php) called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\helpers\general.php:562]
	
	#4  fw_get_variables_from_file(D:\wamp\www\Development\WordPress/wp-content/themes/newtheme/inc/thzframework/theme/options/settings.php, Array ([options] => Array ()), Array ()) called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\core\components\theme.php:74]
	
	#5  _FW_Component_Theme->get_options(settings) called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\core\components\theme.php:86]
	
	#6  _FW_Component_Theme->get_settings_options() called at [D:\wamp\www\Development\WordPress\wp-content\plugins\unyson\framework\core\components\backend.php:484]
	
	#7  _FW_Component_Backend->_action_admin_menu()
	
	#8  call_user_func_array(Array ([0] => _FW_Component_Backend Object ([] => lambda_8597,[] => FW_Form Object ([] => fw_settings,[] => Array ([data-fw-form-id] => fw_settings,[class] => fw_form_fw_settings,[method] => post,[action] => ),[] => ,[] => ,[] => ,[] => 1,[] => Array ([render] => Array ([0] => _FW_Component_Backend Object ( *RECURSION*,[1] => _settings_form_render),[validate] => Array ([0] => _FW_Component_Backend Object ( *RECURSION*,[1] => _settings_form_validate),[save] => Array ([0] => _FW_Component_Backend Object ( *RECURSION*,[1] => _settings_form_save))),[] => Array ([0] => default,[1] => taxonomy,[2] => customizer),[] => default,[] => Array ([0] => FW_Option_Type_Multi_Select,[1] => FW_Option_Type_Form_Builder,[2] => FW_Option_Type_Slides,[3] => FW_Option_Type_Page_Builder,[4] => FW_Option_Type_ThzContentLayout,[5] => FW_Option_Type_ThzTemplates),[] => Array (),[] => ,[] => Array (),[] => Array (),[] => ,[] => ,[] => ),[1] => _action_admin_menu), Array ([0] => )) called at [D:\wamp\www\Development\WordPress\wp-includes\plugin.php:503]
	
	#9  do_action(admin_menu, ) called at [D:\wamp\www\Development\WordPress\wp-admin\includes\menu.php:149]
	
	#10 require_once(D:\wamp\www\Development\WordPress\wp-admin\includes\menu.php) called at [D:\wamp\www\Development\WordPress\wp-admin\menu.php:271]
	
	#11 require(D:\wamp\www\Development\WordPress\wp-admin\menu.php) called at [D:\wamp\www\Development\WordPress\wp-admin\admin.php:138]


in       options/page/page.php  I am calling this  which is  number 2 



    fw()->theme->get_options( 'site' ,array('thz_sitetab' => 'pageoptions'))

not settings.php

I checked all functions that call fw_get_db_settings 
http://prntscr.com/8q3ayw

none is called in admin 


are you saying that if some option value says 


    fw_get_db_settings ('thisvalue','defaultvalue');

it will load settings.php  ?

**Comment by danyj** [comment]
never mind , I got figured out , left vars in 1 file  only , no mistakes

**Comment by moldcraft** [comment]
I remembered where the settings options are included on every refresh, [here](https://github.com/ThemeFuse/Unyson/blob/5777e3a853d2e4231df7c5f7078434f69c636333/framework/core/components/backend.php#L484) (the Theme Settings menu is created only if theme settings are not empty).

I will add `file_exists()` instead, it will be faster and will not load that (in some cases) huge array on every page load.

P.S. Thank you very much for inspections, with your help we fix some deep bugs.

**Comment by moldcraft** [comment]
[Done](https://github.com/ThemeFuse/Unyson/commit/3f0a5b7b68ada259ce0ebba5a883df26a880686f)

**Comment by danyj** [comment]
glad I could help bud . we have to get ready for all the questions that customers might trow at us, thus the release delay until we learn everything.


side question , this now works ok , but I have a problem that https://github.com/ThemeFuse/Unyson/blob/5777e3a853d2e4231df7c5f7078434f69c636333/framework/core/components/backend.php#L1100

cant see those conditional vars we use ,  

example , in topmenu.php where settings for menu are  I have 



	if (isset($thz_topmenutab) && $thz_topmenutab === 'pageoptions') {
		
		$tm_nameprefix = 'fw_options[custom_post_style][custom]';
		$tm_idprefix = 'fw-option-custom_post_style-custom-';
		$tm_location= 'pageoptions';
		
	}else{
		
		$tm_nameprefix = 'fw_options';
		$tm_idprefix = 'fw_options-';
		$tm_location= 'themeoptions';	
		
	}

this is visible on page load , 
http://prntscr.com/8q3pm1
now when I change the topmenu template I do this  via ajax fw_options_render and the html that comes back sees the else condition instead  
http://prntscr.com/8q3pvl

that data attribute is in option type view and is pushed via the param in the option 
http://prntscr.com/8q3qds

longs story short , how do I get this right without js search and replace. is it possible ?

**Comment by moldcraft** [comment]
How is [that parameter](http://prntscr.com/8q3qds) lost? It should be in OptionsModal in `options` attribute. Or I am missing something?

**Comment by danyj** [comment]
it is lost because it is checked on page load, now ajax is not loading the edit or settings page but only renders the options , thus I cant see it in response , 


I used original 

    $data['id_prefix']

and 

  $data['name_prefix']

as reference instead of those conditional vars and it works. 

Have another issue but will pick your brain next time if I am not able to get it. Thnx bud. Happy Sunday hah :)
