### ISSUE TITLE
Using as a part of a theme and only the pagebuilder?

### ISSUE THREAD

**Issue by LehtinenRiku** [ThemeFuse/Unyson#867]
Hello..

How can i use this as a part of a theme, not as a plugin?

I tried http://manual.unyson.io/en/latest/ > "Install anywhere". I added that mentioned code to my functions.php and changed the uris to correspond my theme's folder structure. Doesn't seem to work form me. In fact, it's not working as a plugin either. It only shows "No extensions activated yet
Check the available extensions below" and there is nothing to show..?

Can we get a bit more specific instructions for dumbs like me?

Is it possible to include only the pagebuilder to a theme? Like "comment out" everything else?

**Comment by moldcraft** [comment]
> Doesn't seem to work

More details please. It throws errors/notices, nothing is displayed, or just available extensions are not displayed?

> Is it possible to include only the pagebuilder to a theme? Like "comment out" everything else?

The framework doesn't have such feature. You can do it manually (install extensions you need and put the `framework/` in theme), but at some point, the framework will get old and you will have to update it somehow manually.

**Comment by LehtinenRiku** [comment]
I'm developing locally using MAMP and multisite. I copied framework-folder to my theme-folder and added this to my functions.php:

```
if (defined('FW')):
    // the framework was already included in another place, so this version will be inactive/ignored
else:
    /** @internal */
    function _filter_fw_framework_plugin_directory_uri() {
        return '/framework';
    }
    add_filter('fw_framework_directory_uri', '_filter_fw_framework_plugin_directory_uri');

require dirname(__FILE__) .'/framework/bootstrap.php';
endif;
```

Unyson is lacking icon and Unyson-page is empty. (Shows only "Unyson Extensions" title).
It also changed "Posts" to "Blog posts" from WP-admin sidebar. (Wasn't in english originally.)

![nayttokuva 2015-09-21 kello 20 26 42](https://cloud.githubusercontent.com/assets/11766672/9999440/1ce0876c-609f-11e5-9329-ce62ee46cef9.png)

What is the best way to use it on premium theme?

**Comment by moldcraft** [comment]
> return '/framework';

That is the uri to `http://site.com/wp-content/themes/your-theme/framework` ?

> Unyson-page is empty

I will test that tomorrow.

> What is the best way to use it on premium theme?

ThemeForest will not accept a theme with a framework in it (it violates Plugin Territory). Everything that is related to functionality and content should be in plugins, everything that is related to design should be in theme.

> changed "Posts" to "Blog posts"

You can disable that by doing `remove_action()` for [these actions](https://github.com/ThemeFuse/Unyson-Blog-Extension/blob/144e2aa4f26b6a536cccc1ad8577e5c352244038/class-fw-extension-blog.php#L13-L14)
