### ISSUE TITLE
Redirects to localhost after demo install

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#869]
Hi. For some of our users, while installing demo, it redirects to: http://localhost/theme/wp-admin/upgrade.php?_wp_http_referer=%2Fwp-admin%2Foptions-general.php%3Fpage%3Dwp-maintenance-mode

How to fix that?

**Comment by llemurya** [comment]
@darwinteam the demo install was done correctly or the users was redirected to 503 page? Can you ask about this detail please.

**Comment by darwinteam** [comment]
it was done correctly

but from my experience we face 503 page error as well, on some hosts

**Comment by darwinteam** [comment]
Something else:

The user problem: 
I keep getting a 500 internal error while installing the demo.

The cause he claims:
We finally changed over to Linux (server) and that seems to have solved the problem.

**Comment by darwinteam** [comment]
Any news guys?

**Comment by moldcraft** [comment]
Sorry, no news.

We are busy with other issues and I am not familiar with Demo Install code, you can try to find the problem yourself.

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
