### ISSUE TITLE
(demo data install ) Fatal error: Call to a member function query() 

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#872]
Hello, 
I am trying to instal demo content on the fresh server and wp, but always appears this error during content installation:

mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given
Fatal error: Call to a member function query() on a non-object in /home/content/p3pnexwpnas09_data01/85/2842885/html/wp-content/plugins/unyson/framework/extensions/backup/includes/lib/srdb.class.phpon line 622

After this error I could not access wp so I had to reinstall new wp. I tryied to instal demo content few times, but always the same error appers.

Any ideas?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/851#issuecomment-139749157

**Comment by duongancol** [comment]
This error come from db_escape function, but it's hard to debug because it only happen on some hostings. You could try to disable escape function by going to : 
plugins/unyson/framework/extensions/backup/includes/lib/srdb.class.ph
Then find & remove all <strong>$this->db_escape</strong>

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
