### ISSUE TITLE
Option type unique  does not work right in addable-popup when section/column copied

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#873]
I have unique opt type in  addable-popup  inside cloumn/section options

		'popup-options' => array(
			'id' => array(
				'type' => 'unique',
				'length' => 8
			),

I than copied the section and the unique is not updating 

inside of my loop for addable-popup I printed an ID and image 

this is what I get 
http://prntscr.com/8jj7lb

different images , same id

**Comment by danyj** [comment]
Even tried to open the popup and save it again but does not update the id

**Comment by danyj** [comment]
Works only if I delete the popup , create new one and save

**Comment by moldcraft** [comment]
The save process stops on option type. If option type contains other options, it's its job to "trigger" (re)save for those options. So I will try to call `_get_value_from_input()` for each option in addable-popup (so that will execute unique option type and a new id will be generated)

**Comment by danyj** [comment]
ok , waiting to test,. thnx for looking at it. , or you might want to do it just for unique , since other are not changeable, so we wont overload it for no reason

**Comment by danyj** [comment]
kinda like if type unique  _get_value_from_input()

**Comment by danyj** [comment]
@moldcraft  check mail please.

**Comment by moldcraft** [comment]
Ok *(at the moment I am busy with [this](https://wordpress.org/support/topic/typography-didnt-work-in-customizer))*

**Comment by moldcraft** [comment]
Test please

**Comment by moldcraft** [comment]
Tested?

In two hours I will release the new Unyson version.

**Comment by danyj** [comment]
sorry mate was busy with icons, will get on it now

**Comment by danyj** [comment]
nope , still same

**Comment by danyj** [comment]
@moldcraft   tested again , still same issue , must delete popup and create new one

**Comment by moldcraft** [comment]
I added in section options this

```php

'a-i' => array(
	'type' => 'addable-popup',
	'popup-options' => array(
		'u' => array('type' => 'unique'),
	),
	'template' => '{{- u }}'
),
```

and [it works](https://vid.me/a0Zp).

How do you test it?

**Comment by danyj** [comment]
add it inside column ,  

add section , add column , open column option add   popup , save 

now  copy the section and id will be same

**Comment by moldcraft** [comment]
The id update is happening after post save.

**Comment by danyj** [comment]
no is not I tested that also

**Comment by danyj** [comment]
first one

http://prntscr.com/8jziou

second one 

http://prntscr.com/8jzitf


http://prntscr.com/8jzix0

**Comment by moldcraft** [comment]
* Do you have the latest dev version of Unyson?
* Can you give me your option example so I can test it?

**Comment by danyj** [comment]
Yes latest and I just used yours , see above

**Comment by moldcraft** [comment]
I don't know what to do now. (on my side it works)

**Comment by danyj** [comment]
try it inside a tab

**Comment by danyj** [comment]
I have tabs in options

**Comment by danyj** [comment]
Here video 
http://www.screencast.com/t/9kd68OBRVV

I now deleted all column options and used 


	$options = array(
	
		'a-i' => array(
			'type' => 'addable-popup',
			'popup-options' => array(
				'u' => array(
					'type' => 'unique',
					'length' => 10,
					),
				
			),
			'template' => '{{- u }}'
		),
	);

**Comment by danyj** [comment]
stop , seems like is ok ,  I redownloaded dev and update d, previously I downloaded only the addable popup , still testing

**Comment by danyj** [comment]
It works , on preview and update , sorry for the trouble but you see I was testing as much as possible , continue with release, sorry again

**Comment by moldcraft** [comment]
> previously I downloaded only the addable popup 

The code that does this feature is in option type `unique`, in option type `addable-popup` I added only `apply_filters(...)`

Ok, Thank you
