### ISSUE TITLE
Obsolete extensions

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson#874]
Hello Unyson Users,

We plan to pause the development of some extensions: 

* Styling
* Translation
* Learning
* ~~Feedback~~ *We will not remove this (decided on 06.10.2015)*

and to have more time to support core, options and builder.

##### [Here](https://live.amcharts.com/YjgzZ/) is the statistics of number of requests to `http://github-api-cache.unyson.io/`

How we will pause those extensions:

* If extension is not installed, if it is not set as "Compatible with current theme", it will be hidden from Unyson extensions list in admin
* We will not delete them (just hide from admin). All extensions will continue to work fine for users who already installed them.

When Unyson will become more popular, it will have less issues/bugs, and we will have more free time, we will continue the development of those extensions.

**Comment by WPJobs** [comment]
Hello, moldcraft!

Could you clarify please, if you will remove Translation extension, what plugin can you recommend instead? Is Unyson 100% compatible with WPML?

Thank you

**Comment by moldcraft** [comment]
We will never remove any extension, because there are themes that uses them. We will just hide them from the extensions list, and maybe will show them back later.

**Comment by WPJobs** [comment]
thank you for quick answer, but could you tell me about WPML, is Unyson compatible with this plugin?

**Comment by moldcraft** [comment]
It is compatible

**Comment by thednp** [comment]
But would it be able to replace WPML in the future?

**Comment by moldcraft** [comment]
Replace with what?

**Comment by thednp** [comment]
The translation extension.

**Comment by llemurya** [comment]
@thednp the translation extension works as WPML but it is not tested as well as WPML ,and we decide to put it on hold , but you can test is and report the bugs and it will be fixed.

**Comment by thednp** [comment]
Alright, that's what I wanted to hear, because I couldn't really make a difference, I never tested both, but I will contribute in the future for the development.

**Comment by WPJobs** [comment]
Thank you guys! I would like to create my next theme using your translation extension, i love your work more than WPML plugin

**Comment by kaxigt** [comment]
tnx for answer.
