### ISSUE TITLE
Setting unycon icon groups

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#875]
I am trying to follow instructions here 
https://github.com/ThemeFuse/Unyson/tree/master/framework/static/libs/unycon

to get icon groups but it does not work , loads as undefined

**Comment by moldcraft** [comment]
loads as undefined?

**Comment by danyj** [comment]
yes the script that we should  toi use in console , returns undefined

**Comment by moldcraft** [comment]
Step 7. ?

**Comment by danyj** [comment]
comes back empty http://prntscr.com/8jp1fp

**Comment by moldcraft** [comment]
In screenshot I see that you are executing steps in random order: 1. 7. 2. 5. 7.

**Comment by danyj** [comment]
got it , is confusing ,

**Comment by danyj** [comment]
side quest , how did you get the index export from iconmoon ?

**Comment by moldcraft** [comment]
I made index manually. Demo.html is from iconmoon export

**Comment by danyj** [comment]
ok , thnx
