### ISSUE TITLE
Unyson Customizer refresh time

### ISSUE THREAD

**Issue by efes-s** [ThemeFuse/Unyson#876]
Hi!
How can I change iframe refresh time?
When I change Customize Option  e.g. Page Width slider  then iframe is refreshed some (part of) seconds. 
I would like real time iframe refresh.    

How to get that?

**Comment by moldcraft** [comment]
At the moment you can't. We will add that possibility (maybe tomorrow)

**Comment by moldcraft** [comment]
I added [this filter](https://github.com/ThemeFuse/Unyson/commit/156f8c389689d91285db95c81c433964c17e6beb#diff-8e628e2362d97faf414c064ad2478754R1833)

It will be available tomorrow in the next release (2.4.8)

**Comment by efes-s** [comment]
Thanks!
