### ISSUE TITLE
Any reason behind unycon class selector ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#877]
Is there specific reason behind  this 

https://github.com/ThemeFuse/Unyson/blob/master/framework/static/libs/unycon/unycon.css#L12

with that ,class must be declared as 

    <i class="unycon unycon-photo-camera"></i>

if you use this 

	[class^="unycon-"], [class*=" unycon-"] {
		......

than we dont need the stray class and can use 

    <i class="unycon-photo-camera"></i>

in iconmoon app comes with it if you select this http://prntscr.com/8jq7rr

instead of class selector as you did

**Comment by moldcraft** [comment]
* Because FontAwesome, Glyphicon and Dashicons are doing so
* I thought that `[class^="prefix-"], [class*=" prefix-"]` is slower (because is like doing a regex on all html elements). And I was right:

    * https://github.com/FortAwesome/Font-Awesome/issues/940#issuecomment-18115625
    * https://github.com/FortAwesome/Font-Awesome/issues/568 

        * [Font Awesome v3.x](https://github.com/FortAwesome/Font-Awesome/blob/v3.2.1/css/font-awesome.css#L37-L38)
        * [Font Awesome v4.x](https://github.com/FortAwesome/Font-Awesome/blob/v4.4.0/css/font-awesome.css#L14)

**Comment by danyj** [comment]
thnx much for the info!
