### ISSUE TITLE
Theme Settings: multiple boxes in a tab?

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#878]
Hello there,

We're setting up the Theme Settings for a new theme. We've got several main tabs, like General, Header, Sidebar and Footer.

We wanted to have multiple boxes on these tabs, so our settings will be shown as uncluttered as possible. We can add multiple boxes on a tab, but when loading the Theme Settings only the first box of every tab is opened. Is it possible to have all boxes opened by default?

**Comment by moldcraft** [comment]
Hello,

I will need to add [this](https://github.com/ThemeFuse/Unyson/issues/466#issuecomment-93797869) to each box

**Comment by warudin** [comment]
Awesome, thanks a lot!
I'm sorry for the duplicate question, I didn't stumble upon it with search.
