### ISSUE TITLE
fw_render_view  messing up json strings 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#879]
I need to output data-attr  as a json string but want to use html chars so that I dont have to use single quote in html ,  in option  class render I used 

    $option['attr']['data-categories'] =  fw_htmlspecialchars(json_encode($option['categories']));

it outputs 

     [&amp;quot;Awesome&amp;quot;,&amp;quot;Spinners&amp;quot;]

if I go directly inside the view   and do 

    <?php echo fw_htmlspecialchars(json_encode($option['categories']))?>

I get proper string

    [&quot;Awesome&quot;,&quot;Spinners&quot;]

you see in first one the is adding  &amp

**Comment by danyj** [comment]
i think is fw_attr_to_html  that is adding &amp

**Comment by moldcraft** [comment]
When adding something to `$option['attr']` you don't need to escape it. It will/should be escaped in view by using `fw_attr_to_html()`

**Comment by danyj** [comment]
ok  so fw_attr_to_html was already doing the job I went over with fw_htmlspecialchars, thnx!
