### ISSUE TITLE
How to add own icon option to mega menu

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#880]
I created our own icon option and would like to replace the mega menu Icon option with mine. How can I do that ?

**Comment by llemurya** [comment]
@danyj you can do this if you create your clone of the megamenu extension ,because now the icon picker is hardcoded in mega menu, and the option types didn't work in the menu , you must see the `megamenu/includes/class-fw-ext-mega-menu-admin-walker.php` and replace our icon html with yours and make changes in javascript. Hope my answer will help you.

**Comment by moldcraft** [comment]
@llemurya thanks, but doing a clone is too hard. I will try to add the possibility to change icon option

**Comment by danyj** [comment]
@llemurya   tried last night in the walker but it is not accepting the option since the popup is in js calling the icon options , so no matter what I change the option in walker it does not display in the popup. 

@moldcraft  thnx for looking at it and while you at it let us add own options , I asked in Feb about this 

https://github.com/ThemeFuse/Unyson/issues/240

I am mostly asking about adding the image to the container , so kinda  bg option in the menu settings

**Comment by danyj** [comment]
@llemurya   this is just that button 

https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/includes/class-fw-ext-mega-menu-admin-walker.php#L185

and changing type here 

https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/class-fw-extension-megamenu.php#L71

does not do anything since the rest is hardoced

**Comment by sandrodz** [comment]
having same issue, @moldcraft any insights?

**Comment by moldcraft** [comment]
That option is [hardcoded](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/71dc84e3d79b00c1dfe5925fce3cc8ad1258c119/static/js/admin.js#L87-L90). We will add the possibility to change it via filter, soon

**Comment by sandrodz** [comment]
What time frame are we talking about? few days? a week? month?

I'm asking cause this is the last piece of the customisation (I applied custom walker to mega menu). If 'soon' is too far in the future, I will simply put whole extension in framework-customizations and launch the project.

**Comment by moldcraft** [comment]
A few days

**Comment by sandrodz** [comment]
great news! I will wait :)

**Comment by moldcraft** [comment]
Download the latest dev version of [MegaMenu extension](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension), extract in `unyson/framework/extension/megamenu` and use [this filter](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/cedb15bf553e3580455c77bec6b534790183ed0e/class-fw-extension-megamenu.php#L56). The new version will be released soon

**Comment by danyj** [comment]
this is nice addon but why are we limited to icon option only. I asked almost a year ago https://github.com/ThemeFuse/Unyson/issues/240#issuecomment-74965198 about additional option in there so that we can define background image

**Comment by moldcraft** [comment]
I know about that issue, it's time hasn't come yet.

**Comment by sandrodz** [comment]
@moldcraft how do we use this filter? https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/cedb15bf553e3580455c77bec6b534790183ed0e/class-fw-extension-megamenu.php#L56

**Comment by moldcraft** [comment]
@sandrodz 

```php
function _filter_mega_menu_icon_customizations($option) {
    $option['label'] = __('Hello', 'fw');

    return $option;
}
add_filter(
    'fw:ext:megamenu:icon-option', 
    '_filter_mega_menu_icon_customizations'
);
```

**Comment by sandrodz** [comment]
Some things are still hardcoded in js:

fa -> changed to -> Icon
```
		// Immediately close dialog after clicking on icon
		$(modal.frame.$el).on('click', '.Icon', function () {
			modal.set('values', {
				icon: $(this).data('value')
			});
			modal.frame.close();
		});
```
fa fa-lg -> Icon
```
		$(document).on('change', selector, function (event) {
			var field = $(this).closest('.field-mega-menu-icon');
			var value = $(this).val();
			field.toggleClass('empty', value == '');
			field.find('[data-subject=mega-menu-icon-i]').attr('class', 'Icon ' + value);
		});
		$(selector).change();
```

So what are we doing about these? custom icons definitely will need custom classes.

**Comment by sandrodz** [comment]
I still need to test this. so now only thing we need to do is this:

```
function _filter_mega_menu_icon_customizations($option) {
    $option['label'] = __('Hello', 'fw');

    return $option;
}
add_filter(
    'fw:ext:megamenu:icon-option', 
    '_filter_mega_menu_icon_customizations'
);
```
correct?

**Comment by moldcraft** [comment]
Yes
