### ISSUE TITLE
Images files no longer showing after migrating website from Mamp to Live Server

### ISSUE THREAD

**Issue by knewgi80** [ThemeFuse/Unyson#881]
I was very excited to find the Unyson Plugin for Wordpress and have built a great portion of my site using your plugin. However when I migrated the site from my localhost Mamp to my live server using Backup Buddy, everything Wordpress based migrated beautifully except the image files and sliders created in Unyson. When going into Wordpress, the image files have the correct new URL, but when looking at the website live through a browser the images appear with "localhost:8888/wp-content/...." not found... This is only for the images and sliders, the formatting and layout seems to have migrated nicely.
how can I fix this? any help is appreciated. I am new to creating websites so beginner instructions are preferred. Thank you!

![screenshot](https://cloud.githubusercontent.com/assets/14834725/10097326/8fb12ae0-6378-11e5-9717-920c3f5ec16b.PNG)

**Comment by duongancol** [comment]
I think it's problem of Backup Buddy, not Unyson

**Comment by moldcraft** [comment]
I think in database there are `http:\\\/\\\/localhost` which Backup Buddy didn't replaced

https://github.com/ThemeFuse/Unyson-Backup-Extension/blob/master/includes/helpers/class-fw-backup-helper-database.php#L383-L385

At the moment I don't know a beginner instruction.

**Comment by danyj** [comment]
@knewgi80  did you try Unyson backup ?

**Comment by knewgi80** [comment]
Perhaps you could give me a tip then how to migrate the unyson plugin to a
new site without this hassle.
Am 25.09.2015 12:11 schrieb "moldcraft" <notifications@github.com>:

**Comment by danyj** [comment]
Download Unyson backup extension  http://prntscr.com/8k9hfq
Go to tools/backup  http://prntscr.com/8k9hil
Click on Create Demo Install  http://prntscr.com/8k9hnw
Watch this  http://manual.unyson.io/en/latest/extension/contentdemoinstall/

**Comment by knewgi80** [comment]
I have just gone through all the steps, after installing the content 
demo install into my server wordpress version, it installs the theme 
FIVE times and each one messes up my webpage completely, the images are 
not there, and even the main menu on the start page is completely 
random. This was not a solution for me. To build my homepage I didn't 
use Unyson exclusively but also Wordpress itself.

I am more than frustrated at the amount of time I have already spent on 
this! At this point I am frustrated for even having used Unyson, not 
only do I have to deactivate it when I want to work on a pure wordpress 
page, but now that my website is ready to launch all my hours of 
formatting with Unyson are completely wasted. And I'm too much a 
beginner to be able to work on the code level to change the image 
connections. I used Backup Buddy for a lack of a better migrating 
software, if you have a better suggestion that works well with Unyson, 
please let me know.

This instruction was not helpful to me:

*I think in database there are **|http:\\\/\\\/localhost|**which Backup 
Buddy didn't replaced*

**

*https://github.com/ThemeFuse/Unyson-Backup-Extension/blob/master/includes/helpers/class-fw-backup-helper-database.php#L383-L385*

**

*At the moment I don't know a beginner instruction.
*

I do now know what I need to change to have \\\/ working properly, I 
don't even understand the reference.


Am 9/25/2015 um 12:26 PM schrieb Dan:

**Comment by moldcraft** [comment]
https://www.google.com/#q=mysql%20replace%20string%20in%20database

**Comment by moldcraft** [comment]
https://www.google.com/#q=mysql%20replace%20string%20in%20database

* Find 'localhost:8888', replace with `your-site.com`

**Comment by knewgi80** [comment]
The google link only opens an empty google search engine.

in what file do I change the localhost:8888? In unyson.php (which file 
there are SO many). Wordpress managed to change its own content to the 
online server, only Unyson images did not.

Am 9/25/2015 um 3:54 PM schrieb moldcraft:

**Comment by moldcraft** [comment]
> in what file do I change the localhost:8888?

http://stackoverflow.com/a/4822691

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
