### ISSUE TITLE
Create demo install hangs 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#882]
Was just testing demo install for fellow coder and mine hangs 
http://prntscr.com/8k9ike
Any info about it? 
Checked logs no errors  also checked files and netowrk everything seems ok 
http://prntscr.com/8k9jcx

**Comment by danyj** [comment]
Please take a look at this , second time I am trying to test 
http://prntscr.com/8rim72

the ajax hangs on that same  action ,  I tried to test it for #937

**Comment by moldcraft** [comment]
We are on a halfway to Backup v2

You can help us testing it:

* [Download](https://mega.nz/#!Z5NCjKjK!kNmnh5FvY5N5V97gYU61XfnomCGPeOjRnhjDdDR4ATg) and extract in `plugins/unyson/framework/extensions/backup`
* Open in admin Tools > Backup
* Press the "**Create Full Backup**" button (only this button works at the moment)

Please test it on different servers, to make sure we will have no problems with specific hosting providers.

**Comment by danyj** [comment]
ok will do

**Comment by moldcraft** [comment]
Warning! There is a bug that makes infinite backup of backups directory.

If you are seeing 'Background task running: Copy files' for too long time, please run this sql (in phpmyadmin or from php script)

```sql
DELETE FROM `wp_options` WHERE option_name = 'fw:ext:backup:active_task_collection'
```

**Comment by danyj** [comment]
ok , publishing joomla template for youjoomla  just now , will get to this in about 2-3h

**Comment by moldcraft** [comment]
Ok, 'till then I will update the Download link

**Comment by danyj** [comment]
let me know when you update the link. i'm pushing promo emails out now

**Comment by moldcraft** [comment]
I did

**Comment by danyj** [comment]
Testing now

**Comment by danyj** [comment]
Ohhh, nice one , 
http://prntscr.com/8rkpa5

it ran long for about 6min , than was zipping archive , completed now but I see no backups
the one you see here http://prntscr.com/8rkqwd  is old

**Comment by moldcraft** [comment]
I am testing it on a server and have the same problem

So to not waste time, do not test this anymore. When I will fix this problem I will let you know.

**Comment by danyj** [comment]
system , win wamp , php   5.4.13

**Comment by moldcraft** [comment]
Thanks

**Comment by moldcraft** [comment]
###### Status update

After 2 days of headaches with the Zip step, I found the problem:

It is not possible to do this fast: open a zip file, add a few files in it and close it. With all libraries I have tried, this happens:

* A temp copy of the original zip is created
* The modifications are added
* The zip is re zipped/compressed/processed
* The original zip is replaced

So if you have a 500Mb zip, just adding a new file in it will take long time.

So I don't have any choice and the Zip step will be execute in one step, all files will be compressed at once (this is the fastest way). Here the old problem, the timeout, remains, and for this step we will try to increase the php timeout limit and hope for the best.

I will give you the download link when the next alpha/beta version will be finished.

**Comment by danyj** [comment]
ok , waiting for it,  not sure what zip libs you have but I have great experience with dZip  
https://github.com/vtiger-crm/vtigercrm/blob/master/vtlib/thirdparty/dZip.inc.php
and dUnzip2.inc, http://www.phpclasses.org/browse/file/10410.html

we use it for licensing and can extract template demos , search for license hook , replace and zip back up.

**Comment by moldcraft** [comment]
New Backup v2 alpha version

What works:

* Full backup: db and root dir
* Restore: only db restore

[Download](https://mega.nz/#!s0kH2QBK!SxdezvEuDDUaMeFpIQWPUj4ua7xQhEFxHRwPDjq5eF4)

Now I am working (thinking) on files restore.

**Comment by martinburdon** [comment]
Hi, can the v2 alpha be used to create and use demo installs?

**Comment by moldcraft** [comment]
no. don't use it for production purposes.

**Comment by martinburdon** [comment]
Do you know when it will be possible to use the demo content install features again? I was planning on using it with a theme I have in production but came across the issues from this https://github.com/ThemeFuse/Unyson/issues/944

**Comment by moldcraft** [comment]
Within a month

**Comment by martinburdon** [comment]
Excellent, thanks :+1:

**Comment by martinburdon** [comment]
Hello, I just noticed when playing about with v1 that my password is displayed in the `database.txt` file that is generated from the content install. Is it possible to remove it/will it be removed in v2?

**Comment by moldcraft** [comment]
Ok, in v2 when creating Content export it will not include user details

**Comment by danyj** [comment]
nic cath @martinburdon :100:

**Comment by moldcraft** [comment]
We decided that Backup v2 will be a separated extension, with a different name: backup**s**. So it will not conflict with v1, themes or extensions that are calling public methods `fw_ext('backup')->hello()` will not break, and we don't have the problem to provide the compatibility for old export format (backups made with v1).

At the moment backup and restore works. [Download](https://mega.nz/#!44cymTYY!W-51SWC8XrvpYnB8akbR98ak6Q0a3IBB_N8TG0KYD9w) the latest dev version and extract in `unyson/framework/extension/backups` Important: backup**S** (do not forget to active it on Unyson extensions page, it will be without thumbnail image)

Now we are working on "multiple demo content" feature: a page where the user has a list of demos and choose which demo content to import.

**Comment by martinburdon** [comment]
Awesome, multiple demo content is exactly what I need and will be really handy for anyone wanting to create several demos for customers.

Any idea when a version of the new backup extension will be integrated into the main Unyson release?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/882#issuecomment-150336337

**Comment by danyj** [comment]
>Now we are working on "multiple demo content" feature: a page where the user has a list of demos and choose which demo content to import.

BRAVO!

**Comment by maiakhoa** [comment]
*Problem:* Anyone having the problem with large upload folder of demos because if we use *fw_resize()* function, there are many images included in upload folder beside some default size images generated by WordPress ? If you include upload folder in *auto-install*, the size of theme is large. 

*Solution:* I solved this by custom backup extension and just import db file, after that, I use WordPress Importer to import media files from the server, with this way, we just import needed images for demo and the size of theme is small enough.

*Suggestion:* I suggest that in the new version of *Backups* extension, can we have a solution similar my solution to solve large upload folder.

**Comment by duongancol** [comment]
@maiakhoa I know this ways but There's a disadvantage if make this ways, if you have multiple-demo, for example 5 demos, you have to create 5 demo sites and 5 other demo sites for placeholder image. Totally 10 demo sites. It's hard to manage

**Comment by maiakhoa** [comment]
@duongancol the first version of our theme, I included all demos with upload folder in the package that sell to customers, and in our case, it's approximately 150mb for 4 demos. I know that we can guide customers copy the auto-install folder to theme folder if they want to import the specific demo. And I think it has a little difficult for them, besides that some customers they don't know how to upload the theme via FTP if the theme exceeds the limited upload file size via WordPress. As the result, we received a support ticket for such case. 
So I decided to take care of heavy work by copying 4 upload folders to the server (don't setup WordPress to bypass requests through WordPress core) and change the URL of media files that exported by **WordPress Exporter**. After implement the solution I wrote below, the size of our theme with 4 demos reduced to 3mb, it acceptable. Our customer can select one of them to import without additional actions.
I know this way bring more works for our team before releasing the theme, but it make install steps seamlessly and specifically avoid large size of theme, also reduce support ticket.

**Comment by c0sm1n87** [comment]
@duongancol I understand what you were saying, I ran in this exact issue with my own theme. 

However, I did not create websites with placeholder images, I just ran a Photoshop script to load the images from the archive, add a solid color overlay with a watermark that said "Placeholder" image and overwrite the original file.

Maybe not the best solution, but it's easier than creating dedicated demo servers with placeholder images.

**Comment by moldcraft** [comment]
Sorry, I know you are waiting, but we are not ready yet (almost done).

Here is the latest dev version that you can test [Download](https://mega.nz/#!g0UlmYTS!aYj93Py4YGlMcQPiT4EZwWq5SqTWpCr-vCLAC04WKlo)

* Schedule works
* Full/Content Backup/Restore works
* Multiple Demo Install works

#### How to create demo installs

* Create **Content Backup**
* Extract the zip in `{theme}/demo-content/{demo-name}/`
* Create `manifest.php` in `{theme}/demo-content/{demo-name}/` with the following contents:

    ```php
    <?php if (!defined('FW')) die('Forbidden');
    /**
     * @var string $uri Demo directory url
     */

    $manifest = array();
    $manifest['title'] = __('Awesome Demo', 'fw');
    $manifest['screenshot'] = $uri . '/screenshot.png';
    $manifest['preview_link'] = 'https://your-site.com/demo/awesome';
    ```

I need to finish a few little things, then (at the end) design fixes.

**Comment by moldcraft** [comment]
The latest dev version with fixes for multisite [Download](https://mega.nz/#!thNw0T5T!RzYsopz-q5gknLTitsm_xnQ21dCvCV27xNQOYdE5JnQ)

**Comment by duongancol** [comment]
I tested to create Demo Content. It worked. But when I import this Demo, it loaded more than 4 minutes and displayed 'Time Out' without demo content. I tested on Mamp Pro. The demo content folder is 34mb.

**Comment by maiakhoa** [comment]
@duongancol I tested and had the same error like you, but I found out that we have to update framework folder of Unyson to the latest version from source code (it missed class-fw-type-register and class-fw-type). Then it worked for me, hope that it solves your issue.
@moldcraft nice work, I saw that the performance for importing has much improved. I have one question, do you have the plan to create a remote download type? I think It really helpful if we can provide one more option (remote download type) beside local download type.

**Comment by moldcraft** [comment]
Yes, update framework, latest dev version from github (I firgot about that)

**Comment by moldcraft** [comment]
Yes, remote download is on the way (we, ThemeFuse, will use it to)

**Comment by maiakhoa** [comment]
@moldcraft thanks, I tested the new extension on PHP 5.2 and occurred an error: RecursiveDirectoryIterator::SKIP_DOTS is not supported on PHP 5.2, so do you have alternative solution for this issue ?

**Comment by moldcraft** [comment]
Thank you for the report, I will find a solution

**Comment by maiakhoa** [comment]
Thanks @moldcraft

**Comment by duongancol** [comment]
Yes, it works well. Thank @maiakhoa & @moldcraft

**Comment by c0sm1n87** [comment]
congratz @moldcraft, you're making this so easy for us :D

**Comment by duongancol** [comment]
it seem that we have to use remote download for demo content now. In my latest theme, it got soft rejecte from reviewer with the message bellow:
<strong>Sorry to say but we no longer allow auto-install folder by Unyson which creates it's own database and drops the rest.

http://manual.unyson.io/en/latest/extension/contentdemoinstall/index.html?highlight=auto%20install</strong>

**Comment by martinburdon** [comment]
Ah that's no good :(
I've got a theme in soft reject at the moment so I'll have to fix that too.

Thanks for the heads up :+1:

**Comment by pe6o** [comment]
So what now? 

How the other themes (that doesn't use Unyson) proceed with demo installs?

**Comment by martinburdon** [comment]
I was wondering this too but for users of Unyson.

@duongancol have you sorted your demo content issue out and resubmitted and did you just host the downloads on your server and add a link to them for your customers?

**Comment by duongancol** [comment]
Not resubmit yet, because I intend to change to Backup ver 2

**Comment by moldcraft** [comment]
[Backups (v2)](https://github.com/ThemeFuse/Unyson-Backups-Extension) is finished!

It will be listed in Unyson Extensions in next plugin release.

You can install the latest Unyson dev version from github manually, and install the 'Backup && Content Install' extension from Unyson page.

We will update the docs soon.

**Note:** Extension name is `backups` (with `s`) not `backup`. Make sure you'll add the correct name in theme manifest.php in supported extensions list.

#### How to create Demo Content Installs that are downloaded from your server

1. Copy/Create this [`index.php`](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/download/type/piecemeal/server/index.php) on your server.
2. In the same directory copy/create [`config.php`](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/download/type/piecemeal/server/config.php)
3. Create **Content Backup**
4. Upload the content backup zip to your server
5. In `config.php` in `$cfg['files']` add:

    ```php
    'your-demo-id' => '/path/to/content-backup.zip'
    ```

6. Register the demo(s) from your theme. Add in [`{theme}/inc/hooks.php`](https://github.com/ThemeFuse/Theme-Includes):

    ```php
    /**
     * @param FW_Ext_Backups_Demo[] $demos
     * @return FW_Ext_Backups_Demo[]
     */
    function _filter_theme_fw_ext_backups_demos($demos) {
    	$demos_array = array(
    		'your-demo-id' => array(
    			'title' => __('Demo Title', 'fw'),
    			'screenshot' => 'https://your-site.com/.../screnshot.png',
    			'preview_link' => 'https://your-site.com/demo/your-demo-id',
    		),
    		// ...
    	);
    	
    	// url to `index.php` from step 1.
    	$download_url = 'https://your-site.com/path/to/download-script/';
    
    	foreach ($demos_array as $id => $data) {
    		$demo = new FW_Ext_Backups_Demo($id, 'piecemeal', array(
    			'url' => $download_url,
    			'file_id' => $id,
    		));
    		$demo->set_title($data['title']);
    		$demo->set_screenshot($data['screenshot']);
    		$demo->set_preview_link($data['preview_link']);
    
    		$demos[ $demo->get_id() ] = $demo;
    
    		unset($demo);
    	}
    
    	return $demos;
    }
    add_filter('fw:ext:backups-demo:demos', '_filter_theme_fw_ext_backups_demos');
    ```

7. Refresh the admin page. Open menu `Tools > Demo Content Install`

**Comment by c0sm1n87** [comment]
Thanks @moldcraft this is actually pretty awesome :+1:

**Comment by martinburdon** [comment]
Just had a go of this, absolutely amazing - pain free and no issues whatsoever using the above instructions.

Well done and thank you @moldcraft + anyone else involved :clap: :clap: 

Keep up the great work :+1:

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/extension/backups/index.html

*You can improve the docs by contributing with pull requests https://github.com/ThemeFuse/Unyson-Documentation/blob/master/extension/backups/index.rst*

**Comment by c0sm1n87** [comment]
Hello,

I've been testing the backups extensions and for some reason I can't get it to work on multisite, generating an error of this kind: 

Failed insert row from line 160

Note that this happens only on a network and not if I use it on a regular site

**Comment by moldcraft** [comment]
Please check you apache error log for mysql error and post it here. Also please paste here the line 160 from you backup database.json.txt

**Comment by c0sm1n87** [comment]
I checked the line myself but couldnt make sense why it s not working. I ll post them as soon as i get home :) (about an hour)

**Comment by c0sm1n87** [comment]
{"type":"row","data":{"table":"architectureoptions","row":{"option_id":"442","option_name":"_transient_timeout_feed_d117b5738fbd35bd8c0391cda1f2b5d9","option_value":"1447538539","autoload":"no"}}}

This is the 160th line from the .txt file. however I don't have the error log yet. I mailed the guys from hosting for this and I'll get back ASAP

**Comment by moldcraft** [comment]
Are you doing full backup restore?

**Comment by c0sm1n87** [comment]
Hello @moldcraft 

No, it's not a full backup restore it's content backup only

**Comment by moldcraft** [comment]
@c0sm1n87 just to be sure: are you using the extension version installed from Unyson page, or a version from one of the download links I posted here?

I can remember for sure, and I can't test that at the moment, but I think I made on database export/import the option names that start with _transient_ to be skipped

**Comment by c0sm1n87** [comment]
@moldcraft I downloaded the latest version, posted here. this is taken from manifest.php file:

$manifest = array();

$manifest['name']        = __( 'Backup & Demo Content', 'fw' );
$manifest['description'] = __(
	'This extension lets you create an automated backup schedule,'
	.' import demo content or even create a demo content archive for migration purposes.',
	'fw'
);
$manifest['version'] = '2.0.0';
$manifest['display'] = true;
$manifest['standalone'] = true;
$manifest['requirements'] = array(
	'framework' => array(
		'min_version' => '2.4.10',
	),
);

$manifest['github_update'] = 'ThemeFuse/Unyson-Backups-Extension';

**Comment by c0sm1n87** [comment]
@moldcraft  if you want, I can create a FTP account for you, let me know :)

**Comment by moldcraft** [comment]
Yes, please. Send the details to `moldcraft[at]email.com`

**Comment by c0sm1n87** [comment]
@moldcraft i emailed you the details

**Comment by moldcraft** [comment]
1. Your demo install, in database.json.txt contains

    ```json
    {"type":"table","data":{"name":"architectureoptions","opts":...}
    ```

    but also contains the correct table

    ```json
    {"type":"table","data":{"name":"options","opts":...}
    ```

    Is `architectureoptions` a valid/used table on your wordpress installation (where you made Content Backup) ?

2. The line number was wrong. In code, it starts with `0`, but in errors it must be displayed +1. I fixed that.

3. Line 161 contains a row that is big. The result sql length is 

    ```php
    strlen($sql) == 213900
    ```

    Here is the sql http://pastebin.com/1ET21zwL

    I tried to execute it, to see some errors on the page, with this script

    ```php
	<?php

	ini_set('display_errors', 1);
	ini_set('display_startup_errors', 1);
	error_reporting(E_ALL);

	global $wpdb;

	$sql = file_get_contents(dirname(__FILE__). '/line-161.sql.txt');

	fw_print(strlen($sql));

	$wpdb->show_errors = true;

	$wpdb->query($sql);

	fw_print($wpdb->last_error);
    ```

    but nothing shows up.

    Even `fw_print($sql);` fails to display the sql, because it is a very big string.

So the solution would be to exclude the tables which name starts with `architecture`.

P.S. For `options` table, on db export, transient options are skipped https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/a7a9fe08a8db76bf30297ccda54b67ec9852ce19/hooks.php#L12-L13

## Very important!

A bug [was fixed](https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/36d2a7b18e9aa6fde850ef16ec7ad86bda9b6d51) that exported the tables `users` and `usermeta` on Content Backup (in `database.json.txt`)

Please reInstall the "Backup & Demo Content" extension from Unyson page (delete and download/install it back) and create again you Demo Installs (if you already created and prepared them for production) or open the file `database.json.txt` in zip, and remove everything related to `users` and `usermeta`

**Comment by c0sm1n87** [comment]
Hello,

I will delete the backups folder and install the one that is available on git at this current moment. Regarding your question. I have a single database for the demos (where I keep them, that have different prefixes), is there any chance that the create demo functionality copies the tables regardless of their table prefix? I will try now and let you know.

Regards!

**Comment by moldcraft** [comment]
The code that decides which tables to export is [this](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/a7a9fe08a8db76bf30297ccda54b67ec9852ce19/includes/module/tasks/type/class-fw-ext-backups-task-type-db-export.php#L271) (of course it uses `$wpdb->prefix`)

**Comment by c0sm1n87** [comment]
@moldcraft yes, it seems that is my fault. I have logged on phpmyadmin to check the tables and it seems that the prefix does not have _ sign after it (my error when creating them).

I will fix manually the tables and let you know.

**Comment by moldcraft** [comment]
Please open phpMyAdmin and delete wp option `fw:ext:backups:log`, try again and tell if it works.

P.S. I did some debug and in that option was saved a very large string, I think it's the same problem as described above.

**Comment by c0sm1n87** [comment]
@moldcraft I removed that particular row in the database, and created a new content demo and the same error occurs. Also, note that I checked the txt file and that particular option could not be found.

also, as far as I can see, this option also holds my credentials : fw_ext_settings_options:mailer and is not skipped.

On the site I provided credentials, I tried creating a full backup but it seems it's not working (i had no problem with this last night when I created a full backup before I tried the content install). It keeps zipping the archive (15 minutes I think it took) and afterwards it does not create the option to delete/download - it simply does nothing.

**Comment by moldcraft** [comment]
Delete it from the site where you try to install the demo content, not from the site where you do the export.

Thank you for reporting `fw_ext_settings_options:mailer`, [fixed](https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/2bab15ac4e3285fbead21fd94ba916c293f52fa2) (reinstall extension)

> On the site I provided credentials, I tried creating a full backup but it seems it's not working

Without access to apache error log is very hard to find the problem. If you can give me error log access, I will login on your site and debug the problem.

**Comment by moldcraft** [comment]
P.S. Please do not edit comments with new info, I will not receive notifications about that (and will not see the edits), I receive notifications only for new comments.

**Comment by c0sm1n87** [comment]
@moldcraft i`m trying to get the error log myself, but it seems that there is some problem from the hosting part (the error log that should be available in the cPanel is not being generated - they said that they are looking into this issue). I will reinstall backups and let you know about how is going.

**Comment by c0sm1n87** [comment]
I deleted that particular row from the target database and it worked (with a content created with the new backups version). However, I can see that some images were not imported (this is not a big issue at the current moment due to the fact that it's maybe because of their size - which will not be these in production). 

Another issue I can see that the user/pass can be found in a couple other places, somewhere even here:

{"type":"row","data":{"table":"options","row":{"option_id":"370","option_name":"fw:ext:cf:fd:fff8d4c2da52f8fe0c8b1ff3951115dc",..

{"type":"row","data":{"table":"postmeta","row":{"meta_id":"344","post_id":"134","meta_key":"fw_options","....

**Comment by moldcraft** [comment]
> Another issue I can see that the user/pass can be found in a couple other places

Thank you for reporting. We will fix that soon

**Comment by c0sm1n87** [comment]
thank you @moldcraft :) I appreciate your help

**Comment by maiakhoa** [comment]
It works great. @moldcraft when will we have the next version of Unyson?

**Comment by moldcraft** [comment]
When all bugs in Backups will be fixed.

Currently I am working on a problem: In some demos we have very big pages, and on demo import mysql throws errors because of very big `INSERT` sql.

**Comment by maiakhoa** [comment]
@moldcraft thanks for info.

**Comment by moldcraft** [comment]
@maiakhoa [fixed](https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/53fe53cd33fc839dd5cc4b49f5408e786a2165b0)

To install the latest version of Backups extension: from admin Unsyon page, delete the extension and install it back (the latest version will be downloaded)

**Comment by moldcraft** [comment]
> @c0sm1n87 Another issue I can see that the user/pass can be found in a couple other places

Sorry, at the moment it's not possible to fix that. Mailer settings are saved in each contact form you add in builder, and also it is saved in a separated wp option. I will exclude that wp option, but I can't exclude data saved in each post meta (each contact form shortcode)

The next task that I will start working on is https://github.com/ThemeFuse/Unyson/issues/838 it will make possible mailer settings to be saved only in one wp option and not in each contact form options.

So current solution is only to: Before creating Demo Content, update all your contact forms and remove mailer settings or add fake settings. (I will add this info in docs)

**Comment by c0sm1n87** [comment]
@moldcraft thanks, but I don t think it s from the contact form shortcode ( because I have only one in the whole demo ). I think it s from the comment form and I have no idea how you could skip those ( maybe str replace it when creating the archive - most "shitty" solution i guess )

**Comment by moldcraft** [comment]
> from the comment form

Which private data contains comment form? Also, where I can find it? Is it something made custom in your theme?

**Comment by c0sm1n87** [comment]
good morning,

@moldcraft, you said that : " Mailer settings are saved in each contact form you add in builder " ( I don't know how to quote ), but the thing is, I have only one Contact Form created and is not in a regular blog post. However, I can clearly see that all my blog posts have the mailer settings "available" so to speak. This is what lead me to believe that maybe the mailer settings are saved due to the comment form.

**Comment by moldcraft** [comment]
Ok, thanks. I'll inspect

**Comment by moldcraft** [comment]
@c0sm1n87 Can you send me your `database.json.txt` (zipped) to `moldcraft[at]email.com` so I can understand better where those private data come from?

**Comment by c0sm1n87** [comment]
@moldcraft email sent

**Comment by moldcraft** [comment]
* Contact Form shortcode options are copied to separate wp option [here](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/aad168755b2215bc6357728f6845588a01d52852/extensions/contact-forms/shortcodes/contact-form/class-fw-shortcode-contact-form.php#L44)
* I added in docs [info about contact form mailer settings](http://manual.unyson.io/en/latest/extension/backups/index.html#create-demos)
* Thank you for email. I searched the word `c0sm1n87` and it appears only in contact form settings.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/150

![](http://www.sherv.net/cm/emoticons/rage/freddie-mercury-rage-smiley-emoticon.png)

**Comment by maiakhoa** [comment]
@moldcraft great :clap: :clap: :clap: :clap:

**Comment by c0sm1n87** [comment]
@moldcraft thank you!

**Comment by moldcraft** [comment]
A [fix](https://github.com/ThemeFuse/Unyson-Backups-Extension/compare/6fbce1322c6178e335760208566caef5ede12555...e84912c9fcb2b8c6f744c5bf0a2d11d3bcd1225f) was added that includes the uploads dir url in db export, that is used to replace old links on db restore. 

This problem happens on multisite when 

1. The url of the site where demo install was created is `http://demo-site.com`
2. Demo install links are `http://demo-site.com/wp-content/uploads/2015/11/image.jpg`
3. On multisite, current site uploads dir url is 

    `http://current-site.com/wp-content/uploads/sites/2/2015/11/image.jpg`

    Note the `/sites/2` directory

4. The imported url, after replacing just the domain, becomes

    `http://current-site.com/wp-content/uploads/2015/11/image.jpg`

    which is wrong and images are not displayed

So to avoid this problem on clients with multisite, please reinstall the Backup & Demo Content extension from Unyson page (delete and install back) and create your content installs again.

**Comment by c0sm1n87** [comment]
@moldcraft thanks again :d
