### ISSUE TITLE
What baseline did you use for Unycon ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#883]
When you created the Unycon font , what baseline height did you use? 
I am having bit trouble aligning the fonts http://stackoverflow.com/questions/32781414/what-is-the-baseline-font-height-of-fontawesome-font/32781641#32781641

**Comment by moldcraft** [comment]
Can you give me a [html example](http://sourcebox.io/4b7e96ec0f906b9e7e249fa776800b62/html) with the problem?

**Comment by danyj** [comment]
Issue is not in  html , html for icon is same only class changes from fa  to thzicon or in your case unycon .  , problem is with baseline height when font is created , 
icomoon uses 6.25% .  fontawesome around  14%  so I wanted to see what yours was when you were making the icons.

You see instead of loading 10 different CSS files for icons , I included 

Unycon
FontAwesome
icomoon 

in to one file and need to adjust the baseline so that they all fall on same line 
http://prntscr.com/8kb8v4
for now I left it at 14  and they are fairly all in line but just wanted to know what you guys used in Unycon

**Comment by danyj** [comment]
You used 6.25  according to this 
http://stackoverflow.com/questions/32781414/what-is-the-baseline-font-height-of-fontawesome-font/32781641?noredirect=1#comment53406200_32781641
