### ISSUE TITLE
Try to install extensions and receive an error

### ISSUE THREAD

**Issue by LevyMarketing** [ThemeFuse/Unyson#884]
I have a custom built theme already, but I wanted to use Unyson to build new pages. Well, every time I try to install an extension I receive an error message. Is Unyson not compatible with custom themes?

**Comment by danyj** [comment]
Be precise please. What is the error? Unsyon is compatible with any theme and does not depend on any theme.

**Comment by LevyMarketing** [comment]
There is simply a pop up that only says Error.

**Comment by danyj** [comment]
local or live server ? I just ran a clean install on local server and had no issues. Deleted and added Events Extension. Only thing I can think off could be folder permissions since the extension is downloaded first than installed.

**Comment by moldcraft** [comment]
One this page please

```
http://YOUR_SITE/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=page-builder
```

and try to install the extension. Maybe there will be a more detailed error message.

**Comment by ryangreg55** [comment]
I am having this issue to, I am using Theme (Concept - Codepark) and it recommends me installing Page Builder and Portfolio however when I click install, it says "This page says.... OK" and nothing happens. 

Is there a way to manually install these extensions via FTP and is so how? 

Kind regards,
Ryan

**Comment by moldcraft** [comment]
Can you give us a screenshot with the error?

**Comment by ryangreg55** [comment]
![image](https://cloud.githubusercontent.com/assets/14845109/10124949/6fb5f920-655b-11e5-9bd8-da7cf0ea5b57.png)

Any way of manually installing instead?

**Comment by moldcraft** [comment]
Have you tried.https://github.com/ThemeFuse/Unyson/issues/884#issuecomment-143224441 ?

You can install manually but it's hard

**Comment by ryangreg55** [comment]
Hi Moldcraft

Thank you for your reply, I generally think the problem is that my hosting does not aloe recurring servers accessing the extensions and will not allow this. I spoke to my technical team and they said that I could install these plugins via FTP and they would work. 

Would changing hosting providers allow me just click the install plugin and it will work or is their a guide to adding these extensions via FTP? 

Really appreciate your response!

Kind regards,
Ryan

**Comment by moldcraft** [comment]
* You can change hosting provider
* You can ask current hosting provider to allow requests to http://github-api-cache.unyson.io/
* You can install all extensions locally, then upload the `wp-content/plugins/unyson/framework/extensions` directory via FTP

**Comment by LevyMarketing** [comment]
Thank you moldcraft, the site you sent worked for the page builder. When I tried to access the sliders though, it tells me that extension is unavailable for download. Why would that be?

**Comment by moldcraft** [comment]
Can you give the exact error message, maybe a screenshot?

**Comment by LevyMarketing** [comment]
![sliders error message](https://cloud.githubusercontent.com/assets/14837164/10374665/5ef6b6c8-6dc2-11e5-910c-b922547bb827.jpg)

**Comment by LevyMarketing** [comment]
When I try to download it from my Unyson dashboard, a message saying "Error" pops up. 

![image](https://cloud.githubusercontent.com/assets/14837164/10374697/8a9a4808-6dc2-11e5-8c60-e954a4f99cb9.png)

**Comment by moldcraft** [comment]
Please open the following url in browser

```
http://YOUR_SITE/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=slider
```

and try to install the extension. Maybe there will be a more detailed error message.

**Comment by LevyMarketing** [comment]
Ok, that worked! Thank you! Why is it that I can't download them from the main screen though?

**Comment by moldcraft** [comment]
I don't know. I will try to reproduce it.

Can you inspect the ajax response from developer tools `F12 -> Network`?

**Comment by mtlbigger** [comment]
hi i am getting following error while trying to download the extensions of UNYSON plugin.

Please help

![scrfeenshot error](https://cloud.githubusercontent.com/assets/15210166/10602153/3a67671e-7734-11e5-983a-1e354d1e65fa.jpg)

**Comment by moldcraft** [comment]
Please, add the following code in `{theme}/functions.php`

```php
add_action('fw_init', function(){
    fw_print(
        file_get_contents(
            'http://github-api-cache.unyson.io/repos/themefuse/unyson/releases'
        )
    );
});
```

and show us the output

**Comment by mtlbigger** [comment]
![image](https://cloud.githubusercontent.com/assets/15210166/10603002/766cb48a-7739-11e5-90e4-1ac3cb2e007b.png)

screen shot of error

**Comment by mtlbigger** [comment]
![image](https://cloud.githubusercontent.com/assets/15210166/10604081/b51b337c-773f-11e5-8419-05365bfc78a2.png)

**Comment by moldcraft** [comment]
That is not error. The server response seems is ok (json). Please scroll to the end, to see the json end to make sure it doesn't have anything appended (we had a case when a firewall soft added `<script>` at the end of json)

![](https://static.md/5d2c9e672ac16a3a80051e00322b659c.png)

**Comment by mtlbigger** [comment]
but still the problem is not resolved and i have to remove the code as wit the code i get the error in the theme.
Please with the solution.

**Comment by mtlbigger** [comment]
![image](https://cloud.githubusercontent.com/assets/15210166/10604759/53256cdc-7744-11e5-9a2c-d45bc3cfcafa.png)

it is showing as error in line 214

**Comment by moldcraft** [comment]
PLEASE DO https://github.com/ThemeFuse/Unyson/issues/884#issuecomment-149509351 AND GIVE US THE SCREENSHOT.

That is not error, it's a warning... of course that code will not fix the problem, it's just a debug to check if the response from our server has corrent format.

**Comment by mtlbigger** [comment]
after adding the below mentioned code in theme(function.php):
add_action('fw_init', function(){
    fw_print(
        file_get_contents(
            'http://github-api-cache.unyson.io/repos/themefuse/unyson/releases'
        )
    );
});


i am still not able to install the extensions

![image](https://cloud.githubusercontent.com/assets/15210166/10605189/4442e91c-7747-11e5-8518-b199ca221369.png)

**Comment by moldcraft** [comment]
I told you, that code will not fix the problem.
Can you give us the screenshot?

**Comment by mtlbigger** [comment]
i gave you the screen shot , i gave you screen shot after i inserted the code also after inserting the code when i tried installing extensions, now which screen shot you require Please tell

**Comment by moldcraft** [comment]
You didn't gave me the screenshot I requested in https://github.com/ThemeFuse/Unyson/issues/884#issuecomment-149509351

**Comment by mtlbigger** [comment]
![image](https://cloud.githubusercontent.com/assets/15210166/10606267/5d44ba00-774f-11e5-935d-65d47b194b31.png)

Please confirm will this screenshot suffice the need

**Comment by moldcraft** [comment]
Yes, thank you.

The json response looks fine. Can you give me access to your site code so I can debug the problem? If Yes, send please the details to `moldcraft[at]email.com`

**Comment by mtlbigger** [comment]
i have mailed you the details at moldcraft@email.com

**Comment by moldcraft** [comment]
There is a problem with our host internet connection, it throws this error

```
WP_Error
(
    [errors] => array
    (
        [http_request_failed] => array
        (
            [0] => 'name lookup timed out'
        )
    )
    [error_data] => array()
)
```

**Comment by moldcraft** [comment]
Ask your host support to fix the problem.

**Comment by mtlbigger** [comment]
Hi you said there is a problem with your host connection and then you ask us to ask our host connection please assist 

![image](https://cloud.githubusercontent.com/assets/15210166/10607192/75c790b0-7755-11e5-9389-42ed08409f0e.png)

**Comment by moldcraft** [comment]
If that is your own VPS server, debug and find the problem. If you bought a hosting packed, contact the support to fix that problem.

**Comment by mtlbigger** [comment]
Hi I checked with my hosting support team there is problem with the server.
