### ISSUE TITLE
Adding code to a label in Theme Options

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson#885]
Hi,

I was trying to add Font Awesome icons to certain labels in the Theme Options page. 
Per example it'd be nice to display a Twitter-icon before a field where users can enter their Twitter-account.

I've been trying this for a while, but pure code gets converted to a string and I'm not able to break out if that conversion. Any idea's?

**Comment by moldcraft** [comment]
You can't add in labels raw html code.

**Comment by warudin** [comment]
So there's absolutely no way to achieve something like this?

![schermafdruk 2015-09-25 15 54 19](https://cloud.githubusercontent.com/assets/1815847/10102262/c182e30e-639d-11e5-8550-013a4e04cb0b.png)

**Comment by llemurya** [comment]
@warudin It is possible if you make your own option type, plese see our documentation how to make an [option type](http://manual.unyson.io/en/latest/options/create-option-type.html#content).

**Comment by danyj** [comment]
label[for=fw-option-facebook]:before{
		font-family:'FontAwesome';
		content: "\f09a";
		margin-right:10px;
	}


but that is stretch ,  I wonder why  option attr class is not applied to the container  but to the input only ,  if we can add class to option container than I know great way of doing this

**Comment by danyj** [comment]
http://prntscr.com/8kbjtn

**Comment by danyj** [comment]
If I could do this 

			'attr' => array(
				'title' => 'fa fa-camera-retro',
				'class' => 'label-icon'
			),


and that applied to the option label container  http://prntscr.com/8kbki3

than I can say 

	 label.label-icon{
		font-family:'FontAwesome';
		content: attr(data-title);
		margin-right:10px;
	}

**Comment by warudin** [comment]
I thought about injecting an extra class as well. But indeed, this extra class will be applied to the input, instead of the top-level div.

**Comment by danyj** [comment]
@moldcraft   can you give us  this attr param or something similar so that we can manipulate the anything that is inside a given option container


         'attr' => array(
            'container-class' => 'label-icon'
        ),

**Comment by moldcraft** [comment]
Sorry, I need urgently to inspect and fix the Backup extension. No more new features for now.

**Comment by danyj** [comment]
not a prob mate we will look for solution

**Comment by warudin** [comment]
You don't need to add it right away but it'd be cool to get it in a future release. :+1:

**Comment by danyj** [comment]
im on this submitting commit in a few, 

adding these 2  in the option will output desired class


			'container-class' => 'custom-container',
			'label-class' =>'custom-label',


http://prntscr.com/8kbvdk 
http://prntscr.com/8kbvk2

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/pull/886

**Comment by danyj** [comment]
@warudin  I think you were after this one rather than anything else
https://github.com/ThemeFuse/Unyson/pull/886#issuecomment-143249342

**Comment by warudin** [comment]
Looks awesome. :+1:

**Comment by danyj** [comment]
@warudin  don't get to excited , not accepted yet , team  might have something else in mind I merely just save them some time.

**Comment by warudin** [comment]
I know, but I'm grateful anyway. 😉

**Comment by moldcraft** [comment]
@warudin Please, at the moment, make your options without icons near labels. When we will make that possible, we will let you know.
