### ISSUE TITLE
Specific IP address 

### ISSUE THREAD

**Issue by ryangreg55** [ThemeFuse/Unyson#887]
Hi 

I am having big issues installing your plugin and extensions needed for my wordpress theme. My hosting providers have asked:
Please contact the plugin developer and ask them about the specific IP address of the plugin's server to which the connections should be allowed so that we could activate the plugin.

PLease can you specify this information so I can use these plugin with my Concept Codepark Theme (Wordpress site)

Kind regards,
Ryan

**Comment by moldcraft** [comment]
http://www.dnswatch.info/dns/dnslookup?la=en&host=github-api-cache.unyson.io&type=A&submit=Resolve
