### ISSUE TITLE
Trouble registering script and calling it from option

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#889]
I am trying to globally register icon css file   , in hooks.php I have 

	function _thz_register_scripts(){
		
		wp_register_style(
			'thzicons',
			thz_theme_uri(). '/css/fonts/thzicons/style.css'
		);	
		
	}
	add_action('wp_enqueue_scripts', '_thz_register_scripts');
	add_action('admin_enqueue_scripts', '_thz_register_scripts');

and than in my option class ,  or in theme/static.php I call 

    wp_enqueue_style('thzicons');

that does not work   for option since it seems like 

    fw_option_types_init

fires before 

    admin_enqueue_scripts

do I have to do 

	add_action('fw_option_types_init', '_thz_register_scripts');

as well so that I can use just css handle to enque it in option class?

**Comment by moldcraft** [comment]
Try

```php
add_action('wp_enqueue_scripts', '_thz_register_scripts', 9);
add_action('admin_enqueue_scripts', '_thz_register_scripts', 9);
```

**Comment by danyj** [comment]
@moldcraft , no but 8 works , what is the safe side to make sure it loads always ?  1 ?

**Comment by moldcraft** [comment]
I don't know, 8-

Usually I set 9 for something to be loaded before the actions that were added without any priority specified (default 10). I don't set 8- without reason.

**Comment by danyj** [comment]
ok but than something makes no sense , 

in option-types.php I have this 


    add_action('fw_option_types_init', '_action_theme_include_custom_option_types');

no priority , so how is that than loading before  this 

    add_action('admin_enqueue_scripts', '_thz_register_scripts', 9);

unless  there is somewhere priority 9 set in unyson fw_option_types_init

**Comment by danyj** [comment]
ok the 8 worked in theme options panel but in builder it does not work , not even 1 , so I must use 

    add_action('fw_option_types_init', '_thz_register_scripts');

I am just trying to understand why , that's all. 

so again to sum up ,  
I want to register style globally and than call it via handle from the custom theme option  


in   theme option _enqueue_static  I have 

		wp_enqueue_style('fw-font-awesome');
		wp_enqueue_style('thzicons');

fa works of the bet ,   thzicons wp_register_script must be on  fw_option_types_init

**Comment by moldcraft** [comment]
`'fw_option_types_init'` is called when someone is calling first time 

```
fw()->backend->option_type('WHATEVER_TYPE')
```

it can be called too late, in content, when `admin_enqueue_scripts` already happened.

It's a bad action to register scripts.

**Comment by danyj** [comment]
ok bud I think we are talking by each other here , look here 

https://github.com/ThemeFuse/Unyson/blob/master/framework/core/components/backend.php#L393-L398


you globally registered fa so that we can use 

    wp_enqueue_style('fw-font-awesome');

that is exactly what I am trying to do but it does not work in custom option types  properly


I am not trying to reinvent anything , I am looking for the right way but for some reason only one that works in theme options, builder  and theme settings is fw_option_types_init, I am not saying that is right and if I thought it was I would not be asking for the right way. Seems bad and probably is bad , but cant find the right one. 

Try it yourself , add custom css handle from theme hooks or functions and call it in custom option , it wont work unless you do some workarounds.

**Comment by moldcraft** [comment]
We register that handle on every refresh [here](https://github.com/ThemeFuse/Unyson/blob/156f8c389689d91285db95c81c433964c17e6beb/framework/core/components/backend.php#L1059) on [this action](https://github.com/ThemeFuse/Unyson/blob/156f8c389689d91285db95c81c433964c17e6beb/framework/core/components/backend.php#L160)

You are registering your handle from option-type class? If yes, don't do that, register it in a script that is executed on every refresh (option types are executed/initialized only when called/requested), for e.g. register in `hooks.php`

```
add_action('admin_enqueue_scripts', array($this, '_thz_register_scripts'), 9);
```

**Comment by danyj** [comment]
I am in hooks bud , that is what I am trying to tell you  the whole time ,   it does not work 


this is in hooks.php

    add_action('admin_enqueue_scripts', array($this, '_thz_register_scripts'), 9);


9 does not work 

this  works in theme options only 


add_action('admin_enqueue_scripts', array($this, '_thz_register_scripts'), 8);

none of priorities work  in builder ,   


I am registering the stile in HOOKS.PHP  ,  


I am call the handle 

    wp_enqueue_style('thzicons');

in   option class 


and it does not work

**Comment by moldcraft** [comment]
Can you do this:

* Add `fw_print('test 1');` in `_thz_register_scripts` function
* Add `fw_print('test 2');` in option type after you call `wp_enqueue_style('thzicons');`

ad see which is executed first?

Also in which method in option type you call `wp_enqueue_style('thzicons');`, in render or in enqueue_static ?

**Comment by danyj** [comment]
ok bud I am repeating same thing over and over,  here images ,  custom option type 
![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/10119494/c4eb2c68-6497-11e5-823d-f7125c06132d.jpg)


hooks.php


![screenshot_6](https://cloud.githubusercontent.com/assets/2340172/10119499/e8e57164-6497-11e5-8ba6-db4ffd063349.jpg)


getting  fw_print test in a sec

**Comment by danyj** [comment]
http://prntscr.com/8ksgo4

test 2 executed ,  but no style 

http://prntscr.com/8ksgzl

cant find hadnle

**Comment by moldcraft** [comment]
One moment, I'll try to reproduce this

**Comment by danyj** [comment]
here screen from  option-types.php 


no priority used in those 2 

![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/10119557/97540f5c-6499-11e5-8764-d316cc71eadb.jpg)

**Comment by moldcraft** [comment]
Download latest dev version and test please.

**Comment by moldcraft** [comment]
Why this happened: On post page, [this code](https://github.com/ThemeFuse/Unyson/blob/868316f189d7b6bbcbe6eaada47151dd2dd55560/framework/core/components/backend.php#L687) is executed earlier than `admin_enqueue_scripts`, so enqueue was called too early.

Thank you very much for reporting this. [This](https://github.com/ThemeFuse/Unyson/commit/6adaf5dcf55baac3f88e98aaf45f2def7b56781d) is a good improvement.

**Comment by moldcraft** [comment]
todo: remove [this](https://github.com/ThemeFuse/Unyson/blob/f206b1247c4efbcca8e9b946da48ac00ce05256b/framework/core/extends/class-fw-container-type.php#L77) (because it's weird) better just don't enqeue static for options rendered too early. Usually that will happen only with options used in `add_meta_box()`, but those options are enqueued [here](https://github.com/ThemeFuse/Unyson/blob/f206b1247c4efbcca8e9b946da48ac00ce05256b/framework/core/components/backend.php#L1054-L1056). So there is no sense for that fancy/weird pending enqueue functionality (also if your post options array will be big, it will store in pending all that array and will cause php memory consumption)

**Comment by moldcraft** [comment]
[Done](https://github.com/ThemeFuse/Unyson/commit/5777e3a853d2e4231df7c5f7078434f69c636333)

Please test

**Comment by danyj** [comment]
There you go !  And I thought I am going crazy here. Should have take those pics to begin with., 

This works now as intended without priority 

	add_action('wp_enqueue_scripts', '_thz_register_scripts');
	add_action('admin_enqueue_scripts', '_thz_register_scripts');


will test more to make sure everything else works also but for now seems perfect

**Comment by danyj** [comment]
Did more tests, heads up , any option that is depending on other option must load dependencies ,  I had image option loading in another and  forgot to include its js and css , after this fix  I was forced to add 

	fw()->backend->option_type('thz-image')->enqueue_static();

which is the right way anyhow. 

so if anyone starts complaining about something like this , remind them of this change. in prev version looks like it was not looking for it or was loading them prematurely.  my option was built about 2 months ago and just now I saw this.
