### ISSUE TITLE
Contact Form custom CSS

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#891]
Hello!

I tried to replace default CSS files for Contact Forms (from a page builder) shortcode, and it seems it is not loaded at all, default CSS file loads all the time. 

I tried to overwrite it regarding these instructions http://manual.unyson.io/en/latest/extension/forms/#customize-views

is it a bug, or it is not possible to override these default styles?

Thank you!

**Comment by danyj** [comment]
did you copy static.php to your override and  changed the  link for it inside? 
https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/static.php#L6

if you did and is not working might be connected to  #890

**Comment by danyj** [comment]
Just tested override works , 
copy https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/static.php#L6

to 

framework/extensions/forms/

change that line to your CSS file link

**Comment by WPJobs** [comment]
Thank you for a quick reply! I thought that enough to replace CSS file, as a template file, thank you again!

**Comment by danyj** [comment]
no , seems like it is not reading if the CSS ifle is on override or not, not sure if it should ( unnecessary check since we are overriding ourselfs )  but since it is an override you can change that link to anything you need.
