### ISSUE TITLE
FontAwesome CSS loading without being enqued

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#892]
Blank page , nothing on it 
in static commented out fa handle ,  nowhere in theme is the handle used
![uvjd9jx](https://cloud.githubusercontent.com/assets/2340172/10122474/271eaa3e-651c-11e5-8ae7-a6ad52a1c9e2.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/2340172/10122482/568c8688-651c-11e5-8870-794989ec64b8.jpg)

font awesome still loading 
![screenshot_8](https://cloud.githubusercontent.com/assets/2340172/10122463/c783ed82-651b-11e5-9778-2a2c79625979.jpg)

![screenshot_9](https://cloud.githubusercontent.com/assets/2340172/10122466/e49ae376-651b-11e5-8de5-064c34ef7d0c.jpg)

seems like this is also connected to #890

**Comment by moldcraft** [comment]
try to remove it from dependencies from `.../shortcodes/nodification/static.php`

**Comment by danyj** [comment]
That whole chunk is commented out 
![screenshot_11](https://cloud.githubusercontent.com/assets/2340172/10122795/9ceb1ec0-6524-11e5-8579-afeeedad137d.jpg)

and beside that page is blank , no builder nothing

**Comment by danyj** [comment]
Nothing on this?

**Comment by moldcraft** [comment]
Sorry, no.

I will take a look later

**Comment by danyj** [comment]
I think those are connected #890

**Comment by danyj** [comment]
This is what loads FW 

https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/static.php
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/static.php

static.php override fixes this

**Comment by andreiglingeanu** [comment]
Try to think about something like [this](https://github.com/ThemeFuse/Unyson/blob/v2.6.2/framework/includes/option-types/icon-v2/includes/class-fw-icon-v2-packs-loader.php#L49-L55) in your code. You'll need the `icon-v2` to load your icon packs anyway, if you're gonna use it. Can't think of a better way to get rid of the FA which Unyson forces.
