### ISSUE TITLE
Can't add additional icons

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#893]
Hello,

I am trying to add some extra icons to font awesome library, but it just doesn't work.

Can you tell me where is the issue?
I can create and use new icon set, but adding anything to font-awesome set doesn't work.

```
function _filter_theme_new_icon_set($sets) {
    $groups = array(
        'test' => 'Test'
    );

    $icons = array(
        'glyphicon glyphicon-euro' => array('group' => 'test'),
        'glyphicon glyphicon-bitcoin' => array('group' => 'test'),
        'glyphicon glyphicon-yen' => array('group' => 'test'),
        'glyphicon glyphicon-ruble' => array('group' => 'test'),
        'glyphicon glyphicon-menu-left' => array('group' => 'test'),
        'glyphicon glyphicon-menu-right' => array('group' => 'test'),
        'glyphicon glyphicon-menu-down' => array('group' => 'test'),
        'glyphicon glyphicon-menu-up' => array('group' => 'test'),
    );

    $sets['font-awesome']['groups'] = array_merge( $sets['font-awesome']['groups'], $groups );
    $sets['font-awesome']['icons'] = array_merge( $sets['font-awesome']['icons'], $icons );

    return $sets;
}
add_filter('fw_option_type_icon_sets', '_filter_theme_new_icon_set');
```

I tried https://github.com/ThemeFuse/Unyson/issues/371#issuecomment-82525378 code snippets and suggestions, but still there is an issue.

**Comment by moldcraft** [comment]
> doesn't work

More details?

**Comment by pear1** [comment]
```
			'icon'    => array(
				'type'  => 'icon',
				'label' => __('Select Icon', 'fw'),
			),
```
```
			'icon'    => array(
				'type'  => 'icon',
				'label' => __('Select Icon', 'fw'),
				'set' => 'font-awesome',
			),
```


Everything is default, no added groups or icons.

**Comment by moldcraft** [comment]
You [can't overwrite default set](https://github.com/ThemeFuse/Unyson/blob/5777e3a853d2e4231df7c5f7078434f69c636333/framework/includes/option-types/icon/class-fw-option-type-icon.php#L136-L137) because it is used in many places, and changing it for everyone/everywhere will confuse some people (also they for e.g. will select a glyphicon in MegaMenu but it is not supported there).

So create a new set (a copy of font-awesome).

**Comment by pear1** [comment]
Well I will overwrite it in any possible place, therefore changing it globally would be much better solution, because if theme supports additional icon packs, then that should work in any icon option.

Anyway thank you for reply.
