### ISSUE TITLE
Multisite domain mapping custom field URLS not corrected

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#896]
Hi!

On a clients website, when using the WordPress multisite, the urls of the mapped domains are not changes correctly for the unyson options.

See the source code of http://byebra.be/, when you search for byebra.com you'll see that only the custom fields, like the slider and the 3 main blocks beneath the products are linked to byebra.com/byebra-be.

How can i solve this?

Thanks!

**Comment by moldcraft** [comment]
Hello,

How to reproduce this (the steps) ?

**Comment by nickkuijpers** [comment]
Hi,

Enable WordPress multi-site, install a domain mapping plugin and map a domain to that certain multisite sub-site. When you've mapped a domain with the plugin, you see the error.

**Comment by danyj** [comment]
@nickkuijpers   side question if I may , nice speed on that site , did you do anything to improve it or the theme is just light and server fast? I mean 18 stylesheets , impresive

**Comment by moldcraft** [comment]
Have you set [here](https://static.md/20f853a939f01c735ea615b52c212450.png) the new domain?

**Comment by nickkuijpers** [comment]
@moldcraft no, i've installed https://wordpress.org/plugins/wordpress-mu-domain-mapping/ in the multi-site and i've added a domain in there. Here is some info about multisites http://codex.wordpress.org/Create_A_Network

**Comment by nickkuijpers** [comment]
@danyj Haha thanks :) Its nothing yet, wait for it in like 1.5 weeks. I'm writing a plugin that makes it 100% or like 90+ % in Google Page Insight. Combining all stylesheets, adding JS to the footer and some .htaccess changes. Image optimizing with Kraken.io helps alot tho! Furtheron there is no caching active yet, so when i active this the speed will be like this ( my selling website ) : 

http://www.googlewebsite.nl/
https://developers.google.com/speed/pagespeed/insights/?url=http://www.googlewebsite.nl/
http://tools.pingdom.com/fpt/#!/b1FL8k/http://www.googlewebsite.nl/

Some sick speed aye? xD

**Comment by moldcraft** [comment]
Try to set the new domain in those fields. If that will help, then that is the problem. If not, then in database  were saved links with old domain and you will have to update them manually in all database tables (using some tool)

**Comment by nickkuijpers** [comment]
That is not possible with a WordPress multi-site.

**Comment by nickkuijpers** [comment]
I've tryed that but does not work

**Comment by nickkuijpers** [comment]
http://byebra.cz/wp-content/uploads/sites/6/2015/06/3m-KVALITA.png
http://byebra.com/byebra-cz/wp-content/uploads/sites/6/2015/06/3m-KVALITA.png

Loop, in de media lib its okay, but in front end not. Its a media upload from unyson options

<img width="432" alt="schermafbeelding 2015-10-01 om 13 26 01" src="https://cloud.githubusercontent.com/assets/5340923/10219525/fc7c0020-683f-11e5-946c-075473ee0dc1.png">

**Comment by danyj** [comment]
@nickkuijpers  share some love brother :) since you are making it you might as well make unyson  compress extension

**Comment by nickkuijpers** [comment]
Oehh, tell me, whats that?

**Comment by nickkuijpers** [comment]
Moldcraft, i've solved it by manually str_replaceing the url but that isn't the way. Can you lead me to the code where u call up the bloginfo('wpurl');

**Comment by moldcraft** [comment]
* https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/includes/option-types/upload/class-fw-option-type-upload.php#L194-L198
* https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/2a51926f4ccf549f253df2b0726a422019581fa7/shortcodes/media-image/views/view.php#L17-L19

**Comment by nickkuijpers** [comment]
Thanks, i've replaced them manually. Custom options, the ones which uses the upload functionality and the attachments ID also have the problem so we need to solve it in the class-fp-option-type-upload.php.

**Comment by moldcraft** [comment]
If you'll find a solution, please make a pull request.
