### ISSUE TITLE
Is there fw()->extensions->get_options

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#898]
Is there anything like 

    fw()->theme->get_options

but for extensions folder ?

**Comment by moldcraft** [comment]
[Yes](https://github.com/ThemeFuse/Unyson/blob/5777e3a853d2e4231df7c5f7078434f69c636333/framework/core/extends/class-fw-extension.php#L324)

`fw_ext('EXTENSION_NAME')->get_options('...')` or inside extension class `$this->get_options('...')`

**Comment by danyj** [comment]
thank you!

**Comment by danyj** [comment]
this one does not work 

	fw_ext('shortcodes')->get_options('shortcodes/icon-box/styles')

	fw_ext('shortcodes')->get_options('icon-box/styles')


I have 1 option inside the styles.php file and is not laoding

if I move the file to theme/options and use 

    fw()->theme->get_options('styles')

it loads

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/5777e3a853d2e4231df7c5f7078434f69c636333/framework/core/extends/class-fw-extension.php#L326

`EXTENSION_DIR/options/icon-box/styles`

**Comment by danyj** [comment]
missed that , sorry, thnx

**Comment by danyj** [comment]
@moldcraft , I am trying to make this work for the slider extension ,  

example , here  https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-parent/framework-customizations/extensions/media/extensions/slider/extensions/bx-slider/options

I have set of options in file name called styling.php

and here 
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/media/extensions/slider/extensions/bx-slider/options/options.php


inside my popup option  I am trying to do 

    fw_ext('slider')->get_options('styling')

but it does not work

**Comment by moldcraft** [comment]
Maybe

```
fw_ext('bx-slider')->get_options('styling')
```

?

**Comment by danyj** [comment]
@moldcraft , thats the one!, thnx!
