### ISSUE TITLE
Custom Extensions

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson#90]
Hi,

thanks for the awesome work.

i have some questions regarding custom extensions. For my theme, i am using custom post type Slider. So before plugin was out, i used to extend FW_Extension,  placed all my code under framework-customizations/extensions, and everything was working fine. 

After plugin activation, it is still there, but not working anymore.  Do we need to to workaround similar to shortcodes ?

thanks.

**Comment by thednp** [comment]
@pudeco do you happen to have your extension in a plugin or still in the theme `framework_customization` folders?
