### ISSUE TITLE
How to trigger switch option change via jQuery

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#900]
I found a solution for this  #899  via  multi-picker option data attributes and on change I run small js to set defaults per style,  can you please show me the proper way to trigger change on swith-option type , 

I tried 

    $('MYID').find('input').val($hovereffect).trigger('click');

but is not 100%

**Comment by moldcraft** [comment]
Maybe `.trigger('change');` ? https://github.com/moldcraft/adaptive-switch/blob/fa91bb97aef4aa979a96815d658004d8f532920c/jquery.adaptive-switch.js#L72

**Comment by danyj** [comment]
Hm , no , the click triggers the  switch on/off but seems like the value is not changing since there is a hidden input in there 
value inactive
http://prntscr.com/8mhk28

value active

http://prntscr.com/8mhk9n

**Comment by moldcraft** [comment]
Try `.find('input[type="checkbox"]')`

**Comment by danyj** [comment]
Thnx bud that helped , right one is this 


    	$('ID').find('input[type="checkbox"]').prop('checked', true).trigger('change');
	
	$('ID').find('input[type="checkbox"]').prop('checked', false).trigger('change');
