### ISSUE TITLE
Presets option suggestion

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#901]
By now we all know that using multi-picker is easy but as soon as you come with more complicated options sets that multi-picker grows to large and it gets way to complicated. 

The way I see the multi-picker is as a simple option set changer or presets loader so why not have something like this instead of that huge messy array . 

This how I need to setup a multi picker for only 3 option sets , now you can imagine if your option set has more complicated options and such. 

		'presets' =>array(
			'type' => 'multi-picker',
			'label' => false,
			'desc' => false,
			'picker' => array(
				'picked' => array(
					'label'   => __( 'Load preset', 'fw' ),
					'desc'    => __( 'Desc', 'fw' ),
					'type'  => 'short-select',
					'value' => 'style1',
					'choices' => array(
						'style1'  => __( 'Style 1', 'fw' ),
						'style2'  => __( 'Style 2', 'fw' ),
						'style3'  => __( 'Style 3', 'fw' ),
					),
				)
			),
			'choices' => array(
				'style1' => array(
					'title'    => array(
						'type'  => 'text',
						'label' => __( 'Title', 'fw' ),
						'value' => __( 'Style 1 title', 'fw' ),
						'desc'  => __( 'Icon title', 'fw' ),
					),
					
					'color' => array(
						'type' => 'thz-color-picker',
						'value' => '#ff6600',
						'label' => __('Text color', 'fw'),
						'desc' => __('Set button text color', 'fw')
					),				
				),
				
				'style2' => array(
					'title'    => array(
						'type'  => 'text',
						'label' => __( 'Title', 'fw' ),
						'value' => __( 'Style 2 title', 'fw' ),
						'desc'  => __( 'Icon title', 'fw' ),
					),
					
					'color' => array(
						'type' => 'thz-color-picker',
						'value' => '#000000',
						'label' => __('Text color', 'fw'),
						'desc' => __('Set button text color', 'fw')
					),				
				),
				
				'style3' => array(
					'title'    => array(
						'type'  => 'text',
						'label' => __( 'Title', 'fw' ),
						'value' => __( 'Style 3 title', 'fw' ),
						'desc'  => __( 'Icon title', 'fw' ),
					),
					
					'color' => array(
						'type' => 'thz-color-picker',
						'value' => '#ffffff',
						'label' => __('Text color', 'fw'),
						'desc' => __('Set button text color', 'fw')
					),				
				)
				
				
			)									

		),

that is for starters 79 lines

Now think of this , you have a set of 10 options , from those 10 you want only 2 to be changed on switch , because of those 2 you must rewrite the whole array.  Something like this would be easier to understand and much less code. 

	'presets' => array(
		'label'   => __( 'Load preset', 'fw' ),
		'desc'    => __( 'Desc', 'fw' ),
		'type'  => 'fw-presets',
		'value' => 'style2',
		'choices' => array(
			'style1'  => __( 'Style 1', 'fw' ),
			'style2'  => __( 'Style 2', 'fw' ),
			'style3'  => __( 'Style 3', 'fw' ),
		),
		
		
		
		'defaults' => array (
			
			'style1' => array (
			
				'title' => 'Style 1 title',
				'color' => '#ff6600'
			
			),
			
			'style2' => array (
			
				'title' => 'Style 2 title',
				'color' => '#000000'
			
			),
			
			'style3 => array (
			
				'title' => 'Style 3 title',
				'color' => '#ffffff'
			
			)
		
		
		),
		
		'template' => array (
		
	
			'title'    => array(
				'type'  => 'text',
				'label' => __( 'Title', 'fw' ),
				'value' => __( 'Style 1 title', 'fw' ),
				'desc'  => __( 'Icon title', 'fw' ),
			),
			
			'color' => array(
				'type' => 'thz-color-picker',
				'value' => '#ff6600',
				'label' => __('Text color', 'fw'),
				'desc' => __('Set button text color', 'fw')
			),		
		
		
		)

	),

and since our template is same as style1  I can even leave that one out 

	'presets' => array(
		'label'   => __( 'Load preset', 'fw' ),
		'desc'    => __( 'Desc', 'fw' ),
		'type'  => 'fw-presets',
		'value' => 'style2',
		'choices' => array(
			'style1'  => __( 'Style 1', 'fw' ),
			'style2'  => __( 'Style 2', 'fw' ),
			'style3'  => __( 'Style 3', 'fw' ),
		),
		
		
		
		'defaults' => array (

			'style2' => array (
			
				'title' => 'Style 2 title',
				'color' => '#000000'
			
			),
			
			'style3 => array (
			
				'title' => 'Style 3 title',
				'color' => '#ffffff'
			
			)
		
		
		),
		
		'template' => array (
		
	
			'title'    => array(
				'type'  => 'text',
				'label' => __( 'Title', 'fw' ),
				'value' => __( 'Style 1 title', 'fw' ),
				'desc'  => __( 'Icon title', 'fw' ),
			),
			
			'color' => array(
				'type' => 'thz-color-picker',
				'value' => '#ff6600',
				'label' => __('Text color', 'fw'),
				'desc' => __('Set button text color', 'fw')
			),		
		
		
		)

	),

So I am at 52 lines that do not need to grow bigger  by 10 per set but only by 2 that I need changed.

**Comment by danyj** [comment]
Here is same preset with 4 options but I am changing only 2  


	'presets' => array(
		'label'   => __( 'Load preset', 'fw' ),
		'desc'    => __( 'Desc', 'fw' ),
		'type'  => 'fw-presets',
		'value' => 'style2',
		'choices' => array(
			'style1'  => __( 'Style 1', 'fw' ),
			'style2'  => __( 'Style 2', 'fw' ),
			'style3'  => __( 'Style 3', 'fw' ),
		),
		
		
		
		'defaults' => array (

			'style2' => array (
			
				'title' => 'Style 2 title',
				'color' => '#000000'
			
			),
			
			'style2' => array (
			
				'title' => 'Style 3 title',
				'color' => '#ffffff'
			
			)
		
		
		),
		
		'template' => array (
		
	
			'title'    => array(
				'type'  => 'text',
				'label' => __( 'Title', 'fw' ),
				'value' => __( 'Style 1 title', 'fw' ),
				'desc'  => __( 'Icon title', 'fw' ),
			),
			
			'color' => array(
				'type' => 'thz-color-picker',
				'value' => '#ff6600',
				'label' => __('Text color', 'fw'),
				'desc' => __('Set button text color', 'fw')
			),	
			
			'heading_color' => array(
				'type' => 'thz-color-picker',
				'value' => '#ff6600',
				'label' => __('Heading color', 'fw'),
			),
						
			'text'    => array(
				'type'  => 'textarea',
				'label' => __( 'Text', 'fw' ),
				'value' => __( 'Add text', 'fw' ),
			),
			
	
		
		
		)

	),

**Comment by moldcraft** [comment]
Thank you.
It will be a new option type.

But I can't give an eta when we will start working on this.

**Comment by danyj** [comment]
Snce those  defaults should always be same , you dont need to save them in the array , you can output them as data attributes and use them as hooks for the switch. The only thing that should be saved is template array which always stay same in size.

**Comment by danyj** [comment]
And I think  someone else was working on mutlipicker also or asked for better way to show / hide options 

look at this 



	
	'presets' => array(
		'label'   => __( 'Load preset', 'fw' ),
		'desc'    => __( 'Desc', 'fw' ),
		'type'  => 'fw-presets',
		'value' => 'style2',
		'choices' => array(
			'style1'  => __( 'Style 1', 'fw' ),
			'style2'  => __( 'Style 2', 'fw' ),
			'style3'  => __( 'Style 3', 'fw' ),
		),
		
		
		
		'defaults' => array (

			'style2' => array (
			
				'title' => false,
				'color' => false,
				'heading_color' => '#000000'
			
			),
			
			'style3' => array (
			
				'title' => 'Style 3 title',
				'color' => '#ffffff'
			
			)
		
		
		),
		
		'template' => array (
		
	
			'title'    => array(
				'type'  => 'text',
				'label' => __( 'Title', 'fw' ),
				'value' => __( 'Style 1 title', 'fw' ),
				'desc'  => __( 'Icon title', 'fw' ),
			),
			
			'color' => array(
				'type' => 'thz-color-picker',
				'value' => '#ff6600',
				'label' => __('Text color', 'fw'),
				'desc' => __('Set button text color', 'fw')
			),	
			
			'heading_color' => array(
				'type' => 'thz-color-picker',
				'value' => '#ff6600',
				'label' => __('Heading color', 'fw'),
			),
						
			'text'    => array(
				'type'  => 'textarea',
				'label' => __( 'Text', 'fw' ),
				'value' => __( 'Add text', 'fw' ),
			),
			
	
		
		
		)

	),

**Comment by danyj** [comment]
Man , I should have done this long time ago, 
video: 
http://www.screencast.com/t/ui65LAXGfc

this option does not overload DB , only thing it saves is 1 hidden text input with selected preset name, no overload , all data is outputted in style button data attribute as JSON
http://prntscr.com/8mo0q7

no JS overload , everything is done on button click and check are preformed on per option type base

you can pick and choose option you want 

Selection goes by option ID 

you can use full ID 

or  ID without 

     fw-option-

or 

    fw-edit-options-modal-



option

	'testpreset' => array(
		'label' => __('Active preset', 'fw'),
		'type' => 'thz-presets',
		'value' => 'style1',
		'modal' => false,// if options in modal set to true
		'desc' => __('Select your default preset.', 'fw'),
		'preset-labels' => array (
			
			'style1' => 'Style 1 label',
			'style2' => 'Style 2 label'
				
		),
		
		'presets' => array (
			
			'style1'=> array(
				
				'fw-option-demo_text_2' => array (
					'type' => 'text',
					'value' => 'Hello I am changed'
				),
				'fw-option-demo_short_text_2' => array (
					'type' => 'text',
					'value' => 10
				),
				
				'fw-option-demo_multi_picker_switch_2-gadget--checkbox' => array (
					'type' => 'switch',
					'value' => 1
				),
				
				'fw-option-demo_multi_picker_switch_2-laptop-price' => array (
					'type' => 'text',
					'value' => 8530
				),
				
				'fw-option-demo_multi_picker_switch_2-laptop-webcam--checkbox' => array (
					'type' => 'switch',
					'value' => 1
				),

			),
			
			
			'style2'=>array(
			
				'fw-option-demo_text_2' => array (
					'type' => 'text',
					'value' => 'And I am changed again'
				),
				'fw-option-demo_short_text_2' => array (
					'type' => 'text',
					'value' => 18
				),

				'fw-option-demo_multi_picker_switch_2-gadget--checkbox' => array (
					'type' => 'switch',
					'value' => 0
				),
				
				'fw-option-demo_multi_picker_switch_2-phone-price' => array (
					'type' => 'text',
					'value' => 128358
				),
				
				
				'fw-option-demo_multi_picker_switch_2-phone-memory' => array (
					'type' => 'select',
					'value' => 64
				),

			)
			
		)
	),

**Comment by danyj** [comment]
@moldcraft  can you help me refine this? I know you busy now , when you get to it . If you want I can send you what I have and after refining you can add it to framework if you like. 

idea ,  I am using this  https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/33#issuecomment-131866126

to dump the data for specific set of options from the builder , in this case it is icon box 

I take dumped data and put it in as preset 

		'style1'=>array(
		
			'JSON' => array(
				'value' => 'DUMP DATA GOES HERE'
			
			),
		),

now from JS I need to set those back on click . Instead of looping trough the names , look for types and setting those back ,  I would like to run  reset popup action like but use my JSON data instead , 

This is my current function that sets data back on button click via ID,  type and value, 


		function setPreset($array,$modal){
			
			$.each($array,function (index,preset){
				
				var $type 	= preset.type;
				var $value 	= preset.value;
				var $name 	= index;

				
				var $id = 'fw-option-';
				
				if($modal == 1){
					
					$id = 'fw-edit-options-modal-';
				}
				
				if($name.indexOf($id) > -1){
					$id ='';
				}
				// THIS IS WHERE JSON DATA SHOULD BE PROCESSED
				if($name === 'JSON'){
					
					var $data = JSON.parse($value);
					// need to check if this is builder or theme options
					// for testing we will use builder 
					$options = $data.atts;
					
					console.log($options);
					
					return;	
				}
				
				var $selector = '#' + $id + $name;
				
				
				if($type == 'text' || $type == 'select' || $type == 'textarea'){
					
					$($selector).val($value).trigger('change');
				}
				
				if($type == 'color'){
					
					$($selector).iris();
					$($selector).val($value).trigger('change').trigger('click').iris('hide');
					
				}
				
				if($type == 'switch' || $type == 'checkbox'){
					
					if($value == 1){
						$($selector).prop('checked', true).trigger('change');
					}else{
						$($selector).prop('checked', false).trigger('change');
						
					}
				}	
				
				
				if($type == 'radio'){
					
					$($selector + '-' + $value).prop('checked', true).trigger('change');
				}
				
				if($type == 'icon'){
					
					$($selector).val($value).trigger('change');
					$($selector).parent().find(".selector-arrow-right").trigger('click');
				}
								
				
			});
		}


and this is how that function is processed 


		data.$elements.find('.fw-option.fw-option-type-thz-presets:not(.initialized)').each(function(){	
			
			$this 		=  $(this);
			$thisinput 	= $this.find('input');
			
			$this.find('.thz-presets').each(function(index, element) {
				
					$(element).on('click',function (e){
						
						e.preventDefault();
						
						$thispreset	= $(this);
						$presetname = $thispreset.attr('data-name'); 
						$preset 	= JSON.parse($thispreset.attr('data-preset'));	
						$modal		= $thispreset.attr('data-modal'); 
						
						
						$thispreset.parent().find('.thz-presets').removeClass('button-primary');
						
						setPreset($preset,$modal);
						$thisinput.val($presetname);
						$thispreset.addClass('button-primary');
					});
				
			});
			
		}).addClass('initialized');

**Comment by moldcraft** [comment]
Sorry, this looks complicated and I need to understand all this code, to understand if it's ok or not and to see what can be improved. This consumes time. I don't have it know (I will try to look at this in weekend).

*Right now I need to make urgently Backup because our next theme has big demo install zip and current Backup fails to install it.*

**Comment by danyj** [comment]
not an issue , I can send you the option and it will make sense when you see it. take your time.

**Comment by dinhtungdu** [comment]
@danyj Do this option type live? I share the same interest with you for this options. :)

**Comment by danyj** [comment]
@dinhtungdu no bud , I made it custom for our theme and cant release it until theme is out which will take a while.
