### ISSUE TITLE
Small issue in the general helpers

### ISSUE THREAD

**Issue by c0sm1n87** [ThemeFuse/Unyson#903]
as far as I can see (from my tests), fw_human_time returns as 45 years ago. I checked this function (actually I use the same) and I guess you removed this line accidentally:

$seconds = time() - $seconds
from here: 
https://github.com/ThemeFuse/Unyson/blob/e1c5e3d5e144306712d825e5654de8d06e9f7aba/framework/helpers/general.php#L1173

![untitled-1](https://cloud.githubusercontent.com/assets/10389279/10232766/30697072-6893-11e5-99f8-4a01a9d3dbf6.jpg)

**Comment by moldcraft** [comment]
No changes

* [v2.1.1](https://github.com/ThemeFuse/Unyson/blob/v2.1.1/framework/helpers/general.php#L871)
* [v2.4.8](https://github.com/ThemeFuse/Unyson/blob/v2.4.8/framework/helpers/general.php#L1183)

[diff](https://www.diffchecker.com/y5uxdtul) (identical)

I think it works fine: You give it a number of seconds, and it shows you it in words. It doesn't append ` ago` so you can use for both past and future events.
