### ISSUE TITLE
Additional option for a link or other functionality

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson#904]
I need a additional option for a link or other functionality in my case a link to external website.
Is not so important, but if you have time please male a mechanism to add easy this type of button

http://joxi.ru/a2XYajlCpG85Ag ( in one of this positions - in position 1 I think is the best option)

**Comment by andronic90** [comment]
Thanks for this:
$cfg = array(
	'page_builder' => array(
		'title'       => __( 'Accordion', 'the-core' ),
		'description' => __( 'Add an Accordion', 'the-core' ),
		'tab'         => __( 'Content Elements', 'the-core' ),
		'popup_header_elements' => '<a class="fw-docs-link" target="_blank" href="http://docs.themefuse.com/the-core/your-theme/shortcodes/accordion-1"><span class="fw-docs-info dashicons dashicons-editor-help"></span>'.__('Go to Docs', 'the-core').'</a>',
	)
);

This problem remain only on contact form shortcode.

**Comment by moldcraft** [comment]
This was already implemented.
