### ISSUE TITLE
Additional Column Sizes ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#905]
Hello @moldcraft 

I need to know that how to add additional column sizes in column shortcode.

Like i want this structure .

1/5 | 1/7

How to achieve this because in unyson there is 1/6 | 1/6 option.

Need urgent Help.

Thanks in advance,

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/681

add your own to builder config override
https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/78d175f56f5259f4471761b2b2dc384634b563ad/config.php#L13
