### ISSUE TITLE
How to get option script load after builder.js?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#906]
I need to load my custom option js after  builder.js 

this does not work 

		wp_enqueue_script(
			'fw-option-' . $this->get_type(),
			$uri .'/js/scripts.js',
			array('jquery', 'fw-events','fw-option-builder'),
			fw()->manifest->get_version()
		);

but it should 

https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/e524138b589fbc2d0f2a75fcd434c0c11a1a9dd7/includes/option-types/builder/extends/class-fw-option-type-builder.php#L212

**Comment by danyj** [comment]
tried this also , no go 

		wp_enqueue_script(
			'fw-option-' . $this->get_type(),
			$uri .'/js/scripts.js',
				array(
					'jquery-ui-draggable',
					'jquery-ui-sortable',
					'fw',
					'fw-events',
					'backbone',
					'backbone-relational'
				),
			fw()->manifest->get_version()
		);

**Comment by moldcraft** [comment]
Try [this action](https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/e07cd70ea1ea8a0179078ba6be4d616c9bc732c5)

**Comment by danyj** [comment]
sorry bud , but where should I add  the action ?

**Comment by danyj** [comment]
works, got it
