### ISSUE TITLE
Check if the page content was created by page builder or default editor

### ISSUE THREAD

**Issue by alvisir** [ThemeFuse/Unyson#909]
Hi, it's possible to check if the page content was created by page builder or default editor? 
In my case I should add a class to the content wrapper if one of two conditions occur.

Thanks

**Comment by moldcraft** [comment]
Hello,

Use this function https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/master/helpers.php#L4

**Comment by alvisir** [comment]
Many thanks! You're awesome!
