### ISSUE TITLE
How to  set new fw.OptionsModal  options via JS

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#910]
OK I am digging trough code and I cant find suitable way to set this JSON back , 

fw.OptionsModal  is using own JSON format that contains option type and extra data to set the options back to default 

https://github.com/ThemeFuse/Unyson/blob/0eb2c63ab2f26124d56116227cc8af1b57e09c0c/framework/static/js/fw.js#L971

but using no matter what I can only get the option name and its value , 

this is my json example  that I would like to run on a click , basicaly set my 2 options to style2 and defined color 

	var $ops = '{"style":"style2","color":"#ff6600"}';

	jQuery.ajax({
		url: ajaxurl,
		type: 'POST',
		data: [
			'action=fw_backend_options_get_values',
			'options='+ encodeURIComponent($ops),
			'name_prefix=fw_edit_options_modal'
		].join('&'),
		dataType: 'json',
		success: _.bind(function (response, status, xhr) {
			fw.loading.hide(loadingId);

			if (!response.success) {
				/**
				 * do not replace html here
				 * user completed the form with data and wants to submit data
				 * do not delete all his work
				 */
				alert('Error: '+ response.data.message);
				return;
			}

			// make sure on the below open, the html 'change' will be fired
			this.model.set('html', '', {
				silent: true // right now we don't need modal reRender, only when the open below
			});

			this.model.open(response.data.values);
		}, this),
		error: function (xhr, status, error) {
			fw.loading.hide(loadingId);

			/**
			 * do not replace html here
			 * user completed the form with data and wants to submit data
			 * do not delete all his work
			 */
			alert(status +': '+ error.message);
		}
	});

I tried all possible combos but seems like 
  
    fw_backend_options_get_values

requires me to tell it what type of option it is

This is divider   example
    
    console.log(JSON.stringify(this.model.get('options')));

http://prntscr.com/8n9j1o

and I understand that this is the model of the option that the function requires , but how do I get to do this via my JSON string? 

@moldcraft  I am using the get dbSettingsOptions plugin you made for me to get and save right set of options so options are ok .

**Comment by moldcraft** [comment]
`options=` expects options array, not values array.

optionsModal has 2 attributes https://github.com/ThemeFuse/Unyson/blob/0eb2c63ab2f26124d56116227cc8af1b57e09c0c/framework/static/js/fw.js#L1013-L1031

You can access them via `modal.get('options')` and set via `modal.set('options', [...])` http://backbonejs.org/#Model-get

----

In your js ajax example, you missed/removed an important part https://github.com/ThemeFuse/Unyson/blob/0eb2c63ab2f26124d56116227cc8af1b57e09c0c/framework/static/js/fw.js#L928

there should be your values, but names should be prefixed with `name_prefix=` (or try to change name prefix to a empty string) so with prefix your values would be

```
fw_edit_options_modal[style]=style2&fw_edit_options_modal[color]=#ff6600
```

----

*I hope, I understood your question correctly*

**Comment by danyj** [comment]
Here is exactly what I am trying to do . Via code below from console , set the new values from $ops var

![screenshot_14](https://cloud.githubusercontent.com/assets/2340172/10264348/4f76e608-6a09-11e5-99ca-b898a0c6887d.jpg)

the code 


	$=jQuery;
	var $ops = '{"style":{"ruler_type":"space","space":{"height":"802"}}}';
	var $el = jQuery('.fw-modal-open .media-frame-content form');
	
	jQuery.ajax({
		url: ajaxurl,
		type: 'POST',
		data: [
			'action=fw_backend_options_get_values',
			'options='+ encodeURIComponent($ops),
			'name_prefix=fw_edit_options_modal',
			$el.serialize()
		].join('&'),
		dataType: 'json',
		success: _.bind(function (response, status, xhr) {
	
				// Set the values from $ops var
	
		}, this),
		error: function (xhr, status, error) {
	
			alert(status +': '+ error.message);
		}
	});

When that ajax is done the divider should be set at 

![screenshot_15](https://cloud.githubusercontent.com/assets/2340172/10264353/92369c36-6a09-11e5-8716-8cecdc0efca1.jpg)

**Comment by moldcraft** [comment]
I don't understand:

* Something minor: You prefixed `$ops` with `$` like it's a jQuery DOM element, but it's just a string
* You try to extract values from `$ops` (options) but there is no option in that array/object. Where is the `"type":"..."` parameter?

**Comment by danyj** [comment]
this $ is just me , dont worry about it , 
I cant get the type with any known ways to me , 
if I use this ,  
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/33#issuecomment-131866126

or if  use this 

	var dbSettingsOptions = {
		$form: jQuery('.fw-modal-open .media-frame-content form'),
		options: null,
		getOptions: function (callback) {
			if (this.options) {
				return callback(this.options);
			}
	
			jQuery.ajax({
				url: ajaxurl,
				type: 'POST',
				data: 'action=fw_modal_get_options',
				dataType: 'json',
				success: _.bind(function (response, status, xhr) {
					if (!response.success) {
						alert('Ajax error');
						return;
					}
	
					this.options = response.data.options;
	
					callback(this.options);
				}, this),
				error: function (xhr, status, error) {
					alert('Ajax error');
				}
			});
		},
		getValues: function(callback) {
			if (!this.options) {
				return this.getOptions(_.bind(function(){
					this.getValues(callback);
				}, this));
			}
	
			jQuery.ajax({
				url: ajaxurl,
				type: 'POST',
				data: [
					'action=fw_backend_options_get_values',
					this.$form.serialize()
						.replace(/fwf=[^\&]+\&/, ''), // remove special hidden input value to prevent form save
					'options='+ encodeURIComponent(JSON.stringify(this.options)),
					'name_prefix=fw_edit_options_modal',
				].join('&'),
				dataType: 'json',
				success: _.bind(function (response, status, xhr) {
					if (!response.success) {
						alert('Error: '+ response.data.message);
						return;
					}
	
					callback(response.data.values);
				}, this),
				error: function (xhr, status, error) {
					alert(status +': '+ error.message);
				}
			});
		}
	};


all I get is the  option name and value , no type , 

those are only 2 ways I know

**Comment by danyj** [comment]
fw_modal_get_options  is doing this 

		wp_send_json_success(array(
			//'options' => fw()->theme->get_settings_options()
			'options' => thz_file_get_options('extensions/shortcodes/shortcodes/divider/options')
		));

just gets the default options that's all

**Comment by moldcraft** [comment]
Maybe you can try to generate, on option render, on php side, an array `'option_id' => 'option_type'`, bring it in js then use it like this

```javascript
function optionNameToType(name, namePrefix, idToType) {
    function preg_quote(str) { // http://phpjs.org/functions/preg_quote/
        var delimiter = '/';
        return String(str).replace(new RegExp('[.\\\\+*?\\[\\^\\]$(){}=!<>|:\\' + (delimiter || '') + '-]', 'g'), '\\$&');
    }

    var id = name.replace(new RegExp('^'+ preg_quote(namePrefix) +'\\['), '').replace(/\].*/, '');
    
    return idToType[id];
}

var idToType = {'test': 'text', 'best': 'textarea'}; // this should come from php
var namePrefix = 'fw_edit_options_modal';

console.log( // usage examples
    optionNameToType('fw_edit_options_modal[test]', namePrefix, idToType),
    optionNameToType('fw_edit_options_modal[best][a]', namePrefix, idToType),
    optionNameToType('fw_edit_options_modal[test][a][x]', namePrefix, idToType)
);
```

**Comment by danyj** [comment]
thnx , I see what you mean Il try this but this should be much easier , we should be able to get those types just like you do here https://github.com/ThemeFuse/Unyson/blob/0eb2c63ab2f26124d56116227cc8af1b57e09c0c/framework/static/js/fw.js#L971

**Comment by danyj** [comment]
ok I got data working and coming back with type , now , how to do this peace
https://github.com/ThemeFuse/Unyson/blob/0eb2c63ab2f26124d56116227cc8af1b57e09c0c/framework/static/js/fw.js#L988

on the current open modal ?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/commit/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a

```javascript
var modal = jQuery.data(
    $anyElementInsideModal.closest('form').get(0), 
    'modal'
);
```

**Comment by danyj** [comment]
that magic bullet!

you my friend are one of a kind!
my hat off to you@@@@@@

**Comment by moldcraft** [comment]
Glad I could help

**Comment by danyj** [comment]
small nudge if I may , everything works ok , one small issue is resetting the current modal , 
check this out  http://screencast.com/t/tTY6pnCCJl7

creation , click all events work perfect as long as the modal is open , if I create new preset and close the modal without saving , next time I open it I dont see my preset unless I refresh the page ,  is there a silent save or something I can use to update  it? 

if I do , 

    $el.find('input[type="submit"].hidden-submit').trigger('click');

it closes the modal , I hope I don have to rerun option render  since this thing is overloaded with ajax already
https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/static/js/fw.js#L1109-L1139

**Comment by danyj** [comment]
looks like each time this is used

    modal.open(response.data.values);

new collection is saved , so seems like I must use the render instead of this 


        jQuery.ajax({
            url: ajaxurl,
            type: 'POST',
            data: [
                'action=fw_backend_options_get_values',
                'options=' + encodeURIComponent(get_defaults),
                'name_prefix='+namePrefix,
                get_preset
            ].join('&'),
            dataType: 'json',
            success: function(response, status, xhr) {

                modal.set('html', '', {
                    silent: false
                });

                modal.open(response.data.values);
                fw.soleModal.hide('thz_loading_preset');

            },
            error: function(xhr, status, error) {

                alert(status + ': ' + error.message);
            }
        });

**Comment by danyj** [comment]
ok , i must use render on switching between styles , and that is fixed now ,
with 

    renderPreset(modal,response.data.values);

called on success which runs  
https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/static/js/fw.js#L1109-L1139


 but on not saving and close is problem , looks like I need to update this https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/static/js/fw.js#L1096

but I cant "see" it in my file ,

**Comment by moldcraft** [comment]
Try to comment [these lines](https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/static/js/fw.js#L1096-L1101)

**Comment by danyj** [comment]
I dont follow? , if I uncoment those lines in fw.js when I open modal it is empty , so yes looks like those cached ones is what I see , but this is what runs on each of those preset buttons click .  I get the values and render presets





	function renderPreset (thismodal,thisvalues){
			
		jQuery.ajax({
			url: ajaxurl,
			type: 'POST',
			data: {
				action: 'fw_backend_options_render',
				options: JSON.stringify(thismodal.get('options')),
				values: thisvalues,
				data: {
					name_prefix: 'fw_edit_options_modal',
					id_prefix: 'fw-edit-options-modal-'
				}
			},
			dataType: 'json',
			success: function (response, status, xhr) {

				if (!response.success) {
					thismodal.set('html', 'Error: '+ response.data.message);
					return;
				}
             	 thismodal.set('html', '', {
                    silent: false
                });

				thismodal.set('html', response.data.html);
				fw.soleModal.hide('thz_loading_preset');
			},
			error: function (xhr, status, error) {
				fw.soleModal.hide('thz_loading_preset');
				thismodal.set('html', status+ ': '+ error.message);
			}
		});		
		
	}
	
	
	
    function loadPreset(get_preset, presetTrigger) {
		
		
		var thisform = presetTrigger.closest('form');
        var modal 	= jQuery.data(
            thisform.get(0),
            'modal'
        );
		var namePrefix   =  thisform.find('.thz-presets-save').attr('data-nameprefix');
        var get_defaults = JSON.stringify(modal.get('options'));

        jQuery.ajax({
            url: ajaxurl,
            type: 'POST',
            data: [
                'action=fw_backend_options_get_values',
                'options=' + encodeURIComponent(get_defaults),
                'name_prefix='+namePrefix,
                get_preset
            ].join('&'),
            dataType: 'json',
            success: function(response, status, xhr) {


				renderPreset(modal,response.data.values);


            },
            error: function(xhr, status, error) {

                alert(status + ': ' + error.message);
            }
        });
    }
