### ISSUE TITLE
Search Functionality in Icons Option Type. ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#911]
Hello @moldcraft 

I am just wondering that is there any search functionality in icons option type. You guys have doing very good work in unyson and i don't think so that you have missed this option i am pretty sure that there is a way to do this or you guys have plan to do this in near future.

Not Urgently required but would like to have this option is much appreciated.

Thanks

**Comment by danyj** [comment]
I did send pull for this but since they work on new one it is not accepted. You might try it 
https://github.com/ThemeFuse/Unyson/pull/770

**Comment by wpthemes786** [comment]
Thanks @danyj  Much Appreciated.

**Comment by danyj** [comment]
this is what it does 
http://screencast.com/t/8zPNkJNdpqc

https://github.com/ThemeFuse/Unyson/issues/769

**Comment by wpthemes786** [comment]
Many Thanks @danyj

**Comment by wpthemes786** [comment]
Sorry i forget to ask about overriding files in theme.
I have this structure in my theme 
framework-customizations\includes\option-types\

Thanks

**Comment by danyj** [comment]
I am not sure about  option type overrides , I think you must create own option type , 
http://manual.unyson.io/en/latest/options/create-option-type.html#content

so you would need to download the icon , rename folder and class and call it

**Comment by moldcraft** [comment]
Yes, you can't overwrite option types, create a new one.

**Comment by danyj** [comment]
http://www.filedropper.com/new-icon

download it ,  extract and place new-icon folder in  

   framework-customizations/includes/option-types/

in hooks add 

	function _action_theme_include_custom_option_types() {
		require_once dirname(__FILE__) . '/includes/option-types/new-icon/class-fw-option-type-new-icon.php';
	}
	add_action('fw_option_types_init', '_action_theme_include_custom_option_types');


option type   is 

    new-icon

**Comment by wpthemes786** [comment]
@danyj  and where do i exactly put this hook in hooks file. in inc/hooks.php is that this file

**Comment by danyj** [comment]
yes , but what I did is this since I have many custom option types 

in includes/  folder I placed file name 

    option-types.php


in that file I have 


	<?php if ( ! defined( 'ABSPATH' ) ) die( 'Direct access forbidden.' );
		function _action_theme_include_custom_option_types() {
			if (is_admin()) {
				require_once dirname(__FILE__) . '/option-types/new-icon/class-fw-option-type-new-icon.php';
				// and all other option types
			}
		}
		add_action('fw_option_types_init', '_action_theme_include_custom_option_types');

**Comment by wpthemes786** [comment]
Where should i exactly create this file and put this code in that file. can you provide me full path.

**Comment by danyj** [comment]
create file  

    option-types.php

with the content

	<?php if ( ! defined( 'ABSPATH' ) ) die( 'Direct access forbidden.' );
		function _action_theme_include_custom_option_types() {
			if (is_admin()) {
				require_once dirname(__FILE__) . '/option-types/new-icon/class-fw-option-type-new-icon.php';
				// and all other option types
			}
		}
		add_action('fw_option_types_init', '_action_theme_include_custom_option_types');
 
in 


    framework-customizations/includes/

so it becomes 

     framework-customizations/includes/option-types.php

**Comment by wpthemes786** [comment]
Why its says undefined option type

**Comment by danyj** [comment]
give me a minute, I did not test the override

**Comment by danyj** [comment]
here this one works 
http://www.filedropper.com/new-icon-works

it needed some class overrides since the name is new-icon  not icon anymore 
http://prntscr.com/8nwx1e

undefined option type  will show if paths to files are wrong and option type is not available , if it still shows and you see the new-icon option than do hard refresh

**Comment by wpthemes786** [comment]
![2015-10-05_1418](https://cloud.githubusercontent.com/assets/12461946/10276942/034e2dcc-6b6c-11e5-844f-6c460f160bd2.png)

The above picture is my directory structure.

![2015-10-05_1419](https://cloud.githubusercontent.com/assets/12461946/10276967/3041555c-6b6c-11e5-9685-7e27dd2ea885.png)

And in my option type class file the you have use this path,

$uri = get_template_directory_uri() .'/inc/includes/option-types/'. $this->get_type() .'/static';

Thanks

**Comment by wpthemes786** [comment]
you have said in above comment to put these option type file in framework-customization folder. Now in class file you get the path from different location

**Comment by danyj** [comment]
you dont have inc  folder ,   I do   
I followed this path 
https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-parent/inc

remove the inc from path and it should work , just adjust the path to your folder structure and it should work

**Comment by danyj** [comment]
yes , my bad  that should have  been 


     framework-customizations/inc/includes/option-types.php

**Comment by danyj** [comment]
fixed above , here my structure 
http://prntscr.com/8nx4qx

**Comment by wpthemes786** [comment]
@danyj  waiting for your reply

**Comment by danyj** [comment]
I fixed the above instructions with proper folder structure 

https://github.com/ThemeFuse/Unyson/issues/911#issuecomment-145465082

**Comment by pe6o** [comment]
@danyj is there a new working link where I can download your custom option field?

**Comment by danyj** [comment]
bud , I posted new link and correct info 9 days ago
https://github.com/ThemeFuse/Unyson/issues/911#issuecomment-145465082
http://www.filedropper.com/new-icon-works

**Comment by pe6o** [comment]
Hmm, it redirects me to the homepage of filedropper...

**Comment by danyj** [comment]
http://www.filedropper.com/new-icon-works

**Comment by danyj** [comment]
try now , I reuploaded

**Comment by pe6o** [comment]
Yeah, it works now. Thanks!

**Comment by wpthemes786** [comment]
@danyj  Kindly Sorry i was busy so could not download the new icon zip file.

KIndly send me the download link of new icon zip file.

Many Thanks

**Comment by Ataurr** [comment]
@danyj  Can you please share one more time. 
 all link redirected to home page

**Comment by danyj** [comment]
Here it is, https://www.dropbox.com/s/ptxceyszem559gt/new-icon-works.zip?dl=0

**Comment by moldcraft** [comment]
We have released option-type [`icon-v2`](http://manual.unyson.io/en/latest/options/built-in/icon-v2.html)
