### ISSUE TITLE
How to properly use fw_backend_options_render in ajax?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#913]
OK this is becoming ridiculous and I refuse to believe that this is the way this should be done.  
Please help me out here. 

 I have in theme/options    file topmenu.php   that contains $options array of 20 options for top menu. 

Than I have  topmenu  current  options  serialized  and saved to a file  , just an example 

    fw_options%5Bmenupreset%5D=style1&f.......

Id rather use JSON but according to this way of doing things it needs to be serialized
https://github.com/ThemeFuse/Unyson/blob/bdc4f3ab1ed59e2c0b1ded227eb093cd1f556b4a/framework/static/js/fw.js#L933

Now in order for me to re-render  my saved options , I need to : 

    run ajax to get options default array   by looking in to topmenu.php ( why? ) 
    run ajax to get my saved serialized preset
    run ajax  to  get the values  with  fw_backend_options_get_values ( why? ) 
    run ajax to render and return html with  fw_backend_options_render

is there any way to shorten this madness? 

can I use just  max 2 ajax calls  ? 

    run ajax to get my preset 
    run ajax to rerender

**Comment by danyj** [comment]
this is a crude example that works, so is this the only way ?   


	function loadNewStyle(styleName) {
		function getOptionDefauls() {
	
			fw.loading.show();
	
			jQuery.ajax({
				url: ajaxurl,
				type: 'POST',
				data: {
					'action': 'thz_get_options_from_file',
					'presetdefault': 'topmenu',
				},
				dataType: 'json',
				success: function(response, status, xhr) {
					if (!response.success) {
						alert('Ajax error');
						return;
					}
	
					getPresetValues(response.data.options);
	
				},
				error: function(xhr, status, error) {
					alert('Ajax error');
				}
			});
		}
	
		function getPresetValues(optionvalues) {
	
			$.ajax({
				type: "post",
				dataType: "json",
				url: ajaxurl,
				data: {
					'action': 'thz_presets_read_preset',
					'presetname': styleName,
					'presetelement': 'thztheme/thzpresets/topmenu/'
				},
				success: function(response, status, xhr) {
	
					var get_defaults = optionvalues;
					var get_preset = response.data.options;
					getOptionValues(get_defaults, get_preset)
				}
			});
	
		}
	
		function getOptionValues(get_defaults, get_preset) {
			jQuery.ajax({
				url: ajaxurl,
				type: 'POST',
				data: [
					'action=fw_backend_options_get_values',
					'options=' + encodeURIComponent(JSON.stringify(get_defaults)),
					'name_prefix=fw_options',
					get_preset
				].join('&'),
				dataType: 'json',
				success: function(response, status, xhr) {
	
					renderPreset(response.data.values, get_defaults)
				},
				error: function(xhr, status, error) {
	
					alert(status + ': ' + error.message);
				}
			});
		}
	
		function renderPreset(options_to_render, get_defaults) {
	
			jQuery.ajax({
				url: ajaxurl,
				type: 'POST',
				data: {
					action: 'fw_backend_options_render',
					options: JSON.stringify(get_defaults),
					values: options_to_render,
					data: {
						name_prefix: 'fw_options',
						id_prefix: 'fw-option-'
					}
				},
				dataType: 'json',
				success: function(response, status, xhr) {
	
					if (!response.success) {
						console.log(response.data.message);
						return;
					}
					fw.loading.hide();
					$('#fw-options-box-topmenu_subtab .inside').html(response.data.html);
	
					fwEvents.trigger('fw:options:init', {
						$elements: $('.fw-settings-form')
					});
				},
				error: function(xhr, status, error) {
					console.log(response.error.message);
				}
			});
	
		}
	
		getOptionDefauls();
	
	}


    loadNewStyle('style5')

**Comment by moldcraft** [comment]
> Id rather use JSON but according to this way of doing things it needs to be serialized

[jQuery.ajax.data accepts 2 formats](http://api.jquery.com/jquery.ajax/#sending-data-to-server):

* String, url-like

    ```
    simple_var=val&array_1[]=val&array_1[]=val_2&array_2[x]=val&array_2[y]=val_2
    ```

    This has the same structure like form values sent in POST on submit.

* Object, JSON

    ```javascript
    {
        simple_var: 'val',
        array_1: ['val', 'val_2'],
        array_2: {
            x: 'val',
            y: 'val_2'
        }
    }
    ```

    **Important!** In this case [the keys order is not guaranteed](http://stackoverflow.com/a/4515863), so if in your form the value order is critical, then better to not use this solution.

   For e.g. `addable-...` in form names has

    ```
    whatever[1][hello]=Test
    whatever[2][hello]=Best
    ```

    when you change the order of boxes/options (when sortable is enabled for `addable-...`) then it will be

    ```
    whatever[2][hello]=Test
    whatever[1][hello]=Best
    ```

    but when transformed to JSON, it may cause keys auto-sort and it will become

    ```javascript
    {
        whatever: {
            1: {
                hello: 'Best'
            },
            2: {
                hello: 'Test'
            }
        }
    }
    ```

> can I use just max 2 ajax calls ?

What stops you from doing that?

**Comment by danyj** [comment]
ok , thnx for the info about JSON,  
but  
>What stops you from doing that?

well seems like I must run this in the way I described above 

First ajax is to get the default array structure so that it can be compared to the option value
Second one is  to get my serialized options that are saved in a file  

third is to get options from values required for render
https://github.com/ThemeFuse/Unyson-Framework/blob/master/core/components/backend.php#L659-L666

fourth is to render 

https://github.com/ThemeFuse/Unyson-Framework/blob/master/core/components/backend.php#L578-L585

or am I missing the point here in those actions ?

**Comment by danyj** [comment]
so basically question is can I use my saved serialized directly with render

https://github.com/ThemeFuse/Unyson-Framework/blob/master/core/components/backend.php#L578-L585

and skip the other 2

**Comment by danyj** [comment]
to make it very short , the whole point of all this is to render my saved preset , no matter what format I have saved , JSON , serialized data , I need to render this properly the shortest way possible.

**Comment by moldcraft** [comment]
> First ajax is to get the default array structure so that it can be compared to the option value
> Second one is to get my serialized options that are saved in a file

Why you can't put that data in html on render?

> third is to get options from values required for render

Maybe this step also can be done on render? Or all the above steps in one ajax?

> and If so how ?

on render put all those in `data-...="..."` attributes?

----

Sorry, now I am focused on Backup and I am asking this by fast looking. I am feeling that I don't have enough "brain RAM" too keep track of all the details that you are trying to explain (looks complicated, or maybe because we are chatting/writing, not talking)

**Comment by danyj** [comment]
lol  >"brain RAM"  nice one 

it looks complicated I admit but it is simple concept. 

>Why you can't put that data in html on render?

because render requires 2 things ,  default options JSON string and  object with 

    ID:value  

and serialize comes as 

    NAME:value 

how would you do  this 

1.  how would you save data in a file (   I am rewrtiitng and thinking  of ,  form.serializeArray()  save it in  presetname.json )

2 . how would you render  that saved data

**Comment by moldcraft** [comment]
> on render put all those in `data-...="..."` attributes?

Or to prevent making the html too big. On `_enqueue_static()` to `wp_localize_script()` the data you need.

**Comment by danyj** [comment]
> on render put all those in data-...="..." attributes?

I had it originally like that , but it does get big , and if you have lets say 5 or more presets it gets to much for html

**Comment by danyj** [comment]
SImple concept being ,   save preset in to a file , on button click  render preset

**Comment by moldcraft** [comment]
> save preset in to a file

in `wp-content/uploads` ? because in other directory you will need FTP details from user (a form should be displayed)

> how would you save data?

In DB.

> how would you render that saved data?

* On option static enqueue, localize the data in javascript
* On preset save, in ajax response send the new data and update the javascript value (so it will be used on next render, instead of doing an ajax on next render to get the data)

**Comment by danyj** [comment]
> because in other directory you will need FTP details

no way , please dont tell me this ,  in order to save anything to a file in let say   

    themes/themename/presets 

I need FTP credentials?

I need presets in files so that they can be transferable from theme to theme

**Comment by danyj** [comment]
ok just tested on live server , saving presets to a file works ok , unless you know something that will mess this up

**Comment by moldcraft** [comment]
On regular/default server installations php can't write anywhere (because all files are owned by `your_user` and php scripts are executed by `www-data` user), it can write only in directories with write permissions for all `777`. `wp-content/uploads` is required to be `777` because WordPress will not be able to upload images (asking FTP details on every image upload is too much).

This is the reason why [`WP_Filesystem`](https://codex.wordpress.org/Filesystem_API) exists.

I know a person, his site was regularly hacked, then he set `755` on `wp-content/uploads`, so no bad plugin or any php script can create or modify files. Only when he wants to upload some images, he sets `777` on `wp-content/uploads` then sets back `755`.

I know that on most of hosting providers, there are scripts that automatically install WP and set the owner for all files to `www-data`, this is convenient but not secure.

On my localhost I install apache + php manually and from php I can't change/create files. If I will set the owner to `www-data` for everything, I will not be able to edit the files from IDE. The only way is to set `777` but, when I will create a new file from IDE it will be owned by current user, and it will be a mess with files owned by different users and different permissions (also permission denied errors on extensions or WordPress update).

On your localhost you have MAMP executed as super-user?

**Comment by danyj** [comment]
I am on WAMP local and have no permission issue , just tested this concept on live cPanel  apache + litespeed where by default max folder permission is 755  and it works. 

http://prntscr.com/8oba8c

http://prntscr.com/8obaqk
http://prntscr.com/8obath

I have been doing same concept on Joomla since about 5 years now , and customers had no issues with files modification/creation via php . Sure proper POST checks are required and I do use 

    WP_Filesystem

in this case.  Just hope that in WP is not much different than Joomla when it comes to folder permission issues.

**Comment by moldcraft** [comment]
This is on my localhost

![s](https://static.md/cc4f063c2c6ddb487206ba339c2c1e17.png)

> http://prntscr.com/8oba8c 
> http://prntscr.com/8obath

Can you show the column Owner in that table?

**Comment by moldcraft** [comment]
> I am on WAMP

In Windows didn't exist multiple users, so you will never have an issue with permission denied because the file owner is another user.

**Comment by danyj** [comment]
in cPanel I dont know how to show the owner column but I am sure that in this case is the user ,  no I

**Comment by danyj** [comment]
I mean this relies on user permission for the folder and as long as read and write are set for the user on server it should work. I mean it did work for me for 5 years now. 100K members and few cases where their theme folder was blocked due to wrong things , but if they cant see the theme css file or run theme index.php than there is a problem , as long as those 2 work the creation /modification of files via ajax should be ok. 

You really got me thinking now

**Comment by moldcraft** [comment]
To confirm what I said https://codex.wordpress.org/Changing_File_Permissions

**Comment by danyj** [comment]
OK , please tell me how to test bad case scenario in WP. I am on live server, what should I do , create some admin user and change permissions or ?

**Comment by moldcraft** [comment]
Find the owner of directories within `wp-content/uploads/`

Somehow, make sure the the owner of your theme directories (and files) is another user. For e.g. try to connect with your FTP user (if it's another user) and upload your theme via FTP (instead of WP admin upload form), so the files will be created as FTP user.

**Comment by danyj** [comment]
ah , ok , on it

**Comment by danyj** [comment]
no issue bud , created ftp user , loged in , uploaded  complete theme folder , ( not zip /unzip ) , activated theme and no issues. Could be my server setup that files are always owned by the user.

**Comment by moldcraft** [comment]
Which is owner of `themes/themename/presets` directory and the files in it? Why php was able to create files inside the `presets` directory?

**Comment by danyj** [comment]
I cant see it bud , I think I setup cPanel trough WHM  for all files in user accounts to be owned by that user , so if you ftp anything by any user , let say   cPanel owned by user1 , all files inside are owned by user1 ,  

I have no environment to check this except MAMP on macbook PRO , 

if you know how I should set this up on MAMP it would be great . 

On the other hand it is strange to me that WP can run n this way , 1 WP install multiple file owners

**Comment by moldcraft** [comment]
FileZilla has the Owner column

![](https://static.md/1642f3ecdd07857d8b73b0ce6dc880f6.png)

**Comment by danyj** [comment]
ok give me min

**Comment by danyj** [comment]
http://prntscr.com/8oc91u
http://prntscr.com/8oc96x

**Comment by danyj** [comment]
same owner for everything in that wp folder  , i think this is lightspeed thing

**Comment by danyj** [comment]
Here is why it is doing it , 

    WP_Filesystem

http://ottopress.com/2011/tutorial-using-the-wp_filesystem/

>The WP_Filesystem basically support five different ways of writing files to the system and they all ensure that ownership of those files remains firmly in the hands of the same person that owns the WordPress files. In other words, it writes files using your user account and not as the webserver user.

and that is exactly  what I used , 
I did not use 

  fopen() 

or 

  fwrite()

directly , but used the wp file system instead

**Comment by moldcraft** [comment]
I know that. But in your case it is able to do thatwithout FTP details (I don't know why), in my case it can't and it asks FTP details.

**Comment by danyj** [comment]
>in my case it can't and it asks FTP details

strange , I would really like to test this in some way 

so you are saying that if you do an ajax action that does 


    WP_Filesystem::put_contents(file_path,content);

you are asked for FTP credentials ?

**Comment by danyj** [comment]
I dug this up from Otto's comments

> If you are on shared hosting, and see WordPress ask for FTP credentials, then it’s not running setuid methods, and it’s asking for FTP credentials as a form of protection, because it does not want to write files and have them owned by the webserver user.

**Comment by moldcraft** [comment]
`WP_Filesystem::put_contents();` will fail.

First we [make sure we have filesystem access/connection](https://github.com/ThemeFuse/Unyson/blob/379a69a0b08187b2d9e983cdb2c75335f092729a/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L907-L911) then we do actions on files.

**Comment by danyj** [comment]
yes I do that to , checing the wp_filesystem

	 /**
	 * Return wp_filesystem, initiate if not there
	 */
	public static function thz_preset_file_system(){
		
		global $wp_filesystem;
		if (empty($wp_filesystem)) {
			require_once (ABSPATH . '/wp-admin/includes/file.php');
			WP_Filesystem();
		}
		
		return 	$wp_filesystem;
	}

but this is a big thing and I need to do it right

**Comment by moldcraft** [comment]
I added this code in `{theme}/functions.php`

```php
add_action('admin_head', function(){
	fw_print(
		get_filesystem_method()
	);
});
```

and it shows `'ftpext'`.

What it shows on your server?

**Comment by danyj** [comment]
in wamp and live cPanel

    'direct'

**Comment by danyj** [comment]
I just forced the config  via 

    define('FS_METHOD', 'ftpext');


and see what you mean. This is bad news, can you do me a favor and test on your end with this in config 


	define('FS_METHOD', 'ftpext');
	define('FTP_BASE', 'PATH_TO_YOUR_BASE');
	define('FTP_USER', 'username');
	define('FTP_PASS', 'password');
	define('FTP_HOST', 'host');
	define('FTP_SSL', false);


and see if your ajax would now ask you for credentials

**Comment by moldcraft** [comment]
I'll try later. Recently I reinstalled my OS and I don't have configured the FTP server.

**Comment by danyj** [comment]
for time being until we find suitable solution I did this 
http://prntscr.com/8oe68i
when you get to it please do let me know about ajax + FTP user info in config. 
If that works we might be ok

**Comment by moldcraft** [comment]
~~Your WordPress installation~~ -> Current Theme :)

**Comment by danyj** [comment]
lol :)  no man is WP fault , don't you know that :)

**Comment by danyj** [comment]
I think best fallback is to check if we can save /load to file and if not save in DB

**Comment by danyj** [comment]
Now lets say I cant use a file and must go to DB , can I do a blank , none existing file option save vi ajax like


   fw_set_db_settings_option('menu_presets, ''{presetname:"presetdata....."")

and keep on adding to it ? ( this is the tricky one )

**Comment by moldcraft** [comment]
It will be wiped on next Theme Settings save.

I recommend to use a separate wp option, because presets data can grow and to prevent mysql error when update sql is too big.

```
update_option(
    'thz-presets:'. fw()->theme->manifest->get_id(),
    $presets, 
    false // https://codex.wordpress.org/Function_Reference/update_option#Parameters
);
```

**Comment by danyj** [comment]
was just busting on it , thnx much

**Comment by danyj** [comment]
OK how is this, 

on theme install run this for example 



	$thz_options_presets_option = 'thz_options_presets:'. fw()->theme->manifest->get_id();
	add_option($thz_options_presets_option,array(
	
		
		'topmenupreset' => array(
			'style1'  => array(
				'label' => 'Style 1',
				'canremove'=> false,
				'data'	=> '{style1data}'
				
			
			),
			'style2'=> array(
				'label' => 'Style 2',
				'canremove'=> false,
				'data'	=> '{style2data}'
				
			
			),
		),
		
		
		'iconboxespreset' => array(
			'style1'  => array(
				'label' => 'Style 1',
				'canremove'=> false,
				'data'	=> '{style1data}',
				
			
			),
			'style2'  => array(
				'label' => 'Style 2',
				'canremove'=> false,
				'data'	=> '{style2data}'
			
			),
			
			'stylebyuser'  => array(
				'label' => 'User custom style',
				'canremove'=> true,
				'data'	=> '{stylebyuserdata}'
			
			),
		)
		
	));

than use those to populate defaults , on create/update/delete   new preset add/remove to that option , you think this can fly ?

**Comment by danyj** [comment]
I think this is hand in replacement for files option and we still have presets , I can add hidden admin option to update the file with new presets, if permissions are right , otherwise tell admin  to do direct update if he/she wants more default presets

**Comment by moldcraft** [comment]
```php
$presets = array_merge(
    load_predefined_presets_from_theme_file(),
    $user_presets_from_db
);
```

?

**Comment by danyj** [comment]
they will all endup in  DB option , no reason to merge ,  on user preset save il do update_option combined with 

    fw_akg() 

to add to it

you see i forgot about one big thing and that is theme updates , so looks like I must stay away from files creation/edits and use DB instead , since everything is deleted on theme update and I dont want to create folder outside , check permissions and all the funny stuff. 

here better picture of what I mean , 


on    fw_init ,  I do this 


http://prntscr.com/8ohzj5

so now by default we have 2 predefined styles for the menu , user has option to save new preset , 
when he does that , I just update  DB option

    thz_options_presets:'. fw()->theme->manifest->get_id()

makes sense?

**Comment by danyj** [comment]
So much to think about , but the thing is that I must have this , imagine coding 
5 presets for notifications that have 25 options 
10 presets for icons boxes 30 options 
10 presets for special headings 20 options 
10 presets for buttons 15 options 


if I dont do this right , all those must use multi picker and you know how that  will endup

**Comment by danyj** [comment]
side one , does 

    fw_get_variables_from_file

for ok   with 

    ftpext

**Comment by danyj** [comment]
WORKS brother! :+1: 

o after_setup_theme  run function that reads preset file via 
    
    fw_get_variables_from_file

and gets default presets array , than creates the new presets option
on generate preset , update that option with new preset and re-render 


I set 

    define('FS_METHOD', 'ftpext')

and tested , everything looks fine 

if 

    get_filesystem_method

is returning direct , I show a button that will let you add new preset to the preset file and in DB , this way you can add-on presets to that file while you work . 

if you have any concerns please let me know. 

and again as always , thank you for this 24/7 brainstorming with me . I would have ran in lots of trouble if you did not pointed out the FTP issue.

**Comment by moldcraft** [comment]
> side one , does
>
> `fw_get_variables_from_file`
>
> for ok with
> 
> ftpext

`fw_get_variables_from_file` has nothing to do with `WP_Filesystem`. It uses `include/require`, not `fopen/fclose`

> on [`after_setup_theme`](https://codex.wordpress.org/Plugin_API/Action_Reference/after_setup_theme)

On every page load?

----

I prefer the solution used in [builder templates](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/33)

* There are predefined templates in theme file
* Theme updates can change/improve/add predefined templates
* Predefined templates can't be deleted (no delete button)
* User templates are saved in db and are shown first in templates list

So again

```php
$presets = array_merge(
    $user_presets_from_db,
    $theme_predefined_presets_from_file
);
```

**Comment by danyj** [comment]
>On every page load?

no , on first time , there is check for the option , if not there than it runs it


	function _thz_load_thz_presets(){
	    $thz_options_presets_option = 'thz_options_presets:'. fw()->theme->manifest->get_id();
		if ( !get_option( $thz_options_presets_option )  ) {
			
			$get_thz_options_presets = fw_get_variables_from_file(THZFW_PRESETS.'/thz-options-presets.php',array('thz_options_presets' => array()));
			add_option($thz_options_presets_option,$get_thz_options_presets);
			
		}
		
	}
	
	add_action('after_setup_theme', '_thz_load_thz_presets');


I see what you mean with merge now , it makes sense , why add predefined ones to DB at all , just add user ones and than merge  array from predefined and array from user DB.

I will probably go that route and dont have to create that option on  after_setup_theme  but create it when user saves the first time. 

But in both cases this is exact way it works


> There are predefined templates in theme file
Theme updates can change/improve/add predefined templates
Predefined templates can't be deleted (no delete button)
User templates are saved in db and are shown first in templates list

**Comment by danyj** [comment]
About DB  data limits ,  you think 100KB  is an issue , or what was the limit you were mentioning in other posts. I know there was something . 

You see way I did it now is 1  option with multi array  , 


example 


	$thz_options_templates['topmenutemplates']['style1'] = array(
			'label' 	=> 'Style 1',
			'canremove' => false,
			'data'		=> '{style1data}'
	);
	
	$thz_options_templates['topmenutemplates']['style2'] = array(
			'label' 	=> 'Style 2',
			'canremove' => false,
			'data'		=> '{style2data}'
	);
	
	$thz_options_templates['iconboxtemplates']['style1'] = array(
			'label' 	=> 'Style 1',
			'canremove' => false,
			'data'		=> '{style1data}'
	);
	
	$thz_options_templates['iconboxtemplates']['style2'] = array(
			'label' 	=> 'Style 2',
			'canremove' => false,
			'data'		=> '{style2data}'
	);

so not to hit limits should I leave it like that or rather make an option for each group like 


    thz_options_templates_topmenutemplates

    thz_options_templates_iconboxtemplates

**Comment by moldcraft** [comment]
I pretty sure it will be fine with one option.

*We hit limits when we have a lot of shortcodes with a lot of options (with multi-picker, you know that multipicker value is quite big). Then in that option, the same builder data is stored in 3 variants: original json, corrected json, wordpress shortcode notation.*

**Comment by danyj** [comment]
ok thnx bud!
