### ISSUE TITLE
Portfolio Problems

### ISSUE THREAD

**Issue by c0sm1n87** [ThemeFuse/Unyson#914]
Hello,

I have posted this on an old issue but it seems it wasn't solved there. I will try my luck with a new one.

I gave explanation here:

https://github.com/ThemeFuse/Unyson/issues/737#issuecomment-145984489

As a note, I didn't start from the scratch theme (i find it best to start "fresh" than remove/add) so maybe there is something I left out (i highly doubt it though).

PS: As duongancol mentioned, this is fixed by doing this

    $categories = get_terms( $taxonomy)
instead of this:

    $categories = get_terms( $taxonomy, $args );
 
Thanks in advance.

**Comment by duongancol** [comment]
I'm gald to help.
