### ISSUE TITLE
How to add  an option to existing fw.OptionsModal ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#915]
I have a condition check that if true I need to add one more option to my  fw.OptionsModal . 

I know I can modify options via   

    modal.set('values', { ... });

but how to add competently new option to  an  existing modal ?

this is what I mean 

	  var modal = new fw.OptionsModal({
	   title: 'Custom Title',
	   options: [
	       {'test1': {
	           'type': 'text',
	           'label': 'Test1'
	       }},
	       {'test2': {
	           'type': 'textarea',
	           'label': 'Test2'
	       }}
	   ],
	   values: {
	       'test1': 'Default1',
	       'test2': 'Default2'
	   }
	  });
	  
	  
	  // now here 
	  
	  if(something){
		  
		//  modal add new select option  type with 2 choices
		  
	  }

**Comment by moldcraft** [comment]
`title`, `options`, `values` are [backboneJs model attributes](http://backbonejs.org/#Model-constructor) they can be changed with `model_instance.set('ATTRIBUTE', 'VALUE')` then an event `change:ATTRIBUTE` will be fired, you can listen for it 

```javascript
model_instance.on('change:ATTRIBUTE', function(){...})
```

**Comment by danyj** [comment]
I did not mean this 

    modal.on('change:values', function(modal, values) {
            add option
    });

like adding to object wich works. 

	if(something){

			modaloptions[0]['sendtofile'] = {
				   'type': 'select',
				   'label': 'Select me',
				   'choices':{
						'choice1': 'I am chocie 1',
						'choice2': 'I am chocie 2',
					}
			};			
	}
I thought that I can do that with 
 modal.addsomething......  My "something"  comes from data attribute and I get it on page load , not on modal open so I know  the condition outcome before modal is ever opened. 

Thnx!

**Comment by moldcraft** [comment]
```javascript
var options = _.clone(
    // clone to not change by reference, else model.set() will not trigger 'change'
    modal.get('options')
);

options[0]['...'] = ...;

modal.set('options', options);

modal.open(); // trigger ajax to reRender modal options
```

**Comment by danyj** [comment]
ah ok ! thank you!
