### ISSUE TITLE
Problem activating Unyson

### ISSUE THREAD

**Issue by alemunpi** [ThemeFuse/Unyson#918]
I have a problem with Unyson, to activate these letters and symbols appears, that is?

��/�(P�LS�PLIM��KM�PwW��TH�L2���2SRR��5���/�(P�LS�PLIM��KM�PwW��TH�L2���2SRR��5���/�(P�LS�PLIM��KM�PwW��TH�L2���2SRR��5���/�(P�LS�PLIM��KM�PwW��TH�L2���2SRR��5���/�(P�LS�PLIM��KM�PwW��TH�L2���2SRR��5�
![problem](https://cloud.githubusercontent.com/assets/15026206/10357687/2c1580fc-6d42-11e5-959f-8fd607106ce3.PNG)

**Comment by moldcraft** [comment]
Hello,

How to reproduce this?

**Comment by alemunpi** [comment]
I dont understand your question, I bought a template, this template is made with Unyson plugin, when active the plugin, this error happens, when I disable the plugin, the error disappears.
attached some images.
Thanks.                            

Date: Wed, 7 Oct 2015 23:40:53 -0700

**Comment by alemunpi** [comment]
I dont understand your question, I bought a template, this template is made with Unyson plugin, when active the plugin, this error happens, when I disable the plugin, the error disappears.


Thanks.
 
![captura](https://cloud.githubusercontent.com/assets/15026206/10368453/7df5da16-6d92-11e5-8a36-dd893822e135.PNG)

**Comment by moldcraft** [comment]
Have you contacted the template creator?

I don't have that template and can't test this bug (on my side it works fine)

**Comment by alemunpi** [comment]
On this website you can find information
http://www.mojo-themes.com/item/construction-responsive-wordpress-theme/ 

Thank you very much for your help.

**Comment by alemunpi** [comment]
this is the email:  glacier.theme@gmail.com

**Comment by Ataurr** [comment]
@alemunpi  i think it will be better if you contact theme author here 
http://www.mojo-themes.com/item/construction-responsive-wordpress-theme/#mojo-comments
