### ISSUE TITLE
Unyson custom shortcode give "Undefined Index: shortcodename in /wp-content/plugins/unyson/framework/extensions/shortcodes/includes/coder/class-fw-ext-shortcodes-attr-coder-post-meta.php" ONLY when TinyMCE editor is in visual mode

### ISSUE THREAD

**Issue by sandromattei** [ThemeFuse/Unyson#919]
Hello and sorry for my English . I created a custom shortcode using Unyson but in the file error_log I see this error : PHP Notice: Undefined index : in shortcodename .../wp-content/plugins/unyson/framework/extensions/shortcodes/includes/coder/class-fw-ext-shortcodes-attr-coder-post-meta.php on line 45 .

This error occurs only when the editor tinimce wordpress is in visual mode .
when tinimce is in ' code ' this error does not occur .
can you help me?

**Comment by moldcraft** [comment]
Can you share your custom shortcode (the zip) ?

You can send it to `moldcraft[at]email.com`

**Comment by sandromattei** [comment]
I just sent the files . thank you

**Comment by sandromattei** [comment]
news?

**Comment by moldcraft** [comment]
Sorry, not yet. I will test it in a few hours.

**Comment by moldcraft** [comment]
I added the shortcodes in

```
{theme}/framework-customizations/extensions/shortcodes/shortcodes/
```

and I get [these warnings](https://static.md/a5b002d8a063b27ccf0a436254ec394f.png)

To see the problems add `fw_print()` in

```php
foreach($approfondimenti_aree as $approfondimenti_area){
	fw_print($approfondimenti_area);
```

```php
foreach($news_categories as $news_category){
	fw_print($news_category);
```

```php
foreach($news_aree as $news_area){
	fw_print($news_area);
```

I haven't tested more because it seems that the shortcodes are buggy and not finished.

Please send them again via email when you will fix the warnings and I will continue investigation.

**Comment by sandromattei** [comment]
Those are the custom taxonomies and is correct.
This is the value of postmeta "fw-shortcode-default-values" when I save the post with TinyMCE in "code view":
{"category_banner":{"id":"b65acf7d2bbea6766350f1cb801f01f1","banner_image":[],"banner_link":"http:\/\/","banner_bg":"#FF0000","target_link":"self","banner_text":"","banner_alt":"no","text_align":"text-left","text_position":"align-top","text_width":"col-xs-12","text_float":"nofloat"},"category_news":{"id":"fd69bd5236fd8ac7e8caa4c8a0e01514","news_category":[],"news_area":[],"news_number":"5"},"category_approfondimenti":{"id":"bb7df4fa737761ed12dba4b11c09a648","approfondimenti_area":[],"approfondimenti_number":"5"}},
while this is the value when I save the post with TinyMCE in "visual":
{"category_banner":{"id":"0b176ce9cacd4afc517278c49343907d","banner_image":[],"banner_link":"http:\/\/","banner_bg":"#FF0000","target_link":"self","banner_text":"","banner_alt":"no","text_align":"text-left","text_position":"align-top","text_width":"col-xs-12","text_float":"nofloat"}}

**Comment by moldcraft** [comment]
> Those are the custom taxonomies and is correct.

So you didn't gave me a working code for testing.

Please send again the (working) shortcodes and I will test them.

**Comment by sandromattei** [comment]
I found the problem .
It seems that the cause is the plugin " TinyMCE Advanced ."
The problem occurs when active the " Stop removing the < p > and <br /> tags When saving and show them in the Text editor " ;
You have a solution ?
Thank you!!

**Comment by moldcraft** [comment]
So how exactly to reproduce this?

**Comment by sandromattei** [comment]
Install the TinyMCE Advanced plugin and in his options, check the "Stop removing the <p> and <br /> tags when saving and show them in the Text editor" option.
then, in a page, i put 3 different shortcodes ( i put each shortcode in a '<div>' tag and not in a '<p>' tag );
now, set the tinymce editor in VISUAL mode and save the page.
load page in frontend and check the error_log.
to me it returns these notices:
[14-Oct-2015 06:51:09 UTC] PHP Notice:  Undefined index: category_news in ........./class-fw-ext-shortcodes-attr-coder-post-meta.php on line 45
[14-Oct-2015 06:51:09 UTC] PHP Notice:  Undefined index: category_approfondimenti in ....../class-fw-ext-shortcodes-attr-coder-post-meta.php on line 45

if you set the editor in CODE mode and save, the error not occured

**Comment by sandromattei** [comment]
Install the TinyMCE Advanced plugin and in his options, check the "Stop removing the 'p' and 'br' tags when saving and show them in the Text editor" option.
then, in a page, i put 3 different shortcodes ( i put each shortcode in a 'div' tag and not in a 'p' tag );
now, set the tinymce editor in VISUAL mode and save the page.
load page in frontend and check the error_log.
to me it returns these notices:
[14-Oct-2015 06:51:09 UTC] PHP Notice:  Undefined index: category_news in ........./class-fw-ext-shortcodes-attr-coder-post-meta.php on line 45
[14-Oct-2015 06:51:09 UTC] PHP Notice:  Undefined index: category_approfondimenti in ....../class-fw-ext-shortcodes-attr-coder-post-meta.php on line 45

if you set the editor in CODE mode and save, the error not occured

**Comment by sandromattei** [comment]
here is the problem in the tiniMCE init configuration.
$init['wpautop'] = false;

but i need it
