### ISSUE TITLE
Disable Extension

### ISSUE THREAD

**Issue by braginteractive** [ThemeFuse/Unyson#92]
Is there a way to disable the "Available Extensions" when the plugin is install. 

For example:
The theme the plugin is install for a theme that already has a Portfolio custom post type, so the Portfolio Unyson extension is not needed in this case. Is there a way to disable it from showing in the "Available Extensions" list or say something like "non-compatible"?  

Just don't want the theme user thinking they need to install the Portfolio extension for their portfolio section to work. Just less confusion for them. 

In the past there was a blacklist, but I don't see anything about it now.

**Comment by braginteractive** [comment]
So I noticed if you create a manifest file for an extension you can set it to not display. 

````
<?php if (!defined('FW')) die('Forbidden');
$manifest = array(
	'display'       => false,
);
````

**Comment by moldcraft** [comment]
@braginteractive By default it's not displayed (false). If you want to display it, set that parameter to true.
