### ISSUE TITLE
is there a way to detect very first time admin fw theme settings load

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#920]
I need js hook that will tell me if this is very first load. Curently i am forecd to run ajax, check db for fw settings and return true/false  

Is there anything faster than this that does not involve ajax?

**Comment by danyj** [comment]
I need to do something  in js  before the theme settings  have been saved the first time.

**Comment by moldcraft** [comment]
Reset Settings Options > Refresh

This case also is treated as "very first load"

**Comment by danyj** [comment]
Not i mean you install theme and for very first time go in settings. Now i need to execute script and never again. So i need hook to tell me that this was first time settings view.

**Comment by danyj** [comment]
I need to trigger save on first time load that is the thing

**Comment by danyj** [comment]
But only once and never agin

**Comment by moldcraft** [comment]
We don't have the "very first time hook" detector.

Use [this action](https://github.com/ThemeFuse/Unyson/commit/79524af41243b38e45bb8f216cce6e2191c14317) to print your `<script>...</script>` and do your own detection.

**Comment by danyj** [comment]
ok , thnx, you see im trying not to do this , but looks  like  this is the only way 

	public static function _action_ajax_first_load() {
		
		if(!is_admin() && !isset( $_POST['thz_first_load']) ) return;
		
		$firstload 		= false;
		$not_saved 		= get_option( 'fw_theme_settings_options:'.fw()->theme->manifest->get_id() );
		
		if(empty($not_saved)){
			$firstload = true;
		}
			
		wp_send_json_success( array(
			'firstload' => $firstload 
		));	
		
	}

**Comment by danyj** [comment]
but with that I have to run it every tome admin enters the settings

**Comment by moldcraft** [comment]
This is what I meant

```php
add_action('fw_settings_form_footer', '_action_theme_settings_form_footer');
function _action_theme_settings_form_footer() {
    if (!is_admin() && !isset( $_POST['thz_first_load']) ) return;

    $firstload      = false;
    $not_saved      = get_option( 'fw_theme_settings_options:'.fw()->theme->manifest->get_id() );

    if (empty($not_saved)) {
        $firstload = true;
    }

    echo '<script>var _thz_first_load = '. ($firstload ? 'true' : 'false') .';</script>';
}
```

then use that variable in js instead of doing ajax

**Comment by danyj** [comment]
nothing , is not coming out 

added in hooks 


add_action('fw_settings_form_footer', '_action_theme_settings_form_footer');
function _action_theme_settings_form_footer() {

    $firstload      = false;
    $not_saved      = get_option( 'fw_theme_settings_options:'.fw()->theme->manifest->get_id() );

    if (empty($not_saved)) {
        $firstload = true;
    }

    echo '<script>var _thz_first_load = '. ($firstload ? 'true' : 'false') .';</script>';
}

**Comment by moldcraft** [comment]
Do you have the latest dev version of Unyson. I added that action when I wrote the comment.

**Comment by danyj** [comment]
you did not say that :) no , will get it now

**Comment by danyj** [comment]
thnx bud but I cant use it , is not chanmged on form reset , it stays as is and changes on page refresh.

**Comment by moldcraft** [comment]
Listen form reset event and do ajax to update that variable?

**Comment by danyj** [comment]
im doing it now , might use $.when instead. this is a very tricky one

**Comment by moldcraft** [comment]
There should be an `fwEvents` custom event fired on form reset. If not, I will add it (tomorrow)

**Comment by danyj** [comment]
no stress we will find the way. thnx .
