### ISSUE TITLE
Option to hide "Content Elements"?

### ISSUE THREAD

**Issue by Krystus** [ThemeFuse/Unyson#921]
Is there an option to hide some of the "Content Elements"? My team only uses a few of them. Is there a way or a CSS trick to hide them?

![screenshot-2](https://cloud.githubusercontent.com/assets/15039636/10379206/7c017406-6e0d-11e5-9650-a1813d453e7a.jpg)

**Comment by albertso** [comment]
`fw_ext_shortcodes_disable_shortcodes` filter

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/1

**Comment by llemurya** [comment]
@Krystus if the answer of @albertso helped you please close the issue.

**Comment by Krystus** [comment]
Bug? Something is wrong with Templates button.

$to_disable[] = 'table'; makes a difference.

![toto](https://cloud.githubusercontent.com/assets/15039636/10406098/dabcd5b4-6edd-11e5-838a-601fe3292a49.png)

@albertso thanks.

**Comment by albertso** [comment]
@Krystus u welcome. I don't know why the link moved there, have you inspected the html?
