### ISSUE TITLE
Unyson + Bootstrap + optimization?

### ISSUE THREAD

**Issue by Krystus** [ThemeFuse/Unyson#922]
I am an optimization freak. For my websites I mostly use Bootstrap. Bootstrap defines the header/footer using functions like nav, popover or grid. However, I think a lot of data is duplicated because of CSS from Unyson. Is there any special Bootstrap build which cooperates well with Unyson and retains good optimisation?

**Comment by moldcraft** [comment]
[This css](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/static/css/frontend-grid.css) is [registered here](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/e07cd70ea1ea8a0179078ba6be4d616c9bc732c5/static.php#L4-L6) and it is included enqueued [here](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/3f66c2d2b30fd2e4b1d29ab12ca77e315af23fae/static.php#L7), [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/2a51926f4ccf549f253df2b0726a422019581fa7/shortcodes/column/static.php#L3), [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/2a51926f4ccf549f253df2b0726a422019581fa7/shortcodes/row/static.php#L3) and [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/2a51926f4ccf549f253df2b0726a422019581fa7/shortcodes/section/static.php#L3). 

You can overwrite those `static.php` files in theme (so the original ones will not be executed) and do not register/enqueue that style and include your own (note, also you will need to overwrite views to remove prefix from classes `fw-{bootstrap_class}`). 

For e.g. copy

```
unyson/framework/extensions/shortcodes/section/static.php
```

to

```
{theme}/framework-customizations/extensions/shortcodes/section/static.php
```

and change it however you want.
