### ISSUE TITLE
Addable Popup with thumbnail (initialization problem)

### ISSUE THREAD

**Issue by albertso** [ThemeFuse/Unyson#923]
Hi,

I'm displaying thumbnails in an addable popup option (could also be addable box), like this:
![image](https://cloud.githubusercontent.com/assets/1270475/10380172/8e272df6-6e12-11e5-86d2-2622c7bf0961.png)

As you see it works fine when the image is selected after page load with the wp.media frame. It doesn't show the images again when the page is loaded after being saved:

![image](https://cloud.githubusercontent.com/assets/1270475/10380195/b4980fa0-6e12-11e5-8b16-3c53e924e630.png)

If I enter the popup and _change_ the image, it does update correctly, but only if I change it with the media frame. I've tried this in page and shortcode options. The same behaviour occurs.

This is the option:

    $options = array(
        'backgrounds' => array(
            'type'          => 'addable-popup',
            'label'         => __('Background(s)', 'fw'),
            'desc'          => __('Add a background to this section. Add more backgrounds to create a slideshow.', 'fw'),
            'template'      => ''.
                '<div class="fw-row">'.
                '{{ if ("custom"==image.type && image.custom) { }}'.
                    '{{ if (image.custom) { }}'.
                        '<div class="fw-col-xs-2">'.
                            '{{ if ("custom"==image.type) { }}'.
                                '{{ console.log(image.custom) }}'. // returns attachment_id
                                '{{ console.log(wp.media.attachment(image.custom)) }}'. // returns attachment object
                                '{{ if (image.custom) { }}'. //
                                    '{{ if (wp.media.attachment(image.custom).attributes.sizes) { }}'.
                                        '<img class="item-thumb" src="{{-wp.media.attachment(image.custom).attributes.sizes.thumbnail.url}}"> '.
                                    '{{ } }}'.
                                '{{ } }}'.
                            '{{ } else if ("predefined"==image.type) { }}'.
                                    '<img class="item-thumb" src="{{-image.data.icon}}"> '.
                            '{{ } }}'.
                        '</div>'.
                    '{{ } }}'.
                '{{ } }}'.
                // ...
                '</div>'.
                '',
            'size'          => 'medium',
            'limit'         => 10,
            'popup-options' => array(
                'image'		=> array(
                    'type' => 'background-image',
                    'label' => __('Background Image', 'fw'),
                    'images_only' => true,
                ),
                // ...
            ),
        ),
    );

This is the console log in Chrome. See, the first time I look in the object returned, the attributes are empty. After changing the image, the object in the log does have attributes.

![addable_template_console](https://cloud.githubusercontent.com/assets/1270475/10380554/cea470da-6e14-11e5-9596-2a388a660eb7.JPG)

Looks like some kind of initialization of wp.media is missing when addable options have have interior options with images. Or am I missing something?

I thought I can get and send the values in php with localize script, but that would require looking at page options and scanning the page content looking for shortcodes that have images in addable popups. The same for options in customizer. Any advice? Thanks!

**Comment by llemurya** [comment]
@albertso please watch this [video](https://youtu.be/ORVvGDBWZyw). Hope this helps. I am waiting for your response.
```javacript
/* Code from video */
wp.media.query().more().done(function(){
console.log('RESPONSE',wp.media.attachment('your-id').toJSON());
})
```

**Comment by danyj** [comment]
try this template  exzample for a sec ,  worked fine for me here  in builder https://github.com/ThemeFuse/Unyson/issues/759#issuecomment-127020295

 did you try with   
    
    mage.url 

instead ?

**Comment by danyj** [comment]
works perfectly fine for me , 
http://prntscr.com/8pfilc

same thing you have , do  this 

	{{ console.log(image);if (image) { }} :  <img  style=\'width:100px;height:auto;\' src=\'{{-image.url }}\' /> {{ } }}

adding , saving , changing , removing , works fine

**Comment by danyj** [comment]
I see now , you are looking for the thumbnail instead of the actual image thus the wp.media  fiddle ,

**Comment by albertso** [comment]
@danyj, Hey yes, I'm trying to get the thumbnail (or any registered size) from the attachment instead of the full size. The thing is it almost works, at least after wp frame has been opened once.

@llemurya I followed your video and now I manage to see the image object in the console.log, on a saved page, but I still cannot print the same data to html. The image src appears blank.

I don't see how I should include the code you gave me in the $option['template']. Should I place it at the top, or nest my code in there? Should I use some kind of callback? I can't work it out. I'm awful at js and and asynchronous code...

Any advice on how to structure it to include @llemurya's code?

**Comment by llemurya** [comment]
@albertso yesterday i added the `_context` parameter in the addable-popup template that will be available in the next version of the Unyson, please watch [this video](https://youtu.be/GxnnN9r6s_M) I hope it solve your problem, please give us a feedback.I am waiting for you response.
Below is the code that you must paste in the `template` key.
```javascript
var image = "<img>";
print(image);
wp.media.query().more().done(function () {
	attachment = wp.media.attachment('your_attachment_id').toJSON();
	setTimeout(function () {
		_context.find("img").attr("src", attachment.url);
	}, 500);
});
```

**Comment by llemurya** [comment]
Please see this commit https://github.com/ThemeFuse/Unyson/commit/8c8a0ff995ea8f3295f858308a93b895511ba4bb and add it mannualy to test the code. In the next version it will be in production.

**Comment by llemurya** [comment]
@albertso please write an answer in order to know if it helps you and to fix the issue. I am waiting for your response.Thanks!

**Comment by albertso** [comment]
Hey, sorry for the late response.

I managed to do what you show in the video already, thanks for helping out.
I even have the data storing correct, I use the images in the frontend no problem.

The problem comes __after saving the post__. Have you tried saving that page, and opening again?
Do the __saved boxes__ display the images?

New boxes you add work, but the __stored ones don't show the thumbnail__.

If media frame has not been launched before drawing the boxes, wp.media doesn't return a complete attachment object (with all the attributes.sizes and data)

In my case, I have the addable-box in a shortcode, so the script is run when I click to edit that shortcode and the modal opens, therefore I can open the media frame __before that__, so when I click on the shortcode, the thumbnails in the addable-box show ok. I cannot do that for page-options (because the script is run on page load, and media frame has not run at that moment)

Even if I use `wp.media.query().more().done()` as you suggest, _it doesn't work if the media frame wasn't open before_ rendering the option. Even using with the Timeout.

8c8a0ff doesn't solve it either...

There's some kind of initialization missing. I don't know what happens exactly when media frame opens (in the many cases it does), but when it does, something must "activate", that allows querying wp.media to get attachment data

As I say, my code works (and worked) perfectly like yours. It's in the situation I describe above, (after page save), that __stored__ boxes don't ___display___ as expected.

Functionality-wise, it works (that's why I deprioritized this issue)

**Comment by albertso** [comment]
Btw, thanks for looking into this, and all the great work

It's not the biggest issue, but it bugs me 'cause solution seems almost there,

**Comment by llemurya** [comment]
@albertso it works after saving, please see this [video](https://youtu.be/iE4Gm32gSm8) as a proof.I make `wp.media.query().more().done()` because when the `promise` is resolved it gets the correct attachments list .

**Comment by albertso** [comment]
Ok I see, then I'm doing something wrong.
I'll let you know when I'm done, but you can close the issue.
Thanks for the patience!

**Comment by danyj** [comment]
@albertso , bud , do you mind sharing the template snippet for thumbs ? I am doing something similar and need to extract them. thnx!

**Comment by danyj** [comment]
what I noticed is that it works on some images and not on the others, very strange ,

**Comment by llemurya** [comment]
@danyj in this comment is the solution https://github.com/ThemeFuse/Unyson/issues/923#issuecomment-148647851

**Comment by danyj** [comment]
@llemurya  hey bud , that is exactly what I am using ,   and  some images dont display 
![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/13188423/c76de19c-d751-11e5-8a3b-d2085bb2da3a.jpg)


I added console log after attachment 

						wp.media.query().more().done(function () {
							var aid = medsrc.attachment_id;
							var attachment = wp.media.attachment(aid).toJSON();
							
							console.log(attachment);

**Comment by danyj** [comment]
@llemurya  , here is the full snipp, 


	wp.media.query().more().done(function () {
		var aid = medsrc.attachment_id;
		var attachment = wp.media.attachment(aid).toJSON();
		
		console.log(attachment);
		
		var imghtml ="";
		if(attachment.sizes != undefined && attachment.sizes.thumbnail != undefined){
			var imgsrc = attachment.sizes.thumbnail.url;
			var imghtml = \'<img id="thzpopthumb\'+aid+\'" src="\'+imgsrc+\'" /> \';
		}
		var imgcontainer = \'<div class="thz-popthumb">\'+imghtml+\'</div> \';
		_context.append(imgcontainer); 
	});


I also tried with very long timeouts but same thing , also checked db that image has all attributes and it does

**Comment by danyj** [comment]
tested your exact code with specific attachment id , same 


	wp.media.query().more().done(function () {
		attachment = wp.media.attachment(5482).toJSON();
		setTimeout(function () {
			console.log(attachment);
		}, 500);
	});
![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/13188961/f2a3a01a-d754-11e5-82ed-93827ac7de2e.jpg)

and is missing all atrr

**Comment by albertso** [comment]
Hey!  I finally got it to work fiddling with @llemurya 's code.

The purpose of this is to use thumbnail-sized versions of images, instead of full sizes.

    $options = array(
        'items' => array(
            'type' => 'addable-popup',
            'label' => __('Items', 'fw'),            
            'template'    => '{{'.
                'if (typeof multimedia != "undefined") {
                    if ("selected" in multimedia) {
                        if (typeof multimedia.selected != "undefined") {
                            if (multimedia.selected in multimedia) {
                                var m = multimedia[ multimedia.selected ];
                                switch (multimedia.selected) {
                                    case "image" : // Attention down here
                                        var attachment = wp.media.attachment(m.src.attachment_id)
                                        var image = "<img>";
                                        print(image);
                                        wp.media.query().more().done(function () {
                                            setTimeout(function (){
                                                if (typeof attachment.attributes != "undefined") {
                                                    if (typeof attachment.attributes.sizes != "undefined") {
                                                        _context.find("img").attr("src", attachment.attributes.sizes.thumbnail.url);
                                                    }
                                                }
                                            }, 50);
                                        });
                                    break;
                                    // other cases ...
                                }
                            }
                        }
                    }
                } }}',
            'popup-options' => array(
                'multimedia'     => array( // follow slider structure
                    'type'         => 'multi-picker',
                    'label'        => false,
                    'picker'       => array(
                        'selected' => array(
                            'label' => _( 'Type', 'fw' ),
                            'type'  => 'select',
                            'value' => '',
                            'choices' => array(
                                'image' => __('Image', 'fw'),
                            ),
                        ),
                    ),
                    'choices' => array(
                        'image' => array(
                            'src' => array(
                                'label' => false,
                                'type' => 'upload',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    );

There is a slight delay before the thumbnails appear, but they appear now.
And I wonder if there is a better way to access object properties safely without doing:

        if ("selected" in multimedia) {
            if (typeof multimedia.selected != "undefined") {
                // multimedia.selected

I haven't done much testing, but it seems to work so far.
If there's nothing else to add, this may not be an issue any more.

Thanks for the help!

BTW Great work @moldcraft, @andreiglingeanu, @thednp, @danyj, #1807 shortcodes in wp-editor!! Cool :+1:

**Comment by andreiglingeanu** [comment]
@albertso Refer to [this](http://wordpress.stackexchange.com/questions/181000/get-attachment-image-info-in-js/237574#237574) as a reliable way of preloading your attachments. You should really do this outside of the template - template rendering should be sync (without any timeouts of AJAX request) or you'll get into trouble someday..

**Comment by danyj** [comment]
@everyone , dont use this snippet , 

@albertso , @llemurya , @andreiglingeanu  test   by cloising and openenig the options popup 10 times , 

each time the loads get slower and it comes to the point to kill your browser completely

**Comment by danyj** [comment]
@andreiglingeanu  can your reactive options help here now? 

we need thumbnail image from popup , all we get from upload is  attach ID and big image url , 

can we somehow get thumb url with reactive options help? 

` wp.media.query().more().done`


kills site if popup is opened multiple times like when you build site in preview mode and go back and forth

**Comment by andreiglingeanu** [comment]
@danyj What are you trying to achieve?

Reactive options are, in the nutshell, a way to get the value from an existing option type without touching the server (most of the time).

If you have the element of the option type, do that:

```javascript
fw.options.getValueForEl(document.querySelector('.selector-for-your-option'))
  .then(function (result) {
    console.log(result.value); // the actual value
    console.log(result.optionDescriptor); // more meta data about the option you queried
  });
```

This all happens, most of the times, without an AJAX request and should work _VERY_ quickly.

That's enough of a teaser try this out and you'll be amazed of the possibilities it gives :)

**Comment by andreiglingeanu** [comment]
@danyj Also, please try the new (#2757) `icon-v2` option type, which also does `wp.media.query()`. Does it looks like freezing the website when you have a lot of images there and you quickly open and close the modal? I think there might be needed to perform a check [before that](https://github.com/ThemeFuse/Unyson/blob/cbba989165dda7b190feffb02cfd90a13af3c06c/framework/includes/option-types/icon-v2/static/js/icon-picker-v2.js#L475-L493) in order to avoid the un-needed `wp.media.query()` call. What do you think?

**Comment by danyj** [comment]
@andreiglingeanu   I tried fetch but the attachment info is not present thus we used media.done

used your stack post yesterday and could not make it work because of that, trying again


this is template that is slowing down and is the loop, I tried outside of each or doing i t once via function but same thing , it eventualy slows everything down 


				var imagestitle = \'</div><b class="thz-popup-media-type-images">Mulitple images</b>\';
				setTimeout(function () {
					_context.append(imagestitle);
				}, 100);
				jQuery.each(medsrc, function( index, img ) {
					wp.media.query().more().done(function () {
						var aid = parseInt ( img.attachment_id );
						var attachment = wp.media.attachment(aid).toJSON();
						var imghtml ="";
						if(attachment.sizes != undefined && attachment.sizes.thumbnail != undefined){
							var imgsrc = attachment.sizes.thumbnail.url;
							var imghtml = \'<img src="\'+imgsrc+\'" />\';
						}
						var imgcontainer = \'<div id="thzpopthumb\'+aid+\'" class="thz-popthumb">\'+imghtml+\'</div> \';
						_context.append(imgcontainer);
					});
				});

**Comment by thednp** [comment]
Hey I found out some of you mentioned my name on this issue and I thank you because I've found a great new development. Looking forward to the outcome.

**Comment by danyj** [comment]
this one is not working in templates at all , I ended up creating function to "get" thumb size from the url we have ,

```
	/**
	* Get specific image size url from original image url
	* @original //image_url.ext
	* @size 80x80  
	* returns string
	*/		

	thz.get_image_size_url = function(original,size) {
		
		var re = new RegExp("(.+)\\.(gif|png|jpg|jpeg|svg)", "g");
		return original.replace(re, "$1-"+size+".$2");
		
	}
```

 all ajax request within popup template fail soner or later and cause havoc on the server if within a loop

if we would have full thumb url accessible from upload that would be way to go but this is not ok.
