### ISSUE TITLE
Are we doing ajax async false somewhere in edit page ? 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#928]
I see this on edit page screen refresh 

http://prntscr.com/8q3rk4

which means that some $.ajax is doing 

    'async': false 

and the page load must wait for it. 

Is this a must and are we (Unyson)  doing it at all?  If we can go without it it would speed up the edit page load.

**Comment by moldcraft** [comment]
I did a search in all files and found `async:false` only [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/557989ccf30e0709f448a8b9d1797f06a7ade356/shortcodes/calendar/static/js), but those scripts are enqueued in frontend (I don't know why it was set to `false` that is not my code, and there are no comments).
