### ISSUE TITLE
"Undefined option type:" after save page 

### ISSUE THREAD

**Issue by Krystus** [ThemeFuse/Unyson#929]
Always after edition of content element table I get "Undefined option type:" error. What can be wrong?

![zrzut ekranu 2015-10-11 o 18 10 47](https://cloud.githubusercontent.com/assets/15039636/10417677/25b3f3dc-7045-11e5-93ee-518f3b633526.png)

**Comment by moldcraft** [comment]
We need a way to reproduce this.

Also you can try to report this to theme creator (if you bought the theme).

**Comment by Krystus** [comment]
Clean WordPress installation + clean Plugin with Page Builder.

**Comment by moldcraft** [comment]
> my own simple theme

Maybe the problem is there?

**Comment by Krystus** [comment]
It appears after $to_disable[] = 'button'; in shortcodes/hooks.php!

```
<?php if (!defined('FW')) die('Forbidden');

/** @internal */
function _filter_disable_default_shortcodes($to_disable)
{
        // disable the shortcodes you want like this
        $to_disable[] = 'calendar';
        $to_disable[] = 'call_to_action';
        $to_disable[] = 'accordion';
        $to_disable[] = 'button';
        $to_disable[] = 'contact_form';
        $to_disable[] = 'divider';
        $to_disable[] = 'icon';
        $to_disable[] = 'icon_box';
        $to_disable[] = 'map';
        $to_disable[] = 'notification';
        $to_disable[] = 'special_heading';
        //$to_disable[] = 'table';
        $to_disable[] = 'tabs';
        $to_disable[] = 'team_member';
        $to_disable[] = 'testimonials';
        //$to_disable[] = 'text_block';
        $to_disable[] = 'widget_area';
        return $to_disable;
}
add_filter('fw_ext_shortcodes_disable_shortcodes', '_filter_disable_default_shortcodes');
```

**Comment by moldcraft** [comment]
Thank you for details.

We will take a look at this later, sorry (don't have time for this at the moment)

**Comment by eightnight** [comment]
Hi,
Same problem here
`Undefined option type: `
after editing a table elements within the visual builder in a project page with the backend editor.

Running, latest version of WP, Woffice, Unyson on a clean and fresh install.

**Comment by moldcraft** [comment]
@2FWebd Can you reproduce this with Woffice?

**Comment by 2Fwebd** [comment]
Hi @moldcraft and @eightnight !

I've just tested on our dev site and I can create/edit/delete any Table on a Project post edit page. No error. 

Do you have the same issue on any other post type ? Blog, Wiki or Page ? 

If you have a ticket open about that on our Ticksy Helpdesk, please let me know @eightnight so we can try it directly. 

Cheers, 

2F

**Comment by moldcraft** [comment]
It was fixed https://github.com/ThemeFuse/Unyson/issues/2056#issuecomment-249943593
