### ISSUE TITLE
What is faster  fw()->theme->get_settings_options() or fw_get_variables_from_file ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#930]
I need default theme options array , 
which one of these 2 is faster 

from DB or fw_get_variables_from_file

**Comment by moldcraft** [comment]
> from DB

which function do you use for that?

> or fw_get_variables_from_file (fw()->theme->get_settings_options())

same thing

**Comment by danyj** [comment]
now you lost me 

I tought  

    fw()->theme->get_settings_options() 

is getting options from DB  if they are there and if not from  theme/options/settings.php


you mean to say that  is always  theme/options/settings.php ?

or did I mix , ah yes I think I mixed up 

    fw_get_db_settings_option


so to sum up this is always the file reference 


        fw()->theme->get_settings_options()

**Comment by moldcraft** [comment]
`fw()->theme->get_..._options()` loads them from `{theme}/framework-customizations/theme/options/...`

Why would we store options array in database? We store in database only `option_id => option_value`

----

[This code](https://github.com/ThemeFuse/Unyson/blob/3f0a5b7b68ada259ce0ebba5a883df26a880686f/framework/helpers/database.php#L37-L41) is used to extract options default values

**Comment by danyj** [comment]
I am not storing anything , just pulling options array from it.  but was confused and thought that  get_settings_options is looking in DB . Makes sense now

**Comment by danyj** [comment]
should have looked here https://github.com/ThemeFuse/Unyson/blob/7b3c89f16228e5e739fe272cf6bd899e75d459c3/framework/core/components/theme.php#L79 before asking. thnx bud

**Comment by danyj** [comment]
To explain , what I am after is this 

I need   those default arrays for everything , inside theme/options and    extensions/shortcodes

so for anything from 

    framework_path/theme/options    folder   

 I can use 


    fw()->theme->get_settings_options() 

but for 

    framework_path/theme//extensions/shortcodes/shortcodes/SHORTCODENAME/options.php

I need my own  function for it 

so we have no native  way to pull options from shortcode 


you see this https://github.com/ThemeFuse/Unyson/issues/898#issuecomment-144940967

 is forcing me to place files in different dir , but I dont need or want that , I just want to get options from 



    framework_path\extensions\shortcodes\shortcodes\divider\options.php

for example, 

If there is native function other than fw_get_variables_from_file  please let me know

**Comment by moldcraft** [comment]
* https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/65e595ae84684b330a4161cef4afc1df538a7ddc/includes/class-fw-shortcode.php#L115
* https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/65e595ae84684b330a4161cef4afc1df538a7ddc/class-fw-extension-shortcodes.php#L21

Usage

```php
if ($shortcode = fw_ext('shortcodes')->get_shortcode('SHORTCODE_NAME')) {
    $options = $shortcode->get_options()
}
```

**Comment by danyj** [comment]
:100:

**Comment by danyj** [comment]
I am testing sub options file call  and if used inside the shortcode/options.php  it creates  never ending recursion

```

fw_ext('shortcodes')->get_shortcode('posts')->get_options('style_settings')
```

where this if used in extension/media/ extensions/slider/slick-full/options/options.php   works

    fw_ext('slick-full')->get_options('styling')
