### ISSUE TITLE
Is there something like fw_locate_theme_path  but for framework dir ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#931]
I am using 

    fw_get_template_customizations_directory

for my paths but  looks to me that is not checking the child theme for overrides. Or am I mistaking ?
https://github.com/ThemeFuse/Unyson/blob/8ea45f9aea95be4ffd677baff77bd438dea13f6c/framework/bootstrap-helpers.php#L73

**Comment by moldcraft** [comment]
Like the function name says `template` it means [parent theme](https://codex.wordpress.org/Function_Reference/get_template_directory), `stylesheet` means [child theme](https://codex.wordpress.org/Function_Reference/get_stylesheet_directory).

> Is there something like fw_locate_theme_path but for framework dir ?

no

**Comment by danyj** [comment]
Hm well. This is a bummer . By so many bootstrap paths we dont have this. We can override parent-theme shortcodes and everything else but we have no reference to child theme framework overrides path
https://github.com/ThemeFuse/Scratch-Theme/tree/master/scratch-child/framework-customizations/extensions/shortcodes/shortcodes/demo-two

and in order to make it we have to take this in count also 

    fw_framework_customizations_dir_rel_path

this returns plugin framework dir 
https://github.com/ThemeFuse/Unyson/blob/8ea45f9aea95be4ffd677baff77bd438dea13f6c/framework/bootstrap-helpers.php#L106

this returns only rel path to theme framework override 

    fw_get_framework_customizations_dir_rel_path



and none is checking back and fort.

and if you do what Scratch child did  which is override , parent-theme framework customization , you get wrong path  with  

      fw_get_framework_customizations_dir_rel_path

**Comment by danyj** [comment]
I think that   

    fw_get_template_customizations_directory

should check is_child_theme()

**Comment by moldcraft** [comment]
> We can override parent-theme shortcodes and everything else but we have no reference to child theme framework overrides path

I don't understand the sentence. You tried to overwrite an options/view file in child theme and it didn't worked?

> `fw_get_template_customizations_directory` should check is_child_theme()

Again, in function name is `template`, that means it is related to parent theme only (it is not `locate`).

----

We don't need to allow to overwrite any file in framework, only specific files (for e.g. extension views,config), that's why we don't have such function.

Why you need that function?

> if you do what Scratch child did which is override , parent-theme framework customization , you get wrong path with

Sorry, I don't understand. Can you give an example?

**Comment by danyj** [comment]
You allow more than views , you allow options.php overrdies 
https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-child/framework-customizations/extensions/shortcodes/shortcodes/demo-two/options.php


now in my option type I rely on those defaults   and use 

    fw_get_template_customizations_directory

to read them 

now here is  a bad thing for me ,    I read  via the function above 


    parent-theme/inc/framework/extensions/extensions/shortcodes/divider/options.php 

user makes child theme and wants to add another option to divider , so he/she does  this

     child-theme/inc/framework/extensions/extensions/shortcodes/divider/options.php 

now I am reading wrong options.php  with 

    fw_get_template_customizations_directory

since I am still looking at   parent-theme but options displayed are from child-theme

**Comment by danyj** [comment]
here I broke the function in peaces to show you what I mean 


		$templatedefaults = 'divider/options';
		$path = fw_get_template_customizations_directory('/extensions/shortcodes/shortcodes/'.$templatedefaults);	

		$defaultdata	= fw_get_variables_from_file($path.'.php',array('options' => array()));
		$options 		= $defaultdata['options'];

now when they override my shortcode , I have wrong options

**Comment by moldcraft** [comment]
First check if the files exists in child theme, if not, load from parent.

```
if (!file_exists($path = fw_get_stylesheet_customizations_directory('/...'))) {
    $path = fw_get_template_customizations_directory('/...');
}
```

**Comment by danyj** [comment]
thank you. 

Got everything working with 


	 /**
	 * Return file path , check child-theme
	 */		
	public static function thz_get_file_path($file) {
		
		if(!$file) return;
		
		if (!file_exists($file_path = fw_get_stylesheet_customizations_directory($file.'.php'))) {
			$file_path = fw_get_template_customizations_directory($file.'.php');
		}	
		
		return 	$file_path;
		
	}

**Comment by thednp** [comment]
I want to customize some core extensions, but I want to include them into plugins, so can I set the `framework-customizations` folder to be inside  plugin?

**Comment by moldcraft** [comment]
> can I set the `framework-customizations` folder to be inside plugin?

No.

> I want to customize some core extensions

Try this filter http://manual.unyson.io/en/latest/extensions/introduction.html#custom-load-locations

The load/overwrite order is

* framework extensions
* custom locations extensions
* theme extensions

https://github.com/ThemeFuse/Unyson/blob/7571569a9779cc695b424e4db65e98334adb5e8a/framework/core/components/extensions.php#L356
