### ISSUE TITLE
Text Block: Change modal size

### ISSUE THREAD

**Issue by meneldil** [ThemeFuse/Unyson#932]
Hi everyone,

Currently the "Text block" widget opens a window that is too small. (class: .fw-modal-small)
I wanted to know how to change the size of the window for this widget only? (put the class: .fw-modal-large)

**Comment by moldcraft** [comment]
> http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file
> 
> ```
> 'popup_size' => 'small', // can be large, medium or small
> ```

So copy [`unyson/framework/extensions/shortcodes/shortcodes/text-block/config.php`](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/65e595ae84684b330a4161cef4afc1df538a7ddc/shortcodes/text-block/config.php) in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/text-block/config.php` and set the `popup_size` parameter

**Comment by meneldil** [comment]
Perfect ! Thank you.

However the WYSIWYG editor is still small.
This comes from the CSS rule:
.fw-backend-option-design-default > .fw-backend-option-input.width-type-fixed > .fw-inner, .fw-backend-option-design-customizer > .fw-backend-option-input.width-type-fixed > .fw-inner, .fw-backend-option-design-taxonomy > td > .fw-backend-option-input.width-type-fixed > .fw-inner, .fw-backend-option-fixed-width {
    width: 100%;
    max-width: 428px; <-- This one
}

**Comment by moldcraft** [comment]
It was always small

**Comment by moldcraft** [comment]
Try [`'size' => 'large'`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#wp-editor) [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/65e595ae84684b330a4161cef4afc1df538a7ddc/shortcodes/text-block/options.php#L7)

**Comment by danyj** [comment]
'text' => array(
				'label' => __('Text', 'fw'),
				'desc' => __('Textarea', 'fw'),
				'type' => 'wp-editor',
				'tinymce' => true,
				'size' => 'large',
				'editor_height' => 100,
				'editor_type' => 'html',
				'reinit' => true,
				'wpautop' => false,
				'value' => ''
			),

**Comment by meneldil** [comment]
It works perfectly!
Thank you so much. :D

**Comment by zakirsajib** [comment]
`{theme}/framework-customizations/extensions/shortcodes/shortcodes/text-block/options.php`

`if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}
$options = array(
	'id' => array( 'type' => 'unique' ),
	'general' => array(
		'title'   => esc_html__( 'General', 'fw' ),
		'type'    => 'tab',
		'options' => array(
			'text' => array(
				'label' => __('Text', 'fw'),
            'desc' => __('Textarea', 'fw'),
            'type' => 'wp-editor',
            'tinymce' => true,
            'size' => 'large',
            'editor_height' => 100,
            'editor_type' => 'html',
            'reinit' => true,
            'wpautop' => false,
            'value' => ''
			),
		),
	),
);`
