### ISSUE TITLE
The sidebar extension didn't work with Backup extension

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#933]
I have an custom widget area that is create by Sidebar extension with some widgets.
When I create demo install by Backup extension to restore to client site. The custom widget area didn't apprear after run 'Content Install'. 
In my local: http://prntscr.com/8qphov
After importing demo: http://prntscr.com/8qphxi 
Please check it.

**Comment by duongancol** [comment]
Hi! @llemurya , any news?

**Comment by llemurya** [comment]
@duongancol please test with the new backup extension and say if the bug persists.
