### ISSUE TITLE
the_content()  is returning values in shortcode format

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson#934]
Hi 

I am using ajax to load pages. The post title is ok . But the content is returning values in shortcode format. 
 Any pages that uses the builder does the same. 
Here is the screenshot
![capture](https://cloud.githubusercontent.com/assets/12174913/10452430/c949f9b0-71c6-11e5-92a8-ba1f1e65e217.PNG)

**Comment by moldcraft** [comment]
Hello,

Please try to create a page without page-buider but with a default WP shortcode added manually in text mode. If the shortcode will be displayed on page preview, but it will be shown as text in your ajax load, then it's a problem with ajax load.

**Comment by ashraf92** [comment]
Hi Thank you . I also think so.But I ajax load the other shortcodes are parsed. I am using default wordpress ajax system. Is there anything that I can do in ajax return data-types?

**Comment by moldcraft** [comment]
Try to `do_shortcode($content)`.

I need a way to test/reproduce this in order to find the problem.

**Comment by ashraf92** [comment]
That's great!! Can I send you my demo server wp login?

**Comment by moldcraft** [comment]
Yes

`moldcraft[at]email.com`
