### ISSUE TITLE
How to make editable theme by unyson

### ISSUE THREAD

**Issue by anindya22** [ThemeFuse/Unyson#935]
I want to make a them which options are control by unyson. By those option I want to change header color, body color, font style, heading style, logo change etc. By default word press support some options. But I need to customize those options and their values. Please Give me idea to do this.

Thank You.

**Comment by pe6o** [comment]
Have a look at the Unyson Scratch Theme https://github.com/ThemeFuse/Scratch-Theme
It will help you understand the framework.
