### ISSUE TITLE
Why Unyson automatically adds row/col12 to that block?

### ISSUE THREAD

**Issue by Krystus** [ThemeFuse/Unyson#936]
For now my custom HTML Block is just like Text Block. I have one big section and few columns. One of HTML Blocks (second one) is not in a column. Why Unyson automatically adds row/col12 to that block? Can I turn it off for HTML Block?

![zrzut ekranu 2015-10-14 o 17 38 26](https://cloud.githubusercontent.com/assets/15039636/10488902/2d3dd656-729b-11e5-9e7c-52b0a3518968.png)

![zrzut ekranu 2015-10-14 o 17 35 55](https://cloud.githubusercontent.com/assets/15039636/10488671/1acad1dc-729a-11e5-93ad-5921a5d313e0.png)

**Comment by moldcraft** [comment]
Hello,

Try [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/70e5842692e3fb4eadcc81143e328a0d9468c996/config.php#L13-L19)

**Comment by Krystus** [comment]
```
Parse error: syntax error, unexpected '=', expecting ')' in /private/var/www/dev1/wp-content/themes/twcbagpak/framework-customizations/extensions/shortcodes/shortcodes/html-block/config.php on line 11
```

After => nothing.

```
<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}

$cfg = array();

$cfg['page_builder'] = array(
	'disable_correction' = true,
	'title'       => __( 'HTML Block', 'fw' ),
	'description' => __( 'Add a HTML Block', 'fw' ),
	'tab'         => __( 'Content Elements', 'fw' ),
);
```

**Comment by danyj** [comment]
you have syntax error there 


 not  

    'disable_correction' = true


but ( associative array , not a variable ) 


    'disable_correction' => true

**Comment by danyj** [comment]
and that will disable correction for everything , we are still waiting for this to work 
https://github.com/ThemeFuse/Unyson/issues/799

which should be used per shortcode basis , not all/none

**Comment by Krystus** [comment]
@danyj even with 'disable_correction' => true its not working. #799 is a good idea.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/799
