### ISSUE TITLE
Auto-install (demo data) and ThemeForest, please help

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#937]
Hello, guys!

I've just finished my first project based on your incredible framework, thank you so much for your work, you're really the best and Unyson is a really the best tool for creating themes!

Unfortunatelly i faced a big problem. My theme can not be approved on ThemeForest, because i'm using Auto-install (backup extension). They require me to remove database.sql file from auto-install directory (i believe this is because ThemeCheck plugin generates a warning about that), but if i'll do that, my theme will be without demo data, and this is too bad.

I know this is so stupid, and theme forest review team are bunch of idiots who create problems for no reason, but it is impossible to convince them.

Could you help me please, it there a way to rename an extension of this .sql file or maybe to compress it in archive? It seems all my time which i spent to develop a theme fly to nowhere

Thank you for reading, i hope you will help me, guys

**Comment by moldcraft** [comment]
Which Unyson version do you have?

**Comment by WPJobs** [comment]
Thank you for a fast reply. Unyson 2.4.9 is installed, fresh as always

**Comment by duongancol** [comment]
simple solution, just upload theme without auto-install folder and add it again after your theme is approved. And Reviewer won't check your demo data. So just remove it and add later.

**Comment by WPJobs** [comment]
thank you, @duongancol, it is really simple, but, maybe in the future, is it possible to make some compatibility with ThemeCheck plugin?

**Comment by duongancol** [comment]
yes, if database.txt is zipped but for me it's unneccessary because the reviewer doesn't check demo đata.

**Comment by WPJobs** [comment]
Reviewer doesn't check demo data, that's true, but he checks a whole theme using ThemeCheck plugin, and this plugin generates a warning if .sql file exists in a theme, and this warning generates a problem :)

**Comment by duongancol** [comment]
no, it's database.txt not database.sql, please check again to make sure the problem from Backup extension

**Comment by WPJobs** [comment]
Sorry, not quite understand, can i just rename database.sql into database.txt in /auto-install/ directory? Or should i zip database.sql and then rename it into database.txt? 

I generated auto install by using Backup extension, and then i followed these instructions http://unyson-framework.readthedocs.org/en/latest/extension/contentdemoinstall/#auto-install, i placed uploads folder and database.sql file into /auto-install/ directory in the root dir of my theme

**Comment by moldcraft** [comment]
> .sql file

We don't have .sql we have .txt. Maybe you have a very old version of the Backup extension?

**Comment by moldcraft** [comment]
Sorry, about .sql in docs. I will fix that right away.

**Comment by WPJobs** [comment]
that's true, i generated auto-install with previous version of Unyson, i didn't know that this problem was already fixed in the 2.4.9, thank you, @moldcraft and @duongancol for your fast help! 

I do not know how to thank you for your invaluable help!

**Comment by moldcraft** [comment]
Just use Unyson, that is the best help you can give.

**Comment by duongancol** [comment]
and fon't forget to share it ;)

**Comment by WPJobs** [comment]
thank you again, i will promote it in all possible ways!

**Comment by danyj** [comment]
@WPJobs  so ,  did they accept it? when is the launch. dont let us wait here :)

**Comment by WPJobs** [comment]
@danyj, Thank you for your interest, but reviewer invented new things that i should fix, so my theme still in review process :)

**Comment by danyj** [comment]
ok , show us the theme than we might catch other things you might need.  is already in the process ques so you should not be worried. I would like to know what they actually say and what they are picking about.

**Comment by WPJobs** [comment]
@danyj, oh... latest requirements are:

1) theme should generate 100% valid HTML, by the way, Unyson Forms extension generates an empty "action" form attribute, and this is an error

2) use esc_html__, esc_html_e, and wp_kses, even you wrote a config, e.g.:

$cfg = array(
	'page_builder' => array(
		'title'       => esc_html__( 'Portfolio Works', 'wplab-unicum' ),
		'description' => esc_html__( 'Portfolio Section', 'wplab-unicum' ),
		'tab'         => esc_html__( 'Theme Elements', 'wplab-unicum' ),
	)
);

3) do not use fopen / fwrite etc, use WP_Filesystem instead

more requirements can be found here https://help.market.envato.com/hc/en-us/articles/202822450-WordPress-Theme-Submission-Requirements

p.s. my theme URL is http://unicum.wplab.pro/

**Comment by danyj** [comment]
no way , they ask for  titles in configs to be escaped ?

I used this 

    __( 'Notification', 'fw' ),


for eexample ,  did you miss those or they specifically asking for esc_html__

and so far I know  html is escaped from titles , @moldcraft  are they ?

**Comment by WPJobs** [comment]
@danyj yes, they asked this, here is a cite:

It's possible for translators to sneak HTML and JS into translation files or even just inadvertently mess something up. So, it's good practice to simply escape them. No HTML: esc_html__( 'String', ‘unicum’ ); esc_html_e( 'String', ‘unicum’ ); Some HTML: wp_kses( __( 'String <strong>something</strong>', ‘unicum’ ), $allowed_html_array );

**Comment by danyj** [comment]
than all  custom theme options that we have we have to do this , darn , I have 25  and hundreds of  titles using  __()  

what did you use in theme options ? like any options for example option tab title 


    'title' => __('Icon box settings', 'fw'),

@moldcraft   bud , did they tell you this when they approved Unyson ?

I see about   the form , https://validator.w3.org/nu/?doc=http%3A%2F%2Funicum.wplab.pro%2Fhome-creative-agency%2F

I think @llemurya  is form developer

**Comment by danyj** [comment]
Props on the theme , nice and clean , graphics effects on personal were also used here http://themeforest.net/item/ronneby-highperformance-wordpress-theme/11776839

**Comment by danyj** [comment]
this is what I meant http://themes.dfd.name/ronneby/second/

**Comment by WPJobs** [comment]
@danyj, heh that's what I'm working right now instead of sleeping

**Comment by danyj** [comment]
someone should have told us about this , man this is not ok , I am on the task since Jan 2015, we should have had heads up on this. Thousands of lines of code written.

**Comment by WPJobs** [comment]
@danyj, to b honest, I think that they are just trying to slow down new themes since they have too many new submissions, that's why they come up with all new ridiculous rules

**Comment by danyj** [comment]
@WPJobs if it makes you feel any better , thank you for giving us the heads up. This is very valuable. Pain in the ass but valuable.

**Comment by WPJobs** [comment]
@danyj i was glad to help you, because, it seems, this is the only place where people can help each other. Envato community, support, and reviewers are just ignores my questions or respond pointless

**Comment by danyj** [comment]
we do what we can bud , I think the action should have current link , 

darn I have 2255  lines to fix http://prntscr.com/8rqksl

they even told you this about tgm plugin ? that one alone has about 100  if you are using it 
http://prntscr.com/8rqm40

**Comment by WPJobs** [comment]
no, they don't touch third-party libraries like TGM

**Comment by danyj** [comment]
look here man #844   https://github.com/ThemeFuse/Unyson/blob/3efe8f062d12c9db14298ac9e034404f68b98bbc/framework/includes/container-types/tab/view.php#L12

I think those are escaped , except our custom ones, others should already be escaped and if they not Unyson should do this since the same issue affects the plugin and none of those options run without it.

**Comment by danyj** [comment]
'title' => __('<div class="something">Icon box settings</div>', 'fw'),


http://prntscr.com/8rqqgk

**Comment by WPJobs** [comment]
you know, i'm just tired to argue with them because it's pointless, i've just finished a lot of job to make all language strings escaped and i'm going to sleep. Good luck, man!

**Comment by danyj** [comment]
Escaped from option titles , not descriptions 

http://prntscr.com/8rqrc9

not escaped from shortcodes configs  http://prntscr.com/8rqrp9

**Comment by duongancol** [comment]
You need to escape all HTML translator string.

**Comment by moldcraft** [comment]
> 2) use esc_html__, esc_html_e, and wp_kses, even you wrote a config

No sense. 

Our/My rule is: In database, in variables, in configs, etc. should be original untouched values, ONLY ON OUTPUT IN HTML the developer MUST ESCAPE EVERYTHING that is printed out (that's what we do)

> I see about the form , https://validator.w3.org/nu/?doc=http%3A%2F%2Funicum.wplab.pro%2Fhome-creative-agency%2F

I didn't knew about that. Ok, I'll just add current url in `action` (this is the purpose of an empty `action`)

**Comment by WPJobs** [comment]
yes, sorry, that's my fault about config, you don't need to escape configs

**Comment by danyj** [comment]
@moldcraft   

> ONLY ON OUTPUT IN HTML 

the options label , config title , descriptions are those outputs, and so far I see this , this is a talk about admin options / configs  not frontend so I think this should have been done by the framework itself and not developers. Kirki or redux protect their options and looks like ours are not protected. 

@WPJobs   

> yes, sorry, that's my fault about config, you don't need to escape configs

bud , can you be certain as to what the issue is. There are few more Unyson options on TF and this is first time we hear about it since Unyson has been published. 

@duongancol   
did you had experience with TF check team? did they say we need to translate labels, titles,descriptions ? 


I dont know about anyone else but I have over 2k lines to fix so please give exact details before I start doing this .

**Comment by danyj** [comment]
in light of this I propose the esc _html on Unyson level for following ;

    'title' => // options types or config
    'label' =>  // anywhere

and wp_kses with allowed tags  attr https://codex.wordpress.org/Function_Reference/wp_kses#Allowed_HTML_Tags_Array

for

    'help'=> // anywhere
    'desc'=> // anywhere


allowed tags 

	array(
		'a' => array(
			'href' => array(),
			'title' => array(),
			'target' => array()
		),
		'br' => array(),
		'em' => array(),
		'strong' => array(),
	);

**Comment by danyj** [comment]
And we also have those 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/notification/config.php#L9-L10

man this is a mess

**Comment by moldcraft** [comment]
> this should have been done by the framework itself and not developers.

I meant framework developers, framework itself.

> Kirki or redux protect their options and looks like ours are not protected.

An example?

> And we also have those 
> https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/notification/config.php#L9-L10
> 
> man this is a mess

It doesn't matter what is in config, it matters if that value is escaped on `echo`

**Comment by danyj** [comment]
Kirki redux ,  https://github.com/aristath/kirki/issues/141#issuecomment-89789862

I monitor their gits and constantly see them fix esc issues

**Comment by moldcraft** [comment]
So there are 2 approaches:

1. Sanitize everything every time and don't bother when doing `echo`

    * `$test['foo'] = esc_html__('Bar');`
    * `echo $test['foo'];`

2. Work with raw/original values and sanitize only on output

    * `$test['foo'] = __('Bar');`
    * `echo esc_html($test['foo']);`

I prefer the second approach.

**Comment by danyj** [comment]
second one

**Comment by duongancol** [comment]
I prefer the second choice too but The reviewer search translation string and if they got __() without escaping, the theme will be rejected and even it's echoed or not

**Comment by moldcraft** [comment]
Try to open a forum about this on TF to see what other developers are thinking about this.

**Comment by danyj** [comment]
@duongancol   reviews should also know about the framework and be aware that none of those are visible without Unyson , you cant see  admin options, builder etc without it
I think we should get one of them here to help us out and explain. 

@WPJobs   @moldcraft   do you know or can get in touch with any of them ?

**Comment by danyj** [comment]
Il open a forum on TF

**Comment by danyj** [comment]
Here we go 
https://forums.envato.com/t/output-sanitizing-issue-we-need-theme-reviewers-input-please-advise/11854

**Comment by danyj** [comment]
X theme http://prntscr.com/8rwxhc
Avada http://prntscr.com/8rwxtz
Enfold http://prntscr.com/8rwy6w


each of them hundreds of entries and all are escaped on framework level.

**Comment by pe6o** [comment]
Okay guys, just received the following theme reject from themeforest:

1. Theme does not translate all text strings.

See: https://developer.wordpress.org/themes/functionality/internationalization/#add-text-domain-to-strings

2. No auto-installs please, anything theme needs to include, it must be done via image folder, not uploads which falls in Core.

3. No database.txt at all, this is not what themes should do.

I'm kinda lost how to proceed.. :-\

**Comment by pe6o** [comment]
So it seems that the Unyson 1 Click Demo is currently not permitted on themeforest?

**Comment by danyj** [comment]
@pe6o ,  I think  @WPJobs   just got approved and has used auto install,  lets continue here #948

**Comment by WPJobs** [comment]
@danyj that's true, my theme was just approved. I am very surprised that TF reviewer rejected theme with these reasons o_O Please keep this thread updated, because i'm working on another theme based on Unyson and it will be sad if it will be rejected by auto-installer reason

**Comment by WPJobs** [comment]
@pe6o please keep us updated regarding latest two reasons

**Comment by danyj** [comment]
to me looks like reviewer in @pe6o  case has no idea what Unyson is and think that something in the theme itself runs demo install. @pe6o  , explain the demo install bud and advise that Unyson plugin is doing it and theme only provides the zip.

**Comment by WPJobs** [comment]
@danyj it seems to be true 
@pe6o did you check Unyson framework in a "Framework" field when you uploaded your theme? https://yadi.sk/i/RXAtjdWMjp3pw

**Comment by danyj** [comment]
I dont like X design at all but there is something in this story that we all should be aware off
http://www.ugurus.com/blog/how-x-became-the-fastest-selling-theme-in-themeforest-history

and that is , TF reviewers can make horrible mistakes that can affect the developer but in this case it has affected TF and caused significant loss of their revenue until one of them saw the potential.

**Comment by pe6o** [comment]
@WPJobs Yes, I checked the Unyson framework. I uploaded the theme again with a reviewer notice that this is part of the 1 Click Install. I'll keep you updated.

**Comment by WPJobs** [comment]
thank you, @pe6o

p.s. before you upload your theme again, do not forget to fix a reason #1 (Theme does not translate all text strings.)

**Comment by pe6o** [comment]
Yeah, I explained the translation problem to them. The themecheck was giving fake warnings.

My theme is currently *Temporarily held for further review* - don't know if it's about the **auto-install** or they are deciding on the pricing.

Stay tuned!

**Comment by WPJobs** [comment]
@pe6o it is regarding auto-installer reason, a reviewer wants to ask another guy regarding this, please be patient :)

**Comment by danyj** [comment]
Unbelievable , after  7 days instead to help us  my post is hidden due to links to Unyson git.

**Comment by pe6o** [comment]
@danyj Currently there is a lot of heat in the themeforest forums concerning the new tax changes, so yeah, everyone is on fire there.

**Comment by danyj** [comment]
@WPJobs   post a link to the theme on TF so that we can prop.

**Comment by pe6o** [comment]
@danyj You meant me?
Anyway, here is a link to the theme for anyone curious =)
http://themeforest.net/item/couponhut-coupons-deals-wordpress-theme/12876388

**Comment by danyj** [comment]
ah yes sorry @pe6o

**Comment by pe6o** [comment]
Thank you. Very appreciated!

It seems I have missed adding the *auto-install* folder in it, although I left message to the reviewer that it's from Unyson :0

**Comment by martinburdon** [comment]
Sorry to gate crash this post guys but just wanted to ask @pe6o and @WPJobs how long your items were in the queue before they got reviewed?

Just uploaded mine on Saturday so counting down :smile:

**Comment by pe6o** [comment]
@martinburdon  My latest 2 themes for the last two days took around 10 days initially and every soft reject took 2-3 days.

**Comment by martinburdon** [comment]
Thanks @pe6o

It's the first theme I've done for around 3 years so expecting at least a soft reject (hopefully not a hard reject)

**Comment by danyj** [comment]
@martinburdon  show us the goods :)

**Comment by martinburdon** [comment]
Haha here it is http://demo.rocketshipthemes.co.uk/confetti/demo-1/

**Comment by danyj** [comment]
@martinburdon  clean minimalist , I like it, good luck!

**Comment by martinburdon** [comment]
@danyj thanks, the big question is, is it too minimalist for ThemeForest? Only time will tell!
