### ISSUE TITLE
Sliders all blank 

### ISSUE THREAD

**Issue by LevyMarketing** [ThemeFuse/Unyson#938]
When I go to create a slider every option is blank, so I can't add photos to it. My already created slider is completely blank now as well. 

![image](https://cloud.githubusercontent.com/assets/14837164/10514247/aade6326-731a-11e5-8260-a9f68f365c59.png)

**Comment by moldcraft** [comment]
Please update the Sliders extension

**Comment by LevyMarketing** [comment]
My Unyson is completely up-to-date.

**Comment by moldcraft** [comment]
Do you have the same message here?

![s](https://static.md/87ec91bae91191b96ca0ce9e80b4a060.png)

**Comment by llemurya** [comment]
@LevyMarketing you must update population-methods-extension, and it will work.

**Comment by LevyMarketing** [comment]
Ok, thank you!
