### ISSUE TITLE
[help]Need some instructions for a feature

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#940]
Please enlighten me here and possibly advise a way to do this . 

I see you work on backup extension and are able to do things that I need in my theme feature. 
In joomla version we have a compression which collects  all CSS files and inline and puts them in a file inside the template folder https://github.com/YJSGframework/yjsg/blob/f2146d0718bda21ea770b6c73d37a84fe374662d/includes/yjsgcore/yjsg_compile.php#L214-L216

in WP this would be  

    wp-content/themes/themename/css_compiled

The output  example
http://joomlatemplates.youjoomla.info/eximium/templates/eximium/css_compiled/template-blue.css

now , I  know how to use WP_filesystem or create/generate/move files and content , what makes no sense to me is the 

    FS_METHOD

so how is your backup extension able to make a backup if  this is set ?

     define('FS_METHOD', 'ftpext');

and if user is required to add FTP credentials on plugins/themes/wp updates
I also see that you are moving backups to  wp-content/uploads folder 

is this no restriction folder in wordpress? 

In joomla we can move files anywhere we need them to and  JFile joomla class which is equivalent to WP_filesystem has no restrictions at all.  If folder is writable we can use it. 

So all this FS_METHOD mambo jumbo is limiting me to add the needed functionality. 

I mean I cant port our compression plugin or use theme compression because of this. 
Here look at the source on this template 
http://joomlatemplates.youjoomla.info/play/

that is our compression plugin in action. 
https://github.com/youjoomla/jcompress

Can you please advise of a process and answer those few questions I have. 

Any help from anyone who is reading this is more than welcome.

**Comment by moldcraft** [comment]
As I explained a lot about WP FS in another issue. Again, in `wp-content/uploads` you can create files without WP_Filesystem - this is how WP uploads are created and also our Backup extension creates files in that folder. In other directories you need WP_Filesystem access

**Comment by danyj** [comment]
ok than stay away from theme folder 
use upload folder 
use native php 

	file_exists()
	fopen()
	fwrite()
	fclose()
	move()
	copy()

correct ?

**Comment by moldcraft** [comment]
> ok than stay away from theme folder 
> use upload folder

Yes

> use native php fopen() fwrite() ...

yes ... but Theme Check will throw warnings regarding those functions, that's why we created [this explanation](https://github.com/ThemeFuse/Unyson/blob/master/plugin-check-info.md) in order for Unyson to be accepted on TF (because of Plugin Check, that uses Theme Check code). So I don't know, maybe someone knows the sure answer. If you will find it, let us know.

**Comment by danyj** [comment]
or ? 

use native file/dir writte function and use writable folders ? 

example 

if I do this 

	if (is_writable('theme/css_compiled')){
	  
		 // make new file via php native function NOT WP_Filesystem
	
	}

and   this is on

     define('FS_METHOD', 'ftpext');

would I stil be able to create the file in that dir or not? 

sorry for picking your brain about this but cant find suitable info.

**Comment by danyj** [comment]
ah carp , I see what you mean

**Comment by danyj** [comment]
OK , for creation of custom.css file I used a trick , 

		if(copy(thz_theme_dir()."/css/thz-files-dist",$file_to_writte)){
			
			$msg_to_show = __('File created','creatus');
		
		}


which copies the dist file to new file name , no read/writte. 
but for actual write read files that we will need is a hard one. This is such a bull.
