### ISSUE TITLE
Can i make addable box full width?

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#941]
Hi,

Can i make addable box full width?

![schermafbeelding 2015-10-15 om 17 10 44](https://cloud.githubusercontent.com/assets/5340923/10518025/c2f9dc02-735f-11e5-9d4e-9298cc7f0255.png)

**Comment by moldcraft** [comment]
No.

We will add a parameter later.

**Comment by nickkuijpers** [comment]
Oké, perfect!
