### ISSUE TITLE
wp-editor on load starts on 'text' and not 'wysiwyg'

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson#942]
Hi,

When the back-end page loads, the wp-editor option opens up text on default and not the wysiwyg.

Can i change this somewhere?

**Comment by llemurya** [comment]
@nickkuijpers please read [our documentation](http://manual.unyson.io/en/latest/options/built-in-option-types.html#wp-editor) pay attention at `editor_type` key.I think it solve your problem , please give as an answer if it helps.

**Comment by nickkuijpers** [comment]
Sorry, i see it. Thanks..
