### ISSUE TITLE
Issue when using Content Install

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#944]
Just testing out the content install feature locally with an install I got from my live site and getting the following errors which brings the site down:

```
Deprecated: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in .../wp-content/plugins/unyson/framework/extensions/backup/includes/lib/srdb.class.php on line 610

Fatal error: Call to a member function query() on boolean in .../wp-content/plugins/unyson/framework/extensions/backup/includes/lib/srdb.class.php on line 578
```

**Comment by danyj** [comment]
There is new backup extension in works , see #882

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
