### ISSUE TITLE
Scratch Theme v2

### ISSUE THREAD

**Issue by cars111** [ThemeFuse/Unyson#945]
Hi guys I know you are very busy but I have been waiting for months for the new vertical scratch theme, any ETA?

and where has your trello board gone?

Thanks

**Comment by moldcraft** [comment]
Hello,

**vertical** scratch theme ?

Our new free theme based on Unyson is in the works.

Trello board is [here](https://github.com/ThemeFuse/Unyson/issues/617#issuecomment-107845454)

**Comment by moldcraft** [comment]
Hello,

We finished Scratch Theme v2, but it was not as expected and we don't have plans and time to improve and support it. You can [download it](http://themefuse.com/wp-themes-shop/journal/) (but don't report issues related to it because we don't support it)
