### ISSUE TITLE
Help me understand option type saving process

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#946]
In option types we have   method

    _get_value_from_input

is this method responsible to send option info to DB ? 

You see I have CSS processor that I am currently using on frontend , but would like to save data in DB rather so that I dont have to process it on every load but just pull it out of the DB. 

So in my option _get_value_from_input   right beofre retrun value I added 

    $value['css'] = $this->process_css($value);
    return $value;

and it is saving it.  I dont need a visual option , just need to save the data and use it in frontend. 
Do you see an issue with this and is this ok to do ?

**Comment by moldcraft** [comment]
> is this method responsible to send option info to DB ?

No. It is responsible to return a value that **can be** sent to DB, but it is up to the code that called it to do whatever it wants with that value.

If you option type is used only in one place (for e.g. Theme Settings) then the above solution should work. If it is used in shortcode options, then I think it may save when not needed, or multiple times. It's tricky

I don't know the solution at the moment. [This](https://github.com/ThemeFuse/Unyson/issues/838) seems to be the solution

**Comment by danyj** [comment]
OK , I tested in section options and theme options , it does the same thing for now.  Can you show me proper way to do this since the post you linked to does not do anything or I dont see it. 

Here is an example , my CSS processor collects all these 

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php#L156-L167

and needs to save it under   value->css

which would be here 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/typography-v2/class-fw-option-type-typography-v2.php#L134
