### ISSUE TITLE
How to center page builder column

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#950]
I need to add a class to column inside the builder and tried 

    		'title_template' => '{{  console.log(\'in\'); if (o.centered == \'center\') { console.log(o.centered); } }}',

but nothing is happening, 

what I need is if column is centered http://prntscr.com/8skgxk

to add a class to one of these http://prntscr.com/8skhbt

or do    

    style="display:block;margin-left:auto;margin-right:auto;"

**Comment by danyj** [comment]
@moldcraft  nothing on this ?

**Comment by moldcraft** [comment]
*Sorry for late reply, today I only coded (Backup v2) and didn't opened issues to not be "absorbed" in discussions and get distracted.*

Column doesn't have `title_template` support ([source](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/65e595ae84684b330a4161cef4afc1df538a7ddc/shortcodes/section/includes/page-builder-section-item/static/js/scripts.js#L48) -> `Ctrl+F` -> `title_teplate` -> nothing. [Section](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/65e595ae84684b330a4161cef4afc1df538a7ddc/shortcodes/section/includes/page-builder-section-item/static/js/scripts.js#L48) has)

Try to use [this event](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/9e1a8040de5b8ecab8475142be55c766d4eba446/shortcodes/column/includes/page-builder-column-item/static/js/scripts.js#L65). `model.view.$el` is column DOM element. Column options should be in `model.get('options')`

**Comment by danyj** [comment]
@moldcraft   im bit lost , 




I tried this one but is undefined 


    data.model.get('options');


I get the options but as a full array not as you get it from title like o.option name 
do I need to filter trough it or am I doing this wrong. 

first I had to add this snip to some js file that is called when builder is there 

			fwEvents.on('fw:page-builder:shortcode:column:controls', function(data){
				
				var column_options = data.model.view.modal.get('options');//data.model.view.$el
				console.log(column_options);
			
			});	

and I get  this

![screenshot_16](https://cloud.githubusercontent.com/assets/2340172/10636406/eda33be8-77ff-11e5-975b-d00cce91fdd9.jpg)


the highlighted option is the one i am after.

**Comment by danyj** [comment]
I think I found it , it is 


    data.model.get('atts')

**Comment by danyj** [comment]
Here we go , for anyone that needs it 


js

			fwEvents.on('fw:page-builder:shortcode:column:controls', function(data){
				
				var column_options = data.model.get('atts');//data.model.view.$el
				var centered = column_options.centered;
				
				if(centered == 'center'){
					
					$(data.model.view.$el).addClass('thz-center-builder-column');
					
				}else{
					$(data.model.view.$el).removeClass('thz-center-builder-column');
				}
			
			});	


css

	.fw-option-type-builder .builder-items .builder-item.thz-center-builder-column{
		display:block;
		margin-left:auto;
		margin-right:auto;
	}


output 

![screenshot_18](https://cloud.githubusercontent.com/assets/2340172/10636819/73d3cff0-7802-11e5-87d6-406d1c4ffcbe.jpg)

**Comment by c0sm1n87** [comment]
i found this useful :+1:  

thanks @danyj

**Comment by danyj** [comment]
@c0sm1n87  update , on first time add we fire to soon ,   so check for data and option is required , otherwise js errors are shown 



	fwEvents.on('fw:page-builder:shortcode:column:controls', function(data){
	
		var column_options = data.model.get('atts');
		var centered;
		
		if (column_options && column_options.centered){
			centered = column_options.centered;
		}
	
		if(centered == 'center'){
	
			$(data.model.view.$el).addClass('fw-center-builder-column');
	
		}else{
	
			$(data.model.view.$el).removeClass('fw-center-builder-column');
	
		}
	
	});

**Comment by c0sm1n87** [comment]
thanks @danyj :+1: ,i'll update it right away. I saw that there was a Javascript error and I intended to fix later on ( for time being I was using a simple workaround like the one below)

      if ( typeof fwEvents !== "undefined" ) { //code }

**Comment by danyj** [comment]
@moldcraft   bud need some help here @c0sm1n87  heads up  , check this out 

I add this in  http://prntscr.com/99moiv

thinking that is the layout ,  but I get this instead  http://prntscr.com/99mow3  2 rows , so I thought builder is broken but no ,  builder is splitting the rows since this is builder natural view when centered is removed  from column. 

http://prntscr.com/99mpft

how do we rectify this ?

**Comment by danyj** [comment]
without splitting this in 2 sections of course.

**Comment by c0sm1n87** [comment]
I am not home to test this out, @danyj do you have a public server where I can see this for myself?

**Comment by moldcraft** [comment]
yes, give us the steps (with code) to reproduce this, or admin (ftp) access to your public server (you can install a default WP theme there and create this example with columns, to not show your private theme)

**Comment by danyj** [comment]
steps are above but here again 


add this in column options 


	'centered' => array(
		'label' => __('Center column', 'fw'),
		'desc' => __('If set to center, this column float is removed and it will be centered inside the section.', 'fw'),
		'type' => 'switch',
		'right-choice' => array(
			'value' => 'donotcenter',
			'label' => __('Do not center', 'fw')
		),
		'left-choice' => array(
			'value' => 'center',
			'label' => __('Center', 'creatus')
		),
		'value' => 'donotcenter'
	),

add this in any JS file that loads in admin or in console 


			fwEvents.on('fw:page-builder:shortcode:column:controls', function(data){
				
				var column_options = data.model.get('atts');
				var centered;
				
				if (column_options && column_options.centered){
					centered = column_options.centered;
				}				

				
				if(centered == 'center'){
					
					$(data.model.view.$el).addClass('thz-center-builder-column');
					
				}else{
					
					$(data.model.view.$el).removeClass('thz-center-builder-column');
				}
			
			});

add this CSS in any css file that loads when builder is present 

	.fw-option-type-builder .builder-items .builder-item.thz-center-builder-column {
		display: block;
		margin-left: auto;
		margin-right: auto;
	}




now in builder add: 

1  section 
in section add 

1 column     ( 1/ 2)  and in that column set centered as   centered 

 under that column  add 

4 columns  ( 1/3 ) 

add some text blocks in columns 

you would expect to see  this  in frontend 

![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/11561931/f54908b8-99ca-11e5-8655-8f4eaa935778.jpg)


but what you will get is this 

![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/11561942/0896af74-99cb-11e5-8084-87d4705e2180.jpg)


because the center option is not connected to the builder   and builder simply follows " fill what you can "  rule . So we need to somehow connect the centered option to the builder so it understands that  centered column is  row 1  and the ones under  are row 2

**Comment by moldcraft** [comment]
1. Columns are `float:left`, setting align has no effect
2. A hack/solution would be to

    1. In column view, if `$atts['centered']` then the html must be

        ```html
        <div class="thz-center-builder-column">
            <div class="inner">Content...</div>
        </div>
        ```

    2. Set css in frontend

        ```css
        .row > .col.thz-center-builder-column {
            display: block;
            float: none;
            width: 100%;
        }
        .row > .col.thz-center-builder-column > .inner {
            margin-left: auto;
            margin-right: auto;
        }
        ```

    *(not tested)*

**Comment by moldcraft** [comment]
1. Columns are `float:left`, setting align has no effect
2. A hack/solution would be to

    1. In column view, if `$atts['centered']` then the html must be

        ```html
        <div class="thz-center-builder-column col-...">
            <div class="inner">content</div>
        </div>
        ```

    2. Set css in frontend

        ```css
        .row > .thz-center-builder-column {
            display: block;
            float: none;
            width: 100%;
        }
        .row > .thz-center-builder-column > .inner {
            margin-left: auto;
            margin-right: auto;
        }
        ```

    *(not tested)*

**Comment by danyj** [comment]
no bud ,  look here ,  builder is making automatic rows depending how many columns fit inside the section,  so if you have 3  1/3 columns above , and add one  1/2  it auto creates 2 rows since it has no space , 

http://prntscr.com/99mq21

that is what the problem in this case is , this cant be fixed with css since builder is spliting columns in those rows , 

if this was everything in 1 row I wold not have issues since the grid knows how to align things

**Comment by moldcraft** [comment]
Sorry, I forgot about "automatic row creation mechanism" (I haven't made it)

Checking...

**Comment by moldcraft** [comment]
Add in `{theme}/framework-customizations/extensions/shortcodes/shortcodes/column/config.php`

```php
<?php if (!defined('FW')) die('Forbidden');

$cfg = array(
	'page_builder' => array(
		'tab' => __('Layout Elements', 'fw'),
		'disable_correction' => true,
	)
);
```

**Comment by danyj** [comment]
what does that do now?

**Comment by moldcraft** [comment]
Doesn't create "smart" (automatic) rows for columns.

Wait a few minutes, I am doing a fix at the moment

**Comment by danyj** [comment]
Ok as long as it does not remove the rows. 

Best Regards
Dan Casky
Youjoomla Customer Service
+1727-388-6653
5044 17th street N
Saint Petersburg ,FL
33714
-------------------------------
Youjoomla LLC
www.youjoomla.com
Professional Joomla Web Design Services

**Comment by moldcraft** [comment]
[Done](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/3e8fa1c5033af65923b82c1b5bbe2342a18e5344)

Before & After *(not the `.fw-row`)*

![Before](http://static.md/3ca941863d479d78ab44b00e7ed23a4f.png) ![After](http://static.md/722f6cd681071de6b774eb625edadec7.png)

**Comment by danyj** [comment]
bud , I have no idea what you did  or why you did it but either way this is still same. 

downloaded master  https://github.com/ThemeFuse/Unyson-PageBuilder-Extension

added in column 

    'disable_correction' => true,

same thing

**Comment by moldcraft** [comment]
reSave the page

**Comment by danyj** [comment]
something is wrong ,  

have 2  special headings in front and 1 in back 

http://prntscr.com/9a8xdy
http://prntscr.com/9a8xh7

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/bb91926c09fa0492eddfcf239ab3decf15f77b47

reDownload please

**Comment by danyj** [comment]
ok , http://prntscr.com/9a8zts

looks good now thank you.  but it just kinda feels , dont know , we removed  the rows separation completely.  dont get me wrong this works , like said just feels off to remove this for all columns by default because we want to center 1 column .  ideal scenario would be something like an option that builder would recognize  and row splitting that one column in its own row and others as it did before correction false. like 

    fw_page_builder_center_column


	'fw_page_builder_center_column' => array(
		'label' => __('Center column', 'fw'),
		'desc' => __('If set to center, this column float is removed and it will be centered inside the section.', 'fw'),
		'type' => 'switch',
		'right-choice' => array(
			'value' => 'donotcenter',
			'label' => __('Do not center', 'fw')
		),
		'left-choice' => array(
			'value' => 'center',
			'label' => __('Center', 'fw')
		),
		'value' => 'donotcenter'
	),


thing is that row is invisible shrortcode and we cant affect the loop in the view

**Comment by moldcraft** [comment]
The reason why that separation was created, is to prevent [this problem](http://sourcebox.io/21761b40ebd84a0d91dfb90d0d134327/html)

If you will encounter that problem, let me know and I will try to create and advanced filter to be able to disable correction/separation only for specific columns/sections.

**Comment by danyj** [comment]
I am not using bs but this ,http://fiddle.jshell.net/6Wb6W/18/  so I dont have that issue , but you can see that in my grid I have rows separation. I dont want to trouble you but disable correction for everything  seems to much and in my opinion that rwos separation is good.  we just need to find a better way to tell the row to wrap that single column , 



duhhhhhh,  ok  ,     if there is only 1  column in the row ,  wrap it . that will do the trick

**Comment by danyj** [comment]
crap , row wont know how many columns are there , it fills as much as it can , dont know , just thinking out loud

**Comment by moldcraft** [comment]
Please confirm: You have a section with column, all columns are auto wrapped in row(s). You want  to pick a specific column and wrap it in a separate row (to be separated from the rest of the columns) ?

**Comment by danyj** [comment]
@moldcraft  this 

![screenshot_1](https://cloud.githubusercontent.com/assets/2340172/13530506/fce89724-e221-11e5-8ab0-e44e28bdaa4d.jpg)


comes out as this 


![screenshot_2](https://cloud.githubusercontent.com/assets/2340172/13530519/0578d49e-e222-11e5-8b47-3f67b50dfa6b.jpg)



and it should be like this 

![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/13530571/4358b572-e222-11e5-846d-48ea6d20a1db.jpg)



I know why , it is because my center column option  is not connected to the builder , and without my ad-don the builder actually sees this 


![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/13530611/86b0fed8-e222-11e5-86df-120acf3f9dd9.jpg)


so if we can have that option connect to builder in the proper way , so that builder knows if column is centered it should be in own row , issue would be solved.

**Comment by moldcraft** [comment]
```php
function _filter_theme_fw_ext_page_builder_item_corrector_column_width($width, $column) {
	fw_print($width, $column);

	// return '1_1';

	return $width;
}
add_filter(
	'fw:ext:page-builder:item-corrector:column-width',
	'_filter_theme_fw_ext_page_builder_item_corrector_column_width',
	10, 2
);
```

**Comment by danyj** [comment]
@moldcraft  strange , I have 8columns , http://prntscr.com/cm7p9z

added print 

    fw_print($column['atts']['centered']);

and the filter sees only 6 http://prntscr.com/cm7pnx

**Comment by moldcraft** [comment]
It is because of [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/c2b1b7901d41a013277f8b19ef04f999956dd914/includes/page-builder/includes/items-corrector/class-page-builder-items-corrector.php#L97) and [this](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/c2b1b7901d41a013277f8b19ef04f999956dd914/includes/page-builder/includes/items-corrector/class-page-builder-items-corrector.php#L103), they are not processed by the filter. Fixing...

**Comment by moldcraft** [comment]
Test please

**Comment by danyj** [comment]
@moldcraft  bless you hart !  did not see this !
