### ISSUE TITLE
Table row height issue in firefox

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#951]
Hello we have extend the pricing table shortcode.
now we faced a issue with unyson default.css

chrome work fine http://puu.sh/kPByE/1f4fbc373f.png
but firefox catch height css http://puu.sh/kPBA7/c4f2e4e897.png

if i remove this css height from unyson default-styles.css file. its work fine like chrome
.fw-option-type-table .fw-table-cell{
height: 18px;
}

Should i override this css ? or it should be remove this height from unyson plugin.

Thanks

**Comment by llemurya** [comment]
@Ataurr If you write your own table shortcode then you can override the css in your shortcode.

**Comment by puyaalexxx** [comment]
We cant reproduce the bug because we haven't your custom options for the table, and cant modify or remove that css. The better solution is to override the css in your shortcode
