### ISSUE TITLE
template name for section shortcode of page builder

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#952]
Please make the shortcode to have template name in page builder instead of just saying section.
In case the page have many sections, it will be hard to find the the section that contains the specific content.

**Comment by danyj** [comment]
Add to section options 


			'section_title' => array(
				'type' => 'text',
				'label' => __('Sorting title', 'fw'),
				'value' => '',
				'desc' => __('Used only in builder for easy sorting.', 'fw')
			),



add to section config.php


	'title_template' => '{{-title}}{{ if (o.section_title) { }} : <strong>{{= o.section_title}}</strong>{{ } }}',

output 

http://prntscr.com/8sx7gv

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/extension/shortcodes/index.html#config-file

**Comment by TrangDinhVan** [comment]
Wow, wonderful.
