### ISSUE TITLE
Changing Unyson name is legal?

### ISSUE THREAD

**Issue by coderontheroad** [ThemeFuse/Unyson#954]
I am unlearned about licences. So i want to ask that; Changing name of framework is very easy(delete all unyson texts and write custom names), but if i change the name and use it in production is there any problem about that?

**Comment by moldcraft** [comment]
You can change it. https://github.com/ThemeFuse/Unyson/blob/master/framework/LICENSE

We tried to use in code the 'unyson' word as less as possible. If you'll find some hardcode texts that can be made more flexible to change (with filters or something), please submit pull requests.

Good luck with your own framework!

**Comment by danyj** [comment]
@coderontheroad  I see a  problem , you wont know how to update it further , so keep it as is I suggest and you theme will live a long and prosper life.
