### ISSUE TITLE
How to add builder image for column ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#956]
For shortocdes in builder we can add 

    page_builder.png inside {your-shortcode}/static/img/ directory

but I am doing some column combos and need to add an icon for the new column

I tried adding      

    3_5.png in builder/static/img  folder but is not taking it.

**Comment by danyj** [comment]
@moldcraft  nothing on this?

**Comment by moldcraft** [comment]
Try this filter https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/65e595ae84684b330a4161cef4afc1df538a7ddc/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php#L117

**Comment by danyj** [comment]
thnx I did that but this makes no sense , extra function and filter for a missing image. 

we have these 3  in builder config.php


	'1_2' => array(
		'title'          => '1/2',
		'backend_class'  => 'fw-col-sm-6',
		'frontend_class' => 'thz-col-1-2',
	),

and no icon index , what if  user want to use own icon set for those or wants actual icon class instead  images. 

you should ad least check  overrides for the 

    \inc\thzframework\extensions\builder\static\img/{$key}.png" )

like you do for all other builder elements 

this hard coding makes no sense 
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/65e595ae84684b330a4161cef4afc1df538a7ddc/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php#L110


for me this is an overkill 



	function _thz_add_column_images($column_thumbnails) {
		
		
		$column_thumbnails[ '3_5' ] = array(
			'tab'         => __( 'Layout Elements', 'fw' ),
			'title'       => apply_filters( 'fw_ext_shortcodes_column_title', '3/5', '3_5' ),
			'description' => apply_filters( 'fw_ext_shortcodes_column_description',
				sprintf( __( 'Add a %s column', 'fw' ), '3/5'), '3_5' ),
			'icon'        => THZFW_URI.'/extensions/builder/static/img/3_5.png',
			'data'        => array(
				'width' => '3_5'
			)
		);	
		
		
		$column_thumbnails[ '4_5' ] = array(
			'tab'         => __( 'Layout Elements', 'fw' ),
			'title'       => apply_filters( 'fw_ext_shortcodes_column_title', '4/5', '4_5' ),
			'description' => apply_filters( 'fw_ext_shortcodes_column_description',
				sprintf( __( 'Add a %s column', 'fw' ), '4/5'), '4_5' ),
			'icon'        => THZFW_URI.'/extensions/builder/static/img/4_5.png',
			'data'        => array(
				'width' => '4_5'
			)
		);
	
		return $column_thumbnails ;
		
	}
	add_filter('fw_shortcode_column_thumbnails_data', '_thz_add_column_images');

**Comment by danyj** [comment]
this is but better but still 


	function _thz_add_column_images($column_thumbnails) {
		
		
		$column_thumbnails[ '3_5' ]['icon'] = THZFW_URI.'/extensions/builder/static/img/3_5.png';
		$column_thumbnails[ '4_5' ]['icon'] = THZFW_URI.'/extensions/builder/static/img/4_5.png';
	
	
		return $column_thumbnails ;
		
	}
	add_filter('fw_shortcode_column_thumbnails_data', '_thz_add_column_images');

**Comment by Delishable** [comment]
HOW DO I GET OFF YOUR NOTIFICATIONS LIST? I can't find any  
"unsubscribe" but I DON'T want anymore Unyson emials from  
anyone....you are blowing up my email account! Please remove me!!!  
Thank you, Bethany@delishable.net


Quoting Dan <notifications@github.com>:

**Comment by Delishable** [comment]
HOW DO I GET OFF YOUR NOTIFICATIONS LIST? I can't find any  
"unsubscribe" but I DON'T want anymore Unyson emials from  
anyone....you are blowing up my email account! Please remove me!!!  
Thank you, Bethany@delishable.net


Quoting Dan <notifications@github.com>:

**Comment by danyj** [comment]
@Delishable  please stop yelling here. Learn how to use git or dont use it at all , 
here is how to unsubscribe
http://prntscr.com/8u82y3
