### ISSUE TITLE
Failed to access Github repository

### ISSUE THREAD

**Issue by Krystus** [ThemeFuse/Unyson#957]
Sometimes I get that error on clean WP installation. Why?

![zrzut ekranu 2015-10-22 o 10 30 37](https://cloud.githubusercontent.com/assets/15039636/10660547/032b3da0-78a8-11e5-9b26-01153948efa0.png)

**Comment by moldcraft** [comment]
Please try this https://github.com/ThemeFuse/Unyson/issues/884#issuecomment-149480766

or 

1. add here https://github.com/ThemeFuse/Unyson/blob/master/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L2401

    ```php
    fw_print($response);
    ```

2. open this url

    ```
    http://YOUR_SITE/wp-admin/admin.php?page=fw-extensions&sub-page=install&extension=slider
    ```

3. click on Install button

**Comment by Krystus** [comment]
@moldcraft now it's better!
