### ISSUE TITLE
Unyson Slider Extension Install "Error"

### ISSUE THREAD

**Issue by brunoriggs** [ThemeFuse/Unyson#959]
Dear,

When trying to install a slider extension, returns the "error" message and does not install. Have you seen cases like this? Can you help me?

**Comment by moldcraft** [comment]
Can you give a screenshot? "error" is not informative

Similar issue https://github.com/ThemeFuse/Unyson/issues/957#issuecomment-150150341

**Comment by brunoriggs** [comment]
Yes i can.

![erro_unyson](https://cloud.githubusercontent.com/assets/15251296/10677706/596836aa-78e4-11e5-80a9-0c971f7834b2.jpg)

**Comment by moldcraft** [comment]
Have you tried this https://github.com/ThemeFuse/Unyson/issues/957#issuecomment-150150341 ?
