### ISSUE TITLE
500 Internet error server

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#960]
When I installed Unyson for my client site, it showed Internal Server Error.
Just install and active Unyson, and this error appeared. I couldn't do anything unless removing Unyson plugin folder. 
I think this error come from hosting so let me know if you need these account. 
Thanks!

**Comment by moldcraft** [comment]
Please find apache error log and check if there is error from unyson files

**Comment by duongancol** [comment]
It shows  ssv3_payload_extractor-01rx7vrwxc.php startup in error_log

**Comment by duongancol** [comment]
I had to disable all plugins, so I could install and active Unyson and extensions but when I imported demo content, this error appeared again, any ideas?, it's very headache.

**Comment by moldcraft** [comment]
Can you copy/paste here the latest lines from your error log or make a screenshot?

**Comment by duongancol** [comment]
All of it here: 
1445374815: /hermes/bosnaweb04a/b761/ipg.trioroussocom/fr/ssv3_payload_extractor-01rx7vrwxc.php startup

**Comment by moldcraft** [comment]
Very strange file name `ssv3_payload_extractor-01rx7vrwxc.php`
usually such files can be found on hacked sites.

... I need FTP access and the steps to reproduce the problem, I will debug the code to find the error.

**Comment by duongancol** [comment]
I did send an email for you. Let me know if you need other information. Thanks!

**Comment by moldcraft** [comment]
I can't find apache error log. That `error_log` that is there is weird, it has only one line.

I don't have time to install demo, debug the code (sorry, that I said below that I will debug the code). I need urgently to finish the Backup extension.

Please ask your hosting support, where is apache error log. If it's 500 Internal Server Error, there must be a error message somewhere.

**Comment by duongancol** [comment]
I will do. 
I got new issues from my customer everyday about Backup and Demo Import. So I hope the new version will work better. Let me know if you need somebody to test.

**Comment by danyj** [comment]
@duongancol   yes bud here is test , 
https://github.com/ThemeFuse/Unyson/issues/882#issuecomment-150221459

I am backed up right now and cant get to it till Monday .

**Comment by duongancol** [comment]
@danyj ok mate
@moldcraft I sent you the apache log, I'm not sure it's right but it shows empty. 
I know you're busy however I really need your help. They bought my theme and couldn't use it because of Unyson. If the problem cause by the hosting , I need to know to advice them to move to other hosting providers

**Comment by moldcraft** [comment]
@duongancol I added [here](https://github.com/ThemeFuse/Unyson/blob/510095425962bdf82facfc84c3e48f52ad6fcd52/framework/core/components/extensions.php#L475)

```php
fw_print($extension_name);
```

and it showed this 

![](https://static.md/89b5f6009d5ec17bf5764440592e32e0.png)

Then after trying to reach that `fw-booking` extension, the site showed an error message instead of `500 Page ...`

```
Parse error: syntax error, unexpected '[', expecting ',' or ';' in /.../wp-content/plugins/ht_booking/extensions/fw-booking/includes/post-tables.php on line 75
```

that line is

```php
echo fw_get_db_post_option($id,'c_adult',array(array('c_adult'=> '0')))[0];
```

That is a PHP 5.4 feature http://stackoverflow.com/a/10482105/1794248 that must not be used in WP because WP must be compatible with 5.2 https://wordpress.org/about/requirements/ *Oh, they changed the requirements to 5.6, at the time we started Unyson it was 5.2. Anyway, there is phrase about 5.2: "WordPress also works with PHP 5.2.4+"*

On your hosting is PHP 5.3

![](https://static.md/b986e59efa303ebbc1f26e8be585f1f0.png)

I commented that line in code and the site works now.

**Comment by duongancol** [comment]
Thank @moldcraft . It works. So we should edit the array to compatible with php 5.2 or should advice the user to increase PHP version?

**Comment by moldcraft** [comment]
make the code compatible with 5.2

**Comment by danyj** [comment]
@duongancol  just use temp vars , is always safer,

**Comment by duongancol** [comment]
ok thank you guys

**Comment by wirdfire** [comment]
Hey guys i am having this same problem in 2023. Unyson is not able to import or install demo content is there something i can do to have this solved? client is on my neck pls
