### ISSUE TITLE
Multi-picker unnecessary double coding suggestion needed

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#962]
I have a multi picker with 5 selects , 

	'choices' => array(
		'none'      => __('None', 'fw'),
		'singleline'      => __('Single line', 'fw'),
		'doubleline'      => __('Double line', 'fw'),
		'shadowline'      => __('Shadow line', 'fw'),
		'multiline'      => __('Multiline', 'fw'),
	)

from those 5 selects 4    use same 3 options , color , size , width 
the None   does not need any 

Because of that one I have to write same set of options for each of the remaining 4. Is there any way to avoid this  unnecessary extra coding?

**Comment by moldcraft** [comment]
Unfortunately, nope

https://github.com/ThemeFuse/Unyson/issues/41

**Comment by danyj** [comment]
darn. thnx bud
