### ISSUE TITLE
Admin elements are not using Admin Color Scheme colors

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#963]
I figured that changing the admin theme makes the save settings button look bad so I think we should remove the styling and class for it.

For now, I need to remove the class `submit-button-save` from save settings button, how can I do that please?

Thank you.

**Comment by moldcraft** [comment]
> changing the admin theme

What is admin theme?

> I need to remove the class `submit-button-save`

It is used https://github.com/ThemeFuse/Unyson/blob/3abd0aaed8aa74badd32a0d1e7ed70bf12ab994c/framework/static/css/backend-options.css#L611-L623

----

Can you give a screenshot to show how it looks bad?

**Comment by thednp** [comment]
Go to your profile in admin, select another color theme, and see the theme options again. This is an example on how it looks like with midnight color theme.

![save_button](https://cloud.githubusercontent.com/assets/6761246/10687284/98aa81b6-7974-11e5-895c-e0230897c3cd.jpg)

**Comment by moldcraft** [comment]
At the moment I did this fast fix https://github.com/ThemeFuse/Unyson/commit/4264e024eb14572445bcfb0dd692602a05880f2c

Later (when we will have time) we will use this class https://static.md/26f0308dfbead78375da3c1caab02651.png

**Comment by thednp** [comment]
Excellent. Closing down.

**Comment by moldcraft** [comment]
I'll keep this open to not forget about this feature and close it when it will be fixed

**Comment by thednp** [comment]
`border-color: transparent` looks more consistent :)

**Comment by thednp** [comment]
Done. Please check
https://github.com/ThemeFuse/Unyson/pull/966
