### ISSUE TITLE
Backup extension problem

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#965]
Hello!

After upgrading Backup extension it is impossible to download created demo install, when i click on "download" link i get following https://yadi.sk/i/-L-0wtkBjwVC8

**Comment by llemurya** [comment]
@WPJobs can you send at dev-team@unyson.io the ftp details and the user details in order to test this bug, because I tested on two WordPress instances and it works. I am waiting for your response.

**Comment by WPJobs** [comment]
@llemurya unfortunatelly i tested this on local server, add in your wp-config.php WP_DEBUG_DISPLAY constant, e.g.:

define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', true);

**Comment by sonnnaht** [comment]
I also encountered this problem.
I do not know what to do?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/882

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
