### ISSUE TITLE
Is it possible to overwrite form builder fields?

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#967]
I'm trying to overwrite the default text field/ I've created a **view.php** in:

*framework-customizations\extensions\forms\includes\option-types\form-builder\items\text\*

...but it doesn't seem to overwrite the default one.

**Comment by moldcraft** [comment]
You can [exclude an item type](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/e07cd70ea1ea8a0179078ba6be4d616c9bc732c5/includes/option-types/builder/extends/class-fw-option-type-builder.php#L114) (prevent it to be loaded).

Then create your own `{your_prefix}_text` form item type and [register it](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/aad168755b2215bc6357728f6845588a01d52852/includes/option-types/form-builder/items/text/class-fw-option-type-form-builder-item-text.php#L420)

```php
function _action_theme_include_custom_option_types() {
    if (fw_ext('forms')) {
        require_once '.../path/to/your/item-type/...php';
    }
}
add_action('fw_option_types_init', '_action_theme_include_custom_option_types');
```

**Comment by pe6o** [comment]
I just saw this in the documentation:

**Form Fields** - Frontend form fields views can be customized in **framework-customizations/extensions/forms/form-builder/items/{item-type}/views/view.php**. 
All built-in form builder item types can be found in **framework/extensions/forms/includes/option-types/form-builder/items/** directory.

What is the difference with the above solution?

**Comment by moldcraft** [comment]
I thought you want to overwrite the entire item type (to change it's logic and options). If only view, use the solution from docs.

**Comment by diableroua** [comment]
Hi!
How I can exclude an item type from the folder of theme, without changing a code in the folder of  framework?
