### ISSUE TITLE
Fatal error with get_declared_URI() when you edit a quiz from backend

### ISSUE THREAD

**Issue by antoniomangiacapra** [ThemeFuse/Unyson#969]
Hi,
I am one of the guys behind Woffice, one of our customers has signaled me this error:
```
Fatal error: Call to a member function get_declared_URI() on a non-object in .../wp-content/plugins/unyson/framework/extensions/learning/extensions/learning-quiz/includes/option-types/quiz-builder/items/true-false/class-fw-option-type-quiz-builder-item-true-false.php on line 35
```

I guided him doing some customization about next/previous link of courses, I think that is not connected with this issue.

I am waiting for your advices.
Thank you so much.

**Comment by moldcraft** [comment]
There is [nothing on line 35](https://github.com/ThemeFuse/Unyson-Learning-Extension/blob/38d8cde944212986cd95ff853ebb7ce6efcbaed6/extensions/learning-quiz/includes/option-types/quiz-builder/items/true-false/class-fw-option-type-quiz-builder-item-true-false.php#L35)

This was already fixed https://github.com/ThemeFuse/Unyson-Learning-Extension/issues/6

Make sure the customer has extensions up to date.
