### ISSUE TITLE
auto-install/database.txt points to localhost

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#970]
Clients complain that the image URLs in after 1 click install point to localhost/directory/

Is this how it should be?

**Comment by moldcraft** [comment]
Sorry, current Backup extension is buggy.

We are working on Backup v2 and it should be done in a few days.

**Comment by pe6o** [comment]
So currently all image urls point to the site where the demo installation is created?

**Comment by llemurya** [comment]
@pe6o try to see in the WordPress Settings->General the Site url, if is `http://localhost` change it to your site url , hope this helps, see this [printscreen](https://static.md/2740e131ef6af5b43560c07bcb6ea490.png).

**Comment by llemurya** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)
