### ISSUE TITLE
[error] strange error when saving a multi-select option with required attribute

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#971]
Setting `'attr' => array('required' => 'required')` for a `'type'       => 'multi-select',` option, with blank value (none-selected) throws this error

```
An invalid form control with name='fw_options[demo_multi_select_posts_2]' is not focusable.
```

I think we should be able to make all option types able to handle `required`, because most users forget stuff.

**Comment by moldcraft** [comment]
> I think we should be able to make all option types able to handle `required`, because most users forget stuff.

I don't agree. I prefer the idea: The user doesn't care about all your huge options panel, especially if it's a beginner, and your theme should work with any option values, you should assume that the user selected something wrong, not to force it to fill all the required options. That way the theme is easier to use and will always work, even if a dumb user will configure everything wrong.

Also required options are not compatible with hidden elements https://github.com/ThemeFuse/Unyson/issues/788#issuecomment-129473388

**Comment by moldcraft** [comment]
I will try to reproduce the `An invalid form control ...` error later

**Comment by thednp** [comment]
I think it's the same thing as the @danyj. 
Closing this down.
