### ISSUE TITLE
Setting option width for html field?

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#972]
I need to create an HTML field for some instructions. I tried both `'width' => 'large'` and `'attr' => array('data-width-type'=>'large')` with no effect (I also tried `full` value). Can you please share some info? Also please update info in that.

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/options/built-in-option-types.html#html

**Comment by thednp** [comment]
That is very confusing, that's why I thought I should better ask. Please update documentation to make it clear:

```
'my_option' = array(
  'type' => 'html-full'
)
```

Thanks again for the quick reply.
