### ISSUE TITLE
MySQL server has gone away error page builder

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#973]
I have page builder with 8 sections , each 4 columns , 
than I add tabs shortcode outside a section
with 1 tab we are ok , adding second tab I get 

    MySQL server has gone away error

moving tab inside any of the sections and we are ok again. 

I cant nail the issue since the error is huge , 2615 KB and no actual line 

http://prntscr.com/8v5rkf

I see only partial issue with something that is trying to go in DB 

WHERE `post_id` = 3637 AND `meta_key` = 'fw_options' made by post_preview, wp_create_post_autosave, wp_update_post, wp_insert_post, do_action('save_post'), call_user_func_array, _FW_Component_Backend->_action_save_post, fw_set_db_post_option, do_action('fw_post_options_update'), call_user_func_array, FW_Extension_Page_Builder->_action_fw_post_options_update, wp_update_post, wp_insert_post, do_action('save_post'), call_user_func_array, _FW_Component_Backend->_action_save_post, fw_set_db_post_option, FW_WP_Meta::set, fw_update_metadata

**Comment by moldcraft** [comment]
Related/same problem https://github.com/ThemeFuse/Unyson/issues/899#issuecomment-144645118

This will be the solution https://github.com/ThemeFuse/Unyson/issues/838

**Comment by danyj** [comment]
so in short I am hitting the DB limit, 
just confirmed by copying 2 sections , so is not connected to tabs at all but to the limit. 

is this going to be worked on after backup ? I am not in rush as of now just asking.

**Comment by danyj** [comment]
at the moment page like this http://thefoxwp.com/icon-boxes/ is not doable at all with builder because of the limit. not saying I want that,  just comparing the size.

**Comment by moldcraft** [comment]
Yes, right after backup I will start working on proxy option-type.
