### ISSUE TITLE
Do we have link option type

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#974]
Do we have something similar to this 

http://prntscr.com/8v98o4
http://prntscr.com/8v9766

where we can select existing content link ? Or do you have a snippet that I could use to make an option like that.

**Comment by c0sm1n87** [comment]
I use the example provided by @moldcraft here : https://github.com/ThemeFuse/Unyson/issues/224

I modified it a bit, but not much.

ps: don't forget to remove the post_per_page attribute here so you get ALL URLS instead of the general settings

    private function get_posts($post_type)
    {
        return get_posts(
            array(
                'post_type' => $post_type,
                'post_status' => 'publish'
                ));
    }

**Comment by puyaalexxx** [comment]
Hi! We havent such a option but you can do it for yourself , use a simple popup with specific options inside (http://manual.unyson.io/en/latest/options/built-in-option-types.html)

**Comment by danyj** [comment]
@c0sm1n87  thnx bud , that will work.
