### ISSUE TITLE
Cannot set HTML5 field types for text input option to enable form validation

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#975]
We need some sort of validation for URL, mail, number, and the best so far there is, is the HTML5 standard fields:

``` html
<input type="email" />
<input type="url" />
<input type="number" />
```

So we need a way to be able to add this kind of option settings

``` php
'attr' => array( 'type' => 'url')
'attr' => array( 'type' => 'number')
'attr' => array( 'type' => 'email')
```

**Comment by GheorgheP** [comment]
The type of the option is a special attribute and I don't think adding dynamic types is a good idea.

Also, for your specific case is just few lines of code to make a new option type with your specific input type:

```
class FW_Option_Type_URL extends FW_Option_Type_Text {
	public function get_type() {
		return 'url';
	}

	protected function _render( $id, $option, $data ) {
		$option['attr']['value'] = (string) $data['value'];

		return '<input ' . fw_attr_to_html( $option['attr'] ) . ' type="url" />';
	}
}

function _action_register_url_option_type() {
	FW_Option_Type::register( 'FW_Option_Type_URL', 'url' );
}

add_action( 'fw_option_types_init', '_action_register_url_option_type' );
```

And it remains same as the text input.

Also do not forget, the HTML 5 inputs validators don't have a pretty good design also is hard to change the validation message, also keeping the multilingual compatibility.
https://static.md/d21c8458b42c499b9709e7d359d5b741.png
