### ISSUE TITLE
Combining  addable-option and multi in to custom option type 

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#976]
@moldcraft  sorry but I cant get this one right at all , just confuses me completely. 
I made several option types but combo between these 2 is just mind bugling. 

I need to create addable  option that   adds several  options at once, 

for starters I try just with color and checkbox but cant get it to listen.  Adding works ok but saving is a no. http://prntscr.com/8vkne8   , the thing is that it must start with the add button only , not preset, so I must do this when setting the option

	'testadd' => array(
		'type' => 'thz-test-add',
		'value' => array(),
		'label' => __('Test', 'fw'),
	),

this is the view 

	<?php
		echo fw()->backend->option_type( 'addable-option' )->render(
			$id,
				array(
						'label' => false,
						'desc'  => false,
						'value' => $option['value'],
						'option' => array( 
							'type' => 'multi',
							'inner-options' => array(
								'inset' => array( 
									'type' => 'checkbox',
									'value' => false,
									'label' => __('Inset','fw'),
								),
	
								'shadow-color' => array( 
									'type' => 'rgba-color-picker',
									'value' => '#ff6600',
									'label' => __('Shadow color','fw'),
								),
							),
									
					 ),
	
				),
				array(
					'value' => $data['value'],
					'id_prefix' => $option['attr']['id'] .'-',
					'name_prefix' => $option['attr']['name'],
				)
		);
	?>

and this one is 100% wrong but I cant get it right 

	/**
	 * @internal
	 */
	protected function _get_value_from_input($option, $input_value)
	{
		if (!is_array($input_value)) {
			return $option['value'];
		}

		$value = $option['value'];

		foreach ($option['value'] as $key => $val){

			if (isset($input_value[$key])) {

				$value[$key] = $input_value[$key];
			}
		}

		return $value;

	}

    /**
     * @internal
     */
    protected function _get_defaults()
    {

        return array(
		 'value' => array(
		 	'inset' => false,
			'shadow-color' =>''
		 )
        );
    }

thing is I dont know what exactly the input_value  is returning in this case so not sure what to look for . 

Any help is appreciated!

**Comment by danyj** [comment]
got it, was missing id in data

**Comment by thednp** [comment]
Where were you missing it?

**Comment by danyj** [comment]
I forgot that addable is first and multi is second , 

so that should have been 


	<?php
		echo fw()->backend->option_type( 'addable-option' )->render(
			'addablename',
				array(
						'label' => false,
						'desc'  => false,
						'value' => $option['value'],
						'option' => array( 
							'type' => 'multi',
							'inner-options' => array(
								// inner options here
							),
	
					 ),
	
				),
				array(
					'value' => fw_akg('addablename',$data['value']),
					'id_prefix' => $option['attr']['id'] .'-',
					'name_prefix' => $option['attr']['name'],
				)
		);
	?>


and other  methods 


	/**
	 * @internal
	 */
	protected function _get_value_from_input($option, $input_value)
	{
		
		if (!is_array($input_value)) {
			return $option['value'];
		}
		
		$value = $input_value;

		
		return $value;

	}

    /**
     * @internal
     */
    protected function _get_defaults()
    {

        return array(
			'value' => array(
				'addablename' => array()
			)
			
        );
    }

**Comment by thednp** [comment]
Thanks for the answer. I am also after custom options. Do you happen to know how to unwrap the inner-options using the core coding?

**Comment by danyj** [comment]
you dont have to , just define them ,   multi is taking care of that , when you save they will be there

**Comment by thednp** [comment]
Yes I do, I want those options to get inline and using a `fw-col-sm-5` or similar class.

**Comment by danyj** [comment]
I dont folow , where od you want the output ?

this will be an option with array as value so just use 


      fw_akg('inneroption',$option_name),

**Comment by thednp** [comment]
I mean for the back-end `_render` function, I need the `multi` option type to act like a container as it comes to rendering, so that the `inner-functions` don't use their default view, but a custom view. But I think I partly answered my question: I should use custom templates for each inner option then.
