### ISSUE TITLE
Unyson deactivates extensions (again)

### ISSUE THREAD

**Issue by darwinteam** [ThemeFuse/Unyson#978]
Lots of users reported Unyson deactivating it's extensions again. Please fix. Thanks.

**Comment by danyj** [comment]
do they  all run latest unyson version ?

**Comment by darwinteam** [comment]
Version 2.4.9

**Comment by danyj** [comment]
please try to give as much details as possible @moldcraft  is working hard on backup since few days so lining up ;

wp version 
php version 
addition plugins
hosting environment

would get us all much farther than just guessing where the issue might be.

**Comment by moldcraft** [comment]
deactivating or uninstalling?

**Comment by moldcraft** [comment]
Try to reproduce the problem with these steps https://github.com/ThemeFuse/Unyson/issues/263#issuecomment-131184290

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/263#ref-commit-a12ee0f
