### ISSUE TITLE
Unable to resize video from Height and width settings

### ISSUE THREAD

**Issue by WWS1** [ThemeFuse/Unyson#979]
Since plugin update today the video size height and width settings do not appear to work and sizes appear fixed

**Comment by llemurya** [comment]
@WWS1 please give more details about issue in what extension you have this problem.I am waiting your response.

**Comment by WWS1** [comment]
Thank you for your response.

 

I have added a video to a page using the page builder and used the media elements tab to add a video from YouTube.

I set the Height and width to 300px and height to 200px and everything was fine until I applied the updated unyson extensions on 27th October and now the size of the video on the webpage is now far larger than the settings applied to the unyson page builder and does not change whatever sizes I try to apply in the media elements video popup when they are saved and the page is updated. The current size is set as shown in this email and the website and page is http://www.rachelsavine.co.uk homepage bottom left video if you would care to take a look.

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by llemurya** [comment]
@WWS1 I tested the plugin with the last version and it works please see this [video](https://youtu.be/ze3doubTgUI) as a proof. Maybe it is from the other plugins I see that you have installed     `youtube-embed-plus` plugin.Please verify and give us an answer.

**Comment by WWS1** [comment]
Thank you for your reply I have disabled the YouTube-embed-plus plugin as suggested but this has made no difference, I have cleared the browser cache just in case and the video is still oversized I am currently working on another site and will see what happens with that one and if necessary I will re do the problematic page incase there is a coding issue and will let you know how I get on but I do really appreciate your time spent on this.

Thank you. 

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by WWS1** [comment]
I have been working on this today and it appears that Unyson and Foogallery conflict and when both plugins are installed unyson will not load extensions and shows a white box  containing ERROR in red if Foogallery is deactivated the Unyson extensions download and activate correctly hope this helps and hope this can be sorted as I require both plugins.

 

Thank you once again it is much appreciated.

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by llemurya** [comment]
@WWS1 I tested Unyson with Foogallery plugin and they work well, please give us more details how to reproduce this bug. Thanks.

**Comment by WWS1** [comment]
This issue is not about resizing video it is a conflict between foo Gallery and Unyson if both plugins are activated and you then try to add Unyson extensions a white box showing "ERROR" message appears and extensions are not downloaded or activated if however FOO gallery is deactivated and you try to add Unyson extensions they download and activate without problem. Once the extensions have been downloaded and you activate foo gallery again it all works fine. It is the download and activation of extensions which is the problem when foogallery activated 
Hope this helps

**Comment by llemurya** [comment]
@WWS1 yes I reproduced this bug, we will fix it. Thanks for bug reporting

**Comment by moldcraft** [comment]
The problem is in Foogallery plugin https://github.com/fooplugins/foogallery/blob/1.2.9/includes/admin/class-extensions.php#L34-L74

We will report that.

**Comment by moldcraft** [comment]
https://github.com/fooplugins/foogallery/issues/62#issuecomment-216838772

**Comment by moldcraft** [comment]
@WWS1 Please test https://github.com/fooplugins/foogallery/issues/62#issuecomment-217240476
