### ISSUE TITLE
Slider backend disappeared

### ISSUE THREAD

**Issue by libra3053** [ThemeFuse/Unyson#980]
Hi, for some reason the slides have disappeared from the back-end of my theme so I'm not able to edit the individual slides or add new ones. See the attached screenshot. It looks like it's being hidden in the plugin's css (as you can see in the screenshot), but if I adjust the css it shows up but nothing is clickable. I've tried disabling the child theme I'm using and that didn't seem to solve the problem so I don't believe it has anything to do with custom code I've added. Any ideas? Thanks!

![unyson-error](https://cloud.githubusercontent.com/assets/15351165/10773982/c405806e-7cbb-11e5-927e-9534c0b96697.jpg)

**Comment by libra3053** [comment]
I just went back to a restore point I made yesterday before all the plugin updates and recent changes I made this morning and it came back. So I started off be doing the plugin updates again, one by one, and it looks like the issue is being cause by updating the Unyson plugin. I guess for now I'm just going to continue using the old version, but if you have any thoughts on fixing this please let me know! Thanks!

**Comment by moldcraft** [comment]
I see in screenshot that you have updates available, why you are ignoring them?

This problem was fixed in the latest Slider extension release, just update the extensions.

**Comment by libra3053** [comment]
I don't know where in the screenshot you are seeing that updates are available?? All the plugins were up to date. Updating Unyson to the latest version is what caused it to break.

**Comment by libra3053** [comment]
Ahh I see... I wasn't ignoring the updates. Actually I did all the plugin updates which is what caused it to break. I didn't notice that there was one for the extension also. I see it now though. I will try that. Thanks!
