### ISSUE TITLE
Customizing typography-v2

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#982]
I see you've implemented my typography commit, cool. Now here's a quick question: how can I make those `subsets` and `styles` to be multi-selects please?

Why I ask? Because in my design idea, there is only one place to set the fonts: in the theme options page and no other place. I think having more than 2 webfonts loaded in a page is decreasing load speed considerably and the overall design is not very consistent as well.

**Comment by c0sm1n87** [comment]
Hello @thednp

Can you provide more information on what exactly are you trying to do? I think you ran into the problem I was facing (font wasn't enqueued properly due to styles). If this is the case let me know and I will show you how I "solved" this.  

Regards!

**Comment by thednp** [comment]
hi @c0sm1n87 I don't think it's the same issue, maybe you are talking about `variants` in the JSON and the `style` option type setting.

I am talking about making the `subsets` and the `style` selects to be `multiple="multiple"` and make the option type `typography-v2` work with multiple (array) values for those attributes.

**Comment by thednp** [comment]
I figured there was an `explode` in the PHP I had to do, closing this now.
