### ISSUE TITLE
How can I remove a population method of slide?

### ISSUE THREAD

**Issue by TrangDinhVan** [ThemeFuse/Unyson#983]
I just want to keep only one population method for slide only, how can I remove the others?

**Comment by llemurya** [comment]
@TrangDinhVan please read about this in our [documentation](http://manual.unyson.io/en/latest/extension/slider/index.html#configuration).If it helps, please close the issue or answer if something is not clear.

**Comment by TrangDinhVan** [comment]
Sorry, I mean the slider extension, and the thing I wonder is this: https://nimbus.everhelper.me/client/notes/share/316927/7KK1yPpJtwRThU3cHNgyqLGBaTCRB4lC/

**Comment by llemurya** [comment]
@TrangDinhVan please read the comments on this [issue](https://github.com/ThemeFuse/Unyson/issues/431) , the answer is in comments. If it help please close the issue. Thanks.

**Comment by duongancol** [comment]
@TrangDinhVan : it's here: https://github.com/ThemeFuse/Unyson/issues/391#issuecomment-84968569
