### ISSUE TITLE
Error in Translation Extension ?  Urgent

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#984]
Hello @moldcraft 
Found Error on woocommerce category page. 

![screenshot-alteration themographics com 2015-10-29 13-49-28](https://cloud.githubusercontent.com/assets/12461946/10813903/ec510258-7e43-11e5-9465-4cbba6c21f3a.jpg)

Need help Urgently.

Undefined property: FW_Extension_Translate_Terms::$lang_tag in /home/themographics/public_html/wordpress/alteration/wp-content/plugins/unyson/framework/extensions/translation/extensions/translate-terms/class-fw-extension-translate-terms.php on line 706

**Comment by llemurya** [comment]
@wpthemes786 can you send the ftp details to dev-team@unyson.io in order to investigate this bug. I am waiting for your response.

**Comment by wpthemes786** [comment]
@llemurya  Sorry its the client project and i don't have ftp detail yet. i just have wp backend detail.

The code that i am using to display translation switcher is : 

<?php if (function_exists('fw_ext_translation_get_frontend_active_language') && $show_translation == 'true' && $enable_language == 'on' ) {?>
       <div class="dropdown languages">
        <div aria-labelledby="languages" class="dropdown-menu languages">
         <?php echo fw_ext('translation')->frontend_language_switcher();?>
        </div>
        <button class="btn-dropdown btn-languages" type="button" id="languages" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
         <em class="fa fa-globe"></em>
         <span><?php esc_html_e('English','alteration');?></span>
         <em class="fa fa-caret-down"></em>
        </button>
        
       </div>
       <?php }?>

**Comment by llemurya** [comment]
@wpthemes786 I will try to reproduce this bug with woocommerce and I will give you an answer.

**Comment by llemurya** [comment]
@wpthemes786 I reproduced this bug , I will fix it and make a new version for translation extension.

**Comment by wpthemes786** [comment]
@llemurya  When will you make the new translation version. Kindly i need this to fix urgently

Many Thanks

**Comment by wpthemes786** [comment]
@llemurya Kindly tell us where is the issue so we can resolve it . Because we do not know when will you guys commit the translation extension.

Thanks Need urgent solution

**Comment by llemurya** [comment]
@wpthemes786 the issue was fixed, and the realease is in production you just make an update and say if everything work well. I am waiting for your response.

**Comment by wpthemes786** [comment]
Yes Issue Resolved. Many Thanks :+1:
