### ISSUE TITLE
[ERROR] When no menu set to primary or secondary 'slots', I get a cool notice

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#985]
```
Notice: Trying to get property of non-object in [site]\wp-content\plugins\unyson\framework\extensions\translation\extensions\translate-menus\class-fw-extension-translate-menus.php on line 59
```

**Comment by llemurya** [comment]
@thednp you have Translation Extension active?

**Comment by llemurya** [comment]
@thednp I tried to reproduce this bug , but for me work please give me more details how to reproduce this bug in order to fix it .Thanks. I am waiting for your response.

**Comment by thednp** [comment]
Hi. Sorry for the short delay.

The extension is active. Possible steps to reproduce: 
* install a clean wp with it's [sample data](http://codex.wordpress.org/Theme_Unit_Test) then install 
* install UNYSON plugin, scratch theme and Translations + Page Builder extensions (so far you should have what I have)
* to get to my problem you would have to install a theme that uses a LESS compiler (I use a variation of [this](http://jbst.eu/)), activate the theme go to customizer, change menus, on save you should see the error notice somewhere in the navbar.

**Comment by llemurya** [comment]
@thednp this theme from `jbst.eu` have an custom `nav_walker` ?

**Comment by thednp** [comment]
@llemurya , yes it does have. ThemeCheck spots no issue regarding languages related and/or navwalker, however there is always this issue of multiple text domains..

```
The domains found are jamedo-bootstrap-start-theme,woothemes,jigoshop,cmb,options_framework_theme,crblueprint,wpless2css
```

Right now I think that's why the Translations extension fails on that line.

**Comment by thednp** [comment]
I also think your translation extension documentation should include a warning about multiple domain extensions, themes, plugins. IMO
