### ISSUE TITLE
[optimization suggestion ] Double events in color picker

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#986]
@moldcraft  I am building something that requires color picker , so I used iris , and our rgba picker as base to create my script . 

just figured out that all pickers  in iris are actual UI sliders so this events trigger here 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/static/js/scripts.js#L218-L223

is enough , 

this double fires the change 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/static/js/scripts.js#L110-L115

figured this out by auto populating 5  color pickers via 

    ...on('my:iris:event',...
    colorInput.iris('color', value);

and was getting double events so iris vas repopulating , you might want to look at it

**Comment by thednp** [comment]
Did you filter for `your-option-type:not-initialized` to target your JS function? This is what this sounds to me.

**Comment by danyj** [comment]
my script  has nothing to do with  wp or unyson. I am just using iris script

**Comment by thednp** [comment]
Then why don't you ask or look for support at source?

**Comment by danyj** [comment]
@thednp you do uderstannd that I am not asking but advising right?

**Comment by thednp** [comment]
OK now, I see your point. I did some work on event handling lately, so I'm only trying to figure out the context (I don't use Unyson or WP colorpickers).

**Comment by danyj** [comment]
@thednp who ever made the rgba color picker used this script 
http://pluto.kiwi.nz/2014/07/how-to-add-a-color-control-with-alphaopacity-to-the-wordpress-theme-customizer/

than added trigger events 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/static/js/scripts.js#L218-L223

https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/rgba-color-picker/static/js/scripts.js#L110-L115

in script I am working on I also needed rgba iris , so I used Unyson iris script as a base , 

and on those trigger events I saw double event trigger. 
since the UI slider change triggers always , one of those events , ( iris change )  is to much, 

makes sense now ?

**Comment by danyj** [comment]
or think of it like this 

if you do anything on   fw:option-type:rgba-color-picker:change  like 

	$('.my_elelement').on('fw:option-type:rgba-color-picker:change ',function (){
		
		// do something
		conslole.log('change');
		
	});

you get 2 logs instead of one,  and if anyone needs to read color changes in order to repopulate something it will do this twice ,  in my script I populated 5 color pickers when  you click on element and instead 5 I get 10 populations.

**Comment by thednp** [comment]
Now it does alot more sense, thank you. Please try on IE8-9 if this double fires and let me know.
