### ISSUE TITLE
Add ability to add a class to column Layout Elements

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#987]
I think it would be a good idea to have the ability to assign a class to column Layout Elements.

This would help give greater control over layout elements to create bespoke layouts and designs.

**Comment by moldcraft** [comment]
You can:

* Add an option in your shortcode for css class
* Use [this solution](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head) to generate ids for shortcodes
