### ISSUE TITLE
$atts displaying just 1 or 0 instead of the value in Unyson Builder shortcode view.php file

### ISSUE THREAD

**Issue by zohaib87** [ThemeFuse/Unyson#988]
Hi, 

I am working on some shortcodes but have problem in one other are working fine. $atts displaying just 1 or 0 instead of the real value in Unyson Builder shortcode view.php file. really don't understand whats the problem. field type is set to 'select'

thank you!

**Comment by danyj** [comment]
do 

    fw_print($atts);

and it will make sense 

the way to use it  is

    echo   $atts['option_name'];

**Comment by zohaib87** [comment]
that's how i am using it, the value input is 1488_Contact-form-1 and i am just getting 1.

**Comment by danyj** [comment]
do this 

   fw_print($atts);

and post here, also advise where you are using it

**Comment by zohaib87** [comment]
by doing fw_print($atts); I gets this:
array
(
['cf7_title'] => 0
)
i was justbuiding shortcodes to detect and list gravity forms and contact form 7.. gravity form shortcode is working perfectly.

**Comment by zohaib87** [comment]
well, I think i should leave CF7. GF is working and who will need another contact form plugin when there is a good built in contact form there. 
Thank you so much for your help!

**Comment by llemurya** [comment]
@zohaib87 In the unyson already exists [forms extension](http://manual.unyson.io/en/latest/extension/forms/index.html#content) . Please take a look ,maybe you will use it.

**Comment by zohaib87** [comment]
@llemurya yes, Its a great one. Thank you!
