### ISSUE TITLE
RTL theme settings page looks unpolished

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#989]
Not that I personally care much about it, but have a look or test yourself
![image](https://cloud.githubusercontent.com/assets/6761246/10897109/0a0a51ec-81c7-11e5-993e-3c60c89dfb62.png)

PS: I will do a commit on this soon, but please advise what file would be used for that, or create a new file to commit to.

**Comment by moldcraft** [comment]
We made some RTL fixes but I didn't found time to commit the changes. I will try in a few days to do the commit (the fixes should be in the next release).

**Comment by moldcraft** [comment]
I made the commit. I think it's not perfect and can be improved. You are free to make pull requests

**Comment by thednp** [comment]
That's alot better! 

Now, the separator in the header is not shown, I can't figure out why, seems it's not css issue.
