### ISSUE TITLE
Create Custom Section and Column Shortcodes

### ISSUE THREAD

**Issue by blackmekemeke** [ThemeFuse/Unyson#99]
How to create custom section and column shortcodes and disable built in one, thanks.

**Comment by SynapsisIT** [comment]
Modifying the existing builder will mean we have to lose the bootstrap grid system, at times we do not want to lose something we just want to add something extra.

I can see lots of cases where the current grid system would suit just great and other cases where i would need/want to use a flexible box structure of the layout. Modifying the existing builder to adapt it to the flexible box structure would mean renouncing of the bootstrap grid structure, which would not be the case.

So is there a way or a documentation how we can build an "additional" columns shortcode without loosing what unyson has to offer already?

**Comment by assigeo** [comment]
The problem definition is simple.
We want to **render custom rows** (.fw-main-row) inside the "fw-page-builder-content" div.
And we want custom rows - that we created - to appear in page builder as custom-sections (e.g. testimonials-section). 

I guess that this can be created with a "x-section" shortcode.
So, whenever we want to have a custom row/section, we must create a new "x-section"  @shortcode.

The view.php file may be written:
`<section class="fw-main-row">
    <div class="x-section">
		<?php echo do_shortcode( $content ); ?>
    </div>
</section>` 

@rockalife 
@moldcraft

**Comment by moldcraft** [comment]
@SynapsisIT @assigeo The section and row shortcodes were written a long time ago, in order to give you a solution I must inspect the code, remember how it works and figure out how to implement what you are requesting. So we are almost at the same level, you can inspect and debug the code yourself to figure out a solution. _(I have other tasks to do, sorry)_
