### ISSUE TITLE
WP editor problem with new wordpress version

### ISSUE THREAD

**Issue by khairulalamruet** [ThemeFuse/Unyson#990]
Hi,
The framework is really great and I have used couple of my products with this framework. But now-a-day this is shown an error with "Developer" plugin, this comes from JS of WP Editor.
![e2](https://cloud.githubusercontent.com/assets/6226235/10901632/4e8a365c-821c-11e5-9764-49d5b2f0a5b5.png)
![e1](https://cloud.githubusercontent.com/assets/6226235/10901633/55dc3040-821c-11e5-8708-9cd006bdecd0.png)

Thanks

**Comment by llemurya** [comment]
@khairulalamruet this error show only if `unyson` is enabled or this is the WordPress error? Please check with disabled `unyson` if you get the same error.I am waiting for your response.

**Comment by khairulalamruet** [comment]
Yes, I have tested with disable Unyson but same error shwon. When I active the wp-editor type this error shown then.

Thanks

**Comment by llemurya** [comment]
If you have the error when the Unyson is disabled, maybe the error comes from other plugins , please verify and report the bug to the plugins developers, because I have installed the WordPress v4.3.1 with Unyson enabled and I don't have error message. I am wainting for your response.

**Comment by khairulalamruet** [comment]
The bug did not show all time, when you will use WP-Editor of Unyson then you can see this bug. I have installed fresh copy of Wordpress no plugin at all, but see this problem.

Thanks

**Comment by llemurya** [comment]
@khairulalamruet please explain more detailed , because it is not clear , you said that the error appear if you have an fresh WordPress install without any plugins? Please give us the steps how to reproduce this bug, and where you use the WP Editor options type?

**Comment by khairulalamruet** [comment]
OK. When I have install your plugin there showing no error, but when I use your plugin type "wp-editor" then it shown the error. I am sending you a screenshot below: 
![e3](https://cloud.githubusercontent.com/assets/6226235/10906875/4e61b6ae-824f-11e5-806b-ab8277e23c0e.png)

Hope you are clear now.

Thanks

**Comment by llemurya** [comment]
@khairulalamruet sorry for the delay. I tried to reproduce this bug but I for me works , also I fixed another [bug](https://github.com/ThemeFuse/Unyson/issues/1039) with `wp-editor`.You can download the `Unyson` from github and test if this bugfix resolve your problem. I am waiting for your response.

**Comment by khairulalamruet** [comment]
Thank you for you support. I will check this today and let you know if I will face any problem again.

Thanks

**Comment by llemurya** [comment]
@khairulalamruet did you update to the latest version of Unyson? Please say if the error still remain. Thanks. I am waiting for your response.

**Comment by khairulalamruet** [comment]
Yes this have fixed. Thank you :)
