### ISSUE TITLE
[Question] how to remove fw css and replace with bootstrap row+column classes

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Unyson#991]
I'm using LESS to build CSS files for my theme and I very much want to use my own CSS.

* First I need to remove these 2 `fw-ext-builder-frontend-grid-css` and `fw-ext-forms-default-styles-css` because they're not needed
* because I remove the two, how can I change the classes, a simple template override would do?

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/922#issuecomment-146842773

Yes, a simple template override would do

**Comment by moldcraft** [comment]
TODO: Add in docs instructions "How to replace `.fw-` classes with bootstrap"

**Comment by thednp** [comment]
Thank you :)

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/extension/builder/index.html#changing-the-grid

**Comment by thednp** [comment]
Thanks again @moldcraft.
