### ISSUE TITLE
How To add Time Picker

### ISSUE THREAD

**Issue by aamirs332** [ThemeFuse/Unyson#993]
Hello, I want to add opening hours, i need to add Time Picker, Can you please help me how can i add Time picker for opening hours. Please have look on screenshot. Can you please help
![screenshot_3](https://cloud.githubusercontent.com/assets/5873187/10961794/208e1108-83b4-11e5-87d3-85a3e92b8d41.png)

Regards,

**Comment by aamirs332** [comment]
There is no option for Time picker.  http://manual.unyson.io/en/latest/options/built-in-option-types.html

**Comment by llemurya** [comment]
@aamirs332,@wpthemes786 in unyson are two option-types that are not documented, `datetime-picker` and `datetime-range`, please see this [video](https://youtu.be/k5dDtDbK4oM) to see how it works.Give us feedback if it helps or describe more detailed how you will to see the new option type.As soon as possible we will add the description to the documentation, for now if you will use it, please see the source code of these option types the parameters are described in comments. I am wainting for your response.

**Comment by aamirs332** [comment]
Thanks llemurya :+1: . I just need Time Picker. if you people can add standalone Time Picker option. it would be batter for me, otherwise i have to customized it for my own purpose.

**Comment by llemurya** [comment]
@aamirs332 you must set the next array to obtain only the time-picker
```php
'date-time-picker' => array(
				'type' => 'datetime-picker',
				'datetime-picker' => array(
					'datepicker' => false
				)
			)
```

**Comment by llemurya** [comment]
@aamirs332 this is the [printscreen](https://static.md/58479c4b56971af08d5a7618a3a6b4ac.png) how it looks like.

**Comment by aamirs332** [comment]
Thanks llemurya, but date is still there. :(
![screenshot_4](https://cloud.githubusercontent.com/assets/5873187/10966132/5f49fc1c-83d3-11e5-818a-495bdf1abf62.png)

**Comment by llemurya** [comment]
Yes I know that we date is still where, you want to be without date?

**Comment by llemurya** [comment]
Simple set the next parameters to obtain only time
```php
'date-time-picker' => array(
				'type' => 'datetime-picker',
				'datetime-picker' => array(
					'datepicker' => false,
					'format' => 'H:i'
				)
			)
```
The result will be the [next](https://static.md/3bf3f075364090dc665536a2f51d32ef.png).

**Comment by aamirs332** [comment]
Thanks, now ts working fine :+1:
