### ISSUE TITLE
Time option type in unyson ?

### ISSUE THREAD

**Issue by wpthemes786** [ThemeFuse/Unyson#994]
Hello @moldcraft 

I just want to know that is there any time option type in unyson like date option type.

Thanks

**Comment by danyj** [comment]
@wpthemes786  http://manual.unyson.io/en/latest/options/built-in-option-types.html#date-picker

**Comment by llemurya** [comment]
@wpthemes786 please see https://github.com/ThemeFuse/Unyson/issues/993

**Comment by wpthemes786** [comment]
@llemurya  Thanks for the reference,  but i just need time option not date along with time. just need time.

Thanks for your help

**Comment by llemurya** [comment]
@wpthemes786 see the comment in the #993, you will find the answer.
