### ISSUE TITLE
Theme settings aditional info

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson#996]
I need a filter for add a custom html in this position:
http://joxi.ru/8238nGWcKlXpAO
for example for docs, or other information.
Thanks.

**Comment by thednp** [comment]
Why not add a link into the admin bar? Or an entire menu:

* Theme settings
** Documentation
** About
** etc

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/blob/v2.4.17/framework/views/backend-settings-form.php#L90
