### ISSUE TITLE
How to enqueue script / style from shortcode static file based on shortcode parameter?

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#997]
Hello!

Is it possible to enqueue script or style from shortcode static file based on shortcode parameter? I mean something like this:

```
if( $atts['shortcode_param'] == 'foo') {
    wp_enqueue_style( 'style-foo');
} elseif( $atts['shortcode_param'] == 'bar' ) {
   wp_enqueue_style( 'style-bar');
}
```

thanks for advice :)

**Comment by moldcraft** [comment]
http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head
