### ISSUE TITLE
Range slider increments don't match up

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Unyson#998]
![image](https://cloud.githubusercontent.com/assets/4599099/10984941/2741512a-8415-11e5-8e80-960db35f1cef.png)

**Comment by llemurya** [comment]
@martinburdon you must set the next array.Don't forget about the step.
```php
'range-slider' => array(
				'type' => 'range-slider',
				'properties' => array(
					'min'=>1,
					'max'=>6,
					'step'=>0.1
				)
			),
```

**Comment by llemurya** [comment]
![image](https://static.md/256a623c4308fd544c0f89b369b78956.png)

**Comment by llemurya** [comment]
@martinburdon if you set the `grid_snap` parameter.and change the interval to `0.5`
```php
'range-slider' => array(
				'type' => 'range-slider',
				'properties' => array(
					'min' => 1,
					'max' => 6,
					'step' => 0.5,
					'grid_snap' => true
				)
			),
```
You will obtain the next result:
![image](https://static.md/9742c3792e16e7211fd40a6c84890a3b.png).
For more details you can read the answers for this issue https://github.com/ThemeFuse/Unyson/issues/512.
If it helps please close the issue. I hope this information help you.I am waiting for your response.

**Comment by martinburdon** [comment]
Thanks for your reply, I had the properties array set but not `grid_snap`, this has solved it.
Thank you.
