### ISSUE TITLE
[Question] How to add icon for extra added columns.

### ISSUE THREAD

**Issue by giathinh910** [ThemeFuse/Unyson#999]
Hi. I added more column layout from {theme}/framework-customizations/extensions/builder/config.php
Now I have this:
![screenshot_6](https://cloud.githubusercontent.com/assets/6775636/10988287/a3b6375e-846d-11e5-9ce2-a4441f225672.png).
How can I add icon for those added columns.
Thank you.

**Comment by llemurya** [comment]
@giathinh910 please watch this [video](https://youtu.be/3nLsvhLTyrI).It is the tutorial how to change the icon for custom column.

**Comment by moldcraft** [comment]
In the next version of the Shortcodes extension, the icons will be loaded from

```
extensions/shortcodes/column/thumbnails/{column_id}.png
```

**Comment by giathinh910** [comment]
Thank you very much.
